### ISSUE TITLE
is it possible to use custom similarity metrics? 

### ISSUE THREAD

**Issue by RonsenbergVI** [milvus-io/milvus#1001]
Hello,

I was interesting in using the library but my search space requires to give higher weights to some parts of the vector. Implementing a custom distance would solve the issue. Is is something that is documented?

thanks

**Comment by yamasite** [comment]
Hi,

Thanks for your question! Currently,  distance customization is not yet supported. However, this feature might be implemented in future versions. Stay tuned!

**Comment by henryclw** [comment]
I also have the same demand, part of my vector should have higher weight, my vector is binary vector, any updates or idea about this?
