### ISSUE TITLE
Returning nil explicitly if value evaluates to Nill

### ISSUE THREAD

**Issue by Biki-das** [milvus-io/milvus#10048]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Found a chunk of code which have return statement that evaluates to nil, now it is better to return nil as it improves the readability

### Expected Behavior

if err == nil {
    return err
}

The above is what it currently looks like

if err == nil {
    return nil
}

this is what it should be supposed to

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

**Comment by Biki-das** [comment]
@LoveEachDay could you please review this PR

**Comment by yhmo** [comment]
@Biki-das
It is a good suggestion. We encourage more people to participate in Milvus. It would be better if you can submit a pull request to improve it.

**Comment by Biki-das** [comment]
> @Biki-das
> It is a good suggestion. We encourage more people to participate in Milvus. It would be better if you can submit a pull request to improve it.

Ok working on it!
