### ISSUE TITLE
when pass params to tables via GET, offset and page_size could be set to empty string

### ISSUE THREAD

**Issue by liangliu** [milvus-io/milvus#1007]
Describe the bug
when pass params to tables via GET, offset and page_size could be set to empty string like **''**, and correct result returned 

Steps/Code to reproduce behavior

Expected behavior
those 2 params should be restricted to INT only

Environment details
Screenshots
Additional context

**Comment by BossZou** [comment]
I tried in my host machine. I found an interesting phenomenon. When I process 
```
response = rq.get("http://192.168.1.57:19121/tables?offset=0&page_size=''")
```
The status code is 400, message is `server=oatpp/0.19.11 code=400 description=Bad Request message=Invalid QUERY parameter 'page_size'. Expected type is 'Int64'`

But when I process
```
response = rq.get("http://192.168.1.57:19121/tables?offset=0&page_size=""")
```
The status code is OK.

**Comment by lganzzzo** [comment]
Hey guys, 

Please feel free to open issues in [oatpp](https://github.com/oatpp/oatpp) repo if you find it's an oatpp issue.

Thanks,
Leonid

**Comment by liangliu** [comment]
since there're default values for these 2 params now, pass '' to server could get normal response, close the issue now
