### ISSUE TITLE
'MemoryError' while pass super long string in params to tables API call via get

### ISSUE THREAD

**Issue by liangliu** [milvus-io/milvus#1008]
**Describe the bug**
'MemoryError' while pass super long string in params to tables API call via get

**Steps/Code to reproduce behavior**
**Expected behavior**
correct error message should return to the caller

**Environment details**
**Screenshots**
**Additional context**

**Comment by BossZou** [comment]
I found the statement is `res = requests.get(HOST + 'tables', params={'offset':'x' * 50000000000, 'page_size':922})`. And I tried in my host machine. I noticed `'x' * 50000000000` cost much time, May cause memory error here.

**Comment by liangliu** [comment]
verified
