### ISSUE TITLE
server down while pass super long names in table creation via rest API

### ISSUE THREAD

**Issue by liangliu** [milvus-io/milvus#1009]
**Describe the bug**
server down while pass super long names in table creation via rest API
like this: 

```
xname = 'x' * 500000
req = { 
    "table_name": xname,
    "dimension": 10,
    "index_file_size": 10,
    "metric_type": "L2"
    }
```
server shutdown after post this request from client

**Steps/Code to reproduce behavior**
**Expected behavior**
**Environment details**
**Screenshots**
**Additional context**

**Comment by BossZou** [comment]
I tried in host and all work well. You recommended to use latest docker images and try again.

**Comment by liangliu** [comment]
yeah, cannot reproduce after trying newer image.
Close this issue.
