### ISSUE TITLE
error message returned should updated since offset and page_size could be set to 0

### ISSUE THREAD

**Issue by liangliu** [milvus-io/milvus#1010]
**Describe the bug**
when pass negative number to offset/page_size and call tables API, the error message returned said these 2 params should bigger than 0, actually it could be set to 0 and the value is meaningful, also could get correct result.

the error message should be updated according to this

**Steps/Code to reproduce behavior**
**Expected behavior**
**Environment details**
**Screenshots**
**Additional context**

**Comment by BossZou** [comment]
I see. May the error message should be `Query param 'offset' or 'page_size' should equal or bigger than 0`

**Comment by liangliu** [comment]
verified
