### ISSUE TITLE
"Truth value of an array" errors; issues with Pandas compatibility

### ISSUE THREAD

**Issue by tb438** [milvus-io/milvus#1013]
**Describe the bug**
After following the examples exactly and replacing the dataloader with a simple Pandas CSV loader as well as Numpy loader, I am getting various error messages when trying to load vectors into the database. I am using a CSV file that has one row per line dimension 4680, length 25,000. I initially thought this might be related to float64 (the documentation specifically mentions float32), but after casting to float32 I still get erratic errors when trying to load vectors.

**Steps/Code to reproduce behavior**
```
vectors = pd.read_csv('largefile.csv', names=_COLUMNS[0], header=None)
vectors = vectors.astype('float32')
vectors = np.array(vectors)
print(vectors.head())
[5 rows x 4680 columns]
a      float32
b      float32
c      float32
d      float32
e      float32
        ...   
fwv    float32
fww    float32
fwx    float32
fwy    float32
fwz    float32

vector_ids = [id for id in range(25000)]
status, ids = milvus.insert(table_name=table_name, records=vectors, ids=vector_ids)
```

**Expected behavior**
Pandas is supposedly drop-in compatible with numpy ndarrays, and I've tried several permutations on this them including pandas.Dataframe.to_numpy, with no success. 

**Environment details**
- Quad Xeon w/ 8GB system memory
- Most recent Docker pull
- Most recent Milvus install
- Stock server_config.yaml from examples

**Screenshots**
This is the error I get whenever I convert the Pandas dataframe to numpy ndarray:
```
line 92, in main
    status, ids = milvus.insert(table_name=table_name, records=vectors, ids=vector_ids)
  File "/usr/local/lib/python3.7/dist-packages/milvus/client/grpc_client.py", line 578, in insert
    insert_param = Prepare.insert_param(table_name, records, partition_tag, ids)
  File "/usr/local/lib/python3.7/dist-packages/milvus/client/prepare.py", line 120, in insert_param
    if is_legal_array(vector):
  File "/usr/local/lib/python3.7/dist-packages/milvus/client/check.py", line 39, in is_legal_array
    if not array or \
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by lym777** [comment]
Before inserting  the vector， you can try 
`vectors  = vectors.tolist()`
The type of the vector should be a 2-dimensional list

**Comment by JinHai-CN** [comment]
Fixed.
