### ISSUE TITLE
[Bug]: requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.39/images/%24%7BIMAGE_REPO%7D/milvus-env:%24%7BIMAGE_ARCH%7D-%24%7BOS_NAME%7D-%24%7BDATE_VERSION%7D/json

### ISSUE THREAD

**Issue by ruoniler** [milvus-io/milvus#10153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

/usr/local/lib/python3.5/dist-packages/requests/__init__.py:104: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (2.3.0)/charset_normalizer (2.0.7) doesn't match a supported version!
  RequestsDependencyWarning)
docker pull jaegertracing/all-in-one:latest ...
docker pull minio/minio:RELEASE.2020-12-03T00-03-10Z ...
docker image "docker.io/bitnami/etcd:3.5.0-debian-10-r24" already exists.
docker pull apachepulsar/pulsar:2.7.3 ...
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.39/images/%24%7BIMAGE_REPO%7D/milvus-env:%24%7BIMAGE_ARCH%7D-%24%7BOS_NAME%7D-%24%7BDATE_VERSION%7D/json

During handling of the above exception, another exception occurred:

### Expected Behavior

Images can be collected normally for offline installation and deployment

### Steps To Reproduce

```markdown
1.pip3 install -r requirements.txt
2.python3 save_image.py --manifest ../../docker-compose.yml
```

### Environment

```markdown
- Milvus version:2.0.0
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Kylin-desktop
- CPU/Memory: FT2000 arrch64
- GPU: 
- Others:
```

**Comment by yanliang567** [comment]
looks like a 1.x issue, could you please help to take a look first? @yhmo 

/assign @yhmo

**Comment by ruoniler** [comment]
The milvus version is 2.0.0, not 1. X

**Comment by yhmo** [comment]
@ruoniler 
Is the save_image.py come from milvus bootcamp?

**Comment by ruoniler** [comment]
@yhmo 
No！This come from milvus-master/deployments/offline
