### ISSUE TITLE
[Bug]: Keep primary keys unique for all testcases

### ISSUE THREAD

**Issue by cydrain** [milvus-io/milvus#10174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Milvus has started to support hand-off and compaction, in some scenarios, one entity may exist in more than one segment. So we introduce search result duplication removal based on primary key in query node and proxy.
But now in some testcases, primary keys are not unique. After search result duplication removal based on primary key, the testcase will run fail.

### Expected Behavior

Keep primary keys unique for all testcases

**Comment by cydrain** [comment]
all failed cases:
[failcase.txt](https://github.com/milvus-io/milvus/files/7371234/failcase.txt)

**Comment by binbinlv** [comment]
Close it for PR merge.
