### ISSUE TITLE
No stdout when using locust and milvus

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#1020]
**Describe the bug**
No logger message displayed when using locust and import milvus into it

**Steps/Code to reproduce behavior**

**Expected behavior**

**Environment details**

**Screenshots**

**Additional context**

**Comment by BossZou** [comment]
Hello, did you slove it ?

**Comment by BossZou** [comment]
@del-zhenwu , has this issue been solved? I plan to close it soon.

**Comment by del-zhenwu** [comment]
close
