### ISSUE TITLE
[Bug]: Milvus search hangs when I restart milvus standalone docker

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#10248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. start milvus standalone docker by docker-compose
2. insert 1M 128d data
3. create index: sq8 nlist=4096
4. load collection
5. search is ok
6. docker compose down
7. docker compose up -d
8. search hang

### Expected Behavior

search works fine after restarting milvus

### Steps To Reproduce

```markdown
see "Current Behavior"
```

### Environment

```markdown
- Milvus version:2.0 rc7
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus v2.0.0rc7
- OS(Ubuntu or CentOS): mac
- CPU/Memory: 32GB
- GPU: 
- Others:
```

**Comment by zhuwenxing** [comment]
I tried the same test in rc7 with the same data size and param , but it behaves well.
How long has been between step 1 and step 6? If before shooting down milvus, it has been running a long time, searching will hang after restart, and it is a known issue .

**Comment by JackLCL** [comment]
@zhuwenxing 
Yes, I start milvus and run for a long time. Then I shut down milvus. When I restart milvus again, searching hangs.

**Comment by JackLCL** [comment]
Is it a known issue in rc7? Can you give me the issue number?
@zhuwenxing

**Comment by XiaokangLei** [comment]
Me, too. The operation of inserting data is normal, but the search operation does not respond.
