### ISSUE TITLE
query a non-exist table's partitions returns 200

### ISSUE THREAD

**Issue by liangliu** [milvus-io/milvus#1028]
**Describe the bug**
query a non-exist table's partition returns 200, however the returned content is kind of 'empty', but it's still a little bit confusing for users

**Steps/Code to reproduce behavior**
call via API like this
```
params = {'page_size':10, 'offset':0}
res = requests.get(HOST + 'tables/%s/partitions' % 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx', params)
```

**Expected behavior**
**Environment details**
**Screenshots**
**Additional context**

**Comment by BossZou** [comment]
I see. This is because server don't check table exists. I'm fixing it.

**Comment by liangliu** [comment]
verified
