### ISSUE TITLE
delete a non-exist table's partition, return message confusing

### ISSUE THREAD

**Issue by liangliu** [milvus-io/milvus#1029]
**Describe the bug**
delete a non-exist table's partition, return message confusing
`{"message":"Table SZzSGGFAIppkmVDnBuqOxxxx's partition kzVCVxSyZAmLaYcdHGHR not found","code":4}`

actually the whole table is not exist in milvus

**Steps/Code to reproduce behavior**
**Expected behavior**
**Environment details**
**Screenshots**
**Additional context**

**Comment by BossZou** [comment]
I see. This is because server don't check table exists. I'm fixing it.

**Comment by liangliu** [comment]
verified
