### ISSUE TITLE
[Bug]: Milvus collection load error

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#10295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. I inserted 100 million vectors, each time I inserted 100,000, and successfully inserted
2. I created the index of ivf sq8 and it was successfully established
3. Then I call the interface of collection load and report the error as shown in the figure
<img width="1440" alt="截屏2021-10-20 下午6 34 30" src="https://user-images.githubusercontent.com/34296482/138078665-f554394c-a75d-4735-855e-8222bd4132cc.png">

### Expected Behavior

1.collection load should be sucessfully

### Environment

```markdown
- Milvus version:milvusrc7
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.0.0rc7
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: CPU
- GPU: 
- Others:
```

**Comment by xige-16** [comment]
[DEBUG] [cluster.go:248] ["LoadSegments: queryNode load segments error"] [nodeID=8] ["error info"="rpc error: code = Unknown desc = load segment failed, OOM if load
rc
The rc7 version judges whether the memory can be loaded according to the size of the original vector when loading, it should be that the available memory is less than the total size of the original vector

**Comment by xige-16** [comment]
If an index is created, rc8 will judge whether it can be loaded according to the index size, which will alleviate the problem of insufficient memory during load, you can try rc8
