### ISSUE TITLE
[Bug]: [Chaos] Milvus hangs at `load collection` after querynode pod has been killed

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#10357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Milvus hangs at `load collection`  when running `helllo_milvus.py` after querynode pod has been killed several times.  

### Expected Behavior

Running `helllo_milvus.py` can work well

### Steps To Reproduce

```markdown
1. use helm deploy a cluster milvus
2. run `hello_milvus.py` to check milvus before chaos
3. kill querynode pod every 5s in the 30s duration and delete chaos
4. run `hello_milvus.py` after chaos
```

### Environment

```markdown
- Milvus version: master-20211021-0a1529c
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.0.0rc8.dev9
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Anything else?

[k8s_logs.zip](https://github.com/milvus-io/milvus/files/7386695/k8s_logs.zip)

**Comment by zhuwenxing** [comment]
It reproduced in version `master-20211117-9bd3664`.
It will hang at load for about 5min then hang at the search for at least 10min (terminated by manual)
[querynode.zip](https://github.com/milvus-io/milvus/files/7552246/querynode.zip)

**Comment by xige-16** [comment]
working on this issue

**Comment by xige-16** [comment]
Querycoord continued to try to connect with querynode for 6 minutes, but in fact querycoord had received this querynode offline message within 10s, because of the lock, can not directly suspend the operation of establishing a connection with querynode

**Comment by zhuwenxing** [comment]
Verified and passed in version `master-20211119-51b353b`

**Comment by zhuwenxing** [comment]
In version `3cfc740`, this issue happened again.
Milvus hangs at load collection after querynode pod recovered from being killed.
[querynode-pod-kill-11-22.zip](https://github.com/milvus-io/milvus/files/7578416/querynode-pod-kill-11-22.zip)


/assign @xige-16

**Comment by xige-16** [comment]
duplicate with #11275

**Comment by zhuwenxing** [comment]
In version `master-20211124-6c4c0ef`, verified and passed

![image](https://user-images.githubusercontent.com/12268675/143204822-c4d04e91-1459-4484-96d0-bbc898c61367.png)
