### ISSUE TITLE
search multiple vectors at one time failed (index_type NSG)

### ISSUE THREAD

**Issue by liangliu** [milvus-io/milvus#1036]
**Describe the bug**
search multiple vectors failed (index_type NSG), the result is like this - check the 2nd result:
`{"num":2,"results":[[{"id":"1578999500973074499","distance":"0.000000"},{"id":"1578999500973060066","distance":"14.290987"},{"id":"1578999500973078092","distance":"14.310009"},{"id":"1578999500973065992","distance":"14.391077"},{"id":"1578999500973065804","distance":"14.407885"},{"id":"1578999500973056154","distance":"14.609113"},{"id":"1578999500973078573","distance":"14.650621"},{"id":"1578999500973072446","distance":"14.689371"},{"id":"1578999500973065409","distance":"14.718980"},{"id":"1578999500973069403","distance":"15.096894"}],[{"id":"-1","distance":"-1.000000"},{"id":"-1","distance":"-1.000000"},{"id":"-1","distance":"-1.000000"},{"id":"-1","distance":"-1.000000"},{"id":"-1","distance":"-1.000000"},{"id":"-1","distance":"-1.000000"},{"id":"-1","distance":"-1.000000"},{"id":"-1","distance":"-1.000000"},{"id":"-1","distance":"-1.000000"},{"id":"-1","distance":"-1.000000"}]]} (test_httpvector.py:890)`

related info:
"dimension": 128,
"metric_type": 'L2'
dataset_size: 10000
"index_type":'NSG', 
"nlist":8192
req_search = {"topk": 10, "nprobe": 32, "records": **vec**}

vec is 2-dimension array which fetched from the original dataset which means it should returned sth.

actually, when search one by one, correct results returned for both vec.

**Steps/Code to reproduce behavior**
**Expected behavior**
**Environment details**
**Screenshots**
**Additional context**

**Comment by BossZou** [comment]
Now closing it. Reopen it if have more question.
