### ISSUE TITLE
[Bug]: `nil` `context.Context` passed to function

### ISSUE THREAD

**Issue by Biki-das** [milvus-io/milvus#10406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

`id, sampled, found = InfoFromContext(nil)`
`sp, ctx := StartSpanFromContext(nil)`
`sp, ctx = StartSpanFromContextWithOperationName(nil, "test")`

we should not pass a nil Context, even if a function permits it; pass context.TODO if you are unsure about which Context to use

### Expected Behavior

`sp, ctx := StartSpanFromContext(context.TODO())`
`sp, ctx = StartSpanFromContextWithOperationName(context.TODO(), "test")`
`id, sampled, found = InfoFromContext(context.TODO())`

**Comment by yanliang567** [comment]
@Biki-das  i think you are working on this issue
/assign @Biki-das 
/unassgin
