### ISSUE TITLE
[Bug]: [Chaos]Milvus hangs at `get collection entities` after pulsar pod recovers from being killed

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#10441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20211021-d9abce6
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc8.dev9
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Milvus hangs at `get collections entities` when running helllo_milvus.py after pulsar pod has been killed several times.

note: since pulsar is cluster mode(multi pods),  chaos mesh will kill one of them each time.

### Expected Behavior

The script `helllo_milvus.py` can work well

### Steps To Reproduce

```markdown
1. use helm deploy a cluster milvus
2. run `hello_milvus.py` to check milvus before chaos
3. kill pulsar pod every 5s in the 50s duration and delete chaos
4. run `hello_milvus.py` after chaos
```

### Anything else?

[k8s_logs.zip](https://github.com/milvus-io/milvus/files/7395071/k8s_logs.zip)

**Comment by sunby** [comment]
@zhuwenxing `get collection entities` calls flush. After closing pulsar pod, datanode can not consume any msg and datacoord can not flush segments. Please try to restart pulsar pod and `get collection entitie` will resume.

**Comment by zhuwenxing** [comment]
> @zhuwenxing `get collection entities` calls flush. After closing pulsar pod, datanode can not consume any msg and datacoord can not flush segments. Please try to restart pulsar pod and `get collection entitie` will resume.

Pulsar pods have returned to running status.

**Comment by sunby** [comment]
I restart pulsar every 5s and run `hello_milvus.py` but can not reproduce it.

**Comment by zhuwenxing** [comment]
In version `master-20211117-9bd3664`, after chaos, the e2e test works well!

@yanliang567 so I think `priority/urgent` label can be removed! 

I will re-run this test several times. If all of the tests work well, then this issue can be closed

**Comment by yanliang567** [comment]
@zhuwenxing okay, i assign this issue to you for your next action.
/assign @zhuwenxing 
/unassign @sunby

**Comment by zhuwenxing** [comment]
I have tested this about 3 times in version `master-20211119-51b353b` and in my local env, the result is passed.
