### ISSUE TITLE
[Enhancement]: Test and add new tests for "dedup" from search

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#10458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Test and add new test case covering dedup function from search

Test after the PR of handoff merge.

### Why is this needed?

New feature is added:

related issue: #10199
related PR: #10355

**Comment by binbinlv** [comment]
@zhuwenxing  hi, wenxing, Could this issue be closed since your tests have finished?

**Comment by zhuwenxing** [comment]
> @zhuwenxing hi, wenxing, Could this issue be closed since your tests have finished?

done
