### ISSUE TITLE
[BUG] Memory usage increased during searching vectors

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#105]
**Describe the bug**
Memory usage increased slowly during searching vectors

**Steps/Code to reproduce behavior**
Keep searching about 1000 times

**Expected behavior**
Memory usage keep stable

**Environment details**
N/A

**Screenshots**
N/A

**Additional context**
version 0.5.1 and version before 0.5.1

**Comment by scsven** [comment]
#116 
Have been fixed after this merge.
