### ISSUE TITLE
[Bug]: two proxy nodes do not load balance 

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#10527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20211023-6949350
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): rc8-dev14
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

when inserting data into several collections with multiple threads, only one of two proxy nodes is working
![image](https://user-images.githubusercontent.com/82361606/138599387-1d8d15d1-0157-4209-bdc8-89b896746afc.png)

### Expected Behavior

2 proxy node load balanced

### Steps To Reproduce

```markdown
1. deploy milvus clsuter with 2 proxy node
2. insert data into several collections with multiple threads
```

**Comment by DragonDriver** [comment]
> related issue: index node did not load balance #8445

IndexCoord was responsible for the load balance of IndexNodes. Instead, the load balance of proxy was provided by the k8s service. So these two issues are actually not related. @xiaocai2333 was working on fixing the former.

What's the proxy mode in our nodes of k8s cluster? @zwd1208 
IPVS mode with "Source Hashing" may cause this issue.
/assign @zwd1208

**Comment by DragonDriver** [comment]
By the way, have you tried setting up multiple pymilvus connection instances? @yanliang567 
In your case, I'm not sure if an instance under multiple threads shares the same gRPC connection.
Let me check the code of pymilvus.

**Comment by yanliang567** [comment]
@DragonDriver No, I didn't. But I remember that @czs007 mentioned once that multiple threads creates different gRPC connections.

**Comment by zwd1208** [comment]
@DragonDriver  default mode of kube-proxy is iptables, it use rr for every connection

**Comment by DragonDriver** [comment]
Sorry, due to the limit of Python grpc wrapper, multiple grpc channel under same process will reuse the TCP connection. See also [issue in gRPC](https://github.com/grpc/grpc/issues/20985#issuecomment-552604012).
In addition, the gRPC connection based on HTTP2 is a long TCP connection. It will remain when the connection is established. So you can see any requests can be only forward to one proxy pod.
How about testing the load balance in multiple process? @yanliang567

**Comment by xiaofan-luan** [comment]
> @DragonDriver Hi. I have, I suppose, similar problem. Does this grpc connection issue also affect on querynode loadbalancing? I've got 1 proxy and 3 querynodes but only 2 querynodes deal with requests. Of course, proxy and pulsar broker gonna give requests to querynode though, why only 2 querynodes react? Here is the picture on Grafana.
> 
> ![Screenshot_2021_11_03](https://user-images.githubusercontent.com/11371498/139879245-6346ac2b-443b-4a86-bf02-e9a36d3ddd81.png)

Hi Writtic, querynode load balance is probably due to other issues. You can try to release and load collection see if the problem can be solved.
We'll introduce handoff(RC8) and dynamic load balanace(GA) so once GA released the problem should be solved~ Thanks

**Comment by xiaofan-luan** [comment]
> @DragonDriver Hi. I have, I suppose, similar problem. Does this grpc connection issue also affect on querynode loadbalancing? I've got 1 proxy and 3 querynodes but only 2 querynodes deal with requests. Of course, proxy and pulsar broker gonna give requests to querynode though, why only 2 querynodes react? Here is the picture on Grafana.
> 
> ![Screenshot_2021_11_03](https://user-images.githubusercontent.com/11371498/139879245-6346ac2b-443b-4a86-bf02-e9a36d3ddd81.png)

Hi Writtic, for you case, that is because the default shard number is only set to 2, so only 2 querynodes can handle insert.
To solve the problem:
1) increase shard number to 8 when create collection
2) GA version support handoff and load balance, which will move data around between quernode

**Comment by Writtic** [comment]
@xiaofan-luan Hi, Thanks to reply. And I have another question related to your answer. Could the num_shard parameter affects not only insertion but also query performance? I think the shard which might be loaded on query node could be used both operation.

**Comment by xige-16** [comment]
> 

Modifying the number of num shards corresponding to each collection should not affect query performance.

**Comment by xige-16** [comment]
> 

The execution process and execution time of each query are printed in querynode's log. Is there still querynode's log saved?
