### ISSUE TITLE
real distributed cluster support

### ISSUE THREAD

**Issue by sunyaofei** [milvus-io/milvus#1061]
**Is your feature request related to a problem? Please describe.**
1. when data is large, milvus can partition using partition_tag，but the new partition still in same milvus instance；when single machine cpu/memory is not so big, we cannot handle it
2. when create more than one table, the tables share the same milvus instance

**Describe the solution you'd like**
1. partitions(same table or different table) can split to available hardware
2. write/search is transparent to user

**Additional context**
elasticsearch cluster design can be a reference, https://www.elastic.co/guide/en/elasticsearch/guide/master/distributed-cluster.html

**Comment by JinHai-CN** [comment]
Have you tried milvus sharding solution? https://github.com/milvus-io/milvus/tree/master/shards

**Comment by sunyaofei** [comment]
> Have you tried milvus sharding solution? https://github.com/milvus-io/milvus/tree/master/shards

yes，i am tasting mishard.
I have talked to author @XuPeng-SH , and i get that mishard has covered feature i mentioned above in another way. I will try and give my feedback

**Comment by yhmo** [comment]
The v2.0 is real-distributed system.
