### ISSUE TITLE
[Bug]: Mishards writeable node k8s pod CPU jump too high after restart on another pod

### ISSUE THREAD

**Issue by JackYide** [milvus-io/milvus#10643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 1.1.0
- Mishards version: 1.1.5
- Deployment mode(standalone or cluster): Mishard
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS): Centos
- CPU/Memory: 64core 256g
- GPU: 
- Others:
```

### Current Behavior

Hello guys, 

We have Mishards cluster on k8s deployment, writable node runs fine originally which is about 2% cpu utilization rate with one date collection on searching. 
But, with the same search service QPS searching on the same data collection, if the  writable node drifted to another k8s pod, the cpu utilization rate immediately jump high to ~60%, and it cannot get back to normal state until the existing data be recreated as a new collection and change query on new collection. We tried to not recreated a new collection but only invoke buildIndex and preLoadCollect on the existing collection, however, it not works and cpu still goes high.

we cannot understand why writable node drift to another k8s pod can trigger the cpu jump so much high?  and why recreated collection (create a new collection, invoke buildIndex and preLoadCollect for it, and change query target to this new collection) can make it OK?

### Expected Behavior

writeable node should keep stable after restart on another k8s pod

**Comment by yhmo** [comment]
Typically, high cpu utilization rate happens in two conditions:
1. build index
2. search 

Only write node can build index, build index cause high cpu utilization rate. But once a search request come in, milvus can pause/pending build index work and execute search request first.
You said the cpu utilization rate immediately jump high to ~60% after the writable node drifted to another k8s pod. It seems this node begin build index, but I am not sure, maybe its log can reveal something. 

**For cpu utilization rate during searching:**
The mishards cluster includes a proxy node, write-able node, read-only node, and mysql service. When search request come in, the proxy node will print some log about how it distribute search tasks to each node.
For example, I start a mishards cluster with 1 wr node and 1 ro node by docker-compose, then observe the proxy log by this command: docker logs -f [proxy container id]
After search, the proxy print some log like this:
```
2021-11-01 06:41:31,046 | INFO: Routing: {'172.30.0.5:19530': (['8', '10', '12'], ['8', '10', '12']), '172.30.0.4:19530': (['9', '11', '13', '14'], ['9', '11', '13', '14'])} (service_handler.py:135) (ThreadPoolExecutor-0_9)
2021-11-01 06:41:31,046 | DEBUG: <172.30.0.5:19530> needed update segment ids ['8', '10', '12'] (service_handler.py:156) (ThreadPoolExecutor-0_9)
2021-11-01 06:41:31,049 | DEBUG: <172.30.0.4:19530> needed update segment ids ['9', '11', '13', '14'] (service_handler.py:156) (ThreadPoolExecutor-0_9)
2021-11-01 06:41:31,200 | DEBUG: Search in routing {'172.30.0.5:19530': (['8', '10', '12'], ['8', '10', '12']), '172.30.0.4:19530': (['9', '11', '13', '14'], ['9', '11', '13', '14'])} cost 0.15310907363891602 s (service_handler.py:175) (ThreadPoolExecutor-0_9)
```

The "Routing" log tell us how the proxy distribute search task to each node:
`Routing: {'172.30.0.5:19530': (['8', '10', '12'], ['8', '10', '12']), '172.30.0.4:19530': (['9', '11', '13', '14'], ['9', '11', '13', '14'])} `
In this case, the collection has 7 segments, their internal id is '8, 9, 10, 11, 12, 13, 14'. The '172.30.0.5:19530' is the write node, the '172.30.0.4:19530' is the read-only node. The segments '8', '10', '12' were sent to the write node, the '9', '11', '13', '14' were sent to read-only node.

The routing logic is base on hash, some times it may not be averagely, especially when segment count is few. You can check your mishards proxy node log to see how it distribute segments.
