### ISSUE TITLE
Support dropping original data after index creation

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#107]
**Is your feature request related to a problem? Please describe.**
Currently Milvus keep origin data in disk so that user can change index type freely. But it cost too much disk space. I wish I could drop origin data after index is built successfully.

**Describe the solution you'd like**
Add a parameter in create_index sdk api.  "drop_origin"(boolean), default is false.
If create_index(drop_origin=true), the table only contain index files, and user cannot specify any other index type. Call drop_index to this table, the table will become an empty table.
If create_index(drop_origin=false), keep old behavior.

**Comment by cydrain** [comment]
Another suggestion is: add SDK to drop table's original data

Need more discussion

**Comment by yhmo** [comment]
Abandoned.
