### ISSUE TITLE
error message is not clear when page_size is illegal

### ISSUE THREAD

**Issue by liangliu** [milvus-io/milvus#1075]
**Describe the bug**
query like this: 
`res = requests.get(self.HOST + 'tables', params={'offset':0,'page_size':92233720368547758070000000})
`
response is:
`{"message":"Query param 'page_size' is illegal:stol","code":36}`

guess user cannot understand what is **stol**

**Steps/Code to reproduce behavior**
**Expected behavior**
**Environment details**
**Screenshots**
**Additional context**

**Comment by BossZou** [comment]
I see. Now if `page_size` or `offset` is illegal, the error message is like this:
```
{"message":"Query param 'offset' is illegal, only int supported","code":36}
```
