### ISSUE TITLE
[Bug]: Failed to restart indexnode after create index timeout with memory limit

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#10754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20211027-c51155a
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc8.dev18
- OS(Ubuntu or CentOS): 
- CPU/Memory: indexNode memory limit 512Mi
- GPU: 
- Others:
```

### Current Behavior

1. Deploy cluster milvus and limit indexnode memory resource 512Mi
2. Create collection with dim=512
3. Insert 256000 512dim entities (vectors size is 512Mi)
4. Create index with `index_params = {"index_type": "IVF_SQ8", "metric_type": "L2", "params": {"nlist": 128}}`
5. The indexNode crashed and back-off restarting failed container indexnode.
```
mic-memory-etcd-0                                    1/1     Running            0          47h
mic-memory-etcd-1                                    1/1     Running            0          47h
mic-memory-etcd-2                                    1/1     Running            0          47h
mic-memory-milvus-datacoord-7d9896f7f9-lwx7w         1/1     Running            0          133m
mic-memory-milvus-datanode-56c6d89c64-htz4w          1/1     Running            0          122m
mic-memory-milvus-indexcoord-f9db675f4-qcbnw         1/1     Running            0          133m
mic-memory-milvus-indexnode-7896fbbbb9-rb22j         0/1     CrashLoopBackOff   11         122m
mic-memory-milvus-proxy-67458d9c76-tvwx5             1/1     Running            0          133m
mic-memory-milvus-querycoord-b9f5569b9-65wh2         1/1     Running            0          133m
mic-memory-milvus-querynode-65466c7c59-sqhr7         1/1     Running            1          133m
mic-memory-milvus-rootcoord-769f9cd9f5-4gl5l         1/1     Running            0          133m
mic-memory-minio-0                                   1/1     Running            0          47h
mic-memory-minio-1                                   1/1     Running            0          47h
mic-memory-minio-2                                   1/1     Running            0          47h
mic-memory-minio-3                                   1/1     Running            0          47h
mic-memory-pulsar-bookie-0                           1/1     Running            0          47h
mic-memory-pulsar-bookie-1                           1/1     Running            0          47h
mic-memory-pulsar-bookie-init-48sbm                  0/1     Completed          0          47h
mic-memory-pulsar-broker-0                           1/1     Running            0          47h
mic-memory-pulsar-broker-1                           1/1     Running            0          47h
mic-memory-pulsar-proxy-0                            1/1     Running            0          47h
mic-memory-pulsar-proxy-1                            1/1     Running            0          47h
mic-memory-pulsar-pulsar-init-6lb7p                  0/1     Completed          0          47h
mic-memory-pulsar-recovery-0                         1/1     Running            0          47h
mic-memory-pulsar-toolset-0                          1/1     Running            0          47h
mic-memory-pulsar-zookeeper-0                        1/1     Running            0          47h
mic-memory-pulsar-zookeeper-1                        1/1     Running            0          47h
mic-memory-pulsar-zookeeper-2                        1/1     Running            0          47h
```

### Expected Behavior

TODO

### Steps To Reproduce

```markdown
Reference `test_chaos_memory_stress.py::TestChaosData::test_chaos_memory_stress_indexnode`
```

### Anything else?

[client1.log](https://github.com/milvus-io/milvus/files/7424760/client1.log)

_No response_

**Comment by binbinlv** [comment]
@ThreadDao 
Could you help to verify it first?

**Comment by czs007** [comment]
This problem has not yet been completely resolved. Indexnode has not yet estimated the memory size of the index.
May not be solved in GA.

**Comment by yanliang567** [comment]
@czs007 so what is the current design/behavior for now?

**Comment by czs007** [comment]
> @czs007 so what is the current design/behavior for now?

@yanliang567 
The estimation formulas for different index memory sizes are still being explored.
It may not be so fast.

**Comment by ThreadDao** [comment]
I re-tested this issue on image `master-20211130-f00ee2a`, and yes it has not been fixed.
1. Client gets exception `<BaseException: (code=1, message=CreateIndex Timeout)>`, but describe collection index shows that the index has been created
```
c.describe_index('chaos_memory_gKs8aSUu')
{'index_type': 'IVF_SQ8', 'metric_type': 'L2', 'params': {'nlist': 128}, 'field_name': 'float_vector'}
```
2. The index node is in the loop between pulling up and OOMKilled.

The pod `mic-memory-milvus-indexnode-59b5c7f786-745mj` logs: 
[indexnode_previous.log](https://github.com/milvus-io/milvus/files/7624797/indexnode_previous.log)

**Comment by czs007** [comment]
After discussion, proceesed as follows: set a memory requirement that is about 4 times the original data of the vector. If no indexnode meets this requirement, the index will not be built, and the index status of the segment has always been unissued.

@yanliang567 @ThreadDao

**Comment by xiaocai2333** [comment]
I will working on it.

**Comment by xiaocai2333** [comment]
Added logic to estimate memory when building index. Please check it. @ThreadDao 
/assign @ThreadDao 
/unassign

**Comment by ThreadDao** [comment]
When I create an index the following error happens in indexCoord. I will regress this problem after #13072 is fixed.
```
2087 [2021/12/09 08:32:36.853 +00:00] [DEBUG] [meta_table.go:483] ["IndexCoord metaTable LoadMetaFromETCD"] [indexBuildID=429664110955462658] [revision=84] [ok=true]
2088 [2021/12/09 08:32:36.853 +00:00] [DEBUG] [meta_table.go:486] ["IndexCoord metaTable LoadMetaFromETCD"] [meta.revision=84] [revision=84]
2089 [2021/12/09 08:32:36.853 +00:00] [ERROR] [node_manager.go:137] ["IndexCoord NodeManager PeekClient"] ["There is no IndexNode client corresponding to NodeID"=-1] [stack="github.com/milvus-io/milvus/internal/indexcoord.(*NodeManager).PeekClient\n\t/go/src/github.com/milvu     s-io/milvus/internal/indexcoord/node_manager.go:137\ngithub.com/milvus-io/milvus/internal/indexcoord.(*IndexCoord).assignTaskLoop\n\t/go/src/github.com/milvus-io/milvus/internal/indexcoord/index_coord.go:843"]
2090 [2021/12/09 08:32:36.853 +00:00] [WARN] [index_coord.go:845] ["IndexCoord assignmentTasksLoop can not find available IndexNode"]
2091 [2021/12/09 08:32:36.853 +00:00] [DEBUG] [index_coord.go:777] ["IndexCoord watchMetaLoop PUT"] [IndexBuildID=429664110955462658] [reload=false]
```

**Comment by ThreadDao** [comment]
1. Image version: `master-20211213-af46998`
2. Memory limit of indexNode: `512Mi`
3. Data size: `dim=512`, num_entities=50000, about 100MIB

If you estimate the required memory based on 6 times the original vector data, the existing 512Mi is insufficient and the index will not be created, and the indexNode will not be OOM killed.
[indexcoord.log](https://github.com/milvus-io/milvus/files/7702140/indexcoord.log)
[indexnode.log](https://github.com/milvus-io/milvus/files/7702141/indexnode.log)

**Comment by czs007** [comment]
refer to this https://github.com/milvus-io/milvus/pull/13320

**Comment by xiaocai2333** [comment]
/assign @ThreadDao 

Please retest it.

**Comment by ThreadDao** [comment]
I rerun this on image `master-20211220-a7dfd53` and the indexnode pod didn't be OOMkilled. 
What must be said is it is difficult to determine the failure of indexing based on client exception or server logs due to insufficient memory.
Please @xiaocai2333  improve the index log and post it after testing by yourself.
/assign @xiaocai2333 
/unassign

**Comment by czs007** [comment]
@xiaocai2333 When you have time, think about how to modify it and provide a more informative log.
