### ISSUE TITLE
[Feature]: The construct_from_dataframe pymilvus API also needs to support the shard_num parameter

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#10820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

1. Create collection API support `shard_num` param
`def __init__(self, name, schema=None, using="default", shards_num=2, **kwargs):`

2. construct_from_dataframe don't support
`def construct_from_dataframe(cls, name, dataframe, **kwargs):`

**Comment by xiaocai2333** [comment]
`construct_from_dataframe` also supports shard_num, use it like this:
```
coll = Collection.construct_from_dataframe(coll_name, data, primary_field="int64", shard_num=1)
```
