### ISSUE TITLE
Does Milvus support deletion through milvusid？

### ISSUE THREAD

**Issue by GitHubBylijianbo** [milvus-io/milvus#1084]
**Describe the bug**

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by GitHubBylijianbo** [comment]
Does Milvus support single deletion

**Comment by GitHubBylijianbo** [comment]
milvus 支持单条删除吗？

**Comment by yamasite** [comment]
Not yet. For now, you can only drop the whole table. Vector deletion by ID will be supported in Milvus 0.7.0. Stay tuned!

**Comment by youny626** [comment]
Hi, this feature has just been merged to the master branch! The official 0.7.0 version will be released in a couple of weeks! :D

**Comment by JinHai-CN** [comment]
0.7.0 is released.
