### ISSUE TITLE
CPU not fully used in benchmark test deployed on K8s

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#1092]
**Describe the bug**
![Screenshot_2020-01-18 kubernetes pod dashboard - Grafana](https://user-images.githubusercontent.com/56623710/72657747-b75dee80-39e2-11ea-8d09-d41cc587f568.png)

**Steps/Code to reproduce behavior**

**Expected behavior**

**Environment details**

**Screenshots**

**Additional context**

**Comment by del-zhenwu** [comment]
![Screenshot_2020-01-22 Kubernetes Node Resource Consumption - Grafana](https://user-images.githubusercontent.com/56623710/72861603-68c39380-3d05-11ea-9cb4-cb70d2f16f28.png)

Node monitor have added

**Comment by JinHai-CN** [comment]
Then, what kind of cases lead to low CPU usage?

**Comment by del-zhenwu** [comment]
close
