### ISSUE TITLE
[Bug]: centos与ubuntu源码编译都失败

### ISSUE THREAD

**Issue by githublaohu** [milvus-io/milvus#10934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:1.1
- Deployment mode(standalone or cluster): 编译
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): ubuntu and centos
- CPU/Memory: 
:
```

### Current Behavior

想较好的掌握 milvue优秀的存储，使用源码编译了解架构并且使用好

ubuntu失败信息
`
./faiss/gpu/utils/Float16.cuh:17:2: error: #error "CUDA >= 8.0 is required"
 #error "CUDA >= 8.0 is required"
  ^~~~~
In file included from impl/io.cpp:14:0:
impl/io.cpp: In destructor ‘virtual faiss::BufferedIOWriter::~BufferedIOWriter()’:
./faiss/impl/FaissAssert.h:67:77: warning: throw will always call terminate() [-Wterminate]
     throw faiss::FaissException(__s, __PRETTY_FUNCTION__, __FILE__, __LINE__); \
                                                                             ^
./faiss/impl/FaissAssert.h:77:7: note: in expansion of macro ‘FAISS_THROW_FMT’
       FAISS_THROW_FMT("Error: '%s' failed", #X);        \
       ^~~~~~~~~~~~~~~
impl/io.cpp:235:9: note: in expansion of macro ‘FAISS_THROW_IF_NOT’
         FAISS_THROW_IF_NOT(written > 0);
         ^~~~~~~~~~~~~~~~~~
./faiss/impl/FaissAssert.h:67:77: note: in C++11 destructors default to noexcept
     throw faiss::FaissException(__s, __PRETTY_FUNCTION__, __FILE__, __LINE__); \
                                                                             ^
./faiss/impl/FaissAssert.h:77:7: note: in expansion of macro ‘FAISS_THROW_FMT’
       FAISS_THROW_FMT("Error: '%s' failed", #X);        \
       ^~~~~~~~~~~~~~~
impl/io.cpp:235:9: note: in expansion of macro ‘FAISS_THROW_IF_NOT’
         FAISS_THROW_IF_NOT(written > 0);
         ^~~~~~~~~~~~~~~~~~
ar: 正在创建 libfaiss.a
[ 35%] Performing install step for 'faiss_ep'
make[3]: 警告: jobserver 不可用: 正使用 -j1。添加 “+” 到父 make 的规则。
[ 36%] Completed 'faiss_ep'
[ 36%] Built target faiss_ep
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

`

centos失败信息
`
HEAD 目前位于 4d6b61a... Merge pull request #273 from jupp0r/propagate-curl-errors
In file included from /root/milvus/core/cmake_build/aws_ep-prefix/src/aws_ep/aws-cpp-sdk-s3/include/aws/s3/model/SelectObjectContentRequest.h:19:0,
                 from /root/milvus/core/cmake_build/aws_ep-prefix/src/aws_ep/aws-cpp-sdk-s3/source/S3Client.cpp:115,
                 from /root/milvus/core/cmake_build/aws_ep-prefix/src/aws_ep-build/aws-cpp-sdk-s3/ub_S3.cpp:3:
/root/milvus/core/cmake_build/aws_ep-prefix/src/aws_ep/aws-cpp-sdk-s3/include/aws/s3/model/SelectObjectContentHandler.h:43:22: 错误：未使用的参数‘handler’ [-Werror=unused-parameter]
     class AWS_S3_API SelectObjectContentHandler : public Aws::Utils::Event::EventStreamHandler
                      ^
In file included from /root/milvus/core/cmake_build/aws_ep-prefix/src/aws_ep/aws-cpp-sdk-s3/source/S3Client.cpp:115:0,
                 from /root/milvus/core/cmake_build/aws_ep-prefix/src/aws_ep-build/aws-cpp-sdk-s3/ub_S3.cpp:3:
/root/milvus/core/cmake_build/aws_ep-prefix/src/aws_ep/aws-cpp-sdk-s3/include/aws/s3/model/SelectObjectContentRequest.h: 在成员函数‘void Aws::S3::Model::SelectObjectContentRequest::SetEventStreamHandler(const Aws::S3::Model::SelectObjectContentHandler&)’中:
/root/milvus/core/cmake_build/aws_ep-prefix/src/aws_ep/aws-cpp-sdk-s3/include/aws/s3/model/SelectObjectContentRequest.h:83:92: 附注：在这里第一次需要生成的方法‘Aws::S3::Model::SelectObjectContentHandler& Aws::S3::Model::SelectObjectContentHandler::operator=(const Aws::S3::Model::SelectObjectContentHandler&)’
     inline void SetEventStreamHandler(const SelectObjectContentHandler& value) { m_handler = value; m_decoder.ResetEventStreamHandler(&m_handler); }
                                                                                            ^
子模组 'civetweb' (https://github.com/civetweb/civetweb.git) 已为路径 '3rdparty/civetweb' 注册
子模组 'googletest' (https://github.com/google/googletest.git) 已为路径 '3rdparty/googletest' 注册
正克隆到 '3rdparty/civetweb'...
make[4]: *** [src/CMakeFiles/oatpp.dir/all] 错误 2
make[3]: *** [all] 错误 2
make[2]: *** [oatpp_ep-prefix/src/oatpp_ep-stamp/oatpp_ep-build] 错误 2
make[1]: *** [CMakeFiles/oatpp_ep.dir/all] 错误 2
cc1plus: all warnings being treated as errors
make[5]: *** [aws-cpp-sdk-s3/CMakeFiles/aws-cpp-sdk-s3.dir/ub_S3.cpp.o] 错误 1
make[4]: *** [aws-cpp-sdk-s3/CMakeFiles/aws-cpp-sdk-s3.dir/all] 错误 2

`

**Comment by anoymouscoder** [comment]
I encountered a similar problem on docker image `milvus-env:amd64-ubuntu18.04-latest`.
```
[  2%] Building CXX object src/index/thirdparty/NGT/lib/NGT/CMakeFiles/ngtstatic.dir/Capi.cpp.o
In file included from impl/io.cpp:14:0:
impl/io.cpp: In destructor 'virtual faiss::BufferedIOWriter::~BufferedIOWriter()':
./faiss/impl/FaissAssert.h:67:77: warning: throw will always call terminate() [-Wterminate]
     throw faiss::FaissException(__s, __PRETTY_FUNCTION__, __FILE__, __LINE__); \
                                                                             ^
./faiss/impl/FaissAssert.h:77:7: note: in expansion of macro 'FAISS_THROW_FMT'
       FAISS_THROW_FMT("Error: '%s' failed", #X);        \
       ^~~~~~~~~~~~~~~
impl/io.cpp:235:9: note: in expansion of macro 'FAISS_THROW_IF_NOT'
         FAISS_THROW_IF_NOT(written > 0);
         ^~~~~~~~~~~~~~~~~~
./faiss/impl/FaissAssert.h:67:77: note: in C++11 destructors default to noexcept
     throw faiss::FaissException(__s, __PRETTY_FUNCTION__, __FILE__, __LINE__); \
                                                                             ^
./faiss/impl/FaissAssert.h:77:7: note: in expansion of macro 'FAISS_THROW_FMT'
       FAISS_THROW_FMT("Error: '%s' failed", #X);        \
       ^~~~~~~~~~~~~~~
impl/io.cpp:235:9: note: in expansion of macro 'FAISS_THROW_IF_NOT'
         FAISS_THROW_IF_NOT(written > 0);
         ^~~~~~~~~~~~~~~~~~
```
Is there any way to solve this problem?
