### ISSUE TITLE
[Feature]: DEVELOPMENT.md is not friendly to users

### ISSUE THREAD

**Issue by githublaohu** [milvus-io/milvus#10946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

想本地调试源码，与源码编译。把build目录看完，还是没怎么看懂。

### Describe the solution you'd like.

提供本地调试文档与源码调试文档，谢谢，非常感谢。

**Comment by shanghaikid** [comment]
The developer guide documentation  is not that developer friendly.

**Comment by yhmo** [comment]
@githublaohu 
Could you change the title to "DEVELOPMENT.md is not friendly for developer"?

**Comment by yhmo** [comment]
To build/run milvus:
1. Firstly make sure your OS is Ubuntu or CentOS. We don't recommend build milvus on Mac, but user can start a Ubuntu/CentOS docker container on Mac and build milvus in container.
2. Follow the steps in /milvus/DEVELOPMENT.md. Install dependencies and config Go environment.
3. I think the DEVELOPMENT.md lack a section for "Run Milvus on local". User need to launch third-party service by `docker-compose up -d` under the `deployments/docker/dev` folder.

**Comment by githublaohu** [comment]
> The developer guide documentation is not that developer friendly.

说的很对呀，是的呀。如果无法把部署与配置吃透，大规模使用会遇到很多问题。
内部其他组件的集成问题。比如etcd，对象存储的共用

**Comment by xiaofan-luan** [comment]
what environment you are on? and what detailed problem you hit?

**Comment by xiaofan-luan** [comment]
Also i would be great if issues can be written English, otherwise it would be very confusing to english speakers, thanks

**Comment by githublaohu** [comment]
1. make all 之后，可以执行文件在哪里呀。
2. 从github获得jar，会经常的出现网络问题
3. make all，如何进入开发状态
4. boost的执行命令，在ubuntu上有一些问题

**Comment by xiaofan-luan** [comment]
@githublaohu please use english to communicate~ sorry for the inconvenience but it could help more people

**Comment by xiaofan-luan** [comment]
For how to develop milvus, see DEVELOPING.md
For how run milvus, easiest way is to use docker compose, or run ./start_standalone.sh under scripts dir
