### ISSUE TITLE
../bin/milvus_server: error while loading shared libraries: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1: file too short

### ISSUE THREAD

**Issue by youbingchenyoubing** [milvus-io/milvus#1094]
docker run  --name milvus_gpu \
-p 19530:19530 \
-p 8080:8080 \
-v $milvus_path/db:/var/lib/milvus/db \
-v $milvus_path/conf:/var/lib/milvus/conf \
-v $milvus_path/logs:/var/lib/mulvus/logs \
milvusdb/milvus:0.6.0-gpu-d120719-2b40dd

**Comment by ZhifengZhang-CN** [comment]
You need [nvidia docker](https://github.com/NVIDIA/nvidia-docker)

**Comment by ZhifengZhang-CN** [comment]
[Install GPU-enabled Milvus](https://milvus.io/docs/guides/get_started/install_milvus/gpu_milvus_docker.md)
