### ISSUE TITLE
Are there have API of milvus.close() ?

### ISSUE THREAD

**Issue by tianmaxingkong666** [milvus-io/milvus#1097]
We have the API of milvus.connect(), and i can't find the API of milvus.close() ?

**Comment by BossZou** [comment]
You can invoke `milvus.disconnect()`.

**Comment by yamasite** [comment]
@tianmaxingkong666 Please refer to pymilvus readme in [https://github.com/milvus-io/pymilvus](https://github.com/milvus-io/pymilvus). You can see that `milvus.disconnect()` has been documented.

**Comment by BossZou** [comment]
Now closing it. Reopen  if you have more questions.
