### ISSUE TITLE
Support output log files to HDFS

### ISSUE THREAD

**Issue by mrright2019** [milvus-io/milvus#1099]
日志的输出可以支持hdfs吗，因为我本地的磁盘很小，milvus的日志我又很少看，请问后续有增加hdfs的支持吗

**Comment by XuPeng-SH** [comment]
如果本地磁盘比较小的话，建议将NAS或者HDFS等共享存储挂载到文件系统下，配置日志保存到相关目录下。

**Comment by yhmo** [comment]
Inactive
