### ISSUE TITLE
[Bug]: Failed to drop collection when running cases in multiple threads

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#11034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20211030-54738d2
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): rc8dev22
```

### Current Behavior

Fail to drop collection, when running tests in multiple threads 
```
[2021-11-01 10:18:26 - DEBUG - ci_test]: (api_request)  : [Collection.drop_partition] args: ['search_partition_0'], kwargs: {'timeout': 20} (api_request.py:44)
[2021-11-01 10:18:47 - ERROR - pymilvus.client.grpc_handler]: 
Addr [10.98.0.7:19530] drop_partition
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1635761927.003051909","description":"Error received from peer ipv4:10.98.0.7:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
	{'API start': '2021-11-01 10:18:26.998639', 'RPC start': '2021-11-01 10:18:27.002539', 'RPC error': '2021-11-01 10:18:47.003992'} (grpc_handler.py:74)
[2021-11-01 10:19:07 - ERROR - pymilvus.client.grpc_handler]: Error: <BaseException: (code=1, message=DropPartition failed: partition search_partition_0 does not exist)> (grpc_handler.py:59)
[2021-11-01 10:19:07 - ERROR - ci_test]: Traceback (most recent call last):
  File "/milvus/tests/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/milvus/tests/python_client/utils/api_request.py", line 45, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 904, in drop_partition
    return conn.drop_partition(self._name, partition_name, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 61, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 45, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 459, in drop_partition
    return handler.drop_partition(collection_name, partition_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 417, in drop_partition
    raise BaseException(response.error_code, response.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=DropPartition failed: partition search_partition_0 does not exist)>
 (api_request.py:26)
[2021-11-01 10:19:07 - ERROR - ci_test]: (api_response) : <BaseException: (code=1, message=DropPartition failed: partition search_partition_0 does not exist)> (api_request.py:27)
```

### Expected Behavior

tests run successfully

### Steps To Reproduce

```markdown
run test test_search_before_after_delete with 6 threads for 10 times:
pytest --host x.x.x.x testcases/test_search_20.py::TestCollectionSearch::test_search_before_after_delete -n 6 --count 10
```

**Comment by binbinlv** [comment]
Similar issue in nightly tests:
Drop collection failed until timeout first, then load timeout, then all the tests is hanging.

https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/204/

See cluster pytest logs, the described tests logs will be found.

**Comment by binbinlv** [comment]
blocking nightly tests, so set this as urgent.

**Comment by binbinlv** [comment]
Continuously appear in nightly:

Cluster mode: [logs]
https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/

First drop collection timeout: 
timeline:  2021-11-02 15:49:01

```
[2021-11-02 15:49:01,124 - INFO - ci_test]: [teardown_method] Start teardown test case test_search_index_partitions... (client_base.py:62)
[2021-11-02 15:49:17,274 - ERROR - ci_test]: Traceback (most recent call last):
  File "/milvus/tests/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/milvus/tests/python_client/utils/api_request.py", line 45, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 409, in drop
    conn.drop_collection(self._name, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 53, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 45, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 254, in drop_collection
    return handler.drop_collection(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 355, in drop_collection
    status = rf.result()
  File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "{"created":"@1635868157.272773412","description":"Error received from peer ipv4:172.18.255.155:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Deadline Exceeded","grpc_status":4}"
```

**Comment by binbinlv** [comment]
@congqixia  Any updates, thanks.

**Comment by sunby** [comment]
@binbinlv What's the latest nightly job?

**Comment by binbinlv** [comment]
@sunby
The latest nightly relating to this issue is:

https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/206/

Cluster mode:
Log please download through the upper link,

milvus log: 
artifacts-milvus-distributed-master-206-e2e-nightly-logs.tar.gz

Test log: 
artifacts-milvus-distributed-pymilvus-pytest-logs.tar.gz

And in test log:
drop collection timeout first appears at timeline:  [2021-11-02 15:49:17,274 - ERROR - ci_test]:

```
[2021-11-02 15:49:17,274 - ERROR - ci_test]: Traceback (most recent call last):
  File "/milvus/tests/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/milvus/tests/python_client/utils/api_request.py", line 45, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 409, in drop
    conn.drop_collection(self._name, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 53, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 45, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 254, in drop_collection
    return handler.drop_collection(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 355, in drop_collection
    status = rf.result()
  File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "{"created":"@1635868157.272773412","description":"Error received from peer ipv4:172.18.255.155:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
 (api_request.py:26)
[2021-11-02 15:49:17,274 - ERROR - ci_test]: (api_response) : <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "{"created":"@1635868157.272773412","description":"Error received from peer ipv4:172.18.255.155:19530","file":"src/core/lib/surface/call.cc","file_line":...... (api_request.py:27)
```

Hope it will be a help for your debug, thanks.

**Comment by binbinlv** [comment]
And through test log, the whole pipeline is:

1 first drop_collection failed for timeout:
[2021-11-02 15:49:17] 

2 Then  the latter cases will occur drop_collection and load_collection timeout:
（1) [2021-11-02 15:49:37] drop_collection timeout
  (2) [2021-11-02 15:49:59] drop_collection timeout
  (3) [2021-11-02 15:52:35] load_collection timeout， collection name: search_collection_mypidgIs
  (4) [2021-11-02 15:54:01]  load_collection timeout
  (5) [2021-11-02 15:54:23] load_collection timeout 
  (6) [2021-11-02 15:54:43] load_collection timeout 
   (7) ...
   
3 the whole tests will hang at [2021-11-02 15:58:41]

**Comment by sawyer7246** [comment]
drop a collection in standalone mode while the container exit with code 2. 
```
milvus-standalone | [2021/11/04 02:12:35.754 +00:00] [ERROR] [task_scheduler.go:455] ["Failed to execute task: index not exist"] [traceID=55d21fd1dca34192] [stack="github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:455\ngithub.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:480"]
milvus-standalone | [2021/11/04 02:12:35.754 +00:00] [DEBUG] [impl.go:1029] ["DescribeIndex Done"] [error="index not exist"] [role=proxy] [msgID=428865469939187719] [timestamp=428865475247603713] [db=] [collection=frame_search_collection_1] [field=] ["index name"=_default_idx]
milvus-standalone | [2021/11/04 02:12:35.756 +00:00] [DEBUG] [impl.go:189] ["DropCollection enqueue"] [role=proxy] [db=] [collection=frame_search_collection_1]
milvus-standalone | [2021/11/04 02:12:35.757 +00:00] [DEBUG] [id.go:136] ["IDAllocator pickCanDoFunc"] [need=1] [total=199993] [remainReqCnt=0]
milvus-standalone | [2021/11/04 02:12:35.757 +00:00] [DEBUG] [impl.go:201] [DropCollection] [role=proxy] [msgID=428865469939187720] [timestamp=428865475247603714] [db=] [collection=frame_search_collection_1]
milvus-standalone | [2021/11/04 02:12:35.757 +00:00] [DEBUG] [root_coord.go:1240] [DropCollection] [name=frame_search_collection_1] [msgID=428865469939187720]
milvus-standalone | [2021/11/04 02:12:35.757 +00:00] [DEBUG] [timeticksync.go:111] ["add ddl timetick"] [minTs=428865475247603715] [ts=428865475247603715] [len(ddlTsSet)=1] [reason="drop collection 428845321224454146"]
milvus-standalone | [2021/11/04 02:12:35.781 +00:00] [ERROR] [meta_table.go:412] ["SnapShotKV MultiSaveAndRemoveWithPrefix fail"] [error="etcdserver: too many operations in txn request"] [stack="github.com/milvus-io/milvus/internal/rootcoord.(*MetaTable).DeleteCollection\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/meta_table.go:412\ngithub.com/milvus-io/milvus/internal/rootcoord.(*DropCollectionReqTask).Execute.func2\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/task.go:292\ngithub.com/milvus-io/milvus/internal/rootcoord.(*DropCollectionReqTask).Execute\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/task.go:313\ngithub.com/milvus-io/milvus/internal/rootcoord.executeTask.func1\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/task.go:56"]
milvus-standalone | [2021/11/04 02:12:35.781 +00:00] [DEBUG] [timeticksync.go:122] ["remove ddl timetick"] [ts=428865475247603715] [len(ddlTsSet)=0] [reason="drop collection 428845321224454146"]
milvus-standalone | {"level":"warn","ts":"2021-11-04T02:12:35.781Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0003bc540/#initially=[etcd:2379]","attempt":0,"error":"rpc error: code = InvalidArgument desc = etcdserver: too many operations in txn request"}
milvus-standalone | panic: SnapShotKV MultiSaveAndRemoveWithPrefix fail
milvus-standalone | 
milvus-standalone | goroutine 4144 [running]:
milvus-standalone | github.com/milvus-io/milvus/internal/rootcoord.(*MetaTable).DeleteCollection(0xc000330f00, 0x5f3908c2b2c0002, 0x5f3a2e0a4900003, 0xc0039bd2e0, 0x0, 0x0)
milvus-standalone | 	/go/src/github.com/milvus-io/milvus/internal/rootcoord/meta_table.go:413 +0xff0
milvus-standalone | github.com/milvus-io/milvus/internal/rootcoord.(*DropCollectionReqTask).Execute.func2(0x0, 0x0)
milvus-standalone | 	/go/src/github.com/milvus-io/milvus/internal/rootcoord/task.go:292 +0x1a7
milvus-standalone | github.com/milvus-io/milvus/internal/rootcoord.(*DropCollectionReqTask).Execute(0xc0039cc7e0, 0x2782980, 0xc0039ce660, 0xc000196940, 0x25e6b08)
milvus-standalone | 	/go/src/github.com/milvus-io/milvus/internal/rootcoord/task.go:313 +0x4a9
milvus-standalone | github.com/milvus-io/milvus/internal/rootcoord.executeTask.func1(0x27834c0, 0xc0039cc7e0, 0xc0039af380)
milvus-standalone | 	/go/src/github.com/milvus-io/milvus/internal/rootcoord/task.go:56 +0x45
milvus-standalone | created by github.com/milvus-io/milvus/internal/rootcoord.executeTask
milvus-standalone | 	/go/src/github.com/milvus-io/milvus/internal/rootcoord/task.go:55 +0x89
milvus-standalone exited with code 2
```

**Comment by sunby** [comment]
This issue is caused by deadlock in querynode. @bigsheeper will fix it in rc8
@yanliang567 @binbinlv

**Comment by sunby** [comment]
> too many operations in txn request

Which version  you using?
This issue is fixed in #10288 and you can try it after rc8 release

**Comment by sunby** [comment]
> drop a collection in standalone mode while the container exit with code 2.
> 
> ```
> milvus-standalone | [2021/11/04 02:12:35.754 +00:00] [ERROR] [task_scheduler.go:455] ["Failed to execute task: index not exist"] [traceID=55d21fd1dca34192] [stack="github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:455\ngithub.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:480"]
> milvus-standalone | [2021/11/04 02:12:35.754 +00:00] [DEBUG] [impl.go:1029] ["DescribeIndex Done"] [error="index not exist"] [role=proxy] [msgID=428865469939187719] [timestamp=428865475247603713] [db=] [collection=frame_search_collection_1] [field=] ["index name"=_default_idx]
> milvus-standalone | [2021/11/04 02:12:35.756 +00:00] [DEBUG] [impl.go:189] ["DropCollection enqueue"] [role=proxy] [db=] [collection=frame_search_collection_1]
> milvus-standalone | [2021/11/04 02:12:35.757 +00:00] [DEBUG] [id.go:136] ["IDAllocator pickCanDoFunc"] [need=1] [total=199993] [remainReqCnt=0]
> milvus-standalone | [2021/11/04 02:12:35.757 +00:00] [DEBUG] [impl.go:201] [DropCollection] [role=proxy] [msgID=428865469939187720] [timestamp=428865475247603714] [db=] [collection=frame_search_collection_1]
> milvus-standalone | [2021/11/04 02:12:35.757 +00:00] [DEBUG] [root_coord.go:1240] [DropCollection] [name=frame_search_collection_1] [msgID=428865469939187720]
> milvus-standalone | [2021/11/04 02:12:35.757 +00:00] [DEBUG] [timeticksync.go:111] ["add ddl timetick"] [minTs=428865475247603715] [ts=428865475247603715] [len(ddlTsSet)=1] [reason="drop collection 428845321224454146"]
> milvus-standalone | [2021/11/04 02:12:35.781 +00:00] [ERROR] [meta_table.go:412] ["SnapShotKV MultiSaveAndRemoveWithPrefix fail"] [error="etcdserver: too many operations in txn request"] [stack="github.com/milvus-io/milvus/internal/rootcoord.(*MetaTable).DeleteCollection\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/meta_table.go:412\ngithub.com/milvus-io/milvus/internal/rootcoord.(*DropCollectionReqTask).Execute.func2\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/task.go:292\ngithub.com/milvus-io/milvus/internal/rootcoord.(*DropCollectionReqTask).Execute\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/task.go:313\ngithub.com/milvus-io/milvus/internal/rootcoord.executeTask.func1\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/task.go:56"]
> milvus-standalone | [2021/11/04 02:12:35.781 +00:00] [DEBUG] [timeticksync.go:122] ["remove ddl timetick"] [ts=428865475247603715] [len(ddlTsSet)=0] [reason="drop collection 428845321224454146"]
> milvus-standalone | {"level":"warn","ts":"2021-11-04T02:12:35.781Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0003bc540/#initially=[etcd:2379]","attempt":0,"error":"rpc error: code = InvalidArgument desc = etcdserver: too many operations in txn request"}
> milvus-standalone | panic: SnapShotKV MultiSaveAndRemoveWithPrefix fail
> milvus-standalone | 
> milvus-standalone | goroutine 4144 [running]:
> milvus-standalone | github.com/milvus-io/milvus/internal/rootcoord.(*MetaTable).DeleteCollection(0xc000330f00, 0x5f3908c2b2c0002, 0x5f3a2e0a4900003, 0xc0039bd2e0, 0x0, 0x0)
> milvus-standalone | 	/go/src/github.com/milvus-io/milvus/internal/rootcoord/meta_table.go:413 +0xff0
> milvus-standalone | github.com/milvus-io/milvus/internal/rootcoord.(*DropCollectionReqTask).Execute.func2(0x0, 0x0)
> milvus-standalone | 	/go/src/github.com/milvus-io/milvus/internal/rootcoord/task.go:292 +0x1a7
> milvus-standalone | github.com/milvus-io/milvus/internal/rootcoord.(*DropCollectionReqTask).Execute(0xc0039cc7e0, 0x2782980, 0xc0039ce660, 0xc000196940, 0x25e6b08)
> milvus-standalone | 	/go/src/github.com/milvus-io/milvus/internal/rootcoord/task.go:313 +0x4a9
> milvus-standalone | github.com/milvus-io/milvus/internal/rootcoord.executeTask.func1(0x27834c0, 0xc0039cc7e0, 0xc0039af380)
> milvus-standalone | 	/go/src/github.com/milvus-io/milvus/internal/rootcoord/task.go:56 +0x45
> milvus-standalone | created by github.com/milvus-io/milvus/internal/rootcoord.executeTask
> milvus-standalone | 	/go/src/github.com/milvus-io/milvus/internal/rootcoord/task.go:55 +0x89
> milvus-standalone exited with code 2
> ```

Which version are you using?
This issue is fixed in #10288 and you can try it after rc8 release

**Comment by sawyer7246** [comment]
my image version is `milvusdb/milvus:v2.0.0-rc7-20211011-d567b21` .
maybe I should try out rc8 release.
anyway, thks for quick reply.

**Comment by sawyer7246** [comment]
could you provide me with the rc8 docker-compose file

**Comment by yanliang567** [comment]
verified on 2.0.0-rc8-20211104-d1f4106
