### ISSUE TITLE
Can I hit the API though Curl without using SDK?

### ISSUE THREAD

**Issue by wendilinplay** [milvus-io/milvus#1118]
**What is your question?**
Can I hit the API though Curl without using SDK?

**Comment by yamasite** [comment]
We are working on the Milvus RESTful API, which will be ready by 0.7.0. By then you can use Curl to hit the RESTful API. Stay tuned！

**Comment by BossZou** [comment]
[Here](https://github.com/milvus-io/milvus/tree/master/core/src/server/web_impl) is HTTP doc. You can find more details about HTTP API.

**Comment by BossZou** [comment]
Fixed. close it.
