### ISSUE TITLE
Milvus internal error

### ISSUE THREAD

**Issue by GlebBerjoskin** [milvus-io/milvus#1119]
How to fix the following:
<_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Exception serializing request!"
	debug_error_string = "None"
>
I run milvus-gpu search with IndexType.FLAT, MetricType.IP, 'index_file_size':1024, 'nlist':6000, dimension of 10000 on Ubuntu

**Comment by BossZou** [comment]
Hello, I guess the version of Client SDK doesn't match that of milvus server. You may check the version and find proper one in [milvus.io](https://milvus.io/)

**Comment by BossZou** [comment]
If you are using python SDK, please refer to [here](https://github.com/milvus-io/pymilvus/blob/master/README.md). You can find more information about version matching.

**Comment by cydrain** [comment]
Hi GlebBerjoskin,
1. please check Milvus' error logging, you should be able to find more error info there.
2. Milvus doesn't support too high dimension (such as 10000), you can reduce dimension to 128 and try your test again, to see if this error still exist.
