### ISSUE TITLE
[Bug]: Timeout when execute vector search

### ISSUE THREAD

**Issue by spirit832** [milvus-io/milvus#11223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0
- Deployment mode(standalone or cluster):standalone 
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus v2.0.0rc7
- OS(Ubuntu or CentOS): Ubuntu 
- CPU/Memory: 16G
- GPU: 
- Others:
```

### Current Behavior

创建了一个集合，插入13000多条记录，向量维度为768，执行向量检索一直超时
Create a index with 13000 entities, the vector dim is 768 and search requests always timeout.

**Comment by spirit832** [comment]
补充说明一下 索引类型为  IVF_FLAT nlist:1024

**Comment by xiaofan-luan** [comment]
@spirit832  can you offer milvus logs for further investigation?

**Comment by spirit832** [comment]
{"level":"INFO","time":"2021/11/04 04:56:57.590 +00:00","caller":"grpclog.go:37","message":"[core]Channel Connectivity change to READY"}
{"level":"ERROR","time":"2021/11/04 04:56:57.707 +00:00","caller":"task_scheduler.go:455","message":"Failed to execute task: index not exist","traceID":"217346bb9df061a8","stack":"github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:455\ngithub.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:480"}
{"level":"ERROR","time":"2021/11/04 04:57:00.025 +00:00","caller":"task_scheduler.go:455","message":"Failed to execute task: no index is created","traceID":"1d2dc28543b04db6","stack":"github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:455\ngithub.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:480"}
{"level":"ERROR","time":"2021/11/04 04:57:01.978 +00:00","caller":"task_scheduler.go:455","message":"Failed to execute task: index not exist","traceID":"613b8657e74ec5ba","stack":"github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:455\ngithub.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:480"}
{"level":"ERROR","time":"2021/11/04 04:57:03.687 +00:00","caller":"task_scheduler.go:455","message":"Failed to execute task: no index is created","traceID":"418e479b1f106c80","stack":"github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:455\ngithub.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:480"}
{"level":"ERROR","time":"2021/11/04 04:57:06.735 +00:00","caller":"task_scheduler.go:455","message":"Failed to execute task: index not exist","traceID":"b390bbe6aa169d8","stack":"github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:455\ngithub.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:480"}
{"level":"ERROR","time":"2021/11/04 04:59:30.412 +00:00","caller":"task_scheduler.go:455","message":"Failed to execute task: no index is created","traceID":"6ffd3c676f29bdc0","stack":"github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:455\ngithub.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:480"}
{"level":"ERROR","time":"2021/11/04 04:59:32.079 +00:00","caller":"task_scheduler.go:455","message":"Failed to execute task: no index is created","traceID":"53f63120727c47bf","stack":"github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:455\ngithub.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:480"}
{"level":"ERROR","time":"2021/11/04 04:59:33.933 +00:00","caller":"task_scheduler.go:455","message":"Failed to execute task: index not exist","traceID":"475481e816131af5","stack":"github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:455\ngithub.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:480"}
{"level":"INFO","time":"2021/11/04 04:59:42.685 +00:00","caller":"grpclog.go:37","message":"[core]parsed scheme: \"\""}
{"level":"INFO","time":"2021/11/04 04:59:42.685 +00:00","caller":"grpclog.go:37","message":"[core]scheme \"\" not registered, fallback to default scheme"}
{"level":"INFO","time":"2021/11/04 04:59:42.686 +00:00","caller":"grpclog.go:37","message":"[core]ccResolverWrapper: sending update to cc: {[{172.18.0.4:21121  <nil> 0 <nil>}] <nil> <nil>}"}
{"level":"INFO","time":"2021/11/04 04:59:42.686 +00:00","caller":"grpclog.go:37","message":"[core]ClientConn switching balancer to \"pick_first\""}
{"level":"INFO","time":"2021/11/04 04:59:42.686 +00:00","caller":"grpclog.go:37","message":"[core]Channel switches to new LB policy \"pick_first\""}
{"level":"INFO","time":"2021/11/04 04:59:42.686 +00:00","caller":"grpclog.go:37","message":"[core]Subchannel Connectivity change to CONNECTING"}
{"level":"INFO","time":"2021/11/04 04:59:42.686 +00:00","caller":"grpclog.go:37","message":"[core]Subchannel picks a new address \"172.18.0.4:21121\" to connect"}
{"level":"INFO","time":"2021/11/04 04:59:42.686 +00:00","caller":"grpclog.go:37","message":"[core]pickfirstBalancer: UpdateSubConnState: 0xc00404aa50, {CONNECTING <nil>}"}
{"level":"INFO","time":"2021/11/04 04:59:42.686 +00:00","caller":"grpclog.go:37","message":"[core]Channel Connectivity change to CONNECTING"}
{"level":"INFO","time":"2021/11/04 04:59:42.688 +00:00","caller":"grpclog.go:37","message":"[core]Subchannel Connectivity change to READY"}
{"level":"INFO","time":"2021/11/04 04:59:42.688 +00:00","caller":"grpclog.go:37","message":"[core]pickfirstBalancer: UpdateSubConnState: 0xc00404aa50, {READY <nil>}"}
{"level":"INFO","time":"2021/11/04 04:59:42.688 +00:00","caller":"grpclog.go:37","message":"[core]Channel Connectivity change to READY"}

**Comment by yanliang567** [comment]
Not reproduced locally with the same configs as describe above.
@spirit832 did you reinstall the Milvus after inserting and before searching? Also after inserting, how long did you wait before searching? I am asking because I doubt that it is dup to #7313 

/assign @spirit832 
/unassign

**Comment by spirit832** [comment]
感觉单机版确实不稳定，通过pymilvus持续插入数据时会经常死掉，测试过程中docker-compsed多次崩溃、停止、手动重启，组后导致已无法运行，重新装了一个，继续测试，暂时关闭这个 issues ，感谢支持。
