### ISSUE TITLE
[Bug]: milvus端口映射以后Milvus Enterprise Manager访问不了

### ISSUE THREAD

**Issue by w5688414** [milvus-io/milvus#11228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: 
 docker容器，centos宿主机
```

### Current Behavior

我把milvus映射成了8530，把Milvus Enterprise Manager映射到了8910，然后这两个容器都在同一台服务器上，然后用milvus Enterprise manager连接的时候就显示错误Network Error

但是python客户端能够链接：

```
from milvus import Milvus, IndexType, MetricType, Status

host='your ip'
milvus = Milvus(host=host, port='8530')
print(milvus)
```

### Expected Behavior

希望能够连接

### Anything else?

None

**Comment by shanghaikid** [comment]
Hi, what's your milvus version ?

**Comment by w5688414** [comment]
> Hi, what's your milvus version ?

1.1.1

**Comment by nameczz** [comment]
How did you fill the milvus address input in milvus em? @w5688414

**Comment by w5688414** [comment]
> How did you fill the milvus address input in milvus em? @w5688414

http://ip:8530

**Comment by nameczz** [comment]
> http://ip:8530
Because of we use docker to run em, so ip can't be localhost and 127.0.0.1.
Also milvus 1.1.1 will export 2 ports, 19530 is milvus grpc server, 19121 is http restful server and 19121 is em required.

**Comment by w5688414** [comment]
> 19121

thanks for your reply, it works

**Comment by yanliang567** [comment]
close as it is working now

**Comment by EeyoreLee** [comment]
> 19121

Thanks very much. I can't find the info anywhere in offical docs(v 1.0.0).
