### ISSUE TITLE
Invalid gpu resource: gpu0. Possible reason: gpu_resource_config does not match with the hardware.

### ISSUE THREAD

**Issue by flydragon2018** [milvus-io/milvus#1124]
**What is your question?**

I build from source. however when I start_sever.sh, I got the error message:
..........
..........
 [default] [SERVER] Failed to get gpu card number, cuda error:35

Invalid gpu resource: gpu0. Possible reason: gpu_resource_config does not match with the hardware.

how to configure GPU hardware ?

mine is 1050ti.

**Comment by JinHai-CN** [comment]
Check the requirements: https://milvus.io/docs/v0.6.0/guides/get_started/install_milvus/gpu_milvus_docker.md

What is the version of CUDA and NVIDIA driver?

**Comment by flydragon2018** [comment]
cuda 10.1  nvidia 435.  that should not be a problem.  ubuntu 18.04

I am not sure about GPU classification. mine gpu card is 1050ti.

I will try to compile from source on PC server with  better hardware.

**Comment by JinHai-CN** [comment]
We also use 1050 TI for testing, it's OK. Have you tried the Milvus distribution we released?

**Comment by flydragon2018** [comment]
I rebuilt it.  when I started the server,  got  following messages:
( I will try the docker and see what will happen)

Welcome to Milvus!
Milvus Release version: v0.6.0, built at 2020-02-14 19:36.16, with OpenBLAS library.
You are using Milvus GPU edition
Last commit id: a7d57d7a82268fb4d2b4a07755243543419aeac8

Loading configuration from: ../conf/server_config.yaml
Initializing log config from: ../conf/log_config.conf
S3 DISABLED !
GPU resources ENABLED !
2020-02-14 19:56:00,535 ERROR [default] [SERVER] Failed to get gpu card number, cuda error:35
Config check fail: Invalid gpu resource: gpu0. Possible reason: gpu_resource_config does not match with the hardware.
ERROR: Milvus server fail to load config file
Milvus server exit...

**Comment by JinHai-CN** [comment]
I find you are using the master branch which is development branch to build Milvus.

Can you disable GPU resource in config file to check if Milvus can run successfully?
Another issue: Have you tested if your GPU can work fine?

**Comment by flydragon2018** [comment]
../bin/milvus_server: error while loading shared libraries: libmysqlpp.so.3: cannot open shared object file: No such file or directory

 I update cuda  from 10.1 to 10.2.
now I got this error ?

**Comment by JinHai-CN** [comment]
Milvus depends on MySQL client shared library. You need to install it.

**Comment by yamasite** [comment]
@flydragon2018 

1. Check whether libmysqlpp.so.3 is correctly installed;
2. If libmysqlpp.so.3 is installed, check whether it is added to LD_LIBRARY_PATH.

This problem has been documented in the **troubleshooting** section in https://github.com/milvus-io/milvus/blob/master/INSTALL.md.
