### ISSUE TITLE
Implementation of one-command backup/restore processes

### ISSUE THREAD

**Issue by ndtreviv** [milvus-io/milvus#1127]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
A single REST command to backup a milvus cluster to a cloud based data storage service, such as AWS S3; as well as a single REST command to restore it from the cloud based repository.
The backup process should also verify the efficacy of the backup (similar to elasticsearch) 

**Describe alternatives you've considered**
The alternative as I understand it would be to backup the milvus data directories AND the MySQL table-index table, but even then you couldn't guarantee that the snapshot is atomic (what if someone creates table after you've backed up the data files but before you've backed up the MySQL table-index table?)

**Additional context**
N/A

**Comment by JinHai-CN** [comment]
1. In future release, milvus can store data into S3 or load data from S3. 
2. Yes, as you said, milvus should support atomic snapshot, otherwise the backup/restore function won't work. Or milvus has so-called 'maintenance mode', then administrator can do some data management under this mode.

Would you please describe your use case in detail? Will it be helpful, if milvus support S3 storage?

**Comment by ndtreviv** [comment]
I really like most of the way that the elasticsearch snapshots work.
The only thing I'd change is that in elasticsearch you have to insert the repository details, which then get replicated across the cluster - I'd like to specify that with the backup command.

So:
* issue a command, specify the repo location, the backup happens. 
* ability to query for backup status. 
* the backup mechanism to ensure that the files are all present and correct (not truncated or corrupted along the way). 
* backup details (location, status, time taken etc) stored in a manifest somewhere. This way I can automate the whole thing to happen regularly.
* issue a command to restore a backup, specify repo configuration (location etc). Restore happens.
* ability to query for restore status, which would list percentage complete of all files to be restored and an overall indicator: RESTORING, COMPLETE, FAILED (with reason).
* backup/restore mechanism to automatically work out how much bandwidth/processing power to use during both procedures

Ideally S3, but other people might prefer GCS or Azure's offering.

**Comment by yhmo** [comment]
v1.1.1 can store data in S3.
Inactive

**Comment by FT-JMendyk** [comment]
While support for storing data in S3 is a nice feature, support for one-command backup/restore process is not present in Milvus.
I think that @ndtreviv provided a clean and sensible set of requirements for the backup solution that many users find important and useful for Milvus to have.

@yhmo As such, could you please reopen this issue?
