### ISSUE TITLE
[Bug]: 重启Milvus服务后，检索延迟变高

### ISSUE THREAD

**Issue by mingyuz00** [milvus-io/milvus#11274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
1.1.1（CPU，docker部署）
- Deployment mode(standalone or cluster):
standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
java 1.0.0
- OS(Ubuntu or CentOS): 
Centos 7
- CPU/Memory: 
CPU: Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz  X56
Memory: 128GB
- GPU: 
- Others: 

Docker version 19.03.1, build 74b1e89


dimension：1024
index：IVFSQ8
index_file_size：1024
metric_type：IP
nlist：4096
nprobe：128
```

### Current Behavior

Milvus 中存有240万左右的数据，重启前延迟约120ms左右。
重启Milvus服务。
等加载完数据后，调用服务，显示检索延迟约为800ms以上。

### Expected Behavior

重启后，检索延迟与之前保持一致

### Anything else?

[日志和配置文件.zip](https://github.com/milvus-io/milvus/files/7474360/default.zip)

**Comment by yanliang567** [comment]
this is dup to #7313

**Comment by mingyuz00** [comment]
你好，我的Milvus版本是1.1.1。您合并的版本是2.0的。确实有这个问题吗？我需要等新版本发布才能解决嘛？

**Comment by yanliang567** [comment]
yes, please try to use Milvus 2.0 rcX release for latest updates
