### ISSUE TITLE
[Bug]:DataLoader worker (pid 30295) is killed by signal: Segmentation fault.  

### ISSUE THREAD

**Issue by leadorzf** [milvus-io/milvus#11281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.0rc6
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):v2.0.0-rc6-20210910-020f109
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz/32GB
- GPU: NVIDIA Corporation GP104 [GeForce GTX 1080]
- Others: run in docker
```

### Current Behavior

my job mainly embedding 10000 images intomuilvus, the core executing code is below
```python
from multiprocessing import cpu_count
        dataloader = torch.utils.data.DataLoader(dataset, num_workers=int(cpu_count()/2), batch_size=8) #10,48

        # with tqdm(dataloader) as bar:
        bar = tqdm(dataloader)
        for inputs, img_path in bar:
            with torch.no_grad():
                # output = model.process(inputs.to(device)).cpu().squeeze().numpy().tolist()
                # output = [output]
                # inputs = torch.stack([inputs], dim=0).cuda()
                output = model.process(inputs.to(device))
                output = output.squeeze(0).cpu().numpy().swapaxes(0,1)
                output = output.tolist()
            ids = milvus_client.insert(table_name, output)
            milvus_client.create_index(table_name)
            mysql_cli.create_mysql_table(table_name)
            mysql_cli.load_data_to_mysql(table_name, format_data(ids, img_path))
```
by the way, I'm running the code in docker; exactly, this problem is less happened with I am run in host computer;
In other say, "num_workers" and "batch_size" are the key factors which influence the bug happened

### Expected Behavior

the output error is:
E1104 20:34:57.420335912   30418 chttp2_transport.cc:1113]   Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"
ERROR: Unexpected segmentation fault encountered in worker.
 2021-11-04 20:34:58,610 ｜ ERROR ｜ grpc_handler.py ｜ handler ｜ 81 ｜ 
Addr [127.0.0.1:19530] wait_for_creating_index
Excepted error: DataLoader worker (pid 30295) is killed by signal: Segmentation fault. 
	{'API start': '2021-11-04 20:34:58.566836', 'RPC start': '2021-11-04 20:34:58.567066', 'Exception': '2021-11-04 20:34:58.610342'}
2021-11-04 20:34:58,610 ｜ ERROR ｜ grpc_handler.py ｜ handler ｜ 81 ｜ 
Addr [127.0.0.1:19530] create_index
Excepted error: DataLoader worker (pid 30295) is killed by signal: Segmentation fault. 
	{'API start': '2021-11-04 20:34:55.854759', 'RPC start': '2021-11-04 20:34:55.854877', 'Exception': '2021-11-04 20:34:58.610544'}
2021-11-04 20:34:58,610 ｜ ERROR ｜ milvus_helpers.py ｜ create_index ｜ 81 ｜ Failed to create index: DataLoader worker (pid 30295) is killed by signal: Segmentation fault.

**Comment by yanliang567** [comment]
@yhmo could you please help to look at this issue first?
/assign @yhmo 
/unassign

**Comment by xiaofan-luan** [comment]
seems to hit the same issue here https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-11128/17/pipeline
