### ISSUE TITLE
[BUG] Docker run welcome message: image server version is 0.5.0

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#113]
**Describe the bug**
Using docker run the current 0.5.1-version server, it still message with 0.5.0
`Welcome to Milvus!
Milvus Release version: v0.5.0, built at 2019-10-21 08:48.37
`
**Expected behavior**
The expected printout is 0.5.1

**Environment details**
0.5.1-image

**Screenshots**
N/A

**Additional context**
N/A

**Comment by yhmo** [comment]
Milvus version information should be automatically retrieved at pre-compile stage, by camke, from git branch name. Its seems something wrong with the branch name.

**Comment by yhmo** [comment]
relate to #206
