### ISSUE TITLE
About Sparse Vectors

### ISSUE THREAD

**Issue by canghaiyunfan** [milvus-io/milvus#1130]
whether milvus is support for sparse vectors?

**Comment by yamasite** [comment]
Thanks for your question! Could you please let us know your application scenario for sparse vectors?

**Comment by canghaiyunfan** [comment]
User Profile. There are many attributes, but not all attributes are required for each user.

**Comment by yamasite** [comment]
To clarify your scenario, a user profile is represented by a feature vector with 0/1 values representing different attributes. Because not all attributes are required for each user, a user profile is likely to contain a lot of zero values. Thus, support for sparse vectors will be desirable. Is that correct?

**Comment by canghaiyunfan** [comment]
yes, your understanding is correct. If dimension of attributes is very large, sparse vectors 
can improve efficiency. so i want to know whether milvus is support for sparse vectors. 
Thank you.

**Comment by yamasite** [comment]
Correct me if I'm wrong, but for high-dimensional vectors with 0/1 values, we assume you are referring to binary vectors, right? Milvus 0.7.0 will support **Jaccard/Tanimoto/Hamming** distance for binary vectors.

However, it will be great if you could share more information:
1. What metric do you wish to use to measure vector similarity?
2. What is the dimension of your vector data?

**Comment by canghaiyunfan** [comment]
1. I think the metric method should be the same as dense vectors.
2. Currently in the planning stage, the exact dimensions of vector data are uncertain, may be 10000 level.

you can refer to [pysparnn](https://github.com/facebookresearch/pysparnn)

**Comment by yamasite** [comment]
Thank you very much for your reply!

To sum up:

1. Milvus 0.7.0 will support **Jaccard/Tanimoto/Hamming** distance for binary vectors, with optimized performance for sparse data. For non-binary vectors, Milvus already supports **L2/IP** distance. 
2. Although Milvus still does not have an optimization mechanism for sparse data when it comes to non-binary vectors, Milvus supports **10000-level** dimensions for both binary and non-binary vectors.

**Comment by canghaiyunfan** [comment]
Thanks for your great job!

**Comment by JinHai-CN** [comment]
Fixed.
