### ISSUE TITLE
[Enhancement]: Support more  guaranteeTs  setting consistencies

### ISSUE THREAD

**Issue by nameczz** [milvus-io/milvus#11308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Related pr: https://github.com/milvus-io/milvus/pull/11276.

We need to support two more consistencies:

- Bounded Staleness: Set GuaranteeTs to an older timestamp, such as 1 minutes ago, the query can be executed immediately within a tolerable range.
- Read your own write (Session): Set GuaranteeTs to the client last write, in this way, every client will see all their
own data.

May have some code example is much better.

**Comment by DragonDriver** [comment]
Session consistency can be only implemented in sdk side. See also: https://github.com/milvus-io/pymilvus/pull/821 https://github.com/milvus-io/milvus/issues/9618
You can just keep the last write ts in client and then pass the ts into `guarantee_timestamp` when search a collection.

As for the `bounded staleness`, we have a configuration named `gracefulTime` in query nodes. When the gap between `guarantee_timestamp` and `service time` is less than the `gracefulTime`, search will be executed immediately. So you can choose different `gracefulTime` for better use.

@nameczz

**Comment by DragonDriver** [comment]
Closed. Feel free to reopen this if you have questions about this.
