### ISSUE TITLE
[Enhancement]:  Add design doc to explain the hybrid time in milvus.

### ISSUE THREAD

**Issue by nameczz** [milvus-io/milvus#11307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Like to know how to transform UTC timestamp to hybrid time and how to get UTC timestamp from hybrid time.

Also how to use it in Milvus.

**Comment by DragonDriver** [comment]
Already completed in https://github.com/milvus-io/milvus/pull/12002. Feel free to re-open this issue if have any confusing about the doc.
