### ISSUE TITLE
Implement Range Search as in FAISS

### ISSUE THREAD

**Issue by keotic** [milvus-io/milvus#1133]
FAISS supports range search on some index types, would be beneficial to Milvus as well.
For example, giving a query vectors and getting all the neighbour vectors up to a threshold radius.

**Comment by JinHai-CN** [comment]
Would you please describe the new feature as our template?

On the feature, do you want the function: Search by distance? Only these vectors are returned, which query vector and result vector distance are smaller than a given distance?

**Comment by keotic** [comment]
@JinHai-CN Thanks for the quick reply
Here is a link to the FAISS feature:
https://github.com/facebookresearch/faiss/wiki/Special-operations-on-indexes#range-search

It is as you described by "Search by Distance" instead of returning top_k neighbours, we would like to see all vectors which are in the radius of the given distance (smaller or equal for L2 metric, higher of equal to Inner Product metric)  
Thanks you

**Comment by JinHai-CN** [comment]
Then this function is in our roadmap and we will implement it in future release. Stay tuned.

**Comment by JeroenVanOort** [comment]
Do you have an update on this?

**Comment by JinHai-CN** [comment]
#3201

**Comment by aleks-walker** [comment]
The original question is more than a year old. Any progress?

**Comment by yhmo** [comment]
> The original question is more than a year old. Any progress?

Sorry, no progress. We have announced a new milvus with new architect, golang, cloud-native ability, and put major resource on the new milvus in recent half year. The old milvus(0.10.x) will be maintained, but mainly fix bugs. All the non-implemented features will be considered and designed on the new milvus. We plan to publish the new milvus at the end of this month(hopefully).

**Comment by xiaolongjiangkolena** [comment]
do you happen to implement this?

**Comment by xiaofan-luan** [comment]
> /reopen

This is on our plan of Milvus 2.2, but not the milvus 1.x version. See our roadmap here https://wiki.lfaidata.foundation/display/MIL/Milvus+2.X+Roadmap+and+Time+schedule
