### ISSUE TITLE
Why search_vectors will return multiple results for same id?

### ISSUE THREAD

**Issue by Yobol** [milvus-io/milvus#1134]
[
(id:6, distance:0.0),
(id:3, distance:18.353618621826172),
(id:4, distance:18.464111328125),
(id:3, distance:18.51197052001953),
(id:2, distance:18.548076629638672),
(id:5, distance:19.18881607055664),
(id:3, distance:19.32871437072754),
(id:3, distance:19.543493270874023),
(id:3, distance:20.899608612060547),
(id:4, distance:21.071413040161133)
]

**Comment by yhmo** [comment]
Milvus insert api allow user define ID for each vector, but it doesn't check duplicated ID. User can insert a vector with same ID for multiple times, and Milvus regards them as different vectors. So when you invoke search api to query, it could return multiple results with same ID.

**Comment by Yobol** [comment]
Thanks a lot~~
