### ISSUE TITLE
[DOC]希望有中文版Readme

### ISSUE THREAD

**Issue by akihoni** [milvus-io/milvus#114]
希望GitHub上能有一份中文版的Readme，感觉会更方便一些。

**Comment by jielinxu** [comment]
是的，目前我们是没有的。如果你感兴趣，欢迎提供中文版README

**Comment by shanghaikid** [comment]
官网有 https://milvus.io/docs/zh-CN/userguide/install_milvus/

**Comment by akihoni** [comment]
好的，我将上传一份已有的readme翻译到GitHub。

**Comment by jielinxu** [comment]
Great, thanks.

**Comment by jielinxu** [comment]
This is fixed in #129 .
