### ISSUE TITLE
[Enhancement]: better Java SDK binary vector support

### ISSUE THREAD

**Issue by danielfree** [milvus-io/milvus#11409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Detailed documentation and  maybe new helper functions in Java SDK to use binary vectors. 

### Why is this needed?

Milvus treats each byte(8 bit) as 8 dimensions, in Python&Go we can use 'unit8' to represent binary vector like '10101100', then directly convert to bytes.

However, in Java 'byte' is constraint to signed value(range -128~127), so it will take extra efforts to convert a binary vector string '10101100' to a Java byte, in order to put into Milvus Java SDK's method `InsertParam.withBinaryVectors(List<ByteBuffer>)` ,  since the `Byte.valueOf(binaryString, radix=2)` method will throw exception.

**Comment by yhmo** [comment]
Milvus 1.x or 2.0?
Now the java sdk for 2.0 is in testing. It also use ByteBuffer for binary vectors. 
Could you provide some example code for "Byte.valueOf(binaryString, radix=2) method will throw exception"?

**Comment by danielfree** [comment]
@yhmo 
I guess the caveat is:  we can't directly use `Byte.valueOf(binaryString, 2)` method, the possible solution goes like this

```
   String binaryString = "10010110";
   //this will throw exception
  //byte test = Byte.valueOf(binaryString, 2);
   System.out.println(intValue);  // 150
   int intValue = Integer.parseInt(binaryString, 2);
   //this will convert to byte as -106
   byte oneByte = (byte) intValue;
   System.out.println(oneByte);  // -106
   System.out.println(Byte.toUnsignedInt(oneByte));  //  150 
```

**Comment by yhmo** [comment]
> @yhmo Milvus 1.x with Java SDK
> 
> I guess the caveat is: we can't directly use `Byte.valueOf(binaryString, 2)` method, the possible solution goes like this
> 
> ```
>    String binaryString = "10010110";
>    //this will throw exception
>    //byte test = Byte.valueOf(binaryString, 2);
>    int intValue = Integer.parseInt(binaryString, 2);
>    System.out.println(intValue);  // 150
>    //this will convert to byte as -106
>    byte oneByte = (byte) intValue;
>    System.out.println(oneByte);  // -106
>    System.out.println(Byte.toUnsignedInt(oneByte));  //  150 
> ```

The author of this [article](https://blog.csdn.net/asd4687/article/details/51966212) also face similar problem. Java doesn't support unsigned byte, so programmers need to firstly cast it to short/int, then use 0xff to mask to byte.
