### ISSUE TITLE
[Bug]: Loadbalance still works when param dst_node_ids is wrong

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#11434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20211108-96cd935
- Deployment mode(standalone or cluster): cluster (and querynode replicas is 2)
- SDK version(e.g. pymilvus v2.0.0rc2):2.0.0rc9.dev2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Loadbalance still works when param dst_node_ids is wrongLoad balance

Suppose there are two querynodes with nodeID 5 and 6 respectively. When calling the loadbalance function, two situations are set:
Same as src and dst
src_node_id = 5
dst_node_ids = [5]
==============
dst does not exist
src_node_id = 5
dst_node_ids = [7]
In both cases, the segment on node5 is transferred to 6.

### Expected Behavior

Raise error

### Steps To Reproduce

```markdown
Suppose there are two querynodes with nodeID 5 and 6 respectively. When calling the loadbalance function, two situations are set:
Same as src and dst
src_node_id = 5
dst_node_ids = [5]
==============
dst does not exist
src_node_id = 5
dst_node_ids = [7]
```

### Anything else?

[lb-milvus.zip](https://github.com/milvus-io/milvus/files/7495628/lb-milvus.zip)

**Comment by xige-16** [comment]
pr #11648  has fixed the issue, trouble you check it @zhuwenxing

**Comment by zhuwenxing** [comment]
Verified and passed
