### ISSUE TITLE
[Bug]: Test logs are mixed up when using multiple processes

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#11494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: latest
- Deployment mode(standalone or cluster): both
- SDK version(e.g. pymilvus v2.0.0rc2): latest
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Test logs are mixed up when using multiple processes

### Expected Behavior

Test logs are separated based on process

**Comment by yanliang567** [comment]
@ThreadDao is it done now?

**Comment by binbinlv** [comment]
Fixed, and closed.
