### ISSUE TITLE
Add troubleshooting information to INSTALL.md about compile error caused by insufficient memory

### ISSUE THREAD

**Issue by yamasite** [milvus-io/milvus#1150]
## Report incorrect documentation

**Location of incorrect documentation**
https://github.com/milvus-io/milvus/blob/master/INSTALL.md

**Describe the problems or issues found in the documentation**
Sometimes `internal compiler error` is reported when building Milvus with docker images.

**Suggested fix for documentation**
Need to add troubleshooting information to INSTALL.md. The problem can be resolved by increasing the memory allocated to docker.

Need to fix a typo: `neeed`

**Comment by shengjun1985** [comment]
Done.
