### ISSUE TITLE
Delete vector function does not update table row count

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#1153]
**Describe the bug**

**Steps/Code to reproduce behavior**
```
        vector = gen_single_vector(dim)
        status, ids = connect.add_vectors(table, vector)
        assert status.OK()
        pdb.set_trace()
        status = connect.flush([table])
        assert status.OK()
        status = connect.delete_by_id(table, ids)
        assert status.OK()
        status = connect.flush([table])
        assert status.OK()
        status, res = connect.get_table_row_count(table)
        assert status.OK()
        assert res == 0
```
the above assert failed.
vector still existed in table after calling `delete_by_id`

in table `TableFiles`
```
sqlite> select * from TableFiles;
1|test_delete_1usOXqTq|1581400815169926000|1|1581400815169926000|1|2757500|1|1581400815731413|1581400815169928|1200111|0
```

**Expected behavior**

**Environment details**

**Screenshots**

**Additional context**

**Comment by youny626** [comment]
The vector is only soft-deleted (so it won't be searchable) but the data actually still exists on disk unless compact() is called, so I didn't update table row count in meta. Still contemplating on whether I should do that... @JinHai-CN do you have any thoughts about that?

**Comment by JinHai-CN** [comment]
Since the vector is removed, meta should be updated. And compact won't lead to meta update.

**Comment by del-zhenwu** [comment]
fixed
