### ISSUE TITLE
milvus crash while search_by_id on empty partition AFTER search_by_id on table

### ISSUE THREAD

**Issue by liangliu** [milvus-io/milvus#1158]
**Describe the bug**
CPU version， here is the reproduce steps

1, create table and create partition
2, add data to table
3, search_by_id on table
4, search_by_id on the EMPTY partition

milvus crash

**Steps/Code to reproduce behavior**
**Expected behavior**
**Environment details**
**Screenshots**
**Additional context**

**Comment by liangliu** [comment]
update reproduce steps and add Mo to notice this issue

**Comment by youny626** [comment]
fixed

**Comment by liangliu** [comment]
verified
