### ISSUE TITLE
[Bug]: Config of simdType doesn't take effect

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#11645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20211111-dba0ae4
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc9.dev2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When config of simdType is set to avx, the true simdType getting from milvus is sse4_2
When config of simdType is set to avx512, the true simdType getting from milvus is avx2

### Expected Behavior

smidType in config and milvus system are same

### Steps To Reproduce

```markdown
cd `tests/python_client/customize`
run `pytest -s -v test_simd_compat.py`
```

### Anything else?
```
       log.info(f"milvus simdType: {mil.simd_type}")
>       assert str(mil.simd_type).lower() == simd.lower()
E       AssertionError: assert 'sse4_2' == 'avx'
E         - avx
E         + sse4_2
```
```
>       assert str(mil.simd_type).lower() == simd.lower()
E       AssertionError: assert 'avx2' == 'avx512'
E         - avx512
E         ?    --
E         + avx2
```

_No response_

**Comment by yanliang567** [comment]
@cydrain could you please help to check this issue, I am not sure whether it is configured wrong in milvus init or returns wrong in getMilvusMetrics

/assign @cydrain 
/unassign

**Comment by cydrain** [comment]
When Milvus bootup, it will check if configured SIMD is supportable, if not, lower level SIMD will be set.
| configuration | returned SIMD |
-------------------------------------------
| auto | avx512/avx2/sse4_2|

**Comment by yanliang567** [comment]
@zhuwenxing so does the node support all the types in test env?

**Comment by zhuwenxing** [comment]
> @zhuwenxing so does the node support all the types in test env?

No!  Some nodes don't support AVX512.

**Comment by zhuwenxing** [comment]
> When Milvus bootup, it will check if configured SIMD is supportable, if not, lower level SIMD will be set.
> 
> configuration	possible returned SIMD
> auto	avx512 / avx2 / sse4_2
> avx512	avx512 / avx2 / sse4_2
> avx2	avx2 / sse4_2
> avx	sse4_2
> sse4_2	sse4_2

This makes sense! 
The result follows this rule

**Comment by zhuwenxing** [comment]
> @zhuwenxing so does the node support all the types in test env?

So we need to modify  the assertion to follow this rule
