### ISSUE TITLE
[Bug]: Milvus 2.0 rc8 collection load error

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#11651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:milvus 2.0 rc8
- Deployment mode(standalone or cluster): docker compose cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.0.0rc8
- OS(Ubuntu or CentOS): 
- CPU/Memory: 58G，8core
- GPU: 
- Others:
```

### Current Behavior

1. Insert 10w data, create IVF sq8 index.
2. Then load data error, as shown in the figure appears
![1](https://user-images.githubusercontent.com/34296482/141266167-1d033ecd-9bd1-4228-a3c9-6d0e847dd085.jpg)
[log.txt](https://github.com/milvus-io/milvus/files/7518994/log.txt)
[milvus_logs.zip](https://github.com/milvus-io/milvus/files/7519583/milvus_logs.zip)

**Comment by spirit832** [comment]
关注一下，刚刚发生了同样的问题
standalone  
2.0.0rc7
Ubuntu 
16GMemory

Data: 25000+
![QQ图片20211111174647](https://user-images.githubusercontent.com/19635040/141276258-96dcbf8d-e5f5-4b25-bec1-a512a3cd9ea6.png)
[log.txt](https://github.com/milvus-io/milvus/files/7519419/log.txt)

**Comment by xige-16** [comment]
The dmchannel Request written by querycoord to etcd contains a large number of duplicate unflushedSegment/flushed segment info, exceeding the etcd limit

**Comment by xige-16** [comment]
The problem occurs when there is a large number of partitions under the same colection, and then the load can go wrong

**Comment by xige-16** [comment]
pr #11746 has fixed the issue

**Comment by yanliang567** [comment]
@jingkl could you please help to verify the fix?

/assign @jingkl 
/unassign @xige-16

**Comment by jingkl** [comment]
ok，I will verify
