### ISSUE TITLE
search with non-exist id in partition, results returned not stable

### ISSUE THREAD

**Issue by liangliu** [milvus-io/milvus#1165]
**Describe the bug**
here is the thing:

if the partition is empty, search with non-exist id will return []
if there're data stored in the partition, the results is like this:
[[
(id:-1, distance:0.0),
(id:-1, distance:0.0),
(id:-1, distance:0.0),
(id:-1, distance:0.0),
(id:-1, distance:0.0),
(id:-1, distance:0.0),
(id:-1, distance:0.0),
(id:-1, distance:0.0),
(id:-1, distance:0.0),
(id:-1, distance:0.0)
]]

**Steps/Code to reproduce behavior**
**Expected behavior**
**Environment details**
**Screenshots**
**Additional context**

**Comment by youny626** [comment]
I think that's the expected behaviour?

**Comment by liangliu** [comment]
I can accept these behaviour, however this should also applied to table level
