### ISSUE TITLE
[Bug]: Drop collection timeout

### ISSUE THREAD

**Issue by xige-16** [milvus-io/milvus#11712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Drop collection may time out
[Uploading artifacts-milvus-standalone-PR-11648-1-pymilvus-e2e-logs.tar.gz…]()

**Comment by xiaofan-luan** [comment]
duplicate with #11709, close for now
