### ISSUE TITLE
[Bug]:  When I did a vector search, the service returned rpc error and rpc status =4  

### ISSUE THREAD

**Issue by wolfju** [milvus-io/milvus#11721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.0.0rc8 
- Deployment mode: standalone
- SDK version: pymilvus v2.0.0rc8 
- OS: Ubuntu
- CPU/Memory: cpu :2 m  , memory 4g
```

### Current Behavior

Milvus service returned rpc error and status=4  two hours later

![image](https://user-images.githubusercontent.com/22097367/141425020-d9d83882-5feb-4fa0-8837-158de588bb2a.png)

### Expected Behavior

right response

### Steps To Reproduce

```markdown
1. We online a search service yesterday ，and used it to do searching which we packaged a asynchronous rpc library . The milvus-service  was able to search normally at first, but the service returned rpc error and status=4  two hours later; 
2. I  try to searching same collection by  pymilvus-v2.0.0rc8 , get the same result  ，and it has not been restored yet ！
```

### Anything else?

![image](https://user-images.githubusercontent.com/22097367/141425002-c0ee85b7-446c-4a41-bd3d-aa0dbaeb3492.png)

**Comment by xiaofan-luan** [comment]
Hi wolfju, how is the cluster now? can you offer logs so we can have some knowledge about what the cluster is going on?

**Comment by wolfju** [comment]
> Hi wolfju, how is the cluster now? can you offer logs so we can have some knowledge about what the cluster is going on?

> I waited for a few hours and haven't recovered and then I redeployed the milvus-cluster in standalone mode  ;
> This the cluster log in question at the time from milvus-standalone-standalone-68c69cf86f-lh8bs
[milvus.log](https://github.com/milvus-io/milvus/files/7535655/milvus.log)

**Comment by xiaofan-luan** [comment]
> > Hi wolfju, how is the cluster now? can you offer logs so we can have some knowledge about what the cluster is going on?
> 
> > I waited for a few hours and haven't recovered and then I redeployed the milvus-cluster in standalone mode  ;
> > This the cluster log in question at the time from milvus-standalone-standalone-68c69cf86f-lh8bs
> > [milvus.log](https://github.com/milvus-io/milvus/files/7535655/milvus.log)

Great， we are looking into it
