### ISSUE TITLE
[Bug]: Unittest failed with  pthread lock: Invalid argument

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#11748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:6d11f45
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Unit test failed with error:
```
pthread lock: Invalid argument
SIGABRT: abort
PC=0x7fe99448cfb7 m=0 sigcode=18446744073709551610
```

### Expected Behavior

Unit test passed

### Steps To Reproduce

```markdown
Run ut
```

### Anything else?

https://github.com/milvus-io/milvus/runs/4188623316?check_suite_focus=true

**Comment by yanliang567** [comment]
@xiaofan-luan please help to assign
/assign @xiaofan-luan 
/unassign

**Comment by fishpenguin** [comment]
Working on it.
