### ISSUE TITLE
[Bug]: Search hangs after inserting vectors.

### ISSUE THREAD

**Issue by greensea** [milvus-io/milvus#11845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: d1f4106
- Deployment mode(standalone or cluster): docker-compose standalone
- SDK version(e.g. pymilvus v2.0.0rc2): golang
- OS(Ubuntu or CentOS): Debian
- CPU/Memory: Ryzen 2600X, 32G Mem
- GPU: None
- Others:
```

### Current Behavior

When I search for a vector, I got no results, and there is no timeout or other errors occurs, the search just hangs.

### Expected Behavior

I should get search results in seconds.

### Steps To Reproduce

```markdown
1. Create a collection and insert vectors
2. Search for a vector
3. It hangs
```

### Anything else?

#2692 is similar to this, but that issue is related to an old version 0.1.1

There are 1,655,415 vectors in the collection, each vector is 512 dimensions.
When there are only 400,000+ vectors in the collection, I search for a vector and get results in seconds. Today I search the vector again and milvus hangs. I wait more than 1 hour but got no response, no timeout or error. Then I stop milvus, then I got "error reading from server: EOF".

After restart milvus, I still can not get the search results. 

I noticed milvus is keep printing logs repeatedly that seem abnormal, I attach the logs below.

[repeated-abnormal-logs.log](https://github.com/milvus-io/milvus/files/7538555/repeated-abnormal-logs.log)

**Comment by xiaofan-luan** [comment]
what milvus version is it? can you offer logs of the whole standalone log? Thanks

**Comment by greensea** [comment]
I am use docker image milvusdb/milvus:v2.0.0-rc8-20211104-d1f4106.
The whole standalone log is huge since it is keep printing log repeatedly. I copy the first 10 minutes logs after milvus started.

[whole-log.log](https://github.com/milvus-io/milvus/files/7538841/whole-log.log)

**Comment by yanliang567** [comment]
@greensea it seems that it failed to connected to etcd service, please try to reinstall a milvus.
[`32mmilvus-standalone |[0m [2021/11/15 13:04:42.879 +00:00] [WARN] [grpclog.go:46] ["[core]grpc: addrConn.createTransport failed to connect to {etcd:2379 etcd <nil> 0 <nil>}. Err: connection error: desc = \"transport: Error while dialing dial tcp 172.23.0.3:2379: i/o timeout\". Reconnecting..."]`

**Comment by greensea** [comment]
@yanliang567 I remove the container and start a new container, but the issue still exists. 
I checked etcd and confirm it is started, this is the whole log.
[Uploading whole-log2.log…]()

**Comment by yanliang567** [comment]
@xige-16 could you please help to check this issue?
/assign @xige-16 
/unassign

**Comment by fishpenguin** [comment]
Working on this issue...

**Comment by fishpenguin** [comment]
@greensea Did you call collection.load() before search? If so, can you print your test code here.

**Comment by greensea** [comment]
@fishpenguin I didn't call collection.load() in code, but I load the collection into memory in milvus-insight, and milvus-insight shows the collection is `Loaded For Search'.

![2021-11-17 13-01-13 创建的截图](https://user-images.githubusercontent.com/619187/142139166-13c69f0c-23f0-42d5-a4cb-fa83f2064dad.png)

The code is simple, the main part is:

```
func (s *SMilvus) Search(vectors []float32, nprob int, ktop int) ([]int64, []float32, error) {
    c := s.New()
    defer c.Close()
    
    vectors = NormalizeFloat32(vectors)
    vec := entity.FloatVector(vectors)
        
    log.Println("开始搜索一个向量")
    
    ctx := context.Background()
    sp, _ := entity.NewIndexIvfPQSearchParam(nprob)
    
    stime := time.Now()
    sr, err := c.Search(ctx, "b_face", []string{}, "", []string{"id"}, []entity.Vector{vec}, "vectors", entity.IP, ktop, sp)
    
    log.Printf("搜索完了，耗时 %0.3fs", time.Now().Sub(stime).Seconds())
    if err != nil {
        log.Printf("搜索向量发生错误: %s", err)
        return nil, nil, err
    }
    ...
```

It hangs at Search() method.

Even I search the vector in milvus-insight, the search is also timeout.

![2021-11-17 13-00-59 创建的截图](https://user-images.githubusercontent.com/619187/142139291-4d7daedb-061b-4295-a8fe-150a150a36b7.png)

**Comment by fishpenguin** [comment]
I'm trying to reproduce this issue but still can't. And can't find the reason from the first 10 minutes log.
> I am use docker image milvusdb/milvus:v2.0.0-rc8-20211104-d1f4106.
The whole standalone log is huge since it is keep printing log repeatedly. I copy the first 10 minutes logs after milvus started.

Can you print the last 10 minutes log before milvus stop.

**Comment by fishpenguin** [comment]
@greensea btw, when you restarted the milvus docker, did you restart the minio and etcd docker? If not, you can try to restart the docker-compose which contains minio and etcd, and then restart the milvus docker.

**Comment by greensea** [comment]
@fishpenguin 

Recently I remove docker and then reinstall a new one, the logs is removed. But I can reproduce this issue, I can upload another log file.
I copy the dataset (including milvus, etcd and minio)  to an other server, and start a new docker, this issue still exists. I think this issue may relate to data?
And, in this new server, I got smaller and more pure log file, only 400+KB.

[whole-log3.log](https://github.com/milvus-io/milvus/files/7553286/whole-log3.log)

Yes, when I restart milvus, I also restart etcd and minio.

And I found this issue can be reproduced by using my dataset, just copy the dataset and use the docker-compose config file to start the milvus, this issue can be easily reproduced.  The only problem is that the data size is 7.6G. 
If you are ok, I can upload the dataset to my NAS for you to download.

**Comment by fishpenguin** [comment]
> If you are ok, I can upload the dataset to my NAS for you to download.

I'm ok.

**Comment by fishpenguin** [comment]
>And, in this new server, I got smaller and more pure log file, only 400+KB.

I didn't see that load was called in the "whole-log3.log", please make sure that you have called collection.load() when the new milvus server started, or you can try to call load again and then search to see if the issue still exists.

**Comment by greensea** [comment]
@fishpenguin This is intresting. 
Yes, after start new containers with the dataset, I did not call collection.load(), and not load the collection via milvus-insight. But the data is already `Loaded For Search`.
So there is the questions:
1. Should I load the data into memory after milvus restart?
2. If I have to load the data into memory after milvus restart, is it expected behavior that milvus-insight shows the data is `Loaded For Search', even if I am not load the data manually?

On the other side, if the data is not loaded into memory, I should got an error message tells me that the collection is not loaded into memory. I saw this error message before. But this time, the search just hangs and no error messages return.

**Comment by greensea** [comment]
I just do a test:

1. Unload the collection via milvus-insight (because milvus-insight tells me the collection is `Loaded For Search`)
2. Load the collection via milvus-insight.

After this actions, the search works well, I can get search results now.

Seems I have to reload the collection after milvus restart even if it milvus-insight tells me the collection is already loaded?

**Comment by fishpenguin** [comment]
> Should I load the data into memory after milvus restart?

Yes, you need to call load after milvus restart.

> If I have to load the data into memory after milvus restart, is it expected behavior that milvus-insight shows the data is `Loaded For Search', even if I am not load the data manually?

After milvus start, the milvus-insight `Loaded For Search` will only be shown after you call load, so if the `Loaded For Search` shows green when you doesn't call load, the milvus-insight isn't right.

> Seems I have to reload the collection after milvus restart even if it milvus-insight tells me the collection is already loaded?

Definitely you should load the collection after milvus restart. And in your case, it may be a milvus-insight bug that the `Loaded For Search` shouldn't be shown when load is not called after milvus restart.

**Comment by fishpenguin** [comment]
BTW, please remember to refresh the milvus-insight web page after you restart the milvus server, or the web page just shows the previous load state.

**Comment by greensea** [comment]
@fishpenguin Thanks for the explanation. So I have to load the collection after restart.
But... this issue is not so simple... I just check the collection status with milvus API:
```
curl http://10.26.0.44:8000/api/v1/collections
```
```
{"statusCode":200,"data":[{"collection_name":"b_face","schema":{"fields":[{"type_params":[],"index_params":[],"fieldID":"100","name":"id","is_primary_key":true,"description":"","data_type":"Int64","autoID":false},{"type_params":[{"key":"dim","value":"512"}],"index_params":[],"fieldID":"101","name":"vectors","is_primary_key":false,"description":"","data_type":"FloatVector","autoID":false}],"name":"b_face","description":"","autoID":false},"description":"","autoID":false,"rowCount":"1661415","id":"429029219384164353","isLoaded":true,"createdTime":"1636616590058"}]}
```
Milvus just tell me the collection is loaded, but I did not load the collection after restart.

**Comment by xige-16** [comment]
> @fishpenguin This is intresting. Yes, after start new containers with the dataset, I did not call collection.load(), and not load the collection via milvus-insight. But the data is already `Loaded For Search`. So there is the questions:
> 
> 1. Should I load the data into memory after milvus restart?
> 2. If I have to load the data into memory after milvus restart, is it expected behavior that milvus-insight shows the data is `Loaded For Search', even if I am not load the data manually?
> 
> On the other side, if the data is not loaded into memory, I should got an error message tells me that the collection is not loaded into memory. I saw this error message before. But this time, the search just hangs and no error messages return.

if you copy the dataset (including milvus, etcd and minio) to an other server, then you don't need to load again，Because the etcd has recorded that you called load collection before restart

**Comment by xige-16** [comment]
> > Should I load the data into memory after milvus restart?
> 
> Yes, you need to call load after milvus restart.
> 
> > If I have to load the data into memory after milvus restart, is it expected behavior that milvus-insight shows the data is `Loaded For Search', even if I am not load the data manually?
> 
> After milvus start, the milvus-insight `Loaded For Search` will only be shown after you call load, so if the `Loaded For Search` shows when you doesn't call load after restart, the milvus-insight isn't right.
> 
> > Seems I have to reload the collection after milvus restart even if it milvus-insight tells me the collection is already loaded?
> 
> Definitely you should load the collection after milvus restart. And in your case, it may be a milvus-insight bug that the `Loaded For Search` is shown when load is not called after milvus restart.

restarting milvus use old etcd, so if load collection has been called before restart, then repeated load is unnecessary

**Comment by fishpenguin** [comment]
@greensea  Sorry I just made a mistake, if the etcd hasn't been stopped and removed, milvus doesn't need to reload after restart. because etcd has recorded the loaded state and will automatically told the querycoord to load collection after milvus restart.

**Comment by greensea** [comment]
emm... so may be there is something happen while the querycoord automatically load the collection?

The issue is now: 
1. I start new container with the dataset, the collection is shown loaded. But the search hangs.
2. Then I unload the collection and load the collection again, now I can get the search result.

I am uploading the dataset, will update later

**Comment by xige-16** [comment]
It looks like when the querycoord restarts, the data that was loaded before the restart fails to recover on the querynode, and we're fixing it

**Comment by xige-16** [comment]
duplicate with #11792 , We'll fix it quickly. @greensea

**Comment by greensea** [comment]
Not sure if the dataset is needed for you, just put the link here, feel free to use it.

https://ii.bbxy.net:5443/sharing/LrqXYN7I7
sha256: 7d2df98c52b790ee41d8635e05161794eb6c24ee9593c6c442bf7bc0be60248a  milvus.tar.xz


docker-compose.yaml:
```
version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    volumes:
      - /home/gs/milvus/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2020-12-03T00-03-10Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - /home/gs/milvus/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.0.0-rc8-20211104-d1f4106
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - /home/gs/milvus/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvus
```
Remember change the path mapping in docker-compose.yaml, there are 3 lines to be modify.

**Comment by greensea** [comment]
I have started a new container using image milvusdb/milvus-dev:master-20211120-bf391f2 with the current dataset.
This docker image is built after #12145 pull request so I expected this issue should be fixed.
But the search still hangs. And even more, I tried to unload the collection and load the collection via milvus-insight, the search still hangs. On the previous version, if I unload then load the collection, the search gives results.

Should I delete the dataset and insert the features again?

This is the logs:
[whole-log4.log](https://github.com/milvus-io/milvus/files/7578330/whole-log4.log)

**Comment by greensea** [comment]
Sorry, I just got the search results. It not hangs. It took 6m34s for the search return results. 
But I just unload and reload the collection, currently, I can not verify this issue is fixed, let me see if the search hangs in the next few days.

**Comment by xiaofan-luan** [comment]
> 

Great, thanks greensea. It might be too long for a search if takes 6minutes, what kind of search it is? did you try to build index on top of the data?

**Comment by greensea** [comment]
@xiaofan-luan Thanks. Several days passed and I never saw this issue again, it should be fixed.
And about the 6min search, this is the first search after miluvs start, I think milvus is loading data into memory or reading data from disk. There are other services eating disk IO, and the disk is HDD, these may cause milvus to take a long time to read data. After the first search, milvus return results in seconds.
