### ISSUE TITLE
[Bug]: Loadbalance doesn't take effect when a new querynode added

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#11889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: `fd45a7e`
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc9.dev2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The memory of high load querynode continues to grow

### Expected Behavior

The load should transfer to the new added querynode

### Steps To Reproduce

```markdown
deploy milvus with 2 query node
load collection, insert data and flush to generate memory stress
update helm to set querynode replicas as 3
load collection, insert data and flush
```

### Anything else?

![image](https://user-images.githubusercontent.com/12268675/141933832-0f2681a7-5ca4-4f19-b821-a9546d6ac9ca.png)

[lb-milvus 2.zip](https://github.com/milvus-io/milvus/files/7543897/lb-milvus.2.zip)

**Comment by xige-16** [comment]
The amount of data is too small to trigger balance, and the second querynode memory rise is due to handoff

**Comment by xige-16** [comment]
The first querynode memory rises because 180,000 pieces of data are inserted, divided into 120 growing segments, each segmenting is pre-allocated with 32,768 rows of data, so about 400M of space is pre-allocated

**Comment by xige-16** [comment]
The testing process needs to be redesigned

**Comment by zhuwenxing** [comment]
new test process:
1. Deploy miluvus (single querynode) and set the memory limit of querynode to 2G
2. Create collection, insert data (amount = 3000, as warming up ), create index, load, insert data continuously(600000)
3. By `helm upgrade lb-milvus milvus/milvus --set queryN ode.replicas = 2 --use-values`, add a querynode node.
4. Continue to insert data (300000)and observe the memory rise of the two querynodes.

![image](https://user-images.githubusercontent.com/12268675/142580806-de1c161b-b1f9-4f45-80cd-5a87cb1eff60.png)
[lb-milvus-querycoord-77dfc4fc64-8g4bk.log](https://github.com/milvus-io/milvus/files/7568413/lb-milvus-querycoord-77dfc4fc64-8g4bk.log)


From the log information, the load balance and handoff are both triggered
