### ISSUE TITLE
[Bug]: load collection with unflushed segment failed

### ISSUE THREAD

**Issue by sunby** [milvus-io/milvus#11923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

This segment has no binlog 
![image](https://user-images.githubusercontent.com/9817127/141978884-896c6327-5b62-4122-b8c3-27fd0f7d6738.png)

Then watchDmChannel failed
![image](https://user-images.githubusercontent.com/9817127/141979030-683320a9-2ccc-4f5a-bbd1-7a7231f18d5e.png)

And queryCoord will rollback loadCollectionTask

**Comment by xige-16** [comment]
pr #11888 has fixed the issue
