### ISSUE TITLE
[Bug]: Customize segment size does not work

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#11952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20211116-6542b09
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
```

### Current Behavior

segment size keeps 512MB when trying to customize it to 128MB

### Expected Behavior

segment size changes to 128MB after customize config

### Steps To Reproduce

```markdown
1. deploy Milvus 2.0 by Operator with customized segment size as below
```
apiVersion: milvus.io/v1alpha1
kind: MilvusCluster
metadata:
  name: milvus-6542b09
  namespace: chaos-testing
  labels:
    app: milvus
spec:
  components:
    image: "harbor.zilliz.cc/milvus/milvus:master-20211116-6542b09"
  config:
    dataCoord:
      segment:
        maxSize: 512
```
2. insert 128d - 2 million entities 
3. flush and load the collection
4. utility.get_query_segment_info to check the size of segment
```

### Anything else?

The root cause is that the customized configs in milvus.yaml was overwritten by same keys-values in component.yaml.
maybe remove the same key in component.yaml

**Comment by xiaofan-luan** [comment]
@yanliang567 is this not working?

**Comment by binbinlv** [comment]
@zhuwenxing please verify this issue? If fixed, please close it. Thanks. 

Cancel urgent label first.

**Comment by zhuwenxing** [comment]
Verified and passed.
When segment max size is set as 128, the sealed segment info is as follow:
```
 segmentID: 429277795866640385
collectionID: 429277778565136385
partitionID: 429277778565136386
mem_size: 102795264
num_rows: 194688
index_name: "_default_idx"
indexID: 429277785197379585
nodeID: 7
state: Sealed
```
102795264 //1024//1024 =98MB  which is about equal to 128 * 0.75
