### ISSUE TITLE
grpc: Server.Serve failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams received bogus greeting from client: \\\"GET / HTTP/1.1\\\\r\\\\nUser-Age\\\"\""]

### ISSUE THREAD

**Issue by chengduhaha** [milvus-io/milvus#11983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): v2.0.0rc2
- OS(Ubuntu or CentOS): centos 7.9
- CPU/Memory:
- GPU: 
- Others: k8s cluster
```

### Current Behavior

I deployed k8s distributed milvus v2.0.0 following the official document, but when i requested proxy port 19530, the log of miluvs proxy's pod printed "grpc: Server.Serve failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams received bogus greeting from client: \\\"GET / HTTP/1.1\\\\r\\\\nUser-Age\\\"\""]"

### Expected Behavior

expect to requset milvus proxy 19530 port susccessfully

### Steps To Reproduce

```markdown
I deployed k8s distributed milvus v2.0.0 following the official document, but when i requested proxy port 19530, the log of miluvs proxy's pod printed "grpc: Server.Serve failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams received bogus greeting from client: \\\"GET / HTTP/1.1\\\\r\\\\nUser-Age\\\"\""]"
```

**Comment by yanliang567** [comment]
@chengduhaha could you copy the commands that you issued to deploy Milvus? could you please upgrade your pymilvus to rc8 and retry

**Comment by chengduhaha** [comment]
> @chengduhaha could you copy the commands that you issued to deploy Milvus? could you please upgrade your pymilvus to rc8 and retry

i install milvus cluster by helm chart on k8s  and my k8s is on rancher, command is 
"helm repo add milvus https://milvus-io.github.io/milvus-helm/"
"helm install --set cluster.enable=true --set persistence.enable=true --set mysql.enable=true milvus-cluster   -f values.yaml"
yes, i have upgraded the pymilvus using comamands "python3 -m pip install pymilvus==2.0.0rc8
"

kubectl get svc -n milvus2
NAME                                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                               AGE
milvus-cluster                       NodePort    10.43.142.119   <none>        19530:30787/TCP,9091:31921/TCP        20h

and i request the serivce port whose containerPort is 19530 "curl http://10.133.22.111:30787


the pod log show

[2021/11/17 06:53:02.818 +00:00] [WARN] [grpclog.go:46] ["[core]grpc: Server.Serve failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams received bogus greeting from client: \\\"GET / HTTP/1.1\\\\r\\\\nUser-Age\\\"\""] 
[2021/11/17 06:53:04.528 +00:00] [WARN] [grpclog.go:46] ["[core]grpc: Server.Serve failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams received bogus greeting from client: \\\"GET / HTTP/1.1\\\\r\\\\nUser-Age\\\"\""] 
[2021/11/17 06:54:08.212 +00:00] [WARN] [grpclog.go:46] ["[core]grpc: Server.Serve failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams received bogus greeting from client: \\\"GET / HTTP/1.1\\\\r\\\\nUser-Age\\\"\""]

**Comment by yanliang567** [comment]
/assign @LoveEachDay 
@LoveEachDay could you please help to check this issue?

/unassign @chengduhaha

**Comment by LoveEachDay** [comment]
We only provide gRPC service by now, you cannot use curl to make a request.
/unassign

**Comment by yanliang567** [comment]
@chengduhaha  please check

> We only provide gRPC service by now, you cannot use curl to make a request. /unassign
