### ISSUE TITLE
[Bug]: If one querynode get search assignment by querycoord and restart, then querycoord will hang and pymilvus hangs too.

### ISSUE THREAD

**Issue by JamCrash** [milvus-io/milvus#12079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvus rc8
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

one querynode get assignment by querycoord and restart, then querycoord will hang and pymilvus hangs too.
the restart querynode will not load and search antomatically

**Comment by yanliang567** [comment]
@zhuwenxing it sounds like chaos test against query node, have you see this issue before?
/assign @zhuwenxing 
/unassign
