### ISSUE TITLE
[Enhancement]: Need Pytest  to support service name

### ISSUE THREAD

**Issue by jennyli-z** [milvus-io/milvus#12107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

pytest can pass service name instead of ip to `host`.

### Why is this needed?

use service name to do the test in ci pipeline so that we can remove `kubectl` from e2e test (pytest )stage

### Anything else?

![image](https://user-images.githubusercontent.com/93511422/142413628-cba9c865-aeee-4b77-a56e-6a0a3929016a.png)

**Comment by yanliang567** [comment]
@binbinlv I think we don't need to check the IP any longer, as we are able to support host name connection.
/assign @binbinlv 
/unassign

**Comment by binbinlv** [comment]
@jennyli-z  fixed, could you help to verify, and close this issue if it is OK now. 

Thanks.

**Comment by jennyli-z** [comment]
verified & close
