### ISSUE TITLE
[Bug]: milvus2.0-rc8      并行插入milvus，导致数据写入不一致

### ISSUE THREAD

**Issue by wuweicheng39** [milvus-io/milvus#12132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvus2.0-rc8
- Deployment mode(standalone or cluster):milvus2.0
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus=2.0.0rc8
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

向量数据被覆盖

**Comment by wuweicheng39** [comment]
插入1500万的图片数据，图片的id和图片对应的特征向量。搜索展示效果时候，用原图搜索，竟然结果L2距离为0并且排名第一位的是别的图片。经过个人分析，应该是数据并行插入导致问题。两个pk对应的向量数据，互换了。

**Comment by DragonDriver** [comment]
> 插入1500万的图片数据，图片的id和图片对应的特征向量。搜索展示效果时候，用原图搜索，竟然结果L2距离为0并且排名第一位的是别的图片。经过个人分析，应该是数据并行插入导致问题。两个pk对应的向量数据，互换了。

能否比对一下两张图片所对应的特征向量是否相同？ @wuweicheng39

**Comment by wuweicheng39** [comment]
已经比对，两张图片，特征向量当然不一样。

**Comment by DragonDriver** [comment]
能否麻烦提供一下复现步骤？ @wuweicheng39

**Comment by wuweicheng39** [comment]
1500万的图片插入，同时开启20个进程进行插入操作，如何进行复现？？我只能把我的图片搜索效果，截图给你看看。

**Comment by wuweicheng39** [comment]
我一直关注milvus2.0，之前版本rc版本都没敢用，看到了rc8是ga，就直接试试几千万的图片量，没有想到会遇到这类问题，请求快速解决。

**Comment by DragonDriver** [comment]
> 已经比对，两张图片，特征向量当然不一样。

额，搜索结果会带有向量的 pk，返回的 pk 是否和原来的匹配呢？

**Comment by wuweicheng39** [comment]
这些问题都检查了，我的判断，就是并行插入导致数据不一致。如何把搜索结果贴给你看呢？？？

**Comment by DragonDriver** [comment]
OK，大概了解了，1500 w 数据，20 个进程并行插入，插入完毕后用第一条向量进行搜索，我们尝试本地复现一下。
另外，再问一嘴，插入完毕后有做 flush load 操作吗？

**Comment by wuweicheng39** [comment]
我是用单位实体图片，做的图片搜索，并不是随机生成的向量。模型是imagenet上面的vgg16之类的。展示效果时候，top50结果。测试是将近100张图片，发现四张图片有类似情况。 数据是到1300w时候，做的IMAGE_INDEX = {"index_type": "IVF_FLAT", "params": {"nlist": 1024}, "metric_type": "L2"}。后续应该是边插入，边索引。搜索端，搭建了django，肯定是先load collection，然后才能search。 flush操作没有运行过。

**Comment by wuweicheng39** [comment]
@DragonDriver

**Comment by DragonDriver** [comment]
> 我是用单位实体图片，做的图片搜索，并不是随机生成的向量。模型是imagenet上面的vgg16之类的。展示效果时候，top50结果。测试是将近100张图片，发现四张图片有类似情况。 数据是到1300w时候，做的IMAGE_INDEX = {"index_type": "IVF_FLAT", "params": {"nlist": 1024}, "metric_type": "L2"}。后续应该是边插入，边索引。搜索端，搭建了django，肯定是先load collection，然后才能search。 flush操作没有运行过。

了解了，我尝试复现一下

**Comment by wuweicheng39** [comment]
- Milvus version: milvus2.0-rc8
- Deployment mode(standalone or cluster):milvus-standalone----milvusdb/milvus:v2.0.0-rc8-20211104-d1f4106
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus=2.0.0rc8
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 
- GPU: 
- Others:
@DragonDriver @yanliang567

**Comment by wuweicheng39** [comment]
Milvus version: milvus2.0-rc8
Deployment mode(standalone or cluster):milvus-standalone----image:  milvusdb/milvus:v2.0.0-rc8-20211104-d1f4106
SDK version(e.g. pymilvus v2.0.0rc2):pymilvus=2.0.0rc8
OS(Ubuntu or CentOS): centos
CPU/Memory:  CPU/252G
GPU:
Others:

期间是不是会手动调用 get_index_build_progress(clct_name, index_field)，查看创建索引情况。

@DragonDriver @yanliang567

**Comment by wuweicheng39** [comment]
Milvus version: milvus2.0-rc8
Deployment mode(standalone or cluster):milvus-standalone----image: milvusdb/milvus:v2.0.0-rc8-20211104-d1f4106
SDK version(e.g. pymilvus v2.0.0rc2):pymilvus=2.0.0rc8
OS(Ubuntu or CentOS): centos
CPU/Memory: CPU/252G
GPU:
Others:

期间会 时不时会手动调用 get_index_build_progress(clct_name, index_field)，查看创建索引情况，我理解这个是只读操作，应该不影响写入操作。

@DragonDriver @yanliang567

**Comment by DragonDriver** [comment]
我本地在用 sift 数据集尝试复现，你说的 get_index_build_progress 确实是存在的，create index 请求发送之后，pymilvus 会不断调用这个接口判断索引是否完成。

**Comment by DragonDriver** [comment]
对了，能不能麻烦你将你上面的操作过程简单弄个脚本出来 @wuweicheng39

**Comment by wuweicheng39** [comment]
请求大神快速解决啊。 我已经把之前的1.0的milvus给卸了，就是因为2.0可以加入其他信息，不再需要用一个mysql做个pk映射。少运维一个mysql。

**Comment by DragonDriver** [comment]
你要不先加一下我们的用户群，看看是不是有人遇到过同样的问题，沟通起来也方便一些， @wuweicheng39

**Comment by wuweicheng39** [comment]
如何加入贵单位的用户群？？

**Comment by wuweicheng39** [comment]
@DragonDriver

**Comment by JackLCL** [comment]
![middle_img_v2_e8cf6ad1-9b49-421f-920d-25a7aa01a67g](https://user-images.githubusercontent.com/53512883/142586858-25c9a5e7-6e57-4bdc-8c96-6c6910c2f0f5.jpg)

@wuweicheng39

**Comment by wuweicheng39** [comment]
已经加入，谢谢。

**Comment by yanliang567** [comment]
@DragonDriver  I think we need to know why the distance is 0 while the 2 vectors are different

**Comment by wuweicheng39** [comment]
两个pk对应的vector，互换了。 @yanliang567

**Comment by xiaofan-luan** [comment]
@wuweicheng39 can you share the code to concurrent insert if possible?

**Comment by wuweicheng39** [comment]
等待2.0ga，我再重新入库1500w数据试试。

**Comment by ss892714028** [comment]
Have you made sure that all of the primary IDs across all clients are unique?
For now, Milvus does not do any deduplication to any fields, which means that it is possible that one primary key is associated with more than one vector. With a query, when there is more than one vector associated with a primary key, Milvus will randomly return one vector. This might be the reason that the returned {primary key ID and vector} mapping is inconsistent with some of your input.

**Comment by progzgq** [comment]
@wuweicheng39 老哥 这个问题最后解决了吗？我好像碰到一样的问题

**Comment by wj-0116** [comment]
遇到一样的问题，同问

**Comment by wj-0116** [comment]
> @wuweicheng39 can you share the code to concurrent insert if possible?

遇到同样的问题。

**Comment by xiaofan-luan** [comment]
please wait for milvus 2.1 and retry
