### ISSUE TITLE
how to add my own image dataset  to the pic_search_demo?

### ISSUE THREAD

**Issue by flydragon2018** [milvus-io/milvus#1213]
**What is your question?**
I manage to set up dockers of milvus+ pic_search_demo(client+server).
however since the dataset is too big to finish download in short time,
I want to know how to add my own small image dataset   for  demo?
original images, or I need convert images to vectors first?

any reply  in detail is appreciated.

**Comment by JackLCL** [comment]
When you start pic_search_demo server docker, you can specify your image dataset path and map it inside docker. For detailed operation steps, please refer to the "Run pic_search_demo docker" content in “https://github.com/milvus-io/bootcamp/blob/master/EN_solutions/pic_search/README.md” .

**Comment by JackLCL** [comment]
When you start pic_search_demo server docker, you can specify your image dataset path and map it inside docker. For detailed operation steps, please refer to the "Run pic_search_demo docker" content in “ https://github.com/milvus-io/bootcamp/blob/master/EN_solutions/pic_search/README.md ” .

**Comment by flydragon2018** [comment]
give a concrete  example.  instead of abstract template.

**Comment by JackLCL** [comment]
If you put your pictures in "/mnt/workspace/JPEGImages".  When you start pic_search_demo server docker, you can use this command: 
docker run -d --name zilliz_search_images_demo \
-v /mnt/workspace/JPEGImages:/tmp/pic1 \
-p 35000:5000 \
-e "DATA_PATH=/tmp/images-data" \
-e "MILVUS_HOST=192.168.1.123" \
chenglong555/pic_search_demo:0.5.0
