### ISSUE TITLE
[Enhancement]: Upgrade faiss to 1.7.2

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#12152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

1. Upgrading to 1.7.2
2. Backport patch to the new version.
3. Support a build option for OSX

### Why is this needed?

1. Support Milvus running with faiss lib on the OSX platform.
2. Get Some features of faiss after upgrading(need clarify)

**Comment by xiaofan-luan** [comment]
@jaime0815 Hey jaime, that's a nice proposal, you may want to have a MEP if you gonna to do this~

**Comment by yhmo** [comment]
Please note that currently milvus is using a customize faiss base on v1.6.3. We did pretty much improvement on this customize version.
The faiss v1.7.1 change a lot from v1.6.x, many directories are changed, source files moved, Makefile changed to CMake. It is difficult to integrate the improvement into v1.7.1.
The upper level source code is compiled based on the improvement, so it will failed to compile if you directly switch to v1.7.1.

**Comment by XuanYang-cn** [comment]
If we need to upgrade to faiss 1.7.1, we'll have to cherry-pick every patch we've ever made to our customized faiss into the newest one, which may take a very long time.

**Comment by WinterGYC** [comment]
If it helps, as per out latest test, Faiss 1.7.1 can build and run successfully on the new MacBook Pro (with Apple's M1 chip).

![Lark20211222-155735](https://user-images.githubusercontent.com/10147667/147056705-339d5822-e5a5-48d6-9d77-e5d6e1588569.png)
![Lark20211222-155740](https://user-images.githubusercontent.com/10147667/147056711-d3d8693e-bce1-4f2f-8126-60a327cf5711.png)

**Comment by cydrain** [comment]
> /assign @cydrain Hi cydrain, do we have any plan about the upgrade?

Just for update, I have upgraded faiss from 1.6.3 to 1.7.0 in my local branch on repo "knowhere".

My schedule is like following, [x] means finished
- [x] Familiar with FAISS 1.7.0 compile process and unittest 
- [x] Verify Weizhi's branch which has upgraded FAISS to 1.7.0, let all FAISS unittest pass
- [x] Port all code change under faiss between milvus 1.1 and milvus 2.0 to Weizhi's branch, let all FAISS unittest pass
- [ ] Replace knowhere/thirdparty/faiss with faiss from Weizhi's branch, let all knowhere unittest pass
- [ ] Upgrade knowhere/thirdparty/faiss to 1.7.2
- [ ] Support knowhere build on Mac M1
