### ISSUE TITLE
[Bug]: GC period could not be configured

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#12159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: latest
- Deployment mode(standalone or cluster): both
- SDK version(e.g. pymilvus v2.0.0rc2): latest
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Data is clean by every  24 hours

### Expected Behavior

Data clean time could be configured

**Comment by congqixia** [comment]
GC is configurable after this PR
https://github.com/milvus-io/milvus/pull/12061
Please verify. @binbinlv 
/unassign
/assign @binbinlv

**Comment by binbinlv** [comment]
@congqixia  Ok, testing, thanks.

**Comment by binbinlv** [comment]
Verified and fixed.
