### ISSUE TITLE
[Bug]: Hanging when executing collection.search function 

### ISSUE THREAD

**Issue by lyfggg** [milvus-io/milvus#12169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.0.0rc8
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):v2.0.0rc8
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 8*16G
- GPU: none
- Others: none
```

### Current Behavior

Hanging when executing collection.search function 

### Anything else?

There are 426480 vectors in the collection, each vector is 13560 dimensions.

test.py

connections.connect(host='xxxxxx', port='19530')
print(connections.list_connections())

collection = Collection("npyData")
print(collection.is_empty)
print(collection.num_entities)

collection.load()
print("start serach")
topK = 1
vector = [[random.random() for _ in range(15360)]]
search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
field = ["id", "utm_x", "utm_y", "z", "yall", "roll", "pitch", "s2code"]
res = collection.search(vector, "float_vector", search_params, topK, "id > 0", output_fields=field)
print(res)

**Comment by lyfggg** [comment]
lo
[Uploading standalone.log…]()
gs

**Comment by lyfggg** [comment]
[standalone.zip](https://github.com/milvus-io/milvus/files/7579022/standalone.zip)

**Comment by MathiasExorde** [comment]
Hi, Same issue here. Kind of related to #9689. Search is hanging even for hours. I can't search anything again until I reinstall Milvus and build a new collection. Can we mark this as urgent?

**Comment by lyfggg** [comment]
> Hi, Same issue here. Kind of related to #9689. Search is hanging even for hours. I can't search anything again until I reinstall Milvus and build a new collection. Can we mark this as urgent?

Yes, but even if I restart Milvus, it doesn’t work. Every time I insert data, the search function will hang.

**Comment by DragonDriver** [comment]
Maybe `flush` operation caused this issue. We print some very big information when you call `flush`.

**Comment by lyfggg** [comment]
> Maybe `flush` operation caused this issue. We print some very big information when you call `flush`.

I'd call `flush` many times when inserting data, because before that, I always made errors when inserting data, so I call `flush` every 5000 pieces of data.
So search hanging caused by frequent `flush` calls? How many pieces of data do you suggest I call `flush`? Or not calling flush when inserting?

**Comment by DragonDriver** [comment]
> > Maybe `flush` operation caused this issue. We print some very big information when you call `flush`.
> 
> I'd call `flush` many times when inserting data, because before that, I always made errors when inserting data, so I call `flush` every 5000 pieces of data. So search hanging caused by frequent `flush` calls? How many pieces of data do you suggest I call `flush`? Or not calling flush when inserting?

Acutually, you can call flush after all the inserting was done.
By the way, can you retry the operations with the newest code?

**Comment by lyfggg** [comment]
> Acutually, you can call flush after all the inserting was done. By the way, can you retry the operations with the newest code?

I roll back milvus to the rc5 version yesterday and `search()` under the same scenario and data is fine.
What do you mean by using the newest code? I use the latest version of rc8

**Comment by DragonDriver** [comment]
> > Acutually, you can call flush after all the inserting was done. By the way, can you retry the operations with the newest code?
> 
> I roll back milvus to the rc5 version yesterday and `search()` under the same scenario and data is fine. What do you mean by using the newest code? I use the latest version of rc8

I fixed some problems of `flush` yesterday.

**Comment by lyfggg** [comment]
> > > Acutually, you can call flush after all the inserting was done. By the way, can you retry the operations with the newest code?

I tried to `flush` after inserting data all, and this  time it just hangs on `load`. . . 
[standalone_11_25.zip](https://github.com/milvus-io/milvus/files/7599799/standalone_11_25.zip)

**Comment by DragonDriver** [comment]
> > > > Acutually, you can call flush after all the inserting was done. By the way, can you retry the operations with the newest code?
> 
> I tried to `flush` after inserting data all, and this time it just hangs on `load`. . . [standalone_11_25.zip](https://github.com/milvus-io/milvus/files/7599799/standalone_11_25.zip)

There are no enough memory to do `load` operation. How many rows in your collection?

**Comment by DragonDriver** [comment]
[2021/11/25 02:38:40.070 +00:00] [WARN] [impl.go:323] ["load segment failed, OOM if load, collectionID =  429325681680973825 ,  usedMem =  14605635584 ,  segmentTotalSize =  2062658954 ,  currentSegmentSize =  411325954 ,  totalMem =  17179869184 ,  thresholdFactor =  0.9\n"]

**Comment by lyfggg** [comment]
> [2021/11/25 02:38:40.070 +00:00] [WARN] [impl.go:323] ["load segment failed, OOM if load, collectionID = 429325681680973825 , usedMem = 14605635584 , segmentTotalSize = 2062658954 , currentSegmentSize = 411325954 , totalMem = 17179869184 , thresholdFactor = 0.9\n"]

There are 426480 vectors in the collection, each vector is 13560 dimensions.

**Comment by lyfggg** [comment]
> > [2021/11/25 02:38:40.070 +00:00] [WARN] [impl.go:323] ["load segment failed, OOM if load, collectionID = 429325681680973825 , usedMem = 14605635584 , segmentTotalSize = 2062658954 , currentSegmentSize = 411325954 , totalMem = 17179869184 , thresholdFactor = 0.9\n"]
> 
> There are 426480 vectors in the collection, each vector is 13560 dimensions.

we have 16G memory for milvus, if memory is not enough,  what if the data becomes larger and the index has hundreds of GB, how can we ensure that the memory does not exceed?

**Comment by DragonDriver** [comment]
We provide a [sizing tool](https://milvus.io/tools/sizing) for uses to estimate the size of a collection.

**Comment by DragonDriver** [comment]
And very thanks for providing these information. We will improve the `load` operation as soon as possible.

**Comment by lyfggg** [comment]
> And very thanks for providing these information. We will improve the `load` operation as soon as possible.

Thank you very much for your help too. I'll try to add memory to 32GB and do `load` and `search` again.

**Comment by DragonDriver** [comment]
Feel free to let us know and reopen this issue if you still have any problems.

**Comment by nazzour** [comment]
I am facing the same problem with both docker-compose and k8s. After restarting k8s pods or restarting docker-compose the search does not work anymore. the insertion is OK. Any solution please ??

**Comment by DacDinh147** [comment]
@DragonDriver  I am facing the same issue here. The search hang forever after restarting the docker or spin it up again. After deleting the collection,inserting it again, searching works. But loading the existed collection, perform search, it hanging forever. No any catching error when debugging.
The toy dataset is small, no constraint in memory, here is the information about collection
```
[
  {
    "name": "milvus_img_search",
    "description": "Demo collection search for VOCdevkit dataset",
    "number of entities": 4781
  }
]
```
Would you please provide any solution, I really like the way Milvus organizes data for searching, please help!

**Comment by yanliang567** [comment]
@DacDinh147 would you like to try the latest build in master? please file a new issue with the milvus logs attached if it still reproduced to you

**Comment by DacDinh147** [comment]
@yanliang567 , thank for you rep, I found out to avoid the problem, I have to realease the collection from memory every time I start or restart Milvus server. What should I do in this case of server crash or restart? If I put the collection.release after collection.search, this would slow down everything, releasing from memory, loading into memory,  performing search then releasing, then loading,...., for every single POST request to the server. Why Milvus does not support implicitly releasing collection from memory when server restarting or recovering from crashing. Would you  please tell me how to do it in an optimal way.

**Comment by yanliang567** [comment]
> should

Actually, this is an issue in rc8, and we believe it was fixed it in master. So I suggest retry on master latest. Please feel free to LMK if it does not work for you

**Comment by francohandel** [comment]
@yanliang567 i use milvus v2.0.2 in docker and i still do encounter this issue where by anytime i restart docker or rebuild by docker image my search function returns an empty result. what might be the possible cause?

**Comment by yanliang567** [comment]
@francohandel please file a new issue and provide the info such as reproduce steps and logs for investigation. thanks.

**Comment by martinenkoEduard** [comment]
I even can't release the collection.
It just hangs.
