### ISSUE TITLE
[Enhancement]: Support to get accurate number of entities

### ISSUE THREAD

**Issue by wxyucs** [milvus-io/milvus#12164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

I would like to enhance the number of entities function to get an accurate result.

### Why is this needed?

Currently, the number of entities is calculated by inserting request statistics. After deleting the data, the result is inaccurate.

**Comment by xiaofan-luan** [comment]
To support accurate number of entities, we need to add another parameter similar to query, or just support aggregation?

**Comment by congqixia** [comment]
I don't think this feature is implemented, reopening it.
