### ISSUE TITLE
[Enhancement]: Jaeger servicename should not contain id parameter

### ISSUE THREAD

**Issue by zwd1208** [milvus-io/milvus#12176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

When node component init tracing, it use id as part of the servicename. so there will have many different servicename in jaeger system.

`// init initializes IndexNode's grpc service.
func (s *Server) init() error {
	var err error
	Params.Init()

	indexnode.Params.InitOnce()
	indexnode.Params.Port = Params.Port
	indexnode.Params.IP = Params.IP
	indexnode.Params.Address = Params.Address

	closer := trace.InitTracing(fmt.Sprintf("IndexNode-%d", indexnode.Params.NodeID))
	s.closer = closer

	Params.Address = Params.IP + ":" + strconv.FormatInt(int64(Params.Port), 10)
`

### Why is this needed?

I think all components should use their own names as servicename, we can add tags to distinguish between different instances of the same component.

**Comment by yanliang567** [comment]
/assign @xiaofan-luan 
@xiaofan-luan  i think this should be tracked

**Comment by yanliang567** [comment]
keep it open for tracking

**Comment by czs007** [comment]
In my list of scheduled tasks, opentracing will gradually be used to monitor the system critical path.
