### ISSUE TITLE
The research of ANNS

### ISSUE THREAD

**Issue by chasingegg** [milvus-io/milvus#1218]
Hello guys, it is a wonderful job to integrate those algorithms to your systems. Is there anyone working on the research to further improve the performance of graph index like hnsw and nsg, maybe we could have a discussion, or directly express your idea below.

**Comment by JinHai-CN** [comment]
Welcome to discuss the ANNS algorithm with us. Currently, we are focusing on integrating more popular algorithms into Milvus. On specific graph index such as nsg, we already do slightly improvement on it. For hnsw part, we are investigating some improvements on it, such as granne(https://github.com/granne/granne)/n2(https://github.com/kakao/n2).

**Comment by chasingegg** [comment]
@JinHai-CN what's the slight difference between n2 and the original hnsw algorithm?
