### ISSUE TITLE
[Bug]: Files in minio are not cleaned when enabling GC and setting clean time period

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#12195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: latest
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):  2.0.0rc9.dev14
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Files in minio are not cleaned when enabling GC:

### Expected Behavior

Files in minio are cleaned after GC time period:

### Steps To Reproduce

```markdown
1. Enable GC and set clean time
in milvus.yaml:
enableGarbageCollection: true
  gc:
    interval: 60 # gc interval in seconds
    missingTolerance: 60 # file meta missing tolerance duration in seconds, 1 day
    dropTolerance: 60 # file belongs to dropped entity tolerance duration in seconds, 1 day
2. creating collection, and insert data
3. drop collection
4. Check the files in minio
```

**Comment by binbinlv** [comment]
Logs:
[12195.tar.zip](https://github.com/milvus-io/milvus/files/7585469/12195.tar.zip)

**Comment by congqixia** [comment]
> Logs: [12195.tar.zip](https://github.com/milvus-io/milvus/files/7585469/12195.tar.zip)

@binbinlv according to the log, the build version was `Version:   d567b21`, which a version from Oct 11
```
commit d567b21fd4f5c0df00e2e68f1cee35af4b41f18e (tag: v2.0.0-rc7, origin/2.0.0-rc7)
Author: bigsheeper <yihao.dai@zilliz.com>
Date:   Mon Oct 11 15:40:38 2021
```

**Comment by binbinlv** [comment]
OK, thanks.

There is a problem for the script of starting the milvus using kind, so will start a new one to test. Close this.
