### ISSUE TITLE
[Bug]: Just one pod is available when create mutiple proxy pods

### ISSUE THREAD

**Issue by JamCrash** [milvus-io/milvus#12207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: rc8
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

[2021/11/23 04:07:13.421 +00:00] [DEBUG] [task_scheduler.go:678] ["Proxy collectResultLoop Got a SearchResultMsg, but we should ignore"] [ReqID=429296405931220210]
[2021/11/23 04:07:13.431 +00:00] [DEBUG] [task_scheduler.go:678] ["Proxy collectResultLoop Got a SearchResultMsg, but we should ignore"] [ReqID=429296405931220210]
[2021/11/23 04:07:13.455 +00:00] [DEBUG] [task_scheduler.go:678] ["Proxy collectResultLoop Got a SearchResultMsg, but we should ignore"] [ReqID=429296405931220211]
[2021/11/23 04:07:13.478 +00:00] [DEBUG] [task_scheduler.go:678] ["Proxy collectResultLoop Got a SearchResultMsg, but we should ignore"] [ReqID=429296405931220211]
[2021/11/23 04:07:13.508 +00:00] [DEBUG] [task_scheduler.go:678] ["Proxy collectResultLoop Got a SearchResultMsg, but we should ignore"] [ReqID=429296405931220213]

### Expected Behavior

 I create multiple proxy pods with a clusterIP service. After I call async search concurrently, just one proxy is available an the other show logs above.
 ps: even if I run mutiple search process on linux, only one proxy is active, the other is like above condition

**Comment by DragonDriver** [comment]
related: #10527

**Comment by DragonDriver** [comment]
See also https://github.com/milvus-io/milvus/issues/10527#issuecomment-955907479

**Comment by JamCrash** [comment]
> See also [#10527 (comment)](https://github.com/milvus-io/milvus/issues/10527#issuecomment-955907479)

Thank you, I have seen that. but I have already run multiple process, (not multiple connections in one process), and I also have this problem

**Comment by JamCrash** [comment]
maybe it is relatived to k8s service load balancing? @DragonDriver

**Comment by DragonDriver** [comment]
> maybe it is relatived to k8s service load balancing? @DragonDriver

I'm afraid python gRPC will also reuse the TCP connection though you run multiple process.

**Comment by JamCrash** [comment]
Is this problem will be fixed in GA version? @DragonDriver

**Comment by DragonDriver** [comment]
> Is this problem will be fixed in GA version? @DragonDriver

Sorry, but no. We are also waiting for gRPC to fix this problem. You can try our [go-sdk](https://github.com/milvus-io/milvus-sdk-go) for milvus.

**Comment by DragonDriver** [comment]
In our roadmap, we'll plan to support more load balancing options in later version.

**Comment by xiaofan-luan** [comment]
> > maybe it is relatived to k8s service load balancing? @DragonDriver
> 
> I'm afraid python gRPC will also reuse the TCP connection though you run multiple process.

Even for multi process they share the same connection?

**Comment by DragonDriver** [comment]
> > See also [#10527 (comment)](https://github.com/milvus-io/milvus/issues/10527#issuecomment-955907479)
> 
> Thank you, I have seen that. but I have already run multiple process, (not multiple connections in one process), and I also have this problem

I think maybe you can retry this.

I made a small experiment:
- 1, create a k8s service which connects to three simple grpc server pod;
- 2, run multiple grpc clients which connect to the k8s service;
- 3, server use their own ip and port as the response;

And then we got different response. So maybe it's occasional that your all connection forward to same pod.

**Comment by DragonDriver** [comment]
![image](https://user-images.githubusercontent.com/31589260/143023149-f17e928f-4ee7-4f09-84a1-1c3a4b8a9534.png)

**Comment by yanliang567** [comment]
@zwd1208 I think you have some experiments here

**Comment by zwd1208** [comment]
> @zwd1208 I think you have some experiments here
I have an envoy deployment experiment, it can perform load balancing for GRCP whether there is only one connection or not.
you can do:
1.  create a headless service for proxy
2.  create an envoy deployemnt to loadbalance proxy headless service

The following configuration example:
`
kind: Service
apiVersion: v1
metadata:
  name: milvus-proxy-headless
spec:
  ports:
    - name: proxy
      protocol: TCP
      port: 19530
      targetPort: proxy
  selector:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/instance: grpc-proxy
    app.kubernetes.io/name: milvus
  clusterIP: None
  type: ClusterIP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: envoy-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: envoy-proxy
      app.kubernetes.io/name: envoy
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: envoy-proxy
        app.kubernetes.io/name: envoy
    spec:
      volumes:
        - name: envoy-config
          configMap:
            name: envoy-config
            defaultMode: 420
      containers:
        - name: envoy
          image: envoyproxy/envoy:v1.20.0
          volumeMounts:
            - name: envoy-config
              readOnly: true
              mountPath: /etc/envoy/envoy.yaml
              subPath: envoy.yaml
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: envoy-config
data:
  envoy.yaml: |
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 19530
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              codec_type: auto
              stat_prefix: ingress_http
              access_log:
              - name: envoy.access_loggers.stdout
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
              route_config:
                name: local_route
                virtual_hosts:
                - name: backend
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/" 
                      grpc: {}
                    route:
                      cluster: backend_grpc_service
              http_filters:
              - name: envoy.filters.http.router
                typed_config: {}
      clusters:
      - name: backend_grpc_service
        connect_timeout: 0.250s
        type: strict_dns
        lb_policy: round_robin
        http2_protocol_options: {}
        load_assignment:
          cluster_name: backend_grpc_service
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: milvus-proxy-headless
                    port_value: 19530
`

**Comment by JamCrash** [comment]
Thank you, it works now! @zwd1208
