### ISSUE TITLE
[Bug]: [Memory]Release and load collection get exception no queryNode to allocate

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#12218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20211123-73f18c5
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.0.0rc9.dev11
- OS(Ubuntu or CentOS): 
- CPU/Memory: limit querynode memory 2Gi
- GPU: 
- Others:
```

### Current Behavior

1. deploy milvus cluster master-20211123-73f18c5 and limit querynode memory 2Gi
2. load collection (dim=512, num_entities=399360 about 780Mi)
3. search successfully
4. release collection (No exception, but the memory usage of querynode did not drop)
5. re-load failed
```
[2021-11-23 04:13:43,651 - INFO - ci_test]: ################################################################################ (conftest.py:162)
[2021-11-23 04:13:43,651 - INFO - ci_test]: [initialize_milvus] Log cleaned up, start testing... (conftest.py:163)
[2021-11-23 04:13:44,673 - DEBUG - ci_test]: {
  auto_id: False
  description: 
  fields: [{
    name: int64
    description: 
    type: 5
    is_primary: True
    auto_id: False
  }, {
    name: float
    description: 
    type: 10
  }, {
    name: float_vector
    description: 
    type: 101
    params: {'dim': 512}
  }]
}
 (test_chaos_memory_stress.py:63)
[2021-11-23 04:13:44,673 - DEBUG - ci_test]: 2 (test_chaos_memory_stress.py:64)
[2021-11-23 04:13:48,047 - ERROR - ci_test]: Traceback (most recent call last):
  File "/root/milvus/tests/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/root/milvus/tests/python_client/utils/api_request.py", line 45, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 449, in load
    conn.load_collection(self._name, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 58, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 42, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 322, in load_collection
    return handler.load_collection("", collection_name=collection_name, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 820, in load_collection
    raise BaseException(response.error_code, response.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=call query coordinator LoadCollection: rpc error: code = Unknown desc = , no queryNode to allocate)>
 (api_request.py:26)
[2021-11-23 04:13:48,047 - ERROR - ci_test]: (api_response) : <BaseException: (code=1, message=call query coordinator LoadCollection: rpc error: code = Unknown desc = , no queryNode to allocate)> (api_request.py:27)
```
**Server log:**
[milvus_logs.tar.gz](https://github.com/milvus-io/milvus/files/7586290/milvus_logs.tar.gz)

**Memory usage:**
![image](https://user-images.githubusercontent.com/27288593/142984044-c5227d32-002a-4975-8e8b-3b40fca0ee25.png)

**Comment by bigsheeper** [comment]
I'm working on it

**Comment by xige-16** [comment]
I'll work on it

**Comment by xige-16** [comment]
The possible reason is that after release, the memory requested by go is not returned to the operating system, which causes the memory Used returned by querynode when getMetric is larger

**Comment by godchen0212** [comment]
It seems the memory has not been released completely in querynode.

**Comment by godchen0212** [comment]
I test locally with follow steps:
1. create collection
2. insert 400k data with dim 128.
3. load collection
4. release collection
5. drop collection
I found through the htop memory tool that even after release and drop, the memory usage of queynode is still very high. During this period, no other operations were performed. After one minute, the memory usage displayed in htop began to drop to the initial level.

Script codes:
```python
import time
import random

from pymilvus import CollectionSchema, FieldSchema
from pymilvus import Collection
from pymilvus import connections
from pymilvus import DataType
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
dim = 128
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
schema = CollectionSchema(fields=[int64_field, float_vector])
connections.connect()
import numpy as np
collection = Collection("test_search_collection_"+str(random.randint(0, 100000000000)), schema=schema)
# collection.load()
nb = 400000 
nq = 1
limit = 2
import random
default_search_params = {"metric_type": "L2", "params": {"nprobe": 1}}
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
res = collection.insert([[i for i in range(nb)], vectors])

print("start load")
collection.load()
print("load finished")
collection.release()

print("release finished")
collection.drop()
```

**Comment by godchen0212** [comment]
This issue exposed many problems.
1. The golang runtime returns the memory to os after about two minutes. I test it on my local machine and go version is 1.16. I test insert 500K data with dim 128 in to milvus, load and release for 100 times. The memory usage increase from 58M to 1.5G and fell back to 700M after two minutes. So the problem mentioned in this issue is unsolvable. When the memory is not very large, we cannot load the data immediately after the release but need to wait for golang to return the memory before loading. Otherwise, re-load will inevitably fail due to insufficient memory
2. The same experiment as in 1 is on @bigsheeper computer, and the go version is 1.15. The memory never drops after it rises to 1.5G. It is a golang bug in @czs007 previous survey. We need to upgrade the version of go from 1.15 to 1.16. https://github.com/milvus-io/milvus/blob/a03bbbfddc7e81a5318519f16bdb4a422b2def8e/go.mod#L3
3. At the end of the experiment in 1 there are more than 700 M in the memory, there should be a memory leak. 
    After checking with pprof, I found that golang does not occupy much memory, so the memory leak may be the c++ layer. 
    I tried to annotate the loadFieldData function of segcore. That is, do not load data into segcore. The memory still has more than 700M in the memory, indicating that the memory leak did not occur in the segcore. 
    After that, I tried to annotate the deserialization function, and the memory usage rose to more than 200M and finally returned to more than 100M (including timetick, which occupied tens of megabytes of memory). It can be judged from this that there may be a memory leak in the parquet inverse sequence.

I will open two more issues to solve 2 and 3 issues. Problem 1 mentioned in this issue can be closed now.
/cc @xiaofan-luan 
/cc @czs007 

Experiment codes:
```python
import random

from pymilvus import (
    connections, list_collections,
    FieldSchema, CollectionSchema, DataType,
    Collection,
    utility
)


def hello_milvus():
    # create connection
    connections.connect(host="127.0.0.1",port="19530")

    print(f"\nList collections...")
    print(list_collections())

    # create collection
    dim = 128
    default_fields = [
        FieldSchema(name="count", dtype=DataType.INT64, is_primary=True),
        FieldSchema(name="random_value", dtype=DataType.DOUBLE),
        FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
    ]
    default_schema = CollectionSchema(fields=default_fields, description="test collection")

    print(f"\nCreate collection...")
    collection = Collection(name="hello_milvus", schema=default_schema)

    print(f"\nList collections...")
    print(list_collections())

    #  insert data
    nb = 500000
    vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
    collection.insert(
        [
            [i for i in range(nb)],
            [float(random.randrange(-20, -10)) for _ in range(nb)],
            vectors
        ]
    )

    print(f"\nGet collection entities...")
    print(collection.num_entities)

    import time
    try_time = 100
    while(try_time>0):
        print(f"\nload collection...", try_time)
        collection.load()

        print(f"\nrelease collection...")
        collection.release()
        try_time-=1

hello_milvus()

```

**Comment by xiaofan-luan** [comment]
@godchen0212 very impressive analysis, for scenario 1 we will just accept the behavior.  it should be go back to normal once gc happens so I guess that is kind of reasonable.

Let's focus on the deserialization leakage, guess that may solve a lot of problems

**Comment by godchen0212** [comment]
Case 3 related to issue #12585

**Comment by bigsheeper** [comment]
As for the scenario 2 mentioned above，maybe we don't need to upgrade the version. Here's the release note of go version 1.16: 

> _On Linux, the runtime now defaults to releasing memory to the operating system promptly (using MADV_DONTNEED), rather than lazily when the operating system is under memory pressure (using MADV_FREE). This means process-level memory statistics like RSS will more accurately reflect the amount of physical memory being used by Go processes. Systems that are currently using GODEBUG=madvdontneed=1 to improve memory monitoring behavior no longer need to set this environment variable._

So we can also just set the `GODEBUG=madvdontneed=1` env and no need to upgrade go version. I'v tested it on my computer and it worked. We can just add a config param or use `os.Setenv`, and users would not limited to golang versions.

**Comment by yanliang567** [comment]
> @godchen0212 very impressive analysis, for scenario 1 we will just accept the behavior. it should be go back to normal once gc happens so I guess that is kind of reasonable.
> 
> Let's focus on the deserialization leakage, guess that may solve a lot of problems

@xiaofan-luan 2 questions for the 1st one:
1. how long users need to wait for the next GC?
2. does the memory 100% released after a GC?

@bigsheeper any pr to your suggestion above?

/assign @bigsheeper 
/assign @xiaofan-luan 
/unassign @ThreadDao

**Comment by xiaofan-luan** [comment]
> #12585

We've seen memory leakage on desrialize part, though godchen is working on that

**Comment by bigsheeper** [comment]
#14305 merged,  could you help to retest this issue? @ThreadDao

**Comment by yanliang567** [comment]
verified that memory of query node does keep smooth if load and release in loop for 24+hours
