### ISSUE TITLE
[Bug]: Corrupted double linked list 

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#12213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

the ut failed because of corrupted double linked list 
https://github.com/milvus-io/milvus/runs/4294810646?check_suite_focus=true

![image](https://user-images.githubusercontent.com/83447078/142981540-5434a7f4-22f5-491f-b545-09bf29ea7982.png)

**Comment by congqixia** [comment]
See also: https://github.com/milvus-io/milvus/issues/9997
This error occurred long time ago.

**Comment by xiaofan-luan** [comment]
duplicate with #9997
close for now
