### ISSUE TITLE
[Bug]: Case sensitive when searching with bool expression "bool in [True] or [true]"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#12210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: latest
- Deployment mode(standalone or cluster):both
- SDK version(e.g. pymilvus v2.0.0rc2): latest
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1 Good
res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "bool in [true]")

2 Bad
res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "bool in [True]")
Error: <BaseException: (code=1, message=failed to create query plan: unsupported leaf node)>

### Expected Behavior

For behavior consistency, "bool == True or true" is not case sensitive, so it is better to be same behavior for "bool in [True] or [true]"

**Comment by ThreadDao** [comment]
Image `master-20211123-dd0b36f`

query on bool support expr:

- id in [true / false]
- id == true/ false
- id == True / False

not support:

- id in [True / False]
- id == 0 / 1 / 2

**Comment by DingQK** [comment]
@xiaofan-luan @fishpenguin   Hi! I am new to the milvus community and I really want to contribute. Are there anything I can do to help solve this issue? Thank you so much!

**Comment by binbinlv** [comment]
This issue should be left as "open" until it is fixed.
