### ISSUE TITLE
[Bug]: Inserted data is not cleaned when creating collection with index (GC is enabled)

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#12223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: latest
- Deployment mode(standalone or cluster): both
- SDK version(e.g. pymilvus v2.0.0rc2): latest
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Insert files are not cleaned

### Expected Behavior

Insert files are cleaned after GC time

### Steps To Reproduce

1 Set the env:
Enable GC and set clean time
in milvus.yaml:
enableGarbageCollection: true
  gc:
    interval: 60 # gc interval in seconds
    missingTolerance: 60 # file meta missing tolerance duration in seconds, 1 day
    dropTolerance: 60 # file belongs to dropped entity tolerance duration in seconds, 1 day

2 create collection, insert, create index, drop
```python
from pymilvus import CollectionSchema, FieldSchema
from pymilvus import Collection
from pymilvus import connections
from pymilvus import DataType
from pymilvus import Partition
from pymilvus import utility

dim = 128
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
connections.connect()
import numpy as np
collection = Collection("test_search_collection_binbin_6", schema=schema)
dim = 128
nb = 3000
nq = 2
limit = 10
import random
default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
collection.num_entities

default_index = {"index_type": "IVF_PQ", "params":{"nlist": 128, "m": 16, "nbits": 8}, "metric_type": "L2"}

collection.create_index("float_vector", default_index)
collection.load()
collection.drop()
```

3 Check insert files in minio

**Comment by binbinlv** [comment]
Logs:
[12223.tar.zip](https://github.com/milvus-io/milvus/files/7586690/12223.tar.zip)

(1) collection with index
Not deleted collection name: test_search_collection_binbin_6
                     collection ID: 429301420037180737

(2) collection without index                  
Deleted collection name: test_search_collection_binbin
               collection ID: 429301664210485249

**Comment by congqixia** [comment]
> Logs: [12223.tar.zip](https://github.com/milvus-io/milvus/files/7586690/12223.tar.zip)
> 
> (1) collection with index Not deleted collection name: test_search_collection_binbin_6 collection ID: 429301420037180737
> 
> (2) collection without index Deleted collection name: test_search_collection_binbin collection ID: 429301664210485249

@binbinlv index file clean up is under development. @xiaocai2333

**Comment by binbinlv** [comment]
It works now, so closed.
