### ISSUE TITLE
[Bug]: Every time about 300000 vectors are inserted into miluvs 2.0, Milvus cannot be inserted and queried. The database must be deleted and Milvus must be reinstalled to connect and query.

### ISSUE THREAD

**Issue by icodersky** [milvus-io/milvus#12221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvus2.0 rc8
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.0.0rc8
- OS(Ubuntu or CentOS): centos8
- CPU/Memory: 18core/256GB
- GPU: 
- Others:
```

### Current Behavior

After inserting 500000 vectors for the first time, each node of Milvus reports the following errors, but automatically runs a new pod. At this time, it can connect to the database, but can't insert vectors and query vectors.

Error info:
`The node was low on resource: ephemeral-storage. Container datanode was using 159256Ki, which exceeds its request of 0. `

The database can only be removed and reinstalled for normal use.

Then re insert the vector into the Milvus database. After about 300000 vector data are inserted, the above error is reported, and then the vector and query vector can not be inserted.

**The log files are as follows:**
[my-release-etcd-0.log](https://github.com/milvus-io/milvus/files/7586352/my-release-etcd-0.log)
[my-release-etcd-1.log](https://github.com/milvus-io/milvus/files/7586354/my-release-etcd-1.log)
[my-release-etcd-2.log](https://github.com/milvus-io/milvus/files/7586355/my-release-etcd-2.log)
[my-release-milvus-datacoord-fff88945c-mzn9v.log](https://github.com/milvus-io/milvus/files/7586356/my-release-milvus-datacoord-fff88945c-mzn9v.log)
[my-release-milvus-datanode-646d96dc9d-9hnnb.log](https://github.com/milvus-io/milvus/files/7586357/my-release-milvus-datanode-646d96dc9d-9hnnb.log)
[my-release-milvus-indexcoord-547f86b654-v4q6l.log](https://github.com/milvus-io/milvus/files/7586358/my-release-milvus-indexcoord-547f86b654-v4q6l.log)
[my-release-milvus-proxy-79b84b899f-5tvxw.log](https://github.com/milvus-io/milvus/files/7586359/my-release-milvus-proxy-79b84b899f-5tvxw.log)
[my-release-milvus-querycoord-5f575788f-zxxjj.log](https://github.com/milvus-io/milvus/files/7586360/my-release-milvus-querycoord-5f575788f-zxxjj.log)
[my-release-milvus-rootcoord-74dccd697-p2ff7.log](https://github.com/milvus-io/milvus/files/7586361/my-release-milvus-rootcoord-74dccd697-p2ff7.log)
[my-release-minio-0.log](https://github.com/milvus-io/milvus/files/7586364/my-release-minio-0.log)
[my-release-pulsar-autorecovery-869bffb7b8-slf2f.log](https://github.com/milvus-io/milvus/files/7586365/my-release-pulsar-autorecovery-869bffb7b8-slf2f.log)
[my-release-pulsar-bastion-7c659df966-s8k58.log](https://github.com/milvus-io/milvus/files/7586369/my-release-pulsar-bastion-7c659df966-s8k58.log)
[my-release-pulsar-bookkeeper-0.log](https://github.com/milvus-io/milvus/files/7586370/my-release-pulsar-bookkeeper-0.log)
[my-release-pulsar-broker-6577959744-mrvk8.log](https://github.com/milvus-io/milvus/files/7586372/my-release-pulsar-broker-6577959744-mrvk8.log)

**node status:**
[kubectl_describe_node.log](https://github.com/milvus-io/milvus/files/7586419/kubectl_describe_node.log)

### Steps To Reproduce

```markdown
Milvus Installation instructions:
https://artifacthub.io/packages/helm/milvus/milvus

Milvus Installation method:
helm upgrade --install --set queryNode.replicas=9 --set indexNode.replicas=3 --set dataNode.replicas=3 --set proxy.replicas=3 my-release milvus/milvus

Insert vectors into database...
```

**Comment by xiaofan-luan** [comment]
looks like rootcoord can not be restart and fall into abnormal states forever

**Comment by zwd1208** [comment]
@icodersky This is usually due to Pod ephemeral-storage is not enough, kubelet evicted the pod. when you connect failed, you can check the disk space on the Node

**Comment by lyfggg** [comment]
[https://github.com/milvus-io/milvus/issues/12169](url) 大佬们可以帮忙看看这个是啥原因不

**Comment by icodersky** [comment]
> @icodersky这通常是由于 Pod 临时存储不够，kubelet 驱逐了 Pod。当你连接失败时，你可以检查节点上的磁盘空间



> @icodersky这通常是由于 Pod 临时存储不够，kubelet 驱逐了 Pod。当你连接失败时，你可以检查节点上的磁盘空间

节点的磁盘空间是足够的<img width="1078" alt="204" src="https://user-images.githubusercontent.com/86787724/142991983-ffa4c0d8-c14e-4642-a00a-cb8bc09912a1.png">



> @icodersky This is usually due to Pod ephemeral-storage is not enough, kubelet evicted the pod. when you connect failed, you can check the disk space on the Node

There is enough disk space.
![204](https://user-images.githubusercontent.com/86787724/142992431-11544423-b0f4-4fca-afbb-0abeece84aaf.jpg)
![207](https://user-images.githubusercontent.com/86787724/142992619-1e004f9f-65aa-4590-8b05-b6e7098e4f43.jpg)

**Comment by icodersky** [comment]
> looks like rootcoord can not be restart and fall into abnormal states forever

How to solve this problem?

**Comment by xiaofan-luan** [comment]
> 

not sure how you hit the situation yet but your rootcoord is in a middle state, may try to kill the rootcoord container

**Comment by yanliang567** [comment]
@zwd1208 could you please check the disk logs above?
