### ISSUE TITLE
[Bug]: querynode: Cannot create producer on topic with backlog quota exceeded

### ISSUE THREAD

**Issue by JamCrash** [milvus-io/milvus#12243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0 rc8
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

time="2021-11-24T03:05:20Z" level=info msg="[Reconnecting to broker in 1m3.495358951s]" producerID=4 producer_name=standalone-0-319 topic="persistent://public/default/test-searchResult-0"
time="2021-11-24T03:06:23Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" producerID=4 producer_name=standalone-0-319 topic="persistent://public/default/test-searchResult-0"

### Steps To Reproduce

```markdown
when I create multiple milvus-proxy pod, just one proxy pod is active and the cluster running fine, then I shutdown the active one, another proxy is active, but this time, the search request from pymilvus will hang.
I look at the querynode log, the search assignment is finished successfully, but when write it to pulsar, the error above occur.
```

### Anything else?

look at #12207

**Comment by DragonDriver** [comment]
Can you please provide the complete logs of milvus? @JamCrash

**Comment by JamCrash** [comment]
that's all the log in milvus querynode, it will repeat appear, before that it has filt search result done log

**Comment by JamCrash** [comment]
I want to ask that is there anyone actully deploy multiple milvus proxy pod?

**Comment by DragonDriver** [comment]
> I want to ask that is there anyone actully deploy multiple milvus proxy pod?

If you have multiple clients which need to access milvus, then deploying multiple proxy pods is reasonable.

**Comment by JamCrash** [comment]
> 

Yes, I have multiple client to access, but could you please try to deploy a multiple proxy pods cluster in your environment and see how is it work? In our company k8s env, only one proxy pod can use, when I do search on the other using nodeport, the client hangs ...

**Comment by DragonDriver** [comment]
> > 
> 
> Yes, I have multiple client to access, but could you please try to deploy a multiple proxy pods cluster in your environment and see how is it work? In our company k8s env, only one proxy pod can use, when I do search on the other using nodeport, the client hangs ...

I'll check this soon.

**Comment by DragonDriver** [comment]
![image](https://user-images.githubusercontent.com/31589260/143208758-c291efc4-805c-40c7-a31b-749b25b8d2ae.png)

**Comment by DragonDriver** [comment]
@JamCrash 
I made another small experiment:
- 1, `helm install my-release milvus/milvus --set proxy.replicas=2`;
- 2, using two clients to do search;
- 3, `kubectl logs my-release-milvus-proxy-6cbd7b5f55-rr8ht | grep Search | wc -l` to check if proxy received search requests;

Then both of the two proxy pods received search requests.

**Comment by LoveEachDay** [comment]
@JamCrash How do you install the milvus cluster? By helm chart or docker-compose?

**Comment by JamCrash** [comment]
I deploy milvus separately by k8s yaml

**Comment by DragonDriver** [comment]
@JamCrash can you just try using a simple grpc server in your company k8s env?

**Comment by LoveEachDay** [comment]
> 
Could you provide the install yaml manifests?

**Comment by JamCrash** [comment]
[](url
[test.tar.gz](https://github.com/milvus-io/milvus/files/7595214/test.tar.gz)
)

**Comment by JamCrash** [comment]
[test.tar.gz](https://github.com/milvus-io/milvus/files/7595222/test.tar.gz)
@LoveEachDay

**Comment by JamCrash** [comment]
With service-nodeport on milvus proxy, it runs and search fine this time after I restart cluster and clear all data the last cluster remains, but the proxy log appear like this
![企业微信截图_16377565136678](https://user-images.githubusercontent.com/39126346/143237588-8add8199-8c5e-40a8-8b89-633a39b79577.png)
:

**Comment by DragonDriver** [comment]
> With service-nodeport on milvus proxy, it runs and search fine this time after I restart cluster and clear all data the last cluster remains, but the proxy log appear like this ![企业微信截图_16377565136678](https://user-images.githubusercontent.com/39126346/143237588-8add8199-8c5e-40a8-8b89-633a39b79577.png) :

No idea about why this happend. See some similar issue in gRPC. By the way, how do you access the milvus?

**Comment by LoveEachDay** [comment]
According to the yaml manifests, you use pulsar standalone, which do have a backlog quota, which is 10GB by default.

**Comment by JamCrash** [comment]
With nodeport, it runs and search fine this time after I restart cluster and clear all data the last cluster remains, but th

> > With service-nodeport on milvus proxy, it runs and search fine this time after I restart cluster and clear all data the last cluster remains, but the proxy log appear like this ![企业微信截图_16377565136678](https://user-images.githubusercontent.com/39126346/143237588-8add8199-8c5e-40a8-8b89-633a39b79577.png) :
> 
> No idea about why this happend. See some similar issue in gRPC. By the way, how do you access the milvus?

By kubectl port-forward to proxy

**Comment by DragonDriver** [comment]
Hello, can above issue be reproduced these days? @JamCrash

**Comment by JamCrash** [comment]
I redeploy the cluster with distributed pulsar mod after I clear all the old data, which doesn't reproduce the problem above

**Comment by DragonDriver** [comment]
> I redeploy the cluster with distributed pulsar mod after I clear all the old data, which doesn't reproduce the problem above

OK, thanks for all your information. Closed this now. Feel free to reopen this if any similar issues occur.

**Comment by sroshkul** [comment]
> I redeploy the cluster with distributed pulsar mod after I clear all the old data, which doesn't reproduce the problem above

Hi,
We have similar issue.
What do you mean by "distributed pulsar mod"?
We had deployed with helm and I think it is already has pulsar cluster mode :thinking:

**Comment by yanliang567** [comment]
@sroshkul Try with the PreGA release, which is using pulsar cluster by default if deploy milvus with cluster mode
