### ISSUE TITLE
[Enhancement]: Support Milvus version in getMetric api

### ISSUE THREAD

**Issue by nameczz** [milvus-io/milvus#12240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

In getMetrics api, we can use version instead of commit id.

### Why is this needed?

SDK can do version control by Milvus version

**Comment by DragonDriver** [comment]
Closed because this has been completed. Feel free to reopen this if you have any problems about this feature.

**Comment by nameczz** [comment]
standalone version can't get right version.
![M5A1LLpo9c](https://user-images.githubusercontent.com/20559208/145744859-523d9e84-54d9-462e-bad6-7140e7018a86.png)
@DragonDriver  /reopen

**Comment by nameczz** [comment]
![image](https://user-images.githubusercontent.com/20559208/145776201-465346b7-161e-43eb-9c09-ffe1ca0f423f.png)
use docker-compose.yml to start DISTRIBUTED Milvus.
Same result.
@DragonDriver

**Comment by DragonDriver** [comment]
I will print the build information in #13300 . Next time this issue occurs again, we can then check if these env worked. @nameczz
