### ISSUE TITLE
[Bug]:  search collection hang after load and release partition

### ISSUE THREAD

**Issue by xige-16** [milvus-io/milvus#12259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

this case will hang on search
``` 
   @pytest.mark.tags(CaseLabel.L2)
    def test_release_partition_during_searching(self, connect, collection):
        """
        target: test release partition during searching
        method: insert entities into partition, flush and load partition, release partition during searching
        expected: raise exception
        """
        nq = 1000
        top_k = 1
        connect.create_partition(collection, default_tag)
        query, _ = gen_search_vectors_params(field_name, cons.default_entities, top_k, nq)
        connect.insert(collection, cons.default_entities, partition_name=default_tag)
        connect.flush([collection])
        connect.load_partitions(collection, [default_tag])
        res = connect.search(collection, **query, _async=True)
        connect.release_partitions(collection, [default_tag])
        res = connect.search(collection, **default_single_query)
        assert len(res[0]) == 0
```

### Expected Behavior

search pass

**Comment by binbinlv** [comment]
@bigsheeper 

Hello, how is the status?

Could it be fixed today？ Then today's nightly could have a try. Thanks.

**Comment by bigsheeper** [comment]
#12264 may fix it

**Comment by xige-16** [comment]
the issue still exist,

**Comment by binbinlv** [comment]
@xige-16  How is the fix going? 

Thanks.

**Comment by bigsheeper** [comment]
> @xige-16 How is the fix going?
> 
> Thanks.

#12359 would fix timeout error and return `partitions have been released` message.

**Comment by XuanYang-cn** [comment]
Happened on https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/234/pipeline/121/

**Comment by bigsheeper** [comment]
/unassign
/assign @binbinlv 
#12359 merged

**Comment by xiaofan-luan** [comment]
Should we remove the support of load collection then release partition? that brings too much complexity of the system

**Comment by yanliang567** [comment]
/assign @ThreadDao 
please help to verify the fix @ThreadDao 
/unassign @binbinlv

**Comment by binbinlv** [comment]
Fixed, and closed.
