### ISSUE TITLE
[Enhancement]: Optimize compilation of Arrow

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#12284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Follow this pr and issue: #8395 #8406

**Comment by xaxys** [comment]
Here are the problem I got when testing my code. Hope they are helpful.

It's not difficult to solve the recompile problem of Arrow library. I simply defined a folder named `arrow_build` and use find_package to prevent recompile.
But I've got some problem when linking the librarys.

- I've tried use static library of Arrow in both `core` and `cwrapper`. It will link Arrow library to a static library of core, which will be used by cgo. But it will also link Arrow library to `cwrapper` when cgo compiling. Two copy of Arrow library in finally binary program will cause a `double free` problem in go unit test. And I found it difficult find Why and How to fix it. If we link one copy    of Arrow library, that means `cwrapper` can not be compiled independently, which is not good.
- I've tried use shared library of Arrow in both `core` and `cwrapper`. It works well, all test passed. However, If I want `cwrapper` be compiled independently, I have to specify a path to place compiled shared Arrow library. I chose `arrow_build/output`. But another problem arised, I've to specify `--Wl,rpath=../../arrow_build/output`, which means the temporary folder has been used to place library and the path has been hard coded.

Maybe I could use some help.
