### ISSUE TITLE
[Bug]: why does the  container "milvus run standalone" exit(137) exit over and over again？

### ISSUE THREAD

**Issue by ZeroE04** [milvus-io/milvus#12306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.0
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus v2.0.0rc2
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: Intel Xeon Processor (Skylake)
- GPU: Tesla T4
- Others:
```

### Current Behavior

After the service crash， i do that: ① "sudo docker-compose down" ② “sudo docker-compose up -d”
but the the  container "milvus run standalone" exit(137) exit over and over again. It seems I need to delete the volumes folder and spend a lot of time building collection up again？

### Expected Behavior

when the service crash, I can reboot normally.

### Steps To Reproduce

```markdown
1. the service crash;
2. "sudo docker-compose down" 
3. “sudo docker-compose up -d”

but the  container "milvus run standalone" exit(137) exit over and over again？
```

### Anything else?

None

**Comment by xiaofan-luan** [comment]
@ZeroE04 hi zero, do you have logs when the node crash?

**Comment by yanliang567** [comment]
@ZeroE04 one more question, which version are you using ? if not rc8, could you please retry against milvus rc8 and pymilvus rc8?

/assign @ZeroE04 
/unassign

**Comment by ZeroE04** [comment]
> @ZeroE04 hi zero, do you have logs when the node crash?



> @ZeroE04 hi zero, do you have logs when the node crash?

Sorry..I have removed the volume folder, but you can do "ctrl+d" during the time when data insert，than down and up the docker again, both service crashes for me were caused by interrupt **insert**.

**Comment by ZeroE04** [comment]
> @ZeroE04 one more question, which version are you using ? if not rc8, could you please retry against milvus rc8 and pymilvus rc8?
> 
> /assign @ZeroE04 /unassign

my version is 2.0.0rc8

**Comment by yanliang567** [comment]
> > @ZeroE04 hi zero, do you have logs when the node crash?
> 
> > @ZeroE04 hi zero, do you have logs when the node crash?
> 
> Sorry..I have removed the volume folder, but you can do "ctrl+d" during the time when data insert，than down and up the docker again, both service crashes for me were caused by interrupt **insert**.

could you please try to reproduce this issue and collect the milvus logs to help us investigate this issue?
