### ISSUE TITLE
[Enhancement]:  What should be returned when the message stream is closed?

### ISSUE THREAD

**Issue by czs007** [milvus-io/milvus#12313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

When the message stream is closed, the current system behavior is inconsistent: sometimes it returns (nil error), sometimes it returns (EmptyMsg, nil), and sometimes it returns (nil, nil).
Need to discuss.

**Comment by xiaofan-luan** [comment]
I would say it should be an error? any different opinions?
