### ISSUE TITLE
[Bug]: After restarting Docker, persistent data cannot be loaded into memory 

### ISSUE THREAD

**Issue by yyp1121** [milvus-io/milvus#12310]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.0.0-rc8
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): milvus-sdk-java v2.0.0
- OS(Ubuntu or CentOS): Red Hat
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Insert 10 million data into the collection and check that the memory usage increases by 18GB. After closing Milvus, the memory is released, but after restarting, it is found that the persistent data cannot be loaded into the memory, and using the SDK or Milvus insight to search for data has been waiting until the connection times out.
[restart.log](https://github.com/milvus-io/milvus/files/7608091/restart.log)

![企业微信截图_16379233586337](https://user-images.githubusercontent.com/46116176/143568490-a3d13704-bce0-4c65-93ab-7ad26e35376e.png)
![企业微信截图_16379227232817](https://user-images.githubusercontent.com/46116176/143568502-8e59416b-b880-4b8f-b1f6-b56443f83361.png)
![企业微信截图_16379225879315](https://user-images.githubusercontent.com/46116176/143566746-f17c9e6c-eb9c-4bd8-827f-b8479b5af571.png)

 

### Steps To Reproduce

```markdown
1. Insert data into the collection
2. Restart Milvus on Docker
3. the persistent data cannot be loaded into the memory
```

**Comment by yanliang567** [comment]
@zhuwenxing could you please help to reproduce the issue on latest build?
/assign @zhuwenxing 
/unassign
