### ISSUE TITLE
check s3 connection validation when Milvus startup

### ISSUE THREAD

**Issue by liangliu** [milvus-io/milvus#1234]
**Describe the bug**

storage_config:
  primary_path: /var/lib/milvus
  secondary_path:
  s3_enable: true
  s3_address: 127.0.0.1
  s3_port: 9000
  s3_access_key: xxxxxx
  s3_secret_key: xxxxxx
  s3_bucket: myminio

milvus log output:

```
2020-02-16 19:49:13,467 | ERROR | default | [STORAGE] ERROR: CreateBucket: : Unable to connect to endpoint
2020-02-16 19:49:45,901 | ERROR | default | [STORAGE] ERROR: PutObject: : Unable to connect to endpoint

```

**Steps/Code to reproduce behavior**
**Expected behavior**
**Environment details**
**Screenshots**
**Additional context**

**Comment by JinHai-CN** [comment]
@cydrain Any update?

**Comment by cydrain** [comment]
When user set wrong s3_xxx configurations, 
Milvus will report this error "Unable to connect to endpoint", because s3 server is in-reachable.

It's expected, not an issue.

**Comment by JinHai-CN** [comment]
How about we test if the configurations are correct, when Milvus startup.

**Comment by cydrain** [comment]
Milvus will check S3 validation when start up.
When S3 check fail, Milvus will error out as following:

Milvus server exit...
S3 client start service fail: Unable to connect to endpoint
terminate called without an active exception

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

By default, S3 client will retry 10 times, totally take 50 seconds to error out.

**Comment by cydrain** [comment]
fixed
