### ISSUE TITLE
[Bug]: Timetick constraint may break when cluster datacoord restarts

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#12368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: a05a74f
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

when rootcoord restarts with several healthy proxies online waiting for it, the timetick constraint for all proxies reaches the same might be broken.

### Expected Behavior

Timetick will never be broken even chaos test introduced.

### Steps To Reproduce

```markdown
1. start cluster with multple proxies
2. restart root coordinator
3. check timetick cosntraint
```

**Comment by xiaofan-luan** [comment]
does this issue still exist?
