### ISSUE TITLE
only part of querynode pods are active when call search 

### ISSUE THREAD

**Issue by JamCrash** [milvus-io/milvus#12440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: rc8
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I create a cluster with 15 querynode pods, and create index on that cluster with 600million&64dim vectors. After that I load the collection, but I see only part of querynode pods have been loaded segments while others are not, and the search operation only be executed on the active pods and others are idle

ps: the search operation is doing well

**Comment by yanliang567** [comment]
this is a known issue in rc8, which is caused by no load balance for query node. It was fixed in latest master build, please feel free to try it, thanks

**Comment by JamCrash** [comment]
I use this image: docker pull milvusdb/milvus:v2.0.0-rc8-20211104-d1f4106
maybe it doesn't contain this fix? @yanliang567

**Comment by yanliang567** [comment]
> I use this image: docker pull milvusdb/milvus:v2.0.0-rc8-20211104-d1f4106 maybe it doesn't contain this fix? @yanliang567

No, it does not. 
you can find the latest master build here, https://hub.docker.com/r/milvusdb/milvus-dev/tags?page=1&ordering=last_updated   But please note that they are in testing phase and not offical release.
