### ISSUE TITLE
querynode produece message failed while running 

### ISSUE THREAD

**Issue by JamCrash** [milvus-io/milvus#12459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: docker pull milvusdb/milvus:v2.0.0-rc8-20211104-d1f4106
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

[container (8).log](https://github.com/milvus-io/milvus/files/7623669/container.8.log)

you can see the querynode log above, it runs fine at the beginning, but show error log while running.

[pulsar-query-node-stats.log](https://github.com/milvus-io/milvus/files/7623700/pulsar-query-node-stats.log)

and this is the topic in the pulsar which cause error in querynode, which doesn't have the correspond producer-name:my-release-pulsar-0-4690 that querynode need.

**Comment by yanliang567** [comment]
@xige-16 could you please take a look at this issue?
/assign @xige-16 
/unassign

**Comment by xiaofan-luan** [comment]
if I'm correct pulsar should automatically create topic name if it's not exist, the timeout seems to be the root cause of failure~ we've changed the default pulsar memory limit which might be helpful.

So when the timeout happens, all the pulsar proxy, broker and bookie is alive right? it would be great if there are logs

**Comment by JamCrash** [comment]
yes, there is nothing wrong at the pulsar side...

**Comment by xige-16** [comment]
@JamCrash Have you encountered this problem again? I have not been able to reproduce it locally, it would be better if I could post the pulsar log.

**Comment by JamCrash** [comment]
no, it is not reproduced until now, so I'll close this issue @xige-16
