### ISSUE TITLE
[Enhancement]: Unify param table for all components

### ISSUE THREAD

**Issue by cydrain** [milvus-io/milvus#12478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

For proxy, rootcoord, datacoord, datanode, querycoord, querynode, indexcoord, indexnode,
each has its own param_table.go, and most code are duplicated.

Suggest unify all param_table.go into one file.

### Why is this needed?

Make code clean, and improve maintainability

### Anything else?

Plan to do this in 2 stages:
Stage 1.
Create GrpcServerConfig and GrpcClientConfig in util/paramtable/global_param.go,
each component under internal/distributed/xxx maintain its own server config;
each component under internal/distributed/xxx/client maintain its own client config.

Stage 2.
Create GlobalParamTable which including all configurations except grpc, each component maintain its own config.
Divide this into 4 steps:
1) merge all param_table.go under each component into util/paramtable/global_param.go
2) put shared configurations of etcdConfig / pulsarConfig / minioConfig into BaseParamTable
3) put shared configurations of commonConfig / knowhereConfig into GlobalParamTable
4) unify API names of msgChannelConfig, then put it into GlobalParamTable

**Comment by xiaofan-luan** [comment]
can not agree more, current param table design is awful

**Comment by cydrain** [comment]
rerun failure checks

**Comment by cydrain** [comment]
Schedules (updated on 2022/02/02)
1. extract msgChannelConfig (PR #15163)
2. extract EtcdConfig from BaseParamTable, and move pulsarConfig / rocksdbConfig / minioConfig into BaseParamTable (PR #15434)
    remove dataCoordInsertChannel
3. merge msgChannelConfig / knowhereConfig into commonConfig
4. structure rename
    base_table ==> no change
    base_param ==> no change
    global_param ==> milvus_param
    grpc_param ==> new
5. move initProxySubName / initQueryNodeSubName / initDataNodeSubname into commonConfig
6. rename configration items, such as commonConfig.clusterPrefix
7. realize compatible with old configuration
