### ISSUE TITLE
[Feature]: How can I set up train_type for IVF_PQ index?

### ISSUE THREAD

**Issue by shangfu-peng** [milvus-io/milvus#12516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I'm using IVF_PQ index, it only has three parameters: nlist, m, and nbits.
But in Faiss, it has one extra parameter we can set after initialization, which is the train_type.
https://github.com/facebookresearch/faiss/blob/main/faiss/impl/ProductQuantizer.h#L37
```
enum train_type_t {
    Train_default,
    Train_hot_start,     ///< the centroids are already initialized
    Train_shared,        ///< share dictionary accross PQ segments
    Train_hypercube,     ///< intialize centroids with nbits-D hypercube
    Train_hypercube_pca, ///< intialize centroids with nbits-D hypercube
};
train_type_t train_type;
```
I really want to use "Train_shared" instead of "Train_default" in my case. May I know how to set it in Milvus? If can not for now, may I request to add this parameter in Milvus? Thanks.

In details, I want to use "Train_shared" since I want to cluster all sub-vectors as a global space instead of by default "Train_default" would cluster sub-vectors in M spaces.

### Describe the solution you'd like.

In Faiss, it is easy to change the train_type, by
```
pq_regular.train_type = ProductQuantizer::Train_shared;
```
I think add an extra string parameter for ProductQuantizer is enough.

**Comment by JackLCL** [comment]
@shangfu-peng 
What scenarios do you want to cluster all sub-vectors as a global space? We want to know whether it is a general need.

**Comment by shangfu-peng** [comment]
> What scenarios do you want to cluster all sub-vectors as a global space? We want to know whether it is a general need.

I think it is a general need. Our vector is naturally concatenated by several sub-vectors. In details, our original vector dim is 120*128 in total, which is very long. Each 128 dim is in the same global space. We want to use PQ/IVF_PQ to represent this kind of vector to reduce the index size. 

So we can choose M=120 to train PQ, and each sub-vector dim is 128. By default training, PQ would train the clusters in each m_i, where i=[0, 120). But since every 128 dim is in the same space, Training sub-vectors together would get much better results. The default train type is not desirable since
(1) The default clustering dataset is much smaller, e.g., 1/M of clustering all sub-vectors
(2) In the default train_type, every m_i would has its own clusters, cluster ids, and distance tables. They might be similar but also might be not. Since each 128 dim is in the same global space, we desire the same cluster, cluster ids, and one unique distance table.

**Comment by JackLCL** [comment]
@xiaofan-luan 
What do you think of this demand?

**Comment by shangfu-peng** [comment]
Any update for this feature request?

**Comment by JackLCL** [comment]
@shangfu-peng 
The Milvus team has been working on some stability and performance issues lately, and time is very tight. Can you work with us to develop and contribute to this feature? We can give you some technical support online.

**Comment by xiaofan-luan** [comment]
@shangfu-peng Are you interested in take this feature?
