### ISSUE TITLE
[Bug]: can not start milvus binary with sever config parameters

### ISSUE THREAD

**Issue by jasstionzyf** [milvus-io/milvus#12558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

can not find where to specify sever config parameters when start milvus binary build from source

### Expected Behavior

bin/milvus -configFile=...

**Comment by yanliang567** [comment]
@jasstionzyf do you want to customize milvus server configurations? or anything else? also can you specify reproduce steps if you are asking something specific?

/assign @jasstionzyf 
/unassign

**Comment by jasstionzyf** [comment]
@yanliang567  documents relate with directly start milvus binary is too little.
I want to know if i can and only use milvus binary to start ?
How can i customize milvus server configurations when use milvus binary?
