### ISSUE TITLE
[Bug]: Create collection failed

### ISSUE THREAD

**Issue by JamCrash** [milvus-io/milvus#12571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: rc8:latest
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): rc8 pymilvus
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

pymilvus raise error like this:

error_code: UnexpectedError
reason: "Create collection failed: send dd create collection req failed, error = message send timeout: TimeoutError"
Error: <BaseException: (code=1, message=Create collection failed: send dd create collection req failed, error = message send timeout: TimeoutError)>
.......
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=Create collection failed: send dd create collection req failed, error = message send timeout: TimeoutError)>

### Expected Behavior

after the collection create failed, if I try to create the collection with the same name, it never succeed and raise the same error
but I can create use another new name

**Comment by yanliang567** [comment]
@JamCrash could you please add any repro scripts for us? also it would be very helpful if you have any milvus proxy logs
