### ISSUE TITLE
[Bug]:  return value is incorrect in checkIndexMeta

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#12599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
```

### Current Behavior

Missing return statement.
https://github.com/milvus-io/milvus/pull/11730

**Comment by yanliang567** [comment]
@jaime0815 i think you are working on it.
/assign @jaime0815 
/unassign
