### ISSUE TITLE
no distance returned while search_by_id on binary table (jaccard, hamming, tanimoto)

### ISSUE THREAD

**Issue by liangliu** [milvus-io/milvus#1259]
**Describe the bug**
search with existing id on binary table, returned correct ids but no distances

```
Status(code=1, message="Can't find this key")
```

```
code=1
result set empty
```

**Expected behavior**
**Environment details**
**Screenshots**
**Additional context**

**Comment by JinHai-CN** [comment]
@del-zhenwu Please check if it is fixed? If so, please close the issue.

**Comment by del-zhenwu** [comment]
fixed
