### ISSUE TITLE
Graph search with Exception No Available Query node result

### ISSUE THREAD

**Issue by bluntWu** [milvus-io/milvus#12605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

java.lang.Exception: No Available Query node result, filter reason [UnexpectedError] 
: id 429206359433931035

**Comment by yhmo** [comment]
@bluntWu 

The error "No Available Query node result" means the search return an empty result so that the server side return this error.
Could you send me the client side code? And how many entities in this collection?

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Is your feature request related to a problem? Please describe.
> java.lang.Exception: No Available Query node result, filter reason [UnexpectedError] : id 429206359433931035
> 
> ### Describe the solution you'd like.
> _No response_
> 
> ### Describe an alternate solution.
> _No response_
> 
> ### Anything else? (Additional Context)
> _No response_

This issue should be fixed in GA version, duplicated with #1214i

**Comment by bluntWu** [comment]
public static List<?> searchVideo(List<List<Float>> videoVector, Integer searchNum) {
        milvusClient.loadCollection(LoadCollectionParam.newBuilder()
                .withCollectionName(VIDEO_COLLECTION_NAME)
                .build());
        System.out.println("========== searchProfile() ==========");
        List<String> outFields = Collections.singletonList(VIDEO_ID_FIELD);
        SearchParam searchParam = SearchParam.newBuilder()
                .withCollectionName(VIDEO_COLLECTION_NAME)
                .withOutFields(outFields)
                .withTopK(searchNum)
                .withVectors(videoVector)
                .withVectorFieldName(VIDEO_VECTOR_FIELD)
                .build();
        R<SearchResults> response = milvusClient.search(searchParam);
        SearchResultsWrapper wrapper = new SearchResultsWrapper(response.getData().getResults());
        for (int i = 0; i < videoVector.size(); ++i) {
            System.out.println("Search result of No." + i);
            List<SearchResultsWrapper.IDScore> scores = wrapper.GetIDScore(i);
            System.out.println(scores);
        }
        System.out.println(wrapper.GetFieldData(VIDEO_ID_FIELD).getFieldData());
        System.out.println("==============================");
        System.out.println(response);
        milvusClient.releaseCollection(ReleaseCollectionParam.newBuilder()
                .withCollectionName(VIDEO_COLLECTION_NAME)
                .build());
        return wrapper.GetFieldData(VIDEO_ID_FIELD).getFieldData();
    }

**Comment by yhmo** [comment]
@bluntWu 
I create a collection to test your client code, it works well.
If I create an empty collection, the search will return empty results. But I didn't encounter the error "No Available Query node result".

```
    public void testVideo() {
        List<List<Float>> vectors = generateFloatVectors(5);
        List<?> data = searchVideo(vectors, 10);
        System.out.println(data.size());
    }

    private List<List<Float>> generateFloatVectors(int count) {
        Random ran = new Random();
        List<List<Float>> vectors = new ArrayList<>();
        for (int n = 0; n < count; ++n) {
            List<Float> vector = new ArrayList<>();
            for (int i = 0; i < dimension; ++i) {
                vector.add(ran.nextFloat());
            }
            vectors.add(vector);
        }

        return vectors;
    }

    public List<?> searchVideo(List<List<Float>> videoVector, Integer searchNum) {
        String VIDEO_COLLECTION_NAME = "VIDEO";
        String VIDEO_ID_FIELD = "video_id";
        String VIDEO_VECTOR_FIELD = "video_vec";

        client.dropCollection(DropCollectionParam.newBuilder()
                .withCollectionName(VIDEO_COLLECTION_NAME)
                .build());

        List<FieldType> fieldsSchema = new ArrayList<>();
        fieldsSchema.add(FieldType.newBuilder()
                .withPrimaryKey(true)
                .withAutoID(true)
                .withDataType(DataType.Int64)
                .withName(VIDEO_ID_FIELD)
                .withDescription("video ids")
                .build());

        fieldsSchema.add(FieldType.newBuilder()
                .withDataType(DataType.FloatVector)
                .withName(VIDEO_VECTOR_FIELD)
                .withDescription("video vectors")
                .withDimension(dimension)
                .build());

        CreateCollectionParam createParam = CreateCollectionParam.newBuilder()
                .withCollectionName(VIDEO_COLLECTION_NAME)
                .withDescription("video")
                .withFieldTypes(fieldsSchema)
                .build();

        R<RpcStatus> createR = client.createCollection(createParam);

        List<List<Float>> insertVectors = generateFloatVectors(1000);
        List<InsertParam.Field> fieldsInsert = new ArrayList<>();
        fieldsInsert.add(new InsertParam.Field(VIDEO_VECTOR_FIELD, DataType.FloatVector, insertVectors));

        InsertParam insertParam = InsertParam.newBuilder()
                .withCollectionName(VIDEO_COLLECTION_NAME)
                .withFields(fieldsInsert)
                .build();
        R<MutationResult> insertR = client.insert(insertParam);

        R<GetCollectionStatisticsResponse> statR = client.getCollectionStatistics(
                GetCollectionStatisticsParam.newBuilder()
                .withCollectionName(VIDEO_COLLECTION_NAME)
                .withFlush(true)
                .build());

        client.loadCollection(LoadCollectionParam.newBuilder()
                .withCollectionName(VIDEO_COLLECTION_NAME)
                .build());
        System.out.println("========== searchProfile() ==========");
        List outFields = Collections.singletonList(VIDEO_ID_FIELD);
        SearchParam searchParam = SearchParam.newBuilder()
                .withCollectionName(VIDEO_COLLECTION_NAME)
                .withOutFields(outFields)
                .withTopK(searchNum)
                .withVectors(videoVector)
                .withVectorFieldName(VIDEO_VECTOR_FIELD)
                .build();
        R<SearchResults> response = client.search(searchParam);
        SearchResultsWrapper wrapper = new SearchResultsWrapper(response.getData().getResults());
        for (int i = 0; i < videoVector.size(); ++i) {
            System.out.println("Search result of No." + i);
            List<SearchResultsWrapper.IDScore> scores = wrapper.getIDScore(i);
            System.out.println(scores);
        }
        System.out.println(wrapper.getFieldData(VIDEO_ID_FIELD).getFieldData());
        System.out.println("==============================");
        System.out.println(response);
        client.releaseCollection(ReleaseCollectionParam.newBuilder()
                .withCollectionName(VIDEO_COLLECTION_NAME)
                .build());
        return wrapper.getFieldData(VIDEO_ID_FIELD).getFieldData();
    }
```
