### ISSUE TITLE
There should be timeout policy while minio server is disconnected

### ISSUE THREAD

**Issue by liangliu** [milvus-io/milvus#1260]
**Describe the bug**
1, set s3_enable=true in milvus server config file
2, make minio server disconnected
3, do as usual like creat_index

expected: sth should returned after timeout, since finally it will fail on this operation
actual: hang all the time

**Steps/Code to reproduce behavior**
**Expected behavior**
**Environment details**
**Screenshots**
**Additional context**

**Comment by JinHai-CN** [comment]
@cydrain Any update?

**Comment by cydrain** [comment]
In this failure senario, request has not been send to s3 server successfully.
After re-try 10 times (totally cost about 50 seconds), s3 client error out with:
    m_errorType = Aws::S3::S3Errors::NETWORK_CONNECTION
    m_message = "Unable to connect to endpoint"
    m_responseCode = Aws::Http::HttpResponseCode::REQUEST_NOT_MADE

This is s3's timeout mechanism.
We need not do extra code modification.

**Comment by sahuang** [comment]
This will be further investigated once s3 support is added in master branch
