### ISSUE TITLE
[Bug]: [Memory][min config] index node with 3GB limition OOM when building 40m entities

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#12632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster): master
- SDK version(e.g. pymilvus v2.0.0rc2): rc9
```

### Current Behavior

index node configured 3GB memory limited OOM-ed when trying to build index for a collection with 40 million entities

### Expected Behavior

build index successfully

### Steps To Reproduce

```markdown
1. deploy milvus with minimal config(index node memory limit: 3GB)
2. create a collection and insert 40 million entities
3. build index 
index param: {'index_type': 'HNSW', 'params': {'M': 8, 'efConstruction': 200}, 'metric_type': 'L2'}
```

### Anything else?

kubectl get pod | grep milvus-minimal                                         
```
milvus-minimal-datacoord-65b98d9766-n4qgw                         1/1     Running            0          8h
milvus-minimal-datanode-67f4c74b67-wb4xz                          1/1     Running            0          8h
milvus-minimal-etcd-0                                             1/1     Running            0          8h
milvus-minimal-etcd-1                                             1/1     Running            0          8h
milvus-minimal-etcd-2                                             1/1     Running            0          8h
milvus-minimal-indexcoord-5774ff8f45-x9sb8                        1/1     Running            0          8h
milvus-minimal-indexnode-5bbd4d6ffb-7z5tr                         0/1     OOMKilled          5          8h
```

**Comment by yanliang567** [comment]
I reran the test and insert less data(10 million entities), it still OOM. 
Then I dropped the index, the index node keeps restart for 11 times and then go back to running, which should be improved as well.
```
kubectl get pod | grep milvus-minimal
milvus-minimal-datacoord-65b98d9766-lg2n6                         1/1     Running            0          18h
milvus-minimal-datanode-67f4c74b67-xrgbj                          1/1     Running            0          18h
milvus-minimal-etcd-0                                             1/1     Running            0          18h
milvus-minimal-etcd-1                                             1/1     Running            0          18h
milvus-minimal-etcd-2                                             1/1     Running            0          18h
milvus-minimal-indexcoord-5774ff8f45-zvtxq                        1/1     Running            0          39m
milvus-minimal-indexnode-5bbd4d6ffb-m4m2h                         1/1     Running            11         43m
```

**Comment by DragonDriver** [comment]
Similar to https://github.com/milvus-io/milvus/issues/12218.

We used `InsertCodec` when building index, which has some memory leak. In this case, a collection with 40M entities will be assigned to 8 segments. Milvus will create index for every segment, so there are 8 times memory leak.

@godchen0212 is working on fixing the memory leak of codec.

**Comment by czs007** [comment]
@yanliang567  please recheck this!

**Comment by yanliang567** [comment]
on master-20211208-69259d9, i tried to build index again with index param: {'index_type': 'HNSW', 'params': {'M': 8, 'efConstruction': 200}, 'metric_type': 'L2'}
it costs 4 GB memory.
![image](https://user-images.githubusercontent.com/82361606/145323544-71d6d433-3080-42d3-9d6e-485c49f93c1f.png)

**Comment by yanliang567** [comment]
it would be perfect if we could improve more.
/assign @czs007 
/unassign

**Comment by yanliang567** [comment]
on master-20220105-a187443, the memory of index node is not keeping increase by steps. After about 24h running(build index and drop index in a loop), the memory is almost flat. But the memory consumption is more than 6GB, which is too much for 10 million entities(5G)
![image](https://user-images.githubusercontent.com/82361606/148494158-a0bb4c75-2a94-41d8-9fb6-bdceb33f5dd0.png)

**Comment by xiaofan-luan** [comment]
@yanliang567 can we close the issue?

**Comment by czs007** [comment]
In the case of a segment of a certain size, the memory consumption of different index types may also be different. It's hard to say what the optimal reduction will be until the index memory footprint is modeled.

@yanliang567

**Comment by xiaofan-luan** [comment]
> In the case of a segment of a certain size, the memory consumption of different index types may also be different. It's hard to say what the optimal reduction will be until the index memory footprint is modeled.
> 
> @yanliang567

if we build each index segment by segment, the index node memory should be just a little bit more than build a index on segment needed right? should be no more than 100m data by  default
