### ISSUE TITLE
[Enhancement]: QueryNode releases the segment asynchronously.

### ISSUE THREAD

**Issue by czs007** [milvus-io/milvus#12635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

When trying to delete a segment, if there is a query in progress, you can mark it as delete, and then delete the segment after the query is completed. The segment marked as delete cannot serve new queries.

### Why is this needed?

Currently, when querynode releases a segment, it needs to acquire a mutex lock. When a query is in progress, the request for ReleaseSegment takes a long time.

**Comment by xiaofan-luan** [comment]
keep this issue open for tracking
