### ISSUE TITLE
[Bug]: Files in minio are not deleted in setting time

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#12648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:d40f4a6
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):rc9.22
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: 
  Compaction and GC enabled:
  enableCompaction: true
  enableGarbageCollection: true
  gc:
    interval: 60 
    missingTolerance: 60 
    dropTolerance: 60
```

### Current Behavior

In minio, some collections are deleted, but there are still large numbers of collection exists for relatively long time compared with 60s.

(Will check whether it is very slow or not even deleted until tomorrow)

### Expected Behavior

All the dropped collections are deleted in setting time (at least not a big gap)

### Steps To Reproduce

```markdown
Run CI
```

**Comment by binbinlv** [comment]
@congqixia Hello, congqi, Is this pr (#12702) the complete fix for this issue? Thanks.

**Comment by congqixia** [comment]
> @congqixia Hello, congqi, Is this pr (#12702) the complete fix for this issue? Thanks.

@binbinlv just verified locally with L0 test cases, all fails remains are related to collections that are not dropped.
BTW, this process is kind of annoying.

**Comment by congqixia** [comment]
/unassign
/assign @binbinlv 
@binbinlv could you please verify?

**Comment by yanliang567** [comment]
/assign @ThreadDao 
please help to verify the fix @ThreadDao 
/unassign @binbinlv

**Comment by binbinlv** [comment]
Verified, and fixed.

Milvus: 1276654
pymilvus: 2.0.0rc9.dev24
