### ISSUE TITLE
[Bug]: querynode data can't be released after querycoord ReleaseDQLMessageStream failed

### ISSUE THREAD

**Issue by xige-16** [milvus-io/milvus#12662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

if querycooord ReleaseDQLMessageStream failed, collection meta has been removed from coord's meta, so Even if the release request is received again, the data on querynode cannot be cleaned up

### Expected Behavior

after release collection failed, data also can be released on querynode

**Comment by xiaofan-luan** [comment]
@xige-16 can we close this issue?

**Comment by xige-16** [comment]
> @xige-16 can we close this issue?

Yes, this issue no longer exists
