### ISSUE TITLE
Disk is still in use after milvus server docker stoped and removed

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#1266]
**Describe the bug**
Disk space is full after vectors added into server table, but disk space is still in use after milvus server docker stoped and removed.

Before `docker stop && docker rm`:
```
/dev/sda4             1716083204  1623881180     4959992 100% /home
```
After `docker stop && docker rm`:
```
/dev/sda4             1.6T   17G  1.6T   2% /home
```

**Steps/Code to reproduce behavior**

**Expected behavior**

**Environment details**
branch: crud 

**Screenshots**

**Additional context**

**Comment by JinHai-CN** [comment]
Maybe it is caused by not closing after open the file. You can try to reproduce it now.

**Comment by del-zhenwu** [comment]
in-regression

**Comment by shengjun1985** [comment]
Inactive. Close.
