### ISSUE TITLE
[Enhancement]: Disable mutliple vector fields in a collection 

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#12680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Features of multiple vector fields in one collection requires more further investigation. So let's disable it for now

### Why is this needed?

a not well defined feature would confuse us.

**Comment by perrital** [comment]
Any  news about multiple vector fields (relevant for production environments having multiple versions of embedding models)?

**Comment by yanliang567** [comment]
> Any news about multiple vector fields (relevant for production environments having multiple versions of embedding models)?

not yet, for now I suggest you have multiple collections for different versions of embedding models.
