### ISSUE TITLE
[Bug]: The first insert time of large message(50MB)  for new collection is 10x slower than the following insert

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#12701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20211203-1a806a1
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc9.dev22
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

see #12081

```
first run: end insert, time: 242.40249490737915
second run: end insert, time: 25.066824197769165
```

**Comment by czs007** [comment]
very good

**Comment by XuanYang-cn** [comment]
Possible useful ref:

- https://github.com/grpc/grpc-go/issues/1043
- https://github.com/grpc/grpc-go/pull/1310
- https://github.com/grpc/grpc-go/pull/1153/files
- https://github.com/grpc/grpc-go/blob/master/internal/transport/defaults.go
- https://github.com/grpc/grpc-go/pull/1952

**Comment by czs007** [comment]
can you refer this to other related issues? @XuanYang-cn

**Comment by zhuwenxing** [comment]
[test.log](https://github.com/milvus-io/milvus/files/7647987/test.log) # this is test.py
 
[first_run.log](https://github.com/milvus-io/milvus/files/7647960/first_run.log)
[second_run.log](https://github.com/milvus-io/milvus/files/7647963/second_run.log)

### 
log
[test-insert-slow-12-03-16-49-00.zip](https://github.com/milvus-io/milvus/files/7648044/test-insert-slow-12-03-16-49-00.zip)


insert time and search time of first run both much larger than second

* insert
first run
![image](https://user-images.githubusercontent.com/12268675/144574608-c6bf3da1-9808-422c-8dd1-c202d19c0939.png)
second run
![image](https://user-images.githubusercontent.com/12268675/144574694-ea5713b0-4249-4eb4-86ac-e8cc14deb1b4.png)
 

* search
first run
![image](https://user-images.githubusercontent.com/12268675/144574909-328b6892-4ad1-4745-b207-d899918d966c.png)
second run
![image](https://user-images.githubusercontent.com/12268675/144575040-d2ab66b6-ae07-49ad-afec-05e6247a506a.png)

**Comment by XuanYang-cn** [comment]
@zhuwenxing If you remove the `description` from the `CollectionSchema`, the insert will be normal.

Very strange, investigating now.

**Comment by XuanYang-cn** [comment]
a summarize blog https://grpc.io/blog/grpc-go-perf-improvements/

**Comment by yanliang567** [comment]
weird...
@zhuwenxing could you please try it

**Comment by XuanYang-cn** [comment]
Actually, it's not a description problem, it's the size of the insert-entities problem.

Just adding another field without the description will reproduce this too.

Still looking into this.

**Comment by XuanYang-cn** [comment]
Still cannot stably reproduce, cannot locate the root cause.

**Comment by XuanYang-cn** [comment]
every insert time of 200 nb for 2000 times
![Figure_4](https://user-images.githubusercontent.com/51370125/145805508-98ba903d-61ab-41b9-a3bf-86773e8e5ce7.png)

**Comment by XuanYang-cn** [comment]
another go
![Figure_1](https://user-images.githubusercontent.com/51370125/145808577-b0814041-cd7b-4474-9534-3c9487d027f0.png)

**Comment by zhuwenxing** [comment]
In local terminal: (server and client are not in same machine)
![image](https://user-images.githubusercontent.com/12268675/145927158-44a985db-a93c-46ab-92c8-93f0226e2cbe.png)
In GitHub action: (server and client are in same machine)
![image](https://user-images.githubusercontent.com/12268675/145927245-802e18f3-4ae4-4dca-8c69-2371617744c6.png)

**Comment by XuanYang-cn** [comment]
I'm wondering how many machines our VPN has travelled during the insert.  Especially when 2 VPNs are on.

**Comment by XuanYang-cn** [comment]
Tried `go trace` last week, not helpful.

This week:
```
1. Try minimum reproducing scripts
  - Try refined pymilvus pr 846
  - Try 1.x APIs
  - Try golang SDK
2. Try singlenode, if reproduced, test on different network environments
3. fully understand go grpc
```

**Comment by xiaofan-luan** [comment]
> @zhuwenxing If you make the length of the `description` string in `CollectionSchema` less or equal to 10, the insert will be normal.
> 
> Very strange, investigating.

Might be a tcp slow start issue? do we knwo how large is pkt size?
However even if slow start happen, it should introduce 1 or 2 round trip latency

**Comment by XuanYang-cn** [comment]
> > @zhuwenxing If you make the length of the `description` string in `CollectionSchema` less or equal to 10, the insert will be normal.
> > Very strange, investigating.
> 
> Might be a tcp slow start issue? do we knwo how large is pkt size? However even if slow start happen, it should introduce 1 or 2 round trip latency

1. The description thing cannot be reproduced stably.
2. http2 uses 1 TCP connection, and in our case, once it starts slow, it'll be slow forever in ONE script. So it's not a tcp-slow-start problem.

**Comment by XuanYang-cn** [comment]
Good news: use milvus-io/pymilvus#846, the insert slow problem is gone.

Bad news: don't know why, 846 removes orm's dependency of `Milvus()`, and removes complicated connection pools, uses pure grpc-channel to manage connections.

**Comment by XuanYang-cn** [comment]
So this is a PyMilvus problem, and since it'll be fixed by 846, I think it's not worth the effort to investigate the reason why.

PyMilvus connection control before 846 is useless and meaningless since grpc already hides the complexity of connections control inside the channels.

**Comment by XuanYang-cn** [comment]
@zhuwenxing Do you want to try milvus-io/pymilvus#846 ?

**Comment by zhuwenxing** [comment]
Test with the client in k8s, this issue is not reproduced
* pymilvus-2.0.0rc9.dev27
   * first insert: begin insert, count: 50000 ,nb: 10000 end insert, time: 15.271641492843628
   * second insert: begin insert, count: 50000 ,nb: 10000 end insert, time: 16.773897171020508
* pymilvus-2.0.0rc9.dev28
    * first insert: begin insert, count: 50000 ,nb: 10000 end insert, time: 13.423330307006836
    * second insert: begin insert, count: 50000 ,nb: 10000 end insert, time: 13.418224811553955

**Comment by xiaofan-luan** [comment]
@XuanYang-cn how is the current behaviour?
