### ISSUE TITLE
WAL config check failed

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#1271]
**Describe the bug**
```
  buffer_size: 0   # MB
  record_size: 2     # MB
```
the above field value can be set 0 and server start successfully, expected server exit
**Steps/Code to reproduce behavior**

**Expected behavior**

**Environment details**
branch: crud

**Screenshots**

**Additional context**

**Comment by shengjun1985** [comment]
The serve will check and correct the value automaticly.
So I think that it is not a bug.
To avoid misunderstandings, I still updated the config template (pr 1284).
Thank you.

# buffer_size          | The size of two buffers in wal, both read buffer and write | Integer    | 128             |
#                      | buffer share the same size. Unit is MB.                    |            |                 |
#                      | It should be in range [64, 2048]. If the value set out of  |            |                 |
#                      | the range, the system will use the boundary value.         |            |                 |
#----------------------+------------------------------------------------------------+------------+-----------------+
# record_size          | Max size of one single wal record. Unit is MB.             | Integer    | 2               |
#                      | It should be in range [1, buffer_size]. If the value set   |            |                 |
#                      | out of the range, the system will use the boundary value.  |            |                 |
