### ISSUE TITLE
[Bug]: <BaseException: (code=1, message=round_decimalnot found in search_params)>

### ISSUE THREAD

**Issue by arshikasoni** [milvus-io/milvus#12741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:  milvus:v2.0.0-rc7-20211011-d567b21
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.0.0rc5
- OS(Ubuntu or CentOS):Ubuntu 18.04.6
-OSType: linux
-Architecture: x86_64
-CPUs: 6
-Total Memory: 15.46GiB

- Others: 
Docker version 20.10.10
```

### Current Behavior

I am doing image search engine using milvus and i am following this official website for this:

[https://github.com/milvus-io/bootcamp/blob/master/solutions/reverse_image_search/reverse_image_search.ipynb](url)
![Screenshot from 2021-12-04 10-09-18](https://user-images.githubusercontent.com/91525850/144697834-19e73a0c-a477-4c29-a93a-925bde9cf17d.png)
![Screenshot from 2021-12-04 10-08-23](https://user-images.githubusercontent.com/91525850/144697835-5f44ea1b-7086-423f-94bf-6e72a77a44b4.png)

When i am making embeddings to search from a collection then i am getting this base exception error and when i am converting embeddings to list and then searching it then i am getting search data illegal value error . I am attaching screenshots for reference 

### Steps To Reproduce

I am following official doc and still getting these errors

### Anything else?

If anyone can help , your help will be appreciated, Thanks

**Comment by yanliang567** [comment]
@arshikasoni could you please retry with the Milvus rc8 and Pymilvus rc8? It seems that the Pymilvus version is not matched with Milvus server.

/assign @arshikasoni 
/unassign

**Comment by arshikasoni** [comment]
Yes it is working now..Thanks for the help..!!

**Comment by arshikasoni** [comment]
But after some days again this problem is started .May i know the reason now?

**Comment by arshikasoni** [comment]
![image](https://user-images.githubusercontent.com/91525850/148634260-cf4fd823-a311-41f2-9bff-c78afee5d0fd.png)

![image](https://user-images.githubusercontent.com/91525850/148634271-e809c193-4b29-4834-b710-b22c0b0fa3d6.png)
Now versions are matching but i am getting the same error again

![image](https://user-images.githubusercontent.com/91525850/148634287-a20a0115-73a1-4610-ada0-ca8126e7ea45.png)

**Comment by xiaofan-luan** [comment]
should be already fixed by https://github.com/milvus-io/milvus/pull/9626
what kind of error do you get?

**Comment by arshikasoni** [comment]
It is not fixing 
illegal error is always there , even if i try converting it to list then also the error is same

**Comment by xiaofan-luan** [comment]
what is the full error message? that seems to be the different issue, the vector seems not pass pymilvus parameter check

**Comment by arshikasoni** [comment]
![image](https://user-images.githubusercontent.com/91525850/148634905-b652ba24-f556-4d92-a735-b5671e155eff.png)
![image](https://user-images.githubusercontent.com/91525850/148634916-a1a03e30-371e-47b4-b309-ddecb5c4721b.png)
![image](https://user-images.githubusercontent.com/91525850/148634931-b0a604ca-fd84-43a6-9dd9-ad9ca328ed06.png)

**Comment by arshikasoni** [comment]
![image](https://user-images.githubusercontent.com/91525850/148634968-ff4669b4-ddce-4ac7-94b5-3236dd2677d8.png)

**Comment by XuanYang-cn** [comment]
Seems like the `embeddings` didn't pass this check

```python
  196 def is_legal_search_data(data: Any) -> bool:
  197     import numpy as np
  198     if not isinstance(data, (list, np.ndarray)): 
  199         return False
  200
  201     for vector in data:
  202         # list -> float vector
  203         # bytes -> byte vector
  204         if not isinstance(vector, (list, bytes, np.ndarray)):
  205             return False
  206
  207     return True
```

We only support `list` and `np.ndarray`
