### ISSUE TITLE
[Bug]: Search topK is smaller than expected after compaction

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#12750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.0.0rc9.dev22 
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search topK is smaller than expected after compaction

### Expected Behavior

Search topK is equal with expected after compaction

### Steps To Reproduce

Run nightly:
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/249/pipeline

1. Logs: [standalone: artifacts-milvus-standalone-master-249-pymilvus-e2e-logs.tar.gz]
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/249/artifacts/

2. Failed test case:
test_compact_merge_and_search

3. Failed test case: collection name:
compact_tVXxhQhB

4. TimeLine:
```
[2021-12-04T20:09:58.516Z]         for hits in search_res:
[2021-12-04T20:09:58.516Z] >           assert len(hits) == ct.default_limit
[2021-12-04T20:09:58.516Z] E           assert 9 == 10
[2021-12-04T20:09:58.516Z] E             +9
[2021-12-04T20:09:58.516Z] E             -10
```

**Comment by binbinlv** [comment]
Not occurs steadily.

**Comment by xige-16** [comment]
same error at test_compact_after_binary_index 
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-13110/12/pipeline/

**Comment by xige-16** [comment]
same error at test_compact_merge_and_search

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-13110/11/pipeline
