### ISSUE TITLE
[Bug]: milvus cannot connect to etcd when inject istio sidecar

### ISSUE THREAD

**Issue by JamCrash** [milvus-io/milvus#12761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: rc8 
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

all milvus node will occur logs like this: 
[container (9).log](https://github.com/milvus-io/milvus/files/7657858/container.9.log)

k8s deployment yaml:

[dpl.zip](https://github.com/milvus-io/milvus/files/7657899/dpl.zip)

**Comment by zwd1208** [comment]
We haven't tested run milvus with istio. maybe we'll do some tests later

**Comment by JackLCL** [comment]
@JamCrash 
What istio version do you use?

**Comment by JamCrash** [comment]
istio version 1.7.3

**Comment by JackLCL** [comment]
@zwd1208 
Do we have some updates in preGA about this issue?

**Comment by xiaofan-luan** [comment]
leave it open for more testing
