### ISSUE TITLE
SQLite throw exception when create 50000+ partitions in a table

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#1276]
**Describe the bug**
1. create a table
2. try create 100000 partition in this table
get exception "database is locked" after 50000+ partition created

**Comment by JinHai-CN** [comment]
Maybe we should limit the partition number.

**Comment by yhmo** [comment]
limit to 5000

**Comment by tinkerlin** [comment]
@del-zhenwu regression test

**Comment by del-zhenwu** [comment]
create 5001 partitions in a collection successfully,
