### ISSUE TITLE
[Enhancement]: Support a brute force search vector index 

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#12781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Support a brute force search algorithm that is a kind of vector index, it doesn't depend on thirdparty libs and can be run on Mac/Ubuntu.

### Why is this needed?

Decoupling segcore and faiss, segcore should directly access knowhere interface rather than faiss libs.

**Comment by xiaofan-luan** [comment]
can we use IVF FLAT inside knowhere?

**Comment by xiaofan-luan** [comment]
are we still working on this issue? @jaime0815 @soothing-rain
