### ISSUE TITLE
search_by_id/delete_by_id not supported yet when gpu resource enabled

### ISSUE THREAD

**Issue by liangliu** [milvus-io/milvus#1285]
**Describe the bug**
search_by_id/delete_by_id not supported yet when gpu resource enabled

**Steps/Code to reproduce behavior**
**Expected behavior**
**Environment details**
**Screenshots**
**Additional context**

**Comment by youny626** [comment]
Currently if GPU search resource is enabled, search_by_id and delete_by_id will return error

**Comment by sahuang** [comment]
When gpu resource enabled, search_by_id and delete_by_id works as expected under current master branch.

**Comment by sahuang** [comment]
Needs further discussion..
