### ISSUE TITLE
[Bug]: Segment size bigger than dataCoord.segment.maxSize

### ISSUE THREAD

**Issue by DragonDriver** [milvus-io/milvus#12860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Create collection with a float vector field whose dim is `128`.
Insert 40M entities.
Flush collection.

Then I got 8 segments, the num_rows of those segments are [669930, 1545264, 6298320, 6297564, 6299608, 6297342, 6294408, 6274564]

### Expected Behavior

The size of every segment should be less than dataCoord.segment.maxSize. In other word, the num_rows should be less than `512 * 1024 * 1024/（128 * 4） = 1048576`

**Comment by yanliang567** [comment]
@DragonDriver is this a regression issue? I remember we have tested the config of dataCoord.segment.maxSize, it worked at that time.

**Comment by DragonDriver** [comment]
> @DragonDriver is this a regression issue? I remember we have tested the config of dataCoord.segment.maxSize, it worked at that time.

Nope. I reproduced this issue on my local pc.

**Comment by DragonDriver** [comment]
I made a mistake, actually the dim of float vector field is 8 instead of 128.
Apologize if you spent any time for this meaningless issue.
Closed this.
