### ISSUE TITLE
[Bug]: MaxfieldNum is not valid

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#12881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20211207-b97e88e
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.0.0rc9dev22 
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Modify testcase test maxfieldnum=256
[milvus.yaml ](https://github.com/milvus-io/milvus/blob/master/configs/milvus.yaml)

<img width="1440" alt="截屏2021-12-07 下午3 53 09" src="https://user-images.githubusercontent.com/34296482/144988575-75b1982e-163e-47ec-aa09-27b30dbd86a4.png">

server:

<img width="989" alt="截屏2021-12-07 下午3 58 12" src="https://user-images.githubusercontent.com/34296482/144989265-96f85b69-1bb5-4fe0-beab-011ea373646d.png">

[docker-compose.yml.zip](https://github.com/milvus-io/milvus/files/7666657/docker-compose.yml.zip)

**Comment by yanliang567** [comment]
@yhmo could you please help to take a look at this issue?
/assign @yhmo 
/unassign

**Comment by jingkl** [comment]
Probably the problem is the image, using the master-latest image and tested once again is OK
