### ISSUE TITLE
[Enhancement]: Need a tool to calculate the memory, CPU resource, and the number of different kinds of pods for Milvus2.0.

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#12896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Milvus2.0 needs a tool to calculate the memory, CPU resource, and the number of different kinds of pods.
Milvus1.x has a [sizing tool](https://milvus.io/cn/tools/sizing), and milvus2.0 also needs one, maybe more powerful.

For example, if I have a billion 128-dimensional vectors, how much memory resources, CPU resources and how much persistent storage do I need in total. How many proxy pods, query-node pods, data-node pods, index-node pods should I configure, how much memory should I allocate to each pod, and how many CPU resources should I allocate to each pod.

### Why is this needed?

Milvus 2.0 is a vector database with a more complex distributed architecture than Milvus 1.0. Many users do not know how many hardware resources they need to allocate for their data volume, or how many k8s pods should be allocated for each of the different functions. It would be helpful to have a tool like this to help users solve this problem.

### Anything else?

None.

**Comment by xiaofan-luan** [comment]
Anyone interested please assign yourself

**Comment by xiaofan-luan** [comment]
Anyone want to take it?

**Comment by JackLCL** [comment]
Any updates for this issue?

**Comment by xiaofan-luan** [comment]
keep it open
