### ISSUE TITLE
Remove excessive stdout print "Span1: *ms"

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#1291]
**Describe the bug**
docker logs:
```
Span3: 2.85202ms
Span4: 0.040296ms
Span1: 1.70714ms
Span2: 38.7435ms
Span3: 7.68692ms
Span4: 0.046053ms
Span1: 4.76334ms
Span2: 38.5912ms
Span3: 8.3038ms
Span4: 0.04422ms
Span1: 0.552392ms
Span2: 24.4796ms
Span3: 2.38631ms
Span4: 0.040887ms
Span1: 0.536723ms
Span2: 24.3627ms
Span3: 3.25095ms
Span4: 0.057799ms
Span1: 1.39636ms
```

too much print during server running

**Steps/Code to reproduce behavior**
output these message into log file

**Expected behavior**

**Environment details**
master

**Screenshots**

**Additional context**

**Comment by JinHai-CN** [comment]
@cydrain Already fixed?

**Comment by cydrain** [comment]
duplicate with #1320 
already fixed
