### ISSUE TITLE
[Enhancement]: Automatically replace the index for the sealed segment after load 

### ISSUE THREAD

**Issue by xige-16** [milvus-io/milvus#12958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

After load collection/partition done, Querycoord automatically checks which sealed segments have only loaded the original vector into the memory, and judges whether the index of the sealed segment exists. If the index has been created, querycoord is responsible for replacing a segment in the querynode that only loads the original vector with the segment that loads the index.

### Why is this needed?

For some segments, the index may not have been created when it is loaded, so you can only load the original vector first, and serve the query in the form of an explosive search. After the index is built, the index should be loaded into the memory as soon as possible to speed up the query.

**Comment by yanliang567** [comment]
lets keep it for tracking

**Comment by yanliang567** [comment]
keep it for tracking
