### ISSUE TITLE
Server build failed on  centos-7.0

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#1296]
**Describe the bug**
http://jenkins.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ci/detail/crud/142/pipeline/109

**Steps/Code to reproduce behavior**

**Expected behavior**

**Environment details**
branch: crud

**Screenshots**

**Additional context**

**Comment by JinHai-CN** [comment]
Looks fixed.
