### ISSUE TITLE
[Bug]: The num of proxy nodes returned by pymilvus is wrong

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#12972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20211207-b06fe92
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc9.dev22
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The proxy num returned by pymilvus is one when two proxy nodes are deployed

### Expected Behavior

The proxy num returned by pymilvus is two

### Steps To Reproduce

```markdown
1. deploy a cluster milvus with two proxy replicas
2. init an object of class `MilvusSys` in `tests/python_client/common/milvus_sys.py`
3. assert `len(ms.proxy_nodes) == 2`
```

**Comment by DragonDriver** [comment]
It's reasonable. Proxy didn't watch the proxy nodes in etcd now. So a `GetMetrics` response returned by the specific proxy will only contain itself in the system topology graph. @zhuwenxing

**Comment by zhuwenxing** [comment]
> It's reasonable. Proxy didn't watch the proxy nodes in etcd now. So a `GetMetrics` response returned by the specific proxy will only contain itself in the system topology graph. @zhuwenxing

So there is no other way to get actual proxy node numbers by pymilvus?
If so, we can just get it by k8s API.

**Comment by DragonDriver** [comment]
> 

I also considered this situation. It's easy to get all proxy nodes by etcd, but I don't think it's clear in the system topology graph.

**Comment by zhuwenxing** [comment]
by design, won't fix!
