### ISSUE TITLE
Hide partition_name parameter, avid user directly access partition table

### ISSUE THREAD

**Issue by shengjun1985** [milvus-io/milvus#1297]
[Background]
In version 0.6.0, any partition can be created with a globally unique partition name.
In many interfaces, this partition name can be used as a table name.
Here is an example:
  (1) CreateTable(table_name);
  (2) CreatePartition(table_name, partition_name, partition_tag);
  (3) InsertVectors(table_name, partition_tag, vector_data);
  (4) InsertVectors(partition_name, “”, vector_data);
Where (3) and (4) have the same effect.
In addition, Query() and CreateIndex() have the same usage too.

[Problem]
According to the design, 0.7.0 will add WAL and 2 new operations: DeleteVectors() and Flush().
Should we still support Partition_Name in 0.7.0 ?

[Option]
(1) Not to support Partition_Name
Effect:
  Those who used partition_name before need to modify their codes.

(2) Still support Partition_Name
Effect:
  It is must to specify the interfaces definition, such as Flush() and DeleteVectors().
  Many operations may need to determine the param whether is Table_Name or Partition_Name before implementation.

[Suggestion]
I prefer to option(1) because the usage of Partition_Name has bright a lot of confusion.

**Comment by JinHai-CN** [comment]
With partition tag, all use cases can be satisfied from my point of view. So I also support option1, which means we need to update the code to suppress the current partition name usage. Lots of API will be impacted. @yhmo

**Comment by yhmo** [comment]
Fixed by #1315
