### ISSUE TITLE
[Bug]: Memory leakage happens on binlog reader throw err

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#12993]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/83447078/145188235-02d78aa2-c3b4-4195-a277-48ae70faaafc.png)
if error happens on parse data, binlogReader is left without close, which means memory will leak if error happens.

### Expected Behavior

we need to release reader after error happens

**Comment by congqixia** [comment]
I think this pr(#12995) has fixed this issue.

**Comment by xiaofan-luan** [comment]
close it for now, duplicated with #12995
