### ISSUE TITLE
Data in WAL may be accidentally inserted into a new table with the same name

### ISSUE THREAD

**Issue by shengjun1985** [milvus-io/milvus#1301]
[Problem]
In the WAL enable state, CreateTable() and DropTable() are executed synchronously, while InsertVectors() are executed asynchronously.
Thus, the following sequence may cause a bug.
(1) CreateTable("table_a");
(2) InsertVectors("table_a", vector_data);
(3) DropTable("table_a);
(4) CreateTable("table_a");

Now, we expected an empty table_a.
But in fact, (2) may be executed after (4), so that the data of (2) is accidentally inserted into the new table.
The bug occurs.
Further more, the partition tag will cause the same problem.

[Solution]
Assign a global unique ID to each table and each partition.
The table or partition with the same name created in succession has a different ID.
Then, the bug can be fixed.

[Modify Modlue]
Meta / WAL / MemManager

**Comment by yhmo** [comment]
milvus::engine::meta::TableSchema table_schema;
table_schema.table_id_ = TABLE_NAME;
db_->DescribeTable(table_schema);
table_schema.id_           is the unique id of a table

**Comment by shengjun1985** [comment]
The unique table ID is not enough.
An unique partition ID is necessary too.
So, I don't think it is the right time to solve the issue. 

[temporary solution]
To avoid the bug, a user can call flush() before he creating a table of the same name.

**Comment by JinHai-CN** [comment]
Please try to fix it in 0.7.0. @shengjun1985

**Comment by JinHai-CN** [comment]
Move the issue to 0.8.0.

**Comment by shengjun1985** [comment]
The problem can be fixed by checking table LSN.
I will fix it later.
