### ISSUE TITLE
Get all record IDs in a segment by given a segment id

### ISSUE THREAD

**Issue by JinHai-CN** [milvus-io/milvus#1302]
**Is your feature request related to a problem? Please describe.**
In Milvus GUI scope, user can get all records and show them. But we don't have the interface to get all vectors. Even if we provide such interface, the result will be too huge for any system. Therefore, we need to get part of the records. Now, the solution is GUI can get all segments detailed info of a table. If GUI can get all IDs of the records of a segments, then GUI can get all records of the segment by loop calling interface GetVectorByID. Therefore we can develop an interface to get all record IDs in a segment by a given segment id.

**Describe the solution you'd like**
Currently, all record IDs of a segment are stored in a separate file. Milvus just need to get all the IDs and remove part of them according to the DEL file and return them.
I proposed the interface name: GetIDsInSegment
Input parameters: table name, partition_tag, segment id
Return value: {ids}

**Describe alternatives you've considered**

**Additional context**
- A new interface is added. 
- HTTP and C++/Python/Java/Go SDK are impacted.
- Proto file is impacted.
- HTTP and SDK Documents are impacted.

**Comment by yhmo** [comment]
Fixed by #1370
