### ISSUE TITLE
[Enhancement]: Split Session Init

### ISSUE THREAD

**Issue by czs007** [milvus-io/milvus#13072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

I suggest to split Session's `Init` method to `Init` and `Register`

```
// Init will initialize base struct of the Session, including ServerName, ServerID,
// Address, Exclusive. ServerID is obtained in getServerID.
// Finally it will process keepAliveResponse to keep alive with etcd.
func (s *Session) Init(serverName, address string, exclusive bool) {
	s.ServerName = serverName
	s.Address = address
	s.Exclusive = exclusive
	s.checkIDExist()
	serverID, err := s.getServerID()
	if err != nil {
		panic(err)
	}
	s.ServerID = serverID
	ch, err := s.registerService()
	if err != nil {
		panic(err)
	}
	s.liveCh = s.processKeepAliveResponse(ch)
	s.UpdateRegistered(true)
}
```

The above code is the current implementation of Session. Three things are done in `Init`: get ID, register etcd service, open background coroutine to process keepalive response message.

It is recommended to split the above logic into 2 functions: `Init` and `Register`.  In the `Init` function, only initialization such as obtaining ID is done.

```
// Init will initialize base struct of the Session, including ServerName, ServerID,
// Address, Exclusive. ServerID is obtained in getServerID.
// Finally it will process keepAliveResponse to keep alive with etcd.
func (s *Session) Init(serverName, address string, exclusive bool) {
	s.ServerName = serverName
	s.Address = address
	s.Exclusive = exclusive
	s.checkIDExist()
	serverID, err := s.getServerID()
	if err != nil {
		panic(err)
	}
	s.ServerID = serverID
}
```

Add a new interface called `Register`.  Register etcd in `Register` and start the coroutine to process keepalive response messages.

```
func (s *Session) Register() {
	ch, err := s.registerService()
	if err != nil {
		panic(err)
	}
	s.liveCh = s.processKeepAliveResponse(ch)
	s.UpdateRegistered(true)
}
```

### Why is this needed?

After node A registers with etcd, the node can be discovered by other components.  Before node A is discovered by other components, the sooner it enters Healthy, the better.

Take IndexNode as an example. When IndexNode registers etcd, it starts to start the grpc service, and then enters the Healthy state after initializing all its internal objects.

On the IndexCoordinator side, when a new IndexNode node is found online from etcd, it immediately starts the coroutine to do the following:
1) Create a grpc link Client object with indexNode
2) Call some rpc methods to collection IndexNode's information
3) Add the Client object and other information to the NodeManager

If any of the above 3 steps fails, IndexCoord cannot manage the Node. There may be many reasons for the errors in the above three steps. The high probability occurs when IndexNode has not started the grpc service or has not entered the Healthy state when IndexCoord initiate an rpc request.

Therefore, a better change is that IndexNode will not register with etcd unless it is sure that it enters Healthy. Furthermore, after IndexCoord finds an IndexNode that has entered the Healthy state, the follow-up actions can proceed quickly and smoothly.

**Comment by xiaofan-luan** [comment]
please also take a look at other components, thanks czs
