### ISSUE TITLE
[Feature]: Please add a search qps monitor metrics in "/metrics"

### ISSUE THREAD

**Issue by JamCrash** [milvus-io/milvus#13095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Maybe milvus need a search qps monitor metrics in "/metrics" ?

**Comment by yanliang567** [comment]
if remember correct, this is something we planned in 2.1 or later
@xiaofan-luan  right?

**Comment by xiaofan-luan** [comment]
I guess even for now those are important metrics.
QPS and latency are very important metrics. Maybe we need a document about how to add metrics so @JamCrash can help us on adding more metrics he/she need @czs007

**Comment by JackLCL** [comment]
> I guess even for now those are important metrics. QPS and latency are very important metrics. Maybe we need a document about how to add metrics so @JamCrash can help us on adding more metrics he/she need @czs007

Many users need QPS and latency metrics.

**Comment by yanliang567** [comment]
lets keep it for tracking
