### ISSUE TITLE
Add default partition tag for a table

### ISSUE THREAD

**Issue by JinHai-CN** [milvus-io/milvus#1310]
**Is your feature request related to a problem? Please describe.**
Currently, User insert data into a table without giving any partition. The data will be insert into default partition. But currently, we don't have any default partition information, including partition_tag. GetTableInfo API will also return the default partition.

**Describe the solution you'd like**
Add a default partition_tag '_default' to the table. 

**Describe alternatives you've considered**
N/A

**Additional context**
No impact on API.

**Comment by yhmo** [comment]
Fixed by #1315
