### ISSUE TITLE
[Bug]: Proxy failed to stop normally when kill ETCD service

### ISSUE THREAD

**Issue by czs007** [milvus-io/milvus#13111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: lastest
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): latest
- OS(Ubuntu or CentOS):  Ubuntu
```

### Current Behavior

The proxy still runs even if kills the ETC service.

### Expected Behavior

Proxy stop normally when its dependent critical service such as ETCD stoped.

### Steps To Reproduce

```markdown
1. Deploy Milvus in cluster mode
2. kill ETCD Service

You can see that the proxy is still running.
```

**Comment by DragonDriver** [comment]
Already fixed in #13180 . Feel free to reopen this if any similar issue occurs.
