### ISSUE TITLE
[Enhancement]: Clean up the tso package

### ISSUE THREAD

**Issue by rleungx** [milvus-io/milvus#13124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Remove some unnecessary functions and variables in package tso.

**Comment by xiaofan-luan** [comment]
hi rleungx, guess SetLimitMaxLogic may want to be used in the future? any reason why you want to remove this part of code?

**Comment by rleungx** [comment]
> hi rleungx, guess SetLimitMaxLogic may want to be used in the future? any reason why you want to remove this part of code?

No special reason, just make some cleanups. If you do need `SetLimitMaxLogic`, I'm going to keep it. ^_^

**Comment by xiaofan-luan** [comment]
> 

Not sure if we want to use it or not in the future, so probably we can just keep the logic there in advance? Others looks good to me. @czs007 could you please take a look at this issue see you have any comments? 

sees that we are not trying to reset timestamp so other part lgtm

**Comment by xiaofan-luan** [comment]
@rleungx hi rleungx, are we still work on this issue?
