### ISSUE TITLE
Search failed using CPU-version with index created by GPU-version

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#1318]
**Describe the bug**
Search failed with error message: invalid top-k
```
19:52:36  2020-02-22:11:52:36,254 INFO     [k8s_runner.py:194] Search nprobe: 32
19:52:37  2020-02-22:11:52:37,230 INFO     [runner.py:175] Start query, query params: top-k: 1, nq: 1, actually length of vectors: 1
19:52:37  2020-02-22:11:52:37,230 INFO     [runner.py:177] Start run query, run 1 of 2
19:52:37  2020-02-22:11:52:37,232 ERROR    [client.py:71] Invalid topk: 0. The topk must be within the range of 1 ~ 2048.
19:52:37  2020-02-22:11:52:37,232 INFO     [client.py:33] Milvus query run in 0.0s
```
**Steps/Code to reproduce behavior**
Index created with using GPU-version, then search with CPU-version, status returned not ok

**Expected behavior**

**Environment details**
branch: crud
dataset: sift-50m-l2
index_type: ivf_sq8

**Screenshots**

**Additional context**

**Comment by BossZou** [comment]
Hey, The branch crud has changed the proto: Remove `data_range` param in API `Search` and `SearchInfiles`, the search API has changed. However, the pymilvus SDK is always keeping with milvus on master branch.
