### ISSUE TITLE
[Bug]: querynode doesn't release memory after call release

### ISSUE THREAD

**Issue by JamCrash** [milvus-io/milvus#13214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: rc8
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![企业微信截图_1639212643407](https://user-images.githubusercontent.com/39126346/145670600-6778d009-c472-413d-8127-d2d7257ef598.png)
![企业微信截图_16392127347232](https://user-images.githubusercontent.com/39126346/145670636-7c927557-3314-4433-9b15-ec5066c1c021.png)

and the memory distribution is imbalanced

even after call drop, the memory is not released

**Comment by yanliang567** [comment]
@JamCrash this is a known issue. We did some improvement in master, could you please retry with the latest master build?
/assign @JamCrash 
/unassign

**Comment by JamCrash** [comment]
but I'm use the latest master build two days ago

**Comment by JamCrash** [comment]
milvusdb/milvus-dev:master-latest

**Comment by xiaofan-luan** [comment]
https://github.com/milvus-io/milvus/issues/12218 and https://github.com/milvus-io/milvus/issues/12585 might be the similar issues we are tracking

**Comment by xiaofan-luan** [comment]
There are a few things we are working on:
1) change go settings to release memory from go to the system
2) investigate memory allocator why the memory is not returned

**Comment by xiaofan-luan** [comment]
I'm still investigating on this~

**Comment by xiaofan-luan** [comment]
related to #12585

**Comment by JamCrash** [comment]
No update or reproduction since then, close this issue for now
