### ISSUE TITLE
"core_regression" is a better name for workflow "core"

### ISSUE THREAD

**Issue by cxie** [milvus-io/milvus#1322]
**Describe the bug**
"core" is not a good name for Milvus regression 

**Expected behavior**
suggest to rename to "core_regression"

**Environment details**
- workfow/core.yaml

**Comment by cxie** [comment]
@ZhifengZhang-CN

**Comment by ZhifengZhang-CN** [comment]
@cxie suggest to rename to "cpp"

refer to  [arrow workflows](https://github.com/apache/arrow/tree/master/.github/workflows)

**Comment by cxie** [comment]
Is there a plan to move CPU regressions to GitHub Action?

**Comment by ZhifengZhang-CN** [comment]
No plan. Because CPU regressions consumes hardware resources and takes a long time to execute in github Action  @cxie

**Comment by cxie** [comment]
Do You mean even CPU regressions are too time-consuming to running on Action?

**Comment by ZhifengZhang-CN** [comment]
@cxie Just like you said
