### ISSUE TITLE
[Bug]:  querynode load occur error: Failed to get last message id from broker. While the pulsar runs well

### ISSUE THREAD

**Issue by JamCrash** [milvus-io/milvus#13246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-rc8-dev-lastest 
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

qeurynode log: [container (10).log](https://github.com/milvus-io/milvus/files/7700908/container.10.log)

**Comment by xige-16** [comment]
It seems that pulsar is not well, Is there a pulsar log？

**Comment by JackLCL** [comment]
@JamCrash

**Comment by JamCrash** [comment]
Not reproduce, close this issue
