### ISSUE TITLE
[Enhancement]: Speed up estimating segment memory size

### ISSUE THREAD

**Issue by czs007** [milvus-io/milvus#13262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

DataCoord records the memory size of each BinLog file and provides an interface to obtain the segment memory size.

### Why is this needed?

DataCoord records the size of each Binglog file, thereby avoiding multiple IO requests to parse the Binglog header file, which can speed up.

**Comment by congqixia** [comment]
/unassign @czs007 
/assign
working on it

**Comment by congqixia** [comment]
Note that: this will make GA version incompatible with RC8 or earlier if no conversion is applied
