### ISSUE TITLE
[Enhancement]: proto field naming is not by convention

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#13267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Change the proto message field to snake case.

### Why is this needed?

According to [Google proto style guide](https://developers.google.com/protocol-buffers/docs/style), the message field shall be in snake case (underscore connected string). While currently the field name has snake and camel case at the same time.

**Comment by czs007** [comment]
Golint requires an ID.
The rules of go's proto are as follows：
a_ID -> A_ID
b_id -> BId
c_Id -> C_Id
abcID -> AbcID

Therefore, if you want to pass golint, as long as there is an ID,  you must use abcID in the camel case style in the proto file.

**Comment by congqixia** [comment]
> Golint requires abreivation of Identify as ID. The rules of go's proto are as follows： a_ID -> A_ID b_id -> BId c_Id -> C_Id abcID -> AbcID
> 
> Therefore, if you want to pass golint, as long as there is an ID, you must use abcID in the camel case style in the proto file.

we can by-pass generated *.pb.go files lint check

**Comment by czs007** [comment]
> 

Not only in pb files.
If the variables defined in pb are used in an external go file, the file is affected by the golint check.

**Comment by congqixia** [comment]
> > > Golint requires abreivation of Identify as ID. The rules of go's proto are as follows： a_ID -> A_ID b_id -> BId c_Id -> C_Id abcID -> AbcID
> > > Therefore, if you want to pass golint, as long as there is an ID, you must use abcID in the camel case style in the proto file.
> > 
> > 
> > we can by-pass generated *.pb.go files lint check
> 
> Not only in pb files. If the variables defined in pb are used in an external go file, the file is affected by the golint check.

It won't. Just tested by changing `segmentID` to `segment_id`, in a request def (to reduce impact). Neither `golint` nor `revive` reported any issue about using generated `segmentId` field
