### ISSUE TITLE
[Enhancement]: Speed up load operation

### ISSUE THREAD

**Issue by czs007** [milvus-io/milvus#13264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

The current load operation is too slow.
There are two main reasons: the operation of evaluating the memory size of the file is too slow and loading the file serially.

- [ ] Speed up estimating segment's memory size #13262 
- [ ] Let QueryNode load Segment Binlog files in parallel #13263

### Why is this needed?

Speed ​​is important.

**Comment by thecooltechguy** [comment]
I'm currently using Milvus 2.0-rc8 with ~100M 256-dimensional vectors, and it would definitely be extremely helpful if the load operation's speed can be much faster, since it currently takes a long time.

**Comment by xiaofan-luan** [comment]
@[divyanshugit](https://github.com/divyanshugit)

**Comment by xiaofan-luan** [comment]
assign @divyanshugit

**Comment by divyanshugit** [comment]
Can you assign this issue to me?

**Comment by ss892714028** [comment]
Load is even slower with high dimensional vectors: https://github.com/milvus-io/milvus/issues/15736
