### ISSUE TITLE
fix severe code issues reported by codebeat

### ISSUE THREAD

**Issue by cxie** [milvus-io/milvus#1327]
**Describe the bug**
Codebeat reported a number of code issues of Milvus.

**Steps/Code to reproduce behavior**
For more details, see https://codebeat.co/projects/github-com-milvus-io-milvus-master

**Expected behavior**
All code issues scored below B should be fixed. Let's improve Milvus code quality!

**Comment by JinHai-CN** [comment]
I found lots of 'bad' codes are coming from thirdparty. I will exclude those files.
