### ISSUE TITLE
[Bug]: Insert hangs in parallel when milvus has two proxy replicas

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#13294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 1cba259
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc9.dev22
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: proxy.replicas: 2
```

### Current Behavior

1. Deploy milvus with 2 proxy replicas
2. Connect milvus and create an collection
3. Insert 100 entities in parallel and hangs
```
[2021/12/13 11:59:09.648 +00:00] [DEBUG] [impl.go:610] ["DescribeCollection done"] [traceID=5adb0f4c405a69e] [role=proxy] [MsgID=429758021457674244] [BeginTS=4297580215363174    41] [EndTS=429758021536317441] [db=] [collection=proxy_scale_o1lBzH9T]
230 [2021/12/13 11:59:09.652 +00:00] [ERROR] [grpclog.go:55] ["[transport]transport: http2Server.HandleStreams received an illegal stream id: 9"] [stack="google.golang.org/grpc/i    nternal/grpclog.ErrorDepth\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/internal/grpclog/grpclog.go:55\ngoogle.golang.org/grpc/grpclog.(*componentData).ErrorDepth\n\t/go/pkg    /mod/google.golang.org/grpc@v1.38.0/grpclog/component.go:46\ngoogle.golang.org/grpc/grpclog.(*componentData).Errorf\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/grpclog/comp    onent.go:79\ngoogle.golang.org/grpc/internal/transport.(*http2Server).operateHeaders\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/internal/transport/http2_server.go:380\ngoo    gle.golang.org/grpc/internal/transport.(*http2Server).HandleStreams\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/internal/transport/http2_server.go:507\ngoogle.golang.org/gr    pc.(*Server).serveStreams\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:918\ngoogle.golang.org/grpc.(*Server).handleRawConn.func1\n\t/go/pkg/mod/google.golang.org/g    rpc@v1.38.0/server.go:868"]
```
[proxy_dfpq8.log](https://github.com/milvus-io/milvus/files/7703636/proxy_dfpq8.log)
[proxy_dxtmc.log](https://github.com/milvus-io/milvus/files/7703637/proxy_dxtmc.log)

### Expected Behavior

Insert successfully

### Steps To Reproduce

```markdown
       host = "10.98.0.7"
        c_name = cf.gen_unique_str(prefix)
        # connect
        connections.add_connection(default={"host": host, "port": 19530})
        connections.connect(alias='default')

        # create
        collection_w = ApiCollectionWrapper()
        collection_w.init_collection(name=c_name, schema=cf.gen_default_collection_schema())

        def do_insert():
            log.debug(f'current pid {os.getpid()}')
            df = cf.gen_default_dataframe_data(nb=100)
            collection_w.insert(df)
            log.debug(collection_w.num_entities)

        process_list = []
        for i in range(5):  # 5 processes to insert in parallel
            p = multiprocessing.Process(target=do_insert, args=())  # new process instance
            p.start()
            process_list.append(p)

        for p in process_list:
            p.join()

        log.info('test finished')
```
```


### Anything else?

_No response_

**Comment by yanliang567** [comment]
/assign @congqixia 
@congqixia could you please take a look at this issue?
/unassign

**Comment by congqixia** [comment]
@yanliang567 , ok, working on it. Can we have the log from the datacoord and datanode(s)?

**Comment by yanliang567** [comment]
@ThreadDao 

> @yanliang567 , ok, working on it. Can we have the log from the datacoord and datanode(s)?

**Comment by czs007** [comment]
@congqixia @ThreadDao 
may not be the problem of milvus.
Python multi-process can not copy the shared connections.

**Comment by congqixia** [comment]
@czs007 just checked log from proxy_dfpq8.log
```
[2021/12/13 11:59:09.652 +00:00] [ERROR] [grpclog.go:55] ["[transport]transport: http2Server.HandleStreams received an illegal stream id: 9"] [stack="google.golang.org/grpc/internal/grpclog.ErrorDepth\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/internal/grpclog/grpclog.go:55\ngoogle.golang.org/grpc/grpclog.(*componentData).ErrorDepth\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/grpclog/component.go:46\ngoogle.golang.org/grpc/grpclog.(*componentData).Errorf\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/grpclog/component.go:79\ngoogle.golang.org/grpc/internal/transport.(*http2Server).operateHeaders\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/internal/transport/http2_server.go:380\ngoogle.golang.org/grpc/internal/transport.(*http2Server).HandleStreams\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/internal/transport/http2_server.go:507\ngoogle.golang.org/grpc.(*Server).serveStreams\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:918\ngoogle.golang.org/grpc.(*Server).handleRawConn.func1\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:868"]
[2021/12/13 11:59:09.652 +00:00] [INFO] [grpclog.go:37] ["[transport]transport: loopyWriter.run returning. connection error: desc = \"transport is closing\""]
[2021/12/13 11:59:09.652 +00:00] [WARN] [grpclog.go:46] ["[transport]transport: http2Server.HandleStreams failed to read frame: read tcp 10.97.19.18:19530->10.97.0.0:43512: use of closed network connection"]
```
I think your theory might be correct.

**Comment by congqixia** [comment]
@ThreadDao could you please verify the test script?
/unassign
/assign @ThreadDao

**Comment by ThreadDao** [comment]
/unassign
/assign @czs007 
@congqixia I create connections in each process and insert successfully. But it's wrong to hang anyway. I lowered the priority of the issue.

**Comment by ThreadDao** [comment]
After removing connection, call `has_partition` in parallel hangs 
1. connect in the main process
2. create a collection
3. remove connect
4. start a process to call `has_partition`
5. expected to get an exception: should connect first, but hangs

**Comment by ThreadDao** [comment]
While starting multi-process to create the same collection, the exception will be thrown:
```
<BaseException: (code=1, message=CreateCollection failed: meta table add collection failed,error = collection ccc exist)>
```
While creating the same collection just in main process, no exception will be thrown

**Comment by yanliang567** [comment]
/assign @congqixia 
could you please take a look again @congqixia

**Comment by congqixia** [comment]
> While starting multi-process to create the same collection, the exception will be thrown:
> 
> ```
> <BaseException: (code=1, message=CreateCollection failed: meta table add collection failed,error = collection ccc exist)>
> ```
> 
> While creating the same collection just in main process, no exception will be thrown

@ThreadDao @yanliang567 I think this is the designed behavior. As two user create a collection with same Collection name, only one shall succeed and the other one shall fail with error message like "Collection already exist".

**Comment by ThreadDao** [comment]
@congqixia I think this is acceptable. I’m just saying here that I just want to explain this inconsistency.

**Comment by ThreadDao** [comment]
> After removing connection, call `has_partition` in parallel hangs
> 
> 1. connect in the main process
> 2. create a collection
> 3. remove connect
> 4. start a process to call `has_partition`
> 5. expected to get an exception: should connect first, but hangs

@yanliang567 Do you think this is a problem

**Comment by yanliang567** [comment]
@congqixia, @ThreadDao   I think it is acceptable to get an error, while hanging is not acceptable.
