### ISSUE TITLE
[Bug]: First search latency is much larger than normal situation after re-starting Milvus

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#13318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 835e098
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc8
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

After re-starting, the first search latency is much larger, about **76s**!
![image](https://user-images.githubusercontent.com/12268675/145922106-bbd3c3ed-be32-4819-adfb-8fccddbc42b8.png)

### Expected Behavior

search latency is normal, like about 0.4s

### Steps To Reproduce

```markdown
run actions https://github.com/milvus-io/milvus/actions/workflows/deploy-test.yaml
```

### Anything else?

Log 
https://github.com/milvus-io/milvus/suites/4643986274/artifacts/125963910

**Comment by yanliang567** [comment]
I guess it is because that it was still loading when 1st search issued.
@xige-16 could you please double confirm about it?
/assign @xige-16 
/unassign

**Comment by xiaofan-luan** [comment]
It take some time to recover. but why the recover only happens on first search? 
I guess it should happen as soon as the cluster recover

**Comment by xige-16** [comment]
pr #13682 should has optimized this situation

**Comment by xige-16** [comment]
Could you rerun and see the effect? @zhuwenxing

**Comment by zhuwenxing** [comment]
In job https://github.com/milvus-io/milvus/runs/4695212124?check_suite_focus=true, the issue still exists.
![image](https://user-images.githubusercontent.com/12268675/148018282-59b8dbc5-2c67-4a44-bc96-d10047398547.png)


Log:
https://github.com/milvus-io/milvus/suites/4820545417/artifacts/135956330

**Comment by xige-16** [comment]
sdk retry search req after search timeout(20s)，didn't succeed until the fifth time，So the first successful search took 90s
```
def retry_on_rpc_failure(retry_times=10, wait=1, retry_on_deadline=True):
    def wrapper(func):
        @functools.wraps(func)
        def handler(self, *args, **kwargs):
            counter = 1
            while True:
                try:
                    return func(self, *args, **kwargs)
                except grpc.RpcError as e:
                    # DEADLINE_EXCEEDED means that the task wat not completed
                    # UNAVAILABLE means that the service is not reachable currently
                    # Reference: https://grpc.github.io/grpc/python/grpc.html#grpc-status-code
                    if e.code() != grpc.StatusCode.DEADLINE_EXCEEDED and e.code() != grpc.StatusCode.UNAVAILABLE:
                        raise e
                    if not retry_on_deadline and e.code() == grpc.StatusCode.DEADLINE_EXCEEDED:
                        raise e
                    if counter >= retry_times:
                        if e.code() == grpc.StatusCode.DEADLINE_EXCEEDED:
                            raise BaseException(1, "rpc timeout")
                        raise e
                    time.sleep(wait)
                    self._update_connection_pool()
                except Exception as e:
                    raise e
                finally:
                    counter += 1

        return handler

    return wrapper
```

**Comment by xige-16** [comment]
Querynode did not recover well when the search was retried, and the search timeout was in line with expectations

**Comment by xige-16** [comment]
> sdk retry search req after search timeout(20s)，didn't succeed until the fifth time，So the first successful search took 90s
> 
> ```
> def retry_on_rpc_failure(retry_times=10, wait=1, retry_on_deadline=True):
>     def wrapper(func):
>         @functools.wraps(func)
>         def handler(self, *args, **kwargs):
>             counter = 1
>             while True:
>                 try:
>                     return func(self, *args, **kwargs)
>                 except grpc.RpcError as e:
>                     # DEADLINE_EXCEEDED means that the task wat not completed
>                     # UNAVAILABLE means that the service is not reachable currently
>                     # Reference: https://grpc.github.io/grpc/python/grpc.html#grpc-status-code
>                     if e.code() != grpc.StatusCode.DEADLINE_EXCEEDED and e.code() != grpc.StatusCode.UNAVAILABLE:
>                         raise e
>                     if not retry_on_deadline and e.code() == grpc.StatusCode.DEADLINE_EXCEEDED:
>                         raise e
>                     if counter >= retry_times:
>                         if e.code() == grpc.StatusCode.DEADLINE_EXCEEDED:
>                             raise BaseException(1, "rpc timeout")
>                         raise e
>                     time.sleep(wait)
>                     self._update_connection_pool()
>                 except Exception as e:
>                     raise e
>                 finally:
>                     counter += 1
> 
>         return handler
> 
>     return wrapper
> ```

And the interval between sdk client retry search is equal to timeout, which is wrong.

**Comment by xige-16** [comment]
https://github.com/milvus-io/pymilvus/pull/853 has remove the logic of retry search
