### ISSUE TITLE
[Bug]: DeleteCollection of rootcoord meta table is not atomic and transactional

### ISSUE THREAD

**Issue by DragonDriver** [milvus-io/milvus#13341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```golang
// DeleteCollection delete collection
func (mt *MetaTable) DeleteCollection(collID typeutil.UniqueID, ts typeutil.Timestamp, ddOpStr string) error {
	mt.ddLock.Lock()
	defer mt.ddLock.Unlock()

	collMeta, ok := mt.collID2Meta[collID]
	if !ok {
		return fmt.Errorf("can't find collection. id = %d", collID)
	}

	delete(mt.collID2Meta, collID)
	delete(mt.collName2ID, collMeta.Schema.Name)

	// update segID2IndexMeta
	for partID := range collMeta.PartitionIDs {
		if segIDMap, ok := mt.partID2SegID[typeutil.UniqueID(partID)]; ok {
			for segID := range segIDMap {
				delete(mt.segID2IndexMeta, segID)
			}
		}
	}

	// update partID2SegID
	for partID := range collMeta.PartitionIDs {
		delete(mt.partID2SegID, typeutil.UniqueID(partID))
	}

	for _, idxInfo := range collMeta.FieldIndexes {
		_, ok := mt.indexID2Meta[idxInfo.IndexID]
		if !ok {
			log.Warn("index id not exist", zap.Int64("index id", idxInfo.IndexID))
			continue
		}
		delete(mt.indexID2Meta, idxInfo.IndexID)
	}
	var aliases []string
	// delete collection aliases
	for alias, cid := range mt.collAlias2ID {
		if cid == collID {
			aliases = append(aliases, alias)
		}
	}

	delMetakeysSnap := []string{
		fmt.Sprintf("%s/%d", CollectionMetaPrefix, collID),
	}
	delMetaKeysTxn := []string{
		fmt.Sprintf("%s/%d", SegmentIndexMetaPrefix, collID),
		fmt.Sprintf("%s/%d", IndexMetaPrefix, collID),
	}

	for _, alias := range aliases {
		delete(mt.collAlias2ID, alias)
		delMetakeysSnap = append(delMetakeysSnap,
			fmt.Sprintf("%s/%s", CollectionAliasMetaPrefix, alias),
		)
	}

	// save ddOpStr into etcd
	var saveMeta = map[string]string{
		DDMsgSendPrefix:   "false",
		DDOperationPrefix: ddOpStr,
	}

	err := mt.snapshot.MultiSaveAndRemoveWithPrefix(map[string]string{}, delMetakeysSnap, ts)
	if err != nil {
		log.Error("SnapShotKV MultiSaveAndRemoveWithPrefix fail", zap.Error(err))
		panic("SnapShotKV MultiSaveAndRemoveWithPrefix fail")
	}
	err = mt.txn.MultiSaveAndRemoveWithPrefix(saveMeta, delMetaKeysTxn)
	if err != nil {
		log.Warn("TxnKV MultiSaveAndRemoveWithPrefix fail", zap.Error(err))
		//Txn kv fail will no panic here, treated as garbage
	}

	return nil
}
```

When we drop a collection, rootcoord will clean the meta in etcd. According to the above code, rootcoord will split the clean job into two stages:
- 1, `mt.snapshot.MultiSaveAndRemoveWithPrefix(map[string]string{}, delMetakeysSnap, ts)`
- 2, `mt.txn.MultiSaveAndRemoveWithPrefix(saveMeta, delMetaKeysTxn)`

These two stages both depend on transaction KV. So only one of them will be atomic and transactional. Taking 1 stage as example, all the kv of `delMetakeysSnap` should be removed or all the kv should not be removed. But the combination of these two stages is not atomic and transactional. For example, when there are some issues with `ETCD`(the transaction KV we depend on now), the stage 1 may succeed, but the stage 2 may fail. In other words, we may leave the `delMetaKeysTxn` in the `ETCD` but remove the `delMetakeysSnap`. So when rootcoord recovered from failure, it tried to re-send the `delMetaKeysTxn` dd-msg leaved in the `ETCD`, but actually the related meta of this operation has been removed, then rootcoord will raise an exception such as "cannot find collection ...".

### Expected Behavior

`DeleteCollection` should be atomic and transactional.

**Comment by DragonDriver** [comment]
Related: https://github.com/milvus-io/milvus/issues/12951

**Comment by congqixia** [comment]
@DragonDriver the reason why `Delete` is split into 2 staged is for issue #10233.(Make all clean up into one atomic operation will lead to ETCD error!) We can assume the Collection is dropped after the the `SnapShotKV` operation. Yes, the txn kv clean up might fail in some cases. All we need is a background cleaner to clean up these mess

**Comment by DragonDriver** [comment]
@congqixia Got it. In my opinion, when rootcoord recover from failures, `drop collection` should always succeed whether the meta exists or not. How do you think about it?

**Comment by congqixia** [comment]
> @congqixia Got it. In my opinion, when rootcoord recover from failures, `drop collection` should always succeed whether the meta exists or not. How do you think about it?

@DragonDriver `RootCoord` will save last unfinished DDL (including `Drop Collection`) in etcd. If it crashed during the execution progress, rootcoord will retry the same operation.
I think the issue you mentioned is related to service idempotence, which is undefined so far.

**Comment by DragonDriver** [comment]
@congqixia Sorry, I made a mistake. Actually this issue won't cause #12951. But due to this issue, we need a garbage cleaner in the background to clean up all the useless meta.

**Comment by DragonDriver** [comment]
Closed since this issue won't introduce in-consistency into Milvus. Just like @congqixia said, all we need to do is a background cleaner to clean up the useless meta.
