### ISSUE TITLE
prometheus的rules文件无法下载

### ISSUE THREAD

**Issue by LmYjQ** [milvus-io/milvus#135]
wget -P rules https://raw.githubusercontent.com/milvus-io/docs/master/assets/monitoring/alerts.rules.yml 这个文件下载不到，可以再提供一份吗？

**Comment by jielinxu** [comment]
Yes, the file name alerts.rules.yml is not correct here. Please use https://raw.githubusercontent.com/milvus-io/docs/master/assets/monitoring/alert.rules.yml instead.

**Comment by LmYjQ** [comment]
> Yes, the file name alerts.rules.yml is not correct here. Please use https://raw.githubusercontent.com/milvus-io/docs/master/assets/monitoring/alert.rules.yml instead.

这个貌似还是不行，需要科学上网吗？

**Comment by jielinxu** [comment]
It should work cause the path is correct now.

**Comment by jielinxu** [comment]
Fixed in documentation.
