### ISSUE TITLE
[Enhancement]: Initialize the random number seed at the unified entrance

### ISSUE THREAD

**Issue by czs007** [milvus-io/milvus#13505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

In the main function, uniformly initialize the random number seed.

In addition, the random number seed is initialized in the TestMain method of each unit test module.

### Why is this needed?

Milvus widely uses the package `rand` that comes with go. The `rand` package comes with a global variable globalSeed.
 If rand.Seed is not called, the generator behaves as if seeded by Seed(1).

If 1 is always used as the seed, then each process will generate the same random number sequence, or after the process dies and is recreated, it will  generate the same sequence as before.

This is a hidden risk in the system. We should avoid it.

**Comment by xiaofan-luan** [comment]
close this issue, we should rely on random for channel name creation
