### ISSUE TITLE
Remove stdout message "Bloom filter Error"

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#1351]
**Describe the bug**
docker logs:
```
Bloom filter Error: you have added the same id more than 15 times!
Bloom filter Error: you have added the same id more than 15 times!
Bloom filter Error: you have added the same id more than 15 times!
Bloom filter Error: you have added the same id more than 15 times!
Bloom filter Error: you have added the same id more than 15 times!
Bloom filter Error: you have added the same id more than 15 times!
Bloom filter Error: you have added the same id more than 15 times!
```
**Steps/Code to reproduce behavior**

**Expected behavior**

**Environment details**
pymilvus-test: 0.2.57
```
Welcome to Milvus!
Milvus Release version: v0.7.0, built at 2020-02-24 11:35.09, with OpenBLAS library.
You are using Milvus CPU edition
Last commit id: 4b4467be824b136a0fe2aa7bb59feb9ec4061589
```

**Screenshots**

**Additional context**

**Comment by youny626** [comment]
Now if the bloom filter counter has been incremented more than 15 times, flush will return error.

**Comment by del-zhenwu** [comment]
not really work, still return ok

**Comment by youny626** [comment]
This is due to auto flush.
Or if WAL is enabled, flush is executed asynchronously, so it'll always return Status::OK.
Error log will refect that flush has failed, and you won't be able to add any more duplicate ids.

**Comment by del-zhenwu** [comment]
close since it have been fixed
