### ISSUE TITLE
[Bug]:  milvus only receives requests, but does not actually process them

### ISSUE THREAD

**Issue by suifengmangbu** [milvus-io/milvus#13521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:1.1.1
- Deployment mode(standalone or cluster):standalone 
- SDK version(e.g. pymilvus v2.0.0rc2):milvus-sdk-java 1.1.0
- OS(Ubuntu or CentOS): CentOS 7.5
- CPU/Memory: 32C 96G
- GPU: NONE
- Others:
```

### Current Behavior

Call search request，After running for about 1 month, it will appear only receives requests, but does not actually process them

### Expected Behavior

Able to process requests normally

### Steps To Reproduce

```markdown
1、server_config.xml
cluster:
  enable: false
  role: rw
general:
  timezone: UTC+8
  meta_uri: mysql://*****@*****:3306/milvus_db
storage:
  path: /var/lib/milvus
  auto_flush_interval: 1
wal:
  enable: true
  recovery_error_ignore: false
  buffer_size: 256MB
  path: /var/lib/milvus/wal
cache:
  cache_size: 8GB
  insert_buffer_size: 1GB
  preload_collection: '*'
gpu:
  enable: false
  cache_size: 1GB
  gpu_search_threshold: 1000
  search_devices:
    - gpu0
  build_index_devices:
    - gpu0
fpga:
   enable: false
   search_devices:
     - fpga0
logs:
  level: debug
  trace.enable: true
  path: /var/lib/milvus/logs
  max_log_file_size: 1024MB
  log_rotate_num: 0
  log_to_stdout: false
  log_to_file: true
metric:
  enable: false
  address: 127.0.0.1
  port: 9091

engine_config:
  search_combine_nq: 1


2、search request info
------collection info----------
dimension：512
indexFileSize：512MB
metricType：MetricType.L2
nlist:64
Collection size：20000+
--------request param--------
vector:1
topK:100
nprobe:64
Concurrency：10/s
```

### Anything else?

1、watch info log
After 01:01:16 on December 16, 2021, only appear “search begin” , but no appear "search end" log 
2、watch debug log，The last line of log is：“[2021-12-16 01:01:16,541][DEBUG][SERVER][PrintTimeRecord][taskexecutor_th] [search][0] DoSearch file id:25: totally cost (0.018760 second [18.760158 ms])”
Subsequent requests did not print any logs
3、watch trace log
The last line of log is：“[2021-12-16 01:01:16,541][TRACE][ENGINE][SuspendIfFirst][reqsched_thread] live_search_num_: 1”
Subsequent requests did not print any log

[trace.log](https://github.com/milvus-io/milvus/files/7725707/trace.log)
[debug.log](https://github.com/milvus-io/milvus/files/7725709/debug.log)
[info.log](https://github.com/milvus-io/milvus/files/7725713/info.log)

**Comment by yanliang567** [comment]
/assign @yhmo 
@yhmo could you please help on this issue

/unassign

**Comment by yhmo** [comment]
@suifengmangbu 
From the log it seems no problem. Each search request cost 20 ~ 30ms.
Some questions:
1. is any content in the error.log?
2. how many search requests per minute?

**Comment by suifengmangbu** [comment]
1、is any content in the error.log?error.log has no error information
2、

**Comment by suifengmangbu** [comment]
1、error.log has no error information
2、6-10 search requests per second
3、the problem is :   After 01:01:16 on December 16, 2021，new search request not processed

Previously uploaded “debug.log” was not uploaded completely. I'll upload it again
[debug.log](https://github.com/milvus-io/milvus/files/7752121/debug.log)

watch info.log，not printed " ****** Search end"
watch debug log，no actual processing log，only "milvus generate request_id: **********"
watch trace.log，Subsequent requests did not print any logs

**Comment by yhmo** [comment]
Did you try other interface after it hang? such as ShowCollections(), Flush()

Any other action in client side? For example, some clients insert/delete vectors, some clients search.

**Comment by suifengmangbu** [comment]
because it has been applied to the online system as a service，after it hang，no time to try other interface，Recover first by restarting the Milvus service

in addition，The problem occurred at 1:00 in zero，At that time, there were only search requests, no other requests

We use Java SDK，and set withtimeout to 10 seconds，after it hang，The request timed out and returned

**Comment by yhmo** [comment]
From the log I could not get a conclusion. Seems the job scheduler suddenly blocked. but I didn't found any clue why it stopped.
Let's keep an eye on it.
