### ISSUE TITLE
[Bug]: querycoord ut timeout in github action

### ISSUE THREAD

**Issue by DragonDriver** [milvus-io/milvus#13559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://github.com/milvus-io/milvus/runs/4547601762?check_suite_focus=true

### Expected Behavior

querycoord ut works fine.

**Comment by DragonDriver** [comment]
According to the log, it seems that `LoadPartitions` was not done. So querycoord spent a lot of time to wait for `LoadPartitions` to be done.

**Comment by DragonDriver** [comment]
Tring to reproduce this on my local pc.

**Comment by xiaofan-luan** [comment]
TestWatchNodeLoop/Test_OfflineNodes
Seems to be this case in QueryCoord

**Comment by DragonDriver** [comment]
> TestWatchNodeLoop/Test_OfflineNodes Seems to be this case in QueryCoord

The scheduler loop didn't exit in this case, blocked in `scheduler.wg.Wait`.
