### ISSUE TITLE
[Bug]: The milvus cluster doesn't response at all after 23 days running.

### ISSUE THREAD

**Issue by austinjung** [milvus-io/milvus#13553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.0.0-rc8
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): v2.0.0rc8
- OS(Ubuntu or CentOS): Ubuntu 18.04.5 LTS (Bionic Beaver)
- CPU/Memory: 16 of Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz/64G
- GPU: No GPU
- Others:
```

### Current Behavior

After 23 days of running, the milvus server doesn't respond. It seemed to be hanged.
**This is error logs of milvus-datanode**
[error_logs_of_milvus-datanode.txt](https://github.com/milvus-io/milvus/files/7729971/error_logs_of_milvus-datanode.txt)

**Comment by austinjung** [comment]
If you need more logs from milvus cluster pods, please let me know. We just left the milvus server as it is.

**Comment by LoveEachDay** [comment]
According to  the datanode pod log: `Not enough non-faulty bookies available`, please check whether the pulsar bookkeeper pods and pulsar broker pods are all running.  And provide the pulsar broker log.
/unassign

**Comment by yanliang567** [comment]
@austinjung please check as suggested above

**Comment by austinjung** [comment]
I can see pulsar bookkeeper and pulsar broker pods are running.
(ciitizen-document-classification-service) ajung-MD6M:projects austinjung$ dev get pods | grep milvus
milvus-datacoord-5ff7677564-ms2zm                                 1/1     Running             0          21h
milvus-datanode-68849748c9-t2xh6                                  1/1     Running             1          21h
milvus-etcd-0                                                     1/1     Running             0          21h
milvus-etcd-1                                                     1/1     Running             0          23d
milvus-etcd-2                                                     1/1     Running             0          23d
milvus-indexcoord-599d4dbd57-bp9nw                                1/1     Running             0          21h
milvus-indexnode-b5485b44b-sl8w2                                  1/1     Running             0          21h
milvus-minio-0                                                    1/1     Running             0          21h
milvus-minio-1                                                    1/1     Running             0          21h
milvus-minio-2                                                    1/1     Running             0          23d
milvus-minio-3                                                    1/1     Running             0          23d
milvus-proxy-796667cc74-zdh46                                     1/1     Running             1          21h
milvus-pulsar-autorecovery-5f9dd8ccfb-4rln2                       1/1     Running             0          23d
milvus-pulsar-bastion-66b6859994-fjk2t                            1/1     Running             0          21h
milvus-pulsar-bookkeeper-0                                        1/1     Running             0          23d
milvus-pulsar-bookkeeper-1                                        1/1     Running             0          21h
milvus-pulsar-broker-76b6b99f8d-8qrrw                             1/1     Running             2          23d
milvus-pulsar-proxy-596fcc94d4-5k9q2                              2/2     Running             0          23d
milvus-pulsar-zookeeper-0                                         1/1     Running             0          21h
milvus-pulsar-zookeeper-1                                         1/1     Running             0          23d
milvus-pulsar-zookeeper-2                                         1/1     Running             0          23d
milvus-querycoord-544c9f8cf8-jj9f9                                1/1     Running             0          21h
milvus-querynode-5856dd788-7blcs                                  1/1     Running             0          21h
milvus-querynode-5856dd788-l72h5                                  1/1     Running             0          21h
milvus-rootcoord-6b6f88ffbd-5fssv                                 1/1     Running             0          21h

**Comment by austinjung** [comment]
Here is pulsar broker logs.
[Uploading milvus_pulsar_broker.log…]()

**Comment by austinjung** [comment]
![Uploading Screen Shot 2021-12-16 at 5.58.47 PM.png…]()

**Comment by austinjung** [comment]
`(ciitizen-document-classification-service) ajung-MD6M:projects austinjung$ dev get pods | grep milvus
milvus-datacoord-5ff7677564-ms2zm                                 1/1     Running             0          21h
milvus-datanode-68849748c9-t2xh6                                  1/1     Running             1          21h
milvus-etcd-0                                                     1/1     Running             0          21h
milvus-etcd-1                                                     1/1     Running             0          23d
milvus-etcd-2                                                     1/1     Running             0          23d
milvus-indexcoord-599d4dbd57-bp9nw                                1/1     Running             0          21h
milvus-indexnode-b5485b44b-sl8w2                                  1/1     Running             0          21h
milvus-minio-0                                                    1/1     Running             0          21h
milvus-minio-1                                                    1/1     Running             0          21h
milvus-minio-2                                                    1/1     Running             0          23d
milvus-minio-3                                                    1/1     Running             0          23d
milvus-proxy-796667cc74-zdh46                                     1/1     Running             1          21h
milvus-pulsar-autorecovery-5f9dd8ccfb-4rln2                       1/1     Running             0          23d
milvus-pulsar-bastion-66b6859994-fjk2t                            1/1     Running             0          21h
milvus-pulsar-bookkeeper-0                                        1/1     Running             0          23d
milvus-pulsar-bookkeeper-1                                        1/1     Running             0          21h
milvus-pulsar-broker-76b6b99f8d-8qrrw                             1/1     Running             2          23d
milvus-pulsar-proxy-596fcc94d4-5k9q2                              2/2     Running             0          23d
milvus-pulsar-zookeeper-0                                         1/1     Running             0          21h
milvus-pulsar-zookeeper-1                                         1/1     Running             0          23d
milvus-pulsar-zookeeper-2                                         1/1     Running             0          23d
milvus-querycoord-544c9f8cf8-jj9f9                                1/1     Running             0          21h
milvus-querynode-5856dd788-7blcs                                  1/1     Running             0          21h
milvus-querynode-5856dd788-l72h5                                  1/1     Running             0          21h
milvus-rootcoord-6b6f88ffbd-5fssv                                 1/1     Running             0          21h
(`

**Comment by austinjung** [comment]
```
(ciitizen-document-classification-service) ajung-MD6M:projects austinjung$ dev get pods | grep milvus
milvus-datacoord-5ff7677564-ms2zm                                 1/1     Running             0          21h
milvus-datanode-68849748c9-t2xh6                                  1/1     Running             1          21h
milvus-etcd-0                                                     1/1     Running             0          21h
milvus-etcd-1                                                     1/1     Running             0          23d
milvus-etcd-2                                                     1/1     Running             0          23d
milvus-indexcoord-599d4dbd57-bp9nw                                1/1     Running             0          21h
milvus-indexnode-b5485b44b-sl8w2                                  1/1     Running             0          21h
milvus-minio-0                                                    1/1     Running             0          21h
milvus-minio-1                                                    1/1     Running             0          21h
milvus-minio-2                                                    1/1     Running             0          23d
milvus-minio-3                                                    1/1     Running             0          23d
milvus-proxy-796667cc74-zdh46                                     1/1     Running             1          21h
milvus-pulsar-autorecovery-5f9dd8ccfb-4rln2                       1/1     Running             0          23d
milvus-pulsar-bastion-66b6859994-fjk2t                            1/1     Running             0          21h
milvus-pulsar-bookkeeper-0                                        1/1     Running             0          23d
milvus-pulsar-bookkeeper-1                                        1/1     Running             0          21h
milvus-pulsar-broker-76b6b99f8d-8qrrw                             1/1     Running             2          23d
milvus-pulsar-proxy-596fcc94d4-5k9q2                              2/2     Running             0          23d
milvus-pulsar-zookeeper-0                                         1/1     Running             0          21h
milvus-pulsar-zookeeper-1                                         1/1     Running             0          23d
milvus-pulsar-zookeeper-2                                         1/1     Running             0          23d
milvus-querycoord-544c9f8cf8-jj9f9                                1/1     Running             0          21h
milvus-querynode-5856dd788-7blcs                                  1/1     Running             0          21h
milvus-querynode-5856dd788-l72h5                                  1/1     Running             0          21h
milvus-rootcoord-6b6f88ffbd-5fssv                                 1/1     Running             0          21h
```

**Comment by yanliang567** [comment]
@LoveEachDay

**Comment by LoveEachDay** [comment]
> Here is pulsar broker logs. Uploading milvus_pulsar_broker.log…

We cannot download the broker log from your comment. And you can see the `pulsar broker` pods are restarting 2 times.

**Comment by JackLCL** [comment]
> Here is pulsar broker logs. Uploading milvus_pulsar_broker.log…

@austinjung  
This log was not successfully uploaded. Can you re-upload it?

**Comment by austinjung** [comment]
Here I uploaded again pulsar broker logs. If you still have an issue to download, please provide me an email account. I'll send the logs file through email. Thanks.
[error_logs_of_milvus-datanode.txt](https://github.com/milvus-io/milvus/files/7747035/error_logs_of_milvus-datanode.txt)

**Comment by austinjung** [comment]
And these are pods status as of now.
```
(ciitizen-document-classification-service) ajung-MD6M:projects austinjung$ dev get pods | grep milvus
milvus-datacoord-5ff7677564-ms2zm                                 1/1     Running             0          4d13h
milvus-datanode-68849748c9-t2xh6                                  1/1     Running             1          4d13h
milvus-etcd-0                                                     1/1     Running             0          4d13h
milvus-etcd-1                                                     1/1     Running             0          27d
milvus-etcd-2                                                     1/1     Running             0          27d
milvus-indexcoord-599d4dbd57-bp9nw                                1/1     Running             0          4d13h
milvus-indexnode-b5485b44b-sl8w2                                  1/1     Running             0          4d13h
milvus-minio-0                                                    1/1     Running             0          4d13h
milvus-minio-1                                                    1/1     Running             0          4d13h
milvus-minio-2                                                    1/1     Running             0          27d
milvus-minio-3                                                    1/1     Running             0          27d
milvus-proxy-796667cc74-zdh46                                     1/1     Running             1          4d13h
milvus-pulsar-autorecovery-5f9dd8ccfb-4rln2                       1/1     Running             0          27d
milvus-pulsar-bastion-66b6859994-fjk2t                            1/1     Running             0          4d13h
milvus-pulsar-bookkeeper-0                                        1/1     Running             0          3d13h
milvus-pulsar-bookkeeper-1                                        1/1     Running             0          4d13h
milvus-pulsar-broker-76b6b99f8d-8qrrw                             1/1     Running             4          27d
milvus-pulsar-proxy-596fcc94d4-f226q                              2/2     Running             0          3d13h
milvus-pulsar-zookeeper-0                                         1/1     Running             0          4d13h
milvus-pulsar-zookeeper-1                                         1/1     Running             0          3d13h
milvus-pulsar-zookeeper-2                                         1/1     Running             0          27d
milvus-querycoord-544c9f8cf8-jj9f9                                1/1     Running             0          4d13h
milvus-querynode-5856dd788-7blcs                                  1/1     Running             0          4d13h
milvus-querynode-5856dd788-l72h5                                  1/1     Running             0          4d13h
milvus-rootcoord-6b6f88ffbd-5fssv                                 1/1     Running             0          4d13h
```

**Comment by austinjung** [comment]
And this is the last logs of pulsar broker.
dev logs milvus-pulsar-broker-76b6b99f8d-8qrrw -p > pulsar_logs_with_last_crash.log
[pulsar_logs_with_last_crash.log](https://github.com/milvus-io/milvus/files/7747068/pulsar_logs_with_last_crash.log)

**Comment by yanliang567** [comment]
@LoveEachDay

**Comment by LoveEachDay** [comment]
How do you deploy the milvus cluster? By milvus-helm chart?
Originally, the milvus-helm chart only deploys two bookkeeper pods, if any of the bookkeeper pods is down, the broker will not work, yelling `Not enough non-faulty bookies available`. 
We upgrade this bookkeeper pods from 2 to 3 in milvus-helm version 2.4.6. You can follow the below procedures to upgrade milvus cluster:
```
helm repo add milvus https://milvus-io.github.io/milvus-helm/
helm repo update
helm upgrade <release-name> milvus/milvus
```

By the way, from the pod status clip above, some pods are running 27 days, while other running 4d or 3d. Does your kubernetes cluster healthy?

**Comment by austinjung** [comment]
@LoveEachDay We've deployed again with milvus-helm version 2.4.6. And we'll monitor. Is there any API endpoint to check the healthy of the milvus cluster?
If not, please guide us how we can check the healthy of the milvus cluster efficiently.
Thanks.
