### ISSUE TITLE
[Bug]: RootCoord, Failed to new MetaSnapshot

### ISSUE THREAD

**Issue by hf185** [milvus-io/milvus#13558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.0.0-rc6-20210910-020f109
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS7.9
- CPU/Memory: CPU
- GPU: 
- Others:
```

### Current Behavior

使用docker运行在2*4的CentOS服务器上，32G运行内存，运行一段时间后，自动exit了，再重启就报错：RootCoord, Failed to new MetaSnapshot

### Expected Behavior

正常重启并运行

**Comment by yanliang567** [comment]
@hf185 could you please upload the milvus logs for investigation?
/assign @hf185 
/unassign

**Comment by hf185** [comment]
> @hf185 could you please upload the milvus logs for investigation? /assign @hf185 /unassign

https://github.com/hf185/file/blob/main/milvusdb.log

**Comment by congqixia** [comment]
@xiaofan-luan @hf185 
Just checked log and information provided. The standalone instance used RC6 version image, which has bug about etcd version compacted caused issue. 
This known issue was fixed in later RC versions.
@xiaofan-luan do we have any migration guide from RC6 to latest image?

**Comment by xiaofan-luan** [comment]
> 

I don't think we can support upgrade or migrate from RC6 to GA. 
But this might be a big issue though

**Comment by xiaofan-luan** [comment]
Please let me know if anyone already put RC version on your production environment, we will see what we can do! Sorry about that

**Comment by hf185** [comment]
> 

GA版本现在已经发布了吗?

**Comment by ss892714028** [comment]
> > 
> 
> GA版本现在已经发布了吗?

Not yet, there will be a pre-GA release version in the coming week.

**Comment by hf185** [comment]
我想从rc6升级到rc8可以在不影响旧数据的情况下直接升吗?

**Comment by hf185** [comment]
> 

获取有什么办法能把数据从RC6内导出，然后再导入到RC8呢？

**Comment by hf185** [comment]
> 我想从rc6升级到rc8可以在不影响旧数据的情况下直接升吗?

或者有什么办法能从RC6导出数据，然后在RC8再导入呢？

**Comment by yanliang567** [comment]
> > 我想从rc6升级到rc8可以在不影响旧数据的情况下直接升吗?
> 
> 或者有什么办法能从RC6导出数据，然后在RC8再导入呢？

Sorry, you have to deploy a rc8 milvus and re-insert the data:(

**Comment by hf185** [comment]
> 
> Sorry, you have to deploy a rc8 milvus and re-insert the data:(

ok, thank you.
