### ISSUE TITLE
[Bug]: Molecular Formula Search Demo load smi file error

### ISSUE THREAD

**Issue by DingQK** [milvus-io/milvus#13594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.0.0
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): v2.0.0-rc8
- OS(Ubuntu or CentOS): windows
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I use the quick_deploy for molecular_similarity_search (bootcamp/solutions/molecular_similarity_search/quick_deploy/) and deploy it using Docker Compose according to the guide. And I have experience the following problem:

- When I try to add the "path/to/your/data" (I have tried relative paths, absolute paths), none of which seems to work. 
 
It might be my problem of not knowing the right format for path, but I am wondering if the document can be more specific. I am a supporter for milvus and I really want to contribute. If the problem is found, I volunteer to improve the description in the document. Thank you so much!

### Expected Behavior

In localhost:***

When I type in the path/to/your/data and click "+", smi files can be added.

### Steps To Reproduce

```markdown
1. Start Docker Engine and start quick_deploy
2. Open localhost:***
3. Type in the "path/to/your/data" and click "+"
```

**Comment by LoveEachDay** [comment]
docker-compose has mounted the `../smiles-data` directory into the `molesearch-webserver` container as `/mols_data`. If you want to add more data into `molesearch-webserver`, you have to copy the data into the project directory `solutions/molecular_similarity_search/smiles-data`. 

Then you can add formula via `/smiles-data/<your-data>` as full path.

**Comment by DingQK** [comment]
Thank you for your answer!
