### ISSUE TITLE
Different Timings

### ISSUE THREAD

**Issue by gavrin-s** [milvus-io/milvus#1363]
Is it normal that when I run the same code I get different timings?
Index length = 500 000, index type = FLAT, metric type = IP
In first case 
| query batch size | timings mean, s | timings std, s | timings median, s |
| --- | --- | --- | --- |
| 10 | 0.19401 | 0.12312 | 0.16154 |
| 30 | 0.49903 | 0.10678 | 0.47989 |
| 50 | 1.42037 | 0.31866 | 1.44652 |
| 80 | 2.61397 | 0.25698 | 2.63259 |
| 100 | 3.28944 | 0.27262 | 3.34388 |

In second case
| query batch size | timings mean, s | timings std, s | timings median, s |
| --- | --- | --- | --- |
| 10 | 0.18884 | 0.10530 | 0.16197 |
| 30 | 0.52789 | 0.10549 | 0.51917 |
| 50 | 0.98995 | 0.24204 | 0.91517 |
| 80 | 1.65593 | 0.35347 | 1.57605 |
| 100 |1.98007 | 0.41942 | 1.90255 |

**Comment by JinHai-CN** [comment]
Is there any different between two cases?
Hardware? test data? searching/index parameters?

**Comment by gavrin-s** [comment]
I use cpu version. Vector dim = 512, float 32, nlist = 2048, nprobe = 16.
* hardware: Intel i7-7700 (8 cores)
* software: python 3.6.9, pymilvus==0.2.7

**Comment by JinHai-CN** [comment]
Is there any difference between case1 and case2?

**Comment by gavrin-s** [comment]
Only timings)

**Comment by JinHai-CN** [comment]
Milvus is a CPU-bound software, any active process might influence Milvus performance a little. Therefore, there always have some differences even the query are totally same. But in your case, we found the difference might be a little bit 'big'. We will test it and try to reproduce it. Any found we will let you know.
