### ISSUE TITLE
[Bug]: 由于生产上线需要，修改milvus 1.1.1中mysql元数据管理单元默认创建的"Tables"、"TableFiles"、"Fields"和"Environment" 表格式遇到问题

### ISSUE THREAD

**Issue by liujie3948** [milvus-io/milvus#13684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

由于公司生产上线合规的需要，需要使用公司自己的mysql数据库提前创建好各个表，且每个表有一个标准的数据字段格式。因此需要修改milvus 1.1.1中使用mysql作为元数据管理单元默认创建的"Tables"、"TableFiles"、"Fields"和"Environment" 该4个表格式，我们提前在公司的数据库里面创建好该4个表的各个字段，我们只是在milvus原始表格式字段后面增加了4个新的字段，新增的字段我们直接赋默认值。现在启动milvus 是没有问题，但是使用pymilvus 1.1.2调用milvus的时候会出现下面的问题。
ERROR | grpc_handler.py | create_collectiion | 307 error_code: META_FAILED
reason: "Failed to create collection:Column count doesn't match value count at row 1

**Comment by yanliang567** [comment]
/assign @yhmo 
@yhmo cloud you please help on it?
/unassign

**Comment by liujie3948** [comment]
补充：python代码跟踪到是在create_collection函数里面就出错了。

**Comment by liujie3948** [comment]
![IMG_20211219_171340](https://user-images.githubusercontent.com/17978325/146670818-c0db6c95-8fe2-44fb-a8f3-d928bcc1832f.jpg)
这是我们公司要求的table格式，只需要增加后面4个字段

**Comment by xiaofan-luan** [comment]
please use English for the convenience of non-chinese speakers, thanks

**Comment by JackLCL** [comment]
This problem has been solved by modifying Milvus source code.
