### ISSUE TITLE
[Bug]: milvus_server  cpu useage stays high

### ISSUE THREAD

**Issue by shenjianzch** [milvus-io/milvus#13719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:0.10.6
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):0.4.0
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 2核/8G
- GPU: 
- Others:
```

### Current Behavior

为什么我重启了docker的milvus:0.10.6-cpu-d022221-64ddc2镜像 cpu 一直是跑满的，是因为再加载什么东西吗？暂时向量值数量是317061

- [ ] 

### Expected Behavior

重启

**Comment by xiaofan-luan** [comment]
please use English for the convenience of non-chinese speakers, thanks

**Comment by yanliang567** [comment]
@shenjianzch if you have loaded some collections, if could be reloading after reboot. please wait more time.
/assign @shenjianzch 
/unassign

**Comment by shenjianzch** [comment]
> @shenjianzch if you have loaded some collections, if could be reloading after reboot. please wait more time. /assign @shenjianzch /unassign

ok thanks,i see
