### ISSUE TITLE
求spark写入milvus demo

### ISSUE THREAD

**Issue by Jie-Yuan** [milvus-io/milvus#1375]
求spark写入milvus demo

**Comment by BossZou** [comment]
Hello,  can you describe the requirements in detail ?

**Comment by Jie-Yuan** [comment]
spark生成向量导入milvus创建索引，会方便些

**Comment by Jie-Yuan** [comment]
> spark

最好是支持spark dataframe

**Comment by JinHai-CN** [comment]
We might provide a demo to show how to integrate milvus with Spark, but not now. Milvus already has JAVA SDK: https://github.com/milvus-io/milvus-sdk-java, which can be used in Spark.
