### ISSUE TITLE
[Bug]: Server crash automatically !!!

### ISSUE THREAD

**Issue by STAROFWIND** [milvus-io/milvus#13795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus v2.0.0rc8
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 128G
- GPU: 
- Others:
```

### Current Behavior

I installed Milvus by using docker-compose like the guide: https://milvus.io/docs/v2.0.0/install_standalone-docker.md
I run the server and got successfully like this:
![image](https://user-images.githubusercontent.com/53179529/146750736-aa039604-3eab-4fca-98c3-9226f6f6c19a.png)

But after about 1 minute, The server turns off without any my operation.
![image](https://user-images.githubusercontent.com/53179529/146750807-de0527bb-c526-4025-96b9-03b7ae3b94cb.png)

I only see my Memory increases to ~15G / 128G. Does It relate to "volumes" ?. 

### Steps To Reproduce

```markdown
I installed and run successfully sometimes, But accidentally, until now, the server crash when I start it
```

**Comment by yanliang567** [comment]
@STAROFWIND could you please upload the milvus logs for investigation?
/assign @STAROFWIND 
/unassign

**Comment by STAROFWIND** [comment]
This is all about what issue I am encountering. I just run docker-compose up -d and after a minute or more, milvus standalone disconnect (exit 2).

**Comment by Theodoric008** [comment]
same issue for me, i have to reinstall the whole container

**Comment by STAROFWIND** [comment]
> same issue for me, i have to reinstall the whole container

I am still stuck here, I reinstalled the container but still get the error. Are you successful ?

**Comment by DingQK** [comment]
@STAROFWIND  I installed milvus using the same guide and environment but did not encounter this problem. Perhaps you can check the log output (first set log configurations according to https://milvus.io/docs/v2.0.0/configuration_standalone-basic.md#Log-Configurations) and find out more about your problem. I am also a user and hopefully this can help.

**Comment by yanliang567** [comment]
@DingQK Thanks for you reply, this is helpful for us to address the issue.
@STAROFWIND @Theodoric008 Could you please help to retry and upload the logs if it still reproduces to you? We have to investigate the logs before giving any suggestions?

/assign @Theodoric008

**Comment by STAROFWIND** [comment]
Thank you for your reply ! But actually, there is no log here, I just run "docker-compose up -d" , i don't run anything on the client side.

**Comment by STAROFWIND** [comment]
Hi @DingQK, Thank you for you support. 
This line in the milvus.yaml is what you mean. But also there is nothing. My problem simply: start server (docker-compose up -d ) and it turns off automatically without any trace. 
I still wonder about exceeding disk space in volumes ( 20G for default) ? 
Or how can I clear all and try to reinstall at the beginning ? 
Or I must use lower version 1.1 ( I really don't want to do this, because you said you don't get the error like me) 
Thank you

**Comment by yanliang567** [comment]
@LoveEachDay

**Comment by LoveEachDay** [comment]
@STAROFWIND You can run `docker logs milvus-standalone` to fetch the log from the container.

**Comment by xiaofan-luan** [comment]
any progress on this one guys?

**Comment by Theodoric008** [comment]
> 

no, just keep restarting...

**Comment by xiaofan-luan** [comment]
> > 
> 
> no, just keep restarting...

Hi @Theodoric008 ,any logs for the server so we can take a investigation on that?

**Comment by qianchen94** [comment]
I just met the same problem, did anyone know how to solve it?

**Comment by STAROFWIND** [comment]
I have no idea to solve this. Restart, reinstall and even try on another
physical system, all of these fail !

Vào 17:06, T.4, 9 Th3, 2022 qianchen94 ***@***.***> đã viết:

**Comment by qianchen94** [comment]
>I just change v 2.0.1 to v 2.0.0 on the same physical system, it turns normal... ...

**Comment by qianchen94** [comment]
I solve this problem by restarting the docker, and I changed the volume path in the docker-compose.yml， It goes normal.

**Comment by LoveEachDay** [comment]
You can get the log of the milvus container using the following command:
`docker logs -f milvus-standalone`

> I solve this problem by restarting the docker, and I changed the volume path in the docker-compose.yml， It goes normal.

By default, we use the current working directory which contains the `docker-compose.yml` to save volumes. And the data in the volumes persisted, if you running `docker-compose up -d` several times, the metadata may be messed up.

**Comment by abaybektursun** [comment]
Same here, the standalone version seems to crash every time I query it with this code:
```python
from pymilvus import connections, db, Collection,  CollectionSchema, FieldSchema, DataType, utility 

conn = connections.connect(host="127.0.0.1", port=19530)

db.list_database()
collection_name = 'upwork_summaries'

collection.load()
print(collection)
```

**Comment by xiaofan-luan** [comment]
> Same here, the standalone version seems to crash every time I query it with this code:
> 
> ```python
> from pymilvus import connections, db, Collection,  CollectionSchema, FieldSchema, DataType, utility 
> 
> conn = connections.connect(host="127.0.0.1", port=19530)
> 
> db.list_database()
> collection_name = 'upwork_summaries'
> 
> collection.load()
> print(collection)
> ```
> 
> Server-side error:
> 
> ```
> panic: execution failed
> 
> goroutine 1005 [running]:
> github.com/milvus-io/milvus/internal/datanode.flushNotifyFunc.func1(0xc004b33450)
> 	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:761 +0x157a
> github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).waitFinish(0xc0034b60c0, 0xc00101b740, 0xc0025dd430)
> 	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:204 +0xdb
> created by github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).init.func1
> 	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:121 +0xf1
> ```

is there any log related?
Seems that flush failed due to some reason, maybe due to lack of S3 authorization

**Comment by xiaofan-luan** [comment]
"Resource requested is unreadable, please reduce your request rat"

For some reason, you seems to hit the rate limitation of minio. You probably want to check why minio hit rate limit.
Possible reasons: 1) with many partitions/collections
2) calling flush manually causing too many small files.
3) other exceptions on mInio

**Comment by abaybektursun** [comment]
> > Same here, the standalone version seems to crash every time I query it with this code:
> > ```python
> > from pymilvus import connections, db, Collection,  CollectionSchema, FieldSchema, DataType, utility 
> > 
> > conn = connections.connect(host="127.0.0.1", port=19530)
> > 
> > db.list_database()
> > collection_name = 'upwork_summaries'
> > 
> > collection.load()
> > print(collection)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Server-side error:
> > ```
> > panic: execution failed
> > 
> > goroutine 1005 [running]:
> > github.com/milvus-io/milvus/internal/datanode.flushNotifyFunc.func1(0xc004b33450)
> > 	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:761 +0x157a
> > github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).waitFinish(0xc0034b60c0, 0xc00101b740, 0xc0025dd430)
> > 	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:204 +0xdb
> > created by github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).init.func1
> > 	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:121 +0xf1
> > ```
> 
> is there any log related? Seems that flush failed due to some reason, maybe due to lack of S3 authorization

My bad! Looks like my hard drive was just full

**Comment by Snaiel** [comment]
> "Resource requested is unreadable, please reduce your request rat"
> 
> For some reason, you seems to hit the rate limitation of minio. You probably want to check why minio hit rate limit. Possible reasons: 1) with many partitions/collections 2) calling flush manually causing too many small files. 3) other exceptions on mInio

minio was constantly reporting a file access error. Doing `sudo docker compose up -d` instead of `docker compose up -d` solves the issue of standalone exiting.

Apologies if this is going off-topic, but I now realise that from the install instructions Milvus is started from super user. I'm now unable to see the container in Docker Desktop since the context of `sudo docker compose up -d` is `default` while `docker compose up -d` is `desktop-linux` and doing `sudo docker context ls` only shows `default`.

Should we be able to see Milvus in Docker Desktop?
