### ISSUE TITLE
Update RESTful API doc for new/changed interfaces in 0.7.0

### ISSUE THREAD

**Issue by yamasite** [milvus-io/milvus#1380]
## Report needed documentation

**Report needed documentation**
https://github.com/milvus-io/milvus/blob/master/core/src/server/web_impl/README.md

**Describe the documentation you'd like**
Update RESTful API for new/changed interfaces in 0.7.0.

**Comment by BossZou** [comment]
Hello, I'm updating the restful API, once I finish it, i will inform you the latest API.
