### ISSUE TITLE
Error when server restarts during compact

### ISSUE THREAD

**Issue by sahuang** [milvus-io/milvus#1385]
**Describe the bug**
During compact, if server restarts, number of vectors in table will not act as expected.

**Steps/Code to reproduce behavior**
Steps: 
1. Add 600,000 vectors to table, flush
2. Delete first 1000 vectors, flush
3. Compact; during compact, stop and restart server
4. Get table row count and compare with 600,000

**Results**
Depending on the time to stop server, table row count is different. 
All results are greater than 600,000 (e.g. 743384) and this will not be changed even after compact again when server restarts.

```python
(Pdb) status, info = connect.table_info(table)
(Pdb) info.partitions_stat[0].count
743384
(Pdb) status = connect.compact(table)
(Pdb) status = connect.flush([table])
(Pdb) status, info = connect.table_info(table)
(Pdb) info.partitions_stat[0].count
743384
```

**Environment details**
crud, wal enabled, latest server container
Last commit id: 03da4381c7a4a957e4bf63559d15d8fef9054926

**Comment by yhmo** [comment]
Not able to reproduce by compiled milvus

**Comment by sahuang** [comment]
Cannot be reproduced. Close for now.
