### ISSUE TITLE
[Bug]: Failed to build milvus image with latest version

### ISSUE THREAD

**Issue by codersky** [milvus-io/milvus#13852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

 => [openblas 1/1] FROM docker.io/milvusdb/openblas:ubuntu18.04-20210428@sha256:3ba9394eaa453095fd7fa8ae6fbda414f977a55262b60f01941c1a0ff00245e6                                  0.0s
 => ERROR https://github.com/krallin/tini/releases/download/v0.19.0/tini                                                                                                         75.8s
 => CACHED [stage-1  2/10] RUN apt-get update &&     apt-get install -y --no-install-recommends libtbb-dev gfortran netcat iputils-ping &&     apt-get remove --purge -y &&       0.0s
 => CACHED [stage-1  3/10] COPY --from=openblas /usr/lib/libopenblas-r0.3.9.so /usr/lib/                                                                                          0.0s
 => CACHED [stage-1  4/10] RUN ln -s /usr/lib/libopenblas-r0.3.9.so /usr/lib/libopenblas.so.0 &&     ln -s /usr/lib/libopenblas.so.0 /usr/lib/libopenblas.so                      0.0s
 => CACHED [stage-1  5/10] COPY ./bin/ /milvus/bin/                                                                                                                               0.0s
 => CACHED [stage-1  6/10] COPY ./configs/ /milvus/configs/                                                                                                                       0.0s
 => CACHED [stage-1  7/10] COPY ./lib/ /milvus/lib/                                                                                                                               0.0s
------
 > https://github.com/krallin/tini/releases/download/v0.19.0/tini:
------
failed to load cache key: Get "https://github.com/krallin/tini/releases/download/v0.19.0/tini": Service Unavailable

### Expected Behavior

succeed to build milvus image

### Steps To Reproduce

```markdown
1. download latest version of milvus from github.
2. execute ./build/build_image.sh
```

### Anything else?

nope

**Comment by yanliang567** [comment]
/assign @LoveEachDay 
@LoveEachDay could you please hlep on it

**Comment by LoveEachDay** [comment]
This is a network issue. You need set proxy for docker to download the `tini`.
To build milvus image, follow the below procedures:
```
1. git clone https://github.com/milvus-io/milvus.git
2. cd milvus
3. ./build/builder.sh make install
4. ./build/build_image.sh
5. docker images to check the newly build image
```

/unassign

**Comment by codersky** [comment]
my bad, fixed it after set the proxy env var
