### ISSUE TITLE
[Enhancement]: Distinguish stopping state and stopped state

### ISSUE THREAD

**Issue by DragonDriver** [milvus-io/milvus#13933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

For now, when we're going to stop a component, we will set the state code of component to be `Abnormal`. Under this situation, any gRPC requests entered the component will be refused. However, it will also result in that the `healthz` check returns `unhealthy`, which will cause the component to be killed by the kubelet automatically. If we'll release some important resources in `stop`, being killed too earlier will lead to some resources leak. On the contray, if we set the `Abnormal` after the `stop` was done, component cannot reject the entered gRPC requests which should not be processed.

So I want to add two state to distinguish the `stopping` state and the `stopped` state.

### Why is this needed?

Improve the stability of Milvus.

**Comment by xiaofan-luan** [comment]
keep it for tracking.
We will also need to carefully design init state and health state
