### ISSUE TITLE
[Enhancement]: Enable PProf in milvus

### ISSUE THREAD

**Issue by czs007** [milvus-io/milvus#13978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

I would like to enable pprof server in milvus.

Package pprof serves via its HTTP server runtime profiling data in the format expected by the pprof visualization tool.

The package is typically only imported for the side effect of registering its HTTP handlers. The handled paths all begin with /debug/pprof/.

![image](https://user-images.githubusercontent.com/59249785/147056676-174f428b-6bdb-45db-9cff-aedb0ea8bfb3.png)

### Why is this needed?

we can take a look at heap profile, cpu profile and trace data through pprof.

Use the pprof tool to look at the heap profile:
`go tool pprof http://localhost:9091/debug/pprof/heap`

Or to look at a 30-second CPU profile:
`go tool pprof http://localhost:9091/debug/pprof/profile?seconds=30`

To collect a 5-second execution trace:
`wget -O trace.out http://localhost:9091/debug/pprof/trace?seconds=5`
`go tool trace trace.out`

**Comment by wondermen** [comment]
/debug/pprof is not open with metrics port。 but open it in product enviroment has security problem。could add some env to controll if shoud open pprof,and if opened, it only could be access in local

**Comment by wondermen** [comment]
/debug/pprof is now open with metrics port。 but open it in product enviroment has security problem。could add some env to controll if shoud open pprof,and if opened, it only could be access in local
