### ISSUE TITLE
[Bug]: RocksMQ Reader didn't handle any exception from rocksdb.

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#14121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

currently rocksmq_reader didn't handle errors from rocksdb.
should check Iter.err() when calling seek, next and hasNext()
otherwise the behaviour is unknown

**Comment by yanliang567** [comment]
/assign @xiaofan-luan 
@xiaofan-luan are you going to fix it yourself? :)
/unassign

**Comment by xiaofan-luan** [comment]
it should be fixed after refactoring of rocksmq, close for now
