### ISSUE TITLE
core/conf/demo/server_config.yaml is not updated in the crud branch

### ISSUE THREAD

**Issue by yamasite** [milvus-io/milvus#1416]
**Describe the bug**
https://github.com/milvus-io/milvus/blob/crud/core/conf/demo/server_config.yaml is not updated. Users may not be able to successfully run Milvus after downloading this config file.

**Expected behavior**
New parameters for Milvus 0.7.0 must be added to match the template files.

**Comment by cydrain** [comment]
duplicate to #1432
