### ISSUE TITLE
[Enhancement]: Provide PRM package

### ISSUE THREAD

**Issue by haorenfsa** [milvus-io/milvus#14163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

- [x] Add spec for Build RPM 
- [ ] Auto build rpm & add to release assets when release.

### Why is this needed?

Easier installation on centos or other linux release that supports RPM installation.

**Comment by xiaofan-luan** [comment]
do we instruction about how to use it?

**Comment by haorenfsa** [comment]
> do we instruction about how to use it?

Yes, it's in  https://milvus.io/docs/v2.0.0/install_standalone-aptyum.md#Install-Milvus-with-YUM-on-CentOS

If you want to build rpm on your own, you can use `make rpm` under centos development environment

**Comment by xiaofan-luan** [comment]
Great! I will try on my docker environment
