### ISSUE TITLE
Failed to connect milvus in multi-processes

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#1417]
**Steps/Code to reproduce behavior**

from multiprocessing import Process

            milvus_1 = Milvus()
            status = milvus_1.connect(host="127.0.0.1", port=19530)
            print("client 1 connected", status)
            def test_connect():
                milvus_2 = Milvus()
                print("client 2 created")
                try:
                    status = milvus_2.connect(host="127.0.0.1", port=19530)
                    print("client 2 connected", status)
                except Exception as e:
                    print("exception: ", e)

            p = Process(target=test_connect)
            p.start()
            p.join()

Failed to connect milvus in process "p".

**Comment by BossZou** [comment]
Hello, I tried on my host machine, and the output is here:
```
client 1 connected Status(code=0, message='Success')
client 2 created
E0228 18:15:32.645537819   21399 ev_epoll1_linux.cc:822]     assertion failed: gpr_atm_no_barrier_load(&g_active_poller) != (gpr_atm)worker

Process finished with exit code 0
```
[Here](https://milvus.io/docs/v0.6.0/faq/operational_faq.md#Why-does-my-multiprocessing-program-fail) can be found how to use milvus client in the case of multiprocessing
