### ISSUE TITLE
[Bug]: database space exceeded

### ISSUE THREAD

**Issue by hf185** [milvus-io/milvus#14195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2): v2.0.0-rc8-20211104-d1f4106
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/43991218/147340378-c50a6601-96fb-4e39-b899-c8ae79a39398.png)

**Comment by hf185** [comment]
启动不了了，我现在应该怎么做才能解决这个问题，很急！！！！

**Comment by hf185** [comment]
@yanliang567 麻烦帮忙看看

**Comment by yanliang567** [comment]
it seems that the etcd is full,  @LoveEachDay is there any way to fix it except reinstall

**Comment by LoveEachDay** [comment]
@hf185 You can login to the container or pod to run the following command:
`etcdctl defrag` 

If you have multiple members of etcd, you need pass the endpoints for `etcdctl defrag` command.
You can refer the documentation [here](https://etcd.io/docs/v3.2/op-guide/maintenance/#defragmentation).

By the way, could you provide more information about your cluster? By default, we set the database quota to 4GB and enable auto compaction by revision, which can handle 1billion data scale. Do you change the default settings for etcd? Or your data scale exceeds 1billion?

**Comment by hf185** [comment]
> @hf185您可以登录到容器或 Pod 以运行以下命令： `etcdctl defrag`
> 
> 如果您有 etcd 的多个成员，则需要传递命令的终结点。您可以[参考文档 请点击此处。.](https://etcd.io/docs/v3.2/op-guide/maintenance/#defragmentation)`etcdctl defrag`
> 
> 顺便说一句，您能提供有关集群的更多信息吗？默认情况下，我们将数据库配额设置为 4GB，并启用自动压缩修订版，可以处理 10 亿次数据规模。是否更改 etcd 的默认设置？或者您的数据规模超过 10 亿？

The configuration I use is : [docker-compose.yml](https://github.com/milvus-io/milvus/releases/download/v2.0.0-rc8/milvus-cluster-docker-compose.yml)

The amount of data is still in the millions but the concurrency of inserts is higher

The QPS was around 30-50

@LoveEachDay
