### ISSUE TITLE
auto_flush_interval check failed

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#1421]
**Describe the bug**
auto_flush_interval set 
`100000000000`

```
Milvus Release version: v0.7.0, built at 2020-02-28 10:01.35, with OpenBLAS library.
You are using Milvus CPU edition
Last commit id: b67aaa2a6ee68fea54995ae33c9d548ed29fecd2

Loading configuration from: ../conf/server_config.yaml
Initializing log config from: ../conf/log_config.conf
Milvus server exit...
Config check fail: Invalid db configuration auto_flush_interval: 1e+11. Possible reason: db.auto_flush_interval is not a positive integer.
ERROR: Milvus server fail to load config file
```
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by shengjun1985** [comment]
auto_flush_interval is int32 now and 100000000000 caused overflow.

**Comment by del-zhenwu** [comment]
OK,  update  and fix check message if possiable

**Comment by JinHai-CN** [comment]
We need to add a value check on it.

**Comment by shengjun1985** [comment]
pr1447 modified the type of auto_flush_interval to int64
pr1468 modified the unit of auto_flush_interval to second
Please check it. Thank you.

**Comment by del-zhenwu** [comment]
fixed
