### ISSUE TITLE
[Enhancement]: Get segment size from grpc request, not from binlog/index file header

### ISSUE THREAD

**Issue by xige-16** [milvus-io/milvus#14225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

querycoord get segment size from recovery info and indexPath info which are returned by gprc call from datacoord and rootcoord.

### Why is this needed?

geting segment size from binlog/index file header  is slow relatively.

**Comment by xiaofan-luan** [comment]
keep it for tracking~
