### ISSUE TITLE
Could we disable autoflush permanently

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#1426]

**Comment by JinHai-CN** [comment]
You mean add a config to disable autoflush?

**Comment by del-zhenwu** [comment]
yes, can be set a field in config file

**Comment by JinHai-CN** [comment]
We can set autoflush to -1, to tell Milvus not use auto flush periodically. But If the cached data is larger than the cache size, it will also trigger the auto-flush mechanism.

**Comment by JinHai-CN** [comment]
I suppose @shengjun1985 is working on this feature.
