### ISSUE TITLE
[Bug]: Search result score changed

### ISSUE THREAD

**Issue by greensea** [milvus-io/milvus#14313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: docker image milvusdb/milvus-dev:master-20211222-5a29db6
- Deployment mode(standalone or cluster): docker, standalone
- SDK version(e.g. pymilvus v2.0.0rc2): golang
- OS(Ubuntu or CentOS): Debian
- CPU/Memory: Ryzen 5 2600X, 32GiB mem
- GPU: None
- Others:
```

### Current Behavior

I am doing image search, the vector dimesion is 512, using IVF_PQ index.
At the begining, I insert some vectors, then I search for an inserted image. The result seems good, I can get the image at top 1, and the score is 0.999999, this is good.
Then I continue insert vectors. After 1~2 days, I inserted 400k+ vectors. Now I try to search the image again, but the result seems abnormal. I still get the requested image at the top 1 of the result, but the score is not 0.99999. The score now is 0.77295977.
This is wired, the vectors is not changed, and I am searching the same image (with the same vectors), I should get score 0.99999 like the first time. The score should not changed over time.

### Expected Behavior

The serach score should not changed.

### Anything else?

In fact, this is not the first time I hit this issue. I also hit this issue with the previous version of milvus. At that time, I just think I am doing something wrong(like vector is not normalized). I hit this issue several times and I start to take caution at the vector process. Now I can confirm the searching vectors and the inserted vectors are the same. And I can get score near 1 at the beginning, but the score changed to 0.6~0.7 later.

**Comment by yanliang567** [comment]
@czs007  could you please help on this issue?
/assign @czs007 

/unassign

**Comment by DragonDriver** [comment]
/assign
Hi, @greensea , thanks for reporting this. Could you provide the scripts to help us to reproduce this issue?

**Comment by greensea** [comment]
@DragonDriver I'd like to provide the script to reproduce this issue, but the problem is I can't reproduce this issue easily. 
I have several millions vectors stored in MySQL, and I am import this vectors into milvus. At the beginning every search result seems good, but few days later this issue happens. Sometimes this issue happens  just 1~2 days later, but sometimes this issue happens after 4~5 days.
You can see it take several days to reproduce this issue, so it is hard to reproduce. 
Yes I can provide the vectors dataset and the importing code, but I think it still a hard way to reproduce this issue.
Is is possible I provide the milvus database, and you can just use the data to reproduce the issue? I think this way may be easier.

**Comment by DragonDriver** [comment]
@greensea I got what you mean. How about these index parameters and search parameters?

**Comment by greensea** [comment]
@DragonDriver 
The index is created with milvus-insight, the index is IVF_PQ, nlist=32, m=32, metric type is IP.
Search is done by golang, nprobe = 10, ktop = 100, just fetch `id` field. The code is below: 
```
        nprobe := 10
        ktop :=  100
	vectors = NormalizeFloat32(vectors)
	vec := entity.FloatVector(vectors)

	ctx := context.Background()
	sp, _ := entity.NewIndexIvfPQSearchParam(nprob)

	stime := time.Now()
	sr, err := c.Search(ctx, "b_face", []string{}, "", []string{"id"}, []entity.Vector{vec}, "vectors", entity.IP, ktop, sp)

        return sr
```

**Comment by DragonDriver** [comment]
@greensea maybe you can try set `nprobe` larger. For example, to check if the inserted vector exist in the collection, you can try set `nprobe=nlist` and set `ktop=1`.

**Comment by greensea** [comment]
@DragonDriver I change the nprobe to 32 and search again, but the result is same. I can get the exact image at top 1 place, but the score is not 0.999999 like before.
Then I change nprobe to 64, but still got the same result.

**Comment by DragonDriver** [comment]
/assign @cydrain 
Maybe @cydrain can help to answer your questions.

**Comment by cydrain** [comment]
Hi @greensea , this is not a real issue.
IVF_PQ index is a kind of compression index which will lose accuracy.
You getting score 0.9999 at beginning is because IVF_PQ index is not ready, Milvus uses BruteForce search instead.
When IVF_PQ index is ready, Milvus uses IVF_PQ to search, so you can only get score 0.6~0.7

If you care about the result score, you can choose other index type:
IVF_FLAT: no compression, the top 1 score must be 0.999;
IVF_SQ8: middle compression, the top 1 score should be 0.8x (I guess);

**Comment by greensea** [comment]
@cydrain I see. Thanks.
I am closing this issue.
