### ISSUE TITLE
Support S3

### ISSUE THREAD

**Issue by cydrain** [milvus-io/milvus#1434]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
CRUD support S3

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by JinHai-CN** [comment]
Move to 0.8.0.

**Comment by hoesler** [comment]
What's the status of this feature? I see that code was merged but it is not on the schedule for the next releases. A better distributed storage support like S3 would help a lot to make milvus "cloud ready".

**Comment by scsven** [comment]
Implemented, but not tested.
