### ISSUE TITLE
[Enhancement]: Remove not-used index types

### ISSUE THREAD

**Issue by cydrain** [milvus-io/milvus#14354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Suggest to remove index NSG/NGT/SPTAG, since no one use them.

**Comment by p-gebhard** [comment]
What is the reason to remove NGT, as it is among of the best performing algorithms in the ANN-benchmarks? I mean besides the argument, that nobody uses it.

**Comment by xiaofan-luan** [comment]
> What is the reason to remove NGT, as it is among of the best performing algorithms in the ANN-benchmarks? I mean besides the argument, that nobody uses it.

Hi @p-gebhard ,Since we found HNSW is well enough for most use cases, and there is rarely anyone who is using NGT as far as we know.
Did you try NGT and find it outperform HNSW?

**Comment by cydrain** [comment]
Index "SPTAG", "NGT" and "NSG" are controlled by Macro in repo "knowhere":
- KNOWHERE_SUPPORT_SPTAG
- KNOWHERE_SUPPORT_NGT
- KNOWHERE_SUPPORT_NSG
User can enable them if needed.
