### ISSUE TITLE
Internal Error when inserting too many vectors

### ISSUE THREAD

**Issue by sahuang** [milvus-io/milvus#1438]
**Describe the bug**
When inserting too many vectors into the table, server will trigger error. (Around 100,000)

**Steps/Code to reproduce behavior**
![error](https://user-images.githubusercontent.com/26035292/75601817-19d5fe80-5afa-11ea-90e8-d94b9f98f344.png)

**Expected behavior**
Vectors added

**Environment details**
- Latest crud cpu env

**Comment by JinHai-CN** [comment]
Milvus didn't limit the insert batch size. There are two ways to do this:
- Limit the number of the vectors.
- Limit the space size of the vectors.

I suggest to limit the space size of vectors to a specific value, such as 100MB.

**Comment by BossZou** [comment]
The grpc output message:
```
<_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Exception serializing request!"
	debug_error_string = "None"
>
```

**Comment by BossZou** [comment]
Protobuf has a hard limit of 2GB, So make sure size of transferred data is lower than 2GiB. More datails can find [Here](https://stackoverflow.com/questions/34128872/google-protobuf-maximum-size)

**Comment by wang11wang** [comment]
@BossZou @sahuang  How to solve this problem, I want to insert 500M x 512 dim vectors into milvus standalone
