### ISSUE TITLE
General proto api for NNS libraries

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#1448]
**Is your feature request related to a problem? Please describe.**
We need general api(create/index/search) for all NNS libraries

**Describe the solution you'd like**
Proto proposal:
```
message KeyValuePair {
    string key = 1;
    string value = 2;
}

message TableSchema {
    string table_name = 1;
    int64 dimension = 2;
    int64 index_file_size = 3;
    int32 metric_type = 4;
    repeated KeyValuePair extra_params = 5;
}

message InsertParam {
    string table_name = 1;
    repeated RowRecord row_record_array = 2;
    repeated int64 row_id_array = 3;            //optional
    string partition_tag = 4;
    repeated KeyValuePair extra_params = 5;
}

message IndexParam {
    string table_name = 1;
    int32 index_type = 2;
    repeated KeyValuePair extra_params = 3;
}

message SearchParam {
    string table_name = 1;
    repeated string partition_tag_array = 2;
    repeated RowRecord query_record_array = 3;
    int64 topk = 4;
    repeated KeyValuePair extra_params = 5;
}

message SearchInFilesParam {
    repeated string file_id_array = 1;
    SearchParam search_param = 2;
}

message SearchByIDParam {
    string table_name = 1;
    repeated string partition_tag_array = 2;
    int64 id = 3;
    int64 topk = 4;
    repeated KeyValuePair extra_params = 5;
}
```

**Comment by JinHai-CN** [comment]
Maybe TableSchema/InsertParam don't need key/value pair.

**Comment by tinkerlin** [comment]
Minimum Supported Parameters:

- IVF: [nlist, nprobe]
- IVFPQ: [nbit]
- HNSW: [search_length, out_degree, pool_size]
- HNSW: [M, ef_construct, ef]

**Comment by JinHai-CN** [comment]
@BossZou Please write down the new python APIs here.

**Comment by yhmo** [comment]
For example, IndexParam, pass extra parameters by extra_params:
key="index_param"
value="{nlist: '16384'}"

For example, SearchParam, pass extra parameters by extra_params:
key="search_param"
value="{nprobe: '32'}"

**Comment by yhmo** [comment]
For NSG, IndexParam,  pass extra parameters by extra_params:
key="index_param"
value="{search_length: '100', out_degree:'40', pool_size:'66'}"

**Comment by tinkerlin** [comment]
For HNSW, IndexParam, pass extra parameters by extra_params:
key="index_param"
value="{M: '16', ef_construct:'500'}"

For HNSW, SearchParam
key="search_param"
value = "{ef: '64'}

**Comment by BossZou** [comment]
Do we support  nested `KeyValuePair` ? Just like:
```
{
    key1: {
        key1_1: value
    }
}
```

**Comment by BossZou** [comment]
A possible suit of APIs for python SDK:
Table:
```
      create_table: (table_params)
          table_params: dict (key-value)
```
example for `table_params`:
```
{
    "table_name": milvus_demo,
    "dimension": 128,
    "index_file_size": 1024,
    "metric_type": L2
}
```


Insert:
      insert(table_name, records, ids, partition_tag, params)
          table_name: string
          records: 2-D array
          ids: list
          partition_tag: string
          params: dict (key-value)

Index:
     create_index(table_name, index_type, params)
          table_name: string
          index_type: Index enum
          params: dict (key-value)

search:
      search(table_name, query_records, topk, partition_tags, params)
          table_name: string
          query_records: 2-D array
          topk: int
          partition_tags: list of string
          params: dict (key-value)

search by id:
      search_by_id(table_name, vector_id, topk, params)
          table_name: string
          vector_id: int
          topk: int
          params: dict (key-value)

**Comment by yhmo** [comment]
Meta change:
Tables: 
    1. drop column "nlist"
    2. add column "index_params"

TableFiles: no change

**Comment by JinHai-CN** [comment]
Following parameters are mandatory for building index and searching.
IVF: [nlist, nprobe]
IVFPQ: [nbit]
NSG: [search_length, out_degree, pool_size]
HNSW: [M, ef_construct, ef]

For any parameters above missing in building index or searching. Error message is given and notify user which parameters is missing or its value is wrong.

**Comment by BossZou** [comment]
I have run my example shell successfully:
Here is mys code:
```
def main():
    milvus = Milvus()

    # Connect to Milvus server
    # You may need to change _HOST and _PORT accordingly
    param = {'host': _HOST, 'port': _PORT}
    status = milvus.connect(**param)
    if status.OK():
        print("Server connected.")
    else:
        print("Server connect fail.")
        sys.exit(1)

    # Create table demo_table if it dosen't exist.
    table_name = 'example_table'

    status, ok = milvus.has_table(table_name)
    if not ok:
        param = {
            'table_name': table_name,
            'dimension': _DIM,
            'index_file_size': _INDEX_FILE_SIZE,  # optional
            'metric_type': MetricType.L2  # optional
        }

        milvus.create_table(param, timeout=None)

    # Show tables in Milvus server
    _, tables = milvus.show_tables()

    # present table info
    _, info = milvus.table_info(table_name)
    print(info)

    # Describe demo_table
    _, table = milvus.describe_table(table_name)
    print(table)

    # 10000 vectors with 16 dimension
    # element per dimension is float32 type
    # vectors should be a 2-D array
    vectors = [[random.random() for _ in range(_DIM)] for _ in range(100000)]
    # You can also use numpy to generate random vectors:
    #     `vectors = np.random.rand(10000, 16).astype(np.float32)`

    # Insert vectors into demo_table, return status and vectors id list
    status, ids = milvus.insert(table_name=table_name, records=vectors)

    # Wait for 4 seconds, until Milvus server persist vector data.
    time.sleep(4)

    # Get demo_table row count
    status, result = milvus.count_table(table_name)

    # create index of vectors, search more rapidly
    # Create ivflat index in demo_table
    # You can search vectors without creating index. however, Creating index help to
    # search faster
    index_param = {
        "nlist": 32
    }
    status = milvus.create_index(table_name, IndexType.IVF_FLAT, index_param)
    print(status)

    # describe index, get information of index
    status, index = milvus.describe_index(table_name)
    print(index)

    # Use the top 10 vectors for similarity search
    query_vectors = vectors[0:10]

    # execute vector similarity search

    search_param = {
        "nprobe": 16
    }

    print("Searching ... ")
    status, results = milvus.search(table_name, top_k=1, query_records=query_vectors, params=search_param)

    if status.OK():
        # indicate search result
        # also use by:
        #   `results.distance_array[0][0] == 0.0 or results.id_array[0][0] == ids[0]`
        if results[0][0].distance == 0.0 or results[0][0].id == ids[0]:
            print('Query result is correct')
        else:
            print('Query result isn\'t correct')

    # print results
    print(results)

    # Delete demo_table
    status = milvus.drop_table(table_name)

    # Disconnect from Milvus
    status = milvus.disconnect()
```

@sahuang @del-zhenwu If you have any question, please let me know.

**Comment by BossZou** [comment]
Return value of API `describe_index` has changed. The latest return value is:
```
Status,
IndexParam:
   _table_name,
   _index_type,
   _params (dict)
```

**Comment by tinkerlin** [comment]
The code below is currently supported parameters and parameter names, you can find all definiation in `src/index/knowhere/index/vector_index/helpers/IndexParameter.h`

```
// IVF Params
constexpr const char* nprobe = "nprobe";
constexpr const char* nlist = "nlist";
constexpr const char* m = "m";          // support pq only
constexpr const char* nbits = "nbits";  // support pq only

// NSG Params
constexpr const char* knng = "knng";
constexpr const char* search_length = "search_length";
constexpr const char* out_degree = "out_degree";
constexpr const char* candidate = "candidate_pool_size";

// HNSW Params
constexpr const char* efConstruction = "efConstruction";
constexpr const char* M = "M";
constexpr const char* ef = "ef";

```
Further more info will be updated on the official website.

**Comment by shengjh** [comment]
For each index, can you explain  what parameters are required for creation，and what parameters are required for search separately?

**Comment by tinkerlin** [comment]
The server check parameter like this:
```
bool
IVFConfAdapter::CheckTrain(milvus::json& oricfg) {
    static int64_t MAX_NLIST = 999999;
    static int64_t MIN_NLIST = 1;

    CheckIntByRange(knowhere::IndexParams::nlist, MIN_NLIST, MAX_NLIST);
}
```
Many params are associate with **rows(the number of vector)** and other run-time value,  usually this kind of check is useless. I have to say, at this time, lt's hard to do strict parameter checks. So if you run boundary-test or random-parameter test，it may lead server crash.
 
Here I will give two sets of parameter ranges. Server check version and the Recommand version.
 
Server check params range:
- IVF/PQ/SQ: nlist [rows, 999999]
- IVF/PQ/SQ: nprobe [1,999999]
- NSG: knng [5, 300]
- NSG: search_length [10, 300]
- NSG: out_degree [5, 300]
- NSG: candidate_pool_size [50, 1000]
- HNSW: efConstruction [100, 500]
- HNSW: M [5, 48]

 
Recommend params range 

- The nlist is decided by rows. The recommend range is  [ rows/256,  rows/40]
- The nprobe [ 1, nlist ]

**Comment by tinkerlin** [comment]
The PQ m is decided by dim and have a couple of results. each result represent a kind of compress rad. I will give a simple Python code. By run this scripts, you can get all the parameter combinations. 

**upload later.**

**Comment by tinkerlin** [comment]
> The PQ m is decided by dim and have a couple of results. each result represent a kind of compress rad. I will give a simple Python code. By run this scripts, you can get all the parameter combinations.
> 
> **upload later.**

@shengjh @del-zhenwu

**Comment by yhmo** [comment]
Already implemented, will be release in 0.7.0

**Comment by yhmo** [comment]
For different index type, parameter list is different accordingly, for example:
 *       FLAT/IVFLAT/SQ8:  "{nlist: '16384'}"
 *           ///< nlist range:[1, 999999]
 *       IVFPQ:  "{nlist: '16384', m: "12"}"
 *           ///< nlist range:[1, 999999]
 *           ///< m is decided by dim and have a couple of results.
 *       NSG:  "{search_length: '45', out_degree:'50', candidate_pool_size:'300', "knng":'100'}"
 *           ///< search_length range:[10, 300]
 *           ///< out_degree range:[5, 300]
 *           ///< candidate_pool_size range:[50, 1000]
 *           ///< knng range:[5, 300]
 *       HNSW  "{M: '16', efConstruction:'500'}"
 *           ///< M range:[5, 48]
 *           ///< efConstruction range:[topk, 4096]

**Comment by yhmo** [comment]
For different index type, search parameter is different accordingly, for example:
     *       FLAT/IVFLAT/SQ8/IVFPQ:  {nprobe: 32}
     *           ///< nprobe range:[1,999999]
     *       NSG:  {search_length:100}
     *           ///< search_length range:[10, 300]
     *       HNSW {ef: 64}
     *           ///< ef range:[k, 4096]

**Comment by BossZou** [comment]
> For different index type, search parameter is different accordingly, for example:
> 
> * ```
>     FLAT/IVFLAT/SQ8/IVFPQ:  {nprobe: 32}
>   ```
> * ```
>         ///< nprobe range:[1,999999]
>   ```
> * ```
>     NSG:  {search_length:100}
>   ```
> * ```
>         ///< search_length range:[10, 300]
>   ```
> * ```
>     HNSW {ef: 64}
>   ```
> * ```
>         ///< ef range:[topk, 4096]
>   ```

Great.

**Comment by yamasite** [comment]
@yhmo Could you describe some of the parameters in detail? They were not exposed before and users may have no idea how to set them. 

Index:

- IVFPQ: m
- NSG: search_length out_degree candidate_pool_size knng
- HNSW: ef

Search:
- NSG: search_length
- HNSW: ef

What's the difference between search_length in index creation and searching?
