### ISSUE TITLE
Add AWS S3 SDK library into thirdparty

### ISSUE THREAD

**Issue by cydrain** [milvus-io/milvus#1451]
**Is your feature request related to a problem? Please describe.**
AWS full library is too large, it takes too much time to download and build

**Describe the solution you'd like**
Download and build used AWS S3 sub-libraries only

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by JinHai-CN** [comment]
Great，I also have the same idea.

**Comment by JinHai-CN** [comment]
Even the S3 and core sub-libraries are also about 8 MB size which should not included in source code. I have an idea which is to create another repo which only included the aws-sdk-cpp-core and aws-sdk-cpp-s3. Milvus just need to download this repo.

**Comment by JinHai-CN** [comment]
Move to 0.8.0

**Comment by scsven** [comment]
Not active, close.
