### ISSUE TITLE
Make the code pass ClangTidy or CppCheck.

### ISSUE THREAD

**Issue by JinHai-CN** [milvus-io/milvus#1454]
**Is your feature request related to a problem? Please describe.**
There are lots of issue might introduce bugs. which can be detected by static code analysis.

**Describe the solution you'd like**
Turn on the ClangTidy static code analysis and eliminate all issues.

**Describe alternatives you've considered**
Also can use cpp check.

**Additional context**

**Comment by scsven** [comment]
Done
