### ISSUE TITLE
[Bug]: [Cluster][CI] Fail to create consumer when trying to load a collection

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#14599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
```

### Current Behavior

CI failed: https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-14568/1/pipeline/126/
`[2021-12-30T02:55:34.400Z] [2021-12-30 02:55:23 - ERROR - pymilvus.client.grpc_handler]: Error: <BaseException: (code=1, message=collection 430134436279877634 has not been loaded to memory or load failed)> (grpc_handler.py:69)
`
![image](https://user-images.githubusercontent.com/82361606/147720467-168972f9-edb6-44b1-9901-80617662e8ef.png)

### Expected Behavior

ci pass 

### Steps To Reproduce

```markdown
it occasionally reproduces when running ci
```

**Comment by congqixia** [comment]
```
168360:time="2021-12-30T02:54:22Z" level=error msg="[Failed to create consumer]" consumerID=483 error="request timed out" name=qvhti subscription=by-dev-queryNode-8-430134436279877634-1408226934793101319 topic="persistent://public/default/by-dev-rootcoord-delta_22"
168362:time="2021-12-30T02:54:22Z" level=error msg="[Failed to create consumer]" consumerID=483 error="request timed out" name=qvhti subscription=by-dev-queryNode-8-430134436279877634-1408226934793101319 topic="persistent://public/default/by-dev-rootcoord-delta_22"
168368:time="2021-12-30T02:54:25Z" level=error msg="[Failed to create consumer]" consumerID=484 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=zobxt subscription=by-dev-queryNode-8-430134436279877634-1408226934793101319 topic="persistent://public/default/by-dev-rootcoord-delta_22"
168370:time="2021-12-30T02:54:25Z" level=error msg="[Failed to create consumer]" consumerID=484 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=zobxt subscription=by-dev-queryNode-8-430134436279877634-1408226934793101319 topic="persistent://public/default/by-dev-rootcoord-delta_22"
```
From the log, the consumer tried to connect but request timeout.(Consumer register successful in server but failed in client side) So the following consumer creation all failed due to exclusive policy.

**Comment by congqixia** [comment]
This is a known issue of pulsar.
There are some way to handle this:
1. Close pulsar client and reconnect.
2. Fail fast and let consumer component crash.

Since `msgstream` is a complicated component and hard to reconnect all consumers, producers and readers after reconnecting to pulsar, it's better to do `fail fast` way.

@yanliang567  could you please verify

**Comment by yanliang567** [comment]
close
