### ISSUE TITLE
[Bug]: RootCoord gets the binlog paths is incomplete when call BuildIndex

### ISSUE THREAD

**Issue by xiaocai2333** [milvus-io/milvus#14620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Load failed!
The segment of automatic compaction will only build an index on the data of one of the binlog paths.

IndexNode building index log：
```
[2021/12/30 16:26:57.670 +08:00] [DEBUG] [task.go:377] ["IndexNode build index"] ["data type"="float vector"] [dim=128] ["num rows"=32768]
```

RootCoord call BuildIndex log:
```
[2021/12/30 16:26:31.891 +08:00] [DEBUG] [root_coord.go:883] ["CallBuildIndex finished"] ["index name"=_default_idx] ["field name"=float_vector] ["segment id"=430139616572997633] ["num rows"=998873]
```

querynode load log:
```
row_count_opt_.value()998873
row_count32768
Assert "row_count_opt_.value() == row_count" at /home/zc/work/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:53
 => load data has different row count from other columns
```

### Expected Behavior

Load successfully.

### Steps To Reproduce

```markdown
1. Create a collection, auto compaction
2. Insert 10M, batch = 500000, flush after insert each batch
3. create index
4. Load and failed.
```

**Comment by xiaocai2333** [comment]
[datacoord.log](https://github.com/milvus-io/milvus/files/7792204/datacoord.log)
[datanode.log](https://github.com/milvus-io/milvus/files/7792206/datanode.log)

**Comment by XuanYang-cn** [comment]
L129-L140

https://github.com/milvus-io/milvus/blob/f96cd84efb0ce2a65fff46b97f04619874b59ec2/internal/datanode/binlog_io.go#L129

**Comment by xiaocai2333** [comment]
It's fixed. Close it.
