### ISSUE TITLE
[Bug]: The count of Pulsar subscriptions and consumers not match

### ISSUE THREAD

**Issue by LoveEachDay** [milvus-io/milvus#14658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: nightly 285
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

We've enabled pod monitor for milvus ci, and the summary of the pulsar cluster for [nightly 285](https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/285/pipeline) shown as below:
![image](https://user-images.githubusercontent.com/1573213/147799334-112d0353-3985-423a-b3f3-8e7fc31ecdce.png)

We can see the number of pulsar subscriptions and consumers varies greatly.

### Expected Behavior

The number of pulsar subscriptions and consumers equal.

### Steps To Reproduce

```markdown
1. trigger a nightly ci
2. check the dashboard for pulsar
```

### Anything else?
You can check the [pulsar messaging dashboard ](https://grafana-ci.milvus.io/d/sWPi0L-mk/pulsar-messaging-metrics?orgId=1&refresh=1m&from=now-12h&to=now&var-cluster=md-285-pulsar&var-namespace=All).
_No response_

**Comment by czs007** [comment]
The high probability is that when we destroy the Consumer object, we did not actively call the Consumer's Unsubscrible method.

from Pulsar 's Frequently Q&A:
```

What is the lifecycle of subscription?

Once it’s created, it retains all messages published after that (minus explicit TTL). 
Subscriptions can be dropped by explicitly unsubscribing (in Consumer API) or through the REST/CLI .
```

and refer to this article.

https://www.datastax.com/blog/2021/04/understanding-pulsar-message-ttl-backlog-and-retention

**Comment by xiaofan-luan** [comment]
how would we handle subscription if a node crash? @czs007  
That's probably why we can't random a subscription name because subscription number will out of control

**Comment by xiaofan-luan** [comment]
We need more information here, could you share the test result briefly? @xiaocai2333

**Comment by xiaofan-luan** [comment]
duplicate with #15193 close for now
