### ISSUE TITLE
[Bug]: High IO read usage and search became very slow

### ISSUE THREAD

**Issue by greensea** [milvus-io/milvus#14768]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:milvusdb/milvus-dev:master-20211222-5a29db6
- Deployment mode(standalone or cluster): standlone, docker
- SDK version(e.g. pymilvus v2.0.0rc2): golang
- OS(Ubuntu or CentOS): Debian
- CPU/Memory: Ryzen 5 2600X
- GPU: None
- Others:
```

### Current Behavior

I found milvus starts keep doing IO reading, and the search became very slow.
Everything was fine  2 days ago, but suddenly I found search became very slow. The search should return in 1 second (usually 100+ms), but this time it didn't return the result even for few minutes.
Then I check the system status, and found milvus is doing mass IO read. `iotop` shows that milvus is keep reading at 70~100MB/s speed. This is the max throughput of my disk.
I thought milvus is doing some data job, then I stop importing data to milvus, and stop sending search request, hope milvus finish the job quickly. 
But two days later, milvus is still doing IO read, and the total read data is over 1TB. The dataset is only 30+GB, why milvus doing so much reading?

### Expected Behavior

Milvus should not keep doing IO read, and should return search results in a second.

### Anything else?

There is only one collection, and is using IVF_PQ index.
Milvus is only doing mass IO read, no significant IO write.
Two days later I restart milvus, but it still doing mass IO reading.

**Comment by yanliang567** [comment]
@greensea one quick question: how much memory did you set for milvus? 
/assign @greensea 
/unassign

**Comment by greensea** [comment]
@yanliang567 The server memory is 31.3G. milvus is now used 13.2% memory (~3.4G). 
The server is used 10.1G memory, and there is 20+G free memory.

**Comment by yanliang567** [comment]
@scsven could you please take a look at this issue?
/assign @scsven 
/unassign @greensea

**Comment by xiaofan-luan** [comment]
might be a compaction issue?  how long does it run before the IO increaase?

**Comment by xiaofan-luan** [comment]
do you have logs of milvus?

**Comment by greensea** [comment]
@xiaofan-luan Running about 4~5 days before IO increase.
This is the log since last restart
[docker-compose.log](https://github.com/milvus-io/milvus/files/7806201/docker-compose.log)

**Comment by greensea** [comment]
Update: now milvus used 49.8% memory (~15GB), there is still ~10GB free memory for the server. milvus is still doing mass IO read. CPU usage of milvus is low, only 5% CPU is used.

**Comment by greensea** [comment]
@xiaofan-luan I just upgraded to milvusdb/milvus-dev:master-20220104-9f04855. This commit is 4 days after #14614. Now milvus working good. I will see if this issue happens in the next few days.

**Comment by yanliang567** [comment]
/assign @greensea 
@greensea please keep us posted if any updates. Thanks a lot.

/unassign @scsven

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan I just upgraded to milvusdb/milvus-dev:master-20220104-9f04855. This commit is 4 days after #14614. Now milvus working good. I will see if this issue happens in the next few days.

Sure,  thanks greensea, your issue might be related to we are not limiting compaction numbers and that might be solved in the previous patch
