### ISSUE TITLE
[Enhancement]:Support Partial Results When Run Search Query 

### ISSUE THREAD

**Issue by codersky** [milvus-io/milvus#14840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Search query return as soon as possible when the query load restarted and under loading progress still.

### Why is this needed?

when query load crashes and is restarted, as usual, it takes some time to load the data into memory for querying, for now, the service will hang and fail until all nodes are recovered successfully. sometimes, we can tolerate some data loss, for this case, can the Milvus query support query and return the result immediately. it can be one config/param when we conduct the query.

**Comment by xiaofan-luan** [comment]
That's a good suggestion, we need a extra field(such as speculative read) so the proxy won't wait for all quernode to return and it will return the result after speculative timeout

**Comment by xiaofan-luan** [comment]
@codersky would you want to take this feature? thought it might help on the system availability because reload will take couple minutes

**Comment by xiaofan-luan** [comment]
@codersky would you want to take this feature? thought it might help on the system availability because reload will take couple minutes

**Comment by codersky** [comment]
Glad to take it, i've cloned and setup the dev environment of Milvus.

**Comment by xiaofan-luan** [comment]
/assign @codersky  
welcome~

**Comment by xiaofan-luan** [comment]
how is the design going on? you may want to implement a MEP(Milvus enhancement plan) before we move into code

**Comment by codersky** [comment]
we are working on some internal company legal review, will still work on it
