### ISSUE TITLE
Index type changed to IDMAP after compacted

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#1484]
**Describe the bug**
We droped table index after compacted, it's a problem

1. create table(index_file_size: 10M) and index: ivf_sq8
2. add vectors (10, 000,128d) into table
3. delete two vectors
4. flush and compact
5. describe_index, index_type return FLAT
///
continue to add vectors（300,000）into table
flush table, and still no index created

**Steps/Code to reproduce behavior**

**Expected behavior**

**Environment details**

**Screenshots**

**Additional context**

**Comment by JinHai-CN** [comment]
Compact will generate new segment, the new segment index should have the same type as old one.

**Comment by del-zhenwu** [comment]
fixed
