### ISSUE TITLE
[Bug]: querynode: number of RootCoord is incorrect

### ISSUE THREAD

**Issue by JamCrash** [milvus-io/milvus#14873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: PreGA-latest
```

### Current Behavior

[2022/01/05 09:31:16.630 +00:00] [DEBUG] [client.go:66] ["RootCoordClient GetSessions success"]
[2022/01/05 09:31:16.630 +00:00] [DEBUG] [client.go:69] ["RootCoordClient mess key not exist"] [key=RootCoord]
[2022/01/05 09:31:16.630 +00:00] [DEBUG] [client.go:110] ["RootCoordClient getRootCoordAddr failed"] [error="number of RootCoord is incorrect, 0"]
[2022/01/05 09:31:17.034 +00:00] [DEBUG] [session_util.go:277] ["SessionUtil GetSessions"] [prefix=RootCoord] [resp="{\"header\":{\"cluster_id\":11167392865659229443,\"member_id\":17531627772568193069,\"revision\":101443,\"raft_term\":2}}"]

### Expected Behavior

After deploy 20 querynode, some querynodes are running well, while some querynodes show logs like this, after restart (maybe serveral times)it runs well

seems like #14005

ps: the milvus-proxy shows the same log, but should restart serveral times to fix, before that the coord pod was already start

**Comment by yanliang567** [comment]
@JamCrash According to #14005, could you please help to double check the status of etcd and minio services? if the symptom is same, could you please help to retry on PreGA release?
/assign @JamCrash 
/unassign

**Comment by JamCrash** [comment]
I am using the PreGA version @yanliang567 
The etcd status is fine, and I am using the aws s3, not minio
the rootcoord shows logs like this sometimes: [2022/01/05 10:01:13.796 +00:00] [WARN] [timeticksync.go:339] ["rootcoord send tt to all channels too slowly"] [chanNum=4] [span=249]

And the rootcoord pulsar monitor like this:

**Comment by JamCrash** [comment]
some querynode restart many times and still show error logs like above, I think it can't recover forerver

**Comment by yanliang567** [comment]
@JamCrash could you please try to upload the logs for querynode, rootcoord and proxy?

**Comment by JamCrash** [comment]
[rootcoord.log](https://github.com/milvus-io/milvus/files/7814429/rootcoord.log)
[querynode.log](https://github.com/milvus-io/milvus/files/7814430/querynode.log)
proxy runs well now @yanliang567

**Comment by yanliang567** [comment]
@xige-16 could you please help to check this issue? a similar issue could be #14005
/assign @xige-16

**Comment by xige-16** [comment]
> getRootCoordA

It seems the rootCoord has stoped

**Comment by xige-16** [comment]
After 11:09, rootcoord has no log output, and querynode is still trying to restart at 11:30, but because rootcoord is gone, the restart is unsuccessful.

**Comment by xige-16** [comment]
You can check whether there is rootcoord meta under prefix=by-dev/meta/session/ in etcd. @JamCrash

**Comment by xige-16** [comment]
> RootCoordClient

If the prefix path where the session is stored has not changed, the rootcoord must be down.

**Comment by JamCrash** [comment]
> You can check whether there is rootcoord meta under prefix=by-dev/meta/session/ in etcd. @JamCrash

I can not find the prefix under root path, could you tell where is it ?

**Comment by JamCrash** [comment]
proxy log:
[proxy.log](https://github.com/milvus-io/milvus/files/7819158/proxy.log)

**Comment by JamCrash** [comment]
The rootcoord always says “rootcoord send tt to all channels too slowly”，does it matter?

**Comment by xige-16** [comment]
![iXeaS3d32u](https://user-images.githubusercontent.com/20124155/148324344-a0abf607-0087-4330-a930-2f0b651cd51b.png)
![tMxkQ7ozqy](https://user-images.githubusercontent.com/20124155/148324354-aa934eac-38f3-4f08-8689-51986b2ee4b9.png)

**Comment by xige-16** [comment]
The version of querynode is inconsistent with other components @JamCrash

**Comment by JamCrash** [comment]
It runs well now， imagePullPolicy set to "Always" can fix this, thanks

**Comment by len-n-a-rt** [comment]
Same here

@JamCrash   "imagePullPolicy set to "Always" can fix this, thanks"
how can this help ?

**Comment by xqxq-2020** [comment]
> 
 Excuse me, where could i change imagePullPolicy set to "Always"?
