### ISSUE TITLE
[Bug]: insert data then load collection will  get exception  

### ISSUE THREAD

**Issue by xincrazy** [milvus-io/milvus#14875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: PreGA-latest
```

### Current Behavior

Failed to load data. Query logs as follows:

2022/01/05 09:48:34.239 +00:00] [ERROR] [root_coord.go:1709] ["DescribeSegment failed"] [role=rootcoord] ["collection id"=430276305373888513] ["segment id"=430276489398976513] [msgID=0] [error="segment id 430276489398976513 not belong to collection id 430276305373888513"] [stack="github.com/milvus-io/milvus/internal/rootcoord.(*Core).DescribeSegment\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:1709\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).DescribeSegment\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:413\ngithub.com/milvus-io/milvus/internal/proto/rootcoordpb._RootCoord_DescribeSegment_Handler.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proto/rootcoordpb/root_coord.pb.go:1077\ngithub.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38\ngithub.com/milvus-io/milvus/internal/proto/rootcoordpb._RootCoord_DescribeSegment_Handler\n\t/go/src/github.com/milvus-io/milvus/internal/proto/rootcoordpb/root_coord.pb.go:1079\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934"]

### Expected Behavior

load data success and No manual refresh is required to query data

**Comment by zhangsilence** [comment]
agree

**Comment by yanliang567** [comment]
@xincrazy are you running with cluster mode or standalone mode? could you please help to upload the whole log file for investigation?
/assign @xincrazy 
/unassign

**Comment by xincrazy** [comment]
we are running with cluster mode。The log file is not saved, I have solved the problem by loading data first and then writing data, but I feel this is a bug。

**Comment by yanliang567** [comment]
this is weird, it does not reproduce to us. could you please share your info/details about what you did before you met this issue?

**Comment by xincrazy** [comment]
First I create collection, then write data, then load failed, but if I create collection and load directly, it will succeed, but still can not query data, need to execute getCollectionStatistics method to query results.

**Comment by xiaofan-luan** [comment]
@xincrazy this issue should be solved and it's duplicated with #15139, please check in the GA version
