### ISSUE TITLE
Could Mishards employ Milvus on two different ports from the same host?

### ISSUE THREAD

**Issue by Alsace-lee** [milvus-io/milvus#1494]
**What is your question?**
For testing purposes, I want to deploy read-only and writable milvus on two ports of the same host, but it seems that the configuration file does not allow you to do this

**Comment by XuPeng-SH** [comment]
@Alsace-lee

1. You can refer to all_in_one demo in our github repo. Also if you understand Chinese, you can refer to this page for how to deploy Mishards: https://blog.csdn.net/weixin_44839084/article/details/104354297

2. There are three parameters related to address configuration in Mishard config file:
   1) SERVER_PORT
       Specify Mishards port: Ex. 19535
   2) WOSERVER 
        Specify writable server address: Ex. "tcp://localhost:19531"
   3) DISCOVERY_STATIC_HOSTS
        Specify readonly servers. The port number is hard-coded to 19530. Ex. 
        "localhost" 

Right now Mishards is not robust enough for multi-machine configurations and is not convenient to deploy.
