### ISSUE TITLE
Milvus report assert error when exit

### ISSUE THREAD

**Issue by cydrain** [milvus-io/milvus#1497]
**Describe the bug**
Sometimes, GPU version Milvus report following error when exit:
```
^CMilvus server is going to shutdown ...
Milvus server exit...
Faiss assertion 'err__ == cudaSuccess' failed in faiss::PageLockMemory::~PageLockMemory() at InvertedLists.cpp:36; details: CUDA error 4 driver shutting down
```

**Steps/Code to reproduce behavior**
1. run GPU version Milvus
2. exit using Ctrl+C

**Expected behavior**
should be no error

**Environment details**

**Screenshots**

**Additional context**

**Comment by sahuang** [comment]
Not reprodused in Master branch after running tests with GPU version.
