### ISSUE TITLE
Milvus v0.6.0 generated duplicate ids

### ISSUE THREAD

**Issue by scsven** [milvus-io/milvus#1499]
**Describe the bug**
After inserting 1 million vectors in Milvus, the ids returned are somewhat duplicated.
I have test is on several cloud server, the number of duplicated varies.

**Steps/Code to reproduce behavior**
1. Start container with this image: milvusdb/milvus:0.6.0-cpu-d120719-2b40dd
2. create_table
3. insert 1 million vectors without ids.
4. milvus returned ids duplicated.

**Expected behavior**
Milvus add function provide unique id for every vector.

**Environment details**
- amazon ec2 c5.4xlarge
- Docker
- milvus v0.6.0
- CPU cache: 16gb

**Screenshots**
![企业微信截图_fcbbbf08-3190-4929-aac6-928aed34b27d](https://user-images.githubusercontent.com/12595343/75845917-8fe9a680-5e15-11ea-8c9e-cc5c6bad8a69.png)

![企业微信截图_dd9ca850-7230-428f-a4a1-01cb22ac85c5](https://user-images.githubusercontent.com/12595343/75845934-9e37c280-5e15-11ea-97d8-dadceb781d2c.png)

**Additional context**
I inserted 1 million vectors, there are only 958001 unique ids.

**Comment by JinHai-CN** [comment]
@del-zhenwu We need to add cases on this issue.

**Comment by JinHai-CN** [comment]
@tinkerlin Basic idea:
- Use singleton pattern to update GenerateID.
- Use mutex to provide thread-safe method.
- Add a new check on the timestamp to avoid the timestamp duplicate.
- Rewrite the recursive code to loop.
