### ISSUE TITLE
[Bug]: Index node memory not released

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#15000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220105-2520e57
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.0.0rc9.dev22
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server:
<img width="1185" alt="截屏2022-01-07 下午1 12 57" src="https://user-images.githubusercontent.com/34296482/148495390-cf00ffcf-bb26-49af-9c3d-b0a88231d143.png">
client:
<img width="1350" alt="截屏2022-01-07 上午10 09 52" src="https://user-images.githubusercontent.com/34296482/148495442-c91d4105-81f0-43dd-bea7-366a59600e69.png">

### Expected Behavior

The indexnode's memory should be released

### Steps To Reproduce

```markdown
1. deploy Milvus with minimal config
2. create a collection and insert 10m entities
3. build index 
{"index_type": "IVF_SQ8", "params": {"nlist": 1024}, "metric_type": "L2"}
4.load collection
5.search twice 
{"metric_type": "L2", "params": {"nprobe": 8}}
6.collection.release()
7.sleep(10)
Repeat the process of loading
```

**Comment by DragonDriver** [comment]
What's the memory limit of indexnode? @jingkl

**Comment by DragonDriver** [comment]
Should the memory curve of indexnode act like querynodes'? @jingkl @czs007 @xiaofan-luan
