### ISSUE TITLE
[Enhancement]: Reduce peak memory usage in indexnode

### ISSUE THREAD

**Issue by czs007** [milvus-io/milvus#15043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

I would like to refactor the logic of IndexBuildTask in indexnode.

The index building is divided into the following steps.
1) Load vector data into memory ( VectorDataMemory)
2) Construct Index object (IndexObj)
3) Call the serialization method of the Index object to get the blob of index. (IndexBlobs)
4) Call the Serialize  method defined in storage package to encode the IndexBlobs into SerializedIndexBlobs files to be stored
5) Write the SerializedIndexBlobs files to the object storage through KV interface

The source codes for the above 5 steps are currently written in the Execute method of IndexBuildTask.
There are two shortcomings. One is that the number of lines of code in this method is very long, and the readability is not good. The other is that the life cycle of the variable is too long.

An ideal situation is to split the code into different sub-functions and organize the life cycle of these objects as follows:

![image](https://user-images.githubusercontent.com/59249785/148731927-5dd21de7-7efb-41f1-be38-65d71a01d697.png)

In this way, in the 4 steps of loadAndBuild、Serialize1、Serialize2、 and Save, only two objects are in the same life cycle at the same time.
It should be noted that IndexObj.Delete is called after Serialize1 and before Serialize2 to release the memory occupied by IndexObj.

### Why is this needed?

Reduce peak memory usage in indexnode.

**Comment by xiaofan-luan** [comment]
close
