### ISSUE TITLE
[Bug]: The delete operation did not take effect in hello_milvus.py

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#15101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.0 preGA
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus v2.0.0rc9
- OS(Ubuntu or CentOS): macOS
- CPU/Memory: 8vcpu/32GB
- GPU: 
- Others:
```

### Current Behavior

![XC9z8y90QY](https://user-images.githubusercontent.com/53512883/148737566-7d7f3280-b898-4230-8a29-f6b1b20e69ca.png)

After the vector is deleted, it is still available through the query interface.

### Expected Behavior

After the vector is deleted, it is not available through the query interface.

### Steps To Reproduce

```markdown
1. start milvus-standalone preGA
2. install pymilvus rc9
3. wget https://raw.githubusercontent.com/milvus-io/pymilvus/v2.0.0rc9/examples/hello_milvus.py
4. python hello_milvus.py
```

### Anything else?

N/A

**Comment by yanliang567** [comment]
sounds like a known issue, which occasionally happens in PreGA.
@congqixia @czs007 could you please take a look?

/assign @congqixia 
/unassign

**Comment by JackLCL** [comment]
hello_milvus.py is the first test example after installing milvus on the official website, I hope it will be fixed soon.

**Comment by congqixia** [comment]
@godchen0212 is working on it.
/unassign
/assign @godchen0212

**Comment by godchen0212** [comment]
Pymilvus has a new setting called consistency. The default is Consistency.Bounded, it means that data for a period of time is acceptable, default is 5 seconds. The search results have already been returned when the current deletion has not been actually applied in the system. 
The new hello_milvus will configure the collection to be Consitency.Strong, which is strong consistency to solve this problem. The issue has been fixed in pymilvus master branch.
You can get new hellow_pymilvus with this cmd:
`wget https://raw.githubusercontent.com/milvus-io/pymilvus/master/examples/hello_milvus.py`

**Comment by xiaofan-luan** [comment]
you should just wait for 2 couple of minutes and retry see if delete take effect, default mode is eventual consistency.

Otherwise you can try to set consistency level to strong and retry

**Comment by JackLCL** [comment]
https://milvus.io/docs/v2.0.0/example_code.md#:~:text=wget%20https%3A//raw.githubusercontent.com/milvus%2Dio/pymilvus/v2.0.0rc9/examples/hello_milvus.py

The official website should also be updated at the same time.

**Comment by JackLCL** [comment]
> Pymilvus has a new setting called consistency. The default is Consistency.Bounded, it means that data for a period of time is acceptable, default is 5 seconds. The search results have already been returned when the current deletion has not been actually applied in the system. The new hello_milvus will configure the collection to be Consitency.Strong, which is strong consistency to solve this problem. The issue has been fixed in pymilvus master branch. You can get new hellow_pymilvus with this cmd: `wget https://raw.githubusercontent.com/milvus-io/pymilvus/master/examples/hello_milvus.py`

It works well now.
