### ISSUE TITLE
if client create index with empty params, server will create index successfully or not

### ISSUE THREAD

**Issue by shengjh** [milvus-io/milvus#1516]
**What is your question?**
In json branch, create index for a table with empty params. Server will create index successfully or not?

such as:
connect.create_index(table_name, index_type, {})

**Comment by JinHai-CN** [comment]
Milvus will return with error message.

**Comment by shengjh** [comment]
Does not milvus has some default value for index params?
There is a similar problem，if search vectors with empty params, milvus will return error or success?

**Comment by tinkerlin** [comment]
- No, Milvus has no default parameters.
- milvus will return error  If Index need search params, otherwise return success.
