### ISSUE TITLE
[Bug]: Invalid globalSealedSegments in historical

### ISSUE THREAD

**Issue by bigsheeper** [milvus-io/milvus#15178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

globalSealedSegments in historical is invalid

### Expected Behavior

use globalSealedSegmentsManager

**Comment by xige-16** [comment]
This bug will cause the globalSegmentID of the searchResult to be incorrectly set, and the proxy may return in advance before receiving the full query result.
