### ISSUE TITLE
Search with invalid params return success unexpectedly

### ISSUE THREAD

**Issue by shengjh** [milvus-io/milvus#1519]
**Describe the bug**
Build ivf index for a table, then search vectors with invalid nprobe param.
For example, search((table, top_k, query_vecs, params={"nprobe": "\t"}).
Unexpectedly, it return OK status. 

With hnsw index and searh with invalid params,
such as search(table, top_k, vector, params={"typo": "100"}). It also return OK.

**Expected behavior**
Return status with error
**Environment details**
Branch: json

**Comment by tinkerlin** [comment]
The check process is divided into two phases. First, once the parameters are accepted from the client, the server checks the parameters. If invalid, the server will return a failed status. The second check occurred before the actual indexing. This problem situation is in the first stage. This part of the code is maintained by @yhmo

**Comment by shengjh** [comment]
The problem mentioned above has been fixed. However, still have another bug.
With ivf index, search with too large nprobe(9999999999) or two low nprobe(0), server return OK, but expected error. And there is a strange thing, server return expected error when nprobe setted    @tinkerlin

**Comment by yhmo** [comment]
already fixed in latest json branch

**Comment by yhmo** [comment]
For invalid probe, will return error message like:
"Invalid nprobe value: 9999999999. Valid range is [1, 999999]"
