### ISSUE TITLE
[Bug]: Insert 10 million data to build index OOM, indexnode memory set to 5G

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#15192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220112-3254d36
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server：
<img width="1262" alt="截屏2022-01-13 下午5 15 25" src="https://user-images.githubusercontent.com/34296482/149300962-da6c1f6e-e3e1-4236-ad2a-352e0495c86c.png">
grafana:
<img width="1378" alt="20220113-172026" src="https://user-images.githubusercontent.com/34296482/149301728-45643c96-8c83-4283-ad5a-f5f580a72873.png">

### Expected Behavior

indexnode memory:5GB

Creating hnsw indexes should not crash

### Steps To Reproduce

```markdown
step：
1. Insert 50,000 data at a time, 200 times in total
2. build collection>build  hnsw index>insert data ,index_params = {"index_type": "HNSW", "params": {"M": 8, "efConstruction": 200}, "metric_type": "L2"}
3. load>search,search_params = {"metric_type": "L2", "params": {"ef": 64}}
```

**Comment by xiaocai2333** [comment]
A small suggestion: please don't paste the image for the server pod name, otherwise it cannot be copied. @jingkl

**Comment by jingkl** [comment]
Using  new  milvus image, verified 1000w  hnsw index data, indexnode  set 5G no OOM, actual use 4.23GB
