### ISSUE TITLE
[Bug]: The number of vectors in attu is not right.

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#15207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:preGA
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):rc9
- OS(Ubuntu or CentOS): macos
- CPU/Memory: 8vcpu/32G
- GPU: 
- Others:
```

### Current Behavior

After inserting a new batch of vectors into milvus, the number of vectors in attu is not updated. After calling the num_entities interface of pymilvus, the number of vectors in attu is restored to normal.

### Expected Behavior

After inserting a new batch of vectors into milvus, the number of vector entries in attu can be updated normally.

**Comment by liuyanfeng1981** [comment]
I also encountered this situation

**Comment by yanliang567** [comment]
@shanghaikid is this a issue of attu?

/assign @shanghaikid 
/unassign

**Comment by nameczz** [comment]
@JackLCL In Attu, after insert data,  we will use async flush to flush data.  So it may take some time to update the entity count in Attu.

**Comment by JackLCL** [comment]
> @JackLCL In Attu, after insert data, we will use async flush to flush data. So it may take some time to update the entity count in Attu.

@nameczz If so, it would be nice to have a hint next to the result of count.
