### ISSUE TITLE
[Enhancement]: Better to send search/query results by rpc

### ISSUE THREAD

**Issue by DragonDriver** [milvus-io/milvus#15212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Now, Proxy communicates with QueryNodes by message stream. QueryNodes will send search/query results using message stream, and then Proxy will consume these message to construct a final result to return to the client.

However, under this mechanism, there are some problems as below:
- 1, search/query result transfered in message stream is a little slow, which will limit the qps of search/query;
- 2, When we deploy Milvus cluster, actually we use pulsar as our message stream framework. Every Proxy will create a different subscription to the result stream. According to the pulsar documentation, pulsar will maintain a backlog for every subscription. If the produced message wasn't been consumed by the subscriber, the backlog will grow. Imagine one situation, QueryNodes send search/query results to the stream, and in the same time, Proxy the consumer of this subsciption goes to be down, so these messages will always been kept until their TTL arrive. And these messages will be too many to cause pulsar serving slowly or even not serving.

So I would like to change the behavior that Proxy communicates with QueryNodes. Maybe it's better to let QueryNodes send search/query results by rpc.

Two APIs should be added into Proxy:
```go
type Proxy interface {
    SendSearchResult(result interface{}) (*commonpb.Status, error)
    SendQueryResult(result interface{}) (*commonpb.Status, error)
}
```

QueryNodes should maintain the connection of Proxys, so maybe a `SessionManager` will be required like below:

```go
type Session struct {
	// info about Proxy
}

type SessionManager interface {
	AddSession(session Session) error
	DelSession(session Session) error
	GetOrCreateClient(nodeID UniqueID) types.Proxy
}

type ResultSender struct {
	mgr SessionManager
}

func (s *ResultSender) Start() {
	// watch etcd to update session in SessionManager.
}

func (s *ResultSender) SendSearch(nodeID UniqueID, result interface{}) {
	s.mgr.GetOrCreateClient(nodeID).SendSearchResult(result)
}

func (s *ResultSender) SendQuery(nodeID UniqueID, result interface{}) {
	s.mgr.GetOrCreateClient(nodeID).SendQueryResult(result)
}
```

### Why is this needed?

Decrease the pressure that we use message stream (pulsar).

**Comment by czs007** [comment]
type Proxy interface {
    SendSearch(result interface{}) (*commonpb.Status, error)
    SendQuery(result interface{}) (*commonpb.Status, error)
}

better to be renamed as SendSearchResult and SendQueryResult

**Comment by xiaofan-luan** [comment]
Agree, it should also improve the performance once we send it by rpc~
