### ISSUE TITLE
[Bug]: When Sizing tool calculates a vector, the result is not correct.

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#15232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:N/A
- Deployment mode(standalone or cluster):N/A
- SDK version(e.g. pymilvus v2.0.0rc2):N/A
- OS(Ubuntu or CentOS): N/A
- CPU/Memory: N/A
- GPU: N/A
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/53512883/149688339-8026ee45-1d65-4544-9785-cb33b7de79d8.png)

**Comment by yanliang567** [comment]
@shanghaikid could you please help to take a look at this issue?

/assign @shanghaikid 
/unassign

**Comment by ThyeeZz** [comment]
> @shanghaikid could you please help to take a look at this issue?
> 
> /assign @shanghaikid /unassign

already fixed

**Comment by shanghaikid** [comment]
please test and close this issue. @yanliang567

**Comment by yanliang567** [comment]
@JackLCL could you please help to retry 

/unassign
/assign @JackLCL

**Comment by JackLCL** [comment]
It works well now.
