### ISSUE TITLE
[Bug]: The segments distributed to querynode are inbalance and the memory release insufficient

### ISSUE THREAD

**Issue by JamCrash** [milvus-io/milvus#15233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: pre-GA
- Deployment mode(standalone or cluster): cluster
```

### Current Behavior
do the insert/build index/load operations in concurrency, and the segments distributed to querynode are inbalance, the majority of the querynodes got 6GB segments while some got more than 30GB; search fine; after release, the memory does not release suficient:
(the cluster only has one collection)
![image](https://user-images.githubusercontent.com/39126346/149695940-988a727f-57fd-48c1-8b49-ea3087e2172c.png)
![image](https://user-images.githubusercontent.com/39126346/149696589-91711097-8210-49f2-8889-e7a98fbaae8a.png)

**Comment by yanliang567** [comment]
sounds like 2 issues here: 
1. segments distributed not balanced
2. memory release insufficent

@JamCrash could you please share more details about how to reproduce the #1 issue, how many entities you inserted, how many query nodes you deployed, and how you find the segments distributed inbalanced?  for the #2 issue, this is a know issue for now, and we are trying to improve it 

/assign @JamCrash 
/unassign

**Comment by JamCrash** [comment]
> 



> sounds like 2 issues here:
> 
> 1. segments distributed not balanced
> 2. memory release insufficent
> 
> @JamCrash could you please share more details about how to reproduce the #1 issue, how many entities you inserted, how many query nodes you deployed, and how you find the segments distributed inbalanced? for the #2 issue, this is a know issue for now, and we are trying to improve it
> 
> /assign @JamCrash /unassign

**Comment by JamCrash** [comment]
> sounds like 2 issues here:
> 
> 1. segments distributed not balanced
> 2. memory release insufficent
> 
> @JamCrash could you please share more details about how to reproduce the #1 issue, how many entities you inserted, how many query nodes you deployed, and how you find the segments distributed inbalanced? for the #2 issue, this is a know issue for now, and we are trying to improve it
> 
> /assign @JamCrash /unassign

20nodes, 2 inbalance

**Comment by yanliang567** [comment]
@JamCrash If do concurrency, some query nodes are loaded with index files and some are loaded with original vectors, and that could be the reason. We suggest you release and reload the collection after build index done, this would ensure all querynodes are loaded with index files, and it also benefits in search

**Comment by JamCrash** [comment]
> 

I have do that, it does not solve the problem(not balance)
besides, I think milvus should release the original vectors automatically, because there always have new vectors inserted in production environment

**Comment by yanliang567** [comment]
> > 
> 
> I have do that, it does not solve the problem(not balance) besides, I think milvus should release the original vectors automatically, because there always have new vectors inserted in production environment

Yes, this is one of enhancements that we are planning.
@xige-16 could you please take a look at the inbalance issue?
/assign @xige-16 
/unassign @JamCrash

**Comment by xige-16** [comment]
@JamCrash  If do concurrency, 

> > 
> 
> I have do that, it does not solve the problem(not balance) besides, I think milvus should release the original vectors automatically, because there always have new vectors inserted in production environment

For newly inserted vector data, milvus already supports automatic replacement of the original vector with index.

**Comment by xige-16** [comment]
@JamCrash The two unbalanced nodes should be watching dmchannel and have been receiving streaming data. I will check why they consume so much memory.

**Comment by JamCrash** [comment]
does this issue reproduce?

**Comment by xiaofan-luan** [comment]
@xige-16 any followup?

**Comment by xige-16** [comment]
> does this issue reproduce?

I didn't detect this problem on the unbutu bare metal, and I'll start the milvus test with helm again.

**Comment by xige-16** [comment]
> > does this issue reproduce?
> 
> I didn't detect this problem on the unbutu bare metal, and I'll start the milvus test with helm again. @JamCrash

**Comment by JamCrash** [comment]
If any question I found, I'll ask in this issue, close it for now
