### ISSUE TITLE
[Bug]: Find a data race in querycoord/impl_test.go

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#15238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: go1.17.5
```

### Current Behavior

WARNING: DATA RACE
Write at 0x00c0018d0e58 by goroutine 277:
  github.com/milvus-io/milvus/internal/querycoord.Test_RepeatedLoadDifferentPartitions()
      /Users/zilliz/workspace/dev/milvus/internal/querycoord/impl_test.go:918 +0x4ed
  testing.tRunner()
      /usr/local/Cellar/go/1.17.5/libexec/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/Cellar/go/1.17.5/libexec/src/testing/testing.go:1306 +0x47

Previous read at 0x00c0018d0e58 by goroutine 156:
  github.com/milvus-io/milvus/internal/querycoord.(*loadPartitionTask).updateTaskProcess()
      /Users/zilliz/workspace/dev/milvus/internal/querycoord/task.go:688 +0xc5
  github.com/milvus-io/milvus/internal/querycoord.(*watchQueryChannelTask).updateTaskProcess()
      /Users/zilliz/workspace/dev/milvus/internal/querycoord/task.go:1397 +0xbd
  github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask()
      /Users/zilliz/workspace/dev/milvus/internal/querycoord/task_scheduler.go:567 +0x9a9
  github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processActivateTaskLoop.func1()
      /Users/zilliz/workspace/dev/milvus/internal/querycoord/task_scheduler.go:857 +0x64

Goroutine 277 (running) created at:
  testing.(*T).Run()
      /usr/local/Cellar/go/1.17.5/libexec/src/testing/testing.go:1306 +0x726
  testing.runTests.func1()
      /usr/local/Cellar/go/1.17.5/libexec/src/testing/testing.go:1598 +0x99
  testing.tRunner()
      /usr/local/Cellar/go/1.17.5/libexec/src/testing/testing.go:1259 +0x22f
  testing.runTests()
      /usr/local/Cellar/go/1.17.5/libexec/src/testing/testing.go:1596 +0x7ca
  testing.(*M).Run()
      /usr/local/Cellar/go/1.17.5/libexec/src/testing/testing.go:1504 +0x9d1
  github.com/milvus-io/milvus/internal/querycoord.TestMain()
      /Users/zilliz/workspace/dev/milvus/internal/querycoord/query_coord_test.go:60 +0x3b
  main.main()
      _testmain.go:257 +0x364

Goroutine 156 (running) created at:
  github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processActivateTaskLoop()
      /Users/zilliz/workspace/dev/milvus/internal/querycoord/task_scheduler.go:856 +0x3f9
  github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).Start·dwrap·91()
      /Users/zilliz/workspace/dev/milvus/internal/querycoord/task_scheduler.go:869 +0x39

### Steps To Reproduce

```markdown
1. Use go1.17.5
2. Run go test:
 go test -race -cover "github.com/milvus-io/milvus/internal/querycoord/..." -failfast -v
```

**Comment by yanliang567** [comment]
@jaime0815 I guess you are working on this issue.
/assign @jaime0815 
/unassign

**Comment by jaime0815** [comment]
this issue can not be reproduced after trying it again  -_-
