### ISSUE TITLE
[Bug]: rootcoord send tt to all channels too slowly

### ISSUE THREAD

**Issue by hf185** [milvus-io/milvus#15249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.0.0-pre-ga
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS7.9
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
2022/01/17 08:49:15 clock offset{jet-lag 8 712621062  <nil>} {prev-physical 16 1642409355212950812  UTC} {now 16 1642409355925571874  UTC}
2022/01/17 08:49:15 clock offset{jet-lag 8 662659322  <nil>} {prev-physical 16 1642409355262945719  UTC} {now 16 1642409355925605041  UTC}
2022/01/17 08:49:16 clock offset{jet-lag 8 321856716  <nil>} {prev-physical 16 1642409356662951581  UTC} {now 16 1642409356984808297  UTC}
2022/01/17 08:49:16 clock offset{jet-lag 8 321897385  <nil>} {prev-physical 16 1642409356662952438  UTC} {now 16 1642409356984849823  UTC}
[2022/01/17 08:49:17.678 +00:00] [WARN] [timeticksync.go:339] ["rootcoord send tt to all channels too slowly"] [chanNum=8] [span=378]
2022/01/17 08:49:56 clock offset{jet-lag 8 465974629  <nil>} {prev-physical 16 1642409395662948730  UTC} {now 16 1642409396128923359  UTC}
2022/01/17 08:49:56 clock offset{jet-lag 8 466019843  <nil>} {prev-physical 16 1642409395662950314  UTC} {now 16 1642409396128970157  UTC}
2022/01/17 08:52:45 clock offset{jet-lag 8 196894937  <nil>} {prev-physical 16 1642409565212972781  UTC} {now 16 1642409565409867718  UTC}
[2022/01/17 08:53:01.361 +00:00] [WARN] [timeticksync.go:339] ["rootcoord send tt to all channels too slowly"] [chanNum=8] [span=260]
2022/01/17 08:53:21 clock offset{jet-lag 8 180788902  <nil>} {prev-physical 16 1642409601212975881  UTC} {now 16 1642409601393764783  UTC}
2022/01/17 08:53:28 clock offset{jet-lag 8 285918652  <nil>} {prev-physical 16 1642409608662964149  UTC} {now 16 1642409608948882801  UTC}
2022/01/17 08:53:28 clock offset{jet-lag 8 285943442  <nil>} {prev-physical 16 1642409608662966241  UTC} {now 16 1642409608948909683  UTC}
[2022/01/17 08:55:48.688 +00:00] [WARN] [timeticksync.go:339] ["rootcoord send tt to all channels too slowly"] [chanNum=8] [span=388]
2022/01/17 08:55:49 clock offset{jet-lag 8 1490683425  <nil>} {prev-physical 16 1642409748212969627  UTC} {now 16 1642409749703653052  UTC}
2022/01/17 08:55:49 clock offset{jet-lag 8 1441345457  <nil>} {prev-physical 16 1642409748262959602  UTC} {now 16 1642409749704305059  UTC}
2022/01/17 08:55:52 clock offset{jet-lag 8 1452597394  <nil>} {prev-physical 16 1642409751212952662  UTC} {now 16 1642409752665550056  UTC}
2022/01/17 08:55:52 clock offset{jet-lag 8 1402615375  <nil>} {prev-physical 16 1642409751262963017  UTC} {now 16 1642409752665578392  UTC}
2022/01/17 08:55:54 clock offset{jet-lag 8 313196664  <nil>} {prev-physical 16 1642409754212966302  UTC} {now 16 1642409754526162966  UTC}
2022/01/17 08:55:54 clock offset{jet-lag 8 263230189  <nil>} {prev-physical 16 1642409754262960572  UTC} {now 16 1642409754526190761  UTC}
[2022/01/17 08:56:49.713 +00:00] [DEBUG] [root_coord.go:325] ["check flushed segments"]
2022/01/17 08:58:29 clock offset{jet-lag 8 1268614718  <nil>} {prev-physical 16 1642409908712964244  UTC} {now 16 1642409909981578962  UTC}
2022/01/17 08:58:29 clock offset{jet-lag 8 1268651944  <nil>} {prev-physical 16 1642409908712965624  UTC} {now 16 1642409909981617568  UTC}
2022/01/17 09:00:12 clock offset{jet-lag 8 693612298  <nil>} {prev-physical 16 1642410012212958490  UTC} {now 16 1642410012906570788  UTC}
2022/01/17 09:00:12 clock offset{jet-lag 8 643706731  <nil>} {prev-physical 16 1642410012262906182  UTC} {now 16 1642410012906612913  UTC}
[2022/01/17 09:00:39.305 +00:00] [WARN] [timeticksync.go:339] ["rootcoord send tt to all channels too slowly"] [chanNum=8] [span=605]
[2022/01/17 09:01:21.636 +00:00] [WARN] [timeticksync.go:339] ["rootcoord send tt to all channels too slowly"] [chanNum=8] [span=335]
```

### Steps To Reproduce

数据量大概在两千万+，load了查不多两个小时，load完成后search超时

**Comment by xiaofan-luan** [comment]
hi @hf185 , any search success, or you keep receiving exception after fail?
what kind of disk you are using? seems it's slow so the timetick sync is also really slow.
any detailed logs for all the components.

**Comment by hf185** [comment]
> hi @hf185 , any search success, or you keep receiving exception after fail? what kind of disk you are using? seems it's slow so the timetick sync is also really slow. any detailed logs for all the components.

1. 第一次load后search超时，然后再次load后搜索倒是有响应了，但是每次load时间都在2H+
2. SATA 6Gb/s-7.2K
3. 日志文件太大了，需要哪个时间段的日志呢？

**Comment by xiaofan-luan** [comment]
Better to use english for other non-chinese spearker's concenience~ thanks.
Did you build index on top of the collection? how many nodes do you have and what is the hardware config?
If no index is built I'm not sure how long does a 20m vector search will cost, but with index should be done in a few seconds or so.

**Comment by hf185** [comment]
> Better to use english for other non-chinese spearker's concenience~ thanks. Did you build index on top of the collection? how many nodes do you have and what is the hardware config? If no index is built I'm not sure how long does a 20m vector search will cost, but with index should be done in a few seconds or so.

The index is created.

Hardware Configuration
- CPU: 16core * 2 (32 cores 64 threads)
- Memory: 256G
- Hard Disk: 2000GB-SATA 6Gb/s-7.2K *2 (4T)

**Comment by xiaofan-luan** [comment]
if index creation is done then that looks weird. could you please offer proxy logs and querynode logs?

**Comment by xiaofan-luan** [comment]
also, what is the topK?

**Comment by hf185** [comment]
> if index creation is done then that looks weird. could you please offer proxy logs and querynode logs?

Last night until now, the server's 3.5 T disks have been used up, and now the container has been shut down, and the logs can no longer be exported. I am very curious about what can occupy so many disks. The rc8 used before the ga version has never appeared over this phenomenon

**Comment by hf185** [comment]
How much disk space does 10 million pieces of data occupy?

**Comment by xiaofan-luan** [comment]
> How much disk space does 10 million pieces of data occupy?

based on dimension, for 128 dim float it should take 10-30G I guess~

**Comment by hf185** [comment]
> based on dimension, for 128 dim float it should take 10-30G I guess~

Now 2000W data occupies 3.3 T disks, is it a bug in the ga version?

![ca3f04987a0dfa87833dca1815f2009](https://user-images.githubusercontent.com/43991218/149859776-ccb9c0e8-a413-43b7-8dbd-02a381e7f5d1.png)

**Comment by xiaofan-luan** [comment]
that looks weird, did you do any drop collection operation frequently?
also which directory occupies most of the data? even if 3 replicas it should around hundred gigabytes.

**Comment by xiaofan-luan** [comment]
and did you count entities and make sure there are only 20m vectors?

**Comment by hf185** [comment]
> and did you count entities and make sure there are only 20m vectors?

Yes, only about 20 million

**Comment by hf185** [comment]
@xiaofan-luan 
![image](https://user-images.githubusercontent.com/43991218/149880026-28ac4c5a-785e-45bc-b586-47aa60ae5491.png)

**Comment by xiaofan-luan** [comment]
pulsar and etcd looks find? any details about minio? maybe there are some tools to check minio per bucket

**Comment by hf185** [comment]
> pulsar and etcd looks find? any details about minio? maybe there are some tools to check minio per bucket

The container has been downed by my colleague, and now I can't get the log, but I'm sure rc8 has never had this problem, the same amount of data

**Comment by xiaofan-luan** [comment]
yep, if we know which directory occupies data then we can do some investigation on that

**Comment by xiaofan-luan** [comment]
better to have datanode and datacoord log, big thanks !

**Comment by xiaofan-luan** [comment]
hi @hf185, any progress?

**Comment by hf185** [comment]
> hi @hf185, any progress?

I can't get the docker log now, sorry

**Comment by xiaofan-luan** [comment]
sure, no worries. If the issue can be reproduced please let us know
