### ISSUE TITLE
Config `preload_table` cannot be set to '*'

### ISSUE THREAD

**Issue by BossZou** [milvus-io/milvus#1524]
**Describe the bug**
I want to reload all tables existed into memory cache when server start, so I change config `preload_table` as '*' in config file. However, I restart server and error occurred.

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation
  from source
- Milvus version 
  v0.7.0
- Branch
  master
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**
![preload](https://user-images.githubusercontent.com/40255591/75986681-7fc2eb80-5f29-11ea-9dab-1f9676eb8cb8.png)

**Additional context**

**Comment by cydrain** [comment]
"*" need single-quote or double-quote
