### ISSUE TITLE
[Feature]: How to get the subsequent results of the same vector

### ISSUE THREAD

**Issue by herryzhang** [milvus-io/milvus#15240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

search_param = {"nprobe": 1024, 'metric_type': MetricType.L2}
param = {'collection_name': collection_name,
         'query_records': [feat],
         'top_k': 10,
         'params': search_param, }
status, results = milvus.search(**param)

My Milvis is 1.1.1,I use the code above to get the result 1-10,
the question is how do I get the result of this vector 11-20

**Comment by xiaofan-luan** [comment]
Hi herry, we don't support pagination for now, you will have to specify top 20 to query again.

**Comment by xiaofan-luan** [comment]
and that is a very tough question to solve, anyone else hit the same issue?

**Comment by herryzhang** [comment]
thanks

**Comment by yanliang567** [comment]
@herryzhang close if you have no more questions
