### ISSUE TITLE
Improve the WAL settings

### ISSUE THREAD

**Issue by JinHai-CN** [milvus-io/milvus#1527]
**Is your feature request related to a problem? Please describe.**
Currently, WAL path must be configured. In fact, WAL path can be with primary data path by default.

**Describe the solution you'd like**
Just add the primary data path as the WAL path.

**Comment by yamasite** [comment]
@JinHai-CN Does that mean we will remove `wal_path` from `server_config.yaml`?

**Comment by JinHai-CN** [comment]
Done.
