### ISSUE TITLE
[Bug]: QueryNodeStatsMsg doesn't have consumer 

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#15278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

statsService will always produce QueryNodeStatsMsg to the producer,  but none to consume which may cause fill pulsar storage completely.

### Anything else?

Remove code about QueryNodeStatsMsg.

**Comment by xige-16** [comment]
@jaime0815 Because stateChannel has no consumers for the time being, first cancel the logic of querynode sending state message.

**Comment by bigsheeper** [comment]
keep this issue open, I'll remove the entire statsService after GA

**Comment by xiaofan-luan** [comment]
keep tracking
