### ISSUE TITLE
[Enhancement]: Supports format checking for search parameters

### ISSUE THREAD

**Issue by xige-16** [milvus-io/milvus#15294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

when search params is not correct, sdk or proxy should return error immediately.

### Why is this needed?

when search with params:
```
     search_param = {
                    "data": [[random.random() for _ in range(dim)] for _ in range(5)],
                    "anns_field": "embeedings",
                    "param": {"metric_type": "L2"},
                    "limit": 2}
```

the error returned is confused:
```
Error: <BaseException: (code=1, message=no Available QueryNode result, filter reason [UnexpectedError] Assert "adapter->CheckSearch(conf, index_type, field_indexing->indexing_->index_mode())" at /home/xge/milvus/internal/core/src/query/SearchOnSealed.cpp:109
 => [SearchOnSealed]Search params check failed
```

**Comment by xige-16** [comment]
link : https://github.com/milvus-io/milvus/issues/15139#issuecomment-1016042991

**Comment by xiaofan-luan** [comment]
should fix this issue, very important to user experience

**Comment by xiaofan-luan** [comment]
Anyone interested pls help on this issue
