### ISSUE TITLE
[Bug]: There are not need for QueryNode creating  timetick channel's producer for every flowgraph

### ISSUE THREAD

**Issue by xige-16** [milvus-io/milvus#15295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

querynode create a msgstream for every flowgraphTimeTickNode, and create an useless producer.

### Expected Behavior

timetick channel is no longer needed

**Comment by xiaofan-luan** [comment]
close this issue since it's fixed by #15296
