### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by rocke-dong** [milvus-io/milvus#15299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.0.0-pre-ga
- Deployment mode(standalone or cluster): standalone 
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.0.0rc9, python 3.8
- OS(Ubuntu or CentOS): Ubuntu 20.04
- CPU/Memory: 8  Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz / 32G
- GPU: Tesla T4, 15G
- Others:
```

### Current Behavior

When I insert pandas data with vectors. The vector dimension size is 7621 and whoe length is 28482, there is error:
Addr [localhost:19530] bulk_insert
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.RESOURCE_EXHAUSTED
	details = "grpc: received message larger than max (868385309 vs. 536870912)"
	debug_error_string = "{"created":"@1642578750.170973039","description":"Error received from peer ipv6:[::1]:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"grpc: received message larger than max (868385309 vs. 536870912)","grpc_status":8}"
>
	{'API start': '2022-01-19 07:51:55.475559', 'RPC start': '2022-01-19 07:51:55.475980', 'RPC error': '2022-01-19 07:52:30.269679'}

Error details: 
python3.8/site-packages/pymilvus/orm/collection.py:544, in Collection.insert(self, data, partition_name, timeout, **kwargs)
    542 conn = self._get_connection()
    543 entities = Prepare.prepare_insert_data(data, self._schema)
--> 544 res = conn.insert(collection_name=self._name, entities=entities, ids=None,
    545                   partition_name=partition_name, timeout=timeout, **kwargs)
    546 if kwargs.get("_async", False):
    547     return MutationFuture(res)

python3.8/site-packages/pymilvus/client/stub.py:48, in retry_on_rpc_failure.<locals>.wrapper.<locals>.handler(self, *args, **kwargs)
     43 except grpc.RpcError as e:
     44     # DEADLINE_EXCEEDED means that the task wat not completed
     45     # UNAVAILABLE means that the service is not reachable currently
     46     # Reference: https://grpc.github.io/grpc/python/grpc.html#grpc-status-code
     47     if e.code() != grpc.StatusCode.DEADLINE_EXCEEDED and e.code() != grpc.StatusCode.UNAVAILABLE:
---> 48         raise e
     49     if not retry_on_deadline and e.code() == grpc.StatusCode.DEADLINE_EXCEEDED:
     50         raise e
     
...

python3.8/site-packages/grpc/_channel.py:744, in _MultiThreadedRendezvous.result(self, timeout)
    742     raise grpc.FutureCancelledError()
    743 else:
--> 744     raise self

_MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
    status = StatusCode.RESOURCE_EXHAUSTED
    details = "grpc: received message larger than max (868385309 vs. 536870912)"
    debug_error_string = "{"created":"@1642578750.170973039","description":"Error received from peer ipv6:[::1]:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"grpc: received message larger than max (868385309 vs. 536870912)","grpc_status":8}"

### Expected Behavior

When I insert vector data whose dimension size is 5000, there is ok.
Thanks very much in advance!!!

### Steps To Reproduce

```markdown
""" the Environment
- Milvus version: v2.0.0-pre-ga
- Deployment mode(standalone or cluster): standalone 
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.0.0rc9, python 3.8
- OS(Ubuntu or CentOS): Ubuntu 20.04
- CPU/Memory: 8  Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz / 32G
- GPU: Tesla T4, 15G
"""

from pymilvus import connections
from pymilvus import Collection
from pymilvus import CollectionSchema, FieldSchema, DataType
import pandas as pd
import random


connections.connect(alias="default", host='localhost', port='19530')
collection_name = "test_data"

uid = FieldSchema(
    name="uid", 
    dtype=DataType.INT64, 
    is_primary=True, 
    )
vector = FieldSchema(
    name="vector", 
    dtype=DataType.FLOAT_VECTOR, 
    dim=7621
    )
schema = CollectionSchema(
    fields=[uid, vector], 
    description="vector search"
    )

collection = Collection(name=collection_name, schema=schema, using='default', shards_num=2)

dim_size = 7621
length = 28482
data = pd.DataFrame(
    {
        "uid": list(range(length)),
        "vector": [[random.random() for _ in range(dim_size)] for _ in range(length)],
    }
)

batch1  = collection.insert(data)
```

**Comment by yanliang567** [comment]
@rocke-dong according to the error msg " details = "grpc: received message larger than max (868385309 vs. 536870912)", you inserted too much data in one insert request. Please try to insert less entities in one insert request. 
BTW, Milvus limits the max size as 512M for one grpc request and receive.

/assign @rocke-dong 
/unassign

**Comment by rocke-dong** [comment]
solved! thanks for your timely help, with your reminding, I split the date half and insert two timesly.
