### ISSUE TITLE
[Bug]: unable to start project

### ISSUE THREAD

**Issue by artisan867** [milvus-io/milvus#15339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 1.1.1
- Deployment mode(standalone or cluster): standalone 
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS):  centos7.8 2002
- CPU/Memory:  2 cores 4 threads 4GB (vmware)
- GPU: no
- Others:
```

### Current Behavior

I followed the steps of the official documentation and wanted to deploy it in my virtual machine for learning, but a brand new centos7.8 2002 could not be started, prompting that my configuration file was wrong.

The official document tells that it is the configuration document of 1.1.1. Why is the 0.5 version in the document?

Although I manually changed it to 1.1.1, it still cannot start

### Steps To Reproduce

```markdown
I looked at the documentation for this page：https://milvus.io/docs/v1.1.1/milvus_docker-cpu.md

The download address of the obtained configuration file：https://raw.githubusercontent.com/milvus-io/milvus/v1.1.1/core/conf/demo/server_config.yaml

Why is the page still showing version 0.5?
```

**Comment by artisan867** [comment]
my docker version is：Docker version 20.10.12, build e91ed57

thanks

**Comment by yanliang567** [comment]
@yhmo could you please help on this issue?
/assign @yhmo 
/unassign

**Comment by yhmo** [comment]
The "version: 0.5" is the config file version, not Milvus version. 0.5 is correct, no need to change it.

This page https://milvus.io/docs/v1.1.1/milvus_docker-cpu.md use this command to start milvus:

```
sudo docker run -d --name milvus_cpu_1.1.1 \
-p 19530:19530 \
-p 19121:19121 \
-v /home/$USER/milvus/db:/var/lib/milvus/db \
-v /home/$USER/milvus/conf:/var/lib/milvus/conf \
-v /home/$USER/milvus/logs:/var/lib/milvus/logs \
-v /home/$USER/milvus/wal:/var/lib/milvus/wal \
milvusdb/milvus:1.1.1-cpu-d061621-330cc6
```
You can remove the "-d" to see what error printed in the terminal:
```
sudo docker run --name milvus_cpu_1.1.1 \
-p 19530:19530 \
-p 19121:19121 \
-v /home/$USER/milvus/db:/var/lib/milvus/db \
-v /home/$USER/milvus/conf:/var/lib/milvus/conf \
-v /home/$USER/milvus/logs:/var/lib/milvus/logs \
-v /home/$USER/milvus/wal:/var/lib/milvus/wal \
milvusdb/milvus:1.1.1-cpu-d061621-330cc6
```
From the error we may know what problem it is.
