### ISSUE TITLE
[Bug]: There are always 2 growing segments even there are no more data inserted for hours

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#15344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220120-21f999f
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): rc10dev11
```

### Current Behavior

There are always 2 growing segments in querynode, even there are no more data inserted for hours.
After insert completed for 12+ hours, there are 2 segments still in growing
![image](https://user-images.githubusercontent.com/82361606/150632159-122bded5-2194-471c-bd2d-f875e22a5584.png)

### Expected Behavior

if there are no more data inserted, the growing segments shall be sealed after a few(10?) minutes.

### Steps To Reproduce

```markdown
1. Deploy Milvus cluster
2. create a collection 
3. build index  # index_params = {"index_type": "IVF_SQ8", "metric_type": "L2", "params": {"nlist": 64}}
4. collection.load
5. insert 10 million entities with 50,000 each batch

notes: do NOT manually call flush(collection.num_entities) during inserting
```

### Anything else?

After inserting completed:
![image](https://user-images.githubusercontent.com/82361606/150632121-ccee62a9-ac62-4db5-ae9c-3081ffa25811.png)

**Comment by xiaofan-luan** [comment]
this is by design~~ each channel has at least 1 growing segments waiting for new insertions.

**Comment by yanliang567** [comment]
> this is by design~~ each channel has at least 1 growing segments waiting for new insertions.

even after a few hours without any data inserted?

**Comment by xiaofan-luan** [comment]
yep, growing segments per shards is always there waiting for new insertions

**Comment by sunby** [comment]
The two growing segments will be flushed automatically after 24 hours by default. @yanliang567

**Comment by yanliang567** [comment]
Verified the 2 growing segments turn to sealed after 24+ hours.
