### ISSUE TITLE
[Bug]: [chaos] Datanode failed to restart after delete chaos memory stress

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#15368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220124-390cdd2
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The datanode OOMKilled because of the memory stress. After remove memory chaos, the datanode always CrashLoopBackOff.
```
mic-memory-etcd-0                                                 1/1     Running                      0          79m
mic-memory-etcd-1                                                 1/1     Running                      0          79m
mic-memory-etcd-2                                                 1/1     Running                      0          79m
mic-memory-milvus-datacoord-bf6b7b67-7bnrt                        1/1     Running                      0          77m
mic-memory-milvus-datanode-56d56b77df-64bj8                       0/1     CrashLoopBackOff             6          19m
mic-memory-milvus-indexcoord-7d6b96d59b-8f2kc                     1/1     Running                      0          77m
mic-memory-milvus-indexnode-56bb7cc745-pn8dl                      1/1     Running                      0          77m
mic-memory-milvus-proxy-c9c4d678b-l2xxs                           1/1     Running                      0          77m
mic-memory-milvus-querycoord-5f659d4b57-kmsww                     1/1     Running                      0          77m
mic-memory-milvus-querynode-76c5f5d95-q6j24                       1/1     Running                      0          77m
mic-memory-milvus-rootcoord-7ffcbd55cf-qglm4                      1/1     Running                      0          77m
mic-memory-minio-0                                                1/1     Running                      0          79m
mic-memory-minio-1                                                1/1     Running                      0          79m
mic-memory-minio-2                                                1/1     Running                      0          79m
mic-memory-minio-3                                                1/1     Running                      0          79m
mic-memory-pulsar-autorecovery-b7fd89f76-lsqhr                    1/1     Running                      0          79m
mic-memory-pulsar-bastion-6ffcc5dc48-rnhfx                        1/1     Running                      0          79m
mic-memory-pulsar-bookkeeper-0                                    1/1     Running                      0          79m
mic-memory-pulsar-bookkeeper-1                                    1/1     Running                      0          78m
mic-memory-pulsar-bookkeeper-2                                    1/1     Running                      0          77m
mic-memory-pulsar-broker-58b649fd4b-q7wtx                         1/1     Running                      0          79m
mic-memory-pulsar-proxy-6cffbff78d-ncsvb                          2/2     Running                      0          79m
mic-memory-pulsar-zookeeper-0                                     1/1     Running                      0          79m
mic-memory-pulsar-zookeeper-1                                     1/1     Running                      0          79m
mic-memory-pulsar-zookeeper-2                                     1/1     Running                      0          79m
```

Datanode log:
[datanode.log](https://github.com/milvus-io/milvus/files/7924822/datanode.log)
 

### Expected Behavior

After remove memory stress, datanode recover to running and insert data successfully

### Steps To Reproduce

```markdown
1. Deploy milvus cluster and limit datanode memory 1Gi
2. Insret 250,000 entities for 10 times (per time 25000)
3. Inject chaos memory stress
4. Insert 25000 entities again
5. The datanode oom killed and failed to restart
```

**Comment by XuanYang-cn** [comment]
@ThreadDao is this still a problem now?

/unassign
/unassign @sunby 
/assign @ThreadDao

**Comment by XuanYang-cn** [comment]
Actually, this's still a problem, DN didn't control its Memory status now.

**Comment by XuanYang-cn** [comment]
1. DataNode should be able to thrive in limited memory, for example, when memory >= 2G
2. DataNode should be able to restart properly when crashed

No.1 is still a problem because DataNode doesn't have memory related check, if dml channels are out of burden, DataNode will crash.

I'm not sure if No.2 is a problem now, @ThreadDao Please help to verify it.

**Comment by ThreadDao** [comment]
@XuanYang-cn Re-test your No.2 problem on image `master-20220523-246b22b5`
**Test steps:**
1. Limit datanode memory 1Gi
2. Create collection and insert some entities
3. Apply memory stress 
```
stressors:
    memory:
      workers: 4
      size: 1Gi
  duration: 4m
```
4. Insert 10,000 entities and flush

**Test results:**
The datanode is OOMKilled and restarted successfully, and flush data properly.

**Comment by ThreadDao** [comment]
@XuanYang-cn It crashed and failed to restart `master-20220523-246b22b5`
```
mic-memory-milvus-datanode-74456f9df-4lkx5      0/1     CrashLoopBackOff   11         3h19m
```
**Test steps:**
1. Limit datanode memory 1Gi
2. Create 2 collections with 4 shards
3. Insert entities into 2 collections through two clients at the same time
In summary, increasing the number of shards and collections makes the datanode run out of memory when inserting continuously. And then the datanode is OOMKilled and failed to restart.

[mic_logs.tar.gz](https://github.com/milvus-io/milvus/files/8754517/mic_logs.tar.gz)

The memory usage of datanode pod before crash:
![image](https://user-images.githubusercontent.com/27288593/169819608-5a804435-362b-43a1-aa99-c04c68b5083c.png)

**Comment by ThreadDao** [comment]
> @XuanYang-cn It crashed and failed to restart `master-20220523-246b22b5`
> 
> ```
> mic-memory-milvus-datanode-74456f9df-4lkx5      0/1     CrashLoopBackOff   11         3h19m
> ```
> 
> **Test steps:**
> 
> 1. Limit datanode memory 1Gi
> 2. Create 2 collections with 4 shards
> 3. Insert entities into 2 collections through two clients at the same time
>    In summary, increasing the number of shards and collections makes the datanode run out of memory when inserting continuously. And then the datanode is OOMKilled and failed to restart.
> 
> [mic_logs.tar.gz](https://github.com/milvus-io/milvus/files/8754517/mic_logs.tar.gz)
> 
> The memory usage of datanode pod before crash: ![image](https://user-images.githubusercontent.com/27288593/169819608-5a804435-362b-43a1-aa99-c04c68b5083c.png)

When I increased the memory limit of the querynode to 2Gi, the new datanode pod came up. The memory usage of new datanode is:
![image](https://user-images.githubusercontent.com/27288593/169823292-f7ca0329-e77c-4946-9a6f-99ba3e5c1368.png)

**Comment by ThreadDao** [comment]
When I increased the memory limit of the querynode to 2G, the new datanode pod gets running. the memory usage of new pod is:
![image](https://user-images.githubusercontent.com/27288593/169823774-6f951a29-383c-4e0b-906e-42641980a5c9.png)

**Comment by ThreadDao** [comment]
In my opinion, it is currently permissible if the node can restart successfully after increasing the memory limit.  Because now the datanode does not do the memory check work. I close
