### ISSUE TITLE
[Feature]: Add metrics for search,insert,delete qps, latency 

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#15364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

We need more metrics about DML latency, which including search,insert,delete.
For details, we should see latency histogram for each stage, for example e2e, proxy side, message queue,  per segment and during reduce.
This will help users to investigate on performance issues 。

**Comment by xiaofan-luan** [comment]
should be done since we update metrics

**Comment by Ceeton** [comment]
Regards
