### ISSUE TITLE
[Bug]: drop partition doesn't release memory from querynode

### ISSUE THREAD

**Issue by JamCrash** [milvus-io/milvus#15386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvus-dev:latest
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

when call partition.drop, the memory doesn't release from querynode automatically

**Comment by xiaofan-luan** [comment]
please try 2.0-GA and it should not longer a problem for now

**Comment by JamCrash** [comment]
My image is: milvusdb/milvus-dev:master-latest
It show it is build from master today.
Besides, after call partition.drop, collection.num_entities is not equal to the sum of each partition.num_entities

**Comment by xiaofan-luan** [comment]
umm, we need further investigation. Maybe you can take a deep look and try to understand? We probably need logs from QueryCoord and QueryNode to see why

collection.num_entities I guess would always be equal to entities in the table, no matter it load or released

**Comment by JamCrash** [comment]
![企业微信截图_16431123258082](https://user-images.githubusercontent.com/39126346/150974075-567dd0d9-ff72-4eab-b972-573f32412288.png)

**Comment by yanliang567** [comment]
> 

It is expected for now that collection.num_entities is not precise if it is called after  partition.drop or entities deletion. We are planing to refactor collection.num_entities to improve this.

**Comment by yanliang567** [comment]
@xiaofan-luan can you help to find someone to investigate the memory release issue?
/assign @xiaofan-luan 
/unassign

**Comment by xiaofan-luan** [comment]
/assign @godchen0212 
could you please take a look on this issue?

**Comment by godchen0212** [comment]
I'm working on this.

**Comment by JamCrash** [comment]
does this issue reproduce？ @godchen0212

**Comment by JamCrash** [comment]
another problem I found:
1. call collection.load() 2:call partition.release()
then the pymilvus2.0 shows: "pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=releasing some partitions after load collection is not supported)>"

the querycoord log:
[2022/01/28 04:27:50.803 +00:00] [DEBUG] [impl.go:541] ["releasePartitionRequest received"] [role=querycoord] [collectionID=430791114533109761] [partitionIDs="[430791114533109762]"] [msgID=430792233730723956]
[2022/01/28 04:27:50.803 +00:00] [WARN] [impl.go:580] ["releasePartitionsRequest failed"] [role=querycoord] [collectionID=430791114533109761] [partitionIDs="[430791114533109762]"] [msgID=430792233730723956] [error="releasing some partitions after load collection is not supported"]

**Comment by yanliang567** [comment]
> another problem I found:
> 
>     1. call collection.load()
> 
>     2. call partition.release()
>        then the pymilvus2.0 shows: "pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=releasing some partitions after load collection is not supported)>"
> 
> 
> the querycoord log: [2022/01/28 04:27:50.803 +00:00] [DEBUG] [impl.go:541] ["releasePartitionRequest received"] [role=querycoord] [collectionID=430791114533109761] [partitionIDs="[430791114533109762]"] [msgID=430792233730723956] [2022/01/28 04:27:50.803 +00:00] [WARN] [impl.go:580] ["releasePartitionsRequest failed"] [role=querycoord] [collectionID=430791114533109761] [partitionIDs="[430791114533109762]"] [msgID=430792233730723956] [error="releasing some partitions after load collection is not supported"]

yes, this is by design in 2.0. Now if you load the vectors by collection level, then you have to release them by collection level. If you load them by partition level, then you can release them by partition level or collection level.

**Comment by JamCrash** [comment]
> > another problem I found:
> > ```
> > 1. call collection.load()
> > 
> > 2. call partition.release()
> >    then the pymilvus2.0 shows: "pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=releasing some partitions after load collection is not supported)>"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > the querycoord log: [2022/01/28 04:27:50.803 +00:00] [DEBUG] [impl.go:541] ["releasePartitionRequest received"] [role=querycoord] [collectionID=430791114533109761] [partitionIDs="[430791114533109762]"] [msgID=430792233730723956] [2022/01/28 04:27:50.803 +00:00] [WARN] [impl.go:580] ["releasePartitionsRequest failed"] [role=querycoord] [collectionID=430791114533109761] [partitionIDs="[430791114533109762]"] [msgID=430792233730723956] [error="releasing some partitions after load collection is not supported"]
> 
> yes, this is by design in 2.0. Now if you load the vectors by collection level, then you have to release them by collection level. If you load them by partition level, then you can release them by partition level or collection level.

I think this design is not obvious and the document doesn't mention that...

**Comment by xiaofan-luan** [comment]
> > > another problem I found:
> > > ```
> > > 1. call collection.load()
> > > 
> > > 2. call partition.release()
> > >    then the pymilvus2.0 shows: "pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=releasing some partitions after load collection is not supported)>"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > the querycoord log: [2022/01/28 04:27:50.803 +00:00] [DEBUG] [impl.go:541] ["releasePartitionRequest received"] [role=querycoord] [collectionID=430791114533109761] [partitionIDs="[430791114533109762]"] [msgID=430792233730723956] [2022/01/28 04:27:50.803 +00:00] [WARN] [impl.go:580] ["releasePartitionsRequest failed"] [role=querycoord] [collectionID=430791114533109761] [partitionIDs="[430791114533109762]"] [msgID=430792233730723956] [error="releasing some partitions after load collection is not supported"]
> > 
> > 
> > yes, this is by design in 2.0. Now if you load the vectors by collection level, then you have to release them by collection level. If you load them by partition level, then you can release them by partition level or collection level.
> 
> I think this design is not obvious and the document doesn't mention that...

We just change the default behavior because the implementation of original design is too complicated.
Is there any specific case we want to use this feature? We will change the documentation ASAP'

@LocoRichard  could you please take a look

**Comment by JamCrash** [comment]
And I just found that if I call load by partition level in pymilvus:
par = Partition(collection, 'partition_0‘)
par.load()
then only one partition can be loaded, the other call such as: 
par = Partition(collection, 'partition_1'),
par.load()
will show: 
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=some partitions [430795893903196161] of collection 430791114533109761 has been loaded into QueryNode, please release partitions firstly)>
is it a bug or feature?

**Comment by JamCrash** [comment]
I think user need be able to load any part of collection(partition level),  include release and drop...

**Comment by xiaofan-luan** [comment]
> I think the user need able to load any part of collection(partition level), include release and drop...

If collection is not loaded, then you can load any of the partitions. But you can not load a collection and release 
some of the partitions

**Comment by xiaofan-luan** [comment]
Sorry for the convenience but it is due to some design complexity

**Comment by LocoRichard** [comment]
> > > > another problem I found:
> > > > ```
> > > > 1. call collection.load()
> > > > 
> > > > 2. call partition.release()
> > > >    then the pymilvus2.0 shows: "pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=releasing some partitions after load collection is not supported)>"
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > the querycoord log: [2022/01/28 04:27:50.803 +00:00] [DEBUG] [impl.go:541] ["releasePartitionRequest received"] [role=querycoord] [collectionID=430791114533109761] [partitionIDs="[430791114533109762]"] [msgID=430792233730723956] [2022/01/28 04:27:50.803 +00:00] [WARN] [impl.go:580] ["releasePartitionsRequest failed"] [role=querycoord] [collectionID=430791114533109761] [partitionIDs="[430791114533109762]"] [msgID=430792233730723956] [error="releasing some partitions after load collection is not supported"]
> > > 
> > > 
> > > yes, this is by design in 2.0. Now if you load the vectors by collection level, then you have to release them by collection level. If you load them by partition level, then you can release them by partition level or collection level.
> > 
> > 
> > I think this design is not obvious and the document doesn't mention that...
> 
> We just change the default behavior because the implementation of original design is too complicated. Is there any specific case we want to use this feature? We will change the documentation ASAP'
> 
> @LocoRichard could you please take a look

@xiaofan-luan Constraints have been added to documentation via https://github.com/milvus-io/milvus-docs/pull/1337

**Comment by chenwr727** [comment]
> I think the user need able to load any part of collection(partition level), include release and drop...

@xiaofan-luan Will this feature be developed in the future?

**Comment by xiaofan-luan** [comment]
> nvenience but it is due to some design complexity

Not in my mind~ 
Currently once you load partition A, you can load another partition B and the only way to do so if you release partition A and load partition A,B
We will add the feature to load partition in sequence and then we can implement a rule to load partition I guess
