### ISSUE TITLE
[Bug]: IP Calculation result is not correct

### ISSUE THREAD

**Issue by susoooon** [milvus-io/milvus#15398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.0rc9
- Deployment mode(standalone or cluster):windows
- SDK version(e.g. pymilvus v2.0.0rc2):2.0.0rc9
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

`

  import numpy as np
  from milvus_connect import create_collection,search_id,del_collection
  
  def normal(embedding):
      embedding = embedding/np.linalg.norm(embedding)
      embedding = embedding.tolist()[0]
      return embedding
  
  import random
  name = "repeat"
  entities = [[],[]]
  for i in range(10):
      a = [np.random.random(768)]
      a = np.asarray(a)
      a = normal(a)
      entities[0].append(i)
      entities[1].append(a)
  
  print(entities[1][0]) #一个768长度的列表
  sam = (np.asarray(entities[1][0])*np.asarray(entities[1][0])).sum()
  print(sam)
  sam = np.dot(np.asarray(entities[1][0]),np.asarray(entities[1][0]))
  print(sam)

#输出结果：1.0
#0.9999999999999998

repeat= create_collection(entities,name)#这里我根据name和entities创建了个collection

Z = entities[1][0]
print(entities[0][0])
result = search_id(name,Z)
print(result)

`
#输出结果["['(distance: 0.0, id: 0)', '(distance: 0.45950692892074585, id: 7)', '(distance: 0.4674335718154907, id: 5)']"]

### Expected Behavior

按照官网介绍在归一化后IP应该就等于余弦，但是很明显不是。我哪里做错了还是？

    #这个是查询代码
`
def search_id(name,vectors):

    repeat = Collection(name)      # Get an existing collection.
    repeat.load()

    search_params = {
        "metric_type": "L2",
        "params": {"nprobe": 10},
    }

    result = repeat.search([vectors], "embeddings", search_params, limit=3, output_fields=["id"])

    return result`
  #这里是建表代码
`
def create_collection(entities,name):

    fields = [
        FieldSchema(name="id", dtype=DataType.INT64, is_primary=True, auto_id=False),

        FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=768)
    ]
    schema = CollectionSchema(fields, "REPEAT field in relationship")
    repeat = Collection(name, schema)

    insert_result = repeat.insert(entities)
    # Builds indexes on the entities:

    index = {
        "index_type": "IVF_FLAT",
        "metric_type": "IP",
        "params": {"nlist": 128},
    }
    repeat.create_index("embeddings", index)

    return repeat
`

**Comment by yanliang567** [comment]
@yhmo could you please help on this issue?

/assign @yhmo 
/unassign

**Comment by xiaofan-luan** [comment]
please use English for the convenience of others, thanks

**Comment by susoooon** [comment]
=
