### ISSUE TITLE
[Bug]: Binary search with metric type "METRIC_L2" is not failed when nodes are sets as multiple replica 

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#15407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: latest
- Deployment mode(standalone or cluster):cluster with multiple replica
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc10.dev15
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

search is successful

### Expected Behavior

Search failed with error: "binary search not support metric type: METRIC_L2"

### Steps To Reproduce

```markdown
1 configure milvus with multiple replica(proxy.replicas=2 --set queryNode.replicas=2 --set indexNode.replicas=2 --set dataNode.replicas=2)

2 deploy milvus in cluster mode

3 Run test case:
testcases/test_search_20.py::TestCollectionSearchInvalid.test_search_binary_flat_with_L2
```

### Anything else?

It is good in standalone mode and cluster mode [not multiple replica]

**Comment by xiaofan-luan** [comment]
we definitely to add more test for multi nodes.
Current behaiour looks very crappy

**Comment by yanliang567** [comment]
@binbinlv is this still a valid issue for now?

**Comment by binbinlv** [comment]
@yanliang567 
yes, this issue still exists.

**Comment by binbinlv** [comment]
Keep open to be fixed.

**Comment by binbinlv** [comment]
Keep open to be fixed.
