### ISSUE TITLE
[Feature]: Add a pulsar  authentication options to milvus.

### ISSUE THREAD

**Issue by kingy123** [milvus-io/milvus#15415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

My company has pulsar clusters with JWT authentication,but, At present, Milvus does not support pulsar connection with authentication .

### Describe the solution you'd like.

add pulsar connection authentication options.

**Comment by xiaofan-luan** [comment]
Anyone interestet in take this feature?

**Comment by xiaofan-luan** [comment]
see also https://github.com/milvus-io/milvus/issues/7703
