### ISSUE TITLE
[Bug]: LoadCollection fails on newly installed Milvus 2.0

### ISSUE THREAD

**Issue by robfig** [milvus-io/milvus#15429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): v2.0
- OS(Ubuntu or CentOS): ContainerOS
- CPU/Memory: n1-standard-4
- GPU: 1 x Tesla T4 per node
- Others: Deployed on GKE
```

### Current Behavior

I followed these instructions to set up Milvus Cluster using the Milvus Operator on GKE. 
https://milvus.io/docs/v2.0.0/install_cluster-milvusoperator.md

It started up successfully. I loaded about 64k vectors, and wanted to search them. To do that, I need to LoadCollection. I attempted that many times over a period of hours, and it always fails. I've attached logs that I could find from milvus proxy, querycoord, and querynode. The logs show that the server is indeed failing to load the collection, but there are no errors that indicate what the cause could be. I looked at the source code indicated by one of the stack traces (e.g. github.com/milvus-io/milvus/internal/querynode/impl.go:238), but the trace seems to bottom out in a generic spot, not specific to whatever the underlying failure is. 

Logs:
https://gist.github.com/robfig/e1283ed4cd8454b3c5002266597b1d28

### Expected Behavior

LoadCollection should succeed or ideally fail with a descriptive error about why it is unable to do so.

### Steps To Reproduce

Described in Current Behavior. 

The dataset is proprietary, so I can not share it. I have not tried to reproduce with an open source data set.

**Comment by yanliang567** [comment]
I saw an error from querycoord: 
```
[2022/01/28 02:10:17.289 +00:00] [DEBUG] [cluster.go:277] ["watchDmChannels: queryNode watch dm channel error"] [error="collection hasn't been loaded or has been released, collection id = 430787472968908801"]
[2022/01/28 02:10:17.289 +00:00] [WARN] [task.go:1253] ["watchDmChannelTask: watchDmChannel occur error"] [taskID=430786247858585633]
[2022/01/28 02:10:17.289 +00:00] [DEBUG] [task.go:1264] ["watchDmChannelTask postExecute done"] [taskID=430786247858585633]
[2022/01/28 02:10:17.289 +00:00] [DEBUG] [task_scheduler.go:812] ["waitActivateTaskDone: activate task return err"] [taskID=430786247858585633] [triggerTaskID=430786247858585631] [error="collection hasn't been loaded or has been released, collection id = 430787472968908801"]
[2022/01/28 02:10:17.289 +00:00] [DEBUG] [task_scheduler.go:784] ["waitActivateTaskDone: retry the active task"] [taskID=430786247858585633] [triggerTaskID=430786247858585631]
```
could you please check the milvus pods status, and also the pulsar, etcd pods staus?

/assign @robfig 
/unassign

**Comment by xiaofan-luan** [comment]
@robfig hi Rob, there seems to be some wrong state there, maybe you can try to reboot querynode see if it recovers

**Comment by xiaofan-luan** [comment]
@rob hi rob, did it recover after reboot quernode?
seems that querynode don't have the meta infomation, so watchDML channel request keeps to fail, need to followup more about the details.

**Comment by ranjancse26** [comment]
MilvusException: <MilvusException: (code=1, message=checkIfLoaded failed when search, collection:question_answer, partitions:[], err = GetCollectionInfo failed, collection = question_answer, err = collection 441197464922203706 has not been loaded to memory or load failed)>

This is happening on the Milvus hosted cloud too.

**Comment by xiaofan-luan** [comment]
> MilvusException: <MilvusException: (code=1, message=checkIfLoaded failed when search, collection:question_answer, partitions:[], err = GetCollectionInfo failed, collection = question_answer, err = collection 441197464922203706 has not been loaded to memory or load failed)>
> 
> This is happening on the Milvus hosted cloud too.

Did you tried to load collection before search? usually this is what you do:
create collection
create index
load the collection

**Comment by ranjancse26** [comment]
Thanks it worked after loading the collection. My apologies for not knowing.
