### ISSUE TITLE
[Enhancement]: Restrict each rpc request to 64M rather than 512M

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#15421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

We would like to change grpc request to 64M, and Msgs written into message queue to 1 M.

### Why is this needed?

That would helps the stability of message storage, as well as control the memory usage of proxy itself

**Comment by xiaofan-luan** [comment]
anyone could give me some thoughts about it?

**Comment by XuanYang-cn** [comment]
Should we consider about search results? What If a user asks for limit 100k. That's one RPC response from SDK to the server.

**Comment by xiaofan-luan** [comment]
> Should we consider about search results? What If a user asks for limit 100k. That's one RPC response from SDK to the server.

we remove the response channel and the dependency should be grpc limit, so far I feel it is ok but it would be better if we have pagination and we can reduce it to a smaller value

**Comment by XuanYang-cn** [comment]
Search requests are still using channels, and channels also have a req limit of 100MB for now(5MB in default by Pulsar), are we planning to passing search requests through RPC too?

**Comment by XuanYang-cn** [comment]
For high dimension vectors and large TopK cases, 64MB could end up with very low throughput.

For vectors of dimension 512, 64MB can only contain 64 * 1024 *1024/(512 * 4) = 32 * 1024 , approximately 32,000 number of rows.

Which means  at most nq * Topk = 32000, if the user asks for Topk 1000, the total throughput would be 32 vectors per RPC.

To ensure high throughput as well as a good performance, SDK or users will have to make more RPCs concurrently, and QueryNode needs the ability to handle search requests concurrently.

**Comment by xiaofan-luan** [comment]
> and QueryNode needs the ability to handle search requests concurrently.

Agree, QueryNode need to handle search requests concurrently.
Based on your calculation I thought 64M is a little bit smaller, 512M might be a reasonable limit.
Any other suggestions? change the message size into DML to 1M might be still a work to do

**Comment by xiaofan-luan** [comment]
We decided to leave the limitation as 512M for now
