### ISSUE TITLE
[Bug]: Search Freezes On 10 Million Vectors

### ISSUE THREAD

**Issue by Kencho5** [milvus-io/milvus#15438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.0
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: i7 9700k/16GB
- GPU: 2x RTX 3060
- Others:
```

### Current Behavior

inserting and searching works as expected. i insert 512 dimensional vectors inside Milvus and create **IVF_SQ8** index on vectors (index is created before inserting). searching works fast and returns correct results until total vectors inside database reach around 10 million. after it reaches 10 million it freezes forever. 

i create index using:
```python
collection.create_index(field_name="vector",
                        index_params={'index_type': 'IVF_SQ8',
                                      'metric_type': 'L2',
                                      'params': {
                                        'nlist': 100      # int. 1~65536
                                      }})
collection.load()
```

search parameters:
```python
search_param = {
                "data": query_vectors,
                "anns_field": "vector",
                "param": {"metric_type": "L2", "params": {"nprobe": 8}},
                "limit": 5}
query_results = collection.search(**search_param)
```
traceback when i cancel when it freezes searching:
```
Traceback (most recent call last):
  File "search.py", line 41, in <module>
    query_results = collection.search(**search_param)
  File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 697, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/decorators.py", line 21, in handler
    return func(self, *args, **kwargs)
  File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 444, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 379, in _execute_search_requests
    response = ft.result()
  File "/home/kencho/.local/lib/python3.8/site-packages/grpc/_channel.py", line 733, in result
    timed_out = _common.wait(self._state.condition.wait,
  File "/home/kencho/.local/lib/python3.8/site-packages/grpc/_common.py", line 141, in wait
    _wait_once(wait_fn, MAXIMUM_WAIT_TIMEOUT, spin_cb)
  File "/home/kencho/.local/lib/python3.8/site-packages/grpc/_common.py", line 106, in _wait_once
    wait_fn(timeout=timeout)
  File "/usr/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
```

### Expected Behavior

before reaching 10 million vectors everything works, after reaching 10 million it doesn't. why could that be or how is that even not working?

**Comment by xiaofan-luan** [comment]
@Kencho5 hi kencho~ could you please check the memory utilization, see if you have enough memory(especially for querynode)

If memory is enough, please offer logs of querynode, querycoord and proxy and we will investigate on that

**Comment by Kencho5** [comment]
i checked memory when searching and i doesn't go past 13gb (i have 16gb). i'm having trouble finding those logs of querynode, querycoord and proxy

**Comment by yanliang567** [comment]
@Kencho5 could you please help to upload the logs of standalone pod? 
BTW, 10 million 512d vectors would be about 20GB, so memory utilization could be the first thing we need to check.

**Comment by Kencho5** [comment]
yes i understand it's big, but how come it works perfectly on 9 million and fails on 10? even after checking it doesn't go past 13 gb. after checking logs with `docker container logs -f {container-id}` i get huge logs that are not stopping. this is one of them: 
`[2022/01/29 06:07:20.801 +00:00] [ERROR] [root_coord.go:1389] ["DescribeCollection failed"] [role=rootcoord] ["collection name"=] [msgID=0] [error="can't find collection id : 430719403382276097"] [stack="github.com/milvus-io/milvus/internal/rootcoord.(*Core).DescribeCollection\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:1389\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).DescribeCollection\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:354\ngithub.com/milvus-io/milvus/internal/proto/rootcoordpb._RootCoord_DescribeCollection_Handler.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proto/rootcoordpb/root_coord.pb.go:915\ngithub.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38\ngithub.com/milvus-io/milvus/internal/proto/rootcoordpb._RootCoord_DescribeCollection_Handler\n\t/go/src/github.com/milvus-io/milvus/internal/proto/rootcoordpb/root_coord.pb.go:917\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934"]`

**Comment by Kencho5** [comment]
i deleted the database, re inserted vectors and now on 9,403,595 million vectors the search gets frozen forever and `drop_collection()` gets frozen forever too. any ideas how to fix this? i plan on using Milvus for production, but i can't get it to finish

**Comment by Kencho5** [comment]
also, `index_building_progress()` prints: `{'total_rows': 9403595, 'indexed_rows': 9403595}` so i really don't understand the issue here

**Comment by xiaofan-luan** [comment]
> i deleted the database, re inserted vectors and now on 9,403,595 million vectors the search gets frozen forever and `drop_collection()` gets frozen forever too. any ideas how to fix this? i plan on using Milvus for production, but i can't get it to finish

Did you check the memory consumpltion and there is enough memory? 
It seems that index_building_progress is done but the collection can not be loaded.
For detailed infomation please upload you logs of proxy, rootcoord, querycoord, querynode, thanks

**Comment by Kencho5** [comment]
i did check the memory consumption both on my machine and in docker too. nothing was limiting me there. how or where can i find logs of proxy, rootcoord, querycoord, querynode? since `drop_collection()` is being frozen forever i was guessing maybe the cause is corrupt files?

**Comment by Kencho5** [comment]
i did check the memory consumption both on my machine and in docker too. nothing was limiting me there. how or where can i find logs of proxy, rootcoord, querycoord, querynode? since `drop_collection()` is being frozen forever i was guessing maybe the cause is corrupt files?

**Comment by Kencho5** [comment]
i have trouble finding the logs and checking if collection is loaded. i tried `loading_progress()` and it outputted this:
```
RPC error: [get_query_segment_info], <BaseException: (code=1, message=getSegmentInfo: queryNode 21 is offline)>, <Time:{'RPC start': '2022-02-04 17:02:19.424617', 'RPC error': '2022-02-04 17:02:19.426594'}>
RPC error: [load_collection_progress], <BaseException: (code=1, message=getSegmentInfo: queryNode 21 is offline)>, <Time:{'RPC start': '2022-02-04 17:02:19.424609', 'RPC error': '2022-02-04 17:02:19.426681'}>
Traceback (most recent call last):
  File "count.py", line 7, in <module>
    print(milvus.loading_progress(collection_name))
  File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/orm/utility.py", line 196, in loading_progress
    return _get_connection(using).load_collection_progress(collection_name)
  File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 666, in load_collection_progress
    self.get_query_segment_info(collection_name, timeout))
  File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 455, in get_query_segment_info
    raise BaseException(status.error_code, status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=getSegmentInfo: queryNode 21 is offline)>

```
i hope this is what you were asking me for

**Comment by xiaofan-luan** [comment]
> i have trouble finding the logs and checking if collection is loaded. i tried `loading_progress()` and it outputted this:
> 
> ```
> RPC error: [get_query_segment_info], <BaseException: (code=1, message=getSegmentInfo: queryNode 21 is offline)>, <Time:{'RPC start': '2022-02-04 17:02:19.424617', 'RPC error': '2022-02-04 17:02:19.426594'}>
> RPC error: [load_collection_progress], <BaseException: (code=1, message=getSegmentInfo: queryNode 21 is offline)>, <Time:{'RPC start': '2022-02-04 17:02:19.424609', 'RPC error': '2022-02-04 17:02:19.426681'}>
> Traceback (most recent call last):
>   File "count.py", line 7, in <module>
>     print(milvus.loading_progress(collection_name))
>   File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/orm/utility.py", line 196, in loading_progress
>     return _get_connection(using).load_collection_progress(collection_name)
>   File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
>     raise e
>   File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
>     return func(self, *args, **kwargs)
>   File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
>     raise e
>   File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
>     return func(*args, **kwargs)
>   File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 666, in load_collection_progress
>     self.get_query_segment_info(collection_name, timeout))
>   File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
>     raise e
>   File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
>     return func(self, *args, **kwargs)
>   File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
>     raise e
>   File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
>     return func(*args, **kwargs)
>   File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 455, in get_query_segment_info
>     raise BaseException(status.error_code, status.reason)
> pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=getSegmentInfo: queryNode 21 is offline)>
> ```
> 
> i hope this is what you were asking me for

seems that querynode is crashing. Any reason why collecting logs failed?

**Comment by Kencho5** [comment]
i just don’t know where to get other logs. that was the only thing i could find and weird that the querynode crashes on 10 million and worked on 9.6 million

**Comment by Kencho5** [comment]
8.3 million vectors in and takes 7GB of ram. i also put another ram stick in temporarily to check if that was actually the problem, but it still crashes. querynode was still offline

**Comment by pmoreirac** [comment]
I've been having a similar issue. Indexing 7 different collections with 50.000 vectors each and after ~120 batches of 50.000 vector searches, Milvus becomes unresponsive solely for search instructions.

## Environment
```
- Milvus version: 1.1.1
- SDK version: pymilvus 1.1.2
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: Intel Xeon E5-2690 v4/112 GB 
- GPU: NVIDIA Tesla V100 16GB
```
## Current Behavior
Inserting and searching works successfully, for the uploaded collections, containing 768 dimensional vectors indexed with HNSW

Index creation:
```
    def create_index(self, collection_name):
        index_type = IndexType.HNSW
        params = {
            "M": 4,
            "efConstruction": 8

        }
        self.milvus_client.create_index(collection_name,
                                        index_type=index_type,
                                        params=params)
```
Search parameters:
```
    def __init__(self, host, port, batch_size, ef):
        self.milvus_client = Milvus(host=host, port=port)
        self.batch_size = batch_size
        self.search_params = {
            'ef': ef
        }

    def find_products(self, queries: List[List[float]], collection_name: str, top_k):
        result_ids = []

        status, res = self.milvus_client.search(
            collection_name,
            top_k,
            queries,
            params=self.search_params,
            timeout=0.3
        )
```

**Comment by Kencho5** [comment]
check if collection is loaded. when you run the docker container monitor the resources it’s taking, it takes quite some time. when it stabilizes and doesn’t use cpu in high percentage then try to search again

**Comment by yanliang567** [comment]
> I've been having a similar issue. Indexing 7 different collections with 50.000 vectors each and after ~120 batches of 50.000 vector searches, Milvus becomes unresponsive solely for search instructions.
> ## Environment
> 
> ```
> - Milvus version: 1.1.1
> - SDK version: pymilvus 1.1.2
> - OS(Ubuntu or CentOS): Ubuntu
> - CPU/Memory: Intel Xeon E5-2690 v4/112 GB 
> - GPU: NVIDIA Tesla V100 16GB
> ```
> 
> ## Current Behavior
> 
> Inserting and searching works successfully, for the uploaded collections, containing 768 dimensional vectors indexed with HNSW
> 
> Index creation:
> 
> ```
>     def create_index(self, collection_name):
>         index_type = IndexType.HNSW
>         params = {
>             "M": 4,
>             "efConstruction": 8
> 
>         }
>         self.milvus_client.create_index(collection_name,
>                                         index_type=index_type,
>                                         params=params)
> ```
> 
> Search parameters:
> 
> ```
>     def __init__(self, host, port, batch_size, ef):
>         self.milvus_client = Milvus(host=host, port=port)
>         self.batch_size = batch_size
>         self.search_params = {
>             'ef': ef
>         }
> 
>     def find_products(self, queries: List[List[float]], collection_name: str, top_k):
>         result_ids = []
> 
>         status, res = self.milvus_client.search(
>             collection_name,
>             top_k,
>             queries,
>             params=self.search_params,
>             timeout=0.3
>         )
> ```

@pmoreirac if you are running on Milvus 1.x, you need to file a new ticket. This one is about Milvus 2.0.
