### ISSUE TITLE
[Enhancement]: Improve the collection load performance

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#15445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

We've seen many user report for the load performance. Need to figure out:
1) what is the bottleneck of load, CPU, disk or just the software?
2)Anyway to improve it, add more concurrency? better disk? or less copy?
3)Figure out if there is a way to do lazy load.

### Why is this needed?

By improving the load performance, we will see the system more user friendly and moreover the system recovery speed should be much faster.

**Comment by divyanshugit** [comment]
Hi, Can you please assign me this issue?

**Comment by xiaofan-luan** [comment]
@divyanshugit hi div~ welcome to the community!

**Comment by xiaofan-luan** [comment]
feel free to contact me at github or slack for more information

**Comment by xiaofan-luan** [comment]
close and let's take discussion there
