### ISSUE TITLE
[Bug]: search has been timeouted

### ISSUE THREAD

**Issue by scipe** [milvus-io/milvus#15449]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: Latest in the helm, so 2.0
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): latest, doesn’t matter
- CPU/Memory: a lot of
- GPU: 0
- Others: etcd has been upgraded to latest version
```

### Current Behavior

When I do search I got no results and timeout error

### Expected Behavior

When I do search I should got results instead timeout

### Steps To Reproduce

```markdown
1. Helm on AWS EKS cluster
2. Upgraded etcd latest version
3. Query nodes has own node pool with huge memory instance type (controlled by twins and tolerations)
4. I have 4 fields in my schema: ID (not auto inc), vector 512 dim float, 1 field with int64 and one more field with int64
```

### Anything else?

I got the timeout in attu UI and in nodejs lib. 

Here is my copy of messages from slack thread:

> Hi @yhmo. I got some troubles with by search query. I trying to find any logs regarding to that, but not sure with what I have to start checking. I though it should be querycoord pod but I can not find anything related to my search query there. So the question for now where I can see the error why my search query has been timeouted?

> The latest milvus helm version for k8s. Clustered. 1.5M test dataset. 3 fields: 512 dim vector, and two int64 fields. Trying to search in both ways: just with vectors and just by metadata. All of them has been timeouted

> Okaayy so I found some logs in proxy:
> - Query enqueued
> - Query PreExecute done
> - Query Execute done
> But on Attu front-end I still doesnt have any results.. Like timeouted

> Also I see something like: when I am trying to do search query from nodejs api
`[2022/02/04 17:06:22.898 +00:00] [DEBUG] [time_recorder.go:78] ["proxy execute search 430963038662950989: send search msg to message stream (5ms)"]
[2022/02/04 17:06:22.898 +00:00] [DEBUG] [time_recorder.go:78] ["proxy execute search 430963038662950989: done (5ms)"] `

**Comment by yanliang567** [comment]
@scipe thank you for your issue. Could you please also upload the milvus logs, especially for query nodes, quer coordinator and proxy? Moreover, it would be helpful if you can also upload etcd and pulsar logs for investigation.

/assign @scipe 
/unassign

**Comment by scipe** [comment]
Hi folks. I will provide the whole footprint soon.

**Comment by scipe** [comment]
Here is logs: https://pastebin.com/ue8sXy54
Attached a screenshot with search request
As a results a got timeout.
![Screenshot 2022-02-07 at 15 50 15](https://user-images.githubusercontent.com/3996622/152791353-0bf36b03-a148-49a0-932f-4a6baf72f138.png)

**Comment by scipe** [comment]
feel free to contact with me in slack @yanliang567

**Comment by scipe** [comment]
I did also next things for testing:
- Scale down querynode 2 => 1
- Trying to search for empty collection
But got the same timeout on endpoint

**Comment by scipe** [comment]
The same timeout I see if going to collection => data (without search by vectors) in ATTU.

**Comment by yanliang567** [comment]
@xige-16 could you please help on this issue?
/assign @xige-16 
/unassign @scipe

**Comment by scipe** [comment]
Hey folks! Any news? How can I help you? 

I am thinking to try to do search in collection without any metadata..

**Comment by xige-16** [comment]
It seems querynode's service time is much smaller than the guranee time, which may be the service time has been pushed too slowly or has stoped advancing, and more querynode logs are needed to analyze the issue. @scipe 
```
 [2022/02/07 12:47:44.513 +00:00] [DEBUG] [query_collection.go:337] ["check if query timeout"] [collectionID=430960041038184449] [msgID=430963507544981668] [TimeoutTs=0] [curTime=431027143183695872] [timeoutTsPhysical=1970/01/01 00:00:00.000 +00:00] [curTimePhysical=2022/02/07 12:47:44.513 +00:00]
[2022/02/07 12:47:44.513 +00:00] [DEBUG] [query_collection.go:521] ["query node::receiveQueryMsg: add to unsolvedMsg"] [collectionID=430960041038184449] [sm.GuaranteeTimestamp=2022/02/07 12:47:44.466 +00:00] [serviceTime=2022/02/04 17:24:34.666 +00:00] ["delta seconds"=63593] [msgID=430963507544981668] [msgType=search]

```

**Comment by xige-16** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```gfm
> - Milvus version: Latest in the helm, so 2.0
> - Deployment mode(standalone or cluster): cluster
> - SDK version(e.g. pymilvus v2.0.0rc2): latest, doesn’t matter
> - CPU/Memory: a lot of
> - GPU: 0
> - Others: etcd has been upgraded to latest version
> ```
> 
> ### Current Behavior
> When I do search I got no results and timeout error
> 
> ### Expected Behavior
> When I do search I should got results instead timeout
> 
> ### Steps To Reproduce
> ```gfm
> 1. Helm on AWS EKS cluster
> 2. Upgraded etcd latest version
> 3. Query nodes has own node pool with huge memory instance type (controlled by twins and tolerations)
> 4. I have 4 fields in my schema: ID (not auto inc), vector 512 dim float, 1 field with int64 and one more field with int64
> ```
> 
> ### Anything else?
> I got the timeout in attu UI and in nodejs lib.
> 
> Here is my copy of messages from slack thread:
> 
> > Hi @yhmo. I got some troubles with by search query. I trying to find any logs regarding to that, but not sure with what I have to start checking. I though it should be querycoord pod but I can not find anything related to my search query there. So the question for now where I can see the error why my search query has been timeouted?
> 
> > The latest milvus helm version for k8s. Clustered. 1.5M test dataset. 3 fields: 512 dim vector, and two int64 fields. Trying to search in both ways: just with vectors and just by metadata. All of them has been timeouted
> 
> > Okaayy so I found some logs in proxy:
> > 
> > * Query enqueued
> > * Query PreExecute done
> > * Query Execute done
> >   But on Attu front-end I still doesnt have any results.. Like timeouted
> 
> > Also I see something like: when I am trying to do search query from nodejs api
> > `[2022/02/04 17:06:22.898 +00:00] [DEBUG] [time_recorder.go:78] ["proxy execute search 430963038662950989: send search msg to message stream (5ms)"] [2022/02/04 17:06:22.898 +00:00] [DEBUG] [time_recorder.go:78] ["proxy execute search 430963038662950989: done (5ms)"] `

This proxy log only indicates that proxy successfully sent a search request to querynode, but that proxy did not receive search result

**Comment by xige-16** [comment]
> It seems querynode's service time is much smaller than the guranee time, which may be the service time has been pushed too slowly or has stoped advancing, and more querynode logs are needed to analyze the issue. @scipe
> 
> ```
>  [2022/02/07 12:47:44.513 +00:00] [DEBUG] [query_collection.go:337] ["check if query timeout"] [collectionID=430960041038184449] [msgID=430963507544981668] [TimeoutTs=0] [curTime=431027143183695872] [timeoutTsPhysical=1970/01/01 00:00:00.000 +00:00] [curTimePhysical=2022/02/07 12:47:44.513 +00:00]
> [2022/02/07 12:47:44.513 +00:00] [DEBUG] [query_collection.go:521] ["query node::receiveQueryMsg: add to unsolvedMsg"] [collectionID=430960041038184449] [sm.GuaranteeTimestamp=2022/02/07 12:47:44.466 +00:00] [serviceTime=2022/02/04 17:24:34.666 +00:00] ["delta seconds"=63593] [msgID=430963507544981668] [msgType=search]
> ```

Within the search req timeout range, search req times will time out if the querynode's service time cannot be updated to be greater than the gurante time

**Comment by scipe** [comment]
Here is logs (I did one search request in the end)
[milvus-querynode-8db48f769-9xbmd.log](https://github.com/milvus-io/milvus/files/8031560/milvus-querynode-8db48f769-9xbmd.log)

**Comment by xiaofan-luan** [comment]
the log is partial, but we've seen at least two issues:
1) Time tick stucked for at least two days, to get more logs there is a faq about how to enable logs at https://milvus.io/docs/v2.0.0/operational_faq.md 
2) field bin logs load seems to keep loading path=insert_log/430960041038184449/430960041038184450/430960612918427649/101/430960787204866050

**Comment by scipe** [comment]
1. Yeah, so as I understand logs right now just a stdout. Server already running for 4 days. So you want to see logs right from server start? Maybe I can restart the pod and give you fresh logs?
2. Not sure what I am understand what is that. I am not insertings anything right now.

**Comment by xiaofan-luan** [comment]
> 1. Yeah, so as I understand logs right now just a stdout. Server already running for 4 days. So you want to see logs right from server start? Maybe I can restart the pod and give you fresh logs?
> 2. Not sure what I am understand what is that. I am not insertings anything right now.

Sure, it would be great if you redirect the log and restart the cluster so we can collect the full log

**Comment by scipe** [comment]
here is fresh logs
[milvus-querynode-8db48f769-9xbmd.log](https://github.com/milvus-io/milvus/files/8032579/milvus-querynode-8db48f769-9xbmd.log)

**Comment by xiaofan-luan** [comment]
> here is fresh logs [milvus-querynode-8db48f769-9xbmd.log](https://github.com/milvus-io/milvus/files/8032579/milvus-querynode-8db48f769-9xbmd.log)

seems that current querynode has weird error logs, does search still stuck?

**Comment by scipe** [comment]
yeah same timeout

**Comment by xiaofan-luan** [comment]
> yeah same timeout. updated logs after I did search: [milvus-querynode-8db48f769-9xbmd.log](https://github.com/milvus-io/milvus/files/8032632/milvus-querynode-8db48f769-9xbmd.log)

I thought I got the reason, there seems to be a bad performance bottleneck when search and get original vector .
I will fix it soon.

There are a few temporary solutoons:
1) don't include vector field when search.
2) If you have ssd, you can use local ssd as a cache .

add config:
localStorage.Path = ssd location
localStorage.enabled = true

**Comment by xiaofan-luan** [comment]
localStorage.Path need to set to a fast storage , default path is /var/lib/milvus/data/

**Comment by scipe** [comment]
Okay I know what you mean. You mean not "do not search by vectors", you mean do not have that original vector in search results?

**Comment by scipe** [comment]
like the same before

**Comment by scipe** [comment]
Okay so when I trying to do search from "ATTU => Collection => DataQuery" I see in the output_fields my embedding vector field. So `[DEBUG] [segment.go:383] [FillVectorFieldData]` this row means that system trying to get original vector from file?

Regarding to logs for query without embedding field let me try to do that one more time

**Comment by scipe** [comment]
[milvus-querynode-8db48f769-9xbmd.log](https://github.com/milvus-io/milvus/files/8034237/milvus-querynode-8db48f769-9xbmd.log)
[milvus-proxy-7dd4dd6d86-qvrv9.log](https://github.com/milvus-io/milvus/files/8034238/milvus-proxy-7dd4dd6d86-qvrv9.log)

**Comment by xiaofan-luan** [comment]
> Okay so when I trying to do search from "ATTU => Collection => DataQuery" I see in the output_fields my embedding vector field. So `[DEBUG] [segment.go:383] [FillVectorFieldData]` this row means that system trying to get original vector from file?
> 
> Regarding to logs for query without embedding field let me try to do that one more time

The original file is in Minio, and for fast retrieval we put original vector into local disk, and FillVectorFieldData means retrieve vector field from local disk

**Comment by scipe** [comment]
Okay in my case it's S3.

**Comment by xiaofan-luan** [comment]
it should be cached at  /var/lib/milvus/data/ directory on the quernode

**Comment by scipe** [comment]
@xiaofan-luan after I restart querynode one more time and did search (without searching with vector field) I got results..

**Comment by xiaofan-luan** [comment]
from your logs offered I didn't see any weird logs, everything seems to be working but querynode didn't receive request from proxy. @xige-16 any other comments?

**Comment by scipe** [comment]
Do you wanna access to my cluster? It's created only for testing, no production data and etc.

**Comment by scipe** [comment]
Okay. So always when I try to do search from Data Query (attu UI with includes original vector) - I will never get answer from api. But after I restart the whole pod and waiting init - search is works

**Comment by xige-16** [comment]
> the log is partial, but we've seen at least two issues:
> 
> 1. Time tick stucked for at least two days, to get more logs there is a faq about how to enable logs at https://milvus.io/docs/v2.0.0/operational_faq.md
> 2. field bin logs load seems to keep loading path=insert_log/430960041038184449/430960041038184450/430960612918427649/101/430960787204866050

The log was printed when querynode handled query request, and  the number of logs is equal to the number of rows of the query result.

**Comment by xige-16** [comment]
> 

Now search does not support returning the original vector, the SDK will throw the wrong
```
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=search doesn't support vector field as output_fields)
```

**Comment by scipe** [comment]
@xige-16 dont forget about attu. They still using that field in Data Query from collection admin ui.

**Comment by xige-16** [comment]
> still using that field in Data Query from

Okay, thx~
