### ISSUE TITLE
[Bug]: Collection.delete() expression  cannot use '=='

### ISSUE THREAD

**Issue by excited-tiger** [milvus-io/milvus#15457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.0.0
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):v2.0.0
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

<img width="901" alt="image" src="https://user-images.githubusercontent.com/44421536/152739152-002372b4-9326-4335-ba73-e353564d3a73.png">

### Steps To Reproduce

```markdown
Collection.delete()
it worked with " in [ids,]"
```

**Comment by yanliang567** [comment]
@excited-tiger this is by design, we think using 'in' has a wider usage than '==', and it is easy to use 'in' as a replacement of '=='

**Comment by xiaofan-luan** [comment]
> @excited-tiger this is by design, we think using 'in' has a wider usage than '==', and it is easy to use 'in' as a replacement of '=='

should we also support ==?
