### ISSUE TITLE
[Feature Request]:   delete entities using "<" and more express

### ISSUE THREAD

**Issue by JamCrash** [milvus-io/milvus#15458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:  GA
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.0
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=invalid plan node type)>

**Comment by JackLCL** [comment]
- Milvus version: 
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:


@JamCrash Please provide this info to help us investigate your problem.

**Comment by yanliang567** [comment]
@JamCrash for now, this is by design. please use 'in' instead.

/assign @JamCrash 
/unassign

**Comment by JamCrash** [comment]
so how to delete data using travel timestamp?

**Comment by yanliang567** [comment]
> so how to delete data using travel timestamp?

not quite sure what you want to do here? could you please share  the code snippet or more details about the scenarios you meet?

**Comment by JamCrash** [comment]
there always have new data insert in the milvus in production environment, and some latest vectors which are useless should be deleted, so I should get the ids(auto id) or something else(timestamp) about the useless vectors, what should I do for this task?
(it's better if the milvus has vector expire function)

**Comment by yanliang567** [comment]
> there always have new data inserted in the milvus in production environment, and some latest vectors which are useless should be deleted, so I should get the ids(auto id) or something else(timestamp) about the useless vectors(In the meantime, I don't know which vectors are oldest) @yanliang567 (it's better if the milvus has vector expire function)

@JamCrash sounds reasonable
@xiaofan-luan do we have any plan to enhance this feature, to support more express in delete and query operations?

**Comment by xiaofan-luan** [comment]
> > there always have new data inserted in the milvus in production environment, and some latest vectors which are useless should be deleted, so I should get the ids(auto id) or something else(timestamp) about the useless vectors(In the meantime, I don't know which vectors are oldest) @yanliang567 (it's better if the milvus has vector expire function)
> 
> @JamCrash sounds reasonable @xiaofan-luan do we have any plan to enhance this feature, to support more express in delete and query operations?

We won't support delete with expression because it may cause scan whole collection and takes very long.
For optional solution:
1) query with expression and delete with ids.
2) support a compaction expire plugin which can implement user logic to expire entities

**Comment by xiaofan-luan** [comment]
We now support expire data by timestamp, we should probably extend this feature in the future
