### ISSUE TITLE
[Bug]: AttributeError: 'Partition' object has no attribute '_partition_name'

### ISSUE THREAD

**Issue by excited-tiger** [milvus-io/milvus#15456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvusdb/milvus:v2.0.0
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2): v2.0.0
- OS(Ubuntu or CentOS): MAC OS
- CPU/Memory: M1 max, 32G
- GPU: 
- Others:
```

### Current Behavior

when i use `Partition.delete(expr)`,
> AttributeError: 'Partition' object has no attribute '_partition_name'

### Expected Behavior

deleted 

### Anything else?

# 1 setp

1. connect to Milvus
2. create collection
3. create index
4. create partition

```python

#!/usr/bin/env python
# coding: utf-8

# In[ ]:


from pymilvus import connections

# 1. connect to Milvus
connections.connect("default", host="192.168.10.177", port="19530")


# In[13]:


from pymilvus import FieldSchema, DataType, CollectionSchema, Collection

# 2. create collection
# We're going to create a collection with 3 fields.
# +-+------------+------------+------------------+------------------------------+
# | | field name | field type | other attributes |       field description      |
# +-+------------+------------+------------------+------------------------------+
# |1|    "pk"    |    Int64   |  is_primary=True |      "primary field"         |
# | |            |            |   auto_id=False  |                              |
# +-+------------+------------+------------------+------------------------------+
# |2|  "random"  |    Double  |                  |      "a double field"        |
# +-+------------+------------+------------------+------------------------------+
# |3|"embeddings"| FloatVector|     dim=8        |  "float vector with dim 8"   |
# +-+------------+------------+------------------+------------------------------+
fields = [
    FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, auto_id=False),
    FieldSchema(name="random", dtype=DataType.DOUBLE),
    FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=8)
]

schema = CollectionSchema(fields, "hello_milvus is the simplest demo to introduce the APIs")
hello_milvus = Collection("hello_milvus", schema, consistency_level="Strong")


# In[14]:


# 3. create index
index = {
    "index_type": "IVF_FLAT",
    "metric_type": "L2",
    "params": {
        "nlist": 128
    },
}

hello_milvus.create_index("embeddings", index)


# In[15]:


# 4. create partition
partition_name = 'partition_test'
if not hello_milvus.has_partition(partition_name):  # 按组划分
    hello_milvus.create_partition(partition_name)
milvus_partition = hello_milvus.partition(partition_name)

```

5. insert data
6. query entities

```python

import random

# 5. insert data
print("Start inserting entities")
num_entities = 3000
entities = [
    # provide the pk field because `auto_id` is set to False
    [i for i in range(num_entities)],
    [float(random.randrange(-20, -10)) for _ in range(num_entities)],  # field random
    [[random.random() for _ in range(8)] for _ in range(num_entities)],  # field embeddings
]

insert_result = milvus_partition.insert(entities)

print(f"Number of entities in Milvus: {milvus_partition.num_entities}")  # check the num_entities


# query entities
hello_milvus.load()
ids = insert_result.primary_keys
expr = f"pk in [{ids[0]}, {ids[1]}]"
print(f"Start deleting with expr `{expr}`")

result = milvus_partition.query(expr=expr, output_fields=["random", "embeddings"])
print(f"query before delete by expr=`{expr}` -> result: \n-{result[0]}\n-{result[1]}\n")
```

# 2 error occured

`milvus_partition.delete(expr)`

> AttributeError                            Traceback (most recent call last)
> /var/folders/wk/53fk1p_572919jy_czfk1v9c0000gn/T/ipykernel_29002/1070627151.py in <module>
>       1 # delete
> ----> 2 milvus_partition.delete(expr)
>
> ~/miniconda3/envs/py397/lib/python3.9/site-packages/pymilvus/orm/partition.py in delete(self, expr, timeout, **kwargs)
>     327         conn = self._get_connection()
>     328         res = conn.delete(collection_name=self._collection.name, expr=expr,
> --> 329                           partition_name=self._partition_name, timeout=timeout, **kwargs)
>     330         if kwargs.get("_async", False):
>     331             return MutationFuture(res)
>
> AttributeError: 'Partition' object has no attribute '_partition_name'

# 3 temporary solutions

`hello_milvus.delete(expr,partition_name=partition_name)`

it worked with that:
**Collection.delete(expr, partition_name=partition_name)**

**Comment by xiaofan-luan** [comment]
if you has only one partition, why not directly use collection.delete?

**Comment by xiaofan-luan** [comment]
however, that seems to be a bug, we should complete with default partition if user didn't fill?

**Comment by excited-tiger** [comment]
> however, that seems to be a bug, we should complete with default partition if user didn't fill?

ok

**Comment by XuanYang-cn** [comment]
@excited-tiger  Thanks for pointing it out, `partition.delete` is fixed on pymilvus==2.0.1.dev3 on testpypi, will be released along with pymilvus2.0.1.

`delete` works exactly the same on the Collection level and Partition level, so don't worry about the correctness.

**Comment by XuanYang-cn** [comment]
> however, that seems to be a bug, we should complete with default partition if user didn't fill?

It's a SDK bug, already fixed

**Comment by yanliang567** [comment]
/assign @huangjincheng2022 
@huangjincheng2022 could you please help to add some tests for this fix?
