### ISSUE TITLE
[Enhancement]: Upgrade 1.x collection test cases: （test_collection.py)

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#15469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Modify the 1.x test cases in the following classes in test_collection.py using 2.0 interface:

class class TestCollectionCount
class TestCollectionCountIP
class TestCollectionCountBinary
class TestCollectionMultiCollections
class TestGetCollectionStats
class TestCreateCollection
class TestCreateCollectionInvalid(object)
class TestDescribeCollection:
class TestDescribeCollectionInvalid(object)
class TestDropCollection
class TestDropCollectionInvalid(object)
class TestHasCollection
class TestHasCollectionInvalid(object)
class TestListCollections
class TestLoadCollection
class TestReleaseAdvanced
class TestLoadCollectionInvalid(object)
class TestLoadPartition
class TestLoadPartitionInvalid(object)

**Comment by binbinlv** [comment]
please keep track of each modification on this issue, for example:
TestLoadPartitionInvalid::test_load_partition_with_invalid_partition_name -> class::test_case_name
TestLoadPartitionInvalid::test_load_partition_with_invalid_partition_name Deleted

**Comment by huangjincheng2022** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>



trace case | Delete note
-- | --
TestCollectionCount:test_count_without_connection Deleted | not supported in 2.0 interface
TestCollectionCount:test_collection_count_no_vectors Updated |  
TestCollectionCountIP:test_collection_count_after_index_created Updated |  
TestCollectionCountBinary:test_collection_count_after_index_created_A Updated |  
TestCollectionCountBinary:test_collection_count_no_entities Updated |  
TestCollectionMultiCollections:test_collection_count_multi_collections_l2 Updated |  
TestCollectionMultiCollections:test_collection_count_multi_collections_binary Updated |  
TestCollectionMultiCollections:test_collection_count_multi_collections_mix Updated |  
TestGetCollectionStats:test_get_collection_stats_name_not_existed Deleted | not supported in 2.0 interface
TestGetCollectionStats:test_get_collection_stats_name_invalid Deleted | not supported in 2.0 interface
TestGetCollectionStats:test_get_collection_stats_name_not_existed Deleted | not supported in 2.0 interface
TestGetCollectionStats:test_get_collection_stats_empty Deleted | not supported in 2.0 interface
TestGetCollectionStats:test_get_collection_stats_without_connection Deleted | not supported in 2.0 interface
TestGetCollectionStats:test_get_collection_stats_name_batch Deleted | not supported in 2.0 interface
TestGetCollectionStats:test_get_collection_stats_name_not_existed Deleted | not supported in 2.0 interface
TestGetCollectionStats:test_get_collection_stats_single Deleted | not supported in 2.0 interface
TestGetCollectionStats:test_get_collection_stats_after_delete Deleted | not supported in 2.0 interface
TestGetCollectionStats:test_get_collection_stats_after_compact_parts Deleted | not supported in 2.0 interface
TestGetCollectionStats:test_get_collection_stats_after_compact_delete_one Deleted | not supported in 2.0 interface
TestGetCollectionStats:test_get_collection_stats_partition Deleted | not supported in 2.0 interface
TestGetCollectionStats:test_get_collection_stats_partitions Deleted | not supported in 2.0 interface
TestGetCollectionStats:test_get_collection_stats_partitions_A Deleted | not supported in 2.0 interface
TestGetCollectionStats:test_get_collection_stats_partitions_B Deleted | not supported in 2.0 interface
TestGetCollectionStats:test_get_collection_stats_partitions_C Deleted | not supported in 2.0 interface
TestGetCollectionStats:test_get_collection_stats_partitions_D Deleted | not supported in 2.0 interface
TestGetCollectionStats:test_get_collection_stats_after_index_created Deleted | not supported in 2.0 interface
TestGetCollectionStats:test_get_collection_stats_after_index_created_ipDeleted | not supported in 2.0 interface
TestGetCollectionStats:test_get_collection_stats_after_index_created_jac Deleted | not supported in 2.0 interface
TestGetCollectionStats:test_get_collection_stats_after_create_different_index Deleted | not supported in 2.0 interface
TestGetCollectionStats:test_collection_count_multi_collections_indexed Deleted | not supported in 2.0 interface
TestCreateCollection:_test_create_collection_segment_row_limit Deleted | not supported in 2.0 interface
TestCreateCollection:test_create_collection_after_insert_flush Deleted | not supported in 2.0 interface
TestCreateCollection:test_create_collection_multithread Updated |  
TestCreateCollectionInvalid:_test_create_collection_with_invalid_segment_row_limit Delete | deprecated case
TestCreateCollectionInvalid:_test_create_collection_no_segment_row_limit Delete | deprecated case
TestCreateCollectionInvalid:test_create_collection_limit_fields updated |  
TestDescribeCollection:test_collection_fields Deleted | not supported in 2.0 interface
TestDescribeCollection:test_describe_collection_after_index_created Deleted | not supported in 2.0 interface
TestDescribeCollection:test_describe_collection_without_connection Deleted | not supported in 2.0 interface
TestDescribeCollection:test_describe_collection_not_existed Deleted | not supported in 2.0 interface
TestDescribeCollection:test_describe_collection_multithread Deleted | not supported in 2.0 interface
TestDescribeCollection:test_describe_collection_fields_after_insert Deleted | not supported in 2.0 interface
TestDescribeCollectionInvalid:test_describe_collection_with_invalid_collection_name Deleted | not supported in 2.0 interface
TestDescribeCollectionInvalid:test_describe_collection_with_empty_or_None_collection_name Deleted | not supported in 2.0 interface
TestDropCollection:test_drop_collection_A Updated |  
TestDropCollection:test_drop_collection_without_connection Updated |  
TestDropCollection:test_drop_collection_not_existed Updated |  
TestDropCollection:test_create_drop_collection_multithread Updated |  
TestDropCollectionInvalid:test_drop_collection_with_invalid_collection_name Updated |  
TestDropCollectionInvalid:test_drop_collection_with_empty_or_None_collection_name Updated |  
TestHasCollection:test_has_collection_without_connection Updated |  
TestHasCollection:test_has_collection_not_existed Updated |  
TestHasCollection:test_has_collection_multithread Updated |  
TestHasCollectionInvalid:test_has_collection_with_invalid_collection_name Updated |  
TestHasCollectionInvalid:test_has_collection_with_empty_collection_name Updated |  
TestHasCollectionInvalid:test_has_collection_with_none_collection_name Updated |  
TestListCollections:test_list_collections_multi_collections Updated |  
TestListCollections:test_list_collections_without_connection Updated |  
TestListCollections:test_list_collections_no_collection Deleted | Duplicated case
TestListCollections:test_list_collections_multithread Updated |  
TestLoadCollection:test_load_collection_after_index Updated |  
TestLoadCollection:test_load_collection_after_index_binary Updated |  
TestLoadCollection:test_load_empty_collection Updated |  
TestLoadCollection:test_load_collection_dis_connect Updated |  
TestLoadCollection:test_release_collection_dis_connect Updated |  
TestLoadCollection:test_load_collection_not_existed Updated |  
TestLoadCollection:test_release_collection_not_existed Updated |  
TestLoadCollection:test_release_collection_not_load Updated |  
TestLoadCollection:test_load_collection_after_load_release Updated |  
TestLoadCollection:test_load_collection_repeatedly Updated |  
TestLoadCollection:test_load_release_collection Updated |  
TestLoadCollection:test_release_collection_after_drop Updated |  
TestLoadCollection:test_load_collection_without_flush Delete | not supported in 2.0 interface
TestLoadCollection:_test_load_collection_larger_than_memory Delete | deprecated case
TestLoadCollection:test_load_partitions_release_collection Updated |  
TestReleaseAdvanced:test_release_collection_during_searching Updated |  
TestReleaseAdvanced:test_release_partition_during_searching Updated |  
TestReleaseAdvanced:test_release_collection_during_searching_A Updated |  
TestLoadCollection:_test_release_collection_during_loading Delete | deprecated case
TestLoadCollection:_test_release_partition_during_loading Delete | deprecated case
TestLoadCollection:_test_release_collection_during_loading Delete | deprecated case
TestLoadCollection:_test_release_collection_during_inserting Delete | deprecated case
TestLoadCollection:_test_release_collection_during_indexing Delete | deprecated case
TestLoadCollection:_test_release_collection_during_droping_index Delete | deprecated case
TestLoadCollectionInvalid:test_load_collection_with_invalid_collection_name Delete | not supported in 2.0 interface
TestLoadCollectionInvalid:test_release_collection_with_invalid_collection_name Delete | not supported in 2.0 interface
TestLoadPartition:test_load_partition_after_index_binary Updated |  
TestLoadPartition:test_load_partition_dis_connect Updated |  
TestLoadPartition:test_load_partition_after_index_binary Updated |  
TestLoadPartition:test_release_partition_dis_connect Updated |  
TestLoadPartition:test_load_partition_not_existed Updated |  
TestLoadPartition:test_release_partition_not_load Updated |  
TestLoadPartition:test_load_release_after_drop Updated |  
TestLoadPartition:test_load_release_after_collection_drop Updated |  
TestLoadPartitionInvalid:test_load_partition_with_invalid_partition_name Updated |  
TestLoadPartitionInvalid:test_release_partition_with_invalid_partition_name Updated |  



</body>

</html>
