### ISSUE TITLE
[Bug]:Missing version information of PyMilvus sdk on milvus website Hello Milvus page

### ISSUE THREAD

**Issue by huangjincheng2022** [milvus-io/milvus#15478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:N/A
- Deployment mode(standalone or cluster):N/A
- SDK version(e.g. pymilvus v2.0.0rc2):N/A
- OS(Ubuntu or CentOS): N/A
- CPU/Memory: N/A
- GPU: N/A
- Others: N/A
```

### Current Behavior

 Missing version information of PyMilvus sdk on the Hello Milvus Page. there might be an optimization for it.

### Expected Behavior

Complete version information of PyMilvus SDK.

### Steps To Reproduce

```markdown
https://milvus.io/docs/v2.0.0/example_code.md
```

**Comment by yanliang567** [comment]
I agree that we need a reminder for users of installing/updating pymilvus to latest version, or the hello_milvus code might return errors.

@LocoRichard 
/assign @LocoRichard 
/unassign

**Comment by LocoRichard** [comment]
@huangjincheng2022  @yanliang567 
Fixed via https://github.com/milvus-io/milvus-docs/pull/1344
Good to be closed
