### ISSUE TITLE
[Feature]: Support multiple values for a field

### ISSUE THREAD

**Issue by alturkovic** [milvus-io/milvus#15519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

It would be great if multiple values could be added to a field, something like Pinecones list of values for metadata filtering.

### Describe the solution you'd like.

Add multiple values for a field and search/filter by those values.

**Comment by xiaofan-luan** [comment]
hi @alturkovic ,so by saying multiple values, do you mean structures like list or set?

**Comment by alturkovic** [comment]
Exactly, [Pinecone](https://www.pinecone.io/docs/metadata-filtering/#adding-metadata-in-pinecone-indexes) supports adding multiple values in the metadata which combined with upsert (I saw that upserts are coming to Milvus also) simplifies our use case a lot and enables us to simply "append" values in the list if they already exist, or create a new entity otherwise. This allows us to have only one vector entity and keep track of all "relationships" it has. We can ask for similarity by a relationship (asking if a value is present in list) or globally (no filtering by list).

**Comment by xiaofan-luan** [comment]
> Exactly, [Pinecone](https://www.pinecone.io/docs/metadata-filtering/#adding-metadata-in-pinecone-indexes) supports adding multiple values in the metadata which combined with upsert (I saw that upserts are coming to Milvus also) simplifies our use case a lot and enables us to simply "append" values in the list if they already exist, or create a new entity otherwise. This allows us to have only one vector entity and keep track of all "relationships" it has. We can ask for similarity by a relationship (asking if a value is present in list) or globally (no filtering by list).
> 
> By relationships, I mean a list of external identifiers from our MongoDB database for an example.

Gotcha, we will first support string as our priority since you can always serialize your list into a JSON string if you'd like to.
In the next few release we will add list/set and other data structure support.

Keep this issue open for now

**Comment by xiaofan-luan** [comment]
keep it open~ We want to support it in the need future
