### ISSUE TITLE
 How to set the search parameters for different data sets，if index type is ivf_pq?

### ISSUE THREAD

**Issue by shengjh** [milvus-io/milvus#1551]
**What is your question?**
Currently i have three datasets(sift,glove,kosarak)， and i want to test the performance of searching vectors after building ivf_pq index.  Here are the different vector dimensions for these three datasets.
1. sift_128_euclidean: each vector is 128 dimension
2. glove_200_angular: each vector is 200 dimension,  about 1.18 millions rows
3. kosarak table, binary data: each vector is 27984 dimension, about 1 millions
Is there have any suggestions about how to set search parameters?

**Comment by tinkerlin** [comment]
### SIFT 128

IVF Flat/SQ

- Build Params: { nlist: 16384 }
- Search Params:  nprobe  = [ 1, nlist ]

IVFPQ 

- Build Params: { m: 64 } // Other parameters are the same as above
- Search Params: ...

HNSW 

- Build Params: { M: 24, efConstructor: 500 }
- Search Params:  ef =  [ k, 4096 ] 

NSG 

- Build Params: { knng: 50, out_degree: 50, candidate_pool_size =300, search_length = 50 }
- Search Params: search_length = [ 20, 500 ]

**Comment by tinkerlin** [comment]
### GLOVE 200

IVF Flat/SQ

- Build Params: { nlist: 8192 }
- Search Params:  nprobe  = [ 1, nlist ]

IVFPQ 

- Build Params: { m: 20 } // Other parameters are the same as above
- Search Params: ...

HNSW 

- Build Params: { M: 48, efConstructor: 500 }
- Search Params:  ef =  [ k, 4096 ]

**Comment by tinkerlin** [comment]
### kosarak table

IVF Flat/SQ

- Build Params: { nlist: 2048 }
- Search Params:  nprobe  = [ 1, nlist ]

HNSW

- Build Params: { M: 48, efConstructor: 500 }
- Search Params:  ef =  [ k, 4096 ]

**Comment by JinHai-CN** [comment]
Done.
