### ISSUE TITLE
[Bug]: Search may miss some segments if a compaction complete during the search

### ISSUE THREAD

**Issue by sunby** [milvus-io/milvus#15524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.0.0
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Imagine a case, there are 2 querynode(querynode1 and querynode2). The segment1 is on querynode1 and a search request sent at timestamp t10. At this moment, a compaction (segment1 and segment2 merge to segment3) happen and segment3 is on querynode2. When the search request received on querynode2, the timetick has reached to t11 (t11>t10) and the search will see segment1 on querynode1. When the search request received on querynode1, the timetick has reached to t8 (t8<t10) and the search will be put to a queue to wait the timetick to reach t10. Now querynode1 will release segment1 and see segment3 is on querynode2. Then the search is done on querynode1 and it will not see segment1 on querynode1. So the data of segment1 is missed in this search request.

### Expected Behavior

Dont miss data during search

### Steps To Reproduce

```markdown
It's a corner case that is hard to reproduce.
```

**Comment by xiaofan-luan** [comment]
this may still b a issue so keep it open
