### ISSUE TITLE
[Bug]: collection 431107821927399425 has not been loaded to memory or load failed

### ISSUE THREAD

**Issue by skye95git** [milvus-io/milvus#15538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.0
- Deployment mode(standalone or cluster): standalone 
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0
- OS(Ubuntu or CentOS): Ubuntu 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I deal with 43,827 pieces of data and load connection before search, I see the error message attached below:
```
pymilvus.client.grpc_handler - Error: <BaseException: (code=1, message=collection 431107821927399425 has not been loaded to memory or load failed)>
```

But when I deal with 2,048 pieces of data, It can be loaded Successfully. 

Does Milvus have a place for memory caps? Do I need to change the memory limit of Milvus in the configuration file?

### Expected Behavior

I can Ioad the connnection Successfully.

### Steps To Reproduce

```markdown
1. connect: 
connections.connect(host='localhost', port='19530')


2. Create collection
TABLE_NAME = "test_4"
function_id = FieldSchema(name="id", dtype=DataType.INT64, is_primary=True, auto_id=True)
function = FieldSchema(name="function", dtype=DataType.FLOAT_VECTOR, dim=768)
schema = CollectionSchema(fields=[function_id, function], description="codesearch collection")
collection = Collection(name=TABLE_NAME, schema=schema)


3. Create Index
index_param = {
        "metric_type":"L2",
        "index_type":"IVF_SQ8",
        "params":{"nlist":1024}
    }
collection.create_index(field_name="function", index_params=index_param) 


4. Insert data(in our case 43,827 entries)
embeddings = normalize(embeddings)   
em =list(embeddings)
mr = collection.insert([em])  


5. Load data
search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
collection.load()
```

**Comment by xiaofan-luan** [comment]
might be the same issue as #15429, we've already fixed issues and will be released on next week.
To solve this issue temporarily, you can call num_entities before load and it will trigger a internal flush which would solve the issue

**Comment by skye95git** [comment]
> call num_entities

Thanks. How to call num_entities?

**Comment by zhuwenxing** [comment]
> > call num_entities
> 
> Thanks. How to call num_entities?

collection.num_entities

**Comment by yanliang567** [comment]
@skye95git please feel free to LMK if it does not work for you.

**Comment by skye95git** [comment]
> might be the same issue as #15429, we've already fixed issues and will be released on next week. To solve this issue temporarily, you can call num_entities before load and it will trigger a internal flush which would solve the issue

When you release, give me a reply, thank you!

**Comment by skye95git** [comment]
> @skye95git please feel free to LMK if it does not work for you.

It works normally after adding `collection.num_entities` before load, thank you!

**Comment by skye95git** [comment]
Among the results returned by vector search, is the smaller the distance, the more similar？

If yes, why is the larger the distance in the text search demo example, the more similar it is?
<img width="814" alt="微信图片_20220214175918" src="https://user-images.githubusercontent.com/41561936/153842137-e77436f3-e627-4ea1-b5c3-eceeaa68cb8d.png">

**Comment by yanliang567** [comment]
> Among the results returned by vector search, is the smaller the distance, the more similar？
> 
> If yes, why is the larger the distance in the text search demo example, the more similar it is? <img alt="微信图片_20220214175918" width="814" src="https://user-images.githubusercontent.com/41561936/153842137-e77436f3-e627-4ea1-b5c3-eceeaa68cb8d.png">

it depends on the definition of distance, it is the closer to 1.0, the more similar, if using "IP" distance.

**Comment by skye95git** [comment]
> > 
> 
> i have meet the same problem , how to add collection.num_entities before load? thank you!

```
collection.num_entities
collection.load()
```

**Comment by skye95git** [comment]
> > Among the results returned by vector search, is the smaller the distance, the more similar？
> > If yes, why is the larger the distance in the text search demo example, the more similar it is? <img alt="微信图片_20220214175918" width="814" src="https://user-images.githubusercontent.com/41561936/153842137-e77436f3-e627-4ea1-b5c3-eceeaa68cb8d.png">
> 
> it depends on the definition of distance, it is the closer to 1.0, the more similar, if using "IP" distance.

But in your example [bootcamp](https://github.com/milvus-io/bootcamp)/[solutions](https://github.com/milvus-io/bootcamp/tree/master/solutions)/[text_search_engine](https://github.com/milvus-io/bootcamp/tree/master/solutions/text_search_engine)/text_search_engine.ipynb, "L2" distance is used. 
<img width="613" alt="微信图片_20220216102412" src="https://user-images.githubusercontent.com/41561936/154184597-aaac2e9b-b6dc-4806-a4e4-543f5a8bba53.png">

It is still the closer to 1.0, the more similar:
<img width="814" alt="微信图片_20220214175918" src="https://user-images.githubusercontent.com/41561936/154184695-92eaaf3b-0627-44a3-8142-64895b617196.png">

Maybe you wrote the two print backwards.

**Comment by skye95git** [comment]
Whether the `metric_type` in `search parameters` and `metric_type` in `index parameter` need to be consistent?

**Comment by skye95git** [comment]
In the example [bootcamp](https://github.com/milvus-io/bootcamp)/[solutions](https://github.com/milvus-io/bootcamp/tree/master/solutions)/[text_search_engine](https://github.com/milvus-io/bootcamp/tree/master/solutions/text_search_engine)/text_search_engine.ipynb, the raw data is stored using PostgreSQL. But my original data was closer to 100 million. It is not feasible to store them in a table. Can Milvus store metadata using Rocksdb?

**Comment by xiaofan-luan** [comment]
> Whether the `metric_type` in `search parameters` and `metric_type` in `index parameter` need to be consistent?

sure it has to be same, otherwise there is no reason to build idnex

**Comment by xiaofan-luan** [comment]
> 

how do you defined meta data? like some scalar datas show up together with vector data?

**Comment by skye95git** [comment]
> > 
> 
> how do you defined meta data? like some scalar datas show up together with vector data?

1. For example, when I do text search, I calculate the `text` as a vector and insert it into collection. The `text` is metadata. Can Milvus store text in rocksdb?

2. How do you defined vector data, scalar data, and metadata?
<img width="681" alt="7de6675e6bdc3ec7f1a3405e21b0196" src="https://user-images.githubusercontent.com/41561936/161378333-810f6289-d279-4239-8791-5a6f1fed8b73.png">

**Comment by Mr-Shivam-Sinha** [comment]
> might be the same issue as #15429, we've already fixed issues and will be released on next week. To solve this issue temporarily, you can call num_entities before load and it will trigger a internal flush which would solve the issue

It is not working even after adding collection.num_entities before collection.load()
