### ISSUE TITLE
[Bug]: Attu GUI shows too many decimal values

### ISSUE THREAD

**Issue by ufuk23** [milvus-io/milvus#15534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.0
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.0.0
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 4 / 16GB
- GPU: 
- Others:
```

### Current Behavior

When I insert vectors as float values with rounded as two decimal Attu GUI shows them many decimals as the picture added. If I print the vector on the python console from Milvus, it will seem normal. Has anyone faced this issue and know why it happens?

### Expected Behavior

Expecting rounded 2 decimal values

### Steps To Reproduce

```markdown
See on attu GUI
```

![attu_decimal](https://user-images.githubusercontent.com/8513827/153409898-e3fe2808-f05e-4f68-8332-5df9a933cd6b.png)

**Comment by ufuk23** [comment]
I am curious if this bug belongs to Milvus or just Attu GUI. I mean, does the bug point to the data problem or just GUI problem?

**Comment by shanghaikid** [comment]
GUI bug.

deepBlue ***@***.***> 于 2022年2月10日周四 20:17写道：

**Comment by nameczz** [comment]
Javascript has float precision problem for long time.
When query data, Milvus grpc server will return vector as FloatArray. Then node SDK receive float data and cause precision problem.
https://github.com/grpc/grpc/issues/2227

**Comment by xiaofan-luan** [comment]
It seems all float vector in milvus is stored in FloatArray, which only support x.xxxxxx precision(6 numbers after .)

To support float we will need to add another double definition. should we do that?

**Comment by shanghaikid** [comment]
> It seems all float vector in milvus is stored in FloatArray, which only support x.xxxxxx precision(6 numbers after .)
> 
> To support float we will need to add another double definition. should we do that?

Any performance impact to do that ?

**Comment by xiaofan-luan** [comment]
> > It seems all float vector in milvus is stored in FloatArray, which only support x.xxxxxx precision(6 numbers after .)
> > To support float we will need to add another double definition. should we do that?
> 
> Any performance impact to do that ?

Yes, It would double memory space as well as pulsar throughput. We should leave it to user and let the decide either to pick precision or cost~
