### ISSUE TITLE
[Enhancement]: Security verification

### ISSUE THREAD

**Issue by angleGhost** [milvus-io/milvus#15532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?
We'd like to see username/password or token verification in the connection params.

```java
public class ConnectParam {
    private final String host;
    private final int port;
    private final long connectTimeoutMs;
    private final long keepAliveTimeMs;
    private final long keepAliveTimeoutMs;
    private final boolean keepAliveWithoutCalls;
    private final long idleTimeoutMs;
}
```

### Why is this needed?

In practical applications, Milvus may be deployed in the public network, that is, the Milvus server and the actual business logic are separated in different servers, not limited to the local area network;

Just as Java applications and databases may be deployed separately, and then communicate through the public network.

Hope to get the support of security related functions

**Comment by xiaofan-luan** [comment]
anyone want to take account and password feature please let me know~

**Comment by xiaofan-luan** [comment]
keep it open
