### ISSUE TITLE
[Enhancement]: Avoid to copy many bytes from C code

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#15544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

According to [this](https://www.cockroachlabs.com/blog/the-cost-and-complexity-of-cgo/), we can avoid to copy when converting C bytes to Go bytes by casting the type with unsafe.

### Why is this needed?

In internal/querynode/segment.go(HandleCProto), it converts the C proto bytes to Go bytes with C.GoBytes() method, which copies all the bytes of the large object. It's avoidable, and reduces memory pressure.

**Comment by xiaofan-luan** [comment]
good catch, we have many avoidable copies and we should take care of it 
@czs007 @bigsheeper

**Comment by yah01** [comment]
@xiaofan-luan  What about this:
```golang
// Return a lease and []byte from C bytes which references the same memory with the C bytes
// Call Release(lease) after you don't need the returned []byte
func (converter *BytesConverter) UnsafeGoBytes(cbytes *unsafe.Pointer, len int) (int32, []byte) {
	var (
		goBytes []byte = nil
		lease   int32  = 0
	)

	goBytes = (*[maxByteArrayLen]byte)(*cbytes)[:len:len]
	lease = converter.add(*cbytes)
	*cbytes = nil

	return lease, goBytes
}

func (converter *BytesConverter) Release(lease int32) {
	pI, ok := converter.pointers.LoadAndDelete(lease)
	if !ok {
		panic("try to release the resource that doesn't exist")
	}

	p, ok := pI.(unsafe.Pointer)
	if !ok {
		panic("incorrect value type")
	}

	C.free(p)
}
```
The `UnsafeGoBytes(p, len)` method set the origin pointer to nil, to avoid the caller accessing the C pointer after converting. The returned lease is something like resource ID, the caller may need release it later, then it can remember the lease to achieve this.

This is BytesConverter:
```golang
type BytesConverter struct {
	pointers  sync.Map // lease -> unsafe.Pointer
	nextLease int32
}
```

**Comment by xiaofan-luan** [comment]
> ```go
> BytesConverter
> ```

That make sense to me. We can even have a reference counter so the converter can be shared as shared_ptr

**Comment by xiaofan-luan** [comment]
I love the solution, looks very clean.
My suggestion of next step would be adding some leakage check make sure all the lease is freed in a fixed time period.
The lease id might be number related to physical timestamp, that make more sense to me

**Comment by czs007** [comment]
I suggest add Reset to replace Release and change Release to  delete lease from sync.Map but do not free the underling c Pointer. 
Just like release and reset of unique_ptr.
