### ISSUE TITLE
Request to add WAL log archiving / streaming replay

### ISSUE THREAD

**Issue by VernonPerry** [milvus-io/milvus#1554]
A clear and concise description of what the problem is. E.g. I wish I could use Milvus to do [...]

It looks like WAL is supported for transactional data but without any log archiving that could be used to store a dataset to say for example AWS S3.

**Describe the solution you'd like**

Provide WAL logging archival and replay capability in a similar fashion as Postgresql so that dynamic load balanced clusters can be brought online via Docker master-master nodes that have a shared dataset for exposing similarity search APIs (WAL logs are replayed from S3 to populate the local filesystem while in a pre-run init state).

**Comment by shengjun1985** [comment]
At present, some user operations are not recorded in WAL, so replay by WAL alone is not supported.
If this function is required, the WAL system needs additional design.

**Comment by scsven** [comment]
Implemented as 'transcript'.
