### ISSUE TITLE
[Feature]: Dynamic config load system

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#15558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Currently all milvus config is loaded from milvus.yaml, and config change need to restart the process.

The config file will be a big trouble for production environment because if user change some of the configs by their own they need to take care of it on each upgrade.

### Describe the solution you'd like.

For easier maintenance, we should probably persist user specified config in a meta table(on etcd). And param table should load from both meta table as well as file.

We should expose one API to the SDK - loadConfig. load config will persistent the config to etcd and notify all the process to apply the config into their memory

**Comment by xiaofan-luan** [comment]
hi @dengn, are you looking for some good first issues?

**Comment by nohack** [comment]
Yeah, I would like to see some good first issues.

**Comment by xiaofan-luan** [comment]
@nohack feel free to talk to me on slack if you have no targets yet or you can simply start from this issue?

**Comment by nohack** [comment]
@xiaofan-luan sure.will ping you.

**Comment by nohack** [comment]
> The config file will be a big trouble for production environment because if user change some of the configs by their own they need to take care of it on each upgrade.

How does persisting the milvus.yaml in etcd help while upgrades ? When you mean the config needs changes during upgrade, I assume the schema of the config or the keys getting changed ?
Even when we persist the config in etcd, if the config needs to be updated for an upgrade, it should be updated in etcd as well.That would also be the same with external file right ?

**Comment by xiaofan-luan** [comment]
> 

What we want to introduce is a dynamic config center.
For example, due to some reasons I changed timetick.interval from 100ms to 1s
On the next update I use the latest code, as well as the latest configuration, then the config change lost.
So persistent all customized configs into etcd help on that.
Another feature of the config center is to notify the config change dynamiclly(with some cmd line or webpage)we don't need to restart process for config change.

**Comment by nohack** [comment]
Just want to add few points

a) If a user edits some property as u said timetick.interval in milvus.yaml and when he upgrades milvus and during the upgrade if milvus overrides the users current milvus.yaml with a new config file altogether, then this could be an issue.But generally this is more dependent on how milvus handles upgrades and in an ideal case I think the users current config file should not be overwritten.  
b) In Postgres as well, there is a default config file and users can edit system parameters (config) through alter commands.So any parameters edited through the cli are written to a new postgresql.auto.conf.The user can edit manually the postgresql.conf file.  

So I assume below are the things we want to achieve

1) user can persist milvus config using loadConfig api into etcd.
2) Whenever a config change is persisted in etcd, notify the other processes and depending on the possibility some of these processes can apply the new config changes without requiring a restart.
So is this ok.

**Comment by xiaofan-luan** [comment]
> Just want to add few points
> 
> a) If a user edits some property as u said timetick.interval in milvus.yaml and when he upgrades milvus and during the upgrade if milvus overrides the users current milvus.yaml with a new config file altogether, then this could be an issue.But generally this is more dependent on how milvus handles upgrades and in an ideal case I think the users current config file should not be overwritten. b) In Postgres as well, there is a default config file(postgresql.conf ) and users can edit system parameters by manually editing the file or through alter commands.So any parameters edited through the alter command are written to a new postgresql.auto.conf. [Reference](https://www.postgresql.org/docs/current/sql-altersystem.html)
> 
> So I assume below are the things we want to achieve
> 
> 1. user can persist milvus config using loadConfig api into etcd.
> 2. Whenever a config change is persisted in etcd, notify the other processes and depending on the possibility some of these processes can apply the new config changes without requiring a restart.
>    So is this ok.

1.Yep， My priority would be config in etcd > config in system environment>  config in yaml file > default config
2. postgresql.auto.conf is just like what I mentioned, since Milvus is a distributed system, a file may not be enough thus we use etcd. 

Generally I guess you get what I mean, let me know if you have any other suggestion or question on it~

**Comment by nohack** [comment]
> We should expose one API to the SDK - loadConfig. load config will persistent the config to etcd and notify all the process to apply the config into their memory

So will the users use the sdk to persist the config in etcd.  
Do they persist all the config in one go by providing the milvus.yaml path.

**Comment by xiaofan-luan** [comment]
> > We should expose one API to the SDK - loadConfig. load config will persistent the config to etcd and notify all the process to apply the config into their memory
> 
> So will the users use the sdk to persist the config in etcd. Do they persist all the config in one go by providing the milvus.yaml path.

Thought we should sdk config should overwrite milvus.yaml~
The priority should be:
1.Etcd persistent
2.Environment 
3.milvus.yaml
4.default value in code

**Comment by nohack** [comment]
Yeah, I get this.  
How will the users persist the config into etcd.Should we expose an api which takes the config path as a parameter.

# saves the config file at the provided path to etcd.
saveConfig(configPath)

**Comment by xiaofan-luan** [comment]
> Yeah, I get this. How will the users persist the config into etcd.Should we expose an api which takes the config path as a parameter.
> 
> // saves the config file at the provided path to etcd. saveConfig(configPath)

sure, we should support save(key, value)/remove(key)

**Comment by nohack** [comment]
save(key, value)  
remove(key)

Ok so I can start with the above api implementation then.

**Comment by xiaofan-luan** [comment]
keep it open~ @nohack any progress~

**Comment by nohack** [comment]
Sure.Was a bit tied up.Will work on it.

**Comment by nohack** [comment]
@xiaofan-luan As per the latest code, looks like this is implemented ?

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan As per the latest code, looks like this is implemented ?

Not yet? This is still on the plan of Milvus 2.3

**Comment by nohack** [comment]
@xiaofan-luan [These](https://github.com/milvus-io/milvus/blob/master/internal/util/paramtable/base_table.go#L117-L118) lines are similar to dynamic config load with file and remote etcd based loading ?

**Comment by LaPetiteSouris** [comment]
@xiaofan-luan has this been addressed by https://github.com/milvus-io/milvus/issues/18300 ?

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan has this been addressed by #18300 ?

Yes sir. close it for now
