### ISSUE TITLE
[Bug]: Miss default configerations of milvus limits when I install Milvus with Docker Compose 

### ISSUE THREAD

**Issue by huangjincheng2022** [milvus-io/milvus#15565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.0
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):v2.0.0rc2
- OS(Ubuntu or CentOS): N/A
- CPU/Memory: N/A
- GPU: N/A
- Others: N/A
```

### Current Behavior

https://github.com/milvus-io/milvus/releases/download/v2.0.0/milvus-standalone-docker-compose.yml
Miss default configerations of milvus limits when I install Milvus with Docker Compose 
In my test case, the number of field in a collection should be limited to 256.

**Comment by yanliang567** [comment]
@LoveEachDay could you please help on this issue.

/assign @LoveEachDay 
/unassign
