### ISSUE TITLE
Low CPU utilization when building index

### ISSUE THREAD

**Issue by sahuang** [milvus-io/milvus#1557]
**Describe the bug**
When building index with Milvus CPU version, CPU usage is too low.

**Steps/Code to reproduce behavior**
- Insert sift_10m_1024_128_l2 and build ivf_sq8 index with nlist: 16384. Stopped at building index.
- When calling ```htop```, CPU usage for milvus server is only around ```1400%``` but there are 48 cores.
- Server log on build index
```bash
milvus-20-03-08-10:16-debug.log:2020-03-08 11:25:50,738 | DEBUG | default | [SERVER] DoBuildIndex file id:25: totally cost (1845.348260 seconds [1845348.260270 ms])
```

**Expected behavior**
Higher CPU %

**Environment details**
Milvus Release version: v0.7.0, built at 2020-03-07 16:31.32, with OpenBLAS library.
Milvus CPU edition
Last commit id: ba701808a36ef59012ad9bc30de5f8e5bbcb7987

**Comment by JinHai-CN** [comment]
Still have the same issue? @del-zhenwu

**Comment by del-zhenwu** [comment]
About `3600%` usage while building index currently

**Comment by del-zhenwu** [comment]
close

**Comment by del-zhenwu** [comment]
If server do mixed operations(including flush/build index/compact/searching), the cpu usage is always below 1400%

**Comment by JinHai-CN** [comment]
Compare to previous relesae, how much the performance decreased?

**Comment by shengjun1985** [comment]
Some of these mixed operations are I/O type, so the cpu are not all used.
Furthermore, in ver 0.9.0, the algorithm of building index, the policy of building index and searching and the policy of merging files are all changed.
The issue can be closed now.
