### ISSUE TITLE
[Bug]: Error: failed to open database: Can't construct MySQL connection. Possible reason: out of storage, meta schema is damaged 

### ISSUE THREAD

**Issue by hadisi** [milvus-io/milvus#15575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
  1.0.0-cpu-d030521-1ea92e
- Deployment mode(standalone or cluster):
   standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Welcome to use Milvus!
Milvus Release version: v1.0.0, built at 2021-03-04 06:43.00, with OpenBLAS library.
You are using Milvus CPU edition
Last commit id: 21ea92ec7e57ab00cca671d74195c4eaa81869a2

Loading configuration from: /var/lib/milvus/conf/server_config.yaml
Supported CPU instruction sets: avx512, avx2, sse4_2
FAISS hook AVX512
Error: failed to open database: Can't construct MySQL connection. Possible reason: out of storage, meta schema is damaged or created by in-compatible Milvus version.
Milvus server is going to shutdown ...
Milvus server exit...

### Steps To Reproduce

```markdown
集群内部两台机器A172.20.90.142和B172.22.93.91
mysql-5.7 docker启动 部署在A 机器上。
启动脚本如下
docker run -p 3307:3306 --name mysql \
         -v $base_dir/conf:/etc/mysql \
         -v $base_dir/logs:/var/log/mysql \
         -v $base_dir/data:/var/lib/mysql \
         -e MYSQL_ROOT_PASSWORD=123456 \
         -d mysql:5.
milvus部署在B机器上。
milvus mysql配置如下：
  general:
  timezone: UTC+8
  meta_uri: mysql://root:123456@172.20.90.142:3307/milvus

我直接在B机器，也就是milvus所在机器，用mysql 客户端连接，可以连接上。
[root@n05b-h2t4-aa-cs bin]# ./mysql -uroot -h172.20.90.142 -P3307 -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 10
Server version: 5.7.36 MySQL Community Server (GPL)

Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
```

### Anything else?

问题应该出在  milvus 内部连接 mysql的方式上，求大神解答。

**Comment by hadisi** [comment]
一个机器有多个IP，管理网IP，应用层IP，等等

**Comment by hadisi** [comment]
A、B都是集群内部机器，有多个IP，管理王IP，应用层IP等等。集群内部只能通过应用层IP访问，就是A172.20.90.142和B172.22.93.91这两个是应用层IP 。

**Comment by yhmo** [comment]
先确认一下有没有创建一个叫 "milvus"的database，mysql客户端进入后 use milvus 看看。
如果有这么一个database，地址端口用户名密码都是对的，但是就是连不上，说实话我也比较费解。在milvus代码里使用的是一个叫msqlpp的第三方插件来连接mysql，连接代码就这几行：
```
if (!ssl_ca_.empty()) {
    conn->set_option(new mysqlpp::SslOption(ssl_key_.c_str(), ssl_cert_.c_str(), ssl_ca_.c_str()));
}

conn->connect(db_name_.empty() ? 0 : db_name_.c_str(), server_.empty() ? 0 : server_.c_str(),
              user_.empty() ? 0 : user_.c_str(), password_.empty() ? 0 : password_.c_str(), port_);
```
在这个帖子里也是类似的问题，最后也是不了了之：https://github.com/milvus-io/milvus/issues/3768
我们自己测试的机器环境相对比较简单固定，用户环境中可能有一些我们也无法预知的问题，很难解答出来。可以通过实验的方式，比如换一台机器看看是否能连，如果能连的话，比较一下这两台环境有何不同。

**Comment by hadisi** [comment]
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| milvus             |
| mysql              |
| performance_schema |
| sys                |
+--------------------+
5 rows in set (0.01 sec)

**Comment by hadisi** [comment]
172.21.244.178  和  172.21.244.178，这两台虚拟机可以。虚拟机之间， 不同点，他们们只有一个ip。

**Comment by hadisi** [comment]
> 先确认一下有没有创建一个叫 "milvus"的database，mysql客户端进入后 use milvus 看看。 如果有这么一个database，地址端口用户名密码都是对的，但是就是连不上，说实话我也比较费解。在milvus代码里使用的是一个叫msqlpp的第三方插件来连接mysql，连接代码就这几行：
> 
> ```
> if (!ssl_ca_.empty()) {
>     conn->set_option(new mysqlpp::SslOption(ssl_key_.c_str(), ssl_cert_.c_str(), ssl_ca_.c_str()));
> }
> 
> conn->connect(db_name_.empty() ? 0 : db_name_.c_str(), server_.empty() ? 0 : server_.c_str(),
>               user_.empty() ? 0 : user_.c_str(), password_.empty() ? 0 : password_.c_str(), port_);
> ```
> 
> 在这个帖子里也是类似的问题，最后也是不了了之：#3768 我们自己测试的机器环境相对比较简单固定，用户环境中可能有一些我们也无法预知的问题，很难解答出来。可以通过实验的方式，比如换一台机器看看是否能连，如果能连的话，比较一下这两台环境有何不同。

mysql> show databases;
+--------------------+
| Database |
+--------------------+
| information_schema |
| milvus |
| mysql |
| performance_schema |
| sys |
+--------------------+
5 rows in set (0.01 sec)

172.21.244.178 和 172.21.244.178，这两台虚拟机可以。每台虚拟机只有一个IP，和上面物理机不同点，就是每台物理机有多个ip。而且我查了mysql日志，发现用mysql客户端连接，日志有连接信息。而milvus连接mysql，mysql日志里面，没有记录。

**Comment by yhmo** [comment]
看milvus的error.log里有没有“Failed to connect to database server”这样的句子

**Comment by hadisi** [comment]
> 先确认一下有没有创建一个叫 "milvus"的database，mysql客户端进入后 use milvus 看看。 如果有这么一个database，地址端口用户名密码都是对的，但是就是连不上，说实话我也比较费解。在milvus代码里使用的是一个叫msqlpp的第三方插件来连接mysql，连接代码就这几行：
> 
> ```
> if (!ssl_ca_.empty()) {
>     conn->set_option(new mysqlpp::SslOption(ssl_key_.c_str(), ssl_cert_.c_str(), ssl_ca_.c_str()));
> }
> 
> conn->connect(db_name_.empty() ? 0 : db_name_.c_str(), server_.empty() ? 0 : server_.c_str(),
>               user_.empty() ? 0 : user_.c_str(), password_.empty() ? 0 : password_.c_str(), port_);
> ```
> 
> 在这个帖子里也是类似的问题，最后也是不了了之：#3768 我们自己测试的机器环境相对比较简单固定，用户环境中可能有一些我们也无法预知的问题，很难解答出来。可以通过实验的方式，比如换一台机器看看是否能连，如果能连的话，比较一下这两台环境有何不同。

你吧mysqlpp第三方插件的详细信息给一下，版本号等等，我安装一下，本地测试一下。

**Comment by hadisi** [comment]
> 看milvus的error.log里有没有“Failed to connect to database server”这

[2022-02-15 14:18:21,190][ERROR][ENGINE][create][milvus_server] Failed to connect to database server: Can't connect to MySQL server on '172.20.90.142' (110)

**Comment by yhmo** [comment]
mysqlpp是这个版本：
MYSQLPP_VERSION=3.2.4

**Comment by hadisi** [comment]
> mysqlpp是这个版本： MYSQLPP_VERSION=3.2.4

谢谢哈。微信群里有个小龙的大神，已经指点了，给出了答案。因为我的防火墙没有开启，导致docker内部和外面的网络不通。已经可以了。

**Comment by hadisi** [comment]
因为我的防火墙没有开启，导致milvus容器内部和外面的网络不通。已经可以了。
