### ISSUE TITLE
[Bug]: [benchmark][standalone] Concurrent query of Milvus Standalone for a period of time, the memory of Milvus Standalone gradually increases

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#15584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220213-f74a9c2
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.1.dev1
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Milvus monitor:
**Memory of Milvus Standalone increased by nearly 1G**

<img width="1841" alt="截屏2022-02-15 17 10 53" src="https://user-images.githubusercontent.com/26307815/154029714-5931a72c-64b1-4ec1-be50-b2b1fba9525a.png">
<img width="1841" alt="截屏2022-02-15 17 11 12" src="https://user-images.githubusercontent.com/26307815/154029745-0885e854-cc52-4ebc-8f20-3bd46cb9005f.png">

### Expected Behavior

client pod: benchmark-concurrent-2tb7k-3671218197

argo task: **benchmark-concurrent-2tb7k**

test yaml:
client-configmap: pre2.0-client-locust-concurrent-search-sift1m-ivf-flat-2048-clientnum20
server-configmap: server-single-16c64m

server:
```
NAME                                                              READY   STATUS      RESTARTS   AGE    IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-concurrent-2tb7k-100-etcd-0                             1/1     Running     0          72m    10.97.17.24    qa-node014.zilliz.local   <none>           <none>
benchmark-concurrent-2tb7k-100-milvus-standalone-7f87f67cbpsp97   1/1     Running     0          72m    10.97.16.241   qa-node013.zilliz.local   <none>           <none>
benchmark-concurrent-2tb7k-100-minio-6d4795fdc8-w6bxc             1/1     Running     0          72m    10.97.17.25    qa-node014.zilliz.local   <none>           <none>
```

### Steps To Reproduce

```markdown
1、create a collection and insert 1 million vectors
2、Start 18 clients concurrently search, each client concurrently 20
```

**Comment by xiaofan-luan** [comment]
The memory increase seems to be ok with because the rocksmq cache size is 1GB.
So I guess for standalone this should be expected and other memory increase maybe related to other issues of proxy memory increase and coord memory increase

**Comment by yanliang567** [comment]
> The memory increase seems to be ok with because the rocksmq cache size is 1GB. So I guess for standalone this should be expected and other memory increase maybe related to other issues of proxy memory increase and coord memory increase

@xiaofan-luan do you mean the root cause might be in proxy and coordinator ?

**Comment by xiaofan-luan** [comment]
> o I guess for standalone this should be expected and other memory increase maybe related to other issues of proxy memory increase and coord memory increase

What I mean is the rocksmq cache is set to 1G, so by design the standalone process should be take more than 1G cache + Mem store size(Hundred megabytes) + index + temp memory size. So it's very likely that the process will take more than 2GB memory size so I don't think it is a memory leakage.

**Comment by xiaofan-luan** [comment]
The overhead of querynode should take 1-2GB memory
