### ISSUE TITLE
[Feature]: arm64 鲲鹏服务器需求

### ISSUE THREAD

**Issue by zoujialong9012** [milvus-io/milvus#15607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

鲲鹏arm服务器需求移植milvus

### Describe the solution you'd like.

参考
https://github.com/zoujialong9012/milvus/tree/v2.0_aarch64

**Comment by xiaofan-luan** [comment]
hi there @zoujialong9012, are you gonna to merge the arm64 branch into master?

**Comment by return200** [comment]
@zoujialong9012 朋友 怎么构建的 方便分享一下吗

**Comment by xiaofan-luan** [comment]
@return200 We are gonna to release Arm support soon!

**Comment by return200** [comment]
@xiaofan-luan Thanks for your hard work! I'm looking forward to.

**Comment by xiaohezi205** [comment]
我milvus 2.2.12 arm64v8编译通过了 后续给大家出教程 ，超级兴奋啊 也可以联系我wx:1079361253
