### ISSUE TITLE
[Feature]: Bulk load data

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#15604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Typically, it cost several (5~6) hours to insert one billion entities with 128-dimensional vectors. We need a new interface to do bulk load for the following purposes: 

1. import data from JSON format files. (first stage)
2. import data from Numpy format files. (first stage)
3. copy a collection within on Milvus 2.0 service. (second stage)
4. copy a collection from one Milvus 2.0 service to another. (second stage)
5. import data from Milvus 1.x to Milvus 2.0 (third stage)
6. parquet/faiss files (TBD)

**Comment by xiaofan-luan** [comment]
what kind of format are we plan to support? Json, parquet, xml or ...

**Comment by yhmo** [comment]
> what kind of format are we plan to support? Json, parquet, xml or ...

Basically json/numpy.

**Comment by claireyuw** [comment]
@yhmo @soothing-rain Is the related user doc ready for development yet?
