### ISSUE TITLE
[Enhancement]: Add the function of querying the disk space occupied by the current collection

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#15609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Add a python interface to query the disk space occupied by the collection, or add results to the existing interface get_collection_stats

### Why is this needed?

Estimated required disk size for data export

**Comment by xiaofan-luan** [comment]
Actually it should be a more complicated API for further extendibility, such as memory consumption, disk consumption and entity

**Comment by soothing-rain** [comment]
> 

Can we make them all metrics (i.e. are collected by monitoring)?

**Comment by soothing-rain** [comment]
> Actually it should be a more complicated API for further extendibility, such as memory consumption, disk consumption and entity

Can we make them all metrics (i.e. are collected by monitoring)?
