### ISSUE TITLE
collection load fail

### ISSUE THREAD

**Issue by huaihkiss** [milvus-io/milvus#15615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):v2.0.0rc9
- OS(Ubuntu or CentOS): Mac OS 12.0.1
- CPU/Memory: cpu: 4 core 8 threads, 8G RAM
- GPU: 
- Others:
```

### Current Behavior

I tried to load data, but there was an error
`Failed to execute task: collection 431247688568406017 has not been loaded to memory or load failed`
I tried to call 'num_entities' function before load the data, but it is repeat call ’flush‘ function
This is a log file
[warn_error.log](https://github.com/milvus-io/milvus/files/8087440/warn_error.log)

### Steps To Reproduce

```markdown
1.Create collection
2.Create index
3.Initialization data
4.Load data
```

**Comment by yanliang567** [comment]
@huaihkiss seems that there is no enough memory to load the collection. Could you please check the data size and the configured memory, and make sure data_size < limited_memory * 90%

/assign @huaihkiss 
/unassign

**Comment by heyitao** [comment]
I have meet this problem too;  
After docker-compose finished installing milvus(standelone)
I run the demo hello_milvus.py, and I got: 
![image](https://user-images.githubusercontent.com/22836696/157398498-d9584b3f-097b-4536-9eb2-a7c90c0dfc18.png)
it seems not the reason "no enough memory to load the collection" beacuse only 3000 entities insert in collection. And My machine has 64GB memory.

**Comment by yanliang567** [comment]
@heyitao please check the docker configuration for memory limitation as milvus is running by docker-compose
