### ISSUE TITLE
[Feature]: Deploy milvus cluster offline

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#15610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

we've already support to install standalone milvus with yum/apt see https://milvus.io/docs/v2.0.0/install_standalone-aptyum.md

however, for distributed cluster it become even more complicated because user need to config node number and cpu, memory disk configurations.

We've seen many users require to deploy milvus in offline environment and if they have huge amount of data that will become a issue.

### Describe the solution you'd like.

We should have some scripts on how to deploy milvus cluster offline(together with etcd and minio). 
The full deployment requires:
3 nodes for minio, 3 nodes for etcd, 3 nodes for bookie, 1 pulsar broker, and Milvus itself(including Query,Index,Data coord and node).

**Comment by insist93** [comment]
Looking forward to the scripts😀
