### ISSUE TITLE
[Bug]:[chaos][pulsar]timeout when running hello_milvus.py after pulsar pod recovered from pod kill 

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#15624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220210-1a2a6927
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.0.1.dev3
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

after test_e2e.py is finished, hello_milvus.py hangs at a certain step（not shown in console, so can't tell the exact step）

### Expected Behavior

all steps pass

### Steps To Reproduce

```markdown
see https://github.com/milvus-io/milvus/runs/5175430573?check_suite_focus=true
```

### Anything else?

job link：
https://github.com/milvus-io/milvus/runs/5175430573?check_suite_focus=true
log:
https://github.com/milvus-io/milvus/suites/5288780331/artifacts/163868135

**Comment by zhuwenxing** [comment]
Another same failed job
https://github.com/milvus-io/milvus/runs/5237096747?check_suite_focus=true
log:
https://github.com/milvus-io/milvus/suites/5349688477/artifacts/167385727

**Comment by yanliang567** [comment]
@sunby please help on this issue.
/assign @sunby 
/unassign

**Comment by sunby** [comment]
Insert channel on DataNode can not receive messages after pulsar pod restarted and Flush request timeout.

**Comment by zhuwenxing** [comment]
Recent failed job
* https://github.com/milvus-io/milvus/runs/5396537377?check_suite_focus=true
* https://github.com/milvus-io/milvus/runs/5411928983?check_suite_focus=true

**Comment by zhuwenxing** [comment]
not reproduced yet, remove the urgent label
