### ISSUE TITLE
[Bug]: load_progress has ambiguous output

### ISSUE THREAD

**Issue by ss892714028** [milvus-io/milvus#15629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.0
- Deployment mode(standalone or cluster): 
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![YjcC29OqhV](https://user-images.githubusercontent.com/34635663/154627919-de1a0dfa-b4fd-4a89-aed1-119c47a9e044.png)
num_loaded_entity can be larger than num_total_entity.

The reason is num_total_entity only include the segments that are persisted in S3 (sealed segments). However, both growing segments and sealed segments need to be loaded. 

num_total_entity might need a more accurate expression.

### Expected Behavior

clear output

**Comment by XuanYang-cn** [comment]
@ss892714028  how about changing this into 
```python
{'loading progress':  10%}
```

**Comment by ss892714028** [comment]
> @ss892714028 how about changing this into
> 
> ```python
> {'loading progress':  10%}
> ```

Showing percentage is definitely more user friendly IMO. How is the percentage number calculated?

**Comment by XuanYang-cn** [comment]
> Showing percentage is definitely more user friendly IMO. How is the percentage number calculated?

num_loaded_entity / num_total_entity if num_loaded_entity <= num_total_entity

100% if num_loaded_entity > num_total_entity

**Comment by ss892714028** [comment]
Anyone interested in taking this issue?
