### ISSUE TITLE
[Bug]: Empty segment generated by compaction is still saved

### ISSUE THREAD

**Issue by sunby** [milvus-io/milvus#15630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.0.0
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

A compaction may generate an empty segment because of all entities in segments are deleted. Now datacoord will just add a new segment and may compact this segment later. It's not resonable. 

### Expected Behavior

We can just ignore the empty segment generated by compaction.

**Comment by yanliang567** [comment]
anyone likes to help on this 'good first issue', please feel free to assign to himself. Enjoy!
