### ISSUE TITLE
[Feature]:  Support login with username and password 

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#15656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

There is a basic security requirement as authorized access.

**Comment by xiaofan-luan** [comment]
good to know~
We have ACL and more security features on our plan.
Anyone interested on it please join

**Comment by xiaofan-luan** [comment]
keep it on track
