### ISSUE TITLE
[Enhancement]: Use git submodule to manage milvus.proto, schema.proto and common.proto

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#15653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Every time something changes in milvus-io/milvus/tree/master/internal/proto we need to go to all the SDKs and copy the proto files. Ideally, all SDKs should have only one proto source. And this will also help to have a better documentation for people that want to use grpc directly.

We need to create a repo to shares the three proto files:
milvus.proto
schema.proto
common.proto

Each SDK project imports the repo as a submodule and generates protobuf files by itself.

A discussion is here: 
https://app.slack.com/client/TM98LD8DQ/C012DUVUFNZ/thread/C012DUVUFNZ-1643311295.762299

**Comment by yhmo** [comment]
An empty repo was created for this issue:  https://github.com/milvus-io/milvus-proto

**Comment by XuanYang-cn** [comment]
`milvus-proto` has been updated, I think SDKs are able to start using `git submodule`.

**Comment by yhmo** [comment]
Java SDK start to use the milvus-proto as submodule: https://github.com/milvus-io/milvus-sdk-java/pull/267

**Comment by XuanYang-cn** [comment]
/reopen

let's keep tracking this issue

**Comment by XuanYang-cn** [comment]
https://github.com/milvus-io/pymilvus/pull/975

**Comment by XuanYang-cn** [comment]
cpp， java are done

**Comment by XuanYang-cn** [comment]
https://github.com/milvus-io/milvus-sdk-node/pull/89

**Comment by XuanYang-cn** [comment]
All done, closing this issue
