### ISSUE TITLE
[Bug]: The specified key does not exist.

### ISSUE THREAD

**Issue by suibianmzl** [milvus-io/milvus#15662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.0ga
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):milvus-sdk-go v2
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 48/384G
- GPU: V100
- Others:
```

### Current Behavior

[2022/02/21 06:42:40.940 +00:00] [ERROR] [impl.go:342] ["The specified key does not exist."] [stack="github.com/milvus-io/milvus/internal/querynode.(*QueryNode).LoadSegments.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/impl.go:342\ngithub.com/milvus-io/milvus/internal/querynode.(*QueryNode).LoadSegments\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/impl.go:351\ngithub.com/milvus-io/milvus/internal/distributed/querynode.(*Server).LoadSegments\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:356\ngithub.com/milvus-io/milvus/internal/proto/querypb._QueryNode_LoadSegments_Handler.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proto/querypb/query_coord.pb.go:3456\ngithub.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38\ngithub.com/milvus-io/milvus/internal/proto/querypb._QueryNode_LoadSegments_Handler\n\t/go/src/github.com/milvus-io/milvus/internal/proto/querypb/query_coord.pb.go:3458\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934"]

### Expected Behavior

Querynode automatically loads after restart
![querynode_log](https://user-images.githubusercontent.com/6262877/154911393-e0e87f75-3c7f-4d66-8c69-6a1fc53e342a.png)
[query_node.log](https://github.com/milvus-io/milvus/files/8107337/query_node.log)

**Comment by yanliang567** [comment]
@xige-16 is it  a known issue?
/assign @xige-16 
/unassign

**Comment by xiaocai2333** [comment]
seems like #12465 ,  can you paste your configuration about DataCoord here ?

**Comment by suibianmzl** [comment]
> seems like #12465 , can you paste your configuration about DataCoord here ?

This is the log of the datacoord node. Thank you for your help
[Uploading datacoord.log…]()

**Comment by xiaocai2333** [comment]
> > seems like #12465 , can you paste your configuration about DataCoord here ?
> 
> This is the log of the datacoord node. Thank you for your help Uploading datacoord.log…

thanks， and i want your config file.

**Comment by suibianmzl** [comment]
> seems like #12465 , can you paste your configuration about DataCoord here ?

This is the log of the datacoord node. Thank you for your help

[datacoord2.log](https://github.com/milvus-io/milvus/files/8107645/datacoord2.log)

**Comment by suibianmzl** [comment]
> 



> > > seems like #12465 , can you paste your configuration about DataCoord here ?
> > 
> > 
> > This is the log of the datacoord node. Thank you for your help Uploading datacoord.log…
> 
> thanks， and i want your config file.

OK, here is our configuration file


[values.yaml.log](https://github.com/milvus-io/milvus/files/8107701/values.yaml.log)

**Comment by suibianmzl** [comment]
> > > seems like #12465 , can you paste your configuration about DataCoord here ?
> > 
> > 
> > This is the log of the datacoord node. Thank you for your help Uploading datacoord.log…
> 
> thanks， and i want your config file.

Hello, do you have any ideas to solve this problem

**Comment by xiaocai2333** [comment]
maybe the segment has been compacted, and QueryNode uses the old segment to load after restart. But the old segment in minio(S3) has been deleted.

**Comment by xiaocai2333** [comment]
We will confirm it and fix it. @suibianmzl

**Comment by xiaofan-luan** [comment]
> maybe the segment has been compacted, and QueryNode uses the old segment to load after restart. But the old segment in minio(S3) has been deleted.

How do we know the segment is compacted? I mean even the segment is compacted the file should be kept for a while?

**Comment by xiaofan-luan** [comment]
@xiaocai2333 let's go through the logs carefully and give more evidence on the guess~

**Comment by suibianmzl** [comment]
> We will confirm it and fix it. @suibianmzl

OK, help locate the reason

**Comment by suibianmzl** [comment]
> > @xiaocai2333 let's go through the logs carefully and give more evidence on the guess~
> 
> yeah，I will do it.
> 
> And can you give me the DataNode log and QueryCoord log? @suibianmzl

  We redeployed the cluster and did not keep the logs  ... ￣□￣｜｜

**Comment by xiaocai2333** [comment]
> > > @xiaocai2333 let's go through the logs carefully and give more evidence on the guess~
> > 
> > 
> > yeah，I will do it.
> > And can you give me the DataNode log and QueryCoord log? @suibianmzl
> 
> We redeployed the cluster and did not keep the logs ... ￣□￣｜｜ We create a new cluster to reproduce the problem of uploading logs

Emmm, all right, I will find the bug based on the existing logs. If you reproduce it, keep all logs. 
By the way, how much the data did you insert?

**Comment by suibianmzl** [comment]
> > > > @xiaocai2333 let's go through the logs carefully and give more evidence on the guess~
> > > 
> > > 
> > > yeah，I will do it.
> > > And can you give me the DataNode log and QueryCoord log? @suibianmzl
> > 
> > 
> > We redeployed the cluster and did not keep the logs ... ￣□￣｜｜ We create a new cluster to reproduce the problem of uploading logs
> 
> Emmm, all right, I will find the bug based on the existing logs. If you reproduce it, keep all logs. By the way, how much the data did you insert?

The collection in question is about 170 million data

**Comment by xiaofan-luan** [comment]
We need more logs to take a deep look into it since it happens multiple times.
Maybe the mechanism itself need to be changed

**Comment by xige-16** [comment]
> > 
> 
> > > > seems like #12465 , can you paste your configuration about DataCoord here ?
> > > 
> > > 
> > > This is the log of the datacoord node. Thank you for your help Uploading datacoord.log…
> > 
> > 
> > thanks， and i want your config file.
> 
> OK, here is our configuration file
> 
> ```gfm
> dataCoordinator:
>   enabled: true
>   replicas: 1           # Run Data Coordinator mode with replication disabled
>   resources: {}
>   nodeSelector: {}
>   affinity: {}
>   tolerations: []
>   extraEnv:
>   - name: GODEBUG
>     value: "madvdontneed=1"
> 
>   enableCompaction: true
>   enableGarbageCollection: true
> 
>   segment:
>     maxSize: 512  # Maximum size of a segment in MB
> 
>   compaction:
>     enableAutoCompaction: true
>     retentionDuration: 432000  # 5 days in seconds
> 
>   gc:
>     interval: 60   # gc interval in seconds
>     missingTolerance: 3600  # file meta missing tolerance duration in seconds, 1 day
>     dropTolerance: 3600  # file belongs to dropped entity tolerance duration in seconds, 1 day
> 
> 
>   service:
>     port: 13333
>     annotations: {}
>     labels: {}
>     clusterIP: ""
> 
> dataNode:
>   enabled: true
>   replicas: 3
>   resources: {}
>   nodeSelector: {}
>   affinity: {}
>   tolerations: []
>   extraEnv:
>   - name: GODEBUG
>     value: "madvdontneed=1"
>   flush:
>     insertBufSize: "16777216"  ## bytes, 16MB
>   autoscaling:
>     enabled: false
>     minReplicas: 2
>     maxReplicas: 5
>     metrics:
>       - type: Resource
>         resource:
>           name: cpu
>           target:
>             type: Utilization
>             averageUtilization: 60
>       - type: Resource
>         resource:
>           name: memory
>           target:
>             type: Utilization
>             averageUtilization: 60
> ```
> 
> [values.yaml.log](https://github.com/milvus-io/milvus/files/8107701/values.yaml.log)

datacoord.dropTolerance is set too small, only one hour. , according to our 1 billion data benchmark test, it will take about an hour to load 170 million data. If compaction occurs during load, and the segment before compaction is dropped before loading into querynode memory, load will fail

**Comment by xige-16** [comment]
> We need more logs to take a deep look into it since it happens multiple times. Maybe the mechanism itself need to be changed

After querynode fails to load segment , querycoord can check whether the related segment has been comapcted before retrying the load segment request. @xiaofan-luan

**Comment by xige-16** [comment]
> ```gfm
> dropTolerance
> ```

It is recommended to increase the datacoord.dropTolerance value, and the current default value is 86400 (24h).

**Comment by suibianmzl** [comment]
> > ```
> > dropTolerance
> > ```
> 
> It is recommended to increase the datacoord.dropTolerance value, and the current default value is 86400 (24h).

OK, thanks. Let's try to put datacoord Droptolerance is set to 24h

**Comment by xige-16** [comment]
> s set to 24h

The recommended gc config:
```
  gc:
    interval: 3600 # gc interval in seconds
    missingTolerance: 86400 # file meta missing tolerance duration in seconds, 60*24
    dropTolerance: 86400 # file belongs to dropped entity tolerance duration in seconds, 60*24
```

**Comment by Murphy-AI** [comment]
> > s set to 24h
> 
> The recommended gc config:
> 
> ```
>   gc:
>     interval: 3600 # gc interval in seconds
>     missingTolerance: 86400 # file meta missing tolerance duration in seconds, 60*24
>     dropTolerance: 86400 # file belongs to dropped entity tolerance duration in seconds, 60*24
> ```

@xige-16 Hi xige, can I directly modify this configuration in our current milvus cluster? If yes, how should I do that? Thanks!

**Comment by xiaofan-luan** [comment]
> > > 
> > 
> > 
> > > > > seems like #12465 , can you paste your configuration about DataCoord here ?
> > > > 
> > > > 
> > > > This is the log of the datacoord node. Thank you for your help Uploading datacoord.log…
> > > 
> > > 
> > > thanks， and i want your config file.
> > 
> > 
> > OK, here is our configuration file
> > ```
> > dataCoordinator:
> >   enabled: true
> >   replicas: 1           # Run Data Coordinator mode with replication disabled
> >   resources: {}
> >   nodeSelector: {}
> >   affinity: {}
> >   tolerations: []
> >   extraEnv:
> >   - name: GODEBUG
> >     value: "madvdontneed=1"
> > 
> >   enableCompaction: true
> >   enableGarbageCollection: true
> > 
> >   segment:
> >     maxSize: 512  # Maximum size of a segment in MB
> > 
> >   compaction:
> >     enableAutoCompaction: true
> >     retentionDuration: 432000  # 5 days in seconds
> > 
> >   gc:
> >     interval: 60   # gc interval in seconds
> >     missingTolerance: 3600  # file meta missing tolerance duration in seconds, 1 day
> >     dropTolerance: 3600  # file belongs to dropped entity tolerance duration in seconds, 1 day
> > 
> > 
> >   service:
> >     port: 13333
> >     annotations: {}
> >     labels: {}
> >     clusterIP: ""
> > 
> > dataNode:
> >   enabled: true
> >   replicas: 3
> >   resources: {}
> >   nodeSelector: {}
> >   affinity: {}
> >   tolerations: []
> >   extraEnv:
> >   - name: GODEBUG
> >     value: "madvdontneed=1"
> >   flush:
> >     insertBufSize: "16777216"  ## bytes, 16MB
> >   autoscaling:
> >     enabled: false
> >     minReplicas: 2
> >     maxReplicas: 5
> >     metrics:
> >       - type: Resource
> >         resource:
> >           name: cpu
> >           target:
> >             type: Utilization
> >             averageUtilization: 60
> >       - type: Resource
> >         resource:
> >           name: memory
> >           target:
> >             type: Utilization
> >             averageUtilization: 60
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [values.yaml.log](https://github.com/milvus-io/milvus/files/8107701/values.yaml.log)
> 
> datacoord.dropTolerance is set too small, only one hour. , according to our 1 billion data benchmark test, it will take about an hour to load 170 million data. If compaction occurs during load, and the segment before compaction is dropped before loading into querynode memory, load will fail

@xige-16 what about modify the cleanup period to 24h by default?

**Comment by xiaofan-luan** [comment]
also we do need to improve the load speed since user can not wait an hour to load data, it should be in lazy mode and @yah01 is helping on load performance

**Comment by xige-16** [comment]
> 

@LoveEachDay can you help?

**Comment by xige-16** [comment]
> > > > 
> > > 
> > > 
> > > > > > seems like #12465 , can you paste your configuration about DataCoord here ?
> > > > > 
> > > > > 
> > > > > This is the log of the datacoord node. Thank you for your help Uploading datacoord.log…
> > > > 
> > > > 
> > > > thanks， and i want your config file.
> > > 
> > > 
> > > OK, here is our configuration file
> > > ```
> > > dataCoordinator:
> > >   enabled: true
> > >   replicas: 1           # Run Data Coordinator mode with replication disabled
> > >   resources: {}
> > >   nodeSelector: {}
> > >   affinity: {}
> > >   tolerations: []
> > >   extraEnv:
> > >   - name: GODEBUG
> > >     value: "madvdontneed=1"
> > > 
> > >   enableCompaction: true
> > >   enableGarbageCollection: true
> > > 
> > >   segment:
> > >     maxSize: 512  # Maximum size of a segment in MB
> > > 
> > >   compaction:
> > >     enableAutoCompaction: true
> > >     retentionDuration: 432000  # 5 days in seconds
> > > 
> > >   gc:
> > >     interval: 60   # gc interval in seconds
> > >     missingTolerance: 3600  # file meta missing tolerance duration in seconds, 1 day
> > >     dropTolerance: 3600  # file belongs to dropped entity tolerance duration in seconds, 1 day
> > > 
> > > 
> > >   service:
> > >     port: 13333
> > >     annotations: {}
> > >     labels: {}
> > >     clusterIP: ""
> > > 
> > > dataNode:
> > >   enabled: true
> > >   replicas: 3
> > >   resources: {}
> > >   nodeSelector: {}
> > >   affinity: {}
> > >   tolerations: []
> > >   extraEnv:
> > >   - name: GODEBUG
> > >     value: "madvdontneed=1"
> > >   flush:
> > >     insertBufSize: "16777216"  ## bytes, 16MB
> > >   autoscaling:
> > >     enabled: false
> > >     minReplicas: 2
> > >     maxReplicas: 5
> > >     metrics:
> > >       - type: Resource
> > >         resource:
> > >           name: cpu
> > >           target:
> > >             type: Utilization
> > >             averageUtilization: 60
> > >       - type: Resource
> > >         resource:
> > >           name: memory
> > >           target:
> > >             type: Utilization
> > >             averageUtilization: 60
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > [values.yaml.log](https://github.com/milvus-io/milvus/files/8107701/values.yaml.log)
> > 
> > 
> > datacoord.dropTolerance is set too small, only one hour. , according to our 1 billion data benchmark test, it will take about an hour to load 170 million data. If compaction occurs during load, and the segment before compaction is dropped before loading into querynode memory, load will fail
> 
> @xige-16 what about modify the cleanup period to 24h by default?

The default value on the master branch has been changed to 24h. @xiaofan-luan

**Comment by LoveEachDay** [comment]
> > 
> 
> @LoveEachDay can you help?
> 
> > > > s set to 24h
> > > 
> > > 
> > > The recommended gc config:
> > > ```
> > >   gc:
> > >     interval: 3600 # gc interval in seconds
> > >     missingTolerance: 86400 # file meta missing tolerance duration in seconds, 60*24
> > >     dropTolerance: 86400 # file belongs to dropped entity tolerance duration in seconds, 60*24
> > > ```
> > 
> > 
> > @xige-16 Hi xige, can I directly modify this configuration in our current milvus cluster? If yes, how should I do that? Thanks!
> 
> @LoveEachDay can you help?
Seems you deploy your cluster with milvus-helm chart, you can upgrade your cluster like the following:
```
helm upgrade <release-name> milvus/milvus --reuse-values --set dataCoordinator.gc.dropTolerance=86400
```
