### ISSUE TITLE
[Bug]: Disk usage with IVF_SQ8 seems odd

### ISSUE THREAD

**Issue by ufuk23** [milvus-io/milvus#15667]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.0
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): piymilvus 2.0.0
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 8 / 16 GB
- GPU: -
- Others: -
```

### Current Behavior

We have 160K entities that contain 2048 float vectors which are indexed using IVF_SQ8. When I tested 160K entities with random vectors the disk usage was about 15GB, it was normal. Then I try it on a pre-prod environment for 160K entities with real vectors I realized that the disk usage is 50GB. So I am not sure which is normal, 15 GB or 50 GB? The index type is the same, the code is the same, and the config is the same. So can anyone explain it?

By the way, I just changed the rocksmq parameter called 'retentionTimeInMinutes' as 60 minutes in config. The rest of the parameters are the same as the default.

**Comment by yanliang567** [comment]
@ufuk23  I assumed that the index params are also the same, right?

/assign @LoveEachDay 
/unassign

**Comment by LoveEachDay** [comment]
Milvus standalone deployment will use 3 pvcs: etcd, minio and milvus (for rocksmq).
Can you check the actual disk usage of milvus and minio?

**Comment by ufuk23** [comment]
> @ufuk23 I assumed that the index params are also the same, right?
> 
> /assign @LoveEachDay /unassign

Yes that's right

**Comment by ufuk23** [comment]
> Milvus standalone deployment will use 3 pvcs: etcd, minio and milvus (for rocksmq). Can you check the actual disk usage of milvus and minio?

![preProd](https://user-images.githubusercontent.com/8513827/154944892-da212059-ca1e-4086-90f3-c409aa6cf25f.png)

I think the test code to generate random entities with random vectors, generates 160K random vectors for some of the same primary keys. I mean, I haven't got a 160K unique pk but a 160K unique vector. For example, I have 160K vectors belonging to 50K primary keys. Does this point the reason for the problem? I thought that if I generate a 160K vector no matter what they belong, I can have the same case, but I think the indexing works differently and must be related with pk. Perhaps it explains what happened.

No matter what, I think 50 GB disk size for 160K vectors is not acceptable. I don't need three replicas to store. Can it be a config parameter?

**Comment by LoveEachDay** [comment]
Seems you use `ncdu` to show the disk usages, go down to the minio directory, check the disk usage for `insert_log` and `index_files` .

**Comment by ufuk23** [comment]
> Seems you use `ncdu` to show the disk usages, go down to the minio directory, check the disk usage for `insert_log` and `index_files` .
![preProd2](https://user-images.githubusercontent.com/8513827/154976948-811ca5d8-23ba-46dc-b9ba-28cefcf995d3.png)
![preProd3](https://user-images.githubusercontent.com/8513827/154976960-b3c8bde5-4545-4fa2-bbea-a76ca5f10bc1.png)
![preProd4](https://user-images.githubusercontent.com/8513827/154976972-9bf4017a-e61d-43b9-9ff8-adce9c7e9a4b.png)

**Comment by LoveEachDay** [comment]
You can use `pymilvus` api : `collection.num_entities` to check the number of records in your collection. 
I suspect that the minio volume is reused. May be the minio volume contain some old data?

**Comment by LoveEachDay** [comment]
The ratio of size-of-index/size-of-data is in the range of 25~30%, which meets the expectation.

**Comment by ufuk23** [comment]
> You can use `pymilvus` api : `collection.num_entities` to check the number of records in your collection. I suspect that the minio volume is reused. May be the minio volume contain some old data?

Thanks for your help. As I said before, the number of entities in the collection is 160.000, and I can check it via Attu GUI. I am sure that I remove the volume of the container with the 'rm -rf volumes' command before the indexing. So there must be no old data in that volume.

You said the ratio of 'size-of-index/size-of-data' seems normal, right?

**Comment by LoveEachDay** [comment]
Could you provide your collection schema and short code snippet? So we may reproduce in our environments.

**Comment by ufuk23** [comment]
`
fields = [
    FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, auto_id=False),
    FieldSchema(name="artifact_type", dtype=DataType.INT64),
    FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=2048)
]
schema = CollectionSchema(fields, "artifact")
print(fmt.format("Create collection `artifact`"))
artifact = Collection("artifact", schema, consistency_level="Strong")
`

...
`
index = {
    "index_type": "IVF_SQ8",
    "metric_type": "L2",
    "params": {"nlist": 128},
}
`

**Comment by ufuk23** [comment]
> Could you provide your collection schema and short code snippet? So we may reproduce in our environments.

I tested the above code again after I removed the volume. This time it produces unique primary keys for each vector. Now  I have 40K entities that use 10GB disk usage. And I think it is not normal for my test environment as well.

**Comment by LoveEachDay** [comment]
Using the same schema and insert 5000 records, the minio disk usage is as follows:
![image](https://user-images.githubusercontent.com/1573213/155107438-2fd26833-9351-401e-956c-963613b5b54b.png)

**Comment by ufuk23** [comment]
I suspected the milvus.yaml config file and tried again with the default milvus.yaml config, but get similar results for 5000 records.
![test1](https://user-images.githubusercontent.com/8513827/155130878-184d2662-7b69-4249-826d-cf0b537347a6.png)

**Comment by LoveEachDay** [comment]
Every time you call `artifact.num_entities`,  it will flush the data into a new segments. 
You can change your code without `artifact.num_entities`, and count the number of rows after insertion completed. 
You can check the disk usage after insertion.

**Comment by ufuk23** [comment]
> Every time you call `artifact.num_entities`, it will flush the data into a new segments.
> You can change your code without `artifact.num_entities`, and count the number of rows after insertion completed.
> You can check the disk usage after insertion.

Yes, it works as you said and the disk usage is reduced. I don't know why using num_entities method flushes the data into a new segment and causes the disk usage problem. Unless I don't use the num_entities, Attu GUI cannot show the correct entity count of the collection.

**Comment by LoveEachDay** [comment]
The disk usage problem is because by default we enabled the `segment compaction` , which will convert small segments into a bigger one, and the clean up for old segments is relatively long. So you will find it will takes up more disk space.

The config parameter for compaction is `dataCoord.enableCompaction`, you can find under `configs/milvus.yaml`.

The config parameter for old segment cleanup  is `dataCoord.gc.interval` and `dataCoord.gc.dropTolerance` .

If you want to know the number of entities in your collection, you should call `num_entities` . But you should not call this method frequently when you are inserting data. And you'd better insert data in a bigger batch. 

The default value of `rootCoord.minSegmentSizeToEnableIndex`  is 1024, which means if your number of entities in the segment is less than 1024, it won't create an index file.

You can still search the data even if it does not have any index files. Index files only make your search faster.

**Comment by LoveEachDay** [comment]
Milvus is complicated distributed system even if you use milvus standalone mode. We should provide better documentation to explain those config parameters.

The best practice is that you should insert your data in a bigger batch at 10k level based on the dimensions of your data. We've tested 50k with 128 dimension in about 2 seconds for 1b data volume.
