### ISSUE TITLE
[Bug]: Empty nodes in ATTU

### ISSUE THREAD

**Issue by scipe** [milvus-io/milvus#15666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.0
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): nvm
- OS(Ubuntu or CentOS): containered helm
- CPU/Memory: a lot of
- GPU: no
- Others: AWS EKS with latest 3.0.5 helm version
```

### Current Behavior

Attached screenshot, there is a lot of empty nodes in querynodes but actually it's scaled to 0
![new_issue](https://user-images.githubusercontent.com/3996622/154927827-3b5a5ac1-e489-42f9-a7d9-21d5d372762e.png)

### Expected Behavior

The list of nodes should be empty

**Comment by yanliang567** [comment]
@shanghaikid could you please help on this issue/

/assign @shanghaikid 
/unassign

**Comment by nameczz** [comment]
@scipe 
We try to set replicas 0 for querynodes. Everything is working fine.
<img width="1646" alt="image" src="https://user-images.githubusercontent.com/20559208/155074409-bddc2f25-dba7-4ca9-8ed5-b88f5a4c769b.png">

Could you please give us more details about Milvus helm setting and how to reproduce this issue?
Thanks.
