### ISSUE TITLE
[Enhancement]: Implement multi-cluster failover in milvus-sdk-java

### ISSUE THREAD

**Issue by huazaizai0322** [milvus-io/milvus#15677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

I will add some features in milvus-sdk-java as:
1. Multi-culster register.
2. Server monitor.
3. Server listener.

### Why is this needed?

I hava two issues as:
1. When cluster is unhealthy, I can not search util cluster recovery.
2. When a querynode is restarted, I will search timeout util this querynode completely load.

These two issues reduce the stability of the cluster, so I will implement multi-cluster failover in milvus-sdk-java.

### Anything else?

I will do this feature, I will open source to milvus-io/milvus-sdk-java.

**Comment by yanliang567** [comment]
@huazaizai0322 that's great. Thank you for your contributions to the community. If you need any help please feel free to ask here. 

/assign @huazaizai0322

**Comment by xiaofan-luan** [comment]
keep it posted, the progress happens on java SDK side

**Comment by yanliang567** [comment]
lets keep it on tracking
