### ISSUE TITLE
[Bug]: /volumes/pulsar/standalone/bookkeeper0/current have  lots of big.log file

### ISSUE THREAD

**Issue by blue216** [milvus-io/milvus#15704]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):'2.0.0rc8'
- OS(Ubuntu or CentOS): Centos
- CPU/Memory: 64G
- GPU: Tesla P4
- Others:
```

### Current Behavior

create 300 collections ,and every collection have tens of  partition,  every partioin have about 100 data,

lots of big .log file  generated  in   /volumes/pulsar/standalone/bookkeeper0/current , and   Waste disk space all the time 
![1](https://user-images.githubusercontent.com/6317368/155248327-b943e5e2-3476-4fd3-abf8-2dd61577eb83.png)
.

**Comment by yanliang567** [comment]
@blue216 Besides, it seems that you are still running on Milvus rc8, we strongly suggest you reinstall Milvus with latest 2.0 release. Milvus 2.0 uses pulsar cluster as default for milvus cluster mode, which was recommended by the pulsar community.

**Comment by LoveEachDay** [comment]
@blue216 By default we set the `defaultRetentionTimeMinutes` to `7 days` and `defaultRetentionSizeInMB` to `8G`. Those are parameters are applied to pulsar topics. 

You've created 300 collections, which would create many pulsar topics. if you want to decrease the pulsar storage  usage, you can decrease those two parameters in the `docker-compose.yaml` under `environment` section.

**Comment by blue216** [comment]
I have modify **defaultRetentionTimeMinutes**  to 3days, after  about  1hours later, some of collection will not be loaded any more  , and the program was blocked,

**Comment by blue216** [comment]
**"some of collection will not be loaded any more , and the program was blocked,"**
i have met the same thing when i delete manually  some .log files  a few days ago, then i have to drop all data, start all over again.

**Comment by LoveEachDay** [comment]
> 

Please upload the pulsar log. I suspect the `max direct memory` is too small for your scenario. 
And please note, docker-compose is not recommended for production use. Please use `milvus-helm` or `milvus-operator` to deploy milvus cluster in kubernetes.

**Comment by LoveEachDay** [comment]
> **"some of collection will not be loaded any more , and the program was blocked,"** i have met the same thing when i delete manually some .log files a few days ago, then i have to drop all data, start all over again.

You should not manually delete the files for pulsar. Change the config or use `pulsar-admin` to clean up.

**Comment by xiaofan-luan** [comment]
> @blue216 By default we set the `defaultRetentionTimeMinutes` to `7 days` and `defaultRetentionSizeInMB` to `8G`. Those are parameters are applied to pulsar topics.
> 
> You've created 300 collections, which would create many pulsar topics. if you want to decrease the pulsar storage usage, you can decrease those two parameters in the `docker-compose.yaml` under `environment` section.

We have a upper limit of 256 topics. All collection will share the 256 topics which we call it as physical channel

**Comment by xiaofan-luan** [comment]
> I have modify **defaultRetentionTimeMinutes** to 3days, after about 1hours later, some of collection will not be loaded any more , and the program was blocked,

Also, in rc8 some of the subscription is leaked thus may cause pulsar failed to to cleanup. Please retry with 2.0.1 and change defaultRetentionTimeMinutes which should solve your problem

If not, please offer the steps which can reproduce so we can test under our  own environment

**Comment by blue216** [comment]
> pulsar
![222](https://user-images.githubusercontent.com/6317368/155281769-4fd3dc4e-ac5f-4072-bf6c-3d009cce8537.png)

**Comment by blue216** [comment]
> > I have modify defaultRetentionTimeMinutes to 3days, after about 1hours later, some of collection will not be loaded any more , and the program was blocked,
> 
[pulsar1.log](https://github.com/milvus-io/milvus/files/8123178/pulsar1.log)

> Please upload the pulsar log. I suspect the `max direct memory` is too small for your scenario. And please note, docker-compose is not recommended for production use. Please use `milvus-helm` or `milvus-operator` to deploy milvus cluster in kubernetes.
[Uploading pulsar.log…]()

**Comment by blue216** [comment]
> > I have modify defaultRetentionTimeMinutes to 3days, after about 1hours later, some of collection will not be loaded any more , and the program was blocked,
> 
> Please upload the pulsar log. I suspect the `max direct memory` is too small for your scenario. And please note, docker-compose is not recommended for production use. Please use `milvus-helm` or `milvus-operator` to deploy milvus cluster in kubernetes.
[pulsar1.log](https://github.com/milvus-io/milvus/files/8123180/pulsar1.log)

**Comment by LoveEachDay** [comment]
Nothing unexpected happened in your pulsar1.log. Could you provide a detailed steps which can reproduce your issue?
