### ISSUE TITLE
[Bug]: Some DEBUG/INFO logs are printed before logging level is set.

### ISSUE THREAD

**Issue by soothing-rain** [milvus-io/milvus#15708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: latest master
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): N/A
- OS(Ubuntu or CentOS): Mac
- CPU/Memory: irrelevant
- GPU: irrelevant
- Others:
```

### Current Behavior

Milvus still prints some DEBUG/INFO logs when it is just brought up, even if logging level (that are set in milvus.yaml) was set WARNING or higher. However, these logs won't print after Milvus was successfully brought up.

Looks like some logs are set before logging level was set.

See the picture below:

<img width="1395" alt="image" src="https://user-images.githubusercontent.com/69466447/155270491-3d70f4a4-8736-477c-a02f-cdc412d30335.png">

### Expected Behavior

Not a single DEBUG/INFO log should be printed if log level was set to WARNING or higher.

### Steps To Reproduce

```markdown
1. Set logging level to WARNING or HIGHER.
2. Run Milvus standalone.
```

**Comment by xiaofan-luan** [comment]
seems that it might be unavoidable because the server start before we init log?
