### ISSUE TITLE
[Bug]: Instability; Deadline exceeded 

### ISSUE THREAD

**Issue by AlviseSembenico** [milvus-io/milvus#15703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.0
- Deployment mode(standalone or cluster): Cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.0.0
- OS(Ubuntu or CentOS): OS 
- CPU/Memory: K8S cluster
- GPU: No
- Others: No
```

### Current Behavior

Running the following function a couple of times causes milvus cluster to exceed any type of deadline for any kind of search.
```

search_params = {"nprobe": 10}
collection.search(
    data=data,
    anns_field="embedding",
    param=search_params,
    limit=limit,
)
data = [
        [d.data for d in datapoints],
        [1 for _ in datapoints],
        [cluster.id for cluster in data_index],
]
milvus.insert(collection, data)

results = milvus.collection.search(
            data=data,
            anns_field="embedding",
            param=search_params.dict(),
            limit=limit,
)
ids = list(map(lambda x: x.ids[0], results))
expr = "id in [" + ",".join(map(str, ids)) + "]"
collection.delete(expr)
client.flush([collection_name])
```

In general i've notice severe unstabilities causing any vector search not to respond.

### Expected Behavior

Search time should be consistent and the cluster should be reliable, not causing a stop of searches.

### Steps To Reproduce

```markdown
1. deploy milvus to kubernetes
2. create a collection with 768 size embedding
3. load collection in memory
4. run some search/insert operations
```

**Comment by yanliang567** [comment]
@AlviseSembenico thank you for the issue with detailed info. Could you please also help to upload the logs for pods: querynode, querycoord, rootcoord and proxy, especially for the logs around the period that it reproduces.

/assign @AlviseSembenico 
/unassign

**Comment by xiaofan-luan** [comment]
delete should be only used in small amount of the data, and it may cause your search slow until compaction is happened.

If you want to cleanup your collection then drop collection is what your are looking for. We don't recommend to do delete unless you want to cleanup a few entities
