### ISSUE TITLE
[Feature]: Support standby coordinator for fast recovery and HA

### ISSUE THREAD

**Issue by ss892714028** [milvus-io/milvus#15716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Milvus 2.0.0 does not support multi coordinator pod replicas. Although restarting Milvus coordinator pods are fast because they are stateless, it still takes several tens of seconds, and within that time, the Milvus service is not available. 

### Describe the solution you'd like.

It would be nice to have a standby coordinator pod along side the active coordinator pod. When the health check of the active coordinator fails, the standby coordinator pod steps in and keep the Milvus service available.

**Comment by yah01** [comment]
Should we achieve this with Raft? @ss892714028 @xiaofan-luan

**Comment by xiaofan-luan** [comment]
> Should we achieve this with Raft? @ss892714028 @xiaofan-luan

Milvus build on top of etcd and etcd is based on Raft. Most of the node liveness is maintained by etcd lease and so should the coordinator.

check Session_util.go if anyone interested in taking this feature
