### ISSUE TITLE
[Bug]:  Build milvus 2.0.1 from source fails on centos7

### ISSUE THREAD

**Issue by Bennu-Li** [milvus-io/milvus#15718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.1
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Centos7
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When building Milvus 2.0.1 from source on Centos7 (Use image: milvusdb/milvus-env:amd64-centos7-latest), I got  an error:
<img width="1033" alt="截屏2022-02-23 下午5 47 09" src="https://user-images.githubusercontent.com/53458891/155303729-3f59e649-c80d-479e-97f3-3249a322a6f2.png">

### Steps To Reproduce

```markdown
docker run -it --entrypoint bash --name build-milvus  milvusdb/milvus-env:amd64-centos7-latest
git clone https://github.com/milvus-io/milvus.git
git checkout ce9662c14011b36e3c64422aad2331e450a0a104
git checkout -b 2.0.1
./scripts/install_deps.sh
make install
```

**Comment by matrixji** [comment]
Meet the same problem while I'm compiling from fedora, seems issue from knowhere.

- https://github.com/milvus-io/knowhere/blob/98fa420755d95489f5bd8f3306d5cb74924fbf3b/thirdparty/CMakeLists.txt#L71
- https://github.com/milvus-io/knowhere/blob/98fa420755d95489f5bd8f3306d5cb74924fbf3b/thirdparty/CMakeLists.txt#L197

Here lib need to be ${LIBDIR} macro

**Comment by xiaofan-luan** [comment]
@cydrain has this issue been fixed?

**Comment by cydrain** [comment]
> @cydrain has this issue been fixed?

yes
