### ISSUE TITLE
[Feature]: Embedded Milvus in Python Wanted

### ISSUE THREAD

**Issue by GuillaumeWRLD** [milvus-io/milvus#15711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

As a data scientist, I don't care for Docker. Not a fan of Ubuntu or CentOS either BTW.

Pymilvus is pretty awesome, but I believe there are more things we can do.

An ideal journey for Milvus beginner IMO is:

0. A clean machine with python.
1. pip install milvus
2. $ python3
3. > import milvus
4. > createCollection(...)
5. > milvus.insert(...)
6. > milvus.search(...)
7. > exit()

**Comment by xiaofan-luan** [comment]
a embedded library is not only easy to maintain but also easier to use!
Let's make milvus running at everywhere

**Comment by soothing-rain** [comment]
@GuillaumeWRLD Hey we have drafted a proposal here: https://wiki.lfaidata.foundation/display/MIL/MEP+26+--+Embedded+Milvus

Let me know what you think of it.

**Comment by houlang** [comment]
> @GuillaumeWRLD嘿，我们在这里起草了一份提案：[https ://wiki.lfaidata.foundation/display/MIL/MEP+26+--+Embedded+Milvus](https://wiki.lfaidata.foundation/display/MIL/MEP+26+--+Embedded+Milvus)
> 
> 告诉我你对它的想法。

如果能做成像sqlite一样到处能跑，跨平台免安装且可以支持c++，java，python，那就非常棒了，例如：可以提供在windows下构建安装程序的接口(Milvus可跟着安装包一起被安装)。
It would be great to be able to run anywhere like sqlite, cross-platform installation-free and support c++, Java, python, for example, providing an interface to build installers in Windows (Milvus can be installed with the installation package). [machine translation]

**Comment by houlang** [comment]
我是蒋孝乐。已经收到您的来信，我会尽快回复。

**Comment by houlang** [comment]
我是蒋孝乐。已经收到您的来信，我会尽快回复。

**Comment by houlang** [comment]
我是蒋孝乐。已经收到您的来信，我会尽快回复。

**Comment by houlang** [comment]
我是蒋孝乐。已经收到您的来信，我会尽快回复。

**Comment by soothing-rain** [comment]
Done:
https://github.com/milvus-io/embd-milvus

/unassign

**Comment by GuillaumeWRLD** [comment]
Looks great!
