### ISSUE TITLE
[Bug]: Should unload segment if compaction removes the entire data

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#15714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Unload segment if compaction removed all data in the segment, like handoff but without loading a new segment to replace the old one

### Why is this needed?

This would save memory usage like compaction saves disk usage

**Comment by xiaofan-luan** [comment]
@yah01 good catch, I thought we can still reuse current mechanism. It's just a special case that load no segment while release some of the empty segment
