### ISSUE TITLE
[Bug]: grafana panel shows no data

### ISSUE THREAD

**Issue by dengtangxiaochou** [milvus-io/milvus#15717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.0
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/43942493/155297786-10a1c14a-10bc-44dc-a814-2550b285ee04.png)
![image](https://user-images.githubusercontent.com/43942493/155298767-e82d82db-5da5-4d72-bd21-9d192cc6a5b5.png)

grafana version v8.3.3
Use the data source accessed by prometheus that comes with ack, there is data in the data source,

**Comment by zwd1208** [comment]
How do you install Milvus instances on K8S?  The instance variable of Grafana is matched by app.kubernetes.io/instance label on pods. You may not have this tag on the Pod you deploy.

**Comment by dengtangxiaochou** [comment]
Deployed through the helm you provided, instance variable tags are available
![image](https://user-images.githubusercontent.com/43942493/155308535-b730517d-2e7f-4097-a08a-001c344d530e.png)

**Comment by LoveEachDay** [comment]
Seems like you install the milvus cluster with `milvus-helm` chart. By default, the service monitor is not enabled. You can run the following command to enable servicemonitor for milvus:
`helm upgrade <release-name> milvus/milvus --reuse-values --set metrics.serviceMonitor.enabled=true`

**Comment by LoveEachDay** [comment]
You'd better use the servicemonitor to add scrape targets for prometheus, instead of adding endpoints manually. The reason why the dashboard has no data, is because your scrape endpoint does not have labels required for the dashboard, like `app_kubernetes_io_instance`, etc.

**Comment by ganderaj** [comment]
@LoveEachDay @dengtangxiaochou @zwd1208 

I am encountering similar issue with my Milvus deployment deployed via milvus-helm helm chart. I had the Service Monitor enabled and Prometheus / Grafana stack installed per Milvus documentation.

I have confirmed that Targets under Status bar of Prometheus dashboard are all up and that Service Monitor is installed. I also confirmed that Prometheus is capturing data points by inspecting Prometheus "TSBD Status" and Grafana Default dashboards.

However, Dashboard published by Milvus is displaying "No Data". 

Can you please assist me here ?
[serviceMonitor-milvus-yml.txt](https://github.com/milvus-io/milvus/files/12552626/serviceMonitor-milvus-yml.txt)

![prometheus-Target-Status](https://github.com/milvus-io/milvus/assets/41026744/585db7eb-e606-4465-b744-012656eb9297)

![prometheus-TSDB-Status](https://github.com/milvus-io/milvus/assets/41026744/85b2fca5-3c34-45de-a5a6-c563407e069d)

![grafana-Milvus-Dashboard](https://github.com/milvus-io/milvus/assets/41026744/652e579c-deb1-4f8f-a4ad-747a7cccdc9c)

**Comment by ganderaj** [comment]
Please note that despite having a Milvus installation using milvus-helm chart with the name _"milvus"_, the _"Instance"_ field on the Grafana Dashboard shows no available releases.

<img width="931" alt="image" src="https://github.com/milvus-io/milvus/assets/41026744/ce73fc85-7c43-41c2-b74a-035d3dd3f1e9">

<img width="733" alt="image" src="https://github.com/milvus-io/milvus/assets/41026744/22546df5-0281-4ba0-a73d-839a21978c38">

**Comment by ganderaj** [comment]
I have also noticed that serviceMonitors (SM) correspond to "Targets" under Prometheus Dashboard and have realized that every such SM besides `milvus/milvus` are under `monitoring` namespace.

<img width="433" alt="image" src="https://github.com/milvus-io/milvus/assets/41026744/62d441c9-733a-44bb-8e0f-0a04f122d780">

I have tried creating a similar `Kind: serviceMonitor` under `monitoring` namespace just to rule out if this has anything to do with namespace. But to no avail.

Could you please guide what could potentially cause serviceMonitor:milvus/milvus not to show up on Prometheus/Targets ?
