### ISSUE TITLE
[Bug]: log.level setting in milvus.yaml is not working.

### ISSUE THREAD

**Issue by soothing-rain** [milvus-io/milvus#15720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: latest master
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): N/A
- OS(Ubuntu or CentOS): MacOS
- CPU/Memory: N/A
- GPU: N/A
- Others: N/A
```

### Current Behavior

The log.level setting in milvus.yaml file is not working. Changing it to "error“ or higher won't stop milvus from printing INFO and DEBUG logs.

A workaround to change log level is to update `const defaultLogLevel` in `internal/util/logutil/logutil.go`

**Comment by erezweissgloat** [comment]
Reproduced here.
milvus 2.1.1
log.level doesn't appear to change something. stays always DEBUG.

**Comment by yanliang567** [comment]
@erezweissgloat how did you change the log.level, could you please file a new issue ?
