### ISSUE TITLE
[Bug]: interface conversion: storage.FieldData is nil, not *storage.StringFieldData

### ISSUE THREAD

**Issue by lonyhandsome** [milvus-io/milvus#15739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The problem occurs at regular intervals.How can I solve it

panic: interface conversion: storage.FieldData is nil, not *storage.StringFieldData

goroutine 3821 [running]:
github.com/milvus-io/milvus/internal/storage.(*InsertCodec).Serialize(0xc002d04b60, 0x5fc98a59f740001, 0x5fc98a5a1040001, 0xc002369720, 0x5fc98a59f740001, 0xc002c04700, 0x0, 0x0, 0xb3c8fa, 0xc000010018, ...)
        /go/src/github.com/milvus-io/milvus/internal/storage/data_codec.go:364 +0x25ed
github.com/milvus-io/milvus/internal/datanode.(*rendezvousFlushManager).flushBufferData(0xc0003d5d90, 0xc001b284c8, 0x5fc98a5a1040001, 0x2f90000, 0xc001c61860, 0xc001c61801, 0x47e8c48)
        /go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:344 +0x1cc
github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate(0xc001906ea0, 0xc00284eb00, 0x1, 0x1, 0x3491c80, 0xc000fce870, 0x0)
        /go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:343 +0x1383
github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc00197d650)
        /go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:100 +0x214
created by github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start
        /go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:68 +0x55

**Comment by congqixia** [comment]
Hi @lonyhandsome , looks like you're using `StringField`, which are not supported in 2.0.

**Comment by yanliang567** [comment]
@lonyhandsome BTW, StringField is going to be supported soon in 2.1. 

/assign @lonyhandsome 
/unassign
