### ISSUE TITLE
[Bug]: For high dimensional vectors, the performance of load/release is poor

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#15736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.0
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

50000 vectors with 8192 dimensions. Each load action cost 20+ seconds. Each release action cost 10+ seconds.
The test script:

```
import random
import time
import numpy as np

from pymilvus import (
    connections,
    FieldSchema, CollectionSchema, DataType,
    Collection,
    utility
)

def main():
    create_connection()

    if has_collection("c1"):
        drop_collection("c1")

    dim = 8192
    field1 = FieldSchema(name="f1", dtype=DataType.INT64, description="int64", is_primary=True, auto_id=True)
    field2 = FieldSchema(name="f2", dtype=DataType.FLOAT_VECTOR, description="float vector", dim=dim)
    schema = CollectionSchema(fields=[field1, field2], description="collection description")
    collection = Collection(name="c1", schema=schema)
    print("collection created:")

    collection.create_partition("p1")

    for i in range(5):
        print("insert no.", i)
        data = [
            [[random.random() for _ in range(dim)] for _ in range(10000)],
        ]
        collection.insert(data=data, partition_name="p1")

    print(collection.num_entities)

    collection = Collection(name="c1")
    partition = collection.partition("p1")
    for i in range(5):
        start = time.time()
        partition.load()
        end = time.time()
        print("load cost", end-start, 'second')

        start = time.time()
        partition.release()
        end = time.time()
        print("release cost", end - start, 'second')
```

The output of this script on my machine:

```
Create connection...
Drop collection: c1
collection created:
insert no. 0
insert no. 1
insert no. 2
insert no. 3
insert no. 4
50000
load cost 28.67905354499817 second
release cost 14.894567489624023 second
load cost 27.665396213531494 second
release cost 14.983224630355835 second
load cost 27.160072326660156 second
release cost 15.195626974105835 second
load cost 28.676952123641968 second
release cost 15.21027946472168 second
load cost 28.271227836608887 second
release cost 15.401851415634155 second
```

### Expected Behavior

50000 vectors 8192 dimensions, the data size is about 1.6GB. It cost 28 seconds to load, average load speed is 58MB/sec, the performance is poor.

I expect the time cost is less than 5 seconds.

**Comment by xiaofan-luan** [comment]
@yhmo we probably need a detailed time analysis about where the time is consumed. 58M/sec seems to be a small number compared to SSD throughput

**Comment by xiaofan-luan** [comment]
duplicate with #15445

**Comment by xiaofan-luan** [comment]
we first need to figure out the bottleneck of load, does this related to growing segment(Performance issue of pulsar/rocksmq) or just the sealed segment is too large(Might be the binlog overhead is too large if we saw minio disk consumption is far more than 1.6GB or a performance issue of Minio. )

**Comment by yanliang567** [comment]
still working on it. 
/unstale

**Comment by yanliang567** [comment]
@yah01 was this completed fixed or need more fixes

**Comment by yah01** [comment]
> @yah01 was this completed fixed or need more fixes

It's completed

**Comment by xiaofan-luan** [comment]
should has a improvement on it for 2.1~
@yah01 did we enable binlog compression by default?

**Comment by yah01** [comment]
> should has a improvement on it for 2.1~ @yah01 did we enable binlog compression by default?

Yes, the compression for binlog and mq is enabled by default

**Comment by yah01** [comment]
Hi @yhmo @xiaofan-luan 
I just tested the performance with #17273:
load costs about 5.6 seconds, and release costs about 1 second.
I'm making it better, but it seems not to work for simply increasing the concurrent level.

**Comment by xiaofan-luan** [comment]
> Hi @yhmo @xiaofan-luan I just tested the performance with #17273: load costs about 5.6 seconds, and release costs about 1 second. I'm making it better, but it seems not to work for simply increasing the concurrent level.

Thought we need some basic profiling about the disk usage and cpu usage.

If Disk is key bottle neck(which I believe is the truth), change to higher compression rate might help, increase concurrency might also help, but network throughput is another concern.
If Cpu is the key bottle neck(Or memcpy), we might want to optimize the payloader reader code.
