### ISSUE TITLE
[Enhancement]: How to get all vector ids from Milvus2.0?

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#15745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

I used to use Milvus1.0. And I can get all IDs from Milvus1.0 by using get_collection_stats and list_id_in_segment APIs.

These days I am trying Milvus2.0. And I also want to get all IDs from Milvus2.0. But I don't find any ways to do it.

**Comment by xiaofan-luan** [comment]
maybe you can direct query with no expression and only specify id field

**Comment by JackLCL** [comment]
Sounds good. I will try it.

**Comment by xiaofan-luan** [comment]
@JackLCL  let me know if it works and you can paste your example code if it works

**Comment by JackLCL** [comment]
![image](https://user-images.githubusercontent.com/53512883/155914979-ab73c51d-1c6f-4947-a7a8-3f4eba1a32f5.png)

@xiaofan-luan It doesn't work.

**Comment by ss892714028** [comment]
> ![image](https://user-images.githubusercontent.com/53512883/155914979-ab73c51d-1c6f-4947-a7a8-3f4eba1a32f5.png)
> 
> @xiaofan-luan It doesn't work.

You can do something like this:

```python
res = collection.query(expr = "id not in [892714028]", 
                                       output_fields = ["id"])
```
This gets all vector ids except id `892714028`. However, Milvus currently does not support pagination, in one batch the result will probably exceed rpc transfer limit.

**Comment by JackLCL** [comment]
![image](https://user-images.githubusercontent.com/53512883/155931286-87ccd207-bfbd-42c3-89e7-c8ca973d49c4.png)

@ss892714028 I try your way, but it still doesn't work.

**Comment by ss892714028** [comment]
> ![image](https://user-images.githubusercontent.com/53512883/155931286-87ccd207-bfbd-42c3-89e7-c8ca973d49c4.png)
> 
> @ss892714028 I try your way, but it still doesn't work. Milvus can't return results.

Can you try with a smaller collection?

**Comment by JackLCL** [comment]
I have 1M vectors in this collection. And I want to export all IDs from it.
As you mentioned above, Milvus currently does not support pagination to return results. I think it's the reason that the query API can't return all the results at one time.

**Comment by JackLCL** [comment]
I just found that I didn't forward 19530 port.
After forwarding it, I can get all IDs from Milvus.
Thanks @ss892714028

**Comment by ss892714028** [comment]
@xiaofan-luan Do we have plans for MilvusDM 2.0?

**Comment by xiaofan-luan** [comment]
Once we support bulkload in Milvus 2.1 we will start the Milvus DM 2.0 project~
