### ISSUE TITLE
[Bug]: Can't insert any data to the milvus cluster

### ISSUE THREAD

**Issue by parsa-ra** [milvus-io/milvus#15765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.1 
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.1 
- OS(Ubuntu or CentOS): Ubuntu 20.04 nodes
- CPU/Memory: (16/64) * 7
- GPU: None
- Others:
```

### Current Behavior

After deploying the milvus2.0.1 in cluster mode and inserting about 300M vectors in different partitions cannot insert data into the cluster anymore without any error.
![image](https://user-images.githubusercontent.com/11356471/155847535-7298af57-9822-483d-b4f7-24b20b440d5d.png)

After playing with the logs a bit I found that a couple of segments are waiting to be flushed
Here you can find the output of stern for "proxy" and "datanode" arguments.
[logs.zip](https://github.com/milvus-io/milvus/files/8146845/logs.zip)

### Steps To Reproduce

```markdown
1. Launch Milvus 2.0.1 in cluster mode 
2. Insert about 300M vectors (384 and 256 dim) in multiple partitions
3. Creating indices
4. Putting cluster to query and insertion load 
5. After a while requests timed-out
6. Bringing the deployment down and clearing the pulsar PVCs
7. Deploying again (without modifying etcd and minio PVCs as an HPA test)
8. Can query vector but can't insert any other vectors
```

**Comment by parsa-ra** [comment]
Yeah but as I mentioned in the reproduce steps the cluster went AOL even before clearing out the pulsar PVCs

**Comment by xiaofan-luan** [comment]
@parsa-ra is this log before you clean the PVC or after that? seems that flush is stucked but it might be caused by removal the data out of pulsar PVC. 
Milvus has persistant state on both etcd and pulsar and remove data only on pulsar may not be valid.

If on the step 5 the requests are still stucked, for search we will need proxy/querynodes log and for insert we need proxy, datacoord and datanodes

**Comment by parsa-ra** [comment]
The log is for after cleaning up the pulsar state. 
Here is the log for after cleaning up the pulsar's PVCs for proxy, datanodes and datacoord after clearing PVCs while running and INSERTION job for about 1 minutes. 
stern Query
```bash 
stern 'data|mil-milvus-proxy' > logs_stern_data$(date -u +"%Y-%m-%dT%H:%M:%SZ").logs
+ mil-milvus-proxy-68dc85bf64-mz7wt › proxy
+ mil-milvus-proxy-68dc85bf64-n92hk › proxy
+ mil-milvus-proxy-68dc85bf64-649j6 › proxy
+ mil-milvus-datacoord-687ff584df-jmhjt › datacoord
+ mil-milvus-datanode-565897546-54zcx › datanode
+ mil-milvus-datanode-565897546-zcxfx › datanode
+ mil-milvus-datanode-565897546-2p85g › datanode
```
[logs_stern_data2022-02-27T03:49:32Z.zip](https://github.com/milvus-io/milvus/files/8147992/logs_stern_data2022-02-27T03.49.32Z.zip)


Please let me know if you guys require more logs.

**Comment by godchen0212** [comment]
It seems the datanode cannot receive any data from channel by-dev-rootcoord-dml_1_431390997700935681v1. 
It is temporarily impossible to know whether it is the problem of pulsar or the mechanism of physical channel distribution to vChannel. You need to look at the log of pulsar. 
It is temporarily suspected that the excessive data (about 450G) may cause pulsar to fail to serve.

**Comment by parsa-ra** [comment]
@godchen0212 Please let me know the experiment of the pulsar log that you need me to provide you, e.g. putting the milvus in insertion load at the specific collection meanwhile capturing the pulsar logs ...

**Comment by parsa-ra** [comment]
@LoveEachDay , got it, all of the brokers, or do you have any specific in mind?

**Comment by xiaofan-luan** [comment]
pulsar backlog issues
