### ISSUE TITLE
Background build index thread not work after compact

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#1576]
**Describe the bug**
Background build index thread not work after compact

**Steps/Code to reproduce behavior**
1. create a table
2. create index IVFLAT
3. insert some vectors(data size exceed index_file_size)
4. flush
5. wait background thread build index finish
6. delete some vectors by id
7. compact

result: new segment generated, but background build index not work
expect: after compact, background build index should build index for the new segment

**Comment by youny626** [comment]
For now, if the data size is smaller than index_file_size after compaction, it won't build index. You might want to change the behaviour.

**Comment by yhmo** [comment]
mistake, not a bug
