### ISSUE TITLE
[Feature]: Refine Get Entity Count

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#15766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

GetEntityCount is a big headache for now due to the following reasons:
1) Get Entity count need to call flush so the meta data of each segment is accurate
2) Collection with delete entities can not can't accurately

### Describe the solution you'd like.

I'm proposing to change get entity count from collect meta to collect data in each segment.
1) each segment maintain it's entity count, when insert/delete happens
2) Like Query, get entity count is sent to each querynode, do the aggregation, and response back to proxy and do a reduce.

With this feature, we can implement further aggregation functions such as COUNT, GROUPBY, SUM,..

**Comment by ss892714028** [comment]
This sounds like a promising solution. However, if query node takes care of count_entities, does it require to load all segments into memory? If it does, it is quite heavy.

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan This sounds like a promising solution. However, if query node takes care of count_entities, does it require to load all segments into memory? If it does, it is quite heavy.

It has to, that's a issue but seems that we don't have a perferct solution on that
