### ISSUE TITLE
[Feature]: Extract data directly from Milvus 2.0's storage

### ISSUE THREAD

**Issue by ss892714028** [milvus-io/milvus#15793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

There is currently no way to extract all data from Milvus. With query, since query does not support empty expression field, it cannot be done even by batch without having access to all IDs.  To get all IDs, expr like "ID not in [an_id]" can be used but with [RPC limit](https://milvus.io/docs/v2.0.0/limitations.md#Input-and-Output-per-RPC) of 512 MB, one can only do this with collection size < roughly 100 million. Plus, query is relatively slow for a task like this.

Detailed discussion is in this issue: https://github.com/milvus-io/milvus/issues/15745 

As a database, Milvus should be able to persist and return all of the vectors to user when needed. 

### Describe the solution you'd like.

A solution to extract data from Milvus 2.x directly from its storage. like [MilvusDM](https://github.com/milvus-io/milvus-tools) for Milvus 1.x.

**Comment by xiaofan-luan** [comment]
agree this is an important feature but we don't have enough man power.
Anyone interest can do self assign
