### ISSUE TITLE
[BUG]发生多次table not exist exceptions后进程会卡住

### ISSUE THREAD

**Issue by LmYjQ** [milvus-io/milvus#158]
**Describe the bug**
发生多次table not exist exceptions后进程会卡住

**Steps/Code to reproduce behavior**
执行下面的代码，预期产生1000个假数据，做1000次查询最后输出finish。
实际查到第22次就会卡住
```
import subprocess
from milvus import Milvus, IndexType
from milvus.client.Exceptions import *
from contextlib import contextmanager
from functools import wraps
from pprint import pprint
import sys, os
import time
import random
import concurrent
__name__ = 'AdvancedExample'

_HOST = '172.17.115.5'
_PORT = '19530'
RETRY_TIMES = 3
NORMAL_TIMES = 10

DIMENSION = 192
NUMBER = 1000
TOPK = 10
TABLE_NAME = 'DEMO'

HEADER = "            id              |       L2 distance        "
FORMAT = "    {}     |    {}    "

def generate_vectors():
    # Generating 200000 vectors
    print('Generating {}-dimension vectors ...\n'.format(DIMENSION))
    records = [[random.random() for _ in range(DIMENSION)] for _ in range(NUMBER)]
    platform_cates = ['NameNotExist' for _ in range(NUMBER)]
    return records, platform_cates

class ConnectionHandler(object):
    """Handler connection with the server
    reconnection and connection errors are properly handled
    """

    def __init__(self, host, port):
        self.host = host
        self.port = port
        self._retry_times = 0
        self._normal_times = 0
        self._client = None

    @property
    def client(self):
        return self._connect(10000)

    @property
    def can_retry(self):
        if self._normal_times >= NORMAL_TIMES:
            self._retry_times = self._retry_times - 1 if self._retry_times > 0 else 0
            self._normal_times -= NORMAL_TIMES
        return self._retry_times <= RETRY_TIMES

    def _connect(self, timeout=1000):
        client = Milvus()
        client.connect(self.host, self.port, timeout=timeout)
        return client

    def connect(self, func):
        @wraps(func)
        def inner(*args, **kwargs):
            while self.can_retry:
                try:
                    return func(*args, **kwargs)
                except NotConnectError:
                    self._retry_times += 1
                    if self.can_retry:
                        print('Reconnecting to {} .. {}'.
                              format(_HOST + ':' + _PORT, self._retry_times))
                        continue
                    else:
                        sys.exit(1)
        return inner

api = ConnectionHandler(host=_HOST, port=_PORT)


@api.connect
def version():

    # get client version
    version = api.client.client_version()
    print('Client version: {}\n'.format(version))

    # get server version
    status, version = api.client.server_version()
    if status.OK():
        print('Server version: {}\n'.format(version))
    else:
        print(status.message)

@api.connect
def describe_table():

    # Get schema of table demo_table
    status, schema = api.client.describe_table(TABLE_NAME)
    if status.OK():
        print('Describing table `{}` ... :\n'.format(TABLE_NAME))
        print('    {}'.format(schema), end='\n\n')
    else:
        print(status.message)

@api.connect
def search_vectors(q_records, platfrom_cate):
    TABLE_NAME = platform_cate
    # Search 1 vector
    param = {
        'table_name': TABLE_NAME,
        'query_records': q_records,
        'top_k': TOPK,
    }

    # Search vector
    status, results = api.client.search_vectors(**param)
    if status.OK():
        print('Get a vector from table `{}`. '
              'Searching its {} nearest vectors from table `{}` ... \n'.
              format(TABLE_NAME, TOPK, TABLE_NAME))
        print(HEADER)
        print('-' * 28 + '+' + '-'*27)
        for result in results:
            for qr in result:
                key = idmap.get(str(qr.id))
                print(FORMAT.format(key, qr.distance))
        print('')
    else:
        print(status.message)

def get_records():
    # Generate vectors
    records,  platform_cates = generate_vectors()
    ret = zip( platform_cates, records)
    return ret


if __name__ == 'AdvancedExample':
    # Get version of client and server
    version()
    ret = get_records()
    # Search by the first vector added
    cnt = 0
    for platform_cate,q_record in ret:
        cnt += 1
        search_vectors([q_record],platform_cate)
        print('{} query'.format(cnt))
    print('finish!')
```

**Expected behavior**
我脚本的功能是读取一批测试数据，循环做search_vector操作。当出现多次table not exist exceptions之后进程会卡住不动。

**Environment details**
- Hardware/Softward conditions: centos 
- Method of installation: milvus:0.3.1-cw4
- Milvus python client version 0.1.25, Server version: 0.3.1
- Milvus configuration (Settings you made in `server_config.yaml`) 默认配置只改了host
server_config:
  address: 172.17.115.5
  port: 19530                      # the port milvus listens to, default: 19530, range: 1025 ~ 65534
  gpu_index: 0                     # the gpu milvus uses, default: 0, range: 0 ~ gpu number - 1
  mode: single                     # milvus deployment type: single, cluster

db_config:
  db_path: /tmp/milvus             # milvus data storage path
  db_salve_path:                   # secondry data storage path, split by semicolon
  parallel_reduce: false           # use multi-threads to reduce topk result

  # URI format: dialect://username:password@host:port/database
  # All parts except dialect are optional, but you MUST include the delimiters
  # Currently dialect supports mysql or sqlite
  db_backend_url: sqlite://:@:/

  index_building_threshold: 1024   # index building trigger threshold, default: 1024, unit: MB
  archive_disk_threshold: 0        # triger archive action if storage size exceed this value, unit: GB
  archive_days_threshold: 0        # files older than x days will be archived, unit: day
  insert_buffer_size: 4            # maximum insert buffer size allowed, default: 4, unit: GB, should be at least 1 GB.
                                   # the sum of insert_buffer_size and cpu_cache_capacity should be less than total memory, unit: GB

metric_config:
  is_startup: off                      # if monitoring start: on, off
  collector: prometheus                # metrics collector: prometheus
  prometheus_config:                   # following are prometheus configure
    port: 8080                         # the port prometheus use to fetch metrics
    push_gateway_ip_address: 127.0.0.1 # push method configure: push gateway ip address
    push_gateway_port: 9091            # push method configure: push gateway port

cache_config:
  cpu_cache_capacity: 25               # how many memory are used as cache, unit: GB, range: 0 ~ less than total memory
  cache_free_percent: 0.85             # old data will be erased from cache when cache is full, this value specify how much memory should be kept, range: greater than zero ~ 1.0
  insert_cache_immediately: false      # insert data will be load into cache immediately for hot query

engine_config:
  nprobe: 32                           # number of queried vector buckets.
  nlist: 16384                         # number of vector buckets in a file. Default value is 16384.
  use_blas_threshold: 801               # threshold that triggers the usage of OpenBLAS or Intel MKL libraries. Default value is 20.
  metric_type: L2                      # compare vectors by euclidean distance(L2) or inner product(IP), optional: L2 or IP

**Screenshots**
![image](https://user-images.githubusercontent.com/12581433/67937750-16dd0700-fc09-11e9-9ceb-99780a238b19.png)

**Additional context**

**Comment by LmYjQ** [comment]
> This issue is in 0.5.0 release, or master branch ?

The docker I use is  milvus:0.3.1-cw4, and python client version 0.1.25, Server version: 0.3.1

**Comment by cydrain** [comment]
ok, we will check this issue.

**Comment by JinHai-CN** [comment]
@del-zhenwu @BossZou Can this issue be reproduced? please update the issue on time.

**Comment by cxie** [comment]
Milvus 0.5.1 has been released today, which includes a significant number of important bug fixes and enhancements.  We highly encourage you to try it out. 

Mark this issue as CLOSED at the moment. Please reopen if it reoccurs in 0.5.1.
