### ISSUE TITLE
[Bug]:  [mishards] routing to old pod which has been updated with a new name on k8s resulting in failling for searching requests

### ISSUE THREAD

**Issue by vtkingdom** [milvus-io/milvus#15808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:1.1.1
- Deployment mode(standalone or cluster): mishards
- SDK version(e.g. pymilvus v2.0.0rc2): go 1.1.0
- OS(Ubuntu or CentOS):  uubuntu
- CPU/Memory:  4C:8GB
- GPU: None
- Others:
```

### Current Behavior

Uisng mishards for milvus1.1.1.
when the readonly milvus pod on k8s has changed to a new one which has different pod name, searching through mishards will report error like:  "Conn Group milvus-readonly-85cb44586b-wbpb2 is Empty. Please Check your configurations". As mentioned，the pod which is reported has already been removed from k8s and restart with a new name.
this error will result in failling for every searching request

**Comment by yanliang567** [comment]
/assign @yhmo 
could you please help on this issue?
/unassign
