### ISSUE TITLE
Old segment folder not removed after merge / compact if create_index is called before adding data

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#1580]
**Describe the bug**
Old segment folder not removed after compact

**Steps/Code to reproduce behavior**
1. create a table, index_file_size = 256M, dimension=512
2. create index IVFLAT
3. insert 200000 vectors in one batch, id from 0 to 199999
4. flush
5. delete vectors id from 5 to 199990
6. flush
7. compact

result: there are only one segment in TableFiles, but there are two segment folders under /milvus/db/tables

**Comment by youny626** [comment]
Since we still have this bug: #1530 . Raw file's index type is not IDMAP if create_index is called before adding data. And we determine whether we should remove segment folder based on the table file's index type. If it's not IDMAP, then nothing will be removed in the case.

**Comment by JinHai-CN** [comment]
Will this bug impact any functions?

**Comment by yhmo** [comment]
No compact, just waste disk storage, out of disk after some days
