### ISSUE TITLE
[Bug][benchmark][cluster]: Slow transfers in proxy to pulsar when inserting

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#15807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

In the same scenario, inserting the same data, with a 2x difference in rps, and finding a 2x difference in proxy client producer latency

![20220301-190039](https://user-images.githubusercontent.com/34296482/156157393-5f17156a-f320-49f4-ac19-0c37e48382e4.png)
![20220301-190027](https://user-images.githubusercontent.com/34296482/156157379-a644b778-9cc4-4666-995a-aaca25941641.png)
server-configmap
server-cluster-dn8c32g-in2c2g-qn2c2g
client-configmap
pre2.0-client-insert-locust-client1-nb1k
pre2.0-client-insert-locust-concurrent-client1-nb1k：7 pod
```
{
	"config.yaml": "locust_random_concurrent_performance:
		  collections:
		    - 
		      collection_name: sift_10w_128_l2
		      ni_per: 50000
		      build_index: false
		      index_type: ivf_sq8
		      index_param:
		        nlist: 1024
		      task: 
		        connection_num: 1
		        clients_num: 1
		        spawn_rate: 1 
		        during_time: 600
		        types:
		          -
		            type: insert
		            weight: 1
		            params:
		              ni_per: 1000
		"
}
```

### Steps To Reproduce
1、create collection
2、build index of ivf_sq8
3、insert  10w  vectors
4、flush
5、build index with the same params
6、load
7、locust concurrent: insert 1k data ;  use  7 pods

**Comment by xiaofan-luan** [comment]
didn't get the issue, rps refers to read per second?

**Comment by XuanYang-cn** [comment]
@jingkl What service does the hightest blue line refer to?

**Comment by jingkl** [comment]
> didn't get the issue, rps refers to read per second?

The blue line indicates the specific pulsar producer latency of the corresponding topic

**Comment by jingkl** [comment]
> rps refers to read per second?



> didn't get the issue, rps refers to read per second?

Equivalent to the number of response requests per second (QPS)

**Comment by xiaofan-luan** [comment]
> 

if rps refers to request to per second, that might be valid because each pulsar topic should has limited throughput, once you reached throughput limit increate concurrency won't help on more throughputs.

You can try to tune the pulsar broker config and see if the throughput increase. If not then there might be some performance bottleneck(Maybe a lock or what) but  so far as long as we can reach 100M/s throughput that should be well enough for the users

**Comment by XuanYang-cn** [comment]
let's keep tracking this issue

**Comment by XuanYang-cn** [comment]
keep it on
