### ISSUE TITLE
[Bug]: Image data processed with Towhee cannot be inserted into Milvus ymilvus.orm.exceptions.DataTypeNotSupportException: <DataTypeNotSupportException: (code=0, message=Field dtype must be of DataType)>

### ISSUE THREAD

**Issue by ck-w-0** [milvus-io/milvus#15815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.1
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.1
- OS(Ubuntu or CentOS): wsl2:ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I run the reverse image search  demo in the Toehee documentation，insert the data getting this err
Traceback (most recent call last):
  File "ex_image.py", line 57, in <module>
    collection.insert(data1)
  File "/mnt/e/wsl2/ubuntu/my_project_env/lib/python3.7/site-packages/pymilvus/orm/collection.py", line 535, in insert
    if not self._check_insert_data_schema(data):
  File "/mnt/e/wsl2/ubuntu/my_project_env/lib/python3.7/site-packages/pymilvus/orm/collection.py", line 179, in _check_insert_data_schema
    infer_fields = parse_fields_from_data(data)
  File "/mnt/e/wsl2/ubuntu/my_project_env/lib/python3.7/site-packages/pymilvus/orm/schema.py", line 297, in parse_fields_from_data
    fields.append(FieldSchema("", d_type))
  File "/mnt/e/wsl2/ubuntu/my_project_env/lib/python3.7/site-packages/pymilvus/orm/schema.py", line 172, in __init__
    raise DataTypeNotSupportException(0, ExceptionsMessage.FieldDtype)
pymilvus.orm.exceptions.DataTypeNotSupportException: <DataTypeNotSupportException: (code=0, message=Field dtype must be of DataType)>

**Comment by ck-w-0** [comment]
> which document are you referring to? Actually, you can follow [this tutorial](https://docs.towhee.io/tutorials/reverse-image-search/) to run [reverse image search](https://github.com/towhee-io/towhee/blob/main/tutorials/reverse_image_search.ipynb).

this one too

**Comment by shiyu22** [comment]
Are you using towhee==0.4.0? I have tried it with towhee0.4.0 and it works.

**Comment by shiyu22** [comment]
> yes,maybe my environment are wrong，i use ubuntu in wls2. 我的环境下跑milvus的插入随机生成的数据没有问题，但是图片转化后的数据就有DataTypeNotSupportException，用过您写的towhee文档教程是这样的，我尝试tensorflow+keras下的resnet也是这样，不知道是否是我的环境问题。感谢您之前的解答！

I think that you need to check the data type of the vector before inserting it into Milvus. The data shape of the entity should be like this:
```bash
entities = [
    [[random.random() for _ in range(8)] for _ in range(3000)]  # field embeddings
]
```

**Comment by ck-w-0** [comment]
> > yes,maybe my environment are wrong，i use ubuntu in wls2. 我的环境下跑milvus的插入随机生成的数据没有问题，但是图片转化后的数据就有DataTypeNotSupportException，用过您写的towhee文档教程是这样的，我尝试tensorflow+keras下的resnet也是这样，不知道是否是我的环境问题。感谢您之前的解答！
> 
> I think that you need to check the data type of the vector before inserting it into Milvus. The data shape of the entity should be like this:
> 
> ```shell
> entities = [
>     [[random.random() for _ in range(8)] for _ in range(3000)]  # field embeddings
> ]
> ```

can you print collection.schema you created? thx!
if i change vec_dim = len(vectors[0]) to vec_dim = len(vectors[0][0]) i can insert data
