### ISSUE TITLE
[Bug]: Flush and index time will increase a lot (3.4->35,4->12) if minio IO latency(write/read/flush) is 200ms

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#15837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220302-27a7875a
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.0.1.dev3
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/156488891-25d23c5d-863d-4c52-b9af-c55485e69713.png)

### Expected Behavior

Do not have an exact expectation, but don't think the current result is reasonable

### Steps To Reproduce

```markdown
see GitHub action https://github.com/zhuwenxing/milvus/runs/5396666360?check_suite_focus=true
```

### Anything else?

logs: https://github.com/zhuwenxing/milvus/suites/5510603573/artifacts/176541754

**Comment by yanliang567** [comment]
@czs007 would we have a more details for this test if milvus metrics are ready ?
/assign @czs007 
/unassign

**Comment by xiaofan-luan** [comment]
We are expecting minio to deliver 10ms level latency under most cases...

**Comment by zhuwenxing** [comment]
In this job https://github.com/zhuwenxing/milvus/runs/5403688905?check_suite_focus=true，minio IO latency is 10ms， flush latency is still large (3.8->39.4).
But this may be caused by the Github action runner, because, in the local k8s cluster, the latency increase is acceptable(2.8->4.4)
