### ISSUE TITLE
[Bug]: milvusdb/milvus goes on exited status frequently after loading collection

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#15835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.1
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): Attu
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

milvusdb/milvus container goes on exited status after that proxy healthy error.
it was working fine till morning but at day time this error began to show up.

**Comment by yhmo** [comment]
The log of milvus server:
[milvus_logs.txt](https://github.com/milvus-io/milvus/files/8174260/milvus_logs.txt)

**Comment by yanliang567** [comment]
@yhmo what is the proxy healthy error? how do we reproduce this error? what did we do between working fine and exited statue?

**Comment by yhmo** [comment]
> @yhmo what is the proxy healthy error? how do we reproduce this error? what did we do between working fine and exited statue?

Wait for the user provides more information.

**Comment by congqixia** [comment]
Here is the panic output in the log
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  unsupported data type
SIGABRT: abort
PC=0x7f23aab76fb7 m=5 sigcode=18446744073709551610
```
looks like the collection has a field which is not supported.

**Comment by yanliang567** [comment]
/assign @yhmo 
please help to update the details as the user responses.

/unassign

**Comment by yhmo** [comment]
https://app.slack.com/client/TM98LD8DQ/D03599XB5U2

**Comment by yhmo** [comment]
The user has resolved it, not a bug, close it.
