### ISSUE TITLE
[B]: Variable names in RootCoord are misleading

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#15849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. `GetNotIndexedSegments` actually writes Etcd inside.
2. `indexMeta` and `idxInfo` both are variables of `IndexInfo struct`, which influences codes readability.

/assign @xiaocai

**Comment by xiaofan-luan** [comment]
@XuanYang-cn Agree, I also open another issue about index part and we need some refactor on this

**Comment by xiaocai2333** [comment]
keep it open

**Comment by yanliang567** [comment]
keep it on tracking
