### ISSUE TITLE
mysql chart error

### ISSUE THREAD

**Issue by surjits254** [milvus-io/milvus#1584]
mysql chart deployment file still using apiversion: extensions/v1beta1 instead of apiversion: app/v1 this is making helm command to fail is there any workaround for this?

**Comment by ZhifengZhang-CN** [comment]
@surjits254 https://github.com/milvus-io/milvus-helm/blob/master/requirements.yaml
Change MySQL Helm Version to 1.6.2

Update Milvus Helm dependency
```shell
$ cd milvus-helm/
$ helm dependency update .
```
