### ISSUE TITLE
[Bug]: load failed, OOM if loaded due to memory size too large

### ISSUE THREAD

**Issue by drow931** [milvus-io/milvus#15852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.1
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.2
- OS(Ubuntu or CentOS): centos 7.2
- CPU/Memory: 48-Core/131431556 kB
- GPU: no
- Others:
```

### Current Behavior

When I execute load() ，logs：
`[impl.go:342] ["load segment failed, OOM if load, collectionID = 431544206256242689, maxSegmentSize = 411145909, usedMemAfterLoad = 1291290570, totalMem = 18446744073709551615, thresholdFactor = 0.900000"]`

due to segment_loader.go.checkSegmentSize()  overflows int64

`
// when load segment, data will be copied from go memory to c++ memory
	if usedMemAfterLoad+maxSegmentSize > int64(float64(totalMem)*Params.QueryNodeCfg.OverloadedMemoryThresholdPercentage) {
		return fmt.Errorf("load segment failed, OOM if load, collectionID = %d, maxSegmentSize = %d, usedMemAfterLoad = %d, totalMem = %d, thresholdFactor = %f",
			collectionID, maxSegmentSize, usedMemAfterLoad, totalMem, Params.QueryNodeCfg.OverloadedMemoryThresholdPercentage)
	}
`

**Comment by yanliang567** [comment]
@jaime0815 could you please help on this issue?
/assign @jaime0815 
/unassign

**Comment by drow931** [comment]
Further findings from this bug，I find totalMemory numeric types is uint64，maximum 18446744073709551615

**Comment by xiaofan-luan** [comment]
close it with fix
