### ISSUE TITLE
[Enhancement]: IndexNode only supports task concurrency of 1

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#15850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Should it be more than 1? Why?

/assign @czs007

**Comment by xiaofan-luan** [comment]
so far 1  works for me because the index build task itself can be done in parallel. Concurrent build might need control in memory consumption.

We can do more experiment later on
