### ISSUE TITLE
[Enhancement]: Support multiple indexes on different fields

### ISSUE THREAD

**Issue by longjiquan** [milvus-io/milvus#15867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

I want to support multiple indexes on different fields. For now, Milvus only supports index on vector field, and beside this, only one field in a collection can have index now. It's not convinient if we need better performance when we do attribute filtering. Like other database systems, we can create index for specific field and a field with index may be searched faster. In addition, the size of a field with index may be less than the raw field, thus will decrease the load time of a collection.

**Comment by xiaofan-luan** [comment]
agree, and we can also support build index on different vector index

**Comment by xiaofan-luan** [comment]
keep tracking
