### ISSUE TITLE
set_config shows wrong status

### ISSUE THREAD

**Issue by sahuang** [milvus-io/milvus#1587]
**Describe the bug**
When trying to set cpu_cache_capacity out of memory, sdk returns set successfully and status ok, but server side actually does not set it.

**Steps/Code to reproduce behavior**
- test case
```python
    def test_set_cache_config_out_of_memory_value_B(self, connect, collection):
        '''
        target: set cpu_cache_capacity / insert_buffer_size to be out-of-memory
        method: call set_config with invalid values
        expected: status not ok (cpu_cache_capacity + insert_buffer_size < system memory)
        '''
        self.reset_configs(connect)
        mem_available = self.get_memory_available(connect)
        logging.getLogger().info(mem_available)
        status, cpu_cache_capacity = connect.get_config("cache_config", "cpu_cache_capacity")     
        assert status.OK()
        logging.getLogger().info(cpu_cache_capacity)
        status, insert_buffer_size = connect.get_config("cache_config", "insert_buffer_size")     
        assert status.OK()
        logging.getLogger().info(insert_buffer_size)
        status, reply = connect.set_config("cache_config", "cpu_cache_capacity", mem_available - int(insert_buffer_size) + 1)
>       assert not status.OK()
E       AssertionError: assert not True
E        +  where True = <bound method Status.OK of Status(code=0, message='Success!')>()
E        +    where <bound method Status.OK of Status(code=0, message='Success!')> = Status(code=0, message='Success!').OK
```
- available memory: 502GB, cpu_cache_capacity=4 and insert_buffer_size=1
- try to set cpu_cache_capacity to 502GB, server side does not change

**Expected behavior**
This should be status not ok

**Environment details**
- master branch milvus cpu version

**Comment by BossZou** [comment]
Currently server limit sum of cache capacity and buffer size less than system total memory size rather than available size, so return value in this case is OK.

**Comment by sahuang** [comment]
Number of available memory is always changing, so to be uniform, set sum of cache capacity and buffer size less than system total memory rather than available size seems good.
