### ISSUE TITLE
[Bug]: Collection.load() hangs on large collection  500k+

### ISSUE THREAD

**Issue by radpet** [milvus-io/milvus#15882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.1, helm-milvus-3.0.8
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.0.0rc9
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: None
- Others:
```

### Current Behavior

<img width="1520" alt="image" src="https://user-images.githubusercontent.com/13572835/156882846-b9dbc9a8-2815-4467-ba7b-322ebbf7c310.png">

When I try to load a collection with 500k + entities it stuck.
If I delete the collection and try to load it it is fine.

Memory seems to be normal 
<img width="1701" alt="image" src="https://user-images.githubusercontent.com/13572835/156883239-70d5fbd5-c6d2-4e0d-87a1-cdbebc30cafe.png">

I tried releasing the collection and then loading it again but it failed. Further more sometimes I can't even release the collection. Here are the milvus logs but Attu timesout waiting for the response.
```
[2022/03/05 12:41:14.422 +00:00] [DEBUG] [impl.go:499] ["ReleaseCollection received"] [traceID=4e56d85ea016422] [role=proxy] [db=] [collection=use_en]
[2022/03/05 12:41:14.423 +00:00] [DEBUG] [impl.go:521] ["ReleaseCollection enqueued"] [traceID=4e56d85ea016422] [role=proxy] [MsgID=431615463589413081] [BeginTS=431615921201348609] [EndTS=431615921201348609] [db=] [collection=use_en]
```

I have another instance of milvus with different data but same size 500k+ and it loads fine.

### Expected Behavior

When I try to load a collection with 500k I can query it.

### Steps To Reproduce

```markdown
1. Insert 500k+ 512dim vectors in a collection.
2. Try to query the collection
```

**Comment by radpet** [comment]
Also when I try to drop the collection it may take more than 5 minutes

```[2022/03/05 12:53:47.994 +00:00] [DEBUG] [impl.go:265] ["DropCollection received"] [traceID=6e0cdf523f9da4c3] [role=proxy] [db=] [collection=use_en]
[2022/03/05 12:53:47.994 +00:00] [DEBUG] [impl.go:285] ["DropCollection enqueued"] [traceID=6e0cdf523f9da4c3] [role=proxy] [MsgID=431616034584395807] [BeginTs=431616118745464833] [EndTs=431616118745464833] [db=] [collection=use_en]
[2022/03/05 12:53:47.994 +00:00] [DEBUG] [root_coord.go:1306] [DropCollection] [role=rootcoord] ["collection name"=use_en] [msgID=431616034584395807]```

**Comment by xiaofan-luan** [comment]
hi @radpet， could you please offer querycoord, roodcoord and querynode log so we could take a deeper look into it?

**Comment by radpet** [comment]
Hi @xiaofan-luan Would you please guide me what should I use to filter the logs in order to get useful snippets for querycoord, roodcoord and querynode. I am using the standalone deployment mode so there aren't different pods/instances

**Comment by radpet** [comment]
@xiaofan-luan On a different instance  I can't reproduce it so far.  (same setup, only s3 buckets differ (dev/prod env) , Issue unfortunately affecting the prod env)

```
2022-03-05 16:16:18,192 - milvus.milvus.load_collection:76|INFO|request_id=|loading collection use_en
2022-03-05 16:16:18,199 - milvus.milvus.load_collection:79|INFO|request_id=|loaded collection use_en with entities=595666
```

Is it possible some data to be corrupted leading to failures?

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan @yanliang567 On a different instance I can't reproduce it so far. (same setup, only s3 buckets differ (dev/prod env) , Issue unfortunately affecting the prod env)
> 
> ```
> 2022-03-05 16:16:18,192 - milvus.milvus.load_collection:76|INFO|request_id=|loading collection use_en
> 2022-03-05 16:16:18,199 - milvus.milvus.load_collection:79|INFO|request_id=|loaded collection use_en with entities=595666
> ```
> 
> Is it possible some data to be corrupted leading to failures?

not really sure about it, usually it's not due to corrupted file but some sync mechanism not working. If we can still collect log then we need to take a deep look into it

**Comment by radpet** [comment]
We store logs in Loki so I can get them quite easy.
The file below is a snippet generated by `|~"querycoord|rootcoord|querynode"` filter. In the timeframe I tried deleting the collection and also searching in it.

[milvus_prod_debug.txt](https://github.com/milvus-io/milvus/files/8191059/milvus_prod_debug.txt)

**Comment by yanliang567** [comment]
@radpet which version of pymilvus are you running? Please make sure the version of pymilvus is matched with milvus server.

**Comment by radpet** [comment]
@yanliang567 latest pymilvus 2.0.1

**Comment by yanliang567** [comment]
@sunby could you please help to take a look at this issue?

**Comment by sunby** [comment]
@radpet It will be very helpful if you can provide the complete standalone log before the loading error.

**Comment by yanliang567** [comment]
@hussainfolio3 could you please upload the logs and provide more info when reopening an issue, so that we could investigate the issue?

/assign @hussainfolio3

**Comment by fernandojvdasilva** [comment]
I think I'm having the same issue. but with the cluster version. In my case, it seems that the issue appeared when I had to restart the containers because I needed to resize my partition (running on AWS btw), because I inserted too many vectors. I could insert about 25 million vectors.

These are the steps and logs that I got:

1 - I restarted all the containers using docker-compose restart
2 - tried to list collections using utility.list_collections() (I'm using Pymilvus 2.0.0)
3 - Got the following exception:

`│pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=proxy not healthy)> `

4 - Restarted milvus-proxy container only
5 - Collections listed correctly!

6 - Tried to load collection

7  the script hangs on grpc_handler.py -> load_collection method

8- the logs in milvus-querycoord are:

```
time="2022-05-06T02:50:26Z" level=warning msg="[Failed to close consumer]" consumerID=10 error="server error: MetadataError: Consumer not found" name=xynvi subscription=by-dev-queryNode-431584206669217793-91 topic="persistent://public/default/by-dev-search-0"
[2022/05/06 02:50:32.371 +00:00] [ERROR] [query_coord.go:480] ["loadBalanceSegmentLoop: there are no online QueryNode to balance"] [stack="github.com/milvus-io/milvus/internal/querycoord.(*QueryCoord).loadBalanceSegmentLoop\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/query_coord.go:480"]
[2022/05/06 02:51:32.371 +00:00] [ERROR] [query_coord.go:480] ["loadBalanceSegmentLoop: there are no online QueryNode to balance"] [stack="github.com/milvus-io/milvus/internal/querycoord.(*QueryCoord).loadBalanceSegmentLoop\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/query_coord.go:480"]

```
9 - Restarted milvus-querynode and milvus-querycoord containers
10 - Got the following logs from milvus-querycoord container

```
[2022/05/06 02:56:22.629 +00:00] [INFO] [grpclog.go:37] ["[core]Channel Connectivity change to SHUTDOWN"]
[2022/05/06 02:56:22.629 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel Connectivity change to SHUTDOWN"]
[2022/05/06 02:56:22.629 +00:00] [WARN] [client.go:245] ["querynode ClientBase ReCall grpc first call get error "] [error="err: context deadline exceeded\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:244 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:190 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).LoadSegments\n/go/src/github.com/milvus-io/milvus/internal/querycoord/querynode.go:382 github.com/milvus-io/milvus/internal/querycoord.(*queryNode).loadSegments\n/go/src/github.com/milvus-io/milvus/internal/querycoord/cluster.go:230 github.com/milvus-io/milvus/internal/querycoord.(*queryNodeCluster).loadSegments\n/go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:1079 github.com/milvus-io/milvus/internal/querycoord.(*loadSegmentTask).execute\n/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:553 github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask\n/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:860 github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processActivateTaskLoop.func1\n/usr/local/go/src/runtime/asm_amd64.s:1374 runtime.goexit\n"]
[2022/05/06 02:56:22.629 +00:00] [WARN] [grpclog.go:46] ["[core]grpc: addrConn.createTransport failed to connect to {172.20.0.12:21123 172.20.0.12:21123 <nil> 0 <nil>}. Err: connection error: desc = \"transport: Error while dialing dial tcp 172.20.0.12:21123: operation was canceled\". Reconnecting..."]
[2022/05/06 02:56:22.629 +00:00] [INFO] [grpclog.go:37] ["[core]parsed scheme: \"\""]
[2022/05/06 02:56:22.629 +00:00] [INFO] [grpclog.go:37] ["[core]scheme \"\" not registered, fallback to default scheme"]
[2022/05/06 02:56:22.629 +00:00] [INFO] [grpclog.go:37] ["[core]ccResolverWrapper: sending update to cc: {[{172.20.0.12:21123  <nil> 0 <nil>}] <nil> <nil>}"]
[2022/05/06 02:56:22.629 +00:00] [INFO] [grpclog.go:37] ["[core]ClientConn switching balancer to \"pick_first\""]
[2022/05/06 02:56:22.629 +00:00] [INFO] [grpclog.go:37] ["[core]Channel switches to new LB policy \"pick_first\""]
[2022/05/06 02:56:22.629 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel Connectivity change to CONNECTING"]
[2022/05/06 02:56:22.629 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel picks a new address \"172.20.0.12:21123\" to connect"]
[2022/05/06 02:56:22.629 +00:00] [INFO] [grpclog.go:37] ["[core]pickfirstBalancer: UpdateSubConnState: 0xc0003a96e0, {CONNECTING <nil>}"]
[2022/05/06 02:56:22.629 +00:00] [INFO] [grpclog.go:37] ["[core]Channel Connectivity change to CONNECTING"]

```
11 - Restarted milvus-querynode only
12 - Tried to load collection again
13 - It still hangs at the same point
14 - Logs from milvus-querycoord container:

```
[2022/05/06 03:07:39.353 +00:00] [WARN] [query_coord.go:518] ["loadBalanceSegmentLoop: there are too few available query nodes to balance"] [onlineNodeIDs="[110]"] [availableNodeIDs="[110]"]
[2022/05/06 03:08:39.353 +00:00] [WARN] [query_coord.go:518] ["loadBalanceSegmentLoop: there are too few available query nodes to balance"] [onlineNodeIDs="[110]"] [availableNodeIDs="[110]"]

```

Meanwhile, can I do anything to work around this issue? Should I distribute data in different nodes? If so, any advice on how I could do that?

**Comment by xiaofan-luan** [comment]
> I think I'm having the same issue. but with the cluster version. In my case, it seems that the issue appeared when I had to restart the containers because I needed to resize my partition (running on AWS btw), because I inserted too many vectors. I could insert about 25 million vectors.
> 
> These are the steps and logs that I got:
> 
> 1 - I restarted all the containers using docker-compose restart 2 - tried to list collections using utility.list_collections() (I'm using Pymilvus 2.0.0) 3 - Got the following exception:
> 
> `│pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=proxy not healthy)> `
> 
> 4 - Restarted milvus-proxy container only 5 - Collections listed correctly!
> 
> 6 - Tried to load collection
> 
> 7 the script hangs on grpc_handler.py -> load_collection method
> 
> 8- the logs in milvus-querycoord are:
> 
> ```
> time="2022-05-06T02:50:26Z" level=warning msg="[Failed to close consumer]" consumerID=10 error="server error: MetadataError: Consumer not found" name=xynvi subscription=by-dev-queryNode-431584206669217793-91 topic="persistent://public/default/by-dev-search-0"
> [2022/05/06 02:50:32.371 +00:00] [ERROR] [query_coord.go:480] ["loadBalanceSegmentLoop: there are no online QueryNode to balance"] [stack="github.com/milvus-io/milvus/internal/querycoord.(*QueryCoord).loadBalanceSegmentLoop\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/query_coord.go:480"]
> [2022/05/06 02:51:32.371 +00:00] [ERROR] [query_coord.go:480] ["loadBalanceSegmentLoop: there are no online QueryNode to balance"] [stack="github.com/milvus-io/milvus/internal/querycoord.(*QueryCoord).loadBalanceSegmentLoop\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/query_coord.go:480"]
> ```
> 
> 9 - Restarted milvus-querynode and milvus-querycoord containers 10 - Got the following logs from milvus-querycoord container
> 
> ```
> [2022/05/06 02:56:22.629 +00:00] [INFO] [grpclog.go:37] ["[core]Channel Connectivity change to SHUTDOWN"]
> [2022/05/06 02:56:22.629 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel Connectivity change to SHUTDOWN"]
> [2022/05/06 02:56:22.629 +00:00] [WARN] [client.go:245] ["querynode ClientBase ReCall grpc first call get error "] [error="err: context deadline exceeded\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:244 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:190 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).LoadSegments\n/go/src/github.com/milvus-io/milvus/internal/querycoord/querynode.go:382 github.com/milvus-io/milvus/internal/querycoord.(*queryNode).loadSegments\n/go/src/github.com/milvus-io/milvus/internal/querycoord/cluster.go:230 github.com/milvus-io/milvus/internal/querycoord.(*queryNodeCluster).loadSegments\n/go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:1079 github.com/milvus-io/milvus/internal/querycoord.(*loadSegmentTask).execute\n/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:553 github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask\n/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:860 github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processActivateTaskLoop.func1\n/usr/local/go/src/runtime/asm_amd64.s:1374 runtime.goexit\n"]
> [2022/05/06 02:56:22.629 +00:00] [WARN] [grpclog.go:46] ["[core]grpc: addrConn.createTransport failed to connect to {172.20.0.12:21123 172.20.0.12:21123 <nil> 0 <nil>}. Err: connection error: desc = \"transport: Error while dialing dial tcp 172.20.0.12:21123: operation was canceled\". Reconnecting..."]
> [2022/05/06 02:56:22.629 +00:00] [INFO] [grpclog.go:37] ["[core]parsed scheme: \"\""]
> [2022/05/06 02:56:22.629 +00:00] [INFO] [grpclog.go:37] ["[core]scheme \"\" not registered, fallback to default scheme"]
> [2022/05/06 02:56:22.629 +00:00] [INFO] [grpclog.go:37] ["[core]ccResolverWrapper: sending update to cc: {[{172.20.0.12:21123  <nil> 0 <nil>}] <nil> <nil>}"]
> [2022/05/06 02:56:22.629 +00:00] [INFO] [grpclog.go:37] ["[core]ClientConn switching balancer to \"pick_first\""]
> [2022/05/06 02:56:22.629 +00:00] [INFO] [grpclog.go:37] ["[core]Channel switches to new LB policy \"pick_first\""]
> [2022/05/06 02:56:22.629 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel Connectivity change to CONNECTING"]
> [2022/05/06 02:56:22.629 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel picks a new address \"172.20.0.12:21123\" to connect"]
> [2022/05/06 02:56:22.629 +00:00] [INFO] [grpclog.go:37] ["[core]pickfirstBalancer: UpdateSubConnState: 0xc0003a96e0, {CONNECTING <nil>}"]
> [2022/05/06 02:56:22.629 +00:00] [INFO] [grpclog.go:37] ["[core]Channel Connectivity change to CONNECTING"]
> ```
> 
> 11 - Restarted milvus-querynode only 12 - Tried to load collection again 13 - It still hangs at the same point 14 - Logs from milvus-querycoord container:
> 
> ```
> [2022/05/06 03:07:39.353 +00:00] [WARN] [query_coord.go:518] ["loadBalanceSegmentLoop: there are too few available query nodes to balance"] [onlineNodeIDs="[110]"] [availableNodeIDs="[110]"]
> [2022/05/06 03:08:39.353 +00:00] [WARN] [query_coord.go:518] ["loadBalanceSegmentLoop: there are too few available query nodes to balance"] [onlineNodeIDs="[110]"] [availableNodeIDs="[110]"]
> ```
> 
> Meanwhile, can I do anything to work around this issue? Should I distribute data in different nodes? If so, any advice on how I could do that?

I have a few guess:
1) for log 14, ignore it, simply because you don't have only nodes, I will modify the log level.
2) Expect log 14, any other error logs?  
3) For log 8, it means all querynodes are dead, might be because for pulsar failed to close consumer and cause querynode crash.

So how many querynodes alive right now? If it is possible please upload full querynode logs, thanks @fernandojvdasilva

**Comment by xiaofan-luan** [comment]
hi @yanliang567, meanwhile can we try to reproduce on our own environment? A lot of user hit the same issue so there should be way to reproduce it

**Comment by Jacobh2** [comment]
I just got the same issue, with the last logs from queryNodes being
```log
{"level":"WARN","time":"2022/05/19 05:52:39.838 +00:00","caller":"query_coord.go:532","message":"loadBalanceSegmentLoop: there are too few available query nodes to balance","onlineNodeIDs":[342],"availableNodeIDs":[342]}
panic: All attempts results:
attempt #1:function CompareAndSwap error for compare is false for key: querycoord
attempt #2:function CompareAndSwap error for compare is false for key: querycoord
attempt #3:function CompareAndSwap error for compare is false for key: querycoord
attempt #4:function CompareAndSwap error for compare is false for key: querycoord
attempt #5:function CompareAndSwap error for compare is false for key: querycoord
attempt #6:function CompareAndSwap error for compare is false for key: querycoord
attempt #7:function CompareAndSwap error for compare is false for key: querycoord
attempt #8:function CompareAndSwap error for compare is false for key: querycoord
attempt #9:function CompareAndSwap error for compare is false for key: querycoord
attempt #10:function CompareAndSwap error for compare is false for key: querycoord
attempt #11:function CompareAndSwap error for compare is false for key: querycoord


goroutine 80 [running]:
github.com/milvus-io/milvus/internal/util/sessionutil.(*Session).Register(0xc0000a2f00)
	/go/src/github.com/milvus-io/milvus/internal/util/sessionutil/session_util.go:124 +0xc6
github.com/milvus-io/milvus/internal/querycoord.(*QueryCoord).Register(0xc0006aaea0, 0x0, 0x0)
	/go/src/github.com/milvus-io/milvus/internal/querycoord/query_coord.go:105 +0x36
github.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).start(0xc0005a2640, 0x18, 0x0)
	/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:277 +0x78
github.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).Run(0xc0005a2640, 0x0, 0x0)
	/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:100 +0x7e
github.com/milvus-io/milvus/cmd/components.(*QueryCoord).Run(0xc0002fe138, 0xffffffffffffffff, 0x8)
	/go/src/github.com/milvus-io/milvus/cmd/components/query_coord.go:50 +0x33
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runQueryCoord.func1(0xc00060f700, 0x36693d0, 0xc000462000, 0xc000010598, 0xc0004560f0)
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:178 +0x11b
created by github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runQueryCoord
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:160 +0xb0
```

For me it seems like I tried to load a collection onto few query-nodes, making them get OOMKilled and then crash-loop. I tried to unload the collection but nothing happens via either Attu or via PyMilvus client. I then tried to scale up the query nodes in hope that it would load balance across multiple nodes, but I guess since all query nodes are not ready due to the OOM restarts, they cannot reach a consensus.

**Comment by wayblink** [comment]
Hi, @Jacobh2 could you please upload the complete query node logs if you can still reproduce the issue? We will take a look into it.

**Comment by Jacobh2** [comment]
@wayblink I do not have the logs anymore unfortunately. We have decided to move away from Milvus to another vector database to meet our deadlines.

**Comment by roemchine** [comment]
The same issue happens to me. I restarted the server and I cannot query again. I am using milvus 2.0.2 and I am having aroud 80M vectors. Here is my log file.
[out.txt.gz](https://github.com/milvus-io/milvus/files/10113734/out.txt.gz)

**Comment by yanliang567** [comment]
@roemchine could you please retry on latest release Milvus 2.2.0, which fixed lots of issues. if it reproduced to you, please file a new issue and upload the full logs. Thanks.

**Comment by roemchine** [comment]
@yanliang567 Thank you. I will check if it happens on Milvus 2.2.0 too

**Comment by capihacendado** [comment]
I am having the same issue now in a standalone deployment

**Comment by xiaofan-luan** [comment]
> I am having the same issue now in a standalone deployment

Which milvus version does it happen?
It usually works for 2.2.2 or above, you can check if memory is enough

**Comment by roemchine** [comment]
@xiaofan-luan I could not reproduce the issue on Milvus 2.2.x anymore

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan I could not reproduce the issue on Milvus 2.2.x anymore

Good for you! thanks for the feedback!
