### ISSUE TITLE
[Bug]: How to write back to the mysql database via milvus/db

### ISSUE THREAD

**Issue by shenjianzch** [milvus-io/milvus#15899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:0.10.6
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):0.2.10
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The current wal file is lost, the mysql database is destroyed, and now only milvus/db is the existence of data want to recover from here, what to do, how to restore to the database

### Anything else?

Now after the restart, the new ones are all new, and the previous data cannot be obtained

**Comment by yanliang567** [comment]
/assign @yhmo 
@yhmo could you please help on this issue?

/unassign

**Comment by shenjianzch** [comment]
Can no one help me？

**Comment by yanliang567** [comment]
I don't think thats an easy job.:(

**Comment by yhmo** [comment]
Not all the metadata can be restored from milvus/db folder, that is the problem.
The db folder doesn't persist collection information, so, If the original db has multiple collections or partitions, it cannot be restored.
The db folder doesn't persist index parameters, so the index information is lost and cannot be restored.

**Comment by shenjianzch** [comment]
Can I just give up

**Comment by yhmo** [comment]
> Can I just give up

If your original data is multiple collections/partitions, it is impossible to restore.
If you only has one collection/partition, and you don't need the index data, then it is possible to restore the original vectors.

**Comment by shenjianzch** [comment]
> > Can I just give up
> 
> If your original data is multiple collections/partitions, it is impossible to restore. If you only have one collection/partition, and you don't need the index data, then it is possible to restore the original vectors.

just one collection/partition, how to do it

**Comment by yhmo** [comment]
1. start an empty MySQL server
2. start a new milvus server 0.10.6
3. use MySQL client to login
`USE milvus;`
`SHOW TABLES;`
You will see there are four tables under the database "milvus": Environment, Fields, TableFiles, Tables.
"Environment" and "Fields" can be ignored.
We need to fill the "Tables" and "TableFiles".
"Tables" is for collections information. It has the following fields:
- id			        increment id genereted by mysql
- table_id		        collection name
- state			set to 0, means this collection is in normal state. (if the collection is to be deleted, this value is 1)
- dimension		collection's dimension
- created_on		the time stamp when the collection is created, you can use current timestamp
- flag			the entities id is auto-generated(1) or user provided(2).
- index_file_size		index_file_size of the collection, unit:byte, by default is 1024*1024*1024
- engine_type		index type. set to 1 means has no index
- index_params		index parameters, json format string, set to "{}"
- metric_type		metric type, L2=1, IP=2
- owner_table		for partition's owner collection, set to empty string
- partition_tag		for partition's name, set to empty string
- version			milvus version string, set to "0.10.6"
- flush_lsn		wal record number, set to 0

"TableFiles" is for data files(raw data file and index file) information, it has the following fields:
- id			increment id genereted by mysql
- table_id		the collection name which the segment belongs to	
- segment_id		segment id which this file belongs to, this is a long number, use segment folder name to fill it
- engine_type		index type, set to 1 means no index
- file_id			data file id, if it is a raw data file, the id is equal to segment id, else if it is an index file, this id is another long number.
- file_type		raw file or index file, set to 1 means this is a raw data file
- file_size		file size
- row_count		how many rows in this file
- updated_time		the time stamp the latest time it is updated, you can use current timestamp to fill
- created_on		the time stamp when it is created, you can use the current timestamp to fill
- date			the date when it is created, you can use the current date to fill
- flush_lsn		wal record number, set to 0

4. Restore the collection information
Assume the collection name is "xxx", its dimension is 128, current timestamp is 1646706133932085(created_on=1646706133932085), entities id is auto-genereated(flag=2), the index_file_size is 1GB(index_file_size=1024*1024*1024), it has no index(engine_type=1, index_params="{}"), metric type is L2(metric_type=1), then we can create a new collection by this SQL statement:
`INSERT INTO Tables VALUES(1, "xxx", 0, 128, 1646706133932085, 2, 1024*1024*1024, 1, "{}", 1, "", "", "0.10.6", 0);`

After the SQL statement is executed, you use pymilvus to list collections:
```
status, collecitons = MILVUS.list_collections()
print(collecitons)
```
Then you will see it return a collection named "xxx".


5. Restore segments
Copy the original /milvus/db/tables/ to the new /milvus/db.
Assume the collection name is "xxx", then there will be a "xxx" folder under the /milvus/db/tables
Use python or other scripts to recursive the /milvus/db/tables/xxx folder, there are many sub folders, each sub folder is a segment. In each segment folder, there are four files: 
1). raw data file, file name is equal to segment name 
2). id file, file name is "****.uid"
3). bloom filter file, file name is "bloom_filter"
4). delete docs file(records which entity is deleted), file name is "delete_docs"

Assume there is a segment folder name is "1646706133964922000", there will be a raw file "1646706133964922000" under this folder, and its file size is 52000 bytes. 
The ***.uid file size is 8008 bytes, that means this segment has (8008-8)/8=1000 rows, we can calculate a segment row by (uid_file_size - 8)/8
The "delete_docs" file size is 28 bytes, that means (28-8)/4=5 entities were deleted, we can calculate delete count by (del_file_size - 8)/4
So the segment real row count is (uid_file_size - 8)/8 - (del_file_size - 8)/4 = 1000-5 = 995 rows.

Then we can use this SQL statement to create a segment meta data:

`INSERT INTO TableFiles VALUES(1, "xxx", "1646706133964922000", 1, "1646706133964922000", 1, 52000, 995, 1646707140755640, 1646707140755640, 1220208, 0);`
