### ISSUE TITLE
[FEATURE] Change the name of `use_gpu_threshold` and add descriptions in configuration template

### ISSUE THREAD

**Issue by jielinxu** [milvus-io/milvus#159]
**Is your feature request related to a problem? Please describe.**
The name of the newly added parameter is not clear enough in meaning, and there's no description for it.

**Describe the solution you'd like**
1. Change the parameter name to `gpu_search_threshold` and add the description: threshold beyond which only GPUs are used for search computation.
2. Move this parameter to `resource_config` section, as it is more associated with resource allocation and usage.

**Comment by cydrain** [comment]
done
