### ISSUE TITLE
[Bug]:datanode crash on data insertion

### ISSUE THREAD

**Issue by kingy123** [milvus-io/milvus#15937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.1
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus v2.0.0
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 2c/4G
- GPU: 无
- Others: k8s v1.18.8
```

### Current Behavior

我使用[bootcamp master]测试脚本按如下步骤操作：
1，python main.py --collection v_test_128 -c
2，python main.py --collection v_test_128 --has
3，python main.py --collection v_test_128 --rows
4，python main.py --collection v_test_128 --index_type IVF_SQ8 --create_index
5，python main.py --collection=v_test_128 --insert
使用lab1_sift1b_1m测试数据
结果数据插入时datanode节点一直宕机
日志截取部分如下：
time="2022-02-28T07:37:38Z" level=error msg="[Failed to create consumer]" consumerID=1 error="server error: PersistenceError: java.util.concurrent.CompletionException: java.lang.NullPointerException" name=acond subscription=by-dev-dataNode-18-431497848222646273 topic="persistent://public/default/by-dev-rootcoord-dml_0"

### Expected Behavior

正常数据插入

**Comment by congqixia** [comment]
Hi @kingy123 , thanks for the report! From the log your provided, it looks like pulsar has some problem. Could you please check the pulsar status and provide the log if the pulsar cluster if possible?

**Comment by yanliang567** [comment]
@kingy123 one more question, how many entities did you insert at a time? I am asking because I doubt that if the pulsar service was broken with heavy insert workload.

**Comment by kingy123** [comment]
> 

使用每批量10w条共10批数据，维度是128

**Comment by xiaofan-luan** [comment]
looks like a pulsar issue, did you try to restart pulsar?
