### ISSUE TITLE
[Bug]:并发最多只有30，wrk -t12 -c400 -d30s 'http://0.0.0.0:8510/predict' 测试脚本，

### ISSUE THREAD

**Issue by panxuefeng235** [milvus-io/milvus#15940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.0
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus v2.0.0
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

并发最多只有30

### Expected Behavior

根据开发人员预期并发可以达到400

**Comment by yanliang567** [comment]
@panxuefeng235 could you please share more info about how you get that result and what is your server configuration? it would be helpful, if you could offer some code script about the test

/assign @panxuefeng235 
/unassign

**Comment by panxuefeng235** [comment]
> @panxuefeng235 could you please share more info about how you get that result and what is your server configuration? it would be helpful, if you could offer some code script about the test
> 
> /assign @panxuefeng235 /unassign

I use the wrk tool
wrk -t1 -c40 -d30s --scripts post.lua 'http://0.0.0.0:8510/predict' 

post.lua
wrk.method = "POST"
wrk.headers["Content-Type"] = "application/json"
wrk.body = '{"label":["百里弘毅", "潮鞋"],"topk":5}'


server configuration
https://raw.githubusercontent.com/milvus-io/milvus/master/deployments/docker/standalone/docker-compose.yml -O docker-compose.yml

**Comment by yanliang567** [comment]
@panxuefeng235 let me specify the questions:
1. what is the vector dim?
2.  how many entities are you searching in a collection?
3. did you use any index? what is the index params?
4. what is your hardware configuration, e.g. cpu, memory, ssd disk?
All the items above would impact the search qps and latency. Moreover, I guess you have some RESTful-like wapper before pymilvus(or any other SDK), this could also impact the E2E performance

**Comment by xiaofan-luan** [comment]
Close for now, if more help is necessary, please open an issue in English with the inforamtion yanliang request, thanks @panxuefeng235

**Comment by panxuefeng235** [comment]
> @panxuefeng235 let me specify the questions:
> 
> 1. what is the vector dim?
> 2. how many entities are you searching in a collection?
> 3. did you use any index? what is the index params?
> 4. what is your hardware configuration, e.g. cpu, memory, ssd disk?
>    All the items above would impact the search qps and latency. Moreover, I guess you have some RESTful-like wapper before pymilvus(or any other SDK), this could also impact the E2E performance

1. 128dim
2. 60000
3. index_param = {
        "metric_type":"L2",
        "index_type":"IVF_SQ8",
        "params":{"nlist":1024}
    }
4.cpu
5.yeah,i use the fastapi to do the server

**Comment by yhmo** [comment]
@panxuefeng235 
We require all issues must be written in English.
So please change this issue title to be English and reopen it again.
