### ISSUE TITLE
Add new version docker usage in INSTALL.md

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#1595]
## Report incorrect documentation

**Location of incorrect documentation**
Compile Milvus on Docker
Step 2

**Suggested fix for documentation**
For nvidia docker 2:
docker run --runtime=nvidia -it -p 19530:19530 -d milvusdb/milvus-gpu-build-env:latest

For nvidia container toolkit:
docker run --gpus all -it -p 19530:19530 -d milvusdb/milvus-gpu-build-env:latest

**Comment by JinHai-CN** [comment]
Done.
