### ISSUE TITLE
Pymilvus api description error in guides/milvus_operation.md

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#1597]
## Report incorrect documentation

**Location of incorrect documentation**
>>> status, vector = milvus.get_vector_by_id(collection_name='test01', vector_id=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.
vector_id is a single id:
>>> status, vector = milvus.get_vector_by_id(collection_name='test01', vector_id=10)

**Comment by BossZou** [comment]
Thank you for your issue.we have fixed it and will pull a request soon.

**Comment by JinHai-CN** [comment]
Done.
