### ISSUE TITLE
[Bug]: Error in the decoumentation

### ISSUE THREAD

**Issue by dariocurr** [milvus-io/milvus#15998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

A working documentation

### Why is this needed?

There is an error in the documentation.
When trying to install `milvus Offline`. I executed the following lines

```sh
$ cd images/
$ for image in $(find . -type f -name "*.tar.gz") ; do gunzip -c $image | docker load; done
```

then, following the guide i typed
```sh
docker-compose -f docker-compose.yml up -d
```

but I was in the wrong directory, i.e `images`.

**Comment by xiaofan-luan** [comment]
@dariocurr thanks for the contribution, close the issue for now~
