### ISSUE TITLE
milvus 0.7.0 not working with previous pic-search?

### ISSUE THREAD

**Issue by flydragon2018** [milvus-io/milvus#1599]
**Describe the bug**
Welcome to Milvus!
Milvus Release version: v0.7.0, built at 2020-03-10 11:10.01, with OpenBLAS library.
You are using Milvus GPU edition
Last commit id: 037e4054b6345b0f8fab957af898b455a6424d8d

Loading configuration from: ../conf/server_config.yaml
Initializing log config from: ../conf/log_config.conf
S3 DISABLED !
GPU resources ENABLED !
FAISS hook AVX
Milvus server started successfully!
[libprotobuf ERROR google/protobuf/wire_format_lite.cc:584] String field 'milvus.grpc.SearchParam.partition_tag_array' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. 

**Steps/Code to reproduce behavior**
 compile and start the milvus server.
 start pic-webserver and pic-webclient.
after adding image dataset to sever,  webclient uploading image to search, no result.
that error shows at milvus server.
**Expected behavior**
search milvus server and return result to webclient.

**Environment details**
- Hardware/Softward conditions  Ubuntu18.04 , GPU, 8G  
- Method of installation  from source 
- Milvus version  0.7.0
- Milvus configuration  default

**Screenshots**
I
**Additional context**

**Comment by JinHai-CN** [comment]
Milvus 0.7.0 interface isn't compatible with 0.6.0. Image search demo need to update.

**Comment by QuarTerll** [comment]
I have tested the following version of the demo. And it works for me.
```
milvusdb/milvus:0.10.0-gpu-d061620-5f3c00
milvusbootcamp/pic-search-webserver:0.10.0
milvusbootcamp/pic-search-webclient:0.1.0
```

Hope can help
: )
