### ISSUE TITLE
[BUG] IP search result often changed

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#160]
**Describe the bug**

    Index was created with IVF_FLAT or IVF_SQ8, both of the search result is often changed if do search again
    Search with MetricType: L2 always got the same result

    If index_file_size set 1024, the search result almost the same
    If set 50 (means several files), the search result is changed

**Steps/Code to reproduce behavior**
Searching with IP 

**Expected behavior**
Return the same result all the time

**Environment details**
All server version

**Screenshots**
N/A

**Additional context**
N/A

**Comment by cydrain** [comment]
As you mentioned in slack, your test dataset is "glove-25-angular", and you insert the data slice by slice (100,000 lines per slice, so totally insert 12 times). 
During inserting, the data is serialized into disk and generate multiple raw data files. These raw data files will be merged and generate a larger raw data file.
The size of each raw data file is flexible, it will affect the file merging sequence, thus affect the data  sequence in the final raw data file. Training is data order sensitive, so the searching result maybe fluctuate.

This is not a real issue, I'll close it.
