### ISSUE TITLE
[Bug]: [CI] Install failed sometimes by waiting for zookeeper ready

### ISSUE THREAD

**Issue by jennyli-z** [milvus-io/milvus#16007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-release-nightly/detail/milvus-release-nightly/23/pipeline
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/93511422/157789254-642328ac-1b9f-415c-8f10-f3f5541659ac.png">

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-15784/17/pipeline/

Helm install failed sometimes when it is waiting for zookeeper to be ready.

### Expected Behavior

Should install milvus successfully

**Comment by jennyli-z** [comment]
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/393/pipeline

**Comment by LoveEachDay** [comment]
Fix in milvus-io/milvus-helm#307, try use milvus-helm `3.0.12` version.

**Comment by jennyli-z** [comment]
/unassign
/assign @LoveEachDay 

https://github.com/milvus-io/milvus/pull/16146 install failed， wait for the new chart version.

**Comment by jennyli-z** [comment]
https://github.com/milvus-io/milvus/blob/master/build/ci/jenkins/PR.groovy#L7 already changed to 3.0.19 , greater than 3.0.12.
close it for now
If there's still issue, will reopen it.
