### ISSUE TITLE
BinaryFlat add 2 Metric: Substructure Superstructure

### ISSUE THREAD

**Issue by shengjun1985** [milvus-io/milvus#1603]
**Is your feature request related to a problem? Please describe.**
I want Milvus to support more binary metrics.

**Describe the solution you'd like**
Here are the 2 Metric.
(1) Substructure: D(a, b) = ((a∩b)==a ? 0 : ∞)
(2) Superstructure: D(a, b) = ((a∩b)==b ? 0 : ∞)

Obviously, these two formulas do not satisfy the following properties.
(1) D(a, b) = D(b, a)
(2) D(a, b) + D(a, c) >= D(b, c)
So, IVF can not supported now.

**Describe alternatives you've considered**

**Additional context**

**Comment by shengjun1985** [comment]
@youny626 Please add Java sdk.
@fishpenguin Please add Go sdk.
Thanks.

**Comment by BossZou** [comment]
Python SDK have add `Substructure` and  `Superstructure`. You can install `pymilvus-test>=0.3.1` to use them. [Here](https://github.com/BossZou/pymilvus/blob/master/examples/example_binary.py) is an example to use them in python shell.

**Comment by youny626** [comment]
Available in java SDK 0.6.0-SNAPSHOT

**Comment by fishpenguin** [comment]
Go sdk and C++ sdk have added Substructure and Superstructure
