### ISSUE TITLE
[Bug]: uncontrolled memory growth

### ISSUE THREAD

**Issue by chensanle** [milvus-io/milvus#16043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 1.1.1
- Deployment mode(standalone or cluster): standlone
- SDK version(e.g. pymilvus v2.0.0rc2): gosdk v1.1.1
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 32C/64Gib
- GPU: none
- Others:
```

### Current Behavior

When I continue to do query operations, the memory grows uncontrollably. 
dim: 768; index:ivf_pq; nlist: 4096; m:12; 1M rows
![image](https://user-images.githubusercontent.com/31087327/158149620-62d97ca8-25dd-4a32-9289-a8dad9585481.png)

### Steps To Reproduce

```markdown
1. create colleciton, index
2. insert data
3. benchmark test
4. continue to do query operations, topK: 3000.
```

**Comment by yanliang567** [comment]
@yhmo could u please help on this issue?

/assign @yhmo 
/unassign

**Comment by yhmo** [comment]
There is a "cache_size" in the server_config.yaml, by default it is 4GB. That means the memory usage will be controled around 4GB. The cache strategy is "LRU", that means the cache will grow until it hit the 4GB limit. So, if the milvus memory usage is steadily keep around the "cache_size", than it is as-designed.

**Comment by chensanle** [comment]
> There is a "cache_size" in the server_config.yaml, by default it is 4GB. That means the memory usage will be controled around 4GB. The cache strategy is "LRU", that means the cache will grow until it hit the 4GB limit. So, if the milvus memory usage is steadily keep around the "cache_size", than it is as-designed.

Thanks for your reply. 
I probably understand. the Milvus cache_size is set to 50Gib.

**Comment by yhmo** [comment]
768 dim, 1M rows, data size is less than 4GB. No need to set 50GB. 4 ~ 6 GB is enough.
