### ISSUE TITLE
[Bug]: [CI]DataNode Memory now is almost twice larger  than  the one on Mar.9

### ISSUE THREAD

**Issue by jennyli-z** [milvus-io/milvus#16045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/93511422/158158080-b5fd6358-8d9e-4474-ab03-9f9b491dc133.png)
![image](https://user-images.githubusercontent.com/93511422/158158687-854359c0-467b-47c9-ba2a-0410f20e6f37.png)

From the images above, we can see the memory usage for datanode was below 500MB (Mar.9), but for now(Mar. 14) it  is over 1GB.

https://grafana-ci.milvus.io/d/D0-n341nz/milvus-pr-ci-memory-usage?viewPanel=2&orgId=1&from=now-7d&to=now 

### Expected Behavior

Should be below 500MB, need to find out why it grows such high.

**Comment by jennyli-z** [comment]
https://github.com/milvus-io/milvus/commit/531b4da24930fd88a9cace67800a215d4b4e2818
 Please double check this commit first as it is the only commit that does not have the metrics data to prove it with low memory on 2.0.2 release branch.

**Comment by jennyli-z** [comment]
> [531b4da](https://github.com/milvus-io/milvus/commit/531b4da24930fd88a9cace67800a215d4b4e2818) Please double check this commit first as it is the only commit that does not have the metrics data to prove it with low memory on 2.0.2 release branch.

this commit is safe as 2.0.2 nightly has no memory issue, but the master has
![image](https://user-images.githubusercontent.com/93511422/158291421-40b88033-7c50-4160-947c-e3c9d9d8ba31.png)
@yanliang567

**Comment by yanliang567** [comment]
sounds like a regression issue on master only.

**Comment by sunby** [comment]
This issue is caused by unclosed channel in msgstream and flowgraph will hang. The memory used to insert rows can not be released. I will fix it in https://github.com/milvus-io/milvus/pull/16051

**Comment by jennyli-z** [comment]
![image](https://user-images.githubusercontent.com/93511422/158499415-15e697d4-0570-4f95-942f-89f45e897170.png)
Should be fixed already, I will close it.
