### ISSUE TITLE
Improper description in operational_faq.md

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#1604]
## Report incorrect documentation

**Location of incorrect documentation**
"搜索发生时，只搜索最近似的 nprobe 个文件"
"有可能出现 nprobe 文件中的所有向量总数小于 K"

**Suggested fix for documentation**
Should be:
"搜索发生时，只搜索最近似的 nprobe 个桶"
"有可能出现 nprobe 个桶中的所有向量总数小于 K"

**Comment by yamasite** [comment]
Fixed. https://github.com/yamasite/docs/blob/v0.7.0/site/zh-CN/faq/operational_faq.md
