### ISSUE TITLE
[Bug]: Search failed in the second deployment after restart and upgrade

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#16048]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220314-09b2c46b
- Deployment mode(standalone or cluster): both
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc10.dev2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search failed in the second deployment after restart and upgrade 

### Expected Behavior

all functions work well after restart and upgrade

### Steps To Reproduce

```markdown
see https://github.com/milvus-io/milvus/actions/runs/1984099782
```

**Comment by zhuwenxing** [comment]
/assign @xige-16 
Please take a look

**Comment by yanliang567** [comment]
this is a data compatibility issue. set to critical

**Comment by DragonDriver** [comment]
same as #16049

**Comment by zhuwenxing** [comment]
verified and passed in version `f3eeecf1 `
