### ISSUE TITLE
[Bug]: large size data insertion leads to exception  "Connection reset by peer"

### ISSUE THREAD

**Issue by xiaojuan8** [milvus-io/milvus#16069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.0.0
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2): cpp sdk， master branch
- OS(Ubuntu or CentOS): centos
- CPU/Memory: pod (32 core / 60Gi)
- GPU: no
- Others:
```

### Current Behavior

Insert vectors of large size will cause "connection reset by peer"
my issue is posted in discussion ： https://github.com/milvus-io/milvus/discussions/16054

### Expected Behavior

When I insert vectors of size (<512M), "Connection reset by peer" error should not happen.

### Steps To Reproduce

```markdown
1. deploy k8s cluster of milvus with 5 nodes.
2. cpp sdk insert vectors(dimension=32) of size larger than 100k vectors to milvus cluster
3. wait for a few minutes, error occurred(Connection reset by peer)
```

**Comment by yanliang567** [comment]
sounds like that the pulsar service is not working with such a heavy insert workload. could you please help to check the pulsar service? Also it would be helpful, if you could share the resource configuration(cpu, memory, disks) for pulsar and milvus pods, and pod logs as well.

/assign @xiaojuan8 
/unassign

**Comment by xiaojuan8** [comment]
CPU is: 32 core.
50Gi limit on mem, set in helms value.yml
Disk is mounted using local-pv, so there shouldnt be a limit, disk has 500G+ empty space per server
