### ISSUE TITLE
[Bug]: cluster mode ,query node down

### ISSUE THREAD

**Issue by yangyongjx** [milvus-io/milvus#16074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.1
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 2.0.0
- CPU/Memory: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz 12core /16G

- GPU: 
- Others:
```

### Current Behavior

I want to run the demo Lab Test 2: 100-Million-Scale Vector Similarity Search,but when I load the index,the query node died.

### Expected Behavior

I want to run the demo Lab Test 2: 100-Million-Scale Vector Similarity Search,but when I load the index,the query node died.

### Steps To Reproduce

```markdown
1:按照https://github.com/milvus-io/bootcamp/blob/master/benchmark_test/lab2_sift1b_100m.md 
这个步骤用单机cluster模式插入了41,500,000条数据
2：再Attu 执行load操作

3：load没有成功，querynode节点挂了

3：再load 提示no online queryload to query
```

### Anything else?

[milvus-proxy.log](https://github.com/milvus-io/milvus/files/8260894/milvus-proxy.log)
[milvus-pulsar.log](https://github.com/milvus-io/milvus/files/8260910/milvus-pulsar.log)
[milvus-minio.log](https://github.com/milvus-io/milvus/files/8260911/milvus-minio.log)
[milvus-datacoord.log](https://github.com/milvus-io/milvus/files/8260912/milvus-datacoord.log)
[milvus-querynode.log](https://github.com/milvus-io/milvus/files/8260913/milvus-querynode.log)
[milvus-querycoord.log](https://github.com/milvus-io/milvus/files/8260914/milvus-querycoord.log)
[milvus-rootcoord.log](https://github.com/milvus-io/milvus/files/8260915/milvus-rootcoord.log)
[milvus-indexcoord.log](https://github.com/milvus-io/milvus/files/8260916/milvus-indexcoord.log)
[indexnode.log](https://github.com/milvus-io/milvus/files/8260917/indexnode.log)
[milvus-datanode.log](https://github.com/milvus-io/milvus/files/8260918/milvus-datanode.log)
[milvus cluster .docx](https://github.com/milvus-io/milvus/files/8260922/milvus.cluster.docx)

**Comment by yanliang567** [comment]
@yangyongjx thank you for your issue. Could you please update the issue with English?
it sounds like the memory of querynode is not enough for loading the data.

/assign @yangyongjx 
/unassign

**Comment by yangyongjx** [comment]
1:run the demo https://github.com/milvus-io/bootcamp/blob/master/benchmark_test/lab2_sift1b_100m.md 
2:insert 41,500,000 records
3:load the index failed ,the querynode is down
4:try load again ,it notice "no online queryload to query“

**Comment by yangyongjx** [comment]
If the memory of querynode is not enough for loading the data ，I think it should not be down ,it should notice me the memory is not enough

**Comment by yanliang567** [comment]
@yangyongjx could you please collect the querynode with 'kubectl logs --previous' to get the pod logs before crash?

**Comment by yangyongjx** [comment]
[c4b896960558d38a0e09ad23ecbde5b258ce8918f580054ad9766a708866b83a-json.log](https://github.com/milvus-io/milvus/files/8261397/c4b896960558d38a0e09ad23ecbde5b258ce8918f580054ad9766a708866b83a-json.log)

**Comment by yanliang567** [comment]
looks like a known issue in 2.0.1, which was fixed in master.
Could you please retry with master daily build? 
https://hub.docker.com/layers/milvusdb/milvus-dev/master-latest/images/sha256-081842fd010f59570f367a5bece63c7ab03674990805405db236ba68b9949322?context=explore

**Comment by xiaofan-luan** [comment]
> 1:run the demo https://github.com/milvus-io/bootcamp/blob/master/benchmark_test/lab2_sift1b_100m.md 2:insert 41,500,000 records 3:load the index failed ,the querynode is down 4:try load again ,it notice "no online queryload to query“

We'll also release 2.0.2 soon to solve this issue

**Comment by yangyongjx** [comment]
https://hub.docker.com/layers/milvusdb/milvus-dev/master-latest/images/sha256-081842fd010f59570f367a5bece63c7ab03674990805405db236ba68b9949322?context=explore

Failed to load image layers
An error occurred while loading this page: Failed to find image="sha256:081842fd010f59570f367a5bece63c7ab03674990805405db236ba68b9949322" in list of images for namespace="milvusdb", reponame="milvus-dev", tag="master-latest"

**Comment by LoveEachDay** [comment]
https://hub.docker.com/r/milvusdb/milvus-dev/tags， choose the most recent image tag. 
Use the specfic tag like `master-20220316-d65cf530`, instead of `master-latest`.

**Comment by yangyongjx** [comment]
use the version,where exec load command,it will not crash,
but when I try to delete the record,the querynode crashed,and the Attu connect failed ,it notice timeout of 60000 ms exceeded
<img width="956" alt="milvus_attu_202203171140" src="https://user-images.githubusercontent.com/3679298/158732441-fb223c91-c66c-4f17-a86f-729ab4be7e09.PNG">

(base) brave@brave-MS-7B48:~/software/milvus/data/billion/milvus_sift100m/script$ docker ps|grep query
9a1842379b56   milvusdb/milvus-dev:master-20220316-d65cf530   "/tini -- milvus run…"   About an hour ago   Up About an hour                                                             milvus-querycoord

**Comment by yangyongjx** [comment]
+querynode logs
[Uploading querylog202203171144.txt…]()

**Comment by yanliang567** [comment]
@yangyongjx   i guess you attached the wrong link for querynode logs

**Comment by yangyongjx** [comment]
[bc7f0646f4067e302e1280ca4a1e5587dd86da2e670a1008c27104c6d3a3f38a-json.log](https://github.com/milvus-io/milvus/files/8282521/bc7f0646f4067e302e1280ca4a1e5587dd86da2e670a1008c27104c6d3a3f38a-json.log)

update the log file.

**Comment by yanliang567** [comment]
It seems that the pulsar service is broken
```
{"log":"time=\"2022-03-17T02:57:26Z\" level=info msg=\"Broker notification of Closed consumer: 1\" local_addr=\"172.29.0.11:37684\" remote_addr=\"pulsar://pulsar:6650\"\n","stream":"stderr","time":"2022-03-17T02:57:26.685633352Z"}
{"log":"time=\"2022-03-17T02:57:26Z\" level=info msg=\"[Reconnecting to broker in  102.726496ms]\" consumerID=1 name=prbtj subscription=by-dev-queryNode-431878118736658433-12 topic=\"persistent://public/default/by-dev-rootcoord-dml_1\"\n","stream":"stderr","time":"2022-03-17T02:57:26.685880558Z"}
{"log":"time=\"2022-03-17T02:57:27Z\" level=error msg=\"[Failed to create consumer]\" consumerID=1 error=\"server error: ServiceNotReady: Subscription is fenced\" name=prbtj subscription=by-dev-queryNode-431878118736658433-12 topic=\"persistent://public/default/by-dev-rootcoord-dml_1\"\n","stream":"stderr","time":"2022-03-17T02:57:27.022214721Z"}

```
Could you please double check the pulsar service is running? please help to upload the pulsar logs if possible.

**Comment by yangyongjx** [comment]
[pulsar202203181239.log](https://github.com/milvus-io/milvus/files/8301615/pulsar202203181239.log)
I have restart the service, so I am not sure whether the pulsar service is running ,and the attachement is the log which is include today.

**Comment by yangyongjx** [comment]
And I try to reproduce the problem ,I insert a billion records again,( python main.py --collection ann_100m_sq8 --insert
)but the processed was hanged after insert 31,000,000 records. from the Attu dashboard,the querynode disappear,but from the docker view,querynode process is still running.
[7454860b7dcc3c7c03ad26ded52d586de326a97d4f02f1f5b2303d17f8f7a368-json.log](https://github.com/milvus-io/milvus/files/8301657/7454860b7dcc3c7c03ad26ded52d586de326a97d4f02f1f5b2303d17f8f7a368-json.log)
<img width="897" alt="attu202203181254" src="https://user-images.githubusercontent.com/3679298/158940065-17669db2-da44-4b5d-9478-7c9267a10c1c.PNG">
<img width="960" alt="mivlus202203181255" src="https://user-images.githubusercontent.com/3679298/158940072-48e4c7f5-ed6d-4261-88ab-a1cd5b5902bb.PNG">

**Comment by yangyongjx** [comment]
<img width="960" alt="mivlus202203181255" src="https://user-images.githubusercontent.com/3679298/158940236-2a820d5b-df92-43a1-a499-9ac07b3c50c5.PNG">
 the processed was hanged

**Comment by yangyongjx** [comment]
<img width="683" alt="mivlus202203181257" src="https://user-images.githubusercontent.com/3679298/158940327-7769c39c-8f1c-4038-a1ff-eda622c41313.PNG">
sorry，the last comment upload the error image,the processed was hanged ，

**Comment by yangyongjx** [comment]
[datacoord202203181315.log](https://github.com/milvus-io/milvus/files/8301792/datacoord202203181315.log)
[datanode202203181305.log](https://github.com/milvus-io/milvus/files/8301794/datanode202203181305.log)
[datanode202203181315.log](https://github.com/milvus-io/milvus/files/8301795/datanode202203181315.log)
[etcd202201381319.log](https://github.com/milvus-io/milvus/files/8301796/etcd202201381319.log)
[indexcoord20220318.log](https://github.com/milvus-io/milvus/files/8301797/indexcoord20220318.log)
[indexnode202203181314.log](https://github.com/milvus-io/milvus/files/8301798/indexnode202203181314.log)
[mino202201381321.log](https://github.com/milvus-io/milvus/files/8301799/mino202201381321.log)
[proxy202203181322.log](https://github.com/milvus-io/milvus/files/8301800/proxy202203181322.log)
[pulsar202203181319.log](https://github.com/milvus-io/milvus/files/8301801/pulsar202203181319.log)
[querycoord202203181317.log](https://github.com/milvus-io/milvus/files/8301802/querycoord202203181317.log)
[rootcoord20220318.log](https://github.com/milvus-io/milvus/files/8301803/rootcoord20220318.log)
all logs
