### ISSUE TITLE
[Bug]: can not load new collection

### ISSUE THREAD

**Issue by lzhin** [milvus-io/milvus#16089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.1
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.0.0rc8
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: querynode   Intel(R) Xeon(R) Platinum 8372HC CPU @ 3.40GHz  24 core 32GB
- GPU: no gpu
- Others:
```

### Current Behavior

when insert data, the computer crashes, and then can't load the new collection. The log in querynode is as follow:
![image](https://user-images.githubusercontent.com/17926066/158769916-fa867d6f-d7f6-40cf-8843-8d9b782904cc.png)

**Comment by JackLCL** [comment]
@lzhin 
Your server version is 2.0.1. But your pymilvus version is 2.0.0rc8. Please upgrade your pymillvus version to 2.0.1 and try again.

**Comment by lzhin** [comment]
> 

We have temporarily solved this problem by clearing etcd Minio and other data. Now it is normal. 
Before we also click to release or delete at Attu, but the page stuck and cannot be deleted. If we encounter this problem again, we will try to upgrade pymilvus and delete the collection.
But the problem now is that once this happens, the new collection cannot be loaded and retrieved.

**Comment by yanliang567** [comment]
looks like a dup to https://github.com/milvus-io/milvus/issues/15952, which was fixed now in master.

**Comment by lzhin** [comment]
> looks like a dup to #15952, which was fixed now in master.

Ok, thank you very much!
