### ISSUE TITLE
[Feature]: Caching bitset for hybrid search

### ISSUE THREAD

**Issue by ss892714028** [milvus-io/milvus#16095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

During a hybrid search, Milvus uses a bitset to filter vectors before computing distances. However, there is currently no mechanism for caching the generated bitset. I would like to propose to cache the bitset for future hybrid search with the same expression. 

My reasoning:
1. Generating a bitset is expensive without an index. It runs in linear time.
2. For users, it is very common that a hybrid search with the same expression is run multiple times, generating a bitset with every search request is repetitive and expensive. 

Love to hear your thoughts.

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Is your feature request related to a problem? Please describe.
> During a hybrid search, Milvus uses a bitset to filter vectors before computing distances. However, there is currently no mechanism for caching the generated bitset. I would like to propose to cache the bitset for future hybrid search with the same expression.
> 
> My reasoning:
> 
> 1. Generating a bitset is expensive without an index. It runs in linear time.
> 2. For users, it is very common that a hybrid search with the same expression is run multiple times, generating a bitset with every search request is repetitive and expensive.
> 
> Love to hear your thoughts.
> 
> ### Describe the solution you'd like.
> _No response_
> 
> ### Describe an alternate solution.
> _No response_
> 
> ### Anything else? (Additional Context)
> _No response_

We probably not need to cache on it but we will implement different kind of index on scalar data.
So far no evidence show that scalar filtering is slow, and we are waiting for some basic benchmark to make decision

**Comment by patelprateek** [comment]
@xiaofan-luan : can you please confirm if we are still doing brute force search to generate bitset and then do ann ? 
have we started supporting other index types on scalar fields ?

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan : can you please confirm if we are still doing brute force search to generate bitset and then do ann ? have we started supporting other index types on scalar fields ?

we hava stl sort index and that's the only option for now
