### ISSUE TITLE
[Bug]: MacOS Code Checker action fails at downloading

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#16097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://github.com/milvus-io/milvus/runs/5583652369?check_suite_focus=true

**Comment by jennyli-z** [comment]
1. One reason is the action is in degraded performance make the network on action is not that stable
     https://www.githubstatus.com/history
3. Another reason is `https://ftp.wayne.edu/apache/thrift` is not able to download  thrift for  version 0.13.0

As rerun the action can make it passed, so I think we could close this issue for now. @yanliang567 
![image](https://user-images.githubusercontent.com/93511422/158990387-cee57b4d-5f42-4b28-bbfb-69047ee30db7.png)

**Comment by yanliang567** [comment]
close for now
