### ISSUE TITLE
[Bug]: requirements.py is missing requirement

### ISSUE THREAD

**Issue by Teagum** [milvus-io/milvus#16108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Step _3. Pull and save image_ of [Install Milvus Offline](https://milvus.io/docs/v2.0.x/install_offline-docker.md#Install-Milvus-Offline) fails because `requirements.txt` is missing requirement `pyyaml`.

### Steps To Reproduce

```markdown
1. Download file
wget https://raw.githubusercontent.com/milvus-io/milvus/master/deployments/offline/requirements.txt

2. Run script in fresh venv
pip3 install -r requirements.txt
```

**Comment by yanliang567** [comment]
@Teagum sounds like a good first issue, are you interested in fixing it yourself :)

**Comment by yanliang567** [comment]
please feel free to assign to yourself if anyone is interested. :)

**Comment by Teagum** [comment]
Alright, @yanliang567 , I'll to that.

**Comment by yanliang567** [comment]
great, thx.
/assign @Teagum
