### ISSUE TITLE
[Bug]: The collection load failed before the collection's data was inserted！

### ISSUE THREAD

**Issue by Victor-Future** [milvus-io/milvus#16102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.0-pre-ga
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus v2.0.0
- OS(Ubuntu or CentOS):Ubuntu 16.04 LTS
- CPU/Memory: Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz/32G
- GPU: NVIDIA Tesla M60
- Others:
```

### Current Behavior

The following error occurs when I try to load the data in the collection while the data in the collection is not fully inserted：
_RPC error: [wait_for_loading_collection], <BaseException: (code=1, message=collection 431862526189240321 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-03-16 18:01:36.823697', 'RPC error': '2022-03-16 18:02:17.820761'}>
RPC error: [load_collection], <BaseException: (code=1, message=collection 431862526189240321 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-03-16 18:01:36.595903', 'RPC error': '2022-03-16 18:02:17.821169'}>
E_
At the time of this bug, the device has enough memory to meet the memory requirements for loading the collection
![WechatIMG62](https://user-images.githubusercontent.com/43459525/158840652-17639dc7-d5ce-4a8e-ba57-61665cc1ae96.jpeg)
It is expected to insert set 212132 data at one time, but the set data displayed as 201073 after the insertion operation. At this time, the set fails to be loaded, indicating that the display delay of the attU insertion is too high and the data cannot be loaded during the insertion process. Finally, it becomes 212132 data after half an hour.

### Expected Behavior

When data is inserted once, the insert status should be updated synchronously and prompted when attempting to load unfinished data.

**Comment by xiaofan-luan** [comment]
duplicated and should be working on 2.0.2 or the current day build

**Comment by yanliang567** [comment]
@Victor-Future you can first collection.load() and then collection.insert().

**Comment by yanliang567** [comment]
@Victor-Future also please retry with latest build. thanks.

/assign @Victor-Future 
/unassign

**Comment by Victor-Future** [comment]
Ok, check the latest version and try again to see if this bug still exists

**Comment by Victor-Future** [comment]
@yanliang567  My question is similar to this one #15952, so let's test it out
