### ISSUE TITLE
[Feature]: The paging function

### ISSUE THREAD

**Issue by xiaolongjiangkolena** [milvus-io/milvus#16101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

would be great if we can do pagination instead of only return topK result back.

**Comment by xiaofan-luan** [comment]
pagination is needed for query or range search, but might not be in KNN search.
What's the scenario you want to use paging? like the topk is really large?

**Comment by xiaolongjiangkolena** [comment]
our use case is we would like to use filter and vector search together. If we only restrict to topK, we will miss some result if filter itself can return larger than  topK result .

**Comment by xiaofan-luan** [comment]
keep it on track, this should be done on 2.2

**Comment by xiaofan-luan** [comment]
we already supported with query/search with limit/offset.
There is an issue tracking iterator features and it should be already in Milvus 2.3
