### ISSUE TITLE
[Bug]: Installation of Milvus offline fails because save_image.py does not download image

### ISSUE THREAD

**Issue by Teagum** [milvus-io/milvus#16107]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Installation of Milvus offline fails because `save_image.py` does not download images but exits without error status.

### Expected Behavior

File download should either complete, or abort with error status.

### Steps To Reproduce

```markdown
1. Download Files

- wget https://github.com/milvus-io/milvus/releases/download/v2.0.1/milvus-standalone-docker-compose.yml -O docker-compose.yml
- wget https://raw.githubusercontent.com/milvus-io/milvus/master/deployments/offline/requirements.txt
- wget https://raw.githubusercontent.com/milvus-io/milvus/master/deployments/offline/save_image.py

2. Save image

- pip3 install -r requirements.txt
- python3 save_image.py --manifest docker-compose.yml
```

**Comment by yanliang567** [comment]
@LoveEachDay could you please help on this issue?

/assign @LoveEachDay 
/unassign

**Comment by LoveEachDay** [comment]
You can make the following checks:
1.  check whether docker is running
2. check your download `docker-compose.yml` is valid.

**Comment by Teagum** [comment]
I used `curl` to download the files instead of `wget`. The problem is that by default `curl` does not follow redirects but instead downloads the redirect notification.

So, be sure to add `-L` flag if you use `curl`:

    curl -L <URL> -o out_file
