### ISSUE TITLE
[Bug]: ID array size problem for the advanced search

### ISSUE THREAD

**Issue by ufuk23** [milvus-io/milvus#16115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.0
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 4 / 16 GB
- GPU: No
- Others:
```

### Current Behavior

When I search a vector using the advanced filter with 1M ids' like this "pk in =[1, 2, 3, ...]" it takes a long time. It's about 3-4 seconds for 100K ids' and 30 seconds for 1M ids'. It means the more id size, the more response time.

Why we need this case is we have to filter some records with Apache Solr and get the record ids first. Then we need a Milvus search with a given vector and these ids. We have about 5 million records on Solr, and we may get 1M ids' when we search it.
Can you improve the search speed even if a large id array is passed as pk?

**Comment by xiaofan-luan** [comment]
Hi uf, 
what is the search condition in solr? 
If it's simply some inverted index on int or string milvus is gonna to support soon.
Actually we did not do too much performance optimization and the in operation will be simply optimized to a bunch of and operation,  which may cause very slow speed

**Comment by xiaofan-luan** [comment]
@yanliang567 attribute filtering should be considered soon after milvus 2.1 release I guess

**Comment by yanliang567** [comment]
> @yanliang567 attribute filtering should be considered soon after milvus 2.1 release I guess

agree.

**Comment by ufuk23** [comment]
> Hi uf, what is the search condition in solr? If it's simply some inverted index on int or string milvus is gonna to support soon. Actually we did not do too much performance optimization and the in operation will be simply optimized to a bunch of and operation, which may cause very slow speed

If you can achieve the performance optimization for the "pk in" query, that will be great. 

We show data with the Solr filter according to user permissions. And some users have admin permission, and they may search the whole data. I mean, it is a common scenario used in practice.

Perhaps we can use some extra fields on Milvus that already exist on Solr, but we don't want to do it. We want to use Milvus to keep vectors only, not other fields as Solr does. Otherwise, we may have synchronization problems between Solr and Milvus.

**Comment by ufuk23** [comment]
Is there any activity about this issue?

**Comment by yanliang567** [comment]
@czs007 I think it is in progress in milvus 2.1, any news ?

**Comment by xiaofan-luan** [comment]
@ufuk23 you can try Milvus 2.0.2, it optimized query by PK performance, see if it will help you~
