### ISSUE TITLE
[Bug]: Server can not be recovered after docker-compse restart

### ISSUE THREAD

**Issue by ATUFO** [milvus-io/milvus#16117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.0.1
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): Java SDK milvus 2.0.0
- OS(Ubuntu or CentOS): Ubuntu 18.04
- CPU/Memory: Intel Xeon Gold 6133 @ 4x 2.494GHz      4G Memory
- GPU: None
- Others: 腾讯云服务器
```

### Current Behavior

When I create a new service ,I can index and query data.  In the tests , I inserted 32 records .It's nothing wrong , but when I restart my server or exec `docker-compose restart    |     docker restart xxxx` ( in a word, restart the service), the search didn't work.

see attu dashboard
![580512dadc9e5f674bc3ef33aa9c96c](https://user-images.githubusercontent.com/18240599/159123855-5a383923-6d96-4007-80d5-2f4319681315.png)

### Expected Behavior

Search normally

### Steps To Reproduce

```markdown
1. create a milvus service
2. insert some data ( In my tests,there are only 32 records)
3. restart service ( docker-compose restart |  systemctl restart milvus). I tested docker-compose version and direct install on linux.
4. search . I tested using Attu
```

**Comment by zhuwenxing** [comment]
Hi, you can check the status of the Milvus container. Searching may cause querynode panic after the container is restarted, see https://github.com/milvus-io/milvus/issues/15713. But in the latest version, this issue should have been fixed.

**Comment by ATUFO** [comment]
> Hi, you can check the status of the Milvus container. Searching may cause querynode panic after the container is restarted, see #15713. But in the latest version, this issue should have been fixed.

The version I installed is v2.0.1 。 I have seen #15713 .After that , I updated milvus from v2.0.0 to v2.0.1 。But I have the same problem。


`there are too few available query nodes to balance`  means what? No querynods or at least one querynode exists?
```
[2022/03/20 00:56:45.785 +00:00] [WARN] [query_coord.go:532] ["loadBalanceSegmentLoop: there are too few available query nodes to balance"] [onlineNodeIDs="[27]"] [availableNodeIDs="[27]"]
```

**Comment by xiaofan-luan** [comment]
> > Hi, you can check the status of the Milvus container. Searching may cause querynode panic after the container is restarted, see #15713. But in the latest version, this issue should have been fixed.
> 
> The version I installed is v2.0.1 。 I have seen #15713 .After that , I updated milvus from v2.0.0 to v2.0.1 。But I have the same problem。
> 
> `there are too few available query nodes to balance` means what? No querynods or at least one querynode exists?
> 
> ```
> [2022/03/20 00:56:45.785 +00:00] [WARN] [query_coord.go:532] ["loadBalanceSegmentLoop: there are too few available query nodes to balance"] [onlineNodeIDs="[27]"] [availableNodeIDs="[27]"]
> ```

Usually this means:
1) memory is not enough for the querynode to load data
2) querynode is not healthy for some reason.

My suggestion is 1) check if you have enough memory to load data 2) if that's not the case, upload your log in querynode/querycoord and we will help you on investigation

**Comment by yanliang567** [comment]
@ATUFO you could also try with latest master build. 

/assign @ATUFO 
/unassign

**Comment by xiaofan-luan** [comment]
> Hi, I am having the same problem on K8S after a restart of the service if any collection was already loaded

Hi Alvise, could you try 2.0.2?
