### ISSUE TITLE
[Bug]: query by id on k8s is much slower than just in docker-container

### ISSUE THREAD

**Issue by Mercurialll** [milvus-io/milvus#16111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: every version from 2.0.0 -> till today
- Deployment mode(standalone or cluster): standalone in k8s
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus2.0.0 & pymilvus2.0.1
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: aws xeon / 8GB for milvus (of 16gb)
- GPU: -
- Others:
```

### Current Behavior

When I conduct query-search by ID in standalone version just in docker-container -> I get speed around 10-50ms.
When I conduct query-search by ID in standalone version in k8s cluster -> I get speed around 200-400ms.

### Expected Behavior

I expected to get the same speed in both configurations.

### Steps To Reproduce

```markdown
1. standalone milvus in k8s with default milvus settings. 
2. create collection and fulfill 50k rows: id & vector(2048dim).
3. create index "index_type": "IVF_FLAT", "nlist": 100, "metric_type": "IP".
4. 100 query-searches -> get mean/median speed.
```

### Anything else?

inside scripts to test speed & dock.compose & req-s

[milvus_iss2.zip](https://github.com/milvus-io/milvus/files/8304108/milvus_iss2.zip)

**Comment by yanliang567** [comment]
@Mercurialll thank you for your issue and repro code. we will investigate it soon.

**Comment by xiaofan-luan** [comment]
hi @Mercurialll, what kind of persistent volume are u using while running on K8s cluster?
Guess this might be related to the pvc speed of k8s

**Comment by yanliang567** [comment]
@Mercurialll as xiaofan said above, I tested with 1 million 1024 dim data, the query latency is about 20ms averagely(but not stable enough #16126), but it does not make difference between deployment on k8s or docker-container. Could you please check again with the same persistent volume(for minio)?

/assign @Mercurialll 
/unassign

**Comment by Mercurialll** [comment]
Hello @yanliang567 @xiaofan-luan 
PV= gp3 

I will try to check again and then I'll post the results here

**Comment by xiaofan-luan** [comment]
> n ANN-search spends 20-100ms

That's because ann-search is only in memory while query by id access disk.

There are two possible solutions:
1) load original vector into memory
2) for some of the indexes (if not IVFPQ or SQ), we can directly load vector from index.

if you are intersted please help us on optimizing query by id feature @Mercurialll , or we will leave it to 2.2 until we have enough hands on it

**Comment by Mercurialll** [comment]
I dont understand what do you mean, can you clarify pls:

> 1. load original vector into memory
Do you mean ` collection.load()` and then conduct query? - if so , I always load collections before querying. 

> for some of the indexes (if not IVFPQ or SQ), we can directly load vector from index.
I use IVF_FLAT, how can I get data by id ? - I thought that only one way exists to do it: load collection and then conduct `collection.query(expr="id in [MY_ID]", output_fields=['id', 'vector'], consistency_level=ConsistencyLevel.Eventually)`
