### ISSUE TITLE
[Bug]: Memory usage exception during load

### ISSUE THREAD

**Issue by WeiDong-Shi** [milvus-io/milvus#16123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.5
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.1
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 16  Intel(R) Xeon(R) Platinum 8374C CPU @ 2.70GHz / 128 G
- GPU: 
- Others:
```

### Current Behavior

During the test, 100W pieces of data were written. The vector dimension was 2048. After loading, about 107 g of memory was used. The environment was clean and no other services were running.During the second test, the memory is used normally, and then try to reproduce it again.
[Uploading Docker_Logs-2022.03.21-16:26:46.tar.gz…]()

**Comment by WeiDong-Shi** [comment]
Add the log. The last log upload should have failed.
[Docker_Logs-2022.03.21-16:26:46.tar.gz](https://github.com/milvus-io/milvus/files/8314099/Docker_Logs-2022.03.21-16.26.46.tar.gz)

**Comment by yanliang567** [comment]
one quick question:
did you build index before load collection? what is the index type and index params?

**Comment by WeiDong-Shi** [comment]
The data is not indexed or loaded before collection. After data is written, the index is created first and then loaded.
Index type: IVF_ FLAT
Index parameter: metric_ type:L2，nlist:128

**Comment by WeiDong-Shi** [comment]
> 一个简单的问题： 你在负载收集之前建立了索引吗？什么是索引类型和索引参数？

The data is not indexed or loaded before collection. After data is written, the index is created first and then loaded.

**Comment by yanliang567** [comment]
one more question:
before load collection, how much memory was used? when 107g memory was used, how much for querynode? and waht about the other nodes?

**Comment by WeiDong-Shi** [comment]
> 还有一个问题： 在负载收集之前，使用了多少内存？使用107g内存时，querynode多少钱？其他节点呢？

Before the collection, the environment was clean and the memory usage was less than 2G. After the test, the memory usage of the node was not checked.

**Comment by WeiDong-Shi** [comment]
> one quick question: did you build index before load collection? what is the index type and index params?

The test with the problem is to write the data first, then build the index, and then load the data.

Index type: IVF_ FLAT

Index parameter: metric_ type:L2，nlist:128

**Comment by yanliang567** [comment]
@WeiDong-Shi  one more question:
before load collection, how much memory was used? when 107g memory was used, how much for querynode? and waht about the other nodes?

**Comment by WeiDong-Shi** [comment]
> Before the collection, the environment was clean and the memory usage was less than 2G. After the test, the memory usage of the node was not checked.

Before the collection, the environment was clean and the memory usage was less than 2G. After the test, the memory usage of the node was not checked.

**Comment by xiaofan-luan** [comment]
if it's float, then it should take around 16g memory, @WeiDong-Shi did you find the reason yet?

**Comment by WeiDong-Shi** [comment]
> if it's float, then it should take around 16g memory, @WeiDong-Shi did you find the reason yet?

This problem has not reappeared in the follow-up, and the reason has not been found yet.
