### ISSUE TITLE
[Bug]: cannot find collection but has it

### ISSUE THREAD

**Issue by xqxq-2020** [milvus-io/milvus#16121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:milvusdb/milvus:v2.0.0-rc5-hotfix1-20210901-9e0b2cc
- Deployment mode(standalone or cluster):standalone 
- SDK version(e.g. pymilvus v2.0.0rc2):2.0.0
- OS(Ubuntu or CentOS): CentOS7
- CPU/Memory: Intel(R) Xeon(R) Silver 4215R CPU @ 3.20GHz
- GPU: Quadro K6000
- Others:
```

### Current Behavior

After I create a collection name 'icd',but i run my programe have a error:
![06a66176c5d99caa784d70bb6919094](https://user-images.githubusercontent.com/62696048/159221189-5d33389d-b448-4a5b-8931-e703ac5c2e75.png)

the dashboard have this collection:

![070c3b29704b35ed82352c404510579](https://user-images.githubusercontent.com/62696048/159221254-8bdee437-dc21-4c5e-9616-a91d29cd72b2.png)

**Comment by yanliang567** [comment]
@xqxq-2020 could you please retry with the latest release 2.0.1? If it reproduced for you, please help to upload the milvus pod logs for investigation?

/assign @xqxq-2020 
/unassign

**Comment by xqxq-2020** [comment]
What are the specific  2.0.1 versions like this:
![image](https://user-images.githubusercontent.com/62696048/159393293-5aa66aad-910c-4821-8260-672cb0d22790.png)

**Comment by yanliang567** [comment]
image: milvusdb/milvus:v2.0.1

**Comment by yanliang567** [comment]
BTW, in case you want to use a latest master build: https://hub.docker.com/r/milvusdb/milvus-dev/tags, choose the most recent image tag.
Use the specfic tag like master-20220316-d65cf530
