### ISSUE TITLE
[Bug]: Embedding retreival stuck for more than 12 hours

### ISSUE THREAD

**Issue by k-for-code** [milvus-io/milvus#16130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
Milvus version: 2.0.0
Deployment mode(standalone or cluster): standalone
SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.0.1
OS(Ubuntu or CentOS): Ubuntu 20.04 lts
CPU/Memory: 16 gb ram
GPU: No
Others: 8828536 vectors, IVF_FLAT indexing, using BootCamp code, docker-compose.yml
```

### Current Behavior

Tried to retrieve embedding using a milvus_id, thread execution started and kept on running for more than 12 hours had to kill the process.
No exception, errors, or logs made

```Python
def retreive_embeddings(self, collection_name, milvus_id):
        try:
            self.set_collection(collection_name) #this works have tested
            list_of_ids = [milvus_id]
            results = self.collection.query(  # this is where it gets stuck
                expr=f"id in {list_of_ids}",
                output_fields=["embedding"],
            )
            return [x["embedding"] for x in results]
        except Exception as e:
            LOGGER.error(f"Failed to retreive embeddings in Milvus: {e}, id {milvus_id}")
``` 

### Expected Behavior

Should have returned something, at least an error, exception, or the embeddings.
I checked the dockers, they were running healthy.
This was weird, Do you think the size of data i.e 8828536 vectors and IVF_FLAT is the issue?
Please let me know.

### Anything else?
nlist - 65536
nprobe - earlier 1024, now just 5,   either doesn't help
also, i faced another issue, and i think these are connected, give it a look too
https://github.com/milvus-io/milvus/issues/3250#issuecomment-1073181224
_No response_

**Comment by yanliang567** [comment]
@k-for-code how much is the length of list_of_ids in expr?  did you load the collection successfully before query? could you please help to upload the milvus container log for investigation?
/assign @k-for-code 
/unassign

**Comment by k-for-code** [comment]
the length was 1, but I was not loading the collection, I have modified the code. Thanks
