### ISSUE TITLE
[Bug]: Flush performance degrade for the collection created during chaos after datacoord pod recovered from pod kill 

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#16134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220321-2078b24d
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.0.2.dev5
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

**Get collection entities cost 15.4309 seconds**
```
check collection CreateChecker__Yfx24DUW
collection exists

Create collection...

Insert 3000 vectors cost 0.5203 seconds

Get collection entities...
3000

Get collection entities cost 15.4309 seconds
```

### Expected Behavior

**Get collection entities cost 3.7377 seconds**
```
check collection Checker__m9FOw5zU
collection exists

Create collection...
Insert 3000 vectors cost 0.4555 seconds

Get collection entities...
8200

Get collection entities cost 3.7377 seconds
```

### Steps To Reproduce

```markdown
see https://github.com/milvus-io/milvus/runs/5632714245?check_suite_focus=true
```

### Anything else?

failed job: https://github.com/milvus-io/milvus/runs/5632714245?check_suite_focus=true
logs: https://github.com/milvus-io/milvus/suites/5742511778/artifacts/190470457

**Comment by yanliang567** [comment]
@zhuwenxing does this performance degrade persist? I am asking because I want to make sure it is not because of the first time it flushes

**Comment by zhuwenxing** [comment]
> @zhuwenxing does this performance degrade persist? I am asking because I want to make sure it is not because of the first time it flushes

Not sure, need more tests. These collections all are created during the chaos and empty. But why does it matter if it was the first time it flushes?

**Comment by zhuwenxing** [comment]
https://github.com/milvus-io/milvus/runs/5863529511?check_suite_focus=true
This issue still exists. From the observation,  flush performance degrades mainly happened in collections that were with the prefix `CreateChecker`.  Collections with the prefix `CreateChecker` were created during the chaos and they were empty collections and had never been flushed before.

**Comment by soothing-rain** [comment]
> @soothing-rain any updates

Nope. It is not a P0 issue, should it be escalated?

**Comment by zhuwenxing** [comment]
It also happened for minio pod kill
This job is failed due to timeout, because flush of collection which prefix is CreateChecker cost a lot of time.
https://github.com/zhuwenxing/milvus/runs/6885879889?check_suite_focus=true

![image](https://user-images.githubusercontent.com/12268675/173762979-cf398f0f-c432-4574-9d2a-0b04319e9d27.png)

![image](https://user-images.githubusercontent.com/12268675/173762844-1ed775ac-cc07-4f0c-b24a-0bb908156fee.png)

**Comment by xiaofan-luan** [comment]
@wayblink shall we close this issue?

**Comment by wayblink** [comment]
> @wayblink shall we close this issue?

Let's keep it, still explore it.

**Comment by zhuwenxing** [comment]
failed job: https://github.com/zhuwenxing/milvus/runs/6978232289?check_suite_focus=true
log: https://github.com/zhuwenxing/milvus/suites/7017209278/artifacts/275695453

**Comment by zhuwenxing** [comment]
This issue also happens when Milvus uses kafka as MQ, and the performance degradation is more significant.

failed job: http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test-kafka/detail/chaos-test-kafka/75/pipeline
log:[artifacts-datacoord-pod-kill-75-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/8954902/artifacts-datacoord-pod-kill-75-server-logs.tar.gz)

**Comment by wayblink** [comment]
@zhuwenxing any new test cases？

**Comment by zhuwenxing** [comment]
for datacoord pod kill, this issue still exists
chaos type: pod-kill image tag: 2.1.0-20220913-3c3ba55 target pod: datacoord
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release/detail/chaos-test-kafka-for-release/426/pipeline

![image](https://user-images.githubusercontent.com/12268675/190328430-363916cc-8a8a-4939-9bd6-ebeff137ae7b.png)

![image](https://user-images.githubusercontent.com/12268675/190328544-f89c02a3-83c7-45e4-8214-77e13cdf7170.png)

for the collection with the prefix CreateChecker, the flush time is much longer then other collections

**Comment by zhuwenxing** [comment]
> @zhuwenxing any new test cases？

I think this issue has not been fixed as far as I know, so it is not about the new test cases.
I reopen it just because it is closed by the stable bot, however, the issue is not fixed yet.

**Comment by zhuwenxing** [comment]
chaos type: pod-failure image tag: 2.1.0-20220921-a0ab90ea target pod: datacoord
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release/detail/chaos-test-kafka-for-release/596/pipeline
log:
[artifacts-datacoord-pod-failure-596-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9621660/artifacts-datacoord-pod-failure-596-pytest-logs.tar.gz)
[artifacts-datacoord-pod-failure-596-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9621662/artifacts-datacoord-pod-failure-596-server-logs.tar.gz)

**Comment by xiaofan-luan** [comment]
keep

**Comment by yanliang567** [comment]
@zhuwenxing is it still a valid issue?

**Comment by zhuwenxing** [comment]
It was not reproduced in master-20221219-856bceec
https://github.com/zhuwenxing/milvus/actions/runs/3737035097/jobs/6341904578
![image](https://user-images.githubusercontent.com/12268675/208574389-de0e4354-5693-4f6e-88d1-330f417cfd02.png)
