### ISSUE TITLE
[Bug]: v2.0.1 server is not healthy,

### ISSUE THREAD

**Issue by xqxq-2020** [milvus-io/milvus#16137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:milvusdb/milvus:v2.0.1
- Deployment mode(standalone or cluster):standalone 
- SDK version(e.g. pymilvus v2.0.0rc2):2.0.1
- OS(Ubuntu or CentOS): CentOS7
- CPU/Memory: Intel(R) Xeon(R) Silver 4215R CPU @ 3.20GHz
- GPU: Quadro K6000
- Others:
```

### Current Behavior

After change to 2.0.1 server is also not healthy, please try again later

The same problem is encountered, but it also does not work after restart. Do you have any methods to solve it?

dashboard:

![f942272ae0f17841c687e8a0bee9347](https://user-images.githubusercontent.com/62696048/159405653-91d51823-1ddd-41f3-a2f0-f505011bbb39.png)

server error:

![511a3da8bafe60940ad736171fcbcc8](https://user-images.githubusercontent.com/62696048/159405684-32039345-9164-4f40-97c9-5367f8fa76ab.png)

### Anything else?

error logs:

[milvus.log](https://github.com/milvus-io/milvus/files/8320973/milvus.log)

[minio.log](https://github.com/milvus-io/milvus/files/8321450/minio.log)

[milvus-etcd.log](https://github.com/milvus-io/milvus/files/8321468/milvus-etcd.log)

**Comment by xiaofan-luan** [comment]
this seems to be etcd log. 
if you can offer full log of standaloen server that would be helpful.

v2.0.0-rc5-hotfix1 is not compatible with 2.0 ga version.

**Comment by xqxq-2020** [comment]
I used version is 2.0.1

**Comment by xiaofan-luan** [comment]
> I used version is 2.0.1

please offer logs and we will take a look~

**Comment by xqxq-2020** [comment]
[milvus-etcd.log](https://github.com/milvus-io/milvus/files/8321722/milvus-etcd.log)
[minio.log](https://github.com/milvus-io/milvus/files/8321724/minio.log)
[milvus.log](https://github.com/milvus-io/milvus/files/8321725/milvus.log)

here is logs

**Comment by yanliang567** [comment]
@xige-16  does it the same issue with #14873? but this is about standalone.
/assign @xqxq-2020 
/unassign

**Comment by JackLCL** [comment]
@xige-16 
pls help to investigate this issue.

**Comment by yanliang567** [comment]
@xqxq-2020 could you please retry with latest release v2.0.2 in a clear env.?
