### ISSUE TITLE
[Enhancement]: Get whole collection

### ISSUE THREAD

**Issue by dariocurr** [milvus-io/milvus#16132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

I would like to have a method to retrieve all the rows from a collection, something like `SELECT *` in `SQL`.

Currently I achieve this goal using the following boolean expression: `index != -1`, but I guess this is not the best way to to this.

### Why is this needed?

I have to retrieve the whole table to train a model

### Anything else?

I would like to understand if you will implement it in the future or don't want to implement it for some reason

**Comment by xiaofan-luan** [comment]
Yep, we have this in plan but it's delayed due to lack of manpower.
We want to implement a iterator and iterate through the whole collection

**Comment by zhangdiandian0127** [comment]
Hello, I am looking for some good first issues. And I'm interested in this issue, i want try it.
