### ISSUE TITLE
[Bug]: milvus-pulsar-bookkeeper  pod can't start.

### ISSUE THREAD

**Issue by wangfeifans** [milvus-io/milvus#16175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.2
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 32core/256G
- GPU: no
- Others:
```

### Current Behavior

我们的数据量比较大，数亿张图片张量数据
从milvus单机版切换到集群版本以来，已经崩溃了三次，每次都是milvus-pulsar-bookkeeper -1这个节点出现问题
![3](https://user-images.githubusercontent.com/65521300/159854062-369d2a1e-5245-4ae0-9547-a61d3b77b6c8.png)
![2](https://user-images.githubusercontent.com/65521300/159854092-37993886-1eb1-40c3-93f1-dbd9e20ac479.png)
但这时还可以插入数据，只是不能够检索了。

最近二次都是在在使用attu以后做查询崩溃 ， 
我做了如下操作，检索id>1的数据，在这之后，系统崩溃 milvus-pulsar-bookkeeper 挂掉
![1](https://user-images.githubusercontent.com/65521300/159854168-658e08b2-4503-4da0-ab1e-f8daf7d8c75c.png)
我相当怀疑返回数据记录没有做限制，导致数据量过大，引起bookkeeper 崩溃。。。

**Comment by yanliang567** [comment]
@wangfeifans Hi there, thank you for the issue. Could you please update the issue in English so that more people around the world could join this conversion. 

/assign @wangfeifans 
/unassign

**Comment by Tom-debugs** [comment]
> @wangfeifans Hi there, thank you for the issue. Could you please update the issue in English so that more people around the world could join this conversion.
> 
> /assign @wangfeifans /unassign

现在网页翻译这么方便，外国朋友应该不存在看不懂这个issue吧...
