### ISSUE TITLE
[Bug]: Datacoord node start failed

### ISSUE THREAD

**Issue by lijonnas** [milvus-io/milvus#16191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.0.1
- Deployment mode(standalone or cluster): Cluster with external S3, etcd and pulsar enabled
- SDK version(e.g. pymilvus v2.0.0rc2): None
- OS(Ubuntu or CentOS): ubuntu18.04.1x86_64
- CPU/Memory: 
- GPU: None
- Others:
```

### Current Behavior

the datacoord log is the following:
> Welcome to use Milvus!
> Version:   v2.0.1
> Built:     Wed Feb 23 06:23:51 UTC 2022
> GitCommit: ce9662c1
> GoVersion: go version go1.16.9 linux/amd64
> 
> open pid file: /run/milvus/datacoord.pid
> lock pid file: /run/milvus/datacoord.pid
> [2022/03/25 01:58:39.252 +00:00] [DEBUG] [base_table.go:65] ["config directory"] [configDir=/milvus/configs/]
> [2022/03/25 01:58:39.254 +00:00] [DEBUG] [component_param.go:592] ["init cacheSize"] ["cacheSize (GB)"=0]
> [2022/03/25 01:58:39.254 +00:00] [DEBUG] [component_param.go:624] ["query node init gracefulTime"] [gracefulTime=0]
> [2022/03/25 01:58:39.255 +00:00] [DEBUG] [base_table.go:65] ["config directory"] [configDir=/milvus/configs/]
> [2022/03/25 01:58:39.257 +00:00] [DEBUG] [grpc_param.go:118] [initServerMaxSendSize] [role=datacoord] [grpc.serverMaxSendSize=2147483647]
> [2022/03/25 01:58:39.257 +00:00] [DEBUG] [grpc_param.go:141] [initServerMaxRecvSize] [role=datacoord] [grpc.serverMaxRecvSize=2147483647]
> [2022/03/25 01:58:39.259 +00:00] [DEBUG] [service.go:125] ["network port"] [port=13333]
> [2022/03/25 01:58:39.360 +00:00] [DEBUG] [session_util.go:86] ["Session try to connect to etcd"]
> [2022/03/25 01:58:39.366 +00:00] [DEBUG] [session_util.go:101] ["Session connect to etcd success"]
> [2022/03/25 01:58:39.379 +00:00] [DEBUG] [session_util.go:175] ["Session get serverID success"] [key=id] [ServerId=358]
> [2022/03/25 01:58:39.379 +00:00] [INFO] [base_table.go:440] ["Set log file to "] [path=]
> [2022/03/25 01:58:40.196 +00:00] [ERROR] [service.go:166] ["DataCoord start failed"] [error="All attempts results:\nattempt #1:Access Denied.\nattempt > #2:Access Denied.\n"] [stack="github.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).start\n\t/go/src/github.com/milvus-io/milvus/internal/> distributed/datacoord/service.go:166\ngithub.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/> internal/distributed/datacoord/service.go:214\ngithub.com/milvus-io/milvus/cmd/components.(*DataCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/> components/data_coord.go:47\ngithub.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runDataCoord.func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/> roles.go:243"]
> [2022/03/25 01:59:39.395 +00:00] [INFO] [grpclog.go:37] ["[core]parsed scheme: \"\""]
> [2022/03/25 01:59:39.395 +00:00] [INFO] [grpclog.go:37] ["[core]scheme \"\" not registered, fallback to default scheme"]
> [2022/03/25 01:59:39.395 +00:00] [INFO] [grpclog.go:37] ["[core]ccResolverWrapper: sending update to cc: {[{172.22.100.127:53100  <nil> 0 <nil>}] <nil> <> nil>}"]
> [2022/03/25 01:59:39.395 +00:00] [INFO] [grpclog.go:37] ["[core]ClientConn switching balancer to \"pick_first\""]
> [2022/03/25 01:59:39.395 +00:00] [INFO] [grpclog.go:37] ["[core]Channel switches to new LB policy \"pick_first\""]
> [2022/03/25 01:59:39.395 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel Connectivity change to CONNECTING"]
> [2022/03/25 01:59:39.395 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel picks a new address \"172.22.100.127:53100\" to connect"]
> [2022/03/25 01:59:39.396 +00:00] [INFO] [grpclog.go:37] ["[core]pickfirstBalancer: UpdateSubConnState: 0xc000606830, {CONNECTING <nil>}"]
> [2022/03/25 01:59:39.396 +00:00] [INFO] [grpclog.go:37] ["[core]Channel Connectivity change to CONNECTING"]
> [2022/03/25 01:59:39.396 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel Connectivity change to READY"]
> [2022/03/25 01:59:39.396 +00:00] [INFO] [grpclog.go:37] ["[core]pickfirstBalancer: UpdateSubConnState: 0xc000606830, {READY <nil>}"]
> [2022/03/25 01:59:39.396 +00:00] [INFO] [grpclog.go:37] ["[core]Channel Connectivity change to READY"]
> [2022/03/25 02:00:18.170 +00:00] [WARN] [healthz_handler.go:100] ["component is unhealthy"] [state=Initializing]
> [2022/03/25 02:00:28.170 +00:00] [WARN] [healthz_handler.go:100] ["component is unhealthy"] [state=Initializing]
> [2022/03/25 02:00:38.170 +00:00] [WARN] [healthz_handler.go:100] ["component is unhealthy"] [state=Initializing]
> [2022/03/25 02:00:38.597 +00:00] [WARN] [healthz_handler.go:100] ["component is unhealthy"] [state=Initializing]
> [2022/03/25 02:00:48.170 +00:00] [WARN] [healthz_handler.go:100] ["component is unhealthy"] [state=Initializing]
> [2022/03/25 02:00:58.171 +00:00] [WARN] [healthz_handler.go:100] ["component is unhealthy"] [state=Initializing]
> [2022/03/25 02:01:08.170 +00:00] [WARN] [healthz_handler.go:100] ["component is unhealthy"] [state=Initializing]
> [2022/03/25 02:01:08.597 +00:00] [WARN] [healthz_handler.go:100] ["component is unhealthy"] [state=Initializing]
> [2022/03/25 02:01:18.170 +00:00] [WARN] [healthz_handler.go:100] ["component is unhealthy"] [state=Initializing]
> [2022/03/25 02:01:28.170 +00:00] [WARN] [healthz_handler.go:100] ["component is unhealthy"] [state=Initializing]
> [2022/03/25 02:01:38.170 +00:00] [WARN] [healthz_handler.go:100] ["component is unhealthy"] [state=Initializing]
> [2022/03/25 02:01:38.596 +00:00] [WARN] [healthz_handler.go:100] ["component is unhealthy"] [state=Initializing]
> [2022/03/25 02:01:48.170 +00:00] [WARN] [healthz_handler.go:100] ["component is unhealthy"] [state=Initializing]
> [2022/03/25 02:01:58.170 +00:00] [WARN] [healthz_handler.go:100] ["component is unhealthy"] [state=Initializing]
> [2022/03/25 02:02:08.170 +00:00] [WARN] [healthz_handler.go:100] ["component is unhealthy"] [state=Initializing]
> [2022/03/25 02:02:08.597 +00:00] [WARN] [healthz_handler.go:100] ["component is unhealthy"] [state=Initializing]
> [2022/03/25 02:02:18.170 +00:00] [WARN] [healthz_handler.go:100] ["component is unhealthy"] [state=Initializing]
> [2022/03/25 02:02:28.170 +00:00] [WARN] [healthz_handler.go:100] ["component is unhealthy"] [state=Initializing]
> [2022/03/25 02:02:38.170 +00:00] [WARN] [healthz_handler.go:100] ["component is unhealthy"] [state=Initializing]
> [2022/03/25 02:02:38.597 +00:00] [WARN] [healthz_handler.go:100] ["component is unhealthy"] [state=Initializing]
> [2022/03/25 02:02:38.608 +00:00] [ERROR] [roles.go:496] ["Get signal to exit\n"] [signal=terminated] [stack="github.com/milvus-io/milvus/cmd/roles.(*> MilvusRoles).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:496\nmain.main\n\t/go/src/github.com/milvus-io/milvus/cmd/> main.go:296\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"]
> [2022/03/25 02:02:38.609 +00:00] [INFO] [grpclog.go:37] ["[core]Channel Connectivity change to SHUTDOWN"]

here is the milvus config milvus.yaml:

> 
> etcd:
>   endpoints:
>     - etcd-dev.arch.svc.cluster.local:2379
>   rootPath: milvus-dev-1
>   metaSubPath: meta # metaRootPath = rootPath + '/' + metaSubPath
>   kvSubPath: kv # kvRootPath = rootPath + '/' + kvSubPath
> 
> minio:
>   address: test.cos.ap-shanghai.myqcloud.com
>   port: 80
>   accessKeyID: testaccessKeyID
>   secretAccessKey: testsecretAccessKey
>   useSSL: false
>   bucketName: test.milvus-dev
>   rootPath: milvus-dev/
> 
> pulsar:
>   address: pulsar-dev-broker.arch.svc.cluster.local
>   port: 6650
> 
> rocksmq:
>   path: "/var/lib/milvus/rdb_data"
>   rocksmqPageSize: "2147483648"  # 2 GB
>   retentionTimeInMinutes: 10080
>   retentionSizeInMB: 8192
> 
> rootCoord:
>   address: milvus-dev-rootcoord
>   port: 53100
> 
>   grpc:
>     serverMaxRecvSize: 2147483647  # math.MaxInt32
>     serverMaxSendSize: 2147483647  # math.MaxInt32
>     clientMaxRecvSize: 104857600   # 100 MB, 100 * 1024 * 1024
>     clientMaxSendSize: 104857600   # 100 MB, 100 * 1024 * 1024
> 
>   dmlChannelNum: "256"  # The number of dml channels created at system startup
>   maxPartitionNum: "4096"  # Maximum number of partitions in a collection
>   minSegmentSizeToEnableIndex: "1024"  # It's a threshold. When the segment size is less than this value, the segment will not be indexed
>   timeout: 3600  # time out, 5 seconds
>   timeTickInterval: 200  # ms, the interval that proxy synchronize the time tick
> 
> proxy:
>   port: 19530
> 
>   grpc:
>     serverMaxRecvSize: 2147483647  # math.MaxInt32
>     serverMaxSendSize: 2147483647  # math.MaxInt32
>     clientMaxRecvSize: 104857600   # 100 MB, 100 * 1024 * 1024
>     clientMaxSendSize: 104857600   # 100 MB, 100 * 1024 * 1024
> 
>   timeTickInterval: "200"  # ms, the interval that proxy synchronize the time tick
>   msgStream:
>     insert:
>       bufSize: 1024  # msgPack chan buffer size
>     search:
>       bufSize: 512
>     searchResult:
>       recvBufSize: 1024  # msgPack chan buffer size
>       pulsarBufSize: 1024  # pulsar chan buffer size
>     timeTick:
>       bufSize: 512
>   maxNameLength: 255   # max name length of collection or alias
>   maxFieldNum: "256"     # max field number of a collection
>   maxDimension: 32768  # Maximum dimension of vector
>   maxShardNum: "256"  # Maximum number of shards in a collection
>   maxTaskNum: "1024"  # max task number of proxy task queue
> 
> queryCoord:
>   address: milvus-dev-querycoord
>   port: 19531
>   autoHandoff: true
>   autoBalance: true
>   overloadedMemoryThresholdPercentage: 90
>   balanceIntervalSeconds: 60
>   memoryUsageMaxDifferencePercentage: 30
> 
>   grpc:
>     serverMaxRecvSize: 2147483647  # math.MaxInt32
>     serverMaxSendSize: 2147483647  # math.MaxInt32
>     clientMaxRecvSize: 104857600   # 100 MB, 100 * 1024 * 1024
>     clientMaxSendSize: 104857600   # 100 MB, 100 * 1024 * 1024
> 
> queryNode:
>   gracefulTime: 0  # ms
>   port: 21123
> 
>   grpc:
>     serverMaxRecvSize: 2147483647  # math.MaxInt32
>     serverMaxSendSize: 2147483647  # math.MaxInt32
>     clientMaxRecvSize: 104857600   # 100 MB, 100 * 1024 * 1024
>     clientMaxSendSize: 104857600   # 100 MB, 100 * 1024 * 1024
> 
>   stats:
>     publishInterval: 1000  # Interval for querynode to report node information (milliseconds)
>   dataSync:
>     flowGraph:
>       maxQueueLength: 1024  # Maximum length of task queue in flowgraph
>       maxParallelism: 1024  # Maximum number of tasks executed in parallel in the flowgraph
>   msgStream:
>     search:
>       recvBufSize: 512    # msgPack channel buffer size
>       pulsarBufSize: 512  # pulsar channel buffer size
>     searchResult:
>       recvBufSize: 64  # msgPack channel buffer size
>   segcore:
>     chunkRows: 32768  # The number of vectors in a chunk.
> 
> indexCoord:
>   address: milvus-dev-indexcoord
>   port: 31000
> 
>   grpc:
>     serverMaxRecvSize: 2147483647  # math.MaxInt32
>     serverMaxSendSize: 2147483647  # math.MaxInt32
>     clientMaxRecvSize: 104857600   # 100 MB, 100 * 1024 * 1024
>     clientMaxSendSize: 104857600   # 100 MB, 100 * 1024 * 1024
> 
> indexNode:
>   port: 21121
> 
>   grpc:
>     serverMaxRecvSize: 2147483647  # math.MaxInt32
>     serverMaxSendSize: 2147483647  # math.MaxInt32
>     clientMaxRecvSize: 104857600   # 100 MB, 100 * 1024 * 1024
>     clientMaxSendSize: 104857600   # 100 MB, 100 * 1024 * 1024
> 
> dataCoord:
>   address: milvus-dev-datacoord
>   port: 13333
> 
>   grpc:
>     serverMaxRecvSize: 2147483647  # math.MaxInt32
>     serverMaxSendSize: 2147483647  # math.MaxInt32
>     clientMaxRecvSize: 104857600   # 100 MB, 100 * 1024 * 1024
>     clientMaxSendSize: 104857600   # 100 MB, 100 * 1024 * 1024
>   enableCompaction: true
>   enableGarbageCollection: true
> 
>   segment:
>     maxSize: "512"  # Maximum size of a segment in MB
>     sealProportion: 0.75  # It's the minimum proportion for a segment which can be sealed
>     assignmentExpiration: 2000  # ms
> 
>   compaction:
>     enableAutoCompaction: true
> 
>   gc:
>     interval: 60 # gc interval in seconds
>     missingTolerance: 3600 # file meta missing tolerance duration in seconds, 1 day
>     dropTolerance: 3600 # file belongs to dropped entity tolerance duration in seconds, 1 day
> 
> dataNode:
>   port: 21124
> 
>   grpc:
>     serverMaxRecvSize: 2147483647  # math.MaxInt32
>     serverMaxSendSize: 2147483647  # math.MaxInt32
>     clientMaxRecvSize: 104857600   # 100 MB, 100 * 1024 * 1024
>     clientMaxSendSize: 104857600   # 100 MB, 100 * 1024 * 1024
> 
>   dataSync:
>     flowGraph:
>       maxQueueLength: 1024  # Maximum length of task queue in flowgraph
>       maxParallelism: 1024  # Maximum number of tasks executed in parallel in the flowgraph
>   flush:
>     insertBufSize: "16777216"  # Bytes, 16 MB
> 
> log:
>   level: info
>   file:
>     rootPath: ""
>     maxSize: 300
>     maxAge: 10
>     maxBackups: 20
>   format: text
> 
> msgChannel:
>   \# channel name generation rule: ${namePrefix}-${ChannelIdx}
>   chanNamePrefix:
>     cluster: by-dev
>     rootCoordTimeTick: "rootcoord-timetick"
>     rootCoordStatistics: "rootcoord-statistics"
>     rootCoordDml: "rootcoord-dml"
>     rootCoordDelta: "rootcoord-delta"
>     search: "search"
>     searchResult: "searchResult"
>     proxyTimeTick: "proxyTimeTick"
>     queryTimeTick: "queryTimeTick"
>     queryNodeStats: "query-node-stats"
>     cmd: "cmd"
>     dataCoordInsertChannel: "insert-channel-"
>     dataCoordStatistic: "datacoord-statistics-channel"
>     dataCoordTimeTick: "datacoord-timetick-channel"
>     dataCoordSegmentInfo: "segment-info-channel"
> 
>   \# sub name generation rule: ${subNamePrefix}-${NodeID}
>   subNamePrefix:
>     rootCoordSubNamePrefix: "rootCoord"
>     proxySubNamePrefix: "proxy"
>     queryNodeSubNamePrefix: "queryNode"
>     dataNodeSubNamePrefix: "dataNode"
>     dataCoordSubNamePrefix: "dataCoord"
> 
> common:
>   defaultPartitionName: "_default"  # default partition name for a collection
>   defaultIndexName: "_default_idx"  # default index name
>   retentionDuration: 432000
> 
> knowhere:
>   simdType: auto  # default to auto

**Comment by LoveEachDay** [comment]
```
[2022/03/25 01:58:40.196 +00:00] [ERROR] [service.go:166] ["DataCoord start failed"] [error="All attempts results:\nattempt https://github.com/milvus-io/milvus/issues/1:Access Denied.\nattempt > https://github.com/milvus-io/milvus/issues/2:Access Denied.\n"] [stack="github.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).start\n\t/go/src/github.com/milvus-io/milvus/internal/> distributed/datacoord/service.go:166\ngithub.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/> internal/distributed/datacoord/service.go:214\ngithub.com/milvus-io/milvus/cmd/components.(*DataCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/> components/data_coord.go:47\ngithub.com/milvus-io/milvus/cmd/roles.(MilvusRoles).runDataCoord.func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/> roles.go:243"]
```
According to the above log, seems milvus connect to external s3 failed. Could you check whether the access for external s3 is valid? You can use the `mc` tool to verify following the instructions [here](https://docs.min.io/docs/minio-client-complete-guide.html).

**Comment by lijonnas** [comment]
thanks for your response, I've updated the config, but I got a new error:
> Version:   v2.0.1
> Built:     Wed Feb 23 06:23:51 UTC 2022
> GitCommit: ce9662c1
> GoVersion: go version go1.16.9 linux/amd64
> 
> open pid file: /run/milvus/datacoord.pid
> lock pid file: /run/milvus/datacoord.pid
> [2022/03/25 13:23:10.734 +00:00] [DEBUG] [base_table.go:65] ["config directory"] [configDir=/milvus/configs/]
> [2022/03/25 13:23:10.736 +00:00] [DEBUG] [component_param.go:592] ["init cacheSize"] ["cacheSize (GB)"=0]
> [2022/03/25 13:23:10.736 +00:00] [DEBUG] [component_param.go:624] ["query node init gracefulTime"] [gracefulTime=0]
> [2022/03/25 13:23:10.736 +00:00] [DEBUG] [base_table.go:65] ["config directory"] [configDir=/milvus/configs/]
> [2022/03/25 13:23:10.737 +00:00] [DEBUG] [grpc_param.go:118] [initServerMaxSendSize] [role=datacoord] [grpc.serverMaxSendSize=2147483647]
> [2022/03/25 13:23:10.737 +00:00] [DEBUG] [grpc_param.go:141] [initServerMaxRecvSize] [role=datacoord] [grpc.serverMaxRecvSize=2147483647]
> [2022/03/25 13:23:10.738 +00:00] [DEBUG] [service.go:125] ["network port"] [port=13333]
> [2022/03/25 13:23:10.840 +00:00] [DEBUG] [session_util.go:86] ["Session try to connect to etcd"]
> [2022/03/25 13:23:10.845 +00:00] [DEBUG] [session_util.go:101] ["Session connect to etcd success"]
> [2022/03/25 13:23:10.860 +00:00] [DEBUG] [session_util.go:175] ["Session get serverID success"] [key=id] [ServerId=841]
> [2022/03/25 13:23:10.860 +00:00] [INFO] [base_table.go:440] ["Set log file to "] [path=]
> [2022/03/25 13:23:10.860 +00:00] [DEBUG] [service.go:212] ["DataCoord init done ..."]
> [2022/03/25 13:23:10.860 +00:00] [DEBUG] [session_util.go:86] ["Session try to connect to etcd"]
> [2022/03/25 13:23:10.864 +00:00] [DEBUG] [session_util.go:101] ["Session connect to etcd success"]
> [2022/03/25 13:23:10.864 +00:00] [DEBUG] [base_table.go:65] ["config directory"] [configDir=/milvus/configs/]
> [2022/03/25 13:23:10.866 +00:00] [DEBUG] [grpc_param.go:186] [initClientMaxSendSize] [role=rootcoord] [grpc.clientMaxSendSize=104857600]
> [2022/03/25 13:23:10.866 +00:00] [DEBUG] [grpc_param.go:209] [initClientMaxRecvSize] [role=rootcoord] [grpc.clientMaxRecvSize=104857600]
> [2022/03/25 13:23:10.877 +00:00] [DEBUG] [server.go:396] ["DataCoord success to get DataNode sessions"] [sessions={}]
> [2022/03/25 13:23:10.877 +00:00] [DEBUG] [channel_manager.go:128] ["cluster start up"] [nodes="[]"] [oNodes="[]"] ["new onlines"="[]"] [offLines="[]"]
> [2022/03/25 13:23:10.878 +00:00] [ERROR] [service.go:166] ["DataCoord start failed"] [error="**address https://test.cos.ap-shanghai.myqcloud.com:80: too many colons in address**"] [stack="github.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).start\n\t/go/src/github.com/milvus-io/milvus/> internal/distributed/datacoord/service.go:166\ngithub.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).Run\n\t/go/src/github.com/milvus-io/> milvus/internal/distributed/datacoord/service.go:214\ngithub.com/milvus-io/milvus/cmd/components.(*DataCoord).Run\n\t/go/src/github.com/milvus-io/milvus/> cmd/components/data_coord.go:47\ngithub.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runDataCoord.func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/> roles.go:243"]

here is the external s3 config:
> minio:
> address: test.cos.ap-shanghai.myqcloud.com
> port: 80
> accessKeyID: testaccessKeyID
> secretAccessKey: testsecretAccessKey
> useSSL: false
> bucketName: test
> rootPath: milvus-dev/

Is there any misconf in my config, how should I correct it?
Thanks in advanced!

**Comment by lijonnas** [comment]
Thanks for your response, I've updated the config, but I got a new error:

> Version:   v2.0.1
> Built:     Wed Feb 23 06:23:51 UTC 2022
> GitCommit: ce9662c1
> GoVersion: go version go1.16.9 linux/amd64
> 
> open pid file: /run/milvus/datacoord.pid
> lock pid file: /run/milvus/datacoord.pid
> [2022/03/25 13:40:12.342 +00:00] [DEBUG] [base_table.go:65] ["config directory"] [configDir=/milvus/configs/]
> [2022/03/25 13:40:12.344 +00:00] [DEBUG] [component_param.go:592] ["init cacheSize"] ["cacheSize (GB)"=0]
> [2022/03/25 13:40:12.344 +00:00] [DEBUG] [component_param.go:624] ["query node init gracefulTime"] [gracefulTime=0]
> [2022/03/25 13:40:12.345 +00:00] [DEBUG] [base_table.go:65] ["config directory"] [configDir=/milvus/configs/]
> [2022/03/25 13:40:12.346 +00:00] [DEBUG] [grpc_param.go:118] [initServerMaxSendSize] [role=datacoord] [grpc.serverMaxSendSize=2147483647]
> [2022/03/25 13:40:12.346 +00:00] [DEBUG] [grpc_param.go:141] [initServerMaxRecvSize] [role=datacoord] [grpc.serverMaxRecvSize=2147483647]
> [2022/03/25 13:40:12.349 +00:00] [DEBUG] [service.go:125] ["network port"] [port=13333]
> [2022/03/25 13:40:12.452 +00:00] [DEBUG] [session_util.go:86] ["Session try to connect to etcd"]
> [2022/03/25 13:40:12.457 +00:00] [DEBUG] [session_util.go:101] ["Session connect to etcd success"]
> [2022/03/25 13:40:12.471 +00:00] [DEBUG] [session_util.go:175] ["Session get serverID success"] [key=id] [ServerId=864]
> [2022/03/25 13:40:12.471 +00:00] [INFO] [base_table.go:440] ["Set log file to "] [path=]
> [2022/03/25 13:40:12.471 +00:00] [DEBUG] [service.go:212] ["DataCoord init done ..."]
> [2022/03/25 13:40:12.471 +00:00] [DEBUG] [session_util.go:86] ["Session try to connect to etcd"]
> [2022/03/25 13:40:12.475 +00:00] [DEBUG] [session_util.go:101] ["Session connect to etcd success"]
> [2022/03/25 13:40:12.475 +00:00] [DEBUG] [base_table.go:65] ["config directory"] [configDir=/milvus/configs/]
> [2022/03/25 13:40:12.477 +00:00] [DEBUG] [grpc_param.go:186] [initClientMaxSendSize] [role=rootcoord] [grpc.clientMaxSendSize=104857600]
> [2022/03/25 13:40:12.477 +00:00] [DEBUG] [grpc_param.go:209] [initClientMaxRecvSize] [role=rootcoord] [grpc.clientMaxRecvSize=104857600]
> [2022/03/25 13:40:12.488 +00:00] [DEBUG] [server.go:396] ["DataCoord success to get DataNode sessions"] [sessions={}]
> [2022/03/25 13:40:12.488 +00:00] [DEBUG] [channel_manager.go:128] ["cluster start up"] [nodes="[]"] [oNodes="[]"] ["new onlines"="[]"] [offLines="[]"]
> [2022/03/25 13:40:13.242 +00:00] [ERROR] [service.go:166] ["DataCoord start failed"] [error="**All attempts results:\nattempt #1:The specified key does not exist.\nattempt #2:The specified key does not exist.**\n"] [stack="github.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).start\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:166\ngithub.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:214\ngithub.com/milvus-io/milvus/cmd/components.(*DataCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/data_coord.go:47\ngithub.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runDataCoord.func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:243"]

here is the external s3 config:
> minio:
> address: test.cos.ap-shanghai.myqcloud.com
> port: 80
> accessKeyID: testaccessKeyID
> secretAccessKey: testsecretAccessKey
> useSSL: false
> bucketName: test
> rootPath: milvus-dev

and the rootPath "milvus-dev" has already been created under the bucket
what I missed in my config, how should I correct it?
Thanks in advanced!

**Comment by lijonnas** [comment]
I'v fixed this issue, the address should be "cos.ap-shanghai.myqcloud.com" without the bucket name

**Comment by yanliang567** [comment]
close the issue as it was fixed
