### ISSUE TITLE
[Bug]: [Code Checker] failed on MinGW because of knowhere

### ISSUE THREAD

**Issue by jennyli-z** [milvus-io/milvus#16205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://github.com/milvus-io/milvus/runs/5703704852?check_suite_focus=true
build failed at m
```bash
In file included from D:/a/milvus/milvus/internal/core/src/segcore/SegmentGrowing.h:17,
                 from D:/a/milvus/milvus/internal/core/src/query/generated/ExecPlanNodeVisitor.h:17,
                 from D:/a/milvus/milvus/internal/core/src/query/visitors/ExecPlanNodeVisitor.cpp:16:
D:/a/milvus/milvus/internal/core/src/common/LoadInfo.h:27:5: error: 'knowhere' does not name a type
   27 |     knowhere::VecIndexPtr index;
      |     ^~~~~~~~
make[3]: *** [src/query/CMakeFiles/milvus_query.dir/build.make:146: src/query/CMakeFiles/milvus_query.dir/visitors/ExecPlanNodeVisitor.cpp.obj] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from D:/a/milvus/milvus/internal/core/src/segcore/SegmentGrowing.h:17,
                 from D:/a/milvus/milvus/internal/core/src/segcore/SegmentGrowingImpl.h:30,
                 from D:/a/milvus/milvus/internal/core/src/query/generated/ExecExprVisitor.h:19,
                 from D:/a/milvus/milvus/internal/core/src/query/visitors/ExecExprVisitor.cpp:19:
D:/a/milvus/milvus/internal/core/src/common/LoadInfo.h:27:5: error: 'knowhere' does not name a type
   27 |     knowhere::VecIndexPtr index;
      |     ^~~~~~~~
make[3]: *** [src/query/CMakeFiles/milvus_query.dir/build.make:160: src/query/CMakeFiles/milvus_query.dir/visitors/ExecExprVisitor.cpp.obj] Error 1
make[3]: Leaving directory '/d/a/milvus/milvus/cmake_build'
make[2]: *** [CMakeFiles/Makefile2:1831: src/query/CMakeFiles/milvus_query.dir/all] Error 2
make[2]: Leaving directory '/d/a/milvus/milvus/cmake_build'
make[1]: *** [Makefile:166: all] Error 2
make[1]: Leaving directory '/d/a/milvus/milvus/cmake_build'
mingw32-make: *** [Makefile:139: build-cpp] Error 1
```

### Expected Behavior

should not fail

**Comment by jennyli-z** [comment]
@matrixji could you please help on this issue as you are familiar with windows?

**Comment by matrixji** [comment]
> @matrixji could you please help on this issue as you are familiar with windows?

Sure. I've noticed this PR for upgrading knowhere may break MinGW's CI, I have rebased the PR for [supporting knowhere under windows](https://github.com/milvus-io/knowhere/pull/68) days before, guys in charge of knowhere could check if this PR acceptable.

**Comment by Eric-yuye** [comment]
build-cpp: pre-proc
	@echo "Building Milvus cpp library ..."
	@(env bash $(PWD)/scripts/core_build.sh -t ${mode} -f "$(CUSTOM_THIRDPARTY_PATH)")
	@(env bash $(PWD)/scripts/cwrapper_build.sh -t ${mode} -f "$(CUSTOM_THIRDPARTY_PATH)")
	@(env bash $(PWD)/scripts/cwrapper_rocksdb_build.sh -t ${mode} -f "$(CUSTOM_THIRDPARTY_PATH)")

build-cpp-embd: pre-proc
	@echo "Building **Embedded** Milvus cpp library ..."
	@(env bash $(PWD)/scripts/core_build.sh -b -t ${mode} -f "$(CUSTOM_THIRDPARTY_PATH)")
	@(env bash $(PWD)/scripts/cwrapper_build.sh -b -t ${mode} -f "$(CUSTOM_THIRDPARTY_PATH)")
	@(env bash $(PWD)/scripts/cwrapper_rocksdb_build.sh -b -t ${mode} -f "$(CUSTOM_THIRDPARTY_PATH)")

build-cpp-with-unittest: pre-proc
	@echo "Building Milvus cpp library with unittest ..."
	@(env bash $(PWD)/scripts/core_build.sh -t ${mode} -u -f "$(CUSTOM_THIRDPARTY_PATH)")
	@(env bash $(PWD)/scripts/cwrapper_build.sh -t ${mode} -f "$(CUSTOM_THIRDPARTY_PATH)")
	@(env bash $(PWD)/scripts/cwrapper_rocksdb_build.sh -t ${mode} -f "$(CUSTOM_THIRDPARTY_PATH)")

build-cpp-with-coverage: pre-proc
	@echo "Building Milvus cpp library with coverage and unittest ..."
	@(env bash $(PWD)/scripts/core_build.sh -t ${mode} -u -c -f "$(CUSTOM_THIRDPARTY_PATH)")
	@(env bash $(PWD)/scripts/cwrapper_build.sh -t ${mode} -f "$(CUSTOM_THIRDPARTY_PATH)")
	@(env bash $(PWD)/scripts/cwrapper_rocksdb_build.sh -t ${mode} -f "$(CUSTOM_THIRDPARTY_PATH)")

我也遇到了这个问题，应该是Makefile这里些的有问题，其中CUSTOM_THIRDPARTY_PATH感觉是一个自定义的路径，脚本中没有赋值，不清楚

**Comment by Eric-yuye** [comment]
> 

我试过了，不是的，哈哈哈
