### ISSUE TITLE
[Bug]:  Build failed on Centos

### ISSUE THREAD

**Issue by jennyli-z** [milvus-io/milvus#16222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-publish-images/detail/master/4067/pipeline
milvus build failed on centos 
![image](https://user-images.githubusercontent.com/93511422/160353064-6f034193-49ba-4436-b7a2-eaec7609307a.png)
![image](https://user-images.githubusercontent.com/93511422/160353165-ba5a8281-1f30-417d-a1e2-55f70b2f2adf.png)
It failed since upgrade knowhere v1.1.0

### Expected Behavior

should build success on centos

**Comment by yanliang567** [comment]
seems that cydrain has fixed the issue, please check @jennyli-z 
/assign @jennyli-z 

/unassign

**Comment by jennyli-z** [comment]
https://github.com/milvus-io/milvus/pull/16247 revert already

**Comment by cydrain** [comment]
fixed, please check again @jennyli-z

**Comment by jennyli-z** [comment]
verified https://ci.milvus.io:18080/jenkins/job/milvus-publish-images/job/master/4083/

**Comment by jennyli-z** [comment]
it fixed on master branch，  but the fix break the 2.0.2 branch
https://ci.milvus.io:18080/jenkins/job/milvus-publish-images/job/2.0.2/13/

**Comment by cydrain** [comment]
@jennyli-z please check

**Comment by jennyli-z** [comment]
verified and /close
