### ISSUE TITLE
[Bug]: can not connect milvus

### ISSUE THREAD

**Issue by fffyyy415** [milvus-io/milvus#16258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.0
- Deployment mode(standalone or cluster):standalone 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

first,i start etcd
etcd log:
![image](https://user-images.githubusercontent.com/68848476/160553992-58248f1a-ba17-4316-89fd-6c25feb29776.png)
next,i  start milvus
milvus log
![image](https://user-images.githubusercontent.com/68848476/160554194-cc6a1246-77c2-4f22-b155-dbf9eb4401ce.png)
![image](https://user-images.githubusercontent.com/68848476/160554214-41d27494-2a9d-41ce-9d26-f34a27e4317b.png)
my code connect milvus
details = "upstream connect error or disconnect/reset before headers. reset reason: connection failure"

**Comment by yanliang567** [comment]
@LoveEachDay any ideas?
/assign @LoveEachDay 
/unassign

**Comment by LoveEachDay** [comment]
Seems your milvus cannot contact etcd. Could you login the milvus container or pod, and run `nc -zv etcd 2379` to check the port connectivity?

**Comment by yanliang567** [comment]
/assign @fffyyy415 
@fffyyy415 could you please retry and provide info above?

/unassign @LoveEachDay

**Comment by fffyyy415** [comment]
milvus cannot contact etcd. make a mistake on the milvus config file.
