### ISSUE TITLE
[Bug]: milvus spamming console "no index params in Index file"

### ISSUE THREAD

**Issue by OndrejIT** [milvus-io/milvus#16265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvusdb/milvus:v2.0.1 (docker)
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Docker image milvusdb/milvus:v2.0.1
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

`[DEBUG] [index_coord.go:598] ["IndexCoord GetIndexFilePaths "] [FilePaths="[{\"indexBuildID\":432126842052542466,\"index_file_paths\":[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"],\"serialized_size\":390202540}]"]`
`[DEBUG] [global_meta_broker.go:204] ["get index info from indexCoord successfully"] [buildID=432126842052542466]`
`[DEBUG] [global_meta_broker.go:236] ["get indexFilePath info from indexCoord success"] [segmentID=432113131475435521] [fieldID=103] [buildID=432126842052542466] [indexPaths="[]"]`

`[ERROR] [global_meta_broker.go:276] ["no index params in Index file, segmentID = 432113131475435521, fieldID = 103, buildID = 432126842052542466, indexPaths = [                                                                                                  ]"] [stack="github.com/milvus-io/milvus/internal/querycoord.(*globalMetaBroker).parseIndexInfo\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/global_meta_broker.go:276\ngithub.com/milvus-io/milvus/internal/querycoord.(*globalMetaBroker).getIndexInfo\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/global_meta_broker.go:312\ngithub.com/milvus-io/milvus/internal/querycoord.(*IndexChecker).checkIndexLoop\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/index_checker.go:183"]`

### Anything else?

Can anyone help me to repair my DB?

**Comment by yanliang567** [comment]
@xiaocai2333 could you please take a look at this issue?

/assign @xiaocai2333 
/unassign

**Comment by xiaocai2333** [comment]
Can it be closed? @yanliang567

**Comment by xiaofan-luan** [comment]
> Can it be closed? @yanliang567

The error message is weird, what does it mean?

**Comment by xiaocai2333** [comment]
> > Can it be closed? @yanliang567
> 
> The error message is weird, what does it mean?

![image](https://user-images.githubusercontent.com/46207236/166924475-4e6b9327-7dda-4e9a-a78b-c86fedf233ee.png)

At first I thought that the segment was compacted, which caused QueryCoord not to get the actual index file path,
After careful analysis, there may be reasons for:
1. etcd is not serviceable, load failed.
2. marshal failed (exclude, the content written to etcd is marshalled).
3. task has been reassign (exclude, with retry logic, will get the new version the second time)
4. The minio is not serviceable, save index files failed.

**Comment by xiaocai2333** [comment]
Maybe it should return the error here.

**Comment by yanliang567** [comment]
> Maybe it should return the error here (line 534).

I think that would be good if return an error with meaningful msg.

**Comment by xiaofan-luan** [comment]
> > Maybe it should return the error here (line 534).
> 
> I think that would be good if return an error with meaningful msg.

Exactly~ @xiaocai2333 maybe we should return more meaningful err and print detailed logs here

**Comment by xiaocai2333** [comment]
fixed, please retest it.
/unassign
/assign @yanliang567

**Comment by yanliang567** [comment]
@jingkl could you please help to verify the fix?
/assign @jingkl 
/unassign

**Comment by yanliang567** [comment]
@OndrejIT could you please help to verify the fix on latest master build 
/assign @OndrejIT 
/unassign @jingkl

**Comment by OndrejIT** [comment]
@yanliang567 Sorry i dropped this DB. I cant check.
