### ISSUE TITLE
[Bug]: Stats log support string break the compatibility

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#16276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I upgrade the existed Milvus cluster with the new image master-20220329-e2e34507, the datanode panic

1092 time="2022-03-29T14:40:47Z" level=info msg="[Reconnecting to broker in  102.765569ms]" consumerID=6 name=bwqwv subscription=by-dev-dataNode-95-431906376226963457 topic="pers     istent://public/default/by-dev-rootcoord-dml_2"
1093 panic: runtime error: invalid memory address or nil pointer dereference
1094 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x18b67d2]
1095
1096 goroutine 192 [running]:
1097 github.com/milvus-io/milvus/internal/storage.(*PrimaryKeyStats).UnmarshalJSON(0xc000654ff0, 0xc003638000, 0x2ce61, 0x30000, 0x7f285c3f4488, 0xc000654ff0)
1098     /go/src/github.com/milvus-io/milvus/internal/storage/stats.go:60 +0x172
1099 encoding/json.(*decodeState).object(0xc0005f56b0, 0x2ffc780, 0xc00011a250, 0x16, 0xc0005f56d8, 0xc000971b7b)
1100     /usr/local/go/src/encoding/json/decode.go:609 +0x20a3
1101 encoding/json.(*decodeState).value(0xc0005f56b0, 0x2ffc780, 0xc00011a250, 0x16, 0xc000971b98, 0xb1bdb9)
1102     /usr/local/go/src/encoding/json/decode.go:370 +0x6d
1103 encoding/json.(*decodeState).unmarshal(0xc0005f56b0, 0x2ffc780, 0xc00011a250, 0xc0005f56d8, 0x0)
1104     /usr/local/go/src/encoding/json/decode.go:180 +0x1f4
1105 encoding/json.Unmarshal(0xc003638000, 0x2ce61, 0x30000, 0x2ffc780, 0xc00011a250, 0x31101a0, 0x1)
1106     /usr/local/go/src/encoding/json/decode.go:107 +0x11a
1107 github.com/milvus-io/milvus/internal/storage.(*StatsReader).GetPrimaryKeyStats(0xc000971cd8, 0x0, 0x3, 0xc00090b248)
1108     /go/src/github.com/milvus-io/milvus/internal/storage/stats.go:212 +0x99
1109 github.com/milvus-io/milvus/internal/storage.DeserializeStats(0xc0000359a0, 0x3, 0x4, 0x2, 0x3, 0xc0000359a0, 0x2, 0x4)
1110     /go/src/github.com/milvus-io/milvus/internal/storage/stats.go:229 +0xe6
1111 github.com/milvus-io/milvus/internal/datanode.(*SegmentReplica).initPKBloomFilter(0xc0001a4720, 0xc000657000, 0xc00004f900, 0x3, 0x4, 0x5ff5808bdc80001, 0x0, 0x33e903c)
1112     /go/src/github.com/milvus-io/milvus/internal/datanode/segment_replica.go:470 +0x4cd
1113 github.com/milvus-io/milvus/internal/datanode.(*SegmentReplica).addNormalSegment(0xc0001a4720, 0x5ff09e6647f0d41, 0x5fe745f844c0001, 0x5fe745f844c0002, 0xc000afc0c0, 0x2b, 0     x249f0, 0xc00004f900, 0x3, 0x4, ...)
1114     /go/src/github.com/milvus-io/milvus/internal/datanode/segment_replica.go:373 +0x6e5
1115 github.com/milvus-io/milvus/internal/datanode.(*dataSyncService).initNodes(0xc0009080c0, 0xc0005c7710, 0x368de90, 0xc000436340)
1116     /go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:173 +0x9a5
1117 github.com/milvus-io/milvus/internal/datanode.newDataSyncService(0x368de90, 0xc000639f80, 0xc000a39000, 0x36b2758, 0xc0001a4720, 0x3681210, 0xc000116b80, 0x368e718, 0xc00050     1580, 0xc0005c7710, ...)
1118     /go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:90 +0x228
1119 github.com/milvus-io/milvus/internal/datanode.(*flowgraphManager).addAndStart(0xc000520660, 0xc000656300, 0xc0005c7710, 0x2, 0x2)
1120     /go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_manager.go:58 +0x7dd
1121 github.com/milvus-io/milvus/internal/datanode.(*DataNode).handlePutEvent(0xc000656300, 0xc000679c80, 0x1, 0x0, 0x0)
1122     /go/src/github.com/milvus-io/milvus/internal/datanode/data_node.go:370 +0x2eb
1123 github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).retryHandlePutEvent(0xc000436300, 0x1, 0xc000afc030, 0x2b, 0x1, 0xc000679c80)
1124     /go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:88 +0x118
1125 github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).Run.func1(0xc000436300)
1126     /go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:70 +0x165
1127 created by github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).Run
1128     /go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:64 +0x3f

### Expected Behavior

should keep compatibility

### Steps To Reproduce

```markdown
see #16114
```

**Comment by xiaofan-luan** [comment]
please verify for it ~ @ThreadDao

**Comment by ThreadDao** [comment]
I haven't reproduced the problem, so I think it's fixed for now
