### ISSUE TITLE
[Bug]: About the continuous increase of querynode memory.

### ISSUE THREAD

**Issue by WeiDong-Shi** [milvus-io/milvus#16281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvus-dev:master-20220316-d65cf530
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.1
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 16  Intel(R) Xeon(R) Platinum 8374C CPU @ 2.70GHz / 128 G
- GPU: 
- Others:
```

### Current Behavior

Yesterday, we found that the memory usage of the query node is abnormal. At present, we use the official one million level 128 dimension data. When the data is loaded into the memory, we continue to search and write. The memory continues to grow and does not release. At present, the total amount of data is 1112000 and the memory usage is 38.8g. At present, the writing and query operations have been stopped for nearly 16 hours, Check that memory is not recycled.

![da78fff0bf73f8bc7cff3f8854cc5db0](https://user-images.githubusercontent.com/41734340/160740211-379d23a7-35a8-475a-a423-e64615a30b34.jpg)

[milvus-querynode.log](https://github.com/milvus-io/milvus/files/8376576/milvus-querynode.log)

**Comment by yanliang567** [comment]
@WeiDong-Shi besides search and insert, did you do anything frequently? e.g. load and release collection for many times? 

/assign @WeiDong-Shi 
/unassign

**Comment by yanliang567** [comment]
One more question, which index type did you use, and what are index params?

**Comment by WeiDong-Shi** [comment]
> One more question, which index type did you use, and what are index params?

Index Type: IVF_FLAT
Index Parameters: {"metric_type": "L2", "nlist": 2000}

**Comment by WeiDong-Shi** [comment]
> besides search and insert, did you do anything frequently? e.g. load and release collection for many times?

Only query and insert, no other operations, only load once, and no multiple loading and release operations.

**Comment by yanliang567** [comment]
@czs007 could you please take a look at this issue?

/assign @czs007 
/unassign

**Comment by WeiDong-Shi** [comment]
> 

- Milvus version: milvus-dev:master-20220316-d65cf530
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.1
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 16  Intel(R) Xeon(R) Platinum 8374C CPU @ 2.70GHz / 128 G
- GPU: 
- Others:

**Comment by xiaofan-luan** [comment]
> 

I guess this probably the go garbage collector issue? The best way to handle this is setup a pod memory limit because so far go didn't support any gc configuration to control total memory usage

**Comment by yanliang567** [comment]
@WeiDong-Shi I believe the community has made some improvement on this. could you please retry on latest v2.0.2 release?
