### ISSUE TITLE
Inconsistent reduce standards for SQ8/IVFPQ

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#1628]
**Describe the bug**
Inconsistent reduce standards for SQ8/IVFPQ

**Steps/Code to reproduce behavior**
1 .create a table, index_file_size= 1024MB
2. create index type = SQ8(IVFPQ)
3. insert 1.5GB data
4. search a vector

The top1 result may be incorrect.
Because there are two files, one is index file(1GB), the other is raw file(0.5GB), index file is SQ8 search, raw file is brutal-force search. SQ8 index compress vector data so the distance standards is not consistent with brutal-force search.

**Expected behavior**
Optional: 
1. Give a warnning
2. ...

**Comment by JinHai-CN** [comment]
- Use the raw data to calculation again.
- Build index for all data after FLUSH operation.
- Give a warning.

**Comment by shengjun1985** [comment]
I don't think it is a bug.
PQ and SQ8 will cause a decrease in accuracy, but the distance standards is not changed.
The incorrect top1 is just caused by PQ and SQ8.
