### ISSUE TITLE
[Bug]: Fail connecting to milvus server

### ISSUE THREAD

**Issue by dixingxing0** [milvus-io/milvus#16290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.0.1
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.0.1
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 20core/128GB
- GPU: 
- Others:
```

### Current Behavior

When i try to connect milvus, i get this error :
```
=== start connecting to Milvus     ===

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.9/site-packages/pymilvus/client/grpc_handler.py", line 92, in _wait_for_channel_ready
    grpc.channel_ready_future(self._channel).result(timeout=3)
  File "/root/anaconda3/lib/python3.9/site-packages/grpc/_utilities.py", line 140, in result
    self._block(timeout)
  File "/root/anaconda3/lib/python3.9/site-packages/grpc/_utilities.py", line 86, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/milvus/hello_milvus2.py", line 32, in <module>
    connections.connect(host='milvus.yz.test2.autohome.com.cn', port='80',secure=False)
  File "/root/anaconda3/lib/python3.9/site-packages/pymilvus/orm/connections.py", line 156, in connect
    conn = connect_milvus(**kwargs)
  File "/root/anaconda3/lib/python3.9/site-packages/pymilvus/orm/connections.py", line 144, in connect_milvus
    gh._wait_for_channel_ready()
  File "/root/anaconda3/lib/python3.9/site-packages/pymilvus/client/grpc_handler.py", line 95, in _wait_for_channel_ready
    raise BaseException(Status.CONNECT_FAILED, f'Fail connecting to server on {self._uri}. Timeout')
pymilvus.client.exceptions.BaseException: <BaseException: (code=2, message=Fail connecting to server on milvus.yz.test2.autohome.com.cn:80. Timeout)>
```

### Expected Behavior

Connect success without error.

### Steps To Reproduce

```markdown
connections.connect(host='milvus.yz.test2.autohome.com.cn', port='80',secure=False)
```

**Comment by yanliang567** [comment]
@dixingxing0 how did you deploy the milvus? It is said that you are trying to connect via port 80, could you please share the configurations if there are any customized items?

/assign @dixingxing0 
/unassign

**Comment by dixingxing0** [comment]
I think this issue should be closed, the port 80 is nginx port, we use nginx to proxy the milvus port as http port (which is not http port).

**Comment by Perfeee** [comment]
how to solve this?

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/13135597/169827478-a39419f7-c1c0-4330-bfde-08c871bce759.png">

**Comment by Limore0129** [comment]
> 

have you solved it?

**Comment by yanliang567** [comment]
did you forward the ip to localhost?

> > 
> 
> have you solved it?

**Comment by Limore0129** [comment]
> did you forward the ip to localhost?
> 
> > > 
> > 
> > 
> > have you solved it?

how to config it?

**Comment by Limore0129** [comment]
> > did you forward the ip to localhost?
> > > > 
> > > 
> > > 
> > > have you solved it?
> 
> how to config it?

<img width="882" alt="image" src="https://user-images.githubusercontent.com/49864776/209911381-24e0685f-6b4c-42ee-bb02-24ca9db8ab34.png">
this is my config.

**Comment by yanliang567** [comment]
try this:
`kubectl port-forward service/milvus-standalone 19530`

**Comment by Limore0129** [comment]
> try this: `kubectl port-forward service/milvus-standalone 19530`

<img width="702" alt="image" src="https://user-images.githubusercontent.com/49864776/209934088-65625669-a9fa-4f37-aafd-04032496003b.png">
it not work

**Comment by yanliang567** [comment]
@Limore0129 Mmmm, could you please file a new issue and attach all the logs/screenshots?
