### ISSUE TITLE
[Bug]: QueryCoord unittest timeout 

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#16304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://github.com/milvus-io/milvus/runs/5752094065?check_suite_focus=true

![image](https://user-images.githubusercontent.com/51370125/160856021-c1d8f01a-0632-444d-9c2b-ae197a12dff7.png)

**Comment by sunby** [comment]
This case remove all querynode at the end of the test case and querycoord will try to loadbalance but can not find any querynode to balance. So querycoord will wait for an querynode and it blocks. I will fix it.

**Comment by XuanYang-cn** [comment]
https://github.com/milvus-io/milvus/runs/6074633253?check_suite_focus=true
