### ISSUE TITLE
[Bug]: errors occur  in proxy node when I restart cluster 

### ISSUE THREAD

**Issue by blue216** [milvus-io/milvus#16313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvusdb/milvus-dev:master-latest
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When the test computer is restarted, i then restart the cluster ,something error occur in proxy node ,
later I canot  do  loading, search..

![1667F349-4375-49c6-93F0-6B901E09F82B](https://user-images.githubusercontent.com/6317368/160971879-14059c89-bafd-4454-ade3-a6753d26fb22.png)

**Comment by yanliang567** [comment]
@blue216 did you start all the milvus pods or any other pods? and how did you restart them? Generally, Milvus service will come back to healthy, after all the pods come back to running(it might take more seconds if there are some collections need to the loaded after restart)

/assign @blue216 
/unassign

**Comment by blue216** [comment]
> @blue216 did you start all the milvus pods or any other pods? and how did you restart them? Generally, Milvus service will come back to healthy, after all the pods come back to running(it might take more seconds if there are some collections need to the loaded after restart)
> 
> /assign @blue216 /unassign

I start the cluser with 'docker-compose up -d'

**Comment by xiaofan-luan** [comment]
usually it is due to some component unable to start.
Please upload detailed logs for further investigation

**Comment by blue216** [comment]
proxy node lo
[proxy.log](https://github.com/milvus-io/milvus/files/8386407/proxy.log)
g

**Comment by yanliang567** [comment]
Hi @blue216 , could you please retry with latest 2.0.2 release? Besides proxy node log, we also need queryCoord and queryNode logs, as it seems that searching is not working for you. Thanks.
