### ISSUE TITLE
[Bug]: index.drop() lacks of checking whether the index_name is existed of not

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#16323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: latest
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.0.2.dev13 (master)
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

def drop(self, timeout=None, **kwargs):
        """
        Drop an index and its corresponding index files.
        :param timeout: An optional duration of time in seconds to allow for the RPC. When timeout
                        is set to None, client waits until server response or error occur
        :type  timeout: float
        :raises IndexNotExistException: If the specified index does not exist.
        """
        copy_kwargs = copy.deepcopy(kwargs)
        index_name = copy_kwargs.get("index_name", DefaultConfigs.IndexName)
        copy_kwargs.pop("index_name")
        conn = self._get_connection()
        if conn.describe_index(self._collection.name, index_name) is None:
            raise IndexNotExistException(0, ExceptionsMessage.IndexNotExist)
        conn.drop_index(self._collection.name, self.field_name, index_name, timeout=timeout, **copy_kwargs)

### Expected Behavior

"index_name" should be checked existed or not

**Comment by DragonDriver** [comment]
https://github.com/milvus-io/pymilvus/pull/930 will fix this.
