### ISSUE TITLE
[Bug]: Restart QueryNode,Cluster crash!

### ISSUE THREAD

**Issue by StevenSama** [milvus-io/milvus#16320]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.2 from master
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2): milvus_cli latest
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 24C32G
- GPU: 
- Others:
```

### Current Behavior

restart one of the querynodes and then found that etcd session list have delete that quernode info but when open attu found one bad record ,and the list collections crash.

![image](https://user-images.githubusercontent.com/6235700/160996200-be71f81a-3f97-4e3f-9aa1-2ae7e1140d68.png)
![image](https://user-images.githubusercontent.com/6235700/160997337-dab89f12-b1d7-4898-9f0c-6be36722c173.png)

 `etcdctl get --prefix by-dev/meta/session`
![fdfb7821e830563f9001682515e4fd7](https://user-images.githubusercontent.com/6235700/160996500-b9d0de35-4d53-4dff-b619-951d5cc4fecb.png)
![8174917c13d32c2b7c5f09cb937cc36](https://user-images.githubusercontent.com/6235700/160996553-37091a5f-fc3f-4d37-bfde-61d447dcf470.png)

### Expected Behavior

queryNode remove correctly and cluster will be health

### Steps To Reproduce

```markdown
restart one of the querynode
```

**Comment by yanliang567** [comment]
looks like a milvus cli issue, @xiaofan-luan could you please find someone help on this issue?

/assign @xiaofan-luan 
/unassign

**Comment by StevenSama** [comment]
I dont think so, collection cant load or release or query

**Comment by xiaofan-luan** [comment]
@StevenSama please offer steven 

> �[36mINFO�[0m[11025] Closing consumer=24 �[36mconsumerID�[0m=24 �[36mname�[0m=coecb �[36msubscription�[0m=by-dev-queryNode-432060343714578433-38 �[36mtopic�[0m="persistent://public/default/by-dev-rootcoord-delta_11" �[33mWARN�[0m[11025] [Failed to close consumer] �[33mconsumerID�[0m=24 �[33merror�[0m="server error: MetadataError: Consumer not found" �[33mname�[0m=coecb �[33msubscription�[0m=by-dev-queryNode-432060343714578433-38 �[33mtopic�[0m="persistent://public/default/by-dev-rootcoord-delta_11" �[36mINFO�[0m[11025] The consumer[25] successfully unsubscribed �[36mconsumerID�[0m=25 �[36mname�[0m=trnnk �[36msubscription�[0m=by-dev-queryNode-432060343714578433-38 �[36mtopic�[0m="persistent://public/default/by-dev-search-0" �[36mINFO�[0m[11025] Closing consumer=25 �[36mconsumerID�[0m=25 �[36mname�[0m=trnnk �[36msubscription�[0m=by-dev-queryNode-432060343714578433-38 �[36mtopic�[0m="persistent://public/default/by-dev-search-0" �[33mWARN�[0m[11025] [Failed to close consumer] �[33mconsumerID�[0m=25 �[33merror�[0m="server error: MetadataError: Consumer not found" �[33mname�[0m=trnnk �[33msubscription�[0m=by-dev-queryNode-432060343714578433-38 �[33mtopic�[0m="persistent://public/default/by-dev-search-0"

thought that might be the reason of pulsar backlog full~ can you grep any error related to pulsar back log?
if so you can use https://pulsar.apache.org/docs/en/pulsar-admin/ to cleanup backlog and it should be recovered

**Comment by StevenSama** [comment]
> @StevenSama please offer steven
> 
> > �[36mINFO�[0m[11025] Closing consumer=24 �[36mconsumerID�[0m=24 �[36mname�[0m=coecb �[36msubscription�[0m=by-dev-queryNode-432060343714578433-38 �[36mtopic�[0m="persistent://public/default/by-dev-rootcoord-delta_11" �[33mWARN�[0m[11025] [Failed to close consumer] �[33mconsumerID�[0m=24 �[33merror�[0m="server error: MetadataError: Consumer not found" �[33mname�[0m=coecb �[33msubscription�[0m=by-dev-queryNode-432060343714578433-38 �[33mtopic�[0m="persistent://public/default/by-dev-rootcoord-delta_11" �[36mINFO�[0m[11025] The consumer[25] successfully unsubscribed �[36mconsumerID�[0m=25 �[36mname�[0m=trnnk �[36msubscription�[0m=by-dev-queryNode-432060343714578433-38 �[36mtopic�[0m="persistent://public/default/by-dev-search-0" �[36mINFO�[0m[11025] Closing consumer=25 �[36mconsumerID�[0m=25 �[36mname�[0m=trnnk �[36msubscription�[0m=by-dev-queryNode-432060343714578433-38 �[36mtopic�[0m="persistent://public/default/by-dev-search-0" �[33mWARN�[0m[11025] [Failed to close consumer] �[33mconsumerID�[0m=25 �[33merror�[0m="server error: MetadataError: Consumer not found" �[33mname�[0m=trnnk �[33msubscription�[0m=by-dev-queryNode-432060343714578433-38 �[33mtopic�[0m="persistent://public/default/by-dev-search-0"
> 
> thought that might be the reason of pulsar backlog full~ can you grep any error related to pulsar back log? if so you can use https://pulsar.apache.org/docs/en/pulsar-admin/ to cleanup backlog and it should be recovered

I check it every time ,not the pulsar problem, pulsar space is enough and i set the policy to expire auto

**Comment by StevenSama** [comment]
I think the problem is the bad querynode info still in the server list ,it should be deleted
