### ISSUE TITLE
[Enhancement]: Search/query plan support string

### ISSUE THREAD

**Issue by longjiquan** [milvus-io/milvus#16330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

I want to support string in our search/query plan. Include:
- Plan can handle string value;
- Plan parser in proxy can parse string-related operation, such as `Term`, `Compare`, `Range`, `PrefixMatch` and these combinations;
- Physical plan in segcore can execute the string-related operation;

**Comment by xiaofan-luan** [comment]
could we close this issue?
