### ISSUE TITLE
[Feature]:  Hope to support arm CPU

### ISSUE THREAD

**Issue by xTerry** [milvus-io/milvus#16333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Because localization support is required during the implementation of the project, a large number of servers are arm architecture, so I hope arm can be supported in the next version. Thank you!

**Comment by xiaofan-luan** [comment]
Hi @Presburger, I know you are doing something related, assigned to you
