### ISSUE TITLE
[Bug]: Index out of range

### ISSUE THREAD

**Issue by skye95git** [milvus-io/milvus#16343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.0
- Deployment mode(standalone or cluster): standalone 
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. After I inserted a few million pieces of data into the collection at once (about 10GB), the search returned an error `Index out of range`. How many pieces of data can I insert at a time? How can I fix this error?
![image](https://user-images.githubusercontent.com/41561936/161208174-f9e583d3-fcfb-43a1-8539-3ce68e455d6b.png)

2. After I inserted data into the collection for several times, I could not find the result when searching. Is the problem caused by creating duplicate indexes during multiple inserts?

### Expected Behavior

return search results

**Comment by yanliang567** [comment]
1. generally, it is recommend not insert more than 256MB data in a single batch.  
2. if the multiple indexes have the same index params, it would be okay. 
@skye95git could you please upload the milvus log ?

/assign @skye95git 
/unassign

**Comment by skye95git** [comment]
> 

1. Does `in a single batch` means to execute `collection.insert(data)` once? If yes, 10 GB of data needs to be inserted multiple times. 
2. I use the same index parameter, but I still get duplicate index errors after executing `collection.insert(data)` twice. 
```
# connect to the service
connections.connect(host='localhost', port='19530')

# create Collection
TABLE_NAME = search
function_id = FieldSchema(name="id", dtype=DataType.INT64, is_primary=True, auto_id=True)
function = FieldSchema(name="function", dtype=DataType.FLOAT_VECTOR, dim=768)
schema = CollectionSchema(fields=[function_id, function], description="search")
collection = Collection(name=TABLE_NAME, schema=schema)

# create index
index_param = {
        "metric_type":"IP",
        "index_type":"IVF_FLAT",
        "params":{"nlist":1024}
    }
collection.create_index(field_name="function", index_params=index_param)

for root, dirs, files in os.walk(args.base_file):
        for file in files:
            temp=os.path.join(root,file)
            # calculate vec
            embeddings = np.concatenate(vecs,0)
            embeddings = normalize(embeddings)

            em = list(code_embeddings)
            mr = collection.insert([em])
```
I only set the index parameter once and then insert it multiple times. Or do I need to set the index parameter for each insert?

**Comment by skye95git** [comment]
> 1. generally, it is recommend not insert more than 256MB data in a single batch.
> 2. if the multiple indexes have the same index params, it would be okay.
>    @skye95git could you please upload the milvus log ?
> 
> /assign @skye95git /unassign

1. Does `in a single batch` means to execute `collection.insert(data)` once? If yes, 10 GB of data needs to be inserted multiple times. 
2. I use the same index parameter, but I still get duplicate index errors after executing `collection.insert(data)` twice. 
```
# connect to the service
connections.connect(host='localhost', port='19530')

# create Collection
TABLE_NAME = search
function_id = FieldSchema(name="id", dtype=DataType.INT64, is_primary=True, auto_id=True)
function = FieldSchema(name="function", dtype=DataType.FLOAT_VECTOR, dim=768)
schema = CollectionSchema(fields=[function_id, function], description="search")
collection = Collection(name=TABLE_NAME, schema=schema)

# create index
index_param = {
        "metric_type":"IP",
        "index_type":"IVF_FLAT",
        "params":{"nlist":1024}
    }
collection.create_index(field_name="function", index_params=index_param)

for root, dirs, files in os.walk(args.base_file):
        for file in files:
            temp=os.path.join(root,file)
            # calculate vec
            embeddings = np.concatenate(vecs,0)
            embeddings = normalize(embeddings)

            em = list(code_embeddings)
            mr = collection.insert([em])
```
I only set the index parameter once and then insert it multiple times. Or do I need to set the index parameter for each insert?

**Comment by yanliang567** [comment]
1. yes, for now you shall separate the 10GB data into many batches.  BTW, Milvus 2.1 is going to introduce a new feature that would import the data file into milvus directly. I believe this would be a great help to you.
2. No, you just need to set and build the index for one time.

@skye95git  Could you please retry with small batches when inserting?

**Comment by skye95git** [comment]
> 1. yes, for now you shall separate the 10GB data into many batches.  BTW, Milvus 2.1 is going to introduce a new feature that would import the data file into milvus directly. I believe this would be a great help to you.
> 2. No, you just need to set and build the index for one time.
> 
> @skye95git Could you please retry with small batches when inserting?

Thanks, I have retry with small batches when inserting. It works.

**Comment by yanliang567** [comment]
great to hear that. I will close this issue then.

**Comment by skye95git** [comment]
> great to hear that. I will close this issue then.

Hi，When I insert a number of batches, the process breaks down:
```
04/02/2022 16:41:15 - INFO - __main__ -   ***** calculate code vec *****
04/02/2022 16:42:32 - ERROR - pymilvus.client.grpc_handler -   Error: <BaseException: (code=1, message=getSegmentID fail
ed: SegmentIDAllocator failRemainRequest unexpected error)>
Traceback (most recent call last):
  File "get_python_embedding_continue.py", line 270, in <module>
    mr = collection.insert([em])
  File "/home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 545, in ins
ert
    partition_name=partition_name, timeout=timeout, **kwargs)
  File "/home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/pymilvus/client/stub.py", line 58, in handler
    raise e
  File "/home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/pymilvus/client/stub.py", line 42, in handler
    return func(self, *args, **kwargs)
  File "/home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/pymilvus/client/stub.py", line 911, in insert
    return handler.bulk_insert(collection_name, entities, partition_name, timeout, **kwargs)
  File "/home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 77, in
 handler
    raise e
  File "/home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 69, in
 handler
    return func(self, *args, **kwargs)
  File "/home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 523, i
n bulk_insert
    raise err
  File "/home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 519, i
n bulk_insert
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=getSegmentID failed: SegmentIDAllocator failR
emainRequest unexpected error)>
```

**Comment by skye95git** [comment]
@yanliang567    I have another questions:     

1. In the https://github.com/milvus-io/bootcamp/blob/master/solutions/text_search_engine/text_search_engine.ipynb, the results of the desired search are stored in `PostgreSQL`:
```
def copy_data_to_pg(table_name, fname, conn, cur):
    fname = os.path.join(os.getcwd(),fname)
    try:
        sql = "COPY " + table_name + " FROM STDIN DELIMITER '|' CSV HEADER"
        cursor.copy_expert(sql, open(fname, "r"))
        conn.commit()
        print("Inserted into Postgress Sucessfully!")
    except Exception as e:
        print("Copy Data into Postgress failed: ", e)

...

results = collection.search(query_embeddings, field_name, param=search_params, limit=9, expr=None)

for result in results[0]:
    sql = "select title from " + TABLE_NAME + " where ids = " + str(result.id) + ";"
    cursor.execute(sql)
    rows=cursor.fetchall()
    if len(rows):
        similar_titles.append((rows[0][0], result.distance))
        print((rows[0][0], result.distance))
```
 
In the https://raw.githubusercontent.com/milvus-io/pymilvus/v2.0.1/examples/hello_milvus.py, the results of the desired search are stored in the `collection`:
```
...
fields = [
    FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, auto_id=False),
    FieldSchema(name="random", dtype=DataType.DOUBLE),
    FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=8)
]

schema = CollectionSchema(fields, "hello_milvus is the simplest demo to introduce the APIs")

hello_milvus = Collection("hello_milvus", schema, consistency_level="Strong")

...

hello_milvus.search(vectors_to_search, "embeddings", search_params, limit=3, expr="random > -12", output_fields=["random"])
end_time = time.time()

for hits in result:
    for hit in hits:
        print(f"hit: {hit}, random field: {hit.entity.get('random')}")
print(search_latency_fmt.format(end_time - start_time))
```
In the case of `text search`, I have several million pieces of `text`, compute their vector `text_embedding`, and insert them to a collection. Can I store metadata(`text`) directly in the collection instead of in PostgreSQL, like `hello_milvus.py`? 
```
fields = [
    FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, auto_id=False),
    FieldSchema(name="text", dtype=DataType.DOUBLE),
    FieldSchema(name="text_embeddings", dtype=DataType.FLOAT_VECTOR, dim=8)
]
```

2. If yes, is this recommended?
3. If no, can I replace PostgreSQL with rocksdb? Do I need to install and configure rocksdb myself, or does Milvus have rocksdb built in
4. How do you defined vector data, scalar data, and metadata?

<img width="681" alt="7de6675e6bdc3ec7f1a3405e21b0196" src="https://user-images.githubusercontent.com/41561936/161379929-7adf9691-96df-4599-9dc8-2511e71d5b11.png">
