### ISSUE TITLE
[Bug]: Failed to load index file: DISK2CPU

### ISSUE THREAD

**Issue by WeiDong-Shi** [milvus-io/milvus#16366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 1.1.1
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 1.1.2
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 16  Intel(R) Xeon(R) Platinum 8374C CPU @ 2.70GHz / 128 G
- GPU: 
- Others:
```

### Current Behavior

I created three containers, Milvus RO, Milvus RW and mishards. Data written through mishards can be written normally, but the query will report an error status (code = 1, message ='failed to load index file: disk2cpu: failed to load deleted docs from / var / lib / Milvus / db / tables / test_1 / 1648889214861886000 / 1648889214861886000 '), I can query the data through the read-write node, but I can't query the data through the read-only node or mishards node

**Comment by yanliang567** [comment]
@yhmo could you please help on this issue>

/assign @yhmo 
/unassign

**Comment by WeiDong-Shi** [comment]
This is my configuration. Please help me check if there are any errors.

[config.zip](https://github.com/milvus-io/milvus/files/8402301/config.zip)

**Comment by WeiDong-Shi** [comment]
This is my configuration file, which contains the startup script. You can use it to quickly reproduce my situation. At the same time, you have to help to see if there is a problem with my configuration.

[config.zip](https://github.com/milvus-io/milvus/files/8402331/config.zip)

**Comment by WeiDong-Shi** [comment]
I found the reason for this problem. It's my configuration problem. I didn't look at our architecture diagram by myself.

**Comment by xTerry** [comment]
@WeiDong-Shi How to solve it? What configuration has been modified? I have encountered the same problem
