### ISSUE TITLE
Remove cache_insert_data suggestion

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#1636]
## Report incorrect documentation

**Location of incorrect documentation**
https://github.com/milvus-io/docs/blob/master/site/zh-CN/faq/product_faq.md#Milvus-是否支持-边插入边查询-
https://github.com/milvus-io/docs/blob/master/site/en/faq/product_faq.md#Does-Milvus-support-simultaneous-inserting-and-searching

**Suggested fix for documentation**
Remove the suggestion to set cache_insert_data to true.
Only keep one word: "Support"

**Comment by yamasite** [comment]
Fixed. 

https://github.com/milvus-io/docs/blob/master/site/zh-CN/faq/product_faq.md#Milvus-是否支持-边插入边查询-
https://github.com/milvus-io/docs/blob/master/site/en/faq/product_faq.md#Does-Milvus-support-simultaneous-inserting-and-searching
