### ISSUE TITLE
[Bug]: Search comes back with empty result when trying to match a existing entity in collection

### ISSUE THREAD

**Issue by saiswagath** [milvus-io/milvus#16384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvusdb/daily-build:master-20220330-40fab914 (Test version after milvus 2.0.1 official release)
- Deployment mode(standalone or cluster):standalone 
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus:2.0.
- OS(Ubuntu or CentOS): Debian 10
- CPU/Memory:  
                                   total        used        free      shared  buff/cache   available
                      Mem:           62Gi        14Gi        24Gi       8.1Gi        23Gi        39Gi
                      Swap:          31Gi          0B        31Gi
- GPU: N/A
- Others: N/A
```

### Current Behavior

I created a collection that has 33000 entities. Once the entities are successfully inserted, I tried to perform a search by picking one of the existing entities in the collection, but the search comes back with empty result.

Below is my code:

`embed = model.encode(question)
embed = embed.reshape(1,-1)
embed = normalize(embed)
query_embeddings = embed.tolist()
collection = Collection(TABLE_NAME)
collection.load()
search_params = {"metric_type": 'IP', "params": {"nprobe": 16}}
results = collection.search(query_embeddings, anns_field="embedding", param=search_params, limit=6)
ids = [str(x.id) for x in results[0]]`

After googling a bit we figured out we need to flush before load and them perform search. Suprsingly this seems to work fine. Below is the code with flush:

`embed = model.encode(question)
embed = embed.reshape(1,-1)
embed = normalize(embed)
query_embeddings = embed.tolist()
collection = Collection(TABLE_NAME)
collection.num_entities  #num_entities does flush internally
collection.load()
search_params = {"metric_type": 'IP', "params": {"nprobe": 16}}
results = collection.search(query_embeddings, anns_field="embedding", param=search_params, limit=6)
ids = [str(x.id) for x in results[0]]`

Should we explicitly perform flush before search? Also, this works fine for 100 entities, we noticed this problem only for 33000 entities.

### Steps To Reproduce

```markdown
1) In Milvus using docker-compose create a collection that has 33000 entities
2) Try to search with one of the existing entities, It should return exact match as we are searching with an existing entity
```

**Comment by yanliang567** [comment]
sounds like a bug. 
@binbinlv could you please verify whether it reproduce on master lastest?
/assign @binbinlv 
/unassign

**Comment by xiaofan-luan** [comment]
if that's a bug, then it might be related to growing segment query

**Comment by binbinlv** [comment]
> sounds like a bug. @binbinlv could you please verify whether it reproduce on master lastest? /assign @binbinlv /unassign

OK, verifying.

**Comment by binbinlv** [comment]
Could not reproduce in either master-20220330-40fab914 and latest master build,
@saiswagath 
could you please try 2.0.2 build or latest master build, and see if you could reproduce this issue on your side.

And if you could reproduce it in the 2.0.2 or latest master build, please upload the log of milvus at the same time, thanks very much.


My python script trying to reproduce this issue is:
```python
from pymilvus import CollectionSchema, FieldSchema
from pymilvus import Collection
from pymilvus import connections
from pymilvus import DataType
from pymilvus import Partition
from pymilvus import utility


dim = 128
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
connections.connect(host="***", port="***")


import numpy as np
collection = Collection("test_search_collection_0", schema=schema)

nb = 33000
nq = 1
limit = 6
import random
default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]

res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
collection.load()


search_params = {"metric_type": 'IP', "params": {"nprobe": 16}}
res = collection.search(vectors[:nq], "float_vector", search_params, limit)

ids = [str(x.id) for x in res[0]]

print(ids)
print(collection.num_entities)

collection.drop()
```
