### ISSUE TITLE
[Bug] server hang while insert

### ISSUE THREAD

**Issue by 12304212** [milvus-io/milvus#16396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.2
- Deployment mode(standalone or cluster):  docker standalone
- SDK version(milvus-sdk-java v2.0.1):
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 16G
- GPU: 
- Others:
```

### Current Behavior

InsertParam insertParam = InsertParam.newBuilder()
                .withCollectionName(collectionName)
                //.withPartitionName(partitionName)
                .withFields(fields)
                .build();
一次1000条进行insert

### Expected Behavior

[ERROR] [global_meta_broker.go:229] ["empty index paths, segmentID = 432331990266281985, fieldID = 101, buildID = 432332042301865986"] [stack="github.com/milvus-io/milvus/internal/querycoord.(*globalMetaBroker).parseIndexInfo\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/global_meta_broker.go:229\ngithub.com/milvus-io/milvus/internal/querycoord.(*globalMetaBroker).getIndexInfo\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/global_meta_broker.go:312\ngithub.com/milvus-io/milvus/internal/querycoord.(*IndexChecker).checkIndexLoop\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/index_checker.go:183"]

**Comment by xiaofan-luan** [comment]
hi @12304212 ,please use issue with a meaningful title,  and also upgrade your serverside log as much as possible.
The log error seems to have nothing to do with insert hang.
What is the error message? and the proxy, datacoord, datanode log?

**Comment by yanliang567** [comment]
@12304212 please help to provide more info as suggested above

/assign @12304212 
/unassign

**Comment by 12304212** [comment]
repetitive submission
