### ISSUE TITLE
[Feature]: Support higher topk value for search()

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#16391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Milvus 2.0 has a topk limit of 16,384. Some users have a particular use case that requires higher topk limits.
It would be great if it can be configurated to a higher value in some way.

https://app.slack.com/client/TM98LD8DQ/threads?cdn_fallback=2

### Describe the solution you'd like.

Add a configuration item in the milvus.yaml to set topk limit.

**Comment by xiaofan-luan** [comment]
No we don't want to support high TopK, instead we want to support range search instead

**Comment by nitinrohan19** [comment]
Hi @yhmo @xiaofan-luan can we just make it configurable so that we have the option to extend it whenever needed?

**Comment by xiaofan-luan** [comment]
won't support it.
Instead we will follow ES to do the pagination
see #16994
