### ISSUE TITLE
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=getSegmentID failed: SegmentIDAllocator failR emainRequest unexpected error)[Bug]: 

### ISSUE THREAD

**Issue by skye95git** [milvus-io/milvus#16392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.0
- Deployment mode(standalone or cluster): standalone 
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. When I insert a number of batches, the process breaks down:
```
04/02/2022 16:41:15 - INFO - __main__ -   ***** calculate code vec *****
04/02/2022 16:42:32 - ERROR - pymilvus.client.grpc_handler -   Error: <BaseException: (code=1, message=getSegmentID fail
ed: SegmentIDAllocator failRemainRequest unexpected error)>
Traceback (most recent call last):
  File "get_python_embedding_continue.py", line 270, in <module>
    mr = collection.insert([em])
  File "/home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 545, in ins
ert
    partition_name=partition_name, timeout=timeout, **kwargs)
  File "/home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/pymilvus/client/stub.py", line 58, in handler
    raise e
  File "/home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/pymilvus/client/stub.py", line 42, in handler
    return func(self, *args, **kwargs)
  File "/home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/pymilvus/client/stub.py", line 911, in insert
    return handler.bulk_insert(collection_name, entities, partition_name, timeout, **kwargs)
  File "/home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 77, in
 handler
    raise e
  File "/home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 69, in
 handler
    return func(self, *args, **kwargs)
  File "/home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 523, i
n bulk_insert
    raise err
  File "/home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 519, i
n bulk_insert
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=getSegmentID failed: SegmentIDAllocator failR
emainRequest unexpected error)>
```

2. In the https://github.com/milvus-io/bootcamp/blob/master/solutions/text_search_engine/text_search_engine.ipynb, the results of the desired search are stored in PostgreSQL:
```
def copy_data_to_pg(table_name, fname, conn, cur):
    fname = os.path.join(os.getcwd(),fname)
    try:
        sql = "COPY " + table_name + " FROM STDIN DELIMITER '|' CSV HEADER"
        cursor.copy_expert(sql, open(fname, "r"))
        conn.commit()
        print("Inserted into Postgress Sucessfully!")
    except Exception as e:
        print("Copy Data into Postgress failed: ", e)

...

results = collection.search(query_embeddings, field_name, param=search_params, limit=9, expr=None)

for result in results[0]:
    sql = "select title from " + TABLE_NAME + " where ids = " + str(result.id) + ";"
    cursor.execute(sql)
    rows=cursor.fetchall()
    if len(rows):
        similar_titles.append((rows[0][0], result.distance))
        print((rows[0][0], result.distance))
```
In the https://raw.githubusercontent.com/milvus-io/pymilvus/v2.0.1/examples/hello_milvus.py, the results of the desired search are stored in the collection:
```
...
fields = [
    FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, auto_id=False),
    FieldSchema(name="random", dtype=DataType.DOUBLE),
    FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=8)
]

schema = CollectionSchema(fields, "hello_milvus is the simplest demo to introduce the APIs")

hello_milvus = Collection("hello_milvus", schema, consistency_level="Strong")

...

hello_milvus.search(vectors_to_search, "embeddings", search_params, limit=3, expr="random > -12", output_fields=["random"])
end_time = time.time()

for hits in result:
    for hit in hits:
        print(f"hit: {hit}, random field: {hit.entity.get('random')}")
print(search_latency_fmt.format(end_time - start_time))
```
In the case of text search, I have several million pieces of text, compute their vector text_embedding, and insert them to a collection. Can I store metadata(text) directly in the collection instead of in PostgreSQL, like hello_milvus.py?
```
fields = [
    FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, auto_id=False),
    FieldSchema(name="text", dtype=DataType.DOUBLE),
    FieldSchema(name="text_embeddings", dtype=DataType.FLOAT_VECTOR, dim=8)
]
```
3. If yes, is this recommended?
4. If no, can I replace PostgreSQL with rocksdb? Do I need to install and configure rocksdb myself, or does Milvus have rocksdb built in
5. How do you defined vector data, scalar data, and metadata?
![image](https://user-images.githubusercontent.com/41561936/161884330-dad2b7dd-8af7-4e35-adb9-858b7db7d599.png)

**Comment by yanliang567** [comment]
1. sounds like you are asking about String DataType Support, which would be supported in Milvus 2.1 soon. 
2. I think you can try when string dataType supported.
3. For now, you have to link a 3-rd part database for your text, either is okay I think.
4. vector data is an embedding vector, which is defined clear in milvus.io. https://milvus.io/docs/v2.0.x/overview.md#Embedding-vectors
5. scalar data is the other data fields that stored in milvus, e.g. pk, text 
6. metadata is definition data of collection(or the fields, the vector, index, etc)

**Comment by yanliang567** [comment]
@skye95git how big is your every insert batch? it is recommended that not bigger than 256MB for each insert batch.  Could u please retry with latest release v2.0.2?

/assign @skye95git 
/unassign

**Comment by skye95git** [comment]
> 1. sounds like you are asking about String DataType Support, which would be supported in Milvus 2.1 soon.
> 2. I think you can try when string dataType supported.
> 3. For now, you have to link a 3-rd part database for your text, either is okay I think.
> 4. vector data is an embedding vector, which is defined clear in milvus.io. https://milvus.io/docs/v2.0.x/overview.md#Embedding-vectors
> 5. scalar data is the other data fields that stored in milvus, e.g. pk, text
> 6. metadata is definition data of collection(or the fields, the vector, index, etc)

Thanks  for your reply! I look forward to Milvus 2.1.

**Comment by skye95git** [comment]
> @skye95git how big is your every insert batch? it is recommended that not bigger than 256MB for each insert batch. Could u please retry with latest release v2.0.2?
> 
> /assign @skye95git /unassign

I tried again and the problem disappeared.
