### ISSUE TITLE
Remove debug log 

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#1641]
**Describe the bug**
```
信息: Created partition `tag` in collection `IP_dyGgAFwluP` successfully!
三月 13, 2020 12:13:39 上午 io.milvus.client.MilvusGrpcClient logSevere
严重: Insert vectors failed:
status {
  error_code: UNEXPECTED_ERROR
  reason: "Table IP_dyGgAFwluP\'s partition DsvyeQyHni not found"
}
vector_id_array: 1584029619784319000
vector_id_array: 1584029619784319001
vector_id_array: 1584029619784319002
vector_id_array: 1584029619784319003
vector_id_array: 1584029619784319004
vector_id_array: 1584029619784319005
vector_id_array: 1584029619784319006
vector_id_array: 1584029619784319007
vector_id_array: 1584029619784319008
vector_id_array: 1584029619784319009
vector_id_array: 1584029619784319010
vector_id_array: 1584029619784319011
vector_id_array: 1584029619784319012
```
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by youny626** [comment]
The SDK does not print the "vector_id_array: XXXXXX" message. Either the server or the testing code prints it.

**Comment by yhmo** [comment]
Not able to reproduce
