### ISSUE TITLE
[Enhancement]: The issue template needs to add Milvus log.

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#16425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

When a user reports a bug in an issue, in addition to "Environment", "Current Behavior", "Expected Behavior", and "Steps To Reproduce", a "Milvus log" needs to be added to the issue template.

![image](https://user-images.githubusercontent.com/53512883/162382819-86855bd6-7f67-4cb8-b0d8-8dff63e842d0.png)

### Why is this needed?

Milvus is a complex distributed system. Without detailed error log information, it is difficult to locate problems. Now every time a user raises an issue, members of the Milvus team need to ask the user for the log again, which is a waste of time. If the user is required to upload the log when raising an issue, the problem analysis will be very efficient.

### Anything else?

N/A

**Comment by yanliang567** [comment]
Any one please feel free to assign to yourself if you are interested in fixing this issue.
