### ISSUE TITLE
Incorrect link in milvus install document

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#1643]
## Report incorrect documentation

**Location of incorrect documentation**
https://www.milvus.io/docs/guides/get_started/install_milvus/cpu_milvus_docker.md
In the step 3 note. 

**Describe the problems or issues found in the documentation**
A clear and concise description of what you found to be incorrect.

**Steps taken to verify documentation is incorrect**
List any steps you have taken:

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.

---

## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken:

**Comment by yamasite** [comment]
Removed the extra note that links to 0.6.0 config file.

**Comment by yamasite** [comment]
https://www.milvus.io/docs/guides/get_started/install_milvus/cpu_milvus_docker.md
