### ISSUE TITLE
[Feature]: search_by_distance needs to return all data

### ISSUE THREAD

**Issue by huaihkiss** [milvus-io/milvus#16437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

We retrieve all pictures whose distance is greater than a certain threshold according to the image features, but because the parameters in the api have a limited number, we cannot get all the pictures that exceed this threshold.
Is it possible to remove this restriction or add pagination

**Comment by xiaofan-luan** [comment]
We are planning to support range search in next big release(2.2, targeting at July)
If anyone interested please take it, faiss itself already support range search

**Comment by firedent** [comment]
Hi,
I notice you likely mentioned the `search_by_distance` method. Is it a method implemented in the 2.0.2 release?

**Comment by soothing-rain** [comment]
> Hi, I notice you likely mentioned the `search_by_distance` method. Is it a method implemented in the 2.0.2 release?

Hey as mentioned above, we are targeting to release this feature in Milvus 2.2.

**Comment by xiaofan-luan** [comment]
We call this functionality as range search, @cydrain is working on the issue and would be ready on 2.2

**Comment by firedent** [comment]
That's great. 
Actually, I just wonder how the issue creator gets the term 'search_by_distance'?

> We call this functionality as range search, @cydrain is working on the issue and would be ready on 2.2

**Comment by huuson235** [comment]
I'm looking for this feature too. I hope Milvus team will implement it soon. Currently, to search by distance I get 10000 nearest vectors then use binary search to remove outliers as quick as possible.
