### ISSUE TITLE
Is it possible for Milvus to support vector IDS in the form of strings in subsequent versions

### ISSUE THREAD

**Issue by oswen** [milvus-io/milvus#1644]
In my application scenario, each of my vector IDS is represented by strings, but at present, Milvus does not support vector IDS in the form of strings, which will cause great trouble to my subsequent application of Milvus. Is it possible for Milvus to support vector IDS in the form of strings?

**Comment by JinHai-CN** [comment]
Yes, we will support string in the future.

**Comment by oswen** [comment]
> Yes, we will support string in the future.

Expect the implementation of the feature
