### ISSUE TITLE
Can Milvus implement the feature of filtering queries with multiple tags

### ISSUE THREAD

**Issue by oswen** [milvus-io/milvus#1645]
Through the tutorial I learned that Milvus use partition table for structured data storage and query, but I found that a single tag can only support a single value (for example: gender/color -> male/red, each child tag has only one value), but how to deal with the condition that 'a child tag has multiple values at the same time' ? (e.g. : gender/color -> male/(red, yellow)). I wonder if Milvus can implement "terms query" and storage features similar to Elasticsearch.

**Comment by tinkerlin** [comment]
This feature will be support in further release.
Refer to roadmap [https://github.com/milvus-io/milvus/projects](url)
