### ISSUE TITLE
[Feature]: Support SSL encrypting the traffic between proxy and client

### ISSUE THREAD

**Issue by aakejiang** [milvus-io/milvus#16459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Apply TLS/SSL encrypting the traffic between proxy and client to enhance the security.

### Describe the solution you'd like.

For traffic between proxy and client, we need adding TLS/SSL to encrypt the communication data. While for the requests between inner components like RootCoord, DataNode, IndexCoord, etc, it's not necessary to encrypt/decrypt the data for performance issue. 

The currently default port for proxy is 19530 which is used for SDK requests. We need adding a new port dedicated for inner components' requests. That is, there are two GRPC ports for proxy, one is enabled TLS/SSL for SDK requests, and another is plaintext for inner cluster communications.

**Comment by jaime0815** [comment]
related to #15656

**Comment by jennyli-z** [comment]
@xiyichan

**Comment by xiyichan** [comment]
> @xiyichan Could you help with this issue？

ok
