### ISSUE TITLE
[Bug]: Hello, when I creating a datanode and a querynode container on docker host network, it gives an error which indicates port 9091 is in use.

### ISSUE THREAD

**Issue by john-h-luo** [milvus-io/milvus#16463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.1
- Deployment mode(standalone or cluster):Cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.0.1
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: Enough
- GPU: None
- Others:
```

### Current Behavior

[2022/04/12 04:06:43.736 +00:00] [DEBUG] [base_table.go:65] ["config directory"] [configDir=/milvus/configs/]
[2022/04/12 04:06:43.737 +00:00] [ERROR] [metrics.go:653] ["handle metrics failed"] [error="listen tcp :9091: bind: address already in use"] [stack="github.com/milvus-io/milvus/internal/metrics.ServeHTTP.func1\n\t/go/src/github.com/milvus-io/milvus/internal/metrics/metrics.go:653"]

### Expected Behavior

All node and coord on same host network should be started without error message, make an environment variable to allow me allocate port for metrics rather than hardcoded to 9091.

### Steps To Reproduce

```markdown
1. Create docker host
2. Create Milvus datanode on Host network
3. Create Milvus querynode on Host network
```

**Comment by yanliang567** [comment]
@LoveEachDay could you please take a look at this issue?

/assign @LoveEachDay 
/unassign

**Comment by LoveEachDay** [comment]
Allow user to dynamically set metrics port for milvus components. 
/assign @zwd1208 
/unassign
