### ISSUE TITLE
[Bug]: Interface "loading_progress" shows "0%" after releasing collection and load one partition

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#16468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: latest
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.1.0.dev21
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Interface "loading_progress" shows "0%" after releasing collection and load one partition

### Expected Behavior

Interface "loading_progress" shows "50%" after releasing collection and load one partition

### Steps To Reproduce

```markdown
Run test case:
 testcases/test_utility.py::TestUtilityBase.test_loading_progress_with_release_partition


    def test_loading_progress_with_load_partition(self):
        """
        target: test loading progress after load partition
        method: 1.insert data into two partitions and flush
                2.load one partition and loading progress
        expected: loaded one partition entities
        """
        half = ct.default_nb
        collection_w, partition_w, _, _ = self.insert_entities_into_two_partitions_in_half(half)
        collection_w.release()
        partition_w.load()
        res = self.utility_wrap.loading_progress(collection_w.name)[0]
        assert res[loading_progress] == '50%'
```

**Comment by XuanYang-cn** [comment]
There're 2 types of loading_progress:
1. load_collection async, showing the loading progress in percentage
    - pros: useful for larger collection's loading.
    - cons: need to refactor QueryCoord, couldn't get implemented until memory_replica is done.

2. The collection loading_progress should be influenced both by load_collection and load_partitions.

```text
Collection: 1
Partition: a, b

- If load_partitions([a]), collection_loading_progress == 50%
- If load_partitions([a. b]), collection_loading_progress == 100%
- if load_partitions([a, b]), create_partition(c), collection_loading_progress == 75%
- if load_partitions([a, b]), release_partition(a), collection_loading_progress == 50%
```
- pros:
  -  `load_partition` represents part of `load_collection` 
- cons: 
    - If the collection_loading_progress == 100%, when creating a new partition, the system could do 2 things:
      1. Load the new partition if the progress represents for `load_collection`
      2. DON't load the new partition if the progress represents for the cumulation of `load_partitions`

The questions:
1. The combination of type_1 and type_2 is confusing, it seems we need to choose one out of the two types. @congqixia and I both think type_1 is better. That is make `load_partitions`, `loading_partitions_progress` separate with `load_collection`, `loading_collection_progress`.
2. I'm wondering if we could discuss about the `load-release 接口约束` is still a thing, after the replica feature finished. Cuz under the `load-release 接口约束`, `load_partition` could only be called ONCE. So under `load-release 接口约束`, naturally `load_partition` cannot represent part of `load_collection`. 

 ![image](https://user-images.githubusercontent.com/51370125/163533887-525fa6e7-4e01-44f5-b0fe-9840af5d3765.png)

**Comment by XuanYang-cn** [comment]
behavior after https://github.com/milvus-io/pymilvus/pull/966
```
create collection
Start inserting entities
create partition third
['collection_jqCtac67', 'hello_milvus', 'hello_milvus1']
create partition second
insert data to partition third, second, _default
load partition

1: second_partition.load()
1:loading_progress(coll)                        -> {'loading_progress': '33%', 'num_loaded_partitions': 1, 'not_loaded_partitions': ['_default', 'third']}
1:loading_progress(coll, ['second'])            -> {'loading_progress': '100%', 'num_loaded_partitions': 1, 'not_loaded_partitions': []}
1:loading_progress(coll, ['default'])           -> {'loading_progress': '0%', 'num_loaded_partitions': 0, 'not_loaded_partitions': ['_default']}
1:loading_progress(coll, ['second', '_default'])-> {'loading_progress': '50%', 'num_loaded_partitions': 1, 'not_loaded_partitions': ['_default']}

1: second_partition.release()

2: collection.load()
2:loading_progress(coll)                        -> {'loading_progress': '100%', 'num_loaded_partitions': 3, 'not_loaded_partitions': []}
2:loading_progress(coll, ['second'])            -> {'loading_progress': '100%', 'num_loaded_partitions': 1, 'not_loaded_partitions': []}
2:loading_progress(coll, ['_default'])          -> {'loading_progress': '100%', 'num_loaded_partitions': 1, 'not_loaded_partitions': []}
2:loading_progress(coll, ['second', '_default'])-> {'loading_progress': '100%', 'num_loaded_partitions': 2, 'not_loaded_partitions': []}

3: collection.release()
3:loading_progress(coll)                        -> error
3:loading_progress(coll, ['second'])            -> error
3:loading_progress(coll, ['second', '_default'])-> error
```

**Comment by XuanYang-cn** [comment]
pymilvus==2.1.0.dev35

**Comment by binbinlv** [comment]
Verified in pymilvus==2.1.0.dev35, it has been fixed.
