### ISSUE TITLE
[Bug]: AuthenticationInterceptor before proxy init completion will crash Milvus.

### ISSUE THREAD

**Issue by soothing-rain** [milvus-io/milvus#16473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: latest master
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): N/A
- OS(Ubuntu or CentOS): N/A
- CPU/Memory: N/A
- GPU: N/A
- Others:
```

### Current Behavior

AuthenticationInterceptor checks every incoming RPC for auth stuff.

When Milvus starts from scratch, it needs some time for initialization before fully available.

However if a RPC is called while Milvus is starting up, AuthenticationInterceptor will crash Milvus immediately since globalMetaCache might not be initialized yet:

https://github.com/milvus-io/milvus/blob/7d8d1ff99ad8ef1659463d9af37efddb7d4ded3e/internal/proxy/authentication_interceptor.go#L68

### Expected Behavior

Returns an error instead when globalMetaCache is nil.

**Comment by yanliang567** [comment]
/assign @soothing-rain 
@soothing-rain was this fixed already?

/unassign

**Comment by soothing-rain** [comment]
> /assign @soothing-rain @soothing-rain was this fixed already?
> 
> /unassign

Yes it is fixed
