### ISSUE TITLE
[Bug]: RES too large.

### ISSUE THREAD

**Issue by susoooon** [milvus-io/milvus#16481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.2
- Deployment mode(standalone or cluster):lone
- SDK version(e.g. pymilvus v2.0.0rc2):2.0.2
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 32
- GPU: 0
- Others:
```

### Current Behavior

`    def milvus_updata(self,entities,tenant_id,project_id):

        collection_name = MilvusConstant.MILVUS_COLLECTION_PRE+str(tenant_id)
        partition_name = MilvusConstant.MILVUS_PARTITION_PRE+str(project_id)

        try:

            self.logger.info("milvus updata "+collection_name+" ->" + partition_name + "-> start")

            connections.connect(host=MilvusConstant.MILVUS_HOST_PROD, port=MilvusConstant.MILVUS_PORT) #正式版
            self.logger.info("connections success")

            fields = [
                FieldSchema(name="issue_id", dtype=DataType.INT64, is_primary=True, auto_id=False),
                FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=768),
            ]

            try:
                has_collection = utility.has_collection(collection_name)
            except:
                has_collection = False

            if has_collection == False:
                """检查该租户是否存在，不存在则创建"""
                schema = CollectionSchema(fields)
                collection = Collection(collection_name, schema)
                collection.create_index("embeddings", MilvusConstant.MILVUS_INDEX)
                # collection.load()

                self.logger.info(f"create {collection_name}")
            try:
                has_partition = utility.has_partition(collection_name,partition_name)
            except:
                has_partition = False

            if has_partition == False:
                """检查该项目是否存在，不存在则创建"""
                collection = Collection(collection_name)      # Get an existing collection.
                collection.create_partition(partition_name)
                self.logger.info(f"create {partition_name}")

            collection = Collection(collection_name)      # Get an existing collection.
            collection.load(partition_name=partition_name)

            self.logger.info("判断是否重复")
            """判断issue_id是否重复逻辑，如果已存在则删除后再插入，保证issue_id一致性"""
            issue_ids = entities[0]
            self.logger.info(f"{issue_ids}")

            expr = f"issue_id in {issue_ids}"
            try:
                # query to verify the ids exist
                query_res = collection.query(expr,partition_name=partition_name,output_fields=["issue_id"])
                # self.logger.info(f"查询结果{query_res}")
                #
                if len(query_res) > 0:
                    self.logger.info(f"删除重复id {query_res}")

                    del_issue_ids = [i["issue_id"] for i in query_res]
                    self.milvus_delete_issue(del_issue_ids,project_id,tenant_id)
            except Exception as e:
                self.logger.error(e)
            # """插入逻辑"""
            insert_result =  collection.insert(entities,partition_name=partition_name)`

this is my code.
i want to insert 17000 vector without repetition. batchsize=32
after i insert vec succecssful, use top got this
![image](https://user-images.githubusercontent.com/40882819/163175119-2d41bf06-661e-42cb-85ba-4335c6224d0e.png)

insert more vec, memory growing ,almost 29G memory used ,then memory out. docker Exit

### Expected Behavior

insert all vec in to one collection is ok,only 500M used.
release partition per batch  such partition.release()  after insert, nothing happend
release collection per batch can solve the problem,but it is too slow to updata my vec ,almost need 2s per batch.
is it my coding problem or bug? What shall I do next？

**Comment by susoooon** [comment]
`"""milvus memory error code ,u can run it directly ,memory will larger and larger and  out finally"""
#! -*- coding: utf-8 -*-

from pymilvus import (
    connections, list_collections,
    FieldSchema, CollectionSchema, DataType,
    Collection, utility,Partition
)

import os
import logging
import re
from logging.handlers import TimedRotatingFileHandler
import random

class MilvusConstant:
    """milvus 常量"""
    MILVUS_PORT='19530' #milvus端口号
    MILVUS_HOST_PROD='127.0.0.1' #milvus生产地址


    MILVUS_ALIAS = "relationship"
    MILVUS_COLLECTION_PRE = "tenantID_"
    MILVUS_PARTITION_PRE = "projectID_"
    MILVUS_INDEX =  {
        "index_type": "IVF_FLAT",
        # "index_type": "IVF_SQ8",
        # "index_type": "FLAT",
        "metric_type": "IP",
        "params": {"nlist": 64},
    }



def setup_log(log_name):
    # 创建logger对象。传入logger名字
    logger = logging.getLogger(log_name)
    log_path = os.path.join("./", log_name)
    # 设置日志记录等级
    logger.setLevel(logging.INFO)
    # interval 滚动周期，
    # when="MIDNIGHT", interval=1 表示每天0点为更新点，每天生成一个文件
    # backupCount  表示日志保存个数
    file_handler = TimedRotatingFileHandler(
        filename=log_path, when="MIDNIGHT", interval=1, backupCount=30
    )
    # filename="mylog" suffix设置，会生成文件名为mylog.2020-02-25.log
    file_handler.suffix = "%Y-%m-%d.log"
    # extMatch是编译好正则表达式，用于匹配日志文件名后缀
    # 需要注意的是suffix和extMatch一定要匹配的上，如果不匹配，过期日志不会被删除。
    file_handler.extMatch = re.compile(r"^\d{4}-\d{2}-\d{2}.log$")
    # 定义日志输出格式
    file_handler.setFormatter(
        logging.Formatter(
            "[%(asctime)s] [%(process)d] [%(levelname)s] - %(module)s.%(funcName)s (%(filename)s:%(lineno)d) - %(message)s"
        )
    )
    logger.addHandler(file_handler)

    return logger



class MilvusConnect():
    # _instance_lock = threading.Lock()

    _instance = None
    __init__flag = False
    def __new__(cls, *args, **kwargs):
        if MilvusConnect._instance is None:
            MilvusConnect._instance = object.__new__(cls)
        return MilvusConnect._instance

    def __init__(self,logger):
        if self.__init__flag == False:
            self.__init__flag = True
            self.logger = logger
            self.logger.info("Milvus 启动")
            # connections = connect_milvusDB()

            # MILVUS_HOST=MilvusConstant.MILVUS_HOST_PROD #milvus地址
            # MILVUS_HOST=MilvusConstant.MILVUS_HOST_TEST #milvus地址


            self.count = {}


            # connections.connect( host=MilvusConstant.MILVUS_HOST_TEST, port=MilvusConstant.MILVUS_PORT) #测试版
            #     self.logger.info("加载现有Collection")

            if len(list_collections()) != 0:
                for c in list_collections():
                    Collection(c).load()



    def milvus_search(self,entities,tenant_id,available_project_ids):
        """
        milvus 查询，支持同一tenant_id的同一限定project_id的批量查询（并没有用到批量查询）
        :param entities:
        :param tenant_id:
        :param available_project_ids:
        :return:
        """
        try:
            connections.connect(host=MilvusConstant.MILVUS_HOST_PROD, port=MilvusConstant.MILVUS_PORT) #正式版

            collection_name = MilvusConstant.MILVUS_COLLECTION_PRE+str(tenant_id)
            partition_name = [MilvusConstant.MILVUS_PARTITION_PRE+str(project_id) for project_id in available_project_ids]

            original_id = entities[0]
            original_vec = entities[1]


            search_param = {
                "data": original_vec,
                "anns_field": "embeddings",
                "param": MilvusConstant.MILVUS_INDEX,
                "limit": 20,
                # "expr": f"issue_id in {partition_name}",
                "partition_names":partition_name
            }

            collection = Collection(collection_name)      # Get an existing collection.
            collection.load()

            res = collection.search(**search_param)

            """释放partition"""
            # partition = Partition(collection_name,partition_name)       # Get an existing partition.
            # partition.release()
            # collection = Collection(collection_name)      # Get an existing collection.
            # collection.release()

            return res
        except Exception as e:

            self.logger.error(e)
            return False

    def milvus_updata(self,entities,tenant_id,project_id):

        """
        创建更新collection和partition
        tenant_id就是collection的名字
        project_id 就是partition的名字
        Number of partitions in a collection	4,096
        collection 数量限制 65535
        """

        collection_name = MilvusConstant.MILVUS_COLLECTION_PRE+str(tenant_id)
        partition_name = MilvusConstant.MILVUS_PARTITION_PRE+str(project_id)


        try:

            self.logger.info("milvus updata "+collection_name+" ->" + partition_name + "-> start")

            connections.connect(host=MilvusConstant.MILVUS_HOST_PROD, port=MilvusConstant.MILVUS_PORT) #正式版
            self.logger.info("connections success")

            fields = [
                FieldSchema(name="issue_id", dtype=DataType.INT64, is_primary=True, auto_id=False),
                FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=768),
            ]

            try:
                has_collection = utility.has_collection(collection_name)
            except:
                has_collection = False

            if has_collection == False:
                """检查该租户是否存在，不存在则创建"""
                schema = CollectionSchema(fields)
                collection = Collection(collection_name, schema)
                collection.create_index("embeddings", MilvusConstant.MILVUS_INDEX)
                # collection.load()

                self.logger.info(f"create {collection_name}")
            try:
                has_partition = utility.has_partition(collection_name,partition_name)
            except:
                has_partition = False

            if has_partition == False:
                """检查该项目是否存在，不存在则创建"""
                collection = Collection(collection_name)      # Get an existing collection.
                collection.create_partition(partition_name)
                self.logger.info(f"create {partition_name}")



            # """释放collection"""
            # if collection_name not in self.count.keys():
            #     self.count[collection_name] = 0
            # else:
            #     self.count[collection_name] += 1
            #
            # if self.count[collection_name] % 100 == 0 and self.count[collection_name] != 0:
            #
            #     self.logger.info("milvus release "+collection_name+" ->" + partition_name + " ")
            #
            #     collection = Collection(collection_name)      # Get an existing collection.
            #     collection.release()
            #     collection.load()


            collection = Collection(collection_name)      # Get an existing collection.
            collection.load(partition_name=partition_name)

            self.logger.info("判断是否重复")
            """判断issue_id是否重复逻辑，如果已存在则删除后再插入，保证issue_id一致性"""
            issue_ids = entities[0]
            self.logger.info(f"{issue_ids}")

            expr = f"issue_id in {issue_ids}"
            try:
                # query to verify the ids exist
                query_res = collection.query(expr,partition_name=partition_name,output_fields=["issue_id"])
                # self.logger.info(f"查询结果{query_res}")
                #
                if len(query_res) > 0:
                    self.logger.info(f"删除重复id {query_res}")

                    del_issue_ids = [i["issue_id"] for i in query_res]
                    self.milvus_delete_issue(del_issue_ids,project_id,tenant_id)
            except Exception as e:
                self.logger.error(e)
            # """插入逻辑"""
            insert_result =  collection.insert(entities,partition_name=partition_name)
            # collection.release()
            # insert_result =  collection.insert(entities)
            """释放partition"""
            # partition = Partition(collection_name,partition_name)       # Get an existing partition.
            # partition.release()

            # collection.load(partition_name=partition_name)

            self.logger.info("milvus updata "+collection_name+" " + partition_name + "success!")
            self.logger.info(insert_result) #insert result 存入数据库
            self.logger.info("updata issue_id: "+str(entities[0]))



            return True

        except Exception as e:
            self.logger.info("updata milvus failed: " + collection_name+" " + partition_name)
            self.logger.info("updata issue_id: "+str(entities[0]))
            self.logger.error(e)

            return False




    def milvus_delete_issue(self,issue_id,project_id,tenant_id):
        """

        :param issue_id:
        :param project_id:
        :param tenant_id:
        :param my_logger:
        :return:
        """

        collection_name = MilvusConstant.MILVUS_COLLECTION_PRE+str(tenant_id)
        partition_name = MilvusConstant.MILVUS_PARTITION_PRE+str(project_id)

        try:
            connections.connect(host=MilvusConstant.MILVUS_HOST_PROD, port=MilvusConstant.MILVUS_PORT) #正式版

            if type(issue_id) == str or type(issue_id) == int:
                expr = f"issue_id == {issue_id}"

            elif type(issue_id) == list:
                expr = f"issue_id in {issue_id}"

            else:
                self.logger.error("issue_id type must be str or list")
                return False

            collection = Collection(collection_name)      # Get an existing collection.
            collection.load()

            collection.delete(expr,partition_name=partition_name)

            return True

        except Exception as e:
            self.logger.info("delete issue_id failed: "+ str(issue_id))
            self.logger.error(e)
            return False


if __name__ == '__main__':
    milvus_conn = MilvusConnect(setup_log("milvus_memory_issue"))
    max_count = 20000
    BATCH_SIZE = 32
    for count in range(max_count+10):

        if count % BATCH_SIZE == 0 or count >= max_count:


            entities = [
                [int(str(i)+str(count)) for i in range(BATCH_SIZE)],  # field pk
                # [float(random.randrange(-20, -10)) for _ in range(BATCH_SIZE)],  # field random
                [[random.random() for _ in range(768)] for _ in range(BATCH_SIZE)],  # field embeddings
            ]
            mc_result = milvus_conn.milvus_updata(entities,1,count)


`

**Comment by susoooon** [comment]
[milvus_memory_issue.txt](https://github.com/milvus-io/milvus/files/8493650/milvus_memory_issue.txt)
change txt to py, milvus memory error code ,u can run it directly ,memory will larger and larger and out finally

**Comment by soothing-rain** [comment]
Hey you probably wanna take a look at this: https://github.com/milvus-io/milvus/discussions/16680, which might be the root cause.

**Comment by xiaofan-luan** [comment]
> project_id

Hi @susoooon , how many partitions do you have?

**Comment by susoooon** [comment]
> > project_id
> 
> Hi @susoooon , how many partitions do you have?

more than 5000.Now I solve the problem by param "expr"  . It is ok,though not beautiful enough.

**Comment by xiaofan-luan** [comment]
> > > project_id
> > 
> > 
> > Hi @susoooon , how many partitions do you have?
> 
> more than 5000.Now I solve the problem by param "expr" . It is ok,though not beautiful enough.

usually expr helps on the meta filtering case, I've opened a issue to solve memory allocation problem when there is many parititions

**Comment by yanliang567** [comment]
@xiaofan-luan what the issue issue you mentioned above, please link it in this issue and close this one

/assign @xiaofan-luan 
/unassign

**Comment by xiaofan-luan** [comment]
2.1 has fixed a few memory related issues so pls pls try the new release
