### ISSUE TITLE
[Bug]: Query and search are hang on.

### ISSUE THREAD

**Issue by hiwwx** [milvus-io/milvus#16493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.2
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.0.2
- OS(Ubuntu or CentOS): Ubuntu and CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When i doing query or search operation, the request hangs without any error response.

The following logs are record after i perform the query operation.

My config:
[config.txt](https://github.com/milvus-io/milvus/files/8488070/config.txt)

proxy log:
[proxy_log.LOG](https://github.com/milvus-io/milvus/files/8487832/proxy_log.LOG)
I think the first three lines maybe help.
```
2022-04-14 16:54:07.340 [2022/04/14 08:54:07.340 +00:00] [DEBUG] [task.go:2404] [proxy] ["Query: wait to finish failed, timeout!, taskID:"=432518075153383776]
2022-04-14 16:54:07.340 [2022/04/14 08:54:07.340 +00:00] [DEBUG] [time_recorder.go:78] ["queryTask PostExecute: done (92933ms)"]
2022-04-14 16:54:07.340 [2022/04/14 08:54:07.340 +00:00] [ERROR] [task_scheduler.go:501] ["Failed to post-execute task: queryTask:wait to finish failed, timeout : 432518075153383776"] [traceID=5906f4264ddf6410] [stack="github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:501"]
```

querynode log:
Always repeat the two lines.
```
2022-04-14 17:03:36.293 [2022/04/14 09:03:36.293 +00:00] [DEBUG] [impl.go:37] ["Get QueryNode component states"]
2022-04-14 17:03:36.293 [2022/04/14 09:03:36.293 +00:00] [DEBUG] [impl.go:62] ["Get QueryNode component state done"] [stateCode=Healthy]
```

querycoord log:
[querycoord.LOG](https://github.com/milvus-io/milvus/files/8487879/querycoord.LOG)

Actually, i first met this problem at last week with v2.0.1. So i reinstall v2.0.2 and reinsert all data but yesterday i got this problem too.

### Expected Behavior

Search / Query can return the right response or error message.

### Steps To Reproduce

```markdown
I use milvus in our online system, so it's hard to reproduce it with a light example.
Before i met this problem, I combined query and insert operation to upsert data with 50 thousand requests in order.

If any other info can help you, please let me know.
```

**Comment by yanliang567** [comment]
@soothing-rain could you please help on this issue?

/assign @soothing-rain 
/unassign

**Comment by hiwwx** [comment]
I think something mistake in service discovery may be one reason caused this problem. 
For example, the proxy can not connect to the datacoord with the error message `grpc: addrConn.createTransport failed to connect to {172.20.174.111:13333 172.20.174.111:13333 <nil> 0 <nil>}` after IP of datacoord changed because it has been restarted, and other components got similar error if the upstream has been restarted.
I restart some components in order then send a query and get some new logs as follows:
[proxy_log2.log](https://github.com/milvus-io/milvus/files/8494039/proxy_log2.log)
[querynode_log2.log](https://github.com/milvus-io/milvus/files/8494042/querynode_log2.log)
[querycoord2.log](https://github.com/milvus-io/milvus/files/8494043/querycoord2.log)

**Comment by hiwwx** [comment]
@soothing-rain can u help me to solve this problem?

**Comment by soothing-rain** [comment]
Hey @hiwwx sorry I missed this.

@LoveEachDay could take a look at this?

**Comment by LoveEachDay** [comment]
> I think something mistake in service discovery may be one reason caused this problem. For example, the proxy can not connect to the datacoord with the error message `grpc: addrConn.createTransport failed to connect to {172.20.174.111:13333 172.20.174.111:13333 <nil> 0 <nil>}` after IP of datacoord changed because it has been restarted. This error can be solved if the proxy is restarted, it seems like proxy only gets the latest IP of the upstream component at the init moment. Other components got a similar error if upstream has been restarted. I restart some components in order then send a query and get some new logs as follows: [proxy_log2.log](https://github.com/milvus-io/milvus/files/8494039/proxy_log2.log) [querynode_log2.log](https://github.com/milvus-io/milvus/files/8494042/querynode_log2.log) [querycoord2.log](https://github.com/milvus-io/milvus/files/8494043/querycoord2.log)

@hiwwx Just as you said above, proxy will keep trying to connect the old coord ip. When you trigger a new request, it will reset the connection, try to fetch coord session from etcd, and connect to new coord ip.

I've make an experiment like this:
1> create a milvus cluster with v2.0.2 image
2> wait for all components ready, and run `hello_miluvs.py` 
3> manually delete the querycoord pod, and wait for the new querycoord pod to become ready again.
4> proxy will keep complaining the dialing to connect the old query coord
4> run `hello_miluvs.py`, proxy will reset the connection to old query coord,  fetch new query coord session from etcd, and make a connection to new query coord, and everything runs smoothly.

We'd may change the `reset connection policy` use etcd watch for the coord key.

**Comment by hiwwx** [comment]
Since that is so, let's go back to check why the search request hangs on?
