### ISSUE TITLE
Create collection return fail is better if binary collection dimension is not multiple of 8

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#1650]
**Describe the bug**
The current result is status ok, and add vectors return not ok.
create collection failed is more friendly for binary(JACCARD/HAMMING) collection

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
This bug has been fixed in latest build.
Return error message "Invalid table dimension: xxx. The table dimension must be a multiple of 8"

**Comment by del-zhenwu** [comment]
fixed
