### ISSUE TITLE
[Bug]: kubectl deploy distributed milvus (offline)

### ISSUE THREAD

**Issue by yearlz** [milvus-io/milvus#16502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.2
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 128g
- GPU: 
- Others:
```

### Current Behavior

use the offline mode to deploy the distrubuted milvus,  error occurs

the  instructions are from [https://milvus.io/cn/docs/v2.0.x/install_offline-helm.md](url)

1 .  pull docker images :
2.  load images
    the images are as follows:
![image](https://user-images.githubusercontent.com/32187348/163534846-eef24de1-92a2-4a87-a805-119f7fa30478.png)

4.  use the milvus_manifest.yaml to deploy milvus
  the script like :[milvus_manifest.zip](https://github.com/milvus-io/milvus/files/8494438/milvus_manifest.zip)

then some error occures:
![image](https://user-images.githubusercontent.com/32187348/163535958-7366fb62-bde6-41eb-b655-0de40ccae6fc.png)
![1650006440(1)](https://user-images.githubusercontent.com/32187348/163536652-d12ba206-7edb-4362-81aa-6185d28b251f.png)

this pod gets net connection error
![lQLPDhtVUbr8hkoWzQJVsLfJsAgXQTjzAlx11OkAHwA_597_22](https://user-images.githubusercontent.com/32187348/163536812-ecd2c6e3-e4ae-4f08-82d8-6de0dd9bd8d5.png)
![lQLPDhtVUaWHWSXNAXfNBr6wPogUfIRiB1cCXHWxWsBJAA_1726_375](https://user-images.githubusercontent.com/32187348/163536967-42bc4046-e66b-433c-836b-f6e9a7f9eacc.png)

check the pod zookeeper-0
it shows :

![image](https://user-images.githubusercontent.com/32187348/163548945-dab66b60-16c5-4f53-b61b-b0c92334b3e4.png)

any idea bout it

**Comment by yearlz** [comment]
![lQLPDhtVbOIUghnM0M0GtLB5BkZrshgQxgJcolFmgMgA_1716_208](https://user-images.githubusercontent.com/32187348/163537913-10722732-1461-4526-ab59-9d93417276a2.png)

**Comment by LoveEachDay** [comment]
You'd better not enable istio sidecar for milvus installation namespace.

**Comment by yanliang567** [comment]
@yearlz  please retry as suggested above.

/assign @yearlz 
/unassign

**Comment by yearlz** [comment]
> @yearlz please retry as suggested above.
> 
> /assign @yearlz /unassign

yes, i will try the solution and reply as soon as possible

**Comment by yearlz** [comment]
it works
