### ISSUE TITLE
[Bug]: [credential] No description about user and password in connect API doc

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#16503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:latest
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

No description about user and password in connect API doc

### Expected Behavior

Add description about user and password in connect API doc

### Steps To Reproduce

```markdown
def connect(self, alias=DefaultConfig.DEFAULT_USING, **kwargs):
        """
        Constructs a milvus connection and register it under given alias.
        :param alias: The name of milvus connection
        :type  alias: str
        :raises NotImplementedError: If handler in connection parameters is not GRPC.
        :raises ParamError: If pool in connection parameters is not supported.
        :raises Exception: If server specified in parameters is not ready, we cannot connect to
                           server.
        :example:
            >>> from pymilvus import connections
            >>> connections.connect("test", host="localhost", port="19530")
        """
        if not isinstance(alias, str):
            raise ConnectionConfigException(0, ExceptionsMessage.AliasType % type(alias))
```

**Comment by DragonDriver** [comment]
https://github.com/milvus-io/pymilvus/pull/953 will solve this issue.

**Comment by binbinlv** [comment]
Fixed and closed.

     :param kwargs:
            * *host* (``str``) --
                Required. The host of Milvus instance.
            * *port* (``str/int``) --
                Required. The port of Milvus instance.
            * *user* (``str``) --
                Optional. Use which user to connect to Milvus instance. If user and password
                are provided, we will add related header in every RPC call.
            * *password* (``str``) --
                Optional and required when user is provided. The password corresponding to
                the user.
