### ISSUE TITLE
[Bug]: search speed, now it is very slow in CPU, 33 ms per entity

### ISSUE THREAD

**Issue by rocke-dong** [milvus-io/milvus#16509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.0.2
- Deployment mode(standalone or cluster): standalone 
- SDK version: pymilvus v2.0.2, python 3.8
- OS(Ubuntu or CentOS): Ubuntu 20.04
- CPU/Memory: 8  Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz / 64G
```

### Current Behavior

Actually, this is not a bug, may be a usage issue, I apologize to put into issue to hope to get attentions.
Sorry and Thanks !!

Problem: search speed is very slow, 33 ms per entity.

milvus configs:
nlist: 600
nprobe: 5
metric_type: "L2"
index_type: "IVF_FLAT"
index_file_size: 2048 (MB)
queryNode:
  cacheSize: 32 # GB, default 32 GB, `cacheSize` is the memory used for caching data for faster query.
data infor:
num entity: 167707
vector dim size: 12038
vector type: float
search entity num: 4209
search total time: 139 seconds
search time per entity num: 139/4209*1000=33 ms!

My trial
1. I search many articles, and so use very small nprobe, 5.
2. nlist is based on general terms, the recommended value of nlist is 4 × sqrt(n), where n is the total number of entities in a segment.
3. I test index_file_size 1024 and 2048 when initialize Connection, 1024 and 2048 too tiny difference on search times.
from pymilvus import Collection

```
collection = Collection(name=collection_name, schema=schema, using='default', shards_num=2, 
        index_file_size=2048)
```

4. I test batch search, number of vectors per query(nq) = 500 and nq = 1
that's the data array size, I input 1 entity or 500 entities into collection.search()
```
collection.search(data=data, anns_field=self.vector_field_name, 
            param=self.mivlus_search_params, limit=self.top_num)
```
nq 1 use about 1.5~1.8 times of time thannq 500 in total time.
### the nq(number of vectors per query) has small influence on search speed, the search is not multi process? how to set nq to have best query speed? what's affects nq speed?

Questions
Could you give me advice to improve the search speed?
If collection.search is not multi process or multi thread, do we need write extra multi process or multi thread?
one possible solution, use GPU during search.
thanks!!!

### Expected Behavior

I hope the search speed for per entity is below 5ms. Now it is 33 ms.

### Steps To Reproduce

```markdown
https://github.com/milvus-io/milvus/discussions/16508
```

**Comment by yanliang567** [comment]
thank you for the details of the issue. the community is trying to improve the performance in 2.1.But let's take a look at this one first.

/assign @czs007

**Comment by rocke-dong** [comment]
Dear all,
Mivlus 2.0.2, In sdk, the "index_file_size" parameter doesn't work, when I modify the segment maxSize in milvus.yml from 512 to 2048, the search time reduces from 130 seconds to 41 seconds for 4209 entities, 9.7ms for each entity, number of query is 500, IVF_FLAT. A big improvement in query speed.

segment:
maxSize: 512 # Maximum size of a segment in MB

I will test in milvus 2.1 and 2.2 in the future.

**Comment by xiaofan-luan** [comment]
cool!
