### ISSUE TITLE
[Bug]: 在milvus-insight页面上load数据失败

### ISSUE THREAD

**Issue by jingsu2000** [milvus-io/milvus#16505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.2
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): centos7.6
- CPU/Memory: 4C/16G
- GPU: null
- Others:
```

### Current Behavior

docker-compose部署的集群版，在milvus-insight页面上load数据无响应，之后proxy会假死
proxy容器有如下报错和警告
[ERROR] [task_scheduler.go:491] [\"Failed to execute task: no index is created\"]
[WARN] [impl.go:2115] [\"GetIndexState failed to WaitToFinish\"] [error=\"no index is created\"]

**Comment by JackLCL** [comment]
@jingsu2000 
Please describe your issue in English and upload a full log of Milvus.
