### ISSUE TITLE
[Bug]: [nightly] it did not raise exception when loading balance with one of not existed sealed segment ids

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#16518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: latest
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

it did not raise exception when loading balance with one of not existed sealed segment ids

### Expected Behavior

raise exception when loading balance with one of not existed sealed segment ids

### Steps To Reproduce
https://ci.milvus.io:18080/jenkins/blue/rest/organizations/jenkins/pipelines/milvus-nightly-ci/branches/master/runs/471/nodes/190/steps/211/log/?start=0

```markdown
Running nightly:




    def test_load_balance_with_one_sealed_segment_id_not_exist(self):
        """
        target: test load balance of collection
        method: init a collection and load balance with one of sealed segment ids not exist
        expected: raise exception
        """
        # init a collection
        c_name = cf.gen_unique_str(prefix)
        collection_w = self.init_collection_wrap(name=c_name)
        ms = MilvusSys()
        nb = 3000
        df = cf.gen_default_dataframe_data(nb)
        collection_w.insert(df)
        # get sealed segments
        collection_w.num_entities
        # get growing segments
        collection_w.insert(df)
        collection_w.load()
        # prepare load balance params
        res, _ = self.utility_wrap.get_query_segment_info(c_name)
        segment_distribution = cf.get_segment_distribution(res)
        all_querynodes = [node["identifier"] for node in ms.query_nodes]
        all_querynodes = sorted(all_querynodes,
                                key=lambda x: len(segment_distribution[x]["sealed"])
                                if x in segment_distribution else 0, reverse=True)
        src_node_id = all_querynodes[0]
        dst_node_ids = all_querynodes[1:]
        dst_node_ids.append([node["identifier"] for node in ms.index_nodes][0])
        sealed_segment_ids = segment_distribution[src_node_id]["sealed"]
        # add a segment id which is not exist or a growing segment
        if len(segment_distribution[src_node_id]["growing"]) > 0:
            sealed_segment_ids.append(segment_distribution[src_node_id]["growing"][0])
        else:
            sealed_segment_ids.append(max(segment_distribution[src_node_id]["sealed"]) + 1)
        # load balance
        self.utility_wrap.load_balance(src_node_id, dst_node_ids, sealed_segment_ids, 
                                       check_task=CheckTasks.err_res,
                                       check_items={ct.err_code: 1, ct.err_msg: "is not exist"})
```

### Anything else?

1 milvus logs: [artifacts-milvus-distributed-pulsar-master-471-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/471/artifact/artifacts-milvus-distributed-pulsar-master-471-pymilvus-e2e-logs.tar.gz)

2 collection name: utility_WU8Be5BX

3 test case failed timeline:
[2022-04-17T12:33:31.092Z] [gw2] [ 98%] FAILED testcases/test_utility.py::TestUtilityAdvanced::test_load_balance_with_one_sealed_segment_id_not_exist 

4 test logs:
```
[2022-04-17T12:55:55.542Z] [2022-04-17 12:33:01 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None], kwargs: {'timeout': 20} (api_request.py:55)
[2022-04-17T12:55:55.542Z] [2022-04-17 12:33:03 - DEBUG - ci_test]: (api_response) : None  (api_request.py:27)
[2022-04-17T12:55:55.542Z] [2022-04-17 12:33:03 - DEBUG - ci_test]: (api_request)  : [get_query_segment_info] args: ['utility_WU8Be5BX', 20, 'default'], kwargs: {} (api_request.py:55)
[2022-04-17T12:55:55.542Z] [2022-04-17 12:33:03 - DEBUG - ci_test]: (api_response) : [segmentID: 432589708498042883
[2022-04-17T12:55:55.542Z] collectionID: 432589708366708737
[2022-04-17T12:55:55.542Z] partitionID: 432589708366708738
[2022-04-17T12:55:55.542Z] mem_size: 784428
[2022-04-17T12:55:55.542Z] num_rows: 1497
[2022-04-17T12:55:55.542Z] nodeID: 2
[2022-04-17T12:55:55.542Z] state: Sealed
[2022-04-17T12:55:55.542Z] , segmentID: 432589708498042881
[2022-04-17T12:55:55.542Z] collectionID: 432589708366708737
[2022-04-17T12:55:55.542Z] partitionID: 432589708366708738
[2022-04-17T12:55:55.542Z] mem_size: 787572
[2022-04-17T12:55:55.542Z] num_rows: 1503
[2022-04-17T12:55:55.542Z] nodeID: 2
[2022-04-17T12:55:55.542Z] state: Se......  (api_request.py:27)
[2022-04-17T12:55:55.542Z] [2022-04-17 12:33:03 - DEBUG - ci_test]: (api_request)  : [load_balance] args: [2, [1, 6], [432589708498042883, 432589708498042881, 432589708498042884], 20, 'default'], kwargs: {} (api_request.py:55)
[2022-04-17T12:55:55.542Z] [2022-04-17 12:33:04 - DEBUG - ci_test]: (api_response) : None  (api_request.py:27)
```

**Comment by sunby** [comment]
Querycoord does return error if it receives an unloaded segment. @XuanYang-cn Would you please check whether the pymilvus handle the error?

**Comment by sunby** [comment]
@binbinlv The `ct.err_msg` is wrong. Server returned error message "unloaded segment xxxxx"

**Comment by binbinlv** [comment]
@sunby 

currently, our test framework did not care specific messages actually, so it will be set as pass if either the error code or message is rignt.

Here "pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=, loadBalanceTask: unloaded segment 432630861804863491)>", code is 1, so the test case could pass through "check_items={ct.err_code: 1, ct.err_msg: "is not exist"})", the error code is right.

And this case is L1, so it is right in each PR merging process, and only returns "None" in the above nightly.
```
[2022-04-17T12:55:55.542Z] [2022-04-17 12:33:03 - DEBUG - ci_test]: (api_request)  : [load_balance] args: [2, [1, 6], [432589708498042883, 432589708498042881, 432589708498042884], 20, 'default'], kwargs: {} (api_request.py:55)
[2022-04-17T12:55:55.542Z] [2022-04-17 12:33:04 - DEBUG - ci_test]: (api_response) : None  (api_request.py:27)
```

**Comment by sunby** [comment]
> @sunby
> 
> currently, our test framework did not care specific messages actually, so it will be set as pass if either the error code or message is rignt.
> 
> Here "pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=, loadBalanceTask: unloaded segment 432630861804863491)>", code is 1, so the test case could pass through "check_items={ct.err_code: 1, ct.err_msg: "is not exist"})", the error code is right.
> 
> And this case is L1, so it is right in each PR merging process, and only returns "None" in the above nightly.
> 
> ```
> [2022-04-17T12:55:55.542Z] [2022-04-17 12:33:03 - DEBUG - ci_test]: (api_request)  : [load_balance] args: [2, [1, 6], [432589708498042883, 432589708498042881, 432589708498042884], 20, 'default'], kwargs: {} (api_request.py:55)
> [2022-04-17T12:55:55.542Z] [2022-04-17 12:33:04 - DEBUG - ci_test]: (api_response) : None  (api_request.py:27)
> ```
> 
> So the error message is not the root cause for the test case failure.

OK, thanks for the explaination. Where's the nighly test log? I need to check the details.

**Comment by binbinlv** [comment]
1. milvus logs:
[artifacts-milvus-distributed-pulsar-master-471-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/471/artifact/artifacts-milvus-distributed-pulsar-master-471-pymilvus-e2e-logs.tar.gz)

2. Test logs on website:
https://ci.milvus.io:18080/jenkins/blue/rest/organizations/jenkins/pipelines/milvus-nightly-ci/branches/master/runs/471/nodes/190/steps/211/log/?start=0

3. pytest logs:
[milvus-distributed-pulsar-pymilvus-pytest-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/471/artifact/milvus-distributed-pulsar-pymilvus-pytest-logs.tar.gz)

**Comment by binbinlv** [comment]
1. milvus logs:
[artifacts-milvus-distributed-pulsar-master-471-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/471/artifact/artifacts-milvus-distributed-pulsar-master-471-pymilvus-e2e-logs.tar.gz)

2. Test logs on website:
https://ci.milvus.io:18080/jenkins/blue/rest/organizations/jenkins/pipelines/milvus-nightly-ci/branches/master/runs/471/nodes/190/steps/211/log/?start=0

3. pytest logs:
[milvus-distributed-pulsar-pymilvus-pytest-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/471/artifact/milvus-distributed-pulsar-pymilvus-pytest-logs.tar.gz)

**Comment by sunby** [comment]
@binbinlv I check the log and these 3 segments `[432589708498042883, 432589708498042881, 432589708498042884]` does exist in the collection. Would you like to check the code which generates the non-existed segment id?

**Comment by binbinlv** [comment]
@zhuwenxing  Could you help on this question?

**Comment by zhuwenxing** [comment]
> @binbinlv I check the log and these 3 segments `[432589708498042883, 432589708498042881, 432589708498042884]` does exist in the collection. Would you like to check the code which generates the non-existed segment id?
 
```
    sealed_segment_ids = segment_distribution[src_node_id]["sealed"]
    # add a segment id which is not exist or a growing segment
    if len(segment_distribution[src_node_id]["growing"]) > 0:
        sealed_segment_ids.append(segment_distribution[src_node_id]["growing"][0])
    else:
        sealed_segment_ids.append(max(segment_distribution[src_node_id]["sealed"]) + 1)
```

Maybe one of them is a growing segment.  if doing loading balance for a growing segment, the expectation is failure
In this test case, non-existed sealed segment id could be a growing segment or faked by `max(segment_distribution[src_node_id]["sealed"]) + 1`.

**Comment by sunby** [comment]
> > @binbinlv I check the log and these 3 segments `[432589708498042883, 432589708498042881, 432589708498042884]` does exist in the collection. Would you like to check the code which generates the non-existed segment id?
> 
> ```
>     sealed_segment_ids = segment_distribution[src_node_id]["sealed"]
>     # add a segment id which is not exist or a growing segment
>     if len(segment_distribution[src_node_id]["growing"]) > 0:
>         sealed_segment_ids.append(segment_distribution[src_node_id]["growing"][0])
>     else:
>         sealed_segment_ids.append(max(segment_distribution[src_node_id]["sealed"]) + 1)
> ```
> 
> @sunby Maybe one of them is a growing segment. if doing loading balance for a growing segment, the expectation is to failed In this test case, non-existed sealed segment id could be a growing segment or faked by `max(segment_distribution[src_node_id]["sealed"]) + 1`.

I check these 3 segments and they are all sealed. So maybe 432589708498042884 is created by 432589708498042883+1?
