### ISSUE TITLE
[Bug]: milvus2.0.2 doesn't support GPU?

### ISSUE THREAD

**Issue by rocke-dong** [milvus-io/milvus#16510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
Environment
- Milvus version: v2.0.2
- Deployment mode(standalone or cluster): standalone 
- SDK version: pymilvus v2.0.2, python 3.8
- OS(Ubuntu or CentOS): Ubuntu 20.04
- CPU/Memory: 8  Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz / 64G
- Others:
```

### Current Behavior

wget https://raw.githubusercontent.com/milvus-io/milvus/v2.0.2/configs/milvus.yaml
I check the v2.0.2 configs/milvus.yaml, there is no GPU.
I check the doc, the GPU is only mentioned milvus 1.*.

### Expected Behavior

Does milvus2.0.2 support GPU?
If no support GPU now, will it support in future?
If support GPU, could you give milvus v2.* GPU config and usage docs?

thanks!!

### Steps To Reproduce

```markdown
wget https://raw.githubusercontent.com/milvus-io/milvus/v2.0.2/configs/milvus.yaml
I check the v2.0.2 configs/milvus.yaml, there is no GPU.
I check the doc, the GPU is only mentioned milvus 1.*.
```

**Comment by xiaofan-luan** [comment]
@rocke-dong in our roadmap, GPU will support on milvus 2.2(End of July)

**Comment by yanliang567** [comment]
/assign @rocke-dong  
please feel free to contribute in GPU support if you are interested.
