### ISSUE TITLE
Check validity  of dimension when collection metric type is binary one

### ISSUE THREAD

**Issue by BossZou** [milvus-io/milvus#1651]
**Describe the bug**
I found there is no any limit of dimension when collection metric type is binary one. I tried to create a `HAMMING` collection, specifying dimension is 1. However, I received status of OK.

Here is my shell code:
```
curl -X POST "http://127.0.0.1:19121/collections" -H "accept: application/json" -H "Content-Type: application/json" -d '{"collection_name":"test_collection02","dimension":125,"index_file_size":10,"metric_type":"HAMMING"}'

{"message":"OK","code":0}%
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation from source
- Milvus version v0.7.0
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
Check dimension when create collection, dimension must be a multiple of 8

**Comment by yhmo** [comment]
Fixed by pr1666
