### ISSUE TITLE
[Feature]: Search support vector field as output_fields

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#16538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

We should be able to support search with getting vector result.
So far there is a check here:
if field.DataType == schemapb.DataType_BinaryVector || field.DataType == schemapb.DataType_FloatVector {
	return errors.New("search doesn't support vector field as output_fields")
} 

### Describe the solution you'd like.

We already support retrieve vector even if vector not in memory, my guess is it won't be too hard to support retrieve vector(The performance might be bottle neck)

**Comment by codersky** [comment]
@xiaofan-luan per your comments, can by understand as if we just enable the vector field as result will impact the performance if the vector itself is not in memory, we need to identify it on disk by index? is my understanding right? if yes, any suggestion?

**Comment by xiaofan-luan** [comment]
keep it open~
This has to be done in 2.2

**Comment by dee-corr** [comment]
Hello, is there any update on this?

**Comment by xiaofan-luan** [comment]
Currently it's not working as expected, the trouble is:
1) we can not load all vector data into memory because that might double the memory 
2) currently we implement LRU strategy but it's not working well because the minio storage is too slow thus if cache is not large enough, it greatly affect the performance.

We are thinking of two ways to implement:
1) get vector directly from knowhere
2) refine the cache strategy by introducing some local ssd cache.

Feel free to give us advice and directly code contritubution

**Comment by gaborvecsei** [comment]
Asking for tips:
The temporary solution is to store the embedding in a separate field and then return that. Is that right?

**Comment by xiaofan-luan** [comment]
> Asking for tips: The temporary solution is to store the embedding in a separate field and then return that. Is that right?

Yep, and this feature is already on the way!

**Comment by xige-16** [comment]
repeated with https://github.com/milvus-io/milvus/issues/23449

**Comment by xige-16** [comment]
This feature has been released on milvus 2.2.12.
