### ISSUE TITLE
[Feature]: More informative error messages on inserting to collection

### ISSUE THREAD

**Issue by jmugan** [milvus-io/milvus#16536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Inserting vectors into a collection requires a lot of fumbling in the dark.

### Describe the solution you'd like.

My vectors are in numpy and I have to convert them to a list, but I keep getting errors like `pymilvus.orm.exceptions.DataTypeNotSupportException: <DataTypeNotSupportException: (code=0, message=Data type is not support.)>` or `pymilvus.orm.exceptions.SchemaNotReadyException: <SchemaNotReadyException: (code=0, message=The types of schema and data do not match.)>`. 

It reminds me of the matrix size mismatch problem in deep learning, but PyTorch and TensorFlow will say something like "expected xyz" and got "xyk" to help clue you in on what is going on.

**Comment by xiaofan-luan** [comment]
> but PyTorch and TensorFlow will say something like "expected xyz" and got "xyk" to help clue you in on what is going on.

Emmm, feel free to send pull request, the current error message is confusing~

**Comment by xiaofan-luan** [comment]
keep it open

**Comment by XuanYang-cn** [comment]
fixed at pymilvus==2.2.0, Feel free to reopen this if anything similar occurs again
