### ISSUE TITLE
[Bug]: milvus1.1.1 distributed deployment with 3 servers error

### ISSUE THREAD

**Issue by yearlz** [milvus-io/milvus#16550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 1.1.1
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 500
- GPU: yes
- Others:
```

### Current Behavior

follow the instruction :
[https://github.com/milvus-io/bootcamp/blob/1.0/solutions/Mishards/README.md](url)
2 servers works fine (one "wr" mode with mysql , the other "ro"with mishards).

when i added another server with "ro" mode ,  and redeploy mishards,
it shows:
![image](https://user-images.githubusercontent.com/32187348/164022741-cf140ef2-df26-4bda-ac13-fff15d5361e8.png)

97 is the new server with "ro"

docker logs 97 shows:
![1650436349(1)](https://user-images.githubusercontent.com/32187348/164165663-0e233bac-593f-4996-b6c0-7f559a9eb93c.jpg)

seems that 97 cannot reach mysql on 99 ,but  92 (with mishards) can reach mysql on 99,
the config of "ro" is the same on 97 and 92

the cluster_mishards.yaml is:
![image](https://user-images.githubusercontent.com/32187348/164023010-4a0a3969-a3e2-48ef-a604-eb983e0ab0ab.png)

any idea to solve this?

**Comment by yanliang567** [comment]
@yhmo could you please help on this issue?

/assign @yhmo 
/unassign
