### ISSUE TITLE
[Enhancement]: After the collection is dropped, the data in the collection can be deleted immediately.

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#16556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

When the user executes drop collection, he wishes to add a parameter that controls whether to delete the data in the collection immediately from persistent storage.

### Why is this needed?

Most of the time, after the user performs the drop collection operation, they want to delete the data in the collection from the disk immediately to save disk space, rather than keep it for a period of time and then delete it.

### Anything else?

N/A

**Comment by xiaofan-luan** [comment]
Data can not be delete immediately for the following reasons:
1) this feature is like a trash box in case user drop the wrong collection
2) user may want to travel back to old state and query for certain collection
3) for the implementation reasons, we may build index on a dropped collection and if collection data is purged then build index may stuck
