### ISSUE TITLE
[Bug]: when collection loadding or release Causing cluster nodes to hang up

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#16566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When call collection load/release, the server always hang up.

This bug is reported from here: https://github.com/milvus-io/milvus/discussions/16561. by @[zbhuang666](https://github.com/zbhuang666)

### Anything else?

[FATAL] [logutil.go:102] [panic] [recover=""Failed to create consumer by-dev-rootcoord-dml_99, error = All attempts results:\nattempt https://github.com/milvus-io/milvus/issues/1:server error: ConsumerBusy: Exclusive consumer is already connected\nattempt https://github.com/milvus-io/milvus/issues/2:server error: ConsumerBusy: Exclusive consumer is already connected\nattempt https://github.com/milvus-io/milvus/pull/3:server error: ConsumerBusy: Exclusive consumer is already connected\nattempt https://github.com/milvus-io/milvus/pull/4:server error: ConsumerBusy: Exclusive consumer is already connected\nattempt https://github.com/milvus-io/milvus/pull/5:server error: ConsumerBusy: Exclusive consumer is already connected\nattempt https://github.com/milvus-io/milvus/issues/6:server error: ConsumerBusy: Exclusive consumer is already connected\nattempt https://github.com/milvus-io/milvus/issues/7:server error: ConsumerBusy: Exclusive consumer is already connected\nattempt https://github.com/milvus-io/milvus/pull/8:server error: ConsumerBusy: Exclusive consumer is already connected\nattempt https://github.com/milvus-io/milvus/issues/9:server error: ConsumerBusy: Exclusive consumer is already connected\nattempt https://github.com/milvus-io/milvus/pull/10:server error: ConsumerBusy: Exclusive consumer is already connected\nattempt https://github.com/milvus-io/milvus/pull/11:server error: ConsumerBusy: Exclusive consumer is already connected\n""] [stack="[github.com/milvus-io/milvus/internal/util/logutil.LogPanic\n\t/go/src/github.com/milvus-io/milvus/internal/util/logutil/logutil.go:102\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:965\ngithub.com/milvus-io/milvus/internal/msgstream.(*mqMsgStream).AsConsumerWithPosition\n\t/go/src/github.com/milvus-io/milvus/internal/msgstream/mq_msgstream.go:165\ngithub.com/milvus-io/milvus/internal/msgstream.(*mqMsgStream).AsConsumer\n\t/go/src/github.com/milvus-io/milvus/internal/msgstream/mq_msgstream.go:131\ngithub.com/milvus-io/milvus/internal/datacoord.(*ChannelManager).unsubscribe\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/channel_manager.go:369\ngithub.com/milvus-io/milvus/internal/datacoord.(*ChannelManager).cleanUpAndDelete\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/channel_manager.go:607\ngithub.com/milvus-io/milvus/internal/datacoord.(*ChannelManager).processAck\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/channel_manager.go:578\ngithub.com/milvus-io/milvus/internal/datacoord.(*ChannelManager).watchChannelStatesLoop\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/channel_manager.go:661](https://github.com/milvus-io/milvus/internal/util/logutil.LogPanic/n/t/go/src/github.com/milvus-io/milvus/internal/util/logutil/logutil.go:102/nruntime.gopanic/n/t/usr/local/go/src/runtime/panic.go:965/ngithub.com/milvus-io/milvus/internal/msgstream.(*mqMsgStream).AsConsumerWithPosition/n/t/go/src/github.com/milvus-io/milvus/internal/msgstream/mq_msgstream.go:165/ngithub.com/milvus-io/milvus/internal/msgstream.(*mqMsgStream).AsConsumer/n/t/go/src/github.com/milvus-io/milvus/internal/msgstream/mq_msgstream.go:131/ngithub.com/milvus-io/milvus/internal/datacoord.(*ChannelManager).unsubscribe/n/t/go/src/github.com/milvus-io/milvus/internal/datacoord/channel_manager.go:369/ngithub.com/milvus-io/milvus/internal/datacoord.(*ChannelManager).cleanUpAndDelete/n/t/go/src/github.com/milvus-io/milvus/internal/datacoord/channel_manager.go:607/ngithub.com/milvus-io/milvus/internal/datacoord.(*ChannelManager).processAck/n/t/go/src/github.com/milvus-io/milvus/internal/datacoord/channel_manager.go:578/ngithub.com/milvus-io/milvus/internal/datacoord.(*ChannelManager).watchChannelStatesLoop/n/t/go/src/github.com/milvus-io/milvus/internal/datacoord/channel_manager.go:661)"]

[ERROR] [client.go:254] ["datacoord ClientBase ReCall grpc second call get error "] [error="err: context deadline exceeded\n, /go/src/[github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51](https://github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51) [github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:253](https://github.com/milvus-io/milvus/internal/util/trace.StackTrace/n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:253) [github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:111](https://github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall/n/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:111) [github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).GetComponentStates\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:59](https://github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).GetComponentStates/n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:59) [github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1\n/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:34](https://github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1/n/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:34) [github.com/milvus-io/milvus/internal/util/retry.Do\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:83](https://github.com/milvus-io/milvus/internal/util/retry.Do/n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:83) [github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:98](https://github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates/n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:98) [github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentHealthy\n/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:276](https://github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentHealthy/n/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:276) [github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).init\n/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:171](https://github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).init/n/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:171) [github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Run\n/go/src/github.com/milvus-io/milvus/cmd/components/proxy.go:49](https://github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Run/n/go/src/github.com/milvus-io/milvus/cmd/components/proxy.go:49) [github.com/milvus-io/milvus/cmd/components.(*Proxy).Run\n](https://github.com/milvus-io/milvus/cmd/components.(*Proxy).Run/n)"] [stack="[github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:254\ngithub.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).GetComponentStates\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:111\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:59\ngithub.com/milvus-io/milvus/internal/util/retry.Do\n\t/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:34\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:83\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentHealthy\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:98\ngithub.com/milvus-io/milvus/internal/distributed/proxy.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:276\ngithub.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:171\ngithub.com/milvus-io/milvus/cmd/components.(*Proxy).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/proxy.go:49\ngithub.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runProxy.func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:147](https://github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall/n/t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:254/ngithub.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).GetComponentStates/n/t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:111/ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1/n/t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:59/ngithub.com/milvus-io/milvus/internal/util/retry.Do/n/t/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:34/ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates/n/t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:83/ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentHealthy/n/t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:98/ngithub.com/milvus-io/milvus/internal/distributed/proxy.(*Server).init/n/t/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:276/ngithub.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Run/n/t/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:171/ngithub.com/milvus-io/milvus/cmd/components.(*Proxy).Run/n/t/go/src/github.com/milvus-io/milvus/cmd/components/proxy.go:49/ngithub.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runProxy.func1/n/t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:147)"]

**Comment by yanliang567** [comment]
@yhmo did it repro on v2.0.2?

**Comment by xiaofan-luan** [comment]
It is due to pulsar failure recovery is slower than milvus.

Let's see if we can import pulsarctl and do something

**Comment by nasen23** [comment]
Hello devs. I've already upgraded my milvus cluster to the lastest helm chart, which is 3.1.9. But this issue still persists. 

The datanode keeps crashing with this consumer busy error. I don't know if this issue is already fixed or is related to the error posted here.

BTW, if there is any workaround for this issue, please let me know. We are using this milvus cluster in production. Would be deeply appreciated. 

```
time="2022-09-08T03:42:18Z" level=info msg="[Connected consumer]" consumerID=3933 name=wfxiy subscription=by-dev-dataNode-516-435735412869169153 topic="persistent://public/default/by-dev-rootcoord-dml_165"
time="2022-09-08T03:42:18Z" level=info msg="[Reconnected consumer to broker]" consumerID=3933 name=wfxiy subscription=by-dev-dataNode-516-435735412869169153 topic="persistent://public/default/by-dev-rootcoord-dml_165"
[2022/09/08 03:42:18.778 +00:00] [INFO] [msgstream/mq_msgstream.go:893] ["MsgStream seek finished"] [channel=by-dev-rootcoord-dml_165]
time="2022-09-08T03:42:18Z" level=error msg="[Failed to create consumer]" consumerID=4672 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=opqop subscription=by-dev-dataNode-516-435737409659600897 topic="persistent://public/default/by-dev-rootcoord-dml_107"
time="2022-09-08T03:42:18Z" level=error msg="[Failed to create consumer]" consumerID=4672 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=opqop subscription=by-dev-dataNode-516-435737409659600897 topic="persistent://public/default/by-dev-rootcoord-dml_107"
[2022/09/08 03:42:18.779 +00:00] [DEBUG] [retry/retry.go:39] ["retry func failed"] ["retry time"=0] [error="server error: ConsumerBusy: Exclusive consumer is already connected"]
panic: Failed to create consumer by-dev-rootcoord-dml_107, error = All attempts results:
attempt #1:server error: ConsumerBusy: Exclusive consumer is already connected


goroutine 23214 [running]:
github.com/milvus-io/milvus/internal/mq/msgstream.(*MqTtMsgStream).AsConsumerWithPosition(0xc01d28ad00, 0xc08bd3f400, 0x1, 0x1, 0xc02d5bc3f0, 0x26, 0x1)
        /go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_msgstream.go:659 +0x2df
github.com/milvus-io/milvus/internal/mq/msgstream.(*MqTtMsgStream).AsConsumer(0xc01d28ad00, 0xc08bd3f400, 0x1, 0x1, 0xc02d5bc3f0, 0x26)
        /go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_msgstream.go:628 +0x66
github.com/milvus-io/milvus/internal/datanode.newDmInputNode(0x4387230, 0xc06c4d2a80, 0xc080b53260, 0xc0a2fdd540, 0x0, 0x0, 0x0)
        /go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_dmstream_input_node.go:47 +0x2db
github.com/milvus-io/milvus/internal/datanode.(*dataSyncService).initNodes(0xc048628dd0, 0xc09829a680, 0x4387230, 0xc06c4d2a80)
        /go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:266 +0x189a
github.com/milvus-io/milvus/internal/datanode.newDataSyncService(0x4387230, 0xc000109640, 0xc0b025f000, 0xc098c15440, 0x43b7c78, 0xc098c153e0, 0x4377d48, 0xc08b317210, 0x7f57b99c6798, 0xc000e8d230, ...)
        /go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:108 +0x6b4
github.com/milvus-io/milvus/internal/datanode.(*flowgraphManager).addAndStart(0xc000e8d2f0, 0xc00022f200, 0xc09829a680, 0x2, 0x2)
        /go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_manager.go:58 +0x890
github.com/milvus-io/milvus/internal/datanode.(*DataNode).handlePutEvent(0xc00022f200, 0xc0651de100, 0x3, 0x5a58200, 0x2a5a69cca)
        /go/src/github.com/milvus-io/milvus/internal/datanode/data_node.go:376 +0x2cb
github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).retryHandlePutEvent(0xc0069a1700, 0x1, 0xc05c96e870, 0x2d, 0x3, 0xc0651de100)
        /go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:88 +0x118
github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).Run.func1(0xc0069a1700)
        /go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:70 +0x165
created by github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).Run
        /go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:64 +0x3f
```
