### ISSUE TITLE
[Bug]: Index files of compacted segments are not deleted

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#16573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 4690639
- Deployment mode(standalone or cluster): both
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

After segment compacted is completed, the old segments will be cleaned up by gc in `Datacoord`. However the related index files still remain since the `IndexCoord` does not sense the compaction behavior.

### Expected Behavior

After compaction completes, the index file shall be purged when there is no need of it. (Loading progress may still NEED them)

**Comment by wayblink** [comment]
I ’ll look into it
