### ISSUE TITLE
[Bug]: cannot connect to milvus from attu

### ISSUE THREAD

**Issue by pengyuan** [milvus-io/milvus#16575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.2
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): none
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 128GB
- GPU: 64
- Others:
```

### Current Behavior

helm install my-release milvus/milvus --set attu.enabled=true

kubectl port-forward svc/milvus-attu 3000:3000 -n milvus --address=0.0.0.0 &

chrome visit http://ip:3000

![image](https://user-images.githubusercontent.com/2572263/164420143-9cc6608b-effa-4078-bb9b-47806f3c741a.png)

### Expected Behavior

success connect to milvus

**Comment by yanliang567** [comment]
@pengyuan could you please double check whether the milvus service is running? Try to connect milvus with pymilvus sdk?

/assign @pengyuan 
/unassign

**Comment by yanliang567** [comment]
@pengyuan any updates for this issue?
