### ISSUE TITLE
[Bug]: [test-string] string field can exceed the maximum max_length_per_row

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#16584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:xige-16-segcore-load-string-217dba22d-20220420
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.1.0.dev27
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The default maximum value of the string field is 65535.
<img width="1047" alt="截屏2022-04-20 22 53 24" src="https://user-images.githubusercontent.com/34296482/164590492-1587d981-9953-4fac-8fc6-79fb12eb69f2.png">

### Expected Behavior

string field exceeding the default maximum value of 65535 should result in an error

**Comment by DragonDriver** [comment]
already fixed, please update the pymilvus, thx.

**Comment by jingkl** [comment]
Yes, it's fixed, the error reporting statement is not very standard @DragonDriver 
<img width="1267" alt="截屏2022-04-25 10 54 49" src="https://user-images.githubusercontent.com/34296482/165013291-62f1f285-d4fa-4bcc-a612-6c9403a33f7a.png">

**Comment by xige-16** [comment]
The issue should has been fixed, Trouble you check it. @jingkl

**Comment by jingkl** [comment]
pymilvus 2.1.0.dev36
milvus tag： xige-16-segcore-load-string-ea423ac9d-20220429
Fixed, testcase passed
