### ISSUE TITLE
[Bug]: Failed to get segments after loading collection from meta of QueryCoord

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#16602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Now milvus use in-memory percentage to judge whether a collection is fully loaded, this percentage is updated after all LoadSegmentsTask and WatchDmChannelTask done. But updating segments in meta is after this, which causes a request that reads segments in meta after loading collection and before updating segments will fail

### Expected Behavior

The case above should not happen

### Steps To Reproduce

```markdown
1. Load Collection
2. Call GetReplicas() after loading done immediately
```

**Comment by xiaofan-luan** [comment]
@yah01 is this still a issue?

**Comment by yah01** [comment]
> @yah01 is this still a issue?

It's fixed with the changing to the interface of quering segments, which reads segments from meta (for sealed segments) now instead of RPC to all QueryNodes
