### ISSUE TITLE
[Bug]: Group nodes allocation strategy not work as expected

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#16622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220424-b82f6a1a
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.0.dev30
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

system setting:
5 querynode; 3 replicas; 2 shard for collection

replicas info

```
Replica groups:
- Group: <group_id:432742822794756152>, <group_nodes:(8, 8)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_4_432743603181191169v0>, <shard_leader:6>, <shard_nodes:[8]>, Shard: <channel_name:by-dev-rootcoord-dml_5_432743603181191169v1>, <shard_leader:8>, <shard_nodes:[8]>]>
- Group: <group_id:432742822794756151>, <group_nodes:(2, 2)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_4_432743603181191169v0>, <shard_leader:2>, <shard_nodes:[2]>, Shard: <channel_name:by-dev-rootcoord-dml_5_432743603181191169v1>, <shard_leader:2>, <shard_nodes:[2]>]>
- Group: <group_id:432742822794756153>, <group_nodes:(9, 9)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_4_432743603181191169v0>, <shard_leader:9>, <shard_nodes:[9]>, Shard: <channel_name:by-dev-rootcoord-dml_5_432743603181191169v1>, <shard_leader:3>, <shard_nodes:[9]>]>
```
each group only has one querynode to load all shards, then all used querynode are three nodes, two nodes are not getting well used.

### Expected Behavior

suppose 
* querynodes are `QN1`, `QN2`,`QN3`, `QN4`, `QN5`
* shards are `shard_a`, `shard_b`

With the setting `5 querynode; 3 replicas; 2 shard for collection`, the ideal allocation is 
* Group_A have two nodes, each node have a shard QN1 --> shard_a, QN2 --> shard_b
* Group_B have two nodes, each node have a shard QN3 --> shard_a, QN4 --> shard_b
* Group_C have one nodes,  QN5 --> shard_a, shard b

### Steps To Reproduce

```markdown
1. deploy cluster Milvus with 5 querynodes
2. create a collection, insert data, and load with 3 replicas
```

### Anything else?

collection name: utility_cEBrI4uq
log:
[pod_log.zip](https://github.com/milvus-io/milvus/files/8549237/pod_log.zip)

**Comment by congqixia** [comment]
@sunby could you please take a look?
/unassign
/assign @sunby

**Comment by zhuwenxing** [comment]
It works well after this PR https://github.com/milvus-io/pymilvus/pull/960 in pymilvus.

/unassign @sunby 
/assign
