### ISSUE TITLE
[Enhancement]: Add distributed locks for segment references

### ISSUE THREAD

**Issue by xiaocai2333** [milvus-io/milvus#16623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

In some case, indexing or loading failed due to the segment was compressed. See also: #16450 , #16488 . 
So, when a segment is referenced by other components, the segment needs to be locked.
The specific plan is as follows:
For load:
1. When loading, QueryCoord will get recovery info from DataCoord by each partition, DataCoord returns the all segments for the partition. And DataCoord locks these segments when returning result.
2. When QueryCoord records the meta, it needs to change the lock corresponding the segment to its own. And QueryCoord needs to perform the operations of locking segments and recording the meta as a transaction. And when the task of load segment completes, QueryCoord unlocks the segment.
3. DataCoord needs to record the nodeID of QueryCoord and watch QueryCoord's session. When QueryCoord is down, DataCoord needs to remove the lock added by DataCoord for QueryCoord on the segment (step 1).
4. When QueryCoord is restarted, it will re-obtain the segment info form DataCoord. If a segment is compacted when QueryCoord is restarts, it is no longer needs to load. This segment will not be included in the return results received by QueryCoord, and the meta corresponding to the segment will be deleted, and the lock on the segment will also be deleted. 

For index:
1. RootCoord only lists the segments that need to index, and sends these segments to IndexCoord. Then IndexCoord obtain these segments info from DataCoord.  DataCoord locks these segments when returning results. If a segment has been compacted, DataCoord will not return the segment info to IndexCoord, and IndexCoord will not create index on the segment.
2. Similarly, when IndexCoord records the meta, it needs to change the lock corresponding the segment to its own. And IndexCoord needs to perform the operations of locking segments and recording the meta as a transaction. And when the task of creating index completes, IndexCoord unlocks the segment.(same as step 2 for load)
3. DataCoord needs to record the nodeID of IndexCoord and watch IndexCoord's session. When IndexCoord is down, DataCoord needs to remove the lock added by DataCoord for IndexCoord on the segment (step 1). If DataCoord finds that lock was added by IndexCoord, do nothing.(same as step 3 for load)
4. When QueryCoord is restarted, it will re-obtain the segment info form DataCoord. If a segment is compacted when QueryCoord is restarts, it is no longer needs to load. This segment will not be included in the return results received by QueryCoord, and the meta corresponding to the segment will be deleted, and the lock on the segment will also be deleted. (same as step 4 for load)
5. When IndexCoord restarts, the index tasks that are not completed and not in the task queue will be sent to the index tasks in task meta, which will be sent to the task queue.

### Why is this needed?

In some case, indexing or loading failed due to the segment was compressed. See also: #16450 , #16488 .

**Comment by xiaofan-luan** [comment]
when querycoord/indexcoord crash and restart, does it relist segment info?

For instance, if we list segment A,B in the querycoord, and query coordinator hold the lock.
then compaction happend, A,B is compacted to Segment c but not deleted since querycoord hold the lock.
Then query coord crashed, the lock is released by data coord.
Then segment is deleted by data coord.
On querycoord restart, if they retry to load segment A and segmentB, and find the segment A,B not exists, we ignored all tasks.

Then C is node loaded and A,B failed to handle, seems to lost some data on it.

**Comment by xiaocai2333** [comment]
> when querycoord/indexcoord crash and restart, does it relist segment info?
> 
> For instance, if we list segment A,B in the querycoord, and query coordinator hold the lock. then compaction happend, A,B is compacted to Segment c but not deleted since querycoord hold the lock. Then query coord crashed, the lock is released by data coord. Then segment is deleted by data coord. On querycoord restart, if they retry to load segment A and segmentB, and find the segment A,B not exists, we ignored all tasks.
> 
> Then C is node loaded and A,B failed to handle, seems to lost some data on it.

When QueryCoord crash and restarted, it will re-obtain the segment info form DataCoord. So querycoord will get the segment C and load it.  And segment A,B will no longer be loaded.

**Comment by xiaofan-luan** [comment]
> > when querycoord/indexcoord crash and restart, does it relist segment info?
> > For instance, if we list segment A,B in the querycoord, and query coordinator hold the lock. then compaction happend, A,B is compacted to Segment c but not deleted since querycoord hold the lock. Then query coord crashed, the lock is released by data coord. Then segment is deleted by data coord. On querycoord restart, if they retry to load segment A and segmentB, and find the segment A,B not exists, we ignored all tasks.
> > Then C is node loaded and A,B failed to handle, seems to lost some data on it.
> 
> When QueryCoord crash and restarted, it will re-obtain the segment info form DataCoord. So querycoord will get the segment C and load it. And segment A,B will no longer be loaded. And if querycoord hold the lock, it will release by querycoord instead of datacoord.

OK， if segment list is refreshed then it should works~

**Comment by xiaofan-luan** [comment]
looks good to me, please helps on reviewing the design @congqixia @sunby

**Comment by congqixia** [comment]
lgtm.
BTW could you please add the steps when DataCoord crashes and restarts?

**Comment by xiaocai2333** [comment]
The design is update. @xiaofan-luan @congqixia 

CreateIndex
1. RootCoord gets list of flushed segments, filters out the segments that need to be indexed, and then obtains segmentInfo and sends it to IndexCoord . After successfully receiving the resp of IndexCoord, remove the lock.
  1.1 When RootCoord gets flushed segments, DataCoord adds locks on the segments, the lock path is `/root/segmentRefer/segmentID/index` , and the value is the serverID of RootCoord.
  1.2. RootCoord filters segments that need to be indexed, releases locks for segments that do not need to be indexed.
  1.3. For segments that need to be indexed, RootCoord deletes the lock after receiving the response from IndexCoord.
  1.4. After IndexCoord receives the indexing request, it will record the meta in etcd, and then the reference lock of the segment may be released. When the IndexNode builds the index, the binLog file may not be found. In this case, the indexing task will be marked as failed and wait for the restart or delete. (If it is compacted, RootCoord should initiate a drop index request for the compacted segments)
2. DataCoord needs to monitor RootCoord.
  2.1. When RootCoord is disconnected, delete the lock corresponding to the segments held by RootCoord.
    2.1.1. DataCoord needs to traverse all segments, and determine whether the lock is held by the disconnected RootCoord, and determine whether the value of the lock path is consistent with the serverID of the disconnected RootCoord. So DataCoord needs to persist the serverID of RootCoord.
  2.2. When DataCoord is disconnected, it is necessary to judge whether RootCoord is also disconnected during recovery, and if so, delete the segment lock it holds (2.1.1).

Load
1. The logic of Load is the same as CreateIndex. When GetRecoveryInfo, the DataCoord locks segments. When the load is completed, the segment lock is released by QueryCoord.
1.1. When QueryCoord GetRecoveryInfo, DataCoord adds locks on these segments. The lock path is `/root/segmentRefer/segmentID/load`, and the value is the serverID of QueryCoord.
2. When QueryCoord recovers from power failure, if there is a load task, it will obtain segment information from DataCoord again.
  2.1. QueryCoord does not need to lock the segment by itself. After disconnection, DataCoord will remove the lock. 
3. Similarly, DataCoord needs to monitor QueryCoord. When QueryCoord is disconnected, DataCoord needs to help release the lock.
  3.1. When the DataCoord watches the QueryCoord is down, it releases the locks of the segments held by the QueryCoord(for load).
    3.1.1. DataCoord needs to traverse all segments, and determine whether the lock is held by the disconnected QueryCoord, and determine whether the value of the lock path is consistent with the serverID of the disconnected QueryCoord. So DataCoord needs to persist the serverID of QueryCoord.
  3.2. When DataCoord is disconnected, it is also necessary to judge whether QueryCoord has been disconnected during recovery. If so, execute step 3.1.

Replenish the case of a coord is down:

DataCoord needs to watch the QueryCoord and RootCoord.
1. When QueryCoord/RootCoord is down, DataCoord need to release the locks on the segment corresponding the coord.
2. DataCoord will persist the serverID of QueryCoord/RootCoord. When DataCoord is restarted, it is necessary to check whether the QueryCoord/RootCoord has been restarted. If yes, do step 1.

**Comment by xiaocai2333** [comment]
#16412 #16145

**Comment by xiaocai2333** [comment]
pr is merged.
/close
