### ISSUE TITLE
[Feature]: detailed scripts to deploy  milvus2.0 offline

### ISSUE THREAD

**Issue by yearlz** [milvus-io/milvus#16634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

as a  beginner to  milvus , it confused me when i wanted to apply ingress 、persistance Volume to milvus2.0  in offline deployment mode, according tohttps://milvus.io/cn/docs/v2.0.x/install_offline-helm.md, i can get the "milvus_manifest.yaml" , however, i didn't know how to edit the yml file to apply new features to milvus2.0 offline, so can you show me how to apply new feature to deploy milvus2.0 offline?

**Comment by xiaofan-luan** [comment]
/assgin @zwd1208 could you please help @yearlz for the documents?

**Comment by Bennu-Li** [comment]
To update the `milvus_manifest.yaml` for Milvus new features, you need to update the milvus helm repo. Just use `helm repo update`.

**Comment by yearlz** [comment]
thanks，it helps a lot
