### ISSUE TITLE
[Bug]: Hit no shard leaders available for channel on ci

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#16633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

While search, we hit no shard leaders error, which is unexpected.

Detailed logs please check
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-16624/4/pipeline

### Expected Behavior

search successfully

**Comment by binbinlv** [comment]
Actually, this is reproduced frequently, and we comment on issue #16562.

**Comment by xiaofan-luan** [comment]
duplicate with #16562, close for now
