### ISSUE TITLE
[Bug]: milvus 2.0.2 standalone crash

### ISSUE THREAD

**Issue by RateSpirit** [milvus-io/milvus#16638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.2
- Deployment mode(standalone):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

docker restart logs:
[docker.logs.txt](https://github.com/milvus-io/milvus/files/8552406/docker.logs.txt)
milvus restart logs:
[standalone-9.log](https://github.com/milvus-io/milvus/files/8552424/standalone-9.log)

**Comment by yanliang567** [comment]
@RateSpirit thank you for the issue.  could you please specify what did you do before milvus crash?
Looking into the logs, it seems that the rootcoord is not working. could you please double check the etcd server is running well?

/assign @RateSpirit 
/unassign

**Comment by RateSpirit** [comment]
> @RateSpirit谢谢你的问题。你能具体说明一下在 milvus 崩溃之前你做了什么吗？ 查看日志，rootcoord 似乎无法正常工作。请您仔细检查一下 etcd 服务器是否运行良好？
> 
> /分配@RateSpirit /取消分配
[standalone-1.log](https://github.com/milvus-io/milvus/files/8552731/standalone-1.log)

**Comment by RateSpirit** [comment]
> > @RateSpirit谢谢你的问题。你能具体说明一下在 milvus 崩溃之前你做了什么吗？ 查看日志，rootcoord 似乎无法正常工作。请您仔细检查一下 etcd 服务器是否运行良好？
> > /分配@RateSpirit /取消分配
> > [standalone-1.log](https://github.com/milvus-io/milvus/files/8552731/standalone-1.log)
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/11364643/165051421-83ab1b34-c68d-4abd-8cc7-67b543255ffc.png">

**Comment by xiaofan-luan** [comment]
reloadFromKV: taskStateInfo and triggerTaskInfo are inconsistent

**Comment by xiaofan-luan** [comment]
standalone-1.log seems to have cleared infomatiton,

The root cause is SaveBinlogPaths can not work on etcd  with request too large

request is too large","stack":"github.com/milvus-io/milvus/internal/datacoord.(*Server).SaveBinlogPaths\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/services.go:355\ngithub.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).SaveBinlogPaths\

**Comment by xiaofan-luan** [comment]
@sunby please help on it, thanks~

**Comment by sunby** [comment]
@RateSpirit Hi, would you please provide the log file where the first crash occured? And which log level did you enable? It will be very helpful if you can upload the whole log file before the first crash.
