### ISSUE TITLE
[Bug]: Search result does not match topK required

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#16631]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I've hit this issue on ci

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-16618/2/pipeline

Guess that might be related to recently check in of QueryNode

### Expected Behavior

result size should match topk user expected

**Comment by binbinlv** [comment]
this is the same with issue #16564 and the issues comments on 16564.

**Comment by xiaofan-luan** [comment]
sorry for the duplication, close it for now ,see #16564
