### ISSUE TITLE
PQ index parameter 'm' validation

### ISSUE THREAD

**Issue by ReactiveCJ** [milvus-io/milvus#1663]
**Describe the bug**
PQ can set m not in  {96, 64, 56, 48, 40, 32, 28, 24, 20, 16, 12, 8, 4, 3, 2, 1} , for interface, it doesn't report the error. 
inv_param = {'nlist': 4, 'm': 5}
milvus.create_index(collection_name=collection_name, index_type=IndexType.IVF_PQ, params=inv_param)
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)
CPU, MacOS, Docker, v0.7.0 
**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
Fixed by pr1677
