### ISSUE TITLE
[Bug]: Failed to connecting 19530 on ci cases

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#16630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I've seen many CI runs hit this issue
For example:

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-16604/5/pipeline

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-16624/2/pipeline/

Need to investigate the core reason why ci failed

### Expected Behavior

ci passed successfully

**Comment by binbinlv** [comment]
this is the same with #15282

**Comment by xiaofan-luan** [comment]
dupliacate with #15282
