### ISSUE TITLE
Mishards is used for distributed cluster deployment and data query. In most cases, it returns, and sometimes it returns an empty list[]

### ISSUE THREAD

**Issue by AI-Mart** [milvus-io/milvus#16643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:1.1.2
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 1.1.2
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: T4 16G
- Others:
```

### Current Behavior

Mishards is used for distributed cluster deployment and data query. In most cases, it returns, and sometimes it returns an empty list[]

### Expected Behavior

Mishards is used for distributed cluster deployment and data query. In most cases, it returns, and sometimes it returns an empty list[]

### Steps To Reproduce

```markdown
collection_param = {
    'dimension': 256,
    'index_file_size': 256,
    'metric_type': MetricType.IP
}

index_type = IndexType.IVF_FLAT
index_param = {'nlist': 1024}

top_k = 5
search_param = {'nprobe': 32}
```

### Anything else?

 ```
   def simi_search(self, index, description, category, collection_name,
                    partition_tag, redis_key_id2index, redis_key_index2cat, top_k):
        """
        semantic index
        """
        text = re.sub(r'\s', '', description)
        feed = {'0': text}
        ret = self.client.predict(feed_dict=feed)
        embeddings = eval(ret.value[0])  # 是二维数组
        embeddings = preprocessing.normalize(embeddings, norm='l2')
        status, results = self.vec_to_milvus.search(
            collection_name=collection_name,
            vectors=embeddings.tolist(),
            partition_tag=partition_tag,
            top_k_=top_k)

        result_dict = dict()
        result_dict['current_id'] = index
        result_dict['similar_id_list'] = []
        if results:
            for idx, distance_idx in enumerate(results[0]):
                event_id = self.connect_database_redis.h_get(redis_key_id2index, distance_idx.id)
                event_cat = self.connect_database_redis.h_get(redis_key_index2cat, event_id)
                if category == event_cat and event_id != index:
                    result_dict['similar_id_list'].append({event_id: distance_idx.distance})
            return [embeddings.tolist(), result_dict, 0]
        return [embeddings.tolist(), results, result_dict, 1]
```

 ```
  def search(self, vectors, collection_name, partition_tag=None, top_k_=top_k):
        try:
            status, results = self.client.search(
                collection_name=collection_name,
                query_records=vectors,
                top_k=top_k_,
                params=search_param,
                partition_tag=partition_tag)
            # print(status)
            return status, results
        except Exception as e:
            print('Milvus recall error: ', e)
```

**Comment by JackLCL** [comment]
@AI-Mart 
Please upload milvus log to help analyze this problem.

**Comment by AI-Mart** [comment]
无返回
`[[[-0.10037688668711754, 0.015197261066547809, -0.07836079244940561, 0.04032146760144152, 0.003124489605476766, -0.029799604418501484, -0.03967552830836387, -0.05514469273948117, 0.02804241097372762, -0.074425708505379, 0.06932036180837266, 0.11507123540082621, 0.09609857682953954, -0.0125929561232442, 0.06169842120121105, -0.059517785162870804, 0.05293207135703611, 0.005886257455309844, 0.05454757710350085, -0.06294586824775092, -0.08444276129997776, -0.01693439009676909, -0.015916877292193918, -0.06154285307055456, -0.11182535999886133, 0.021009313995024245, 0.08692140567596163, 0.10459295439127102, -0.026343540676788003, -0.007043382040071341, -0.08040196851314681, 0.0026085312853589204, -0.025199980806005266, 0.007550235750243678, 0.056076998837436595, -0.050538721231998394, -0.06220808936834486, -0.04796995462859973, -0.0990173791774963, 0.03455503085495476, 0.0666093487130921, -0.02829541221437587, 0.047037283452176774, -0.032455293224788274, 0.06436009282401686, -0.10230041807734025, -0.10229245340628317, 0.028894081296488468, -0.07832315211434447, 0.07147515923190847, -0.04275443246549746, -0.058191313529271156, 0.1265918377869419, 0.048931645817901374, -0.04056523198433204, -0.06237379028912075, -0.07087529060625967, -0.06921298403543102, -0.024957509098913064, -0.14504151772819165, 0.012435064342647639, -0.06809717757876205, 0.025997135227807607, 0.009846665458392655, 0.0160708901140729, 0.044035183608973856, 0.1034816257337651, 0.06066416880384122, 0.0017188551998234092, 0.033139573207538256, -0.005980667492072959, -0.023762279449102412, 0.06165670539835925, 0.021322229082543866, -0.023801897913411127, -0.0342733765425406, 0.014374093872610847, 0.08788157694674537, -0.04771148652416464, 0.02057293533024845, -0.062314029179159264, -0.09568660440537667, -0.07882891245175944, 0.0013421815328211694, -0.04131061045632765, -0.04990699392212129, 0.06000677796781247, -0.04947105670426798, 0.08654182837785693, -0.08877079633495047, 0.0005435167967654495, -0.003023098141513976, -0.17469839136704818, 0.043464543612470916, 0.061848542957178385, -0.02879139366426753, -0.05125554535242594, 0.030569709506091735, 0.06132546374429833, -0.008547382857398285, -0.1610474071112358, -0.1507680342618404, -0.12831131266555446, -0.12055524297447792, 0.08161771706294922, 0.016062530562224404, -0.023834242748047744, -0.059430035945494994, 0.07027066850995194, -0.08540755193096299, 0.046399021982788856, -0.04483978674910109, -0.007089333963865984, 0.029082120921658076, -0.09676720686696175, -0.03552387832727823, -0.05183600893993801, 0.025574866100744015, 0.05448906769114235, 0.07500241327479162, -0.0937879654061752, -0.055535878042737345, -0.07691092429377852, 0.05568407754881438, -0.001299031143886627, 0.06435912424849075, 0.018702932639005715, 0.07794899883918603, 0.04728078333944285, 0.13656049160755865, -0.041103715273367855, -0.1102996523795392, 0.04268355136343805, -0.07818989847369354, 0.09020443712522459, -0.0688829381996158, -0.007795391994791682, 0.0228831667739833, 0.02383253842765082, 0.05253849069199804, 0.08589957339706901, -0.07552157720737188, -0.05377050386005827, -0.03193544011346829, 0.03600314812405386, 0.051833825919713764, -0.07983932299002483, 0.018443609580404304, -0.02408401602449068, 0.04092961382254814, 0.05186643711262006, 0.07674464222768697, 0.035738056453136324, -0.03550750940088683, 0.01861666422459772, -0.006816025233461, 0.030022596581647253, 0.02044032989014192, 0.02550180197846035, -0.07394632322459832, -0.046997236579462275, 0.006714280099732783, -0.046991618841410794, -0.01165045763052163, -0.08902229069559751, 0.022010441109400838, -0.07375751060165306, -0.08471604115938149, -0.004571628054500921, 0.08773556046089258, 0.07382794094356378, -0.02723016540017026, 0.11267906246758179, 0.005274491648835671, -0.05945671275065857, -0.020508702009059642, -0.04430519266333169, -0.04847643022178783, 0.13432932572907894, 0.03946637187407965, 0.05272725116087651, -0.02452341217455938, -0.025224534195592358, -0.040432507334929986, -0.034102348456371064, -0.037072157481649395, -0.013432356270469853, -0.08674856709861634, -0.0025969891712828985, 0.18834857096011576, 0.024639346939745222, 0.0731406173984875, 0.01704382423005849, 0.023737139326263923, 0.04075715522483233, 0.02679011359897619, -0.12722792368668656, 0.08080516415292684, -0.1333187289262893, 0.06411952101507205, -0.020286941054419184, 0.006011479369674969, -0.07536806543706313, -0.009187565645353878, 0.004710865442993498, 0.08144285937816104, 0.01524055173595218, -0.0025689384324222913, 0.06609837296899804, 0.01283507392774032, -0.09591283384595398, -0.03629389959583257, -0.07596838109757013, 0.03206186902195057, -0.0003272320773457088, -0.0028910102839542133, -0.007806592080635042, -0.0028702266555073555, -0.042710541093002374, 0.12055011697477047, 0.051299999243784276, 0.009984168724164431, -0.041980514543095745, 0.012812443719366143, -0.015497679667135264, 0.12354564540555772, -0.0670544464202482, 0.041788226224127915, 0.0936518358412698, 0.03158738249815777, 0.03789669837645272, 0.09887969244116813, 0.01840688566680249, 0.056051763719690735, -0.003855422565124549, 0.023850285711521695, -0.0946241962625207, 0.04273724770048984, 0.06836471304023779, -0.004764730349439738, 0.09251440779862549, -0.1255392942132904, -0.04715502870853836, 0.052503439433824024, 0.007835149226170963, 0.058784364873332266, 0.028786304917464926, 0.02630275247126698, -0.017609334501563486, 0.03358677570381842, -0.0053022455286107495, -0.04199390323709908, 0.0519658800168285, 0.028561608433922234, -0.023315555652649582, 0.011331915491724312]], [], {"current_id": "202204241638000042", "similar_id_list": []}, 1]

有返回
[[[-0.10037688668711754, 0.015197261066547809, -0.07836079244940561, 0.04032146760144152, 0.003124489605476766, -0.029799604418501484, -0.03967552830836387, -0.05514469273948117, 0.02804241097372762, -0.074425708505379, 0.06932036180837266, 0.11507123540082621, 0.09609857682953954, -0.0125929561232442, 0.06169842120121105, -0.059517785162870804, 0.05293207135703611, 0.005886257455309844, 0.05454757710350085, -0.06294586824775092, -0.08444276129997776, -0.01693439009676909, -0.015916877292193918, -0.06154285307055456, -0.11182535999886133, 0.021009313995024245, 0.08692140567596163, 0.10459295439127102, -0.026343540676788003, -0.007043382040071341, -0.08040196851314681, 0.0026085312853589204, -0.025199980806005266, 0.007550235750243678, 0.056076998837436595, -0.050538721231998394, -0.06220808936834486, -0.04796995462859973, -0.0990173791774963, 0.03455503085495476, 0.0666093487130921, -0.02829541221437587, 0.047037283452176774, -0.032455293224788274, 0.06436009282401686, -0.10230041807734025, -0.10229245340628317, 0.028894081296488468, -0.07832315211434447, 0.07147515923190847, -0.04275443246549746, -0.058191313529271156, 0.1265918377869419, 0.048931645817901374, -0.04056523198433204, -0.06237379028912075, -0.07087529060625967, -0.06921298403543102, -0.024957509098913064, -0.14504151772819165, 0.012435064342647639, -0.06809717757876205, 0.025997135227807607, 0.009846665458392655, 0.0160708901140729, 0.044035183608973856, 0.1034816257337651, 0.06066416880384122, 0.0017188551998234092, 0.033139573207538256, -0.005980667492072959, -0.023762279449102412, 0.06165670539835925, 0.021322229082543866, -0.023801897913411127, -0.0342733765425406, 0.014374093872610847, 0.08788157694674537, -0.04771148652416464, 0.02057293533024845, -0.062314029179159264, -0.09568660440537667, -0.07882891245175944, 0.0013421815328211694, -0.04131061045632765, -0.04990699392212129, 0.06000677796781247, -0.04947105670426798, 0.08654182837785693, -0.08877079633495047, 0.0005435167967654495, -0.003023098141513976, -0.17469839136704818, 0.043464543612470916, 0.061848542957178385, -0.02879139366426753, -0.05125554535242594, 0.030569709506091735, 0.06132546374429833, -0.008547382857398285, -0.1610474071112358, -0.1507680342618404, -0.12831131266555446, -0.12055524297447792, 0.08161771706294922, 0.016062530562224404, -0.023834242748047744, -0.059430035945494994, 0.07027066850995194, -0.08540755193096299, 0.046399021982788856, -0.04483978674910109, -0.007089333963865984, 0.029082120921658076, -0.09676720686696175, -0.03552387832727823, -0.05183600893993801, 0.025574866100744015, 0.05448906769114235, 0.07500241327479162, -0.0937879654061752, -0.055535878042737345, -0.07691092429377852, 0.05568407754881438, -0.001299031143886627, 0.06435912424849075, 0.018702932639005715, 0.07794899883918603, 0.04728078333944285, 0.13656049160755865, -0.041103715273367855, -0.1102996523795392, 0.04268355136343805, -0.07818989847369354, 0.09020443712522459, -0.0688829381996158, -0.007795391994791682, 0.0228831667739833, 0.02383253842765082, 0.05253849069199804, 0.08589957339706901, -0.07552157720737188, -0.05377050386005827, -0.03193544011346829, 0.03600314812405386, 0.051833825919713764, -0.07983932299002483, 0.018443609580404304, -0.02408401602449068, 0.04092961382254814, 0.05186643711262006, 0.07674464222768697, 0.035738056453136324, -0.03550750940088683, 0.01861666422459772, -0.006816025233461, 0.030022596581647253, 0.02044032989014192, 0.02550180197846035, -0.07394632322459832, -0.046997236579462275, 0.006714280099732783, -0.046991618841410794, -0.01165045763052163, -0.08902229069559751, 0.022010441109400838, -0.07375751060165306, -0.08471604115938149, -0.004571628054500921, 0.08773556046089258, 0.07382794094356378, -0.02723016540017026, 0.11267906246758179, 0.005274491648835671, -0.05945671275065857, -0.020508702009059642, -0.04430519266333169, -0.04847643022178783, 0.13432932572907894, 0.03946637187407965, 0.05272725116087651, -0.02452341217455938, -0.025224534195592358, -0.040432507334929986, -0.034102348456371064, -0.037072157481649395, -0.013432356270469853, -0.08674856709861634, -0.0025969891712828985, 0.18834857096011576, 0.024639346939745222, 0.0731406173984875, 0.01704382423005849, 0.023737139326263923, 0.04075715522483233, 0.02679011359897619, -0.12722792368668656, 0.08080516415292684, -0.1333187289262893, 0.06411952101507205, -0.020286941054419184, 0.006011479369674969, -0.07536806543706313, -0.009187565645353878, 0.004710865442993498, 0.08144285937816104, 0.01524055173595218, -0.0025689384324222913, 0.06609837296899804, 0.01283507392774032, -0.09591283384595398, -0.03629389959583257, -0.07596838109757013, 0.03206186902195057, -0.0003272320773457088, -0.0028910102839542133, -0.007806592080635042, -0.0028702266555073555, -0.042710541093002374, 0.12055011697477047, 0.051299999243784276, 0.009984168724164431, -0.041980514543095745, 0.012812443719366143, -0.015497679667135264, 0.12354564540555772, -0.0670544464202482, 0.041788226224127915, 0.0936518358412698, 0.03158738249815777, 0.03789669837645272, 0.09887969244116813, 0.01840688566680249, 0.056051763719690735, -0.003855422565124549, 0.023850285711521695, -0.0946241962625207, 0.04273724770048984, 0.06836471304023779, -0.004764730349439738, 0.09251440779862549, -0.1255392942132904, -0.04715502870853836, 0.052503439433824024, 0.007835149226170963, 0.058784364873332266, 0.028786304917464926, 0.02630275247126698, -0.017609334501563486, 0.03358677570381842, -0.0053022455286107495, -0.04199390323709908, 0.0519658800168285, 0.028561608433922234, -0.023315555652649582, 0.011331915491724312]], {"current_id": "202204241638000042", "similar_id_list": [{"202204251659000051": 0.05485381558537483}, {"202204241618000041": -0.20339015126228333}]}, 0]

`

**Comment by JackLCL** [comment]
We need the log of milvus server not the log from the client.

**Comment by yanliang567** [comment]
@AI-Mart could you please to upload the milvus server logs?
/assign @AI-Mart 
/unassign
