### ISSUE TITLE
[Bug]: [embd] Package directory is wrong on readme of embd-milvus

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#16645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: NA
- Deployment mode(standalone or cluster):NA
- SDK version(e.g. pymilvus v2.0.0rc2):NA
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Package directory is wrong:
milvus.py is deleted, and preload.py is not on readme.

### Expected Behavior

delete milvus.py and add preload.py on readme

### Steps To Reproduce

```markdown
https://github.com/milvus-io/embd-milvus
```

**Comment by soothing-rain** [comment]
done.
