### ISSUE TITLE
[Bug]: [chaos]Search failed with two replicas when one group is available, but another one is not

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#16644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220424-5c663004
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.0.dev33
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior
Search works well in the first assert but raises errors in the second assert.
```
[2022-04-25 16:55:03 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=no shard leaders available for channel: by-dev-rootcoord-dml_1_432767386375097665v1, leaders: [8 9], err: fail to Search, QueryNode ID=9, reason=SharcCluster for by-dev-rootcoord-dml_1_432767386375097665v1 replicaID 432767088036937731 is no available)>, <Time:{'RPC start': '2022-04-25 16:55:03.240156', 'RPC error': '2022-04-25 16:55:03.429824'}> (decorators.py:73)
```
after this chaos test, the load operation will timeout for any other collections, even if they are created after chaos.
```
[2022-04-25 17:05:43 - ERROR - pymilvus.decorators]: grpc RpcError: [load_collection], <_MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2022-04-25 17:05:23.598932', 'gRPC error': '2022-04-25 17:05:43.603717'}> (decorators.py:81)
[2022-04-25 17:06:04 - ERROR - pymilvus.decorators]: grpc RpcError: [load_collection], <_MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2022-04-25 17:05:44.608748', 'gRPC error': '2022-04-25 17:06:04.612788'}> (decorators.py:81)
[2022-04-25 17:06:25 - ERROR - pymilvus.decorators]: grpc RpcError: [load_collection], <_MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2022-04-25 17:06:05.618389', 'gRPC error': '2022-04-25 17:06:25.623273'}> (decorators.py:81)
[2022-04-25 17:06:25 - ERROR - ci_test]: Traceback (most recent call last):
```

### Expected Behavior

When we have multi replicas, search should still work when one of replicas is not available

### Steps To Reproduce

```markdown
1. deploy Milvus with 5 querynode
2. init a collection, insert data, load with 2 replicas, and search
3. first assert: expect all search requests success
4. inject pod failure to one querynode, then one group is not available
5. second assert: expect all search requests success because there is still one group can offer service
6. delete chaos and wait querynode ready
7. third assert: expect all search requests success
```

### Anything else?

log: 
[test-multi-replicas-04-25-17-20.zip](https://github.com/milvus-io/milvus/files/8553266/test-multi-replicas-04-25-17-20.zip)

**Comment by zhuwenxing** [comment]
So this issue has two effects:
* can't promise HA when loading multi replicas
* Milvus can not recover after the chaos is deleted  when loading multi replicas

**Comment by xiaofan-luan** [comment]
probably mark it as a new feature?

**Comment by xiaofan-luan** [comment]
so far it's by design, by we can have blacklist and hedged read as a new feature

**Comment by yanliang567** [comment]
> so far it's by design, by we can have blacklist and hedged read as a new feature

don't we assign the request to the other replica group if on is offline?

/assign @xiaofan-luan 
/unassign

**Comment by xiaofan-luan** [comment]
> > so far it's by design, by we can have blacklist and hedged read as a new feature
> 
> don't we assign the request to the other replica group if on is offline?
> 
> /assign @xiaofan-luan /unassign

It's harder to do so because it usually takes a long time to know a replica is not working.
One thing could help is to init shard replica latency tracker, if certain replica response is higher than others, or if it didn't response for the last n request, then we blacklist the replica.
Other way to help on the avalaibility is called Hedged read, see mongodb documentation about the details of hedged read https://www.mongodb.com/docs/manual/core/read-preference-hedge-option/

**Comment by zhuwenxing** [comment]
@XuanYang-cn please take a look.

server log:
[test-multi-replicas-04-26-14-05.zip](https://github.com/milvus-io/milvus/files/8560317/test-multi-replicas-04-26-14-05.zip)

client log:
[client_log.log](https://github.com/milvus-io/milvus/files/8560319/client_log.log)

before chaos
```
[2022-04-26 11:58:44,630 - INFO - ci_test]: replicas_info for collection Checker__z4Sv1na3: Replica groups:
- Group: <group_id:432785403215872003>, <group_nodes:(2, 7)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_432785455185395713v0>, <shard_leader:2>, <shard_nodes:[2, 7]>, Shard: <channel_name:by-dev-rootcoord-dml_1_432785455185395713v1>, <shard_leader:7>, <shard_nodes:[7, 2]>]>
- Group: <group_id:432785403215872002>, <group_nodes:(1, 6, 8)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_432785455185395713v0>, <shard_leader:8>, <shard_nodes:[8, 1]>, Shard: <channel_name:by-dev-rootcoord-dml_1_432785455185395713v1>, <shard_leader:1>, <shard_nodes:[1]>]> (test_chaos_multi_replicas.py:188)
```

during chaos
```
[2022-04-26 12:01:05,020 - INFO - ci_test]: replicas_info for collection Checker__z4Sv1na3: Replica groups:
- Group: <group_id:432785403215872002>, <group_nodes:(1, 6, 8)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_432785455185395713v0>, <shard_leader:8>, <shard_nodes:[8, 1]>, Shard: <channel_name:by-dev-rootcoord-dml_1_432785455185395713v1>, <shard_leader:1>, <shard_nodes:[1]>]>
- Group: <group_id:432785403215872003>, <group_nodes:(2, 7, 13)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_432785455185395713v0>, <shard_leader:2>, <shard_nodes:[2, 7]>, Shard: <channel_name:by-dev-rootcoord-dml_1_432785455185395713v1>, <shard_leader:7>, <shard_nodes:[7, 2]>]> (test_chaos_multi_replicas.py:212)
```
after chaos

```
[2022-04-26 12:03:48,465 - INFO - ci_test]: replicas_info for collection Checker__z4Sv1na3: Replica groups:
- Group: <group_id:432785403215872002>, <group_nodes:(1, 6, 8)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_432785455185395713v0>, <shard_leader:8>, <shard_nodes:[8, 1]>, Shard: <channel_name:by-dev-rootcoord-dml_1_432785455185395713v1>, <shard_leader:1>, <shard_nodes:[1]>]>
- Group: <group_id:432785403215872003>, <group_nodes:(2, 7, 13)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_432785455185395713v0>, <shard_leader:2>, <shard_nodes:[2, 7]>, Shard: <channel_name:by-dev-rootcoord-dml_1_432785455185395713v1>, <shard_leader:7>, <shard_nodes:[7, 2]>]> (test_chaos_multi_replicas.py:242)
```

**Comment by zhuwenxing** [comment]
Here is a new question: why a new querynode id `13` is in gruop_nodes?
```
<group_nodes:(1, 6, 8)>
<group_nodes:(2, 7, 13)>
```

```
milvus-multi-querynode-querycoord-86949bcbdb-nz7wx                1/1     Running     0          157m
milvus-multi-querynode-querynode-7fd9f6666-dzx9k                  1/1     Running     0          157m
milvus-multi-querynode-querynode-7fd9f6666-mwrsp                  1/1     Running     2          157m
milvus-multi-querynode-querynode-7fd9f6666-vr464                  1/1     Running     0          157m
milvus-multi-querynode-querynode-7fd9f6666-wvw68                  1/1     Running     0          157m
milvus-multi-querynode-querynode-7fd9f6666-z7p5z                  1/1     Running     0          157m
milvus-multi-querynode-rootcoord-768b86b754-9wjst                 1/1     Running     0          157m
```
As we can see, the total number of querynode is  5. The chaos is pod failure, so there will be no querynode getting online or offline. The effect of chaos is just making `milvus-multi-querynode-querynode-7fd9f6666-mwrsp` not be ready, and restarting.

**Comment by yah01** [comment]
> @XuanYang-cn please take a look. /assign @XuanYang-cn
> 
> A new try with `master-20220426-80ae6de3` server log: [test-multi-replicas-04-26-14-05.zip](https://github.com/milvus-io/milvus/files/8560317/test-multi-replicas-04-26-14-05.zip)
> 
> client log: [client_log.log](https://github.com/milvus-io/milvus/files/8560319/client_log.log)
> 
> before chaos
> 
> ```
> [2022-04-26 11:58:44,630 - INFO - ci_test]: replicas_info for collection Checker__z4Sv1na3: Replica groups:
> - Group: <group_id:432785403215872003>, <group_nodes:(2, 7)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_432785455185395713v0>, <shard_leader:2>, <shard_nodes:[2, 7]>, Shard: <channel_name:by-dev-rootcoord-dml_1_432785455185395713v1>, <shard_leader:7>, <shard_nodes:[7, 2]>]>
> - Group: <group_id:432785403215872002>, <group_nodes:(1, 6, 8)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_432785455185395713v0>, <shard_leader:8>, <shard_nodes:[8, 1]>, Shard: <channel_name:by-dev-rootcoord-dml_1_432785455185395713v1>, <shard_leader:1>, <shard_nodes:[1]>]> (test_chaos_multi_replicas.py:188)
> ```
> 
> during chaos
> 
> ```
> [2022-04-26 12:01:05,020 - INFO - ci_test]: replicas_info for collection Checker__z4Sv1na3: Replica groups:
> - Group: <group_id:432785403215872002>, <group_nodes:(1, 6, 8)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_432785455185395713v0>, <shard_leader:8>, <shard_nodes:[8, 1]>, Shard: <channel_name:by-dev-rootcoord-dml_1_432785455185395713v1>, <shard_leader:1>, <shard_nodes:[1]>]>
> - Group: <group_id:432785403215872003>, <group_nodes:(2, 7, 13)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_432785455185395713v0>, <shard_leader:2>, <shard_nodes:[2, 7]>, Shard: <channel_name:by-dev-rootcoord-dml_1_432785455185395713v1>, <shard_leader:7>, <shard_nodes:[7, 2]>]> (test_chaos_multi_replicas.py:212)
> ```
> 
> after chaos
> 
> ```
> [2022-04-26 12:03:48,465 - INFO - ci_test]: replicas_info for collection Checker__z4Sv1na3: Replica groups:
> - Group: <group_id:432785403215872002>, <group_nodes:(1, 6, 8)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_432785455185395713v0>, <shard_leader:8>, <shard_nodes:[8, 1]>, Shard: <channel_name:by-dev-rootcoord-dml_1_432785455185395713v1>, <shard_leader:1>, <shard_nodes:[1]>]>
> - Group: <group_id:432785403215872003>, <group_nodes:(2, 7, 13)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_432785455185395713v0>, <shard_leader:2>, <shard_nodes:[2, 7]>, Shard: <channel_name:by-dev-rootcoord-dml_1_432785455185395713v1>, <shard_leader:7>, <shard_nodes:[7, 2]>]> (test_chaos_multi_replicas.py:242)
> ```

This was fixed with #16653 (60f7fef），which is newer than the tested commit.

**Comment by zhuwenxing** [comment]
> > @XuanYang-cn please take a look. /assign @XuanYang-cn
> > A new try with `master-20220426-80ae6de3` server log: [test-multi-replicas-04-26-14-05.zip](https://github.com/milvus-io/milvus/files/8560317/test-multi-replicas-04-26-14-05.zip)
> > client log: [client_log.log](https://github.com/milvus-io/milvus/files/8560319/client_log.log)
> > before chaos
> > ```
> > [2022-04-26 11:58:44,630 - INFO - ci_test]: replicas_info for collection Checker__z4Sv1na3: Replica groups:
> > - Group: <group_id:432785403215872003>, <group_nodes:(2, 7)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_432785455185395713v0>, <shard_leader:2>, <shard_nodes:[2, 7]>, Shard: <channel_name:by-dev-rootcoord-dml_1_432785455185395713v1>, <shard_leader:7>, <shard_nodes:[7, 2]>]>
> > - Group: <group_id:432785403215872002>, <group_nodes:(1, 6, 8)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_432785455185395713v0>, <shard_leader:8>, <shard_nodes:[8, 1]>, Shard: <channel_name:by-dev-rootcoord-dml_1_432785455185395713v1>, <shard_leader:1>, <shard_nodes:[1]>]> (test_chaos_multi_replicas.py:188)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > during chaos
> > ```
> > [2022-04-26 12:01:05,020 - INFO - ci_test]: replicas_info for collection Checker__z4Sv1na3: Replica groups:
> > - Group: <group_id:432785403215872002>, <group_nodes:(1, 6, 8)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_432785455185395713v0>, <shard_leader:8>, <shard_nodes:[8, 1]>, Shard: <channel_name:by-dev-rootcoord-dml_1_432785455185395713v1>, <shard_leader:1>, <shard_nodes:[1]>]>
> > - Group: <group_id:432785403215872003>, <group_nodes:(2, 7, 13)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_432785455185395713v0>, <shard_leader:2>, <shard_nodes:[2, 7]>, Shard: <channel_name:by-dev-rootcoord-dml_1_432785455185395713v1>, <shard_leader:7>, <shard_nodes:[7, 2]>]> (test_chaos_multi_replicas.py:212)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > after chaos
> > ```
> > [2022-04-26 12:03:48,465 - INFO - ci_test]: replicas_info for collection Checker__z4Sv1na3: Replica groups:
> > - Group: <group_id:432785403215872002>, <group_nodes:(1, 6, 8)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_432785455185395713v0>, <shard_leader:8>, <shard_nodes:[8, 1]>, Shard: <channel_name:by-dev-rootcoord-dml_1_432785455185395713v1>, <shard_leader:1>, <shard_nodes:[1]>]>
> > - Group: <group_id:432785403215872003>, <group_nodes:(2, 7, 13)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_432785455185395713v0>, <shard_leader:2>, <shard_nodes:[2, 7]>, Shard: <channel_name:by-dev-rootcoord-dml_1_432785455185395713v1>, <shard_leader:7>, <shard_nodes:[7, 2]>]> (test_chaos_multi_replicas.py:242)
> > ```
> 
> This was fixed with #16653 ([60f7fef](https://github.com/milvus-io/milvus/commit/60f7fef3b3adff83823b4a725be5b162f0d4bcdd)），which is newer than the tested commit.

OK, I will check this again with master-latest image.

**Comment by XuanYang-cn** [comment]
### Query is normal, search is abnormal:
```
 23 [2022-04-26 12:01:05,065 - INFO - ci_test]: ******2nd assert after chaos injected:  (test_chaos_multi_replicas.py:217)
 24 [2022-04-26 12:01:05,066 - INFO - ci_test]: Expect Succ: Op.search succ rate 0.0, total: 32, average time: 0.0000 (test_chaos_multi_replicas.py:36)
 25 [2022-04-26 12:01:05,070 - INFO - ci_test]: Expect Succ: Op.query succ rate 1.0, total: 100, average time: 0.2020 (test_chaos_multi_replicas.py:36)
```

### replica infos
```
- Group: <group_id:432785403215872002>, <group_nodes:(1, 6, 8)>
- Group: <group_id:432785403215872003>, <group_nodes:(2, 7)> # Abnormal groups
```

- Proxy search Leader 8, which should be normal -> return error below, **this's wrong for search**, Leader8 shouldn't have to connect to QueryNode of other groups. `10.97.4.157` is the injected failing QueryNode 7

![image](https://user-images.githubusercontent.com/51370125/165708468-eb7812ba-702e-454c-8ea8-86c1a469ef22.png)

- Proxy search Leader 2, whose group is abnormal -> return error below, **this's expected and correct**
![image](https://user-images.githubusercontent.com/51370125/165710002-c2766c7c-db83-46aa-8fca-f13bd30d40b2.png)

**Comment by XuanYang-cn** [comment]
> > > so far it's by design, by we can have blacklist and hedged read as a new feature
> > 
> > 
> > don't we assign the request to the other replica group if on is offline?
> > /assign @xiaofan-luan /unassign
> 
> It's harder to do so because it usually takes a long time to know a replica is not working. One thing could help is to init shard replica latency tracker, if certain replica response is higher than others, or if it didn't response for the last n request, then we blacklist the replica. Other way to help on the avalaibility is called Hedged read, see mongodb documentation about the details of hedged read https://www.mongodb.com/docs/manual/core/read-preference-hedge-option/

This's correct for shardLeader not available and it needs to be considered carefully later.

However for @zhuwenxing 's test cases, shard leaders work well, its one group unavailable because one QueryNode is unavailable. In this case, the search should work fine.

**Comment by zhuwenxing** [comment]
Things become much more complicated.
With version `master-20220429-7dfab0aa`, all works well no matter whether it was during chaos or after chaos when running `pytest -s -v chaos/test_chaos_multi_replicas.py`.  But there is still one thing weird: I just inject pod failure to one pod, however, there will be two pods getting failure.


When running `pytest -s -v chaos/test_chaos_multi_replicas.py` again, things will be getting worse, much error logs like 
```
 ERROR - pymilvus.decorators]: RPC error: [_execute_search_requests], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 15 failed, reason  err err: context deadline exceeded
```
or 
```
[2022-04-29 16:41:54 - ERROR - pymilvus.decorators]: RPC error: [query], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Query, QueryNode ID = 1, reason=collection hasn't been loaded or has been released, collection id = 432857798563856385)>, <Time:{'RPC start': '2022-04-29 16:41:53.668107', 'RPC error': '2022-04-29 16:41:54.005657'}> (decorators.py:73)
```
the result is 
```
[2022-04-29 16:38:13,902 - INFO - ci_test]: ******1st assert before chaos:  (test_chaos_multi_replicas.py:166)
[2022-04-29 16:38:13,902 - INFO - ci_test]: Expect Succ: Op.search succ rate 0.8888888888888888, total: 9, average time: 0.3978 (test_chaos_multi_replicas.py:36)
[2022-04-29 16:38:14,162 - INFO - ci_test]: Expect Succ: Op.query succ rate 0.9, total: 10, average time: 0.2853 (test_chaos_multi_replicas.py:36)
```

```
[2022-04-29 16:40:35,206 - INFO - ci_test]: ******2nd assert after chaos injected:  (test_chaos_multi_replicas.py:192)
[2022-04-29 16:40:35,206 - INFO - ci_test]: Expect Succ: Op.search succ rate 0.5121951219512195, total: 41, average time: 0.3859 (test_chaos_multi_replicas.py:36)
[2022-04-29 16:40:35,213 - INFO - ci_test]: Expect Succ: Op.query succ rate 0.575, total: 40, average time: 0.3007 (test_chaos_multi_replicas.py:36)
```

```
[2022-04-29 16:44:50,599 - INFO - ci_test]: ******3rd assert after chaos deleted:  (test_chaos_multi_replicas.py:224)
[2022-04-29 16:44:50,600 - INFO - ci_test]: Expect Succ: Op.search succ rate 1.0, total: 37, average time: 0.3685 (test_chaos_multi_replicas.py:36)
[2022-04-29 16:44:50,602 - INFO - ci_test]: Expect Succ: Op.query succ rate 1.0, total: 39, average time: 0.2787 (test_chaos_multi_replicas.py:36)
```

Then run `pytest -s -v chaos/test_chaos_multi_replicas.py`  with the third try, things get much worse, 
and there be one more error:
```
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Query, QueryNode ID = 18, reason=Query 24 failed, reason cannot find segment 432858129009475586 in QueryNode err %!w(<nil>))>
```

```
[2022-04-29 16:59:11,074 - INFO - ci_test]: ******1st assert before chaos:  (test_chaos_multi_replicas.py:166)
[2022-04-29 16:59:11,075 - INFO - ci_test]: Expect Succ: Op.search succ rate 0.5333333333333333, total: 15, average time: 0.3857 (test_chaos_multi_replicas.py:36)
[2022-04-29 16:59:11,362 - INFO - ci_test]: Expect Succ: Op.query succ rate 0.5625, total: 16, average time: 0.2762 (test_chaos_multi_replicas.py:36)
```

```
[2022-04-29 17:01:31,939 - INFO - ci_test]: ******2nd assert after chaos injected:  (test_chaos_multi_replicas.py:192)
[2022-04-29 17:01:31,939 - INFO - ci_test]: Expect Succ: Op.search succ rate 0.8529411764705882, total: 34, average time: 2.2727 (test_chaos_multi_replicas.py:36)
[2022-04-29 17:01:31,943 - INFO - ci_test]: Expect Succ: Op.query succ rate 0.8787878787878788, total: 33, average time: 2.2588 (test_chaos_multi_replicas.py:36)
```

```
[2022-04-29 17:04:46,195 - INFO - ci_test]: ******3rd assert after chaos deleted:  (test_chaos_multi_replicas.py:224)
[2022-04-29 17:04:46,195 - INFO - ci_test]: Expect Succ: Op.search succ rate 0.0, total: 40, average time: 0.0000 (test_chaos_multi_replicas.py:36)
[2022-04-29 17:04:46,200 - INFO - ci_test]: Expect Succ: Op.query succ rate 0.0, total: 41, average time: 0.0000 (test_chaos_multi_replicas.py:36)
```

client log:
first try:[ci_test_log.log](https://github.com/milvus-io/milvus/files/8589716/ci_test_log.log)
second try: [ci_test_log.log](https://github.com/milvus-io/milvus/files/8589720/ci_test_log.log)
third try: [ci_test_log.log](https://github.com/milvus-io/milvus/files/8589730/ci_test_log.log)

server log:
[test-multi-replicas-04-29-17-21.zip](https://github.com/milvus-io/milvus/files/8589757/test-multi-replicas-04-29-17-21.zip)

**Comment by zhuwenxing** [comment]
The test script is https://github.com/milvus-io/milvus/blob/master/tests/python_client/chaos/test_chaos_multi_replicas.py

The result is not that stable. 
In the new round, the result is :
first run: all passed
second run: only failed during chaos with succ rate 0.8, all passed before chaos and after chaos
third run: succ rate is 0.9 before chaos , but all failed during chaos and after chaos

Two pods are in a failure status during the third run, this may be the root cause. So the question is why there will be one more pod getting errors or restarting by itself.

**Comment by yah01** [comment]
LoadBalance will fail if the offline node is the shard leader, there may be more problems with LoadBalance...
@sunby could u help on this?
/assign @sunby

**Comment by zhuwenxing** [comment]
It works well in version `master-20220506-67ce206c`. searching all success during all stages.

But there will still be some offline node id in the group nodes.

**Comment by zhuwenxing** [comment]
Hi, @yah01 
I decide to close this issue and open a new issue to trace the problem about the offline node id in the group nodes

**Comment by yah01** [comment]
@zhuwenxing 
This should be the same as #16705, and the PR #16854 has just been merged.
