### ISSUE TITLE
[Enhancement]: Replace plan parser library with ANTLR

### ISSUE THREAD

**Issue by DragonDriver** [milvus-io/milvus#16658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

I want to replace plan parser library with ANTLR.

### Why is this needed?

Now, we use https://github.com/antonmedv/expr to parse our expr and then generate the logical plan. But this library is not able to extend the grammar rules, which is not easy for common use. Replacing it with ANTLR will bring us a lot of benefits to implement more common expression.

**Comment by xiaofan-luan** [comment]
agree,  we probably want to investigate goyacc and antler but we definitely need a more flexible plan parser
