### ISSUE TITLE
How to modify configuration parameters dynamically?

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#1665]
**What is your question?**
How to modify configuration parameters dynamically?
And what kind of sdk can dynamically modify configuration parameters?
I think it's not easy to find in the official documentation.

**Comment by yamasite** [comment]
This has been documented in https://milvus.io/docs/v0.7.0/reference/milvus_config.md. For specific behaviors of each client, you need to refer to the API doc of each client, such as [HTTP API](https://github.com/milvus-io/milvus/tree/master/core/src/server/web_impl).

**Comment by JinHai-CN** [comment]
Fixed.
