### ISSUE TITLE
[Bug]: Failed to search data after reloadding collection

### ISSUE THREAD

**Issue by Renekton** [milvus-io/milvus#16657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.1
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): attu and milvus-cpp-sdk
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: Total:125G, Used:25G, Free:27G, Shared:375M, buff/cache:72G, Available:98G
- GPU: 
- Others:
```

### Current Behavior

When I release collection and load collection, I can not search data in the colleciton.

### Expected Behavior

When I release collection and load collection, I can search data in the colleciton successfully.

### Steps To Reproduce

```markdown
1. release collection
2. load collection
3. search data in the collection
4. can not search data in the collection, the error is "Timeout"
5. log file as shown below
```

### Anything else?

[milvus_log.zip](https://github.com/milvus-io/milvus/files/8559397/milvus_log.zip)

**Comment by aakejiang** [comment]
1.proxy_release.log:
`
[2022/04/26 02:32:52.902 +00:00] [WARN] [impl.go:1889] ["GetIndexState failed to WaitToFinish"] [error="no index is created"] [traceID=245b887f2bb3b6f0] [role=proxy] [MsgID=432377340216831027] [BeginTs=432784113111924739] [EndTs=432784113111924739] [db=] [collection=ti_sr_normal] [field=] ["index name"=_default_idx]
`

@Renekton Did you create the index?

**Comment by Renekton** [comment]
> 1.proxy_release.log: `[2022/04/26 02:32:52.902 +00:00] [WARN] [impl.go:1889] ["GetIndexState failed to WaitToFinish"] [error="no index is created"] [traceID=245b887f2bb3b6f0] [role=proxy] [MsgID=432377340216831027] [BeginTs=432784113111924739] [EndTs=432784113111924739] [db=] [collection=ti_sr_normal] [field=] ["index name"=_default_idx]`
> 
> @Renekton Did you create the index?

I have create IVF_FLAT index and delete it . And I have done this operation several times.

**Comment by Renekton** [comment]
![image](https://user-images.githubusercontent.com/7531084/165489743-70da09e4-d700-44ec-a110-926564a59417.png)

There is no index in the collection when I do the reloading operation and the searching operation.

**Comment by aakejiang** [comment]
You can post the logs when creating index for field VECTOR_FLOAT_DATA. So i can investigate why it's failed.

**Comment by Renekton** [comment]
> You can post the logs when creating index for field VECTOR_FLOAT_DATA. So i can investigate why it's failed.
There are some logs which produced by the "proxy node" , and nothing found in the "index node".
[proxy_create_index.zip](https://github.com/milvus-io/milvus/files/8580222/proxy_create_index.zip)

**Comment by xiaofan-luan** [comment]
I didn't see any error message from the log you created,  what is the error log and what's the time you hit this issue? From the log you upload at 04/26 02:41:33 everything seems to be ok

**Comment by Renekton** [comment]
> I didn't see any error message from the log you created, what is the error log and what's the time you hit this issue? From the log you upload at 04/26 02:41:33 everything seems to be ok

I'm not sure the specific time,  I did a lot of operations during that time. Do I need to upload more logs or restart the system?

**Comment by aakejiang** [comment]
> 

That's the reason why you cannot search anything. You must have created the index before searching.

**Comment by aakejiang** [comment]
> ![image](https://user-images.githubusercontent.com/7531084/165489743-70da09e4-d700-44ec-a110-926564a59417.png)
> 
> There is no index in the collection when I do the reloading operation and the searching operation.

That's the reason why you cannot search anything. You must have created the index before searching.

**Comment by aakejiang** [comment]
![image](https://user-images.githubusercontent.com/68629395/165874740-ad18016e-6fbf-4aa8-9a3f-fcfe5e89a2ba.png)

So can you search now after creating the index, if there are any problems let me know with the logs.

**Comment by Renekton** [comment]
> ![image](https://user-images.githubusercontent.com/68629395/165874740-ad18016e-6fbf-4aa8-9a3f-fcfe5e89a2ba.png)
> 
> So can you search now after creating the index, if there are any problems let me know with the logs.

![image](https://user-images.githubusercontent.com/7531084/165875430-a25e0291-3b4c-40fd-b8d4-7182d4f3a139.png)

**Comment by aakejiang** [comment]
How many records do you have in total? Could you just narrow down the search to a small range like VECTOR_ID < 10 and try again?

**Comment by Renekton** [comment]
> How many records do you have in total? Could you just narrow down the search to a small range like VECTOR_ID < 10 and try again?

![image](https://user-images.githubusercontent.com/7531084/165919428-c1f695e0-8ef0-4ba3-88dc-84cd1159b692.png)

just 13 entities. the result of searching is also timeout when I narrow down the range.

**Comment by JackLCL** [comment]
@Renekton 
It is recommended that you use the latest milvus2.0.2 version to test again.

**Comment by Renekton** [comment]
May be I find the problem. It seems that I can not do the searching when I reload the milvus cluster.
I will do more test.

**Comment by Renekton** [comment]
I have done more tests and the problem is fatal.
I think something is wrong with pulsar or milvus loading data

1. There are 15,701,172 entities in my milvus cluster
![image](https://user-images.githubusercontent.com/7531084/168012016-30e9cdc5-014d-4721-9325-855cf9d6d32c.png)
2. restart the milvus cluster, the cluster log shows as the "milvus-cluster-reload.log"
3. I can connect the milvus by attu, and get the collection lists successfully;
4. search the data in a collection, and the error is timeout, the cluster log shows as the "milvus-cluster-search-after-restarting-cluster.log"
5. I can find the size of pulsar folder in volume path is huge(74G     pulsar), is this normal ?
6. so I stop the cluster, and  rename the pulsar folder ;
7. I restart the cluster and find that the cluster is ok 
[milvus-cluster-log.zip](https://github.com/milvus-io/milvus/files/8675797/milvus-cluster-log.zip)

**Comment by JackLCL** [comment]
@aakejiang Any updates?

**Comment by Renekton** [comment]
I have changed to the stand-alone version, and the problem still exists.
The log as shown as below：
[milvus-stand-alone.zip](https://github.com/milvus-io/milvus/files/8713514/milvus-stand-alone.zip)

**Comment by Renekton** [comment]
I deleted the maximal collection in my milvus after the above operation, and then restart the milvus. Now the milvus could not be started. the error log as shown as below :
[milvus-can-not-be-started.zip](https://github.com/milvus-io/milvus/files/8713585/milvus-can-not-be-started.zip)

![image](https://user-images.githubusercontent.com/7531084/168967922-5bbdb110-8fb0-4dcd-9dea-32d5fc880d41.png)

**Comment by yanliang567** [comment]
@aakejiang could you please take a look at this issue?

**Comment by aakejiang** [comment]
```
[2022/05/18 05:48:55.761 +00:00] [WARN] [server.go:667] ["failed to regisger node"] [id=53] [address=172.30.0.4:21124] [error="rpc error: code = ResourceExhausted desc = trying to send message larger than max (3099784 vs. 2097152)"]
```
For now we just know exceeding grpc max send size that causes DataNode registration failed.

**Comment by xiaofan-luan** [comment]
@sunby seems that channelOps is too large to write into etcd

**Comment by xiaofan-luan** [comment]
> 

why cause the register so large?

**Comment by aakejiang** [comment]
```
[2022/05/24 01:51:04.955 +00:00] [DEBUG] [query_collection.go:1088] ["historical search"] [msgID=433417634421407747] [collectionID=433407637431779329] ["searched partitionIDs"="[433407637431779330]"] ["searched segmentIDs"="[]"]
[2022/05/24 01:51:04.955 +00:00] [DEBUG] [query_collection.go:1098] ["streaming search"] [msgID=433417634421407747] [collectionID=433407637431779329] ["searched dmChannel"=by-dev-rootcoord-dml_5_433407637431779329v1] ["searched partitionIDs"="[433407637431779330]"] ["searched segmentIDs"="[]"]
[2022/05/24 01:51:04.955 +00:00] [DEBUG] [query_collection.go:1098] ["streaming search"] [msgID=433417634421407747] [collectionID=433407637431779329] ["searched dmChannel"=by-dev-rootcoord-dml_4_433407637431779329v0] ["searched partitionIDs"="[433407637431779330]"] ["searched segmentIDs"="[]"]
```
From above logs, we know there are no segments for both historical and streaming query to search.

That's why the log shows there are no result for the search:
```
[2022/05/24 01:51:04.955 +00:00] [DEBUG] [query_collection.go:1128] ["QueryNode Empty SearchResultMsg"] [collectionID=433407637431779329] [msgID=433417634421407747] [vChannels="[by-dev-rootcoord-dml_5_433407637431779329v1,by-dev-rootcoord-dml_4_433407637431779329v0]"] [sealedSegmentSearched="[]"]
```

There are only 3,694 records total, and there is only growing segment for the collection, so let's find why there are no "searched segmentIDs" for "streaming search".

```
[2022/05/24 01:47:50.208 +00:00] [DEBUG] [partition.go:52] ["add a segment to replica"] [collectionID=433407637431779329] [partitionID=433407637431779330] [segmentID=433407637562851329]
[2022/05/24 01:47:50.210 +00:00] [DEBUG] [partition.go:64] ["remove a segment from replica"] [collectionID=433407637431779329] [partitionID=433407637431779330] [segmentID=433407637562851329]
[2022/05/24 01:47:50.277 +00:00] [DEBUG] [partition.go:52] ["add a segment to replica"] [collectionID=433407637431779329] [partitionID=433407637431779330] [segmentID=433407637497315329]
[2022/05/24 01:47:50.278 +00:00] [DEBUG] [partition.go:64] ["remove a segment from replica"] [collectionID=433407637431779329] [partitionID=433407637431779330] [segmentID=433407637497315329]
```

From the logs above, we know there are always a "remove" action after adding a segment to replica.

Back to the code, there is a defer func in watchDmChannelsTask to remove segments when err is not nil, see [code](https://github.com/milvus-io/milvus/blob/v2.0.2/internal/querynode/task.go#L321). The root cause is [here](https://github.com/milvus-io/milvus/blob/v2.0.2/internal/querynode/task.go#L450), method getQueryCollection returns a non-nil err that triggers the execution of removing segments in defer function.

**Comment by aakejiang** [comment]
>The root cause is [here](https://github.com/milvus-io/milvus/blob/v2.0.2/internal/querynode/task.go#L450), method getQueryCollection returns a non-nil err that triggers the execution of removing segments in defer function.

The queryCollections map used in watchDmChannelsTask is filled in addQueryChannelTask. While watchDmChannelsTask executes before addQueryChannelTask. That causes method getQueryCollection always return error.

```
[2022/05/24 01:47:50.210 +00:00] [DEBUG] [task.go:466] ["WatchDmChannels done"] [collectionID=433407637431779329] [vChannels="[by-dev-rootcoord-dml_5_433407637431779329v1]"]
[2022/05/24 01:47:50.278 +00:00] [DEBUG] [task.go:466] ["WatchDmChannels done"] [collectionID=433407637431779329] [vChannels="[by-dev-rootcoord-dml_4_433407637431779329v0]"]
[2022/05/24 01:48:25.150 +00:00] [DEBUG] [task.go:132] ["Execute addQueryChannelTask"] [collectionID=433407637431779329]
```

**Comment by xiaofan-luan** [comment]
> > The root cause is [here](https://github.com/milvus-io/milvus/blob/v2.0.2/internal/querynode/task.go#L450), method getQueryCollection returns a non-nil err that triggers the execution of removing segments in defer function.
> 
> The queryCollections map used in watchDmChannelsTask is filled in addQueryChannelTask. While watchDmChannelsTask executes before addQueryChannelTask. That causes method getQueryCollection in watchDmChannelsTask always return error.
> 
> ![image](https://user-images.githubusercontent.com/68629395/170050182-130417aa-9f00-47d8-b3dd-404dea3f4496.png)
> 
> ```
> [2022/05/24 01:47:50.210 +00:00] [DEBUG] [task.go:466] ["WatchDmChannels done"] [collectionID=433407637431779329] [vChannels="[by-dev-rootcoord-dml_5_433407637431779329v1]"]
> [2022/05/24 01:47:50.278 +00:00] [DEBUG] [task.go:466] ["WatchDmChannels done"] [collectionID=433407637431779329] [vChannels="[by-dev-rootcoord-dml_4_433407637431779329v0]"]
> [2022/05/24 01:48:25.150 +00:00] [DEBUG] [task.go:132] ["Execute addQueryChannelTask"] [collectionID=433407637431779329]
> ```

Good catch, we just to make sure 2.1 doesn't exist the same issue then I will close the issue for now

**Comment by xiaofan-luan** [comment]
this seems to be no longer an issue in 2.1, close for now? @aakejiang
