### ISSUE TITLE
[Bug]: Insert userface and userage fields to get the wrong result

### ISSUE THREAD

**Issue by liangyihan** [milvus-io/milvus#16662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.0.2
- Deployment mode(standalone or cluster):standalone 
- SDK version(e.g. pymilvus v2.0.0rc2): milvus-sdk-java 2.0.4
- OS(Ubuntu or CentOS): CentOS7
- CPU/Memory:  48  Intel(R) Xeon(R) Silver 4116 CPU @ 2.10GHz/256G
- GPU: 
- Others:
```

### Current Behavior

**1.insert data correctly**
_set structure:_
![image](https://user-images.githubusercontent.com/45417436/165212473-6cb08353-da2b-4511-807a-01a659f0cf0b.png)

_input parameter：_
{"userFace":[[0.80020356, 0.3490076, 0.499359, 0.94444656], [0.23521596, 0.73284143, 0.7519735, 0.8311272]]}

_return results:_
![image](https://user-images.githubusercontent.com/45417436/165213881-30298600-ef2a-493a-943b-1d53060165bd.png)

_insert code：_
public R<MutationResult> insert(String partitionName,List<List<Float>> vectors) {
        System.out.println("========== insert vector() ==========");
        List<InsertParam.Field> fields = new ArrayList<>();
        fields.add(new InsertParam.Field("userFace", DataType.FloatVector, vectors));

        InsertParam insertParam = InsertParam.newBuilder()
                .withCollectionName("test2")
                .withPartitionName(partitionName)
                .withFields(fields)
                .build();
        for (int i=0;i<fields.size();i++){
            System.out.println("insert vector data: "+fields.get(i).getName()+"="+fields.get(i).getValues());
        }
        R<MutationResult> response = milvusClient.insert(insertParam);
        handleResponseStatus(response);

        return response;
    }

**2.incorrect insert data**
_set structure:_
![image](https://user-images.githubusercontent.com/45417436/165214720-ad4cdcc6-2984-4024-a1cc-bb4e01712ffe.png)

_input parameter：_
{"userFace":[[0.80020356, 0.3490076, 0.499359, 0.94444656], [0.23521596, 0.73284143, 0.7519735, 0.8311272]],"userAge":[30,31]}

_return results:_
![image](https://user-images.githubusercontent.com/45417436/165214959-674e3ab3-0cfe-4f3b-841d-e0f428092cf8.png)

_insert code：_
public R<MutationResult> insert(String partitionName,List<List<Float>> vectors,List<Integer> ages) {
        System.out.println("========== insert() vector and age ==========");
        List<InsertParam.Field> fields = new ArrayList<>();
         fields.add(new InsertParam.Field("userAge", DataType.Int8, ages));
        fields.add(new InsertParam.Field("userFace", DataType.FloatVector, vectors));

        InsertParam insertParam = InsertParam.newBuilder()
                .withCollectionName("test3")
                .withPartitionName(partitionName)
                .withFields(fields)
                .build();
        for (int i=0;i<fields.size();i++){
            System.out.println("insert vector and age  data: "+fields.get(i).getName()+"="+fields.get(i).getValues());
        }
        R<MutationResult> response = milvusClient.insert(insertParam);
        handleResponseStatus(response);

        return response;
    }

**3.if you import data through the import on the Attu page, it is correct to import userface to test2, userface and userage to test3**

through the above findings, if you call the insert API to store the data, the data is wrong when inserting the data userface and userage to test3. Please help me troubleshoot the problem. Thank you!

### Expected Behavior

![image](https://user-images.githubusercontent.com/45417436/165236264-4be5597a-82f4-4f6c-bee0-fb7243f6f089.png)

**Comment by yanliang567** [comment]
@yhmo could you please take a look at this issue? it looks like that java sdk reformat the float vector data. 
/assign @yhmo 
/unassign

**Comment by xiaofan-luan** [comment]
I thinks it's simply the js floating point issuel.
If you want to check if java SDK returned the correct floating point you can use java to verify it
