### ISSUE TITLE
[Bug]: [test-string] Delete failed to report error "invalid plan node type"

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#16678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:xige-16-segcore-load-string-b50e5bf72-20220425
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.1.0.dev33
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

<img width="1439" alt="截屏2022-04-26 21 23 51" src="https://user-images.githubusercontent.com/34296482/165426543-5a606dc9-66a9-4fdf-bf23-64daa2e2b2b0.png">

**Comment by kingmbc** [comment]
I had the same issue. So I just changed it as below and succeeded.

```python
feed_emb_collection.delete(expr=f"id == [{emb_id}]") # failed

feed_emb_collection.delete(expr=f"id in [{emb_id}]") # Success
```

**Comment by xige-16** [comment]
> same issue

Milvus only supports deleting entities  with the term expression in. 
https://milvus.io/docs/v2.0.x/delete_data.md?shell#Delete-Entities

**Comment by jingkl** [comment]
milvus : master-20220505-20936f78
pymilvus:2.1.0.dev39
Verified that the delete expression is fine with “in”
