### ISSUE TITLE
[Bug]: [bulk load] Only support 32 row based files import at one time is not good enough

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#16674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220425-bc5e9ec9
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
```

### Current Behavior

For now it is designed that milvus does not support import more than 32 row based files at one time. It means it only supports 32GB import at a time.  I don't think this is good enough for those who has 1TB data(128d-2billion).

**Comment by soothing-rain** [comment]
We haven't decided the file size limit yet. Can you help us test a bit and figure out what's the best number together?

Perhaps we can test with 4Gigs, 8Gigs and even larger file and see how they work.

**Comment by yhmo** [comment]
Row-based file is stream reading, the memory usage can be controlled under low level. But column-based file is not stream reading, it could lead to OOM. I suggest we don't allow user input a huge file more than 4GB.

**Comment by xiaofan-luan** [comment]
> > Row-based file is stream reading, the memory usage can be controlled under low level. But column-based file is not stream reading, it could lead to OOM. I suggest we don't allow user input a huge file more than 4GB.
> 
> Agree, 4GB file is probably large enough. User can trigger multi tasks simultaneously.
> 
> For column-based file maybe we can do one task with multiple files and each file can be restricted to 4GB or even smaller(256M) so memory can be limited

Don't even think read 4GB a time is a good idea because datanode has very limited memory resources

**Comment by yhmo** [comment]
> > > Row-based file is stream reading, the memory usage can be controlled under low level. But column-based file is not stream reading, it could lead to OOM. I suggest we don't allow user input a huge file more than 4GB.
> > 
> > 
> > Agree, 4GB file is probably large enough. User can trigger multi tasks simultaneously.
> > For column-based file maybe we can do one task with multiple files and each file can be restricted to 4GB or even smaller(256M) so memory can be limited
> 
> Don't even think read 4GB a time is a good idea because datanode has very limited memory resources

256MB is too small, the data is split into multiple segments according to shard number. Default shard number is 2, then each segment size is only 128MB.

**Comment by soothing-rain** [comment]
We are changing file size limit to 1 Gigabytes.

The other topic about 32 tasks as a limit is resolved in a different issue.

/unassign
/assign @yanliang567

**Comment by yanliang567** [comment]
verified the 1GB limitation
