### ISSUE TITLE
[Bug]: [bulk load]Milvus should retrun errors if import from two numpy files with same name

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#16698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220425-bc5e9ec9
- Deployment mode(standalone or cluster): standalne
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.0.dev34
```

### Current Behavior

one of numpy files would be successfully imported into Milvus. But I think this is confusing as:
1. it is said that multiple numpy files are not support 
2. User might believed that all the data in multi files were successfully imported

### Expected Behavior

return error that indicates not support import multi numpy files at a time.

### Steps To Reproduce

1. prepare 2 .npy files 
2. import the 2 files at a time

```
self.utility_wrap.bulk_load(collection_name=c_name,
                            row_based=False,
                            files=[1.npy, 1.npy])
```

**Comment by yanliang567** [comment]
if moving the vectors.npy to different folders, and call them in one bulk_load(files=["/seg_1/a.numpy",  "/seg_2/a.numpy"], only one of files was imported, and the other one was ignored. 
So I think we need to warn users that this is not a valid operation.

a strict rule might be: if there are numpy files in the file list, then the file list must be one of the following two knids:
1. files = ['one_json_file', 'one_numpy_file']
2. files = ['one_numpy_file']

**Comment by yhmo** [comment]
Fixed by #16760

**Comment by yanliang567** [comment]
verified if imorted duplicate files, it reports errors

**Comment by yanliang567** [comment]
but if import 2 files from different folder, if not all succeed, see #16992
