### ISSUE TITLE
[Feature]: Add healthy check API

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#16702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Milvus is a distributed system with many components. After the user has started the cluster, an API is needed to determine whether the cluster is successfully started and can be serviced. In the online production environment, we also need to make polling calls through this health check API to master the health status of the current cluster.

### Describe the solution you'd like.

Add a healthy check API for Milvus. Because Milvus contains many components, the judgment logic may be very complicated. I hope we can discuss in this issue.

### Describe an alternate solution.

N/A

### Anything else? (Additional Context)

N/A

**Comment by xiaofan-luan** [comment]
we have health check command but it is not omnipotent.
It's still hard to define the boundary of health and ready to service unless if we support search without loading data into memory
