### ISSUE TITLE
[Bug]: [kafka]Milvus is unavailable after it recovered from kafka pod kill chaos

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#16715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220427-0a953948
- Deployment mode(standalone or cluster): cluster with kafka as mq
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.1.0.dev33
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

all operations failed after chaos and running test_e2e will time out 

```
3rd assert after chaos deleted:
Op.create  succ_rate: 0.00, total: 000, average_time: 0.0000, max_time: 0.0000, min_time: 0.0000
Op.insert  succ_rate: 0.00, total: 001, average_time: 0.0000, max_time: 0.0000, min_time: 0.0000
Op.flush   succ_rate: 0.00, total: 000, average_time: 0.0000, max_time: 0.0000, min_time: 0.0000
Op.index   succ_rate: 0.00, total: 000, average_time: 0.0000, max_time: 0.0000, min_time: 0.0000
Op.search  succ_rate: 0.00, total: 000, average_time: 0.0000, max_time: 0.0000, min_time: 0.0000
Op.query   succ_rate: 0.00, total: 001, average_time: 0.0000, max_time: 0.0000, min_time: 0.0000
```
```
testcases/test_e2e.py::TestE2e::test_milvus_default 
-------------------------------- live log setup --------------------------------
[2022-04-27 17:59:36 - INFO - ci_test]: ################################################################################ (conftest.py:166)
[2022-04-27 17:59:36 - INFO - ci_test]: [initialize_milvus] Log cleaned up, start testing... (conftest.py:167)
[2022-04-[27](https://github.com/milvus-io/milvus/runs/6198423584?check_suite_focus=true#step:13:27) 17:59:36 - INFO - ci_test]: [setup_class] Start setup class... (client_base.py:45)
[2022-04-27 17:59:36 - INFO - ci_test]: *********************************** setup *********************************** (client_base.py:51)
[2022-04-27 17:59:36 - INFO - ci_test]: [setup_method] Start setup test case test_milvus_default. (client_base.py:52)
Error: The action has timed out.
```

### Expected Behavior

all test cases pass

### Steps To Reproduce

```markdown
see https://github.com/milvus-io/milvus/runs/6198423584?check_suite_focus=true
```

### Anything else?

failed job: https://github.com/milvus-io/milvus/runs/6198423584?check_suite_focus=true
log: https://github.com/milvus-io/milvus/suites/6286216147/artifacts/224975411

**Comment by zhuwenxing** [comment]
I have tried the latest version `master-20220509-62658dcd`. 
It has the same issue, after Kafka pod kill, running test_e2e.py will hang, though all pods are in running status.

[artifacts-kafka-pod-kill-15-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/8649916/artifacts-kafka-pod-kill-15-server-logs.tar.gz)

**Comment by jaime0815** [comment]
Milvus connect to Kafka by a headless service,  due to the client still trying to use the old pod IP when some Kafka pods are killed, finally leading Milvus to connect to Kafka failed.

**Comment by xiaofan-luan** [comment]
> ect to Kafka failed.

Emm， can it recover automatically or we need to reset the connection?

**Comment by zhuwenxing** [comment]
@jaime0815 
with the config below, I tried a new test, but the result is same as old, running test_e2e.py hangs.
```yaml
kafka:
  enabled: true
  name: kafka
  replicaCount: 3
  defaultReplicationFactor: 2
```
[artifacts-kafka-pod-kill-16-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/8657524/artifacts-kafka-pod-kill-16-pytest-logs.tar.gz)

[artifacts-kafka-pod-kill-16-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/8657523/artifacts-kafka-pod-kill-16-server-logs.tar.gz)

**Comment by jaime0815** [comment]
it is caused by confluent Kafka client, https://github.com/confluentinc/confluent-kafka-go/issues/779

**Comment by zhuwenxing** [comment]
The last 5 tests of Kafka pod kill chaos test all passed.
verified in version `master-20220517-127dd34b`
