### ISSUE TITLE
Using BLAS to compute the Flat index is slow

### ISSUE THREAD

**Issue by JinHai-CN** [milvus-io/milvus#1673]
**Describe the bug**
When nq is larger than use_blas_threshold, OpenBlas is used for Flat index computation. This will slow down the FAISS index computation.

**Steps/Code to reproduce behavior**
Make the use_blas_threshold = 20 and use NQ = 20, it will happen.

**Expected behavior**
Use OpenBlas shouldn't be so slow. Check with https://github.com/facebookresearch/faiss/wiki/Troubleshooting#slow-brute-force-search-with-openblas
Use export OMP_WAIT_POLICY=PASSIVE to speed up the result.

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by shengjun1985** [comment]
"OpenBLAS and OpenMP are known not to play will together."
There is no such case in our project.

**Comment by JinHai-CN** [comment]
I know we don't have such case. But currently, FAISS use sgemm one vector by another one, which isn't efficient.

**Comment by JinHai-CN** [comment]
#2269 Use latest version and compilation option to improve the performance.
