### ISSUE TITLE
[Bug]: Connection raise error when using alias to create connection

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#16740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220429-a38c84e7
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.0.dev37
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
<ConnectionConfigException: (code=0, message=Alias of 'demo' already creating connections, but the configure is not the same as passed in.)
```

### Expected Behavior

create connection success

### Steps To Reproduce

```python
from pymilvus import connections
connections.connect(
  "demo",
 host="10.96.207.189",
 port="19530"
)

connections.connect(alias="demo")
```

**Comment by yanliang567** [comment]
@binbinlv is this because of the updates for username and passwords?

**Comment by binbinlv** [comment]
@zhuwenxing @yanliang567 
Yes, this error is reported by the updates for username and passwords.

And should disconnect first after reconnect.

**Comment by binbinlv** [comment]
```
>>> connections.disconnect("demo")
>>>
>>>
>>> connections.connect(alias="demo")
```

**Comment by XuanYang-cn** [comment]
Working on it now

**Comment by XuanYang-cn** [comment]
pymilvus == 2.1.0.dev40

**Comment by XuanYang-cn** [comment]
/assign
/unassign @zhuwenxing

dev40 is reverted, the test case and pymilvus are too connected with each other.

**Comment by zhuwenxing** [comment]
Hi, @XuanYang-cn 
I want to upgrade the priority level because reconnect would be used to make sure the connection is back to normal in the chaos test.

**Comment by XuanYang-cn** [comment]
pymilvus == 2.1.0.dev57

**Comment by XuanYang-cn** [comment]
- #16977

**Comment by zhuwenxing** [comment]
verified and passed with `pymilvus==2.1.0.dev57`
