### ISSUE TITLE
[Bug]: Drop collection hangs and rootcoord send tt to all channels too slowly

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#16750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220424-b82f6a1a
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.1.0.dev33
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: 

    queryNode:
      replicas: 5
  config:
    common:
      retentionDuration: 40
    queryNode:
      gracefulTime: 0
```
```


### Current Behavior

1.  Cancel `teardown` method so the collection is not deleted after running case
2. Run multi `test_load_replica_xx` cases multi times ( I really don't remember the exact operation)
3. List collection and drop one collection hangs
```
c.list_collections()
['collection_e3muioow', 'collection_fZTyH1jc', 'collection_vcGEpBKA', 'collection_sNKIUR89', 'collection_ooJyW7HS', 'collection_3YprB5Bd', 'collection_KaJNIz2R', 'collection_3Wed1LrK', 'collection_HThV2uC2', 'collection_QdfiedGI', 'collection_yyMFfhZW', 'collection_D9jPdc1a', 'collection_6YjecH17', 'collection_CEEfpxt4', 'collection_yGZDWPEI']
c.drop_collection('collection_fZTyH1jc')
```
Server logs:
[milvus_logs.tar.gz](https://github.com/milvus-io/milvus/files/8590348/milvus_logs.tar.gz)




### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

_No response_

**Comment by ThreadDao** [comment]
@LoveEachDay This problem is really annoying, but it hasn't come up lately

**Comment by xiaofan-luan** [comment]
keep it there, we are going to think about it

**Comment by ThreadDao** [comment]
leave it alone

**Comment by ThreadDao** [comment]
keep open
