### ISSUE TITLE
[Enhancement]: Simplify tests using `T.TempDir`

### ISSUE THREAD

**Issue by Juneezee** [milvus-io/milvus#16759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Currently we are using `ioutil.TempDir` and `os.RemoveAll` to create and cleanup temporary directory in tests. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 

This saves us at least 2 lines (error check, and cleanup) on every instance, or in some cases adds cleanup that we forgot.

### Anything else?

Reference: https://pkg.go.dev/testing#T.TempDir

**Comment by xiaofan-luan** [comment]
@Juneezee good suggestion! would you like to work on it?
