### ISSUE TITLE
[Enhancement]: Make segmentMaxLifetime configurable

### ISSUE THREAD

**Issue by czs007** [milvus-io/milvus#16772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

A growing segment will switch to sealed state when it reaches a predefined size (set to 512MB by default) or if a period of time has passed without an insertion (e.g., 24 hours).

Currently, the period is hard coded as following:
```// segmentMaxLifetime default segment max lifetime value
// TODO needs to be configurable
const segmentMaxLifetime = 24 * time.Hour
```

I'd like to make this time period configurable.

### Why is this needed?

To make this system more tunnerable

**Comment by xiaofan-luan** [comment]
fix by #16783
