### ISSUE TITLE
[Bug]: [nightly] Test cases failed for querynode core dumping 

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#16806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: latest
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2): latest
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Test case failed  for querynode core dumping [At last, all the tests are killed for the nightly CI time limit]

### Steps To Reproduce

Nightly:
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/512/pipeline

### Milvus Log

[artifacts-milvus-distributed-kafka-master-512-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/512/artifact/artifacts-milvus-distributed-kafka-master-512-pymilvus-e2e-logs.tar.gz)

Some clues:

```
fatal error: unexpected signal during runtime execution

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fe0d19890f1]



runtime stack:

runtime.throw(0x3cb1fe6, 0x2a)

        /usr/local/go/src/runtime/panic.go:1117 +0x72

runtime.sigpanic()

        /usr/local/go/src/runtime/signal_unix.go:718 +0x2e5



goroutine 174434 [syscall]:

runtime.cgocall(0x219ccda, 0xc003393168, 0xc0016701c0)

        /usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc003393138 sp=0xc003393100 pc=0x833b5b

github.com/milvus-io/milvus/internal/querynode._Cfunc_Marshal(0xc0016701c0, 0xc00073a880, 0x7fdf24006890, 0x2, 0xc002680728, 0x1, 0x0, 0x0)

        _cgo_gotypes.go:553 +0x51 fp=0xc003393168 sp=0xc003393138 pc=0x20f1051

github.com/milvus-io/milvus/internal/querynode.marshal.func1(0xc0016701c0, 0xc00073a880, 0xc001b0ff00, 0x2, 0xc002680728, 0xc000000001, 0x1, 0x2)

        /go/src/github.com/milvus-io/milvus/internal/querynode/reduce.go:91 +0xe8 fp=0xc0033931c0 sp=0xc003393168 pc=0x21112e8

github.com/milvus-io/milvus/internal/querynode.marshal(0x60256ae92d80001, 0x0, 0xc00073a860, 0x2, 0x2, 0xc001b0ff00, 0x2, 0xc002680728, 0x1, 0x2, ...)

        /go/src/github.com/milvus-io/milvus/internal/querynode/reduce.go:91 +0x434 fp=0xc003393350 sp=0xc0033931c0 pc=0x20fffb4

github.com/milvus-io/milvus/internal/querynode.(*queryShard).searchFollower(0xc00069c540, 0x3fcd9f0, 0xc0014b4cc0, 0xc001a1e5f0, 0xc0007be598, 0x1, 0x1, 0x60256ae92d80001, 0x0, 0x0, ...)

        /go/src/github.com/milvus-io/milvus/internal/querynode/query_shard.go:538 +0x7a5 fp=0xc003393780 sp=0xc003393350 pc=0x20c3f85

github.com/milvus-io/milvus/internal/querynode.(*queryShard).search(0xc00069c540, 0x3fcd9f0, 0xc0014b4cc0, 0xc001a1e5f0, 0x0, 0x0, 0x0)

        /go/src/github.com/milvus-io/milvus/internal/querynode/query_shard.go:358 +0x5e5 fp=0xc003393a28 sp=0xc003393780 pc=0x20c1025

github.com/milvus-io/milvus/internal/querynode.(*QueryNode).Search(0xc0004fc1e0, 0x3fcd9f0, 0xc0014b4cc0, 0xc001a1e5f0, 0x0, 0x0, 0x0)

        /go/src/github.com/milvus-io/milvus/internal/querynode/impl.go:602 +0x477 fp=0xc003393ec0 sp=0xc003393a28 pc=0x20b68d7

github.com/milvus-io/milvus/internal/querynode.(*ShardCluster).Search.func1(0xc0018cd1a0, 0xc001541fb0, 0x3fcd9f0, 0xc0014b4cc0, 0xc001a1e5f0, 0xc0018cd1b0, 0xc001b0fe70, 0xc001b0fe80, 0xc001c16e40)

        /go/src/github.com/milvus-io/milvus/internal/querynode/shard_cluster.go:667 +0xac fp=0xc003393f98 sp=0xc003393ec0 pc=0x210cc8c

runtime.goexit()

        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc003393fa0 sp=0xc003393f98 pc=0x8a3601

created by github.com/milvus-io/milvus/internal/querynode.(*ShardCluster).Search

        /go/src/github.com/milvus-io/milvus/internal/querynode/shard_cluster.go:665 +0x774



goroutine 1 [chan receive, 1 minutes]:

github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run(0xc000b59ea0, 0xc000012000, 0x0, 0x0)

        /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:503 +0x465

github.com/milvus-io/milvus/cmd/milvus.RunMilvus(0xc00003e090, 0x3, 0x3)

        /go/src/github.com/milvus-io/milvus/cmd/milvus/milvus.go:331 +0x845

main.main()

        /go/src/github.com/milvus-io/milvus/cmd/main.go:26 +0x45
17:05
```

### Anything else?

Tests are killed for overall timeout

[2022-05-05T20:58:28.739Z] [gw0] [ 62%] FAILED testcases/test_search_20.py::TestCollectionSearch::test_search_index_partitions_fuzzy[5000-2-128-True-False-partition_names0] 

[2022-05-05T20:58:46.836Z] testcases/test_search_20.py::TestCollectionSearch::test_search_index_partitions_fuzzy[5000-2-128-True-False-partition_names1] 

[2022-05-05T21:01:08.299Z] testcases/test_search_20.py::TestCollectionSearch::test_search_after_index_different_metric_type[128-True-False-HNSW-params4] 

script returned exit code 124

**Comment by binbinlv** [comment]
Similar issue in the following nightly: [in cluster mode, both in pulsar cluster and kafka cluster mode]

1. https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/511/pipeline/157

2. https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/510/pipeline/145

3. https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/509/pipeline

**Comment by jaime0815** [comment]
This issue can be reproduced within recently nightly test

**Comment by yanliang567** [comment]
this issue could be the root cause of many issue, such as #16816. 
@xiaofan-luan could you find someone help on this issue with top priority?

/assign @xiaofan-luan 
/unassign

**Comment by xiaofan-luan** [comment]
should be already fixed by https://github.com/milvus-io/milvus/pull/16815

**Comment by yanliang567** [comment]
@binbinlv could you please help to verify the fix?
/assign @binbinlv 
/unassign

**Comment by binbinlv** [comment]
Has not been reproduced for several days, fixed and closed.
