### ISSUE TITLE
[Bug]:Home page example- In the sample code, there is a class name incorrectly used

### ISSUE THREAD

**Issue by yongpengli** [milvus-io/milvus#16807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:V2.0.X
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```
address: https://milvus.io/cn/docs/v2.0.x/check_partition.md

### Current Behavior

// Class name error in if statement
R<Boolean> respHasPartition = milvusClient.hasPartition(
        HasPartitionParam.newBuilder()
                .withCollectionName("book")
                .withPartitionName("novel")
                .build());
if (respHasCollection.getData() == Boolean.TRUE) {
    System.out.println("Partition exists.");
}

### Expected Behavior

R<Boolean> respHasPartition = milvusClient.hasPartition(
        HasPartitionParam.newBuilder()
                .withCollectionName("book")
                .withPartitionName("novel")
                .build());
if (**respHasPartition**.getData() == Boolean.TRUE) {
    System.out.println("Partition exists.");
}

### Steps To Reproduce
open url: https://milvus.io/cn/docs/v2.0.x/check_partition.md
Mouse move to 'Verify if a partition exist'
click java demo
_No response_

**Comment by yanliang567** [comment]
@yhmo could you please help to fix this code demo, or we need to ask doc team for help?

/assign @yhmo 
/unassign

**Comment by YiyunNi** [comment]
Close with [PR #1157](https://github.com/milvus-io/milvus-docs/pull/1517)
