### ISSUE TITLE
[Bug]: [nightly] Search failed with 0 query number returned

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#16816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 7cc995d
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.1.0.dev36
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search failed with 0 queries returned:
[2022-05-05T20:17:27.095Z] [2022-05-05 19:16:40 - ERROR - ci_test]: search_results_check: Numbers of query searched (0) is not equal with expected (2) (func_check.py:209)

### Expected Behavior

Search successfully returned with correct query numbers

### Steps To Reproduce

Running nightly:
https://ci.milvus.io:18080/jenkins/blue/rest/organizations/jenkins/pipelines/milvus-nightly-ci/branches/master/runs/512/nodes/124/steps/145/log/?start=0

```python
 @pytest.mark.tags(CaseLabel.L1)
    def test_search_load_flush_load(self, nb, nq, dim, auto_id, _async):
        """
        target: test search when load before flush
        method: 1. insert data and load
                2. flush, and load
                3. search the collection
        expected: search success with limit(topK)
        """
        # 1. initialize with data
        collection_w = self.init_collection_general(prefix, auto_id=auto_id, dim=dim)[0]
        # 2. insert data
        insert_ids = cf.insert_data(collection_w, nb, auto_id=auto_id, dim=dim)[3]
        # 3. load data
        collection_w.load()
        # 4. flush and load
        collection_w.num_entities
        collection_w.load()
        # 5. search
        vectors = [[random.random() for _ in range(dim)] for _ in range(nq)]
        collection_w.search(vectors[:nq], default_search_field,
                            default_search_params, default_limit,
                            default_search_exp, _async=_async,
                            check_task=CheckTasks.check_search_results,
                            check_items={"nq": nq,
                                         "ids": insert_ids,
                                         "limit": default_limit,
                                         "_async": _async})
```

### Milvus Log

1. Logs

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/512/artifacts

artifacts-milvus-standalone-master-512-pymilvus-e2e-logs.tar.gz

2. collection name: search_collection_iM8n3Rq8

3. Failed timeline:
```
[2022-05-05T19:12:36.994Z] testcases/test_search_20.py::TestCollectionSearch::test_search_load_flush_load[3000-2-8-False-False]
```

**Comment by yanliang567** [comment]
utility.get_segment_info(collection_name) returns [[[]], when this issue reproduces.

@congqixia  could you please help to take a look?
/assign @congqixia 
/unassign

**Comment by binbinlv** [comment]
Has not been reproduced for several day, it may be fixed by one pr merged, and close if first, will reopen it if it appears again in the future.
