### ISSUE TITLE
Wrong description for index_file_size in FAQ

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#1682]
## Report incorrect documentation

**Location of incorrect documentation**
https://www.milvus.io/cn/docs/v0.7.0/faq/operational_faq.md#为什么有时候小的数据集查询时间反而更长

**Describe the problems or issues found in the documentation**
如果数据文件的大小小于配置文件里 index_file_size 参数的值

**Suggested fix for documentation**
改为：
如果数据文件的大小小于create_collection时index_file_size 参数的值

And English edtion also should be fixed.

**Comment by yamasite** [comment]
Fixed

https://github.com/milvus-io/docs/blob/v0.7.0/site/zh-CN/faq/operational_faq.md
https://github.com/milvus-io/docs/blob/v0.7.0/site/en/faq/operational_faq.md
