### ISSUE TITLE
[Bug]: collection.search() timeout parameter not working

### ISSUE THREAD

**Issue by DoliteMatheo** [milvus-io/milvus#16835]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.0
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.0.2
- OS(Ubuntu or CentOS):
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I set timeout parameter in collection.search() function, it was not working as expected.
I wanted to catch the timeout error whenever the Milvus service becomes unavailable, but when I stopped the Milvus service (docker stop XXX) and executed the collection.search(xxx, ..., timeout=1), it just kept hanging forever and no timeout error was given.
So how can I get the timeout signal when the Miluvs service is unavailable? I'm preparing to run some other procedure when such signal is acquired.
Thanks.

### Expected Behavior

When the timeout deadline is reached, some timeout error is being thrown.

### Steps To Reproduce

```markdown
1. Connect to Milvus
2. Stop the Milvus Service
3. Execute collection.search(xxx, ..., timeout=1)
4. Wait
The process hangs forever.
```

**Comment by XuanYang-cn** [comment]
I've test it on `pymilvus2.0.2` and `pymilvus-master-latest`.

In `pymilvus2.0.2`, search stuck, but in `pymilvus-master-latest`, search response with `MilvusException` after 10 retries failed. However, the retry is controlled by number of retries not timeout time when accounting `grpc.RpcError`.

So `pymilvus-latest` works normal and It's a bug in `pymilvus2.0.2`, it's not supposed to stuck, PyMilvus wants to return failure as soon as possible. I'll fix it soon.

- [ ] While server unavailable, search stuck at pymilvus2.0.2.
- [ ] API's retry should take the timeout into account when encounter `grpc.RpcError`.

**Comment by XuanYang-cn** [comment]
milvus-io/pymilvus#992 is the test case I use

**Comment by XuanYang-cn** [comment]
It's wait_for_ready and the combination of `timeout=None` makes the API hangs forever
- [ ] we need to get rid of `wait_for_ready` on 2.0.3 and 2.1.0

**Comment by XuanYang-cn** [comment]
After milvus-io/pymilvus#1006, search won't be hanging forever, the behavior should be  like the following output

PyMilvus will retry for 10 times and raise `pymilvus.BaseException` in PyMilvus 2.0.x

PyMilvus will retry for 10 times and raise `pymilvus.MilvusException` in PyMilvus 2.1.x
```
collection _test_issue_16835: inserted 1000 entites and loaded
Please turn-off the server [y/N]: y
grpc RpcError: [has_collection], <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>, <Time:{'RPC start': '2022-05-19 15:28:27.094185', 'gRPC error': '2022-05-19 15:28:27.095951'}>
grpc RpcError: [has_collection], <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>, <Time:{'RPC start': '2022-05-19 15:28:28.097514', 'gRPC error': '2022-05-19 15:28:28.098925'}>
grpc RpcError: [has_collection], <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>, <Time:{'RPC start': '2022-05-19 15:28:29.100431', 'gRPC error': '2022-05-19 15:28:29.101471'}>
grpc RpcError: [has_collection], <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>, <Time:{'RPC start': '2022-05-19 15:28:30.102951', 'gRPC error': '2022-05-19 15:28:30.104442'}>
grpc RpcError: [has_collection], <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>, <Time:{'RPC start': '2022-05-19 15:28:31.105917', 'gRPC error': '2022-05-19 15:28:31.107087'}>
grpc RpcError: [has_collection], <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>, <Time:{'RPC start': '2022-05-19 15:28:32.108567', 'gRPC error': '2022-05-19 15:28:32.109724'}>
grpc RpcError: [has_collection], <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>, <Time:{'RPC start': '2022-05-19 15:28:33.111196', 'gRPC error': '2022-05-19 15:28:33.112705'}>
grpc RpcError: [has_collection], <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>, <Time:{'RPC start': '2022-05-19 15:28:34.114178', 'gRPC error': '2022-05-19 15:28:34.115348'}>
grpc RpcError: [has_collection], <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>, <Time:{'RPC start': '2022-05-19 15:28:35.116839', 'gRPC error': '2022-05-19 15:28:35.117229'}>
grpc RpcError: [has_collection], <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>, <Time:{'RPC start': '2022-05-19 15:28:36.118456', 'gRPC error': '2022-05-19 15:28:36.119592'}>
RPC error: [search], <BaseException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1652945316.118766987","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5419,"referenced_errors":[{"created":"@1652945313.112350864","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
>)>, <Time:{'RPC start': '2022-05-19 15:28:27.094136', 'RPC error': '2022-05-19 15:28:36.120024'}>
```

**Comment by XuanYang-cn** [comment]
The next fixes would be:
- [ ] Raise Exception with a special code: Milvus_UNAVALIABLE
- [ ] Enable timeout to control the retry
