### ISSUE TITLE
[Bug]: Import Image into Milvus takes too much storage

### ISSUE THREAD

**Issue by axzs7777** [milvus-io/milvus#16843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: V2.0.2
- Deployment mode(standalone or cluster):  standalone
- SDK version(e.g. pymilvus v2.0.0rc2):  2.0.2
- OS(Ubuntu or CentOS): CentOS-7-x86_64-Minimal-2009
- CPU/Memory: Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz   2.90 GHz /Memory: 32G
- GPU: 
- Others:
```

### Current Behavior

Attu: 
![image](https://user-images.githubusercontent.com/18043668/167329684-5bbc009e-30d7-4374-b687-742481550d9c.png)
![image](https://user-images.githubusercontent.com/18043668/167329615-8cb4db32-7476-4445-bade-c37fbdf07273.png)
![image](https://user-images.githubusercontent.com/18043668/167329652-be5c8f3c-aff3-4116-a302-29e0c2052aac.png)

Disk consumption of CentOS milvus-minio volumes ：
![image](https://user-images.githubusercontent.com/18043668/167329838-70526012-3f04-4950-a27f-89b2af698177.png)

the milvus-minio volumes of three directories：index_files，insert_log, starts_log：
![image](https://user-images.githubusercontent.com/18043668/167330350-7e394d18-abbc-48ec-8cc9-61af369ae66e.png)

Why does it takes so much storage?

### Steps To Reproduce

```markdown
version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2020-12-03T00-03-10Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.0.2
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvus
```

**Comment by xiaofan-luan** [comment]
Hi @axzs7777 please translate your issue into English, thanks! because there might be other people who want to help but couldn't understand chinese

**Comment by yanliang567** [comment]
@axzs7777 is this the first time of deploying milvus? I mean did you remove the volumes before reinstall milvus?

**Comment by axzs7777** [comment]
yes, is first time of deploying milvus。

uvicorn==0.13.4
urllib3==1.26.9
fastapi==0.75.2
python-multipart==0.0.5
starlette==0.17.1
numpy==1.21.6
towhee==0.6.0
Pillow==9.1.0
pydantic==1.9.0
pymilvus==2.0.2

**Comment by LoveEachDay** [comment]
@axzs7777 Could you also check the `milvus` subdirectory size under the `volumes` directory?

**Comment by axzs7777** [comment]
Because I inserted more than 14000 pictures and occupied my disk, the virtual machine crashed, but I can re solve this problem。
Do you need to upload modified img_search_server  to you！

**Comment by LoveEachDay** [comment]
You can try to reproduce this problem, and record the disk usage for minio and milvus.

**Comment by axzs7777** [comment]
OK, I'll test it later and send it to you

**Comment by axzs7777** [comment]
Now more than 3000 pictures have been uploaded.
![image](https://user-images.githubusercontent.com/18043668/167581632-7b092ad2-9694-4c55-9143-363c4f9028f6.png)

but disk usage for minio so much
