### ISSUE TITLE
能否增加一个获取当前机器配置的接口

### ISSUE THREAD

**Issue by Jie-Yuan** [milvus-io/milvus#1685]
比如 cpu  gpu memory ip等

**Comment by Jie-Yuan** [comment]
获取ip是为了机器重启控制ip的变动

**Comment by del-zhenwu** [comment]
> 比如 cpu gpu memory ip等
Hi, you can try `_cmd("get_config *")` to get cpu/gpu/memory info.

**Comment by JinHai-CN** [comment]
Do you mean you want to get host information from Milvus? @Jie-Yuan

**Comment by Jie-Yuan** [comment]
> Do you mean you want to get host information from Milvus? @Jie-Yuan

Yes

**Comment by Jie-Yuan** [comment]
> > 比如 cpu gpu memory ip等
> 
> Hi, I have updated, you can try `_cmd("get_system_info")` to get cpu/gpu/memory info.

restful?

**Comment by BossZou** [comment]
In python sdk, you can invoke like this to obtain system cpu/gpu memory:
```python
>>> client = Milvus()
>>> client.connect($host, $port)
>>> client._cmd("get_system_info")
(Status(code=0, message='Success!'), '{"gpu0_memory_total":"8366915584","gpu0_memory_used":"601030656","memory_total":"33703714816","memory_used":"44896256"}')
```

**Comment by Jie-Yuan** [comment]
我想要一些 ip信息

**Comment by Jie-Yuan** [comment]
curl http://127.0.0.1:19121/system/info


> In python sdk, you can invoke like this to obtain system cpu/gpu memory:
> 
> ```python
> >>> client = Milvus()
> >>> client.connect($host, $port)
> >>> client._cmd("get_system_info")
> (Status(code=0, message='Success!'), '{"gpu0_memory_total":"8366915584","gpu0_memory_used":"601030656","memory_total":"33703714816","memory_used":"44896256"}')
> ```
> 
> Or use restful API:
> 
> ```shell
> curl http://127.0.0.1:19121/system/info
> ```
> 
> The response is like:
> 
> ```json
> {"code":0,"message":"OK","reply":"{"gpu0_memory_total":"8366915584","gpu0_memory_used":"601030656","memory_total":"33703714816","memory_used":"44896256"}"}
>  
> ```
> 
> However, server has no access to obtain IP of host machine.

如果需要些ip及端口信息呢？
因为docker ip会被 这个功能方便咱们管理

**Comment by JinHai-CN** [comment]
If server has multiple ip, which ip address need to be fetched? And without IP address, how could you ever connect to the server and port?
