### ISSUE TITLE
[Enhancement]: Proxy need a cache for checking collection load state

### ISSUE THREAD

**Issue by bigsheeper** [milvus-io/milvus#16859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Currently Proxy sends a `ShowCollections` rpc request to QueryCoord before each search, so we need a cache for checking collection load state in Proxy, to prevent this `ShowCollections` rpc cost.

**Comment by xiaofan-luan** [comment]
when did the cache evict?

**Comment by bigsheeper** [comment]
> when did the cache evict?

When `ReleaseCollection` or `DropCollection`.  pr #16577 use the `ReleaseDQLMessageStream` interface to evict cache, but there would be no DQLMessageStream in the master branch, so I would wrap a new api to evict cache.

**Comment by bigsheeper** [comment]
Proxy also need a cache for checking partitions load state
