### ISSUE TITLE
[Bug]:  milvus deploy problem with k8s

### ISSUE THREAD

**Issue by yearlz** [milvus-io/milvus#16862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2): v2.0.2
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

use different namespace to deploymet milvus ，the new config files influences the old one

the older one use the scripts in [https://milvus.io/cn/docs/v2.0.x/install_offline-helm.md](url) “milvus_manifest.yaml” and deployed in "default" namespace
![image](https://user-images.githubusercontent.com/32187348/167396154-c488edff-6e64-4b5e-b4eb-a74a554ac449.png)

i make some changes on the older scrips, like namespace、the nums of the querynode and so on, like:
![image](https://user-images.githubusercontent.com/32187348/167396385-ca4829bd-250a-4df9-83c1-08d2d8039056.png)

when deploy new milvus , the older service update too.

**Comment by yanliang567** [comment]
@LoveEachDay  could you please help to take a look at this issue?
/assign @LoveEachDay 
/unassign

**Comment by LoveEachDay** [comment]
You should use `helm template <release-name> -n <namespace> milvus/milvus > new-release.yaml` to generate a new manifest other than manually edit the old manifests because some resource may does not have the `namespace` metadata.

Then apply the manifests with `helm apply -f new-release.yaml`,

**Comment by yearlz** [comment]
> You should use `helm template <release-name> -n <namespace> milvus/milvus > new-release.yaml` to generate a new manifest other than manually edit the old manifests because some resource may does not have the `namespace` metadata.
> 
> Then apply the manifests with `helm apply -f new-release.yaml`,

in fact , to deploy milvus offline, i edit the mainfests in this way to get the new manifests.yaml 
![image](https://user-images.githubusercontent.com/32187348/167401943-2bc4f168-1eae-4fcd-a8ae-db3975dd6799.png)

**Comment by LoveEachDay** [comment]
When running `helm template`, you'd better specify a `namespace` .

**Comment by yearlz** [comment]
> When running `helm template`, you'd better specify a `namespace` .

i will try that one,and 
![image](https://user-images.githubusercontent.com/32187348/167413681-3e54ff40-b90e-4f82-85ab-4b86d851e4a1.png)
the <release name> of two scripts  is "my-release" ,  this may cause the problem?

**Comment by LoveEachDay** [comment]
If you apply the manifests into the same namespace, it will update the old release.

If you apply the manifest into different  namespaces, the two same release does not interfere each other.

**Comment by yearlz** [comment]
> If you apply the manifests into the same namespace, it will update the old release.
> 
> If you apply the manifest into different namespaces, the two same release does not interfere each other.

it is weird that when the newer one deployment in a different namespace ,  the new service in the new namespace is created, at the same time , the older is updated too, really strange.

**Comment by LoveEachDay** [comment]
Because when run `helm template my-release milvus/milvus > milvus.yaml`, some resource generated above does not have the `namespace` field under the `metadata` section. You need to both pass the namespace when you generate and apply the manifests.

If you want to install a milvus cluster with name `my-release` into `ns1` namespace:
1.  `helm template my-release -n ns1 milvus/milvus > ns1-milvus.yaml`
2.  `kubectl apply -f ns1-milvus.yaml -n ns1`

**Comment by yearlz** [comment]
> Because when run `helm template my-release milvus/milvus > milvus.yaml`, some resource generated above does not have the `namespace` field under the `metadata` section. You need to both pass the namespace when you generate and apply the manifests.
> 
> If you want to install a milvus cluster with name `my-release` into `ns1` namespace:
> 
> 1. `helm template my-release -n ns1 milvus/milvus > ns1-milvus.yaml`
> 2. `kubectl apply -f ns1-milvus.yaml -n ns1`

got it , i will try that ,thks
