### ISSUE TITLE
[Bug]: Growing segments should be able to load delta logs.

### ISSUE THREAD

**Issue by soothing-rain** [milvus-io/milvus#16885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: latest master
- Deployment mode(standalone or cluster): N/A
- SDK version(e.g. pymilvus v2.0.0rc2): N/A
- OS(Ubuntu or CentOS): N/A
- CPU/Memory: N/A
- GPU: N/A
- Others:
```

### Current Behavior

Growing segment with valid checkpoints could have delta logs.

When growing segment is being loaded, query node will try to load delta logs for growing segment.

If there's no delta log for the growing segment, we are good. Otherwise, an error will occur and cause the whole load to fail: https://github.com/milvus-io/milvus/blob/2d0f908dbafeb7439a5bbc2e35d9b5726cf33bce/internal/querynode/segment.go#L735-L738

A decent fix would be to fully support loading delta logs while loading growing segments.

To do this, we need to do at least the following:
1. Fully support loading delta logs for growing segments. For example: https://github.com/milvus-io/milvus/blob/2d0f908dbafeb7439a5bbc2e35d9b5726cf33bce/internal/core/src/segcore/segment_c.cpp#L213
2. When 1. is done, remove the limit:
https://github.com/milvus-io/milvus/blob/2d0f908dbafeb7439a5bbc2e35d9b5726cf33bce/internal/querynode/segment.go#L735-L738

**Comment by xiaofan-luan** [comment]
please help on investigating it
