### ISSUE TITLE
使用源码编译，但是还是无法启动

### ISSUE THREAD

**Issue by qoodoo** [milvus-io/milvus#1688]
1. 开始时要使用docker 运行，但无法启动，报./start_server.sh: line 3: 7 Illegal instruction     (core dumped) ../bin/milvus_server -c ../conf/server_config.yaml -l ../conf/log_config.conf，据说是CPU指令集不支持，遂改用源码编译，以期能够运行。
2. 下载v-0.7的源码，把avx2 改成avx。按推荐使用ubuntu18.04的docker容器进行安装，编译时能够正常完成，但还是无法启动。./start_server.sh: line 3: 14965 Illegal instruction     (core dumped) ../bin/milvus_server -c ../conf/server_config.yaml -l ../conf/log_config.conf
多次尝试，14965 这个数字每次都不相同。
请问如何解决？

**Comment by JinHai-CN** [comment]
Currently, no way to solve the issue unless you use AVX2/AVX512 CPU to run milvus.
