### ISSUE TITLE
[Bug]: [bulkload] Not automatically build index if importing data less than 1000

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#16890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220510-2d0f908d
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-2.1.0.dev54
```

### Current Behavior

imported data did not automatically build index if imported data less than 1000 entities

### Expected Behavior

Expected :{'indexed_rows': 100, 'total_rows': 100}
Actual   :{'indexed_rows': 0, 'total_rows': 100}

### Steps To Reproduce

```markdown
1. prepare row base json file with 100 entities
2. create collection
3. build index
4. import data
After import successfully, check index_building_progress()
```

**Comment by soothing-rain** [comment]
I thought I read somewhere that Milvus won't created index on segments with less than 1000 rows?

**Comment by yanliang567** [comment]
> I thought I read somewhere that Milvus won't created index on segments with less than 1000 rows?
Yes, but index_building_progress shall return consistent just as index built successfully.

**Comment by soothing-rain** [comment]
> > I thought I read somewhere that Milvus won't created index on segments with less than 1000 rows?
> > Yes, but index_building_progress shall return consistent just as index built successfully.

Ah I see what you mean. In our current design, dataindexed is more like a hint, it not necessarily mean every single segment has been indexed.

**Comment by yanliang567** [comment]
right, so shall we make this hint consistent in these APIs? Thanks.

**Comment by yanliang567** [comment]
keep it open
