### ISSUE TITLE
[Bug]: Kill one etcd node, can't recovery

### ISSUE THREAD

**Issue by WangErXiao** [milvus-io/milvus#16894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.02
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When i do chaos test killing a etcd node, the etcd can't recovery by self!
etcd Version: bitnami/etcd version 6.3.3;

Three replica;
When i kill etcd-0 or etcd-2 , the etcd cluster can recovery by self;
When i kill etcd-1 , the etcd cluster can't recovery by self;

Error Log:
`etcd 08:52:28.53 INFO  ==> ** Starting etcd setup **
etcd 08:52:28.55 INFO  ==> Validating settings in ETCD_* env vars..
etcd 08:52:28.55 WARN  ==> You set the environment variable ALLOW_NONE_AUTHENTICATION=yes. For safety reasons, do not use this flag in a production environment.
etcd 08:52:28.55 INFO  ==> Initializing etcd
etcd 08:52:28.56 INFO  ==> Detected data from previous deployments
etcd 08:53:28.74 INFO  ==> Updating member in existing cluster
Error: bad member ID arg (strconv.ParseUint: parsing "": invalid syntax), expecting ID in Hex`

### Expected Behavior

Etcd cluster can recovery by self

**Comment by yanliang567** [comment]
@WangErXiao Mm...sounds like an etcd issue,  have you tried to open an issue in etcd community as well?

@LoveEachDay could you please help to take a look at this issue?
/assign @LoveEachDay 
/unassign

**Comment by LoveEachDay** [comment]
This is a known issue for bitnami/etcd. You can find related issues here:
1. bitnami/bitnami-docker-etcd#29 
2. bitnami/bitnami-docker-etcd#39

@WangErXiao  If you encounter this problem, you'd manually remove the `/bitnami/etcd/data/member_id` file from this pod's pvc volume.

**Comment by WangErXiao** [comment]
thx
