### ISSUE TITLE
[Feature]: Support Pymilvus 1.x list_id_in_segment in 2.x

### ISSUE THREAD

**Issue by yuliu-eric** [milvus-io/milvus#16905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

We are planning to adopt the upcoming Milvus 2.1 release, and will need to handle existing use cases gracefully. Currently there's a use case list_id_in_segment in Milvus 1.x Python SDK, and we expect the same API in 2.x.

### Describe the solution you'd like.

Currently there's a use case list_id_in_segment in Milvus 1.x Python SDK, and we expect the same API in 2.x.

**Comment by xiaofan-luan** [comment]
Hi eric, thanks for your suggestion~
If I'm correct the goal is to fetch all result in a streaming way without hit the limit of Grpc and causing memory burst.
From my point of view, an iterator implementation is more straight forward, and more user friendly.

We would like to implement query pagination, the interface are something like:
iter := milvus.open(query condition)
while iter.hasNext() :
    process(iter.Next())

**Comment by xiaofan-luan** [comment]
The iteration can be further extend to pagination, with a (offset, limit) implementation and loop through all the segment.

By the way, search pagination is more complicated than query and need more carefully think through

**Comment by yuliu-eric** [comment]
> Hi eric, thanks for your suggestion~ If I'm correct the goal is to fetch all result in a streaming way without hit the limit of Grpc and causing memory burst. From my point of view, an iterator implementation is more straight forward, and more user friendly.
> 
> We would like to implement query pagination, the interface are something like: iter := milvus.open(query condition) while iter.hasNext() : process(iter.Next())

Hi Xiaofan, 

Thank you for the proposed alternative!

Basically below is the current logic in 1.x:

```
- get partition and segment info by call get_collection_stats(collection_name)
- iterate through every segment
    - get ids per segment in batch mode 
        - ids = list_id_in_segment(collection_name, segment_name)
    - perform some logic and add qualified id to the id_list_for_deletion
- delete entity w/ ids in batch mode
    - milvus.delete_by_ids(collection_name, id_list_for_deletion)
```
Ideally we prefer to migrate it to 2.x seamlessly following the same concept and processing logic. I guess the solution you mentioned above 'The iteration can be further extend to pagination, with a (offset, limit) implementation and loop through all the segment.' should work in this case? If so, this feature will be available in which release?

Bests,
Eric

**Comment by yuliu-eric** [comment]
Seems like the [proposed alternative](https://github.com/milvus-io/milvus/issues/16905#issuecomment-1123209590) is planned in release 2.2, do you have a timeline for the 2.2 release? We'd expect to have such feature available sometime this Quarter. 

Also, can you kind reply to my questions [above](https://github.com/milvus-io/milvus/issues/16905#issuecomment-1123218370)? Want to make sure my understanding is correct. Thank you!

Bests,
Eric

**Comment by xiaofan-luan** [comment]
> Seems like the [proposed alternative](https://github.com/milvus-io/milvus/issues/16905#issuecomment-1123209590) is planned in release 2.2, do you have a timeline for the 2.2 release? We'd expect to have such feature available sometime this Quarter.
> 
> Also, can you kind reply to my questions [above](https://github.com/milvus-io/milvus/issues/16905#issuecomment-1123218370)? Want to make sure my understanding is correct. Thank you!
> 
> Bests, Eric

The estimated release date would be August, but we can probably prioritize it and see if it could be delivered on beginning of July

**Comment by yuliu-eric** [comment]
Thank you Xiaofan for the update!

We plan to onboarding from 2.1 release, so that would be great if that pagination feature can be released together in 2.1 release; if not, would my original proposal `list_id_in_segment` be feasible to meet the preferred timeline?

Bests,
Eric

**Comment by xiaofan-luan** [comment]
> Thank you Xiaofan for the update!
> 
> We plan to onboarding from 2.1 release, so that would be great if that pagination feature can be released together in 2.1 release; if not, would my original proposal `list_id_in_segment` be feasible to meet the preferred timeline?
> 
> Bests, Eric

Emm, we can quickly add an iterator for query if necessary, and it should be working on some minor version of 2.1~ I don't like the idea to expose segment to user because it's hard to understand

**Comment by yuliu-eric** [comment]
`we can quickly add an iterator for query if necessary, and it should be working on some minor version of 2.1` - that would be super helpful

**Comment by xiaofan-luan** [comment]
keep it open util the iterator in

**Comment by xiaofan-luan** [comment]
Once we release 2.1 we will begin to design on it

**Comment by yuliu-eric** [comment]
Do we have any workaround before it's available? We may need this feature during the 1.x to 2.x migration. Otherwsie, we cannot onboard 2.1 due to the lack of this feature.

**Comment by xiaofan-luan** [comment]
the first part design has been done.  We implemented a pagination interface while we can specify offset, limit  while iterating.

**Comment by yuliu-eric** [comment]
cool, which release will it be included to?
