### ISSUE TITLE
  String field 'milvus.grpc.SearchParam.partition_tag_array' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.

### ISSUE THREAD

**Issue by reynaldliu** [milvus-io/milvus#1691]
ERROR google/protobuf/wire_format_lite.cc:584] String field 'milvus.grpc.SearchParam.partition_tag_array' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.

v0.7/master

**Comment by BossZou** [comment]
Thanks so much. It seems like that parittion tags in partition_tag_array contain UTF-8 characters, causing this issue. 
@reynaldliu , may you provide your procedure code here ?

**Comment by BossZou** [comment]
I guess that the version of python SDK doesn't match  that of milvus server. Please check them.

------------------------------------------------------------------------------------------------------------------------------
Closing this question.

**Comment by xulu666666** [comment]
请问这个问题解决了吗？ v0.8
Has this problem been solved？

**Comment by yhmo** [comment]
@xulu666666  This issue is caused by un-matched sdk version vs server version. 

To avoid this issue, make sure use correct sdk version:
server | pymilvus
0.7.0   | 0.2.8
0.7.1   | 0.2.9
0.8.0   | 0.2.10

**Comment by xulu666666** [comment]
@yhmo thanks so much, the problem was solved.
