### ISSUE TITLE
[Bug]: Proxy should clear ShardLeader cache when release collection

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#16926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

After Load - Release - Load, the groups will change.

But while release collection, proxy didn't clear the shard leaders' cache, causing search hang.

See also: #16902

**Comment by congqixia** [comment]
Proxy shall clear the cache if the release operation is handled by it. We shall expect the cache might be ouf-of-date if there are multiple proxies online. Working on the query node side to figure out how to fail fast in this case.

**Comment by XuanYang-cn** [comment]
- [ ] Clear cache when releasing collection/partition
- [ ] If proxy query a wrong leader and get this, refresh the cache and re-query
![origin_img_v2_0e0c523d-7937-49a8-b121-3e09e2107ceg](https://user-images.githubusercontent.com/51370125/168006010-e1ff534b-42d6-4503-a381-951be4869d6a.png)
