### ISSUE TITLE
[Bug]: etcdserver: too many operations in txn request when shards_num is set to 256

### ISSUE THREAD

**Issue by longjiquan** [milvus-io/milvus#16922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

=== start connecting to Milvus     ===

Does collection hello_milvus exist in Milvus: False

=== Create collection `hello_milvus` ===

shards_num: 256, dim: 1024
create 1 partitions done
RPC error: [load_collection], <MilvusException: (code=1, message=, etcdserver: too many operations in txn request)>, <Time:{'RPC start': '2022-05-11 19:18:17.716439', 'RPC error': '2022-05-11 19:18:17.777778'}>
Traceback (most recent call last):
  File "16802_memory_shard.py", line 41, in <module>
    hello_milvus.load()
  File "/home/ljq/miniconda3/envs/regression/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 450, in load
    conn.load_collection(self._name, timeout=timeout, replica_number=replica_number, **kwargs)
  File "/home/ljq/miniconda3/envs/regression/lib/python3.6/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/home/ljq/miniconda3/envs/regression/lib/python3.6/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/home/ljq/miniconda3/envs/regression/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/home/ljq/miniconda3/envs/regression/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/home/ljq/miniconda3/envs/regression/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 728, in load_collection
    raise MilvusException(response.error_code, response.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=, etcdserver: too many operations in txn request)>

**Comment by longjiquan** [comment]
```python
import random
import time

from pymilvus import (
    connections,
    utility,
    FieldSchema, CollectionSchema, DataType,
    Collection,
)

fmt = "\n=== {:30} ===\n"
search_latency_fmt = "search latency = {:.4f}s"

print(fmt.format("start connecting to Milvus"))
connections.connect("default", host="localhost", port="19530")

has = utility.has_collection("hello_milvus")
print(f"Does collection hello_milvus exist in Milvus: {has}")

dim = 1024
shards_num = 256

fields = [
    FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, auto_id=False),
    FieldSchema(name="random", dtype=DataType.DOUBLE),
    FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=dim)
]

schema = CollectionSchema(fields, "hello_milvus is the simplest demo to introduce the APIs")

print(fmt.format("Create collection `hello_milvus`"))
hello_milvus = Collection("hello_milvus", schema, shards_num=shards_num)

print(f"shards_num: {shards_num}, dim: {dim}")

n_partitions = 1
for i in range(n_partitions):
    hello_milvus.create_partition("part_" + str(i))
print(f"create {n_partitions} partitions done")

hello_milvus.load()
print("load done")

nrows = shards_num * 2
counter = 0
for i in range(n_partitions):
    entities = [
        # provide the pk field because `auto_id` is set to False
        [j for j in range(counter, counter + nrows)],
        [float(random.randrange(-20, -10)) for _ in range(nrows)],  # field random
        [[random.random() for _ in range(dim)] for _ in range(nrows)],  # field embeddings
    ]
    par = "part_" + str(i)
    insert_result = hello_milvus.insert(entities, partition_name=par)
    counter += nrows
print(f"insert into {n_partitions} partitions done")

# -----------------------------------------------------------------------------
# search based on vector similarity
print(fmt.format("Start searching based on vector similarity"))
vectors_to_search = entities[-1][-2:]
search_params = {
    "metric_type": "l2",
    "params": {"nprobe": 10},
}

start_time = time.time()
result = hello_milvus.search(vectors_to_search, "embeddings", search_params, limit=3, output_fields=["random"])
end_time = time.time()

for hits in result:
    for hit in hits:
        print(f"hit: {hit}, random field: {hit.entity.get('random')}")
print(search_latency_fmt.format(end_time - start_time))

utility.drop_collection("hello_milvus")
```

**Comment by longjiquan** [comment]
By default, max number of txn requests that etcd supported is `128`. Also this can be configured. In our helm deployment, this was configured to 256, so `256` shards can be supported. However, if we deploy etcd without any configuration changes, only `128` shards can be supported. When query cluster tried to load an collection, querycoord will write all delta channel info into etcd and every shard correspond to a delta channel info. So more than 128 shards cannot be configured.

**Comment by yanliang567** [comment]
@longjiquan was this fixed?

**Comment by longjiquan** [comment]
> @longjiquan was this fixed?

We can modify configuration of etcd for fast fix, though `128` is big enough for most users. We can also optimize these code by spliting txn requests.
