### ISSUE TITLE
[Bug]: Strong Consistency Level not worked as expected

### ISSUE THREAD

**Issue by YEXINGZHE54** [milvus-io/milvus#16949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.2
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):goalng github.com/milvus-io/milvus-sdk-go/v2 v2.0.0
- OS(Ubuntu or CentOS): Image milvus-cli:latest
- CPU/Memory: 
- GPU: 
- Others: 

code of INSERT data pasted below
```

### Current Behavior

After inserting data using the code pasted below
And then, start up a container of Milvus-cli, and check data in it:

>>> col.query(expr='ID>0',output_fields=['ID'], consistency_level="Strong")
[]
>>> col.query(expr='ID>0',output_fields=['ID'], consistency_level="Strong")
[]
>>> col.num_entities
2
>>> col.query(expr='ID==0',output_fields=['ID'], consistency_level="Strong")
[]
>>> col.query(expr='ID<0',output_fields=['ID'], consistency_level="Strong")
[]

### Expected Behavior

col.query(expr='ID>0',output_fields=['ID'], consistency_level="Strong")

should return response of valid data

### Steps To Reproduce

```markdown
1. deploy Milvus 2.0.2 in k8s with ceph enabled, all other settings default
2. use the code posted above to insert data
3. setup Milvus-cli:
kubectl run milvus-cli --image=zilliz/milvus_cli:latest --restart=Never -n infra-test --command -- 'tail' '-f' '/dev/null'
4. check data in Milvus-cli container
```

### Anything else?

code of Insert data(in golang, sdk github.com/milvus-io/milvus-sdk-go/v2 v2.0.0)

func Insert(ctx context.Context, vectors []VectorData) (err error) {
	col := ctx.Value("name").(string)
	ids := make([]int64, 0, len(vectors))
	vecs := make([][]float32, 0, len(vectors))
	for idx, v := range vectors {
		ids = append(ids, v.Id)
		vecs = append(vecs, vectors[idx].Vector[:])
	}
	idColumn := entity.NewColumnInt64("ID", ids)
	vecColumn := entity.NewColumnFloatVector("Vector", 1280, vecs)
	// remove duplicate data
	err = c.DeleteByPks(ctx, col, "", idColumn)
	if err != nil {
		return
	}
	_, err = c.Insert(
		ctx,       // ctx
		col,       // CollectionName
		"",        // partitionName
		idColumn,  // columnarData
		vecColumn, // columnarData
	)
	if err != nil {
		return
	}
	err = c.Flush(ctx, col, true)
	return
}

**Comment by xige-16** [comment]
This seems to be a bug. When judging whether the delete log is effective, the timestamp between the delete pk and the insert pk is not checked.

**Comment by xige-16** [comment]
I will fix it soon.

**Comment by xige-16** [comment]
same with #15744
