### ISSUE TITLE
[Bug]: Milvus query result has precision problem in vector field

### ISSUE THREAD

**Issue by nameczz** [milvus-io/milvus#16951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.2
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.0.2, attu 2.0.5
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. create collection with schema id, vector 
2. insert data, one vector is [1.3476964684980388,1.5402094571370055,1.5247762599580974,1.577921703425524] 
3. use [1.3476964684980388,1.5402094571370055,1.5247762599580974,1.577921703425524]  do vector search. Get one  result which distance is 0 and id 123456.
4. query data with expr id ==  123456. 
 In attu get vector result as [1.3476964235305786,1.540209412574768,1.5247762203216553,1.577921748161316].
 In pymilvus get vector result like:
![image](https://user-images.githubusercontent.com/20559208/168044839-c5d03ac0-e6d2-43a6-9012-c9d4cd27be5c.png)

### Expected Behavior

Query result is same as what i'm insert into milvus.

### Steps To Reproduce

```markdown
1. create collection with schema id, vector 
2. insert data, one vector is [1.3476964684980388,1.5402094571370055,1.5247762599580974,1.577921703425524] 
3. use [1.3476964684980388,1.5402094571370055,1.5247762599580974,1.577921703425524]  do vector search. Get one  result which distance is 0 and id 123456.
4. query data with expr id ==  123456.
```

**Comment by shanghaikid** [comment]
related issue https://github.com/milvus-io/milvus/issues/15534#

**Comment by xiaofan-luan** [comment]
mark 15534 as good first issue, please assign yourself if anyone want to take it

**Comment by xiaofan-luan** [comment]
known issue, but currently we don't have a solution on that

**Comment by xiaofan-luan** [comment]
keep it open

**Comment by yanliang567** [comment]
keep it open

**Comment by yanliang567** [comment]
@haorenfsa was it fixed?

**Comment by haorenfsa** [comment]
> @haorenfsa was it fixed?

Sry, I mixed this with #20415. This issue seems to have no solution for now and the precision lost in vector fields seems to be acceptable.

**Comment by yanliang567** [comment]
close for now
