### ISSUE TITLE
[Feature]: Support QueryNode Graceful stop

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#16959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

when querynode upgrade, currently we just stop querynode without waiting segment moved to other querynode.
It takes a couple of minutes to reload data(if not even longer)

### Describe the solution you'd like.

My suggestion is to open a script or cli command to mark one querynode as offline mode.
Then we gracefully balance out all the segment on this query node so user request would not be stopped for a long time

**Comment by paragor** [comment]
or querynode can handle *TERM(sigterm for example), mark itself as offline and wait some time

**Comment by ArunMurugan78** [comment]
Hey!
I would like to work on this. I'm new to contributing to open source projects and this repository. Some pointer on where to start looking would be really helpful.

**Comment by xiaofan-luan** [comment]
Welcome @ArunMurugan78 

Most of the issue is actually done by an other issue.
But if you can help on writing a scripts to gracefully stop the cluster that will be really great.
To fully stop the cluster, you will need to understand how milvus start and stop.

You should start from code: roles.go to understand how milvus bring up a node. Each node have a stop method which handles stop of a node.

Your goal is to write a script to gracefully stop the cluster. all the script we have is under scripts dir. there is already a stop_graceful.sh but you could take a look and see if work for standalone, cluster deployment and do some refinement if necessary

**Comment by ArunMurugan78** [comment]
Cool! I'll look into it.
