### ISSUE TITLE
[Bug]: [nightly] query returns not empty after delete operation

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#16961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

query returns not empty after delete operation

```

[2022-05-12T20:50:02.188Z] [2022-05-12 19:02:15 - DEBUG - ci_test]: (api_request)  : [Collection.delete] args: ['int64 in [1]', None, 20], kwargs: {} (api_request.py:55)

[2022-05-12T20:50:02.188Z] [2022-05-12 19:02:16 - DEBUG - ci_test]: (api_response) : (insert count: 0, delete count: 1, upsert count: 0, timestamp: 433162062718828546)  (api_request.py:27)

[2022-05-12T20:50:02.188Z] [2022-05-12 19:02:16 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ['int64 in [0, 1]', None, None, 20], kwargs: {} (api_request.py:55)

[2022-05-12T20:50:02.188Z] [2022-05-12 19:02:16 - DEBUG - ci_test]: (api_response) : [{'int64': 1}]  (api_request.py:27)
```

### Expected Behavior

query returns empty after delete operation

### Steps To Reproduce

Running nightly:
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/526/pipeline/124

cases:
1. testcases/test_delete.py::TestDeleteOperation::test_delete_entity_loop

```python
    def test_delete_entity_loop(self):
        """
        target: test delete all entities one by one in a loop
        method: delete data one by one for a loop
        expected: No exception
        """
        # init an auto_id collection and insert tmp_nb data, flush and load
        collection_w, _, _, ids = self.init_collection_general(prefix, nb=tmp_nb, insert_data=True, auto_id=True)[0:4]

        for del_id in ids:
            expr = f'{ct.default_int64_field_name} in {[del_id]}'
            res = collection_w.delete(expr)[0]
            assert res.delete_count == 1

        # query with all ids
        expr = f'{ct.default_int64_field_name} in {ids}'
        collection_w.query(expr, check_task=CheckTasks.check_query_empty)
```

2. testcases/test_delete.py::TestDeleteOperation::test_delete_merge_ids_channel_and_sealed
```python
    def test_delete_merge_ids_channel_and_sealed(self):
        """
        target: test merge deleted ids come from both channel and sealed
        method: 1.create, insert ids [0, tmp_nb) with shard_num=1
                2.delete id 0 and flush
                3.load and query with id 0
                4.delete id 1 (merge same segment deleted ids 0 and 1)
                5.query with id 0 and 1
        expected: Empty query result
        """
        # init collection and insert data without flush
        collection_w = self.init_collection_wrap(name=cf.gen_unique_str(prefix), shards_num=1)
        df = cf.gen_default_dataframe_data(tmp_nb)
        collection_w.insert(df)

        # delete id 0 and flush
        del_res, _ = collection_w.delete(tmp_expr)
        assert del_res.delete_count == 1
        assert collection_w.num_entities == tmp_nb

        # load and query id 0
        collection_w.load()
        collection_w.query(tmp_expr, check_task=CheckTasks.check_query_empty)

        # delete id 1 and query id 0 and 1
        collection_w.delete(expr=f'{ct.default_int64_field_name} in {[1]}')
        collection_w.query(expr=f'{ct.default_int64_field_name} in {[0, 1]}',
                           check_task=CheckTasks.check_query_empty)
```

### Milvus Log

```markdown
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/526/artifacts/

name: artifacts-milvus-standalone-master-526-pymilvus-e2e-logs.tar.gz
```

### Anything else?

1. for failed test case:  testcases/test_delete.py::TestDeleteOperation::test_delete_entity_loop
   1.1 collection name: delete_xvx6Sd46
   1.2 FAILED timeline: 
2022-05-12T19:02:09.856Z] [gw3] [ 12%] FAILED testcases/test_delete.py::TestDeleteOperation::test_delete_entity_loop 

2. for failed test case: testcases/test_delete.py::TestDeleteOperation::test_delete_merge_ids_channel_and_sealed 
    2.1 collection name: delete_qQwOG19e
    2.2 FAILED timeline
2022-05-12T19:02:18.008Z] [gw3] [ 12%] FAILED testcases/test_delete.py::TestDeleteOperation::test_delete_merge_ids_channel_and_sealed

**Comment by jingkl** [comment]
testcase
The vector can be searched when the string is the primary key for deletion
```
    @pytest.mark.tags(CaseLabel.L0)`
    def test_delete_expr_string_field_primary_true(self):
        """
        target: test delete data
        method: 1.create collection and insert data
                2.collection.load()
                4.collection delete expr with string field, int field
                5.query expr
        expected: Delete successfully
        """
        collection_w, vectors = self.init_collection_general(prefix, insert_data=True, primary_field=ct.default_string_field_name)[0:2]
        collection_w.delete(expr=default_string_exp)
        collection_w.query(expr=default_string_exp, check_task=CheckTasks.check_query_empty)
    
        # search with id 0 vectors
        search_res, _ = collection_w.search([vectors[0][ct.default_float_vec_field_name][0]],
                                            ct.default_float_vec_field_name,
                                            ct.default_search_params, ct.default_limit)
    
>       assert len(search_res) == 0
```

debug  log：
```
[2022-05-13 10:31:22 - INFO - ci_test]: insert_data: inserting data into collection delete_4qiG9xM5 (num_entities: 3000) (common_func.py:599)
[2022-05-13 10:31:22 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [      int64   float varchar                                       float_vector
0         0     0.0       0  [0.001767644431708157, 0.0204781481787672, 0.0...
1         1     1.0       1  [0.027995597525904768, 0.12965104078228468, 0....
2         2     2.0       2  [0.005098784382205545, 0.13337568......, kwargs: {'timeout': 20} (api_request.py:55)
[2022-05-13 10:31:23 - DEBUG - ci_test]: (api_response) : (insert count: 3000, delete count: 0, upsert count: 0, timestamp: 433169126702186498)  (api_request.py:27)
[2022-05-13 10:31:26 - INFO - ci_test]: insert_data: inserted data into collection delete_4qiG9xM5 (num_entities: 3000) (client_base.py:159)
[2022-05-13 10:31:26 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 20], kwargs: {} (api_request.py:55)
[2022-05-13 10:31:27 - DEBUG - ci_test]: (api_response) : None  (api_request.py:27)
[2022-05-13 10:31:27 - DEBUG - ci_test]: (api_request)  : [Collection.delete] args: ['varchar in [ "0"]', None, 20], kwargs: {} (api_request.py:55)
[2022-05-13 10:31:27 - DEBUG - ci_test]: (api_response) : (insert count: 0, delete count: 1, upsert count: 0, timestamp: 433169127881834499)  (api_request.py:27)
[2022-05-13 10:31:27 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ['varchar in [ "0"]', None, None, 20], kwargs: {} (api_request.py:55)
[2022-05-13 10:31:27 - DEBUG - ci_test]: (api_response) : []  (api_request.py:27)
[2022-05-13 10:31:27 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.001767644431708157, 0.0204781481787672, 0.00989903207894516, 0.008158727061765464, 0.11207468072326665, 0.11749715814740583, 0.12997374747580404, 0.09275946983820914, 0.0017174978549179586, 0.10328104159935773, 0.04022658659535088, 0.06870330372072138, 0.049557489540479095, 0.033486328398035566......, kwargs: {} (api_request.py:55)
[2022-05-13 10:31:28 - DEBUG - ci_test]: (api_response) : ["['(distance: 0.34207746386528015, id: 2676)', '(distance: 0.3502596914768219, id: 2327)', '(distance: 0.35751569271087646, id: 902)', '(distance: 0.35967016220092773, id: 57)', '(distance: 0.36342790722846985, id: 1705)', '(distance: 0.37002065777778625, id: 2867)', '(distance: 0.3700515031814575,......  (api_request.py:27)
```

**Comment by binbinlv** [comment]
Continuously Failure:
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/532/pipeline/134

**Comment by binbinlv** [comment]
Block the nightly test, so set it as critical urgent.

**Comment by xige-16** [comment]
The reason is that the sealed segment does not update the size of the delete record when deleting the data, resulting in the delete operation not taking effect in subsequent queries.

**Comment by binbinlv** [comment]
Verified and fixed after fix pr #17033

**Comment by binbinlv** [comment]
Delete issue appears again, could you please help to check? @xige-16 

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/546/pipeline/129

1. milvus log:
[artifacts-milvus-standalone-master-546-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/546/artifact/artifacts-milvus-standalone-master-546-pymilvus-e2e-logs.tar.gz)

2. collection name:  delete_D9ix9Zqg

3. [2022-05-22T19:02:34.771Z] [gw5] [ 17%] FAILED testcases/test_delete.py::TestDeleteString::test_delete_query_ids_both_sealed_and_channel_with_string 

4. test cases:
```python
def test_delete_query_ids_both_sealed_and_channel_with_string(self):

 """
target: test query that delete ids from both channel and sealed
method: 1.create and insert, string field is primary
               2.delete id 0 and flush
               3.load and query id 0
               5.insert new id and delete the id
               6.query id 0 and new id
 expected: Empty query result
 """
# init collection and insert data without flush

schema = cf.gen_string_pk_default_collection_schema()
collection_w = self.init_collection_wrap(name=cf.gen_unique_str(prefix), schema=schema)
df = cf.gen_default_dataframe_data(tmp_nb)
collection_w.insert(df)

# delete id 0 and flush
del_res, _ = collection_w.delete(default_string_expr)
assert del_res.delete_count == 1
assert collection_w.num_entities == tmp_nb

# load and query id 0
collection_w.load()
collection_w.query(default_string_expr, check_task=CheckTasks.check_query_empty)
```

**Comment by jaime0815** [comment]
the following failed cases seem related to this issue,  the root causes are 'Query result is not empty' apart from test_compact_search_after_delete_channel case

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/548/pipeline/

```
testcases/test_delete.py::TestDeleteParams::test_delete_expr_single - ...
testcases/test_delete.py::TestDeleteParams::test_delete_entities[True]
testcases/test_compaction.py::TestCompactionOperation::test_compact_search_after_delete_channel testcases/test_delete.py::TestDeleteOperation::test_delete_after_index
testcases/test_delete.py::TestDeleteString::test_delete_sealed_data_channel_delete_with_string
testcases/test_delete.py::TestDeleteString::test_delete_expr_repeated_values_with_string
estcases/test_delete.py::TestDeleteString::test_delete_flush_loop_with_string
```

**Comment by xiaofan-luan** [comment]
> the following failed cases seem related to this issue, the root causes are 'Query result is not empty' apart from test_compact_search_after_delete_channel case
> 
> https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/548/pipeline/
> 
> ```
> testcases/test_delete.py::TestDeleteParams::test_delete_expr_single - ...
> testcases/test_delete.py::TestDeleteParams::test_delete_entities[True]
> testcases/test_compaction.py::TestCompactionOperation::test_compact_search_after_delete_channel testcases/test_delete.py::TestDeleteOperation::test_delete_after_index
> testcases/test_delete.py::TestDeleteString::test_delete_sealed_data_channel_delete_with_string
> testcases/test_delete.py::TestDeleteString::test_delete_expr_repeated_values_with_string
> estcases/test_delete.py::TestDeleteString::test_delete_flush_loop_with_string
> ```

Does this happened only for kafka or for pulsar also? I guess xi-ge xi working on the delete fix

**Comment by binbinlv** [comment]
> > the following failed cases seem related to this issue, the root causes are 'Query result is not empty' apart from test_compact_search_after_delete_channel case
> > https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/548/pipeline/
> > ```
> > testcases/test_delete.py::TestDeleteParams::test_delete_expr_single - ...
> > testcases/test_delete.py::TestDeleteParams::test_delete_entities[True]
> > testcases/test_compaction.py::TestCompactionOperation::test_compact_search_after_delete_channel testcases/test_delete.py::TestDeleteOperation::test_delete_after_index
> > testcases/test_delete.py::TestDeleteString::test_delete_sealed_data_channel_delete_with_string
> > testcases/test_delete.py::TestDeleteString::test_delete_expr_repeated_values_with_string
> > estcases/test_delete.py::TestDeleteString::test_delete_flush_loop_with_string
> > ```
> 
> Does this happened only for kafka or for pulsar also? I guess xi-ge xi working on the delete fix

Please refer to the latest comments of issue #17176

**Comment by xige-16** [comment]
> > the following failed cases seem related to this issue, the root causes are 'Query result is not empty' apart from test_compact_search_after_delete_channel case
> > https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/548/pipeline/
> > ```
> > testcases/test_delete.py::TestDeleteParams::test_delete_expr_single - ...
> > testcases/test_delete.py::TestDeleteParams::test_delete_entities[True]
> > testcases/test_compaction.py::TestCompactionOperation::test_compact_search_after_delete_channel testcases/test_delete.py::TestDeleteOperation::test_delete_after_index
> > testcases/test_delete.py::TestDeleteString::test_delete_sealed_data_channel_delete_with_string
> > testcases/test_delete.py::TestDeleteString::test_delete_expr_repeated_values_with_string
> > estcases/test_delete.py::TestDeleteString::test_delete_flush_loop_with_string
> > ```
> 
> Does this happened only for kafka or for pulsar also? I guess xi-ge xi working on the delete fix

It is not the same as the delete problem in segcore. From the log of jaimie0815, querynode has not received the delete message from delta channel.

**Comment by longjiquan** [comment]
inversitigating this
/assign

**Comment by longjiquan** [comment]
Did the minio pod still be kept? It will be easier if we can get the delta logs and the bloom filter flushed to minio. @binbinlv 

According to the test case, insert -> delete (pk "0") -> flush -> load -> insert -> delete(no pk will be filtered) -> query.
So there will be two sealed segments and two growing segments.
In this case, we don't need to care growing segments from the log, since this case won't produce duplicate pks.
However, the log indicates that sealed segments loaded the delta logs and bloom filters. So maybe the data in delta logs might be wrong.

**Comment by binbinlv** [comment]
@longjiquan 

It is reproduced in the following nightly, and the environment has been kept, and please let me know if you have finished using the environment, then I need to clean it, thanks.

https://ci.milvus.io:18080/jenkins/blue/rest/organizations/jenkins/pipelines/milvus-nightly-ci/branches/master/runs/551/nodes/64/steps/178/log/?start=0

logs:
[artifacts-milvus-distributed-kafka-master-551-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/551/artifact/artifacts-milvus-distributed-kafka-master-551-pymilvus-e2e-logs.tar.gz)

one of FAILED case:
test_delete_sealed_data_channel_delete_with_string

collection name: delete_Vuz8OZQS

**Comment by longjiquan** [comment]
```shell
cat mdk-551-n-milvus-querynode-5f476f6465-wkv96_milvus-ci_querynode-bd4077582ee6c5106e1f4e1f4eabef884ddf15111ff49ec0935d166720855c7a.log | grep "delete in streaming replica" | grep 433452844403916833
cat mdk-551-n-milvus-querynode-5f476f6465-zzn7z_milvus-ci_querynode-b9bf23fc91d265b3d8d78ed193a4e7ca1c8e6da932897245eed2749b3bbc3229.log | grep "delete in streaming replica" | grep 433452844403916833
```

**Comment by longjiquan** [comment]
For failed case `test_delete_sealed_data_channel_delete_with_string`, querynode didn't receive delete message.

**Comment by binbinlv** [comment]
And other two failed cases needs to be investigated:
[2022-05-25T16:10:58.134Z] FAILED testcases/test_delete.py::TestDeleteOperation::test_delete_flush_loop
[2022-05-25T16:10:58.134Z] FAILED testcases/test_delete.py::TestDeleteString::test_delete_flush_loop_with_string

1. testcases/test_delete.py::TestDeleteOperation::test_delete_flush_loop
collection name： delete_oBhL3NjS

2. testcases/test_delete.py::TestDeleteString::test_delete_flush_loop_with_string
collection name：delete_A9ulRbCs

**Comment by binbinlv** [comment]
OK, verifying, thanks.

**Comment by binbinlv** [comment]
From the latest nightly, some deleted cases still failed, so needs further investigation, thanks.

Nightly commit: 72f454e, which is the commit of the pr to be fixed.

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/564/pipeline


4 Failed cases：
[2022-05-31T20:27:06.592Z] FAILED testcases/test_delete.py::TestDeleteParams::test_delete_partition - As...

[2022-05-31T20:27:06.592Z] FAILED testcases/test_compaction.py::TestCompactionOperation::test_compact_search_after_delete_channel

[2022-05-31T20:27:06.592Z] FAILED testcases/test_delete.py::TestDeleteOperation::test_delete_after_index

[2022-05-31T20:27:06.592Z] FAILED testcases/test_delete.py::TestDeleteString::test_delete_entities_repeatedly_with_string

**Comment by longjiquan** [comment]
I run a test that continously run `test_delete_flush_loop_with_string` for 10000 times base on #17334 . And the issue cannot be reproduced.
![image](https://user-images.githubusercontent.com/31589260/171533874-c86b170d-64b1-4337-aeee-178ae6d60b8f.png)

Before #17334 , the dml channels used by same collection may be changed in order. So delete request with same primary key will enter the other channel, which will lead tsafe not working properly.

**Comment by binbinlv** [comment]
This issue on pulsar is fixed and could not reproduced for couple days, so close this issue.
