### ISSUE TITLE
[Enhancement]: Avoid generating many small segments when inserting continuously in small batches

### ISSUE THREAD

**Issue by xige-16** [milvus-io/milvus#16972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

When a small batch is continuously inserted, the proxy will request the datacroord to pre-allocate the segmentID, and the quota (number of rows) that can be inserted by the segmentID, but when the pre-allocation result expires, the allocated segment quota will be wasted. As a result, datacoord frequently allocates new segmentIDs, and eventually flushes many small segments. Even if milvus can rely on auto compaction to alleviate the query performance problems caused by small segments, it will still have a certain impact on the query/search performance of querynode.
[logs.tar.gz](https://github.com/milvus-io/milvus/files/8684662/logs.tar.gz)

**Comment by xiaofan-luan** [comment]
so what's the plan? 
for the pre-allocated segment ID, shall we return from proxy to data coord if it is not used?

**Comment by xiaofan-luan** [comment]
so we don't need to generate new segments

**Comment by xige-16** [comment]
My fault, the proxy log did receive a flush request, so it has nothing to do with the system system semgent allocation mechanism
