### ISSUE TITLE
[Bug]: [bulkload] failed to bulk load numpy files in different folders in one request

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#16992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220513-52fc9a55
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-2.1.0.dev57
```

### Current Behavior

only 1 numpy file was imported successfully if importing 2 numpy files from two different folder at one request.

### Expected Behavior

all numpy files are imported successfully

### Steps To Reproduce

```markdown
1. prepare 2 numpy files in different folder
2. import the 2 files in one request
'''
files = '/6d_10_0/vectors.npy,/6d_10_1/vectors.npy'
task_ids, _ = self.utility_wrap.bulk_load(collection_name=c_name,
                                                  row_based=False,
                                                  files=files)
'''
```

### Milvus Log

```markdown
>       assert self.collection_wrap.num_entities == entities * file_nums
E       assert 10 == 20
```

### Anything else?

files = '/6d_10_0/vectors.npy,/6d_10_1/vectors.npy'
[Archive.zip](https://github.com/milvus-io/milvus/files/8692026/Archive.zip)

**Comment by yhmo** [comment]
Fixed by https://github.com/milvus-io/milvus/pull/17105
Not allow duplicate file name for numpy file, even they are in different path.
