### ISSUE TITLE
[Bug]:  Etcd crashloop on k8s

### ISSUE THREAD

**Issue by korjavin** [milvus-io/milvus#17007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.1
- Deployment mode(standalone or cluster): k8s cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS):  containeros
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

From time to time after one of etcd nodes stuck into enternal crashloop with a message
```
etcd 05:27:29.43 INFO  ==> Initializing etcd
etcd 05:27:29.44 INFO  ==> Detected data from previous deployments
etcd 05:27:29.56 INFO  ==> Updating member in existing cluster
Error: bad member ID arg (strconv.ParseUint: parsing "": invalid syntax), expecting ID in Hex

```

### Expected Behavior

I'd expect that etcd can survive restart.

### Steps To Reproduce

```markdown
1. k8s helm installation
2. Load some data
3. Restart etcd
```

### Milvus Log

```markdown
etcd 05:27:29.43 INFO  ==> Initializing etcd
etcd 05:27:29.44 INFO  ==> Detected data from previous deployments
etcd 05:27:29.56 INFO  ==> Updating member in existing cluster
Error: bad member ID arg (strconv.ParseUint: parsing "": invalid syntax), expecting ID in Hex
```

**Comment by LoveEachDay** [comment]
This is a known issue for bitnami/etcd. You can find related issues here:

bitnami/bitnami-docker-etcd#29
bitnami/bitnami-docker-etcd#39
@korjavin If you encounter this problem, you'd manually remove the /bitnami/etcd/data/member_id file from this pod's pvc volume.

**Comment by yanliang567** [comment]
@korjavin please retry with suggestion above.
/assign @korjavin 

/unassign
