### ISSUE TITLE
[Enhancement]: ChunkManager interface should support ctx

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#17013]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Current chunk manager didn't accept ctx for timeout and tracing control.
such as:
       Read(ctx, Context, filePath string) ([]byte, error)

**Comment by e11jah** [comment]
hi, @xiaofan-luan Are you saying add context for LocalChunkManager? What will happen if the context has been canceled outside when writing the local file?

**Comment by e11jah** [comment]
It seems that it needs to be changed to asynchronous io to facilitate context control. 😂

**Comment by xiaofan-luan** [comment]
> f the context has been canceled outside when writing the local file?

Yep, both local and minio chunkmanager should support context and have a way to control timeout and trace I guess

**Comment by xiaofan-luan** [comment]
This would help on adding more trace later~

**Comment by e11jah** [comment]
@xiaofan-luan 
Storing context in structures may lead to confusion. 
The caller’s lifetime is intermingled with a shared context, and the context is scoped to the lifetime where the ChunkManager is created. 
And both MinioChunkManager and LocalChunkManager should be refactored.
So I think it's better to divide this into several tasks.

More details in https://go.dev/blog/context-and-structs

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan Storing context in structures may lead to confusion. The caller’s lifetime is intermingled with a shared context, and the context is scoped to the lifetime where the ChunkManager is created. And both MinioChunkManager and LocalChunkManager should be refactored. So I think it's better to divide this into several tasks.
> 
> More details in https://go.dev/blog/context-and-structs

For storage it should be ok, but how do we control timeout for each request?

**Comment by e11jah** [comment]
> > @xiaofan-luan Storing context in structures may lead to confusion. The caller’s lifetime is intermingled with a shared context, and the context is scoped to the lifetime where the ChunkManager is created. And both MinioChunkManager and LocalChunkManager should be refactored. So I think it's better to divide this into several tasks.
> > More details in https://go.dev/blog/context-and-structs
> 
> For storage it should be ok, but how do we control timeout for each request?

Maybe using the context of the rpc request is the way to control timeout for each request... but I can't find where the ChunkManager be called.
