### ISSUE TITLE
[Enhancement]: Add logic for search grouping

### ISSUE THREAD

**Issue by czs007** [milvus-io/milvus#17021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Currently,  search/query requests for the same Collection are executed sequentially in the querynode.
Additionally, search requests for different Collections are executed concurrently.
This looks messy. The querynode does not manage the concurrency of tasks very well.

1. we should improve the logic of task_scheduler to manage the concurrency of tasks.
2. When there are a large number of small nq search requests for the same Collection, it is convenient to improve cpu utilization through search grouping, thereby improving throughput

### Why is this needed?

Performance matters

**Comment by xiaofan-luan** [comment]
good suggestion,
I would suggest to use search grouping rather than search merging so it's more clear
