### ISSUE TITLE
[Feature]: Support Search By ID

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#17029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Currently, We can combine 2 APIs to ack like SearchByID: 
1. `vectors = query(expr=f"id in {ids}", output_field=["embeddings"])`
2. `search(vectors)`

It's inconvenient and inefficient, I'd like an API to directly SearchByID 
`search(ids)`

Some works has been done: #10236, milvus-io/pymilvus#752. I'll start here and redesign, reimplement this feature, follow the below steps:

- [ ] Write design docs of SearchByID
- [ ] Implement SearchByID with UT >= 80%
- [ ] Make SearchByID passing the stability tests
- [ ] Benchmark with the previous 2-APIs way, at the expectation of more efficiency

**Comment by xiaofan-luan** [comment]
keep it open

**Comment by XuanYang-cn** [comment]
Closing for done

**Comment by xiaofan-luan** [comment]
> Closing for done

Did we have it already?

**Comment by xiaofan-luan** [comment]
keep it open
