### ISSUE TITLE
docker server connection error

### ISSUE THREAD

**Issue by rose-jinyang** [milvus-io/milvus#1703]
Hello
I've installed the latest milvus docker image and pymilvus-0.2.8.
I started milvus server as documentaion step-by-step and ran python3 example.py.
But I've faced the following server connection error.
![image](https://user-images.githubusercontent.com/47862419/77054648-fcb29280-6a0a-11ea-8e8a-d884751fc7dc.png)
I made the main folder called "milvus" and child folders called "logs", "db" and "conf".
I used the copies of config files in the folder "milvus/core/conf/demo"
Could u help me?
Thanks

**Comment by BossZou** [comment]
Hello, may you tell me which operating system you use, and you can run cmd `docker ps -a` in terminal and paste the output here, or try to check if port 19530 is in used and available if you mapped port to your host machine.

**Comment by rose-jinyang** [comment]
Thanks for your reply.
I am using Windows 10 Pro 64bit.
I started server with the following command.
![image](https://user-images.githubusercontent.com/47862419/77059943-bbbe7c00-6a12-11ea-99fc-6c4fbfb785a9.png)
The result of the command "docker ps -a" is the following:
![image](https://user-images.githubusercontent.com/47862419/77060022-ddb7fe80-6a12-11ea-8ac5-5a33d73c4397.png)
I've checked whether the port 19530 is being used by other process.
![image](https://user-images.githubusercontent.com/47862419/77060494-9e3de200-6a13-11ea-8ae1-227bffa8b799.png)

**Comment by JinHai-CN** [comment]
@rose-jinyang Can you check the docker logs if the server started successfully?

**Comment by rose-jinyang** [comment]
Well, I'm strange why there is not any log file in logs folder.

**Comment by rose-jinyang** [comment]
Hello
Please help me so that this issue can be fixed asap.
Thanks

**Comment by BossZou** [comment]
Hello @rose-jinyang , I noticed that the status of milvus container is 'Created' rather than 'Up', so I guess that there was error when milvus container tried to launch. May you run cmd `docker logs ${milvus container id}` to check logs outputted on container console. Or you can find more help about docker [here](https://stackoverflow.com/questions/43734412/what-does-created-container-mean-in-docker)

**Comment by rose-jinyang** [comment]
Hello, Thanks for your help.
I've fixed this issue by help of developer Shiyu.
The resaon was that the memory size in Docker setting was less as 2GB.
So I made this memory size increase to 5GB.
At the end, the milvus server started.
