### ISSUE TITLE
Limit the insert data batch size

### ISSUE THREAD

**Issue by JinHai-CN** [milvus-io/milvus#1705]
**Is your feature request related to a problem? Please describe.**
Currently, we don't limit the data insert batch size.

**Describe the solution you'd like**
We need to limit the batch data size to 256MB. (128K * 512 dimension vectors)

**Comment by yhmo** [comment]
Already fixed in pr1936. If insert batch data larger than 256MB, client will get error "The amount of data inserted each time cannot exceed 256 MB", and operation will be skipped
