### ISSUE TITLE
refactor kafka msgstream implementation

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#17068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

- Add some limitations just to support the following case:
  1.   can not invoke Seek after Chan 
  2.   can not invoke Seek  after Seek
  3.   either only invoke Chan or Invoke Chan after seek
- Add a goroutine to consume events of the Producer events channel 
- Remove produce retry when delivery chan value is nil

**Comment by wowococo** [comment]
Are you trying to use Producer events channel instead of deliveryChan ?

**Comment by jaime0815** [comment]
> Are you trying to use Producer events channel instead of deliveryChan ?

Nope, delivery chan is sync produce usage, but still needs to invoke Produce events, or it may occur hang on the client-side
