### ISSUE TITLE
Add a unit for buffer_size default value

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#1706]
## Report incorrect documentation

**Location of incorrect documentation**
https://www.milvus.io/docs/v0.7.0/reference/milvus_config.md
Section wal_config
buffer_size  has no unit

**Describe the problems or issues found in the documentation**
Add a unit for buffer_size default value:
buffer_size     256(MB)

**Comment by yamasite** [comment]
Already fixed in https://github.com/milvus-io/docs/commit/b7373f4df9b72f4bb57779b331ef3705a7686f34
