### ISSUE TITLE
[Bug]: VectorChunkManager will have great performance downgrade if localCache is disabled

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#17062]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: d6bb86d
- Deployment mode(standalone or cluster): both
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When `localCacheEnabled` is set to `false` when create a `VectorChunkManager`, the binlog file will be retrieved EVERY time `segment.fillFieldData` is called. 
Which means, if the original vector is needed for a Query on a collection with an index does not store the original vector, for each vector returned, a minio get operation will be performed.
Say, 100000 records meet the query criteria, 100000 minio get operations are needed, which cause the unacceptable performance downgrade.

### Expected Behavior

There shall not be performance downgrade at this scale when `localCache` is disabled.

### Steps To Reproduce

```markdown
1. Set queryNode.CacheEnabled to false in milvus.yaml
2. Query vectors with large scale
```

### Anything else?

See also #17038

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```gfm
> - Milvus version: d6bb86d
> - Deployment mode(standalone or cluster): both
> - SDK version(e.g. pymilvus v2.0.0rc2):
> - OS(Ubuntu or CentOS): 
> - CPU/Memory: 
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> When `localCacheEnabled` is set to `false` when create a `VectorChunkManager`, the binlog file will be retrieved EVERY time `segment.fillFieldData` is called. Which means, if the original vector is needed for a Query on a collection with an index does not store the original vector, for each vector returned, a minio get operation will be performed. Say, 100000 records meet the query criteria, 100000 minio get operations are needed, which cause the unacceptable performance downgrade.
> 
> ### Expected Behavior
> There shall not be performance downgrade at this scale when `localCache` is disabled.
> 
> ### Steps To Reproduce
> ```gfm
> 1. Set queryNode.CacheEnabled to false in milvus.yaml
> 2. Query vectors with large scale
> ```
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> See also #17038

Knowing it, any suggestion?
@czs007 @sunby @xige-16

**Comment by xiaofan-luan** [comment]
One possible solution is to retrieve through index, but not all index support get original vector, such as IVFPQ

**Comment by xiaofan-luan** [comment]
Another possible solution is to load vector into memory, that's why we enable local cache because we don't want to load original vector into memory

**Comment by xiaofan-luan** [comment]
might also be related to https://github.com/milvus-io/milvus/issues/17006

**Comment by xige-16** [comment]
If the binlig file corresponding to the raw data can be found through the pks or rowID of the search/query result, then we can only pull the data of the specified binlog file, instead of pulling the segment's all binlog data when cache==false.

**Comment by xige-16** [comment]
> If the binlig file corresponding to the raw data can be found through the pks or rowID of the search/query result, then we can only pull the data of the specified binlog file, instead of pulling the segment's all binlog data when cache==false.

In this way, we may need to control that the range of rowIDs corresponding to different binlog files cannot overlap.

**Comment by xiaofan-luan** [comment]
we will close it, the new vector chunk manager will be written in cpp and support local disk
