### ISSUE TITLE
[Enhancement]: Set timestamp in server side in case of Bounded consistency level

### ISSUE THREAD

**Issue by czs007** [milvus-io/milvus#17087]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Currently for Bound consistency, the client takes the client's time minus the default configured 5 seconds as the gurarantee_timestamp.
When the client time and server time are very different, this leads to the failure of Bound consistency. see https://github.com/milvus-io/milvus/issues/16841

I would like to change the strategy to:
For Bounded Consistency, client-side set guarantee_timestamp to 2.
On the server side, set the timestamp to the arrival time  minus the default configured interval (5 seconds)  if recevied guarantee_timestamp is 2.

Currently we have made some special settings for guarantee_timestamp.
When guarantee_timestamp is 0, the proxy will change it to the time when the request arrives at the server.This is the effect of Strong consistency.

When the guarantee_timestamp is 1, the proxy does not change it. Since the service time of querynode will be always greater than 1, it is the effect of Eventually consistency.

Now, we add a new special setting for guarantee_timestmap:
if guarantee_timestamp is 2, proxy will change it to the arrival time  minus the default configured interval.

### Why is this needed?

The settings of guarantee_timestamp and travel_timestamp will affect the effect of search grouping, so this logic needs to be clarified.

**Comment by congqixia** [comment]
Make sense. In my first opinion, client/sdk shall pass a duration instead of ts to avoid time lag issue. In this case, bounded consistency level works like the built-in duration const.

**Comment by xiaofan-luan** [comment]
looks good to me~
