### ISSUE TITLE
奇怪的查询

### ISSUE THREAD

**Issue by CrazyBeeline** [milvus-io/milvus#1710]
1.我创建了一张表:test
2.添加索引
{
  "index_type": "IVFSQ8",
  "params": {
   "nlist":16384
  }
}
3.插入特征
{
  "vectors": [[xxxx]
],
  "ids": [4]
}
4.查询结果
{
    "num":1,
    "result":[
        [
            {
                "distance":"1.000000",
                "id":"4"
            },
            {
                "distance":"340282346638528859811704183484516925440.000000",
                "id":"-1"
            }
        ]
    ]
}
版本：0.7.0
部署：docker milvusdb/milvus:0.7.0-gpu-d031120-40c7e8
交互方式：Milvus RESTful API
是否使用gpu：否

**Comment by JinHai-CN** [comment]
What is the TopK in your query?

**Comment by CrazyBeeline** [comment]
{
  "search": {
      "topk": 100,
      "vectors": [[XXX]],
      "params": {
          "nprobe": 16
      }
  }
}

**Comment by JinHai-CN** [comment]
How many vectors in your collection?

**Comment by CrazyBeeline** [comment]
just  one

**Comment by JinHai-CN** [comment]
Then the vectors which id is -1 with very large distance, just isn't valid result. Just ignore them.

**Comment by yamasite** [comment]
@CrazyBeeline Your topk is larger than the actual number of vectors. Please refer to this FAQ for more info. https://milvus.io/docs/v0.7.0/faq/operational_faq.md#Why-there-are-vectors-with--1-as-IDs-in-my-search-result

**Comment by CrazyBeeline** [comment]
明白了  非常感谢
