### ISSUE TITLE
Add mysql meta service description in milvus documentation

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#1711]
## Report incorrect documentation

**Location of incorrect documentation**
https://www.milvus.io/docs/v0.7.0/reference/data_manage.md

**Comment by yhmo** [comment]
# 元数据后台管理服务

Milvus 默认使用sqlite作为元数据后台管理服务，sqlite内嵌于Milvus进程中，无需启动额外服务。但我们强烈建议使用MySQL作为元数据管理服务，
尤其是在生产环境中，主要基于可靠性的考虑。
以MySQL作为元数据管理服务，请参考以下步骤：
-   拉取MySQL最新镜像
```shell 
docker pull mysql:latest
```
-   启动MySQL服务（密码和端口可自行设置）
```shell 
docker run -p 3306:3306 -e MYSQL_ROOT_PASSWORD=123456 -d mysql:latest
```
-   使用root账号登录MySQL，回车后提示你输入密码，输入上一步设置的密码
```shell 
mysql -h127.0.0.1 -uroot -p
```
-   进入MySQL客户端命令行，创建一个database，名称可自行设定，这里取为‘milvus’
```shell 
create database milvus
```

-   退出MySQL客户端, 修改server_config.yaml文件的backend_url，注意密码，端口以及database名称要和以上几步的设置一致
```shell 
backend_url: mysql://root:123456@127.0.0.1:3306/milvus
```
-   使用修改过的server_config.yaml启动Milvus服务

**Comment by yamasite** [comment]
Fixed in https://github.com/milvus-io/docs/pull/430/files
