### ISSUE TITLE
[Bug]: UpdateTimeTick failed: skip ChannelTimeTickMsg from un-recognized session 

### ISSUE THREAD

**Issue by WangErXiao** [milvus-io/milvus#17124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.2
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I upgrade proxy pod, search service fails.
 i see the error log as below

```
sendChannelsTimeTickLoop.UpdateChannelTimeTick] [ErrorCode=UnexpectedError] [Reason="UpdateTimeTick failed: skip ChannelTimeTickMsg from un-recognized session 22"]
```

### Expected Behavior

search service success

**Comment by xiaofan-luan** [comment]
should be recovered for a while?
it usually means proxy is crashed without a session but still keep sending request.
try to restart all proxy(or proxy with nodeID 22) see if it helps

**Comment by WangErXiao** [comment]
It can't recover for a while.
My three proxy nodes all failed ,display same log with different session id;

After I restart all proxy node ,it still not works.

**Comment by WangErXiao** [comment]
I worry about that if milvus services receive online product traffic, how can I upgrade milvus without loss?

**Comment by WangErXiao** [comment]
After restarting rootCoord, it recovered !   Why?

**Comment by yanliang567** [comment]
@xiaofan-luan could you please help on this issue?
/assign @xiaofan-luan

**Comment by xiaofan-luan** [comment]
> After restarting rootCoord, it recovered ! Why?

could you offer rootcoord log before start so I can help on investigating~

**Comment by WangErXiao** [comment]
Sorry, I didn't keep the log.  When this problem occur again, I will catch the log.

**Comment by yanliang567** [comment]
please use this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation
