### ISSUE TITLE
[Bug]: build error, AutoMoc subprocess error

### ISSUE THREAD

**Issue by minleminzui** [milvus-io/milvus#17123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.x
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus v2.0.0rc2
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others: Linux LAPTOP-PU9O0ADC 5.10.16.3-microsoft-standard-WSL2
- gcc (GCC)  9.4.0 
- cmake version 3.23.0
- moc 5.12.8
```

### Current Behavior

When I build milvus， I encountered  a compilation error 
![image](https://user-images.githubusercontent.com/54172054/169443401-e2906567-3dba-4c09-8fec-ec3dd57c0b3b.png)
And this is content in TQTcpServer.h, please reference to [code](https://pastebin.ubuntu.com/p/DdhWzgrBK2/)

**Comment by xiaofan-luan** [comment]
hi @minleminzui , we don't tried wsl on our environment.
One way to work around is to user docker, CentOS or ubuntu should work.
It seems that thrift is a dependency of arrow community, maybe we should ask them for help~~

**Comment by minleminzui** [comment]
thanks

**Comment by yanliang567** [comment]
@minleminzui please feel free to close this issue, after you built successfully as suggested above.
