### ISSUE TITLE
Partition : add has_partition method , and auto create partition if not exist when creating index

### ISSUE THREAD

**Issue by RifeWang** [milvus-io/milvus#1713]
问题：在新增向量时，如果指定了 partition ，而这个 partition 又不存在，目前会直接报错 `partition not found` 。

建议：在这种情况下 milvus 自动去创建这个 partition ，然后正常插入向量。

理由：partition 实际上具有与其所属 collection 一致的结构，在 collection 已经存在的情况下，通过类似于 NOSQL 数据库去弱化 partition 的存在，在使用上会更加方便。

另外建议增加一个 `has_partition` 方法，去判断某个具体的 partition 是否存在，当前 `collection_info` 和 `show_partitions` 方法都是直接返回了全部数据，如果 partition 过多则处理起来不够有针对性。

**Comment by JinHai-CN** [comment]
HasPartition method looks like an useful API.

**Comment by yhmo** [comment]
add has_partition api issue #1962
