### ISSUE TITLE
[Bug]: string data type not supported yet, please use VarChar type instead

### ISSUE THREAD

**Issue by Derekhe01** [milvus-io/milvus#17130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.2
- Deployment mode(standalone or cluster): ansible cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.0.2
- OS(Ubuntu or CentOS):  Ubuntu 20.04
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

FieldSchema(name="vid", dtype=DataType.STRING),

>>> Picture = Collection("Picture", schema)
error_code: UnexpectedError
reason: "string data type not supported yet, please use VarChar type instead"

RPC error: [create_collection], <BaseException: (code=1, message=string data type not supported yet, please use VarChar type instead)>, <Time:{'RPC start': '2022-05-20 07:18:45.327026', 'RPC error': '2022-05-20 07:18:45.330937'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 144, in __init__
    conn.create_collection(self._name, fields=schema.to_dict(), shards_num=self._shards_num,
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 145, in create_collection
    raise BaseException(status.error_code, status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=string data type not supported yet, please use VarChar type instead)>

**But there is no VarChar type in DataType...**

**Comment by yanliang567** [comment]
sounds like pymilvus reports a wrong error msg. But it is true that Milvus 2.0.2 does not support string data type yet. it is going to be supported in Milvus 2.1, which will be released soon in May.

**Comment by xige-16** [comment]
dataType::string not support,  please use VarChar type instead.

**Comment by xige-16** [comment]
> h will be released soon in May.

In milvus 2.1 and master branch

**Comment by xige-16** [comment]
> which will be released soon in Ma

milvus 2.1 will not support DataType::string, only support DataType::VarChar for string data

**Comment by yanliang567** [comment]
@Derekhe01 could you please double confirm the pymilvus version?

**Comment by xiaofan-luan** [comment]
we are not gonna to support string in a long period

**Comment by Rosesqy** [comment]
Hi, I still got error "message=string is not supported now" with datatype:VARCHAR, and I've checked my pymilvus version is 2.1.1, the data I tried to insert is like ['1','2',...]

**Comment by yanliang567** [comment]
@Derekhe01 could you please file a new issue and attach the code snippet to reproduce the issue?

**Comment by cherrot** [comment]
> we are not gonna to support string in a long period

Then why could we declare string type in your SDK?

**Comment by xiaofan-luan** [comment]
> > we are not gonna to support string in a long period
> 
> Then why could we declare string type in your SDK, like [here](https://github.com/milvus-io/milvus-sdk-go/blob/064f60ca21c32971660fa53312553846734206fc/entity/schema.go#L436) ?

This is just for future extension, sorry for the confusion.
