### ISSUE TITLE
[Bug]: Segment lock is messed up

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#17151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Currently the segPtrMu is happened inside segment, which is a mess up.
1.  we don't want to check err for every getSegmentByID... it's error prone
2. for example, in segmentPreInsert, we get this lock, but didn't check whether the segment is closed or not.
       func (s *Segment) segmentPreInsert(numOfRecords int) (int64, error) {
	/*
		long int
		PreInsert(CSegmentInterface c_segment, long int size);
	*/
	s.segPtrMu.RLock()
	defer s.segPtrMu.RUnlock() // thread safe guaranteed by segCore, use RLock

        //=========================================need a double check here!!
    
	if s.segmentType != segmentTypeGrowing {
		return 0, nil
	}
	var offset int64
	cOffset := (*C.int64_t)(&offset)
	status := C.PreInsert(s.segmentPtr, C.int64_t(int64(numOfRecords)), cOffset)
	if err := HandleCStatus(&status, "PreInsert failed"); err != nil {
		return 0, err
	}
	return offset, nil
} 

### Expected Behavior

we need to acquire this lock before search/query/delete/insert execution, and release when the op done, otherwise the segment itself maybe removed

**Comment by bigsheeper** [comment]
I'll fix it

**Comment by xiaofan-luan** [comment]
@bigsheeper does the segmentPtr lock also guard for delete and insert?

**Comment by bigsheeper** [comment]
> @bigsheeper does the segmentPtr lock also guard for delete and insert?

Yes，now collection mutex would guard for both delete and insert

**Comment by xiaofan-luan** [comment]
remove the urgent label for now
