### ISSUE TITLE
希望“新增分区表数据更新tag后，该数据自动移动至新tag对应的分区表“的功能

### ISSUE THREAD

**Issue by oswen** [milvus-io/milvus#1715]
目前在使用milvus的分区表功能，但是发现一个问题，比如目前table1中有两个分区表a和b，对应tag1和tag2，我有一条数据需要由tag1更新到tag2，发现新数据已更新到分区表b中，但是分区表a中依然存储旧数据，这样如何实现分区表的数据更新呢？

**Comment by JinHai-CN** [comment]
Currently, the ID of each entity(record) isn't unique. In future release, you can't insert the entity(record) with same ID into same collection. At that time, insert the new entity(record) with same ID will override the old one.

**Comment by oswen** [comment]
> Currently, the ID of each entity(record) isn't unique. In future release, you can't insert the entity(record) with same ID into same collection. At that time, insert the new entity(record) with same ID will override the old one.

So if you update the tag of a record, it will also refresh the tag?

**Comment by yhmo** [comment]
Firstly use "delete_by_id" to delete the vector from the collection, secondly use "insert" to add a new vector with same id into partition 'b'.
