### ISSUE TITLE
[Feature]: use milvus in Singularity

### ISSUE THREAD

**Issue by skye95git** [milvus-io/milvus#17165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I face a problem, on our server, normal user doesn't have permission to use docker, but can use Singularity. Can Milvus run in Singularity? If so, how do I install Milvus?

### Describe the solution you'd like.

Wish I could start milvus directly in Singularity like running `sudo docker-compose up -d`.

**Comment by xiaofan-luan** [comment]
what is singularity? any inputs?

**Comment by skye95git** [comment]
> what is singularity? any inputs?

Singularity is a container used on supercomputing clusters, similar to Docker.
Or do you have a Docker image of Milvus? I can convert the Docker image into a Singularity image.

**Comment by xiaofan-luan** [comment]
> > what is singularity? any inputs?
> 
> Singularity is a container used on supercomputing clusters, similar to Docker. Or do you have a Docker image of Milvus? I can convert the Docker image into a Singularity image.

Sure we do~ most of scripts are under scripts dir, thought @LoveEachDay could help you on it~

**Comment by JackLCL** [comment]
@skye95git 
You can find the milvus docker image [here](https://hub.docker.com/r/milvusdb/milvus/tags).

**Comment by skye95git** [comment]
> @skye95git You can find the milvus docker image [here](https://hub.docker.com/r/milvusdb/milvus/tags).

Thanks, I will try it.

**Comment by complexly** [comment]
> > @skye95git You can find the milvus docker image [here](https://hub.docker.com/r/milvusdb/milvus/tags).
> 
> Thanks, I will try it.

Hi @skye95git, I am wondering if you have succeeded in running milvus on singularity? I came across difficulties for the root/sudo issues, could you share some of your singularity-compose file? Thanks!
