### ISSUE TITLE
[Bug]:  [kafka] Query result is not empty after deletion operation

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#17176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: latest 
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.1.0.dev61
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Query result is not empty after deletion operation

FAILED cases:
```
FAILED testcases/test_delete.py::TestDeleteParams::test_delete_expr_single - ...
FAILED testcases/test_delete.py::TestDeleteParams::test_delete_entities[True]
FAILED testcases/test_delete.py::TestDeleteOperation::test_delete_after_index
FAILED testcases/test_delete.py::TestDeleteString::test_delete_sealed_data_channel_delete_with_string
FAILED testcases/test_delete.py::TestDeleteString::test_delete_expr_repeated_values_with_string
FAILED testcases/test_delete.py::TestDeleteString::test_delete_flush_loop_with_string
```

### Expected Behavior

Query result is empty after deletion operation

### Steps To Reproduce

Nightly:
https://ci.milvus.io:18080/jenkins/blue/rest/organizations/jenkins/pipelines/milvus-nightly-ci/branches/master/runs/548/nodes/64/steps/177/log/?start=0

### Milvus Log

Taking one failed case as an example:

1. milvus log:
[artifacts-milvus-distributed-kafka-master-548-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/548/artifact/artifacts-milvus-distributed-kafka-master-548-pymilvus-e2e-logs.tar.gz)

2. FAILED case:
[2022-05-23T19:06:03.682Z] [gw0] [ 14%] FAILED testcases/test_delete.py::TestDeleteParams::test_delete_expr_single 

3. collection name: delete_p69WiQNV

4. Test logs:
```
[2022-05-23T20:14:57.481Z] self = <test_delete.TestDeleteParams object at 0x7f57d04eeeb8>
[2022-05-23T20:14:57.481Z] 
[2022-05-23T20:14:57.481Z]     @pytest.mark.tags(CaseLabel.L1)
[2022-05-23T20:14:57.481Z]     def test_delete_expr_single(self):
[2022-05-23T20:14:57.481Z]         """
[2022-05-23T20:14:57.481Z]         target: test delete with one value
[2022-05-23T20:14:57.481Z]         method: delete with expr: "id in [0]"
[2022-05-23T20:14:57.481Z]         expected: Describe num entities by one
[2022-05-23T20:14:57.481Z]         """
[2022-05-23T20:14:57.481Z]         # init collection with tmp_nb default data
[2022-05-23T20:14:57.481Z]         collection_w = self.init_collection_general(prefix, nb=tmp_nb, insert_data=True)[0]
[2022-05-23T20:14:57.481Z]         expr = f'{ct.default_int64_field_name} in {[0]}'
[2022-05-23T20:14:57.481Z]         del_res, _ = collection_w.delete(expr)
[2022-05-23T20:14:57.481Z]         assert del_res.delete_count == 1
[2022-05-23T20:14:57.482Z] >       collection_w.query(expr, check_task=CheckTasks.check_query_empty)
[2022-05-23T20:14:57.482Z] 

[2022-05-23T20:14:57.482Z] >       assert len(query_res) == 0, "Query result is not empty"
[2022-05-23T20:14:57.482Z] E       AssertionError: Query result is not empty
```

**Comment by binbinlv** [comment]
It appears in the latest 2 nightly, so set it as critical.

**Comment by jaime0815** [comment]
#16961 same issue

**Comment by xiaofan-luan** [comment]
consistency might be the reason of the issue, but need further investigation, any idea why we not open those issues in nightly regression before? @binbinlv

**Comment by binbinlv** [comment]
@xiaofan-luan 
Actually, there is a similar issue  #16961. 

And from the comments in #16961, we could know the delete issue occurs in the nightly (pulsar) was ever fixed by gexi and has not been reproduced for a period of time. But as the latest comment of #16961, it occurs again for one time in pulsar, but the latest yesterday nightly, it is OK, so in pulsar nightly, this issue is randomly reproduced in low probability.

In kafka pipeline, it is reproduced in high probability, from the latest 2 nightly yesterday, the delete issue is reproduced steadily.

Because it is reproduced steadily in kafka pipeline (but in pulsar pipeline, it is random reproduced in low probability), so I open this issue in case of different root cause of issue #16961.

Thanks.

**Comment by longjiquan** [comment]
similar to #16961 , the order of dml channels used by delete later differs from the order used by insert.

rootcoord:
```log
43581:[2022/05/23 19:05:58.097 +00:00] [DEBUG] [task.go:139] ["collection name -> id"] ["collection name"=delete_p69WiQNV] [collection_id=433411262532550657] ["default partition id"=433411262532550658]
```

proxy:
```log
35137:[2022/05/23 19:05:58.182 +00:00] [DEBUG] [channels_mgr.go:368] [singleTypeChannelsMgr] [collection_id=433411262532550657] [createMsgStream.getChannels="{\"by-dev-rootcoord-dml_240_433411262532550657v0\":\"by-dev-rootcoord-dml_240\",\"by-dev-rootcoord-dml_241_433411262532550657v1\":\"by-dev-rootcoord-dml_241\"}"]
35143:[2022/05/23 19:05:58.183 +00:00] [DEBUG] [channels_mgr.go:368] [singleTypeChannelsMgr] [collection_id=433411262532550657] [createMsgStream.getChannels="{\"by-dev-rootcoord-dml_240_433411262532550657v0\":\"by-dev-rootcoord-dml_240\",\"by-dev-rootcoord-dml_241_433411262532550657v1\":\"by-dev-rootcoord-dml_241\"}"]
```

**Comment by binbinlv** [comment]
@longjiquan  could you please have a check? Thanks.

Latest nightly failure about delete:
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/574/pipeline

1. Milvus logs:
[artifacts-milvus-distributed-kafka-master-574-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/574/artifact/artifacts-milvus-distributed-kafka-master-574-pymilvus-e2e-logs.tar.gz)


2. Failed cases:
(1) FAILED testcases/test_delete.py::TestDeleteParams::test_delete_expr_single - ...
      collection name: delete_GXO5uZeM

(2) FAILED testcases/test_delete.py::TestDeleteParams::test_delete_entities[True]
      collection name: delete_AN6Z8ZBD

(3) FAILED testcases/test_delete.py::TestDeleteParams::test_delete_entities[False]
     collection name: delete_rc1aLtAy

(4) FAILED testcases/test_delete.py::TestDeleteOperation::test_delete_flush_loop
      collection name: delete_0c1uTVXc

(5) FAILED testcases/test_delete.py::TestDeleteOperation::test_delete_entity_loop
      collection name: delete_yE4jRZt3

(6) FAILED testcases/test_delete.py::TestDeleteString::test_delete_entity_loop_with_string
      collection name: delete_76wmndOP

**Comment by longjiquan** [comment]
case delete_GXO5uZeM

```shell
$ grep -n "collection name -> id" mdk-574-n-milvus-rootcoord-797c44d95b-j69gs_milvus-ci_rootcoord-840f0ee40ff699254dd50604e93019a7135fdccbbbd12706508098ee9acb16a0.log | grep delete_GXO5uZeM
44011:[2022/06/05 15:06:41.942 +00:00] [DEBUG] [task.go:139] ["collection name -> id"] ["collection name"=delete_GXO5uZeM] [collection_id=433701939295289345] ["default partition id"=433701939295289346]
```

querynode didn't receive delete message:

```shell
$ grep -n "delete in historical" mdk-574-n-milvus-querynode-79c9bc4876-9dc6d_milvus-ci_querynode-fb9294c7fa6855849c58cab402ec5166bda2b1ab710970e7dd537574c7286b85.log | grep 433701939295289345 | wc -l
0
$ grep -n "delete in historical" mdk-574-n-milvus-querynode-79c9bc4876-pjhcl_milvus-ci_querynode-06f07af85bfd20aba39ea0a041cc60be1fb3c2185d28158779cc03d4826994c6.log | grep 433701939295289345 | wc -l
0
```
