### ISSUE TITLE
Register querynode of the same address(ip:port) into etcd

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#17174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

We can find querynode with the same address in this log [artifacts-milvus-distributed-PR-17042-17-pymilvus-e2e-logs.tar.gz](https://github.com/milvus-io/milvus/files/8754698/artifacts-milvus-distributed-PR-17042-17-pymilvus-e2e-logs.tar.gz)

![image](https://user-images.githubusercontent.com/4024711/169827229-230aab08-a15f-43d0-95ef-5d15d451dc6b.png)

### Expected Behavior

We should forbid using the same address for querynode

**Comment by xiaofan-luan** [comment]
@jaime0815 this not a issue.
I guess the original QueryNode ID 4 crash and we bring in a new one

**Comment by xiaofan-luan** [comment]
we only specify querynode by its ID but not ip address

**Comment by jaime0815** [comment]
> we only specify querynode by its ID but not ip address

Querycoord communicates with QueryNode by IP address,  it may cause some issues if the different querynode use the same IP address

**Comment by xiaofan-luan** [comment]
> > we only specify querynode by its ID but not ip address
> 
> Querycoord communicates with QueryNode by IP address, it may cause some issues if the different querynode use the same IP address

It shouldn't happen, because querynode with same ip and port can not exist at the same time due to each port can be only registed by one process
The old querynode is possibly crashed, you should check if querynode 4 and 9 process still exists.

**Comment by xiaofan-luan** [comment]
we should never support register two querynode with same IP, even if the port is different

**Comment by xiaofan-luan** [comment]
> 

I guess we doesn't need to, and we should assume two pod would share the same ip.
