### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by minleminzui** [milvus-io/milvus#17181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.0.x
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus v2.0.0rc2
- OS(Ubuntu or CentOS): Ubuntu 20.04 in vmware
- CPU/Memory: 
- GPU: 
- Others: go: >= 1.16 cmake: >= 3.18 gcc: 9.4.0
```

### Current Behavior

when I build the milvus, I encountered  the following errors
![image](https://user-images.githubusercontent.com/54172054/169945436-becc8893-2fef-405d-8a35-dc3019e5b61c.png)
actually，I don't know how to modify the cmake file to solve this problem
thanks

**Comment by xiaofan-luan** [comment]
@minleminzui hi there, how do you compile milvus? this seems to be only a warning, any fatal errors?

**Comment by minleminzui** [comment]
there are all the content of the log [error.log](https://paste.ubuntu.com/p/5VjrrVdrf2/)
thanks

**Comment by minleminzui** [comment]
@xiaofan-luan

**Comment by minleminzui** [comment]
I compiled milvus in this way 
![image](https://user-images.githubusercontent.com/54172054/169959595-667786f0-d30e-4bca-a2fb-abaf3890ec44.png)

**Comment by longjiquan** [comment]
@minleminzui It seems that we missed some softwares in our `scripts/install_deps.sh`. Could you please install the below softwares first? I'll fix the `install_deps.sh` soon.

```shell
apt get install libtool m4 autoconf automake
```

**Comment by minleminzui** [comment]
@longjiquan  sure, thanks

**Comment by minleminzui** [comment]
it works,  but when I wanted to run milvus in [this way](https://milvus.io/cn/docs/v2.0.x/example_code.md) , I encountered another problem 
![image](https://user-images.githubusercontent.com/54172054/169981682-32659a56-328b-4be6-ae32-8b18b3e0daca.png)

**Comment by longjiquan** [comment]
@minleminzui You can disable the http proxy and https proxy and then retry this.

**Comment by minleminzui** [comment]
thanks, but it still can't work 
![image](https://user-images.githubusercontent.com/54172054/169984526-ed8b70fa-9b8e-4825-894f-9a6b49f6a83d.png)

**Comment by longjiquan** [comment]
@minleminzui can you provide the log of the Milvus server?

**Comment by minleminzui** [comment]
sorry，I don't konw how to run milvus server after compiling source code, actually，after `apt get install lcov libtool m4 autoconf automake`, I got the [build.log](https://paste.ubuntu.com/p/yCxB2P98tw/), does it mean that I built milvus successfully?  And I find a blog which build milvus in another way and start milvus server. Is this blog correct?thanks.

**Comment by longjiquan** [comment]
> sorry，I don't konw how to run milvus server after compiling source code, actually，after `apt get install lcov libtool m4 autoconf automake`, I got the [build.log](https://paste.ubuntu.com/p/yCxB2P98tw/), does it mean that I built milvus successfully? And I find a blog which build milvus in another way and start milvus server. Is this blog correct?thanks.

Yeah, it's right to tell developers or users to build Milvus from source code. But after Milvus was built, you then need to run Milvus.

**Comment by longjiquan** [comment]
@minleminzui Maybe you can refer to https://github.com/milvus-io/milvus/blob/master/DEVELOPMENT.md#e2e-tests to deploy Milvus.

**Comment by minleminzui** [comment]
> > sorry，I don't konw how to run milvus server after compiling source code, actually，after `apt get install lcov libtool m4 autoconf automake`, I got the [build.log](https://paste.ubuntu.com/p/yCxB2P98tw/), does it mean that I built milvus successfully? And I find a blog which build milvus in another way and start milvus server. Is this blog correct?thanks.
> 
> Yeah, it's right to tell developers or users to build Milvus from source code. But after Milvus was built, you then need to run Milvus.

I change the source code locally,  could you tell me which commands or shell scripts should I execute to run miluvs after I built the mlivus? I am attending the [ospp](https://summer-ospp.ac.cn/#/org/prodetail/227410327), I need to contibute some code to milvus when I apply for this project successfully. Thanks.

**Comment by longjiquan** [comment]
> > > sorry，I don't konw how to run milvus server after compiling source code, actually，after `apt get install lcov libtool m4 autoconf automake`, I got the [build.log](https://paste.ubuntu.com/p/yCxB2P98tw/), does it mean that I built milvus successfully? And I find a blog which build milvus in another way and start milvus server. Is this blog correct?thanks.
> > 
> > 
> > Yeah, it's right to tell developers or users to build Milvus from source code. But after Milvus was built, you then need to run Milvus.
> 
> I have changed the source code locally, could you tell me which commands or shell scripts should I execute to run miluvs after I built the mlivus? I am attending the [ospp](https://summer-ospp.ac.cn/#/org/prodetail/227410327), I need to contribute some code to milvus after I apply for this project successfully. Thanks.

```shell
cd deployments/docker/dev
docker-compose up -d
cd ../../..
./bin/milvus run standalone
```

**Comment by longjiquan** [comment]
Can you provide the way how you deploy Milvus in details? @minleminzui

**Comment by minleminzui** [comment]
The following script is the way how I deploy Milvus. Thanks. 
```
git clone https://github.com/milvus-io/milvus.git
cd milvus/
./scripts/install_deps.sh
sudo apt-get install lcov libtool m4 autoconf automake
make
cd deployments/docker/dev
docker-compose up -d
cd ../../..
./bin/milvus run standalone
```

**Comment by xiaofan-luan** [comment]
> It helps a lot, thanks. But another problem has arisen. After I executed `./bin/milvus run standalone` ![image](https://user-images.githubusercontent.com/54172054/170049261-600376ba-ea00-4deb-bb72-664f119d351e.png) It seems that there are something wrong about minio. ![image](https://user-images.githubusercontent.com/54172054/170049377-5b4cdbe7-bb5c-4d62-a2ac-a6899e106ae0.png)

you probably need to change milvus.yaml and set the disk directory to where you want to

**Comment by xiaofan-luan** [comment]
by default it is under /var directory and you might not has the access to this directory

**Comment by longjiquan** [comment]
> by default it is under /var directory and you might not has the access to this directory

Maybe it's not the wrong configuration caused this issue., by default local storage is disabled.
I googled some blogs, some of them said you should correct your time of computer.

**Comment by minleminzui** [comment]
thank you very much. It all works well.
