### ISSUE TITLE
[Bug]: service node registers wrong ip in cluster

### ISSUE THREAD

**Issue by nexttonever** [milvus-io/milvus#17191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.2
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.2
- OS(Ubuntu or CentOS):  CentOS
- CPU/Memory: 
- GPU: 
- Others: docker swarm
```

### Current Behavior

After I deployed a cluster via docker stack, a connection timeout error occurs when i do a query request via attu.
I found an error log in querynode:
```
milvus_querynode.1.ziuduryke2e7@mymachine    | [2022/05/24 07:14:58.784 +00:00] [WARN] [grpclog.go:46] ["[core]grpc: addrConn.createTransport failed to connect to {10.0.0.8:19530 10.0.0.8:19530 <nil> 0 <nil>}. Err: connection error: desc = \"transport: Error while dialing dial tcp 10.0.0.8:19530: i/o timeout\". Reconnecting..."]
```

my understanding is that querynode try to connect to proxy (10.0.0.8:19530), but failed becacuse the ip is not reachable.

i found the proxy has 3 ips:
```
root@mymachine:/data/milvus/docker# docker exec -it milvus_proxy.1.meuhl3zud732lucxh7odnm36r hostname -I
10.0.0.12 172.26.0.3 10.0.3.3
```

querynode only has 2 ips:
```
root@mymachine:/data/milvus/docker# docker exec -it milvus_querynode.1.3b3l75y6kt5dcbjm0jjyb1sls hostname -I
10.0.3.18 172.26.0.10
```

there are 3 docker network related in the question:
- milvus (10.0.3.0/24) --created by compose file
- ingress (10.0.0.0/24)
- docker_gwbridge (172.26.0.10/16)

etcd data:
```
# etcdctl get --prefix testmilvus/meta/session/proxy
testmilvus/meta/session/proxy-8
{"ServerID":8,"ServerName":"proxy","Address":"10.0.0.12:19530","TriggerKill":true}
#
```

---
The problem should be: 
querynode joined networks of milvus and docker_gwbridge,
proxy joined netwroks of milvus, docker_gwbridge, and ingress,
but proxy registered the ip under ingress, which is unreachable for querynode.

I have searched documents for a long time, but no solution is found.

How can i fix it?

**Comment by nexttonever** [comment]
@LoveEachDay
说英文真累，我说中文吧。

实际上我没打算设置多个网卡，那是docker swarm自动设置的。
如果将网络改为host模式，那么宿主机又是有多张网卡的，又要出问题。

所以可以指定一个配置项么？比如给proxy指定一个发布ip，或者发布域名，覆盖“随机选择”的逻辑。

**Comment by LoveEachDay** [comment]
> @LoveEachDay 说英文真累，我说中文吧。
> 
> 实际上我没打算设置多个网卡，那是docker swarm自动设置的。 如果将网络改为host模式，那么宿主机又是有多张网卡的，又要出问题。
> 
> 所以可以指定一个配置项么？比如给proxy指定一个发布ip，或者发布域名，覆盖“随机选择”的逻辑。

@nexttonever For now you cannot specify the publish ip address. You'd better try to use milvus with Kubernetes instead of Docker swarm.

**Comment by roemchine** [comment]
The issue still exists in Milvus version 2.2.x
I would also like to use Milvus in Docker swarm because Docker swarm is easier to set up than Kubernetes.
In my option, it makes more sense to be able to deploy the Milvus cluster with Docker on multiple nodes than just on a single node.

**Comment by xiaofan-luan** [comment]
> 

Not sure if there is still many user on docker swarm or normandy, but I guess it is still a good idea to deploy milvus on multiple dockers? anyone vote for this?

**Comment by yangxianpku** [comment]
>  你好，我最近也涉及使用docker stack部署milvus集群，能否提供下你的compose文件呢，非常感谢！
