### ISSUE TITLE
[Bug]: num_entities is wrong after delete or upsert

### ISSUE THREAD

**Issue by nexttonever** [milvus-io/milvus#17193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.2
- Deployment mode(standalone or cluster): 
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

as the title said.

this is the test script, copied from pymilvs doc:
```

from pymilvus import connections, Collection, FieldSchema, CollectionSchema, DataType
import random

# add connection config here
# connections.add_connection()
connections.connect()

schema = CollectionSchema([
     FieldSchema("film_id", DataType.INT64, is_primary=True),
     FieldSchema("film_date", DataType.INT64),
     FieldSchema("films", dtype=DataType.FLOAT_VECTOR, dim=2)
 ])

collection = Collection("test_collection_query", schema)

# insert 10 entities, and num_entities is ok
data = [
     [i for i in range(10)],
     [i + 2000 for i in range(10)],
     [[random.random() for _ in range(2)] for _ in range(10)],
 ]


collection.insert(data)

assert collection.num_entities == 10

collection.load()

# query all entities, size is ok 
res = collection.query("film_id >= 0")

assert len(res) == 10

# delete 5 entities, but num_entities is still 10
collection.delete(f"film_id in {[i for i in range(5)]}")

assert collection.num_entities == 10

# however query size is 5, that's ok
res = collection.query("film_id >= 0"]
assert len(res) == 5
```

**Comment by yanliang567** [comment]
this is a known issue in milvus 2.0.2, which is complicated and going to be fixed by some refactor work in 2.2 or later.
In short, the num_entities is not precise after deletion.

**Comment by nexttonever** [comment]
Got it

**Comment by James4Ever0** [comment]
have the same problem.

**Comment by xiaofan-luan** [comment]
We will keep this issue.
Some of the behaviour is by design, but we will see what we can do

**Comment by myoons** [comment]
Is there any updates about this issue?
I can't find updates related to this issue in 2.2 release.

**Comment by xiaofan-luan** [comment]
delete will not count into number entities, this is still by design

**Comment by myoons** [comment]
Thanks for reply. 

Then is there any way to get the exact number of entities in Collection?

**Comment by xiaofan-luan** [comment]
not yet, but we've been working on the count function for a while

**Comment by myoons** [comment]
Okay. I'll wait for update. Thanks for your job.

**Comment by xiaofan-luan** [comment]
> Okay. I'll wait for update. Thanks for your job.

We will have one beta release on 2.3, so it shouldn't be too long

**Comment by myoons** [comment]
Great!

**Comment by JingChen23** [comment]
Hi I'm using 2.4, seems the collection.num_entities is still unchanged after I delete all the entities from the collection.

If this is by design, could someone tell me or point me to a doc to let me know the purpose of this design?

**Comment by yanliang567** [comment]
we have not release 2.4 yet. Also 2.3.0 is still in beta. we are going to release v2.3.0 soon this month. please stay tuned.

> Hi I'm using 2.4, seems the collection.num_entities is still unchanged after I delete all the entities from the collection.
> 
> If this is by design, could someone tell me or point me to a doc to let me know the purpose of this design?

**Comment by JingChen23** [comment]
> we have not release 2.4 yet. Also 2.3.0 is still in beta. we are going to release v2.3.0 soon this month. please stay tuned.
> 
> > Hi I'm using 2.4, seems the collection.num_entities is still unchanged after I delete all the entities from the collection.
> > If this is by design, could someone tell me or point me to a doc to let me know the purpose of this design?

I'm using 2.2.9, sorry for telling the wrong version by mistake.
So is the meaning behind your words is that 2.3.0 will make a change to the current collection.num_entities logic?

**Comment by yanliang567** [comment]
in v2.3.0, it offers count(*) to return a precise number of entities, it looks like this:
```
res = hello_milvus.query(expr="", output_fields=["count(*)"])
print(res)
print(res[0])

# 结果如下：
# [{'count(*)': 3000}]
# {'count(*)': 3000}
```

**Comment by hoangph3** [comment]
You should run collection.flush() before run collection.num_entities. It's working!
