### ISSUE TITLE
[Enhancement]: Improve search grouping decision logic

### ISSUE THREAD

**Issue by czs007** [milvus-io/milvus#17209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

When judging whether the search can be grouped, it is also necessary to check whether the `SearchParams` are the same, such as `nprobe`, `efSearch` and other parameters.

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What would you like to be added?
> When judging whether the search can be grouped, it is also necessary to check whether the `SearchParams` are the same, such as `nprobe`, `efSearch` and other parameters.
> 
> ### Why is this needed?
> _No response_
> 
> ### Anything else?
> _No response_

might we just pick the largest of all?
