### ISSUE TITLE
[Bug]: TestLoadBalanceIndexedSegmentsAfterNodeDown times out

### ISSUE THREAD

**Issue by longjiquan** [milvus-io/milvus#17212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://pipelines.actions.githubusercontent.com/serviceHosts/c158e734-3f62-428e-85f8-58d396bf553e/_apis/pipelines/1/runs/61247/signedlogcontent/2?urlExpires=2022-05-25T06%3A21%3A28.3993207Z&urlSigningMethod=HMACV1&urlSignature=aQznq1qk5ocMHK7cKFvaQN%2FDYFwwAkgw7VruCdo2uzI%3D

**Comment by longjiquan** [comment]
It will be nice if you could help to fix this issue. @congqixia 
/assign @congqixia

**Comment by congqixia** [comment]
@longjiquan the link in the issue description may be temporary, I guess the universal link of the action shall be the following one?
https://github.com/milvus-io/milvus/runs/6585649979?check_suite_focus=true

**Comment by longjiquan** [comment]
> @longjiquan the link in the issue description may be temporary, I guess the universal link of the action shall be the following one? https://github.com/milvus-io/milvus/runs/6585649979?check_suite_focus=true

Yes, my mistake.
