### ISSUE TITLE
[Bug]: The amount of data inserted each time cannot exceed 256 MB

### ISSUE THREAD

**Issue by Igoslow** [milvus-io/milvus#17220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:1.1.1
- Deployment mode(standalone or cluster): standalone 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS):  Ubuntu 
- CPU/Memory: cpu
- GPU: no
- Others: 
use MilvusDM 1.0
```

### Current Behavior

use MilvusDM 1.0

when Milvus data to Milvus data, we find a problem. Please help me, Thank you very much

![image](https://user-images.githubusercontent.com/23188838/170233256-41f76382-7d7c-4a0c-ac21-49c9ae13ab98.png)

### Expected Behavior

ad

**Comment by yanliang567** [comment]
@yhmo I think this is a limitation of insert. Could you please help to double confirm?

/assign @yhmo 
/unassign

**Comment by yhmo** [comment]
@Igoslow
The v1.x has a limitation that data size of each insert request must be less than 256MB. 
You need to split the data to be multiple parts and call insert() by several times.
