### ISSUE TITLE
[Bug]: grpc: addrConn.createTransport failed to connect 

### ISSUE THREAD

**Issue by WangErXiao** [milvus-io/milvus#17235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.2
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

i found error info from rootCoord.
as below:

`[2022/05/26 08:55:34.291 +00:00] [WARN] [grpclog.go:46] ["[core]grpc: addrConn.createTransport failed to connect to {xxx:31000 xxx:31000 <nil> 0 <nil>}. Err: connection error: desc = \"transport: Error while dialing dial tcp xxx:31000: i/o timeout\". Reconnecting..."]
[2022/05/26 08:55:34.291 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel Connectivity change to TRANSIENT_FAILURE"]
[2022/05/26 08:55:34.291 +00:00] [INFO] [grpclog.go:37] ["[core]pickfirstBalancer: UpdateSubConnState: 0xc0016bfa20, {TRANSIENT_FAILURE connection error: desc = \"transport: Error while dialing dial tcp xxx:31000: i/o timeout\"}"]`

xxx is ip address, but my cluster no this ip.

**Comment by yanliang567** [comment]
seems that rootcoord was not able to connect to indexcoord at that time. if it always fails it would cause Milvus service down, but if it succeessfully connected at the end, it does not matter. @WangErXiao does your milvus running healthy now?

/assign @WangErXiao 
unassign
