### ISSUE TITLE
[Enhancement]: Upgrade Docker images to newer Ubuntu LTS, and improve ARM images

### ISSUE THREAD

**Issue by soulteary** [milvus-io/milvus#17243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Hello maintainers 👋

I see that the version of the docker environment used by the current project is relatively old and stays at 18.04.

Maybe we can try to upgrade to 20.04 or 22.04.

Alternatively, the actual cost of maintaining support for both versions is not very high.

And, maybe we can try to provide an ARM image, which can greatly facilitate users to get started quickly. As we all know, there are more and more ARM desktop devices and servers.

### Why is this needed?

Using an older version may not be a wise choice.

![image](https://user-images.githubusercontent.com/1500781/170519222-87988e74-fc27-41af-90e8-62bc7e327ea6.png)

ref: https://ubuntu.com/blog/what-is-an-ubuntu-lts-release

### Anything else?

If no one in the community is willing to do it, I would like to donate some time to help Milvus become better.

I have a certain degree of familiarity with docker/golang and ubuntu, and have done some related things. The previous experience can be seen in my GitHub account.

Looking forward to hearing suggestions from the community and maintainers, I hope the project will get better and better. 🍻

**Comment by xiaofan-luan** [comment]
@LoveEachDay  do we ever tried to run mivlus on 20.0.4 or higher?

**Comment by LoveEachDay** [comment]
> @LoveEachDay do we ever tried to run mivlus on 20.0.4 or higher?

@xiaofan-luan We have tested milvus binary on Ubuntu 20.04 which runs smoothly. It would take small effort for us to upgrade the base image from 18.04 to 20.04.

**Comment by soulteary** [comment]
Thanks for the reply @LoveEachDay @xiaofan-luan  , since the program can run smoothly on the new version, then I can test and prepare with confidence.

Hopefully this week or next week, I can complete this issue. And everyone can run milvus with a more secure and modern base image.
