### ISSUE TITLE
[Enhancement]: Refine Segment allocation policy

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#17254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

1. we can not estimate size in datacoord any more, since we added var char and other possible other variable length datafield. 
    1) we just allocate for each write(In batch) and report the current write size to datacoord. (Thought that would be good enough for now, and much easier, later on if we introduce log node, this could be allocated by log node)
    2) we estimate a number, reclaim a small batch(for example 2000), and once 2000 is used and timeout, we report back our current stage(how many id is used, how much data is written) and return the rest to the datacoord.

Both should work, need a further discussion on that. @sunby @xige-16 @czs007 any ideas?

**Comment by xige-16** [comment]
releated with #16972

**Comment by xige-16** [comment]
woking it
