### ISSUE TITLE
[Bug]: Frequent writing to etcd causes etcd storage overflow

### ISSUE THREAD

**Issue by lvmnn** [milvus-io/milvus#17256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.2
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): golang sdk
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 56c/256g
- GPU: 
- Others:  20qps read/write
```

### Current Behavior

The database has about 500w data。
20qps read/write, write etcd 2g data within 3 hours, resulting in etcd storage overflow.
From the etcd monitoring  view, the write speed is about 100kb/s

**Comment by lvmnn** [comment]
[datacoord.log](https://github.com/milvus-io/milvus/files/8790452/datacoord.log)
[rootcoord.log](https://github.com/milvus-io/milvus/files/8790458/rootcoord.log)

**Comment by xiaofan-luan** [comment]
@lvmnn thanks for the issue, when saying overflow do you mean that etcd disk full?
We thought etcd should be fully relies on disk and won't OOM?
Could you please check which etcd path takes the most part of disk/mem? maybe we can work on it

**Comment by xiaofan-luan** [comment]
@wayblink @aakejiang pleas follow this issue since that might be related to data clean and meta storage

**Comment by xiaofan-luan** [comment]
by the way, thought there could be some configs about how many versions will be maintained in etcd and that might be able to help on reduce etcd disk size

**Comment by lvmnn** [comment]
> @lvmnn thanks for the issue, when saying overflow do you mean that etcd disk full? We thought etcd should be fully relies on disk and won't OOM? Could you please check which etcd path takes the most part of disk/mem? maybe we can work on it

the disk is full，trying to find the etcd path

**Comment by lvmnn** [comment]
@xiaofan-luan 
Our etcd mvcc version has maintained 10000, what is the recommended value?

**Comment by xiaofan-luan** [comment]
10w might be too large, 1000 should works for me.

**Comment by xiaofan-luan** [comment]
But knowing which path takes most of the storage is also important

**Comment by lvmnn** [comment]
> 10w might be too large, 1000 should works for me.
Adjust this parameter to 1000, etcd storage is relatively stable, the following is the comparison of monitoring

before
![image](https://user-images.githubusercontent.com/92595690/170914771-dcd05bc0-1280-48a6-ac69-73a5917911ed.png)


now
![image](https://user-images.githubusercontent.com/92595690/170914815-d189af98-0938-48c0-9b46-75cf67609643.png)

**Comment by aakejiang** [comment]
As per comment in [etcd](https://github.com/etcd-io/etcd/issues/11352):
```
As an experiment, you can turn on "--debug" flag which will print out per request debugging information. I think the user value is redacted but user key is printed in the debugging info.

This is not traversing the key space in data store. But it can tell which key is being added or updated.
```
This would help us know which keys are frequently added and updated.

The following 2 metrics could be helpful:
etcd_mvcc_db_total_size_in_bytes, this should match your db file size
etcd_mvcc_db_total_size_in_use_in_bytes, this is what is actually needed. If you do defrag, the resulting db file size should be close to this number. Post these two metrics so we can know the size of historical data.

**Comment by xiaofan-luan** [comment]
> As per comment in [etcd](https://github.com/etcd-io/etcd/issues/11352):
> 
> ```
> As an experiment, you can turn on "--debug" flag which will print out per request debugging information. I think the user value is redacted but user key is printed in the debugging info.
> 
> This is not traversing the key space in data store. But it can tell which key is being added or updated.
> ```
> 
> This would help us know which keys are frequently added and updated.
> 
> The following 2 metrics could also be helpful:
> 
> ```
> etcd_mvcc_db_total_size_in_bytes, this should match your db file size
> etcd_mvcc_db_total_size_in_use_in_bytes, this is what is actually needed. If you do defrag, the resulting db file size should be close to this number. 
> ```
> 
> Post these two metrics so we can know the size of historical data.

@LoveEachDay pls also help to check if set set defualt mvcc version  to 100 for all deployments(HELM, Operator, Docker compose...)

**Comment by LoveEachDay** [comment]
@xiaofan-luan By default we've enabled compaction by revision (every 1000), and we set the backend db size to 4GB. This setting survives our 1b vector test.
