### ISSUE TITLE
Unitest cost too much time

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#1726]
**Describe the bug**
http://internal.zilliz.com:18080/jenkins/blue/organizations/jenkins/milvus-ci/detail/PR-1718/6/pipeline/574

that cost more than 2h

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by JinHai-CN** [comment]
Unit test timeout of EngineTest.ENGINE_IMPL_THROW_EXCEPTION_TEST
