### ISSUE TITLE
[Bug]: [kafka] [Nightly] Panic occurs during kafka nightly tests reporting "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#17267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.1.0.dev66
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Panic occurs:

mdk-559-n-milvus-datanode-74d7c6c4bd-sh5ff_milvus-ci_datanode-67f3386e94cd2e35749d7871cb5354ae2b16e14be8db5426674d9873d143fea8.log:panic: DDNode forward delete msg failed, vChannel = by-dev-rootcoord-dml_11_433544038401179649v0, err = All attempts results:
mdk-559-n-milvus-proxy-7d7bbf4dc8-2gsb5_milvus-ci_proxy-66cafb6b5941323a073752fc9f544fee9128020ff84f2e758890f7419adb0603.log:panic: runtime error: invalid memory address or nil pointer dereference
mdk-559-n-milvus-querycoord-945cfb849-k75s2_milvus-ci_querycoord-89d591d03895eef21d2fd2630d789d5bd5374101551c9e6916b118409e203b04.log:panic: err: find no available rootcoord, check rootcoord state
mdk-559-n-milvus-querycoord-945cfb849-k75s2_milvus-ci_querycoord-9292aef71909d000ec2b2620310904b875908f725fa4f77b497315f63ec8692e.log:panic: All attempts results:
mdk-559-n-milvus-querynode-74d86df77-8s2p9_milvus-ci_querynode-bb16f02c9c5a0937ee899e4360fc725383e6d5248a0f4cf2dc26287f9b7c6aa8.log:panic: context canceled
mdk-559-n-milvus-querynode-74d86df77-cgfwq_milvus-ci_querynode-143983a2347272bb73e790944812882d968aeacbeb24126ffbbcad1733a49c14.log:panic: context canceled
mdk-559-n-milvus-querynode-74d86df77-tdp5l_milvus-ci_querynode-ed27ce93155e1f43827964a13cb214d7d4d62d67bd7fbee331d56deabac89820.log:panic: context canceled

### Expected Behavior

No panic

### Steps To Reproduce

```markdown
Nightly:
https://ci.milvus.io:18080/jenkins/blue/rest/organizations/jenkins/pipelines/milvus-nightly-ci/branches/master/runs/559/nodes/64/steps/178/log/?start=0
```

### Milvus Log

Milvus logs:

[artifacts-milvus-distributed-kafka-master-559-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/559/artifact/artifacts-milvus-distributed-kafka-master-559-pymilvus-e2e-logs.tar.gz)

Panic log files:
1. mdk-559-n-milvus-datanode-74d7c6c4bd-sh5ff_milvus-ci_datanode-67f3386e94cd2e35749d7871cb5354ae2b16e14be8db5426674d9873d143fea8.log
2. mdk-559-n-milvus-proxy-7d7bbf4dc8-2gsb5_milvus-ci_proxy-66cafb6b5941323a073752fc9f544fee9128020ff84f2e758890f7419adb0603.log
3. mdk-559-n-milvus-querycoord-945cfb849-k75s2_milvus-ci_querycoord-89d591d03895eef21d2fd2630d789d5bd5374101551c9e6916b118409e203b04.log
4. mdk-559-n-milvus-querycoord-945cfb849-k75s2_milvus-ci_querycoord-9292aef71909d000ec2b2620310904b875908f725fa4f77b497315f63ec8692e.log
5. mdk-559-n-milvus-querynode-74d86df77-8s2p9_milvus-ci_querynode-bb16f02c9c5a0937ee899e4360fc725383e6d5248a0f4cf2dc26287f9b7c6aa8.log
6. mdk-559-n-milvus-querynode-74d86df77-cgfwq_milvus-ci_querynode-143983a2347272bb73e790944812882d968aeacbeb24126ffbbcad1733a49c14.log
7. mdk-559-n-milvus-querynode-74d86df77-tdp5l_milvus-ci_querynode-ed27ce93155e1f43827964a13cb214d7d4d62d67bd7fbee331d56deabac89820.log

**Comment by binbinlv** [comment]
@jaime0815 

Could you please have a look first? 

Several panics occur, and my title just mentions one of them, so needs to investigate them all, thanks.

**Comment by yanliang567** [comment]
set it to higher priority

**Comment by xiaofan-luan** [comment]
67f3386e94cd2e35749d7871cb5354ae2b16e14be8db5426674d9873d143fea8.log:panic: DDNode forward delete msg failed, vChannel = by-dev-rootcoord-dml_11_433544038401179649v0, err = All attempts results:
mdk-559-n-milvus-proxy-7d7bbf4dc8-2gsb5_milvus-ci_proxy-66cafb6b5941323a073752fc9f544fee9128020ff84f2e758890f7419adb0603.log:panic: runtime error: invalid memory address or nil pointer dereference

**Comment by xiaofan-luan** [comment]
that's the main cause, @longjiquan pls take a look

**Comment by xiaofan-luan** [comment]
this might be related to the delete issues also, previously we probably just lose the delete

**Comment by xiaofan-luan** [comment]
probably we will need to add retry here

**Comment by xiaofan-luan** [comment]
#17178

**Comment by jaime0815** [comment]
panic: DDNode forward delete msg failed, vChannel = by-dev-rootcoord-dml_11_433544038401179649v0, err = All attempts results:

attempt #1:delivery chan of kafka producer is closed

attempt #2:delivery chan of kafka producer is closed

attempt #3:delivery chan of kafka producer is closed

attempt #4:delivery chan of kafka producer is closed

attempt #5:delivery chan of kafka producer is closed





goroutine 466044 [running]:

github.com/milvus-io/milvus/internal/datanode.(*ddNode).Operate(0xc001103ce0, 0xc0060d4450, 0x1, 0x1, 0x425e540, 0xc003303a
70, 0x0)

        /go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_dd_node.go:180 +0x2467

github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc0004d6c40)

        /go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:100 +0x214

created by github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start

**Comment by bigsheeper** [comment]
this issue should be fixed, would you please make a verify, thanks @binbinlv
