### ISSUE TITLE
Do we need a new parameter name for preload_table in milvus_config.yaml?

### ISSUE THREAD

**Issue by yamasite** [milvus-io/milvus#1731]
**Describe the bug**

The name `preload_table` is confusing.

**Steps/Code to reproduce behavior**

https://github.com/milvus-io/milvus/blob/master/core/conf/demo/server_config.yaml

```
# preload_table        | A comma-separated list of table names that need to be pre-loaded when Milvus server starts up.  '*' means preload all existing tables (single-quote or double-quote required).                                  
```
**Expected behavior**
Should we use `collection` instead of `table`?

**Comment by JinHai-CN** [comment]
Yes, we do.

**Comment by yhmo** [comment]
duplicated with #1766
