### ISSUE TITLE
[Bug]: Indexcoord's unreasonable log output frequency when some issues happen

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#17314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220530-c88514bc
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The logs are refreshing too fast in indexcoord, close to 100,000 lines of repeated logs every second
```
cat cluster-upgrade-654-milvus-indexcoord-64c5489dbf-g4mtm.log|grep '2022/05/31 06:59:06'|wc -l
>>> 98860

```
repeated logs
```
[2022/05/31 06:46:18.297 +00:00] [DEBUG] [index_coord.go:820] ["IndexCoord watchMetaLoop find meta updated."]
[2022/05/31 06:46:18.297 +00:00] [DEBUG] [index_coord.go:820] ["IndexCoord watchMetaLoop find meta updated."]
[2022/05/31 06:46:18.297 +00:00] [DEBUG] [index_coord.go:820] ["IndexCoord watchMetaLoop find meta updated."]
```

### Expected Behavior

Output logs at a reasonable frequency

### Milvus Log

[cluster-upgrade-654.zip](https://github.com/milvus-io/milvus/files/8802830/cluster-upgrade-654.zip)

### Anything else?

This issue was found in https://github.com/milvus-io/milvus/issues/17291.
When #17291 happened, indexcoord would output close to 100,000 lines of repeated logs every second.

**Comment by yanliang567** [comment]
@xiaofan-luan sounds like a log refinement issue.

/assign @xiaofan-luan 
/unassign

**Comment by xiaofan-luan** [comment]
/assign @xiaocai2333 
pls check if it is still a issue
