### ISSUE TITLE
[Bug]: List collections call hang after imported a new collection

### ISSUE THREAD

**Issue by lilida** [milvus-io/milvus#17344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.2
- Deployment mode(standalone or cluster): Cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

After import embedding to a newly created collection, cannot list or describe collections because the call just hang. It looks like waiting for the datacoord node.

milvus_cli > list collections
RPC error: [list_collections], <BaseException: (code=1, message=syncTimestamp Failed:context deadline exceeded)>, <Time:{'RPC start': '2022-06-01 21:48:59.546617', 'RPC error': '2022-06-01 21:49:04.566725'}>
Connect to Milvus error!<BaseException: (code=1, message=syncTimestamp Failed:context deadline exceeded)>
milvus_cli > list collections
RPC error: get_flush_state{'RPC start': '2022-06-01 21:52:22.112394', 'RPC error': '2022-06-01 21:52:27.140803'}
RPC error: _wait_for_flushed{'RPC start': '2022-06-01 21:49:55.589235', 'RPC error': '2022-06-01 21:52:27.140954'}
RPC error: flush{'RPC start': '2022-06-01 21:49:55.586976', 'RPC error': '2022-06-01 21:52:27.140993'}
<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "err: context deadline exceeded
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:253 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall
/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:464 github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).GetFlushState
/go/src/github.com/milvus-io/milvus/internal/proxy/impl.go:3901 github.com/milvus-io/milvus/internal/proxy.(*Proxy).GetFlushState
/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:623 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).GetFlushState
/go/src/github.com/milvus-io/milvus/internal/proto/milvuspb/milvus.pb.go:6382 github.com/milvus-io/milvus/internal/proto/milvuspb._MilvusService_GetFlushState_Handler.func1
/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38 github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1
/go/src/github.com/milvus-io/milvus/internal/proto/milvuspb/milvus.pb.go:6384 github.com/milvus-io/milvus/internal/proto/milvuspb._MilvusService_GetFlushState_Handler
/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286 google.golang.org/grpc.(*Server).processUnaryRPC
/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609 google.golang.org/grpc.(*Server).handleStream

I restarted the datacoord and datanode after the issue happened. datanode then keep failing to start. It always reported  the state is in initializing and the liveness probe killed the pod later

### Expected Behavior

It should work or report the right error message

### Milvus Log

[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/8820723/milvus-log.tar.gz)

**Comment by yanliang567** [comment]
@lilida it seems that the tt between components are too slow, which make them disconnected from each other. 
[2022/06/02 04:19:09.007 +00:00] [WARN] [timeticksync.go:339] ["rootcoord send tt to all channels too slowly"] [chanNum=4] [span=206]
did you run the etcd service on SSD volume?

/assign @lilida

**Comment by lilida** [comment]
No. It is not running on SSD but regular GP3 EBS. However, this cluster has no load and only one small (3000 items) collection before I imported another 60K. Do we still need SSD here? @yanliang567

**Comment by yanliang567** [comment]
@lilida etcd is play a role as registering and service detecting in Milvus cluster, so it requires high performance in volume, and we suggest you use SSD here.

**Comment by lilida** [comment]
Some update. the issue seems to be related to the storage of S3. Unlike default config uses minio, I am using S3 as backend.  The minio initialization seems never succeeded. After I switched back to minio, it seems that the issue is gone

**Comment by yanliang567** [comment]
@lilida so could you please share how you configure Milvus with S3?
