### ISSUE TITLE
[Bug]: Search failed with error message `cannot find sealed segment 433627047283654657 in QueryNode` after Milvus recovered from  standalone pod kill

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#17347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220602-7a59a805
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-2.1.0.dev66
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search failed when running `hello_milvus.py`

```
15:53:06  Search...
15:53:06  Traceback (most recent call last):
15:53:06    File "scripts/hello_milvus.py", line 116, in <module>
15:53:06      hello_milvus(args.host)
15:53:06    File "scripts/hello_milvus.py", line 91, in hello_milvus
15:53:06      "int64 > 100", output_fields=["int64", "float"], timeout=TIMEOUT
15:53:06    File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 690, in search
15:53:06      partition_names, output_fields, round_decimal, timeout=timeout, **kwargs)
15:53:06    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 61, in handler
15:53:06      raise e
15:53:06    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 44, in handler
15:53:06      return func(self, *args, **kwargs)
15:53:06    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 79, in handler
15:53:06      raise e
15:53:06    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 75, in handler
15:53:06      return func(*args, **kwargs)
15:53:06    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 449, in search
15:53:06      return self._execute_search_requests(requests, timeout, **_kwargs)
15:53:06    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 79, in handler
15:53:06      raise e
15:53:06    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 75, in handler
15:53:06      return func(*args, **kwargs)
15:53:06    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 411, in _execute_search_requests
15:53:06      raise pre_err
15:53:06    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 402, in _execute_search_requests
15:53:06      raise MilvusException(response.status.error_code, response.status.reason)
15:53:06  pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=137, reason=Search 137 failed, reason cannot find sealed segment 433627047283654657 in QueryNode err %!w(<nil>))>
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
see http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/5908/pipeline
```

### Milvus Log

[artifacts-standalone-pod-kill-5908-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/8822137/artifacts-standalone-pod-kill-5908-server-logs.1.tar.gz)

**Comment by zhuwenxing** [comment]
/assign @congqixia 
Please take a look

**Comment by zhuwenxing** [comment]
This happened again, so set it as a critical issue.

failed job: http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/6481/pipeline
log: [artifacts-standalone-pod-kill-6481-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/8896297/artifacts-standalone-pod-kill-6481-server-logs.tar.gz)

**Comment by letian-jiang** [comment]
The log of the killed container is not available. Is it recoverable?  @zhuwenxing 
```
Error from server (BadRequest): previous terminated container "standalone" in pod "standalone-pod-kill-6481-milvus-standalone-84fc65cbc9-mq2cl" not found
```

**Comment by zhuwenxing** [comment]
If the log you check is in https://github.com/milvus-io/milvus/issues/17347#issuecomment-1154687216
then we can think the standalone is recovered.
![image](https://user-images.githubusercontent.com/12268675/173725003-24c2808b-0875-47ce-b9fd-d96d7e1c7ed5.png)
from the image above, we can see before running `verify all collections.py`, `test_e2e.py`and `hello_milvus.py` were passed, so it means Milvus can offer services.

Also, if `standalone` was not recovered, the error should be `connection error` at the very beginning

**Comment by zhuwenxing** [comment]
all containers log for standalone-pod-kill-6481 release
[standalone-pod-kill-6481.zip](https://github.com/milvus-io/milvus/files/8905348/chaos.1.zip)

**Comment by letian-jiang** [comment]
QueryNode released the missing segment when handling SealedSegmentsChangeInfo
```
[2022/06/14 03:54:42.304 +00:00] [INFO] [query_node.go:354] ["get SealedSegmentsChangeInfo from etcd"] [infoID=0]
[2022/06/14 03:54:42.304 +00:00] [INFO] [shard_cluster.go:333] ["ShardCluster remove segment"] [nodeID=97] [segmentID=433895145349578753] [state=0]
[2022/06/14 03:54:42.304 +00:00] [WARN] [shard_cluster.go:345] ["ShardCluster removeSegment found node not match"] [segmentID=433895145349578753] [nodeID=135] [evtNodeID=97]
[2022/06/14 03:54:42.304 +00:00] [WARN] [shard_cluster.go:601] ["node not in cluster"] [nodeID=97] [collectionID=433895145244983297] [vchannel=by-dev-rootcoord-dml_13_433895145244983297v1]
[2022/06/14 03:54:42.304 +00:00] [WARN] [shard_cluster_service.go:158] ["failed to handoff"] [channel=by-dev-rootcoord-dml_13_433895145244983297v1] [segment="online_nodeID:135 online_segments:<segmentID:433895145349578753 collectionID:433895145244983297 partitionID:433895145244983298 nodeID:135 num_rows:1497 dmChannel:\"by-dev-rootcoord-dml_13_433895145244983297v1\" segment_state:Sealed replica_ids:433895114375168021 node_ids:97 node_ids:135 node_ids:135 > offline_nodeID:97 offline_segments:<segmentID:433895145349578753 collectionID:433895145244983297 partitionID:433895145244983298 nodeID:97 num_rows:1497 dmChannel:\"by-dev-rootcoord-dml_13_433895145244983297v1\" segment_state:Sealed replica_ids:433895114375168021 node_ids:97 node_ids:135 > "] [error="All attempts results:\nattempt #1:node not in cluster nodeID 97\n"]
[2022/06/14 03:54:42.304 +00:00] [INFO] [shard_cluster.go:333] ["ShardCluster remove segment"] [nodeID=135] [segmentID=433895145349578754] [state=0]
[2022/06/14 03:54:42.304 +00:00] [INFO] [partition.go:104] ["remove a segment from replica"] [collectionID=433895145244983297] [partitionID=433895145244983298] [segmentID=433895145349578754]
[2022/06/14 03:54:42.304 +00:00] [INFO] [segment.go:224] ["delete segment from memory"] [collectionID=433895145244983297] [partitionID=433895145244983298] [segmentID=433895145349578754]
[2022/06/14 03:54:42.304 +00:00] [INFO] [impl.go:360] ["release segments done"] [collectionID=433895145244983297] [segmentIDs="[433895145349578754]"]
[2022/06/14 03:54:42.304 +00:00] [INFO] [shard_cluster_service.go:156] ["successfully handoff "] [channel=by-dev-rootcoord-dml_12_433895145244983297v0] [segment="online_nodeID:135 online_segments:<segmentID:433895145349578754 collectionID:433895145244983297 partitionID:433895145244983298 nodeID:135 num_rows:1503 dmChannel:\"by-dev-rootcoord-dml_12_433895145244983297v0\" segment_state:Sealed replica_ids:433895114375168021 node_ids:97 node_ids:135 node_ids:135 > offline_nodeID:135 offline_segments:<segmentID:433895145349578754 collectionID:433895145244983297 partitionID:433895145244983298 nodeID:135 num_rows:1503 dmChannel:\"by-dev-rootcoord-dml_12_433895145244983297v0\" segment_state:Sealed replica_ids:433895114375168021 node_ids:97 node_ids:135 > "]
```

**Comment by letian-jiang** [comment]
The issue should be fixed by #17593, please verify it.
/assign @zhuwenxing

**Comment by letian-jiang** [comment]
> QueryNode released the missing segment when handling SealedSegmentsChangeInfo
> 
> ```
> [2022/06/14 03:54:42.304 +00:00] [INFO] [query_node.go:354] ["get SealedSegmentsChangeInfo from etcd"] [infoID=0]
> [2022/06/14 03:54:42.304 +00:00] [INFO] [shard_cluster.go:333] ["ShardCluster remove segment"] [nodeID=97] [segmentID=433895145349578753] [state=0]
> [2022/06/14 03:54:42.304 +00:00] [WARN] [shard_cluster.go:345] ["ShardCluster removeSegment found node not match"] [segmentID=433895145349578753] [nodeID=135] [evtNodeID=97]
> [2022/06/14 03:54:42.304 +00:00] [WARN] [shard_cluster.go:601] ["node not in cluster"] [nodeID=97] [collectionID=433895145244983297] [vchannel=by-dev-rootcoord-dml_13_433895145244983297v1]
> [2022/06/14 03:54:42.304 +00:00] [WARN] [shard_cluster_service.go:158] ["failed to handoff"] [channel=by-dev-rootcoord-dml_13_433895145244983297v1] [segment="online_nodeID:135 online_segments:<segmentID:433895145349578753 collectionID:433895145244983297 partitionID:433895145244983298 nodeID:135 num_rows:1497 dmChannel:\"by-dev-rootcoord-dml_13_433895145244983297v1\" segment_state:Sealed replica_ids:433895114375168021 node_ids:97 node_ids:135 node_ids:135 > offline_nodeID:97 offline_segments:<segmentID:433895145349578753 collectionID:433895145244983297 partitionID:433895145244983298 nodeID:97 num_rows:1497 dmChannel:\"by-dev-rootcoord-dml_13_433895145244983297v1\" segment_state:Sealed replica_ids:433895114375168021 node_ids:97 node_ids:135 > "] [error="All attempts results:\nattempt #1:node not in cluster nodeID 97\n"]
> [2022/06/14 03:54:42.304 +00:00] [INFO] [shard_cluster.go:333] ["ShardCluster remove segment"] [nodeID=135] [segmentID=433895145349578754] [state=0]
> [2022/06/14 03:54:42.304 +00:00] [INFO] [partition.go:104] ["remove a segment from replica"] [collectionID=433895145244983297] [partitionID=433895145244983298] [segmentID=433895145349578754]
> [2022/06/14 03:54:42.304 +00:00] [INFO] [segment.go:224] ["delete segment from memory"] [collectionID=433895145244983297] [partitionID=433895145244983298] [segmentID=433895145349578754]
> [2022/06/14 03:54:42.304 +00:00] [INFO] [impl.go:360] ["release segments done"] [collectionID=433895145244983297] [segmentIDs="[433895145349578754]"]
> [2022/06/14 03:54:42.304 +00:00] [INFO] [shard_cluster_service.go:156] ["successfully handoff "] [channel=by-dev-rootcoord-dml_12_433895145244983297v0] [segment="online_nodeID:135 online_segments:<segmentID:433895145349578754 collectionID:433895145244983297 partitionID:433895145244983298 nodeID:135 num_rows:1503 dmChannel:\"by-dev-rootcoord-dml_12_433895145244983297v0\" segment_state:Sealed replica_ids:433895114375168021 node_ids:97 node_ids:135 node_ids:135 > offline_nodeID:135 offline_segments:<segmentID:433895145349578754 collectionID:433895145244983297 partitionID:433895145244983298 nodeID:135 num_rows:1503 dmChannel:\"by-dev-rootcoord-dml_12_433895145244983297v0\" segment_state:Sealed replica_ids:433895114375168021 node_ids:97 node_ids:135 > "]
> ```
> 
> The online segment and offline segment are same, which is not what we expected and leads to the segment removed from meta.

The reason for such a duplicate segment is unclear now. 
Gonna investigate it further,

**Comment by zhuwenxing** [comment]
@letian-jiang 
In version `master-20220616-53a49a92`, the error changed to load failure.
```
20:47:32  check collection Checker__wAS9PJDA
20:47:32  collection is exist
20:47:32  
20:47:32  Create collection...
20:47:32  
20:47:32  Insert 3000 vectors cost 0.0707 seconds
20:47:32  
20:47:32  Get collection entities...
20:47:32  6130
20:47:32  
20:47:32  Get collection entities cost 3.0165 seconds
20:47:32  
20:47:32  Create index...
20:47:32  
20:47:32  Create index cost 1.0320 seconds
20:47:32  
20:47:32  load collection...
20:47:32  Traceback (most recent call last):
20:47:32    File "scripts/verify_all_collections.py", line 124, in <module>
20:47:32      hello_milvus(collection_name)
20:47:32    File "scripts/verify_all_collections.py", line 74, in hello_milvus
20:47:32      collection.load()
20:47:32    File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 450, in load
20:47:32      conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
20:47:32    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 61, in handler
20:47:32      raise e
20:47:32    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 44, in handler
20:47:32      return func(self, *args, **kwargs)
20:47:32    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 79, in handler
20:47:32      raise e
20:47:32    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 75, in handler
20:47:32      return func(*args, **kwargs)
20:47:32    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 683, in load_collection
20:47:32      raise MilvusException(response.error_code, response.reason)
20:47:32  pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=, failed to get segment 433948783414607873)>
```

failed job: http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/6555/pipeline
log:  [artifacts-standalone-pod-kill-6555-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/8919135/artifacts-standalone-pod-kill-6555-server-logs.tar.gz)

I can open a new issue to trace this.

**Comment by zhuwenxing** [comment]
The issue https://github.com/milvus-io/milvus/issues/17607 blocked the verification

**Comment by zhuwenxing** [comment]
Not reproduced yet, remove the critical label.
