### ISSUE TITLE
[Enhancement]: Reduce the number of lock operations in getStream

### ISSUE THREAD

**Issue by czs007** [milvus-io/milvus#17346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

![image](https://user-images.githubusercontent.com/59249785/171578682-22e0095f-6047-492b-88b4-3c4cf1427331.png)

It is recommended to change the interface of createMsgStream to return (msgstream, error), which can reduce the last lock operation  `lockGetStream` in `getStream`.

**Comment by longjiquan** [comment]
fixed by #17468
