### ISSUE TITLE
[Bug]: hangs at collection.num_entities

### ISSUE THREAD

**Issue by jmugan** [milvus-io/milvus#17358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I call `collection.num_entities` it hangs. Maybe the database got shutdown in a bad state? Restarting doesn't help.

### Expected Behavior

It returns the number of entities.

### Milvus Log

I didn't see anything in the logs.

**Comment by yanliang567** [comment]
@jmugan thank you for the issue. I sounds like a known issue for us. To confirm that, could you please use this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export Milvus logs? 

/assign @jmugan 
/unassign

**Comment by jmugan** [comment]
Hi @yanliang567 I've exported the logs. They are 100 MB. Do you want the whole thing?

The last few records look like this
```
milvus-standalone | [2022/06/03 01:12:40.433 +00:00] [INFO] [impl.go:3906] ["received get flush state response"] [response="status:<> "]
milvus-standalone | [2022/06/03 01:12:40.433 +00:00] [INFO] [services.go:928] ["received get flush state request"] [segmentIDs="[433589616282959873,433589616309174273]"] [len=2]
milvus-standalone | [2022/06/03 01:12:40.433 +00:00] [INFO] [services.go:951] ["[flush state] unflushed segment ids"] [segmentIDs="[433589616282959873,433589616309174273]"] [len=2]
milvus-standalone | [2022/06/03 01:12:40.433 +00:00] [INFO] [services.go:928] ["received get flush state request"] [segmentIDs="[433589616282959873,433589616309174273]"] [len=2]
milvus-standalone | [2022/06/03 01:12:40.433 +00:00] [INFO] [services.go:928] ["received get flush state request"] [segmentIDs="[433589616282959873,433589616309174273]"] [len=2]
milvus-standalone | [2022/06/03 01:12:40.433 +00:00] [INFO] [services.go:951] ["[flush state] unflushed segment ids"] [segmentIDs="[433589616282959873,433589616309174273]"] [len=2]
milvus-standalone | [2022/06/03 01:12:40.433 +00:00] [INFO] [services.go:951] ["[flush state] unflushed segment ids"] [segmentIDs="[433589616282959873,433589616309174273]"] [len=2]
milvus-standalone | [2022/06/03 01:12:40.433 +00:00] [INFO] [impl.go:3906] ["received get flush state response"] [response="status:<> "]
milvus-standalone | [2022/06/03 01:12:40.433 +00:00] [INFO] [impl.go:3906] ["received get flush state response"] [response="status:<> "]
milvus-standalone | [2022/06/03 01:12:40.433 +00:00] [INFO] [impl.go:3906] ["received get flush state response"] [response="status:<> "]
```

**Comment by jmugan** [comment]
Are there any workarounds for this? Can I reset something?

**Comment by yanliang567** [comment]
> Hi @yanliang567 I've exported the logs. They are 100 MB. Do you want the whole thing?
> 
> The last few records look like this
> 
> ```
> milvus-standalone | [2022/06/03 01:12:40.433 +00:00] [INFO] [impl.go:3906] ["received get flush state response"] [response="status:<> "]
> milvus-standalone | [2022/06/03 01:12:40.433 +00:00] [INFO] [services.go:928] ["received get flush state request"] [segmentIDs="[433589616282959873,433589616309174273]"] [len=2]
> milvus-standalone | [2022/06/03 01:12:40.433 +00:00] [INFO] [services.go:951] ["[flush state] unflushed segment ids"] [segmentIDs="[433589616282959873,433589616309174273]"] [len=2]
> milvus-standalone | [2022/06/03 01:12:40.433 +00:00] [INFO] [services.go:928] ["received get flush state request"] [segmentIDs="[433589616282959873,433589616309174273]"] [len=2]
> milvus-standalone | [2022/06/03 01:12:40.433 +00:00] [INFO] [services.go:928] ["received get flush state request"] [segmentIDs="[433589616282959873,433589616309174273]"] [len=2]
> milvus-standalone | [2022/06/03 01:12:40.433 +00:00] [INFO] [services.go:951] ["[flush state] unflushed segment ids"] [segmentIDs="[433589616282959873,433589616309174273]"] [len=2]
> milvus-standalone | [2022/06/03 01:12:40.433 +00:00] [INFO] [services.go:951] ["[flush state] unflushed segment ids"] [segmentIDs="[433589616282959873,433589616309174273]"] [len=2]
> milvus-standalone | [2022/06/03 01:12:40.433 +00:00] [INFO] [impl.go:3906] ["received get flush state response"] [response="status:<> "]
> milvus-standalone | [2022/06/03 01:12:40.433 +00:00] [INFO] [impl.go:3906] ["received get flush state response"] [response="status:<> "]
> milvus-standalone | [2022/06/03 01:12:40.433 +00:00] [INFO] [impl.go:3906] ["received get flush state response"] [response="status:<> "]
> ```

yes, if possibel, please upload the whole logs with a zip file.

**Comment by jmugan** [comment]
Here is the log. 
[milvus_log.zip](https://github.com/milvus-io/milvus/files/8838612/milvus_log.zip)

**Comment by yanliang567** [comment]
@xiaofan-luan looks like a known issue in milvus 2.0.2, could you please double check that?

/assign @xiaofan-luan 

/unassign

**Comment by soothing-rain** [comment]
@jmugan Hey we have fixed this issue in 2.1 :)

**Comment by jmugan** [comment]
Great news! Thanks!

**Comment by jmugan** [comment]
Just getting back to this. So, 2.1 hasn't been released yet? I don't suppose I can do `image: milvusdb/milvus:v2.1` in the standalone part of the docker compose file. Is there an estimate for when it will be released?

**Comment by yanliang567** [comment]
not yet, the new ETA is next week.
