### ISSUE TITLE
milvus-standalone pod crashed and failed to restart after inserting 100k vectors

### ISSUE THREAD

**Issue by passionzhan** [milvus-io/milvus#17361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.1
- Deployment mode(standalone or cluster):standalone 
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.0.2
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 30G
- GPU: 无
- Others:
```

### Current Behavior

单机版在插入10w+数据后，名为milvus-standalone的docker容器服务突然就挂了，手动重启也起不来。
将原有milvus-standalone镜像删除，然后 用命令 docker-compose up -d 挂载原有数据重启，还是不行。

### Milvus Log

mivlus日志见网盘：

链接：https://pan.baidu.com/s/1jyUE_aoTlFMDUt3DVdIi8Q 
提取码：l377

**Comment by yanliang567** [comment]
@passionzhan could you please retry with Milvus 2.0.2, I think this was fixed already.

/assign @passionzhan 
/unassign
