### ISSUE TITLE
[Bug]: drop collection if pass with alias name then the alias couldn't be delete or alter to other collection

### ISSUE THREAD

**Issue by zhuiqi525** [milvus-io/milvus#17360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.2
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When i try to drop collection and make some mistake pass with alias name. then the alias couldn't be drop or bind to other collections.

it's easy to reproduce this situation

### Expected Behavior

when drop collection with alias name, just do nothing or drop collection

### Steps To Reproduce

```markdown
1. create collection a
2. create alias alias_a bind to a
3. drop collection with collectionName "alias_a"
4. then you will find alias_a could't be use anymore and couldn't be drop or do alter operation
```

**Comment by yanliang567** [comment]
@zhuiqi525 are you using a python sdk or java sdk? and sdk version?

/assign @zhuiqi525

**Comment by zhuiqi525** [comment]
> @zhuiqi525 are you using a python sdk or java sdk? and sdk version?
> 
> /assign @zhuiqi525

python sdk , version 2.0.2

**Comment by EricStarer** [comment]
In the current version，drop collection operation will drop the alias with it simultaneously. In the future version, drop a collection with alias will return an error: "Collection with alias could not be droped. You should remove the alias from this collection first."

**Comment by EricStarer** [comment]
So we recommend you drop or alter the alias first, then drop the collection. @zhuiqi525

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```gfm
> - Milvus version: 2.0.2
> - Deployment mode(standalone or cluster):
> - SDK version(e.g. pymilvus v2.0.2):
> - OS(Ubuntu or CentOS): 
> - CPU/Memory: 
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> When i try to drop collection and make some mistake pass with alias name. then the alias couldn't be drop or bind to other collections.
> 
> it's easy to reproduce this situation
> 
> ### Expected Behavior
> when drop collection with alias name, just do nothing or drop collection
> 
> ### Steps To Reproduce
> ```gfm
> 1. create collection a
> 2. create alias alias_a bind to a
> 3. drop collection with collectionName "alias_a"
> 4. then you will find alias_a could't be use anymore and couldn't be drop or do alter operation
> ```
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

This is actually the expected behavior, you will has to drop all alias of the related collection before drop the collection

**Comment by yanliang567** [comment]
/assign @zhuwenxing 
@zhuwenxing could you please help to check the behavior here?

**Comment by EricStarer** [comment]
I will check the behavior in a new feature #17131

**Comment by zhuwenxing** [comment]
I have tried with `master-20220602-48cf63a2` and ` 2.1.0.dev66`

When running the script below
```python
from pymilvus import connections, Collection, FieldSchema, CollectionSchema, DataType, utility
import random
connections.connect(host="127.0.0.1", port="19530")

drop_flag = True

fields = [
    FieldSchema("film_id", DataType.INT64, is_primary=True),
    FieldSchema("films", dtype=DataType.FLOAT_VECTOR, dim=128)
]
schema_a = CollectionSchema(fields, description="test_a")
schema_b = CollectionSchema(fields, description="test_b")

try:
    collection_a = Collection("collection_a", schema_a)
    collection_b = Collection("collection_b", schema_b)
    vectors_a = [[random.random() for _ in range(128)] for _ in range(1000)]
    vectors_b = [[random.random() for _ in range(128)] for _ in range(3000)]
    data_a = [
        [1 for i in range(1000)],
        vectors_a
    ]
    data_b = [
        [1 for i in range(3000)],
        vectors_b
    ]
    collection_a.insert(data_a)
    collection_b.insert(data_b)
    print(f"collection_a num_entities: {collection_a.num_entities}")
    print(f"collection_b num_entities: {collection_b.num_entities}")
    # create alias tom and assign it to collection_a
    utility.create_alias(collection_a.name, "tom")
    collection_tom_alias = Collection("tom")

    # create alias jack and assign it to collection_b
    utility.create_alias(collection_b.name, "jack")
    collection_jack_alias = Collection("jack")

    try:
        # try to use alias to drop collection_a, but it will fail as expect
        collection_tom_alias.drop()
    except Exception as e:
        print("failed to drop collection with alias")
        print(e)
    try:
        # try to alter alias tom to collection_b
        print(f"before alter, collection_tom_alias num_entities:  {collection_tom_alias.num_entities}")
        print("alter alias tom to collection_b")
        utility.alter_alias("collection_b", "tom")
        print(f"after alter, collection_tom_alias num_entities:  {collection_tom_alias.num_entities}")
        # try to drop alias tom
        utility.drop_alias("tom")
        print("drop alias tom done")
    except Exception as e:
        print(e)

    utility.drop_alias("jack")
    print("drop alias jack done")
except Exception as e:
    print(e)
finally:
    if drop_flag:
        print("drop all collection") 
        collection_a.drop()
        collection_b.drop()

```


the output is 
```
collection_a num_entities: 1000
collection_b num_entities: 3000
failed to drop collection with alias
<MilvusException: (code=1, message=DropCollection failed: cannot drop the collection via alias = tom)>
RPC error: [drop_collection], <MilvusException: (code=1, message=DropCollection failed: cannot drop the collection via alias = tom)>, <Time:{'RPC start': '2022-06-07 14:20:47.939844', 'RPC error': '2022-06-07 14:20:47.956243'}>
before alter, collection_tom_alias num_entities:  1000
alter alias tom to collection_b
after alter, collection_tom_alias num_entities:  3000
drop alias tom done
drop alias jack done
drop all collection
```

So in this config, it is OK to alter alias to another collection and drop alias after you drop collection failed by alias by mistake

**Comment by zhuwenxing** [comment]
@zhuiqi525
You can try the code to check the behavior.
or can you please provide your reproduced code?

**Comment by zhuwenxing** [comment]
Same behavior in version `v2.0.2`
