### ISSUE TITLE
Etcd node suddenly failed to run

### ISSUE THREAD

**Issue by AI-Mart** [milvus-io/milvus#17370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.2
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.0.2
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 8c32G
- GPU: 32G
- Others:
```

### Current Behavior

Etcd node suddenly failed to ru
<img width="786" alt="微信图片_20220606111243" src="https://user-images.githubusercontent.com/63343847/172088528-f5afe86e-aaf8-4279-9c5f-e17c2c8646bb.png">

### Expected Behavior

The etcd node should run successfully

### Milvus Log

[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/8841666/milvus-log.tar.gz)

**Comment by JackLCL** [comment]
@AI-Mart 
Can you upload the etcd log here?

**Comment by AI-Mart** [comment]
上传了日志了的，是的压缩文件



发自我的iPhone


------------------ Original ------------------
From: Chenglong.li ***@***.***&gt;
Date: Mon,Jun 6,2022 11:33 AM
To: milvus-io/milvus ***@***.***&gt;
Cc: AI-Mart ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [milvus-io/milvus] Etcd node suddenly failed to run (Issue #17370)





 
@AI-Mart
 Can you upload the etcd log here?

**Comment by AI-Mart** [comment]
[my-release-etcd-log.zip](https://github.com/milvus-io/milvus/files/8842264/my-release-etcd-log.zip)

**Comment by LoveEachDay** [comment]
@AI-Mart Seems like pod `my-release-etcd-1` restarted. Could you provide the the log using the following command:
```
kubectl log my-release-etcd-1 --previous > my-release-etcd-1.pre.log
```

And upload the above log file.

**Comment by AI-Mart** [comment]
[root@k8s-master01 ~]# kubectl logs my-release-etcd-1 --previous > my-release-etcd-1.pre.log
Error from server (BadRequest): previous terminated container "etcd" in pod "my-release-etcd-1" not found

**Comment by AI-Mart** [comment]
[root@k8s-master01 ~]# kubectl logs my-release-etcd-1 --previous > my-release-etcd-1.pre.log
Error from server (BadRequest): previous terminated container "etcd" in pod "my-release-etcd-1" not found
[root@k8s-master01 ~]#

**Comment by LoveEachDay** [comment]
@AI-Mart According the above output, the `my-release-etcd-1` does not restart. Could you list the pod status for the etcd cluster?

**Comment by AI-Mart** [comment]
Colleague restart the container and delete it. We can only wait for the next replication. First, we export the log and then analyze it
