### ISSUE TITLE
[Bug]: [bulkload]one of data node crashes if bulk load a big file with 1 million entities

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#17394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220602-48cf63a2
- Deployment mode(standalone or cluster): cluster with 2 data nodes
- SDK version(e.g. pymilvus v2.0.0rc2):
```

### Current Behavior

one of data nodes crashes

### Expected Behavior

bulk load data successfully

### Steps To Reproduce

```markdown
1. prepare a numpy file with 1 million data(128d, about 970MB)
2. bulk load the data file
```

### Milvus Log
[datanode.crash.log.tar.gz](https://github.com/milvus-io/milvus/files/8844219/datanode.crash.log.tar.gz)

_No response_

**Comment by yanliang567** [comment]
debug log:
[datanode.crash.debug.log.tar.gz](https://github.com/milvus-io/milvus/files/8844357/datanode.crash.debug.log.tar.gz)

**Comment by xiaofan-luan** [comment]
/milvus/tools/run.sh: line 8:    17 Killed                  $@

according to the last log, seems to be killed, might a memory issue?

**Comment by yanliang567** [comment]
I did set a 4GB memory limitation, but the monitor says it has not meet the limitation yet.
![image](https://user-images.githubusercontent.com/82361606/172281949-7a29e565-c8ae-4f17-9438-99ba809b48a6.png)

**Comment by xiaofan-luan** [comment]
Memory usage seems to be ok,  is this reproducible or happened by chance? might be killed because of lack of physical  memory on the machine

**Comment by yanliang567** [comment]
reproduced 2 times with 2 attempts :(

**Comment by xiaofan-luan** [comment]
@yhmo any progress on it?

**Comment by yhmo** [comment]
#17461 add `debug.FreeOSMemory()` during bulkload to fix this issue. 
I use the 1GB numpy file to test, import the file by 5 times:
```
files100 = ["17394/100/vectors_128d_1m.npy"]
for i in range(5):
    tasks = utility.bulk_load(collection_name=collection_name, partition_name=None, is_row_based=False, files=files100)
```

Before the code change, the peak memory consumption is 5.6GB, and after all the tasks finished, the memory consumption steadily reduce to 4GB in one minute.

After the code change, the   peak memory consumption is 2.8GB, and after all the tasks finished,  the memory consumption reduce to 200MB quickly.

**Comment by yanliang567** [comment]
verified no crash any more on master-20220608-6d078ebe
