### ISSUE TITLE
[Bug]: Alter alias not working after restarting docker compose, collection failed  to load

### ISSUE THREAD

**Issue by alphinside** [milvus-io/milvus#17403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.2
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.0.2
- OS(Ubuntu or CentOS): Ubuntu 20.04
- CPU/Memory: Intel Core i7-11700k / 16gb
- GPU: -
- Others: -
```

### Current Behavior

After I shutdown the service using docker compose down, and reinitialize the service again using the docker compose up. Failed to alter alias and some collection ( not all ) failed to load. 

As a context as milvus doesn't have list alias API yet, I try to embed the collection name into it's description, so to know which alias map to whic collection, I just describe the alias collection and read the description to find the collection it's mapped to. Something like this ( the alias is `propertyUnits` and the literal collection name is `propertyUnits__v0_1`

```
<Collection>:
-------------
<name>: propertyUnits
<partitions>: [{"name": "_default", "collection_name": "propertyUnits", "description": ""}]
<description>: propertyUnits__v0_1
...
}
``` 

I found that after I downed and restarted the docker compose, alter alias not working directly. The alias only changed if I restarted the service again and the cycle continue. 

In addition I also encounter a collection load error ( only 1 apart from 4 collection I have ):

```
2022-06-07 07:14:21,155 : ERROR : RPC error: [wait_for_loading_collection], <BaseException: (code=1, message=collection 433716601692094465 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-06-07 07:14:20.651431', 'RPC error': '2022-06-07 07:14:21.155698'}>
2022-06-07 07:14:21,155 : ERROR : RPC error: [load_collection], <BaseException: (code=1, message=collection 433716601692094465 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-06-07 07:14:20.635769', 'RPC error': '2022-06-07 07:14:21.155832'}>
*** pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=collection 433716601692094465 has not been loaded to memory or load failed)>
``` 
The order of sequence I do :

1. docker compose up
2. create collections `propertyUnits__v0_1`
3. create collections `propertyUnits__v0_2`
4. insert data to both collections
5. create alias `propertyUnits` and assign to `propertyUnits__v0_1`
6. describe the `propertyUnits` alias ( working properly, mapped to `propertyUnits__v0_1` )
7. alter alias `propertyUnits` to `propertyUnits__v0_2`
8. describe the `propertyUnits` alias ( working properly, mapped to `propertyUnits__v0_2` )
9. docker compose down
10. docker compose up
11. alter alias `propertyUnits` to `propertyUnits__v0_1`
12. describe the `propertyUnits` alias ( not working, still mapped to `propertyUnits__v0_2` )
13. docker compose down
14. docker compose up
15. describe the `propertyUnits` alias ( now mapped to `propertyUnits__v0_1` )
16. alter alias `propertyUnits` to `propertyUnits__v0_2`
17. describe the `propertyUnits` alias ( not working, still mapped to `propertyUnits__v0_1` )
18. docker compose down
19. docker compose up
20. describe the `propertyUnits` alias ( now mapped to `propertyUnits__v0_2`)

### Expected Behavior

- Alter alias working immediately even after service restart
- No collection load error

### Steps To Reproduce

```markdown
The order of sequence I do :

1. docker compose up
2. create collections `propertyUnits__v0_1`
3. create collections `propertyUnits__v0_2`
4. insert data to both collections
5. create alias `propertyUnits` and assign to `propertyUnits__v0_1`
6. describe the `propertyUnits` alias ( working properly, mapped to `propertyUnits__v0_1` )
7. alter alias `propertyUnits` to `propertyUnits__v0_2`
8. describe the `propertyUnits` alias ( working properly, mapped to `propertyUnits__v0_2` )
9. docker compose down
10. docker compose up
11. alter alias `propertyUnits` to `propertyUnits__v0_1`
12. describe the `propertyUnits` alias ( not working, still mapped to `propertyUnits__v0_2` )
13. docker compose down
14. docker compose up
15. describe the `propertyUnits` alias ( now mapped to `propertyUnits__v0_1` )
16. alter alias `propertyUnits` to `propertyUnits__v0_2`
17. describe the `propertyUnits` alias ( not working, still mapped to `propertyUnits__v0_1` )
18. docker compose down
19. docker compose up
20. describe the `propertyUnits` alias ( now mapped to `propertyUnits__v0_2`)
```

### Milvus Log

No error on alter alias

Error on collection load : 

```
2022-06-07 07:14:21,155 : ERROR : RPC error: [wait_for_loading_collection], <BaseException: (code=1, message=collection 433716601692094465 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-06-07 07:14:20.651431', 'RPC error': '2022-06-07 07:14:21.155698'}>
2022-06-07 07:14:21,155 : ERROR : RPC error: [load_collection], <BaseException: (code=1, message=collection 433716601692094465 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-06-07 07:14:20.635769', 'RPC error': '2022-06-07 07:14:21.155832'}>
*** pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=collection 433716601692094465 has not been loaded to memory or load failed)>
```

**Comment by yanliang567** [comment]
@alphinside thank you for the issue. could you please use docker-compose logs > milvus.log to export the logs for investigation?

/assign @alphinside 
/unassign

**Comment by alphinside** [comment]
Sure, I reproduce the load error and do the alter alias (but alias not changed) in this log @yanliang567 
[milvus.log](https://github.com/milvus-io/milvus/files/8849306/milvus.log)

**Comment by yanliang567** [comment]
@soothing-rain could you please take a look at this issue?
/assign @soothing-rain 
/unassign

**Comment by alphinside** [comment]
adding more logs here. It appears that after multilple collection load and release, some collection will be failed to load 
[milvus.log](https://github.com/milvus-io/milvus/files/8849858/milvus.log)

**Comment by soothing-rain** [comment]
Hey @alphinside ,

1) Regarding collection load failure, this is a known issue to Milvus 2.0.2. You can try our hot-fixed version (docker pull milvusdb/milvus:v2.0.2-hotfix-16885), or wait a bit for our Milvus 2.1 release :)
2) About the alias thing, I am not sure what you mean by `I found that after I downed and restarted the docker compose, alter alias not working directly. The alias only changed if I restarted the service again and the cycle continue.` What do you mean by `restarted the service again` ? Did you bring down and bring up Milvus twice with docker compose? If so you can update these steps after `Steps To Reproduce` step 9?

**Comment by alphinside** [comment]
Hi @soothing-rain thank you for your information, will try that version

2. for the alias thing, yes after the first docker compose down-up restart, in order the alias to have effect, I need to restart the docker compose again. Sure will update the detail focused on the alias now

**Comment by alphinside** [comment]
I've also found that after restarting docker compose, the alias appeared as collection themselves ( they appear when I try to list collection using `utility.list_collections`  ).

I also try dropping the collection which is linked to the alias ( without dropping the alias) and recreate the collection and reassign the alias, it gives me this error 

```
milvus-standalone | [2022/06/08 14:36:19.247 +00:00] [ERROR] [root_coord.go:2024] ["CreateAlias failed"] [role=rootcoord] [alias=developerProjects_house] ["collection name"=developerProjects_house__v0_1] [msgID=433768914909660395] [error="meta table add alias failed, error = collection alias collides with existing collection name. collection = developerProjects_house, alias = developerProjects_house"] [stack="github.com/milvus-io/milvus/internal/rootcoord.(*Core).CreateAlias\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:2024\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).CreateAlias\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:82\ngithub.com/milvus-io/milvus/internal/proto/rootcoordpb._RootCoord_CreateAlias_Handler.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proto/rootcoordpb/root_coord.pb.go:933\ngithub.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38\ngithub.com/milvus-io/milvus/internal/proto/rootcoordpb._RootCoord_CreateAlias_Handler\n\t/go/src/github.com/milvus-io/milvus/internal/proto/rootcoordpb/root_coord.pb.go:935\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934"]
```

full log in here 
[milvus_2.log](https://github.com/milvus-io/milvus/files/8862693/milvus_2.log)
@soothing-rain

**Comment by EricStarer** [comment]
I found that you can solve this problem by reinitialize a `Collection` object and do not need to down&&up milvus.

**Comment by EricStarer** [comment]
I found that you can refresh the alias state by reinitialize a `Collection` object using the alias. @alphinside

**Comment by EricStarer** [comment]
Actually, the bug is because the `collection schema` is not updated when alias is altered or droped. So we need to reinitialize a `Collection` object to update the schema from the milvus. @alphinside
