### ISSUE TITLE
[Enhancement]: Add log_level env variable to milvus standalone

### ISSUE THREAD

**Issue by dariocurr** [milvus-io/milvus#17401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

I would like the option to edit the log level when running `milvus-standalone`.

### Why is this needed?

To don't mess up the shell

**Comment by xiaofan-luan** [comment]
I thought there is already already a switch at milvus.yaml, do we want to config log level from local env as well?

**Comment by dariocurr** [comment]
Yeah we would like it. The console is messed up and unreadble

**Comment by soothing-rain** [comment]
Hey @dariocurr it appears that there is an env variable for the config path (altho I never tried it :) )

https://github.com/milvus-io/milvus/blob/9c463750330801057cc515a4b129eb6f40e9a1c9/internal/util/paramtable/base_table.go#L105
