### ISSUE TITLE
[Bug]: Hangs at outputting repeated log after Milvus recovered from rootcoord pod kill chaos

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#17408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220606-98e95275
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.1.0.dev66
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

running `verify_all_collections.py` timeout 

repeated log in proxy pod
```
[2022/06/06 13:51:26.889 +00:00] [DEBUG] [task.go:2526] ["get index state"] [role=proxy] [indexBuildIDs="[433723178946658312,433723178946658308,433723178946658306,433723273737928708,433723178946658310,433723273737928706]"]
[2022/06/06 13:51:26.890 +00:00] [DEBUG] [impl.go:2148] ["GetIndexState done"] [traceID=38ba8e43bb451e45] [role=proxy] [MsgID=433723126746001454] [BeginTs=433723404942573569] [EndTs=433723404942573569] [db=] [collection=Checker__JANoT8fv] [field=float_vector] ["index name"=_default_idx]
[2022/06/06 13:51:27.392 +00:00] [DEBUG] [impl.go:2078] ["GetIndexState received"] [traceID=18cdc665452a0264] [role=proxy] [db=] [collection=Checker__JANoT8fv] [field=float_vector] ["index name"=_default_idx]
[2022/06/06 13:51:27.397 +00:00] [DEBUG] [id.go:140] ["IDAllocator pickCanDoFunc"] [need=1] [total=122130] [remainReqCnt=0]
[2022/06/06 13:51:27.397 +00:00] [DEBUG] [impl.go:2109] ["GetIndexState enqueued"] [traceID=18cdc665452a0264] [role=proxy] [MsgID=433723126746001455] [BeginTs=433723405074169858] [EndTs=433723405074169858] [db=] [collection=Checker__JANoT8fv] [field=float_vector] ["index name"=_default_idx]

```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
see http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/6149/pipeline/224
```

### Milvus Log

failed job: http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/6149/pipeline

log: [artifacts-rootcoord-pod-kill-6149-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/8849954/artifacts-rootcoord-pod-kill-6149-server-logs.1.tar.gz)

### Anything else?

The repeated log is the same as https://github.com/milvus-io/milvus/issues/17330

**Comment by xiaofan-luan** [comment]
From the indexcoord log we find 4 index task in none mode and never assigned, need to figure out the reason

**Comment by zhuwenxing** [comment]
I tried twice again, but it was not reproduced, so this issue does not appear stably.

**Comment by xiaofan-luan** [comment]
> I tried twice again, but it was not reproduced, so this issue does not appear stably.

/

> I tried twice again, but it was not reproduced, so this issue does not appear stably.

This might be the timing issue between flush and index creation, czs007 and I are working on it

**Comment by xiaocai2333** [comment]
rootcoord code
```
// Execute task execution
func (t *DropIndexReqTask) Execute(ctx context.Context) error {
	if t.Type() != commonpb.MsgType_DropIndex {
		return fmt.Errorf("drop index, msg type = %s", commonpb.MsgType_name[int32(t.Type())])
	}
	if err := t.core.RemoveIndex(ctx, t.Req.CollectionName, t.Req.IndexName); err != nil {
		return err
	}
	_, _, err := t.core.MetaTable.DropIndex(t.Req.CollectionName, t.Req.FieldName, t.Req.IndexName)
	return err
}
```

If rootcoord was killed between `t.core.RemoveIndex()` and `t.core.MetaTable.DropIndex`, the DropIndex task will failed. IndexCoord will remove the index with the indexName, but rootcoord did not successfully clean up the meta in etcd. So when rootcoord restarted, the segment index info still exist in rootcoord.

![image](https://user-images.githubusercontent.com/46207236/172317471-acfd2af3-ef83-4c38-9287-d2736e3a421f.png)
The dropIndex task failed, but sdk didn't retry. So it is not idempotent.

**Comment by zhuwenxing** [comment]
This issue also has the same behavior
https://github.com/milvus-io/milvus/issues/17369

**Comment by XuanYang-cn** [comment]
Same issue in http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/6274/pipeline

and http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/6271/pipeline/

**Comment by xiaofan-luan** [comment]
@xiaocai2333 is working on this~

**Comment by zhuwenxing** [comment]
rootcoord pod kill with kafka mq
failed job: https://github.com/milvus-io/milvus/runs/6905128402?check_suite_focus=true
log: https://github.com/milvus-io/milvus/suites/6949332631/artifacts/270983099

**Comment by zhuwenxing** [comment]
Many other pod kill chaos tests that were passed, now also have this issue.
datacoord: http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/6568/pipeline 
querynode: http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/6562/pipeline

**Comment by xiaocai2333** [comment]
pr is merged, please check it 
/unassign
/assign @zhuwenxing

**Comment by zhuwenxing** [comment]
Not reproduced yet! remove the critical label.
