### ISSUE TITLE
[Bug]: Failed to create producer

### ISSUE THREAD

**Issue by WangErXiao** [milvus-io/milvus#17410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.2
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Cluster stop response  search request suddenly. 
I find proxy log as below. After I used pulsar-admin namespaces clear-backlog public/default, it still can't work.

time="2022-06-07T06:19:45Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededException: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-prd-search-0"
[2022/06/07 06:19:48.353 +00:00] [DEBUG] [time_recorder.go:78] ["proxy execute search 433738937070256130: done (51061ms)"]
[2022/06/07 06:19:48.353 +00:00] [DEBUG] [impl.go:2500] ["Search done"] [traceID=605e39ff9c4fd381] [role=proxy] [msgID=433738937070256130] [db=] [collection=hello_milvus] [partitions="[]"] [dsl=] [len(PlaceholderGroup)=42] [OutputFields="[pk,random]"] [search_params="[{\"key\":\"params\",\"value\":\"{\\\"nprobe\\\":1,\\\"round_decimal\\\":-1}\"},{\"key\":\"anns_field\",\"value\":\"embeddings\"},{\"key\":\"topk\",\"value\":\"100\"},{\"key\":\"metric_type\",\"value\":\"L2\"},{\"key\":\"round_decimal\",\"value\":\"-1\"}]"] [travel_timestamp=0] [guarantee_timestamp=0]
panic: Failed to create producer by-prd-search-0, error = All attempts results:
attempt #1:server error: ProducerBlockedQuotaExceededException: Cannot create producer on topic with backlog quota exceeded
attempt #2:server error: ProducerBlockedQuotaExceededException: Cannot create producer on topic with backlog quota exceeded
attempt #3:server error: ProducerBlockedQuotaExceededException: Cannot create producer on topic with backlog quota exceeded
attempt #4:server error: ProducerBlockedQuotaExceededException: Cannot create producer on topic with backlog quota exceeded
attempt #5:server error: ProducerBlockedQuotaExceededException: Cannot create producer on topic with backlog quota exceeded
attempt #6:server error: ProducerBlockedQuotaExceededException: Cannot create producer on topic with backlog quota exceeded
attempt #7:server error: ProducerBlockedQuotaExceededException: Cannot create producer on topic with backlog quota exceeded
attempt #8:server error: ProducerBlockedQuotaExceededException: Cannot create producer on topic with backlog quota exceeded
attempt #9:server error: ProducerBlockedQuotaExceededException: Cannot create producer on topic with backlog quota exceeded
attempt #10:server error: ProducerBlockedQuotaExceededException: Cannot create producer on topic with backlog quota exceeded
attempt #11:server error: ProducerBlockedQuotaExceededException: Cannot create producer on topic with backlog quota exceeded

goroutine 356 [running]:
github.com/milvus-io/milvus/internal/msgstream.(*mqMsgStream).AsProducer(0xc000a152b0, 0xc001154ba0, 0x1, 0x1)
     /go/src/github.com/milvus-io/milvus/internal/msgstream/mq_msgstream.go:124 +0x278
github.com/milvus-io/milvus/internal/proxy.(*singleTypeChannelsMgr).createMsgStream(0xc000a220b0, 0x603bf6ba59c0001, 0x2, 0x2)
     /go/src/github.com/milvus-io/milvus/internal/proxy/channels_mgr.go:392 +0x633
github.com/milvus-io/milvus/internal/proxy.(*channelsMgrImpl).createDQLStream(0xc000a16010, 0x603bf6ba59c0001, 0x0, 0x0)
     /go/src/github.com/milvus-io/milvus/internal/proxy/channels_mgr.go:490 +0xeb
github.com/milvus-io/milvus/internal/proxy.(*searchTask).Execute(0xc000d1bb80, 0x3669478, 0xc00110f620, 0x0, 0x0)
     /go/src/github.com/milvus-io/milvus/internal/proxy/task.go:1694 +0xcaf
github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask(0xc000a24000, 0x36871f0, 0xc000d1bb80, 0x3684620, 0xc000013c30)
     /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:488 +0x996
created by github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).queryLoop
     /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:548 +0x1a5
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1ad209c]

**Comment by WangErXiao** [comment]
proxy continue restarting!

**Comment by yanliang567** [comment]
@WangErXiao Could you please use this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @WangErXiao 
/unassign

**Comment by xiaofan-luan** [comment]
keep it on track

**Comment by Sivannnnnn** [comment]
@JackLCL @xiaofan-luan @yanliang567 
hello, i used milvus v2.1.1 cluster，I am importing a large amount of data to Milvus. When importing data to 250 million, I also encountered this problem, and the restart cannot be solved. May I ask which version is expected to solve this problem?
