### ISSUE TITLE
Remove AlterAlias for collection 

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#17419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

1. AlterAlias is meaningless the alias does not need to alter
2. AlterAlias is implemented at the same with AddAlias

**Comment by xiaofan-luan** [comment]
alter alias means change alias A from pointing collectionA to pointing collectionB, although the implementation is weak the semantic is clear
