### ISSUE TITLE
[Bug]: getSegmentInfo: queryNode 3 is offline

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#17411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220606-98e95275
- Deployment mode(standalone or cluster): cluster with 2 data nodes
```

### Current Behavior

Fail to self.utility_wrap.get_query_segment_info(name)
```
[2022-06-07 14:12:59,550 - INFO - ci_test]: assert flush: 3.1987709999084473, entities: 3000 (test_e2e.py:41)
[2022-06-07 14:12:59,551 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 20], kwargs: {} (api_request.py:55)
[2022-06-07 14:13:03,357 - DEBUG - ci_test]: (api_response) : None  (api_request.py:27)
[2022-06-07 14:13:03,358 - INFO - ci_test]: [test][2022-06-07T06:12:59Z][2022-06-07T06:13:03Z][3.80661120s] e2e__WK11Z6gL load () -> (None, True) (wrapper.py:30)
[2022-06-07 14:13:03,358 - DEBUG - ci_test]: (api_request)  : [get_query_segment_info] args: ['e2e__WK11Z6gL', 20, 'default'], kwargs: {} (api_request.py:55)
[2022-06-07 14:13:03,376 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/yanliang/fork/milvus/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
    res = func(*args, **kwargs)
  File "/Users/yanliang/fork/milvus/tests/python_client/utils/api_request.py", line 56, in api_request
    return func(*arg, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/orm/utility.py", line 578, in get_query_segment_info
    return _get_connection(using).get_query_segment_info(collection_name, timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 61, in handler
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 44, in handler
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 79, in handler
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 75, in handler
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 460, in get_query_segment_info
    raise MilvusException(status.error_code, status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=getSegmentInfo: queryNode 3 is offline)>
 (api_request.py:35)
[2022-06-07 14:13:03,376 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=getSegmentInfo: queryNode 3 is offline)> (api_request.py:36)

```

### Expected Behavior

return successfully with segments info that loaded in querynodes

### Steps To Reproduce

```markdown
1. create a collection
2. insert 3000 entities
3. load collection
4. self.utility_wrap.get_query_segment_info(name)

Notes:
I deployed Milvus cluster with 2 data nodes and 1 querynode, 
one of data node crashed once before and recovered, but querynode is always running healthy. 
So that's confusing about the msg "querynode 3 is offline"
```

### Milvus Log

[get.seg.info.log.tar.gz](https://github.com/milvus-io/milvus/files/8850624/get.seg.info.log.tar.gz)

**Comment by yanliang567** [comment]
@soothing-rain this reproduces when trying to run tests after issue #17394 reproduced. Not sure whether they are connected or not.
/assign @soothing-rain 
/unassign

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```gfm
> - Milvus version: master-20220606-98e95275
> - Deployment mode(standalone or cluster): cluster with 2 data nodes
> ```
> 
> ### Current Behavior
> Fail to self.utility_wrap.get_query_segment_info(name)
> 
> ```
> [2022-06-07 14:12:59,550 - INFO - ci_test]: assert flush: 3.1987709999084473, entities: 3000 (test_e2e.py:41)
> [2022-06-07 14:12:59,551 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 20], kwargs: {} (api_request.py:55)
> [2022-06-07 14:13:03,357 - DEBUG - ci_test]: (api_response) : None  (api_request.py:27)
> [2022-06-07 14:13:03,358 - INFO - ci_test]: [test][2022-06-07T06:12:59Z][2022-06-07T06:13:03Z][3.80661120s] e2e__WK11Z6gL load () -> (None, True) (wrapper.py:30)
> [2022-06-07 14:13:03,358 - DEBUG - ci_test]: (api_request)  : [get_query_segment_info] args: ['e2e__WK11Z6gL', 20, 'default'], kwargs: {} (api_request.py:55)
> [2022-06-07 14:13:03,376 - ERROR - ci_test]: Traceback (most recent call last):
>   File "/Users/yanliang/fork/milvus/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
>     res = func(*args, **kwargs)
>   File "/Users/yanliang/fork/milvus/tests/python_client/utils/api_request.py", line 56, in api_request
>     return func(*arg, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/orm/utility.py", line 578, in get_query_segment_info
>     return _get_connection(using).get_query_segment_info(collection_name, timeout=timeout)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 61, in handler
>     raise e
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 44, in handler
>     return func(self, *args, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 79, in handler
>     raise e
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 75, in handler
>     return func(*args, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 460, in get_query_segment_info
>     raise MilvusException(status.error_code, status.reason)
> pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=getSegmentInfo: queryNode 3 is offline)>
>  (api_request.py:35)
> [2022-06-07 14:13:03,376 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=getSegmentInfo: queryNode 3 is offline)> (api_request.py:36)
> ```
> 
> ### Expected Behavior
> return successfully with segments info that loaded in querynodes
> 
> ### Steps To Reproduce
> ```gfm
> 1. create a collection
> 2. insert 3000 entities
> 3. load collection
> 4. self.utility_wrap.get_query_segment_info(name)
> 
> Notes:
> I deployed Milvus cluster with 2 data nodes and 1 querynode, 
> one of data node crashed once before and recovered, but querynode is always running healthy. 
> So that's confusing about the msg "querynode 3 is offline"
> ```
> 
> ### Milvus Log
> [get.seg.info.log.tar.gz](https://github.com/milvus-io/milvus/files/8850624/get.seg.info.log.tar.gz)
> 
> ### Anything else?
> _No response_

I guess 3 is the querynode nodeID and it's growing globally~

**Comment by soothing-rain** [comment]
Looking at QueryCoord log:
```
[2022/06/06 11:55:39.050 +00:00] [INFO] [cluster.go:600] ["registerNode: create a new QueryNode"] [nodeID=18] [address=10.97.11.19:21123] [state=0]
[2022/06/06 11:55:39.050 +00:00] [INFO] [querynode.go:125] ["start: queryNode client start success"] [nodeID=18] [address=10.97.11.19:21123]
[2022/06/06 11:55:39.055 +00:00] [INFO] [cluster.go:600] ["registerNode: create a new QueryNode"] [nodeID=3] [address=10.97.11.228:21123] [state=2]
```

So QueryCoord thinks QueryNode ID=3 is still alive, but QueryNode ID=18 is the only living QueryNode.

@congqixia WDYT?

**Comment by jiaoew1991** [comment]
like  #17367

**Comment by yanliang567** [comment]
still reproduces on master-20220614-f9553970 
[querynode.offline.log.tar.gz](https://github.com/milvus-io/milvus/files/8904773/querynode.offline.log.tar.gz)

/unassign 
/assign @jiaoew1991 @congqixia

**Comment by yanliang567** [comment]
verified not repro on master-20220617-0f877636

**Comment by soothing-rain** [comment]
Still reproducible here.

Ways to reproduce:
(1) Run standalone, shut it down.
(2) Repeat (1) several times.
(3) Check out standalone logs, you can see logs like:
```
[2022/06/23 16:36:37.185 +08:00] [INFO] [cluster.go:612] ["registerNode: create a new QueryNode"] [nodeID=37] [address=192.168.0.101:21123] [state=0]
[2022/06/23 16:36:37.185 +08:00] [INFO] [querynode.go:125] ["start: queryNode client start success"] [nodeID=37] [address=192.168.0.101:21123]
[2022/06/23 16:36:37.188 +08:00] [INFO] [cluster.go:612] ["registerNode: create a new QueryNode"] [nodeID=13] [address=192.168.0.101:21123] [state=2]
[2022/06/23 16:36:37.190 +08:00] [INFO] [cluster.go:612] ["registerNode: create a new QueryNode"] [nodeID=17] [address=192.168.0.101:21123] [state=2]
[2022/06/23 16:36:37.191 +08:00] [INFO] [cluster.go:612] ["registerNode: create a new QueryNode"] [nodeID=26] [address=192.168.0.101:21123] [state=2]
[2022/06/23 16:36:37.192 +08:00] [INFO] [cluster.go:612] ["registerNode: create a new QueryNode"] [nodeID=5] [address=192.168.0.101:21123] [state=2]
```
(4) Insert a lot of data, you can get error messages like:
```
[2022/06/23 16:38:38.049 +08:00] [ERROR] [impl.go:904] ["getSegmentInfoRequest failed"] [role=querycoord] [collectionID=434103518952423425] [segmentIDs="[434103519122817025,434103519201460225]"] [msgID=0] [error="getSegmentInfo: queryNode 5 is offline"] [stack="github.com/milvus-io/milvus/internal/querycoord.(*QueryCoord).GetSegmentInfo\n\t/Users/yuchengao/Documents/GitHub/soothing-rain/milvus/internal/querycoord/impl.go:904\ngithub.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).GetSegmentInfo\n\t/Users/yuchengao/Documents/GitHub/soothing-rain/milvus/internal/distributed/querycoord/service.go:376\ngithub.com/milvus-io/milvus/internal/proto/querypb._QueryCoord_GetSegmentInfo_Handler.func1\n\t/Users/yuchengao/Documents/GitHub/soothing-rain/milvus/internal/proto/querypb/query_coord.pb.go:3427\ngithub.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1\n\t/Users/yuchengao/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38\ngithub.com/milvus-io/milvus/internal/proto/querypb._QueryCoord_GetSegmentInfo_Handler\n\t/Users/yuchengao/Documents/GitHub/soothing-rain/milvus/internal/proto/querypb/query_coord.pb.go:3429\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/Users/yuchengao/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1282\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/Users/yuchengao/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1616\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/Users/yuchengao/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:921"]
```

**Comment by yah01** [comment]
> Still reproducible here.
> 
> Ways to reproduce: (1) Run standalone, shut it down. (2) Repeat (1) several times. (3) Check out standalone logs, you can see logs like:
> 
> ```
> [2022/06/23 16:36:37.185 +08:00] [INFO] [cluster.go:612] ["registerNode: create a new QueryNode"] [nodeID=37] [address=192.168.0.101:21123] [state=0]
> [2022/06/23 16:36:37.185 +08:00] [INFO] [querynode.go:125] ["start: queryNode client start success"] [nodeID=37] [address=192.168.0.101:21123]
> [2022/06/23 16:36:37.188 +08:00] [INFO] [cluster.go:612] ["registerNode: create a new QueryNode"] [nodeID=13] [address=192.168.0.101:21123] [state=2]
> [2022/06/23 16:36:37.190 +08:00] [INFO] [cluster.go:612] ["registerNode: create a new QueryNode"] [nodeID=17] [address=192.168.0.101:21123] [state=2]
> [2022/06/23 16:36:37.191 +08:00] [INFO] [cluster.go:612] ["registerNode: create a new QueryNode"] [nodeID=26] [address=192.168.0.101:21123] [state=2]
> [2022/06/23 16:36:37.192 +08:00] [INFO] [cluster.go:612] ["registerNode: create a new QueryNode"] [nodeID=5] [address=192.168.0.101:21123] [state=2]
> ```
> 
> (4) Insert a lot of data, you can get error messages like:
> 
> ```
> [2022/06/23 16:38:38.049 +08:00] [ERROR] [impl.go:904] ["getSegmentInfoRequest failed"] [role=querycoord] [collectionID=434103518952423425] [segmentIDs="[434103519122817025,434103519201460225]"] [msgID=0] [error="getSegmentInfo: queryNode 5 is offline"] [stack="github.com/milvus-io/milvus/internal/querycoord.(*QueryCoord).GetSegmentInfo\n\t/Users/yuchengao/Documents/GitHub/soothing-rain/milvus/internal/querycoord/impl.go:904\ngithub.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).GetSegmentInfo\n\t/Users/yuchengao/Documents/GitHub/soothing-rain/milvus/internal/distributed/querycoord/service.go:376\ngithub.com/milvus-io/milvus/internal/proto/querypb._QueryCoord_GetSegmentInfo_Handler.func1\n\t/Users/yuchengao/Documents/GitHub/soothing-rain/milvus/internal/proto/querypb/query_coord.pb.go:3427\ngithub.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1\n\t/Users/yuchengao/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38\ngithub.com/milvus-io/milvus/internal/proto/querypb._QueryCoord_GetSegmentInfo_Handler\n\t/Users/yuchengao/Documents/GitHub/soothing-rain/milvus/internal/proto/querypb/query_coord.pb.go:3429\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/Users/yuchengao/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1282\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/Users/yuchengao/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1616\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/Users/yuchengao/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:921"]
> ```

is it recoverable?

**Comment by soothing-rain** [comment]
> registerNode: create a new QueryNode

Oh I can see that the meta data is cleared correctly. Let me see if it is recoverable.

**Comment by soothing-rain** [comment]
> > Still reproducible here.
> > Ways to reproduce: (1) Run standalone, shut it down. (2) Repeat (1) several times. (3) Check out standalone logs, you can see logs like:
> > ```
> > [2022/06/23 16:36:37.185 +08:00] [INFO] [cluster.go:612] ["registerNode: create a new QueryNode"] [nodeID=37] [address=192.168.0.101:21123] [state=0]
> > [2022/06/23 16:36:37.185 +08:00] [INFO] [querynode.go:125] ["start: queryNode client start success"] [nodeID=37] [address=192.168.0.101:21123]
> > [2022/06/23 16:36:37.188 +08:00] [INFO] [cluster.go:612] ["registerNode: create a new QueryNode"] [nodeID=13] [address=192.168.0.101:21123] [state=2]
> > [2022/06/23 16:36:37.190 +08:00] [INFO] [cluster.go:612] ["registerNode: create a new QueryNode"] [nodeID=17] [address=192.168.0.101:21123] [state=2]
> > [2022/06/23 16:36:37.191 +08:00] [INFO] [cluster.go:612] ["registerNode: create a new QueryNode"] [nodeID=26] [address=192.168.0.101:21123] [state=2]
> > [2022/06/23 16:36:37.192 +08:00] [INFO] [cluster.go:612] ["registerNode: create a new QueryNode"] [nodeID=5] [address=192.168.0.101:21123] [state=2]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (4) Insert a lot of data, you can get error messages like:
> > ```
> > [2022/06/23 16:38:38.049 +08:00] [ERROR] [impl.go:904] ["getSegmentInfoRequest failed"] [role=querycoord] [collectionID=434103518952423425] [segmentIDs="[434103519122817025,434103519201460225]"] [msgID=0] [error="getSegmentInfo: queryNode 5 is offline"] [stack="github.com/milvus-io/milvus/internal/querycoord.(*QueryCoord).GetSegmentInfo\n\t/Users/yuchengao/Documents/GitHub/soothing-rain/milvus/internal/querycoord/impl.go:904\ngithub.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).GetSegmentInfo\n\t/Users/yuchengao/Documents/GitHub/soothing-rain/milvus/internal/distributed/querycoord/service.go:376\ngithub.com/milvus-io/milvus/internal/proto/querypb._QueryCoord_GetSegmentInfo_Handler.func1\n\t/Users/yuchengao/Documents/GitHub/soothing-rain/milvus/internal/proto/querypb/query_coord.pb.go:3427\ngithub.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1\n\t/Users/yuchengao/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38\ngithub.com/milvus-io/milvus/internal/proto/querypb._QueryCoord_GetSegmentInfo_Handler\n\t/Users/yuchengao/Documents/GitHub/soothing-rain/milvus/internal/proto/querypb/query_coord.pb.go:3429\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/Users/yuchengao/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1282\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/Users/yuchengao/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1616\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/Users/yuchengao/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:921"]
> > ```
> 
> is it recoverable?

Turns out it is not recoverable.

Try this script to reproduce (after stop & start Milvus standalone a couple of times). Happens when calling `get_query_segment_info`:
```
# hello_milvus.py demonstrates the basic operations of PyMilvus, a Python SDK of Milvus.
# 1. connect to Milvus
# 2. create collection
# 3. insert data
# 4. create index
# 5. search, query, and hybrid search on entities
# 6. delete entities by PK
# 7. drop collection

import random
import time

from pymilvus import (
    connections,
    utility,
    FieldSchema, CollectionSchema, DataType,
    Collection,
)

fmt = "\n=== {:30} ===\n"
search_latency_fmt = "search latency = {:.4f}s"

#################################################################################
# 1. connect to Milvus
# Add a new connection alias `default` for Milvus server in `localhost:19530`
# Actually the "default" alias is a buildin in PyMilvus.
# If the address of Milvus is the same as `localhost:19530`, you can omit all
# parameters and call the method as: `connections.connect()`.
#
# Note: the `using` parameter of the following methods is default to "default".
print(fmt.format("start connecting to Milvus"))
connections.connect("default", host="localhost", port="19530")

has = utility.has_collection("hello_milvus")
print(f"Does collection hello_milvus exist in Milvus: {has}")

#################################################################################
# 2. create collection
# We're going to create a collection with 3 fields.
# +-+------------+------------+------------------+------------------------------+
# | | field name | field type | other attributes |       field description      |
# +-+------------+------------+------------------+------------------------------+
# |1|    "pk"    |    Int64   |  is_primary=True |      "primary field"         |
# | |            |            |   auto_id=False  |                              |
# +-+------------+------------+------------------+------------------------------+
# |2|  "random"  |    Double  |                  |      "a double field"        |
# +-+------------+------------+------------------+------------------------------+
# |3|"embeddings"| FloatVector|     dim=8        |  "float vector with dim 8"   |
# +-+------------+------------+------------------+------------------------------+
fields = [
    FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, auto_id=False),
    FieldSchema(name="random", dtype=DataType.DOUBLE),
    FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=8)
]

schema = CollectionSchema(fields, "hello_milvus is the simplest demo to introduce the APIs")

print(fmt.format("Create collection `hello_milvus`"))
hello_milvus = Collection("hello_milvus", schema, consistency_level="Strong")
print(fmt.format("Start loading"))
hello_milvus.load()
time.sleep(5)

################################################################################
# 3. insert data
# We are going to insert 3000 rows of data into `hello_milvus`
# Data to be inserted must be organized in fields.
#
# The insert() method returns:
# - either automatically generated primary keys by Milvus if auto_id=True in the schema;
# - or the existing primary key field from the entities if auto_id=False in the schema.
print(fmt.format("Start inserting entities"))
num_entities = 3000
entities = [
    # provide the pk field because `auto_id` is set to False
    [i for i in range(num_entities)],
    [float(random.randrange(-20, -10)) for _ in range(num_entities)],  # field random
    [[random.random() for _ in range(8)] for _ in range(num_entities)],  # field embeddings
]

insert_result = hello_milvus.insert(entities)

print(f"Number of entities in Milvus: {hello_milvus.num_entities}")  # check the num_entites

time.sleep(10)

################################################################################
# 4. create index
# We are going to create an IVF_FLAT index for hello_milvus collection.
# create_index() can only be applied to `FloatVector` and `BinaryVector` fields.
# print(fmt.format("Start Creating index IVF_FLAT"))
# index = {
#     "index_type": "IVF_FLAT",
#     "metric_type": "L2",
#     "params": {"nlist": 128},
# }

#hello_milvus.create_index("embeddings", index)

################################################################################
# 5. search, query, and hybrid search
# After data were inserted into Milvus and indexed, you can perform:
# - search based on vector similarity
# - query based on scalar filtering(boolean, int, etc.)
# - hybrid search based on vector similarity and scalar filtering.
#

# Before conducting a search or a query, you need to load the data in `hello_milvus` into memory.


# -----------------------------------------------------------------------------
# search based on vector similarity

print(connections._fetch_handler("default").get_query_segment_info(collection_name='hello_milvus'))

print(fmt.format("Start searching based on vector similarity"))
vectors_to_search = entities[-1][-2:]
search_params = {
    "metric_type": "l2",
    "params": {"nprobe": 10},
}

start_time = time.time()
result = hello_milvus.search(vectors_to_search, "embeddings", search_params, limit=3, output_fields=["random"])
end_time = time.time()

for hits in result:
    for hit in hits:
        print(f"hit: {hit}, random field: {hit.entity.get('random')}")
print(search_latency_fmt.format(end_time - start_time))

# -----------------------------------------------------------------------------
# query based on scalar filtering(boolean, int, etc.)
print(fmt.format("Start querying with `random > -14`"))

start_time = time.time()
result = hello_milvus.query(expr="random > -14", output_fields=["random", "embeddings"])
end_time = time.time()

print(f"query result:\n-{result[0]}")
print(search_latency_fmt.format(end_time - start_time))

# -----------------------------------------------------------------------------
# hybrid search
print(fmt.format("Start hybrid searching with `random > -12`"))

start_time = time.time()
result = hello_milvus.search(vectors_to_search, "embeddings", search_params, limit=3, expr="random > -12", output_fields=["random"])
end_time = time.time()

for hits in result:
    for hit in hits:
        print(f"hit: {hit}, random field: {hit.entity.get('random')}")
print(search_latency_fmt.format(end_time - start_time))

###############################################################################
# 6. delete entities by PK
# You can delete entities by their PK values using boolean expressions.
ids = insert_result.primary_keys
expr = f"pk in [{ids[0]}, {ids[1]}]"
print(fmt.format(f"Start deleting with expr `{expr}`"))

result = hello_milvus.query(expr=expr, output_fields=["random", "embeddings"])
print(f"query before delete by expr=`{expr}` -> result: \n-{result[0]}\n-{result[1]}\n")

hello_milvus.delete(expr)

result = hello_milvus.query(expr=expr, output_fields=["random", "embeddings"])
print(f"query after delete by expr=`{expr}` -> result: {result}\n")


###############################################################################
# 7. drop collection
# Finally, drop the hello_milvus collection
print(fmt.format("Drop collection `hello_milvus`"))
utility.drop_collection("hello_milvus")
```

**Comment by yanliang567** [comment]
not reproduce to me recently.
