### ISSUE TITLE
[Bug]: The old query node pod destoryed, but did not unregister meta from etcd.

### ISSUE THREAD

**Issue by angelapytao** [milvus-io/milvus#17426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvusdb/milvus-dev(master-latest)
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): K8S
- CPU/Memory: 
- GPU: 
- Others: GitCommit: a2d2ad88
```

### Current Behavior

```
set querynode 2 pods, redeploy querynode, the old pod did not unregister meta data from etcd.
![13651654651273_ pic](https://user-images.githubusercontent.com/5369411/172513548-e73edc83-35ac-4b7d-920e-d8f9be48b1f1.jpg)

<img width="522" alt="image" src="https://user-images.githubusercontent.com/5369411/172513777-065a28ba-bb97-4a9f-860b-7c1e9af9f7c0.png">


### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

_No response_

**Comment by yanliang567** [comment]
@angelapytao thank you for the issue. But I don't understand the reproduce steps above, could you please specify more details about the step, and what error/msg did you see from the milvus?
Also could you please use this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @angelapytao 
/unassign

**Comment by soothing-rain** [comment]
@congqixia Could it be related to #17411 ?

**Comment by congqixia** [comment]
> @congqixia Could it be related to #17411 ?

Might be related. Since some load balance shall be performed before removing the etcd entry.
