### ISSUE TITLE
[Bug]: [bulkload] Occasional import request failed: Import task queue max size is 32, currently there are 32 tasks is pending. Not able to execute this request with 1 tasks.

### ISSUE THREAD

**Issue by yongpengli-z** [milvus-io/milvus#17425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220607-af108b5b
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):java-sdk 2.0.6-snapshot
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

After  bulk load multiple files repeatedly,ImportRequest failed:
‘Import task queue max size is 32, currently there are 32 tasks is pending. Not able to execute this request with 1 tasks.’

### Steps To Reproduce

```markdown
1.prepare more than 10 json files
2.bulk load multiple files repeatedly
```

### Milvus Log

[rowbasedjsons.zip](https://github.com/milvus-io/milvus/files/8857484/rowbasedjsons.zip)

**Comment by soothing-rain** [comment]
@yongpengli-z Hey we only allow up to 32 pending files. This is expected.

**Comment by yongpengli-z** [comment]
I waited about 30 minutes ，but I could‘t bulk load any files，it always importRequest failed 。
I only restart my server，then bulk load success.

**Comment by yanliang567** [comment]
I doubt that there is something wrong in task queue cleanup. @soothing-rain

**Comment by soothing-rain** [comment]
Interesting. @yhmo can you follow up on this issue?

/unassign
/assign @yhmo

**Comment by yhmo** [comment]
The #17570 fix the problem. The bulkload pending task list max size is 32, if a bulkload operation want to add 5 tasks into the list, but the pending list only has 4 spare positions, the bulkload() interface will return an error status to the client, and the client will throw an exception to user. User can use try/except to catch the exception and retry the operation.

**Comment by yanliang567** [comment]
@yongpengli-z could you please help to verify the fix?

/assign @yongpengli-z 
/unassign

**Comment by yongpengli-z** [comment]
actual reason：when the task is not completed before collection dropped ,the task will always pending.
this bug
