### ISSUE TITLE
[Bug]: Load the collection, the number of loaded entities is twice the total

### ISSUE THREAD

**Issue by StevenSama** [milvus-io/milvus#17429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-dev（docker pull milvusdb/milvus-dev:master-20220602-48cf63a2）
- Deployment mode(standalone or cluster):standalone 
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 
- OS(Ubuntu or CentOS): Ubuntu 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Load the collection, the number of loaded entities is twice the total

### Expected Behavior

the number of loaded entities is equal to the total

### Steps To Reproduce

```markdown
load collection
```

**Comment by yanliang567** [comment]
@StevenSama how do you know the number of loaded entities? Did you load the collection with memory replicas? Also could you please use this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @StevenSama 
/unassign

**Comment by StevenSama** [comment]
> @StevenSama how do you know the number of loaded entities? Did you load the collection with memory replicas? Also could you please use this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
> 
> /assign @StevenSama /unassign

milvus_cli > connect -h 10.164.1.63
Connect Milvus successfully.
+-------+-------------+
| Host  | 10.164.1.63 |
| Port  |    19530    |
| Alias |   default   |
+-------+-------------+
milvus_cli > list collections
+----+-------------------+--------------------------+
|    | Collection Name   | Entities(Loaded/Total)   |
+====+===================+==========================+
|  0 | test_db           | 446188/223094            |
+----+-------------------+--------------------------+
milvus_cli >

**Comment by StevenSama** [comment]
> > @StevenSama how do you know the number of loaded entities? Did you load the collection with memory replicas? Also could you please use this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
> > /assign @StevenSama /unassign
> 
> milvus_cli > connect -h 10.164.1.63 Connect Milvus successfully. +-------+-------------+ | Host | 10.164.1.63 | | Port | 19530 | | Alias | default | +-------+-------------+ milvus_cli > list collections +----+-------------------+--------------------------+ | | Collection Name | Entities(Loaded/Total) | +====+===================+==========================+ | 0 | test_db | 446188/223094 | +----+-------------------+--------------------------+ milvus_cli >

@yanliang567 Use this image to load must appear

**Comment by yanliang567** [comment]
@shanghaikid could you please help to check whether it is a cli issue?

/assign @shanghaikid 
/unassign

**Comment by StevenSama** [comment]
package milvus;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.UnsupportedEncodingException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.LinkedBlockingDeque;
import java.util.concurrent.TimeUnit;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONArray;

import io.milvus.client.MilvusServiceClient;
import io.milvus.grpc.DataType;
import io.milvus.grpc.MutationResult;
import io.milvus.grpc.QueryResults;
import io.milvus.grpc.SearchResults;
import io.milvus.param.ConnectParam;
import io.milvus.param.IndexType;
import io.milvus.param.MetricType;
import io.milvus.param.R;
import io.milvus.param.collection.CreateCollectionParam;
import io.milvus.param.collection.DropCollectionParam;
import io.milvus.param.collection.FieldType;
import io.milvus.param.collection.LoadCollectionParam;
import io.milvus.param.dml.DeleteParam;
import io.milvus.param.dml.InsertParam;
import io.milvus.param.dml.QueryParam;
import io.milvus.param.dml.SearchParam;
import io.milvus.param.index.CreateIndexParam;

public class MyMilvus {
private String collectionName;
int dim = 768;
int nb = 100000;
String host = "10.164.1.55";
int port = 19530;
boolean isLoadDone = false;
static LinkedBlockingDeque<Map<String, List>> queue = new LinkedBlockingDeque<Map<String, List>>(
10000);

public MyMilvus(String collectionName) {
	this.collectionName = collectionName;
}

private void insert(MilvusServiceClient milvusClient, int nb) {
	Random ran = new Random();
	List<Long> ids_values = new ArrayList<>();
	List<List<Float>> float_vec_values = new ArrayList<>();
	for (long i = 0L; i < nb; ++i) {
		ids_values.add(i);
		List<Float> vector = new ArrayList<>();
		for (int k = 0; k < dim; ++k) {
			vector.add(ran.nextFloat());
		}
		float_vec_values.add(vector);
	}

	List<InsertParam.Field> fields = new ArrayList<>();
	fields.add(new InsertParam.Field("id", DataType.Int64, ids_values));
	fields.add(new InsertParam.Field("embedding", DataType.FloatVector, float_vec_values));

	InsertParam insertParam = InsertParam.newBuilder().withCollectionName(collectionName).withFields(fields)
			.build();
	R<MutationResult> rs = milvusClient.insert(insertParam);
	System.out.println(rs);
}

private void loadDbFromFile(MilvusServiceClient milvusClient, String filePath) {

	List<Long> ids_values = new ArrayList<>();
	List<List<Float>> float_vec_values = new ArrayList<>();
	try {
		InputStreamReader reader = new InputStreamReader(new FileInputStream(filePath), "UTF-8");
		BufferedReader bufferedReader = new BufferedReader(reader);
		String lineTxt = null;
		while ((lineTxt = bufferedReader.readLine()) != null) {
			String[] arr = lineTxt.split(" ", 2);
			try {
				Long id = Long.valueOf(arr[0]);
				ids_values.add(id);
				JSONArray jarr = JSONArray.parseArray(arr[1]);
				List<Float> vector = new ArrayList<Float>();
				for (Object o : jarr) {
					BigDecimal b = (BigDecimal) o;
					vector.add(b.floatValue());
				}
				float_vec_values.add(vector);

				if (ids_values.size() > 10000) {
					List<InsertParam.Field> fields = new ArrayList<>();
					fields.add(new InsertParam.Field("id", DataType.Int64, ids_values));
					fields.add(new InsertParam.Field("embedding", DataType.FloatVector, float_vec_values));

					InsertParam insertParam = InsertParam.newBuilder().withCollectionName(collectionName)
							.withFields(fields).build();
					R<MutationResult> rs = milvusClient.insert(insertParam);
					ids_values.clear();
					float_vec_values.clear();
                                        return;
				}
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
				System.out.println(arr[1]);
			}
		}
		reader.close();
		if (ids_values.size() > 0) {
			List<InsertParam.Field> fields = new ArrayList<>();
			fields.add(new InsertParam.Field("id", DataType.Int64, ids_values));
			fields.add(new InsertParam.Field("embedding", DataType.FloatVector, float_vec_values));

			InsertParam insertParam = InsertParam.newBuilder().withCollectionName(collectionName).withFields(fields)
					.build();
			R<MutationResult> rs = milvusClient.insert(insertParam);
			ids_values.clear();
			float_vec_values.clear();
		}
	} catch (IOException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}

}
private void drop(MilvusServiceClient milvusClient, String collectionName) {
	milvusClient.dropCollection(DropCollectionParam.newBuilder().withCollectionName(collectionName).build());
}

private void create(MilvusServiceClient milvusClient, String collectionName) {
	FieldType fieldType1 = FieldType.newBuilder().withName("id").withDataType(DataType.Int64).withPrimaryKey(true)
			.withAutoID(false).build();
	FieldType fieldType2 = FieldType.newBuilder().withName("embedding").withDataType(DataType.FloatVector)
			.withDimension(dim).build();
	CreateCollectionParam createCollectionReq = CreateCollectionParam.newBuilder()
			.withCollectionName(collectionName).withDescription(collectionName).withShardsNum(2)
			.addFieldType(fieldType1).addFieldType(fieldType2).build();
	milvusClient.createCollection(createCollectionReq);

}

private void buildIndex(MilvusServiceClient milvusClient, String collectionName) {
	final IndexType INDEX_TYPE = IndexType.IVF_SQ8; // IndexType
	final String INDEX_PARAM = "{\"nlist\":256}"; // ExtraParam
	milvusClient.createIndex(CreateIndexParam.newBuilder().withCollectionName(collectionName)
			.withFieldName("embedding").withIndexType(INDEX_TYPE).withMetricType(MetricType.IP)
			.withExtraParam(INDEX_PARAM).withSyncMode(Boolean.FALSE).build());
}

private void load(MilvusServiceClient milvusClient) {
	milvusClient.loadCollection(LoadCollectionParam.newBuilder().withCollectionName(collectionName).build());
}

public static void main(String[] args) {
	String collectionName = "test_db";

	MyMilvus myMilvus = new MyMilvus(collectionName);
	System.out.println("hello milvus");
	final MilvusServiceClient milvusClient = new MilvusServiceClient(
			ConnectParam.newBuilder().withHost(myMilvus.host).withPort(myMilvus.port).build());

	myMilvus.drop(milvusClient, collectionName);
	myMilvus.create(milvusClient, collectionName);
	myMilvus.buildIndex(milvusClient, collectionName);
	myMilvus.load(milvusClient);
	myMilvus.loadDbFromFile(milvusClient, "./features.txt");
}

**Comment by StevenSama** [comment]
the features.txt link in the code,
https://drive.google.com/file/d/11Hlp6QI4AtoEt5u0cX36npjPm8DB0xZW/view?usp=sharing

**Comment by yanliang567** [comment]
@yongpengli-z could you please help to reproduce this with master build?

/assign @yongpengli-z 
/unassign

**Comment by yongpengli-z** [comment]
I verified by your code and file. But my result is OK。I used querySegmentInfo find the num_rows is 2130904.
The result search by  milvus_cli is 2130904.
![5C34gxrxhu](https://user-images.githubusercontent.com/103410837/174552101-3a4938ff-e7ea-4a90-a160-ced6c79eaad2.jpg)
![img_v2_6683ebfd-9200-4d96-9e6e-c2f2c43ca0cg](https://user-images.githubusercontent.com/103410837/174552134-79318edf-eff5-438d-8bc4-c71b4e3150e1.jpg)

**Comment by yongpengli-z** [comment]
Milvus version:master-dev（milvusdb/milvus-dev:master-20220602-48cf63a2）
milvus-sdk-java:2.0.4
