### ISSUE TITLE
[Bug]: Create index failed with error message `message=DescribeSegments failed: segment not found` after Milvus recovered from proxy pod kill chaos

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#17460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220608-6d078ebe
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.1.0.dev69
- OS(Ubuntu or CentOS):  
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

create index failed when running `verify_all_collections.py` after chaos
```
RPC error: [wait_for_creating_index], <MilvusException: (code=1, message=DescribeSegments failed: segment not found, collection: 433773350997458945, segment: 433773359922675714)>, <Time:{'RPC start': '2022-06-08 18:54:04.610897', 'RPC error': '2022-06-08 18:54:05.196288'}>
RPC error: [create_index], <MilvusException: (code=1, message=DescribeSegments failed: segment not found, collection: 433773350997458945, segment: 433773359922675714)>, <Time:{'RPC start': '2022-06-08 18:54:03.914594', 'RPC error': '2022-06-08 18:54:05.196354'}>
```

### Expected Behavior

all test cases passed 

### Steps To Reproduce

```markdown
see https://github.com/milvus-io/milvus/runs/6799774364?check_suite_focus=true
```

### Milvus Log

failed job: https://github.com/milvus-io/milvus/runs/6799774364?check_suite_focus=true

log: https://github.com/milvus-io/milvus/suites/6850170494/artifacts/264442562

**Comment by xiaocai2333** [comment]
segment is compacted.

getIndexState logic:
1. get segment IDs
2. get buildID by segmentID

compaction happens between 1 and 2, so in step 2 rootcoord find segment not exist.

proxy log
```
[2022/06/08 18:54:05.117 +00:00] [DEBUG] [impl.go:2078] ["GetIndexState received"] [traceID=6a0f858e9842a34b] [role=proxy] [db=] [collection=Checker__WarrnhnM] [field=float_vector] ["index name"=_default_idx]
[2022/06/08 18:54:05.128 +00:00] [DEBUG] [id.go:140] ["IDAllocator pickCanDoFunc"] [need=1] [total=172786] [remainReqCnt=0]
[2022/06/08 18:54:05.128 +00:00] [DEBUG] [impl.go:2109] ["GetIndexState enqueued"] [traceID=6a0f858e9842a34b] [role=proxy] [MsgID=433773444662061647] [BeginTs=433773463496818689] [EndTs=433773463496818689] [db=] [collection=Checker__WarrnhnM] [field=float_vector] ["index name"=_default_idx]
[2022/06/08 18:54:05.194 +00:00] [ERROR] [task_scheduler.go:468] ["Failed to execute task: DescribeSegments failed: segment not found, collection: 433773350997458945, segment: **433773359922675714**"] [traceID=6a0f858e9842a34b] [stack="github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:468\ngithub.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:494"]
[2022/06/08 18:54:05.194 +00:00] [WARN] [impl.go:2122] ["GetIndexState failed to WaitToFinish"] [error="DescribeSegments failed: segment not found, collection: 433773350997458945, segment: 433773359922675714"] [traceID=6a0f858e9842a34b] [role=proxy] [MsgID=433773444662061647] [BeginTs=433773463496818689] [EndTs=433773463496818689] [db=] [collection=Checker__WarrnhnM] [field=float_vector] ["index name"=_default_idx]

```

datanode log
```
[2022/06/08 18:54:05.190 +00:00] [INFO] [segment_replica.go:723] ["merge flushed segments"] [planID=433773463130341378] ["compacted To segmentID"=433773463130341380] ["compacted From segmentIDs"="[433773359164030977,433773363173523458,433773358352433154,433773362479628290,433773361653612546,433773360802955265,**433773359922675714**,433773357563904004,433773351168901121,433773462434349058]"] ["partition ID"=433773350997458946] ["channel name"=by-dev-rootcoord-dml_7_433773350997458945v1]
```

**Comment by xiaofan-luan** [comment]
> segment is compacted.
> 
> getIndexState logic:
> 
> 1. get segment IDs
> 2. get buildID by segmentID
> 
> compaction happens between 1 and 2, so in step 2 rootcoord find segment not exist.
> 
> proxy log `[2022/06/08 18:54:05.117 +00:00] [DEBUG] [impl.go:2078] ["GetIndexState received"] [traceID=6a0f858e9842a34b] [role=proxy] [db=] [collection=Checker__WarrnhnM] [field=float_vector] ["index name"=_default_idx] [2022/06/08 18:54:05.128 +00:00] [DEBUG] [id.go:140] ["IDAllocator pickCanDoFunc"] [need=1] [total=172786] [remainReqCnt=0] [2022/06/08 18:54:05.128 +00:00] [DEBUG] [impl.go:2109] ["GetIndexState enqueued"] [traceID=6a0f858e9842a34b] [role=proxy] [MsgID=433773444662061647] [BeginTs=433773463496818689] [EndTs=433773463496818689] [db=] [collection=Checker__WarrnhnM] [field=float_vector] ["index name"=_default_idx] [2022/06/08 18:54:05.194 +00:00] [ERROR] [task_scheduler.go:468] ["Failed to execute task: DescribeSegments failed: segment not found, collection: 433773350997458945, segment: 433773359922675714"] [traceID=6a0f858e9842a34b] [stack="github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:468\ngithub.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:494"] [2022/06/08 18:54:05.194 +00:00] [WARN] [impl.go:2122] ["GetIndexState failed to WaitToFinish"] [error="DescribeSegments failed: segment not found, collection: 433773350997458945, segment: 433773359922675714"] [traceID=6a0f858e9842a34b] [role=proxy] [MsgID=433773444662061647] [BeginTs=433773463496818689] [EndTs=433773463496818689] [db=] [collection=Checker__WarrnhnM] [field=float_vector] ["index name"=_default_idx]`
> 
> datanode log
> 
> ```
> [2022/06/08 18:54:05.190 +00:00] [INFO] [segment_replica.go:723] ["merge flushed segments"] [planID=433773463130341378] ["compacted To segmentID"=433773463130341380] ["compacted From segmentIDs"="[433773359164030977,433773363173523458,433773358352433154,433773362479628290,433773361653612546,433773360802955265,**433773359922675714**,433773357563904004,433773351168901121,433773462434349058]"] ["partition ID"=433773350997458946] ["channel name"=by-dev-rootcoord-dml_7_433773350997458945v1]
> ```

Any plan to fix it?

**Comment by xiaocai2333** [comment]
@xiaofan-luan  
I have a simple plan:
1. when the segment is referenced, lock the segment
2. The segment cannot be compacted while there is a lock on it.
3. In order to prevent too many components to  hold locks, a new interface `GetIndexState` is added for RootCoord, and RootCoord  gets the index state and hold locks. The proxy only needs to know if the result is a success or a failure.

**Comment by yanliang567** [comment]
> @xiaofan-luan I have a simple plan:
> 
>     1. when the segment is referenced, lock the segment
> 
>     2. The segment cannot be compacted while there is a lock on it.
> 
>     3. In order to prevent too many components to  hold locks, a new interface `GetIndexState` is added for RootCoord, and RootCoord  gets the index state and hold locks. The proxy only needs to know if the result is a success or a failure.

what about if rootcoord failed in this plan?

**Comment by xiaocai2333** [comment]
> > @xiaofan-luan I have a simple plan:
> > ```
> > 1. when the segment is referenced, lock the segment
> > 
> > 2. The segment cannot be compacted while there is a lock on it.
> > 
> > 3. In order to prevent too many components to  hold locks, a new interface `GetIndexState` is added for RootCoord, and RootCoord  gets the index state and hold locks. The proxy only needs to know if the result is a success or a failure.
> > ```
> 
> what about if rootcoord failed in this plan?

DataCoord will monitor whether RootCoord is offline. If it is offline, DataCoord will release the lock added by RootCoord.

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan I have a simple plan:
> 
> 1. when the segment is referenced, lock the segment
> 2. The segment cannot be compacted while there is a lock on it.
> 3. In order to prevent too many components to  hold locks, a new interface `GetIndexState` is added for RootCoord, and RootCoord  gets the index state and hold locks. The proxy only needs to know if the result is a success or a failure.

I'm not sure adding lock for getIndexState is a good plan because no one ganruatee this lock will be released

**Comment by xiaofan-luan** [comment]
Why this lock is not  holded by indexcoord? When index build done the lock is released

**Comment by xiaocai2333** [comment]
> Why this lock is not holded by indexcoord? When index build done the lock is released

If the lock is held by IndexCoord, the atomicity of getIndexState on the Proxy node cannot be guaranteed. This problem still occurs.

**Comment by zhuwenxing** [comment]
This happened again after querycoord pod kill.
failed job: https://github.com/milvus-io/milvus/runs/6906028666?check_suite_focus=true
log: https://github.com/milvus-io/milvus/suites/6950181067/artifacts/271031510 (in dir `data-consist-test`)

**Comment by xiaocai2333** [comment]
pr #17529 will fix it.

**Comment by xiaocai2333** [comment]
pr #17529 is merged, please check it.
/unassign
/assign @zhuwenxing
