### ISSUE TITLE
[Bug]:   A log error is reported during query

### ISSUE THREAD

**Issue by xuysh2022** [milvus-io/milvus#17493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.2
- Deployment mode(standalone or cluster):单机版
- SDK version(e.g. pymilvus v2.0.0rc2):java
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 16/32
- GPU: no
- Others: w
```

### Current Behavior

2022-06-10 17:48:59 io.milvus.client.AbstractMilvusGrpcClient logError 
ERROR: SearchRequest failed:
QueryNode search fail, reason [UnexpectedError] Assert "(field_meta.get_sizeof() == element.line_sizeof_)" at /root/rpm-build/milvus-202-build/milvus/internal/core/src/query/Plan.cpp:41

: id 433808879651651634

### Expected Behavior

查询的时候出现milvus日志错误，怀疑是不是跟我服务器的权限有关，很多目录都没有写的权限，可能是日志输出的时候无权限导致失败，但是我不知道日志写到哪里，无法验证。

### Steps To Reproduce

```markdown
无
```

### Milvus Log

无

### Anything else?

package com.ctid.business.api.controller;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import io.milvus.Response.SearchResultsWrapper;
import io.milvus.client.MilvusServiceClient;
import io.milvus.grpc.DataType;
import io.milvus.grpc.SearchResults;
import io.milvus.param.ConnectParam;
import io.milvus.param.MetricType;
import io.milvus.param.R;
import io.milvus.param.collection.CreateCollectionParam;
import io.milvus.param.collection.FieldType;
import io.milvus.param.collection.HasCollectionParam;
import io.milvus.param.collection.LoadCollectionParam;
import io.milvus.param.dml.InsertParam;
import io.milvus.param.dml.SearchParam;

@Controller
@RequestMapping(value="/mil")
public class MilvusController {
	@RequestMapping(value = "/add", produces = "application/json;charset=UTF-8")
	public @ResponseBody String add(@RequestParam String vec) {
		try {
			
			final MilvusServiceClient milvusClient = new MilvusServiceClient(
					ConnectParam.newBuilder()
							.withHost("localhost")
							.withPort(19530)
							.build());
			
			
			R<Boolean> respHasCollection = milvusClient.hasCollection(
			        HasCollectionParam.newBuilder()
			                .withCollectionName("questions")
			                .build());
			if (!respHasCollection.getData()) {//表不存在
				System.out.println("questions表不存在，开始创建questions表");
				FieldType fieldType1 = FieldType.newBuilder()
				        .withName("ques_id")
				        .withDataType(DataType.Int64)
				        .withPrimaryKey(true)
				        .withAutoID(false)
				        .build();
				FieldType fieldType2 = FieldType.newBuilder()
				        .withName("ques_intro")
				        .withDataType(DataType.FloatVector)
				        .withDimension(768)
				        .build();
				
				CreateCollectionParam createCollectionReq = CreateCollectionParam.newBuilder()
				        .withCollectionName("questions")
				        .withDescription("question vec desc")
				        .withShardsNum(2)
				        .addFieldType(fieldType1)
				        .addFieldType(fieldType2)
				        .build();
				milvusClient.createCollection(createCollectionReq);
			}else {
				System.out.println("questions表已经存在");
			}
			
			FileReader fis = new FileReader("/home/appmanager/vec.txt");
			BufferedReader bis = new BufferedReader(fis);
			 String ques="";
			Long i = 1l;
            while((ques = bis.readLine())!=null) {
            	List<Long> id_array = new ArrayList<>();
            	id_array.add(i);
            	i++;
            	List<Float> ques_intro_array = new ArrayList<>();
            	String[] arr_ques = ques.split(",");
            	for(String str : arr_ques) {
            		ques_intro_array.add(Float.valueOf(str));
            	}
            	
            	List<List<Float>> list = new ArrayList<>();
            	list.add(ques_intro_array);
            	
            	List<InsertParam.Field> fields = new ArrayList<>();
            	fields.add(new InsertParam.Field("ques_id", DataType.Int64, id_array));
            	fields.add(new InsertParam.Field("ques_intro", DataType.FloatVector, list));

            	InsertParam insertParam = InsertParam.newBuilder()
            			.withCollectionName("questions")
						/* .withPartitionName("novel") */
            			.withFields(fields)
            			.build();
            	milvusClient.insert(insertParam);
            }
            milvusClient.close();
            fis.close();
            bis.close();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			return  "{\"statusCode\":\"203\",  \"message\":\"操作失败\"}";
		}
		
		return "{\"statusCode\":\"200\",  \"message\":\"操作成功\"}";
		
	}
	
	
	
	
	@RequestMapping(value = "/query", produces = "application/json;charset=UTF-8")
	public @ResponseBody String query(@RequestParam String quess) {
		try {
			final MilvusServiceClient milvusClient = new MilvusServiceClient(
					ConnectParam.newBuilder()
							.withHost("localhost")
							.withPort(19530)
							.build());
			
			
			milvusClient.loadCollection(
			        LoadCollectionParam.newBuilder()
			                .withCollectionName("questions")
			                .build());
			
			List<String> list = new ArrayList<>();
			list.add("ques_id");
			
			FileReader fis = new FileReader("/home/appmanager/vecquery.txt");
			BufferedReader bis = new BufferedReader(fis);
			String ques=bis.readLine();
			
			if(ques != null && !"".equals(ques)) {
			
			
				List<Float> ques_intro_array = new ArrayList<>();
	        	String[] arr_ques = ques.split(",");
	        	for(String str : arr_ques) {
	        		ques_intro_array.add(Float.valueOf(str));
	        	}
				
	        	List<List<Float>> ls = new ArrayList<>();
	        	ls.add(ques_intro_array);
				SearchParam searchParam = SearchParam.newBuilder()
						.withCollectionName("questions")
						/* .withMetricType(MetricType.L2) */
						.withOutFields(list)
						.withTopK(1)
						.withVectors(ls)
						.withVectorFieldName("ques_intro")
						/* .withParams("{\"nprobe\":10}") */
						.build();
				R<SearchResults> respSearch = milvusClient.search(searchParam);
				
				SearchResultsWrapper wrapperSearch = new SearchResultsWrapper(respSearch.getData().getResults());
				
				return "{\"statusCode\":\"200\",  \"message\":\"" + wrapperSearch.getIDScore(0).toString() +"##########" + wrapperSearch.getFieldData("ques_id", 0).toString() +"\"}";
			}else {
				return "{\"statusCode\":\"203\",  \"message\":\"文件异常\"}";
			}
			}catch(Exception e) {
			e.printStackTrace();
		}
		return "{\"statusCode\":\"201\",  \"message\":\"操作失败\"}";
	}
}

**Comment by xuysh2022** [comment]
[vec.txt](https://github.com/milvus-io/milvus/files/8878145/vec.txt)
[vecquery.txt](https://github.com/milvus-io/milvus/files/8878147/vecquery.txt)

**Comment by xuysh2022** [comment]
submit milvus logs
[milvus-all-log.log](https://github.com/milvus-io/milvus/files/8887306/milvus-all-log.log)

**Comment by yanliang567** [comment]
@longjiquan sounds like a cgo assert error, could you please help to take a look?

/assign @longjiquan 
/unassign @xuysh2022

**Comment by longjiquan** [comment]
@xuysh2022 hello, I guess you passed the vectors with wrong dimension. Of course, this error log is not very human-readable, I'll fix this soon.

**Comment by longjiquan** [comment]
@xuysh2022 Could you check if the dimension of your every vectors in `/home/appmanager/vecquery.txt` is equal to `768`?

**Comment by xuysh2022** [comment]
My problem has been solved. It is really the wrong dimension of the vector
