### ISSUE TITLE
Revise mysql meta backend description

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#1750]
## Report incorrect documentation

**Location of incorrect documentation**
https://www.milvus.io/cn/docs/v0.7.0/reference/data_manage.md

**Describe the problems or issues found in the documentation**
"退出 MySQL 客户端, 修改 server_config.yaml 文件的 backend_url 参数，注意密码，端口以及 database 名称要和以上几步的设置一致。"
`backend_url: mysql://root:123456@127.0.0.1:3306/milvus`
改为
“退出 MySQL 客户端, 修改 server_config.yaml 文件的 backend_url 参数，使用MySQL服务所在的主机IP作为地址，注意密码，端口以及 database 名称要和以上几步的设置一致。”
`backend_url: mysql://root:123456@<mysql host ip>:3306/milvus`

**Comment by yamasite** [comment]
Fixed in https://github.com/milvus-io/docs/pull/444

**Comment by yamasite** [comment]
@yhmo More fix in https://github.com/milvus-io/docs/pull/454
