### ISSUE TITLE
[Bug]: CPU usage & Search latency too high after Milvus 1.1.0 pod restart

### ISSUE THREAD

**Issue by yuliu-eric** [milvus-io/milvus#17512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 1.1.0
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 1.1.0
- OS(Ubuntu or CentOS): AWS Linux
- CPU/Memory: Happens across different settings
- GPU: N/A
- Others:
```

### Current Behavior

We have a few milvus use cases running on different hosts. CPU usage (before: <20%, after: >80%) and Search latency (before: <30ms, after: > 200ms to a few seconds) become too high after the pod restart, and it takes at least several hours to recover.

Access pattern: periodically insert and search every tens of minus or every few hours.

Collection data size: MB ~ GB

### Expected Behavior

Expect stable CPUS and search latency as before the pod restart.

**Comment by yanliang567** [comment]
/assign @yhmo 
please take a look at this 1.x issue.

/assign

**Comment by yhmo** [comment]
From the log, it seems 90% of time consume is wasted in the bottom search engine, in vector similarity computation. Looks like the machine CPU is busy on something.

**Comment by yuliu-eric** [comment]
Thank you for the update! Do you need anything else for further investigation?

**Comment by yuliu-eric** [comment]
Per this thread (https://github.com/milvus-io/milvus/issues/4208#issuecomment-725765972), what values do you suggest to set for `--cpuset-cpus` and `--cpuset-mems`, given the following instance config

```
lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    2
Core(s) per socket:    16
Socket(s):             1
NUMA node(s):          2
Vendor ID:             AuthenticAMD
CPU family:            23
Model:                 1
Model name:            AMD EPYC 7571
Stepping:              2
CPU MHz:               2542.232
BogoMIPS:              4399.98
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             64K
L2 cache:              512K
L3 cache:              8192K
NUMA node0 CPU(s):     0-7,16-23
NUMA node1 CPU(s):     8-15,24-31
```

**Comment by yuliu-eric** [comment]
Trying to set above ENV in values.yaml and upgrade through helm, but the setting didn't take effect, no `OMP_NUM_THREADS` or `cpuset-xxx` found in printenv on the pod. 

```
  service:
    type: LoadBalancer
    port: 19530
    ...
  extraEnv:
    - name: OMP_NUM_THREADS
      value: "4"
    - name: cpuset-cpus
      value: "0-3"
    - name: cpuset-mems
      value: "0"
```

Would you please share the examples how to set those ENVs while using helm?

**Comment by yhmo** [comment]
--cpuset-cpus="0,1,2,3,4,5,6,7,16,17,18,19,20,21,22,23"
--cpuset-mems="0"

**Comment by yhmo** [comment]
By this configuration, the container only use 16 CPU cores.

**Comment by yuliu-eric** [comment]
Got it, thank you for the explanations! 

But I guess the [above settings](https://github.com/milvus-io/milvus/issues/17512#issuecomment-1155038338) of `cpuset` under `extraEnv` won't work right?

**Comment by yhmo** [comment]
> Got it, thank you for the explanations!
> 
> But I guess the [above settings](https://github.com/milvus-io/milvus/issues/17512#issuecomment-1155038338) of `cpuset` under `extraEnv` won't work right?

Right, I think it can't work. The "cpuset-cpus" is docker parameter. You need to learn the kubernetes cpu manager policy:
https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/

**Comment by yuliu-eric** [comment]
Got it, thank you for confirming!
