### ISSUE TITLE
[Bug]: Milvus crashed after deleting data and querying

### ISSUE THREAD

**Issue by Modilay** [milvus-io/milvus#17517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster): standalone 
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.0.0
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

After deleting the data, query is used, and then an exception occurs, causing the docker to be closed. Then the collection cannot be used normally after restart. Both query and select will cause errors

### Milvus Log

以下是报错的日志
[output.log](https://github.com/milvus-io/milvus/files/8888401/output.log)

**Comment by yanliang567** [comment]
@Modilay  thank you for the issue. Could you please share the milvus version you are running? If possible, please help to reproduce it with latest master build and use this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @Modilay 
/unassign
