### ISSUE TITLE
Add api GetVectorsByID

### ISSUE THREAD

**Issue by zhangjuchang** [milvus-io/milvus#1752]
**Is your feature request related to a problem? Please describe.**
我们用于检索的数据都记录在了milvus中，每次批量检索时，现在只能一个个通过id获取vector，并且并行效率不高。
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by JinHai-CN** [comment]
This API is already planned.

**Comment by yhmo** [comment]
```
message VectorsIdentity {
    string collection_name = 1;
    repeated int64 id_array = 2;
}
message RowRecord {
    repeated float float_data = 1;             //float vector data
    bytes binary_data = 2;                      //binary vector data
}
message VectorsData {
    Status status = 1;
    repeated RowRecord vectors_data = 2;
}

GetVectorsByID(VectorsIdentity) returns (VectorsData)
```

Some vectors could not be found, for such case, the VectorsData may contains some empty RowRecord

**Comment by yhmo** [comment]
Implemented in pr2056
