### ISSUE TITLE
[Enhancement]: Update Milvus Roadmap

### ISSUE THREAD

**Issue by yovelcohen** [milvus-io/milvus#17532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

the roadmap described at: 
[Milvus Roadmap](https://milvus.io/docs/roadmap.md )
is not updated at all. 

### Why is this needed?

since 2.1 is a very waited version, an updated roadmap with realistic time assessments would be great.

**Comment by xiaofan-luan** [comment]
Thanks for following up,
We now put our mile stone at, you could check details about 2.1 and 2.2
https://wiki.lfaidata.foundation/display/MIL/Milvus+Home

**Comment by yovelcohen** [comment]
@xiaofan-luan Thanks, that's great, but I think the roadmap on milvus.io should still be updated or reference to this page since it might confuse others as well :)
