### ISSUE TITLE
[Bug]: Growing segment can't be cleaned from querynode memory

### ISSUE THREAD

**Issue by xige-16** [milvus-io/milvus#17566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

If querynode receive a growing segment1, and datanode has flushed segment1, then querycoord will handoff a sealed segment 1 to querynode. After that, querynode should auto remove growing segment 1 from memory. 

But now the growing segment is not cleaned up

**Comment by congqixia** [comment]
@xige-16 shall we could is issue?

**Comment by xiaofan-luan** [comment]
close due to the fix of 17609
