### ISSUE TITLE
[Enhancement]: Mov all index related meta from rootcoord to index

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#17578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

As discussed with @aakejiang 
There is no reason we maintain segID2IndexMeta in rootcoord.
All index related meta should be handled in indexcoord

**Comment by jaime0815** [comment]
I propose all index meta maintenance move into roocoord, all index services to keep stateless as far as possible,  it benefits metadata to unified management.
