### ISSUE TITLE
[Bug]: Search took forever after compaction on etcd and restart datanode and datacoord

### ISSUE THREAD

**Issue by siwenyang** [milvus-io/milvus#17583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.0.1
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): v2.0.1
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: deployed on aws ec2s with terraform and anisble
```

### Current Behavior

1. data_coord node and data node are shut down since etcd error: [error="etcdserver: mvcc: database space exceeded"]
2. manually compaction in etcd, recover etcd to healthy stautsd, with this instruction: https://etcd.io/docs/v3.2/op-guide/maintenance/
3. restart data_coord and data node by docker-compose down && docker-compose up -d
4. check all modules in cluster is on
5. collection.load() and try search with collection.search(), but wait search forever

### Steps To Reproduce

```markdown
1. data_coord node and data node are shut down since etcd error: [error="etcdserver: mvcc: database space exceeded"]
2. manually compaction in etcd, recover etcd to healthy stautsd, with this instruction: https://etcd.io/docs/v3.2/op-guide/maintenance/
3. restart data_coord and data node by docker-compose down && docker-compose up -d
4. check all modules in cluster is on
5. collection.load() and try search with collection.search(), but wait search forever
```

### Milvus Log

[siwen_log.log](https://github.com/milvus-io/milvus/files/8915607/siwen_log.log)

**Comment by siwenyang** [comment]
So before etcd error, my cluster had 2 collections. After mannually compaction on etcd and restart data coord and data node. Search on old collections took forever. However, if I rebuild the index of the collections, search would work. My further question is: Will compaction on etcd and restart data coord and data node cause old collection index not work? Thank you for help.

**Comment by yanliang567** [comment]
@xige-16 is this a known issue to us?

/assign @xige-16 
/unassign

**Comment by xige-16** [comment]
The dmlChannel position of the segment after compaction has not been updated, which causes querynode to watch the earlier positon of dmchannel during load, and the search recovery is slow.

**Comment by xige-16** [comment]
> So before etcd error, my cluster had 2 collections. After mannually compaction on etcd and restart data coord and data node. Search on old collections took forever. However, if I rebuild the index of the collections, search would work. My further question is: Will compaction on etcd and restart data coord and data node cause old collection index not work? Thank you for help.

It should have nothing to do with create index. After restarting, if you wait for a while and then query, the query should also work normally.

**Comment by xige-16** [comment]
pr #17554 should has fixed the issue
