### ISSUE TITLE
[Bug]: <ConnectionNotExistException: (code=0, message=should create connect first.)>

### ISSUE THREAD

**Issue by gctian** [milvus-io/milvus#17592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.2
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus V2.0.2
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others: python3.6.8
```

### Current Behavior

execute utility.list_collections() in jupyter，I can create collection, create index  and search, but `utility.list_collections()` error，`collection = Collection("book")` also has this error.

ConnectionNotExistException               Traceback (most recent call last)
<ipython-input-66-5acf1c145b91> in <module>
     21 ## 列出目前所有 collection
     22 from pymilvus import utility
---> 23 utility.list_collections()
     24 '''
     25 1、创建连接

~/.virtualenvs/NLP/lib/python3.6/site-packages/pymilvus/orm/utility.py in list_collections(timeout, using)
    429         >>> utility.list_collections()
    430     """
--> 431     return _get_connection(using).list_collections()
    432 
    433 

~/.virtualenvs/NLP/lib/python3.6/site-packages/pymilvus/orm/utility.py in _get_connection(alias)
    160 
    161 def _get_connection(alias):
--> 162     return connections._fetch_handler(alias)
    163 
    164 

~/.virtualenvs/NLP/lib/python3.6/site-packages/pymilvus/orm/connections.py in _fetch_handler(self, alias)
    243         conn = self._conns.get(alias, None)
    244         if conn is None:
--> 245             raise ConnectionNotExistException(0, ExceptionsMessage.ConnectFirst)
    246 
    247         return conn

ConnectionNotExistException: <ConnectionNotExistException: (code=0, message=should create connect first.)>

### Expected Behavior

list_collections in current cluster

### Milvus Log

---------------------------------------------------------------------------
ConnectionNotExistException               Traceback (most recent call last)
<ipython-input-66-5acf1c145b91> in <module>
     21 ## 列出目前所有 collection
     22 from pymilvus import utility
---> 23 utility.list_collections()
     24 '''
     25 1、创建连接

~/.virtualenvs/NLP/lib/python3.6/site-packages/pymilvus/orm/utility.py in list_collections(timeout, using)
    429         >>> utility.list_collections()
    430     """
--> 431     return _get_connection(using).list_collections()
    432 
    433 

~/.virtualenvs/NLP/lib/python3.6/site-packages/pymilvus/orm/utility.py in _get_connection(alias)
    160 
    161 def _get_connection(alias):
--> 162     return connections._fetch_handler(alias)
    163 
    164 

~/.virtualenvs/NLP/lib/python3.6/site-packages/pymilvus/orm/connections.py in _fetch_handler(self, alias)
    243         conn = self._conns.get(alias, None)
    244         if conn is None:
--> 245             raise ConnectionNotExistException(0, ExceptionsMessage.ConnectFirst)
    246 
    247         return conn

ConnectionNotExistException: <ConnectionNotExistException: (code=0, message=should create connect first.)>

**Comment by yanliang567** [comment]
@gctian could you please share the repro code here?

/assign @gctian 
/unassign

**Comment by WoodieDudy** [comment]
Fix it by setting connection alias to "default".
Before I had alias="main"
