### ISSUE TITLE
Server is not forbidden to create new partition which tag is "_default"

### ISSUE THREAD

**Issue by BossZou** [milvus-io/milvus#1762]
**Describe the bug**
Currently each collection has a default partition which tag is "_default". However, user still can create a partition with tag "_default" successfully. This behavior is confusing.

```python
>>> client = Milvus()
>>> client.create_collection({"collection_name": "test_default_partition", "dimension": 128})
>>> status = client.create_partition("test_default_partition", "_default")
Status(code=0, message='OK')
```

**Comment by yhmo** [comment]
return error code=SERVER_INVALID_PARTITION_TAG, message="'_default' is built-in partition tag"

**Comment by yhmo** [comment]
fixed in pr 1770
