### ISSUE TITLE
[Enhancement]: $ go get -u github.com/milvus-io/milvus-sdk-go/v2;  Golang SDK fail to install

### ISSUE THREAD

**Issue by houlang** [milvus-io/milvus#17633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

$ go get -u github.com/milvus-io/milvus-sdk-go/v2;  Golang SDK fail to install。

### Why is this needed?

Unable to continue the work

### Anything else?

When will the C++SDK come out? It is better to have C++SDK, save using C++ to drop Golang.

**Comment by congqixia** [comment]
Hi @houlang Thanks for the issue.
Just tested with the command you provided, SDK installed successfully.
```
❯ go get -u github.com/milvus-io/milvus-sdk-go/v2
go: downloading github.com/milvus-io/milvus-sdk-go/v2 v2.0.0
go: downloading github.com/milvus-io/milvus-sdk-go v1.1.1
go get: added github.com/milvus-io/milvus-sdk-go/v2 v2.0.0
```
Some small tips:
- Is goproxy setup properly?
- Do you want to install it inside a project with go mod?
- Do a previous sdk version exist inside you project already?

**Comment by houlang** [comment]
> 



> Hi @houlang Thanks for the issue. Just tested with the command you provided, SDK installed successfully.
> 
> ```
> ❯ go get -u github.com/milvus-io/milvus-sdk-go/v2
> go: downloading github.com/milvus-io/milvus-sdk-go/v2 v2.0.0
> go: downloading github.com/milvus-io/milvus-sdk-go v1.1.1
> go get: added github.com/milvus-io/milvus-sdk-go/v2 v2.0.0
> ```
> 
> Some small tips:
> 
> * Is goproxy setup properly?
> * Do you want to install it inside a project with go mod?
> * Does a previous sdk version exists inside you project already?

Yes, I did. Thank you

**Comment by houlang** [comment]
我是蒋孝乐。已经收到您的来信，我会尽快回复。

**Comment by houlang** [comment]
我是蒋孝乐。已经收到您的来信，我会尽快回复。
