### ISSUE TITLE
[Bug]: segments are missing when dropping vchannel

### ISSUE THREAD

**Issue by aakejiang** [milvus-io/milvus#17636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![6W2NZ9qW50](https://user-images.githubusercontent.com/68629395/174514829-65961a74-2af2-4392-bbff-5a2218a0388b.jpg)

When dropping vchannel, the segments in DropVirtualChannelRequest are not assigned, no other places as well.
This will cause dropped segments will not marked DROPPED in etcd.

**Comment by aakejiang** [comment]
assign @congqixia

**Comment by xiaofan-luan** [comment]
Don't quite understand about this.
Why does drop virtual channel request from datanode to datacoord?
