### ISSUE TITLE
删除集合，只删除了以集合命名的物理文件，分区表的物理文件并没有删除。

### ISSUE THREAD

**Issue by puremilkll** [milvus-io/milvus#1764]
**Describe the bug**
通过restful 删除集合 （集合中已经创建了分区表并且有数据）后，分区表的物理文件未得到删除

**Environment details**
- Milvus version (v0.7)

**Comment by JinHai-CN** [comment]
Have you tried this case with any SDK? Have the same result?

**Comment by puremilkll** [comment]
没尝试过SDK

**Comment by puremilkll** [comment]
> Have you tried this case with any SDK? Have the same result?

没有尝试过SDK

**Comment by del-zhenwu** [comment]
Cannot re-produced with python-sdk with server-version: 0.7.1
```
[root@f916c3ab9ea5 tables]# ll
total 16
drwxr--r-- 3 root root 4096 Mar 27 09:18 1585300736496776000
drwxr--r-- 2 root root 4096 Mar 27 09:18 1585300736507904000
drwxr--r-- 2 root root 4096 Mar 27 09:18 test_O3xzOFuv
drwxr--r-- 2 root root 4096 Mar 27 09:18 test_partition_guIcOhHV
[root@f916c3ab9ea5 tables]# ll
total 12
drwxr--r-- 3 root root 4096 Mar 27 09:18 1585300736496776000
drwxr--r-- 2 root root 4096 Mar 27 09:18 1585300736507904000
drwxr--r-- 2 root root 4096 Mar 27 09:18 test_O3xzOFuv
```
after calling 
```
(Pdb) connect.drop_collection(collection)
Status(code=0, message='Delete collection successfully!')
```

**Comment by yhmo** [comment]
In the server_config.yaml, set deploy_mode = cluster_writable,  in this mode, dropped collection's folder/file will be deleted after 1 hour

**Comment by yhmo** [comment]
This question has already been explained
