### ISSUE TITLE
[Bug]: Drop partition didn't trigger datacoord segment to be dropped

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#17648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Currently, when we call drop partition, we have no way to update segment state to dropped, All the segment is left there and can not be cleaned for ever, this also incur that indexes can not be cleaned.

Drop collection handling is triggered by setting channel to drop mode and notify datacoord by datanode.

We probably want to follow drop collection mechanism to handle drop partition

**Comment by congqixia** [comment]
@xiaofan-luan #18292 shall be a temp fix for this problem. Still need to design drop related procedure in DataCoord

**Comment by xiaofan-luan** [comment]
keep it for 2.2.
