### ISSUE TITLE
[Bug]: storage.Datasorter does not handle vector correctly

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#17660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: eb1f0bc
- Deployment mode(standalone or cluster): both
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When doing `Swap`, datasorter only process the first and second vectors.

### Expected Behavior

DataSorter sort data correctly.

### Anything else?

Related to #17505

**Comment by xiaofan-luan** [comment]
good catch
