### ISSUE TITLE
Clustering vector set

### ISSUE THREAD

**Issue by rose-jinyang** [milvus-io/milvus#1768]
**What is your question?**
Hello
I am a Milvus user.
Thank you for contributing Milvus.
I have a trouble to cluster a vector set with milvus.
How can I cluster vector set with milvus?
If there is any solution, please let me know asap.
Thanks

**Comment by JinHai-CN** [comment]
If you want to know how to use milvus, please refer to: https://milvus.io/docs/v0.7.0/guides/milvus_operation.md

If you want to know more use cases of milvus, please refer to:
https://github.com/milvus-io/bootcamp

**Comment by rose-jinyang** [comment]
Hi, Thanks for your reply.
I know how to use Milvus and already saw that guides and bootcamp source code.
What I want to do is to cluster vectors.
Faiss supports both vector search and clustering to user.
But Milvus supports only vector search.
How can I cluster vectors with Milvus?
If there is any solution, please let me know asap.

**Comment by JinHai-CN** [comment]
Currently, Milvus only provide the vector searching function. In future release, Milvus will provide the preprocessing module like normalisation or clustering.

**Comment by rose-jinyang** [comment]
Thanks for your reply

**Comment by pwichmann** [comment]
Just to refer to this topic again as another user of Milvus -- two years later than the original post:
Does Milvus offer the feature to cluster returned vectors?

For example, if I run this code:
```Python
results = collection.search(
	data=[[0.1, 0.2]], 
	anns_field="book_intro", 
	param=search_params, 
	limit=5000
)
```

It would be amazing if there was an option to have Milvus cluster similar vectors into different groups. In this case, the returned 5000 most similar vectors may be clustered into - let's say - 10 groups.

**Comment by fabmeyer** [comment]
> Just to refer to this topic again as another user of Milvus -- two years later than the original post: Does Milvus offer the feature to cluster returned vectors?
> 
> For example, if I run this code:
> 
> ```python
> results = collection.search(
> 	data=[[0.1, 0.2]], 
> 	anns_field="book_intro", 
> 	param=search_params, 
> 	limit=5000
> )
> ```
> 
> It would be amazing if there was an option to have Milvus cluster similar vectors into different groups. In this case, the returned 5000 most similar vectors may be clustered into - let's say - 10 groups.
> 
> The groups could either be computed across the whole dataset prior to a request. Or after a request has been received and then the grouping is only performed on the result set.

@pwichmann is this available now in Milvus? I need a database to store many keywords as vectors and do clustering over them.

**Comment by xiaofan-luan** [comment]
/assign @liliu-z 

We should seriously think about this

**Comment by xiaofan-luan** [comment]
For open source milvus, being able to cluster 100M data should be good to go.

**Comment by polyyarp** [comment]
Hi, I wonder if the clustering vector set in Milvus is already implemented?
Thank yoiu.

**Comment by xiaofan-luan** [comment]
not yet~
but this is on the roadmap of 3.0
