### ISSUE TITLE
[Bug]:  Milvus's K8S cluster is unavailable

### ISSUE THREAD

**Issue by wziyang** [milvus-io/milvus#17709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.2
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.0.1
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 32c/128g
- GPU: 
- Others:
```

### Current Behavior

I deployed a Milvus cluster with Helm.
*****************
helm install ${MILVUS_CLUSTER_NAME} milvus/milvus --set etcd.replicaCount=3 --set proxy.replicas=3 --set service.type=NodePort --set service.nodePort=${MILVUS_CLUSTER_PORT} --set queryNode.replicas=3 --set indexNode.replicas=3 --set dataNode.replicas=3 --set log.persistence.enabled=true --set log.level=debug
*****************
The main operations for Milvus are insertion and search.
The total data is 10w.
The nodes of the K8S cluster of Milvus often down and restart, and the probability after many times will cause the cluster to be unavailable.
![image](https://user-images.githubusercontent.com/38698650/174981231-a49bbb9c-a301-49de-9b3d-f5351ffbaf46.png)
![image](https://user-images.githubusercontent.com/38698650/174989182-f56f2768-5a80-434d-88a9-d24cab39c3f6.png)

The following is the last time each pod was restarted. After the restart, the cluster is unavailable.
![image](https://user-images.githubusercontent.com/38698650/174983237-8b664f0a-dd7a-4ab4-8111-f15f49fed6e5.png)
![image](https://user-images.githubusercontent.com/38698650/174983472-c8bb1825-fcc8-4a42-bee5-c938fc4c9a20.png)
I can see an exception in the node structure at attu.
Is it caused by the node registration after the ETCD restart？
![image](https://user-images.githubusercontent.com/38698650/174989464-0422b202-cc50-417c-af02-1f01c660d99b.png)

### Expected Behavior

Why does a cluster often go down and how can I recover it.

### Steps To Reproduce

```markdown
If you manually delete 2 or 3 etcd nodes, there is a high probability that the same situation will occur, that is, the cluster is running normally, but the search and insert operations are timeout.

This happens regardless of the amount of data in the cluster, and can be triggered by using the "book" sample in the teaching document.
```

### Milvus Log

[indexnode-17.log](https://github.com/milvus-io/milvus/files/8956084/indexnode-17.log)
[proxy-38.log](https://github.com/milvus-io/milvus/files/8956086/proxy-38.log)
[proxy-51.log](https://github.com/milvus-io/milvus/files/8956087/proxy-51.log)
[querycoord-36.log](https://github.com/milvus-io/milvus/files/8956088/querycoord-36.log)
[querycoord-50.log](https://github.com/milvus-io/milvus/files/8956090/querycoord-50.log)
[querynode-24.log](https://github.com/milvus-io/milvus/files/8956093/querynode-24.log)
[querynode-40.log](https://github.com/milvus-io/milvus/files/8956095/querynode-40.log)
[rootcoord-21.log](https://github.com/milvus-io/milvus/files/8956097/rootcoord-21.log)
[rootcoord-41.log](https://github.com/milvus-io/milvus/files/8956098/rootcoord-41.log)
[datacoord-42.log](https://github.com/milvus-io/milvus/files/8956101/datacoord-42.log)
[datacoord-48.log](https://github.com/milvus-io/milvus/files/8956102/datacoord-48.log)
[datanode-32.log](https://github.com/milvus-io/milvus/files/8956103/datanode-32.log)
[datanode-49.log](https://github.com/milvus-io/milvus/files/8956104/datanode-49.log)
[indexcoord-23.log](https://github.com/milvus-io/milvus/files/8956105/indexcoord-23.log)
[indexcoord-47.log](https://github.com/milvus-io/milvus/files/8956106/indexcoord-47.log)

**Comment by wziyang** [comment]
There is an abnormal format in a place, and I rewritten it here
helm install MILVUS_CLUSTER_NAME milvus/milvus --set etcd.replicaCount=3 --set proxy.replicas=3 --set service.type=NodePort --set service.nodePort=MILVUS_CLUSTER_PORT --set queryNode.replicas=3 --set indexNode.replicas=3 --set dataNode.replicas=3 --set log.persistence.enabled=true --set log.level=debug

**Comment by yanliang567** [comment]
@wziyang thank you for the issue.
it seems that the timeticks is very slow which caused milvus components unhealthy and restart. It usually caused by etcd running against a slow persistent volume. Do you run etcd on SSD volume? if not I recommend you run etcd on SSD volumes.
```
[2022/06/20 07:34:47.592 +08:00] [WARN] [timeticksync.go:339] ["rootcoord send tt to all channels too slowly"] [chanNum=2] [span=511]
[2022/06/20 07:34:48.117 +08:00] [WARN] [tso.go:177] ["clock offset is huge, check network latency and clock skew"] [jet-lag=487.635903ms] [prev-physical=2022/06/20 07:34:47.630 +08:00] [now=2022/06/20 07:34:48.117 +08:00]
```

/assign @wziyang 
/unassign

**Comment by wziyang** [comment]
@yanliang567 Thank you for your reply, It is indeed not SSD, may I ask how to recover data in this case？

**Comment by yanliang567** [comment]
As you only have 100k data inserted, I suggest you reinstall a new cluster.

**Comment by JackLCL** [comment]
@wziyang 
You can make these two envs bigger.
![origin_img_v2_b738cb1e-afc1-48e0-b0cf-a7dca19b203g](https://user-images.githubusercontent.com/53512883/177232859-eb5215e0-ec35-431d-9569-e142ceba0b9b.jpg)
