### ISSUE TITLE
[Bug]: [benchmark][cluster]High number of goroutines in Milvus rootcoord

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#17705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220621-1e87b545
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.1.0dev78
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo
benchmark-tag-no-clean-szhfb
server-configmap
server-cluster-8c64m
client-configmap
client-random-locust-100m-ddl-r8-w2-10m
<img width="1917" alt="20220622-154813" src="https://user-images.githubusercontent.com/34296482/174974141-0b19ceab-ec40-4317-b6c7-24e7296aa099.png">

**Comment by jingkl** [comment]
client-random-locust-100m-ddl-r8-w2-10m:

```
{
	"config.yaml": "locust_random_performance:
		  collections:
		    -
		      collection_name: sift_100m_128_l2
		      # other_fields: int
		      ni_per: 50000
		      build_index: true
		      index_type: ivf_sq8
		      index_param:
		        nlist: 2048
		      task:
		        types:
		          -
		            type: query
		            weight: 8
		            params:
		              top_k: 10
		              nq: 10
		              search_param:
		                nprobe: 16
		          -
		            type: load
		            weight: 1
		          -
		            type: get
		            weight: 8
		            params:
		              ids_length: 10
		          -
		            type: scene_test
		            weight: 2
		        connection_num: 1
		        clients_num: 20
		        spawn_rate: 2
		        during_time: 600
		"
}
```
1、create collection
2、build index of ivf_sq8
3、insert 100million vectors
4、flush
5、build index with the same params
6、load
7、locust concurrent: search, load, query, scene_test
```
@time_wrapper
    def scene_test(self, collection_name=None, vectors=None, ids=None):
        logger.debug("[scene_test] Start scene test : %s" % collection_name)
        self.create_collection(dimension=128, collection_name=collection_name)
        time.sleep(1)

        collection_info = self.get_info(collection_name)

        entities = utils.generate_entities(collection_info, vectors, ids)
        logger.debug("[scene_test] Start insert : %s" % collection_name)
        self.insert(entities, collection_name=collection_name)
        logger.debug("[scene_test] Start flush : %s" % collection_name)
        self.flush(collection_name=collection_name)

        self.count(collection_name=collection_name)

        logger.debug("[scene_test] Start create index : %s" % collection_name)
        self.create_index(field_name='float_vector', index_type="ivf_sq8", metric_type='l2',
                          collection_name=collection_name, index_param={'nlist': 2048})
        time.sleep(59)

        logger.debug("[scene_test] Start drop : %s" % collection_name)
        self.drop(collection_name=collection_name)
        logger.debug("[scene_test]Scene test close : %s" % collection_name)
        # time.sleep(1)
```

​​

**Comment by longjiquan** [comment]
http://10.97.11.12:9091/debug/pprof/goroutine?debug=1

**Comment by longjiquan** [comment]
goroutine profile: total 1608
512 @ 0x88a5e5 0x85578f 0x85540b 0x1a58b38 0x8c2101
#	0x1a58b37	github.com/apache/pulsar-client-go/pulsar.(*partitionProducer).failTimeoutMessages+0xf7	/go/pkg/mod/github.com/milvus-io/pulsar-client-go@v0.6.8/pulsar/producer_partition.go:488

512 @ 0x88a5e5 0x89b7f7 0x1a57810 0x8c2101
#	0x1a5780f	github.com/apache/pulsar-client-go/pulsar.(*partitionProducer).runEventsLoop+0xaf	/go/pkg/mod/github.com/milvus-io/pulsar-client-go@v0.6.8/pulsar/producer_partition.go:320

512 @ 0x88a5e5 0x89b7f7 0x1a5f705 0x8c2101
#	0x1a5f704	github.com/apache/pulsar-client-go/pulsar.(*producer).runBackgroundPartitionDiscovery.func1+0x124	/go/pkg/mod/github.com/milvus-io/pulsar-client-go@v0.6.8/pulsar/producer_impl.go:147
