### ISSUE TITLE
[Bug]: Error after upgrade milvus to latest version: collection 'XYZ' as not been loaded to memory or load failed

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#17711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvusdb/milvus-dev:master-20220621-e43f487f
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Upgrade milvus from milvusdb/milvus-dev:master-20220412-4781db8a to milvusdb/milvus-dev:master-20220621-e43f487f

We created a cluster of 9 shards 3 Query nodes, and ingested 17M vectors of 1024 Dim. We were checking in parallel, if its in accessible state or not, by performing search() for one vector, num_entities and query() on one scalar field. It was giving results till 15M data ingested, but thrown error after ingestion of 17M (previous thread issue),
`[2022/06/21 06:06:35.927 +00:00] [ERROR] [task_scheduler.go:489] ["Failed to execute task: call query coordinator LoadCollection: context canceled"] [traceID=4be1cd04c7d3ffc3] [stack="github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:489\ngithub.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:515"]`
It got fixed, when we updated to milvusdb/milvus-dev:master-20220621-e43f487f  version, but load() is throwing `pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=collection 'XYZ' as not been loaded to memory or load failed)>`
So, we horizontally scaled with 2 nodes more, which couldn't help. And then we vertically scaled to 64GB from 32GB, though there was available space it could max reach ~20GB and still same error is thrown and also we re-updated to the latest version (milvusdb/milvus-dev:master-latest).
`pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=collection 'XYZ' as not been loaded to memory or load failed)>`
Upon looking the query node logs, we have seen following WARN and ERROR lines,
```
{"log":"[2022/06/21 13:50:02.820 +00:00] [WARN] [cgo_helper.go:57] [\"LoadFieldData failed, C Runtime Exception: [UnexpectedError] Assert \\\"
row_count_opt_.value() == size\\\" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:177\\n =\u003e field
 (102) data has different row count (151231) than other column's row count (97381)\\n\"]\n","stream":"stdout","time":"2022-06-21T13:50:02.8202
3525Z"}
{"log":"Assert \"row_count_opt_.value() == size\" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:177\n
","stream":"stdout","time":"2022-06-21T13:50:02.820538759Z"}
{"log":" =\u003e field (1) data has different row count (151231) than other column's row count (97381)\n","stream":"stdout","time":"2022-06-21
T13:50:02.820551229Z"}
{"log":"[2022/06/21 13:50:02.820 +00:00] [WARN] [cgo_helper.go:57] [\"LoadFieldData failed, C Runtime Exception: [UnexpectedError] Assert \\\"
row_count_opt_.value() == size\\\" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:177\\n =\u003e field
 (1) data has different row count (151231) than other column's row count (97381)\\n\"]\n","stream":"stdout","time":"2022-06-21T13:50:02.820581
609Z"}
```

```
{"log":"[2022/06/21 13:50:02.897 +00:00] [ERROR] [segment_loader.go:155] [\"load segment failed when load data into memory\"] [collectionID=434041800985935873] [partitionID=434041800985935874] [segmentID=434046224783900673] [\"segment type\"=3] [error=\"[UnexpectedError] Assert \\\"row_count_opt_.value() == size\\\" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:177\\n =\u003e field (1) data has different row count (151231) than other column's row count (97381)\"] [stack=\"github.com/milvus-io/milvus/internal/querynode.(*segmentLoader).LoadSegment.func2\\n\\t/go/src/github.com/milvus-io/milvus/internal/querynode/segment_loader.go:155\\ngithub.com/milvus-io/milvus/internal/util/funcutil.ProcessFuncParallel.func3\\n\\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/parallel.go:85\"]\n","stream":"stdout","time":"2022-06-21T13:50:02.897676381Z"}
{"log":"[2022/06/21 13:50:02.897 +00:00] [ERROR] [parallel.go:87] [loadSegmentFunc] [error=\"[UnexpectedError] Assert \\\"row_count_opt_.value() == size\\\" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:177\\n =\u003e field (1) data has different row count (151231) than other column's row count (97381)\"] [idx=0] [stack=\"github.com/milvus-io/milvus/internal/util/funcutil.ProcessFuncParallel.func3\\n\\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/parallel.go:87\"]\n","stream":"stdout","time":"2022-06-21T13:50:02.897706701Z"} 
but while ingesting the data, no error with pymilvus.orm.exceptions.DataNotMatchException: <DataNotMatchException: (code=0, message=Arrays must all be same length.)> is thrown. Please help, the prod instance lying in disabled state, for quite a long time now. 
```

**Comment by yhmo** [comment]
Reported by Slack thread: https://app.slack.com/client/TM98LD8DQ/CMNHUC371/thread/CMNHUC371-1655823407.763429?cdn_fallback=2

**Comment by xige-16** [comment]
Which version did you upgrade from?  @lhotari

**Comment by p1913721** [comment]
Issue

**Comment by p1913721** [comment]
Done

**Comment by p1913721** [comment]
Done

**Comment by yhmo** [comment]
> from milvusdb/milvus-dev:master-20220412-4781db8a to milvusdb/milvus-dev:master-20220621-e43f487f

from milvusdb/milvus-dev:master-20220412-4781db8a to milvusdb/milvus-dev:master-20220621-e43f487f

**Comment by xige-16** [comment]
> > Which version did you upgrade from? @lhotari
> 
> from milvusdb/milvus-dev:master-20220412-4781db8a to milvusdb/milvus-dev:master-20220621-e43f487f

I can't reproduce it locally, can you provide the reproduced test code or log?

**Comment by yhmo** [comment]
query coord log while load() is called:
![query_coord](https://user-images.githubusercontent.com/2282099/175475798-873dab23-1506-4e62-a6c2-d26fe938a43d.png)

query node log while load() is called:
![query_node](https://user-images.githubusercontent.com/2282099/175475803-32914592-bc4f-4cf7-8946-8aa05d304675.png)

root coord log while load() is called:
![root_coord](https://user-images.githubusercontent.com/2282099/175475821-6af6871b-a476-458d-a028-cb7e91b07035.png)

**Comment by xige-16** [comment]
Not enough logs

**Comment by xige-16** [comment]
@yhmo
