### ISSUE TITLE
CPU performance get lower

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#1772]
**Describe the bug**

based on dataset: `sift-50m`, indexed with `ivf_sq8`, search with params: `nq:1000`, `topk: 1`
3.11: `87214f742b4f651a98e2f52e6e821f830b9e56b2`, cost: 0.73s
3.13: `24c39535be5dc32ab1b2e2846df8facef91e0e37`, cost: 1.68s

based on dataset: `sift-1b`, indexed with `ivf_sq8`, search with params: `nq:1000`, `topk: 1`
3.11: `87214f742b4f651a98e2f52e6e821f830b9e56b2`, cost: 10s
3.13: `24c39535be5dc32ab1b2e2846df8facef91e0e37`, cost: 27s

**Steps/Code to reproduce behavior**
current log path:
```
/test/milvus/db_data_7/sift_1b_2048_128_l2_sq8_wal/logs/milvus-20-03-27-00:49-debug.log
```
3.11 log path:
```
/test/milvus/db_data_7/sift_1b_2048_128_l2_sq8_wal/logs/milvus-20-03-12-01:16-debug.log
```

**Expected behavior**

**Environment details**
CPU-version

**Screenshots**

**Additional context**

**Comment by tinkerlin** [comment]
`cat milvus-20-03-12-01:16-debug.log | grep "IVF search cost:" > 311-ivfcost.log`
`cat milvus-20-03-27-00:49-debug.log| grep "IVF search cost:" > 327-ivfcost.log`

**327-ivfcost use more time on quantization cost**
@shengjun1985

**Comment by del-zhenwu** [comment]
It may be a mistake during testing stage, for the config_item: use_blas_threshold has been changed to 0 after 0.7.0 released

**Comment by del-zhenwu** [comment]
invalid issue, close
