### ISSUE TITLE
[Bug]: Questions about flush

### ISSUE THREAD

**Issue by WeiDong-Shi** [milvus-io/milvus#17776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 1.1.1
- Deployment mode(standalone or cluster):s tandalone
- SDK version(e.g. pymilvus v2.0.0rc2): 1.1.2
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 16  Intel(R) Xeon(R) Platinum 8374C CPU @ 2.70GHz / 128 G
- GPU: 
- Others:
```

### Current Behavior

I call the flush method every time I delete data, but I find that miluvs does not execute every request, resulting in incomplete deletion of the data to be deleted. I would like to consult our flush execution rules and how I can configure it to ensure that my processing can be executed every time.

**Comment by yanliang567** [comment]
@yhmo could you please help on this question?

/assign @yhmo 
/unassign

**Comment by yhmo** [comment]
In v1.x, firstly we know insert data is put into a buffer, waiting to be flushed. Flush action will flush the buffer into storage, to new segment files.
So, when you continually do insert, some data has been serialized into storage, and some data is in the buffer.

Delete action contains some ids that need to be deleted. When you call delete(), the delete action firstly checks the insert buffer, to find whether the deleted ids are in the buffer. If the buffer contains that id, the delete action will instantly remove the entities from the buffer. But without flush, the delete action won't affect persisted segments.

For example, entities [1, 2, 3] have been persisted into a segment in storage, now the insert buffer has entities with id [4, 5, 6], you call delete with deleted_ids=[3, 4]. The delete action will remove the [4] from the buffer. The the left [3] is recorded in buffer, wait flush action.

Then you call flush(), the flush action will do the following things:
1. use the id [3] to check all persisted segments. if found in a segment, change the segment's delete_doc.
2. flush the buffer with entities [5, 6] into a new segment

Note: if you call delete with deleted_ids=[4, 5, 6], then all the buffer will be removed, the flush action won't create a new segment.

**Comment by WeiDong-Shi** [comment]
> 在 v1.x 中，首先我们知道插入数据被放入缓冲区，等待刷新。刷新操作会将缓冲区刷新到存储中，到新的段文件。 所以，当你不断地插入时，一些数据已经序列化到存储中，而一些数据在缓冲区中。
> 
> 删除操作包含一些需要删除的 id。当您调用 delete() 时，删除操作首先检查插入缓冲区，以查找已删除的 id 是否在缓冲区中。如果缓冲区包含该 id，删除操作将立即从缓冲区中删除实体。但是如果没有刷新，删除操作不会影响持久段。
> 
> 例如，实体 [1, 2, 3] 已被持久化到存储中的段中，现在插入缓冲区具有 id 为 [4, 5, 6] 的实体，您可以使用 deleted_ids=[3, 4] 调用 delete。删除操作将从缓冲区中删除 [4]。左边[3]被记录在buffer中，等待flush动作。
> 
> 然后调用flush()，flush动作会做以下事情：
> 
> 1. 使用 id [3] 检查所有持久化的段。如果在段中找到，则更改段的 delete_doc。
> 2. 将带有实体 [5, 6] 的缓冲区刷新到新段中
> 
> 注意：如果你用deleted_ids=[4, 5, 6]调用delete，那么所有的buffer都会被删除，flush操作不会创建一个新的segment。

我每一次执行写入动作之后也都会调用一次 flush 的接口，可还是会遇见同样的问题，

**Comment by WeiDong-Shi** [comment]
> 在 v1 中，首先插入数据中被探查，等待 发掘。存储中，而一些数据化到中。
> 
> 删除操作删除（）时，删除操作首先检查插入的一些签名，查找已删除的某些身份，以删除如果您在操作中包含该 ID，则需要立即删除该 ID。但如果发现，删除不会影响到任何区域。
> 
> 例如，已被删除 2，移动到存储中的段中，现在插入 [1, 5, 6, 6, 6, 6, 5, 6, 4] 。等待删除] 删除停止中的 [4]。[3] 删除缓冲区中，刷新动作。
> 
> 然后调用flush()，flush动作会做以下事情：
> 
> 1. 使用id [3] 检查所有变化的段。如果在段中找到，则删除_doc。
> 2. 将太阳, 6] 人物的发现 [5] 探索新段中
> 
> 注意：如果你用deleted_ids=[4, 5, 6]调用delete，那么所有的缓冲区都会被删除，flush操作不会创建一个新的segment。

I will not only call flush action when deleting, but also call flush after each write. Is there a problem with this repeated flush? Would you recommend me to use automatic flush operation?

**Comment by WeiDong-Shi** [comment]
> In v1.x, firstly we know insert data is put into a buffer, waiting to be flushed. Flush action will flush the buffer into storage, to new segment files. So, when you continually do insert, some data has been serialized into storage, and some data is in the buffer.
> 
> Delete action contains some ids that need to be deleted. When you call delete(), the delete action firstly checks the insert buffer, to find whether the deleted ids are in the buffer. If the buffer contains that id, the delete action will instantly remove the entities from the buffer. But without flush, the delete action won't affect persisted segments.
> 
> For example, entities [1, 2, 3] have been persisted into a segment in storage, now the insert buffer has entities with id [4, 5, 6], you call delete with deleted_ids=[3, 4]. The delete action will remove the [4] from the buffer. The the left [3] is recorded in buffer, wait flush action.
> 
> Then you call flush(), the flush action will do the following things:
> 
> 1. use the id [3] to check all persisted segments. if found in a segment, change the segment's delete_doc.
> 2. flush the buffer with entities [5, 6] into a new segment
> 
> Note: if you call delete with deleted_ids=[4, 5, 6], then all the buffer will be removed, the flush action won't create a new segment.

I will not only call flush action when deleting, but also call flush after each write. Is there a problem with this repeated flush? Would you recommend me to use automatic flush operation?
