### ISSUE TITLE
[Bug]: cannot run ansible script: host key verification failed, while host doesn't exist in local known_hosts file

### ISSUE THREAD

**Issue by horuswoo** [milvus-io/milvus#17770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
this is on starting the Milvus cluster, not on running Milvus.

- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS):
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I was following [this](https://milvus.io/docs/v2.0.0/aws.md#provision-a-milvus-cluster) to provision and start the milvus cluster.

Behavior:
when I run the ansible command, I get this:
```
fatal: [18.118.148.155]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Host key verification failed.", "unreachable": true}
```

However the host doesn't exist in the known_hosts file at all.

### Expected Behavior

Either there is no `Host key verification failed` error, or the host would exist in the `known_hosts` file.

### Steps To Reproduce

```markdown
Follow the doc linked above.
```

### Anything else?

I've verified that the key in `ssh-add -l` matches the key pair used by the ec2 instances.

**Comment by john-h-luo** [comment]
Could you please check that your ssh key pair is valid?

**Comment by john-h-luo** [comment]
Are you still working on this issue?

**Comment by john-h-luo** [comment]
@horuswoo
