### ISSUE TITLE
[Bug]: Memory keeps rising，milvus cluster 2.0.2

### ISSUE THREAD

**Issue by GitHua2017** [milvus-io/milvus#17793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.2
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 16
- GPU: 
- Others:
```

### Current Behavior

Memory keeps rising  even though I'm not doing anything。

### Expected Behavior

Memory keeps stable.

### Steps To Reproduce

```markdown
1.Create a K8s cluster with kind in docker.(https://milvus.io/docs/v2.0.x/install_cluster-milvusoperator.md)
2.Install Helm Chart for Milvus.(https://milvus.io/docs/v2.0.x/install_cluster-helm.md)
3.Keep the milvus cluster running and doing nothing with it.
4.Finally, it is found that the memory of the milvus cluster will continue to rise.
```

### Milvus Log

**1. only deploy K8s cluster with kind.**
top - 17:33:32 up 14 days,  6:25,  1 user,  load average: 0.48, 2.07, 2.04
Tasks: 251 total,   1 running, 250 sleeping,   0 stopped,   0 zombie
%Cpu(s):  1.4 us,  1.3 sy,  0.0 ni, 97.0 id,  0.2 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 16249472 total, 12242028 free,  2034560 used,  1972884 buff/cache
KiB Swap:  4194300 total,  3306688 free,   887612 used. 13690204 avail Mem 

> PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                                
>   16656 root      20   0 1342064 533936  21464 S   5.3  3.3   1308:27 kube-apiserver                                                                                                                                                         
>  223507 root      20   0  767816  70900  11228 S   2.0  0.4 327:19.71 kube-controller                                                                                                                                                        
>   16774 root      20   0   10.7g  68396  13352 S   2.0  0.4 444:08.52 etcd                                                                                                                                                                   
>   18200 root      20   0 2247096  66316  14644 S   2.0  0.4 423:28.99 kubelet                                                                                                                                                                
>   19833 root      20   0 2468420  61240  14816 S   1.3  0.4 469:01.95 kubelet                                                                                                                                                                
>   19831 root      20   0 2247160  59584  15304 S   1.0  0.4 446:44.66 kubelet                                                                                                                                                                
>   19834 root      20   0 2246776  56440  15136 S   1.3  0.3 363:36.23 kubelet                                                                                                                                                                
>   14329 root      19  -1   99144  49736  49028 S   0.0  0.3   0:17.44 systemd-journal                                                                                                                                                        
>   14302 root      19  -1   99272  49148  48428 S   0.0  0.3   0:17.28 systemd-journal                                                                                                                                                        
> 3976025 eco       20   0  740888  48148  12340 S   0.0  0.3   0:02.15 cainjector                                                                                                                                                             
>   14288 root      19  -1   94944  44452  43736 S   0.0  0.3   0:16.67 systemd-journal                                                                                                                                                        
>   14594 root      20   0 2213812  42584   8340 S   0.7  0.3 148:32.54 containerd                                                                                                                                                             
> 3976189 root      20   0  752888  42440  17156 S   0.7  0.3   0:02.67 kube-scheduler                                                                                                                                                         
>   14579 root      20   0 2213620  42324   7728 S   0.3  0.3 124:00.92 containerd                                                                                                                                                             
>   14599 root      20   0 2402480  40216   8464 S   0.3  0.2 153:50.12 containerd                                                                                                                                                             
>   14578 root      20   0 2687772  40200   6892 S   0.7  0.2 109:40.49 containerd                                                                                                                                                             
>  164930 eco       20   0  759632  32288   4980 S   0.0  0.2  14:30.75 controller                                                                                                                                                             
>    2297 root      20   0   79492  23792  23616 S   0.0  0.1   3:14.31 systemd-journal                                                                                                                                                        
>    6966 root      20   0 1518416  23176   1728 S   0.3  0.1  42:44.16 dockerd                                                                                                                                                                
>   20693 root      20   0  752360  22468   5304 S   0.0  0.1  41:10.13 coredns                                                                                                                                                                
>   13449 root      20   0  751696  22312   3640 S   0.0  0.1   3:56.79 collectorkit                                                                                                                                                           
>   20735 root      20   0  752104  21380   4768 S   0.0  0.1  40:29.34 coredns                                                                                                                                                                
>   21923 root      20   0  747612  19600   3776 S   0.0  0.1   3:17.92 kube-proxy                                                                                                                                                             
>    6991 root      20   0  605992  19136   2352 S   0.0  0.1  17:07.33 lubanagent                                                                                                                                                             
>   20746 root      20   0  731212  18900   3804 S   0.0  0.1  10:18.75 local-path-prov                                                                                                                                                        
>   21250 root      20   0  747612  17568   3240 S   0.0  0.1   3:24.91 kube-proxy                                                                                                                                                             
>   21333 cloudmo+  20   0  718836  17256   4184 S   0.3  0.1   6:43.77 node_exporter                                                                                                                                                          
>   19526 root      20   0  747356  17184   3132 S   0.0  0.1   3:13.92 kube-proxy                                                                                                                                                             
>  164723 eco       20   0  743924  17044   4444 S   0.0  0.1  58:10.54 webhook                                                                                                                                                                
>   23151 root      20   0  747356  16844   3392 S   0.0  0.1   3:18.79 kube-proxy                                                                                                                                                             
>   22111 root      20   0  732756  16128   3192 S   0.0  0.1   7:29.05 kindnetd                                                                                                                                                               
>    7248 root      20   0 1196128  15792   2216 S   0.7  0.1  66:56.65 containerd                                                                                                                                                             
>   21446 root      20   0  732564  15172   3224 S   0.0  0.1   7:41.65 kindnetd                                                                                                                                                               
>   23042 root      20   0  732756  14924   3248 S   0.3  0.1   7:32.89 kindnetd                                                                                                                                                               
>   22151 root      20   0  733012  14572   3184 S   0.0  0.1   7:13.87 kindnetd 

**2. after deploying milvus cluster**
top - 17:38:14 up 14 days,  6:30,  1 user,  load average: 2.82, 2.81, 2.35
Tasks: 329 total,   1 running, 325 sleeping,   0 stopped,   3 zombie
%Cpu(s):  2.8 us,  2.3 sy,  0.0 ni, 94.7 id,  0.1 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem : 16249472 total,  7607512 free,  5855740 used,  2786220 buff/cache
KiB Swap:  4194300 total,  3310272 free,   884028 used.  9863272 avail Mem 

> PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                                
> 4037487 root      20   0    9.8g 585844  22136 S   0.7  3.6   0:15.75 java                                                                                                                                                                   
>   16656 root      20   0 1342320 518664  22276 S   5.3  3.2   1308:50 kube-apiserver                                                                                                                                                         
> 4035503 root      20   0   10.2g 389868  25268 S   0.0  2.4   0:08.67 java                                                                                                                                                                   
> 4035227 root      20   0   10.2g 386760  25176 S   0.3  2.4   0:07.16 java                                                                                                                                                                   
> 4035162 root      20   0   10.2g 379800  25240 S   0.7  2.3   0:07.10 java                                                                                                                                                                   
> 4040960 root      20   0 6527164 294764  21844 S   0.3  1.8   0:05.96 java                                                                                                                                                                   
> 4022127 root      20   0 6147092 267008  21508 S   0.3  1.6   0:06.13 java                                                                                                                                                                   
> 4025896 root      20   0 6546476 257972  21520 S   0.0  1.6   0:05.18 java                                                                                                                                                                   
> 4030184 root      20   0 6078480 244432  21432 S   0.3  1.5   0:05.47 java                                                                                                                                                                   
> 4019048 eco       20   0 1072812 171908  21608 S   0.7  1.1   0:03.75 minio                                                                                                                                                                  
> 4019006 eco       20   0 1073068 166632  21360 S   0.3  1.0   0:04.00 minio                                                                                                                                                                  
> 4023027 eco       20   0 1140656 165996  21212 S   0.7  1.0   0:02.76 minio                                                                                                                                                                  
> 4035470 root      20   0 5939012 160164  21848 S   0.3  1.0   0:11.32 java                                                                                                                                                                   
> 4021204 eco       20   0 1073004 103252  21592 S   1.0  0.6   0:02.49 minio                                                                                                                                                                  
>  223507 root      20   0  768072  78940  12968 S   1.7  0.5 327:25.20 kube-controller                                                                                                                                                        
>   16774 root      20   0   10.7g  75696  16060 S   1.7  0.5 444:17.32 etcd                                                                                                                                                                   
>   18200 root      20   0 2247096  67624  14872 S   2.3  0.4 423:35.01 kubelet                                                                                                                                                                
>   19831 root      20   0 2247160  66544  15692 S   3.6  0.4 446:51.33 kubelet                                                                                                                                                                
>   19833 root      20   0 2468420  64588  15220 S   3.3  0.4 469:07.62 kubelet                                                                                                                                                                
>   19834 root      20   0 2246776  64460  15652 S   3.6  0.4 363:42.26 kubelet                                                                                                                                                                
>   14329 root      19  -1   99144  50928  50220 S   0.0  0.3   0:17.59 systemd-journal                                                                                                                                                        
>   14302 root      19  -1   99272  50140  49420 S   0.0  0.3   0:17.40 systemd-journal                                                                                                                                                        
>   14594 root      20   0 2205616  49040   8464 S   0.7  0.3 148:35.64 containerd                                                                                                                                                             
> 3976025 eco       20   0  740888  48200  12356 S   0.7  0.3   0:03.85 cainjector                                                                                                                                                             
>   14579 root      20   0 2221816  47392   8068 S   1.7  0.3 124:03.72 containerd                                                                                                                                                             
>   14599 root      20   0 2410676  44736   8564 S   0.7  0.3 153:52.71 containerd                                                                                                                                                             
>   14288 root      19  -1   94944  44460  43744 S   0.0  0.3   0:16.68 systemd-journal                                                                                                                                                        
> 3976189 root      20   0  752888  42956  17848 S   0.7  0.3   0:03.83 kube-scheduler                                                                                                                                                         
>   14578 root      20   0 2687772  40284   6972 S   0.7  0.2 109:41.90 containerd                                                                                                                                                             
> 4018394 1001      20   0 5972144  37404  11504 S   1.0  0.2   0:03.79 etcd                                                                                                                                                                   
> 4014262 root      20   0 1706860  36952  23016 S   0.3  0.2   0:00.24 milvus                                                                                                                                                                 
> 4041569 root      20   0   52708  35832    792 S   0.0  0.2   0:00.04 hsar                                                                                                                                                                   
> 4017258 root      20   0 1854324  35588  23644 S   0.0  0.2   0:00.24 milvus                                                                                                                                                                 
> 4017193 root      20   0 1633384  35544  23624 S   0.7  0.2   0:00.44 milvus                                                                                                                                                                 
> 4014673 root      20   0 1706348  35512  22644 S   0.0  0.2   0:00.23 milvus                                                                                                                                                                 
> 4014545 root      20   0 1558628  35476  22520 S   0.0  0.2   0:00.23 milvus                                                                                                                                                                 
> 4017257 root      20   0 1558884  35080  23440 S   0.0  0.2   0:00.26 milvus                                                                                                                                                                 
> 4014570 root      20   0 1559396  34964  22476 S   0.0  0.2   0:00.22 milvus                                                                                                                                                                 
> 4020879 1001      20   0 5972144  34808  11456 S   1.0  0.2   0:02.58 etcd                                                                                                                                                                   
> 4016818 root      20   0 1706092  34736  23140 S   0.3  0.2   0:00.22 milvus                                                                                                                                                                 
>  164930 eco       20   0  759888  34108   5056 S   0.0  0.2  14:31.20 controller                                                                                                                                                             
> 4020272 1001      20   0 5971888  31336  11344 S   1.0  0.2   0:02.59 etcd                                                                                                                                                                   
>    2297 root      20   0   79492  24588  24412 S   0.0  0.2   3:14.44 systemd-journal                                                                                                                                                        
>    6966 root      20   0 1518416  23504   1876 S   0.3  0.1  42:44.73 dockerd                                                                                                                                                                
>   21923 root      20   0  747612  22388   4476 S   0.0  0.1   3:18.16 kube-proxy                                                                                                                                                             
>   13449 root      20   0  751696  22312   3640 S   0.0  0.1   3:56.83 collectorkit                                                                                                                                                           
>   20735 root      20   0  752104  22204   5296 S   0.0  0.1  40:31.06 coredns                                                                                                                                                                
>   20693 root      20   0  752360  21896   5584 S   0.0  0.1  41:11.86 coredns                                                                                                                                                                
>   19526 root      20   0  747356  20092   4120 S   0.0  0.1   3:14.18 kube-proxy

**3. 1 days after deploying the cluster**
top - 09:54:47 up 14 days, 22:46,  1 user,  load average: 0.66, 0.65, 0.59
Tasks: 321 total,   1 running, 317 sleeping,   0 stopped,   3 zombie
%Cpu(s):  2.9 us,  2.1 sy,  0.0 ni, 94.5 id,  0.5 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem : 16249472 total,  3179032 free,  9361976 used,  3708464 buff/cache
KiB Swap:  4194300 total,  3320512 free,   873788 used.  6324356 avail Mem 

> PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                                
> 4037487 root      20   0    9.9g   2.4g  22356 S   1.0 15.3  10:57.41 java                                                                                                                                                                   
> 4035503 root      20   0   10.4g 667252  25924 S   0.3  4.1   4:20.11 java                                                                                                                                                                   
> 4035162 root      20   0   10.3g 639432  25832 S   0.7  3.9   4:37.34 java                                                                                                                                                                   
> 4035227 root      20   0   10.3g 592260  25428 S   0.0  3.6   3:41.26 java                                                                                                                                                                   
> 4040960 root      20   0 8092388 526884  22408 S   0.7  3.2   3:28.43 java                                                                                                                                                                   
>   16656 root      20   0 1342320 479852  24248 S   7.0  3.0   1373:00 kube-apiserver                                                                                                                                                         
> 4022127 root      20   0 6147092 418360  21652 S   0.0  2.6   2:12.36 java                                                                                                                                                                   
> 4025896 root      20   0 6546476 409132  21620 S   0.3  2.5   1:41.44 java                                                                                                                                                                   
> 4030184 root      20   0 6080528 408020  21628 S   0.0  2.5   1:38.81 java                                                                                                                                                                   
> 4019048 eco       20   0 1141744 223344  22044 S   0.7  1.4   5:52.52 minio                                                                                                                                                                  
> 4023027 eco       20   0 1141488 205684  21872 S   0.7  1.3   7:12.67 minio                                                                                                                                                                  
> 4019006 eco       20   0 1140976 205272  21892 S   0.7  1.3   7:06.97 minio                                                                                                                                                                  
> 4035470 root      20   0 5939012 169400  21888 S   0.3  1.0   2:01.67 java                                                                                                                                                                   
> 4021204 eco       20   0 1141232 144724  22076 S   0.7  0.9   7:23.09 minio                                                                                                                                                                  
>  223507 root      20   0  768072  73432  13492 S   1.3  0.5 343:25.55 kube-controller                                                                                                                                                        
>   19831 root      20   0 2247160  70076  17048 S   2.7  0.4 468:38.09 kubelet                                                                                                                                                                
>   16774 root      20   0   10.7g  68536  18648 S   1.7  0.4 466:14.44 etcd                                                                                                                                                                   
>   19834 root      20   0 2246776  66980  17096 S   2.7  0.4 384:59.83 kubelet                                                                                                                                                                
>   18200 root      20   0 2247096  66884  16532 S   1.7  0.4 444:32.44 kubelet                                                                                                                                                                
>   19833 root      20   0 2468420  65652  16668 S   1.3  0.4 489:15.15 kubelet                                                                                                                                                                
>    2297 root      20   0  132912  64844  64668 S   0.0  0.4   3:23.42 systemd-journal                                                                                                                                                        
> 4014262 root      20   0 1854772  54320  25460 S   3.0  0.3  28:28.59 milvus                                                                                                                                                                 
> 4018394 1001      20   0 5972656  53840  12632 S   1.0  0.3  12:11.69 etcd                                                                                                                                                                   
>   14329 root      19  -1  107336  53368  52660 S   0.0  0.3   0:18.43 systemd-journal                                                                                                                                                        
>   14302 root      19  -1  107464  52436  51716 S   0.0  0.3   0:18.22 systemd-journal                                                                                                                                                        
>   14594 root      20   0 2230204  49656   9172 S   0.7  0.3 155:33.56 containerd

**4. 5 days after deploying the cluster**
top - 10:07:16 up 18 days, 22:59,  1 user,  load average: 0.40, 0.52, 0.65
Tasks: 318 total,   1 running, 314 sleeping,   0 stopped,   3 zombie
%Cpu(s):  3.1 us,  2.0 sy,  0.0 ni, 94.4 id,  0.5 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem : 16249472 total,   220216 free, 14538332 used,  1490924 buff/cache
KiB Swap:  4194300 total,  2151908 free,  2042392 used.  1147932 avail Mem 

> PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                                
> 4037487 root      20   0    9.9g   2.6g   7616 S   1.3 16.6  71:04.07 java                                                                                                                                                                   
> 4035162 root      20   0   10.5g   2.3g  10376 S   0.7 14.9  35:33.08 java                                                                                                                                                                   
> 4035503 root      20   0   10.5g   2.1g   6536 S   0.7 13.6  33:59.26 java                                                                                                                                                                   
> 4035227 root      20   0   10.5g   1.8g   7012 S   0.3 11.4  27:23.48 java                                                                                                                                                                   
> 4040960 root      20   0 8094444   1.0g   6776 S   0.0  6.4  25:37.82 java                                                                                                                                                                   
>   16656 root      20   0 1342832 472464  20180 S   8.6  2.9   1755:26 kube-apiserver                                                                                                                                                         
> 4025896 root      20   0 6546476 394296   6012 S   0.0  2.4  10:07.21 java                                                                                                                                                                   
> 4022127 root      20   0 6147092 392908   6552 S   0.7  2.4  13:42.07 java                                                                                                                                                                   
> 4030184 root      20   0 6080528 382032   7248 S   0.0  2.4  10:04.27 java                                                                                                                                                                   
> 4019048 eco       20   0 1141744 206428   7864 S   0.3  1.3  43:15.79 minio                                                                                                                                                                  
> 4023027 eco       20   0 1141488 191444   7872 S   0.7  1.2  53:18.65 minio                                                                                                                                                                  
> 4019006 eco       20   0 1141232 188404   7468 S   0.3  1.2  53:14.98 minio                                                                                                                                                                  
> 4021204 eco       20   0 1141232 131368   7336 S   0.7  0.8  55:09.28 minio                                                                                                                                                                  
>  223507 root      20   0  768328  68984  10088 S   1.7  0.4 438:47.18 kube-controller                                                                                                                                                        
>   19831 root      20   0 2247160  68256  14572 S   1.7  0.4 598:46.56 kubelet                                                                                                                                                                
>   14329 root      19  -1  115528  67352  66644 S   0.0  0.4   0:23.37 systemd-journal                                                                                                                                                        
>   14302 root      19  -1  115656  66516  65796 S   0.0  0.4   0:23.08 systemd-journal                                                                                                                                                        
>   19833 root      20   0 2468420  65844  14068 S   2.6  0.4 609:27.09 kubelet                                                                                                                                                                
>   19834 root      20   0 2320764  65304  14556 S   1.7  0.4 512:13.17 kubelet                                                                                                                                                                
>   18200 root      20   0 2247096  65256  14656 S   2.6  0.4 569:31.19 kubelet                                                                                                                                                                
>   16774 root      20   0   10.7g  62236  11992 S   2.3  0.4 596:54.99 etcd                                                                                                                                                                   
>   14288 root      19  -1  103136  60864  60148 S   0.0  0.4   0:22.44 systemd-journal                                                                                                                                                        
> 4018394 1001      20   0 5972656  47528   6532 S   1.3  0.3  84:43.82 etcd                                                                                                                                                                   
>   14594 root      20   0 2238400  43644   6200 S   0.3  0.3 197:02.48 containerd                                                                                                                                                             
>   14579 root      20   0 2238464  42524   5760 S   0.7  0.3 169:37.16 containerd                                                                                                                                                             
> 3976025 eco       20   0  741400  40556   5252 S   0.7  0.2  22:01.05 cainjector                                                                                                                                                             
> 4035470 root      20   0 5939012  40252   1904 S   0.0  0.2   8:03.30 java                                                                                                                                                                   
>   14599 root      20   0 2435264  40020   5884 S   1.0  0.2 198:56.32 containerd                                                                                                                                                             
> 4020272 1001      20   0 5972400  39692   6268 S   1.3  0.2  69:06.62 etcd                                                                                                                                                                   
>    2297 root      20   0   87692  39540  39368 S   0.0  0.2   4:16.12 systemd-journal                                                                                                                                                        
> 4020879 1001      20   0 5972912  38400   6528 S   1.0  0.2  71:59.31 etcd                                                                                                                                                                   
>   14578 root      20   0 2687772  37992   5336 S   1.0  0.2 145:02.81 containerd                                                                                                                                                             
> 4014262 root      20   0 1854772  33084   6648 S   3.0  0.2 198:29.68 milvus                                                                                                                                                                 
> 3976189 root      20   0  753400  31280   6140 S   0.3  0.2  22:04.58 kube-scheduler                                                                                                                                                         
>  164930 eco       20   0  759888  28772   4156 S   0.3  0.2  19:30.09 controller                                                                                                                                                             
> 4014545 root      20   0 1854580  25376   6896 S   1.3  0.2  77:02.50 milvus                                                                                                                                                                 
>    6980 root      20   0  659944  23532  20892 S   0.0  0.1   2:53.47 rsyslogd                                                                                                                                                               
>   13449 root      20   0  751952  22844   4148 S   0.0  0.1   5:12.98 collectorkit                                                                                                                                                           
>   20735 root      20   0  752104  22204   5204 S   0.0  0.1  54:09.49 coredns                                                                                                                                                                
>   20693 root      20   0  752360  22032   5336 S   0.3  0.1  55:12.96 coredns                                                                                                                                                                
>    6966 root      20   0 1518416  22004   1520 S   0.3  0.1  56:22.99 dockerd                                                                                                                                                                
> 4016818 root      20   0 1854324  21240   6636 S   0.0  0.1   6:15.04 milvus                                                                                                                                                                 
>   14297 root      19  -1  123776  20692  20504 S   0.0  0.1   0:24.06 systemd-journal                                                                                                                                                        
> 4014673 root      20   0 1855092  20220   6392 S   0.0  0.1   6:32.56 milvus                                                                                                                                                                 
>   21923 root      20   0  747612  19916   3984 S   0.0  0.1   4:26.14 kube-proxy                                                                                                                                                             
>    6991 root      20   0  605992  19388   2432 S   0.0  0.1  22:31.51 lubanagent                                                                                                                                                             
> 4017193 root      20   0 1854836  19332   6220 S   0.3  0.1  24:57.99 milvus                                                                                                                                                                 
>   21250 root      20   0  747612  18660   4028 S   0.0  0.1   4:33.66 kube-proxy                                                                                                                                                             
>   23151 root      20   0  747356  18324   3980 S   0.3  0.1   4:25.87 kube-proxy

**Comment by chenlinwei12321** [comment]
We also encountered this problem. Have you solved it？

**Comment by soothing-rain** [comment]
We have solved some memory related issues. Expect things to get much better in v2.1.0.

In the meantime, @GitHua2017 can you let us know which pod (or pods) have the most significant memory growth?

**Comment by soothing-rain** [comment]
> 

Understood.

Can you tell which pod is consuming the that significant memory? Is it DataCoord, QueryCoord, etc? And how much.

**Comment by soothing-rain** [comment]
> 1、which pod (or pods) have the most significant memory growth? A: I deploy in docker, virtual environment，but the physical machine memory growth. 2、What was done the first time after you deployed Milvus? (have you inserted any data, built indexes, did some searches, etc.) A: I do nothing after deploying Milvus. 3、What happened between Day1 and Day5. Any insert/query operations to Milvus? A: After deploying Milvus, I keep it running without doing anything.

Understood.

Can you tell which pod is consuming the that significant memory? Is it DataCoord, QueryCoord, etc? And how much.
