### ISSUE TITLE
[Feature]: Create index on a loaded collection should support automatically load index when index build done.

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#17809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Currently if user do:
1) insert data
2) load collection
3) create index

The loaded collection will never know a collection has index and reload the index.
 

### Describe the solution you'd like.

Temporary fix: release collection and reload.
User should follow the following way:

Create collection
Create Index
insert
Create Index
Load
Search
That is the safest way for now.

Permanent fix: 
Enable to new mechanism to notify querycoord to reload segment when index done, should be similar to the handoff solution

**Comment by molo6379** [comment]
Hi, thanks for the instructions! However, I got a question about milvus_client.py 

if you look at this code
`
def create_collection(
        self,
        collection_name: str,
        dimension: int,
        primary_field_name: str = "id",  # default is "id"
        id_type: str = "int",  # or "string",
        vector_field_name: str = "vector",  # default is  "vector"
        metric_type: str = "IP",
        auto_id: bool = False,
        timeout: Optional[float] = None,
        **kwargs,
    ):
        if "enable_dynamic_field" not in kwargs:
            kwargs["enable_dynamic_field"] = True

        schema = self.create_schema(auto_id=auto_id, **kwargs)

        if id_type == "int":
            pk_data_type = DataType.INT64
        elif id_type in ("string", "str"):
            pk_data_type = DataType.VARCHAR
        else:
            raise PrimaryKeyException(message=ExceptionsMessage.PrimaryFieldType)

        pk_args = {}
        if "max_length" in kwargs and pk_data_type == DataType.VARCHAR:
            pk_args["max_length"] = kwargs["max_length"]

        schema.add_field(primary_field_name, pk_data_type, is_primary=True, **pk_args)
        vector_type = DataType.FLOAT_VECTOR
        schema.add_field(vector_field_name, vector_type, dim=dimension)
        schema.verify()

        conn = self._get_connection()
        if "consistency_level" not in kwargs:
            kwargs["consistency_level"] = DEFAULT_CONSISTENCY_LEVEL
        try:
            conn.create_collection(collection_name, schema, timeout=timeout, **kwargs)
            logger.debug("Successfully created collection: %s", collection_name)
        except Exception as ex:
            logger.error("Failed to create collection: %s", collection_name)
            raise ex from ex
        index_params = {"metric_type": metric_type, "params": {}}
        self._create_index(collection_name, vector_field_name, index_params, timeout=timeout)
        self._load(collection_name, timeout=timeout)
`
Theres a self._load() part where I assume that it is loading collection as soon as it creates.
Then wouldn't it be the unsafe way of loading collection according to your guideline? Thanks

**Comment by xiaofan-luan** [comment]
> Thanks

For currently milvus, you has to create index before you load

**Comment by molo6379** [comment]
> > Thanks
> 
> For currently milvus, you has to create index before you load

Thanks for the response, how about data insert? Some say that its slower to insert data after index creation is that true?
