### ISSUE TITLE
[Bug]:  ", etcdserver: request is too large" when loading collection

### ISSUE THREAD

**Issue by joshuayyy** [milvus-io/milvus#17813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.0.2
- Deployment mode(standalone or cluster): standalone 
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus v2.0.2
- OS(Ubuntu or CentOS): Ubuntu 20.04
- CPU/Memory: 8-core CPU, 16G RAM
- GPU: NA
- Others: NA
```

### Current Behavior

When I load a collection with about 900,000, an error is reported that ", etcdserver: request is too large".
I tried pymilvus, attu, and milvus_cli, but failed.

### Steps To Reproduce

```markdown
It happens when I did scalar queries (which also download vectors), vector searches and data insertions (a few dozen vectors at a time, about 100 times per hour) for that collection. In this case, the collection crashes after a day or so, and then cannot be loaded.
```

### Milvus Log

segments of the log:

{"log":"{"level":"warn","ts":"2022-06-26T16:44:53.851Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0005fe700/#initially=[etcd:2379]","attempt":0,"error":"rpc error: code = InvalidArgument desc = etcdserver: request is too large"}\n","stream":"stderr","time":"2022-06-26T16:44:53.851835228Z"}
{"log":"[2022/06/26 16:44:53.852 +00:00] [DEBUG] [task.go:493] ["loadCollectionTask postExecute done"] [msgID=434168792013340712] [collectionID=434079380423573505]\n","stream":"stdout","time":"2022-06-26T16:44:53.852268516Z"}
{"log":"[2022/06/26 16:44:53.852 +00:00] [DEBUG] [task_scheduler.go:627] ["scheduleLoop: process triggerTask failed"] [triggerTaskID=434168792013340712] [error="etcdserver: request is too large"]\n","stream":"stdout","time":"2022-06-26T16:44:53.85228047Z"}
{"log":"[2022/06/26 16:44:53.856 +00:00] [DEBUG] [task_scheduler.go:684] ["scheduleLoop: trigger task done and delete from etcd"] [triggerTaskID=434168792013340712]\n","stream":"stdout","time":"2022-06-26T16:44:53.856781601Z"}
{"log":"[2022/06/26 16:44:53.856 +00:00] [ERROR] [impl.go:238] ["load collection to query nodes failed"] [role=querycoord] [collectionID=434079380423573505] [msgID=434168792598971736] [error=", etcdserver: request is too large"] [stack="github.com/milvus-io/milvus/internal/querycoord.(*QueryCoord).LoadCollection\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/impl.go:238\ngithub.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).LoadCollection\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:345\ngithub.com/milvus-io/milvus/internal/proto/querypb._QueryCoord_LoadCollection_Handler.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proto/querypb/query_coord.pb.go:3012\ngithub.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38\ngithub.com/milvus-io/milvus/internal/proto/querypb._QueryCoord_LoadCollection_Handler\n\t/go/src/github.com/milvus-io/milvus/internal/proto/querypb/query_coord.pb.go:3014\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934"]\n","stream":"stdout","time":"2022-06-26T16:44:53.856818439Z"}
{"log":"[2022/06/26 16:44:53.856 +00:00] [DEBUG] [task.go:4300] ["loadCollectionTask PostExecute"] [role=proxy] [msgID=434168792598971736]\n","stream":"stdout","time":"2022-06-26T16:44:53.856953802Z"}
{"log":"[2022/06/26 16:44:53.856 +00:00] [DEBUG] [impl.go:500] ["LoadCollection done"] [traceID=6c411a2ba8e3556d] [role=proxy] [MsgID=434168792598971736] [BeginTS=434179117114195969] [EndTS=434179117114195969] [db=] [collection=milvus_pre_2048]\n","stream":"stdout","time":"2022-06-26T16:44:53.856961043Z"}
{"log":"[2022/06/26 16:45:23.245 +00:00] [INFO] [compaction_trigger.go:249] ["global generated plans"] [collection=0] ["plan count"=0]\n","stream":"stdout","time":"2022-06-26T16:45:23.245728728Z"}
{"log":"[2022/06/26 16:45:23.245 +00:00] [INFO] [compaction_trigger.go:249] ["global generated plans"] [collection=0] ["plan count"=0]\n","stream":"stdout","time":"2022-06-26T16:45:23.24575212Z"}
{"log":"[2022/06/26 16:45:23.792 +00:00] [DEBUG] [query_coord.go:530] ["loadBalanceSegmentLoop: memory usage rate of all online QueryNode"] ["mem rate"="{\"37\":1.8156764980403758e-10}"]\n","stream":"stdout","time":"2022-06-26T16:45:23.792861976Z"}
{"log":"[2022/06/26 16:45:23.792 +00:00] [WARN] [query_coord.go:532] ["loadBalanceSegmentLoop: there are too few available query nodes to balance"] [onlineNodeIDs="[37]"] [availableNodeIDs="[37]"]\n","stream":"stdout","time":"2022-06-26T16:45:23.792895006Z"}
{"log":"[2022/06/26 16:46:23.245 +00:00] [INFO] [compaction_trigger.go:249] ["global generated plans"] [collection=0] ["plan count"=0]\n","stream":"stdout","time":"2022-06-26T16:46:23.245252053Z"}
{"log":"[2022/06/26 16:46:23.245 +00:00] [INFO] [compaction_trigger.go:249] ["global generated plans"] [collection=0] ["plan count"=0]\n","stream":"stdout","time":"2022-06-26T16:46:23.245277364Z"}
{"log":"[2022/06/26 16:46:23.793 +00:00] [DEBUG] [query_coord.go:530] ["loadBalanceSegmentLoop: memory usage rate of all online QueryNode"] ["mem rate"="{\"37\":1.7687451503434212e-10}"]\n","stream":"stdout","time":"2022-06-26T16:46:23.793129297Z"}
{"log":"[2022/06/26 16:46:23.793 +00:00] [WARN] [query_coord.go:532] ["loadBalanceSegmentLoop: there are too few available query nodes to balance"] [onlineNodeIDs="[37]"] [availableNodeIDs="[37]"]\n","stream":"stdout","time":"2022-06-26T16:46:23.793150849Z"}

Full logs:

[milvus-standalone.log](https://github.com/milvus-io/milvus/files/8988499/milvus-standalone.log)

**Comment by yanliang567** [comment]
sounds like a known issue in 2.0.2
@xiaofan-luan could you please help to double check?

/assign @xiaofan-luan 
/unassign

**Comment by kgmiller** [comment]
I'm seeing this in production too - just upgraded from 0.10.0 to 2.0.2 last week, this has our entire production system down now. Logs are attached.
[milvus.log](https://github.com/milvus-io/milvus/files/8996480/milvus.log)

**Comment by yhmo** [comment]
Similar to #16638
