### ISSUE TITLE
[Enhancement]: Support for using pre-created Kafka topics

### ISSUE THREAD

**Issue by lvmnn** [milvus-io/milvus#17811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

In most companies, Kafka is maintained by professional teams and cannot be configured to automatically create topics.

Hopefully, 2.1 will support the use of pre-created topics

**Comment by taohongxiu** [comment]
My company is the same

**Comment by xiaofan-luan** [comment]
keep it

**Comment by xiaofan-luan** [comment]
is this ready?

**Comment by smellthemoon** [comment]
looking into it now

**Comment by xiaofan-luan** [comment]
keep it open
