### ISSUE TITLE
[Bug]: Data keeps persistent in disk even after retension timeout

### ISSUE THREAD

**Issue by RateSpirit** [milvus-io/milvus#17856]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.2
- Deployment mode(standalone):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

修改 milvus.yaml 的 
rocksmq:
  path: /var/lib/milvus/rdb_data # The path where the message is stored in rocksmq
  rocksmqPageSize: 1073741824 # 1 GB, 1 * 1024 * 1024 * 1024 bytes, The size of each page of messages in rocksmq
  retentionTimeInMinutes: 1440 # 1 days, 7 * 24 * 60 minutes, The retention time of the message in rocksmq.
  retentionSizeInMB: 1024 # 1 GB, 1 * 1024 MB, The retention size of the message in rocksmq.

之后， 系统跑一段时间
rdb_data目录下的sst问题会把系统磁盘占满

<img width="481" alt="image" src="https://user-images.githubusercontent.com/11364643/176088003-ec5a3b19-49aa-4cc1-880b-62a7813613de.png">
20多天前的数据还保存着

### Expected Behavior

rdb_data目录占用磁盘固定不变

**Comment by xiaofan-luan** [comment]
hi @RateSpirit :
1) pls have a readable issue name
2) please use English in your issue
3) with your configuration, data should be purged in 7 days, pls offer your log so we can investigate on why

**Comment by xiaofan-luan** [comment]
the actually cleanup logic happens on rocksdb retention

**Comment by yanliang567** [comment]
@RateSpirit Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @RateSpirit 
/unassign

**Comment by xiaofan-luan** [comment]
It should be deleted by milvus, but rocksdb compaction time to clean data is not a guarantee.
Let me invesigate if there are something I can config to trigger it faster
