### ISSUE TITLE
[Bug]: shard leader is unavailable

### ISSUE THREAD

**Issue by BUPTAnderson** [milvus-io/milvus#17855]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): milvus-sdk-go v2.0.0
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 32Cores/196GB
- GPU: 
- Others:
```

### Current Behavior

`search/query` can not return
querycoord log print a lots of `shard leader is unavailable` msgs

### Expected Behavior

`search/query` can return rightly

### Milvus Log

[querycoord-21.log](https://github.com/milvus-io/milvus/files/8997511/querycoord-21.log)

**Comment by BUPTAnderson** [comment]
rootcoord still not working after restart, [querycoord-21.log](https://github.com/milvus-io/milvus/files/8997511/querycoord-21.log) is the restart log

**Comment by yanliang567** [comment]
@jiaoew1991  sounds like a known issue on master, could you please take a look?

/assign @jiaoew1991 
/unassign

**Comment by jiaoew1991** [comment]
@BUPTAnderson Could you please use this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

**Comment by BUPTAnderson** [comment]
> @BUPTAnderson Could you please use this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

sorry， cluster has redeployed and logs have been cleared.

**Comment by BUPTAnderson** [comment]
when i upgrade the cluster, this issue occured again, same to #18178

**Comment by xiaofan-luan** [comment]
close because of duplicated
