### ISSUE TITLE
[Enhancement]: Session manager and Proxymanager need to handle etcd compacted err

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#17857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Currently we panic when etcd hit err.
This may not be the right behaviour when revision is compacted and Err.Compacted thrown out.

To fix that, we need to figure out:
1) if we just do watch, do we receive compacted err?

if no, my suggest would be we don't use watch/load with revision.

If yes, we have to make sure everywhere use watch/load with/without revision works correctly.

### Why is this needed?

The etcd revision could be increasing fast, make sure we handle it correctly when etcd revision compacted

**Comment by xiaocai2333** [comment]
working on it~, verify it 
Even if we just do watch, we still receive `ErrCompacted`.

**Comment by xiaocai2333** [comment]
How to trigger ErrCompacted:

1. Trigger compaction manually

```
_, _, _, revision, _ := mt.client.LoadWithRevisionAndVersions(key)

// save some metas to etcd

resp, err := etcdCli.Compact(context.Background(), 3000)
watchChan = watchWithRevision(key, revision)
```

2. Trigger compaction automatically

First you need to configure environment variables for etcd.
```
environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
```
the code

```
_, _, _, revision, _ := mt.client.LoadWithRevisionAndVersions(key)

// Write a lot of keys to let etcd trigger compaction automatically

watchChan = watchWithRevision(key, revision)
```

`WatchWithRevision` triggers ErrCompacted in the above two ways, but `WatchWithPrefix` does not trigger in the above two ways.
I'm sure compaction happened either happened.

But a few days ago, the test team found that WatchWithRevision also triggers ErrCompacted. Maybe need more test.

**Comment by xiaofan-luan** [comment]
> ```
> 
> ```

My guess is WatchWithPrefix shouldn't hit ErrCompacted. any comments? @congqixia @sunby

**Comment by congqixia** [comment]
@xiaocai2333 try update revision for key A and `WatchWithPrefix` fro key B.
