### ISSUE TITLE
[Enhancement]: Get row count from query cluster

### ISSUE THREAD

**Issue by longjiquan** [milvus-io/milvus#17868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

I want to enhance the workflow of how Milvus return the row count of a collection or partition.
If a collection/partition was loaded, the row count can be returned from query cluster, same to `retrieve/search`:
- 1, Proxy send request to the shard leader；
- 2, For growing segments, get row count of segments from shard leader;
- 3, For sealed segments, shard leader dispatch the request to the followers, the row count of sealed segment between all replicas should be consistent and eqaul, so any followers can handle it;
- 4, For a specific segment, the real count is equal to the insert count minus the delete count. Note, the delete count here doesn't means the number of delete records, we should calculate the number of primary keys which hit in insert records;
- 5, The total number of a shard should be the sum of all segments, shard leader counts the sum and return to the Proxy;
- 6, The total number of a collection should be the sum of all shards, Proxy counts the sum and return to the users;

### Why is this needed?

If this is supported, when `num_entities` was called by sdk, the `flush` can be removed.

**Comment by xiaofan-luan** [comment]
do we have any MEP or design plans about it?

**Comment by longjiquan** [comment]
> do we have any MEP or design plans about it?

Not yet, maybe the information in this issue is detailed enough?
