### ISSUE TITLE
Exception in search params check

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#1787]
**Describe the bug**
If list(float) passed as query_records, it will raise an exception
```
object of type 'float' has no len()
```

```
def is_legal_records(value):
    param_error = ParamError('A vector must be a non-empty, 2-dimensional array and '
                             'must contain only elements with the float data type or the bytes data type.')

    if isinstance(value, np.ndarray):
        if not is_legal_numpy_array(value):
            raise param_error

        return True

    if not isinstance(value, list) or len(value) == 0:
        raise param_error

    if isinstance(value[0], bytes):
        check_func = is_legal_bin_vector
    else:
        check_func = is_legal_vector

    _dim = len(value[0])

    for record in value:
        if not check_func(record):
            raise param_error
        if _dim != len(record):
            raise ParamError('Whole vectors must have the same dimension')

    return True
```
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by BossZou** [comment]
I see. It's  the following code segment that cause this bug:
```python
if isinstance(value[0], bytes):
        check_func = is_legal_bin_vector
    else:
        check_func = is_legal_vector
```

The corrent code should be:
```python
    if isinstance(value[0], bytes):
        check_func = is_legal_bin_vector
    elif isinstance(value[0], list):
        check_func = is_legal_vector
    else:
        raise param_error
```

This bug will be fixed in pymilvus v0.2.9.

**Comment by BossZou** [comment]
Hello @del-zhenwu , pymilvus v0.2.9 has been released. May you invalidate if the bug already exists.

**Comment by del-zhenwu** [comment]
close
