### ISSUE TITLE
[Bug]: password encryption too slow

### ISSUE THREAD

**Issue by aakejiang** [milvus-io/milvus#17874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: Master
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Go bcrypt is an asymmetric cryptography and very safe in security, while on the other hand is very slow. In the min cost, it spends couples of seconds.

bcrypt.GenerateFromPassword benchmark in min cost
```
BenchmarkPasswordEncrypt-10         1051           1138816 ns/op
```

bcrypt.CompareHashAndPassword benchmark in min cost
```
BenchmarkPasswordVerify-10          1023           1171985 ns/op
```

If the cost be 10 or above, the performance will be worse.

We will use SHA256 for password comparison while still store password encrypted by bcrypt.

```
BenchmarkPasswordVerify-10       7113756               152.7 ns/op           160 B/op          3 allocs/op
```

**Comment by xiaofan-luan** [comment]
did we put this into 2.1 branch?

**Comment by xiaofan-luan** [comment]
@aakejiang ready for the QA to test? pls assign this issue back to yanglinag
