### ISSUE TITLE
[Feature]: Need more information about `consistency_level` in milvus-docs.

### ISSUE THREAD

**Issue by songzhi108** [milvus-io/milvus#17887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I need more info about option `consistency_level` when I make a search.

### Describe the solution you'd like.

1. There are two ways to set the `consistency_level`, "create collection" and "make a search". I think set `consistency_level` when "make a search" is a best practice. Or set it as a "CONST".

2. In the search scenario sometimes we need low latency than data consistency. We should set the default value to `Bounded` instead of `Strong`.

**Comment by longjiquan** [comment]
Hi, @songzhi108 . Thanks for the nice advice. We have already updated the documentation of this internally, but it's not released yet.
As for your questions:
- 1, Yeah, you're right that it's better to set consistency level when we make a search, maybe we should mention this in our docs;
- 2, The default `consistency_level` is `Bounded` instead of `Strong`, if you found any docs mentioned this, please let me know and we'll fix it soon.

**Comment by YiyunNi** [comment]
Hi @songzhi108 , thanks for the suggestion. 

1. Added extra information about the best practice of tuning consistency level in this PR: https://github.com/milvus-io/milvus-docs/pull/1571

2. I have searched through our documentation and did not find any mention of default consistency as `Strong`. Please let me know if any doc is containing this wrong information.

Thank you!

**Comment by songzhi108** [comment]
> Hi @songzhi108 , thanks for the suggestion.
> 
> 1. Added extra information about the best practice of tuning consistency level in this PR: [Add the best practice of tuning consistency milvus-docs#1571](https://github.com/milvus-io/milvus-docs/pull/1571)
> 2. I have searched through our documentation and did not find any mention of default consistency as `Strong`. Please let me know if any doc is containing this wrong information.
> 
> Thank you!

Sorry for Q2, I think it was the code-snap(https://milvus.io/cn/docs/v2.0.x/search.md) mislead me.

**Comment by YiyunNi** [comment]
Added further clarification in this PR: https://github.com/milvus-io/milvus-docs/pull/1587
