### ISSUE TITLE
[Bug]: Load failed after standalone pod kill chaos test 

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#17885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220628-6b79d4f7
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-2.1.0.dev87
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Load failed when running `test_e2e.py` after standalone pod kill chaos test

```
11:42:00  [2022-06-28 03:41:38 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 20], kwargs: {} (api_request.py:55)
11:42:00  [2022-06-28 03:41:58 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)>, <Time:{'RPC start': '2022-06-28 03:41:38.232499', 'RPC error': '2022-06-28 03:41:58.233721'}> (decorators.py:94)
11:42:00  [2022-06-28 03:41:58 - ERROR - ci_test]: Traceback (most recent call last):
11:42:00    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 48, in handler
11:42:00      return func(self, *args, **kwargs)
11:42:00    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 661, in load_collection
11:42:00      response = rf.result()
11:42:00    File "/usr/local/lib/python3.7/dist-packages/grpc/_channel.py", line 744, in result
11:42:00      raise self
11:42:00  grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
11:42:00  	status = StatusCode.DEADLINE_EXCEEDED
11:42:00  	details = "Deadline Exceeded"
11:42:00  	debug_error_string = "{"created":"@1656387718.233283835","description":"Error received from peer ipv4:10.96.213.58:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Deadline Exceeded","grpc_status":4}"
11:42:00  >
11:42:00  
11:42:00  During handling of the above exception, another exception occurred:
11:42:00  
11:42:00  Traceback (most recent call last):
11:42:00    File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
11:42:00      res = func(*args, **kwargs)
11:42:00    File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request
11:42:00      return func(*arg, **kwargs)
11:42:00    File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 469, in load
11:42:00      conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
11:42:00    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 95, in handler
11:42:00      raise e
11:42:00    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 91, in handler
11:42:00      return func(*args, **kwargs)
11:42:00    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 62, in handler
11:42:00      raise MilvusException(Status.UNEXPECTED_ERROR, f"rpc deadline exceeded: {timeout_msg}")
11:42:00  pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)>
11:42:00   (api_request.py:35)
11:42:00  [2022-06-28 03:41:58 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)> (api_request.py:36)
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
see http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/7392/
```

### Milvus Log

failed job: http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/7392/
log: [artifacts-standalone-pod-kill-7392-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9006542/artifacts-standalone-pod-kill-7392-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
failed job: http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/7495/pipeline
log: [artifacts-standalone-pod-kill-7495-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9009186/artifacts-standalone-pod-kill-7495-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
failed job: http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/7507/pipeline
log: [artifacts-standalone-pod-kill-7507-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9016048/artifacts-standalone-pod-kill-7507-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
> failed job: http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/7507/pipeline log: [artifacts-standalone-pod-kill-7507-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9016048/artifacts-standalone-pod-kill-7507-server-logs.tar.gz)

all logs included killed pods
[standalone-pod-kill-7507.zip](https://github.com/milvus-io/milvus/files/9027312/standalone-pod-kill-7507.zip)

**Comment by xiaofan-luan** [comment]
won't fix on it for now, but we will offer a command to force release a collection to solve the problem

**Comment by XuanYang-cn** [comment]
maybe fixed by #18249

**Comment by zhuwenxing** [comment]
here are some failed jobs recently
* https://github.com/milvus-io/milvus/runs/7372380810?check_suite_focus=true
* https://github.com/milvus-io/milvus/runs/7372064437?check_suite_focus=true

**Comment by zhuwenxing** [comment]
> won't fix on it for now, but we will offer a command to force release a collection to solve the problem

Is there such a command that can be used? If so, I can try to add it to the pipeline for verification
