### ISSUE TITLE
[Bug]: drop_collection not working? any other method to delete collection

### ISSUE THREAD

**Issue by rakesh1401** [milvus-io/milvus#17883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

[Bug]: drop_collection not working? any other method to delete collection

### Expected Behavior

[Bug]: drop_collection not working? any other method to delete collection

### Steps To Reproduce

```markdown
[Bug]: drop_collection not working? any other method to delete collection
```

### Milvus Log

[Bug]: drop_collection not working? any other method to delete collection

### Anything else?

[Bug]: drop_collection not working? any other method to delete collection

**Comment by yanliang567** [comment]
@rakesh1401 thank you for the issue, could you please specify "not working"? is there an error msg when calling drop_collection, or the collection is able to be listed even after drop_collection called? Also could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @rakesh1401 
/unassign
