### ISSUE TITLE
[Bug]: querynode balance bug? 

### ISSUE THREAD

**Issue by songzhi108** [milvus-io/milvus#17892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.0.2
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): None.
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: Resource Limit at 2c/2Gi
- GPU: None.
- Others: None.
```

### Current Behavior

![b4d9667022ea8d04a5ca61c65aabf77](https://user-images.githubusercontent.com/91243118/176345200-c9ceb4d3-cef3-4aad-92d8-79506de332a8.png)

In this snapshot, we saw three querynode memory usage is not in balance.

![32eba717e6f69b422e334ed7fb624de](https://user-images.githubusercontent.com/91243118/176345218-3d95e483-5d5b-424c-b569-558fa83cee08.png)

This snapshot tell us we did the Resource Limits in the YAML.

**Comment by yanliang567** [comment]
@songzhi108 how many vectors did you inserted? BTW, querynode balance is not about the data size preciously, it is about the segment counts. According to the Memory Usage snapshot above, I guess you totally have 2 segments, and they were balanced actually.

/assign @songzhi108 
/unassign

**Comment by songzhi108** [comment]
> @songzhi108 how many vectors did you inserted? BTW, querynode balance is not about the data size preciously, it is about the segment counts. According to the Memory Usage snapshot above, I guess you totally have 2 segments, and they were balanced actually.
> 
> /assign @songzhi108 /unassign

Yes, you are right. There are 2 segments in my test env by `get_query_segment_info()` api.
Thank you~
