### ISSUE TITLE
[Bug]: Growing segment may be leaked to offload if the corresponding sealed segment is compacted before handoff done

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#17914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Flushing a segment `s` triggers a handoff task, the growing segment will never be offload if segment `s` is compacted before the handoff task is processed by QueryNode.

**Comment by xiaofan-luan** [comment]
we can simply check release list in shardleader growing list?

**Comment by yah01** [comment]
Now the shard leader offloads growing segments according to both of OnlineSegments and OfflineSegments, this is solved.
