### ISSUE TITLE
[Bug]: similarity change when searching same vector twice

### ISSUE THREAD

**Issue by Roger-Z** [milvus-io/milvus#17969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.2
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):java 
- OS(Ubuntu or CentOS): centos 7
- CPU/Memory: 16C/128GB
- GPU: 
- Others:
```

### Current Behavior

As shown below, score changes for same target vector and source vector, and sequence also change (the fifth record). 
first time:
[{"score":0.2914793,"strID":"","longID":434213119081134550},{"score":0.28723007,"strID":"","longID":434213119081134564},{"score":0.28342956,"strID":"","longID":433936307429600422},{"score":0.28324175,"strID":"","longID":434051991170452987},{"score":0.28290173,"strID":"","longID":434015689862736189} 
...

second time:
[{"score":0.2917078,"strID":"","longID":434213119081134550},{"score":0.28728828,"strID":"","longID":434213119081134564},{"score":0.28324613,"strID":"","longID":433936307429600422},{"score":0.28314242,"strID":"","longID":434051991170452987},{"score":0.28296056,"strID":"","longID":434261571641582146}
...

### Expected Behavior

Sequence of vector list result should not change if we search same vector, and the score for same vector shouldn't change.

**Comment by xiaofan-luan** [comment]
might be related to #17661

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```gfm
> - Milvus version:2.0.2
> - Deployment mode(standalone or cluster):cluster
> - SDK version(e.g. pymilvus v2.0.0rc2):java 
> - OS(Ubuntu or CentOS): centos 7
> - CPU/Memory: 16C/128GB
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> As shown below, score changes for same target vector and source vector, and sequence also change (the fifth record). first time: [{"score":0.2914793,"strID":"","longID":434213119081134550},{"score":0.28723007,"strID":"","longID":434213119081134564},{"score":0.28342956,"strID":"","longID":433936307429600422},{"score":0.28324175,"strID":"","longID":434051991170452987},{"score":0.28290173,"strID":"","longID":434015689862736189} ...
> 
> second time: [{"score":0.2917078,"strID":"","longID":434213119081134550},{"score":0.28728828,"strID":"","longID":434213119081134564},{"score":0.28324613,"strID":"","longID":433936307429600422},{"score":0.28314242,"strID":"","longID":434051991170452987},{"score":0.28296056,"strID":"","longID":434261571641582146} ...
> 
> ### Expected Behavior
> Sequence of vector list result should not change if we search same vector, and the score for same vector shouldn't change.
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

Hi Roger, does it always happen on your cluster? Any  easy way to reproduce?

**Comment by Roger-Z** [comment]
It's our own problem, sorry for the misinformation.
