### ISSUE TITLE
[Bug]: Incorrect calculation of distance in RHNSW_PQ and HNSW indexes.

### ISSUE THREAD

**Issue by andrwtokar** [milvus-io/milvus#17978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.0.2-hotfix-16885
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I generated 10,000 vectors with dimension equal to 512 and they were all normalized to 1. Later I put it into the milvus cluster. I choose the first vector as the target to search and tried to find the 10 most similar vectors.

Vectors was inserted by the next code:
```
data = [
    [i for i in range(NUM_OF_VECTORS)],
    [np.int32(i) for i in range(NUM_OF_VECTORS)],
    [list(arr) for arr in norm_vectors[:NUM_OF_VECTORS]]
]
collection = pymilvus.Collection("Research_metrics")
collection.insert(data)
```

Vectors was searched by the next code:
```
result = collection.search(search_array, "embedding", SEARCH_PARAMS, 10)
```

1. First problem with vectors is in calculating L2 metric in RHNSW_PQ and HNSW:
    I calculate L2 metric using next code:
    ```
    def calc_L2(v1, v2):
        vector = np.array(v1) - np.array(v2)
        return np.sqrt(np.sum(vector ** 2))
    
    py_dists = [calc_L2(target_vector, v2) for v2 in norm_vectors] 
    sorted_dists = sorted(py_dists)
    ```
    and find the most similars:
    ```
    top_k = []
    _K = 10
    
    for elem in sorted_dists[:_K]:
        ind = np.where(py_dists == elem)[0]
        top_k.append({'dist': elem, 'id': data[0][ind[0]]})
    ```
    In result I have a pairs like (distance, id):
    ```
    [{'dist': 0.0, 'id': 0},
     {'dist': 0.6322099272907319, 'id': 3566},
     {'dist': 0.6329032324460313, 'id': 9815},
     {'dist': 0.6350992936345169, 'id': 3943},
     {'dist': 0.6403008236680318, 'id': 9166},
     {'dist': 0.6407730140081191, 'id': 1175},
     {'dist': 0.6417439558193064, 'id': 1181},
     {'dist': 0.642033956310882, 'id': 3951},
     {'dist': 0.6422083261918663, 'id': 932},
     {'dist': 0.6435270469866163, 'id': 5444}]
    ```
    
    But cluster return the next values in both type of index:
    ```
    [(distance: 0.0, id: 0),
     (distance: 0.39968937635421753, id: 3566),
     (distance: 0.4005664885044098, id: 9815),
     (distance: 0.4033510982990265, id: 3943),
     (distance: 0.40998515486717224, id: 9166),
     (distance: 0.4105900526046753, id: 1175),
     (distance: 0.41183531284332275, id: 1181),
     (distance: 0.41220760345458984, id: 3951),
     (distance: 0.412431538105011, id: 932),
     (distance: 0.41412705183029175, id: 5444)]
    ```

    As you can see ids are similar in all ways of calculation, but the distances if different.

2. Second problem is in calculating IP metric in RHNSW_PQ
    When I generated 1 million vectors or more the distances, that was returned from search, are random and
    I calculate IP metric using next code:
    ```
    py_dists_ip = norm_vectors @ target_vector
    sorted_dists_ip = sorted(py_dists_ip)[::-1]
    ```
    and find the most similars. In result I have a pairs like (distance, id):
    ```
       [{'dist': 0.9999993017867349, 'id': 0},
     {'dist': 0.8077163906935895, 'id': 286907},
     {'dist': 0.807411025537698, 'id': 6857},
     {'dist': 0.8046243754434582, 'id': 524375},
     {'dist': 0.8042509088828416, 'id': 968902},
     {'dist': 0.8035942896196975, 'id': 189254},
     {'dist': 0.8033109301806923, 'id': 516414},
     {'dist': 0.8028552072175215, 'id': 809283},
     {'dist': 0.8021161012085138, 'id': 881002},
     {'dist': 0.8020816034756446, 'id': 490389}]
    ```
    But cluster return the next values in the index RHNSW_PQ :
    ```
    [(distance: 0.8042508959770203, id: 968902),
     (distance: 0.8028551936149597, id: 809283),
     (distance: 0.8021161556243896, id: 881002),
     (distance: 0.801440417766571, id: 881575),
     (distance: 0.8013886213302612, id: 814162),
     (distance: 0.8009716868400574, id: 974503),
     (distance: 0.8007720708847046, id: 810870),
     (distance: 0.8003769516944885, id: 815567),
     (distance: 0.7998511791229248, id: 981968),
     (distance: 0.7992445230484009, id: 964928)]
    ```

    This problem only appears in the index RHNSW_PQ. Everything works correctly in HNSW.

### Expected Behavior

I expected the distances manually calculated and returned by the cluster to be equal.

**Comment by andrwtokar** [comment]
> 2. PQ has very low recall rate in our test. You probably want to try RNHSW see if you hit similar issue?

Yes, I can use the HNSW index, but it takes too much memory and I want to try RHNSW_PQ as soon as possible.

When I looked at the knowhere repository, I found that the IP metric is not released for RHNSW_PQ. But it's not listed on the product page.
A little more about the problem: if I put 10 thousand vectors in the index - it works correctly and returns good distances. But if I put more data, the calculation of distances breaks down.

**Comment by xiaofan-luan** [comment]
> 



> 

If you use PQ you will only get 0.3-0.4 recall, which is usually not acceptable.
Try RNHSW-SQ and it will save your memory to only 1/4.

**Comment by cydrain** [comment]
Hi @andrwtokar ,
I see your main question is why the distances manually calculated and returned by the RHNSW_PQ not equal.
This is because in index RHNSW_PQ, the original vector is encoded by Product Quantizer.
You can google some articles about PQ, and you can see this behavior is expected.

RHNSW-PQ really gives smaller index size, but the recall rate is not so good.
I also suggest you to use RHNSW-SQ instead, the memory can be reduced to 1/3, and the recall rate is as good as HNSW.

**Comment by andrwtokar** [comment]
Hi, @cydrain,
I could understand if it was only in the RHNSW_PQ index because of the PQ, but the L2 distance calculation doesn't work in HNSW either.

When I had a problem calculating the IP distance, I first checked the RHNSW_SQ index, and here the metric calculation does not work correctly either.

**Comment by cydrain** [comment]
> Hi, @cydrain, I could understand if it was only in the RHNSW_PQ index because of the PQ, but the L2 distance calculation doesn't work in HNSW either.
> 
Hi @andrwtokar ,
L2 distance formula is like this: (||x||^2 - 2*||x||*||y|| + ||y||^2) ^ 1/2
But in knowhere, in considering of efficiency, we only calculate: ||x||^2 - 2*||x||*||y|| + ||y||^2
It saves a sqrt() operation and will not change the result order.
This can explain why L2 distance is not as your expected

> When I had a problem calculating the IP distance, I first checked the RHNSW_SQ index, and here the metric calculation does not work correctly either.

For IP distance, can you tell me what's not correct ?

**Comment by andrwtokar** [comment]
> In considering of efficiency, knowhere calculates L2 without sqrt() operation. So the L2 distance calculated by knowhere is not the "real" L2 distance(d), it's (d^2), but it will not affect the result ordering.

Thank you for this information. I refined my calculations and got a better result.

> For IP distance, I don't know what you mean "the metric calculation does not work correctly". Before do IP search, you need normalize your vector, have you done that ?

I have 18 million normalized vectors and 1 searchable vector. The result contains distances greater than 1. I collect the ids and distances of these vectors:
```
search_result = collection.search(search_array, "embedding", SEARCH_PARAMS, TOP_K)

# filtered ids and dists where distance greater 1
filtered_ids = [elem.id for elem in search_result[0] if elem.distance > 1]
filtered_dists = np.array([elem.distance for elem in search_result[0] if elem.distance > 1])
```

I requested these embeddings and checked the norm again:
```
expr = "pk in [" + ','.join(map(str, filtered_ids)) + "]"
query_result = collection.query(expr=expr, output_fields=['pk', 'embedding'])

embs = [res['embedding'] for res in query_result] # select embeddings from query
vectors_norma = [np.sqrt(np.sum(np.array(emb) ** 2)) for emb in embs] # calculate norma
vectors_norma = np.array([round(norma, 5) for norma in vectors_norma]) # round to 5 decimal places
---
Statistics on the number of vectors.
  Total: 2294
  Norma less then 1: 0
  Norma greater then 1: 0
  Norma equal 1: 2294
```

In the next step, I calculated the distance using the milvus features:
```
vectors_left = {
    "ids": list(filtered_ids), 
    "collection": COLLECTION, 
    "partition": "_default", 
    "field": "embedding"
}
vectors_right = {"float_vectors": [target_vec]}
params = {
    "metric": SEARCH_PARAMS['metric_type'], 
    "dim": 512
}
results = mv.utility.calc_distance(
    vectors_left=vectors_left, 
    vectors_right=vectors_right, 
    params=params
)

cluster_dists = np.array([elem[0] for elem in results])
```

In result I have different values of distances:
```
filtered_dists[:20]
---
array([1.00000703, 1.00001419, 1.00002015, 1.00003982, 1.00008142,
       1.00013161, 1.00014544, 1.00014842, 1.00020623, 1.00021255,
       1.00021815, 1.00025845, 1.00026309, 1.00030255, 1.00032854,
       1.00032949, 1.00034177, 1.00035501, 1.00035524, 1.00037742])
```
and
```
cluster_dists[:20]
---
array([0.1163904 , 0.43577462, 0.32233223, 0.35023543, 0.35440281,
       0.14156397, 0.13059847, 0.22011338, 0.23046377, 0.04979669,
       0.19178183, 0.22364403, 0.37988421, 0.28458491, 0.24494992,
       0.30483344, 0.25534821, 0.4428899 , 0.18375187, 0.20843443])
```

When I requested the desired vectors and calculated the metric using Python tools, I got the same result as return `mv.utility.calc_distance()`. So the metric is not valid inside the similarity search in the RHNSW_PQ index.

**Comment by cydrain** [comment]
Hi @andrwtokar ,
You're right, we found a bug in RHNSW_PQ, when set metric type to IP, it actually do L2 distance calculation.
That's why you see distance greater than 1.0.
This bug has been fixed in knowhere (https://github.com/milvus-io/knowhere/pull/316).

**Comment by xiaofan-luan** [comment]
leave it until milvus merge it

**Comment by cydrain** [comment]
@yanliang567 knowhere-v1.2.0 has been merged into Milvus, please verify the fix
/assign @yanliang567

**Comment by yanliang567** [comment]
RHNSW is going to off support.
