### ISSUE TITLE
[Bug]: milvus hang cannot process search request after running a while

### ISSUE THREAD

**Issue by WordlessToContinue** [milvus-io/milvus#17998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:  milvusdb/milvus:1.1.1-cpu-d061621-330cc6
- Deployment mode(standalone or cluster):standalone 
- SDK version(e.g. pymilvus v2.0.0rc2):1.1.1
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 64cpus 256GB
- GPU: 
- Others:
```

### Current Behavior

milvus hang cannot process search request after running a while

### Steps To Reproduce

```markdown
1.create 20+ collections , Each collection contains 100000 ~ 1000000 float data, index : HNSW
2.Multithread search for one of the collection
3.milvus hang after a few hours
```

### Milvus Log

milvus begin log
30.2_milvus-22-06-28-19_20-info.log.1 

milvus hang logs
30.2_milvus-22-06-28-19_20-info.log
30.2_milvus-22-06-28-19_20-debug.log

[log.zip](https://github.com/milvus-io/milvus/files/9027474/log.zip)

**Comment by yhmo** [comment]
Looks like a combined search request was hang. Might be a bug of search combine.
Try disable the search combine behavior. In the server_config.yaml, add the two lines:
```
engine_config:
    search_combine_nq: 0
```
Then restart the server.

**Comment by WordlessToContinue** [comment]
I will test it , but won't the performance degrade with this configuration ?

**Comment by WordlessToContinue** [comment]
hang logs as follow
[errorLog.tar.gz](https://github.com/milvus-io/milvus/files/9068739/errorLog.tar.gz)
