### ISSUE TITLE
[Bug]: [memory] Index creation timeout while indexnode OOMKilled, index has already created after indexnode restart

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#18005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.0-20220630-49d9e5fa
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. Deploy milvus cluster and limit indexnode memory 2Gi
2. Create index for 58w 512dim entities and gets timeout exception
3. Indexnode OOMkilled
4. Increase indexnode memory limit and it re-running
5. Describe collection index and it is indexed

[indexnode_pre.log](https://github.com/milvus-io/milvus/files/9027636/indexnode_pre.log)
[indexcoord.log](https://github.com/milvus-io/milvus/files/9027638/indexcoord.log)

[indexnode.log](https://github.com/milvus-io/milvus/files/9027647/indexnode.log)

### Expected Behavior

I don't know if the index is actually built on the milvus server ?

**Comment by yanliang567** [comment]
i think we shall check memory to avoid OOM.

**Comment by xiaocai2333** [comment]
@ThreadDao What is the memory size of IndexNode？ What is the dimensions of the data?

**Comment by ThreadDao** [comment]
> @ThreadDao What is the memory size of IndexNode？ What is the dimensions of the data?

58w 512dim

**Comment by xiaocai2333** [comment]
After the discussion about pr #17878 , we will not check whether the machine configuration of indexnode complies with the conditions for indexing. So users need to ensure that the machine of indexnode can build the index during the test.  @yanliang567 @ThreadDao

**Comment by ThreadDao** [comment]
The new version of index will also have this problem. Of course this is closely related to the pymilvus
