### ISSUE TITLE
[Bug]: Wired Search Behavior in Milvus 2.0.2

### ISSUE THREAD

**Issue by yuliu-eric** [milvus-io/milvus#18012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.2
- Deployment mode(standalone or cluster): Cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.0.2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Background: We have migrated a few collections from Milvus 1.1.0 to Milvus 2.0.2 using the MilvusDM tool, and run a few performance tests.

1. After creating an index, the search latencies are around **30ms** for all the aforementioned migrated collections on Milvus 2.0.2.
2. The day after, we re-run the same test and the search latencies increased to **200ms+** for the same collections.
3. Then we tried to drop the index and re-create the index, but create_index was just hanging there forever.
4. Then we tried to create new collections and insert some random entities, and the search latencies were stable at around 30ms.

**Comment by yanliang567** [comment]
@yuliu-eric thank you for the issue. Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation? BTW, We'd better have logs for both step#1(30ms) and step #2(200ms).

/assign @yuliu-eric 
/unassign

**Comment by yuliu-eric** [comment]
We lost the logs for 30ms in #1, but we do have the logs for steps #2 and #4. Do you have a location where I can upload the logs?

**Comment by yanliang567** [comment]
That's good, could you use google drive or baidu drive for the logs ?

**Comment by yuliu-eric** [comment]
Sure, please try this [link](https://drive.google.com/drive/folders/11wlRLAFq0ly54WwO7F1QLxolP74-t80E) and request access so that I can grant for.

**Comment by yanliang567** [comment]
> Sure, please try this [link](https://drive.google.com/drive/folders/11wlRLAFq0ly54WwO7F1QLxolP74-t80E) and request access so that I can grant for.

Thank you, we got the logs.

**Comment by yuliu-eric** [comment]
We have tried both `Bounded` and `Eventual`, but got the same performances.

**Comment by xiaocai2333** [comment]
> Access granted, please try again.

got it, thanks.

**Comment by yuliu-eric** [comment]
we should have the logs for steps https://github.com/milvus-io/milvus/issues/2 and https://github.com/milvus-io/milvus/pull/4, you don't find them in the logs?

**Comment by xiaocai2333** [comment]
> we should have the logs for steps #2 and #4, you don't find them in the logs?

yes. There is no log after the system has just started up.
![image](https://user-images.githubusercontent.com/46207236/178478002-54454086-49aa-4297-aa62-5a8ca120cd4c.png)

**Comment by yuliu-eric** [comment]
Hmm, we've re-run search tests and saved the logs [here](https://drive.google.com/drive/folders/1ytHDQyS_H2Jpbe4j_q318OFA_7VB_0iv). Please take another look.

**Comment by xiaocai2333** [comment]
> 

@yuliu-eric  Sorry, there is still no corresponding log in the new log file. Can you tell the log level of the your cluster?

**Comment by yuliu-eric** [comment]
I think we don't set any logging configs explicitly. I've uploaded our values.yaml config to the same link above, would you please help to take a look and see if there's any suspicious configurations in the yaml file?

**Comment by xiaocai2333** [comment]
```
log:
  level: "debug"
```

The configuration is correct, but strangely, there is no corresponding log in the log files. 
I will try to reproduce it.

**Comment by xiaocai2333** [comment]
@yuliu-eric This problem is difficult to reproduce, can you use version 2.1 directly?
BTW, is your original data version 1.1.1? Does it have to be kept?

**Comment by yuliu-eric** [comment]
> This problem is difficult to reproduce, can you use version 2.1 directly?

Sure, we can try out 2.1, when do you think 2.1 will be ready?

> BTW, is your original data version 1.1.1? Does it have to be kept?

Yes, original data version is 1.1 and we need to migrate them to 2.x

**Comment by JackLCL** [comment]
> Sure, we can try out 2.1, when do you think 2.1 will be ready?

Yes, it's ready now.

**Comment by yuliu-eric** [comment]
Cool, we will try out the 2.1 version and update back soon.

**Comment by yanliang567** [comment]
close. please file a new one if it reproduced to you in 2.1
