### ISSUE TITLE
[Bug]: Unable to install and start Milvus in one-line code.

### ISSUE THREAD

**Issue by YiyunNi** [milvus-io/milvus#18015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I run the command `docker run --name=milvus -p19530:19530  milvusdb/milvus:v2.0.2 milvus run embedded`, I was unable to start Milvus.
![截屏2022-07-01 18 55 56](https://user-images.githubusercontent.com/74396087/176881779-da1c5dc3-bc98-438e-b947-af10d0a8c15e.png)

### Expected Behavior

When I run the command `docker run --name=milvus -p19530:19530  milvusdb/milvus:v2.0.2 milvus run embedded`, Milvus should be installed and started.

**Comment by haorenfsa** [comment]
Sry, I made a mistake, it's added in v2.1.
