### ISSUE TITLE
The first load of data takes too long && Searching time is unstable.

### ISSUE THREAD

**Issue by shiyu22** [milvus-io/milvus#1805]
**Describe the bug**
The first load of data takes too long && Searching time is unstable.

**Steps/Code to reproduce behavior**
- Num of vectors: 820,000,000
- Dimensions: 2048
- Data Type: bytes
I have three collections, named similarity_table_2048(metric_type=JACCARD), substructure_table_2048(metric_type=SUBSTRUCTURE), superstructure_table_2048(metric_type=SUPERSTRUCTURE), each collection has 820 million data. The first load of data takes more than half an hour. 
The average query time is 2 seconds, but abnormal values often occur, which takes 6-10 seconds.

**Environment details**
- Milvus version V0.7.1-cpu
- Milvus configuration cpu_cache_capacity:700

**Screenshots**
[milvus-20-03-30-16_22-debug.zip](https://github.com/milvus-io/milvus/files/4402438/milvus-20-03-30-16_22-debug.zip)

**Comment by JinHai-CN** [comment]
@scsven @yhmo Check the data loading.
@shengjun1985 Check the searching cost.

**Comment by shengjun1985** [comment]
It is confirmed by shiyu22 that not to use the full cpu cores can lead to stable searching time .
So, this is not a problem.

**Comment by shiyu22** [comment]
Yes, when I set OMP_NUM_THREDS with starting milvus, the searching time stabilized.

**Comment by yhmo** [comment]
Three tables, each table has about 100 data files, and 20GB data.
From the log, the bottle neck is loading data files from disk to cpu memory, each file(2GB) cost about 10~20 seconds.

**Comment by shengjun1985** [comment]
#1928 (fixed in pr1931) has solved the performance of the first load.
And v0.8.0 is 3 times better than v0.7.1.
