### ISSUE TITLE
Search results are inaccurate with shard search.

### ISSUE THREAD

**Issue by wuxiaomei92** [milvus-io/milvus#1806]
**Describe the bug**
I deployed a writable shard and two read-only shards, and created a table with 15 partitions, each with the same data.
When I search, I set nprobe equal to nlist, but the search results are not the same as the single search results.
incorrect results:
![image](https://user-images.githubusercontent.com/15917470/77978808-8a5c7f00-7335-11ea-8f99-9c8e7f7f0a57.png)

correct results:
![image](https://user-images.githubusercontent.com/15917470/77978786-7c0e6300-7335-11ea-8652-401ddc1815d0.png)

**Comment by wuxiaomei92** [comment]
I see why, because the distance I'm using is the inner product, but the distance compare defaults to the Euclidean distance when  merge results.

**Comment by JinHai-CN** [comment]
Ok, close it.
