### ISSUE TITLE
About MacOS Github actions

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#18079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Github has updated MacOS in 6.27.2022, https://github.com/actions/virtual-environments/commit/7ff67b1a39fecb4c7965a305dc715676ecded01, it updated link from `llvm` to `llvm@13`

Github is planning to upgrade llvm to version 14 in July 11 actions/virtual-environments/issues/5835

In order to use ccahe, llvm version in our Github actions has to be fixed, so we should follow this instruction in our action.
```
brew uninstall llvm
brew install llvm@13
```
Since our ccache is broken now, it takes up to 40mins to compile rocksdb, and over 1h for compilation complete.

**Comment by xiaofan-luan** [comment]
is there any plan to fix this?

**Comment by XuanYang-cn** [comment]
**Use a fixed llvm version in Github action to cope with the future upgrade**
```
brew uninstall llvm
brew install llvm@13
```
**Update ccache to reduce compilation time**
1. Change timeout to 90mins
2. Wait until macos action passes and update ccache
3. Change timeout back to 60mins
