### ISSUE TITLE
Memory still rising during searching process

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#1807]
**Describe the bug**
Memory usage rising from 7.8G to 8G.
The usage of memory resources:
# TODO:

**Steps/Code to reproduce behavior**
Keep searching 100,000 times
using dataset: sift-50m
using CPU-version

**Expected behavior**

**Environment details**
master-branch.
with CPU-version.
cpu_cache_size was set an enough value

**Screenshots**

**Additional context**

**Comment by tinkerlin** [comment]
still exist

**Comment by yhmo** [comment]
Use the following code to get memory state before/after search:
```
def print_memory():
    program_name = "milvus_server"
    order_str = "ps x | grep %s" % program_name
    strs_obj = os.popen(order_str)
    t_strs = strs_obj.read()
    pid_list = re.findall(r"(\d+).+server_config.yaml", t_strs, re.I)
    # process = psutil.Process(os.getpid())
    process = psutil.Process(int(pid_list[0]))
    used = process.memory_info().rss / 1024 / 1024
    print(program_name, 'used memory:', used, 'MB')
    return used

    mem = psutil.virtual_memory()
    zj = float(mem.total) / 1024 / 1024
    ysy = float(mem.used) / 1024 / 1024
    kx = float(mem.free) / 1024 / 1024
    print('System total memory: %d MB' % zj)
    print('System used memory: %d MB' % ysy)
    print('System free memory: %d MB' % kx)

def search():
    pre_used = print_memory()
    do_search_100_times()
    post_used = print_memory()
    print("memory cost increase", post_used - pre_used, "MB")
```

50M vectors, dimension:128, index type:IDMAP, metric type:L2, index_file_size:1024MB
Memory increase about 5MB for search 100 times.

**Comment by yhmo** [comment]
Search. 0
memory cost increase 0.2578125 MB
Search. 8
memory cost increase 0.2578125 MB
Search. 9
memory cost increase 0.2578125 MB
Search. 11
memory cost increase 0.2578125 MB
Search. 21
memory cost increase 0.2578125 MB
Search. 22
memory cost increase 0.2578125 MB
Search. 33
memory cost increase 0.2578125 MB
Search. 34
memory cost increase 0.2578125 MB
Search. 40
memory cost increase 0.2578125 MB
Search. 44
memory cost increase 0.2578125 MB
Search. 48
memory cost increase 0.2578125 MB
Search. 55
memory cost increase 0.2578125 MB
Search. 61
memory cost increase 0.2578125 MB
Search. 66
memory cost increase 0.2578125 MB
Search. 71
memory cost increase 0.2578125 MB
Search. 74
memory cost increase 0.2578125 MB
Search. 77
memory cost increase 0.2578125 MB
Search. 87
memory cost increase 0.2578125 MB
Search. 88
memory cost increase 0.2578125 MB
Search. 99
memory cost increase 0.2578125 MB
memory cost totally increase 5.15625 MB
search total time cost: 98.56131339073181 sec

**Comment by yhmo** [comment]
50000000 vectors, dim=128, index type:IVFSQ8, metric type:L2, index_file_size:1024MB
nq=1, nprobe=16, search 100 times:

preload table: AAA
Status(code=0, message='OK')
preload table time cost: 14.274694681167603 sec
preload table memory increase 7782.4609375 MB
Search. 8
memory cost increase 0.25390625 MB
Search. 19
memory cost increase 0.2578125 MB
Search. 29
memory cost increase 0.25390625 MB
Search. 30
memory cost increase 0.2578125 MB
Search. 41
memory cost increase 0.2578125 MB
Search. 52
memory cost increase 0.2578125 MB
Search. 59
memory cost increase 0.2578125 MB
Search. 62
memory cost increase 0.2578125 MB
Search. 73
memory cost increase 0.2578125 MB
Search. 84
memory cost increase 0.2578125 MB
Search. 90
memory cost increase 0.2578125 MB
Search. 95
memory cost increase 0.2578125 MB
search table memory increase 3.0859375 MB
search total time cost: 10.75398063659668 sec

**Comment by yhmo** [comment]
The reason is milvus scheduler cache some task object to reuse, the default cached task object count is 65536. So after query about 2000+ times, the memory will not increase any more.

**Comment by tinkerlin** [comment]
@del-zhenwu regresstion test
