### ISSUE TITLE
[Bug]: [Nightly] Loading  new replica without release does not report error

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#18088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1 branch latest
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.1.0.dev83
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Loading  new replica without release does not report error: successfully

### Expected Behavior

Report error:
ct.err_code: 5, ct.err_msg: f"Should release first then reload with the new number of replicas"

### Steps To Reproduce

Nightly: 
https://ci.milvus.io:18080/jenkins/blue/rest/organizations/jenkins/pipelines/milvus-release-nightly/runs/136/nodes/215/steps/239/log/?start=0

```python
   def test_load_replica_change(self):
        """
        target: test load replica change
        method: 1.load with replica 1
                2.load with a new replica number
                3.release collection
                4.load with a new replica
        expected: The second time successfully loaded with a new replica number
        """
        # create, insert
        collection_w = self.init_collection_wrap(cf.gen_unique_str(prefix))
        df = cf.gen_default_dataframe_data()
        insert_res, _ = collection_w.insert(df)
        assert collection_w.num_entities == ct.default_nb

        collection_w.load(replica_number=1)
        for seg in self.utility_wrap.get_query_segment_info(collection_w.name)[0]:
            assert len(seg.nodeIds) == 1

        collection_w.query(expr=f"{ct.default_int64_field_name} in [0]")
        loading_progress, _ = self.utility_wrap.loading_progress(collection_w.name)
        assert loading_progress == {'loading_progress': '100%', 'num_loaded_partitions': 1, 'not_loaded_partitions': []}

        # verify load different replicas thrown an exception
        error = {ct.err_code: 5, ct.err_msg: f"Should release first then reload with the new number of replicas"}
        collection_w.load(replica_number=2, check_task=CheckTasks.err_res, check_items=error)
```

### Milvus Log

1. milvus log
[milvus-distributed-pulsar-136-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-release-nightly/136/artifact/milvus-distributed-pulsar-136-pymilvus-e2e-logs.tar.gz)
2. collection name: collection_GZ8F6Kxv
3. FAILED time:
[2022-07-05T23:46:06.630Z] [gw1] [ 11%] FAILED testcases/test_collection.py::TestLoadCollection::test_load_replica_change

**Comment by binbinlv** [comment]
It occurs in both 2.1 branch and master, so set it as urgent.

**Comment by yah01** [comment]
/assign @bigsheeper 
#18074 introduced break changes to the loading interfaces

**Comment by bigsheeper** [comment]
after https://github.com/milvus-io/milvus/issues/18100 fixed，I‘ll remove the load check when LoadCollection in Proxy

**Comment by binbinlv** [comment]
So now this issue is blocked by #18100

**Comment by binbinlv** [comment]
Fixed， so close it.
