### ISSUE TITLE
[Bug]: [benchmark][cluster]kafka has a higher latency than pulsar in the search, query, load interface

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#18107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.1.0dev87
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo
test-etcd-no-clean-trj4s-1
server-configmap
server-cluster-8c64m-datanode2-indexnode4-querynode6-kafka
client-configmap
client-random-locust-search-60h-1b

master-20220624-23040449
pymilvus 2.1.0dev87

argo
test-etcd-no-clean-582t5-1
server-configmap
server-cluster-8c64m-datanode2-indexnode4-querynode6
client-configmap
client-random-locust-search-60h-1b

pymilvus 2.1.0dev87
2.1.0-20220701-b3a1a60f

query：
kafka
<img width="1376" alt="截屏2022-07-06 15 31 35" src="https://user-images.githubusercontent.com/34296482/177494833-dc4d7de2-d0b0-4b22-94a9-8a6881af184f.png">

pulsar：
<img width="1375" alt="截屏2022-07-06 15 34 24" src="https://user-images.githubusercontent.com/34296482/177495434-e0bdd2c1-28f0-4c66-aa52-3a773592a263.png">

load：
kafka
<img width="1380" alt="截屏2022-07-06 15 36 34" src="https://user-images.githubusercontent.com/34296482/177495974-cbda1ffc-5513-45d4-be2b-c40adbb06bd7.png">
pulsar：
<img width="1368" alt="截屏2022-07-06 15 37 06" src="https://user-images.githubusercontent.com/34296482/177495994-790dd58a-1a12-41db-be5d-7bfabacc4bd7.png">

search：
kafka：
<img width="1355" alt="截屏2022-07-06 15 38 14" src="https://user-images.githubusercontent.com/34296482/177496180-a843f963-11d4-437c-baf7-a099d7589ff1.png">

pulsar：
<img width="1372" alt="截屏2022-07-06 15 37 46" src="https://user-images.githubusercontent.com/34296482/177496204-1dacce35-1644-437a-9686-2c2301424418.png">

**Comment by yanliang567** [comment]
looks like search with kafka is 50% slower than it with pulsar, @czs007 could you please take a look?

/assign @czs007 
/unassign

**Comment by xiaofan-luan** [comment]
doesn't really make sense to me, we didn't rely to much on stream storage in read path right now
