### ISSUE TITLE
[Bug]:  Ram usage and manuelly docker starting every container down

### ISSUE THREAD

**Issue by umitkarakas123** [milvus-io/milvus#18155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.2
- Deployment mode(standalone or cluster): cluster 
- SDK version(e.g. pymilvus v2.0.0rc2): v2.0.2
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 4 / 18134528
```

### Current Behavior

my query nodes are down all the time. I have to open it manually every time. currently, all my services are working, but I can't write collection. i noticed that query nodes use a lot of ram, and my ram is full. what should I do if query nodes don't use this much ram?

here is my logs....

### Milvus Log

[
[querycoord_logs.txt](https://github.com/milvus-io/milvus/files/9063732/querycoord_logs.txt)

### Anything else?
[querynode_logs.txt](https://github.com/milvus-io/milvus/files/9063858/querynode_logs.txt)

_No response_

**Comment by umitkarakas123** [comment]
is there any update @yanliang567 ??

**Comment by yanliang567** [comment]
@umitkarakas123 it is not easy to address the issue as we did not reproduce it locally. Do you have any chance to check it on 2.1.0 build?

**Comment by umitkarakas123** [comment]
now my rootcord exited and here is rootcord logs;  @yanliang567 

`[2022/07/19 15:00:03.536 +00:00] [DEBUG] [session_util.go:86] ["Session try to connect to etcd"]
[2022/07/19 15:00:03.536 +00:00] [DEBUG] [root_coord.go:791] ["RootCoord connected to QueryCoord"]
[2022/07/19 15:00:03.536 +00:00] [DEBUG] [session_util.go:101] ["Session connect to etcd success"]
[2022/07/19 15:00:03.539 +00:00] [DEBUG] [session_util.go:175] ["Session get serverID success"] [key=id] [ServerId=60]
[2022/07/19 15:00:03.539 +00:00] [INFO] [base_table.go:425] ["Set log file to "] [path=]
[2022/07/19 15:00:03.539 +00:00] [DEBUG] [root_coord.go:990] ["RootCoord, Connecting to Etcd"] ["kv root"=by-dev/kv] ["meta root"=by-dev/meta]
[2022/07/19 15:00:03.544 +00:00] [DEBUG] [meta_table.go:239] ["reload meta table from KV successfully"]
[2022/07/19 15:00:03.544 +00:00] [DEBUG] [root_coord.go:996] ["RootCoord, Setting TSO and ID Allocator"]
[2022/07/19 15:00:03.549 +00:00] [INFO] [tso.go:121] ["sync and save timestamp"] [last=2022/07/19 14:49:09.275 +00:00] [save=2022/07/19 15:00:06.544 +00:00] [next=2022/07/19 15:00:03.544 +00:00]
[2022/07/19 15:00:03.550 +00:00] [INFO] [tso.go:121] ["sync and save timestamp"] [last=2022/07/19 14:49:09.276 +00:00] [save=2022/07/19 15:00:06.549 +00:00] [next=2022/07/19 15:00:03.549 +00:00]
[2022/07/19 15:00:03.557 +00:00] [DEBUG] [dml_channels.go:71] ["init dml channels"] [num=256]
[2022/07/19 15:00:03.564 +00:00] [DEBUG] [dml_channels.go:71] ["init dml channels"] [num=256]
time="2022-07-19T15:00:03Z" level=info msg="[Connecting to broker]" remote_addr="pulsar://172.16.66.23:6650"
time="2022-07-19T15:00:03Z" level=info msg="[TCP connection established]" local_addr="172.16.66.24:55766" remote_addr="pulsar://172.16.66.23:6650"
time="2022-07-19T15:00:03Z" level=info msg="[Connection is ready]" local_addr="172.16.66.24:55766" remote_addr="pulsar://172.16.66.23:6650"
time="2022-07-19T15:00:03Z" level=info msg="[Connecting to broker]" remote_addr="pulsar://172.16.66.23:6650"
time="2022-07-19T15:00:03Z" level=info msg="[TCP connection established]" local_addr="172.16.66.24:55770" remote_addr="pulsar://172.16.66.23:6650"
time="2022-07-19T15:00:03Z" level=info msg="[Connection is ready]" local_addr="172.16.66.24:55770" remote_addr="pulsar://172.16.66.23:6650"
time="2022-07-19T15:00:04Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:04Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:04Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:04Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:04Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:04Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:05Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:05Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:07Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:07Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:10Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:10Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:13Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:13Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:16Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:16Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:19Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:19Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:22Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:22Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:25Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:25Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:28Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:28Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:31Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:31Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:34Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:34Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:37Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:37Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:40Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:40Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:43Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:43Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:46Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:46Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:49Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:49Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:52Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
time="2022-07-19T15:00:52Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded" topic="persistent://public/default/by-dev-rootcoord-dml_0"
panic: Failed to create producer by-dev-rootcoord-dml_0, error = All attempts results:
attempt #1:server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded
attempt #2:server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded
attempt #3:server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded
attempt #4:server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded
attempt #5:server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded
attempt #6:server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded
attempt #7:server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded
attempt #8:server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded
attempt #9:server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded
attempt #10:server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded
attempt #11:server error: ProducerBlockedQuotaExceededError: Cannot create producer on topic with backlog quota exceeded


goroutine 130 [running]:
github.com/milvus-io/milvus/internal/msgstream.(*mqMsgStream).AsProducer(0xc0004e36c0, 0xc000444e10, 0x1, 0x1)
	/go/src/github.com/milvus-io/milvus/internal/msgstream/mq_msgstream.go:124 +0x278
github.com/milvus-io/milvus/internal/rootcoord.(*dmlChannels).addChannels(0xc0000b6e70, 0xc000599b20, 0x2, 0x2)
	/go/src/github.com/milvus-io/milvus/internal/rootcoord/dml_channels.go:163 +0x1b1
github.com/milvus-io/milvus/internal/rootcoord.newTimeTickSync(0x36693d0, 0xc0002303c0, 0x3c, 0x3669c20, 0xc000232fc0, 0xc00063e3f0, 0x0)
	/go/src/github.com/milvus-io/milvus/internal/rootcoord/timeticksync.go:97 +0x459
github.com/milvus-io/milvus/internal/rootcoord.(*Core).Init.func2()
	/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:1033 +0xbaf
sync.(*Once).doSlow(0xc00012ec28, 0xc000157c68)
	/usr/local/go/src/sync/once.go:68 +0xec
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
github.com/milvus-io/milvus/internal/rootcoord.(*Core).Init(0xc00012eb00, 0x368ad08, 0xc00000f548)
	/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:961 +0x2a5
github.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).init(0xc000654630, 0x83483e, 0xc000112408)
	/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:219 +0x612
github.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).Run(0xc000654630, 0x0, 0x0)
	/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:138 +0x2f
github.com/milvus-io/milvus/cmd/components.(*RootCoord).Run(0xc000230400, 0xffffffffffffffff, 0x8)
	/go/src/github.com/milvus-io/milvus/cmd/components/root_coord.go:54 +0x33
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runRootCoord.func1(0xc00063f700, 0x36693d0, 0xc0005f42c0, 0xc0000109c8, 0xc000112400)
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:115 +0x11b
created by github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runRootCoord
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:97 +0xb0
`

**Comment by yanliang567** [comment]
did you upgrade 2.0.2 to 2.1 or install a new 2.1 milvus completely?

**Comment by umitkarakas123** [comment]
ı using docker compose.yml so using like this; 
[dependencies.yml.txt](https://github.com/milvus-io/milvus/files/9147612/dependencies.yml.txt)

**Comment by umitkarakas123** [comment]
every deploy this coords yml, rootcoord exited all the time
[coords.yml.txt](https://github.com/milvus-io/milvus/files/9147720/coords.yml.txt)  

@yanliang567

**Comment by yanliang567** [comment]
@LoveEachDay could you please help on this ?
/assign @LoveEachDay 
/unassign
