### ISSUE TITLE
[Bug]: can't getEntityByID or deleteEntityByID in _default partition by java sdk

### ISSUE THREAD

**Issue by broken-blade** [milvus-io/milvus#18174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 1.1.1
- Deployment mode(standalone or cluster):standalone 
- SDK version(e.g. pymilvus v2.0.0rc2): java v1.1.0
- OS(Ubuntu or CentOS): windows
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Hi guys!
I have already insert one vector into milvus by java sdk **without specifying partition**,and I can get search result with this vector.
Now there has some problems that really confused me:
1. when I use getEntityByID to get this vector(withPartitionTag("_default")), it returns `Response {code = UNEXPECTED_ERROR, message = "Collection or partition is empty"}`; 
2. when I use  deleteEntityByID to delete this vector(withPartitionTag("_default")),it returns `Response {code = SUCCESS, message = "Success!"}`, but i can still search this vector
3. when I use python sdk(pymilvus==1.1.2) to get or delete this vetcor, it works
4. when I insert vector with specific partition, then i can get or delete this vector with java sdk

I'm new to milvus,if I made some low-level mistake,please let me know,thanks!
 

### Steps To Reproduce

```markdown
1.install milvus 1.1.1 by docker(follow this guide:https://milvus.io/cn/docs/v1.1.1/milvus_docker-cpu.md)
2.create milvus client 
3.insert vector(dimension 256) and serch this vector by itself
4.get entity by id
5.delete by id and search this vector by itself
```

**Comment by yanliang567** [comment]
@broken-blade thank you for the issue. We recommend you try Milvus 2.0, which is more powerful. 

/assign @yhmo 
/unassign

**Comment by broken-blade** [comment]
> @broken-blade thank you for the issue. We recommend you try Milvus 2.0, which is more powerful.
> 
> /assign @yhmo /unassign

Thanks for your reply! I will try it later!

**Comment by broken-blade** [comment]
After comparing python and java sdk, I found that python sdk doen't need partition param, so i use an empty string("") instead of _default in java sdk, and it can successfully get or delete by id.

**Comment by yhmo** [comment]
> After comparing python and java sdk, I found that python sdk doen't need partition param, so i use an empty string("") instead of _default in java sdk, and it can successfully get or delete by id.

Maybe is a bug of java sdk 1.1
