### ISSUE TITLE
[Bug]: BulkLoad add new segment with MsgPosition of no offset and timestamp 

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#18172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

the add segment is triggered by datacoord, with no offset and time in Msgposition.
1) How did we handle with segment failover? should we has a special Msgposition which means no need to recovery?
2) can we handle delete bulkloaded data as expected? what about failover?

**Comment by soothing-rain** [comment]
Upon last discussion, the solution is to send a message to DML channel to get the position. Similar to what we do while creating collection:
https://github.com/milvus-io/milvus/blob/fcb5db0e2772b5d69b90d1aaeefacdb3b0e68545/internal/rootcoord/task.go#L237-L254


We haven't quite started working on it yet tho.

**Comment by yanliang567** [comment]
any updates ? @wayblink

**Comment by wayblink** [comment]
> any updates ? @wayblink 
Bulkload related issue is handling in a separate branch. This issue has been resolved. will merge into master after all bulkload refactor is done.
