### ISSUE TITLE
Duplicate data generated after restart milvus server

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#1818]
**Describe the bug**
Duplicate data generated after restart milvus server

**Steps/Code to reproduce behavior**
1. Create a collection, dimension = 128, metric = L2, index_file_size = 1024
2. Insert 10000 vectors
3. Create index IVFSQ8
4. Stop milvus server
5. Start milvus server

result:
The collection has 20000 vectors

**Comment by del-zhenwu** [comment]
`flush_lsn` in `TableFiles` should not be 0

**Comment by yhmo** [comment]
already fixed in 0.7.1
