### ISSUE TITLE
[Enhancement]: GetCompactionState and GetCompactionStateWithPlans has very weird behaviour

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#18190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

currently these two interface is relied by ci test.
But there are several problems make the interface not stable
1. all task state is not persistent, if datacoord crash then we have no idea about previous plans.
2. we don't know when to clean up the task map
3. the interface is weird to users, and I'm not sure why we have two interfaces for GetCompactionState and GetCompactionStateWithPlans

**Comment by xiaocai2333** [comment]
My thoughts are the same as discussed before. When the planID is not found when getting the compacting state, the task is considered complete.
For DataCoord down, there are three cases:
1. After DataCoord restarts, it successfully receives the notification of the completion of the compaction task, then  completes the task.
2. Before DataCoord restarts, the SDK receives a timeout response, and user decides whether to retry or not.
3. After DataCoord restarts, it does not receive the notification of task completion, and the SDK has not timed out, but PlanID doesn't exist anymore, returns success to the user.

For segment has a reference lock:
1. If a segment has a reference lock when the compaction task starts or completes, it will directly return the compaction success to the user.

For completed tasks, we can delete them directly from meta. Or to be more reliable, add a retention time to the task, and clear it from the meta after the task is completed and the retention time is exceeded.
