### ISSUE TITLE
[Enhancement]: Design consistency level and time travel jointly

### ISSUE THREAD

**Issue by letian-jiang** [milvus-io/milvus#18223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

There are two timestamps related to search (and query), guarantee timestamp and time-travel timestamp. I illustrate the faulty situation with an example.

In the current Milvus implementation, if a user sends a search request (strong consistency and no time travel) to the proxy, the proxy would ask TSO for a time-stamp as the request's guarantee timestamp. But the time-travel timestamp would be the maximum uint64 (i.e. the largest timestamp). This discrepancy leads to searching returns results "in the future", which violates the common notion of strong consistency (aka. linearizability).

This issue proposes a joint design on consistency level and time travel.
* In most cases, the guarantee timestamp and the time-travel timestamp should be identical.
* Only in bounded consistency-level, we relax the requirement of guarantee timestamp by subtracting it a configurable graceful time.
* Timetravel and the customized consistency level should refer to the same thing.

### Anything else?

Strong consistency: proxy asks TSO for a search timestamp
- guarantee timestamp = search timestamp
- timetravel timestamp = search timestamp

Session consistency: SDK sends last-write timestamp
- guarantee timestamp = last-write timestamp
- timetravel timestamp = last-write timestamp

Bounded consistency: proxy asks TSO for a search timestamp
- guarantee timestamp = search timestamp - graceful time (relaxed in terms of graceful time)
- timetravel timestamp = search timestamp

Customized consistency (aka. timetravel), user sends timetravel' timestamp
- guarantee timestamp = timetravel' timestamp
- timetravel timestamp = timetravel' timestamp

**Comment by xiaofan-luan** [comment]
1. for strong consistency, we just guarantee all data can be seen if it is written before a certain timestamp, and we didn't check if follows certain Mvcc.  I think read future data is ok, unless user ask to read a specified snapshot? 

2. if user want to a accurate snapshot, then guarantee timestamp = timetravel timestamp

the semantic we deliver:
data <= guarantee timestamp must be seen
data >=  timetravel timestamp must not be seen.
if guarantee = timetravel, then it means to get the exact snapshot at certain ts

**Comment by xiaofan-luan** [comment]
Just check the definition of Consistency,
read the write after read happened definitely doesn't match serial consistency.
We need to change it.
Also, I would recommend to change the name of guarantee ts and  timetravel ts, to make it easiar to understand by users

**Comment by letian-jiang** [comment]
> Just check the definition of Consistency, read the write after read happened definitely doesn't match serial consistency. We need to change it. Also, I would recommend to change the name of guarantee ts and timetravel ts, to make it easiar to understand by users

Yes. I think search timestamp + delta for relaxation is clarifying enough.

**Comment by letian-jiang** [comment]
Additional notes:
* search/query timestamp = time-travel timestamp
* delta = time-travel timestamp - guarantee timestamp
