### ISSUE TITLE
[Feature]: Support pulsar authentication using tokens

### ISSUE THREAD

**Issue by cfreebuf** [milvus-io/milvus#18228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

When deploy milvus with external pulsar cluster provided by other team,
we meet the problem that milvus does not support pulsar auth,
but for security it's recommend to enable auth for pulsar cluster.
so will milvus support pulsar auth later?

**Comment by xiaofan-luan** [comment]
good suggestions, mark it as good first issue~

**Comment by xiaofan-luan** [comment]
We also want to support user specified tenant and namespace
