### ISSUE TITLE
[Bug]: Milvus eventual consistency violated

### ISSUE THREAD

**Issue by psc0606** [milvus-io/milvus#18233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.1
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus v2.0.0rc2, java-sdk 2.0.4
- OS(Ubuntu or CentOS): CentOS 7
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Easy to replay, when I do, simulate update operation:
1. delete by primary id;
2. then insert the same id imedilately;
3. query within another request

result:  both of the clients tell  me successfully by log.
Both of two clients can not query the data any more.
Both of two clients, get the total number of collection items,  give me error number (always incr).

**Comment by yanliang567** [comment]
I believe this was fixed in master (milvus 2.1). @ThreadDao could you please help to double confirm that?

/assign @ThreadDao 
/unassign

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```gfm
> - Milvus version: 2.0.1
> - Deployment mode(standalone or cluster): cluster
> - SDK version(e.g. pymilvus v2.0.0rc2):pymilvus v2.0.0rc2, java-sdk 2.0.4
> - OS(Ubuntu or CentOS): CentOS 7
> - CPU/Memory: 
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> Easy to replay, when I do, simulate update operation:
> 
> 1. delete by primary id;
> 2. then insert the same id imedilately;
> 3. query within another request
> 
> result: both of the clients tell me successfully by log. Both of two clients can not query the data any more. Both of two clients, get the total number of collection items, give me error number (always incr).
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

Milvus can not get the correct entity number while delete, since the num entity is simply a meta estimation.

**Comment by xiaofan-luan** [comment]
This is a known a issue and we will fix it in later version.
