### ISSUE TITLE
[Feature]:Load and release partitions dynamically

### ISSUE THREAD

**Issue by Sivannnnnn** [milvus-io/milvus#18242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

In milvus2.0.2, I created multiple partitions under a collection. In my actual production environment, I added data every day. I set one partition per day. The first time I load ten partitions into memory, and then when I load another partition into memory, Milvus will report an error,

`pymilvus.client.exceptions.BaseException: <BaseException: (code=5, message=some partitions [434533531536326657] of collection 434533531523157313 has been loaded into QueryNode, please release partitions firstly [LoadParametersMismatch])>`

I want to implement the function of loading or releasing partitions at will. When will it be implemented？

**Comment by xiaofan-luan** [comment]
yep, we already has the plan to do so~ it is probably released 4-5 months

**Comment by xiaofan-luan** [comment]
I thought @bigsheeper could follow up the issue

**Comment by xiaofan-luan** [comment]
keep it open, this should be done once flow graph sharing task done

**Comment by SamSamhuns** [comment]
Hi, were there any updates to this? Especially regarding which version of Milvus will support this dynamic load/release. Related to the issue I created in the [pymilvus repo](https://github.com/milvus-io/pymilvus/issues/1500)

**Comment by xiaofan-luan** [comment]
> Hi, were there any updates to this? Especially regarding which version of Milvus will support this dynamic load/release. Related to the issue I created in the [pymilvus repo](https://github.com/milvus-io/pymilvus/issues/1500)

Hi Sam,
Dynamic partition load/release will be supported on Milvus 2.3. Targeting at June 20th

**Comment by SamSamhuns** [comment]
Thank you!
