### ISSUE TITLE
[Bug]: LoadCollection request for loaded collection would be blocked by Handoff

### ISSUE THREAD

**Issue by bigsheeper** [milvus-io/milvus#18258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

LoadCollection request for loaded collection would be blocked by Handoff, and load collection would be timeout.

Also see at VDC issue 582.

**Comment by xiaofan-luan** [comment]
why would handoff block load? My guess is handoff only executed in a few seconds?

**Comment by bigsheeper** [comment]
> why would handoff block load? My guess is handoff only executed in a few seconds?

Handoff is blocked by loadSegments in QueryNode, QueryNode costs about 3~4 seconds on `FromDmlLoadDelete` when load segments. And yes you're right, handoff only executed in a few seconds, but there are multiple concurrent loadCollection requests from 20 clients in VDC-581 case, a few seconds is fatal for these loadCollection requests.
