### ISSUE TITLE
[Bug]:  Use the inserted data to search, can not get the origin data when metric is IP

### ISSUE THREAD

**Issue by nameczz** [milvus-io/milvus#18265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:milvus-dev imageid:238d4d48b454
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):node sdk
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

the data i am using is 0_id, when metric is L2 is working fine. When metric is IP, distance is 12.
Collection schema: 
<img width="1688" alt="image" src="https://user-images.githubusercontent.com/20559208/178681690-80e1faa0-5541-4b5a-b2b9-ad7f236ea6c3.png">
Search result when metric is L2:
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/20559208/178681548-aca7d2ff-3c5a-4d34-9e1a-473d2bbae0f1.png">
Search result when metric is IP:
![HxJ3KqVpQL](https://user-images.githubusercontent.com/20559208/178686686-02f26cf7-2db5-4981-878a-7bd562d539d7.jpg)

### Expected Behavior

Search can get the origin data when metric is IP .

### Steps To Reproduce

```markdown
1. create collection
2. insert mock data
3. search with the insert data
```

**Comment by longjiquan** [comment]
Try normalize the vectors

**Comment by longjiquan** [comment]
![image](https://user-images.githubusercontent.com/31589260/178692297-a185af18-9e24-4f36-b6ce-af618576e2fb.png)

This pictures illustrate why the topk results differ between different metric types.

With L2, of course, distance between `OA` and itself is 0, so it's hit in top0. However, with IP, the distance between `OA` and `OB` is greater than the distance between `OA` and itself.

**Comment by nameczz** [comment]
> Try normalizing the vectors. @nameczz

thanks, i think it's the reason, close this issue.
