### ISSUE TITLE
[DOC] 0.5.1 readme version badge need to be updated

### ISSUE THREAD

**Issue by JinHai-CN** [milvus-io/milvus#183]
## Report incorrect documentation

**Location of incorrect documentation**
README.md && README_CN.md

**Describe the problems or issues found in the documentation**
badge version

**Steps taken to verify documentation is incorrect**
open 0.5.1 branch

**Suggested fix for documentation**
change it to 0.5.1

**Comment by jielinxu** [comment]
Done.
