### ISSUE TITLE
[Bug]: everything seemed normal, but can't search, timeout and no return ..

### ISSUE THREAD

**Issue by wangfeifans** [milvus-io/milvus#18303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.2
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 32core/128g
- GPU: 
- Others:
```

### Current Behavior

all pods is ok . but cat 't can't search.
how to check and fix ?

### Milvus Log
[log is here](http://tpapi.iprtt.com/logs.tar.gz)
_No response_

**Comment by wangfeifans** [comment]
[logs](http://tpapi.iprtt.com/logs.tar.gz) 
add logs.

**Comment by yanliang567** [comment]
@wangfeifans it reports a security issue when trying to download the logs you attached. could you please retry to upload it ?

/assign @wangfeifans 
/unassign

**Comment by wangfeifans** [comment]
> @wangfeifans it reports a security issue when trying to download the logs you attached. could you please retry to upload it ?
> 
> /assign @wangfeifans /unassign

here >>
http://tpapi.iprtt.com/logs.tar.gz

can you download this link？

**Comment by yanliang567** [comment]
No, failed for the same security issue. @wangfeifans

**Comment by wangfeifans** [comment]
> No, failed for the same security issue. @wangfeifans
try ..
[logs](https://feeapi.iprtt.com/logs.tar.gz)

**Comment by yanliang567** [comment]
@soothing-rain could you please help to take a look at this issue. come to me if you also fail to download the logs.

/assign @soothing-rain 
/unassign
