### ISSUE TITLE
[Feature]: Decrease the rocksmq data usage for milvus standalone

### ISSUE THREAD

**Issue by LoveEachDay** [milvus-io/milvus#18304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

PR #15840 brings data compression for data in `minio`, this data usage decrease is very impressive. But the data usage for `rocksmq` is very large. 

Here we create a milvus standalone with 100 million vector data, 128 dimension, index type `ivfsq8`, and the data usage for `minio` is about `26GB`, while the data usage for `rocksmq` is about `163GB`. 

We'd like to decrease the `rocksmq` data usage.

### Describe the solution you'd like.

1. data compression in rocksmq
2. decrease the default `retention` parameters for rocksmq

**Comment by LoveEachDay** [comment]
Check out the issue #18288 where user have 206GB for `rocksmq` .

**Comment by xiaofan-luan** [comment]
I will take a look about rocksb compression, compaction, ttl and other retention related infos
