### ISSUE TITLE
[Bug]: Segment may not be released

### ISSUE THREAD

**Issue by bigsheeper** [milvus-io/milvus#18310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When add the segment with the same segmentID, the newSegment wouldn't be charged by metaReplica, and would never be released.

**Comment by xiaofan-luan** [comment]
good catch! this may cause serious memory leak
