### ISSUE TITLE
[Bug]: Search failed when running `hello_milvus.py` with error `attempt #1:fail to get shard leaders from QueryCoord: no replica available` after many pod kill chaos test 

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#18316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220718-f7bd054a
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.1.0.dev99
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search failed when running `hello_milvus.py` with error `attempt #1:fail to get shard leaders from QueryCoord: no replica available` after many pod kill chaos test 
```
Traceback (most recent call last):
  File "chaos/scripts/hello_milvus.py", line 1[23](https://github.com/milvus-io/milvus/runs/7395778203?check_suite_focus=true#step:14:24), in <module>
    hello_milvus(args.host)
  File "chaos/scripts/hello_milvus.py", line 97, in hello_milvus
    res = collection.search(
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 712, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 95, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 91, in handler
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 73, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 446, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 410, in _execute_search_requests
    raise pre_err
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line [40](https://github.com/milvus-io/milvus/runs/7395778203?check_suite_focus=true#step:14:41)1, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
attempt #1:fail to get shard leaders from QueryCoord: no replica available
attempt #2:fail to get shard leaders from QueryCoord: no replica available
attempt #3:fail to get shard leaders from QueryCoord: no replica available
attempt #4:fail to get shard leaders from QueryCoord: no replica available
attempt #5:fail to get shard leaders from QueryCoord: no replica available
attempt #6:fail to get shard leaders from QueryCoord: no replica available
attempt #7:fail to get shard leaders from QueryCoord: no replica available
attempt #8:context deadline exceeded
```

### Steps To Reproduce

```markdown
see https://github.com/milvus-io/milvus/runs/7395778203?check_suite_focus=true
```

### Milvus Log

standalone pod kill
failed job:https://github.com/milvus-io/milvus/runs/7395778203?check_suite_focus=true
log: https://github.com/milvus-io/milvus/suites/7408839986/artifacts/302152242

etcd pod kill
failed job: http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/8439/pipeline/
log: [artifacts-etcd-pod-kill-8439-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9136751/artifacts-etcd-pod-kill-8439-server-logs.tar.gz)

### Anything else?

This issue should be introduced by PR on Jul 18, 2022, probably https://github.com/milvus-io/milvus/pull/18250

**Comment by zhuwenxing** [comment]
This reproduced stably， see https://github.com/milvus-io/milvus/actions/runs/2692378331， the failed job all failed for the same reason as this issue

**Comment by zhuwenxing** [comment]
@xiaofan-luan 
Can you please take a look, this issue may be related to the PR https://github.com/milvus-io/milvus/pull/18250

**Comment by weiliu1031** [comment]
this issue my be related to https://github.com/milvus-io/milvus/issues/18178

**Comment by zhuwenxing** [comment]
I have tried with two images `master-20220718-638f6c36` and `master-20220718-c9756359`, and it works well on `master-20220718-638f6c36` and have the same issue on  `master-20220718-c9756359`.
So It is basically confirmed that this issue was introduced by PR https://github.com/milvus-io/milvus/pull/18250

**Comment by zhuwenxing** [comment]
It still happened in version `master-20220721-a6e1ddb5`

failed job: https://github.com/zhuwenxing/milvus/runs/7443664045?check_suite_focus=true
log: [logs-standalone](https://github.com/zhuwenxing/milvus/suites/7454035644/artifacts/305097703)

**Comment by zhuwenxing** [comment]
If reloads before the search, this issue seems will not happen.
In the deploy test, search works well after reinstall, because the collection reloaded, but if the collection was not reloaded, this issue will also happen. see https://github.com/zhuwenxing/milvus/actions/runs/2718590326

**Comment by xige-16** [comment]
failed job
https://github.com/milvus-io/milvus/actions/runs/2777041289

**Comment by yanliang567** [comment]
@xige-16 @xiaofan-luan any updates for this? It blocks our nightly compatibility and upgrade tests. please take it a high priority.

**Comment by xige-16** [comment]
The sourceNodeID of the balance task is inconsistent with the nodeID of the down node
```
[querycoord/query_coord.go:371] ["find querynode down while coord not alive"] [nodeIDs="[82,57,66,98,49,74,89,42,10,25,34,18,106,114,121]"]

[task="base:<msg_type:LoadBalanceSegments sourceID:189 > source_nodeIDs:0 balance_reason:NodeDown "]
[task="base:<msg_type:LoadBalanceSegments sourceID:189 > source_nodeIDs:1 balance_reason:NodeDown "]
...
```

**Comment by xiaofan-luan** [comment]
@zhuwenxing should be fixed by 18590, pls verify on it

**Comment by zhuwenxing** [comment]
verified and passed in version `master-20220810-29384dd`
