### ISSUE TITLE
[Enhancement]: Return empty result in advance if all data filtered out

### ISSUE THREAD

**Issue by czs007** [milvus-io/milvus#18331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

When the number of valid data is 0, the performance of hnsw is very low. Therefore, a small optimization is to return an empty result in advance without calling the know interface when it is determined in advance that the effective number is 0.

**Comment by xiaofan-luan** [comment]
pls backport to master as well, thanks
