### ISSUE TITLE
[Bug]: Flush failed when running `test_e2e.py` after minio pod kill

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#18368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220721-f37e07b0
- Deployment mode(standalone or cluster): cluster 
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.1.0.dev103
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Flush failed when running `test_e2e.py` after minio pod kill
```
        # flush
        t0 = time.time()
        num_entities, check_result = collection_w.flush(timeout=180)
>       assert check_result
E       assert False
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
see https://github.com/milvus-io/milvus/runs/7455771217?check_suite_focus=true
```

### Milvus Log

failed job: https://github.com/milvus-io/milvus/runs/7455771217?check_suite_focus=true
log : https://github.com/milvus-io/milvus/suites/7465437108/artifacts/306195968

### Anything else?

After https://github.com/milvus-io/milvus/issues/18270 was fixed, then this issue happened.
Not sure whether the issue already exists or is caused by the fix pr https://github.com/milvus-io/milvus/pull/18343

**Comment by xiaofan-luan** [comment]
pls help on it~

**Comment by yanliang567** [comment]
@wayblink any updates

**Comment by zhuwenxing** [comment]
Not reproduced anymore, so close it
