### ISSUE TITLE
[Bug]: Wrong parameters used to build OpenBLAS in docker builder

### ISSUE THREAD

**Issue by soulteary** [milvus-io/milvus#18360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.x
- Deployment mode(standalone or cluster): all
- OS(Ubuntu or CentOS): all
```

### Current Behavior

The parameters in the build scheme we are currently using are: https://github.com/milvus-io/milvus/blob/master/build/docker/openblas/ubuntu18.04/Dockerfile

```bash
make TARGET=CORE2 DYNAMIC_ARCH=1 DYNAMIC_OLDER=1 USE_THREAD=0 USE_OPENMP=0 FC=gfortran CC=gcc COMMON_OPT="-O3 -g -fPIC" FCOMMON_OPT="-O3 -g -fPIC -frecursive" NMAX="NUM_THREADS=128" LIBPREFIX="libopenblas" LAPACKE="NO_LAPACKE=1" INTERFACE64=0 NO_STATIC=1 && \...
```

the `LAPACKE` option is invalid, and in knowhere, this dependency is also not needed. https://github.com/milvus-io/knowhere/pull/290

In some build environments (eg. docker), if you build the lapacke used by openblas, there will be some unexpected errors. Since we don't need this dependency, we can not build this thing at all.

### Expected Behavior

Tool images build only the necessary artifacts

### Anything else?

I'll try to finish this issue and add some tests, but since there's a lot of process involved, it should take some time to fully validate.

**Comment by xiaofan-luan** [comment]
/assign @soulteary 
would you help on this issue? thanks!

**Comment by soulteary** [comment]
I tried submitting a simple PR to remove all LAPACK related stuff from the build. @xiaofan-luan 

https://github.com/milvus-io/milvus/pull/18464
