### ISSUE TITLE
[Bug]:  Poor performance when  I do batch inserting

### ISSUE THREAD

**Issue by psc0606** [milvus-io/milvus#18372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.2
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): java sdk 2.0.4
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: proxy(3 pods, 1core and 8G per pod), all coord(root, data, index) (1pod, 4core and 8G), datanode(10 pods, 2core and 8G per pod), indexnode(20 pods, 4core and 4G per pod), querynode(30pods, 1core and 8G per pod)
- GPU: No
- Others: 1000w entity
```

### Current Behavior

```
	for channelID, count := range channelCountMap {
		ts, ok := channelMaxTSMap[channelID]
		if !ok {
			ts = typeutil.ZeroTimestamp
			log.Debug("Warning: did not get max Timestamp!")
		}
		channelName := channelNames[channelID]
		if channelName == "" {
			return nil, fmt.Errorf("proxy, repack_func, can not found channelName")
		}
		mapInfo, err := it.segIDAssigner.GetSegmentID(it.CollectionID, it.PartitionID, channelName, count, ts)
		if err != nil {
			log.Debug("insertTask.go", zap.Any("MapInfo", mapInfo),
				zap.Error(err))
			return nil, err
		}
		reqSegCountMap[channelID] = make(map[UniqueID]uint32)
		reqSegCountMap[channelID] = mapInfo
		log.Debug("Proxy", zap.Int64("repackFunc, reqSegCountMap, reqID", reqID), zap.Any("mapinfo", mapInfo))
	}
```
I enable proxy debug log, get lots of logs, but when I do batch insert 1000 entities per request (128dim, only two field), but I get rather poor performance, about 800ms(I get from logs)

By analyze logs and `task.go`, I found poor performance about above `for` loop. I think the reason that every channel request a `GetSegmentID` info one by one. 

I have some questions about Channel: 
1. How many channels will be allocated?
2. Who can explain basic knowloage about Channel in milvus?

### Milvus Log

some logs from my server(milliseconds): 
milvus insert cost: 867
milvus insert cost: 910
milvus insert cost: 873
milvus insert cost: 881
milvus insert cost: 916
milvus insert cost: 920
milvus insert cost: 879
milvus insert cost: 889
milvus insert cost: 962
milvus insert cost: 876
milvus insert cost: 876
milvus insert cost: 898
milvus insert cost: 919
milvus insert cost: 899
milvus insert cost: 886
milvus insert cost: 877
milvus insert cost: 893
milvus insert cost: 895
milvus insert cost: 933
milvus insert cost: 913
milvus insert cost: 874
milvus insert cost: 920
milvus insert cost: 871
milvus insert cost: 906
milvus insert cost: 877
milvus insert cost: 898
milvus insert cost: 875
milvus insert cost: 909
milvus insert cost: 970
milvus insert cost: 900
milvus insert cost: 1022
milvus insert cost: 869
milvus insert cost: 888
milvus insert cost: 889
milvus insert cost: 928
milvus insert cost: 923
milvus insert cost: 946
milvus insert cost: 885
milvus insert cost: 886
milvus insert cost: 990
milvus insert cost: 906
milvus insert cost: 911
milvus insert cost: 903
milvus insert cost: 898
milvus insert cost: 883
milvus insert cost: 893
milvus insert cost: 885
milvus insert cost: 1133
milvus insert cost: 895
milvus insert cost: 888
milvus insert cost: 870
milvus insert cost: 896
milvus insert cost: 875

milvus insert cost: 906
milvus insert cost: 1053
milvus insert cost: 900
milvus insert cost: 870
milvus insert cost: 919
milvus insert cost: 888
milvus insert cost: 886
milvus insert cost: 887
milvus insert cost: 875
milvus insert cost: 882
milvus insert cost: 917
milvus insert cost: 889
milvus insert cost: 925
milvus insert cost: 928
milvus insert cost: 921
milvus insert cost: 882
milvus insert cost: 894
milvus insert cost: 953
milvus insert cost: 887
milvus insert cost: 1051
milvus insert cost: 918
milvus insert cost: 898
milvus insert cost: 880
milvus insert cost: 896
milvus insert cost: 908
milvus insert cost: 941

Detail logs about message ID 434759025007934993 in proxy:
[Explore-logs-2022-07-22 17_04_27.txt](https://github.com/milvus-io/milvus/files/9166333/Explore-logs-2022-07-22.17_04_27.txt)

update: add more log
[Explore-logs-2022-07-22 17_41_43.txt](https://github.com/milvus-io/milvus/files/9166599/Explore-logs-2022-07-22.17_41_43.txt)

**Comment by psc0606** [comment]
another case is proxy metric make insert rather slow:

```
![image](https://user-images.githubusercontent.com/7888889/180429296-30fccad7-445d-4b3d-bcba-b5ab27033213.png)

```

**Comment by xiaofan-luan** [comment]
it just means the produce takes 266ms, which means message storage is slow.

**Comment by xiaofan-luan** [comment]
it's the stream.Produce takes time

**Comment by psc0606** [comment]
@xiaofan-luan  But the second picture told me that it cost 826ms. And our pulsar metric indicate no any presussure.

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan But the second picture told me that it cost 826ms. And our pulsar metric indicate no any presussure.

time is consumed at stream.Produced, did you have pulsar metrics? what about the write latency?

**Comment by psc0606** [comment]
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/7888889/180728874-70a18680-37e5-4181-9327-e7763ce8fb9d.png">

**Comment by psc0606** [comment]
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/7888889/180730616-5734989b-7fc8-445e-91d1-3d502539c53e.png">

**Comment by psc0606** [comment]
updated: 
We set shard number to 64 first, when I use default two shard number. The batch insert time cost become normal.

**Comment by xiaofan-luan** [comment]
To make multi shard faster, we might want to insert in parallel, we can keep this as a feature
