### ISSUE TITLE
[Bug]: Simply delta channel operation

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#18393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

see #18391
When we do recover, we find several delta channel is not properly assigned with segment, causing system hang due to no time tick pushing forward.

### Expected Behavior

1. query coord should not assign delta channel
2. while querynode load segment, it handles delta channel load
3. TODO: release delta channel properly

### Anything else?

1. currently delta channel is leaked due to not released, we will handle it later otherwise the delta channel will be consumed by every delta channel.

**Comment by xiaofan-luan** [comment]
related to https://github.com/milvus-io/milvus/issues/18391

**Comment by weiliu1031** [comment]
what do you mean by " otherwise the delta channel will be consumed by every delta channel." ?
