### ISSUE TITLE
[QUESTION]请问milvus有缓存失效的机制吗？

### ISSUE THREAD

**Issue by LmYjQ** [milvus-io/milvus#184]
测试过程中发现内存占用会随着查询到的索引增加而增加（应该是数据从硬盘加载到内存了），但是过了一天内存占用量还是没有变。
请问有类似“缓存失效时间”的设置，或者手动让指定的table失效的命令吗？

**Comment by yhmo** [comment]
我们目前还没有缓存过期失效的机制。只有当缓存占用量达到server_config.yaml里cache_cache_caoacity的值之后，才会把旧数据清除出内存。能否问一下是什么使用场景下需要主动去释放缓存？
（Q: We noticed that milvus load index file from disk and cpu memory cost increase after search. But the memory usage has no changed even after one day. Is there any way can manually release cache for specified table, or any configuration can release 'expired cache'?
A: So far we don't have such mechanism to allow user manually release cache. Could you describe the usage scenario for the requirement?）

**Comment by LmYjQ** [comment]
> 我们目前还没有缓存过期失效的机制。只有当缓存占用量达到server_config.yaml里cache_cache_caoacity的值之后，才会把旧数据清除出内存。能否问一下是什么使用场景下需要主动去释放缓存？
> （Q: We noticed that milvus load index file from disk and cpu memory cost increase after search. But the memory usage has no changed even after one day. Is there any way can manually release cache for specified table, or any configuration can release 'expired cache'?
> A: So far we don't have such mechanism to allow user manually release cache. Could you describe the usage scenario for the requirement?）

我们的应用场景是建立很多个索引（千-万个table），所以希望某些table一段时间没有被查到的时候就失效，节省内存。
另外发现执行了delete table之后内存也不会减少，被删掉的表如何释放内存空间呢

**Comment by XuPeng-SH** [comment]
Milvus服务能稳定运行的前提在于有足够的内存空间，我们之后会让Milvus启动后申请独占一块内存空间，也就是说Milvus运行期占多少系统内存，在启动时就已经决定了(LRU缓存和Insert Buffer)。这种情况下，即使Milvus内部设置缓存失效时间，也不会为外部其他应用腾出内存空间。而在Milvus服务内部，不释放内存可以提高内存命中率。

**Comment by XuPeng-SH** [comment]
> > 我们目前还没有缓存过期失效的机制。只有当缓存占用量达到server_config.yaml里cache_cache_caoacity的值之后，才会把旧数据清除出内存。能否问一下是什么使用场景下需要主动去释放缓存？
> > （Q: We noticed that milvus load index file from disk and cpu memory cost increase after search. But the memory usage has no changed even after one day. Is there any way can manually release cache for specified table, or any configuration can release 'expired cache'?
> > A: So far we don't have such mechanism to allow user manually release cache. Could you describe the usage scenario for the requirement?）
> 
> 我们的应用场景是建立很多个索引（千-万个table），所以希望某些table一段时间没有被查到的时候就失效，节省内存。
> 另外发现执行了delete table之后内存也不会减少，被删掉的表如何释放内存空间呢

delete table我们会将操作记录在元数据中，不实时清理缓存中被删除的table数据，他们将永远不能被访问，等待LRU被置换出去时全部销毁。

**Comment by LmYjQ** [comment]
> > > 我们目前还没有缓存过期失效的机制。只有当缓存占用量达到server_config.yaml里cache_cache_caoacity的值之后，才会把旧数据清除出内存。能否问一下是什么使用场景下需要主动去释放缓存？
> > > （Q: We noticed that milvus load index file from disk and cpu memory cost increase after search. But the memory usage has no changed even after one day. Is there any way can manually release cache for specified table, or any configuration can release 'expired cache'?
> > > A: So far we don't have such mechanism to allow user manually release cache. Could you describe the usage scenario for the requirement?）
> > 
> > 
> > 我们的应用场景是建立很多个索引（千-万个table），所以希望某些table一段时间没有被查到的时候就失效，节省内存。
> > 另外发现执行了delete table之后内存也不会减少，被删掉的表如何释放内存空间呢
> 
> delete table我们会将操作记录在元数据中，不实时清理缓存中被删除的table数据，他们将永远不能被访问，等待LRU被置换出去时全部销毁。

明白了。非常感谢！

**Comment by cydrain** [comment]
The issue is clear now, close it.
