### ISSUE TITLE
[Bug]: ValueError: Value out of range: 18011707182610584615

### ISSUE THREAD

**Issue by bjjoy** [milvus-io/milvus#18407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.0.2
- OS(Ubuntu or CentOS): MacOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
connect_milvus()
collection = Collection(collection_name)  # Get an existing collection.
mr = collection.insert(news_data)
```

### Milvus Log

Unexcepted error: [bulk_insert], Value out of range: 18011707182610584615, <Time: {'RPC start': '2022-07-26 11:09:59.229761', 'Exception': '2022-07-26 11:09:59.239590'}>

### Anything else?

FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, auto_id=False)

when pk=-1，I can not search any data. But pk!=-1, example pk=-384972667586, I can search and get my data.

I do not know pk is unsigned or singed value

**Comment by xiaofan-luan** [comment]
@yanliang567 let's add some test case about data distribution also

**Comment by longjiquan** [comment]
@bjjoy Hello, I wrote a small test to try to reproduce your issue but no problem occured. It would help us a lot if you can provide the detailed script~
Below is my script, using `-1` and `-384972667586` as pk:
```python
import random
import time
import threading

import numpy as np

from pymilvus import (
    connections,
    FieldSchema, CollectionSchema, DataType,
    Collection,
    utility
)

HOST = '127.0.0.1'
PORT = '19530'

# Const names
COLLECTION_NAME = 'demo'
ID_FIELD_NAME = 'pk'
VECTOR_FIELD_NAME = 'vec'

DIM = 8
SHARD_NUM = 1

def create_collection():
    field1 = FieldSchema(name=ID_FIELD_NAME, dtype=DataType.INT64, is_primary=True, auto_id=False)
    field2 = FieldSchema(name=VECTOR_FIELD_NAME, dtype=DataType.FLOAT_VECTOR, dim=DIM)
    schema = CollectionSchema(fields=[field1, field2])
    collection = Collection(name=COLLECTION_NAME, data=None, schema=schema, shards_num=SHARD_NUM)
    print("\ncollection created:", COLLECTION_NAME)
    return collection

def gen_vec():
    return [random.random() for _ in range(DIM)]

def do_insert():
    collection = Collection(name=COLLECTION_NAME)
    data = [
        [-1, -384972667586],
        [gen_vec(), gen_vec()],
    ]
    res = collection.insert(data)
    print(res)

def do_search():
    search_params = {"metric_type": "L2"}
    collection = Collection(name=COLLECTION_NAME)
    collection.load()
    res = collection.search([gen_vec()], VECTOR_FIELD_NAME, search_params, limit=2, output_fields=[ID_FIELD_NAME])

    def show_res(res):
        for hits in res:
            for hit in hits:
                print(f"pk: {hit.entity.get(ID_FIELD_NAME)}")

    show_res(res)

if __name__ == '__main__':
    connections.connect(host=HOST, port=PORT)

    collection = create_collection()

    do_insert()

    do_search()
```

**Comment by longjiquan** [comment]
![image](https://user-images.githubusercontent.com/31589260/181670151-cc9e4cb6-7b7a-4da6-83cc-fe77a24931b9.png)

**Comment by yanliang567** [comment]
@binbinlv can we retry this and add some tests accordinlgy
/assign @binbinlv

**Comment by bjjoy** [comment]
> @yanliang567 let's add some test case about data distribution also

I am so sorry reply this issue too late. I have got solution.

dtype=DataType.INT64，it is signed int. Its range is -9223372036854775808 ~ 9223372036854775807

But my pk generator mmh3 generate the unsigned int64 18011707182610584615，so Value out of range.

I test in milvus 2.1.1, the exception is pymilvus.exceptions.DataNotMatchException: <DataNotMatchException: (code=0, message=The data in the same column must be of the same type.)>

Using signed int is run very well

**Comment by binbinlv** [comment]
> > @yanliang567 let's add some test case about data distribution also
> 
> I am so sorry reply this issue too late. I have got solution.
> 
> dtype=DataType.INT64，it is signed int. Its range is -9223372036854775808 ~ 9223372036854775807
> 
> But my pk generator mmh3 generate the unsigned int64 18011707182610584615，so Value out of range.
> 
> I test in milvus 2.1.1, the exception is pymilvus.exceptions.DataNotMatchException: <DataNotMatchException: (code=0, message=The data in the same column must be of the same type.)>
> 
> Using signed int runs very well

So here it works as design? If so, I think this issue could be closed?

**Comment by bjjoy** [comment]
pk is unsigned int64 in milvus 2.0.*，python mmh3 generate the signed int64.
