### ISSUE TITLE
[Enhancement]: to support type string for binary data

### ISSUE THREAD

**Issue by yangkequn** [milvus-io/milvus#18424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

support binary data rather than characters only(varchar)

### Why is this needed?

currently, milvus only support type VarChar, but can not support arbitary binary data.
however modern programing language usually use string to enable storing binary data. 
for example, i want to save a chunk of audio to milvus rather than redis to lower my system latency, without binary string, i can't do this neatly

**Comment by vishjain** [comment]
Can I try this issue? /assign

**Comment by vishjain** [comment]
Can I try this issue?
