### ISSUE TITLE
[Enhancement]: Ambiguous types tag for binary vector 

### ISSUE THREAD

**Issue by qwert170** [milvus-io/milvus#18422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

我在尝试添加unsigned int8的功能的时候，发现/util/importutil/numpy_parser.go在convertNumptType函数里，uint8返回的是binary vector,这一块和添加unsigned int8有冲突

**Comment by yhmo** [comment]
@qwert170 这里convertNumptType你可以先不动。要解决冲突的话，这里要把numpy header descriptor 的数据类型和collection schema的数据类型比对一下，以确定是否匹配
