### ISSUE TITLE
[Bug]: [Milvusv2.1][doc] milvus download address 404

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#18436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I follow the link to download the standalone version of milvus,  with 404 

![image](https://user-images.githubusercontent.com/48523564/181409619-186f0a72-619a-4812-9a0e-2cf392369906.png)

I checked the link and the .deb package address should be: "https://github.com/milvus-io/milvus/releases/download/v2.1.0/milvus_2.1.0-2_amd64.deb" , 
the rpm package address should be: "https://github.com/milvus-io/milvus/releases/download/v2.1.0/milvus-2.1.0-2.el7.x86_64.rpm". 

### Steps To Reproduce

```markdown
1. Open URL: https://milvus.io/docs/v2.1.x/install_standalone-docker.md
2. Verify milvus APT or YUM download address
```

**Comment by YiyunNi** [comment]
Thanks for the feedback. I will fix it asap.

**Comment by YiyunNi** [comment]
Fixed with this [PR](https://github.com/milvus-io/milvus-docs/pull/1669).

**Comment by yanliang567** [comment]
/assign @elstic 
please help to verify the fix

/unassign

**Comment by elstic** [comment]
Now it's normal
