### ISSUE TITLE
[Bug]: datanode CrashLoopBackOff when run case `test_alias_exec_operations_as_collection`

### ISSUE THREAD

**Issue by jennyli-z** [milvus-io/milvus#18444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. e2e failed at case test_alias_exec_operations_as_collection  https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-18442/2/pipeline/

2. part of log in datanode
```
[2022/07/28 10:32:42.476 +00:00] [ERROR] [datanode/flush_manager.go:737] ["flush pack with error, DataNode quit now"] [error="execution failed"] [stack="github.com/milvus-io/milvus/internal/datanode.flushNotifyFunc.func1\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:737\ngithub.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).waitFinish\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:201"]

panic: execution failed



goroutine 19212 [running]:

github.com/milvus-io/milvus/internal/datanode.flushNotifyFunc.func1(0xc000ffec80)

	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:739 +0x16b3

github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).waitFinish(0xc00208f080, 0xc0002efa10, 0xc003e17120)

	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:201 +0xbd

created by github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).init.func1

	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:119 +0xb0
```

### Expected Behavior

should pass the case

### Milvus Log

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-18442/2/artifacts

**Comment by yanliang567** [comment]
seems not reproduce, close for now

**Comment by animelfc** [comment]
I have the  same problem, how do you reslove this problem

**Comment by xiaofan-luan** [comment]
> I have the same problem, how do you reslove this problem

what version you are using. upgrade to 2.2.11 should fix the problem

**Comment by animelfc** [comment]
您好，您的邮件已收到，查阅后，我会尽快回复您！

**Comment by divyajaincs** [comment]
@xiaofan-luan Getting the similar issue while inserting more than 150k records in a collection with version 2.2.11 also.

**Comment by yanliang567** [comment]
please file a new issue with completed milvus logs. refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs
