### ISSUE TITLE
[Enhancement]: SDK Collection `init`, remove redundant `HasCollection` interface and use `DescribeCollection` instead

### ISSUE THREAD

**Issue by SimFG** [milvus-io/milvus#18456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

In pymilvus sdk, `Collection` object initialization may involve the following api: 
- HasCollection
- DescribeCollection, if collection exists
- CreateCollection, if collection does not exist

**Expected**
Use `DescribeCollection` to replace `HasCollection` implementation.

**Comment by congqixia** [comment]
@SimFG maybe this issue shall be in pymilvus repo?

**Comment by SimFG** [comment]
@congqixia Other types of sdk need to confirm the implementation of this part.
