### ISSUE TITLE
[Bug]: message size exceeds MaxMessageSize: MessageTooBig

### ISSUE THREAD

**Issue by psc0606** [milvus-io/milvus#18470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.1
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: proxy(3 pods, 1core and 8G per pod), all coord(root, data, index) (1pod, 4core and 8G), datanode(10 pods, 2core and 8G per pod), indexnode(20 pods, 4core and 4G per pod), querynode(30pods, 1core and 8G per pod)
- GPU: None
- Others: None
```

### Current Behavior

When I do batch insert by pymilvus, pymilvus client occasionally abort exceptionally. Each batch has three fields: 128dim floatvector, one int64 id, and another int64 id. I see only

### Expected Behavior

proxy split big message correctlly

### Steps To Reproduce
Each batch size 5w entites.

### Milvus Log

pymilvus client log below:
```
2022-07-29 18:10:04,977 ｜ ERROR ｜ decorators.py ｜ handler ｜ 95 ｜ RPC error: [bulk_insert], <MilvusException: (code=1, message=message size exceeds MaxMessageSize: MessageTooBig)>, <Time:{'RPC start': '2022-07-29 18:10:04.608322', 'RPC error': '2022-07-29 18:10:04.977344'}>
```

proxy log below(ignore time zone)
![image](https://user-images.githubusercontent.com/7888889/182061892-c4c4236a-985a-4a8d-8686-67fc939bcad3.png)

**Comment by xiaofan-luan** [comment]
did you use your own message queue? this is because the batch size is too large and exceed message queue limit.
There are two thing you can do:
1. change your mq limit to a valid size
2. use smaller batch when insert

**Comment by psc0606** [comment]
We use pular, default queue limit is 5M. But I wonder why the proxy split bigger message into smaller message not work?```
	// repack the row data corresponding to the offset to insertMsg
	getInsertMsgsBySegmentID := func(segmentID UniqueID, rowOffsets []int, channelName string, maxMessageSize int) ([]msgstream.TsMsg, error) {
		repackedMsgs := make([]msgstream.TsMsg, 0)
		requestSize := 0
		msgID, err := getMsgID()
		if err != nil {
			return nil, err
		}
		insertMsg := createInsertMsg(segmentID, channelName, msgID)
		for _, offset := range rowOffsets {
			curRowMessageSize, err := typeutil.EstimateEntitySize(it.InsertRequest.GetFieldsData(), offset)
			if err != nil {
				return nil, err
			}

			// if insertMsg's size is greater than the threshold, split into multiple insertMsgs
			if requestSize+curRowMessageSize >= maxMessageSize {
				repackedMsgs = append(repackedMsgs, insertMsg)
				msgID, err = getMsgID()
				if err != nil {
					return nil, err
				}
				insertMsg = createInsertMsg(segmentID, channelName, msgID)
				requestSize = 0
			}

			typeutil.AppendFieldData(insertMsg.FieldsData, it.GetFieldsData(), int64(offset))
			insertMsg.HashValues = append(insertMsg.HashValues, it.HashValues[offset])
			insertMsg.Timestamps = append(insertMsg.Timestamps, it.Timestamps[offset])
			insertMsg.RowIDs = append(insertMsg.RowIDs, it.RowIDs[offset])
			insertMsg.NumRows++
			requestSize += curRowMessageSize
		}
		repackedMsgs = append(repackedMsgs, insertMsg)

		return repackedMsgs, nil
	}
```

**Comment by xiaofan-luan** [comment]
> maxMessageSize

From  our test is should work, did you check the value of maxMessageSize?

**Comment by xiaofan-luan** [comment]
May be you want to change it to 2 smaller size(Say 2 MB) and retry?

**Comment by psc0606** [comment]
We use default maxMessageSize value. Thanks, I'll retry.
