### ISSUE TITLE
[Bug]: Milvus crashed when m=0 after 'IVF_PQ' index

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#18479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220801-3871758
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.1.0.dev97
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Error occurs during searching case with dim=1:
index = 'IVF_PQ', params = {'m': 0, 'nbits': 8, 'nlist': 128}, auto_id = False
_async = False

### Expected Behavior

Milvus shouldn't be crashed when search 'dim=1' cases.

### Steps To Reproduce

```python
@pytest.mark.tags(CaseLabel.L1)
    @pytest.mark.parametrize("index, params",
                             zip(ct.all_index_types[:9],
                                 ct.default_index_params[:9]))
    def test_search_after_different_index_with_min_dim(self, index, params, auto_id, _async):
        """
        target: test search after different index with min dim
        method: test search after different index and corresponding search params with dim = 1
        expected: search successfully with limit(topK)
        """
        # 1. initialize with data
        collection_w, _, _, insert_ids, time_stamp = self.init_collection_general(prefix, True, 5000,
                                                                                  partition_num=1,
                                                                                  auto_id=auto_id,
                                                                                  dim=min_dim, is_index=True)[0:5]
        # 2. create index and load
        if params.get("m"):
            if (min_dim % params["m"]) != 0:
                params["m"] = min_dim // 4
        if params.get("PQM"):
            if (min_dim % params["PQM"]) != 0:
                params["PQM"] = min_dim // 4
        default_index = {"index_type": index, "params": params, "metric_type": "L2"}
        collection_w.create_index("float_vector", default_index)
        collection_w.load()
        # 3. search
        search_params = cf.gen_search_param(index)
        vectors = [[random.random() for _ in range(min_dim)] for _ in range(default_nq)]
        for search_param in search_params:
            log.info("Searching with search params: {}".format(search_param))
            collection_w.search(vectors[:default_nq], default_search_field,
                                search_param, default_limit,
                                default_search_exp, _async=_async,
                                travel_timestamp=time_stamp,
                                check_task=CheckTasks.check_search_results,
                                check_items={"nq": default_nq,
                                             "ids": insert_ids,
                                             "limit": default_limit,
                                             "_async": _async})
```

### Milvus Log

[milvus-log.txt](https://github.com/milvus-io/milvus/files/9231769/milvus-log.txt)

### Anything else?

[ - ERROR - pymilvus.decorators]: RPC error: [describe_collection], <MilvusUnavaliableException: (code=1, message=server unavaliable: Retry timeout: 40s)>,  (decorators.py:94)
[ - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusUnavaliableException: (code=1, message=server unavaliable: Retry timeout: 40s)>,  (decorators.py:94)
[ - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/zilliz/virtual-environment/test1/lib/python3.8/site-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/test1/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 225, in describe_collection
    response = rf.result()
  File "/Users/zilliz/virtual-environment/test1/lib/python3.8/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: Failed to connect to remote host: Connection refused"
	debug_error_string = "UNKNOWN:Failed to pick subchannel {created_time:"2022-08-01T15:30:11.737092+08:00", children:[UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: Failed to connect to remote host: Connection refused {grpc_status:14, created_time:"2022-08-01T15:30:11.737079+08:00"}]}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zilliz/milvus/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/Users/zilliz/milvus/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/Users/zilliz/virtual-environment/test1/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 1077, in create_index
    return conn.create_index(self._name, field_name, index_params,
  File "/Users/zilliz/virtual-environment/test1/lib/python3.8/site-packages/pymilvus/decorators.py", line 95, in handler
    raise e
  File "/Users/zilliz/virtual-environment/test1/lib/python3.8/site-packages/pymilvus/decorators.py", line 91, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/virtual-environment/test1/lib/python3.8/site-packages/pymilvus/decorators.py", line 73, in handler
    raise e
  File "/Users/zilliz/virtual-environment/test1/lib/python3.8/site-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/test1/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 525, in create_index
    collection_desc = self.describe_collection(collection_name, timeout=timeout, **copy_kwargs)
  File "/Users/zilliz/virtual-environment/test1/lib/python3.8/site-packages/pymilvus/decorators.py", line 95, in handler
    raise e
  File "/Users/zilliz/virtual-environment/test1/lib/python3.8/site-packages/pymilvus/decorators.py", line 91, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/virtual-environment/test1/lib/python3.8/site-packages/pymilvus/decorators.py", line 64, in handler
    raise MilvusUnavaliableException(Status.UNEXPECTED_ERROR, f"server unavaliable: {timeout_msg}")
pymilvus.exceptions.MilvusUnavaliableException: <MilvusUnavaliableException: (code=1, message=server unavaliable: Retry timeout: 40s)>
 (api_request.py:39)
[2022-08-01 15:30:11 - ERROR - ci_test]: (api_response) : <MilvusUnavaliableException: (code=1, message=server unavaliable: Retry timeout: 40s)> (api_request.py:40)

**Comment by xiaofan-luan** [comment]
[2022/08/01 03:32:55.205 +00:00] [ERROR] [proxy/task_scheduler.go:459] ["Failed to pre-execute task: invalid dimension: 1. should be multiple of 8. "] [traceID=43f7cdc2cd7b1b0a] [stack="github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:459\ngithub.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:494"]

**Comment by xiaofan-luan** [comment]
did milvus crash?
It seems that milvus vector dimension has to be multiplier of 8. 

This check should not be at proxy side but at rootcoord side and again the error message doesn't make sense to me

**Comment by xiaofan-luan** [comment]
@XuanYang-cn we probably need better error message for this kind of error

**Comment by XuanYang-cn** [comment]
<img width="1440" alt="截屏2022-08-01 15 48 12" src="https://user-images.githubusercontent.com/51370125/182099506-9bee1c11-ee27-412a-8bc2-ad7da0274c31.png">
@xiaofan-luan  proxy crashed, pymilvus cannot report anything else. I think the "server unavaliable" is clear enough for this kind of crash.

**Comment by XuanYang-cn** [comment]
@NicoYuan1986 It crashed because "m==0", not becasue of  "dim == 1"

Although `m==0` shouldn't crash proxy, I'll fix this.

if 'dim == 1', m Must be 1, ref https://milvus.io/docs/v2.1.x/index.md#IVF_PQ

**Comment by XuanYang-cn** [comment]
It works perfectly fine with correct params

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/51370125/182101117-5997267a-9f7b-4291-a6c1-e4cc361dcfc2.png">

**Comment by xiaofan-luan** [comment]
> It works perfectly fine with correct params
> 
> <img alt="image" width="1440" src="https://user-images.githubusercontent.com/51370125/182101117-5997267a-9f7b-4291-a6c1-e4cc361dcfc2.png">

We will need to think of how we can let the user know the parameter error and fix the issue, any suggestion?

**Comment by XuanYang-cn** [comment]
@xiaofan-luan the current behaviour for invalid index params: 

For index params: `{'index_type': 'IVF_PQ', 'metric_type': 'L2', 'params': {'m': 2, 'nbits': 8, 'nlist': 128}}`
```python
RPC error: [create_index], <MilvusException: (code=1, message=invalid index params: map[dim:1 index_type:IVF_PQ m:2 metric_type:L2 nbits:8 nlist:128])>, <Time:{'RPC start': '2022-08-02 15:41:08.353273', 'RPC error': '2022-08-02 15:41:08.366573'}>
Traceback (most recent call last):
...
```

`conf_adapter.go` checks the params with true or false, so the information is lost at proxy.

So we could refine the `internal/util/indexparamcheck/conf_adapter.go`  to return `error` with more informative error message.
```golang
func (adapter *IVFPQConfAdapter) checkPQParams(params map[string]string) bool {                               
      dimStr, dimensionExist := params[DIM]                                                                     
      if !dimensionExist {                                                                                      
          return false                                                                                          
      }                                                                                                         
                                                                                                                
      dimension, err := strconv.Atoi(dimStr)                                                                    
      if err != nil { // invalid dimension                                                                      
          return false                                                                                          
      }                                                                                                         
                                                                                                                
      // nbits can be set to default: 8                                                                         
      nbitsStr, nbitsExist := params[NBITS]                                                                     
      var nbits int                                                                                             
      if !nbitsExist {                                                                                          
          nbits = 8                                                                                             
      } else {                                                                                                  
          nbits, err = strconv.Atoi(nbitsStr)                                                                   
          if err != nil { // invalid nbits                                                                      
              return false                                                                                      
          }                                                                                                     
      }                  
.....                                           
```

**Comment by NicoYuan1986** [comment]
The issue has been fixed.
<MilvusException: (code=1, message=invalid index params: map[dim:1 index_type:IVF_PQ m:0 metric_type:L2 nbits:8 nlist:128])> (api_request.py:40)
