### ISSUE TITLE
[Bug]: failed to complete compaction

### ISSUE THREAD

**Issue by psc0606** [milvus-io/milvus#18471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.1, java-sdk-2.1.0-beta4
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: proxy(3 pods, 1core and 8G per pod), all coord(root, data, index) (1pod, 4core and 8G), datanode(10 pods, 2core and 8G per pod), indexnode(20 pods, 4core and 4G per pod), querynode(30pods, 1core and 8G per pod)
- GPU: None
- Others: None
```

### Current Behavior

After milvus cluster stably running only for two days, I see some error logs about compaction failure in my cluster (below). To now, the cluster is likely okay, we can read and write collection normally. But someone can tell me about the bad result if compaction failure still exists.

### Steps To Reproduce

```markdown
I don't know how to reproduce it.
```

### Milvus Log
![image](https://user-images.githubusercontent.com/7888889/182064304-10b169f2-f15f-4720-be4f-d3c5f2aa23ed.png)

**Comment by yanliang567** [comment]
@psc0606 thank you for the issue.

@xige-16 could you pleae take a look? sounds like a log issue.
/assign @xige-16 
/unassign

**Comment by xiaofan-luan** [comment]
This is not a bug, but the log do need to be refined.
Thanks for the feedback @psc0606

**Comment by xiaofan-luan** [comment]
/assign @xiaocai2333 
1. we should not print too many meaningless log if it's just because of the lock.
2. should we simply ignore error if it's caused by compaction? or just changed the log to info

**Comment by xiaocai2333** [comment]
> 

1. For auto compaction, we can ignore the compaction error about reference lock. We expect these segments still can be compacted later.
2. For mushal compaction,  can we ignore the error also? related issue: #17725

**Comment by xiaofan-luan** [comment]
> > 
> 
> 1. For auto compaction, we can ignore the compaction error about reference lock. We expect these segments still can be compacted later.
> 2. For mushal compaction,  can we ignore the error also? related issue: [[Bug]: [kafka] "wait_for_compaction_completed" is failed for "Get compaction state timeout" #17725](https://github.com/milvus-io/milvus/issues/17725)

Good discussion. For manual compaction, what will happen if get lock failed? Does the compaction plan retry?
I thought the current compaction state design does not make sense, it should not check status based on compactionID

Actually, manual compaction succeed only when all segments generation time is larger than compaction trigger time(which means all segments are created after compaction happened) Does that make more sense?
@sunby @xiaocai2333
