### ISSUE TITLE
[Bug]: Collection shards_num 参数存在bug

### ISSUE THREAD

**Issue by zhoushewei** [milvus-io/milvus#18480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.0
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.0.2
- OS(Ubuntu or CentOS): Ubuntu 18.04
- CPU/Memory: 6c
- GPU: 
- Others:
```

### Current Behavior

V2.0.2版本，如下代码不会出现问题
col = Collection(cur_table_name,
                 schema,
                 consistency_level="Strong" ,
                 shards_num = 16
                 )
V2.1.0 版本使用上面代码建20张表（表结构pk(int64),feature(3840),timestam(double))，建表前cpu5%左右，建表后cpu50%左右，新建临时表插入数据后，dataquery出现shard异常，清除所有表数据和表结构，milvus全部假死状态，无法通过重启恢复；
v2.1.0版本 正确方式，使用代码不会出现问题，有负载情况下，cpu稳定在20%左右，运行稳定
col = Collection(cur_table_name,
                 schema,
                 consistency_level="Strong" #,
                 #shards_num = 16
                 )
“shards_num = 16” 此处后台存在bug，需要修正；

**Comment by xiaofan-luan** [comment]
Hi @zhoushewei ,
1) Did you collect the log when you cluster crash? How much memory and CPU is there for your querynode? we've changed the way of handling shard, which may cause extra overheads, but we don't expect to see such a big gap.
2) we are trying to reproduce on our own test environment.

**Comment by xiaofan-luan** [comment]
@yanliang567 could you pls verify large shard number(Let's say 16 or 32 ) on our own environment？

**Comment by yanliang567** [comment]
@ThreadDao could you please help to reproduce the issue ?

/assign @ThreadDao 
/unassign

**Comment by ThreadDao** [comment]
Hi @zhoushewei 
I limit datanode cpu to 6, and then create 20 collections with 16 shards, and the maximum cpu usage of the datanode is only 0.5. Hard to reproduce. I would appreciate it if you could upload your server log or part of the code to reproduce

**Comment by xiaofan-luan** [comment]
@zhoushewei any suggestion on your environment? we can not reproduce your issue

**Comment by zhoushewei** [comment]
我这边现在已经无法复现了，当时环境已经铲除，感谢支撑！

**Comment by yanliang567** [comment]
close this issue for now
