### ISSUE TITLE
[Bug]: The data in the same column must be of the same type

### ISSUE THREAD

**Issue by w5688414** [milvus-io/milvus#18490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.1
- OS(Ubuntu or CentOS): ubuntu 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/12107462/182288838-36041b3f-675b-4bcd-af6f-4d4f84b6a72d.png">

### Expected Behavior

插入数据的时候能够正常插入

### Steps To Reproduce

```markdown
use this data to insert including inserting text data and vector data. https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/neural_search/recall/milvus

here is the fields

fields = [
    FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, auto_id=False, max_length=100),
    FieldSchema(name="text", dtype=DataType.VARCHAR, max_length=1000),
    FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=data_dim)
]
```
```


### Milvus Log

_No response_

### Anything else?

_No response_

**Comment by xiaofan-luan** [comment]
@w5688414 we can't see your photo,  could you quickly describe what's the problem?

**Comment by JackLCL** [comment]
Perhaps the length of the text exceeds the defined length of the string.

**Comment by tommykoctur** [comment]
Hello,

I have been debugging this a few hours.

Error: The data in the same column must be of the same type. 

Can you make this error be more descriptive, I didn't get it. Anyway can you also print field name to find where is the problem. Debugging is really hard. 

Thank you

**Comment by yanliang567** [comment]
> Anyway can you also p

which milvus and pymilvus are you running? I believe we had some improvements for this in milvus v2.2.9 and pymilvus 2.2.9

**Comment by tommykoctur** [comment]
Hi,

I got milvus 2.1.4 and  2.1.3 ...

**Comment by NasonZ** [comment]
#25912 Encountering the same issue, also added code to reproduce the error.
