### ISSUE TITLE
[Bug]:  About the problem of high CPU load

### ISSUE THREAD

**Issue by WeiDong-Shi** [milvus-io/milvus#18516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.0
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.0
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 64C / 256G
- GPU: 
- Others:
```

### Current Behavior

 - Index Config
```text
dim: 2048	
Index Type: IVF_FLAT
metric_type:IP
nlist: 4096
```
- SearchParams
```
consistency_level: Strong
output_fields: user_id
metric_type: IP
nprobe: 128
limit: 10
```

I'm now conducting a concurrent query test. I'm sending 10 concurrent queries and 200000 data volumes. I found that the CPU utilization is not high, but the load will be very high. There are currently 10 query nodes.

```
top - 15:13:36 up  4:52,  3 users,  load average: 452.84, 357.41, 217.48
Tasks: 701 total,   1 running, 402 sleeping,   0 stopped,   0 zombie
%Cpu(s): 48.4 us,  8.2 sy,  0.0 ni, 43.3 id,  0.0 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem : 25948646+total, 16484614+free, 41501880 used, 53138444 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 21618172+avail Mem
```

**Comment by yanliang567** [comment]
if it is 10 concurrent queries, maybe it is by design for now(or lets say it needs an improvement). 
@jiaoew1991 could you please take a look?

/assign @jiaoew1991 
/unassign

**Comment by jiaoew1991** [comment]
I'll follow up

**Comment by jiaoew1991** [comment]
hi @WeiDong-Shi, how did you deploy Milvus, all of the components running a single 64c/256G ubuntu server?

**Comment by WeiDong-Shi** [comment]
> hi @WeiDong-Shi, how did you deploy Milvus, all of the components running a single 64c/256G ubuntu server?

Yes, the test environment is simply built, and all nodes are on the same server.

**Comment by jiaoew1991** [comment]
@WeiDong-Shi when using `query` API and the output fields contain vector field, the output will fetch the original vector from `MinIO/s3`,  the bottleneck is IO, in this case, the load is high but the CPU usage is low is reasonable

**Comment by WeiDong-Shi** [comment]
> @WeiDong-Shi when using `query` API and the output fields contain vector field, the output will fetch the original vector from `MinIO/s3`, the bottleneck is IO, in this case, the load is high but the CPU usage is low is reasonable

I'm not sure if I don't fully understand what you mean, but I don't output the fields used to store vectors when I use the query. I only output the two default fields of your interface, the ID and distance fields of Milvus, and attach a self-defined field of varchar (32) that I define myself. So I don't fully understand what you mean.

**Comment by jiaoew1991** [comment]
@WeiDong-Shi Could you provide flamegraph for us to diagnostic? follow this article to generate flamegraph https://www.benburwell.com/posts/flame-graphs-for-go-with-pprof/

**Comment by WeiDong-Shi** [comment]
> @WeiDong-Shi Could you provide flamegraph for us to diagnostic? follow this article to generate flamegraph https://www.benburwell.com/posts/flame-graphs-for-go-with-pprof/

Regarding this question, I have not conducted a test recently. If it is repeated in the subsequent test, I will provide more detailed information again.
