### ISSUE TITLE
[Bug]: client gets stuck when searching

### ISSUE THREAD

**Issue by dzqoo** [milvus-io/milvus#18511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.1 
- Deployment mode(standalone or cluster):standalone docker-compose
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.0.1
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 750GB，72个逻辑核
- GPU: 无
- Others: 无
```

### Current Behavior

When I search the result with id and embedding, the client gets stuck and I get log from milvus quernode below.

``[2022/08/02` 19:37:40.976 +00:00] [WARN] [node.go:81] ["some node(s) haven't received input"] [list="[nodeCtxTtChecker-dmlInputNode,nodeCtxTtChecker-dNode,nodeCtxTtChecker-stNode-434899722813571073-by-dev-rootcoord-delta_4_434899722813571073v4,nodeCtxTtChecker-iNode,nodeCtxTtChecker-stNode-434899722813571073-by-dev-rootcoord-dml_1_434899722813571073v1,nodeCtxTtChecker-stNode-434899722813571073-by-dev-rootcoord-delta_5_434899722813571073v5,nodeCtxTtChecker-stNode-434899722813571073-by-dev-rootcoord-delta_3_434899722813571073v3,nodeCtxTtChecker-stNode-434899722813571073-by-dev-rootcoord-dml_4_434899722813571073v4,nodeCtxTtChecker-fdmNode-434899722813571073,nodeCtxTtChecker-stNode-434899722813571073-by-dev-rootcoord-delta_0_434899722813571073v0,nodeCtxTtChecker-stNode-434899722813571073-by-dev-rootcoord-delta_1_434899722813571073v1,nodeCtxTtChecker-stNode-434899722813571073-by-dev-rootcoord-delta_2_434899722813571073v2,nodeCtxTtChecker-fdNode-434899722813571073]"] ["duration "=2m0s]`

detail logs shows in  milvus log.

### Milvus Log

[Uploading milvus-query.log…]()

**Comment by yanliang567** [comment]
@dzqoo any chance to reproduce it on 2.1.0? if yes, please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation

/assign @dzqoo 
/unassign
