### ISSUE TITLE
Building index with admin always prompts timeout。

### ISSUE THREAD

**Issue by Bennu-Li** [milvus-io/milvus#1851]
**Describe the bug**
Building index with admin, prompting timeout. But the index was created successfully after refreshing

![image](https://user-images.githubusercontent.com/53458891/78212238-ba488580-74e1-11ea-995b-f8ea75a7ec06.png)

**Comment by BossZou** [comment]
@Bennu-Li This is because all of restful api are synchronous, so server will return results until task done. Building index may cost much time which exceed the timeout value of http request in frontend.

**Comment by shengjun1985** [comment]
Inactive. Close.
