### ISSUE TITLE
[Bug]: DataNode may crash if one collection reuses same pchannel for some shards

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#18517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 7cd37fc
- Deployment mode(standalone or cluster): cluster with pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Data node will crash if:
- One collection has some vchannel reusing same pchannel say: `dml_0_collectionidv0`, `dml_1_collectionidv1`
- Those vchannels are assigned to same datanode

### Expected Behavior

DataNode shall not crash and handles data correctly in previously mentioned situation.

### Steps To Reproduce

```markdown
- Set `dmlChannelNum` to 1
- Start milvus cluster with pulsar
- Create a collection with 2 shard
```

### Milvus Log

```
[2022/08/03 14:55:19.699 +08:00] [DEBUG] [retry/retry.go:39] ["retry func failed"] ["retry time"=0] [error="server error: ConsumerBusy: Exclusive consumer is already connected"]
panic: Failed to create consumer by-dev-rootcoord-dml_197, error = All attempts results:
attempt #1:server error: ConsumerBusy: Exclusive consumer is already connected
```

**Comment by xiaofan-luan** [comment]
I'm not sure if it will work if shard number < collection shard number.
From the original design collection shard number must be smaller than collection shard number, did we test on it?

**Comment by congqixia** [comment]
> I'm not sure if it will work if shard number < collection shard number. From the original design collection shard number must be smaller than collection shard number, did we test on it?

@xiaofan-luan you are correct. We do not support `ShardNumber` > `DmlChannel Number`.
