### ISSUE TITLE
[Bug]: s3 with iam role not available,Access Denied

### ISSUE THREAD

**Issue by zhoudayu123** [milvus-io/milvus#18523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 16/128
- GPU: 
- Others:
```

### Current Behavior

minio:
  enabled: false

externalS3:
  enabled: true
  host: "s3.us-west-2.amazonaws.com"
  port: "443"
  useSSL: true
  bucketName: "mars6-prod-milvus"
  rootPath: "/"
  useIAM: true

### Steps To Reproduce

```markdown
when i configure with ak sk,it works. but change to iam,it not work.
i'm sure that iam role is ok ,because i can access s3 by aws cli and other pod.
```

### Milvus Log

![image](https://user-images.githubusercontent.com/51695477/182597441-6b520d9c-b0a8-4867-a189-c9f8b533bd74.png)

### Anything else?

how can i configure s3 with iam correctly?

**Comment by yanliang567** [comment]
@LoveEachDay could you please help on this issue?
/assign @LoveEachDay 
/unassign

**Comment by LoveEachDay** [comment]
@zhoudayu123 Did you deploy a milvus cluster into a aws eks with s3 iam role? If so you'd create a service account which binds a iam role first. And here's a tutorial to setup iam role for eks: https://levelup.gitconnected.com/using-iam-roles-to-allow-the-pods-in-aws-eks-to-read-the-aws-s3-bucket-be493fbdda84. Take a try.

If you set up the service account, you can verify the setting using the following commands:
```
kubectl describe pods <milvus-pods>
```
You'd see the following environment variables
```
AWS_STS_REGIONAL_ENDPOINTS   
AWS_DEFAULT_REGION
AWS_REGION
AWS_ROLE_ARN
AWS_WEB_IDENTITY_TOKEN_FILE
```
injected to your milvus pod and a  volume which has the sts token attached to the milvus pod.

You can take a reference from [here](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html).

**Comment by yanliang567** [comment]
@zhoudayu123 please try as suggest above
/assign @zhoudayu123 
/unassign @LoveEachDay

**Comment by erezweissgloat** [comment]
@zhoudayu123 Any news? stuck at the same point

**Comment by LoveEachDay** [comment]
@erezweissgloat Have you setup the service account for a iam role following the above instructions?

**Comment by erezweissgloat** [comment]
> @erezweissgloat Have you setup the service account for a iam role following the above instructions?

Works now, service account defected. Thanks!!!

**Comment by haorenfsa** [comment]
can be closed
