### ISSUE TITLE
[Bug]: milvus2.1 cluster scaling and restart problem

### ISSUE THREAD

**Issue by bestRiven** [milvus-io/milvus#18536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.0
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

At present, the cluster version of 2.1 is tested, and the following problems are found: the 6G memory threshold is set. After reaching 80% occupancy, the capacity will be expanded, but the memory of the previous node has been increasing after the expansion. The memory of the new node has not changed, and then it will restart automatically after it is full. After the restart, the memory will not rise back, and the query will report an error. This situation is equivalent to that the capacity expansion function of the cluster is unavailable.

### Milvus Log

| 1659604325 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:12:04.435 +00:00] [DEBUG] [querynode/impl.go:64] ["Get QueryNode component state done"] [stateCode=Healthy] | milvus-cluster | 2022-08-04T09:12:04.436111746Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604326
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | 1659604326 | 172.20.3.35 | 172.20.3.35 | fa9168ca-f366-446d-9a97-384d6b1694c3 | 172.20.12.53 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:12:06.724 +00:00] [DEBUG] [querynode/impl.go:64] ["Get QueryNode component state done"] [stateCode=Healthy] | milvus-cluster | 2022-08-04T09:12:06.724564923Z | cn-hangzhou.172.20.3.35 | iZbp1eexno0clhh9gq1tr0Z | milvus-querynode-598bf85b4-jtj5g | 1659604328
  | 1659604327 | 172.20.3.35 | 172.20.3.35 | fa9168ca-f366-446d-9a97-384d6b1694c3 | 172.20.12.53 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:12:07.078 +00:00] [DEBUG] [querynode/impl.go:64] ["Get QueryNode component state done"] [stateCode=Healthy] | milvus-cluster | 2022-08-04T09:12:07.078501694Z | cn-hangzhou.172.20.3.35 | iZbp1eexno0clhh9gq1tr0Z | milvus-querynode-598bf85b4-jtj5g | 1659604328
  | 1659604327 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:12:06.777 +00:00] [DEBUG] [querynode/flow_graph_service_time_node.go:71] ["update tSafe:"] [collectionID=435055279543681025] [tSafe=435055316584890369] [tSafe_p=2022/08/04 09:12:06.572 +00:00] [channel=by-dev-rootcoord-dml_12_435055279543681025v0] | milvus-cluster | 2022-08-04T09:12:06.777295819Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604329
  | 1659604329 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:12:08.251 +00:00] [DEBUG] [querynode/impl.go:64] ["Get QueryNode component state done"] [stateCode=Healthy] | milvus-cluster | 2022-08-04T09:12:08.251305921Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604332
  | 1659604337 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:12:16.776 +00:00] [DEBUG] [querynode/flow_graph_service_time_node.go:71] ["update tSafe:"] [collectionID=435055279543681025] [tSafe=435055319219175425] [tSafe_p=2022/08/04 09:12:16.621 +00:00] [channel=by-dev-rootcoord-dml_12_435055279543681025v0] | milvus-cluster | 2022-08-04T09:12:16.776564762Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604338
  | 1659604337 | 172.20.3.35 | 172.20.3.35 | fa9168ca-f366-446d-9a97-384d6b1694c3 | 172.20.12.53 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:12:17.078 +00:00] [DEBUG] [querynode/impl.go:64] ["Get QueryNode component state done"] [stateCode=Healthy] | milvus-cluster | 2022-08-04T09:12:17.078565422Z | cn-hangzhou.172.20.3.35 | iZbp1eexno0clhh9gq1tr0Z | milvus-querynode-598bf85b4-jtj5g | 1659604340
  | 1659604339 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:12:18.251 +00:00] [DEBUG] [querynode/impl.go:64] ["Get QueryNode component state done"] [stateCode=Healthy] | milvus-cluster | 2022-08-04T09:12:18.251377566Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604341
  | 1659604347 | 172.20.3.35 | 172.20.3.35 | fa9168ca-f366-446d-9a97-384d6b1694c3 | 172.20.12.53 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:12:27.078 +00:00] [DEBUG] [querynode/impl.go:64] ["Get QueryNode component state done"] [stateCode=Healthy] | milvus-cluster | 2022-08-04T09:12:27.078349998Z | cn-hangzhou.172.20.3.35 | iZbp1eexno0clhh9gq1tr0Z | milvus-querynode-598bf85b4-jtj5g | 1659604349
  | 1659604347 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:12:26.776 +00:00] [DEBUG] [querynode/flow_graph_service_time_node.go:71] ["update tSafe:"] [collectionID=435055279543681025] [tSafe=435055321840615425] [tSafe_p=2022/08/04 09:12:26.621 +00:00] [channel=by-dev-rootcoord-dml_12_435055279543681025v0] | milvus-cluster | 2022-08-04T09:12:26.776899794Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604350
  | 1659604349 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:12:28.251 +00:00] [DEBUG] [querynode/impl.go:64] ["Get QueryNode component state done"] [stateCode=Healthy] | milvus-cluster | 2022-08-04T09:12:28.251345672Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604350
  | 1659604355 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:12:34.435 +00:00] [DEBUG] [querynode/impl.go:64] ["Get QueryNode component state done"] [stateCode=Healthy] | milvus-cluster | 2022-08-04T09:12:34.436066641Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604356
  | 1659604356 | 172.20.3.35 | 172.20.3.35 | fa9168ca-f366-446d-9a97-384d6b1694c3 | 172.20.12.53 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:12:36.724 +00:00] [DEBUG] [querynode/impl.go:64] ["Get QueryNode component state done"] [stateCode=Healthy] | milvus-cluster | 2022-08-04T09:12:36.72444848Z | cn-hangzhou.172.20.3.35 | iZbp1eexno0clhh9gq1tr0Z | milvus-querynode-598bf85b4-jtj5g | 1659604358
  | 1659604357 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:12:36.775 +00:00] [DEBUG] [querynode/flow_graph_service_time_node.go:71] ["update tSafe:"] [collectionID=435055279543681025] [tSafe=435055324449210369] [tSafe_p=2022/08/04 09:12:36.572 +00:00] [channel=by-dev-rootcoord-dml_12_435055279543681025v0] | milvus-cluster | 2022-08-04T09:12:36.775785646Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604359
  | 1659604357 | 172.20.3.35 | 172.20.3.35 | fa9168ca-f366-446d-9a97-384d6b1694c3 | 172.20.12.53 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:12:37.078 +00:00] [DEBUG] [querynode/impl.go:64] ["Get QueryNode component state done"] [stateCode=Healthy] | milvus-cluster | 2022-08-04T09:12:37.078376323Z | cn-hangzhou.172.20.3.35 | iZbp1eexno0clhh9gq1tr0Z | milvus-querynode-598bf85b4-jtj5g | 1659604358
  | 1659604359 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:12:38.251 +00:00] [DEBUG] [querynode/impl.go:64] ["Get QueryNode component state done"] [stateCode=Healthy] | milvus-cluster | 2022-08-04T09:12:38.251328446Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604362
  | 1659604362 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:12:41.176 +00:00] [DEBUG] [querynode/flow_graph_filter_dm_node.go:93] ["Filter invalid message in QueryNode"] [traceID=ac627df5a979960] | milvus-cluster | 2022-08-04T09:12:41.176449833Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604365
  | 1659604362 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:12:41.176 +00:00] [DEBUG] [querynode/flow_graph_filter_dm_node.go:93] ["Filter invalid message in QueryNode"] [traceID=ac627df5a979960] | milvus-cluster | 2022-08-04T09:12:41.176472812Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604365
  | 1659604362 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:12:41.176 +00:00] [DEBUG] [querynode/flow_graph_filter_dm_node.go:93] ["Filter invalid message in QueryNode"] [traceID=ac627df5a979960] | milvus-cluster | 2022-08-04T09:12:41.17647687Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604365
  | 1659604362 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:12:41.176 +00:00] [DEBUG] [querynode/flow_graph_filter_dm_node.go:93] ["Filter invalid message in QueryNode"] [traceID=ac627df5a979960] | milvus-cluster | 2022-08-04T09:12:41.176480165Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604365
  | 1659604362 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:12:41.176 +00:00] [DEBUG] [querynode/flow_graph_filter_dm_node.go:93] ["Filter invalid message in QueryNode"] [traceID=ac627df5a979960] | milvus-cluster | 2022-08-04T09:12:41.176483402Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604365
  | 1659604362 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:12:41.176 +00:00] [DEBUG] [querynode/flow_graph_filter_dm_node.go:93] ["Filter invalid message in QueryNode"] [traceID=ac627df5a979960] | milvus-cluster | 2022-08-04T09:12:41.176486435Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604365
  | 1659604362 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:12:41.248 +00:00] [DEBUG] [querynode/flow_graph_insert_node.go:194] ["insertNode operator"] ["insert size"=10000] ["insert offset"=20000] ["segment id"=435055299795091457] [collection=435055279543681025] [channel=by-dev-rootcoord-dml_12_435055279543681025v0] | milvus-cluster | 2022-08-04T09:12:41.248548907Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604365
  | 1659604362 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:12:41.317 +00:00] [DEBUG] [querynode/flow_graph_insert_node.go:369] ["Do insert done"] [len=10000] [collectionID=435055279543681025] [segmentID=435055299795091457] | milvus-cluster | 2022-08-04T09:12:41.317524196Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604365
  | 1659604367 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:12:46.776 +00:00] [DEBUG] [querynode/flow_graph_service_time_node.go:71] ["update tSafe:"] [collectionID=435055279543681025] [tSafe=435055327070650369] [tSafe_p=2022/08/04 09:12:46.572 +00:00] [channel=by-dev-rootcoord-dml_12_435055279543681025v0] | milvus-cluster | 2022-08-04T09:12:46.776793985Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604368
  | 1659604367 | 172.20.3.35 | 172.20.3.35 | fa9168ca-f366-446d-9a97-384d6b1694c3 | 172.20.12.53 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:12:47.078 +00:00] [DEBUG] [querynode/impl.go:64] ["Get QueryNode component state done"] [stateCode=Healthy] | milvus-cluster | 2022-08-04T09:12:47.07833061Z | cn-hangzhou.172.20.3.35 | iZbp1eexno0clhh9gq1tr0Z | milvus-querynode-598bf85b4-jtj5g | 1659604370
  | 1659604369 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:12:48.251 +00:00] [DEBUG] [querynode/impl.go:64] ["Get QueryNode component state done"] [stateCode=Healthy] | milvus-cluster | 2022-08-04T09:12:48.251366396Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604371
  | 1659604377 | 172.20.3.35 | 172.20.3.35 | fa9168ca-f366-446d-9a97-384d6b1694c3 | 172.20.12.53 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:12:57.078 +00:00] [DEBUG] [querynode/impl.go:64] ["Get QueryNode component state done"] [stateCode=Healthy] | milvus-cluster | 2022-08-04T09:12:57.078325165Z | cn-hangzhou.172.20.3.35 | iZbp1eexno0clhh9gq1tr0Z | milvus-querynode-598bf85b4-jtj5g | 1659604379
  | 1659604377 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:12:56.777 +00:00] [DEBUG] [querynode/flow_graph_service_time_node.go:71] ["update tSafe:"] [collectionID=435055279543681025] [tSafe=435055329692090369] [tSafe_p=2022/08/04 09:12:56.572 +00:00] [channel=by-dev-rootcoord-dml_12_435055279543681025v0] | milvus-cluster | 2022-08-04T09:12:56.777924342Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604380
  | 1659604379 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:12:58.251 +00:00] [DEBUG] [querynode/impl.go:64] ["Get QueryNode component state done"] [stateCode=Healthy] | milvus-cluster | 2022-08-04T09:12:58.251409522Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604380
  | 1659604385 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:13:04.435 +00:00] [DEBUG] [querynode/impl.go:64] ["Get QueryNode component state done"] [stateCode=Healthy] | milvus-cluster | 2022-08-04T09:13:04.43607472Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604386
  | 1659604386 | 172.20.3.35 | 172.20.3.35 | fa9168ca-f366-446d-9a97-384d6b1694c3 | 172.20.12.53 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:13:06.724 +00:00] [DEBUG] [querynode/impl.go:64] ["Get QueryNode component state done"] [stateCode=Healthy] | milvus-cluster | 2022-08-04T09:13:06.724449123Z | cn-hangzhou.172.20.3.35 | iZbp1eexno0clhh9gq1tr0Z | milvus-querynode-598bf85b4-jtj5g | 1659604388
  | 1659604387 | 172.20.3.35 | 172.20.3.35 | fa9168ca-f366-446d-9a97-384d6b1694c3 | 172.20.12.53 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:13:07.078 +00:00] [DEBUG] [querynode/impl.go:64] ["Get QueryNode component state done"] [stateCode=Healthy] | milvus-cluster | 2022-08-04T09:13:07.078474061Z | cn-hangzhou.172.20.3.35 | iZbp1eexno0clhh9gq1tr0Z | milvus-querynode-598bf85b4-jtj5g | 1659604388
  | 1659604387 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:13:06.776 +00:00] [DEBUG] [querynode/flow_graph_service_time_node.go:71] ["update tSafe:"] [collectionID=435055279543681025] [tSafe=435055332313268225] [tSafe_p=2022/08/04 09:13:06.571 +00:00] [channel=by-dev-rootcoord-dml_12_435055279543681025v0] | milvus-cluster | 2022-08-04T09:13:06.77614862Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604389
  | 1659604389 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:13:08.251 +00:00] [DEBUG] [querynode/impl.go:64] ["Get QueryNode component state done"] [stateCode=Healthy] | milvus-cluster | 2022-08-04T09:13:08.251381473Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604392
  | 1659604397 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:13:16.778 +00:00] [DEBUG] [querynode/flow_graph_service_time_node.go:71] ["update tSafe:"] [collectionID=435055279543681025] [tSafe=435055334947815425] [tSafe_p=2022/08/04 09:13:16.621 +00:00] [channel=by-dev-rootcoord-dml_12_435055279543681025v0] | milvus-cluster | 2022-08-04T09:13:16.778179379Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604398
  | 1659604397 | 172.20.3.35 | 172.20.3.35 | fa9168ca-f366-446d-9a97-384d6b1694c3 | 172.20.12.53 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:13:17.078 +00:00] [DEBUG] [querynode/impl.go:64] ["Get QueryNode component state done"] [stateCode=Healthy] | milvus-cluster | 2022-08-04T09:13:17.078368089Z | cn-hangzhou.172.20.3.35 | iZbp1eexno0clhh9gq1tr0Z | milvus-querynode-598bf85b4-jtj5g | 1659604400
  | 1659604399 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:13:18.251 +00:00] [DEBUG] [querynode/impl.go:64] ["Get QueryNode component state done"] [stateCode=Healthy] | milvus-cluster | 2022-08-04T09:13:18.251397058Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604401
  | 1659604407 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:13:26.775 +00:00] [DEBUG] [querynode/flow_graph_service_time_node.go:71] ["update tSafe:"] [collectionID=435055279543681025] [tSafe=435055337569255425] [tSafe_p=2022/08/04 09:13:26.621 +00:00] [channel=by-dev-rootcoord-dml_12_435055279543681025v0] | milvus-cluster | 2022-08-04T09:13:26.776128421Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604410
  | 1659604407 | 172.20.3.35 | 172.20.3.35 | fa9168ca-f366-446d-9a97-384d6b1694c3 | 172.20.12.53 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:13:27.078 +00:00] [DEBUG] [querynode/impl.go:64] ["Get QueryNode component state done"] [stateCode=Healthy] | milvus-cluster | 2022-08-04T09:13:27.078389212Z | cn-hangzhou.172.20.3.35 | iZbp1eexno0clhh9gq1tr0Z | milvus-querynode-598bf85b4-jtj5g | 1659604409
  | 1659604409 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:13:28.251 +00:00] [DEBUG] [querynode/impl.go:64] ["Get QueryNode component state done"] [stateCode=Healthy] | milvus-cluster | 2022-08-04T09:13:28.251423173Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604410
  | 1659604411 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:13:30.777 +00:00] [DEBUG] [querynode/flow_graph_filter_dm_node.go:93] ["Filter invalid message in QueryNode"] [traceID=3140e4bcedf73f27] | milvus-cluster | 2022-08-04T09:13:30.77726826Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604413
  | 1659604411 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:13:30.777 +00:00] [DEBUG] [querynode/flow_graph_filter_dm_node.go:93] ["Filter invalid message in QueryNode"] [traceID=3140e4bcedf73f27] | milvus-cluster | 2022-08-04T09:13:30.777293303Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604413
  | 1659604411 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:13:30.777 +00:00] [DEBUG] [querynode/flow_graph_filter_dm_node.go:93] ["Filter invalid message in QueryNode"] [traceID=3140e4bcedf73f27] | milvus-cluster | 2022-08-04T09:13:30.77730463Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604413
  | 1659604411 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:13:30.777 +00:00] [DEBUG] [querynode/flow_graph_filter_dm_node.go:93] ["Filter invalid message in QueryNode"] [traceID=3140e4bcedf73f27] | milvus-cluster | 2022-08-04T09:13:30.77730804Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604413
  | 1659604411 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:13:30.777 +00:00] [DEBUG] [querynode/flow_graph_filter_dm_node.go:93] ["Filter invalid message in QueryNode"] [traceID=3140e4bcedf73f27] | milvus-cluster | 2022-08-04T09:13:30.777311306Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604413
  | 1659604411 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:13:30.777 +00:00] [DEBUG] [querynode/flow_graph_filter_dm_node.go:93] ["Filter invalid message in QueryNode"] [traceID=3140e4bcedf73f27] | milvus-cluster | 2022-08-04T09:13:30.777324567Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604413
  | 1659604411 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:13:30.842 +00:00] [DEBUG] [querynode/flow_graph_insert_node.go:194] ["insertNode operator"] ["insert size"=10000] ["insert offset"=30000] ["segment id"=435055299795091457] [collection=435055279543681025] [channel=by-dev-rootcoord-dml_12_435055279543681025v0] | milvus-cluster | 2022-08-04T09:13:30.842399143Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604413
  | 1659604411 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:13:30.935 +00:00] [DEBUG] [querynode/flow_graph_insert_node.go:369] ["Do insert done"] [len=10000] [collectionID=435055279543681025] [segmentID=435055299795091457] | milvus-cluster | 2022-08-04T09:13:30.936015425Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604413
  | 1659604415 | 172.20.3.67 | 172.20.3.67 | 708a48c3-046d-4fda-a75f-6bc148f5898d | 172.20.10.186 | querynode | stdout | milvusdb/milvus:v2.1.0 | [2022/08/04 09:13:34.435 +00:00] [DEBUG] [querynode/impl.go:64] ["Get QueryNode component state done"] [stateCode=Healthy] | milvus-cluster | 2022-08-04T09:13:34.436164088Z | cn-hangzhou.172.20.3.67 | iZbp17zrjws1w2c925h48kZ | milvus-querynode-598bf85b4-h2nnd | 1659604416

**Comment by JackLCL** [comment]
Related discussion：https://github.com/milvus-io/milvus/discussions/18533
