### ISSUE TITLE
[Bug]: Query performance not stable

### ISSUE THREAD

**Issue by psc0606** [milvus-io/milvus#18537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.1, java-sdk-2.1.0-beta4
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: proxy(3 pods, 1core and 8G per pod), all coord(root, data, index) (1pod, 4core and 8G), datanode(10 pods, 2core and 8G per pod), indexnode(20 pods, 4core and 4G per pod), querynode(30pods, 1core and 8G per pod)
- GPU: None
- Others: None
```

### Current Behavior

We have three collection, each of them about 5200w entities, each of entity has two fields: 128dim float vector field, and int64 id field.  We load collection with default 2 shards, default 1 replicaNumber, index: IVF_FLAT. The QPS of query request is very low (about 10 QPS, my query request param: topK: 1000, metric_type: L2, params: {\"nprobe\":64}, ). Insert and delete request are also low(<10QPS).  

But we get unstable query time cost(P99 about 400ms~600ms), normal query only cost 40 ~ 60ms. 

We have milvus monitor:
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/7888889/182996010-6683d3c0-b12f-4917-ab1b-8ea1a1dfb6ab.png">
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/7888889/182996146-b791d0f2-d9b2-49b1-8f33-f8a939d08307.png">
<img width="972" alt="image" src="https://user-images.githubusercontent.com/7888889/182996285-eb2be674-9519-41d6-86a4-3e1e8a72ce70.png">
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/7888889/182996345-6275575c-3649-4984-98bd-9289429d7884.png">
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/7888889/182996375-0cfa6392-6ccd-4435-9059-68867450bbe4.png">
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/7888889/182996468-ad81f2e9-f230-49ec-b559-41b56baa5517.png">
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/7888889/182996517-c25ffe8d-0fce-44dd-a176-a60574b5f5be.png">
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/7888889/182996569-e8865cb5-7f40-446d-8bbf-f88d0877ae7d.png">
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/7888889/182996629-96f8287d-7f51-4935-8835-5074c3f12e4c.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/7888889/182996686-9ad5c4d4-3fe3-4151-88e0-03e8168d665e.png">

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/7888889/182996823-6bf38d47-12b1-4d09-aff0-37180465fb84.png">
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/7888889/182996864-6d756c8a-c3c5-47f6-88b1-7052b81e5118.png">

From querynode, I can see query latency is very high:
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/7888889/182997184-0c4e9b3c-45f2-4eec-9428-060343d70f9f.png">
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/7888889/182997220-7543a34a-a8f5-431e-8b30-4e79e46b1ffe.png">

What's happen to my querynodes, only a few querynodes have rather high query latency. **Finally, at 23:41 made our cluster not responsible. Then milvus cluster seems crash.**

### Expected Behavior

I expect a relative stable query cost, and a relative balanced query time cost. 

### Milvus Log

[milvus-2022-08-04_23.log](https://github.com/milvus-io/milvus/files/9274406/milvus-2022-08-04_23.log)

**Comment by yanliang567** [comment]
@psc0606 thank you for the issue. How many vectors(nq) did you use in each search request?  Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @czs007 
/unassign

**Comment by psc0606** [comment]
Only one vector in each search request.

**Comment by psc0606** [comment]
@yanliang567 I have already update the whole milvus log.

**Comment by psc0606** [comment]
Another interesting thing is when I load collection with two replicaNumer, the query time P99 will only half of the before. But when I add more replicaNumber, the query time cost can not be better.

**Comment by yanliang567** [comment]
@czs007 any updates
