### ISSUE TITLE
 After I insert the vector with admin, the count value does not change.

### ISSUE THREAD

**Issue by Bennu-Li** [milvus-io/milvus#1853]
**Describe the bug**
After I insert the vector with admin, the count value does not change.
This value will only change after the page is manually refreshed

![image](https://user-images.githubusercontent.com/53458891/78215737-cd138800-74ea-11ea-95e3-0c6d2418b9b8.png)

**Comment by shanghaikid** [comment]
@Bennu-Li  please update milvus-admin docker, and see if it is fixed.

**Comment by tinkerlin** [comment]
@
