### ISSUE TITLE
[Bug]: num_entities is 0 after insert and flush 

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#18555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220805-c5c3392
- Deployment mode(standalone or cluster): cluster with Kafka as MQ
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.1.0.dev103
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

run test_e2e.py after installation, it shows that the num_entities is 0 after flush
```
23:25:59          # flush
23:25:59          t0 = time.time()
23:25:59          num_entities, check_result = collection_w.flush(timeout=180)
23:25:59          assert check_result
23:25:59  >       assert num_entities == len(data[0]) + entities
23:25:59  E       assert 0 == 3000
23:25:59  E         +0
23:25:59  E         -3000
```

### Expected Behavior

expect num_entities is 3000

### Steps To Reproduce

```markdown
1. install Milvus with Kafka as MQ
2. run test_e2e.py
```

### Milvus Log

[artifacts-rootcoord-pod-failure-210-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9286036/artifacts-rootcoord-pod-failure-210-server-logs.tar.gz)

[artifacts-rootcoord-pod-failure-210-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9286037/artifacts-rootcoord-pod-failure-210-pytest-logs.tar.gz)

**Comment by yanliang567** [comment]
@XuanYang-cn is it somthing related to what we going to do for flush and num_entities?
/assign @XuanYang-cn 
/unassign

**Comment by XuanYang-cn** [comment]
@zhuwenxing What's PyMilvus version?

**Comment by zhuwenxing** [comment]
> What's PyMilvus version?

 pymilvus==2.1.0.dev103

**Comment by XuanYang-cn** [comment]
![image](https://user-images.githubusercontent.com/51370125/183595082-976d3888-6532-4738-9132-2aa1c21b11d4.png)

DataCoord consumes the first 2 msgs failed of `time tick channel`, so DC isn't aware of any numRows change, the  segment row num remains zero in DC's meta. According to the the error message, Kafka client is unable to connect to server, seems like the server is unavailable then.

**Comment by xiaofan-luan** [comment]
Any plan we will fix it soon? 
Empty segment is critical since it will cause flush issues

**Comment by XuanYang-cn** [comment]
@xiaofan-luan No, we trust Pulsar/Kafka to be reliable, it's kafka who's losing data, there is nothing we can do about it.

Maybe one thing, make sure kafka **truly started** before using milvus.

Empty segments are not the problem here, losing data is.

**Comment by XuanYang-cn** [comment]
@zhuwenxing recommend closing this issue, and reopening if anything similar happens.

/unassign
/assign @zhuwenxing

**Comment by zhuwenxing** [comment]
Not reproduced anymore, so close it!
