### ISSUE TITLE
[Bug]: err: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (215849469 vs. 104857600)

### ISSUE THREAD

**Issue by xinghycc** [milvus-io/milvus#18558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):standalone 
- SDK version(e.g. pymilvus v2.0.0rc2):attu 2.1.0
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 32G
- GPU: No
- Others: docker
```

### Current Behavior

When ATTU is used to query data, the page and Milvus server are abnormal. The following information is displayed:
1.The database contains more than 100,000 data.
2.Query criteria  id>0.
3.An error occurred while executing the query.
err: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (215849469 vs. 104857600) 

### Steps To Reproduce

```markdown
1.The database contains more than 100,000 data.
2.Open the attu.
2.Query criteria  id>0.
3.An error occurred while executing the query.
```

### Milvus Log

err: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (215849469 vs. 104857600) , 
/go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace 
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:232 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).Call 
/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:241 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Query 
/go/src/github.com/milvus-io/milvus/internal/proxy/task_query.go:347 github.com/milvus-io/milvus/internal/proxy.(*queryTask).queryShard.func1 
/go/src/github.com/milvus-io/milvus/internal/proxy/task_policies.go:55 github.com/milvus-io/milvus/internal/proxy.roundRobinPolicy 
/go/src/github.com/milvus-io/milvus/internal/proxy/task_query.go:370 github.com/milvus-io/milvus/internal/proxy.(*queryTask).queryShard 
/go/src/github.com/milvus-io/milvus/internal/proxy/task_query.go:243 github.com/milvus-io/milvus/internal/proxy.(*queryTask).Execute.func1.1 
/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 golang.org/x/sync/errgroup.(*Group).Go.func1 
/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit

**Comment by yanliang567** [comment]
@xinghycc thank you for the issue. It seems that you are trying to retrieve all the data in the collection, which exceeds the maxsize of one gprc size. I suggest you not  retrieve so much data at a time, as it also might cause some memory issue. Try to retrieve less data, e.g. id in [1,2,3,4,5]

/assign @xinghycc 
/unassign
