### ISSUE TITLE
[Bug]: The standalone milvus-etcd has a high memory footprint.

### ISSUE THREAD

**Issue by xinghycc** [milvus-io/milvus#18560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.0
- Deployment mode(standalone or cluster):standalone 
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.1.0
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 32
- GPU: no
- Others: docker-compose
```

### Current Behavior

When top checked the information, it was found that MilVUS-ETCD occupied a high amount of memory for a long time, reaching about 80%, and the amount of data in the database was about 200,000. At the beginning of Milvus, ETCD occupied about 28% of the memory. Through the query, the memory began to rise and reached about 80%. Stop the query, and the memory footprint does not decrease.

### Steps To Reproduce

```markdown
1.Start mivlus service, docker-compose up -d.
2.Run the Linux top command.
```

### Milvus Log

![8209f74924a9925802b2e743608df5e](https://user-images.githubusercontent.com/9926539/183552863-23ce7784-7d23-4cf1-97e2-05808d29d895.png)

**Comment by LoveEachDay** [comment]
@xinghycc Etcd has two usages in milvus:
1. metadata store
2. service discovery

From the the `top output` and your vector data size, the meta store cannot be that large. We've tested 100 million vector data (128 dimension) in milvus, which only have 300M memory usage for etcd.

By default the volume is kept when you run `docker-compose down`.  Did you run several times of `docker-compose up` which will use the same etcd volume?

Could you copy the `docker-compose.yaml` to another directory, and try `docker-compose up` to verify the memory usage? And did you keep the default config for etcd like the following snippet:
```
environment:
  - ETCD_AUTO_COMPACTION_MODE=revision
  - ETCD_AUTO_COMPACTION_RETENTION=1000
  - ETCD_QUOTA_BACKEND_BYTES=4294967296
```
Enable auto compaction will significantly decrease the etcd memory usage.

**Comment by xiaofan-luan** [comment]
@LoveEachDay why we didn't set ETCD_AUTO_COMPACTION_RETENTION to smaller by default?

**Comment by LoveEachDay** [comment]
@xiaofan-luan This is a balance between performance and memory usage. If you set compaction retention to a smaller value, it'll affect the normal etcd operation.

> @LoveEachDay why we didn't set ETCD_AUTO_COMPACTION_RETENTION to smaller by default?

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan This is a balance between performance and memory usage. If you set compaction retention to a smaller value, it'll affect the normal etcd operation.
> 
> > @LoveEachDay why we didn't set ETCD_AUTO_COMPACTION_RETENTION to smaller by default?

From the user scenario etcd takes 25.6G memory, do we think it is normal or abnormal? unless user create collection frequently. otherwise I don't see a reason we update etcd so frequently?

**Comment by LoveEachDay** [comment]
> From the user scenario etcd takes 25.6G memory, do we think it is normal or abnormal? unless user create collection frequently. otherwise I don't see a reason we update etcd so frequently?

Of course it's abnormal that etcd uses 25.6GB memory. We cannot reproduce using the above procedures. We need @xinghycc to clarify the steps and give us more detail information.

**Comment by xiejiang0133** [comment]
I had the same problem, 6 million data of 512dim,  uses 25GB+ memory.

**Comment by xiejiang0133** [comment]
> I had the same problem, 6 million data of 512dim, uses 25GB+ memory.



> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```gfm
> - Milvus version:2.1.0
> - Deployment mode(standalone or cluster):standalone 
> - SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.1.0
> - OS(Ubuntu or CentOS): CentOS
> - CPU/Memory: 32
> - GPU: no
> - Others: docker-compose
> ```
> 
> ### Current Behavior
> When top checked the information, it was found that MilVUS-ETCD occupied a high amount of memory for a long time, reaching about 80%, and the amount of data in the database was about 200,000. At the beginning of Milvus, ETCD occupied about 28% of the memory. Through the query, the memory began to rise and reached about 80%. Stop the query, and the memory footprint does not decrease.
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> ```gfm
> 1.Start mivlus service, docker-compose up -d.
> 2.Run the Linux top command.
> ```
> 
> ### Milvus Log
> ![8209f74924a9925802b2e743608df5e](https://user-images.githubusercontent.com/9926539/183552863-23ce7784-7d23-4cf1-97e2-05808d29d895.png)
> 
> ### Anything else?
> _No response_

Did you solve your problem?

**Comment by xiaofan-luan** [comment]
> ### Expected Behavior

might be the similar issue of https://github.com/etcd-io/etcd/issues/12548
if you KV stored is relatively large, then etcd will take many extra memory.

**Comment by xiaofan-luan** [comment]
@LoveEachDay @SimFG  Is there a way to analysis the most memory consuming KVs in etcd?

**Comment by SimFG** [comment]
@xiaofan-luan I don't know this kind of way. Maybe we can check the amount of the big size KVs in this scene.
