### ISSUE TITLE
Memory usage exceeded expectations

### ISSUE THREAD

**Issue by xiaoweiqb** [milvus-io/milvus#1856]
**Describe the bug**
IVF_SQ8_H index vector data was inserted in 5100w 512d IVF_SQ8_H, the memory footprint exceeded the theoretical value by 50%, reaching 46GB, and nq=1 nprode=32 query QPS only 4~5 under 50 concurrent

**Steps/Code to reproduce behavior**
Insert data written in the Java SDK program, 10, one thousand times, inserts, and build a CreateIndex and preLoadCollection, midway stop once inserted, because building index stuck, when the data amount is 1500 w, then after being milvus CPU utilization rate down to normal, and then to insert the data, and stop preLoadCollection operation, manually create indexes only 10 w round, until the insert data volume of 5100 w, then perform a preLoadCollection,Memory up to 46GB, CPU usage is normal 0-12%
Jmeter was used for the pressure test, 50 concurrent /s nq=1, carrying its own project business, and adding the printed log. It was calculated that the query time of miluvs was 4000-9000ms, and the CPU usage rate decreased from 1200% at the beginning to about 800%

**Expected behavior**
5000W 512d vector data memory occupies about 30GB, 50 concurrent /s QPS to achieve your expected test results

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
Baode server
CentOS Linux release 7.6.1810 (Core)
Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz *2
GeForce GTX 1080 Ti *4
128GB Memory
- Method of installation (Docker, or from source)
installation of Docker
- Milvus version (v0.3.1, or v0.4.0)
Milvus version is 0.7.1
- Milvus configuration (Settings you made in `server_config.yaml`)

version: 0.2
server_config:
  address: 0.0.0.0
  port: 19530
  deploy_mode: single
  time_zone: UTC+8
  web_port: 19121
db_config:
  backend_url: sqlite://:@:/
  preload_table:
storage_config:
  primary_path: /var/lib/milvus
  secondary_path:
metric_config:
  enable_monitor: false
  address: 127.0.0.1
  port: 9091
cache_config:
  cpu_cache_capacity: 64
  insert_buffer_size: 1
  cache_insert_data: false
engine_config:
  use_blas_threshold: 1100
  gpu_search_threshold: 1000
gpu_resource_config:
  enable: true
  cache_capacity: 2
  search_resources:
    - gpu0
    - gpu1
    - gpu2
    - gpu3
  build_index_resources:
    - gpu0
    - gpu1
    - gpu2
    - gpu3
tracing_config:
  json_config_path:
wal_config:
  enable: true
  recovery_error_ignore: true
  buffer_size: 256
  wal_path: /var/lib/milvus/wal

**Screenshots**
![image](https://user-images.githubusercontent.com/11550475/78225005-09031900-74fc-11ea-8e80-d58b23a9f964.png)
50 concurrent /s mivlus-debug logs
![image](https://user-images.githubusercontent.com/11550475/78225105-38198a80-74fc-11ea-9eb0-f9564589ff2c.png)
No load CPU utilization
![image](https://user-images.githubusercontent.com/11550475/78225135-4bc4f100-74fc-11ea-9b87-0bf3a60e5cd6.png)
Set the number of
![image](https://user-images.githubusercontent.com/11550475/78225302-921a5000-74fc-11ea-958b-57a16a9f280e.png)
![image](https://user-images.githubusercontent.com/11550475/78225326-99d9f480-74fc-11ea-85c1-b4f1e8220d50.png)
tables infomation

**Additional context**

**Comment by shengjun1985** [comment]
You set the index_file_size 1024(M).
After built index with IVF_SQ8_H, each index file may be 1024 * 30% ≈ 300(M).
But the log "file type: 3 size:56184535 byte" showed that the index files size were only 53(M).

One possible reason is that you manually built index too often.
And it produced too many small index files, which leaded to inefficiency.

If the data is static, you can insert all the data, then call CreateIndex() once.
If the data is stream, you can call CreateIndex() once, then insert the data.
Please try again.
If you have any questions, please continue to ask.

**Comment by cydrain** [comment]
In Milvus, the memory consumption during query is bigger than original index size.

Use 50,000,000 128-dim sift-1b dataset as an example.
```
raw vector size: 24G
index size: 6.5G (index type SQ8H)
uids size: 381M
bloomfilter size: 464M
index related total size = 6.5G + 381M + 464M = 7.3G
```
When SQ8H query, some data need be duplicated between CPU and GPU, including:
```
uids data: 381M
Quantizer data: 341M
others:
```
So the memory consumption of SQ8H query  will be at lease: 7.3G + 381M + 341M = 8.0G
It's close to our observation 8.4G (compare the memory usage before and after SQ8H query)

**Comment by xiaoweiqb** [comment]
tks
