### ISSUE TITLE
[Bug]: Persisted Data in S3 Gets deleted after milvus is brought down and restarted

### ISSUE THREAD

**Issue by guptajayesh** [milvus-io/milvus#18574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.0
- Deployment mode(standalone or cluster): Cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.1
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I deployed Milvus on EKS with external s3 configured, After I perform the Create Collection and Insert Operations, The Data is stored in Milvus efficiently and is visible in s3 buckets
However, If I bring down the Milvus deployment and restart it with the same configuration, Milvus deletes the old files in s3 and shows preexisting collection doesn't exist, Is that expected behaviour?

### Expected Behavior

Milvus Loads pre existing collection even after restart

### Steps To Reproduce

```markdown
Helm Deploy Milvus with External S3 using Access Key on EKS
Delete Milvus Deployment on EKS
ReDeploy Milvus on eks with the same configuration
```

**Comment by yanliang567** [comment]
@guptajayesh I guess you enabled the delete pvc policy in deployment. @LoveEachDay could you please give some guide here?

/assign @LoveEachDay 
/unassign

**Comment by LoveEachDay** [comment]
@guptajayesh Could you provide the helm values for your installment? You can run the following command:
```
helm get values <release> --all > helm-values.yaml
```
And upload the `helm-values.yaml` here, do remember to remove the access key and secret key in the `helm-values.yaml` file for your external s3 config section.

**Comment by jackfischer** [comment]
Hello @LoveEachDay we have just experienced exactly this.

We are on Milvus v2.2.10 and helm chart 4.0.25.
[values-prod.yaml.txt](https://github.com/milvus-io/milvus/files/11782707/values-prod.yaml.txt)

**Comment by yanliang567** [comment]
> Hello @LoveEachDay we have just experienced this.
> 
> We are on Milvus v2.2.10 and helm chart 4.0.25. [values-prod.yaml.txt](https://github.com/milvus-io/milvus/files/11782707/values-prod.yaml.txt)

please try to file a new issue for v2.2.10
