### ISSUE TITLE
[Enhancement]: Independent partition load and release

### ISSUE THREAD

**Issue by jercas** [milvus-io/milvus#18579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

  Independent partition control, partitions are loaded and released independently of each other influences. And when querying the collection, query all currently loaded partitions together.

### Why is this needed?

  For online vector retrieval tasks, we need to update the vector frequently. But independent partial loading and releasing are not supported for now. This makes the operation of updating the vector unable to be seamless, and the old part must be released before the new part is loaded, which will interrupt the continuous online query.

  We hope that Milvus can load the new partition at the same time a's the old partition is loaded, and then release the old partition so that the vector update has no effect on online query tasks.

### Anything else?

![milvus_feature](https://user-images.githubusercontent.com/27855802/183799934-ed67f9f0-e10a-4784-aadc-599cbc3fece5.jpeg)

**Comment by sunby** [comment]
Thanks for the advice. Same as https://github.com/milvus-io/milvus/issues/18242
