### ISSUE TITLE
[Bug]:   parse minio key error during binlog gc

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#18580]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

[ERROR] [datacoord/garbage_collector.go:143] [\"parse segment id error\"] [infoKey=usr-7Pc5npSqRa6B-ed7ceXtMg/in01-fdeac4ddcf7c430/delta_log/435129779953860609/435129779953860610/435139120830611457/435140055221665793] [error=\"usr-7Pc5npSqRa6B-ed7ceXtMg/in01-fdeac4ddcf7c430/delta_log/435129779953860609/435129779953860610/435139120830611457/435140055221665793 is not a valid binlog path\"] [stack=\"github.com/milvus-io/milvus/internal/datacoord.(*garbageCollector).scan\\n\\t/go/src/github.com/milvus-io/milvus/internal/datacoord/garbage_collector.go:143\\ngithub.com/milvus-io/milvus/internal/datacoord.(*garbageCollector).work\\n\\t/go/src/github.com/milvus-io/milvus/internal/datacoord/garbage_collector.go:96\"]\n","stream":"stdout","time":"2022-08-08T05:40:05.875624898Z"}

**Comment by xiaofan-luan** [comment]
is this still a issue?
