### ISSUE TITLE
[Bug]: queryCoord stays in "Initializing" state "reloadFromKV: taskStateInfo and triggerTaskInfo are inconsistent"

### ISSUE THREAD

**Issue by datenhahn** [milvus-io/milvus#18595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvusdb/milvus:master-20220810-4d46aa5
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-2.1.0
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: (Requests --> Limits)
     - proxy: 200mCPU / 4Gi --> 4CPU / 4Gi
     - rootCoordinator: 200mCPU / 2Gi --> 4CPU / 2Gi
     - queryCoordinator: 200mCPU / 4Gi --> 4CPU / 4Gi
     - indexCoordinator: 250mCPU / 2Gi --> 4CPU / 2Gi
     - indexNode: 250mCPU / 2Gi --> 4CPU / 2Gi
     - dataCoordinator: 250mCPU / 2Gi --> 4CPU / 2Gi
     - dataNode: 1CPU / 4Gi --> 16CPU / 4Gi
     - queryNode: 4CPU / 8Gi --> 16CPU / 8Gi
     - etcd (3 Replicas): 250mCPU / 2Gi --> 4CPU / 2Gi
     - pulsar - zookeeper (3 replicas):  250mCPU / 1536Mi --> 4CPU / 1536Mi
     - pulsar - bookkeeper (3 replicas): 250mCPU / 6Gi --> 16CPU / 6Gi
     - pulsar - broker: 250mCPU / 6Gi --> 16CPU / 6Gi
     - pulsar - proxy:  250mCPU / 2Gi --> 4CPU / 2Gi
     - minio (4 replicas): 250mCPU / 2Gi --> 4CPU / 2Gi
- GPU:
00:01.3 Non-VGA unclassified device: Intel Corporation 82371AB/EB/MB PIIX4 ACPI (rev 08)
00:03.0 VGA compatible controller: Amazon.com, Inc. Device 1111

- Others:
```

### Current Behavior

After some time milvus shuts down and after the restart it cannot start up again (queryCoord stays in state "Initializing"). We insert about 20-60 vectors per Minute and have lots of different partitions.

```
 name:\"embeddings\" description:\"vector\" data_type:FloatVector type_params:<key:\"dim\" value:\"100\" > > > 
collectionID:435190257603051521 load_meta:<collectionID:435190257603051521 partitionIDs:435190259255345153 partit
ionIDs:435190259936395265 partitionIDs:435190260604600321 partitionIDs:435190266987806721 partitionIDs:4351902576
03051522 partitionIDs:435190258572984321 > replicaID:435189643092426754 "]
[2022/08/10 14:18:41.206 +00:00] [ERROR] [querycoord/task_scheduler.go:269] ["reloadFromKV: taskStateInfo and tri
ggerTaskInfo are inconsistent"] [stack="github.com/
milvus-io/milvus/internal/querycoord.(*TaskScheduler).reloadFromKV\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:269\ngithub.com/milvus-io/milvus/internal/querycoord.newTaskScheduler\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:205\ngithub.com/milvus-io/milvus/internal/querycoord.(*QueryCoord).Init.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/query_coord.go:214\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:68\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:59\ngithub.com/milvus-io/milvus/internal/querycoord.(*QueryCoord).Init\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/query_coord.go:137\ngithub.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:227\ngithub.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:96\ngithub.com/milvus-io/milvus/cmd/components.(*QueryCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/query_coord.go:50\ngithub.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runQueryCoord.func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:186"]
[2022/08/10 14:20:12.459 +00:00] [WARN] [roles/healthz_handler.go:100] ["component is unhealthy"] [state=Initializing]
[2022/08/10 14:20:22.459 +00:00] [WARN] [roles/healthz_handler.go:100] ["component is unhealthy"] [state=Initializing]
[2022/08/10 14:20:32.459 +00:00] [WARN] [roles/healthz_handler.go:100] ["component is unhealthy"] [state=Initializing]
[2022/08/10 14:20:42.459 +00:00] [WARN] [roles/healthz_handler.go:100] ["component is unhealthy"] [state=Initializing]
```

### Expected Behavior

Milvus should not shutdown and if it shutsdown it should be able to recover from failure and result in an up and running state afterwards.

### Steps To Reproduce

```markdown
1. On an EKS Kubernetes cluster deploy a Milvus cluster
2. Insert about 20-60 Vectors (100 Dimensions) and also delete Vectors at the same rate and occasionally query it. Insert in multiple Partitions. Create the partitions on the fly when needed.
3. After some time milvus shuts down with errors during flushing and it cannot recover from this (all services recover, but querycoord not)
4. This happens indefinite
```

### Milvus Log

 name:\"embeddings\" description:\"vector\" data_type:FloatVector type_params:<key:\"dim\" value:\"100\" > > > 
collectionID:435190257603051521 load_meta:<collectionID:435190257603051521 partitionIDs:435190259255345153 partit
ionIDs:435190259936395265 partitionIDs:435190260604600321 partitionIDs:435190266987806721 partitionIDs:4351902576
03051522 partitionIDs:435190258572984321 > replicaID:435189643092426754 "]
[2022/08/10 14:18:41.206 +00:00] [ERROR] [querycoord/task_scheduler.go:269] ["reloadFromKV: taskStateInfo and tri
ggerTaskInfo are inconsistent"] [stack="github.com/
milvus-io/milvus/internal/querycoord.(*TaskScheduler).reloadFromKV\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:269\ngithub.com/milvus-io/milvus/internal/querycoord.newTaskScheduler\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:205\ngithub.com/milvus-io/milvus/internal/querycoord.(*QueryCoord).Init.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/query_coord.go:214\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:68\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:59\ngithub.com/milvus-io/milvus/internal/querycoord.(*QueryCoord).Init\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/query_coord.go:137\ngithub.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:227\ngithub.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:96\ngithub.com/milvus-io/milvus/cmd/components.(*QueryCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/query_coord.go:50\ngithub.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runQueryCoord.func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:186"]
[2022/08/10 14:20:12.459 +00:00] [WARN] [roles/healthz_handler.go:100] ["component is unhealthy"] [state=Initializing]
[2022/08/10 14:20:22.459 +00:00] [WARN] [roles/healthz_handler.go:100] ["component is unhealthy"] [state=Initializing]
[2022/08/10 14:20:32.459 +00:00] [WARN] [roles/healthz_handler.go:100] ["component is unhealthy"] [state=Initializing]
[2022/08/10 14:20:42.459 +00:00] [WARN] [roles/healthz_handler.go:100] ["component is unhealthy"] [state=Initializing]

**Comment by datenhahn** [comment]
Here are the full logs (134MB tar.gz): https://drive.google.com/file/d/1W32Ag4d3qUt-N1Trg3YJlmq7Ep2IJGQ8/view?usp=sharing

**Comment by weiliu1031** [comment]
root cause:  query coord init blocks due to task queue limit.
1. according to the log, data coord flush lots of segment files
![image](https://user-images.githubusercontent.com/108661493/184052624-9c991f16-a5e5-47a6-b2e1-f519f2fc2123.png)

2. query coord triggers lots of handoff task, but all failed, due to
`[2022/08/10 12:34:00.635 +00:00] [ERROR] [querycoord/task.go:2454] ["assignInternalTask: assign segment to node failed"] [error="no available queryNode to allocate"] [stack="github.com/milvus-io/milvus/internal/querycoord.assignInternalTask\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:2454\ngithub.com/milvus-io/milvus/internal/querycoord.(*loadSegmentTask).reschedule\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:1413\ngithub.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).waitActivateTaskDone.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:792\ngithub.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).waitActivateTaskDone\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:904"]
[2022/08/10 12:34:00.635 +00:00] [ERROR] [querycoord/task.go:1415] ["loadSegment reschedule failed"] [excludeNodes="[44]"] [taskID=435189643092433748] [error="no available queryNode to allocate"] [stack="github.com/milvus-io/milvus/internal/querycoord.(*loadSegmentTask).reschedule\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:1415\ngithub.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).waitActivateTaskDone.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:792\ngithub.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).waitActivateTaskDone\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:904"]`

3. all triggered but failed tasks persist on meta store

4. after then, query coord restart, and reload more than 1024 task, then init progress blocks.
 `func newTaskQueue() *taskQueue {
	return &taskQueue{
		tasks:    list.New(),
		maxTask:  1024,
		taskChan: make(chan int, 1024),
	}
}`

**Comment by weiliu1031** [comment]
> root cause: query coord init blocks due to task queue limit.
> 
> 1. according to the log, data coord flush lots of segment files
>    ![image](https://user-images.githubusercontent.com/108661493/184052624-9c991f16-a5e5-47a6-b2e1-f519f2fc2123.png)
> 2. query coord triggers lots of handoff task, but all failed, due to
>    `[2022/08/10 12:34:00.635 +00:00] [ERROR] [querycoord/task.go:2454] ["assignInternalTask: assign segment to node failed"] [error="no available queryNode to allocate"] [stack="github.com/milvus-io/milvus/internal/querycoord.assignInternalTask\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:2454\ngithub.com/milvus-io/milvus/internal/querycoord.(*loadSegmentTask).reschedule\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:1413\ngithub.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).waitActivateTaskDone.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:792\ngithub.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).waitActivateTaskDone\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:904"] [2022/08/10 12:34:00.635 +00:00] [ERROR] [querycoord/task.go:1415] ["loadSegment reschedule failed"] [excludeNodes="[44]"] [taskID=435189643092433748] [error="no available queryNode to allocate"] [stack="github.com/milvus-io/milvus/internal/querycoord.(*loadSegmentTask).reschedule\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:1415\ngithub.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).waitActivateTaskDone.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:792\ngithub.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).waitActivateTaskDone\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:904"]`
> 3. all triggered but failed tasks persist on meta store
> 4. after then, query coord restart, and reload more than 1024 task, then init progress blocks.
>    `func newTaskQueue() *taskQueue { return &taskQueue{ tasks:    list.New(), maxTask:  1024, taskChan: make(chan int, 1024), } }`

by the way, there seems to be much more segments, what's the amount of data?

**Comment by weiliu1031** [comment]
can you explain： 10 + 10 * 12 + 10 * 12 * 52 + 10 * 365 = 10020 partitions ？

**Comment by datenhahn** [comment]
Ah sorry, I just copy and pasted my notes :) . We originally planned for partitions with different sizings and therefore (hopefully) different search times, smaller partitions resulting in faster searches, larger partitions in slower searches, but other results (more data) depending on the usecase. In our customers case these are documents with a date (e.g. 2022-08-10) and there are document approx. for the last 10 years which should be vectorized and added to milvus.

Our plan is to add every document to these four partitions. Every document is added to ALL of the partitions (so it shows up in the relevant searches). e.g. a document with date 2022-08-12 would be added to the partitions.

2022
2022-08
2022-08-KW32
2022-08-12

For 10 years this results (approx.) in the following amount of partitions:

10 yearly partitions (one for every year in the ten years)
10 * 12  monthly partitions (one for every month in the ten years)
10 * 52 (one for every week in the ten years (I just realized I have a calculation error there in the other calculation))
10 * 365 (one for every day)

So the actual number would be approx. 4300 partitions.

**Comment by yanliang567** [comment]
yes, if you had less partitions and only had one partition online(loaded) at the same time. Just in case that the max number of partition for a collection is 4096.

**Comment by datenhahn** [comment]
This seems to be fixed, stability / self healing of Milvus has increased much in the last weeks (last test was with v2.1.2, closing ticket.
