### ISSUE TITLE
[Bug]: 2.0.0中文文档中有字母大小写错误

### ISSUE THREAD

**Issue by DazzlingGalaxy** [milvus-io/milvus#18596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

我是在Bing中搜milvus，搜索结果中有官方gitee地址，打开并手动定位到https://gitee.com/milvus-io/milvus#%E5%90%AF%E5%8A%A8-milvus，然后点"安装 Milvus 单机版"，跳转到https://milvus.io/cn/docs/v2.0.0/install_standalone-docker.md，再通过左侧目录手动进入https://milvus.io/cn/docs/v2.0.0/search.md，再手动定位到https://milvus.io/cn/docs/v2.0.0/search.md#%E8%BF%9B%E8%A1%8C%E5%90%91%E9%87%8F%E6%90%9C%E7%B4%A2，Python代码中consistency_level="strong"写错了，正确的应该是consistency_level="Strong"，这里大小写敏感，写成小写s会报错，看了源码中search()方法的consistency_level参数的介绍才知道中文文档写错了，介绍原话'if no consistency level was specified, search will use the consistency level when you create the collection.'，再看2.0.0中文文档中Collection()创建集合时的代码(https://milvus.io/cn/docs/v2.0.0/create_collection.md#Create-a-collection-with-the-schema)，发现是大小写错了。

从github的README进入2.0.x的英文文档(https://milvus.io/docs/v2.0.x/search.md#Conduct-a-vector-search)，英文文档没写错，是consistency_level="Strong"，所以是中文翻译人员翻译时不小心写错了吗？

最后再问一下，无论是英文文档还是中文文档，现在已经有2.1.x版Milvus了，为什么从github或gitee的README中打开文档，还是跳转到2.0.x的文档？

这个问题本想在gitee中反馈，因为中文文档是从gitee的README中打开的，但gitee中这个仓库不让提Issue，还好文档页面右上角有"提交bug"的按钮，点击后来到github。

**Comment by yanliang567** [comment]
@DazzlingGalaxy https://milvus.io/ is the only official home page for milvus. If there are any issues in it, please feel free to file new tickets. thanks.
