### ISSUE TITLE
[Bug]: Failed to enable auth in Milvus 2.1

### ISSUE THREAD

**Issue by yuliu-eric** [milvus-io/milvus#18607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): AWS Linux
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Tried to enable auth by adding the following config in value.yaml through helm (followed by this [instruction](https://milvus.io/docs/v2.1.x/authenticate.md#Authenticate-User-Access)), but doesn't seem to work (can still connect to milvus w/o username & password).

```
common:
  security:
    authorizationEnabled: "true"
```

**Comment by binbinlv** [comment]
@yuliu-eric 

May I know how could you judge whether it is connected or not connected?

Just a reminder: interface "connect" returns successfully could not say milvus is connected. The "connect" interface could always return successfully even the user info is right or not. (the check is not at this interface)

Need call another api like utility.list_collections() to confirm whether the milvus is connected successfully or not.

**Comment by LoveEachDay** [comment]
@yuliu-eric Enable authorization with helm chart, you need explicitly set:
```
authorization:
   enabled: true
```
in your values.

**Comment by yuliu-eric** [comment]
> 

Yes, that works, thank you!

Would be great to document the instructions for different env, e.g, through helm or docker, etc. The current one `Set common.security.authorizationEnabled in milvus.yaml as true when [configuring Milvus](https://milvus.io/docs/v2.1.x/configure-docker.md) to enable authentication.` from this [instruction](https://milvus.io/docs/v2.1.x/authenticate.md#Authenticate-User-Access) doesn't work for helm.

> @yuliu-eric Enable authorization with helm chart, you need explicitly set:
> 
> ```
> authorization:
>    enabled: true
> ```
> 
> in your values.

**Comment by YiyunNi** [comment]
Thanks for the suggestion @yuliu-eric ! I have added the instruction in the doc in this [PR](https://github.com/milvus-io/milvus-docs/pull/1731).

**Comment by divyajaincs** [comment]
where we need to add this for authorization in config? 
```
authorization:
   enabled: true
```
