### ISSUE TITLE
[Feature]: Support labelling/filtering based on collections 2.1 metrics monitoring

### ISSUE THREAD

**Issue by yuliu-eric** [milvus-io/milvus#18605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Currently milvus 2.1 supports labeling/filtering based on pod/node when view the metrics on Grafana, and it will be super helpful/required to support such labels at collection level when multiple collections exist in the same milvus cluster.

**Comment by LoveEachDay** [comment]
@yuliu-eric Originally we had labeled some metrics with `collection name` or `collection id` as a label, but this will largely increase the metrics cardinality which will bring high memory pressure for prometheus. 

So we remove the `collection name` and `collection id` label.

**Comment by yuliu-eric** [comment]
Got it. Then is there other options to handle this scenario?

**Comment by xiaofan-luan** [comment]
should be done in 2.2 already.
We support collection level search/query/mutation latency

**Comment by xiaofan-luan** [comment]
see #19686
