### ISSUE TITLE
[Bug]: There is a wrong name metrics in milvus-dashboard.json

### ISSUE THREAD

**Issue by dzqoo** [milvus-io/milvus#18610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![be2cd1c2c80daf28973c02b3f190216](https://user-images.githubusercontent.com/8862305/184096346-5b7e668e-b0fa-40cc-abc2-b09015e4e06b.jpg)

### Expected Behavior

change "milvus_proxy_sq_lantency_bucket" to  "milvus_proxy_sq_latency_bucket"

### Steps To Reproduce

```markdown
NA
```

### Milvus Log

NA

**Comment by LoveEachDay** [comment]
@dzqoo This typo has been fixed. You can check the `milvus_dashboard.json` in the master branch from [here](https://github.com/milvus-io/milvus/blob/f22fc4f2369c7299f9f7df6d0b32764cd8d2a3a6/deployments/monitor/grafana/milvus-dashboard.json#L303).
