### ISSUE TITLE
[Bug]: datanode occuplied memory too much，and not release after 12 hours

### ISSUE THREAD

**Issue by hukang6677** [milvus-io/milvus#18622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.0
- Deployment mode(standalone or cluster):dockercompose——  cluster
- SDK version(e.g. pymilvus v2.0.0rc2):milvus-sdk-java  2.1.0-beta4
- OS(Ubuntu or CentOS): Ubuntu 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

我是这样操作的：
建了5个Collection，每次insert插入5万条数据，每个Collection插入200次，最后每个Collection里面都是1000万条数据，总共5000万条。只做了插入数据操作，没有创建索引，没有加载Collection。12小时后datanode消耗的内存也没释放。共有四个datanode节点，总共消耗20G内存。
![微信图片_20220812110811](https://user-images.githubusercontent.com/102129512/184279701-a1715ff5-dc3e-41bc-93ac-2e614e94ef2e.png)

### Expected Behavior

四个datanode节点消耗的内存能够释放，自动处理机制或milvus需要怎么配置

### Steps To Reproduce

```markdown
我是这样操作的：
建了5个Collection，每次insert插入5万条数据，每个Collection插入200次，最后每个Collection里面都是1000万条数据，总共5000万条。只做了插入数据操作，没有创建索引，没有加载Collection。12小时后datanode消耗的内存也没释放。
共有四个datanode节点，总共消耗20G内存。
```

### Milvus Log

[milvus.log.gz](https://github.com/milvus-io/milvus/files/9313471/milvus.log.gz)

**Comment by soothing-rain** [comment]
@hukang6677 Hey this certainly looks abnormal. Can you dump your DataNode's heap and send the file to us?

For example:
```curl -s http://${data_node_ip}:9091/debug/pprof/heap > heap_snapshot.heap``` 
(Let me know if you don't know how to do this)

**Comment by yanliang567** [comment]
@hukang6677 any updates for suggested above?
