### ISSUE TITLE
[Bug]: milvus2.1 crash etcd cluster

### ISSUE THREAD

**Issue by psc0606** [milvus-io/milvus#18623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.1, java-sdk-2.1.0-beta4
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: proxy(3 pods, 1core and 8G per pod), all coord(root, data, index) (1pod, 4core and 8G), datanode(10 pods, 2core and 8G per pod), indexnode(20 pods, 4core and 4G per pod), querynode(30pods, 1core and 8G per pod)
- GPU: None
- Others: None

- etcd cluster: 3 node, 8G per node
```

### Current Behavior

Milvus 2.1 crashed when etcd cluster leader oom, and etcd can not recovery any more.

Why etcd cluster oom? Maybe some resouce leak.

![image](https://user-images.githubusercontent.com/7888889/184287113-e82e8197-b085-4529-9401-968b9fe0352d.png)

![image](https://user-images.githubusercontent.com/7888889/184287360-becafc25-6560-43c0-a038-21b2162363e1.png)
![image](https://user-images.githubusercontent.com/7888889/184287389-ce764e0f-085a-41bc-95de-5b2bf41ed2ea.png)

### Milvus Log

[milvus.log.zip](https://github.com/milvus-io/milvus/files/9313713/milvus.log.zip)

compressed in macOs.

**Comment by LoveEachDay** [comment]
@psc0606 How do you install the milvus cluster? And could you provide the etcd config or the env?

**Comment by yanliang567** [comment]
/assign @psc0606 
could you please provide more info as requested above?

/unassign

**Comment by psc0606** [comment]
Finally, we decreased the snapshot-count of etcd from 100000(default) to 20000. The problem disappeared.
