### ISSUE TITLE
[Bug]: [Nightly] Query failed reporting "fail to search on all shard leaders, err=fail to Query, QueryNode ID = 3, reason=Query 3 failed, reason failed to get service timestamp"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#18621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master (174130c)
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.2.0.dev6
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Query failed reporting "<MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Query, QueryNode ID = 3, reason=Query 3 failed, reason failed to get service timestamp, taskID = 435223142315102254, collectionID = 435223144464646145, err=cannot found tSafer, vChannel = by-dev-rootcoord-delta_255_4...... (api_request.py:40)"

### Expected Behavior

query successfully

### Steps To Reproduce

Nightly:
https://jenkins.milvus.io:18080/blue/rest/organizations/jenkins/pipelines/Milvus%20Nightly%20CI/branches/master/runs/31/nodes/123/steps/143/log/?start=0

```python
    @pytest.mark.tags(CaseLabel.L0)
    def test_query_partition(self):
        """
        target: test query on partition
        method: create a partition and query
        expected: verify query result
        """
        collection_w = self.init_collection_wrap(name=cf.gen_unique_str(prefix))
        partition_w = self.init_partition_wrap(collection_wrap=collection_w)
        df = cf.gen_default_dataframe_data()
        partition_w.insert(df)
        assert collection_w.num_entities == ct.default_nb
        partition_w.load()
        res = df.iloc[:2, :1].to_dict('records')
        collection_w.query(default_term_expr, partition_names=[partition_w.name],
                           check_task=CheckTasks.check_query_results, check_items={exp_res: res})
```

### Milvus Log

1.  milvus log:[artifacts-milvus-standalone-nightly-31-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/31/artifact/artifacts-milvus-standalone-nightly-31-pymilvus-e2e-logs.tar.gz)
2. Failed timeline: [2022-08-11T19:02:24.165Z] [gw5] [ 29%] FAILED testcases/test_query.py::TestQueryParams::test_query_partition 
3. collection name: query_KVCB0Y2D

**Comment by binbinlv** [comment]
@congqixia 
hello, congqi,
Could you help to have a look first? thanks.

**Comment by weiliu1031** [comment]
some information to sync:
1. we found two delta channel's seek position point to same channel.
![4nHt3EXXzV](https://user-images.githubusercontent.com/108661493/184342844-8fa2bc58-6f51-41e4-a9cd-79fc99a28d41.jpg)
2. when load segment, it build delta channel from seek position.  so we get one delta channel, and another delta channel can be loaded.
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/108661493/184343729-22a12b2d-2a20-404d-8500-35791c2bde09.png">

3. when we do query. it fails, because one delta channel is not loaded. 

one more issue needs track down: 
1. why two delta channel has same channel in seek position ?

**Comment by binbinlv** [comment]
Same issue appears again:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/35/pipeline/123
1. milvus log: [artifacts-milvus-standalone-nightly-35-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/35/artifact/artifacts-milvus-standalone-nightly-35-pymilvus-e2e-logs.tar.gz)
2. collection name: search_collection_iwVbsWYR
3. Failed timeline: [2022-08-13T19:01:27.035Z] [gw3] [ 30%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_with_ndarray[8-False-True] 
4. error message:
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 1 failed, reason failed to get service timestamp, taskID = 435268425230094618, collectionID = 435268427930140673, err=cannot found tSafer, vChannel = by-dev-rootcoord-delta_255_435268427930140673v1 err %!w(<nil>))>

**Comment by binbinlv** [comment]
Same issue appears again:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/38/pipeline/123
1. milvus log:
[artifacts-milvus-standalone-nightly-38-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/38/artifact/artifacts-milvus-standalone-nightly-38-pymilvus-e2e-logs.tar.gz)
2. collection name: query_Pl5vAVUI
3. Failed time: [2022-08-15T15:04:23.324Z] [gw5] [ 30%] FAILED testcases/test_query.py::TestQueryParams::test_query_partition

**Comment by binbinlv** [comment]
@weiliu1031 @congqixia 
any progress here?
Thanks.

**Comment by weiliu1031** [comment]
Final result:
cause there are too much collection, so two shard in on collection has the same pchannel.
each insert message has been send to all two vahnnels.
![3p9Oedo0Yg](https://user-images.githubusercontent.com/108661493/185073643-f47ae9be-44ab-4ffe-88dc-903fef975e42.jpg)

**Comment by binbinlv** [comment]
It has not been reproduced for a period of time, fixed. So close it.
