### ISSUE TITLE
[Bug]: Huge S3 storage usage

### ISSUE THREAD

**Issue by zigapk** [milvus-io/milvus#18638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.0
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.0.2
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 8 cores, 64 Gb RAM
- GPU: /
- Others: /
```

### Current Behavior

I inserted 12 150 630 entities into a collection with 1 partition. Each entity has the following fields:
- primary key,
- 4096 bits long binary vector with FLAT index,
- 2 more Int64 fields with an ascending index.

By my calculations, this is around 6 Gb of data and I'd expect the database to use a few tens of gigabytes at most.

However, the database's S3 storage usage is upwards of 260 Gb at the moment and still rising a long time after I stopped inserting the data. I've searched the documentation for the reason for this and did not find an answer. The Milvus sizing tool produces similar numbers to my calculations.

My retention duration is set to 0 and I am using custom S3 storage, however this also happened when using minio as a storage provider.

I'd  truly appreciate some help regarding this.

### Expected Behavior

I expect the database to use a few tens of gigabytes at most.

### Steps To Reproduce

```markdown
1. Create a schema with 4096 bit log binary vector.
2. Insert a lot of entities (in a range of millions).
3. Observe the S3 storage usage rise.
```

### Milvus Log

Logs exported with `docker-compose logs --tail=10000` available [here](https://transfer.sh/50jdQO/milvus.log).

**Comment by xiaofan-luan** [comment]
hi @zigapk , thanks for the feedback.
Usually the S3 data size should be a few times larger than the calculation, but in your case that is far more larger than expected.
Did your try any tool to do the analysis about the S3 storage consumption?

**Comment by xiaofan-luan** [comment]
/assign @zhagnlu 
could you help on investigating?

**Comment by zigapk** [comment]
@xiaofan-luan do you have any particular tool in mind? I only used `df` linux command to measure storage usage on my local machine and read the S3 storage usage from my cloud provider's web console (Digital Ocean).

When using local storage, most of the storage seems to be used up by files inside `volumes/minio/a-bucket/files` and `volumes/minio/.minio.sys`.

**Comment by xiaofan-luan** [comment]
AWS S3 command tool might help
aws s3 ls s3://${path}/ --recursive --human-readable --summarize

All milvus related files is stored ad volumes/minio/a-bucket/files

**Comment by zigapk** [comment]
@xiaofan-luan data from the `aws ls` command is available [here](https://transfer.sh/tdJlnp/spaces.txt).

**Comment by zigapk** [comment]
@xiaofan-luan I'd like to inform you that the disk space started to drop now. Still wondering why it had to go into the terabytes.

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan I'd like to inform you that the disk space started to drop now. Still wondering why it had to go into the terabytes.

The garbage collection policy will be working only after "common.retentionDuration", by default is 5 days.
So even data is deleted, or compaction happened, the data will be recycled  5 days later.
This is for time travel usage, we are considering to change the default retention time to 1 day so data can be recycled faster.

**Comment by zhagnlu** [comment]
after analyzing file list by aws ls, storage layout:
![image](https://user-images.githubusercontent.com/11935707/186859326-222ac397-8498-4c9d-b081-7a30b70419ce.png)
it shows insert binlog has about 140G and stats binlog has about 26G, it is exceptionly huge. 
but no delta log,  so  not the deleted reason, then  find lots of segment has same size like figure show:
![image](https://user-images.githubusercontent.com/11935707/186860488-1471bfc2-6fa2-4be7-a3bc-9a9fc352f3d8.png)
so it may be compaction reason.

**Comment by zhagnlu** [comment]
the server log shows compaction timeout happens for losts of times:
![image](https://user-images.githubusercontent.com/11935707/186861406-eaa9fb16-b8cf-4e2d-812d-ae34697fdcf0.png)
and lots of remote s3  error
![image](https://user-images.githubusercontent.com/11935707/186862206-8463715f-31ee-4b1c-8b4d-92962091f0ea.png)
so it may be s3 storage server not stable, it causes compaction timeout lots of times. and  garbage collector only trigger every 24h, so files can not be clean up in time.

**Comment by zhagnlu** [comment]
this problem has been fixed as https://github.com/milvus-io/milvus/issues/18674
