### ISSUE TITLE
Searching params check for Annoy

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#1863]
**Describe the bug**
`search_k` value can not be set `string/empty/-1`, it's not expected, and if `search_k` not existed in `search_param`, the search status returned is OK

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
```
Milvus Release version: v0.7.1, built at 2020-04-02 16:21.32, with OpenBLAS library.
You are using Milvus GPU edition
Last commit id: 7ccfa5b9f09931104a7ff7340001bf08321126fc
```
**Screenshots**

**Additional context**

**Comment by shengjun1985** [comment]
The valid range of search_k is updated to {-1} ∪ [topk, int64::max]
Doc: https://github.com/milvus-io/docs/pull/508
Code: https://github.com/milvus-io/milvus/pull/1855
