### ISSUE TITLE
[Bug]: Milvus search hangs after system restart

### ISSUE THREAD

**Issue by dilip814** [milvus-io/milvus#18630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.2
- Deployment mode(standalone or cluster):Standlone
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 20.04
- CPU/Memory: Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz / 112GB
- GPU: Tesla P100
- Others:
```

### Current Behavior

Most of the time if we restart system when Milvus docker container was running, after system restart collection search hangs up

### Expected Behavior

Milvus collection search should not hang

### Steps To Reproduce

```markdown
1. Start Milvus using docker-compose
2. Enrol few vectors
3. Run similarity search usecase
4. Restart system
5. Run docker-compose to start Milvus
6. Run similarity search usecase

Observation: collection.search hangs.
```

### Milvus Log

[milvus.log](https://github.com/milvus-io/milvus/files/9315690/milvus.log)

**Comment by yanliang567** [comment]
@dilip814 thank you for the issue, could you please retry with milvus 2.1.1?
if it reproduced, please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation

/assign @dilip814 
/unassign

**Comment by dilip814** [comment]
Thanks @yanliang567 for response. I will try with Milvus 2.1.1
