### ISSUE TITLE
[Bug]: Load Balance is not working

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#18644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. DML Channel and Shardleader is not balanced as expected when we add more querynode to the cluster.
2. Segment is not balanced either, need to check the reason.

Currently we rely on memory reported by querynode to do load balance, which is not reliable.
1) the memory we collect is from process memory usage, but there maybe some garbages in golang or memory allocator so it's not accurate
2) the memory limit has to be machine memory or the cgroup limit, but we've seen many user didn't set the correct value onto it.

My suggestions is:
1) Add mechanism to balance dml channel (not sure if there is one)
2) balance segment by entity count (better to balance by data size)
3) Add more cluster expand, shrink test on it. make sure the API of balance, get Segment location is work as expect.

### Expected Behavior

1. when we add a querynode into the cluster, the segment should be balanced a few minutes by there data size.
2. we should be able to trigger loadbalance by a cli command

**Comment by yanliang567** [comment]
keep it

**Comment by yanliang567** [comment]
keep it open

**Comment by yanliang567** [comment]
keep it active
