### ISSUE TITLE
[Bug]: When I changed milvus from v2.0.1 to v2.1.0，I got a worse performance(rt) in my scene.

### ISSUE THREAD

**Issue by dzqoo** [milvus-io/milvus#18645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.0 
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.1.0
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 32 cores/756GBi 
- GPU: 
- Others:
```

### Current Behavior

(1)When I test the performance of milvus search in my scene,I got the following result of rt : 
- Client performance
nq topk  rt
10 10 0.5071010589599609
10 10 0.5250134468078613
10 10 0.5025763511657715
10 10 0.5275528430938721
10 10 0.5605242252349854
10 10 0.3852427005767822
10 10 0.44965672492980957
10 10 0.18056321144104004
- server performance (from promethus grafana)
Search Latency：![image](https://user-images.githubusercontent.com/8862305/184568630-949fcb52-ce2b-4c23-8a8a-52a18db2c455.png)
Search in Queue Latency：![image](https://user-images.githubusercontent.com/8862305/184568568-d484ce44-f862-476d-a554-e7003ba132ea.png)
Search Segment Latency：![image](https://user-images.githubusercontent.com/8862305/184568485-d489d7f2-2161-47cc-80cf-d2d530d3f0fb.png)
CpuUsage：
![image](https://user-images.githubusercontent.com/8862305/184568797-cab8a799-afa3-4695-84c5-1e15460e734e.png)
Segment Loaded Num：![image](https://user-images.githubusercontent.com/8862305/184569066-6f4d0d81-069e-4afa-a852-c9a851e5594e.png)

(2)Here are the milvus‘s deployment topology and node's dispose:
![image](https://user-images.githubusercontent.com/8862305/184567457-d41970f3-a15d-481f-82e9-8b9f2652a89b.png)
<img width="368" alt="部署拓扑" src="https://user-images.githubusercontent.com/8862305/184567466-e5bb74c9-1508-4963-b9b0-6f2ca3d3b8e5.png">
(3)Here are the hnsw configuration：
HNSW.(m=32，efconstruction=512)
(4)Here are the search configuration：
ef=512，nq=10，TOPK=10，concurrency=20
(5)Here are the data configuration：
float16 10M  embedding，400 dimension

### Expected Behavior

When I do this test，I expected the rt can not higher than 100ms in my scene，which is higher then 500ms now.

**Comment by yanliang567** [comment]
@dzqoo thank you for the issue. 2 quick quetsions:
1. how is the performance when running v2.0.1?
2. how did you deploy milvus cluster v2.1.0? 
Also Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @dzqoo 
/unassign

**Comment by dzqoo** [comment]
@yanliang567 thank for applying.
1. v2.0.1 is better than v2.1.0，but not that better;
2. Yes，it's a clutser deploying by helm.
Here is whole logs in milvus.
[logs.tar.gz](https://github.com/milvus-io/milvus/files/9335331/logs.tar.gz)

**Comment by yanliang567** [comment]
/assign @czs007 
could you please help to take a look?

/unassign @dzqoo

**Comment by xiaofan-luan** [comment]
1. There seems to be a issue a loadbalancer,  only 3 of the 5 node is working. @sunby 
2.  each node takes only 6 cpu cores, from attu each machine seems to have more than 20 cores, does that make sense?

**Comment by xiaofan-luan** [comment]
@dzqoo 
pls do not use multiple replicas. Use 1 replica instead and try

**Comment by xiaofan-luan** [comment]
@dzqoo 
I saw you have 5 querynodes, does they share same machines?
From the attu, 2 of the nodes has 20 cores, the other three has 36 cores, do you know the reason?

**Comment by dzqoo** [comment]
@xiaofan-luan 
Yes, my 5 querynodes share the three machines which two have 32 cores and another has 20 cores.

**Comment by dzqoo** [comment]
> 

1 replica will cause qps decreased. I got that increasing replica will increase the thoughtouput.
