### ISSUE TITLE
[Bug]: oom

### ISSUE THREAD

**Issue by wangnimaa** [milvus-io/milvus#18654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):standalone 
- SDK version(e.g. pymilvus v2.0.0rc2):2.0
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 16G
- GPU: 
- Others:
```

### Current Behavior

we use milvus 2.0,but After a period of use，buffer/cache is so big, then docker is oom。

### Steps To Reproduce

```markdown
-
```

### Milvus Log

-

### Anything else?

-

**Comment by yanliang567** [comment]
@wangnimaa thank you for the issue. could you please share more details about the issue?
1. how many vectors did you insert? what is the dim?
2. how many cpu and memory did you configure for milvus? how much does milvus consume?

if you have metrics and logs for OOM, that would be perfect.   please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation

/assign @wangnimaa 
/unassign

**Comment by yanliang567** [comment]
Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
