### ISSUE TITLE
[Bug]: manual load balance failed

### ISSUE THREAD

**Issue by dzqoo** [milvus-io/milvus#18651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.0 
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus v2.1.0
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 32 cores/765GBi
- GPU: 
- Others:
```

### Current Behavior

When I use python code to load balance ，I get  following error.
`pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=, source nodes and destination nodes must be in the same replica group, source nodes and destination nodes must be in the same replica group)>`

There is my python code.
`from pymilvus import connections, utility
connections.connect(host="********",port=19530)
src_node_id = 6
dst_node_ids = [6,3,14]
sealed_segment_ids = []
utility.load_balance("ann_10m_hnsw", src_node_id, dst_node_ids, sealed_segment_ids)`

querynode6 is in the same replica group as querynode3 and querynode14

What can I do for this error.

**Comment by zhuwenxing** [comment]
we have a test case about load balance.
1. call `collection.get_replicas()` to get groups and find a group that has multi nodes
2. call `utility.get_query_segment_info()` to get segments distribution 
3.  call `utility.load_balance()` to load balance

I have no idea how you make sure 6,3,14 is in one group, and `sealed_segment_ids = []` this statement is also not correct.

```
    @pytest.mark.tags(CaseLabel.L2)
    def test_load_balance_in_one_group(self):
        """
        target: test load balance of collection in one group
        method: init a collection, load with multi replicas and load balance among the querynodes in one group
        expected: load balance successfully
        """
        self._connect()
        querynode_num = len(MilvusSys().query_nodes)
        if querynode_num < 3:
            pytest.skip("skip load balance for multi replicas testcase when querynode number less than 3")
        # init a collection
        c_name = cf.gen_unique_str(prefix)
        collection_w = self.init_collection_wrap(name=c_name)
        nb = 3000
        df = cf.gen_default_dataframe_data(nb)
        collection_w.insert(df)
        # get sealed segments
        collection_w.num_entities
        collection_w.load(replica_number=2)
        # get growing segments
        collection_w.insert(df)
        # get replicas information
        res, _ = collection_w.get_replicas()
        # prepare load balance params
        # find a group which has multi nodes
        group_nodes = []
        for g in res.groups:
            if len(g.group_nodes) >= 2:
                group_nodes = list(g.group_nodes)
                break
        res, _ = self.utility_wrap.get_query_segment_info(c_name)
        segment_distribution = cf.get_segment_distribution(res)
        group_nodes = sorted(group_nodes,
                             key=lambda x: len(
                                 segment_distribution[x]["sealed"])
                             if x in segment_distribution else 0, reverse=True)
        src_node_id = group_nodes[0]
        dst_node_ids = group_nodes[1:]
        sealed_segment_ids = segment_distribution[src_node_id]["sealed"]
        # load balance
        self.utility_wrap.load_balance(collection_w.name, src_node_id, dst_node_ids, sealed_segment_ids)
        # get segments distribution after load balance
        res, _ = self.utility_wrap.get_query_segment_info(c_name)
        segment_distribution = cf.get_segment_distribution(res)
        sealed_segment_ids_after_load_banalce = segment_distribution[src_node_id]["sealed"]
        # assert src node has no sealed segments
        assert sealed_segment_ids_after_load_banalce == []
        des_sealed_segment_ids = []
        for des_node_id in dst_node_ids:
            des_sealed_segment_ids += segment_distribution[des_node_id]["sealed"]
        # assert sealed_segment_ids is subset of des_sealed_segment_ids
        assert set(sealed_segment_ids).issubset(des_sealed_segment_ids)
```

**Comment by dzqoo** [comment]
@zhuwenxing Thank you for applying!
I got my collection's replicas groups and find that every group only have one group_nodes.And I wonder if it is normal.
Here are the output:
`[Group: <group_id:435306513441751155>, <group_nodes:(45,)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_4_435306970076413953v4>, <shard_leader:45>, <shard_nodes:[45]>, Shard: <channel_name:by-dev-rootcoord-dml_5_435306970076413953v5>, <shard_leader:45>, <shard_nodes:[45]>, Shard: <channel_name:by-dev-rootcoord-dml_0_435306970076413953v0>, <shard_leader:45>, <shard_nodes:[45]>, Shard: <channel_name:by-dev-rootcoord-dml_1_435306970076413953v1>, <shard_leader:45>, <shard_nodes:[45]>, Shard: <channel_name:by-dev-rootcoord-dml_2_435306970076413953v2>, <shard_leader:45>, <shard_nodes:[45]>, Shard: <channel_name:by-dev-rootcoord-dml_3_435306970076413953v3>, <shard_leader:45>, <shard_nodes:[45]>]>, Group: <group_id:435306513441751156>, <group_nodes:(33,)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_3_435306970076413953v3>, <shard_leader:33>, <shard_nodes:[33]>, Shard: <channel_name:by-dev-rootcoord-dml_4_435306970076413953v4>, <shard_leader:33>, <shard_nodes:[33]>, Shard: <channel_name:by-dev-rootcoord-dml_5_435306970076413953v5>, <shard_leader:33>, <shard_nodes:[33]>, Shard: <channel_name:by-dev-rootcoord-dml_0_435306970076413953v0>, <shard_leader:33>, <shard_nodes:[33]>, Shard: <channel_name:by-dev-rootcoord-dml_1_435306970076413953v1>, <shard_leader:33>, <shard_nodes:[33]>, Shard: <channel_name:by-dev-rootcoord-dml_2_435306970076413953v2>, <shard_leader:33>, <shard_nodes:[33]>]>, Group: <group_id:435306513441751152>, <group_nodes:(44,)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_4_435306970076413953v4>, <shard_leader:44>, <shard_nodes:[44]>, Shard: <channel_name:by-dev-rootcoord-dml_5_435306970076413953v5>, <shard_leader:44>, <shard_nodes:[44]>, Shard: <channel_name:by-dev-rootcoord-dml_0_435306970076413953v0>, <shard_leader:44>, <shard_nodes:[44]>, Shard: <channel_name:by-dev-rootcoord-dml_1_435306970076413953v1>, <shard_leader:44>, <shard_nodes:[44]>, Shard: <channel_name:by-dev-rootcoord-dml_2_435306970076413953v2>, <shard_leader:44>, <shard_nodes:[44]>, Shard: <channel_name:by-dev-rootcoord-dml_3_435306970076413953v3>, <shard_leader:44>, <shard_nodes:[44]>]>, Group: <group_id:435306513441751154>, <group_nodes:(42,)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_1_435306970076413953v1>, <shard_leader:42>, <shard_nodes:[42]>, Shard: <channel_name:by-dev-rootcoord-dml_2_435306970076413953v2>, <shard_leader:42>, <shard_nodes:[42]>, Shard: <channel_name:by-dev-rootcoord-dml_3_435306970076413953v3>, <shard_leader:42>, <shard_nodes:[42]>, Shard: <channel_name:by-dev-rootcoord-dml_4_435306970076413953v4>, <shard_leader:42>, <shard_nodes:[42]>, Shard: <channel_name:by-dev-rootcoord-dml_5_435306970076413953v5>, <shard_leader:42>, <shard_nodes:[42]>, Shard: <channel_name:by-dev-rootcoord-dml_0_435306970076413953v0>, <shard_leader:42>, <shard_nodes:[42]>]>, Group: <group_id:435306513441751153>, <group_nodes:(43,)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_4_435306970076413953v4>, <shard_leader:43>, <shard_nodes:[43]>, Shard: <channel_name:by-dev-rootcoord-dml_5_435306970076413953v5>, <shard_leader:43>, <shard_nodes:[43]>, Shard: <channel_name:by-dev-rootcoord-dml_0_435306970076413953v0>, <shard_leader:43>, <shard_nodes:[43]>, Shard: <channel_name:by-dev-rootcoord-dml_1_435306970076413953v1>, <shard_leader:43>, <shard_nodes:[43]>, Shard: <channel_name:by-dev-rootcoord-dml_2_435306970076413953v2>, <shard_leader:43>, <shard_nodes:[43]>, Shard: <channel_name:by-dev-rootcoord-dml_3_435306970076413953v3>, <shard_leader:43>, <shard_nodes:[43]>]>]`

**Comment by zhuwenxing** [comment]
From the info, I guess the query node num is 5,shard nums is 6, and replicas number is 5, so each group can only have one node.

**Comment by dzqoo** [comment]
@zhuwenxing Yes, you are right.
Here are other two questions:
- How big the replicas number is suitable？
- If the shard num has an affect in this scene？
Look forward to your reply!

**Comment by zhuwenxing** [comment]
`replicas number` is used to increase the throughput, but it needs to be less than the num of the query node. If you want a large replicas number, you need more query node numbers.

`shard num` is more related to the data node. It is responsible for consuming the inserted data and flushing data to the disk

**Comment by dzqoo** [comment]
@zhuwenxing 
I want to reduce the latency and how can I achieve this? Does adding more query nodes and replicas  works?

**Comment by zhuwenxing** [comment]
You can have a try. But as far as I know, replicas will not reduce the latency for a single request, it is designed to trade more machine resources for greater throughput

**Comment by dzqoo** [comment]
@zhuwenxing Thank you~
