### ISSUE TITLE
[Bug]: [Nightly] Search failed reporting "fail to search on all shard leaders, err=fail to Search, QueryNode ID=4, reason=Search 2 failed, reason query shard(channel)...does not exist"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#18656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master (2bb9961)
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.2.0.dev6
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search failed reporting "fail to search on all shard leaders, err=fail to Search, QueryNode ID=4, reason=Search 2 failed, reason query shard(channel)...does not exist"

### Expected Behavior

No error

### Steps To Reproduce

```markdown
Nightly:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/36/pipeline/155
```

### Milvus Log

1. milvus log: [artifacts-milvus-distributed-kafka-nightly-36-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/36/artifact/artifacts-milvus-distributed-kafka-nightly-36-pymilvus-e2e-logs.tar.gz)
2. collection name: search_collection_W5uR0QHE
3. Failed time: [2022-08-14T15:19:13.943Z] [gw0] [ 44%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_with_dup_primary_key[8-False-False-2]

**Comment by binbinlv** [comment]
Same issue:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/35/pipeline/155

1. milvus log:
[artifacts-milvus-distributed-kafka-nightly-35-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/35/artifact/artifacts-milvus-distributed-kafka-nightly-35-pymilvus-e2e-logs.tar.gz)
2. collection name: search_collection_ASkRL5Js
3. Failed timeline: [2022-08-13T19:11:22.341Z] [gw3] [ 46%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_collection_after_release_load[5000-2-8-False-False]

**Comment by weiliu1031** [comment]
Some info to sync:
![kmWAZ7yffH](https://user-images.githubusercontent.com/108661493/184816420-88ce1bce-8c57-4e5d-a49d-22ca39d8029d.jpg)
1. milvus start with querynode 2 and 4
2. querynode 2 stop suddenly, without cleaning resource, such as it's session
3. querynode 13 start, on same host with querynode 2
4. querycoord with the view 2, 4, 13, when it try to do search on query node 2, failed cause by query node 2 is actually offline

one more thing to track:
when query node crash suddenly, how to avoid the affect to system behavior?

**Comment by NicoYuan1986** [comment]
This issue no longer occurs in master(c58a8d8).
