### ISSUE TITLE
[Bug]: Milvus 1.1.1 search with gpu hang

### ISSUE THREAD

**Issue by moneishkumar** [milvus-io/milvus#18666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: V1.1.1 GPU
- Deployment mode(standalone or cluster): - 
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==1.1.2
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 25GB
- GPU: RTX A3000
- Others: NVIDIA-SMI 510.72, Driver Version: 512.72, CUDA Version: 11.6
```

### Current Behavior

When I try to run the milvus GPU it hangs while searching [ .search() ] and the following error is seen. 
 
Searching ...
Addr [127.0.0.1:19530] search
Rpc error: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Socket closed"
        debug_error_string = "{"created":"@1660151357.798968663","description":"Error received from peer ipv4:127.0.0.1:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Socket closed","grpc_status":14}"
>
        {'API start': '2022-08-10 10:07:51.405065', 'RPC start': '2022-08-10 10:07:51.405323', 'RPC error': '2022-08-10 10:09:17.799484'}
Search failed.  Status(code=<StatusCode.UNAVAILABLE: (14, 'unavailable')>, message='Error occurred. Socket closed')

**Comment by yhmo** [comment]
"Socket closed" indicated the server has crashed.
Possible reason to crash the server: GPU OOM during the search
