### ISSUE TITLE
[Bug]: Some inserted vectors are incorrect

### ISSUE THREAD

**Issue by huuson235** [milvus-io/milvus#18663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.0
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.1.0
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 20 cores intel / 24 GB RAM
- GPU: None
- Others: None
```

### Current Behavior

When I insert 2M vector-512D into Milvus, some vectors are not correct.

For example:

On disk:  [ 0.05308599  0.0808935  -0.02041397  0.02257334  0.00362627  0.09881948 ...]

On milvus: [-0.013106  0.108721 -0.049404  0.007004  0.038336  0.05662  -0.005104 ...]

The below table is Inner Product (IP) results (Expected: IP on Disk is same with IP on Milvus)

| ID_1 | ID_2 | IP_Disk | IP_Milvus | Is same? |
|---|---|---|---|---|
|537200 | 2277169 | -0.055380068719387054 |  -0.055379928311000005 | YES |
|537200 | 2277168 | 0.07101514935493469   |  0.07101542202999997 | YES |
|537200 | 2277170 | 0.0496969148516655     | 0.049697044530000005 | YES |
|537201 | 2277169 | 0.09038154780864716   |  -0.052623724648 | NO |
|537201 | 2277168 | 0.19147896766662598   |  0.049650675962000006 | NO |
|537201 | 2277170 | 0.23121210932731628   |  0.04336227802099999 | NO |
|537202 | 2277169 | 0.009045092388987541  |  0.7695754243069999 | NO |
|537202 | 2277168 | -0.00040660565719008446 | 0.032298678971 | NO |
|537202 | 2277170 | 0.03958938270807266    | 0.0015584101520000025 | NO |
|537215 | 2277169 | 0.15179213881492615    | -0.017708354507999992 | NO |
|537215 | 2277168 | 0.13234451413154602    | 0.12171995942499998 | NO |
|537215 | 2277170 | 0.12216714024543762  |   0.09056603762999998 | NO |
|537216 | 2277169 | 0.12527978420257568   |  -0.056951261155 | NO |
|537216 | 2277168 | 0.08369824290275574    | 0.12280469831 | NO |
|537216 | 2277170 | 0.039908215403556824 |   0.105570667608 | NO |
|537217 | 2277169 | -0.08351980894804001   | -0.083519674034 | YES |
|537217 | 2277168 | 0.056062377989292145  |  0.056062581221999995 | YES |
|537217 | 2277170 | 0.071621373295784     |  0.07162107319899999 | YES |

### Expected Behavior

100% vectors on Milvus are similar to vectors on Disk

### Steps To Reproduce

```markdown
Just insert 2M vector by using method insert()
```

**Comment by yanliang567** [comment]
@huuson235 thank you for the issue. quick questions
1. how did you get the values of ip_disk and ip_milvus?
2. what is the index params 
If possible, could you please share a code snippet to reproduce the issue?

/assign @huuson235 
/unassign

**Comment by huuson235** [comment]
1. I get some incorrect vectors then using numpy to calculate IP_disk, and use method search() of Milvus to calculate IP_milvus
2. Index params here:

**Comment by huuson235** [comment]
1. I get some incorrect vectors then using numpy to calculate IP_disk, and use method search() of Milvus to calculate IP_milvus
```python
# calculate ip_disk
def read_emb_from_disk(image_id):
  with open(str(image_id) + ".npy", "rb") as f:
    emb_np = np.load(f)
  return emb_np

def calc_IP(emb1, emb2):
  cosine = np.sum(emb1 * emb2)
  return cosine

def calc_IP_disk(image_id1, image_id2):
  emb1 = read_emb_from_disk(image_id1)
  emb2 = read_emb_from_disk(image_id2)
  ip_disk = calc_IP(emb1, emb2)
  return ip_disk

# IP Milvus
def calc_IP_milvus(image_id1, image_id2):
    emb1 = milvus.query(f"image_id == {image_id1}", ["embedding"])
    emb1 = np.array(emb1[0]["embedding"])

    emb2 = milvus.query(f"image_id == {image_id2}", ["embedding"])
    emb2 = np.array(emb2[0]["embedding"])
    IP_milvus = calc_IP(emb1, emb2)
    return IP_milvus

ip_disk = calc_IP_disk(image_id1, image_id2)
ip_milvus = calc_IP_milvus(image_id1, image_id2)
```
Index params here:
```python
            index = {
                "index_type": "IVF_FLAT",
                "metric_type": "IP",
                "params": {"nlist": n_list }
            }
```

**Comment by huuson235** [comment]
I am so sorry, it's my bad. My code had bugs. So sorry.
