### ISSUE TITLE
 milvus update account password must inport old password, the question is how to update account password when i forget old account password. 

### ISSUE THREAD

**Issue by yelusion2** [milvus-io/milvus#18670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.0
- Deployment mode(standalone or cluster):standalone cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.1.0 
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

milvus update account password must inport old password, the question is how to update account password when i forget old account password. 

### Expected Behavior

i can use root super account to reset other normal account password.

root super account password i can through a special way to reset (update miluvs.yaml or a tool to update etcd root account data)

### Anything else?

i can use root super account to reset other normal account password.

root super account password i can through a special way to reset (update miluvs.yaml or a tool to update etcd root account data)

**Comment by yelusion2** [comment]
pg参考：
http://postgres.cn/docs/13/sql-alterrole.html
mysql参考：
https://dev.mysql.com/doc/refman/8.0/en/set-password.html

**Comment by jaime0815** [comment]
it is not a bug

**Comment by yanliang567** [comment]
@jaime0815 @SimFG was this fixed? what is the current behavior now?

**Comment by SimFG** [comment]
@yanliang567 Has fixed.
