### ISSUE TITLE
[Enhancement]: redesign the timeout logic for compaction

### ISSUE THREAD

**Issue by jiaoew1991** [milvus-io/milvus#18674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

The compaction timeout logic is controlled in `datacoord`, the `compactionTask` is generated by `datacoord` and executed by `dataanode`, the execution time of `compactiontask` starts from `datacoord` generation task, and may have been **queued** for 150s when dataanode was executed, resulting in a real execution time of only 30s, which is easy to timeout.

1. Whether the timeout mechanism is still necessary
2. If timeout is still needed, the start time needs to be corrected or the timeout check is left to `datanode`

**Comment by jiaoew1991** [comment]
The timeout mechanism is still necessary, in order to prevent the occurrence of `datanode` suspended animation and network instability caused by the problem of too long execution time

Now the core problem is the `datacoord` cannot confirm the exact state of the task, and how to recover if the `datanode` execution fails

A better approach is for `datacoord` to periodically access `datanode` through RPC to get the current state of the task, and if the RPC access fails, the task is considered to have failed.

**Comment by xiaofan-luan** [comment]
overall looks good to me, also we need to try cancel the task if compaction timeout to avoid execute  multiple times

**Comment by jiaoew1991** [comment]
add new rpc endpoint  GetCompactionState for `datanode`
remove CompleteCompaction for `datacoord`

add new config `dataCoord.compaction.check.interval` which default value is 10, the cycle of `datacoord` to checks the status of the compaction task
