### ISSUE TITLE
[Bug]: cannot parse expression: age_gte <= 90 <= age_lte, error: only comparison between two fields is supported

### ISSUE THREAD

**Issue by stringk245** [milvus-io/milvus#18684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.1
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.0.2
- OS(Ubuntu or CentOS): Ubuntu 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Milvus==2.0.2
.search({"expr":"uid==1 &&  age_gte <= 90 <= age_lte"})   is successfule

but  Milvus==2.1.1
.search({"expr":"uid==1 &&  age_gte <= 90 <= age_lte"})    raise  code=1, message=failed to create query plan: cannot parse expression: age_gte <= 90 <= age_lte, error: only comparison between two fields is supported

### Expected Behavior

when  Milvus==2.1.1
.search({"expr":"uid==1 &&  age_gte <= 90 <= age_lte"})   is ok,  not raise

### Steps To Reproduce

```markdown
collection.search({"expr":"uid==1 &&  age_gte <= 90 <= age_lte"})
```

### Milvus Log

BaseException: (code=1, message=failed to create query plan: cannot parse expression: age_gte <= 90 <= age_lte, error: only comparison between two fields is supported)>

**Comment by longjiquan** [comment]
Sorry, we changed our parser implementation in `2.1.1` and limited some range operations. In your case, we'd recommend you to use logical and to connect these two filter expressions: `age_gte <= 90 && age_lte >= 90`.
