### ISSUE TITLE
[Bug]: 2.1.1 has problems with loading/releasing a collection.

### ISSUE THREAD

**Issue by martinenkoEduard** [milvus-io/milvus#18728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.1
- Deployment mode(standalone or cluster):standalone, deb
- SDK version(e.g. pymilvus v2.0.0rc2):  2.1.1
- OS(Ubuntu or CentOS): ubuntu 18
- CPU/Memory: 8 vcpu/15gb RAM
- GPU: none
- Others:
```

### Current Behavior

I created a test collection 

fields = [
    FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, auto_id=False),
    FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=128)
]

with 1 million of entries.

But I tried to release/load a collection,  it just hangs.

### Milvus Log

can't find them on standalone, deb installation.

**Comment by yanliang567** [comment]
@martinenkoEduard Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?


/assign @martinenkoEduard 
/unassign

**Comment by martinenkoEduard** [comment]
I accidentally deleted the vm, so I lost all logs. The issue haven't showed again.

**Comment by yanliang567** [comment]
@martinenkoEduard we do not reproduce this issue locally. Do you mind closing this issue for now? You could reopen it if it reproduced to you.
