### ISSUE TITLE
[Bug]: Official website Chinese document

### ISSUE THREAD

**Issue by bestRiven** [milvus-io/milvus#18731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Please help me recover the Chinese documents on the official website. Thank you

**Comment by shanghaikid** [comment]
Thank you, we are not supporting Chinese doc, you can refer here for the chinese doc. Thanks. 
https://github.com/milvus-io/web-content/tree/master/v2.0.x/site/zh-CN
