### ISSUE TITLE
[Feature]:  Publish allowed characters 

### ISSUE THREAD

**Issue by yovelcohen** [milvus-io/milvus#18747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I tried to run a query against a list of strings:
```python
    def get_ids_from_external_ids(self, external_ids) -> Set[int]:
        expr = f'[{", ".join(external_ids)}]' if isinstance(external_ids[0], str) else external_ids
        try:
            return set([di['id'] for di in self.query(
                expr=f"external_id in {expr}",
                output_fields=["id"],
                consistency_level="Strong",
                timeout=30
            )])
```
and kept getting errors like:
```
error: line 1:12227 token recognition error at: '\u00f3')>, <Time:{'RPC start': '2022-08-21 05:04:30.470673', 'RPC error': '2022-08-21 05:04:30.507507'}>

error: line 1:8746 token recognition error at: '''

error: line 1:902 token recognition error at: '\u00c7'
```

### Describe the solution you'd like.

now that filtering by strings is possible, it'll be great if a list curating examples of valid/invalid queries and a list of those unallowed characters so we can serialize are requests properly.

**Comment by xige-16** [comment]
working on it

**Comment by yanliang567** [comment]
I believe this is avaliable in milvus 2.4
