### ISSUE TITLE
[Bug]: remove redundant slashes at config 

### ISSUE THREAD

**Issue by wg1026688210** [milvus-io/milvus#18761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Found an extra slash at [this](https://github.com/milvus-io/milvus/blob/9589bd38137a84e480ce0a26941c2c1220f264ad/internal/util/paramtable/base_table.go#L110)

**Comment by yanliang567** [comment]
great, i think you were working on this issue.
/assign @wg1026688210 
/unassign
