### ISSUE TITLE
[Enhancement]: request querynode directly on proxy for low lantency search request

### ISSUE THREAD

**Issue by wg1026688210** [milvus-io/milvus#18765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

For the collection of small data volume requests, we need to query low latency.

Now we think of a simplest solution: by some low-consumption load balancing strategies on the proxy node, request the querynode directly on the proxy, so that there is no need to forward the request again among querynodes , and there is no need to consider the memory-based load balancing on the querynode.

I left a draft  pr for the discussion

**Comment by xiaofan-luan** [comment]
Hi @wg1026688210 
@congqixia , @jiaoew1991 and I have a quick discussion on how we can handle small data.
We are thinking of having 2 collection mode
1) lightening mode -> each shard < 100m data, no extra request forward.   
2) heavy mode -> each shard can be scaled to 10B data, worked for big data scenario.

for lightening mode, all segments and shards will be deployed on single machine
for heavy mode, all segments will be balanced separately with shard leaders, heavy mode may need extra KV storage for PK ->Segment offset relationship maintenance


to change from lightening mode to heavy mode, collection need to be reloaed.

**Comment by wg1026688210** [comment]
> for lightening mode, all segments and shards will be deployed on single machine

Hi 
@xiaofan-luan @congqixia @jiaoew1991 
I  agree with the idea of lightening mode and heavy mode very much.

If all segments are deployed to the same machine, will the load balancing  and high availability capabilities be lost,For example, a very large number of requests will be sent to a lightening-mode collection whose segment is all allocated on one machine.

In addition, the service also needs to maintain a logic to allocate segments according to the memory size. Will this increase the maintenance cost on querynode and querycoodinator? I haven't had time to look at the code for this piece yet ,so I don't know if this solution is easy to maintain.

How about  we give users the choice of whether to use the light-heavy mode when querying through a new client parameters?

lightening-mode:   request  the querynode through a low-consumption load balancing strategy in the proxy like nginx.

heavy-mode: request as before logic.
