### ISSUE TITLE
[Bug]: Abnormal memory usage

### ISSUE THREAD

**Issue by Sivannnnnn** [milvus-io/milvus#18764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.1.0 
- Deployment mode(standalone or cluster): standalone 
- SDK version(e.g. pymilvus v2.0.0rc2): java
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 36 core 128G RAM
- GPU: 
- Others:
```

### Current Behavior

My table structure, primary key: INT64, vector: 128-dimensional float32 vector. Other service fields are int8, INT8, int16, and int32. There are six fields in total. When using IVF_SQ8 index and 150 million data, only the primary key and vector, the memory usage is 30 GB, but after adding the following four service fields, the memory usage is 45 GB. It is estimated that these four business fields occupy 15GB of memory space. Theoretically, these 150 million fields take up 1.5* 10^8*8*10^-9 gigabytes of space, which is about 1 gigabyte.
Are there any ways to reduce memory usage？

**Comment by yanliang567** [comment]
@Sivannnnnn thank you for the issue. Could you please share more info:
1. how did you delploy milvus, cluster or standalone, deployment cofnigurations?
2. how did you insert and build data, reproduce code snippet? did you have delete operations?
3. refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation

/assign @Sivannnnnn 
/unassign

**Comment by Sivannnnnn** [comment]
1. - Milvus version: v2.1.0 
- Deployment mode(standalone or cluster): standalone 
- SDK version(e.g. pymilvus v2.0.0rc2): java
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 36 core 128G RAM
- GPU: 
- Others:


2.I use batch insert, vector and scalar fields are inserted together, the vector field memory is normal, there is no other operation, just insert, then load

**Comment by xiaofan-luan** [comment]
ThreadSafeVector might be the main reason.
We use std::deque to store data, which may extra data explosion.
What do you think @xige-16 ?

**Comment by xiaofan-luan** [comment]
The way we stored data in Milvus:
SegmentSealedImpl -> InsertRecord -> ConcurrentVector
The concurrent Vector implementation is tricky:

We use deque to store vector data:
    std::atomic<int64_t> size_ = 0;
    std::deque<Type> vec_;

The deque overhead itself may takes much more memory than the int/float data itself.
We may need to change the deque to flat array

**Comment by Sivannnnnn** [comment]
@xiaofan-luan 
Hello, I came to report back on the issues that I currently encountered in the Milvus V2.1.0 standalone process

1. Frequent read and write operations cause the SST files in the Milvus data directory to become larger and larger, and the disk is full and cannot be cleared. Is there any solution at present?

2. Milvus's scalar fields take up a lot of memory

May I ask when these problems are expected to be solved, or do you have any short-term countermeasures

**Comment by xiaofan-luan** [comment]
Hi @Sivannnnnn,

For problem 1 , https://github.com/milvus-io/milvus/pull/18752, I tried to add compaction on rocksmq everyday to clean expired data. We've tested and so far it worked well, you can try to deploy daily build and see it your problem has been fixed.

For problem2, we are already working on a fix, and it should be in 2.1.3

**Comment by Sivannnnnn** [comment]
@xiaofan-luan 
hello，Problem 1 does not seem to have been solved

I use milvus-dev: 2.00-20220830-standlone. I have modified the rockSMQ configuration as shown below. I don't have a large amount of data, about 10 real-time data per second, but I have enabled MILvUS with 10 concurrent queries per second. The query log will also be appended to the SST file in the Milvus folder, but the SST file is not cleaned, and my disk will still be full after a long time.

![image](https://user-images.githubusercontent.com/46392469/187822184-6db3de8a-67cb-457a-b14a-07fc45673c2a.png)


![image](https://user-images.githubusercontent.com/46392469/187822263-45745c9d-d176-45c9-b1d8-812a07a6a8cc.png)

**Comment by LoveEachDay** [comment]
@Sivannnnnn How do you change the `milvus.yaml` in the docker container?  For now there is a issue when you restart the milvus container, which will makes rocksmq retention failed. 

So you can just run docker-compose without change the `milvus.yaml` in the container. And wait a day to check out the disk usages of rocksmq.

And for the `logs` directory in side `/var/lib/milvus` directory, do you set `log.file.rootPath` to `/var/lib/milvus/logs`?

**Comment by Sivannnnnn** [comment]
@LoveEachDay  Log-related configuration I use the default configuration
![image](https://user-images.githubusercontent.com/46392469/188367709-0cc12f00-5fee-4983-94bc-5ed27a47735e.png)

**Comment by Sivannnnnn** [comment]
@LoveEachDay  I modify the contents of the configuration file by file mapping
![image](https://user-images.githubusercontent.com/46392469/188367865-b87bf995-cd33-4e1c-afce-d8acbfbba1db.png)

**Comment by Sivannnnnn** [comment]
@LoveEachDay @xiaofan-luan @JackLCL 

Hello, after several days of testing, I write thousands of pieces of data every day, RockSMQ has filled up the disk again, and now it takes 10s for me to query each time, which only took 200ms before. Is the problem solved now

![image](https://user-images.githubusercontent.com/46392469/188772532-41851b50-7ac0-4046-bbe8-2b8935df20cc.png)

**Comment by Sivannnnnn** [comment]
![image](https://user-images.githubusercontent.com/46392469/188772693-5bd581ce-2e0e-4b1b-92d0-fd9ea3b20d8c.png)

**Comment by yanliang567** [comment]
keep it active

**Comment by Sivannnnnn** [comment]
@yanliang567 

> keep it active

The release log of Milvus V2.1.4 mentions a reduction in the amount of memory used for scalar data. I haven't had a chance to verify this yet. Why keep it active?

**Comment by yanliang567** [comment]
I'd like to keep it active until your verification, or it would be automatically stale and closed after 30 days

**Comment by Sivannnnnn** [comment]
All right, I'll check it out and make sure it's off

**Comment by Sivannnnnn** [comment]
@yanliang567 

![image](https://user-images.githubusercontent.com/46392469/194809862-f4de44e0-3b19-4186-84a5-564ffffdf3cd.png)


My field is shown in the figure. The memory usage is 58G when using version 2.1.1, and 48G when loading after release. It was verified using version 2.1.4, with an initial memory footprint of 50G and a post-release loading footprint of 40G. Overall, the memory is optimized by nearly 20%. Thank you to all the developers. By the way, how do we handle scalar fields now? Do we use arrays instead of the old two-way lists

**Comment by xiaofan-luan** [comment]
good job @aoiasd ~~

**Comment by xiaofan-luan** [comment]
> @yanliang567
> 
> ![image](https://user-images.githubusercontent.com/46392469/194809862-f4de44e0-3b19-4186-84a5-564ffffdf3cd.png)
> 
> My field is shown in the figure. The memory usage is 58G when using version 2.1.1, and 48G when loading after release. It was verified using version 2.1.4, with an initial memory footprint of 50G and a post-release loading footprint of 40G. Overall, the memory is optimized by nearly 20%. Thank you to all the developers. By the way, how do we handle scalar fields now? Do we use arrays instead of the old two-way lists

Hi @Sivannnnnn , thanks for the feedback. thought you are looking for this fix https://github.com/milvus-io/milvus/pull/19421

**Comment by xiaofan-luan** [comment]
Generally speaking, we found a few issues:
1)std::variant<std::monostate, int64_t, std::string> consumes memory of all types, but actually it should be only one of the int64 or string so we use template instead.
2) use binary search on pk rather than orderedmap, see OffsetOrderedArray as  implementation of OffsetMap.  In our scenario, binary search on a vector is not only memory efficient but also fast than unordered_map

**Comment by Sivannnnnn** [comment]
ok，Thank you for your answer
