### ISSUE TITLE
[Bug]: Milvus won't start.  Milvus Proxy is not ready yet. please wait

### ISSUE THREAD

**Issue by martinenkoEduard** [milvus-io/milvus#18763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.1.0-3-g1b33c7313
- Deployment mode(standalone or cluster): standalone, deb
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.1.0
- OS(Ubuntu or CentOS): ubuntu 18
- CPU/Memory: 8vcpu/ 30gb RAM
- GPU: 
- Others:
```

### Current Behavior

The whole weekends the server was loading vectors one by one. Each time recreating connection.
something like 200k-300k vectors
All seemingly went fine, without shutdowns and reboots. And then on the monday i get the following error:

When accessing milvus it shows the following error:

[has_collection] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>
[has_collection] retry:5, cost: 0.81s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>
[has_collection] retry:6, cost: 2.43s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>
[has_collection] retry:7, cost: 7.290000000000001s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, Socket closed>
[has_collection] retry:8, cost: 21.870000000000005s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>
[has_collection] retry:9, cost: 60s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>
pymilvus.exceptions.MilvusUnavaliableException: <MilvusUnavaliableException: (code=1, message=server unavaliable: Retry run out of 10 retry times)>

I found this very strange:
Aug 21 05:06:35 ubuntu18 milvus[4445]: panic: etcdserver: mvcc: database space exceeded

### Milvus Log

[milvus.zip](https://github.com/milvus-io/milvus/files/9391667/milvus.zip)
[milvus-etcd.zip](https://github.com/milvus-io/milvus/files/9391668/milvus-etcd.zip)
[milvus-minio.zip](https://github.com/milvus-io/milvus/files/9391669/milvus-minio.zip)

**Comment by martinenkoEduard** [comment]
Btw - how do I change ETCD config? It seems to use special version of ETCD - milvus-etcd.

**Comment by martinenkoEduard** [comment]
Could it be because I create a new connection on every request?

connections.connect("default", host=MILVUS_HOST, port=MILVUS_PORT)
collection = Collection("faces")
collection.load()
connections.disconnect("default")

**Comment by LoveEachDay** [comment]
@martinenkoEduard By default, etcd installed with milvus deb package doesn't enable compaction. You'd enable compaction for etcd by change the following configurations to `/usr/lib/systemd/system/milvus-etcd.service` file.
```
ExecStart=/usr/bin/milvus-etcd --data-dir /var/lib/milvus/etcd-data --auto-compaction-mode=revision --auto-compaction-retention='1000'
```

**Comment by martinenkoEduard** [comment]
> @martinenkoEduard By default, etcd installed with milvus deb package doesn't enable compaction. You'd enable compaction for etcd by change the following configurations to `/usr/lib/systemd/system/milvus-etcd.service` file.
> 
> ```
> ExecStart=/usr/bin/milvus-etcd --data-dir /var/lib/milvus/etcd-data --auto-compaction-mode=revision --auto-compaction-retention='1000'
> ```

Does it have any disadvantages? Why isn't it default?

What about docker compose and cluster version?

Maybe i need to tweek something else?

**Comment by martinenkoEduard** [comment]
--auto-compaction-retention='1000'

What value should i set?
1000 in hours?
Isn't a lot?

My system.worked for 78 hours tops, before encountering a bug.
Maybe even less

**Comment by martinenkoEduard** [comment]
Do I need to defrag?

**Comment by martinenkoEduard** [comment]
is it wise to set 
etcdctl compact
etcdctl defrag 

In a script (cron)?


defrag seems to free a lot of space..

**Comment by martinenkoEduard** [comment]
I tried to restore milvus:
It shows Error: context deadline exceeded.

**Comment by martinenkoEduard** [comment]
Btw - on this database ETCD db size shos 2.1 GB
After defrag it is 1.9.

Something isn't righ i suppose)

**Comment by LoveEachDay** [comment]
> Does it have any disadvantages? Why isn't it default?
Enable auto compaction will decrease the memory usage, but it add some cpu overhead. And you can inspect the overhead via the log like this:
```
{"level":"info","ts":"2022-08-23T03:14:19.684Z","caller":"mvcc/index.go:214","msg":"compact tree index","revision":81865}
{"level":"info","ts":"2022-08-23T03:14:19.697Z","caller":"mvcc/kvstore_compaction.go:57","msg":"finished scheduled compaction","compact-revision":81865,"took":"12.016841ms"}
```
> What about docker compose and cluster version?
We've enabled auto compaction for etcd in docker-compose, milvus helm chart, and milvus operator.  For deb and rpm package installment, we'll enable compaction in the next version.

> Maybe i need to tweak something else?
You may also need to change the db quota to 4G like this:
```
--quota-backend-bytes=4294967296
```

**Comment by LoveEachDay** [comment]
> --auto-compaction-retention='1000'
> 
> What value should i set? 1000 in hours? Isn't a lot?
> 
> My system.worked for 78 hours tops, before encountering a bug. Maybe even less

Etcd compaction has two mode: `periodic`, which means how often to trigger a compaction, `revision`, which means after how many writes to trigger a compaction.

We'll set the compaction mode to `revision`, and set `--auto-compaction-retention='1000'` means after 1000 writes, it will trigger a compaction.

**Comment by LoveEachDay** [comment]
> > --auto-compaction-retention='1000'
> > What value should i set? 1000 in hours? Isn't a lot?
> > My system.worked for 78 hours tops, before encountering a bug. Maybe even less
> 
> Etcd compaction has two mode: `periodic`, which means how often to trigger a compaction, `revision`, which means after how many writes to trigger a compaction.
> 
> We'll set the compaction mode to `revision`, and set `--auto-compaction-retention='1000'` means after 1000 writes, it will trigger a compaction.

**Comment by martinenkoEduard** [comment]
Is it ok?
sudo crontab -e
*/5 * * * * /home/administrator/etcd_clear.sh

etcd_clear.sh
export ETCDCTL_API=3
rev=$(ETCDCTL_API=3 etcdctl endpoint status --write-out="json" | egrep -o '"revision":[0-9]*' | egrep -o '[0-9]*')
ETCDCTL_API=3 etcdctl --endpoints=localhost:2380,localhost:2379 compact $rev
ETCDCTL_API=3 etcdctl --endpoints=localhost:2380,localhost:2379 defrag
echo "last revision $rev" > /home/administrator/rev.txt

**Comment by martinenkoEduard** [comment]
Should I set? --quota-backend-bytes='8589934592'

**Comment by LoveEachDay** [comment]
> 



> Is it ok? sudo crontab -e */5 * * * * /home/administrator/etcd_clear.sh
> 
> etcd_clear.sh export ETCDCTL_API=3 rev=$(ETCDCTL_API=3 etcdctl endpoint status --write-out="json" | egrep -o '"revision":[0-9]_' | egrep -o '[0-9]_') ETCDCTL_API=3 etcdctl --endpoints=localhost:2380,localhost:2379 compact $rev ETCDCTL_API=3 etcdctl --endpoints=localhost:2380,localhost:2379 defrag echo "last revision $rev" > /home/administrator/rev.txt

It's not recommended to write a cronjob to trigger a compaction. Just enable auto compaction for etcd config.
And defrag may be needed but not at every 5 minutes, maybe every 24 hours.

And for `quota-backend-bytes`, we've tested 1 billion collection, 4GB is enough.

**Comment by martinenkoEduard** [comment]
Does it have any disadvantages to set quota-backend-bytes to 8?

**Comment by LoveEachDay** [comment]
> Does it have any disadvantages to set quota-backend-bytes to 8?

No. You can take a reference from here for etcd maintenance: https://etcd.io/docs/v3.5/op-guide/maintenance/

**Comment by martinenkoEduard** [comment]
What about docker compose version of standalone milvus?
Do i need to change auto-compaction-retention= and set defrag?

What is the best way to do it? Without rebuilding the whole image

**Comment by myxzlpltk** [comment]
This is also happened to me. Yesterday, it was totally normal during and then I upgrade my docker desktop from `4.11.0` to `4.12.0` . And then bam, I can't run milvus/minio container. At first I thought this is might be glitch. So, I reinstall milvus based on [installation guide](https://milvus.io/docs/v2.1.x/install_standalone-docker.md). Even though all three containers run, but when I try connect using Attu I get this error

> Error: Error: 14 UNAVAILABLE: internal: Milvus Proxy is not ready yet. please wait

**Comment by yanliang567** [comment]
> This is also happened to me. Yesterday, it was totally normal during and then I upgrade my docker desktop from `4.11.0` to `4.12.0` . And then bam, I can't run milvus/minio container. At first I thought this is might be glitch. So, I reinstall milvus based on [installation guide](https://milvus.io/docs/v2.1.x/install_standalone-docker.md). Even though all three containers run, but when I try connect using Attu I get this error
> 
> > Error: Error: 14 UNAVAILABLE: internal: Milvus Proxy is not ready yet. please wait
> 
> **Update** I don't know why it solved.
> 
>     1. Reset firewall configuration
> 
>     2. Delete volume `rm -rf  volumes`
> 
>     3. Compose docker `docker-compose up -d`

Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

**Comment by pnthang01** [comment]
If you guys still facing this issue and your milvus is deployed via docker-compose. Possible that you need to create new network name.
My milvus db is fixed after tried this.

**Comment by martinenkoEduard** [comment]
> If you guys still facing this issue and your milvus is deployed via docker-compose. Possible that you need to create new network name. My milvus db is fixed after tried this.

Do you mean to create a new network and change name for every entry?

**Comment by pnthang01** [comment]
> > If you guys still facing this issue and your milvus is deployed via docker-compose. Possible that you need to create new network name. My milvus db is fixed after tried this.
> 
> Do you mean to create a new network and change name for every entry?

Sorry, I wasn't clear. I used docker swarm to deploy the stack but network was created separate on attachable mode. When I restarted the services, this issue happened. 
Although I tried to clear the volumes for all services, the issue still occurred. 
But after I created new network name (yeah completely new name), it works normal.

Perhaps, the dev team may need to look to network part to reproduce the issue then.

**Comment by mouhandalkadri** [comment]
I am facing the same issue, I deployed Milvus by the docker-compose file provided in the docs, but after a while Milvus NodeJS client raises DEADLINE_EXCEEDED exception. After some investigation I found that the client is logging `milvus proxy is not ready yet. please wait`

Any thoughts?

**Comment by Luke5hao** [comment]
> I am facing the same issue, I deployed Milvus by the docker-compose file provided in the docs, but after a while Milvus NodeJS client raises DEADLINE_EXCEEDED exception. After some investigation I found that the client is logging `milvus proxy is not ready yet. please wait`
> 
> Any thoughts?

Were you able to resolve this?
