### ISSUE TITLE
[Bug]: failed to search on all shard leaders, err=fail to Search, QueryNode ID=89

### ISSUE THREAD

**Issue by matt1209** [milvus-io/milvus#18776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.1
- Deployment mode(standalone or cluster):standalone 
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus2.1.1
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I run `collection.search` , the error raised: `fail to search on all shard leaders, fail to Search, QueryNode ID=89`.

### Steps To Reproduce

```markdown
1. run 5 times `collection_prepare.py` in benchmark blog on milvus.io, I changed the `nb=50000, insert_times=200`
2. run script on <https://milvus.io/docs/v2.1.x/search.md> 
`search_params = {"metric_type": "L2", "params": {"nprobe": 10}}`
`results = collection.search(
	data=[[random.random() for _ in range(dim)]], 
	anns_field="embedding", 
	param=search_params, 
	limit=10, 
	expr=None,
	consistency_level="Strong"
)`
```

### Milvus Log

![ed020480-7e99-48e1-a568-1a16d1a4f361](https://user-images.githubusercontent.com/10979776/186050188-ca4b0722-59de-4af7-8c86-0e648fc65313.jpg)

**Comment by yanliang567** [comment]
@matt1209 thank you for the issue. Did you also change the index type in collection_prepare.py? It seems that you are using ivf_ index in search params, while it build hnsw index in collection_prepare.py?
Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @matt1209 
/unassign

**Comment by JackLCL** [comment]
![image](https://user-images.githubusercontent.com/53512883/186097366-d2935102-b052-43b5-985b-a2041906218d.png)

What's your topk?  The ef parameter must in [top_k, 32768].

**Comment by yanliang567** [comment]
I see, topk does not matter here. Milvus will use topk as ef if ef<topk. 
please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation. we shall have all completed logs to analzye the issue.

**Comment by matt1209** [comment]
I'm sorry I can't provide here because we don't have internet for all computers.

**Comment by matt1209** [comment]
Is this caused by I run the benchmark script 5 times?

**Comment by yanliang567** [comment]
it's hard to tell if no completed logs.  does it only reproduce when you run the scripts for 5 times? what about for 1 time?
 How did you deploy milvus,with helm, operator or docker compose? did you limit the cpu or memory for milvus?

**Comment by matt1209** [comment]
Hi, I just tried for run 1 time but when I did search, there was an error msg : `check if Loaded failded when search, partitions:[], err=showPartitions failed, reason=collection xxxx has not been loaded into QueryNode`. Do it must be loaded before search? I tried to run load() but it takes long time and large memery to load.

**Comment by yanliang567** [comment]
> Hi, I just tried for run 1 time but when I did search, there was an error msg : `check if Loaded failded when search, partitions:[], err=showPartitions failed, reason=collection xxxx has not been loaded into QueryNode`. Does it must be loaded before search? I tried to run load() but it takes long time and large memery to load.

this error indicates that collection load failed. I guess you don't have enough free memory for load the collection.

**Comment by matt1209** [comment]
> > Hi, I just tried for run 1 time but when I did search, there was an error msg : `check if Loaded failded when search, partitions:[], err=showPartitions failed, reason=collection xxxx has not been loaded into QueryNode`. Does it must be loaded before search? I tried to run load() but it takes long time and large memery to load.
> 
> this error indicates that collection load failed. I guess you don't have enough free memory for load the collection.

Is there anyway that I can do search on hard disk instead loading to memory? I deploy milvus with docker compose but cpu mem is not enough.

**Comment by yanliang567** [comment]
i am afraid not. But a good news is that the community is going to offer a new disk-based index type, which would save about 5-6 times of memory. If everything goes well, it will be available soon this year.
