### ISSUE TITLE
[Bug]: Search failed with error  fail to search on all shard leaders, err=fail to Search, QueryNode ID=17, reason=ShardCluster for by-dev-rootcoord-dml_9_xxxv1 replicaID xxx is no available after etcd pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#18799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.0-20220822-ab30ebb1
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.2.0.dev19
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The search failed when running `verify_all_collections.py` after etcd pod kill chaos test
![image](https://user-images.githubusercontent.com/12268675/186128001-158078a2-f662-4803-8f37-e36312ae8e1c.png)

```
14:18:47  check collection Checker__84jtsD6A
14:18:47  collection is exist
14:18:47  
14:18:47  Create collection...
14:18:47  
14:18:47  Insert 3000 vectors cost 0.1239 seconds
14:18:47  
14:18:47  Get collection entities...
14:18:47  36370
14:18:47  
14:18:47  Get collection entities cost 3.0188 seconds
14:18:47  
14:18:47  Create index...
14:18:47  
14:18:47  Create index cost 0.5102 seconds
14:18:47  
14:18:47  Get replicas number
14:18:47  
14:18:47  Replicas number is 1
14:18:47  
14:18:47  load collection...
14:18:47  
14:18:47  load collection cost 0.0042 seconds
14:18:47  
14:18:47  Search...
14:18:47  Traceback (most recent call last):
14:18:47    File "scripts/verify_all_collections.py", line 138, in <module>
14:18:47      hello_milvus(collection_name)
14:18:47    File "scripts/verify_all_collections.py", line 95, in hello_milvus
14:18:47      "int64 > 100", output_fields=["int64", "float"], timeout=TIMEOUT
14:18:47    File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 718, in search
14:18:47      partition_names, output_fields, round_decimal, timeout=timeout, schema=schema_dict, **kwargs)
14:18:47    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 96, in handler
14:18:47      raise e
14:18:47    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 92, in handler
14:18:47      return func(*args, **kwargs)
14:18:47    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 74, in handler
14:18:47      raise e
14:18:47    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 48, in handler
14:18:47      return func(self, *args, **kwargs)
14:18:47    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 452, in search
14:18:47      return self._execute_search_requests(requests, timeout, **_kwargs)
14:18:47    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 416, in _execute_search_requests
14:18:47      raise pre_err
14:18:47    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 407, in _execute_search_requests
14:18:47      raise MilvusException(response.status.error_code, response.status.reason)
14:18:47  pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=17, reason=ShardCluster for by-dev-rootcoord-dml_9_435482766336851969v1 replicaID 435482756135518244 is no available)>
```

### Expected Behavior

all test cases passed

### Milvus Log

failed job：https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/675/pipeline
log: 
[artifacts-etcd-pod-kill-675-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9401455/artifacts-etcd-pod-kill-675-server-logs.tar.gz)
[artifacts-etcd-pod-kill-675-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9401458/artifacts-etcd-pod-kill-675-pytest-logs.tar.gz)
 

### Anything else?

This issue happened stably

**Comment by jiaoew1991** [comment]
maybe we should waiting for QueryCoordV2's code checkin. the behavior of Chaos Test will be better

**Comment by zhuwenxing** [comment]
> maybe we should waiting for QueryCoordV2's code checkin. the behavior of Chaos Test will be better

But this happened in 2.1 branch, so it should be fixed before next release

**Comment by aoiasd** [comment]
https://zilliverse.feishu.cn/docx/doxcn4n7HiEZlTFstTQT5Dem28e
The main reason is that before restart the queryNode, some segment dropped because of compaction, but when we restart node, we will just reload the segments in bin logs(no dropped segment) and the segment info in etcd will still be the old node, so when querycoord get query task, it will find some segment in dropped node and get failed.

**Comment by zhuwenxing** [comment]
chaos type: pod-kill image tag: 2.1.0-20220913-3c3ba55 target pod: etcd

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release/detail/chaos-test-for-release/549/pipeline

log:
[artifacts-etcd-pod-kill-549-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9572818/artifacts-etcd-pod-kill-549-server-logs.tar.gz)
[artifacts-etcd-pod-kill-549-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9572823/artifacts-etcd-pod-kill-549-pytest-logs.tar.gz)

**Comment by jiaoew1991** [comment]
we can retry it with querycoordV2

/assign @zhuwenxing
/unassign

**Comment by zhuwenxing** [comment]
Bad news, after querycoordV2 merged in master, the pod kill chaos test almost failed due to load collection timeout. but etcd is OK.

I would open a new issue to trace the load timeout problem.

**Comment by zhuwenxing** [comment]
chaos type: pod-kill image tag: 2.1.0-20220916-3c3ba55c target pod: etcd
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release/detail/chaos-test-for-release/714/pipeline/

log:
[artifacts-etcd-pod-kill-714-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9613758/artifacts-etcd-pod-kill-714-pytest-logs.tar.gz)
[artifacts-etcd-pod-kill-714-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9613759/artifacts-etcd-pod-kill-714-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
for 2.1 branch, this issue is reproduced stable.

/assign @jiaoew1991 

please help to take a look!

**Comment by zhuwenxing** [comment]
It was not reproduced in the master branch, but it still happened in 2.1 branch (2.1.0-20220930-706b8e98). 

Any fix plan or just recommend users use the later release v2.2?
