### ISSUE TITLE
[Bug]: Milvus docker hangs up

### ISSUE THREAD

**Issue by zxcvjl** [milvus-io/milvus#18798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.0
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.0
- OS(Ubuntu or CentOS): 
- CPU/Memory: 48C/194G
- GPU: 15109MiB *2
- Others:
```

### Current Behavior

After the query is started, the docker of Milvus is directly hung up within 10 minutes

### Milvus Log

[Uploading milvus2022-08-23.log…]()

**Comment by zxcvjl** [comment]
[milvus.log](https://github.com/milvus-io/milvus/files/9401466/milvus.log)

**Comment by zxcvjl** [comment]
![image](https://user-images.githubusercontent.com/10806552/186130222-09aee740-36c5-46b2-a16b-2955b677543d.png)

**Comment by yanliang567** [comment]
@zxcvjl could you please share the timestamp of search and hand, as according to the log i can see the last search completed successfully at 2022/08/23 09:51:11.280
`[2022/08/23 09:51:11.280 +00:00] [DEBUG] [timerecord/time_recorder.go:78] ["proxy execute search 435486251862458611: done (95ms)"]`
and then the collection was released immediately:
`[2022/08/23 09:51:11.318 +00:00] [DEBUG] [proxy/impl.go:601] ["ReleaseCollection done"] [traceID=2916f02338960319] [role=proxy] [MsgID=435486251862458612] [BeginTS=435486266817511425] [EndTS=435486266817511425] [db=] [collection=AP_Duplicate_Payment]`
