### ISSUE TITLE
Four documentation issues

### ISSUE THREAD

**Issue by shiyu22** [milvus-io/milvus#1880]
## Report incorrect documentation

**Location of incorrect documentation**
1. https://milvus.io/docs/v0.7.1/guides/metric.md
2. https://milvus.io/docs/v0.7.1/guides/metric.md#Jaccard-distance
3. https://milvus.io/docs/v0.7.1/guides/metric.md#Superstructure
4. https://milvus.io/docs/v0.7.1/guides/milvus_operation.md#Create-an-index

**Describe the problems or issues found in the documentation**
1. The table shows Distance Metrics & Index Types, but is the metric of SUBSTRUCTURE and SUPERSTRUCTURE support ivflat index?
2. The formula of Jaccard similarity coefficient and the formula of Jaccard similarity distance are reversed, but the Chinese version is correct.
3. The SUPERSTRUCTURE is not means the less the value, the more similar the structure is to its superstructure. Milvus will only return the result with the distance of 0, that is, SUPERSTRUCTURE only return the result of his superstructure. SUBSTRUCTURE result is the same.
4. Is that need to create index on FLAT?

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.
1. List SUBSTRUCTURE and SUPERSTRUCTURE only support FLAT index in the table.
2. Do same as Chinese version.
3. Modify the SUPERSTRUCTURE and SUBSTRUCTURE's description.
4. Note that FLAT is the default index, no need to create index.

**Comment by shengjun1985** [comment]
Thank you for your suggestion.
It is fixed.
