### ISSUE TITLE
Some inserted vector becomes all zeros when index_file_size >= 2GB

### ISSUE THREAD

**Issue by shiyu22** [milvus-io/milvus#1883]
**Describe the bug**
Some inserted binary-vector becomes all zeros

**Steps/Code to reproduce behavior**
Data scale: 820 million 2048 dimensions binary vectors

According to the specified id, insert the data into two tables(named superstructure_table_2048 with metric.SUPERSTRUCTURE and substructure_table_2048 with metric.SUBSTRUCTURE) with milvus, but  
 the table data named superstructure_table_2048 has becomes all zeros.
![image](https://user-images.githubusercontent.com/53459423/78755558-f2e9d280-79ab-11ea-823f-ebadeb01a268.png)
but some vectors is correct.
![image](https://user-images.githubusercontent.com/53459423/78756014-aa7ee480-79ac-11ea-94ef-6b319a691f8d.png)

**Comment by yhmo** [comment]
1. create a collection, dimension=2048
2. insert 10 binary vectors into the collection, id from 0 to 9
3. flush
4. insert 10 binary vectors into the collection, id from 10 to 19
5. flush
6. get_vector_by_id(id=9), return vector data is correct
7. get_vector_by_id(id=10), return vector data all is zero

**Comment by shengjun1985** [comment]
binary flat, dim = 2048, index_file_size = 2048
The vectors whose offset larger than 8388592 is all zero.
I guess that the index file whose size larger than 2G may cause the bug.

**Comment by yhmo** [comment]
For float vector, reproduce steps:
1. create a collection, dimension=512, index_file_size=2048
2. insert 5,000,000 float vectors into the collection
3. flush
4. search, check all vector data in source code, some files contains all-zero vector

**Comment by del-zhenwu** [comment]
regression simple test script:
```
nb = 1000
m.create_collection({
    'collection_name': collection_name,
    'dimension': dim,
    'index_file_size': index_file_size,
    'metric_type': MetricType.L2})
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
for i in range(18):
    print(i)
    status, ids = m.add_vectors(collection_name, vectors, ids=[i for i in range(i*nb, (i+1)*nb)])
    m.flush([collection_name])
print("start get")
for i in range(18 * nb):
    print(i)
    status, result = m.get_vector_by_id(collection_name, i)
    if result[0] == 0.0:
        print(result)
        break
```
