### ISSUE TITLE
Can't set "eventual" consistency level.

### ISSUE THREAD

**Issue by martinenkoEduard** [milvus-io/milvus#18842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.1
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.1
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Can't set "eventual" 

hello_milvus = Collection("faces", schema,  consistency_level="eventual")

Traceback (most recent call last):
  File "/app/milvusScriptsReady/milvus_create_512_dim_low_consistency.py", line 30, in <module>
    hello_milvus = Collection("faces", schema,  consistency_level="eventual")
  File "/home/administrator/anaconda3/lib/python3.9/site-packages/pymilvus/orm/collection.py", line 137, in __init__
    consistency_level = get_consistency_level(kwargs.get("consistency_level", DEFAULT_CONSISTENCY_LEVEL))
  File "/home/administrator/anaconda3/lib/python3.9/site-packages/pymilvus/client/types.py", line 295, in get_consistency_level
    raise InvalidConsistencyLevel(0, f"invalid consistency level: {consistency_level}") from e
pymilvus.exceptions.InvalidConsistencyLevel: <InvalidConsistencyLevel: (code=0, message=invalid consistency level: eventual)>
(base) administrator@administrator-VirtualBox:/app/milvusScriptsReady$ pymilvus.exceptions.InvalidConsistencyLevel: <InvalidConsistencyLevel: (code=0, message=invalid consistency level: eventual)>

**Comment by soothing-rain** [comment]
The word is `Eventually` :)

**Comment by yanliang567** [comment]
@martinenkoEduard thank you for the issue. BTW, where did you get the word "eventual", I think we need to update the doc if there were a typo there.

/assign @martinenkoEduard 
/unassign

**Comment by martinenkoEduard** [comment]
In the guide page.
https://milvus.io/docs/consistency.md

**Comment by yanliang567** [comment]
@YiyunNi could you please help to update the doc accordingly

**Comment by YiyunNi** [comment]
Fixed docs with PR: https://github.com/milvus-io/milvus-docs/pull/1773

**Comment by martinenkoEduard** [comment]
> @YiyunNi could you please help to update the doc accordingly

How do I do it? I will gladly help)

**Comment by YiyunNi** [comment]
> > @YiyunNi could you please help to update the doc accordingly
> 
> How do I do it? I will gladly help)

That'll be great! Please refer to our doc contributing guide [here](https://github.com/milvus-io/milvus-docs/blob/v2.1.x/CONTRIBUTING.md). Thanks! @martinenkoEduard
