### ISSUE TITLE
[Bug]: java.lang.RuntimeException: All attempts results

### ISSUE THREAD

**Issue by Mask-Z** [milvus-io/milvus#18890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.1.0
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): milvus-sdk-java  2.1.0-beta4
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 40/252G
- GPU: 
- Others:
```

### Current Behavior

When i use  `milvusClient ` do search, response return the message:

`2022-08-29 18:23:08 io.milvus.client.AbstractMilvusGrpcClient logError 
ERROR: SearchRequest failed:
All attempts results:
attempt #1:fail to get shard leaders from QueryCoord: no replica available
attempt #2:fail to get shard leaders from QueryCoord: no replica available
attempt #3:fail to get shard leaders from QueryCoord: no replica available
attempt #4:fail to get shard leaders from QueryCoord: no replica available
attempt #5:fail to get shard leaders from QueryCoord: no replica available
attempt #6:fail to get shard leaders from QueryCoord: no replica available
attempt #7:fail to get shard leaders from QueryCoord: no replica available
attempt #8:context deadline exceeded`

### Steps To Reproduce

```markdown
1. Execute the code: 
SearchParam searchParam = SearchParam.newBuilder()
                    .withCollectionName("image")
                    .withMetricType(MetricType.L2)
                    .withOutFields(Arrays.asList("rowKey","type","published"))
                    .withTopK(SEARCH_K)
                    .withVectors(search_vectors)
                    .withVectorFieldName("multiple")
                    .withExpr("type == 11")
                    .withParams(SEARCH_PARAM)
                    .build();
            R<SearchResults> response = milvusClient.search(searchParam);
            System.out.println(response.getMessage());
```

### Anything else?

`It looks like it has something to do with milvus clusters`

**Comment by yanliang567** [comment]
@Mask-Z thank you for the issue. Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @Mask-Z 
/unassign

**Comment by Mask-Z** [comment]
log file too big, please get it by the url

url: https://pan.baidu.com/s/1ICxEkSrvgcgPzhrverYgHw  
password: 31nv

**Comment by jiaoew1991** [comment]
It can be found from the log that the number of shard leaders is less than the number of shard numbers, so the Querycoord return error when proxy try to list shard leaders. 

how many alive Querynode do you have, and how many shards does the collection have ?
