### ISSUE TITLE
[Bug]: The label of cases that have been solved were not removed

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#18908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Remove label of cases that have been solved.

**Comment by zhuwenxing** [comment]
The title is more like an action, not a description. I think it would be better when it is `The label of cases that have been solved were not removed`
/cc @binbinlv 
What do you think about it?

**Comment by binbinlv** [comment]
> The title is more like an action, not a description. I think it would be better when it is `The label of cases that have been solved were not removed` /cc @binbinlv What do you think about it?

Yes, the title of an issue should describe what the problem is.

@NicoYuan1986  Could modify it, thanks.

**Comment by NicoYuan1986** [comment]
> > The title is more like an action, not a description. I think it would be better when it is `The label of cases that have been solved were not removed` /cc @binbinlv What do you think about it?
> 
> Yes, the title of an issue should describe what the problem is.
> 
> @NicoYuan1986 Could modify it, thanks.

OK！Thank you both.
