### ISSUE TITLE
[Bug]: datacoord data race 

### ISSUE THREAD

**Issue by sunby** [milvus-io/milvus#18916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://github.com/milvus-io/milvus/runs/8090622376?check_suite_focus=true

**Comment by jiaoew1991** [comment]
dup with https://github.com/milvus-io/milvus/issues/18931
