### ISSUE TITLE
[Bug]: "describe collection -c" command in milvus-cli cann't display properly when there is "varchar" field in scheme.

### ISSUE THREAD

**Issue by skybluezx** [milvus-io/milvus#18922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.1.1
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): Not applicable
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 32G
- GPU: 24G
- Others: Milvus-Cli version: 0.3.0
```

### Current Behavior

When I input "describe collection -f [collection_name]", it only returns "21". I found that this situation only occurs when there is a "varchar" field in the table.  And I found the id number of varchar is exactly "21". So I don't know whether this is a bug or my improper operation.

**Comment by yanliang567** [comment]
@shanghaikid is it a cli issue?
/assign @shanghaikid 
/unassign

**Comment by nameczz** [comment]
It's cli bug, will fix it in next release
