### ISSUE TITLE
[Enhancement]: Need to add more cases to test shard_num valid range

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#18944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

```
shards_num (optional) | Number of the shards for the collection to create. | [1,256]
```

**Comment by binbinlv** [comment]
@NicoYuan1986 
Could you help to add some test cases to cover more shard number values. (for example, min, maximum)

**Comment by NicoYuan1986** [comment]
> @NicoYuan1986 Could you help to add some test cases to cover more shard number values? (for example, min, maximum)
> 
> Thanks.

OK!👌

**Comment by binbinlv** [comment]
Close this issue for fixed.
