### ISSUE TITLE
memory leak causes the milvus service to crash

### ISSUE THREAD

**Issue by gumy917** [milvus-io/milvus#1895]
**Describe the bug**
At milvus server run time,  the memory usage exceed the sum of cpu_cache_capacity(16G) and insert_buffer_size(10G), reach to 40G, eventually, the milvus server crashes(machine memory: 64G). 
1.The data is growing dynamically
2.It looks like the file index is created or the file is merged, memory not freed

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
- Method of installation 
source install

- Milvus version 
milvus-0.6.0 cpu release

- Milvus configuration 

primary_path:  /storage_master/milvus
secondary_path: /storage_backup/milvus

cpu_cache_capacity: 16
insert_buffer_size: 10
cache_insert_data: true

**Screenshots**

Additional context
Index: ivfflat
index_file_size: 1024

 machine memory: 64G

**Comment by JinHai-CN** [comment]
We already know cache_insert_data = true may cause memory leak. It will be fixed in future release, please switch it to false in configure file.

**Comment by gumy917** [comment]
ok, thanks for your response.
