### ISSUE TITLE
[Bug]: Cannot search partition whose name contains character "$"

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#18951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.1
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.1.0
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Create a partition name contains the character "$", then search the partition, the search return error.

Use this script to reproduce:

```
def main():
    connections.connect(host=_HOST, port=_PORT)

    dim = 128
    field1 = FieldSchema(name="ID", dtype=DataType.INT64, is_primary=True)
    field2 = FieldSchema(name="VEC", dtype=DataType.FLOAT_VECTOR, dim=dim)
    schema = CollectionSchema(fields=[field1, field2])
    collection = Collection(name="TEST", schema=schema)

    print(utility.list_collections())

    p1 = collection.create_partition("111")
    p2 = collection.create_partition("a$b")

    count = 1000
    data = [
        [i for i in range(count)],
        [[random.random() for _ in range(dim)] for _ in range(count)],
    ]
    p1.insert(data)
    p2.insert(data)

    print("Row count:", collection.num_entities)

    collection.load()

    search_vectors = [[random.random() for _ in range(dim)] for _ in range(1)]
    search_param = {
        "data": search_vectors,
        "partition_names": [p1.name],
        "anns_field": "VEC",
        "param": {"metric_type": "L2", "params": {}},
        "limit": 3}
    results = collection.search(**search_param)
    print("seach partition 1 successfully")

    search_param = {
        "data": search_vectors,
        "partition_names": [p2.name],
        "anns_field": "VEC",
        "param": {"metric_type": "L2", "params": {}},
        "limit": 3}
    results = collection.search(**search_param)
    print("seach partition 2 successfully")
```

When searching the partition "a$b", the search API throws an exception:
`pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=partition name a$b not found)>`containing

### Expected Behavior

Search can succeed on partition name which contains special characters.

**Comment by yhmo** [comment]
Current name rule:
The name of a resource can contain numbers, letters, dollar signs ($), and underscores (_). A resource name must start with a letter or an underscore (_).

**Comment by yanliang567** [comment]
@binbinlv please double check whether there are cases cover the name rule above?
/assign @binbinlv 
/assign @czs007 
/unassign

**Comment by binbinlv** [comment]
> @binbinlv please double check whether there are cases cover the name rule above? /assign @binbinlv /assign @czs007 /unassign

OK, checking.

**Comment by yhmo** [comment]
We discuss this issue in a meeting, put the conclusion here:
Milvus uses a regular pattern to match the partition name. As we know, "^" and "$" is the special character of regular pattern. So, we shouldn't allow "$" in partition name.

**Comment by inkinworld** [comment]
> We discuss this issue in a meeting, put the conclusion here: Milvus uses a regular pattern to match the partition name. As we know, "^" and "$" is the special character of regular pattern. So, we shouldn't allow "$" in partition name. A partition name should only contain numbers, letters, and underscores.

hi ~ why  "^" and "$" is the special character of regular pattern so we shouldn't allow "$" in partition name ?
when user users a regular pattern to match the partition name, just use escape character .i.e:` \$` is fine.
