### ISSUE TITLE
there is no way to specify the name of the database in the admin panel

### ISSUE THREAD

**Issue by alexvaa** [milvus-io/milvus#1896]
**Describe the bug**
there is no way to specify the name of the database in the admin panel

**Steps/Code to reproduce behavior**
change meta data base in admin panel and restart milvus 

**Expected behavior**
i can set data base name in admin panel

**Environment details**
- Hardware/Softward conditions (OS - centos, CPU-4, Memory-8)
- Method of installation Docker
- Milvus version v0.7.1

**Comment by shanghaikid** [comment]
@alexvaa hi, what do you mean about  the name of the database, you can set the name on collection/partition creation, but you can not rename it.

**Comment by yhmo** [comment]
Hi @alexvaa 
  Currently milvus has no 'database' concept, the top level concept is 'collection'. To create a 'database' concept, more concept may be involved such as 'user', 'privilege'. We may consider to plan these in future.
