### ISSUE TITLE
[Bug]: fail to install milvus with kubesphere 

### ISSUE THREAD

**Issue by 2mickey** [milvus-io/milvus#18976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

按照b站教程安装最新milvus提示失败

**Comment by yanliang567** [comment]
could you please refer to milvus.io and try again? https://milvus.io/docs/v2.1.x/install_standalone-helm.md
If it failed again, please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation

/assign @2mickey 
/unassign

**Comment by 2mickey** [comment]
Error: error while running post render on files: error while running command /tmp/helm-operator/milvus_milvus-91cslp_728p137yzzlml4/helm-post-render.sh. error output: Error: map[string]interface {}(nil): yaml: unmarshal errors: line 49: mapping key "httpNumThreads" already defined at line 37 : exit status 1

**Comment by yanliang567** [comment]
@LoveEachDay could u please help on this?

/assign @LoveEachDay 
/unassign @2mickey

**Comment by LoveEachDay** [comment]
`httpNumThreads` is a config for pulsar proxy. Seems this key was duplicated in the config.
@2mickey Could you provide the detailed procedures for installing milvus with kubersphere?

**Comment by 2mickey** [comment]
直接按照b站教程做的，你们可以试试看？或者可以远程帮看看吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "milvus-io/milvus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月2日(星期五) 晚上6:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [milvus-io/milvus] [Bug]: fail to install milvus with kubesphere  (Issue #18976)





 
httpNumThreads is a config for pulsar proxy. Seems this key was duplicated in the config.
 @2mickey Could you provide the detailed procedures for installing milvus with kubersphere?

**Comment by ruixiu** [comment]
有搞定吗？我也遇到这个问题了，一直都不行

**Comment by ruixiu** [comment]
刚刚搞定了：开启cluster模式，竟然需要把standalone.messageQueue设置为pulsar

**Comment by oahCW** [comment]
我也碰到了这个问题，把standalone.messageQueue设置为pulsar后依然还是报错呀：
Error: error while running post render on files: error while running command /tmp/helm-operator/milvus-pro_milvus-3acredit_lqy3workkn7250/helm-post-render.sh. error output: Error: map[string]interface {}(nil): yaml: unmarshal errors: line 49: mapping key "httpNumThreads" already defined at line 37 : exit status 1

**Comment by dgoldenberg-ias** [comment]
We're seeing a similar issue at clustered/k8s deployment. Any ideas on a fix or a workaround?

**Comment by xiaofan-luan** [comment]
> standalone.messageQueue

I'm not an expert on the deployment.
But seems that you will need to change standalone.messageQueue to kafka or pulsar from the previous discussion.
Are you aware of that?

**Comment by dgoldenberg-ias** [comment]
I would say that this needs to be reconciled still, since the switch over to using Kafka is a workaround rather than the solution.

**Comment by hyf3513OneGO** [comment]
> I would say that this needs to be reconciled still, since the switch over to using Kafka is a workaround rather than the solution.

Only one line mistake leads to quite a lot confusing
