### ISSUE TITLE
[Bug]: log.level seems to do nothing

### ISSUE THREAD

**Issue by erezweissgloat** [milvus-io/milvus#18972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.1
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):--
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Deployed with Helm 3.1.5, appVersion: "2.1.1".
When I change log.level to "info", the pods still print all the debug logs.
I've verified that the configmap was updated and that the pods contains this configmap.

### Expected Behavior

When I change log.level to "info" I expect debug logs to disappear.

**Comment by LoveEachDay** [comment]
@erezweissgloat There are some history that the config of `log.level` doesn't take effect at the milvus component initialization.  So even if you change the `log.level` to `info`, there will still part of `debug` log in the beginning. But after the initialization, it will only output `info` log and above.

**Comment by xiaofan-luan** [comment]
Yep, before log module is init, there will be some output but it should be soon be removed

**Comment by erezweissgloat** [comment]
Thank you guys
