### ISSUE TITLE
[Bug]: milvus集群异常fail to search on all shard leaders

### ISSUE THREAD

**Issue by hukang6677** [milvus-io/milvus#18988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.0
- Deployment mode(standalone or cluster):k8s cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 128G
- GPU: 
- Others:
```

### Current Behavior

![fc9b4b324ee2855c733c98af2031d30](https://user-images.githubusercontent.com/102129512/188071057-953ba587-baab-43fa-8c9e-d07fb8f85d7e.png)
![667abbca69634991885f79408bf0752](https://user-images.githubusercontent.com/102129512/188071082-94f272bd-a10c-4252-a61c-29f69e0a488b.png)
![5e181ab1533998e5a90564f450e611a](https://user-images.githubusercontent.com/102129512/188071102-ee46a585-629d-4b68-84a7-2982a4c4d575.png)
请问下 k8s搭建的milvus集群有两个工作节点node1 ，node2
昨天晚上node1上的pod被驱逐了，在node2上重新运行了相应的pod，可能是由于node1上内存不足了才发生驱逐。但我的Attu里面queryNode为什么会这样？ 并且我用JavaSDK查询会报错如下，请问下这个怎么处理？

### Expected Behavior

请问下 k8s搭建的milvus集群有两个工作节点node1 ，node2
昨天晚上node1上的pod被驱逐了，在node2上重新运行了相应的pod，可能是由于node1上内存不足了才发生驱逐。但我的Attu里面queryNode为什么会这样？ 并且我用JavaSDK查询会报错如下，请问下这个怎么处理？

### Milvus Log

[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/9475334/milvus-log.tar.gz)

**Comment by weiliu1031** [comment]
about the `NPE` in your code, you can debug your 'MilvusTest2' code. you can also show your code here

**Comment by weiliu1031** [comment]
about why your Attu show two empty query node info:
1. from the log,  the query node has restarted twice with `ServerId=1` and `ServerId=11`, and the latest is `ServerId=19`
2. maybe query node crush suddenly, and some session info hasn't been cleared. and Attu is affected,  i will check this with Attu's engineer.

**Comment by yanliang567** [comment]
@hukang6677 about the attu display issue, I believe it was fixed in Attu. please retry with latest build.
