### ISSUE TITLE
[Bug]: DescribeCollection cache was never hit in Proxy

### ISSUE THREAD

**Issue by bigsheeper** [milvus-io/milvus#18999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

DescribeCollection cache was never hit in Proxy due to describeCollection didn't return collectionName, and Proxy use collectionName to check if cache is hit.

**Comment by xiaofan-luan** [comment]
pls check DescribeCollection usage in proxy and other component, we want to make sure every call in proxy has to go to meta cache but not directly call "DescribeCollection"

**Comment by xiaofan-luan** [comment]
see also #19006

**Comment by bigsheeper** [comment]
> pls check DescribeCollection usage in proxy and other component, we want to make sure every call in proxy has to go to meta cache but not directly call "DescribeCollection"

There's only one direct `DescribeCollection` call without going to meta cache——implementation of `GetRecoveryInfo` in DataCoord. I think it's just fine to call `DescribeCollection` because `GetRecoveryInfo` is not very frequent. How do you think? @xiaofan-luan
