### ISSUE TITLE
[Bug]: Search latency becomes high when migrating data from 1.1 to 2.1 by Milvus Data Migration Tool

### ISSUE THREAD

**Issue by cndpzc** [milvus-io/milvus#19003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.0
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.0
- OS(Ubuntu or CentOS): Amazon Linux
- CPU/Memory: 12C/8Gi
- GPU: 
- Others:
```

### Current Behavior

When we migrate data from V1.1 to V2.1, we find that search latency becomes very high, from 10ms in V1.1 to 300ms+.

Data properties:

- Row count: 5.5M
- Dim 100
- Index: IVF_FLAT with nlist = 4096

Search pattern
- nq=1, topk=5, nprobe=128
- concurrency=1

### Expected Behavior

Latency < 20ms

### Milvus Log

[1_x_migration_0902.tar.gz](https://github.com/milvus-io/milvus/files/9477304/1_x_migration_0902.tar.gz)

### Anything else?

[show_segment.txt](https://github.com/milvus-io/milvus/files/9477300/show_segment.txt)

**Comment by xiaofan-luan** [comment]
/assign @czs007 
please follow up why the search latency is high?

**Comment by bigsheeper** [comment]
Hi~ @cndpzc , I'd like to know what kind of consistency level you use when create collection and search, for more infomation: https://milvus.io/docs/v2.1.x/consistency.md

**Comment by cndpzc** [comment]
I see the consistency level of collection is strong, and I don't set consistency level in search.

**Comment by bigsheeper** [comment]
> onsistency level of collection is stro

you can try with consistency level EVENTUALLY,  if everything goes well, latency would be going down.

**Comment by cndpzc** [comment]
In creating collection or search query?

**Comment by bigsheeper** [comment]
> In creating collection or search query?

Search's priority of consistency level is higher than createCollection. If the cluster is still running, would try set consistency level when search. If not, could set when create collection. Anyway, for your convenient.

**Comment by cndpzc** [comment]
@bigsheeper I set consistency level to `Eventually` in search, but latency remains 200-300ms.

**Comment by bigsheeper** [comment]
> @bigsheeper I set consistency level to `Eventually` in search, but latency remains 200-300ms.

Hello @cndpzc ,can you offer me the script you run? If there's any confidential information, you could remove that confidential part.

**Comment by bigsheeper** [comment]
@cndpzc Hi cndpzc, could you please offer me the milvus log? you can export milvus log with this script: https://github.com/milvus-io/milvus/tree/master/deployments/export-log

**Comment by cndpzc** [comment]
@bigsheeper Sure, but maybe need to wait for some time. We found logs in our environment are not completed, solving this in #19015

**Comment by bigsheeper** [comment]
> @bigsheeper Sure, but maybe need to wait for some time. We found logs in our environment are not completed, solving this in #19015

Ok :)

**Comment by cndpzc** [comment]
After we change the param `log.persistence.enabled` (see [here](https://github.com/milvus-io/milvus/issues/19015#issuecomment-1238046105)) and restart the service, search latency decreases to `120ms`. However it's still much higher than `10ms` in V1.1.

Here're the metrics and logs FYI
<img width="1817" alt="image" src="https://user-images.githubusercontent.com/3941929/188775786-b8149bd4-c2c7-4995-a996-0f658e32cb7a.png">
[logs-20220907.tar.gz](https://github.com/milvus-io/milvus/files/9502287/logs-20220907.tar.gz)

**Comment by bigsheeper** [comment]
@cndpzc log shows that purging memory operation is too frequent and cost dozens of milliseconds. And purging has been deprecated now, you can try with the latest version https://hub.docker.com/layers/milvusdb/milvus/2.1.0-latest/images/sha256-155657d14db5b93b1d5784e5e6c2d4bba281bd26ba703bee8b172f1c2bed3b13?context=explore

**Comment by cndpzc** [comment]
@bigsheeper Thank you for investigating! I'll give a try later. May I ask two questions?
- When was purging memory deprecated? 
- Is this issue related to DM tool migration?

**Comment by bigsheeper** [comment]
> @bigsheeper Thank you for investigating! I'll give a try later. May I ask two questions?
> 
> * When was purging memory deprecated?
> * Is this issue related to DM tool migration?

@cndpzc You're wellcome :), for your questions:
1. After #18612 , milvus uses Jemalloc as memory allocator, so purging memory is unnecessary;
2. This issue is not related to milvusDM.

**Comment by cndpzc** [comment]
New test result is interesting... We didn't touch the script nor Milvus nodes. From metrics or client-side logs, we can see latency decrease a lot at 14:40. Can't explain why this happen...

<img width="1691" alt="image" src="https://user-images.githubusercontent.com/3941929/188852050-0f0e1d55-b640-4ff2-a261-af09c3137f8f.png">


[clinet-side-logs.zip](https://github.com/milvus-io/milvus/files/9505062/clinet-side-logs.zip)
[logs-20220907.tar.gz](https://github.com/milvus-io/milvus/files/9505070/logs-20220907.tar.gz)

(Time in log is UTC format)
...
2022-09-07 04:31:02,145 [INFO] (8936) - task 70, nq: 1, cost 84.492 108.516 112.737
2022-09-07 04:44:42,304 [INFO] (8936) - task 71, nq: 1, cost 83.54 108.084 112.473
2022-09-07 04:58:15,446 [INFO] (8936) - task 72, nq: 1, cost 83.093 108.023 112.269
2022-09-07 05:11:47,328 [INFO] (8936) - task 73, nq: 1, cost 82.852 107.917 112.419
2022-09-07 05:25:32,279 [INFO] (8936) - task 74, nq: 1, cost 84.486 108.097 112.605
2022-09-07 05:39:06,123 [INFO] (8936) - task 75, nq: 1, cost 82.747 107.973 112.73
2022-09-07 05:52:37,858 [INFO] (8936) - task 76, nq: 1, cost 82.7 107.699 111.894
2022-09-07 06:06:13,242 [INFO] (8936) - task 77, nq: 1, cost 82.998 107.638 112.434
2022-09-07 06:14:47,646 [ERROR] (8936) - RPC error: [search], <MilvusException: (code=1, message=syncTimestamp Failed:err: find no available rootcoord, check rootcoord state
....(a lot of exceptions)
2022-09-07 06:41:39,401 [INFO] (8936) - task 259, nq: 1, cost 19.148 21.13 22.749
2022-09-07 06:44:45,305 [INFO] (8936) - task 260, nq: 1, cost 18.488 20.371 21.759
2022-09-07 06:47:53,012 [INFO] (8936) - task 261, nq: 1, cost 18.689 20.446 21.643
2022-09-07 06:50:58,273 [INFO] (8936) - task 262, nq: 1, cost 18.437 20.177 21.352

**Comment by cndpzc** [comment]
@bigsheeper Sure, looking forward to V2.1.2 :)

**Comment by yuliu-eric** [comment]
[values.txt](https://github.com/milvus-io/milvus/files/9523334/values.txt)
上面`Environment`的资源配置相关信息不准确，我把启动集群的配置文件贴在这里了。
