### ISSUE TITLE
[Bug]: query performance become worser when a querynode was down

### ISSUE THREAD

**Issue by psc0606** [milvus-io/milvus#19019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.1, java-sdk-2.1.0-beta4
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: proxy(3 pods, 1core and 8G per pod), all coord(root, data, index) (1pod, 4core and 8G), datanode(10 pods, 2core and 8G per pod), indexnode(20 pods, 4core and 4G per pod), querynode(30pods, 1core and 8G per pod)
- GPU: None
- Others: None
```

### Current Behavior

When one querynode of milvus was down, then a new querynode was added into the cluster. But an abnormal phenomenon occurred:
The query performance become worser though a new querynode recovered.
![image](https://user-images.githubusercontent.com/7888889/188401924-dcf14e78-3e17-4882-8b61-e2dfbed47368.png)

So, I released the collection and reload it, the query time cost become normal again.

### Milvus Log

one of slow querynode: 
[milvus-querynode-p5v2.log](https://github.com/milvus-io/milvus/files/9488197/milvus-querynode-p5v2.log)

The querynode was down for manual maintenance perpose, so the querynode had no any ERROR log.

querycoord log: 
[milvus-querycoord-6fv7l.log](https://github.com/milvus-io/milvus/files/9488231/milvus-querycoord-6fv7l.log)

**Comment by yanliang567** [comment]
/assign @xige-16 
sound like a load inbalance issue

/unassign

**Comment by xige-16** [comment]
investing...
