### ISSUE TITLE
[Bug]: the `Flush` privilege can't be granted

### ISSUE THREAD

**Issue by SimFG** [milvus-io/milvus#19018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The `Flush` privilege can't be granted

**Comment by ICLzhang** [comment]
Can you provide a more detailed description of the process where the problem occurs or export the logs with the log tool。https://github.com/milvus-io/milvus/tree/master/deployments/export-log
