### ISSUE TITLE
[Bug]: fail to search on all shard leaders

### ISSUE THREAD

**Issue by cjh6666688888** [milvus-io/milvus#19027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:milvus:v2.1.0
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Query exception：
fail to search on all shard leaders, err=fail to Search, QueryNode ID=341, reason=ShardCluster for nlp_one-rootcoord-dml_2_435509622751625217v0 replicaID 435236143614925732 is no available
fail to search on all shard leaders, err=fail to Search, QueryNode ID=344, reason=ShardCluster for nlp_one-rootcoord-dml_2_435509622751625217v0 replicaID 435236143614925731 is no available
fail to search on all shard leaders, err=fail to Search, QueryNode ID=51, reason=ShardCluster for nlp_one-rootcoord-dml_3_435509622751625217v1 replicaID 435236143614925731 is no available

### Steps To Reproduce

```markdown
1.Indexes are deleted and resources are released
2.Add indexes and load data into memory
3.Query exception：
fail to search on all shard leaders, err=fail to Search, QueryNode ID=341, reason=ShardCluster for nlp_one-rootcoord-dml_2_435509622751625217v0 replicaID 435236143614925732 is no available
fail to search on all shard leaders, err=fail to Search, QueryNode ID=344, reason=ShardCluster for nlp_one-rootcoord-dml_2_435509622751625217v0 replicaID 435236143614925731 is no available
fail to search on all shard leaders, err=fail to Search, QueryNode ID=51, reason=ShardCluster for nlp_one-rootcoord-dml_3_435509622751625217v1 replicaID 435236143614925731 is no available
```

### Milvus Log

fail to search on all shard leaders, err=fail to Search, QueryNode ID=341, reason=ShardCluster for nlp_one-rootcoord-dml_2_435509622751625217v0 replicaID 435236143614925732 is no available
fail to search on all shard leaders, err=fail to Search, QueryNode ID=344, reason=ShardCluster for nlp_one-rootcoord-dml_2_435509622751625217v0 replicaID 435236143614925731 is no available
fail to search on all shard leaders, err=fail to Search, QueryNode ID=51, reason=ShardCluster for nlp_one-rootcoord-dml_3_435509622751625217v1 replicaID 435236143614925731 is no available

**Comment by yanliang567** [comment]
Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @cjh6666688888 
/unassign

**Comment by ICLzhang** [comment]
Service has been restored in milvus2.1.2。
