### ISSUE TITLE
[Bug]: Memory Leak on QueryCoord, goroutine increased to 1 million

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#19037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.0-20220902-853793a
- Deployment mode(standalone or cluster): cluster
```

### Current Behavior

querycoord memory increased to 5+GB in 24 hours, and Goroutines querycoord increased to 1+ million
![image](https://user-images.githubusercontent.com/82361606/188534985-424a0470-449a-4f57-b742-39e83ea68ba9.png)
![image](https://user-images.githubusercontent.com/82361606/188535034-d66b3200-0b7e-4ed5-8395-34b1c838bd56.png)
![image](https://user-images.githubusercontent.com/82361606/188535063-f1d392fc-75a3-440d-a5b8-e7d029f32f1f.png)

### Expected Behavior

memory keeps stable

### Steps To Reproduce

```markdown
1. upgrade milvus image from 2.1 to 2.1.0-20220902-853793a
2. insert, search, scale querynode, etc.
```

### Milvus Log

[querycoord.mem.leak.log](https://github.com/milvus-io/milvus/files/9492886/querycoord.mem.leak.log)

**Comment by xiaofan-luan** [comment]
should not be problem in querycoordV2
