### ISSUE TITLE
[Bug]:  Unstable ut failed for msgstream

### ISSUE THREAD

**Issue by jennyli-z** [milvus-io/milvus#19039]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://github.com/milvus-io/milvus/runs/8185786388?check_suite_focus=true
it failed sometime github.com/milvus-io/milvus/internal/mq/msgstream
![image](https://user-images.githubusercontent.com/93511422/188543686-acbd336d-38d5-402a-84ae-a491217fd156.png)

**Comment by jiaoew1991** [comment]
dup with https://github.com/milvus-io/milvus/issues/19192, track it together.

**Comment by jiaoew1991** [comment]
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/2297455/190940969-00863fcc-2131-4d5a-96ff-b0157b5f9a80.png">
