### ISSUE TITLE
[Bug]: "search Request latency" and "search segment latency" are quite low,but the search latency of end to end is still high.

### ISSUE THREAD

**Issue by dzqoo** [milvus-io/milvus#19042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.0
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): centos
- CPU/Memory: querynode's cpu is 4 and querynode's memory is 16Gi
- GPU: 
- Others:
```

### Current Behavior

When I expand querynode's num to 30,I got a real low "search Request latency" and "search segment latency",where is dozens ms .BUT, the end2end search latency is still high，where is exceed 300ms.
I wonder to know where is the bottleneck.

- Here is the metrics dashboard:
![search segment latency](https://user-images.githubusercontent.com/8862305/188559172-4a5ca9d5-2f0d-4f36-9339-bf06f41dc0a8.jpg)
![search Request latency](https://user-images.githubusercontent.com/8862305/188559266-31ec6a30-9189-4058-b3ed-8a77869a7f0d.jpg)
![end2end search latency](https://user-images.githubusercontent.com/8862305/188559313-87e35c05-e260-462c-a823-a850e0f17762.jpg)

- Here is my cluster config:
[values.log](https://github.com/milvus-io/milvus/files/9493746/values.log)

-Here is the cluster's total log:
[Uploading milvus-log.tar.gz…]()

**Comment by dzqoo** [comment]
[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/9493853/milvus-log.tar.gz)
reupload milvus log

**Comment by dzqoo** [comment]
> [milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/9493853/milvus-log.tar.gz) reupload milvus log
please refer the ”ai-diagnose-test“ part.Thanks.

**Comment by yanliang567** [comment]
@dzqoo  thank you for the issue.  how many entities did you inserted for this collection? could you please also share the cpu and memory metrics for query nodes, we'd like to check if the segments are balanced ?

**Comment by dzqoo** [comment]
> @dzqoo thank you for the issue. how many entities did you inserted for this collection? could you please also share the cpu and memory metrics for query nodes, we'd like to check if the segments are balanced ?

I have 600M entities and 128 dimension.
Here are the queryNode metrics:
![cpu usage](https://user-images.githubusercontent.com/8862305/188570881-acb47e44-f1d2-4595-9295-7f0c11a94bac.png)
![memory](https://user-images.githubusercontent.com/8862305/188571108-27c456d5-72e1-4d13-82e0-6115dc852a6c.png)

**Comment by dzqoo** [comment]
> > @dzqoo thank you for the issue. how many entities did you inserted for this collection? could you please also share the cpu and memory metrics for query nodes, we'd like to check if the segments are balanced ?
> 
> I have 600M entities and 128 dimension. Here are the queryNode metrics: ![cpu usage](https://user-images.githubusercontent.com/8862305/188570881-acb47e44-f1d2-4595-9295-7f0c11a94bac.png) ![memory](https://user-images.githubusercontent.com/8862305/188571108-27c456d5-72e1-4d13-82e0-6115dc852a6c.png)

It's wrong：600M => 6M...

**Comment by yanliang567** [comment]
@dzqoo thank you for quick reply. 
1. the Search Request Latency on querynode view, it contains time cost in search and map reduce in this querynode.
2. the Search Latency on proxy view, it contains a) the time cost from proxy to querynode and response, and b) map reduce in proxy for results from all querynodes. 
In this case, I think it cost more time in map reduce as you have many querynodes.
So, if you are looking for a better search latency for 6 million vectors' collection, I think 6 or 12 querynodes are enough.  Because 6M-128d data shall be about 12 segments, 6 or 12 querynodes would be a good balance for 12 segments. Please try it and keep me posted if any issues.

**Comment by dzqoo** [comment]
> > @dzqoo thank you for quick reply.
> > 
> > 1. the Search Request Latency on querynode view, it contains time cost in search and map reduce in this querynode.
> > 2. the Search Latency on proxy view, it contains a) the time cost from proxy to querynode and response, and b) map reduce in proxy for results from all querynodes.
> >    In this case, I think it cost more time in map reduce as you have many querynodes.
> >    So, if you are looking for a better search latency for 6 million vectors' collection, I think 6 or 12 querynodes are enough.  Because 6M-128d data shall be about 12 segments, 6 or 12 querynodes would be a good balance for 12 segments. Please try it and keep me posted if any issues.
> 
> I don‘t think so. Although I have so many queynode, are all the querynode will apply a search?In my opinion，which querynode will apply search is definited from the begining.

I have test with 14 queryNode(my entities is nearly 7M).And I got the following result:
![end2end search latency](https://user-images.githubusercontent.com/8862305/188770750-44240db4-925e-43bb-b7b3-0609252dd7e4.png)
![Search in queue latency](https://user-images.githubusercontent.com/8862305/188771484-ab481110-ab3b-4da4-9b1b-5c25c90fed87.png)
![Search Segment latency](https://user-images.githubusercontent.com/8862305/188771594-95dc2c38-001a-4eea-929f-6383439435a7.png)

And I alse got the Search Reduce Latency，which is very low also as you see:
![Search reduce latency](https://user-images.githubusercontent.com/8862305/188772211-14dcd198-1d39-4de3-9eb3-6da47b862610.png)

**Comment by yanliang567** [comment]
@dzqoo could you please also share tehe Search Vector Count Rate on Proxy? and Search Request Rage on QueryNode?

**Comment by dzqoo** [comment]
> 
![Search Vector Count Rate](https://user-images.githubusercontent.com/8862305/188779685-9d118104-da4e-4f41-b3ae-cb7d069312e0.png)
![Search Request Rate on queryNode](https://user-images.githubusercontent.com/8862305/188780093-cbb3ab3c-7092-479a-ad75-63d003f9e2ae.png)

**Comment by dzqoo** [comment]
![Search Request Rate on QueryNode](https://user-images.githubusercontent.com/8862305/188780217-b5d5e9ce-8b62-4813-ac39-b0bd46c7b5b0.png)

**Comment by yanliang567** [comment]
@czs007 could you please take a look as well?

**Comment by dzqoo** [comment]
I have another question..
Why my 7m collection has 26 segments as is showed following:
![image](https://user-images.githubusercontent.com/8862305/188824720-6ec78111-9573-4d20-8dba-cd3d66228472.png)

**Comment by jingkl** [comment]
`kubectl exec -it fouram-tag-no-clean-szxjd-1-minio-866b878fb9-4f7nt -n qa-milvus -- bash`

**Comment by dzqoo** [comment]
> 2\. milvus

![image](https://user-images.githubusercontent.com/8862305/188877136-3532d4a1-388d-41a7-860e-7b8d556b6d79.png)
Here is my result. It's normal?

**Comment by yanliang567** [comment]
@dzqoo looks like you have many small segments that should had been compacted.  Please try:
1. run `collection.compact() ` to manually trigger a compaction task
2. wait a few seconds and run `utility.index_building_progress("collection_name") `   ,  then you will see indexing restarted for new compacted segments
3. after building progress completed to 100%, release and reload the collection to make sure all the index files were loaded 
4. search again and check the latency.
5. if the latency did not improve, please send me the results of `utility.get_query_segment_info("collection_name")`

**Comment by dzqoo** [comment]
After I trigger the manual compaction, I got a much worse result as you see in the following:
![image](https://user-images.githubusercontent.com/8862305/189016557-bd627f6e-467c-4cdd-aa2d-ce4ee122a00e.png)
And the num of segment is also not changed.

Here is the resutl of utility.get_query_segment_info("collection_name"):
`[segmentID: 435840936925462529
collectionID: 435780125802889217
partitionID: 435780125802889218
num_rows: 271414
state: Sealed
nodeIds: 227
, segmentID: 435840783688663045
collectionID: 435780125802889217
partitionID: 435780125802889218
num_rows: 271548
state: Sealed
nodeIds: 227
, segmentID: 435840803231498242
collectionID: 435780125802889217
partitionID: 435780125802889218
num_rows: 271361
state: Sealed
nodeIds: 230
, segmentID: 435840978867978241
collectionID: 435780125802889217
partitionID: 435780125802889218
num_rows: 270913
state: Sealed
nodeIds: 233
, segmentID: 435840839931920386
collectionID: 435780125802889217
partitionID: 435780125802889218
num_rows: 270946
state: Sealed
nodeIds: 226
, segmentID: 435840923817738241
collectionID: 435780125802889217
partitionID: 435780125802889218
num_rows: 271510
state: Sealed
nodeIds: 226
, segmentID: 435840921196560385
collectionID: 435780125802889217
partitionID: 435780125802889218
num_rows: 271631
state: Sealed
nodeIds: 227
, segmentID: 435840803231498241
collectionID: 435780125802889217
partitionID: 435780125802889218
num_rows: 271465
state: Sealed
nodeIds: 231
, segmentID: 435840971003658241
collectionID: 435780125802889217
partitionID: 435780125802889218
num_rows: 270962
state: Sealed
nodeIds: 233
, segmentID: 435840986732298241
collectionID: 435780125802889217
partitionID: 435780125802889218
num_rows: 135600
state: Sealed
nodeIds: 234
, segmentID: 435840876632080386
collectionID: 435780125802889217
partitionID: 435780125802889218
num_rows: 270769
state: Sealed
nodeIds: 235
, segmentID: 435840908089360385
collectionID: 435780125802889217
partitionID: 435780125802889218
num_rows: 271666
state: Sealed
nodeIds: 226
, segmentID: 435840858281738241
collectionID: 435780125802889217
partitionID: 435780125802889218
num_rows: 270824
state: Sealed
nodeIds: 230
, segmentID: 435840783688663047
collectionID: 435780125802889217
partitionID: 435780125802889218
num_rows: 271497
state: Sealed
nodeIds: 230
, segmentID: 435840905467658241
collectionID: 435780125802889217
partitionID: 435780125802889218
num_rows: 271689
state: Sealed
nodeIds: 233
, segmentID: 435840950032138241
collectionID: 435780125802889217
partitionID: 435780125802889218
num_rows: 271250
state: Sealed
nodeIds: 234
, segmentID: 435840894982160385
collectionID: 435780125802889217
partitionID: 435780125802889218
num_rows: 135625
state: Sealed
nodeIds: 234
, segmentID: 435840858281738242
collectionID: 435780125802889217
partitionID: 435780125802889218
num_rows: 270789
state: Sealed
nodeIds: 235
, segmentID: 435840876632080385
collectionID: 435780125802889217
partitionID: 435780125802889218
num_rows: 270771
state: Sealed
nodeIds: 231
, segmentID: 435840963126493185
collectionID: 435780125802889217
partitionID: 435780125802889218
num_rows: 270985
state: Sealed
nodeIds: 231
, segmentID: 435840839931920385
collectionID: 435780125802889217
partitionID: 435780125802889218
num_rows: 271042
state: Sealed
nodeIds: 233
, segmentID: 435840939546378241
collectionID: 435780125802889217
partitionID: 435780125802889218
num_rows: 271403
state: Sealed
nodeIds: 235
, segmentID: 435840821581578242
collectionID: 435780125802889217
partitionID: 435780125802889218
num_rows: 271054
state: Sealed
nodeIds: 235
, segmentID: 435840821581578241
collectionID: 435780125802889217
partitionID: 435780125802889218
num_rows: 271223
state: Sealed
nodeIds: 227
, segmentID: 435840955275280385
collectionID: 435780125802889217
partitionID: 435780125802889218
num_rows: 271119
state: Sealed
nodeIds: 230
, segmentID: 435840894982160386
collectionID: 435780125802889217
partitionID: 435780125802889218
num_rows: 271710
state: Sealed
nodeIds: 234
]`

**Comment by yanliang567** [comment]
"Search Latency" on proxy is e2e latency, and it was determined by the slowest "Search Request Latency" of querynode , so if comparing with the slowest "search request latency" of querynodes, it is about 30ms gap, which i think is reasonable.

The other issue in this case is that many small segments were not compacted, even after manually call collection.compact().

**Comment by yanliang567** [comment]
@jiaoew1991 could u please help to take a look at the not compact issue? here attached the datanode logs
[data0.log](https://github.com/milvus-io/milvus/files/9526636/data0.log)
[data1.log](https://github.com/milvus-io/milvus/files/9526637/data1.log)

**Comment by yanliang567** [comment]
here attached logs from @dzqoo [milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/9531909/milvus-log.tar.gz)

**Comment by congqixia** [comment]
hi @dzqoo could you please export the etct meta backup using this tool?
https://github.com/milvus-io/birdwatcher

**Comment by dzqoo** [comment]
> hi @dzqoo could you please export the etct meta backup using this tool? https://github.com/milvus-io/birdwatcher

[bw_etcd_ALL.220909-122717.bak.gz](https://github.com/milvus-io/milvus/files/9532325/bw_etcd_ALL.220909-122717.bak.gz)
Here is the backup.How Can I read it?

**Comment by congqixia** [comment]
@dzqoo looks like the backup file is empty. Did you connect to your instance successfully? To verify connection, you could try some `show` commands to list some meta information of you instance. Such as `show collections` or `show segments`

**Comment by dzqoo** [comment]
> @dzqoo looks like the backup file is empty. Did you connect to your instance successfully? To verify connection, you could try some `show` commands to list some meta information of you instance. Such as `show collections` or `show segments`

How can I connect etcd when I deploy a cluster milvus?

**Comment by yanliang567** [comment]
@congqixia could you please give a hand here?

**Comment by yanliang567** [comment]
summarize the problems：
Many segments with 27MB did not compact into bigger segments, but compact to new 27MB segments(with new segment ids), even after collection.compact() called manually

**Comment by congqixia** [comment]
Hi @dzqoo , just added a `dry-mode` command to select possible milvus instance after connect to etcd with `birdwatcher`
Here are some example:
```
Offline > connect --dry
Using meta path: by-dev/meta/
using dry mode, ignore rootPath and metaPath
Etcd(127.0.0.1:2379) > find-milvus
2 candidates found:
by-dev
session
Etcd(127.0.0.1:2379) > use by-dev
Using meta path: by-dev/meta/
Milvus(by-dev) > 
```

**Comment by dzqoo** [comment]
> 

cool ~ It is worked ! I have a wrong understand about the rootPath before...
Here is my backend meta of all component.
[bw_etcd_ALL.220914-135248.bak.gz](https://github.com/milvus-io/milvus/files/9563114/bw_etcd_ALL.220914-135248.bak.gz)

**Comment by congqixia** [comment]
@dzqoo @yanliang567 Here are some analysis result from the meta:
```
SegmentID: 435863473641488387	 State: Flushed	Index build ID: 435863491793125378, state: Finished 
SegmentID: 435863473641488389	 State: Flushed	Index build ID: 435863491793125380, state: Finished 
SegmentID: 435863491794960385	 State: Flushed	Index build ID: 435863510169419778, state: Finished 
SegmentID: 435863491794960386	 State: Flushed	Index build ID: 435863510143205378, state: Finished 
SegmentID: 435863510145040385	 State: Flushed	Index build ID: 435863528650571778, state: Finished 
SegmentID: 435863510145040386	 State: Flushed	Index build ID: 435863528493285378, state: Finished 
SegmentID: 435863528494858241	 State: Flushed	Index build ID: 435863546843365378, state: Finished 
SegmentID: 435863528494858242	 State: Flushed	Index build ID: 435863547000389634, state: Finished 
SegmentID: 435863546844938241	 State: Flushed	Index build ID: 435863565193445378, state: Finished 
SegmentID: 435863546844938242	 State: Flushed	Index build ID: 435863565298302978, state: Finished 
SegmentID: 435863565195018241	 State: Flushed	Index build ID: 435863583543525378, state: Finished 
SegmentID: 435863565195018242	 State: Flushed	Index build ID: 435863584106872834, state: Finished 
SegmentID: 435863583545360385	 State: Flushed	Index build ID: 435863594029285378, state: Finished 
SegmentID: 435863583545360386	 State: Flushed	Index build ID: 435863596650463234, state: Finished 
SegmentID: 435863594030858241	 State: Flushed	Index build ID: 435863609757925378, state: Finished 
SegmentID: 435863596639191041	 State: Flushed	Index build ID: 435863615000805378, state: Finished 
SegmentID: 435863609760022529	 State: Flushed	Index build ID: 435863622865125378, state: Finished 
SegmentID: 435863615002640385	 State: Flushed	Index build ID: 435863630729445378, state: Finished 
SegmentID: 435863622866698241	 State: Flushed	Index build ID: 435863637191294978, state: Finished 
SegmentID: 435863630731280385	 State: Flushed	Index build ID: 435863646458085378, state: Finished 
SegmentID: 435863635960791041	 State: Flushed	Index build ID: 435863652841291778, state: Finished 
SegmentID: 435863646459920385	 State: Flushed	Index build ID: 435863662881406978, state: Finished 
SegmentID: 435863651689693185	 State: Flushed	Index build ID: 435863672738021378, state: Finished 
SegmentID: 435863659567120385	 State: Flushed	Index build ID: 435863684665573378, state: Finished 
SegmentID: 435863667418071041	 State: Flushed	Index build ID: 435863698192203778, state: Finished 
SegmentID: 435863672660951042	 State: Flushed	Index build ID: 435863710329208834, state: Finished 
SegmentID: 435842171177795587	 State: Flushed	no segment index info
SegmentID: 435842220775440387	 State: Flushed	no segment index info
SegmentID: 435958797024624643	 State: Flushed	Index build ID: 435959980762071044, state: Finished 
SegmentID: 435958797182173186	 State: Flushed	Index build ID: 435959980722749444, state: Finished 
SegmentID: 435958888565309444	 State: Flushed	Index build ID: 435959980788285442, state: Finished 
SegmentID: 435958890977034241	 State: Flushed	Index build ID: 435959986254249986, state: Finished 
SegmentID: 435958906286505988	 State: Flushed	Index build ID: 435959998286659586, state: Finished 
SegmentID: 435958906692567049	 State: Flushed	Index build ID: 435959985074339842, state: Finished 
SegmentID: 435958927886909443	 State: Flushed	Index build ID: 435959980722749442, state: Finished 
SegmentID: 435958928057303041	 State: Flushed	Index build ID: 435959984602480642, state: Finished 
SegmentID: 435958953891856388	 State: Flushed	Index build ID: 435959980748963844, state: Finished 
SegmentID: 435958953904701442	 State: Flushed	Index build ID: 435959980801392644, state: Finished 
SegmentID: 435958974548541444	 State: Flushed	Index build ID: 435959980748963842, state: Finished 
SegmentID: 435958984247869444	 State: Flushed	Index build ID: 435959980762071046, state: Finished 
SegmentID: 435958994471485444	 State: Flushed	Index build ID: 435959980775178242, state: Finished 
SegmentID: 435959001064669187	 State: Flushed	Index build ID: 435959995822243842, state: Finished 
SegmentID: 435959014709002244	 State: Flushed	Index build ID: 435959980709642244, state: Finished 
SegmentID: 435959016806154241	 State: Flushed	Index build ID: 435959980722749446, state: Finished 
SegmentID: 435959037882531843	 State: Flushed	Index build ID: 435959981509181442, state: Finished 
SegmentID: 435959038040080385	 State: Flushed	Index build ID: 435959988691927042, state: Finished 
SegmentID: 435959058591907843	 State: Flushed	Index build ID: 435959980801392642, state: Finished 
SegmentID: 435959058736087041	 State: Flushed	Index build ID: 435959982793687042, state: Finished 
SegmentID: 435959086274314243	 State: Flushed	Index build ID: 435959980709642246, state: Finished 
SegmentID: 435959086444707841	 State: Flushed	Index build ID: 435959981666467842, state: Finished 
SegmentID: 435959100010659844	 State: Flushed	Index build ID: 435959985598627842, state: Finished 
SegmentID: 435959109728337923	 State: Flushed	Index build ID: 435959980775178244, state: Finished 
SegmentID: 435959118465597444	 State: Flushed	Index build ID: 435959981981302786, state: Finished 
SegmentID: 435959124914601988	 State: Flushed	Index build ID: 435960000881623042, state: Finished 
SegmentID: 435959142622167043	 State: Flushed	Index build ID: 435959987931709442, state: Finished 
SegmentID: 435959145676144643	 State: Flushed	Index build ID: 435959980788285444, state: Finished 
SegmentID: 435959154956042244	 State: Flushed	Index build ID: 435959980709642242, state: Finished 
SegmentID: 435959163606794243	 State: Flushed	Index build ID: 435959982505328642, state: Finished 
SegmentID: 435959174105923585	 State: Flushed	Index build ID: 435959983186903042, state: Finished 
SegmentID: 435959176766423043	 State: Flushed	Index build ID: 435959992597872642, state: Finished 
SegmentID: 435959189808087043	 State: Flushed	Index build ID: 435959993646448642, state: Finished 
SegmentID: 435959191446487044	 State: Flushed	Index build ID: 435959982217232386, state: Finished 
SegmentID: 435959194054819841	 State: Flushed	Index build ID: 435959980762071042, state: Finished 
SegmentID: 435959204160471041	 State: Flushed	Index build ID: 435959990500720642, state: Finished 
SegmentID: 435959204186685441	 State: Flushed	Index build ID: 435959981797801986, state: Finished 
SegmentID: 435959205536727043	 State: Flushed	Index build ID: 435959984209264642, state: Finished 
SegmentID: 435963231321456645	 State: Flushed	no segment index info
SegmentID: 435963846547210243	 State: Flushed	no segment index info
SegmentID: 435964272963747843	 State: Flushed	no segment index info
SegmentID: 435964284983312387	 State: Flushed	no segment index info
SegmentID: 435964297146531843	 State: Flushed	no segment index info
SegmentID: 435964309467561985	 State: Flushed	no segment index info
SegmentID: 435964321709424643	 State: Flushed	no segment index info
SegmentID: 435964334004240387	 State: Flushed	no segment index info
SegmentID: 435964346115293187	 State: Flushed	no segment index info
SegmentID: 435964358488489987	 State: Flushed	no segment index info
SegmentID: 435964361712599041	 State: Flushed	no segment index info
SegmentID: 435964370664816643	 State: Flushed	no segment index info
SegmentID: 435964383129763843	 State: Flushed	no segment index info
SegmentID: 435964383182454787	 State: Flushed	no segment index info
SegmentID: 435964395345674241	 State: Flushed	no segment index info
SegmentID: 435964407600906243	 State: Flushed	no segment index info
SegmentID: 435964419908567043	 State: Flushed	no segment index info
SegmentID: 435964419908567046	 State: Flushed	no segment index info
SegmentID: 435964431888547843	 State: Flushed	no segment index info
SegmentID: 435964444314173443	 State: Flushed	no segment index info
SegmentID: 435964456464809987	 State: Flushed	no segment index info
SegmentID: 435964469689712643	 State: Flushed	no segment index info
SegmentID: 435964472599511041	 State: Flushed	no segment index info
SegmentID: 435964481433763843	 State: Flushed	no segment index info
SegmentID: 435964493990461444	 State: Flushed	no segment index info
SegmentID: 435964497136189441	 State: Flushed	no segment index info
SegmentID: 435964506298122243	 State: Flushed	no segment index info
SegmentID: 435964509692887041	 State: Flushed	no segment index info
SegmentID: 435964518606045188	 State: Flushed	no segment index info
SegmentID: 435964522236677441	 State: Flushed	no segment index info
SegmentID: 435964530953027588	 State: Flushed	no segment index info
SegmentID: 435976651587128641	 State: Flushing
SegmentID: 435980646727024641	 State: Flushed	Index build ID: 435980650646339586, state: Finished 
SegmentID: 435980653687409985	 State: Flushed	Index build ID: 435980657632477186, state: InProgress 
SegmentID: 435980659860439041	 State: Flushed	Index build ID: 435980663753277442, state: InProgress 
SegmentID: 435980665968594241	 State: Flushed	Index build ID: 435980669874601986, state: InProgress 
SegmentID: 435980671945477441	 State: Flushed	Index build ID: 435980676166057986, state: InProgress 
SegmentID: 435980677896408385	 State: Flushed	Index build ID: 435980681946071042, state: InProgress 
SegmentID: 435980683938365441	 State: Flushed	Index build ID: 435980687883632642, state: InProgress 
SegmentID: 435980689928555841	 State: Flushed	Index build ID: 435980693913206786, state: InProgress 
SegmentID: 435980696102047041	 State: Flushed	Index build ID: 435980700125757442, state: InProgress 
SegmentID: 435980702223109441	 State: Flushed	Index build ID: 435980706233712642, state: InProgress 
SegmentID: 435980708475243841	 State: Dropped
SegmentID: 435980714569891841	 State: Dropped
SegmentID: 435980718685552643	 State: Flushed	Index build ID: 435980727572234242, state: Unissued 
SegmentID: 435980720927345985	 State: Dropped
SegmentID: 435980727296983041	 State: Dropped
SegmentID: 435980731294679043	 State: Flushed	Index build ID: 435980738228649986, state: InProgress 
SegmentID: 435980733522903041	 State: Dropped
SegmentID: 435980739958538241	 State: Dropped
SegmentID: 435980743956234243	 State: Flushed	Index build ID: 435980751165194242, state: Unissued 
SegmentID: 435980746184458241	 State: Dropped
SegmentID: 435980752528343041	 State: Dropped
SegmentID: 435980756591575043	 State: Flushed	Index build ID: 435980764259549186, state: Unissued 
SegmentID: 435980758859120641	 State: Dropped
SegmentID: 435980765347384641	 State: Dropped
SegmentID: 435980769489059843	 State: Flushed	Index build ID: 435980777366487042, state: Unissued 
SegmentID: 435980771560197441	 State: Dropped
SegmentID: 435980777838546241	 State: Dropped
SegmentID: 435980781914685443	 State: Flushed	Index build ID: 435980790473687042, state: Unissued 
SegmentID: 435980783959608641	 State: Flushed	Index build ID: 435980788310999042, state: Unissued 
SegmentID: 435980790237757441	 State: Flushed	Index build ID: 435980796909322242, state: Unissued 
SegmentID: 435980796332805441	 State: Flushing
```
looks like some collection has no index built. While some index task is blocked

**Comment by congqixia** [comment]
@dzqoo the reason why collection xxj_paisou_0203_topic, id 435980634380042241 search is slow is that the index build task is stuck. There is a working PR to fix this problem. I shall let you know after the PR is merged.

**Comment by congqixia** [comment]
Issue #19208 is tracking index block problem

**Comment by xiaocai2333** [comment]
Can you provide me with a log of the search time?  @dzqoo

**Comment by dzqoo** [comment]
@xiaocai2333 There is the search log.
https://github.com/milvus-io/milvus/issues/19253

**Comment by xiaocai2333** [comment]
I checked `loadIndex` in all QueryNode's logs, all results are true.

![image](https://user-images.githubusercontent.com/46207236/190971454-f6a998c9-e2f7-470b-94c5-889bdb9b21f7.png)

![image](https://user-images.githubusercontent.com/46207236/190971549-798e07db-b50f-4c8c-9135-61dd4e2408d1.png)

**Comment by xiaocai2333** [comment]
And from the log @yanliang567 gave me, there are many growing segment...
![image](https://user-images.githubusercontent.com/46207236/190971890-3d86cbf1-0030-4ad6-b09b-ef98aa2a7004.png)

And all sealed segments are loaded index.
![image](https://user-images.githubusercontent.com/46207236/190971977-0c8824c2-adab-4ef6-abf2-dd52e2c17e3a.png)

**Comment by yanliang567** [comment]
the building index issue was fixed.
the other issues will be tracked in #20532
