### ISSUE TITLE
[Bug]: The unit of collectionSize is missing in the exception message no enough memory

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#19057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220906-8dce723
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The `collectionSize` without units can confuse users, and they don't know how much memory to increase to load data
![image](https://user-images.githubusercontent.com/27288593/188595767-235c139a-d9c5-4b1d-aae8-dbfbc5ea8fb8.png)

### Expected Behavior

Clearly state the unit, preferably `MiB`

**Comment by yah01** [comment]
/assign @ThreadDao 
For now, the new QueryCoord won't check whether memory is enough to load, it will continuously try to load the collection within 10min, and report "load timeout" if failed to load after that.
