### ISSUE TITLE
[Bug]: Collection loading not responding

### ISSUE THREAD

**Issue by ICLzhang** [milvus-io/milvus#19055]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.0
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.1.1
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I execute the collection.load() operation, the program does not respond.

### Expected Behavior

Returns the success or failure of the load operation.

### Steps To Reproduce

```markdown
1. Open attu & connection collection
2. Click the load button
3. No response & can not operate
```

### Milvus Log

[logs.tar.gz](https://github.com/milvus-io/milvus/files/9495001/logs.tar.gz)

### Anything else?

I guess Milvus underestimates the memory of the load, the load passes the check but cannot be loaded, and it keeps retrying. Whether it should return load failure code after how many times to load.

**Comment by weiliu1031** [comment]
need more info about the load collection hang event:
 1. which collection do you load ?
 2. when do you start the load operation ?

**Comment by ICLzhang** [comment]
1. load hello_milvus by attu. 550w entity 100 dim , IVF_FlAT inde and querynode limit 4G
2. I don't remember the exact time of the operation, but I exported the log after I found the problem
@weiliu1031

**Comment by yanliang567** [comment]
@ICLzhang Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

**Comment by ICLzhang** [comment]
The log file logs.tar.gz has been uploaded when opening an issue

**Comment by weiliu1031** [comment]
from the log, every loadCollection Operation finished in seconds. can you reproduce this issue and provide more detail? 
![image](https://user-images.githubusercontent.com/108661493/188837424-25e1c559-a5a7-438d-858d-7371e0440680.png)
