### ISSUE TITLE
[Bug]: release or load not respond

### ISSUE THREAD

**Issue by SuperLiChen** [milvus-io/milvus#19061]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.1
- Deployment mode(standalone or cluster): standalone 
- SDK version(e.g. pymilvus v2.0.0rc2):  milvus-sdk-java 2.1.0-beta4
- OS(Ubuntu or CentOS):  ubuntu1~20.04.1
- CPU/Memory:  Core(TM) i3-1115G4 @ 3.00GHz / 16GB
- GPU:  GeForce GTX 1070
- Others:
```

### Current Behavior

When I execute the milvus_cli  load -c xxx or  release -c xxx operation,  not respond.

data size: 20W
![image](https://user-images.githubusercontent.com/17897964/188611518-648dcfa2-9b4f-46e2-834c-bea6dacce20b.png)

### Steps To Reproduce

```markdown
1. load collection a
2. create partitions to a
3. collection a load percentage will not 100%
4. release collection a will not respond
```

### Milvus Log

[info.tar.gz](https://github.com/milvus-io/milvus/files/9495703/info.tar.gz)

**Comment by soothing-rain** [comment]
/unassign
/assign @jiaoew1991 

Is this issue resolved in the upcoming 2.1.2 release?

**Comment by weiliu1031** [comment]
system restart, and it try to loadBalance the collection which has been loaded before service restart. and one of loadCollectionTask(cluster_5a9931a7ad951999e787f9f4cee7bac6) Cost 5min, and your load operation is submitted during this period, so it blocks until timeout due to load collection processed in serial.

load collection on cluster_5a9931a7ad951999e787f9f4cee7bac6 cost 5min in from dml load delete record, does this collection did amount of delete before restart? and the reason is still in investigating.

**Comment by SuperLiChen** [comment]
@weiliu1031 
no deletc collection document before restart milvus

maybe the crux of the problem is dynamically creating a partition
because i need search vector in collections, so I will load collection to 100% percentage when start java services 

when I dynamically creating a new partition.
	1. get search error like:  xxx  not loaded or released.
	2. use milvus_cli call release collection or load collection not responed

**Comment by weiliu1031** [comment]
> @weiliu1031 no deletc collection document before restart milvus
> 
> maybe the crux of the problem is dynamically creating a partition because i need search vector in collections, so I will load collection to 100% percentage when start java services
> 
> when I dynamically creating a new partition. 1. get search error like: xxx not loaded or released. 2. use milvus_cli call release collection or load collection not responed

Unfortunately， the load operation hang, is related to dynamically creating partition.

for now, there are some flaws in the handling of dynamically created partitions. here is the case:
1. when you do load collection operation, it will consume stream data from mq with a `position`
2. but if you create a partition without any write operation（empty partition）, and then do load operation, the `position` will use the earliest mq message position, and the consume process will take much more time. 
3. so it produce a 5min load collection stuck, and any load operation after this will also stuck until it finished.

**Comment by weiliu1031** [comment]
> @weiliu1031 Ok, is there any way for me to see the processing progress of the task queue after load? such as birdwathcher

yes, birdwatcher add this feature to check query coord task recently. another way is log, but it's a bit complicated.
