### ISSUE TITLE
[Bug]: [benchmark][stanalone]Milvus' compaction failed, resulting in incorrectly segments size

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#19072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.0-20220906-1d8d919
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.1.2dev2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server-instance
fouram-tag-no-clean-szxjd-1
server-configmap
server-single-32c128m-redur0
client-configmap
client-random-locust-100m-ddl-r8-w2-12h
sever：
```
fouram-tag-no-clean-szxjd-1-etcd-0                                1/1     Running                  0               108s    10.104.9.76    4am-node14   <none>           <none>
fouram-tag-no-clean-szxjd-1-milvus-standalone-6b8bf67f44-pk59q    1/1     Running                  0               108s    10.104.1.12    4am-node10   <none>           <none>
fouram-tag-no-clean-szxjd-1-minio-866b878fb9-4f7nt                1/1     Running                  0               108s    10.104.9.75    4am-node14   <none>           <none>
```

<img width="944" alt="截屏2022-09-07 12 00 41" src="https://user-images.githubusercontent.com/34296482/188786004-57c23900-143a-4fa7-a659-eb9ed5704495.png">
<img width="1316" alt="截屏2022-09-07 12 02 04" src="https://user-images.githubusercontent.com/34296482/188786031-9872c91f-9d28-407c-b812-60ad5ed0efe3.png">

### Expected Behavior

kubectl exec -it fouram-tag-no-clean-szxjd-1-minio-866b878fb9-4f7nt     -n qa-milvus  -- bash
cd / milvus-bucket/file/insert_log/

**Comment by yanliang567** [comment]
@jingkl any requests failed, such as search?

**Comment by jiaoew1991** [comment]
lots of compaction tasks failed because of some segments cannot be found in datanode's metadata, need more time to find out the root cause of metadata inconsistent

**Comment by XuanYang-cn** [comment]
The completed compaction tasks are stored at DataNode. DC retrieves these completed tasks to finish compaction and alter meta.

DataNode changes its segment meta right after the task is completed(which is wrong), once the DC retrieves the tasks and **failed** to finish this compaction task, DC and DN's segments meta are inconsistent.

The following compaction about the old segment will all fail at DataNode. And can never be consistent after.

|Segments in DataNode| Segments in DataCoord|
|---|---|
|A+B -> C| A, B|

**Solution:**

Add an RPC in DataNode, When DC is altering meta from compaction, call this RPC. If RPC fails, DC rollback.

```protobuf
rpc SyncSegment(SyncSegmentRequest) SyncSegmentResponse

message SyncSegmentRequest {
  repeated int64 compactedFrom = 1;
  int64 compactedTo = 2;
}
```
