### ISSUE TITLE
[Bug]: No version and GitCommit in milvus pod logs

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#19079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Before
![FcWsJWGIwa](https://user-images.githubusercontent.com/27288593/188828671-8fe0c8ed-4c13-44c9-8f81-961a6d1f36ac.jpg)

Now:
![T3gXASBBeE](https://user-images.githubusercontent.com/27288593/188829524-7f55945a-10a4-406b-a3fa-6dcd0e287f56.jpg)

### Expected Behavior

Log GitCommit or version

**Comment by jennyli-z** [comment]
![image](https://user-images.githubusercontent.com/93511422/188829844-544875d8-d000-4e10-8e0a-3e55f7a81af2.png)

**Comment by jennyli-z** [comment]
https://exerror.com/fatal-detected-dubious-ownership-in-repository/ new builder image has the issue to get git info
