### ISSUE TITLE
[Bug]: Primary key VARCHAR Exception

### ISSUE THREAD

**Issue by mazitovs** [milvus-io/milvus#19090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.1
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.1
- OS(Ubuntu or CentOS): ubuntu 22.04
- CPU/Memory: 20cpu, 64ram
- GPU: 8gb
- Others:
```

### Current Behavior

I am trying to create collection with VARCHAR pk, but get an exception MilvusException: <MilvusException: (code=1, message=the data type of primary key should be int64)>

### Expected Behavior

I would like to load string ids and float embeddings. I need string id to further search in db on it 

### Steps To Reproduce

```markdown
pk = FieldSchema(name=id_name, dtype=DataType.VARCHAR, is_primary=True, auto_id=False)
field = FieldSchema(name=field_name, dtype=DataType.FLOAT_VECTOR, dim=EMB_DIM)
schema = CollectionSchema(fields=[pk,field], description="2mln")
collection = Collection(name=table_name, schema=schema)
```
```


### Milvus Log

_No response_

### Anything else?

-

**Comment by mazitovs** [comment]
> ```
> pk = FieldSchema(name="str_id", dtype=DataType.VARCHAR, max_length=128,
>                      is_primary=True, auto_id=False)
>     field = FieldSchema(name="embedding", dtype=DataType.FLOAT_VECTOR, dim=256)
>     schema = CollectionSchema(fields=[pk, field], description="2mln")
>     collection = Collection(name="test2mln", schema=schema)
> ```

Hi! Thank you for reply
Does it works fine for you?
I still have an exception

```
error_code: UnexpectedError
reason: "the data type of primary key should be int64"

RPC error: [create_collection], <MilvusException: (code=1, message=the data type of primary key should be int64)>, <Time:{'RPC start': '2022-09-08 17:09:00.944635', 'RPC error': '2022-09-08 17:09:00.947871'}>
```

**Comment by yanliang567** [comment]
yes, it works for me. 
could you please double check the pymilvus version? @mazitovs

**Comment by briconnelly** [comment]
/reopen

I am using the Question Answering System tutorial from the Milvus site/github.  https://github.com/towhee-io/examples/tree/main/nlp/question_answering

I am getting the same error that this gentlemen was but I do have the max_length defined. 

Here is the error: MilvusException: <MilvusException: (code=1, message=the data type of primary key should be int64)>

Here is the code I am running in a Jupyter dash: 
`def create_milvus_collection(collection_name, dim):
    if utility.has_collection(collection_name):
        utility.drop_collection(collection_name)
    
    fields = [
    FieldSchema(name='id', dtype=DataType.VARCHAR, description='ids',  max_length=500,  is_primary=True, auto_id=False),
    FieldSchema(name='embedding', dtype=DataType.FLOAT_VECTOR, descrition='embedding vectors', dim=dim)
    ]
    schema = CollectionSchema(fields=fields, description='reverse image search')
    collection = Collection(name=collection_name, schema=schema)

    # create IVF_FLAT index for collection.
    index_params = {
        'metric_type':'L2',
        'index_type':"IVF_FLAT",
        'params':{"nlist":2048}
    }
    collection.create_index(field_name="embedding", index_params=index_params)
    return collection

collection = create_milvus_collection('question_answer', 768)`

I have ensured I have the latest pymilvus and all dependent packages that I have found are needed, but can't seem to get around this error.  Any help would be appreciated!

**Comment by gappelgren** [comment]
FieldSchema(name='id', dtype=DataType.INT64, descrition='ids', max_length=128, is_primary=True, auto_id=False),

from dtype=DataType.VARCHAR. to  dtype=DataType.INT64,
max_length=128

**Comment by yanliang567** [comment]
only VARCHAR type need max_length property.

**Comment by ForeverCm** [comment]
> only VARCHAR type need max_length property.

![image](https://github.com/milvus-io/milvus/assets/18618391/66146e17-250b-4775-81a8-471f0ecfc8c3)
How do I set max length

**Comment by Lin-plax** [comment]
> only VARCHAR type need max_length property.

And VARCHAR type MUST have a max_length.
