### ISSUE TITLE
[Bug]: certain VarChar can't be inserted 

### ISSUE THREAD

**Issue by pingren** [milvus-io/milvus#19115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.1.1
- Deployment mode: Standalone / Cluster (I tried both).
- SDK version: pymilvus2.1.1 (also tried @zilliz/milvus2-sdk-node@2.1.2 for Node.js)
- OS: 1.22.11-gke.400 on Google Cloud

It happens on deployments (Standalone or Cluster) by Helm on GKE. 
I can't reproduce on my local milvus by Docker Compose.
```

### Current Behavior

Inserting "ann-ounce" will work. However, if I insert anything string including "announce", the request will hang for a while and fail.

![CleanShot 2022-09-08 at 17 16 15](https://user-images.githubusercontent.com/5123601/189088121-147976c3-312a-482e-87d5-71c7cd07fc76.png)

### Steps To Reproduce

Python Script to reproduce:

```python
from pymilvus import CollectionSchema, FieldSchema, DataType, Collection, connections

connections.connect(
  alias="default", 
  host='PUT YOUR HOST HERE', 
  port='19530'
)
vector = FieldSchema(
  name="vector", 
  dtype=DataType.FLOAT_VECTOR, 
  dim=1
)
id = FieldSchema(
  name="id", 
  dtype=DataType.VARCHAR, 
  is_primary=True,
  max_length=64
)
varchar = FieldSchema(
  name="varchar", 
  dtype=DataType.VARCHAR,
  max_length=1024
)
schema = CollectionSchema(
  fields=[vector, id, varchar], 
  description="Test varchar insert"
)

collection = Collection(
    name="test_varchar", 
    schema=schema, 
    using='default', 
    shards_num=2,
)

data = [
  [[0.3]],
  ['test-id'],
  ['ann-ounce'],
]
mr = collection.insert(data)
print('insert VARCHAR ann-ounce ok', mr)

data = [
  [[0.3]],
  ['test-id2'],
  ['announce'],
]

mr = collection.insert(data)
print('insert VARCHAR announce ok', mr)
```

**Comment by yanliang567** [comment]
@jingkl  please help to reproduce it locally

**Comment by jingkl** [comment]
I used the Milvus 2.1.1 tag and the pymilvus==2.1.1 standalone service and executed the tests without errors.
The test results are as follows
<img width="1237" alt="截屏2022-09-08 21 54 40" src="https://user-images.githubusercontent.com/34296482/189140584-73ab1f4d-be21-4282-94e1-c23e50075735.png">

**Comment by yanliang567** [comment]
> I used the Milvus 2.1.1 tag and the pymilvus==2.1.1 standalone service and executed the tests without errors. The test results are as follows <img alt="截屏2022-09-08 21 54 40" width="1237" src="https://user-images.githubusercontent.com/34296482/189140584-73ab1f4d-be21-4282-94e1-c23e50075735.png">

any chance to retry on AWS and Google

**Comment by soothing-rain** [comment]
@pingren can you provide logs for Milvus server?

**Comment by pingren** [comment]
Yes. But my Milvus server is on production. I am too busy right now to set up a new environment. 

Hopefully I could reproduce the issue in a dev server and provide logs in holidays next weeks.

**Comment by pingren** [comment]
I can't reproduce this one on a new environment either. I will close the issue.

A few days ago, our production milvus encountered another issue, and search service down about 12 hours. Unfortunately, all metrics and status are "health" on K8s.

I have to decide to switched to [another vector search  solution](https://www.elastic.co/guide/en/elasticsearch/reference/current/knn-search.html) after all of these unexpected bugs.
