### ISSUE TITLE
[Bug]: [metrics] The number of segments in the Flushing state in the Meta of DataCoord is negative

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#19121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![BvPua0zF5S](https://user-images.githubusercontent.com/27288593/189116468-880965b7-29db-4840-8500-c6f86739e940.jpg)

### Expected Behavior

Flushing segments num >=0

**Comment by yanliang567** [comment]
keep it open

**Comment by ThreadDao** [comment]
@czs007 assign you again

**Comment by yanliang567** [comment]
@ThreadDao @czs007 is it still valid

**Comment by ThreadDao** [comment]
> @ThreadDao @czs007 is it still valid

probably. nobody fixed it

**Comment by yanliang567** [comment]
@czs007 any updates? @xige-16

**Comment by xiaofan-luan** [comment]
keep it

**Comment by xige-16** [comment]
The issue of incorrect segment num metrics no longer exists in the latest version of Milvus. @ThreadDao
