### ISSUE TITLE
[Bug]: Failed to connect milvus, after deleting a collection once

### ISSUE THREAD

**Issue by KajiMaCN** [milvus-io/milvus#19139]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

执行一次实体删除之后，出现报错：pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530. Timeout)>
更换端口等其他操作均未解决此ERROR。Attu客户端同样也无法连接。卸载重装、重启电脑均无法连接。

### Milvus Log

D:\Anaconda3\envs\MilvusLearn2\python.exe "D:/PyCharm Projects/MilvusLearn/main.py" 
2022-09-09 17:04:38.491308: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-09-09 17:04:38.491407: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-09-09 17:04:39.958225: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2022-09-09 17:04:39.958312: W tensorflow/stream_executor/cuda/cuda_driver.cc:263] failed call to cuInit: UNKNOWN ERROR (303)
2022-09-09 17:04:39.960586: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: HCBD-PC0103
2022-09-09 17:04:39.960694: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: HCBD-PC0103
2022-09-09 17:04:39.960910: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "D:\Anaconda3\envs\MilvusLearn2\lib\site-packages\pymilvus\client\grpc_handler.py", line 115, in _wait_for_channel_ready
    grpc.channel_ready_future(self._channel).result(timeout=3)
  File "D:\Anaconda3\envs\MilvusLearn2\lib\site-packages\grpc\_utilities.py", line 139, in result
    self._block(timeout)
  File "D:\Anaconda3\envs\MilvusLearn2\lib\site-packages\grpc\_utilities.py", line 85, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PyCharm Projects\MilvusLearn\main.py", line 123, in <module>
    create_table()
  File "D:\PyCharm Projects\MilvusLearn\main.py", line 26, in create_table
    connections.connect(host=host, port=port)
  File "D:\Anaconda3\envs\MilvusLearn2\lib\site-packages\pymilvus\orm\connections.py", line 262, in connect
    connect_milvus(**kwargs, password=password)
  File "D:\Anaconda3\envs\MilvusLearn2\lib\site-packages\pymilvus\orm\connections.py", line 233, in connect_milvus
    gh._wait_for_channel_ready()
  File "D:\Anaconda3\envs\MilvusLearn2\lib\site-packages\pymilvus\client\grpc_handler.py", line 118, in _wait_for_channel_ready
    raise MilvusException(Status.CONNECT_FAILED, f'Fail connecting to server on {self._address}. Timeout')
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19531. Timeout)>

Process finished with exit code 1

**Comment by yanliang567** [comment]
@KajiMaCN thank you for the issue. Which version did you run, also could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @KajiMaCN 
/unassign

**Comment by KajiMaCN** [comment]
After I deleted all the files from Milvus, I tried the same operation again with the same result, with the following message.

My code is as follows：
```
    for img in img_vectors:
        t2=time.time()
        img_id=search_data(img_vectors[0])
        t3=time.time()
        delete_data(img_id)
        print('time cost: {}'.format(time.time() - t2))
        print('time cost: {}'.format(time.time() - t3))
```

ERROR in pyCharm:
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530. Timeout)>

ERROR in attu:
![WZ 2G9IK)HZC8OD4D462LJ8](https://user-images.githubusercontent.com/28567261/189842796-12f67a84-df29-4cc4-994b-13f17a7e3be8.png)

and logs can be got from:
[https://drive.google.com/file/d/1GLnh_koXL86B8wk_62x-i7WvtnGEUgDa/view?usp=sharing](url)

**Comment by KajiMaCN** [comment]
> @KajiMaCN thank you for the issue. Which version did you run, also could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
> 
> /assign @KajiMaCN /unassign

After I deleted all the files from Milvus, I tried the same operation again with the same result, with the following message.

My code is as follows：

```
img_vectors = pd.read_csv('img_vector.csv', header=None).values[2:10]
for img in img_vectors:
    t2=time.time()
    img_id=search_data(img_vectors[0])
    t3=time.time()
    delete_data(img_id)
    print('time cost: {}'.format(time.time() - t2))
    print('time cost: {}'.format(time.time() - t3))
```

ERROR in pyCharm:
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530. Timeout)>

ERROR in attu:
![WZ 2G9IK)HZC8OD4D462LJ8](https://user-images.githubusercontent.com/28567261/189847134-52a51425-52eb-48d6-8ab1-2f06f60b97bf.png)

and logs can be got from:
[https://drive.google.com/file/d/1GLnh_koXL86B8wk_62x-i7WvtnGEUgDa/view?usp=sharing](url)

**Comment by KajiMaCN** [comment]
> @KajiMaCN looking into the logs, it seems that it failed in search operation with collection not loaded error: `�[32mmilvus-standalone |�[0m panic: insertNode processDeleteMessages failed, collectionID = 435959221490548737, err = partition 435959832902893569 hasn't been loaded or has been released, channel: by-dev-rootcoord-dml_3_435959221490548737v1` Also there is an panic issue which indicates that milvus crashed:
> 
> ```
> [32mmilvus-standalone |�[0m goroutine 689026 [running]:
> �[32mmilvus-standalone |�[0m github.com/milvus-io/milvus/internal/querynode.(*insertNode).Operate(0xc0022f07e0, 0xc003a5b060, 0x1, 0x1, 0x0, 0x0, 0x0)
> �[32mmilvus-standalone |�[0m 	/go/src/github.com/milvus-io/milvus/internal/querynode/flow_graph_insert_node.go:234 +0x3c45
> �[32mmilvus-standalone |�[0m github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc002d4a180)
> �[32mmilvus-standalone |�[0m 	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:102 +0x23b
> �[32mmilvus-standalone |�[0m created by github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start
> �[32mmilvus-standalone |�[0m 	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:70 +0x70
> ```
> 
> could you please retry on latest release 2.1.1 and again refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

In fact, this is the version log for 2.1.1, I just looked at it via docker, except that it is marked as 2.0.0 and 2.0.1 on the web page.

**Comment by KajiMaCN** [comment]
I tried the following code again, with only minor changes to the previous one, and the error message was updated.
Same version as above.
logs: https://drive.google.com/file/d/1Wb-mGYJ4FmORABiuv1P62Q3vNEiQlGbN/view?usp=sharing
```
def search_data(vectors):
    print('search')
    connections.connect(host=host, port=port)
    collection = Collection(name=field_name)
    print('连接成功')

    # 首次查询建立索引和load()
    # default_index = {"index_type": "FLAT", "params": {"nlist": 128}, "metric_type": "L2"}
    # print(f"\nCreate index...")
    # collection.create_index(field_name="feature", index_params=default_index)
    # print(print(f"\nCreate index...is OKOKOKOKOK"))
    # collection.load()
    # exit()

    # vectors = img2feature('1.jpg').tolist()[0]

    topK = 10
    search_params = {"metric_type": "L2", "params": {"nprobe": 10}}

    res = collection.search(
        [vectors],
        "feature",
        search_params,
        topK,
        "create_time > {}".format(0),
        output_fields=["milvus_id"]
    )
    print('>>>', res)
    in_id=[]
    for hits in res:
        print(len(hits))
        for hit in hits:
            print(hit)
            in_id.append(hit.id)
    print('查询结束')
    return in_id

def delete_data(index):
    default_schema = CollectionSchema(fields=default_fields, description="test collection")
    collection = Collection(name=field_name, schema=default_schema)
    partition = Partition(collection, collection.name, "")
    expr = f"milvus_id in {index}"
    partition.delete(expr)


img_vectors = pd.read_csv('img_vector.csv', header=None).values[0:5]
for img in img_vectors:
    t2=time.time()
    img_id=search_data(img)
    t3=time.time()
    delete_data(img_id)
    print('time cost: {}'.format(time.time() - t2))
    print('time cost: {}'.format(time.time() - t3))
```

**ERROR in pyCharm:**
[delete] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNAVAILABLE: WSA Error>
[delete] retry:5, cost: 0.81s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNAVAILABLE: WSA Error>
[delete] retry:6, cost: 2.43s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNAVAILABLE: WSA Error>
[delete] retry:7, cost: 7.290000000000001s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNAVAILABLE: WSA Error>
[delete] retry:8, cost: 21.870000000000005s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNAVAILABLE: WSA Error>
[delete] retry:9, cost: 60s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNAVAILABLE: WSA Error>
[delete] retry:10, cost: 60s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNAVAILABLE: WSA Error>
RPC error: [delete], <MilvusUnavaliableException: (code=1, message=server unavaliable: Retry run out of 10 retry times)>, <Time:{'RPC start': '2022-09-13 17:33:22.077987', 'RPC error': '2022-09-13 17:36:01.849741'}>
Traceback (most recent call last):
  File "D:\Anaconda3\envs\MilvusLearn2\lib\site-packages\pymilvus\decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "D:\Anaconda3\envs\MilvusLearn2\lib\site-packages\pymilvus\client\grpc_handler.py", line 378, in delete
    raise err
  File "D:\Anaconda3\envs\MilvusLearn2\lib\site-packages\pymilvus\client\grpc_handler.py", line 368, in delete
    response = future.result()
  File "D:\Anaconda3\envs\MilvusLearn2\lib\site-packages\grpc\_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNAVAILABLE: WSA Error"
	debug_error_string = "UNKNOWN:Failed to pick subchannel {created_time:"2022-09-13T09:36:01.849991849+00:00", children:[UNKNOWN:failed to connect to all addresses; last error: UNAVAILABLE: WSA Error {grpc_status:14, created_time:"2022-09-13T09:36:01.849984512+00:00"}]}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PyCharm Projects\MilvusLearn\table.py", line 134, in <module>
    delete_data(img_id)
  File "D:\PyCharm Projects\MilvusLearn\table.py", line 115, in delete_data
    partition.delete(expr)
  File "D:\Anaconda3\envs\MilvusLearn2\lib\site-packages\pymilvus\orm\partition.py", line 332, in delete
    res = conn.delete(self._collection.name, expr, self.name, timeout=timeout, **kwargs)
  File "D:\Anaconda3\envs\MilvusLearn2\lib\site-packages\pymilvus\decorators.py", line 96, in handler
    raise e
  File "D:\Anaconda3\envs\MilvusLearn2\lib\site-packages\pymilvus\decorators.py", line 92, in handler
    return func(*args, **kwargs)
  File "D:\Anaconda3\envs\MilvusLearn2\lib\site-packages\pymilvus\decorators.py", line 64, in handler
    raise MilvusUnavaliableException(Status.UNEXPECTED_ERROR, f"server unavaliable: {timeout_msg}")
pymilvus.exceptions.MilvusUnavaliableException: <MilvusUnavaliableException: (code=1, message=server unavaliable: Retry run out of 10 retry times)>

Process finished with exit code 1
