### ISSUE TITLE
[Bug]: rpc error: code = Canceled desc = grpc: the client connection is closing

### ISSUE THREAD

**Issue by cjh6666688888** [milvus-io/milvus#19151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:milvus:v2.1.0
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):milvus-sdk-go/v2 v2.1.2-0.20220823032848-8832edc6f96e
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

This exception occurs when a large number of concurrent accesses are made to the cluster, "The Client connection is closing".
Cluster logs are normal, but no exception logs exist.It can be accessed normally using the Python SDK.

### Steps To Reproduce

```markdown
1.If 100 threads are used to access the cluster, an access exception will occur when you delete or query the cluster.rpc error: code = Canceled desc = grpc: the client connection is closing.
```

### Milvus Log

The cluster has no exception log. Procedure,The request should not go to the cluster and the GO SDK directly accesses the exception information

**Comment by yanliang567** [comment]
@czs007 sounds like an sdk issue, could you please help to confirm that?
/assign @czs007 
/unassign
