### ISSUE TITLE
[Bug]: package mq/msgstream test case TestStream_KafkaTtMsgStream_2 fails sometimes

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#19192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

[log](https://github.com/milvus-io/milvus/actions/runs/3042685336/jobs/4901116567): line 67957

**Comment by xiaofan-luan** [comment]
we will ban all kafka related test cases for now.

We will also see some cases kafka can not recover but pulsar is ok, still investigate on it.
