### ISSUE TITLE
[Bug]: DataNode can't recovery from oom.

### ISSUE THREAD

**Issue by dzqoo** [milvus-io/milvus#19190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.0
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: dataNode config:1c4g
- GPU: 
- Others:
```

### Current Behavior

When I insert data into milvus by 13w  per batch, dataNode crashed by oomkill and can't recovery.
Here is my dataNode logs:
[datanode.log](https://github.com/milvus-io/milvus/files/9562091/datanode.log)
[datanode1.log](https://github.com/milvus-io/milvus/files/9562092/datanode1.log)

**Comment by yanliang567** [comment]
the shard_num was set to 1, and it oom with insert workload described above.
[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/9563051/milvus-log.tar.gz)

/assign @soothing-rain 
/unassign

**Comment by soothing-rain** [comment]
Hey @dzqoo , with a DataNode of size 1c4g and with # of shards = 1, it is high possible that inserting with 130k per batch could congest DataNode.

I'd suggest try one of the things below to resolve this issue:
1. Add more resource to your DataNode
2. Decrease the # of records per insert batch. (Or wait until v2.2 for our new bulk load feature).
3. Change # of shards back to 2.

/unassign
/assign @dzqoo

**Comment by dzqoo** [comment]
> 

get.Thank for applyin.
