### ISSUE TITLE
[Bug]: CreateIndex hangs forever while compacting segments

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#19208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

If segments are compacted while creating index for collection, IndexCoord marks the compacted segments as deleted, but not to update the index states, leaves these segments' index states InProgress or Unissued forever.

**Comment by congqixia** [comment]
#19163 shall fix this problem for master branch.
Do we have any fix for 2.1 branc

**Comment by yanliang567** [comment]
> #19163 shall fix this problem for master branch. Do we have any fix for 2.1 branch

Xiaocai said that it could  be a different issue for 2.1 branch.
@xiaocai2333 could u please take a look at this issue?

**Comment by congqixia** [comment]
@xiaocai2333 @yanliang567 re-confirmed the log for #19042, this problem shall happen in the build manually on master. 2.1 branch shall be fine.

**Comment by xiaocai2333** [comment]
verify it. @yah01 @yanliang567

**Comment by yah01** [comment]
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-19392/1/pipeline/
@xiaocai2333 reproduced in master e2e

**Comment by xiaocai2333** [comment]
Not completely stuck, but doubled the time to build the index when a compaction occurs.
