### ISSUE TITLE
[Feature]: Add policy to seal long time idle segment

### ISSUE THREAD

**Issue by longjiquan** [milvus-io/milvus#19221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

If users insert entities into segment continuously within a certain period of time, but they forgot to flush/(seal) it and the size of segment didn't reach the seal proportion. Under this situation, Milvus will wait these segments to be expired and during this period search latency may be a little high. We can assume that entities won't be inserted into this segment anymore, so sealLongTimeIdlePolicy will seal these segments to trigger handoff of query cluster.

**Comment by xiaofan-luan** [comment]
/assign @yanliang567 
pls help on verifying the new policy

**Comment by yanliang567** [comment]
released on 2.2.0
