### ISSUE TITLE
[Bug]: task queue is full

### ISSUE THREAD

**Issue by Mask-Z** [milvus-io/milvus#19226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.1.0
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): milvus-sdk-java  2.1.0-beta4
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 40/252G
- GPU: 
- Others:
```

### Current Behavior

When i use `milvusClient` do insert, response return the message:

`task queue is full`

### Steps To Reproduce

```markdown
1. Execute the code(Each batch contains up to 1500 pieces of data):
 InsertParam insertParam = InsertParam.newBuilder()
                        .withCollectionName(key)
                        .withFields(value)
                        .build();
 R<MutationResult> insert = milvusClient.insert(insertParam);
```

### Anything else?

`When I saw this error, I closed the write process, and the next day I turned the write process back on, and the data was successfully written again without any code changes`

**Comment by sunby** [comment]
@Mask-Z Thanks for the feedback.
How many threads did you open to do insertion concurrently?
And It will be very helpful if you can provide the proxy log.
