### ISSUE TITLE
Support string id

### ISSUE THREAD

**Issue by chenqingguo** [milvus-io/milvus#1924]
The id only support int,which limit our using.

**Comment by JinHai-CN** [comment]
The feature is planned, please check: https://github.com/milvus-io/milvus/projects

**Comment by qbzenker** [comment]
+1 for this feature!

**Comment by bariqi** [comment]
hope this feature will be released soon

**Comment by luoy2** [comment]
+1 for this feature

**Comment by yangj2133** [comment]
> The id only support int,which limit our using.

I also encountered this problem, how did you solve it?

**Comment by sahuang** [comment]
@chenqingguo @qbzenker @bariqi @luoy2 @yangj2133 

This feature is currently in our plan and we are designing it. The documentation is listed here: https://docs.google.com/document/d/13YiSVMj29t_8tObRii1gTl_43LEIcutPV7ky_qCRSxs/edit?usp=sharing

Feel free to make any comments or suggestions.

**Comment by moyu505** [comment]
+1 for this feature!

**Comment by cocodee** [comment]
Is there any new progress for this issue?

**Comment by yhmo** [comment]
> Is there any new progress for this issue?

This feature will not be implemented in current version 0.10.x. We are rebuild milvus by new architect, new language. The main target is to make it more cloud-native. The related requirements will be considered in the new milvus, and will be developed until the main functions of new milvus are finished.

**Comment by cocodee** [comment]
> > Is there any new progress for this issue?
> 
> This feature will not be implemented in current version 0.10.x. We are rebuild milvus by new architect, new language. The main target is to make it more cloud-native. The related requirements will be considered in the new milvus, and will be developed until the main functions of new milvus are finished.

Could you please elaborate on the refactor of milvus? What's the new language?Are there any design docs?

**Comment by yhmo** [comment]
> > > Is there any new progress for this issue?
> > 
> > 
> > This feature will not be implemented in current version 0.10.x. We are rebuild milvus by new architect, new language. The main target is to make it more cloud-native. The related requirements will be considered in the new milvus, and will be developed until the main functions of new milvus are finished.
> 
> Could you please elaborate on the refactor of milvus? What's the new language?Are there any design docs?

We use golang to rewrite a distributed milvus. The old version 0.10.x will be marked as v1.0(and we will continue maintain it), and the master branch will be used for new milvus source code. We are preparing the articles/documentations/sourcecode, we hope publish them in a couple of weeks.

**Comment by suvashishtha** [comment]
+1

**Comment by batara666** [comment]
please

**Comment by hadim** [comment]
Are string fields now supported in Milvus 2.0? Especially, string fields as primary key.

**Comment by codenoid** [comment]
@hadim 

![](https://pbs.twimg.com/media/E6_0i1AXIAMkq__?format=jpg&name=medium)

https://twitter.com/milvusio/status/1418621288206249986/photo/1

**Comment by yhmo** [comment]
This feature is in progress in v2.0: 
https://wiki.lfaidata.foundation/display/MIL/MEP+11+--+Support+String+DataType

**Comment by yhmo** [comment]
Duplicate with #4430, close this one, tracked by #4430
