### ISSUE TITLE
[Bug]: Segments Search in one queryNode is serial and  time cost of "reduce search result" is high.

### ISSUE THREAD

**Issue by dzqoo** [milvus-io/milvus#19253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.1 
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 4C16G
- GPU: 
- Others:
```

### Current Behavior

When I search 128 dimension of 1kw vectors by 5 concurrent_num and 150 topk, I got 200ms rt. 
I got the following querynode logs and find that segment search is in one querynode is serial  and time cost of "reduce search result" is really high,which is 134ms in my case.

- Here is the serial segments query:
![3b4dfb266eec7c5ec9e17ba25c176af](https://user-images.githubusercontent.com/8862305/190608907-7720bbd3-e305-4440-b3fb-2916a75abc72.jpg)

- Here is the high cost of "reduce search result" 
![41ac97d6ecc16903eeb525475393243](https://user-images.githubusercontent.com/8862305/190608826-f5533b35-3d92-4452-b03c-aceeefd74d06.jpg)

### Expected Behavior

1. segments search in one querynode should be paralleling
2.  "reduce search result" in one querynode should be low.

**Comment by dzqoo** [comment]
Here is the metrics:
![4e0b6b08f16eb133e196cd266bd07ff](https://user-images.githubusercontent.com/8862305/190612207-31742dbc-f02e-4860-a621-45b06d4b1dd0.jpg)
![1e938965777ad79dc504d3effe84639](https://user-images.githubusercontent.com/8862305/190612278-5229cd2e-d679-4624-addf-a5bdac2c6ebf.jpg)

**Comment by dzqoo** [comment]
Here is all the metric log:
[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/9582914/milvus-log.tar.gz)

**Comment by bigsheeper** [comment]
Hello, @dzqoo reduce spent a lots of time to `purge memory`,  and `purgeMemory` would be removed in 2.1.3.  Please have a try after 2.1.3 releasing.

**Comment by dzqoo** [comment]
> Hello, @dzqoo reduce spent a lots of time to `purge memory`, and `purgeMemory` would be removed in 2.1.3. Please have a try after 2.1.3 releasing.
@bigsheeper 
Got it! When does 2.1.3 release?

**Comment by bigsheeper** [comment]
> > Hello, @dzqoo reduce spent a lots of time to `purge memory`, and `purgeMemory` would be removed in 2.1.3. Please have a try after 2.1.3 releasing.
> > @bigsheeper
> > Got it! When does 2.1.3 release?

@dzqoo It should be this week.

**Comment by bigsheeper** [comment]
@dzqoo Hi, the v2.1.4 has been released. :)

**Comment by dzqoo** [comment]
@bigsheeper get it!
