### ISSUE TITLE
To flush all collections, flush() doesn't work

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#1925]
**Describe the bug**
To flush all collections, flush() doesn't work

**Steps/Code to reproduce behavior**
1. set auto_flush_interval = 100 in server_config.yaml
2. start milvus server
3. create a collection
4. insert some vectors
5. call flush() api

result:
Milvus didn't persist data into disk.

6. call flush(collection_name_array=[TABLE_NAME])
result:
vector data persist into disk

Neither work for python sdk and C++ sdk

**Expected**
1. call flush(collection_name_array=[TABLE_NAME]) to flush a single collection
2. call flush() to flush all collections in milvus

**Comment by yhmo** [comment]
Fixed by pr1935

**Comment by tinkerlin** [comment]
@del-zhenwu regression test

**Comment by del-zhenwu** [comment]
java-sdk should add a method, `flush()` with no params.

**Comment by sahuang** [comment]
Server side will deal with flush().  pr1935 has not been merged yet.

**Comment by yhmo** [comment]
fixed by pr2257

**Comment by tinkerlin** [comment]
@del-zhenwu regression test

**Comment by del-zhenwu** [comment]
fixed and close
