### ISSUE TITLE
[Enhancement]: replace github.com/tecbot/gorocksdb with cockroachdb/pebble

### ISSUE THREAD

**Issue by ben1009** [milvus-io/milvus#19276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

seems duplicated with https://github.com/milvus-io/milvus/issues/16957, saw actions been taken but somehow paused, may i ask what the thought behind, thanks

**Comment by jiaoew1991** [comment]
Hi @ben1009, I have tried to work on #16957 on May and June, the pull request is nearly complete. Later, due to priority reasons, there is no advance for the time being, if you are interested you can try to complete it 😊
