### ISSUE TITLE
[Bug]: search and install one docment  use 400ms

### ISSUE THREAD

**Issue by SuperLiChen** [milvus-io/milvus#19297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:  2.1.1
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): java-sdk-beta-4
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 64GB
- GPU: 
- Others:
```

### Current Behavior

collection base have 80W  512 dim data

Consistency Level  is use  default.

search and  insert  approximately use 400ms.

### Milvus Log

[milvus.tar.gz](https://github.com/milvus-io/milvus/files/9606490/milvus.tar.gz)

**Comment by yanliang567** [comment]
@SuperLiChen thank you for the issue, quick questions:
1. how do you measure the time cost?
2. do you have any metrics for reference?
In the attached log ,it seems that search done in less ms
```
milvus-proxy        | [2022/09/20 09:56:28.153 +00:00] [DEBUG] [proxy/task_search.go:341] ["Search Execute done."] [msgID=436120523266064462]
milvus-querynode    | [2022/09/20 09:56:28.248 +00:00] [DEBUG] [querynode/result.go:40] ["shard leader get valid search results"] [numbers=0]
milvus-proxy        | [2022/09/20 09:56:28.153 +00:00] [DEBUG] [timerecord/time_recorder.go:78] ["proxy execute search 436120523266064462: done (25ms)"]
```

**Comment by SuperLiChen** [comment]
1.  I cost time by  java sdk search function start and return time interval
 
2.  do you have any metrics for reference?  80W data in cluster_5a9931a7ad951999e787f9f4cee7bac6_2022_09,  total 15 thread to search  milvua, Five of them to search  cluster_5a9931a7ad951999e787f9f4cee7bac6_2022_09
 
3.  I have  the same time search on six  collections ,  collection  `cluster_5a9931a7ad951999e787f9f4cee7bac6_2022_09`  hava more  data need cost more time
```
| [2022/09/20 09:56:28.203 +00:00] [DEBUG] [proxy/task_search.go:341] ["Search Execute done."] [msgID=436120523266064461]
| [2022/09/20 09:56:28.203 +00:00] [DEBUG] [timerecord/time_recorder.go:78] ["proxy execute search 436120523266064458: done (121ms)"]
```

**Comment by yanliang567** [comment]
it seems that it costs more time in waiting:
```
milvus-proxy        | [2022/09/20 09:56:28.201 +00:00] [DEBUG] [timerecord/time_recorder.go:78] ["Search: wait search result (169ms)"]
milvus-proxy        | [2022/09/20 09:56:28.201 +00:00] [DEBUG] [proxy/impl.go:2518] ["Search done"] [traceID=2e93faa3bbb0eec4] [role=proxy] [msgID=436120523266064454] [db=] [collection=cluster_5a9931a7ad951999e787f9f4cee7bac6_2022_09] [partitions="[]"] [dsl="location == \"_default\""] [len(PlaceholderGroup)=2060] [OutputFields="[]"] [search_params="[{\"key\":\"anns_field\",\"value\":\"feature\"},{\"key\":\"topk\",\"value\":\"1\"},{\"key\":\"metric_type\",\"value\":\"IP\"},{\"key\":\"round_decimal\",\"value\":\"-1\"},{\"key\":\"params\",\"value\":\"{\\\"ef\\\": 4}\"}]"] [travel_timestamp=0] [guarantee_timestamp=1]
```
how much CPU do you configure for Milvus? are they running in 100%?, if yes, please try to add more cpu

**Comment by yanliang567** [comment]
@SuperLiChen any updates? do you have any screenshots of metrics in grafana
