### ISSUE TITLE
[Bug]: HNSW created bug

### ISSUE THREAD

**Issue by kkpssr** [milvus-io/milvus#19303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

After I drop IVF_FLAT index and create HNSW index, HNSW index is not work.  index_params is {'metric_type': 'IP', 'index_type': 'HNSW', 'params': {'M': 32, 'efConstruction': 256}} and search_params is {"metric_type":"IP","params":{"ef":1000}}, it show search_param err,and i change ef to nprobe , it works but return distance is larger than 1 like L2 distance not IP distance but order descend like IP distance. Then i just delete all index and search again, i find results are same and still requires nprobe parmas, it seems like IVF index is not delete yet(because the result of collection.indexes is [] so i am not sure what the index_type is and why database think it still exists index which need nprobe param) and still exists in milvus  and I can not delete it by collection.drop_indexes.

**Comment by yanliang567** [comment]
/assign @binbinlv 
coud you please try to reproduce this issue?

/unassign

**Comment by binbinlv** [comment]
> /assign @binbinlv coud you please try to reproduce this issue?
> 
> /unassign

OK，working.

**Comment by kkpssr** [comment]
> > /assign @binbinlv coud you please try to reproduce this issue?
> > /unassign
> 
> OK，working.

hi, i update milvus to 2.1.2 and search_params {"metric_type":"IP","params":{"ef":1000}} is work but results are not change. the distance is very large from 10 to 200+,but my search metric is IP

**Comment by binbinlv** [comment]
> > > /assign @binbinlv coud you please try to reproduce this issue?
> > > /unassign
> > 
> > 
> > OK，working.
> 
> hi, i update milvus to 2.1.2 and search_params {"metric_type":"IP","params":{"ef":1000}} is work but results are not change. the distance is very large from 10 to 200+,but my search metric is IP

Hello, I have reproduced the 2 problems you mentioned in this issue:
(1) for problem 1: search error after drop index and create another different index: 
I reproduced your issue, it reports error "Param 'nprobe' not exist err" in the following script: (drop one index, and create another index, and search, if will fail):
```python
index_param = {"index_type": "IVF_FLAT", "metric_type": "IP", "params": {"nlist": 100}}
    collection.create_index("float_vector", index_param)
    collection.load()
    print("start searching %d" % i)
    nq = 2
    limit = 50
    default_search_params = {"metric_type": "IP", "params": {"nprobe": 10}}
    res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
    print(res[0].ids)
    print("start drop index %d" % i)
    collection.drop_index()
    index_param = {"index_type": "HNSW", "metric_type": "IP", "params": {'M': 32, 'efConstruction': 256}}
    collection.create_index("float_vector", index_param)
    collection.load()
    print("start searching %d after change index" % i)
    default_search_params = {"metric_type": "IP", "params": {"ef":1000}}
    res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
    print(res[0].ids)
    print(res[0].distances)
```

But we suggest release collection first if you want to load another index, so it is good when add **collection.release** after drop_index:
```
index_param = {"index_type": "IVF_FLAT", "metric_type": "IP", "params": {"nlist": 100}}
    collection.create_index("float_vector", index_param)
    collection.load()
    print("start searching %d" % i)
    nq = 2
    limit = 50
    default_search_params = {"metric_type": "IP", "params": {"nprobe": 10}}
    res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
    print(res[0].ids)
    print("start drop index %d" % i)
    collection.drop_index()
    **collection.release()**
    index_param = {"index_type": "HNSW", "metric_type": "IP", "params": {'M': 32, 'efConstruction': 256}}
    collection.create_index("float_vector", index_param)
    collection.load()
    print("start searching %d after change index" % i)
    default_search_params = {"metric_type": "IP", "params": {"ef":1000}}
    res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
    print(res[0].ids)
    print(res[0].distances)
```

(2) for problem 2:  the distance is larger than 1:
it may be that you did not normalize the vector, please refer the comments in #18265

**Comment by yanliang567** [comment]
/assign @xiaofan-luan 
I think we shall improve it smarter: e.g. release the index automatically after the index dropped.

**Comment by kkpssr** [comment]
thanks very much
I have try the operation u mentioned and problems are solved and, if  milvus can offer normalize function like faiss  or auto normalize when use IP metric in the future, i think will be more convenient to use..

**Comment by kkpssr** [comment]
> @kkpssr so could you please try the two points I mentioned above? Thanks. /assign @kkpssr

by the way, i use IVF_SQ8 index before and also search in IP and results returned is right, all similarity is below 1. So, the vectors I use in IVF_SQ8 index and HNSW index are same which are not normalized before. why results are different?

**Comment by kkpssr** [comment]
> @kkpssr so could you please try the two points I mentioned above? Thanks. /assign @kkpssr

thanks very much
I have try the operation u mentioned and problems are solved and, if milvus can offer normalize function like faiss or auto normalize when use IP metric in the future, i think will be more convenient to use..
