### ISSUE TITLE
[Bug]: Hard disk hibernation

### ISSUE THREAD

**Issue by suforme** [milvus-io/milvus#19315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Hard disk hibernation will cause docker to crash

**Comment by yanliang567** [comment]
@suforme thank you for the issue.  Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @suforme

**Comment by soothing-rain** [comment]
That's kinda expected. Is there any special reason your hard disk go hibernate once and a while in your production environment?
