### ISSUE TITLE
[Bug]: Milvus Standalone not robust at batch insert operation

### ISSUE THREAD

**Issue by Leslie-Wong-H** [milvus-io/milvus#19327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.2
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): @zilliz/milvus2-sdk-node 2.1.2
- OS(Ubuntu or CentOS): Ubuntu 20.04
- CPU/Memory: DigitalOcean 2C2G
- GPU: 
- Others:
```

### Current Behavior

Try to adopt milvus-standalone-docker-compose.yml to my current trace.moe compose file to test at a DigitalOcean 2c2g VM. This is the polished compose file, [link.](https://github.com/Leslie-Wong-H/trace.moe/blob/master/docker-compose.yml) 

The number of vector data is around 3 million. However, the insert process does not work performantly. The insert approach I take is to insert at a batch of 10,000 each time and pause for 500ms. Yet occasionally "Connection dropped" error happened and milvus-standalone restarted and might manage to continue the insert process. Sadly, the insert process would eventually fail, with the milvus-standalone error from "Connection dropped" to "proxy not healthy". The same scenario happened when changed from 10,000 to 1,000. 

Here is the loader code, [link](https://github.com/Leslie-Wong-H/trace.moe-worker/blob/master/loader.js#L170)

![de54d0c0329fa12d03095f8c074a383](https://user-images.githubusercontent.com/27696701/191432469-e14d82e8-5454-4d86-824d-7d4dd622f0d1.jpg)

![4c5bcbe4bc26af2a056218afdce29c6](https://user-images.githubusercontent.com/27696701/191432678-1d34f148-fa16-489b-aac4-82b435d27daa.jpg)

![6255a5c963b120e2a425e4d04f70fda](https://user-images.githubusercontent.com/27696701/191432767-d0ac971e-6367-4ed2-b151-4cc65a90d53d.jpg)

### Expected Behavior

Milvus standalone could perform robustly and smoothly at batch insert operation.  

### Steps To Reproduce

```markdown
DigitalOcean 2C2G Ubuntu 20.04

prepare liresolr hash files at /home/soruly/trace.moe-hash

Use this docker compose file [link](https://github.com/Leslie-Wong-H/trace.moe/blob/master/docker-compose.yml)

docker-compose up -d

docker logs -f -n 100 tracemoe_loader_1
```

### Milvus Log

[xshF040.tmp.txt](https://github.com/milvus-io/milvus/files/9613734/xshF040.tmp.txt)

### Anything else?

https://groups.google.com/g/grpc-io/c/xTJ8pUe9F_E

**Comment by yanliang567** [comment]
@Leslie-Wong-H thank you for the issue.
Looking into the log, I find the rootcoord lost connection to etcd, which causes milvus stop working. Could you please try
1. expand the VM to 4C8G or even bigger
2. make sure the etcd is using SSD volume
Check more prerequisite for installation here: https://milvus.io/docs/v2.1.x/prerequisite-docker.md

/assign @Leslie-Wong-H 
/unassign

**Comment by Leslie-Wong-H** [comment]
It works at a 4C16G VM.
