### ISSUE TITLE
QPS decreased

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#1932]
**Describe the bug**
```
0.8.0
==
single connection

 Name                                                          # reqs      # fails     Avg     Min     Max  |  Median   req/s failures/s
--------------------------------------------------------------------------------------------------------------------------------------------
 grpc milvus_search                                             92825     0(0.00%)     108       4     205  |     110  753.31    0.00
--------------------------------------------------------------------------------------------------------------------------------------------
 Aggregated                                                     92825     0(0.00%)     108       4     205  |     110  753.31    0.00

Percentage of the requests completed within given times
 Type                 Name                                                           # reqs    50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100%
------------------------------------------------------------------------------------------------------------------------------------------------------
 grpc                 milvus_search                                                   92825    110    120    120    120    130    160    170    170    180    200    200
------------------------------------------------------------------------------------------------------------------------------------------------------
 None                 Aggregated                                                      92825    110    120    120    120    130    160    170    170    180    200    200



0.7.1
==
single connection
 Name                                                          # reqs      # fails     Avg     Min     Max  |  Median   req/s failures/s
--------------------------------------------------------------------------------------------------------------------------------------------
 grpc milvus_search                                            128492     0(0.00%)      76       4     184  |      78 1047.00    0.00
--------------------------------------------------------------------------------------------------------------------------------------------
 Aggregated                                                    128492     0(0.00%)      76       4     184  |      78 1047.00    0.00

Percentage of the requests completed within given times
 Type                 Name                                                           # reqs    50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100%
------------------------------------------------------------------------------------------------------------------------------------------------------
 grpc                 milvus_search                                                  128492     78     80     82     84    100    110    120    120    170    180    180
------------------------------------------------------------------------------------------------------------------------------------------------------
 None                 Aggregated                                                     128492     78     80     82     84    100    110    120    120    170    180    180
```

**Steps/Code to reproduce behavior**
search based on `sift-1m` with `ivf_sq8` index created
search params: `nq:1, top-k: 10, nprobe:16`
search with single milvus connection 
search with 100-clients, and test last for 2mins

using pymilvus-sdk

**Expected behavior**

**Environment details**
using default server config, gpu-version
search logs can be available on `eros` containers: 19530(server version 0.7.1)/19531(server version 0.8.0)
**Screenshots**

**Additional context**

**Comment by del-zhenwu** [comment]
```
 Name                                                          # reqs      # fails     Avg     Min     Max  |  Median   req/s failures/s
--------------------------------------------------------------------------------------------------------------------------------------------
 grpc milvus_search                                              2339     0(0.00%)     676      15    1071  |     840  106.80    0.00
--------------------------------------------------------------------------------------------------------------------------------------------
 Aggregated                                                      2339     0(0.00%)     676      15    1071  |     840  106.80    0.00

```

**Comment by yhmo** [comment]
Use C++ sdk_qps to compare 0.9.0 and 0.8.0:
dataset: 1M vectors, 128 dimensions, IVFSQ8
search parameters: nq = 1, topk = 10, nprobe = 16
0.8.0 qps: 1200+
0.9.0 qps: 3000+

**Comment by yhmo** [comment]
QPS decreased between 0.8.0 and 0.7.1, the reason is: to ensure data consistence, we add some locks in meta system

QPS decreased between 0.9.0 and 0.8.0, the reason is: in 0.9.0, to fix #2216, we rewrite file merge strategy to reduce hard disk cost during inserting, after insert, some small files may not be merged, and create index operation will build index for them respectively. 

Fixed by pr2372,  force merge files before build index operation

**Comment by del-zhenwu** [comment]
comparing with the older version, the fixed version still got a low qps result.
```
	 Name                                                          # reqs      # fails     Avg     Min     Max  |  Median   req/s failures/s
	--------------------------------------------------------------------------------------------------------------------------------------------
	 grpc milvus_search                                             20948     0(0.00%)     529       3     622  |     570  172.61    0.00
	--------------------------------------------------------------------------------------------------------------------------------------------
	 Aggregated                                                     20948     0(0.00%)     529       3     622  |     570  172.61    0.00

	Percentage of the requests completed within given times
	 Type                 Name                                                           # reqs    50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100%
	------------------------------------------------------------------------------------------------------------------------------------------------------
	 grpc                 milvus_search                                                   20948    570    580    580    580    590    600    600    600    610    620    620
	------------------------------------------------------------------------------------------------------------------------------------------------------
	 None                 Aggregated                                                      20948    570    580    580    580    590    600    600    600    610    620    620
```

**Comment by tinkerlin** [comment]
@BossZou may be sdk problem

**Comment by yhmo** [comment]
Use C++SDK example sdk_qps test, qps is 1000+:

Client start...
Create collection C_2020_6_11_11_10_1
Insert 100000 entities No.0 begin...
Insert 100000 entities No.0 totally cost: 648 ms
Insert 100000 entities No.1 begin...
Insert 100000 entities No.1 totally cost: 458 ms
Insert 100000 entities No.2 begin...
Insert 100000 entities No.2 totally cost: 544 ms
Insert 100000 entities No.3 begin...
Insert 100000 entities No.3 totally cost: 471 ms
Insert 100000 entities No.4 begin...
Insert 100000 entities No.4 totally cost: 475 ms
Insert 100000 entities No.5 begin...
Insert 100000 entities No.5 totally cost: 532 ms
Insert 100000 entities No.6 begin...
Insert 100000 entities No.6 totally cost: 424 ms
Insert 100000 entities No.7 begin...
Insert 100000 entities No.7 totally cost: 880 ms
Insert 100000 entities No.8 begin...
Insert 100000 entities No.8 totally cost: 447 ms
Insert 100000 entities No.9 begin...
Insert 100000 entities No.9 totally cost: 434 ms
Create index IVFSQ8 begin...
===========================================
Index collection name: C_2020_6_11_11_10_1
Index type: IVFSQ8
Index extra_params: {"nlist":16384}
===========================================
Create index IVFSQ8 totally cost: 306987 ms
Load table C_2020_6_11_11_10_1 begin...
Load table C_2020_6_11_11_10_1 totally cost: 222 ms
Searching C_2020_6_11_11_10_1 begin...
Searching C_2020_6_11_11_10_1 totally cost: 918 ms
TPS = 1085 	QPS = 1085

**Comment by yhmo** [comment]
same parameters
0.8.0 cpu version:

Client start...
Create collection C_2020_6_11_12_3_24
Insert 100000 entities No.0 begin...
Insert 100000 entities No.0 totally cost: 689 ms
Insert 100000 entities No.1 begin...
Insert 100000 entities No.1 totally cost: 551 ms
Insert 100000 entities No.2 begin...
Insert 100000 entities No.2 totally cost: 960 ms
Insert 100000 entities No.3 begin...
Insert 100000 entities No.3 totally cost: 855 ms
Insert 100000 entities No.4 begin...
Insert 100000 entities No.4 totally cost: 825 ms
Insert 100000 entities No.5 begin...
Insert 100000 entities No.5 totally cost: 953 ms
Insert 100000 entities No.6 begin...
Insert 100000 entities No.6 totally cost: 894 ms
Insert 100000 entities No.7 begin...
Insert 100000 entities No.7 totally cost: 1062 ms
Insert 100000 entities No.8 begin...
Insert 100000 entities No.8 totally cost: 1248 ms
Insert 100000 entities No.9 begin...
Insert 100000 entities No.9 totally cost: 1507 ms
Create index IVFSQ8 begin...
===========================================
Index collection name: C_2020_6_11_12_3_24
Index type: IVFSQ8
Index extra_params: {"nlist":16384}
===========================================
Create index IVFSQ8 totally cost: 1252639 ms
Preload table C_2020_6_11_12_3_24 begin...
Preload table C_2020_6_11_12_3_24 totally cost: 259 ms
Searching C_2020_6_11_12_3_24 begin...
Searching C_2020_6_11_12_3_24 totally cost: 980 ms
TPS = 1018 	QPS = 1018
