### ISSUE TITLE
[Bug]: test_search_index_partitions_fuzzy has logic error

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#19374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: cfd01a1
- Deployment mode(standalone or cluster): both
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

test_search_index_partitions_fuzzy case create index with nlist=128 and search with nprobe=16, may cause result cannot return (limit=1000) results

### Expected Behavior

case has determined result

**Comment by binbinlv** [comment]
Thanks for the issue, working.
