### ISSUE TITLE
[Bug]: Ver. 2.1.2 Search resulted in wrong distance values and strange orders

### ISSUE THREAD

**Issue by DoliteMatheo** [milvus-io/milvus#19407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.2
- Deployment standalone
- SDK version(e.g. pymilvus v2.1.1 or v2.1.2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I searched with inner product metric, I got wrong (negative) distance results and listed in wrong order, as shown in the following codes.
Furthermore, I got different orders each time I executed the codes. It seemed that no regular rules could be found to explain why the result entities were arranged in such strange orders each time.
<pre>
First execution:
436189898583049570 -0.9999136924743652
436189898583049569 -0.9152258634567261
436189898583049563 -0.8596071600914001
436189898583049567 -0.765427827835083
436189898583049562 -0.2779543399810791
436189898583049561 -1.0                <= the identical vector is here
436189898583049566 -0.9928231835365295
436189898583049565 -0.9725246429443359
436189898583049564 -0.5909770727157593
436189898583049568 -0.5619877576828003

Second execution:
436189898583049682 -0.9954628944396973
436189898583049683 -0.9509173631668091
436189898583049679 -0.942169189453125
436189898583049678 -0.9350605010986328
436189898583049676 -0.8867830634117126
436189898583049677 -0.8851568102836609
436189898583049675 -1.0                <= the identical vector is here
436189898583049680 -0.9833482503890991
436189898583049684 -0.9611386656761169
436189898583049681 -0.940362274646759
</pre>

### Expected Behavior

Right (positive) distance values sorted in descending order.

### Steps To Reproduce

```markdown
import random

import numpy as np
from pymilvus import CollectionSchema, FieldSchema, DataType, connections, Collection
from pymilvus import utility

connections.connect(alias="default", uri="http://localhost:19530")
if utility.has_collection("test"):
    test_collection = Collection(name="test")
    test_collection.drop()

dim = 2
pid = FieldSchema(name="pid", dtype=DataType.INT64, is_primary=True, auto_id=True)
embedding = FieldSchema(name="embedding", dtype=DataType.FLOAT_VECTOR, dim=dim)
schema = CollectionSchema(
    fields=[pid, embedding],
    description="test",
)

test_collection = Collection(
    name="test",
    schema=schema,
    using="default",
    shards_num=2,
    consistency_level="Strong",
)


def vec_norm(vector):
    norm = np.linalg.norm(vector)
    if norm == 0:
        return vector
    return (vector / norm).tolist()


if __name__ == "__main__":

    vec_list = [vec_norm([random.random() for _ in range(dim)]) for n in range(10)]
    test_collection.insert([vec_list])
    test_collection.load()
    result = test_collection.search(
        data=[vec_list[0]],
        anns_field="embedding",
        param={"metric_type": "ip", "params": {"nprobe": 10}},
        limit=10,
        output_fields=[
            "pid",
        ],
        timeout=1,
    )
    for hit in result[0]:
        print(hit.entity.get("pid"), hit.distance)

```

**Comment by cydrain** [comment]
The result from knowhere is correct
```
585:CYD - BruteForceSearch, i = 0, 0.995733
586:CYD - BruteForceSearch, i = 1, 0.945454
587:CYD - BruteForceSearch, i = 2, 0.438621
588:CYD - BruteForceSearch, i = 3, -3.40282e+38
589:CYD - BruteForceSearch, i = 4, -3.40282e+38
590:CYD - BruteForceSearch, i = 5, -3.40282e+38
591:CYD - BruteForceSearch, i = 6, -3.40282e+38
592:CYD - BruteForceSearch, i = 7, -3.40282e+38
593:CYD - BruteForceSearch, i = 8, -3.40282e+38
594:CYD - BruteForceSearch, i = 9, -3.40282e+38
601:CYD - BruteForceSearch, i = 0, 1
602:CYD - BruteForceSearch, i = 1, 0.999995
603:CYD - BruteForceSearch, i = 2, 0.931457
604:CYD - BruteForceSearch, i = 3, 0.887777
605:CYD - BruteForceSearch, i = 4, 0.814421
606:CYD - BruteForceSearch, i = 5, 0.63684
607:CYD - BruteForceSearch, i = 6, 0.435797
608:CYD - BruteForceSearch, i = 7, -3.40282e+38
609:CYD - BruteForceSearch, i = 8, -3.40282e+38
610:CYD - BruteForceSearch, i = 9, -3.40282e+38
```

**Comment by yanliang567** [comment]
@cydrain do we order the results by distance

**Comment by cydrain** [comment]
> @cydrain do we order the results by distance

of cause yes

**Comment by cydrain** [comment]
I'm debugging from where cause the result becomes wrong

**Comment by cydrain** [comment]
Hi @DoliteMatheo ,

If you change the metric type to upper case like following:
```
param={"metric_type": "IP", "params": {"nprobe": 10}},
```
you can get correct result, you can use this as a workaround.
I'll fix this bug soon.

**Comment by yanliang567** [comment]
using the scripts on [2.1.0-20220926-e5f70676]
```
436271497908322466 1.0
436271497908322469 0.9965322017669678
436271497908322474 0.9934778809547424
436271497908322468 0.9798558950424194
436271497908322473 0.9691959619522095
436271497908322475 0.8933621644973755
436271497908322471 0.8694570660591125
436271497908322472 0.8639649152755737
436271497908322470 0.8576121926307678
436271497908322467 0.7575317025184631
```
