### ISSUE TITLE
[Bug]: can't release growing segment

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#19417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

the executor can release only sealed segment

**Comment by xiaofan-luan** [comment]
can you give some clear explain why growing segment can not be released?

**Comment by yah01** [comment]
> can you give some clear explain why growing segment can not be released?

The executor gets the segment to release from SegmentDistributionManager, which not contains the growing segment. The executor treats this as the segment has been released.
