### ISSUE TITLE
[Bug]: create_collection OR drop_collection Retry run out of 10 retry times

### ISSUE THREAD

**Issue by siwenyang** [milvus-io/milvus#19425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.1
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When i do create_collection OR drop_collection, it take very long waiting and show error:

[create_collection] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, Socket closed>
[create_collection] retry:5, cost: 0.81s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, Socket closed>
[create_collection] retry:6, cost: 2.43s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, Socket closed>
[create_collection] retry:7, cost: 7.290000000000001s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, Socket closed>
[create_collection] retry:8, cost: 21.870000000000005s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, Socket closed>
[create_collection] retry:9, cost: 60s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, Socket closed>
[create_collection] retry:10, cost: 60s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, Socket closed>
RPC error: [create_collection], <MilvusUnavaliableException: (code=1, message=server unavaliable: Retry run out of 10 retry times)>, <Time:{'RPC start': '2022-09-25 11:15:54.094021', 'RPC error': '2022-09-25 11:49:33.029882'}>
Traceback (most recent call last):
  File "/home/siwen/.conda/envs/aencoder2/lib/python3.6/site-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/home/siwen/.conda/envs/aencoder2/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 194, in create_collection
    status = rf.result()
  File "/home/siwen/.conda/envs/aencoder2/lib/python3.6/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Socket closed"
        debug_error_string = "{"created":"@1664131773.028279084","description":"Error received from peer ipv4:54.205.41.26:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Socket closed","grpc_status":14}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "search_engine_new.py", line 391, in <module>
    collection = Collection(name=TABLE_NAME, schema=schema, consistency_level="Strong")
  File "/home/siwen/.conda/envs/aencoder2/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 139, in __init__
    consistency_level=consistency_level)
  File "/home/siwen/.conda/envs/aencoder2/lib/python3.6/site-packages/pymilvus/decorators.py", line 96, in handler
    raise e
  File "/home/siwen/.conda/envs/aencoder2/lib/python3.6/site-packages/pymilvus/decorators.py", line 92, in handler
    return func(*args, **kwargs)
  File "/home/siwen/.conda/envs/aencoder2/lib/python3.6/site-packages/pymilvus/decorators.py", line 64, in handler
    raise MilvusUnavaliableException(Status.UNEXPECTED_ERROR, f"server unavaliable: {timeout_msg}")
pymilvus.exceptions.MilvusUnavaliableException: <MilvusUnavaliableException: (code=1, message=server unavaliable: Retry run out of 10 retry times)>

### Steps To Reproduce

```markdown
1. connect milvus
2. create_collection or drop_collection
```

### Milvus Log

[my-release-pulsar-broker-0.log](https://github.com/milvus-io/milvus/files/9641836/my-release-pulsar-broker-0.log)
[my-release-milvus-rootcoord-8699c7889b-9lpqr.log](https://github.com/milvus-io/milvus/files/9641837/my-release-milvus-rootcoord-8699c7889b-9lpqr.log)
[my-release-milvus-proxy-78576f5678-jtb7z.log](https://github.com/milvus-io/milvus/files/9641838/my-release-milvus-proxy-78576f5678-jtb7z.log)

**Comment by siwenyang** [comment]
Milvus version: 2.1.2

**Comment by ICLzhang** [comment]
@XuanYang-cn

**Comment by soothing-rain** [comment]
Resolved offline.

User kept inserting data for 4 days, which caused Pulsar bookie disk usage over 200GigBytes.

These temp data in bookie will not be cleaned up with in `defaultRetentionTimeInMinutes` period, which is by default 7 days.

As instructed by @LoveEachDay , the solution is to set `defaultRetentionTimeInMinutes` to a short period to a shorter period so they can be cleaned up by Pulsar.

**Comment by siwenyang** [comment]
Thank you for help
