### ISSUE TITLE
[Bug]: Milvus uses all the memory, and does not automatically delete files

### ISSUE THREAD

**Issue by Andriy1989** [milvus-io/milvus#19434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.2
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus(last version)
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 16
- GPU: -
- Others: EC2
```

### Current Behavior

Hello! 
I have created 150+ collections. Each collection, as of now, contains from 1 to 50 vectors with a dimension of 4096. In the future, the number of vectors will increase many times, but for now it is just like this. I found that with this configuration milvus "devours" 25 GB of memory during 2 weekend days. I found information about a similar bug (according to the answers it should have been solved by now), also according to the recommendations I downloaded the file https://raw.githubusercontent.com/milvus-io/milvus/v2.1.2/configs/milvus.yaml and set the parameter retentionTimeInMinutes: 1440 (1 day), and added the path to this file in docker-compose.yaml (All other settings are default). It did nothing milvus does not delete unnecessary files. I solve this problem by stopping milvus and manually deleting the entire volumes/milvus folder. After launch, the milvus folder is automatically generated again. Currently, 5 .sst files are generated simultaneously in the rdb_data folder with a size of approximately 70 mb, which are not automatically deleted.
Is there a more efficient way to solve this problem?

### Steps To Reproduce

```markdown
1. install milvus 2.1.2 (wget https://github.com/milvus-io/milvus/releases/download/v2.1.2/milvus-standalone-docker-compose.yml -O docker-compose.yml
)
2. create 150 collections

```

**Comment by yanliang567** [comment]
/assign @LoveEachDay 
could you please take a look at this issue?
/unassign

**Comment by xiaofan-luan** [comment]
@Andriy1989
We don't expect the case where we have so many collections but each collection only contains a few vectors.
Any reasons we want to use like this?

**Comment by Andriy1989** [comment]
Hello! First of all, thank you for your reply. I am preparing a search system for similar products based on their image vectors. Right now I only have a little over 1000 images, but in the future I plan to have about 100,000 image vectors (Currently each vector has an extension of 4096). Now, in order to speed up the vector search (and improve its results), I divided them into separate categories (product groups) and additionally by gender, now I have conditionally 75 product groups, which are further divided for men and women, so I get 150 collections. Now the question, if I understood correctly, the files in rdb_data are generated in such a volume due to the use of a large number of collections, but are not deleted, because there are not enough vectors in the collections (they are too small). Will using one collection solve my problem, but dividing it into separate partitions, that is, will such an architecture reduce the volume of created sst files, and what do you think is more efficient to have 150 collections or 1 collection with 150 partitions, or conditionally 2 collections with 75 partitions?

**Comment by Andriy1989** [comment]
Ok, I created one collection with 150 partitions. Now the ec2 instance is running low on memory, but only one .sst file has been created in 3 hours of work.
Now another question arose.
When I do Creating index I get a message

print(fmt.format("Start Creating index IVF_FLAT"))
index = {
    "index_type": "IVF_FLAT",
    "metric_type": "L2",
    "params": {"nlist": 128},
}

base_collection.create_index(collection_name, index)

Status(code=0, message=''). This message has not appeared before.

**Comment by yanliang567** [comment]
Status(code=0, message=''), it just means creating index successfully
