### ISSUE TITLE
What does "inf" mean

### ISSUE THREAD

**Issue by CrazyBeeline** [milvus-io/milvus#1944]
/tables/{table_name}/vectors
{
  "search": {
      "topk": integer($int64),
      "partition_tags": [string],
      "file_ids": [string],
      "vectors": [[number($float/$uint8)]]
      "params": {
          "nprobe": 16
      }
  }
}
search like above
I get results of previous queries:
{
"distance" : "inf"
"id"  : "158406888065913"
}

version:0.8.0
![image](https://user-images.githubusercontent.com/25030234/79421628-ce19de80-7fed-11ea-97bc-f93f23657d10.png)

**Comment by cydrain** [comment]
To support vector deletion, we did some modification in FAISS, that is:
when a vector is deleted, we did not really remove it, but use another structure named "faiss::ConcurrentBitset" to mark this vector as "removed"; when this vector is calculated, we set its distance as "inf" (means FLOAT MAX).
Generally this vector should not appear in the result set, except the data set is too small.
For example, you need topk = 10, but there is only 8 vectors in current bucket.
In such case, it's possible to see "distance = inf" in the result set.
You can double check whether this vector is deleted.

**Comment by CrazyBeeline** [comment]
谢谢你的答复
inf的数据现在排在前面
topk=10  如果有两个inf 实际上只有8个有效
如果有个场景topk=1 就不会搜索到数据

**Comment by cydrain** [comment]
yes, you're correct.

I suppose your data set is small, you can set nlist smaller, thus each bucket will not return result with distance=inf

**Comment by CrazyBeeline** [comment]
ok!!
Another question: can deleted vectors always be found?
Does the compact operation actually delete vectors?

**Comment by yhmo** [comment]
Deleted vectors cannot be found by get_vector_by_id.
Compact operation will actually delete vectors from raw file, and rebuild index file(if its index has been created). Compact is a heavy operation.

**Comment by CrazyBeeline** [comment]
@yhmo 
In the case of large amount of data, compact is undoubtedly a bad choice
Is there any other way to avoid "inf" queries
Look forward to your reply

**Comment by yhmo** [comment]
Insert 1000000 vectors, and only delete 10 vectors, can definitely avoid 'inf' queries.
But if you only insert 20 vectors, and delete 10 vectors, and search topk > 10, then the 'inf' definitely will returned in result.

**Comment by CrazyBeeline** [comment]
Personal point of view since "inf" is useless data, query results can be ranked behind or simply filtered out
It should not be regarded as an infinite score
