### ISSUE TITLE
[Bug]: ETCD writing data memory abnormal growth

### ISSUE THREAD

**Issue by tgk60w** [milvus-io/milvus#19453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![飞书20220926-173106](https://user-images.githubusercontent.com/49012823/192266484-67d5c2df-42c4-4a0f-abef-f8acf39e7ed2.jpg)
Write 200,000 data, memory has been increasing

**Comment by yanliang567** [comment]
If there were heavy inserting workload at that time, I think this is expected, as long as the memory is able to get down. @tgk60w

**Comment by xiaofan-luan** [comment]
2.2 should kind of solving this issue.
@yanliang567 could we test on master branch and watch the etcd memory usage?

**Comment by tgk60w** [comment]
Stop writing data, only the memory occupation decreases.

**Comment by yanliang567** [comment]
> Stop writing data, only the memory occupation decreases.

anything else keeps increasing or not decrease?

**Comment by tgk60w** [comment]
What is the new version of the launch date

**Comment by tgk60w** [comment]
![image](https://user-images.githubusercontent.com/49012823/192491458-ee20e515-fd2d-460a-abed-7ea6073bc84b.png)
Registration data occupies too much memory, and it is impossible to continue writing data

**Comment by tgk60w** [comment]
> 

现在有解决办法吗?每注册一次数据内存就涨得很高,已经没办法再向milvus 继续注册数据了

**Comment by tgk60w** [comment]
现在有解决办法吗?每注册一次数据内存就涨得很高,已经没办法再向milvus 继续注册数据了 @yanliang567

**Comment by yanliang567** [comment]
@tgk60w how do you insert data into milvus, could you please share a script so that we could reproduce it?
