### ISSUE TITLE
[Bug]: promethus operator can't get instance metrics from namesapce except from default 

### ISSUE THREAD

**Issue by dzqoo** [milvus-io/milvus#19456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.2 
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus2.1.2
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I deploy monitor metrics with Prometheus under office steps，I can not get metrics from helm instance except from default namespace.
Here is my grafana display, in which when select the milvus namespace where my cluster deploied, the instance selector only can show None.
![10cd23fe196f2c7374a0c2812a10681](https://user-images.githubusercontent.com/8862305/192285832-ee1587af-f879-42b6-b37e-48b05e8aff04.jpg)

**Comment by LoveEachDay** [comment]
@dzqoo You need first check the following two things:
1.  `servicemonitor` custom resource has been created successfully in the specified namespace other than `default`
2. if `servicemonitor` is created, check whether prometheus operator has reloaded the prometheus config and  added the scrape target. If the prometheus config doesn't changed, you'd check whether the cluster role is successfully created.

**Comment by dzqoo** [comment]
@LoveEachDay Thank you for applying! I will check it out.

**Comment by kingmbc** [comment]
I had a similar issue. Could you give me more details on the below answer?
```
if servicemonitor is created, check whether prometheus operator has reloaded the prometheus config and added the scrape target. If the prometheus config doesn't changed, you'd check whether the cluster role is successfully created.
```

**Comment by yanliang567** [comment]
> I had a similar issue. Could you give me more details on the below answer?
> 
> ```
> if servicemonitor is created, check whether prometheus operator has reloaded the prometheus config and added the scrape target. If the prometheus config doesn't changed, you'd check whether the cluster role is successfully created.
> ```
> 
> I just followed this official guide.
> 
>     * https://milvus.io/docs/v2.0.x/monitor.md
@kingmbc could you please file a new issue for your questions?
