### ISSUE TITLE
server_config.yaml does not exist, and I’m sure it has been placed in /home/root/milvus/conf as required.

### ISSUE THREAD

**Issue by ydnnh2008** [milvus-io/milvus#1945]
I have pulled the image according to the steps, and placed log_config.conf and server_config.yaml in / home / root / milvus / conf and then started it according to the command, but it still reported an error.

 the command I used:

docker run -d --name milvus_test1 --gpus all \
-p 19530:19530 \
-p 19121:19121 \
-p 9091:9091 \
-v /home/$USER/milvus/db:/var/lib/milvus/db \
-v /home/$USER/milvus/conf:/var/lib/milvus/conf \
-v /home/$USER/milvus/logs:/var/lib/milvus/logs \
-v /home/$USER/milvus/wal:/var/lib/milvus/wal \
milvusdb/milvus:0.8.0-gpu-d041520-464400

The error is:

    __  _________ _   ____  ______    
   /  |/  /  _/ /| | / / / / / __/    
  / /|_/ // // /_| |/ / /_/ /\ \    
 /_/  /_/___/____/___/\____/___/     

Welcome to use Milvus!
Milvus Release version: v0.8.0, built at 2020-04-14 15:32.37, with OpenBLAS library.
You are using Milvus GPU edition
Last commit id: 464400767f8723b9867755c63ab07f7cfe2ecb29

Loading configuration from: ../conf/server_config.yaml
Initializing log config from: ../conf/log_config.conf
Milvus server exit...
Config file not exist: ../conf/server_config.y

I have tried many times, and it is the same wrong, I don’t understand why it still prompts that server_config.yaml does not exist, and I’m sure it has been placed in /home/root/milvus/conf as required.
/home/root/milvus/conf/server_config.yaml
/home/root/milvus/conf/log_config.conf

**Comment by yhmo** [comment]
Hi ydnnh2008,
  Please print 'echo $USER' on your terminator to makesure which user are currently login your machine.

**Comment by Nicolas2912** [comment]
Helle everyone,

so I have an similar problem. I want to configure my server_config.yaml file. In the docs is standing that this file is in ' home/$USER/milvus' but I have no such directory. Can anyone help me please.

I have milvus standalone via docker. 

That was my docker-compose.yml 

`version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.11
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvus`
