### ISSUE TITLE
[Bug]:  I got less data in milvus when I insert data into milvus by 8 threads.

### ISSUE THREAD

**Issue by dzqoo** [milvus-io/milvus#19460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.2 
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):java2.1.0
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I insert data into milvus by 8 theads, I got less data in milvus then the actual.
I have ruled out the impact of abnormal data because the same data is worked well in 1 insert theads.
I got the error in datanode:
`14560: [2022/09/26 11:54:41.107 +00:00] [ERROR] [datanode/compactor.go:509] ["compact wrong"] [planID=436258278408454146] [error="upload to blob storage wrong"] [stack="github.com/milvus-io/milvus/internal/datanode.(*compactionTask).compact\n\t/data/zqdou/milvus-2.1.2/internal/datanode/compactor.go:509\ngithub.com/milvus-io/milvus/internal/datanode.(*compactionExecutor).executeTask\n\t/data/zqdou/milvus-2.1.2/internal/datanode/compaction_executor.go:84"]
	行 14560: [2022/09/26 11:54:41.107 +00:00] [ERROR] [datanode/compactor.go:509] ["compact wrong"] [planID=436258278408454146] [error="upload to blob storage wrong"] [stack="github.com/milvus-io/milvus/internal/datanode.(*compactionTask).compact\n\t/data/zqdou/milvus-2.1.2/internal/datanode/compactor.go:509\ngithub.com/milvus-io/milvus/internal/datanode.(*compactionExecutor).executeTask\n\t/data/zqdou/milvus-2.1.2/internal/datanode/compaction_executor.go:84"]
	行 14563: [2022/09/26 11:54:41.108 +00:00] [WARN] [datanode/compaction_executor.go:86] ["compaction task failed"] [planID=436258278408454146] [error="upload to blob storage wrong"]
	行 15115: [2022/09/26 12:13:10.059 +00:00] [DEBUG] [datanode/data_node.go:753] [DataNode.GetMetrics] [node_id=362] [req="{\"metric_type\":\"system_info\"}"] [metric_type=system_info] [systemInfoMetrics="status:<> response:\"{\\\"has_error\\\":false,\\\"error_reason\\\":\\\"\\\",\\\"name\\\":\\\"datanode362\\\",\\\"hardware_infos\\\":{\\\"ip\\\":\\\"100.22.1.229:21124\\\",\\\"cpu_core_count\\\":32,\\\"cpu_core_usage\\\":1.968072558383362,\\\"memory\\\":17179869184,\\\"memory_usage\\\":562626560,\\\"disk\\\":104857600,\\\"disk_usage\\\":2097152},\\\"system_info\\\":{\\\"system_version\\\":\\\"0a5dd35\\\",\\\"deploy_mode\\\":\\\"DISTRIBUTED\\\",\\\"build_version\\\":\\\"0a5dd35-dev\\\",\\\"build_time\\\":\\\"Sat Sep 17 14:12:53 UTC 2022\\\",\\\"used_go_version\\\":\\\"go version go1.16.9 linux/amd64\\\"},\\\"created_time\\\":\\\"2022-09-26 06:57:39.095567274 +0000 UTC m=+0.186327058\\\",\\\"updated_time\\\":\\\"2022-09-26 06:57:39.09556751 +0000 UTC m=+0.186327289\\\",\\\"type\\\":\\\"datanode\\\",\\\"id\\\":362,\\\"system_configurations\\\":{\\\"flush_insert_buffer_size\\\":16777216}}\" component_name:\"datanode362\" "] []
	行 15115: [2022/09/26 12:13:10.059 +00:00] [DEBUG] [datanode/data_node.go:753] [DataNode.GetMetrics] [node_id=362] [req="{\"metric_type\":\"system_info\"}"] [metric_type=system_info] [systemInfoMetrics="status:<> response:\"{\\\"has_error\\\":false,\\\"error_reason\\\":\\\"\\\",\\\"name\\\":\\\"datanode362\\\",\\\"hardware_infos\\\":{\\\"ip\\\":\\\"100.22.1.229:21124\\\",\\\"cpu_core_count\\\":32,\\\"cpu_core_usage\\\":1.968072558383362,\\\"memory\\\":17179869184,\\\"memory_usage\\\":562626560,\\\"disk\\\":104857600,\\\"disk_usage\\\":2097152},\\\"system_info\\\":{\\\"system_version\\\":\\\"0a5dd35\\\",\\\"deploy_mode\\\":\\\"DISTRIBUTED\\\",\\\"build_version\\\":\\\"0a5dd35-dev\\\",\\\"build_time\\\":\\\"Sat Sep 17 14:12:53 UTC 2022\\\",\\\"used_go_version\\\":\\\"go version go1.16.9 linux/amd64\\\"},\\\"created_time\\\":\\\"2022-09-26 06:57:39.095567274 +0000 UTC m=+0.186327058\\\",\\\"updated_time\\\":\\\"2022-09-26 06:57:39.09556751 +0000 UTC m=+0.186327289\\\",\\\"type\\\":\\\"datanode\\\",\\\"id\\\":362,\\\"system_configurations\\\":{\\\"flush_insert_buffer_size\\\":16777216}}\" component_name:\"datanode362\" "] []`

**Comment by dzqoo** [comment]
[ai-diagnose-milvus-datanode-84bcf6f55f-sk6ww.log](https://github.com/milvus-io/milvus/files/9650719/ai-diagnose-milvus-datanode-84bcf6f55f-sk6ww.log)
Here is the total of of one of the 4 datanode.

**Comment by soothing-rain** [comment]
Browsing through your log there are a lot of "Resource requested is unreadable, please reduce your request rate" warnings, which suggest that there's too much pressure on your MinIO.

I'd suggest that you insert with small # of threads and expect our Bulk Load feature in Milvus 2.2

Some references:
https://aws.amazon.com/premiumsupport/knowledge-center/s3-resolve-503-slowdown-throttling/
https://stackoverflow.com/questions/58433594/aws-s3-slowdown-please-reduce-your-request-rate

**Comment by soothing-rain** [comment]
BTW speaking of "less data in milvus then the actual", did you experience any failed insert operations?

**Comment by dzqoo** [comment]
> BTW speaking of "less data in milvus then the actual", did you experience any failed insert operations?

No, everythings is well.
