### ISSUE TITLE
[Bug]: UT TestIndexNodeComplex failed

### ISSUE THREAD

**Issue by bigsheeper** [milvus-io/milvus#19466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://github.com/milvus-io/milvus/actions/runs/3132416469/jobs/5084738617
related pr https://github.com/milvus-io/milvus/pull/19458

**Comment by xiaocai2333** [comment]
same as #19411
