### ISSUE TITLE
Milvus C++ installation Error

### ISSUE THREAD

**Issue by AyushP123** [milvus-io/milvus#1947]
**Describe the bug**
I was able to install milvus and set the server running up, which I was able to test using python api.
I went on to build the C++ sdk using `./build.sh` in milvus/sdk and faced the error:
```
/home/milvus/sdk/grpc/GrpcClient.cpp:60:41: error: ‘class milvus::grpc::MilvusService::Stub’ has no member named ‘HasCollection’
     ::grpc::Status grpc_status = stub_->HasCollection(&context, collection_name, &response);
```

**Steps/Code to reproduce behavior**
run `./build.sh` in milvus/sdk

**Expected behavior**
milvus c++ object files build

**Environment details**
- Hardware/Softward conditions:
  OS: Ubuntu 18.04
  GPU: 2080 Ti
- Method of installation: From source

- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by JinHai-CN** [comment]
Which branch are you using?

**Comment by AyushP123** [comment]
I didn't pull up the latest changes, was able to install it with 0.8.0
