### ISSUE TITLE
insert search数据缓慢

### ISSUE THREAD

**Issue by hacktmz** [milvus-io/milvus#1949]
**Describe the bug**
单机milvus。使用官方demo修改为insert 2048d向量比faiss原生train+add要缓慢很多

**Expected behavior**
插入搜索速度持平faiss

faiss gpu ivf-flat train cost time: 3.280709981918335

单纯的faiss搜一张图100次耗时
faiss gpu    ivfflat 0.04812216758728027
milvus                     14.31

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
 Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz 8核  32G RAM T4单卡 16g显存

- Method of installation (Docker, or from source)
docker

- Milvus version (v0.3.1, or v0.4.0)
v0.80

- Milvus configuration (Settings you made in `server_config.yaml`)

CollectionSchema(collection_name='example_collection_', dimension=2048, index_file_size=1024, metric_type=<MetricType: L2>)

(collection_name='example_collection_', index_type=<IndexType: IVFLAT>, params={'nlist': 2048})

cache_config:
  cpu_cache_capacity: 8
  insert_buffer_size: 1
  cache_insert_data: false

engine_config:
  use_blas_threshold: 1100
  gpu_search_threshold: 0

其他默认

**Screenshots**

**Additional context**

**Comment by JinHai-CN** [comment]
Currently, Milvus doesn't store data in GPU memory. Since you are using GPU to do the search, Milvus will copy the data from CPU to GPU.
On the other hand, if you use original faiss to do it, the data is in GPU memory after training. No copy data from CPU to GPU, when you do the searching. Therefore, it will be much faster.

**Comment by hacktmz** [comment]
> Currently, Milvus doesn't store data in GPU memory. Since you are using GPU to do the search, Milvus will copy the data from CPU to GPU.
> On the other hand, if you use original faiss to do it, the data is in GPU memory after training. No copy data from CPU to GPU, when you do the searching. Therefore, it will be much faster.

那么如何提高gpu利用率来加快搜索速度

**Comment by JinHai-CN** [comment]
If your data size is larger than GPU memory size, you will have to do the data copy with FAISS. Then, the searching performance won't be so good as now.

**Comment by JinHai-CN** [comment]
> > Currently, Milvus doesn't store data in GPU memory. Since you are using GPU to do the search, Milvus will copy the data from CPU to GPU.
> > On the other hand, if you use original faiss to do it, the data is in GPU memory after training. No copy data from CPU to GPU, when you do the searching. Therefore, it will be much faster.
> 
> 那么如何提高gpu利用率来加快搜索速度

You can't speed it up with Milvus. In the future, we will improve the usage of GPU.

You also can read this article to help understand the reason: https://www.milvus.io/cn/blogs/2019-12-03-select-index.md

**Comment by hacktmz** [comment]
希望可以加入如faiss-gpu API一般的百万级数据常驻显存的策略。对于nq=1的场景更加的贴合，gpu才能发挥作用

**Comment by huhaibin** [comment]
> 希望可以加入如faiss-gpu API一般的百万级数据常驻显存的策略。对于nq=1的场景更加的贴合，gpu才能发挥作用

同样非常希望加入该功能，我们想要用Milvus来替换faiss的使用，但是milvus在nq=1的使用场景下，gpu的使用太鸡肋了。

**Comment by yhmo** [comment]
Link to #1953 #3204

**Comment by shengjun1985** [comment]
The insertion performance of Milvus involves writing to disk.
So as a system, it is normal that the performance is slower than that of a library.
From 0.9.0, we have done a lot of optimization on the CPU performance of training and query.
If still have questions, please continue to contact our community.
Finally, GPU caching can be discussed in issue 1594.
