### ISSUE TITLE
[Bug]: The data of released partitions may be read

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#19496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

From QueryCoordV2, The QueryNode has no idea which partitions are released, this results in the QueryNode may load growing segments of released partitions, and Query/Search would see these data. 

Note: after the segments are flushed, the segment will be released, because QueryCoord can find the sealed segments of released partitions

**Comment by yanliang567** [comment]
@czs007 this is a partition related issue that you may take care.

**Comment by xiaofan-luan** [comment]
keep it

**Comment by yanliang567** [comment]
keep it avtive

**Comment by xiaofan-luan** [comment]
keep it active

**Comment by yah01** [comment]
@bigsheeper Is this solved with the new dynamic load partition?

**Comment by bigsheeper** [comment]
> @bigsheeper Is this solved with the new dynamic load partition?

Yes, I believe it can be solved. Perhaps we should add a test case for this scenario when testing dynamiclly loading partitions @binbinlv
