### ISSUE TITLE
[milvus-admin] The index column  in segments panel  is showing idmap, but my index is set IVFSQ8

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus#1950]
![image](https://user-images.githubusercontent.com/185051/79431570-3623f100-7ffd-11ea-8504-4338de6df2e0.png)

What does it mean? creating index? will it get update ?

**Comment by yhmo** [comment]
Assume a collection has 10 segments, that means there are 10 raw files under the collection, and user create sq8 index, milvus will build index and generate 10 sq8 index files under the collection. So, there are 20 data files under this collection, 10 raw files, 10 index files. When user call show_table_info, the api will get all data files information and return. For raw file, its index type is "IDMAP", for index file, its index type is "SQ8"

**Comment by shanghaikid** [comment]
ok, thanks.
