### ISSUE TITLE
Limit log file count

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#1951]
**Describe the bug**
After long time running, lot of log files generated under /milvus/logs folder, waste lot of storage. 
Each file size is limited to 200MB, we need to limit log file count.

**Comment by yhmo** [comment]
Rewrite RolloutHandler in LogUtil.cpp to do this

**Comment by JinHai-CN** [comment]
Add a config parameter to control the rotate file number limit.
value 0, means no limit.

**Comment by scsven** [comment]
#2207 done
