### ISSUE TITLE
[Enhancement]: Disable time travel and short growing segment lifeime

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#19519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

disable time travel to save memory and disk
shorten growing segment lifetime

**Comment by xiaofan-luan** [comment]
Any suggestion on how we change the config while not change the test cases?

**Comment by yanliang567** [comment]
helm charts were updated accordingly, so they will be applied in e2e tests without ut test impact.
