### ISSUE TITLE
What is the maximum index_file_size

### ISSUE THREAD

**Issue by shiyu22** [milvus-io/milvus#1952]
## Report needed documentation

**Report needed documentation**
index_file_size is pointed when creating collection,but what is the maximum value.

**Comment by JinHai-CN** [comment]
Add index file limit in document. Currently, the index file size range is: 1 ~ 4096.

**Comment by cydrain** [comment]
The limit is better to be 1024 ~ 4096

**Comment by PahudPlus** [comment]
index_file_size is updated in performance_tuning.md.

**Comment by PahudPlus** [comment]
Fixed
