### ISSUE TITLE
Improve Sizing tool

### ISSUE THREAD

**Issue by RyanWei** [milvus-io/milvus#1953]
Could you please improve the sizing tool: https://milvus.io/tools/sizing:
1. Support the more configuration recommendation: Nlist, index_file_size, Nprob.
2. Recommendation for other index type rather than IVF

**Comment by JinHai-CN** [comment]
For IVF index:
index_file_size range: 1 ~ 4096. Normally, index_file_size is larger, the performance is better.

formula:
    index_file_size * nprobe = nlist * nlist

**Comment by JinHai-CN** [comment]
@shengjun1985 Provide the best parameter calculation method of HNSW and Annoy. Also, the memory usage also need to be given.

**Comment by shengjun1985** [comment]
[Annoy]
The best parameter is depend on the dimension and the row num.
For example, dim = 128, n = 1million, it is recommended to set ntrees = 8 and search_k = 50000 which can cause 97% accuracy.
For more info, please refer to:
https://docs.google.com/document/d/1K14Ryy4L_nrit5r1_kSjFieYkItMwdjpUO9tXl35tyQ/edit

**Comment by shengjun1985** [comment]
[HNSW]
https://arxiv.org/pdf/1603.09320.pdf
