### ISSUE TITLE
[Bug]: drop collection  and full insert，disk space cost double

### ISSUE THREAD

**Issue by 12304212** [milvus-io/milvus#19558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.3
- Deployment mode(standalone or cluster):standalone 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 32G
- GPU: 
- Others:
```

### Current Behavior

drop collection  and full insert，disk space cost double，and Never delete

**Comment by 12304212** [comment]
but recent two months disk data  don't clear.  the disk space cost  60X

**Comment by 12304212** [comment]
![image](https://user-images.githubusercontent.com/103092492/193168111-1c7c4bd6-8a7f-4cf7-b23f-6b935bfb3c47.png)
![image](https://user-images.githubusercontent.com/103092492/193168156-24fb8f04-844e-4c53-b4e1-5c0e637915f9.png)

**Comment by yanliang567** [comment]
sounds like a known issue about rockdb, which are are trying to fix.
/assign @xiaofan-luan 
/unassign @12304212

**Comment by xiaofan-luan** [comment]
This is a known issue of rocksmq and we are working on a fix.
So far the easiest fix would be doing a flush and remove the sst directory
