### ISSUE TITLE
[Bug]: proxy crashed if alter collection alias and search in mutlipe threads

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#19557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220928-9d40be7e
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.2dev36
```

### Current Behavior

Proxy pod crashed
[prox.pre.log](https://github.com/milvus-io/milvus/files/9671878/prox.pre.log)

### Expected Behavior

search keeps success

### Steps To Reproduce

```markdown
1. write a script to alter collection alias and search with collection alias
2. run the script in 10 threads
```

**Comment by soothing-rain** [comment]
/unassign
/assign @yanliang567 

Should be fixed now.
