### ISSUE TITLE
[Bug]: IndexBuildTask retry forever if embedding contains Inf/Nan value

### ISSUE THREAD

**Issue by vman-posh** [milvus-io/milvus#19571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.1
- Deployment mode(standalone or cluster): Cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.1.1
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 4/16
- GPU: -
- Others: 6 query nodes, 2 index nodes and 1 data node
```

### Current Behavior

After inserting the embedding containing Inf or NaN value, the Index Node throws `leakage` error and fails to build index. The error is possibly from the underlying FAISS package. 

```bash
[ERROR] [indexcgowrapper/index.go:87] ["there is leakage in index object, please check."] [stack="github.com/milvus-io/milvus/internal/util/indexcgowrapper.NewCgoIndex.func4\n\t/usr/local/src/milvus-2.1.1/internal/util/indexcgowrapper/index.go:87\nruntime.runfinq\n\t/usr/local/go/src/runtime/mfinal.go:242"]
```

### Error log from Faiss package (Index Node)
```bash
[ERROR] [indexnode/task.go:454] ["failed to build index"] [error="[UnexpectedError] Error in void faiss::Clustering::train_encoded(faiss::Clustering::idx_t, const uint8_t*, const faiss::Index*, faiss::Index&, const float*) at /usr/local/src/milvus-2.1.1/cmake_build/3rdparty_download/knowhere-subbuild/src/knowhere_ep/thirdparty/faiss/faiss/Clustering.cpp:423: Error: 'std::isfinite(x[i])' failed: input contains NaN's or Inf's"] [stack="github.com/milvus-io/milvus/internal/indexnode.(*IndexBuildTask).buildIndex\n\t/usr/local/src/milvus-2.1.1/internal/indexnode/task.go:454\ngithub.com/milvus-io/milvus/internal/indexnode.(*IndexBuildTask).Execute\n\t/usr/local/src/milvus-2.1.1/internal/indexnode/task.go:584\ngithub.com/milvus-io/milvus/internal/indexnode.(*TaskScheduler).processTask\n\t/usr/local/src/milvus-2.1.1/internal/indexnode/task_scheduler.go:290\ngithub.com/milvus-io/milvus/internal/indexnode.(*TaskScheduler).indexBuildLoop.func1\n\t/usr/local/src/milvus-2.1.1/internal/indexnode/task_scheduler.go:309"]

[ERROR] [indexnode/task.go:593] ["IndexNode IndexBuildTask Execute buildIndex failed, need to retry"] [buildId=436142493022289922] [error="[UnexpectedError] Error in void faiss::Clustering::train_encoded(faiss::Clustering::idx_t, const uint8_t*, const faiss::Index*, faiss::Index&, const float*) at /usr/local/src/milvus-2.1.1/cmake_build/3rdparty_download/knowhere-subbuild/src/knowhere_ep/thirdparty/faiss/faiss/Clustering.cpp:423: Error: 'std::isfinite(x[i])' failed: input contains NaN's or Inf's"] [stack="github.com/milvus-io/milvus/internal/indexnode.(*IndexBuildTask).Execute\n\t/usr/local/src/milvus-2.1.1/internal/indexnode/task.go:593\ngithub.com/milvus-io/milvus/internal/indexnode.(*TaskScheduler).processTask\n\t/usr/local/src/milvus-2.1.1/internal/indexnode/task_scheduler.go:290\ngithub.com/milvus-io/milvus/internal/indexnode.(*TaskScheduler).indexBuildLoop.func1\n\t/usr/local/src/milvus-2.1.1/internal/indexnode/task_scheduler.go:309"]
```

### Error log from Proxy Node
```bash
[ERROR] [indexcoord/index_builder.go:170] ["index builder peek client error, there is no available"] [stack="github.com/milvus-io/milvus/internal/indexcoord.(*indexBuilder).process\n\t/usr/local/src/milvus-2.1.1/internal/indexcoord/index_builder.go:170\ngithub.com/milvus-io/milvus/internal/indexcoord.(*indexBuilder).schedule\n\t/usr/local/src/milvus-2.1.1/internal/indexcoord/index_builder.go:152"]
```

### Expected Behavior

If I try to insert an invalid vector from Pymilvus, the SDK should itself validate and throw an error. Or, atleast while building index, an error should be thrown to notify user to sanitize and reload data.

### Steps To Reproduce

```markdown
1. Milvus cluster deployment
2. Create an index of type IVF_FLAT before inserting any data
3. Insert vectors containing Inf or NaN values
4. Check the logs from Index node and Proxy node once the index building starts
```

### Anything else?

I checked this for IVF_FLAT indexes only.

**Comment by xiaofan-luan** [comment]
/assign @cydrain 
pls help on it~

**Comment by binbinlv** [comment]
> /assign @binbinlv please check if we have tests for this scenarios

OK.

**Comment by Rachel-42maru** [comment]
I have same problem. How did you deal with this error?

**Comment by PrudhviKumar96** [comment]
I have the same issue. Any solutions?

**Comment by cydrain** [comment]
hi @binbinlv , what's the test for this issue?

**Comment by binbinlv** [comment]
> hi @binbinlv , what's the test for this issue?

hello, we have "Null value support" as a new function in our roadmap, and we will develop test cases systematically based on the new design when this function is ready.

And I think after the new function, this issue will be fixed.

**Comment by binbinlv** [comment]
> hi @binbinlv , what's the test for this issue?

We have tests for insert (in python)
(1): vectors[0][0] = None
report error:
pymilvus.exceptions.DataNotMatchException: <DataNotMatchException: (code=1, message=The data in the same column must be of the same type.)>

(2)  vectors[0][0] = float('nan')
report error:
pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=value 'NaN' is not a number or infinity)>

(3) vectors[0][0] = float('inf')
report error:
pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=value '+Inf' is not a number or infinity)>

@PrudhviKumar96 
What is your pymilvus version?

And could you provide more details about how do you insert an embedding with Nan value? Thanks very much.
