### ISSUE TITLE
C++ API Question

### ISSUE THREAD

**Issue by AyushP123** [milvus-io/milvus#1959]
Hi,

Thank you for your good work, I wanted to ask, where can I find more on the documentation and examples about the C++ API. In particular i wanted to know how to what should be the format for extra_params in IndexParam for IVFPQ. 

I tried `"{{'nlist': 100}, {'m':16'}}"`, got an error of `CreateIndex rpc failed!` (which should be replaced by the expected format for the extra_params, for the particular index).

I also tried using `json.hpp` from `milvus/sdk/thirdparty/nlohmann/` as follows:
```
using JSON = nlohmann::json;
JSON params = {nlist: 100, m: 16};
IndexParam index_param = {"test_01", IndexType::IVFPQ, params.dump()};

```
got a message `Parameter list must contain: nlist ` 
`( params.dump() is [100, 16] )`.

**Comment by yhmo** [comment]
Please use json parameter like: {{"nlist", 1000}, {"m", 12}}
