### ISSUE TITLE
The collection query is not responding

### ISSUE THREAD

**Issue by cjh6666688888** [milvus-io/milvus#19606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:milvus:v2.1.2
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The collection query is not responding，For details, see logs.

### Milvus Log

The collection query is not responding，For details, see logs.

**Comment by cjh6666688888** [comment]
[bw_etcd_ALL.221002-211104.bak.gz](https://github.com/milvus-io/milvus/files/9692646/bw_etcd_ALL.221002-211104.bak.gz)

**Comment by bigsheeper** [comment]
seems not built index? @cjh6666688888 

![image](https://user-images.githubusercontent.com/42060877/193469054-b9d73905-7e46-438a-8b6d-c12af036dcb0.png)

**Comment by bigsheeper** [comment]
autohome use 2.2 preview version and no query timeout, so close it.
