### ISSUE TITLE
[Bug]: Binlog parser test panic

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#19601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://github.com/milvus-io/milvus/actions/runs/3158526001/jobs/5140653273

**Comment by xiaofan-luan** [comment]
same here, any progress?

**Comment by yhmo** [comment]
This is a random failure. The map of golang is not sorted, each time when we get the element from a map, the sequence could be different.
The pr https://github.com/milvus-io/milvus/pull/19643 can fix this problem.

**Comment by yhmo** [comment]
pr #19643 has been merged into master branch.
