### ISSUE TITLE
[Bug]: fail to load segment, error: NoSuchKey

### ISSUE THREAD

**Issue by Roger-Z** [milvus-io/milvus#19610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.4
- Deployment mode(standalone or cluster): k8s cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

querynode pod was crashed and recreated automatically, but fail to load some index segment, error as below:
[querynode/segment_loader.go:175] ["load segment failed when load data into memory"] [collectionID=436324908334317569] [partitionID=436324908334317570] [segmentID=436348990553587713] [segmentType=Sealed] [error="All attempts results:\nattempt #1:NoSuchKey\nattempt #2:NoSuchKey\nattempt #3:NoSuchKey\nattempt #4:NoSuchKey\nattempt #5:NoSuchKey\nattempt #6:NoSuchKey\nattempt #7:NoSuchKey\nattempt #8:NoSuchKey\nattempt #9:NoSuchKey\n"] [stack="github.com/milvus-io/milvus/internal/querynode.(*segmentLoader).LoadSegment.func3\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/segment_loader.go:175\ngithub.com/milvus-io/milvus/internal/util/funcutil.ProcessFuncParallel.func3\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/parallel.go:83"]

### Expected Behavior

should be able to load index file successfully.

### Steps To Reproduce

```markdown
1. querynode pod crash in 20:15, Oct 2 Beijing time
2. after recreate the pod, milvus failed to load index segment, milvus sugguest to upgrade to latest version, so we upgrade to 2.1.4 in 10:30, Oct 3
3. load that 50m collection, and try to search, will trigger the error. 

please check the attached log for more details
```

### Milvus Log

http://rt.ops.cn2.corp.agrant.cn:18000/log/logs.tar.gz

**Comment by jiaoew1991** [comment]
quite the same with https://github.com/milvus-io/milvus/issues/18220

**Comment by yah01** [comment]
@Roger-Z Hey Roger, what's the version before upgrading?

**Comment by Roger-Z** [comment]
> @Roger-Z Hey Roger, what's the version before upgrading?

2.0.2 upgrade to 2.1.4

**Comment by yah01** [comment]
> > @Roger-Z Hey Roger, what's the version before upgrading?
> 
> 2.0.2 upgrade to 2.1.4

Could you use [birdwatcher](https://github.com/milvus-io/birdwatcher) to backup the env?

**Comment by bigsheeper** [comment]
autohome seems met the same issue. Load failed with `NoSuckKey` error:
```log
[2022/10/12 11:58:47.852 +08:00] [WARN] [querynode/task.go:240] ["All attempts results:\nattempt #1:NoSuchKey\n"]
[2022/10/12 11:58:47.853 +08:00] [WARN] [querynode/task_scheduler.go:112] ["All attempts results:\nattempt #1:NoSuchKey\n"]
[2022/10/12 11:58:47.853 +08:00] [WARN] [querynode/impl.go:129] ["All attempts results:\nattempt #1:NoSuchKey\n"]
[2022/10/12 11:58:49.676 +08:00] [ERROR] [querynode/segment_loader.go:175] ["load segment failed when load data into memory"] [collectionID=436120504361287681] [partitionID=436120504361287682] [segmentID=436591786582081537] [segmentType=Growing] [error="All attempts results:\nattempt #1:NoSuchKey\n"] [stack="github.com/milvus-io/milvus/internal/querynode.(*segmentLoader).LoadSegment.func3\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/segment_loader.go:175\ngithub.com/milvus-io/milvus/internal/util/funcutil.ProcessFuncParallel.func3\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/parallel.go:83"]
```

Querycoord:
![image](https://user-images.githubusercontent.com/42060877/195339001-1c1c7d36-b114-4fba-a1ab-321e38d24049.png)

Querynode:
![image](https://user-images.githubusercontent.com/42060877/195339093-4d9e26d6-9c14-45a2-8ba7-1dd4129b3168.png)

**Comment by bigsheeper** [comment]
Here are the logs and etcd backup:
[bw_etcd_ALL.221012-135922.bak.gz](https://github.com/milvus-io/milvus/files/9764702/bw_etcd_ALL.221012-135922.bak.gz)

[datanode-80.log](https://github.com/milvus-io/milvus/files/9764712/datanode-80.log)

[datanode-82.log](https://github.com/milvus-io/milvus/files/9764723/datanode-82.log)

**Comment by yah01** [comment]
The GC of DataCoord may removes old stats logs, and the Query cluster still holds the old stats log path. We will fix this with v2.2.

**Comment by icodersky** [comment]
> They use birdwatcher to remove the growing segment(they allowed data loss), then load again and successfully. However we still need to find out the root cause of `NoSuchKey` error.

We met the same issue.  How do you solve this problem? 
Can you tell me how to write the code to remove the growing segment with birdwatcher? Thank you!

 @bigsheeper

**Comment by bigsheeper** [comment]
> > They use birdwatcher to remove the growing segment(they allowed data loss), then load again and successfully. However we still need to find out the root cause of `NoSuchKey` error.
> 
> We met the same issue. How do you solve this problem? Can you tell me how to write the code to remove the growing segment with birdwatcher? Thank you!
> 
> @bigsheeper

Hi @icodersky, do you allow data loss?

**Comment by icodersky** [comment]
> > > They use birdwatcher to remove the growing segment(they allowed data loss), then load again and successfully. However we still need to find out the root cause of `NoSuchKey` error.
> > 
> > 
> > We met the same issue. How do you solve this problem? Can you tell me how to write the code to remove the growing segment with birdwatcher? Thank you!
> > @bigsheeper
> 
> Hi @icodersky, do you allow data loss?

Allow.

**Comment by bigsheeper** [comment]
> Allow. @bigsheeper

Hi @icodersky you can use birdwatcher (https://github.com/milvus-io/birdwatcher) to remove the growing segment.
With the `remove-segment-by-id` command of birdwatcher, just like:
1. check the target segment by`remove-segment-by-id --segment=[segmentID]`, it would print the segment info, and you need to make sure it is the segment you want to remove:
![image](https://user-images.githubusercontent.com/42060877/196684335-da70974a-d241-4a81-8deb-9b99cd3b7ca1.png)

2. remove segment actually by `remove-segment-by-id --segment=[segmentID] --run`, it would execute removing operation, and you can see the related log:
![image](https://user-images.githubusercontent.com/42060877/196685057-e3c0679b-3c55-46ae-acdf-94dbc9b95350.png)

By the way, it would be better to release collection before you `remove-segment-by-id`.

**Comment by Roger-Z** [comment]
![image](https://user-images.githubusercontent.com/3478019/196849035-dcf46f7d-1d0c-416d-945c-a0fbbaf199b9.png)
would you please take a look at this error? I can't show or remove segment.

**Comment by bigsheeper** [comment]
> ![image](https://user-images.githubusercontent.com/3478019/196849035-dcf46f7d-1d0c-416d-945c-a0fbbaf199b9.png) would you please take a look at this error? I can't show or remove segment.

Context deadline exceeded，maybe you connect to the wrong etcd? can you `show collection` ?

**Comment by Roger-Z** [comment]
yes, I can show collections @bigsheeper

**Comment by Roger-Z** [comment]
now I use birdwatcher to remove those missing segment, and reload the index successfully, however, I can perform a search, it's stuck on Start do search, and timeout.

**Comment by Roger-Z** [comment]
![image](https://user-images.githubusercontent.com/3478019/197095555-2710128a-5b54-4f63-847b-d365cfdf8be4.png)

**Comment by Roger-Z** [comment]
this is backup of etcd [Uploading bw_etcd_ALL.221021-103340.bak.gz…]()

**Comment by Roger-Z** [comment]
etcd backup: http://rt.ops.cn2.corp.agrant.cn:18000/log/bw_etcd_ALL.221021-103340.bak.gz
log: http://rt.ops.cn2.corp.agrant.cn:18000/log/milvus1022.tar.gz
