### ISSUE TITLE
[Bug]: Milvus does not aware of query nodes death

### ISSUE THREAD

**Issue by TaQuangTu** [milvus-io/milvus#19612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.1.4
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.1.2
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When a query node get down, search function does not route search requests to other query nodes, all later search requests fail.

### Expected Behavior

When a query node fail, later search requests should be routed to other query nodes.

### Steps To Reproduce

1. Deploy Milvus on Kubernete with recommended installation guide.

helm upgrade my-release milvus/milvus --set queryNode.replicas=3 --reuse-values

2. Create collection, load it & create index `IVF_FLAT` immediately.
3. Insert & search at Request Per Second (RPS) = 20. 5 vectors for each insertion until around 1000 vectors inserted.

### Milvus Log

Error
```
code 1, mess : fail to search on all shard leaders, err=fail to Search, QueryNode ID=10, reason=Search 11 failed, reason  err err: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.233.118.29:21123: connect: connection refused"
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:232 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).Call
/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:213 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Search
/go/src/github.com/milvus-io/milvus/internal/querynode/shard_cluster.go:824 github.com/milvus-io/milvus/internal/querynode.(*ShardCluster).Search.func2
/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit
```

### Anything else?

I deploy Milvus cluster under cluster mode, 3 pods as worker node. 

<img width="685" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/29690416/194040094-a25c9dc7-631e-464f-bb56-b4c0eccd90f3.png">

**Comment by czs007** [comment]
@TaQuangTu  I'm working on it. Later, I'll provide a tool, and need your help to troubleshoot the problem together.

**Comment by TaQuangTu** [comment]
It's ok @czs007. Thank you and Milvus's contributors.

**Comment by czs007** [comment]
> Im ready @czs007. Thank you and Milvus's contributors.

@TaQuangTu Please familiarize yourself with the installation and use of this tool  https://github.com/milvus-io/birdwatcher first. 
I am writing a document explaining the meaning of meta information.
After you know how to use this birdwatcher, if possible, use the backup command to backup the meta information into a gz file, so that I can analyze it together. You can send it to my email zhenshan.cao@zilliz.com or post it here.

**Comment by TaQuangTu** [comment]
Sorry @czs007 for my late back. This log was captured in following test case:
I tried to reproduce this test ([official Milvus 2 load test guide](https://milvus.io/blog/2022-08-16-A-Quick-Guide-to-Benchmarking-Milvus-2-1.md))
When I conducted search request to the collection, after a while, one of my query node fail --> all incoming search requests fail.
--> Then I captured meta information with the provided tool (`birdwatcher`).
Below is the meta file. Please take a look. Thank you.
[bw_etcd_ALL.221007-095343.bak.gz](https://github.com/milvus-io/milvus/files/9730354/bw_etcd_ALL.221007-095343.bak.gz)
