### ISSUE TITLE
[Bug]: Pymilvus index_building_progress() Returns Indexed Row Count as 0

### ISSUE THREAD

**Issue by vman-posh** [milvus-io/milvus#19616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.1
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.1.1
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 8/16
- GPU: None
- Others:
```

### Current Behavior

After building the index for 100 million vectors, `utility.index_building_progress(collection_name, index_name)` returns indexed row count as `0`. Checked the logs of Index Node to confirm that index building process was complete. Able to reproduce the behaviour with 20M, 50M and 100M vectors.

### Expected Behavior

When `utility.index_building_progress(collection_name, index_name)` in Pymilvus is called, it should return correct number of indexed rows count.

### Steps To Reproduce

```markdown
1. Create a collection with 1 varchar field and 1 embedding vector field
2. Create index on the collection (I used IVF_FLAT) before inserting any vectors
3. Insert the vectors
4. Wait for index building to complete
5. Check indexed rows using `utility.index_building_progress(collection_name, index_name)`
```

### Milvus Log

[indexcoord/index_coord.go:486] ["IndexCoord get index states"] [IndexBuildIDs="[]"]
[indexcoord/meta_table.go:429] ["IndexCoord get index states from meta table"] [indexBuildIDs="[]"]
[indexcoord/index_coord.go:521] ["IndexCoord get index states success"] [total=0] [None=0] [Unissued=0] [InProgress=0] [Finished=0] [Failed=0]
[DEBUG] [proxy/impl.go:2034] ["GetIndexBuildProgress done"] [traceID=6451dd089601305c] [role=proxy] [MsgID=436481898218388199] [BeginTs=436481993258565633] [EndTs=436481993258565633] [db=] [collection=listing_collection_extra] [field=] ["index name"=embedding_index] [result="status:<> total_rows:103295340 "]

### Anything else?

If additional logs are required I can provide.

**Comment by SimFG** [comment]
You need check whether the `index_name` is correct. Using: `utility.index_building_progress("listing_collection_extra","embedding_index")`

**Comment by vman-posh** [comment]
Yes, the index name is correct. 

Created index using - 
`listing_collection.create_index('embedding', listing_index, index_name="embedding_index")`

I could list the index using
`listing_collection.indexes[0].index_name`
O/P: `embedding_index`

**Comment by SimFG** [comment]
Check whether the index has been build completely, using: `utility.wait_for_index_building_complete("listing_collection_extra", index_name="embedding_index")`. When the function has executed over, retry the `index_building_progress ` method.

**Comment by vman-posh** [comment]
When I ran `utility.wait_for_index_building_complete("listing_collection_extra", index_name="embedding_index")`, it returned `True`. 
After that I tried `index_building_progress` method and it still returns `{'total_rows': 103295340, 'indexed_rows': 0}`

**Comment by SimFG** [comment]
Can you provide the milvus server log? I will check it.

**Comment by yanliang567** [comment]
/assign @SimFG 

@vman-posh could you please double check the pymilvus version? or please retry with latest milvus 2.1.4 and pymilvus 2.1.3 if convenient.

**Comment by vman-posh** [comment]
I couldn't find pymilvus version 2.1.4. I tested using pymilvus v2.1.3 and the issue still persists. 
Attached logs from Milvus.
[logs.txt](https://github.com/milvus-io/milvus/files/9748712/logs.txt)

**Comment by SimFG** [comment]
Sorry for replying so late. From the `log.txt`, maybe you need to wait the milvus `v2.2` version, which it will be released in the next week.
![image](https://user-images.githubusercontent.com/21985684/196380296-88a3323b-39c1-4aaf-babb-a4a466e8b03c.png)
The `rootcoord` has been refactor. If you want to continue to use this version, you can try to  use the default index name to create the index.

**Comment by vman-posh** [comment]
Yes, using default index name works!
