### ISSUE TITLE
[Bug]: search timeout

### ISSUE THREAD

**Issue by siwenyang** [milvus-io/milvus#19615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster): 2.1.2 cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.1
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I do search, got error:

File "/home/siwen/.conda/envs/aencoder2/lib/python3.6/site-packages/pymilvus/decorators.py"
line 64, in handler
raise MilvusUnavaliableException(Status.UNEXPECTED ERROR, f"server unavaliable: pvmilvus.exceptions.MilvusUnavaliableException «MilvusUnavaliableException: {timeout msg}")
(code=1,
message=server unavaliable: Retry run out of 10 retry
times)>

### Expected Behavior

search should be performed, instead of time out

### Milvus Log

[my-release-milvus-proxy-6978f8bf6c-2whh5.log](https://github.com/milvus-io/milvus/files/9719782/my-release-milvus-proxy-6978f8bf6c-2whh5.log)

**Comment by jaime0815** [comment]
@siwenyang , could you please provide all the log files?

**Comment by siwenyang** [comment]
> @siwenyang , could you please provide all the log files?

could you let me know which one you need? thank you

**Comment by siwenyang** [comment]
> @siwenyang , could you please provide all the log files?

Please let me know what else logs you need. Thank you for help.

[my-release-milvus-querycoord-8494bbf496-q75qr.log](https://github.com/milvus-io/milvus/files/9720842/my-release-milvus-querycoord-8494bbf496-q75qr.log)
[my-release-milvus-datacoord-778c7fc4fd-bf9n8.log](https://github.com/milvus-io/milvus/files/9720843/my-release-milvus-datacoord-778c7fc4fd-bf9n8.log)
[my-release-milvus-rootcoord-7d67658797-pl5h5.log](https://github.com/milvus-io/milvus/files/9720845/my-release-milvus-rootcoord-7d67658797-pl5h5.log)

**Comment by jaime0815** [comment]
all logs include querynode datanode and indexnode indexcoord log files @siwenyang

**Comment by jaime0815** [comment]
you can refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export all logs?

**Comment by siwenyang** [comment]
> all logs include querynode datanode and indexnode indexcoord log files @siwenyang

Here are all scripts, Thank you for help:
[my-release-milvus-indexcoord-6bdff5dd4c-sq85v.log](https://github.com/milvus-io/milvus/files/9721088/my-release-milvus-indexcoord-6bdff5dd4c-sq85v.log)
[my-release-milvus-indexnode-7c89978c48-5rwxg.log](https://github.com/milvus-io/milvus/files/9721089/my-release-milvus-indexnode-7c89978c48-5rwxg.log)
[my-release-milvus-datanode-664fcb84cd-gpvf7.log](https://github.com/milvus-io/milvus/files/9721090/my-release-milvus-datanode-664fcb84cd-gpvf7.log)
[my-release-milvus-querynode-546697b4b4-c4znq.log](https://github.com/milvus-io/milvus/files/9721091/my-release-milvus-querynode-546697b4b4-c4znq.log)
[my-release-milvus-querynode-546697b4b4-7dglh.log](https://github.com/milvus-io/milvus/files/9721092/my-release-milvus-querynode-546697b4b4-7dglh.log)
[my-release-milvus-querynode-546697b4b4-6b8t2.log](https://github.com/milvus-io/milvus/files/9721093/my-release-milvus-querynode-546697b4b4-6b8t2.log)
[my-release-milvus-querynode-546697b4b4-5qvkw.log](https://github.com/milvus-io/milvus/files/9721094/my-release-milvus-querynode-546697b4b4-5qvkw.log)
[my-release-milvus-querynode-546697b4b4-sj6td.log](https://github.com/milvus-io/milvus/files/9721095/my-release-milvus-querynode-546697b4b4-sj6td.log)
[my-release-milvus-querynode-546697b4b4-ndwzc.log](https://github.com/milvus-io/milvus/files/9721096/my-release-milvus-querynode-546697b4b4-ndwzc.log)
[my-release-milvus-querynode-546697b4b4-h4hbn.log](https://github.com/milvus-io/milvus/files/9721097/my-release-milvus-querynode-546697b4b4-h4hbn.log)
[my-release-milvus-querynode-546697b4b4-8t6cs.log](https://github.com/milvus-io/milvus/files/9721098/my-release-milvus-querynode-546697b4b4-8t6cs.log)
[my-release-milvus-querycoord-8494bbf496-q75qr.log](https://github.com/milvus-io/milvus/files/9721099/my-release-milvus-querycoord-8494bbf496-q75qr.log)
[my-release-milvus-datacoord-778c7fc4fd-bf9n8.log](https://github.com/milvus-io/milvus/files/9721100/my-release-milvus-datacoord-778c7fc4fd-bf9n8.log)
[my-release-milvus-rootcoord-7d67658797-pl5h5.log](https://github.com/milvus-io/milvus/files/9721101/my-release-milvus-rootcoord-7d67658797-pl5h5.log)
[my-release-milvus-proxy-6978f8bf6c-2whh5.log](https://github.com/milvus-io/milvus/files/9721102/my-release-milvus-proxy-6978f8bf6c-2whh5.log)

**Comment by jaime0815** [comment]
It seems all search requests failing,  Can you provide a reproduce steps?

**Comment by siwenyang** [comment]
Before stopped milvus, we tried 6 multi-threads calling search together. There were already several search calls couldn’t finish, i.e., search call over time. But still some search finished. However, after restarting milvus cluster, all search calls failed due to over time.

1. Stop milvus cluster by helm
2. Restart milvus cluster by helm
3. load collection
4. search

________________________________

**Comment by congqixia** [comment]
Preliminary conclusions: there are lots of log indicating no timetick has been received in querynode
```
my-release-milvus-querynode-546697b4b4-c4znq.log:[2022/10/06 04:00:05.455 +00:00] [WARN] [flowgraph/node.go:83] ["some node(s) haven't received input"] [list="[nodeCtxTtChecker-dNode-by-dev-rootcoord-delta_52_436151062879272961v0,nodeCtxTtChecker-dmInputNode-query-436133241570459649-by-dev-rootcoord-delta_31_436133241570459649v1,nodeCtxTtChecker-dNode-by-dev-rootcoord-delta_31_436133241570459649v1,nodeCtxTtChecker-stNode-by-dev-rootcoord-delta_30_436133241570459649v0,nodeCtxTtChecker-dmInputNode-query-436151062879272961-by-dev-rootcoord-delta_53_436151062879272961v1,nodeCtxTtChecker-fdNode-by-dev-rootcoord-delta_52_436151062879272961v0,nodeCtxTtChecker-stNode-by-dev-rootcoord-delta_53_436151062879272961v1,nodeCtxTtChecker-fdNode-by-dev-rootcoord-delta_31_436133241570459649v1,nodeCtxTtChecker-stNode-by-dev-rootcoord-delta_52_436151062879272961v0,nodeCtxTtChecker-fdNode-by-dev-rootcoord-delta_53_436151062879272961v1,nodeCtxTtChecker-stNode-by-dev-rootcoord-delta_31_436133241570459649v1,nodeCtxTtChecker-dmInputNode-query-436133241570459649-by-dev-rootcoord-delta_30_436133241570459649v0,nodeCtxTtChecker-dNode-by-dev-rootcoord-delta_53_436151062879272961v1,nodeCtxTtChecker-dmInputNode-query-436151062879272961-by-dev-rootcoord-delta_52_436151062879272961v0,nodeCtxTtChecker-dNode-by-dev-rootcoord-delta_30_436133241570459649v0,nodeCtxTtChecker-fdNode-by-dev-rootcoord-delta_30_436133241570459649v0]"] ["duration "=2m0s]
my-release-milvus-querynode-546697b4b4-c4znq.log:[2022/10/06 04:02:05.455 +00:00] [WARN] [flowgraph/node.go:83] ["some node(s) haven't received input"] [list="[nodeCtxTtChecker-dNode-by-dev-rootcoord-delta_53_436151062879272961v1,nodeCtxTtChecker-dmInputNode-query-436151062879272961-by-dev-rootcoord-delta_52_436151062879272961v0,nodeCtxTtChecker-dNode-by-dev-rootcoord-delta_30_436133241570459649v0,nodeCtxTtChecker-fdNode-by-dev-rootcoord-delta_30_436133241570459649v0,nodeCtxTtChecker-dNode-by-dev-rootcoord-delta_52_436151062879272961v0,nodeCtxTtChecker-dmInputNode-query-436133241570459649-by-dev-rootcoord-delta_31_436133241570459649v1,nodeCtxTtChecker-dNode-by-dev-rootcoord-delta_31_436133241570459649v1,nodeCtxTtChecker-stNode-by-dev-rootcoord-delta_30_436133241570459649v0,nodeCtxTtChecker-dmInputNode-query-436151062879272961-by-dev-rootcoord-delta_53_436151062879272961v1,nodeCtxTtChecker-fdNode-by-dev-rootcoord-delta_52_436151062879272961v0,nodeCtxTtChecker-stNode-by-dev-rootcoord-delta_53_436151062879272961v1,nodeCtxTtChecker-fdNode-by-dev-rootcoord-delta_31_436133241570459649v1,nodeCtxTtChecker-stNode-by-dev-rootcoord-delta_52_436151062879272961v0,nodeCtxTtChecker-fdNode-by-dev-rootcoord-delta_53_436151062879272961v1,nodeCtxTtChecker-stNode-by-dev-rootcoord-delta_31_436133241570459649v1,nodeCtxTtChecker-dmInputNode-query-436133241570459649-by-dev-rootcoord-delta_30_436133241570459649v0]"] ["duration "=2m0s]
my-release-milvus-querynode-546697b4b4-c4znq.log:[2022/10/06 04:04:05.456 +00:00] [WARN] [flowgraph/node.go:83] ["some node(s) haven't received input"] [list="[nodeCtxTtChecker-dNode-by-dev-rootcoord-delta_53_436151062879272961v1,nodeCtxTtChecker-dmInputNode-query-436151062879272961-by-dev-rootcoord-delta_52_436151062879272961v0,nodeCtxTtChecker-dNode-by-dev-rootcoord-delta_30_436133241570459649v0,nodeCtxTtChecker-fdNode-by-dev-rootcoord-delta_30_436133241570459649v0,nodeCtxTtChecker-dNode-by-dev-rootcoord-delta_52_436151062879272961v0,nodeCtxTtChecker-dmInputNode-query-436133241570459649-by-dev-rootcoord-delta_31_436133241570459649v1,nodeCtxTtChecker-dNode-by-dev-rootcoord-delta_31_436133241570459649v1,nodeCtxTtChecker-stNode-by-dev-rootcoord-delta_30_436133241570459649v0,nodeCtxTtChecker-dmInputNode-query-436151062879272961-by-dev-rootcoord-delta_53_436151062879272961v1,nodeCtxTtChecker-fdNode-by-dev-rootcoord-delta_52_436151062879272961v0,nodeCtxTtChecker-stNode-by-dev-rootcoord-delta_53_436151062879272961v1,nodeCtxTtChecker-fdNode-by-dev-rootcoord-delta_31_436133241570459649v1,nodeCtxTtChecker-stNode-by-dev-rootcoord-delta_52_436151062879272961v0,nodeCtxTtChecker-fdNode-by-dev-rootcoord-delta_53_436151062879272961v1,nodeCtxTtChecker-stNode-by-dev-rootcoord-delta_31_436133241570459649v1,nodeCtxTtChecker-dmInputNode-query-436133241570459649-by-dev-rootcoord-delta_30_436133241570459649v0]"] ["duration "=2m0s]
my-release-milvus-querynode-546697b4b4-c4znq.log:[2022/10/06 04:06:05.455 +00:00] [WARN] [flowgraph/node.go:83] ["some node(s) haven't received input"] [list="[nodeCtxTtChecker-dmInputNode-query-436151062879272961-by-dev-rootcoord-delta_53_436151062879272961v1,nodeCtxTtChecker-fdNode-by-dev-rootcoord-delta_52_436151062879272961v0,nodeCtxTtChecker-stNode-by-dev-rootcoord-delta_53_436151062879272961v1,nodeCtxTtChecker-fdNode-by-dev-rootcoord-delta_31_436133241570459649v1,nodeCtxTtChecker-stNode-by-dev-rootcoord-delta_52_436151062879272961v0,nodeCtxTtChecker-fdNode-by-dev-rootcoord-delta_53_436151062879272961v1,nodeCtxTtChecker-stNode-by-dev-rootcoord-delta_31_436133241570459649v1,nodeCtxTtChecker-dmInputNode-query-436133241570459649-by-dev-rootcoord-delta_30_436133241570459649v0,nodeCtxTtChecker-dNode-by-dev-rootcoord-delta_53_436151062879272961v1,nodeCtxTtChecker-dmInputNode-query-436151062879272961-by-dev-rootcoord-delta_52_436151062879272961v0,nodeCtxTtChecker-dNode-by-dev-rootcoord-delta_30_436133241570459649v0,nodeCtxTtChecker-fdNode-by-dev-rootcoord-delta_30_436133241570459649v0,nodeCtxTtChecker-dNode-by-dev-rootcoord-delta_52_436151062879272961v0,nodeCtxTtChecker-dmInputNode-query-436133241570459649-by-dev-rootcoord-delta_31_436133241570459649v1,nodeCtxTtChecker-dNode-by-dev-rootcoord-delta_31_436133241570459649v1,nodeCtxTtChecker-stNode-by-dev-rootcoord-delta_30_436133241570459649v0]"] ["duration "=2m0s]
```
Still need to find the root cause

**Comment by jaime0815** [comment]
It is strange timetick has only been received in DML channel,  please ensure Pulsar works well, and can you provide Puslar logs?

**Comment by siwenyang** [comment]
> It is strange timetick has only been received in DML channel, please ensure Pulsar works well, and can you provide Puslar logs?
[my-release-pulsar-zookeeper-1.log](https://github.com/milvus-io/milvus/files/9740731/my-release-pulsar-zookeeper-1.log)
[my-release-pulsar-zookeeper-2.log](https://github.com/milvus-io/milvus/files/9740732/my-release-pulsar-zookeeper-2.log)
[my-release-pulsar-zookeeper-0.log](https://github.com/milvus-io/milvus/files/9740733/my-release-pulsar-zookeeper-0.log)
[my-release-pulsar-bookie-1.log](https://github.com/milvus-io/milvus/files/9740739/my-release-pulsar-bookie-1.log)

[my-release-pulsar-recovery-0.log](https://github.com/milvus-io/milvus/files/9740734/my-release-pulsar-recovery-0.log)
[my-release-pulsar-bookie-2_new.log](https://github.com/milvus-io/milvus/files/9740735/my-release-pulsar-bookie-2_new.log)
[my-release-pulsar-bookie-0_new.log](https://github.com/milvus-io/milvus/files/9740736/my-release-pulsar-bookie-0_new.log)
[my-release-pulsar-broker-0_new.log](https://github.com/milvus-io/milvus/files/9740737/my-release-pulsar-broker-0_new.log)
[my-release-pulsar-proxy-0.log](https://github.com/milvus-io/milvus/files/9740738/my-release-pulsar-proxy-0.log)


Hi here are puslar logs.

**Comment by jaime0815** [comment]
> > It is strange timetick has only been received in DML channel, please ensure Pulsar works well, and can you provide Puslar logs?
> 
> Hi here are puslar logs. I updated milvus cluster again, some new parts in logs should be irrelevant.
> 
> [my-release-pulsar-zookeeper-1.log](https://github.com/milvus-io/milvus/files/9740731/my-release-pulsar-zookeeper-1.log) [my-release-pulsar-zookeeper-2.log](https://github.com/milvus-io/milvus/files/9740732/my-release-pulsar-zookeeper-2.log) [my-release-pulsar-zookeeper-0.log](https://github.com/milvus-io/milvus/files/9740733/my-release-pulsar-zookeeper-0.log) [my-release-pulsar-bookie-1.log](https://github.com/milvus-io/milvus/files/9740739/my-release-pulsar-bookie-1.log) [my-release-pulsar-recovery-0.log](https://github.com/milvus-io/milvus/files/9740734/my-release-pulsar-recovery-0.log) [my-release-pulsar-bookie-2_new.log](https://github.com/milvus-io/milvus/files/9740735/my-release-pulsar-bookie-2_new.log) [my-release-pulsar-bookie-0_new.log](https://github.com/milvus-io/milvus/files/9740736/my-release-pulsar-bookie-0_new.log) [my-release-pulsar-broker-0_new.log](https://github.com/milvus-io/milvus/files/9740737/my-release-pulsar-broker-0_new.log) [my-release-pulsar-proxy-0.log](https://github.com/milvus-io/milvus/files/9740738/my-release-pulsar-proxy-0.log)

these logs are unuseful for investigating this issue.  now is it work after updating milvus cluster?

**Comment by siwenyang** [comment]
> > > It is strange timetick has only been received in DML channel, please ensure Pulsar works well, and can you provide Puslar logs?
> > 
> > 
> > Hi here are puslar logs. I updated milvus cluster again, some new parts in logs should be irrelevant.
> > [my-release-pulsar-zookeeper-1.log](https://github.com/milvus-io/milvus/files/9740731/my-release-pulsar-zookeeper-1.log) [my-release-pulsar-zookeeper-2.log](https://github.com/milvus-io/milvus/files/9740732/my-release-pulsar-zookeeper-2.log) [my-release-pulsar-zookeeper-0.log](https://github.com/milvus-io/milvus/files/9740733/my-release-pulsar-zookeeper-0.log) [my-release-pulsar-bookie-1.log](https://github.com/milvus-io/milvus/files/9740739/my-release-pulsar-bookie-1.log) [my-release-pulsar-recovery-0.log](https://github.com/milvus-io/milvus/files/9740734/my-release-pulsar-recovery-0.log) [my-release-pulsar-bookie-2_new.log](https://github.com/milvus-io/milvus/files/9740735/my-release-pulsar-bookie-2_new.log) [my-release-pulsar-bookie-0_new.log](https://github.com/milvus-io/milvus/files/9740736/my-release-pulsar-bookie-0_new.log) [my-release-pulsar-broker-0_new.log](https://github.com/milvus-io/milvus/files/9740737/my-release-pulsar-broker-0_new.log) [my-release-pulsar-proxy-0.log](https://github.com/milvus-io/milvus/files/9740738/my-release-pulsar-proxy-0.log)
> 
> these logs are unuseful for investigating this issue. now is it work after updating milvus cluster?

After milvus reinstall, it didn't work at start. But after around 2 days waiting, milvus work.

**Comment by jaime0815** [comment]
I suspect the search timeout is caused by the unstable Pulsar service,  some clues were found in the log that datanode reconnects pulsar and pulsar occurs GC frequently. 

try to scale up puslar pod, maybe it can help you.

**Comment by siwenyang** [comment]
> 

Thank you for help.
