### ISSUE TITLE
[Enhancement]: MsgBase should ensure all field fill in

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#19639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

MsgBase now has 4 field:
	MsgType              MsgType 
	MsgID                int64    `protobuf:"varint,2,opt,name=msgID,proto3" json:"msgID,omitempty"`
	Timestamp            uint64   `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SourceID             int64    `protobuf:"varint,4,opt,name=sourceID,proto3" json:"sourceID,omitempty"`

#19627 add one more field, which is target ID.

### Why is this needed?

But some of field is not filled when not used, which may cause trouble when we try to handle at consumer side based on certain field.

My suggestion would be ignore messageID field, and make sure all message fill in all the other four field.
There are 465 place msgBase is used so that might be a huge project

**Comment by smellthemoon** [comment]
MsgID and traceID have the same effect, so I think that traceID can be used instead of MsgID. However, it maybe  a little tricky
for the reason that ctx was not provided in mq, it may be a better approach to implement two schemes in mq and grpc.
