### ISSUE TITLE
[Bug]: Where I upgrade milvus from 2.1.2 to 2.1.4, I can't load data.

### ISSUE THREAD

**Issue by dzqoo** [milvus-io/milvus#19646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.4
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus2.1.3
- OS(Ubuntu or CentOS): Centos
- CPU/Memory: querynode:5c16g
- GPU: 
- Others:
```

### Current Behavior

When I upgrade milvus  from 2.1.2 to 2.1.4 and I do loading data into querynode, I got following error.
![image](https://user-images.githubusercontent.com/8862305/194706632-9f229e13-fb6c-4d20-9df0-0078bda73f1f.png)

When I do loading the same data in 2.1.2 with same cluster configs, everything is well.

Here is the all the component logs:
[milvus-log.zip](https://github.com/milvus-io/milvus/files/9739203/milvus-log.zip)
ETCD meta data:
`Milvus(by-dev) > show collections
================================================================================
Collection ID: 436282921587048449	Collection Name:photosearch_topic_onehot_128_02_03
Partitions:
 - Partition ID:436282921587048450	Partition Name:_default
Fields:
 - Field ID: 0 	 Field Name: RowID 	 Field Type: Int64
 - Field ID: 1 	 Field Name: Timestamp 	 Field Type: Int64
 - Field ID: 100 	 Field Name: topic_id 	 Field Type: VarChar
	 - Primary Key, AutoID: false
	 - Type Param max_length: 72
 - Field ID: 101 	 Field Name: remarks 	 Field Type: VarChar
	 - Type Param max_length: 65535
 - Field ID: 102 	 Field Name: vector 	 Field Type: FloatVector
	 - Type Param dim: 128
Consistency Level: Bounded
Start position for channel by-dev-rootcoord-dml_6: [8 8 16 0 24 0 32 0]
Start position for channel by-dev-rootcoord-dml_7: [8 9 16 0 24 0 32 0]
Start position for channel by-dev-rootcoord-dml_8: [8 10 16 0 24 0 32 0]
Start position for channel by-dev-rootcoord-dml_9: [8 11 16 0 24 0 32 0]
`

**Comment by congqixia** [comment]
Hi @dzqoo ,could you please provide the backup file with birdwatcher of you etcd meta?

**Comment by dzqoo** [comment]
@congqixia 
[bw_etcd_ALL.221009-101702.bak.gz](https://github.com/milvus-io/milvus/files/9740627/bw_etcd_ALL.221009-101702.bak.gz)

**Comment by congqixia** [comment]
From the log
```
[2022/10/08 11:57:42.614 +00:00] [INFO] [querycoord/segment_allocator.go:112] ["shuffleSegmentsToQueryNodeV2: get the segment size of loadReqs end"] ["segment size of reqs"="[286151243,302843437,285178293,286470910,285060775,286550822,301591277,284739779,284818174,302115834,285772610,285774303,428322223,284964761,428052506,302008387,301554036,303149748,302919280,285663040,286249475,408581840,285258906,302189837,285519063,293852955,286272801,409547362,301536823,302037304,428213171,285489167,301867935,302307364,286056682,302272823,302445048,428354957,285704354,285738068,302613381,284518232,285787727,409042868,286133561,285976565,543304170,302636768,427878909]"]
```
We could calculate the total size of the load collection shall be `15611089554` or `14.538960116 GB`.
From the offline info from @yanliang567 , the querynode memory size shall be 16GB, and `14.538960116 GB` will be over 90% of the memory capacity(percentage configurable in milvus.yaml). 

When load 8 replicas with 15 querynodes, there shall be one replica contains only one querynode, which shall not be able to load the whole collection.

**Comment by dzqoo** [comment]
@congqixia 
I don't know why one querynode has load a whole collection.Will the segments in one replica be loadded in one querynode?

**Comment by chunyuforka** [comment]
> 



> @congqixia I don't know why one querynode has load a whole collection.Will the segments in one replica be loadded in one querynode?

I have the same problem as you!  I also experienced slow loading after upgrading to version 2.1.4
Only one queryNode memory is occupied

**Comment by chunyuforka** [comment]
> > 
> 
> > @congqixia I don't know why one querynode has load a whole collection.Will the segments in one replica be loadded in one querynode?
> 
> I have the same problem as you! I also experienced slow loading after upgrading to version 2.1.4 Only one queryNode memory is occupied

I found something in the queryCoord log
![ChSnD3MSEd](https://user-images.githubusercontent.com/62608774/194890504-185d3ad7-a5ed-4060-b207-eab6b8a2fd65.jpg)
