### ISSUE TITLE
v0.8.0 version, 在python子进程中使用pymilvus调用milvlus接口异常

### ISSUE THREAD

**Issue by MRCHEN3303** [milvus-io/milvus#1964]
1、在一个子进程里面，调用search，报错：
E0417 12:04:46.181508375  135605 ev_epoll1_linux.cc:822]     assertion failed: gpr_atm_no_barrier_load(&g_active_poller) != (gpr_atm)worker

2、在一个子进程里面，调用collection_info，报错：
show_collection_info

2020-04-17 13:20:32,569 - milvus.client.grpc_handler - ERROR - show_collection_info

**Comment by MRCHEN3303** [comment]
补充下代码：

def _monitor_task_backend():
        milvus_base = Milvus()
        milvus_base.connect(host="192.168.60.125", port=19530)
        print(milvus_base.collection_info('static_face_info'))

def multiprocessing_monitor():
      multi_pool = Pool(1)
      multi_pool.apply_async(func=_monitor_task_backend)

if __name__ == '__main__':
     multiprocessing_monitor()

**Comment by MRCHEN3303** [comment]
问题定位到了，情形如下：
1、主进程有milvus连接的情况下，子进程再milvus连接调用会报错。

2、主进程没有milvus连接的情况下，子进程使用milvus正常。

**Comment by BossZou** [comment]
@MRCHEN3303  You are right, There are some limitation if you use python sdk in multi-process situation. You can read [multiprocessing standard](https://milvus.io/docs/v0.8.0/faq/operational_faq.md#Why-does-my-multiprocessing-program-fail)

**Comment by JinHai-CN** [comment]
Fixed.
