### ISSUE TITLE
[Bug]: Can't built the varchar index of the Milvus 2.1.4

### ISSUE THREAD

**Issue by icodersky** [milvus-io/milvus#19655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.4
- Deployment mode(standalone or cluster):k8s helm cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus v2.1.4
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 256GB
- GPU: 
- Others:
```

### Current Behavior

The string index of Milvus 2.1.4 has not been built. Neither ATTU nor Python code can‘t build the string index normally. I have been waiting. The database files are growing continuously, but we just put 2000 pieces of data yet. (Installed by the k8s helm, the helm has updated milvus to the latest version.). The index of vectors can be builted normally.

![image](https://user-images.githubusercontent.com/86787724/194734902-e33ec3c7-ca46-4bcf-a496-a27281570861.png)

![image](https://user-images.githubusercontent.com/86787724/194734826-55518c45-7426-4251-aaa3-809f2fac40a8.png)

### Steps To Reproduce

```markdown
After installing the milvus's latest version(2.1.4) with helm in k8s, we insert 2000 pieces of data, and then build an index of varchar. By the way, build then index of vector is ok.
```

### Milvus Log

[milvus-log.tar.gz](https://github.com/zilliztech/attu/files/9740629/milvus-log.tar.gz)

**Comment by icodersky** [comment]
Can this problem be solved?

**Comment by icodersky** [comment]
> I did not encounter your problem using the following script trying to imitate your operation. Could you please have a check and try this script if it is the similar with your operation? Thanks.
> 
> milvus: 2.1.4 pymilvus: 2.1.3
> 
> ```python
> from pymilvus import CollectionSchema, FieldSchema
> from pymilvus import Collection
> from pymilvus import connections
> from pymilvus import DataType
> from pymilvus import Partition
> from pymilvus import utility
> 
> connections.connect(host="***", port="19530")
> 
> dim=2048
> string_field_1 = FieldSchema(name="Id", dtype=DataType.VARCHAR, max_length=50,is_primary=True)
> string_field_2 = FieldSchema(name="Patid", dtype=DataType.VARCHAR, max_length=50)
> string_field_3 = FieldSchema(name="Group", dtype=DataType.VARCHAR, max_length=30)
> string_field_4 = FieldSchema(name="AgentNo", dtype=DataType.VARCHAR, max_length=30)
> string_field_5 = FieldSchema(name="IsOpen", dtype=DataType.VARCHAR, max_length=10)
> float_vector = FieldSchema(name="Img", dtype=DataType.FLOAT_VECTOR, dim=dim)
> schema = CollectionSchema(fields=[string_field_1, string_field_2, string_field_3, string_field_4, string_field_5, float_vector])
> 
> collection = Collection("test_search_collection_binbin_0", schema=schema)
> 
> nb = 2000
> vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
> res = collection.insert([[str(i) for i in range(nb)], [str(i) for i in range(nb)], [str(i) for i in range(nb)], [str(i) for i in range(nb)], [str(i) for i in range(nb)], vectors])
> index_param = {"index_type": "IVF_SQ8", "metric_type": "L2", "params": {"nlist": 8192}}
> collection.create_index("Img", index_param, index_name="index_name_1")
> collection.create_index("Patid", index_param, index_name="index_name_2")
> collection.create_index("Group", index_param, index_name="index_name_3")
> ```
 
We found a problem.
The problem occurred when we used attu2.1.1, but the problem did not occur when we used attu2.1.0

**Comment by yanliang567** [comment]
@shanghaikid could you please take a look, it seems to be an attu issue.
/assign @shanghaikid 
/unassign @xige-16

**Comment by Tumao727** [comment]
We have fixed this in attu latest version. Please check it. @icodersky
