### ISSUE TITLE
[Enhancement]: Simplify tests using `T.Setenv`

### ISSUE THREAD

**Issue by Juneezee** [milvus-io/milvus#19650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Currently we are using `os.Setenv` to set and manually restore environment variables in tests. We can use `T.Setenv` function from the `testing` package instead. `T.Setenv` calls `os.Setenv(key, value)` and uses `T.Cleanup` to restore the environment variable to its original value after the test completed.

### Anything else?

Reference: https://pkg.go.dev/testing#T.Setenv

**Comment by xiaofan-luan** [comment]
Good catch, merged into master
