### ISSUE TITLE
IVFPQ C++ questions

### ISSUE THREAD

**Issue by AyushP123** [milvus-io/milvus#1966]
Hi,

Thank you for your good work. I have compiled a list of questions which I think might be useful for someone new to milvus C++ API.

1. Is it possible to insert 5 million vectors in a single go??.  In the `server_config.yaml`, I read that `buffer_size` cannot be greater than 4096 MB. I was able to insert 60k vectors in one go, however when I went ahead to insert 5 million vectors, I got an error: 
`E0417 10:43:16.798395407   14176 proto_buffer_writer.h:83]   assertion failed: byte_count_ < total_size_`
 2. For IVFPQ, faiss uses a coarse quantizer, in milvus is the quantizer assumed by the metric we choose??
3. For IVFPQ, faiss has a `train` method wherein the cluster centroids for IVF and the PQ encodings are computed. For milvus does this happen at the first insert and is then updated every time we update the index??

**Comment by AyushP123** [comment]
FYI I am creating IVFPQ as follows in C++. I had a few more follow up questions:
4. Does the collection just save the IVFPQ index or also the vectors in their original form.
```
conn->DropIndex("test_01");
milvus::CollectionParam collection_param = {"test_01", 512, 2048, milvus::MetricType::L2};
conn->CreateCollection(collection_param);
JSON index_params = {{"nlist", 1000}, {"m", 16}};
IndexParam index_param = {"test_01", IndexType::IVFPQ, index_params.dump()};
conn->CreateIndex(index_param);
```

**Comment by yhmo** [comment]
Hi AyushP123,
  Let me answer your question 1, 4,5. My friend will answer 4&5 later.
1. unlimited insert data could lead to risk run out of memory, so we recently make a change to limit insert data size(#1705) to 256MB
4. Milvus store both raw vectors data and index data to storage disk. 
5. Milvus support float vector and binary vector. For a new created collection, it can only be inserted float vector if the first inserted vector is float. Similarly, the collection can only be inserted float vector if the first inserted vector is binary. So, when you insert a float vector, just keep the binary_data to be empty.

**Comment by AyushP123** [comment]
5. How should the index and the raw vectors be deleted in the memory. I used DropCollection and DropIndex, the GPU and CPU memory being used is not released.

**Comment by yhmo** [comment]
DropIndex will delete all index files from storage disk, and free memory after about 10 seconds.
DropCollection will delete all index files and raw files from storage disk, and free memory after about 10 seconds.

**Comment by AyushP123** [comment]
Thank you for your response @yhmo, for one of my sessions I ended up accidentally shutting down the milvus-server by using `Ctrl + C` instead of running `milvus/core/milvus/stop_script.sh`. I was able to reconnect to the server by running `milvus/core/milvus/start_script.sh`, however when I used `DropCollection` this time, the GPU and CPU memory did not get released. I shut down the server by running the `stop_script.sh` and the respective memories were not released, there is no process running however the GPU and CPU memory are still occupied. How should I solve this??

**Comment by yhmo** [comment]
@AyushP123 
Please provide more information for your problem:
- What kind of of milvus you are running?(compiled by yourself or docker container ?)
- The parameters of the collection: dimension, index_file_size, metric_type
- How many vectors were inserted into the collection?
- Before Ctrl + C, any operation was performed?(such as create_index, search)
- After restart milvus server, before you invoke DropCollection, any other operation was performed?

**Comment by AyushP123** [comment]
Answers to the query:

- Compiled milvus from source, ran the server by running `milvus/core/milvus/scripts/start_server.sh`.

- Parameters of the collection: dimension: 128, index_file_size: 1024, metric_type: L2. I have added the rest of the information here -> https://github.com/milvus-io/milvus/issues/1966#issuecomment-615206466
- Approx 5 million vectors.

- Yes, before Ctrl + C, I ran the operations: CreateCollection(), CreateIndex(), CountCollection(), Insert() from MilvusApi.h

- After restarting the Milvus Server, I ran DropCollection()

**Comment by yhmo** [comment]
Before start_server.sh
GPU memory ocupied: 414MB
CPU memory ocupied: 5.19GB

After start_server.sh
GPU memory ocupied: 421MB
CPU memory ocupied: 5.25GB

C++SDK call CreateCollection(), CreateIndex(), Insert(5 million vectors), CountCollection()
GPU memory ocupied: 443MB
CPU memory ocupied: 5.87GB

Ctrl+C
cmd "ps -ef|grep milvus_server", we can see the milvus_server process is still running
GPU memory ocupied: 443MB
CPU memory ocupied: 5.87GB

stop_server.sh
cmd "ps -ef|grep milvus_server", we can see the milvus_server process is stopped
GPU memory ocupied: 440MB
CPU memory ocupied: 5.20GB

Conclusion:
Ctrl+C cannot actually stop the server.
GPU memory not completely free

**Comment by tinkerlin** [comment]
plz refer to #1992
