### ISSUE TITLE
[Bug]: CreateIndex becomes slower, e2e case test_search_invalid_params_type failed

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#19679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-19678/2/pipeline
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-19670/2/pipeline

**Comment by aoiasd** [comment]
The reason of CreateIndex timeout was that, the indexNode has a param named buildParallel(default =1 ) limited the task scheduler of index node could only run one task in the same time. But the indexCoord will try to create tasks as many as segments of the collection, and will try to send the tasks per 1 seconds but only one success. So if collection has many segment(nearly or more than 40), CreateIndex will be timeout(limited to within 40s).

**Comment by xiaofan-luan** [comment]
how large is the data size for 40 segments?
If we can pass this test before, there might be some performance degrade?

**Comment by aoiasd** [comment]
100000 rows data. Collection field was float_vector(dim=128) and three scalar(int64, float and varchar). CreateSegmentIndex task in queryNode was still vary fast(nearly 60ms ), but we push the task per 1s and limit only one could work, so we could only finish one CreateSegmentIndex task per 1s. The time cost of CreateCollectionIndex was almost only related with the sum of segments, and if two CreateCollectionIndex task in queryCoord, have contention, will make them slower(In fact CreateCollectionIndex with 40 segments some times could pass the e2e test if not have contention with other task).

**Comment by aoiasd** [comment]
> how large is the data size for 40 segments?
> If we can pass this test before, there might be some performance degrade?

100000 rows data. Collection field was float_vector(dim=128) and three scalar(int64, float and varchar). CreateSegmentIndex task in queryNode was still vary fast(nearly 60ms ), but we push the task per 1s and limit only one could work, so we could only finish one CreateSegmentIndex task per 1s. The time cost of CreateCollectionIndex was almost only related with the sum of segments, and if two CreateCollectionIndex task in queryCoord, have contention, will make them slower(In fact CreateCollectionIndex with 40 segments some times could pass the e2e test if not have contention with other task).

**Comment by xiaofan-luan** [comment]
> > how large is the data size for 40 segments?
> > If we can pass this test before, there might be some performance degrade?
> 
> 100000 rows data. Collection field was float_vector(dim=128) and three scalar(int64, float and varchar). CreateSegmentIndex task in queryNode was still vary fast(nearly 60ms ), but we push the task per 1s and limit only one could work, so we could only finish one CreateSegmentIndex task per 1s. The time cost of CreateCollectionIndex was almost only related with the sum of segments, and if two CreateCollectionIndex task in queryCoord, have contention, will make them slower(In fact CreateCollectionIndex with 40 segments some times could pass the e2e test if not have contention with other task).

Maybe we can trigger a new index task one the old task done rather than simply wait for 1s and reschedule?

**Comment by aoiasd** [comment]
> > > how large is the data size for 40 segments?
> > > If we can pass this test before, there might be some performance degrade?
> > 
> > 
> > 100000 rows data. Collection field was float_vector(dim=128) and three scalar(int64, float and varchar). CreateSegmentIndex task in queryNode was still vary fast(nearly 60ms ), but we push the task per 1s and limit only one could work, so we could only finish one CreateSegmentIndex task per 1s. The time cost of CreateCollectionIndex was almost only related with the sum of segments, and if two CreateCollectionIndex task in queryCoord, have contention, will make them slower(In fact CreateCollectionIndex with 40 segments some times could pass the e2e test if not have contention with other task).
> 
> Maybe we can trigger a new index task one the old task done rather than simply wait for 1s and reschedule?

How we trigger the new task? if we want known the task status，we must get it from queryNode, polling same to be necessary，maybe we just need to reduce the polling interval？

**Comment by aoiasd** [comment]
> > > > how large is the data size for 40 segments?
> > > > If we can pass this test before, there might be some performance degrade?
> > > 
> > > 
> > > 100000 rows data. Collection field was float_vector(dim=128) and three scalar(int64, float and varchar). CreateSegmentIndex task in queryNode was still vary fast(nearly 60ms ), but we push the task per 1s and limit only one could work, so we could only finish one CreateSegmentIndex task per 1s. The time cost of CreateCollectionIndex was almost only related with the sum of segments, and if two CreateCollectionIndex task in queryCoord, have contention, will make them slower(In fact CreateCollectionIndex with 40 segments some times could pass the e2e test if not have contention with other task).
> > 
> > 
> > Maybe we can trigger a new index task one the old task done rather than simply wait for 1s and reschedule?
> 
> How we trigger the new task? if we want known the task status，we must get it from queryNode, polling same to be necessary，maybe we just need to reduce the polling interval？

Or because now we check and delete the task in process if finished in the same logic with trigger new task，but maybe the former we could use a longer polling interval, and the latter should used a shorter one.

**Comment by congqixia** [comment]
Hi @xiaofan-luan , do we have any agreement on how to fix this problem yet?

**Comment by yanliang567** [comment]
keep it active

**Comment by yanliang567** [comment]
@yah01 was it fixed?

**Comment by yah01** [comment]
> @yah01 was it fixed?

@aoiasd plz confirm

**Comment by aoiasd** [comment]
Seems like has been fixed

**Comment by aoiasd** [comment]
But createIndex still could only run one task per 1s, ci fixed just because segments sum reduce or compaction faster.
