### ISSUE TITLE
[Enhancement]: Bulkload support parse binlog with start_ts and end_ts 

### ISSUE THREAD

**Issue by wayblink** [milvus-io/milvus#19690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

To support Milvus-backup, we have already supported parse binlog. With start_ts and end_ts we can filter the data to achieve  checkpoint and incremental load.

**Comment by xiaofan-luan** [comment]
we need to unify binlog reader for both bulkload and compaction for further enhancement.

the usage should be

binlogIterator := newBinlogIterator(binlogpath, deltapath, startTs, endTs)
for row: binlogIterator.next(): 
       processing row

All go side file reader should follow the binlog iterator.
And iterator it self has to control is's memory.
TODO: iterator will follow PK order
