### ISSUE TITLE
[Bug]: GC may break the condition of removing segment

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#19691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

As we add the condition of removing segment: child segment is indexed, the garbage collector has 2 ways to collection segments (clearEtcd & scan), `scan()` methods may break the condition

**Comment by xiaofan-luan** [comment]
don't get it.
If we can not delete in clearEtcd,  then all meta will not cleaned, filescan can not delete files with etcd meta?
