### ISSUE TITLE
[Enhancement]: optimize typeutil.AppendFieldData

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#19693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

AppendFieldData is frequently used and data is frequently copied.

Maybe we can optimize it to in place swap or something.

### Why is this needed?

- [ ] record the benchmark of current AppendFieldData
- [ ] optimize it
- [ ] benchmark the refined AppendFieldData

Hopefully, the refined version will be faster and more memory efficient.

**Comment by XuanYang-cn** [comment]
Typical usage of `AppendFieldData` is multi-srcs into 1 dst
```golang
func AppendFieldData(dst []*schemapb.FieldData, src []*schemapb.FieldData, idx int64)
```

**Comment by XuanYang-cn** [comment]
A really clever & complicated mathod to merge 2 sorted arrays in O(1) extra space: Method-6 [Using Euclidean Division Lemma] https://www.geeksforgeeks.org/merge-two-sorted-arrays-o1-extra-space/

**Comment by XuanYang-cn** [comment]
Suppose we have `k` srcs, each has a length of N, then our implementation has a time complexity of `O(kN)`

We can make it better to `O(Nlogk)` with a min-heap. ref: https://www.geeksforgeeks.org/merge-k-sorted-arrays-set-2-different-sized-arrays/

Space costs seem to be a must, otherwise, the code would be too complicated to understand and maintain.

**Comment by xiaofan-luan** [comment]
keep it
