### ISSUE TITLE
Binary index support AVX2 / AVX512

### ISSUE THREAD

**Issue by cydrain** [milvus-io/milvus#1970]
**Is your feature request related to a problem? Please describe.**
na

**Describe the solution you'd like**
Binary index support AVX2 / AVX512

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by shengjun1985** [comment]
We have tested various implementations of avx512 and found that the performance is not good, so we don't plan to support it.
Now, AVX2 is supported and the performance of Jaccard and Hamming is improved.
