### ISSUE TITLE
[Bug]:  query segment data is empty, and querynode restart not load history data not balance

### ISSUE THREAD

**Issue by Folgerjun** [milvus-io/milvus#19721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.4
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 代码中是 2.1.0 ,查询 segment 使用的是 2.1.3
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

新增的 querynode pod 没有被使用
重启后的 querynode 也没有重新加载数据

### Milvus Log

querynode log: 
[milvus-querynodes.tar.gz](https://github.com/milvus-io/milvus/files/9761259/milvus-querynodes.tar.gz)

**Comment by Folgerjun** [comment]
![img_v2_d62b3bcf-8452-4dbe-b0f3-c8dc092a857g](https://user-images.githubusercontent.com/24917694/195244248-bb5ee893-798b-4294-8338-04aa16d9eca1.jpg)
![img_v2_133174f3-c37b-4ebd-9203-5aac785ba94g](https://user-images.githubusercontent.com/24917694/195244280-ebd9599d-0e8a-4e09-96ff-136f8249b713.jpg)

- qn 重启历史数据没有自动加载 新加的两个 qn 也没有被使用
![img_v2_416a8a62-99ed-4860-940f-497de734c90g](https://user-images.githubusercontent.com/24917694/195244690-77e1c4dd-2a8f-4085-8dcf-bde7306d6e09.jpg)

**Comment by Folgerjun** [comment]
补充一下：
- Deployment mode(standalone or cluster): cluster （官网k8s部署）

**Comment by Folgerjun** [comment]
add milvus log:
[logs.tar.gz](https://github.com/milvus-io/milvus/files/9762875/logs.tar.gz)

**Comment by Folgerjun** [comment]
@yanliang567 tks! Although I don't know how the problem is caused, it seems to work normally after the release and load operations.

**Comment by yanliang567** [comment]
looking into the logs, it seems that there are some meta that indicates the collection was loaded, so it does not load even after you called load() again. @Folgerjun
