### ISSUE TITLE
[Bug]: Milvus search and query return wrong result

### ISSUE THREAD

**Issue by mchenyu1218** [milvus-io/milvus#19743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.2
- Deployment mode(standalone or cluster): standalone 
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 
- OS(Ubuntu or CentOS): Linux server
- CPU/Memory: AMD EPYC 7352 24-Core Processor/32GiB
```

### Current Behavior

I was trying to do a query search for some data in milvus, however, the return result does not satisfy the condition we offer. For example, I would like to search for a book in a time range and select a university, but milvus is still giving me the wrong results. I am using Milvus Version 2.1.x and working on the jupyter notebook on the server. Below is the function

def filter_search(k:int, start_year: int, end_year: int, selected_univ: str):
    hello_milvus.load()
    temp = "year >= " + str(start_year) + " and year <= " + str(end_year) + " and university == \"" + str(selected_univ)+"\""
#     filter query based on the results of topic_search
    print(temp)
    
    results = hello_milvus.query(
    expr = temp, 
    consistency_level="Strong",
    output_fields = ["doc_id"],
    limit=None
    )
    print(results)
    for x in results: 
        print(x['doc_id'])
        get_doc_info(x['doc_id'], dataset)
        print("-------------------------")

### Expected Behavior

After executing the function with filter_search(15, 2019.0, 2020, "ucb"), I got the results below, most of which are irrelevant to the expression.
year >= 2019.0 and year <= 2020 and university == "ucb"

8004
Found doc :8004 at 182893
id : 184583

title : Molecular Mechanisms by which Salvinorin A Binds to and Activates the κ-Opioid Receptor

URI : http://rave.ohiolink.edu/etdc/view?acc_num=case1207342013

year : 2008.0

university : Case Western Reserve University School of Graduate Studies
...

### Steps To Reproduce

```markdown
In this environment, I started jupyter notebook on the server and execute that function.
```

### Milvus Log

None

**Comment by xiaofan-luan** [comment]
can I see your insert code?
Say if the filtering condition is only university == "ucb" does it work?

**Comment by mchenyu1218** [comment]
No, I have also tried to do a filter query with only year > 2015, but the returned results still contain documents that are before 2015.

**Comment by mchenyu1218** [comment]
My milvus information is below:
fields = [
    FieldSchema(name="doc_id", dtype=DataType.INT64, is_primary=True),
    FieldSchema(name="eid", dtype=DataType.INT64),
    FieldSchema(name="document_vector", dtype=DataType.FLOAT_VECTOR, dim=50), #Generate schema using for loop
    FieldSchema(name="year", dtype=DataType.DOUBLE),
    FieldSchema(name="university", dtype=DataType.VARCHAR, max_length=100)   
]

Besides, below is how I insert the code: 
eid_list = big_df.loc[:,"id"].values.tolist()
doc_id =  list([i for i in range(big_df.shape[0])])
for i in range(len(eid_list)):
    eid_list[i] = int(eid_list[i])
year_list = big_df.loc[:,"year"].values.tolist()
univ_list = big_df.loc[:,"univ"].values.tolist()
LDA_50_list = big_df.loc[:,"LDA_50"].values.tolist()
data = [doc_id, eid_list, LDA_50_list, year_list, univ_list]
hello_milvus.insert(data)

**Comment by binbinlv** [comment]
> /assign @binbinlv please retry to reproduce it in our lab
> 
> /unassign

Ok, working on it.

**Comment by binbinlv** [comment]
Did not reproduce this issue on my side through the following script, 

@mchenyu1218  Could you help to have a look whether the script describe your scenario rightly? Thanks.

Milvus: v2.1.2, standalone
pymilvus: 2.1.2

```python
 from pymilvus import CollectionSchema, FieldSchema
 from pymilvus import Collection
from pymilvus import connections
from pymilvus import DataType
from pymilvus import Partition
from pymilvus import utility

connections.connect(host="***", port="19530")

fields = [
FieldSchema(name="doc_id", dtype=DataType.INT64, is_primary=True),
FieldSchema(name="eid", dtype=DataType.INT64),
FieldSchema(name="document_vector", dtype=DataType.FLOAT_VECTOR, dim=50), #Generate schema using for loop
FieldSchema(name="year", dtype=DataType.DOUBLE),
FieldSchema(name="university", dtype=DataType.VARCHAR, max_length=100)
]

schema = CollectionSchema(fields=fields)
collection = Collection("test_search_collection", schema=schema)

dim=50
nb =3000
import random
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
import numpy as np

res = collection.insert([[i for i in range(nb)], [i for i in range(nb)], vectors, [np.double(i) for i in range(nb)], ["university"+str(i) for i in range(2000, 2000+nb)]])
collection.load()

expr = "year>=2019.0 and year <= 2020 and university == \"university4020\""
collection.query(expr, output_fields=["university"])
```

**Comment by mchenyu1218** [comment]
I will give you some parts of our data that go wrong by today

**Comment by mchenyu1218** [comment]
https://drive.google.com/drive/folders/1MVZIKKrmjkynEnO7CxYkcRcUOycIYRgM?usp=share_link
This is a part of our dataset, could you try to use the data and reproduce it again?

**Comment by binbinlv** [comment]
> https://drive.google.com/drive/folders/1MVZIKKrmjkynEnO7CxYkcRcUOycIYRgM?usp=share_link This is a part of our dataset, could you try to use the data and reproduce it again?

@mchenyu1218 

FieldSchema(name="year", dtype=DataType.DOUBLE),

here the type for year field is double, but I found that there is "None" in your year data file, so how do you insert the data in double schema.

I want to convert the imported string "year" to double, but it reports error:

```
>>> for year in years_milvus:
...   years_milvus_double.append(float(year))
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ValueError: could not convert string to float: 'None'
```
the "None" data in years_milvus.txt.
```
>>> years_milvus[39647]
'None'
>>> years_milvus[39743]
'None'
>>> years_milvus[41118]
'None'
```

**Comment by binbinlv** [comment]
@mchenyu1218 

And there are 50000 entities in your provided file, and there are some "None" after 30000, so I used the first 30000 data, and reproduce use the above script, the result is right too.

res = collection.insert([id_int[0:30000], [i for i in range(30000)], vectors[0:30000], years_milvus_double, university_milvus[0:30000]])
collection.load()
expr = "year >= 2019.0 and year <= 2020 and university == \"ucb\""
res = collection.query(expr, output_fields=["university"])
>>> length = 0
>>> for tmp_res in res:
...     if tmp_res['university'] == 'ucb':
...       length = length + 1
...
>>> length
797
>>> len(res)
797
```
