### ISSUE TITLE
[Bug]: The total_rows of interface index_building_progress is wrong

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#19752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvus latest
- Deployment mode(standalone or cluster):both
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.0.dev44
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The total_rows of interface index_building_progress is wrong
```
        res, _ = self.utility_wrap.index_building_progress(c_name)
        assert res['indexed_rows'] == 0
>       assert res['total_rows'] == nb
E       assert 0 == 1024
```

### Expected Behavior

The total_rows of interface index_building_progress is the same with nb

### Steps To Reproduce

```markdown
Running test case:
test_utility.py:TestUtilityBase.test_index_process_collection_index

or

test_utility.py:TestUtilityBase.test_wait_index_collection_index
```

**Comment by SimFG** [comment]
The result of new api only contains the `loading_progress` value.

**Comment by binbinlv** [comment]
Verified and fixed.
milvus : [master-20221014-8e7a4733](https://hub.docker.com/layers/milvusdb/milvus/master-20221014-8e7a4733/images/sha256-5bb9da9e187d33096b25b4595eb8ed654d7805d4147cfd64be14ab4dc9dd6192?context=explore)
pymilvus: 2.2.0.dev44

Result:
{'total_rows': 1024, 'indexed_rows': 1024}
