### ISSUE TITLE
[Bug]: When I loadded data into querynode, I got querynode oomkilled.

### ISSUE THREAD

**Issue by dzqoo** [milvus-io/milvus#19769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.2
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus2.1.3
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: querynode:6C24G
- GPU: 
- Others:
```

### Current Behavior

When I load data into querynode and querynode remainded memory is rich for my situation , the is restart because of oomkiled.

Here is the data describe: 300W*400dim with 4.8GB scalar data.
Here is the remainded memory of querynode:
![56fd378f845190547dd93c43c012456](https://user-images.githubusercontent.com/8862305/195583072-4121c46a-396f-4160-9558-7451e1617b2d.jpg)
Here is the whole log of milvus components:
[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/9776067/milvus-log.tar.gz)

**Comment by yanliang567** [comment]
here attached more info from @dzqoo 
<img width="296" alt="image" src="https://user-images.githubusercontent.com/82361606/195594055-e63bf5b9-c11e-45ac-b59e-504dc4c7a046.png">
<img width="191" alt="image" src="https://user-images.githubusercontent.com/82361606/195594094-96eba82c-7082-468d-95cc-c039d5f2b0a3.png">
<img width="296" alt="image" src="https://user-images.githubusercontent.com/82361606/195594186-6ccabfdf-aebc-4ab8-a82f-00874f1d49ee.png">
