### ISSUE TITLE
[Bug]: [rate limit] Continue delete operation ，memory protection is invalid,the milvus server crashed

### ISSUE THREAD

**Issue by yongpengli-z** [milvus-io/milvus#19808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20221016-15878781
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):java-sdk-2.1.0
- OS(Ubuntu or CentOS): 
- CPU/Memory: 8
- GPU: 
- Others:
```

### Current Behavior

quotaAndLimits:
  enabled: true
 dml:
    enabled: true
    insertRate:
      max: 5
    deleteRate:
      max: 2

Continue to delete,the milvus crashed
![image](https://user-images.githubusercontent.com/103410837/196075377-4ad894a5-594b-40e9-a44a-791fe9fc05b8.png)
![image](https://user-images.githubusercontent.com/103410837/196075465-a9f80751-2679-403f-b51b-5bd2c92dbff3.png)

### Steps To Reproduce

```markdown
@Test(description = "DeleteRateTest")
  public void DeleteRateTest() {
    int insertRounds = 5000;
    List<Long> book_id_array = new ArrayList<>();
    for (long i = 0; i < 100000; ++i) {
      book_id_array.add(i);
    }
    for (int r = 0; r < insertRounds; r++) {

      R<MutationResult> delete =
          milvusClient.delete(
              DeleteParam.newBuilder()
                  .withCollectionName("book128")
                  .withExpr("book_id in " + book_id_array)
                  .build());
      log.info("第" + r + "次," + delete.getStatus().toString());
    }
  }
```

**Comment by bigsheeper** [comment]
![img_v2_ad2c3102-6b68-40eb-9951-6857e8de63dg](https://user-images.githubusercontent.com/42060877/196077459-25d12550-6321-4c62-85ce-f733085d07e8.jpg)

**Comment by bigsheeper** [comment]
![image](https://user-images.githubusercontent.com/42060877/196318979-cabcc1ae-e8ef-4734-b88f-830d7db270d5.png)

force to deny writing at 10:16:14, so the oom should be due to the other behavior.

**Comment by bigsheeper** [comment]
please set the memory water mark to 0.8 and 0.9,  and check if the memory is still raising and OOM crash.

**Comment by xiaofan-luan** [comment]
might be the reason compaction will take great amount memory once it is triggered
