### ISSUE TITLE
[Bug]: Cannot create producer on topic with backlog quota exceeded

### ISSUE THREAD

**Issue by yangrz7** [milvus-io/milvus#19805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.x
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus:2.1.1
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![WechatIMG62](https://user-images.githubusercontent.com/37785043/196041982-b4def133-a765-47ab-b14c-f2c3cb0d3075.jpeg)
![Xnip2022-10-16_22-44-24](https://user-images.githubusercontent.com/37785043/196041988-4574ea82-302e-4cc9-a9ab-731db466686b.jpg)

### Steps To Reproduce

```markdown
1. 使用pymilvus连续插入3000w条左右数据
2. 再次插入时阻塞（查看集群log；Cannot create producer on topic with backlog quota exceeded）
3. 使用Attu也无法查询
```

### Milvus Log

[https://fccv-sit-1301539759.cos.ap-guangzhou.myqcloud.com/yangrz/milvus-log.tar](url)

**Comment by soothing-rain** [comment]
@yangrz7 Please take a look at https://github.com/milvus-io/milvus/issues/19423 . See if it is helpful.

/unassign
/assign @yangrz7
