### ISSUE TITLE
[Enhancement]: Milvus search's error reporting is unclear and too lengthy

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#19829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

An error statement like this is not very clear：

`{"log":"[2022-10-14 14:52:39,568] [   ERROR] - RPC error: [search], \u003cMilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=63, reason=ShardCluster for in01-a0c80e87fc44016-rootcoord-dml_0_436665542695976966v0 replicaID 436665542799261697 is no available, state 2, version \u0026{versionID:220 segments:map[436665542698377193:{segmentID:436665542698377193 partitionID:436665542695976967 nodeID:67 state:1 version:-1 inUse:0} 436665542699777504:{segmentID:436665542699777504 partitionID:436665542695976967 nodeID:63 state:3 version:0 inUse:0} 436665542701177775:{segmentID:436665542701177775 partitionID:436665542695976967 nodeID:63 state:3 version:0 inUse:0} 436665542702378058:{segmentID:436665542702378058 partitionID:436665542695976967 nodeID:67 state:1 version:-1 inUse:0} 436665542703978394:{segmentID:436665542703978394 partitionID:436665542695976967 nodeID:63 state:3 version:1665758604324543553 inUse:0} 436665542705378692:{segmentID:436665542705378692 partitionID:436665542695976967 nodeID:63 state:3 version:1665758827334048285 inUse:0} 436665542706979003:{segmentID:436665542706979003 partitionID:436665542695976967 nodeID:68 state:3 version:1665759099330233874 inUse:0} 436665542707979278:{segmentID:436665542707979278 partitionID:436665542695976967 nodeID:67 state:1 version:-1 inUse:0} 436665542709779619:{segmentID:436665542709779619 partitionID:436665542695976967 nodeID:63 state:3 version:1665758827334048285 inUse:0} 436665542711179930:{segmentID:436665542711179930 partitionID:436665542695976967 nodeID:63 state:3 version:0 inUse:0} 436665542712780236:{segmentID:436665542712780236 partitionID:436665542695976967 nodeID:63 state:3 version:0 inUse:0} 436665542713780514:{segmentID:436665542713780514 partitionID:436665542695976967 nodeID:63 state:3 version:0 inUse:0} 436665542715580867:{segmentID:436665542715580867 partitionID:436665542695976967 nodeID:68 state:3 version:1665759099330233874 inUse:0} 436665542716981148:{segmentID:436665542716981148 partitionID:436665542695976967 nodeID:63 state:3 version:1665758827334048285 inUse:0} 436665542717981413:{segmentID:436665542717981413 partitionID:436665542695976967 nodeID:63 state:3 version:1665758827334048285 inUse:0} 436665542719781764:{segmentID:436665542719781764 partitionID:436665542695976967 nodeID:63 state:3 version:1665758604324543553 inUse:0} 436665542721182065:{segmentID:436665542721182065 partitionID:436665542695976967 nodeID:68 state:3 version:1665759099330233874 inUse:0} 436665542721982314:{segmentID:436665542721982314 partitionID:436665542695976967 nodeID:67 state:1 version:-1 inUse:0} 436665542723982676:{segmentID:436665542723982676 partitionID:436665542695976967 nodeID:63 state:3 version:1665759099120696068 inUse:0} 436665542725582997:{segmentID:436665542725582997 partitionID:436665542695976967 nodeID:68 state:3 version:1665759099348404084 inUse:0} 436665542727183307:{segmentID:436665542727183307 partitionID:436665542695976967 nodeID:63 state:3 version:0 inUse:0} 436665542728183581:{segmentID:436665542728183581 partitionID:436665542695976967 nodeID:68 state:3 version:1665759099348404084 inUse:0} 436665542729983923:{segmentID:436665542729983923 partitionID:436665542695976967 nodeID:63 state:3 version:1665758604324543553 inUse:0} 436665542731384230:{segmentID:436665542731384230 partitionID:436665542695976967 nodeID:68 state:3 version:0 inUse:0} 436665542732184484:{segmentID:436665542732184484 partitionID:436665542695976967 nodeID:68 state:3 version:0 inUse:0} 436665542734384841:{segmentID:436665542734384841 partitionID:436665542695976967 nodeID:68 state:3 version:1665759099330233874 inUse:0} 436665542735785249:{segmentID:436665542735785249 partitionID:436665542695976967 nodeID:63 state:3 version:0 inUse:0} 436665542737385556:{segmentID:436665542737385556 partitionID:436665542695976967 nodeID:63 state:3 version:0 inUse:0} 436665542738185812:{segmentID:436665542738185812 partitionID:436665542695976967 nodeID:63 state:3 version:0 inUse:0} 436665542739986155:{segmentID:436665542739986155 partitionID:436665542695976967 nodeID:63 state:3 version:1665758604324543553 inUse:0} 436665542741586467:{segmentID:436665542741586467 partitionID:436665542695976967 nodeID:63 state:3 version:1665759099120696068 inUse:0} 436665542742986779:{segmentID:436665542742986779 partitionID:436665542695976967 nodeID:63 state:3 version:1665759099120696068 inUse:0} 436665542744587094:{segmentID:436665542744587094 partitionID:436665542695976967 nodeID:63 state:3 version:0 inUse:0} 436665542745587370:{segmentID:436665542745587370 partitionID:436665542695976967 nodeID:63 state:3 version:0 inUse:0} 436665542747387711:{segmentID:436665542747387711 partitionID:436665542695976967 nodeID:63 state:3 version:0 inUse:0} 436665542748988021:{segmentID:436665542748988021 partitionID:436665542695976967 nodeID:68 state:3 version:0 inUse:0} 436665542749588267:{segmentID:436665542749588267 partitionID:436665542695976967 nodeID:67 state:1 version:-1 inUse:0} 436665542751188583:{segmentID:436665542751188583 partitionID:436665542695976967 nodeID:63 state:3 version:0 inUse:0} 436665542752988919:{segmentID:436665542752988919 partitionID:436665542695976967 nodeID:63 state:3 version:0 inUse:0} 436665542754789260:{segmentID:436665542754789260 partitionID:436665542695976967 nodeID:63 state:3 version:0 inUse:0} 436665542756189567:{segmentID:436665542756189567 partitionID:436665542695976967 nodeID:63 state:3 version:0 inUse:0} 436665542756989814:{segmentID:436665542756989814 partitionID:436665542695976967 nodeID:63 state:3 version:0 inUse:0} 436665542758590132:{segmentID:436665542758590132 partitionID:436665542695976967 nodeID:63 state:3 version:1665758961681937447 inUse:0} 436665542760390461:{segmentID:436665542760390461 partitionID:436665542695976967 nodeID:68 state:3 version:0 inUse:0} 436665542761990783:{segmentID:436665542761990783 partitionID:436665542695976967 nodeID:63 state:3 version:0 inUse:0} 436665542763391094:{segmentID:436665542763391094 partitionID:436665542695976967 nodeID:68 state:3 version:1665759099330233874 inUse:0} 436665542764791396:{segmentID:436665542764791396 partitionID:436665542695976967 nodeID:63 state:3 version:0 inUse:0} 436665542765991679:{segmentID:436665542765991679 partitionID:436665542695976967 nodeID:68 state:3 version:1665759099330233874 inUse:0} 436665542767792017:{segmentID:436665542767792017 partitionID:436665542695976967 nodeID:68 state:3 version:0 inUse:0} 436665542769192328:{segmentID:436665542769192328 partitionID:436665542695976967 nodeID:63 state:3 version:1665759099120696068 inUse:0} 436665542770792639:{segmentID:436665542770792639 partitionID:436665542695976967 nodeID:67 state:1 version:-1 inUse:0} 436665542771592897:{segmentID:436665542771592897 partitionID:436665542695976967 nodeID:63 state:3 version:0 inUse:0} 436665542773393240:{segmentID:436665542773393240 partitionID:436665542695976967 nodeID:68 state:3 version:0 inUse:0} 436665542774993561:{segmentID:436665542774993561 partitionID:436665542695976967 nodeID:67 state:1 version:-1 inUse:0} 436665542776593871:{segmentID:436665542776593871 partitionID:436665542695976967 nodeID:63 state:3 version:1665759099120696068 inUse:0} 436665542777994183:{segmentID:436665542777994183 partitionID:436665542695976967 nodeID:68 state:3 version:1665759099330233874 inUse:0} 436665542778994463:{segmentID:436665542778994463 partitionID:436665542695976967 nodeID:63 state:3 version:0 inUse:0} 436665542780794789:{segmentID:436665542780794789 partitionID:436665542695976967 nodeID:63 state:3 version:1665758604324543553 inUse:0} 436665542782195094:{segmentID:436665542782195094 partitionID:436665542695976967 nodeID:63 state:3 version:0 inUse:0} 436665542783795406:{segmentID:436665542783795406 partitionID:436665542695976967 nodeID:68 state:3 version:1665759099330233874 inUse:0} 436665542784795671:{segmentID:436665542784795671 partitionID:436665542695976967 nodeID:63 state:3 version:1665758827334048285 inUse:0} 436665542786596100:{segmentID:436665542786596100 partitionID:436665542695976967 nodeID:63 state:3 version:1665758604324543553 inUse:0} 436665542787996401:{segmentID:436665542787996401 partitionID:436665542695976967 nodeID:67 state:1 version:-1 inUse:0} 436665542789396702:{segmentID:436665542789396702 partitionID:436665542695976967 nodeID:63 state:3 version:1665758827334251219 inUse:0} 436665542790396962:{segmentID:436665542790396962 partitionID:436665542695976967 nodeID:68 state:3 version:0 inUse:0} 436665542791397216:{segmentID:436665542791397216 partitionID:436665542695976967 nodeID:68 state:3 version:0 inUse:0} 436665542791997301:{segmentID:436665542791997301 partitionID:436665542695976967 nodeID:63 state:3 version:1665758604324543553 inUse:0}] current:0xc0045c7058 inUse:0xc0045c7060 lastVersion:0xc003810240 ch:0xc0032485a0 closeOnce:{done:0 m:{state:0 sema:0}}})\u003e, \u003cTime:{'RPC start': '2022-10-14 14:52:39.548771', 'RPC error': '2022-10-14 14:52:39.568578'}\u003e (pymilvus.decorators:112)\n","stream":"stdout","time":"2022-10-14T14:52:39.568723817Z"}`

**Comment by XuanYang-cn** [comment]
/unassign
/unassign @yanliang567 
/assign @yah01 
Please help to refine the error message

**Comment by XuanYang-cn** [comment]
/unassign @yah01 
/assign @jingkl 
Please help verify

**Comment by yah01** [comment]
/assign @jingkl 
plz help check with #19836
