### ISSUE TITLE
[Enhancement]: Keep the latest record if Query got duplicated PKs

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#19853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

```python
for schema ("pk": int64, "vec", floatvector)

if insert(1, vecA), (2, vecB)
then delete(pk=1)
then insert(1, vecC), (2, vecD)

query("pk"=1) should got (1, vecC)
query("pk"=2) should got (2, vecD)
```

We should always return the latest record, combined with delete, we can achieve a clean `update`.

### Why is this needed?

/assign @smellthemoon

**Comment by xiaofan-luan** [comment]
For query that make sense.
For search it's a little bit tricky, because if old record is in TopK but new record is not, we have nothing to do, which is kind of annoying ^..^

**Comment by xiaofan-luan** [comment]
unless we can detect deduplication before data ingestion

**Comment by XuanYang-cn** [comment]
> unless we can detect deduplication before data ingestion

this's difficult for collection-level duplication detection in the current storage

**Comment by XuanYang-cn** [comment]
@xiaofan-luan So query is ready to go?

**Comment by congqixia** [comment]
Still WIP

**Comment by XuanYang-cn** [comment]
#20166 was merged, and the next would be adding e2e testcases to cover these cases.

@binbinlv Please help with the e2e cases with @smellthemoon 
/assign @binbinlv
