### ISSUE TITLE
Poor milvus IVFPQ recall as compared to faiss IVFPQ

### ISSUE THREAD

**Issue by AyushP123** [milvus-io/milvus#1992]
Hi,

I created IVFPQ index in faiss as follows ( Python Code) :

```
res = faiss.StandardGpuResources()
d = 256
nlist = 1000
m = 16
nbits = 8
quantizer = faiss.IndexFlatL2(256)
cpu_index = faiss.IndexIVFPQ(quantizer, 256, 1000, 16, 8)
cpu_index.nprobe = 100
index = faiss.index_cpu_to_gpu(res, 0, cpu_index)
index.train(vec)
index.add(vec)
topk = 50
D, I = index.search(query, topk)
```

I created IVFPQ index in milvus as follows ( C++ code ), (compiled milvus sdk and copied `libmilvus_sdk.so, MilvusApi.h, Status.h and json.hpp`):

  ```
ConnectParam param = {"127.0.0.1", "19530"};
conn->Connect(param);
milvus::CollectionParam collection_param = {"test_01", 256, 1024, milvus::MetricType::L2};
conn->CreateCollection(collection_param);
JSON index_params = {{"nlist", 1000}, {"m", 16}};
IndexParam index_param = {"test_01", IndexType::IVFPQ, index_params.dump()};
conn->CreateIndex(index_param);

// Inserted data in batches, inserted using manual ids [0 to 8 million]

JSON search_params = {{"nprobe", 100}};
int64_t topk = 200;
PartitionTagList partition_tag_array;
TopKQueryResult results;
// Read Query Data into entity_array 
conn->Search("test_01", partition_tag_array, entity_array, topk,
                             search_params.dump(), results);
```

While computing the recall using the results from faiss I get a recall of around 97% and while computing recall using results from milvus I get a recall of 20%. I have the following questions ( I am indexing around 8 million vectors ):
1. What is `index_file_size`??. From what I understand using the [troubleshoot link](https://www.milvus.io/docs/v0.8.0/guides/troubleshoot.md), the index is updated after entries occupying `index_file_size` have been added to the database. I have a few follow up questions to this.
          a. Is `index_file_size` used to describe the data occupied by raw vectors or their corresponding indexes ( In the example that I was working on mentioned above the raw vector occupies 1kb and the PQ encoding occupies 16 bytes, so if I want to update the index after every 1 million entries should I set `index_file_size` as 1024 MB or 16 MB ).
          b. if the size occupied never reaches `index_file_size`, then is the index never built??. By building an index, what I mean is that for IVFPQ are the centroids and PQ encodings never trained on the database vectors??.
2. If I want to search across all the partitions should I initialize PartitionTagList as empty??
3. I am assuming for IVFPQ nbits is by default set to 8 from what I could understand through the codebase.
4. When is the faiss.train method called while building IVFPQ index in milvus??

**Comment by tinkerlin** [comment]
1. I guess what you means is `increamental index`. This is not support by milvus now. When the size of the inserted data reaches `index_file_size`, the index will be automatically created in the background. If there is data to be inserted later and also reach `index_file_size`, another index will be create. As i say, the two index is completely irrelevant.  This behavior also will cause milvus-ivfpq recall far lower than faiss-ivfpq.
To the second question, Yes, in this situation the background job will block, but you can build it by manual invoke `create_index`.
2. Yes
3. You are right, the reason why nbits set to 8 is the GPU only support nbit=8 for now.
4. The create index stage is divided into two parts. First train all data and add all data into index.
@AyushP123

**Comment by AyushP123** [comment]
Hi @tinkerlin, thank you for your response. There was a bug in my code due to which I got a suboptimal performance through milvus,  after fixing the bug I got a recall close to the faiss recall. I wanted to ask a few more questions for clarification:
1. Does milvus IVFPQ implementation use faiss code??
2. In the previous answer for the question 4, you mentioned that index stage is divided into two parts, train all the data and then add all the data into index. So every time I call Insert() the centroids and the encodings for IVFPQ change??.

**Comment by tinkerlin** [comment]
1. Yes
2. The **all data** mentioned here means current dataset. Once insert data size reaches `index_file_size` the milvus will use this part of data to create index. The other side client keep inserting data, if data size reaches the second `index_file_size` , milvus will create a new index, and the data range is newly added data. 
To your question, each time you call `insert()` only affect current dataset, and once current dataset be indexed, they won't be reuse again. The next `create_index` stage, won't use the data inserted in the last round.
@AyushP123

**Comment by shengjun1985** [comment]
@AyushP123
https://github.com/milvus-io/docs/blob/master/site/en/guides/milvus_operation.md#createdrop-indexes-in-a-collection
The note introduced how Milvus worked, please refer.

**Comment by AyushP123** [comment]
Thanks for your response guys, really helped a lot!!.
