### ISSUE TITLE
[Bug]: Milvus crush after running some node sdk test case

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus#19931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvusdb/weekly-build:master-20221017-b0404cbb
- Deployment mode(standalone or cluster): 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Milvus crush

### Steps To Reproduce

```markdown
Not sure if it is related with load collection with replica_number.
```

### Milvus Log

[Uploading log-milvus.zip…]()

**Comment by shanghaikid** [comment]
milvus-standalone | [2022/10/20 08:00:31.443 +00:00] [INFO] [datacoord/services.go:501] ["DropVChannel plan to remove"] [channel=by-dev-rootcoord-dml_190_436792891842958310v0]
milvus-standalone | [2022/10/20 08:00:31.444 +00:00] [DEBUG] [datacoord/channel_manager.go:560] ["remove channel assignment"] ["nodeID to be removed"=22] [channelID=by-dev-rootcoord-dml_191_436792891842958310v1] [collectionID=436792891842958310]
milvus-standalone | [2022/10/20 08:00:31.445 +00:00] [INFO] [datanode/data_node.go:359] ["DataNode is handling watchInfo DELETE event"] [key=by-dev/meta/channelwatch/22/by-dev-rootcoord-dml_191_436792891842958310v1]
milvus-standalone | [2022/10/20 08:00:31.446 +00:00] [INFO] [datanode/data_node.go:451] ["try to release flowgraph"] [vChanName=by-dev-rootcoord-dml_191_436792891842958310v1]
milvus-standalone | [2022/10/20 08:00:31.447 +00:00] [INFO] [datacoord/channel_manager.go:756] ["removed channel assignment"] ["channel name"=by-dev-rootcoord-dml_191_436792891842958310v1]
milvus-standalone | [2022/10/20 08:00:31.447 +00:00] [INFO] [datacoord/handler.go:57] [GetDataVChanPositions] [collectionID=436792891842958310] [channel=by-dev-rootcoord-dml_190_436792891842958310v0] [numOfSegments=0]
milvus-standalone | [2022/10/20 08:00:31.448 +00:00] [DEBUG] [datacoord/channel_checker.go:97] ["timer started"] ["watch state"=ToRelease] [nodeID=22] ["channel name"=by-dev-rootcoord-dml_190_436792891842958310v0] ["timeout time"=2022/10/20 08:00:51.447 +00:00]
milvus-standalone | [2022/10/20 08:00:31.449 +00:00] [INFO] [datanode/data_node.go:356] ["DataNode is handling watchInfo PUT event"] [key=by-dev/meta/channelwatch/22/by-dev-rootcoord-dml_190_436792891842958310v0] ["watch state"=ToRelease]
milvus-standalone | [2022/10/20 08:00:31.449 +00:00] [INFO] [datanode/data_node.go:451] ["try to release flowgraph"] [vChanName=by-dev-rootcoord-dml_190_436792891842958310v0]
milvus-standalone | [2022/10/20 08:00:31.449 +00:00] [INFO] [datanode/data_sync_service.go:149] ["dataSyncService closing flowgraph"] [collectionID=436792891842958310] [vChanName=by-dev-rootcoord-dml_190_436792891842958310v0]
milvus-standalone | [2022/10/20 08:00:31.449 +00:00] [DEBUG] [server/rocksmq_impl.go:499] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_190] [group=by-dev-dataNode-22-by-dev-rootcoord-dml_190_436792891842958310v0] [elapsed=0]
milvus-standalone | [2022/10/20 08:00:31.450 +00:00] [DEBUG] [client/client_impl.go:140] ["Consumer MsgMutex closed"]
milvus-standalone | [2022/10/20 08:00:31.450 +00:00] [WARN] [flowgraph/input_node.go:69] ["MsgStream closed"] ["input node"=dmInputNode-data-436792891842958310-by-dev-rootcoord-dml_190_436792891842958310v0]
milvus-standalone | [2022/10/20 08:00:31.450 +00:00] [DEBUG] [flowgraph/node.go:97] ["flow graph node closed"] [nodeName=dmInputNode-data-436792891842958310-by-dev-rootcoord-dml_190_436792891842958310v0]
milvus-standalone | [2022/10/20 08:00:31.451 +00:00] [DEBUG] [flowgraph/node.go:97] ["flow graph node closed"] [nodeName=ddNode-436792891842958310-by-dev-rootcoord-dml_190_436792891842958310v0]
milvus-standalone | [2022/10/20 08:00:31.454 +00:00] [DEBUG] [flowgraph/node.go:97] ["flow graph node closed"] [nodeName=ibNode-by-dev-rootcoord-dml_191_436792891842958310v1]
milvus-standalone | [2022/10/20 08:00:31.454 +00:00] [INFO] [datanode/flow_graph_delete_node.go:105] ["Flowgraph Delete Node closing"]
milvus-standalone | [2022/10/20 08:00:31.454 +00:00] [DEBUG] [flowgraph/node.go:97] ["flow graph node closed"] [nodeName=deleteNode-by-dev-rootcoord-dml_191_436792891842958310v1]
milvus-standalone | [2022/10/20 08:00:31.454 +00:00] [INFO] [datanode/data_node.go:451] ["try to release flowgraph"] [vChanName=by-dev-rootcoord-dml_190_436792891842958310v0]
milvus-standalone | [2022/10/20 08:00:31.461 +00:00] [DEBUG] [flowgraph/node.go:97] ["flow graph node closed"] [nodeName=ibNode-by-dev-rootcoord-dml_190_436792891842958310v0]
milvus-standalone | [2022/10/20 08:00:31.462 +00:00] [INFO] [datanode/flow_graph_delete_node.go:105] ["Flowgraph Delete Node closing"]
milvus-standalone | [2022/10/20 08:00:31.462 +00:00] [DEBUG] [flowgraph/node.go:97] ["flow graph node closed"] [nodeName=deleteNode-by-dev-rootcoord-dml_190_436792891842958310v0]
milvus-standalone | [2022/10/20 08:00:31.464 +00:00] [INFO] [datanode/data_node.go:440] ["handle put event success"] [key=channelwatch/22/by-dev-rootcoord-dml_190_436792891842958310v0] [state=ReleaseSuccess] [vChanName=by-dev-rootcoord-dml_190_436792891842958310v0]
milvus-standalone | [2022/10/20 08:00:31.464 +00:00] [DEBUG] [datacoord/channel_checker.go:112] ["stop timer before timeout"] ["watch state"=ToRelease] [nodeID=22] ["channel name"=by-dev-rootcoord-dml_190_436792891842958310v0] ["timeout time"=2022/10/20 08:00:51.447 +00:00]
milvus-standalone | [2022/10/20 08:00:31.465 +00:00] [DEBUG] [datacoord/channel_manager.go:560] ["remove channel assignment"] ["nodeID to be removed"=22] [channelID=by-dev-rootcoord-dml_190_436792891842958310v0] [collectionID=436792891842958310]
milvus-standalone | [2022/10/20 08:00:31.466 +00:00] [DEBUG] [datanode/data_node.go:350] ["DataNode received a PUT event with an end State"] [state=ReleaseSuccess]
milvus-standalone | [2022/10/20 08:00:31.469 +00:00] [INFO] [datacoord/channel_manager.go:756] ["removed channel assignment"] ["channel name"=by-dev-rootcoord-dml_190_436792891842958310v0]
milvus-standalone | [2022/10/20 08:00:31.470 +00:00] [INFO] [datanode/data_node.go:359] ["DataNode is handling watchInfo DELETE event"] [key=by-dev/meta/channelwatch/22/by-dev-rootcoord-dml_190_436792891842958310v0]
milvus-standalone | [2022/10/20 08:00:31.470 +00:00] [INFO] [datanode/data_node.go:451] ["try to release flowgraph"] [vChanName=by-dev-rootcoord-dml_190_436792891842958310v0]
milvus-standalone | [2022/10/20 08:00:31.553 +00:00] [WARN] [rootcoord/drop_collection_task.go:48] ["drop non-existent collection"] [collection=zxc]
milvus-standalone | [2022/10/20 08:00:31.553 +00:00] [INFO] [rootcoord/root_coord.go:819] ["done to drop collection"] [traceID=27b188acbd899802] [role=rootcoord] [name=zxc] [msgID=436798182180782091] [ts=436798182180782092]
milvus-standalone | [2022/10/20 08:00:31.553 +00:00] [DEBUG] [proxy/impl.go:310] ["DropCollection done"] [traceID=27b188acbd899802] [role=proxy] [MsgID=436798182180782091] [BeginTs=436798182180782091] [EndTs=436798182180782091] [db=] [collection=zxc]
milvus-standalone | [2022/10/20 08:00:31.558 +00:00] [ERROR] [rootcoord/root_coord.go:912] ["failed to describe collection"] [traceID=17b18eaf80cdaff8] ["collection name"=] [id=436792891842958319] [msgID=0] [ts=18446744073709551615] [error="code: CollectionNotExists, reason: can't find collection: collection_wizmgxlf"] [stack="[github.com/milvus-io/milvus/internal/rootcoord.(*Core).DescribeCollection\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:912\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).DescribeCollection\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:343\ngithub.com/milvus-io/milvus/internal/proto/rootcoordpb._RootCoord_DescribeCollection_Handler.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proto/rootcoordpb/root_coord.pb.go:1595\ngithub.com/milvus-io/milvus/internal/util/logutil.UnaryTraceLoggerInterceptor\n\t/go/src/github.com/milvus-io/milvus/internal/util/logutil/grpc_interceptor.go:22\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34\ngithub.com/milvus-io/milvus/internal/proto/rootcoordpb._RootCoord_DescribeCollection_Handler\n\t/go/src/github.com/milvus-io/milvus/internal/proto/rootcoordpb/root_coord.pb.go:1597\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1283\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1620\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:922](http://github.com/milvus-io/milvus/internal/rootcoord.(*Core).DescribeCollection/n/t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:912/ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).DescribeCollection/n/t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:343/ngithub.com/milvus-io/milvus/internal/proto/rootcoordpb._RootCoord_DescribeCollection_Handler.func1/n/t/go/src/github.com/milvus-io/milvus/internal/proto/rootcoordpb/root_coord.pb.go:1595/ngithub.com/milvus-io/milvus/internal/util/logutil.UnaryTraceLoggerInterceptor/n/t/go/src/github.com/milvus-io/milvus/internal/util/logutil/grpc_interceptor.go:22/ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1/n/t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25/ngithub.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1/n/t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38/ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1/n/t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25/ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1/n/t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34/ngithub.com/milvus-io/milvus/internal/proto/rootcoordpb._RootCoord_DescribeCollection_Handler/n/t/go/src/github.com/milvus-io/milvus/internal/proto/rootcoordpb/root_coord.pb.go:1597/ngoogle.golang.org/grpc.(*Server).processUnaryRPC/n/t/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1283/ngoogle.golang.org/grpc.(*Server).handleStream/n/t/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1620/ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2/n/t/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:922)"]
milvus-standalone | panic: runtime error: invalid memory address or nil pointer dereference
milvus-standalone | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2aa42f9]
milvus-standalone | 
milvus-standalone | goroutine 5959904 [running]:
milvus-standalone | [github.com/milvus-io/milvus/internal/querycoordv2/task.packSubDmChannelRequest](http://github.com/milvus-io/milvus/internal/querycoordv2/task.packSubDmChannelRequest)(0xc0241d1b18, {0x3f03cb0?, 0xc0241d1b10?}, 0x0, 0xc00ac551d0, 0x0)
milvus-standalone |     /go/src/[github.com/milvus-io/milvus/internal/querycoordv2/task/utils.go:135](http://github.com/milvus-io/milvus/internal/querycoordv2/task/utils.go:135) +0xd9
milvus-standalone | [github.com/milvus-io/milvus/internal/querycoordv2/task.(*Executor).subDmChannel](http://github.com/milvus-io/milvus/internal/querycoordv2/task.(*Executor).subDmChannel)(0xc00362fb90, 0xc0241d1b18, 0x0?)
milvus-standalone |     /go/src/[github.com/milvus-io/milvus/internal/querycoordv2/task/executor.go:385](http://github.com/milvus-io/milvus/internal/querycoordv2/task/executor.go:385) +0x6d2
milvus-standalone | [github.com/milvus-io/milvus/internal/querycoordv2/task.(*Executor).executeDmChannelAction](http://github.com/milvus-io/milvus/internal/querycoordv2/task.(*Executor).executeDmChannelAction)(0xc004ad2000?, 0xc0241d1b18, 0x0)
milvus-standalone |     /go/src/[github.com/milvus-io/milvus/internal/querycoordv2/task/executor.go:339](http://github.com/milvus-io/milvus/internal/querycoordv2/task/executor.go:339) +0x85
milvus-standalone | [github.com/milvus-io/milvus/internal/querycoordv2/task.(*Executor).Execute.func1()](http://github.com/milvus-io/milvus/internal/querycoordv2/task.(*Executor).Execute.func1())
milvus-standalone |     /go/src/[github.com/milvus-io/milvus/internal/querycoordv2/task/executor.go:109](http://github.com/milvus-io/milvus/internal/querycoordv2/task/executor.go:109) +0xfe
milvus-standalone | created by [github.com/milvus-io/milvus/internal/querycoordv2/task.(*Executor).Execute](http://github.com/milvus-io/milvus/internal/querycoordv2/task.(*Executor).Execute)
milvus-standalone |     /go/src/[github.com/milvus-io/milvus/internal/querycoordv2/task/executor.go:102](http://github.com/milvus-io/milvus/internal/querycoordv2/task/executor.go:102) +0x38a

**Comment by shanghaikid** [comment]
After restarting the docker, I was able to use milvus. 
But after running for 1 hour, it crushed again, and can never be restarted. 
[log-milvus2.zip](https://github.com/milvus-io/milvus/files/9828741/log-milvus2.zip)

**Comment by yanliang567** [comment]
@shanghaikid is it still a problem for you?

**Comment by shanghaikid** [comment]
> @shanghaikid is it still a problem for you?

For now, I don't think so.
