### ISSUE TITLE
[Bug]: QueryCoord keep retrying loadSegment even the collection has been dropped

### ISSUE THREAD

**Issue by bigsheeper** [milvus-io/milvus#19934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 51774844d611971e
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

QueryCoord：
![image](https://user-images.githubusercontent.com/42060877/196911328-204cf0c3-d561-4220-966c-6691083e4511.png)

**Comment by bigsheeper** [comment]
This issue is from *autohome*, online cluster.
[querycord日志.txt](https://github.com/milvus-io/milvus/files/9828397/querycord.txt)
[rootc
[bw_etcd_ALL.221020-170101.bak.gz](https://github.com/milvus-io/milvus/files/9828420/bw_etcd_ALL.221020-170101.bak.gz)
oord-238.log.zip](https://github.com/milvus-io/milvus/files/9828414/rootcoord-238.log.zip)

**Comment by longjiquan** [comment]
Not a querycoord's issue, should be fixed in rootcoord, so close this now.
/close
