### ISSUE TITLE
[Bug]: Error message does not have the key information when create index failed

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#19946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20221020-96cf74d5
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The error message is 
`<MilvusException: (code=1, message=CreateIndex failed: index already exist, but parameters are inconsistent)`
but what the existing parameters are, and the passed-in parameters are.

### Expected Behavior

Tell the reason why parameters are inconsistent.

**Comment by xiaocai2333** [comment]
fixed， please check it.
/assign @zhuwenxing 
/unassign
