### ISSUE TITLE
[Bug]: standalone DEB install does not copy /etc files

### ISSUE THREAD

**Issue by willgamz** [milvus-io/milvus#19948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvus_2.1.4-1_amd64.deb
- Deployment mode(standalone or cluster): standalone
- OS(Ubuntu or CentOS): Ubuntu 18
```

### Current Behavior

After DEB installation /etc files are not copied
The installation ends missing all /etc files. They are in DEB, but are not copied.

tested in:

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

### Steps To Reproduce

```markdown
wget https://github.com/milvus-io/milvus/releases/download/v2.1.4/milvus_2.1.4-1_amd64.deb
    sudo apt-get update
    sudo dpkg -i milvus_2.1.4-1_amd64.deb
    sudo apt-get -f install
```

### Milvus Log

Oct 20 16:21:17 ip-172-31-30-99 systemd[1]: Started Milvus Standalone Server.
Oct 20 16:21:17 ip-172-31-30-99 milvus[4840]: /usr/bin/milvus: error while loading shared libraries: libmilvus_indexbuilder.so: cannot open shared object file: No such file or directory
Oct 20 16:21:17 ip-172-31-30-99 systemd[1]: milvus.service: Main process exited, code=exited, status=127/n/a
Oct 20 16:21:17 ip-172-31-30-99 systemd[1]: milvus.service: Failed with result 'exit-code'.
Oct 20 16:21:17 ip-172-31-30-99 systemd[1]: milvus.service: Service hold-off time over, scheduling restart.
Oct 20 16:21:17 ip-172-31-30-99 systemd[1]: milvus.service: Scheduled restart job, restart counter is at 8.
Oct 20 16:21:17 ip-172-31-30-99 systemd[1]: Stopped Milvus Standalone Server.
Oct 20 16:21:17 ip-172-31-30-99 systemd[1]: Started Milvus Standalone Server.
Oct 20 16:21:17 ip-172-31-30-99 systemd[1]: milvus.service: Main process exited, code=exited, status=127/n/a
Oct 20 16:21:17 ip-172-31-30-99 milvus[4907]: /usr/bin/milvus: error while loading shared libraries: libmilvus_indexbuilder.so: cannot open shared object file: No such file or directory
Oct 20 16:21:17 ip-172-31-30-99 systemd[1]: milvus.service: Failed with result 'exit-code'.
Oct 20 16:21:17 ip-172-31-30-99 systemd[1]: milvus.service: Service hold-off time over, scheduling restart.
Oct 20 16:21:17 ip-172-31-30-99 systemd[1]: milvus.service: Scheduled restart job, restart counter is at 9.
Oct 20 16:21:17 ip-172-31-30-99 systemd[1]: Stopped Milvus Standalone Server.
Oct 20 16:21:17 ip-172-31-30-99 systemd[1]: Dependency failed for Milvus Standalone Server.
Oct 20 16:21:17 ip-172-31-30-99 systemd[1]: milvus.service: Job milvus.service/start failed with result 'dependency'.

**Comment by Bennu-Li** [comment]
Use the command `sudo systemctl status milvus-minio` and `sudo systemctl status milvus-etcd` to check the dependency status.

**Comment by Bennu-Li** [comment]
Try to stop milvus server:
`sudo systemctl stop milvus`
And then start it:
`sudo systemctl start milvus`
And check milvus status:
`sudo systemctl status milvus`

**Comment by willgamz** [comment]
@Bennu-Li 
If you install the package from:
wget https://github.com/milvus-io/milvus/releases/download/v2.1.4/milvus_2.1.4-1_amd64.deb
    sudo apt-get update
    sudo dpkg -i milvus_2.1.4-1_amd64.deb
    sudo apt-get -f install

Check the /etc/milvus don't have files provided in the DEB.
