### ISSUE TITLE
[Bug]: `curl http://{milvus_standalone_host}:9091/api/v1/health` returns `404: Page not Found`

### ISSUE THREAD

**Issue by devennavani** [milvus-io/milvus#19949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.1
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.1
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Output when I do `curl -vv 10.5.131.253:9091/api/v1/health`:

```
*   Trying 10.5.131.253:9091...
* Connected to 10.5.131.253 (10.5.131.253) port 9091 (#0)
> GET /api/v1/health HTTP/1.1
> Host: 10.5.131.253:9091
> User-Agent: curl/7.79.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Thu, 20 Oct 2022 20:56:53 GMT
< Content-Length: 19
< 
404 page not found
* Connection #0 to host 10.5.131.253 left intact
```

`10.5.131.253` is the host IP of our Milvus standalone server. 

When I do `kubectl get svc`, I can see the folllowing:

`milvus                 ClusterIP   172.20.42.81     <none>        19530/TCP,9091/TCP            120m`

For reference, `curl 10.5.131.253:9091/metrics` works.

### Expected Behavior

I am expecting a response of `{'status': 'ok'}`.

### Steps To Reproduce

```markdown
Deploy Milvus standalone to K8s and try pinging port 9091 of the Milvus standalone pod.
```

### Milvus Log

There are no warn / error / fatal logs on the Milvus standalone server, only info logs.

**Comment by LoveEachDay** [comment]
@devennavani Could you check the `/milvus/configs/milvus.yaml` file inside the `milvus-standalone` pod to verify whether `proxy.http.enabled` is set to `true` ?

**Comment by devennavani** [comment]
@LoveEachDay that fixed it, thanks! It would be helpful to have that in the docs somewhere.
