### ISSUE TITLE
[Bug]: reload index is too slow

### ISSUE THREAD

**Issue by Roger-Z** [milvus-io/milvus#19958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.4
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I have an index with 50m entities, 768 dimension each, it cost me 10 hours to release and reload the index to memory.

### Expected Behavior

should load faster, because the load balance is not working, we have to release and reload index occasionally.

### Milvus Log

http://rt.ops.cn2.corp.agrant.cn:18000/log/milvus1022.tar.gz

**Comment by Roger-Z** [comment]
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/3478019/197105569-8f39c853-4e83-4223-91cf-0e5937dba216.png">

**Comment by Roger-Z** [comment]
looks like it's loading index file every half an hour, and sleep a long time, which is odd.

**Comment by bigsheeper** [comment]
Hi @Roger-Z can you offer me the backup of etcd by using birdwatcher?

**Comment by Roger-Z** [comment]
@bigsheeper  sure, here it is
http://rt.ops.cn2.corp.agrant.cn:18000/log/bw_etcd_ALL.221021-103340.bak.gz

**Comment by bigsheeper** [comment]
> @bigsheeper sure, here it is http://rt.ops.cn2.corp.agrant.cn:18000/log/bw_etcd_ALL.221021-103340.bak.gz

@Roger-Z seems the link was out of work.

**Comment by Roger-Z** [comment]
@bigsheeper The link is still valid, please copy the link and paste into browser.
