### ISSUE TITLE
[Enhancement]: Add compaction time cost as monitoring metric.

### ISSUE THREAD

**Issue by soothing-rain** [milvus-io/milvus#19963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

As we need to better track compaction time cost.

**Comment by xiaofan-luan** [comment]
keep it

**Comment by xiaofan-luan** [comment]
keep it

**Comment by XuanYang-cn** [comment]
This PR added the compaction latency metric: https://github.com/milvus-io/milvus/pull/15650
```
metrics.DataNodeCompactionLatency.WithLabelValues(fmt.Sprint(paramtable.GetNodeID())).Observe(float64(t.tr.ElapseSpan().Milliseconds()))
```

**Comment by XuanYang-cn** [comment]
DataNodeCompactionLatency is enough for now.
