### ISSUE TITLE
[Bug]: milvus sdk should trigger releaseCollection after loadCollection timeout

### ISSUE THREAD

**Issue by weiliu1031** [milvus-io/milvus#19961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. sdk trigger load collection request and success
2. sdk check loading progress with timeout 
3. sdk timeout and exit, but query coord is still doing loadTask.
4. it will affect later user operation

### Expected Behavior

when sdk trigger a loadCollection and meet timeout in check loading progress, sdk should trigger releaseCollection before exit

**Comment by yanliang567** [comment]
I don't think this is a good idea in sdk. 
/assign @xiaofan-luan 
/unassign
