### ISSUE TITLE
[Bug]: Create indexes failed when created for different fields

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#19972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:e8cf049
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev54
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Create indexes failed when created for different fields.

### Expected Behavior

Succeed

### Steps To Reproduce

Run:
```python
    @pytest.mark.tags(CaseLabel.L1)
    def test_index_create_indexes_for_different_fields(self):
        """
        target: Test create indexes for different fields
        method: create two different indexes
        expected: create successfully
        """
        collection_w = self.init_collection_general(prefix, True, is_index=True)[0]
        default_index = {"index_type": "IVF_FLAT", "params": {"nlist": 128}, "metric_type": "L2"}
        collection_w.create_index(default_field_name, default_index)
        collection_w.create_index(ct.default_int64_field_name, {})

```

**Comment by xiaocai2333** [comment]
[pr1202](https://github.com/milvus-io/pymilvus/pull/1202)  will fix it, wait for publish success.

**Comment by xiaocai2333** [comment]
The reason is that the index name is not specified when creating an index for different fields, and `_default_idx` will be filled in by default in pymivlus, resulting in the use of the same index_name to create an index for different fields. So failed.

**Comment by xiaocai2333** [comment]
pr [19998](https://github.com/milvus-io/milvus/pull/19998)  will fix it.

![image](https://user-images.githubusercontent.com/46207236/197378450-66ed6693-b13a-42e6-9d64-6a25aa6a4b05.png)

**Comment by NicoYuan1986** [comment]
Fixed!
