### ISSUE TITLE
index file missed after compact

### ISSUE THREAD

**Issue by cydrain** [milvus-io/milvus#1997]
**Describe the bug**
index file missed after compact

**Steps/Code to reproduce behavior**
1. create collection dimension=512, metric_type=L2, index_file_size=1024
2. insert 100000 vectors
3. flush
4. create sq8 index, we can see there are two files recorded in meta, one is raw file, the other is index file
5. delete some vectors by id
6. compact
7. there is no index file in meta, neither in /milvus/db/tables folder. only a raw file is left

**Expected behavior**
there should be an index file under milvus/db/tables and recorded in meta

**Environment details**

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
fix in pr2108

**Comment by tinkerlin** [comment]
@del-zhenwu regression test
