### ISSUE TITLE
Support using MySQL 8.0 or higher as metadata store on CentOS

### ISSUE THREAD

**Issue by zhupengfly** [milvus-io/milvus#1998]
Milvus元数据后台管理 在 CentOS 系统中暂时不支持 MySQL 8.0 或更高版本，但是CentOS 系统和MySQL 8.0在实际生产中使用的场景是非常多的。

**Comment by JinHai-CN** [comment]
We will fixed it in the future.

**Comment by shengjun1985** [comment]
Let's follow the issue in #3792.
