### ISSUE TITLE
[FEATURE] Delete vectors by ID

### ISSUE THREAD

**Issue by solevarr** [milvus-io/milvus#2]
**Is your feature request related to a problem? Please describe.**
I wish I could use Milvus to find and delete vector by it's corresponding ID. Currently the SDK supports only removing the vectors using the date-time, which is a little bit useless for the following cases; suppose I've inserted a huge dataset of animals and the last image vector of a person was mistakenly added, so in order to remove the last vector I need to remove the whole table. 

**Describe the solution you'd like**
Delete vector by its corresponding ID. 

**Describe alternatives you've considered**
Actually this feature is already implemented in FAISS search engine and the other ones. I think you know that it is possible to remove the ID from the index, using remove_ids()  in FAISS. Is this possible to add the same feature for the Milvus?

**Additional context**
https://github.com/facebookresearch/faiss/wiki/Special-operations-on-indexes

**Comment by JinHai-CN** [comment]
Yes, we already planned to add this feature in the future.
Please check the roadmap: https://milvus.io/docs/en/roadmap/
Any comments are welcome!

**Comment by yhmo** [comment]
This requirement should be given high priority since more people mentioned it.
https://github.com/milvus-io/pymilvus/issues/113

From other community channel we also receive question for this function. I think we should consider design/implement it in the near future.
Reopen this issue.

**Comment by namnh2204** [comment]
I'm still waiting for this feature...

**Comment by yhmo** [comment]
This feature is in tech design phase. We will implement it with the highest priority.

**Comment by yhmo** [comment]
This feature is in tech design phase. We will implement it with the highest priority.

**Comment by yhmo** [comment]
Already implemented in master branch, will be released in 0.7.0
