### ISSUE TITLE
[Bug]: [UT] Failed UT on master -rootcoord

### ISSUE THREAD

**Issue by jennyli-z** [milvus-io/milvus#20008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
UT action runner 

```
[https://github.com/milvus-io/milvus/actions/runs/3309648643/jobs/5463038734](https://github.com/milvus-io/milvus/actions/runs/3309648643/jobs/5463038734)

### Current Behavior

Failed on rootcoord
![image](https://user-images.githubusercontent.com/93511422/197443628-b4b72da9-4b2b-40bb-b23f-5958e6b49085.png)

### Expected Behavior

should pass

### Milvus Log

[logs_93788.zip](https://github.com/milvus-io/milvus/files/9848694/logs_93788.zip)

**Comment by longjiquan** [comment]
Close this since this issue has been fixed already.
/close
