### ISSUE TITLE
[Bug]: When insert data into milvus table and reload data, the performance is descreased.

### ISSUE THREAD

**Issue by dzqoo** [milvus-io/milvus#20012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.2
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 24GB querynode memory
- GPU: 
- Others:
```

### Current Behavior

When insert data into milvus table , I found that search performance is decreased seriously.And I reloaded the table ，BUT the performance get worse.I found that some Growing segments are empty as you see below.
![image](https://user-images.githubusercontent.com/8862305/197445682-15a4cb06-35da-45ac-96e6-386e66941e23.png)
![image](https://user-images.githubusercontent.com/8862305/197445715-0aa7f867-a6e4-4ce9-9f22-0fcad5d148b7.png)

Here are the all logs.
-- milvus component logs:
[milvus-log.tar .gz](https://github.com/milvus-io/milvus/files/9848670/milvus-log.tar.gz)

-- birdwatcher logs(table name is photosearch_topic_onehot_128_02_03):
[bw_etcd_ALL.221024-115630.bak.gz](https://github.com/milvus-io/milvus/files/9848673/bw_etcd_ALL.221024-115630.bak.gz)

**Comment by yanliang567** [comment]
the following 3 segments were compacted:
![image](https://user-images.githubusercontent.com/82361606/197523865-d981abe7-8152-478f-9c4b-c28b8edc4768.png)
 but they are still be searched
`[2022/10/24 11:38:57.716 +00:00] [DEBUG] [querynode/segment.go:333] ["do search on segment done"] [msgID=436888919839429183] [segmentID=436846452445806593] [segmentType=Growing] [loadIndex=false]`

**Comment by yanliang567** [comment]
from @dzqoo : he inserted 5 million data again last night, and find the search latency become worse. What's more the index tasks seem to be stuck...always in progress as screenshot below:
<img width="925" alt="image" src="https://user-images.githubusercontent.com/82361606/197667093-61b6c97d-a3d1-40d9-afb9-69496dc738b1.png">

**Comment by yanliang567** [comment]
the growing segments will be sealed and handoff with indexed segments, it was not an issue any more.
