### ISSUE TITLE
[Enhancement]: LRU cache should be cleaned.

### ISSUE THREAD

**Issue by dixingxing0** [milvus-io/milvus#20016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

we found querynode create more than 1000 goroutine for `evictedWorker`, we think the lru cache should be cleaned after collection has been dropped.

### Anything else?

[goroutine-qn-25.zip](https://github.com/milvus-io/milvus/files/9848911/goroutine-qn-25.zip)

**Comment by congqixia** [comment]
After this pr (#19546), chunk manager not long depends on the `ctx` passed during initialization. So the `close` method shall be called explicitly. Thanks for pointing out! @dixingxing0 
/assign
