### ISSUE TITLE
[Bug]:使用centos 无法连接到milvus server

### ISSUE THREAD

**Issue by shuoshuo09** [milvus-io/milvus#20015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.4
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus v2.1.0
- OS(Ubuntu or CentOS): CentrOS
- CPU/Memory: 
- GPU: 15000mb
- Others:
```

### Current Behavior

Execute using cenos sudo yum install https://github.com/milvus-io/milvus/releases/download/v2.1.4/milvus-2.1.4-1.el7.x86_64.rpm Then run sudo systemctl start milvus 服务正常启动，但是无法用 from pymilvus import connections
connections.connect(host='127.0.0.1', port='19530') 链接

Traceback (most recent call last):
File "/Users/d1dx/opt/anaconda3/envs/milvus02/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 115, in _wait_for_channel_ready
grpc.channel_ready_future(self._channel).result(timeout=3)
File "/Users/d1dx/opt/anaconda3/envs/milvus02/lib/python3.8/site-packages/grpc/_utilities.py", line 139, in result
self._block(timeout)
File "/Users/d1dx/opt/anaconda3/envs/milvus02/lib/python3.8/site-packages/grpc/_utilities.py", line 85, in _block
raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/examples-0.7/learn_.py", line 11, in
connections.connect(host='127.0.0.1', port='19530')
File "/Users/d1dx/opt/anaconda3/envs/milvus02/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 262, in connect
connect_milvus(**kwargs, password=password)
File "/Users/d1dx/opt/anaconda3/envs/milvus02/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 233, in connect_milvus
gh._wait_for_channel_ready()
File "/Users/d1dx/opt/anaconda3/envs/milvus02/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 118, in _wait_for_channel_ready
raise MilvusException(Status.CONNECT_FAILED, f'Fail connecting to server on {self._address}. Timeout')
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on 127.0.0.1:19530. Timeout)>

**Comment by yanliang567** [comment]
/assign @Bennu-Li 
do we need to forward the localhost ip address with rpm installation?

/unassign

**Comment by shuoshuo09** [comment]
> /assign @Bennu-Li do we need to forward the localhost ip address with rpm installation?
> 
> /unassign

How do I operate it？

**Comment by LoveEachDay** [comment]
@shuoshuo09 Could you run `lsof -i:19530` to verify that milvus is running well?

**Comment by Bennu-Li** [comment]
@shuoshuo09 And could you run `systemctl status milvus`  to check that milvus status is well?

**Comment by Bennu-Li** [comment]
> /assign @Bennu-Li do we need to forward the localhost ip address with rpm installation?
> 
> /unassign

NO, it does not need to

**Comment by shuoshuo09** [comment]
> Could you run `lsof -i:19530` to verify that milvus is running well?

It was executed without any reaction or error

**Comment by shuoshuo09** [comment]
> 

Is in the green running state

**Comment by shuoshuo09** [comment]
I connected with the port number 19531, but there was another error

**Comment by LoveEachDay** [comment]
@shuoshuo09 port 19531 is for milvus querycoord. You need to access the `:19530` for grpc access which almost all sdks using this port, and `:9091` for rest api access.

Could you upload the milvus service log? And could you run the following command and paste the results:
```
lsof -p <milvus-pid> -n -p
```

And for the default installation, milvus will listen to the following ports:
```
milvus-se 2615297 root   26u     IPv6           52709365       0t0        TCP *:53100 (LISTEN)
milvus-se 2615297 root   28u     IPv6           52782537       0t0        TCP *:19531 (LISTEN)
milvus-se 2615297 root   30u     IPv6           52765260       0t0        TCP *:19529 (LISTEN)
milvus-se 2615297 root   32u     IPv6           52765262       0t0        TCP *:19530 (LISTEN)
milvus-se 2615297 root   33u     IPv6           52747780       0t0        TCP *:21123 (LISTEN)
milvus-se 2615297 root   35u     IPv6           52725528       0t0        TCP *:13333 (LISTEN)
milvus-se 2615297 root   37u     IPv6           52772465       0t0        TCP *:21121 (LISTEN)
milvus-se 2615297 root   38u     IPv6           52778141       0t0        TCP *:9091 (LISTEN)
milvus-se 2615297 root   39u     IPv6           52783232       0t0        TCP *:21124 (LISTEN)
milvus-se 2615297 root   40u     IPv6           52771449       0t0        TCP *:31000 (LISTEN)
```
