### ISSUE TITLE
[Bug]: milvus单机版频繁宕机

### ISSUE THREAD

**Issue by liu7A** [milvus-io/milvus#20020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.1.4
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): java sdk 2.1.0
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 8cpu 8gMemory
- GPU: no
- Others: use -> docker compose -f standalone.yaml
```

### Current Behavior

1. 单机版 docker compose 运行， milvus v2.1.4 
2. java sdk，创建一个集合。有分区没有索引。 字段：字符串id，二进制向量(长度1024)。（此时集合数据为空）
3. 立刻loadCollection
4. 插入1000条数据，二进制向量是分子smiles转化的java.nio.ByteBuffer;
5. 啥也没干，一直挂机40分钟。然后milvus容器停止。

### Steps To Reproduce

```markdown
1. 单机版 docker compose 运行， milvus v2.1.4 
2. java sdk，创建一个集合。有分区没有索引。 字段：字符串id，二进制向量(长度1024)。（此时集合数据为空）
3. 立刻loadCollection
4. 插入1000条数据，二进制向量是分子smiles转化的java.nio.ByteBuffer;
5. 啥也没干，一直挂机40分钟。然后milvus容器停止。
```

### Milvus Log

milvus-standalone  | [2022/10/24 06:40:18.831 +00:00] [INFO] [querynode/partition.go:104] ["remove a segment from replica"] [collectionID=436887048990752769] [partitionID=436887049567207425] [segmentID=436887055413018626] [segmentType=Growing]
milvus-standalone  | [2022/10/24 06:40:18.831 +00:00] [INFO] [querynode/segment.go:237] ["delete segment from memory"] [collectionID=436887048990752769] [partitionID=436887049567207425] [segmentID=436887055413018626] [segmentType=Growing]
milvus-standalone  | [2022/10/24 06:40:18.831 +00:00] [INFO] [querynode/partition.go:104] ["remove a segment from replica"] [collectionID=436887048990752769] [partitionID=436887049567207425] [segmentID=436887056272588801] [segmentType=Growing]
milvus-standalone  | [2022/10/24 06:40:18.832 +00:00] [INFO] [querynode/segment.go:237] ["delete segment from memory"] [collectionID=436887048990752769] [partitionID=436887049567207425] [segmentID=436887056272588801] [segmentType=Growing]
milvus-standalone  | [2022/10/24 06:40:18.832 +00:00] [INFO] [querynode/partition.go:104] ["remove a segment from replica"] [collectionID=436887048990752769] [partitionID=436887049567207425] [segmentID=436887056823091202] [segmentType=Growing]
milvus-standalone  | [2022/10/24 06:40:18.832 +00:00] [INFO] [querynode/segment.go:237] ["delete segment from memory"] [collectionID=436887048990752769] [partitionID=436887049567207425] [segmentID=436887056823091202] [segmentType=Growing]
milvus-standalone  | [2022/10/24 06:40:18.832 +00:00] [INFO] [querynode/partition.go:104] ["remove a segment from replica"] [collectionID=436887048990752769] [partitionID=436887049567207425] [segmentID=436887057976524801] [segmentType=Growing]
milvus-standalone  | [2022/10/24 06:40:18.832 +00:00] [INFO] [querynode/segment.go:237] ["delete segment from memory"] [collectionID=436887048990752769] [partitionID=436887049567207425] [segmentID=436887057976524801] [segmentType=Growing]
milvus-standalone  | [2022/10/24 06:40:18.832 +00:00] [INFO] [querynode/partition.go:104] ["remove a segment from replica"] [collectionID=436887048990752769] [partitionID=436887049567207425] [segmentID=436887058212454402] [segmentType=Growing]
milvus-standalone  | [2022/10/24 06:40:18.832 +00:00] [INFO] [querynode/segment.go:237] ["delete segment from memory"] [collectionID=436887048990752769] [partitionID=436887049567207425] [segmentID=436887058212454402] [segmentType=Growing]
milvus-standalone  | [2022/10/24 06:40:18.832 +00:00] [INFO] [querynode/partition.go:104] ["remove a segment from replica"] [collectionID=436887048990752769] [partitionID=436887049567207425] [segmentID=436887059890176001] [segmentType=Growing]
milvus-standalone  | [2022/10/24 06:40:18.833 +00:00] [INFO] [querynode/segment.go:237] ["delete segment from memory"] [collectionID=436887048990752769] [partitionID=436887049567207425] [segmentID=436887059890176001] [segmentType=Growing]
milvus-standalone  | [2022/10/24 06:40:18.851 +00:00] [INFO] [querynode/collection.go:352] ["delete collection"] [collectionID=436887048990752769]
milvus-standalone  | {"level":"warn","ts":"2022-10-24T06:40:18.853Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000266e00/#initially=[etcd:2379]","attempt":0,"error":"rpc error: code = NotFound desc = etcdserver: requested lease not found"}
milvus-etcd        | {"level":"warn","ts":"2022-10-24T06:40:18.852Z","caller":"etcdserver/util.go:123","msg":"failed to apply request","took":"49.254µs","request":"header:<ID:7587866119658395229 > lease_revoke:<id:694d84089975c85e>","response":"size:29","error":"lease not found"}
milvus-standalone  | [2022/10/24 06:40:18.851 +00:00] [WARN] [querynode/query_shard_service.go:128] ["Close query shard service"]
milvus-standalone  | [2022/10/24 06:40:18.851 +00:00] [WARN] [querynode/query_shard_service.go:128] ["Close query shard service"]
milvus-standalone  | [2022/10/24 06:40:18.854 +00:00] [WARN] [querynode/shard_segment_detector.go:122] ["SegmentDetector event channel closed"]
milvus-standalone  | [2022/10/24 06:40:18.854 +00:00] [WARN] [querynode/shard_segment_detector.go:122] ["SegmentDetector event channel closed"]
milvus-standalone  | [2022/10/24 06:40:18.854 +00:00] [WARN] [querynode/shard_node_detector.go:142] ["event ch closed"]
milvus-standalone  | [2022/10/24 06:40:18.854 +00:00] [WARN] [querynode/shard_segment_detector.go:122] ["SegmentDetector event channel closed"]
milvus-standalone  | [2022/10/24 06:40:18.854 +00:00] [WARN] [querynode/shard_node_detector.go:142] ["event ch closed"]
milvus-standalone  | [2022/10/24 06:40:18.855 +00:00] [WARN] [querynode/shard_segment_detector.go:122] ["SegmentDetector event channel closed"]
milvus-standalone  | [2022/10/24 06:40:18.855 +00:00] [WARN] [querynode/shard_node_detector.go:142] ["event ch closed"]
milvus-standalone  | [2022/10/24 06:40:18.855 +00:00] [WARN] [querynode/shard_segment_detector.go:122] ["SegmentDetector event channel closed"]
milvus-standalone  | [2022/10/24 06:40:18.855 +00:00] [WARN] [querynode/shard_node_detector.go:142] ["event ch closed"]
milvus-standalone  | [2022/10/24 06:40:18.855 +00:00] [WARN] [querynode/shard_segment_detector.go:122] ["SegmentDetector event channel closed"]
milvus-standalone  | [2022/10/24 06:40:18.855 +00:00] [WARN] [querynode/shard_node_detector.go:142] ["event ch closed"]
milvus-standalone  | [2022/10/24 06:40:18.855 +00:00] [WARN] [querynode/shard_segment_detector.go:122] ["SegmentDetector event channel closed"]
milvus-standalone  | [2022/10/24 06:40:18.855 +00:00] [WARN] [querynode/shard_node_detector.go:142] ["event ch closed"]
milvus-standalone  | [2022/10/24 06:40:18.855 +00:00] [WARN] [querynode/shard_segment_detector.go:122] ["SegmentDetector event channel closed"]
milvus-standalone  | [2022/10/24 06:40:18.855 +00:00] [WARN] [querynode/shard_node_detector.go:142] ["event ch closed"]
milvus-standalone  | [2022/10/24 06:40:18.855 +00:00] [WARN] [querynode/shard_segment_detector.go:122] ["SegmentDetector event channel closed"]
milvus-standalone  | [2022/10/24 06:40:18.855 +00:00] [WARN] [querynode/shard_node_detector.go:142] ["event ch closed"]
milvus-etcd        | {"level":"warn","ts":"2022-10-24T06:40:18.857Z","caller":"etcdserver/util.go:123","msg":"failed to apply request","took":"82.39µs","request":"header:<ID:7587866119658395230 > lease_revoke:<id:694d84089975c85e>","response":"size:29","error":"lease not found"}
milvus-standalone  | [2022/10/24 06:40:18.857 +00:00] [WARN] [querynode/shard_node_detector.go:142] ["event ch closed"]
milvus-standalone  | [2022/10/24 06:40:18.857 +00:00] [WARN] [querynode/shard_segment_detector.go:122] ["SegmentDetector event channel closed"]
milvus-standalone  | [2022/10/24 06:40:18.857 +00:00] [WARN] [querynode/shard_node_detector.go:142] ["event ch closed"]
milvus-standalone  | [2022/10/24 06:40:18.857 +00:00] [WARN] [querynode/shard_segment_detector.go:122] ["SegmentDetector event channel closed"]
milvus-standalone  | [2022/10/24 06:40:18.858 +00:00] [WARN] [querynode/shard_node_detector.go:142] ["event ch closed"]
milvus-standalone  | [2022/10/24 06:40:18.858 +00:00] [WARN] [querynode/shard_segment_detector.go:122] ["SegmentDetector event channel closed"]
milvus-standalone  | [2022/10/24 06:40:18.858 +00:00] [WARN] [querynode/shard_node_detector.go:142] ["event ch closed"]
milvus-standalone  | [2022/10/24 06:40:18.858 +00:00] [WARN] [querynode/shard_segment_detector.go:122] ["SegmentDetector event channel closed"]
milvus-standalone  | [2022/10/24 06:40:18.858 +00:00] [WARN] [querynode/shard_node_detector.go:142] ["event ch closed"]
milvus-standalone  | [2022/10/24 06:40:18.858 +00:00] [WARN] [querynode/shard_segment_detector.go:122] ["SegmentDetector event channel closed"]
milvus-standalone  | [2022/10/24 06:40:18.858 +00:00] [WARN] [querynode/shard_node_detector.go:142] ["event ch closed"]
milvus-standalone  | [2022/10/24 06:40:18.859 +00:00] [WARN] [querynode/shard_segment_detector.go:122] ["SegmentDetector event channel closed"]
milvus-standalone  | {"level":"warn","ts":"2022-10-24T06:40:18.860Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000266e00/#initially=[etcd:2379]","attempt":0,"error":"rpc error: code = NotFound desc = etcdserver: requested lease not found"}
milvus-standalone  | [2022/10/24 06:40:18.859 +00:00] [WARN] [querynode/shard_node_detector.go:142] ["event ch closed"]
milvus-standalone  | [2022/10/24 06:40:18.859 +00:00] [WARN] [querynode/shard_segment_detector.go:122] ["SegmentDetector event channel closed"]
milvus-standalone  | [2022/10/24 06:40:18.859 +00:00] [WARN] [querynode/shard_node_detector.go:142] ["event ch closed"]
milvus-standalone  | [2022/10/24 06:40:18.860 +00:00] [DEBUG] [querycoord/service.go:283] ["QueryCoord stop"] [Address=172.18.0.4:19531]
milvus-standalone  | [2022/10/24 06:40:18.860 +00:00] [INFO] [querycoord/query_coord.go:266] ["close scheduler..."]
milvus-standalone  | [2022/10/24 06:40:18.861 +00:00] [INFO] [querycoord/query_coord.go:271] ["close index checker..."]
milvus-standalone  | [2022/10/24 06:40:18.861 +00:00] [DEBUG] [proxy/service.go:502] ["Proxy stop"] ["internal address"=172.18.0.4:19529] ["external address"=172.18.0.4:19529]
milvus-standalone  | [2022/10/24 06:40:18.861 +00:00] [DEBUG] [proxy/service.go:520] ["Graceful stop grpc internal server..."]
milvus-standalone  | [2022/10/24 06:40:18.862 +00:00] [DEBUG] [proxy/service.go:524] ["Graceful stop grpc external server..."]
milvus-standalone  | [2022/10/24 06:40:18.864 +00:00] [INFO] [proxy/proxy.go:354] ["close id allocator"] [role=proxy]
milvus-standalone  | [2022/10/24 06:40:18.864 +00:00] [INFO] [proxy/proxy.go:359] ["close segment id assigner"] [role=proxy]
milvus-standalone  | [2022/10/24 06:40:18.864 +00:00] [INFO] [proxy/proxy.go:364] ["close scheduler"] [role=proxy]
milvus-standalone  | [2022/10/24 06:40:18.864 +00:00] [INFO] [proxy/proxy.go:372] ["close channels time ticker"] [role=proxy]
milvus-etcd        | {"level":"warn","ts":"2022-10-24T06:40:18.865Z","caller":"etcdserver/util.go:123","msg":"failed to apply request","took":"10.775µs","request":"header:<ID:7587866119658395231 > lease_revoke:<id:694d84089975c889>","response":"size:29","error":"lease not found"}
milvus-standalone  | {"level":"warn","ts":"2022-10-24T06:40:18.865Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000202fc0/#initially=[etcd:2379]","attempt":0,"error":"rpc error: code = NotFound desc = etcdserver: requested lease not found"}
milvus-standalone  | [2022/10/24 06:40:18.866 +00:00] [DEBUG] [rootcoord/service.go:286] ["Rootcoord stop"] [Address=172.18.0.4:53100]
milvus-etcd        | {"level":"warn","ts":"2022-10-24T06:40:18.867Z","caller":"etcdserver/util.go:123","msg":"failed to apply request","took":"8.857µs","request":"header:<ID:7587866119658395232 > lease_revoke:<id:694d84089975c84d>","response":"size:29","error":"lease not found"}
milvus-standalone  | {"level":"warn","ts":"2022-10-24T06:40:18.867Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000266380/#initially=[etcd:2379]","attempt":0,"error":"rpc error: code = NotFound desc = etcdserver: requested lease not found"}
milvus-standalone  | [2022/10/24 06:40:18.867 +00:00] [DEBUG] [rootcoord/service.go:315] ["Rootcoord begin to stop grpc server"]
milvus-standalone  | [2022/10/24 06:40:18.867 +00:00] [DEBUG] [rootcoord/service.go:318] ["Graceful stop grpc server..."]
milvus-standalone  | [2022/10/24 06:40:18.868 +00:00] [DEBUG] [server/global_rmq.go:88] ["Close Rocksmq!"]
milvus-standalone  | [2022/10/24 06:40:18.868 +00:00] [WARN] [server/rocksmq_retention.go:110] ["Rocksmq retention finish!"]
milvus-standalone  | [2022/10/24 06:40:18.868 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_7] [group=by-dev-dataNode-6-436887048990752769] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.868 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_7] [group=by-dev-queryNode-436887048990752769-4] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.868 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_0] [group=by-dev-dataNode-6-436887048990752769] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.868 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_0] [group=by-dev-queryNode-436887048990752769-4] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.869 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_13] [group=by-dev-dataNode-6-436887048990752769] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.869 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_13] [group=by-dev-queryNode-436887048990752769-4] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.869 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_14] [group=by-dev-dataNode-6-436887048990752769] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.869 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_14] [group=by-dev-queryNode-436887048990752769-4] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.869 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_11] [group=by-dev-dataNode-6-436887048990752769] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.869 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_11] [group=by-dev-queryNode-436887048990752769-4] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.869 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-datacoord-timetick-channel] [group=by-dev-dataCoord] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.869 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_1] [group=by-dev-dataNode-6-436887048990752769] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.869 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_1] [group=by-dev-queryNode-436887048990752769-4] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.869 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_9] [group=by-dev-dataNode-6-436887048990752769] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.869 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_9] [group=by-dev-queryNode-436887048990752769-4] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.869 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_2] [group=by-dev-dataNode-6-436887048990752769] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.870 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_2] [group=by-dev-queryNode-436887048990752769-4] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.870 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_12] [group=by-dev-dataNode-6-436887048990752769] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.870 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_12] [group=by-dev-queryNode-436887048990752769-4] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.870 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_3] [group=by-dev-dataNode-6-436887048990752769] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.870 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_3] [group=by-dev-queryNode-436887048990752769-4] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.870 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_5] [group=by-dev-dataNode-6-436887048990752769] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.870 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_5] [group=by-dev-queryNode-436887048990752769-4] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.870 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_6] [group=by-dev-dataNode-6-436887048990752769] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.870 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_6] [group=by-dev-queryNode-436887048990752769-4] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.870 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_8] [group=by-dev-dataNode-6-436887048990752769] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.870 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_8] [group=by-dev-queryNode-436887048990752769-4] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.870 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_10] [group=by-dev-dataNode-6-436887048990752769] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.870 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_10] [group=by-dev-queryNode-436887048990752769-4] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.871 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_4] [group=by-dev-dataNode-6-436887048990752769] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.871 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_4] [group=by-dev-queryNode-436887048990752769-4] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.871 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_15] [group=by-dev-dataNode-6-436887048990752769] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.871 +00:00] [DEBUG] [server/rocksmq_impl.go:502] ["Rocksmq destroy consumer group successfully "] [topic=by-dev-rootcoord-dml_15] [group=by-dev-queryNode-436887048990752769-4] [elapsed=0]
milvus-standalone  | [2022/10/24 06:40:18.908 +00:00] [INFO] [server/rocksmq_impl.go:275] ["Successfully close rocksmq"]
milvus-standalone  | panic: close of closed channel
milvus-standalone  | 	panic: close of closed channel
milvus-standalone  | 
milvus-standalone  | goroutine 1 [running]:
milvus-standalone  | github.com/milvus-io/milvus/internal/querycoord.(*HandoffHandler).Stop(0xc00173b7a0)
milvus-standalone  | 	/go/src/github.com/milvus-io/milvus/internal/querycoord/handoff_handler.go:123 +0x3d
milvus-standalone  | github.com/milvus-io/milvus/internal/querycoord.(*QueryCoord).Stop(0xc0003f7040, 0x0, 0x0)
milvus-standalone  | 	/go/src/github.com/milvus-io/milvus/internal/querycoord/query_coord.go:272 +0x1c5
milvus-standalone  | github.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).Stop(0xc000be0320, 0x0, 0x0)
milvus-standalone  | 	/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:292 +0x236
milvus-standalone  | github.com/milvus-io/milvus/cmd/components.(*QueryCoord).Stop(0xc0001666d8, 0x203000, 0x85ce5b)
milvus-standalone  | 	/go/src/github.com/milvus-io/milvus/cmd/components/query_coord.go:59 +0x2f
milvus-standalone  | panic(0x3cdf240, 0x434e550)
milvus-standalone  | 	/usr/local/go/src/runtime/panic.go:971 +0x499
milvus-standalone  | github.com/milvus-io/milvus/internal/indexcoord.(*indexBuilder).Stop(0xc00013dc70)
milvus-standalone  | 	/go/src/github.com/milvus-io/milvus/internal/indexcoord/index_builder.go:72 +0x3d
milvus-standalone  | github.com/milvus-io/milvus/internal/indexcoord.(*IndexCoord).Stop(0xc000bdac60, 0x0, 0x0)
milvus-standalone  | 	/go/src/github.com/milvus-io/milvus/internal/indexcoord/index_coord.go:302 +0x165
milvus-standalone  | github.com/milvus-io/milvus/internal/distributed/indexcoord.(*Server).Stop(0xc000b945b0, 0x0, 0x0)
milvus-standalone  | 	/go/src/github.com/milvus-io/milvus/internal/distributed/indexcoord/service.go:173 +0x2e7
milvus-standalone  | github.com/milvus-io/milvus/cmd/components.(*IndexCoord).Stop(0xc0008ebc10, 0x20, 0x7f9475002108)
milvus-standalone  | 	/go/src/github.com/milvus-io/milvus/cmd/components/index_coord.go:57 +0x2e
milvus-standalone  | github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run(0xc000a0cf60, 0xc000010001, 0x0, 0x0)
milvus-standalone  | 	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:528 +0x5c5
milvus-standalone  | github.com/milvus-io/milvus/cmd/milvus.(*run).execute(0xc0003c6d50, 0xc00004e090, 0x3, 0x3, 0xc0003b2420)
milvus-standalone  | 	/go/src/github.com/milvus-io/milvus/cmd/milvus/run.go:111 +0x496
milvus-standalone  | github.com/milvus-io/milvus/cmd/milvus.RunMilvus(0xc00004e090, 0x3, 0x3)
milvus-standalone  | 	/go/src/github.com/milvus-io/milvus/cmd/milvus/milvus.go:60 +0x162
milvus-standalone  | main.main()
milvus-standalone  | 	/go/src/github.com/milvus-io/milvus/cmd/main.go:26 +0x45

**Comment by jiaoew1991** [comment]
By the way, plz translate the title and content into English
