### ISSUE TITLE
[Bug]: CI tests, QueryNode panic occasionally

### ISSUE THREAD

**Issue by bigsheeper** [milvus-io/milvus#20033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/42060877/197523539-055951bc-1b0b-4921-853d-ea9074b3d899.png)

### Steps To Reproduce

```markdown
`pytest --tags L2`
```

**Comment by yah01** [comment]
/assign @congqixia 
looks like caused by a recent PR
