### ISSUE TITLE
Question for HNSW Indexing size

### ISSUE THREAD

**Issue by dwang-sflscientific** [milvus-io/milvus#2005]
**What is your question?**
Right now I am using HNSW to index 10M vectors using the following hyperparameters:

CPU cach limit: 50GB
Vector DIM = 1024
_INDEX_FILE_SIZE = 4096
M = 16
efConstruction = 500
Upload_batch_size: 500K vectors.

The estimated raw vector size should be:
4byte * 1024 * 10M = 40GB.

After indexing, the *.rv files in `db/table/collection_name/` folder is ~20GB, the indexing files in `db/table/collection_name/` folder` is about 75GB.

My questions are:
1. when I do query first time, htop shows only 14GB memory is cached : though my CPU cache limit is 50GB?
2. Why the index file size is greater than the estimated raw vector size(75GB v.s. 40GB)
3. why the *.rv file size is only half of the estimated raw vector size(20GB v.s. 40GB)

Any help is really appreciated!

**Comment by tinkerlin** [comment]
Can you give some more detail info ? 
How long have you observed this situation after call `create_index`?  And how about now?

Milvus keep merging inserted raw data, and flush to disk(generate .rv file). In this process,  will generate lots of intermediate data files (will remove later) and spend some times. 
This may cause the folder size is greater than the estimated size and .rv file size only a half. lt will return to the expecte size after merge process done. You need to wait for a while.

**Comment by yhmo** [comment]
Typically, for large data set, we can insert vectors by batch(each batch contains about 10000~100000 vectors). Insert action only copy data into memory buffer, a background thread will flush the buffer into disk per second, you also can invoke flush() to force flush data into disk. Example of insert large set data:
insert(100000 vectors)
flush()
insert(100000 vectors)
flush()
insert...
flush...

Each flush action will generate a file on disk, these files are small-size, a background thread in Milvus will merge them into large file(until file size exceed index_file_size). So during insert, the disk cost will larger than raw data size. Until all files merged finish, the disk cost will eventually equal to total raw data size.

 After create_index(), raw data files will not be deleted, index files will cost extra disk space. Different index type has different size, for example:
IVFLAT index size = raw data size
IVFSq8 index size = raw data size * 30%
HNSW index size = raw data size * 200%

**Comment by yhmo** [comment]
I just test on my machine with 200000 vectors using your parameters:

```
insert(100000 vectors)
flush()
insert(100000 vectors)
flush()
```
use `du -h` to calculate disk cost: 8GB
then create HNSW index:
`create_index()`

use `du -h` to calculate disk cost: 24GB

**Comment by dwang-sflscientific** [comment]
@yhmo:  I got similar number:  index size 75GB v.s. estimated data size 40GB. For your experiment, do I need 16GB ram to load the HNSW index to avoid memory swapping?

@tinkerlin: Thanks for your explanation. I did wait for a while and use `htop` to make sure the CPU consumption becomes zero.

@yhmo @tinkerlin: the general question I have now is: looks like the HNSW index is 2X large to raw data size. Does it mean I need 2X more memory to load index entirely into my memory? Right now I am trying to estimate how much memory I need to optimize the query performance.

I am also doing the same experiment using Opendistro KNN(AWS Elasticsearch), which using mnslib HNSW as the backend engine. For AWS Elasticsearch, index size consumed by memory for 100M vectors(400GB) is about 420GB.

**Comment by tinkerlin** [comment]
- To achieve best query performance, the cache must be able to accommodate all the index data. 
- Milvus use [https://github.com/nmslib/hnswlib.git](hnswlib) as the backend engine.
- The HNSW index size can be adjust by build parameter, we suggest users to choose the best param combination by themselves to adapte their own scenarios.

@dwang-sflscientific

**Comment by yhmo** [comment]
@dwang-sflscientific 
For 10M vectors(1024 dim),  total raw data size is 40GB, HNSW index size is about 75GB. So you need at least 150GB ram avoid memory swapping.
I suggest you try the IVFSQ8 index, it only require about 30% space compare to raw data size. That is to say, for 10M vectors(1024 dim), SQ8 index only require 12GB memory space.

**Comment by bhushanbrb** [comment]
@yhmo recommended Index type for 3million X Float Embedding (256 dimensions) is SQ8 index? or FLAT index?

**Comment by vhdmoradi** [comment]
NOT DIRECTLY RELATED, 
But my question is about the indexing size in Qdrant. The reason I ask it here is that it also uses HNSW algorithm.
So, I will have maybe around 10 million products, with dense vectors in 1024 dimensions. I was wondering if I should use memmap storage, or on-memory storage for indexing data. Thinking the indexing data would NOT take that much of space, I first decided to use memory (For now I have 120 GB of memroy, but I can raise it to 300 GB maybe, although rather use a better way), but then did some research and found out that it would not be a negligible number. But could not find a way to determine the indexing size in Qdrant for 10 million vectors indexed by HNSW algo, with 48 layers and 200 neighbours. Is there a general formula or it is different based on the implementation that Qdrant has utilized?
