### ISSUE TITLE
[Bug]: [CI][E2E] e2e failed because of TT Protection issue

### ISSUE THREAD

**Issue by jennyli-z** [milvus-io/milvus#20053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
CI
```

### Current Behavior

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-20038/1/pipeline

<MilvusException: (code=48, message=force to deny /milvus.proto.milvus.MilvusService/Insert.)>

### Expected Behavior

should always pass

### Milvus Log

[artifacts-milvus-distributed-PR-20038-1-pymilvus-e2e-logs.tar.gz](https://github.com/milvus-io/milvus/files/9857087/artifacts-milvus-distributed-PR-20038-1-pymilvus-e2e-logs.tar.gz)

**Comment by bigsheeper** [comment]
/assgin @jennyli-z 
/unassign

this issue should be resolved.
