### ISSUE TITLE
[Bug]: For same entity, fail to query by id(PK),  but succeed to query by vector 

### ISSUE THREAD

**Issue by Roger-Z** [milvus-io/milvus#20102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.4
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

We encountered an issue for querying entity by id, we can query same entity with entity embedding, but get an error (NoSuchKey) to query by id.
![Uploading image.png…]()
![Uploading 60451666757467_.pic.jpg…]()

### Milvus Log

http://rt.ops.cn2.corp.agrant.cn:18000/log/milvus1026.tar.gz
http://rt.ops.cn2.corp.agrant.cn:18000/log/bw_etcd_ALL.221026-164629.bak.gz

**Comment by yanliang567** [comment]
@Roger-Z failed to open the screenshots you attached. Also, could you please share some code snippets for reproducing the issue.
/assign @Roger-Z
