### ISSUE TITLE
Remove '-p 9091:9091' in Step 4 Start Docker container

### ISSUE THREAD

**Issue by fishpenguin** [milvus-io/milvus#2013]
## Report incorrect documentation

**Location of incorrect documentation**
https://github.com/milvus-io/docs/tree/master/site/zh-CN/guides/get_started/install_milvus/cpu_milvus_docker.md

https://github.com/milvus-io/docs/blob/master/site/zh-CN/guides/get_started/install_milvus/gpu_milvus_docker.md

**Describe the problems or issues found in the documentation**
9091 port is used for pushgateway, not for milvus

**Suggested fix for documentation**
Remove '-p 9091:9091' in Step 4 Start Docker container

**Comment by PahudPlus** [comment]
Fixed.
