### ISSUE TITLE
[Bug]: start milvus with docker-compose,milvus-etcd start failed（使用docker 容器启动milvus,milvus-etc组件启动失败）

### ISSUE THREAD

**Issue by gzg25895381** [milvus-io/milvus#20159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.4
- Deployment mode:standalone
- OS:Ubuntu 
- CPU/Memory:4C/8G 
- GPU: T4
- docker:20.10.12
- docker-compose:  1.26.2
```

### Current Behavior

下载的docker-compose.yml为官网提供的命令下载，命令如下：
wget https://github.com/milvus-io/milvus/releases/download/v2.1.4/milvus-standalone-docker-compose.yml -O docker-compose.yml
docker 版本：20.10.12
docker-compose 版本：docker-compose version 1.26.2, build eefe0d31
执行命令（start command）：sudo docker-commpose up -d
执行结果(result):使用 docker-compose ps查看服务状态，milvus-etcd启动失败
使用 sudo docker logs -t -f milvus-etcd 查看milvus-etcd的日志显示结果如下：
2022-10-28T02:20:50.906620469Z exec /usr/local/bin/etcd: exec format error
试过（tryed）：
sudo docker-compose down
sudo rm -rf volumes
sudo docker-compose up -d
问题依然存在（not works）
请问这种问题应该怎么排查，或者从哪个方向入手，谢谢（what can i do next or how to fix this,thanks）

### Expected Behavior

服务能正常启动（its，works）

**Comment by LoveEachDay** [comment]
@gzg25895381 Could you provide the information for cpu architecture? amd64 or arm? Run the following command to check:
```
 lscpu | grep Architecture
```
You'd better use `x86_64` cpu to run milvus.

**Comment by gzg25895381** [comment]
> @gzg25895381 Could you provide the information for cpu architecture? amd64 or arm? Run the following command to check:
> 
> ```
>  lscpu | grep Architecture
> ```
> 
> You'd better use `x86_64` cpu to run milvus.

my sure  the cpu architecture is x86_64, and i have try version 2.1.3 docker-compose.yml  it's report the same error log.
i think maybe my environments some where has problem。 if you has some suggest，plese tell me，thank you！

**Comment by gzg25895381** [comment]
> @gzg25895381 Could you provide the information for cpu architecture? amd64 or arm? Run the following command to check:
> 
> ```
>  lscpu | grep Architecture
> ```
> 
> You'd better use `x86_64` cpu to run milvus.

my sure  the cpu architecture is x86_64, and i have try version 2.1.3 docker-compose.yml  it's report the same error log.
i think maybe my environments some where has problem。 if you has some suggest，plese tell me，thank you！

**Comment by LoveEachDay** [comment]
@gzg25895381 By default the docker-compose will start `etcd` , `minio` and `milvus` containers. How about the `minio` and `milvus` containers?
