### ISSUE TITLE
[Enhancement]: Add option to canclel collection load

### ISSUE THREAD

**Issue by eugeneradionov** [milvus-io/milvus#20173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Add an option to cancel the collection load.

### Why is this needed?

I have 75M records in the collection and the Kubernetes cluster with unlimited resources. If I have started the collection load I cannot cancel it. It takes too much time to load (for some reason, idk why exactly) and I want to force release it or cancel loading. But, when I'm trying to release the collection I get infinite loading. As I understand, there is a kind of lock exists, so the "release" call waits until the collection loads.

**Comment by yah01** [comment]
The `master` now supports releasing the loading collection, it will come with v2.2.0
