### ISSUE TITLE
[Bug]: There's memory leak in query results.

### ISSUE THREAD

**Issue by soothing-rain** [milvus-io/milvus#20203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Related to #19526 

There's memory leak where Milvus standalone memory goes up to 40GigBytes with 2 segments and 100,000 rows.

<img width="1445" alt="image" src="https://user-images.githubusercontent.com/69466447/198960999-09b1bcf9-fcdb-46e2-8b03-40baacc4ca49.png">

![79e7d8b1-0c68-4e56-9e28-e50687654316](https://user-images.githubusercontent.com/69466447/198961205-5f815a85-5589-47f9-a22f-93879dbdd4de.jpeg)

![11b5IIugNa](https://user-images.githubusercontent.com/69466447/198961163-682af990-7002-4763-96a3-1b043ae1b6c8.jpg)

**Comment by xiaofan-luan** [comment]
not sure that's really the case?
might only be a jemalloc issue?
