### ISSUE TITLE
[Bug]: Index time takes 4 hours after upsert 20% entities, which is too long

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#20259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20221031-8d0cc422
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
```

### Current Behavior

it takes about 4 hours to build indexes after upsert 20% entities(delete 1million and insert 1 million)
![image](https://user-images.githubusercontent.com/82361606/199392636-15368dd5-3c58-4f4a-8b96-1adc3723caad.png)

### Expected Behavior

complete indexing in less than 1 hour

### Steps To Reproduce

```markdown
1. insert 5m-128d entities and build hnsw
2. delete random 1 million entities and insert 1 million
3. check the index node metrics
```

### Milvus Log

[bw_etcd_ALL.221102-110345.bak.gz](https://github.com/milvus-io/milvus/files/9915845/bw_etcd_ALL.221102-110345.bak.gz)
[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/9915846/milvus-log.tar.gz)

### Anything else?

```
yanliang-cluster-1cu-milvus-datanode-9d777b9f9-4sjdg            1/1     Running     0                 46h
yanliang-cluster-1cu-milvus-indexnode-6bdd68465f-4zzqh          1/1     Running     0                 46h
yanliang-cluster-1cu-milvus-mixcoord-668d45dccc-dlkfk           1/1     Running     0                 46h
yanliang-cluster-1cu-milvus-proxy-589cc54dc6-czgz8              1/1     Running     0                 46h
yanliang-cluster-1cu-milvus-querynode-57f8dc994c-bj7lp          1/1     Running     0                 19h
```

**Comment by longjiquan** [comment]
The machine of indexnode is not good at performance. It even cost 20 min to build hnsw index for a segment with 70w rows.

**Comment by longjiquan** [comment]
![image](https://user-images.githubusercontent.com/31589260/199670954-34ef0fc6-2409-49a8-a3bc-6c90ceef28a4.png)
![image](https://user-images.githubusercontent.com/31589260/199671033-e2e5b091-67ef-4a34-b142-dde405410abb.png)

**Comment by longjiquan** [comment]
btw, the log when building index is a little wrong, i'll fix this.

**Comment by longjiquan** [comment]
the log fixed in #20302

**Comment by xiaofan-luan** [comment]
@longjiquan so it's a won't fix?

**Comment by xiaofan-luan** [comment]
if we could offer some more performance for index build speed of orignal HNSW that would be super helpful

**Comment by yanliang567** [comment]
I think the root cause is more about compaction: after upsert 20% data, many segments will be compacted

**Comment by longjiquan** [comment]
Under this case, compaction is reasonable. Also the compacted but not indexed segments won't influence search/query. It will only influence the newly index task since indexnode has a sequence task model. By the way, why not scale the indexnodes if you really need to create index for more collections? @yanliang567

**Comment by yanliang567** [comment]
close for now. 
in 2.2.2, it costs 10-20 minutes to complete the index and compaction, after that, search latency turns back to normal.
