### ISSUE TITLE
[Bug]: search on non_indexed segment while the segment was already indexed

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#20252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20221031-8d0cc422
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
```

### Current Behavior

the search latency keeps high after upsert 20% entities, and found it is still searching on the non_indexed segments, even the segments completed building index already.
![image](https://user-images.githubusercontent.com/82361606/199384798-d40614de-98ee-4086-a113-7d57130787ce.png)

### Expected Behavior

handoff replaces the non_indexed segments with indexed ones, and the search latency becomes faster.

### Steps To Reproduce

```markdown
1. insert 5 million entities and build hnsw index
2. search a client to keep searching permanently 
3. start a new client to upsert 20% entities(delete 1m and then inset 1m)
4. check the search latency
```

### Milvus Log

in querynode, it says that the following 3 segments are loadIndex=flase:
```
[2022/11/02 02:19:16.803 +00:00] [DEBUG] [querynode/segment.go:375] ["do search on segment done"] [msgID=437087255049535489] [segmentID=437042918730979898] [segmentType=2] [loadIndex=false]
[2022/11/02 02:19:16.803 +00:00] [DEBUG] [querynode/segment.go:375] ["do search on segment done"] [msgID=437087254997368833] [segmentID=437042918730979899] [segmentType=2] [loadIndex=false]
...
[2022/11/02 02:19:16.924 +00:00] [DEBUG] [querynode/segment.go:375] ["do search on segment done"] [msgID=437087255049535489] [segmentID=437042918730379665] [segmentType=2] [loadIndex=false]
...
```
Actually they completed indexed already.
```
SegmentID: 437042918730979898	 State: Flushed
	IndexV2 build ID: 437042918730980691, states Finished
SegmentID: 437042918730979899	 State: Flushed
	IndexV2 build ID: 437042918730980689, states Finished
```

### Anything else?

[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/9915551/milvus-log.tar.gz)

**Comment by yanliang567** [comment]
[bw_etcd_ALL.221102-110345.bak.gz](https://github.com/milvus-io/milvus/files/9915575/bw_etcd_ALL.221102-110345.bak.gz)

**Comment by congqixia** [comment]
From the log I found:
```
  | [2022/11/02 05:04:46.622 +00:00] [WARN] [task/executor.go:177] ["failed to load segment"] [taskIDs="[1380,1383,1384,1385,1387,1369,1370,1373,1375,1376]"] [collectionID=437042918722571686] [segmentIDs="[437042918730980535,437042918730979898,437042918730982076,437042918731010287,437042918731101371,437042918730379697,437042918730379665,437042918730979935,437042918730980123,437042918730980195]"] [nodeID=38] [source=2] [reason="follower 38 failed to load segment, reason load segment failed, OOM if load, collectionID = 437042918722571686, maxSegmentSize = 518 MB, concurrency = 1, usedMemAfterLoad = 9779 MB, totalMem = 8192 MB, thresholdFactor = 0.900000"]
```
So the handoff did not actually happened, since there is no enough memory to load indexed sealed segment.

**Comment by yanliang567** [comment]
so sounds like we need to figure out a better solution, or maybe update the value of thresholdFactor?

**Comment by xiaofan-luan** [comment]
It seems that the memory usage is already high(above 7 Gigabytes)

and load 512M  segment need extra 2G memory which might be a little too much.

have one implementation here to improve resource calculation. but still the memory budget seems to be really tight.
https://github.com/milvus-io/milvus/pull/20246

**Comment by xiaofan-luan** [comment]
related to #20245

**Comment by yanliang567** [comment]
Verified on 2.2.0-20221124-925fa9d4: small segments(<16MB) will be sealed in segment.maxLife, but we can manually flush the collection to seal them. After that these segments would be automatically indexed and handoff to querynode
