### ISSUE TITLE
Query result is incomplete

### ISSUE THREAD

**Issue by hanqiushi** [milvus-io/milvus#20262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.4
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. java-milvus v2.1.0):
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 64G
- GPU: 
- Others:
```

### Current Behavior

The collection params:
![image](https://user-images.githubusercontent.com/1206528/199425949-cd33d636-8362-4555-89ad-e98c14fa89fe.png)
Use flat index.

Preparation:
I inserted 2 items, all other params are equal except param group

Query params & results:
Using param face:
![image](https://user-images.githubusercontent.com/1206528/199426060-be572f58-0963-4d97-8858-5f2f2d49d64d.png)
Using param group:
![image](https://user-images.githubusercontent.com/1206528/199426395-40e92807-b4a2-4044-a25b-78fb905eba90.png)
Using param face & group:
![image](https://user-images.githubusercontent.com/1206528/199427159-05a035d4-7c2b-4695-8620-bd4c21f135a8.png)

### Expected Behavior

When I use face param to query, the expected result should contain 2 items, but now only 1 item returned
After I use face & group param to query, the result is right

### Steps To Reproduce

```markdown
Same as behavior
```

**Comment by hanqiushi** [comment]
[querynode/result.go:280] ["skip duplicated query result"] [count=1]
I see this log when query, seems it is intended to skip duplicated result.
The question is, what is duplicated result ? And how can I query multiple results ?

**Comment by hanqiushi** [comment]
![image](https://user-images.githubusercontent.com/1206528/199437345-be839f23-adde-4f8c-a20b-e29cac225c6f.png)
Should I add an unique ID as primary key ?

**Comment by yanliang567** [comment]
I think 'face' is the primary key, and you shall insert data with unique primary key. @hanqiushi

**Comment by hanqiushi** [comment]
> I think 'face' is the primary key, and you shall insert data with unique primary key. @hanqiushi

You are right, thanks for pointing it out
