### ISSUE TITLE
[Bug]: cluster Failed to start

### ISSUE THREAD

**Issue by S-Dragon0302** [milvus-io/milvus#20272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.4
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

链接: https://pan.baidu.com/s/1qGxA5TdvJreRqSfvFSVNeQ 提取码: ac4i 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by yanliang567** [comment]
it seems that the rootcoord is unhealthy.
```
time="2022-11-02T08:17:43Z" level=info msg="[TCP connection established]" local_addr="10.255.80.54:53904" remote_addr="pulsar://10.100.7.20:6650"
time="2022-11-02T08:17:43Z" level=info msg="[Connection is ready]" local_addr="10.255.80.54:53904" remote_addr="pulsar://10.100.7.20:6650"
[2022/11/02 08:18:13.633 +00:00] [DEBUG] [retry/retry.go:39] ["retry func failed"] ["retry time"=0] [error="request timed out"]
[2022/11/02 08:19:19.786 +00:00] [DEBUG] [rootcoord/root_coord.go:1450] [GetComponentStates] ["State Code"=Initializing]
[2022/11/02 08:19:19.786 +00:00] [WARN] [roles/healthz_handler.go:100] ["component is unhealthy"] [state=Initializing]
[2022/11/02 08:19:29.786 +00:00] [DEBUG] [rootcoord/root_coord.go:1450] [GetComponentStates] ["State Code"=Initializing]
```
/assign @jiaoew1991 
/unassign

**Comment by jiaoew1991** [comment]
Hi @S-Dragon0302 could you provide a goroutine dump for the `RootCoord`? 
you can fetch it by ```curl http://<ip>:9091/debug/pprof/goroutine?debug=1```

**Comment by S-Dragon0302** [comment]
![Uploading image.png…]()

**Comment by S-Dragon0302** [comment]
![image](https://user-images.githubusercontent.com/30819544/201287791-bdd2ff7e-2100-4866-b0e6-9686f5726be3.png)

**Comment by S-Dragon0302** [comment]
链接: https://pan.baidu.com/s/1vngD4E3bXWhjVuui4I08tA 提取码: 2gm3 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by weiliu1031** [comment]
root coord start failed, when it try to create channel on pulsar during init process, meet `request timeout`,  please check:
1. do you use a new pulsar service which create with milvus, or you reuse your old pulsar service ?
2. please check your pulsar config

**Comment by S-Dragon0302** [comment]
链接: https://pan.baidu.com/s/1W2hOCbnk2ZNx7pWqo0jDrQ 提取码: wiv2 复制这段内容后打开百度网盘手机App，操作更方便哦
