### ISSUE TITLE
[Bug]: build a iamge with  build/build_image.sh  after make milvus in docker , it will raise an exception：

### ISSUE THREAD

**Issue by linggong2011** [milvus-io/milvus#20291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

when I build a iamge with  build/build_image.sh  after make milvus in docker , it will raise an exception：

 > [stage-1  7/10] COPY ./lib/ /milvus/lib/:
------
failed to compute cache key: "/lib" not found: not found

### Expected Behavior

so how to generate /milvus/lib/ ?

**Comment by linggong2011** [comment]
Ubuntu

**Comment by jiaoew1991** [comment]
Actually you need to build the milvus image using the `builder image` to setup a compile environment otherwise on your local machine, you can try `docker-compose build builder` at the root path of the milvus folder, the default OS value of `builder image` is ubuntu20.04, you can change it at `.env` file

**Comment by linggong2011** [comment]
I just want to build a image like milvusdb/milvus:v2.1.4 from source code，so it can run in my own k8s cluster in distribute mod.
So just to tell me the build commands， Thanks

**Comment by linggong2011** [comment]
BYW，I am using a mac computer to build the image .

**Comment by jiaoew1991** [comment]
You can find the built milvus image here https://hub.docker.com/r/milvusdb/milvus/tags?page=1 @linggong2011

**Comment by linggong2011** [comment]
Thanks

**Comment by aurelianInc** [comment]
@jiaoew1991 I'm trying to build milvus image by running ./build/build_image.sh to test some local changes and running into same error 
`failed to compute cache key: "/lib" not found: not found`
