### ISSUE TITLE
[Bug]: fail to load index, error "no enough memory"

### ISSUE THREAD

**Issue by Roger-Z** [milvus-io/milvus#20356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.4
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

release and load a index with 68m entities, error occur, even there are 320GB memory available in my cluster
![企业微信截图_16676129579891](https://user-images.githubusercontent.com/3478019/200120088-b8ddbce3-16b1-4bf5-8bb3-a5442b6135a0.png)

### Milvus Log

http://rt.ops.cn2.corp.agrant.cn:18000/log/milvus1105.tar.gz

http://rt.ops.cn2.corp.agrant.cn:18000/log/bw_etcd_ALL.221105-201056.bak.gz

**Comment by yanliang567** [comment]
@Roger-Z how much free memory for query nodes left in cluster?

**Comment by xiaofan-luan** [comment]
keep it open, will close if no response later
