### ISSUE TITLE
更换元数据管理后，磁盘占用变高

### ISSUE THREAD

**Issue by zhupengfly** [milvus-io/milvus#2037]
`db_config:
  backend_url: mysql://root:123@10.10.4.19:3306/milvus
  preload_collection:
  auto_flush_interval: 1
`
我将我的元数据管理交给mysql后，发现我的磁盘很快被占用完，之前需要一整天才能占满的磁盘，现在1个小时就被占满了，我尝试把磁盘所有数据清理后再次进行尝试，结果仍然是磁盘很快被占用满。（我使用的是milvus0.8.0）

**Comment by yhmo** [comment]
Please provide more information:
- collection parameters: index_file_size, metric_type, dimension
- index parameters: index type, nlist
- how many vectors were inserted
- use `docker exec -it [container id] bash` command to log into milvus container, got to /var/lib/milvus folder, use `du -h -d 1` to show folder size
- use `mysql -h127.0.0.1 -uroot -p` to connect mysql, then 'select sum(file_size) from TableFiles' to calculate data size.

**Comment by zhupengfly** [comment]
- verson 0.8.0

- index_file_size:1024,metric_type:IP,dimension:512

- index type:IVF_SQ8,nlist:65536

- 215546

- 
![image](https://user-images.githubusercontent.com/25003362/79978972-5f4bf200-84d3-11ea-88a3-59326890a148.png)

- 443873952

**Comment by yhmo** [comment]
Your /milvus/db has 237GB, it is weird. The mysql only record 443MB data size for the 215546 vectors.
Is the "/milvus/db" a clean folder before you start milvus?

**Comment by zhupengfly** [comment]
在启动milvus前，我将对应的文件都是清空了的，生成的文件为什么占用那么多空间，我感觉比较奇怪，我不知道是不是有什么设置会导致这种情况。

**Comment by yhmo** [comment]
Typically, we launch milvus by docker:
`docker run -p 19530:19530 -v /abc/efg/db:/var/lib/milvus/db -d milvusdb/milvus:gpu-latest`

The "-v /abc/efg/db:/var/lib/milvus/db" is to mapping folder between container and local machine, when you login docker container and use "du -h -d 1" command to calculate disk cost, it actually calculate the  "/abc/efg/db" folder outside the container. So you need to ensure the "/abc/efg/db" folder is empty, and the mapping is correct.

**Comment by yhmo** [comment]
This issue could relate to #2216 
In milvus 0.6.0/0.7.0/0.8.0, for **mishard**(or **deploy_mode** set to **cluster_writable**), and user insert vector in small batch continually, the hard disk space consumed very fast. 
In 0.9.0, we optimize the merge algorithm, reduce the disk cost to 20% compare to previous version.
