### ISSUE TITLE
[Bug]: milvus-windows-20220818-21594b2 版本load会卡住，崩溃

### ISSUE THREAD

**Issue by JericLee** [milvus-io/milvus#20383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

 [ERROR] [grpcclient/client.go:140] ["failed to get client address"] [error="find no available rootcoord, check rootcoord state"] [stack="github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).connect\n\tD:/a/milvus/milvus/internal/util/grpcclient/client.go:140\ngithub.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).GetGrpcClient\n\tD:/a/milvus/milvus/internal/util/grpcclient/client.go:112\ngithub.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).callOnce\n\tD:/a/milvus/milvus/internal/util/grpcclient/client.go:202\ngithub.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall\n\tD:/a/milvus/milvus/internal/util/grpcclient/client.go:245\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord/client.(*Client).GetComponentStates\n\tD:/a/milvus/milvus/internal/distributed/rootcoord/client/client.go:127\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1\n\tD:/a/milvus/milvus/internal/util/funcutil/func.go:67\ngithub.com/milvus-io/milvus/internal/util/retry.Do\n\tD:/a/milvus/milvus/internal/util/retry/retry.go:37\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates\n\tD:/a/milvus/milvus/internal/util/funcutil/func.go:91\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentHealthy\n\tD:/a/milvus/milvus/internal/util/funcutil/func.go:106\ngithub.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).init\n\tD:/a/milvus/milvus/internal/distributed/querycoord/service.go:155\ngithub.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).Run\n\tD:/a/milvus/milvus/internal/distributed/querycoord/service.go:96\ngithub.com/milvus-io/milvus/cmd/components.(*QueryCoord).Run\n\tD:/a/milvus/milvus/cmd/components/query_coord.go:50\ngithub.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runQueryCoord.func1\n\tD:/a/milvus/milvus/cmd/roles/roles.go:186"]

**Comment by yanliang567** [comment]
@JericLee Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
/assign @JericLee

**Comment by JericLee** [comment]
I'm using the windows version,
At this website:
http://github.com/matrixji/milvus/releases
The latest version number:
[windows-test-v29](https://github.com/matrixji/milvus/releases/tag/windows-test-v29) [Latest](https://github.com/matrixji/milvus/releases/latest)
workflow for release windows
Signed-off-by: Ji Bin <matrixji@live.com>

[notice](javascript:;)execute "milvus.laodcollection" is bound to crash!

**Comment by yanliang567** [comment]
@JericLee could you please use an official release, as we don't offer windows version for not.

**Comment by yanliang567** [comment]
close for now
