### ISSUE TITLE
关于CPU 指令集，建议将目前对应版本支持的特殊CPU指令集标明（备注）

### ISSUE THREAD

**Issue by wangqiao2011** [milvus-io/milvus#2040]
**Is your feature request related to a problem? Please describe.**
在不支持avx2 CPU指令集的设备上运行Milvus docker失败，如下提示（非法指令）：
[root@localhost ~]# docker logs b972d11e9e5f
./start_server.sh: line 3:     7 Illegal instruction     (core dumped) ../bin/milvus_server -c ../conf/server_config.yaml -l ../conf/log_config.conf

**Describe the solution you'd like**
建议将对应Milvus支持的CPU特有指令集标明，这样用户（开发者）可以更好的选择硬件(CPU)设备环境。

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by JinHai-CN** [comment]
Yes, in the next release, we will give the check on the CPU type and the detailed description in document.

**Comment by tinkerlin** [comment]
@PahudPlus detail info refer to #2039

**Comment by PahudPlus** [comment]
CPU instruction sets and CPU version updated.
