### ISSUE TITLE
[Bug]: [Nightly] The result is wrong when query pagination with expression

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#20406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: c5cd92d
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.0.dev71
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The result is wrong when query pagination with expression.
```
[2022-11-07T19:18:43.923Z] FAILED testcases/test_query.py::TestQueryParams::test_query_pagination_with_expression[100-0 < int64 < 400] - assert [3, 5, 6, 7, 8, 9, ...] == [1, 2, 3, 4, 5, 6, ...]
[2022-11-07T19:18:43.923Z]   At index 0 diff: 3 != 1
[2022-11-07T19:18:43.923Z]   Right contains 209 more items, first extra item: 191
```

### Expected Behavior

PASS

### Steps To Reproduce

```markdown
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/186/pipeline/155/
```

### Milvus Log

1. log: [artifacts-milvus-distributed-kafka-nightly-186-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/186/artifact/artifacts-milvus-distributed-kafka-nightly-186-pymilvus-e2e-logs.tar.gz)
2. collection name: query_nA5pOi5B
3. failed time: [2022-11-07T18:11:38.118Z] [gw3] [ 32%] FAILED testcases/test_query.py::TestQueryParams::test_query_pagination_with_expression[100-0 < int64 < 400]

**Comment by XuanYang-cn** [comment]
I can't reproduce it locally, and the logs seem fine.

I'll add some detailed logs.
