### ISSUE TITLE
[Bug]: Indexnode does not release memory after index tasks completed

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#20455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20221103-deb9963d
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.0dev72
```

### Current Behavior

index node does not release memory after index tasks completed

### Expected Behavior

index node shall release memory after tasks completed

### Steps To Reproduce

```markdown
1. delete and insert 1 million entities every 12 hours (it leads index node to build index as the collection was indexed before)
2. check the memory usage of index node
```

### Milvus Log

master-20221103-deb9963d
```
yanliang-cluster-1cu-milvus-datanode-855dc87f6c-g8psg           1/1     Running     1 (5d23h ago)   5d23h
yanliang-cluster-1cu-milvus-indexnode-5cf7c979c9-d7nvw          1/1     Running     0               5d23h
yanliang-cluster-1cu-milvus-mixcoord-65cfdd5d65-glcp6           1/1     Running     0               5d23h
yanliang-cluster-1cu-milvus-proxy-575b7d8568-2twg5              1/1     Running     0               5d23h
yanliang-cluster-1cu-milvus-querynode-689f7fc4f7-8mnw8          1/1     Running     0               4h10m
```
master-20221109-0dc659a0
```
yanliang-cluster-1cu-milvus-datanode-848447979-rzsz5            1/1     Running     0               28m
yanliang-cluster-1cu-milvus-indexnode-997d5cc59-78spn           1/1     Running     0               28m
yanliang-cluster-1cu-milvus-mixcoord-58b7f4b757-lczmx           1/1     Running     0               28m
yanliang-cluster-1cu-milvus-proxy-85848fcb4d-58gt9              1/1     Running     0               28m
yanliang-cluster-1cu-milvus-querynode-6fc57668b9-6n2l2          1/1     Running     0               13m
```

### Anything else?

![image](https://user-images.githubusercontent.com/82361606/200987525-bb67cbd7-2db6-4fa2-ac1d-376c7a0b1366.png)

**Comment by xiaofan-luan** [comment]
might need a debug.FreeOSMemory after each index build task?

**Comment by xiaocai2333** [comment]
I have not reproduced this situation locally. After completing the indexing task, the memory occupied by IndexNode is about 200M.

**Comment by xiaocai2333** [comment]
> might need a debug.FreeOSMemory after each index build task?

we can try this.

**Comment by yanliang567** [comment]
on 2.2.0-20221111-7c502601, the memory decreased to 1.15GB from 2.0GB, better than before.
![image](https://user-images.githubusercontent.com/82361606/201806087-ef33d726-4cc5-47ae-89f7-da24cd1975f7.png)

**Comment by xiaocai2333** [comment]
> I have not reproduced this situation locally. After completing the indexing task, the memory occupied by IndexNode is about 200M.

Sorry, I tested with the master-latest. I will test it on master-20221103-deb9963d.

**Comment by xiaocai2333** [comment]
> on 2.2.0-20221111-7c502601, the memory decreased to 1.15GB from 2.0GB, better than before. ![image](https://user-images.githubusercontent.com/82361606/201806087-ef33d726-4cc5-47ae-89f7-da24cd1975f7.png)

I checked the recent prs related IndexNode, maybe because this pr (#20391 )makes it better.

**Comment by xiaocai2333** [comment]
Is there any more detailed information on this? I would like to be known how the memory of IndexNode got to 3.73GiB.  @yanliang567

**Comment by yanliang567** [comment]
it deleted 1 million and insert 1 million entities at 4:00 AM and 4:00 PM twice a day.

> Is there any more detailed information on this? I would like to be known how the memory of IndexNode got to 3.73GiB. @yanliang567
