### ISSUE TITLE
[Enhancement]: Investigate Milvus disk consumption 

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#20453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

We've seen great amplification on disk usage in Milvus, and many user failed to insert data into milvus because of lack of enough disk space.

A few things to suspect:
1) Streaming data will be 3X because we gc streaming data with a relatively long time (Usually 3-5 days). Any log flushed to Minio and checkpointed should be discarded.

2) Minio 3X the data. (Compression， dedup and EC might alleviate the issue a little bit)

3) Compaction and GC may 2X the disk consumption，if we flush many small segments, things got even worse. (Trigger GCed file cleanup faster)

4) Index may 2X the disk consumption because store the vector data in both knowhere and binlog (Refine the data format)

5) Disk storage format may 4X the data consumption. In current bin log , we store int8 with int32 data type, which consumes 4 times disk space. (Refine the data format)

6) Stats(Bloom filter) may take disk space. Before 2.2 this is a huge issue for small segment, but now it's just maybe 10 percent or less(Should be ok for now,  need more evidence on it)

7) Time tick in the stream. This is especially annoying for user not inserting any data, and they still see disk usage increase.(Use kafka/pulsar/rocksdb compaction strategy to cleanup consecutive timeticks?)

8) Other issues leak the minio object? (Need more test)

**Comment by jiaoew1991** [comment]
The logs may be huge

**Comment by XuanYang-cn** [comment]
Query for vectors may cache a large amount of data on disk, at most 2G by default.

**Comment by XuanYang-cn** [comment]
Standalone may need to consider rocksdb

**Comment by xiaofan-luan** [comment]
keep open

**Comment by xiaofan-luan** [comment]
keep it open, this is still a part for Milvus 2.3 and 2.4

**Comment by xiaofan-luan** [comment]
keep it

**Comment by claud0698** [comment]
Hello, is there any fix for this bug regarding the increase in disk usage even when there is no insertion in the collections?

**Comment by xiaofan-luan** [comment]
> Hello, is there any fix for this bug regarding the increase in disk usage even when there is no insertion in the collections?

If you are using standalone, maybe of the disk is consumed by timetick in side logs.
could you check which directory takes most of the memory?

**Comment by claud0698** [comment]
> > Hello, is there any fix for this bug regarding the increase in disk usage even when there is no insertion in the collections?
> 
> If you are using standalone, maybe of the disk is consumed by timetick in side logs. could you check which directory takes most of the memory?

The most memory is here:
=> 39G milvus
      => 39G       milvus/rdb_data
      => 124M    milvus/rdb_data_meta_kv
      => 4.0K       milvus/logs

Is this where timetick in side logs are stored?

**Comment by xiaofan-luan** [comment]
if you use rocksmq, then here -> milvus/rdb_data
That might be too large for now, we should limit it to less than 10GB

**Comment by xiaofan-luan** [comment]
@yanliang567

**Comment by claud0698** [comment]
> if you use rocksmq, then here -> milvus/rdb_data That might be too large for now, we should limit it to less than 10GB

Is the possible fix to try to change the config for rocksmq? I will try to change the config file for the retention size and time.

**Comment by xiaofan-luan** [comment]
> > if you use rocksmq, then here -> milvus/rdb_data That might be too large for now, we should limit it to less than 10GB
> 
> Is the possible fix to try to change the config for rocksmq? I will try to change the config file for the retention size and time.

Change retention time might help, we are working on reproducing it

**Comment by jiaoew1991** [comment]
@aoiasd  is working on it
