### ISSUE TITLE
[Bug]: The time of releasing collection after reinstallation is much larger than normal when mq is Kafka 

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#20489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20221110-14a544d6
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/201063218-07a4caa5-9d50-4b59-852a-2ac0d06ed504.png)

### Expected Behavior

This is the performance when mq is pulsar
![image](https://user-images.githubusercontent.com/12268675/201063586-ffa46a58-8451-46c5-b2bf-76ef46ae4908.png)

### Milvus Log

job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_for_release/detail/deploy_test_kafka_for_release/353/pipeline
log:
[artifacts-kafka-cluster-reinstall-353-pytest-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/9979676/artifacts-kafka-cluster-reinstall-353-pytest-logs.1.tar.gz)
[artifacts-kafka-cluster-reinstall-353-server-first-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/9979679/artifacts-kafka-cluster-reinstall-353-server-first-deployment-logs.tar.gz)
[artifacts-kafka-cluster-reinstall-353-server-second-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/9979680/artifacts-kafka-cluster-reinstall-353-server-second-deployment-logs.tar.gz)

**Comment by jaime0815** [comment]
related to #20445

**Comment by zhuwenxing** [comment]
Verified in image `2.2.0-20221126-dd10e571`
