### ISSUE TITLE
[QUESTION] Can I build without GPU?

### ISSUE THREAD

**Issue by WenqiJiang** [milvus-io/milvus#205]
I found that both the docker image and the build scripts require CUDA. However, is it possible to build the environment without Nvidia GPU?

**Comment by cxie** [comment]
It will be supported in the upcoming 0.6.0 release. 
Refer to #12

**Comment by WenqiJiang** [comment]
> It will be supported in the upcoming 0.6.0 release.
> Refer to #12

Thanks for letting me know. I am wondering if it is possible to build with CPU by making some adjustments to the build.sh and CMakeList.

**Comment by youny626** [comment]
> > It will be supported in the upcoming 0.6.0 release.
> > Refer to #12
> 
> Thanks for letting me know. I am wondering if it is possible to build with CPU by making some adjustments to the build.sh and CMakeList.

Hi, the CPU version can also be built from source. The 0.6.0 version will be released in a few weeks.

**Comment by youny626** [comment]
Also if you decide to try the CPU version from the current 0.6.0 branch, feel free to point out any issue you encountered. We are still actively developing the CPU version. :p

**Comment by cydrain** [comment]
close
