### ISSUE TITLE
[Bug]: Disk data is not cleaned up and restart fails

### ISSUE THREAD

**Issue by xige-16** [milvus-io/milvus#20522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

["AppendIndex failed, C Runtime Exception: [UnexpectedError] Assert \"!local_chunk_manager.Exist(local_index_path_prefix)\" at /go/src/github.com/milvus-io/milvus/internal/core/src/index/VectorDiskIndex.cpp:42\n =\u003e local index path //milvus/data//index_files/437252037854075869/1/ has been exist\n"]

### Expected Behavior

After milvus start， building / loding index should be success

**Comment by yanliang567** [comment]
@xige-16 is this still an issue

**Comment by xige-16** [comment]
When milvus exits abnormally, the local data in the /milvus/data directory cannot be cleaned up normally.
