### ISSUE TITLE
[Bug]: Milvus's performance is too bad Although I restarted the cluster

### ISSUE THREAD

**Issue by dzqoo** [milvus-io/milvus#20532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.2
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): centos
- CPU/Memory: queryNode:3c12g,querynode num is 12 
- GPU: 
- Others:
```

### Current Behavior

I have 1900w data which is 128 dim inserted into milvus.The replicas num is 2.

I test the performance use office scipt and the RT is too bad as you see in the following:
![image](https://user-images.githubusercontent.com/8862305/201458767-0a8abced-d1ef-430d-906c-3e1575bd6f8e.png)
![image](https://user-images.githubusercontent.com/8862305/201458846-14f7659f-d724-44a9-8abc-98976d6206b5.png)
![image](https://user-images.githubusercontent.com/8862305/201458862-a51d4912-9344-406e-a6de-dd9fc6be87a9.png)

There is all the logs :
[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/9994202/milvus-log.tar.gz)

I have reinstall milvus and reinsert the data, everything goes no more better anyway.

**Comment by dzqoo** [comment]
[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/9994335/milvus-log.tar.gz)
The logs above are incomplete. Please see this log package

**Comment by dzqoo** [comment]
I have test the performance in latest version of milvus2.2.0 and still get bad performance as you see in the following:
1. query latency:
![image](https://user-images.githubusercontent.com/8862305/203059428-3546c67b-ed5b-42b7-b163-9c66468e79f6.png)
![image](https://user-images.githubusercontent.com/8862305/203059549-8478aad1-3c53-4574-ad0b-faf39b114e8f.png)
![image](https://user-images.githubusercontent.com/8862305/203059739-4ac58ed8-1541-4890-9db5-25b2bd0dcc4f.png)

2. querynode cpu load
there is the querynode cpu, and my querynode cpu config is 3c24g:
![image](https://user-images.githubusercontent.com/8862305/203060048-9a8fd71e-3ad7-4ab8-b70c-253e2a6ba74f.png)

3. there is all the logs:
[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/10056642/milvus-log.tar.gz)

4. there is the etcd meta:
[bw_etcd_ALL.221121-204420.bak.gz](https://github.com/milvus-io/milvus/files/10056651/bw_etcd_ALL.221121-204420.bak.gz)

**Comment by yanliang567** [comment]
<img width="934" alt="image" src="https://user-images.githubusercontent.com/82361606/203266123-4b6e76ca-7528-4408-9f14-8aee28ca540c.png">

<img width="931" alt="image" src="https://user-images.githubusercontent.com/82361606/203266740-c339a746-cea5-4871-b4f8-4215b8eea058.png">

<img width="931" alt="image" src="https://user-images.githubusercontent.com/82361606/203266192-4c897367-5fc9-4e70-83ed-7c830b6d2f1d.png">
<img width="937" alt="image" src="https://user-images.githubusercontent.com/82361606/203266208-4cb45270-9216-477c-8a1f-e314b780838b.png">
<img width="934" alt="image" src="https://user-images.githubusercontent.com/82361606/203266232-6e45592a-f7f0-408f-9518-70159c0cff34.png">

**Comment by yanliang567** [comment]
here are some offline updates from @dzqoo:
1. there is a varchar filed with max length 65535, which will be retrieved in search requests. 
2. there are 2 more small collections with 400d-3m vectors earch, which also have the same varchar filed to be retrieved
3. exptected latency <100ms with 200 QPS total for 3 collections

**Comment by yanliang567** [comment]
Updates from @dzqoo: performance is not an issue any more after testing on Milvus 2.2. 
Close the issue.
