### ISSUE TITLE
[Bug]: Deleted entities could still be searched 

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#20575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: PR-20568-20221114-16bf42dae (2.2 branch)
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev71
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Deleted entities could still be searched 
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-20568/1/pipeline/

### Expected Behavior

Deleted entities could not be searched 

### Steps To Reproduce

```python
def test_delete_search_with_string(self):
        """
        target: test delete and search
        method: search entities after it was deleted, string field is primary
        expected: deleted entity is not in the search result
        """
        # init collection with nb default data
        collection_w, _, _, ids = self.init_collection_general(prefix, insert_data=True,
                                                               primary_field=ct.default_string_field_name)[0:4]
        entity, _ = collection_w.query(default_string_expr, output_fields=["%"])
        search_res, _ = collection_w.search([entity[0][ct.default_float_vec_field_name]],
                                            ct.default_float_vec_field_name,
                                            ct.default_search_params, ct.default_limit)
        # assert search results contains entity
        assert "0" in search_res[0].ids

        expr = f'{ct.default_string_field_name} in {ids[:ct.default_nb // 2]}'
        expr = expr.replace("'", "\"")
        collection_w.delete(expr)
        search_res_2, _ = collection_w.search([entity[0][ct.default_float_vec_field_name]],
                                              ct.default_float_vec_field_name,
                                              ct.default_search_params, ct.default_limit)
        # assert search result is not equal to entity
        log.debug(f"Second search result ids: {search_res_2[0].ids}")
        inter = set(ids[:ct.default_nb // 2]
                    ).intersection(set(search_res_2[0].ids))
        # Using bounded staleness, we could still search the "deleted" entities,
        # since the search requests arrived query nodes earlier than query nodes consume the delete requests.
        assert len(inter) == 0
```

### Milvus Log

[artifacts-milvus-standalone-PR-20568-1-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20HA%20CI/job/PR-20568/1/artifact/artifacts-milvus-standalone-PR-20568-1-pymilvus-e2e-logs.tar.gz)

collection name: delete_kWtVotoB

**Comment by xiaofan-luan** [comment]
if it's bounded, delete will disappeared after certain seconds and we don't guarantee data to be deleted immediately.

could we try to refetch after bounded window? by default is 3 seconds.

**Comment by binbinlv** [comment]
> if it's bounded, delete will disappeared after certain seconds and we don't guarantee data to be deleted immediately.
> 
> could we try to refetch after bounded window? by default is 3 seconds.

will try.

**Comment by xiaofan-luan** [comment]
similar to #20640

**Comment by yah01** [comment]
related #20655

**Comment by soothing-rain** [comment]
@MrPresent-Han can you also help with this? :)

/assign @MrPresent-Han

**Comment by MrPresent-Han** [comment]
Ok, I will handle this

**Comment by soothing-rain** [comment]
related e2e failure on Nov 23rd:

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-20776/9

**Comment by xiaofan-luan** [comment]
@MrPresent-Han 
Any progress on it?

**Comment by MrPresent-Han** [comment]
trying to reproduce it locally

**Comment by sunby** [comment]
> trying to reproduce it locally

It is hard to reproduce. We can add some logs to trace the bug.

**Comment by MrPresent-Han** [comment]
One weird thing is that query_node checks all segments on one node, rather than the segments belonging to single shard, which is unnecessary from my perspective, as deleteIDs have been diverted according to hash result

![20221128-145358](https://user-images.githubusercontent.com/116052805/204213004-af5faf1e-779c-4fea-9946-2fa3a6361dcc.jpeg)

as shown in the image above, there is only two segments(9372,9373) in this collection, which is distributed on two channels(v0,v1) respectively. There is no need to try to delete 9373 in v0 or 9372 in v1

**Comment by congqixia** [comment]
> One weird thing is that query_node checks all segments on one node, rather than the segments belonging to single shard, which is unnecessary from my perspective, as deleteIDs have been diverted according to hash result
> 
> ![20221128-145358](https://user-images.githubusercontent.com/116052805/204213004-af5faf1e-779c-4fea-9946-2fa3a6361dcc.jpeg)
> 
> as shown in the image above, there is only two segments(9372,9373) in this collection, which is distributed on two channels(v0,v1) respectively. There is no need to try to delete 9373 in v0 or 9372 in v1

@MrPresent-Han actually I think that's some thing important. One delete message shall only apply in one shard. Even we check all the segment in the collection, the target segment's Bloom Filter shall match all delete id. However we found some entries is applied to the another segment.

**Comment by MrPresent-Han** [comment]
> > One weird thing is that query_node checks all segments on one node, rather than the segments belonging to single shard, which is unnecessary from my perspective, as deleteIDs have been diverted according to hash result
> > ![20221128-145358](https://user-images.githubusercontent.com/116052805/204213004-af5faf1e-779c-4fea-9946-2fa3a6361dcc.jpeg)
> > as shown in the image above, there is only two segments(9372,9373) in this collection, which is distributed on two channels(v0,v1) respectively. There is no need to try to delete 9373 in v0 or 9372 in v1
> 
> @MrPresent-Han actually I think that's some thing important. One delete message shall only apply in one shard. Even we check all the segment in the collection, the target segment's Bloom Filter shall match all delete id. However we found some entries is applied to the another segment.

Because bloomFilter could only detect those 'definitely non-existed' items, Although some delete entries are applied to unrelated

**Comment by yah01** [comment]
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-20861/3/pipeline

**Comment by congqixia** [comment]
Here is the root cause of this problem:
Previously in querynode, one delete msg will scan all segments of this collection. So the bloom filter may report false positive, which will cause concurrent deletes on same segment.
And the implementation of DeleteRecord._ackResponder will returns the latest continuous acked position of delete records. So concurrent delete may cause some time tick safe delete "hidden" by the other `PreDelete` op.

**Comment by congqixia** [comment]
@binbinlv Fix pr has been merged. Could you please check whether this problem still persists?

**Comment by binbinlv** [comment]
It did not appeared in recently days, but considering it is an incidental issue,  so close it first. Will reopen it if it occurs in the future.
