### ISSUE TITLE
Milvus增加多值多字段过滤查询

### ISSUE THREAD

**Issue by oswen** [milvus-io/milvus#2061]
**Is your feature request related to a problem? Please describe.**
希望Milvus增加类似于elasticsearch的terms过滤功能及范围筛选功能

**Describe the solution you'd like**
{
  "query": {
    "bool": {
      "must": [
        {
          “match_all”: {}
        },
        {
          "terms": {
            "ban": [
              "1"
            ]
          }
        },
        {
          "terms": {
            "flag_language": [
              "zh",
              "undefined"
            ]
          }
        },
        {
          "terms": {
            "pc_outside_zh": [
              1
            ]
          }
        },
        {
          "range": {
            "status": {
              "gt": "0"
            }
          }
        }
      ]
    }
  },
  "collapse": {
    "field": "question_id"
  },
  "_source": [
    "question",
    "question_id",
    "std_question"
  ],
  "size": 20
}
上面这个elasticsearch的DSL是我们项目中会用到的一个简单的过滤查询，其中terms项表示根据“ban”字段的值(可以为单个值，也可以是数组组成的多个值)进行过滤；range项表示范围过滤查询，示例中的gt表示“大于等于”字段“status”表示的值；以上均是elasticsearch过滤查询的示例，希望milvus能够参考elasticsearch的设计思想，实现这种复杂的过滤查询功能。

**Comment by tinkerlin** [comment]
This feature will be supported in future versions. 
Refer to RoadMap [https://github.com/milvus-io/milvus/projects](url)

@oswen

**Comment by JinHai-CN** [comment]
https://github.com/milvus-io/milvus/blob/master/DESIGN.md
Check the DSL design document and this feature is planned to release in 0.10.0.

**Comment by scsven** [comment]
Supported in 0.11.0 release.
