### ISSUE TITLE
[Bug]: windows sometimes using 169.254.x.x as local ip, which is not available for connect

### ISSUE THREAD

**Issue by matrixji** [milvus-io/milvus#20625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2-testing-20221110
- Deployment mode(standalone or cluster):standalone, windows
- SDK version(e.g. pymilvus v2.0.0rc2): not related
- OS(Ubuntu or CentOS): windows
- CPU/Memory: not related
- GPU: not related
- Others: https://github.com/matrixji/milvus/releases/tag/windows-v2.2-testing-20221110
```

### Current Behavior

Recently, guys report some problems under windows to me, so I try to find the root cause from the provided logs.
It seems in windows, the IP address 169.254.x.x may be selected as the first local IP, in such case, the connection to this IP is not available.

I'm not very sure if it should be fixed in [go-basic/ipv4](https://github.com/go-basic/ipv4/blob/master/ip.go), there is a method `IsGlobalUnicast` in `net/ip` to filter valid IP for unicast connections. And with current implementations, the go-basic/ipv4 only filter out the Loopback IPs.

Another option: when we run with standalone mode, does it possible to use 127.0.0.1 as the grpc IP address directly?

### Expected Behavior

hope the standalone mode running success under windows

### Milvus Log

[milvus11.14.log](https://github.com/milvus-io/milvus/files/10014325/milvus11.14.log)

**Comment by yanliang567** [comment]
/assign @matrixji 
please help to work on this issue.
/unassign

**Comment by matrixji** [comment]
> we should provide a config to let users to specific which host they want to bind
I may try to fix this with two parts, first ignore the address like 169.254.x.x, and then try to introduce a new parameter for config listen local IP/network in later PR.
