### ISSUE TITLE
实时增量更新、查询，milvus应该如何配置？

### ISSUE THREAD

**Issue by Bennu-Li** [milvus-io/milvus#2063]
**What is your question?**
流式数据插入（每秒上百条的数据产生），要求实时增量更新，插入后立马查询，总量大概在两三亿的样子。如何去设置milvus的参数，有最优的配置建议吗？

**Comment by tinkerlin** [comment]
Milvus currently does not guarantee real-time query, it takes a while for the inserted data to be queried. However, you can obtain the maximum real-time performance by setting the following parameters.
```
cache_insert_data: true
auto_flush_interval: 1
```

**Comment by yhmo** [comment]
@Bennu-Li 
What is the dimension of your vectors?

To ensure inserted vectors be search-able, you need to write the client like this:

```
insert(100 vectors)
flush(collection_name)
search()
insert(100 vectors)
flush(collection_name)
search()
```
To get better performance for query, milvus need to hold all data in cpu memory. IVFSQ8 is a good choice, its index file size is about 30% compare to raw data file.
Assume your vectors are 512-dimensional. each vector is 512*4 byte=2KB, 200M vectors raw data size is 200M*2KB=400GB, so the SQ8 index size is 120GB. So you need to set the "cpu_cache_capacity" to 120 in the server_config.yaml before you start milvus server. 
And cpu version performance is different to gpu version. For our experiment on a 56 core server, 50M 512-dimensional vectors with SQ8 index, each query with nq<100 cost about 1 second.
But if vectors continuely inserted, background worker process the inserted data will affect the performance of query.
