### ISSUE TITLE
[Bug]: [standalone] Search params check failed error Issue

### ISSUE THREAD

**Issue by seungwoo-h** [milvus-io/milvus#20644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): '2.1.3'
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: Intel(R) Xeon(R) Silver 4210 CPU @ 2.20GHz
- GPU: Tesla V100 X2
- Others:
```

### Current Behavior

ERROR:pymilvus.decorators:RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=26, reason=Search 26 failed, reason [UnexpectedError] Assert "adapter->CheckSearch(conf, index_type, field_indexing->indexing_->index_mode())" at /go/src/github.com/milvus-io/milvus/internal/core/src/query/SearchOnSealed.cpp:54
 => [SearchOnSealed]Search params check failed err %!w(<nil>))>, <Time:{'RPC start': '2022-11-16 07:27:26.724729', 'RPC error': '2022-11-16 07:27:27.020444'}>
Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?ae3fb963-21a4-487d-9286-fc1136314779)
---------------------------------------------------------------------------
MilvusException                           Traceback (most recent call last)
File /usr/local/lib/python3.9/dist-packages/haystack/pipelines/base.py:524, in Pipeline.run(self, query, file_paths, labels, documents, meta, params, debug)
    523     logger.debug("Running node '%s` with input: %s", node_id, node_input)
--> 524     node_output, stream_id = self._run_node(node_id, node_input)
    525 except Exception as e:
    526     # The input might be a really large object with thousands of embeddings.
    527     # If you really want to see it, raise the log level.

File /usr/local/lib/python3.9/dist-packages/haystack/pipelines/base.py:451, in Pipeline._run_node(self, node_id, node_input)
    450 def _run_node(self, node_id: str, node_input: Dict[str, Any]) -> Tuple[Dict, str]:
--> 451     return self.graph.nodes[node_id]["component"]._dispatch_run(**node_input)

File /usr/local/lib/python3.9/dist-packages/haystack/nodes/base.py:201, in BaseComponent._dispatch_run(self, **kwargs)
    197 """
    198 The Pipelines call this method when run() is executed. This method in turn executes the _dispatch_run_general()
    199 method with the correct run method.
    200 """
--> 201 return self._dispatch_run_general(self.run, **kwargs)

File /usr/local/lib/python3.9/dist-packages/haystack/nodes/base.py:245, in BaseComponent._dispatch_run_general(self, run_method, **kwargs)
    243         run_inputs[key] = value
--> 245 output, stream = run_method(**run_inputs, **run_params)
    247 # Collect debug information
...
    533 #

Exception: Exception while running node 'Retriever': <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=26, reason=Search 26 failed, reason [UnexpectedError] Assert "adapter->CheckSearch(conf, index_type, field_indexing->indexing_->index_mode())" at /go/src/github.com/milvus-io/milvus/internal/core/src/query/SearchOnSealed.cpp:54
 => [SearchOnSealed]Search params check failed err %!w(<nil>))>
Enable debug logging to see the data that was passed when the pipeline failed.

### Expected Behavior

The program should return normal search results

### Steps To Reproduce

```markdown
This error happens after 24 hours to 48 hours after the saving vectors to milvus collection.
I didn't add or remove any data, but this happens every time.

from haystack.document_stores import MilvusDocumentStore
from haystack.nodes import DensePassageRetriever, FARMReader
from haystack.pipelines import ExtractiveQAPipeline 
import torch

class CFG_DPR():
    milvus_host = "172.28.0.4"
    milvus_collection = "nov16full" #nov13
    milvus_sql_url = "sqlite:////VOLUME/swhong/sqlite_db/nov16full.db" #nov13.db
    milvus_index_type = "HNSW" # IVF_FLAT / HNSW
    milvus_index_param = {"M": 32, "efConstruction": 64}
    milvus_search_param = {"ef": 250, "metric_type": "IP"}
    retriever_model_path = '/VOLUME/swhong/saved_models/dpr_korq2_nov11_multibert'
    reader_model_path = "/VOLUME/swhong/saved_models/reader_models" # or "ainize/klue-bert-base-mrc"
    pipeline_search_param = {"Retriever": {"top_k": 10}, "Reader": {"top_k": 5}}

dpr_args = CFG_DPR()

dpr_document_store = MilvusDocumentStore(
    host=dpr_args.milvus_host, 
    return_embedding=True, 
    index=dpr_args.milvus_collection, 
    sql_url=dpr_args.milvus_sql_url, 
    index_type=dpr_args.milvus_index_type, 
    index_param=dpr_args.milvus_index_param, 
    search_param=dpr_args.milvus_search_param
)

dpr_retriever = DensePassageRetriever.load(load_dir=dpr_args.retriever_model_path, document_store=dpr_document_store])
```

### Milvus Log

ERROR:pymilvus.decorators:RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=19, reason=Search 19 failed, reason [UnexpectedError] Assert "adapter->CheckSearch(conf, index_type, field_indexing->indexing_->index_mode())" at /go/src/github.com/milvus-io/milvus/internal/core/src/query/SearchOnSealed.cpp:54
 => [SearchOnSealed]Search params check failed err %!w(<nil>))>, <Time:{'RPC start': '2022-11-16 07:03:39.124387', 'RPC error': '2022-11-16 07:03:39.368965'}>
Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?b10e407f-987c-41ab-bd15-0bfb8309bfb7)
---------------------------------------------------------------------------
MilvusException                           Traceback (most recent call last)
File /usr/local/lib/python3.9/dist-packages/haystack/pipelines/base.py:524, in Pipeline.run(self, query, file_paths, labels, documents, meta, params, debug)
    523     logger.debug("Running node '%s` with input: %s", node_id, node_input)
--> 524     node_output, stream_id = self._run_node(node_id, node_input)
    525 except Exception as e:
    526     # The input might be a really large object with thousands of embeddings.
    527     # If you really want to see it, raise the log level.

File /usr/local/lib/python3.9/dist-packages/haystack/pipelines/base.py:451, in Pipeline._run_node(self, node_id, node_input)
    450 def _run_node(self, node_id: str, node_input: Dict[str, Any]) -> Tuple[Dict, str]:
--> 451     return self.graph.nodes[node_id]["component"]._dispatch_run(**node_input)

File /usr/local/lib/python3.9/dist-packages/haystack/nodes/base.py:201, in BaseComponent._dispatch_run(self, **kwargs)
    197 """
    198 The Pipelines call this method when run() is executed. This method in turn executes the _dispatch_run_general()
    199 method with the correct run method.
    200 """
--> 201 return self._dispatch_run_general(self.run, **kwargs)

File /usr/local/lib/python3.9/dist-packages/haystack/nodes/base.py:245, in BaseComponent._dispatch_run_general(self, run_method, **kwargs)
    243         run_inputs[key] = value
--> 245 output, stream = run_method(**run_inputs, **run_params)
    247 # Collect debug information
...
    533 #

Exception: Exception while running node 'Retriever': <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=19, reason=Search 19 failed, reason [UnexpectedError] Assert "adapter->CheckSearch(conf, index_type, field_indexing->indexing_->index_mode())" at /go/src/github.com/milvus-io/milvus/internal/core/src/query/SearchOnSealed.cpp:54
 => [SearchOnSealed]Search params check failed err %!w(<nil>))>
Enable debug logging to see the data that was passed when the pipeline failed.

**Comment by yanliang567** [comment]
@seungwoo-h Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @seungwoo-h

**Comment by yanliang567** [comment]
@seungwoo-h any chance to retry on milvus 2.2, which fixed bunch of issues
