### ISSUE TITLE
[Bug]: cluster pods remain in pending state for pulsar and etcd

### ISSUE THREAD

**Issue by akmalmasud96** [milvus-io/milvus#20650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.4
- Deployment mode(standalone or cluster): cluster
- helm chart : 3.2.17
- Others: eksctl with aws fargate
```

### Current Behavior

I was deploying on the aws eksctl using aws fargate. The pods remain in pending state for pulsar and etcd.

### Steps To Reproduce

```markdown
I was following this documentation,

https://milvus.io/docs/v2.1.x/eks.md
```

### Milvus Log

> Pod not supported on Fargate: volumes not supported: data not supported because: PVC data-milvus-etcd-0 not bound

**Comment by yanliang567** [comment]
@LoveEachDay please help to take a look

/assign @LoveEachDay 
/unassign

**Comment by LoveEachDay** [comment]
Duplicate for milvus-io/milvus-helm#389.

**Comment by john-h-luo** [comment]
Hello, @akmalmasud96, https://milvus.io/docs/v2.2.x/eks.md has updates, I've tested it myself and I believe it will help you setup a Milvus cluster. If you encounter any issue please leave a comment to let me know.
