### ISSUE TITLE
[Bug]: The memory usage is high after the update

### ISSUE THREAD

**Issue by devNullgh** [milvus-io/milvus#20654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.1 -> 2.1.4
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.1
- OS(Ubuntu or CentOS):  CentOS
- CPU/Memory: 16c/64GB
- GPU: ---
- Others: Entity Count is 7W
```

### Current Behavior

Update 2.1.1 to 2.1.4, the memory usage is too high.

### Expected Behavior

Entity Count is only 7W，the memory usage should not be so high.

### Steps To Reproduce

```markdown
Related Parameters:
Index Type:IVF_SQ8;
Vector_DIM:2048;
Index File Size:1024;
Metric Type:L2;
Nlist:16384;
Partitions:2;
Fields:total 3 fields:  2 VarChar fields and 1 FloatVector;
```

### Milvus Log

![image](https://user-images.githubusercontent.com/43362620/202170301-e59d7baf-bda4-41b8-8f93-f781ae234e3e.png)

![image](https://user-images.githubusercontent.com/43362620/202169320-1b51ae1b-f169-47e4-9997-7e0b93f7b1d5.png)

![image](https://user-images.githubusercontent.com/43362620/202168110-75bae308-c309-4301-8319-c4d58318fe52.png)

**Comment by yanliang567** [comment]
@devNullgh did you run any delete operations before? 
Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @devNullgh 
/unassign

**Comment by devNullgh** [comment]
> Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

No deletion operation has been did.
We only update milvus from 2.1.1 to 2.1.4, because response time is too long at 7W vectors on the milvus2.1.1.

milvus logs:
 https://pan.baidu.com/s/1dY3_duFSGcBCQrWdpH8Z9g?pwd=7f5s

**Comment by devNullgh** [comment]
@yanliang567  We have tried reinstalling milvus-2.1.4 with docker-compose，but the memory usage is still very high.
![image](https://user-images.githubusercontent.com/43362620/202594888-3226ac32-d8d8-4d14-8483-5d7d53ac12dc.png)
![image](https://user-images.githubusercontent.com/43362620/202594939-ab26757e-5e3c-407e-80b7-08dd9fb46210.png)

schema:
id,  primary key,  varchar,  length（300）
user_id,  varchar,  length（300）
embedding,  floatvector,  dim（2048），index_type（IVF_SQ8），metric_type（L2）,  nlist（16384）

**Comment by devNullgh** [comment]
@yanliang567 We increased the memory to 128GB, but milvus still ran out of memory.
![0d9137444930d8e00eead27bdf74c33](https://user-images.githubusercontent.com/43362620/202597776-9aa0ab82-92b6-4352-9c4e-38608a2e6ebd.png)
![image](https://user-images.githubusercontent.com/43362620/202597862-9581e3d1-3011-4a2b-976d-dfbc19fc9179.png)

**Comment by yanliang567** [comment]
sounds like we need some improvement on varchar memory usage.
@congqixia any comments?

**Comment by xiaofan-luan** [comment]
What's the frequency of update?
This is definitely not a var char memory issue, since there are only 70k entities.
@devNullgh can your share you test code? I'm not sure how you generate so many segments.

even if each entity is 2048 dim(roughly 8k) ，it should take no larger than 1G memory

**Comment by xiaofan-luan** [comment]
so the log is expired and I didn't get it.

**Comment by devNullgh** [comment]
> What's the frequency of update? This is definitely not a var char memory issue, since there are only 70k entities. @devNullgh can your share you test code? I'm not sure how you generate so many segments.
> 
> even if each entity is 2048 dim(roughly 8k) ，it should take no larger than 1G memory

@xiaofan-luan 
code based on demo, change the id type from int64 to varchar:
https://github.com/milvus-io/milvus/issues/20654

We do not do update operation, only insert with '/img/upload', about 200~500 pictures per day.

It may not be a memory problem, we guess it may be a memory leak caused by varchar.

**Comment by devNullgh** [comment]
> so the log is expired and I didn't get it.

@xiaofan-luan 
20221205-to re-upload milvus logs:
https://pan.baidu.com/s/1EwpH54N6XK4JOl-hkd9vAg?pwd=26qa
