### ISSUE TITLE
[Bug]: Recovery would be slow if upgrade from 2.1 to 2.2 with empty collection

### ISSUE THREAD

**Issue by bigsheeper** [milvus-io/milvus#20656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Recovery would be slow if upgrade from 2.1 to 2.2 with empty collection.
If with empty collection, restarted milvus would seek from collection started position, which would be very early. Pulling back data(recovery) would cost a lot of time.
And during recovery, milvus would force to deny writing. So we should close tt delay protection in opensource.

**Comment by zhuwenxing** [comment]
In the upgrading test, we covered this scenario.
https://github.com/milvus-io/milvus/blob/master/tests/python_client/deploy/testcases/test_action_first_deployment.py
![image](https://user-images.githubusercontent.com/12268675/202345331-7ab72338-f27b-419d-a8c4-0b28748d6a56.png)

**Comment by bigsheeper** [comment]
> In the upgrading test, we covered this scenario. https://github.com/milvus-io/milvus/blob/master/tests/python_client/deploy/testcases/test_action_first_deployment.py ![image](https://user-images.githubusercontent.com/12268675/202345331-7ab72338-f27b-419d-a8c4-0b28748d6a56.png)

**Comment by xiaofan-luan** [comment]
is this still a valid issue?

**Comment by bigsheeper** [comment]
> is this still a valid issue?

no, it has been fixed
