### ISSUE TITLE
[Bug]: Very slow searching and query embeddings from collection.

### ISSUE THREAD

**Issue by mazitovs** [milvus-io/milvus#20687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-2.1.3
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 20cpu, 64ram
- GPU: 1080 8gb
- Others:
```

### Collection
I have collection in Milvus with 60mln rows, partitioned by year
```
work_id = FieldSchema(name="id", dtype=DataType.INT64, is_primary=True)
embedding = FieldSchema(name="embedding", dtype=DataType.FLOAT_VECTOR, dim=settings.VECTOR_DIMENSION, is_primary=False)
year = FieldSchema(name="year", dtype=DataType.INT64, is_primary=False)
concept_id_lvl_0 = FieldSchema(name="concept_id_lvl_0", dtype=DataType.VARCHAR, max_length=64, is_primary=False)
concept_id_lvl_1 = FieldSchema(name="concept_id_lvl_1", dtype=DataType.VARCHAR, max_length=64, is_primary=False)
schema = CollectionSchema(fields=[work_id, embedding, year, concept_id_lvl_0, concept_id_lvl_1])
collection = Collection(name=collection_name, schema=schema)
```
embeddings are from `SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2', cache_folder='models', device='cuda')`

### Index
```
default_index = {"index_type": "IVF_SQ8", "metric_type":"IP", "params": {"nlist": 16384}}
collection.create_index(field_name="embedding", index_params=default_index)
```
### Search
```
query = "some query"
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2', cache_folder='models', device='cuda')
vector = model.encode(query).reshape(1, -1).tolist()
search_params = {"metric_type": "IP", "params": {"nprobe": 64}}
res = collection.search(vector, anns_field="embedding", param=search_params, limit= 16384, expr="year>2020")
res = [item for item in res[0] if item.distance > 0.5]
```
My app get text query, embed it by SentenceTransformer, and push vector to Milvus searching with topk limit 16384. After I need to get back embeddings from collection and send it in clustering part. 
```
embeddings = collection.query(expr=f'id in {json.dumps(res)}', output_fields=["embedding"])
```

### Problem
Here is my application log

> [2022-11-16 07:27:05,895: INFO/MainProcess] Task app.tasks.processing.search_milvus_task[guid0] received
> **[2022-11-16 07:28:02,089: INFO/MainProcess] Task app.tasks.processing.search_milvus_task[guid0] succeeded in 56.1940124835819s: 26**
> [2022-11-16 07:28:02,093: INFO/MainProcess] Task app.tasks.processing.clustering_task[guid1] received
> **[2022-11-16 07:28:02,731: INFO/MainProcess] Get embeds by searched ids from milvus**
> [2022-11-16 07:33:22,290: INFO/MainProcess] Get texts by searched id from pg

### Questions 
1. How can I speed up searching searching task? It costs me 56seconds
2. Are there any better options to get back embeddings from Milvus collection than getting it by `collection.query(expr=f'id in {json.dumps(res)}', output_fields=["embedding"])` because loading time is more than 5 minutes?

### Expected Behavior

1. Searching task <2s
2. Query to collection <2s

**Comment by yanliang567** [comment]
@mazitovs thank you for the issue. Quick questions:
1. what is the dim of the vectors, and how many vectors did you have in the collection?
2. how do you deploy milvus, via docker compose? did you change any configurations or just use the default configuration?
3. Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

One quick piece of suggestion:
1. use a smaller value for nlist and nprobe, if you are not very sensitive of recall

**Comment by mazitovs** [comment]
Add @dmitry-r

**Comment by dmitry-r** [comment]
1. VECTOR_DIMENSION: int = 384, 60mln vectors in collection
2. Via docker compose with default config
3. Unfortunately, logs was lost

> @mazitovs thank you for the issue. Quick questions:
> 
> 1. what is the dim of the vectors, and how many vectors did you have in the collection?
> 2. how do you deploy milvus, via docker compose? did you change any configurations or just use the default configuration?
> 3. Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
> 
> One quick piece of suggestion:
> 
> 1. use a smaller value for nlist and nprobe, if you are not very sensitive of recall

**Comment by mazitovs** [comment]
@yanliang567

> [2022-11-21 03:49:33,360: INFO/MainProcess] Task app.tasks.processing.search_milvus_task[guid0] received
> **[2022-11-21 03:50:21,188: INFO/MainProcess] Task app.tasks.processing.search_milvus_task[baf3058c-f1c5-42a8-8179-76d20a7eeaa1] succeeded in 47.827316728420556s: 56**
> [2022-11-21 03:50:21,192: INFO/MainProcess] Task app.tasks.processing.clustering_task[guid1] received
> **[2022-11-21 03:50:21,982: INFO/MainProcess] Get embeds by searched ids from milvus**
> [2022-11-21 03:54:23,705: INFO/MainProcess] Get texts by searched id from pg


`docker compose logs milvus --since='2022-11-21T03:49:33Z' --until='2022-11-21T03:57:23Z'`
[milvus.log](https://github.com/milvus-io/milvus/files/10053874/milvus.log)

**Comment by yanliang567** [comment]
@mazitovs Looking into the milvus.log attached above, it indicates that the search request was done in milvus in 228ms. 
```
milvus  | [2022/11/21 03:49:33.596 +00:00] [DEBUG] [proxy/impl.go:2724] ["Search received"] [traceID=5ab4e948e4721af4] [role=proxy] [db=] [collection=works] [partitions="[]"] [dsl=] [len(PlaceholderGroup)=1548] [OutputFields="[]"] [search_params="[{\"key\":\"anns_field\",\"value\":\"embedding\"},{\"key\":\"topk\",\"value\":\"16384\"},{\"key\":\"metric_type\",\"value\":\"IP\"},{\"key\":\"params\",\"value\":\"{\\\"nprobe\\\":64}\"},{\"key\":\"round_decimal\",\"value\":\"-1\"}]"] [travel_timestamp=0] [guarantee_timestamp=2]
milvus  | [2022/11/21 03:49:33.596 +00:00] [DEBUG] [timerecord/time_recorder.go:91] ["Search: search request enqueue (0ms)"] [traceID=5ab4e948e4721af4]
…
milvus  | [2022/11/21 03:49:33.825 +00:00] [DEBUG] [timerecord/time_recorder.go:91] ["Search: wait search result (228ms)"] [traceID=5ab4e948e4721af4]
milvus  | [2022/11/21 03:49:33.825 +00:00] [DEBUG] [timerecord/time_recorder.go:91] ["Search: wait search result (0ms)"] [traceID=5ab4e948e4721af4]
milvus  | [2022/11/21 03:49:33.825 +00:00] [DEBUG] [proxy/impl.go:2810] ["Search done"] [traceID=5ab4e948e4721af4] [role=proxy] [msgID=437519010644361221] [db=] [collection=works] [partitions="[]"] [dsl=] [len(PlaceholderGroup)=1548] [OutputFields="[]"] [search_params="[{\"key\":\"anns_field\",\"value\":\"embedding\"},{\"key\":\"topk\",\"value\":\"16384\"},{\"key\":\"metric_type\",\"value\":\"IP\"},{\"key\":\"params\",\"value\":\"{\\\"nprobe\\\":64}\"},{\"key\":\"round_decimal\",\"value\":\"-1\"}]"] [travel_timestamp=0] [guarantee_timestamp=2]

```
I guess it costs more in network or client side, could you please check that?

**Comment by mazitovs** [comment]
Yes, I agree, we will check. Thx

However what about that? 
> Are there any better options to get back embeddings from Milvus collection than getting it by collection.query(expr=f'id in {json.dumps(res)}', output_fields=["embedding"]) because loading time is more than 5 minutes?

**Comment by mazitovs** [comment]
@yanliang567 Any updates about question 2?

**Comment by xiaofan-luan** [comment]
/assign @xige-16 
pls help on it

**Comment by xiaofan-luan** [comment]
embedding retrieval is super slow because each request went to S3.

We'll improve the performance by using chunkManager to cache vectors and directly fetch vectors from Knowhere if possible

**Comment by yanliang567** [comment]
> @yanliang567 Any updates about question 2?

As Xiaofan commented above, any more updates or questions?
