### ISSUE TITLE
[Bug]Error: INSTALLATION FAILED with k8s 1.19.1

### ISSUE THREAD

**Issue by smallcai03** [milvus-io/milvus#20708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

k8s版本为1.19.1.   执行helm install my-release milvus/milvus ，
出现Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: SchemaError(io.milvus.v1alpha1.MilvusCluster.spec.components.dataCoord.volumes): array should have exactly one sub-item 。
后来尝试使用milvus operator进行安装仍然出现该问题，
后来又尝试kubesphere也出现该问题。
更新k8s为1.19.8问题依然存在

### Expected Behavior

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: SchemaError(io.milvus.v1alpha1.MilvusCluster.spec.components.dataCoord.volumes): array should have exactly one sub-item 。

### Steps To Reproduce

```markdown
centos7.9.2009
```

### Milvus Log

wu

### Anything else?

wu

**Comment by smallcai03** [comment]
吼吼，知道了~~

**Comment by yanliang567** [comment]
> 吼吼，知道了~~

fixed? do you mind sharing your solution with the community.

**Comment by smallcai03** [comment]
不好意思，这是自动回复。。。
还没解决


caishuping
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "milvus-io/milvus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月18日(星期五) 下午3:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [milvus-io/milvus] [Bug]Error: INSTALLATION FAILED with k8s 1.19.1 (Issue #20708)





  
吼吼，知道了~~
  
fixed? do you mind sharing your solution with the community.

**Comment by Bennu-Li** [comment]
Have you installed milvus-operator? Try to uninstall milvus-operator https://milvus.io/docs/v2.1.x/install_cluster-milvusoperator.md#Uninstall-Milvus-Operator.  And then install milvus again by milvus helm chart.
And It's better to upgrade your k8s version to 1.20+

**Comment by smallcai03** [comment]
Thanks.
I have successfully installed by k8s 1.21.0.
but when I do this command.
&nbsp;&nbsp;kubectl get pods
the status is pending always,Unable to convert running.
how can i do ?


caishuping
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "milvus-io/milvus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月18日(星期五) 晚上7:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [milvus-io/milvus] [Bug]Error: INSTALLATION FAILED with k8s 1.19.1 (Issue #20708)





 
Have you installed milvus-operator? Try to uninstall milvus-operator https://milvus.io/docs/v2.1.x/install_cluster-milvusoperator.md#Uninstall-Milvus-Operator.  And then install milvus again by milvus helm chart.
 And It's better to upgrade your k8s version to 1.20+

**Comment by LoveEachDay** [comment]
@smallcai03 Does you kubernetes cluster has a `default storageclass`? You can verify with the following command:
```
kubectl get storageclass
```

Milvus and its dependencies all reply on the default storageclass to initialize a pvc for storage. You can describe the pending pods to check the status output using this command:
```
kubectl describe pods <pod-name>
```

**Comment by smallcai03** [comment]
吼吼，知道了~~
