### ISSUE TITLE
[Bug]: Incorrect search result of pymilvus example

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#20703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Start a milvus server(2.2)
Run this pymilvus example:  https://github.com/milvus-io/pymilvus/blob/master/examples/example.py

The example insert 10000 vectors into milvus, and then use the No.1 No.2 and No.3 vectors to search. 

![Screenshot from 2022-11-18 11-44-33](https://user-images.githubusercontent.com/2282099/202613687-d9007f44-30ca-4a9a-a771-8c101ea53601.png)

But the result is incorrect, in the result for No.1 vector, the Top0 should be the No.1 vector, but it isn't.
![Screenshot from 2022-11-18 10-15-40](https://user-images.githubusercontent.com/2282099/202613695-70a24cd5-3d86-4ad9-98ef-69ff884d1d05.png)

**Comment by yhmo** [comment]
Same problem: https://github.com/milvus-io/milvus/discussions/20680

**Comment by XuanYang-cn** [comment]
```
  115     search_param = {                                                                                                                        
  116         "data": search_vectors,                                                                                                             
  117         "anns_field": vector_field,                                                                                                         
  118         "param": {"metric_type": _METRIC_TYPE, "params": {"nprobe": _NPROBE}},                                                              
  119         "limit": _TOPK,                                                                                                                     
  120         "expr": "id_field > 0"}    
```

The first vector's `id==0`, and the expr requires `"id_field>0"`, so the first result won't be the NO.1 vector.

change `id_field>0` to `id_field>=0` will get the following:
Search result for 0th vector: 
Top 0: (distance: 0.0, id: 0)
Top 1: (distance: 15.004575729370117, id: 5568)
Top 2: (distance: 15.679189682006836, id: 8573)

Search result for 1th vector: 
Top 0: (distance: 0.0, id: 1)
Top 1: (distance: 14.305086135864258, id: 4011)
Top 2: (distance: 14.806175231933594, id: 3669)

Search result for 2th vector: 
Top 0: (distance: 0.0, id: 2)
Top 1: (distance: 14.328184127807617, id: 5903)
Top 2: (distance: 14.504249572753906, id: 471)
