### ISSUE TITLE
[Enhancement]: Reduce max # of fields to a value < 128

### ISSUE THREAD

**Issue by soothing-rain** [milvus-io/milvus#20729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Milvus stores segment metadata in Etcd, for example the key could look like:
```
"%s/%d/%d/%d/%d", SegmentBinlogPathPrefix, collectionID, partitionID, segmentID, fieldID
```

In the case where there are too many fields in a single segment (Milvus supports up to 255 fields), saving metadata of a single segment can involve > `maxTxnOps` # of Etcd operations, which, if committed in a single Etcd save, can lead to an `too many operations` error.

<img width="489" alt="image" src="https://user-images.githubusercontent.com/69466447/202960674-04598bb7-956a-487d-a861-5916b75f3796.png">

We are currently splitting these Etcd operations into multiple Etcd save calls, but this breaks segment-level atomicity.

IMHO we could reduce the max # of fields per collection in Milvus (from the default 255) for two reason:
1) I don't see a strong need where users need a huge # of fields. (Or there indeed is? please correct me)
2) We could reduce max # of fields to something <128, or even <100 for some extra buffer for atomicity.

**Comment by xiaofan-luan** [comment]
Important, let's do it ASAP

**Comment by yanliang567** [comment]
@binbinlv @NicoYuan1986 please help to check the value in our ci tests.

/assign @NicoYuan1986

**Comment by NicoYuan1986** [comment]
> @binbinlv @NicoYuan1986 please help to check the value in our ci tests.
> 
> /assign @NicoYuan1986

The value in test cases has been modified to 64. #21239

**Comment by NicoYuan1986** [comment]
I think we have completed the change. The new max field number is 64.
Corresponding modifications also have been done. So close the issue.
