### ISSUE TITLE
[Enhancement]: Remove dependency of Etcd server for unit test

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#20748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Use embed etcd server to remove dependency of Etcd server for unit test

### Why is this needed?

Unit tests may fail due to etcd failed to start in github workers

**Comment by xiaofan-luan** [comment]
keep it

**Comment by xiaofan-luan** [comment]
keep it

**Comment by xiaofan-luan** [comment]
we can probably finish it on 3.0

**Comment by congqixia** [comment]
keep it
