### ISSUE TITLE
[Bug]: Cannot connect to Milvus server from a docker container

### ISSUE THREAD

**Issue by bernarde01** [milvus-io/milvus#20752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v3.5
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.1.3
- OS(Ubuntu or CentOS): Debian
- CPU/Memory: 4core/16GB
- GPU: 
- Others:
```

### Current Behavior

When I run Milvus in standalone mode on docker (by executing docker-compose on the default Milvus docker-compose.yml file, resulting in the three containers being created), I cannot connect to the Milvus server from a task running in another docker container on the same host. I have configured this container to be on the same network as the Milvus server, and I can ping the Milvus server from this container via the Milvus server's IP.

### Expected Behavior

When I run:

connections.connect(
    alias="default", 
    host=<milvus-standalone container ip>, 
    port='19530',
    secure=False
    )

I am connected to the Milvus server.

### Steps To Reproduce

```markdown
connections.connect(
    alias="default", 
    host=<milvus-standalone container ip>, 
    port='19530',
    secure=False
    )
```

### Milvus Log

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 115, in _wait_for_channel_ready
    grpc.channel_ready_future(self._channel).result(timeout=3)
  File "/usr/local/lib/python3.7/site-packages/grpc/_utilities.py", line 139, in result
    self._block(timeout)
  File "/usr/local/lib/python3.7/site-packages/grpc/_utilities.py", line 85, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "task.py", line 45, in <module>
    secure=True
  File "/usr/local/lib/python3.7/site-packages/pymilvus/orm/connections.py", line 262, in connect
    connect_milvus(**kwargs, password=password)
  File "/usr/local/lib/python3.7/site-packages/pymilvus/orm/connections.py", line 233, in connect_milvus
    gh._wait_for_channel_ready()
  File "/usr/local/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 118, in _wait_for_channel_ready
    raise MilvusException(Status.CONNECT_FAILED, f'Fail connecting to server on {self._address}. Timeout')
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on 192.168.192.4:19530. Timeout)>

### Anything else?

Milvus standalone containers running:

![image](https://user-images.githubusercontent.com/38493683/203087629-4c4ecc39-4152-4c7c-9877-898882c9c27e.png)

**Comment by bernarde01** [comment]
@yanliang567 I tested the Milvus server with curl <milvus server hostname>:9091/api/v1/health, and got the response:

{"status":"ok"}

I also connected successfully to the server from my localhost with:

connections.connect(
  alias="default", 
  host=<milvus server hostname>, 
  port=19530
)

So it looks like the Milvus server is healthy.

**Comment by yanliang567** [comment]
Then I think we need to check the network between two docker containers. 
@LoveEachDay  any suggestions?

/assgin @LoveEachDay

**Comment by LoveEachDay** [comment]
@bernarde01 You can put the test client container into the `docker-compose.yml` as a new `service`, so that you can access milvus service using `standalone:19530`.

**Comment by bernarde01** [comment]
Thanks @LoveEachDay 
I added the test client container to the `docker-compose.yaml` file, and set the connect command to:
`connections.connect(
        alias="default", 
        host='standalone', 
        port=19530
    )`
I get the same timeout error:`pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on standalone:19530. Timeout)>`

**Comment by bernarde01** [comment]
Turns out this is not a Milvus issue. The problem was caused by our corporate network, and the proxy requirement. In the dockerfile, I need to set the proxy settings to be able to pull images. However, this sets the proxy settings during builld and for the container. These proxy settings prevented communication between the containers. The fix was:

`
FROM python:3.9.12

# Set proxy
ENV https_proxy <proxy settings>

COPY requirements.txt /

RUN pip3 install --proxy <proxy settings> -r requirements.txt

COPY task.py /

ENV https_proxy ""

CMD ["python3", "-u", "task.py"]
`
