### ISSUE TITLE
[Bug]: 2.1->2.2 migration fails due to incorrect Attu image tag

### ISSUE THREAD

**Issue by devennavani** [milvus-io/milvus#20756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The migration script (`deployments/migrate-meta/migrate.sh`) fails because it tries to use the milvusdb/milvus:v2.2.0 image tag to re-deploy Attu.

### Expected Behavior

There should be a special condition inside the `start_milvus_deploy` of the function in the script to use the Zilliz attu tag if the deployment is Attu.

**Comment by yanliang567** [comment]
@devennavani milvus v2.2.0 is the latest release, is there a problem for migration?
/assign @devennavani
