### ISSUE TITLE
[Enhancement]: Query/Search performance suffers from coping & serializing & deserializing data

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#20765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

The QueryNode needs to call segcore (written in C++) to query/search data by CGO, after reviewing this, I found that we can improve the performance significantly by:
- The query/search path copies column data multiple times which is not necessary
- The CGO interfaces use protobuf to transfer data between Go and C++, serializing & deserializing impact performance significantly. According to [this](https://www.cockroachlabs.com/blog/the-cost-and-complexity-of-cgo/), CGO overhead is about 10ns ~ 200ns, which is much less than (de)serializing, we should take more CGO calls but no (de)serializing
- The chunk manager doesn't organize data well for bool and string type, filling data within the two types is very slow, for a binlog, the time/space complexity is roughly $O(nm)$ where $n$ is the number of rows to retrieve, and $m$ is the number of rows of binlog

**Comment by xiaofan-luan** [comment]
@yah01 
Any tools for analyzing escape and allocation?
