### ISSUE TITLE
[Bug]: Binary vector with invalid metric type shouldn't be searched

### ISSUE THREAD

**Issue by longjiquan** [milvus-io/milvus#20766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Binary vector with L2/IP can be searched but the distance is not right as expected.

**Comment by longjiquan** [comment]
![image](https://user-images.githubusercontent.com/31589260/203455987-3a2c383e-5748-4bd0-8d8e-a43569ff7435.png)

**Comment by longjiquan** [comment]
https://github.com/milvus-io/milvus/blob/45205da8f184f908f9cbf222f8ee3e0edb26cf72/internal/core/src/query/SearchBruteForce.cpp#L40

**Comment by cydrain** [comment]
script to reproduce

```python
from pymilvus import connections, FieldSchema, CollectionSchema, DataType, Collection, utility
# this needs the bitstring package
import bitstring

COLLECTION_NAME = 'tanimoto_test'
VECTOR_DIMENSION = 64
METRIC_TYPE = 'JACCARD'
#METRIC_TYPE = 'TANIMOTO'
HOST = '127.0.0.1'
PORT = '19530'

V1 = b'\x01\x23\x45\x67\x89\xab\xcd\xef'
V2 = b'\xfe\xdc\xba\x98\x76\x54\x32\x10'

if __name__ == '__main__':
    connections.connect(
        alias='default',
        host=HOST,
        port=PORT)

    # don't try to create collection and load data if it has already been done
    #if utility.has_collection(COLLECTION_NAME):
    #    connections.disconnect('default')

    fld_idx = FieldSchema(name="id", dtype=DataType.INT64, descrition="int64 primary id",
                          is_primary=True)
    fld_fingerprint = FieldSchema(name="fingerprint", dtype=DataType.BINARY_VECTOR,
                                  descrition="binary vector fingerprint",
                                  dim=VECTOR_DIMENSION, is_primary=False)

    schema = CollectionSchema(fields=[fld_idx, fld_fingerprint],
                              description="test")
    collection = Collection(name=COLLECTION_NAME, schema=schema, using='default')
    assert len(V1) == VECTOR_DIMENSION // 8
    assert len(V2) == VECTOR_DIMENSION // 8
    r = collection.insert([[1, 2], [V1, V2]])
    print(f'Inserted: {r}')

    collection.load()
    #search_params = {"metric_type": METRIC_TYPE}
    search_params = {"metric_type": "L2"}
    res = collection.search([V1], anns_field="fingerprint", param=search_params, limit=2)
    r = res[0]
    print(f'Search result: {r}')

    collection.release()
    collection.drop()

    print('Done.')
```

**Comment by cydrain** [comment]
run above script, sometimes we get empty search result
![Screenshot from 2022-11-23 18-10-47](https://user-images.githubusercontent.com/3992404/203520869-d6c6a1e2-712b-4328-adc0-6e067f847753.png)

sometimes, we get weird search result
![Screenshot from 2022-11-23 18-10-05](https://user-images.githubusercontent.com/3992404/203520969-355a3367-2357-426f-ade3-b68eb6a1c999.png)

**Comment by cydrain** [comment]
Let me explain this issue in detail:
1. why sometimes we see weird search result ?
## In this case, this BINARY_VECTOR's dim is 64, its real data length is 8 bytes.
     When we do search with metric type "L2", we regard each data row's length as "64 float" which is 256 bytes.
     So Milvus accesses out-of-bound memory, and calculate a weird L2 distance.
2. why sometimes we see empty search result ?
## In this case brute force search is called, which uses max heap to store search result.
     max heap is initialized with (id = -1, distance = MAX_FLOAT), the calculated distance is insert into this heap only when it is 
     smaller than the heap top. When the calculated distance is larger than the heap top, this distance is ignored.
     When knowhere return (id = -1, distance = MAX_FLOAT), this result will be ignored by Milvus, so we see empty search result.
3. how to fix this issue ?
## Knowhere has API to do parameter validation check, but it's only for index.
     In this case, no index is created, so we cannot use knowhere's parameter validation check API.
     I suggest to add parameter validation check in "createIndexTask" and "searchTask" in proxy module.

```
	is_float_data_type := (field.GetDataType() == schemapb.DataType_FloatVector)
	is_float_metric_type := funcutil.SliceContain(indexparamcheck.METRICS, metricType)
	if is_float_data_type != is_float_metric_type {
		return fmt.Errorf("data type %s and index type %s mis-match", field.GetDataType().String(), indexType)
	}
```

**Comment by czs007** [comment]
Brute Force search is currently implemented in knowhere, and it is a good choice to handle this case in knowhere.
This case has been handled in segcore before. It's because this MEP(https://wiki.lfaidata.foundation/pages/viewpage.action?pageId=61964400) broke it again.

quick solution：
    You can roll back part of the previous code in segcore to solve this case.
    
  FYI @cydrain @liliu-z

**Comment by cydrain** [comment]
With above fix, Milvus will report err when data type and metric type mis-match
![Screenshot from 2022-11-25 16-51-58](https://user-images.githubusercontent.com/3992404/203940371-468b44f9-8255-4bab-ae59-6294468a5d30.png)

**Comment by xiaofan-luan** [comment]
if user use binary vector metrics does that serve as expected?

**Comment by xiaofan-luan** [comment]
2. in current milvus 2.2, this is not gonna to happen, because load can not happen before index creation, could you double check that's the case? @cydrain

**Comment by cydrain** [comment]
> if user use binary vector metrics does that serve as expected?
have tried 2 scenarioes:
1. create collection with field data type BINARY_VECTOR
    insert data with correct data type
    search with metric type "L2"
2. create collection with field data type FLOAT_VECTOR
    insert data with correct data type
    search with metric type "JACCARD"
in both scenarioes, search will get wrong result

With this fix, search will report error "Data type and metric type mis-match"

**Comment by cydrain** [comment]
> 2. in current milvus 2.2, this is not gonna to happen, because load can not happen before index creation, could you double check that's the case? @cydrain

in milvus 2.2 and master branch, this issue can be reproduced with following steps:
1. create collection with field data type BINARY_VECTOR
2. insert data with correct data type
3. create index with correct metric type and index type
4. search with metric type "L2"

**Comment by cydrain** [comment]
fix has been merged into master and 2.2.0 branch
@yanliang567

**Comment by yanliang567** [comment]
/assign @binbinlv 
please help to verify it

**Comment by binbinlv** [comment]
Verification:
pymilvus: 2.3.0.dev15
master: [master-20221205-243d8cff](https://hub.docker.com/layers/milvusdb/milvus/master-20221205-243d8cff/images/sha256-20d37ac27bf7b12c41e6b1279dd37d540f5f999831cc02bdf7b1c116ebfbe454?context=explore)
mode: standalone and cluster

test case: test_search.py::test_search_binary_flat_with_L2
Result:
code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 1 failed, reason [UnexpectedError] Assert "is_float_data_type == is_float_metric_type" at /go/src/github.com/milvus-io/milvus/internal/core/src/query/SearchBruteForce.cpp:31
 => [BruteForceSearch] Data type and metric type mis-match err %!w(<nil>))>
 (api_request.py:39)
