### ISSUE TITLE
[Bug]: get loading process can not resturn load status

### ISSUE THREAD

**Issue by yelusion2** [milvus-io/milvus#20773]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0
- Deployment mode(standalone or cluster): standalone and cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

get loading process interface only return loading process,  its 0-100.
message GetLoadingProgressResponse {
  common.Status status = 1;
  int64 progress = 2;
}

when collection loaded return 100, how can i know this collection almost loaded or completely loaded ?
when collection have released or never load, this interface return error,  this approach requires the user filter collection load status, but showCollections interface only alone return in memory collection list, it's awkward to use together.
message ShowCollectionsResponse {
  // Contain error_code and reason
  common.Status status = 1;
  // Collection name array
  repeated string collection_names = 2;
  // Collection Id array
  repeated int64 collection_ids = 3;
  // Hybrid timestamps in milvus
  repeated uint64 created_timestamps = 4;
  // The utc timestamp calculated by created_timestamp
  repeated uint64 created_utc_timestamps = 5;
  // Load percentage on querynode when type is InMemory
  // Deprecated: use GetLoadingProgress rpc instead
  repeated int64 inMemory_percentages = 6;
  // Indicate whether query service is available
  repeated bool query_service_available = 7;
}

### Expected Behavior

get loading process interface return load status and loading process;
when collection have released or never load, return load status = 0 and  loading process =-1;
when collection is loading, return load status = 1 and  real  loading process;
when collection have loaded, return load status = 2 and   loading process=100;

### Steps To Reproduce

```markdown
1.create an collection do not load;
2.get this collection loading process;
3.show collections
4.load this collection
5.get this collection loading process;
6.show collections
```

**Comment by yanliang567** [comment]
please make sure all the changes are within milvus server, or you have to update it to all the sdk maintainers.
