### ISSUE TITLE
[Bug]: search get stuck

### ISSUE THREAD

**Issue by lvmnn** [milvus-io/milvus#20794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.4
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

After restarting milvus, search is stuck. try to roll back the restart, cannot recover

we have 2 query node, Observation logs show that one query node is stuck in front of reduce。

Normal querynode log：
![image](https://user-images.githubusercontent.com/92595690/203526195-696a8fe7-cc14-49fa-bcd8-023c837d554a.png)

Abnormal query node logs：
![image](https://user-images.githubusercontent.com/92595690/203526286-ef5fa2a9-bdc8-4c87-9631-9afd1efd7c53.png)

proxy logs:
![image](https://user-images.githubusercontent.com/92595690/203526445-d81bcfeb-1892-482a-b081-0d9718729289.png)

**Comment by lvmnn** [comment]
[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/10074742/milvus-log.tar.gz)

**Comment by lvmnn** [comment]
[bw_etcd_ALL.221123-185223.bak.gz](https://github.com/milvus-io/milvus/files/10074760/bw_etcd_ALL.221123-185223.bak.gz)

**Comment by yanliang567** [comment]
@lvmnn quick question, how long did you wait after milvus restart? I am asking because I want to make sure the collection completed reload after restart.

/assign @jiaoew1991

**Comment by lvmnn** [comment]
[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/10080703/milvus-log.tar.gz)
[bw_etcd_ALL.221124-115350.bak.gz](https://github.com/milvus-io/milvus/files/10080706/bw_etcd_ALL.221124-115350.bak.gz)

**Comment by Cheung7788** [comment]
Use birdwatcher cmd " repair-channel --collection [collection_id] --run " fix this issue.
birdwatcher github link: https://github.com/milvus-io/birdwatcher/blob/main/README.md

**Comment by lvmnn** [comment]
> Use birdwatcher cmd " repair-channel --collection [collection_id] --run " fix this issue. birdwatcher github link: https://github.com/milvus-io/birdwatcher/blob/main/README.md

thx,Already solved
