### ISSUE TITLE
[Bug]: fail to search or query on exisiting collection after upgrading from 2.1 to 2.2 

### ISSUE THREAD

**Issue by hukang6677** [milvus-io/milvus#20798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0
- Deployment mode(standalone or cluster):cluster（helm）
- SDK version(e.g. pymilvus v2.0.0rc2):2.1.0
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 256
- GPU: 
- Others:
```

### Current Behavior

将milvus从2.1升级到2.2
从新加载之前的collection（vehicle_feature20220926），然后search/query 都失败。报超时异常
![image](https://user-images.githubusercontent.com/102129512/203675210-6db2055c-44f3-469a-81ce-4d5884737d4d.png)

### Expected Behavior

collection（vehicle_feature20220926）加载后能正常查询

### Milvus Log

[1124milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/10080211/1124milvus-log.tar.gz)

**Comment by yanliang567** [comment]
@hukang6677 did you run migrations before upgrading to 2.2.0? Please check the guide https://milvus.io/docs/v2.2.x/upgrade_milvus_cluster-helm.md for details if not. The other workaround is release the collection, drop the index, rebuild the index and reload the collection.

/assign @hukang6677

**Comment by hukang6677** [comment]
我对milvus集群做了下面的操作
对原2.1.1的milvus执行了helm uninstall my-release 操作，
然后重新安装了2.2.0（helm repo update  /  helm install my-release milvus/milvus）

**Comment by hukang6677** [comment]
对原有 collection（vehicle_feature20220926）做了 rebuild the index and reload the collection.

**Comment by yanliang567** [comment]
@hukang6677 did you drop the previous index? It seems that the collection failed to recognize the meta of index file.
```
Assert "field_indexing->metric_type_ == search_info.metric_type_" at /go/src/github.com/milvus-io/milvus/internal/core/src/query/SearchOnSealed.cpp:39
 => Metric type of field index isn't the same with search info
```

**Comment by hukang6677** [comment]
![image](https://user-images.githubusercontent.com/102129512/203700466-c13ff3d0-74a2-4668-875a-5d1d3b2dbca5.png)
![image](https://user-images.githubusercontent.com/102129512/203700495-7b50b760-8aa6-4636-bfd3-1cf6be269bd6.png)

**Comment by hukang6677** [comment]
重新创建索引会报 “Network Error”
![image](https://user-images.githubusercontent.com/102129512/203706842-4b93ac92-1b6b-42c2-9808-427778d9c87a.png)

**Comment by yanliang567** [comment]
please try with this order:
1. release the collection
2. drop the index
3. build the index
4. load the collection

**Comment by hukang6677** [comment]
yes, I did it in that order

**Comment by xiaofan-luan** [comment]
@hukang6677 is this an issue?
Looks like you are building index with one metric and search in another metrics.
could you offer your current test code?

**Comment by longjiquan** [comment]
According to the log, you built index with metric type `L2`. So searching with `L2` is also required. @hukang6677
