### ISSUE TITLE
[Bug]: Fix inaccurate `querynode_num` metric.

### ISSUE THREAD

**Issue by soothing-rain** [milvus-io/milvus#20796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

<img width="451" alt="img_v2_9d30af36-269b-41e4-bc86-350805bad80g" src="https://user-images.githubusercontent.com/69466447/203539644-7251b347-b26c-487b-8746-733ce8c11145.png">

`querynode_num` metric seems unreasonably high when user only spun up 10 querynodes.

**Comment by yah01** [comment]
The QueryNode will be removed after balance done, but this task may hang for a very long time (known issue of v2.1). Fixed within v2.2.
