### ISSUE TITLE
[Bug]: Search got stuck after I inserted  2 million into collection with 19 million vector.

### ISSUE THREAD

**Issue by dzqoo** [milvus-io/milvus#20795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 4 querynode with 4c24GBi 
- GPU: 
- Others:
```

### Current Behavior

When I inserted 2 million data into milvus, my following search is got stuck. And I got following error from querycoor：
<img width="856" alt="62938a5a24857169f203c4b08b0e076" src="https://user-images.githubusercontent.com/8862305/203538046-f06d5e38-eb1c-47dd-9fa8-60f535cf7b69.png">

Here is all the logs:
[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/10075133/milvus-log.tar.gz)
Here is all the meta data:
[bw_etcd_ALL.221123-194552.bak.gz](https://github.com/milvus-io/milvus/files/10075134/bw_etcd_ALL.221123-194552.bak.gz)

**Comment by congqixia** [comment]
Found one channel did not return search error:
`channel=by-verify-rootcoord-dml_24_437541159718619631v0`

**Comment by xiaofan-luan** [comment]
see a second hang on GetDataDistribution.

seems to be a deadlock issue. Invesigating
