### ISSUE TITLE
[Bug]: Docker for The meta migration image tag is wrong

### ISSUE THREAD

**Issue by jennyli-z** [milvus-io/milvus#20801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
https://milvus.io/docs/v2.2.x/upgrade_milvus_cluster-helm.md
```

### Current Behavior

![image](https://user-images.githubusercontent.com/93511422/203678959-58547e3c-0e29-4876-888a-9ad3aaf16bfc.png)

### Expected Behavior

should be
milvusdb/meta-migration:v2.2.0
 https://hub.docker.com/layers/milvusdb/meta-migration/v2.2.0/images/sha256-105827119413a141fc1782a39f4f7e2844d9947bfd4c5b0f36673836a6c8ee18?context=repo

**Comment by yanliang567** [comment]
verified fixed
