### ISSUE TITLE
[Bug]: After creating index, total indexed rows may be 0

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#20818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-20816/1/pipeline

**Comment by xiaocai2333** [comment]
1. When the state of a segment is `flushing`, the flush operation is considered done.
2. But the interface `GetFlushedSegments` return flushed segments.
3. In this case, the segments state are `flushing`, so IndexCoord get flushed segments is empty.
4. So the `total_rows` is 0.

**Comment by xiaocai2333** [comment]
fixed, close it.
/close
