### ISSUE TITLE
[Bug]: inserted data disappeared after searching successfully for a new mins

### ISSUE THREAD

**Issue by SunYusheng** [milvus-io/milvus#20811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS): Ubuntu20 WSL2
- CPU/Memory:  16G
- GPU:  -
- Others:  docker 2.2.0 yaml
```

### Current Behavior

when I insert some entities. everything is OK. and can do search operation. but just a few minutes later, all the entities dispeared. the entities count is zero.  collection schema info can still be readed. but the collection is totally empty !

**Comment by yanliang567** [comment]
@SunYusheng Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign

**Comment by SunYusheng** [comment]
[standalone.zip](https://github.com/milvus-io/milvus/files/10084042/standalone.zip)
[etcd.zip](https://github.com/milvus-io/milvus/files/10084060/etcd.zip)
zipped logs

**Comment by gbmarc1** [comment]
I seem to experience the same thing. My collection becomes empty after the first search or when I am in debug mode and I wait long enough.
I am using the same version and deployment mode (standalone).

**Comment by SimFG** [comment]
From the log file, this issue is caused by the small collection ttl property, which is set `15s`.
![image](https://user-images.githubusercontent.com/21985684/206682999-2009f031-6c57-4c5f-bd1b-b245e89f94d4.png)
You can remove this priperty.
@SunYusheng @gbmarc1

**Comment by gbmarc1** [comment]
Thanks @SimFG, it was indeed the ttl. Everything works as expected for me.

**Comment by xiaofan-luan** [comment]
close the issue for now. 
We also changed the document

**Comment by AwesomeYuer** [comment]
@SimFG this issue seems to persist, and I have left this property unset in Python

·```
# def set_properties(collection):
    # https://github.com/milvus-io/milvus/issues/21731
    # [Bug]: The data disappears from the object store without ttl #21731
    # collection.set_properties(properties={"collection.ttl.seconds": 1800})
```

https://github.com/AwesomeYuer/milvus-sample-notebooks/blob/master/milvus.sample.ipynb

![image](https://user-images.githubusercontent.com/1026479/236705245-0ad4a097-c51b-4cc8-b5d4-661900cf971b.png)

![image](https://user-images.githubusercontent.com/1026479/236705260-40571eb1-58a2-4164-85f1-218164789fc3.png)
