### ISSUE TITLE
[Bug]: Upgrading to 2.2.0 breaks S3 access

### ISSUE THREAD

**Issue by geroz** [milvus-io/milvus#20823]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0
- Deployment mode(standalone or cluster): Standalone
```

### Current Behavior

We've been running milvus backed by S3. When we try to upgrade to 2.2.0, we get this error:

`{"level":"WARN","time":"2022/11/23 18:36:12.842 +00:00","caller":"storage/minio_chunk_manager.go:103","message":"failed to check blob bucket exist","bucket":"milvus-dev","error":"Access Denied."}`

This is with no other changes to the config whatsoever, the credentials and settings are confirmed good. If we set the image back to any version prior to 2.2.0, it works again.

**Comment by xiaofan-luan** [comment]
seems to be a access issue, @LoveEachDay any idea on this?

**Comment by LoveEachDay** [comment]
@geroz Could you provide the `minio` config section in the `configs/milvus.yaml`？ Do remove the `accessKeyID` and `secretAccessKey` config options.

**Comment by JiehangXie** [comment]
> 

same to me, this is the milvus.yaml file and docker-compose file

milvus.yaml
`
minio:
  address: localhost
  port: 9000
  accessKeyID: pUFn4Hfcxxxxx
  secretAccessKey: qkNSvgYvD3Swb3BGEXvwimMOci11xxx
  useSSL: false
  bucketName: "milvus"
  rootPath: files
  useIAM: false
  cloudProvider: "aws"
  iamEndpoint: ""

`

docker-compose file
`
  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.0
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
      - /home/dell/develop/milvus/milvus.yaml:/milvus/configs/milvus.yaml
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
`

**Comment by LoveEachDay** [comment]
@JiehangXie The `MINIO_ADDRESS` env is missing in the `standalone` section of the `docker-compose.yml` . 
```
  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.0
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
```

**Comment by JiehangXie** [comment]
> 

it doesnt work and cause a new error like the log below.
[err.log](https://github.com/milvus-io/milvus/files/10103678/err.log)

**Comment by geroz** [comment]
@LoveEachDay my `values.yaml`:
```
milvus.minio.enabled: false
milvus.externalS3.enabled: true
milvus.externalS3.bucketName: milvus-dev
milvus.externalS3.host: s3.us-east-1.amazonaws.com
milvus.externalS3.port: 443
milvus.externalS3.useSSL: true
milvus.externalS3.useIAM: false
```
The key id and secret are provided via environment variables `MINIO_ACCESS_KEY` and `MINIO_SECRET_KEY`. As mentioned this config has been working fine with any image prior to 2.2.0.

**Comment by JiehangXie** [comment]
> @JiehangXie The `MINIO_ADDRESS` env is missing in the `standalone` section of the `docker-compose.yml` .
> 
> ```
>   standalone:
>     container_name: milvus-standalone
>     image: milvusdb/milvus:v2.2.0
>     command: ["milvus", "run", "standalone"]
>     environment:
>       ETCD_ENDPOINTS: etcd:2379
>       MINIO_ADDRESS: minio:9000
>     volumes:
> ```

attempt #6:Get "http://127.0.0.1:9000/milvus/?location=": dial tcp 127.0.0.1:9000: connect: connection refused
attempt #7:Get "http://127.0.0.1:9000/milvus/?location=": dial tcp 127.0.0.1:9000: connect: connection refused
attempt #8:Get "http://127.0.0.1:9000/milvus/?location=": dial tcp 127.0.0.1:9000: connect: connection refused
attempt #9:Get "http://127.0.0.1:9000/milvus/?location=": dial tcp 127.0.0.1:9000: connect: connection refused
attempt #10:Get "http://127.0.0.1:9000/milvus/?location=": dial tcp 127.0.0.1:9000: connect: connection refused
attempt #11:Get "http://127.0.0.1:9000/milvus/?location=": dial tcp 127.0.0.1:9000: connect: connection refused

**Comment by LoveEachDay** [comment]
> @LoveEachDay my `values.yaml`:
> 
> ```
> milvus.minio.enabled: false
> milvus.externalS3.enabled: true
> milvus.externalS3.bucketName: milvus-dev
> milvus.externalS3.host: s3.us-east-1.amazonaws.com
> milvus.externalS3.port: 443
> milvus.externalS3.useSSL: true
> milvus.externalS3.useIAM: false
> ```
> 
> The key id and secret are provided via environment variables `MINIO_ACCESS_KEY` and `MINIO_SECRET_KEY`. As mentioned this config has been working fine with any image prior to 2.2.0.

You'd login to the milvus standalone pod, check the `milvus.yaml` at path `/milvus/configs/milvus.yaml` .

**Comment by yanliang567** [comment]
@geroz @JiehangXie hey guys, do this issue resolved on your sides?

**Comment by geroz** [comment]
Not really, we just went back to 2.1.4 until this gets fixed.

**Comment by ivancili** [comment]
@geroz I ran into the same issue, and after inspecting the codebase to see how environment variables are loaded, I was able to solve this issue by setting the following env variables (i also use external s3 with Milvus version 2.2.3):
```
    extraEnv:
      - name: minio.accessKeyID
        valueFrom:
          secretKeyRef:
            name: milvus-secret
            key: accessKey
      - name: minio.secretAccessKey
        valueFrom:
          secretKeyRef:
            name: milvus-secret
            key: secretKey
```
This is the file where you can find all configurable variables, look for `Key` struct member: https://github.com/milvus-io/milvus/blob/master/internal/util/paramtable/service_param.go

**Comment by xiaofan-luan** [comment]
> le where you can find all configurable variables, look for `Key` struct member: https://github.com/milvus-io/milvus/blob/master/internal/util/paramtable/service_param.go

Great! thanks for the solution!

**Comment by ivancili** [comment]
@xiaofan-luan Just a note, the original issue occurs because Milvus stopped reading environment variables related to Minio, which is a breaking change obviously. Compare [base_table.go](https://github.com/milvus-io/milvus/blob/v2.1.4/internal/util/paramtable/base_table.go) in v2.1.4 and [base_table.go](https://github.com/milvus-io/milvus/blob/v2.2.0/internal/util/paramtable/base_table.go) v2.2.0, you'll notice the code that used to read `MINIO_*` variables is gone.

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan Just a note, the original issue occurs because Milvus stopped reading environment variables related to Minio, which is a breaking change obviously. Compare [base_table.go](https://github.com/milvus-io/milvus/blob/v2.1.4/internal/util/paramtable/base_table.go) in v2.1.4 and [base_table.go](https://github.com/milvus-io/milvus/blob/v2.2.0/internal/util/paramtable/base_table.go) v2.2.0, you'll notice the code that used to read `MINIO_*` variables is gone.

@LoveEachDay do we want to solve the issue? or this won't be a issue in later version?

**Comment by xiaofan-luan** [comment]
@jiaoew1991  @LoveEachDay 
we might want to keep the environment variable there? What do you guys think?

**Comment by jiaoew1991** [comment]
> @jiaoew1991 @LoveEachDay we might want to keep the environment variable there? What do you guys think?

we still have environment variables as configs 🤔

**Comment by Nirbhay2727** [comment]
what are the final milvus.yaml and docker-compose.yml files? this will be of great help as I cannot find them elsewhere

**Comment by guycohenzedek** [comment]
Any updates?

**Comment by JiehangXie** [comment]
这是自动回复邮件。
 
您好，您的邮件已到达我的邮箱，我将尽快查阅并回复，谢谢。Hello, I have reveived your email. But due to the time differences and my busy work, perhaps I will reply to you in 24 to 48 hours.

**Comment by xiaofan-luan** [comment]
> Any updates? I'm using Milvus standalone 2.4.1

this is a very old issue. what is your problem for now?
