### ISSUE TITLE
[Bug]: Search return empty results while querynode recovering

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#20841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/51370125/203959693-ebf83394-926f-40bd-840c-92ef0e19f91f.png)

### Expected Behavior

1. milvus master cluster 1 QN, 1 DN (`milvus run querynode &> querynode.log &`)
2. prepare a collection with 20 sealed segments, dim=128, numRows=5,000,000; create index, load.
3. Loop unlimited: Search with nq=1, print latency
4. start the second QN `milvus run querynode --alias=1 &> querynode1.log &`
5. stop the first QN: `milvus stop querynode`

Observe:
1. `tail -f querynode1.log | grep "segments distribution"`
2. `tail -f proxy | grep "WARN"`
3. The search latency of step3

Current Behaviour:

1. Before querynode1 load all segments done(collection available), proxy will get empty results.

**Comment by XuanYang-cn** [comment]
See also #20502

**Comment by xiaofan-luan** [comment]
so this is only a issue on master right?

**Comment by XuanYang-cn** [comment]
> so this is only a issue on master right?

I just tested on 2.2.0 and it reproduced.

**Comment by XuanYang-cn** [comment]
/assign @yah01 
Please help investigating.

**Comment by yah01** [comment]
The QueryCoord detects the offline event of QueryNode in 1min (etcd lease timeout), during the lag, QueryCoord can't pull the distribution of the QueryNode, and considers it's online. The solutions are:
1. Check TargetID in QueryNode Query/Search
2. QueryCoord shouldn't returns QueryNodes whose distribution have been not updated for a while (much less than 1min)

**Comment by XuanYang-cn** [comment]
Add a new node, after 1min the search fails forever
![image](https://user-images.githubusercontent.com/51370125/205592519-0a6f8249-62bb-4352-8ced-65d61b7578c0.png)

/assign @yah01 
/unassign

**Comment by yah01** [comment]
not reproduced with [11e44](https://github.com/milvus-io/milvus/commit/11e4445ef7e60cbed53a91ba1f4876473dab3aa8) for me

**Comment by XuanYang-cn** [comment]
verified at e131915207e5982a8e9675c6a5412a705c081887
