### ISSUE TITLE
[Bug]: collection ttl only happened after compact

### ISSUE THREAD

**Issue by janej2013** [milvus-io/milvus#20842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.2.0
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

using pymilvus==2.2.0
1. create collection with `properties={"collection.ttl.seconds": 60}`.
2. insert 100 vectors.
3. wait for 10mins, the 100 vectors still can be searched, and collection num_entites = 100.
4. insert 500,000 vectors. 
5. grafana dashboard "Compaction Latency" table shows auto compaction just happened once.
6. after the compaction, memory usage decreased by 1 GB, collection num_entites = 0 and no vector can be searched.
7. insert 200,000 vectors.
8. wait for 10mins, no auto compaction happened, vectors still can be searched, and collection num_entites = 200,000.
9. so I manually compact once using pymilvus.
10. now, collection num_entites = 0 and no vector can be searched.

### Expected Behavior

please confirm:  is there any relation between compaction and collection ttl ?

if collection ttl can only happened after compact, it would be a great help to make that clear in Milvus Docs.

**Comment by yanliang567** [comment]
@janej2013 yes, this is by design. 
@xiaofan-luan any plans to create a doc to introduce the details about compaction and collection ttl?

/assign @janej2013  @xiaocai2333

**Comment by xiaofan-luan** [comment]
Yes Currently, ttl only happens on compaction.
There are two things to figure out:
1. should we have some guarantee? If certain percentage of the entity is expired, should we trigger a compaction automatically?
2. Do we want to filter out all the expired entities?
@janej2013 if you can share your scenario maybe we can do a bit more on TTL design
