### ISSUE TITLE
[Bug]: TestDeleteOperation not stable

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#20856]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

UT failed on master

<img width="931" alt="image" src="https://user-images.githubusercontent.com/83447078/204206332-f4c09730-4f99-4540-9e9e-ecdbe65d490b.png">

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-20845/2/pipeline

**Comment by congqixia** [comment]
See also #20575
