### ISSUE TITLE
[Bug]: Loading progress shows error instead of 0% for not loaded partitions

### ISSUE THREAD

**Issue by JohannesMessner** [milvus-io/milvus#20867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.2.0
- OS(Ubuntu or CentOS): Ubuntu
```

### Current Behavior

When a collection is not loaded, calling `loading_progress()` on it raises
```terminal
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection 437683206696992896 has not been loaded to memory or load failed)>
```
instead of returning 0%.

This seems to be a regression, I found this older bug report here: https://github.com/milvus-io/milvus/issues/18033, although I am not using multiple replicas.

### Expected Behavior

return a loading progress of 0%

### Steps To Reproduce

```markdown
Run the script below:

import numpy as np
from pymilvus import (
    connections,
    Collection,
    FieldSchema,
    DataType,
    CollectionSchema,
    has_collection,
    loading_progress, MilvusException,
)

conn_alias = 'my_conn'
connections.connect(
            alias=conn_alias, host='localhost', port=19530
        )


def create_coll():
    document_id = FieldSchema(
        name='document_id', dtype=DataType.VARCHAR, max_length=100
    )
    offset = FieldSchema(
        name='offset',
        dtype=DataType.VARCHAR,
        max_length=100,
        is_primary=True,
    )
    dummy_vector = FieldSchema(
        name='dummy_vector', dtype=DataType.FLOAT_VECTOR, dim=1
    )

    schema = CollectionSchema(
        fields=[offset, document_id, dummy_vector],
        description='offset2id for DocumentArray',
    )

    return Collection(
        name='testcollection_offset2iddjajsdblsdfablabseflasdf',
        schema=schema,
        using=conn_alias,
        # **self._config.collection_config,  # we probably don't want to apply the same config here
    )


def build_index(coll):
    offset_index_params = {
        'metric_type': 'L2',
        'index_type': 'IVF_FLAT',
        'params': {'nlist': 1024},
    }
    coll.create_index(
        field_name='dummy_vector', index_params=offset_index_params
    )


coll = create_coll()
build_index(coll)
print(loading_progress(coll.name, using=conn_alias))
```

### Anything else?

Seems to be a regression from here: https://github.com/milvus-io/milvus/issues/18033, although I am not using multiple replicas.

**Comment by xiaofan-luan** [comment]
Hi @JohannesMessner ,

This is kind of by design, we don't expect user to call loading_progress before load.
I thought there are some other API to check collection load states, if you want to know if a collection is loaded or not

**Comment by JohannesMessner** [comment]
@xiaofan-luan thanks for your response!
If there is a different API for this, then I could not find it it. Actually, that's why it was recommended to me to use `loading_progress()` in the first place. Could you maybe point me to this API?

Also, this was not the case in v2.1.3, and this changed behaviour is breaking our integration with Milvus. So I would argue that this is a bug (and the ticket I referenced above seems to agree), or at least a breaking change. To me it is very unexpected that a method called `loading_progress()` would require me to have knowledge of the loading state beforehand, or potentially break if I don't
.
I think with some effort I can work around it, but it would not be a pleasant experience for the end user and might have performance impacts.

**Comment by yhmo** [comment]
@JohannesMessner 
Why you need to call `loading_progress(coll.name, using=conn_alias)` after `build_index(coll)`? Do you expect to check the index building progress? If yes, you can use the `utility.index_building_progress(collection_name, index_name='', using='default')` to check. This method returns a json object with key "indexed_rows" and "total_rows", if the value of "indexed_rows" is equal to "total_rows", that means the index progress is 100%.

**Comment by JohannesMessner** [comment]
No, I 'm just trying to check if a collection is or is not loaded into memory.

The code above is just a snippet for reproducibility, in our real application it is not always known if `load()` has been called before I make the call to `loading_progress()`, or if `loading_progress()` is called directly after index creation.

[Our app](https://github.com/docarray/docarray) (for the purposes of this issue) is basically a fancy wrapper and some extra functionality around the PyMilvus client, so a lot of stuff can happen in a lot of different orders, and I need a way to know if a collection is already loaded into memory or not.

So if there is a different API for determinine if `.load()` has been called on a collection, or to tell in a binary way if it is fully loaded into memory, then that would be perfect for my use case! It's just that `loading_progress()` was the closest thing to that that I could find.
And up until the 2.2.0 update this approached worked fine, so if the old non-breaking behaviour of  `loading_progress()` could be maintained, that would also be great.

**Comment by JohannesMessner** [comment]
Hi @yhmo @xiaofan-luan, just checking in, so is this considered a bug that will get fixed, or should I get busy on a workaround on our side? Thanks!

**Comment by xiaofan-luan** [comment]
thought this is a reasonable requirement.
@SimFG  @czs007 do we support check collection load state?

**Comment by SimFG** [comment]
@xiaofan-luan We plan to return `-1` progress value when the collection isn't loaded.
pr link: #20998

**Comment by JohannesMessner** [comment]
Hey guys @xiaofan-luan @SimFG @yanliang567,
I see that #20998 has been closed.
Is there any update on this issue? Will there still be a fix? If so, is there a rough timeline for release?
Thank you!

**Comment by xiaofan-luan** [comment]
there should be another API get_load_state to check whether is collection is loaded.
LoadProgress is only for collection under loading.

**Comment by JohannesMessner** [comment]
That also works for me! Do you think it will be part of the next release?
(Or are you saying it already exists? I couldn't find it in the docs)

**Comment by xiaofan-luan** [comment]
> That also works for me! Do you think it will be part of the next release? (Or are you saying it already exists? I couldn't find it in the docs)

@SimFG is working on this, should be able to ship for next release (2.2.3 , release date would be around by the mid of January).

**Comment by JohannesMessner** [comment]
Perfect, thank you guys!
