### ISSUE TITLE
[Bug]: Search with invalid params doesn't report proper error message, for DiskANN

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#20865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-20861/2/pipeline/

**Comment by xige-16** [comment]
![7TeN9X1LH8](https://user-images.githubusercontent.com/20124155/204426450-5c453cbb-86b5-4b6f-8ca7-619c8d381194.png)

failed due to search timeout, It has nothing to do with the error message of invalid search param

**Comment by xige-16** [comment]
@yah01 
/unassign
