### ISSUE TITLE
[Bug]: Cannot find /milvus/internal/core/output/lib/libjemalloc.so

### ISSUE THREAD

**Issue by xige-16** [milvus-io/milvus#20885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master/5ffbb01
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When running milvus/script/start_cluster.sh, a warning comes out
```
WARN: Cannot find xxx/milvus/internal/core/output/lib/libjemalloc.so
```
And only tbbmalloc.so exists

### Expected Behavior

start milvus with jemalloc

**Comment by Eormeci** [comment]
Is there anyone who solved that issue ? It literally exists;

```
root@da6ffd806772:/opt/milvus/scripts# find / -name "libjemalloc.so" 2>/dev/null
/usr/lib/aarch64-linux-gnu/libjemalloc.so
/opt/milvus/internal/core/output/lib/libjemalloc.so
/opt/milvus/cmake_build/3rdparty_download/jemalloc-subbuild/src/jemalloc_ep/lib/libjemalloc.so
```
 I added them to paths with export command but still gives the same error ..
