### ISSUE TITLE
[Bug]: [docs] Milvus official website search document after 404

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#20906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I use the search bar on the milvus official website, the search results give a page 404

https://user-images.githubusercontent.com/48523564/204759265-3807f492-3939-4d55-8a83-e352e8be9e41.mov

**Comment by shanghaikid** [comment]
Just triggered and index rebuilding from algolia, hopefully it can be fixed soon.

**Comment by shanghaikid** [comment]
fixed
