### ISSUE TITLE
[Bug]: Segment flush may block forever if sync deletes only

### ISSUE THREAD

**Issue by bigsheeper** [milvus-io/milvus#20918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

FlushTaskRunner add `2`(insert task and delete task) to waitGroup:
https://github.com/milvus-io/milvus/blob/67390d208b8251230293b40f7e9297863f1f2dd4/internal/datanode/flush_task.go#L231-L240

However, if the delete buffer size is over 64MB, only the flushDeleteTask would be executed for the segment:
https://github.com/milvus-io/milvus/blob/67390d208b8251230293b40f7e9297863f1f2dd4/internal/datanode/flow_graph_delete_node.go#L120-L137

So FlushTaskRunnter may be blocked forever at `Wait()`:
https://github.com/milvus-io/milvus/blob/67390d208b8251230293b40f7e9297863f1f2dd4/internal/datanode/flush_task.go#L181-L186

**Comment by XuanYang-cn** [comment]
/assign
I'd like to track this issue too.
