### ISSUE TITLE
[Bug]: external kafka can't connect with azure kafka, certificate verify failed

### ISSUE THREAD

**Issue by erezweissgloat** [milvus-io/milvus#20933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.2
- Deployment mode(standalone or cluster):cluster
```

### Current Behavior

When I try to connect to azure kafka, I get the error:

`{"level":"ERROR","time":"2022/12/01 10:35:33.541 +00:00","caller":"kafka/kafka_client.go:77","message":"kafka error","error msg":"sasl_ssl://**:9096/bootstrap: SSL handshake failed: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed: broker certificate could not be verified, verify that ssl.ca.location is correctly configured or root CA certificates are installed (install ca-certificates package) (after 12ms in state SSL_HANDSHAKE, 9 identical error(s) suppressed)","stack":"github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/kafka.(*kafkaClient).getKafkaProducer.func1.1\n\t/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/kafka/kafka_client.go:77"}`

values.yaml:

> externalKafka:
>   enabled: true
>   brokerList: localhost:9092
>   securityProtocol: SASL_SSL
>   sasl:
>     mechanisms: SCRAM-SHA-512
>     username: "KAFKAUSERNAME"
>     password: "KAFKAPASSWORD"
>     caPath: "/certs/ca.crt"

The volume is mount to the pod and to the container, to the same path.
I've verified it's really there /certs/ca.crt inside rootcoord pod.
I've verified it's really in the milvus.yaml inside the rootcoord pod.

For me it seems like you don't consume the caPath from the values.yaml.

### Expected Behavior

Successful connection.

### Steps To Reproduce

```markdown
mentioned above.
```

### Milvus Log

`{"level":"ERROR","time":"2022/12/01 10:39:25.544 +00:00","caller":"kafka/kafka_client.go:77","message":"kafka error","error msg":"sasl_ssl://wn0-gloat.l3pfzs3echaethzoxe32adkzfa.bx.internal.cloudapp.net:9096/bootstrap: SSL handshake failed: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed: broker certificate could not be verified, verify that ssl.ca.location is correctly configured or root CA certificates are installed (install ca-certificates package) (after 11ms in state SSL_HANDSHAKE, 11 identical error(s) suppressed)","stack":"github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/kafka.(*kafkaClient).getKafkaProducer.func1.1\n\t/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/kafka/kafka_client.go:77"}`

### Anything else?

Thank you!

**Comment by LoveEachDay** [comment]
@erezweissgloat We don't support `caPath` config for kafka. You'd make sure the tls certificate is public available.

**Comment by yovelcohen** [comment]
@LoveEachDay you got by any chance a guide or a lead on how to do so in azure?

**Comment by LoveEachDay** [comment]
@erezweissgloat Could your kafka broker use tls certificate which is signed by public CA?

**Comment by erezweissgloat** [comment]
@LoveEachDay Is it just have to be public? or a specific one of azure?

**Comment by LoveEachDay** [comment]
@erezweissgloat If you want enable tls connection between milvus and kafka brokers, milvus will first validate the tls certificate is signed by a trusted CA. If you generate the tls certificate with self-signed CA, milvus will complaining the ca certificates.

BTW, msk certificates is signed by a trusted public CA.

**Comment by erezweissgloat** [comment]
Thanks!
