### ISSUE TITLE
[Bug]: Milvus 2.2.0 can not start

### ISSUE THREAD

**Issue by huuson235** [milvus-io/milvus#20954]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.0
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: Intel i5 16 core / 12GB ram
- GPU: No
- Others:
```

### Current Behavior

My milvus standalone can not start correctly, here is the log from docker. It loop these logs and do not start.

milvus-standalone | [2022/12/02 06:23:29.187 +00:00] [DEBUG] [rootcoord/import_manager.go:164] ["start trying to flip task state"]
milvus-standalone | [2022/12/02 06:23:29.187 +00:00] [INFO] [rootcoord/import_manager.go:780] ["import manager starts loading from Etcd"]
milvus-standalone | [2022/12/02 06:23:29.188 +00:00] [DEBUG] [querycoordv2/services.go:550] ["get metrics request received"] [msgID=0] [metricType="{\"metric_type\":\"system_info\"}"]
milvus-standalone | [2022/12/02 06:23:29.193 +00:00] [DEBUG] [proxy/impl.go:3794] [Proxy.GetProxyMetrics] [node_id=8] [req="{\"metric_type\":\"system_info\"}"] [metric_type=system_info]
milvus-standalone | [2022/12/02 06:23:29.194 +00:00] [DEBUG] [querynode/impl.go:1214] [QueryNode.GetMetrics] [node_id=2] [req="{\"metric_type\":\"system_info\"}"] [metric_type=system_info] [queryNodeMetrics="status:<> response:\"{\\\"has_error\\\":false,\\\"error_reason\\\":\\\"\\\",\\\"name\\\":\\\"querynode2\\\",\\\"hardware_infos\\\":{\\\"ip\\\":\\\"172.18.0.4:21123\\\",\\\"cpu_core_count\\\":16,\\\"cpu_core_usage\\\":0,\\\"memory\\\":16509079552,\\\"memory_usage\\\":149872640,\\\"disk\\\":104857600,\\\"disk_usage\\\":2097152},\\\"system_info\\\":{\\\"system_version\\\":\\\"e7429f88\\\",\\\"deploy_mode\\\":\\\"STANDALONE\\\",\\\"build_version\\\":\\\"v2.2.0\\\",\\\"build_time\\\":\\\"Fri Nov 18 13:26:40 UTC 2022\\\",\\\"used_go_version\\\":\\\"go version go1.18.3 linux/amd64\\\"},\\\"created_time\\\":\\\"2022-12-02 06:10:29.179275318 +0000 UTC m=+0.578221664\\\",\\\"updated_time\\\":\\\"2022-12-02 06:10:29.179275384 +0000 UTC m=+0.578221724\\\",\\\"type\\\":\\\"querynode\\\",\\\"id\\\":2,\\\"system_configurations\\\":{\\\"simd_type\\\":\\\"AVX2\\\"},\\\"quota_metrics\\\":{\\\"Hms\\\":{\\\"ip\\\":\\\"172.18.0.4:21123\\\",\\\"cpu_core_count\\\":16,\\\"cpu_core_usage\\\":0,\\\"memory\\\":16509079552,\\\"memory_usage\\\":149872640,\\\"disk\\\":104857600,\\\"disk_usage\\\":2097152},\\\"Rms\\\":[{\\\"Label\\\":\\\"NQPerSecond\\\",\\\"Rate\\\":0},{\\\"Label\\\":\\\"SearchThroughput\\\",\\\"Rate\\\":0},{\\\"Label\\\":\\\"InsertConsumeThroughput\\\",\\\"Rate\\\":0},{\\\"Label\\\":\\\"DeleteConsumeThroughput\\\",\\\"Rate\\\":0}],\\\"Fgm\\\":{\\\"MinFlowGraphChannel\\\":\\\"\\\",\\\"MinFlowGraphTt\\\":18446744073709551615,\\\"NumFlowGraph\\\":0},\\\"SearchQueue\\\":{\\\"UnsolvedQueue\\\":0,\\\"ReadyQueue\\\":0,\\\"ReceiveChan\\\":0,\\\"ExecuteChan\\\":0,\\\"AvgQueueDuration\\\":0},\\\"QueryQueue\\\":{\\\"UnsolvedQueue\\\":0,\\\"ReadyQueue\\\":0,\\\"ReceiveChan\\\":0,\\\"ExecuteChan\\\":0,\\\"AvgQueueDuration\\\":0}}}\" component_name:\"querynode2\" "]
milvus-standalone | [2022/12/02 06:23:29.194 +00:00] [DEBUG] [datacoord/services.go:870] [DataCoord.GetMetrics] [node_id=5] [req="{\"metric_type\":\"system_info\"}"] [metric_type=system_info] [metrics="status:<> response:\"{\\\"cluster\\\":{\\\"self\\\":{\\\"has_error\\\":false,\\\"error_reason\\\":\\\"\\\",\\\"name\\\":\\\"datacoord5\\\",\\\"hardware_infos\\\":{\\\"ip\\\":\\\"172.18.0.4:13333\\\",\\\"cpu_core_count\\\":16,\\\"cpu_core_usage\\\":0,\\\"memory\\\":16509079552,\\\"memory_usage\\\":150241280,\\\"disk\\\":104857600,\\\"disk_usage\\\":2097152},\\\"system_info\\\":{\\\"system_version\\\":\\\"e7429f88\\\",\\\"deploy_mode\\\":\\\"STANDALONE\\\",\\\"build_version\\\":\\\"v2.2.0\\\",\\\"build_time\\\":\\\"Fri Nov 18 13:26:40 UTC 2022\\\",\\\"used_go_version\\\":\\\"go version go1.18.3 linux/amd64\\\"},\\\"created_time\\\":\\\"2022-12-02 06:10:29.382873864 +0000 UTC m=+0.781820204\\\",\\\"updated_time\\\":\\\"2022-12-02 06:10:29.382873909 +0000 UTC m=+0.781820250\\\",\\\"type\\\":\\\"datacoord\\\",\\\"id\\\":5,\\\"system_configurations\\\":{\\\"segment_max_size\\\":512},\\\"quota_metrics\\\":{\\\"TotalBinlogSize\\\":0}},\\\"connected_nodes\\\":[{\\\"has_error\\\":false,\\\"error_reason\\\":\\\"\\\",\\\"name\\\":\\\"datanode6\\\",\\\"hardware_infos\\\":{\\\"ip\\\":\\\"172.18.0.4:21124\\\",\\\"cpu_core_count\\\":16,\\\"cpu_core_usage\\\":0,\\\"memory\\\":16509079552,\\\"memory_usage\\\":149872640,\\\"disk\\\":104857600,\\\"disk_usage\\\":2097152},\\\"system_info\\\":{\\\"system_version\\\":\\\"e7429f88\\\",\\\"deploy_mode\\\":\\\"STANDALONE\\\",\\\"build_version\\\":\\\"v2.2.0\\\",\\\"build_time\\\":\\\"Fri Nov 18 13:26:40 UTC 2022\\\",\\\"used_go_version\\\":\\\"go version go1.18.3 linux/amd64\\\"},\\\"created_time\\\":\\\"2022-12-02 06:10:29.55865334 +0000 UTC m=+0.957599680\\\",\\\"updated_time\\\":\\\"2022-12-02 06:10:29.558653381 +0000 UTC m=+0.957599721\\\",\\\"type\\\":\\\"datanode\\\",\\\"id\\\":6,\\\"system_configurations\\\":{\\\"flush_insert_buffer_size\\\":16777216},\\\"quota_metrics\\\":{\\\"Hms\\\":{\\\"ip\\\":\\\"172.18.0.4:21124\\\",\\\"cpu_core_count\\\":16,\\\"cpu_core_usage\\\":0,\\\"memory\\\":16509079552,\\\"memory_usage\\\":149872640,\\\"disk\\\":104857600,\\\"disk_usage\\\":2097152},\\\"Rms\\\":[{\\\"Label\\\":\\\"InsertConsumeThroughput\\\",\\\"Rate\\\":0},{\\\"Label\\\":\\\"DeleteConsumeThroughput\\\",\\\"Rate\\\":0}],\\\"Fgm\\\":{\\\"MinFlowGraphChannel\\\":\\\"\\\",\\\"MinFlowGraphTt\\\":18446744073709551615,\\\"NumFlowGraph\\\":0}}}]},\\\"connections\\\":{\\\"name\\\":\\\"datacoord5\\\",\\\"connected_components\\\":[]}}\" component_name:\"datacoord5\" "] []
milvus-standalone | [2022/12/02 06:23:29.194 +00:00] [DEBUG] [proxy/multi_rate_limiter.go:96] ["RateLimiter setRates"] [rates="[{\"rt\":6,\"r\":1.7976931348623157e+308},{\"rt\":8,\"r\":1.7976931348623157e+308},{\"rt\":9,\"r\":1.7976931348623157e+308},{\"rt\":7,\"r\":1.7976931348623157e+308},{\"rt\":5,\"r\":1.7976931348623157e+308}]"]

**Comment by huuson235** [comment]
milvus-standalone | [2022/12/02 06:55:30.132 +00:00] [ERROR] [grpcclient/client.go:149] ["failed to get client address"] [error="find no available rootcoord, check rootcoord state"] [stack="github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).connect\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:149\ngithub.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).GetGrpcClient\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:122\ngithub.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).callOnce\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:247\ngithub.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:290\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord/client.(*Client).GetComponentStates\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:127\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:65\ngithub.com/milvus-io/milvus/internal/util/retry.Do\n\t/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:37\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:89\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentHealthy\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:104\ngithub.com/milvus-io/milvus/internal/distributed/proxy.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:378\ngithub.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:292\ngithub.com/milvus-io/milvus/cmd/components.(*Proxy).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/proxy.go:53\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:102"]
milvus-standalone | [2022/12/02 06:55:30.132 +00:00] [WARN] [grpcclient/client.go:296] ["rootcoord ClientBase ReCall grpc first call get error "] [error="err: find no available rootcoord, check rootcoord state\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:295 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:127 github.com/milvus-io/milvus/internal/distributed/rootcoord/client.(*Client).GetComponentStates\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:65 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1\n/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:37 github.com/milvus-io/milvus/internal/util/retry.Do\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:89 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:104 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentHealthy\n/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:378 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).init\n/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:292 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Run\n/go/src/github.com/milvus-io/milvus/cmd/components/proxy.go:53 github.com/milvus-io/milvus/cmd/components.(*Proxy).Run\n"]

**Comment by yanliang567** [comment]
@huuson235 Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @huuson235

**Comment by bigsheeper** [comment]
> i'm having same issue here @yanliang567 , here is the logs , same as @huuson235 , it keeps looping same logs https://gist.github.com/msaoudallah/9af59006b4e05920f14950711e6b3614

Seems milvus started successfully:
![image](https://user-images.githubusercontent.com/42060877/207014001-6ed0ccc1-49bb-4cfd-8c48-2f226f7ddcc8.png)

**Comment by huuson235** [comment]
> > i'm having same issue here @yanliang567 , here is the logs , same as @huuson235 , it keeps looping same logs https://gist.github.com/msaoudallah/9af59006b4e05920f14950711e6b3614
> 
> @huuson235 @msaoudallah Seems milvus started successfully: ![image](https://user-images.githubusercontent.com/42060877/207014001-6ed0ccc1-49bb-4cfd-8c48-2f226f7ddcc8.png)

How about this line in my logs:
`milvus-standalone | [2022/12/02 06:55:30.132 +00:00] [ERROR] [grpcclient/client.go:149] ["failed to get client address"] [error="find no available rootcoord, check rootcoord state"] [stack="github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).connect\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:149\ngithub.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).GetGrpcClient\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:122\ngithub.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).callOnce\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:247\ngithub.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:290\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord/client.(*Client).GetComponentStates\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:127\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:65\ngithub.com/milvus-io/milvus/internal/util/retry.Do\n\t/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:37\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:89\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentHealthy\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:104\ngithub.com/milvus-io/milvus/internal/distributed/proxy.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:378\ngithub.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:292\ngithub.com/milvus-io/milvus/cmd/components.(*Proxy).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/proxy.go:53\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:102"]`

**Comment by bigsheeper** [comment]
> 
> How about this line in my logs: `milvus-standalone | [2022/12/02 06:55:30.132 +00:00] [ERROR] [grpcclient/client.go:149] 
> ...

@huuson235 It takes a while for Milvus to init and start, during Milvus init/start, some components of Milvus would be unhealthy state, which is normal, after that, Milvus would start successfully. 

![image](https://user-images.githubusercontent.com/42060877/207242841-47c485b7-1ae0-4782-bd88-f5835ff1cec8.png)
![image](https://user-images.githubusercontent.com/42060877/207242885-19b416a0-8475-453b-9b5b-246fe976ee43.png)

**Comment by yanliang567** [comment]
@huuson235 is this issue resolved for you?

**Comment by huuson235** [comment]
> @huuson235 is this issue resolved for you?

I have installed newest version milvus 2.2.2, newest pymilvus but it's still not started.
Pymilvus exception: ```<MilvusException: (code=2, message=Fail connecting to server on localhost:19530. Timeout)>```
And Milvus logs loop these lines forever.
```
milvus-standalone | [2022/12/19 04:24:14.275 +00:00] [DEBUG] [querycoordv2/services.go:551] ["get metrics request received"] [msgID=0] [metricType="{\"metric_type\":\"system_info\"}"]
milvus-standalone | [2022/12/19 04:24:14.277 +00:00] [DEBUG] [proxy/impl.go:3796] [Proxy.GetProxyMetrics] [node_id=64] [req="{\"metric_type\":\"system_info\"}"] [metric_type=system_info]
milvus-standalone | [2022/12/19 04:24:14.279 +00:00] [DEBUG] [datacoord/services.go:877] [DataCoord.GetMetrics] [node_id=59] [req="{\"metric_type\":\"system_info\"}"] [metric_type=system_info] [metrics="status:<> response:\"{\\\"cluster\\\":{\\\"self\\\":{\\\"has_error\\\":false,\\\"error_reason\\\":\\\"\\\",\\\"name\\\":\\\"datacoord59\\\",\\\"hardware_infos\\\":{\\\"ip\\\":\\\"172.19.0.4:13333\\\",\\\"cpu_core_count\\\":16,\\\"cpu_core_usage\\\":7.6297686053932345,\\\"memory\\\":16509079552,\\\"memory_usage\\\":145481728,\\\"disk\\\":104857600,\\\"disk_usage\\\":2097152},\\\"system_info\\\":{\\\"system_version\\\":\\\"ae5259ca\\\",\\\"deploy_mode\\\":\\\"STANDALONE\\\",\\\"build_version\\\":\\\"v2.2.1\\\",\\\"build_time\\\":\\\"Thu Dec 15 08:33:42 UTC 2022\\\",\\\"used_go_version\\\":\\\"go version go1.18.3 linux/amd64\\\"},\\\"created_time\\\":\\\"2022-12-19 03:45:11.270355199 +0000 UTC m=+0.498148157\\\",\\\"updated_time\\\":\\\"2022-12-19 03:45:11.270355239 +0000 UTC m=+0.498148198\\\",\\\"type\\\":\\\"datacoord\\\",\\\"id\\\":59,\\\"system_configurations\\\":{\\\"segment_max_size\\\":512},\\\"quota_metrics\\\":{\\\"TotalBinlogSize\\\":0}},\\\"connected_nodes\\\":[{\\\"has_error\\\":false,\\\"error_reason\\\":\\\"\\\",\\\"name\\\":\\\"datanode63\\\",\\\"hardware_infos\\\":{\\\"ip\\\":\\\"172.19.0.4:21124\\\",\\\"cpu_core_count\\\":16,\\\"cpu_core_usage\\\":0,\\\"memory\\\":16509079552,\\\"memory_usage\\\":145367040,\\\"disk\\\":104857600,\\\"disk_usage\\\":2097152},\\\"system_info\\\":{\\\"system_version\\\":\\\"ae5259ca\\\",\\\"deploy_mode\\\":\\\"STANDALONE\\\",\\\"build_version\\\":\\\"v2.2.1\\\",\\\"build_time\\\":\\\"Thu Dec 15 08:33:42 UTC 2022\\\",\\\"used_go_version\\\":\\\"go version go1.18.3 linux/amd64\\\"},\\\"created_time\\\":\\\"2022-12-19 03:45:11.471437209 +0000 UTC m=+0.699230172\\\",\\\"updated_time\\\":\\\"2022-12-19 03:45:11.47143734 +0000 UTC m=+0.699230300\\\",\\\"type\\\":\\\"datanode\\\",\\\"id\\\":63,\\\"system_configurations\\\":{\\\"flush_insert_buffer_size\\\":16777216},\\\"quota_metrics\\\":{\\\"Hms\\\":{\\\"ip\\\":\\\"172.19.0.4:21124\\\",\\\"cpu_core_count\\\":16,\\\"cpu_core_usage\\\":0,\\\"memory\\\":16509079552,\\\"memory_usage\\\":145367040,\\\"disk\\\":104857600,\\\"disk_usage\\\":2097152},\\\"Rms\\\":[{\\\"Label\\\":\\\"InsertConsumeThroughput\\\",\\\"Rate\\\":0},{\\\"Label\\\":\\\"DeleteConsumeThroughput\\\",\\\"Rate\\\":0}],\\\"Fgm\\\":{\\\"MinFlowGraphChannel\\\":\\\"\\\",\\\"MinFlowGraphTt\\\":18446744073709551615,\\\"NumFlowGraph\\\":0}}}]},\\\"connections\\\":{\\\"name\\\":\\\"datacoord59\\\",\\\"connected_components\\\":[]}}\" component_name:\"datacoord59\" "] []
milvus-standalone | [2022/12/19 04:24:14.279 +00:00] [INFO] [proxy/multi_rate_limiter.go:96] ["RateLimiter setRates"] [rates="[{\"rt\":5,\"r\":1.7976931348623157e+308},{\"rt\":9,\"r\":1.7976931348623157e+308},{\"rt\":8,\"r\":1.7976931348623157e+308},{\"rt\":6,\"r\":1.7976931348623157e+308},{\"rt\":7,\"r\":1.7976931348623157e+308}]"]
```

**Comment by yanliang567** [comment]
> > @huuson235 is this issue resolved for you?
> 
> I have installed newest version milvus 2.2.1, newest pymilvus but it's still not started. Pymilvus exception: `<MilvusException: (code=2, message=Fail connecting to server on localhost:19530. Timeout)>` And Milvus logs loop these lines forever.
> 
> ```
> milvus-standalone | [2022/12/19 04:24:14.275 +00:00] [DEBUG] [querycoordv2/services.go:551] ["get metrics request received"] [msgID=0] [metricType="{\"metric_type\":\"system_info\"}"]
> milvus-standalone | [2022/12/19 04:24:14.277 +00:00] [DEBUG] [proxy/impl.go:3796] [Proxy.GetProxyMetrics] [node_id=64] [req="{\"metric_type\":\"system_info\"}"] [metric_type=system_info]
> milvus-standalone | [2022/12/19 04:24:14.279 +00:00] [DEBUG] [datacoord/services.go:877] [DataCoord.GetMetrics] [node_id=59] [req="{\"metric_type\":\"system_info\"}"] [metric_type=system_info] [metrics="status:<> response:\"{\\\"cluster\\\":{\\\"self\\\":{\\\"has_error\\\":false,\\\"error_reason\\\":\\\"\\\",\\\"name\\\":\\\"datacoord59\\\",\\\"hardware_infos\\\":{\\\"ip\\\":\\\"172.19.0.4:13333\\\",\\\"cpu_core_count\\\":16,\\\"cpu_core_usage\\\":7.6297686053932345,\\\"memory\\\":16509079552,\\\"memory_usage\\\":145481728,\\\"disk\\\":104857600,\\\"disk_usage\\\":2097152},\\\"system_info\\\":{\\\"system_version\\\":\\\"ae5259ca\\\",\\\"deploy_mode\\\":\\\"STANDALONE\\\",\\\"build_version\\\":\\\"v2.2.1\\\",\\\"build_time\\\":\\\"Thu Dec 15 08:33:42 UTC 2022\\\",\\\"used_go_version\\\":\\\"go version go1.18.3 linux/amd64\\\"},\\\"created_time\\\":\\\"2022-12-19 03:45:11.270355199 +0000 UTC m=+0.498148157\\\",\\\"updated_time\\\":\\\"2022-12-19 03:45:11.270355239 +0000 UTC m=+0.498148198\\\",\\\"type\\\":\\\"datacoord\\\",\\\"id\\\":59,\\\"system_configurations\\\":{\\\"segment_max_size\\\":512},\\\"quota_metrics\\\":{\\\"TotalBinlogSize\\\":0}},\\\"connected_nodes\\\":[{\\\"has_error\\\":false,\\\"error_reason\\\":\\\"\\\",\\\"name\\\":\\\"datanode63\\\",\\\"hardware_infos\\\":{\\\"ip\\\":\\\"172.19.0.4:21124\\\",\\\"cpu_core_count\\\":16,\\\"cpu_core_usage\\\":0,\\\"memory\\\":16509079552,\\\"memory_usage\\\":145367040,\\\"disk\\\":104857600,\\\"disk_usage\\\":2097152},\\\"system_info\\\":{\\\"system_version\\\":\\\"ae5259ca\\\",\\\"deploy_mode\\\":\\\"STANDALONE\\\",\\\"build_version\\\":\\\"v2.2.1\\\",\\\"build_time\\\":\\\"Thu Dec 15 08:33:42 UTC 2022\\\",\\\"used_go_version\\\":\\\"go version go1.18.3 linux/amd64\\\"},\\\"created_time\\\":\\\"2022-12-19 03:45:11.471437209 +0000 UTC m=+0.699230172\\\",\\\"updated_time\\\":\\\"2022-12-19 03:45:11.47143734 +0000 UTC m=+0.699230300\\\",\\\"type\\\":\\\"datanode\\\",\\\"id\\\":63,\\\"system_configurations\\\":{\\\"flush_insert_buffer_size\\\":16777216},\\\"quota_metrics\\\":{\\\"Hms\\\":{\\\"ip\\\":\\\"172.19.0.4:21124\\\",\\\"cpu_core_count\\\":16,\\\"cpu_core_usage\\\":0,\\\"memory\\\":16509079552,\\\"memory_usage\\\":145367040,\\\"disk\\\":104857600,\\\"disk_usage\\\":2097152},\\\"Rms\\\":[{\\\"Label\\\":\\\"InsertConsumeThroughput\\\",\\\"Rate\\\":0},{\\\"Label\\\":\\\"DeleteConsumeThroughput\\\",\\\"Rate\\\":0}],\\\"Fgm\\\":{\\\"MinFlowGraphChannel\\\":\\\"\\\",\\\"MinFlowGraphTt\\\":18446744073709551615,\\\"NumFlowGraph\\\":0}}}]},\\\"connections\\\":{\\\"name\\\":\\\"datacoord59\\\",\\\"connected_components\\\":[]}}\" component_name:\"datacoord59\" "] []
> milvus-standalone | [2022/12/19 04:24:14.279 +00:00] [INFO] [proxy/multi_rate_limiter.go:96] ["RateLimiter setRates"] [rates="[{\"rt\":5,\"r\":1.7976931348623157e+308},{\"rt\":9,\"r\":1.7976931348623157e+308},{\"rt\":8,\"r\":1.7976931348623157e+308},{\"rt\":6,\"r\":1.7976931348623157e+308},{\"rt\":7,\"r\":1.7976931348623157e+308}]"]
> ```

the logs are debug info, which shall not cause the connection failure. Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

**Comment by huuson235** [comment]
It's worked in version 2.2.2. Tks dev team. Close issue.
