### ISSUE TITLE
[Bug]: UnitTest TestChannelManager_StateTransfer is not stable

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#20953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 482986c
- Deployment mode(standalone or cluster): both
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

UnitTest TestChannelManager_StateTransfer is not stable

### Expected Behavior

Unit test shall pass stably 

### Anything else?

https://github.com/milvus-io/milvus/actions/runs/3598585906/jobs/6061477856

**Comment by XuanYang-cn** [comment]
related to #20790
