### ISSUE TITLE
[Bug]: search gradually slowed down

### ISSUE THREAD

**Issue by lvmnn** [milvus-io/milvus#20955]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.4
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Long after the cluster is online，search gradually slowed down，Maybe the index build failed。
the Insert qps=5. segment_size=512M

![image](https://user-images.githubusercontent.com/92595690/205234876-ca17b442-14ac-4ac0-ba1f-3a2d3e42fc85.png)
![image](https://user-images.githubusercontent.com/92595690/205235008-d50e4477-9dea-4cc5-871f-7b2bf45f1bef.png)
![image](https://user-images.githubusercontent.com/92595690/205235102-361d3499-fd7e-4cde-a9a4-7bf5998d110c.png)
![image](https://user-images.githubusercontent.com/92595690/205235153-46284667-aeaa-4f90-9b7d-d22febd373ac.png)
![image](https://user-images.githubusercontent.com/92595690/205235214-9f909204-77aa-4493-be1c-d8a2d871f4a1.png)

### Milvus Log

[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/10138834/milvus-log.tar.gz)
[bw_etcd_ALL.221202-144738.bak.gz](https://github.com/milvus-io/milvus/files/10138836/bw_etcd_ALL.221202-144738.bak.gz)

**Comment by lvmnn** [comment]
The cpu load of the query node is unbalanced

<img width="1386" alt="image" src="https://user-images.githubusercontent.com/92595690/205236442-1eab1b69-ff2f-472f-8efb-88ffa5b8321d.png">

**Comment by lvmnn** [comment]
![image](https://user-images.githubusercontent.com/92595690/205257909-a9b28590-3f46-4145-9f93-7377562cf423.png)

**Comment by lvmnn** [comment]
After manually executing create_index(by pymilvus), we observed that indexnode had created an index, but through birdwather, there was no index.
![image](https://user-images.githubusercontent.com/92595690/205262896-44aa4202-bf4c-4b2f-ae25-5e46b10c9b11.png)

**Comment by lvmnn** [comment]
![image](https://user-images.githubusercontent.com/92595690/205264727-00f329a3-bfe2-49ca-81d6-729a4507a56c.png)

**Comment by yanliang567** [comment]
@lvmnn not all segments are searched in indexed mode
`[2022/12/02 06:50:38.231 +00:00] [DEBUG] [querynode/segment.go:316] ["start do search on segment"] [msgID=437770984929368132] [segmentID=437454180056563713] [segmentType=Sealed] [loadIndex=false]`
this is a known issue that occasionally reproduces in 2.1.x.

**Comment by yanliang567** [comment]
please retry on 2.2.0 or 2.2.1(will release soon next week)

**Comment by lvmnn** [comment]
> @lvmnn not all segments are searched in indexed mode
> 
> `[2022/12/02 06:50:38.231 +00:00] [DEBUG] [querynode/segment.go:316] ["start do search on segment"] [msgID=437770984929368132] [segmentID=437454180056563713] [segmentType=Sealed] [loadIndex=false]`
> 
> this is a known issue that occasionally reproduces in 2.1.x. 
Several of our clusters have similar qustion after manually restarting the cluster. I want to know why this happened. @yanliang567

**Comment by lvmnn** [comment]
![image](https://user-images.githubusercontent.com/92595690/205797290-d5457946-73d5-468e-ab50-4720a7c54300.png)
![image](https://user-images.githubusercontent.com/92595690/205797391-c8a87ed0-3caa-4cd1-b19c-60e39c1f68d7.png)

**Comment by lvmnn** [comment]
A similar situation occurs for another cluster, the grafana view on the business side。
![image](https://user-images.githubusercontent.com/92595690/205798862-dcee842e-a325-4734-9f27-ce177e558896.png)

**Comment by XuanYang-cn** [comment]
@lvmnn Please provide the latest etcd backup and querynode logs.

The querynodes of previous logs don't match with the etcd backup info.

**Comment by XuanYang-cn** [comment]
> @lvmnn Please provide the latest etcd backup and querynode logs.
> 
> The querynodes of previous logs don't match with the etcd backup info.

There're only 8 querynodes in the previous etcd backups and only 7 valid querynode logs. Please provide 16 querynode logs and the latest etcd backup.

**Comment by lvmnn** [comment]
> > @lvmnn Please provide the latest etcd backup and querynode logs.
> > The querynodes of previous logs don't match with the etcd backup info.
> 
> There're only 8 querynodes in the previous etcd backups and only 7 valid querynode logs. Neither of which matches with the metrics info.

the number of Querynodes was expanded for performance reasons. So it's inconsistent.

**Comment by lvmnn** [comment]
[bw_etcd_ALL.221206-153616.bak.gz](https://github.com/milvus-io/milvus/files/10163844/bw_etcd_ALL.221206-153616.bak.gz)

**Comment by lvmnn** [comment]
> bw_etcd_ALL.221206-153616.bak.gz

another cluster log,same question

**Comment by xiaofan-luan** [comment]
@lvmnn did you try to release and reload collection?

**Comment by lvmnn** [comment]
> @lvmnn did you try to release and reload collection?

The retry does solve the problem and the retrieval is faster. But it is not certain that the problem will recur

**Comment by yanliang567** [comment]
@lvmnn any chance to retry to milvus 2.2.1?
