### ISSUE TITLE
[Bug]: drop collection do not delete index_files and rdb_data

### ISSUE THREAD

**Issue by newfacade** [milvus-io/milvus#20960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.0
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.2.0
- OS(Ubuntu or CentOS): macOS 12.6
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Follow the instructions in https://milvus.io/docs/configure-docker.md, I modify `milvus.yaml` in rocksmq
```
retentionTimeInMinutes: 30
```
and dataCoord
```
gc:
    interval: 600
    missingTolerance: 1200
    dropTolerance: 1200
```
to accelerate GarbageCollection, as I met the similar problem as in https://github.com/milvus-io/milvus/issues/18288 and I want to do quick test on my local machine. 
Then I modify `docker-compose.yml`, add a volumes section under each Milvus component, i.e. etcd, minio, and standalone (BTW docs seems forget standalone users in Modify the installation file section). Then I start milvus.

I download `hello_milvus.py` and modify num_entities from 3000 to 3000000 (the only modification I do), the script drop collection at the end.

Hours later after I ran `hello_milvus.py`, only insert log files are deleted. index_files and rdb_data are not deleted.

### Expected Behavior

I expect GarbageCollection to delete insert log files, index_files and rdb_data in an hour.
As I've dropped this collection and modify the configuration.

**Comment by xiaofan-luan** [comment]
for rdb data,  it also depends on rocksdb compaction time period. This might not be able to tune by a config.

If using kafka/pulsar this might be a issue.

**Comment by xiaocai2333** [comment]
@newfacade How do you know the index files is not deleted? What tools did you use? I tested it locally, and the index files can be deleted normally, can you paste the logs here?

**Comment by newfacade** [comment]
> 

By using `du -sh /root/to/localdir/volumes/minio/a-bucket/files/*` all the time, I found that delta_log, insert_log, stats_log are deleted, while index_files are remained, e.g.
<img width="609" alt="WeChat3bb4d63c238bd2aa4c14946f5770b2fb" src="https://user-images.githubusercontent.com/50542807/206081711-96b04f78-efb0-460a-aecc-4af19ccfd2d6.png">
Where are logs, is `volumes/milvus/logs` by default? my easylog.log files here are empty...
<img width="538" alt="WeChat499a65bfc4fc9cbe55925f0266e74b7a" src="https://user-images.githubusercontent.com/50542807/206082069-9d2f8449-8eb4-4a8b-b81e-801e62551cb1.png">

**Comment by newfacade** [comment]
> @newfacade To speed up the `rockmq` storage recycle, you can decrease the `rocksmq.rocksmqPageSize` which defaults to 2G. You may change it to `512MB` which will helps to reclaim the storage used by the rocksmq.

Get. This is the size of the data after running `python hello_milvus.py` (num_entities is modified):
```
(base) facer@localhost tmp % du -sh volumes/*
9.2M	volumes/etcd
443M	volumes/milvus
178M	volumes/minio
```
How does `rocksmq.rocksmqPageSize` works? How to adjust `rocksmq.rocksmqPageSize` to fit my data size (e.g my data size is about 3000000*8 float)?

**Comment by xiaocai2333** [comment]
@newfacade I got it, it's my bad. I will fix it.

**Comment by xiaofan-luan** [comment]
> @newfacade To speed up the `rockmq` storage recycle, you can decrease the `rocksmq.rocksmqPageSize` which defaults to 2G. You may change it to `512MB` which will helps to reclaim the storage used by the rocksmq.

Do we want to make the change by default? 
2G might be a little bit too large

**Comment by xiaocai2333** [comment]
Reasons why index files are not deleted in time:
1. IndexCoord will list all directories prefixed with `index_files`, and then determine whether the files in this directory need to be deleted.
2. But another colleague changed minio's `ListWithPrefix` interface so that it does not return the directory.

**Comment by yanliang567** [comment]
@newfacade could you please retry on milvus 2.2.1
