### ISSUE TITLE
[Bug]: Release collection made Milvus cluster unresponsive

### ISSUE THREAD

**Issue by suesunss** [milvus-io/milvus#20965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.2.0
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0
- OS(Ubuntu or CentOS): debian
- CPU/Memory: 2c(queryndoe)
- GPU: 4g(querynode)
- Others: ETCD and s3 is third-party services deployed on physical machines
```

### Current Behavior

I have a collection with 1m vectors and hnsw index on it. I recently loaded it and used it for search for a while.  I have another field of type VarChar with encoded strings, I want to create a marisa-trie index on it using attu, I failed to do it because the collection haven’t been released yet. Thus I tried to click on the ‘release’ button, however, all of a suddent, the attu window got stuck and the whole Milvus cluster suddenly became unresponsive.

Some trace:

**proxy**

```go
[2022/12/02 10:20:58.393 +00:00] [ERROR] [proxy/task_scheduler.go:453] ["Failed to pre-execute task: create index failed, collection is loaded, please release it first"] [traceID=67ba08ae370adeec] [stack="github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask\n\t/go/src/github.com/milvus-
io/milvus/internal/proxy/task_scheduler.go:453\ngithub.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:488"]
```
(This is an expected behavior as collection must be released before create an index)

**queryndoe**

```go
[2022/12/02 10:21:14.247 +00:00] [ERROR] [grpcclient/client.go:278] ["ClientBase Call grpc first call get error"] [role=querynode] [error="err: rpc error: code = DeadlineExceeded desc = context deadline exceeded\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:277 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call\n/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:371 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).GetDataDistribution\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:176 github.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).GetDataDistribution.func1\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:241 github.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).send\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:171 github.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).GetDataDistribution\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/dist/dist_handler.go:75 github.com/milvus-io/milvus/internal/querycoordv2/dist.(*distHandler).start\n/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit\n"] [stack="github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:278\ngithub.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).GetDataDistribution\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:371\ngithub.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).GetDataDistribution.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:176\ngithub.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).send\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:241\ngithub.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).GetDataDistribution\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:171\ngithub.com/milvus-io/milvus/internal/querycoordv2/dist.(*distHandler).start\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/dist/dist_handler.go:75"]
```
(query node keeps reporting this error message just after we tried to release the collection)

cpu and memory usage for components:

```bash
NAME                                     CPU(cores)   MEMORY(bytes)
milvus-dev-attu-68bc89f9ff-lmbwc         1m           107Mi
milvus-dev-datacoord-84cb95df6f-klb8z    14m          138Mi
milvus-dev-datanode-7859f4b8b5-jv4lz     79m          871Mi
milvus-dev-indexcoord-86c7bd847-qhxrp    4m           138Mi
milvus-dev-indexnode-8c6fbcb54-8rmx2     1m           1202Mi
milvus-dev-indexnode-8c6fbcb54-j7djf     1m           1269Mi
milvus-dev-indexnode-8c6fbcb54-p4q7n     1m           1124Mi
milvus-dev-proxy-7c64b6f595-qnspp        13m          291Mi
milvus-dev-pulsar-bookie-0               25m          3736Mi
milvus-dev-pulsar-bookie-1               29m          4020Mi
milvus-dev-pulsar-bookie-2               34m          3755Mi
milvus-dev-pulsar-broker-0               86m          3341Mi
milvus-dev-pulsar-proxy-0                30m          1543Mi
milvus-dev-pulsar-recovery-0             2m           316Mi
milvus-dev-pulsar-zookeeper-0            3m           483Mi
milvus-dev-pulsar-zookeeper-1            6m           474Mi
milvus-dev-pulsar-zookeeper-2            3m           490Mi
milvus-dev-querycoord-76d5cb9444-qp7bw   9m           143Mi
milvus-dev-querynode-5ff55d9f86-jnnc4    8m           1433Mi
milvus-dev-querynode-5ff55d9f86-wqnwz    7m           1521Mi
milvus-dev-querynode-5ff55d9f86-zgbwk    13m          1512Mi
milvus-dev-rootcoord-8cb78777d-lzcfm     23m          324Mi
```

### Expected Behavior

new index be successfully created

### Milvus Log

[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/10141085/milvus-log.tar.gz)

### Anything else?

ETCD and minio (we use ceph rgw with s3 interface) are deployed using physical machins and they are both running smoothly as far as we noticed.

**Comment by weiliu1031** [comment]
when releaseCollection request submit, querycoord will send releaseSegment and unSubChannel to querynode, and then get data distribution from querynode, which will tell whether segment has been released. 

but for your case:
1. all release tasks have been sent to query node successfully and query node finished all task
2. when query coord get data distribution from 3 query node, only one of them return a response.
3. then query coord doesn't know task status on other two querynode, so releaseCollection request is stucked to wait for all task finished.

about the reason:
1. please check network stats between querycoord and all 3 querynode, to make sure whether exist a second-level lag here
2. maybe there is a dead lock on get data distribution which escape from all test cases, for investigation, we need a pprof dump here, if milvus service haven't been restarted.

about recovery:
if network is fine, restart all querynode will work aound, hope this could help.

**Comment by suesunss** [comment]
> when releaseCollection request submit, querycoord will send releaseSegment and unSubChannel to querynode, and then get data distribution from querynode, which will tell whether segment has been released.
> 
> but for your case:
> 
> 1. all release tasks have been sent to query node successfully and query node finished all task
> 2. when query coord get data distribution from 3 query node, only one of them return a response.
> 3. then query coord doesn't know task status on other two querynode, so releaseCollection request is stucked to wait for all task finished.
> 
> about the reason:
> 
> 1. please check network stats between querycoord and all 3 querynode, to make sure whether exist a second-level lag here

I will investigate if there is a seond-level lag. There is indeed some trace from one of our querynode, saying the liveness/readiness probe failed:

```
Events:
  Type     Reason        Age                 From             Message
  ----     ------        ----                ----             -------
  Warning  Unhealthy     28m                 kubelet          Liveness probe failed: Get "http://10.10.173.252:9091/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy     28m (x3 over 28m)   kubelet          Readiness probe failed: Get "http://10.10.173.252:9091/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  NodeNotReady  27m                 node-controller  Node is not ready
  Warning  Unhealthy     27m (x2 over 27m)   kubelet          Liveness probe failed: HTTP probe failed with statuscode: 500
  Warning  Unhealthy     27m (x3 over 27m)   kubelet          Readiness probe failed: HTTP probe failed with statuscode: 500
  Warning  Unhealthy     25m (x2 over 26m)   kubelet          Liveness probe failed: Get "http://10.10.173.252:9091/healthz": dial tcp 10.10.173.252:9091: connect: connection refused
  Normal   Killing       25m                 kubelet          Container querynode failed liveness probe, will be restarted
  Warning  Unhealthy     18m (x50 over 27m)  kubelet          Readiness probe failed: Get "http://10.10.173.252:9091/healthz": dial tcp 10.10.173.252:9091: connect: connection refused
```
>  then query coord doesn't know task status on other two querynode, so releaseCollection request is stucked to wait for all task finished.

If this is an expected hahavior, then it is weird to me, as **a single Release** manipulation will fail the entire cluser and make it unresponsive. Maybe, It would be better that, at least, some exceptions could be raised to indicate the current state. Or, maybe there are some considerations in terms of the design that I am missing ?


> maybe there is a dead lock on get data distribution which escape from all test cases, for investigation, we need a pprof dump here, if milvus service haven't been restarted.
> 
> about recovery: if network is fine, restart all querynode will work aound, hope this could help.

I've already restarted the querynode, the cluster returns to normal condition.

Moreover, I can no longer reproduce the problem, I can sucessfully release a collection now, no configuration has changed yet.

**Comment by weiliu1031** [comment]
> > when releaseCollection request submit, querycoord will send releaseSegment and unSubChannel to querynode, and then get data distribution from querynode, which will tell whether segment has been released.
> > but for your case:
> > 
> > 1. all release tasks have been sent to query node successfully and query node finished all task
> > 2. when query coord get data distribution from 3 query node, only one of them return a response.
> > 3. then query coord doesn't know task status on other two querynode, so releaseCollection request is stucked to wait for all task finished.
> > 
> > about the reason:
> > 
> > 1. please check network stats between querycoord and all 3 querynode, to make sure whether exist a second-level lag here
> 
> I will investigate if there is a seond-level lag. There is indeed some trace from one of our querynode, saying the liveness/readiness probe failed:
> 
> ```
> Events:
>   Type     Reason        Age                 From             Message
>   ----     ------        ----                ----             -------
>   Warning  Unhealthy     28m                 kubelet          Liveness probe failed: Get "http://10.10.173.252:9091/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
>   Warning  Unhealthy     28m (x3 over 28m)   kubelet          Readiness probe failed: Get "http://10.10.173.252:9091/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
>   Warning  NodeNotReady  27m                 node-controller  Node is not ready
>   Warning  Unhealthy     27m (x2 over 27m)   kubelet          Liveness probe failed: HTTP probe failed with statuscode: 500
>   Warning  Unhealthy     27m (x3 over 27m)   kubelet          Readiness probe failed: HTTP probe failed with statuscode: 500
>   Warning  Unhealthy     25m (x2 over 26m)   kubelet          Liveness probe failed: Get "http://10.10.173.252:9091/healthz": dial tcp 10.10.173.252:9091: connect: connection refused
>   Normal   Killing       25m                 kubelet          Container querynode failed liveness probe, will be restarted
>   Warning  Unhealthy     18m (x50 over 27m)  kubelet          Readiness probe failed: Get "http://10.10.173.252:9091/healthz": dial tcp 10.10.173.252:9091: connect: connection refused
> ```
> 
> (but this seems to be messages after the request is stucked, and the pod got restarted)
> 
> > then query coord doesn't know task status on other two querynode, so releaseCollection request is stucked to wait for all task finished.
> 
> If this is an expected hahavior, then it is weird to me, as **a single Release** manipulation will fail the entire cluser and make it unresponsive. Maybe, It would be better that, at least, some exceptions could be raised to indicate the current state. Or, maybe there are some considerations in terms of the design that I am missing ?
> 
> > maybe there is a dead lock on get data distribution which escape from all test cases, for investigation, we need a pprof dump here, if milvus service haven't been restarted.
> > about recovery: if network is fine, restart all querynode will work aound, hope this could help.
> 
> I've already restarted the querynode, the cluster returns to normal condition.
> 
> Moreover, I can no longer reproduce the problem, I can sucessfully release a collection now, no configuration has changed yet.

it doesn't  means only one single Release operation fail the entire cluster, the root cause is that query coord has no way to know query node's task state when get data distribution failed, so all request will be stuck here. the single result operation is not the trigger reason, it's side effect of invalid status of milvus service.

**Comment by suesunss** [comment]
> looks like querynode-5ff55d9f86-wqnw might stuck due to some reason? If you can use pprof to leave a stack that would be really helpful. To recover fast, you can simply reboot the machine see if it helps

Yes, reboot querynode is helpful. I'll try to investigate into details next time.

**Comment by xiaofan-luan** [comment]
need more information why this is stucked....

**Comment by xiaofan-luan** [comment]
I still thought there is a dead lock here， investigating
