### ISSUE TITLE
[Bug]: Milvus 2.2.0 will make computer shut down when building index

### ISSUE THREAD

**Issue by JiehangXie** [milvus-io/milvus#20972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0
- Deployment mode(standalone or cluster):standalone 
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus v2.2.0
- OS(Ubuntu or CentOS): Windows 11
- CPU/Memory: AMD Ryzen 7 5800X 8-Core/ DDR4 16GB*2
- GPU: RTX 3080 Ti
- Others: The video can be seen in "Milvus用户交流群104"
```

### Current Behavior

When run the api "create_index()", after about half of a minute, the computer will suddenly shut down
Then after restarting the computer, run milvus in docker, without "create_index()" running, after about a minute, the computer will still shut down.

**Comment by JiehangXie** [comment]
the number of vector data is about 32w+

**Comment by JiehangXie** [comment]
The code is 
`    def buildIndex(self):
        """
        建立索引
        """
        index_params = {
                    "index_type": "IVF_SQ8", 
                    "metric_type": "L2",
                    "params": {"nlist": 16384}
                }

        try:
            self.connection.create_index(
                field_name = self.vector_field_name,
                index_params = index_params
            )

            utility.wait_for_index_building(
                collection_name = self.collection_name,
                index_name = self.vector_field_name,
                using = self.alias
            )

            self.load()
            
            utility.wait_for_loading_complete(
                collection_name = self.collection_name,
                index_name = self.vector_field_name,
                using = self.alias
            )

        except Exception as e:
            return e
        
        return True`

**Comment by JiehangXie** [comment]
[etcd.log](https://github.com/milvus-io/milvus/files/10150434/etcd.log)
[milvus-standalone.log](https://github.com/milvus-io/milvus/files/10150435/milvus-standalone.log)

**Comment by JiehangXie** [comment]
`python
def buildIndex(self):
    """
    建立索引
    """
    index_params = {
                "index_type": "IVF_SQ8", 
                "metric_type": "L2",
                "params": {"nlist": 16384}
            }

    try:
        self.connection.create_index(
            field_name = self.vector_field_name,
            index_params = index_params
        )

        utility.wait_for_index_building(
            collection_name = self.collection_name,
            index_name = self.vector_field_name,
            using = self.alias
        )

        self.load()
        
        utility.wait_for_loading_complete(
            collection_name = self.collection_name,
            index_name = self.vector_field_name,
            using = self.alias
        )

    except Exception as e:
        return e
    
    return True
`

**Comment by JiehangXie** [comment]
```python
def buildIndex(self):
    """
    建立索引
    """
    index_params = {
                "index_type": "IVF_SQ8", 
                "metric_type": "L2",
                "params": {"nlist": 16384}
            }

    try:
        self.connection.create_index(
            field_name = self.vector_field_name,
            index_params = index_params
        )

        utility.wait_for_index_building(
            collection_name = self.collection_name,
            index_name = self.vector_field_name,
            using = self.alias
        )

        self.load()
        
        utility.wait_for_loading_complete(
            collection_name = self.collection_name,
            index_name = self.vector_field_name,
            using = self.alias
        )

    except Exception as e:
        return e
    
    return True
```

**Comment by JiehangXie** [comment]
I have clear the logs before, this is a complete progress 
[milvus-standalone.log](https://github.com/milvus-io/milvus/files/10150497/milvus-standalone.log)
[etcd.log](https://github.com/milvus-io/milvus/files/10150498/etcd.log)
log from starting to shutting down.

**Comment by JiehangXie** [comment]
I have clear the logs before, this is a complete progress
 log from starting to shutting down.

[milvus-standalone.log](https://github.com/milvus-io/milvus/files/10150497/milvus-standalone.log)
[etcd.log](https://github.com/milvus-io/milvus/files/10150498/etcd.log)

**Comment by yanliang567** [comment]
@JiehangXie how much memory did you configure the the docker? I guess it was caused by OOM, please try with a smaller nlist value, such as 1024, instead of 16384.
/assign @JiehangXie

**Comment by JiehangXie** [comment]
> @JiehangXie how much memory did you configure the the docker? I guess it was caused by OOM, please try with a smaller nlist value, such as 1024, instead of 16384. /assign @JiehangXie

it seems to be a Windows or Docker problems. I have uninstalled Docker and delete all datas, and reinstall the Docker, the problem is still unresolved.

**Comment by JiehangXie** [comment]
> @JiehangXie how much memory did you configure the the docker? I guess it was caused by OOM, please try with a smaller nlist value, such as 1024, instead of 16384. /assign @JiehangXie

but I install milvus 2.1.4 in the same computer just now, and it can work…… @yanliang567

**Comment by xiaofan-luan** [comment]
@yanliang567 There seems to be many issue related to IVF SQ8 index?

**Comment by yanliang567** [comment]
i don't think it is due to index.  I saw many "failed to get metrics, err=NotHealthy" errors in logs.

@bigsheeper could you please give a hand on it?
/assign @bigsheeper 
/unassign

**Comment by bigsheeper** [comment]
![image](https://user-images.githubusercontent.com/42060877/206352719-b86f404e-fc8b-4354-b907-2f685c284135.png)

![image](https://user-images.githubusercontent.com/42060877/206352821-4528e4f2-2b6b-4cb9-a5fe-2a1980226fbd.png)

panic due to rootcoord failed to register lease to etcd. Maybe etcd is unhealthy?@JiehangXie

**Comment by bigsheeper** [comment]
WARNING: 2022/12/05 03:42:19 [core] grpc: addrConn.createTransport failed to connect to {0.0.0.0:2379 0.0.0.0:2379 <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp 0.0.0.0:2379: operation was canceled". Reconnecting...

**Comment by JiehangXie** [comment]
> ![image](https://user-images.githubusercontent.com/42060877/206352719-b86f404e-fc8b-4354-b907-2f685c284135.png)
> 
> ![image](https://user-images.githubusercontent.com/42060877/206352821-4528e4f2-2b6b-4cb9-a5fe-2a1980226fbd.png)
> 
> panic due to rootcoord failed to register lease to etcd. Maybe etcd is unhealthy?@JiehangXie

@bigsheeper maybe……，I uninstall milvus 2.1.4 but maintain the milvus-minio and etcd, then install milvus 2.2.0 alone, it can work normally. Now I try to rewrite the vector data to exclude if OOM occurs this problem.

**Comment by JiehangXie** [comment]
The problem is still happend when inserting photo to No.129119, and below is the logs before shutdown 
autoly last night.
[etcd.log](https://github.com/milvus-io/milvus/files/10190998/etcd.log)
[milvus-standalone.log](https://github.com/milvus-io/milvus/files/10190997/milvus-standalone.log)

**Comment by bigsheeper** [comment]
> The problem is still happend when inserting photo to No.129119, and below is the logs before shutdown autoly last night. @bigsheeper [etcd.log](https://github.com/milvus-io/milvus/files/10190998/etcd.log) [milvus-standalone.log](https://github.com/milvus-io/milvus/files/10190997/milvus-standalone.log)

No panic and exceptions in these log, can you offer me the monitor or memory usage or any other information? thank you very much. :)

**Comment by JiehangXie** [comment]
> > The problem is still happend when inserting photo to No.129119, and below is the logs before shutdown autoly last night. @bigsheeper [etcd.log](https://github.com/milvus-io/milvus/files/10190998/etcd.log) [milvus-standalone.log](https://github.com/milvus-io/milvus/files/10190997/milvus-standalone.log)
> 
> No panic and exceptions in these log, can you offer me the monitor or memory usage or any other information? thank you very much. :)

It happened suddenly and can't get any record. If it is convenient for you, you can directly control my computer with sunlogin or todesk in working time. My Wechat is xiejiehang.Thanks a lot. @bigsheeper

**Comment by bigsheeper** [comment]
> > > The problem is still happend when inserting photo to No.129119, and below is the logs before shutdown autoly last night. @bigsheeper [etcd.log](https://github.com/milvus-io/milvus/files/10190998/etcd.log) [milvus-standalone.log](https://github.com/milvus-io/milvus/files/10190997/milvus-standalone.log)
> > 
> > 
> > No panic and exceptions in these log, can you offer me the monitor or memory usage or any other information? thank you very much. :)
> 
> It happened suddenly and can't get any record. If it is convenient for you, you can directly control my computer with sunlogin or todesk in working time. My Wechat is xiejiehang.Thanks a lot. @bigsheeper

@JiehangXie Sorry for late reply，is this issue still happen these days?

**Comment by JiehangXie** [comment]
> > > > The problem is still happend when inserting photo to No.129119, and below is the logs before shutdown autoly last night. @bigsheeper [etcd.log](https://github.com/milvus-io/milvus/files/10190998/etcd.log) [milvus-standalone.log](https://github.com/milvus-io/milvus/files/10190997/milvus-standalone.log)
> > > 
> > > 
> > > No panic and exceptions in these log, can you offer me the monitor or memory usage or any other information? thank you very much. :)
> > 
> > 
> > It happened suddenly and can't get any record. If it is convenient for you, you can directly control my computer with sunlogin or todesk in working time. My Wechat is xiejiehang.Thanks a lot. @bigsheeper
> 
> @JiehangXie Sorry for late reply，is this issue still happen these days?

After testing, I feel it is caused by AMD CPU because it happend in other AI Framework too.

**Comment by xiaofan-luan** [comment]
> these days?

could be related to some unsupported simd instruction, we are working on fixing it
