### ISSUE TITLE
[Enhancement]: Undefined behavior when output duplicate fields in Query API

### ISSUE THREAD

**Issue by jiaoew1991** [milvus-io/milvus#20979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Feedback from users, when they want to output duplicate fields in Query API, the result is unstable, one of the fields will return empty.
We should handle this case, most of the databases support a `select alias` statement to handle duplicate fields, we can use this way to support it, or return an error to forbid this case

### Why is this needed?

make API more expectable

**Comment by xiaofan-luan** [comment]
keep it?
