### ISSUE TITLE
[Bug]: [benchmark][diskann] Milvus creates diskann index, inserts 1million data, then load data, memory usage too high

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#20994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0dev72
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

deploy_config
fouramf-server-standalone-12c16m
case_params
fouramf-go-bench-diskann
other_params
--milvus_tag=v2.2.0 
testacase：test_go_bench_custom_parameters

sever：

```
NAME                                                              READY   STATUS      RESTARTS        AGE     IP             NODE         NOMINATED NODE   READINESS GATES
fouramf-go-6cldx-8l2w9-73-1898-etcd-0                             1/1     Running     0               6m37s   10.104.9.186   4am-node14   <none>           <none>
fouramf-go-6cldx-8l2w9-73-1898-milvus-standalone-584df8f6f6sqrl   1/1     Running     0               6m37s   10.104.6.103   4am-node13   <none>           <none>
fouramf-go-6cldx-8l2w9-73-1898-minio-579b8dcc5b-tv4ds             1/1     Running     0               6m37s   10.104.9.185   4am-node14   <none>           <none> (cli_client.py:123)
```

<img width="1396" alt="截屏2022-12-05 19 38 34" src="https://user-images.githubusercontent.com/34296482/205628303-057a3d4a-9c0f-4950-9eb6-087e048d10db.png">

### Steps To Reproduce

```markdown
1. create a collection 
        2. build diskann index on vector column
        3. insert 1m of vectors
        4. flush collection
        5. build index on vector column with the same parameters
        6. count the total number of rows
        7. load collection
        8. call the go program to perform search concurrent operations
```

### Anything else?

`[check_params] scene_go_search required params: {'dataset_params': {'dim': 128, 'dataset_name': 'sift', 'dataset_size': '1m', 'ni_per': 50000, 'metric_type': 'L2'}, 'collection_params': {'other_fields': []}, 'load_params': {}, 'search_params': {'top_k': [1], 'nq': [1], 'search_param': {'search_list': [30]}}, 'index_params': {'index_type': 'DISKANN', 'index_param': {}}, 'go_search_params': {'concurrent_number': [30, 40, 50, 60, 70, 80], 'during_time': 3600, 'interval': 20}} (params_check.py:31)`

**Comment by xiaofan-luan** [comment]
related to #20995
