### ISSUE TITLE
[Bug]:IndexCoord deletes segmentIndex by mistake because IndexMeta is not stored in time

### ISSUE THREAD

**Issue by czs007** [milvus-io/milvus#21009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: Master and 2.2.0
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Currently, IndexCoord saves segmentIndexMeta first, and then saves IndexMeta. When the collection has a large number of segments, it takes a long time for the indexcoord to store these segmentIndexMeta. Before saving the IndexMeta, the GC logic arrives. Since there is no IndexMeta, all the segmentIndexMeta are deleted.

**Comment by xiaocai2333** [comment]
fixed and close
/close
