### ISSUE TITLE
[Bug]: most of the bootcamp link are not working on https://milvus.io/docs/

### ISSUE THREAD

**Issue by alexucb** [milvus-io/milvus#21018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The 'milvus-io/bootcamp' repository doesn't contain the 'solutions/nlp/text_search/quick_deploy' path in 'master'.

**Comment by yanliang567** [comment]
I think its about the link https://milvus.io/bootcamp/
@LoveEachDay could you please help on this？

/assign @LoveEachDay 
/unassign

**Comment by YiyunNi** [comment]
Thanks for catching this! @alexucb The bootcamp links are now updated with the PRs mentioned above.
