### ISSUE TITLE
[Bug]: Why does it take more than 5 seconds to query a vector in a cluster

### ISSUE THREAD

**Issue by sloan96** [milvus-io/milvus#21017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: Milvus 2.2.0    milvus-chart:3.3.0
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.1.0
- OS(Ubuntu or CentOS): CentOS 7.2
- CPU/Memory: 48 cores/ 128G memory
- GPU: no
- Others: Install Milvus cluster with helm（https://milvus.io/docs/install_cluster-helm.md#Install-Milvus-Cluster-with-Helm），no minikube was used. "helm install my-release milvus"
```

### Current Behavior

When I successfully deployed the cluster, I created the collection, nlist=1024, nprob=32, index_type=INV_FLAT, and inserted 4 vector data. The average time of searching 10 vectors was more than 5 seconds. However, when I deployed on a single machine, the same environment configuration was adopted. The average search time for 10 vectors is only 500ms. I wonder what on earth caused such a big time gap

### Milvus Log

The cluster logs have been uploaded to the web disk.
链接: https://pan.baidu.com/s/1A6gFo0VBrS9qNKFqsT1kNw 提取码: y51j

**Comment by xiaofan-luan** [comment]
1. how large is the dataset?
2. what is the machine config？
3. What is the conccurency?

**Comment by xiaofan-luan** [comment]
/assign @JackLCL  
could you help on following up

**Comment by sloan96** [comment]
> 1. how large is the dataset?
vector dim = 512,  just inserted 4 data for test.
> 2. what is the machine config？
The pod machine is 128G with 48 cores
> 3. What is the conccurency?
what means？
@xiaofan-luan

**Comment by JackLCL** [comment]
@sloan96 
Did you solve this problem?
If not, could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
