### ISSUE TITLE
[Bug]: fail to search on all shard leaders, err=All attempts results:\nattempt #1:fail to get shard leaders from QueryCoord: no replica available\nattempt #2:fail to get shard leaders from QueryCoord: no replica available\nattempt

### ISSUE THREAD

**Issue by tgk60w** [milvus-io/milvus#21020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.1.2):gomilvus v2.1.2
- OS(Ubuntu or CentOS): 
- CPU/Memory: CPU
- GPU: 
- Others:
```

### Current Behavior

fail to search on all shard leaders, err=All attempts results:\nattempt #1:fail to get shard leaders from QueryCoord: no replica available\nattempt #2:fail to get shard leaders from QueryCoord: no replica available\nattempt #3:fail to get shard leaders from QueryCoord: no replica available\nattempt #4:fail to get shard leaders from QueryCoord: no replica available\nattempt #5:fail to get shard leaders from QueryCoord: no replica available\nattempt #6:fail to get shard leaders from QueryCoord: no replica available\nattempt #7:fail to get shard leaders from QueryCoord: no replica available\nattempt #8:context deadline exceeded\n

### Milvus Log

[ytst-milvus-prod-standalone-8f58c774-jrxr5.log.zip](https://github.com/milvus-io/milvus/files/10172216/ytst-milvus-prod-standalone-8f58c774-jrxr5.log.zip)

[ytst-milvus-prod-etcd-0.log.zip](https://github.com/milvus-io/milvus/files/10172312/ytst-milvus-prod-etcd-0.log.zip)

**Comment by yanliang567** [comment]
@tgk60w which version of milvus and pymilvus are you running?

**Comment by tgk60w** [comment]
> @tgk60w which version of milvus and pymilvus are you running? Milvus 2.2.0 just released, please try it if you did not.

2.1.2

**Comment by tgk60w** [comment]
> @tgk60w which version of milvus and pymilvus are you running? Milvus 2.2.0 just released, please try it if you did not.

Can't switch version quickly
