### ISSUE TITLE
[Bug]:  modeStrore has a concurrent write issue when init privilege policy

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#21022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

occurs fatal error and panic exit
![img_v2_b02b3686-ff41-4c16-8c8c-f650fcb0c18g](https://user-images.githubusercontent.com/4024711/206075494-36d234da-ff1b-4ebb-8fb3-8fdb1520edd0.jpg)

**Comment by jaime0815** [comment]
![image](https://user-images.githubusercontent.com/4024711/206416565-d55a8aa6-32a3-4b90-b4be-85f87799d3f9.png)

**Comment by SimFG** [comment]
benchmark:
```go
// about 7w/s
func BenchmarkModel(b *testing.B) {
	for i := 0; i < b.N; i++ {
		getPolicyModel(ModelStr)
	}
}

// about 38w/s
func BenchmarkCopyModel(b *testing.B) {
	m := getPolicyModel(ModelStr)
	for i := 0; i < b.N; i++ {
		m.Copy()
	}
}
```
![YQqE5IhP9I](https://user-images.githubusercontent.com/21985684/206991309-75899a9d-ea56-41a8-9e2c-2a9566866952.jpg)
![NGx59OVNle](https://user-images.githubusercontent.com/21985684/206991339-efc1aa74-5f9e-4b37-bf58-213bcc8d514a.jpg)
