### ISSUE TITLE
[Bug]: Restarting milvus may make milvus unsearchable

### ISSUE THREAD

**Issue by devNullgh** [milvus-io/milvus#21041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvus-2.1.4-1.el7.x86_64
- Deployment mode(standalone or cluster): standalone , rpm
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.3
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 16c/128GB
- GPU: ---
- Others: Milvus rpm version is milvus-2.1.4-1.el7.x86_64, but the attu shows that the milvus version is V2.1.3-1-G9122e34-Dev, there are some differences.
```

### Current Behavior

Since the etcd configuration of rpm version was not modified, we modified the etcd configuration and restarted, but found that milvus could not be searched after the restart.
We tried to release collection, but the release took a long time（a lot of hours） and could not be successfully released.

### Expected Behavior

Should be able to search normally after a normal restart.

### Milvus Log

milvus logs:
https://pan.baidu.com/s/1mzeMD63pVPcGNO0n7FDWIg?pwd=wo81

**Comment by yanliang567** [comment]
@devNullgh which items did you changed in ectd configurations?
/assign @devNullgh

**Comment by devNullgh** [comment]
@yanliang567 

`--auto-compaction-retention 1000 
--auto-compaction-mode revision 
--quota-backend-bytes 8589934592`

The docker-compose version is modified for these, but the rpm version is not.
etcd error: "etcdserver: mvcc: database space exceeded"
So we changed the above parameters.

**Comment by LoveEachDay** [comment]
@devNullgh Could you check the service status for milvus dependencies:
```
systemctl status milvus-etcd
systemctl status milvus-minio
```

**Comment by devNullgh** [comment]
@LoveEachDay 
milvus-etcd and milvus-minio both work properly
![image](https://user-images.githubusercontent.com/43362620/206401298-6548ba72-63d1-46d4-a8ad-52759c01aef9.png)
![image](https://user-images.githubusercontent.com/43362620/206401388-6df8dfb8-9cde-45dd-bdbb-cfaf28b5a736.png)
