### ISSUE TITLE
[Enhancement]: milvus server support getConnections interface and add collection metric

### ISSUE THREAD

**Issue by yelusion2** [milvus-io/milvus#21051]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

support getConnections interface, user can get Connections number througth sdk;
collection metric, convenient for users to locate problems;

### Why is this needed?

support getConnections interface, user can get Connections number througth sdk;
collection metric, convenient for users to locate problems;

**Comment by xiaofan-luan** [comment]
might be reasonable to add some metrics about connection count.
add a API could be too much?

**Comment by yelusion2** [comment]
> might be reasonable to add some metrics about connection count. add a API could be too much?
The purpose of adding api is to facilitate external users to obtain the kernel version。Like user do minor version upgrade to check version.
