### ISSUE TITLE
[Bug]: root path is not used in local chunk manager

### ISSUE THREAD

**Issue by longjiquan** [milvus-io/milvus#21064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 039e9ce4b
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://github.com/milvus-io/milvus/blob/6709ccf690aec88a3323f419b060b8d962b81445/internal/storage/vector_chunk_manager.go#L176

**Comment by longjiquan** [comment]
https://github.com/milvus-io/milvus/blob/6709ccf690aec88a3323f419b060b8d962b81445/internal/storage/local_chunk_manager.go#L87-L101

**Comment by longjiquan** [comment]
Though we didn't use the root path now, it's right for the retrieve logic since `Read` also didn't use the root path.

**Comment by xiaofan-luan** [comment]
@yhmo may want to take a look also

**Comment by yanliang567** [comment]
@xige-16 @yhmo any updates?

**Comment by yhmo** [comment]
chunk manager class requires outer callers input a full path to call write(). This is not a bug of chunk manager.
@longjiquan will change the logic of outer caller to fix it.

**Comment by yanliang567** [comment]
@longjiquan any comments?
