### ISSUE TITLE
[Enhancement]: Milvus metrics dashborad do not support filter by collection's name.

### ISSUE THREAD

**Issue by dzqoo** [milvus-io/milvus#21065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

I would like to suggest a feature that Milvus dashboard support to filtered by collection's name.

By now the collection's name is not in metrics's "group by" statement.
![image](https://user-images.githubusercontent.com/8862305/206368876-afca17cc-8fef-4473-8ec5-e161813bf88b.png)

### Why is this needed?

I want to see the metrics in the collection's dimension which helps me to decide which collection to optimize from.

**Comment by yanliang567** [comment]
@dzqoo Thanks for the suggestion, sounds like a reasonable requirement.

**Comment by LoveEachDay** [comment]
@dzqoo For now the collection level metrics are only available for `Collection Search Latency` and `Collection Mutation Latency` two panels.
