### ISSUE TITLE
[Bug]: Can't install milvus cluster2.2.0 with helm 

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus#21098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu 20.04
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```shell
helm install my-release milvus/milvus
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
```

### Expected Behavior

Install milvus successfully

### Steps To Reproduce

```markdown
https://milvus.io/docs/install_cluster-helm.md 

1. install minikube
2. helm repo add milvus https://milvus-io.github.io/milvus-helm/
3. helm repo update
4. helm install my-release milvus/milvus
```

**Comment by shanghaikid** [comment]
> @shanghaikid Could you check your kubernetes cluster version? Since kubernetes v1.25 has removed "PodDisruptionBudget" in version "policy/v1beta1".

I think mine is v1.25.  so it is not supported ?

**Comment by LoveEachDay** [comment]
May we can just disable pdb for kubernetes v1.25 compatibility?

**Comment by LoveEachDay** [comment]
You can disable pdb for pulsar using following values:
```
helm install my-release milvus/milvus --set pulsar.bookkeeper.pdb.usePolicy=false,pulsar.broker.pdb.usePolicy=false,pulsar.proxy.pdb.usePolicy=false,pulsar.zookeeper.pdb.usePolicy=false
```

**Comment by shanghaikid** [comment]
@AnthonyTsu1984 I think we'd better add a note in the official docs.

**Comment by LoveEachDay** [comment]
@shanghaikid @AnthonyTsu1984 We can disable pdb in default milvus values.

**Comment by AnthonyTsu1984** [comment]
> @shanghaikid @AnthonyTsu1984 We can disable pdb in default milvus values.

That's good. I would like to know if this change affects users using pdb on Kubernetes v1.21 through v1.25. If yes, a note is still in need to guide them to enable pdb. Simply, two directions:

- Milvus configurations stay unchanged, add a note on the workaround suggested by @shanghaikid.
- Change Milvus configurations, and add a note on the workaround suggested by @LoveEachDay.

**Comment by shanghaikid** [comment]
> @shanghaikid @AnthonyTsu1984 We can disable pdb in default milvus values.

Any impact on existing users?

**Comment by LoveEachDay** [comment]
No

> > @shanghaikid @AnthonyTsu1984 We can disable pdb in default milvus values.
> 
> Any impact on existing users?

**Comment by shanghaikid** [comment]
> No
> 
> > > @shanghaikid @AnthonyTsu1984 We can disable pdb in default milvus values.
> > 
> > 
> > Any impact on existing users?

Let's disable the pdb.
