### ISSUE TITLE
[Bug]: Ensure bulkinsert data to be loaded

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#21091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Currently bulk insert done means data import and insert. Whether data is loaded remains to be unknown and  might cause some misunderstanding.

### Expected Behavior

Redesign load interface, when bulkinsert down, call load and make sure all bulkinserted segment is loaded

**Comment by yhmo** [comment]
In 2.2.3, the bulkinsert/load logic has been changed. The new workflow is:
1. use bulkinsert() import some segments
2. use wait_for_index_building_complete() or DescribeIndex to wait index finished
3. use load(refresh=true) to refresh the segment list and load them into memory
4. search

**Comment by yhmo** [comment]
2.2.3 has been released, close this issue.
