### ISSUE TITLE
[BUG] monitor: CPU/GPU usage radio and temperature disappeared on grafana after zooming in/out

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#211]
**Describe the bug**
CPU/GPU usage radio and temperature disappeared on grafana after zooming in/out

**Steps/Code to reproduce behavior**
Re-produce this issue by using zoom button

**Expected behavior**
N/A

**Environment details**
N/A

**Screenshots**
![Screenshot_2019-11-06 dashboard2 - Grafana](https://user-images.githubusercontent.com/56623710/68273115-8f781380-00a0-11ea-9a1d-afa4fa68f63d.png)

**Additional context**
N/A

**Comment by fishpenguin** [comment]
This is because these no data metrics are real-time, cannot display history message. I add history GPU utilization in docs.
