### ISSUE TITLE
[Bug]: The case does not check the search output fields when search with empty `output_fields`

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#21112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20221208-6709ccf6
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.0.dev15
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

 1. Search with `output_fields=[]` does not check the result output fields. Maybe you can gets the actual output fields by `searchRes[hits][hit].entity.fields`
Test case: output_fields -> []
"""
def test_search_with_output_fields_empty(self, nb, nq, dim, auto_id, _async):
        """
        target: test search with output fields
        method: search with empty output_field
        expected: search success
        """
        # 1. initialize with data
        collection_w, _, _, insert_ids = self.init_collection_general(prefix, True, nb,
                                                                      auto_id=auto_id,
                                                                      dim=dim)[0:4]
        # 2. search
        log.info("test_search_with_output_fields_empty: Searching collection %s" % collection_w.name)
        vectors = [[random.random() for _ in range(dim)] for _ in range(nq)]
        res = collection_w.search(vectors[:nq], default_search_field,
                                  default_search_params, default_limit,
                                  default_search_exp, _async=_async,
                                  output_fields=[],
                                  check_task=CheckTasks.check_search_results,
                                  check_items={"nq": nq,
                                               "ids": insert_ids,
                                               "limit": default_limit,
                                               "_async": _async})[0]
        if _async:
            res.done()
            res = res.result()
        assert len(res[0][0].entity._row_data) == 0
"""

2. By the way, `query` default return pk field even if `output_fields=[]`
```
[{'int64': 0}, {'int64': 1}] 
```

**Comment by yanliang567** [comment]
@binbinlv could you please help to update the tests

**Comment by binbinlv** [comment]
> @binbinlv could you please help to update the tests

OK, working.
