### ISSUE TITLE
[Bug]: excessive ram usage with no disk usage

### ISSUE THREAD

**Issue by warmagedon007** [milvus-io/milvus#21125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.4
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.3
- OS(Ubuntu or CentOS): docker on kubernetes
- CPU/Memory: 8 cores. 160Gi
- GPU: None
- Others: 
Used helmchart 3.2.18
```

### Current Behavior

I used the helm chart specified. It's the last one where the default image was 2.1.4.
I enabled disk usage. I double-checked the config for the querynode enable the disk. And the yaml creates the emptyDir.
I created a test gallery with vector size of 128, with 6 additional int64 fields and 11 Varchar255 fields.

When I load 3 million vectors to the gallery. The ram used gets up to 80Gi.
Then I checked the disk. /milvus/data, it's empty.

Im guessing that all data is loaded into the ram not the disk, thus ballooning the ram usage.

### Expected Behavior

When specifying disk usage and loading large galleries. Use the disk to minimize ram usage.

(Isn't it the desired behavior?)

### Steps To Reproduce

```markdown
1. Deploy with the helm chart on kubernetes.
2. Put a large gallery in it.
3. Watch the ram
4. Check the disk.
```

**Comment by karimBenzema12** [comment]
Hi!
I ecountered the same problem.
@yanliang567 can you clarify/help?

**Comment by karimBenzema12** [comment]
Hi!
I encountered the same problem.
@yanliang567 can you clarify/help?

**Comment by xiaofan-luan** [comment]
Milvus 2.1.4 don't support disk Index, all data should be loaded in memory before search.
If only load vectors,  8GB should be good enough for 5m 128dim vectors. With 6 additional int64 fields and 11 Varchar255 fields, it may takes great amount of memory and need to further test on it.

**Comment by xiaofan-luan** [comment]
Also, distributed milvus store data on pulsar/minio and the data directory is specified by helm chart/milvus.yaml file.

**Comment by xiaofan-luan** [comment]
@yanliang567 shall we verify the memory usage for pure varchar field and string index?

**Comment by yanliang567** [comment]
@warmagedon007 @karimBenzema12 please retry on milvus 2.2 if you do want diskann index.
/assign @warmagedon007 

@xiaofan-luan okay
