### ISSUE TITLE
[Bug]: collection.delete() doesn't delete entities when expr contains non-primary key

### ISSUE THREAD

**Issue by MayStepanyan** [milvus-io/milvus#21122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.3
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.3
- OS(Ubuntu or CentOS): Ubuntu 
- CPU/Memory: 32 GB
- GPU: None
- Others:
```

### Current Behavior

I have a collection with primary field "photo_id" and a regular field "instance_id". Each entity can have several photo i.e. "instance_id" fields values can be duplicated.

When I remove data with `expr= "photo_id in {{some_indices}}"`, they are successfully removed and I can't query them immediately. When I use `expr="instance_id in {{some_indices}}" instead, nothing happens. When I access the .primary_keys attribute of collection.delete() methods response, I see valid ids that should've been deleted, but they are not actually deleted.

Notes
---------
- When I check whether they deleted or not, I set consistency level to Strong. 
- I tried to wait for a couple of minutes or even hours, but entities just do not get deleted.
- When I use primary field (photo_id) in the expression instead, items are deleted immediately
- I have just one, default partition in my collection

### Expected Behavior

Items should be deleted both when I use primary and secondary keys in expression

### Steps To Reproduce

```markdown
- Create any collection with two integer fields: primary and secondary
- Fill some values with duplicated secondary field, e.g. [[0,1,2,3], [0,0,1,1]]
- Try to delete items via collection.delete() method with expr that includes secondary field
```

**Comment by xiaofan-luan** [comment]
Currently we only support delete by primary key.
But it should throw out an error if not supported. @longjiquan could you pls check on it?

**Comment by longjiquan** [comment]
Feel free to reopen this if the issue still exists.
/close
