### ISSUE TITLE
[Enhancement]: Milvus support array data type

### ISSUE THREAD

**Issue by citePerson** [milvus-io/milvus#21126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

我希望milvus能够支持数组的标量存储，在许多业务场景中都需要用到数组这个数据结构，但是目前milvus不支持数组的存储方式，比如一个简单的业务场景：当一个标量字段存储多个值并且需要与接收的多个值求交集的来筛选数据集的时候，现在的操作就超级麻烦。希望能支持越来越多的标量数据结构，类如数组，字典嵌套等

### Why is this needed?

目前milvus不支持数组的存储方式，比如一个简单的业务场景：当一个标量字段存储多个值并且需要与接收的多个值求交集的来筛选数据集的时候，而且这是数据库都支持的数据类型

**Comment by xiaofan-luan** [comment]
Hi @citePerson 
It would be really helpful if we use English to submit issue.

**Comment by xiaofan-luan** [comment]
Yes, we are planing to support more datatypes such as array and set.
Currently scalar data types take too much memory, so one thing we are trying to improve is our execution engine.
Once we replace the execution engine the next step would be supporting more data types.
For current use, an alternative solution would be store data in mysql or other databases and only use milvus as vector retrieval

**Comment by citePerson** [comment]
If you use MySQL to store scalars  and use milvus to store vecs,how do you do?
 When and what version to support more datatypes such as array and set and dict?

**Comment by citePerson** [comment]
> If you use MySQL to store scalars and use milvus to store vecs,how do you do?
> When and what version to support more datatypes such as array and set and dict?

**Comment by citePerson** [comment]
If you use MySQL to store scalars and use milvus to store vecs,how do you do?
 When and what version to support more datatypes such as array and set and dict?

**Comment by xiaofan-luan** [comment]
> If you use MySQL to store scalars and use milvus to store vecs,how do you do? When and what version to support more datatypes such as array and set and dict?

related (https://github.com/milvus-io/milvus/issues/21141)

**Comment by xiaofan-luan** [comment]
We are planning to finish the feature in next two big releases. 
Stage 1 : Introduce a new execution engine to do scalar filtering
Stage 2: Add more features based on velox supported
