### ISSUE TITLE
[Bug]: When I create index for Milvus, Milvus hang

### ISSUE THREAD

**Issue by learningpro** [milvus-io/milvus#21123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.4
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): MacOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

the same as https://github.com/milvus-io/milvus/issues/15705
it hangs after creating index

=== start connecting to Milvus     ===

Does collection hello_milvus exist in Milvus: False

=== Create collection `hello_milvus` ===

=== Start inserting entities       ===

Number of entities in Milvus: 0

=== Start Creating index IVF_FLAT  ===

### Steps To Reproduce

```markdown
It's very easy to reproduce this issue, just do as your document says https://milvus.io/docs/v2.1.x/example_code.md

It's very easy to reproduce this issue, just do as your document says https://milvus.io/docs/v2.1.x/example_code.md

It's very easy to reproduce this issue, just do as your document says https://milvus.io/docs/v2.1.x/example_code.md
```

**Comment by xiaofan-luan** [comment]
hi @learningpro , if you could provide logs that would be super helpful.
I can't reproduce on my local machine. 
Also pls try latest 2.2.0 image because we fixed many issue there

**Comment by learningpro** [comment]
2.2.0 works like a charm https://milvus.io/docs/example_code.md
Thanks and close it.

**Comment by learningpro** [comment]
However I must use 2.1.x now. https://github.com/milvus-io/milvus/issues/20867#issuecomment-1342619390

When I run hello_milvus.py, it hangs here:
python3.9 hello_milvus.py

=== start connecting to Milvus     ===

Does collection hello_milvus exist in Milvus: False

=== Create collection `hello_milvus` ===


=== Start inserting entities       ===

Number of entities in Milvus: 0

=== Start Creating index IVF_FLAT  ===





docker logs here
[milvus-standalone.log](https://github.com/milvus-io/milvus/files/10208165/milvus-standalone.log)

**Comment by learningpro** [comment]
The cause is the wrong version of pymilvus. When using pymilvus 2.2.0 to connect to Milvus 2.1.4, it will hangs that.
