### ISSUE TITLE
Mishards config DISCOVERY_STATIC_HOSTS is not robust

### ISSUE THREAD

**Issue by SkyYang** [milvus-io/milvus#2116]
**Describe the bug**
DISCOVERY_STATIC_HOSTS expects hosts list splited by "," and now it can't tolerate space in between, which is very error-prone

**Steps/Code to reproduce behavior**
DISCOVERY_STATIC_HOSTS=192.168.1.12,192.168.1.13 is valid.
DISCOVERY_STATIC_HOSTS=192.168.1.12, 192.168.1.13 will cause the server to fail to start and the exception message is very confusing. 

**Expected behavior**
Configuration should be more robust.
.

**Comment by tinkerlin** [comment]
thanks for your suggestion, we will fix soon.
