### ISSUE TITLE
[Bug]: DataCoord lost channel watch schema info after restart

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#21160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: b0afdb2
- Deployment mode(standalone or cluster): both
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

DataCoord lost channel watch schema info after restart. DataNodes have to fetch schema which may fail in some situtation

### Expected Behavior

DataCoord shall fill collection schema for every ChannelWatchInfo

### Anything else?

Related to #20663

**Comment by zhuwenxing** [comment]
image tag: master-20221212-56e722f9
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/479/pipeline

log:
[artifacts-pulsar-pod-kill-479-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10213692/artifacts-pulsar-pod-kill-479-server-logs.tar.gz)
[artifacts-pulsar-pod-kill-479-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10213695/artifacts-pulsar-pod-kill-479-pytest-logs.tar.gz)
