### ISSUE TITLE
[Bug]: Proxy doesn't update shard leaders cache while received some types or error

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#21184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master & 2.2.0
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

As the proxy update cache if:
- got `NotShardLeader` error 
- got any GRPC errors
- got `ErrConnect`
This doesn't work for `NodeIDNotMatch` error, which occurs if the QueryNode restarts with the same IP address

### Expected Behavior
Update cache if got error except:
- context canceled
- context deadline exceeded

_No response_

**Comment by xiaofan-luan** [comment]
we might want to refresh the cache every few minutes to avoid cache

**Comment by xiaofan-luan** [comment]
My suggestion is we clean the cache for all errors, or we should throw certain error to clean the cache.

**Comment by yah01** [comment]
> My suggestion is we clean the cache for all errors, or we should throw certain error to clean the cache.

Cleaning cache for all errors works, retry with a canceled context will fail immediately

**Comment by yah01** [comment]
> we might want to refresh the cache every few minutes to avoid cache

Will add dual caches

**Comment by jiaoew1991** [comment]
> > we might want to refresh the cache every few minutes to avoid cache
> 
> Will add dual caches

@yah01  You can refer to the cache implementation of Guava, which has the TTL of the key
