### ISSUE TITLE
[Bug]: Segments are balanced continuously 

### ISSUE THREAD

**Issue by MrPresent-Han** [milvus-io/milvus#21189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I start a cluster and found that one segment is balanced constantly from one node to another

### Expected Behavior

It's expected that the segment should be allocated to one node readily without back and forth

### Milvus Log

![image](https://user-images.githubusercontent.com/116052805/207268330-c7c5cde8-9aa8-4b15-a221-636bb426640a.png)

**Comment by xiaofan-luan** [comment]
is this still a issue?

**Comment by xiaofan-luan** [comment]
keep it
