### ISSUE TITLE
[Bug]: querynode search on growing segments even the segments are indexed

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#21215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20221205-7ea86ed3
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
```

### Current Behavior

querynode search on growing segments even the segments are indexed.

### Expected Behavior

querynode search with indexed segments

### Steps To Reproduce

```markdown
There is collection with 1.5 million entities, with 4 indexed segments.(search latency <30ms)
1. then insert 50k entities without flush
2. search the collection, and found querynode always searching on non-indexed segments.(search latency >2kms)
```

### Milvus Log

![image](https://user-images.githubusercontent.com/82361606/207502722-ea64e0f8-2966-4462-9847-738478dba910.png)
![image](https://user-images.githubusercontent.com/82361606/207502782-fa73e6a1-2a13-416d-9194-47ce10841644.png)
![image](https://user-images.githubusercontent.com/82361606/207507740-3c31eaef-70bc-4859-b956-db7a44788787.png)

### Anything else?
```

yanliang-cluster-1cu-milvus-datanode-69ff56d879-zpssx           1/1     Running     0              8d      10.102.6.218    devops-node10   <none>           <none>
yanliang-cluster-1cu-milvus-indexnode-fd4744f75-77hrp           1/1     Running     0              8d      10.102.7.149    devops-node11   <none>           <none>
yanliang-cluster-1cu-milvus-mixcoord-6888b6b64f-nxg5q           1/1     Running     0              8d      10.102.10.185   devops-node20   <none>           <none>
yanliang-cluster-1cu-milvus-proxy-6d879cc5f6-mjzbn              1/1     Running     0              8d      10.102.6.178    devops-node10   <none>           <none>
yanliang-cluster-1cu-milvus-querynode-6b4df5dbbd-mw8k8          1/1     Running     3 (19h ago)    5d21h   10.102.7.240    devops-node11   <none>           <none>
```

**Comment by yanliang567** [comment]
BTW, manual flush does not help

**Comment by yanliang567** [comment]
looks like an occasional issue, I retried and this time search latency recovered in mins.
![image](https://user-images.githubusercontent.com/82361606/207509816-1e90d917-037f-443e-99b4-f649e2521452.png)

**Comment by XuanYang-cn** [comment]
Handoff watch loop stopped because of `etcdserver: mvcc: required revision has been compacted`, and never able to handoff after.
![image](https://user-images.githubusercontent.com/51370125/207528538-c11e77b9-7bff-4417-831f-1b1b2f9aa379.png)

**Comment by XuanYang-cn** [comment]
/assign @yanliang567 
This should be fixed on master

**Comment by yanliang567** [comment]
verified on 2.2.1
