### ISSUE TITLE
[doc]: the valid scope for search_k is incorrect

### ISSUE THREAD

**Issue by cydrain** [milvus-io/milvus#21211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

in this webpage https://milvus.io/docs/index.md , the description for param "search_k" is incorrect:

![Screenshot from 2022-12-14 11-14-58](https://user-images.githubusercontent.com/3992404/207497000-b52826c0-4055-44ce-b362-3ca71bf7c61b.png)

By checking ANNOY official website in github ([spotify/annoy](https://github.com/spotify/annoy)),
the description for parameter "search_k" is as following:

![Screenshot from 2022-12-13 21-29-27](https://user-images.githubusercontent.com/3992404/207497239-47d18262-4f5b-40c2-85be-e78a6a5e0814.png)

So knowhere has updated "search_k" 's scope to [k, inf], please update this doc.

### Expected Behavior

param "searck_k" 's valid scope should be updated to [k, inf]

**Comment by yanliang567** [comment]
param "searck_k" 's valid scope should be updated to [k, inf].
@cydrain k is topk? what is inf ?

**Comment by cydrain** [comment]
> param "searck_k" 's valid scope should be updated to [k, inf]. @cydrain k is topk? what is inf ?

"inf" means infinite

**Comment by AnthonyTsu1984** [comment]
Already been resolved. see
https://milvus.io/docs/index.md#ANNOY
