### ISSUE TITLE
提供一种不会删除已下载资源的清理构建产物方式

### ISSUE THREAD

**Issue by thirstycrow** [milvus-io/milvus#2122]
**Is your feature request related to a problem? Please describe.**
build.sh -r (或者在 cmake_build 下执行 make clean）会把之前下载的第三方代码包删掉，下次构建的时候需要重新下载，时间太长了

**Describe the solution you'd like**
提供一种不会删除已下载资源的清理构建产物方式

**Comment by JinHai-CN** [comment]
Good idea! 
Check the parameter URL_HASH / URL_MD5 of https://cmake.org/cmake/help/latest/module/ExternalProject.html.
