### ISSUE TITLE
Support cache priority

### ISSUE THREAD

**Issue by lzhx171** [milvus-io/milvus#2123]
**Describe the bug**
When the cpu_cache_capacity size is less than the total size of memory  the index needs(i.e. the index needs 12GB mem, but cpu_cache_capacity is 10G), no matter what value  cpu_cache_capacity is set(i.e. cpu_cache_capacity:10  or cpu_cache_capacity:4 ), the search cost is almost same. The index  block in  cache may not be hit and is swapped out by LRU, which makes it loaded again from disk when its turn to search. Generally  if  cpu_cache_capacity :10, only 2GB block need to be swapped.

**Steps/Code to reproduce behavior**
num of vec: 12,000,000
num of dim: 1024
format: float
index type: ivfsq8
cpu_cache_capacity: 10 or 4 or 2

**Expected behavior**
In search task, index in cache should be searched in priority, and than swapped out by LRU
The larger the cpu_cache_capacity, the shorter the search time.  

**Environment details**
- CPU, ubuntu1604
- Docker
- Milvus version v0.8.0
- cpu_cache_capacity: 10 # 4 or 2 or ...

**Comment by JinHai-CN** [comment]
@scsven We may change the scheduler policy to achieve this enhancement.

**Comment by yhmo** [comment]
Currently we only fix critical issues for v1.x. This issue is not a block issue, we will keep it pending here.

**Comment by scsven** [comment]
@lzhx171 Hi, thanks for your attention. Although Milvus v1 is a disk-based design, it's a large cost to load data from the disk actually. Even we made a new policy, it also needs to load the disk files each time. And the 1.0 series is stable, we will not update it unless bugs are found. 
Now the version 2.0 is developing, it's a pure memory-based design, and it also supports cluster deployment. Have a try: https://milvus.io/docs/home
