### ISSUE TITLE
[Bug]: Lack check of new maximum field's number '64'

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#21238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:9d8f422
- Deployment mode(standalone or cluster):cluster & standalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0.dev21
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Lack check of new maximum field's number '64'.
When creating collection with 65 fields, it doesn't raise exception.
When creating collection with 267 fields, it will raise MilvusException: (code=1, message=maximum field's number should be limited to 256)

And 2 test cases were affected:
test_create_collection_limit_fields
test_create_collection_over_maximum_fields

### Expected Behavior

update

**Comment by NicoYuan1986** [comment]
Link: #21104

**Comment by binbinlv** [comment]
@soothing-rain 

Could you please have a look? Thanks.

**Comment by soothing-rain** [comment]
I already updated the limit in python config:
https://github.com/milvus-io/milvus/blob/master/tests/python_client/common/common_type.py#L60

There should be no problem when https://github.com/milvus-io/milvus/pull/21239 is address right?

**Comment by NicoYuan1986** [comment]
> I already updated the limit in python config: https://github.com/milvus-io/milvus/blob/master/tests/python_client/common/common_type.py#L60
> 
> There should be no problem when #21239 is address right?

Yes, I found the update of maximum field's number. But we need more check.
![image](https://user-images.githubusercontent.com/109071306/207830241-94ae7996-a19b-4608-81ea-695d3bab191b.png)
![image](https://user-images.githubusercontent.com/109071306/207830630-da1d3647-6683-4dd9-a4b9-22e45687f65d.png)

**Comment by NicoYuan1986** [comment]
Verified fixed.
