### ISSUE TITLE
[Enhancement]: Merge IndexCoord to DataCoord

### ISSUE THREAD

**Issue by xiaocai2333** [milvus-io/milvus#21269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

1. Merge IndexCoord to DataCoord.
2. Remove handoff.
3. Remove flushed segment watcher.
4. Remove segment reference lock.
5. GetRecoverInfo return indexed, flushed unindexed, growing segments.
6. Compaction with flushed segment instead of indexed.

### Why is this needed?

1. Improve code maintainability.
2. Fixed some handoff events not being handled correctly.
3. In the case with compaction, the index will be built faster.

**Comment by xiaofan-luan** [comment]
keep it
