### ISSUE TITLE
[Bug]: The versions in releases notes are wrong for v2.2.1 and v2.2.0

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#21270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The milvus version and python SDK version are wrong for v2.2.1 and v2.2.0

![gYShSZTPdK](https://user-images.githubusercontent.com/83755740/208009474-34d89c3f-a15b-46bb-bb2a-c7b2404342b0.jpg)
![lyAcGLxLdj](https://user-images.githubusercontent.com/83755740/208009488-059b6321-3fac-40cc-8cd6-04357388e8ea.jpg)

### Expected Behavior

v2.2.1: milvus 2.2.1, python SDK version: 2.2.1
v 2.2.0: milvus version: 2.2.0

### Steps To Reproduce

```markdown
https://milvus.io/docs/release_notes.md
```

**Comment by yanliang567** [comment]
![image](https://user-images.githubusercontent.com/82361606/208339656-09767958-b220-4369-8cd7-bac5991c4f33.png)

**Comment by yanliang567** [comment]
verified fix
