### ISSUE TITLE
[doc]: The limit of resource 'field' is incorrect in the official documents

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#21278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://milvus.io/docs/limitations.md
On this page, field limit is 256. We need to update it to 64 according to #21238 and #21239
![image](https://user-images.githubusercontent.com/109071306/208034477-548239cf-ff31-462e-8fb5-ee27086bbb2f.png)

### Expected Behavior

update fields limit to 64

**Comment by yanliang567** [comment]
verified fix
