### ISSUE TITLE
[Bug]: Milvus and pymilvus version are wrong in "hello milvus" page

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#21272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://milvus.io/docs/example_code.md

### Expected Behavior

Milvus 2.2.1 and pymilvus 2.2.1

### Steps To Reproduce

```markdown
https://milvus.io/docs/example_code.md
```

**Comment by binbinlv** [comment]
![image](https://user-images.githubusercontent.com/83755740/208024839-96d4ec7d-08c8-4ead-8f54-15f2f783ee9f.png)

**Comment by yanliang567** [comment]
verified fixed
