### ISSUE TITLE
[Bug]:  cluster load failed and datanode oom

### ISSUE THREAD

**Issue by Cheung7788** [milvus-io/milvus#21279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.2.0
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. insert data quickly causes datanode to not work
2. load random_test_2 failed 
![image](https://user-images.githubusercontent.com/28556111/208039627-75a45524-3f62-4549-8983-a59a321e44cd.png)

### Milvus Log

[bw_etcd_ALL.221216-133308.bak.gz](https://github.com/milvus-io/milvus/files/10243293/bw_etcd_ALL.221216-133308.bak.gz)
[logs.tar (8).gz](https://github.com/milvus-io/milvus/files/10243254/logs.tar.8.gz)

**Comment by congqixia** [comment]
Load failed due to loading progress exceeded 10 minutes timeout 
```
#milvus-querycoord-69fd6584d-xplhp.log
26538:[2022/12/16 04:03:37.528 +00:00] [INFO] [observers/collection_observer.go:113] ["load collection timeout, cancel it"] [collectionID=438070723963719134] [loadTime=10m0.524413618s]
```
Load timeout is configurable in v2.2.0
