### ISSUE TITLE
[Enhancement]: Impl rename collection name interface asap

### ISSUE THREAD

**Issue by yelusion2** [milvus-io/milvus#21284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

i need a api to rename coolection name;

### Why is this needed?

in this case:
step1: backup collection like collection_test
step2: restore collection_test and new collection named collection_test_back
step3: check collection_test_back data, and its ok;

then i must update my application code to use collection collection_test_back.

if i can rename collection name, i can do like these:
step4: rename collection collection_test to collection_test_history
step5: rename collection collection_test_back to collection_test

so my application do not change anthing.

**Comment by yelusion2** [comment]
i want this api asap, preferably milvus 2.2.2.

**Comment by JackLCL** [comment]
@yelusion2 
I think collection alias is what you want. 
https://milvus.io/docs/collection_alias.md#Collection-Alias

**Comment by yelusion2** [comment]
@JackLCL 
These are two different concepts.
