### ISSUE TITLE
[Bug]: can not load when I released data.

### ISSUE THREAD

**Issue by dzqoo** [milvus-io/milvus#21285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Centos
- CPU/Memory: 3C24G
- GPU: 
- Others:
```

### Current Behavior

When I released data, I can not load data anymone and got the following error:

![a54f720caca80dfdb7ac0934c32c995e](https://user-images.githubusercontent.com/8862305/208061874-14263b64-da0e-4a61-
9ecf-f46f08c62b2f.png)

queryNode has following error:
![image](https://user-images.githubusercontent.com/8862305/208062107-e5b5754a-7a94-436e-a1e4-e1de66d8033c.png)

Here is all the logs:

[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/10244218/milvus-log.tar.gz)

**Comment by xiaofan-luan** [comment]
@bigsheeper could you take a look into it?

**Comment by bigsheeper** [comment]
@dzqoo seems the `![a54f720caca80dfdb7ac0934c32c995e](https://user-images.githubusercontent.com/8862305/208061874-14263b64-da0e-4a61-
9ecf-f46f08c62b2f.png)` is invalid.

**Comment by bigsheeper** [comment]
I found lots of OOM warning:
```
[error="follower 20 failed to load segment, reason load segment failed, OOM if load, collectionID = 438063355644253010, maxSegmentSize = 449 MB, concurrency = 1, usedMemAfterLoad = 20784 MB, totalMem = 24576 MB, thresholdFactor = 0.900000"]
```

@dzqoo could you please offer me the memory monitor of all querynodes?  Seems the memory resource is nearly exhausted.

**Comment by xiaofan-luan** [comment]
maybe change the config  querycoord.overloadedMemoryThresholdPercentage from 0.9 to 0.95 will help.
By default milvus reserve 10% memory which, is 2.4G, so each querynode can only use up to 21.6G in your case.
On your case, your memory slightly over the 21.6G (20784 + 4 * 449M)

**Comment by dzqoo** [comment]
> Hello @dzqoo seems the `![a54f720caca80dfdb7ac0934c32c995e](https://user-images.githubusercontent.com/8862305/208061874-14263b64-da0e-4a61- 9ecf-f46f08c62b2f.png)` is invalid.
> 
> And what's the phenomenon when load, any error message or timeout message?

![a54f720caca80dfdb7ac0934c32c995e](https://user-images.githubusercontent.com/8862305/208068159-04667d0c-4c36-48ed-9574-73221cc8ab91.png)

**Comment by xiaofan-luan** [comment]
might because of your collection is not loaded but keeping receive search/insert request

**Comment by xiaofan-luan** [comment]
> > Hello @dzqoo seems the `![a54f720caca80dfdb7ac0934c32c995e](https://user-images.githubusercontent.com/8862305/208061874-14263b64-da0e-4a61- 9ecf-f46f08c62b2f.png)` is invalid.
> > And what's the phenomenon when load, any error message or timeout message?
> 
> ![a54f720caca80dfdb7ac0934c32c995e](https://user-images.githubusercontent.com/8862305/208068159-04667d0c-4c36-48ed-9574-73221cc8ab91.png)

could you do me a favor? is there still a environement left?

**Comment by xiaofan-luan** [comment]
we need pprof info on querynode, seems to be a dead lock here

**Comment by dzqoo** [comment]
> I found lots of OOM warning:
> 
> ```
> [error="follower 20 failed to load segment, reason load segment failed, OOM if load, collectionID = 438063355644253010, maxSegmentSize = 449 MB, concurrency = 1, usedMemAfterLoad = 20784 MB, totalMem = 24576 MB, thresholdFactor = 0.900000"]
> ```
> 
> @dzqoo could you please offer me the memory monitor of all querynodes? Seems the memory resource is nearly exhausted.

![image](https://user-images.githubusercontent.com/8862305/208069986-394950b9-f6d7-4d21-8345-687cd5991366.png)


> we need pprof info on querynode, seems to be a dead lock here

How can I get this?

**Comment by xiaofan-luan** [comment]
I thouht it's ai-diagnose-test-milvus-querynode-5c4f99df68-7tsc2.log

**Comment by bigsheeper** [comment]
> > we need pprof info on querynode, seems to be a dead lock here
> 
> How can I get this?

like this: `curl http://10.14.105.220:9091/debug/pprof/heap > "$(date +"%FT%T").heap"`
then you could found a xxx.heap file.

**Comment by bigsheeper** [comment]
> I thouht it's ai-diagnose-test-milvus-querynode-5c4f99df68-7tsc2.log

@dzqoo You could modify `10.14.105.220` to this querynode's address.

**Comment by xiaofan-luan** [comment]
I've seen a couple of similar scenarios, but have no idea about why it's deadlocked.

**Comment by dzqoo** [comment]
[2022-12-16T180615.zip](https://github.com/milvus-io/milvus/files/10244789/2022-12-16T180615.zip)
Here is the heap

**Comment by bigsheeper** [comment]
@dzqoo could you offer me goroutine info by `curl http://10.14.105.220:9091/debug/pprof/goroutines > "$(date +"%FT%T").out`

**Comment by dzqoo** [comment]
[2022-12-16T183454.zip](https://github.com/milvus-io/milvus/files/10244969/2022-12-16T183454.zip)


> @dzqoo could you offer me goroutine info by `curl http://xxx:9091/debug/pprof/goroutine?debug=2 > "$(date +"%FT%T").out`

**Comment by xiaofan-luan** [comment]
I'm on it. Root cause found

**Comment by xiaofan-luan** [comment]
didn't find any blocking on GetDataDistribution.
Any other querynode blocking on this?

**Comment by xiaofan-luan** [comment]
<img width="518" alt="image" src="https://user-images.githubusercontent.com/83447078/208086718-d3b9dbcd-8054-4379-bf9c-db775b75206b.png">

should be nodeID = 23, my fault.
the machine should be @dzqoo 
ai-diagnose-test-milvus-querynode-5c4f99df68-rcznl.log

**Comment by xiaofan-luan** [comment]
and once your do pprof, reboot this machine and cluster will recover.

**Comment by dzqoo** [comment]
[rcznl.zip](https://github.com/milvus-io/milvus/files/10245336/rcznl.zip)
here is the heap of ai-diagnose-test-milvus-querynode-5c4f99df68-rcznl

**Comment by dzqoo** [comment]
other scene: my attu can not open

**Comment by bigsheeper** [comment]
@dzqoo please help to dump the goroutine file of `ai-diagnose-test-milvus-querynode-5c4f99df68-p7kd4`. Thanks a lot.

**Comment by dzqoo** [comment]
[p7kd4.zip](https://github.com/milvus-io/milvus/files/10245473/p7kd4.zip)

**Comment by xiaofan-luan** [comment]
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/83447078/208094019-708c808c-c0d3-4164-8c0c-8f3ae75dea64.png">

**Comment by xiaofan-luan** [comment]
Stucked on LRU cache close.
In 2.2.1 the implementation change a little bit

**Comment by dzqoo** [comment]
> Stucked on LRU cache close. In 2.2.1 the implementation change a little bit

Can I upgrade milvus from 2.2.0 to 2.2.1 directly?

**Comment by xiaofan-luan** [comment]
> Author

It should not block, but maybe it can be still improved a little bit

**Comment by xiaofan-luan** [comment]
upgrade to 2.2.1 fix the issue, with #21294 it should be even faster

**Comment by yanliang567** [comment]
@dzqoo did you upgrade to 2.2.1 as suggested? please keep us posted if any issues.

**Comment by dzqoo** [comment]
I have upgraed to milvus2.2.1.And everything went well.
BUT, I upgrade dataCoor's config(change maxSize from 512 to 2048) and then some collection can't loaded.

Here is all the logs :
[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/10255219/milvus-log.tar.gz)

**Comment by yanliang567** [comment]
@bigsheeper could you please help to take a look

**Comment by yanliang567** [comment]
@dzqoo do you still have this issue on 2.2.2?

**Comment by yanliang567** [comment]
close it for now. please feel free to file a new one if any new problems.
