### ISSUE TITLE
[Bug]: [benchmark][varchar]Milvus varchar field has higher memory after indexing than without indexing

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#21295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20221213-1c309a74
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.1dev4
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

fouramf-pcv5h：
deploy_config
fouramf-server-cluster-8c24m-test
case_params：
fouramf-client-varchar50-search-noindex
other_params：
 --milvus_tag=2.2.0-20221213-1c309a74 -k test_search_custom_parameters -s --case_skip_clean_collection --deploy_mode=cluster --sync_report
server：

```
fouramf-pcv5h-81-8826-etcd-0                                     1/1     Running     0              84m     10.104.5.162   4am-node12   <none>           <none>
fouramf-pcv5h-81-8826-etcd-1                                     1/1     Running     0              84m     10.104.6.185   4am-node13   <none>           <none>
fouramf-pcv5h-81-8826-etcd-2                                     1/1     Running     0              84m     10.104.1.75    4am-node10   <none>           <none>
fouramf-pcv5h-81-8826-milvus-datacoord-756dd9ff8d-jlkbw          1/1     Running     0              84m     10.104.4.15    4am-node11   <none>           <none>
fouramf-pcv5h-81-8826-milvus-datanode-75d89d4585-p6z27           1/1     Running     0              84m     10.104.9.3     4am-node14   <none>           <none>
fouramf-pcv5h-81-8826-milvus-indexcoord-7f664f7bf9-psnjc         1/1     Running     0              84m     10.104.4.13    4am-node11   <none>           <none>
fouramf-pcv5h-81-8826-milvus-indexnode-5bffc7746b-8jtdz          1/1     Running     0              84m     10.104.4.16    4am-node11   <none>           <none>
fouramf-pcv5h-81-8826-milvus-proxy-6bf5f6c45c-98bmb              1/1     Running     0              84m     10.104.1.70    4am-node10   <none>           <none>
fouramf-pcv5h-81-8826-milvus-querycoord-85b5d9c45b-n9czk         1/1     Running     0              84m     10.104.5.155   4am-node12   <none>           <none>
fouramf-pcv5h-81-8826-milvus-querynode-6f844b5c68-pqr89          1/1     Running     0              84m     10.104.1.71    4am-node10   <none>           <none>
fouramf-pcv5h-81-8826-milvus-rootcoord-cd76dcdb8-sg5vm           1/1     Running     0              84m     10.104.4.17    4am-node11   <none>           <none>
fouramf-pcv5h-81-8826-minio-0                                    1/1     Running     0              84m     10.104.5.164   4am-node12   <none>           <none>
fouramf-pcv5h-81-8826-minio-1                                    1/1     Running     0              84m     10.104.6.187   4am-node13   <none>           <none>
fouramf-pcv5h-81-8826-minio-2                                    1/1     Running     0              84m     10.104.1.78    4am-node10   <none>           <none>
fouramf-pcv5h-81-8826-minio-3                                    1/1     Running     0              84m     10.104.9.8     4am-node14   <none>           <none>
fouramf-pcv5h-81-8826-pulsar-bookie-0                            1/1     Running     0              84m     10.104.5.163   4am-node12   <none>           <none>
fouramf-pcv5h-81-8826-pulsar-bookie-1                            1/1     Running     0              84m     10.104.6.188   4am-node13   <none>           <none>
fouramf-pcv5h-81-8826-pulsar-bookie-2                            1/1     Running     0              84m     10.104.1.77    4am-node10   <none>           <none>
fouramf-pcv5h-81-8826-pulsar-bookie-init-kqghl                   0/1     Completed   0              84m     10.104.1.69    4am-node10   <none>           <none>
fouramf-pcv5h-81-8826-pulsar-broker-0                            1/1     Running     0              84m     10.104.4.14    4am-node11   <none>           <none>
fouramf-pcv5h-81-8826-pulsar-proxy-0                             1/1     Running     0              84m     10.104.5.153   4am-node12   <none>           <none>
fouramf-pcv5h-81-8826-pulsar-pulsar-init-lfb94                   0/1     Completed   0              84m     10.104.1.68    4am-node10   <none>           <none>
fouramf-pcv5h-81-8826-pulsar-recovery-0                          1/1     Running     0              84m     10.104.5.154   4am-node12   <none>           <none>
fouramf-pcv5h-81-8826-pulsar-zookeeper-0                         1/1     Running     0              84m     10.104.5.160   4am-node12   <none>           <none>
fouramf-pcv5h-81-8826-pulsar-zookeeper-1                         1/1     Running     0              83m     10.104.6.190   4am-node13   <none>           <none>
fouramf-pcv5h-81-8826-pulsar-zookeeper-2                         1/1     Running     0              82m     10.104.1.80    4am-node10   <none>           <none> 
```

This is a varchar field with no memory for indexing：

<img width="1377" alt="截屏2022-12-16 21 31 29" src="https://user-images.githubusercontent.com/34296482/208109435-39a504e0-f9ae-4fdc-9db4-32e9d96bf458.png">

fouramf-server-cluster-8c24m-test
case_params
fouramf-client-varchar50-search
other_params
 --milvus_tag=2.2.0-20221213-1c309a74 -k test_search_custom_parameters -s --case_skip_clean_collection --deploy_mode=cluster --sync_report

server：

```
fouramf-ztbzf-59-9866-etcd-0                                     1/1     Running     0              114m    10.104.1.34    4am-node10   <none>           <none>
fouramf-ztbzf-59-9866-etcd-1                                     1/1     Running     0              114m    10.104.4.31    4am-node11   <none>           <none>
fouramf-ztbzf-59-9866-etcd-2                                     1/1     Running     0              114m    10.104.5.173   4am-node12   <none>           <none>
fouramf-ztbzf-59-9866-milvus-datacoord-7b4658dfd7-k5jqg          1/1     Running     0              114m    10.104.4.21    4am-node11   <none>           <none>
fouramf-ztbzf-59-9866-milvus-datanode-7c49cfd746-mvp6v           1/1     Running     0              114m    10.104.5.167   4am-node12   <none>           <none>
fouramf-ztbzf-59-9866-milvus-indexcoord-6444f87cd8-cdttn         1/1     Running     0              114m    10.104.4.16    4am-node11   <none>           <none>
fouramf-ztbzf-59-9866-milvus-indexnode-66bccc4dc7-fbs54          1/1     Running     0              114m    10.104.9.229   4am-node14   <none>           <none>
fouramf-ztbzf-59-9866-milvus-proxy-5c87b4bcfd-84gz6              1/1     Running     0              114m    10.104.4.17    4am-node11   <none>           <none>
fouramf-ztbzf-59-9866-milvus-querycoord-7c546ccdff-nt4k7         1/1     Running     0              114m    10.104.5.166   4am-node12   <none>           <none>
fouramf-ztbzf-59-9866-milvus-querynode-d648b9d95-9mzhm           1/1     Running     0              114m    10.104.9.227   4am-node14   <none>           <none>
fouramf-ztbzf-59-9866-milvus-rootcoord-866ff58fc-lgktx           1/1     Running     0              114m    10.104.9.228   4am-node14   <none>           <none>
fouramf-ztbzf-59-9866-minio-0                                    1/1     Running     0              114m    10.104.1.31    4am-node10   <none>           <none>
fouramf-ztbzf-59-9866-minio-1                                    1/1     Running     0              114m    10.104.4.30    4am-node11   <none>           <none>
fouramf-ztbzf-59-9866-minio-2                                    1/1     Running     0              114m    10.104.5.172   4am-node12   <none>           <none>
fouramf-ztbzf-59-9866-minio-3                                    1/1     Running     0              114m    10.104.6.24    4am-node13   <none>           <none>
fouramf-ztbzf-59-9866-pulsar-bookie-0                            1/1     Running     0              114m    10.104.4.26    4am-node11   <none>           <none>
fouramf-ztbzf-59-9866-pulsar-bookie-1                            1/1     Running     0              114m    10.104.1.35    4am-node10   <none>           <none>
fouramf-ztbzf-59-9866-pulsar-bookie-2                            1/1     Running     0              114m    10.104.5.174   4am-node12   <none>           <none>
fouramf-ztbzf-59-9866-pulsar-bookie-init-v8tx7                   0/1     Completed   0              114m    10.104.4.18    4am-node11   <none>           <none>
fouramf-ztbzf-59-9866-pulsar-broker-0                            1/1     Running     0              114m    10.104.1.28    4am-node10   <none>           <none>
fouramf-ztbzf-59-9866-pulsar-proxy-0                             1/1     Running     0              114m    10.104.4.14    4am-node11   <none>           <none>
fouramf-ztbzf-59-9866-pulsar-pulsar-init-5pbrz                   0/1     Completed   0              114m    10.104.4.19    4am-node11   <none>           <none>
fouramf-ztbzf-59-9866-pulsar-recovery-0                          1/1     Running     0              114m    10.104.4.15    4am-node11   <none>           <none>
fouramf-ztbzf-59-9866-pulsar-zookeeper-0                         1/1     Running     0              114m    10.104.4.28    4am-node11   <none>           <none>
fouramf-ztbzf-59-9866-pulsar-zookeeper-1                         1/1     Running     0              113m    10.104.1.37    4am-node10   <none>           <none>
fouramf-ztbzf-59-9866-pulsar-zookeeper-2                         1/1     Running     0              113m    10.104.5.176   4am-node12   <none>           <none>
```

This is the varchar field to create the index memory：

<img width="1378" alt="截屏2022-12-16 21 34 11" src="https://user-images.githubusercontent.com/34296482/208110669-35babbec-26f2-4bb2-b7a9-4ed8341a8f4e.png">

### Steps To Reproduce

```markdown
1. create a collection 
        2. build index on vector column
        3. insert a 1m of vectors
        4. flush collection
        5. build index on vector column with the same parameters
        6. build index on on scalars column or not
        7. count the total number of rows
        8. load collection
        9. search collection
```

### Anything else?

[Collection schema: {'auto_id': False, 'description': '', 'fields': [{'name': 'id', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float_vector', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 128}}, {'name': 'varchar_1', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_2', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_3', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_4', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_5', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_6', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_7', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_8', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_9', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_10', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_11', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_12', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_13', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_14', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_15', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_16', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_17', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_18', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_19', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_20', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_21', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_22', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_23', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_24', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_25', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_26', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_27', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_28', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_29', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_30', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_31', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_32', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_33', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_34', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_35', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_36', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_37', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_38', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_39', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_40', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_41', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_42', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_43', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_44', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_45', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_46', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_47', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_48', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_49', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_50', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}]} (base.py:118)

**Comment by yanliang567** [comment]
keep it active
