### ISSUE TITLE
[Bug]: Dev container can not compile latest milvus

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#21293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1 . sh scripts/devcontainer.sh up
2. ssh into dev container
3. make

the make failed with
<img width="936" alt="image" src="https://user-images.githubusercontent.com/83447078/208079383-485cd8e3-39df-482f-a597-081a03bcc654.png">

**Comment by jiaoew1991** [comment]
fixed it by #21301

**Comment by xiaofan-luan** [comment]
still not working, reopen it

**Comment by xiaofan-luan** [comment]
something related to boost compile

**Comment by jiaoew1991** [comment]
fixed by https://github.com/milvus-io/milvus/pull/21374
