### ISSUE TITLE
[Enhancement]: Implement pure go PayloadWriter

### ISSUE THREAD

**Issue by jiaoew1991** [milvus-io/milvus#21290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

We are using cgo based PayloadWriter which caused lots of memory bugs, and the cgo call is bad for performance, we can implement a pure Go version 

The other benefit is to reduce the C dependence of datanode and datacoord

**Comment by xiaofan-luan** [comment]
Agreed. 
Should we refine the dataformat?  otherwise go writer will be rewritten soon

**Comment by jiaoew1991** [comment]
> Agreed. Should we refine the dataformat? otherwise go writer will be rewritten soon

the data format should be refined later, it is a long-term feature that may be finished in 2023 Q1, but in these 3 months we can use Go PayloadWriter to avoid panic issues

**Comment by yah01** [comment]
/assign
As I will be involved in the new storage format design, also take this

**Comment by xiaofan-luan** [comment]
@yah01 
@jiaoew1991 
Is there any performance comparison?
