### ISSUE TITLE
[Bug]: Quercoord init failed: task sum out of range, should amplify queryCoord.maxTask

### ISSUE THREAD

**Issue by zhenzi0322** [milvus-io/milvus#21323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.1.4
- Deployment mode(standalone or cluster): standalone 
- MQ type(rocksmq, pulsar or kafka):    none
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.0
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 125
- GPU: p40
- Others: none
```

### Current Behavior

After importing more than 1.8 million vectors, milvus standalone stops running

### Milvus Log

```
 docker logs milvus-standalone --tail 100
```

[2022/12/20 08:25:52.828 +00:00] [INFO] [datanode/data_sync_service.go:233] ["recover sealed segments form checkpoints"] [vChannelName=by-dev-rootcoord-dml_0_438177692397800769v0] [segmentID=438179168412499969] [numRows=489]
[2022/12/20 08:25:52.828 +00:00] [INFO] [datanode/segment_replica.go:495] ["begin to init pk bloom filter"] [segmentID=438179374746042369] ["stats bin logs"=1]
[2022/12/20 08:25:52.828 +00:00] [INFO] [datanode/data_sync_service.go:241] ["Add Flushed segment"] ["segment ID"=438178984072839169] ["collection ID"=438177692397800769] ["partition ID"=438177692397800770] ["channel name"=by-dev-rootcoord-dml_0_438177692397800769v0]
[2022/12/20 08:25:52.828 +00:00] [INFO] [datanode/segment_replica.go:495] ["begin to init pk bloom filter"] [segmentID=438178984072839169] ["stats bin logs"=1]
panic: Quercoord init failed: task sum out of range, should amplify queryCoord.maxTask

goroutine 254 [running]:
github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).reloadFromKV(0xc0049a2500, 0xc004ebe860, 0xc0044ce800)
        /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:304 +0xe6b
github.com/milvus-io/milvus/internal/querycoord.newTaskScheduler(0x43b7d10, 0xc001194040, 0x43f20d8, 0xc00321f520, 0x43e9350, 0xc0033a0b00, 0xc003007758, 0xc004b923c0, 0xc00320d100, 0xc004ba3680, ...)
        /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:211 +0x235
github.com/milvus-io/milvus/internal/querycoord.(*QueryCoord).Init.func1()
        /go/src/github.com/milvus-io/milvus/internal/querycoord/query_coord.go:212 +0x1650
sync.(*Once).doSlow(0xc0001c6f30, 0xc000b592b0)
        /usr/local/go/src/sync/once.go:68 +0xec
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:59
github.com/milvus-io/milvus/internal/querycoord.(*QueryCoord).Init(0xc0001c6f00, 0xa, 0xc003216d80)
        /go/src/github.com/milvus-io/milvus/internal/querycoord/query_coord.go:135 +0x2d2
github.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).init(0xc000c6dea0, 0x8bdf3e, 0xc001008f78)
        /go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:227 +0x18b4
github.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).Run(0xc000c6dea0, 0xc000c6de00, 0x0)
        /go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:96 +0x2f
github.com/milvus-io/milvus/cmd/components.(*QueryCoord).Run(0xc00021ff20, 0xffffffffffffffff, 0x43ca108)
        /go/src/github.com/milvus-io/milvus/cmd/components/query_coord.go:50 +0x33
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runQueryCoord.func1(0x400b001, 0x43b7d10, 0xc000c778c0, 0xc00045b480, 0xc000474130, 0xc001008f70)
        /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:186 +0x125
created by github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runQueryCoord
        /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:168 +0xba

**Comment by xiaofan-luan** [comment]
hi @zhenzi0322,
If you are still under test, maybe you can upgrade to 2.2.1 because we refactor the querycoord implementation in total so it's better not to spend time on older versions.
If it's your production environment, we can help you to figure out a way to recover and then upgrade

**Comment by zhenzi0322** [comment]
该版本v2.1.4有我想要的刚插入向量就能搜索出来向量的功能。有没有办法不升级就能解决该问题的。

**Comment by yanliang567** [comment]
> 该版本v2.1.4有我想要的刚插入向量就能搜索出来向量的功能。有没有办法不升级就能解决该问题的。

what you want is also supported in v2.2.1. One more question: how did you insert data into milvus? how many threads, how much data for each batch insert?

/assign @zhenzi0322

**Comment by zhenzi0322** [comment]
两个线程，每次插入1000个图片向量，插入到180万左右就突然停止了服务。

**Comment by xiaofan-luan** [comment]
> 两个线程，每次插入1000个图片向量，插入到180万左右就突然停止了服务。

if you could share the server side logs that would be helpful.
Usually that could be caused by OOM or out of disk space.

**Comment by zhenzi0322** [comment]
顶部贴有日志的，后面100条的日志。从日志提示来看，不是磁盘空间的问题，我也检查过磁盘，还有很多

**Comment by yanliang567** [comment]
we need full logs to address what is happening. Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

**Comment by xiaofan-luan** [comment]
@zhenzi0322 could you offer logs for this issue or this is no more a issue?
