### ISSUE TITLE
After the queryNode is restarted, "target node id not match" displayed when search. [Bug]: 

### ISSUE THREAD

**Issue by ggKe** [milvus-io/milvus#21325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.1
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 16c16G
- GPU: 
- Others:
```

### Current Behavior

{
"data": "no search data",
"error": "fail to search on all shard leaders, err=fail to Search, QueryNode ID=28, reason=QueryNode 50 can't serve, recovering: target node id not match target id = 28, node id = 50",
"message": "fail to search on all shard leaders, err=fail to Search, QueryNode ID=28, reason=QueryNode 50 can't serve, recovering: target node id not match target id = 28, node id = 50",
"status": "failed"
}

An error was reported before the querynode restarted

{"level":"warn","ts":"2022-12-20T15:08:50.082+0800","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000288a80/#initially=[milvus-test.etcd1.corpauto.com:2385;milvus-test.etcd2.corpauto.com:2385;milvus-test.etcd3.corpauto.com:2385]","attempt":0,"error":"rpc error: code = NotFound desc = etcdserver: requested lease not found"}
{"level":"warn","ts":"2022-12-20T15:08:50.083+0800","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000288a80/#initially=[milvus-test.etcd1.corpauto.com:2385;milvus-test.etcd2.corpauto.com:2385;milvus-test.etcd3.corpauto.com:2385]","attempt":0,"error":"rpc error: code = NotFound desc = etcdserver: requested lease not found"}

### Steps To Reproduce

```markdown
milvus v2.2.1
1、one of the queryNodes is restarted
2、search any collection
3、An error occurs in the query result."target node id not match "
4、Occasionally you can succeed
5、Restart the proxy and the problem disappears.
```

**Comment by xiaofan-luan** [comment]
https://github.com/milvus-io/milvus/pull/21185 
seems to solve the same issue
