### ISSUE TITLE
Dev test fail.

### ISSUE THREAD

**Issue by BossZou** [milvus-io/milvus#2134]
**Describe the bug**
```
test_connect.py::TestConnect::test_connect_uri_null FAILED                                                                                                                                                              [ 96%]
--------------------------------------------------------------------------------------------------- live log sessionfinish ----------------------------------------------------------------------------------------------------
[17:24:15-INFO-root]: Please connect to the server first! (conftest.py:52)


=================================== FAILURES ===================================
______________________ TestConnect.test_connect_uri_null _______________________

self = <test_connect.TestConnect object at 0x7f878284f6d8>
args = {'handler': 'GRPC', 'ip': 'localhost', 'port': 19530}

    def test_connect_uri_null(self, args):
        '''
        target: test connect with null uri
        method: uri set null
        expected: connected is True
        '''
        uri_value = ""
        if self.local_ip(args):
>           milvus = get_milvus(uri=uri_value, handler=args["handler"])
E           TypeError: get_milvus() missing 2 required positional arguments: 'host' and 'port'

test_connect.py:106: TypeError
```

It seem like passing parameters `port`, `host` in function `get_milvus()` miss default value.

---------------------------------------------------------------------------------------------------------------------
@del-zhenwu , I you solved this issue, please let me know.

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)
- Commit id: 12b3bf0693dd277626fcef873efa5342155e45ab
**Screenshots**

**Additional context**

**Comment by del-zhenwu** [comment]
fixed
