### ISSUE TITLE
[Bug]: Pymilvus 2.2.1 collection drop is fail

### ISSUE THREAD

**Issue by byeong0** [milvus-io/milvus#21342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.1
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.2.1
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

utility.drop_collection("hello_milvus")

### Milvus Log

RPC error: [drop_collection], <MilvusException: (code=1, message=InvalidateCollectionMetaCache failed, proxyID = 74, err = err: failed to connect 10.255.92.62:19529, reason: context deadline exceeded
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:304 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall
/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/client/client.go:135 github.com/milvus-io/milvus/internal/distributed/proxy/client.(*Client).InvalidateCollectionMetaCache
/go/src/github.com/milvus-io/milvus/internal/rootcoord/proxy_client_manager.go:139 github.com/milvus-io/milvus/internal/rootcoord.(*proxyClientManager).InvalidateCollectionMetaCache.func1
/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 golang.org/x/sync/errgroup.(*Group).Go.func1
/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit
)>, <Time:{'RPC start': '2022-12-22 09:10:33.399717', 'RPC error': '2022-12-22 09:10:46.356164'}>
Traceback (most recent call last):
  File "/Users/byeong0/ssg/src/ssg-brain-app/test_milvus.py", line 194, in <module>
    utility.drop_collection("hello_milvus")
  File "/opt/homebrew/lib/python3.9/site-packages/pymilvus/orm/utility.py", line 403, in drop_collection
    return _get_connection(using).drop_collection(collection_name, timeout=timeout)
  File "/opt/homebrew/lib/python3.9/site-packages/pymilvus/decorators.py", line 96, in handler
    raise e
  File "/opt/homebrew/lib/python3.9/site-packages/pymilvus/decorators.py", line 92, in handler
    return func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/opt/homebrew/lib/python3.9/site-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/pymilvus/client/grpc_handler.py", line 207, in drop_collection
    raise MilvusException(status.error_code, status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=InvalidateCollectionMetaCache failed, proxyID = 74, err = err: failed to connect 10.255.92.62:19529, reason: context deadline exceeded
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:304 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall
/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/client/client.go:135 github.com/milvus-io/milvus/internal/distributed/proxy/client.(*Client).InvalidateCollectionMetaCache
/go/src/github.com/milvus-io/milvus/internal/rootcoord/proxy_client_manager.go:139 github.com/milvus-io/milvus/internal/rootcoord.(*proxyClientManager).InvalidateCollectionMetaCache.func1
/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 golang.org/x/sync/errgroup.(*Group).Go.func1
/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit
)>

**Comment by yanliang567** [comment]
@byeong0 Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the full Milvus server logs for investigation?
/assign @byeong0

**Comment by xiaofan-luan** [comment]
10.255.92.62 seems that the pod is not connectable.
Did you retry and see if it's working?
We will need proxy log for the details by InvalidateCollectionMetaCache failed
