### ISSUE TITLE
[Bug]: I can't search for string fields

### ISSUE THREAD

**Issue by xiao12mm** [milvus-io/milvus#21349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.1
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.1
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 24 cores  128G Memory
- GPU: Nvidia p4
- Others: NO
```

### Current Behavior

create fields
```
fields = [
    FieldSchema(name="uid", dtype=DataType.INT64, is_primary=True, auto_id=True),
    FieldSchema(name="str", dtype=DataType.VARCHAR,max_length=128),
    FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=768)
]
```
search
```
results = collection.search(
	data=[embedding],
	anns_field="embeddings",
	param=search_params,
	limit=100,
	expr=None,
	output_fields = ["uid", "str"],
	consistency_level="Strong",
)
```
I want to search the field "str",

### Expected Behavior

I want to search for field "str", I define output_fields = ["uid", "str"],

But the results are only ids and distance, so how do I search for the "str" field?

**Comment by JackLCL** [comment]
![image](https://user-images.githubusercontent.com/53512883/209104834-9a30fcd9-9711-4f17-95c9-6b5bf4d0becc.png)
You can refer this way in [hello_milvus.py](https://raw.githubusercontent.com/milvus-io/pymilvus/v2.2.1/examples/hello_milvus.py)

**Comment by xiao12mm** [comment]
it is the answer. Thank you
@JackLCL

**Comment by SamSamhuns** [comment]
Shouldn't this information be included in the pymilvus documentation? I was previously using the search API followed with a query API to get the extra fields in the data?

**Comment by xiaofan-luan** [comment]
@SamSamhuns 
Good suggestion.
@JackLCL could you follow up?

**Comment by JackLCL** [comment]
@SamSamhuns 
You can use the method [here](https://github.com/milvus-io/pymilvus/blob/master/examples/hello_milvus.py#L156) to get the string field in output_field.
https://github.com/milvus-io/pymilvus/blob/master/examples/hello_milvus.py#L156

**Comment by SamSamhuns** [comment]
Thanks, I have switched to the `hit.entity.get('field')` already. But it would be helpful if this information is present in the official docs for the `search` API though.

**Comment by AnthonyTsu1984** [comment]
Already add an example of retrieving the value of a specified output field on the `search()` page of the pymilvus API reference.
