### ISSUE TITLE
[Bug]: i can only connect with localhost in milvus cluster but connect timeout with ip

### ISSUE THREAD

**Issue by fangxingjun** [milvus-io/milvus#21378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.1
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.1
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 32cpu 256g
- GPU: no
- Others: no
```

### Current Behavior

<ipython-input-3-3335af0ce4dd> in <module>
      1 from pymilvus import connections
----> 2 connections.connect(
      3   alias="default2",
      4   host='192.168.10.219',
      5   port='19530'

/opt/module/anaconda3/lib/python3.8/site-packages/pymilvus/orm/connections.py in connect(self, alias, user, password, **kwargs)
    301                     raise ConnectionConfigException(message=ExceptionsMessage.ConnDiffConf % alias)
    302
--> 303             connect_milvus(**kwargs, user=user, password=password)
    304
    305         else:

/opt/module/anaconda3/lib/python3.8/site-packages/pymilvus/orm/connections.py in connect_milvus(**kwargs)
    272             timeout = t if isinstance(t, int) else DefaultConfig.DEFAULT_CONNECT_TIMEOUT
    273
--> 274             gh._wait_for_channel_ready(timeout=timeout)
    275             kwargs.pop('password')
    276             kwargs.pop('secure', None)

/opt/module/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py in _wait_for_channel_ready(self, timeout)
    113                 return
    114             except grpc.FutureTimeoutError as e:
--> 115                 raise MilvusException(Status.CONNECT_FAILED,
    116                                       f'Fail connecting to server on {self._address}. Timeout') from e
    117

MilvusException: <MilvusException: (code=2, message=Fail connecting to server on 192.168.10.219:19530. Timeout)>

### Expected Behavior

![image](https://user-images.githubusercontent.com/54159669/209493954-2d57892c-79f1-4d4f-8659-90dcd7916b62.png)

### Steps To Reproduce

```markdown
i hive 3 node: 1 cluster + 2 worker, have installed environment with milvus.
```

**Comment by yanliang567** [comment]
@fangxingjun is the milvus ip load balancer?

**Comment by fangxingjun** [comment]
@yanliang567 hello, I installed the milvus cluster with helm according to the official website. Sorry, I don't know what you mean about milvus ip load balancer.

**Comment by fangxingjun** [comment]
> 

![image](https://user-images.githubusercontent.com/54159669/209516892-7d2fb16d-358e-4c17-9af5-4addb5865dbb.png)
the cluster ip is that, It is the k8s cluster node

**Comment by fangxingjun** [comment]
@LoveEachDay ![image](https://user-images.githubusercontent.com/54159669/209516892-7d2fb16d-358e-4c17-9af5-4addb5865dbb.png)
the cluster ip is that, It is the k8s cluster node

**Comment by LoveEachDay** [comment]
@fangxingjun You can change the milvus svc type from `ClusterIP` to `NodePort` via `kubectl edit svc my-release-milvus`.
Then you run `kubectl get svc` again to check the open ports, then you can access through `192.168.10.219:<port>`.

Note: the port is not `19530` .

**Comment by fangxingjun** [comment]
![image](https://user-images.githubusercontent.com/54159669/209524939-b510eb51-79a7-4ffe-b8f7-0d91e384e5cb.png)
hello, i have changed the svc type with NodePort, the port is 30135? but i still connect timeout

**Comment by yanliang567** [comment]
Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation? @fangxingjun

**Comment by LoveEachDay** [comment]
@fangxingjun Could you run the following command to verify port connectivity: `nc -zv 192.168.10.219 30135` ?

**Comment by fangxingjun** [comment]
![image](https://user-images.githubusercontent.com/54159669/209528463-09c7485b-0142-4f81-875a-991e575ef827.png)
@LoveEachDay 
![image](https://user-images.githubusercontent.com/54159669/209528507-e338cc2d-1405-4e41-8eb3-efa985f64ccb.png)

**Comment by LoveEachDay** [comment]
@fangxingjun Could you verify that you can access to `192.168.10.219`? You can verify by running `ping 192.168.10.219`

**Comment by fangxingjun** [comment]
@LoveEachDay 
![image](https://user-images.githubusercontent.com/54159669/209532353-2dcc4e2d-f3f4-48f6-9b02-4315f2c238be.png)

**Comment by fangxingjun** [comment]
@yanliang567 please check 
[my-release-milvus-attu-5c4d57748c-tvp2j.log](https://github.com/milvus-io/milvus/files/10302982/my-release-milvus-attu-5c4d57748c-tvp2j.log)
[my-release-milvus-datacoord-67875ddfcb-vlvz7.log](https://github.com/milvus-io/milvus/files/10302983/my-release-milvus-datacoord-67875ddfcb-vlvz7.log)
[my-release-milvus-datanode-7bc5c5bd59-5hwsf.log](https://github.com/milvus-io/milvus/files/10302984/my-release-milvus-datanode-7bc5c5bd59-5hwsf.log)
[my-release-milvus-indexcoord-64c6999dc9-hmgnz.log](https://github.com/milvus-io/milvus/files/10302985/my-release-milvus-indexcoord-64c6999dc9-hmgnz.log)
[my-release-milvus-indexnode-7d665fc7cd-pgrx4.log](https://github.com/milvus-io/milvus/files/10302986/my-release-milvus-indexnode-7d665fc7cd-pgrx4.log)
[my-release-milvus-proxy-5d87ddf99c-ktsgh.log](https://github.com/milvus-io/milvus/files/10302987/my-release-milvus-proxy-5d87ddf99c-ktsgh.log)
[my-release-milvus-querycoord-c5fc6bb64-8s8qn.log](https://github.com/milvus-io/milvus/files/10302988/my-release-milvus-querycoord-c5fc6bb64-8s8qn.log)
[my-release-milvus-querycoord-c5fc6bb64-8s8qn-pre.log](https://github.com/milvus-io/milvus/files/10302989/my-release-milvus-querycoord-c5fc6bb64-8s8qn-pre.log)
[my-release-milvus-querynode-77d9f669b8-hltp9.log](https://github.com/milvus-io/milvus/files/10302990/my-release-milvus-querynode-77d9f669b8-hltp9.log)
[my-release-milvus-querynode-77d9f669b8-hltp9-pre.log](https://github.com/milvus-io/milvus/files/10302991/my-release-milvus-querynode-77d9f669b8-hltp9-pre.log)
[my-release-milvus-rootcoord-84f5977bb6-qj2wl.log](https://github.com/milvus-io/milvus/files/10302992/my-release-milvus-rootcoord-84f5977bb6-qj2wl.log)
[my-release-milvus-rootcoord-84f5977bb6-qj2wl-pre.log](https://github.com/milvus-io/milvus/files/10302993/my-release-milvus-rootcoord-84f5977bb6-qj2wl-pre.log)

**Comment by yanliang567** [comment]
looking in the logs, the proxy started successfully. 
But there are some reqeust timeout about etcd sever and rootcoord
```
{"level":"warn","ts":"2022-12-26T04:33:15.093Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0006e8fc0/#initially=[my-release-etcd:2379]","attempt":0,"error":"rpc error: code = Unavailable desc = etcdserver: request timed out"}
...
[2022/12/26 05:39:48.414 +00:00] [WARN] [grpclog/grpclog.go:46] ["[core][Channel #26 SubChannel #27] grpc: addrConn.createTransport failed to connect to {\n  \"Addr\": \"172.18.18.230:53100\",\n  \"ServerName\": \"172.18.18.230:53100\",\n  \"Attributes\": null,\n  \"BalancerAttributes\": null,\n  \"Type\": 0,\n  \"Metadata\": null\n}. Err: connection error: desc = \"transport: Error while dialing dial tcp 172.18.18.230:53100: connect: connection refused\""]

```

**Comment by yanliang567** [comment]
@LoveEachDay could you please help to take a look?

/assign @LoveEachDay

**Comment by LoveEachDay** [comment]
> @LoveEachDay ![image](https://user-images.githubusercontent.com/54159669/209532353-2dcc4e2d-f3f4-48f6-9b02-4315f2c238be.png)

@fangxingjun Could you check if there are any firewall rules which blocks the access of `192.168.10.219:30135` ?

And also could you login the worker node of `192.168.10.219`, and try run the client at this worker node?

**Comment by fangxingjun** [comment]
![image](https://user-images.githubusercontent.com/54159669/209622666-3cd4753e-27ad-422e-9218-090fca32fe02.png)
@LoveEachDay the service of firewalld is not loaded

**Comment by LoveEachDay** [comment]
@fangxingjun So `192.168.10.219` is the ip address of `hadoop10` ?  So could you run `nc -zv 192.168.10.219 30135` at `hadoop10` ?

**Comment by fangxingjun** [comment]
@LoveEachDay timeout ![image](https://user-images.githubusercontent.com/54159669/209624528-2cdfaa87-90ef-412e-ae8c-6e9cb16d64bd.png)
![image](https://user-images.githubusercontent.com/54159669/209624552-84fa1737-0b93-469e-b113-d669c6410715.png)

**Comment by LoveEachDay** [comment]
@fangxingjun From the above output, this doesn't make sense, you cannot access the service from the worker node? Could you check the kube-proxy pod log at the same node? 

You can also run `kubectl get pods -o wide`, identify the milvus-proxy pod and its worker node, then login to this worker node, try check the port connectivity via `nc -zv <milvus-proxy-ip> 19530` .

**Comment by fangxingjun** [comment]
@LoveEachDay @thank u very much， thank your team！i find the reason because of your saying. yeah, the proxy node is hadoop11

**Comment by yanliang567** [comment]
close the issue as comments above.
