### ISSUE TITLE
[Bug]: why the minio index_files is sooooo big

### ISSUE THREAD

**Issue by sulmz** [milvus-io/milvus#21370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.2.0
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 2c 8G
- GPU: 
- Others:
```

### Current Behavior

My milvus just contain 29798 vectors (2048demession from resnet50), but the minio index_files display more than 10G!
How can I thinner it ?
<img width="1532" alt="image" src="https://user-images.githubusercontent.com/61011747/209419006-41c0634b-a29c-4476-a2df-4918965ac45a.png">

I also have changed the gc time, here is my Milvus.yaml
<img width="762" alt="image" src="https://user-images.githubusercontent.com/61011747/209419021-03e0eab1-281f-4afa-9ab3-d4103f7960b6.png">

### Milvus Log

here is my Milvus.yaml
[Milvus.yaml.zip](https://github.com/milvus-io/milvus/files/10297911/Milvus.yaml.zip)

**Comment by xiaofan-luan** [comment]
/assign @sunby 
could you help on investigation?

**Comment by sunby** [comment]
@sulmz Maybe there are some problems for the gc in indexcoord, would you like to provide the indexcoord log to help me find it?

**Comment by sunby** [comment]
@sulmz https://github.com/milvus-io/milvus/pull/21059 this pr has fixed this issue. Please use the version >=v2.2.2 and retry it.

**Comment by sulmz** [comment]
I am fixed for update, thx milvus group!
