### ISSUE TITLE
[Bug]: Memory leak in bruteforce search when invalid metric type was passed

### ISSUE THREAD

**Issue by longjiquan** [milvus-io/milvus#21380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

See bruteforce search in knowhere.

**Comment by longjiquan** [comment]
https://github.com/milvus-io/knowhere/blob/c73b9a03b69333e88dbdddb96f666b6c0af74fd2/knowhere/archive/BruteForce.cpp#L46-#L47

**Comment by longjiquan** [comment]
Maybe metric type check should be in front of allocating memories.

**Comment by cydrain** [comment]
fixed by https://github.com/milvus-io/knowhere/pull/611

**Comment by longjiquan** [comment]
Verified on my local pc. Thx for the quick fix, @cydrain .
