### ISSUE TITLE
[Bug]: Java sdk Pagination bug

### ISSUE THREAD

**Issue by bestRiven** [milvus-io/milvus#21384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): java 2.2.1
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

don't have "limit" and "offset" Parameter. "topk" is Required, so Paging is not available。
`if (topK <= 0) {
                throw new ParamException("TopK value is illegal");
            }`

**Comment by yhmo** [comment]
The question is not clear.
Is search() or query()?

**Comment by JackLCL** [comment]
> The question is not clear. Is search() or query()?

He means search().

**Comment by yelusion2** [comment]
https://milvus.io/api-reference/java/v2.2.1/Query%20and%20Search/search().md
withParams(String params)
The offset for pagination with offset as the key and an integer as the value.
The limit for pagination with limit as the key and an integer as the value.


<br class="Apple-interchange-newline">

**Comment by bestRiven** [comment]
`
public R<SearchResults> search(String collectionName, String vectorName, List<List<Float>> vectors, List<String> outFields, String expr, Integer offset, Integer topK) {
        SearchParam searchParam = SearchParam.newBuilder()
                .withParams(JSONUtil.toJsonStr(SearchParamsDto.builder().nprobe(128).offset(offset).limit(topK).build()))
                .withTopK(topK)
                .withCollectionName(collectionName)
                .withVectorFieldName(vectorName)
                .withVectors(vectors)
                .withMetricType(MetricType.IP)
                .withOutFields(outFields)
                .withExpr(expr)
                .build();
        return milvusServiceClient.withTimeout(20, TimeUnit.SECONDS).search(searchParam);
    }

R<SearchResults> searchResponse = milvusService.search(collectionName, MilvusQuestionUtil.VECTOR_FIELD, newVectors, MilvusQuestionUtil.getOutFields(), "question_type == 14", 10, 10);
`

**Comment by yhmo** [comment]
Already fixed and release a new version for JAVA sdk: https://github.com/milvus-io/milvus-sdk-java/releases/tag/v2.2.2
