### ISSUE TITLE
[Bug]: Deleted entities are not able to be physically deleted even triggered by manually compact 

### ISSUE THREAD

**Issue by shieldlin** [milvus-io/milvus#21399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.1
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2): milvus java sdk 2.2.1
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

We have a collection with normally 298w entities. Every 15min, we will update new data into this collection with old entities deleted and new entities inserted.

We normally did manually compaction everyday. And the total number of entities was kept around 300w.  However, after several days without manually compaction.  The total number of entities will not get down even if we do manually compact.

So the behavior was like:
Before compaction, there are 400w entities. After manually compact , there are still 400w entites.

### Expected Behavior

Befor compact, there are 400w enitities. After manually compact, there should be 298w entities left.

### Milvus Log

[log.tar.gz](https://github.com/milvus-io/milvus/files/10306787/log.tar.gz)

**Comment by yanliang567** [comment]
@shieldlin num_entities is not precise in current design, we are trying to develop a new API to get a precise entities  now. But it is weird about the different behavior of manual compaction and auto-compaction.
What's more, have you try TTL（Time to live), a new feature of 2.2.0, which i think could be helpful for you. check here for details: https://milvus.io/docs/release_notes.md

@XuanYang-cn could you please take a look at this issue?

**Comment by xiaofan-luan** [comment]
after some offline discussion, it seems that manual compaction is not working after a few days(It used to work when trigger everyday).
My guess is that compaction stucked due to some reason..

**Comment by JackLCL** [comment]
[bw_etcd_ALL.221227-173600.bak.gz](https://github.com/milvus-io/milvus/files/10307304/bw_etcd_ALL.221227-173600.bak.gz)

**Comment by JackLCL** [comment]
[bw_etcd_ALL.221227-173600.bak.gz](https://github.com/milvus-io/milvus/files/10307688/bw_etcd_ALL.221227-173600.bak.gz)

**Comment by xiaocai2333** [comment]
1. The checkpoint of VChannel will point to the position of the entity message, not only tt msg.
2. Seek `inclusive` is false of msgStream, it will drop the first msg. (TtMsgStream `inclusive` is true)
3. So if the VChannel checkpoint is point the delete msg, it will lost the delete msg when loading.

pr #21478 will fix it.

**Comment by yanliang567** [comment]
@xiaocai2333 any ideas about how to reproduce it in house?
/assign @binbinlv  please take a look at this in case we can cover it in ci

**Comment by xiaocai2333** [comment]
> @xiaocai2333 any ideas about how to reproduce it in house? /assign @binbinlv please take a look at this in case we can cover it in ci

yes, it can reproduce, but it's occasional.
this is my test code:
```
if __name__ == "__main__":
    # print(milvus.has_collection(coll_name))
    connections.connect(user=username, password=password, host="localhost", port=19530, Secure=True)
    # connections.connect(host="localhost", port=19530)
    # utility.create_credential(user=username, password=password)
    # print(utility.list_cred_users())

    coll = create_collections()

    # print("drop collection...")
    # coll.drop()
    # print("drop collection done!")
    #
    # coll = create_collections()
    #
    print("insert...")
    insert2(coll, "")
    print("insert done...")

    num_entities(coll)
    create_index(coll)
    delete(coll)
    num_entities(coll)
    print("compact...")
    coll.compact()
    print("compact done!")

    load(coll)
    query(coll)
    release(coll)

    time.sleep(30)
    load(coll)
    query(coll)
    release(coll)

    time.sleep(40)
    load(coll)
    query(coll)
    release(coll)

    time.sleep(60)
    load(coll)
    query(coll)
    release(coll)
```

Generally, the last Query can find the deleted data.

**Comment by xiaocai2333** [comment]
By the way, I attach the print results when it reproduced.
```
insert...
insert num_rows:  50000
insert done...
num entities...
50000
num entities done!

create index...
create index done!
delete all...
delete done!
num entities...
50000
num entities done!

compact...
compact done!
load collection...
load collection done!
load collection cost:  4.041240692138672

query...
query result...
0
query done!
release collection...
release collection done!

load collection...
load collection done!
load collection cost:  4.051191568374634

query...
query result...
0
query done!
release collection...
release collection done!

load collection...
load collection done!
load collection cost:  4.050070285797119

query...
query result...
50000
query done!
release collection...
release collection done!

load collection...
load collection done!
load collection cost:  4.057743072509766

query...
query result...
50000
query done!
release collection...
release collection done!
```

**Comment by xiaofan-luan** [comment]
@NicoYuan1986 
can we close the issue?

**Comment by NicoYuan1986** [comment]
> @NicoYuan1986 can we close the issue?

I didn't reproduce the issue locally. I think it's fixed. I'll close the issue if it's fine with nightly test result too.

**Comment by NicoYuan1986** [comment]
fixed.
