### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'pymilvus'

### ISSUE THREAD

**Issue by mahajpuneet** [milvus-io/milvus#21392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.0
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): docker   
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.0
- OS(Ubuntu or CentOS): Mac OS x64
- CPU/Memory: 16 GB
- GPU: None
- Others:
```

### Current Behavior

Tried installing pymilvus as per the docs, and also got grpcio ==1.47.2 and grpcio-tools==1.47.2 installed. Then got milvus and pymilvus installed. milvus==2.1.0 and pymilvus==2.1.0.

Can you pls help me, can't get python3 -c "from pymilvus import Collection" to work for me.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pymilvus'

### Expected Behavior

When I call the last command, pymilvus should be loaded into the command line for python env

### Steps To Reproduce

```markdown
As described in the "current behavior" area
```

**Comment by yanliang567** [comment]
@mahajpuneet how do you install pymilvus? it seems that you installed python and pymilvus in a different virtual env?
/assign @mahajpuneet

**Comment by mahajpuneet** [comment]
@yanliang567 : simply did a pip install for the same. Some logs for further context:
(base) BLRL-300075517:milvus 300075517$ which env
/usr/bin/env
(base) BLRL-300075517:milvus 300075517$ which env pymilvus
/usr/bin/env

**Comment by yanliang567** [comment]
Mmm...what about trying to install pymilvus via pip3?

**Comment by mahajpuneet** [comment]
ok tried that,logs below:

(base) BLRL-300075517:milvus 300075517$ pip3 install pymilvus
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Collecting pymilvus
  Using cached pymilvus-2.2.1-py3-none-any.whl (122 kB)
Requirement already satisfied: ujson<=5.4.0,>=2.0.0 in /opt/homebrew/lib/python3.9/site-packages (from pymilvus) (5.4.0)
Requirement already satisfied: grpcio-tools<=1.48.0,>=1.47.0 in /opt/homebrew/lib/python3.9/site-packages (from pymilvus) (1.47.2)
Requirement already satisfied: mmh3<=3.0.0,>=2.0 in /opt/homebrew/lib/python3.9/site-packages (from pymilvus) (3.0.0)
Requirement already satisfied: grpcio<=1.48.0,>=1.47.0 in /opt/homebrew/lib/python3.9/site-packages (from pymilvus) (1.47.2)
Requirement already satisfied: pandas>=1.2.4 in /opt/homebrew/lib/python3.9/site-packages (from pymilvus) (1.4.1)
Requirement already satisfied: six>=1.5.2 in /opt/homebrew/lib/python3.9/site-packages (from grpcio<=1.48.0,>=1.47.0->pymilvus) (1.16.0)
Requirement already satisfied: setuptools in /opt/homebrew/lib/python3.9/site-packages (from grpcio-tools<=1.48.0,>=1.47.0->pymilvus) (65.4.1)
Requirement already satisfied: protobuf<4.0dev,>=3.12.0 in /opt/homebrew/lib/python3.9/site-packages (from grpcio-tools<=1.48.0,>=1.47.0->pymilvus) (3.20.3)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/lib/python3.9/site-packages (from pandas>=1.2.4->pymilvus) (2021.3)
Requirement already satisfied: numpy>=1.20.0 in /opt/homebrew/lib/python3.9/site-packages (from pandas>=1.2.4->pymilvus) (1.22.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /opt/homebrew/lib/python3.9/site-packages (from pandas>=1.2.4->pymilvus) (2.8.2)
Installing collected packages: pymilvus
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Successfully installed pymilvus-2.2.1
(base) BLRL-300075517:milvus 300075517$ python -c "from pymilvus import Collection"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pymilvus'
(base) BLRL-300075517:milvus 300075517$

**Comment by yanliang567** [comment]
what about python3 -c "from pymilvus import Collection"
(base) BLRL-300075517:milvus 300075517$ python -c "from pymilvus import Collection"
Traceback (most recent call last):

**Comment by mahajpuneet** [comment]
Same, sigh:
(base) BLRL-300075517:milvus 300075517$ python3 -c "from pymilvus import Collection"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pymilvus'

**Comment by mahajpuneet** [comment]
working now, but in jupyter notebooks. @yanliang567 . I will close the ticket, maybe the jupyter/conda python sees the package but facing issues in terminal

**Comment by yanliang567** [comment]
great to hear that. But we can run pymilvus in jupyter and terminal as well.
