### ISSUE TITLE
[Enhancement]: Support recovering mode to skip all data in message queue

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#21393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

We hit a lot of situation where cluster can not recover because of data in MQ is not recovered(Might be due to old checkpoint, corrupted data....)

In certain cases we want to recover the cluster ASAP even it's ok to lose data, thus we can have a config or command to skip streaming data and recover the cluster.

We will name this recovery mode and user may take risk of loosing data in recovery mode. Data in message queue can be replayed by birdwatcher to keep data integrity

### Why is this needed?

Recover the data ASAP

**Comment by jaime0815** [comment]
https://github.com/milvus-io/birdwatcher/pull/66  currently we can use Birdwather to reset checkpoint to the latest msgID of the topic or the latest checkpoint of pchannel of the collection

**Comment by xiaofan-luan** [comment]
> [milvus-io/birdwatcher#66](https://github.com/milvus-io/birdwatcher/pull/66) currently we can use Birdwather to reset checkpoint to the latest msgID of the topic or the latest checkpoint of pchannel of the collection

Just let a user to try if it is working, related https://github.com/milvus-io/milvus/issues/21391

**Comment by xiaofan-luan** [comment]
keep it
