### ISSUE TITLE
[Bug]: datanode restart fail

### ISSUE THREAD

**Issue by wziyang** [milvus-io/milvus#21391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.0
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2):2.1.0
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 32G/128G
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/38698650/209550632-aa8594cb-4beb-440a-a2ae-28318bb17005.png)
datanode restart fail，it log: data service save bin log path failed to get segment xxxxxxxxxxxxxxxxxxxx

### Milvus Log

[Uploading milvus_log.zip…]()

**Comment by wziyang** [comment]
![image](https://user-images.githubusercontent.com/38698650/209551135-b531c0a7-25f0-42f3-97c3-38412ea0173c.png)

**Comment by wziyang** [comment]
[milvus_log.zip](https://github.com/milvus-io/milvus/files/10303564/milvus_log.zip)
Supplement log

**Comment by xiaofan-luan** [comment]
from the log, this is a dropped segment so datacoord can not find any segment related.
This might be the old checkpoint issue.
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/83447078/209559325-149098b8-4d85-473d-a0a7-f3345fe50bef.png">

**Comment by xiaofan-luan** [comment]
Since these are dropped collection, one possible way is to simply clean all the data in channel by-dev-rootcoord-dml_17_437098920113602561v15

**Comment by xiaofan-luan** [comment]
can you install birdwatcher(https://github.com/milvus-io/birdwatcher/) and try command 
reset-checkpoint --collection 437098920113602561 --vchannel by-dev-rootcoord-dml_17_437098920113602561v15 --mq_type pulsar --address pulsar://localhost:6650 --set_to latest-msgid
it will help you to reset the checkpoint of the dropped collection

**Comment by yanliang567** [comment]
@wziyang could you please provide more info as described above?
/assign @wziyang

**Comment by wziyang** [comment]
Which version of birdWatcher is used? I build the main branch without reset-checkpoint.
![image](https://user-images.githubusercontent.com/38698650/209599438-a27a3cb9-1009-4e0f-b9d6-53db2f8ed439.png)
@xiaofan-luan

**Comment by congqixia** [comment]
@wziyang in latest `birdwatcher` the `repair-checkpoint` command is renamed to `repair checkpoint`
Also you need to connect to your etcd to execute this command
```
// connect to etcd, replace your ip and port here
connect --etcd [etcd-ip]:[etcd-port]
// repair checkpoint, replace your pulsar ip here
repair checkpoint --collection 437098920113602561 --vchannel by-dev-rootcoord-dml_17_437098920113602561v15 --mq_type pulsar --address pulsar://[pulsar-ip]:6650 --set_to latest-msgid
```

**Comment by yanliang567** [comment]
@wziyang any updates? does it reproduce to you on the latest release v2.2.2?

**Comment by yhmo** [comment]
link to #21527
