### ISSUE TITLE
[Bug]: querycoord exit with interrupt signal after upgrade to 2.2.2 from 2.1.4

### ISSUE THREAD

**Issue by BUPTAnderson** [milvus-io/milvus#21408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.2
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-2.1.3
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 40Core/192GB
- GPU: 
- Others:
```

### Current Behavior

When upgrade milvus from 2.1.4 to 2.2.2, we  can query normally. But after above 4 hours, the querycoord exit with  interrupt signal.

### Expected Behavior

querycoord  is working properly

### Steps To Reproduce

```markdown
upgrade from 2.1.4 to 2.2.2
```

### Milvus Log

[querycoord-25.log](https://github.com/milvus-io/milvus/files/10311657/querycoord-25.log)

### Anything else?

etcd log:
```
Dec 27 16:14:25 hadoop2765.rz.momo.com etcd[95232]: {"level":"warn","ts":"2022-12-27T16:14:25.197+0800","caller":"etcdserver/util.go:123","msg":"failed to apply request","took":"48.687µs","request":"header:<ID:1041602038151722662 > lease_revoke:<id:0e748388f95aae5b>","response":"size:30","error":"lease not found"}
Dec 27 16:14:25 hadoop2765.rz.momo.com etcd[95232]: {"level":"warn","ts":"2022-12-27T16:14:25.199+0800","caller":"etcdserver/util.go:123","msg":"failed to apply request","took":"15.778µs","request":"header:<ID:16215918032585729299 > lease_revoke:<id:0e748388f95aae5b>","response":"size:30","error":"lease not found"}
```

**Comment by BUPTAnderson** [comment]
After querycoord exit, we restart querycoord service, but querycoord crash after 30mins.
No Error messages are output for this querycoord restart operation.
[querycoord-36.log](https://github.com/milvus-io/milvus/files/10311730/querycoord-36.log)

**Comment by BUPTAnderson** [comment]
etcd log file:
[etcd.log](https://github.com/milvus-io/milvus/files/10311834/etcd.log)

**Comment by xiaofan-luan** [comment]
@BUPTAnderson
Querycoord25 crashed because of "QueryCoord disconnected from etcd, process will exit"
querycoord36 crashed at what time? The log looks weird, the last log is 19:42, but before that there are almost 10 minutes gap and we didn't see any logs.
Does it recover for now if we bring up new querycoord?

**Comment by xiaofan-luan** [comment]
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/83447078/209761654-1d53bc31-12e5-4131-a484-9e7ae71daa7a.png">
for querycoord-25 the log is also weird.
it moved directly from [2022/12/27 12:23:04.031 +08:00]  to [2022/12/27 16:14:25.192 +08:00] [WARN]

**Comment by LoveEachDay** [comment]
> After querycoord exit, we restart querycoord service, but querycoord crash after 30mins. No Error messages are output for this querycoord restart operation. [querycoord-36.log](https://github.com/milvus-io/milvus/files/10311730/querycoord-36.log)

Could you run `kubectl describe <query-coord-pod>` to inspect the restart reason?

**Comment by BUPTAnderson** [comment]
> > After querycoord exit, we restart querycoord service, but querycoord crash after 30mins. No Error messages are output for this querycoord restart operation. [querycoord-36.log](https://github.com/milvus-io/milvus/files/10311730/querycoord-36.log)
> 
> Could you run `kubectl describe <query-coord-pod>` to inspect the restart reason?

@LoveEachDay Sorry, the above problem was generated by my deployment in a physical machine environment, not k8s env.

**Comment by BUPTAnderson** [comment]
@LoveEachDay The following file are the logs of other nodes.
[logs.tar.gz](https://github.com/milvus-io/milvus/files/10317238/logs.tar.gz)

**Comment by LoveEachDay** [comment]
@BUPTAnderson There aren't any `querycoord` logs in the above attachment.

**Comment by BUPTAnderson** [comment]
@LoveEachDay 
[querycoord-25.log](https://github.com/milvus-io/milvus/files/10311657/querycoord-25.log)
[etcd.log](https://github.com/milvus-io/milvus/files/10311834/etcd.log)
[querycoord-36.log](https://github.com/milvus-io/milvus/files/10311730/querycoord-36.log)

**Comment by LoveEachDay** [comment]
@BUPTAnderson I have checked those 3 files, and we can see querycoord-25 restarted because etcd session expired. But in querycoord-36, there is no clue about the process crash.
Are there more querycoord logs?

**Comment by BUPTAnderson** [comment]
> @BUPTAnderson I have checked those 3 files, and we can see querycoord-25 restarted because etcd session expired. But in querycoord-36, there is no clue about the process crash. Are there more querycoord logs?

Yes，it show that etcd session expired. What I'm confused about is why the etcd session expired, only milvus cluster use the  etcd server and etcd db size is only 12 MB. How can I prevent this from happening again?

**Comment by LoveEachDay** [comment]
@BUPTAnderson By default, querycoord will register itself into etcd, put a session key with lease (ttl: 60s). And querycoord will keepalive, so that etcd will renew the lease. We suspect that querycoord may be hanging (lack of evidence), which cannot renew the lease. So the key will be removed in etcd and querycoord will exit. 

> > @BUPTAnderson I have checked those 3 files, and we can see querycoord-25 restarted because etcd session expired. But in querycoord-36, there is no clue about the process crash. Are there more querycoord logs?
> 
> Yes，it show that etcd session expired. What I'm confused about is why the etcd session expired, only milvus cluster use the etcd server and etcd db size is only 12 MB. How can I prevent this from happening again?

**Comment by BUPTAnderson** [comment]
> @BUPTAnderson By default, querycoord will register itself into etcd, put a session key with lease (ttl: 60s). And querycoord will keepalive, so that etcd will renew the lease. We suspect that querycoord may be hanging (lack of evidence), which cannot renew the lease. So the key will be removed in etcd and querycoord will exit.
> 
> > > @BUPTAnderson I have checked those 3 files, and we can see querycoord-25 restarted because etcd session expired. But in querycoord-36, there is no clue about the process crash. Are there more querycoord logs?
> > 
> > 
> > Yes，it show that etcd session expired. What I'm confused about is why the etcd session expired, only milvus cluster use the etcd server and etcd db size is only 12 MB. How can I prevent this from happening again?


@LoveEachDay 
Should we add some retry mechanism in these places？

**Comment by LoveEachDay** [comment]
@BUPTAnderson Milvus is designed for cloud-native and target to run in a kubernetes cluster. We rely on the kubelet to automatically restart the milvus process. It's by design to fail fast instead of meaningless retry.

**Comment by xiaofan-luan** [comment]
> 

We should add some retry on etcd client configs.
However if it is session expired it means etcd it is not working for more than 1 minutes.

From the etcd log, there missed a huge amount of time. Did you know what happened at that time? @BUPTAnderson 
![image](https://user-images.githubusercontent.com/83447078/210164523-9ad92bc0-7d99-46f4-a93b-55680ffa04b0.png)

**Comment by jaime0815** [comment]
It seems your Etcd cluster is unhealthy, is it an external Etcd cluster? if so, please provide your Etcd version.

**Comment by BUPTAnderson** [comment]
> It seems your Etcd cluster is unhealthy, is it an external Etcd cluster? if so, please provide your Etcd version.

yes, we use a external Etcd cluster with version-3.5.4

**Comment by BUPTAnderson** [comment]
> > 
> 
> We should add some retry on etcd client configs. However if it is session expired it means etcd it is not working for more than 1 minutes.
> 
> From the etcd log, there missed a huge amount of time. Did you know what happened at that time? @BUPTAnderson ![image](https://user-images.githubusercontent.com/83447078/210164523-9ad92bc0-7d99-46f4-a93b-55680ffa04b0.png)

Because i deploy etcd with systemd. I grep etcd log from `/var/log/messages`, The following is whole log of etcd.
[etcd.log](https://github.com/milvus-io/milvus/files/10328789/etcd.log)
