### ISSUE TITLE
Server start failed if using existed data path

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#2141]
**Describe the bug**
`docker logs`: 
```
Cannot create wal dir
Milvus server exit...
```

**Steps/Code to reproduce behavior**
In nightly benchmark regression.
start server with -v `db_path:$PATH` -v `wal_path:$PATH` , in witch `$PATH=NAS_DIR`

**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by BossZou** [comment]
Yes, I think this issue is the same as #2133
