### ISSUE TITLE
[Bug]: helm cluster setting authorization fail

### ISSUE THREAD

**Issue by wziyang** [milvus-io/milvus#21413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.2
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.1
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 32/128
- GPU: 
- Others:
```

### Current Behavior

I modified the authorization configuration but did not take effect：
![0277b7aae4fd75acb8d839eb1d03b7f](https://user-images.githubusercontent.com/38698650/209769694-22f08b7f-48c0-48f9-b285-6e14bb202142.png)

The document is displayed like this：
![image](https://user-images.githubusercontent.com/38698650/209769778-ac79b736-71ad-41f5-a17e-461c4f88f4ad.png)

But I didn't find this configuration in Chart（https://artifacthub.io/packages/helm/milvus/milvus/4.0.2）
I can find it in the old Chart version （https://artifacthub.io/packages/helm/milvus/milvus/3.3.6）

### Expected Behavior

authorization  setting success

**Comment by LoveEachDay** [comment]
@wziyang Since milvus helm chart version v4.0.0, we have refined the milvus config options. You can enable the authorization using the following configs:
```
extraConfigFiles:
  user.yaml: |+
    common:
       security:
          authorizationEnabled: true
```

Our documentation is based on milvus-helm chart 3.*, and we'll refined the above shortly.

**Comment by wziyang** [comment]
Configuration is successful, thank you
