### ISSUE TITLE
[Enhancement]: Integration test framework

### ISSUE THREAD

**Issue by wayblink** [milvus-io/milvus#21418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Introduce integration test framework to Milvus. Support setup a mini cluster in one process locally and do E2E operations on it. Aims to test the overall behavior of Milvus cluster.

**Comment by xiaofan-luan** [comment]
keep it open

**Comment by wayblink** [comment]
Todo test lists

Data :
balance dml channels
handle datanode crashes
insert + delete + flush + compaction and test the correctness of data
bulkLoad E2E

Index:
indexnode crash while index is building
indexcoord crash while index is building
test Index load balance while multiple index node

Query:
Segment loadbalancing with multiple querynode
Shard load balancing
LB with multiple replicas.
Load balance triggered by user
Shard Leader recovery with growing segments
Segment recovery with sealed segments.
Flush/Compaction triggered handoff

Others:
Backup
Graceful stop
Coordinator standy
More DDL test ....

while implement the list the other thing to do is improve util functions, such as get segment distribution, get shard distribution, verify data count, verify delete count............

**Comment by xiaofan-luan** [comment]
keep it
