### ISSUE TITLE
[Bug]: Milvus stopped working. (v 2.1.4 or 2.2.2)

### ISSUE THREAD

**Issue by tagilchanin** [milvus-io/milvus#21423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.4 or 2.2.2
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): - 
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory:  88 CPU / 512 Gb Ram
- GPU: -
- Others:
```

### Current Behavior

Milvus stopped working. 
When connecting to port 19530: The connection was reset
When connecting to port 9091: 404 page not found

### Steps To Reproduce

```markdown
1. wget https://github.com/milvus-io/milvus/releases/download/v2.2.2/milvus-standalone-docker-compose.yml -O docker-compose.yml
2. docker-compose up -d
3. docker-compose ps (all container worked)
4. Log in using a browser on port 19530 or 9091
```

### Milvus Log

Log Standalone:
milvus-standalone | [2022/12/28 10:37:21.534 +00:00] [ERROR] [grpcclient/client.go:260] ["ClientBase ReCall grpc second call get error"] [role=querycoord] [error="err: find no available querycoord, check querycoord state\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:259 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/client/client.go:118 github.com/milvus-io/milvus/internal/distributed/querycoord/client.(*Client).GetComponentStates\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:65 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1\n/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:37 github.com/milvus-io/milvus/internal/util/retry.Do\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:89 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:104 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentHealthy\n/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:461 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).init\n/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:288 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Run\n/go/src/github.com/milvus-io/milvus/cmd/components/proxy.go:50 github.com/milvus-io/milvus/cmd/components.(*Proxy).Run\n"] [stack="github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:260\ngithub.com/milvus-io/milvus/internal/distributed/querycoord/client.(*Client).GetComponentStates\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/client/client.go:118\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:65\ngithub.com/milvus-io/milvus/internal/util/retry.Do\n\t/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:37\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:89\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentHealthy\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:104\ngithub.com/milvus-io/milvus/internal/distributed/proxy.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:461\ngithub.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:288\ngithub.com/milvus-io/milvus/cmd/components.(*Proxy).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/proxy.go:50\ngithub.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runProxy.func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:155"]
milvus-standalone | [2022/12/28 10:37:21.534 +00:00] [DEBUG] [retry/retry.go:39] ["retry func failed"] ["retry time"=0] [error="err: find no available querycoord, check querycoord state\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:259 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/client/client.go:118 github.com/milvus-io/milvus/internal/distributed/querycoord/client.(*Client).GetComponentStates\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:65 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1\n/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:37 github.com/milvus-io/milvus/internal/util/retry.Do\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:89 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:104 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentHealthy\n/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:461 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).init\n/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:288 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Run\n/go/src/github.com/milvus-io/milvus/cmd/components/proxy.go:50 github.com/milvus-io/milvus/cmd/components.(*Proxy).Run\n"]

**Comment by yanliang567** [comment]
@tagilchanin could you please try to connect the milvus via pymilvus? Here is an example: https://milvus.io/docs/example_code.md
if you want to use a browser, you need to install Attu as well. https://github.com/zilliztech/attu

/assign @tagilchanin 
/unassign

**Comment by xiaofan-luan** [comment]
seems the cluster is not start up as expected. 
querycoord is not working, could you offer the log of querycoord we can check why

**Comment by tagilchanin** [comment]
Very strange behaviour. Using attu I was able to connect to milvus. With the help of a browser and a java client, there is no connection.

Tell me how to send querycoord logs.


```
docker-compose ps
      Name                     Command               State                              Ports
-------------------------------------------------------------------------------------------------------------------------
milvus-etcd         etcd -advertise-client-url ...   Up      2379/tcp, 2380/tcp
milvus-minio        /usr/bin/docker-entrypoint ...   Up      9000/tcp
milvus-standalone   /tini -- milvus run standalone   Up      10.168.202.56:19530->19530/tcp, 10.168.202.56:9091->9091/tcp

```

**Comment by yanliang567** [comment]
in case you did not run port-forward:
`kubectl port-forward service/milvus-standalone 19530`

**Comment by tagilchanin** [comment]
I don't use kubectl, I have docker-compose

**Comment by xiaofan-luan** [comment]
> I don't use kubectl, I have docker-compose

could you collect  logs? we need detailed logs to investigate on it. Seems Querycoord is not working as expected

**Comment by tagilchanin** [comment]
[
[milvus.log](https://github.com/milvus-io/milvus/files/10323224/milvus.log)
Log milvus

**Comment by xiaofan-luan** [comment]
> [ [milvus.log](https://github.com/milvus-io/milvus/files/10323224/milvus.log) Log milvus

Let me check~

**Comment by xiaofan-luan** [comment]
From the message I saw:
[rootcoord/meta_table.go:980] ["get init buildIDs, index not found"] ["collection name"=hello_milvus] ["index name"=_default_idx]
Is this a cluster upgrade from 2.1.4 to 2.2.2?
If so I'm afraid you didn't run the upgrade script 
https://milvus.io/docs/upgrade_milvus_standalone-docker.md#Upgrade-Milvus-Standalone-with-Docker-Compose

**Comment by xiaofan-luan** [comment]
I should be ok if you drop index hello_milvus and recreate one index.
Could you try it?

**Comment by xiaofan-luan** [comment]
It's probably because on 2.2 we change the meta format(Especially the index) and require to run the migrate tool 
docker run --rm -it --network milvus -v $(pwd)/migration.yaml:/milvus/configs/migration.yaml milvusdb/meta-migration:v2.2.0 /milvus/bin/meta-migration -config=/milvus/configs/migration.yaml

**Comment by ronald-das** [comment]
> It's probably because on 2.2 we change the meta format(Especially the index) and require to run the migrate tool docker run --rm -it --network milvus -v $(pwd)/migration.yaml:/milvus/configs/migration.yaml milvusdb/meta-migration:v2.2.0 /milvus/bin/meta-migration -config=/milvus/configs/migration.yaml

Hi, I am trying ot run the migration script, but it fails while connecting to the etcd 
logs
```
sudo docker run --rm -it --network milvus -v $(pwd)/migration.yaml:/milvus/configs/migration.yaml milvusdb/meta-migration:v2.2.0 /milvus/bin/meta-migration -config=/milvus/configs/migration.yaml
Cmd: run, SourceVersion: 2.1.4, TargetVersion: 2.2.0, BackupFilePath: /tmp/migration.bak, RunWithBackup: true
Type: etcd, EndPoints: [milvus-etcd], MetaRootPath: /home/azureuser/volumes/etcd/meta
[2023/01/10 06:24:06.363 +00:00] [DEBUG] [sessionutil/session_util.go:185] ["Session try to connect to etcd"]
{"level":"warn","ts":"2023-01-10T06:24:11.363Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00035d500/#initially=[milvus-etcd]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp: address milvus-etcd: missing port in address\""}
[2023/01/10 06:24:11.363 +00:00] [DEBUG] [retry/retry.go:39] ["retry func failed"] ["retry time"=0] [error="context deadline exceeded"]
[2023/01/10 06:24:11.564 +00:00] [DEBUG] [sessionutil/session_util.go:185] ["Session try to connect to etcd"]
{"level":"warn","ts":"2023-01-10T06:24:16.565Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00035d500/#initially=[milvus-etcd]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp: address milvus-etcd: missing port in address\""}
[2023/01/10 06:24:16.966 +00:00] [DEBUG] [sessionutil/session_util.go:185] ["Session try to connect to etcd"]
{"level":"warn","ts":"2023-01-10T06:24:21.966Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00035d500/#initially=[milvus-etcd]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp: address milvus-etcd: missing port in address\""}
[2023/01/10 06:24:22.767 +00:00] [DEBUG] [sessionutil/session_util.go:185] ["Session try to connect to etcd"]

```
