### ISSUE TITLE
[Bug]: 40Milliion 512Dim Vector IVF-FLAT Search latency is over 100ms

### ISSUE THREAD

**Issue by changhong52** [milvus-io/milvus#21437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.2.0
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

使用5000W数据的资源配置压测 4000W数据IVF-FLAT压测时间超过100ms
![milvus资源配置](https://user-images.githubusercontent.com/121591595/209899058-2dd9e162-f97f-4ff6-9831-03e23c7d4de4.jpeg)
![20221229-113557](https://user-images.githubusercontent.com/121591595/209900085-bd65a029-6442-4226-921f-bf2d51dc6748.jpeg)

### Expected Behavior

期望4000W压测结果在qps:30的基础上 RT99小于100ms

**Comment by yanliang567** [comment]
looking into the logs, most search requests are done in 90ms, and become to 100+ms as concurrent searchers increased. Checking the querynode logs, all the segments were loaded index, so I think the search latency here is expected. If you want to get a better latency, please try
1.  change a new index, such as hnsw, or ivf_sq, if recall is not that sensitive for you
2. decrease the concurrent searcher
3. add more cpus 

/assign @changhong52 
/unassign

**Comment by yanliang567** [comment]
close for now
