### ISSUE TITLE
[Bug]: Proxys still request old querynodes wihtout updating local meta cache when querynodes were evicted by k8s

### ISSUE THREAD

**Issue by psc0606** [milvus-io/milvus#21439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.2
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.2.1, java-sdk-2.2.1
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: proxy(5 pods, 8c8G), all coord(root, data, index) (1pod, 8c8G), datanode(5 pods, 8c8G), indexnode(5 pods, 8c8G), querynode(20pods, 8c8G)
- GPU: None
- Others: None
```

### Current Behavior

other info: 
- collectionName: xxx
- replica: 2

One of querynode(part of xxx was load in the memory) was evicted by k8s, then its pod ip was changed.
But proxys node still attempt to dial the non-existing pod ip which failed all related requests.

Finally, milvus became normal when all proxys were restarted.

So I can see lots of logs like this:
```
"[2022/12/28 23:59:44.326 +00:00] [WARN] [grpclog/grpclog.go:46] [\"[core][Channel #15964 SubChannel #15965] grpc: addrConn.createTransport failed to connect to {\\n \\\"Addr\\\": \\\"10.75.184.218:21123\\\",\\n \\\"ServerName\\\": \\\"10.75.184.218:21123\\\",\\n \\\"Attributes\\\": null,\\n \\\"BalancerAttributes\\\": null,\\n \\\"Type\\\": 0,\\n \\\"Metadata\\\": null\\n}. Err: connection error: desc = \\\"transport: Error while dialing dial tcp 10.75.184.218:21123: operation was canceled\\\"\"]\n"
```

### Steps To Reproduce

```markdown
1. Evict querynode by k8s(part of collection segment is on that querynode)
2. search that collection
3. lots of requests timeout(500ms)
```

### Milvus Log
[querynode_Explore-logs-2022-12-29 14_44_15.txt](https://github.com/milvus-io/milvus/files/10317998/querynode_Explore-logs-2022-12-29.14_44_15.txt)
[querycoord_Explore-logs-2022-12-29 14_42_52.txt](https://github.com/milvus-io/milvus/files/10318002/querycoord_Explore-logs-2022-12-29.14_42_52.txt)
[proxy-Explore-logs-2022-12-29 14_40_44.txt](https://github.com/milvus-io/milvus/files/10318003/proxy-Explore-logs-2022-12-29.14_40_44.txt)

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```gfm
> - Milvus version: 2.2.2
> - Deployment mode(standalone or cluster): cluster
> - SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.2.1, java-sdk-2.2.1
> - OS(Ubuntu or CentOS): CentOS
> - CPU/Memory: proxy(5 pods, 8c8G), all coord(root, data, index) (1pod, 8c8G), datanode(5 pods, 8c8G), indexnode(5 pods, 8c8G), querynode(20pods, 8c8G)
> - GPU: None
> - Others: None
> ```
> 
> ### Current Behavior
> other info:
> 
> * collectionName: xxx
> * replica: 2
> 
> One of querynode(part of xxx was load in the memory) was evicted by k8s, then its pod ip was changed. But proxys node still attempt to dial the non-existing pod ip which failed all related requests.
> 
> Finally, milvus became normal when all proxys were restarted.
> 
> So I can see lots of logs like this:
> 
> ```
> "[2022/12/28 23:59:44.326 +00:00] [WARN] [grpclog/grpclog.go:46] [\"[core][Channel #15964 SubChannel #15965] grpc: addrConn.createTransport failed to connect to {\\n \\\"Addr\\\": \\\"10.75.184.218:21123\\\",\\n \\\"ServerName\\\": \\\"10.75.184.218:21123\\\",\\n \\\"Attributes\\\": null,\\n \\\"BalancerAttributes\\\": null,\\n \\\"Type\\\": 0,\\n \\\"Metadata\\\": null\\n}. Err: connection error: desc = \\\"transport: Error while dialing dial tcp 10.75.184.218:21123: operation was canceled\\\"\"]\n"
> ```
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> ```gfm
> 1. Evict querynode by k8s(part of collection segment is on that querynode)
> 2. search that collection
> 3. lots of requests timeout(500ms)
> ```
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

On 2.2.2 this should already be solved. It probably need 1-2 minutes to find the crash of the old node, did it recover later or won't help?

**Comment by xiaofan-luan** [comment]
offers proxy log and querynode/querycoord.log would be super helpful

**Comment by psc0606** [comment]
Not recovery at all. At last, we had all proxys restarted( After 8 hours).

**Comment by psc0606** [comment]
updated: add milvus log

**Comment by congqixia** [comment]
The update cache operation is executed by failed:
```
[2022/12/28 18:48:29.563 +00:00] [WARN] [proxy/task_search.go:409]["first search failed, updating shardleader caches and retry search"] [traceID=5e93f13a2504d6d1] [error="context canceled"]
```
When ctx is cancel, the grpc call to update meta cache will never success.
The correct way to handle this shall be invalidate the cache when error occurs. Let the `GetShard` handle cache missing itself.
/unassign @jiaoew1991 
/assign

**Comment by psc0606** [comment]
Can someone explain why not the globalcache was automatically updated by watching etcd, what's the thinking behind it?

**Comment by congqixia** [comment]
@psc0606 a valid shard leader is determined by QueryCoord. The only session cannot make a querynode a candidate for shard leader here.
