### ISSUE TITLE
[Bug]:  The milvus pod service stops when loading data into memory. （2 querynode）

### ISSUE THREAD

**Issue by jinlongzhong** [milvus-io/milvus#21436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:  v2.2.2(by helm)
- Deployment mode(standalone or cluster): cluster(3 nodes)
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.2.1
- OS(Ubuntu or CentOS):  CentOS
- CPU/Memory: per node : 16GPU / 24GB RAM
- GPU: 
- Others:
```

### Current Behavior

The milvus pod service stops when loading data into memory. （2 querynode）
However, this does not happen when using a single querynode.

### Steps To Reproduce

```markdown
install ref: https://milvus.io/docs/install_cluster-helm.md
1. create collection and insert data (normal)
2. create index (normal)
3. load (error) information:
RPC error: [get_loading_progress], <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Stream removed"
        debug_error_string = "{"created":"@1672239378.184000000","description":"Error received from peer ipv4:192.168.1.167:27017","file":"src/core/lib/surface/call.cc","file_line":967,"grpc_message":"Stream removed","grpc_status":2}"
>)>, <Time:{'RPC start': '2022-12-28 22:56:05.427299', 'RPC error': '2022-12-28 22:56:18.203565'}>
```

### Milvus Log

error in querynode：
[WARN] [querynode/impl.go:498] ["context canceled"]
[2022/12/28 23:44:10.702 +00:00] [WARN] [querynode/shard_cluster.go:651] ["follower load segment failed"] [collectionID=438366220681416231] [channel=by-dev-rootcoord-dml_2_438366220681416231v0] [replicaID=438366242946678785] [dstNodeID=91] [segmentIDs="[438367976196688446]"] [reason="context canceled"]
[2022/12/28 23:44:10.702 +00:00] [WARN] [querynode/impl_utils.go:41] ["shard cluster failed to load segments"] [traceID=28b3664b8257440b] [shard=by-dev-rootcoord-dml_2_438366220681416231v0] [segmentIDs="[438367976196688446]"] [error="follower 91 failed to load segment, reason context canceled"]

**Comment by jinlongzhong** [comment]
all milvus log
[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/10317455/milvus-log.tar.gz)

**Comment by xiaofan-luan** [comment]
let me take a look into it

**Comment by xiaofan-luan** [comment]
seems that the etcd is crashing.
![image](https://user-images.githubusercontent.com/83447078/210161121-c1b0f5e1-e243-411e-ae24-cc0535fe155e.png)

**Comment by xiaofan-luan** [comment]
@jinlongzhong 
1. how many data you are trying to load? (dimension, index type and entity numbers)
2. What is the memory config or etcd and milvus?
3. could you verify your etcd is all healthy?

**Comment by xiaofan-luan** [comment]
2022/12/28 23:46:54.673 
This seems to be the time etcd begin to crash

**Comment by jinlongzhong** [comment]
@xiaofan-luan 
1. data:56W; dim:1024; index type:IVF_FLAT;
2.  per  node:ram 24G, etcd and milvus config: default;
3. the etcd status seems unhealthy.I built the cluster using sealos,and default configuration.

**Comment by jinlongzhong** [comment]
@xiaofan-luan 
1. data:56W; dim:1024; index type:IVF_FLAT;
2.  per  node:ram 24G, etcd and milvus config: default;
3. the etcd status seems unhealthy.I built the cluster using sealos,and default configuration.

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan
> 
> 1. data:56W; dim:1024; index type:IVF_FLAT;
> 2. per  node:ram 24G, etcd and milvus config: default;
> 3. the etcd status seems unhealthy.I built the cluster using sealos,and default configuration.

Memory seems to be enough.
Any logs about etcd? I'm not an expert on etcd but maybe we can take a look into it together

**Comment by jinlongzhong** [comment]
@xiaofan-luan 
one of the etcd log
[milvus_my-release-etcd-1_etcd.log](https://github.com/milvus-io/milvus/files/10335090/milvus_my-release-etcd-1_etcd.log)
