### ISSUE TITLE
[shards] Server start failed caused by permission denied

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#2143]
**Describe the bug**
```
[2020-04-26T18:05:44.148Z] deploy_mode: single instance lock db path failed.
[2020-04-26T18:05:44.148Z] Permission denied. Could not get lock.
[2020-04-26T18:05:44.148Z] Milvus server exit...
```
**Steps/Code to reproduce behavior**
Start shards with helm failed, the docker logs show the above message.

**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by tinkerlin** [comment]
already fixed

**Comment by del-zhenwu** [comment]
close it
