### ISSUE TITLE
[Feature]: Support releasing partitions from a loaded collection and then loading some other partitions Or Support entity expire

### ISSUE THREAD

**Issue by zxmantou** [milvus-io/milvus#21447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

We need to keep 90 days data in milvus to save storage. Due to milvus not support entity expires, we create a partition for every day, and we try to create a cronjob to delete partition of 90days ago. (according to [this issue](https://github.com/milvus-io/milvus/issues/6151#issuecomment-870341634))

but when Collection is loaded, we can't release single partition. error msg: 
> releasing some partitions after load collection is not supported

then we try to load every single partition. when one partition is loaded, other partitions can't be loaded. error msg: 
> some partitions %v of collection %v has been loaded into QueryNode, please release partitions firstly

### Describe the solution you'd like.

we find the message from [this doc page](https://milvus.io/docs/release_partition.md):

> Error will be returned at the attempt to load partition(s) when the parent collection is already loaded. Future releases will support releasing partitions from a loaded collection, and (if needed) then loading some other partition(s).

So I would like to know is this feature in planning?  

### Describe an alternate solution.

Support entity expire is better for me

**Comment by xiaofan-luan** [comment]
/assign @bigsheeper 
pls take a look into it

**Comment by bigsheeper** [comment]
> So I would like to know is this feature in planning?

Hello @zxmantou, yes, this feature is in planning, actually we have had some design schemes for it. See also: #18242

**Comment by zxmantou** [comment]
> Hello @zxmantou, yes, this feature is in planning, actually we have had some design schemes for it. See also: #18242

got it , thank you very much!
