### ISSUE TITLE
[Enhancement]: Optimize performance of ListSegments operation in ETCD catalog

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#21452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

1.  Use a batch get request with a prefix instead of a directly get request with the prefix
2. Use parallel operation instead of serial operation

### Why is this needed?

The list segment operation in the catalog will take more and more time along with segment number growth. It causes recovery time needs more time because Datacoord needs to preload all segment meta into the cache before the service becomes available.

Currently, preloading 5000 segments will take more than 100s.

### Anything else?

There are some test results based on a simple implementation.
```
goos: darwin
goarch: amd64
pkg: github.com/milvus-io/milvus/internal/metastore/kv/datacoord
cpu: Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
BenchmarkCatalog_List1000Segments
BenchmarkCatalog_List1000Segments-8                  1        16792400190 ns/op(16.8s)
BenchmarkCatalog_ParallelList1000Segment
BenchmarkCatalog_ParallelList1000Segment-8                 28          41418921 ns/op(0.04s)

BenchmarkCatalog_List5000Segments
BenchmarkCatalog_List5000Segments-8                  1        131452150077 ns/op(131.4s)
BenchmarkCatalog_ParallelList5000Segment
BenchmarkCatalog_ParallelList5000Segment-8                  3         375204559 ns/op(0.38s)

BenchmarkCatalog_List10000Segments
BenchmarkCatalog_List10000Segments-8                  1        193096165942 ns/op(193s)
BenchmarkCatalog_ParallelList10000Segment
BenchmarkCatalog_ParallelList10000Segment-8                  3         393884981 ns/op(0.39s)

BenchmarkCatalog_List20000Segments
BenchmarkCatalog_List20000Segments-8                  1        438703316013 ns/op(438.7s)
BenchmarkCatalog_ParallelList20000Segment
**BenchmarkCatalog_ParallelList20000Segment-8                  1        1722244533 ns/op(1.7s)
```

**Comment by xiaofan-luan** [comment]
Looks much faster, good job!

**Comment by xiaofan-luan** [comment]
Should improve datacoord recovery speed impressively
