### ISSUE TITLE
[Bug]: deleting on non-pk field should be forbidden now

### ISSUE THREAD

**Issue by longjiquan** [milvus-io/milvus#21458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Milvus only support to delete by pk now, for example, `delete("pk in [1, 2, 3]")` or `delete("pk in [\"1\", \"2\"]")` if the pk is VarChar type. However, we didn't forbid the case that the field is not primary key.

**Comment by yanliang567** [comment]
/assign @binbinlv 
@binbinlv please check if there were cases for this secnarios.

**Comment by binbinlv** [comment]
> /assign @binbinlv @binbinlv please check if there were cases for this secnarios.

OK, working.

**Comment by binbinlv** [comment]
/assign @ThreadDao 

yufen is working on this, so transfer to her.

**Comment by xiaofan-luan** [comment]
Good catch
