### ISSUE TITLE
[Bug]: Make the `UnsubDmChannel` rpc unsuccessful when the releaseCollectionTask fails

### ISSUE THREAD

**Issue by SimFG** [milvus-io/milvus#21470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/21985684/210050194-16ff06ac-901d-4e98-b2b1-89cd915335a3.png)

**Comment by xiaofan-luan** [comment]
Good catch!
