### ISSUE TITLE
[Bug]: A C search error on 1280 Dimension index type IVF_SQ8

### ISSUE THREAD

**Issue by djboboch** [milvus-io/milvus#21480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.2
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): kafka 
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.2.1
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 90 CPU 160 GB
- GPU: No
- Others:
```

### Current Behavior

We have two vectors one of dimensions 500, that does the search correctly.

However with out 1280 dimnesion saerch we get search errors.

**Node type**

We are running on Azure Standard_F32s_v2, which meets all the requirements for searches.

We have about 370000 entries four our collection on which the error occurs. 

### Expected Behavior

Working vektor search.

### Milvus Log

[proxy/impl.go:2782] ["Search failed to WaitToFinish"] [traceID=4ea128a3d98729f5] [error="fail to search on all shard leaders, err=fail to Search, QueryNode ID=60, reason=Search 60 failed, reason [UnexpectedError] Error in virtual knowhere::DatasetPtr knowhere::IVF::Query(const DatasetPtr&, const Config&, faiss::BitsetView) at IndexIVF.cpp:161: [json.exception.out_of_range.403] key 'nprobe' not found err %!w(<nil>)"] [role=proxy] [msgID=438410983233552392] [db=] [collection=image] [partitions="[]"] [dsl=] [len(PlaceholderGroup)=5132] [OutputFields="[]"] [search_params="[{\"key\":\"anns_field\",\"value\":\"signature\"},{\"key\":\"topk\",\"value\":\"51\"},{\"key\":\"metric_type\",\"value\":\"IP\"},{\"key\":\"params\",\"value\":\"{}\"},{\"key\":\"round_decimal\",\"value\":\"-1\"},{\"key\":\"offset\",\"value\":\"0\"}]"] [travel_timestamp=0] [guarantee_timestamp=0]

[WARN] [proxy/task_scheduler.go:462] ["Failed to execute task: "] [error="fail to search on all shard leaders, err=fail to Search, QueryNode ID=60, reason=Search 60 failed, reason [UnexpectedError] Error in virtual knowhere::DatasetPtr knowhere::IVF::Query(const DatasetPtr&, const Config&, faiss::BitsetView) at IndexIVF.cpp:161: [json.exception.out_of_range.403] key 'nprobe' not found err %!w(<nil>)"] [traceID=4ea128a3d98729f5]

[WARN] [proxy/task_search.go:401] ["failed to do search"] [traceID=4ea128a3d98729f5] [Shards="map[by-dev-rootcoord-dml_10_438392357819391930v0:[<NodeID: 60>] by-dev-rootcoord-dml_11_438392357819391930v1:[<NodeID: 60>]]"] [error="fail to Search, QueryNode ID=60, reason=Search 60 failed, reason [UnexpectedError] Error in virtual knowhere::DatasetPtr knowhere::IVF::Query(const DatasetPtr&, const Config&, faiss::BitsetView) at IndexIVF.cpp:161: [json.exception.out_of_range.403] key 'nprobe' not found err %!w(<nil>)"]

[WARN] [proxy/task_policies.go:116] ["failed to search/query with round-robin policy"] [traceID=4ea128a3d98729f5] [error="Channel: by-dev-rootcoord-dml_10_438392357819391930v0 returns err: fail to Search, QueryNode ID=60, reason=Search 60 failed, reason [UnexpectedError] Error in virtual knowhere::DatasetPtr knowhere::IVF::Query(const DatasetPtr&, const Config&, faiss::BitsetView) at IndexIVF.cpp:161: [json.exception.out_of_range.403] key 'nprobe' not found err %!w(<nil>)Channel: by-dev-rootcoord-dml_11_438392357819391930v1 returns err: fail to Search, QueryNode ID=60, reason=Search 60 failed, reason [UnexpectedError] Error in virtual knowhere::DatasetPtr knowhere::IVF::Query(const DatasetPtr&, const Config&, faiss::BitsetView) at IndexIVF.cpp:161: [json.exception.out_of_range.403] key 'nprobe' not found err %!w(<nil>)"]

[WARN] [proxy/task_policies.go:129] ["failed to do query with node"] [traceID=4ea128a3d98729f5] [nodeID=60] [dmlChannels="[by-dev-rootcoord-dml_10_438392357819391930v0,by-dev-rootcoord-dml_11_438392357819391930v1]"] [error="fail to Search, QueryNode ID=60, reason=Search 60 failed, reason [UnexpectedError] Error in virtual knowhere::DatasetPtr knowhere::IVF::Query(const DatasetPtr&, const Config&, faiss::BitsetView) at IndexIVF.cpp:161: [json.exception.out_of_range.403] key 'nprobe' not found err %!w(<nil>)"]

[WARN] [proxy/task_search.go:497] ["QueryNode search result error"] [traceID=4ea128a3d98729f5] [msgID=438410983233552392] [nodeID=60] [reason="Search 60 failed, reason [UnexpectedError] Error in virtual knowhere::DatasetPtr knowhere::IVF::Query(const DatasetPtr&, const Config&, faiss::BitsetView) at IndexIVF.cpp:161: [json.exception.out_of_range.403] key 'nprobe' not found err %!w(<nil>)"]

[WARN] [querynode/impl.go:901] ["search shard cluster failed"] [traceID=4ea128a3d98729f5] [vChannel=by-dev-rootcoord-dml_10_438392357819391930v0] [error="Search 60 failed, reason [UnexpectedError] Error in virtual knowhere::DatasetPtr knowhere::IVF::Query(const DatasetPtr&, const Config&, faiss::BitsetView) at IndexIVF.cpp:161: [json.exception.out_of_range.403] key 'nprobe' not found err %!w(<nil>)"]

[WARN] [querynode/shard_cluster.go:994] ["failed to do search"] [msgID=438410983233552392] [sourceID=65] [channels="[by-dev-rootcoord-dml_10_438392357819391930v0]"] [segmentIDs="[]"] [error="Search 60 failed, reason [UnexpectedError] Error in virtual knowhere::DatasetPtr knowhere::IVF::Query(const DatasetPtr&, const Config&, faiss::BitsetView) at IndexIVF.cpp:161: [json.exception.out_of_range.403] key 'nprobe' not found err %!w(<nil>)"]

[WARN] [querynode/impl.go:901] ["search shard cluster failed"] [traceID=4ea128a3d98729f5] [vChannel=by-dev-rootcoord-dml_11_438392357819391930v1] [error="Search 60 failed, reason [UnexpectedError] Error in virtual knowhere::DatasetPtr knowhere::IVF::Query(const DatasetPtr&, const Config&, faiss::BitsetView) at IndexIVF.cpp:161: [json.exception.out_of_range.403] key 'nprobe' not found err %!w(<nil>)"]

[WARN] [querynode/shard_cluster.go:994] ["failed to do search"] [msgID=438410983233552392] [sourceID=65] [channels="[by-dev-rootcoord-dml_11_438392357819391930v1]"] [segmentIDs="[]"] [error="Search 60 failed, reason [UnexpectedError] Error in virtual knowhere::DatasetPtr knowhere::IVF::Query(const DatasetPtr&, const Config&, faiss::BitsetView) at IndexIVF.cpp:161: [json.exception.out_of_range.403] key 'nprobe' not found err %!w(<nil>)"]

[WARN] [querynode/task_scheduler.go:339] ["[UnexpectedError] Error in virtual knowhere::DatasetPtr knowhere::IVF::Query(const DatasetPtr&, const Config&, faiss::BitsetView) at IndexIVF.cpp:161: [json.exception.out_of_range.403] key 'nprobe' not found"]

 [WARN] [querynode/task_scheduler.go:339] ["[UnexpectedError] Error in virtual knowhere::DatasetPtr knowhere::IVF::Query(const DatasetPtr&, const Config&, faiss::BitsetView) at IndexIVF.cpp:161: [json.exception.out_of_range.403] key 'nprobe' not found"]

Same 4 errors: 

[WARN] [querynode/cgo_helper.go:56] ["Search failed, C Runtime Exception: [UnexpectedError] Error in virtual knowhere::DatasetPtr knowhere::IVF::Query(const DatasetPtr&, const Config&, faiss::BitsetView) at IndexIVF.cpp:161: [json.exception.out_of_range.403] key 'nprobe' not found\n"]
[WARN] [querynode/cgo_helper.go:56] ["Search failed, C Runtime Exception: [UnexpectedError] Error in virtual knowhere::DatasetPtr knowhere::IVF::Query(const DatasetPtr&, const Config&, faiss::BitsetView) at IndexIVF.cpp:161: [json.exception.out_of_range.403] key 'nprobe' not found\n"]
[WARN] [querynode/cgo_helper.go:56] ["Search failed, C Runtime Exception: [UnexpectedError] Error in virtual knowhere::DatasetPtr knowhere::IVF::Query(const DatasetPtr&, const Config&, faiss::BitsetView) at IndexIVF.cpp:161: [json.exception.out_of_range.403] key 'nprobe' not found\n"]
[WARN] [querynode/cgo_helper.go:56] ["Search failed, C Runtime Exception: [UnexpectedError] Error in virtual knowhere::DatasetPtr knowhere::IVF::Query(const DatasetPtr&, const Config&, faiss::BitsetView) at IndexIVF.cpp:161: [json.exception.out_of_range.403] key 'nprobe' not found\n"]

**Comment by yanliang567** [comment]
@djboboch cloud you please double confirm the milvus version and pymilvus version, it seems to be a known issue that already fixed in v2.2.2. Also please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation. 

/assign @djboboch 
/assign @cydrain

**Comment by xiaofan-luan** [comment]
@cydrain @yanliang567 
Did we have test on IVFSQ8?
This seems to be a very fundamental case

**Comment by xiaofan-luan** [comment]
@djboboch 
Did you specify nprobe when you do search? 
Can you share your code to do search?

**Comment by xiaofan-luan** [comment]
> key 'nprobe' not found err

The error says:
 key 'nprobe' not found err

**Comment by djboboch** [comment]
Hi, it seems that the default nprobe was not set. I seems to have solved the problem.

**Comment by yanliang567** [comment]
@djboboch do you mind closing the issue as it was solved?
