### ISSUE TITLE
[Feature]: support for cpu without AVX

### ISSUE THREAD

**Issue by yshuyan** [milvus-io/milvus#21483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I use docker-compose and want to upgrage from 2.1.4 to 2.2.2，but the docker can't be created for exited code 132  

![image](https://user-images.githubusercontent.com/54971201/210196386-6ef4cd8f-d60f-4936-9be2-613e23abd63b.png) 
 
I searh the code and the reason maybe cpu not support avx
 

Envirment:
- Milvus version: 2.1.4
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq 
- SDK version(e.g. pymilvus v2.0.0rc2): milvus-sdk-java==2.0.0
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: No
- Others:

### Describe the solution you'd like.

the 2.2.2 can be run on the cpu without avx

**Comment by xiaofan-luan** [comment]
I don't think we change anything about AVX in 2.2.2.
Could you share the log why your cluster crashed and also how did you do upgrade?

**Comment by yshuyan** [comment]
I romove all the old volumns files and then use the latest docker-compose.yml，the image status has been showed above,and doesn't have any logs when use "docker logs -f " command

**Comment by xiaofan-luan** [comment]
https://github.com/milvus-io/milvus/blob/289df1cc3ddeef5a1b08cc19fa84f1da2d3f0298/deployments/export-log/README.md 
check the following way to collect logs

**Comment by yshuyan** [comment]
[milvus.log](https://github.com/milvus-io/milvus/files/10341209/milvus.log)
here is the log, thank you

**Comment by liliu-z** [comment]
Fixed in the Knowhere 1.3.7 with [commit](https://github.com/milvus-io/knowhere/pull/634)
