### ISSUE TITLE
[Bug]: NewGrpcClient:  time out

### ISSUE THREAD

**Issue by tgk60w** [milvus-io/milvus#21496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):gomilvus:2.2.0
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/49012823/210379712-5dee0d9f-d22d-4b91-8fb5-2ec9eed7df5d.png)
conf.MilvusAddr is null
![image](https://user-images.githubusercontent.com/49012823/210380284-be279553-b50b-45a9-98d4-5b996651f887.png)

**Comment by yanliang567** [comment]
@tgk60w what's the expectation, i did not get that.
/assign @tgk60w

**Comment by tgk60w** [comment]
> @tgk60w what's the expectation, i did not get that. /assign @tgk60w

Can't connect to the server and not report errors

**Comment by yanliang567** [comment]
/assign @congqixia 
could you please take a look? it looks like a go sdk issue?

**Comment by xiaofan-luan** [comment]
@tgk60w pls check if you network is setup correctly? usually this is caused by network
