### ISSUE TITLE
[Bug]: Unable to load index, after operate load, the datacoord and rootcoord is exit

### ISSUE THREAD

**Issue by icodersky** [milvus-io/milvus#21510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvus2.2.2
- Deployment mode(standalone or cluster): k8s cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus2.2.1
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 700GB
- GPU: 
- Others:
```

### Current Behavior

After importing data, I operate load, and then all tables fail to load. Then I want to check the specific information. After setting log. level=info (originally log. level=errer), some services of milvus cannot be started.

<img width="646"  src="https://user-images.githubusercontent.com/86787724/210499680-a10b955f-a709-4859-b499-be2f806a53d8.png">

### Milvus Log

milvus日志：
[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/10342010/milvus-log.tar.gz)

**Comment by icodersky** [comment]
milvus logs:

[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/10342076/milvus-log.tar.gz)

**Comment by yanliang567** [comment]
@icodersky thank you for the issue. quick questions:
1. how did you import data? via insert or bulk_insert?
2. how much data did you import? what is the dim?

/assign @jiaoew1991

**Comment by icodersky** [comment]
> @icodersky thank you for the issue. quick questions:
> 
> 1. how did you import data? via insert or bulk_insert?
> 2. how much data did you import? what is the dim?
> 
> /assign @jiaoew1991

1. using Python, bulk_insert 5000 entries at a time.
2. There are about 100 million pieces of 2048 dim vector data.

**Comment by xiaofan-luan** [comment]
/assign @soothing-rain 
could you pls take a look on it

**Comment by soothing-rain** [comment]
It appears that RootCoord cannot start due to lack of Pulsar bookie resources:
```
panic: Failed to create producer by-dev-rootcoord-dml_0, error = All attempts results:
attempt #1:server error: PersistenceError: org.apache.bookkeeper.mledger.ManagedLedgerException: Not enough non-faulty bookies available
attempt #2:server error: PersistenceError: org.apache.bookkeeper.mledger.ManagedLedgerException: Not enough non-faulty bookies available
attempt #3:server error: PersistenceError: org.apache.bookkeeper.mledger.ManagedLedgerException: Not enough non-faulty bookies available
attempt #4:server error: PersistenceError: org.apache.bookkeeper.mledger.ManagedLedgerException: Not enough non-faulty bookies available
attempt #5:server error: PersistenceError: org.apache.bookkeeper.mledger.ManagedLedgerException: Not enough non-faulty bookies available
attempt #6:server error: PersistenceError: org.apache.bookkeeper.mledger.ManagedLedgerException: Not enough non-faulty bookies available
attempt #7:server error: PersistenceError: org.apache.bookkeeper.mledger.ManagedLedgerException: Not enough non-faulty bookies available
attempt #8:server error: PersistenceError: org.apache.bookkeeper.mledger.ManagedLedgerException: Not enough non-faulty bookies available
attempt #9:server error: PersistenceError: org.apache.bookkeeper.mledger.ManagedLedgerException: Not enough non-faulty bookies available
attempt #10:server error: PersistenceError: org.apache.bookkeeper.mledger.ManagedLedgerException: Not enough non-faulty bookies available
attempt #11:server error: PersistenceError: org.apache.bookkeeper.mledger.ManagedLedgerException: Not enough non-faulty bookies available
```

1) How did you start your Milvus cluster? Can you post your deployment configuration file here?
2) Can you double check if your pulsar PVCs have enough disk space?

@icodersky
