### ISSUE TITLE
[Bug]: metricType return wrong when recreate index with anther metricType

### ISSUE THREAD

**Issue by yelusion2** [milvus-io/milvus#21539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2
- Deployment mode(standalone or cluster): all
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

create a L2 metric type index, drop the index and then create a IP metric type index in same collection field.

describe collection return schema the metric type is L2, that is wrong,

and describe inde retrun the metric type is IP, its right.

### Expected Behavior

describe collection return the right metric type

### Steps To Reproduce

```markdown
1. create a collection
2. create a index in the collection vector field, and the metric type is L2
3. drop step 2 index
4. create a index in the collection vector field, and the metric type is IP
4. describe the collection
```

### Anything else?

PS:

if we create index have specify metric type,  we do search and query can not specify metric type param, default the index metric type, if user specify metric type we use it.

**Comment by yanliang567** [comment]
@yelusion2 could you please share the code snippet to reproduce this issue? 

@czs007 i think you are working on this issue.
/assign @czs007 
/unassign

**Comment by yelusion2** [comment]
i have found the reason， 
i create index have specify the vector field schema type param with metric_type ,
but the search action will validator the metric type with the describe collection schema metric_type, 
then return error.
the error is :
{"Code":47021,"Message":"message:fail to search on all shard leaders, err=fail to Search, QueryNode ID=2, reason=Search 2 failed, reason [UnexpectedError] Assert "field_indexing->metric_type_ == search_info.metric_type_" at /go/src/[github.com/milvus-io/milvus/internal/core/src/query/SearchOnSealed.cpp:39\n](http://github.com/milvus-io/milvus/internal/core/src/query/SearchOnSealed.cpp:39/n) => Metric type of field index isn't the same with search info err %!w(<nil>).","RequestId":"0818fd6d-406b-48eb-a6dd-0db0388cb445","Data":null}

**Comment by xiaocai2333** [comment]
I can't reproduce it on branch 2.2.0 and master. Is it still exist?

**Comment by xiaocai2333** [comment]
![image](https://user-images.githubusercontent.com/46207236/226508120-5138d069-9348-42c7-a122-a3f4df4ddd19.png)

In version 2.1, we can specify metric_type on the column when building a table, and we can not specify it when building an index. At this time, the metric_type parameter is in type_params, but after the upgrade, QueryCoord thinks that metrics_type is in index_params when it gets IndexInfo from IndexCoord.
So, it can create index successfully, but search failed.
we need check it in milvus. metrics_type must be in index_params.

**Comment by yanliang567** [comment]
i believe it was fixed already. close.
