### ISSUE TITLE
[Bug]: query pagination return result missing data

### ISSUE THREAD

**Issue by yelusion2** [milvus-io/milvus#21542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2 
- Deployment mode(standalone or cluster): all
- MQ type(rocksmq, pulsar or kafka):   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

create a collection with same shard, 
insert little data, 
searh data with no expr topk 10, get the 10 record ids,
query with the id in that 10 record ids,  no limit no offset, return the 10 data,
but query with the id in that 10 record ids,  limit is 10, offset is 0, return data less than 10 

### Expected Behavior

 query with the id in that 10 record ids,  limit is 10, offset is 0, return the 10 data.

### Steps To Reproduce

```markdown
1.create a collection with same shard, 
2.insert little data, 
3. searh data with no expr topk 10, get the 10 record ids,
4. query with the id in that 10 record ids,  no limit no offset, return the 10 data,
5. but query with the id in that 10 record ids,  limit is 10, offset is 0, return data less than 10.
```

**Comment by yanliang567** [comment]
/assign @NicoYuan1986 
@NicoYuan1986 is this a known issue? do we have tests to cover this scenario?

**Comment by NicoYuan1986** [comment]
> /assign @NicoYuan1986 @NicoYuan1986 is this a known issue? do we have tests to cover this scenario?

No, i'll check it.

**Comment by NicoYuan1986** [comment]
I tried to reproduce it in the master and 2.2 branch. But it looks okay.
milvus: master-20230110-c550427e
pymilvus: 2.3.0.dev21
![image](https://user-images.githubusercontent.com/109071306/211531199-df31e823-e78b-40aa-9699-4e8904601392.png)

milvus: 2.2.0-20230110-c7040379
pymilvus: 2.2.1.dev5
![image](https://user-images.githubusercontent.com/109071306/211534874-aaed91af-2e2b-4ec5-87fc-f72a30c773e4.png)

**Comment by XuanYang-cn** [comment]
I couldn't reproduce it locally either. Is it still an issue now? If so, @yelusion2 Please share the reproducing scripts.
/assign @yelusion2 
/unassign @NicoYuan1986

**Comment by xiaofan-luan** [comment]
@yelusion2 
is this still a issue?

**Comment by yelusion2** [comment]
this issue have resolved.
