### ISSUE TITLE
建议限制partition数目可配置

### ISSUE THREAD

**Issue by richxnh** [milvus-io/milvus#2156]
建议限制partition数目可配置，在我们的业务场景中，partition数目会超过4096，用的mysql做数据库。

**Comment by JinHai-CN** [comment]
Maybe you can describe why you want so many partitions.

**Comment by richxnh** [comment]
主要是为了更精确的检索特征(如：按时间分片或按空间分片)，集中在一个大索引里，会降低搜索的精度

**Comment by JinHai-CN** [comment]
When Milvus support scalar fields filtering, you may archive the result as you want.

**Comment by richxnh** [comment]
这个功能什么时候实现呢？如果时间比较长，希望能在这下一版先放开partition限制，partition可配置

**Comment by JinHai-CN** [comment]
Milvus 0.10.0 will have this feature.

**Comment by richxnh** [comment]
好的，谢谢告知
