### ISSUE TITLE
[Enhancement]: Add checkpoint ts restraint for segment gc

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#21563]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Add segment gc restraint that segment could be gc only when channel cp is after its dml position

### Why is this needed?

In some extreme case, when segment is gc-ed, querynode/datanode may read it from dml channel and without knowing it's dropped. 
Adding this restraint shall add protection for this case.

**Comment by xiaofan-luan** [comment]
might be related to #21527
