### ISSUE TITLE
建议原始数据建立索引后可删除

### ISSUE THREAD

**Issue by richxnh** [milvus-io/milvus#2158]
在我们这的大多数场景下，当原始数据建立索引后，存在的意义就不大了，建议可增加一个配置选项，原始数据可自动或手动清除，以减少数据存储空间。

**Comment by JinHai-CN** [comment]
We will optimize the index / raw data storage in the future, stay tuned.

**Comment by richxnh** [comment]
能大致说一下方案及在哪个版本实现吗？谢谢

**Comment by JinHai-CN** [comment]
According to current plan, it will be implemented in 0.12.0. The proposed solution is to reduce the index storage size, but the raw data.

**Comment by richxnh** [comment]
0.12.0版本的索引存储大小，能优化到多少呢？实际我们更担心的是原始数据大小，我们一张图片会提取多种策略的特征，这样就会有多个原始特征文件，如果原始特征文件都保存的话，数据量会非常大。原始特征数据建索引后的大小已经很小了，可以接受。

**Comment by JinHai-CN** [comment]
Depending on the dimension, but most of them will be reduced.
