### ISSUE TITLE
[Bug]:  Data node get restarted after search in collection

### ISSUE THREAD

**Issue by meetsoni15** [milvus-io/milvus#21587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvus:v2.1.4
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus (2.1.3) | go-milvus (2.2.0)
- OS(Ubuntu or CentOS): Amazon Linux (CentOS)
- CPU/Memory: 4/16
- GPU: NA
- Others: Setup everything on EKS clsuter
```

### Current Behavior

We have setup a Milvus cluster on EKS nodes, but have been facing issues with data availability. The data node restarts after certain times and data gets lost. We are using Attu UI for checking data and collections. Please refer attached node screenshot. 

Here We have attached logs for data nodes and proxy server. Please check and suggest needfull and if you need anything else please feel free to reach out

### Expected Behavior

As per expected behavior,  data should be there in collection.

### Steps To Reproduce

```markdown
1. Connect to milvus using go-sdk
2. Load collection
3. Search data into any collection for certain times
4. Released collection
3. After repeating same process multiple time data node get restarted and data gets lost
```

### Milvus Log

![image](https://user-images.githubusercontent.com/13797780/211255765-24474406-402f-4a0a-81df-9f15d6be6ccf.png)

**Comment by JackLCL** [comment]
@meetsoni15 
Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

**Comment by yanliang567** [comment]
@meetsoni15 besides, could you please retry on milvus 2.2.2, which fixed many issues.
/assign @meetsoni15

**Comment by meetsoni15** [comment]
@yanliang567 Ok will try with milvus 2.2.2

**Comment by meetsoni15** [comment]
@yanliang567 After upgrading to Milvus 2.2.2 Issue got resolved. Thanks!!
