### ISSUE TITLE
[Bug]: Manually delete the session key, but the component does not exit

### ISSUE THREAD

**Issue by xiaocai2333** [milvus-io/milvus#21599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Manually delete the session key of `IndexCoord`, `DataCoord` or `node`, but the component does not exit.

### Expected Behavior

Manually delete the session key, and the component exits after one minute at the latest.

**Comment by xiaofan-luan** [comment]
keep it
