### ISSUE TITLE
[FEATURE] Add CLI to get server info

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#216]
**Is your feature request related to a problem? Please describe.**
Not a problem

**Describe the solution you'd like**
Add server interface, we can call it by sdk to get server current info and server config

**Describe alternatives you've considered**

**Additional context**

**Comment by del-zhenwu** [comment]
just as redis:info interface, user can get server info(memory usage, gpu usage ..) by cmd

**Comment by cydrain** [comment]
done
