### ISSUE TITLE
请问能不使用docker进行部署吗？

### ISSUE THREAD

**Issue by lxw0109** [milvus-io/milvus#2160]
请问能不使用docker进行部署吗？有相关的文档吗？蟹蟹~

**Comment by tinkerlin** [comment]
https://www.milvus.io/cn/docs/v0.8.0/guides/get_started/install_milvus/install_milvus.md

**Comment by tinkerlin** [comment]
https://github.com/milvus-io/milvus/blob/master/INSTALL.md

**Comment by lxw0109** [comment]
感谢~
