### ISSUE TITLE
milvus.client.exceptions.NotConnectError: Fail connecting to server on 127.0.0.1:19530. Timeout

### ISSUE THREAD

**Issue by jotline** [milvus-io/milvus#2161]
**Describe the bug**
 I just follow the guides in https://www.milvus.io/docs/guides/get_started/example_code.md
Everything looks fine, but the code just doesn't work
example.py is in here -> https://raw.githubusercontent.com/milvus-io/pymilvus/0.8.0/examples/example.py

**Environment details**
certifi==2020.4.5.1
chardet==3.0.4
grpcio==1.28.1
grpcio-tools==1.28.1
idna==2.9
numpy==1.18.3
protobuf==3.11.3
pymilvus==0.2.10
requests==2.23.0
six==1.14.0
ujson==2.0.3
urllib3==1.25.9

**Screenshots**
![image](https://user-images.githubusercontent.com/19920429/80441768-2cc05000-893e-11ea-8e85-66c781a946d9.png)
![image](https://user-images.githubusercontent.com/19920429/80441812-42357a00-893e-11ea-8582-9861ca05bfc8.png)
![image](https://user-images.githubusercontent.com/19920429/80441851-5aa59480-893e-11ea-9f82-43bd33f71803.png)
![image](https://user-images.githubusercontent.com/19920429/80442281-27173a00-893f-11ea-828e-423818423a08.png)

**Comment by BossZou** [comment]
Hello @jotline , May you provide your conf file and command to run images?

**Comment by jotline** [comment]
@BossZou The problem is solved, it seems that the network configuration(maybe VPN or http_proxy) of my localhost machine affects the network connection of milvus.
When I change a  machine to run the same code(just change the ip ), it works fine.
