### ISSUE TITLE
[Bug]: There is a certain probability that the activated and standby coord cannot be switched when pod failure chaos is injected into activated coord

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#21626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: wayblink-mep-30-debug-2.2-c6aed4b-20230110
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023-01-10T10:29:52.068Z]         log.info(f"activated pod list: {activate_pod_list_after_chaos}, standby pod list: {standby_pod_list_after_chaos}")

[2023-01-10T10:29:52.068Z]         if role_type == "standby":

[2023-01-10T10:29:52.068Z]             # if the standby pod is injected, the activated pod should not be changed

[2023-01-10T10:29:52.068Z]             assert activate_pod_list_after_chaos[0] == activate_pod_list[0]

[2023-01-10T10:29:52.068Z]         if role_type == "activated":

[2023-01-10T10:29:52.068Z]             # if the activated pod is injected, the one of standby pods should be changed to activated

[2023-01-10T10:29:52.068Z] >           assert activate_pod_list_after_chaos[0] in standby_pod_list

[2023-01-10T10:29:52.068Z] E           AssertionError: assert 'querycoord-pod-failure-30-milvus-querycoord-7f866f94c8-whrkw' in ['querycoord-pod-failure-30-milvus-querycoord-7f866f94c8-95tpt']
```

And this makes a lot of error during the chaos
![d3242ba8-b882-4393-a36e-b96acdae98d2](https://user-images.githubusercontent.com/12268675/211535686-e3bf0aaa-bd52-4923-8017-a680f936d266.jpeg)

```
[2023-01-10T10:17:10.349Z] [2023-01-10 10:17:10 - INFO - ci_test]: IndexChecker, succ_rate: 0.48, total: 113, average_time: 4.2755, max_time: 21.7233, min_time: 2.1894 (checker.py:127)
```

### Milvus Log

chaos type: pod-failure image tag: wayblink-mep-30-debug-2.2-c6aed4b-20230110 target pod: querycoord
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/standby_test/detail/standby_test/30/pipeline
log:
[artifacts-querycoord-pod-failure-30-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10381939/artifacts-querycoord-pod-failure-30-server-logs.tar.gz)

[artifacts-querycoord-pod-failure-30-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10381940/artifacts-querycoord-pod-failure-30-pytest-logs.tar.gz)

### Anything else?

chaos type: pod-failure image tag: wayblink-mep-30-debug-2.2-c6aed4b-20230110 target pod: indexcoord
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/standby_test/detail/standby_test/28/pipeline
log:
[artifacts-indexcoord-pod-failure-28-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10381948/artifacts-indexcoord-pod-failure-28-server-logs.tar.gz)
[artifacts-indexcoord-pod-failure-28-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10381949/artifacts-indexcoord-pod-failure-28-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
seems a same issue https://github.com/milvus-io/milvus/issues/21589

**Comment by zhuwenxing** [comment]
/assign @wayblink 

please take a look

**Comment by zhuwenxing** [comment]
It is still reproduced in `2.2.0-20230114-d475de49`
chaos type: pod-failure image tag: 2.2.0-latest target pod: rootcoord
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/standby_test/detail/standby_test/124/pipeline
log:
[artifacts-rootcoord-pod-failure-124-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10422174/artifacts-rootcoord-pod-failure-124-server-logs.tar.gz)

[artifacts-rootcoord-pod-failure-124-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10422175/artifacts-rootcoord-pod-failure-124-pytest-logs.tar.gz)

**Comment by wayblink** [comment]
Session watch activeKey with WithPrefix option. So other key updates may also influence the watch logic and bring in chaos. After removing WithPrefix, bug fixed.

**Comment by zhuwenxing** [comment]
Not reproduced recently, so close it.

**Comment by zhuwenxing** [comment]
It still happened.
chaos type: pod-failure image tag: 2.2.0-20230131-02cfcbbd target pod: indexcoord role_type : activated
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/standby_test/detail/standby_test/290/pipeline
log:
[artifacts-indexcoord-pod-failure-290-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/10553113/artifacts-indexcoord-pod-failure-290-server-logs.1.tar.gz)

[artifacts-indexcoord-pod-failure-290-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10553114/artifacts-indexcoord-pod-failure-290-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
verified and passed with `2.2.0-20230202-161725a6`
