### ISSUE TITLE
[Bug]: milvus2.2.0 search latency >1s, when searching without expr

### ISSUE THREAD

**Issue by changhong52** [milvus-io/milvus#21632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:  2.2.0
- Deployment mode(standalone or cluster):  cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):  V2.2.0
- OS(Ubuntu or CentOS):  Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

2500W数据压测向量检索，耗时大于1s
![sQMjpriL1L](https://user-images.githubusercontent.com/121591595/211565269-15a8667e-8c66-46d9-b59e-f978eaadb8d7.jpg)

### Expected Behavior

期望查看很慢的原因

### Anything else?

![image](https://user-images.githubusercontent.com/121591595/211308229-c144ef8a-427b-4262-b364-7580c363fc30.png)

**Comment by JackLCL** [comment]
[logs.tar.gz](https://github.com/milvus-io/milvus/files/10383221/logs.tar.gz)

**Comment by xiaofan-luan** [comment]
@yanliang567 do we have a benchmark case for hybrid search?

**Comment by yanliang567** [comment]
keep it active, we are trying to improve the hybrid searching soon

**Comment by KeshavSingh29** [comment]
Is there a reference example on how to conduct hybrid search (w/ PyMilvus) on Milvus vectorstore with metadata?

**Comment by yanliang567** [comment]
> Is there a reference example on how to conduct hybrid search (w/ PyMilvus) on Milvus vectorstore with metadata?

try this link: https://milvus.io/docs/hybridsearch.md#Conduct-a-Hybrid-Search
BTW, the improvement of hybrid search is in testing now. It would come to be available soon this month or early next month.

**Comment by patelprateek** [comment]
@yanliang567 : has the hybrid search been improved ? what is the new latency after the optimization
Also can you please provide some pointers on what the optimizations are for example : instead of lineqr scan filtering are we creating new index types (inverted , sorted, bitsets ) ? any memory implications . 
If you can proivde pointers to any design or code that would be very helpful for modeling oour data accordingly

**Comment by yanliang567** [comment]
The hybird search improved in milvus v2.3.2 with HNSW and DiskANN, if 90% or more data is filtered in the search request.

**Comment by patelprateek** [comment]
@yanliang567 : can you please provide more details about what the optimizations are . are we doing the filtering ? ikeep reading different comments and it is not clear to me what exactly is happening. Are we doing brute force predicate filtering to generated bitset or are we using some different index structure ?
