### ISSUE TITLE
[Feature]: Implement Iterator functionality

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#21633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

We want to iterate through the table for the following reasons:
1. export the collection with multi rpcs.
2. in range search, if the result set is large, iterate with multiple RPCs.

### Describe the solution you'd like.

<img width="646" alt="image" src="https://user-images.githubusercontent.com/83447078/211583202-51fc3bd2-e10f-443a-b35a-59011e6bb8e5.png">

The iterator interface is like this
type ResultIterator interface {
	// Begin resets the cursor of the iterator and returns the first entity.
	open(SearchRequest sr) error

	// Next returns the next Row.
	Next() Result, error

	// Is their a next 
        HasNext() bool

	// Close the iterator
	Close()
}

var searchRequest sr
err := iterator.open(sr)
defer iterator.close()
if err != nil 
    return err
while iterator.hasNext() 
      entity, err := iterator.Next()
      if err != nil 
         return err

**Comment by xiaofan-luan** [comment]
The problem is how we do iterate, here is the plan

the open function is send to all shard leaders, this will ensure all segments won't be released in 30s, the return value will be token, something like a replicaID , map[shard]segment list - offset, ts

the open function will also return the first part of data into client cache, by default the concurrency will be same as shard numbers, so the first cache returns shard number * limit entities.

then when the user call next, client will return entities from client cache, until the cache runs out.

Then the open function will send the token back, each shard leader find the segment to execute on, and fetch for the next limit  entities.

When close is called, we close the iterator at shard leader so handoff can be done.

If client crash, we will keep a 30s lease time and shard leader automatically close the lease.

**Comment by xiaofan-luan** [comment]
Limitations:
Iterator returned result is not in order.
How to handle shard leader balance? 
For query, each segment can always return in data order.
For range search, do we support offset?

**Comment by xiaofan-luan** [comment]
Anyone interested in this feature?

**Comment by djboboch** [comment]
Hi, extracting all the ID's that are assigned to the vector representation would be great :) 
I am facing an issue right now, where I need to verify all the representation with our metadata state and without the iterator I don't seem to know how to extract all the data we have.

I would be more then happy to help in the implementation of this feature.

**Comment by djboboch** [comment]
Hi @xiaofan-luan  could you point me at a direction where I could start developing this feature ?

**Comment by xiaofan-luan** [comment]
> Hi @xiaofan-luan could you point me at a direction where I could start developing this feature ?

Hi dj, sorry for the late reply.

to finish the iterator feature, we need to implement a volcano style pull based iterator.

When iterator open is called, the first step is to maintain a ts and a segment list at that time.

Then, we could sort segment list and start to return result for each segment. For the ease of implementation, we could return all result matched in one segment at a time. the result will be cached in SDK, so each next won't necessarily request a rpc. Each time we return one segment result only to ensure the returned result don't exceed rpc limit(if segment size is too large we might need another pivot such as distance or PK)

Third part would be implement per segment level search/query. It would't take too much effort because everything should be similar to current pagination logic.

Lastly, don't forget to handle the case when segment is compacted so the list you maintained will be invalidated. To handle this the easiest way is to add a lock and ensure segment won't be handoffed, the lock will only be released once iterator is closed or iterator lease timeout.

@djboboch any ideas or questions? I'm glad to offer some 1 to 1 mentorship on this feature if you want to spend some time on it~

**Comment by thinh2** [comment]
Hi, is this issue available?

**Comment by shunjiezhao** [comment]
Hello, I am very interested in this feature. 

 I have some questions.

1. How to deal with lease expiration does not affect previously loaded segments,
For example
```
1. load collection
2. call open
3. expiration of lease
4. query
5. release collection
```


Can shardLeader maintain a refcnt to solve this problem

2. What is the role of ts?
3. I want to get more familiar with this feature. Is there any flow, concept or code that I need to focus on.

**Comment by xiaofan-luan** [comment]
MrPresent should be the right person to answer the question.

So far My understands we don't have lease at serverside. but rather send request with a cursor. 
For query the cursor is pk (Since query always return cursor in the same order), for search we use range

**Comment by shunjiezhao** [comment]
Hi @MrPresent-Han, I see your impl in pymilvus , i has a question about search param.
What is the role of these two parameters ( `radius` , `range_filter`) in range search, and how do the search results relate to their previous ones?
