### ISSUE TITLE
[Bug]: Failed to deploy the stand-alone version of etcd that comes with the milvus cluster

### ISSUE THREAD

**Issue by RongHouchao** [milvus-io/milvus#21636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.2
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Deployment method: helm
Branch: Master branch of milvus-helm

Modify the configuration file: etcd. replicaCount=1, and then start milvus. The built-in etcd of milvus fails to start.
![image](https://user-images.githubusercontent.com/117245915/211708416-f214e4f8-84b7-473f-a617-2b8a5ccfb7fc.png)

![image](https://user-images.githubusercontent.com/117245915/211708592-4f7a2711-d931-4ebc-bded-a94454ebfb49.png)

The etcd log is as follows:
![image](https://user-images.githubusercontent.com/117245915/211708736-0a58c154-2076-464e-84c5-3f7a1a7c5aaa.png)

### Expected Behavior

When etcd. replicaCount=1 is configured, the stand-alone version of etcd should be started by default. Now, there is no parameter in values.yaml that controls the deployment of the stand-alone version or the cluster version, just a parameter to configure the number of pods

### Steps To Reproduce

```markdown
Pull the master branch of milvus-helm, modify the etcd.replicaCount of values.yaml to 1, start milvus, etcd fails to start, and there must be a problem.
```

### Milvus Log

..

### Anything else?

...

**Comment by yanliang567** [comment]
@RongHouchao I'd like to know why you want a standalone etcd against a clustered milvus?
/assign @LoveEachDay 
/unassign

**Comment by RongHouchao** [comment]
Insufficient resources. I want to reduce the consumption of these components as much as possible to maximize the use of queryNode resources

**Comment by LoveEachDay** [comment]
@RongHouchao From the above screenshot, we can see you may have installed with a three member etcd clusters, later you changed to 1 member etcd.
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/1573213/216526675-09ad60bd-b1e5-4585-bcf9-4b888ab84dd3.png">


You'd first restore the etcd cluster back to 3 members, and then running the following command:
```
kubectl exec -it my-release-etcd-0 -- bash
# execute the following command in the etcd pod
etcdctl member list
etcdctl member remove <memer-id-for-etcd-1> <member-id-for-etcd-2>
```
After this you can change the etcd replicaCount back to 1.
