### ISSUE TITLE
[Bug]: All Milvus Node and Coord containers doesn't print out error for unsupported CPU instrcution set 

### ISSUE THREAD

**Issue by john-h-luo** [milvus-io/milvus#21649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.2
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Rocky Linux
- CPU/Memory: 4C/16G
- GPU: 
- Others:
```

### Current Behavior

This issue is intented to reproduce an issue resolved this morning, regarding Milvus pod continuing restarting, while no log generated to help identifying root cause.

When I creating Milvus cluster by docker compose, the following happened sequentially:
1. I create a VM on kvm platform, specifically set up CPU instrction not to include: sse4_2, avx, avx512
2. I installed docker engine correctly, and could confirm it is running
3. I downloaded milvus-cluster-docker-compose.yml from milvus.io
4. I ran command "docker compose up -d"
5. I check Milvus status with docker ps -a, noticing that Milvus nodes and coords are in "Exited (132)" state
6. I check milvus-rootcoord log by docker logs milvus-rootcoord, no log returned.

Below is a screenshot to show Milvus status, this test environment is retained for further investigation
![image](https://user-images.githubusercontent.com/67673717/211755409-258467c9-0201-4686-823a-7d1d2baf3467.png)

Steps to fix this issue:
1. kvm platform admin logged in, locate the machine
2. Setting CPU instruction set to include: sse4_2, avx, avx512
3. Reboot machine, and logged in with user credential
4. Retry Milvus deployment, and now it is running

### Expected Behavior

When I create Milvus cluster on a machine with unsupported CPU instruction set, error should print to point out that CPU instruction set is not supported by Milvus.

**Comment by yanliang567** [comment]
/assign @liliu-z 
we'd better print the simd not support error anyway.

/unassign

**Comment by liliu-z** [comment]
Fixed in Knowhere 1.3.7 with [commit](https://github.com/milvus-io/knowhere/pull/634
)

**Comment by xiaofan-luan** [comment]
@liliu-z did it merge to milvus 2.2.3 yet?

**Comment by liliu-z** [comment]
> @liliu-z did it merge to milvus 2.2.3 yet?

Yes, @cydrain  plz double confirm on this

**Comment by yanliang567** [comment]
@john-h-luo please help to verify and close the issue.
/assign @john-h-luo 
/unassign

**Comment by liliu-z** [comment]
https://github.com/milvus-io/knowhere/pull/607 should be merged. Plz let me know if it doesn't work
