### ISSUE TITLE
Some questions in doc

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#2165]
Q1:
link: https://milvus.io/cn/docs/v0.8.0/guides/index.md
![image](https://user-images.githubusercontent.com/53512883/80456224-d06e2800-895f-11ea-8561-d41418e629c2.png)

Q2:
link:https://milvus.io/cn/docs/v0.8.0/guides/index.md
![image](https://user-images.githubusercontent.com/53512883/80456315-f7c4f500-895f-11ea-9efd-28dbd84c7bbc.png)

Q3:
link:https://milvus.io/cn/docs/v0.8.0/guides/troubleshoot.md#%E7%B4%A2%E5%BC%95%E5%BB%BA%E7%AB%8B%E6%93%8D%E4%BD%9C
![image](https://user-images.githubusercontent.com/53512883/80456348-04494d80-8960-11ea-9149-e17a092ef36d.png)

Q4:
link:https://milvus.io/cn/docs/v0.8.0/reference/milvus_config.md#%E9%85%8D%E7%BD%AE%E6%A6%82%E8%BF%B0
![image](https://user-images.githubusercontent.com/53512883/80456382-10cda600-8960-11ea-8e76-6a95ba5949d2.png)

**Comment by shengjun1985** [comment]
Done
