### ISSUE TITLE
[Bug]: Get Segment Info with log id but not log path

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#21692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

See #21657

one thing we could do is to compress all segments.
the other thing we could do is to return []*SegmentInfo  with only logID and no log path, this will decrease each SegmentInfo size a lot (From 100KB + to less than 10K).
The last thing we can do is returning infos without log path only.  most cases we should not get SegmentInfo in a batch but should only maintain it's ids.

**Comment by xiaofan-luan** [comment]
Anyone interested pls take it

**Comment by cxorm** [comment]
Hi @xiaofan-luan,
I'm interested in this issue,
Could I take it if you don't mind?
