### ISSUE TITLE
[Bug]: gogo/protobuf is deprecated

### ISSUE THREAD

**Issue by weiliu1031** [milvus-io/milvus#21708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

milvus has imported the dependency [`gogo/protobuf`](https://github.com/gogo/protobuf), which has been deprecated,  it is not compatible with all brand new golang protobuf features.

![image](https://user-images.githubusercontent.com/108661493/212263158-7b369309-8051-47a7-9306-8bc6118dd928.png)

more details: https://github.com/apache/pulsar-client-go/issues/862

**Comment by yanliang567** [comment]
any updates?
