### ISSUE TITLE
return vectors with search result

### ISSUE THREAD

**Issue by sunyaofei** [milvus-io/milvus#2171]
**Is your feature request related to a problem? Please describe.**
0.8.0 support getVectorById, but need second query, thus effecting whole throughput

**Describe the solution you'd like**
return vectors with search result if need

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by tinkerlin** [comment]
The feature you need is `SearchByID`, this will be support in 0.9.0.
Refer to roadmap [https://github.com/milvus-io/milvus/projects](url)

**Comment by sunyaofei** [comment]
> The feature you need is `SearchByID`, this will be support in 0.9.0.
> Refer to roadmap [https://github.com/milvus-io/milvus/projects](url)

i need matched vector returned when search topk(now, only ids and distance returned).
Can `SearchByID` satisfy this case ?

**Comment by sunyaofei** [comment]
> > The feature you need is `SearchByID`, this will be support in 0.9.0.
> > Refer to roadmap [https://github.com/milvus-io/milvus/projects](url)
> 
> i need matched vector returned when search topk(now, only ids and distance returned).
> Can `SearchByID` satisfy this case ?

i find the same issue, thx @tinkerlin 
https://github.com/milvus-io/milvus/issues/1751

**Comment by yhmo** [comment]
SearchByID was disabled by milvus plan meeting. The reason is user can call search to get result id and then use get_entity_by_id to get vector data.
