### ISSUE TITLE
[Bug]: The data disappears from the object store without ttl

### ISSUE THREAD

**Issue by bingbb47** [milvus-io/milvus#21731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.2 
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

After about one day of inserting data, the data in the object storage begins to disappear gradually. First, press the partition folder to disappear, and finally the insert_log and stat_log of the collection has disappeared. But the segment metadata still exists in etcd.
The bucket has no lifecycle set，and the collection has no ttl set.

### Expected Behavior

skip

### Steps To Reproduce

```markdown
skip
```

### Milvus Log

[milvuslog0116.tar.gz](https://github.com/milvus-io/milvus/files/10422290/milvuslog0116.tar.gz)
[bw_etcd_ALL.230116-110344.bak.gz](https://github.com/milvus-io/milvus/files/10422295/bw_etcd_ALL.230116-110344.bak.gz)

**Comment by congqixia** [comment]
Hi @bingbb47 thanks for the issue.
Found these lines from the log file you provide:
```
# milvus-datacoord.geek-blue-recall-v2-27hx9.log
11646:[2023/01/16 00:17:44.342 +00:00] [INFO] [datacoord/garbage_collector.go:198] ["scan file to do garbage collection"] [total=0] [valid=0] [missing=0] [removedKeys="[]"]
24548:[2023/01/16 01:17:44.247 +00:00] [INFO] [datacoord/garbage_collector.go:198] ["scan file to do garbage collection"] [total=0] [valid=0] [missing=0] [removedKeys="[]"]
```
It looks like in the time range in the logs files, the binlog files is already gone. Is there any chance that you could provide the log before? Maybe the log during the files appears to be missing?

**Comment by congqixia** [comment]
BTW what Object store are you using actually?

**Comment by Cheung7788** [comment]
s3

**Comment by yanliang567** [comment]
/assign @congqixia 

@Cheung7788 could you please check the audit logs from s3 to check the logs of removing these objects from s3?

**Comment by bingbb47** [comment]
> Hi @bingbb47 thanks for the issue. Found these lines from the log file you provide:
> 
> ```
> # milvus-datacoord.geek-blue-recall-v2-27hx9.log
> 11646:[2023/01/16 00:17:44.342 +00:00] [INFO] [datacoord/garbage_collector.go:198] ["scan file to do garbage collection"] [total=0] [valid=0] [missing=0] [removedKeys="[]"]
> 24548:[2023/01/16 01:17:44.247 +00:00] [INFO] [datacoord/garbage_collector.go:198] ["scan file to do garbage collection"] [total=0] [valid=0] [missing=0] [removedKeys="[]"]
> ```
> 
> It looks like in the time range in the logs files, the binlog files is already gone. Is there any chance that you could provide the log before? Maybe the log during the files appears to be missing?


[log_datacoord.tar.gz](https://github.com/milvus-io/milvus/files/10423362/log_datacoord.tar.gz)

**Comment by bingbb47** [comment]
If the problem is caused by gc, I want to know what the trigger condition is and how to avoid it

**Comment by bingbb47** [comment]
> 你好@bingbb47谢谢你的问题。 从您提供的日志文件中找到这些行：
> 
> ```
> # milvus-datacoord.geek-blue-recall-v2-27hx9.log
> 11646:[2023/01/16 00:17:44.342 +00:00] [INFO] [datacoord/garbage_collector.go:198] ["scan file to do garbage collection"] [total=0] [valid=0] [missing=0] [removedKeys="[]"]
> 24548:[2023/01/16 01:17:44.247 +00:00] [INFO] [datacoord/garbage_collector.go:198] ["scan file to do garbage collection"] [total=0] [valid=0] [missing=0] [removedKeys="[]"]
> ```
> 
> 看起来在日志文件的时间范围内，binlog文件已经消失了。你有没有机会提供之前的日志？也许文件期间的日志似乎丢失了？

I get it ! there is another discarded cluster use the same bucket, i can find "garbage_collector" log in that datacoord. I think this may be the reason for data loss

**Comment by xiaofan-luan** [comment]
~~
Use the same bucket is ok, but be sure to use separate root path otherwise the A cluster will GC files in B Cluster

**Comment by bingbb47** [comment]
> ~~ Use the same bucket is ok, but be sure to use separate root path otherwise the A cluster will GC files in B Cluster

This is my fault. Thank you for your help, i think i can close the issue~
