### ISSUE TITLE
[Bug]: S3 file write but can not be read

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#21760]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

<img width="1681" alt="image" src="https://user-images.githubusercontent.com/83447078/212805382-92d296a8-81af-4927-853d-438169838e76.png">

On bulkload, one datanode returned new binlog created, but the loader datanode report file not found.
I doubt this is a s3 issue, but S3 should support read after read consistency

**Comment by jaime0815** [comment]
S3 has already supported a strong consistency mode, but it still looks like an eventual consistency mode. https://aws.amazon.com/s3/consistency/

**Comment by xiaofan-luan** [comment]
> S3 has already supported a strong consistency mode, but it still looks like an eventual consistency mode. https://aws.amazon.com/s3/consistency/

weird, does it enable by default?
