### ISSUE TITLE
[Bug]: After standby rootcoord activated, the service can still not recover 

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#21777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230117-f081c3c6
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):Plusar    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/212858761-e3184edd-7424-4b1c-b52a-05b93fabbf48.png)

In the following picture, we can know that the standby rootcoord activated, but many services still failed as we can see in the above picture 
![image](https://user-images.githubusercontent.com/12268675/212859417-b0ffaf6a-15c4-4f02-8f20-714c4f910cdb.png)

### Expected Behavior

After standby rootcoord is activated, the services can recovery

### Milvus Log

chaos type: pod-failure image tag: 2.2.0-20230117-f081c3c6 target pod: rootcoord

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/standby_test/detail/standby_test/144/pipeline
log:
[artifacts-rootcoord-pod-failure-144-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/10433388/artifacts-rootcoord-pod-failure-144-server-logs.1.tar.gz)

[artifacts-rootcoord-pod-failure-144-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10433390/artifacts-rootcoord-pod-failure-144-pytest-logs.tar.gz)

### Anything else?

It is not a stable issue. This job is a success, https://qa-jenkins.milvus.io/blue/organizations/jenkins/standby_test/detail/standby_test/145/pipeline

And here is another issue, the activated rootcoord before which has been injected pod failure chaos, after the chaos is deleted, the pod can not recover.
![image](https://user-images.githubusercontent.com/12268675/212861314-b3238487-a8d4-406c-b8aa-def121991c75.png)

![image](https://user-images.githubusercontent.com/12268675/212861217-d6a6eec9-2a4a-4f5a-aa82-50622f935145.png)

**Comment by zhuwenxing** [comment]
/assign @wayblink 
Please take a look

**Comment by wayblink** [comment]
@zhuwenxing please help check whether it still exists

**Comment by zhuwenxing** [comment]
Verified and passed
