### ISSUE TITLE
[Bug]: index creation time is similar with  index_node 2*16C or 6*16C on 10m dataset

### ISSUE THREAD

**Issue by changhong52** [milvus-io/milvus#21786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:  2.2.0
- Deployment mode(standalone or cluster):  cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):  V2.2.0
- OS(Ubuntu or CentOS):  Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

index_node 2*16C与6*16C创建1000W索引耗时几乎相同，并没有明显的缩短时间file:///Users/admin/Library/Application%20Support/LarkShell/OptimizeImage/a74b2151-901e-48ec-99ed-b93b0309e0ba.jpeg
file:///Users/admin/Library/Application%20Support/LarkShell/sdk_storage/1362341e5cc5a4e9334aafee668cdc9d/resources/images/BQBfM5VHgA.jpg

### Expected Behavior

加了4个index_node期望时间缩短至少一倍

### Steps To Reproduce

```markdown
1生产环境批量插入1000W数据创建索引
2index_node 2*16C与6*16C创建1000W索引耗时几乎相同，并没有明显的缩短时间
```

**Comment by yanliang567** [comment]
@changhong52 Could you please export the full Milvus logs for investigation, referring this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log).


/assign @changhong52

**Comment by changhong52** [comment]
[index.log](https://github.com/milvus-io/milvus/files/10442604/index.log)
所有index日志

**Comment by xiaofan-luan** [comment]
@changhong52 
from the log you offered(Only one indexnode) , the index build time is not very busy.(Only worked at 03:38 and 02:38) and it only has one segment to work with.
Could you share what is the expecting index build time you are looking for and the data size?
