### ISSUE TITLE
[Bug]: The etcd of the stand-alone version of milvus cannot be started

### ISSUE THREAD

**Issue by RongHouchao** [milvus-io/milvus#21780]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.4
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):  pulsae
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The etcd service exited and could not be started

![image](https://user-images.githubusercontent.com/117245915/213060433-8785ad4e-2896-4f5b-8e40-a1e5896d7d55.png)

### Expected Behavior

Etcd service starts normally

### Steps To Reproduce

```markdown
Occasionally, we don't know the conditions
```

### Milvus Log

![image](https://user-images.githubusercontent.com/117245915/213060598-694f41b2-19fc-4bc6-950f-bc104b4ca473.png)

**Comment by xiaofan-luan** [comment]
seems to be similar to https://github.com/etcd-io/etcd/issues/11444 but there is no fix on it

**Comment by RongHouchao** [comment]
能解决吗？我们在遇到了这个问题，比较急

**Comment by RongHouchao** [comment]
复现条件是什么，要怎样规避这个问题呢

**Comment by xiaofan-luan** [comment]
Not an expert on etcd, is this a production environment? 
I can go through the code really quick, but I've no idea if can be fixed.
how did you deploy the etcd? at least 2 of the other etcd could work?

**Comment by RongHouchao** [comment]
是生产环境，受限于客户现场的资源，目前都是部署的单机版的，目前已经无法提供服务了，有恢复的手段么？比较急，可以电话联系么，感谢

**Comment by RongHouchao** [comment]
是生产环境，受限于客户现场的资源，目前都是部署的单机版的，目前已经无法提供服务了，有恢复的手段么？比较急，可以电话联系么，感谢

**Comment by xiaofan-luan** [comment]
pls contact me at xiaofan.luan@zilliz.com

Seems the data file corrupted, is there a way to reimport data?

**Comment by xiaofan-luan** [comment]
if the etcd data directory is not large pls also copy one and we can investigate on the laptop

**Comment by RongHouchao** [comment]
What data is stored in the etcd?

What do you mean by data re-import is a complete set of operations such as unloading and reloading milvus, then rebuilding the collection and partition, and then re-importing vector data.

I want to know the conditions for this problem and the measures to avoid it in the future.

**Comment by RongHouchao** [comment]
We are currently deployed in the customer's environment, and the customer is very sorry for not allowing it to be exported.

If you export the data again, can you just rebuild the etcd? Is there any way to restore vector data directly? Or do vector data have to be imported again?

**Comment by xiaofan-luan** [comment]
> 
 
@LoveEachDay @xiaofan-luan @jaime0815 
Let's go through the code and see how we can recover

**Comment by xiaofan-luan** [comment]
> We are currently deployed in the customer's environment, and the customer is very sorry for not allowing it to be exported.
> 
> If you export the data again, can you just rebuild the etcd? Is there any way to restore vector data directly? Or do vector data have to be imported again?

Did you do any operation on this cluster? such as reboot or upgrade?

**Comment by RongHouchao** [comment]
After restarting, etcd still doesn't get up. Then I stopped operating the cluster and made a bug request.

**Comment by xiaofan-luan** [comment]
![img_v2_8a56735e-4a32-479b-9fd5-dd64645fc77g](https://user-images.githubusercontent.com/83447078/213072331-2fb94efc-39e4-4e7c-84ef-703c5b7ff0a5.jpg)

![img_v2_27397217-d3b4-4f4e-801d-8be21895596g](https://user-images.githubusercontent.com/83447078/213072365-9b9d2210-60b4-4ebb-a1d5-e697a83c96d4.jpg)

**Comment by jaime0815** [comment]
@RongHouchao can you send me your WeChat or phone number to accelerate solve this problem?  my email is yun.zhang@zilliz.com

**Comment by RongHouchao** [comment]
OK, the customer is pressing. I redeploy and then import the data, but I backed up the previous volumes directory. I send you private email.

**Comment by jaime0815** [comment]
related to https://github.com/etcd-io/etcd/issues/15140

**Comment by xiaofan-luan** [comment]
we should probably upgrade to 3.5.6 also
