### ISSUE TITLE
[Enhancement]: Upgrade Etcd client and server to 3.5.5

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#21796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

etcd 3.5.5 has been released for more than 6 months and it seems to be a pretty stable version.
We should consider upgrade etcd server and our dependency to 3.5.5 version

**Comment by LoveEachDay** [comment]
Ok, we'll trigger a stability test for etcd 3.5.5 and try to catch up 2.2.3 release.

**Comment by LoveEachDay** [comment]
We've already upgrade etcd version to v3.5.5 since milvus version v2.2.3.
