### ISSUE TITLE
[QUESTION] 请问最新的镜像要cuda10.1才能支持吗?

### ISSUE THREAD

**Issue by Masterchenyong** [milvus-io/milvus#218]
**What is your question?**
请问最新的镜像要cuda10.1才能支持吗？

**Comment by JinHai-CN** [comment]
The latest docker image don't need cuda, but nvidia-driver: 418 or higher
Please refer to: https://milvus.io/docs/en/userguide/install_milvus/

But, if you want to compile Milvus, CUDA is necessary. Currently, we suggest you to compile it under CUDA 10.1.
