### ISSUE TITLE
[Enhancement]: Milvus Operator Documentation

### ISSUE THREAD

**Issue by filip-halt** [milvus-io/milvus#21803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

The development of the Milvus operator has changed things a bit. Finding the correct info is now a bit confusing. For example, if trying to deploy a cluster using the operator and an S3 backend, figuring out how to do it is very difficult. 

One might first look [here](https://milvus.io/docs/object_storage_operator.md). 

<img width="671" alt="image" src="https://user-images.githubusercontent.com/81822489/213308032-a4570f7b-24e2-4fa7-9dc4-2a87b0d7b03d.png">

Unfortunately this page doesnt really tell you what you need to do to install the operator. You are missing the ability to add the bucket, user_id, etc.

Since the previous page doesnt help, the next place one might go is to check is [here](https://milvus.io/docs/configure_operator.md). 

<img width="793" alt="image" src="https://user-images.githubusercontent.com/81822489/213308339-69b802c0-cb53-4f44-8975-822bd2e01b68.png">

This helps a little, but also confuses the users. S3 falls under minIO and in this guide, the minio components fall under the dependency category. This still doesnt tell you the right solution. 

Finally you search the operator repo for instances of 's3' and find this [file](https://github.com/milvus-io/milvus-operator/blob/44e709e6214de4afdc4d889f53602643d5789709/config/samples/milvus_s3.yaml)

<img width="620" alt="image" src="https://user-images.githubusercontent.com/81822489/213308552-92e77e49-0b19-441d-a9ac-d33426b8a7b5.png">

Here you finally find out how to use the config, and realize that the first link wasnt enough info, the second link said to put minio configs under `dependencies` which was wrong as it has to be under config. How is one supposed to figure this out?

### Why is this needed?

Simplified and complete guide to milvus-operator. Needs to begin with all the examples we [here](https://github.com/milvus-io/milvus-operator/tree/44e709e6214de4afdc4d889f53602643d5789709/config/samples), then show examples on how to change values in each system (coords, nodes, minio, pulsar, etc). We need to show code examples for modifying each one, not just a generic template like this: 
<img width="746" alt="image" src="https://user-images.githubusercontent.com/81822489/213309144-91b436c4-814e-4e61-8af2-0db7d0bf56c9.png">

The page on setting up external object storage doesnt actually tell you how to completely. A lot of the instructions are spread out everywhere and make it near impossible to figure out.

**Comment by haorenfsa** [comment]
I'll update these docs about milvus-operator, it's ratther out of date. Sry for the inconvenience it caused.

**Comment by haorenfsa** [comment]
The Administration Guides have been updated in the milvus-operator repo: https://github.com/milvus-io/milvus-operator/tree/main/docs/administration .
It will be updated later to [milvus.io](https://milvus.io/docs) .
