### ISSUE TITLE
[Bug]: before bulkinsert, check json files with characters not in UTF8

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#21813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.2
- Deployment mode(standalone or cluster): cluster
```

### Current Behavior

fail to bulk insert for json files with characters not in UTF8, but the error msg is not clear
![image](https://user-images.githubusercontent.com/82361606/213369748-087ce9aa-b139-430c-93cb-7e5de88b4752.png)
![image](https://user-images.githubusercontent.com/82361606/213369798-3c204260-9878-4831-91ac-58351d2e84b6.png)

### Expected Behavior

a meaningful error msg to indicate users that there are some invalid characters in the json file

### Steps To Reproduce

```markdown
1. bulk insert json files with characters not in UTF8
```

**Comment by yanliang567** [comment]
/assign @yhmo  @zhuwenxing 
please help to improve the error msg and add some tests to cover these scenarios.

**Comment by yhmo** [comment]
"The format of JSON file does not meet the requirements" is not a message of milvus, neither server nor sdk.

**Comment by yelusion2** [comment]
This problem has been solved, because the user json file contains special characters, which has been fed back to the user.
So this is a user file problem, not a milvus kernel or cloud platform bug.
