### ISSUE TITLE
[Bug]: Batch insert failing due to gRPC max message rror

### ISSUE THREAD

**Issue by zstatmanweil** [milvus-io/milvus#21823]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.2
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.2.1
- OS(Ubuntu or CentOS): Centos
```

### Current Behavior

When I tried to batch insert 25K vectors with a DIM of 1024 using the python SDK (`collection.insert(entities, partition)`), I see this error:

```
RPC error: [batch_insert], <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.RESOURCE_EXHAUSTED
        details = "grpc: received message larger than max (106958108 vs. 67108864)"
        debug_error_string = "{"created":"@1674173193.112117362","description":"Error received from peer ipv4:3.13.139.190:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"grpc: received message larger than max (106958108 vs. 67108864)","grpc_status":8}"
>)>, <Time:{'RPC start': '2023-01-20 00:06:29.244246', 'RPC error': '2023-01-20 00:06:33.123518'}>
```

### Expected Behavior

I was able to insert the exact same data a couple weeks ago when I was on v2.2.0 and there wasn't an issue. 

### Milvus Log

[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/10462189/milvus-log.tar.gz)

### Anything else?

I am relatively new to Milvus and having trouble finding where the error is appearing in the logs. I have looked at the rootcoord, datacoord, datanode, and proxy. I also looked in the helm values file and I can't seem to find a place to increase grpc.clientMaxRecvSize and grpc.clientMaxSendSize. Even if I could, I am confused why previously I was able to insert these same entities and now it is failing.

**Comment by yah01** [comment]
Hi @zstatmanweil , we have added a RPC message size limit, which is 64MiB (https://github.com/milvus-io/milvus/pull/20844), to avoid system OOM caused by large RPC message.

**Comment by yanliang567** [comment]
/assign @zstatmanweil 
sounds like my design as comments above

**Comment by zstatmanweil** [comment]
Thank you for the explanation! I will close.

**Comment by xiaofan-luan** [comment]
> grpc.clientMaxRecvSize

it could be changed in Milvus.yaml.
But we highly suggest the rpc size not bigger than 256MB

**Comment by vellrya** [comment]
I've been collecting emedding for images for a few hours, but couldn't add them to the database because the program ended with an error and the result was lost.

> ERROR:pymilvus.decorators:RPC error: [batch_insert], <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
> 	status = StatusCode.RESOURCE_EXHAUSTED
> 	details = "grpc: received message larger than max (69056612 vs. 67108864)"
> 	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::1%5D:19530 {grpc_message:"grpc: received message larger than max (69056612 vs. 67108864)", grpc_status:8, created_time:"2023-06-22T20:25:28.954499479+00:00"}"
> )>, <Time:{'RPC start': '2023-06-22 23:25:25.436884', 'RPC error': '2023-06-22 23:25:28.964011'}>

I didn't know such a limit existed (I think, like many other new users), and the loss of data from hours of work is disappointing(

Wouldn't a better solution be to automatically split the large batches into smaller ones on the library side and insert them one by one, rather than throwing an error?

**Comment by xiaofan-luan** [comment]
> I've been collecting emedding for images for a few hours, but couldn't add them to the database because the program ended with an error and the result was lost.
> 
> > ERROR:pymilvus.decorators:RPC error: [batch_insert], <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
> > status = StatusCode.RESOURCE_EXHAUSTED
> > details = "grpc: received message larger than max (69056612 vs. 67108864)"
> > debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::1%5D:19530 {grpc_message:"grpc: received message larger than max (69056612 vs. 67108864)", grpc_status:8, created_time:"2023-06-22T20:25:28.954499479+00:00"}"
> > )>, <Time:{'RPC start': '2023-06-22 23:25:25.436884', 'RPC error': '2023-06-22 23:25:28.964011'}>
> 
> I didn't know such a limit existed (I think, like many other new users), and the loss of data from hours of work is disappointing(
> 
> Wouldn't a better solution be to automatically split the large batches into smaller ones on the library side and insert them one by one, rather than throwing an error?

You are right. We can definitely do better on this.
Opened a issue and wait for someone to take

**Comment by Diaboy01** [comment]
> > I've been collecting emedding for images for a few hours, but couldn't add them to the database because the program ended with an error and the result was lost.
> > > ERROR:pymilvus.decorators:RPC error: [batch_insert], <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
> > > status = StatusCode.RESOURCE_EXHAUSTED
> > > details = "grpc: received message larger than max (69056612 vs. 67108864)"
> > > debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::1%5D:19530 {grpc_message:"grpc: received message larger than max (69056612 vs. 67108864)", grpc_status:8, created_time:"2023-06-22T20:25:28.954499479+00:00"}"
> > > )>, <Time:{'RPC start': '2023-06-22 23:25:25.436884', 'RPC error': '2023-06-22 23:25:28.964011'}>
> > 
> > 
> > I didn't know such a limit existed (I think, like many other new users), and the loss of data from hours of work is disappointing(
> > Wouldn't a better solution be to automatically split the large batches into smaller ones on the library side and insert them one by one, rather than throwing an error?
> 
> You are right. We can definitely do better on this. Opened a issue and wait for someone to take

Problem still not solved, is it? :/
