### ISSUE TITLE
[Bug]: The p99 search latency is very high(more than one second) , while the average search latency is only 40 millisecond

### ISSUE THREAD

**Issue by linggong2011** [milvus-io/milvus#21832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The p99 search latency is very high(more than one second) , while the average search latency is only 40 millisecond

### Expected Behavior

The p99 search latency is less then 1 sec

**Comment by congqixia** [comment]
Hi @linggong2011 
Thanks for reporting this problem. I was wondering that if you could provide the the Milvus Version you were using?
And if there is any metrics (say Prometheus) it would be a great help if you could provide these metrics info.

**Comment by congqixia** [comment]
Also the logs during the high P99 performance might help as well.

**Comment by yanliang567** [comment]
@congqixia talking to @linggong2011 offline, he is using milvus 2.2.0. 
here is the logs
[logs.tar(1).gz](https://github.com/milvus-io/milvus/files/10477671/logs.tar.1.gz)
[bw_etcd_ALL.230123-055815.bak.gz](https://github.com/milvus-io/milvus/files/10477676/bw_etcd_ALL.230123-055815.bak.gz)

**Comment by yanliang567** [comment]
![image](https://user-images.githubusercontent.com/82361606/213989951-ff97abcf-69d9-4ed4-8c0d-d506120a52e6.png)
![image](https://user-images.githubusercontent.com/82361606/213989979-a4069024-1e1a-451b-ab65-028db8468867.png)
![image](https://user-images.githubusercontent.com/82361606/213990023-8f9d9e14-3b25-4ffb-b4e4-ee0dade9cfb4.png)

**Comment by yanliang567** [comment]
![image](https://user-images.githubusercontent.com/82361606/214024436-b33a4644-c799-43b2-914a-faadb23f1c24.png)
![image](https://user-images.githubusercontent.com/82361606/214024495-c426a8c3-d0f2-471b-ae2b-13ac4ff14ba5.png)

**Comment by liliu-z** [comment]
Looks like one of the pods has high latency. Since the pod is not shard leader and the latency from segcore is small, so suspect the problem is from queueing. 
We checked the task scheduler related params `Ready Read Task Length,  Unsolved Read Task Length,  Parallel Read Task Num,  Estimate CPU Usage`, all are normal for that pod.

**Comment by liliu-z** [comment]
The bad pod recovered, but another pod get bad with high latency, sounds like a transfer to me 
![20230123-210257](https://user-images.githubusercontent.com/105927039/214046553-33d6cf4f-5f04-4930-bafe-b0e225f5b91e.jpeg)
Check all other metrics, no big discrepancy found for this specific pod.

**Comment by xiaofan-luan** [comment]
might because of certain segment lack of index?

seems that the queueing latency is very high.

**Comment by yanliang567** [comment]
the issue occurs every 5:00am, so it is doubtful that it caused by some hardware resource or bussiness traffic.
today the user updated cup ration to 50, the performance improved a lot.
![img_v2_4cf461b9-ede0-42cb-8a60-a4b29daf846g](https://user-images.githubusercontent.com/82361606/215000178-8027b570-7d93-4c61-8af5-019b3a8599c0.jpg)

**Comment by yanliang567** [comment]
after discussion internal, we believe the root cause is the current nq comaction policy does not working well for  IVF_Flat. We agree to improve the policy for different index types. 
@liliu-z  will work on this improvement.
 /unassign

**Comment by liliu-z** [comment]
/assign @hhy3

We can kick off a standalone with IVFFlat to see if this is reproducible in-house.

**Comment by liliu-z** [comment]
Checked offline. Noticed that some CPU throttling occurred in the pod with high P99. 
User deploys their pod on a 64 vCPUs host, which leads to NUMA problem. We now highly suspect this is the root cause of the unpredictable P99.

**Comment by liliu-z** [comment]
Solve by changing host to 16 vCPU. OK to close

**Comment by yanliang567** [comment]
close as comments above
