### ISSUE TITLE
[Enhancement]: Add an option to ignore growing segment when search

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#21836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

1. Add an option in search to ignore growing segment, this helps to improve the search speed when insert while search. No consistency guarantee will be followed

### Why is this needed?

we've seen great performance regression when search && insert at the same time.
This would only be temporary solution, we will work on optimizing. growing segment search speed in the next release

**Comment by xiaofan-luan** [comment]
/assign @aoiasd 
pls help on it

**Comment by aoiasd** [comment]
completed
