### ISSUE TITLE
error find no available rootcoord

### ISSUE THREAD

**Issue by mjafar84** [milvus-io/milvus#21843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode- standalone 
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I have collection with 10 million record. When try to search some data from Attu tool error occured. After some investigation there is error like 'querycoord is offline'. I can't resolve the issue. I have removed containers  with 'docker compose down' and then up new service with existing volumes with old data. After that the following eror occured. 

[milvus2.1.2.log](https://github.com/milvus-io/milvus/files/10526836/milvus2.1.2.log)

### Expected Behavior

Want to succesfully start milvus and load collection to search data

### Milvus Log

[milvus2.1.2.log](https://github.com/milvus-io/milvus/files/10526836/milvus2.1.2.log)

**Comment by xiaofan-luan** [comment]
from the log you offered, everthing looks ok after on 8:57, previous error are just because service not started.
What is the latest error?
We strongly recommend you to use 2.2.2 as the latest version is much stable

**Comment by mjafar84** [comment]
@xiaofan-luan  thanks for recommendation. I will try upgrade if it will work. I have a lot of tries and test to solve the problem for 3 days. Each time different problem occurs. Actually I recreated the services with docker compose with old volume data. It started. (but not sure still if it is sucessfull running). Now I am loading collection for vector search. It still continues waiting to finish.  I doubt about loading because it never ends yesterday. I will write about result if any error occures. Thanks.

**Comment by mjafar84** [comment]
Still loading 1 collection. Already 2 hours passed. I can't see any warning or  error in log but it doesn't ends. Collection has 10 million rows. Server has 16 CPU and 48G RAM. what is the wrong????

**Comment by yanliang567** [comment]
maybe it is faster to re-deploy a new milvus 2.2.2 and re-insert the data.  @mjafar84

**Comment by mjafar84** [comment]
Actually I try to upgrade 2.1.2 to 2.2.0 with docker compose. My guide is this https://milvus.io/docs/upgrade_milvus_standalone-docker.md . As stated on step 1, I have stop all Milvus components with docker compose stop.. When I executed 3rd step following error occuured (try to connect etcd)                                                                       oot@milvus:/dbmilvus# docker run --rm -it --network milvus -v $(pwd)/migration.yaml:/milvus/configs/migration.yaml milvusdb/meta-migration:v2.2.0 /milvus/bin/meta-migration -config=/milvus/configs/migration.yaml
Cmd: run, SourceVersion: 2.1.2, TargetVersion: 2.2.0, BackupFilePath: /tmp/migration.bak, RunWithBackup: true
Type: etcd, EndPoints: [milvus-etcd:2379], MetaRootPath: by-dev/meta
[2023/01/29 11:18:37.809 +00:00] [DEBUG] [sessionutil/session_util.go:185] ["Session try to connect to etcd"]
{"level":"warn","ts":"2023-01-29T11:18:42.812Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0004f6540/#initially=[milvus-etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
[2023/01/29 11:18:42.813 +00:00] [DEBUG] [retry/retry.go:39] ["retry func failed"] ["retry time"=0] [error="context deadline exceeded"]
[2023/01/29 11:18:43.013 +00:00] [DEBUG] [sessionutil/session_util.go:185] ["Session try to connect to etcd"]
{"level":"warn","ts":"2023-01-29T11:18:48.017Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0004f6540/#initially=[milvus-etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup milvus-etcd: Try again\""}
[2023/01/29 11:18:48.418 +00:00] [DEBUG] [sessionutil/session_util.go:185] ["Session try to connect to etcd"]
{"level":"warn","ts":"2023-01-29T11:18:53.421Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0004f6540/#initially=[milvus-etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup milvus-etcd: Try again\""}
[2023/01/29 11:18:54.222 +00:00] [DEBUG] [sessionutil/session_util.go:185] ["Session try to connect to etcd"]
{"level":"warn","ts":"2023-01-29T11:18:59.223Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0004f6540/#initially=[milvus-etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup milvus-etcd: Try again\""}
[2023/01/29 11:19:00.824 +00:00] [DEBUG] [sessionutil/session_util.go:185] ["Session try to connect to etcd"]
{"level":"warn","ts":"2023-01-29T11:19:05.828Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0004f6540/#initially=[milvus-etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup milvus-etcd: Try again\""}
[2023/01/29 11:19:08.829 +00:00] [DEBUG] [sessionutil/session_util.go:185] ["Session try to connect to etcd"]
{"level":"warn","ts":"2023-01-29T11:19:13.834Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0004f6540/#initially=[milvus-etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup milvus-etcd: Try again\""}
[2023/01/29 11:19:16.836 +00:00] [DEBUG] [sessionutil/session_util.go:185] ["Session try to connect to etcd"]
{"level":"warn","ts":"2023-01-29T11:19:21.838Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0004f6540/#initially=[milvus-etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup milvus-etcd: Try again\""}
[2023/01/29 11:19:24.840 +00:00] [DEBUG] [sessionutil/session_util.go:185] ["Session try to connect to etcd"]
{"level":"warn","ts":"2023-01-29T11:19:29.845Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0004f6540/#initially=[milvus-etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup milvus-etcd: Try again\""}
[2023/01/29 11:19:32.847 +00:00] [DEBUG] [sessionutil/session_util.go:185] ["Session try to connect to etcd"]
{"level":"warn","ts":"2023-01-29T11:19:37.851Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0004f6540/#initially=[milvus-etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup milvus-etcd: Try again\""}
[2023/01/29 11:19:40.853 +00:00] [DEBUG] [sessionutil/session_util.go:185] ["Session try to connect to etcd"]
{"level":"warn","ts":"2023-01-29T11:19:45.854Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0004f6540/#initially=[milvus-etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup milvus-etcd: Try again\""}
[2023/01/29 11:19:48.856 +00:00] [DEBUG] [sessionutil/session_util.go:185] ["Session try to connect to etcd"]
{"level":"warn","ts":"2023-01-29T11:19:53.860Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0004f6540/#initially=[milvus-etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup milvus-etcd: Try again\""}
[2023/01/29 11:19:53.860 +00:00] [DEBUG] [retry/retry.go:39] ["retry func failed"] ["retry time"=10] [error="context deadline exceeded"]
[2023/01/29 11:19:56.862 +00:00] [DEBUG] [sessionutil/session_util.go:185] ["Session try to connect to etcd"]
{"level":"warn","ts":"2023-01-29T11:20:01.867Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0004f6540/#initially=[milvus-etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup milvus-etcd: Try again\""}
[2023/01/29 11:20:04.869 +00:00] [DEBUG] [sessionutil/session_util.go:185] ["Session try to connect to etcd"]
{"level":"warn","ts":"2023-01-29T11:20:09.873Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0004f6540/#initially=[milvus-etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup milvus-etcd: Try again\""}
[2023/01/29 11:20:12.876 +00:00] [DEBUG] [sessionutil/session_util.go:185] ["Session try to connect to etcd"]
{"level":"warn","ts":"2023-01-29T11:20:17.880Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0004f6540/#initially=[milvus-etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup milvus-etcd: Try again\""}
[2023/01/29 11:20:20.882 +00:00] [DEBUG] [sessionutil/session_util.go:185] ["Session try to connect to etcd"]
{"level":"warn","ts":"2023-01-29T11:20:25.886Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0004f6540/#initially=[milvus-etcd:23

**Comment by yanliang567** [comment]
/assign @LoveEachDay 
could you please help on this issue?

**Comment by john-h-luo** [comment]
@mjafar84 I'll help you upgrade milvus, let me know when you have time. Also join us on Slack for communication could accelerate the this process.

**Comment by mjafar84** [comment]
Thanks @john-h-luo . I have ignored the upgrade process for now. I have used volumes with new Milvus 2.2.2 installation. Everything seems OK. I didn't noticed any error on log file. Using Milvus CLI I have easily loaded collection to RAM for approxiamtely 3 minutes. With old version I can't load the loading process hang for hours and never ends. Now I have a problem with an Attu tool. When I have tried to connect to Milvus 2.2.2. The following error occured,  "Error: Error: 2 UNKNOWN: auth check failure, please check username and password are correct " It doesn't ask me user and password while trying to connect .... I have cleared all cache data and also check another browser. But result is same can't connect. For information I can login to Milvus with Milvus CLI with same user and password successfully which may already saved on cache for Attu browser login.

**Comment by john-h-luo** [comment]
Please check the version of attu, we have encountered similiar issue in previous versions checking user name and password, but those have been resolved in the latest version. For more information about attu, here's url for referencehttps://github.com/zilliztech/attu
