### ISSUE TITLE
[Bug]: querynode can't start, Get signal to exit

### ISSUE THREAD

**Issue by zhoudayu123** [milvus-io/milvus#21850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.2
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):  pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 4* 4Core/32G
- GPU: 
- Others:
```

### Current Behavior

I build independent etcd  and pulsar, and build milvus cluster with these external etcd and pulsar, querynode can not run success.
<img width="391" alt="image" src="https://user-images.githubusercontent.com/51695477/215308938-273f24fc-7c59-4b6a-8a6d-073c47573ea8.png">

<img width="530" alt="image" src="https://user-images.githubusercontent.com/51695477/215308797-e858c2dc-25b8-4b58-8185-d34b60cba762.png">

### Milvus Log

[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/10529166/milvus-log.tar.gz)
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/51695477/215308779-07085aac-031c-48cc-b8b2-1ca5d91a561a.png">

**Comment by yanliang567** [comment]
/assign @jiaoew1991 
it is wired that the logs of querynode shows the init status:
[2023/01/29 06:05:12.067 +00:00] [INFO] [querynode/service.go:216] ["**QueryNode init done** ..."]
[2023/01/29 06:05:18.744 +00:00] [DEBUG] [querynode/impl.go:72] ["Get QueryNode component state done"] [stateCode=Initializing]
...
[2023/01/29 06:05:28.745 +00:00] [DEBUG] [querynode/impl.go:72] ["Get QueryNode component state done"] [**stateCode=Initializing**]
[2023/01/29 06:05:28.746 +00:00] [DEBUG] [querynode/impl.go:72] ["Get QueryNode component state done"] [**stateCode=Initializing**]

/unassign

**Comment by congqixia** [comment]
According to the log, `querynode` stuck in the procedure of `Start`
Just checked the code, the most suspicious function call was `NewPersistentStorageChunkManager`
@zhoudayu123 I was wondering that if you could provided the information for the querynode storage?

**Comment by xiaofan-luan** [comment]
most likely this is a issue because of object storage is not setting up correctly .
are you using minio or S3?
check the following configs
<img width="1591" alt="image" src="https://user-images.githubusercontent.com/83447078/215422744-4b829118-120d-4d79-b7a9-6384d7bc3121.png">

guess that might be a access deny issue

**Comment by xiaofan-luan** [comment]
you can set the log level to warn and there will be a log why the init fail

**Comment by zhoudayu123** [comment]
Hi, @xiaofan-luan   Thank you for your reply, I use S3  for object storage, milvus configmap seems correct
<img width="414" alt="image" src="https://user-images.githubusercontent.com/51695477/215438467-3e9e87c6-6a98-489c-b633-ba9b62c9305c.png">


I set log level to warn, I still confused from querynode log .
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/51695477/215442181-7e4de522-ce2b-4377-ab59-83cae7f01b5f.png">

[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/10534364/milvus-log.tar.gz)

**Comment by xiaofan-luan** [comment]
So you follows https://github.com/milvus-io/milvus-operator/blob/main/docs/administration/manage-dependencies/object-storage.md#access-aws-s3-by-assumerole ? my guess is this is caused by S3 access denied

**Comment by jaime0815** [comment]
Are you sure IAM is available? you can try to access s3 with IAM into the Milvus pod or corresponding EC2. @zhoudayu123

**Comment by zhoudayu123** [comment]
when i build milvus with 2.1.4 version with independent etcd and pulsar， querynode works normally.
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/51695477/215466872-c9bd0653-56b3-4451-9b42-85e1c6bd3dab.png">
<img width="525" alt="image" src="https://user-images.githubusercontent.com/51695477/215466952-e4b0e80d-f955-4ed0-a1b3-14897f079c66.png">

**Comment by zhoudayu123** [comment]
i can access s3 in eks with other pod, i'm testing if access s3 in milvus pod.

**Comment by zhoudayu123** [comment]
Hi， @jaime0815  @xiaofan-luan   i can access s3 in milvus pod.
<img width="623" alt="image" src="https://user-images.githubusercontent.com/51695477/215469364-4c6843d5-c8d9-4110-a0f8-25602ce8ad3c.png">
it's weird that it works in 2.1.4 version but not in 2.2.2 version.

**Comment by zhoudayu123** [comment]
these two version has same configmap of minio(s3).

**Comment by xiaofan-luan** [comment]
might be related with #20823

**Comment by xiaofan-luan** [comment]
lscpu | grep -e sse4_2 -e avx -e avx2 -e avx512

**Comment by xiaofan-luan** [comment]
could you check if your cpu support avx512?
it might be related to avx issue, see https://github.com/milvus-io/milvus/issues/21649

**Comment by zhoudayu123** [comment]
<img width="791" alt="image" src="https://user-images.githubusercontent.com/51695477/216337055-a5f852ca-aa57-4200-a446-d503bba6e7e2.png">

**Comment by zhoudayu123** [comment]
@xiaofan-luan  Hi, anything new discoveries for this issue?   we will use 2.1.4 version for the worst, but i don't think it's a good solution, because latest version fixed more bugs and did some refactoring.

**Comment by john-h-luo** [comment]
@xiaofan-luan Yes, the last time when I encounter CPU instruction set issue, I've observed that all of the node couldn't start, by this case, some pods started successfully, and if all the pods are scheduled onto same node, it might not be related to that issue.

**Comment by john-h-luo** [comment]
I will look into it to determine if it is caused by S3 accessibility.

**Comment by zhoudayu123** [comment]
@john-h-luo  thanks for your reply, if you need some more information about it, please feel free to tell me.

**Comment by john-h-luo** [comment]
@zhoudayu123 Sure, I've looked into logs and configs of the pod, and I think at the moment we can rule out the possibility of either CPU instruction set or S3 inaccessibility, because here we have log indicating: "[2023/01/29 06:05:12.064 +00:00] [INFO] [storage/minio_chunk_manager.go:130] ["minio chunk manager init success."] [bucketname=mars6-prod-milvus] [root=]". My guessing is querynode might have component failed during initialing phase, I will have to seek some advice from co-worker, and get back to you very soon.

**Comment by john-h-luo** [comment]
@zhoudayu123 Are you using Helm install to create your Milvus cluster, if yes, could you share with me the helm vaules file you use to create it, it is ok to erase anything that's considered private information to you and your company.

**Comment by xiaofan-luan** [comment]
@cydrain 
Is there any logs show that knowhere is started successfully

**Comment by zhoudayu123** [comment]
Thanks for @john-h-luo  's help， it 's caused by s3 inaccessibility, i accessed s3 by set iam role in ec2 before, even though it can access s3 in pod, but it's not suitable for milvus.  it's correct way by set web-indentity type iam role and bind with eks service account.
steps:
1. get eks oidc(https://.....) by eks console.
2. new iam role which type is web-indentity, and add eks oidc last step into role truest entity.
3. set service account  bind with iam role last step by values.yaml

**Comment by locustbaby** [comment]
> face same issue

Hi @rusnov , would you mind showing some details to help you with it?
And also I'd like to invite you to join our slack only if you don't mind .
