### ISSUE TITLE
[Bug]:The node server is powered off and restarted，some collection search failure

### ISSUE THREAD

**Issue by hukang6677** [milvus-io/milvus#21867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.2
- Deployment mode(standalone or cluster):cluster(Helm)
- MQ type(rocksmq, pulsar or kafka):pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.2
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 256g
- GPU: 
- Others:
```

### Current Behavior

2/5000
some collection search failure

### Expected Behavior

collection search success

### Steps To Reproduce

```markdown
1.The node server is powered off and restarted (k8s-node01)
2.all collection loaded
3.some collection search failure (eg: CollectionName:vehicle_search_20221228)
```

### Milvus Log

[milvus_log1.tar.gz](https://github.com/milvus-io/milvus/files/10532958/milvus_log1.tar.gz)
[milvus_log2.tar.gz](https://github.com/milvus-io/milvus/files/10532963/milvus_log2.tar.gz)
[milvus_log6.tar.gz](https://github.com/milvus-io/milvus/files/10533020/milvus_log6.tar.gz)
[my-release-milvus-indexcoord-78c4947846-n4n4j.zip](https://github.com/milvus-io/milvus/files/10533214/my-release-milvus-indexcoord-78c4947846-n4n4j.zip)

**Comment by xiaofan-luan** [comment]
/assign @smellthemoon 

could you help on investigating?

**Comment by hukang6677** [comment]
[proxy_log1.tar.gz](https://github.com/milvus-io/milvus/files/10543579/proxy_log1.tar.gz)
[proxy_log2.tar.gz](https://github.com/milvus-io/milvus/files/10543584/proxy_log2.tar.gz)
[proxy_log3.tar.gz](https://github.com/milvus-io/milvus/files/10543586/proxy_log3.tar.gz)

**Comment by smellthemoon** [comment]
@hukang6677 Is this still the case after a while? It looks like a node restart caused querynode down, causing failed to search on shard and ShardNotAvailable error.

**Comment by hukang6677** [comment]
@yanliang567    proxy pod logs has attached

**Comment by yanliang567** [comment]
@hukang6677 Thanks for the logs. 
Looking into the logs, we found that the datanode does not watch the expected channel successfully, which caused the search requests keep waiting for the timetick sync up until timeout. 
`{"level":"WARN","time":"2023/01/30 03:36:45.784 +00:00","caller":"flowgraph/node.go:103","message":"some node(s) haven't received input","list":["nodeCtxTtChecker-dmInputNode-query-438321495194033264-by-dev-rootcoord-delta_5_438321495194033264v1","nodeCtxTtChecker-fdNode-by-dev-rootcoord-delta_5_438321495194033264v1","nodeCtxTtChecker-dmInputNode-query-438321495194033264-by-dev-rootcoord-delta_4_438321495194033264v0","nodeCtxTtChecker-fdNode-by-dev-rootcoord-delta_4_438321495194033264v0","nodeCtxTtChecker-stNode-by-dev-rootcoord-delta_4_438321495194033264v0","nodeCtxTtChecker-dNode-by-dev-rootcoord-delta_5_438321495194033264v1","nodeCtxTtChecker-stNode-by-dev-rootcoord-delta_5_438321495194033264v1","nodeCtxTtChecker-dNode-by-dev-rootcoord-delta_4_438321495194033264v0"],"duration ":"2m0s"}
`

Could you please try to search with consistency_level=eventual? check [here]([url](https://milvus.io/blog/understanding-consistency-levels-in-the-milvus-vector-database-2.md)) for more info about consistency level.
Furthermore, if that works for you, you can update the maxWatchDuration to 900 to ensure the watch channel operations not fail for timeout.
![image](https://user-images.githubusercontent.com/82361606/215933691-21ca7666-6558-423c-94a0-b60031f7b51e.png)

**Comment by xiaofan-luan** [comment]
how large is the dataset and how many shards is there? 

if each channel recover takes more than 60 seconds then that should be optimized

**Comment by hukang6677** [comment]
@xiaofan-luan
![image](https://user-images.githubusercontent.com/102129512/215957365-0e4864cb-d83c-4e2c-87bb-355d74bd2ee9.png)

**Comment by hukang6677** [comment]
@yanliang567 
.withConsistencyLevel(ConsistencyLevelEnum.EVENTUALLY)  
search still failed

**Comment by xiaofan-luan** [comment]
it's not a consistency issue. 
@smellthemoon any analysis?

**Comment by smellthemoon** [comment]
@hukang6677 Could you please attach the logs after changing the ConsistencyLevelEnum? Thanks.

**Comment by hukang6677** [comment]
@smellthemoon  the log is too large

**Comment by hukang6677** [comment]
@smellthemoon 
[datacoord_log1.tar.gz](https://github.com/milvus-io/milvus/files/10564488/datacoord_log1.tar.gz)
[datacoord_log0.tar.gz](https://github.com/milvus-io/milvus/files/10564489/datacoord_log0.tar.gz)

**Comment by smellthemoon** [comment]
> @smellthemoon
> [datacoord_log1.tar.gz](https://github.com/milvus-io/milvus/files/10564488/datacoord_log1.tar.gz)
> [datacoord_log0.tar.gz](https://github.com/milvus-io/milvus/files/10564489/datacoord_log0.tar.gz)

Thank you very much. This is the first log, but the second log is too big, so you haven't upload it, is that what your means?   It will be a great help if you can provide the log of the second time.

**Comment by smellthemoon** [comment]
@hukang6677 .Thanks!!! Look at  the log carefully, we can only see search requests waiting for the timetick sync up until timeout. The level of log is enabled at "Info" on the querynode, and we don’t know the details. You can dynamically set the log level, and then take a debug log to have a look.
