### ISSUE TITLE
[Bug]: migrate script users incorrect tag for image

### ISSUE THREAD

**Issue by filip-halt** [milvus-io/milvus#21877]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The migrate_pod image is using the incorrect year for the tag, resulting in pod pull failing. 

`meta_migration_pod_tag="milvusdb/meta-migration:v2.2.0-bugfix-20220112` 

needs to be:

`meta_migration_pod_tag="milvusdb/meta-migration:v2.2.0-bugfix-20230112`

https://hub.docker.com/r/milvusdb/meta-migration/tags

**Comment by yanliang567** [comment]
@LoveEachDay please help to review the pr #21876

**Comment by yanliang567** [comment]
closed for the pr merged
