### ISSUE TITLE
No logs dir generated using the latest images

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#2188]
**Describe the bug**
```
drwxr-xr-x 2 root root   4096 Apr 29 09:28 bin
drwxr-xr-x 2 root root   4096 Apr 29 09:28 conf
drwxr--r-- 3 root root   4096 Apr 29 10:41 db
-rwxr-xr-x 1 root root    116 Apr 29 09:28 docker-entrypoint.sh
drwxr-xr-x 2 root root   4096 Apr 29 09:28 lib
-rw-r----- 1 root root      0 Apr 29 10:39 lock
-rw-r--r-- 1 root root 126473 Apr 29 10:41 logsmilvus-20-04-29-18:39-debug.log
-rw-r--r-- 1 root root    474 Apr 29 10:41 logsmilvus-20-04-29-18:39-error.log
-rw-r--r-- 1 root root      0 Apr 29 10:39 logsmilvus-20-04-29-18:39-fatal.log
-rw-r--r-- 1 root root      0 Apr 29 10:39 logsmilvus-20-04-29-18:39-global.log
-rw-r--r-- 1 root root  99446 Apr 29 10:53 logsmilvus-20-04-29-18:39-info.log
-rw-r--r-- 1 root root   2772 Apr 29 10:41 logsmilvus-20-04-29-18:39-trace.log
-rw-r--r-- 1 root root   3619 Apr 29 10:41 logsmilvus-20-04-29-18:39-warning.log
drwxr-xr-x 1 root root   4096 Apr 29 10:39 scripts
drwxr-xr-x 2 root root   4096 Apr 29 10:41 wal
```
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by BossZou** [comment]
@del-zhenwu , this issue has been fixed in [PR2174](https://github.com/milvus-io/milvus/pull/2174), please double check.

**Comment by del-zhenwu** [comment]
fixed
