### ISSUE TITLE
[Enhancement]: Improve Milvus segment balance policy to shard aware

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#21888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Milvus current balance with RowCountBasedBalancer. 
It's actually balance channel by channel numbers, and balance sealed segment by count.

Current balancer must support three interface 
``` golang
AssignSegment(collectionID int64, segments []*meta.Segment, nodes []int64) []SegmentAssignPlan
AssignChannel(collectionID int64, channels []*meta.DmChannel, nodes []int64) []ChannelAssignPlan
Balance() ([]SegmentAssignPlan, []ChannelAssignPlan)
```

`AssignSegment` need to assign new segment to nodes, without changing exist segment distribution
`AssignChannel` need to assign new channel to nodes, without changing exist channel distribution
`Balance` try to optimize the overall balance status in the background globally, without moving too much segments(because moving is also a cost action).

Current balancer has some problems:
1) segment allocation didn't respect channel distribution, causing too many rpcs between shard leader and segment owner
2) didn't respect global segment distribution, if we have many collections an each collection owns one segment, then the system may totally unbalanced 

To simplify this question, we can name it as job distribution problem.

See if we have n different type of jobs, each job take a specified time todo. We are trying to assign m jobs to k workers,.
A good algorithm means:

1. all workers takes approximately similar time to finish the job 
2. it's better to assign same type of work to same worker because they can do a little bit faster than random assign.
3. jobs comes in batch, we have assign jobs as soon as possible, but we can transfer job between workers in the background. Of course, transfer takes extra time so you can not calculate optimal distribution each time and do swap.  

for example, we have two job types 1,2.
for 1, all jobs takes time [1, 1.2, 1.3, 1.5]
for 2, all jobs takes time [0.8, 1.2, 1.4, 1.6]

if we have three workers, the idea distribution would be:
worker 1 job1 [1, 1.2, 1.3]
worker 2 job1 [1.5]  job2 [1.6]
worker 1 job1 [0.8, 1.2, 1.4]

if we have four workers, the idea distribution would be:
worker 1 job1 [1, 1.5]
worker 2 job1 [1.2, 1.3]
worker 3 job2 [0.8, 1.6]
worker 4 job1 [1.2, 1.4]

if the job assign is not balanced, we can always balance it in the back ground, assume we have two workers

worker 1 job1 [1, 1.2] job2[0.8, 1.2]
worker 2 job1 [1.3, 1.5] job2[1.4, 1.6]

then swap worker1's 0.8 weight job with worker2's 1.6 weight job might be good idea.

assume if same type job run on same worker can gain 1.1x acceleration, balance between workers takes 0.2 * jobs weight

**Comment by yah01** [comment]
The cost of RPCs is $max(c_1, c_2, ...)$, either only one or more times RPCs won't make much performance diff, so we actually have only two strategies:
- Put all segments of the same channel together, then the algorithm just respects the nodes' capacity
- Deliver the segments depends on the nodes' load

**Comment by xiaofan-luan** [comment]
> The cost of RPCs is max(c1,c2,...), either only one or more RPCs won't make much performance diff, so we actually have only two strategies:
> 
> * Put all segments of the same channel together, then the algorithm just respects the nodes' capacity
> * Deliver the segments depends on the nodes' load

Don‘t quite understand what is c stands for?  max(c1,c2,...)

**Comment by yah01** [comment]
> > The cost of RPCs is max(c1,c2,...), either only one or more RPCs won't make much performance diff, so we actually have only two strategies:
> > 
> > * Put all segments of the same channel together, then the algorithm just respects the nodes' capacity
> > * Deliver the segments depends on the nodes' load
> 
> Don‘t quite understand what is c stands for? max(c1,c2,...)

$c_i$ means the cost(time taken) of $i^{th}$ RPC
