### ISSUE TITLE
[Bug]: [benchamrk]Milvus search, query and load latency keeps growing

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#21897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

We ran several sets of stability tests during the Chinese New Year holidays, and compared to the previous version, the latency of query, search, and load of milvus is higher 

#### Conclusion: The normal case is that the query and search latencies level off after a while, but now the query and search latencies keep growing 

 Here is a comparison of the latency of **v2.2.1** and **2.2.0-20230118-cae6d48f**
 
 1） 100m ivfsq8 
 client-random-locust-search-filter-100m-ddl-con
v2.2.1: (12h)
    query
    ![image](https://user-images.githubusercontent.com/48523564/215761827-c26ef583-7e67-4a2f-8f6a-5f534600ee7f.png)
    load_collection
![image](https://user-images.githubusercontent.com/48523564/215761954-972a5df2-feea-43df-adc0-db4b808c70e4.png)
   search
![image](https://user-images.githubusercontent.com/48523564/215762002-b13c53c3-e613-481c-9df9-4558337e39a0.png)
 scene_test(Insertion and deletion of a small table)
![image](https://user-images.githubusercontent.com/48523564/215762125-ee160fc9-0e57-4c60-aa70-ed4fffb2534b.png)

2.2.0-20230118-cae6d48f: (168 hours)
query
![image](https://user-images.githubusercontent.com/48523564/215762351-7b78c0f2-1efc-47a2-b350-d9fc6921654a.png)

load_collection
![image](https://user-images.githubusercontent.com/48523564/215762418-0834c823-d80f-4878-8b67-f4d298fbb8fb.png)

search 
![image](https://user-images.githubusercontent.com/48523564/215762457-40aadee4-b912-493a-a026-a8b49ba2726a.png)
scene_test
![image](https://user-images.githubusercontent.com/48523564/215762526-7210d2b6-f482-478a-a285-9a2e7e194955.png)
argo task: fouram-tag-no-clean-v94nb

---

Here is a comparison of the latency of **2.2.0-20221118-e7429f88** and **2.2.0-20230118-cae6d48f**

2) 100M  Ivfsq8 replica2  Cluster
v2.2.0  （2.2.0-20221118-e7429f88）: （60 hours）
query 
![image](https://user-images.githubusercontent.com/48523564/215929297-0c98c506-c45c-44f1-b4c1-784be75de5b5.png)

load_collection
![image](https://user-images.githubusercontent.com/48523564/215929353-5a188f4e-7299-4100-b977-e6939f7d2a9a.png)
search 
![image](https://user-images.githubusercontent.com/48523564/215929424-7cbdb726-240e-4ace-b9ce-51f8b43e88db.png)
scene_test
![image](https://user-images.githubusercontent.com/48523564/215929445-db08bd60-6429-4a20-92ea-e424033aa17a.png)

2.2.0-20230118-cae6d48f: (168 hours)
query:
![image](https://user-images.githubusercontent.com/48523564/215929538-d32a655c-6ab4-4d3b-becf-33699906059a.png)

load_collection
![image](https://user-images.githubusercontent.com/48523564/215929576-7e9815de-48c1-4265-9389-dc2adc638383.png)
search 
![image](https://user-images.githubusercontent.com/48523564/215929622-46ac6437-752a-4c8a-b75d-3d05cdcf2a9f.png)
scene_test
![image](https://user-images.githubusercontent.com/48523564/215929695-ea62da49-a809-4d6d-9028-44815d16c7b4.png)

argo task: fouram-tag-no-clean-8pt9c

**Comment by xiaofan-luan** [comment]
what does all the diagram mean?

**Comment by xiaofan-luan** [comment]
can you make a form to make the comparison? also the monitoring metrics looks weird, why is it keep increasing?

**Comment by xiaofan-luan** [comment]
rt_ms should be ralatively a stable value

**Comment by elstic** [comment]
> what does all the diagram mean?

@xiaofan-luan  I added to the issue . The normal situation is that the query and search latency level off after a while, but now the query and search latency keeps growing

**Comment by elstic** [comment]
> can you make a form to make the comparison? also the monitoring metrics looks weird, why is it keep increasing?

Yes, I'll put together a table comparing the latency gap between the most recent release and version 2.2.0-20230118-cae6d48f later

**Comment by elstic** [comment]
> > can you make a form to make the comparison? also the monitoring metrics looks weird, why is it keep increasing?
> 
> Yes, I'll put together a table comparing the latency gap between the most recent release and version 2.2.0-20230118-cae6d48f later

#### I compare the differences between version 2.2.0 and the current version 2.2.3 because the data in version 2.2.0 is more complete
 
 v2.2.0 latency：

interface | query | search | load_collection
-- | -- | -- | --
100M IVF_SQ8 replica2 Cluster | Stable at 0.02s | Stable at 0.11s | Stable at 0.06s
100M IVF_SQ8 DQL&DDL Standalone | Average latency less than 0.05s | Average latency less than 0.1s | Average latency less than 0.10s

2.2.0-20230118-cae6d48f latency：

interface | query | search | load_collection
-- | -- | -- | --
100M IVF_SQ8 replica2 Cluster | Delayed maximum arrival time: 0.58 seconds, and also shows an upward trend | Delayed maximum arrival time: 0.42 seconds, and also shows an upward trend | Delayed maximum arrival time: 3.35 seconds, and also shows an upward trend
100M IVF_SQ8 DQL&DDL Standalone | Delayed maximum arrival time: 0.978 seconds, and also shows an upward trend | Delayed maximum arrival time: 0.693 seconds, and also shows an upward trend | Delayed maximum arrival time: 3.457 seconds, and also shows an upward trend

hnsw Index latency is also increased, but it is not listed here


@xiaofan-luan  @jiaoew1991

**Comment by liliu-z** [comment]
@jingkl Is this from the same test you mentioned?

**Comment by liliu-z** [comment]
@elstic does it happen to IVFSQ8 only?

**Comment by elstic** [comment]
> @elstic does it happen to IVFSQ8 only?

@liliu-z  The hnsw index also exists, but it doesn't have the same scenario as 2.2.0, so I didn't add it. I'll add the latest delay of 2.2.3

**Comment by liliu-z** [comment]
> > @elstic does it happen to IVFSQ8 only?
> 
> @liliu-z The hnsw index also exists, but it doesn't have the same scenario as 2.2.0, so I didn't add it. I'll add the latest delay of 2.2.3

Do any other indexes get tested? 
We don't need to make a comparison. Once the latency keeps growing, there should be a problem.
And if all indexes get tested performed the same way, this problem can be narrowed down to Milvus' side

**Comment by elstic** [comment]
> Do any other indexes get tested? We don't need to make a comparison. Once the latency keeps growing, there should be a problem. And if all indexes get tested performed the same way, this problem can be narrowed down to Milvus' side

Our stability test ran both hnsw and ivf_sq8 indexes and both have this phenomenon, the latency continues to increase

**Comment by elstic** [comment]
@xiaofan-luan All indexes (hnsw, ivf_sq8) have delayed growth when we run stability, liliu-z think it's a problem on the milvus side, can you help evaluate it?

**Comment by soothing-rain** [comment]
> @xiaofan-luan All indexes (hnsw, ivf_sq8) have delayed growth when we run stability, liliu-z think it's a problem on the milvus side, can you help evaluate it?

Will take a look at.

**Comment by soothing-rain** [comment]
Also happened in our stability test. The test ran from Jan 18th to Jan 25th. However GC stopped after Jan 19th:
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/69466447/216315417-3376b3d8-6597-4eb4-be26-0106cc7d0bc8.png">

It seems that channel `channelCpTs` is `0`, causing GC to be skipped under the new constraint: https://github.com/milvus-io/milvus/pull/21773

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/69466447/216316108-54ab4ad6-3952-4f48-81bf-21840c0a8c2f.png">

We will try reproduce this scenario and find out what happened there.

**Comment by xiaofan-luan** [comment]
good catch team!

**Comment by soothing-rain** [comment]
What happened:

1) There's a new restriction on GC that if a segment DML position is ahead of channel checkpoint, it will not get GCed. #21773
2) There are a few bugs on channel checkpoints, causing segments not being able to get GCed because of (1).
3) There's a restriction that if segments are not GCed, it's collection's meta data won't get cleaned. #21671. Causing all collections to remain in meta data.


BUGs identified including:
1) (fixed) Channel checkpoints are updated every 60 seconds. However segment DML pos are updated more frequently. There's a case when a segment DML pos gets updated but channel checkpoint is not update. When drop collection happen at this point, the channel's CP will be behind segment DML pos forever.
2) (working on) During deletion, segment's historical deletebuffer is evicted during flush , but not evicted when collection is dropped. As a result, the channel's checkpoint will stay in deletebuffer's position forever.
3) (fixed) In spite of 1) and 2), I seriously worried that there could be more potential bugs to causes channel CP to stay behind, which would block a channel's segment GC forever. A safer solution is to check if the vchannel is dropped during GC. And do not block GC if a vchannel is dropped.
4) (fixed) Channel's checkpoint is cleaned up when flow graph is dropped, so during GC, all channel checkpoints we retrieved are 0.

**Comment by yanliang567** [comment]
@soothing-rain @xiaofan-luan can we improve the restriction 1 and 3 with an async task? e.g. if there is no linked collection meta, do cleanup.

**Comment by elstic** [comment]
Verified, fixed, latency no longer growing

**Comment by elstic** [comment]
fix version:2.2.3

**Comment by xiaofan-luan** [comment]
@elstic why is the search latency keep growing? Since only GC is related.

**Comment by yanliang567** [comment]
does it because more time cost and frequency of stop-the-world? @soothing-rain could you please share more info about this issue?

**Comment by soothing-rain** [comment]
The most recent guess is that the latency did not actually grew in the original issue. Larger latency was spotted because the pymilvus is congested as other API calls (like DescribeCollections) became much slower due to this issue.

We will take a deep look at it in issue https://github.com/milvus-io/milvus/issues/22068
