### ISSUE TITLE
[Enhancement]: Control Garbage Collection's Capability range over S3 deletion

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#21928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Make datacoord only able to delete meta that contains key in its control. So that 2 Milvus won't delete each other's data in S3 by mistake.

For example, in MilvusA, datacoordA controls `collA, collB, shardC1, shardC2, shardC3, partitionD1, partitionD2, partitionD3`.

Then this datacoordA can only remove meta with keys that MUST contain `one of collA or collB`, `one of shardC1, shardC2, or shardC3`, `one of partitionD1, partitionD2 or partitionD3`.

**Comment by xiaofan-luan** [comment]
we should thinking of changing the S3 path

[log_type]/collID/partID/segID/fieldID/fileName

I'm actucally thinking of change to

2bytehash(collID) /[log_type]/collID/partID/segID/fieldID/fileName

when we do garbage collection, we iterate through all collections from etcd, and for each etcd we iterate by 1bytehash(collID) /[log_type]/collID.

The reason I want to change:
1) hash help to distributed file to different S3 prefix.
2) Milvus only cleanup collID belongs to this cluster
3) do garbage collection concurrently by the hash value

**Comment by vishalkanaujia** [comment]
I am interested in working on it. Could you please assign it to me?

**Comment by congqixia** [comment]
As for 2.3 and 2.2.x  we shall implement a simple strategy to prevent data loss. That is to only delete files in records.
