### ISSUE TITLE
[Bug]: [Nightly]Search with shards_num 63 lost data

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#21922]
## Environment
- Milvus version: 5d5a04d
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.0.dev26
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: 

## Current Behavior:
Search with shards_num 63 lost data.
case:
```python
@pytest.mark.tags(CaseLabel.L2)
    @pytest.mark.parametrize("shards_num", [-256, 0, 1, 10, 31, 63])
    def test_search_with_non_default_shard_nums(self, auto_id, shards_num, _async):
        """
        target: test search with non_default shards_num
        method: connect milvus, create collection with several shard numbers , insert, load and search
        expected: search successfully with the non_default shards_num
        """
        self._connect()
        name = cf.gen_unique_str(prefix)
        collection_w = self.init_collection_wrap(name=name, shards_num=shards_num)
        dataframe = cf.gen_default_dataframe_data()
        collection_w.insert(dataframe)
        collection_w.create_index(ct.default_float_vec_field_name, index_params=ct.default_flat_index)
        collection_w.load()
        vectors = [[random.random() for _ in range(default_dim)] for _ in range(default_nq)]
        collection_w.search(vectors[:default_nq], default_search_field,
                            default_search_params, default_limit,
                            default_search_exp, _async=_async,
                            check_task=CheckTasks.check_search_results,
                            check_items={"nq": default_nq,
                                         "limit": default_limit,
                                         "_async": _async})
```
error:
[2023-02-01T19:19:23.267Z] [2023-02-01 18:11:56 - ERROR - ci_test]: search_results_check: limit(topK) searched (0) is not equal with expected (10) (func_check.py:227)

## Expected Behavior:
pass

## Log:
1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/270/pipeline/123
2. log: artifacts-milvus-standalone-nightly-270-pymilvus-e2e-logs.tar.gz
3. collection name: search_collection_AJdxWqaT
4. failed time: [2023-02-01T18:11:57.253Z] [gw4] [ 40%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_with_non_default_shard_nums[False-True-63]

**Comment by NicoYuan1986** [comment]
Not reproduced recently. I'll reopen the issue if it's reproduced.
