### ISSUE TITLE
[Bug]: [ResourceGroup] __default_resource_group capacity is 1000000 

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#21945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230202-d41cc0b2
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):  2.3.0.dev29
```

### Current Behavior

<capacity:1000000>,
```
[2023-02-03 10:23:15,123 - DEBUG - ci_test]: (api_request)  : [describe_resource_group] args: ['__default_resource_group', 'default', None], kwargs: {} (api_request.py:56)
[2023-02-03 10:23:15,142 - DEBUG - ci_test]: (api_response) : ResourceGroupInfo:
        <name:__default_resource_group>,
        <capacity:1000000>,
        <num_available_nodes:1>,
        <num_loaded_replicas:{}>,
        <num_outgoing_nodes:{}>,
        <num_incoming_nodes:{}>  (api_request.py:31)
```

### Expected Behavior

the capacity should equal the num_available_node at initial state.

### Steps To Reproduce

```markdown
describe the __default_resource_group after milvus new deployed
```

**Comment by yanliang567** [comment]
the capacity is 2 now 
utility.describe_resource_group('__default_resource_group')
ResourceGroupInfo:
        <name:__default_resource_group>, 
        <capacity:2>, 
        <num_available_nodes:1>, 
        <num_loaded_replicas:{}>, 
        <num_outgoing_nodes:{}>, 
        <num_incoming_nodes:{}>

**Comment by yanliang567** [comment]
BTW, shall we update the default resource group name to '__default_resource_group', which starts with one hyphen

**Comment by yanliang567** [comment]
when add more querynode, the capacity changed again. I guess there was a second when trying to refresh the capacity,  there were 12 querynodes as it was doing scale out.
```
ResourceGroupInfo:
        <name:__default_resource_group>, 
        <capacity:12>, 
        <num_available_nodes:8>, 
```

**Comment by weiliu1031** [comment]
> /assign @yanliang567

please verify on this

**Comment by yanliang567** [comment]
After discussion with @weiliu1031 , the new design is 
1. the default resource group capacity is a constant (1millsion), no matter node ups or down. 
2. the user created resource group capacity will be updated depending on nodes up and down (same as previsou design)

verified the new updates for the new design on master-20230216-8ec5ba13
