### ISSUE TITLE
[Bug]: create failed

### ISSUE THREAD

**Issue by gyd-a** [milvus-io/milvus#21948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):no 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

### Current Behavior

OS: container of ubuntu 18
Problem: Source code compilation milvus. run ./scripts/start_cluster.sh.  8 processes start normally. 
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/52058819/216502764-10461eb0-bb5a-49e9-9c38-d92f768945c9.png">
create error.
<img width="658" alt="image" src="https://user-images.githubusercontent.com/52058819/216502857-4e1a64d6-f766-462f-b828-caabc15bc70a.png">
Four processes remain.

**Comment by smellthemoon** [comment]
Do it still report an error after waiting?

**Comment by xiaofan-luan** [comment]
@gyd-a 
pls offer logs so we can investigate why
