### ISSUE TITLE
[Bug]: failed to get client address

### ISSUE THREAD

**Issue by jmugan** [milvus-io/milvus#21952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.2
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I ran the upgrade script to upgrade from 2.1 to 2.2, but I'm not sure if it worked. I got:

```
[2023/02/03 04:00:41.306 +00:00] [WARN] [config/file_source.go:85] ["Read config failed"] [error="read /milvus/configs/migration.yaml: is a directory"]
panic: key not found: etcd.endpoints

goroutine 1 [running]:
github.com/milvus-io/milvus/internal/util/paramtable.(*EtcdConfig).initEndpoints(0xc000455380)
	/home/jenkins/agent/workspace/internal/util/paramtable/service_param.go:142 +0x97
github.com/milvus-io/milvus/internal/util/paramtable.(*EtcdConfig).LoadCfgToMemory(0xc000455380)
	/home/jenkins/agent/workspace/internal/util/paramtable/service_param.go:109 +0x4c
github.com/milvus-io/milvus/cmd/tools/migration/configs.(*MilvusConfig).init(0xc00015ed98, 0xc00054eea0)
	/home/jenkins/agent/workspace/cmd/tools/migration/configs/config.go:93 +0x156
github.com/milvus-io/milvus/cmd/tools/migration/configs.newMilvusConfig(...)
	/home/jenkins/agent/workspace/cmd/tools/migration/configs/config.go:73
github.com/milvus-io/milvus/cmd/tools/migration/configs.(*Config).init(0xc00033d230, {0x7ffd15f75f44?, 0x2?})
	/home/jenkins/agent/workspace/cmd/tools/migration/configs/config.go:121 +0xbb
github.com/milvus-io/milvus/cmd/tools/migration/configs.NewConfig(...)
	/home/jenkins/agent/workspace/cmd/tools/migration/configs/config.go:129
github.com/milvus-io/milvus/cmd/tools/migration/command.Execute({0xc00003c040?, 0x2, 0x2})
	/home/jenkins/agent/workspace/cmd/tools/migration/command/main.go:24 +0x192
main.main()
	/home/jenkins/agent/workspace/cmd/tools/migration/main.go:10 +0x2e
```
After upgrading, it can't query the data. I look in the log and I see
```
["failed to get client address"] [error="find no available rootcoord, check rootcoord state"]
```
Did the upgrade work? Anyone have any ideas? I'm upgrading because our 2.1 in production started stopping randomly about once a day. I don't know what is going on, so I'm having quite a bit of trouble. Thanks!

### Milvus Log

[milvus.log](https://github.com/milvus-io/milvus/files/10575526/milvus.log)

**Comment by haorenfsa** [comment]
@jmugan Did you follow the instruction in https://milvus.io/docs/upgrade_milvus_cluster-helm.md ?

**Comment by haorenfsa** [comment]
Looks like that the `migration.yaml` file aws not provisioned correctly before you did the upgrade. 
So the upgrade failed, which means the DB metadata is still in v2.1.x form. 
So when you start the container with v2.2.2 image, Milvus will not be able to load the index correctly. You'll have to load the indexes you need again, and it should be working.

**Comment by jmugan** [comment]
What does "Looks like that the migration.yaml file was not provisioned correctly" mean exactly? I followed the instructions. Is there something else I should have done. This is in dev and I want to make sure I do it right when I do it in production.

**Comment by jmugan** [comment]
The reason I'm trying to upgrade is it keeps crashing in production, a couple times a day `milvusdb/milvus:v2.1.4` just stops.
[milvus.zip](https://github.com/milvus-io/milvus/files/10580694/milvus.zip)
 I've attached the log. I can create a new issue if that would be better.

**Comment by haorenfsa** [comment]
> What does "Looks like that the migration.yaml file was not provisioned correctly" mean exactly? I followed the instructions. Is there something else I should have done? This is in dev and I want to make sure I do it right when I do it in production.

I drew such a conclusion from the log of the upgrade script:
```
[2023/02/03 04:00:41.306 +00:00] [WARN] [config/file_source.go:85] ["Read config failed"] [error="read /milvus/configs/migration.yaml: is a directory"]
```

According to the [docker upgrade instruction](https://milvus.io/docs/upgrade_milvus_standalone-docker.md) The `/milvus/configs/migration.yaml` in the upgrade script's container is provisioned from `$(pwd)/migration.yaml` the $(pwd) is where you run the `docker` command.

If the `migration.yaml` is provisioned correctly, you should see the logs like below:
```log
Cmd: run, SourceVersion: 2.1.4, TargetVersion: 2.2.0, BackupFilePath: /tmp/migration.bak, RunWithBackup: true
Type: etcd, EndPoints: [milvus-etcd:2379], MetaRootPath: by-dev/meta
```

**Comment by haorenfsa** [comment]
> The reason I'm trying to upgrade is it keeps crashing in production, a couple times a day `milvusdb/milvus:v2.1.4` just stops. [milvus.zip](https://github.com/milvus-io/milvus/files/10580694/milvus.zip) I've attached the log. I can create a new issue if that would be better.

@yanliang567 Could you help check is it a known issue?

**Comment by yanliang567** [comment]
@jmugan could you please retry the upgrade scripts as suggested above? BTW, we do not suggest you run a standalone milvus for production.

**Comment by jmugan** [comment]
When I ran it I got this
```
(base) jmugan@jmugan-G7-7700:~/milvus$ docker run --rm -it --network milvus -v $(pwd)/migration.yaml:/milvus/configs/migration.yaml milvusdb/meta-migration:v2.2.0 /milvus/bin/meta-migration -config=/milvus/configs/migration.yaml
Cmd: run, SourceVersion: 2.1.4, TargetVersion: 2.2.0, BackupFilePath: /tmp/migration.bak, RunWithBackup: true
Type: etcd, EndPoints: [milvus-etcd:2379], MetaRootPath: by-dev/meta
[2023/02/06 01:54:46.686 +00:00] [DEBUG] [sessionutil/session_util.go:185] ["Session try to connect to etcd"]
[2023/02/06 01:54:46.694 +00:00] [DEBUG] [sessionutil/session_util.go:200] ["Session connect to etcd success"]
[2023/02/06 01:54:46.696 +00:00] [DEBUG] [sessionutil/session_util.go:282] ["Session get serverID success"] [key=id] [ServerId=154]
[2023/02/06 01:54:46.698 +00:00] [DEBUG] [sessionutil/session_util.go:310] ["service begin to register to etcd"] [serverName=migration] [ServerID=154]
[2023/02/06 01:54:46.701 +00:00] [DEBUG] [sessionutil/session_util.go:347] ["put session key into etcd"] [key=by-dev/meta/session/migration] [value="{\"ServerID\":154,\"ServerName\":\"migration\",\"Address\":\"2023-02-06 01:54:46.694312541 +0000 UTC m=+0.060377811\",\"Exclusive\":true,\"TriggerKill\":true,\"Version\":\"2.2.0-pre+dev\"}"]
[2023/02/06 01:54:46.701 +00:00] [INFO] [sessionutil/session_util.go:364] ["Service registered successfully"] [ServerName=migration] [serverID=154]
[2023/02/06 01:54:46.702 +00:00] [DEBUG] [sessionutil/session_util.go:422] ["SessionUtil GetSessions "] [prefix=migration] [key=migration] [address="2023-02-06 01:54:46.694312541 +0000 UTC m=+0.060377811"]
lease key won't be backuped: by-dev/meta/session/migration, lease id: 7587868418037737010
backup to: /tmp/migration.bak
prefix root-coord/collection will be removed!
prefix snapshots/root-coord/collection will be removed!
prefix root-coord/collection-alias will be removed!
prefix snapshots/root-coord/collection-alias will be removed!
prefix root-coord/segment-index will be removed!
prefix root-coord/index will be removed!
prefix indexes will be removed!
prefix root-coord/dd-msg-send will be removed!
prefix snapshots/root-coord/dd-msg-send will be removed!
prefix root-coord/dd-operation will be removed!
prefix snapshots/root-coord/dd-operation will be removed!
combineToCollectionIndexesMeta220, nil schema:  436794496861601793 , record:  &{[] <nil>}
combineToCollectionIndexesMeta220, nil schema:  436794548307623937 , record:  &{[] <nil>}
combineToCollectionIndexesMeta220, nil schema:  436806782449352705 , record:  &{[] <nil>}
[2023/02/06 01:54:46.732 +00:00] [WARN] [meta/210_to_220.go:280] ["release the collection without index"] [collectionID=436817304828510209]
migration session expired
[2023/02/06 01:54:46.744 +00:00] [WARN] [sessionutil/session_util.go:382] ["keep alive"] [error="context done"]
[2023/02/06 01:54:46.744 +00:00] [DEBUG] [sessionutil/session_util.go:630] ["liveness exits due to context done"]
```

Also, what's the best way to Milvus in production? Is it Kubernetes?

**Comment by jmugan** [comment]
We are on EC2. Is this the easiest recommended way? https://milvus.io/docs/aws.md

**Comment by haorenfsa** [comment]
> We are on EC2. Is this the easiest recommended way to run Milvus in production? https://milvus.io/docs/aws.md

Kubernetes is usually a better option. Our daily tests & performance tuning are all based on Kubernetes. https://milvus.io/docs/eks.md.

The key problems about deploy a standalone on EC2 are:
-  Your service & data are at risk (EC2 may crash or its disk data may lost.) You may need to do snapshots regularly for your EC2's disk, and prepare a recovery script, etc.
-  Standalone mode of Milvus is not easy to scale. Cluster mode is recommended for production. You can try our guide to [deploy Milvus Cluster with Ansible](https://milvus.io/docs/install_cluster-ansible.md), but it's not that will tested compared to Kubernetes deployment.

By the way, our  [Cloud Service of Managed Milvus](https://cloud.zilliz.com/) is also an option.

**Comment by jmugan** [comment]
Ah, thank you so much!

**Comment by haorenfsa** [comment]
> When I ran it I got this

@longjiquan Plz help confirming if the log infers upgrade suceeded? 

I also sugguest adding a line of log at the end to tell user if the upgrade is succeeded or failed.

**Comment by longjiquan** [comment]
> > When I ran it I got this
> 
> @longjiquan Plz help confirm if the log infers upgrade suceeded?
> 
> I also sugguest adding a line of log at the end to tell user if the upgrade is succeeded or failed.

OK, thx for the nice advice, I'll try my best effort to enhance the script. And then, these logs is normal, the migration succeeded.

**Comment by hbsardhara09** [comment]
I am also getting this issue, attaching log file and docker compose 
[docker-compose-milvus-standalone.yml.txt](https://github.com/milvus-io/milvus/files/12510006/docker-compose-milvus-standalone.yml.txt)
[milvus_logs.txt](https://github.com/milvus-io/milvus/files/12510008/milvus_logs.txt)

**Comment by hbsardhara09** [comment]
Is there any update?
