### ISSUE TITLE
[Bug]: Small segment don't  merge automatically

### ISSUE THREAD

**Issue by lvmnn** [milvus-io/milvus#21959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.2
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior
collection_name: item_image_4

1. set segment.maxSize = 48g
2. create a new milvus cluster
3. insert 100 million into milvus， dim = 512

After some time，Small segment don't  merge automatically

![image](https://user-images.githubusercontent.com/92595690/216535495-8ca39c40-6450-4f30-adde-06263d364dcb.png)

### Milvus Log

[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/10576429/milvus-log.tar.gz)

### Anything else?

![image](https://user-images.githubusercontent.com/92595690/216535684-c2f1a26b-0df0-4859-863e-2ac5d52ede43.png)

**Comment by lvmnn** [comment]
[bw_etcd_ALL.230203-152102.bak.gz](https://github.com/milvus-io/milvus/files/10576569/bw_etcd_ALL.230203-152102.bak.gz)

**Comment by lvmnn** [comment]
Another cluster
set segment=10g
[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/10576864/milvus-log.tar.gz)

**Comment by lvmnn** [comment]
> Another cluster set segment=10g [milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/10576864/milvus-log.tar.gz)

new info
[bw_etcd_ALL.230203-182006.bak.gz](https://github.com/milvus-io/milvus/files/10577985/bw_etcd_ALL.230203-182006.bak.gz)
[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/10577996/milvus-log.tar.gz)

**Comment by xiaofan-luan** [comment]
1. you can not set the segment size to 48G, because this will causing serious problem of: no load balancing, build index is supper slow. My recommendation would be 4G if you have enough memory(querynode more than 32G) or 2G
2. for current implementation, if you update the configuration after insert data then it won't take affect. We probably need to work on it to change the logic .

**Comment by xiaofan-luan** [comment]
5M rows seems to be a large value,  is there any specific reason you want to change the config?

**Comment by lvmnn** [comment]
> 5M rows seems to be a large value, is there any specific reason you want to change the config?

We have a billion search, and we need extreme search speed

**Comment by XuanYang-cn** [comment]
Might be download error, try increasing `dataCoord.compaction.timeout` to 24hrs and restart dataCoord

**Comment by lvmnn** [comment]
> Might be download error, try increasing `dataCoord.compaction.timeout` to 24hrs and restart dataCoord

Yes, the merge succeeded after changing this configuration
