### ISSUE TITLE
[Bug]: [ResourceGroup]Property names of ResourceGroupInfo is not consistent with protobuf definition

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#21958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230202-d41cc0b2
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.0.dev29
```

### Current Behavior

the property name is singleton, while the response is plural.
![image](https://user-images.githubusercontent.com/82361606/216534376-bba68772-6382-4b32-8f49-21255c09bda0.png)

 <name:__default_resource_group>,
        <capacity:1000000>,
        <num_available_nodes:1>,
        <num_loaded_replicas:{}>,
        <num_outgoing_nodes:{}>,
        <num_incoming_nodes:{}>

**Comment by weiliu1031** [comment]
> /assign @yanliang567

please verify on this

**Comment by yanliang567** [comment]
verified on dev38
