### ISSUE TITLE
[Feature]: Milvus Java SDK 判断 collection是否load的接口

### ISSUE THREAD

**Issue by hukang6677** [milvus-io/milvus#21955]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

需要一个Milvus Java SDK 判断 collection是否load的接口

**Comment by xiaofan-luan** [comment]
/assign @yhmo 
pls help on that

**Comment by yhmo** [comment]
The interface has been defined in milvus.proto:
rpc GetLoadState(GetLoadStateRequest) returns (GetLoadStateResponse) {}

Need to implement it in Java sdk.

**Comment by yhmo** [comment]
The GetLoadState has been implemented in Java SDK: https://github.com/milvus-io/milvus-sdk-java/pull/439
Will be available in a later version v2.2.3(along with the Milvus v2.2.3)
