### ISSUE TITLE
[Enhancement]:  Reduce memory usage of scalar index (stl_sort)

### ISSUE THREAD

**Issue by czs007** [milvus-io/milvus#21967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

In the current implementation of the scalar index (stl_sort), using size_t as the row number will cause the IndexStructure to perform padding for the purpose of alignment, thus causing memory usage to expand.

Therefore, for data of type int8, int16, and int32, IndexStructure occupies 2 * sizeof (int64) memory

```
template <typename T>
struct IndexStructure {
     //...
    T a_;
    size_t idx_;
};

template <typename T>
class ScalarIndexSort : public ScalarIndex<T> {
 private:
    bool is_built_;
    Config config_;
    std::vector<size_t> idx_to_offsets_;  // used to retrieve.
    std::vector<IndexStructure<T>> data_;
};
```

I 'd like to change size_t to int32_t, since the num of rows in segment will not exceed 2,147,483,647.

### Why is this needed?

memory is expensive

**Comment by xiaofan-luan** [comment]
good catch!
