### ISSUE TITLE
[Bug]: follow the offical guideline, when insert the book data, there is error occur: "MilvusException: (code=1, message=string is not supported now)"

### ISSUE THREAD

**Issue by JinXia77** [milvus-io/milvus#21969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.1
- Deployment mode(standalone or cluster):standlone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.1
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I followed the offical guideline to insert "book" data into milvus, there is an error occur : MilvusException: (code=1, message=string is not supported now),
the collection schema is :
```
book_id = FieldSchema(
  name="book_id", 
  dtype=DataType.INT64, 
  is_primary=True, 
)
book_name = FieldSchema(
  name="book_name", 
  dtype=DataType.VARCHAR, 
  max_length=200,
)
word_count = FieldSchema(
  name="word_count", 
  dtype=DataType.INT64,  
)
book_intro = FieldSchema(
  name="book_intro", 
  dtype=DataType.FLOAT_VECTOR, 
  dim=2
)
schema = CollectionSchema(
  fields=[book_id, book_name, word_count, book_intro], 
  description="Test book search"
)
collection_name = "book"

```
the insert code is :
`data = [
  [i for i in range(2000)],
  [str(i) for i in range(2000)],
  [i for i in range(10000, 12000)],
  [[random.random() for _ in range(2)] for _ in range(2000)],
]

collection = Collection("book")      # Get an existing collection.
mr = collection.insert(data)`

the error information is shown below:
<MilvusException: (code=1, message=string is not supported now)>

Can somebody know why I run the same code from offical guide line, but I can not insert string data smoothly?

**Comment by yanliang567** [comment]
@JinXia77 I add one line of code to init the collection, and it inserts successfully. Please double check the pymilvus version you are running. 
```
book_id = FieldSchema(
        name="book_id",
        dtype=DataType.INT64,
        is_primary=True,
    )
    book_name = FieldSchema(
        name="book_name",
        dtype=DataType.VARCHAR,
        max_length=200,
    )
    word_count = FieldSchema(
        name="word_count",
        dtype=DataType.INT64,
    )
    book_intro = FieldSchema(
        name="book_intro",
        dtype=DataType.FLOAT_VECTOR,
        dim=2
    )
    schema = CollectionSchema(fields=[book_id, book_name, word_count, book_intro],
                              description="Test book search"
                              )
    collection_name = "book"
    collection = Collection(name=collection_name, schema=schema)

    data = [
        [i for i in range(2000)],
        [str(i) for i in range(2000)],
        [i for i in range(10000, 12000)],
        [[random.random() for _ in range(2)] for _ in range(2000)],
    ]
```
```
02/03/2023 17:46:31 PM - INFO - start
(insert count: 2000, delete count: 0, upsert count: 0, timestamp: 439200669186392067, success count: 2000, err count: 0)

```

/assign @JinXia77 
/unassign

**Comment by JinXia77** [comment]
I double checked the pymilvus version which is 2.2.1,shown below
![image](https://user-images.githubusercontent.com/110447054/216571454-2a536022-7020-45ea-b3ea-4c5396c11f3d.png)

 and use the collecion.describe which shows below
![collecion_describe](https://user-images.githubusercontent.com/110447054/216571523-3395f783-a33f-4b0b-b89b-7e03ea096ef0.png)

still the error occured.
![image](https://user-images.githubusercontent.com/110447054/216571748-eb596204-70ec-4bb7-8b06-1dcdcfaaa4ff.png)

**Comment by JinXia77** [comment]
> @JinXia77 I add one line of code to init the collection, and it inserts successfully. Please double check the pymilvus version you are running.
> 
> ```
> book_id = FieldSchema(
>         name="book_id",
>         dtype=DataType.INT64,
>         is_primary=True,
>     )
>     book_name = FieldSchema(
>         name="book_name",
>         dtype=DataType.VARCHAR,
>         max_length=200,
>     )
>     word_count = FieldSchema(
>         name="word_count",
>         dtype=DataType.INT64,
>     )
>     book_intro = FieldSchema(
>         name="book_intro",
>         dtype=DataType.FLOAT_VECTOR,
>         dim=2
>     )
>     schema = CollectionSchema(fields=[book_id, book_name, word_count, book_intro],
>                               description="Test book search"
>                               )
>     collection_name = "book"
>     collection = Collection(name=collection_name, schema=schema)
> 
>     data = [
>         [i for i in range(2000)],
>         [str(i) for i in range(2000)],
>         [i for i in range(10000, 12000)],
>         [[random.random() for _ in range(2)] for _ in range(2000)],
>     ]
> ```
> 
> ```
> 02/03/2023 17:46:31 PM - INFO - start
> (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 439200669186392067, success count: 2000, err count: 0)
> ```
> 
> /assign @JinXia77 /unassign

I double checked the pymilvus version which is 2.2.1,shown below
![image](https://user-images.githubusercontent.com/110447054/216571454-2a536022-7020-45ea-b3ea-4c5396c11f3d.png)

 and use the collecion.describe which shows below
![collecion_describe](https://user-images.githubusercontent.com/110447054/216571523-3395f783-a33f-4b0b-b89b-7e03ea096ef0.png)

still the error occured.
![image](https://user-images.githubusercontent.com/110447054/216571748-eb596204-70ec-4bb7-8b06-1dcdcfaaa4ff.png)

**Comment by JinXia77** [comment]
> @JinXia77 I add one line of code to init the collection, and it inserts successfully. Please double check the pymilvus version you are running.
> 
> ```
> book_id = FieldSchema(
>         name="book_id",
>         dtype=DataType.INT64,
>         is_primary=True,
>     )
>     book_name = FieldSchema(
>         name="book_name",
>         dtype=DataType.VARCHAR,
>         max_length=200,
>     )
>     word_count = FieldSchema(
>         name="word_count",
>         dtype=DataType.INT64,
>     )
>     book_intro = FieldSchema(
>         name="book_intro",
>         dtype=DataType.FLOAT_VECTOR,
>         dim=2
>     )
>     schema = CollectionSchema(fields=[book_id, book_name, word_count, book_intro],
>                               description="Test book search"
>                               )
>     collection_name = "book"
>     collection = Collection(name=collection_name, schema=schema)
> 
>     data = [
>         [i for i in range(2000)],
>         [str(i) for i in range(2000)],
>         [i for i in range(10000, 12000)],
>         [[random.random() for _ in range(2)] for _ in range(2000)],
>     ]
> ```
> 
> ```
> 02/03/2023 17:46:31 PM - INFO - start
> (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 439200669186392067, success count: 2000, err count: 0)
> ```
> 
> /assign @JinXia77 /unassign

I am not sure if is error info will help, just mention here. When I insert the data into "book" collecion, there is another error information shown in terminal, shown below.
![image](https://user-images.githubusercontent.com/110447054/216580868-f8def820-4484-4630-ab83-b8f9381996a7.png)

**Comment by yanliang567** [comment]
@JinXia77 Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

**Comment by xiaofan-luan** [comment]
varchar will be the correct datatype.
As the error message said, string is not supported

**Comment by yanliang567** [comment]
@JinXia77 so how did you solve this problem?

**Comment by JinXia77** [comment]
> @JinXia77 so how did you solve this problem?

Yes! Thank you for your help, I recheck the version of milvus images and pymilvus, I found I downloaded a wrong docker-compose file which is 2.0.2 version. Now I redownload the 2.2.2 version milvus docker-compose file and re-insert the book data, it success. Sorry for my careless and wasting your so much time.  : (

**Comment by yanliang567** [comment]
Great to hear that. please enjoy with milvus 2.2.2.
