### ISSUE TITLE
[Bug]: [ResourceGroup] it hangs when describe a non exisitng resource grou

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#21962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230202-d41cc0b2
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.0.dev29
```

### Current Behavior

client hang

### Expected Behavior

return error with msg in a second

### Steps To Reproduce

```markdown
utility.describe_resource_group('non_existing_rg_name')
```

**Comment by yanliang567** [comment]
pymilvus-2.3.0.dev31 with master-20230208-403f85a9
It does not hang now, but the error msg is not meaningful:
`[2023-02-08 14:42:42,824 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Unexpected error, message=<error_code>)> (api_request.py:40)`

**Comment by weiliu1031** [comment]
> /assign @yanliang567

please verify on this

**Comment by yanliang567** [comment]
verified on pymilvus 2.3 dev38
`ct.err_msg: "failed to describe resource group, err=resource group doesn't exist"`
