### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ai4ki** [milvus-io/milvus#21984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.2
- Deployment mode: standalone
- pymilvus: 2.2.1
```

### Current Behavior

This issue has been discussed [here](https://github.com/milvus-io/milvus/issues/18199) but I found no reproducible solution.

I want to perform brute force similarity search with metric type inner product. I create a collection with the following index params:

`index_params = {
        'metric_type': "IP",
        'index_type': "FLAT",
        'params': {}
    }`

Loading my embeddings into the collection works fine. However, when I search the collection, I get this error: `KeyError: 'FLAT'`

### Expected Behavior

For exact similarity search, I wouldn't have to create an index in the first place. But I simply couldn't find anything in the Milvus documentation that shows how to set the metric_type when no index is created.

The above approach used to work just fine with Milvus v2.0.2. (which I can't use anymore because it crashed on my machine and I couldn't get it running again).

 My code and setup works as expected when I create an actual index like IVF_FLAT.

**Comment by haorenfsa** [comment]
@ai4ki Hi, `FLAT` means no index, you just need to load the collection and do search with your `metric_type` as `search_param`, check: https://milvus.io/docs/search.md.

**Comment by ai4ki** [comment]
Hi, thanks a lot for your quick reply--this works!

**Comment by huuson235** [comment]
> @ai4ki Hi, `FLAT` means no index, you just need to load the collection and do search with your `metric_type` as `search_param`, check: https://milvus.io/docs/search.md.

But when I do collection.load() it raise exception `index doesen't exist` ???

**Comment by haorenfsa** [comment]
@huuson235 Hi, could you plz provide the version of your pymilvus?  There may be some breaks across different verison. Try the pymilvus@v2.2.1

**Comment by haorenfsa** [comment]
@ThreadDao

**Comment by haorenfsa** [comment]
@huuson235  Hi, I just checked with the team. There're some feature breaks between different version.

For versions >= v2.2.0, You should add `FLAT` index and then load & search
For versions before that, you should just load & search.

cc @ai4ki

**Comment by huuson235** [comment]
> @huuson235 Hi, I just checked with the team. There're some feature breaks between different version.
> 
> For versions >= v2.2.0, You should add `FLAT` index and then load & search For versions before that, you should just load & search.
> 
> cc @ai4ki

thank you <3
