### ISSUE TITLE
The configuration file version is wrong

### ISSUE THREAD

**Issue by Bennu-Li** [milvus-io/milvus#2199]
## Report incorrect documentation

This document is still milvus0.5
https://github.com/milvus-io/milvus/blob/0.8.0/shards/kubernetes_demo/milvus_write_servers.yaml

**Comment by tinkerlin** [comment]
The Kubernetes example will use helm as deploy tool instead of single yaml file. We will update the document soon.
@Bennu-Li

**Comment by PahudPlus** [comment]
Pending input from Lin.

**Comment by shengjun1985** [comment]
Done
