### ISSUE TITLE
mishards support milvusAdmin

### ISSUE THREAD

**Issue by xwqb** [milvus-io/milvus#2200]
At present, mishards cluster management method is not sound enough, and the degree of data clarity is not ideal. It is hoped that mishards cluster mode can be supported in the future

**Comment by JinHai-CN** [comment]
We are optimizing the mishards deployment. Then we will check if we show mishards on MilvusAdmin.

**Comment by yhmo** [comment]
We recommend users use Milvus v2.0 to replace Mishards. Now the v2.0 rc4 has been released.
