### ISSUE TITLE
[Enhancement]: Remove constraint that compaction based on indexed segment

### ISSUE THREAD

**Issue by xiaocai2333** [milvus-io/milvus#22037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Remove constraint that compaction based on indexed segment at branch 2.2.0.

### Why is this needed?

1. In the absence of an index, the small segments can be merged in time.
2. Part of the indexing time can be omitted.

### Anything else?

to be discussed:
1. Compaction based on indexed segments is to prevent the QueryCoord current view and target view diff from being too large.

Suppose that we will have 10 segments that can be compacted.(from same channel)
1. These 10 segments will not be generated at the same time, but will only be generated one by one.
2. case 1, the time interval for generating segments is very short, that we can speculate that the size of these segments is not large, then it has little effect on the size of the `diff`.
3. case 2, the size of these segments is large, that the time interval for generating segments will definitely not be short. Perhaps compaction occurs when there are 3 segments(compaction policy: small segments >= 3).
4. By the way, regardless of whether the index is built or not, the size of final `diff` is twice the data size of the 10 segments.

**Comment by xiaocai2333** [comment]
@congqixia @jiaoew1991 @yah01 
please discuss with this, thanks.

**Comment by yah01** [comment]
FYI, Small segment (with row num < 1024) will be considered "indexed"
