### ISSUE TITLE
[Bug]: Milvus latency metrics not accurate.

### ISSUE THREAD

**Issue by soothing-rain** [milvus-io/milvus#22068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: latest
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

In our stability test, we found that Milvus latency seems pretty stable as appeared in Grafana:
![8Dp0EPIfrP](https://user-images.githubusercontent.com/69466447/217495054-72112343-433e-4966-8eaf-b89988233904.jpg)

However, according to actually stats on the client side, this is incorrect:
![07fe6f9f-29d7-4e9e-8601-f0670b2fc9b2](https://user-images.githubusercontent.com/69466447/217495192-b4077dee-0de2-4a55-9f7c-d1404a536925.jpeg)

Client logs also shows that the second graph abve is correct. Please see pictures below how performance regression happened after 3 days:
![lt8NwK4q5a](https://user-images.githubusercontent.com/69466447/217495308-003ca428-2be7-45ba-a9b1-f278030cc8bf.jpg)
![59652bc9-e0e2-4a67-92f3-813eeca92d33](https://user-images.githubusercontent.com/69466447/217495450-b65a0a0e-c6e8-44dc-9e64-9468b1df96b8.jpeg)

**Comment by yanliang567** [comment]
I think the reason is when you set a longer period in grafana, the granularity displayed becomes bigger, then it looks more smooth.
@LoveEachDay please help to double check.

/assign @LoveEachDay 
/unassign

**Comment by soothing-rain** [comment]
Xiaofan mentioned that it also be a pymilvus issue.

/assign @xige-16
