### ISSUE TITLE
[Bug]: Milvus standalone panics when running with `etcd.use.embed: true`

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#22065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230208-b83bbc04
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![cUNIio03xN](https://user-images.githubusercontent.com/26307815/217485753-e8134986-baba-4e89-945b-7226f013f34c.jpg)

**Comment by wangting0128** [comment]
`DEPLOY_MODE=STANDALONE nohup bin/milvus run standalone > /tmp/standalone.log &`
I tried it,👆this cmd can solve this problem
@xiaofan-luan

**Comment by yanliang567** [comment]
@wangting0128 was it fixed?

**Comment by wangting0128** [comment]
> @wangting0128 was it fixed?

yes！close it now
