### ISSUE TITLE
[Bug]:  Milvus query speed is very slow 

### ISSUE THREAD

**Issue by JulyMood** [milvus-io/milvus#22069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.2
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):  pulsar  
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus:2.2.2
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: Helm default config
- GPU: no
- Others:
```

### Current Behavior

When the query interface is used, the condition has the trie index, speed is very slow。

![image](https://user-images.githubusercontent.com/16485777/217498662-4b9ca8cf-6f15-40cb-a521-3ae5ff30516b.png)

![p1675850594799](https://user-images.githubusercontent.com/16485777/217498777-16b31d5d-be3c-4b76-9d24-4a4bc3d8f099.jpg)
![p1675850493068](https://user-images.githubusercontent.com/16485777/217498803-b3f0367e-2f35-45d6-82ab-bb049b70afd2.jpg)

### Expected Behavior

Return in 1 second

### Steps To Reproduce

```markdown
As above
```

**Comment by xiaofan-luan** [comment]
thanks for the feedback, what if there is no index?

**Comment by JulyMood** [comment]
> 感谢反馈，没有索引怎么办？

It's actually faster, in less than a second. What's the reason?

**Comment by yanliang567** [comment]
the current design is
1. Milvus loads index files, if there are index
2. so Milvus has to retrieve the data from disk if client tries to retrieve  raw data.
The community is working on a new design to improve this performance, which I believe will be available soon in 2023

**Comment by kingkupps** [comment]
Is there any update on this? I'm seeing similar behavior with Milvus 2.2.3

**Comment by xiaofan-luan** [comment]
/assign @zhagnlu 
I thought zhaglu is working on it~

**Comment by xiaofan-luan** [comment]
Seems that with the new optimization it's gonna to be ok to return in hundred milliseconds.

**Comment by nathananneken-8451** [comment]
> Seems that with the new optimization it's gonna to be ok to return in hundred milliseconds.

Do you have any issue or PR links to the updated vector retrieval redesign implementation work?

**Comment by zhagnlu** [comment]
> > Seems that with the new optimization it's gonna to be ok to return in hundred milliseconds.
> 
> Do you have any issue or PR links to the updated vector retrieval redesign implementation work?
 
For now, we are focusing on optimize query performance, this caused by several reasons like https://github.com/milvus-io/milvus/issues/24223 describe it.

**Comment by umar1997** [comment]
Is there a way to preload the index or keep the index in memory like we do the collection?

> the current design is
> 
> 1. Milvus loads index files, if there are index
> 2. so Milvus has to retrieve the data from disk if client tries to retrieve  raw data.
>    The community is working on a new design to improve this performance, which I believe will be available soon in 2023
