### ISSUE TITLE
[Bug]: When the image tag is wrong for rolling update, then run rolling update with right image tag again, the operation will be blocked.

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#22060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When the image tag is wrong for rolling update, there will be an `ImagePullBackOff` error. 

If then run the rolling update script again with the right image tag, this operation will be blocked forever without a manual fix.

This error needs to edit the deployment to fix the image tag, and it is not that convenient.

### Expected Behavior

Hope the rolling update script can detect this error and fix it.

**Comment by zhuwenxing** [comment]
/assign @locustbaby 

Please take a look.

**Comment by locustbaby** [comment]
Sure,  I will optimize the display of block error messages.
Also, I will think about whether I should do a rollback.
