### ISSUE TITLE
[Bug]: milvus2.2 etcd restart failed

### ISSUE THREAD

**Issue by wziyang** [milvus-io/milvus#22082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.2
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.2
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 32/128
- GPU: 
- Others:
```

### Current Behavior

After running for a period of time,  an etcd restart failed，milvus is temporarily normal.

![image](https://user-images.githubusercontent.com/38698650/217709660-9faddc2d-f8ba-40d0-938e-75189e99023c.png)
![image](https://user-images.githubusercontent.com/38698650/217709803-0d89f1c9-1d60-4ae0-978f-dce77a87c096.png)

### Milvus Log

etcd 11:15:43.69
etcd 11:15:43.69 Welcome to the Bitnami etcd container
etcd 11:15:43.69 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-etcd
etcd 11:15:43.69 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-etcd/issues
etcd 11:15:43.69
etcd 11:15:43.70 INFO  ==> ** Starting etcd setup **
etcd 11:15:43.72 INFO  ==> Validating settings in ETCD_* env vars..
etcd 11:15:43.72 WARN  ==> You set the environment variable ALLOW_NONE_AUTHENTICATION=yes. For safety reasons, do not use this flag in a production environment.
etcd 11:15:43.72 INFO  ==> Initializing etcd
etcd 11:15:43.72 INFO  ==> Generating etcd config file using env variables
etcd 11:15:48.83 INFO  ==> http://milvus-prod22-etcd-1.milvus-prod22-etcd-headless.milvus-prod22.svc.cluster.local:2380,http://milvus-prod22-etcd-2.milvus-prod22-etcd-headless.milvus-prod22.svc.cluster.local:2380
etcd 11:15:48.84 INFO  ==> get_etcd_active_endpoints: http://milvus-prod22-etcd-1.milvus-prod22-etcd-headless.milvus-prod22.svc.cluster.local:2380,http://milvus-prod22-etcd-2.milvus-prod22-etcd-headless.milvus-prod22.svc.cluster.local:2380
etcd 11:15:48.85 INFO  ==> Detected data from previous deployments
etcd 11:15:48.85 INFO  ==> The member will try to join the cluster by it's own
etcd 11:15:48.86 INFO  ==> ** etcd setup finished! **

etcd 11:15:48.88 INFO  ==> ** Starting etcd **
{"level":"info","ts":1675912548.9318142,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_ADVERTISE_CLIENT_URLS","variable-value":"http://milvus-prod22-etcd-0.milvus-prod22-etcd-headless.milvus-prod22.svc.cluster.local:2379"}
{"level":"info","ts":1675912548.9319117,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_AUTO_COMPACTION_MODE","variable-value":"revision"}
{"level":"info","ts":1675912548.9319248,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_AUTO_COMPACTION_RETENTION","variable-value":"1000"}
{"level":"info","ts":1675912548.9319444,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_AUTO_TLS","variable-value":"false"}
{"level":"info","ts":1675912548.9319592,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_CLIENT_CERT_AUTH","variable-value":"false"}
{"level":"info","ts":1675912548.9319746,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_DATA_DIR","variable-value":"/bitnami/etcd/data"}
{"level":"info","ts":1675912548.9319892,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_ELECTION_TIMEOUT","variable-value":"2500"}
{"level":"info","ts":1675912548.9320269,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_HEARTBEAT_INTERVAL","variable-value":"500"}
{"level":"info","ts":1675912548.9320455,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_INITIAL_ADVERTISE_PEER_URLS","variable-value":"http://milvus-prod22-etcd-0.milvus-prod22-etcd-headless.milvus-prod22.svc.cluster.local:2380"}
{"level":"info","ts":1675912548.93206,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_INITIAL_CLUSTER","variable-value":"milvus-prod22-etcd-0=http://milvus-prod22-etcd-0.milvus-prod22-etcd-headless.milvus-prod22.svc.cluster.local:2380,milvus-prod22-etcd-1=http://milvus-prod22-etcd-1.milvus-prod22-etcd-headless.milvus-prod22.svc.cluster.local:2380,milvus-prod22-etcd-2=http://milvus-prod22-etcd-2.milvus-prod22-etcd-headless.milvus-prod22.svc.cluster.local:2380"}
{"level":"info","ts":1675912548.932071,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_INITIAL_CLUSTER_STATE","variable-value":"existing"}
{"level":"info","ts":1675912548.9320788,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_INITIAL_CLUSTER_TOKEN","variable-value":"etcd-cluster-k8s"}
{"level":"info","ts":1675912548.9320924,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_LISTEN_CLIENT_URLS","variable-value":"http://0.0.0.0:2379"}
{"level":"info","ts":1675912548.9321127,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_LISTEN_PEER_URLS","variable-value":"http://0.0.0.0:2380"}
{"level":"info","ts":1675912548.9321225,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_LOG_LEVEL","variable-value":"info"}
{"level":"info","ts":1675912548.9321399,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_NAME","variable-value":"milvus-prod22-etcd-0"}
{"level":"info","ts":1675912548.9321496,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_PEER_AUTO_TLS","variable-value":"false"}
{"level":"info","ts":1675912548.9321694,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_QUOTA_BACKEND_BYTES","variable-value":"4294967296"}
{"level":"warn","ts":1675912548.9321911,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_TRUSTED_CA_FILE="}
{"level":"warn","ts":1675912548.9322112,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_CONF_FILE=/opt/bitnami/etcd/conf/etcd.yaml"}
{"level":"warn","ts":1675912548.9322286,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_ON_K8S=yes"}
{"level":"warn","ts":1675912548.9322374,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_SNAPSHOTS_DIR=/snapshots"}
{"level":"warn","ts":1675912548.9322455,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_BIN_DIR=/opt/bitnami/etcd/bin"}
{"level":"warn","ts":1675912548.9322612,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_VOLUME_DIR=/bitnami/etcd"}
{"level":"warn","ts":1675912548.9322734,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_ROOT_PASSWORD="}
{"level":"warn","ts":1675912548.9322822,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_CLUSTER_DOMAIN=milvus-prod22-etcd-headless.milvus-prod22.svc.cluster.local"}
{"level":"warn","ts":1675912548.9322894,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_DISASTER_RECOVERY=no"}
{"level":"warn","ts":1675912548.9323022,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_KEY_FILE="}
{"level":"warn","ts":1675912548.93231,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_CONF_DIR=/opt/bitnami/etcd/conf"}
{"level":"warn","ts":1675912548.932324,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_DAEMON_GROUP=etcd"}
{"level":"warn","ts":1675912548.9323308,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_START_FROM_SNAPSHOT=no"}
{"level":"warn","ts":1675912548.93234,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_INIT_SNAPSHOT_FILENAME="}
{"level":"warn","ts":1675912548.9323516,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_INIT_SNAPSHOTS_DIR=/init-snapshot"}
{"level":"warn","ts":1675912548.9323595,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_TMP_DIR=/opt/bitnami/etcd/tmp"}
{"level":"warn","ts":1675912548.932367,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_BASE_DIR=/opt/bitnami/etcd"}
{"level":"warn","ts":1675912548.9323797,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_CERT_FILE="}
{"level":"warn","ts":1675912548.9323864,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_NEW_MEMBERS_ENV_FILE=/bitnami/etcd/data/new_member_envs"}
{"level":"warn","ts":1675912548.9324021,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_DAEMON_USER=etcd"}
{"level":"info","ts":"2023-02-09T11:15:48.932+0800","caller":"etcdmain/etcd.go:72","msg":"Running: ","args":["etcd"]}
{"level":"info","ts":"2023-02-09T11:15:48.934+0800","caller":"etcdmain/etcd.go:115","msg":"server has been already initialized","data-dir":"/bitnami/etcd/data","dir-type":"member"}
{"level":"info","ts":"2023-02-09T11:15:48.934+0800","caller":"embed/etcd.go:131","msg":"configuring peer listeners","listen-peer-urls":["http://0.0.0.0:2380"]}
{"level":"info","ts":"2023-02-09T11:15:48.934+0800","caller":"embed/etcd.go:139","msg":"configuring client listeners","listen-client-urls":["http://0.0.0.0:2379"]}
{"level":"info","ts":"2023-02-09T11:15:48.935+0800","caller":"embed/etcd.go:307","msg":"starting an etcd server","etcd-version":"3.5.0","git-sha":"946a5a6f2","go-version":"go1.16.3","go-os":"linux","go-arch":"amd64","max-cpu-set":32,"max-cpu-available":32,"member-initialized":true,"name":"milvus-prod22-etcd-0","data-dir":"/bitnami/etcd/data","wal-dir":"","wal-dir-dedicated":"","member-dir":"/bitnami/etcd/data/member","force-new-cluster":false,"heartbeat-interval":"500ms","election-timeout":"2.5s","initial-election-tick-advance":true,"snapshot-count":100000,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["http://milvus-prod22-etcd-0.milvus-prod22-etcd-headless.milvus-prod22.svc.cluster.local:2380"],"listen-peer-urls":["http://0.0.0.0:2380"],"advertise-client-urls":["http://milvus-prod22-etcd-0.milvus-prod22-etcd-headless.milvus-prod22.svc.cluster.local:2379"],"listen-client-urls":["http://0.0.0.0:2379"],"listen-metrics-urls":[],"cors":["*"],"host-whitelist":["*"],"initial-cluster":"","initial-cluster-state":"existing","initial-cluster-token":"","quota-size-bytes":4294967296,"pre-vote":true,"initial-corrupt-check":false,"corrupt-check-time-interval":"0s","auto-compaction-mode":"revision","auto-compaction-retention":"1µs","auto-compaction-interval":"1µs","discovery-url":"","discovery-proxy":"","downgrade-check-interval":"5s"}
{"level":"info","ts":"2023-02-09T11:15:58.938+0800","caller":"etcdserver/backend.go:85","msg":"db file is flocked by another process, or taking too long","path":"/bitnami/etcd/data/member/snap/db","took":"10.000328201s"}

**Comment by LoveEachDay** [comment]
@wziyang From the etcd v3.5.0 source code, etcd will wait for 10 seconds to load the db file. Could you check the db file size and storage capabilities whether it's too slow? 

Here's the source code:
```
// openBackend returns a backend using the current etcd db.
func openBackend(cfg config.ServerConfig, hooks backend.Hooks) backend.Backend {
	fn := cfg.BackendPath()

	now, beOpened := time.Now(), make(chan backend.Backend)
	go func() {
		beOpened <- newBackend(cfg, hooks)
	}()

	select {
	case be := <-beOpened:
		cfg.Logger.Info("opened backend db", zap.String("path", fn), zap.Duration("took", time.Since(now)))
		return be

	case <-time.After(10 * time.Second):
		cfg.Logger.Info(
			"db file is flocked by another process, or taking too long",
			zap.String("path", fn),
			zap.Duration("took", time.Since(now)),
		)
	}

	return <-beOpened
}
```

**Comment by wziyang** [comment]
@LoveEachDay ![image](https://user-images.githubusercontent.com/38698650/217991686-9af5e92e-abb8-4c42-88c5-fedd0ff04e39.png)
 the db file size just 218M, it should not be too slow.

**Comment by LoveEachDay** [comment]
@wziyang What kind of storage do you use for etcd? Do you use nfs? 
Fast disks are the most critical factor for etcd deployment performance and stability. Try to benchmark the storage and following the hardware recommendations at : https://etcd.io/docs/v3.5/op-guide/hardware/#disks

**Comment by wziyang** [comment]
@LoveEachDay Yes, I use nfs and the disk is ssd. I would like to know how to get etcd to start up again, which it has been unable to do.

**Comment by LoveEachDay** [comment]
@wziyang Are there 2 etcd pods still running? If so, you may delete the pvc for etcd-0, and the etcd cluster will sync the data to etcd-0 after it start up.

**Comment by wziyang** [comment]
@LoveEachDay It is normal after deleting, thank you

**Comment by yanliang567** [comment]
close the issue as comments above.
