### ISSUE TITLE
Is Index IVFPQ supported on GPU?

### ISSUE THREAD

**Issue by AyushP123** [milvus-io/milvus#2209]
I was benchmarking Milvus as compared to Faiss for IVF_PQ and found that for individual queries Milvus IVF_PQ implementation is slower in creating the index and searching. I wanted to know for both C++ and python, is Index.IVF_PQ implemented for GPU??

**Comment by AyushP123** [comment]
Reason for confusion:
It is mentioned here that IVF_PQ is not implemented for the GPU:
https://github.com/milvus-io/pymilvus/blob/master/examples/indexes/example_ivf_pq.py.
It is mentioned here that IVF_PQ is implemented for the GPU:
https://www.milvus.io/docs/v0.8.0/guides/index.md

**Comment by cydrain** [comment]
Use released Milvus doc as golden:
https://www.milvus.io/docs/v0.8.0/guides/index.md

**Comment by tinkerlin** [comment]
In fact, IVFPQ supports GPU. Some information in `example_ivf_pq.py` is outdated and we will update it soon. @AyushP123 @BossZou
