### ISSUE TITLE
Refactor log in Milvus

### ISSUE THREAD

**Issue by scsven** [milvus-io/milvus#221]
**Is your feature request related to a problem? Please describe.**
There are some redundant message in log files and some logs need more context.

**Describe the solution you'd like**
Review all log in source code, remove unused log. Add unique id in Query, Job and Task. Logging message with these ids.

**Describe alternatives you've considered**

**Additional context**

**Comment by cxie** [comment]
Can we change logging framework to glog?

**Comment by JinHai-CN** [comment]
Move to planned features, the log format and context need to unified.

**Comment by scsven** [comment]
This issue is too old, log module has been rewrite.
