### ISSUE TITLE
[Bug]: [CI] test_search_invalid_params_type[DISKANN-params6] failed due to aio limit

### ISSUE THREAD

**Issue by bigsheeper** [milvus-io/milvus#22123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

querynode load failed due to aio limit:
![image](https://user-images.githubusercontent.com/42060877/218062441-599a29ea-aaf2-401b-902a-109e2d3d7eb5.png)

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-22114/2/pipeline/

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-21917/13/pipeline/

**Comment by liliu-z** [comment]
Re-released Knowhere 2.0 to fix this issue.
