### ISSUE TITLE
Issue when starting docker image on Windows

### ISSUE THREAD

**Issue by rose-jinyang** [milvus-io/milvus#2212]
Hello
Thanks for this contributing this project.
I tried to run Milvus 0.8.0 docker image on Windows 10 pro 64bit.
But it does not start.
I set the memory of docker engine to 6GB.
In config setting file, the sum of cpu cache size and insert buffer size is 5GB.
I followed all the steps as milvus help document.
I am using the latest version of docker desktop on Windows 10.
I downgraded docker version but it still does not start.
I think that there was this issue for milvus 0.7.0.
I am strange why Milvus docker image often does not start on Windows 10.
How can I fix this issue?
Thanks

**Comment by tinkerlin** [comment]
Can you show more detailed information? 
I have tried it locally and milvus is functioning normally.
