### ISSUE TITLE
[Bug]: Suspected data loss during batch ingestion.

### ISSUE THREAD

**Issue by jeet129** [milvus-io/milvus#22122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvusdb/milvus-nightly
                  tag: nightly-20230205-ae305a5
- Deployment mode: cluster
- MQ type - pulsar    
- SDK version - Java sdk 2.2.0
- OS(Ubuntu or CentOS): Centos
- CPU/Memory: Based on sizing tools
- GPU: 
- Others: Collection with 3 fields - id, float vector of 384 dim, varchar field,
There are around 455 Partitions in the collection
Data cord - 1 core/2GB,
Data Node - 4 instances of 2 core/16GB,
Number of shards - 4,
proxy - 2 core/8GB
```

### Current Behavior

We are doing a bulk ingestion of data to our milvus 2.2.x cluster, our data nodes, data cooord, query coord, proxy keeps crashing. And post the ingestion the entity count shown on attu is 7.8M , where as expected count was supposed to be 21.8M.

### Steps To Reproduce

```markdown
1. create a collection
2. create 455 partitions to the collection
3. insert 1 ~ 5 rows into each partition randomly
4. datanode crashed occasionally, with 16GB mem. change to 20GB, no crash anymore
5. totally insert 24M rows, but num_entities only return 7M, even after called flush()
```

### Milvus Log

[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/10705736/milvus-log.tar.gz)

**Comment by MrPresent-Han** [comment]
I will have a look at this

**Comment by congqixia** [comment]
Hi @jeet129 could you please backup some meta information from you Milvus instance using this tool?
https://github.com/milvus-io/birdwatcher

**Comment by MrPresent-Han** [comment]
Hello, @jeet129 , before I give the final conclusion for this issue. Please modify a parameter in milvus.yaml:

**Comment by MrPresent-Han** [comment]
Obviously, watch channel timeout problem occurred in this case, seeing screenshot below:
<img width="1349" alt="截屏2023-02-10 19 52 58" src="https://user-images.githubusercontent.com/116052805/218087209-b6246730-78a2-445a-a038-af803e52a04a.png">

**Comment by jeet129** [comment]
@MrPresent-Han,

The max watch duration was already modified to 3600, sharing the snippet from the values.yaml
![image](https://user-images.githubusercontent.com/16897361/218308386-3d8eb5aa-e922-4c03-9952-30eb9a730765.png)

**Comment by xiaofan-luan** [comment]
In this test case we see very large partition numbers, that might be one of the reason watch DML will fail

**Comment by MrPresent-Han** [comment]
![XB3FfRZwXp](https://user-images.githubusercontent.com/116052805/218312459-d5a22d93-b2f8-435b-a33c-9b263d28bf07.jpg)

**Comment by xiaofan-luan** [comment]
> 

Seems the issue is quite clearly:
1. too many partitions lead to large number of growing segments ( 4 * 445 ~ 1780)
2.  each growing segments take at least a chunk, which is around 16M
3.  due to large segment numbers(1534 for a single shard), watch DML takes longer than 1 minutes and timeout

**Comment by xiaofan-luan** [comment]
from datanode log, load stats log is super slow, that might due to minio througput limitation

<img width="723" alt="image" src="https://user-images.githubusercontent.com/83447078/218315105-ccc13d93-3248-42ff-8418-3403dabb777e.png">

**Comment by MrPresent-Han** [comment]
Regarding the problem of the number of entries is much lower than expectation, I found the log as follow:
<img width="1349" alt="截屏2023-02-12 22 28 29" src="https://user-images.githubusercontent.com/116052805/218317058-b777b67e-cf4a-47b3-8eb9-89130d67c919.png">
It shows that the sum of growing segments is around 25 millions rows, while the number for sealed segment is only 208184. These two figures don't match the provided number 21.8M

**Comment by jeet129** [comment]
> ![XB3FfRZwXp](https://user-images.githubusercontent.com/116052805/218312459-d5a22d93-b2f8-435b-a33c-9b263d28bf07.jpg) @jeet129 , hello, I think the correct form of this parameter in milvus.yaml is shown in the image above. It's 'dataCoord', rather than 'dataCoordinator'. So I think this will help settle down the watch channel failed problem and I will continue to search for the root cause.

This value of dataCoordinator is taken from the helm chart of milvus. Either the helm is incorrect or its expected values:
https://artifacthub.io/packages/helm/milvus/milvus/4.0.5?modal=install

**Comment by MrPresent-Han** [comment]
Hello, @jeet129 , there is a little detail regarding extra config for milvus.yaml in the https://artifacthub.io/packages/helm/milvus/milvus/4.0.5?modal=install

**Comment by xiaofan-luan** [comment]
> Regarding the problem of the number of entries is much lower than expectation, I found the log as follow: <img alt="截屏2023-02-12 22 28 29" width="1349" src="https://user-images.githubusercontent.com/116052805/218317058-b777b67e-cf4a-47b3-8eb9-89130d67c919.png"> It shows that the sum of growing segments is around 25 millions rows, while the number for sealed segment is only 208184. These two figures don't match the provided number 21.8M
> 
> At the same time, as expected, there are many WARN log concerning the incorrectness of number of rows in the segmentInfo when datanode trying to get segment meta from datacoord, as follows:
> 
> <img alt="截屏2023-02-12 22 29 10" width="1359" src="https://user-images.githubusercontent.com/116052805/218317225-f0b91377-c6f1-4357-8dda-f27ec6745690.png">
> 
> I suspect the OOM crashed process violate the process of updateSegmentInfo process and lead to a weird meta status. So I agree with the idea of Conqi to get a backup of meta using bird-watcher. @xiaofan-luan

is the fix meta log expected if OOM happens?

**Comment by wayblink** [comment]
> from datanode log, load stats log is super slow, that might due to minio througput limitation
> 
> <img alt="image" width="723" src="https://user-images.githubusercontent.com/83447078/218315105-ccc13d93-3248-42ff-8418-3403dabb777e.png">

@jeet129 According to this log, probably it meet minio performance bottleneck. Please verify this by looking into minio UI and Start trace log.
![image](https://user-images.githubusercontent.com/18096561/218423317-48ee5ab7-d1e8-4d0e-b6d8-8e2e45bd31bf.png)

**Comment by jeet129** [comment]
@MrPresent-Han, @xiaofan-luan 
Please find the etcd backup using birdwatcher
[bw_etcd_ALL.230212-223040.bak.gz](https://github.com/milvus-io/milvus/files/10722574/bw_etcd_ALL.230212-223040.bak.gz)

**Comment by congqixia** [comment]
Quick analysis:
```
Collection ID: 439201266082250839       Collection Name: rg_qgApparelBaseItm
Collection State: CollectionDropping
...
Collection ID: 439309920937412306       Collection Name: rg_qgApparelBaseItm
Collection State: CollectionDropping
...
```
Collection is still in dropping state and cannot be cleared.
```
For current collection 439309921019645441
```
--- Growing: 0, Sealed: 1360, Flushed: 4492
--- Total Segments: 5852, row count: 8315068
Sealed 1360 segments, total rows 417283
Flushed 4492 segments, total rows 7897785
```

**Comment by congqixia** [comment]
For some channel, checkpoint is not healthy:
```
Backup(by-dev) > show checkpoint --collection 439309921019645441
vchannel by-dev-rootcoord-dml_4_439309921019645441v0 seek to 2023-02-09 22:28:27.942 +0800 CST, from channel checkpoint
vchannel by-dev-rootcoord-dml_5_439309921019645441v1 seek to 2023-02-10 01:20:20.742 +0800 CST, from channel checkpoint
vchannel by-dev-rootcoord-dml_6_439309921019645441v2 seek to 2023-02-09 22:51:31.343 +0800 CST, from channel checkpoint
vchannel by-dev-rootcoord-dml_7_439309921019645441v3 seek to 2023-02-13 17:34:58.287 +0800 CST, from channel checkpoint
```

**Comment by xiaofan-luan** [comment]
might be the similar issue with dropping collection? 
how long does it take to load stats and recover from wal

**Comment by yhmo** [comment]
Link to https://github.com/milvus-io/milvus/pull/22241

**Comment by yhmo** [comment]
The data was successfully inserted with hotfix-2.2.5. The data loss bug might be a legacy/temporary  of old build/version.
