### ISSUE TITLE
[Bug]: StandBy Node received a batch insert request during rolling upgrade

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#22126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2 branch
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://qa-jenkins.milvus.io/blue/organizations/jenkins/rolling_update_test/detail/rolling_update_test/39/pipeline/247
```
[2023-02-10T03:52:23.217Z] [2023-02-10 03:52:23 - ERROR - pymilvus.decorators]: RPC error: [batch_insert], <MilvusException: (code=1, message=syncTimeStamp Failed:StateCode=StandBy)>, <Time:{'RPC start': '2023-02-10 03:52:23.133743', 'RPC error': '2023-02-10 03:52:23.137115'}> (decorators.py:108)
```

**Comment by wayblink** [comment]
This behavior is explainable. As we change the start, register order. Now a registered session key doesn't ensure that the node is healthy. In this case. Standby rootcoord is switching from standby to active. It
1, register key
2, start -> update state to healthy
Between 1 and 2. Proxy will discover this rootcoord in standby mode and will fail requests during this period.

I think the solutions might be three:
1, Rethink the Start/Register order, go back to obey the principle before —— component can only register after it is healthy.
2, Do nothing, tell users external call may fail during rolling update
3, Add retry in all inner calls. This is preferred but may need a large effort

**Comment by xiaofan-luan** [comment]
preferred option 3 also
We need to first polish the retry mechanism

**Comment by wayblink** [comment]
This should be solved after inner retry is added. @jaime0815 Is this issue still exist in recent tests?
