### ISSUE TITLE
[Bug]: Notebook: search_article_in_medium; won't load inserted data

### ISSUE THREAD

**Issue by anonywuss** [milvus-io/milvus#22133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.3
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.2
- OS(Ubuntu or CentOS): MacOS
- CPU/Memory: i7/16gb
- GPU: none
- Others:
```

### Current Behavior

When running collection.load(), it throws error "index doesn't exist".

### Expected Behavior

In the previous step, towhee had inserted all the fields into Milvus (no errors reported). Expected collection.load() to load the data after inserting the data.

### Steps To Reproduce

```markdown
Open Jupyter notebook: https://github.com/towhee-io/examples/tree/main/nlp/text_search
```

### Anything else?

Although this is a towhee example, I discovered it as a Milvus example: https://milvus.io/docs/text_search_engine.md

Unsure if this is a Milvus or Towhee issue.

**Comment by yanliang567** [comment]
@anonywuss Please try to build index before loading the collection. This is a limitation introduced since Milvus 2.2.0, which we are trying to fix it ASAP.

/assign @anonywuss 
/unassign

**Comment by xiaofan-luan** [comment]
@yanliang567 @anonywuss 
You have to build index before load.
 This is the limitation and won't change in the future.

**Comment by anonywuss** [comment]
What index do you recommend? I tried IVF_FLAT, but when running the query in the notebook, I get the error: 
"ValueError: cannot select an axis to squeeze out which has size not equal to one"
