### ISSUE TITLE
[Feature]: we need a function of determine whether collection is loaded

### ISSUE THREAD

**Issue by changhong52** [milvus-io/milvus#22141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

we need a function of determine whether collection is loaded

### Describe the solution you'd like.

we need a function of determine whether collection is loaded

### Describe an alternate solution.

develop a function of determine whether collection is loaded

### Anything else? (Additional Context)

no

**Comment by SimFG** [comment]
You can check whether  the `utility.load_state` method has existed in the pymilvus version. If not, you can upgrade the version to `2.2.2`.

**Comment by changhong52** [comment]
2.2.0 already exist

**Comment by changhong52** [comment]
2.2.2 already exsit
