### ISSUE TITLE
[Bug]: Load timeout due to io_setup() failed in QueryNode

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#22152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-22114/3/pipeline
![image](https://user-images.githubusercontent.com/12216890/218420390-cb8ce3d3-5199-4d52-9fbf-79f870ff93b2.png)

**Comment by congqixia** [comment]
duplicated with #22123
