### ISSUE TITLE
[Bug]: How to expend the number of datanode ?

### ISSUE THREAD

**Issue by vesa1123** [milvus-io/milvus#22153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.2.2
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus
- OS(Ubuntu or CentOS): CentOS Linux release 7.9.2009 (Core)
- CPU/Memory: Intel(R) Xeon(R) CPU E5-2609 v3 @ 1.90GHz 6*2/ 128G
- GPU: /
- Others: /
```

### Current Behavior

Milvus cluster is installed with defualt deployments of docker-compose. When I reload more and more data, one only datanode is not enough。I find the error tip as belowing:

![企业微信截图_16757377552622](https://user-images.githubusercontent.com/124133960/218426783-d05330a6-f455-4fae-abec-22750b029934.png)

Then I use the following scripts to add the two multiple instances:

 datanode-1:
    container_name: milvus-datanode-1
    image: milvusdb/milvus:v2.2.2
    command: ["milvus", "run", "datanode"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      PULSAR_ADDRESS: pulsar://pulsar:6650
    depends_on:
      - "datacoord"

  datanode-2:
    container_name: milvus-datanode-2
    image: milvusdb/milvus:v2.2.2
    command: ["milvus", "run", "datanode"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      PULSAR_ADDRESS: pulsar://pulsar:6650
    depends_on:
      - "datacoord"

### Expected Behavior

But when I restart the serviece with commond:

docker-compose restart 

But the addtional datanodes starts failed:

![1676283214292](https://user-images.githubusercontent.com/124133960/218430581-a6bd627e-1dd5-419b-b65f-05eb2ff02355.png)

I'm confused about how to multiple instances of a service ?

**Comment by LoveEachDay** [comment]
@vesa1123 From the attu error output, you need increase the number of `querynode` instead of `datanode`.

`querynode` is responsible for loading data into memory and serving search requests. And `datanode` is responsible for consuming inserted data from message queue and inserting data into object storage.

@locustbaby will help you to diagnose the issue that multiple data nodes failed to start.

**Comment by locustbaby** [comment]
hi, @vesa1123  , I tested it myself and it did not reproduce.
Can't start your datanodes until now?
Would you mind checking the docker logs of those failed datanodes?
