### ISSUE TITLE
[Bug]: [benchmark][standalone] DISKANN index, 100m data load slowed down by 7%

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#22165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: PR-22074-20230208-fb4becd93
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.0.dev26
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

milvus image | load time
-- | --
PR-22074-20230208-fb4becd93 | 10116s
2.2.0-20230207-e3501f7a | 9445s

Machine configuration : 8c64G

diskann indexes 100 million data, load time slows down by 671s, a 7% slowdown

### Steps To Reproduce

```markdown
1. create a collection 
2. build DISKANN index on vector column
3. insert a 100 million of vectors
4. flush collection
5. build index 
6. load collection  --> Statistics time
```

**Comment by liliu-z** [comment]
@elstic can you help check whether this can be reproduced in Knowhere side? Do we have similar check in Knowhere's CI?

**Comment by liliu-z** [comment]
> > @elstic can you help check whether this can be reproduced in Knowhere side? Do we have similar check in Knowhere's CI?
> 
> In knowhere, the previous diskann index put the load in the first search, and the ci in knowhere ignores the check of the first search time, so there is no load time in the log. I could add it, but firstly we were given a threshold of 20% and now load is 7% slower and even if it were it probably wouldn't report an error, and secondly we don't have a precise time for load, we would print out the time for "first search+load".

Anyway, can you help triage this issue by running DiskANN load in Knowhere with different versions? So we can know whether this issue is from the algorithm.

**Comment by xige-16** [comment]
@yanliang567 Has the memory index slowed down?

**Comment by elstic** [comment]
> @yanliang567 Has the memory index slowed down?

Memory indexing has not slowed down

**Comment by elstic** [comment]
We ran the results using images from February 7 and February 8, so you can check the commits between those dates. (see image names)

**Comment by liliu-z** [comment]
> > Anyway, can you help triage this issue by running DiskANN load in Knowhere with different versions? So we can know whether this issue is from the algorithm.
> 
> Recent versions of knowhere, diskann index, sift 1m dataset, load time.
> 
> knowhere version	load time
> 1.3.7	27.675s
> 1.3.8	25.585s
> 2.0(load+first search )	26.5064s

Looks like this issue is not rooted in Knowhere.

**Comment by elstic** [comment]
image: 2.2.0-20230814-27fe2a45 
100m data load time: 8747.1404s
