### ISSUE TITLE
Continuously inserting data causes a lot of hard disk space to be consumed

### ISSUE THREAD

**Issue by zhouxiupeng** [milvus-io/milvus#2216]
**What is your question?**

**Comment by zhouxiupeng** [comment]
milvus 8.0，参数基本参照example 的配置。
我的原始特征是128位的，1.3G的文本文件。从晚上9点开始执行导入，每次导入一条，没有采用批量导入模式。早起发现128G的磁盘空间全部占完了。
今天白天重新进行了测试，其中过程如下：
逐条导入，
导入了1w个特征，磁盘占用4.6G，
select count(1) FROM milvus.TableFiles where table_id='example' 总记录 = 863     
当导入2w是，    
select count(1) FROM milvus.TableFiles where table_id='example' 总记录 = 1727
磁盘占用12G
当导入3w是，    
select count(1) FROM milvus.TableFiles where table_id='example' 总记录 = 2747
磁盘占用22G
当导入4w是，    
select count(1) FROM milvus.TableFiles where table_id='example' 总记录 = 3685
磁盘占用34G
当导入5w是，    
select count(1) FROM milvus.TableFiles where table_id='example' 总记录 = 4419
磁盘占用46G
再导入新的collection数据时，发现上面的数据一直在减少。
大概20分钟后，select count(1) FROM milvus.TableFiles where table_id='example' 总记录=1
磁盘大小33M 
新建colection,重新导入数据
导入了1w个特征，磁盘占用2.9G，
select count(1) FROM milvus.TableFiles where table_id='mycollection'  1035   

我的结论是：
如果collection一直有数据插入，磁盘空间占用一直增长，应该没有执行merger操作或merger操作非常缓慢，我不知道我的理解是否正确。
这应该是昨天我的磁盘空间被沾满的原因吧。
关于merger的启动机制不知道是怎么设定的？

**Comment by yhmo** [comment]
Background merge machinery:
1. insert n vectors, data write to buffer
2. background thread flush buffer into to disk as a small data file 'a'
3. insert m vectors, data write to buffer
4. background thread flush buffer into disk as a small data file 'b'
5. background merge thread found there are some small files, then merge the 'a' and 'b' to 'c', and set 'a' and 'b' to soft-delete, they will be deleted about 10 seconds later
6. insert vectors, data write to buffer
7. background thread flush buffer into disk as a small data file 'd'
8. background merge thread found there are some small files, then merge the 'c' and 'd' to 'e', and set 'c' and 'd' to soft-delete, they will be deleted about 10 seconds later
repeat the above steps...

**Comment by yhmo** [comment]
At the step 5, we can see there some duplicate data at a moment('c' = 'a' + 'b'), so the disk cost will is 'a' + 'b' + 'c', until 'a' and 'b' are deleted after 10 seconds.
Another reason is the /milvus/logs folder cost too much disk space, we already get a bug report about the /milvus/logs folder cost too much disk space. We will fix the issue in 0.9.0.

**Comment by yhmo** [comment]
Reproduce steps:
1. create collection
2. insert 1 vector one by one, with 0.2 second interval

After insert 2000 times, the 'db' folder is about 30GB(about 8000 segments)

**Comment by yhmo** [comment]
The mishard run in cluster mode, unused files will be deleted after 1 hour delay. With the above steps, 5 vectors were written into a single file in each second, and merge thread will merge the small files with previous files:
file_1 = 5 vectors
file_2 = file_1 + 5 vectors
file_3 = file_2 + 5 vectors
.....
file_(n) = file_(n-1) + 5 vectors

After file_(n) is merged completely, the file_(n-1) is marked as 'soft-delete', and parmanently deleted after 1 hour, so there lot of 'soft-delete' files occupy disk space.

**Comment by yhmo** [comment]
For single mode, insert 50000 times, disk cost no more than 300MB

**Comment by zhouxiupeng** [comment]
也就是说单机版没有问题。网络版才会有问题。网络版会在0.9版本增加变量file_deletion_delay。0.9版本有发布时间安排吗？

**Comment by yhmo** [comment]
0.9.0 will be released in middle of May. 
I created an issue for "file_deletion_delay" (#2231). 
The delete delay time could be risk in cluster mode if it was too short. Assume there are two nodes in mishard: node_A is read-only, node_B is writable. node_B merge file_a and file_b into file_c, and then soft-delete file_a and file_b, at the same time, node_A is performing search action and search vectors in file_a and file_b, load them from shared-storage. If the delete delay time is too sort, the file_a and file_b will be hard-deleted before node_A finish loading, then milvus will return error says "xxx file doesn't exist".

**Comment by yhmo** [comment]
#2231

**Comment by yhmo** [comment]
Link to #1942, optimize merge strategy.

**Comment by yhmo** [comment]
pr2250 add the  "file_deletion_delay" into server_config.yaml(under 'storage_config' item)
pr2277 implement a new strategy 'layered' to optimize merge process

**Comment by yhmo** [comment]
Use the following steps to compare 'layered' strategy and old strategy:
1. server_config_yaml,  file_cleanup_timeout=3600(second), start milvus server
2. create a collection, dimensionm=512, index_file_size=1024
3. insert 100 vectors per second, totally insert 20000 vectors

Layered strategy:  
disk cost: 1.6GB
time cost: 211 seconds

Old strategy:
disk cost: 4.9GB
time cost: 216 seconds

**Comment by yhmo** [comment]
already optimized in 0.9.0
