### ISSUE TITLE
[Enhancement]: Add a limitation for the number of collection

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#22162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Add a max.num.of.collection configuration, the default value is 1024

### Why is this needed?

Can not create collections unlimitedly, or it will cause some stability issues.

**Comment by xiaofan-luan** [comment]
looks good to me.
But be sure to make it a configurable params.
