### ISSUE TITLE
[Feature]: Is there an docker image of diskann

### ISSUE THREAD

**Issue by Sivannnnnn** [milvus-io/milvus#22178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

https://milvus.io/docs/disk_index.md#Prerequisites

The document says To use DiskANN, note that

You have run make disk_index=ON when you compile Milvus from the source.

I don't want to compile manually, there is no ready-made docker image？

**Comment by xige-16** [comment]
@Sivannnnnn You can directly use the image released by milvus. After version 2.1, the diskann function is supported.

**Comment by xige-16** [comment]
@Sivannnnnn Version 2.2.3 is recommended

**Comment by Sivannnnnn** [comment]
> @Sivannnnnn Version 2.2.3 is recommended

OK ,thinks
