### ISSUE TITLE
[Enhancement]: Support config a complete URL for S3

### ISSUE THREAD

**Issue by haorenfsa** [milvus-io/milvus#22185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Currently we need config 3 or more fields(if using IAM) when we want to use S3 or other cloud service for object storage.
They're 
- `minio.address`
- `minio.port`
- `minio.useSSL`

These can be simplified by providing a configuration of complete URL, for example from `https://s3.amazonaws.com`, we can infer that its port is 443, and useSSL is true.

P.S. Further more we can take more advanvage of URL to make the configuration even simpler like: `s3://bucketname`, `gcs://bucketname`

**Comment by cyrusvahidi** [comment]
right now I am having trouble even understanding the S3 config. what is supposed to go in `minio.address` and `minio.port`? `https://s3.amazonaws.com` and `443`? or is it my own VPC endpoint created on S3?

**Comment by haorenfsa** [comment]
Use s3.amazonaws.com or regional hostname for address, and 443 for port

**Comment by haorenfsa** [comment]
In first stage, we can use a field like `minio.url` to replace 
- `minio.address`
- `minio.port`
- `minio.useSSL`

The translation examples:
url: `https://s3.amazonaws.com` -> 
address: `s3.amazonaws.com`
port:`443`
useSSL:`true`


url: `http://my-object-storage-host` -> 
address: `my-object-storage-host`
port:`80`
useSSL:`false`
