### ISSUE TITLE
[Bug]:  upexcepted error when shard num equals max configuration,cause create collection failed.

### ISSUE THREAD

**Issue by yelusion2** [milvus-io/milvus#22189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.3
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

upexcepted error when shard num equals max configuration, cause create collection failed.

### Expected Behavior

when shard num equals max configuration can create collection.

### Steps To Reproduce

```markdown
1. start up a milvus, config dmlchannelNum=a, maxShardNum=b

2. create a conllection and set its shardNum=min(a,b)
```

**Comment by longjiquan** [comment]
already fixed in #22188 , please help to check this.
/assign @yelusion2
