### ISSUE TITLE
[Enhancement]: Support Stats log check point

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#22184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Currently, each segment of milvus owns bunch of insert bin log and stats log.
insert bin log and stats log is actually 1-1 mapping.
With frequent sync/flush, stats log number becomes huge, which lead to slow watch dml channel request.
The reason why dml channel watch is slow is because object storage system such as S3 and minio has strict limitation on QPS, usually a few thousand level per prefix.

To Fix that, one possible way is to introduce stats log checkpoint mechanism. packing all statslog file into a large file to avoid large QPS. 1B entities require around 800MB BF,  which should be a reasonable size to be read in less than 10 seconds.  

The stats log checkpoint only worked as a cache. When we watch dml channel, the first thing is to load the last stats log checkpoint(If it exist). And then when we load each segment, we will skip single stats log if it's already in checkpoint file so the load IOPs required will dramatically increased
 

### Why is this needed?

Improve failure recovery speed  and accelerate load performance.

**Comment by congqixia** [comment]
Look good to me. Just small details:
- `Statslog Checkpoint` shall only contains data from sealed segments
- `Statslog Checkpoint` cannot be generated too frequently to avoid storage/traffic waste. We need a reasonable strategy to determine when to generate it.

**Comment by xiaofan-luan** [comment]
> Look good to me. Just small details:
> 
> * `Statslog Checkpoint` shall only contains data from sealed segments
> * `Statslog Checkpoint` cannot be generated too frequently to avoid storage/traffic waste. We need a reasonable strategy to determine when to generate it.

For sure. we could generate checkpoint in a background task per hour. We don't need to update checkpoint each time segment modified since it's only a cache. If compaction happened and some of the stats log missed in the checkpoint we will just reload from new segment

Compaction should still be very important to reduce stats log numbers.

**Comment by xiaofan-luan** [comment]
keep it open
