### ISSUE TITLE
No address added out of total 1 resolved 请问干净的系统安装出现这个错误怎么处理啊？

### ISSUE THREAD

**Issue by apple12358lp** [milvus-io/milvus#2219]
**What is your question?**
`Welcome to use Milvus!
Milvus Release version: v0.8.0, built at 2020-04-14 15:32.37, with OpenBLAS library.
You are using Milvus GPU edition
Last commit id: 464400767f8723b9867755c63ab07f7cfe2ecb29

Loading configuration from: ../conf/server_config.yaml
Initializing log config from: ../conf/log_config.conf
GPU resources ENABLED !
Milvus server started successfully!
E0503 17:35:13.310124509      25 server_chttp2.cc:40]        {"created":"@1588498513.310100755","description":"No address added out of total 1 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":394,"referenced_errors":[{"created":"@1588498513.310097084","description":"Unable to configure socket","fd":26,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":217,"referenced_errors":[{"created":"@1588498513.310094966","description":"Cannot assign requested address","errno":99,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":190,"os_error":"Cannot assign requested address","syscall":"bind"}]}]}
Milvus server is going to shutdown ...
terminate called after throwing an instance of 'std::system_error'
  what():  Resource deadlock avoided
./start_server.sh: line 3:     7 Aborted                 (core dumped) ../bin/milvus_server -c ../conf/server_config.yaml -l ../conf/log_config.conf
`

**Comment by tinkerlin** [comment]
This error means the 19530 port is occupied already. You may try to switch to another port, or you can change the default port in `server_config.yaml`. @apple12358lp

**Comment by apple12358lp** [comment]
ok,thank you.
