### ISSUE TITLE
[Bug]: collection.num_entities doesn't match the number of insert Data

### ISSUE THREAD

**Issue by shiyu22** [milvus-io/milvus#22196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: Milvus 2.2.2
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Mac
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Issue from [#131](https://github.com/towhee-io/examples/issues/131)

**Comment by yanliang567** [comment]
can we get the milvus logs?

**Comment by shiyu22** [comment]
I'm trying milvus2.2.3 and running `flush()` before `num_entities`, it works fine. And will close this issue.
