### ISSUE TITLE
[Bug]: [Nightly]Query a value on a partition which discard it will return a result

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#22210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:cad39eb
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.2.dev8
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Query a value on a partition which discard it will return a result.
```
[2023-02-15T21:28:28.590Z] [2023-02-15 20:07:20 - DEBUG - ci_test]: (api_request)  : [Collection.delete] args: ['varchar in [ "0"]', '_default', 120], kwargs: {} (api_request.py:56)
[2023-02-15T21:28:28.590Z] [2023-02-15 20:07:20 - DEBUG - ci_test]: (api_response) : (insert count: 0, delete count: 1, upsert count: 0, timestamp: 439482224573415430, success count: 0, err count: 0)  (api_request.py:31)
[2023-02-15T21:28:28.590Z] [2023-02-15 20:07:20 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 120} (api_request.py:56)
[2023-02-15T21:28:28.590Z] [2023-02-15 20:07:23 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)
[2023-02-15T21:28:28.590Z] [2023-02-15 20:07:23 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['float_vector', {'index_type': 'FLAT', 'params': {}, 'metric_type': 'L2'}], kwargs: {'timeout': 1200, 'index_name': ''} (api_request.py:56)
[2023-02-15T21:28:28.590Z] [2023-02-15 20:07:24 - DEBUG - ci_test]: (api_response) : Status(code=0, message=)  (api_request.py:31)
[2023-02-15T21:28:28.590Z] [2023-02-15 20:07:24 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:56)
[2023-02-15T21:28:28.590Z] [2023-02-15 20:07:28 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)
[2023-02-15T21:28:28.590Z] [2023-02-15 20:07:28 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ['varchar in [ "0"]', None, ['_default'], 120], kwargs: {} (api_request.py:56)
[2023-02-15T21:28:28.590Z] [2023-02-15 20:07:28 - DEBUG - ci_test]: (api_response) : [{'varchar': '0'}]  (api_request.py:31)
```

### Expected Behavior

return empty

### Steps To Reproduce

```markdown
1. init collection and partition
2. insert same data into partition_w and default partition
3. delete same id 0 from default_partition, and query on it get empty result -> raise error
```

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/97/pipeline/156/
2. log: [artifacts-milvus-distributed-kafka-nightly-97-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/97/artifact/artifacts-milvus-distributed-kafka-nightly-97-pymilvus-e2e-logs.tar.gz)
3. failed time: [2023-02-15T20:07:29.253Z] [gw3] [ 17%] FAILED testcases/test_delete.py::TestDeleteString::test_delete_from_partitions_with_same_ids_of_string
4. test case:
```python
@pytest.mark.tags(CaseLabel.L1)
def test_delete_from_partitions_with_same_ids_of_string(self):
    """
    target: test delete same ids from two partitions with same data
    method: 1.insert same nb data into two partitions
            2.delete same ids from partition_1
    expected: The data only in partition_1 will be deleted
    """
    # init collection and partition
    schema = cf.gen_string_pk_default_collection_schema()
    collection_w = self.init_collection_wrap(name=cf.gen_unique_str(prefix), schema=schema)
    partition_w = self.init_partition_wrap(collection_wrap=collection_w)

    # insert same data into partition_w and default partition
    df = cf.gen_default_dataframe_data(tmp_nb)
    collection_w.insert(df)
    partition_w.insert(df)

    # delete same id 0 from default_partition, and query on it get empty result
    collection_w.delete(default_string_expr,
                        partition_name=ct.default_partition_name)
    assert collection_w.num_entities == tmp_nb * 2
    collection_w.create_index(ct.default_float_vec_field_name, index_params=ct.default_flat_index)
    collection_w.load()
    collection_w.query(default_string_expr, partition_names=[ct.default_partition_name],
                       check_task=CheckTasks.check_query_empty)

    # query on partition_w with id 0 and get an result
    collection_w.query(default_string_expr, partition_names=[partition_w.name],
                       check_task=CheckTasks.check_query_results, check_items={exp_res: query_tmp_expr_str})
```

**Comment by NicoYuan1986** [comment]
keep reproduced.
link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/101/pipeline/188
log: [artifacts-milvus-distributed-pulsar-nightly-101-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/101/artifact/artifacts-milvus-distributed-pulsar-nightly-101-pymilvus-e2e-logs.tar.gz)
failed cases: 
```
test_delete_from_partitions_with_same_ids
test_delete_from_partitions_with_same_ids_of_string
test_query_another_partition
```

**Comment by NicoYuan1986** [comment]
Latest: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/102/pipeline/144
log: [artifacts-milvus-distributed-kafka-nightly-102-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/102/artifact/artifacts-milvus-distributed-kafka-nightly-102-pymilvus-e2e-logs.tar.gz)

**Comment by bigsheeper** [comment]
The old "GetDistribution" logic is:
https://github.com/milvus-io/milvus/blob/dc6c7ddbeef321601571961dd126624b99aff62d/internal/querynode/shard_cluster_version.go#L48-L60


Currently "GetDistribution" logic is modified to:
https://github.com/milvus-io/milvus/blob/dc6c7ddbeef321601571961dd126624b99aff62d/internal/querynode/snapshot.go#L73-L91

The difference is currently "GetDistribution" would return a `SnapshotItem` even though the segment is empty, so shard follower would receive a query request with empty queried segments:

`[2023/02/22 15:28:29.437 +08:00] [DEBUG] [querynode/impl.go:1098] ["Received QueryRequest"] [traceID=1aac45d3b7dfe1fb] [msgID=439628833590083585] [fromShardleader=true] [vChannels="[by-dev-rootcoord-dml_1_439628828535422979v1]"] [segmentIDs="[]"] [guaranteeTimestamp=439628833590083585] [timeTravel=439628833590083585] [partitionIDs="[439628828535422980]"]`


And shard follower would query all segments, which not belongs to the queried partition:
https://github.com/milvus-io/milvus/blob/dc6c7ddbeef321601571961dd126624b99aff62d/internal/querynode/validate.go#L66-L73

We should check if the segments distribution is empty before transferring query request, if it is, then we don't transfer it, this could save an rpc overhead and also avoid this issue.

**Comment by NicoYuan1986** [comment]
Fixed.
