### ISSUE TITLE
[Bug]:  Correct usage of Ticker and Timer

### ISSUE THREAD

**Issue by czs007** [milvus-io/milvus#22222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master/2.x
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

## Timer Vesus Ticker

Timers — These are used for one-off tasks. It represents a single event in the future. 
        You tell the timer how long you want to wait, and it provides a channel that will be notified at that time. You can call Stop prevents the Timer from firing. 
        Stop  returns true if the call stops the timer, false if the timer has already expired or been stopped. 

Tickers — Tickers are exceptionally helpful when you need to perform an action repeatedly at given time intervals. 
        We can use tickers, in combination with goroutines to run these tasks in the background of our applications.  

## For repeated- tasks,  use Ticker 
Although Timer can also help to achieve this (Reset, for example), there are many details that need to be paid attention to, especially in the case of Stop （You can refer to this discussion  https://github.com/golang/go/issues/27169 ）. 

**When using Ticker,  remember to stop it to release associated resources.**

## For one-off task,  use Timer or time.After
As  for  time.After, it waits for the duration to elapse and then sends the current time on the returned channel. It is equivalent to NewTimer(d).C.
The underlying Timer is not recovered by the garbage collector until the timer fires. If efficiency is a concern, use NewTimer  instead and call Timer.Stop if the timer is no longer needed.
 
**Avoid using time.After when you have a For loop**

```
    	for {
		select {
		 ...
		case <-time.After(time.Minute * 3):
		}
	    }
```

In this use case, it may cause a large number of Timer objects to be created, although these large objects will be GCed later.

## Do not use time.Tick 
Tick is a convenience wrapper for NewTicker providing access to the ticking channel only. 
While Tick is useful for clients that have no need to shut down the Ticker, be aware that without a way to shut it down the underlying Ticker cannot be recovered by the garbage collector; it "leaks". 

In milvus, there is no such usage scenario, so the use of time.Tick is prohibited

**Comment by congqixia** [comment]
Good point! We need a linter for these cases
