### ISSUE TITLE
[Bug]: [ResourceGroup]Fail to describe resource group after trying to transfer 0 replica to it

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#22246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230216-8ec5ba13
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):  pymilvus-2.3.0.dev38
```

### Current Behavior

try to transfer 0 replica from default rg to a rgA, it fails with error: 
`msg: 'failed to transfer replica between resource group, err=NotHealthy'}`

after that, try to describe the rgA, it fails with error
`message=failed to describe resource group, err=NotHealthy`
what's more, if trying to load a new collection to default rg at this moment, it fails 
` message=failed to load collection, err=NotHealthy`

### Expected Behavior

transfer 0 replica shall be forbidden with a meaningful msg, and it shall not break anything else.

### Steps To Reproduce

```markdown
test_transfer_replica_with_wrong_num_replica

transfer_replica(source=ct.default_resource_group_name,
                                           target=rg_name,
                                           collection_name=collection_w.name,
                                           num_replica=0)
```

**Comment by weiliu1031** [comment]
please verify this

**Comment by yanliang567** [comment]
verified on 2.2.0-20230228-91d251ab
