### ISSUE TITLE
[Bug]: The ttl function is invalid for setting the time of one week in seconds

### ISSUE THREAD

**Issue by jiaminger** [milvus-io/milvus#22247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.2
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus): 2.2.1
- OS(Ubuntu or CentOS): Ubuntu  18.04
- CPU/Memory: 32G
- GPU: 
- Others:
```

### Current Behavior

When I set the ttl parameter in seconds as the time of a week, 7 * 24 * 60 * 60 seconds, but the data in the collection that exceeds the time of a week is not automatically deleted.

I modify the setting for 180 seconds, and the test data can be automatically deleted.

Is there an upper limit in seconds? Can you set ttl time in days？

### Expected Behavior

When the time of the week is up data should be automatically deleted

**Comment by jaime0815** [comment]
Data may not be removed immediately when reaches configured TTL time, it depends on the compaction mechanism. The data will not be queryable after the expired segments are compacted, by the way, at this time Milvus still doesn't clean data from Minio/S3 until the next cycle of GC arrived.

 you can observe it again after a period of time.
