### ISSUE TITLE
Define cache setting in MB rather then GB

### ISSUE THREAD

**Issue by hoesler** [milvus-io/milvus#2225]
Defining `cache_config.cpu_cache_capacity`, `cache_config.insert_buffer_size` and `gpu_resource_config.cache_capacity ` in GB is too coarse grained in my opinion.
On servers with limited memory this would enable more fine-tuned adjustments.

**Comment by cydrain** [comment]
We need discuss with this, if we should unify all settings in config file to use MB.

**Comment by hoesler** [comment]
To give you a bit more context: I am playing around with the horizontal scalability of milvus on kubernetes using mishards. For a simple smoke test, I already needed 4GB worker nodes (t3.medium), because the smallest setting is 1GB cpu_cache_capacity + 1GB insert_buffer_size. Admitting this is not a real world use case, I think allowing to spin up milvus with a smaller footprint would simplify to try out milvus.

**Comment by JackLCL** [comment]
@hoesler Thanks for your advice. Welcome to join our slack channel and communicate with us more about milvus. 
Slack Link: https://milvusio.slack.com/join/shared_invite/zt-e0u4qu3k-bI2GDNys3ZqX1YCJ9OM~GQ

**Comment by scsven** [comment]
Now, Milvus can setting these values with unit (B, KB, MB, GB).
