### ISSUE TITLE
No logs in docker logs directory

### ISSUE THREAD

**Issue by willamhou** [milvus-io/milvus#2226]
**Describe the bug**
I run the example code demo, but there are no logs in logs directory
**Steps/Code to reproduce behavior**
run example python code, observe the logs directory

**Expected behavior**
In logs directory, there are logs.

**Environment details**
- Hardware/Softward conditions  Centos 16core 48G  Milvus
- Method of installation (Docker, or from source) Docker
- Milvus version (v0.3.1, or v0.4.0) V0.8.0
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**
![image](https://user-images.githubusercontent.com/8574759/81130828-b8a82c80-8f7b-11ea-83d4-8696486492f4.png)

**Additional context**

**Comment by BossZou** [comment]
@willamhou Please provide your log configure file, which is under folder `conf`.

**Comment by willamhou** [comment]
![image](https://user-images.githubusercontent.com/8574759/81135199-b1881b00-8f89-11ea-801a-695cb6429adf.png)
This is the log config in docker.

**Comment by BossZou** [comment]
@willamhou May you provide your docker command to run milvus server docker ? Did you map log folder into your host machine?

**Comment by willamhou** [comment]
I user the docker commond provided by milvus.io. This is the link https://milvus.io/cn/docs/v0.8.0/guides/get_started/install_milvus/cpu_milvus_docker.md

The docker command is that
docker run -d --name milvus_cpu \
-p 19530:19530 \
-p 19121:19121 \
-p 9091:9091 \
-v /home/$USER/milvus/db:/var/lib/milvus/db \
-v /home/$USER/milvus/conf:/var/lib/milvus/conf \
-v /home/$USER/milvus/logs:/var/lib/milvus/logs \
-v /home/$USER/milvus/wal:/var/lib/milvus/wal \
milvusdb/milvus:0.8.0-cpu-d041520-464400


And I did map the log folder to host machine:
![image](https://user-images.githubusercontent.com/8574759/81154323-5fa9ba00-8fb6-11ea-83cc-4faee3ac287a.png)

**Comment by BossZou** [comment]
I tried in my host machine and all is well. Is there any files under folder `db`? If configuration is correct, I guess there are some permission issue.

**Comment by willamhou** [comment]
![image](https://user-images.githubusercontent.com/8574759/81161015-7bfd2500-8fbd-11ea-8dca-f00b1de6b0bd.png)
In db directory, there are files.  The permission is root~

**Comment by BossZou** [comment]
It's strange. May you provide the output in console by running command `docker logs $docker-id`?

**Comment by willamhou** [comment]
![image](https://user-images.githubusercontent.com/8574759/81165290-558eb800-8fc4-11ea-9dfa-f9eea54657cc.png)
This is the output in console using docker logs

**Comment by BossZou** [comment]
@willamhou May you show me milvus folders permission under folder `/home/$USER/milvus` by running `ll` or `ls -l`? I found logs was output to console rather than log files. It's much possible that milvus docker have no permission to write logs.

**Comment by willamhou** [comment]
![image](https://user-images.githubusercontent.com/8574759/81172732-5f6ae800-8fd1-11ea-8fa6-9719e7edbc75.png)

The permission is root too~

**Comment by BossZou** [comment]
@willamhou May you try to restart milvus docker, just do nothing and show the output in milvus docker console? If server start incorrectly, some information will be output in console.
And please show more details about your host environment (OS, CPU details).

**Comment by willamhou** [comment]
![image](https://user-images.githubusercontent.com/8574759/81466496-bdcbdc80-9204-11ea-9969-e635f735cceb.png)
I restart the docker. I see  ”ASSERT FAILURE“  with docker logs. This may be the reason~

**Comment by BossZou** [comment]
> ![image](https://user-images.githubusercontent.com/8574759/81135199-b1881b00-8f89-11ea-801a-695cb6429adf.png)
> This is the log config in docker.

I found your logs file start with 'BAL:', however, it should be '* GLOBAL:'
![log](https://user-images.githubusercontent.com/40255591/81467348-ad1e6500-920a-11ea-8b17-56fcb43b602f.png)
[Here](https://github.com/milvus-io/milvus/blob/0.8.0/core/conf/demo/log_config.conf) is a correct log config file

**Comment by willamhou** [comment]
Yeap, I recheck the config, find this. When I wget the config. The log config maybe changed. Thx for your help~~~
