### ISSUE TITLE
[Bug]: milvus: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by janelu9** [milvus-io/milvus#22292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0
- Deployment: standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu): 18.04
- CPU/Memory: 16g
- GPU: 16
- Others:
```

### Current Behavior
sudo apt install software-properties-common
sudo add-apt-repository ppa:milvusdb/milvus-standalone
sudo apt update
sudo apt install milvus

### Milvus Log

milvus: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by milvus)

milvus: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by milvus)

milvus: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by milvus)

**Comment by jiaoew1991** [comment]
@janelu9 Hi, it seems the glibc in your system is too old, you can try to upgrade to ubuntu 20.04+ or install a newer version of glibc, the upgrade glibc code you can ref https://github.com/milvus-io/milvus/blob/57f8de95c1af63f32b2565a221d8caa7abee2594/build/docker/builder/cpu/centos7/Dockerfile#L27-L36

**Comment by janelu9** [comment]
> mkdir /tmp/stdlib && cd /tmp/stdlib && \ 
>      wget https://repo.anaconda.com/archive/Anaconda3-2022.10-Linux-x86_64.sh && \ 
>      sh Anaconda3-2022.10-Linux-x86_64.sh -b -p conda && \ 
>      cp conda/lib/libstdc++.so.6.0.29 /usr/lib64 && \ 
>      rm /usr/lib64/libstdc++.so.6 && \ 
>      ln -s /usr/lib64/libstdc++.so.6.0.29 /usr/lib64/libstdc++.so.6 && \ 
>      cp conda/lib/libatomic.so.1.2.0 /usr/lib64 && \ 
>      ln -s /usr/lib64/libatomic.so.1.2.0 /usr/lib64/libatomic.so && \ 
>      ln -s /usr/lib64/libatomic.so.1.2.0 /usr/lib64/libatomic.so.1 && \ 
>      rm -rf /tmp/stdlib

but I con't install milvus by command `add-apt-repository ppa:milvusdb/milvus-standalone` on  ubuntu 20.04+

**Comment by janelu9** [comment]
> @janelu9 Hi, it seems the glibc in your system is too old, you can try to upgrade to ubuntu 20.04+ or install a newer version of glibc, the upgrade glibc code you can ref
> 
> https://github.com/milvus-io/milvus/blob/57f8de95c1af63f32b2565a221d8caa7abee2594/build/docker/builder/cpu/centos7/Dockerfile#L27-L36

Now I have installed milvus on ubuntu 20.04 , but how can I start the server by `milvus run`?

**Comment by yanliang567** [comment]
Milvus standalone and its dependencies (etcd and MinIO) start automatically.  please check the link for details https://milvus.io/docs/v2.1.x/install_standalone-aptyum.md#Install-Milvus-Standalone-with-APTYUM
