### ISSUE TITLE
[Bug]: Query too slowly

### ISSUE THREAD

**Issue by linggong2011** [milvus-io/milvus#22315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Query no response

### Milvus Log

[2023/02/21 03:51:00.653 +00:00] [WARN] [rootcoord/timeticksync.go:289] ["rootcoord send tt to all channels too slowly"] [chanNum=6] [span=234]

**Comment by Cheung7788** [comment]
[logs.tar(4).gz](https://github.com/milvus-io/milvus/files/10789940/logs.tar.4.gz)

**Comment by congqixia** [comment]
Hi @linggong2011
From the log @Cheung7788 attached. There is no incoming request in proxy logs. Looks like `attu` did not connect to the right address.
Could you please test with sdk (say  pymilvus , go-sdk or java sdk)?

**Comment by Cheung7788** [comment]
After restarting the milvus cluster, the search operation fails, and the log is ：

[logs.tar(5).gz](https://github.com/milvus-io/milvus/files/10791195/logs.tar.5.gz)
