### ISSUE TITLE
Cancel method for async flush/search/...

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#2232]
**Is your feature request related to a problem? Please describe.**
Java async concurrent class provide calling `cancel` to support more async functions, milvus interface should also provide these functions, to meet the async methods.
The following code copied from `Future.java`
```
    boolean cancel(boolean mayInterruptIfRunning);

    /**
     * Returns {@code true} if this task was cancelled before it completed
     * normally.
     *
     * @return {@code true} if this task was cancelled before it completed
     */
    boolean isCancelled();
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by tinkerlin** [comment]
All current SDKs not support async cancel method.
