### ISSUE TITLE
IDMAP search time on GPU is not stable

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#2233]
**Describe the bug**
`topk=1`
![Screenshot_2020-05-06 cpu_sift_50m_search_flat](https://user-images.githubusercontent.com/56623710/81169362-5545eb00-8fcb-11ea-9b23-63b9ea856849.png)
`topk=10`
![Screenshot_2020-05-06 cpu_sift_50m_search_flat(1)](https://user-images.githubusercontent.com/56623710/81171270-b3c09880-8fce-11ea-804d-c98d4236aa43.png)

This issue not happened on searching with IVF_FLAT:
![Screenshot_2020-05-06 gpu_sift_50m_search_flat(1)](https://user-images.githubusercontent.com/56623710/81169706-dbfac800-8fcb-11ea-8911-a471cb65b229.png)

**Steps/Code to reproduce behavior**
`search params`:
```
        "server.value.mode": "GPU",
        "collection.dataset_name": "sift_50m_2048_128_l2",
        "index.index_type": "flat",
        "search.nq": 200,
        "search.topk": 1,
        "search.search_param.nprobe": 8
```
**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
relate to #1859

**Comment by shengjun1985** [comment]
relate to #1976

**Comment by shengjun1985** [comment]
@ThreadDao 
We have fixed a bug that copy data from CPU to GPU in #4174.
Please help to confirm the performance in 0.10.4. Thank you.

**Comment by shengjun1985** [comment]
Fixed.
