### ISSUE TITLE
[Bug]: Got RPC terminated exception

### ISSUE THREAD

**Issue by linggong2011** [milvus-io/milvus#22338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 16/32
- GPU: 
- Others:
```

### Current Behavior

Got RPC terminated exception as below
![img_v2_7007ab49-2227-42db-a9b5-28e0a6c93afg](https://user-images.githubusercontent.com/6279934/220548689-51932e1c-b742-4af9-bb43-47eec0d9c534.jpg)

### Expected Behavior

stable

### Milvus Log

[logs.tar.gz](https://github.com/milvus-io/milvus/files/10800990/logs.tar.gz)

**Comment by congqixia** [comment]
Hi @linggong2011  Thanks for reporting this issue.
One quick question, does your client use multi-processes and share connection between them. It might be a known issue for `pymilvus` client. The connection shall be thread exclusive and can not be shared.
