### ISSUE TITLE
QueryNode, DataNode, Querycoord error - Back-off restarting failed container querynode

### ISSUE THREAD

**Issue by mjafar84** [milvus-io/milvus#22355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.3
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Redhat
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I have installed Milvus 2.2.3 cluster on local Kubernetes  with Helm (3 master and 5 worker node).
I have assigned components to specific nodes and use S3 as external storage.
Querynode, Datanode, Indexnode --> worker2 and worker4
Rootcoord, querycoord,datacoord,indexcoord,proxy --> worker1 ad worker5
etcd, pulsar, S3 --> worker3
I have used NFS extrnal provisioner and force it to work  on worker3 only (data persistence).

I will attach all logs as screenshot.  If config data required I can send.
 Actually I doubt about data/query/index/node, if it is required any pvc to assign or not? 

### Milvus Log

pods status
![all](https://user-images.githubusercontent.com/123801973/220620755-529decb9-c6f6-4bbd-b8a1-9efd4b097209.jpeg)

describe pod my2-milvus-querynode-664fc756b4-4ns76
![all1](https://user-images.githubusercontent.com/123801973/220620914-b52185e0-a030-4409-b077-698b2a7ec0c9.jpeg)

describe pod my2-milvus-datanode-6b94c4d9ff-r6gpr
![all2](https://user-images.githubusercontent.com/123801973/220621022-bcb1ceb6-d431-4d9f-bdf9-37280bfbda70.jpeg)

describe pod my2-milvus-querycoord-799658f888-7nrt6
![all3](https://user-images.githubusercontent.com/123801973/220621077-bde481f1-0511-4d72-b2b8-322585cc0e66.jpeg)

### Anything else?

[](url)

**Comment by mjafar84** [comment]
One more thing from pods logs I found it is related  to externalS3 . We have local S3 used with it. Can you please give another example for this part. Please consider that the S3 is local not on cloud AWS.
externalS3:
  enabled: true
  host: "s3.test.loc"
  port: "80"
  accessKey: "xcbxbxcb"
  secretKey: "xvbxbxb"
  useSSL: false
  bucketName: "milvus"
  rootPath: "s3://milvus"
  useIAM: false
  cloudProvider: "aws"
  iamEndpoint: ""

**Comment by locustbaby** [comment]
hi @mjafar84 , 
about your question:
`Actually I doubt about data/query/index/node, if it is required any pvc to assign or not?`
From my test, there is no pvc, you can check pod's yaml to confirm

As for the local S3 config you said, I guess you already get the pod's logs, is there any logs about this?
An example here, maybe you can change the rootPath and test again.
```yaml
minio:
  enabled: false
    
externalS3:
  enabled: true
  host: "minio.default.svc.cluster.local"
  port: "9000"
  accessKey: ""
  secretKey: "
  useSSL: false
  bucketName: "milvus-1"
  rootPath: "files"
```

**Comment by mjafar84** [comment]
Issue is solved with SSL certificate embedded to milvus image. Thanks @locustbaby
