### ISSUE TITLE
[Bug]: if i restart milvus culster, i got "fail to save the role" by rootcoord

### ISSUE THREAD

**Issue by eliassama** [milvus-io/milvus#22350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.2
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS): container
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

if i restart milvus culster, i got "fail to save the role" by rootcoord

![image](https://user-images.githubusercontent.com/79587688/220587464-91f51617-2ac3-41de-82f1-99a145d651bf.png)

and the datanode report 
![image](https://user-images.githubusercontent.com/79587688/220587531-39c9467b-3ca8-4dfb-8d51-61deed3ee1da.png)
![image](https://user-images.githubusercontent.com/79587688/220588403-4286a2bf-41b5-4f66-95f6-7220c13761e0.png)

and the datacoord report
![image](https://user-images.githubusercontent.com/79587688/220587844-42ea9385-117a-494c-8f7d-a6b2754eefcd.png)
![image](https://user-images.githubusercontent.com/79587688/220587960-babcfbf1-ccea-40a7-a5c6-f594f1634401.png)
![image](https://user-images.githubusercontent.com/79587688/220588033-24963d64-6b36-49f0-b22e-69bca912f48c.png)
 

### Steps To Reproduce

```markdown
just milvus-culster is too slow, i restart milvus-culster and upgrade pulsar's disk.
```

**Comment by eliassama** [comment]
and pulsar is normal

**Comment by SimFG** [comment]
@eliassama Can you provide the log of milvus startup? like:
![image](https://user-images.githubusercontent.com/21985684/220609498-c08d9247-4732-4a78-8307-74a6832c8f59.png)

**Comment by eliassama** [comment]
![image](https://user-images.githubusercontent.com/79587688/220617303-f68466b3-a38b-440b-891e-e251125a6618.png)


> @eliassama Can you provide the log of milvus startup? like: ![image](https://user-images.githubusercontent.com/21985684/220609498-c08d9247-4732-4a78-8307-74a6832c8f59.png)

**Comment by eliassama** [comment]
and i upgrade 2.2.3, just have same error

**Comment by eliassama** [comment]
and i rollback , just same 
![image](https://user-images.githubusercontent.com/79587688/220617719-4e140356-81ae-47c2-b05a-996c3a859f3b.png)

**Comment by SimFG** [comment]
had you also got "fail to save the role" by rootcoord? like:
![image](https://user-images.githubusercontent.com/21985684/220617782-ef8ebcf8-fc23-4bcc-b2b5-cb42f0ee09f8.png)

**Comment by SimFG** [comment]
all nodes have upgrade to 2.2.3?

**Comment by eliassama** [comment]
right

> had you also got "fail to save the role" by rootcoord? like: ![image](https://user-images.githubusercontent.com/21985684/220617782-ef8ebcf8-fc23-4bcc-b2b5-cb42f0ee09f8.png)
2.2.2 and 2.2.3 is same fail.

![image](https://user-images.githubusercontent.com/79587688/220618402-6483ba8a-bba5-404b-830c-f99f354246fb.png)
![image](https://user-images.githubusercontent.com/79587688/220618675-148ad21c-70b7-4c7b-b3a8-534df7562cb2.png)

**Comment by eliassama** [comment]
> all nodes have upgrade to 2.2.3?

yes. four coord,and three kinds of nodes to upgrade 2.2.3.

It is the same whether all nodes are upgraded to 2.2.3 or all nodes are rolled back to 2.2.2

**Comment by SimFG** [comment]
I look at the error, it won't influence the milvus service. You can try if it works normally. I will refine the log, thanks your feedback.

**Comment by eliassama** [comment]
and i think the another big question is dataNode can not create consumer
![image](https://user-images.githubusercontent.com/79587688/220619871-c7c523c9-522b-4aee-8745-b0b0c2450bdf.png)
![image](https://user-images.githubusercontent.com/79587688/220620367-6be7f7c6-2355-4d55-91c3-c5b729e13691.png)
![image](https://user-images.githubusercontent.com/79587688/220620469-5fd52c1d-fd22-481f-af4b-d2774c3310a4.png)

**Comment by eliassama** [comment]
> I look at the error, it won't influence the milvus service. You can try if it works normally. I will refine the log, thanks your feedback.

yes. i think so. I can still use attu with this error. 

But at present all the data can not be written, query.

I think it may be because dataNode cannot consume.

**Comment by SimFG** [comment]
Is it convenient to provide a complete log

**Comment by eliassama** [comment]
> Is it convenient to provide a complete log
Hold on. I think I may have found the cause of the problem.

**Comment by yanliang567** [comment]
@eliassama so what is going on here, could you please share the results?

/unassign
