### ISSUE TITLE
[Enhancement]: Refine ErrorCode, make error message more readable

### ISSUE THREAD

**Issue by jiaoew1991** [milvus-io/milvus#22389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

The ErrorCode in Milvus was not used well, we even do not have a clear ErrorCode guideline.
Try to define an ErrorCode guideline and migrate old code to the new guideline.

**Comment by xiaofan-luan** [comment]
can we have the error code rule in Milvus documentation?

**Comment by jiaoew1991** [comment]
> can we have the error code rule in Milvus documentation?

Yes, we should add some guidelines in doc, such as errorcode, config, etc
