### ISSUE TITLE
[Enhancement]: Replace `const std::string&` with `std::string_view`

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#22408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Replace all `const std::string&` with `std::string_view`

### Why is this needed?

`std::string_view` could improve the performance and cover more use cases.

Also it's easy to make mistake when we use template with `std::string` like:
```c++
template<typename T>
bool equal(T x, T y)
```
This template works well for types with small size, but will impact the performance significantly with `std::string`.
If change the parameter type to `const T&`, this will bring pointer operations for small type, which also not performs best

We can define a type template like:
```c++
template<typename T>
using Parameter = std::conditional_t<std::is_same_v<T, std::string>, std::string_view, T>
```
Then using Parameter <T> as the parameter type with template functions to reach best performance

**Comment by xiaofan-luan** [comment]
good catch!
