### ISSUE TITLE
[Bug]: int8, int16, int32 fieldTypes are erroring out on inserting integers 

### ISSUE THREAD

**Issue by Mahanchello** [milvus-io/milvus#22448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.3
- Deployment mode(standalone or cluster): cluster 
- MQ type(rocksmq, pulsar or kafka): kafka    
- SDK version(e.g. pymilvus v2.0.0rc2): latest
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

create collection with scalar fieldType int8, int16 or int32 and try to insert integer like 1, get error `caught error: 'int' object has no attribute 'name'`

### Expected Behavior

data gets inserted with no issues

### Steps To Reproduce

```markdown
run the following code:
`fields = [
    FieldSchema(name="id", dtype=DataType.INT64, is_primary=True, auto_id=False, description='id'),
    FieldSchema(name="vector", dtype=DataType.FLOAT_VECTOR, dim=512, description='vector'),
    FieldSchema(name="another_id", dtype=DataType.INT8, description='another id'),
]
schema = CollectionSchema(fields, "test")
collection = Collection(
    name='test',
    schema=schema,
    consistency_level="Bounded"
    )
data = [['fjk789sdfhjk'], [[random.random() for _ in range(512)]], [1]]
res = collection.insert(data)`
```

### Milvus Log

`caught error: 'int' object has no attribute 'name'`

**Comment by yanliang567** [comment]
@Mahanchello please try to use numpy for int8, int16 and in32 in pymilvus. One more thing is that the id field is int64, so you shall not input a varchar ['fjk789sdfhjk']. 
I updated the line of data below, and it ran successfully.
```
data = [[1], [[random.random() for _ in range(512)]], [numpy.int8(1)]]
res = collection.insert(data)
```
