### ISSUE TITLE
[Bug]: [Nightly]Search binary without flush often lost data

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#22451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:8dd1add
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search binary without flush often lost data.
```
[2023-02-27T21:23:32.379Z] [2023-02-27 20:34:26 - ERROR - ci_test]: search_results_check: limit(topK) searched (0) is not equal with expected (10) (func_check.py:255)
```

### Expected Behavior

search 10.

### Steps To Reproduce

```markdown
1. initialize a collection without data
2. insert data
3. load
4. search -> raise error
```

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/109/pipeline/156
2. log: [artifacts-milvus-distributed-kafka-nightly-109-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/109/artifact/artifacts-milvus-distributed-kafka-nightly-109-pymilvus-e2e-logs.tar.gz)
3. collection name: search_collection_oz0uVhIq
4. FAILED time: [2023-02-27T20:35:38.690Z] [gw4] [ 58%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_binary_without_flush[TANIMOTO-True]

**Comment by xiaofan-luan** [comment]
/assign @cydrain 
could you take a look on this?

**Comment by cydrain** [comment]
> /assign @cydrain could you take a look on this?

ok

**Comment by NicoYuan1986** [comment]
Latest: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/110/pipeline/124
log: 90 MB
[artifacts-milvus-standalone-nightly-110-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/110/artifact/artifacts-milvus-standalone-nightly-110-pymilvus-e2e-logs.tar.gz)

The 3 failed cases are all about TANIMOTO

**Comment by NicoYuan1986** [comment]
Latest: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/115/pipeline/156

milvus: 09593ad
pymilvus: 2.2.3.dev3
log: [artifacts-milvus-distributed-kafka-nightly-115-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/115/artifact/artifacts-milvus-distributed-kafka-nightly-115-pymilvus-e2e-logs.tar.gz)

**Comment by NicoYuan1986** [comment]
Same with #22403 
So close this one.
