### ISSUE TITLE
[Enhancement]:milvus pulls the s3 rate limit

### ISSUE THREAD

**Issue by lvmnn** [milvus-io/milvus#22450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

When loading large-scale index data, the file pulling rate reached 10Gb/s, which exceeded the s3 gateway capability.  
Can limit the speed of milvus pulling s3 files?

**Comment by xiaofan-luan** [comment]
This is kind of a tradeoff. You can always tune the parallism to load data but then loading will just gonna to be slow

**Comment by lvmnn** [comment]
> This is kind of a tradeoff. You can always tune the parallism to load data but then loading will just gonna to be slow

So how do you adjust the parallism parameter? @xiaofan-luan

**Comment by xiaofan-luan** [comment]
<img width="745" alt="image" src="https://user-images.githubusercontent.com/83447078/221737601-b054daaa-80c4-4411-998f-b50e0ded6e87.png">
segment_loader.go.
it's not tunable for now, totally computed by cpu size. if you can open a pull request to add some concurrency control over it

**Comment by xiaofan-luan** [comment]
keep it
