### ISSUE TITLE
[Bug]: Data race in grpc client

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#22478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12216890/221842096-6c1e0fb7-5df4-4d61-8208-c56bf564965e.png)

**Comment by yah01** [comment]
TestSegmentAllocator6 reproduces this

**Comment by congqixia** [comment]
patch merged. could you please verify? @yah01 
/unassign
/assign @yah01

**Comment by yah01** [comment]
![Uploading image.png…]()
run 10 times and not reproduced
