### ISSUE TITLE
[Bug]: DataNode panic when silent

### ISSUE THREAD

**Issue by MrPresent-Han** [milvus-io/milvus#22482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.3
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

A cluster with 4 datanodes was left silent for about 2days and it's found that the datanode had restart behavior

### Expected Behavior

datanode stay in stable state as expected

### Milvus Log

panic: Failed to create consumer by-dev-rootcoord-dml_26, error = All attempts results:
--
  |   | panic: Failed to create consumer by-dev-rootcoord-dml_39, error = All attempts results:
  |   | panic: Failed to create consumer by-dev-rootcoord-dml_62, error = All attempts results:
  |   | panic: runtime error: invalid memory address or nil pointer dereference
  |   | panic: Failed to create consumer by-dev-rootcoord-dml_57, error = All attempts results:
  |   | panic: Failed to create consumer by-dev-rootcoord-dml_30, error = All attempts results:
  |   | panic: DDNode forward delete msg failed, vChannel = by-dev-rootcoord-dml_10_439647239243038725v10, err = All attempts results:

**Comment by xiaofan-luan** [comment]
@MrPresent-Han 
Any progress on it?

**Comment by MrPresent-Han** [comment]
couldn't reproduce any more, please close it 
@yanliang567
