### ISSUE TITLE
[Bug]: [Upsert]Lack error check of upsert parameter 'partition_name'

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#22499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230301-fa5c3397
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0.dev44
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Lack error check of upsert parameter 'partition_name'.
When i use invalid partition_name, it didn't raise exception.
```
collection_w.upsert(data=data, partition_name=partition_name)
```
![image](https://user-images.githubusercontent.com/109071306/222089108-e1e12fba-4c8f-4d99-9989-f0c0cf014871.png)

Only this 4 will report error.

### Expected Behavior

The invalid partition_name can raise exception

**Comment by smellthemoon** [comment]
related pr has merged, plz help check it. @NicoYuan1986

**Comment by NicoYuan1986** [comment]
Fixed.
