### ISSUE TITLE
[Bug]: [Upsert]Num_entities is wrong when upsert data is same with inserted data

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#22496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230301-fa5c3397
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0.dev44
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Num_entities is wrong when upsert data is same with inserted data.
![image](https://user-images.githubusercontent.com/109071306/222071920-e20dd13a-1b71-4253-8755-31869e6179b9.png)

### Expected Behavior

num_entities is 3000. Now it's 4000, seems delete failure.

### Steps To Reproduce

```markdown
1. create a collection
2. insert 3000 data
3. take the first 1000 of inserted data
4. upsert the 1000 data


dim = 128
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
schema = CollectionSchema(fields=[int64_field, float_vector])
collection = Collection("test_upsert", schema=schema)

nb = 3000
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
collection.insert([[i for i in range(nb)], vectors])
collection.flush()
print(collection.num_entities)


collection.upsert([[i for i in range(1000)], vectors[:1000]])
collection.flush()
print(collection.num_entities)
```

**Comment by NicoYuan1986** [comment]
Strange. A few minutes later, num_entities became 2000.
![image](https://user-images.githubusercontent.com/109071306/222078719-6e6897d3-da39-4a98-97be-ee2614547759.png)

**Comment by smellthemoon** [comment]
Thank you for @NicoYuan1986 's help. Upsert answer is right, but num_entities is wrong.
In-depth investigation.
![11](https://user-images.githubusercontent.com/64083300/222141147-38aec4b9-9097-4e46-89ab-38e15b59ac2d.jpeg)

**Comment by smellthemoon** [comment]
When it didn't load, the num_entities returns the number of inserts, so 1000 is added after upsert, and after a while, compact  apply delete and then the num_entities becomes 2000.

**Comment by smellthemoon** [comment]
![1](https://user-images.githubusercontent.com/64083300/222394057-33c9c444-efd6-463c-a0bf-02440b48483b.jpeg)
After loaded and waited a while, the result is correct.
