### ISSUE TITLE
[Enhancement]: Unify error usage by wrapping error and make `errors.Is` available

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#22519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Unify error usage by wrapping error and make `errors.Is` available

### Why is this needed?

Some former error usage say `ErrorList` may conceal leaf error type so user cannot determine the root cause

**Comment by yah01** [comment]
- [ ] RootCoord
- [ ] DataCoord
- [ ] QueryCoord
- [ ] DataNode
- [ ] QueryNode
- [ ] Proxy

**Comment by congqixia** [comment]
/reopen
still wip

**Comment by jiaoew1991** [comment]
keep it

**Comment by jiaoew1991** [comment]
keep it

**Comment by jiaoew1991** [comment]
keep it
