### ISSUE TITLE
[Bug]:  Pods fail with  "write failed: open /milvus/configs/milvus.yaml: permission denied"

### ISSUE THREAD

**Issue by dugar-tarun** [milvus-io/milvus#22516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.3
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I try to install the milvus helm chart on an Openshift cluster, the following pods go into a CrashLoopBackOff error:
DataCoordinator
DataNode
IndexCoordinator
IndexNode
MilvusProxy
QueryCoordinator
QueryNode
MilvusProxy

All the pods fail with the following message:
```write failed: open /milvus/configs/milvus.yaml: permission denied```

### Expected Behavior

Expected milvus pods to get deployed successfully.

### Steps To Reproduce

```markdown
Install and deploy the milvus helm chart in an openshift cluster with the default config.
```

**Comment by xiaofan-luan** [comment]
> /milvus/configs/milvus.yaml

seems to be permission denied, pls check
/milvus/configs/milvus.yaml

**Comment by yanliang567** [comment]
@locustbaby  any more suggestions?

/assign @locustbaby 
/unassign

**Comment by locustbaby** [comment]
hi @dugar-tarun, would you mind sharing your milvus pod's yaml, anyone is ok
May I know whether there are any secure policies that will affect the file's permission in a pod?

**Comment by dugar-tarun** [comment]
kind: Pod
apiVersion: v1
metadata:
  generateName: milvus-datacoord-6949d8bcf5-
  annotations:
    checksum/config: cb499d18152e36bcd2e3c9b70ed96627999fe2c38ea2486903c3105afb951409
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "192.168.82.229"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "192.168.82.229"
          ],
          "default": true,
          "dns": {}
      }]
    kubernetes.io/limit-ranger: >-
      LimitRanger plugin set: cpu, memory request for container datacoord; cpu,
      memory limit for container datacoord; cpu, memory request for init
      container config; cpu, memory limit for init container config
    openshift.io/scc: restricted
    pyroscope.io/application-name: milvus-datacoord
    pyroscope.io/port: '9091'
    pyroscope.io/scrape: 'true'
  resourceVersion: '3203710203'
  name: milvus-datacoord-6949d8bcf5-zgcbh
  uid: 72cc4439-1d02-438e-846e-0ed364a96124
  creationTimestamp: '2023-02-28T09:49:39Z'
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2023-02-28T09:49:39Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:checksum/config': {}
            'f:pyroscope.io/application-name': {}
            'f:pyroscope.io/port': {}
            'f:pyroscope.io/scrape': {}
          'f:generateName': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/name': {}
            'f:component': {}
            'f:pod-template-hash': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"f5906c0e-39bd-487b-8fa0-191037d36833"}': {}
        'f:spec':
          'f:volumes':
            .: {}
            'k:{"name":"milvus-config"}':
              .: {}
              'f:configMap':
                .: {}
                'f:defaultMode': {}
                'f:name': {}
              'f:name': {}
            'k:{"name":"tools"}':
              .: {}
              'f:emptyDir': {}
              'f:name': {}
          'f:containers':
            'k:{"name":"datacoord"}':
              'f:image': {}
              'f:volumeMounts':
                .: {}
                'k:{"mountPath":"/milvus/configs/default.yaml"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
                  'f:readOnly': {}
                  'f:subPath': {}
                'k:{"mountPath":"/milvus/configs/user.yaml"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
                  'f:readOnly': {}
                  'f:subPath': {}
                'k:{"mountPath":"/milvus/tools"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
              'f:terminationMessagePolicy': {}
              .: {}
              'f:resources': {}
              'f:args': {}
              'f:livenessProbe':
                .: {}
                'f:failureThreshold': {}
                'f:httpGet':
                  .: {}
                  'f:path': {}
                  'f:port': {}
                  'f:scheme': {}
                'f:initialDelaySeconds': {}
                'f:periodSeconds': {}
                'f:successThreshold': {}
                'f:timeoutSeconds': {}
              'f:readinessProbe':
                .: {}
                'f:failureThreshold': {}
                'f:httpGet':
                  .: {}
                  'f:path': {}
                  'f:port': {}
                  'f:scheme': {}
                'f:initialDelaySeconds': {}
                'f:periodSeconds': {}
                'f:successThreshold': {}
                'f:timeoutSeconds': {}
              'f:terminationMessagePath': {}
              'f:imagePullPolicy': {}
              'f:ports':
                .: {}
                'k:{"containerPort":9091,"protocol":"TCP"}':
                  .: {}
                  'f:containerPort': {}
                  'f:name': {}
                  'f:protocol': {}
                'k:{"containerPort":13333,"protocol":"TCP"}':
                  .: {}
                  'f:containerPort': {}
                  'f:name': {}
                  'f:protocol': {}
              'f:name': {}
          'f:dnsPolicy': {}
          'f:serviceAccount': {}
          'f:restartPolicy': {}
          'f:schedulerName': {}
          'f:terminationGracePeriodSeconds': {}
          'f:initContainers':
            .: {}
            'k:{"name":"config"}':
              'f:image': {}
              'f:volumeMounts':
                .: {}
                'k:{"mountPath":"/milvus/tools"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
              'f:terminationMessagePolicy': {}
              .: {}
              'f:resources': {}
              'f:command': {}
              'f:terminationMessagePath': {}
              'f:imagePullPolicy': {}
              'f:name': {}
          'f:serviceAccountName': {}
          'f:enableServiceLinks': {}
          'f:securityContext': {}
    - manager: multus
      operation: Update
      apiVersion: v1
      time: '2023-02-28T09:49:41Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:k8s.v1.cni.cncf.io/network-status': {}
            'f:k8s.v1.cni.cncf.io/networks-status': {}
      subresource: status
    - manager: Go-http-client
      operation: Update
      apiVersion: v1
      time: '2023-02-28T09:49:44Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions':
            'k:{"type":"ContainersReady"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Initialized"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Ready"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:containerStatuses': {}
          'f:hostIP': {}
          'f:initContainerStatuses': {}
          'f:phase': {}
          'f:podIP': {}
          'f:podIPs':
            .: {}
            'k:{"ip":"192.168.82.229"}':
              .: {}
              'f:ip': {}
          'f:startTime': {}
      subresource: status
  namespace: ocp050020
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: milvus-datacoord-6949d8bcf5
      uid: f5906c0e-39bd-487b-8fa0-191037d36833
      controller: true
      blockOwnerDeletion: true
  labels:
    app.kubernetes.io/instance: milvus
    app.kubernetes.io/name: milvus
    component: datacoord
    pod-template-hash: 6949d8bcf5
spec:
  restartPolicy: Always
  initContainers:
    - resources:
        limits:
          cpu: '1'
          memory: 1Gi
        requests:
          cpu: 120m
          memory: 512Mi
      terminationMessagePath: /dev/termination-log
      name: config
      command:
        - /cp
        - '/run-helm.sh,/merge'
        - '/milvus/tools/run-helm.sh,/milvus/tools/merge'
      securityContext:
        capabilities:
          drop:
            - KILL
            - MKNOD
            - SETGID
            - SETUID
        runAsUser: 1001420000
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: tools
          mountPath: /milvus/tools
        - name: kube-api-access-26wbd
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: ''
  serviceAccountName: azure-pipelines
  imagePullSecrets:
    - name: azure-pipelines-dockercfg-z4vxq
  priority: 0
  schedulerName: default-scheduler
  enableServiceLinks: true
  terminationGracePeriodSeconds: 30
  preemptionPolicy: PreemptLowerPriority
  nodeName: titan-k99w4-worker-1-tzl6k
  securityContext:
    seLinuxOptions:
      level: 's0:c38,c7'
    fsGroup: 1001420000
  containers:
    - resources:
        limits:
          cpu: '1'
          memory: 1Gi
        requests:
          cpu: 120m
          memory: 512Mi
      readinessProbe:
        httpGet:
          path: /healthz
          port: metrics
          scheme: HTTP
        initialDelaySeconds: 90
        timeoutSeconds: 5
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 5
      terminationMessagePath: /dev/termination-log
      name: datacoord
      livenessProbe:
        httpGet:
          path: /healthz
          port: metrics
          scheme: HTTP
        initialDelaySeconds: 90
        timeoutSeconds: 5
        periodSeconds: 30
        successThreshold: 1
        failureThreshold: 5
      securityContext:
        capabilities:
          drop:
            - KILL
            - MKNOD
            - SETGID
            - SETUID
        runAsUser: 1001420000
      ports:
        - name: datacoord
          containerPort: 13333
          protocol: TCP
        - name: metrics
          containerPort: 9091
          protocol: TCP
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: milvus-config
          readOnly: true
          mountPath: /milvus/configs/default.yaml
          subPath: default.yaml
        - name: milvus-config
          readOnly: true
          mountPath: /milvus/configs/user.yaml
          subPath: user.yaml
        - name: tools
          mountPath: /milvus/tools
        - name: kube-api-access-26wbd
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: ''
      args:
        - /milvus/tools/run-helm.sh
        - milvus
        - run
        - datacoord
  serviceAccount: azure-pipelines
  volumes:
    - name: milvus-config
      configMap:
        name: milvus
        defaultMode: 420
    - name: tools
      emptyDir: {}
    - name: kube-api-access-26wbd
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
          - configMap:
              name: openshift-service-ca.crt
              items:
                - key: service-ca.crt
                  path: service-ca.crt
        defaultMode: 420
  dnsPolicy: ClusterFirst
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/memory-pressure
      operator: Exists
      effect: NoSchedule
status:
  containerStatuses:
    - restartCount: 569
      started: false
      ready: false
      name: datacoord
      state:
        waiting:
          reason: CrashLoopBackOff
          message: >-
            back-off 5m0s restarting failed container=datacoord
            pod=milvus-datacoord-6949d8bcf5-zgcbh_ocp050020(72cc4439-1d02-438e-846e-0ed364a96124)
      imageID: >-
        
      image: ''
      lastState:
        terminated:
          exitCode: 1
          reason: Error
          startedAt: '2023-03-02T09:58:32Z'
          finishedAt: '2023-03-02T09:58:32Z'
          containerID: >-
            cri-o://bab592c10f4f6a9394f32adb994131e3cd5931c6219f918af6a73fc1ba578868
      containerID: 'cri-o://bab592c10f4f6a9394f32adb994131e3cd5931c6219f918af6a73fc1ba578868'
  qosClass: Burstable
  podIPs:
    - ip: 192.168.82.229
  podIP: 192.168.82.229
  hostIP: 10.0.1.177
  startTime: '2023-02-28T09:49:40Z'
  initContainerStatuses:
    - name: config
      state:
        terminated:
          exitCode: 0
          reason: Completed
          startedAt: '2023-02-28T09:49:42Z'
          finishedAt: '2023-02-28T09:49:42Z'
          containerID: >-
            cri-o://b065a4ab6e74a6d3f6a21530f597a3616e13ab18ec0c4a2c8c67241738961393
      lastState: {}
      ready: true
      restartCount: 0
      image: ''
      imageID: >-
        
      containerID: 'cri-o://b065a4ab6e74a6d3f6a21530f597a3616e13ab18ec0c4a2c8c67241738961393'
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-02-28T09:49:42Z'
    - type: Ready
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2023-02-28T09:49:40Z'
      reason: ContainersNotReady
      message: 'containers with unready status: [datacoord]'
    - type: ContainersReady
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2023-02-28T09:49:40Z'
      reason: ContainersNotReady
      message: 'containers with unready status: [datacoord]'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-02-28T09:49:39Z'
  phase: Running



Hope this above yaml helps. I might have some policies enabled but I have kind of a limited access. Is there something you suspect that's causing this issue? If so, I can raise requests to take a closer look at said policies.

**Comment by locustbaby** [comment]
I see the `seLinuxOptions:  level: 's0:c38,c7'` in your yaml, do you know any details of it? 
In our pod, there are two containers here, an initcontainer will change(write) the file `milvus.yaml` first which is inside of the container originally, but the `write` failed when init, I guess there are some secure policies related

and as tips, seems there is some messages maybe you can mask in your yaml

**Comment by locustbaby** [comment]
ah, the config `fsGroup: 1001420000` and `runAsUser: 1001420000 `

**Comment by dugar-tarun** [comment]
So it cannot be run as a non-root user? Because I am definitely not allowed to run any container as root here.

**Comment by LoveEachDay** [comment]
@dugar-tarun For now you need to run milvus container with root. 
The `/milvus/configs/milvus.yaml` has the following permissions:
```
-rw-r--r-- 1 root root 7.7K Mar  2 10:06 milvus.yaml
```
We will merge config into `milvus.yaml` which requires write permission. So if you run as a non-root user, it will keep crashing.

**Comment by dugar-tarun** [comment]
Hello,
I can see a linked feature request to this issue. Can you please give me an estimate on when you plan to complete and release it?
We are waiting on this to deploy Milvus on OpenShift. Really appreciate the support.

**Comment by locustbaby** [comment]
Oh, sorry for the late reply, very thanks for your focus
This is a big break so we have to discuss and test more, we will be faster

**Comment by ZubeenK** [comment]
Hi, can I get to know the estimated time to fix this issue? I am also facing the same issue.

**Comment by dugar-tarun** [comment]
The issue has been closed but just wanted to ask if this feature has been released?
