### ISSUE TITLE
[Bug]:  use docker-compose  start Milvus  failed

### ISSUE THREAD

**Issue by WishHe** [milvus-io/milvus#22553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.3
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others: docker-compose
```

### Current Behavior

use docker-compose  Start Milvus 

### Milvus Log

[ERROR] [querynode/service.go:134] ["QueryNode init error: "] [error="All attempts results:\nattempt #1:Access Denied.\nattempt #2:Access Denied.\nattempt #3:Access Denied.\nattempt #4:Access Denied.\nattempt #5:Access Denied.\nattempt #6:Access Denied.\nattempt #7:Access Denied.\nattempt #8:Access Denied.\nattempt #9:Access Denied.\nattempt #10:Access Denied.\nattempt #11:Access Denied.\n"] [stack="github.com/milvus-io/milvus/internal/distributed/querynode.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:134\ngithub.com/milvus-io/milvus/internal/distributed/querynode.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:213\ngithub.com/milvus-io/milvus/cmd/components.(*QueryNode).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/query_node.go:54\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:104"]

**Comment by yanliang567** [comment]
sounds like a permission issue. could you please check that?
Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @WishHe 
/unassign
