### ISSUE TITLE
[Bug]: After release one collection, Milvus cluster is crashed

### ISSUE THREAD

**Issue by QAQwaitme** [milvus-io/milvus#22579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Milvus cluster on Kubernetes. About 30 million pieces  of data per day, One of the collections  cant  insert ,after release the collection, Milvus cluster is crashed

### Milvus Log

--  This is the QueryCrood logs with error :
[ERROR] [grpcclient/client.go:278] ["ClientBase Call grpc first call get error"] [role=querynode] [error="err: rpc error: code = DeadlineExceeded desc = context deadline exceeded\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:277 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call\n/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:371 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).GetDataDistribution\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:176 github.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).GetDataDistribution.func1\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:241 github.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).send\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:171 github.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).GetDataDistribution\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/dist/dist_handler.go:75 github.com/milvus-io/milvus/internal/querycoordv2/dist.(*distHandler).start\n/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit\n"] [stack="github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:278\ngithub.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).GetDataDistribution\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:371\ngithub.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).GetDataDistribution.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:176\ngithub.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).send\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:241\ngithub.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).GetDataDistribution\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:171\ngithub.com/milvus-io/milvus/internal/querycoordv2/dist.(*distHandler).start\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/dist/dist_handler.go:75"]
 -- This is the RootCrood logs of error 
 time="2023-03-06T02:21:34Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededException: Cannot create producer on topic with backlog quota exceeded" producerID=2 producer_name=my-release-pulsar-0-1 topic="persistent://public/default/by-dev-rootcoord-dml_1"
 -- This is the IndexCrood logs of error , the name of my index is :index 
 [2023/03/06 02:16:30.847 +00:00] [ERROR] [indexcoord/index_coord.go:506] ["IndexCoord get index state fail"] [collectionID=439783822987886751] [indexName=_default_idx] ["fail reason"="there is no index on collection: 439783822987886751 with the index name: _default_idx"] [stack="github.com/milvus-io/milvus/internal/indexcoord.(*IndexCoord).GetIndexState\n\t/go/src/github.com/milvus-io/milvus/internal/indexcoord/index_coord.go:506\ngithub.com/milvus-io/milvus/internal/distributed/indexcoord.(*Server).GetIndexState\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/indexcoord/service.go:256\ngithub.com/milvus-io/milvus/internal/proto/indexpb._IndexCoord_GetIndexState_Handler.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proto/indexpb/index_coord.pb.go:2448\ngithub.com/milvus-io/milvus/internal/util/logutil.UnaryTraceLoggerInterceptor\n\t/go/src/github.com/milvus-io/milvus/internal/util/logutil/grpc_interceptor.go:22\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34\ngithub.com/milvus-io/milvus/internal/proto/indexpb._IndexCoord_GetIndexState_Handler\n\t/go/src/github.com/milvus-io/milvus/internal/proto/indexpb/index_coord.pb.go:2450\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1283\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1620\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:922"]
-- This is Proxy logs of error 
time="2023-03-06T02:32:15Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededException: Cannot create producer on topic with backlog quota exceeded" producerID=2 producer_name=my-release-pulsar-0-285 topic="persistent://public/default/by-dev-rootcoord-dml_1"

**Comment by QAQwaitme** [comment]
DataNode also reboot for times

**Comment by yanliang567** [comment]
@QAQwaitme It seems that the pulsar service is not working well. Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @QAQwaitme 
/unassign

**Comment by QAQwaitme** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```gfm
> - Milvus version: 2.2.0
> - Deployment mode(standalone or cluster): cluster
> - MQ type(rocksmq, pulsar or kafka):    pulsar
> - SDK version(e.g. pymilvus v2.0.0rc2):
> - OS(Ubuntu or CentOS): CentOS
> - CPU/Memory: 
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> Milvus cluster on Kubernetes. About 30 million pieces of data per day, One of the collections cant insert ,after release the collection, Milvus cluster is crashed
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> -- This is the QueryCrood logs with error : [ERROR] [grpcclient/client.go:278] ["ClientBase Call grpc first call get error"] [role=querynode] [error="err: rpc error: code = DeadlineExceeded desc = context deadline exceeded\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:277 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call\n/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:371 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).GetDataDistribution\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:176 github.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).GetDataDistribution.func1\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:241 github.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).send\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:171 github.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).GetDataDistribution\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/dist/dist_handler.go:75 github.com/milvus-io/milvus/internal/querycoordv2/dist.(*distHandler).start\n/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit\n"] [stack="github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:278\ngithub.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).GetDataDistribution\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:371\ngithub.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).GetDataDistribution.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:176\ngithub.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).send\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:241\ngithub.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).GetDataDistribution\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:171\ngithub.com/milvus-io/milvus/internal/querycoordv2/dist.(*distHandler).start\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/dist/dist_handler.go:75"] -- This is the RootCrood logs of error time="2023-03-06T02:21:34Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededException: Cannot create producer on topic with backlog quota exceeded" producerID=2 producer_name=my-release-pulsar-0-1 topic="persistent://public/default/by-dev-rootcoord-dml_1" -- This is the IndexCrood logs of error , the name of my index is :index [2023/03/06 02:16:30.847 +00:00] [ERROR] [indexcoord/index_coord.go:506] ["IndexCoord get index state fail"] [collectionID=439783822987886751] [indexName=_default_idx] ["fail reason"="there is no index on collection: 439783822987886751 with the index name: _default_idx"] [stack="github.com/milvus-io/milvus/internal/indexcoord.(*IndexCoord).GetIndexState\n\t/go/src/github.com/milvus-io/milvus/internal/indexcoord/index_coord.go:506\ngithub.com/milvus-io/milvus/internal/distributed/indexcoord.(*Server).GetIndexState\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/indexcoord/service.go:256\ngithub.com/milvus-io/milvus/internal/proto/indexpb._IndexCoord_GetIndexState_Handler.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proto/indexpb/index_coord.pb.go:2448\ngithub.com/milvus-io/milvus/internal/util/logutil.UnaryTraceLoggerInterceptor\n\t/go/src/github.com/milvus-io/milvus/internal/util/logutil/grpc_interceptor.go:22\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34\ngithub.com/milvus-io/milvus/internal/proto/indexpb._IndexCoord_GetIndexState_Handler\n\t/go/src/github.com/milvus-io/milvus/internal/proto/indexpb/index_coord.pb.go:2450\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1283\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1620\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:922"] -- This is Proxy logs of error time="2023-03-06T02:32:15Z" level=error msg="[Failed to create producer]" error="server error: ProducerBlockedQuotaExceededException: Cannot create producer on topic with backlog quota exceeded" producerID=2 producer_name=my-release-pulsar-0-285 topic="persistent://public/default/by-dev-rootcoord-dml_1"
> 
> ### Anything else?
> _No response_

/ /
