### ISSUE TITLE
[Bug]: big performance degradation in v2.2.3 (compared to v2.2.2)

### ISSUE THREAD

**Issue by alexjst** [milvus-io/milvus#22570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.3
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.2.2
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: bigger than what the sizing tool suggests
- GPU: None
- Others:
```

### Current Behavior

Using a randomly generated dataset of 1M vectors of 128 dimensions, we compared the performances of v2.2.2 and v2.2.3. 
With HNSW index type, we noticed a significant performance degradation in the lastest version v2.2.3 in terms of search latencies as observed in the grafana dashboard.

With topK=500, P99 in v2.2.2 ~= 12ms; P99 in v2.2.3 ~= 60ms, a 5X difference.
With topK=1200, P99 in v2.2.2 ~= 16ms; P99 in v2.2.3 ~= 200ms, a 10x difference.

We are not comfortable upgrading to v2.2.3 because of this. Please help verify and check.

### Expected Behavior

The latency performance in the newer version v2.2.3 should not be so much worse than v2.2.2. 

### Steps To Reproduce

```markdown
1. The following python code snippet shows the collection creation: (dim=128, data_size=1000000, nb=20000)

    id = FieldSchema(name="id", dtype=DataType.INT64, description="auto primary id")
    age_field = FieldSchema(name="age", dtype=DataType.INT64, description="age")
    embedding_field = FieldSchema(name="embedding", dtype=DataType.FLOAT_VECTOR, dim=dim)
    schema = CollectionSchema(fields=[id, age_field, embedding_field],
                              auto_id=auto_id, primary_field=id.name,
                              description="my collection")
    collection = Collection(name=collection_name, schema=schema, shards_num=shards)
    loginfo(f"created {collection_name} successfully")

    for i in range(insert_times):
        # prepare data
        ages = [random.randint(1, 100) for _ in range(nb)]
        embeddings = [[random.random() for _ in range(dim)] for _ in range(nb)]
        data = [ages, embeddings]
        t0 = time.time()
        collection.insert(data)
        tt = round(time.time() - t0, 3)
        loginfo(f"Insert {i} costs {tt} seconds")

    loginfo(f"Flushing...")
    collection.flush()
    loginfo(f"Collection entities: {collection.num_entities}")

    loginfo(f"Building index...")
    t0 = time.time()
    collection.create_index(field_name=embedding_field.name, index_params=index_params)
    tt = round(time.time() - t0, 3)
    loginfo(f"Build index costs {tt} seconds")

    loginfo(f"Loading index...")
    t0 = time.time()
    collection.load(replica_number=replicas)
    tt = round(time.time() - t0, 3)
    loginfo(f"Loading index costs {tt} seconds")
    loginfo("Collection preparation completed")

2. Run a load test (with Locust for example, set QPS = 500 and 1200 separately). The search code looks like the following:

    @task
    def search(self):
        # Generate a random embedding to use as the query
        query = [random.uniform(-1, 1) for i in range(int(self.dim))]
        logInfo(f"Sending query {query}")
        # Send the search request to Milvus
        try:
            self.collection.search(
                data=[query],
                anns_field=self.field_name,
                param=self.search_params,
                limit=self.topk,
                expr=None,
                consistency_level="Eventually"
            )
        except Exception as e:
            logError(f"Error searching milvus: {str(e)}")


3. Run load test for at least a few minutes.
4. From grafana dashboard, the P99 and P95 latencies have huge differences. In our datacenter, the newer version v2.2.3 is 5x or 10x slower.
```

### Anything else?

We have a custom cluster setup that's more close to bare metal setup. But it shouldn't really matter.
Cluster resource is sufficient because it is capable to handle many times the data size.

**Comment by alexjst** [comment]
FYI, some parameters in the code:

auto_id = True
index_params = {"index_type": index_type, "params": {"M": 8, "efConstruction": 200}, "metric_type": "L2"}

**Comment by xiaofan-luan** [comment]
Hi @alexjst, 
what about the avg? We you talk about 5X slower, is it only for P99 or avg also?

**Comment by xiaofan-luan** [comment]
We've done some performance optimization on 2.2.3 so I would expect to gain some performance. Could you just share some detailed info with us such as your dataset(if an opensourced one), avg latency and throughput?

**Comment by xiaofan-luan** [comment]
We are trying to reproduce in house but meanwhile logs would really helpful

**Comment by yanliang567** [comment]
@alexjst do you happen to have the screenshot of milvus metric in granfana, if yes, we'd like you take a look at screenshots of the proxy, querynode and runtime.  also please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation

/aksksign @alexjst

**Comment by alexjst** [comment]
> Hi @alexjst, what about the avg? We you talk about 5X slower, is it only for P99 or avg also?

The comparison result is pretty much the same when we look at P99, P95, P90 or P50.

**Comment by alexjst** [comment]
> We've done some performance optimization on 2.2.3 so I would expect to gain some performance. Could you just share some detailed info with us such as your dataset(if an opensourced one), avg latency and throughput?

I have copied and pasted the related code in the issue description. The dataset was created by the script to generate 1M random vectors. It should be easy to reproduce by modifying the script to make it work in your environment. Please take a look at the code snippets. It's not fancy, just a generic random vector collection for latency testing.

**Comment by alexjst** [comment]
> @alexjst do you happen to have the screenshot of milvus metric in granfana, if yes, we'd like you take a look at screenshots of the proxy, querynode and runtime. also please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation
> 
> /aksksign @alexjst

Sure, I am attaching a dashboard screenshot. V2.2.3 is on the left (in green), V2.2.2 is on the right (in yellow). 
In this test, QPS=500, but topK was changed to 500 (around 08:15~08:17 for v2.2.3 and around 09:01~09:16 for v2.2.2) and then to topK=1200 (around 8:20~8:35 for v2.2.3 and 09:18~09:27 for v2.2.2).  

<img width="1711" alt="Screen Shot 2023-03-03 at 7 09 37 PM" src="https://user-images.githubusercontent.com/7521539/222872960-e1001f76-ec1b-4aa7-9e7d-874ffbc154b5.png">

**Comment by xiaofan-luan** [comment]
Sure, we will investigate on it and try to fix on 2.2.4

**Comment by alexjst** [comment]
> @alexjst do you happen to have the screenshot of milvus metric in granfana, if yes, we'd like you take a look at screenshots of the proxy, querynode and runtime. also please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation
> 
> /aksksign @alexjst



> 

Let me upload the full-page screenshot of the dashboard. You would need to download it and enlarge it to see the panels in detail. It's hard to get the logs because of log rotation. Also, we are using Hashcorp Nomad (https://www.hashicorp.com/products/nomad) for deployment so the log export script wouldn't work out of the box. 
![screencapture-grafana-rbx-d-9AWsl4c4z-rss-service-2023-03-03-19_27_50](https://user-images.githubusercontent.com/7521539/222873762-12cbbbcc-0d79-4913-a70f-fac2c082bced.png)

**Comment by alexjst** [comment]
> Sure, we will investigate on it and try to fix on 2.2.4

Thanks!

**Comment by liliu-z** [comment]
Hi @alexjst, Thanks for these clarification. Can I ask the setup of this cluster? For example, how many proxynode/querynode, what the resource allocation of them.

And can I ask how many shard do you have? It didn't show up in the script. Thanks!

**Comment by alexjst** [comment]
> Hi @alexjst, Thanks for these clarification. Can I ask the setup of this cluster? For example, how many proxynode/querynode, what the resource allocation of them.
> 
> And can I ask how many shard do you have? It didn't show up in the script. Thanks!

Sure, here's the setup: etcd: 2G x 5; kafka: 16G x 5; rootcoord: 2G * 1; datacoord: 2G * 1; indexcoord: 2G * 1; querycoord: 2G * 1; datacoord: 4G * 3; indexnode: 32G * 3; querynode: 32G * 10; proxynode: 4G * 3; shards=3; replicas=1;

**Comment by alexjst** [comment]
> @alexjst Just checked the monitor you sent. node-19/17 are serving the requests in 2.2.3 version. The latency for node-19 is pretty normal but that for node-17 is the bottleneck. Highly suspect that we have a growing segment in node-17.
> 
> If we are using the latest version of Monitor we can confirm this from the monitor, but looks like we are still using the old version. There are two methods to fix this:
> 
> 1. Temporarily change the monitor chart of metric we need:
>    a. Find the `Segment Loaded Num` chart, click the title and choose `edit`.
>    b. In the `Metrics browser`, change the last part of the formula from `by (pod, node_id)` to `by (pod, node_id, segment_state)`
>    c. Open the `options` and change the content in the `Legend` from `{{pod}}-{{node_id}}` to `{{pod}}-{{node_id}}-{{segment_state}}`.
> 2. Update the dashboard to the latest version:
>    a. Click the gear button at the right-top corner to modify the grafana settings.
>    b. Check out to the `JSON Model` tab, and paste https://github.com/milvus-io/milvus/blob/master/deployments/monitor/grafana/milvus-dashboard.json to it.
>    c. Save changes and take a look at the `Segment Loaded Num` again.
> 
> Thanks

I used the temporary method and this is what I got: 
<img width="601" alt="image" src="https://user-images.githubusercontent.com/7521539/223319785-ebe9c4b8-f4f2-41b3-ad7e-1017acd07e50.png">
If I select node 17 only:
<img width="602" alt="image" src="https://user-images.githubusercontent.com/7521539/223319912-a8dd973e-2aad-4b54-ab2d-790edc3964cb.png">
Sorry I am not able to get "pod" displayed due to our setup.

**Comment by xiaofan-luan** [comment]
> > @alexjst Just checked the monitor you sent. node-19/17 are serving the requests in 2.2.3 version. The latency for node-19 is pretty normal but that for node-17 is the bottleneck. Highly suspect that we have a growing segment in node-17.
> > If we are using the latest version of Monitor we can confirm this from the monitor, but looks like we are still using the old version. There are two methods to fix this:
> > 
> > 1. Temporarily change the monitor chart of metric we need:
> >    a. Find the `Segment Loaded Num` chart, click the title and choose `edit`.
> >    b. In the `Metrics browser`, change the last part of the formula from `by (pod, node_id)` to `by (pod, node_id, segment_state)`
> >    c. Open the `options` and change the content in the `Legend` from `{{pod}}-{{node_id}}` to `{{pod}}-{{node_id}}-{{segment_state}}`.
> > 2. Update the dashboard to the latest version:
> >    a. Click the gear button at the right-top corner to modify the grafana settings.
> >    b. Check out to the `JSON Model` tab, and paste https://github.com/milvus-io/milvus/blob/master/deployments/monitor/grafana/milvus-dashboard.json to it.
> >    c. Save changes and take a look at the `Segment Loaded Num` again.
> > 
> > Thanks
> 
> I used the temporary method and this is what I got: <img alt="image" width="601" src="https://user-images.githubusercontent.com/7521539/223319785-ebe9c4b8-f4f2-41b3-ad7e-1017acd07e50.png"> If I select node 17 only: <img alt="image" width="602" src="https://user-images.githubusercontent.com/7521539/223319912-a8dd973e-2aad-4b54-ab2d-790edc3964cb.png"> Sorry I am not able to get "pod" displayed due to our setup.

Is there any way we can reproduce the issue?

> > @alexjst Just checked the monitor you sent. node-19/17 are serving the requests in 2.2.3 version. The latency for node-19 is pretty normal but that for node-17 is the bottleneck. Highly suspect that we have a growing segment in node-17.
> > If we are using the latest version of Monitor we can confirm this from the monitor, but looks like we are still using the old version. There are two methods to fix this:
> > 
> > 1. Temporarily change the monitor chart of metric we need:
> >    a. Find the `Segment Loaded Num` chart, click the title and choose `edit`.
> >    b. In the `Metrics browser`, change the last part of the formula from `by (pod, node_id)` to `by (pod, node_id, segment_state)`
> >    c. Open the `options` and change the content in the `Legend` from `{{pod}}-{{node_id}}` to `{{pod}}-{{node_id}}-{{segment_state}}`.
> > 2. Update the dashboard to the latest version:
> >    a. Click the gear button at the right-top corner to modify the grafana settings.
> >    b. Check out to the `JSON Model` tab, and paste https://github.com/milvus-io/milvus/blob/master/deployments/monitor/grafana/milvus-dashboard.json to it.
> >    c. Save changes and take a look at the `Segment Loaded Num` again.
> > 
> > Thanks
> 
> I used the temporary method and this is what I got: <img alt="image" width="601" src="https://user-images.githubusercontent.com/7521539/223319785-ebe9c4b8-f4f2-41b3-ad7e-1017acd07e50.png"> If I select node 17 only: <img alt="image" width="602" src="https://user-images.githubusercontent.com/7521539/223319912-a8dd973e-2aad-4b54-ab2d-790edc3964cb.png"> Sorry I am not able to get "pod" displayed due to our setup.

Seems it is a little bit hard to reproduce, do you want to setup a offline sync so we get more detail about it?

**Comment by xiaofan-luan** [comment]
feel free to send me email xiaofan.luan@zilliz.com
