### ISSUE TITLE
[Bug]: query interface does not support expr to be null

### ISSUE THREAD

**Issue by lentitude2tk** [milvus-io/milvus#22626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): java-sdk
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When using the java-sdk to call the query interface, the expr parameter must be passed in. Otherwise, the interface will prompt that expr cannot be null or empty. This logic is different from the conventional database usage method. It is hoped that the expr parameter can be directly used for scenarios where the expr parameter is empty.

### Expected Behavior

If the query is performed when the input expr parameter is empty, you can query the results according to other query conditions, for example, query the top 100 data and return 100 of them.

### Steps To Reproduce

```markdown
1. It can be reproduced when the expr parameter passed in is empty
```

**Comment by xiaofan-luan** [comment]
/assign @longjiquan 
pls take a look into it

**Comment by longjiquan** [comment]
Hello, @lentitude2tk , thanks for the nice feedback. I guess I got what you want, besides your needs, I want to clear some key points with you:
- What's the expected behavior when the expression is empty?
- Under this case, how Milvus should filter the result?

**Comment by lentitude2tk** [comment]
@longjiquan  Sorry for not checking the email and replying promptly.

Typically, when using other database products, the usual practice is to perform an initial query without a WHERE condition and then further filter the results based on different fields or values.

- If the expression is empty, you can follow the default rules of the milvus engine and return the specified number of data entries based on the limit/offset parameters. If there are no default rules, returning the specified data randomly is also acceptable.
- If there is no expression, there is no need to apply any filters.

**Comment by yanliang567** [comment]
keep it active

**Comment by xiaofan-luan** [comment]
@longjiquan 
query with empty expression should return the first top n result in collection?

**Comment by lentitude2tk** [comment]
> @longjiquan query with empty expression should return the first top n result in collection?

In addition, the data returned in the empty expression scenario must be sorted based on certain specifications, otherwise the offset and limit in this scenario are meaningless
