### ISSUE TITLE
[Bug]: Varchar limits aren't applied to the right field when using aotoID

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#22623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master(cecd59d9)
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0.dev45
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Varchar limits aren't applied to the right field when using aotoID.
1. create a Schema that looks as such: 
![image](https://user-images.githubusercontent.com/109071306/223613812-05fce259-3a4a-4344-8da2-fcf9a5406f19.png)
2. One field, source is set to max_length=2, but upon inserting this data:
![image](https://user-images.githubusercontent.com/109071306/223613853-ea9c2490-20b5-4995-9370-32f1e2974e0c.png)
Here it should report exception when insert. But insert successfully.
![image](https://user-images.githubusercontent.com/109071306/223614251-22d05ca8-0285-4b14-a9ca-4b0c39e63949.png)
3. The max_length is applied to the source_id field. When swapping the order of the fields it seems like the max_length is applied to the one after the one that is specified to be shorter. When inserting the data that is correctly formatted:
![image](https://user-images.githubusercontent.com/109071306/223614481-fcf7c141-2583-44a0-b926-7f7499263af5.png)
It report an error.

### Expected Behavior

Apply varchar limits correctly and find the reason why it performs like this.

### Steps To Reproduce

```python
from pymilvus import CollectionSchema, FieldSchema, Collection, connections, DataType, Partition, utility
import random

DIM = 128
fields = [
    FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, auto_id=True),
    FieldSchema(name="embedding", dtype=DataType.FLOAT_VECTOR, dim=DIM),
    FieldSchema(name="source", dtype=DataType.VARCHAR, max_length=2),
    FieldSchema(name="source_id", dtype=DataType.VARCHAR, max_length=65500)
]
schema = CollectionSchema(fields=fields)
connections.connect()
# utility.drop_collection("test_varchar")
collection = Collection("test_varchar", schema=schema)

nb = 2
vectors = [[random.random() for _ in range(DIM)] for _ in range(nb)]
data = [
    vectors,
    ["source_1_________", "source_2___________"],
    ['1', '2']
]
collection.insert(data)

data = [
    vectors,
    ['1', '2'],
    ["source_1_________", "source_2___________"]
]
collection.insert(data)
```

### Milvus Log

[milvus.log](https://github.com/milvus-io/milvus/files/10917024/milvus.log)

**Comment by xiaofan-luan** [comment]
the first insert is wrong and the second insert should work, because the order is important

**Comment by xiaofan-luan** [comment]
Milvus only rely the order to decide the field mapping

**Comment by xiaofan-luan** [comment]
> the first insert is wrong and the second insert should work, because the order is important

Oh i guess I know what is happening.

**Comment by xiaofan-luan** [comment]
/assign @czs007 
could you help to check if this is a sdk issue or serverside issue?

**Comment by longjiquan** [comment]
Will be fixed by https://github.com/milvus-io/pymilvus/pull/1325

**Comment by longjiquan** [comment]
Related pr: #22628

**Comment by yanliang567** [comment]
@NicoYuan1986 please try to add a test in ci
