### ISSUE TITLE
[Enhancement]:  support oss for chunk manager

### ISSUE THREAD

**Issue by zhagnlu** [milvus-io/milvus#22663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

support read and write oss by chunk manager, security mode is IAM

**Comment by xiaofan-luan** [comment]
keep it

**Comment by elonzh** [comment]
keep it

**Comment by xiaofan-luan** [comment]
> keep it

OSS should be already supported in latest master or the next 2.2.9 release.
