### ISSUE TITLE
Server hang when using multi-clients to query different collections

### ISSUE THREAD

**Issue by zhupengfly** [milvus-io/milvus#2266]
- 我们在压测时发现，对于单个collection中的数据查询，并发量加大时，程序还能较好的运行。
- 当我们创建两个collection，并对它们进行并发查询时，发现milvus服务卡死了，查询无响应，用milvus-admin去连接也无法连接上。
- 但是我们用curl的方式去查询服务的status时，发现返回的是Success的。
- 我们使用的是milvus0.8.0的GPU版本

**Comment by scsven** [comment]
Could you please provide the log file in milvus/logs directory?

**Comment by yhmo** [comment]
We have noticed some users encounter same problem, it is an critical issue, we will fix it in 0.9.0.

**Comment by yhmo** [comment]
fixed by pr2277

**Comment by tinkerlin** [comment]
@del-zhenwu regression test

**Comment by del-zhenwu** [comment]
fixed

**Comment by del-zhenwu** [comment]
>     * 我们在压测时发现，对于单个collection中的数据查询，并发量加大时，程序还能较好的运行。
> 
>     * 当我们创建两个collection，并对它们进行并发查询时，发现milvus服务卡死了，查询无响应，用milvus-admin去连接也无法连接上。
> 
>     * 但是我们用curl的方式去查询服务的status时，发现返回的是Success的。
> 
>     * 我们使用的是milvus0.8.0的GPU版本

The issue has been fixed in version 0.9. you can try with the latest daily image, or try again in the next 0.9 release version
