### ISSUE TITLE
["IndexCoord get index state fail"] [collectionID=123123] [indexName=_default_idx] ["fail reason"="there is no index on collection

### ISSUE THREAD

**Issue by ABAPPLO** [milvus-io/milvus#22671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.2
- Deployment mode(standalone or cluster):  cluster
- MQ type(rocksmq, pulsar or kafka): pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus  2.2.2
- OS(Ubuntu or CentOS): CentOS （K8S）
- CPU/Memory:  CPU:128    Mem:128G
- GPU: None
- Others: -
```

### Current Behavior

We had a problem with the milvus cluster (but the disk was not damaged), but it was fixed later (k8s). Before reloading the data, we changed the index of the data and then loaded the data. However, in the case of sufficient resources, the data was only 50% loaded. The two collections in question have the usual insert and delete operations, neither of which has been loaded

### Expected Behavior

Normally it's all loaded, but now it's half loaded

### Steps To Reproduce

```markdown
Just load the data into memory
```

### Milvus Log

node: IndexCoord

**Comment by ABAPPLO** [comment]
IndexCoord
[2023/03/09 03:41:13.400 +00:00] [ERROR] [indexcoord/index_coord.go:507] ["IndexCoord get index state fail"] [collectionID=12122222222] [indexName=_default_idx] ["fail reason"="there is no index on collection: 12122222222 with the index name: _default_idx"] 
[stack="github.com/milvus-io/milvus/internal/indexcoord.(*IndexCoord).GetIndexState
	/go/src/github.com/milvus-io/milvus/internal/indexcoord/index_coord.go:507
	github.com/milvus-io/milvus/internal/distributed/indexcoord.(*Server).GetIndexState
	/go/src/github.com/milvus-io/milvus/internal/distributed/indexcoord/service.go:263
	github.com/milvus-io/milvus/internal/proto/indexpb._IndexCoord_GetIndexState_Handler.func1
	/go/src/github.com/milvus-io/milvus/internal/proto/indexpb/index_coord.pb.go:2448
	github.com/milvus-io/milvus/internal/util/logutil.UnaryTraceLoggerInterceptor
	/go/src/github.com/milvus-io/milvus/internal/util/logutil/grpc_interceptor.go:22
	github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25
	github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38
	github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25
	github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34
	github.com/milvus-io/milvus/internal/proto/indexpb._IndexCoord_GetIndexState_Handler
	/go/src/github.com/milvus-io/milvus/internal/proto/indexpb/index_coord.pb.go:2450
	google.golang.org/grpc.(*Server).processUnaryRPC
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1283
	google.golang.org/grpc.(*Server).handleStream
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1620
	google.golang.org/grpc.(*Server).serveStreams.func1.2
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:922"]

**Comment by xiaofan-luan** [comment]
Hi @ABAPPLO ,
This is a known issue for 2.2.2.
Pls upgrade to 2.2.3 and your problem should be solved
