### ISSUE TITLE
[Bug]: the datanode try to find the droped data

### ISSUE THREAD

**Issue by bingbb47** [milvus-io/milvus#22699]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.2 -> 2.2.3
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The datanode continues to output the following logs.
Although this error does not affect the normal operation of the cluster, it continues to try to obtain data from s3, resulting in increased gateway pressure.
We first found this problem on the 2.2.2 version , and in the release note of 2.2.3, I noticed that there was a bug fix of  "CheckPoint and GC Related issues fixed"
But I still found such logs after upgrading

### Expected Behavior

datanode stop to get the droped data

### Milvus Log

[datanode.txt](https://github.com/milvus-io/milvus/files/10943056/datanode.txt)

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```gfm
> - Milvus version: 2.2.2 -> 2.2.3
> - Deployment mode(standalone or cluster): cluster
> - MQ type(rocksmq, pulsar or kafka): pulsar
> - SDK version(e.g. pymilvus v2.0.0rc2):
> - OS(Ubuntu or CentOS): 
> - CPU/Memory: 
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> The datanode continues to output the following logs. Although this error does not affect the normal operation of the cluster, it continues to try to obtain data from s3, resulting in increased gateway pressure. We first found this problem on the 2.2.2 version , and in the release note of 2.2.3, I noticed that there was a bug fix of "CheckPoint and GC Related issues fixed" But I still found such logs after upgrading
> 
> ### Expected Behavior
> datanode stop to get the droped data
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> [datanode.txt](https://github.com/milvus-io/milvus/files/10943056/datanode.txt)
> 
> ### Anything else?
> _No response_

Hi @bingbb47 , once you hit the issue, upgrade won't help.
If you are still under testing, maybe you can simply upgrade.
If it's already under production, we can help you to recover or you can directly use birdwatcher to modify the meta.

**Comment by bingbb47** [comment]
> > ### Is there an existing issue for this?
> > 
> > * [x]   I have searched the existing issues
> > 
> > ### Environment
> > ```
> > - Milvus version: 2.2.2 -> 2.2.3
> > - Deployment mode(standalone or cluster): cluster
> > - MQ type(rocksmq, pulsar or kafka): pulsar
> > - SDK version(e.g. pymilvus v2.0.0rc2):
> > - OS(Ubuntu or CentOS): 
> > - CPU/Memory: 
> > - GPU: 
> > - Others:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Current Behavior
> > The datanode continues to output the following logs. Although this error does not affect the normal operation of the cluster, it continues to try to obtain data from s3, resulting in increased gateway pressure. We first found this problem on the 2.2.2 version , and in the release note of 2.2.3, I noticed that there was a bug fix of "CheckPoint and GC Related issues fixed" But I still found such logs after upgrading
> > ### Expected Behavior
> > datanode stop to get the droped data
> > ### Steps To Reproduce
> > _No response_
> > ### Milvus Log
> > [datanode.txt](https://github.com/milvus-io/milvus/files/10943056/datanode.txt)
> > ### Anything else?
> > _No response_
> 
> Hi @bingbb47 , once you hit the issue, upgrade won't help. If you are still under testing, maybe you can simply upgrade. If it's already under production, we can help you to recover or you can directly use birdwatcher to modify the meta.

thanks , for birdwatcher, witch comand can help to resolve it.

**Comment by xiaofan-luan** [comment]
From the log, the collection with issue is geek-blue-recall-v2.  is this a dropped collection? 
@congqixia could we have a command to cleanup dropped collection in birdwatcher

**Comment by congqixia** [comment]
Hi @bingbb47 could you please provide a backup using birdwatcher so that we could check which command shall be used or some new command shall be added?
https://github.com/milvus-io/birdwatcher#backup-etcd

**Comment by bingbb47** [comment]
> 
[bw_etcd_ALL.230312-151410.bak.gz](https://github.com/milvus-io/milvus/files/10950288/bw_etcd_ALL.230312-151410.bak.gz)

**Comment by bingbb47** [comment]
[2023/03/12 08:15:49.997 +00:00] [ERROR] [datanode/channel_meta.go:213] ["failed to init bloom filter"] ["segment ID"=438401893546975312] [error="All attempts results:\nattempt #1:NoSuchKey(key=files/stats_log/438401893544567314/438401893546975307/438401893546975312/100/438401893546975388)\n"] [stack="github.com/milvus-io/milvus/internal/datanode.(*ChannelMeta).addSegment\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/channel_meta.go:213\ngithub.com/milvus-io/milvus/internal/datanode.(*dataSyncService).initNodes.func2\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:253\ngithub.com/milvus-io/milvus/internal/util/concurrency.(*Pool).Submit.func1\n\t/go/src/github.com/milvus-io/milvus/internal/util/concurrency/pool.go:46\ngithub.com/panjf2000/ants/v2.(*goWorker).run.func1\n\t/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.8/worker.go:70"]

in this log, 
![BossHi-20230312162031](https://user-images.githubusercontent.com/111261344/224532900-25387985-8369-4546-ac81-5816e5f5da64.png)
but
![BossHi-20230312162113](https://user-images.githubusercontent.com/111261344/224532936-ad3b7199-8e23-4f33-9659-0ad1f2f4d513.png)

**Comment by congqixia** [comment]
Hi @bingbb47  in this case, 
`remove channel` command help.
Here is some suggested actions to take:
1. backup before take any modifiaction
2. stop datacoord and datanode
3. run `birdwatcher` `remove channel` command ( this is the dry run step, no action will be take)
4. check all the suspects list to verify any all channel are safe to remove
5. run `remove channel --run` to actually remove orphan channels
6. Start datacoord and datanodes and check everything is fine

**Comment by bingbb47** [comment]
> Hi @bingbb47 in this case, `remove channel` command might help. Here is some suggested actions to take:
> 
> 1. backup before take any modifiaction
> 2. stop datacoord and datanode
> 3. run `birdwatcher` `remove channel` command ( this is the dry run step, no action will be take)
> 4. check all the suspects list to verify any all channel are safe to remove
> 5. run `remove channel --run` to actually remove orphan channels
> 6. Start datacoord and datanodes and check everything is fine

thanks for help! by the way, will these actions affect the normal query of other collections?

**Comment by congqixia** [comment]
> thanks for help! by the way, will these actions affect the normal query of other collections?
@bingbb47 in some degree, yes. If datanode down time is too large, it may impact the delta timetick for query nodes.

**Comment by bingbb47** [comment]
> 



> > thanks for help! by the way, will these actions affect the normal query of other collections?
> > @bingbb47 in some degree, yes. If datanode down time is too large, it may impact the delta timetick for query nodes.

ok, i will do it as fast as i can ..

**Comment by bingbb47** [comment]
> Hi @bingbb47 in this case, `remove channel` command might help. Here is some suggested actions to take:
> 
> 1. backup before take any modifiaction
> 2. stop datacoord and datanode
> 3. run `birdwatcher` `remove channel` command ( this is the dry run step, no action will be take)
> 4. check all the suspects list to verify any all channel are safe to remove
> 5. run `remove channel --run` to actually remove orphan channels
> 6. Start datacoord and datanodes and check everything is fine

when i run remove channel --run, birdwatcher panic with

Start to delete orphan watch channel info...
audio delete geek-blue-recall-v2/meta/channelwatch/89/geek-blue-recall-v2-rootcoord-dml_9_438401893509923286v1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x12f6e45]

goroutine 1 [running]:
github.com/milvus-io/birdwatcher/states/etcd/audit.(*FileAuditKV).writeData(0xc00095c420, {0xc00062bba8, 0x6, 0x6})
        /usr/mabingzheng/birdwatcher/states/etcd/audit/audit_write.go:45 +0xa5
github.com/milvus-io/birdwatcher/states/etcd/audit.(*FileAuditKV).writeHeader(0x1538d20?, 0x1, 0x1)
        /usr/mabingzheng/birdwatcher/states/etcd/audit/audit_write.go:19 +0x8d
github.com/milvus-io/birdwatcher/states/etcd/audit.(*FileAuditKV).Delete(0xc00095c420, {0x1a43298, 0xc0010ec660}, {0xc000405c70, 0x61}, {0x0, 0x0, 0x0})
        /usr/mabingzheng/birdwatcher/states/etcd/audit/audit.go:59 +0x1ba
github.com/milvus-io/birdwatcher/states/etcd/remove.ChannelCommand.func1(0xc00015aa00?, {0x17c1c8d?, 0x1?, 0x1?})
        /usr/mabingzheng/birdwatcher/states/etcd/remove/channel.go:77 +0x629
github.com/spf13/cobra.(*Command).execute(0xc00015aa00, {0xc000ad1080, 0x1, 0x1})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0xc0007f5900)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/milvus-io/birdwatcher/states.(*cmdState).Process(0xc000586150, {0xc0000462a0?, 0xc000680c00?})
        /usr/mabingzheng/birdwatcher/states/states.go:63 +0x146
main.(*promptApp).promptExecute(0xc0003ee0a8, {0xc0000462a0?, 0x25a5500?})
        /usr/mabingzheng/birdwatcher/main.go:126 +0x3f0
github.com/c-bata/go-prompt.(*Prompt).Run(0xc00040c5a0)
        /root/go/pkg/mod/github.com/c-bata/go-prompt@v0.2.6/prompt.go:84 +0x755
main.runPrompt({0x1a4b220?, 0xc0003ee048})
        /usr/mabingzheng/birdwatcher/main.go:184 +0x338
main.main()
        /usr/mabingzheng/birdwatcher/main.go:35 +0x176

**Comment by bingbb47** [comment]
i have try the birdwatcher:v1.0.0 and the latest commit, have the same phenomenon

**Comment by bingbb47** [comment]
> Hi @bingbb47 in this case, `remove channel` command might help. Here is some suggested actions to take:
> 
> 1. backup before take any modifiaction
> 2. stop datacoord and datanode
> 3. run `birdwatcher` `remove channel` command ( this is the dry run step, no action will be take)
> 4. check all the suspects list to verify any all channel are safe to remove
> 5. run `remove channel --run` to actually remove orphan channels
> 6. Start datacoord and datanodes and check everything is fine

the birdwatcher will panic when i use  remove channel --run (the birdwatcher was builded from the latest commit ).
It seems that there is a problem with the interaction with etcd, when i use kill session command could cause same panic

Start to delete orphan watch channel info...
audio delete geek-blue-recall-v2/meta/channelwatch/100/geek-blue-recall-v2-rootcoord-dml_12_438401893539551538v0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x12fa165]

goroutine 1 [running]:
github.com/milvus-io/birdwatcher/states/etcd/audit.(*FileAuditKV).writeData(0xc0001702a0, {0xc0000340e8, 0x6, 0x6})
        /usr/mabingzheng/birdwatcher/states/etcd/audit/audit_write.go:45 +0xa5
github.com/milvus-io/birdwatcher/states/etcd/audit.(*FileAuditKV).writeHeader(0x152e640?, 0x1, 0x1)
        /usr/mabingzheng/birdwatcher/states/etcd/audit/audit_write.go:19 +0x8d
github.com/milvus-io/birdwatcher/states/etcd/audit.(*FileAuditKV).Delete(0xc0001702a0, {0x1a38bb8, 0xc00014dec0}, {0xc00047f490, 0x63}, {0x0, 0x0, 0x0})
        /usr/mabingzheng/birdwatcher/states/etcd/audit/audit.go:59 +0x1ba
github.com/milvus-io/birdwatcher/states/etcd/remove.ChannelCommand.func1(0xc000dd5b80?, {0x17b75ad?, 0x1?, 0x1?})
        /usr/mabingzheng/birdwatcher/states/etcd/remove/channel.go:77 +0x629
github.com/spf13/cobra.(*Command).execute(0xc000dd5b80, {0xc0004f07c0, 0x1, 0x1})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0xc000a3a280)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/milvus-io/birdwatcher/states.(*cmdState).Process(0xc0006aa230, {0xc001180120?, 0xc001300000?})
        /usr/mabingzheng/birdwatcher/states/states.go:63 +0x146
main.(*promptApp).promptExecute(0xc0003b6048, {0xc001180120?, 0x279a500?})
        /usr/mabingzheng/birdwatcher/main.go:126 +0x3f0
github.com/c-bata/go-prompt.(*Prompt).Run(0xc000404510)
        /root/go/pkg/mod/github.com/c-bata/go-prompt@v0.2.6/prompt.go:84 +0x755
main.runPrompt({0x1a40b40?, 0xc0004d51e8})
        /usr/mabingzheng/birdwatcher/main.go:184 +0x338
main.main()
        /usr/mabingzheng/birdwatcher/main.go:35 +0x176

**Comment by yanliang567** [comment]
/assign @congqixia 
could you please give a hand on this?

/unassign

**Comment by congqixia** [comment]
@bingbb47 thanks for your feed back! it looks like some fix is not merged, the patch pr could be check here
https://github.com/milvus-io/birdwatcher/pull/109
I will release v1.0.1 asap. You could try main branch after the patch merged if urgent

**Comment by bingbb47** [comment]
> @bingbb47 thanks for your feed back! it looks like some fix is not merged, the patch pr could be check here [milvus-io/birdwatcher#109](https://github.com/milvus-io/birdwatcher/pull/109) I will release v1.0.1 asap. You could try main branch after the patch merged if urgent

great! expecting
