### ISSUE TITLE
[Enhancement]: Use persistent segment tree to generate bitset for masking delete records

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#22702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Use persistent segment tree to generate this bitset:
- add a new version (point) for each delete request
- restore the bitset for the given travel timestamp by walking through the versions [0, ts], which takes only expected $O(\log{m})$ where $m$ is the number of delete records, and worst $O(m)$

An example with insert record `1..8`, and delete 3, 4, 5:
![image](https://user-images.githubusercontent.com/12216890/224535304-d1dc4bff-7066-4c3a-9d56-2dedab464f52.png)

You can even travel on a time range [start, end] with this and no performance impact 😀

### Why is this needed?

Each query/search request generates a bitset that indicates which insert records had been deleted (if not hit bitset cache), by the steps:
1. find all delete barrier (by travel timestamp)
2. for each delete record:
    1. find the offsets for the deleted pk in insert records, takes $O(log{n})$
    2. set the bits to 1 for the offsets

The total complexity is $O(m\log{n})$ where $n$ is the number of insert records, $m$ the number of delete records.
For a given delete record, which insert records (offsets) will be removed is consistent, but we calculate this for each query/search request.

### Anything else?

This works better if using time travel, or the cache will always be hit

**Comment by xiaofan-luan** [comment]
does it mean we have to cache the bitset for each delete timestamp?

**Comment by yah01** [comment]
> does it mean we have to cache the bitset for each delete timestamp?

no, the node in the tree only records whether all the data is deleted within its range

**Comment by xiaofan-luan** [comment]
I got loss about the example.

Can you further explain the data structure?

To get O(lg(m)) complexity, my idea is get something like a skiplist, we randomly generate some checkpoint between delete entries(cache the bitset at that ts) and apply all the delete between checkpoint1 and checkpoint2.

For instance, if we have 8 entries. and delete 4 at ts = 1, delete 2 at ts = 2 , delete 7 at ts 3, delete 0 at ts 4, then skiplist looks like

ts = 1     00001000
ts = 2    delete 2
ts = 3   delete 7
ts = 4    10101001

if we want to generate delete biset when ts = 2, then we find the last snapshot, which is ts =1, and apply ts =2, then we can get 00101000

**Comment by xiaofan-luan** [comment]
by evenly pick snapshot it can be o(lgm)
