### ISSUE TITLE
[Bug]: Scalar queries burn CPU in milvus::query::ExecExprVisitor::ExecRangeVisitorImpl()

### ISSUE THREAD

**Issue by akevdmeer** [milvus-io/milvus#22719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.3
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): Pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.0
- OS(Ubuntu or CentOS): FCOS
- CPU/Memory: 48 Xeon cores, 768G RAM on host
- GPU: n/a
- Others:
```

### Current Behavior

We're doing many simple scalar queries with `expr: field_name in [{field_values}]` and find our querynodes hitting their CPU limit in `milvus::query::ExecExprVisitor::ExecRangeVisitorImpl()` (established using `perf`)

The collection has > 100M rows and growing. Query performance gets worse as the collection grows. We've added resources to the querynodes repeatedly but are approaching the end of what we can do.

It looks like there is an O(_n_) cost factor involved, where _n_ is the number of rows in the collection, not the number of rows that satisfy the condition!

### Expected Behavior

The cost of a scalar query should not depend on the overall rows in the collection.

### Steps To Reproduce

```markdown
1. Create a collection with many rows
2. Run query with `in` condition and run profiler such as perf.
3. Insert many more rows and repeat, observe degrading performance.
```

**Comment by jiaoew1991** [comment]
Hi @akevdmeer, thank you for the discovery, This discovery is very important for us to improve performance.
Can you upload the prof sampling data?

**Comment by xiaofan-luan** [comment]
I thought that might be due to we make a termnode for each in condition.
Which means if in[1,2,3,4] you will filter 4 times

**Comment by yanliang567** [comment]
/assign @xiaofan-luan 
i think this is what we are trying to improve in query.

/unassign

**Comment by xiaofan-luan** [comment]
> /assign @xiaofan-luan i think this is what we are trying to improve in query.
> 
> /unassign

With velox support that should be fixed in 2.4

**Comment by xiaofan-luan** [comment]
/assign @zhagnlu 
pls take a look into it

**Comment by xiaofan-luan** [comment]
keep it and assign to @zhagnlu

**Comment by xiaofan-luan** [comment]
any updates? @zhagnlu

**Comment by zhagnlu** [comment]
will using dynamic simd to improve performance for this situation like  field_name in [{field_values}],  performance improve show as below:
![image](https://github.com/milvus-io/milvus/assets/11935707/3ba8a7e5-7257-4f94-b24e-3f47004b7101)

**Comment by zhagnlu** [comment]
> 

Haven't complete totally, this test is in UT. I will pull request tomorrow or next week.

**Comment by yanliang567** [comment]
@zhagnlu any updates
