### ISSUE TITLE
Search in "_default" partition failed by using javasdk

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#2272]
**Describe the bug**
Search in "_default" partition failed by using javasdk

**Steps/Code to reproduce behavior**
1. create a collection
2. search with partition tag="_default"

return error:  Cannot find specified partition

milvus version: 0.8.0
![webwxgetmsgimg (1)](https://user-images.githubusercontent.com/2282099/81465418-b0aaef80-91fc-11ea-952f-d394840daed4.jpeg)
![webwxgetmsgimg](https://user-images.githubusercontent.com/2282099/81465420-b4d70d00-91fc-11ea-979f-9fdf6cbc8b73.jpeg)

**Comment by sahuang** [comment]
Cannot reproduce, tested with search partition tag "_default" and result returned successfully.
