### ISSUE TITLE
[Bug]: [Nightly]The result of range search is lost with binary tanimoto flat index

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#22787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:80c6adb
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0.dev47
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The result of range search is lost with binary tanimoto flat index.
```
[2023-03-15T19:26:03.891Z] [2023-03-15 19:03:46 - ERROR - ci_test]: search_results_check: limit(topK) searched (1) is not equal with expected (2) (func_check.py:253)
```

### Expected Behavior

search succeed

### Milvus Log

1. link:https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/312/pipeline/155/
2. log: [artifacts-milvus-distributed-kafka-nightly-312-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/312/artifact/artifacts-milvus-distributed-kafka-nightly-312-pymilvus-e2e-logs.tar.gz)
3. collection name: search_collection_YTTbB1fq
4. failed time: [2023-03-15T19:03:47.419Z] [gw1] [ 84%] FAILED testcases/test_search.py::TestCollectionRangeSearch::test_range_search_binary_tanimoto_flat_index[500-32-False-True-True-BIN_FLAT]

**Comment by smellthemoon** [comment]
Perhaps the test code needs to be adjusted here. During the range search, the result may not be within the radius and filter range, resulting in the searched result being less than the limit.
<img width="702" alt="1" src="https://user-images.githubusercontent.com/64083300/225538943-baf4c787-c333-4095-a3eb-a267adadb126.png">
<img width="807" alt="2" src="https://user-images.githubusercontent.com/64083300/225538960-fca9e9fc-8a7b-4b71-bf3a-6fda8d1dbc2e.png">
@binbinlv plz help check if the distance of result is greater than 1000 or less than 0 (which were set to range and radius_filter).

**Comment by binbinlv** [comment]
closed.
