### ISSUE TITLE
[Bug]: Especially many flushRunner coroutines, when memory usage is high.

### ISSUE THREAD

**Issue by czs007** [milvus-io/milvus#22785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master/2.2.0
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I deployed standalone milvus on local bare metal and then ran torture testing code, I found that the milvus process started a lot of flushRunner coroutines and continued to grow.
The following is the statistical results from pprof, you can see that the number of flushRunner coroutines is as high as 168599.

```
goroutine profile: total 170381
168599 @ 0x1420696 0x13ec4ec 0x13ebf18 0x297827e 0x14526c1
#        0x297827d        [github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).waitFinish+0x3d](http://github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).waitFinish+0x3d)        /home/czs/milvus/internal/datanode/flush_task.go:186

```
At present, it is speculated that one of the strategies of DataCoord's segment sync policy is to detect that if memory usage is at a high level, it will trigger the sync action of segment.
Causes the datanode to keep opening the flushRunner task, and each flushRunner triggers the DataCoord to hold a large lock and then update etcd.
As the etcd update will be slower and slower, the phenomenon of high memory usage has not been alleviated in time, and more and more coroutines have also led to the continued rise of memory usage, which has led to an avalanche phenomenon.

**Comment by ThreadDao** [comment]
@czs007 
Test finished. Closet it first?
