### ISSUE TITLE
[Bug]: e2e test test_partition_upsert is not stable

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#22793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-22792/1/pipeline
![image](https://user-images.githubusercontent.com/12216890/225555365-1ad683a0-2d6c-4173-848a-66282a15d6b7.png)

**Comment by yah01** [comment]
/assign @NicoYuan1986 
/assign @smellthemoon 
Fix or skip?

**Comment by NicoYuan1986** [comment]
It will be fixed after my pr #22780 merged.

**Comment by yanliang567** [comment]
@NicoYuan1986 please help to verify and close it.

**Comment by NicoYuan1986** [comment]
verified fixed.
