### ISSUE TITLE
[Bug]: All versions of the official website have problems with partition usage and demos

### ISSUE THREAD

**Issue by HongqiZhao** [milvus-io/milvus#22795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://milvus.io/api-reference/pymilvus/v2.2.0/Partition/Partition().md
<html>
<body>
<h2 style="box-sizing: inherit; margin: 50px 0px 20px; padding: 0px; border: 0px; font-size: 32px; vertical-align: baseline; font-style: normal; font-weight: bold; line-height: 42px; color: rgb(0, 0, 0); font-family: Inter; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Invocation</h2><pre style="box-sizing: inherit; margin: 24px 0px; padding: 0px; border: 0px; font-size: 13px; vertical-align: baseline; border-radius: 4px; background-color: rgb(246, 246, 246); position: relative; color: rgb(25, 25, 25); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><code class="language-python hljs" style="box-sizing: inherit; margin: 12px 0px; padding: 12px; border: none; font-size: 14px; vertical-align: baseline; color: rgb(69, 69, 69); background: transparent; line-height: 20px; font-family: &quot;Source Code Pro&quot;; border-radius: 4px; display: block; font-weight: 400; overflow: auto;"><div class="code-module--codeSection--XTz70" style="box-sizing: inherit; margin: 0px; padding: 0px; border: 0px; font-size: 14px; vertical-align: baseline; font-family: &quot;Source Code Pro&quot;; line-height: 20px;">Partition(collection, name, description=<span class="hljs-string" style="box-sizing: inherit; margin: 0px; padding: 0px; border: 0px; font-size: 14px; vertical-align: baseline; color: rgb(84, 121, 13);">''</span>, **kwargs)
</div><button class="code-module--copyBtn--wxhFm" aria-label="Copy" style="box-sizing: inherit; position: absolute; cursor: pointer; top: 12px; right: 12px; border: none; padding: 0px; z-index: 2; background-color: transparent;"><svg aria-hidden="true" focusable="false" data-prefix="far" data-icon="copy" class="svg-inline--fa fa-copy " role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M502.6 70.63l-61.25-61.25C435.4 3.371 427.2 0 418.7 0H255.1c-35.35 0-64 28.66-64 64l.0195 256C192 355.4 220.7 384 256 384h192c35.2 0 64-28.8 64-64V93.25C512 84.77 508.6 76.63 502.6 70.63zM464 320c0 8.836-7.164 16-16 16H255.1c-8.838 0-16-7.164-16-16L239.1 64.13c0-8.836 7.164-16 16-16h128L384 96c0 17.67 14.33 32 32 32h47.1V320zM272 448c0 8.836-7.164 16-16 16H63.1c-8.838 0-16-7.164-16-16L47.98 192.1c0-8.836 7.164-16 16-16H160V128H63.99c-35.35 0-64 28.65-64 64l.0098 256C.002 483.3 28.66 512 64 512h192c35.2 0 64-28.8 64-64v-32h-47.1L272 448z"></path></svg></button></code></pre><h2 style="box-sizing: inherit; margin: 50px 0px 20px; padding: 0px; border: 0px; font-size: 32px; vertical-align: baseline; font-style: normal; font-weight: bold; line-height: 42px; color: rgb(0, 0, 0); font-family: Inter; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Parameters</h2>

Parameter | Description | Type | Required
-- | -- | -- | --
collection | Name of the collection | String | True
name | Name of the partition to create | String | True
description | Description of the collection | String | False

</body>
</html>

### Expected Behavior

*param: collection* is not a collection name, but an object of a collection class

### Steps To Reproduce

```markdown
none
```

### Milvus Log

none

### Anything else?

none

**Comment by XuanYang-cn** [comment]
@HongqiZhao Should be fixed by now

**Comment by yanliang567** [comment]
verified fixed on website page

**Comment by HongqiZhao** [comment]
Thanks
