### ISSUE TITLE
[BUG] memory usage increased slowly during searching vectors

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#228]
**Describe the bug**
The memory usage increased slowly, search 20h, and the usage increased 1G, the first 10h increased 0.5G and the next 10h increased 0.5G

**Steps/Code to reproduce behavior**
Do search continually

**Expected behavior**
No continually memory usage

**Environment details**
SQ8H index type
dataset: sift-500m-128d-l2

**Screenshots**

**Additional context**

**Comment by scsven** [comment]
fixed
