### ISSUE TITLE
[Bug]: python client insert string max_length=64 ,batch_insert errror

### ISSUE THREAD

**Issue by gyd-a** [milvus-io/milvus#22804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

bug:  字符串 最大长度限制到64,  批量插入数据失败，抱字符串长度超过64， 怀疑是把整个批量插入的数据长度和64比较了

**Comment by xiaofan-luan** [comment]
@yanliang567 pls help on reproducing it

**Comment by yanliang567** [comment]
@NicoYuan1986 
please help to reproduce it in house
/assign @NicoYuan1986 
/unassign

**Comment by NicoYuan1986** [comment]
fail to reproduce it in house. Can you give more details? such as pymilvus version, example data  ..
