### ISSUE TITLE
[Bug]: error="listen tcp :53100: bind: address already in use"

### ISSUE THREAD

**Issue by mintcckey** [milvus-io/milvus#22808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: found in 2.2.4，but could exist in earlier versions.
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: find during e2e test
```

### Current Behavior

After rootcoord restarts, it starts grpc server but discovers that the port is taken. Therefore rootcoord fails to be ready. Shortly after, proxycoord also restarts and it tries to create the rootcoord client but cannot find the session address from etcd. 

### Expected Behavior

When rootcoord stops, it does a graceful termination and the port should be released.

### Milvus Log

![image](https://user-images.githubusercontent.com/127183620/225794000-3a564336-92af-425b-a39a-2a7d75616bfe.png)

![image](https://user-images.githubusercontent.com/127183620/225794539-d6e9e02c-681a-4ec7-8cd3-faaa9c379700.png)

![image](https://user-images.githubusercontent.com/127183620/225794855-976b5934-d54a-4c29-a76f-449f2d44a217.png)

**Comment by xiaofan-luan** [comment]
port is binded.
You will need to kill the process using the port or change to another port

**Comment by mintcckey** [comment]
@xiaofan-luan Hi, this happens in the container environment (in k8s). Basically, the container restarts, program starts from the beginning and hit this issue because the previous run seems to not release the port after graceful termination. Do you think the dev team should take a look at it to figure out why the port is still bind after the container restarts? Thx.

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan Hi, this happens in the container environment (in k8s). Basically, the container restarts, program starts from the beginning and hit this issue because the previous run seems to not release the port after graceful termination. Do you think the dev team should take a look at it to figure out why the port is still bind after the container restarts? Thx.

sure, /assign @zwd1208
