### ISSUE TITLE
[Bug]: loadpatition block

### ISSUE THREAD

**Issue by hotwinters** [milvus-io/milvus#22803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):go最新的
- OS(Ubuntu or CentOS): windows
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

在尝试使用goSDk，loadpatition加载一个分区的时候，发现线程卡住了，调试进去看发现卡在select里，inmemorypercentages一直为nil，导致持续循环，此时我断开连接，再次打开但不再加载分区，发现能够成功搜索，和释放分区，也就是之前分区加载已经成功了，但不清楚为什么

**Comment by bigsheeper** [comment]
Hello, @hotwinters could you tell me of the version of Milvus you are using? Additionally, could you please provide me with the Milvus log? If you are unsure of how to export the Milvus log, you may refer to [this](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) guide. Thank you very much.

**Comment by hotwinters** [comment]
2.2version ,日志明天上午能够提供给您

**Comment by hotwinters** [comment]
@bigsheeper 日志文件太大了，我应该怎么调整日志的输出内容呀，以及想知道清空日志这些操作应该怎么做

**Comment by bigsheeper** [comment]
> @bigsheeper 日志文件太大了，我应该怎么调整日志的输出内容呀，以及想知道清空日志这些操作应该怎么做

If you're deploying with k8s, Milvus will automatically do log retension.

**Comment by bigsheeper** [comment]
@hotwinters No worries, I belive I have located the issue and will fix it promptly.

**Comment by hotwinters** [comment]
@bigsheeper ok. thanks

**Comment by bigsheeper** [comment]
Milvus Go SDK still uses ShowCollection and ShowPartitions to check the load state.However, ShowPartition does not assign the Type field to `ShowType_InMemory`, resulting in the ShowPartition request not being sent to QueryCoord.

Fix: now, ShowCollection and ShowPartitions are deprecated for checking load state, we should use GetLoadingProgress instead, as in pymilvus.

**Comment by hotwinters** [comment]
ok,学到了，我先部署下k8s，然后进行下一步的学习

**Comment by yanliang567** [comment]
close this issue for now.
please feel free to file a new issue, if any probelms
