### ISSUE TITLE
[Bug]: The data after travel timestamp is still visible

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#22810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The sealed segment ignores the travel timestamp, just returns all the insert records (delete records work well).

### Expected Behavior

Only data before travel timestamp is visible

**Comment by yah01** [comment]
@smellthemoon it may be related to the issues of upsert

**Comment by smellthemoon** [comment]
related to #22563

**Comment by yah01** [comment]
Milvus sets the travel timestamp to MaxTimestamp for search (not query), it will make the visible of batch write partial.

**Comment by xiaofan-luan** [comment]
> Milvus sets the travel timestamp to MaxTimestamp for search (not query), it will make the visible of batch write partial.

... good catch, might not be a serious problem in previous search.....but we definitely should handle it cleanly

**Comment by yah01** [comment]
Checked, travel on sealed segment respects timestamp, but search sets the travel timestamp to MaxTimestamp
