### ISSUE TITLE
[Bug]: when the status of collection is 'CollectionDropping', cannot create  alias as the same name

### ISSUE THREAD

**Issue by bingbb47** [milvus-io/milvus#22817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.3
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

when a collection be dropped, the status of the collection shows like 'CollectionDroping' in birdwatch.
this staus will remain for half an hour (like a drop gc tolerance), 
in this time , we can create a new collection with the same name, but cannot create a alias as the name

i think it seems unsuited

### Expected Behavior

none

### Steps To Reproduce

```markdown
none
```

**Comment by yanliang567** [comment]
sounds like 2 issues here:
1. collectionDropping statue in birdwather
2. cannot create an alias with the same name

/assign @congqixia 
could you please take a look?

/unassign

**Comment by congqixia** [comment]
/assign @yanliang567 
could you please help verify?

**Comment by yanliang567** [comment]
verified on master 0802 image
