### ISSUE TITLE
Poor search performance during building index in the background

### ISSUE THREAD

**Issue by shengjun1985** [milvus-io/milvus#2283]
**Is your feature request related to a problem? Please describe.**
Poor search performance during building index in the background.

**Describe the solution you'd like**
We can suspend the building tasks when any query command arrives.

**Describe alternatives you've considered**
Limit the CPU usage for building and searching tasks.
But the effect is poor.

**Additional context**
none

**Comment by JinHai-CN** [comment]
Do we have the benchmark on milvus if #2285 is merged?

**Comment by op-hunter** [comment]
| B  doesn’t build | B  build IVF_FLAT | B build IVF_PQ | B build IVF_SQ | B build HNSW | B build ANNOY | B build NSG
-- | -- | -- | -- | -- | -- | -- | --
A_IVFFLAT_search  costs | 25.86 | 26.416 | 29.431 | 27.376 | 26.216 25.768 25.379 | 21.201 | 26.855 29.485 31.415

@JinHai-CN @shengjun1985
