### ISSUE TITLE
[Bug]: Insert is very slowly

### ISSUE THREAD

**Issue by linggong2011** [milvus-io/milvus#22833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Insert is very slowly, milvus configuration as below:
queryNode:
  replicas: 1
  resources:
    requests:
      cpu: "14"
      memory: 52Gi

indexNode:
  replicas: 7
  resources:
    requests:
      cpu: "14"
      memory: 52Gi

### Milvus Log

[logs.tar.gz](https://github.com/milvus-io/milvus/files/11002237/logs.tar.gz)

**Comment by yanliang567** [comment]
@linggong2011 could you please also attach the datanode config and screenshots of milivus metrics?

**Comment by xiaofan-luan** [comment]
did you try to insert concurrently or in batch?

**Comment by changhong52** [comment]
no we are trying for batch

**Comment by changhong52** [comment]
but why insert one spend so long time about 100ms

**Comment by changhong52** [comment]
https://apm.shizhuang-inc.com/grafana?params=/d/uLf5cJ3GS/kubeone?orgId=1&var-datasource=csprd&var-app_name=milvus&var-namespace=kubeai-milvus-cv-clothes-v3&var-instance=milvus-cv-clothes-v3&var-collection=All&var-pod=milvus-cv-clothes-v3-datacoord-969b5b957-fwr2v&var-component=&from=now-2d&to=now

**Comment by xiaofan-luan** [comment]
> but why insert one spend so long time about 100ms

usually most time is consumed by kafka/pulsar.
You can take a look into proxy metrics see if you got any clue.
/assign @czs007 we also need to review the code in client and proxy see if there are anything we can do to improve

**Comment by changhong52** [comment]
监控和节点信息：每个节点16核，总数据量980万。index节点7*16核，query 1*16核 ，data 1*2核
![Uploading 节点数.jpeg…]()

**Comment by czs007** [comment]
> > but why insert one spend so long time about 100ms
> 
> usually most time is consumed by kafka/pulsar. You can take a look into proxy metrics see if you got any clue. /assign @czs007 we also need to review the code in client and proxy see if there are anything we can do to improve

ok. I will check the logic and do some experiments.

**Comment by xiaofan-luan** [comment]
keep it. 
@yanliang567  any progress?

**Comment by yanliang567** [comment]
trying to improve the insert throughput...keep it active
