### ISSUE TITLE
[Bug]: search with ignore_growing=True, but milvus actually search with ignore_growing=False

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#22840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.4
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): v2.2.3
```

### Current Behavior

search with ignore_growing=True, but milvus actually search with ignore_growing=False

### Expected Behavior

search with ignore_growing=True,

### Steps To Reproduce

```markdown
search with ignore_growing=True
collection.search(data=search_vectors, anns_field=field_name,
                                  param=search_params, limit=topk,
                                  ignore_growing=True)
```

### Milvus Log

in milvus log, it shows
  | "[{\"key\":\"anns_field\",\"value\":\"embedding\"},{\"key\":\"topk\",\"value\":\"1\"},{\"key\":\"metric_type\",\"value\":\"L2\"},{\"key\":\"params\",\"value\":\"{\\\"ef\\\":32}\"},{\"key\":\"round_decimal\",\"value\":\"-1\"},{\"key\":\"offset\",\"value\":\"0\"},{\"key\":\"ignore_growing\",\"value\":\"False\"}]"

### Anything else?

```
yanliang-cluster-1cu-milvus-datanode-cd55b8594-6hw6j             1/1     Running            0                 18h
yanliang-cluster-1cu-milvus-indexnode-69cc89b8fc-6hwrd           1/1     Running            0                 18h
yanliang-cluster-1cu-milvus-mixcoord-7fb8c9b8cd-q9mz6            1/1     Running            0                 18h
yanliang-cluster-1cu-milvus-proxy-59c7f74888-qqzzt               1/1     Running            0                 18h
yanliang-cluster-1cu-milvus-querynode-76fbd4f998-7bcl8           1/1     Running            0                 18h
yanliang-cluster-1cu-milvus-querynode-76fbd4f998-v9hb6           1/1     Running            0                 18h
```

**Comment by yanliang567** [comment]
ignore_growing parameter shall be in search_parameter, e.g.
        `search_params = {"metric_type": metric_type, "params": {"ef": ef}, "ignore_growing": True}`

**Comment by thaiminhpv** [comment]
According to https://milvus.io/api-reference/pymilvus/v2.4.x/MilvusClient/Vector/search.md , I can no longer see `ignore_growing` params
Is this params disabled in 2.4.x?
