### ISSUE TITLE
[Bug]: Can't load after restarting

### ISSUE THREAD

**Issue by hf185** [milvus-io/milvus#22860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: V2.2.3
- Deployment mode(standalone or cluster): standalone 
- MQ type(rocksmq, pulsar or kafka): pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: Memory
- GPU: 
- Others:
```

### Current Behavior

Use the K8S on the virtual machine to deploy Milvus-Standalone. After the virtual machine restarts, Milvus starts normally, but the previous test collection cannot be loaded successfully.

### Expected Behavior

Normally load, search

### Steps To Reproduce

```markdown
1. Use K8S on the virtual machine to deploy Milvus-Standalone
2. Start Zilliz/Attu
3. Create a collection, create index, Import Sample Data
4. Normal search
5. Turn off the virtual machine
6. Open the virtual machine
7. Waiting for K8S to start Milvus
8. Visit Zilliz/Attu
9. At this time, you can see that you have been loading, but the newly built collection can be loaded and searched normally
```

### Milvus Log

![e6e401e5cb950d16948923bfcc7e1c1](https://user-images.githubusercontent.com/43991218/226288351-0cfd96fe-f2b1-4ac9-b4db-7bd9d33280a1.png)

### Anything else?

![b57812616d4ffc56a38fab5809c2a83](https://user-images.githubusercontent.com/43991218/226289535-26fc6cbb-1e97-4dfa-a9c0-ac3e8f4c8d4e.png)

**Comment by congqixia** [comment]
@hf185 some quick questions:
1. <strike>what was the VirtualMachine you were using?</strike>
2. What was the storage milvus-standalone used? (minio/s3/local storage)

**Comment by hf185** [comment]
> @hf185 some quick questions:
> 
> 1. what was the VirtualMachine you were using? VMWare from offline info
> 2. What was the storage milvus-standalone used? (minio/s3/local storage)

2. minio

**Comment by Donglong** [comment]
same question. 
mivlus version: v2.2.8
