### ISSUE TITLE
[Enhancement]: Need an interface to check indexed rows & total rows of the given index in real time.

### ISSUE THREAD

**Issue by soothing-rain** [milvus-io/milvus#22888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Given an index, we'd like to know what's the status of the index building. Like how many rows are indexed v.s. how many rows are the in total.

The `DescribeIndex` is able to do this. However it will only check indexes created before `CreateIndex` call.

We want a new interface, .e.g. `GetIndexStats` works just like `DescribeIndex` but is able to check all indexes in real time.

**Comment by soothing-rain** [comment]
@wayblink People are suggesting the name `getIndexStatistics`. Let's go with that.

**Comment by wayblink** [comment]
@czs007  Why `DescribeIndex` only check indexes created before `CreateIndex `? Can I do it on `DescribeIndex`?
