### ISSUE TITLE
[Bug]: After upgrading Milvus from version 2.2.0 to 2.2.4, the load balancing of the query nodes is worse than in version 2.2.0

### ISSUE THREAD

**Issue by linggong2011** [milvus-io/milvus#22886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.4
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

After upgrading Milvus from version 2.2.0 to 2.2.4, the load balancing of the query nodes is worse than in version 2.2.0. At the same time, the query time has become several times slower. This may indicate that there are some performance or load balancing issues during the upgrade process, which have led to a decrease in query efficiency.

### Expected Behavior

The same as 2.2.0

**Comment by MrPresent-Han** [comment]
Is the test env still existed?

**Comment by MrPresent-Han** [comment]
according to test towards 2.2.8. load balance between has been improved marked by introducing new balance policy, which considers both replica and global data factor. So this issue can be closed

**Comment by yanliang567** [comment]
i'd close this issue. please feel free to file a new one if any new problems in v2.2.8
