### ISSUE TITLE
[Bug]: Pulsar subscription should use failover mode

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#22907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

panic: Failed to create consumer by-dev-rootcoord-dml_3, error = All attempts results:
attempt #1:server error: ConsumerBusy: Exclusive consumer is already connected

goroutine 102404 [running]:
github.com/milvus-io/milvus/internal/mq/msgstream.(*MqTtMsgStream).AsConsumer(0xc00958ab00, {0xc007c65af0?, 0x1, 0x3?}, {0xc007c7f540, 0x3e}, 0x2)

Although this is not the root cause, this error seems to be very annoying.

**Comment by yanliang567** [comment]
keep it
