### ISSUE TITLE
[Enhancement]: improve querycoord load balance

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#22914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

- [ ]  channel is never balanced  (Priority High) 
- [ ]  the balancer only care about replica and collection, but no global segment count.   this will lead to not balanced cluster when collection number is large but each collection has only 1-2 segments.  (Priority High) 
- [ ]  the balancer is not shard aware, segment within same shard should put together  (Priority Medium) 
- [ ]  the balancer should balance by segment size but not segment number of entities, because the dim of each collection might varies significantly. (Priority Low) 
- [ ]  the balancer should be load aware, considering request (Priority Low)

**Comment by yanliang567** [comment]
/assign @wangting0128 
please help to design some tests to verify the enhancement.

**Comment by MrPresent-Han** [comment]
@xiaofan-luan is this issue ok to close? I am controlling the number of issue on my head

**Comment by xiaofan-luan** [comment]
close for now.
Thanks for pointing this out
