### ISSUE TITLE
[Bug]: Test script `test_action_second_deployment.py` timeout(1h30min) and can not be finished in expected time (10min) 

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#22918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230321-67658f11
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/226791615-057de72e-01fc-4b08-87ef-a68c541ee8af.png)

### Expected Behavior

all test cases passed in expected time

### Milvus Log

image tag: master-20230321-67658f11
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_cron/detail/deploy_test_kafka_cron/538/pipeline
log:

[artifacts-kafka-standalone-reinstall-538-server-second-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/11035805/artifacts-kafka-standalone-reinstall-538-server-second-deployment-logs.tar.gz)

[artifacts-kafka-standalone-reinstall-538-server-first-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/11035807/artifacts-kafka-standalone-reinstall-538-server-first-deployment-logs.tar.gz)

[artifacts-kafka-standalone-reinstall-538-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11035810/artifacts-kafka-standalone-reinstall-538-pytest-logs.tar.gz)

### Anything else?

It works well when the Milvus is deployed with cluster mode.

**Comment by jiaoew1991** [comment]
/unassign
/assign @zhuwenxing 

Please verify it with https://github.com/milvus-io/milvus/pull/22977

**Comment by zhuwenxing** [comment]
Not reproduced in master-20230427-45fbe1d1
