### ISSUE TITLE
Where Can I download config version 0.4 ? How can I upgrade my 0.3 config ? 

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus#2291]
**What is your question?**
Just upgrade my docker, it said my config is not valid, I need version 0.4, but where can I find the valid 0.4 ? and how can I upgrade my config from 0.3 to 0.4 ?
![image](https://user-images.githubusercontent.com/185051/81534763-264cc200-939b-11ea-99f6-0cb631618434.png)

**Comment by tinkerlin** [comment]
checkout branch 0.8.0 and use milvus/core/conf instead.

**Comment by shanghaikid** [comment]
How can I upgrade my old one ?

**Comment by cydrain** [comment]
you're using master branch, your config file should be from master branch also.
