### ISSUE TITLE
[Bug]: too many useless log in mq producer

### ISSUE THREAD

**Issue by longjiquan** [milvus-io/milvus#22917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://github.com/milvus-io/milvus/blob/bc8fca80fa85c12b652add3f74985a4e3ae6f9ac/internal/mq/msgstream/mqwrapper/rmq/rmq_producer.go#L47

**Comment by longjiquan** [comment]
`TimeRecorder.Elapse` will print the log internally, so everytime the message has been produced to mq, a log will be printed, which is very frequent.

**Comment by longjiquan** [comment]
https://github.com/milvus-io/milvus/blob/bc8fca80fa85c12b652add3f74985a4e3ae6f9ac/internal/mq/msgstream/mqwrapper/kafka/kafka_producer.go#L73

**Comment by xiaofan-luan** [comment]
all start.Elapse should not print debug log ?

**Comment by longjiquan** [comment]
> all start.Elapse should not print debug log ?

`ElapseSpan` just return the span, not print the debug log.

**Comment by xiaofan-luan** [comment]
> > all start.Elapse should not print debug log ?
> 
> `ElapseSpan` just return the span, not print the debug log.

it  actually print a log for tracing I guess

**Comment by longjiquan** [comment]
Tracing can be done by the kafka/pulsar client themselves using the `ctx` if we really need to trace every message produced to the mq. Log printing is not reasonable here.

**Comment by xige-16** [comment]
same with https://github.com/milvus-io/milvus/issues/22619
