### ISSUE TITLE
[Bug]: collection无法load

### ISSUE THREAD

**Issue by HongqiZhao** [milvus-io/milvus#22923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):   pulsar  
- SDK version(e.g. pymilvus v2.0.0rc2):  pymilvus v2.0.0
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 充足
- GPU: 无
- Others: 无
```

### Current Behavior

1. 昨晚创建了一个partition，写了2000条数据后，删除掉了，然后release collection。
2. 又在该collection创建了一个同样名称的partition, load起来了，往partition里写入到现在约200w，然后search报错。
3. 上午把索引删除重建了，重建后就无法load了，自动取消。
4. 该集群 实体数为0的可以load，另外一个18w的load 20min到12%也自动取消了。（索引重建）

### Expected Behavior

正常load

**Comment by yanliang567** [comment]
/assign @NicoYuan1986 
could you please help to reproduce this on v2.2.4?

/unassign
