### ISSUE TITLE
0.8.0入库操作完成后，CPU占用一直很高

### ISSUE THREAD

**Issue by linven0721** [milvus-io/milvus#2293]
**What is your question?**
使用milvus-0.8.0-cpu-d041520-464404版本创建索引IVFSQ8，入库1.8亿数据，完成后，cpu一直占用很高，docker重启milvus之后，cpu还是很高。此时查询数据时，一直没有响应，会卡着。请问这是配置问题吗？

![cpu](https://user-images.githubusercontent.com/30649209/81540111-c0b10380-93a3-11ea-9b5e-58e03f3e391e.jpg)

**Comment by yhmo** [comment]
For cpu edition,  build index and search both use cpu. After you invoke create_index, all dara files were marked as 'to build index', milvus background thread will build index for these files one by one, even you restart milvus.
And cpu build index is very slow(slower than gpu by almost 10 times), so after you restart milvus, the background begin build index task and occupy most of cpu cores, and search task cannot get enough cpu resource to compute.
So you have to wait, until background thread finish build index task. For my experience, build index for an 1GB file could cost about 5~10 minute in a 12 cores machine.

**Comment by yhmo** [comment]
We are currently working on an issue relate to your issue: #2283
The solution is: when user invoke search api, milvus should stop build index task, release all cpu resource for seaching. Hopefully this enhancement could release in 0.9.0

**Comment by yhmo** [comment]
link to #2283

**Comment by linven0721** [comment]
> For cpu edition, build index and search both use cpu. After you invoke create_index, all dara files were marked as 'to build index', milvus background thread will build index for these files one by one, even you restart milvus.
> And cpu build index is very slow(slower than gpu by almost 10 times), so after you restart milvus, the background begin build index task and occupy most of cpu cores, and search task cannot get enough cpu resource to compute.
> So you have to wait, until background thread finish build index task. For my experience, build index for an 1GB file could cost about 5~10 minute in a 12 cores machine.

谢谢您的解答，我这边是在CPU：Gold6240（2颗，单颗18核）上面测试的，入库完之后的磁盘文件185GB，cpu一直占用，一两天也没建完索引，这是什么情况啊？可以通过哪些日志观察索引建立进度呢？

**Comment by yhmo** [comment]
Before build index, milvus will output a log like "Collect xxx to-index files", the 'xxx' is a number, indicate how many data files need to be build index.
You can find this log in /milvus/logs/xxxx.debug.log
