### ISSUE TITLE
[Bug]: Index loss after upgrading from 2.2.0 to 2.2.4

### ISSUE THREAD

**Issue by jiaoew1991** [milvus-io/milvus#22952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.4
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.0
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Two problems

First, some segments have no index after the upgrade, which leads to balance failure and unbalanced data between querynodes

The second is compact after the upgrade, which may cause the number of newly generated segment rows to be 0.

**Comment by yanliang567** [comment]
/assign @elstic 
please try to reproduce it in house.
/unassign

**Comment by elstic** [comment]
I upgraded from milvus 2.2.0 to 2.2.4, cluster, mq using pulsar, and did not reproduce some segments without index.

**Comment by elstic** [comment]
The index I am using is IVF_SQ8 and it is not reproduced, any more details please? I still have my environment, do you want to see it? @jiaoew1991

**Comment by yah01** [comment]
The segment's RowNum lost (be 0), newer(since v2.2.2) DataCoord re-calculates the number of rows by the binlogs' `EntriesNum`, which is not set for an older DataNode (before v2.2.1).

This results in the DataCoord's meta may be broken by the older DataNode

**Comment by yanliang567** [comment]
close for now.

**Comment by xiaofan-luan** [comment]
conclusion,
pls upgrade to v2.2.6 or above.
