### ISSUE TITLE
[Bug]: Remove TimeTick Stream.

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#22953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Time Tick Stream become the bottleneck when there are many collections or shards.
Each of the shards will send the tick per 100ms, and the DataNodeTtLoop must handle all of these ticks in time.
Otherwise flush will stuck and may causing many serious issues.

In fact we don't really need to use a channel to record all the time tick message, and we never care about the old timeticks when datacoord comes back.

So why not change the report to RPC? With carefully design we should be able to handle 1000+ collections with 100+ datanodes if they report every 200ms.

**Comment by jiaoew1991** [comment]
This issue looks more like an enhancement.
