### ISSUE TITLE
[Bug]: [benchmark][mmap]Enabling mmap when memory is sufficient leads to performance degradation

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#22954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230320-0317e045
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

deploy_config:fouramf-server-standalone-8c32m-mmap

case : test_concurrent_locust_hnsw_dml_dql_filter_standalone
argo task : fouramf-nb4tt 

server
```
fouramf-nb4tt-95-9732-etcd-0                                      1/1     Running     0               115s    10.104.5.61     4am-node12   <none>           <none>
fouramf-nb4tt-95-9732-milvus-standalone-78946b58b7-k8s5s          1/1     Running     0               115s    10.104.4.220    4am-node11   <none>           <none>
fouramf-nb4tt-95-9732-minio-9885ffdbd-9jzcz                       1/1     Running     0               115s    10.104.4.221    4am-node11   <none>           <none> 
```

  mem:
![image](https://user-images.githubusercontent.com/48523564/227120746-9a40ede2-7ec8-4c30-b88e-92878a5c62d5.png)
 
 Comparison of the same test scenario without opening mmap, query delay of about 56 ms when not opened, opened to 90ms.
The blue line is the latency without mmap enabled, the yellow line is the latency with it enabled.

![image](https://user-images.githubusercontent.com/48523564/227121195-7c4c88d6-601e-4826-9c14-261be00ea927.png)

### Steps To Reproduce

```markdown
1. create a collection or use an existing collection
        2. build index on vector column
        3. insert a certain number of vectors
        4. flush collection
        5. build index on vector column with the same parameters
        6. build index on on scalars column or not
        7. count the total number of rows
        8. load collection
        9. perform concurrent operations
        10. clean all collections or not
```

**Comment by yah01** [comment]
/assign
Looks like memory leaked

**Comment by yah01** [comment]
Milvus has a OOM problem with DataNode & DataCoord, @XuanYang-cn is fixing this, the growing memory usage will force the OS to evict some page cache (created by mmap), then the mmap version will slow down

**Comment by elstic** [comment]
Using this version: master-20230324-da58ba6a There is no performance degradation.

**Comment by xiaofan-luan** [comment]
keep it.
Is there still an issue on it?

**Comment by elstic** [comment]
> keep it. Is there still an issue on it?

After the pr of c++ load enters the master branch, I will verify the performance comparison again, and if there are no problems, I will close the issue .

**Comment by yah01** [comment]
keep it active

**Comment by xiaofan-luan** [comment]
do we support mmap on scalar data for now?

**Comment by yah01** [comment]
> do we support mmap on scalar data for now?

Yes,when mmap enabled, only RowID and Timestamp are still stored in memory, all the other data are stored in the mapped memory

**Comment by xiaofan-luan** [comment]
@yah01 
Did we already support mmap on scalar data?

**Comment by yah01** [comment]
> @yah01 Did we already support mmap on scalar data?

Yes

**Comment by elstic** [comment]
@xige-16 ,load pr has been merged in. After regression, there is no performance degradation with mmap on. 
Verify image: 
master-20230711-cb721781
