### ISSUE TITLE
[Enhancement]: Add `ServiceDiscovery` abstraction

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#22967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Add `ServiceDiscovery` abstraction and refactor `sessionutil` package

### Why is this needed?

With `ServiceDiscovery` abstraction, it's easier to integrate other registry service such as Consul, ZK, etc.
And currently the `Session` provides too much function which does not make sense, say "list other session"
Also, with `ServiceDiscovery` interface, we could implement internal process call in `Standlone`, `Mixcoord` or any other mixture deployment mode instead of heavy grpc call.

**Comment by congqixia** [comment]
- [ ] Add `ServiceDiscovery` interface definition
- [ ] Provides all features `sessionutil` has
- [ ] Adapt `ServiceDiscovery` as dependency in all components
  - [ ] Datacoord
  - [ ] Querycoord
  - [ ] RootCoord
  - [ ] DataNode
  - [ ] QueryNode
  - [ ] IndexNode
  - [ ] proxy

**Comment by xiaofan-luan** [comment]
keep it

**Comment by xiaofan-luan** [comment]
keep it open

**Comment by congqixia** [comment]
/reopen
still WIP
