### ISSUE TITLE
data_size in segment does not decrease after delete vectors and compact

### ISSUE THREAD

**Issue by sahuang** [milvus-io/milvus#2296]
**Describe the bug**
data_size in segment does not decrease after delete vectors and compact

**Steps/Code to reproduce behavior**
1) Insert 100000 vectors to collection
2) Flush, call showCollectionInfo to get collection info, and get segmentInfo from it
3) Record SegmentSize: segmentInfo.getLong("data_size")
4) Delete 100 vectors compact and flush
5) Record new segment size
6) New segment size is the same as previous segment size

**Expected behavior**
After 100 vectors deleted, compacted and flushed, row count decreases, so data_size should also decrease.

**Environment details**
- Latest master branch, used Java SDK

**Comment by del-zhenwu** [comment]
make sure call `flush first` and then `compact` after `delete` operation.
