### ISSUE TITLE
[Enhancement]: Avoid copy When load MemIndex

### ISSUE THREAD

**Issue by xige-16** [milvus-io/milvus#22986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

https://github.com/milvus-io/milvus/blob/a59dc9cbb059d122f10a63d5d8b968d207ef097b/internal/core/src/index/VectorMemIndex.cpp#L79-L84

milvus::Assemble did one memcpy , should merge assemble and LoadIndexToMemory

**Comment by xiaofan-luan** [comment]
keep it.
@xige-16 
this has to be in master branch, don't forget it

**Comment by jiaoew1991** [comment]
reopen it until merged into master.

**Comment by xiaofan-luan** [comment]
keep it, very importan
