### ISSUE TITLE
[Bug]: fail to release partition in 20 mins

### ISSUE THREAD

**Issue by clk1st** [milvus-io/milvus#22993]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:version:2.2.4
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):milvus-sdk-java v2.2.3
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 8核/32G
- GPU: 无
- Others: 无
```

### Current Behavior

After writing 176 pieces of data, loadPartitions prompts an error {exception=Exception: failed to load partitions, err=some partitions [440337800318080678] of collection 440337800317633660 has been loaded into QueryNode, please release partitions firstly, dataParme=Parame, dataParme=Loadsm=Load null}, and then the execution of releasePartition is very slow, and it has not been executed for more than 20 minutes.

### Milvus Log

log download：[https://test-1257093296.cos.ap-beijing.myqcloud.com/milvus_log.tar.gz](url)

**Comment by yanliang567** [comment]
@clk1st  how many partitions do you have, and how did you load them? for now there are some constraints in release a partition, please check here: https://milvus.io/docs/release_partition.md#Constraints. But failing to release a partition in 20 mins could be an issue.

/assign @soothing-rain 
/unassign

**Comment by clk1st** [comment]
> @clk1st 你有多少个分区，你是如何加载它们的？目前分区释放有一些限制，请查看这里： https: [//milvus.io/docs/release_partition.md#Constraints](https://milvus.io/docs/release_partition.md#Constraints)。但是未能在 20 分钟内释放分区可能是个问题。
> 
> /分配@soothing-rain /取消分配

One collection, two partitions, because the problem was found during test writing, and the amount of data is very small. The operation process is to check whether the partition exists when writing. If it does not exist, create a partition, then write data, and then load the partition to memory, and an error will be reported.

**Comment by xiaofan-luan** [comment]
> > @clk1st 你有多少个分区，你是如何加载它们的？目前分区释放有一些限制，请查看这里： https: [//milvus.io/docs/release_partition.md#Constraints](https://milvus.io/docs/release_partition.md#Constraints)。但是未能在 20 分钟内释放分区可能是个问题。
> > /分配@soothing-rain /取消分配
> 
> One collection, two partitions, because the problem was found during test writing, and the amount of data is very small. The operation process is to check whether the partition exists when writing. If it does not exist, create a partition, then write data, and then load the partition to memory, and an error will be reported.

you can not load one partition then the other one in 2.2.X.
You can either load partition, release partition, load two partitions.
or load collection.
but you can not load partition and load another one.

**Comment by clk1st** [comment]
> @clk1st how many partitions do you have, and how did you load them? for now there are some constraints in release a partition, please check here: https://milvus.io/docs/release_partition.md#Constraints. But failing to release a partition in 20 mins could be an issue.
> 
> /assign @soothing-rain /unassign



> > > @clk1st 你有多少个分区，你是如何加载它们的？目前分区释放有一些限制，请查看这里： https: [//milvus.io/docs/release_partition.md#Constraints](https://milvus.io/docs/release_partition.md#Constraints)。但是未能在 20 分钟内释放分区可能是个问题。
> > > /分配@soothing-rain /取消分配
> > 
> > 
> > One collection, two partitions, because the problem was found during test writing, and the amount of data is very small. The operation process is to check whether the partition exists when writing. If it does not exist, create a partition, then write data, and then load the partition to memory, and an error will be reported.
> 
> you can not load one partition then the other one in 2.2.X. You can either load partition, release partition, load two partitions. or load collection. but you can not load partition and load another one.

When the partition is loaded during the search, do I need to release it immediately after the search is completed? Or can it not be released, and the same partition will not be loaded next time? If it is not released, it will report an error when loading other partitions?

**Comment by xiaofan-luan** [comment]
> > @clk1st how many partitions do you have, and how did you load them? for now there are some constraints in release a partition, please check here: https://milvus.io/docs/release_partition.md#Constraints. But failing to release a partition in 20 mins could be an issue.
> > /assign @soothing-rain /unassign
> 
> > > > @clk1st 你有多少个分区，你是如何加载它们的？目前分区释放有一些限制，请查看这里： https: [//milvus.io/docs/release_partition.md#Constraints](https://milvus.io/docs/release_partition.md#Constraints)。但是未能在 20 分钟内释放分区可能是个问题。
> > > > /分配@soothing-rain /取消分配
> > > 
> > > 
> > > One collection, two partitions, because the problem was found during test writing, and the amount of data is very small. The operation process is to check whether the partition exists when writing. If it does not exist, create a partition, then write data, and then load the partition to memory, and an error will be reported.
> > 
> > 
> > you can not load one partition then the other one in 2.2.X. You can either load partition, release partition, load two partitions. or load collection. but you can not load partition and load another one.
> 
> When the partition is loaded during the search, do I need to release it immediately after the search is completed? Or can it not be released, and the same partition will not be loaded next time? If it is not released, it will report an error when loading other partitions?

load should not happens on search. It's a DDL operation that only need to be done once. 
Usually what you do is:
Create Collection
Create Partition
Create Index
Insert data.
Load Collection
Search.....
Create another partition(It will be auto loaded).

Or,
Create Collection
Create Partition
Create Index
Insert data.
Load Parititon
Search.....
Create another partition
Insert
Release Parititon
Load Two partitions,
Search..

**Comment by clk1st** [comment]
> 
Got it, thank you. My usage is not quite right. There is another problem. If you are loading partitions and searching for different partitions at the same time, you will report an error. In this scenario, you need to choose to load the collection?

**Comment by clk1st** [comment]
> > > @clk1st how many partitions do you have, and how did you load them? for now there are some constraints in release a partition, please check here: https://milvus.io/docs/release_partition.md#Constraints. But failing to release a partition in 20 mins could be an issue.
> > > /assign @soothing-rain /unassign
> > 
> > 
> > > > > @clk1st 你有多少个分区，你是如何加载它们的？目前分区释放有一些限制，请查看这里： https: [//milvus.io/docs/release_partition.md#Constraints](https://milvus.io/docs/release_partition.md#Constraints)。但是未能在 20 分钟内释放分区可能是个问题。
> > > > > /分配@soothing-rain /取消分配
> > > > 
> > > > 
> > > > One collection, two partitions, because the problem was found during test writing, and the amount of data is very small. The operation process is to check whether the partition exists when writing. If it does not exist, create a partition, then write data, and then load the partition to memory, and an error will be reported.
> > > 
> > > 
> > > you can not load one partition then the other one in 2.2.X. You can either load partition, release partition, load two partitions. or load collection. but you can not load partition and load another one.
> > 
> > 
> > When the partition is loaded during the search, do I need to release it immediately after the search is completed? Or can it not be released, and the same partition will not be loaded next time? If it is not released, it will report an error when loading other partitions?
> 
> load should not happens on search. It's a DDL operation that only need to be done once. Usually what you do is: Create Collection Create Partition Create Index Insert data. Load Collection Search..... Create another partition(It will be auto loaded).
> 
> Or, Create Collection Create Partition Create Index Insert data. Load Parititon Search..... Create another partition Insert Release Parititon Load Two partitions, Search..

Got it, thank you. My usage is not quite right. There is another problem. If you are loading partitions and searching for different partitions at the same time, you will report an error. In this scenario, you need to choose to load the collection?

**Comment by xiaofan-luan** [comment]
if you always search the whole collection, do load collection is the right choice.
load with partitioon usually works when you only need to search part of your collections
