### ISSUE TITLE
[Bug]: [Nightly]Binary search  returned 0 result with tanimoto flat index

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#23001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:081572d
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0.dev48
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Binary search  returned 0 result with tanimoto flat index
```
[2023-03-26T19:36:41.865Z] [2023-03-26 18:26:13 - ERROR - ci_test]: search_results_check: limit(topK) searched (0) is not equal with expected (2) (func_check.py:253)
```

### Expected Behavior

pass

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/323/pipeline/155/
2. log: [artifacts-milvus-distributed-kafka-nightly-323-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/323/artifact/artifacts-milvus-distributed-kafka-nightly-323-pymilvus-e2e-logs.tar.gz)
3. collection name: search_collection_7ElTx1fX
4. all failed cases:
```
test_search_binary_tanimoto_flat_index
test_search_binary_without_flush[TANIMOTO-True]
```

**Comment by cydrain** [comment]
should be fixed with knowhere-v2.1.1
related PR: https://github.com/milvus-io/knowhere/pull/783

**Comment by cydrain** [comment]
similar as #22403

**Comment by NicoYuan1986** [comment]
reproduced twice.
1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/324/pipeline/187
2. log: [artifacts-milvus-distributed-pulsar-nightly-324-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/324/artifact/artifacts-milvus-distributed-pulsar-nightly-324-pymilvus-e2e-logs.tar.gz)
3. failed time: 
```
[2023-03-27T18:28:10.970Z] [gw3] [ 45%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_binary_tanimoto_flat_index[500-32-False-False-True-BIN_FLAT]
[2023-03-27T18:29:24.948Z] [gw3] [ 46%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_binary_tanimoto_flat_index[500-32-True-True-True-BIN_IVF_FLAT]
```
