### ISSUE TITLE
API names change in python-sdk

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#2303]
**Describe the bug**
`
`pymilvus-test 0.3.14`

```
>>> from milvus import Milvus
>>> dir(Milvus)
['__class__', '__del__', '__delattr__', '__dict__', '__dir__', '__doc__', '__enter__', '__eq__', '__exit__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_cmd', '_connection', 'client_version', 'close', 'compact', 'connect', 'connected', 'count_entities', 'create_collection', 'create_index', 'create_partition', 'delete_entity_by_id', 'disconnect', 'drop_collection', 'drop_index', 'drop_partition', 'flush', 'get_collection_info', 'get_collection_stats', 'get_config', 'get_entity_by_id', 'get_index_info', 'handler', 'has_collection', 'has_partition', 'insert', 'list_collections', 'list_id_in_segment', 'list_partitions', 'load_collection', 'name', 'search', 'search_by_ids', 'search_in_segment', 'server_status', 'server_version', 'set_config', 'set_hook']
```

1. `_cmd` rename to `command`.
2. remove `search_by_ids`. instead of setting it to duplicated

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by BossZou** [comment]
Finished. Please check.
