### ISSUE TITLE
Is there a docker image with the diskann index enabled?

### ISSUE THREAD

**Issue by dada-2020** [milvus-io/milvus#23071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Is there a docker image with the diskann index enabled?

### Why is this needed?

need diskann

**Comment by xiaofan-luan** [comment]
I think so, @LoveEachDay

**Comment by filereadAndrew** [comment]
Is there a link to this docker image?

**Comment by LoveEachDay** [comment]
@dada-2020 @filereadAndrew By default the milvus image will support memory index and disk index at the same time. You can try milvus image from milvusdb/milvus:v2.2.0.
