### ISSUE TITLE
[Bug]: Can't connect milvus server

### ISSUE THREAD

**Issue by kaydxh** [milvus-io/milvus#23098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode standalone:
- MQ type rocksmq:    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I installed milvus Standalone with Docker Compose, https://milvus.io/docs/v2.0.x/install_standalone-docker.md
After installed milvus, I can telnet localhost 19530, but, I run  hello_milvus.go,  it has error.
go run hello_milvus.go 
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/16474709/228423198-831929b3-06ec-474e-a760-71ee4c8b7164.png">
<img width="1443" alt="image" src="https://user-images.githubusercontent.com/16474709/228423258-d1afdae1-dd16-4c78-be51-024eb9f1abae.png">

**Comment by kaydxh** [comment]
the existing issus is https://github.com/milvus-io/milvus/issues/20010, but can't find solution.

**Comment by yanliang567** [comment]
/assign @locustbaby 
could you please help to take a look?

/unassign

**Comment by locustbaby** [comment]
Hi @kaydxh ,
Sorry for the late reply, took some time to test but didn't reproduce.
From the error, more like a grpc error, I searched that and found [this](https://stackoverflow.com/questions/71627962/grpc-error-how-to-solve-connection-closed-before-server-preface-received)
Do you enable the tls config ?

**Comment by kaydxh** [comment]
> Hi @kaydxh , Sorry for the late reply, took some time to test but didn't reproduce. From the error, more like a grpc error, I searched that and found [this](https://stackoverflow.com/questions/71627962/grpc-error-how-to-solve-connection-closed-before-server-preface-received) Do you enable the tls config ?

Yes, I have enabled the config, but it still not work in centos7, in macOS it works ok.
