### ISSUE TITLE
[Enhancement]: introduction of the Pulsar Admin Go Library

### ISSUE THREAD

**Issue by ericsyh** [milvus-io/milvus#23097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Hi Milvus team,

I know that currently, several Milvus projects are using the pulsarctl's internal pkg for the Pulsar Admin library. To have a better dependency management, we have already extracted the internal pkg as a separate go library [pulsar-admin-go](https://github.com/streamnative/pulsar-admin-go), and we will keep iterating and maintaining this library. 

If possible, I will suggest changing the Milvus projects dependency to this new library, and very welcome to give us some feedback or engage in it.

**Comment by xiaofan-luan** [comment]
good suggestion!
We will working on investigating it
