### ISSUE TITLE
[Enhancement]: Set the search pool size used in diskann search in milvus.yaml

### ISSUE THREAD

**Issue by cqy123456** [milvus-io/milvus#23120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

The current threads number in query node is depended on cpu number, which is not enough for diskann performance.  Use a new key in milvus.yaml to increase threads num can increase disk IOPS to improve performance.

**Comment by xiaofan-luan** [comment]
it should be set by a yaml file right? I would suggest there is a dynamic tuning policy
