### ISSUE TITLE
[Bug]:  err = collection 440481549438831999 has not been loaded to memory or load failed

### ISSUE THREAD

**Issue by kubecutle** [milvus-io/milvus#23178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: image: milvusdb/milvus:v2.2.5
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    No MQ
- SDK version(e.g. pymilvus v2.0.0rc2): Java SDK 2.2.4
- OS(Ubuntu or CentOS): Ubuntu 22
- CPU/Memory: 24 GB
- GPU: 
- Others:
```

### Current Behavior

When I execute searches I see the following error:

```
SearchRequest failed:
checkIfLoaded failed when search, collection:b4b78a08_2a75_48e8_a6f9_1015aa808893, partitions:[], err = GetCollectionInfo failed, collection = b4b78a08_2a75_48e8_a6f9_1015aa808893, err = collection 440481549438831999 has not been loaded to memory or load failed
```

My code is following:
```
       milvusClient.loadCollection(
        LoadCollectionParam.newBuilder()
          .withCollectionName(collectionId)
          .build()
        );
        int SEARCH_K=3;
        SearchParam searchParam = SearchParam.newBuilder()
		.withCollectionName(collectionId)
		.withConsistencyLevel(ConsistencyLevelEnum.EVENTUALLY)
		.withMetricType(MetricType.L2)
		.withOutFields(Arrays.asList("chunk_id"))
		.withTopK(SEARCH_K)
		.withVectors(Arrays.asList(embedding.getEmbedding().stream().map(Double::floatValue).collect(Collectors.toList())))
		.withVectorFieldName("embedding")
		.withParams(SEARCH_PARAM)
		.build();
```

I saw  in a previous thread that calling num_entities could be a workaround. How do I call this function with the Java client?

**Comment by yanliang567** [comment]
/assign @yhmo 
any ideas?

/unassign

**Comment by kubecutle** [comment]
There is an example in the milvus-java-sdk that I was able to run successfully. I am now trimming it down to see what I missed. One thing I can already say is that I wasn't creating an index. Though I suspect I missed something else because just missing an index would have produced an index related issue.

**Comment by lisong888** [comment]
Version 2.2. x requires the creation of an index before the collection can be loaded into memory

**Comment by xiaofan-luan** [comment]
> Version 2.2. x requires the creation of an index before the collection can be loaded into memory

exacly! we add a new constraint here
