### ISSUE TITLE
[Bug]: PartitionNotFound when searching on an empty partition

### ISSUE THREAD

**Issue by W2Q3Q1** [milvus-io/milvus#23187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.4
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): Docker default
- SDK version(e.g. pymilvus v2.0.0rc2):  pymilvus 2.2.3
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: Not used
- Others:
```

### Current Behavior

Exception PartitionNotFound raised when trying to search something on an empty partition. This behavior is not specified on the document, and is weird.

### Expected Behavior

Just return empty list.

### Steps To Reproduce

```markdown
The python demo is shown below.


import pymilvus

host = "localhost"
port = "19530"
alias = "alias"
collection = "collection"
key = "key"
value = "value"
partition = "partition"
dim = 2

if __name__ == "__main__":
    pymilvus.connections.connect(
        alias=alias,
        host=host,
        port=port
    )
    key_schema = pymilvus.FieldSchema(
        name=key,
        dtype=pymilvus.DataType.INT64,
        is_primary=True,
        auto_id=True
    )
    value_schema = pymilvus.FieldSchema(
        name=value,
        dtype=pymilvus.DataType.FLOAT_VECTOR,
        dim=dim,
    )
    collection_schema = pymilvus.CollectionSchema(
        fields=[key_schema, value_schema],
    )
    collection = pymilvus.Collection(
        name=collection,
        schema=collection_schema,
        using=alias,
        consistency_level="Strong"
    )
    index_params = {
        "metric_type": "IP",
        "index_type": "FLAT",
        "params": {}
    }
    collection.create_index(
        field_name=value,
        index_params=index_params
    )
    collection.load()
    collection.create_partition(
        partition_name=partition
    )
    # collection.insert(
    #     data=[[[float(0.1) for _ in range(dim)]]],
    #     partition_name=partition
    # )
    search_type = "FLAT"
    search_params = {
        "metric_type": "IP",
        "params": {}
    }
    collection.search(
        data=[[float(0.1) for _ in range(dim)]],
        anns_field=value,
        param=search_params,
        limit=1,
        partition_names=[partition],
        consistency_level="Strong"
    )
    collection.release()
    pymilvus.connections.disconnect(
        alias=alias
    )
```
```


### Milvus Log

_No response_

### Anything else?

_No response_

**Comment by yanliang567** [comment]
/assign @NicoYuan1986 
please help to reproduce it in house
/unassign

**Comment by NicoYuan1986** [comment]
Reproduced in house.
```
RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
attempt #1:code: UnexpectedError, error: fail to Search, QueryNode ID=1, reason=stream operation failed: PartitionNotFound(partitionID=440552970972038818)
attempt #2:context canceled
)>, <Time:{'RPC start': '2023-04-04 10:49:36.523571', 'RPC error': '2023-04-04 10:49:36.756933'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 614, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 483, in search
    return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 452, in _execute_search_requests
    raise pre_err
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 443, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
attempt #1:code: UnexpectedError, error: fail to Search, QueryNode ID=1, reason=stream operation failed: PartitionNotFound(partitionID=440552970972038818)
attempt #2:context canceled
```
/assign @smellthemoon please help to resolve it, thx.

**Comment by NicoYuan1986** [comment]
Update: not reproduced on master. reproduced on 2.2.5 branch

**Comment by yanliang567** [comment]
/assign @smellthemoon 

@NicoYuan1986 please help to add a testcase for this, thx

**Comment by smellthemoon** [comment]
Thank you very much @W2Q3Q1 , this problem has been solved on the master and 2.3 #22655 , but it is difficult to solve it well on 2.2 at this stage. This problem is because there is no data insert on the partition, which causes the cache on the querynode to not be updated, so there is no record of this partition in the cache during query/search, resulting in PartitionNotFound. Now there are two ways to solve this problem. 1. Considering that search is relatively meaningless in the absence of data , you can insert any legal data on this partition, and then search without any problem; 2. This problem has been solved on 2.3, you can wait for the release of 2.3.

**Comment by W2Q3Q1** [comment]
Thanks for your reply very much! We have solved that problem in our application by checking whether specific exception happens and whether PartitionNotFound is inside the exception information. Also, we are now thinking about updating to Milvus 2.3.

**Comment by xiaofan-luan** [comment]
> Thank you very much @W2Q3Q1 , this problem has been solved on the master and 2.3 #22655 , but it is difficult to solve it well on 2.2 at this stage. This problem is because there is no data insert on the partition, which causes the cache on the querynode to not be updated, so there is no record of this partition in the cache during query/search, resulting in PartitionNotFound. Now there are two ways to solve this problem. 1. Considering that search is relatively meaningless in the absence of data , you can insert any legal data on this partition, and then search without any problem; 2. This problem has been solved on 2.3, you can wait for the release of 2.3.

is there a quick fix for 2.2.X?

**Comment by W2Q3Q1** [comment]
> > Thank you very much @W2Q3Q1 , this problem has been solved on the master and 2.3 #22655 , but it is difficult to solve it well on 2.2 at this stage. This problem is because there is no data insert on the partition, which causes the cache on the querynode to not be updated, so there is no record of this partition in the cache during query/search, resulting in PartitionNotFound. Now there are two ways to solve this problem. 1. Considering that search is relatively meaningless in the absence of data , you can insert any legal data on this partition, and then search without any problem; 2. This problem has been solved on 2.3, you can wait for the release of 2.3.
> 
> is there a quick fix for 2.2.X?

Yes. If you COULD make sure that specific partition SHOULD exist (which means PartitionNotFound happens iif it is empty), you can try Search method, catch the Exception and test if string "PartitionNotFound" is inside the Exception's information.

**Comment by smellthemoon** [comment]
> > Thank you very much @W2Q3Q1 , this problem has been solved on the master and 2.3 #22655 , but it is difficult to solve it well on 2.2 at this stage. This problem is because there is no data insert on the partition, which causes the cache on the querynode to not be updated, so there is no record of this partition in the cache during query/search, resulting in PartitionNotFound. Now there are two ways to solve this problem. 1. Considering that search is relatively meaningless in the absence of data , you can insert any legal data on this partition, and then search without any problem; 2. This problem has been solved on 2.3, you can wait for the release of 2.3.
> 
> is there a quick fix for 2.2.X?

On 2.2.x, there is no code to fix it, and three methods have been considered, 1. querynode consumes ddl from the stream, 2. cherry-pick #22655 , 3. to check whether it is loaded in proxy, and then if the consistency level is not strong, ignore the PartitionNotFound error. But considering that the first two changes are too large, but the third one cannot check the consistency level here, the solution on 2.2.x is to insert arbitrary data on this partition.

**Comment by xkliu-only** [comment]
How do I insert data separately for this error-reporting partition @smellthemoon

**Comment by yanliang567** [comment]
> How do I insert data separately for this error-reporting partition @smellthemoon

you can specify the partition name when inserting: https://milvus.io/api-reference/pymilvus/v2.2.x/Collection/insert().md
