### ISSUE TITLE
[Feature]: Support cosine similarity

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#23206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

a lot of NLP users want to use cosine similarity.

it's actually nothing but faiss.normalize_L2() + IP distance

**Comment by amityahav** [comment]
@xiaofan-luan hey I would like to give it a shot. Could you point me where to start?

**Comment by amityahav** [comment]
@xiaofan-luan Thank you I will take a look

**Comment by liliu-z** [comment]
Hi @amityahav , Yes we are working this, The vector index related work of Mivuls is in https://github.com/milvus-io/knowhere, and more than welcome for any contributions and questions.

**Comment by caesarjuly** [comment]
@liliu-z Hi, is there any update on this issue? I'd like to work on it.

**Comment by xiaofan-luan** [comment]
I 

> @liliu-z Hi, is there any update on this issue? I'd like to work on it.

I thought @cydrain  is working on it, any progress?

**Comment by caesarjuly** [comment]
@xiaofan-luan Thanks for the quick reply. I look around and find some `COSINE` related codes in knowhere. So it probably has been done.
BTW, I'm looking for opportunities to contribute to open source projects and find Milvus is an excellent candidate. If there is any `good first issue` pending, I will be happy to help. I'm a senior MLE and quite familiar with ML and embeddings. Thanks!

**Comment by garyhlai** [comment]
I think this issue can be closed right? If the vectors are normalized (i.e. with magnitude of 1), the dot product is the exactly the same as cosine similarity because cosine(x) = inner product / product of magnitude

**Comment by duongktr** [comment]
hi @garyhlai, so as you said, i can use IP in the search param config if I want to calculate cosine distance when my vector is normalized to [0,1], right ?

**Comment by xiaofan-luan** [comment]
> hi @garyhlai, so as you said, i can use IP in the search param config if I want to calculate cosine distance when my vector is normalized to [0,1], right ?

use 2.3.1 so you can directly use cosine metrics

**Comment by duongktr** [comment]
@xiaofan-luan I'm currently using v2.2.x, including both pymilvus and Milvus service docker running, should I upgrade both or just need to modify pymilvus ?

**Comment by xiaofan-luan** [comment]
use ip distance and normalize your vectors, you will get samilar disatance as cosine

**Comment by xiaofan-luan** [comment]
you can normalize your vector so IP is as same as consine metrics. max distance will be 1

**Comment by YangZhaoo** [comment]
> you can normalize your vector so IP is as same as consine metrics. max distance will be 1

OK，thank you
