### ISSUE TITLE
[Bug]: [benchmark]load memory usage more 

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#23209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Save load memory pr After entering, load memory usage is higher instead .
index : HNSW 
dataset : 6m 128d
image : 

Adjusting memory usage before load：6G ,image : 2.2.0-20230324-9c3c29db
![image](https://user-images.githubusercontent.com/48523564/229703391-ed78f5be-5526-48fb-9495-cae3db51774e.png)

Adjusting memory usage after load：  6.68G, image: xige-16-opt-mem-copy-aa2886b-20230403
 
![image](https://user-images.githubusercontent.com/48523564/229703070-1b1cbbf5-ff38-4191-8aa1-bd59be19b5a6.png)

 

### Expected Behavior

Adjusted memory usage after load less than peak memory usage before load adjustment

**Comment by elstic** [comment]
### [cluster] load memory not saved

#### Current Behavior

Adjusting memory usage before load：4.3G (querynode)
![image](https://user-images.githubusercontent.com/48523564/229705145-9beb3c06-f760-454a-9f72-0b46b09a8d8d.png)


Adjusting memory usage after load： 5.5G (querynode)
![image](https://user-images.githubusercontent.com/48523564/229704864-5e95a33c-a912-4134-ab9c-c01531696eae.png)

**Comment by binbinlv** [comment]
@xige-16 
what is the progress now?

**Comment by xige-16** [comment]
2.2.0 has been verifyed , and can load more data

**Comment by elstic** [comment]
issue Validated, please be aware that:   @yanliang567 

After entering load pr, slightly more memory resources are needed when memory is sufficient, but more data can be loaded when resources are limited.
See the table for details:

(standalone ， index : HNSW)
| data_size\image  |  memory  |  v2.2.5    | 2.2.0-20230425-e820479b  |
|  ----|  ----  | ----  | ----  |
| 6m |     Sufficient resources    |  6.23G | 6.81G|
| 8m |     2c9g    | load failed  | 7.22G  |

**Comment by yanliang567** [comment]
@elstic so shall we close this issue now?

**Comment by elstic** [comment]
> @elstic so shall we close this issue now?

Yes, I'll close this issue
