### ISSUE TITLE
[Enhancement]: Remove ANNOY index type

### ISSUE THREAD

**Issue by cydrain** [milvus-io/milvus#23200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

ANNOY index type has low recall and high memory consumption, few users use it.
Decide to remove ANNOY from Milvus.

**Comment by cydrain** [comment]
ANNOY has been removed from knowhere vis this PR
https://github.com/milvus-io/knowhere/pull/796

**Comment by xiaofan-luan** [comment]
Agree! @cydrain pls follow up on on document side

**Comment by cydrain** [comment]
have created following issue to update the supported index types in doc
https://github.com/milvus-io/milvus/issues/23285
