### ISSUE TITLE
[Bug]: CPU & Memory usage of datacoord keeps increasing

### ISSUE THREAD

**Issue by cndpzc** [milvus-io/milvus#23211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.4
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I noticed cpu usage of `datanode` was high, I updated cpu limit of `datanode` from 1 to 2 (at around 11:00). After restarting the cpu usage of `datanode` became normal, but several hours later I noticed cpu & memory of `datacoord` kept increasing. It seems to be caused by the increase of open fds. 

<img width="1826" alt="image" src="https://user-images.githubusercontent.com/3941929/229711797-86195142-ccde-434d-b6d4-7d29b0be0269.png">

<img width="1837" alt="image" src="https://user-images.githubusercontent.com/3941929/229716866-f067365d-f57e-41f2-9139-f85c81c07a0c.png">

Didn't see any exception in `datacoord` or `datanode` metrics.
<img width="1819" alt="image" src="https://user-images.githubusercontent.com/3941929/229717815-0187c25f-7f62-45fa-85ea-8b6061d3f277.png">
<img width="1812" alt="image" src="https://user-images.githubusercontent.com/3941929/229718133-a7407882-f6e0-401b-af74-fcba22b5ed95.png">

### Milvus Log

[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/11145578/milvus-log.tar.gz)

**Comment by xiaofan-luan** [comment]
opened fds keeps increasing
/assign @sunby

**Comment by cndpzc** [comment]
BTW I'm also seeing cpu usage of `datanode` keeps increasing for days, with the memory relocate rate and free rate increasing. But the insert vector rate is quite low, about 10/s in avg.
<img width="1849" alt="image" src="https://user-images.githubusercontent.com/3941929/230254205-d85e5b4d-a6db-461e-880f-5309f11e02a0.png">
<img width="1830" alt="image" src="https://user-images.githubusercontent.com/3941929/230254506-3291e579-b8f0-4c79-b7e3-b69ada46e69c.png">

**Comment by xiaofan-luan** [comment]
seems that something in memory is growing. 
could you pprof on datanode and see the heap usage?
we have 9091 enabled so you can directly go with the pprof webui

**Comment by cndpzc** [comment]
datacoord: 
[pprof.milvus.samples.cpu.001.pb.gz](https://github.com/milvus-io/milvus/files/11228529/pprof.milvus.samples.cpu.001.pb.gz)

**Comment by cndpzc** [comment]
datanode:
[pprof.milvus.samples.cpu.002.pb.gz](https://github.com/milvus-io/milvus/files/11228548/pprof.milvus.samples.cpu.002.pb.gz)

**Comment by xiaofan-luan** [comment]
great, let me take a look into it

**Comment by xiaofan-luan** [comment]
![profile002](https://user-images.githubusercontent.com/83447078/232123610-b9488a97-313f-402f-982e-4e02c1e06258.png)
![profile001](https://user-images.githubusercontent.com/83447078/232123616-ba0ab2eb-fc46-47be-97c4-7728dde98cb7.png)

**Comment by xiaofan-luan** [comment]
it seems that zap.logger takes eats too much cpus. I will take a look and make sure it won't happen

**Comment by xiaofan-luan** [comment]
log.Warn("failed to get segment statistics info", zap.Int64("segmentID", sid), zap.Error(err))

I thought you are hitting some issue with this log

**Comment by xiaofan-luan** [comment]
it's actually fixed by
https://github.com/milvus-io/milvus/issues/22976

**Comment by xiaofan-luan** [comment]
restart will help for now, or upgrade to 2.2.6 directly
