### ISSUE TITLE
[Bug]: helm value.yaml "extraConfigFiles" parameter does not effects.

### ISSUE THREAD

**Issue by sd1620597** [milvus-io/milvus#23213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.5
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):  kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When we upgrade milvus from 2.2.3 to 2.2.5 we found extraConfigFiles does not effects.
But 2.2.3 does well.
`extraConfigFiles:
  user.yaml: |+
    common:
      retentionDuration: 0
    dataCoord:
      segment:
        maxSize: 128`
And, I edit milvus.yaml in pod. It effects.
I guest the priority of milvus.yaml is higher than user.yaml.

**Comment by yanliang567** [comment]
/assign @LoveEachDay 
can we reproduce it in house?

/unassign

**Comment by JackLCL** [comment]
@sd1620597 
Can you use "helm ls" command to verify which helm chart version you are using?
I doubt you are use older helm chart version(<4.0.0). So  helm value.yaml "extraConfigFiles" parameter does not effects.

**Comment by sd1620597** [comment]
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
my-release      milvus          15              2023-04-07 11:16:26.061529042 +0800 CST deployed        milvus-4.0.13   2.2.3

**Comment by sd1620597** [comment]
`NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
my-release      milvus          15              2023-04-07 11:16:26.061529042 +0800 CST deployed        milvus-4.0.13   2.2.3 `

**Comment by LoveEachDay** [comment]
We've proceed the following tests:
1. install a milvus cluster with chart version `4.0.11` with milvus version `v2.2.3`
```
helm install test-1 milvus/milvus --version=4.0.11
```
![image](https://user-images.githubusercontent.com/1573213/231375465-deeb12ae-beb9-444b-82a1-bb63da5efca5.png)

2. create a `new-values.yaml` with the following config:
```
extraConfigFiles:
  user.yaml: |+
    common:
      retentionDuration: 0
    dataCoord:
      segment:
        maxSize: 128
```
3. upgrade milvus to most recent chart version `4.0.14` with mivus version `v2.2.5`:
```
helm upgrade test-1 milvus/milvus --version=4.0.14 -f new-values.yaml
```
<img width="1503" alt="image" src="https://user-images.githubusercontent.com/1573213/231375522-4441dcfc-2636-4e5b-babf-619c6c5469c0.png">
4. checkout the configmap:
```
kubectl get configmap test-1-milvus -o yaml
```
We can see the new configuration is set under `user.yaml` section.
<img width="1497" alt="image" src="https://user-images.githubusercontent.com/1573213/231377315-028a1cb2-966b-4618-a6fc-1a19c7be8eed.png">

5. Login milvus pod to check whether `configs/milvus.yaml` is updated.
![image](https://user-images.githubusercontent.com/1573213/231377753-2a44d700-8041-4936-b861-1da3da184b91.png)

 We can see the upgrade is successfully proceed.

**Comment by sd1620597** [comment]
My user.yaml in pod is updated too.
But, in attu, it is still default value.
The only way I found to change the value in attu is changing the milvus.yaml in the pod.
And restart the pod by killing main process.
