### ISSUE TITLE
[Enhancement]: Remove load cache in Proxy

### ISSUE THREAD

**Issue by bigsheeper** [milvus-io/milvus#23214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

I propose that we should remove the load cache in Proxy for the following reasons:
1. Keeping load cache in Proxies is a complex and chaotic process;
2. The Proxy already holds shard leader cache, which is adequate;
3. Removing the load cache would not reduce query performance;
4. The collection load cache in Proxy is inaccurate because it does not update after loadPartition or releasePartition, thus requiring ShardLeaders to check again. (see also: #23141)

So, after removing cache in Proxy, query requests will be sent to ShardLeaders, and ShardLeaders are responsible for checking if the collection or partitions are loaded. 
![image](https://user-images.githubusercontent.com/42060877/229717049-e00d4db2-ee84-4cf2-b996-657cfc1fb63b.png)

**Comment by xiaofan-luan** [comment]
Agreed~
shard leader cache works for that

**Comment by bigsheeper** [comment]
completed
