### ISSUE TITLE
部署milvus集群后进行查询返回search failed

### ISSUE THREAD

**Issue by Vergissmeinicht** [milvus-io/milvus#2322]
我在两台机子上部署了cpu-only版的milvus服务，并进行查询操作。发送至cluster_writable的结点可以正常返回查询结果，发送至cluster_readonly的结点会返回：
Searching ...
Search failed.  Status(code=1, message="Collection file doesn't exist: /var/lib/milvus/db/tables/example_collection_2/1589339806692851000/1589339806692851000")
两台机子上部署cpu-only单点版的milvus都可以进行正常操作 ，请问我可能是哪里出错了？

**Comment by Vergissmeinicht** [comment]
I've run two cpu-only milvus on two machines using mishards. It turns out that a "search failed" response occurs when I send a search request which is routing to cluster_readonly server, while request routing to cluster_writable server can lead to correct response.

The failed message is below:
Searching ...
Search failed. Status(code=1, message="Collection file doesn't exist: /var/lib/milvus/db/tables/example_collection_2/1589339806692851000/1589339806692851000")

I've run single cpu-only milvus on the two machines I mention above separately and everything goes well. Does anyone know how to fix this?

**Comment by tinkerlin** [comment]
Milvus currently uses mishards to support distributed deployments.
Refer to [https://github.com/milvus-io/milvus/tree/master/shards](url)

**Comment by BossZou** [comment]
@Vergissmeinicht May you support your running code and configure file of milvus  cluster_readonly node ?

**Comment by Vergissmeinicht** [comment]
> @Vergissmeinicht May you support your running code and configure file of milvus cluster_readonly node ?

Here's configuration for cluster_writable node:
`
version: 0.3
server_config:
  address: 0.0.0.0
  port: 19530
  deploy_mode: cluster_writable
  time_zone: UTC+8
  web_port: 19121
db_config:
  backend_url: mysql://test:12345678@192.168.2.91:3306/milvus
  preload_collection:
  auto_flush_interval: 1
storage_config:
  primary_path: /var/lib/milvus
  secondary_path:
metric_config:
  enable_monitor: false
  address: 127.0.0.1
  port: 9091
cache_config:
  cpu_cache_capacity: 4
  insert_buffer_size: 1
  cache_insert_data: false
engine_config:
  use_blas_threshold: 1100
  gpu_search_threshold: 1000
gpu_resource_config:
  enable: false
  cache_capacity: 1
  search_resources:
    - gpu0
  build_index_resources:
    - gpu0
tracing_config:
  json_config_path:
wal_config:
  enable: true
  recovery_error_ignore: true
  buffer_size: 256
  wal_path: /var/lib/milvus/wal
`
cluster_readonly node:
`
version: 0.3
server_config:
  address: 0.0.0.0
  port: 19530
  deploy_mode: cluster_readonly
  time_zone: UTC+8
  web_port: 19121
db_config:
  backend_url: mysql://test:12345678@192.168.2.91:3306/milvus
  preload_collection:
  auto_flush_interval: 1
storage_config:
  primary_path: /var/lib/milvus
  secondary_path:
metric_config:
  enable_monitor: false
  address: 127.0.0.1
  port: 9091
cache_config:
  cpu_cache_capacity: 4
  insert_buffer_size: 1
  cache_insert_data: false
engine_config:
  use_blas_threshold: 1100
  gpu_search_threshold: 1000
gpu_resource_config:
  enable: false
  cache_capacity: 1
  search_resources:
    - gpu0
  build_index_resources:
    - gpu0
tracing_config:
  json_config_path:
wal_config:
  enable: true
  recovery_error_ignore: true
  buffer_size: 256
  wal_path: /var/lib/milvus/wal
`
I follow the instruction here to start milvus server: https://www.milvus.io/docs/v0.8.0/guides/get_started/install_milvus/cpu_milvus_docker.md
`docker run -d --name milvus_cpu \
-p 19530:19530 \
-p 19121:19121 \
-p 9091:9091 \
-v /home/$USER/milvus/db:/var/lib/milvus/db \
-v /home/$USER/milvus/conf:/var/lib/milvus/conf \
-v /home/$USER/milvus/logs:/var/lib/milvus/logs \
-v /home/$USER/milvus/wal:/var/lib/milvus/wal \
milvusdb/milvus:0.8.0-cpu-d041520-464400`

**Comment by BossZou** [comment]
@Vergissmeinicht , May you provide the docker logs for read node ?

**Comment by Vergissmeinicht** [comment]
> @Vergissmeinicht , May you provide the docker logs for read node ?

Here's the docker logs:
Welcome to use Milvus!
Milvus Release version: v0.8.0, built at 2020-04-14 15:32.48, with OpenBLAS library.
You are using Milvus CPU edition
Last commit id: 464400767f8723b9867755c63ab07f7cfe2ecb29

Loading configuration from: ../conf/server_config.yaml
Initializing log config from: ../conf/log_config.conf
Milvus server started successfully!

It seems that it's ok. And here's the error log:
2020-05-14 14:50:38,420 | ERROR | default | [ENGINE] Collection file doesn't exist: /var/lib/milvus/db/tables/example_collection_/1589438953180853000/1589438954182054000 in path: /var/lib/milvus/db for collection: example_collection_
2020-05-14 14:50:38,420 | ERROR | default | [SERVER] [search][0] Query fail: Collection file doesn't exist: /var/lib/milvus/db/tables/example_collection_/1589438953180853000/1589438954182054000
2020-05-14 14:50:38,420 | ERROR | default | [SERVER] Request failed with code: Error: Collection file doesn't exist: /var/lib/milvus/db/tables/example_collection_/1589438953180853000/1589438954182054000

**Comment by Vergissmeinicht** [comment]
It turns out that I didn't point the db path to a shared directory. My distributed deployment works when I fix this problem.
