### ISSUE TITLE
[Enhancement]: Open up topk limit param in config

### ISSUE THREAD

**Issue by filip-halt** [milvus-io/milvus#23230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

The ability to modify the top-k limit. I understand that this is already implemented but just missing a config param. 

### Why is this needed?

Different users need the ability to scale the total search result

**Comment by PiercarloSlavazza** [comment]
Hi @xiaofan-luan, I am using Milvus 2.3.3, I checked https://raw.githubusercontent.com/milvus-io/milvus/v2.3.3/configs/milvus.yaml but I do not see `common.topKLimit` (nor in the 2.4.*): is it still supported even if not explicitely listed?

**Comment by xiaofan-luan** [comment]
I thought this is recently add in milvus 2.4.

**Comment by PiercarloSlavazza** [comment]
Hm, by looking at the code, I think it might be `quotaAndLimits.limits.topKLimit` - makes sense?

**Comment by PiercarloSlavazza** [comment]
Nope, I think I can confirm `common.topKLimit` because, when set, I see in the logs:

> milvus-standalone  | [2024/04/12 19:23:03.157 +00:00] [INFO] [config/manager.go:351] ["receive update event"] [event="{\"EventSource\":\"FileSource\",\"EventType\":\"CREATE\",\"Key\":\"commontopklimit\",\"Value\":\"96000\",\"HasUpdated\":false}"]
> milvus-standalone  | [2024/04/12 19:23:03.157 +00:00] [INFO] [config/manager.go:351] ["receive update event"] [event="{\"EventSource\":\"FileSource\",\"EventType\":\"CREATE\",\"Key\":\"common.topklimit\",\"Value\":\"96000\",\"HasUpdated\":false}"]

**Comment by PiercarloSlavazza** [comment]
Sorry - I have to rectify again: it seems that Milvus print that statements for every and each config added…

**Comment by xiaofan-luan** [comment]
/assign @aoiasd 
please help on investigating that

**Comment by PiercarloSlavazza** [comment]
Hi, no need for further help, thank you - I confirm that eventually `common.topKLimit` was the right one (behaviour verified).
