### ISSUE TITLE
[Bug]: if there are many partitions in one collection, get recovery info happens too frequently

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#23231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/83447078/229921743-4bb32164-a98f-40f4-a85f-58aab7d4fe49.png">

I thought the log is just too frequent to the datacoord too.
May be we should pull the target in batch?

**Comment by weiliu1031** [comment]
cause we will call get recovery info for each partition, for collection which have lots of partition, get recovery info will execute  many times and can be very slow. 

fix: we should make get recovery info a collection level api, to reduce the frequency to call.

**Comment by xiaofan-luan** [comment]
> cause we will call get recovery info for each partition, for collection which have lots of partition, get recovery info will execute many times and can be very slow.
> 
> fix: we should make get recovery info a collection level api, to reduce the frequency to call.

Agreed, exactly what I am thinking

**Comment by weiliu1031** [comment]
already fixed
