### ISSUE TITLE
[Bug]: Slack invitation link expired

### ISSUE THREAD

**Issue by thinh2** [milvus-io/milvus#23243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The Slack attaching to the README.md document is expired

**Comment by yanliang567** [comment]
@thinh2 thank you for the issue. We will fix it soon. here is the correct one: milvusio.slack.com

/assign @zhuwenxing 
/unassign

**Comment by thinh2** [comment]
Hi @yanliang567, it looks like the link above does not allow new user like me to sign up. Could you please check the slack setting?

**Comment by zhuwenxing** [comment]
@thinh2 
You can also visit https://milvus.io and join Slack via the link on the top right.
![image](https://user-images.githubusercontent.com/12268675/230528471-14f5f851-03a9-4aaf-b0e9-79b0249a4b1d.png)


This link on the website is the same as the link in README.

**Comment by thinh2** [comment]
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/26578143/230710350-94ef5dfa-7bda-411f-a4a8-7dee9b859cba.png">

I tried to click Join Slack button, but it does not prompt milvus's slack workspace. The step to produce it is:

1. Click Join Slack button
2. Enter one random email which haven't joined milvus's slack.
3. Enter passcode received from the email
4. The website redirected to the page attached below.
Could you please check again? Thank you !

**Comment by yanliang567** [comment]
@fzliu could you please take a look at this?
/assign @fzliu

**Comment by zhuwenxing** [comment]
@thinh2 you can use this invite link https://milvusio.slack.com/join/shared_invite/zt-1slimkif6-8uWK0XPL8adve6vSD4jSwg
We will update it in readme soon.

**Comment by thinh2** [comment]
Thanks @zhuwenxing, I can join Milvus's Slack now. Should I close the ticket or leave it open until the readme is updated?
