### ISSUE TITLE
[Bug]: query node oom killed due to inaccurate memory prediction based on container limit

### ISSUE THREAD

**Issue by MrPresent-Han** [milvus-io/milvus#23262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.5
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka): Kafka   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: 
- image: v2.2.0-20230402-6d5ec9c-28175ab
```

### Current Behavior

set pod request memory with 2g and limit 9g
query node crashed and restart
client sdk got load failed response and raise an error

### Expected Behavior

query node keeps stable and report failure right away when memory is not sufficient

### Steps To Reproduce

```markdown
create a collection
build autoindex index
insert 25m data
load collection and error raised after a few minutes
```

### Milvus Log

[2023-04-02 18:33:44,908] [   DEBUG] - Start build index for last file (milvus_benchmark.runners.locust:318)
2[2023-04-02 18:33:44,908] [    INFO] - Building index start, collection_name: sift_25m_128_l2, index_type: AUTOINDEX, metric_type: L2 (milvus_benchmark.client:302)
3[2023-04-02 18:33:44,908] [   DEBUG] - collection: sift_25m_128_l2 Index params: {'index_type': 'AUTOINDEX', 'metric_type': 'L2', 'params': {}} (milvus_benchmark.client:311)
4[2023-04-02 19:06:06,741] [   DEBUG] - Building index done, collection_name: sift_25m_128_l2, response: Status(code=0, message=) (milvus_benchmark.client:313)
5[2023-04-02 19:06:06,744] [   DEBUG] - Milvus create_index run in 1941.8366s (milvus_benchmark.client:57)
6[2023-04-02 19:06:06,744] [   DEBUG] - {'flush_time': 2.0255, 'build_time': 1941.8366} (milvus_benchmark.runners.locust:322)
7[2023-04-02 19:06:06,746] [   DEBUG] - Row count: 25000000 in collection: <sift_25m_128_l2> (milvus_benchmark.client:528)
8[2023-04-02 19:06:06,746] [    INFO] - 25000000 (milvus_benchmark.runners.locust:323)
9[2023-04-02 19:06:06,747] [    INFO] - Start load collection (milvus_benchmark.runners.locust:324)
10[2023-04-02 19:08:40,487] [ WARNING] - [93m[get_loading_progress] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, unavailable>[0m (pymilvus.decorators:71)
11[2023-04-02 19:08:40,763] [ WARNING] - [93m[get_loading_progress] retry:5, cost: 0.81s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, unavailable>[0m (pymilvus.decorators:71)
12[2023-04-02 19:08:41,576] [ WARNING] - [93m[get_loading_progress] retry:6, cost: 2.43s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>[0m (pymilvus.decorators:71)
13[2023-04-02 19:08:44,009] [ WARNING] - [93m[get_loading_progress] retry:7, cost: 7.29s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>[0m (pymilvus.decorators:71)
14[2023-04-02 19:08:51,302] [ WARNING] - [93m[get_loading_progress] retry:8, cost: 21.87s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>[0m (pymilvus.decorators:71)
15[2023-04-02 19:09:13,175] [ WARNING] - [93m[get_loading_progress] retry:9, cost: 60.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, unavailable>[0m (pymilvus.decorators:71)
16[2023-04-02 19:10:13,182] [   ERROR] - RPC error: [get_loading_progress], <MilvusException: (code=1, message=collection 440521673462515474 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2023-04-02 19:08:40.226804', 'RPC error': '2023-04-02 19:10:13.182455'}> (pymilvus.decorators:108)
17[2023-04-02 19:10:13,184] [   ERROR] - RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection 440521673462515474 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2023-04-02 19:06:06.771396', 'RPC error': '2023-04-02 19:10:13.184428'}> (pymilvus.decorators:108)
18[2023-04-02 19:10:13,184] [   ERROR] - RPC error: [load_collection], <MilvusException: (code=1, message=collection 440521673462515474 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2023-04-02 19:06:06.747123', 'RPC error': '2023-04-02 19:10:13.184549'}> (pymilvus.decorators:108)
19[2023-04-02 19:10:13,184] [   ERROR] - <MilvusException: (code=1, message=collection 440521673462515474 has not been loaded to memory or load failed)> (milvus_benchmark.main:120)
20[2023-04-02 19:10:13,187] [   ERROR] - Traceback (most recent call last):

**Comment by MrPresent-Han** [comment]
This error is caused by the fact that the prediction made on the node is based on the limit memory of one pod, which is an unavailable value in some cases. So when the gap between request memory and limit memory is very big, it's rather prone to have a wrong estimation of the memory consumed in the process of loading segment and lead to oom killed

**Comment by xiaofan-luan** [comment]
keep it
