### ISSUE TITLE
CPU run unitest failed

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#2327]
**Describe the bug**
http://internal.zilliz.com:18080/jenkins/blue/organizations/jenkins/milvus-ci/detail/PR-2305/13/pipeline/189

```

[2020-05-13T08:44:18.854Z] [ RUN      ] DBTest.SEARCH_TEST

[2020-05-13T09:14:03.429Z] Sending interrupt signal to process

[2020-05-13T09:14:03.430Z] Killing processes

[2020-05-13T09:14:04.516Z] kill finished with exit code 0
```
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
fixed by pr2323
