### ISSUE TITLE
[Bug]: Memory is not freed after release a collection with index IVF_SQ8

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#23278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.5
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Create a collection with index IVF_SQ8, and insert 2M vectors with 512 dim. Load the collection then release. Memory usage keeps high, memory is not freed after a long time(several minutes).

### Expected Behavior

Memory usage should decrease after a short while.

### Steps To Reproduce

```markdown
1. wget https://github.com/milvus-io/milvus/releases/download/v2.2.5/milvus-cluster-docker-compose.yml -O docker-compose.yml

2. start milvus cluster by command: docker-compose up -d

3. run this script:

import random
import time

from pymilvus import (
    connections,
    FieldSchema, CollectionSchema, DataType,
    Collection,
    utility,
)

_HOST = '127.0.0.1'
_PORT = '19530'

if __name__ == '__main__':
    connections.connect(host=_HOST, port=_PORT)

    dim = 512
    collection_name = "demo"

    if utility.has_collection(collection_name):
        utility.drop_collection(collection_name)

    field1 = FieldSchema(name="id", dtype=DataType.INT64, is_primary=True, auto_id=True)
    field2 = FieldSchema(name="embedding", dtype=DataType.FLOAT_VECTOR, dim=dim)
    schema = CollectionSchema(fields=[field1, field2])
    collection = Collection(name=collection_name, schema=schema)
    print("\ncollection created:", collection_name)

    index_param = {
        "index_type": "IVF_SQ8",
        "params": {"nlist": 256},
        "metric_type": "L2"}
    collection.create_index("embedding", index_param)

    num = 10000
    data = [
        [[random.random() for _ in range(dim)] for _ in range(num)],
    ]
    for k in range(200):
        print("insert", k)
        collection.insert(data)

    collection.flush()
    print("Collection row count:", collection.num_entities)

    collection = Collection(name=collection_name)
    start = time.time()
    collection.load()
    end = time.time()
    print("Loaded collection, time cost:", (end-start), "s")

    time.sleep(1)

    collection = Collection(name=collection_name)
    start = time.time()
    collection.release()
    end = time.time()
    print("Released collection, time cost:", (end - start), "s")
```
4. check the memory usage by command:  docker stats -a

The memory usage of querynode is ~=50MB at begin. And increased to 1.2GB after load(), back to 900MB after release(). The memory is not freed even after several minutes.

5. call load() and release() again. The memory usage of querynode increased to 1.7GB after load(), back to 1.4GB after release().  The memory is not freed even after several minutes.

6. call load() and release() again. The memory usage of querynode increased to 1.9GB after load(), back to 1.6GB after release().  The memory is not freed even after several minutes.

7. if do a loop to load->release->load->release ....., you will see the memory usage is higher and higher.

**Comment by alyosama** [comment]
@xiaofan-luan  any updates regarding this bug ?

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan any updates regarding this bug ?

From our current profiling, it's but a leakage but simply because jemalloc maintains the memory as cache.
Add malloc_trim(0) see it works better

**Comment by xiaofan-luan** [comment]
have a pr on it, see it works

**Comment by alyosama** [comment]
@xiaofan-luan would you mind if you point me to the fix branch or the pr ?

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan would you mind if you point me to the fix branch or the pr ?

still work on it, milvus use jemalloc while jemalloc doesn't support malloc_trim(0), so need to figure out a new way to tune jemalloc

**Comment by xiaofan-luan** [comment]
keep it

**Comment by xiaofan-luan** [comment]
@xige-16 
Any progress on it?

**Comment by yhmo** [comment]
I am not working on this issue.
/assign @xige-16

**Comment by xige-16** [comment]
> @xiaofan-luan would you mind if you point me to the fix branch or the pr ?

Try exporting MALLOC_CONF=background_thread:true before starting Milvus. This way, the memory cached by jemalloc will be returned to the OS faster.

**Comment by xiaofan-luan** [comment]
> > @xiaofan-luan would you mind if you point me to the fix branch or the pr ?
> 
> Try exporting MALLOC_CONF=background_thread:true before starting Milvus. This way, the memory cached by jemalloc will be returned to the OS faster.

is this by default setup in our image?

**Comment by xige-16** [comment]
> > > @xiaofan-luan would you mind if you point me to the fix branch or the pr ?
> > 
> > 
> > Try exporting MALLOC_CONF=background_thread:true before starting Milvus. This way, the memory cached by jemalloc will be returned to the OS faster.
> 
> is this by default setup in our image?

No, it can be set through environment variables in k8s.

**Comment by xige-16** [comment]
> > > @xiaofan-luan would you mind if you point me to the fix branch or the pr ?
> > 
> > 
> > Try exporting MALLOC_CONF=background_thread:true before starting Milvus. This way, the memory cached by jemalloc will be returned to the OS faster.
> 
> is this by default setup in our image?

Default setup in the image is a good way. I'll fix it.

**Comment by xige-16** [comment]
pr: https://github.com/milvus-io/milvus/pull/26353
