### ISSUE TITLE
Connection stats display

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#2328]
**Is your feature request related to a problem? Please describe.**
Just like redis server, clients can get all connection stats by `info` or `client list`:
```
redis 127.0.0.1:6379> client list
addr=127.0.0.1:52555 fd=5 name= age=855 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=client
addr=127.0.0.1:52787 fd=6 name= age=6 idle=5 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=ping
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by BossZou** [comment]
This may be considered in the future.

**Comment by BossZou** [comment]
Backlog ...

**Comment by yhmo** [comment]
Will be considered in v2.x
