### ISSUE TITLE
[Bug]: test_search_partition_deleted failed due to loading collection times out

### ISSUE THREAD

**Issue by longjiquan** [milvus-io/milvus#23295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-23282/1/pipeline

**Comment by xiaofan-luan** [comment]
is this still a issue?

**Comment by longjiquan** [comment]
debug log lost and didn't meet this any more. close this.
