### ISSUE TITLE
[Bug]: Investigate the Cpu Usage on small instance when the system is idle

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#23309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://github.com/milvus-io/milvus/issues/22571 
https://github.com/milvus-io/milvus/issues/17942

We will see many similar issues that said cpu is high after data insertion.

I have some wild guess about it, but we need to verify on how to reproduce:
1. Single collection with enough data -> Create a 2c8G Standalone and insert 8GB memory into it, do some search and leave it for at least 1 day, see the data growth and cpu usage(should be less than 0.5 core)
2. Multi collection -> Create a 2c8G Standalone  and create 100 collections, see what will happen
3. Multi collection - >Create a 2c8G Standalone  and create 100 collections, each collection insert 10000 entities and trigger index build

### Expected Behavior

CPU usage is below 1 CPU

**Comment by yanliang567** [comment]
/assign @elstic 
could you please follow up this issue and test addition accordingly.

**Comment by elstic** [comment]
> /assign @elstic could you please follow up this issue and test addition accordingly.

ok, let me look at the problem .

**Comment by elonzh** [comment]
😒I just deployed a standalone server with several collections... 

![image](https://user-images.githubusercontent.com/8749411/231924363-3ac42922-83fd-4e6b-ad7a-5cf6102cd324.png)

![image](https://user-images.githubusercontent.com/8749411/231924192-01103ec1-0465-4e5e-a750-3422957f3b37.png)

**Comment by elstic** [comment]
1) After 3h of testing, the cpu resource usage was reduced to less than 0.5, using about 0.05c.
![image](https://user-images.githubusercontent.com/48523564/232088262-416b36b6-2536-4c62-81dd-22b0dcb30943.png)


2)  create 100 collections ,cpu usage 0.15, mem usage : 482m
![image](https://user-images.githubusercontent.com/48523564/231996389-ea5c97f7-47b4-484b-bc5b-fd06ac8c81fa.png)
![image](https://user-images.githubusercontent.com/48523564/231996529-9f9ad30f-d93f-42b7-8cec-6560e2cf912a.png)


3) Conclusion: cpu use below 0.5c
![image](https://user-images.githubusercontent.com/48523564/232016882-dcf01167-f66d-436c-b460-b5dd824296ef.png)

![image](https://user-images.githubusercontent.com/48523564/232016766-7f621391-5447-423f-b94b-9ec09353281a.png)

**Comment by xiaofan-luan** [comment]
> > 1. After 3h of testing, the cpu resource usage was reduced to less than 0.5, using about 0.05c.
> >    ![image](https://user-images.githubusercontent.com/48523564/232088262-416b36b6-2536-4c62-81dd-22b0dcb30943.png)
> > 2. create 100 collections ,cpu usage 0.15, mem usage : 482m
> >    ![image](https://user-images.githubusercontent.com/48523564/231996389-ea5c97f7-47b4-484b-bc5b-fd06ac8c81fa.png)
> >    ![image](https://user-images.githubusercontent.com/48523564/231996529-9f9ad30f-d93f-42b7-8cec-6560e2cf912a.png)
> > 3. Conclusion: cpu use below 0.5c
> >    ![image](https://user-images.githubusercontent.com/48523564/232016882-dcf01167-f66d-436c-b460-b5dd824296ef.png)
> > 
> > ![image](https://user-images.githubusercontent.com/48523564/232016766-7f621391-5447-423f-b94b-9ec09353281a.png)
> > How many collections are there in your test， could you add a few data entities into each collection also

**Comment by elonzh** [comment]
I have no idea about the increase in CPU usage. I stopped the server when received the alert.

But I am sure there are no requests when this issue happens because it is a test server for evaluation.

**Comment by elstic** [comment]
> > > 1. After 3h of testing, the cpu resource usage was reduced to less than 0.5, using about 0.05c.
> > >    ![image](https://user-images.githubusercontent.com/48523564/232088262-416b36b6-2536-4c62-81dd-22b0dcb30943.png)
> > > 2. create 100 collections ,cpu usage 0.15, mem usage : 482m
> > >    ![image](https://user-images.githubusercontent.com/48523564/231996389-ea5c97f7-47b4-484b-bc5b-fd06ac8c81fa.png)
> > >    ![image](https://user-images.githubusercontent.com/48523564/231996529-9f9ad30f-d93f-42b7-8cec-6560e2cf912a.png)
> > > 3. Conclusion: cpu use below 0.5c
> > >    ![image](https://user-images.githubusercontent.com/48523564/232016882-dcf01167-f66d-436c-b460-b5dd824296ef.png)
> > > 
> > > ![image](https://user-images.githubusercontent.com/48523564/232016766-7f621391-5447-423f-b94b-9ec09353281a.png)
> > > How many collections are there in your test， could you add a few data entities into each collection also

@xiaofan-luan 
My three tests were set up as you would expect, the second test created 100 collections and then did nothing.
The third test creates 100 collections and adds 10,000 pieces of 128-dimensional data to each collection, and creates an index.

**Comment by xiaofan-luan** [comment]
> I have no idea about the increase in CPU usage. I stopped the server when received the alert.
> 
> But I am sure there are no requests when this issue happens because it is a test server for evaluation.

hi @elonzh , I know what's going on.
It will be fixed in 2.2.6, thanks for your feedback.

**Comment by elonzh** [comment]
The container log may offer some help.

![image](https://user-images.githubusercontent.com/8749411/232190396-9d012bc8-cb69-44cc-bb1f-28092e06d482.png)

![image](https://user-images.githubusercontent.com/8749411/232190364-f2da1bd7-12d6-4178-98bf-9fe12cfcb6cb.png)

https://wormhole.app/MvAn6#RRH8iE3nz6RqOppHGKaS4g

**Comment by elonzh** [comment]
@xiaofan-luan Will the fix be patched to v2.3? I am using `v2.3.0-beta` for Aliyun OSS provider support.

**Comment by xiaofan-luan** [comment]
it will be fix on 2.2.6

**Comment by xiaofan-luan** [comment]
don't use 2.3 into production yet, we are still working on fixes

**Comment by elonzh** [comment]
This is insane! Upgrade to 2.2.6 is not working even though I cleared all data.

![image](https://user-images.githubusercontent.com/8749411/233823662-1e42c8d9-6c7c-4c80-9a16-d4ca15519281.png)

![image](https://user-images.githubusercontent.com/8749411/233823752-13f2ece7-843c-4ed0-8620-20073d2bd19c.png)

**Comment by elonzh** [comment]
Seems it's rockmq issue. It creates some many goroutines.

![image](https://user-images.githubusercontent.com/8749411/233858854-a129ba63-92a7-46ad-ad8c-5a48f09dff10.png)

[pprof.milvus.samples.cpu.001.pb.gz](https://github.com/milvus-io/milvus/files/11304582/pprof.milvus.samples.cpu.001.pb.gz)

**Comment by xiaofan-luan** [comment]
> Seems it's rockmq issue. It creates some many goroutines.
> 
> ![image](https://user-images.githubusercontent.com/8749411/233858854-a129ba63-92a7-46ad-ad8c-5a48f09dff10.png)
> 
> [pprof.milvus.samples.cpu.001.pb.gz](https://github.com/milvus-io/milvus/files/11304582/pprof.milvus.samples.cpu.001.pb.gz)

What disk you are using? our QA team tried to reproduce on internal environment and get no clue. I tried with hundred collections but not help

**Comment by elonzh** [comment]
```apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: alicloud-disk-essd
  uid: 65d085b6-64c4-4526-9ee1-5755f04589d9
  resourceVersion: '1489528'
  creationTimestamp: '2020-10-23T03:00:37Z'
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"alicloud-disk-essd"},"parameters":{"type":"cloud_essd"},"provisioner":"diskplugin.csi.alibabacloud.com","reclaimPolicy":"Delete"}
allowVolumeExpansion: true
allowedTopologies: []
mountOptions: []
parameters:
  type: cloud_essd
provisioner: diskplugin.csi.alibabacloud.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

**Comment by xiaofan-luan** [comment]
how many collections, shards and partitions do you have/
essd should work perfectly

**Comment by xiaofan-luan** [comment]
and you don't change default time tick interval right?
There seems to be many time ticks in the system

**Comment by xiaofan-luan** [comment]
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/83447078/233866368-4ce8c786-40ae-41eb-97bb-75c5a75b0a45.png">
seems that most of the cpu is in the cgo call ,but that doesn't make too much sense too me unless there are many channels

**Comment by elonzh** [comment]
I changed the milvus config and reset the data, still not working.

```
extraConfigFiles:
  user.yaml: |+
    rocksmq:
      # The path where the message is stored in rocksmq
      lrucacheratio: 0.06 # rocksdb cache memory ratio
      rocksmqPageSize: 16777216 # default is 256 MB, 256 * 1024 * 1024 bytes, The size of each page of messages in rocksmq
      retentionTimeInMinutes: 1440 # default is 5 days, 5 * 24 * 60 minutes, The retention time of the message in rocksmq.
      retentionSizeInMB: 1024 # default is 8 GB, 8 * 1024 MB, The retention size of the message in rocksmq.
      compactionInterval: 86400 # 1 day, trigger rocksdb compaction every day to remove deleted data
    rootCoord:
      # changing this value will make the cluster unavailable
      dmlChannelNum: 4
    dataCoord:
      segment:
        maxSize: 128 # Maximum size of a segment in MB
        diskSegmentMaxSize: 256 # Maximun size of a segment in MB for collection which has Disk index
```

![image](https://user-images.githubusercontent.com/8749411/233990473-92a83c4b-8400-4d17-8431-2a85aaa418ed.png)

![image](https://user-images.githubusercontent.com/8749411/233990804-370ec35b-fc25-4e68-868a-6924355ead1b.png)

![image](https://user-images.githubusercontent.com/8749411/233990731-18cdbc03-cd1d-4591-a46b-67579a25b748.png)

**Comment by elonzh** [comment]
I am using Alicloud ACS kubernetes.

<html>
<body>


System Images : Alibaba Cloud Linux 3 (Soaring Falcon) | Kernel Version : 5.10.134-12.2.al8.x86_64
-- | --
Kubelet Version : v1.24.6-aliyun.1 | Kube-Proxy Version : v1.24.6-aliyun.1


</body>
</html>

**Comment by xiaofan-luan** [comment]
@elstic 
could we try to restart the standalone server after we insert enough data and keep the cluster for a while see if this is reproducible?

**Comment by xiaofan-luan** [comment]
this has to be happen with many collections.
For instance 100 collections, each collection insert 100k data

**Comment by elstic** [comment]
Deployment method:kuernetes Standalone

Deployed v2.2.6 instance, inserted 100,000 128-dimensional data into 85 collections, inserted 10,000 data into 120 collections, then upgraded to v2.2.9; waited 2 days, cpu usage went up from 1.5c two days ago to 2.5c now

![image](https://github.com/milvus-io/milvus/assets/48523564/7d375402-d34a-426b-97bf-7236d115eba3)


server:
```
fouramf-xww99-15-5808-etcd-0                                      1/1     Running     0              2d10h
fouramf-xww99-15-5808-milvus-standalone-64df46f558-dlmq2          1/1     Running     1 (39h ago)    41h
fouramf-xww99-15-5808-minio-f7f566454-pj6sh                       1/1     Running     0              2d10h
```

@xiaofan-luan 
Instance still remains, please let the development troubleshoot the issue

**Comment by aoiasd** [comment]
Rocksdb cpu usage will increase with files num. When system idle, milvus keeps send ttmsg to rocksmq, and cpu usage will increase with data in rocksmq. Till rocksmq start retention, after 3 days or large than 8G default. So set a smaller retention time or retention size may help(rocksmq.retentionTimeInMinutes and rocksmq.retentionSizeInMB at milvus.config). 

We won't send ttmsg by message queue at master, so this question has been solved at master.

**Comment by xiaofan-luan** [comment]
> Rocksdb cpu usage will increase with files num. When system idle, milvus keeps send ttmsg to rocksmq, and cpu usage will increase with data in rocksmq. Till rocksmq start retention, after 3 days or large than 8G default. So set a smaller retention time or retention size may help(rocksmq.retentionTimeInMinutes and rocksmq.retentionSizeInMB at milvus.config).
> 
> We won't send ttmsg by message queue at master, so this question has been solved at master.

There will be still tt messages in dml channel, and this is already in 2.2.12.
And yes, this will be alleviated with the new implmentation

**Comment by xiaofan-luan** [comment]
Have too many collections/partiitons in may still cause  this problem. @elonzh if you can do more test on the newly comed 2.2.12 it would be really helpful

**Comment by yanliang567** [comment]
@elonzh v2.2.12 was released this week. please try to run your tests if convenient. thanks.
