### ISSUE TITLE
[Bug]: Disk usage grows very fast

### ISSUE THREAD

**Issue by clk1st** [milvus-io/milvus#23308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:version:2.2.4
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):milvus-sdk-java v2.2.3
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 8核/32G
- GPU: 无
- Others: 无
```

### Current Behavior

The disk takes up more than 100 G in one hour, and the logs in the /data/milvus/docker/containers/ directory grow rapidly. There are a large number of WARN level logs. I don’t know where there is a problem.

### Milvus Log

{"log":"{\"level\":\"WARN\",\"time\":\"2023/04/09 06:38:09.312 +00:00\",\"caller\":\"datanode/flow_graph_insert_buffer_node.go:687\",\"message\":\"failed to get segment statistics info\",\"segmentID\":440654511001151157,\"error\":\"error, there's no segment 440654511001151157\"}\n","stream":"stdout","time":"2023-04-09T06:38:09.312391496Z"}
{"log":"{\"level\":\"WARN\",\"time\":\"2023/04/09 06:38:09.312 +00:00\",\"caller\":\"datanode/flow_graph_insert_buffer_node.go:687\",\"message\":\"failed to get segment statistics info\",\"segmentID\":440654511001151157,\"error\":\"error, there's no segment 440654511001151157\"}\n","stream":"stdout","time":"2023-04-09T06:38:09.312394721Z"}
{"log":"{\"level\":\"WARN\",\"time\":\"2023/04/09 06:38:09.312 +00:00\",\"caller\":\"datanode/flow_graph_insert_buffer_node.go:687\",\"message\":\"failed to get segment statistics info\",\"segmentID\":440654511001151157,\"error\":\"error, there's no segment 440654511001151157\"}\n","stream":"stdout","time":"2023-04-09T06:38:09.312401793Z"}
{"log":"{\"level\":\"WARN\",\"time\":\"2023/04/09 06:38:09.312 +00:00\",\"caller\":\"datanode/flow_graph_insert_buffer_node.go:687\",\"message\":\"failed to get segment statistics info\",\"segmentID\":440654511001151157,\"error\":\"error, there's no segment 440654511001151157\"}\n","stream":"stdout","time":"2023-04-09T06:38:09.312412483Z"}
{"log":"{\"level\":\"WARN\",\"time\":\"2023/04/09 06:38:09.312 +00:00\",\"caller\":\"datanode/flow_graph_insert_buffer_node.go:687\",\"message\":\"failed to get segment statistics info\",\"segmentID\":440654511001151157,\"error\":\"error, there's no segment 440654511001151157\"}\n","stream":"stdout","time":"2023-04-09T06:38:09.312418962Z"}
{"log":"{\"level\":\"WARN\",\"time\":\"2023/04/09 06:38:09.312 +00:00\",\"caller\":\"datanode/flow_graph_insert_buffer_node.go:687\",\"message\":\"failed to get segment statistics info\",\"segmentID\":440654511001151157,\"error\":\"error, there's no segment 440654511001151157\"}\n","stream":"stdout","time":"2023-04-09T06:38:09.312422419Z"}
{"log":"{\"level\":\"WARN\",\"time\":\"2023/04/09 06:38:09.312 +00:00\",\"caller\":\"datanode/flow_graph_insert_buffer_node.go:687\",\"message\":\"failed to get segment statistics info\",\"segmentID\":440654511001151157,\"error\":\"error, there's no segment 440654511001151157\"}\n","stream":"stdout","time":"2023-04-09T06:38:09.312445758Z"}
{"log":"{\"level\":\"WARN\",\"time\":\"2023/04/09 06:38:09.312 +00:00\",\"caller\":\"datanode/flow_graph_insert_buffer_node.go:687\",\"message\":\"failed to get segment statistics info\",\"segmentID\":440654511001151157,\"error\":\"error, there's no segment 440654511001151157\"}\n","stream":"stdout","time":"2023-04-09T06:38:09.312452096Z"}
{"log":"{\"level\":\"WARN\",\"time\":\"2023/04/09 06:38:09.312 +00:00\",\"caller\":\"datanode/flow_graph_insert_buffer_node.go:687\",\"message\":\"failed to get segment statistics info\",\"segmentID\":440654511001151157,\"error\":\"error, there's no segment 440654511001151157\"}\n","stream":"stdout","time":"2023-04-09T06:38:09.312455296Z"}
{"log":"{\"level\":\"WARN\",\"time\":\"2023/04/09 06:38:09.312 +00:00\",\"caller\":\"datanode/flow_graph_insert_buffer_node.go:687\",\"message\":\"failed to get segment statistics info\",\"segmentID\":440654511001151157,\"error\":\"error, there's no segment 440654511001151157\"}\n","stream":"stdout","time":"2023-04-09T06:38:09.312458657Z"}
{"log":"{\"level\":\"WARN\",\"time\":\"2023/04/09 06:38:09.312 +00:00\",\"caller\":\"datanode/flow_graph_insert_buffer_node.go:687\",\"message\":\"failed to get segment statistics info\",\"segmentID\":440654511001151157,\"error\":\"error, there's no segment 440654511001151157\"}\n","stream":"stdout","time":"2023-04-09T06:38:09.31246215Z"}
{"log":"{\"level\":\"WARN\",\"time\":\"2023/04/09 06:38:09.312 +00:00\",\"caller\":\"datanode/flow_graph_insert_buffer_node.go:687\",\"message\":\"failed to get segment statistics info\",\"segmentID\":440654511001151157,\"error\":\"error, there's no segment 440654511001151157\"}\n","stream":"stdout","time":"2023-04-09T06:38:09.312484317Z"}
{"log":"{\"level\":\"WARN\",\"time\":\"2023/04/09 06:38:09.312 +00:00\",\"caller\":\"datanode/flow_graph_insert_buffer_node.go:687\",\"message\":\"failed to get segment statistics info\",\"segmentID\":440654511001151157,\"error\":\"error, there's no segment 440654511001151157\"}\n","stream":"stdout","time":"2023-04-09T06:38:09.312490216Z"}
{"log":"{\"level\":\"WARN\",\"time\":\"2023/04/09 06:38:09.312 +00:00\",\"caller\":\"datanode/flow_graph_insert_buffer_node.go:687\",\"message\":\"failed to get segment statistics info\",\"segmentID\":440654511001151157,\"error\":\"error, there's no segment 440654511001151157\"}\n","stream":"stdout","time":"2023-04-09T06:38:09.312493637Z"}

**Comment by xiaofan-luan** [comment]
@clk1st 
Thanks for the feedback. It seems you run into a issue at 2.2.4, could you upgrade to 2.2.5 see if there is still the error meesage there?

**Comment by clk1st** [comment]
> 



> @clk1st Thanks for the feedback. It seems you run into a issue at 2.2.4, could you upgrade to 2.2.5 see if there is still the error meesage there?

Does upgrading to 2.2.5 require downtime and data migration? Deployed using docker-compose without using k8s

**Comment by xiaofan-luan** [comment]
it requires a few minutes down time, but definitely no data migration.

**Comment by yanliang567** [comment]
/assign @clk1st 
could you please check that?

**Comment by xiaofan-luan** [comment]
it's actually fixed by
https://github.com/milvus-io/milvus/issues/22976

**Comment by xiaofan-luan** [comment]
restart will help for now.

**Comment by elonzh** [comment]
What data does Milvus need to use disk to store? Only logs? I have the same issue on `v2.3.0-beta`.

**Comment by xiaofan-luan** [comment]
it's actually the WAL if you deploy a standalone, one thing you could improve is to decrease the default shard numbers. 

Change rootCoord.dmlChannelNum to 32 or 16 could probably help you to reduce your extra data size. Try it and see if it works.

If you can offer the local disk size distribution, we can check if there are anything else we can do to reduce data size.

**Comment by xiaofan-luan** [comment]
> What data does Milvus need to use disk to store? Only logs? I have the same issue on `v2.3.0-beta`.

Hi Elonzh, I know you have some bad experience while you test it. feel free to send me email @ xiaofan.luan@zilliz.com and I can help with all issues. 
Let's work together to make milvus better
