### ISSUE TITLE
[Doc Bug]: There are some problems with the two documents here

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#23327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

There are some problems with the two documents here:
1. https://milvus.io/docs/upgrade.md#Step-3-Check-the-image-tag, the Milvus version is not the latest
2. https://github.com/milvus-io/pymilvus,
`Documentation is available online: https://milvus.io/api-reference/pymilvus/v2.2.3/About.md`, while the link is broken.

**Comment by yanliang567** [comment]
@del-zhenwu thanks for the issue. 

/assign @AnthonyTsu1984 
/unassign

**Comment by AnthonyTsu1984** [comment]
Thanks for your issue. The page you've mentioned is already deprecated and will be removed in a few days. 

For the latest guide, please refer to 

- For the upgrade of Milvus cluster, see [https://milvus.io/docs/upgrade_milvus_cluster-operator.md](https://milvus.io/docs/upgrade_milvus_cluster-operator.md).
- For the upgrade of Milvus standalone, see [https://milvus.io/docs/upgrade_milvus_standalone-operator.md](https://milvus.io/docs/upgrade_milvus_standalone-operator.md).

Thanks again for the issue.
