### ISSUE TITLE
[Bug]: Standalone cluster wrong logic during rollingupdate

### ISSUE THREAD

**Issue by wayblink** [milvus-io/milvus#23326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:hotfix-2.2.5
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Standalone cluster enabled active-standby create multiple sessions in etcd

**Comment by xiaofan-luan** [comment]
probably add some integrated test on standalone.
Make sure the master/slave switch works smoothly

**Comment by wayblink** [comment]
#21623 To add integration tests for active-standby logic. Standalone integration test might be a little complicated, will add it later.
