### ISSUE TITLE
[Bug]: master branch, milvus server side monitoring is not continuous

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#23341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230410-03a4f60b
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

 Milvus individual components Memory usage monitoring is discontinuous.

Current Monitoring ： 
![image](https://user-images.githubusercontent.com/48523564/231046454-644f994a-3399-400b-8c18-b5b55cc48eeb.png)

Expected：
![image](https://user-images.githubusercontent.com/48523564/231046622-ef074278-6e06-448d-b5b9-2658504ababa.png)

**Comment by LoveEachDay** [comment]
In recent version, we've added knowhere metrics for `/metrics` endpoint. For now there's an error when fetching metrics:
```
An error has occurred while serving metrics:

text format parsing error in line 1: invalid metric name
```
@cydrain We'd ignore metrics returned from `CRegistry`.

**Comment by elstic** [comment]
This issue has been verified and fixed .
