### ISSUE TITLE
[Bug]: modify parameter log.file.rootPath in milvus.yaml, not working.

### ISSUE THREAD

**Issue by SendTextLi** [milvus-io/milvus#23355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): kafka   
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.1.3
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 8 * 40core * 512G
- GPU: /
- Others: /
```

### Current Behavior

when I use helm-milvus package milvus-3.3.1.tgz to deploy my milvus, which can not modify log.file.rootPath in milvus.yaml，in order to export milvus's pod logs to my local disk directory, whose route is "/home/finance/Logs/mw-milvus-even". So I upgrade my helm package as  milvus-3.3.6.tgz, and modify the paramter log.file.rootPath in milvus/values.yaml file like below:
extraConfigFiles:
  user.yaml: |+
    #    For example enable rest http for milvus proxy
    #    proxy:
    #      http:
    #        enabled: true
    log:
      file:
        rootPath: "/home/finance/Logs/mw-milvus-even"

And config param log.persistence.mountPath as "/home/finance/Logs/mw-milvus-even", 
log:
  level: "debug"
  file:
    maxSize: 300    # MB
    maxAge: 10    # day
    maxBackups: 20
  format: "text"    # text/json

  persistence:
    mountPath: "/home/finance/Logs/mw-milvus-even"
    # mountPath: "/milvus/logs"
    ## If true, create/use a Persistent Volume Claim
    ## If false, use emptyDir
    ##
    enabled: false
    annotations:
      helm.sh/resource-policy: keep
    persistentVolumeClaim:
      existingClaim: ""
      ## Milvus Logs Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.
      ## ReadWriteMany access mode required for milvus cluster.
      ##
      storageClass:
      accessModes: ReadWriteMany
      size: 100Gi
      subPath: ""

After that, I upgrade my milvus cluster by using command "helm upgrade milvus-even milvus -f ./milvus/values.yaml".

### Expected Behavior

I wanna export milvus pods' logs to my local directory "/home/finance/Logs/mw-milvus-even", whose authority is "777".
I can see the parmater log.file.rootPath has changed in milvus.yaml, because I enter the pod's containter:
[root@kube-worker-61 ~]# docker exec -it f42b5d17c3aabad9feb7b22a1aacc1e8200b79fbb28d3f1f6e1c77ab3eceebba /bin/bash
root@milvus-even-proxy-7df8c8b46c-q2p7k:/milvus# ll
total 4
drwxr-xr-x 1 root root   71 Apr 11 08:00 ./
drwxr-xr-x 1 root root   59 Apr 11 08:00 ../
drwxr-xr-x 2 root root   28 Nov 18 13:29 bin/
drwxr-xr-x 1 root root   78 Apr 11 08:00 configs/
drwxr-xr-x 2 root root 4096 Nov 18 13:29 lib/
-rw-r--r-- 1 root root    0 Apr 11 08:00 myeasylog.log
drwxrwxrwx 2 root root   38 Apr 11 08:00 tools/
root@milvus-even-proxy-7df8c8b46c-q2p7k:/milvus# cd configs/
root@milvus-even-proxy-7df8c8b46c-q2p7k:/milvus/configs# ll
total 72
drwxr-xr-x 1 root root    78 Apr 11 08:00 ./
drwxr-xr-x 1 root root    71 Apr 11 08:00 ../
-rw-r--r-- 1 root root   106 Nov 18 13:22 OWNERS
drwxr-xr-x 2 root root    31 Nov 18 13:22 advanced/
drwxr-xr-x 2 root root   196 Nov 18 13:22 cert/
-rw-r--r-- 1 root root 12957 Nov 18 13:22 config.go
-rw-r--r-- 1 root root  4985 Nov 18 13:22 config_test.go
-rw-r--r-- 1 root root  8562 Apr 11 08:00 default.yaml
-rw-r--r-- 1 root root   883 Nov 18 13:22 easylogging.yaml
-rw-r--r-- 1 root root 11717 Nov 18 13:22 embedded-milvus.yaml
-rw-r--r-- 1 root root     0 Nov 18 13:22 hook.yaml
-rw-r--r-- 1 root root  2587 Nov 18 13:22 milvus.example.toml
-rw-r--r-- 1 root root  6413 Apr 11 08:00 milvus.yaml
-rw-r--r-- 1 root root   161 Apr 11 08:00 user.yaml
root@milvus-even-proxy-7df8c8b46c-q2p7k:/milvus/configs# cat user.yaml
#    For example enable rest http for milvus proxy
#    proxy:
#      http:
#        enabled: true
log:
  file:
    rootPath: "/home/finance/Logs/mw-milvus-even"root@milvus-even-proxy-7df8c8b46c-q2p7k:/milvus/configs#
root@milvus-even-proxy-7df8c8b46c-q2p7k:/milvus/configs#cat milvus.yaml
...
log:
  file:
    maxAge: 10
    maxBackups: 20
    maxSize: 300
    rootPath: /home/finance/Logs/mw-milvus-even
  format: text
  level: debug
...

But no logs exported to my local directory "/home/finance/Logs/mw-milvus-even" in any cluster mechine：
[root@kube-master-54 Logs]# cd mw-milvus-even/
[root@kube-master-54 mw-milvus-even]#
[root@kube-master-54 mw-milvus-even]# ll
total 0
[root@kube-master-54 mw-milvus-even]# pwd
/home/finance/Logs/mw-milvus-even
[root@kube-master-54 mw-milvus-even]#

### Steps To Reproduce

```markdown
/
```

### Milvus Log

/

### Anything else?

/

**Comment by SendTextLi** [comment]
Are there any other methods to export logs to my local directory? Can you show me how to do that @yanliang567 @xiaofan-luan

**Comment by yanliang567** [comment]
> Are there any other methods to export logs to my local directory? Can you show me how to do that @yanliang567 @xiaofan-luan

please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation

**Comment by SendTextLi** [comment]
Using the exporting log script is a feasible approach，but it is not covenient. It's impossible to export all the log in the whole time from my deployment beginning to any time. this script just can play a role when the milvus cluster crashes. It would be better export logs all the time.

**Comment by SendTextLi** [comment]
Using the exporting log script is a feasible approach，but it is not covenient. It's impossible to export all the log in the whole time from my deployment beginning to any time. this script just can play a role when the milvus cluster crashes. It would be better export logs all the time. @yanliang567

**Comment by locustbaby** [comment]
I'll investigate this issue.

**Comment by locustbaby** [comment]
@SendTextLi Hi, I checked your config and I found you set `log.persistence.enabled` as false, pod will use emptyDir actually if false here.
There are the comments before the config.
![image](https://user-images.githubusercontent.com/21237232/231429500-01f56228-a2f9-4b71-b959-bf84dca68909.png)

If you want to see the log on your host, set the `log.persistence.enabled`  as true, also with the correct `log.persistence.persistentVolumeClaim` .

**Comment by SendTextLi** [comment]
@locustbaby I kow this way, I created local pv/pvc and it's useful, but I don't wanna use this approach, which does not Comply with company regulations. Otherwise, the developer of milvus told me changing the log.file.rootPath in milvus.yaml can make sense, but it's a bug, the source code has not gained this paramter from milvus.yaml, in other words, it is not working by modifying this param.

**Comment by locustbaby** [comment]
A bit confused, I test it by myself and it works for me with chart version `milvus-3.3.6` and your `values.yaml`
![image](https://user-images.githubusercontent.com/21237232/231648668-e7648de7-5d2b-45d0-aeb0-f21b5d3412c9.png)
Cause the `log.persistence.enabled:false`, pod use `emptydir` and log exported inside pod

**Comment by xiaofan-luan** [comment]
log.file.rootPath is actually used in BaseTable SetLogger function.
I don't really understand waht is log.persistence.enabled?
I thought user should create a pv and change the log.file.rootPath to that PV right?
@locustbaby could we have a document about different ways to collect metrics?

**Comment by locustbaby** [comment]
Documentation is being written,
The `log.persistence.enabled` is from charts' values which can refer [here](https://github.com/milvus-io/milvus-helm/blob/master/charts/milvus/values.yaml#:~:text=%23%23-,enabled%3A%20false,-annotations%3A).

Let me take an example;

If your charts' values.yaml like this:
```
log:
  level: "debug"
  file:
    maxSize: 300 # MB
    maxAge: 10 # day
    maxBackups: 20
  format: "text" # text/json

  persistence:
    mountPath: "/home/finance/Logs/mw-milvus-even"
    # mountPath: "/milvus/logs"
    ## If true, create/use a Persistent Volume Claim
    ## If false, use emptyDir
    ##
    enabled: true
    annotations:
      helm.sh/resource-policy: keep
    persistentVolumeClaim:
      existingClaim: ""
      ## Milvus Logs Persistent Volume Storage Class
      ## If defined, storageClassName:
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ## set, choosing the default provisioner.
      ## ReadWriteMany access mode required for milvus cluster.
      ##
      storageClass:
      accessModes: ReadWriteOnce
      size: 100Gi
      subPath: ""
```
As you can see the `log.persistence.enabled`  is set as true,  then k8s will create pv automatically with your Storage Class, and the log will be there:

![image](https://user-images.githubusercontent.com/21237232/231961836-16754745-f2f2-4b6a-9ec5-92e16d15e08f.png)

And, the location of the log on host machine depends on how your `Storage Class` work
![image](https://user-images.githubusercontent.com/21237232/231962571-fb1e87ff-af7e-4dfd-a498-09cff5c2b14e.png)


On the other side, If `log.persistence.enabled` is false, there won't be a PVC and pod will use [emptyDir](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir), so that the logs will only in pod
