### ISSUE TITLE
[Bug]: [benchmark] milvus insert data datanode memory rise

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#23359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230410-d845175f
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1b data continuous search test scenario, 
before inserting 1b data datanode memory use no more than 1.4G, but now the same insert frequency, datanode memory use more than 3G, and is still growing.

image: 2.1.0-20220726-1b33c731
datanode memory usage (709m + 733m combined does not exceed 1.4G) :  
![image](https://user-images.githubusercontent.com/48523564/231103603-fb2e69cc-fed0-4df9-8027-b29243e0b70b.png)
![image](https://user-images.githubusercontent.com/48523564/231103617-f17aef7b-881f-42df-96cc-477bcd2c8ddf.png)

image: 2.2.0-20230410-d845175f
```
qtp-1b-test-lbcyr-etcd-0                                          1/1     Running     0               6m23s   10.104.5.110    4am-node12   <none>           <none>
qtp-1b-test-lbcyr-etcd-1                                          1/1     Running     0               6m22s   10.104.6.235    4am-node13   <none>           <none>
qtp-1b-test-lbcyr-etcd-2                                          1/1     Running     0               6m22s   10.104.4.48     4am-node11   <none>           <none>
qtp-1b-test-lbcyr-milvus-datacoord-5b489d5f57-dnvw7               1/1     Running     0               6m23s   10.104.4.31     4am-node11   <none>           <none>
qtp-1b-test-lbcyr-milvus-datanode-5888986546-9kkjt                1/1     Running     1 (2m22s ago)   6m23s   10.104.6.228    4am-node13   <none>           <none>
qtp-1b-test-lbcyr-milvus-indexcoord-6bd8dd4d7-jrjj2               1/1     Running     1 (2m22s ago)   6m23s   10.104.4.33     4am-node11   <none>           <none>
qtp-1b-test-lbcyr-milvus-indexnode-58b84db4c8-ctldx               1/1     Running     0               6m23s   10.104.9.122    4am-node14   <none>           <none>
qtp-1b-test-lbcyr-milvus-proxy-7b9c67b545-st8ch                   1/1     Running     1 (2m22s ago)   6m23s   10.104.5.101    4am-node12   <none>           <none>
qtp-1b-test-lbcyr-milvus-querycoord-695fb8f5b-nfmws               1/1     Running     1 (2m22s ago)   6m23s   10.104.4.35     4am-node11   <none>           <none>
qtp-1b-test-lbcyr-milvus-querynode-8574948fc4-kn8jz               1/1     Running     0               6m23s   10.104.6.227    4am-node13   <none>           <none>
qtp-1b-test-lbcyr-milvus-querynode-8574948fc4-l24r2               1/1     Running     0               6m23s   10.104.9.119    4am-node14   <none>           <none>
qtp-1b-test-lbcyr-milvus-querynode-8574948fc4-p5cbs               1/1     Running     0               6m23s   10.104.4.37     4am-node11   <none>           <none>
qtp-1b-test-lbcyr-milvus-querynode-8574948fc4-p5rjt               1/1     Running     0               6m23s   10.104.5.100    4am-node12   <none>           <none>
qtp-1b-test-lbcyr-milvus-querynode-8574948fc4-vr7vc               1/1     Running     0               6m23s   10.104.4.40     4am-node11   <none>           <none>
qtp-1b-test-lbcyr-milvus-querynode-8574948fc4-xf8cn               1/1     Running     0               6m23s   10.104.1.120    4am-node10   <none>           <none>
qtp-1b-test-lbcyr-milvus-rootcoord-5fb7645c68-mnpcb               1/1     Running     1 (2m22s ago)   6m23s   10.104.4.34     4am-node11   <none>           <none>
qtp-1b-test-lbcyr-minio-0                                         1/1     Running     0               6m23s   10.104.5.109    4am-node12   <none>           <none>
qtp-1b-test-lbcyr-minio-1                                         1/1     Running     0               6m23s   10.104.6.234    4am-node13   <none>           <none>
qtp-1b-test-lbcyr-minio-2                                         1/1     Running     0               6m22s   10.104.4.46     4am-node11   <none>           <none>
qtp-1b-test-lbcyr-minio-3                                         1/1     Running     0               6m22s   10.104.9.124    4am-node14   <none>           <none>
qtp-1b-test-lbcyr-pulsar-bookie-0                                 1/1     Running     0               6m23s   10.104.5.107    4am-node12   <none>           <none>
qtp-1b-test-lbcyr-pulsar-bookie-1                                 1/1     Running     0               6m23s   10.104.6.233    4am-node13   <none>           <none>
qtp-1b-test-lbcyr-pulsar-bookie-2                                 1/1     Running     0               6m22s   10.104.4.45     4am-node11   <none>           <none>
qtp-1b-test-lbcyr-pulsar-bookie-init-qk8wj                        0/1     Completed   0               6m23s   10.104.4.38     4am-node11   <none>           <none>
qtp-1b-test-lbcyr-pulsar-broker-0                                 1/1     Running     0               6m23s   10.104.4.36     4am-node11   <none>           <none>
qtp-1b-test-lbcyr-pulsar-proxy-0                                  1/1     Running     0               6m23s   10.104.5.99     4am-node12   <none>           <none>
qtp-1b-test-lbcyr-pulsar-pulsar-init-q6n6t                        0/1     Completed   0               6m23s   10.104.4.32     4am-node11   <none>           <none>
qtp-1b-test-lbcyr-pulsar-recovery-0                               1/1     Running     0               6m23s   10.104.4.39     4am-node11   <none>           <none>
qtp-1b-test-lbcyr-pulsar-zookeeper-0                              1/1     Running     0               6m23s   10.104.5.106    4am-node12   <none>           <none>
qtp-1b-test-lbcyr-pulsar-zookeeper-1                              1/1     Running     0               5m44s   10.104.6.237    4am-node13   <none>           <none>
qtp-1b-test-lbcyr-pulsar-zookeeper-2                              1/1     Running     0               5m2s    10.104.4.54     4am-node11   <none>           <none>
```
datanode memory usage: 
![image](https://user-images.githubusercontent.com/48523564/231105445-ca4101f3-e9a8-4973-9d50-0e50c9248b41.png)

**Comment by xiaofan-luan** [comment]
can we change the pod limit to 2G and increase the ingest concurrency and see if it OOMed?

**Comment by elstic** [comment]
> can we change the pod limit to 2G and increase the ingest concurrency and see if it OOMed?


> /assign @elstic please retry as suggested above, and did this run with datanode.memory.forceSynceEnable=True?

I will retry and comment the results here.
@yanliang567    Yes, forceEnable is true on images starting with 2.2.0

**Comment by elstic** [comment]
> can we change the pod limit to 2G and increase the ingest concurrency and see if it OOMed?

Set limit 2G and no OOM occurs.
Just insert deny .
use image: 2.2.0-20230412-51f5a128


![image](https://user-images.githubusercontent.com/48523564/231924412-efea7b1f-bdb1-49c3-b380-9501f7f2a605.png)

client error log :
```
[2023-04-13 15:45:28,238 -  INFO - fouram]: [Base] Start inserting, ids: 69450000 - 69499999, data size: 1,000,000,000 (base.py:157)
[2023-04-13 15:45:29,277 -  INFO - fouram]: [Time] Collection.insert run in 1.0378s (api_request.py:41)
[2023-04-13 15:45:29,279 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_4sfUyz8B): 69400000 (base.py:305)
[2023-04-13 15:45:30,629 -  INFO - fouram]: [Base] Start inserting, ids: 69500000 - 69549999, data size: 1,000,000,000 (base.py:157)
[2023-04-13 15:45:31,350 - ERROR - fouram]: RPC error: [batch_insert], <MilvusException: (code=53, message=deny to write, reason: memory quota exhausted, please allocate more resources, req: /milvus.proto.milvus.MilvusService/Insert)>, <Time:{'RPC start': '2023-04-13 15:45:30.652223', 'RPC error': '2023-04-13 15:45:31.350141'}> (decorators.py:108)
[2023-04-13 15:45:31,504 - ERROR - fouram]: Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 33, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 70, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 430, in insert
    res = conn.batch_insert(self._name, entities, partition_name,
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e


pymilvus.exceptions.MilvusException: <MilvusException: (code=53, message=deny to write, reason: memory quota exhausted, please allocate more resources, req: /milvus.proto.milvus.MilvusService/Insert)>
 (api_request.py:48)
[2023-04-13 15:45:31,505 - ERROR - fouram]: (api_response) : <MilvusException: (code=53, message=deny to write, reason: memory quota exhausted, please allocate more resources, req: /milvus.proto.milvus.MilvusService/Insert)> (api_request.py:49)
[2023-04-13 15:45:31,505 - ERROR - fouram]: [CheckFunc] insert request check failed, response:<MilvusException: (code=53, message=deny to write, reason: memory quota exhausted, please allocate more resources, req: /milvus.proto.milvus.MilvusService/Insert)> (func_check.py:49)

```

**Comment by xiaofan-luan** [comment]
/assign @bigsheeper 

could you take a look why the force flush is not happen?

**Comment by bigsheeper** [comment]
working on it

**Comment by bigsheeper** [comment]
**Test 1**
Using pprof to analyze DataNode memory, result:
1. about 50% memory consumed by insertBuffer;
2. about 50% memory consumed by msgstream receive buffer;
![pprof001(1)](https://user-images.githubusercontent.com/42060877/234778014-64ac3dcf-cffd-4e47-b01e-1d6554a18da5.svg)

**Comment by bigsheeper** [comment]
**Test 3**
I assume that the arrow payload writer in C++ consumed a lot of memroy, so I added a log to print the arrow memory pool size. Result:
- Arrow memory pool consumed about only 80MB.

![image](https://user-images.githubusercontent.com/42060877/234781847-74d9cbc7-aea0-4ad5-9718-2d0fba0d929a.png)

**Comment by bigsheeper** [comment]
**Test 4**
I'm attempting to replicate this issue on my local machine and I have observed that DataNode's memory usage increases gradully over time. I used heaptrack to analyze. Result:

- There is an unusual cmalloc memory consumption in the FlameGraph.

![image](https://user-images.githubusercontent.com/42060877/235097437-9444b802-f9ea-4c09-b264-c071e9a4ec0e.png)

[heaptrack.milvus.175568.gz](https://github.com/milvus-io/milvus/files/11351579/heaptrack.milvus.175568.gz)

**Comment by bigsheeper** [comment]
https://github.com/milvus-io/milvus/pull/23138 upgraded arrow, may resolve this issue, please help to make a verify @elstic

**Comment by elstic** [comment]
> /assign @elstic

After verification, datanode memory rise still exists .
use image: 2.2.0-20230525-ef1a671d
argo task : fouramf-4vkjr
 
<img src=https://github.com/milvus-io/milvus/assets/48523564/cba15942-5a13-42e3-b94b-deb4eb04df57 width=60%/>

**Comment by elstic** [comment]
/unassign 
@bigsheeper

**Comment by bigsheeper** [comment]
https://github.com/milvus-io/milvus/pull/24656 with go payload wirter, datanode oom issue may be resolved.

**Comment by bigsheeper** [comment]
/assign @elstic 
please help to make a verify @elstic

**Comment by elstic** [comment]
This issue still exists. 

image: 2.2.0-20230608-a03ebcff 

![image](https://github.com/milvus-io/milvus/assets/48523564/1f3c8f04-85b3-45e3-8897-3acd2c9e0b83)

**Comment by xiaofan-luan** [comment]
this is as expected? unless datanode reaches certain threshold ton do auto flush?

**Comment by elstic** [comment]
> this is as expected? unless datanode reaches certain threshold ton do auto flush?

This is not expected, before we 20 concurrently inserted data, daatanode memory does not rise

**Comment by xiaofan-luan** [comment]
datanode should reserve pod total memory * 0.5, anything below this is as expected

**Comment by xiaofan-luan** [comment]
we only flush under memory pressure. If the pod memory limit is large, milvus will try to use 50% of the memory as data cache

**Comment by xiaofan-luan** [comment]
if your data pod is 8g memory, we would expect to use a little bit more than 4GB memory

**Comment by elstic** [comment]
This issue still exists. Reboot after datanode memory reaches limit .

 

case:  test_concurrent_locust_100m_hnsw_ddl_dql_filter_output_kafka_cluster
argo task :  fouramf-t24hx
during time : 192h

memory usage ： 
![image](https://github.com/milvus-io/milvus/assets/48523564/c94c7e21-ce03-4dff-894b-bc96e0af2c41)

datanode memory usage: 
![image](https://github.com/milvus-io/milvus/assets/48523564/19753d0d-158e-4477-b193-f8ebdd164a3c)

#### Steps:
```
1. create a collection or use an existing collection  
  2. build an HNSW index on the vector column
  3. insert 100 million vectors
  4. flush collection
  5. build index on vector column with the same parameters  
  6. count the total number of rows
  7. load collection
  8. execute concurrent search, query,load,scene_test 
    (scene_test steps: 
       1） Create a collection 2） Insert 3000 pieces of data  3） flush collection 
       4） Create an index  5） drop collection)
  9.  step 8 lasts 192h 
```

server:
```
fouramf-t24hx-30-7593-etcd-0                                      1/1     Running                       0                  8d      10.104.17.130   4am-node23   <none>           <none>
fouramf-t24hx-30-7593-etcd-1                                      1/1     Running                       0                  8d      10.104.4.163    4am-node11   <none>           <none>
fouramf-t24hx-30-7593-etcd-2                                      1/1     Running                       0                  8d      10.104.14.213   4am-node18   <none>           <none>
fouramf-t24hx-30-7593-kafka-0                                     1/1     Running                       1 (8d ago)         8d      10.104.14.212   4am-node18   <none>           <none>
fouramf-t24hx-30-7593-kafka-1                                     1/1     Running                       0                  8d      10.104.1.104    4am-node10   <none>           <none>
fouramf-t24hx-30-7593-kafka-2                                     1/1     Running                       0                  8d      10.104.13.175   4am-node16   <none>           <none>
fouramf-t24hx-30-7593-milvus-datacoord-6d67b686b5-xnx96           1/1     Running                       0                  8d      10.104.19.52    4am-node28   <none>           <none>
fouramf-t24hx-30-7593-milvus-datanode-7c469b8bdc-vstfh            1/1     Running                       2 (2d2h ago)       8d      10.104.19.53    4am-node28   <none>           <none>
fouramf-t24hx-30-7593-milvus-indexcoord-6c847cf9f8-4r6mm          1/1     Running                       0                  8d      10.104.4.160    4am-node11   <none>           <none>
fouramf-t24hx-30-7593-milvus-indexnode-86bdff87b7-nqrgn           1/1     Running                       0                  8d      10.104.17.124   4am-node23   <none>           <none>
fouramf-t24hx-30-7593-milvus-proxy-6958c8fcb4-q7m2v               1/1     Running                       0                  8d      10.104.4.158    4am-node11   <none>           <none>
fouramf-t24hx-30-7593-milvus-querycoord-7595cdff77-p9w8d          1/1     Running                       0                  8d      10.104.19.54    4am-node28   <none>           <none>
fouramf-t24hx-30-7593-milvus-querynode-7f6d9d6bf5-p6tk6           1/1     Running                       0                  8d      10.104.19.55    4am-node28   <none>           <none>
fouramf-t24hx-30-7593-milvus-querynode-7f6d9d6bf5-vt4gq           1/1     Running                       0                  8d      10.104.4.161    4am-node11   <none>           <none>
fouramf-t24hx-30-7593-milvus-rootcoord-7b4cb8fd4c-kz976           1/1     Running                       0                  8d      10.104.19.51    4am-node28   <none>           <none>
fouramf-t24hx-30-7593-minio-0                                     1/1     Running                       0                  8d      10.104.17.132   4am-node23   <none>           <none>
fouramf-t24hx-30-7593-minio-1                                     1/1     Running                       0                  8d      10.104.4.165    4am-node11   <none>           <none>
fouramf-t24hx-30-7593-minio-2                                     1/1     Running                       0                  8d      10.104.5.186    4am-node12   <none>           <none>
fouramf-t24hx-30-7593-minio-3                                     1/1     Running                       0                  8d      10.104.21.223   4am-node24   <none> 
```

**Comment by xiaofan-luan** [comment]
didn't really understand.
Datanode memory is only a few giga bytes.
It rise becasue datanode accumulate data in memory and decrease when flush happened

**Comment by xiaofan-luan** [comment]
3g memory seems to be very reasonable. 
You can tune the param of datanode to decrease memory usage

**Comment by yanliang567** [comment]
> didn't really understand. Datanode memory is only a few giga bytes. It rise becasue datanode accumulate data in memory and decrease when flush happened

Actually the memory usage decreased not because of flush, but OOM and restarted. 
![image](https://github.com/milvus-io/milvus/assets/82361606/8ece92f3-a7e5-4bd3-8c81-8dc68ffedbae)

**Comment by xiaofan-luan** [comment]
> > didn't really understand. Datanode memory is only a few giga bytes. It rise becasue datanode accumulate data in memory and decrease when flush happened
> 
> Actually the memory usage decreased not because of flush, but OOM and restarted. ![image](https://user-images.githubusercontent.com/82361606/273437166-8ece92f3-a7e5-4bd3-8c81-8dc68ffedbae.png)

How much memory does datanode have?

**Comment by xiaofan-luan** [comment]
datanode start to flush with 50% of the datanode allocated memory.

**Comment by elstic** [comment]
> > > didn't really understand. Datanode memory is only a few giga bytes. It rise becasue datanode accumulate data in memory and decrease when flush happened
> > 
> > 
> > Actually the memory usage decreased not because of flush, but OOM and restarted. ![image](https://user-images.githubusercontent.com/82361606/273437166-8ece92f3-a7e5-4bd3-8c81-8dc68ffedbae.png)
> 
> How much memory does datanode have?

dataNode.resources.limits.cpu=2.0,dataNode.resources.limits.memory=4Gi,dataNode.resources.requests.cpu=2.0,dataNode.resources.requests.memory=3Gi

**Comment by yanliang567** [comment]
> > > didn't really understand. Datanode memory is only a few giga bytes. It rise becasue datanode accumulate data in memory and decrease when flush happened
> > 
> > 
> > Actually the memory usage decreased not because of flush, but OOM and restarted. ![image](https://user-images.githubusercontent.com/82361606/273437166-8ece92f3-a7e5-4bd3-8c81-8dc68ffedbae.png)
> 
> How much memory does datanode have?
dataNode.resources.limits.memory=4Gi

**Comment by xiaofan-luan** [comment]
/assign @bigsheeper
could you check why global memory protection is not working?

**Comment by bigsheeper** [comment]
The log is gone, can you help to reproduce it @elstic

**Comment by bigsheeper** [comment]
![img_v2_a3a0959d-5dd0-49b7-a61e-5fcccc32efeg](https://github.com/milvus-io/milvus/assets/42060877/315998c9-68ee-42f3-8b32-94dc02070577)

**Comment by bigsheeper** [comment]
> /assign @bigsheeper could you check why global memory protection is not working?

I'll check it after datanode's memory exceeds 50%.

**Comment by xiaofan-luan** [comment]
seems that bf only takes < 200MB, this may not dominate the datanode memory?

if bf dominate, one of the easy way we can handle it is to mmap

**Comment by bigsheeper** [comment]
newest test: execute concurrent search, query,load,scene_test 
  1.  (scene_test steps: 
       1） Create a collection 2） Insert 3000 pieces of data  3） flush collection 
       4） Create an index  5） drop collection)
  2.  step 1 lasts 60h 

Datanode memory still increases gradually：

![img_v2_8c060f49-5b17-4981-9c2c-327828f305cg](https://github.com/milvus-io/milvus/assets/42060877/3745df57-1c77-4533-bc23-c93710c9c865)
![img_v2_bd6ebe7f-f11c-44fa-ac47-2b19f9b7232g](https://github.com/milvus-io/milvus/assets/42060877/86c5a7a8-5400-4e18-8467-9232b3024e0a)

go heap pprof:
![image](https://github.com/milvus-io/milvus/assets/42060877/98e15b19-53f2-4412-822e-b0c80220fb5c)

**Comment by bigsheeper** [comment]
Associated but should not to be the root cause: https://github.com/milvus-io/milvus/issues/27876

**Comment by elstic** [comment]
This problem still exists
image: master-20231025-a951c757
case: test_concurrent_locust_100m_hnsw_ddl_dql_filter_kafka_cluster

datanode resources settings:
```
'dataNode': {'resources': {'limits': {'cpu': '2.0', 'memory': '4Gi'}
```
datanode memory usage: 
(The datanode reboots when it reaches its memory limit.)
![image](https://github.com/milvus-io/milvus/assets/48523564/94e05b1d-d28c-4bea-849d-8bbb22c94c8e)

server:
```
fouramf-rxm24-58-2368-etcd-0                                      1/1     Running     0                23h     10.104.20.239   4am-node22   <none>           <none>
fouramf-rxm24-58-2368-etcd-1                                      1/1     Running     0                23h     10.104.18.62    4am-node25   <none>           <none>
fouramf-rxm24-58-2368-etcd-2                                      1/1     Running     0                23h     10.104.17.177   4am-node23   <none>           <none>
fouramf-rxm24-58-2368-kafka-0                                     1/1     Running     2 (23h ago)      23h     10.104.20.235   4am-node22   <none>           <none>
fouramf-rxm24-58-2368-kafka-1                                     1/1     Running     2 (23h ago)      23h     10.104.24.24    4am-node29   <none>           <none>
fouramf-rxm24-58-2368-kafka-2                                     1/1     Running     2 (23h ago)      23h     10.104.15.183   4am-node20   <none>           <none>
fouramf-rxm24-58-2368-milvus-datacoord-c6fbbd56f-9kh58            1/1     Running     0                23h     10.104.24.16    4am-node29   <none>           <none>
fouramf-rxm24-58-2368-milvus-datanode-5b98456b9-4w49w             1/1     Running     1 (7h55m ago)    23h     10.104.24.17    4am-node29   <none>           <none>
fouramf-rxm24-58-2368-milvus-indexcoord-6f5b746dc6-zrsxs          1/1     Running     0                23h     10.104.24.15    4am-node29   <none>           <none>
fouramf-rxm24-58-2368-milvus-indexnode-8555845f7c-7npgs           1/1     Running     0                23h     10.104.23.213   4am-node27   <none>           <none>
fouramf-rxm24-58-2368-milvus-proxy-846757fb58-sc6f5               1/1     Running     0                23h     10.104.23.212   4am-node27   <none>           <none>
fouramf-rxm24-58-2368-milvus-querycoord-9b95bd9f9-dln6q           1/1     Running     0                23h     10.104.18.52    4am-node25   <none>           <none>
fouramf-rxm24-58-2368-milvus-querynode-55f4789d85-2z87j           1/1     Running     0                23h     10.104.19.253   4am-node28   <none>           <none>
fouramf-rxm24-58-2368-milvus-querynode-55f4789d85-ttqsj           1/1     Running     0                23h     10.104.4.67     4am-node11   <none>           <none>
fouramf-rxm24-58-2368-milvus-rootcoord-6b7ffd6665-nm52s           1/1     Running     0                23h     10.104.24.14    4am-node29   <none>           <none>
fouramf-rxm24-58-2368-minio-0                                     1/1     Running     0                23h     10.104.20.241   4am-node22   <none>           <none>
fouramf-rxm24-58-2368-minio-1                                     1/1     Running     0                23h     10.104.18.60    4am-node25   <none>           <none>
fouramf-rxm24-58-2368-minio-2                                     1/1     Running     0                23h     10.104.17.178   4am-node23   <none>           <none>
fouramf-rxm24-58-2368-minio-3                                     1/1     Running     0                23h     10.104.24.27    4am-node29   <none>           <none>
fouramf-rxm24-58-2368-zookeeper-0                                 1/1     Running     0                23h     10.104.19.3     4am-node28   <none>           <none>
fouramf-rxm24-58-2368-zookeeper-1                                 1/1     Running     0                23h     10.104.20.240   4am-node22   <none>           <none>
fouramf-rxm24-58-2368-zookeeper-2                                 1/1     Running     0                23h     10.104.18.63    4am-node25   <none>           <none>
```

**Comment by bigsheeper** [comment]
> This problem still exists image: master-20231025-a951c757 case: test_concurrent_locust_100m_hnsw_ddl_dql_filter_kafka_cluster
> 
> datanode resources settings:
> 
> ```
> 'dataNode': {'resources': {'limits': {'cpu': '2.0', 'memory': '4Gi'}
> ```
> 
> datanode memory usage: (The datanode reboots when it reaches its memory limit.) ![image](https://user-images.githubusercontent.com/48523564/278228307-94e05b1d-d28c-4bea-849d-8bbb22c94c8e.png)
> 
> server:
> 
> ```
> fouramf-rxm24-58-2368-etcd-0                                      1/1     Running     0                23h     10.104.20.239   4am-node22   <none>           <none>
> fouramf-rxm24-58-2368-etcd-1                                      1/1     Running     0                23h     10.104.18.62    4am-node25   <none>           <none>
> fouramf-rxm24-58-2368-etcd-2                                      1/1     Running     0                23h     10.104.17.177   4am-node23   <none>           <none>
> fouramf-rxm24-58-2368-kafka-0                                     1/1     Running     2 (23h ago)      23h     10.104.20.235   4am-node22   <none>           <none>
> fouramf-rxm24-58-2368-kafka-1                                     1/1     Running     2 (23h ago)      23h     10.104.24.24    4am-node29   <none>           <none>
> fouramf-rxm24-58-2368-kafka-2                                     1/1     Running     2 (23h ago)      23h     10.104.15.183   4am-node20   <none>           <none>
> fouramf-rxm24-58-2368-milvus-datacoord-c6fbbd56f-9kh58            1/1     Running     0                23h     10.104.24.16    4am-node29   <none>           <none>
> fouramf-rxm24-58-2368-milvus-datanode-5b98456b9-4w49w             1/1     Running     1 (7h55m ago)    23h     10.104.24.17    4am-node29   <none>           <none>
> fouramf-rxm24-58-2368-milvus-indexcoord-6f5b746dc6-zrsxs          1/1     Running     0                23h     10.104.24.15    4am-node29   <none>           <none>
> fouramf-rxm24-58-2368-milvus-indexnode-8555845f7c-7npgs           1/1     Running     0                23h     10.104.23.213   4am-node27   <none>           <none>
> fouramf-rxm24-58-2368-milvus-proxy-846757fb58-sc6f5               1/1     Running     0                23h     10.104.23.212   4am-node27   <none>           <none>
> fouramf-rxm24-58-2368-milvus-querycoord-9b95bd9f9-dln6q           1/1     Running     0                23h     10.104.18.52    4am-node25   <none>           <none>
> fouramf-rxm24-58-2368-milvus-querynode-55f4789d85-2z87j           1/1     Running     0                23h     10.104.19.253   4am-node28   <none>           <none>
> fouramf-rxm24-58-2368-milvus-querynode-55f4789d85-ttqsj           1/1     Running     0                23h     10.104.4.67     4am-node11   <none>           <none>
> fouramf-rxm24-58-2368-milvus-rootcoord-6b7ffd6665-nm52s           1/1     Running     0                23h     10.104.24.14    4am-node29   <none>           <none>
> fouramf-rxm24-58-2368-minio-0                                     1/1     Running     0                23h     10.104.20.241   4am-node22   <none>           <none>
> fouramf-rxm24-58-2368-minio-1                                     1/1     Running     0                23h     10.104.18.60    4am-node25   <none>           <none>
> fouramf-rxm24-58-2368-minio-2                                     1/1     Running     0                23h     10.104.17.178   4am-node23   <none>           <none>
> fouramf-rxm24-58-2368-minio-3                                     1/1     Running     0                23h     10.104.24.27    4am-node29   <none>           <none>
> fouramf-rxm24-58-2368-zookeeper-0                                 1/1     Running     0                23h     10.104.19.3     4am-node28   <none>           <none>
> fouramf-rxm24-58-2368-zookeeper-1                                 1/1     Running     0                23h     10.104.20.240   4am-node22   <none>           <none>
> fouramf-rxm24-58-2368-zookeeper-2                                 1/1     Running     0                23h     10.104.18.63    4am-node25   <none>           <none>
> ```

Pprof and corresponding memory monitoring:
![NDuf6aJmCD](https://github.com/milvus-io/milvus/assets/42060877/1b90e600-f96b-4bff-86f2-793f8a63e136)

![FqxJT1APnj](https://github.com/milvus-io/milvus/assets/42060877/5eb48df9-16ed-433a-a350-a92f51717af0)

![img_v2_908c05c1-24e0-44e4-bc2d-37a9cadba44g](https://github.com/milvus-io/milvus/assets/42060877/edd1907b-d2ac-42ea-b29c-b4c51ae1b8d2)

![pprof001](https://github.com/milvus-io/milvus/assets/42060877/b24f54aa-59a4-48c4-8008-2ef682ea4b5b)
47133)

**Comment by xiaofan-luan** [comment]
goroutine misuse and leakage is something we should deal with

**Comment by xiaofan-luan** [comment]
is this still a issue? @yanliang567 
do we see go routine leakage after drop collection?

**Comment by yanliang567** [comment]
@elstic please check the results in recent nightly.
/assign @elstic

**Comment by bigsheeper** [comment]
> is this still a issue? @yanliang567 do we see go routine leakage after drop collection?

I have verified; there is no leakage of goroutines.

**Comment by bigsheeper** [comment]
pprof shows 84MB heap in use:
![cluster-test-pulsar_20231208_15_17](https://github.com/milvus-io/milvus/assets/42060877/3990a7e5-9970-4e23-99cf-fb3de3a16abf)

but memory usage is about 974MB:
![image](https://github.com/milvus-io/milvus/assets/42060877/70938731-c993-44d6-aa57-29ec51a99b7b)

BTW, there is a memory leak, because datanode OOMed many times:
![image](https://github.com/milvus-io/milvus/assets/42060877/bc9a80af-0caa-44fe-8873-2097309131dd)

**Comment by bigsheeper** [comment]
I attempted to utilize other tools such as heaptrack and memleak, but encountered inoperability.

**Comment by bigsheeper** [comment]
/assign @czs007 
please help to investigate.

**Comment by elstic** [comment]
May be fixed by this pr:   https://github.com/milvus-io/milvus/pull/29268 
No datanode memory hikes.
![image](https://github.com/milvus-io/milvus/assets/48523564/44612798-5322-4256-825a-d93fdd0b6df6)


Verify case : test_concurrent_locust_100m_hnsw_ddl_dql_filter_kafka_cluster
