### ISSUE TITLE
[Enhancement]: Tune the topk when the topk is large to improve performance

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#23370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

For each of the search, if the topk is large, then search on each segment and reduce is slow.

They way I propose it to reduce topk numbers for segment size is larger on the shard leader.

For example:
For topk > 100 , we can change topk per segment to original topk / sqrt(segment numbers), that will definitely help to improve   the search performance with large topks and large amount of data

**Comment by xiaofan-luan** [comment]
> What is the `recall` reduced by this way?

most cases no.  For instance, if you have 10 segments, if retrieve top 100 from each segments, then you has to reduce from top 1000 results to find top 100. But if you reduce the topk from 100 to 30, you still get 300 results to find top 100, which will probably miss 1 or 2 results but won't affect too much

**Comment by jiaoew1991** [comment]
keep it open

**Comment by winterfellding** [comment]
Hi, i'd like to know if there's any update about this issue.
