### ISSUE TITLE
[Bug]: local cache is not cleaned after collection released

### ISSUE THREAD

**Issue by longjiquan** [milvus-io/milvus#23373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Deploy milvus cluster locally, and then run `hello_milvus` locally. After completion, even though after the query cluster have released the collection, the chunk cache still existed.

**Comment by xiaofan-luan** [comment]
what is a chunk cache?

**Comment by longjiquan** [comment]
> what is a chunk cache?

The local cache when we tried to retrieve vectors from minio.

**Comment by longjiquan** [comment]
I don't know if it's proper to call it as `chunk cache` or `local cache`, maybe `local cache` is better?
