### ISSUE TITLE
[Feature]: Support JSON data type

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#23389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Now Milvus requires a schema like SQL database, we need the ability to dynamically add new field, and store some dynamic data (like resume), JSON is what we need

**Comment by yah01** [comment]
Also this feature should be add into 2.2.0 branch

**Comment by congqixia** [comment]
- [ ] Add JSON support for `MergeDataArray` @yah01

**Comment by yah01** [comment]
> * [ ]  Add JSON support for `MergeDataArray` @yah01

included in #23644

**Comment by yah01** [comment]
JSON feature compeleted, open new issues for the coming related features
