### ISSUE TITLE
[Enhancement]: Optimize the return result of collection.get_replicas interface

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#23396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

**Optimize the results of shard_nodes to improve the readability** 

![b340f476-6c5c-43bf-ac6f-acc8351160b7](https://user-images.githubusercontent.com/26307815/231416455-90513c88-d6dd-4a56-8c5b-a2ac35ba4cf6.jpeg)

**Comment by xiaofan-luan** [comment]
good suggestion

**Comment by binbinlv** [comment]
@XuanYang-cn 

The results using Pymilvus 2.2.6:
```
>>> collection.get_replicas()
Replica groups:
- Group: <group_id:440468238087487498>, <group_nodes:(414,)>, <shards:[Shard: <channel_name:disable-sync-rootcoord-dml_18_440476454498368194v0>, <shard_leader:414>, <shard_nodes:{414}>, Shard: <channel_name:disable-sync-rootcoord-dml_19_440476454498368194v1>, <shard_leader:414>, <shard_nodes:{414}>]>, <resource_group: __default_resource_group>, <num_outbound_node: {}>
>>>
```

Should "shard_nodes:{414}" be shard_nodes:{'query node id': nodes number, ...} or {(query node id, nodes number), }?

**Comment by XuanYang-cn** [comment]
> 

@binbinlv What's the difference of query node id with nodes number?

**Comment by XuanYang-cn** [comment]
should be fixed
/unasign
/assign @wangting0128

**Comment by wangting0128** [comment]
verified, close now.
