### ISSUE TITLE
[Bug]: After deleting 600,000 data from a 60 million dataset in Milvus, no data can be queried, and the number of datasets still appears.

### ISSUE THREAD

**Issue by linggong2011** [milvus-io/milvus#23409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

[Bug]: After deleting 600,000 data from a 60 million dataset in Milvus, no data can be queried, and the number of datasets still appears.

### Expected Behavior

works normally

### Milvus Log

[logs.tar.gz](https://github.com/milvus-io/milvus/files/11218891/logs.tar.gz)

**Comment by Cheung7788** [comment]
[bw_etcd_ALL.230413-064118.bak.gz](https://github.com/milvus-io/milvus/files/11218987/bw_etcd_ALL.230413-064118.bak.gz)

**Comment by xiaofan-luan** [comment]
> 

Is shihuo_json_milvus the collection you are talking about right?

And from the log all I see is that the shihuo_json_milvus is an empty collection. Could you explain in detail(better in code about all the operations you did?)

From the log: it should be a alias change or drop collection
[2023/04/12 14:02:39.755 +00:00] [INFO] [proxy/impl.go:109] ["received request to invalidate collection meta cache"] [traceID=16e624abb4bbdc93] [module=Proxy] [role=proxy] [db=] [collectionName=shihuo_json_milvus] [collectionID=0]

And all of the search result is empty for this collection
search result is empty
[2023/04/13 04:49:59.206 +00:00] [WARN] [proxy/task_search.go:450] ["search result is empty"] [traceID=6cebe5cca64ad74] [msgID=440758802624544785]

**Comment by Cheung7788** [comment]
yes, user deletes shihuo_json_milvus collection, and rebuilds a collection with the same name, inserts data and deletes one percent of it, then returns empty in the search & query.

but, create another table in this cluster, delete some data, and do queries, everything is normal.

Through the log we found this issue：
![img_v2_c45fa2bd-904f-4f6c-9878-8fbbb81a0deg](https://user-images.githubusercontent.com/28556111/231932398-573cbc67-d64f-4d2a-8418-bf97e61da9e5.jpg)
We restarted querycoord and querynode to restore the service.

**Comment by yanliang567** [comment]
/assign @binbinlv 
could you please help to reproduce it in house?

**Comment by binbinlv** [comment]
Did not reproduce this issue:
milvus: 2.2.0
pymilvus: 2.2.0
replica: 2
deploy: cluster, pulsar

my step is:
1. create collection
2. insert data
3. create index
4. load
5. search: successfully
6. delete one percent of insert data
7. search: successfully
8. drop this collection
9. create the collection with the same name
10. insert data
11. create index
12. load
13. search: successfully
14. delete one percent of insert data
15. search: successfully
16. And restart querycoord and querynode
17. search: successfully.

@linggong2011 
Is my operation the same with yours? thx.
