### ISSUE TITLE
[Bug]: 2.2.5milvus write 2000W data employ 750G  internal storage

### ISSUE THREAD

**Issue by changhong52** [milvus-io/milvus#23400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.5
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pusar
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.0
- OS(Ubuntu or CentOS): 
- CPU/Memory: 256C/800G
- GPU: 
- Others:
```

### Current Behavior

write 2000W data  employ 750G  internal storage ,data structure and memory:
4 varchar and 1 vector:

![Uploading [milvus2.jpg…]()]

**Comment by xiaofan-luan** [comment]
we know the issue and it will be fixed soon in 2.2.6

**Comment by JackLCL** [comment]
I wrote a script to try to reproduce this problem. But I didn't reproduce it successfully. I found that the memory usage of Milvus2.2.5 is lower than that of Milvus2.2.0.
Here is my reproduce code:

`# hello_milvus.py demonstrates the basic operations of PyMilvus, a Python SDK of Milvus.
# 1. connect to Milvus
# 2. create collection
# 3. insert data
# 4. create index
# 5. search, query, and hybrid search on entities
# 6. delete entities by PK
# 7. drop collection
import time

import numpy as np
from pymilvus import (
    connections,
    utility,
    FieldSchema, CollectionSchema, DataType,
    Collection,
)

fmt = "\n=== {:30} ===\n"
search_latency_fmt = "search latency = {:.4f}s"
num_entities, dim = 1000, 512

#################################################################################
# 1. connect to Milvus
# Add a new connection alias `default` for Milvus server in `localhost:19530`
# Actually the "default" alias is a buildin in PyMilvus.
# If the address of Milvus is the same as `localhost:19530`, you can omit all
# parameters and call the method as: `connections.connect()`.
#
# Note: the `using` parameter of the following methods is default to "default".
print(fmt.format("start connecting to Milvus"))
connections.connect("default", host="10.102.7.182", port="19530")

has = utility.has_collection("hello_milvus")
print(f"Does collection hello_milvus exist in Milvus: {has}")

fields = [
    FieldSchema(name="pk", dtype=DataType.VARCHAR, is_primary=True, auto_id=False, max_length=1000),
    FieldSchema(name="str1", dtype=DataType.VARCHAR, max_length=1000),
    FieldSchema(name="str2", dtype=DataType.VARCHAR, max_length=1000),
    FieldSchema(name="str3", dtype=DataType.VARCHAR, max_length=1000),
    FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=dim)
]

schema = CollectionSchema(fields, "hello_milvus is the simplest demo to introduce the APIs")

print(fmt.format("Create collection `hello_milvus`"))
hello_milvus = Collection("hello_milvus", schema, consistency_level="Strong")

################################################################################
# 4. create index
# We are going to create an IVF_FLAT index for hello_milvus collection.
# create_index() can only be applied to `FloatVector` and `BinaryVector` fields.
print(fmt.format("Start Creating index IVF_FLAT"))
index = {
    "index_type": "IVF_FLAT",
    "metric_type": "L2",
    "params": {"nlist": 128},
}

hello_milvus.create_index("embeddings", index)

print(fmt.format("Start loading"))
hello_milvus.load()

print(fmt.format("Start loading"))
hello_milvus.load()
、
`

**Comment by JackLCL** [comment]
For Milvus2.2.0:
![4hyRM5v88I](https://user-images.githubusercontent.com/53512883/231681313-e93cbda9-4cf2-4dd3-b71d-5e8f65e7de9e.jpg)

![2091aa4c-0040-4291-bc55-03ad6371f047](https://user-images.githubusercontent.com/53512883/231681470-5a75896e-b736-4236-adb2-e26eb5fbbbaa.jpeg)

![HmbkVu2khk](https://user-images.githubusercontent.com/53512883/231681577-82e2cfec-3550-428a-a7c9-8525fb84fe9d.jpg)

**Comment by JackLCL** [comment]
For Milvus2.2.5:
![da29aa90-533d-4486-b50a-399c43907ec5](https://user-images.githubusercontent.com/53512883/231681798-2888b443-a06f-4a87-ba65-3791f1e1439b.jpeg)

![image](https://user-images.githubusercontent.com/53512883/231682023-7be6cab4-0da5-4268-a4b5-823ac2fa808a.png)

![d3959c39-d386-414a-99bd-365b4756966c](https://user-images.githubusercontent.com/53512883/231682144-a9428303-3702-47c5-aff7-7dab31501afa.jpeg)

**Comment by yanliang567** [comment]
milvus 2.2.6 is going to be available soon.
/assign @changhong52 
/unassign
