### ISSUE TITLE
[Bug]: Unable to import data correctly using Attu interface

### ISSUE THREAD

**Issue by LiJie20190102** [milvus-io/milvus#23416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.5
- Deployment mode(standalone or cluster): standalone 
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others: Attu 2.2.3
```

### Current Behavior

I use the Attu interface and select the specified partition to import data into the collection, but the final data will enter Default_ partition.
![image](https://user-images.githubusercontent.com/53458004/231729720-e38e847a-9f9f-4100-9c93-0dfb0170e7d0.png)

![image](https://user-images.githubusercontent.com/53458004/231729749-be3b4d17-604d-4248-8b8e-c618bca2d7bb.png)

### Expected Behavior

Using the Attu interface to import data into the correct partition

### Steps To Reproduce

```markdown
1.Use the Attu interface to select the partition for the collection and import data
2. Check if the data is in the corresponding partition
```

**Comment by yanliang567** [comment]
/assign @NicoYuan1986 
could you please help to reproduce it in house?
/unassign

**Comment by NicoYuan1986** [comment]
Reproduce the error in house. @yanliang567 
milvus: 2.2.5
attu: 2.2.4

1. insert to partition 'news'
![image](https://user-images.githubusercontent.com/109071306/232005096-8a3e8ff5-bb83-4952-9cfd-1a184b0b2f1f.png)

2. check 
![image](https://user-images.githubusercontent.com/109071306/232005414-2c62b748-2297-43ab-905e-40fccdc390b2.png)

**Comment by NicoYuan1986** [comment]
It seems to be a milvus problem.
![image](https://user-images.githubusercontent.com/109071306/232016763-493b789d-3369-4f2a-aa64-ca924ff0905e.png)
('_default' represents 'Default partition' in attu)
