### ISSUE TITLE
script query expected

### ISSUE THREAD

**Issue by sunyaofei** [milvus-io/milvus#2342]
**Is your feature request related to a problem? Please describe.**
for field x, need bit operate `x & 1024 != 0` as a filter condition

**Describe the solution you'd like**
[reference for elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-script-query.html)

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by scsven** [comment]
@sunyaofei Thanks for you suggestion ! The default script language in Elasticsearch is Painless. It's designed specifically for use with Elasticsearch. We will consider integrating a scripting language in the future to support more filtering conditions. If you have good suggestions, please let us know.
