### ISSUE TITLE
[Enhancement]: Support concurrent write delete records on QueryNode

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#23429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

A delete buffer in QueryNode, also a sealed delete records. The delete buffer should be a map, so we are able to delete items in any order. The QueryNode merges the delete buffer into sealed delete records periodically , to improve the performance while applying delete

### Why is this needed?

Now QueryNode requires the delete records to be applied in order, and no concurrent write. This limits us to balance channel, also it's easy to make mistakes that breaks this limit. I'd like to remove this limitation

**Comment by xiaofan-luan** [comment]
> I totally agree with that

**Comment by yah01** [comment]
adding delete buffer requires a write lock while deleting, may slow query/search perf

**Comment by yah01** [comment]
For master, the problem is there may be multiple delegators are delivering the delete records to the same segment. We could simply skip applied delete records, cases are:
- if 1,2,3 already deleted, then try to delete 2,3,4, we could only apply 4
- if 1,2,3 already deleted, then try to delete 1,2, we could skip all
- if 1,2,3 already deleted, then try to delete 4,5, we apply all
- if 1,2,3 already deleted, then try to delete 0, we name this bad case, we can't handle this, and need a solution to avoid this

Let's consider two delegator $d_1, d_2$, and $d_2$ is the new one.
- if the segment is loaded by $d_1$, then no bad case because $d_1$ and $d_2$ are delivering delete records from the same checkpoint
- if the segment is loaded by $d_2$, as $d_1$ will see the segment by sync operation, which makes $d_1$ to update the checkpoint to be the same as $d_2$

**Comment by congqixia** [comment]
@yah01 So it could be deducted that:
1. Delegators shall forward delete data monotonically increasing by time
2. All delegators shall share the same checkpoint

I think point 2 may have some problem in following situation:
- $d_1$ $d_2$ has the same set up
- Segment $S_1$ is an existing segment that does not need to be balanced
- $d_1$ has an older position, say $p_0$, following by data $m_1$,  $m_2$, $m_3$
- $d_2$ has a newer vision (with target updated), say $p_1$, following by data $m_3$ $m_4$ $m_5$

If $d_2$ does nothing to patch position, it will send $m_3$ directly and make this layout:

> $S_1$ : $m_0$, $m_3$ ...

So we need add the ability to load added `deltalog` from $d_2$ and pending delete here?
