### ISSUE TITLE
[Bug]: creating partition is not atomic

### ISSUE THREAD

**Issue by longjiquan** [milvus-io/milvus#23436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://github.com/milvus-io/milvus/blob/a88178a5eaef499f0342729c51ae38d5cedf35a5/internal/rootcoord/create_partition_task.go#L79-L107

**Comment by longjiquan** [comment]
If the task succeeded on `addPartitionMetaStep` but failed on later steps, the garbage will leave in the meta.

**Comment by longjiquan** [comment]
By the way, we should also pay attention to the recovery logci of the partitions under creating state.

**Comment by xiaofan-luan** [comment]
> By the way, we should also pay attention to the recovery logci of the partitions under creating state.

Is there a bug on it?

**Comment by longjiquan** [comment]
not very critical, and we haven't released the feature yet.

**Comment by longjiquan** [comment]
The only problem is that it will leave garbage on the etcd.

**Comment by bigsheeper** [comment]
fixed
