### ISSUE TITLE
[Bug]: The default configs are different when Milvus is deployed by different tools

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#23435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

* minio buckets:

docker-compose: a-bucket/files

helm/operator: milvus-bucket/file

* label 

helm: 
```
app.kubernetes.io/instance=yongpeng-suivm
app.kubernetes.io/name=milvus
component=datanode
```

operator
```
app.kubernetes.io/component=datanode
app.kubernetes.io/instance=disable-sync
app.kubernetes.io/name=milvus
```

* etcd prefix

helm: by-dev

operator: ${release_name}

### Expected Behavior

It would be better if the default config is the same when using different deploy tools

**Comment by zhuwenxing** [comment]
What are the inconveniences:
1. configuration of Milvus-backup
2. Milvus-CDC configuration
3. Chaos test requires different configuration files when fault injection is performed on the same type of component

**Comment by yanliang567** [comment]
/assign @LoveEachDay 
can we keep the same configs for the new deployments first?
/unassign
