### ISSUE TITLE
[Bug]: [Sizingtool] ivf_sq8 Index memory usage calculation error

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#23442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.6-20230413-d0e87113
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

ivf_sq8 index memory usage calculation error, standalone ivf_sq8 index tool shows 14 million, memory usage 5.1G, real time test 7 million when memory usage has reached 8G

params: 
   nlist: 1024
   dim:128

![image](https://user-images.githubusercontent.com/48523564/232020244-6f1d084f-e1b7-4d4d-b4b6-838636769558.png)

case:

![image](https://user-images.githubusercontent.com/48523564/232021117-cf980b2e-6add-4154-9959-6255d7da9784.png)

![image](https://user-images.githubusercontent.com/48523564/232021448-9427014b-716c-49ce-bb42-b8fe66440077.png)

**Comment by yanliang567** [comment]
@elstic sizing tool estimates the memory for querynode in cluster mode, in standalone it requires more memory for indexnode and datanode, which is expected.

/assign @elstic 
/unassign

**Comment by elstic** [comment]
> @elstic sizing tool estimates the memory for querynode in cluster mode, in standalone it requires more memory for indexnode and datanode, which is expected.
> 
> /assign @elstic /unassign

Okay, I'll close the issue then
