### ISSUE TITLE
Optimize API `search_in_segment` for mishards

### ISSUE THREAD

**Issue by BossZou** [milvus-io/milvus#2346]
**What is your question?**
When received a search request, mishards will obtain collection files meta from meta db, then invoke `search_in_segment`. In the meantime server may run a merge task to merge collection files, then mark outdated files as `TO_DELETE` after finished. So there is a situation: When mishards get collection file meta, it received available segment file A, B, C, but  at the time of invoke `search_in_segment`, file A, B, C has been merged into D and marked as `TO_DELETE`, then server will return a incorrect status with message `Invalid file id.`
During mishards visiting meta db, it filter files which typs is `TO_DELETE`, and server do the same thing during search with file ids. I tried  comments code as below:
```
--*db/meta/MySQlMetaImpl.cpp::FilesByID*--
            // End
            // statement << " AND"
            //           << " (file_type = " << std::to_string(SegmentSchema::RAW)
            //           << " OR file_type = " << std::to_string(SegmentSchema::TO_INDEX)
            //           << " OR file_type = " << std::to_string(SegmentSchema::INDEX) << ");";
```
This bug doesn't appear any more. I think server not need to check file type(status), but I have no idea there are potential risks. Maybe need a discussion.

**Comment by tinkerlin** [comment]
fixed by #2367
