### ISSUE TITLE
[Bug]: can't make the first connection 

### ISSUE THREAD

**Issue by E7ANA** [milvus-io/milvus#23460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.5
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.2.5
- OS(Ubuntu or CentOS): windows
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

when I'm trying to connect for the first time with this code:
`from pymilvus import connections
connections.connect(
  alias="default", 
  host='localhost', 
  port='19530'
)`

I get this error messge:
`    raise MilvusException(Status.CONNECT_FAILED,
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530. Timeout)>`

I opened this port at my firewall, what else should I do? thanks.

### Expected Behavior

It should connect to the server

**Comment by Cheung7788** [comment]
Try using proxy ip instead of locahost

**Comment by yanliang567** [comment]
/assign @locustbaby 
any ideas?

/unassign

**Comment by E7ANA** [comment]
With mibikube and docker

**Comment by locustbaby** [comment]
> ` raise MilvusException(Status.CONNECT_FAILED, pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530. Timeout)>`

https://milvus.io/docs/install_standalone-helm.md#Connect-to-Milvus

**Comment by HongLouyemeng** [comment]
> https://milvus.io/docs/install_standalone-helm.md#Connect-to-Milvus 你是用operator/helm安装的吗？其实你可以用同样的方式连接到milvus，因为它们都安装在k8s中
我得到了相同的问题。。
