### ISSUE TITLE
[Bug]: Insert and query topk is blocked

### ISSUE THREAD

**Issue by yesletgo** [milvus-io/milvus#23461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.3
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):   pulsar  
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.3
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 84cores/600G
- GPU: 
- Others:
```

### Current Behavior

A data volume of tens of millions of levels, as the data volume increases, inserting and querying topks are blocked

### Expected Behavior

should not blocked

### Milvus Log

https://video-tag-lib-1251808348.cos.ap-beijing.myqcloud.com/milvus_log/milvus-log.tar.gz

**Comment by smellthemoon** [comment]
<img width="1226" alt="1" src="https://user-images.githubusercontent.com/64083300/232392503-581e8ad0-57e1-4298-b6f6-7d7f3a5803c8.png">
querynode reports endless segments cause mom.
seems to be fixed with #22976 
you can upgrade to 2.2.5 and try again. @yesletgo

**Comment by yesletgo** [comment]
> <img alt="1" width="1226" src="https://user-images.githubusercontent.com/64083300/232392503-581e8ad0-57e1-4298-b6f6-7d7f3a5803c8.png">
> 
> querynode reports endless segments cause oom. seems to be fixed with #22976 you can upgrade to 2.2.5 and try again. @yesletgo

Isn't this log a datanode？but you say querynode. Is it datanode that causes querynode oom?

**Comment by smellthemoon** [comment]
> > <img alt="1" width="1226" src="https://user-images.githubusercontent.com/64083300/232392503-581e8ad0-57e1-4298-b6f6-7d7f3a5803c8.png">
> > querynode reports endless segments cause oom. seems to be fixed with #22976 you can upgrade to 2.2.5 and try again. @yesletgo
> 
> Isn't this log a datanode？but you say querynode. Is it datanode that causes querynode oom?

sorry, it's a typo. I mean datanode.

**Comment by yesletgo** [comment]
> sorry, it's a typo. I mean datanode.
Okay, why doesn't the log display datanode oom instead of querynode oom?
<img width="756" alt="微信图片_20230417144937" src="https://user-images.githubusercontent.com/21998052/232406181-6e77ed86-3ab4-4588-92e5-8158ca1c4488.png">

**Comment by smellthemoon** [comment]
> > sorry, it's a typo. I mean datanode.
> > Okay, why doesn't the log display datanode oom instead of querynode oom?
> 
> <img alt="微信图片_20230417144937" width="756" src="https://user-images.githubusercontent.com/21998052/232406181-6e77ed86-3ab4-4588-92e5-8158ca1c4488.png">

because load failed, endless segment cause DataCoord oom. When you query, you can see querycoord report the error.

**Comment by yesletgo** [comment]
> > > sorry, it's a typo. I mean datanode.
> > > Okay, why doesn't the log display datanode oom instead of querynode oom?
> > 
> > 
> > <img alt="微信图片_20230417144937" width="756" src="https://user-images.githubusercontent.com/21998052/232406181-6e77ed86-3ab4-4588-92e5-8158ca1c4488.png">
> 
> because load failed, endless segment cause DataCoord oom. When you query, you can see querycoord report the error.
After upgrading to 2.2.5, another issue occurred. [](url)https://github.com/milvus-io/milvus/issues/23477
