### ISSUE TITLE
[Bug]: how to get  the port which my pod is running on windows 11

### ISSUE THREAD

**Issue by 1nnovat1on** [milvus-io/milvus#23476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

kubectl get pod my-release-milvus-standalone-54c4f88cb9-f84pf --template='{{(index (index .spec.containers 0).ports 0).containerPort}}{{"\n"}}'

i get error: error parsing template '{{(index, template: output:1: unclosed action

### Expected Behavior

I should be getting the port which my pod is running on

### Steps To Reproduce

```markdown
windows 11
```

**Comment by locustbaby** [comment]
@1nnovat1on Hi, Could you please run `kubectl get pod` and share the result with us?
