### ISSUE TITLE
[Bug]:  Collection.name is succussfully accessed, but collection.num_entities is locked for a long time and finaly failed

### ISSUE THREAD

**Issue by jaloveapple** [milvus-io/milvus#23470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):  pymilvus 2.1.1
- OS(Ubuntu or CentOS):  ubuntu
- CPU/Memory: 
- GPU:  NO
- Others:
```

### Current Behavior

def show_collection(collection_name):
    connections.connect(host="127.0.0.1", port='19530')
    # collection_name = "ImageSearchOwnTest"
    col = Collection(collection_name)
    print("Collection name:", col.name)
    print("Collection ",col.schema)  #is_empty
    print("Collection partition:", col.partitions)
    print("Collection primary_field", col.primary_field)

    # This is error
    #print("num of entities:", col.num_entities)
    # This is still error
    #print(col.is_empty)

In above  col. name is accessed normally,  but col.num_entities cannot be accessed, it will  stay for a long time.

Traced back : pymilvus/client/grpc_handler.py
we find:
    def num_entities(self) -> int:
        """
        Returns the number of entities in the collection.

        :return int:
            Number of entities in the collection.

        :raises CollectionNotExistException: If the collection does not exist.

        :example:
            >>> from pymilvus import connections, Collection, FieldSchema, CollectionSchema, DataType
            >>> connections.connect()
            >>> schema = CollectionSchema([
            ...     FieldSchema("film_id", DataType.INT64, is_primary=True),
            ...     FieldSchema("films", dtype=DataType.FLOAT_VECTOR, dim=2)
            ... ])
            >>> collection = Collection("test_collection_num_entities", schema)
            >>> collection.num_entities
            0
            >>> collection.insert([[1, 2], [[1.0, 2.0], [3.0, 4.0]]])
            >>> collection.num_entities
            2
            """
        conn = self._get_connection()
        conn.flush([self._name])   # we found this error
        stats = conn.get_collection_stats(collection_name=self._name)
        result = {stat.key: stat.value for stat in stats}
        result["row_count"] = int(result["row_count"])
        return result["row_count"]

we find conn.flush in above code is error.

Continue to trace:
   def flush(self, collection_names: list, timeout=None, **kwargs):
        if collection_names in (None, []) or not isinstance(collection_names, list):
            raise ParamError("Collection name list can not be None or empty")

        for name in collection_names:
            check_pass_param(collection_name=name)

        request = Prepare.flush_param(collection_names)
        future = self._stub.Flush.future(request, timeout=timeout)
        response = future.result()
        if response.status.error_code != 0:
            raise MilvusException(response.status.error_code, response.status.reason)

        def _check():
            for collection_name in collection_names:
                segment_ids = future.result().coll_segIDs[collection_name].data
                print(segment_ids)
                self._wait_for_flushed(segment_ids)

        if kwargs.get("_async", False):
            flush_future = FlushFuture(future)
            flush_future.add_callback(_check)

            user_cb = kwargs.get("_callback", None)
            if user_cb:
                flush_future.add_callback(user_cb)

            return flush_future
        # we found _check is error
        _check()

in above code, we find _check() is error, and in _check() function,  it will stacked in self._wait_for_flushed(segment_ids)

And we continue to trace:

    def _wait_for_flushed(self, segment_ids, timeout=None, **kwargs):
        flush_ret = False
        while not flush_ret:
            print(segment_ids)
            flush_ret = self.get_flush_state(segment_ids, timeout=timeout, **kwargs)
            print(flush_ret)
            if not flush_ret:
                time.sleep(0.5)

self.get_flush_state  output False.

Continue:
    @retry_on_rpc_failure()
    def get_flush_state(self, segment_ids, timeout=None, **kwargs):
        req = Prepare.get_flush_state_request(segment_ids)
        future = self._stub.GetFlushState.future(req, timeout=timeout)
        print(future)
        response = future.result()
        print(response)
        status = response.status
        if status.error_code == 0:
            return response.flushed  # todo: A wrapper class of PersistentSegmentInfo
        raise MilvusException(status.error_code, status.reason)

So at last: it located at  self._stub.GetFlushState.future

### Expected Behavior

How to fix this error

**Comment by yanliang567** [comment]
@jaloveapple it seems that you are running pymilvus is 2.1.1 on milvus 2.0, which there could be some compatibility issue. Could you please retry on latest milvus 2.2.5 and pymilvus 2.2.5?

/assign @jaloveapple 
/unassign
