### ISSUE TITLE
[Bug]: index doesn't exist, collectionID 440870237207735284

### ISSUE THREAD

**Issue by lisong888** [milvus-io/milvus#23482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.5
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.5
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I encountered an error loading storage using loadCollection()

import io.milvus.param.*;

LoadCollectionParam param = LoadCollectionParam.newBuilder()
        .withCollectionName(collectionName)
        .withReplicaNumber(2)
        .withSyncLoad(Boolean.TRUE)
        .withSyncLoadWaitingInterval(500L)
        .withSyncLoadWaitingTimeout(30L)
        .build();
R<RpcStatus> response = client.loadCollection(param);
if (response.getStatus() != R.Status.Success.getCode()) {
    System.out.println(response.getMessage());
}

**Comment by xiaofan-luan** [comment]
hi lisong, you will need to create collection before load.
It's usually:
1. create collection
2. crete index
3. load
4. search

**Comment by lisong888** [comment]
Why didn't the previous layout need to create an index? Version 2.2.5 requires this: create collection retrieve index - to load

**Comment by yanliang567** [comment]
/assign @lisong888 
please retry to load the collection after index created.

/unassign

**Comment by tinswzy** [comment]
milvusdb/milvus:v2.2.11
if no index， hello_milvus.load() encounter exception：”code=1, message=index doesn't exist, collectionID xxx“
my question is:  Why does a collection have to have an index？

**Comment by xiaofan-luan** [comment]
> > 
> 
> every collection has to create a index. You need to do create index before create collection



> > 
> 
> every collection has to create a index. You need to do create index before create collection

This is by design

**Comment by tinswzy** [comment]
> > > 
> > 
> > 
> > every collection has to create a index. You need to do create index before create collection
> 
> > > 
> > 
> > 
> > every collection has to create a index. You need to do create index before create collection
> 
> This is by design

Thanks for your reply
