### ISSUE TITLE
[Bug]: I feel very sad，neither can I use milvus grafana 

### ISSUE THREAD

**Issue by qilaijun101** [milvus-io/milvus#23495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.5
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS): container
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I can't use grafana by 9.4.3
![image](https://user-images.githubusercontent.com/14890813/232710581-ebdd7ce6-c498-48c1-9c31-f60c60d5f2ce.png)

failed to upgrade legacy queries Datasource prometheus was not found

but I can get data by Prometheus explore
![image](https://user-images.githubusercontent.com/14890813/232710910-6732d813-5a97-45d9-bbc6-47e0bd21c988.png)

### Expected Behavior

the Garanfa can display the milvus infomation

### Steps To Reproduce

```markdown
no
```

### Milvus Log

failed to upgrade legacy queries Datasource prometheus was not found

### Anything else?

no

**Comment by yanliang567** [comment]
/assign @locustbaby 
could you please help on this?

/unassign

**Comment by qilaijun101** [comment]
the /unassign  put the back of  the Prometheus url ?

**Comment by qilaijun101** [comment]
Can you give me a complete example?

**Comment by locustbaby** [comment]
Hi @qilaijun101 , May I know how you install the milvus in your cluster?
Could you please check the labels of the milvus' deployment whether have the label `app_kubernetes_io_name`

**Comment by qilaijun101** [comment]
> Hi @qilaijun101 , May I know how you install the milvus in your cluster? Could you please check the labels of the milvus' deployment whether have the label `app_kubernetes_io_name`

install command:
helm install my-milvus milvus/milvus --version 4.0.14
upgrad command:
helm upgrade  my-milvus milvus/milvus --version 4.0.14 --set metrics.serviceMonitor.enabled=true

use Promethus explore 
milvus_querynode_collection_num{instance="my-milvus-querynode:9091",node_id="3"}

![image](https://user-images.githubusercontent.com/14890813/232743967-b1ffa908-588d-49f5-bfef-979d73cf34d1.png)

**Comment by qilaijun101** [comment]
![image](https://user-images.githubusercontent.com/14890813/232744763-8bae5bf7-c1c8-4ecc-a332-c4ceb0c99410.png)

**Comment by qilaijun101** [comment]
I feel will not need the app_kubernetes_io_name and namespace and the app_kubernetes_io_instance will use instance replace

@locustbaby

**Comment by locustbaby** [comment]
> I think i will not need the app_kubernetes_io_name and namespace and the app_kubernetes_io_instance will use instance replace
> 
> @locustbaby

That's weird cause our Servicemonitor will scrape those labels ,such as`app_kubernetes_io_name`,`app_kubernetes_io_instance`

**Comment by qilaijun101** [comment]
Could it be that my Prometheus is misconfigured?    or is it possible to have remote conference support?

> > I think i will not need the app_kubernetes_io_name and namespace and the app_kubernetes_io_instance will use instance replace
> > @locustbaby
> 
> That's weird cause our Servicemonitor will scrape those labels ,such as`app_kubernetes_io_name`,`app_kubernetes_io_instance`

**Comment by locustbaby** [comment]
> Could it be that my Prometheus is misconfigured? or is it possible to have remote conference support?
> 
> > > I think i will not need the app_kubernetes_io_name and namespace and the app_kubernetes_io_instance will use instance replace
> > > @locustbaby
> > 
> > 
> > That's weird cause our Servicemonitor will scrape those labels ,such as`app_kubernetes_io_name`,`app_kubernetes_io_instance`

Do you use the Prometheus operator to collect metrics? or static config

**Comment by qilaijun101** [comment]
> 



> > Could it be that my Prometheus is misconfigured? or is it possible to have remote conference support?
> > > > I think i will not need the app_kubernetes_io_name and namespace and the app_kubernetes_io_instance will use instance replace
> > > > @locustbaby
> > > 
> > > 
> > > That's weird cause our Servicemonitor will scrape those labels ,such as`app_kubernetes_io_name`,`app_kubernetes_io_instance`
> 
> Do you use the Prometheus operator to collect metrics? or static config

I use static config to collect metrics, for example 

global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'default_my-milvus_my-milvus-rootcoord'
    static_configs:
      - targets: [
        'my-milvus-rootcoord:9091'
      ]global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'default_my-milvus_my-milvus-rootcoord'
    static_configs:
      - targets: [
        'my-milvus-rootcoord:9091'
      ]
  - job_name: 'default_my-milvus_my-milvus-querynode'
    static_configs:
      - targets: [
        'my-milvus-querynode:9091'
      ]
  - job_name: 'default_my-milvus_my-milvus-querycoord'
    static_configs:
      - targets: [
        'my-milvus-indexnode:9091'
      ]
  - job_name: 'default_my-milvus_my-milvus-proxy'
    static_configs:
      - targets: [
        'my-milvus-proxy:9091'
      ]
  - job_name: 'default_my-milvus_my-milvus-indexnode'
    static_configs:
      - targets: [
        'my-milvus-indexnode:9091'
      ]
  - job_name: 'default_my-milvus_my-milvus-indexcoord'
    static_configs:
      - targets: [
        'my-milvus-indexcoord:9091'
      ]
  - job_name: 'default_my-milvus_my-milvus-datanode'
    static_configs:
      - targets: [
        'my-milvus-datanode:9091'
      ]
  - job_name: 'default_my-milvus_my-milvus-datacoord'
    static_configs:
      - targets: [
        'my-milvus-datacoord:9091'
      ]

  - job_name: 'default_my-milvus_my-milvus-querynode'
    static_configs:
      - targets: [
        'my-milvus-querynode:9091'
      ]
  - job_name: 'default_my-milvus_my-milvus-querycoord'
    static_configs:
      - targets: [
        'my-milvus-indexnode:9091'
      ]
  - job_name: 'default_my-milvus_my-milvus-proxy'
    static_configs:
      - targets: [
        'my-milvus-proxy:9091'
      ]
  - job_name: 'default_my-milvus_my-milvus-indexnode'
    static_configs:
      - targets: [
        'my-milvus-indexnode:9091'
      ]
  - job_name: 'default_my-milvus_my-milvus-indexcoord'
    static_configs:
      - targets: [
        'my-milvus-indexcoord:9091'
      ]
  - job_name: 'default_my-milvus_my-milvus-datanode'
    static_configs:
      - targets: [
        'my-milvus-datanode:9091'
      ]
  - job_name: 'default_my-milvus_my-milvus-datacoord'
    static_configs:
      - targets: [
        'my-milvus-datacoord:9091'
      ]

**Comment by qilaijun101** [comment]
> May I know something about how your Prometheus scrape metrics? As our [charts](https://github.com/milvus-io/milvus-helm/blob/master/charts/milvus/templates/servicemonitor.yaml#:~:text=matchLabels%22%20.%20%7C%20indent%206%20%7D%7D-,targetLabels,-%3A),there should be some labels in metrics
> 
> Could you please get servicemonitor's yaml for me?

I just get the servicemonitor is running，but i can not find yml file

**Comment by locustbaby** [comment]
Solved.
Our helm uses `Prometheus Operator` as default, docs [here](https://milvus.io/docs/monitor.md#Monitor-metrics-with-Prometheus).
