### ISSUE TITLE
[FEATURE] Set the default value of gpu_cache_capacity smaller

### ISSUE THREAD

**Issue by Yukikaze-CZR** [milvus-io/milvus#235]
**Is your feature request related to a problem? Please describe.**
Should Milvus set default value of gpu_cache_capacity smaller than 4 to reduce the likelihood of occurrence of 'Config check fail: Invalid gpu cache capacity: 4. Possible reason: cache_config.gpu_cache_capacity exceeds GPU memory.' ?

**Comment by cydrain** [comment]
You need adjust this parameter setting based on your hardware.
There is no "BEST" default value.

Close this issue.
