### ISSUE TITLE
Summer 2020 wiki

### ISSUE THREAD

**Issue by LovelyBuggies** [milvus-io/milvus#2350]
**What is your question?**

Hello milvus group,

I saw you are participating in the [Summer 2020](https://isrc.iscas.ac.cn/summer2020/#/organisations). I cannot find where are the project ideas yet. Can you tell me where they are or when they will be publicated?

**Comment by JinHai-CN** [comment]
Yeah, we are preparing the tasks, stay tune.

**Comment by LovelyBuggies** [comment]
Nice. i'll keep watching.
