### ISSUE TITLE
[Enhancement]:  Add a cache  purge  mechanism  for the local file of scalar data query fetching  from object store at Querynode

### ISSUE THREAD

**Issue by wg1026688210** [milvus-io/milvus#23500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Querynode will fetch the scalar file from object store when handling a scalar request . 
We need add a mechanism for purging the local file prevent local disk of Querynode  from being filled up

**Comment by xiaofan-luan** [comment]
> 

make sense. 
I thought the cache has a capacity limit, doesn't it take affect?
