### ISSUE TITLE
[Feature]: Implement logical partition keys

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#23553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

A lot of user for milvus right now are building Saas Service on top of LLM.

A very common use cases:

User has 100 million datas, but it is splited into 10000 workspaces. 

When search, only one or multiple of the work spaces is searched.

There are few ways we can support that:

1. Multiple collections -> Highly limited  by collection numbers, usually no more than a few thousand 
2. Partitions -> has a limit of 4096, and partition on current release is not fully stable.
3. Combination of collection and Partition -> might work, but with so many small segments, the load balance becomes extremely difficult 
4. Multi Collections/Partitions + Filtering -> Best so far, but we will still facing two the performance degrade if the hnsw filter ratio is small.

### Describe the solution you'd like.

I would like to introduce another level of abstract, partition key.

So when user create a collection
from pymilvus import CollectionSchema, FieldSchema, DataType
book_id = FieldSchema(
  name="book_id", 
  dtype=DataType.INT64, 
  is_primary=True, 
)
book_name = FieldSchema(
  name="book_name", 
  dtype=DataType.VARCHAR, 
  max_length=200,
)
book_group= FieldSchema(
  name="book_group", 
  dtype=DataType.VARCHAR, 
  max_length=200,
  **is_partition_key=true**,
  **partitions= 1024**
)
book_intro = FieldSchema(
  name="book_intro", 
  dtype=DataType.FLOAT_VECTOR, 
  dim=2
)
schema = CollectionSchema(
  fields=[book_id, book_name, book_group, book_intro], 
  description="Test book search"
)

So you will see book group is the parititon key, and the collection will create 1024 partitions by default.

When insert happens:
1. hash(book_group)%1024 to decide which segment should be written into
2. others are exactly same as current insert path.

When build index happens:
1. build small index group on each of the book group
2. if group < 1024 rows, no index is build
3. Store each of the index group into a index file.

When search:
1. User must specify a group of partition key when search (Performance may degrade if not specified)
2. Milvus first pick the correct segment to work with 
3. Then do scalar filtering on the segment based on partition keys and other filter conditions.
4. pick the valid the index group to search on(Either use index or Brute force search)

### Describe an alternate solution.

To be mentioned,
The collection with logical partition can not create or delete partitions dynamically

**Comment by lishq** [comment]
can a single data record only belong to one unique partition? For example, if the same data is stored in partition A, can it still be stored in partition B?
