### ISSUE TITLE
[Enhancement]: Support lazily creating dataCoord time tick channel

### ISSUE THREAD

**Issue by MrPresent-Han** [milvus-io/milvus#23574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

At present, the dataCoord time tick channel is created instantly when the datacoord starts, regardless of whether there are data node channels or not.

### Why is this needed?

In vdc environment, there are only 4 topics for 1Cu and many instances don't have any collections at all. So when there are many instances like this, topics resources will be wasted meaninglessly,

### Anything else?

This is temporary solution and will be removed when time tick channels are replaced by roc report

**Comment by xiaofan-luan** [comment]
I won't say that would be super important for now.
I will just wait for the timetick to be removed
