### ISSUE TITLE
[SDK]: Client remove the logic to fill in the default number of shard when create collection

### ISSUE THREAD

**Issue by czs007** [milvus-io/milvus#23578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

RT.

Since the default shard number will be filled in the server.

**Comment by czs007** [comment]
@XuanYang-cn @congqixia @yhmo @yelusion2

**Comment by yhmo** [comment]
https://github.com/milvus-io/milvus-sdk-java/pull/551
