### ISSUE TITLE
[Bug]: Resource Groups load collection error

### ISSUE THREAD

**Issue by lizhaohuigit1** [milvus-io/milvus#23582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.6
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus2.2.7
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Resource group list: ['__default_resource_group', 'rg1', 'rg2']
Resource group description: ResourceGroupInfo:
<name:rg1>,
<capacity:2>,
<num_available_node:2>,
<num_loaded_replica:{}>,
<num_outgoing_node:{}>,
<num_incoming_node:{}>
Resource group description: ResourceGroupInfo:
<name:rg2>,
<capacity:2>,
<num_available_node:2>,
<num_loaded_replica:{}>,
<num_outgoing_node:{}>,
<num_incoming_node:{}>
RPC error: [load_collection], <MilvusException: (code=1, message=failed to load collection, err=failed to spawn replica for collection[nodes not enough])>, <Time:{'RPC start': '2023-04-20 17:32:40.080220', 'RPC error': '2023-04-20 17:32:40.115087'}>
Traceback (most recent call last):
  File "/home/lizhaohui/milvus/test/resource_groups.py", line 19, in <module>
    collection.load(replica_number=2, _resource_group=resource_groups) 
  File "/home/lizhaohui/miniconda3/envs/milvus/lib/python3.9/site-packages/pymilvus/orm/collection.py", line 366, in load
    conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/home/lizhaohui/miniconda3/envs/milvus/lib/python3.9/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/home/lizhaohui/miniconda3/envs/milvus/lib/python3.9/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/home/lizhaohui/miniconda3/envs/milvus/lib/python3.9/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/home/lizhaohui/miniconda3/envs/milvus/lib/python3.9/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/home/lizhaohui/miniconda3/envs/milvus/lib/python3.9/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/home/lizhaohui/miniconda3/envs/milvus/lib/python3.9/site-packages/pymilvus/client/grpc_handler.py", line 672, in load_collection
    raise MilvusException(response.error_code, response.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=failed to load collection, err=failed to spawn replica for collection[nodes not enough])>

### Expected Behavior

success load collection

### Steps To Reproduce

```markdown
my code
`from pymilvus import utility,connections,Collection
connections.connect(
  alias="default", 
  host='localhost', 
  port='19530'
)
rgs = utility.list_resource_groups(using='default')
print(f"Resource group list: {rgs}")
info = utility.describe_resource_group('rg1', using="default")
print(f"Resource group description: {info}")
info = utility.describe_resource_group('rg2', using="default")
print(f"Resource group description: {info}")

collection = Collection('intent_223_create_index_last_nlist_2048')

# collection.load(replica_number=2)

resource_groups = ['rg1']#,'rg2','rg3','rg4']
collection.load(replica_number=2, _resource_group=resource_groups) 
print("load 成功")`
```

### Milvus Log

[logs.txt](https://github.com/milvus-io/milvus/files/11285093/logs.txt)

### Anything else?

None

**Comment by xiaofan-luan** [comment]
Seems that rg1 takes 2 nodes and rg2 failed to load

**Comment by xiaofan-luan** [comment]
try release and load again should solve the problem temporarily.

@weiliu1031 is working on solving this issue

**Comment by yanliang567** [comment]
@lizhaohuigit1 could you please retry release the collection first as suggested above? for now, milvus does not support dynamically update the replicas or resource groups.

/unassign

**Comment by yanliang567** [comment]
if it does not help, please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation.

**Comment by lizhaohuigit1** [comment]
> if it does not help, please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation.

After I released it, I still encountered this issue while loading. I am Milvus deployed by Docker, and this script is for K8S. Do you have a script for Docker to export logs

**Comment by JackLCL** [comment]
@lizhaohuigit1 
![image](https://user-images.githubusercontent.com/53512883/233558740-72daa68a-eb9e-43ee-a9d0-f14c0364f727.png)
You can use "docker-compose logs > milvus.log" to export logs from docker.

**Comment by weiliu1031** [comment]
@lizhaohuigit1 any progress here for logs ?
