### ISSUE TITLE
[Bug]: Test cases hang after pulsar pod failure chaos test 

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#23591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230420-66cd15f7 
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/233529937-8a160ca9-a738-476e-8e0b-e3ae93e860ad.png)

### Expected Behavior

all test cases passed

### Milvus Log

failed job: chaos-test-cron/3654
log:
[artifacts-pulsar-pod-failure-3654-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/11291898/artifacts-pulsar-pod-failure-3654-server-logs.tar.gz)
[artifacts-pulsar-pod-failure-3654-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11291899/artifacts-pulsar-pod-failure-3654-pytest-logs.tar.gz)

**Comment by jiaoew1991** [comment]
Blocked by tt
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/2297455/233823908-787ca009-62e0-479c-a609-f22b808987fb.png">
