### ISSUE TITLE
[FEATURE] Reduce milvus docker image size

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#236]
**Is your feature request related to a problem? Please describe.**
I wish the milvus docker image size reduce to less than 1GB

**Describe the solution you'd like**
The milvus docker images is about 3.3GB, it is too large. We should not build unittest program into docker. Each unittest program is about 250MB, totally there 10 unittest programs in docker image, we need to remove them.

**Comment by ZhifengZhang-CN** [comment]
Duplicate of #251

**Comment by ZhifengZhang-CN** [comment]
Done
