### ISSUE TITLE
[Bug]: The CPU usage of two leader query nodes is high.

### ISSUE THREAD

**Issue by linggong2023** [milvus-io/milvus#23616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

[Bug]: The CPU usage of two leader query nodes is high.

**Comment by linggong2023** [comment]
[bw_etcd_ALL.230423-070110.bak.gz](https://github.com/milvus-io/milvus/files/11303044/bw_etcd_ALL.230423-070110.bak.gz)

**Comment by Cheung7788** [comment]
https://drive.google.com/file/d/11f9NpSjpxriPlKU4F-EN0pKs0yWrs6GG/view?usp=share_link

**Comment by yanliang567** [comment]
sounds reasonable for current design.
@congqixia any comments?

/assign @congqixia 
/unassign

**Comment by congqixia** [comment]
It might be a known issue in which handoff might blocks
Could you please execute `show segment-loaded-grpc` command with latest birdwatcher to check any growing segments on these two querynode?
@linggong2023

**Comment by congqixia** [comment]
These segment distribution is fetch via GRPC call online and cannot be retrieved from etcd backup

**Comment by linggong2023** [comment]
If we upgrade to 2.2.6, can it fix that issue?

**Comment by linggong2023** [comment]
Milvus(by-dev) > show segment-loaded-grpc
===========
ServerID 15
SegmentID: 440078454757956394 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_0_440078454477555906v0
SegmentID: 440078454758179938 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_1_440078454477555906v1
SegmentID: 440078454758165298 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_1_440078454477555906v1
SegmentID: 440078454757958213 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_0_440078454477555906v0
Sealed segments number: 4
===========
ServerID 16
SegmentID: 440078454758166367 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_0_440078454477555906v0
SegmentID: 440078454758162410 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_1_440078454477555906v1
SegmentID: 440078454758168201 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_0_440078454477555906v0
SegmentID: 440078454757955331 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_0_440078454477555906v0
Sealed segments number: 4
===========
ServerID 17
SegmentID: 440078454757956562 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_0_440078454477555906v0
SegmentID: 440078454757959812 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_1_440078454477555906v1
SegmentID: 440078454757957040 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_0_440078454477555906v0
Sealed segments number: 3
===========
ServerID 18
SegmentID: 440078454758164199 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_1_440078454477555906v1
SegmentID: 440078454758177492 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_1_440078454477555906v1
SegmentID: 440078454758164972 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_1_440078454477555906v1
SegmentID: 440078454758168121 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_0_440078454477555906v0
Sealed segments number: 4
===========
ServerID 19
SegmentID: 440078454758165812 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_0_440078454477555906v0
SegmentID: 440078454758181053 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_1_440078454477555906v1
SegmentID: 440078454757955345 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_0_440078454477555906v0
SegmentID: 440078454758167432 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_0_440078454477555906v0
Sealed segments number: 4
===========
ServerID 20
Channel by-dev-rootcoord-dml_0_440078454477555906v0, collection: 440078454477555906, version 1680078138006206984
Leader view for channel: by-dev-rootcoord-dml_0_440078454477555906v0
Growing segments number: 125 , ids: [440078454848192771 440078454859973860 440078454764128181 440078454793291024 440078454853163989 440078454859985136 440078454862960296 440078454791988702 440078454829283452 440078454803446994 440078454809526619 440078454847995466 440078454898382206 440078454906022227 440078454776640622 440078454779326694 440078454819456903 440078454847278079 440078454847981399 440078454886076418 440078454893836336 440078454763800210 440078454764948509 440078454827854219 440078454848186125 440078454776734094 440078454821447660 440078454793178906 440078454797458128 440078454854014133 440078454858109514 440078454862806188 440078454810668669 440078454842059330 440078454804164705 440078454815462696 440078454884964674 440078454893319495 440078454909332416 440078454771495616 440078454771569495 440078454786122138 440078454817084969 440078454809543929 440078454815976431 440078454779367318 440078454798132275 440078454811187995 440078454770893413 440078454771001877 440078454858977360 440078454898381436 440078454906023023 440078454908373637 440078454770287934 440078454774810962 440078454819553966 440078454836804701 440078454863249217 440078454876868241 440078454909209459 440078454780346897 440078454798130571 440078454886139697 440078454841526937 440078454854293857 440078454760168313 440078454827858106 440078454836765962 440078454757955444 440078454823397864 440078454870286723 440078454909080458 440078454757955469 440078454828708470 440078454864147993 440078454885406938 440078454903387538 440078454796615434 440078454816987373 440078454847265103 440078454871254779 440078454902464538 440078454909332324 440078454854314223 440078454863367370 440078454842124833 440078454803769316 440078454828252175 440078454835349832 440078454785882364 440078454791979728 440078454876441532 440078454841114339 440078454847680016 440078454829270414 440078454903616270 440078454776543367 440078454804185235 440078454811255543 440078454871139183 440078454902442540 440078454780405282 440078454786879776 440078454796577979 440078454841344864 440078454903566239 440078454760168276 440078454760589843 440078454770878159 440078454835891895 440078454853506725 440078454869653737 440078454764280442 440078454764955947 440078454785901882 440078454853171112 440078454760585874 440078454775253490 440078454864230776 440078454869647728 440078454786820820 440078454858059664 440078454821496876 440078454854145518]
SegmentID: 440078454758182387 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_1_440078454477555906v1
SegmentID: 440078454758172144 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_1_440078454477555906v1
SegmentID: 440078454758163594 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_1_440078454477555906v1
SegmentID: 440078454758166014 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_0_440078454477555906v0
Sealed segments number: 4
===========
ServerID 21
Channel by-dev-rootcoord-dml_1_440078454477555906v1, collection: 440078454477555906, version 1680078138030733157
Leader view for channel: by-dev-rootcoord-dml_1_440078454477555906v1
Growing segments number: 125 , ids: [440078454797458098 440078454829270389 440078454893319479 440078454898381318 440078454770893386 440078454786122090 440078454853171117 440078454780346918 440078454836765923 440078454863249156 440078454902464581 440078454835891873 440078454909080498 440078454847278112 440078454864268106 440078454893836455 440078454908373583 440078454909332168 440078454779324483 440078454809437068 440078454785878114 440078454811255531 440078454835444869 440078454836804724 440078454906022159 440078454770287837 440078454884754939 440078454804184736 440078454829283471 440078454847981430 440078454804164724 440078454791988752 440078454842124832 440078454859973890 440078454776543395 440078454776734060 440078454779367367 440078454847995504 440078454876441531 440078454876868240 440078454764128151 440078454847680019 440078454871139162 440078454817084945 440078454771495599 440078454776640607 440078454803421098 440078454815976450 440078454823397769 440078454848192743 440078454853091724 440078454763800209 440078454853506726 440078454764280395 440078454771001902 440078454780405309 440078454809543932 440078454906023031 440078454757955491 440078454775248014 440078454842059338 440078454848186085 440078454854145554 440078454898381536 440078454764948486 440078454810668668 440078454828252251 440078454796615575 440078454793291014 440078454859985100 440078454903616288 440078454791979708 440078454803769355 440078454811187975 440078454854293827 440078454760168277 440078454757955443 440078454858059750 440078454862951464 440078454869653663 440078454909213492 440078454854314168 440078454841114375 440078454870286761 440078454771569464 440078454871254772 440078454863461916 440078454819456904 440078454864147962 440078454760168484 440078454869650056 440078454827852332 440078454760585873 440078454819553982 440078454903387589 440078454785928310 440078454793178907 440078454798130520 440078454828708493 440078454884703182 440078454903566286 440078454764955976 440078454886139694 440078454815462735 440078454841345346 440078454841526977 440078454847264863 440078454858977351 440078454774811052 440078454786879859 440078454821496955 440078454902442539 440078454909332222 440078454786820857 440078454770878166 440078454796577867 440078454798132272 440078454821447695 440078454827858085 440078454862960299 440078454760589844 440078454854014124 440078454858109472 440078454886076419 440078454816987335]
SegmentID: 440078454758167936 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_0_440078454477555906v0
SegmentID: 440078454758179237 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_1_440078454477555906v1
SegmentID: 440078454758173403 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_1_440078454477555906v1
Sealed segments number: 3
===========
ServerID 24
SegmentID: 440078454757959810 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_1_440078454477555906v1
SegmentID: 440078454758167065 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_0_440078454477555906v0
SegmentID: 440078454758181784 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_0_440078454477555906v0
SegmentID: 440078454758164511 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_1_440078454477555906v1
Sealed segments number: 4
===========
ServerID 25
SegmentID: 440078454758163835 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_1_440078454477555906v1
SegmentID: 440078454758170317 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_1_440078454477555906v1
SegmentID: 440078454758162408 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_1_440078454477555906v1
SegmentID: 440078454758169604 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_0_440078454477555906v0
Sealed segments number: 4
===========
ServerID 26
SegmentID: 440078454757955922 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_0_440078454477555906v0
SegmentID: 440078454758182386 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_1_440078454477555906v1
SegmentID: 440078454758182966 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_1_440078454477555906v1
SegmentID: 440078454757959219 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_0_440078454477555906v0
Sealed segments number: 4
===========
ServerID 27
SegmentID: 440078454758181785 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_0_440078454477555906v0
SegmentID: 440078454757955924 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_0_440078454477555906v0
SegmentID: 440078454757957032 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_0_440078454477555906v0
Sealed segments number: 3
===========
ServerID 28
SegmentID: 440078454758166760 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_0_440078454477555906v0
SegmentID: 440078454757958211 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_0_440078454477555906v0
SegmentID: 440078454758181596 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_0_440078454477555906v0
Sealed segments number: 3
===========
ServerID 29
SegmentID: 440078454758178561 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_1_440078454477555906v1
Sealed segments number: 1
===========
ServerID 30
SegmentID: 440078454758179057 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_1_440078454477555906v1
SegmentID: 440078454758181707 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_0_440078454477555906v0
SegmentID: 440078454758175979 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_1_440078454477555906v1
Sealed segments number: 3
===========
ServerID 5
SegmentID: 440078454758181185 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_1_440078454477555906v1
SegmentID: 440078454758161476 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_1_440078454477555906v1
SegmentID: 440078454758167695 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_0_440078454477555906v0
SegmentID: 440078454758166086 CollectionID: 440078454477555906 Channel: by-dev-rootcoord-dml_0_440078454477555906v0
Sealed segments number: 4

**Comment by congqixia** [comment]
From the growing segments states, it could be assumed that the handoff is blocked in system. It's recommended to upgrade to higher version of Milvus to fix this problem

**Comment by xiaofan-luan** [comment]
1. Add skip growing for now may help
2. we are working on growing segment index to help on this

**Comment by changhong52** [comment]
@xiaofan-luan @congqixia why the handoff is blocked in system?
