### ISSUE TITLE
[Bug]: 2.3 proxy is not compatible with 2.2.x querynode

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#23619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.0 beta & 2.2.x
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Query request from proxy(2.2.x) to 2.3.0beta querynode will cause panicking

### Expected Behavior

No panicking or prevent query request from 2.2.x proxy to 2.3 qn

**Comment by congqixia** [comment]
In master branch the search plan is structured like
https://github.com/milvus-io/milvus/blob/b7cb34b9667f7d22366e4ccc3d930ed1be81126d/internal/parser/planparserv2/plan_parser_v2.go#L78-L84
while 2.2.x plan is
https://github.com/milvus-io/milvus/blob/5f96f4bbfd9de15fa21e8b678a7ff82cc560a378/internal/parser/planparserv2/plan_parser_v2.go#L78-L83

**Comment by longjiquan** [comment]
https://github.com/milvus-io/milvus/blob/04364129fb39d09229177672e3b41a1be85df70b/internal/core/src/query/PlanProto.cpp#L166-L175

**Comment by longjiquan** [comment]
This case won't make querynode panic, the query just got error at line:168.

**Comment by congqixia** [comment]
Confirmed.
