### ISSUE TITLE
[Bug]: compaction scenarios use more memory and trigger "deny to write"

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#23621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20230421-5f96f4bb
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task : fouramf-stable-1682190000 , id : 7
case_name: test_concurrent_locust_hnsw_compaction_standalone

server:
```
fouramf-stable-1682190000-7-etcd-0                                1/1     Running     0                 2m58s   10.104.16.202   4am-node21   <none>           <none>
fouramf-stable-1682190000-7-milvus-standalone-5687567647-lpkk9    1/1     Running     0                 3m      10.104.22.32    4am-node26   <none>           <none>
fouramf-stable-1682190000-7-minio-78f699bc68-8wzgk                1/1     Running     0                 3m      10.104.24.187   4am-node29   <none>           <none>
```
client pod : fouramf-stable-1682190000-3033084186
client error log:
![image](https://user-images.githubusercontent.com/48523564/233825838-43cd3609-79f5-46b3-9fd9-5b981eca0c9b.png)

memory  uasge:
![image](https://user-images.githubusercontent.com/48523564/233825349-3f203802-d07d-4afb-a4d9-e825d627af6a.png)

Same case, previous image: 2.2.6-20230413-d0e87113  memory use: 

![image](https://user-images.githubusercontent.com/48523564/233825609-462eebee-a180-4ec3-a5ca-223e43fb8e97.png)

### Expected Behavior

This case memory usage should be less than 9.3 G, like this:
![image](https://user-images.githubusercontent.com/48523564/233825609-462eebee-a180-4ec3-a5ca-223e43fb8e97.png)

### Steps To Reproduce

```markdown
1. create a collection or use an existing collection
        2. build index on vector column   --> hnsw
        3. insert a certain number of vectors
        4. flush collection
        5. build index on vector column with the same parameters
        6. build index on on scalars column or not
        7. count the total number of rows
        8. load collection
        9. perform concurrent operations [load, query, （insert、delete、flush）, search]
        10. clean all collections or not
```

**Comment by elstic** [comment]
#### [cluster] 

server:
```
fouramf-stable-1682190000-8-etcd-0                                1/1     Running     0                 6m51s   10.104.16.203   4am-node21   <none>           <none>
fouramf-stable-1682190000-8-etcd-1                                1/1     Running     0                 6m50s   10.104.18.238   4am-node25   <none>           <none>
fouramf-stable-1682190000-8-etcd-2                                1/1     Running     0                 6m50s   10.104.15.127   4am-node20   <none>           <none>
fouramf-stable-1682190000-8-milvus-datacoord-99ddfdf47-z7cww      1/1     Running     1 (2m51s ago)     6m51s   10.104.18.228   4am-node25   <none>           <none>
fouramf-stable-1682190000-8-milvus-datanode-656b945b6c-t55nz      1/1     Running     1 (2m52s ago)     6m53s   10.104.24.184   4am-node29   <none>           <none>
fouramf-stable-1682190000-8-milvus-indexcoord-6f5ccdf8cc-78vs9    1/1     Running     1 (2m51s ago)     6m52s   10.104.6.247    4am-node13   <none>           <none>
fouramf-stable-1682190000-8-milvus-indexnode-6c6f668bf6-th4bs     1/1     Running     0                 6m52s   10.104.6.249    4am-node13   <none>           <none>
fouramf-stable-1682190000-8-milvus-proxy-6f74db66f9-rx8jv         1/1     Running     1 (2m51s ago)     6m51s   10.104.16.185   4am-node21   <none>           <none>
fouramf-stable-1682190000-8-milvus-querycoord-6df8dc9874-nv5sb    1/1     Running     1 (2m51s ago)     6m52s   10.104.18.229   4am-node25   <none>           <none>
fouramf-stable-1682190000-8-milvus-querynode-598447856b-zkkrc     1/1     Running     0                 6m52s   10.104.19.222   4am-node28   <none>           <none>
fouramf-stable-1682190000-8-milvus-rootcoord-845c8966c4-2kbfr     1/1     Running     1 (2m52s ago)     6m53s   10.104.24.183   4am-node29   <none>           <none>
fouramf-stable-1682190000-8-minio-0                               1/1     Running     0                 6m49s   10.104.16.208   4am-node21   <none>           <none>
fouramf-stable-1682190000-8-minio-1                               1/1     Running     0                 6m48s   10.104.5.70     4am-node12   <none>           <none>
fouramf-stable-1682190000-8-minio-2                               1/1     Running     0                 6m48s   10.104.23.83    4am-node27   <none>           <none>
fouramf-stable-1682190000-8-minio-3                               1/1     Running     0                 6m47s   10.104.15.130   4am-node20   <none>           <none>
fouramf-stable-1682190000-8-pulsar-bookie-0                       1/1     Running     0                 6m50s   10.104.15.128   4am-node20   <none>           <none>
fouramf-stable-1682190000-8-pulsar-bookie-1                       1/1     Running     0                 6m49s   10.104.16.209   4am-node21   <none>           <none>
fouramf-stable-1682190000-8-pulsar-bookie-2                       1/1     Running     0                 6m48s   10.104.23.81    4am-node27   <none>           <none>
fouramf-stable-1682190000-8-pulsar-bookie-init-nvw7l              0/1     Completed   0                 6m53s   10.104.6.245    4am-node13   <none>           <none>
fouramf-stable-1682190000-8-pulsar-broker-0                       1/1     Running     0                 6m51s   10.104.23.62    4am-node27   <none>           <none>
fouramf-stable-1682190000-8-pulsar-proxy-0                        1/1     Running     0                 6m50s   10.104.16.188   4am-node21   <none>           <none>
fouramf-stable-1682190000-8-pulsar-pulsar-init-mzs8w              0/1     Completed   0                 6m53s   10.104.24.182   4am-node29   <none>           <none>
fouramf-stable-1682190000-8-pulsar-recovery-0                     1/1     Running     0                 6m51s   10.104.18.230   4am-node25   <none>           <none>
fouramf-stable-1682190000-8-pulsar-zookeeper-0                    1/1     Running     0                 6m50s   10.104.18.239   4am-node25   <none>           <none>
fouramf-stable-1682190000-8-pulsar-zookeeper-1                    1/1     Running     0                 4m43s   10.104.1.125    4am-node10   <none>           <none>
fouramf-stable-1682190000-8-pulsar-zookeeper-2                    1/1     Running     0                 3m13s   10.104.24.201   4am-node29   <none>           <none>
```
client : 
![image](https://user-images.githubusercontent.com/48523564/233825960-cfdfadf2-97a3-4b6f-a329-7026fc15c0b5.png)

mem usage:
![image](https://user-images.githubusercontent.com/48523564/233826019-a37e6093-a61d-4e85-a5cd-8acbf1dcd1eb.png)

**Comment by xiaofan-luan** [comment]
memory compaction takes seems to be huge

**Comment by MrPresent-Han** [comment]
the last lead segment request completed at 04:24, meaning that following sealed&&indexed segments cannot be loaded and matched growing segments cannot be released, resulting in memory constantly growing between 04:30 and 06:50.

**Comment by MrPresent-Han** [comment]
In this test case, all inserts are very small, usually containing only 1 row, meaning that the generated segment are all very small and will trigger compaction very frequently, considering one compaction circumstance:
SegA-->SegA'-->SegA''-->....., in these process, segA'' will inherit delBuf from all compactFrom segments, which means the checkPoint of SegA'' can be very early, resulting in querynode cannot release matched growing segments because channel cp is too early.
So I add one more sync_segment_policy: syncCPLagTooBehind to make sure if one segment's cp is too earlier than physical time, it will be sync instantly. 
test result as follows, qnode memory and growing segments are fluctuating under 9g with a cycle of 10min(default value)

<img width="1083" alt="截屏2023-05-04 19 19 46" src="https://user-images.githubusercontent.com/116052805/236189676-0c6e5073-d674-4aeb-af76-6ffcee35bed7.png">

**Comment by xiaofan-luan** [comment]
> 

But we did sync very 10 minutes right? That should be already good enough to ensure checkpoint is not too lag behind

**Comment by xiaofan-luan** [comment]
probably simply because compaction can not catch up with write? what if we can have multiple compaction happens concurrently?

**Comment by xiaofan-luan** [comment]
> In this test case, all inserts are very small, usually containing only 1 row, meaning that the generated segment are all very small and will trigger compaction very frequently, considering one compaction circumstance: SegA-->SegA'-->SegA''-->....., in these process, segA'' will inherit delBuf from all compactFrom segments, which means the checkPoint of SegA'' can be very early, resulting in querynode cannot release matched growing segments because channel cp is too early. So I add one more sync_segment_policy: syncCPLagTooBehind to make sure if one segment's cp is too earlier than physical time, it will be sync instantly. test result as follows, qnode memory and growing segments are fluctuating under 9g with a cycle of 10min(default value)
> 
> <img alt="截屏2023-05-04 19 19 46" width="1083" src="https://user-images.githubusercontent.com/116052805/236189676-0c6e5073-d674-4aeb-af76-6ffcee35bed7.png">

And there is a 

> In this test case, all inserts are very small, usually containing only 1 row, meaning that the generated segment are all very small and will trigger compaction very frequently, considering one compaction circumstance: SegA-->SegA'-->SegA''-->....., in these process, segA'' will inherit delBuf from all compactFrom segments, which means the checkPoint of SegA'' can be very early, resulting in querynode cannot release matched growing segments because channel cp is too early. So I add one more sync_segment_policy: syncCPLagTooBehind to make sure if one segment's cp is too earlier than physical time, it will be sync instantly. test result as follows, qnode memory and growing segments are fluctuating under 9g with a cycle of 10min(default value)
> 
> <img alt="截屏2023-05-04 19 19 46" width="1083" src="https://user-images.githubusercontent.com/116052805/236189676-0c6e5073-d674-4aeb-af76-6ffcee35bed7.png">

Is there a specific reason why segment  inherit delBuf don't flush? they should flush after 10 minutes right?

**Comment by MrPresent-Han** [comment]
@elstic I tried 2.2.0-20230621-bd75f4c3 in standalone mode and it turned that this problem has been fixed. Could you verify and decide whether this issue can be resolved or not?

https://argo-workflows.zilliz.cc/workflows/qa/fouramf-gdncn?tab=workflow&nodeId=fouramf-gdncn-2523503942&nodePanelView=containers

**Comment by elstic** [comment]
> @elstic I tried 2.2.0-20230621-bd75f4c3 in standalone mode and it turned that this problem has been fixed. Could you verify and decide whether this issue can be resolved or not?
> 
 
 
 Yes, it has been verified that the issue has been fixed. 
But please hide the intranet (argo) link
