### ISSUE TITLE
[Enhancement]: Issues with segcore c++ lib 

### ISSUE THREAD

**Issue by yiwangdr** [milvus-io/milvus#23639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

I created this issue based on my limited understanding of the codebase. Please correct me if I'm making mistakes here.

There are things we can improve on our C++ libs. Generally, the recent C++ code changes are much better than the legacy code. I guess a lot of the issues are from very early days.

I probably will separate this issue to more specific sub-issues as they may require a lot of efforts.

1. the code style looks not very consistent or can be improved. Some examples:

- An example of inconsistency is the input param, where I saw both pointers and references used across the libs ([example](https://github.com/milvus-io/milvus/blob/6b29a991a596e8eed37a7902f935e8202f0b0c52/internal/core/src/segcore/ConcurrentVector.cpp#L22-L23)). Please correct me if that's an intended behavior for good reasons. At high level, I would follow the google style: "Non-optional input parameters should usually be values or const references, while non-optional output and input/output parameters should usually be references (which cannot be null). "
A minor thing: if we have to use pointer as input param, let's check its nullptr case.

- Efficiency: unnecessary data copy ([example](https://github.com/milvus-io/milvus/blob/6b29a991a596e8eed37a7902f935e8202f0b0c52/internal/core/src/query/visitors/VerifyPlanNodeVisitor.cpp#L43))
- Efficiency: unnecessary pass-by-value ([example](https://github.com/milvus-io/milvus/blob/6b29a991a596e8eed37a7902f935e8202f0b0c52/internal/core/src/index/StringIndexMarisa.cpp#L164))

2. File names are .cpp, which I think should be .cc so that it's consistent with knowhere repo.

3. The unit test coverage is not as good as our golang code. Ideally, we should have x_test.cc for each x (x.h & x.cc)

### Why is this needed?

Improve our code quality and maintainability in the long run.

**Comment by xiaofan-luan** [comment]
Very detailed suggesi

> 

Totally agreed especially on the interface comment and the ut comment.
We should avoid using Raw ptr and take care about all the copys. Not sure how much effort there is to change to pointers, but at least make sure no extra copy and we should separate input and output params
