### ISSUE TITLE
[Bug]: Standalone GPU milvus cannot be deployed

### ISSUE THREAD

**Issue by 1041787154** [milvus-io/milvus#23641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:milvusdb/milvus:v2.3.0-gpu-beta
- Deployment mode(standalone or cluster):standalone 
- MQ type(rocksmq, pulsar or kafka):pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu 
- CPU/Memory: 
- GPU: NVIDIA Corporation Device 2236 (rev a1)
- Others:
```

### Current Behavior

When I was deploying the standalone GPU version of Milvus, an error occurred,Please refer to the connection for the specific code
![image](https://user-images.githubusercontent.com/15188273/233882530-e2ea726f-4e25-477c-85d7-3b2f02589506.png)

This is the yml file I am using
![image](https://user-images.githubusercontent.com/15188273/233882895-2864d5d9-9635-4584-b3d4-d57a502013b7.png)

**Comment by yanliang567** [comment]
@1041787154 for now, milvus can only use gpu 0, please double check that.
@liliu-z could you please help to take a look?

/assign @liliu-z 
/unassign

**Comment by 1041787154** [comment]
> 

![image](https://user-images.githubusercontent.com/15188273/233919057-6807eb3e-be7d-4138-85c5-77da65fa2efd.png)
Checked, I only have Gup 0 on my end, so it shouldn't be the problem

**Comment by 1041787154** [comment]
> @1041787154 for now, milvus can only use gpu 0, please double check that. @liliu-z could you please help to take a look?
> 
> /assign @liliu-z /unassign
![image](https://user-images.githubusercontent.com/15188273/233919547-95bc5bb9-3a62-4925-949b-62c4dce9b3bd.png)

Checked, I only have Gup 0 on my end, so it shouldn't be the problem

**Comment by 1041787154** [comment]
who can help me? thanks!!
