### ISSUE TITLE
[Enhancement]: Enhance Active-standby and other session operations

### ISSUE THREAD

**Issue by wayblink** [milvus-io/milvus#23668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

When we developed Active-standby first version. We never thought it would be used in standalone and rolling update. As the logic become complicated. We found the code become ugly and face some corner cases on cloud. I would like to enhance Active-standby logic and other session operations to make them robust and readable.

**Comment by xiaofan-luan** [comment]
good suggestion, let's do this

**Comment by xiaofan-luan** [comment]
kepp it
