### ISSUE TITLE
Reduce SQL execution times for collection contains lot of partitions

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#2366]
**Describe the bug**
Assume a collection has 1000 partitions, when user performs search action, milvus firstly get segments from meta by partition one by one, execute SQL statements like "SELECT segments from TableFiles where table_id=partition_id" for 1000 times. Each SQL statement costs about 1~2 milliseconds. The SQL statements could be bottleneck.

**Comment by del-zhenwu** [comment]
duplicated with #951?

**Comment by yhmo** [comment]
fixed by pr2383
1000 partiitons, each partition insert 100 vectors, MySQL backend,  time cost reduce from 11~17 seconds to 1~2 seconds

**Comment by yhmo** [comment]
fixed by pr2383 in 0.10.0 branch
