### ISSUE TITLE
[Bug]: collection or partition not loaded into memory when query

### ISSUE THREAD

**Issue by logidelic** [milvus-io/milvus#23669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 5ecec95
- Other info: Zilliz Cloud fully-managed Milvus service
- SDK version(e.g. pymilvus v2.0.0rc2): milvus2-sdk-node 2.2.4
```

### Current Behavior

- I run `collectionManager.loadCollection` for `collection1` which returns Success
- After success above, I run `dataManager.query` which yields (sporadically):

```
error_code: UnexpectedError
collection:collection1 or partition:[] not loaded into memory when query
```

### Expected Behavior

The collection was just loaded, so query souldn't error.

**Comment by yanliang567** [comment]
sounds like a zilliz cloud issue, for the sake of security and privacy, please contact to the support@zilliz.com, they will help you immediately. 

/assign @logidelic
