### ISSUE TITLE
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on 159.27.**.***:16812. Timeout)>

### ISSUE THREAD

**Issue by gg22mm** [milvus-io/milvus#23673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

#
![图片](https://user-images.githubusercontent.com/6648329/233967377-b93c1657-08ed-4747-880f-229839e2bd4b.png)

attu都可以登陆进来
![图片](https://user-images.githubusercontent.com/6648329/234150956-c068d854-6799-45ae-981c-ac119c4bf629.png)

![图片](https://user-images.githubusercontent.com/6648329/234150673-0d52c29d-535c-42f8-99e8-e5d3000263d4.png)

http://159.27.13.175:16814/
你的默认用户是root，密码是Milvus

#
but run:

from pymilvus import (
connections,
utility,
FieldSchema,
CollectionSchema,
DataType,
Collection,
)
connections.connect("default", host="159.27.13.175", port="16812", user='root', password='Milvus')

error:
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on 159.27.**.***:16812. Timeout)>
![图片](https://user-images.githubusercontent.com/6648329/234155476-77ea1102-c71f-48b0-9381-48fb44b47e53.png)

![图片](https://user-images.githubusercontent.com/6648329/233967546-e2213be1-376f-44d9-a368-0a35a3758218.png)

**Comment by gg22mm** [comment]
> try to connect port 19530 instead of 16812, if you did not customize the default configurations.
> 
> /assign @gg22mm /unassign

我们服务器是不能用19530 与 9091 端口的  /  Our server cannot use ports 19530 and 9091 。
我的自动义配置如下/My automatic configuration is as follows：

version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.6
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "16812:19530"
      - "16813:9091"
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvus


但是还是报错，不能改自定义端口吗/But still reporting an error, cannot I change the custom port ？

**Comment by yanliang567** [comment]
/assign @locustbaby 
could you please help on this?
/unassign

**Comment by XuanYang-cn** [comment]
Try to add  `secure=True` in connect()
```
connections.connect("default", host="159.27.13.175", port="16812", user='root', password='Milvus', secure=True)
```

**Comment by gg22mm** [comment]
> Try to add `secure=True` in connect()
> 
> ```
> connections.connect("default", host="159.27.13.175", port="16812", user='root', password='Milvus', secure=True)
> ```

还是报错，没有解决我的问题 / Still reporting an error, did not solve my problem 。
我怀疑是milvus-standalone的问题，进去docker中不能手动运行 / I suspect it's a problem with milvus standalone and cannot be manually run in the Docker。
![图片](https://user-images.githubusercontent.com/6648329/234523049-07a6bdf4-723c-4e80-a38c-368a8b09cd2f.png)

**Comment by locustbaby** [comment]
hi @gg22mm, actually the params of `connect` is the same as `Attu`
May I know where you installed your Milvus and Attu? Same In a k8s cluster?

**Comment by locustbaby** [comment]
@gg22mm  Oh, I saw the issue#5775, I test your milvus and it's worked for me, code as below
```
# hello_milvus.py demonstrates the basic operations of PyMilvus, a Python SDK of Milvus.
# 1. connect to Milvus
# 2. create collection
# 3. insert data
# 4. create index
# 5. search, query, and hybrid search on entities
# 6. delete entities by PK
# 7. drop collection
import time
import sys

import numpy as np
from pymilvus import (
    connections,
    utility,
    FieldSchema, CollectionSchema, DataType,
    Collection,
)

fmt = "\n=== {:30} ===\n"
search_latency_fmt = "search latency = {:.4f}s"
num_entities, dim = 3000, 8

#################################################################################
# 1. connect to Milvus
# Add a new connection alias `default` for Milvus server in `localhost:19530`
# Actually the "default" alias is a buildin in PyMilvus.
# If the address of Milvus is the same as `localhost:19530`, you can omit all
# parameters and call the method as: `connections.connect()`.
#
# Note: the `using` parameter of the following methods is default to "default".
print(fmt.format("start connecting to Milvus"))
connections.connect("default", host="159.27.13.175", port="16812", user='root', password='Milvus')


has = utility.has_collection("hello_milvus")
print(f"Does collection hello_milvus exist in Milvus: {has}")
sys.exit()
```

**Comment by gg22mm** [comment]
非常抱歉，同时非常感谢您的耐心回复，应该是我的环境问题，我在在aistudio中运行的。  我尝试在自己本地运行也是可以的，也不报错了。
I'm very sorry, and thank you very much for your patient response. It should be my environmental issue, and I am running it in AIStudio. I can also try running it locally on my own 。
