### ISSUE TITLE
[Bug]: Collection Creation INT64 error when trying to create VARCHAR as primary key

### ISSUE THREAD

**Issue by briconnelly** [milvus-io/milvus#23684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.6
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.2.7
- CPU/Memory: 16 GB
```

### Current Behavior

I am using the Question Answering System tutorial from the Milvus site/github.  https://github.com/towhee-io/examples/tree/main/nlp/question_answering

Here is the error: MilvusException: <MilvusException: (code=1, message=the data type of primary key should be int64)>

Here is the code I am running in a Jupyter dash: 
`def create_milvus_collection(collection_name, dim):
    if utility.has_collection(collection_name):
        utility.drop_collection(collection_name)
    
    fields = [
    FieldSchema(name='id', dtype=DataType.VARCHAR, description='ids',  max_length=500,  is_primary=True, auto_id=False),
    FieldSchema(name='embedding', dtype=DataType.FLOAT_VECTOR, descrition='embedding vectors', dim=dim)
    ]
    schema = CollectionSchema(fields=fields, description='reverse image search')
    collection = Collection(name=collection_name, schema=schema)

    # create IVF_FLAT index for collection.
    index_params = {
        'metric_type':'L2',
        'index_type':"IVF_FLAT",
        'params':{"nlist":2048}
    }
    collection.create_index(field_name="embedding", index_params=index_params)
    return collection
collection = create_milvus_collection('question_answer', 768)`

I have ensured I have the latest pymilvus and all dependent packages/docker image, but can't seem to get around this error.  Any help would be appreciated! 

### Expected Behavior

create collection with varchar as primary key

### Steps To Reproduce

```markdown
I am using the Question Answering System tutorial from the Milvus site/github.  https://github.com/towhee-io/examples/tree/main/nlp/question_answering

Have followed all steps for set up.
```

### Milvus Log

N/A

**Comment by yanliang567** [comment]
it does not reproduce to me with pymilvus 2.2.7. After checking the source code and error msg you met,  I doubt that you are not running the latest pymilvus. 
![image](https://user-images.githubusercontent.com/82361606/234198421-8cd84db0-d480-48f1-8514-0f5631e9cfe9.png)

/assign @briconnelly 
please double check the pymilvus version.
/unassign

**Comment by briconnelly** [comment]
<img width="366" alt="Screen Shot 2023-04-25 at 9 19 07 AM" src="https://user-images.githubusercontent.com/59710457/234324221-903b699c-4b85-4313-b4a9-b490840f4972.png">

here is my version. it appears to be latest.  i did try to convert the VARCHAR to INT64 as it suggests, but the process has not completed (hour + of processing). I'm stumped!

**Comment by yanliang567** [comment]
@briconnelly Mmm...could you please double check the milvus version you running? In the top of milvus pod log, you could see the milvus version as below:
![image](https://user-images.githubusercontent.com/82361606/234452334-61909860-b966-4c5f-b80c-9409e44c811d.png)

**Comment by briconnelly** [comment]
@yanliang567  okay i think i figured out why this is happening, i did have an old version of milvus from the docker container/image because I am running on a M1 that does not have linux/arm64/v8. i'll remedy this and hoping then it will work.  thanks for you help here.

**Comment by yanliang567** [comment]
great, feel free to let me know if you met any issues.
