### ISSUE TITLE
Support db data share between different milvus instances for read only mode

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#2369]
**Describe the bug**
We now can not support two or more different milvus instances share the same db data dir, caused by meta local.
But if the instances only do read operations, actually we should support.

**Steps/Code to reproduce behavior**

**Expected behavior**

**Environment details**

**Screenshots**

**Additional context**

**Comment by JinHai-CN** [comment]
Yes, one databases directory support multiple read node.

**Comment by scsven** [comment]
Supported yet.

**Comment by del-zhenwu** [comment]
mode: readonly
