### ISSUE TITLE
[Bug]: create connect

### ISSUE THREAD

**Issue by echo-initial** [milvus-io/milvus#23713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.4
- Deployment mode(standalone or cluster): standalone 
- MQ type(rocksmq, pulsar or kafka): RocksMQ
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.4
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Create a new connection before connecting

### Expected Behavior

Successfully connected

### Steps To Reproduce

```markdown
def addCon():
    connections.add_connection(
        default={"host": "100.64.139.90", "port": "19530"},
        tes={"host": HOST, "port": PORT},
        tes2={"host": HOST, "port": PORT, "user": USER, "password": PASSWORD}
    )
    print(connections.list_connections())
    print(connections.get_connection_addr("tes"))


def create_milvus_collection(cover):
    connections.connect(alias="tes", host=HOST, port=PORT)
    # connections.connect(alias="tes2", host=HOST, port=PORT, user=USER, password=PASSWORD)

    if utility.has_collection(COLLECTION_NAME):
        if cover:
            utility.drop_collection(COLLECTION_NAME)
        else:
            return

    fields = [
        FieldSchema(name='pk', dtype=DataType.INT64, description='主键', is_primary=True, auto_id=False),
        FieldSchema(name='vec', dtype=DataType.FLOAT_VECTOR, description='text vec', dim=DIM),
        FieldSchema(name='data', dtype=DataType.VARCHAR, description='data', max_length=500),
        FieldSchema(name='mysql_id', dtype=DataType.INT64, description='mysql主键id'),
        FieldSchema(name='k_id', dtype=DataType.INT64, description='k_id')
    ]

    schema = CollectionSchema(fields=fields, description='知识点分析')

    collection = Collection(name=COLLECTION_NAME, schema=schema)

    # create IVF_FLAT index for collection.
    index_params = {
        'metric_type': METRIC_TYPE,
        'index_type': INDEX_TYPE,
        'params': {"nlist": 2048}
    }

    collection.create_index(field_name='vec', index_params=index_params)


if __name__ == '__main__':
    addCon()

    create_milvus_collection(True)
```

### Milvus Log

    raise ConnectionNotExistException(message=ExceptionsMessage.ConnectFirst)
pymilvus.exceptions.ConnectionNotExistException: <ConnectionNotExistException: (code=1, message=should create connect first.)>

**Comment by yanliang567** [comment]
try this:
```
    host = '10.102.x.x'
    port = 19530
    connections.add_connection(default={"host": host, "port": port})
    connections.connect(alias='default')
    create_milvus_collection(True)
```

/assign @echo-initial 
/unassign

**Comment by echo-initial** [comment]
alias="default" can succeed, but changing other aliases will fail

**Comment by echo-initial** [comment]
@yanliang567

**Comment by huuson235** [comment]
Same issue, I want to connect to 2 different milvus server but only one default connection can be used!
@yanliang567

**Comment by yanliang567** [comment]
one connection can be pointed to only one milvus

**Comment by unanan** [comment]
same issue

> alias="default" can succeed, but changing other aliases will fail

**Comment by InkyZigi** [comment]
I was troubled by the same problem.
Then I trying like this, using param 'db_name' rather than 'alias':
`connections.connect(db_name='default')`

The reason can be found from the inside function: 
`def connect(
        self,
        alias: str = Config.MILVUS_CONN_ALIAS,
        user: str = "",
        password: str = "",
        db_name: str = "default",
        token: str = "",
        **kwargs,
    ) -> None: ......`

**Comment by yanliang567** [comment]
if you want to connect to 2 milvus cluster, you shall use different aliases, such as aliasA, aliasB, then calling every API with using=aliasX
1.connections.connect(alias="aliasA", host=hostA, port=portA)
2.connections.connect(alias="aliasB", host=hostB, port=portB)
3. utility.list_colection(using="aliasA")
4. utility.list_collections(using=aliasB)

**Comment by insist93** [comment]
> if you want to connect to 2 milvus cluster, you shall use different aliases, such as aliasA, aliasB, then calling every API with using=aliasX 1.connections.connect(alias="aliasA", host=hostA, port=portA) 2.connections.connect(alias="aliasB", host=hostB, port=portB) 3. utility.list_colection(using="aliasA") 4. utility.list_collections(using=aliasB)

我发现，整个python进程内，必须要先创建 default 别名的连接，才可以创建其他别名的连接。这算bug吗？ ref:https://github.com/milvus-io/milvus/issues/17592

**Comment by yanliang567** [comment]
I can create connections with alias without default. 
>>> from pymilvus import connections, utility
>>> connections.connect('aliasA', host='10.104.20.207', port=19530)
>>> utility.list_collections(using='aliasA')
[]

**Comment by hongzaolvdoutangyuan** [comment]
I encountered the same problem. I don't need to change the place where it is written. I just need to specify using when calling it.
write in milvus：`connections.connect(alias=milvus_alias, host = milvus_host, port = milvus_port)`
call milvus：`collection = Collection(collection_name, using=milvus_name)`

collection_name: your index_name
milvus_name: your alias

**Comment by yanliang567** [comment]
> I encountered the same problem. I don't need to change the place where it is written. I just need to specify using when calling it. write in milvus：`connections.connect(alias=milvus_alias, host = milvus_host, port = milvus_port)` call milvus：`collection = Collection(collection_name, using=milvus_name)`
> 
> collection_name: your index_name milvus_name: your alias

not reproduce your issue. please try latest pymilvus 2.4.4
```
>>> c=Collection('search_collection_YWPQY2Iw', using='aliasA')
>>> c.name
'search_collection_YWPQY2Iw'
```

**Comment by lynneTest** [comment]
> > if you want to connect to 2 milvus cluster, you shall use different aliases, such as aliasA, aliasB, then calling every API with using=aliasX 1.connections.connect(alias="aliasA", host=hostA, port=portA) 2.connections.connect(alias="aliasB", host=hostB, port=portB) 3. utility.list_colection(using="aliasA") 4. utility.list_collections(using=aliasB)
> 
> 我发现，整个python进程内，必须要先创建 default 别名的连接，才可以创建其他别名的连接。这算bug吗？ ref:#17592

非常感谢！！！！！！
