### ISSUE TITLE
[Bug]: [ci] After deleting entities and compaction, sometimes the num_entities decreases and sometimes remains the same

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#23730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. create a collection with 1 shard
2. insert 100 entities without flush
3. delete 20 entities and trigger auto compact
4. insert 1 entity and the`num_entities` is sometimes 101 and sometimes 81

![image](https://user-images.githubusercontent.com/27288593/234498186-0b51624d-84db-46cc-ad29-f3a4e7906cd8.png)

See the jenkins link for detail:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-23710/8/pipeline

**Comment by ThreadDao** [comment]
/assign @XuanYang-cn 
Maybe it has something to do with compaction. Please take a look as soon as possible. Because it's not stable and might affect the pr merge. Thank you so much

**Comment by ThreadDao** [comment]
> > @ThreadDao
> > ```
> > P1. num_entities = segC + segA = (inserts: 1) + (inserts: 100, deletes: 20) = 101
> > segA ---compacted--> SegB
> > P2. num_entities = segC + segB = (inserts: 1) + (inserts: 80) = 81
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > c.num_entities==101 at P1 c.num_entities==81 at P2
> > Since we don't know when segA->segB is finished, we could get either 81 or 101.
> > Suggest to wait for num_entities == 81 and set a timeout of 30s. /unassign /assign @ThreadDao
> 
> maybe an easier way to wait for the compaction done? for example check the segment number?

For delete-type compaction, the number of segments before and after is the same. It doesn't matter. case has been changed to wait for the auto-compaction to complete and update the num_entities. You can rebase master branch and rerun e2e-test

**Comment by XuanYang-cn** [comment]
also needed in 2.2.0  #23802
