### ISSUE TITLE
Build index for small segment waste time on waiting background index thread finish

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#2373]
**Describe the bug**
http://internal.zilliz.com:18080/jenkins/blue/organizations/jenkins/milvus-ci/detail/0.9.1/8/pipeline/736
```
[2020-05-17T20:45:13.196Z] ____________________ TestMixBase.test_mix_multi_collections ____________________

```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
The steps of TestMixBase.test_mix_multi_collections:
1. create 60 collections, insert 10000 vectors to each collection
2. create index for 60 collections
3. search 60 collections

Time cost distribute:
step 1 cost 7.5 seconds
step 2 cost 197.5 seconds
step 3 cost 0.5 second

**Comment by yhmo** [comment]
Build index for each segment(contains 10000 vectors) cost 4~5 seconds by gpu version.
My hardware:
GeForce GTX 1660  6GB
Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz   12 core

**Comment by yhmo** [comment]
Fixed by pr2482
After fix, the time cost of Test case TestMixBase.test_mix_multi_collections reduce from 206 seconds to 47 seconds;

**Comment by del-zhenwu** [comment]
nightly run time decreased
