### ISSUE TITLE
[Bug]: Attu load collection very slowly 

### ISSUE THREAD

**Issue by qilaijun101** [milvus-io/milvus#23746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.5
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: querynode 4C23G
- GPU: 
- Others:
```

### Current Behavior

<img width="1393" alt="image" src="https://user-images.githubusercontent.com/14890813/234741279-d4a129a4-5816-438b-8e0a-aae877ca40e0.png">
 load collection very slowly 

### Steps To Reproduce

```markdown
1. load collection by atuu
2. check the load status
```

### Milvus Log

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/14890813/234742002-f7291962-54a5-4688-8f21-4ae86a7efc02.png">

**Comment by yanliang567** [comment]
how many entities did you insert in the collection, and what is the dim?
also Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
/assign @qilaijun101
