### ISSUE TITLE
incorrect v0.9.0 doc about python

### ISSUE THREAD

**Issue by shiyu22** [milvus-io/milvus#2374]
## Report incorrect documentation

**Location of incorrect documentation**
https://milvus.io/docs/v0.9.0/guides/get_started/example_code.md

**Describe the problems or issues found in the documentation**
The pymilvus version of milvus0.9.0 should be 0.2.11, and the Python example code is still 0.8.0

**Comment by PahudPlus** [comment]
Fixed.

**Comment by shiyu22** [comment]
wget https://raw.githubusercontent.com/milvus-io/pymilvus/0.9.0/examples/example.py, this link is not exists.

And the [example code](https://github.com/milvus-io/pymilvus/blob/0.8.0/examples/example.py) is incorrect.

**Comment by BossZou** [comment]
should be  https://raw.githubusercontent.com/milvus-io/pymilvus/0.2.11/examples/example.py

**Comment by PahudPlus** [comment]
The issue has been fixed. https://www.milvus.io/docs/v0.9.0/guides/get_started/example_code.md
