### ISSUE TITLE
[Enhancement]: By adding a requirement, the description of the collection can be modified

### ISSUE THREAD

**Issue by xiao12mm** [milvus-io/milvus#23761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

By adding a requirement, the description of the collection can be modified

### Why is this needed?

I usually add collections with the default description, sometimes I test too many collections, I don't know which collection uses what improvement method, and it's too much work to rebuild the collection, insert the data, I think I can change it at any time, right

**Comment by xiaofan-luan** [comment]
@xiao12mm 
Maybe you can add the modify collection func in alterCollection?
shouldn't be too hard to do it
