### ISSUE TITLE
[Bug]: [segment monitor] compaction test scenario where the number of segments on the monitor  is incorrect

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#23775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:  2.2.0-20230427-9286d7a4
- Deployment mode(standalone or cluster):standalone 
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I turn on the segment_state metric and look at it, it is different from what birdwatcher observes
This instance has only one collection . 

<img src=https://user-images.githubusercontent.com/48523564/234822077-29cd01b3-6ef1-4c9a-b418-84dc3fa71006.png width=95% />
 
![image](https://user-images.githubusercontent.com/48523564/234824470-7dfa413c-1161-41ab-bb44-edf607ff23f4.png)

grafana (Growing 4k,Sealed 1.4k) : 

<img src=https://user-images.githubusercontent.com/48523564/234822398-bbf815f6-3ebd-4fd9-a670-b2d762d26a5f.png width=60% />

birdwatcher (Connect to etcd ,Total Segments: 903):
<img src=https://user-images.githubusercontent.com/48523564/234822748-aab90bb7-9682-442e-8a96-6333c76d2f1e.png width=60% />

**server**:
```
fouramf-r6ppj-86-3857-etcd-0                                      1/1     Running            0                 80m     10.104.1.77     4am-node10   <none>           <none>
fouramf-r6ppj-86-3857-milvus-standalone-597fc5f647-6c9rx          1/1     Running            0                 80m     10.104.18.104   4am-node25   <none>           <none>
fouramf-r6ppj-86-3857-minio-669f864f7f-vmcrs                      1/1     Running            0                 80m     10.104.1.76     4am-node10   <none>           <none>
```
 

### Expected Behavior

The number of segments observed by monitoring is the same as that observed by birdwatcher .

### Steps To Reproduce

```markdown
1. create a collection or use an existing collection
        2. build index on vector column
        3. insert a certain number of vectors
        4. flush collection
        5. build index on vector column with the same parameters
        6. build index on on scalars column or not
        7. count the total number of rows
        8. load collection
        9. perform concurrent operations (load、query、scene_insert_delete_flush、searc)                                                                                                                                 
        10. clean all collections or not
```

**Comment by elstic** [comment]
This issue still exists.    segment wrong number

![image](https://github.com/milvus-io/milvus/assets/48523564/ecb12c05-c7ff-48ed-b2ca-e54754e5fc8e)

![image](https://github.com/milvus-io/milvus/assets/48523564/50f67111-8e36-4205-aa6b-9a0c71eb4003)

**Comment by yanliang567** [comment]
/assign @XuanYang-cn 
could yuo please help on this issue
