### ISSUE TITLE
Duplicate data after server restart

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#2378]
**Describe the bug**
1. create a collection
2. create a partition for the collection
3. insert 100 vectors into the partition
4. get the row count of the collection = 100
5. restart milvus server
6. get the row count of the collection = 200

After restart, wal re-import data into the partition.

**Comment by JinHai-CN** [comment]
@del-zhenwu I think you can add one more test case on the issue.

**Comment by yhmo** [comment]
reproduce on 0.7.x/0.8.0/0.9.0

**Comment by yhmo** [comment]
fixed by pr2388

**Comment by yhmo** [comment]
fixed by pr2388

**Comment by del-zhenwu** [comment]
fixed
