### ISSUE TITLE
[Bug]: datanode FAIL TO START  and pulsar error message ：All producers on topic [persistent://public/default/by-dev-datacoord-timetick-channel] are disconnected

### ISSUE THREAD

**Issue by gxh-97** [milvus-io/milvus#23789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.5
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar     
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I checked the system, I found an error message, and then I checked the Milvus cluster and found that datanode si exceeded (2)

### Expected Behavior

business as usual

### Milvus Log

datanode logs picture
![383af288126f73fa10df8071a0fe114](https://user-images.githubusercontent.com/79824489/235047625-5725095d-c18e-4492-a591-57dce82ce056.png)
and logs text
[log_datannode.log](https://github.com/milvus-io/milvus/files/11349557/log_datannode.log)

### Anything else?

pulsar  logs
![8e2c2bb18bb625653553488ccd91e4f](https://user-images.githubusercontent.com/79824489/235047542-182f5b87-2808-4411-a057-e903254fd7d8.png)

**Comment by yanliang567** [comment]
sound like the topic backlog quota exceeded... @LoveEachDay any ideas?

/assign @LoveEachDay 
/unassign
