### ISSUE TITLE
[Enhancement]: Improve the search performance by adjust the merge policy

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#23796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

1. evaluate the cost to merge by extra cost, not merge factor (defined by below)
2. the task pool size should be the same as the number of CPU cores

### Why is this needed?

For 1: for given two search tasks $t_1$, $t_2$, with $nq_1, topk_1$ and $nq_2, topk_2$, Milvus merges them into a search task: 
$nq_m = nq_1 + nq_2$
$topk_m = max(topk_1,topk_2)$

and Milvus defines the cost of search task be $c = nq \times topk$

According to @liliu-z, larger $nq$ would reach better performance (friendly to cache, less cgo call & serialize/deserialize overhead...).

The merge policy currently is:
- if $topk_1 = topk_2$, always merges $t_1, t_2$
- otherwise, requires the merge factor $f_{t_1, t_2} = c_m/min(c_1, c_2)$ be not more than `TopkMergeRatio` (10 by default)

This policy doesn't work well because the factor doesn't evaluate the real extra cost ($c_m - min(c_1, c_2)$) while merging, which means it will failed to merge tasks with very small cost but large factor.

example:
the factor is same for merging $topk_1 = 1, topk_2 = 10$ and
$topk_1 = 100, topk_2 = 1000$, but the extra costs are not the same.

**Comment by xiaofan-luan** [comment]
So what is the suggested solution?
I'm assuming TopkMergeRatio can be something like a min(2,  100 / sqrt(topk))
So everything with topk > 10000 might not be prioritized to merge

**Comment by yah01** [comment]
> So what is the suggested solution?
> 
> I'm assuming TopkMergeRatio can be something like a min(2,  100 / sqrt(topk))
> 
> So everything with topk > 10000 might not be prioritized to merge

It's hard to measure accurately the cost by ratio, the better way is to calculate the cost directly:
$cost = (nq_1+nq_2)*topk_max - min(nq*topk)$

And we need to test to find out the best cost threshold

**Comment by xiaofan-luan** [comment]
keep it as this might be related
