### ISSUE TITLE
[Bug]: [benchmark] insert 100 million data, 2 replica , concurrent operations, IVF_SQ8 index search latency is twice that of November 2022 

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#23797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20230427-c82ec0b1
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Same scenario, insert 100 million data, concurrent operations, IVF_SQ8 index search latency is twice as high as in November 2022 .

image: 2.2.0-20230427-c82ec0b1
search latency :  about 0.233s
![image](https://user-images.githubusercontent.com/48523564/235058904-92dcfdfa-3ab9-4651-9b77-e1b352443a36.png)

image : 2.2.0-20221118-e7429f88
search latency :  about 0.109s
![image](https://user-images.githubusercontent.com/48523564/235061872-293f5d65-b2c9-4abf-a744-c4a6cc37e818.png)

### Steps To Reproduce

```markdown
1. create a collection or use an existing collection
        2. build index on vector column
        3. insert a certain number of vectors
        4. flush collection
        5. build index on vector column with the same parameters
        6. build index on on scalars column or not
        7. count the total number of rows
        8. load collection
        9. perform concurrent operations (search、load、query、ddl)
        10. clean all collections or not
```

**Comment by xiaofan-luan** [comment]
@cydrain pls help on investigate it

**Comment by cydrain** [comment]
image: 2.2.0-20230427-c82ec0b1 (knowhere-1.3.12)

image : 2.2.0-20221118-e7429f88 (knowhere-1.3.2)

**Comment by elstic** [comment]
using dataset: SIFT , metirc_type:L2

search (weight=20):
```
 nq=10, top_k=10, search_param={"nprobe": 16},
 expr=eval("{'float_1': {'GT': -1.0, 'LT': parser_data_size(data_size) * 0.5}}")),
```
query (weight=10):
```
ids=[i for i in range(10)]
```
load(weight=1)
ddl (weight=2)
```
create collection,insert vectors, flush, build index ,time.sleep(59), drop collection 
```

**Comment by elstic** [comment]
Synchronized information: 
ddl operations have slowed down more ：
![image](https://github.com/milvus-io/milvus/assets/48523564/bdce13e8-7ff8-40c9-8dda-5f76fdd7f945)
between 112s and 114s

In the previous version v2.2.4:
![image](https://github.com/milvus-io/milvus/assets/48523564/6cd24c88-8a18-4378-8aa3-efccfc15fb2e)


case: test_concurrent_locust_100m_ivf_sq8_ddl_dql_filter_replica2_cluster

**Comment by elstic** [comment]
/assign @jiaoew1991 
ddl is slowing down, please help troubleshoot

**Comment by jiaoew1991** [comment]
Is this still a problem, @elstic?

**Comment by elstic** [comment]
> Is this still a problem, @elstic?

This issue no longer exists. 
Please see the search latency of this case recently run, it and our benchmark data has been about the same, according to my judgment, should be this issue under the pr repair:  https://github.com/milvus-io/milvus/issues/24022
![image](https://github.com/milvus-io/milvus/assets/48523564/bba9860e-ee76-4e85-b5a3-ec2c23bb9a37)
