### ISSUE TITLE
[Bug]: set authorizationEnabled as true (Cluster docker-compose mode), but invalid.

### ISSUE THREAD

**Issue by shatealaboxiaowang** [milvus-io/milvus#23799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.6
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus2.2.2
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 48c/256G
- GPU: 
- Others:
```

### Current Behavior

when i set authorizationEnabled as true in milvus.yaml, but invalid (because any user name and password can connect).

### Expected Behavior

No

### Steps To Reproduce

```markdown
1.Set common.security.authorizationEnabled in milvus.yaml as true when configuring Milvus to enable authentication；
2. Modified milvus.yaml path map in docker-compose.yaml;
3. Build a service in docker-compose up -d;
4. Connect to the milvus service from a python client with any account and password.
```

### Milvus Log

No

### Anything else?

set authorizationEnabled as true in milvus.yaml, but invalid (because any user name and password can connect).
This happens when deployment mode is cluster docker-compose, and is ok when deployment mode is cluster k8s

**Comment by yanliang567** [comment]
cluster docker-compose mode is going to be deprecated for it is not a "real" cluster for HA.  we recommend you use cluster k8s mode.

/assign @shatealaboxiaowang 
/unassign

**Comment by xiaofan-luan** [comment]
let's still investigate on why common.security.authorizationEnabled won't work because it will be similar in the standalone deployment

**Comment by shatealaboxiaowang** [comment]
> 

Thanks very much，this meas there are no plans to fix this feature on cluster docker-compose mode ? If we want to use this feature, we must use k8s ?

**Comment by shatealaboxiaowang** [comment]
> let's still investigate on why common.security.authorizationEnabled won't work because it will be similar in the standalone deployment

ok, thanks, Are there any plans to fix this feature in the future?

**Comment by SimFG** [comment]
@xiaofan-luan ok, i will check it out

**Comment by SimFG** [comment]
@shatealaboxiaowang I tried it locally and found that authorizationEnabled should be in effect. You can enter the docker container of milvus, and then confirm whether the authorizationEnabled is successfully configured.
```
cd configs
cat milvus.yaml | grep authorizationEnabled
```
