### ISSUE TITLE
The Milvus logs level configuration is too complicated

### ISSUE THREAD

**Issue by ZhifengZhang-CN** [milvus-io/milvus#2379]
**What is your question?**
The Milvus logs level configuration is too complicated

**Expected behavior**
 Explains the message severity levels  or level list for Milvus logs levels .

e.g.
```
logs:                              logs:
  enable: true                       enable: true
  levels: error            or        levels: "error, warning"
```

**Comment by scsven** [comment]
"key: value" pattern is easier to be modified in some script likes awk.
