### ISSUE TITLE
[Bug]: DataNode memory constantly increase in silent status

### ISSUE THREAD

**Issue by MrPresent-Han** [milvus-io/milvus#23836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): Kafka   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

DataNode memory consumption keep going up after restarted

### Expected Behavior

DataNode memory consumption is stable

![image (2)](https://user-images.githubusercontent.com/116052805/235554945-48d1185a-c546-40f5-bd6a-869fed42345c.png)

### Milvus Log
[milvus-datanode-7bc7856b6d-6wpkn (1).log](https://github.com/milvus-io/milvus/files/11368827/milvus-datanode-7bc7856b6d-6wpkn.1.log)
[milvus-datacoord-79c44bb8c4-qq75b.log](https://github.com/milvus-io/milvus/files/11368829/milvus-datacoord-79c44bb8c4-qq75b.log)
[kafka-1.log](https://github.com/milvus-io/milvus/files/11368831/kafka-1.log)
[milvus-rootcoord-6955b946f5-4z9wm.log](https://github.com/milvus-io/milvus/files/11368834/milvus-rootcoord-6955b9
[pprof.milvus.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz](https://github.com/milvus-io/milvus/files/11368835/pprof.milvus.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz)
46f5-4z9wm.log)

**Comment by MrPresent-Han** [comment]
after restarted datacoord, datanode's Memory still goes up
![image (3)](https://user-images.githubusercontent.com/116052805/235555309-a9f5cec0-0aa2-4ce7-a20e-ef9cace3cc2b.png)
according to pprof provided by clients, I suspect there are too long time tick log which leads to msg accumulate in the buffer
<img width="566" alt="截屏2023-05-02 08 39 00" src="https://user-images.githubusercontent.com/116052805/235555745-b9c0ea2f-db07-4860-b49a-b1c34f823bbc.png">

**Comment by MrPresent-Han** [comment]
in the rootCoord log, many time tick slow logs
[2023/05/01 09:13:13.478 +00:00] [INFO] [rootcoord/import_manager.go:780] ["import manager starts loading from Etcd"]
[2023/05/01 09:13:13.931 +00:00] [WARN] [rootcoord/timeticksync.go:289] ["rootcoord send tt to all channels too slowly"] [chanNum=256] [span=869]
[2023/05/01 09:13:14.705 +00:00] [WARN] [rootcoord/timeticksync.go:289] ["rootcoord send tt to all channels too slowly"] [chanNum=256] [span=773]
[2023/05/01 09:13:15.540 +00:00] [WARN] [rootcoord/timeticksync.go:289] ["rootcoord send tt to all channels too slowly"] [chanNum=256] [span=834]
[2023/05/01 09:13:16.483 +00:00] [WARN] [rootcoord/timeticksync.go:289] ["rootcoord send tt to all channels too slowly"] [chanNum=256] [span=943]
[2023/05/01 09:13:17.482 +00:00] [WARN] [rootcoord/timeticksync.go:289] ["rootcoord send tt to all channels too slowly"] [chanNum=256] [span=998]
[2023/05/01 09:13:18.380 +00:00] [WARN] [rootcoord/timeticksync.go:289] ["rootcoord send tt to all channels too slowly"] [chanNum=256] [span=898]
[2023/05/01 09:13:19.435 +00:00] [WARN] [rootcoord/timeticksync.go:289] ["rootcoord send tt to all channels too slowly"] [chanNum=256] [span=1055]

**Comment by MrPresent-Han** [comment]
besides, some channels checkpoint lag behind a lot than real time, 
![飞书20230502-084618](https://user-images.githubusercontent.com/116052805/235556195-3781b684-6fd5-4c81-9d4a-44323b07abf2.jpg)

**Comment by xiaofan-luan** [comment]
> in the rootCoord log, many time tick slow logs, by the way, **there are 376 channels used by the client** [2023/05/01 09:13:13.478 +00:00] [INFO] [rootcoord/import_manager.go:780] ["import manager starts loading from Etcd"] [2023/05/01 09:13:13.931 +00:00] [WARN] [rootcoord/timeticksync.go:289] ["rootcoord send tt to all channels too slowly"] [chanNum=256] [span=869] [2023/05/01 09:13:14.705 +00:00] [WARN] [rootcoord/timeticksync.go:289] ["rootcoord send tt to all channels too slowly"] [chanNum=256] [span=773] [2023/05/01 09:13:15.540 +00:00] [WARN] [rootcoord/timeticksync.go:289] ["rootcoord send tt to all channels too slowly"] [chanNum=256] [span=834] [2023/05/01 09:13:16.483 +00:00] [WARN] [rootcoord/timeticksync.go:289] ["rootcoord send tt to all channels too slowly"] [chanNum=256] [span=943] [2023/05/01 09:13:17.482 +00:00] [WARN] [rootcoord/timeticksync.go:289] ["rootcoord send tt to all channels too slowly"] [chanNum=256] [span=998] [2023/05/01 09:13:18.380 +00:00] [WARN] [rootcoord/timeticksync.go:289] ["rootcoord send tt to all channels too slowly"] [chanNum=256] [span=898] [2023/05/01 09:13:19.435 +00:00] [WARN] [rootcoord/timeticksync.go:289] ["rootcoord send tt to all channels too slowly"] [chanNum=256] [span=1055]

seems that the message queue is very slow?
