### ISSUE TITLE
[Enhancement]: Simplify milvus usage

### ISSUE THREAD

**Issue by chasingegg** [milvus-io/milvus#23849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Metric_type like 'L2'/'IP' does not need to be specified in search params, we could infer the metric_type from index side.

**Comment by xiaofan-luan** [comment]
> 

Totally agreed. now seems that index is a must there is no meaning for search.
Just ignore it when user specified metric type on search for compatibility

**Comment by chasingegg** [comment]
Already done, close it.
