### ISSUE TITLE
[Bug]: There's no way to know the value of shards_num from the client

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#23853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230427-a7c44b29
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq   
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.8.dev10
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

There's no way to know the value of shards_num from the client.
When using 'collection._shards_num' to get shard number, an error will be raised.
```
AttributeError: 'Collection' object has no attribute '_shards_num'
```

### Expected Behavior

return the shards_num

**Comment by XuanYang-cn** [comment]
I'll add a `num_shards` property in `Collection`

Why `num_shards` not `shards_num`?: 
- `shards_num` is confusing, usually read as `shards number`, refering to the id of the shards. 
- `num_shards` read as `number of shards`, means the count of the shards, following `num_entities`.

**Comment by xiaofan-luan** [comment]
> I'll add a `num_shards` property in `Collection`
> 
> Why `num_shards` not `shards_num`?:
> 
> * `shards_num` is confusing, usually read as `shards number`, refering to the id of the shards.
> * `num_shards` read as `number of shards`, means the count of the shards, following `num_entities`.

make sense to me, num_shards works

**Comment by XuanYang-cn** [comment]
@NicoYuan1986 Please try pymilvus-2.2.9.dev2
/unassign
/assign @NicoYuan1986

**Comment by NicoYuan1986** [comment]
Update: pymilvus version 2.2.9.dev4
We can now create a collection by given num_shards we need using shards_num=xx.
![image](https://github.com/milvus-io/milvus/assets/109071306/a5ecdacc-5c46-40f9-9443-f0665a126bbf)
And both collection.num_shards and collection._num_shards are worked.

When using num_shards=xx, it doesn't work.
![image](https://github.com/milvus-io/milvus/assets/109071306/a96e9e9d-8033-4777-aaf8-41b59162bd76)

wait for new modification.

**Comment by XuanYang-cn** [comment]
should be done
/unassign
/assign @NicoYuan1986

**Comment by NicoYuan1986** [comment]
![image](https://github.com/milvus-io/milvus/assets/109071306/4e8ea236-e1ed-4428-bcdd-e61336d3cba9)

fixed.
