### ISSUE TITLE
[Bug]: DDL rate limit is not working

### ISSUE THREAD

**Issue by bigsheeper** [milvus-io/milvus#23865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master & 2.2.0
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

DDL rate limit should be not working with Collection level rate limit, we should add the global rate limit back or fix it @weiliu1031

**Comment by weiliu1031** [comment]
please verify this

**Comment by bigsheeper** [comment]
/assign @ThreadDao 
please help to make a verify
