### ISSUE TITLE
[SDK]: Client remove the check logic of index param when create index

### ISSUE THREAD

**Issue by czs007** [milvus-io/milvus#23860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

RT

### Why is this needed?

Since server will check the index params.

@XuanYang-cn  @longjiquan @congqixia  @yhmo @yelusion2 @shanghaikid @yah01 @nameczz 

### Anything else?

- [ pymilvus ] https://github.com/milvus-io/pymilvus/issues/1411

_No response_

**Comment by xiaofan-luan** [comment]
very important to us.
