### ISSUE TITLE
[Bug]: [benchmark] milvus load time consuming slowdown 

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#23870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:   2.2.0-20230427-c82ec0b1
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

#### v2.2.4 :
100 million data, hnsw cluster, load time taken: 49.29s

#### 2.2.0-20230427-c82ec0b1:
100 million data, hnsw cluster, load time taken:  103.5604s

load time consumption has increased:  **110.1%**

### Steps To Reproduce

```markdown
1. create a collection or use an existing collection
        2. build index on vector column
        3. insert a certain number of vectors
        4. flush collection
        5. build index on vector column with the same parameters
        6. build index on on scalars column or not
        7. count the total number of rows
        8. load collection    ===》  Statistics time
        9. perform concurrent operations
        10. clean all collections or not
```

**Comment by congqixia** [comment]
Just looked into this problem.
The root cause was `queryCoord.checkInterval` changed to 10s by default.
This will cause segment task generated 10+ seconds after the load operation.
I think where was a pr to change this value:
https://github.com/milvus-io/milvus/pull/23786
WDYGT? @xiaofan-luan @sunby @yah01

**Comment by xiaofan-luan** [comment]
> Just looked into this problem. The root cause was `queryCoord.checkInterval` changed to 10s by default. This will cause segment task generated 10+ seconds after the load operation. I think where was a pr to change this value: #23786 WDYGT? @xiaofan-luan @sunby @yah01

should we just trigger a checker immediately on load and other operations but not change the timer to 10s

**Comment by congqixia** [comment]
Sounds like a plan: `CollectionObserver` could trigger checker more frequently when there are some collections/partitions being loaded.

**Comment by congqixia** [comment]
patch merged, could you please verify?
/assign @elstic

**Comment by elstic** [comment]
> patch merged, could you please verify? /assign @elstic

@congqixia   
I verified the same index, same amount of data, build 100m data, now it takes: 73.4534s, better than before the fix, but it doesn't seem to be back to v2.2.4.
Verify image: 2.2.0-20230508-82be9e83 

|  v2.2.4   |  2.2.0-20230427-c82ec0b1  | 2.2.0-20230508-82be9e83  |
|  ----  | ----  | ----  |
| 49.29s  |103.5604s   |   73.4534s   |

**Comment by xiaofan-luan** [comment]
fine, let's change to 1s and retest?

**Comment by elstic** [comment]
I set the checkInterval to: 1000

I get the load time time 76.9476s (image:2.2.0-20230524-e8545777)



Without any parameter modification, the loadl time is: 80.4232s 
(image: 2.2.0-20230524-e8545777)

---
The results don't seem to make much difference .
