### ISSUE TITLE
[Bug]: milvus-operator pod displays an error indicating that Back-off restarting failed container

### ISSUE THREAD

**Issue by maqiang515** [milvus-io/milvus#23875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1、Environment is normal at first, but with Prometheus and granfna installed milvus-operator starts, but after a while the status is CrashLoopBackOff, describe the event of the Back-off restarting failed container
2、After deleting Prometheus and granfna, milvus-operator has the same effect

**Comment by xiaofan-luan** [comment]
please attach your log so we can take a look into it.
@maqiang515

**Comment by yanliang567** [comment]
@maqiang515 Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
/assign @maqiang515

**Comment by maqiang515** [comment]
Reloaded the milvus. No clue why
