### ISSUE TITLE
[Bug]: Milvus 2.2.0, at 3:00 AM when the QPS is relatively low, the query response time P99 increases to several seconds."

### ISSUE THREAD

**Issue by linggong2023** [milvus-io/milvus#23880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: Previously, due to scheduling issues, we were unable to achieve the desired QPS. As a result, we adjusted the ration value from 2.2.0 to 100.
```

### Current Behavior

Sometimes at 3 am, the P99 latency increases.

**Comment by linggong2023** [comment]
Will upgrading to 2.2.6 solve this problem?

**Comment by xiaofan-luan** [comment]
I don't think this is a Milvus issue. We don't have any hard coded limit on 3 AM.
Please check your environment, if there is any insertion/bulkinsertions, QPS, CPU usage and investigate on why.
