### ISSUE TITLE
[Bug]: Compiling milvus on arm encountered an error with confluent-kafka-go

### ISSUE THREAD

**Issue by Sivannnnnn** [milvus-io/milvus#23893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.6
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: kunpeng920
- GPU: 
- Others:
```

### Current Behavior

When compiling milvus2.2.6 on ARM, milvus relies on confluent-kafka-go@v1.9.1. I installed librdkafka@v1.9.1, but it compiled incorrectly

`
/opt/milvus/new-milvus-2.2.6
fatal: bad revision 'HEAD'
fatal: Needed a single revision
Build Tag: 
Build Time: Sat May  6 02:02:01 UTC 2023
Git Commit: 
Go Version: go version go1.19.1 linux/arm64
fatal: bad revision 'HEAD'
fatal: Needed a single revision
Building Milvus ...
# command-line-arguments
/usr/local/go/pkg/tool/linux_arm64/link: running gcc failed: exit status 1
/usr/bin/ld.gold: error: /data/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.9.1/kafka/librdkafka_vendor/librdkafka_glibc_linux.a(rdkafka_error.o): incompatible target
/usr/bin/ld.gold: error: /data/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.9.1/kafka/librdkafka_vendor/librdkafka_glibc_linux.a(rdkafka_mock.o): incompatible target
/usr/bin/ld.gold: error: /data/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.9.1/kafka/librdkafka_vendor/librdkafka_glibc_linux.a(rdkafka_txnmgr.o): incompatible target
/usr/bin/ld.gold: error: /data/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.9.1/kafka/librdkafka_vendor/librdkafka_glibc_linux.a(rdkafka_aux.o): incompatible target
/usr/bin/ld.gold: error: /data/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.9.1/kafka/librdkafka_vendor/librdkafka_glibc_linux.a(rdkafka_admin.o): incompatible target
/usr/bin/ld.gold: error: /data/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.9.1/kafka/librdkafka_vendor/librdkafka_glibc_linux.a(rdkafka_header.o): incompatible target
/usr/bin/ld.gold: error: /data/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.9.1/kafka/librdkafka_vendor/librdkafka_glibc_linux.a(rdkafka_metadata.o): incompatible target
/usr/bin/ld.gold: error: /data/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.9.1/kafka/librdkafka_vendor/librdkafka_glibc_linux.a(rdkafka_event.o): incompatible target
/usr/bin/ld.gold: error: /data/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.9.1/kafka/librdkafka_vendor/librdkafka_glibc_linux.a(rdkafka_subscription.o): incompatible target
/usr/bin/ld.gold: error: /data/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.9.1/kafka/librdkafka_vendor/librdkafka_glibc_linux.a(rdkafka_partition.o): incompatible target
/usr/bin/ld.gold: error: /data/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.9.1/kafka/librdkafka_vendor/librdkafka_glibc_linux.a(rdkafka_cgrp.o): incompatible target
/usr/bin/ld.gold: error: /data/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.9.1/kafka/librdkafka_vendor/librdkafka_glibc_linux.a(rdkafka_queue.o): incompatible target
/usr/bin/ld.gold: error: /data/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.9.1/kafka/librdkafka_vendor/librdkafka_glibc_linux.a(rdkafka_offset.o): incompatible target
/usr/bin/ld.gold: error: /data/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.9.1/kafka/librdkafka_vendor/librdkafka_glibc_linux.a(rdkafka_conf.o): incompatible target
/usr/bin/ld.gold: error: /data/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.9.1/kafka/librdkafka_vendor/librdkafka_glibc_linux.a(rdkafka_topic.o): incompatible target
/usr/bin/ld.gold: error: /data/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.9.1/kafka/librdkafka_vendor/librdkafka_glibc_linux.a(rdkafka_msg.o): incompatible target
/usr/bin/ld.gold: error: /data/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.9.1/kafka/librdkafka_vendor/librdkafka_glibc_linux.a(rdkafka.o): incompatible target
cgo-gcc-prolog:174: error: undefined reference to 'rd_kafka_AclBindingFilter_new'
cgo-gcc-prolog:189: error: undefined reference to 'rd_kafka_AclBinding_destroy'
cgo-gcc-prolog:204: error: undefined reference to 'rd_kafka_AclBinding_host'
cgo-gcc-prolog:222: error: undefined reference to 'rd_kafka_AclBinding_name'
cgo-gcc-prolog:250: error: undefined reference to 'rd_kafka_AclBinding_new'
cgo-gcc-prolog:269: error: undefined reference to 'rd_kafka_AclBinding_operation'
cgo-gcc-prolog:288: error: undefined reference to 'rd_kafka_AclBinding_permission_type'
cgo-gcc-prolog:306: error: undefined reference to 'rd_kafka_AclBinding_principal'
cgo-gcc-prolog:325: error: undefined reference to 'rd_kafka_AclBinding_resource_pattern_type'
cgo-gcc-prolog:344: error: undefined reference to 'rd_kafka_AclBinding_restype'
cgo-gcc-prolog:363: error: undefined reference to 'rd_kafka_AclOperation_name'
cgo-gcc-prolog:382: error: undefined reference to 'rd_kafka_AclPermissionType_name'
cgo-gcc-prolog:397: error: undefined reference to 'rd_kafka_AdminOptions_destroy'
cgo-gcc-prolog:413: error: undefined reference to 'rd_kafka_AlterConfigs'
cgo-gcc-prolog:429: error: undefined reference to 'rd_kafka_AlterConfigs_result_resources'
cgo-gcc-prolog:448: error: undefined reference to 'rd_kafka_ConfigEntry_is_read_only'
cgo-gcc-prolog:467: error: undefined reference to 'rd_kafka_ConfigEntry_is_sensitive'
cgo-gcc-prolog:486: error: undefined reference to 'rd_kafka_ConfigEntry_is_synonym'
cgo-gcc-prolog:504: error: undefined reference to 'rd_kafka_ConfigEntry_name'
cgo-gcc-prolog:523: error: undefined reference to 'rd_kafka_ConfigEntry_source'
cgo-gcc-prolog:542: error: undefined reference to 'rd_kafka_ConfigEntry_synonyms'
cgo-gcc-prolog:560: error: undefined reference to 'rd_kafka_ConfigEntry_value'
cgo-gcc-prolog:579: error: undefined reference to 'rd_kafka_ConfigResource_configs'
cgo-gcc-prolog:594: error: undefined reference to 'rd_kafka_ConfigResource_destroy'
cgo-gcc-prolog:610: error: undefined reference to 'rd_kafka_ConfigResource_error'
cgo-gcc-prolog:628: error: undefined reference to 'rd_kafka_ConfigResource_error_string'
cgo-gcc-prolog:646: error: undefined reference to 'rd_kafka_ConfigResource_name'
cgo-gcc-prolog:666: error: undefined reference to 'rd_kafka_ConfigResource_new'
cgo-gcc-prolog:687: error: undefined reference to 'rd_kafka_ConfigResource_set_config'
cgo-gcc-prolog:706: error: undefined reference to 'rd_kafka_ConfigResource_type'
cgo-gcc-prolog:725: error: undefined reference to 'rd_kafka_ConfigSource_name'
cgo-gcc-prolog:744: error: undefined reference to 'rd_kafka_CreateAcls'
cgo-gcc-prolog:760: error: undefined reference to 'rd_kafka_CreateAcls_result_acls'
cgo-g
`

I want to use 2.x confluent-kafka and librdkafka, but milvus will get an error when compiling confluent-kafka-go should be v0 or v1, not v2

**Comment by yanliang567** [comment]
@liliu-z does milvus support compiling on ARM now?

/assign @liliu-z 
/unassign

**Comment by Presburger** [comment]
@Sivannnnnn 

```
git clone https://github.com/confluentinc/librdkafka.git
cd librdkafka
./configure
make
sudo make install
```
try the above command. then rebuild milvus.
old version kafka client go repo not contain arm binary lib, those days we will update the go version.
