### ISSUE TITLE
Split large record to small records in WalManager

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#2390]
**Describe the bug**

In the MemManagerImpl::InsertEntities(), each wal record was converted to a VectorSource
In the MemTable::Add(), a VectorSource could be split into two MemTableFiles, each MemTableFile was serialized to a segment, could lead to unexpected result.

Firstly we need to split large record to small records in WalManager, and then modify MemManager to avoid a record split into multiple segments.

**Comment by shengjun1985** [comment]
Needn't modify.
