### ISSUE TITLE
[Bug]: Standalone pod can not be healthy after standalone pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#23921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230507-dcf55e77
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):rocksmq    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/236719645-3bb96277-b92b-4499-92a8-695d8bfbee90.png)

### Expected Behavior

Milvus can recover to healthy status and all test cases can pass

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-cron/detail/chaos-test-kafka-cron/3926/pipeline

log: 
[artifacts-standalone-pod-kill-3926-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/11417194/artifacts-standalone-pod-kill-3926-server-logs.1.tar.gz)

[artifacts-standalone-pod-kill-3926-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11417195/artifacts-standalone-pod-kill-3926-pytest-logs.tar.gz)

**Comment by jiaoew1991** [comment]
same as https://github.com/milvus-io/milvus/issues/23959

**Comment by jiaoew1991** [comment]
/unassign
/assign @zhuwenxing 

pls verify it with pr #23961

**Comment by zhuwenxing** [comment]
verified and passed with `master-20230524-014387fd`
