### ISSUE TITLE
Remove '-p 9091:9091' in Step 4 Start Docker container 

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#2392]
Location of incorrect documentation
https://milvus.io/cn/docs/v0.9.0/guides/get_started/install_milvus/cpu_milvus_docker.md

Describe the problems or issues found in the documentation
9091 port is used for pushgateway, not for milvus

Suggested fix for documentation
Remove '-p 9091:9091' in Step 4 Start Docker container

**Comment by PahudPlus** [comment]
According to yudong Cai, the port will be removed in 0.10.0

**Comment by PahudPlus** [comment]
This issue has been fixed in 0.9.1
