### ISSUE TITLE
[Bug]:  pod automatic restart

### ISSUE THREAD

**Issue by yesletgo** [milvus-io/milvus#23953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.5
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):   pulsar  
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.5
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 84cores/600G
- GPU: 
- Others:
```

### Current Behavior

some pod automatic restart

### Expected Behavior

normal operation 

### Milvus Log

https://video-tag-lib-1251808348.cos.ap-beijing.myqcloud.com/milvus_log/milvus-log3.tar.gz
https://video-tag-lib-1251808348.cos.ap-beijing.myqcloud.com/milvus_log/my-release-pulsar-broker-0

**Comment by xiaofan-luan** [comment]
/assign @smellthemoon 
please take a look into it, thanks!

**Comment by yesletgo** [comment]
afler restart, cluster hang.
full log: https://video-tag-lib-1251808348.cos.ap-beijing.myqcloud.com/milvus_log/logs_24h.tar.gz

**Comment by yesletgo** [comment]
If it's an issue with ETCD, from other issues, isn't the ETCD fault fixed ?

**Comment by smellthemoon** [comment]
can't connect to etcd
<img width="1102" alt="1" src="https://github.com/milvus-io/milvus/assets/64083300/995d3470-5f0e-4b19-9db7-81ccf714101f">
may related with #23895
