### ISSUE TITLE
nq达到10000的时候会出现这个问题BUG

### ISSUE THREAD

**Issue by mjiansun** [milvus-io/milvus#2395]
**我构建的库为50000条2048维，具体的配置参数如下**：  
`version: 0.3

server_config:
  address: 0.0.0.0
  port: 19530
  deploy_mode: single
  time_zone: UTC+8
  web_port: 19121

db_config:
  backend_url: sqlite://:@:/
  preload_collection:
  auto_flush_interval: 1

storage_config:
  primary_path: /var/lib/milvus
  secondary_path:

metric_config:
  enable_monitor: false
  address: 127.0.0.1
  port: 9091

cache_config:
  cpu_cache_capacity: 25
  insert_buffer_size: 1
  cache_insert_data: false

engine_config:
  use_blas_threshold: 801
  gpu_search_threshold: 1001

gpu_resource_config:
  enable: true
  cache_capacity: 10
  search_resources:
    -gpu0
    -gpu1
    -gpu2
    -gpu3
  build_index_resources:
    -gpu0
    -gpu1
    -gpu2
    -gpu3

wal_config:
  enable: true
  recovery_error_ignore: true
  buffer_size: 256
  wal_path: /var/lib/milvus/wal`
  
**nq达到10000的时候会出现这个问题（数据维度为2048，索引为类型为IVF_SQ8）**：  
[3.40282347e+38 3.40282347e+38 3.40282347e+38 ... 3.40282347e+38
 3.40282347e+38 3.40282347e+38]  
**nq小一点的时候不会出现问题，具体尝试了小于等于5000都不会出现BUG。**

**Comment by sahuang** [comment]
This is indeed an issue as I have reproduced the bug from my side. The bug is likely caused by large nq cudaMalloc on GPU. We will investigate further and propose a solution to it.

**Comment by sahuang** [comment]
It is recommended to use a relatively smaller nq in querying, because large nq can cause cudaMalloc failure which results in wrong results (or even server down). If you use a large nq, Milvus will now search by blocks of 2000.
