### ISSUE TITLE
[Bug]: [perf][Recall] Milvus diskann's recall of the data set in glove continues to decrease 

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#23965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0/master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

glove-200 dataset-2.2.0 branch image： 2.2.0-20230429-546d3179
cluster
<img width="408" alt="截屏2023-05-09 11 49 53" src="https://user-images.githubusercontent.com/34296482/236989333-62c5b1e3-0215-4b7d-9c78-049912d87f91.png">

standalone  image： 2.2.0-20230428-67dd70f1
<img width="402" alt="截屏2023-05-09 11 14 26" src="https://user-images.githubusercontent.com/34296482/236986637-45b00df3-5951-4807-a766-32f95c8dba6b.png">

glove-200 dataset-master ：master-20230505-6a48de34
<img width="404" alt="截屏2023-05-09 11 32 05" src="https://user-images.githubusercontent.com/34296482/236987026-9a0b0874-290f-48c7-be1b-4acdab78cb38.png">

sift 128d dataset-master master-20230504-a76e9d20
<img width="395" alt="截屏2023-05-09 11 36 39" src="https://user-images.githubusercontent.com/34296482/236987770-efb27043-7523-4784-9a1c-bab4e1a8e5f3.png">

### Steps To Reproduce

```markdown
1. create a collection
2. build disk and index
3，insert glove-200d data
4. build index again
5. load collection
6. search
```

**Comment by liliu-z** [comment]
From this info, it is hard for me find out the potential issues. Can I have the commit ID of good/bad version? Thanks.

**Comment by liliu-z** [comment]
recall jump between bbc21fe8 and 67dd70, Knowhere versions are 1.3.10 and 1.3.12

**Comment by hhy3** [comment]
Is there any way to reproduce the results? The 0.998 recall for glove-200 dataset seems astonishingly high.
