### ISSUE TITLE
[Bug]: During search, timeout does not take effect, causing the search to stall continuously

### ISSUE THREAD

**Issue by 1041787154** [milvus-io/milvus#23979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.3
- Deployment mode(standalone or cluster):standalone 
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.2
- OS(Ubuntu or CentOS): Ubuntu 
- CPU/Memory: 4
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/15188273/237033834-ad8a793b-5db0-4888-9aad-f4aee32e0aa3.png)
timeout donot work！

### Expected Behavior

1. Make timeout effective

2. Reasons for stuck for more than 20 seconds during search

### Milvus Log

[log1.txt](https://github.com/milvus-io/milvus/files/11428778/log1.txt)

**Comment by XuanYang-cn** [comment]
timeout working as expected in pymilvus since timeout is not controlled by pymilvus, it's controlled by milvus server. I double checked that `timeout` is passing to milvus server in the latest pymilvus.

Seems like the milvus's problem to hang. @1041787154 what's your milvus version and the pymilvus version?

**Comment by 1041787154** [comment]
> timeout working as expected in pymilvus since timeout is not controlled by pymilvus, it's controlled by milvus server. I double checked that `timeout` is passing to milvus server in the latest pymilvus.
> 
> Seems like the milvus's problem to hang. @1041787154 what's your milvus version and the pymilvus version?
@XuanYang-cn 
I have already marked the versions of Milvus and SDK in my question. Could you please take a closer look
