### ISSUE TITLE
milvusdb/milvus:v2.2.8，mount /etc/localtime

### ISSUE THREAD

**Issue by skycyan** [milvus-io/milvus#23975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

**Describe the problem：**
$ docker run -itd  -e TZ=Asia/Shanghai -v /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime milvusdb/milvus:v2.2.8 sh
$ docker exec -it ed44f43244 date
Tue, 09 May 2023 06:41:33 +0000

**Solve：**
$ docker exec -it ed44f43244 apt-get -y update && apt-get -y install tzdata
...
$ docker exec -it ed44f43244 date
Tue May  9 15:10:18 CST 2023

### Why is this needed?

milvusdb/milvus:v2.2.8 image. 
When mount / etc/localtime occurs, the time zone in the container cannot be changed (it does not take effect). You need to install the Tzdata package to solve the problem.
As a database, the system environment in which it runs should need to change the time zone flexibly.

**Comment by xiaofan-luan** [comment]
good suggestion.
Any interest to finish your first contribution?
