### ISSUE TITLE
[Bug]: QueryNodev2 load segment is not idempotent

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#23971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: fb6e4ce
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When a segment is load multiple time , instead of returning success, segment loader will load it again. Which may cause memory leak.

### Expected Behavior

Load segment is idempotent and no memory leak shall happen

### Anything else?

related to #23678

**Comment by jiaoew1991** [comment]
看上去被 https://github.com/milvus-io/milvus/pull/23968 修复了？

**Comment by yah01** [comment]
/assign @congqixia 
plz help verify it
