### ISSUE TITLE
是否可以支持按相似度检索和统计 是否可以支持分页检索

### ISSUE THREAD

**Issue by qiuchsh** [milvus-io/milvus#2398]
**What is your question?**

**Comment by JinHai-CN** [comment]
I will summrize your requirements as below:
1. SearchByDistance / SearchBySimilarity, we already planned to implement it.
2. What is '统计' you are talking about?
3. Is the '分页检索' similar with database function: cursor ?

**Comment by qiuchsh** [comment]
> I will summrize your requirements as below:
> 
> 1. SearchByDistance / SearchBySimilarity, we already planned to implement it.
> 2. What is '统计' you are talking about?
> 3. Is the '分页检索' similar with database function: cursor ?

1. 统计：相当于countByDistance / countBySimilarity，按条件检索结果总数，当然统计结果也可以直接在SearchByDistance / SearchBySimilarity结果集中一起返回（如果SearchByDistance / SearchBySimilarity结果集不是返回检索所有结果）
2. 分页检索：可以用cursor，例如：SearchByDistance结果有10万条，每页100条，则第一次就返回1~100，下一页返回101~200，以此类推，也可以跳转到指定页数，如最后一页 99901~100000，主要为解决前端显示和内存问题

**Comment by tinkerlin** [comment]
I already put this requirement into the backlog list. It will be dicussed in the plan meeting.
And could you please describe problem by using english this may help other developers who have the same problem around world.
@qiuchsh

**Comment by shengjun1985** [comment]
search by distance, let's traced in #1133
search in page, let's traced in #3851
