### ISSUE TITLE
[Bug]: `test_upsert_multiple_times` e2e case is not stable

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#23986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: ae6fccc
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

test_upsert_multiple_times fails randomly

### Expected Behavior

e2e case passes stably

**Comment by congqixia** [comment]
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-23976/4/pipeline

**Comment by xiaofan-luan** [comment]
we should not rely on num_entities, because compaction will also change it.
Try to use count in master

**Comment by xiaofan-luan** [comment]
2.2 don't have it, so it's gonna to be there
