### ISSUE TITLE
[Bug]: search very slow with (5000x64) datas

### ISSUE THREAD

**Issue by zhangjiulong** [milvus-io/milvus#23980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.x
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 64x128G
- GPU: 2
- Others:
```

### Current Behavior

I write shape of 5000x64 vectors to milvus and each vec is normed.
While searching  for 100 times  with similar metrics Inner product and index type FLAT each search cost 300ms or more.
But with gensim similar_by_vector method only cost 3ms?
I think it is unnormal.

**Comment by yanliang567** [comment]
@zhangjiulong thank you for the issue. I think there are 2 factors we need to think for this issue:
1. gensim is a lib, while milvus is a system, which is more heavier 
2. FLAT is brute-force search in milvus

Also there might be some issue for your deployment, in our benchmark, the search latency could be <10ms in 1m-128dim vectors. Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @zhangjiulong

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```gfm
> - Milvus version:2.x
> - Deployment mode(standalone or cluster):standalone
> - MQ type(rocksmq, pulsar or kafka):    
> - SDK version(e.g. pymilvus v2.0.0rc2):pymilvus
> - OS(Ubuntu or CentOS): ubuntu
> - CPU/Memory: 64x128G
> - GPU: 2
> - Others:
> ```
> 
> ### Current Behavior
> I write shape of 5000x64 vectors to milvus and each vec is normed. While searching for 100 times with similar metrics Inner product and index type FLAT each search cost 300ms or more. But with gensim similar_by_vector method only cost 3ms? I think it is unnormal.
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

if you can show your test script it will be super helpful

**Comment by zhangjiulong** [comment]
Hi guys， I read a reply sent with the name groot.  Contents like the following:
I guess you are using "Strong" consistency level to search. Try consistency_level="Bounded"

results = collection.search(  data=vectors,  anns_field=vector_field_name,  param=search_params,  limit=10,  consistency_level="Bounded" )
It worked. 

Thanks for guys and milvus group. Thanks.

**Comment by yanliang567** [comment]
great to hear that.
