### ISSUE TITLE
[Bug]: Insert failure when searching concurrently

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#23991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230509-fb6e4cee
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):   pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2):
```

### Current Behavior

insert 5m-128d entities for 5 times
1st error at 2nd time:
`2023/05/09 09:16:00.729 +00:00] [ERROR] [retry/retry.go:42] ["retry func failed"] ["retry time"=0] [error="data service save bin log path failed, reason = etcdserver: request timed out"] [stack="github.com/milvus-io/milvus/pkg/util/retry.Do\n\t/go/src/github.com/milvus-io/milvus/pkg/util/retry/retry.go:42\ngithub.com/milvus-io/milvus/internal/datanode.flushNotifyFunc.func1\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:818\ngithub.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).waitFinish\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:205"`
2nd error at 4th time, and some milvus pod restarted at this moment:
`2023/05/09 09:44:32.753 +00:00] [WARN] [grpcclient/client.go:299] ["ClientBase Call grpc first call get error"] [role=datacoord] [error="err: find no available datacoord, check datacoord state\n, /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:298 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call\n/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:389 github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).SaveBinlogPaths\n/go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:819 github.com/milvus-io/milvus/internal/datanode.flushNotifyFunc.func1.1\n/go/src/github.com/milvus-io/milvus/pkg/util/retry/retry.go:40 github.com/milvus-io/milvus/pkg/util/retry.Do\n/go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:818 github.com/milvus-io/milvus/internal/datanode.flushNotifyFunc.func1\n/go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:205 github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).waitFinish\n/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit\n"`

### Expected Behavior

no insert error

### Steps To Reproduce

```markdown
1. create a collection
2. insert 5m-128d vectors
3. 3. build index {'index_type': 'HNSW', 'metric_type': 'IP', 'params': {'M': 8, 'efConstruction': 96}}
4. load
5. keep searching Permanently
6. insert 5m-128d vectors for 5 times
```

### Milvus Log

milvus pods
```
yanliang-cd-mmszh-milvus-datanode-67f965cf-69dmx                  1/1     Running            0                  62m
yanliang-cd-mmszh-milvus-indexnode-85995c8cc4-gc2xs               1/1     Running            0                  62m
yanliang-cd-mmszh-milvus-indexnode-85995c8cc4-prhwf               1/1     Running            1 (8m29s ago)      62m
yanliang-cd-mmszh-milvus-indexnode-85995c8cc4-qlcgq               1/1     Running            0                  62m
yanliang-cd-mmszh-milvus-indexnode-85995c8cc4-s4lp9               1/1     Running            0                  62m
yanliang-cd-mmszh-milvus-mixcoord-ff849f99-8jtpf                  1/1     Running            1 (8m28s ago)      62m
yanliang-cd-mmszh-milvus-proxy-7899c889cc-ffqzs                   1/1     Running            0                  62m
yanliang-cd-mmszh-milvus-querynode-6d78c64847-b529f               1/1     Running            1 (7m15s ago)      62m
yanliang-cd-mmszh-milvus-querynode-6d78c64847-hxjh9               1/1     Running            1 (8m32s ago)      62m
yanliang-cd-mmszh-milvus-querynode-6d78c64847-nbhsn               1/1     Running            1 (8m59s ago)      62m
yanliang-cd-mmszh-milvus-querynode-6d78c64847-prv2z               1/1     Running            2 (8m34s ago)      62m
```

**Comment by yanliang567** [comment]
BTW, insertion is recoverable if new insert requests issued.

**Comment by xiaofan-luan** [comment]
seems that flush failed due to etcd request timeout

**Comment by yanliang567** [comment]
> seems that flush failed due to etcd request timeout

yes, and it reproduced when i recreated a new collection and insert for times today.
`2023/05/10 01:41:35.972 +00:00] [WARN] [grpclog/grpclog.go:46] ["[core][Channel #4 SubChannel #5] grpc: addrConn.createTransport failed to connect to {\n  \"Addr\": \"localhost:2379\",\n  \"ServerName\": \"localhost\",\n  \"Attributes\": null,\n  \"BalancerAttributes\": null,\n  \"Type\": 0,\n  \"Metadata\": null\n}. Err: connection error: desc = \"transport: Error while dialing: dial tcp [::1]:2379: connect: connection refused\""`

**Comment by jiaoew1991** [comment]
We have recently encountered many issues with slow Etcd writes. https://github.com/milvus-io/milvus/issues/23895
