### ISSUE TITLE
[Bug]: [perf]  Milvus' search qps in gist's dataset decreases by about half

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#24004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

**Milvus search qps's recent week of testing is about half the size of the original 2.2.6 release**
The leftmost version is 2.2.6-41d9ab3d, The image tested in the figure below is date+commitid

gist-768d-hsnw index
<img width="456" alt="截屏2023-05-10 11 44 03" src="https://github.com/milvus-io/milvus/assets/34296482/fa3c9e54-7ee4-4c97-93b4-415008c9e2ec">

gist-768d-ivf-flat index
<img width="427" alt="截屏2023-05-10 11 49 16" src="https://github.com/milvus-io/milvus/assets/34296482/7d012402-c155-4fdc-bf1d-171eacaf3130">

gist-768d-diskann  index
<img width="431" alt="截屏2023-05-10 11 49 53" src="https://github.com/milvus-io/milvus/assets/34296482/4e2803b4-0656-4404-a339-ea75e1c5ee68">

### Steps To Reproduce

```markdown
1. create a collection 
        2. build index on vector column
        3. insert a 1m gist768d of vectors
        4. flush collection
        5. build index on vector column with the same parameters
        6. count the total number of rows
        7. load collection
        8. hnsw, ivf_flat concurrent [1, 20, 50, 100] search , diskann  concurrent [1, 20] search
```

**Comment by yanliang567** [comment]
/assign @liliu-z 
it only reproduces on gist dataset.
/unassign

**Comment by liliu-z** [comment]
Looks like this drop happened between f9d6ece and 41d9ab, and the corresponding Knowhere version is 1.3.12 and 1.3.11 respectively

**Comment by liliu-z** [comment]
@jingkl can you help make sure we didn't use debug image for this test? This big jump looks scaring to me 
cc @yanliang567

**Comment by hhy3** [comment]
Perhaps I can not reproduce the results in the figure. Could you please provide more info like milvus configuration, hardware environment, and testing script?

**Comment by jiaoew1991** [comment]
/assign @yah01 
It seems that some PRs fixed the bugs on April 30th. 🤔

**Comment by yah01** [comment]
The `MaxNQ` config item has been increased, will bench on it

**Comment by yah01** [comment]
Nothing changes after modified the `MaxNQ` back to 1000

**Comment by yanliang567** [comment]
@jingkl does it reproduce recently?

**Comment by jingkl** [comment]
2.2.14 search performance back to normal, close issue
