### ISSUE TITLE
api is required for get index creating status

### ISSUE THREAD

**Issue by sunyaofei** [milvus-io/milvus#2402]
**Is your feature request related to a problem? Please describe.**
i use two milvus collection to do full data update(one is for search, one is for write, when write is done and index creating is done, write read switch), but i have no way to know when index creating is done

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by JinHai-CN** [comment]
I suppose GetCollectionInfo can meet your requirement.
@yhmo Would you please double confirm it?

**Comment by yhmo** [comment]
@sunyaofei 
Please use this api to get index information:

```
status, info = MILVUS.get_index_info(collection_name=TABLE_NAME)
print(status, info)
```

**Comment by yhmo** [comment]
To get index creating status, we can use get_collection_stat() api:

```
status, collection_info = MILVUS.get_collection_stats(collection_name=TABLE_NAME)
print(status, collection_info)
partition_list = collection_info["partitions"]
    for partition in partition_list:
        segment_list = partition["segments"]
        for segment in segment_list:
            segment_name = segment["name"]
            print(status, "segment", segment_name, "index type", segment["index_name"])
```

Firstly use get_collection_stats to get all segments information in json format, secondly iterate the json structure to know each segment index type, if the "index_name" of a segment is "IDMAP", that means this segment has no index, else the "index_name" could be "IVFLAT"/"IVFSQ8"/"IVFPQ",etc.
If none of the segments "index_name" is "IDMAP", that means this collection has finished build index.

**Comment by sunyaofei** [comment]
> To get index creating status, we can use get_collection_stat() api:
> 
> ```
> status, collection_info = MILVUS.get_collection_stats(collection_name=TABLE_NAME)
> print(status, collection_info)
> partition_list = collection_info["partitions"]
>     for partition in partition_list:
>         segment_list = partition["segments"]
>         for segment in segment_list:
>             segment_name = segment["name"]
>             print(status, "segment", segment_name, "index type", segment["index_name"])
> ```
> 
> Firstly use get_collection_stats to get all segments information in json format, secondly iterate the json structure to know each segment index type, if the "index_name" of a segment is "IDMAP", that means this segment has no index, else the "index_name" could be "IVFLAT"/"IVFSQ8"/"IVFPQ",etc.
> If none of the segments "index_name" is "IDMAP", that means this collection has finished build index.

get it, thx

**Comment by sunyaofei** [comment]
> To get index creating status, we can use get_collection_stat() api:
> 
> ```
> status, collection_info = MILVUS.get_collection_stats(collection_name=TABLE_NAME)
> print(status, collection_info)
> partition_list = collection_info["partitions"]
>     for partition in partition_list:
>         segment_list = partition["segments"]
>         for segment in segment_list:
>             segment_name = segment["name"]
>             print(status, "segment", segment_name, "index type", segment["index_name"])
> ```
> 
> Firstly use get_collection_stats to get all segments information in json format, secondly iterate the json structure to know each segment index type, if the "index_name" of a segment is "IDMAP", that means this segment has no index, else the "index_name" could be "IVFLAT"/"IVFSQ8"/"IVFPQ",etc.
> If none of the segments "index_name" is "IDMAP", that means this collection has finished build index.


small data size(<5000) will not create index, see ref below
https://github.com/milvus-io/milvus/blob/423098dcb3228f3853351ae5fa66cccf02f96668/core/src/db/DBImpl.cpp#L1597
