### ISSUE TITLE
[Bug]: failed to get file size of 'rowjson.json', error:The specified key does not exist.

### ISSUE THREAD

**Issue by maqiang515** [milvus-io/milvus#24028]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.5
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1、minio的bucket使用的默认：milvus-bucket
2、使用bulkinsert方法：
BulkInsertParam bulkParam = BulkInsertParam.newBuilder()
                .withCollectionName(COLLECTION_NAME)
                .withPartitionName("p1")
                //.withFiles(Arrays.asList("rowjson.json"))
                .addFile("rowjson.json")
                .build();
报：failed to get file size of 'rowjson.json', error:The specified key does not exist.
3、使用minio客户端读此文件可以读取文件内容
![image](https://github.com/milvus-io/milvus/assets/11402161/36ecbfcb-0e3c-4cd4-b39a-18d2bf4cfedd)

**Comment by sunmingqiaa** [comment]
i meet this too

**Comment by sunmingqiaa** [comment]
我的解决了，不能直接copy文件到minio目录下，需要用minio api上传

**Comment by yanliang567** [comment]
> 我的解决了，不能直接copy文件到minio目录下，需要用minio api上传

Yes, minio encodes and decodes files with its api, so if you directly copy the files to the mino folder, it is not able to read them.

**Comment by yanliang567** [comment]
i'd close this issue. thank you for the updates, and feel free to file new issues.

**Comment by maqiang515** [comment]
> 我的解决了，不能直接copy文件到minio目录下，需要用minio api上传

怎么解决的，我是通过API上传的 FileUtils.multiFilesUpload(path, filenames, null);

**Comment by maqiang515** [comment]
> i'd close this issue. thank you for the updates, and feel free to file new issues.

别关呀，我的是通过API上传的，这个就是mi'lvus的jdk包里面的
![image](https://github.com/milvus-io/milvus/assets/11402161/49fce360-875c-45cc-8169-f0746f5ab4cf)

**Comment by maqiang515** [comment]
> you shall use minio sdk to upload the files to minio folder first, then use milvus sdk to bulk insert data into milvus. here is an example using python minio api to upload files to minio: https://github.com/milvus-io/milvus/blob/master/tests/python_client/bulk_insert/minio_comm.py

![image](https://github.com/milvus-io/milvus/assets/11402161/8bc6ef8b-2cc5-4ac3-a469-ee5fa03a368c)
我是通过upload方法放到minio，这个可以么

**Comment by yanliang567** [comment]
> > you shall use minio sdk to upload the files to minio folder first, then use milvus sdk to bulk insert data into milvus. here is an example using python minio api to upload files to minio: https://github.com/milvus-io/milvus/blob/master/tests/python_client/bulk_insert/minio_comm.py
> 
> ![image](https://user-images.githubusercontent.com/11402161/237852824-8bc6ef8b-2cc5-4ac3-a469-ee5fa03a368c.png) 我是通过upload方法放到minio，这个可以么

I think is okay to use minioClient.uploadObject(), which was used in our java sdk testing.

**Comment by maqiang515** [comment]
> > > you shall use minio sdk to upload the files to minio folder first, then use milvus sdk to bulk insert data into milvus. here is an example using python minio api to upload files to minio: https://github.com/milvus-io/milvus/blob/master/tests/python_client/bulk_insert/minio_comm.py
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/11402161/237852824-8bc6ef8b-2cc5-4ac3-a469-ee5fa03a368c.png) 我是通过upload方法放到minio，这个可以么
> 
> I think is okay to use minioClient.uploadObject(), which was used in our java sdk testing. please make sure you update the correct milvus-bucket name to your deployment.

![image](https://github.com/milvus-io/milvus/assets/11402161/0ca08d01-4c16-4e87-a9d9-fbfe63db11cf)
这块检查了，是默认的名字

**Comment by yanliang567** [comment]
@yongpengli-z could you please double check it works with java sdk?
/assign @yongpengli-z

**Comment by maqiang515** [comment]
配了一个桶名称可以了，但是默认文档中还是
![image](https://github.com/milvus-io/milvus/assets/11402161/8b14328b-ea2a-479e-b9c8-bec3f13753e5)
这是我配置的，唉
![image](https://github.com/milvus-io/milvus/assets/11402161/0c3d2706-b1ad-4373-84ac-fe2cda9cb68c)

**Comment by UshaPravinkumar** [comment]
Using Java sdk, it is not working. I'm still getting the below error.
Failed Reason:failed to get file size of 'a-bucket/food_review_bulk_sample.json', error:The specified key does not exist.

Any solution or workaround for this case?

**Comment by xiaofan-luan** [comment]
> x-bucke

Did you set the correct bucket name?

**Comment by xiaofan-luan** [comment]
> Using Java sdk, it is not working. I'm still getting the below error. Failed Reason:failed to get file size of 'x-bucket/sample.json', error:The specified key does not exist.
> 
> Any solution or workaround for this case?

please check the example at pymilvus 
https://github.com/milvus-io/pymilvus/blob/6e6d80bf5e5e188ec3aa4edb09add7b59506b47f/examples/example_bulkinsert_json.py#L4

**Comment by UshaPravinkumar** [comment]
> > Using Java sdk, it is not working. I'm still getting the below error. Failed Reason:failed to get file size of 'x-bucket/sample.json', error:The specified key does not exist.
> > Any solution or workaround for this case?
> 
> please check the example at pymilvus https://github.com/milvus-io/pymilvus/blob/6e6d80bf5e5e188ec3aa4edb09add7b59506b47f/examples/example_bulkinsert_json.py#L4

I could upload files, download or read those files from the bucket using minioclient object. But unable to bulk insert operation using MilvusServiceClient object.
The bucket name is correct.
