### ISSUE TITLE
[Bug]: Yaml parse failed when create new dev container

### ISSUE THREAD

**Issue by caesarjuly** [milvus-io/milvus#24026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu 22.04
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When use `./scripts/devcontainer.sh up` cmd to start containers, a `docker-compose-devcontainer.yml` file will be generated from `docker-compose.yml`. But according to the bash script [here](https://github.com/milvus-io/milvus/blob/0c99399f3553fc3c1edb7f8bb38feff61abe89a6/scripts/devcontainer.sh#L58), it only comment out 5 lines.
``` awk 'c&&c--{sub(/^/,"#")} /# Build devcontainer/{c=5} 1' $ROOT_DIR/docker-compose.yml > $ROOT_DIR/docker-compose-devcontainer.yml.tmp```

So the following [line](https://github.com/milvus-io/milvus/blob/0c99399f3553fc3c1edb7f8bb38feff61abe89a6/docker-compose.yml#L56) will be ignored, this leads to a wrong format in the yml file. The container will fail to run.
```- ${IMAGE_REPO}/milvus-env:${IMAGE_ARCH}-${OS_NAME}-${LATEST_DATE_VERSION}```

### Expected Behavior

Docker container run successfully

### Steps To Reproduce

```markdown
Run `./scripts/devcontainer.sh up ` on master branch
```

### Milvus Log

```
ERROR: yaml.parser.ParserError: while parsing a block mapping
  in "/home/fan/Projects/go/src/milvus/docker-compose-devcontainer.yml", line 49, column 5
expected <block end>, but found '<block sequence start>'
  in "/home/fan/Projects/go/src/milvus/docker-compose-devcontainer.yml", line 56, column 9
```

**Comment by yanliang567** [comment]
@caesarjuly i 'd close this issue for the pr was merged. thank you for your fixing
