### ISSUE TITLE
distributed collection indexing to multi machine, more than one milvus writable is required

### ISSUE THREAD

**Issue by sunyaofei** [milvus-io/milvus#2404]
**Is your feature request related to a problem? Please describe.**
When i have more than one collection in a milvus cluster(one writable, more than one readonly), indexing will be in one machine, causing indexing time is long when multi collection indexing is invoked at same time or during a short time span. 

Advanced expect, distributed collection indexing for a single collection

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by JinHai-CN** [comment]
1. Indexing will be invoked one collection by another. 
2. We are planning the multiple-write distributed solution.

**Comment by yhmo** [comment]
v2.0 implement this.
