### ISSUE TITLE
search timeout for a while

### ISSUE THREAD

**Issue by dzqoo** [milvus-io/milvus#24065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.2
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 6c32gb
- GPU: 
- Others:
```

### Current Behavior

The search is timeout for 3 mins when my cluster reach the business peak period.
1. Here is the **_Search Latency_** dashboard:
![image](https://github.com/milvus-io/milvus/assets/8862305/c9371d9f-bc03-4f66-8472-72c345b8bab1)
2. Here are parts of querynode metrics and _**Search Segment Latency**_ is quite well:
![image](https://github.com/milvus-io/milvus/assets/8862305/2762f993-f3d2-44a8-b449-a8d410458a41)
3. Here is _**Search Group NQ**_ dashboard which is shaked at the same time:
![image](https://github.com/milvus-io/milvus/assets/8862305/2c2f1575-c7b4-48a3-ba61-1b7dbf078c8f)

This cluster is my online environment and I hope to providing a solution and reasons as soon as possible.Thanks a lot~

### Milvus Log

[Uploading milvus.log.tar.gz…]()
[Uploading milvus.log.tar.gz…]()

**Comment by dzqoo** [comment]
5. Here are parts of runtime metrics
![image](https://github.com/milvus-io/milvus/assets/8862305/6944e0b1-0080-4bd2-a577-821077c53815)
![image](https://github.com/milvus-io/milvus/assets/8862305/7922aad9-d49c-44b7-ac04-09d8d297b895)

**Comment by xiaofan-luan** [comment]
> 5. Here are parts of runtime metrics
>    ![image](https://user-images.githubusercontent.com/8862305/237868812-6944e0b1-0080-4bd2-a577-821077c53815.png)
>    ![image](https://user-images.githubusercontent.com/8862305/237868851-7922aad9-d49c-44b7-ac04-09d8d297b895.png)

If you look at your metrics, seems that queue time is very large, which triggered search merge logic.

Did you have chance to try 2.2.8? I remember we have some fix on the search merge logic

**Comment by dzqoo** [comment]
> > 5. Here are parts of runtime metrics
> >    ![image](https://user-images.githubusercontent.com/8862305/237868812-6944e0b1-0080-4bd2-a577-821077c53815.png)
> >    ![image](https://user-images.githubusercontent.com/8862305/237868851-7922aad9-d49c-44b7-ac04-09d8d297b895.png)
> 
> If you look at your metrics, seems that queue time is very large, which triggered search merge logic.
> 
> Did you have chance to try 2.2.8? I remember we have some fix on the search merge logic
Can I know which specific merge logic is causing it?

**Comment by dzqoo** [comment]
I encountered this problem again today .><.
Search is timeout for ~2 min and at the same while, the "search reduce latency" metrics  is quite high as you see  in the following:
![image](https://github.com/milvus-io/milvus/assets/8862305/57cd92f1-fbfa-4cbc-b6fb-9a82d2ded509)
I wonder to know if this problem has been resolved in the latest version（2.2.8 or 2.2.9).
Looking forward to your reply~

**Comment by dzqoo** [comment]
I found that at the same time,the goroutine of this  querynode is pretty high as you :
![image](https://github.com/milvus-io/milvus/assets/8862305/45b40445-0a86-40a7-be6a-6ce6106ff9bb)

**Comment by dzqoo** [comment]
![image](https://github.com/milvus-io/milvus/assets/8862305/77b2907f-66ee-44c4-83af-d1472351a48d)
I encountered this issue again when I upgraded to version 2.2.9...

**Comment by yanliang567** [comment]
any insertion or delete requests at that time? could you please share the cpu usage of querynodes

**Comment by dzqoo** [comment]
![image](https://github.com/milvus-io/milvus/assets/8862305/9f4eb1ee-cdde-42e4-83db-e59bbda1a8dd)
![image](https://github.com/milvus-io/milvus/assets/8862305/0db74453-3f53-4fd6-b0dd-b9322142e959)
![image](https://github.com/milvus-io/milvus/assets/8862305/aa28a39f-d110-4206-85a2-3bced5f4b252)
I have no insertion or delete requests at the same time. The cpu usage is showed as you see in the pic.

**Comment by dzqoo** [comment]
![1aa1232538f16f1c53aaf8d0c69d2a2](https://github.com/milvus-io/milvus/assets/8862305/657a9e7c-346b-4a2f-96d0-b171e6c9e9aa)
"Search Group NQ" at the same time.

**Comment by yanliang567** [comment]
seems that the nq group size increased during the business peak period. a known issue that we are trying to fix? @liliu-z

**Comment by liliu-z** [comment]
Hi @dzqoo , Looks like that we don't have any QPS bumping during this time, and from the info we have right now, I don't have too much ideas. Can you help screenshot all graph looks abnormal during that time?
Also can you check if there is any growing segment that time?
Thanks

**Comment by liliu-z** [comment]
More info is needed, especially for querynode. Also resource usage graph you provided, like CPU, Memeory, I didn't querynode inside them. Can you help provide some infos about this? Thanks

**Comment by dzqoo** [comment]
![image](https://github.com/milvus-io/milvus/assets/8862305/37975441-63ae-439f-9307-40356e12012e)
![image](https://github.com/milvus-io/milvus/assets/8862305/88c10417-b1dc-42bc-aae8-db1d3e134d0e)
![image](https://github.com/milvus-io/milvus/assets/8862305/71cb1195-29ed-41af-b5ed-ee9ef0010564)
![image](https://github.com/milvus-io/milvus/assets/8862305/3c6149ff-3aa4-4c86-a821-c797c52a13b0)
![image](https://github.com/milvus-io/milvus/assets/8862305/cc76994d-5b80-49cd-a818-8bcd6e6b8ab1)
![image](https://github.com/milvus-io/milvus/assets/8862305/d1923319-1f5a-47f5-a341-e4eb4683cf42)
![image](https://github.com/milvus-io/milvus/assets/8862305/f3e2618e-06ee-43d1-9a6b-98dbb200d40c)
![image](https://github.com/milvus-io/milvus/assets/8862305/ffaff314-fc0c-4cd8-a156-9078d7703e61)
![image](https://github.com/milvus-io/milvus/assets/8862305/adb3edb0-8c49-49ae-80de-f0533b9368b8)
![image](https://github.com/milvus-io/milvus/assets/8862305/bf4b6cd2-e748-499a-b8af-e87ff9355eda)
![image](https://github.com/milvus-io/milvus/assets/8862305/e021ef4b-4557-468c-a489-b598978e034d)
![image](https://github.com/milvus-io/milvus/assets/8862305/31e55f52-23b3-42a4-8cb8-74a01d589403)

**Comment by liliu-z** [comment]
Can I get more infos like:
1. How much data we have and in what dimension?
2. How many querynode we have and what type are they?
3. How many collections we have?
4. How many segments for each collections and each querynode. From the grafana page all data stack together and make it hard to tell.
Thanks

**Comment by dzqoo** [comment]
> @dzqoo Can I get more infos like:
> 
> 1. How much data we have and in what dimension?
> 2. How many querynode we have and what type are they?
> 3. How many collections we have?
> 4. How many segments for each collections and each querynode. From the grafana page all data stack together and make it hard to tell.
>    Thanks

1. We have ~1 billion data in about 10 collections which dimensions are range from 128 to 768;
2. We have 15 querynode and 32gb6c for each querynode;
3. the segments in each querynode is showed as you see:
![image](https://github.com/milvus-io/milvus/assets/8862305/0d6afe5b-977d-471d-8e47-01f3008bd6fd)

**Comment by liliu-z** [comment]
@dzqoo Can I have the segment distribution of the specific collection you queried? Thanks!

**Comment by dzqoo** [comment]
> @dzqoo Can I have the segment distribution of the specific collection you queried? Thanks! And also what dim is that collection and how many rows.

All tables have timed out retrieval... @liliu-z

**Comment by xiaofan-luan** [comment]
could you try the latest version? 
I fix many performance issues in the last 6 months. We'd like to init a meeting if the newest version still not stable, but we probably don't want to spend time on investigating staled issues.

**Comment by xiaofan-luan** [comment]
2.2.11 should be at least 50% faster to 2.2.2 and we solved many balanced issues and stability issues

**Comment by dzqoo** [comment]
Thank you for your reply~And when does the version 2.3 come out？I want to go directly to version 2.3.

**Comment by xiaofan-luan** [comment]
I will be released next week ~
