### ISSUE TITLE
[Bug]: The attu cannot log in

### ISSUE THREAD

**Issue by xiao12mm** [milvus-io/milvus#24066]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.8
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.2.8
- OS(Ubuntu or CentOS): centos
- CPU/Memory: Intel(R) Xeon(R) Gold 6278C CPU @ 2.60GHz 32 core  Memory:252G
- GPU: v100 32G *4
- Others:
```

### Current Behavior

I used docker-compose to install milvus stand-alone,version=2.2.8, and then attu,version=2.2.5. I could open the attu landing page, but I could not log in, and there was no error on the page

### Steps To Reproduce

```markdown
Successful login
```

### Milvus Log

Error: 14 UNAVAILABLE: Name resolution failed for target dns:{x.x.x.x:19530}:19530
    at callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at /app/node_modules/@grpc/grpc-js/build/src/call-interface.js:78:35
    at Object.onReceiveStatus (/app/node_modules/@zilliz/milvus2-sdk-node/dist/utils/Grpc.js:138:45)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /app/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/app/node_modules/@grpc/grpc-js/build/src/client.js:160:34)
    at ServiceClientImpl.<anonymous> (/app/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at /app/node_modules/@zilliz/milvus2-sdk-node/dist/utils/Function.js:19:24
    at new Promise (<anonymous>)
    at promisify (/app/node_modules/@zilliz/milvus2-sdk-node/dist/utils/Function.js:16:15)
    at MilvusClient.<anonymous> (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/GrpcClient.js:227:72)
    at step (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/GrpcClient.js:59:23)
    at Object.next (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/GrpcClient.js:40:53)
    at /app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/GrpcClient.js:34:71
    at new Promise (<anonymous>) {
  code: 14,
  details: 'Name resolution failed for target dns:{x.x.x.x}:19530',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} },
  expose: true,
  statusCode: 400,
  status: 400
}
POST /api/v1/milvus/connect 400 Error: 14 UNAVAILABLE: Name resolution failed for target dns:{x.x.x.x}:19530

 POST 400 /api/v1/milvus/connect 452.878 ms @ Fri, 12 May 2023 04:55:34 GMT ::ffff:103.102.192.138 from undefined Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

Error: 14 UNAVAILABLE: Name resolution failed for target dns:{x.x.x.x}:19530
    at callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at /app/node_modules/@grpc/grpc-js/build/src/call-interface.js:78:35
    at Object.onReceiveStatus (/app/node_modules/@zilliz/milvus2-sdk-node/dist/utils/Grpc.js:138:45)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /app/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/app/node_modules/@grpc/grpc-js/build/src/client.js:160:34)
    at ServiceClientImpl.<anonymous> (/app/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at /app/node_modules/@zilliz/milvus2-sdk-node/dist/utils/Function.js:19:24
    at new Promise (<anonymous>)
    at promisify (/app/node_modules/@zilliz/milvus2-sdk-node/dist/utils/Function.js:16:15)
    at MilvusClient.<anonymous> (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/GrpcClient.js:227:72)
    at step (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/GrpcClient.js:59:23)
    at Object.next (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/GrpcClient.js:40:53)
    at /app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/GrpcClient.js:34:71
    at new Promise (<anonymous>) {
  code: 14,
  details: 'Name resolution failed for target dns:{x.x.x.x}:19530',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} },
  expose: true,
  statusCode: 400,
  status: 400
}
POST /api/v1/milvus/connect 400 Error: 14 UNAVAILABLE: Name resolution failed for target dns:{x.x.x.x}:19530

 POST 400 /api/v1/milvus/connect 364.594 ms @ Fri, 12 May 2023 04:55:35 GMT ::ffff:103.102.192.138 from undefined Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

### Anything else?

no yet

**Comment by xiao12mm** [comment]
Clients running the windows version of attu can log in normally

**Comment by shanghaikid** [comment]
139.9.248.174:19530, please make sure that you can access the ip address from the pc that attu installed. 
- check if you have vpn installed and opened ? 
- test if the port is opened to your pc, you can telnet to the address via [this way](https://kb.synology.com/en-me/DSM/tutorial/Whether_TCP_port_is_open_or_closed#:~:text=Press%20the%20Windows%20key%20%2B%20R,only%20a%20cursor%20will%20show.`)

**Comment by xiao12mm** [comment]
This IP address is a public IP address and 19530 can be pinged through. The web side can access port 8000, and can access the web page, but cannot log in to it. I use windows client is able to successfully login and operationthis IP is

**Comment by shanghaikid** [comment]
You need to test if the server's port is opened. it can be pinged doesn't mean your milvus cluster is accessible from your pc. ping use ICMP protocol. 


```'Name resolution failed for target dns:{x.x.x.x}:19530',```  means the attu server can not access the milvus server, so please ensure the communication is ok between two sides.

**Comment by xiao12mm** [comment]
Port 8000 and port 19530 of the target IP address are normal.

Why can I log in normally with windows client? Do they use different protocols?

**Comment by shanghaikid** [comment]
Ok, let me explain. 

1. attu windows application
if your can connect to the milvus cluster from your pc, that means your windows attu can send request to the milvus cluster. 

2. attu docker version
if your pc can open the webpage of attu, only means your pc can access the attu server,  that doesn't mean the attu server can send request to the milvus cluster.  **the request is sending from attu server** you need to ensure the attu server and milvus server in the same network.

**Comment by xiao12mm** [comment]
Yes, milvus' access IP is the same as attu's.    They are created using the same server docker environment.    I was able to log in successfully a few days ago, but this problem occurred after the message queue was blocked a few days ago.    Now that I have fixed the message queue, the problem arises
At the same time, I was able to successfully access and create collections and indexes using python code, and I could successfully insert data

**Comment by shanghaikid** [comment]
> Yes, milvus' access IP is the same as attu's. They are created using the same server docker environment. I was able to log in successfully a few days ago, but this problem occurred after the message queue was blocked a few days ago. Now that I have fixed the message queue, the problem arises At the same time, I was able to successfully access and create collections and indexes using python code, and I could successfully insert data

Can you execute your python code from your server (where attu installed)

**Comment by xiao12mm** [comment]
let me try

**Comment by xiao12mm** [comment]
```
93e270c1f2ea   zilliz/attu:v2.2.5       "docker-entrypoint.s…"   30 hours ago   Up 30 hours   0.0.0.0:8000->3000/tcp, :::8000->3000/tcp   reverent_brown
25585c32015c   milvusdb/milvus:v2.2.3   "/tini -- milvus run…"   30 hours ago   Up 30 hours                                               proxy
a1aa00141c7e   milvusdb/milvus:v2.2.3   "/tini -- milvus run…"   30 hours ago   Up 30 hours                                               querycoord
ed445805d9f3   milvusdb/milvus:v2.2.3   "/tini -- milvus run…"   30 hours ago   Up 30 hours                                               datacoord
2a24e09ca09d   milvusdb/milvus:v2.2.3   "/tini -- milvus run…"   30 hours ago   Up 30 hours                                               indexcoord
cc935a30690e   milvusdb/milvus:v2.2.3   "/tini -- milvus run…"   30 hours ago   Up 30 hours                                               rootcoord

```
This is the service installed on my server's docker
On this server, I can use python scripts to connect to milvus and operate

**Comment by shanghaikid** [comment]
> ```
> 93e270c1f2ea   zilliz/attu:v2.2.5       "docker-entrypoint.s…"   30 hours ago   Up 30 hours   0.0.0.0:8000->3000/tcp, :::8000->3000/tcp   reverent_brown
> 25585c32015c   milvusdb/milvus:v2.2.3   "/tini -- milvus run…"   30 hours ago   Up 30 hours                                               proxy
> a1aa00141c7e   milvusdb/milvus:v2.2.3   "/tini -- milvus run…"   30 hours ago   Up 30 hours                                               querycoord
> ed445805d9f3   milvusdb/milvus:v2.2.3   "/tini -- milvus run…"   30 hours ago   Up 30 hours                                               datacoord
> 2a24e09ca09d   milvusdb/milvus:v2.2.3   "/tini -- milvus run…"   30 hours ago   Up 30 hours                                               indexcoord
> cc935a30690e   milvusdb/milvus:v2.2.3   "/tini -- milvus run…"   30 hours ago   Up 30 hours                                               rootcoord
> ```
> 
> This is the service installed on my server's docker On this server, I can use python scripts to connect to milvus and operate

That's weird.
- you can access attu webpage, that means the connection between your pc to attu is good. 
- you can run python script from your pc to the milvus, that means the milvus server is working as expected.
- you can run **the same python script**  in the server, that means in the server, everything should be ok...
