### ISSUE TITLE
[Bug]: Memory of one querynode keeps high after doing upsert

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#24083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230512-7e645dab
- Deployment mode(standalone or cluster): cluster with 6 querynodes
- MQ type(rocksmq, pulsar or kafka):   pulsar
```

### Current Behavior

memory usage of a query node keeps high after upserting
![image](https://github.com/milvus-io/milvus/assets/82361606/5edf1d75-1cd7-4092-9f51-ea56d8edd678)

### Expected Behavior

memory reduces to balanced after a few mins

### Steps To Reproduce

```markdown
1. deploy a milvus cluster with 6 querynodes
2. insert 20m-128d entities 
3. build index hnsw
4. keep searching permanently
5. upsert(delete and insert 2m data)
```

### Milvus Log

milvus pods:
```
yanliang-cd-mmszh-milvus-datanode-78b6f74cb9-2cqw7               1/1     Running            0                5h54m   10.102.6.147    devops-node10   <none>           <none>
yanliang-cd-mmszh-milvus-datanode-78b6f74cb9-99s55               1/1     Running            0                5h53m   10.102.9.189    devops-node13   <none>           <none>
yanliang-cd-mmszh-milvus-indexnode-89bbc8856-7lskb               1/1     Running            0                5h54m   10.102.9.187    devops-node13   <none>           <none>
yanliang-cd-mmszh-milvus-indexnode-89bbc8856-z7qhg               1/1     Running            0                5h53m   10.102.6.152    devops-node10   <none>           <none>
yanliang-cd-mmszh-milvus-mixcoord-79d568cbfc-wjdwl               1/1     Running            0                5h54m   10.102.9.188    devops-node13   <none>           <none>
yanliang-cd-mmszh-milvus-proxy-86bbb76b79-scjsr                  1/1     Running            0                5h54m   10.102.6.149    devops-node10   <none>           <none>
yanliang-cd-mmszh-milvus-querynode-8fdb44fc-4www4                1/1     Running            0                5h53m   10.102.5.168    devops-node21   <none>           <none>
yanliang-cd-mmszh-milvus-querynode-8fdb44fc-9lgr2                1/1     Running            0                5h54m   10.102.9.186    devops-node13   <none>           <none>
yanliang-cd-mmszh-milvus-querynode-8fdb44fc-b5b9t                1/1     Running            0                5h53m   10.102.9.190    devops-node13   <none>           <none>
yanliang-cd-mmszh-milvus-querynode-8fdb44fc-gwpnz                1/1     Running            0                5h53m   10.102.7.59     devops-node11   <none>           <none>
yanliang-cd-mmszh-milvus-querynode-8fdb44fc-tz47r                1/1     Running            0                5h53m   10.102.10.24    devops-node20   <none>           <none>
yanliang-cd-mmszh-milvus-querynode-8fdb44fc-w6rjk 
```

**Comment by jiaoew1991** [comment]
/assign @smellthemoon 
/unassign 

@aoiasd has been investigating a lot of memory issues recently, @smellthemoon  you can consult with him for some experience.

**Comment by xiaofan-luan** [comment]
this might be reasonable? 
Upsert didn't delete real data right? but seems the memory usage is high and not balanced

**Comment by yanliang567** [comment]
yes, it leads to an OOM in the next round of upsert.

**Comment by yanliang567** [comment]
reproduced on master-20230524-e206265d with kafka
![image](https://github.com/milvus-io/milvus/assets/82361606/f3bf0797-d446-4d2b-a9fb-641375eb05db)

```
yanliang-kafka-milvus-datanode-75cdbc4758-2znlz                   1/1     Running            0                 7h6m
yanliang-kafka-milvus-indexnode-67544d6897-j5ff4                  1/1     Running            0                 7h6m
yanliang-kafka-milvus-indexnode-67544d6897-jz86l                  1/1     Running            0                 7h6m
yanliang-kafka-milvus-mixcoord-6c878f465b-v2d4q                   1/1     Running            0                 7h6m
yanliang-kafka-milvus-proxy-84d479444-rnvpc                       1/1     Running            0                 7h6m
yanliang-kafka-milvus-querynode-669cbdc7d8-2g9mk                  1/1     Running            0                 7h6m
yanliang-kafka-milvus-querynode-669cbdc7d8-7pd4h                  1/1     Running            0                 7h6m
yanliang-kafka-milvus-querynode-669cbdc7d8-fd8vh                  1/1     Running            0                 7h6m
yanliang-kafka-milvus-querynode-669cbdc7d8-xzbnk                  1/1     Running            0                 7h6m
```

**Comment by yanliang567** [comment]
it reproduces today when doing only insert
![image](https://github.com/milvus-io/milvus/assets/82361606/878675fe-537f-4e3f-86ad-80c40fe2f4d9)

```
yanliang-cd-mmszh-milvus-datanode-84dc7fdc9d-6gmjj                1/1     Running       0               8d      10.102.7.163    devops-node11   <none>           <none>
yanliang-cd-mmszh-milvus-datanode-84dc7fdc9d-tqmh8                1/1     Running       0               8d      10.102.6.120    devops-node10   <none>           <none>
yanliang-cd-mmszh-milvus-indexnode-5645dcbdf-6w8tn                1/1     Running       0               8d      10.102.6.151    devops-node10   <none>           <none>
yanliang-cd-mmszh-milvus-indexnode-5645dcbdf-tk7jd                1/1     Running       0               8d      10.102.9.47     devops-node13   <none>           <none>
yanliang-cd-mmszh-milvus-mixcoord-b46bf6b68-w7s4l                 1/1     Running       0               8d      10.102.9.48     devops-node13   <none>           <none>
yanliang-cd-mmszh-milvus-proxy-6df5788676-lhzd5                   1/1     Running       0               8d      10.102.9.53     devops-node13   <none>           <none>
yanliang-cd-mmszh-milvus-querynode-f8878984-7wjh8                 1/1     Running       0               17h     10.102.10.64    devops-node20   <none>           <none>
yanliang-cd-mmszh-milvus-querynode-f8878984-hwpg2                 1/1     Running       0               17h     10.102.5.111    devops-node21   <none>           <none>
yanliang-cd-mmszh-milvus-querynode-f8878984-j9696                 1/1     Running       0               17h     10.102.9.172    devops-node13   <none>           <none>
yanliang-cd-mmszh-milvus-querynode-f8878984-l847r                 1/1     Running       0               17h     10.102.9.173    devops-node13   <none>           <none>
yanliang-cd-mmszh-milvus-querynode-f8878984-msk4j                 1/1     Running       0               17h     10.102.7.99     devops-node11   <none>           <none>
yanliang-cd-mmszh-milvus-querynode-f8878984-z6x85                 1/1     Running       0               17h     10.102.6.241    devops-node10   <none>           <none>

```

**Comment by smellthemoon** [comment]
some place where the buffer returned by mq has not been released. The phenomenon observed at that time is that the memory on the go side has not been released. Unable to determine which msg is not released temporarily.

**Comment by xiaofan-luan** [comment]
@smellthemoon this is a critical issue. please work with @yanliang567 to reproduce and leave the scenario

**Comment by xiaofan-luan** [comment]
@smellthemoon 
please work on a tool to enable pprof every 1 minutes to generate debug infos

**Comment by smellthemoon** [comment]
The main reason for the memory consumption is that when the binlog writer calls the data organization insert log, it copies and consumes memory and when sends the insert log in the memory to minio, and the copy happened again.
<img width="369" alt="1" src="https://github.com/milvus-io/milvus/assets/64083300/e99cebe2-32d5-47c3-834f-795cc8b0907a">
<img width="397" alt="2" src="https://github.com/milvus-io/milvus/assets/64083300/fdb46ed0-a06d-4053-96a0-a3a2072d960a">

**Comment by smellthemoon** [comment]
Add a payload writer on the go side and then go gc manages this part of memory may help to solve it. #24656

**Comment by smellthemoon** [comment]
It is not reproduced on a single qn. It is guessed that the reason for the increase in memory is that in the insert phase, the sealed segment without an index will be loaded as growing, which will cause the leader to consume too much memory. The root cause is that indexing is too slow.

**Comment by MrPresent-Han** [comment]
I believe this is sth related to segment-load strategy, according to the log, we can see a following case:
growing A flushed, growing B flushed
A, B->C
C, D-> E
E is a large segment and it was indexed successfully, but before the E segment's index was loaded, growing A and B cannot be released.
Whereas when E index is completed, mixCoord continuously tried to load E segment onto node-345, where the all growing segments are located due to the fact there is only one channel. It leads to the problem that loading segment constantly failed because of memory insufficiency  and original two growing segments cannot be released, generating a kind of dead-lock case in this situation.

pay attention to segment: 441686852518715233

**Comment by xiaofan-luan** [comment]
> I believe this is sth related to segment-load strategy, according to the log, we can see a following case: growing A flushed, growing B flushed A, B->C C, D-> E E is a large segment and it was indexed successfully, but before the E segment's index was loaded, growing A and B cannot be released. Whereas when E index is completed, mixCoord continuously tried to load E segment onto node-345, where the all growing segments are located due to the fact there is only one channel. It leads to the problem that loading segment constantly failed because of memory insufficiency and original two growing segments cannot be released, generating a kind of dead-lock case in this situation.
> 
> pay attention to segment: 441686852518715233

Might be a valid guess.
We should try to load the segment to other node?

**Comment by MrPresent-Han** [comment]
Besides, regarding the reason of former growing segments accumulation, I guess it is because the existing segment_checker didn't correctly release dropped previous growing segment.

consider segment: 441686852518715233
this segment is add as growing at 09:37 on node-345, and then it's flushed and loaded as history segment on node 352
then at 09:41, it was compacted and dropped, so segment checker decided to release this segment on node-352 with scope=all. but the matched growing segment was on node-345.

So indeed, this segment was never released in shard-leader-distribution and segment checker constantly considered that it's in the current target. So it will not be released forever and lead to memory increasement

**Comment by MrPresent-Han** [comment]
For the accumulation of growing segments at the beginning. It's very weird that loadSegmentsRequest needTransfer is **false**, which will lead to release growing segment failure. And it seems that there are differences in the version of query nodes.

Could you restart a new cluster using the master-latest and reproduce the issue concerning insert or upset?
@yanliang567

**Comment by arunk054** [comment]
Hi, we are facing the same issue. Is there any update on this?

**Comment by xiaofan-luan** [comment]
> Hi, we are facing the same issue. Is there any update on this?

How much upsert you are using? if you did huge amount a delete this may takes querynode memory until compaction done.
We need to more clues on your issue but this is an pretty old issue and won't be related if you use 2.4.13
