### ISSUE TITLE
如果指定id插入时, id一样有没有可以自动覆盖的方法

### ISSUE THREAD

**Issue by qiuchsh** [milvus-io/milvus#2408]
**What is your question?**

**Comment by tinkerlin** [comment]
Milvus do not have mechanisms for covering duplicate id.
@qiuchsh

**Comment by qiuchsh** [comment]
> Milvus do not have mechanisms for covering duplicate id.
> @qiuchsh

有计划支持这个功能吗

@tinkerlin

**Comment by tinkerlin** [comment]
I already put this requirement into the backlog list. It will be dicussed in the plan meeting.

**Comment by shengjun1985** [comment]
This is a duplicate issue with #2545.
Please allow me the close it.
Thank you for your concern and support for our project.
