### ISSUE TITLE
[Bug]: metric type JACCARD is allowed for float vector FLAT index

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#24080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:113f9a0
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Create FLAT index on float vector field with JACCARD metric type will not return error

### Expected Behavior

JACCARD metric type shall only be allowed on binary vector

**Comment by cydrain** [comment]
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=3, reason=worker(3) query failed: [UnexpectedError] Assert "is_float_data_type == is_float_metric_type" at /home/caiyd/vec/milvus/internal/core/src/query/SearchBruteForce.cpp:34
 => [BruteForceSearch] Data type and metric type miss-match)>

**Comment by cydrain** [comment]
@congqixia I need your script to re-produce this issue

**Comment by cydrain** [comment]
similar check has been made before searching
https://github.com/milvus-io/milvus/pull/20838

**Comment by cydrain** [comment]
For real index, we also have checked the param validation before creating index
```
func (c *binaryVectorBaseChecker) CheckTrain(params map[string]string) error
func (c *floatVectorBaseChecker) CheckTrain(params map[string]string) error 
```

we will see error like this:
```
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=metric type not found or not supported, supported: [L2 IP COSINE])>
```

**Comment by cydrain** [comment]
As a conclusion, we have already checked the param validation:
1. before creating real index
2. before searching

For this case, it's not a e2e test, and it's not a real index ("FLAT" will not create real index), so it bypass all above checks.
Can we just let it be ?

**Comment by yanliang567** [comment]
@cydrain I understand the code implements, but I still suggest not skip the checking for FLAT index, which benefits:
1.  avoid users confusion
2. save users time
3. milvus behaves the same for all the index types
