### ISSUE TITLE
[Enhancement]: Adjust the default size of segments and the size for flushing segments

### ISSUE THREAD

**Issue by jiaoew1991** [milvus-io/milvus#24098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

The current default segment size is 512M, but this value needs to be reconsidered. In scenarios where the data volume exceeds 100 million, it has been tested that a segment size of 2G or 4G is more appropriate. 
However, for small data scenarios, a segment size of 512M requires compaction to achieve and is not conducive to rapid application verification. 
Therefore, the default segment size can be set to 2G.

At the same time we can consider to provide a "seal size" parameter to replace the current "dataCoord.segment.sealProportion" parameter. The sealProportion is a proportional value that will be affected by the segment size. Many users forget to adjust this parameter after modifying the segment size, which leads to delayed sealing of segments and affects stability. Therefore, it is recommended to use a new numerical parameter instead of proportion for more intuitive adjustment.

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What would you like to be added?
> The current default segment size is 512M, but this value needs to be reconsidered. In scenarios where the data volume exceeds 100 million, it has been tested that a segment size of 2G or 4G is more appropriate. However, for small data scenarios, a segment size of 512M requires compaction to achieve and is not conducive to rapid application verification. Therefore, the default segment size can be set to 2G.
> 
> At the same time we can consider to provide a "seal size" parameter to replace the current "dataCoord.segment.sealProportion" parameter. The sealProportion is a proportional value that will be affected by the segment size. Many users forget to adjust this parameter after modifying the segment size, which leads to delayed sealing of segments and affects stability. Therefore, it is recommended to use a new numerical parameter instead of proportion for more intuitive adjustment.
> 
> ### Why is this needed?
> _No response_
> 
> ### Anything else?
> _No response_

It might be dynamically tuned with machine memory limit?

**Comment by jiaoew1991** [comment]
> > ### Is there an existing issue for this?
> > 
> > * [x]   I have searched the existing issues
> > 
> > ### What would you like to be added?
> > The current default segment size is 512M, but this value needs to be reconsidered. In scenarios where the data volume exceeds 100 million, it has been tested that a segment size of 2G or 4G is more appropriate. However, for small data scenarios, a segment size of 512M requires compaction to achieve and is not conducive to rapid application verification. Therefore, the default segment size can be set to 2G.
> > At the same time we can consider to provide a "seal size" parameter to replace the current "dataCoord.segment.sealProportion" parameter. The sealProportion is a proportional value that will be affected by the segment size. Many users forget to adjust this parameter after modifying the segment size, which leads to delayed sealing of segments and affects stability. Therefore, it is recommended to use a new numerical parameter instead of proportion for more intuitive adjustment.
> > ### Why is this needed?
> > _No response_
> > ### Anything else?
> > _No response_
> 
> It might be dynamically tuned with machine memory limit?

I don't think it's feasible in the short term. Firstly, the memory size of nodes may vary, and secondly, excessive automation is not very controllable for users. We can provide some best practices as suggestions to users based on data scale and machine size.

**Comment by jiaoew1991** [comment]
keep it

**Comment by shunjiezhao** [comment]
Hello, I see sealPolicybeing applied to the growing Segment, how do I get the size of the current growing segment?
I use `collection perRecordSize * segment.currRows`  to calculate, is that feasible?

**Comment by jiaoew1991** [comment]
Hi @shunjiezhao do you want to contribute to this issue 😄？

**Comment by jiaoew1991** [comment]
Let me answer your question
> Does this only need to change this parameter in the configuration file?

Not only to modify this default value, but also to modify the default value in component_params


> I see that DataNode periodically reports the row count of segments to datacrood so can I use this number * the estimated size of one row to calculate the size of the growing segment?

There are examples of size estimation in the existing code. Each SegmentInfo has a MaxRowNum field, which can be calculated based on this field. This field is calculated by the estimateMaxNumOfRows method of SegmentManager.
