### ISSUE TITLE
[Bug]: Search occasionally times out

### ISSUE THREAD

**Issue by yesletgo** [milvus-io/milvus#24114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.8
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.5
- OS(Ubuntu or CentOS): centos
- CPU/Memory:  84cores/600G
- GPU: 
- Others:
```

### Current Behavior

Search occasionally times out

### Expected Behavior

It should be normal

### Milvus Log

https://video-tag-lib-1251808348.cos.ap-beijing.myqcloud.com/milvus_log/k8s_logs_24h.tar.gz

![image](https://github.com/milvus-io/milvus/assets/21998052/aa987abe-72cf-48d4-91b4-5eaa6e06ddc5)
![image](https://github.com/milvus-io/milvus/assets/21998052/08f51f9e-78d7-49d2-883d-2ccf4ffd4519)
![image](https://github.com/milvus-io/milvus/assets/21998052/69abd686-1ae7-456b-8553-284c085c635c)
![image](https://github.com/milvus-io/milvus/assets/21998052/09c232ef-117c-4f1d-9ab9-d283735f2bdd)

**Comment by yanliang567** [comment]
it seems that the tt lag was huge at that moment.
/assign @jiaoew1991 
/unassign

**Comment by jiaoew1991** [comment]
It seems not only TT is slow, but also the Kafka connection is unstable 🤔
