### ISSUE TITLE
[Bug]: [PartitionKey] partition.flush() should be disabled if partition key is on

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#24165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20230515-8b8f9f1e
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-2.2.9.dev8
```

### Current Behavior

partition.flush is not disabled when partition key is on

### Expected Behavior

disable partition.flush

**Comment by yanliang567** [comment]
the same situation to 
1. utility.loading_progress(collection_name=collection_w.name, partition_names=[partitions[0].name])
2. utility.wait_for_loading_complete(collection_name=collection_w.name, partition_names=[partitions[0].name])
3. collection.delete(expr=f'{pk_field.name} in {pks}', partition_names=[p1.name])
4.

**Comment by xige-16** [comment]
milvus only suport flush on collection for now

**Comment by yanliang567** [comment]
close as by design
