### ISSUE TITLE
[Bug]: No error is produced when creating invalid index (FLAT+JACCARD)

### ISSUE THREAD

**Issue by chyezh** [milvus-io/milvus#24178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20230517-1589d8ad
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):   rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):  milvus-sdk-go:v2.2.x
- OS(Ubuntu or CentOS): Mac
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

An error is expected when creating index on FLAT+JACCARD but got nil.
![image](https://github.com/milvus-io/milvus/assets/20332315/7d1603c0-bce9-4dfe-8646-3f2633da66ba)

### Expected Behavior

An error should be produced.

### Steps To Reproduce

```markdown
cd milvus-sdk-go/test/testcases && go test * -run TestCreateIndexInvalidParams
```

**Comment by congqixia** [comment]
Same with #24080
Could you please link PR to this issue as well? @longjiquan

**Comment by longjiquan** [comment]
> Same with #24080 Could you please link PR to this issue as well? @longjiquan

sure.

**Comment by longjiquan** [comment]
Please recheck this, thx a lot. @chyezh

**Comment by chyezh** [comment]
passed in latest image.
