### ISSUE TITLE
[Bug]: [benchmark] diskann index insert 100m data, build index too slow, more than 17h 

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#24177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230516-c31af5ed
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Disk Type ：NVME
```

### Current Behavior

argo task : fouramf-concurrent-mxbzf , id :2 
case: test_concurrent_locust_100m_diskann_ddl_dql_filter_cluster

server
```
fouram-58-2583-etcd-0                                             1/1     Running            0                  18h     10.104.22.133   4am-node26   <none>           <none>
fouram-58-2583-etcd-1                                             1/1     Running            0                  18h     10.104.9.77     4am-node14   <none>           <none>
fouram-58-2583-etcd-2                                             1/1     Running            0                  18h     10.104.6.44     4am-node13   <none>           <none>
fouram-58-2583-milvus-datacoord-7866cdf96-sr58w                   1/1     Running            1 (18h ago)        18h     10.104.22.127   4am-node26   <none>           <none>
fouram-58-2583-milvus-datanode-5464995cff-bdg8w                   1/1     Running            1 (18h ago)        18h     10.104.18.204   4am-node25   <none>           <none>
fouram-58-2583-milvus-indexcoord-64b58675c8-vst2q                 1/1     Running            0                  18h     10.104.22.124   4am-node26   <none>           <none>
fouram-58-2583-milvus-indexnode-7dc8c65687-5kl6n                  1/1     Running            0                  18h     10.104.22.128   4am-node26   <none>           <none>
fouram-58-2583-milvus-proxy-5f78798c84-8789h                      1/1     Running            1 (18h ago)        18h     10.104.22.123   4am-node26   <none>           <none>
fouram-58-2583-milvus-querycoord-597446f58c-hczr6                 1/1     Running            1 (18h ago)        18h     10.104.22.126   4am-node26   <none>           <none>
fouram-58-2583-milvus-querynode-77c4f4c99c-r4dbm                  1/1     Running            0                  18h     10.104.24.102   4am-node29   <none>           <none>
fouram-58-2583-milvus-rootcoord-846df4bdbf-lhvfz                  1/1     Running            1 (18h ago)        18h     10.104.22.125   4am-node26   <none>           <none>
fouram-58-2583-minio-0                                            1/1     Running            0                  18h     10.104.22.134   4am-node26   <none>           <none>
fouram-58-2583-minio-1                                            1/1     Running            0                  18h     10.104.9.75     4am-node14   <none>           <none>
fouram-58-2583-minio-2                                            1/1     Running            0                  18h     10.104.6.41     4am-node13   <none>           <none>
fouram-58-2583-minio-3                                            1/1     Running            0                  18h     10.104.5.87     4am-node12   <none>           <none>
fouram-58-2583-pulsar-bookie-0                                    1/1     Running            0                  18h     10.104.22.135   4am-node26   <none>           <none>
fouram-58-2583-pulsar-bookie-1                                    1/1     Running            0                  18h     10.104.9.80     4am-node14   <none>           <none>
fouram-58-2583-pulsar-bookie-2                                    1/1     Running            0                  18h     10.104.6.45     4am-node13   <none>           <none>
fouram-58-2583-pulsar-bookie-init-wwbcq                           0/1     Completed          0                  18h     10.104.9.68     4am-node14   <none>           <none>
fouram-58-2583-pulsar-broker-0                                    1/1     Running            0                  18h     10.104.9.69     4am-node14   <none>           <none>
fouram-58-2583-pulsar-proxy-0                                     1/1     Running            0                  18h     10.104.22.122   4am-node26   <none>           <none>
fouram-58-2583-pulsar-pulsar-init-6x7s7                           0/1     Completed          0                  18h     10.104.9.67     4am-node14   <none>           <none>
fouram-58-2583-pulsar-recovery-0                                  1/1     Running            0                  18h     10.104.9.66     4am-node14   <none>           <none>
fouram-58-2583-pulsar-zookeeper-0                                 1/1     Running            0                  18h     10.104.9.79     4am-node14   <none>           <none>
fouram-58-2583-pulsar-zookeeper-1                                 1/1     Running            0                  18h     10.104.6.61     4am-node13   <none>           <none>
fouram-58-2583-pulsar-zookeeper-2                                 1/1     Running            0                  18h     10.104.18.214   4am-node25   <none>           <none>
```

client log    :
```
 [2023-05-16 13:25:04,885 -  INFO - fouram]: [Time] Collection.insert run in 1.845s (api_request.py:41)
[2023-05-16 13:25:04,887 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_pp9XXZ4l): 99900000 (base.py:457)
[2023-05-16 13:25:04,960 -  INFO - fouram]: [Base] Total time of insert: 3515.5631s, average number of vector bars inserted per second: 28444.9453, average time to insert 50000 vectors per time: 1.7578s (base.py:374)
[2023-05-16 13:25:04,960 -  INFO - fouram]: [Base] Start flush collection fouram_pp9XXZ4l (base.py:272)
[2023-05-16 13:25:07,498 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_pp9XXZ4l): 100000000 (base.py:457)
[2023-05-16 13:25:07,502 -  INFO - fouram]: [Base] Params of index: {'index_type': 'DISKANN', 'metric_type': 'L2', 'params': {}} (base.py:435)
[2023-05-16 13:25:07,502 -  INFO - fouram]: [Base] Start build index of DISKANN for collection fouram_pp9XXZ4l, params:{'index_type': 'DISKANN', 'metric_type': 'L2', 'params': {}} (base.py:422)
[2023-05-17 06:56:12,103 -  INFO - fouram]: [Time] Index run in 63064.5993s (api_request.py:41)
[2023-05-17 06:56:12,104 -  INFO - fouram]: [CommonCases] RT of build index DISKANN: 63064.5993s (common_cases.py:90)
[2023-05-17 06:56:12,109 -  INFO - fouram]: [Base] Params of index: {'index_type': 'DISKANN', 'metric_type': 'L2', 'params': {}} (base.py:435)
[2023-05-17 06:56:12,109 -  INFO - fouram]: [CommonCases] Prepare index DISKANN done. (common_cases.py:93)
```
 
**build index : 63064.5993s => 17.5h**

v2.2.7:
  build index DISKANN: 16807.7364s => 4.6h

### Steps To Reproduce

```markdown
1. create a collection or use an existing collection
        2. build index on vector column
        3. insert a certain number of vectors
        4. flush collection
        5. build index on vector column with the same parameters
        6. build index on on scalars column or not
        7. count the total number of rows
        8. load collection
        9. perform concurrent operations
        10. clean all collections or not
```

### Anything else?

indexnode resources:
'indexNode': {'resources': {'limits': {'cpu': '8', 'memory': '32Gi', 'ephemeral-storage': '100Gi'}, 'requests': {'cpu': '8', 'memory': '32Gi'}},

**Comment by smellthemoon** [comment]
eport errors during building index, but not log out the exact error.
<img width="1069" alt="1" src="https://github.com/milvus-io/milvus/assets/64083300/f70e1d3c-616b-4ec7-9e46-c6c418c164ff">
can you retest it after this pr(#24260) merged, which can help us see what happened clearly. @elstic

**Comment by elstic** [comment]
> eport errors during building index, but not log out the exact error. <img alt="1" width="1069" src="https://user-images.githubusercontent.com/64083300/239466302-f70e1d3c-616b-4ec7-9e46-c6c418c164ff.png"> can you retest it after this pr(#24260) merged, which can help us see what happened clearly. @elstic

Yes, please let me know after the merger.
But the above error, which is only reported by milvus to collect metircs, may only cause abnormal monitoring somewhere here, but not necessarily related to the build index timeout.
I have observed that indexnode memory is not smooth and such warning appears at the point of memory drop, not sure if it is related, you can refer to it. Of course your judgment prevails, I just observed the warning.

![image](https://github.com/milvus-io/milvus/assets/48523564/22b38e67-16e8-4913-a62d-4fdd51956434)

![image](https://github.com/milvus-io/milvus/assets/48523564/e6f13971-5547-454b-b178-353e2653a2d1)

**Comment by smellthemoon** [comment]
The first picture is the case of building index on 2.2.7, the front is the time, and the back is the point to load
<img width="366" alt="1" src="https://github.com/milvus-io/milvus/assets/64083300/45a691ca-52fe-49f8-90fc-1a7f89cdaca5">
The second picture is the situation above the master
<img width="468" alt="2" src="https://github.com/milvus-io/milvus/assets/64083300/34599b7b-7ce6-42cd-8837-d16c9f6e711e">
We can see that in the case of the same size, the branch on the master takes much more time in knowhere. according to @elstic, both versions are release level, @liliu-z @cqy123456 any other ideas for that? I'm trying to rebuild the image  to avoid the factor of the environment.

**Comment by elstic** [comment]
I didn't say that those images are release level, I just said they need to be debugged by you, but generally they are not debug level.
@smellthemoon

**Comment by smellthemoon** [comment]
> 

ok I will double check it.

**Comment by smellthemoon** [comment]
> I didn't say that those images are release level, I just said they need to be verified by you, but generally they are not debug level.
> @smellthemoon

ok，I will double check it

**Comment by xiaofan-luan** [comment]
There is nothing to do with knowhere.
Check indexnode see if there is any OOM

**Comment by elstic** [comment]
update :
image: master-20230530-b09e7aea
build index DISKANN: 34915.2526s

**Comment by smellthemoon** [comment]
> The first picture is the case of building index on 2.2.7, the front is the time, and the back is the point to load
> <img alt="1" width="366" src="https://user-images.githubusercontent.com/64083300/240562783-45a691ca-52fe-49f8-90fc-1a7f89cdaca5.png">
> The second picture is the situation above the master
> <img alt="2" width="468" src="https://user-images.githubusercontent.com/64083300/240562904-34599b7b-7ce6-42cd-8837-d16c9f6e711e.png">
> We can see that in the case of the same size, the branch on the master takes much more time in knowhere. according to @elstic, both versions are release level, @liliu-z @cqy123456 any other ideas for that? I'm trying to rebuild the image to avoid the factor of the environment.

update：rebuild the image to test, but still the same.

**Comment by xiaofan-luan** [comment]
> The first picture is the case of building index on 2.2.7, the front is the time, and the back is the point to load <img alt="1" width="366" src="https://user-images.githubusercontent.com/64083300/240562783-45a691ca-52fe-49f8-90fc-1a7f89cdaca5.png"> The second picture is the situation above the master <img alt="2" width="468" src="https://user-images.githubusercontent.com/64083300/240562904-34599b7b-7ce6-42cd-8837-d16c9f6e711e.png"> We can see that in the case of the same size, the branch on the master takes much more time in knowhere. according to @elstic, both versions are release level, @liliu-z @cqy123456 any other ideas for that? I'm trying to rebuild the image to avoid the factor of the environment.

Did you ensure the memory is enough?

**Comment by binbinlv** [comment]
any updates?
@jiaoew1991

**Comment by smellthemoon** [comment]
the same commit: master-20230502-87d790f0 (v2.2.7) master build index time has already been 18h.

**Comment by elstic** [comment]
This issue still exists, verified version: master-20230714-fc9a6dc2

Build index after inserting 100 million data 78670.0845s

**Comment by xiaofan-luan** [comment]
> the same commit: master-20230502-87d790f0 (v2.2.8) master build index time has already been 18h.

Can you add monitoring metrics for both index building and original data load.

To solve the problem, you should add more performance metrics on diffenrent stages.

**Comment by cqy123456** [comment]
After setting knowhere thread pool size by pod resource,  build time between 2.2.0 and master is close in knowhere.
2.2.0:
![2a988db4-7907-49c1-9f8f-fb1a4f2f8bbe](https://github.com/milvus-io/milvus/assets/39671710/8cb6bfa3-1a09-49f8-ba9d-b8935e6f0978)
master:
![cb679363-3260-4b90-b15d-b5eeb28a3dc0](https://github.com/milvus-io/milvus/assets/39671710/d111b125-df2a-4770-9713-0a9d54591de1)

**Comment by smellthemoon** [comment]
In the latest test, although the time to build an index on each segment is less (about the same size as 2.2.0), but the number of times to build an index has increased, and the size of the segment has also become smaller, resulting in a build time that should still be about the same as before.
<img width="1212" alt="1" src="https://github.com/milvus-io/milvus/assets/64083300/27bb9c70-70c4-401b-b00c-de332180d250">
In 2.2.0, ‘compactableProportion’ is 0.85 and in master, ‘compactableProportion’ is 0.5. Can test it again according to the parameters of 2.2.0. @elstic

**Comment by elstic** [comment]
in recent tests, build index time consuming back to normal
Verify image: master-20230802-830f0678
build index: 18627.3541s
