### ISSUE TITLE
[Enhancement]: Use generic to simplify XXclient code 

### ISSUE THREAD

**Issue by jiaoew1991** [milvus-io/milvus#24196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

There is a large amount of duplicate code in XXclient as shown below, which can be simplified using methods similar to those in https://github.com/milvus-io/milvus/pull/24195.
```
// GetComponentStates gets the component states of QueryCoord.
func (c *Client) GetComponentStates(ctx context.Context) (*milvuspb.ComponentStates, error) {
	ret, err := c.grpcClient.ReCall(ctx, func(client querypb.QueryCoordClient) (any, error) {
		if !funcutil.CheckCtxValid(ctx) {
			return nil, ctx.Err()
		}
		return client.GetComponentStates(ctx, &milvuspb.GetComponentStatesRequest{})
	})
	if err != nil || ret == nil {
		return nil, err
	}
	return ret.(*milvuspb.ComponentStates), err
}
```

**Comment by preetham** [comment]
@jiaoew1991 Can I pick this up?

**Comment by preetham** [comment]
@jiaoew1991 I have raised a PR: https://github.com/milvus-io/milvus/pull/24311 for the same.

I have updated only datacoord client as requested in the issue, I'll make the changes to other clients as well if this is as expected. Also might split the changes into multiple PRs as the code changes might be too many to review.

**Comment by jiaoew1991** [comment]
@preetham sure，thank you for your contribution 

/assign @preetham

**Comment by preetham** [comment]
@jiaoew1991 Part 2 of the changes: https://github.com/milvus-io/milvus/pull/24344

**Comment by jiaoew1991** [comment]
hi @preetham datanode/client/client.go not yet refactored, do you still want to contribute code and complete this issue? 😄

**Comment by preetham** [comment]
Hey @jiaoew1991 , apologies for the missed client package. Here you go: https://github.com/milvus-io/milvus/pull/24494

**Comment by jiaoew1991** [comment]
@preetham Well done, we can close this issue now. 👏🏻
