### ISSUE TITLE
[Bug]: fail to delete row

### ISSUE THREAD

**Issue by shieldlin** [milvus-io/milvus#24201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.5
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): java
- OS(Ubuntu or CentOS): Centos
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

We try to delete 400k row in order to update them. but fond 2k rows fail to update( fail to delete)

### Milvus Log

[log.tar.gz](https://github.com/milvus-io/milvus/files/11498036/log.tar.gz)

**Comment by yanliang567** [comment]
@shieldlin one quick question: do you mean you can still query the entities even after you delete them? or you got an exception when trying to deleting those 2k entities? if the former, could you please check if there are any duplicate pk in the milvus? if the latter, could you please attach the error msg?

/assign @shieldlin

**Comment by shieldlin** [comment]
> 

yes. But how? attu only shows the old one.

**Comment by sunby** [comment]
@yanliang567 We have found several related issues and fix them.
