### ISSUE TITLE
[Bug]: [PartitionKey] It is slower to insert the same batch into a partition key enabled collection 

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#24218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20230517-d4f7ebd1
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-2.2.9.dev11
```

### Current Behavior

I have 2 collections: one is partition key enabled, the other is not
almost every batch insert is slower if the collection is partition key enabled. sometimes it is 2-4 times slower
nb=50000, partition key values=1000, num_partitions=64：
![image](https://github.com/milvus-io/milvus/assets/82361606/5e31cc9b-9b73-4f84-87b6-e837c17268c6)

### Expected Behavior

insert latency should be almost the same.

### Steps To Reproduce

```markdown
1. create 2 collections, one is partition key on, the other is off
2. insert the same data batch to 2 collections
```

### Milvus Log

around UTC time 2023-05-18T05:14:57
pod names:
```
yanliang-parkey-etcd-0                                            1/1     Running            0                  5h6m
yanliang-parkey-milvus-standalone-5bf7bddbdb-hkc7x                1/1     Running            0                  5h5m
yanliang-parkey-minio-777dfb88d8-m5sjc                            1/1     Running            0                  5h6m
```

**Comment by xige-16** [comment]
In partition key mode, the proxy will apply for more segmentids concurrently. But because datacoord.SegmentManager.AllocSegment holds a large lock, the average delay of allocateSegmentID is high when the concurrency is high

**Comment by yanliang567** [comment]
if nb=10000, partition key values =10000, num_partitions=4096, it became much slower:
```
05/22/2023 03:55:00 AM - INFO - hnsw_parkey insert 75 costs 5.296
05/22/2023 03:55:06 AM - INFO - hnsw_parkey insert 76 costs 5.9
05/22/2023 03:55:11 AM - INFO - hnsw_parkey insert 77 costs 5.207
05/22/2023 03:55:17 AM - INFO - hnsw_parkey insert 78 costs 4.969
```

**Comment by yanliang567** [comment]
insert latency with partition key enabled on milvus 2.2.12 is almost same with partition key disabled.
