### ISSUE TITLE
[Enhancement]: Add linter to finds structures with uninitialized fields

### ISSUE THREAD

**Issue by jiaoew1991** [milvus-io/milvus#24215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Many issues arise from forgetting to initialize newly added fields in a struct. You can try using a linter like https://github.com/GaijinEntertainment/go-exhaustruct to check for this problem.

**Comment by jiaoew1991** [comment]
keep it

**Comment by jiaoew1991** [comment]
@smellthemoon Take some time to deal with this issue.

**Comment by smellthemoon** [comment]
golangci-lint version is 1.27.0 in master and 2.2.0. In that version, go-exhaustruct(V2)can not support files exclude rules. But in the test code, a lots of cases can't fill in all the struct. The latest golangci-lint code has supported go-exhaustruct(V3), but not released yet. After the next release(1.53.4), will add the linter to finds structures with uninitiated
field and test the compatibility of the previous linter.
