### ISSUE TITLE
[Bug]:  FlushAll doesn't work while enable database function

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#24220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![img_v2_adc3d1a5-4f28-4652-8a97-40ab8b131a7g](https://github.com/milvus-io/milvus/assets/4024711/7a21abae-1fed-4162-a7d3-a7e528b787e8)

**Comment by ThreadDao** [comment]
Fixed `2.2.0-20230524-5a773983`
