### ISSUE TITLE
重建索引导致旧数据搜索不到

### ISSUE THREAD

**Issue by tianyuzhu** [milvus-io/milvus#2422]
**Describe the bug**
重建索引类型为IVFSQ8H的索引，旧数据不能搜索到

操作步骤：
1、新建索引类型为IVFSQ8H的collection
2、插入一部分数据，我的插入了30万条
3、通过以图搜图能搜索到正确的结果
4、通过java sdk执行createIndex，类型还是IVFSQ8H，完成后再次执行第3步，不能搜索到数据

- 2080ti，120G内存，CPU E5-2678 v3
- Method of installation (Docker)
- Milvus version (v0.9.0)
- 配置文件中，gpu_resource_config:
   enable: true
   cache_capacity: 2

**Comment by tianyuzhu** [comment]
如果我在createIndex时把索引类型从IVFSQ8H指定为IVFSQ8，执行完成后再执行第3步的操作，是能搜索到数据的

**Comment by tianyuzhu** [comment]
//创建索引
            JSONObject indexParamsJson = new JSONObject();
            indexParamsJson.put("nlist", 16384);
            IndexType indexType = IndexType.IVF_SQ8_H;       
            Index index = new Index.Builder(collectionName, indexType)
                    .withParamsInJson(indexParamsJson.toString())
                    .build();
            Response createIndexResponse = client.createIndex(index);

           //搜索
            JSONObject searchParamsJson = new JSONObject();
            searchParamsJson.put("nprobe", 16384);
            SearchParam.Builder builder = new SearchParam.Builder(tableName)
                    .withFloatVectors(features)
                    .withTopK(topK)
                    .withParamsInJson(searchParamsJson.toString());
            SearchResponse searchResponse = client.search(builder.build());

**Comment by yhmo** [comment]
The "Illegal search parameter" error occurs before search begin, in ExecutionEngineImpl.cpp line1152, thrown by method IVFConfAdapter::CheckSearch().

IVFConfAdapter::CheckSearch() check two parameters: nprobe and topk
If search by GPU, the nprobe valid range is : [1, 1024]
If search by CPU, the nprobe valid range is : [1, 999999]

The input nprobe:16384 exceeds the max nprobe in GPU mode, so you get this exception.

**Comment by op-hunter** [comment]
https://github.com/facebookresearch/faiss/wiki/Faiss-on-the-GPU
reference to the document above, "k and nprobe must be <= 1024 for all indices.".

**Comment by tianyuzhu** [comment]
确实是这样，我验证过了，感谢！
