### ISSUE TITLE
[Bug]: Some search failed with reason context canceled err %!w exception when multiple users search concurrently

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#24236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20230517-d4f7ebd1
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq  
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.2.9 dev3
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. deploy standalone with config (you can clone my qtp task 1684324896261)
```
{
extraConfigFiles:{
user.yaml:"queryNode:
scheduler:
scheduleReadPolicy:
name: "user-task-polling"
common:
security:
authorizationEnabled: "true"
"
}
standalone:{
resources:{
requests:{
memory:"8Gi"
cpu:"2"
}
limits:{
memory:"16Gi"
cpu:"4"
}}}}
```
2. Start 5 clients to do the same same in parallel:
  2.1. root user connect and create a user, then bind the user to the admin role
  2.2. connect with the bellow user
 2.3. create a collection -> create hnsw index with params {'M': 8, 'efConstruction': 200} -> insert 1m-768d with ni_per 1000 -> flush collection -> create index again -> load collection
2.4. only 2 user load collection successfully due to insufficient memory
2.5. Concurrently search the 3 successfully loaded collections and one collection gets the following exception:
```
[2023-05-18 09:44:00,993 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
attempt #1:code: UnexpectedError, error: fail to Search, QueryNode ID=1, reason=Search 1 failed, reason context canceled err %!w(<nil>)
attempt #2:context canceled
)>, <Time:{'RPC start': '2023-05-18 09:44:00.449728', 'RPC error': '2023-05-18 09:44:00.993866'}> (decorators.py:108)
[2023-05-18 09:44:00,997 - ERROR - fouram]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
attempt #1:code: UnexpectedError, error: fail to Search, QueryNode ID=1, reason=Search 1 failed, reason context canceled err %!w(<nil>)
attempt #2:context canceled
)> (api_request.py:49)
```
 

### Steps To Reproduce

```markdown
workflow name in fouram cluster:
- fouramf-concurrent-rbac-5 (Prepared data for 5 collections but failed to load two collections)
- fouramf-concurrent-gbgh-fnlrq (continue to concurrent search 3 collections)

client params (cm zong-user-task-schedule):

{'dataset_params': {'metric_type': 'L2',
                                                    'dim': 768,
                                                    'dataset_name': 'gist',
                                                    'dataset_size': 1000000,
                                                    'ni_per': 1000},
                                 'collection_params': {'other_fields': [],
                                                       'shards_num': 2,
                                                       'collection_name': 'fouram_tEVXdLpu'},
                                 'load_params': {},
                                 'query_params': {},
                                 'search_params': {},
                                 'resource_groups_params': {'reset': False},
                                 'database_user_params': {'reset_rbac': False,
                                                          'reset_db': False},
                                 'index_params': {'index_type': 'HNSW',
                                                  'index_param': {'M': 8,
                                                                  'efConstruction': 200}},
                                 'concurrent_params': {'concurrent_number': 20,
                                                       'during_time': 3600,
                                                       'interval': 30,
                                                       'spawn_rate': None},
                                 'concurrent_tasks': [{'type': 'search',
                                                       'weight': 1,
                                                       'params': {'nq': 10,
                                                                  'top_k': 100,
                                                                  'search_param': {'ef': 120},
                                                                  'random_data': True}}]}
```
```


### Milvus Log

server pods in fouram cluster and qa-milvus namespace:
```
dao-users-mnyuo-etcd-0                                            1/1     Running            0                27h     10.104.15.83    4am-node20   <none>           <none>
dao-users-mnyuo-milvus-standalone-65b57f454b-jvvdd                1/1     Running            0                27h     10.104.17.240   4am-node23   <none>           <none>
dao-users-mnyuo-minio-7d74bdc7cb-wwxlq                            1/1     Running            0                27h     10.104.17.239   4am-node23   <none>           <none>
```

### Anything else?

_No response_

**Comment by ThreadDao** [comment]
@chyezh 
I started 8 clients (8 users) to do the search and I found that only one user search was always successful, other user's search have some deadlines exceeds search requests.  

argo workflow name in 4am: `fouramf-concurrent-rbac-nq-2`
pods in 4am cluster qa-milvus ns
```
diff-nq-wgbax-etcd-0                                              1/1     Running                  0               11h     10.104.6.136    4am-node13   <none>           <none>
diff-nq-wgbax-milvus-standalone-5d99994dfc-6np6q                  1/1     Running                  0               11h     10.104.19.251   4am-node28   <none>           <none>
diff-nq-wgbax-minio-7b8d47b68f-nrx4q                              1/1     Running                  0               11h     10.104.6.135    4am-node13   <none>           <none>
```

**Comment by chyezh** [comment]
At the beginning of the task, insert flush index cost huge cpu resource, and search task can not execute within the timeout .
![image](https://github.com/milvus-io/milvus/assets/20332315/78a2246f-7312-47c4-af3c-1fc89658426d)

After all insert and index task was finished, search task was executed without timeout.
And users are sharing task queue fairly, as expected.
![image](https://github.com/milvus-io/milvus/assets/20332315/fe674de6-1c52-44f2-a477-9100571de37c)
But search task lag is still high, I will provide new reasonable test parameter.

**Comment by xiaofan-luan** [comment]
> At the beginning of the task, insert flush index cost huge cpu resource, and search task can not execute within the timeout . ![image](https://user-images.githubusercontent.com/20332315/239900139-78a2246f-7312-47c4-af3c-1fc89658426d.png)
> 
> After all insert and index task was finished, search task was executed without timeout. And users are sharing task queue fairly, as expected. ![image](https://user-images.githubusercontent.com/20332315/239898877-fe674de6-1c52-44f2-a477-9100571de37c.png) But search task lag is still high, I will provide new reasonable test parameter.

I don't expect insert cost so much CPU?

**Comment by chyezh** [comment]
@xiaofan-luan 
In this test, 8 clients perform insert, index, and load operations at the same time. The number of vectors is 1000000*128dim. The latency of the search operation decreases to a stable level after the collection loaded and index task finished.
![image](https://github.com/milvus-io/milvus/assets/20332315/527484ac-7929-4932-ae8a-54574f8d0cf8)
![image](https://github.com/milvus-io/milvus/assets/20332315/ab95443f-37b2-415b-a9c3-61b1b8cd85ad)
![image](https://github.com/milvus-io/milvus/assets/20332315/9d594dfc-534b-4d62-9d4f-212565e6a2d8)
