### ISSUE TITLE
[Bug]: indexnode panic when upgrade from 2.2.3 to 2.2.8

### ISSUE THREAD

**Issue by bingbb47** [milvus-io/milvus#24259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.8
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

look likes something wrong about aws s3
but upgrade without s3 config change, and the panic only occured on indexnode

### Milvus Log

[indexnode.log](https://github.com/milvus-io/milvus/files/11514425/indexnode.log)

**Comment by yanliang567** [comment]
but reproduced in house without aws s3

**Comment by xiaocai2333** [comment]
> but reproduced in house without aws s3

@bingbb47  indexnode is stateless, please check your own environment configuration.

@yanliang567 if you reproduced it, please upload the log.

**Comment by xiaocai2333** [comment]
Guess the cause of the panic is the same as #25129 , the wrong use of the `noexcept` keyword.

**Comment by xiaocai2333** [comment]
has been fixed.
/unassign
/assign @yanliang567

**Comment by yanliang567** [comment]
@bingbb47 could you please retry on milvus v.2.2.12?
/assign @bingbb47 
/unassign

**Comment by bingbb47** [comment]
> @bingbb47 could you please retry on milvus v.2.2.12? /assign @bingbb47 /unassign

This problem seems to have some random factors, and has not been discovered since v2.2.8 version
