### ISSUE TITLE
[Bug]: chunk manager init failed dataCoord init error

### ISSUE THREAD

**Issue by 580825** [milvus-io/milvus#24267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.8
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): null
- OS(Ubuntu or CentOS): CentOS7
- CPU/Memory: 16c/32G
- GPU: null
- Others: 
k8s version v1.26.2
helm version v3.6.1
containerd version 1.6.18
milvus chart version:  4.0.21,  APP VERSION: 2.2.8
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/12560237/d6761f5d-4317-4bcc-85ae-14221ceb24a6)

### Milvus Log

[datacoord.log](https://github.com/milvus-io/milvus/files/11515641/datacoord.log)

**Comment by xiaofan-luan** [comment]
did you check your minio is running as expected?

**Comment by yanliang567** [comment]
I think we should first figure out why minio is not running? could you please describe the minio pod? If the other dependencies (etcd, pulsar) are not running well, too, please also try to describe them for more information?

/assign @580825
