### ISSUE TITLE
[Bug]: [benchmark] low querynodes load

### ISSUE THREAD

**Issue by AlexeyIvanov8** [milvus-io/milvus#24271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.8
- Deployment mode(standalone or cluster): Cluster(Milvus operator)
- MQ type(rocksmq, pulsar or kafka): Kafka  
- SDK version(e.g. pymilvus v2.0.0rc2): milvus-sdk-java:2.2.2
- OS(Ubuntu or CentOS): 
- CPU/Memory: see below
- GPU: no
- Others: 

milvuscluster:
  image: milvusdb/milvus:v2.2.8
  components:
    dataCoord:
      replicas: 1
      resources:
        limits:
          cpu: 8
          memory: 16Gi
        requests:
          cpu: 1
          memory: 1Gi
    dataNode:
      replicas: 3
      resources:
        limits:
          cpu: 16
          memory: 64Gi
        requests:
          cpu: 1
          memory: 4Gi
    indexCoord:
      replicas: 1
      resources:
        limits:
          cpu: 8
          memory: 16Gi
        requests:
          cpu: 1
          memory: 1Gi
    indexNode:
      replicas: 4
      resources:
        limits:
          cpu: 32
          memory: 64Gi
        requests:
          cpu: 1
          memory: 4Gi
    queryCoord:
      replicas: 1
      resources:
        limits:
          cpu: 8
          memory: 16Gi
        requests:
          cpu: 1
          memory: 1Gi
    queryNode:
      replicas: 7
      resources:
        limits:
          cpu: 8
          memory: 64Gi
        requests:
          cpu: 4
          memory: 4Gi
    proxy:
      replicas: 2
      resources:
        limits:
          cpu: 10
          memory: 16Gi
        requests:
          cpu: 4
          memory: 8Gi
      serviceType: LoadBalancer
    rootCoord:
      replicas: 1
      resources:
        limits:
          cpu: 8
          memory: 8Gi
        requests:
          cpu: 1
          memory: 1Gi
  config:
    minio:
      bucketName: larva
      rootPath: ""
      useSSL: false
    proxy:
      maxTaskNum: 8192
    queryNode:
      dataSync:
        flowGraph:
          maxQueueLength: 1024 # Maximum length of task queue in flowgraph
          maxParallelism: 1024 # Maximum number of tasks executed in parallel in the flowgraph
    scheduler:
      #receiveChanSize: 10240
      #unsolvedQueueSize: 10240
      # maxReadConcurrentRatio is the concurrency ratio of read task (search task and query task).
      # Max read concurrency would be the value of `runtime.NumCPU * maxReadConcurrentRatio`.
      # It defaults to 2.0, which means max read concurrency would be the value of runtime.NumCPU * 2.
      # Max read concurrency must greater than or equal to 1, and less than or equal to runtime.NumCPU * 100.
      maxReadConcurrentRatio: 50.0 # (0, 100]
      cpuRatio: 120.0 # ratio used to estimate read task cpu usage.
    dataCoord:
      segment:
        maxSize: 512
  dependencies:
    kafka:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
        values:
          defaultReplicationFactor: 2
          replicaCount: 5
          numPartitions: 3
          resources:
            requests:
              cpu: 100m
              memory: 1G
            limits:
              cpu: 4
              memory: 8G
          persistence:
            accessMode: ReadWriteOnce
            enabled: true
            size: 30Gi
            storageClass: linstor-hdd
    etcd:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: false
        values:
          persistence:
            storageClass: linstor-hdd
            accessMode: ReadWriteOnce
            enabled: true
            size: 30Gi
          resources:
            limits:
              cpu: '4'
              memory: 16Gi
            requests:
              cpu: 200m
              memory: 1Gi
    storage:
      external: true
      endpoint: "minio-gateway.seaweedfs:80"
      secretRef: "larva-minio-secret"
      type: MinIO
```

### Current Behavior

I have collection of 118000 embeddings with dim=512, index params: HNSW:metric_type:IPM:8efConstruction:8.

1. Run load tests for search on 3 replicas: three of querynodes has about 3-4CPU load although each have limit 8CPU. Summary throughput is 150000 searches in second.
2. Run load tests for search on 7 replicas: seven of querynodes has about 3-4CPU load although each have limit 8CPU. Summary throughput is 250000 searches in second.

In both cases load is the same.

### Expected Behavior

I expect that in case one the querynodes CPU load must be greater than 3-4CPU because cluster(proxy, Kafka, etc) has sufficient throughput at least for 250000 searches in second(in case two). I try change various cluster settings from https://milvus.io/docs/v2.1.x/configure-docker.md but they had no significant effects.

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```gfm
> - Milvus version: 2.2.8
> - Deployment mode(standalone or cluster): Cluster(Milvus operator)
> - MQ type(rocksmq, pulsar or kafka): Kafka  
> - SDK version(e.g. pymilvus v2.0.0rc2): milvus-sdk-java:2.2.2
> - OS(Ubuntu or CentOS): 
> - CPU/Memory: see below
> - GPU: no
> - Others: 
> 
> milvuscluster:
>   image: milvusdb/milvus:v2.2.8
>   components:
>     dataCoord:
>       replicas: 1
>       resources:
>         limits:
>           cpu: 8
>           memory: 16Gi
>         requests:
>           cpu: 1
>           memory: 1Gi
>     dataNode:
>       replicas: 3
>       resources:
>         limits:
>           cpu: 16
>           memory: 64Gi
>         requests:
>           cpu: 1
>           memory: 4Gi
>     indexCoord:
>       replicas: 1
>       resources:
>         limits:
>           cpu: 8
>           memory: 16Gi
>         requests:
>           cpu: 1
>           memory: 1Gi
>     indexNode:
>       replicas: 4
>       resources:
>         limits:
>           cpu: 32
>           memory: 64Gi
>         requests:
>           cpu: 1
>           memory: 4Gi
>     queryCoord:
>       replicas: 1
>       resources:
>         limits:
>           cpu: 8
>           memory: 16Gi
>         requests:
>           cpu: 1
>           memory: 1Gi
>     queryNode:
>       replicas: 7
>       resources:
>         limits:
>           cpu: 8
>           memory: 64Gi
>         requests:
>           cpu: 4
>           memory: 4Gi
>     proxy:
>       replicas: 2
>       resources:
>         limits:
>           cpu: 10
>           memory: 16Gi
>         requests:
>           cpu: 4
>           memory: 8Gi
>       serviceType: LoadBalancer
>     rootCoord:
>       replicas: 1
>       resources:
>         limits:
>           cpu: 8
>           memory: 8Gi
>         requests:
>           cpu: 1
>           memory: 1Gi
>   config:
>     minio:
>       bucketName: larva
>       rootPath: ""
>       useSSL: false
>     proxy:
>       maxTaskNum: 8192
>     queryNode:
>       dataSync:
>         flowGraph:
>           maxQueueLength: 1024 # Maximum length of task queue in flowgraph
>           maxParallelism: 1024 # Maximum number of tasks executed in parallel in the flowgraph
>     scheduler:
>       #receiveChanSize: 10240
>       #unsolvedQueueSize: 10240
>       # maxReadConcurrentRatio is the concurrency ratio of read task (search task and query task).
>       # Max read concurrency would be the value of `runtime.NumCPU * maxReadConcurrentRatio`.
>       # It defaults to 2.0, which means max read concurrency would be the value of runtime.NumCPU * 2.
>       # Max read concurrency must greater than or equal to 1, and less than or equal to runtime.NumCPU * 100.
>       maxReadConcurrentRatio: 50.0 # (0, 100]
>       cpuRatio: 120.0 # ratio used to estimate read task cpu usage.
>     dataCoord:
>       segment:
>         maxSize: 512
>   dependencies:
>     kafka:
>       inCluster:
>         deletionPolicy: Delete
>         pvcDeletion: true
>         values:
>           defaultReplicationFactor: 2
>           replicaCount: 5
>           numPartitions: 3
>           resources:
>             requests:
>               cpu: 100m
>               memory: 1G
>             limits:
>               cpu: 4
>               memory: 8G
>           persistence:
>             accessMode: ReadWriteOnce
>             enabled: true
>             size: 30Gi
>             storageClass: linstor-hdd
>     etcd:
>       inCluster:
>         deletionPolicy: Delete
>         pvcDeletion: false
>         values:
>           persistence:
>             storageClass: linstor-hdd
>             accessMode: ReadWriteOnce
>             enabled: true
>             size: 30Gi
>           resources:
>             limits:
>               cpu: '4'
>               memory: 16Gi
>             requests:
>               cpu: 200m
>               memory: 1Gi
>     storage:
>       external: true
>       endpoint: "minio-gateway.seaweedfs:80"
>       secretRef: "larva-minio-secret"
>       type: MinIO
> ```
> 
> ### Current Behavior
> I have collection of 118000 embeddings with dim=512, index params: HNSW:metric_type:IPM:8efConstruction:8.
> 
> 1. Run load tests for search on 3 replicas: three of querynodes has about 3-4CPU load although each have limit 8CPU. Summary throughput is 150000 searches in second.
> 2. Run load tests for search on 7 replicas: seven of querynodes has about 3-4CPU load although each have limit 8CPU. Summary throughput is 250000 searches in second.
> 
> In both cases load is the same.
> 
> ### Expected Behavior
> I expect that in case one the querynodes CPU load must be greater than 3-4CPU because cluster(proxy, Kafka, etc) has sufficient throughput at least for 250000 searches in second(in case two). I try change various cluster settings from https://milvus.io/docs/v2.1.x/configure-docker.md but they had no significant effects.
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

Thanks for the feedback!
What is estimated QPS you are looking for? 

I thought there might be some bottle neck on 250000 QPS or more but we never tried. Could you offer pprof files see if we can find the bottle neck?

Also if increase proxy number would it help for your performance?  I'm doubting the bottlenect is at proxy side

**Comment by yanliang567** [comment]
I  think it is worth a try of updating the CPU requests to 8 in case one.  It helps to ensure that whether there are CPU competition underlying
```
queryNode:
      replicas: 7
      resources:
        limits:
          cpu: 8
          memory: 64Gi
        requests:
          cpu: 8
          memory: 4Gi
```

**Comment by yanliang567** [comment]
/assign @AlexeyIvanov8 
please let us know if any updates

**Comment by AlexeyIvanov8** [comment]
Thanks for the feedback!
Estimated QPS is 250k on collection with 200k vectors. I make additional tests and put in table below.

I tried the following with no effect:
1. Increase proxy number from 2 to 4
2. Increase cpu requests for querynodes from 4 to 8

Load tests results(I can retest with other params or config if necessary):

| Vectors in collection | Querynodes num | Replicas | QPS | one querynode CPU(max 8) |
|-----------------------|----------------|----------|-----|--------------------------|
| 118000 | 7 | 1 | 57000 | 3-4 |
| 118000 | 7 | 4 | 183000 | 3-4 |
| 118000 | 7 | 7 | 285000 | 3-4 |
| 212800 | 7 | 1 | 10000 | 6-7 |
| 212800 | 7 | 7 | 76000 | 6-7 |
| 212800 | 14 | 14 | 104000 | 6-7 |

I am confused by the following points:
1. For a collection of 100k vectors loading nodes is only 3-4 CPUs although on every node available 8 CPU.
2. For a collection of 200k vectors adding nodes from above 7 gives a non-linear performance increase (less than (num querynodes)*(QPS for one querynode)).

Pprof files in attachments zip(I'm used this instruction https://github.com/milvus-io/milvus/issues/13978#issue-1086559737 if it's incorrect I can redo):
[pprof.zip](https://github.com/milvus-io/milvus/files/11533705/pprof.zip)

**Comment by yanliang567** [comment]
@AlexeyIvanov8 thank you for the updates.  We are looking into it today.

/assign @xiaofan-luan

**Comment by xiaofan-luan** [comment]
and the for the pprof results, I think we get proxy pprof, any chance we can also get the querynode pprof?
except for current cpu flamegraph, please also offer block and mutex profile
go tool pprof http://localhost:6060/debug/pprof/block
go tool pprof http://localhost:6060/debug/pprof/mutex

**Comment by AlexeyIvanov8** [comment]
Excuse me for long answer, I change index params to `HNSW:IP:M=16:efConstructions=8` and achieve some speedup but querynode is still load only for 3-4 CPU of 8. Throughput is 134k searches in second on 3 replicas and 240к searches on 7 replicas. It mean that proxy can process at least 240k searches in second but why when replicas=3 and througnput=134k load of query node is only 3-4CPU?

> oh one querynode CPU(max 8) is the cpu usage?

3-4CPU

> and the for the pprof results, I think we get proxy pprof, any chance we can also get the querynode pprof?

Querynode pprof for 200k collection:
[querynode_pprof.zip](https://github.com/milvus-io/milvus/files/11575893/querynode_pprof.zip)

> Need investigate why 200k data takes much resources than 100k, what's the vector dimension?

512

> For more replica didn't increase search performance, you might want to increase the proxy number and have a load balancer before all proxy.

Proxy node run with replicas=4 and monitoring shows that each node give the part of load(1.4Mil, 2.0Mil, 3.26Mil, 2.12Mil).

> What is the expr you are using?
1. Search by vector and get ids(id1, ... idN)
2. Search by expr "id in [id1, ..., idN]" and get metadata

> By the way did you also track the cpu usage under different use cases?

When collection contains more rows (10Mil) and dim=512 querynodes load is 6-7CPU. When rows number=10Mil and dim=2048 querynodes load is ~8CPU

**Comment by xiaofan-luan** [comment]
I love your detailed feedback.
So basically what you are trying to do is use in to filter out valid candidates and search topk from valid candidates, I'm correct?

What is the typical list size when you do id in [......]?

**Comment by xiaofan-luan** [comment]
by the way, the block and mutex profiling is not working. but we are trying to reproduce in house

**Comment by AlexeyIvanov8** [comment]
> So basically what you are trying to do is use in to filter out valid candidates and search topk from valid candidates, I'm correct?

I'm execute two queries:
1. Search for similar ones without any additional filters(`MilvusClient.search`). The result is a list of ids with similarities. In previous versions it was possible to get only an id with similarity with `MilvusClient.search`. Perhaps in new ones this is not required, then I can re-test.
2. use a query(`MilvusClient.query`) with expr `id in [......]` to get the values of the remaining fields.

> What is the typical list size when you do id in [......]

700

**Comment by AlexeyIvanov8** [comment]
I retest the query `MilvusClient.search` with additional fields and got a big drop in performance.

A request without additional fields takes about 200ms and an additional request with `id in [...]` for getting additional fields take also 200ms.

A one request `MilvusClient.search` with additional fields takes more than 10 seconds, while loading the querynodes and proxy is about 0.

| request | one request time | throughput | querynode load | batch size |
|---------|------------------|------------|-----------------|------------|
| MilvusClient.search with additional fields | > 10000ms | 200k | <0.1 | 700 |
| MilvusClient.search + MilvusClient.query | 200ms + 200ms | 200k | 3-4 | 700 |
| MilvusClient.search with additional fields | 30ms | 10k | <0.1 | 700 |
| MilvusClient.search + MilvusClient.query | 30ms + 30ms | 10k | <0.1 | 700 |

**Comment by xiaofan-luan** [comment]
> I retest the query `MilvusClient.search` with additional fields and got a big drop in performance.
> 
> A request without additional fields takes about 200ms and an additional request with `id in [...]` for getting additional fields take also 200ms.
> 
> A one request `MilvusClient.search` with additional fields takes more than 10 seconds, while loading the querynodes and proxy is about 0.
> 
> request	one request time	throughput	querynode load	batch size
> MilvusClient.search with additional fields	> 10000ms	200k	<0.1	700
> MilvusClient.search + MilvusClient.query	200ms + 200ms	200k	3-4	700
> MilvusClient.search with additional fields	30ms	10k	<0.1	700
> MilvusClient.search + MilvusClient.query	30ms + 30ms	10k	<0.1	700

Should be improved on 2.3.0.

Mark it
