### ISSUE TITLE
[Bug]: failed to update segment max size，The data set cannot be loaded

### ISSUE THREAD

**Issue by maqiang515** [milvus-io/milvus#24278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.8
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):java
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 48/256 3台
- GPU: 
- Others:
```

### Current Behavior

The data set cannot be loaded，It's always 0%, and it automatically exits after a period of time；segment changed to 1024 to load；Data set size 150 million

### Milvus Log

[miluvs-log.tar.gz](https://github.com/milvus-io/milvus/files/11523839/miluvs-log.tar.gz)

**Comment by yanliang567** [comment]
I did not find any load info in the attached logs. Could you please reproduce the issue and collect the logs again? @maqiang515 
Also what did you do before loading the collection? I guess there were too many growing segments for milvus to load the collection. And after a while(as you changed the segment size), it is able to load. So if you could share more details about the reproduce steps and collection info, it would be helpful.

/assign @maqiang515 
/unassign

**Comment by maqiang515** [comment]
Thanks, for the same reason as #22204, I reduced the number of Querynodes, added the memory and adjusted the parameter from 0.9 to 0.95. It's fine now; But if I have limited hardware, isn't the amount of a single data set going to be enough to support the necessary hardware?
