### ISSUE TITLE
[Bug]: Press Test search api， CPU usage is not high

### ISSUE THREAD

**Issue by kaydxh** [milvus-io/milvus#24292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.8
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):  rocksmq   
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS):  CentOS
- CPU/Memory: 96core Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz Memory  256G
- GPU: 
- Others:
```

### Current Behavior

I use press tool from https://github.com/milvus-io/milvus-tools/tree/main/benchmark, and also use http press tool ab and bombardier, Increased concurrency from 80 to 6000，test search API for FLAT index, collection size is 10000, and vector is 1024 dimension FLOAT. The result are  as follow(CPU only used 2200% at peak):
./bombardier -n 30000  -c 3000 -t 10s -f ./search.json -m  POST -l  http://xx.xx.xx.xx:9091/api/v1/search

<img width="898" alt="image" src="https://github.com/milvus-io/milvus/assets/16474709/4d580334-9c97-4b8b-8fff-642a453857db">

### Expected Behavior

I expectd cpu usage arrived 9000%+ at peak.

**Comment by kaydxh** [comment]
Note:  The latency between client and server machines is 0.089ms for the above result. If latency arrives  2.6ms, the CPU usage is about 600% at peak.

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version: v2.2.8
> - Deployment mode(standalone or cluster): standalone
> - MQ type(rocksmq, pulsar or kafka):  rocksmq   
> - SDK version(e.g. pymilvus v2.0.0rc2): 
> - OS(Ubuntu or CentOS):  CentOS
> - CPU/Memory: 96core Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz Memory  256G
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> I use press tool from https://github.com/milvus-io/milvus-tools/tree/main/benchmark, and also use http press tool ab and bombardier, Increased concurrency from 80 to 6000，test search API for FLAT index, collection size is 10000, and vector is 1024 dimension FLOAT. The result are as follow(CPU only used 2200% at peak): ./bombardier -n 30000 -c 3000 -t 10s -f ./search.json -m POST -l http://xx.xx.xx.xx:9091/api/v1/search
> 
> <img alt="image" width="898" src="https://user-images.githubusercontent.com/16474709/239822904-4d580334-9c97-4b8b-8fff-642a453857db.png">
> ### Expected Behavior
> I expectd cpu usage arrived 9000%+ at peak.
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

search consumes CPU.
use hnsw might help

**Comment by kaydxh** [comment]
In my use case, customers need to use brute force search more often.

**Comment by xiaofan-luan** [comment]
> In my use case, customers need to use brute force search more often.

brute force search takes a lot of cpu, maybe 2.3 GPU is an option
