### ISSUE TITLE
milvus 0.9 performance degrade between 0426 and 0427

### ISSUE THREAD

**Issue by Bennu-Li** [milvus-io/milvus#2429]
**Describe the bug**
nlist:16384  index_file_size: 2048
count: 100000000
index: IVF_SQ8 (cpu search)
nprobe: 64

nq=100, topk=10:
   milvus0.8 search_time: 0.86S s
   milvus0.9 search_time: 2.67 s
nq=500, topk=10:
   milvus0.8 search_time: 3.73 s
   milvus0.9 search_time: 10.48 s
nq=1000, topk=10:
   milvus0.8 search_time: 6.97 s
   milvus0.9 search_time: 20.15 s

**Comment by del-zhenwu** [comment]
Are the search requests generated in concurrent execution ?

**Comment by Bennu-Li** [comment]
No

**Comment by del-zhenwu** [comment]
After comparing with all the history data. I found the same issue.
This issue occur between 4.25 and 4.27
nprobe=8, there is no gap performance between 0.8/0.9
![Screenshot_2020-06-04 gpu_sift_50m_search_flat](https://user-images.githubusercontent.com/56623710/83710279-ece23c00-a652-11ea-8ae2-81520747b505.png)

but search with nprobe=32, result changed.
![Screenshot_2020-06-04 gpu_sift_50m_search_flat(1)](https://user-images.githubusercontent.com/56623710/83710284-ef449600-a652-11ea-8690-b1abc4235f48.png)

**Comment by del-zhenwu** [comment]
there is no gap performance between 0.8/0.9 with ivf_flat.
nprobe=8
![Screenshot_2020-06-04 gpu_sift_50m_search_flat(3)](https://user-images.githubusercontent.com/56623710/83711389-a3472080-a655-11ea-84d5-eb056b4a6fa2.png)

nprobe=32
![Screenshot_2020-06-04 gpu_sift_50m_search_flat(2)](https://user-images.githubusercontent.com/56623710/83711396-a6421100-a655-11ea-972e-04ceafb44e2a.png)

**Comment by cydrain** [comment]
<div class="table-wrapper" markdown="block">

| 索引类型    | 支持 CPU 建索引    | 支持 CPU 搜索 | 支持 GPU 建索引      | 支持 GPU 搜索       | 支持浮点型向量   | 支持二值型向量 |
| ---------- | ---------------- | ------------- | ------------------ | ------------------ | -------------- | ------------ |
| `FLAT`     | ✔️                | ✔️            | ✔️ (仅支持浮点型向量) | ✔️ (仅支持浮点型向量) | ✔️             | ✔️            |
| `IVF_FLAT` | ✔️                | ✔️            | ✔️ (仅支持浮点型向量) | ✔️ (仅支持浮点型向量) | ✔️             | ✔️            |
| `IVF_SQ8`  | ✔️                | ✔️            | ✔️                  | ✔️                 | ✔️             | ❌             |
| `IVF_SQ8H` | ✔️                | ✔️            | ✔️                  | ✔️                 | ✔️             | ❌             |
| `IVF_PQ`   | ✔️                | ✔️            | ✔️ (仅支持欧氏距离)   | ✔️ (仅支持欧氏距离)  | ✔️             | ❌             |
| `RNSG`     | ✔️                | ✔️            | ❌                  | ❌                 | ✔️             | ❌             |
| `HNSW`     | ✔️                | ✔️            | ❌                  | ❌                 | ✔️             | ❌             |
| `ANNOY`    | ✔️                | ✔️            | ❌                  | ❌                 | ✔️             | ❌             |
</div>

**Comment by JinHai-CN** [comment]
So, commit 1384484b must be the root cause.

**Comment by del-zhenwu** [comment]
```
│  Nq/Top-k   │      1      │     10      │     100     │    1000     │
├─────────────┼─────────────┼─────────────┼─────────────┼─────────────┤
│           1 │        2.42 │        2.23 │        2.37 │        2.48 │
│          10 │        3.77 │        3.63 │        3.81 │        4.33 │
│         100 │        9.26 │         9.1 │        9.07 │        9.44 │
│        1000 │       52.12 │       52.03 │       52.49 │       60.19 │
```

**Comment by del-zhenwu** [comment]
after fix. sift-50m, nprobe: 32
```
19:06:36  │  Nq/Top-k   │      1      │     10      │     100     │    1000     │
19:06:36  ├─────────────┼─────────────┼─────────────┼─────────────┼─────────────┤
19:06:36  │           1 │        0.08 │        0.06 │        0.06 │        0.06 │
19:06:36  │          10 │         0.1 │        0.09 │         0.1 │        0.11 │
19:06:36  │         100 │        0.29 │        0.27 │        0.32 │        0.37 │
19:06:36  │         200 │         0.5 │        0.57 │        0.58 │        0.63 │
19:06:36  │         500 │        0.98 │        1.12 │        1.16 │        1.39 │
19:06:36  │        1000 │        1.83 │        2.16 │        1.93 │        2.46 │
```

**Comment by del-zhenwu** [comment]
fixed

**Comment by Bennu-Li** [comment]
nlist:16384 index_file_size: 2048
count: 100000000
index: IVF_SQ8 (cpu search)
nprobe: 64

image:   registry.zilliz.com/milvus/engine:PR-2496-gpu-centos7-release
nq    topk     time
![image](https://user-images.githubusercontent.com/53458891/83991349-12d34d80-a97f-11ea-94ce-94c488b9eeb1.png)

image: registry.zilliz.com/milvus/engine:PR-2499-gpu-centos7-release
nq    topk     time
![image](https://user-images.githubusercontent.com/53458891/83991459-5fb72400-a97f-11ea-8a34-37e8e4930df2.png)
