### ISSUE TITLE
[Bug]: Load Collection for a long time

### ISSUE THREAD

**Issue by czmmiao** [milvus-io/milvus#24303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

while loading the collection into the memory, the loading command hangs forever, while the background logs has shown OOM error

![5374ced3376ac458f56e35155262de4](https://github.com/milvus-io/milvus/assets/5085248/8350de9e-bf98-4f8d-9835-1ea39159a2bd)

### Expected Behavior

show oom in the command line

### Steps To Reproduce

```markdown
1. create a collection which is bigger than system memory
2. load the collection
```

### Milvus Log

![5374ced3376ac458f56e35155262de4](https://github.com/milvus-io/milvus/assets/5085248/f2de9341-5814-4312-82c4-216caeb447ed)

### Anything else?

nope

**Comment by yanliang567** [comment]
@czmmiao which version are you running? could you please retry on milvus v2.2.8? if it reproduced, please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation

/assign @czmmiao 
/unassign
