### ISSUE TITLE
[Enhancement]: milvus search expr impl %xxx%

### ISSUE THREAD

**Issue by yelusion2** [milvus-io/milvus#24305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

milvus search expr impl %xxx%

### Why is this needed?

The label field will be placed in the corresponding label group. When users select a label during a query, they would like to retrieve only the data under that specific label. They would prefer to use "like "%label%" as the filtering method.

**Comment by xiaofan-luan** [comment]
keep it
