### ISSUE TITLE
[Bug]: The write performance is unstable, and the operation of the datanode nodes is not as expected.

### ISSUE THREAD

**Issue by klboke** [milvus-io/milvus#24306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.8
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):kafka
- SDK version(e.g. pymilvus v2.0.0rc2):milvus-sdk-java.2.2.5
- OS(Ubuntu or CentOS): k8s 
- CPU/Memory: 
- GPU: 
- Others: A collection with 6 shards distributed across three datanodes.
```

### Current Behavior

The write performance is unstable, fluctuating frequently between high and low.
<img width="578" alt="image" src="https://github.com/milvus-io/milvus/assets/18591662/c281dd6f-8be0-4dbb-ac74-e05432bdc7b8">
Moreover, according to the monitoring data, only one datanode is working, while the expected configuration is that 6 shards should be evenly distributed across 3 datanodes.
<img width="1728" alt="image" src="https://github.com/milvus-io/milvus/assets/18591662/fea97f4e-a2bc-4d3a-a543-2773bbc704bb">

### Expected Behavior

The write performance is stable, and the three datanode nodes work together."

### Steps To Reproduce

```markdown
Using a Java client, create 8 threads, with each thread looping to write a batch of 100 records at a time.
```

### Milvus Log

https://github.com/klboke/milvus-log

**Comment by xiaofan-luan** [comment]
/assign @sunby 
Do we do balance for shards?

**Comment by klboke** [comment]
> Do we do balance for shards?

Could you please provide some relevant code for me to take a look? I'm not quite sure what you mean.

**Comment by klboke** [comment]
Just to add, after some point in time, the write performance doubled and became stable. It was observed that the CPU utilization of the index node remained consistently high during this period.
<img width="575" alt="image" src="https://github.com/milvus-io/milvus/assets/18591662/92442263-f1ba-46f4-b6aa-4e65bcba849a">
<img width="577" alt="image" src="https://github.com/milvus-io/milvus/assets/18591662/ae271d03-f1dc-4c0a-ab39-78de565d7735">

**Comment by xiaofan-luan** [comment]
Indexing actually consumes a lot of CPU and memories. What you can do is to expand index pod number while insert.

What's the estimated write throughput? I would recommend to use bulkinsert if you want to insert data in large batch

**Comment by klboke** [comment]
The problem has been identified. The write performance is related to the environment of the writing client.
