### ISSUE TITLE
[Bug]: Search failed with many kinds of error after chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#24318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230522-675821c7
- Deployment mode(standalone or cluster):both
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Error 1:
```
fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_1_441658408855018408v0 is not available in any replica, err=NodeOffline(nodeID=2)
```
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/4400/pipeline
log:
[artifacts-pulsar-pod-failure-4400-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/11538770/artifacts-pulsar-pod-failure-4400-server-logs.tar.gz)
[artifacts-pulsar-pod-failure-4400-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11538771/artifacts-pulsar-pod-failure-4400-pytest-logs.tar.gz)

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/4398/pipeline
log:
[artifacts-indexnode-pod-failure-4398-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/11538782/artifacts-indexnode-pod-failure-4398-server-logs.tar.gz)

[artifacts-indexnode-pod-failure-4398-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11538783/artifacts-indexnode-pod-failure-4398-pytest-logs.tar.gz)

Error 2:
```
fail to get shard leaders from QueryCoord: collection 441657905979726798 is not fully loaded
```
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/4394/pipeline
log:
[artifacts-standalone-pod-failure-4394-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/11538792/artifacts-standalone-pod-failure-4394-server-logs.tar.gz)
[artifacts-standalone-pod-failure-4394-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11538793/artifacts-standalone-pod-failure-4394-pytest-logs.tar.gz)

Error 3:
```
fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_1_441657760629529585v0 is not available in any replica, err=NodeHeartbeatOutdated(nodeID=2, lastHeartbeat=2023-05-22 21:28:37.098998478 +0000 UTC)
```
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/4392/pipeline
log:

[artifacts-etcd-pod-kill-4392-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/11538808/artifacts-etcd-pod-kill-4392-server-logs.tar.gz)
[artifacts-etcd-pod-kill-4392-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11538810/artifacts-etcd-pod-kill-4392-pytest-logs.tar.gz)

Error 4:
```
attempt #0: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_1_441657606381640590v0 is not available in any replica, err=<nil>:
```
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/4390/pipeline
log:

[artifacts-querynode-pod-kill-4390-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/11538859/artifacts-querynode-pod-kill-4390-server-logs.tar.gz)
[artifacts-querynode-pod-kill-4390-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11538858/artifacts-querynode-pod-kill-4390-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
/assign @jiaoew1991 
Please take a look!

**Comment by jiaoew1991** [comment]
/unassign 
/assign @zhuwenxing 

please verify it with #24300

**Comment by zhuwenxing** [comment]
verified with `master-20230523-227a770a`
