### ISSUE TITLE
Index search slower than raw file search for collection contains lot of partitions 

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#2431]
**Describe the bug**
Index search slower than raw file search for collection contains lot of partitions 

**Steps/Code to reproduce behavior**
Milvus version: 0.9.0
Meta backend: MySQL
Hardware: CPU i7 3.2G 12 cores  MEM 32GB
cache_capacity: 25GB
1. create a collection (dim=512,index_file_size=1024)
2. create 1000 partitions for this collection
3. insert 10000 vectors into each partition
4. search nq=1, topk=10, nprobe=16,  time cost: 3.6 seconds(hot query)
5. create index IVFLAT nlist=1000
6. search nq=1, topk=10, nprobe=16, time cost: 9.5 seconds(hot query)

Theoretically, index search should be faster than raw file search.

**Comment by yhmo** [comment]
If set the auto_flush_interval=1000, restart server, hot search again, time cost is 0.9 second. That means the background threads cost too much time in SQL.

**Comment by yhmo** [comment]
fixed by pr2438
After fix,  time cost is 0.9 second(index) and 1.3 second(raw).

**Comment by del-zhenwu** [comment]
fixed
