### ISSUE TITLE
[Bug]: flush takes more than 3 seconds to complete

### ISSUE THREAD

**Issue by hatvn** [milvus-io/milvus#24310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.2.8
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.2.0
- OS(Ubuntu or CentOS): Macos
- CPU/Memory: 16GB
- GPU: 
- Others:
```

### Current Behavior

I try to measure the execution time of flush when I insert entities, the execution time is > 3 seconds quite big

### Expected Behavior

I think the flush time should be much smaller

### Steps To Reproduce

```markdown
To reproduce just run the code:
import datetime
import numpy as np
from pymilvus import (
    connections,
    utility,
    FieldSchema, CollectionSchema, DataType,
    Collection,
)
connections.connect("default", host="localhost", port="19530")
dim = 128
fields = [
    FieldSchema(name="pk", dtype=DataType.VARCHAR, is_primary=True, auto_id=False, max_length=100),
    FieldSchema(name="random", dtype=DataType.DOUBLE),
    FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=dim)
]

schema = CollectionSchema(fields, "hello_milvus is the simplest demo to introduce the APIs")
hello_milvus = Collection("hello_milvus", schema, consistency_level="Strong")

print("Start inserting entities")
rng = np.random.default_rng(seed=19530)
num_entities = 30
entities = [
    # provide the pk field because `auto_id` is set to False
    [str(i) for i in range(num_entities)],
    rng.random(num_entities).tolist(),  # field random, only supports list
    rng.random((num_entities, dim)),    # field embeddings, supports numpy.ndarray and list
]
t1 = datetime.datetime.now()
insert_result = hello_milvus.insert(entities)
t2 = datetime.datetime.now()
hello_milvus.flush()
t3 = datetime.datetime.now()
print(f"insert time: {(t2 - t1).total_seconds()}, flush time: {(t3 - t2).total_seconds()}")
print(f"Number of entities in Milvus: {hello_milvus.num_entities}")  # check the num_entites
```

### Milvus Log

Start inserting entities
insert time: 0.101328, flush time: 3.576118
Number of entities in Milvus: 30

**Comment by hatvn** [comment]
@yanliang567 I found that, inserting 30 entities or 30k entities, the flush is still ~ 3 seconds. Seems that number of items doesn't influence, right ? 

By the way, I am still confused of when to call flush. I assume that if we insert/delete even 1 entity, I still need to call flush, right ? In the version 1.1, it states that: 
Milvus also performs an automatic flush. The automatic flush function flushes all existing collection data every a fixed interval (1 second) ([link](https://milvus.io/docs/v1.1.1/flush_python.md#:~:text=Milvus%20also%20performs%20an%20automatic,fixed%20interval%20(1%20second).)) 
Not sure if this feature is still available in: milvus 2.2 and **how can I change this fixed interval?**
If automatic flush is still available, I think **no need to call flush if no need to search inserted items, immediately?** @yanliang567  thank you !

**Comment by yanliang567** [comment]
Frequently calling flush makes more pieces of small segments, which is terrible for milvus performance.  So you don't need to call flush if no need to see them in collection.num_entities immediately.  As searching the inserted items, if does not matter to flush(). If you want to skip the new inserted items to improve the search latency, try ignore_growing as below:
```
search_params = {"metric_type": "HNSW", "params": {"ef": 64}, "ignore_growing": True}
collection.search(data=search_vectors, anns_field=vector_field_name,
                           param=search_params, limit=topk
                           )
```

**Comment by hatvn** [comment]
@yanliang567 So let me summarize things:
+ If we insert new items, no need to call flush(), these items will be still searchable. The only thing is: collection.num_entities won't reflect immediately
+ Only call flush() when the number of newly created items is greater than a threshold, such as: 1000 items to avoid pieces of small segments.
+ auto flush still works in Milvus 2.2

**Comment by yanliang567** [comment]
Yes, except the 1000 items example :)

**Comment by hatvn** [comment]
@yanliang567 so what is the suggested number of items?

**Comment by yanliang567** [comment]
I suggest you leave it to milvus auto flush, or only call once after you insert all the data into the collection
