### ISSUE TITLE
[Bug]: Docker cluster deployed 5 queryNodes, and after a day, many nodes hung up

### ISSUE THREAD

**Issue by 1041787154** [milvus-io/milvus#24319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.3
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):   pulsar  
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.2
- OS(Ubuntu or CentOS): Ubuntu 
- CPU/Memory: 48c
- GPU: 125G
- Others:
```

### Current Behavior

Docker cluster deployed 5 queryNodes, and after a day, many nodes hung up

### Expected Behavior

I hope that when deploying the Docker cluster, multiple query nodes can be used to ensure normal operation

### Milvus Log

[milvus.log](https://github.com/milvus-io/milvus/files/11538972/milvus.log)
![image](https://github.com/milvus-io/milvus/assets/15188273/901dd262-422f-449a-b4ad-af2986632e40)

**Comment by xiaofan-luan** [comment]
docker compose can not do cluster deployment.
you need to run cluster mode on K8s

**Comment by xiaofan-luan** [comment]
docker compose is for single machine, you should run standalone instead

**Comment by yanliang567** [comment]
For now it's not recommended to use docker-compose to deploy a milvus cluster.

/assign @1041787154 
could you please try on k8s for milvus cluster?

/unassign

**Comment by 1041787154** [comment]
> docker compose is for single machine, you should run standalone instead
@yanliang567 @xiaofan-luan 

But in the document, 2.3.0. beta supports Docker Compose to deploy cluster versions, is it not supported by 2.2. x?
![image](https://github.com/milvus-io/milvus/assets/15188273/bbe6d8b1-84c0-4218-84b6-f2b51b59fccf)

**Comment by xiaofan-luan** [comment]
docker compose should support only 1 querynode and 1 datanode, this is the so called standalone mode.
You can not scale horizontally

**Comment by xiaofan-luan** [comment]
to scale you have to see install milvus with cluster mode
