### ISSUE TITLE
[Bug]: After the collection is deleted, the disk space cannot be fully restored

### ISSUE THREAD

**Issue by xiao12mm** [milvus-io/milvus#24324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.8
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.3
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: Intel(R) Xeon(R) Gold 6278C CPU @ 2.60GHz
- GPU: V100
- Others:
```

### Current Behavior

When I am done inserting the data and then deleting the collection, the disk space can be completely restored
When I insert a piece of data, make an error, and then delete the collection, the hard disk space is not fully restored

### Expected Behavior

After the error, delete the collection, also can fully restore the disk space

### Steps To Reproduce

```markdown
1、Create a collection
2、create index
3、insert data
4、insert time out (50,000 per batch insert,When I used version 2.2.3, 50,000 per batch, there was no time out)
5、delete collection
6、The disk space is not fully restored.
```

**Comment by yanliang567** [comment]
@xiao12mm milvus only marks the collection as dropped when you call collection.drop(). It will wait about 24 hours (default settings) to delete the data on disk.
![image](https://github.com/milvus-io/milvus/assets/82361606/e0380958-9c5c-405f-9af0-694388513205)

if you can see the collection data on disk after 24h, please upload the milvus logs for investigation.

/assign @xiao12mm 
/unassign

**Comment by xiao12mm** [comment]
Ok, I'll wait a day to see

**Comment by yanliang567** [comment]
> @yanliang567
> 
> As you mentioned:
> 
> > Milvus only marks the collection as dropped when you call collection.drop(). It will wait about 24 hours (default settings) to delete the data on disk.
> 
> There might be a reason for this, right? Why is it designed this way? If there is a 24-hour gap, can we retrieve the deleted collection during this period?

Only If we can also rebuild the meta for the deleted collection, which is not 100%
