### ISSUE TITLE
[Bug]: Many errors about `alias` come out since pymilvus=2.4.0.dev37

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#24330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230522-675821c7
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):2.4.0.dev37
```

### Current Behavior

Many errors about `alias` come out since pymilvus=2.4.0.dev37.
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-24230/6/pipeline/110/
case: test_alias_called_by_utility_has_collection

### Expected Behavior

pass

**Comment by NicoYuan1986** [comment]
When i rollback the version to 2.4.0.dev36, the error disappeared.

**Comment by NicoYuan1986** [comment]
Same in 2.2 branch :  https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-24231/7/pipeline/110/

**Comment by XuanYang-cn** [comment]
seem fixed
/unassign
/assign @NicoYuan1986

**Comment by NicoYuan1986** [comment]
Fixed.
