### ISSUE TITLE
[Enhancement]: Enable workload based replica selection

### ISSUE THREAD

**Issue by weiliu1031** [milvus-io/milvus#24366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

![image](https://github.com/milvus-io/milvus/assets/108661493/8903bebd-9086-41f0-97ae-a64398d73b81)
1. querynode  request cost metrics, to get the work load of querynode
2. look aside balancer, enable workload based replica selection 
3. lb policy, refactor the replica selection and retry policy

### Why is this needed?

to achieve a better replica selection policy, which can route request  to the querynode with lowest workload

**Comment by xiaofan-luan** [comment]
The architecture diagram looks great

**Comment by jiaoew1991** [comment]
keep it
