### ISSUE TITLE
 Check DB wether available while invoking Connect API

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#24372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

We need to check the db parameter while establishing the connection,  yet it can’t be handled during the GRCP connecting stage,  using  Connect API is a reasonable way.

related to https://github.com/milvus-io/milvus/issues/24158

**Comment by longjiquan** [comment]
should be fixed by https://github.com/milvus-io/pymilvus/pull/1496 and https://github.com/milvus-io/pymilvus/pull/1497

**Comment by ThreadDao** [comment]
Fixed
