### ISSUE TITLE
[Bug]: "Missing dependencies during compilation of Milvus 2.2.8."

### ISSUE THREAD

**Issue by wg1026688210** [milvus-io/milvus#24378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.8
- OS(Ubuntu or CentOS): CentOS 
- CPU/Memory: 40 core /128GB
```

### Current Behavior

1. sh  build/builder.sh make install
![image](https://github.com/milvus-io/milvus/assets/14267759/539a91a7-52ec-4eb5-a179-6ef90c2e6ec7)
It fail at this step.
2.  we try docker pull milvusdb/milvus-env:amd64-ubuntu18.04-20230502-cc412bb from dockerhub
```
export OS_NAME=ubuntu18.04
​export DATE_VERSION=20230502-cc412bb
sh  build/builder.sh bash 
go env -w GOPROXY=https://goproxy.cn%2Cdirect/ && make install-centos
export MILVUS_IMAGE_REPO=xxxxx/bdp_platform/milvusdb
export MILVUS_IMAGE_TAG="branch_autohome_2.2.8_img" 
sh  build/build_image.sh
```
Successfully completed image building. But it seems to have missing dependencies.
![image](https://github.com/milvus-io/milvus/assets/14267759/b5c8164a-2c36-4562-9195-3d53b2d9ba78)

**Comment by yanliang567** [comment]
Mmm...amd64? @jiaoew1991 @liliu-z  could you please help to take a look?

/assign @jiaoew1991 @liliu-z 
/unassign

**Comment by jiaoew1991** [comment]
@wg1026688210 You can try Ubuntu 20.04, as not many people are using 18.04 anymore.

**Comment by wg1026688210** [comment]
Hi~ @jiaoew1991  thanks for your help ,  It work by using 20.04 . I have a small suggestion on building Milvus ,shall we remove the building with Ubuntu 18.04 (document,image) if Ubuntu 18.04 cannot support Milvus well.

**Comment by jiaoew1991** [comment]
> Hi~ @jiaoew1991 thanks for your help , It work by using 20.04 . I have a small suggestion on building Milvus ,shall we drop the building with Ubuntu 18.04 (document,image) if Ubuntu 18.04 cannot support Milvus well.

Good points, maybe we should remove Ubuntu18.04 in master branch. What do you think @xiaofan-luan

**Comment by xiaofan-luan** [comment]
Agreed, ubuntu 18.04 is recommeneded
