### ISSUE TITLE
[Enhancement]: The `flush_all` will flush all the collections of the milvus instead of all the collections of the using database

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#24384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

image version: `2.2.0-20230524-5a773983`

flush_all will flush all collections of the milvus instance, it means all db's collections rather than the using db's collections

**Comment by yanliang567** [comment]
I think we to clarify the scope and goal of flush_all before saying it should full all the collections or not. 
/assign @xiaofan-luan

**Comment by xiaofan-luan** [comment]
I think flush all could pass db or not.

**Comment by xiaofan-luan** [comment]
but without user specified it should flush all database

**Comment by yanliang567** [comment]
> but without user specified it should flush all database

If one of userA only granted with databaseA, I think he can only flush all the collections in databaseA, even he call flushall() without any parameters.

**Comment by xiaofan-luan** [comment]
> > but without user specified it should flush all database
> 
> If one of userA only granted with databaseA, I think he can only flush all the collections in databaseA, even he call flushall() without any parameters.

But then it's gonna to be very hard for K8s to do rolling upgrade

**Comment by yanliang567** [comment]
close for now as comments above
