### ISSUE TITLE
Could not open temperature file

### ISSUE THREAD

**Issue by linven0721** [milvus-io/milvus#2439]
**What is your question?**
我们使用的是0.8.0-gpu版本，发现docker中milvus进程会异常退出，在稳定性测试时，多并发查询下，100多万次查询以后，客户端无法连接至服务端，查看error日志，打印"Could not open temperature file"，请问这是什么原因？
测试环境：
   CPU:Intel Xeon Gold 6240 CPU @2.6Ghz
  GPU:GeForce RTX 2080Ti
  docker:18.06
 Nvidia Docker:2.0.3
硬盘：SATA

**Comment by yhmo** [comment]
@linven0721 
This issue is caused by milvus system monitor, please set enable_monitor = false in the server_config.yaml:
```
metric_config:
  enable_monitor: false
```

**Comment by yhmo** [comment]
Some users also report similar crash issue, if the enable_monitor=true, milvus will get system information in interval such as cpu temperature, disk usage, etc,  sometimes it failed to read information from /proc/cpuinfo and return an empty file handle and crash milvus. We have already made fix in 0.9.0. But if you still want to use 0.8.0, please set enable_monitor = false

**Comment by yhmo** [comment]
relate to #2264

**Comment by linven0721** [comment]
谢谢您的解答，非常感谢。
