### ISSUE TITLE
[Bug]: DB info was not shown in bulk insert state

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#24408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20230525-ef1a671d
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![4ddc3288-b90e-4cac-9fa7-7c2452569b22](https://github.com/milvus-io/milvus/assets/12268675/31ead254-0c54-4e3d-b5ae-a91aaf30d20f)

There is no db info in the bulk insert state. 

Since there can be the same collection name in different DBS, so need to tell the user this bulk insert task is for which db.

**Comment by yanliang567** [comment]
@yhmo any updates
