### ISSUE TITLE
[Bug]: Milvus cluster 2.2.8 restarted unexpectedly

### ISSUE THREAD

**Issue by yuliu-eric** [milvus-io/milvus#24407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.8
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Our milvus cluster (2.2.8) has been updated from 2.2.3 to 2.2.8 since last Friday (05/19), it's running smoothly until this morning where most of the cluster nodes have been restarted unexpectedly themselves and took about an hour to recover.

Using the export-log tool to get the logs from all the nodes but no logs saved before restart. Both logs and export errors are attached.

Milvus k8s status also attached.

### Milvus Log

[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/11562686/milvus-log.tar.gz)
[export-log-error.txt](https://github.com/milvus-io/milvus/files/11562703/export-log-error.txt)
<img width="891" alt="Screen Shot 2023-05-25 at 16 30 28" src="https://github.com/milvus-io/milvus/assets/87292135/0b1ac6e7-ab81-4954-908b-4384e9819f96">

**Comment by cndpzc** [comment]
In addition, we found one node of `etcd` was down during 11:10-12:00. Not sure if it's related.

<img width="1380" alt="image" src="https://github.com/milvus-io/milvus/assets/3941929/56c5cad9-205c-4c4d-ad02-d627b70040d6">

**Comment by jiaoew1991** [comment]
If Etcd had crashed at that time, it would have been reasonable as Milvus uses Etcd as a service discovery service. If Etcd crashes, Milvus components will not be able to provide services.

In addition, the logs posted in the issue are only after the restart and there are no logs before the restart. If Milvus is self-maintained, it is strongly recommended to use log collection services such as Loki or Logstash together to retain enough logs for analyzing error causes.

**Comment by cndpzc** [comment]
@jiaoew1991 Thanks for reply, do you have guides or practices on how to integrate Milvus logs into Loki? We installed Milvus with Helm.

For etcd, it seems only one node was down, there were still two nodes alive, in such case is Milvus not able to provide service?  Do you have some more advices on how we could improve the whole system's availability?
