### ISSUE TITLE
[Bug]: CPU usage of Querynode gets down when there are data inserting

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#24423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:  master-20230524-e206265d
- Deployment mode(standalone or cluster): cluster with 6 querynodes
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
```

### Current Behavior

1. the cpu usage of querynodes get down much when there are data inserting
2. also the cpu usage of querynodes get down a little when there are data deleting
![image](https://github.com/milvus-io/milvus/assets/82361606/f876b6ae-bcce-4a78-bab0-61b745801775)
 

### Expected Behavior

i think the cpu usage of querynode shall not be impacted

### Steps To Reproduce

```markdown
1. delete or insert while there are always searching requests
```

### Milvus Log

milvus pods:
```
yanliang-cd-mmszh-milvus-datanode-84dc7fdc9d-6gmjj                1/1     Running            0                 45h     10.102.7.163    devops-node11   <none>           <none>
yanliang-cd-mmszh-milvus-datanode-84dc7fdc9d-tqmh8                1/1     Running            0                 45h     10.102.6.120    devops-node10   <none>           <none>
yanliang-cd-mmszh-milvus-indexnode-5645dcbdf-6w8tn                1/1     Running            0                 45h     10.102.6.151    devops-node10   <none>           <none>
yanliang-cd-mmszh-milvus-indexnode-5645dcbdf-tk7jd                1/1     Running            0                 45h     10.102.9.47     devops-node13   <none>           <none>
yanliang-cd-mmszh-milvus-mixcoord-b46bf6b68-w7s4l                 1/1     Running            0                 45h     10.102.9.48     devops-node13   <none>           <none>
yanliang-cd-mmszh-milvus-proxy-6df5788676-lhzd5                   1/1     Running            0                 45h     10.102.9.53     devops-node13   <none>           <none>
yanliang-cd-mmszh-milvus-querynode-f8878984-292sn                 1/1     Running            0                 17h     10.102.5.90     devops-node21   <none>           <none>
yanliang-cd-mmszh-milvus-querynode-f8878984-7cwzm                 1/1     Running            0                 17h     10.102.9.180    devops-node13   <none>           <none>
yanliang-cd-mmszh-milvus-querynode-f8878984-gjp65                 1/1     Running            0                 17h     10.102.6.122    devops-node10   <none>           <none>
yanliang-cd-mmszh-milvus-querynode-f8878984-jzzbp                 1/1     Running            0                 17h     10.102.10.81    devops-node20   <none>           <none>
yanliang-cd-mmszh-milvus-querynode-f8878984-l8d42                 1/1     Running            0                 17h     10.102.9.182    devops-node13   <none>           <none>
yanliang-cd-mmszh-milvus-querynode-f8878984-wrrk9                 1/1     Running            0                 17h     10.102.7.13     devops-node11   <none>           <none>
```

**Comment by congqixia** [comment]
any difference in responding time/qps of search/query during the insert & delete process?

**Comment by xiaofan-luan** [comment]
I thought i might due to the slow search of growing segments?

**Comment by yanliang567** [comment]
delete almost makes no difference to search qps and latency, but insert impacts a lot.
![img_v2_fef920de-1c8c-4869-9aab-e33d41c714cg](https://github.com/milvus-io/milvus/assets/82361606/ec73c362-4fba-403e-93c7-3a648bc0f933)


> any difference in responding time/qps of search/query during the insert & delete process?

**Comment by yanliang567** [comment]
> I thought i might due to the slow search of growing segments?

BF search does not use much cpu?

**Comment by congqixia** [comment]
![image](https://github.com/milvus-io/milvus/assets/84113973/7e6d5d21-297a-4dc9-aad8-98575463d55a)
Indeed the insert caused some un-index growing segments loaded which lead to the performance downgrade
Looking into the delete case now

**Comment by yanliang567** [comment]
when searching with skip_growing=True, the delete requests make the cpu usage down :(
![image](https://github.com/milvus-io/milvus/assets/82361606/ffb940b9-308a-49fe-9580-bcd407253ba4)

**Comment by xiaofan-luan** [comment]
Good catch!
Milvus 2.3 we should more focus on performance on special use cases such as delete, filtering and high pressure

**Comment by yanliang567** [comment]
keep it active

**Comment by yanliang567** [comment]
seems not reproduced recently. lets keep it for a few more days.
