### ISSUE TITLE
[Bug]: Milvus 2.2.8 returns less count when search with topK

### ISSUE THREAD

**Issue by yuliu-eric** [milvus-io/milvus#24449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.8
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    kafka 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

This issue happens once a while after we have upgraded the milvus 2.x cluster from 2.2.3 to 2.2.8: compared with milvus 1.x, the same collection and entities, milvus 2.x returned less count when search with topk.

```
milvus 1.x returned res: nq = 10, topk = 100
milvus 2.x returned res: nq = 10, topk = 97

milvus 1.x returned res: nq = 10, topk = 100
milvus 2.x returned res: nq = 10, topk = 96

milvus 1.x returned res: nq = 10, topk = 100
milvus 2.x returned res: nq = 10, topk = 99

milvus 1.x returned res: nq = 10, topk = 100
milvus 2.x returned res: nq = 10, topk = 92

milvus 1.x returned res: nq = 10, topk = 100
milvus 2.x returned res: nq = 10, topk = 98
```

### Milvus Log

[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/11573699/milvus-log.tar.gz)

**Comment by yuliu-eric** [comment]
[milvus-log-with-etcd.tar.gz](https://github.com/milvus-io/milvus/files/11573852/milvus-log-with-etcd.tar.gz)

**Comment by congqixia** [comment]
@yuliu-eric thanks for you feedback
one quick question, do you have any duplicated pks in your dataset?

**Comment by yuliu-eric** [comment]
> one quick question, do you have any duplicated pks in your dataset?

Ideally it shall not happen.

**Comment by xiaofan-luan** [comment]
might be related with duplicated PK I guess
