### ISSUE TITLE
[Bug]: milvus-operator suddenly reported CrashLoopBackOff, retry 16 times in 80 minutes

### ISSUE THREAD

**Issue by maqiang515** [milvus-io/milvus#24463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.8
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2): java
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 136/768
- GPU: 
- Others: Data set 50 million
```

### Current Behavior

1、querynode 10 cpus: 4 Memory: 32GB load data set is normal; Same with cpu and memory, 14, 15, 16 can not load the data set properly
2、milvus-operator suddenly reported CrashLoopBackOff, retry 16 times in 80 minutes；How do I modify the memory of the milvus-operator pod

### Milvus Log

![image](https://github.com/milvus-io/milvus/assets/11402161/0ad02d06-f5fe-4314-b6e3-04e663c26379)#
[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/11584692/milvus-log.tar.gz)

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```gfm
> - Milvus version:2.2.8
> - Deployment mode(standalone or cluster):cluster
> - MQ type(rocksmq, pulsar or kafka):    pulsar 
> - SDK version(e.g. pymilvus v2.0.0rc2): java
> - OS(Ubuntu or CentOS): CentOS
> - CPU/Memory: 136/768
> - GPU: 
> - Others: Data set 50 million
> ```
> 
> ### Current Behavior
> 1、querynode 10 cpus: 4 Memory: 32GB load data set is normal; Same with cpu and memory, 14, 15, 16 can not load the data set properly 2、milvus-operator suddenly reported CrashLoopBackOff, retry 16 times in 80 minutes；How do I modify the memory of the milvus-operator pod
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> ![image](https://user-images.githubusercontent.com/11402161/241563145-0ad02d06-f5fe-4314-b6e3-04e663c26379.png)# [milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/11584692/milvus-log.tar.gz)
> 
> ### Anything else?
> _No response_

It seems to be OOM error.
How many querynodes you have, and how many data youn want to load.

Seems the limitiation is very small
<img width="270" alt="image" src="https://github.com/milvus-io/milvus/assets/83447078/34c35e9d-4d90-40e5-9066-e0cbb0ab643f">

**Comment by maqiang515** [comment]
> > ### Is there an existing issue for this?
> > 
> > * [x]   I have searched the existing issues
> > 
> > ### Environment
> > ```
> > - Milvus version:2.2.8
> > - Deployment mode(standalone or cluster):cluster
> > - MQ type(rocksmq, pulsar or kafka):    pulsar 
> > - SDK version(e.g. pymilvus v2.0.0rc2): java
> > - OS(Ubuntu or CentOS): CentOS
> > - CPU/Memory: 136/768
> > - GPU: 
> > - Others: Data set 50 million
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Current Behavior
> > 1、querynode 10 cpus: 4 Memory: 32GB load data set is normal; Same with cpu and memory, 14, 15, 16 can not load the data set properly 2、milvus-operator suddenly reported CrashLoopBackOff, retry 16 times in 80 minutes；How do I modify the memory of the milvus-operator pod
> > ### Expected Behavior
> > _No response_
> > ### Steps To Reproduce
> > _No response_
> > ### Milvus Log
> > ![image](https://user-images.githubusercontent.com/11402161/241563145-0ad02d06-f5fe-4314-b6e3-04e663c26379.png)# [milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/11584692/milvus-log.tar.gz)
> > ### Anything else?
> > _No response_
> 
> It seems to be OOM error. How many querynodes you have, and how many data youn want to load.
> 
> Seems the limitiation is very small <img alt="image" width="270" src="https://user-images.githubusercontent.com/83447078/241564496-34c35e9d-4d90-40e5-9066-e0cbb0ab643f.png">

16 Querynodes and performance tests; 10 querynode index type flat, data set 50 million, bad performance, want to try by adding querynode

**Comment by yanliang567** [comment]
/assign @haorenfsa 
could you please help to take a look?
/unassign

**Comment by xiaofan-luan** [comment]
> 

for 50 million 768 dim data, you will need at least
300G memory for HNSW, or 64G memory for FAISS IVF_SQ8,
I would recoomend to use 5 * 64G querynode or 10 * 32G

**Comment by xiaofan-luan** [comment]
> > 
> 
> for 50 million 768 dim data, you will need at least 300G memory for HNSW, or 64G memory for FAISS IVF_SQ8, I would recoomend to use 5 * 64G querynode or 10 * 32G

could you share the cluster config? And which node is crash loop back off?

**Comment by xiaofan-luan** [comment]
if it's coordinator, maybe you should just give 2 giga bytes memory for coordinator and see it works

**Comment by maqiang515** [comment]
> > > 
> > 
> > 
> > for 50 million 768 dim data, you will need at least 300G memory for HNSW, or 64G memory for FAISS IVF_SQ8, I would recoomend to use 5 * 64G querynode or 10 * 32G
> 
> could you share the cluster config? And which node is crash loop back off?

# This is a sample to deploy a milvus cluster in milvus-operator's default configurations.
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
  labels:
    app: milvus
spec:
  mode: cluster
  dependencies: 
    etcd:
      inCluster:
        values:
          extraEnvVars:
          - name: ETCD_ELECTION_TIMEOUT
            value: "25000"
          - name: ETCD_SNAPSHOT_COUNT
            value: "10000"
          - name: ETCD_ENABLE_PPROF
            value: "true"
          persistence:
            accessMode: ReadWriteOnce
            enabled: true
            size: 30Gi   #SSD Required
  components:
    dataCoord:
      resources:
        limits:
          cpu: "0.5"
          memory: 2Gi
    queryCoord:
      resources:
        limits:
          cpu: "0.5"
          memory: 2Gi
    indexCoord:
      resources:
        limits:
          cpu: "0.5"
          memory: 2Gi
    rootCoord:
      resources:
        limits:
          cpu: 1
          memory: 2Gi
    dataNode:
      replicas: 1
      resources:
        limits:
          cpu: 2
          memory: 8Gi
    indexNode:
      replicas: 4
      resources:
        limits:
          cpu: 8
          memory: 16Gi
    queryNode:
      replicas: 14
      resources:
        limits:
          cpu: 4
          memory: 32Gi
    proxy:
      replicas: 1
      resources:
        limits:
          cpu: 2
          memory: 8Gi
  config: 
    minio:
      bucketName: iflytek-bucket
    dataCoord:
      scheduler:
        cpuRation: 200
    proxy:
      timeTickInterval: 600
    queryCoord:
      overloadedMemoryThresholdPercentage: 95
      loadTimeoutSeconds: 1200
      segmentTaskTimeout: 240000

**Comment by maqiang515** [comment]
> if it's coordinator, maybe you should just give 2 giga bytes memory for coordinator and see it works

我还在找再哪修改，直接从pod 进行修改被禁止了；
![image](https://github.com/milvus-io/milvus/assets/11402161/ed38beac-908a-4e8e-aed4-45bdb8d8e90c)

**Comment by xiaofan-luan** [comment]
> 

@haorenfsa looks like the milvus operator crashed, could you take a look on it?

**Comment by maqiang515** [comment]
> 1、querynode 10 cpus: 4 Memory: 32GB load data set is normal; Same with cpu and memory, 14, 15, 16 can not load the data set properly

milvus-operator 问题已修改好，测试40分钟还未报错，请帮忙分析下面这个问题，load了一下还是不行，谢谢！
1、querynode 10 cpus: 4 Memory: 32GB load data set is normal; Same with cpu and memory, 14, 15, 16 can not load the data set properly

**Comment by haorenfsa** [comment]
@maqiang515  About milvus-operator, could please provide us the log of milvus-operator around the time when it gets OOM killed, so that we can prevent this problem from happening again. Thank you in advance.

**Comment by haorenfsa** [comment]
@maqiang515 And about milvus itself, are there any errors that the server returned? And also could please provide the logs of the queryCoord and one of the queryNode?

**Comment by maqiang515** [comment]
> @maqiang515 And about milvus itself, are there any errors that the server returned? And also could you please provide the logs of the queryCoord and one of the queryNode?

The log is provided above, and the component log is provided above
![image](https://github.com/milvus-io/milvus/assets/11402161/00c8c820-5082-4c7f-a910-7f07b296b259)

**Comment by maqiang515** [comment]
> @maqiang515 About milvus-operator, could please provide us the log of milvus-operator around the time when it gets OOM killed, so that we can prevent this problem from happening again. Thank you in advance.
The log is captured when an error occurs. View the oom in kubectl describe pod. Increase the memory by 1GB
[Uploading milvus-operator.txt…]()

**Comment by haorenfsa** [comment]
> The log is provided above, and the component log is provided above
Sry my bad, I'll check it

**Comment by haorenfsa** [comment]
@maqiang515 Hi looks like some queryNodes timeout when loading segments. Maybe the connection from your milvus to the Objects Storage is slow or maybe there's a but. cc @xiaofan-luan @yanliang567  any known issues?

For quick solution, you can try config the segment load timeout longer, wait your milvus updated and try again.

```yaml
apiVersion: milvus.io/v1beta1
kind: Milvus
# .... omit other fields
spec:
  config:
    queryCoord:
      segmentTaskTimeout: 600000 # 1 for 1ms.  default as 2 minute, try change to 600000 or larger
```
Apply above changes.

and wait for milvus updated:
```
kubectl wait milvus my-release --for=condition=milvusUpdated
```

Ref: 

QueryCoord: 
> [2023/05/28 10:32:01.339 +00:00] [WARN] [retry/retry.go:44] ["retry func failed"] ["retry time"=0] [error="follower 954 failed to load segment, reason [UnexpectedError] Error:GetObjectBuffer:  curlCode: 28, Timeout was reached"]
[2023/05/28 10:32:01.339 +00:00] [WARN] [task/executor.go:198] ["failed to load segment"] [taskIDs="[285]"] [collectionID=441644262342220412] [shard=my-release-rootcoord-dml_8_441644262342220412v8] [segmentIDs="[441644262344609858]"] [nodeID=954] [source=2] [reason="follower 954 failed to load segment, reason [UnexpectedError] Error:GetObjectBuffer:  curlCode: 28, Timeout was reached"]

queryNode:
> [2023/05/28 10:32:05.607 +00:00] [WARN] [querynode/cgo_helper.go:56] ["LoadFieldData failed, C Runtime Exception: [UnexpectedError] Error:GetObjectBuffer:  curlCode: 28, Timeout was reached\n"]
[2023/05/28 10:32:05.613 +00:00] [INFO] [gc/gc_tuner.go:84] ["GC Tune done"] ["previous GOGC"=200] ["heapuse "=35] ["total memory"=128] ["next GC"=68] ["new GOGC"=200] [gc-pause=414.015µs] [gc-pause-end=1685269925612271483]
[2023/05/28 10:32:05.616 +00:00] [ERROR] [querynode/segment_loader.go:177] ["load segment failed when load data into memory"] [collectionID=441644262342220412] [segmentType=Sealed] [partitionID=441644262342220577] [segmentID=441644262344278150] [error="[UnexpectedError] Error:GetObjectBuffer:  curlCode: 28, Timeout was reached"] [stack="github.com/milvus-io/milvus/internal/querynode.(*segmentLoader).LoadSegment.func3\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/segment_loader.go:177\ngithub.com/milvus-io/milvus/internal/util/funcutil.ProcessFuncParallel.func3\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/parallel.go:83"]
[2023/05/28 10:32:05.616 +00:00] [ERROR] [funcutil/parallel.go:85] [loadSegmentFunc] [error="[UnexpectedError] Error:GetObjectBuffer:  curlCode: 28, Timeout was reached"] [idx=0] [stack="github.com/milvus-io/milvus/internal/util/funcutil.ProcessFuncParallel.func3\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/parallel.go:85"]

**Comment by maqiang515** [comment]
> ```yaml
> 600000 
> ```
I tried to change this parameter to 240000, but it still didn't work. I tried to change it to 600000. At the same time look at the source querynode error; Look at the increase ren'w thinks the parameters don't know what's going to happen under test
scheduler:
    receiveChanSize: 10240
grouping:   
    maxNQ: 50000
![image](https://github.com/milvus-io/milvus/assets/11402161/b5c07a6d-d8e1-43f8-8d67-49709028d6ab)

**Comment by jiaoew1991** [comment]
> 

@maqiang515  The code in the screenshot is for handling small query merging, which occurs before the execution of query tasks.
