### ISSUE TITLE
[Bug]: [Nightly]Kafka runs slowly and will be killed for 6h timeout with load collection timeout error

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#24473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:0fe8342
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):   kafka 
- SDK version(e.g. pymilvus v2.0.0rc2):2.4.0.dev27
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Kafka runs slowly and will be killed for 6h timeout with load collection timeout error.
```
[2023-05-28 22:02:00,922 - ERROR - ci_test]: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 770, in load_partitions
    response = future.result()
  File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 797, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2023-05-28T22:02:00.919989628+00:00", grpc_status:4}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 370, in load
    conn.load_partitions(self._name, partition_names, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 64, in handler
    raise MilvusException(message=f"rpc deadline exceeded: {timeout_msg}") from e
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 120s)>
 (api_request.py:39)
```

### Expected Behavior

pass

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/386/pipeline/155
2. log: [artifacts-milvus-distributed-kafka-nightly-386-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/386/artifact/artifacts-milvus-distributed-kafka-nightly-386-pymilvus-e2e-logs.tar.gz)
3. failure started time: [2023-05-28T18:22:26.805Z] [gw0] [ 37%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_normal_default_params[32-True-False-search_params2]

**Comment by NicoYuan1986** [comment]
Update: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/389/pipeline/299/
log: [artifacts-milvus-distributed-pulsar-nightly-389-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/389/artifact/artifacts-milvus-distributed-pulsar-nightly-389-pymilvus-e2e-logs.tar.gz)

**Comment by smellthemoon** [comment]
["[core][Channel #3 SubChannel #4] grpc: addrConn.createTransport failed to connect to {\n  \"Addr\": \"localhost:2379\",\n  \"ServerName\": \"localhost\",\n  \"Attributes\": null,\n  \"BalancerAttributes\": null,\n  \"Type\": 0,\n  \"Metadata\": null\n}. Err: connection error: desc = \"transport: Error while dialing: dial tcp [::1]:2379: connect: connection refused\""]
too many repeated logs in both two situations.
<img width="1363" alt="1" src="https://github.com/milvus-io/milvus/assets/64083300/d4109523-85c3-42c4-a778-d751b9bcbb4f">
etcd refuse connection during this time.

**Comment by NicoYuan1986** [comment]
not reproduced.
