### ISSUE TITLE
milvus.search() return empty list [] in use gpu case

### ISSUE THREAD

**Issue by MRCHEN3303** [milvus-io/milvus#2449]
集合大小4.5万，使用以下命令搜索：
status, results = milvus.search(collection_name='face_info',
                                                    query_records=query,
                                                    top_k=1,
                                                    params={'nprobe': 64},
                                                    partition_tags=[’B‘，’C‘，’D‘])
（注：query 为 1000 个 512维向量，gpu使用阈值为1000，所以触发了GPU搜索）
results的结果示例如下：
[[<milvus.client.abstract.QueryResult object at 0x7fc70c7fd0b8>]
[]
....
[<milvus.client.abstract.QueryResult object at 0x7fc70c7fd0f0>]]
出现[]这种空的情况。

执行上述语句前，删除了集合中的一个分区A.

**Comment by MRCHEN3303** [comment]
集合 nlist=1024  
索引类型：IVFLAT    
'metric_type': MetricType.IP

**Comment by scsven** [comment]
@MRCHEN3303 Hi, which version of Milvus happens on?

**Comment by shengjun1985** [comment]
IVF GPU doesn't support metric type IP now.
Please wait for 0.10.0.
