### ISSUE TITLE
每天的第一次搜索会很慢

### ISSUE THREAD

**Issue by tianyuzhu** [milvus-io/milvus#2452]
1、请问一下milvus现在把数据放在内存的策略是什么样的？我现在只有一个collection(名字叫xxx_512_sq8h)，每天一个partition，做搜索时从当天的数据中搜索会很快，但是从之前几天的数据中搜索，第一次会很慢，后面的搜索就会很快，第二天再执行往天的搜索，也是同样的现象，是不是bug？可以通过哪些方式解决？系统环境和配置如下：
2080ti，120G内存，CPU E5-2678 v3
Method of installation (Docker)
Milvus version (v0.9.0)

索引类型：IVFSQ8H，512维
系统只运行了3天，总共3个partition，每个partition数据量在4~5万条之间，当前的数据总量：13万条左右。

milvus配置文件：
db_config:
    preload_collection: xxx_512_sq8h

gpu_resource_config:
    enable: true
    cache_capacity: 2

cache_config:
    cpu_cache_capacity: 50

engine_config
    use_blas_threshold: 1100
    gpu_search_threshold: 1000

相关代码：
        //创建索引
        JSONObject indexParamsJson = new JSONObject();
        indexParamsJson.put("nlist", 16384);
        IndexType indexType = IndexType.IVF_SQ8_H;       
        Index index = new Index.Builder(collectionName, indexType)
                .withParamsInJson(indexParamsJson.toString())
                .build();
        Response createIndexResponse = client.createIndex(index);

       //搜索
        JSONObject searchParamsJson = new JSONObject();
        searchParamsJson.put("nprobe", 64);
        SearchParam.Builder builder = new SearchParam.Builder(tableName)
                .withFloatVectors(features)
                .withTopK(topK)
                .withParamsInJson(searchParamsJson.toString());
        SearchResponse searchResponse = client.search(builder.build());

2、在内存不足的情况下，我想把最新15天或30天的数据常驻内存，达到热数据快速搜索的目的，请问有什么方式可以做到？

**Comment by tinkerlin** [comment]
You need to increase cpu_cache_capacity.

**Comment by tianyuzhu** [comment]
现在的数据总大小只有400M，配置文件里 cpu_cache_capacity: 50

**Comment by yhmo** [comment]
@tianyuzhu 
你的数据量很小，理论上往天的数据只要搜索一次就会留在缓存里，比如你在第二天搜了第一天的数据，那么你在第三天再去搜索第一天的数据时，那些数据已经在缓存了，不应该会慢。除非你在搜索之前有增加新的数据插入到第一天的那个分区里，这样就会让缓存里的数据失效，因为会重写一份新数据文件。

**Comment by tianyuzhu** [comment]
数据确实在不停的写入，包括晚上，我第二天来查询的时候partition里也有头一天的partition，我试验一下
