### ISSUE TITLE
[Bug]: index_building_progress comes to 0 indexd_rows after manual compact()

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#24538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0 
- Deployment mode(standalone or cluster):  cluster
- MQ type(rocksmq, pulsar or kafka):
```

### Current Behavior

the indexed_rows was same as total_rows, but after manually call compact(), it comes to less and less, and to 0 at the end.
```
utility.index_building_progress('rand_1m_1536d')
{'total_rows': 10000000, 'indexed_rows': 0}
```

### Expected Behavior

should persist during compaction

**Comment by xiaofan-luan** [comment]
/assign @xiaocai2333 
can we also return current 

> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```gfm
> - Milvus version: 2.2.0 
> - Deployment mode(standalone or cluster):  cluster
> - MQ type(rocksmq, pulsar or kafka):
> ```
> 
> ### Current Behavior
> the indexed_rows was same as total_rows, but after manually call compact(), it comes to less and less, and to 0 at the end.
> 
> ```
> utility.index_building_progress('rand_1m_1536d')
> {'total_rows': 10000000, 'indexed_rows': 0}
> ```
> 
> ### Expected Behavior
> should persist during compaction
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

This might be expected? because if do compaction then all the data is not indexed.

It should be reasonable to return more info about:
current querynode serving index stats.
current stats
last build index stats

**Comment by yanliang567** [comment]
agree to return more info for this, or the users might be confused whether milvus is running on BF searching or indexing

**Comment by xiaocai2333** [comment]
After discussion, we decided to add a parameter `to_be_indexed_rows` to indicate how much data still needs to be indexed.
1. return additional parameters `to_be_indexed_rows`, indicating how much data needs to be indexed.
2. example:
  - segments: A(2048, indexed), B(2048 not indexed) =(compaction)=> C(4096, not indexed)
  - describe result: `total_rows: 4096`, `indexed_rows: 2048`, `to_be_indexed_rows:4096`, `state: InProgress`
3. example:
  - segments: A(2048, indexed), B(2048 not indexed) =(compaction)=> C(4096, not indexed), segment D (2048, insert after create index)
  - describe result: `total_rows: 6144`, `indexed_rows: 2048`, `to_be_indexed_rows:6144`, `state: InProgress`
  - after segment C is indexed, describe index result: `total_rows: 6144`, `indexed_rows: 4096`, `to_be_indexed_rows:2048`, `state: Finished`

**Comment by xiaocai2333** [comment]
@yanliang567 
For your example, we would return `total_rows: 1000000, indexed_rows:1000000, to_be_indexed_rows:1000000`

**Comment by xiaocai2333** [comment]
Tips: rename `to_be_indexed_rows` to `pending_indexed_rows`

**Comment by yanliang567** [comment]
what about `pending_reindex_rows` to indicates that the are to be re-indexed for smart optimization

**Comment by xiaofan-luan** [comment]
> 

pending index  rows should cover the new generated segment rows and growing segments

**Comment by xiaocai2333** [comment]
/assign @yanliang567 
@yanliang567 please verify it.

**Comment by yanliang567** [comment]
verified on master-20230605-11db4174
