### ISSUE TITLE
[Bug]: Lack error detection when search parameter 'metric_type' is different from index

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#24533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2(2.2.0-20230530-f3fb1950)
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.9.dev25
```

### Current Behavior

Lack error detection when search parameter 'metric_type' is different from index.

```
>>> print(collection.index().params)
{'M': '30', 'efConstruction': '360', 'index_type': 'HNSW', 'metric_type': 'IP'}
>>> search_params = {"metric_type": "L2"}
>>> res = collection.search([vector], "float_vector", search_params, 10)
>>> print(res[0].ids)
[]
```

### Expected Behavior

raise exception

### Steps To Reproduce

![image](https://github.com/milvus-io/milvus/assets/109071306/81329574-9408-42a6-b804-030e3ca7ab2d)

**Comment by yanliang567** [comment]
it reproduces on non empty collection 2.2.0-20230602-3844f45d with pymilvus 2.2.9 dev36
![image](https://github.com/milvus-io/milvus/assets/82361606/aae9cc8d-4dfc-4bce-86b4-ed94f5c26022)

**Comment by NicoYuan1986** [comment]
Fixed.
