### ISSUE TITLE
[Bug]: Error message "DataCoord is not serving" then restarting node results in full data loss.

### ISSUE THREAD

**Issue by arunk054** [milvus-io/milvus#24544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.2
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): Nomad
- SDK version(e.g. pymilvus v2.0.0rc2): Native GRPC client
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: N/A
- Others:
```

### Current Behavior

Our cluster is receiving Insert requests at about 0.1 QPS and we have the Collection loaded in memory with IVF_SQ8 and a size of ~8 Million embeddings (640 dimension).
The cluster has been running for more than a month but all of a sudden we start seeing this error: `"getSegmentID failed: SegmentIDAllocator failRemainRequest err:syncSegmentID Failed:DataCoord is not serving"`. At the same time all ingestion is also erroring out.
While this happens we are able to see all the collections but not able to Insert or Search or create collection. This happens for about an hour. and then we restart the DataCoord node. After which the errors stop but we see all collections are lost. We are able to create new collections and perform insert / search but all prior collections are lost.

### Expected Behavior

We expected no data loss after restarting data-coord node.

### Steps To Reproduce

```markdown
N/A
```

### Milvus Log

The logs are uploaded [here](https://drive.google.com/drive/folders/1E8wCFDPxCiafSOoguizp1IHYYzJSlYnh?usp=drive_link)

### Anything else?

N/A

**Comment by jiaoew1991** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```gfm
> - Milvus version: 2.2.2
> - Deployment mode(standalone or cluster): cluster
> - MQ type(rocksmq, pulsar or kafka): Nomad
> - SDK version(e.g. pymilvus v2.0.0rc2): Native GRPC client
> - OS(Ubuntu or CentOS): Ubuntu
> - CPU/Memory: 
> - GPU: N/A
> - Others:
> ```
> 
> ### Current Behavior
> Our cluster is receiving Insert requests at about 0.1 QPS and we have the Collection loaded in memory with IVF_SQ8 and a size of ~8 Million embeddings (640 dimension). The cluster has been running for more than a month but all of a sudden we start seeing this error: `"getSegmentID failed: SegmentIDAllocator failRemainRequest err:syncSegmentID Failed:DataCoord is not serving"`. At the same time all ingestion is also erroring out. While this happens we are able to see all the collections but not able to Insert or Search or create collection. This happens for about an hour. and then we restart the DataCoord node. After which the errors stop but we see all collections are lost. We are able to create new collections and perform insert / search but all prior collections are lost.
> 
> ### Expected Behavior
> We expected no data loss after restarting data-coord node.
> 
> ### Steps To Reproduce
> ```gfm
> N/A
> ```
> 
> ### Milvus Log
> The logs are uploaded [here](https://drive.google.com/drive/folders/1E8wCFDPxCiafSOoguizp1IHYYzJSlYnh?usp=drive_link)
> 
> ### Anything else?
> N/A

Hi  @arunk054 What do you mean by MQ type is Nomad？

**Comment by weiliu1031** [comment]
found some clue about  complete data loss,  base on the log, we found that here comes access problem with etcd data dir suddenly，and then it trigger milvus restarts but no meta data found from the etcd, so all collection lost
![image](https://github.com/milvus-io/milvus/assets/108661493/4314462a-67ff-4e45-8755-1809231ea614)

**Comment by ganderaj** [comment]
We have deployed Milvus (v2.2.13) on AWS EKS which went into unhealthy state post applying HPA rules (not sure if it caused it though). 

Pod Error Messages as per container logs --

On Rootcoord
`[error="find no available querycoord, check querycoord state"]`
`[error="err: find no available datacoord, check datacoord state"]`
 
On Datacord and Querycord
`[error="find no available rootcoord, check rootcoord state"]`

Environment was back to being stable 20m later after undergoing couple of pod restarts across several components. However, **ALL DATA WAS LOST**. The databases, collections, roles, grants, users among others were all purged. It appeared as if it is a fresh new installation.

Not sure if this is related to the parent issue but wanted to seek Moderator's input. What could potentially lead to data loss ? K8s deployments are typically expected to be stateless how to achieve this model with Milvus on EKS ?

**Comment by xiaofan-luan** [comment]
> We have deployed Milvus (v2.2.13) on AWS EKS which went into unhealthy state post applying HPA rules (not sure if it caused it though).
> 
> Pod Error Messages as per container logs --
> 
> On Rootcoord `[error="find no available querycoord, check querycoord state"]` `[error="err: find no available datacoord, check datacoord state"]`
> 
> On Datacord and Querycord `[error="find no available rootcoord, check rootcoord state"]`
> 
> Environment was back to being stable 20m later after undergoing couple of pod restarts across several components. However, **ALL DATA WAS LOST**. The databases, collections, roles, grants, users among others were all purged. It appeared as if it is a fresh new installation.
> 
> Not sure if this is related to the parent issue but wanted to seek Moderator's input. What could potentially lead to data loss ? K8s deployments are typically expected to be stateless how to achieve this model with Milvus on EKS ?

My guess is you changed some of your milvus cluster settings when you apply HPA.
Please check your etcd and S3 rootpath is set as expected

**Comment by xiaofan-luan** [comment]
Milvus itself has no data persistent.
All the rely on is etcd for meta, kafka/pulsar for growing data and S3 for data.
From your description, all collection has gone, my guess is that your etcd data is loss for some reason, or you configured the wrong root path

**Comment by ganderaj** [comment]
> Milvus itself has no data persistent. All the rely on is etcd for meta, kafka/pulsar for growing data and S3 for data. From your description, all collection has gone, my guess is that your etcd data is loss for some reason, or you configured the wrong root path

From your reply I take it that ETCD in its PVCs store data concerning DBs, Collections etcs,. If this is accurate, how do we persist data should there be an issue with the EKS Node or EBS Volume ? What shall be our Disaster Recovery strategy ?

**Comment by xiaofan-luan** [comment]
> > Milvus itself has no data persistent. All the rely on is etcd for meta, kafka/pulsar for growing data and S3 for data. From your description, all collection has gone, my guess is that your etcd data is loss for some reason, or you configured the wrong root path
> 
> From your reply I take it that ETCD in its PVCs store data concerning DBs, Collections etcs,. If this is accurate, how do we persist data should there be an issue with the EKS Node or EBS Volume ? What shall be our Disaster Recovery strategy ?

etcd itself should be 3 replicas.
If all the replicas crashed then your data might loss.
