### ISSUE TITLE
[Enhancement]: Assign metric type in the search request

### ISSUE THREAD

**Issue by bigsheeper** [milvus-io/milvus#24575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Assign metric type in the search request when the user has not explicitly assigned.

**Comment by filip-halt** [comment]
Im running into issues with this. Running milvus.2.20-latest and master pymilvus im getting <MilvusException: (code=1, message=metric_type not found in search_params)>. It looks like it should be in 2.2.0 latest.

**Comment by bigsheeper** [comment]
done
