### ISSUE TITLE
[Bug]: datanode channel_meta.go:224 "failed to init bloom filter"

### ISSUE THREAD

**Issue by bedivere2018** [milvus-io/milvus#24584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.8
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus
- OS(Ubuntu or CentOS): CentOS Linux release 7.9.2009 (Core)
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

This morning when I opened Attu, I found that the data in Milvus was not coming out or was very slow. Upon checking the milvus-logs, I found that there were error logs in the datanode. 

[2023/06/01 02:41:27.482 +00:00] [ERROR] [datanode/channel_meta.go:224] ["failed to init bloom filter"] ["segment ID"=441662789977048170] [error="All attempts results:\nattempt #1:NoSuchKey(key=files/stats_log/441662789921245639/441662789921245640/441662789977048170/100/441662789977048515)\nattempt #2:NoSuchKey(key=files/stats_log/441662789921245639/441662789921245640/441662789977048170/100/441662789977048752)\nattempt #3:NoSuchKey(key=files/stats_log/441662789921245639/441662789921245640/441662789977048170/100/441662789977049102)\nattempt #4:NoSuchKey(key=files/stats_log/441662789921245639/441662789921245640/441662789977048170/100/441662789977049442)\nattempt #5:NoSuchKey(key=files/stats_log/441662789921245639/441662789921245640/441662789977048170/100/441662789977049893)\nattempt #6:NoSuchKey(key=files/stats_log/441662789921245639/441662789921245640/441662789977048170/100/441662789977050358)\nattempt #7:NoSuchKey(key=files/stats_log/441662789921245639/441662789921245640/441662789977048170/100/441662789977050615)\nattempt #8:NoSuchKey(key=files/stats_log/441662789921245639/441662789921245640/441662789977048170/100/441662789977050809)\nattempt #9:NoSuchKey(key=files/stats_log/441662789921245639/441662789921245640/441662789977048170/100/441662789977051092)\nattempt #10:NoSuchKey(key=files/stats_log/441662789921245639/441662789921245640/441662789977048170/100/441662789977051325)\n"] [stack="github.com/milvus-io/milvus/internal/datanode.(*ChannelMeta).addSegment\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/channel_meta.go:224\ngithub.com/milvus-io/milvus/internal/datanode.(*dataSyncService).initNodes.func2\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:257\ngithub.com/milvus-io/milvus/internal/util/concurrency.(*Pool).Submit.func1\n\t/go/src/github.com/milvus-io/milvus/internal/util/concurrency/pool.go:46\ngithub.com/panjf2000/ants/v2.(*goWorker).run.func1\n\t/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.8/worker.go:70"]

I haven't done any special operations, just normal use of Pymilvus to write，delete data and query vectors. 
The current symptoms are as follows: 
1. When viewing the collection on Attu, it reports "Error: Error: 4 DEADLINE_EXCEEDED: Deadline exceeded"; 
2. The speed of writing and querying Milvus has become slower; 
It is uncertain whether there are some deeper impacts.

How can I fix these error logs?

### Milvus Log

[datanode-50.log](https://github.com/milvus-io/milvus/files/11620436/datanode-50.log)

### Anything else?

I'm not sure if this issue is the same problem.
https://github.com/milvus-io/milvus/issues/22699

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```gfm
> - Milvus version: v2.2.8
> - Deployment mode(standalone or cluster): cluster
> - MQ type(rocksmq, pulsar or kafka): pulsar
> - SDK version(e.g. pymilvus v2.0.0rc2): pymilvus
> - OS(Ubuntu or CentOS): CentOS Linux release 7.9.2009 (Core)
> - CPU/Memory: 
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> This morning when I opened Attu, I found that the data in Milvus was not coming out or was very slow. Upon checking the milvus-logs, I found that there were error logs in the datanode.
> 
> [2023/06/01 02:41:27.482 +00:00] [ERROR] [datanode/channel_meta.go:224] ["failed to init bloom filter"] ["segment ID"=441662789977048170] [error="All attempts results:\nattempt #1:NoSuchKey(key=files/stats_log/441662789921245639/441662789921245640/441662789977048170/100/441662789977048515)\nattempt #2:NoSuchKey(key=files/stats_log/441662789921245639/441662789921245640/441662789977048170/100/441662789977048752)\nattempt #3:NoSuchKey(key=files/stats_log/441662789921245639/441662789921245640/441662789977048170/100/441662789977049102)\nattempt #4:NoSuchKey(key=files/stats_log/441662789921245639/441662789921245640/441662789977048170/100/441662789977049442)\nattempt #5:NoSuchKey(key=files/stats_log/441662789921245639/441662789921245640/441662789977048170/100/441662789977049893)\nattempt #6:NoSuchKey(key=files/stats_log/441662789921245639/441662789921245640/441662789977048170/100/441662789977050358)\nattempt #7:NoSuchKey(key=files/stats_log/441662789921245639/441662789921245640/441662789977048170/100/441662789977050615)\nattempt #8:NoSuchKey(key=files/stats_log/441662789921245639/441662789921245640/441662789977048170/100/441662789977050809)\nattempt #9:NoSuchKey(key=files/stats_log/441662789921245639/441662789921245640/441662789977048170/100/441662789977051092)\nattempt #10:NoSuchKey(key=files/stats_log/441662789921245639/441662789921245640/441662789977048170/100/441662789977051325)\n"] [stack="github.com/milvus-io/milvus/internal/datanode.(*ChannelMeta).addSegment\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/channel_meta.go:224\ngithub.com/milvus-io/milvus/internal/datanode.(*dataSyncService).initNodes.func2\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:257\ngithub.com/milvus-io/milvus/internal/util/concurrency.(*Pool).Submit.func1\n\t/go/src/github.com/milvus-io/milvus/internal/util/concurrency/pool.go:46\ngithub.com/panjf2000/ants/v2.(*goWorker).run.func1\n\t/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.8/worker.go:70"]
> 
> I haven't done any special operations, just normal use of Pymilvus to write，delete data and query vectors. The current symptoms are as follows:
> 
> 1. When viewing the collection on Attu, it reports "Error: Error: 4 DEADLINE_EXCEEDED: Deadline exceeded";
> 2. The speed of writing and querying Milvus has become slower;
>    It is uncertain whether there are some deeper impacts.
> 
> How can I fix these error logs?
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> [datanode-50.log](https://github.com/milvus-io/milvus/files/11620436/datanode-50.log)
> 
> ### Anything else?
> I'm not sure if this issue is the same problem. #22699

1. can you sure you are using 2.2.8? We don't see similar issue in 2.2.8 but this is a common issue before 2.2.8
2. There seems to be a lot of "upload to blob storage wrong" please check if your minio or S3 is working as expected.
3. Are you trying to deploy multiple milvus on same OSS?

**Comment by bedivere2018** [comment]
> 1. can you sure you are using 2.2.8? We don't see similar issue in 2.2.8 but this is a common issue before 2.2.8
> 2. There seems to be a lot of "upload to blob storage wrong" please check if your minio or S3 is working as expected.
> 3. Are you trying to deploy multiple milvus on same OSS?

Thanks for your reply.
1. Sure.
2. Minio is working normally.
3. Only one milvus clustered deployed, not multiple.

When setup milvus clustered with helm, I made some changes to the parameters in value.yaml. Will it have any impact?
extraConfigFiles:
  user.yaml: |+
    common:
      retentionDuration: 0
    dataCoord:
      enableGarbageCollection: true
      gc:
        interval: 1800
        missingTolerance: 10800
        dropTolerance: 10800
    log:
      level: error

If this is a common issue before 2.2.8，any solutions available?

**Comment by xiaofan-luan** [comment]
> > 1. can you sure you are using 2.2.8? We don't see similar issue in 2.2.8 but this is a common issue before 2.2.8
> > 2. There seems to be a lot of "upload to blob storage wrong" please check if your minio or S3 is working as expected.
> > 3. Are you trying to deploy multiple milvus on same OSS?
> 
> Thanks for your reply.
> 
> 1. Sure.
> 2. Minio is working normally.
> 3. Only one milvus cluster deployed, not multiple.
> 
> When setup milvus cluster with helm, I made some changes to the parameters in value.yaml. Will it have any impact? extraConfigFiles: user.yaml: |+ common: retentionDuration: 0 dataCoord: enableGarbageCollection: true gc: interval: 1800 missingTolerance: 10800 dropTolerance: 10800 log: level: error
> 
> If this is a common issue before 2.2.8，any solutions available?

Seems all ok to me.  Could you check from datacoord log see what happens to files/stats_log/441662789921245639/441662789921245640/441662789977048170/100/441662789977051325?

441662789921245639 collection ID
441662789921245640 partitonID 
441662789977048170 segmentID 
100 fieldID
441662789977051325 fileID.

so it seems that the data file in etcd is missing. if you can check in datacoord logs for what happens for 441662789977048170 and 441662789977051325 that would be super helpful

**Comment by bedivere2018** [comment]
> Seems all ok to me. Could you check from datacoord log see what happens to files/stats_log/441662789921245639/441662789921245640/441662789977048170/100/441662789977051325?
> 
> 441662789921245639 collection ID 441662789921245640 partitonID 441662789977048170 segmentID 100 fieldID 441662789977051325 fileID.
> 
> so it seems that the data file in etcd is missing. if you can check in datacoord logs for what happens for 441662789977048170 and 441662789977051325 that would be super helpful

I'm sorry, upon checking, there were no datacoord error logs in milvus-log. 
Perhaps setting the log level to error was not necessary? 

Currently, the situation is that after attempting to restart the cluster, querycoord failed to start. 
Due to the downtime of Milvus has been quite long, I had to uninstall Milvus, cleared minio bucket and local directory, reinstalled it, and restored the data using the backup. 
I am not sure if this issue will reoccur next time.

**Comment by bedivere2018** [comment]
I have experienced 2 more issues recently：
The first time, the datanode reported the same error as before, and the querycoord also had an error, causing slow write and query performance.
The second time, the datanode work normally, but the querycoord had an error, causing slow query performance.
The datanode reported errors such as "compact wrong" and "download from blob storage wrong", but the service was not affected.
The querycoord service had exceptions and kept reporting "get recovery info failed", "failed to get next targets for collection", and "failed to update next target for collection".
[querycoord-33.log](https://github.com/milvus-io/milvus/files/11659232/querycoord-33.log)

We suspect that the issue may be related to the fact that we are using gigabit network cards. From the monitor, we noticed that when using milvus-backup tool to backup milvus, the network card bandwidth was fully utilized, which may have caused communication issues among the milvus components. However, the components are not robust enough to automatically recover from errors.
We are now considering adding two more network cables to create a dedicated network card for backup, or finding a way to limit the bandwidth of the milvus-backup tool.

@xiaofan-luan, do you have any advice for me?

**Comment by xiaofan-luan** [comment]
could you maintain longer about the datacoord logs?

Seems datanode try to save data to datacoord but the segment has already be deleted. But the log is too short and we don't see the reason why it happened.

**Comment by xiaofan-luan** [comment]
Seems like object storage is the key trigger of this issue. It would be really helpful if you persistent the log with file or Loki/Kibana
