### ISSUE TITLE
[Bug]: The data loading speed of Milvus 2.2.0 is too slow

### ISSUE THREAD

**Issue by linggong2023** [milvus-io/milvus#24598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

[Bug]: The data loading speed of Milvus 2.2.0 is too slow，When I click on 'Load' in Attu, the data loading speed is very slow.

**Comment by linggong2023** [comment]
[logs.tar.gz](https://github.com/milvus-io/milvus/files/11624084/logs.tar.gz)

**Comment by yanliang567** [comment]
@linggong2023 how much data(dim and rows) are we talking about here? and how much time do you expect to complete?

/assign @jiaoew1991 
/unassign

**Comment by linggong2023** [comment]
2.2.6 query is not respons
[logs.tag.gz](https://github.com/milvus-io/milvus/files/11631540/logs.tag.gz)

**Comment by yanliang567** [comment]
could you please retry with latest milvus release v2.2.9 and attu release 2.2.5 @linggong2023
