### ISSUE TITLE
[Bug]: querynode memory keeps increasing even the rows counts did not changed a lot by insert and delete requests

### ISSUE THREAD

**Issue by Satyadev592** [milvus-io/milvus#24597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.3
- Deployment mode(standalone or cluster): Cluster (AWS, not on k8s)
- MQ type(rocksmq, pulsar or kafka): Pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.3
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 8/64
- GPU: -
- Others: -
```

### Current Behavior

We are noticing an increase in query nodes RAM utilisation over time. Our day level operations can be classified as follows:
300K inserts
300K deletes
1M updates (delete followed by insert)
Technically our num_entities is not changing over time but our query node utilisation is increasing over time. Here's a graph illustrating our issue:
<img width="1469" alt="image" src="https://github.com/milvus-io/milvus/assets/12812275/37fafcff-9f3e-4b48-aacb-458bb19f6e08">
We have tried manual compaction every day to see if that solves the issue - but it does not. 
We are currently doing rolling restarts of the query nodes which gets the query nodes back to 35GB usage.

### Expected Behavior

The memory utilisation for the query nodes should plateau for our use case as the number of entities/vectors is not increasing.

**Comment by yanliang567** [comment]
@Satyadev592 sounds like a known issue about compaction and handoff in v2.2.3, any chance to run a test on v2.2.8?
/assign @Satyadev592

**Comment by yanliang567** [comment]
we have a similar test scenario in house with latest build: every day we do insert and delete with almost same counts to make the total rows not changed a lot. We can see that the memory of query node keeps stable
![image](https://github.com/milvus-io/milvus/assets/82361606/fdefd765-ca8d-465f-bd81-2697ffaa5a59)

**Comment by xiaofan-luan** [comment]
> keeps stable

try to trigger on compaction and see what's happening?

Using 2.2.8 might be a better choice

**Comment by yanliang567** [comment]
@Satyadev592 we have release v2.2.9, any chance to run a test on the latest release?

**Comment by Satyadev592** [comment]
We upgraded to 2.2.9 and thought this issue is behind us but unfortunately it was short lived. 
The issue where memory util spikes up randomly presented itself yet again. Attaching some graphs for reference. 

The memory spike seems to be correlated with DDL requests showpartitions and describecollection. 

<img width="1593" alt="Screenshot 2023-10-09 at 10 03 49 AM" src="https://github.com/milvus-io/milvus/assets/12812275/3364f5c0-d521-4ea0-bfce-05a71c3b4ee6">
<img width="1479" alt="Screenshot 2023-10-09 at 10 04 18 AM" src="https://github.com/milvus-io/milvus/assets/12812275/dad0e897-31c9-4718-bd91-0537e732af8b">

**Comment by yanliang567** [comment]
@Satyadev592 Could you please attach the etcd backup for investigation？ Check this: https://github.com/milvus-io/birdwatcher for details about how to backup etcd with birdwatcher

**Comment by Satyadev592** [comment]
[Untitled.txt](https://github.com/milvus-io/milvus/files/12853387/Untitled.txt)
Here's the backup as requested.

**Comment by xiaofan-luan** [comment]
@Satyadev592 could you try to manual compact and check if memory descrease?
