### ISSUE TITLE
[Bug]: Milvus doesnt resort to Knowhere defaults

### ISSUE THREAD

**Issue by filip-halt** [milvus-io/milvus#24608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: Master  
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus master
```

### Current Behavior

When creating an index using: 
{
    "index_type": "HNSW",
    "metric_type": "IP",
    "params": {}
}

The process failes saying that efConstruction value isnt between 5,500.
  

### Expected Behavior

The knowhere defailt config values should be used in this case instead of an error. This worked before. 

<img width="1237" alt="image" src="https://github.com/milvus-io/milvus/assets/81822489/c2f4f0e0-a893-4fa6-a0e4-711c0fb50e4e">

The cause is from this block in [indexparamcheck](https://github.com/milvus-io/milvus/blob/93ea9c492506902403ba1ff0dc9dce9c2e6da973/pkg/util/indexparamcheck/utils.go#L33).

If a value is missing it shouldnt fail but rather default to HNSW config in knowhere.

**Comment by yanliang567** [comment]
/assign @longjiquan @NicoYuan1986 
could you please take a look into this issue?

/unassign

**Comment by longjiquan** [comment]
Could you help confirm the milvus version and pymilvus version which resort to Knowhere defaults? It seems we always reported an error when these required parameters are not passed.
/assign @filip-halt

**Comment by filip-halt** [comment]
Ah, I looked through my history and saw that it was only the search params that were defaulted to. Just tested 2.2.3-present and you are right, never supported. Might be one worth supporting.
