### ISSUE TITLE
[Bug]: Milvus build from source fail

### ISSUE THREAD

**Issue by bryanwux** [milvus-io/milvus#24605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.8
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): MacOS
- CPU/Memory: x86_64
- GPU: 
- Others: go version: go1.20.4 darwin/amd64 
          cmake version: 3.26.4
```

### Current Behavior

I was trying to build Milvus from source but met following errors:

<img width="1291" alt="image" src="https://github.com/milvus-io/milvus/assets/17968665/4e248cc0-2c14-4574-aec5-abece1acc4f9">

### Steps To Reproduce

```markdown
$ cd milvus/
$ ./scripts/install_deps.sh
$ make
```

**Comment by jiaoew1991** [comment]
related to https://github.com/milvus-io/milvus/issues/24056

**Comment by jiaoew1991** [comment]
@bryanwux you can rebase master and retry https://github.com/milvus-io/milvus/pull/24610
