### ISSUE TITLE
Disk-Io operations during searching 

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#2460]
**Describe the bug**

The following log lines appeared during searching process.

```
[2020-05-29 11:06:12,480][DEBUG][ENGINE][Search][taskexector_th] [search][0] get 1000000 uids from index /var/lib/milvus/db/tables/sift_1m_1024_128_l2/1590721531476109000/1590721535761193000
```
There are several disk-Io operations during one search request. 

**Steps/Code to reproduce behavior**

**Expected behavior**

**Environment details**

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
This log "get xxx uids from index xxxx" doesn't indicate I/O read. It means mapping vector id from faiss compute result(faiss result is offset, to return id, we need pick id one by one by the offset value).
Not a bug
