### ISSUE TITLE
[Bug]: Testcases hang after standalone and etcd pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#24616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230601-93ea9c49
- Deployment mode(standalone or cluster):standalone and cluster
- MQ type(rocksmq, pulsar or kafka): rocksmq and pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/12268675/b98d1db0-bedc-40d2-901a-b2073565dc74)
![image](https://github.com/milvus-io/milvus/assets/12268675/a7b94e72-bc97-4f9d-99bd-b582f7622e77)

### Milvus Log

standalone

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/4636/pipeline
log:
[artifacts-standalone-pod-failure-4636-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/11631678/artifacts-standalone-pod-failure-4636-server-logs.tar.gz)
[artifacts-standalone-pod-failure-4636-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11631679/artifacts-standalone-pod-failure-4636-pytest-logs.tar.gz)

etcd
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/4634/pipeline
log:
[artifacts-etcd-pod-kill-4634-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/11631681/artifacts-etcd-pod-kill-4634-server-logs.tar.gz)
[artifacts-etcd-pod-kill-4634-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11631682/artifacts-etcd-pod-kill-4634-pytest-logs.tar.gz)

**Comment by wayblink** [comment]
@xiaofan-luan @zhuwenxing @yanliang567 
It seems not related to the etcd keepalive fix. 
I found some error log about stats log :

standalone:
2023-06-02 05:59:35 | [2023/06/01 21:59:35.047 +00:00] [ERROR] [funcutil/parallel.go:88] [loadRemoteFunc] [error="failed to read file/stats_log/441884435714547498/441884435714547499/441884435714548218/100/1: NoSuchKey(key=file/stats_log/441884435714547498/441884435714547499/441884435714548218/100/1)"] [idx=0] [stack="github.com/milvus-io/milvus/pkg/util/funcutil.ProcessFuncParallel.func3\n\t/go/src/github.com/milvus-io/milvus/pkg/util/funcutil/parallel.go:88"]
--
  |   | 2023-06-02 05:59:35 | [2023/06/01 21:59:35.047 +00:00] [WARN] [segments/segment_loader.go:379] ["failed to load remote segment"] [traceID=9d93470c50e0e956684989c5b5422fa1] [collectionID=441884435714547498] [segmentIDs="[441884435714548218]"] [error="failed to read file/stats_log/441884435714547498/441884435714547499/441884435714548218/100/1: NoSuchKey(key=file/stats_log/441884435714547498/441884435714547499/441884435714548218/100/1)"]
  |   | 2023-06-02 05:59:35 | [2023/06/01 21:59:35.047 +00:00] [WARN] [delegator/delegator_data.go:331] ["failed to load bloom filter set for segment"] [traceID=9d93470c50e0e956684989c5b5422fa1] [collectionID=441884435714547498] [channel=by-dev-rootcoord-dml_13_441884435714547498v1] [replicaID=441884435767623688] [workID=2] [segments="[441884435714548218]"] [error="failed to read file/stats_log/441884435714547498/441884435714547499/441884435714548218/100/1: NoSuchKey(key=file/stats_log/441884435714547498/441884435714547499/441884435714548218/100/1)"]

etcd:
2023-06-02 05:35:21 | [2023/06/01 21:35:21.859 +00:00] [WARN] [datanode/channel_meta.go:427] ["failed to load bloom filter files"] [segmentID=441884313131494657] [error="failed to read file/stats_log/441884313131494548/441884313131494549/441884313131494657/100/1: NoSuchKey(key=file/stats_log/441884313131494548/441884313131494549/441884313131494657/100/1)"]Show context
-- | --
  |   | 2023-06-02 05:35:21 | [2023/06/01 21:35:21.859 +00:00] [ERROR] [datanode/channel_meta.go:236] ["failed to init bloom filter"] ["segment ID"=441884313131294311] [error="failed to read file/stats_log/441884313131294292/441884313131294293/441884313131294311/100/1: NoSuchKey(key=file/stats_log/441884313131294292/441884313131294293/441884313131294311/100/1)"] [stack="github.com/milvus-io/milvus/internal/datanode.(*ChannelMeta).addSegment\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/channel_meta.go:236\ngithub.com/milvus-io/milvus/internal/datanode.(*dataSyncService).initNodes.func2\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:266\ngithub.com/milvus-io/milvus/pkg/util/conc.(*Pool[...]).Submit.func1\n\t/go/src/github.com/milvus-io/milvus/pkg/util/conc/pool.go:73\ngithub.com/panjf2000/ants/v2.(*goWorker).run.func1\n\t/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.2/worker.go:67"]

**Comment by zhuwenxing** [comment]
This issue reproduced stably

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/4706/pipeline
log:

[artifacts-etcd-pod-kill-4706-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/11648283/artifacts-etcd-pod-kill-4706-server-logs.tar.gz)

[artifacts-etcd-pod-kill-4706-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11648284/artifacts-etcd-pod-kill-4706-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
standalone pod kill

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/4708/pipeline
log:
[artifacts-standalone-pod-failure-4708-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/11648288/artifacts-standalone-pod-failure-4708-server-logs.tar.gz)
[artifacts-standalone-pod-failure-4708-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11648289/artifacts-standalone-pod-failure-4708-pytest-logs.tar.gz)

**Comment by sunby** [comment]
same reason as https://github.com/milvus-io/milvus/issues/24614

**Comment by aoiasd** [comment]
fixed by https://github.com/milvus-io/milvus/pull/24670
