### ISSUE TITLE
[Bug]:  pod restart, search fail

### ISSUE THREAD

**Issue by yesletgo** [milvus-io/milvus#24615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):2.2.8
- MQ type(rocksmq, pulsar or kafka):   kafka 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 84cores/600G
- GPU: 
- Others:
```

### Current Behavior

search fail, pod restart, hang up.

### Milvus Log

https://video-tag-lib-1251808348.cos.ap-beijing.myqcloud.com/milvus_log/bw_etcd_ALL.230601-175320.bak.gz
https://video-tag-lib-1251808348.cos.ap-beijing.myqcloud.com/milvus_log/k8s_logs_06_02_24h.tar.gz

**Comment by jiaoew1991** [comment]
/assign @weiliu1031 
/unassign 

It seems that after one of the query nodes went down, the LB was not able to recover quickly.

**Comment by weiliu1031** [comment]
when pod restart, qc try to load segment which lost during restart, but meet `NoSuchKey` error, so loading will hang, and channel keep unavailable state.

`"All attempts results:\nattempt #1:NoSuchKey(key=file/stats_log/441420634096175374/441420634096175375/441420634096233511/100/441420634096233513)\nattempt #2:NoSuchKey(key=file/stats_log/441420634096175374/441420634096175375/441420634096233511/100/441420634096233602)\nattempt #3:NoSuchKey(key=file/stats_log/441420634096175374/441420634096175375/441420634096233511/100/441420634096233723)\nattempt #4:NoSuchKey(key=file/stats_log/441420634096175374/441420634096175375/441420634096233511/100/441420634096233814)\nattempt #5:NoSuchKey(key=file/stats_log/441420634096175374/441420634096175375/441420634096233511/100/441420634096233899)\nattempt #6:NoSuchKey(key=file/stats_log/441420634096175374/441420634096175375/441420634096233511/100/441420634096233984)\nattempt #7:NoSuchKey(key=file/stats_log/441420634096175374/441420634096175375/441420634096233511/100/441420634096234229)\nattempt #8:NoSuchKey(key=file/stats_log/441420634096175374/441420634096175375/441420634096233511/100/441420634096234314)\nattempt #9:NoSuchKey(key=file/stats_log/441420634096175374/441420634096175375/441420634096233511/100/441420634096234404)\nattempt #10:NoSuchKey(key=file/stats_log/441420634096175374/441420634096175375/441420634096233511/100/441420634096234491)\nattempt #11:NoSuchKey(key=file/stats_log/441420634096175374/441420634096175375/441420634096233511/100/441420634096234554)\n"]`

**Comment by yesletgo** [comment]
so,What causes meet NoSuchKey @weiliu1031

**Comment by weiliu1031** [comment]
> so,What causes meet NoSuchKey @weiliu1031

did you deploy multi milvus cluster with same bucket on minio?

**Comment by weiliu1031** [comment]
i saw you have another milvus cluster running at same time, from issue #24673, and if you doesn't change the default config in milvus.yaml, and two milvus cluster may share same bucket in minio, and could delete each other's data by mistake.
