### ISSUE TITLE
[Bug]: pkg-config is needed for x86 mac as well

### ISSUE THREAD

**Issue by bryanwux** [milvus-io/milvus#24626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): MacOS
- CPU/Memory: x86-64
- GPU: 
- Others:
```

### Current Behavior

Currently, pkg-config is only downloaded for arm64 Mac when building Milvus from source. However, it is actually needed when using an intel core Mac. I suggest add `brew install pkg-config` in `install_deps.sh` as well.

**Comment by xiaofan-luan** [comment]
@bryanwux 
could you have a fixed pr on it?

**Comment by bryanwux** [comment]
@xiaofan-luan  Will do soon.

**Comment by jiaoew1991** [comment]
#24627 fixed it
