### ISSUE TITLE
[Feature]: milvus support fast get collection or db level statistics(like rows and avg_row_length etc...)

### ISSUE THREAD

**Issue by yelusion2** [milvus-io/milvus#24633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Now milvus has  getCollectionStatistics api, but its accurate value is obtained, it is affected by the flush operation and will be very performance consuming.

Some time we want fast get collection or db level statistics, and not very consumption performance, and all we need is a reference value. The advantage of doing this is that：
1.Quickly obtain the actual effective data size of the collection or db.
If we get this data from milvus storage directly, time consuming and slowly.

2.Quickly get the rows and avg_row_length  we can quickly assess water levels for scheduling resource.

### Describe the solution you'd like.

 fast get collection or db level statistics(like rows and avg_row_length etc...)

### Describe an alternate solution.

insert/delete/upsert async write msg to milvus meta.
then fast get collection or db level statistics througth meta

**Comment by xiaofan-luan** [comment]
so you are saying we need a param to skip flush on getCollectionStatistics?

what is required stats?

**Comment by yelusion2** [comment]
some milvus meta in etcd, and we can get the data fast.like rows, insert
log/delta/stat log usage etc...

**Comment by bigsheeper** [comment]
Conformed with @yelusion2 , use GetMetrics interface instead.
