### ISSUE TITLE
[Enhancement]: Auto_id varchar

### ISSUE THREAD

**Issue by filip-halt** [milvus-io/milvus#24641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Can we support a varchar primary key that is auto_id? We could take the int based auto_id and cast it to a varchar.

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What would you like to be added?
> Can we support a varchar primary key that is auto_id? We could take the int based auto_id and cast it to a varchar.
> 
> ### Why is this needed?
> _No response_
> 
> ### Anything else?
> _No response_

Add a random varchar based on snowflake algorithm? or just convert a long into varchar?

**Comment by shunjiezhao** [comment]
Hello, should i  just convert a int64  into varchar?

**Comment by xiaofan-luan** [comment]
/assign @yanliang567 
has been merged. Could you help on test it

**Comment by smellthemoon** [comment]
related with https://github.com/milvus-io/pymilvus/pull/1583
