### ISSUE TITLE
[Enhancement]:  optimazation  retrieve by pk index 

### ISSUE THREAD

**Issue by zhagnlu** [milvus-io/milvus#24659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

for these query retrieve by pk index, such as pk in [1, 3, 4 ....]  and search with vector output field,  has a bad performance because bad design for search id interface. add a cache to these interface and improve performance a lot.

**Comment by xiaofan-luan** [comment]
is there any performance evaluation?
