### ISSUE TITLE
[Bug]: milvus was deployed on my server,i create 2 collection and the collection work well, oneday my server restart,then the 2 collection can't index and search anymore

### ISSUE THREAD

**Issue by pagyyuan** [milvus-io/milvus#24654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.0.2
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 
- GPU: None
- Others:
```

### Current Behavior

milvus was deployed on my server,i create 2 collection and the collection work well, oneday my server restart,then the 2 collection can't index and search anymore

**Comment by yanliang567** [comment]
@pagyyuan we need logs to investigate issues, could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assgin @pagyyuan 
/unassign

**Comment by jiaoew1991** [comment]
How did you start etcd and minio? If you started them with docker-compose, you need to mount their storage paths, otherwise the data will be lost after restarting Docker.
