### ISSUE TITLE
[Enhancement]:  support element in json array function

### ISSUE THREAD

**Issue by zhagnlu** [milvus-io/milvus#24677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

support retrieve one element in  json array just like array contains element,

**Comment by xiaocai2333** [comment]
json: {"x": [1,2,3,4]}
expr: `1 in json["x"]`

**Comment by xiaofan-luan** [comment]
seems to be a reasonable feature

**Comment by xiaofan-luan** [comment]
we decide to use array_contains instead of IN
