### ISSUE TITLE
[Enhancement]: Increase in single digit level and concurrent search query time

### ISSUE THREAD

**Issue by yesletgo** [milvus-io/milvus#24673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Under 100 levels of concurrency, the search performance is within 1 second

### Why is this needed?

Online cluster environment 588.45 GiB 84Cores, has 80 million data, 1024 dimensions.
milvus: 2.2.8/2.2.5

my-release-etcd-0                               1/1     Running     0          27d
my-release-etcd-1                               1/1     Running     0          27d
my-release-etcd-2                               1/1     Running     0          27d
my-release-milvus-attu-6d8c857f7c-j5wkq         1/1     Running     0          27d
my-release-milvus-datacoord-5db9fc6c69-8f8bn    1/1     Running     0          27d
my-release-milvus-datanode-59b68dd9b-5dzrl      1/1     Running     0          27d
my-release-milvus-indexcoord-86f74668c8-k8g9k   1/1     Running     0          27d
my-release-milvus-indexnode-5b994b6479-2s42l    1/1     Running     0          27d
my-release-milvus-indexnode-5b994b6479-cv8s8    1/1     Running     0          27d
my-release-milvus-indexnode-5b994b6479-qxt5p    1/1     Running     0          27d
my-release-milvus-indexnode-5b994b6479-r6fqj    1/1     Running     0          27d
my-release-milvus-proxy-64858765b4-g885w        1/1     Running     0          27d
my-release-milvus-querycoord-84bcbbbb6f-xfm7x   1/1     Running     0          27d
my-release-milvus-querynode-78df587f4b-25ctc    1/1     Running     0          27d
my-release-milvus-querynode-78df587f4b-2w52x    1/1     Running     0          27d
my-release-milvus-querynode-78df587f4b-55h2p    1/1     Running     0          27d
my-release-milvus-querynode-78df587f4b-5g2fc    1/1     Running     0          27d
my-release-milvus-querynode-78df587f4b-6q69s    1/1     Running     0          27d
my-release-milvus-querynode-78df587f4b-725dt    1/1     Running     0          27d
my-release-milvus-querynode-78df587f4b-9gn8p    1/1     Running     0          27d
my-release-milvus-querynode-78df587f4b-lxg69    1/1     Running     0          27d
my-release-milvus-querynode-78df587f4b-mmzn7    1/1     Running     0          27d
my-release-milvus-querynode-78df587f4b-nw6bf    1/1     Running     0          27d
my-release-milvus-querynode-78df587f4b-tdpn8    1/1     Running     0          27d
my-release-milvus-querynode-78df587f4b-vhjqb    1/1     Running     0          27d
my-release-milvus-rootcoord-758f489fb9-hmd4h    1/1     Running     0          27d
my-release-minio-0                              1/1     Running     0          27d
my-release-minio-1                              1/1     Running     0          27d
my-release-minio-2                              1/1     Running     0          27d
my-release-minio-3                              1/1     Running     0          27d
my-release-pulsar-bookie-0                      1/1     Running     0          27d
my-release-pulsar-bookie-1                      1/1     Running     0          27d
my-release-pulsar-bookie-2                      1/1     Running     0          27d
my-release-pulsar-bookie-init-zjfbz             0/1     Completed   0          27d
my-release-pulsar-broker-0                      1/1     Running     0          27d
my-release-pulsar-proxy-0                       1/1     Running     0          27d
my-release-pulsar-pulsar-init-mxsfz             0/1     Completed   0          27d
my-release-pulsar-recovery-0                    1/1     Running     0          27d
my-release-pulsar-zookeeper-0                   1/1     Running     0          27d
my-release-pulsar-zookeeper-1                   1/1     Running     0          27d
my-release-pulsar-zookeeper-2                   1/1     Running     0          27d
nfs-client-provisioner-7f49bb7897-jkx7k         1/1     Running     1          227d

**Increase in single digit level and concurrent search query time.
One search of 700ms, with 5 concurrent searches taking over 2s.
If there are 10 concurrent instances, it will take more than 4 seconds.
If there are 50 concurrent instances, it will take more than 20 seconds.
........**

### Anything else?

https://video-tag-lib-1251808348.cos.ap-beijing.myqcloud.com/milvus_log/logs_new_milvus_202306066h.tar.gz

**Comment by xiaofan-luan** [comment]
try to increase segment size or change search params might help.
How is the cpu utilization? is it fully utilized? and What is the search params?

**Comment by xiaofan-luan** [comment]
1. Try HNSW index, should be much faster than faiss
2. Change segment.maxSize = 2048
3. reduce topk might help/or you have to add more physical resources

**Comment by yesletgo** [comment]
> 1. Try HNSW index, should be much faster than faiss
> 2. Change segment.maxSize = 2048
> 3. reduce topk might help/or you have to add more physical resources

Is it normal for single digit concurrency to have such a significant impact on search performance ?

**Comment by xiaofan-luan** [comment]
> 

Using HNSW should be at least 10 times faster than FAISS Index. and enlarge segment size should bring 2-3 times performance gain. But you are right, vector search requires hardware resouces

**Comment by xiaofan-luan** [comment]
> > try to increase segment size or change search params might help. How is the cpu utilization? is it fully utilized? and What is the search params?
> 
> When conducting concurrent searches, the CPU of cluster will sharply increase to 90%.
> 
> collection nlist is 10000.
> 
> dataCoord: address: my-release-milvus-datacoord port: 13333
> 
> ```
>   channel:
>     watchTimeoutInterval: 120
> 
>   grpc:
>     serverMaxRecvSize: 2147483647  # math.MaxInt32
>     serverMaxSendSize: 2147483647  # math.MaxInt32
>     clientMaxRecvSize: 104857600   # 100 MB, 100 * 1024 * 1024
>     clientMaxSendSize: 104857600   # 100 MB, 100 * 1024 * 1024
>   enableCompaction: true
>   enableGarbageCollection: true
> 
>   segment:
>     maxSize: "512"  # Maximum size of a segment in MB
>     sealProportion: 0.75  # It's the minimum proportion for a segment which can be sealed
>     assignmentExpiration: 2000  # ms
> 
>   compaction:
>     enableAutoCompaction: true
> ```
> 
> SearchParam{collectionName='new_vtl_vit_zh_cluster', partitionNames='[]', metricType=IP, target vectors count=1, vectorFieldName='feature', topK=1000, nq=1, expr='', params='{"nprobe":200}', consistencyLevel='EVENTUALLY', ignoreGrowing='true'}



> > > 
> > 
> > 
> > Using HNSW should be at least 10 times faster than FAISS Index. and enlarge segment size should bring 2-3 times performance gain. But you are right, vector search requires hardware resouces
> 
> SearchParam{collectionName='new_vtl_vit_en_cluster', partitionNames='[]', metricType=IP, target vectors count=1, vectorFieldName='feature', topK=1000, nq=1, expr='', params='{"ef":1000}', consistencyLevel='BOUNDED', ignoreGrowing='false'}
> 
> Online cluster environment 60 cores/ 370G, has 30 million data, 1024 dimensions. milvus: 2.2.10
> 
> Increase in single digit level and concurrent search query time. One search of 800ms, with 5 concurrent searches taking over 1.6s. If there are 10 concurrent instances, it will take more than 3.2 seconds. If there are 50 concurrent instances, it will take more than 12 seconds.
> 
> What's even more serious is that some searches have never returned.
> 
> log: https://video-tag-lib-1251808348.cos.ap-beijing.myqcloud.com/milvus_log/logs_new_milvus_2.2.10_202306266h.tar.gz

If your cpu is all used. There is nothing we can do to improve performance.
The only thing you can do is try better index or increase hardware resource. 

HNSW or IVFSQ8 is better at throughput and that's you should be working on

**Comment by yesletgo** [comment]
> > > try to increase segment size or change search params might help. How is the cpu utilization? is it fully utilized? and What is the search params?
> > 
> > 
> > When conducting concurrent searches, the CPU of cluster will sharply increase to 90%.
> > collection nlist is 10000.
> > dataCoord: address: my-release-milvus-datacoord port: 13333
> > ```
> >   channel:
> >     watchTimeoutInterval: 120
> > 
> >   grpc:
> >     serverMaxRecvSize: 2147483647  # math.MaxInt32
> >     serverMaxSendSize: 2147483647  # math.MaxInt32
> >     clientMaxRecvSize: 104857600   # 100 MB, 100 * 1024 * 1024
> >     clientMaxSendSize: 104857600   # 100 MB, 100 * 1024 * 1024
> >   enableCompaction: true
> >   enableGarbageCollection: true
> > 
> >   segment:
> >     maxSize: "512"  # Maximum size of a segment in MB
> >     sealProportion: 0.75  # It's the minimum proportion for a segment which can be sealed
> >     assignmentExpiration: 2000  # ms
> > 
> >   compaction:
> >     enableAutoCompaction: true
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > SearchParam{collectionName='new_vtl_vit_zh_cluster', partitionNames='[]', metricType=IP, target vectors count=1, vectorFieldName='feature', topK=1000, nq=1, expr='', params='{"nprobe":200}', consistencyLevel='EVENTUALLY', ignoreGrowing='true'}
> 
> > > > 
> > > 
> > > 
> > > Using HNSW should be at least 10 times faster than FAISS Index. and enlarge segment size should bring 2-3 times performance gain. But you are right, vector search requires hardware resouces
> > 
> > 
> > SearchParam{collectionName='new_vtl_vit_en_cluster', partitionNames='[]', metricType=IP, target vectors count=1, vectorFieldName='feature', topK=1000, nq=1, expr='', params='{"ef":1000}', consistencyLevel='BOUNDED', ignoreGrowing='false'}
> > Online cluster environment 60 cores/ 370G, has 30 million data, 1024 dimensions. milvus: 2.2.10
> > Increase in single digit level and concurrent search query time. One search of 800ms, with 5 concurrent searches taking over 1.6s. If there are 10 concurrent instances, it will take more than 3.2 seconds. If there are 50 concurrent instances, it will take more than 12 seconds.
> > What's even more serious is that some searches have never returned.
> > log: https://video-tag-lib-1251808348.cos.ap-beijing.myqcloud.com/milvus_log/logs_new_milvus_2.2.10_202306266h.tar.gz
> 
> If your cpu is all used. There is nothing we can do to improve performance. The only thing you can do is try better index or increase hardware resource.
> 
> HNSW or IVFSQ8 is better at throughput and that's you should be working on

Data reduced from 100 million to 30 million CPUs, using only 40%.
