### ISSUE TITLE
[Enhancement]: MetaKv code refactory

### ISSUE THREAD

**Issue by yiwangdr** [milvus-io/milvus#24694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

meta data deserves a neat interface. Implementation details (e.g. etcd) should sit behind the interface.

1. We have MetaKv as the metadata r/w interface. It's preferred over specific kv implementations (e.g. EtcdKV).
2. We have many refactories over time, which left us with unused interfaces. They should be cleaned up.

**Comment by jiaoew1991** [comment]
We are now using `mockery` to automatically generate mock code, so we can also delete the internal/kv/mocks package.

RocksdbKV seems to no longer be in use, so I think it can also be deleted.

**Comment by congqixia** [comment]
Also I recommend to add ctx parameter for all `KV` interface

**Comment by yiwangdr** [comment]
> We are now using `mockery` to automatically generate mock code, so we can also delete the internal/kv/mocks package.
> 
> RocksdbKV seems to no longer be in use, so I think it can also be deleted.

1. It looks like [some tests are still using them](https://github.com/search?q=repo%3Amilvus-io%2Fmilvus+%2Fmocks.New.*KV%2F&type=code). Is mockery supposed to replace KV mock as well?
2. rocksmq [still needs it](https://github.com/milvus-io/milvus/blob/41af0a98fa24005062fedf76d9978482167f39a2/internal/mq/mqimpl/rocksmq/server/rocksmq_impl.go#L31). We probably need to wait until rocksmq is deprecated, which doesn't have a timeline yet.

**Comment by yiwangdr** [comment]
> Also I recommend to add ctx parameter for all `KV` interface

ooc, how will we use ctx in `KV`?

**Comment by xiaofan-luan** [comment]
> > Also I recommend to add ctx parameter for all `KV` interface
> 
> ooc, how will we use ctx in `KV`?

For time-out？

**Comment by xiaofan-luan** [comment]
> > We are now using `mockery` to automatically generate mock code, so we can also delete the internal/kv/mocks package.
> > RocksdbKV seems to no longer be in use, so I think it can also be deleted.
> 
> 1. It looks like [some tests are still using them](https://github.com/search?q=repo%3Amilvus-io%2Fmilvus+%2Fmocks.New.*KV%2F&type=code). Is mockery supposed to replace KV mock as well?
> 2. rocksmq [still needs it](https://github.com/milvus-io/milvus/blob/41af0a98fa24005062fedf76d9978482167f39a2/internal/mq/mqimpl/rocksmq/server/rocksmq_impl.go#L31). We probably need to wait until rocksmq is deprecated, which doesn't have a timeline yet.

I don't think rocksmq can be removed in a short run unless we have a way to migrate from rocksmq to natsmq

**Comment by yiwangdr** [comment]
> > > We are now using `mockery` to automatically generate mock code, so we can also delete the internal/kv/mocks package.
> > > RocksdbKV seems to no longer be in use, so I think it can also be deleted.
> > 
> > 
> > 
> > 1. It looks like [some tests are still using them](https://github.com/search?q=repo%3Amilvus-io%2Fmilvus+%2Fmocks.New.*KV%2F&type=code). Is mockery supposed to replace KV mock as well?
> > 2. rocksmq [still needs it](https://github.com/milvus-io/milvus/blob/41af0a98fa24005062fedf76d9978482167f39a2/internal/mq/mqimpl/rocksmq/server/rocksmq_impl.go#L31). We probably need to wait until rocksmq is deprecated, which doesn't have a timeline yet.
> 
> I don't think rocksmq can be removed in a short run unless we have a way to migrate from rocksmq to natsmq

Agreed. Let's keep it for now.

**Comment by jiaoew1991** [comment]
> RocksdbKV

1. Our goal is to replace all mocks with mockery.
2. If we couldn't find rocksmq before and still use rockskv, then we need to keep it for now.

**Comment by yiwangdr** [comment]
> > RocksdbKV
> 
> 1. Our goal is to replace all mocks with mockery.
> 2. If we couldn't find rocksmq before and still use rockskv, then we need to keep it for now.

Thanks for the clarification. The goal makes sense to me. Is there a tracking issue? 
Right now, it looks like we have a combination of mockery + legacy mock, which look like a tech debt.

**Comment by jiaoew1991** [comment]
> > > RocksdbKV
> > 
> > 
> > 
> > 1. Our goal is to replace all mocks with mockery.
> > 2. If we couldn't find rocksmq before and still use rockskv, then we need to keep it for now.
> 
> Thanks for the clarification. The goal makes sense to me. Is there a tracking issue? Right now, it looks like we have a combination of mockery + legacy mock, which look like a tech debt.

Just opened an issue. 😄 https://github.com/milvus-io/milvus/issues/24845
