### ISSUE TITLE
[Bug]: autouseradd: running as root is not permitted, trying to enable S3

### ISSUE THREAD

**Issue by frankbecker** [milvus-io/milvus#24693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0
- Deployment mode(standalone or cluster): standalone built from repo with docker-compose
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I am trying to spin up milvus with index storage in S3, I have been following these steps [here](https://milvus.io/docs/v2.0.x/deploy_s3.md#Set-up-with-Docker-Compose), and I keep getting this error in the builder docker container: `autouseradd: running as root is not permitted`

### Expected Behavior

I expect to have milvus running locally and storing it's index in my S3 bucket.

**Comment by locustbaby** [comment]
@frankbecker hi, may I know where your Milvus was deployed?
Milvus' container now need to run as root user, we are working on changing it
