### ISSUE TITLE
[Bug]: Search 5 failed, reason deadline exceed err %!w(<nil>)

### ISSUE THREAD

**Issue by deer-code** [milvus-io/milvus#24740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.2
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 8/64G
- GPU: 
- Others:
```

### Current Behavior

failed to do search

### Milvus Log

------------【queryNode】------------
[querynode/shard_cluster.go:841] ["failed to do search"] [req="req:<base:<msg_type:Search msgID:442026263814466748 timestamp:442026598652182555 sourceID:12 > reqID:12 collectionID:437428833499742209 partitionIDs:440656095518654465 partitionIDs:440678746555940865 partitionIDs:440701396177911809 partitionIDs:440724042706321409 partitionIDs:440746692432625665 partitionIDs:440769342159454209 partitionIDs:440791994205995009 partitionIDs:440814639516221441 partitionIDs:440837290421649409 partitionIDs:440859938208088065 partitionIDs:440882592234078209 partitionIDs:440905239588241409 partitionIDs:440927885920043009 partitionIDs:440950539487019009 partitionIDs:440973187733258241 partitionIDs:440995837065560065 partitionIDs:441018482807799809 partitionIDs:441041143386865665 partitionIDs:441063786494558209 partitionIDs:441086430532599809 partitionIDs:441109087900663809 partitionIDs:441131729199038465 partitionIDs:441154378624925697 partitionIDs:441177030041796609 partitionIDs:441199678745739265 partitionIDs:441222334409867265 partitionIDs:441244975276228609 partitionIDs:441267629078872065 partitionIDs:441290274074001410 partitionIDs:441312926749425665 partitionIDs:441335578009796609 partitionIDs:441358235600683009 partitionIDs:441380878904459265 partitionIDs:441403526481707009 partitionIDs:441426174255038465 partitionIDs:441448819132203009 partitionIDs:441471474390007809 partitionIDs:441494118309822465 partitionIDs:441516776150007809 partitionIDs:441539432849342465 partitionIDs:441562070727262209 partitionIDs:441584718160068609 partitionIDs:441607382920593409 partitionIDs:441630014021828609 partitionIDs:441652663407345665 partitionIDs:441675315820888065 partitionIDs:441697976479121409 partitionIDs:441720623308734465 partitionIDs:441743272104951809 partitionIDs:441765928005009409 partitionIDs:441788559997272065 partitionIDs:441811207312113665 partitionIDs:441833876267204609 partitionIDs:441856509871915009 partitionIDs:441879158549643265 partitionIDs
--
  | 56:\\356\\335;\\275\\250\\233=\\275\\n\\335^\\274;'\\322\\272\\267\\235\\236=6\\225\\247:\\310\\204\\273<E\\340\\303<_\\247e\\274Ma\\264\\274%}\\355\\275\\362\\004\\203\\275l\\0221\\275\\265ql\\275\\325\\201}<\\212\\303-=\\261\\001j\\275JP\\306\\275\\027\\344\\252\\273\\003\\354\\237=\\271\\374\\262\\275\\353\\037\\223\\275\\001\\361\\n\\275\\177\\350\\023<\\345w\\017\\275\\373-\\303=*@5=:\\005*=\\251\\200y\\273b\\323\\027\\275\\357\\266(\\275^HQ\\275\\344\\203\\336=Efk=<\\206f;c\\254\\204\\273L\\016o\\275\\353\\037\\023=\\312\\327\\000\\274\\350K\\021\\275\\026\\205\\026\\275\\242RN<\\200\\204\\224\\273/*\\220=\\335\\002n\\275\\352R\\365\\274\\243+\\273\\274\\013\\266K=\\325\\201}=K)3\\274\\335\\002\\356\\274;\\033\\203\\273w\\244\\217\\273\\350\\016%=B\\206\\032=\\352F&\\275\\220\\030\\354\\274\\21730\\2751\\350\\270\\275p\\202\\263\\274H\\222\\235=\\327\\255\\257\\274S\\347\\217=\\343\\252\\361\\274\\312\\327\\000<6\\322\\223<\\371o\\032=\\2410\\246\\275\\367\\372,<:\\310\\275<K\\257\\332\\272^\\377\\025=\\356W\\224\\2755\\371\\246<\\264\\230\\177:\\245\\240(\\274\\001\\375Y;\\352\\203\\022\\275\\033\\270,\\275\|\\2329\\275\\244~\\200\\274\\0035\\333<+%\\361=\\3712\\256\\275\\034\\235\\350\\274\\005\\3474\\275y\\350\\337\\273\\340\\312 \\2740\\225s<\\310\\n\\343\\275\\001\\264\\036=\\306\\306\\222\\273\" dsl_type:BoolExprV1 serialized_expr_plan:\"\\032\\003hij\\no\\020k\\032P\\032N\\010\\001\\022.\\032,\\010\\001\\022\\026\\n\\024\\n\\004\\010e\\020\\025\\022\\014\\\"\\n9929118198\\032\\020\\n\\016\\n\\004\\010g\\020\\005\\022\\002\\020\\000\\022\\002\\020\\002\\032\\032*\\030\\n\\004\\010i\\020\\025\\020\\006\\032\\016\\\"\\014841005045571\\\"\\025\\010\\024\\032\\002IP\\\"\\002{}(\\377\\377\\377\\377\\377\\377\\377\\377\\377\\001*\\002$0\" output_fields_id:104 output_fields_id:105 output_fields_id:106 travel_timestamp:18446744073709551615 guarantee_timestamp:442026597341462555 timeout_timestamp:442026601306914816 nq:1 topk:20 metricType:\"IP\" > dml_channel:\"by-dev-rootcoord-dml_8_437428833499742209v0\" scop
Thu, Jun 8 2023 12:14:27 pm | [2023/06/08 04:14:27.314 +00:00] [WARN] [querynode/impl.go:508] ["search cluster failed"] [msgID=442026263814466748] [collectionID=437428833499742209] [error="Search 5 failed, reason deadline exceed err %!w(<nil>)"]
Thu, Jun 8 2023 12:14:50 pm | [2023/06/08 04:14:50.750 +00:00] [WARN] [flowgraph/node.go:83] ["some node(s) haven't received input"] [list="[nodeCtxTtChecker-stNode-by-dev-rootcoord-dml_8_437428833499742209v0,nodeCtxTtChecker-dmInputNode-query-437428833499742209-by-dev-rootcoord-delta_8_437428833499742209v0,nodeCtxTtChecker-fdmNode-by-dev-rootcoord-dml_8_437428833499742209v0,nodeCtxTtChecker-dNode-by-dev-rootcoord-delta_8_437428833499742209v0,nodeCtxTtChecker-fdNode-by-dev-rootcoord-delta_8_437428833499742209v0,nodeCtxTtChecker-stNode-by-dev-rootcoord-delta_8_437428833499742209v0,nodeCtxTtChecker-dmInputNode-query-437428833499742209-by-dev-rootcoord-dml_8_437428833499742209v0,nodeCtxTtChecker-iNode-by-dev-rootcoord-dml_8_437428833499742209v0]"] ["duration "=2m0s]
Thu, Jun 8 2023 12:15:18 pm | [2023/06/08 04:15:18.615 +00:00] [ERROR] [querynode/shard_cluster.go:841] ["failed to do search"] [req="req:<base:<msg_type:Search msgID:442026263814470513 timestamp:442026612125073413 sourceID:12 > reqID:12 collectionID:437428833499742209 partitionIDs:440656095518654465 partitionIDs:440678746555940865 partitionIDs:440701396177911809 partitionIDs:440724042706321409 partitionIDs:440746692432625665 partitionIDs:440769342159454209 partitionIDs:440791994205995009 partitionIDs:440814639516221441 partitionIDs:440837290421649409 partitionIDs:440859938208088065 partitionIDs:440882592234078209 partitionIDs:440905239588241409 partitionIDs:440927885920043009 partitionIDs:440950539487019009 partitionIDs:440973187733258241 partitionIDs:440995837065560065 partitionIDs:441018482807799809 partitionIDs:441041143386865665 partitionIDs:441063786494558209 partitionIDs:441086430532599809 partitionIDs:441109087900663809 partitionIDs:441131729199038465 partitionIDs:441154378624925697 partitionIDs:441177030041796609 partitionIDs:441199678745739265 partitionIDs:441222334409867265 partitionIDs:441244975276228609 partitionIDs:441267629078872065 partitionIDs:441290274074001410 partitionIDs:441312926749425665 partitionIDs:441335578009796609 partitionIDs:441358235600683009 partitionIDs:441380878904459265 partitionIDs:441403526481707009 partitionIDs:441426174255038465 partitionIDs:441448819132203009 partitionIDs:441471474390007809 partitionIDs:441494118309822465 partitionIDs:441516776150007809 partitionIDs:441539432849342465 partitionIDs:441562070727262209 partitionIDs:441584718160068609 partitionIDs:441607382920593409 partitionIDs:441630014021828609 partitionIDs:441652663407345665 partitionIDs:441675315820888065 partitionIDs:441697976479121409 partitionIDs:441720623308734465 partitionIDs:441743272104951809 partitionIDs:441765928005009409 partitionIDs:441788559997272065 partitionIDs:441811207312113665 partitionIDs:441833876267204609 partitionIDs:441856509871915009 partitionIDs:441879158549643265 partitionIDs
  | +\\014\\275\\3461\\226\\275\\351`o=@+`<\\355s\\343<\\352\\342\\017\\275E\\022\\034\\275$z{<\\177W\\340\\2745N5=\\356\\277\\301;\\376G\\235;\\322Jh\\275Pg\\335<\\263.\\037<\\227mg\\273\\034\\334\|\\275\\376\\013\\222<\\237\\337-\\274\\273\\246.\\275\\341\\206e\\274\\244z\\213<\\016\\\"\\240=\\026^$<\\001\\207I=\\001\\377\\337\\274\\336G9=M8\\004\\273\\313\\010\\033\\275\\317\\271\\224<\\327}\\202=\\021\\303\\306;\\323j\\016\\274t\\334\\257\\273Y;\\036=`w\\\"=\\316GG\\275\\207A=<\\267\\3654\\275A;3\\275\\2724\\341\\273\\313\\010\\233<\\031%:<-\\354A:\\306\\251H\\275\\260\\311\\203\\275\\210\\005\\262<T>F=\\276G\\325\\274\\277\\337\\221<\\247\\365\\302\\272Ld\\274;\\267\\005\\210<!\\207-\\275\\353D\\n=\\351\\234z\\275\\346\\251\\254<\\257\\317L\\274\\365M\\355\\275\\236\\203\\374<\\242Ze=P+R\\274\\277\\243\\206\\275\\224>\\016=\\r\\374\\260=\\210g,=.\\\"\\004<\\331`}\\274d\\306\\241\\274\\355s\\343\\273\\243.-:\\306\\231\\365=9\\2354\\275\\362\\036\\224=]t\\001=\\355\\353y\\275\\026\\346\\r\\275\\0225\\224=W}r\\274Et\\226\\274\\031\\255\\243=Y\\303\\007<\\232\\370q<\\375\\257`=A;3\\274\\276\\013J=\\316GG=)\\017\\220\\275hA\\331=\\277\\365\\255={\\220J=\\273\\314\\235=\\034\\240\\361;\" dsl_type:BoolExprV1 serialized_expr_plan:\"\\032\\003hij\\no\\020k\\032P\\032N\\010\\001\\022.\\032,\\010\\001\\022\\026\\n\\024\\n\\004\\010e\\020\\025\\022\\014\\\"\\n9929118198\\032\\020\\n\\016\\n\\004\\010g\\020\\005\\022\\002\\020\\000\\022\\002\\020\\002\\032\\032*\\030\\n\\004\\010i\\020\\025\\020\\006\\032\\016\\\"\\014001013141211\\\"\\025\\010\\024\\032\\002IP\\\"\\002{}(\\377\\377\\377\\377\\377\\377\\377\\377\\377\\001*\\002$0\" output_fields_id:104 output_fields_id:105 output_fields_id:106 travel_timestamp:18446744073709551615 guarantee_timestamp:442026610814353413 timeout_timestamp:442026614774300672 nq:1 topk:20 metricType:\"IP\" > dml_channel:\"by-dev-rootcoord-dml_8_437428833499742209v0\" scope:All "] [error="Search 5 failed, reason deadline exceed err %!w(<nil>)"] [stack="github.com/milvus-io/milvus/internal/querynod
Thu, Jun 8 2023 12:15:18 pm | [2023/06/08 04:15:18.616 +00:00] [WARN] [querynode/impl.go:508] ["search cluster failed"] [msgID=442026263814470513] [collectionID=437428833499742209] [error="Search 5 failed, reason deadline exceed err %!w(<nil>)"]
Thu, Jun 8 2023 12:15:34 pm | [2023/06/08 04:15:34.516 +00:00] [

------------【datanode】------------

[2023/06/08 04:25:06.279 +00:00] [WARN] [flowgraph/node.go:83] ["some node(s) haven't received input"] [list="[nodeCtxTtChecker-ibNode-by-dev-rootcoord-dml_8_437428833499742209v0,nodeCtxTtChecker-dmInputNode-data-437428833499742209-by-dev-rootcoord-dml_8_437428833499742209v0,nodeCtxTtChecker-ddNode-437428833499742209-by-dev-rootcoord-dml_8_437428833499742209v0,nodeCtxTtChecker-deleteNode-by-dev-rootcoord-dml_8_437428833499742209v0]"] ["duration "=2m0s]
--
Thu, Jun 8 2023 12:27:06 pm | [2023/06/08 04:27:06.280 +00:00] [WARN] [flowgraph/node.go:83] ["some node(s) haven't received input"] [list="[nodeCtxTtChecker-ibNode-by-dev-rootcoord-dml_8_437428833499742209v0,nodeCtxTtChecker-dmInputNode-data-437428833499742209-by-dev-rootcoord-dml_8_437428833499742209v0,nodeCtxTtChecker-ddNode-437428833499742209-by-dev-rootcoord-dml_8_437428833499742209v0,nodeCtxTtChecker-deleteNode-by-dev-rootcoord-dml_8_437428833499742209v0]"] ["duration "=2m0s]

**Comment by yanliang567** [comment]
@deer-code milvus 2.1.2 is a quite old release, could you please retry on latest v2.2.9?
/assign @deer-code

**Comment by deer-code** [comment]
How to export the data of milvus

**Comment by Cheung7788** [comment]
Can you export all the logs, we need more information about querynode pod & datanode code. 
https://github.com/milvus-io/milvus/tree/master/deployments/export-log
