### ISSUE TITLE
[Bug]: A large amount of memory left in the querynode node will not be released after release

### ISSUE THREAD

**Issue by baijinge0310** [milvus-io/milvus#24753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.8
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.2.8
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 48/376
- GPU: 
- Others:
```

### Current Behavior

In order to store a large amount of data under limited resources, our business uses to manually release the collection of N days ago at a fixed time every day. When querying, it is only allowed to search for collection within N days. It will be created in the early hours of every day with the suffix of year, month and day as the table name. (because partition does not support release and load partial partition at present, we can only use this method.)

Therefore, we need to test whether the memory will be completely freed after the release, because if there is some space left in each release, the cumulative memory overflow will be a problem sooner or later. I tested the use of diskann index and sq8 index, both 1kw rows, 512-dimensional data.

1. Let's start with the sq8 index, because the problem here is bigger:

1.1 first of all, the following picture is a screenshot of the resource consumption of the milvus cluster before I inserted the data. You can see that the initial value of querynode is 1141Mi.
<img width="621" alt="1 初始状态" src="https://github.com/milvus-io/milvus/assets/74445362/1823f99d-9a2d-4ea4-ae43-b9ac9fc1feaa">
1.2 it took me a long time to insert the 1kw data. This is a screenshot of the resource occupancy after the insertion and load. You can see that the memory footprint of querynode is 8356Mi.
<img width="545" alt="2 load后插入1kw条数据后" src="https://github.com/milvus-io/milvus/assets/74445362/c306701d-7484-400f-b713-f45845ad1e19">
1.3 Then I'm going to test whether there is residual memory, so release took this table. This is a screenshot of the resource occupancy after release, when the cpu usage returned to normal. At this time, the memory footage of querynode is 5812Mi, that is, 5812-1141=4671Mi of memory has not been freed.
<img width="584" alt="3 release" src="https://github.com/milvus-io/milvus/assets/74445362/8cb0af08-2153-4dbe-b664-01718a069381">
1.4 Then I load this table again. At this time, the memory footprint of querynode is 8969Mi, which is normal.
<img width="633" alt="4 又load" src="https://github.com/milvus-io/milvus/assets/74445362/00f6d77a-d28f-42d7-9e81-441175cbf4aa">
1.5 Then I release this table, which is even more exaggerated this time. At this time, the memory occupation of querynode is 7235Mi. This time, only 1.7 GB of memory has been released. I can't count how much is left.
<img width="716" alt="5 又release" src="https://github.com/milvus-io/milvus/assets/74445362/b52b1c73-c4da-4a1c-a6ae-6717b5ae8eaf">

2. The diskann index will also encounter the same problem, except that there is less residue, and the memory increment is 8G after 1G of memory is left.

### Anything else?
One more thing I forgot to mention is that in order to release the remaining memory after 1.3, I tried to use both `collection.flush` and `collection.compact` methods, both of which were ineffective, and even there was a slight increase in memory footprint after compact.
This is the total capacity of this node.
![集群总资源](https://github.com/milvus-io/milvus/assets/74445362/ae0a5dc0-fe90-4b46-947b-494c031bfaf6)

**Comment by yanliang567** [comment]
sounds like a cgo known issue. 
/assign @xige-16 
/unassign

**Comment by baijinge0310** [comment]
There is the latest progress. After the collection of the load+release sq8 index type, the memory residue caused by it can be completely cleaned up through the collection of the diskann index type of load+release twice to see if the problem can be checked from this direction.

**Comment by xige-16** [comment]
@baijinge0310  We have analyzed the memory usage of Milvus and have not found any memory leaks. After releasing, the memory of the query node does not decrease immediately, which may be because the memory allocated by jemalloc is not immediately returned to the operating system.

**Comment by xige-16** [comment]
@baijinge0310 You can keep loading releases continuously, and you will find that the query node will not experience out-of-memory (OOM) errors.
