### ISSUE TITLE
Support PostgresSQL as meta backend

### ISSUE THREAD

**Issue by Vergissmeinicht** [milvus-io/milvus#2475]

**Comment by JinHai-CN** [comment]
Would you please write down why you want Milvus uses postgresql as the meta backend?

**Comment by Vergissmeinicht** [comment]
Recently I work in a project of chatterbot and I implemented a vector database by using faiss and annoy. Then I happend to know that milvus can manage vector search very well so I decide to use milvus. But I see that milvus supports only MySQL and Sqlite while my team prefer Postgres due to its better performance. So I create this issue to see whether milvus will use Postgres in the coming version. Appreciated if you can do this.

**Comment by threefoldo** [comment]
Yes, we also like PostgreSQL support.

**Comment by jockeyyan** [comment]
We have same issue, and most of our apps run on PostgreSQL, and it is easier than mysql with only one db as backend.

**Comment by libhot** [comment]
也希望支持postgre

**Comment by abhiksark** [comment]
Is there any update on this? My Team Prefers PostgreSQL as well

**Comment by faisalron** [comment]
My team would be very grateful if you support PostgreSQL...

**Comment by yhmo** [comment]
Now the team is mainly focus on developing the new architect milvus(distributed, cloud-native). Sorry we have no resource to implement this feature.

This feature including these work/tasks:
1. integrate libpqxx library into milvus, as a third-party, the source code is in: https://github.com/jtv/libpqxx
2. create **PostgresMetaImpl.h/cpp** under core/src/db/meta (just like the **core/src/db/meta/MySQLMetaImpl.h/cpp**)
3. implement all the interfaces of **core/src/db/meta/Meta.h**
4. add unittest cases for PostgresMetaImpl, just like the **unittest/db/test_db_mysql.cpp**
