### ISSUE TITLE
Milvus v0.9 crashes on startup when using non-root user for the container

### ISSUE THREAD

**Issue by Nilabhra** [milvus-io/milvus#2476]
**Bug Description**
Milvus v0.9 crashes on startup when using a non-root user for the container with the following error message in STDOUT:
```
milvus_1  | Could not open lock file.
milvus_1  | Milvus server exit...
milvus_1  | deploy_mode: single instance lock db path failed.
```
This problem is not present in v0.7.1 if the volumes for `db` and `log` are chown-ed with the proper user id.

**Steps/Code to reproduce behavior**
Use any non-root user ID.

**Expected behavior**
Milvus should boot up without any errors.

**Environment details**
- Hardware/Softward conditions: Nix based systems
- Method of installation: Pulled CPU only docker image
- Milvus version: 0.9.0
- Milvus configuration: N/A

**Comment by scsven** [comment]
@Nilabhra Hi, please check the user who starts the milvus_server has permission to create file in the `db` directory.

**Comment by Nilabhra** [comment]
@scsven I chown-ed the `db` directory and it's contents with the proper user id and group id, while this works with Milvus 0.7.1, gives me the above-mentioned error message for version 0.9.0

**Comment by scsven** [comment]
@Nilabhra Could you please try to compile following codes in Milvus container ?

`c
#include <sys/stat.h>
#include <fcntl.h>
#include <stdio.h>
#include <errno.h>


int
main(int argc, char **argv) {
    int fd = open(argv[1], O_RDWR | O_CREAT | O_NOFOLLOW, 0640);
    if (fd < 0) {
        if (errno == EROFS) {
            // Not using locking for read-only lock file
            printf("Lock file is read-only.\n");
        }
        printf("Could not open lock file.\n");
        printf("errno: %d\n", errno);
        return 0;
    }
    printf("success\n");
    return 0;
}
`

After you compiled the code successfully, try with this
`
./a.out /path/to/milvus/db
`
and paste the output here ?

**Comment by Nilabhra** [comment]
I get the following:
```
Could not open lock file.
errno: 21
```
Here are how the permissions look:
```
-rw-r--r-- 1 1000 1001 24576 May 31 20:08 meta.sqlite
-rw-r--r-- 1 1000 1001 32768 Jun  3 12:33 meta.sqlite-shm
-rw-r--r-- 1 1000 1001     0 Jun  3 12:33 meta.sqlite-wal
drwxr--r-- 3 1000 1001  4096 May 31 20:04 tables
```

**Comment by JinHai-CN** [comment]
Errno 21 means this is a directory.

Please change the command to:
'''
./a.out /path/to/milvus/db/file.lock
'''

**Comment by JinHai-CN** [comment]
@Nilabhra Also, Please printout current directory permissions. In 0.9.0, Milvus will create a lock file to make this directory only used by one Milvus instance. If you can't create the lock file, there must be some reason and we want to know it.

**Comment by Nilabhra** [comment]
There is no `file.lock` inside `db` but there is a file called `lock` in `/var/lib/milvus/`.

I ran the program for both the cases and it just prints `success`:
```
root@1067eb119d2e:~# ./a.out /var/lib/milvus/lock
success
root@1067eb119d2e:~# ./a.out /var/lib/milvus/db/lock.file
success
```

The directory permissions look like this:

```
drwxr-xr-x 2 root root 4096 May 15 01:55 bin
drwxr-xr-x 1 root root 4096 May 27 10:52 conf
drwxr-xr-x 3 1000 1001 4096 Jun  4 09:57 db
-rwxr-xr-x 1 root root  116 May 15 01:54 docker-entrypoint.sh
drwxr-xr-x 2 root root 4096 May 15 01:55 lib
-rw-r----- 1 root root    0 Jun  4 09:57 lock
drwxr-x--x 2 root root 4096 Jun  4 09:57 logs
drwxr-xr-x 1 root root 4096 Jun  4 09:57 scripts
drwxr-xr-x 2 1000 1001 4096 May 31 20:08 wal
```

I guess I could create the lock file because my user was root when I logged into the container. I tried creating a new user but could not get the file to link after compilation:

```
dummy@1067eb119d2e:/home$ gcc a.c -o a.out
/usr/bin/ld: cannot open output file a.out: Permission denied
collect2: error: ld returned 1 exit status
```

**Comment by scsven** [comment]
@Nilabhra I have some questions, one is whether the user dummy is user 1000, and the other question is why the permission of directories such as `bin` / `conf` / `logs` belong to root ?

**Comment by JinHai-CN** [comment]
@Nilabhra I am curious who creates /var/lib/milvus/lock? Milvus only creates the lock file in db/wal directory. Another issue: what is in your WAL directory?

**Comment by Nilabhra** [comment]
@JinHai-CN I don't know who creates `/var/lib/milvus/lock`. There is no `db/wal`. The `wal` directory has:
```
total 4
-rw-r----- 1 dummy dummygroup  0 May 25 20:49 lock
-rw-r--r-- 1 dummy dummygroup 24 May 31 20:06 mxlog.meta
```

**Comment by JinHai-CN** [comment]
OK, then try to remove the lock file in wal directory and restart Milvus.

**Comment by Nilabhra** [comment]
It doesn't boot up when I try with user 1000.

**Comment by scsven** [comment]
@Nilabhra I found the cause of this problem. Milvus create lock in `primary_path` which is defined in server_config.yaml, by default, `primary_path` is `/var/lib/milvus`. So, Milvus tried to lock with `/var/lib/milvus/lock`. With you paste above, this file is belong to `root`. 

So you have to delete this file `/var/lib/milvus/lock` with `root` user, and then chown `/var/lib/milvus` with user `dummy`.

If you want to prevent the executable program and config files from being modified, separating the program and data would be a good solution.

**Comment by Nilabhra** [comment]
@scsven This worked, thanks for all the help!
