### ISSUE TITLE
[Bug]: It still needs to provide metric type when search 

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#24785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20230608-a03ebcff
- Deployment mode(standalone or cluster): 2.2.0-20230608-a03ebcff
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.9.dev36
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior
It still needs to provide metric type when search.
Now it seems that search params don't need 'params' anymore except metric type.

### Expected Behavior
support provide search params

### Steps To Reproduce

```markdown
from pymilvus import CollectionSchema, FieldSchema, Collection, connections, DataType, Partition, utility
import numpy as np
import random
connections.connect()

# create a collection
dim = 3
fields = [
    FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True, description='pk'),
    FieldSchema(name="float", dtype=DataType.FLOAT),
    FieldSchema(name="string", dtype=DataType.VARCHAR, max_length=64),
    FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
]
schema = CollectionSchema(fields=fields)
collection = Collection("test_search", schema=schema)
# utility.drop_collection('test_search')

# insert data
nb = 3000
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
data = [[i for i in range(nb)], [np.float32(i) for i in range(nb)], [str(i) for i in range(nb)], vectors]
collection.insert(data)

# create index and load
index_params = {"index_type": "FLAT", "params": {"nlist": 128}, "metric_type": "L2"}
collection.create_index("float_vector", index_params)
collection.load()

# search
search_params = {"metric_type": "L2", "params": {"search_k": 1000}}
res = collection.search(vectors[:1], "float_vector", search_params, 10)
print(res[0].ids)
```

**Comment by chasingegg** [comment]
@NicoYuan1986 why you say metric type is must to be set, since I don't see a test case without metric type.

**Comment by NicoYuan1986** [comment]
> @NicoYuan1986 why you say metric type is must to be set, since I don't see a test case without metric type.

I just found out that we have provided default params of index and search. I thought it might be a bug before.
I will modify the issue content and add some test cases then.



There are some test cases about search_params.
test_search_param_invalid_metric_type, test_search_invalid_params_type, test_search_normal_without_specify_metric_type, test_search_normal_default_params

some are new-added.

**Comment by filip-halt** [comment]
The reason this happened was because pymilvus went from setting metric_type to "" to not including it in the request.

**Comment by NicoYuan1986** [comment]
Fixed. I will add some test cases then.
