### ISSUE TITLE
Python SDK will return an empty array if the collection is empty

### ISSUE THREAD

**Issue by shengjun1985** [milvus-io/milvus#2479]
**Describe the bug**
Python sdk will return an empty array if the collection is empty

**Steps/Code to reproduce behavior**
(1) create a collection
(2) insert 1 row into it
(3) delete the row
(4) query with nq = 5 and topK = 10 by Python SDK
empty array is returned

**Expected behavior**
"[[],[],[],[],[]]" is expected.

**Environment details**
- Milvus version (v0.9.1)
- Python SDK version (0.2.12)

**Additional context**
Python SDK will run OK If the server returns {-1, -1, -1, -1, -1}.
Python SDK will run an empty array If the server returns {}.

**Comment by shengjun1985** [comment]
@BossZou 
This issue is fixed by the server, and now I close it.
Please help to confirm that Python SDK will run an empty array If the server returns {}.

**Comment by BossZou** [comment]
Python SDK will return empty 2-D results if response is empty.
