### ISSUE TITLE
[BUG] external dependencies should reside in /thirdparties other than src/external

### ISSUE THREAD

**Issue by cxie** [milvus-io/milvus#248]
**Is your feature request related to a problem? Please describe.**
This bug is upstream of #246

**Describe the solution you'd like**
Modify CMake configuration to move dependencies into /thirdparties, and remove src/external fold.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by scsven** [comment]
Good idea, but third party directory called thirdparty rather than thirdparties in general.

interesting link https://vector-of-bool.github.io/2018/09/16/layout-survey.html

**Comment by scsven** [comment]
Done
