### ISSUE TITLE
[Bug]: Deploy Milvus failed with standby mode is on

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#24802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230609-3f8777db
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/12268675/558314a8-75c2-4439-b460-0123cdb83753)

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/standby_test/detail/standby_test/1435/pipeline
log:

[artifacts-rootcoord-pod-failure-1435-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/11706001/artifacts-rootcoord-pod-failure-1435-server-logs.tar.gz)
[artifacts-rootcoord-pod-failure-1435-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11706003/artifacts-rootcoord-pod-failure-1435-pytest-logs.tar.gz)

### Anything else?

It works well with 2.2.0-20230608-a03ebcff, so there is something wrong with the commit in 06/09

**Comment by zhuwenxing** [comment]
Seems like an environmental issue.  It works well in today's test for image tag 2.2.0-20230609-3f8777db.
![image](https://github.com/milvus-io/milvus/assets/12268675/ba7d2808-980c-4e11-834c-4520dc924c1e)

success job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/standby_test/detail/standby_test/1437/pipeline/74

**Comment by wayblink** [comment]
see it

**Comment by wayblink** [comment]
Seems caused by env at that time, not reproduced any more. Open this issue if it happens again.
