### ISSUE TITLE
[Bug]: set type NodePort fail

### ISSUE THREAD

**Issue by yesletgo** [milvus-io/milvus#24801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.9
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The cluster is installed through Milvus Operator, k8s (1.27.0) is installed through Kubeadm, and Docker (24.0.2).
Use: kubectl edit svc my-release-milvus
![image](https://github.com/milvus-io/milvus/assets/21998052/327390ed-da4c-4cb0-914c-5111fb508ce6)

My release milvus sets the type to nodeport, which only takes effect temporarily and will change back to ClusterIP later
![image](https://github.com/milvus-io/milvus/assets/21998052/b262a179-11b9-4c8f-a7b8-87d190e1ce35)

### Expected Behavior

My release milvus takes effect by setting the type to nodeport

**Comment by haorenfsa** [comment]
Hi, the service is managed by operator. Here's how to modify service type

![Screenshot_20230610_173336_com.github.android.jpg](https://github.com/milvus-io/milvus/assets/15938850/3ad1ac6e-266f-4cfe-9cf8-1927389f6f0d)

For more information check https://github.com/milvus-io/milvus-operator/blob/main/docs/CRD/milvus.md

**Comment by yesletgo** [comment]
> Hi, the service is managed by operator. Here's how to modify service type
> 
> ![Screenshot_20230610_173336_com.github.android.jpg](https://user-images.githubusercontent.com/15938850/244862224-3ad1ac6e-266f-4cfe-9cf8-1927389f6f0d.jpg)
> 
> For more information check https://github.com/milvus-io/milvus-operator/blob/main/docs/CRD/milvus.md

Thank you. how to login  the mini front-end interface with the type nodeport.
![image](https://github.com/milvus-io/milvus/assets/21998052/33f3a99c-0b3d-4c9b-961c-cb018c8b5bc4)

**Comment by yesletgo** [comment]
How to configure mini other port: 9001 in the configuration file using milvus operator mode ？

**Comment by haorenfsa** [comment]
use kubectl get pod -o wide, you can find the hostname of the node ,use it together with the nodeport

**Comment by haorenfsa** [comment]
> How to configure mini other port: 9001 in the configuration file using milvus operator mode ？

I'm not sure if you want to use different port of minio created by milvus or externally deployed minio?

**Comment by yesletgo** [comment]
> > How to configure mini other port: 9001 in the configuration file using milvus operator mode ？
> 
> I'm not sure if you want to use different port of minio created by milvus or externally deployed minio?

I want to access Minio on the browser interface, and I have learned that accessing Minio's 9001 port is possible, but how to map the port so that external servers can access it.

**Comment by haorenfsa** [comment]
@yesletgo The minio helm chart we're using is rather old and does not support that configuration directly. You can walk around by first copying  the current `my-release-minio`, and rename it like `my-release-minio-console`, and change the port of it to 9001, and then access through the new nodeport

**Comment by yesletgo** [comment]
> @yesletgo The minio helm chart we're using is rather old and does not support that configuration directly. You can walk around by first copying the current `my-release-minio`, and rename it like `my-release-minio-console`, and change the port of it to 9001, and then access through the new nodeport

ok, thank you.

**Comment by yesletgo** [comment]
@haorenfsa 
How can port 2379 of ETCD be mapped out for clusters installed through milvus operator? I am modifying from type set clusterIp to NodePort through 'kubectl edit svc my release-etcd' , but I don't think it's correct.
![image](https://github.com/milvus-io/milvus/assets/21998052/13f4ff65-5707-40c8-a39e-7eda83d74486)

**Comment by haorenfsa** [comment]
@yesletgo For temporary changes you can use `kube edit` directly as you mentioned.  It will be only overwritten if you try to update or restart your etcd through milvus-operator.
Or you can set `spec.dependencies.etcd.inCluster.values.service.type` to `NodePort` as permanent change.

**Comment by yesletgo** [comment]
> spec.dependencies.etcd.inCluster.values.service.type

Thank you. Can you tell me where to find it? There are no relevant documents, only the following:
![image](https://github.com/milvus-io/milvus/assets/21998052/c3206610-ad87-4020-b82e-4b2a5358562b)

**Comment by haorenfsa** [comment]
Here:
<img width="1095" alt="image" src="https://github.com/milvus-io/milvus/assets/15938850/d32ae475-27f2-41b9-8e74-43431902228a">

**Comment by yesletgo** [comment]
> Here: <img alt="image" width="1095" src="https://user-images.githubusercontent.com/15938850/251692191-d32ae475-27f2-41b9-8e74-43431902228a.png">

Thanks a lot.
