### ISSUE TITLE
[Bug]: Goroutine number is large on large collection numbers

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#24826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

each collection has two shards by default
Each shards has a bunch of goroutines, including:

from the pprof stack:
Flowgraph takes around 5000 goroutines. 
MsgStream 1193
panjf2000 785
Etcd 3558 goroutines
ShardCluster 1533
Cache evictedWorker 415
channelEventManager 390
mergedTimeTickerSender 390

**Comment by yanliang567** [comment]
any updates

**Comment by xiaofan-luan** [comment]
this has to be fixed.

@smellthemoon 
@sunby 
any comments?

**Comment by yanliang567** [comment]
@smellthemoon any updates

**Comment by smellthemoon** [comment]
> @smellthemoon any updates

sorry to see this now, I will do it as soon as possible.

**Comment by smellthemoon** [comment]
shard cluster 2.3 has removed.

**Comment by smellthemoon** [comment]
some thoughts and solutions about that:
1.  five nodes(dmStreamNode, ddNode, insertBufferNode, deleteNode, ttNode) in flowgraph now. dmStreamNode will consume data from mq, which have some io operations. Others will have an input and an output, which are passed as parameters, which are executed sequentially and can be placed in one goroutine.
2. newChannel has already use global pool now, but it do submitting in a goroutine in case of task pool is full. When the size of work pool is small or the load is heavy, may cause some goroutines wait(lazy load, can't block here). Set channelWorkPoolSize in milvus.yaml  may can handle this situation more flexibly.
3. channelEventManager is  going to be abandoned (move etcd watch).

**Comment by xiaofan-luan** [comment]
we actually works on a seperate the issue to improve milvus performance with more than 10000 collections.
