### ISSUE TITLE
[Bug]: The check of param 'search_params' in search and search_iterator is not consistent

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#24827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230608-41af0a98
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0.dev70
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

 The check of param 'search_params' in search and search_iterator is not consistent.

```python
search_params = {"metric_type": "L2"}

# search:
res = collection.search(vectors[:1], "float_vector", search_params, limit, output_fields=['int64'], expr=expression)

# collection.search_iterator
res = collection.search_iterator(vectors[:1], "float_vector", search_params, limit, output_fields=['int64'], expr=expression)
"""
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 694, in search_iterator
    iterator = SearchIterator(conn, self._name, data, anns_field, param, limit, expr, partition_names,
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/iterator.py", line 117, in __init__
    self.__check_radius()
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/iterator.py", line 132, in __check_radius
    if self._param[PARAMS][RADIUS] is None:
KeyError: 'params'
"""
```

### Expected Behavior

update error check of search_iterator

### Steps To Reproduce

```markdown
from pymilvus import CollectionSchema, FieldSchema, Collection, connections, DataType, Partition, utility
import numpy as np
import random
connections.connect()

dim = 8
fields = [
    FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, description='pk'),
    FieldSchema(name="int64", dtype=DataType.INT64),
    FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
]
schema = CollectionSchema(fields=fields)
collection = Collection("test_search_iterator", schema=schema)
# utility.drop_collection('test_search_iterator')

nb = 1000
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
data = [
    [i for i in range(nb)],
    [i for i in range(nb)],
    vectors
]
collection.insert(data)

collection.create_index("float_vector", {"metric_type": "L2"})
collection.load()

limit = 5
expression = "5 <= int64 < 995"
search_params = {"metric_type": "L2"}
collection.search(vectors[:1], "float_vector", search_params, limit, output_fields=['int64'], expr=expression)
res = collection.search_iterator(vectors[:1], "float_vector", search_params, limit,
                                 output_fields=['int64'], expr=expression)


collection.drop()
```

**Comment by MrPresent-Han** [comment]
https://github.com/milvus-io/pymilvus/pull/1534

**Comment by MrPresent-Han** [comment]
Also, some tiny adjustment needed towards test code, as following:
`from pymilvus import CollectionSchema, FieldSchema, Collection, connections, DataType, Partition, utility
import random

HOST = "localhost"
PORT = 19530

connections.connect("default", host=HOST, port=PORT)

dim = 8
fields = [
    FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, description='pk'),
    FieldSchema(name="int64", dtype=DataType.INT64),
    FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
]
schema = CollectionSchema(fields=fields)
collection = Collection("test_search_iterator", schema=schema)

nb = 1000
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
data = [
    [i for i in range(nb)],
    [i for i in range(nb)],
    vectors
]
collection.insert(data)

collection.create_index("float_vector", {"metric_type": "L2"})
collection.load()

limit = 5
expression = "5 <= int64 < 995"
search_params = {"metric_type": "L2"}
collection.search(vectors[:1], "float_vector", search_params, limit, output_fields=['int64'], expr=expression)
search_iterator = collection.search_iterator(vectors[:1], "float_vector", search_params, limit,
                                 output_fields=['int64'], expr=expression)

page_idx = 0
while True:
    res = search_iterator.next()  # next翻页
    if len(res[0]) == 0:
        print("query iteration finished, close")
        search_iterator.close()  # 没有新的结果，翻页结束，close掉iterator
        break
    for i in range(len(res[0])):
        print(res[0][i])
    page_idx += 1
    print(f"page{page_idx}-------------------------")

collection.drop()`

**Comment by NicoYuan1986** [comment]
Fixed!
