### ISSUE TITLE
[Bug]: https://github.com/zilliztech/milvus-backup/issues/139

### ISSUE THREAD

**Issue by liwenchao1995** [milvus-io/milvus#24825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://github.com/zilliztech/milvus-backup/issues/139

### Expected Behavior

https://github.com/zilliztech/milvus-backup/issues/139

### Steps To Reproduce

```markdown
https://github.com/zilliztech/milvus-backup/issues/139
```

### Milvus Log

https://github.com/zilliztech/milvus-backup/issues/139

**Comment by liwenchao1995** [comment]
thank you

**Comment by yanliang567** [comment]
assigned the issue to the owner. let's follow up the issue in backup repo.
