### ISSUE TITLE
[Bug]:[v2.2.8] load Collection stuck at 50% , querynode error log：Assert \"not supported\" at /go/src/github.com/milvus-io/milvus/internal/core/src/storage/DataCodec.cpp:81

### ISSUE THREAD

**Issue by yangshuai0711** [milvus-io/milvus#24836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.8
- Deployment mode(cluster):
- MQ type(pulsar):    
- SDK version(attu 2.2.5):
- OS(centos7 based k8s, run official docker images): 
- CPU/Memory: assign by helm charts
- GPU: none
- Others:
```

### Current Behavior

i startup a cluster by helm, icreate a simple collection with 2 fields, id and vec(512 float).
then i insert 100 sample data by attu, and create an index , i click load collection button ,then it happend.

![image](https://github.com/milvus-io/milvus/assets/4221876/fd06c5d0-dc04-4099-9415-f43fcb543ad7)

### Expected Behavior

data loaded, and i can execute an normal search

### Steps To Reproduce

```markdown
i startup a cluster by helm, icreate a simple collection with 2 fields, id and vec(512 float).
then i insert 100 sample data by attu, and create an index , i click load collection button ,then it happend.
```

### Milvus Log

[logs.tar.gz](https://github.com/milvus-io/milvus/files/11722932/logs.tar.gz)

**Comment by yangshuai0711** [comment]
> @yangshuai0711 does it reproduce on milvus v2.2.9?
> 
> /assign @jiaoew1991 @yangshuai0711

yes, it is

**Comment by Ramya25061997** [comment]
same issue Collection loading stuck at 50% with milvus version 2.2.8 and 2.2.9 and attu version 2.1.1. readiness probe also failing for datacoord, datanode, indexcoord , proxy

**Comment by jiaoew1991** [comment]
/assign @xige-16 

Looks like it's a change brought by version 2.2.8.

**Comment by xiaofan-luan** [comment]
what kind of index you are using? 
And do you change any configs? @yangshuai0711

**Comment by yangshuai0711** [comment]
> 
yes, i changed configs. several times.

index config:
![image](https://github.com/milvus-io/milvus/assets/4221876/46fac264-ad7c-4e74-a998-adb940abdccc)

now i can reproduce this problem  with docker-compose  config from https://github.com/milvus-io/milvus/blob/master/deployments/docker/cluster/docker-compose.yml, and image change to 2.2.8

**Comment by yangshuai0711** [comment]
@xige-16 @jiaoew1991 @yanliang567 
I think I found the cause. I changed 'externalS3' in the chart values. When I recovered it to 'minIO inbounded', it worked fine
Maybe there are some problems with my S3 server, but it's okay when I write and read files with the S3 SDK myself.

**Comment by jiaoew1991** [comment]
> @xige-16 @jiaoew1991 @yanliang567 @xiaofan-luan I think I found the cause. I changed 'externalS3' in the chart values. When I recovered it to 'minIO inbounded', it worked fine Maybe there are some problems with my S3 server, but it's okay when I write and read files with the S3 SDK myself.

Thank you for providing the clue. We will investigate it to see if there are any other issues. 😄

**Comment by yangshuai0711** [comment]
> 



> 



> > @xige-16 @jiaoew1991 @yanliang567 @xiaofan-luan I think I found the cause. I changed 'externalS3' in the chart values. When I recovered it to 'minIO inbounded', it worked fine Maybe there are some problems with my S3 server, but it's okay when I write and read files with the S3 SDK myself.
> 
> Thank you for providing the clue. We will investigate it to see if there are any other issues. 😄

Yes, I have verified that my S3 server is working properly. After configuring Milvus with externalS3, data can be written normally, but there are issues when the indexNode reads the index. Currently, my purpose of using an additional S3 service cannot be achieved. Could you please help me take a look at what the problem might be?

**Comment by xige-16** [comment]
> > 
> 
> > 
> 
> > > @xige-16 @jiaoew1991 @yanliang567 @xiaofan-luan I think I found the cause. I changed 'externalS3' in the chart values. When I recovered it to 'minIO inbounded', it worked fine Maybe there are some problems with my S3 server, but it's okay when I write and read files with the S3 SDK myself.
> > 
> > 
> > Thank you for providing the clue. We will investigate it to see if there are any other issues. 😄
> 
> Yes, I have verified that my S3 server is working properly. After configuring Milvus with externalS3, data can be written normally, but there are issues when the indexNode reads the index. Currently, my purpose of using an additional S3 service cannot be achieved. Could you please help me take a look at what the problem might be?

I have reproduced the issue on macos, and this issue is being investigated.

**Comment by zhagnlu** [comment]
the same issue as https://github.com/milvus-io/milvus/issues/24959

**Comment by xige-16** [comment]
milvus 2.2.11 has fixed this issue

**Comment by yanliang567** [comment]
@yangshuai0711 could you please retry with Milvus 2.2.13 to verify the fix?
/unassign
/assign @yangshuai0711

**Comment by yangshuai0711** [comment]
> @yangshuai0711 could you please retry with Milvus 2.2.13 to verify the fix? /unassign /assign @yangshuai0711

ok， i will verify it soon
