### ISSUE TITLE
[Bug]: Query iterator failed reporting KeyError: 'id'

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#24833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230608-41af0a98
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0.dev70
```

### Current Behavior

Query iterator failed reporting KeyError: 'id'.

```
>>> while True:
...     res = query_iterator.next()  # next翻页
...     if len(res) == 0:
...         print("query iteration finished, close")
...         query_iterator.close()  # 没有新的结果，翻页结束，close掉iterator
...         break
...     for i in range(len(res)):
...         print(res[i])
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/iterator.py", line 66, in next
    self.__update_cursor(ret)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/iterator.py", line 93, in __update_cursor
    self._next_id = res[-1][ID]
KeyError: 'id'
```

### Expected Behavior

query successfully

### Steps To Reproduce

```python
from pymilvus import CollectionSchema, FieldSchema, Collection, connections, DataType, Partition, utility
import random
connections.connect()

dim = 8
fields = [
    FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, description='pk'),
    FieldSchema(name="int64", dtype=DataType.INT64),
    FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
]
schema = CollectionSchema(fields=fields)
collection = Collection("test_search_iterator", schema=schema)
# utility.drop_collection('test_search_iterator')

nb = 1000
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
data = [
    [i for i in range(nb)],
    [i for i in range(nb)],
    vectors
]
collection.insert(data)

collection.create_index("float_vector", {"metric_type": "L2"})
collection.load()

expression = "5 <= int64 < 995"
query_iterator = collection.query_iterator(expr=expression, output_fields=['int64'],
                                           offset=0, limit=5, consistency_level='Strong')

while True:
    res = query_iterator.next()  # next翻页
    if len(res) == 0:
        print("query iteration finished, close")
        query_iterator.close()  # 没有新的结果，翻页结束，close掉iterator
        break
    for i in range(len(res)):
        print(res[i])
```

**Comment by shunjiezhao** [comment]
Hi, I found that we set pk field name to constant.
https://github.com/milvus-io/pymilvus/blob/d3b98ca1052bc3ad31d757828b7abbe23eaea556/pymilvus/orm/constants.py#L28

get query result use this constant
https://github.com/milvus-io/pymilvus/blob/d3b98ca1052bc3ad31d757828b7abbe23eaea556/pymilvus/orm/iterator.py#L93

constructing expr is also used
https://github.com/milvus-io/pymilvus/blob/d3b98ca1052bc3ad31d757828b7abbe23eaea556/pymilvus/orm/iterator.py#LL79C1-L88C28

firstly, we use expr https://github.com/milvus-io/pymilvus/blob/d3b98ca1052bc3ad31d757828b7abbe23eaea556/pymilvus/orm/iterator.py#LL81C1-L82C32
this is  query result
![image](https://github.com/milvus-io/milvus/assets/90906581/bdc1d2b7-9e9b-4a41-b69d-162a62444d4d)


I think we should get pk field schema from collection or schema param in py sdk.

**Comment by MrPresent-Han** [comment]
hello, @NicoYuan1986 , thanks for detecting flaws and this has been fixed by pr:
https://github.com/milvus-io/milvus/issues/24833

**Comment by MrPresent-Han** [comment]
Also, test code needs some tiny adjustment:
`from pymilvus import CollectionSchema, FieldSchema, Collection, connections, DataType, Partition, utility
import random

HOST = "localhost"
PORT = 19530

connections.connect()

dim = 8
fields = [
    FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, description='pk'),
    FieldSchema(name="int64", dtype=DataType.INT64),
    FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
]
schema = CollectionSchema(fields=fields)
collection = Collection("test_search_iterator", schema=schema)
# utility.drop_collection('test_search_iterator')

nb = 1000
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
data = [
    [i for i in range(nb)],
    [i for i in range(nb)],
    vectors
]
collection.insert(data)

collection.create_index("float_vector", {"metric_type": "L2"})
collection.load()

expression = "5 <= int64 < 995"
query_iterator = collection.query_iterator(expr=expression, output_fields=['int64'],
                                           offset=0, limit=5, consistency_level='Strong')
page_idx = 0
while True:
    res = query_iterator.next()
    if len(res) == 0:
        print("query iteration finished, close")
        query_iterator.close()
        break
    for i in range(len(res)):
        print(res[i])
    page_idx += 1
    print(f"page{page_idx}-------------------------")`

**Comment by NicoYuan1986** [comment]
Fix. master-20230619-21769072    pymilvus==2.4.0.dev75
