### ISSUE TITLE
[Enhancement]: Tracking the use of mockery to mock existing interfaces.

### ISSUE THREAD

**Issue by jiaoew1991** [milvus-io/milvus#24845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Due to historical reasons, many mock codes in unit tests are handwritten, which makes them difficult to maintain. Starting from version 2.2.0, Milvus introduces mockery to generate mock codes. 

Follow the progress of this replacement through this issue.

**Comment by jiaoew1991** [comment]
keep it

**Comment by xiaofan-luan** [comment]
I failed to create mockery on macos becasue of CGO
could not import C (no metadata for C)"
