### ISSUE TITLE
[Bug]:Should hide autoindex parameter detail

### ISSUE THREAD

**Issue by czs007** [milvus-io/milvus#24850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

In the event that the user does not specify any index parameters, the 'describe index' function will return the detailed index parameters for 'AUTOINDEX'.

### Expected Behavior

In the event that the user does not specify any index parameters,  should not return the detailed index parameters for 'AUTOINDEX'.

**Comment by yanliang567** [comment]
verified fix on 8ef67b8
