### ISSUE TITLE
[Bug]: Unable to build milvus in dev container on master branch

### ISSUE THREAD

**Issue by vku-ibm** [milvus-io/milvus#24863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master (028cbee5192cca9c40e4eddccccdc3b099c0fc84)
- Deployment mode(standalone or cluster): dev container
- OS(Ubuntu or CentOS): docker host on Ubuntu 22.04
- CPU/Memory: 2cores 8gmem (VM)
- docker version: 24.0.2
- docker-compose version: 1.29.2
```

### Current Behavior

Following guidelines to build milvus in a docker container:
[https://github.com/milvus-io/milvus/tree/master/build#readme](https://github.com/milvus-io/milvus/tree/master/build#readme)

Working from a clean clone of master at revision (028cbee5192cca9c40e4eddccccdc3b099c0fc84).

1. Launched dev containers:
```
$ ./scripts/devcontainer.sh up
~/milvus-dev/milvus ~/milvus-dev/milvus
Creating network "milvus_dev" with the default driver
Creating milvus_etcd_1   ... done
Creating milvus_minio_1  ... done
Creating milvus_pulsar_1 ... done
Creating milvus_jaeger_1 ... done
Creating milvus_builder_1    ... done
Creating milvus_gpubuilder_1 ... done
~/milvus-dev/milvus
```

2. Checked state of containers:
```
$ docker-compose -f docker-compose-devcontainer.yml ps
       Name                      Command                       State                                            Ports                                 
------------------------------------------------------------------------------------------------------------------------------------------------------
milvus_builder_1      /tini -- autouseradd --use ...   Up                                                                                             
milvus_etcd_1         /opt/bitnami/scripts/etcd/ ...   Up (health: starting)   2379/tcp, 2380/tcp                                                     
milvus_gpubuilder_1   /tini -- autouseradd --use ...   Up                                                                                             
milvus_jaeger_1       /go/bin/all-in-one-linux         Up                      14250/tcp, 14268/tcp, 16686/tcp, 5775/udp, 5778/tcp, 6831/udp, 6832/udp
milvus_minio_1        /usr/bin/docker-entrypoint ...   Up (health: starting)   9000/tcp                                                               
milvus_pulsar_1       bin/pulsar standalone --no ...   Up 
```

3. Logged into container and tried to build milvus:
```
$ docker exec -ti milvus_builder_1 bash
milvus@71c86b360034:/go/src/github.com/milvus-io/milvus$ make milvus
Download milvus-proto repo ...
Build 3rdparty ...
/go/src/github.com/milvus-io/milvus/cmake_build /go/src/github.com/milvus-io/milvus
/usr/bin/python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /go/src/github.com/milvus-io/milvus/internal/core/output/lib/libjemalloc.so)
/usr/bin/python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /go/src/github.com/milvus-io/milvus/internal/core/output/lib/libjemalloc.so)
/usr/bin/python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /go/src/github.com/milvus-io/milvus/internal/core/output/lib/libjemalloc.so)
/usr/bin/python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /go/src/github.com/milvus-io/milvus/internal/core/output/lib/libjemalloc.so)
uname: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /go/src/github.com/milvus-io/milvus/internal/core/output/lib/libjemalloc.so)
uname: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /go/src/github.com/milvus-io/milvus/internal/core/output/lib/libjemalloc.so)
Cannot build on windows
/go/src/github.com/milvus-io/milvus
Generate proto ...
Installing protoc-gen-go
/go/src/github.com/milvus-io/milvus/internal/proto /go/src/github.com/milvus-io/milvus
/go/src/github.com/milvus-io/milvus/cmake_build/bin/protoc: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /go/src/github.com/milvus-io/milvus/cmake_build/bin/protoc)
generate etcd_meta.proto failed
make: *** [Makefile:157: generated-proto] Error 1
```

### Expected Behavior

The expectation is to have milvus being build in the container successfully.

### Steps To Reproduce

```markdown
1. Clone https://github.com/milvus-io/milvus
2. Try to build milvus in container on master branch (rev 028cbee5192cca9c40e4eddccccdc3b099c0fc84)
```

**Comment by jiaoew1991** [comment]
Hi @vku-ibm, could you provide the docker image ID for me to use? I have no problem starting the dev container locally with master.

**Comment by vku-ibm** [comment]
@jiaoew1991
the image of dev environment is: milvusdb/milvus-env:amd64-ubuntu20.04-20230320-f547c1f
and id is: 5aa66e588067

hope that helps! Please, let me know if you need more information or if we should try something on our side.

**Comment by jiaoew1991** [comment]
> Logged into container and tried to build milvus:
> $ docker exec -ti milvus_builder_1 bash
> milvus@71c86b360034:/go/src/github.com/milvus-io/milvus$ make milvus
> Download milvus-proto repo ...
> Build 3rdparty ...
> /go/src/github.com/milvus-io/milvus/cmake_build /go/src/github.com/milvus-io/milvus
> /usr/bin/python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /go/src/github.com/milvus-io/milvus/internal/core/output/lib/libjemalloc.so)
> /usr/bin/python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /go/src/github.com/milvus-io/milvus/internal/core/output/lib/libjemalloc.so)
> /usr/bin/python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /go/src/github.com/milvus-io/milvus/internal/core/output/lib/libjemalloc.so)
> /usr/bin/python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /go/src/github.com/milvus-io/milvus/internal/core/output/lib/libjemalloc.so)
> uname: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /go/src/github.com/milvus-io/milvus/internal/core/output/lib/libjemalloc.so)
> uname: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /go/src/github.com/milvus-io/milvus/internal/core/output/lib/libjemalloc.so)
> Cannot build on windows
> /go/src/github.com/milvus-io/milvus
> Generate proto ...
> Installing protoc-gen-go
> /go/src/github.com/milvus-io/milvus/internal/proto /go/src/github.com/milvus-io/milvus
> /go/src/github.com/milvus-io/milvus/cmake_build/bin/protoc: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /go/src/github.com/milvus-io/milvus/cmake_build/bin/protoc)
> generate etcd_meta.proto failed
> make: *** [Makefile:157: generated-proto] Error 1

<img width="872" alt="image" src="https://github.com/milvus-io/milvus/assets/2297455/8eccd3e9-8caa-4c33-8d4a-66ee1b086e37">

From this code snippet and the error log above, it seems that you might not be running in a docker environment 🤔. It's quite strange.

**Comment by jiaoew1991** [comment]
@vku-ibm Is there any more of this issue? If not, I will close the issue.

**Comment by hatfieldbrian** [comment]
`make clean` fixed this for me.  I had initially built it on a RHEL 9 host by issuing `make` then switched to `build/builder.sh make`.
