### ISSUE TITLE
[Enhancement]: Investigate performance affect on K

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#24866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

We've found performance is not affect on small topk(1-50).
But with performance larger than top 100, we've seen performance degrade. 
For instance, with topk 1000, we've seen 20 times lacency compared to top1.

Wonder if there are any thing we can do to improve latency on large topK search.

**Comment by xiaofan-luan** [comment]
this should be split into two parts:
1) what knowhere's expected performance @liliu-z 
2) is there any bottle neck on milvus side we can improve @longjiquan

**Comment by longjiquan** [comment]
I guess https://github.com/milvus-io/milvus/pull/25166 will optimize this a little when the topk is very large.

**Comment by longjiquan** [comment]
I have profiled the search path when the topk is very large, anyone interested can refer to https://zilliverse.feishu.cn/docx/OHxPd6m0xoRs1SxUePxc7lIGnhe for detailed results.
