### ISSUE TITLE
[Bug]: ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by Light-jason** [milvus-io/milvus#24868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.3
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

when I set the collection_name,it will be appear the following error:
  File "D:\预装软件\Jetbrain\PyCharm 2021.1.2\plugins\python\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\预装软件\Jetbrain\PyCharm 2021.1.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/PycharmProject/AICustomService/compare.py", line 72, in <module>
    vector_db = Milvus.from_documents(
  File "D:\Anaconda\lib\site-packages\langchain\vectorstores\base.py", line 296, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
  File "D:\Anaconda\lib\site-packages\langchain\vectorstores\milvus.py", line 794, in from_texts
    vector_db = cls(
  File "D:\Anaconda\lib\site-packages\langchain\vectorstores\milvus.py", line 147, in __init__
    self._init()
  File "D:\Anaconda\lib\site-packages\langchain\vectorstores\milvus.py", line 206, in _init
    self._extract_fields()
  File "D:\Anaconda\lib\site-packages\langchain\vectorstores\milvus.py", line 286, in _extract_fields
    self.fields.remove(self._primary_field)
ValueError: list.remove(x): x not in list

**Comment by shiyu22** [comment]
Hi @Light-jason, I have reproduced your issue, you used an existing collection, right? But LangChain has its own rules to create the collection, and when your collection schema does not match his, it will report such an error. So, it is recommended to use a collection name that does not exist.

If you really want to use an existing table, the table creation parameters should be consistent with LangChain, refer to [_create_collection](https://github.com/hwchase17/langchain/blob/master/langchain/vectorstores/milvus.py#L211).
> You can create collection with this fields:
> ```
> fields = [
>    FieldSchema(name='pk', dtype=DataType.INT64, is_primary=True, auto_id=True),
>    FieldSchema(name='text', dtype=DataType.VARCHAR, max_length=65_535),
>    FieldSchema(name='vector', dtype=DataType.FLOAT_VECTOR, dim=1536)
> ]
> ```

**Comment by shiyu22** [comment]
Good job. So we can close the issue. @Light-jason @yanliang567

**Comment by MehediTamim** [comment]
@shiyu22  I used your solution. But I got the same error.

I created a collection like below:
fields = [
            FieldSchema(name='pk', dtype=DataType.INT64, description='ids', max_length=2000, is_primary=True, auto_id=False),
            FieldSchema(name='text', dtype=DataType.ARRAY, element_type=DataType.VARCHAR, description='metadata',
                        max_capacity=20, max_length=1000, auto_id=False),
            FieldSchema(name='vector', dtype=DataType.FLOAT_VECTOR, description='embedding vectors', dim=self.dimension),
        ]
        
     Can someone help me to solve this issue?

**Comment by jaelgu** [comment]
> @shiyu22 I used your solution. But I got the same error.
> 
> I created a collection like below: fields = [ FieldSchema(name='pk', dtype=DataType.INT64, description='ids', max_length=2000, is_primary=True, auto_id=False), FieldSchema(name='text', dtype=DataType.ARRAY, element_type=DataType.VARCHAR, description='metadata', max_capacity=20, max_length=1000, auto_id=False), FieldSchema(name='vector', dtype=DataType.FLOAT_VECTOR, description='embedding vectors', dim=self.dimension), ]
> 
> ```
>  got this error:
>  'tuple' object has no attribute 'embed_query'
>   ('', '')
>     
>  Can someone help me to solve this issue? 
> ```

Hi, `embed_query` is an attribute of langchain's embedding method. It looks like you've used some invalid embedding method. Can you share your code of which embedding used and how you use Milvus via langchain?
