### ISSUE TITLE
[Bug]: [benchmark] slow insertion with low datanodes workload

### ISSUE THREAD

**Issue by AlexeyIvanov8** [milvus-io/milvus#24871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.9
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): Kafka   
- SDK version(e.g. pymilvus v2.0.0rc2): java SDK v2.2.2
- OS(Ubuntu or CentOS): 
- CPU/Memory: see below
- GPU: No
- Others: 

milvuscluster:
  image: milvusdb/milvus:v2.2.9
  components:
    dataCoord:
      replicas: 2
      resources:
        limits:
          cpu: 8
          memory: 16Gi
        requests:
          cpu: 4
          memory: 4Gi
    dataNode:
      replicas: 16
      resources:
        limits:
          cpu: 8
          memory: 32Gi
        requests:
          cpu: 1
          memory: 4Gi
    indexCoord:
      replicas: 1
      resources:
        limits:
          cpu: 8
          memory: 16Gi
        requests:
          cpu: 1
          memory: 1Gi
    indexNode:
      replicas: 8
      resources:
        limits:
          cpu: 16
          memory: 64Gi
        requests:
          cpu: 6
          memory: 4Gi
    queryCoord:
      replicas: 1
      resources:
        limits:
          cpu: 8
          memory: 16Gi
        requests:
          cpu: 2
          memory: 2Gi
    queryNode:
      replicas: 14
      resources:
        limits:
          cpu: 8
          memory: 64Gi
        requests:
          cpu: 8
          memory: 4Gi
    proxy:
      replicas: 4
      resources:
        limits:
          cpu: 10
          memory: 16Gi
        requests:
          cpu: 4
          memory: 8Gi
      serviceType: LoadBalancer
    rootCoord:
      replicas: 1
      resources:
        limits:
          cpu: 8
          memory: 8Gi
        requests:
          cpu: 1
          memory: 1Gi
  config:
    minio:
      bucketName: *
      rootPath: ""
      useSSL: false
    proxy:
      maxTaskNum: 8192
    queryNode:
      dataSync:
        flowGraph:
          maxQueueLength: 1024 # Maximum length of task queue in flowgraph
          maxParallelism: 1024 # Maximum number of tasks executed in parallel in the flowgraph
    scheduler:
      maxReadConcurrentRatio: 50.0 # (0, 100]
      cpuRatio: 120.0 # ratio used to estimate read task cpu usage.
    dataCoord:
      #enableGarbageCollection: true
      channel:
        watchTimeoutInterval: 10
      segment:
        maxSize: 4096
        sealProportion: 0.75
    dataNode:
      flush:
        insertBufSize: 67108864
  dependencies:
    kafka:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
        values:
          defaultReplicationFactor: 2
          replicaCount: 5
          numPartitions: 20
          numNetworkThreads: 10
          numIoThreads: 20
          logRetentionHours: 1
          resources:
            requests:
              cpu: 2
              memory: 2G
            limits:
              cpu: 8
              memory: 16G
          persistence:
            accessMode: ReadWriteOnce
            enabled: true
            size: 50Gi
            storageClass: linstor-hdd
    etcd:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: false
        values:
          persistence:
            storageClass: linstor-hdd
            accessMode: ReadWriteOnce
            enabled: true
            size: 30Gi
          resources:
            limits:
              cpu: "4"
              memory: 16Gi
            requests:
              cpu: 200m
              memory: 1Gi
    storage:
      external: true
      endpoint: *
      secretRef: *
      type: S3
```

### Current Behavior

I'm trying to reach a download target of 200k per second. But the data is slowly stored after getting into Kafka when processing in the datanode begins.

Inserting 40 million vectors takes about 40 minutes with 4 shards, while the proxy throughput is 7.3 million per second.

When the number of shards increases to 16, the throughput of the proxy node drops to 1.4 million per second and full throughput(include datanode processing) slightly increased, but not as expected: 23k(16 shards) vs 18k(4 shards), although I expect x4 increasing of throughput. Also drops insertion latency from 2000ms(4 shards) to >10000ms(16 shards).

I tried to change the settings `dataCoord.channel.watchTimeoutInterval: 10; dataCoord.segment.maxSize: 4096; dataCoord.segment.sealProportion: 0.75; dataNode.flush.insertBufSize: 67108864` but with no visible effect.

Can you tell me if I'm missing something?

Index params: HNSW;IP;M=16;efConstruction=8

Below load tests results:

| shards num | load time(minutes) | batch size | proxy throughput | total save time(minutes) | total number of inserted vectors | insertion per second | latency(ms) |
|------------|--------------------|------------|------------------|--------------------------|----------------------------------|----------------------|-------------|
| 4 | 5 | 700 | 7300000 | 40 | 43000000 | 18600 | 2000 |
| 16 | 5 | 700 | 1424557 | 5 | 7122785 | 23742 | >10000 |

PProf from one of datanodes:

[milvus_datanode_pprof.zip](https://github.com/milvus-io/milvus/files/11736081/milvus_datanode_pprof.zip)

### Expected Behavior

Linear increasing of insertion throughput when add shards/node replicas/anything else.

**Comment by xiaofan-luan** [comment]
think this might be under optimization with @MrPresent-Han

**Comment by xiaofan-luan** [comment]
the major bottleneck might be etcd, as well as the index building speed

**Comment by MrPresent-Han** [comment]
I will have a look at this

**Comment by MrPresent-Han** [comment]
Hello, @AlexeyIvanov8 sorry for delaying replying the issue. I'm starting working on this occasion and hope to keep close touch with you. Can you join our slack channel and communicate this issue in more detail. Your feedback is rather important for milvus development.
slack: https://milvusio.slack.com/archives/CMNHUC371

**Comment by AlexeyIvanov8** [comment]
Hello, @MrPresent-Han
I don't have an account in [https://milvusio.slack.com](https://milvusio.slack.com/) and can't create one(I don't see the button "Create an account"). Could you help me with that? Or I can answer any of your questions here.

**Comment by MrPresent-Han** [comment]
@AlexeyIvanov8 hello, Alex, use the following link:

**Comment by yanliang567** [comment]
keep it

**Comment by yanliang567** [comment]
keep it

**Comment by AlexeyIvanov8** [comment]
Hello, @MrPresent-Han , I answered the questions in slack thread https://milvusio.slack.com/archives/CMNHUC371/p1692778317444749 , is there anything else I can do to help?
