### ISSUE TITLE
[QUESTION] support NSG?

### ISSUE THREAD

**Issue by WenqiJiang** [milvus-io/milvus#249]
I specified MIX_NSG, but it turns out that Milvus built an IVFLAT for me. Also, it seems weird that I need to specify 'nlist' and 'nprobe' for graph search.

Thanks.

**Comment by BossZou** [comment]
Hello, which version are you using? And if you chose a graph index, 'nlist' and 'nprobe' have no effort on searching.

**Comment by WenqiJiang** [comment]
> Hello, which version are you using? And if you choose a graph index, 'nlist' and 'nprobe' have no effect on searching.

It works now, but it has been 2 hours and the building process is still going on. The dataset contains 10 million 512d vectors. We use 32-core CPU with 64G memory. I am not sure if the program is stuck since building IVFPQ with 4096 clusters only takes 5 minutes.

Thanks.

**Comment by tinkerlin** [comment]
If you are using the cpu version, this will take a lot of time. we use KNNG to build NSG and KNNG is built by using IVFFLAT. The stage of build KNNG will be so slow on cpu.
