### ISSUE TITLE
What should I do to enable the Milvus standalone version to run on arm64

### ISSUE THREAD

**Issue by hotwinters** [milvus-io/milvus#24900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.9
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: arm64
- Others:
```

### Current Behavior

i use sudo docker buildx build --platform linux/arm64 -t milvus/arm:arm64 to get milvus arm64 version，but in milvus，i find ./milvus just support x86，Should I compile the executable Milvus program for the arm version from the source code myself, and do I have a Docker image for the arm

**Comment by yanliang567** [comment]
I don't think Milvus has supported running on Arm yet.
@xiaofan-luan  any ideas?

/assign @xiaofan-luan

**Comment by xiaofan-luan** [comment]
you have to compile your own ARM release.
Current docker images are only for X86 servers

**Comment by hotwinters** [comment]
@xiaofan-luan How do I cross compile on x86? I tried it myself, but due to my lack of technical skills, I really don't know how to operate it. Please provide me with a rough idea,thanks

**Comment by xiaofan-luan** [comment]
I'm not an expert. @Presburger have you ever tried to do cross compile?

**Comment by hotwinters** [comment]
i try  but
![image](https://github.com/milvus-io/milvus/assets/34262412/1ef6621a-df44-4053-ae2a-58a87749ef5a)

**Comment by hotwinters** [comment]
too many errors ,i need rewrite Makefiles,and download many third-party dependencies by myself

**Comment by Presburger** [comment]
> I'm not an expert. @Presburger have you ever tried to do cross compile?

no, Cross-compiling will result in a huge amount of work.

**Comment by Presburger** [comment]
> too many errors ,i need rewrite Makefiles,and download many third-party dependencies by myself

It is recommended to open an arm64 server environment to compile, we tested on ubuntu 20.04.

**Comment by hotwinters** [comment]
@Presburger thanks for your help，What should I do to resolve this error report

![image](https://github.com/milvus-io/milvus/assets/34262412/1dd5d77c-949b-4b15-b408-87d76c289bab)

**Comment by sbates130272** [comment]
Hi team Milvus. I am going to add a +1 to the request for arm64 docker images. Many people are working on M1/2 Macbooks these days and would love to test out your cool database on them. Seems like your overall support for Arm64 is still weak but I'm going to leave this here so you know people are asking for non-amd64 images. Thanks!

**Comment by sbates130272** [comment]
Just going to leave this here for now too. Trying to install dependencies on Ubuntu 22.04 for arm64:
```
batesste@bunbeg:~/Projects/milvus$ ./scripts/install_deps.sh
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package clang-format-10
E: Unable to locate package clang-tidy-10
```

**Comment by sbates130272** [comment]
Wow. Well looks like builds on arm64 linux hosts is totally messed up. From what I can tell your installer has put a x86 version of cmake into my /usr/local/bin/. Lucky I work inside a VM that i can recreate from scratch as needed. I think we need a new issue dedicated to arm64 builds but for now I will just leave this here:
```
CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
Modules directory not found in
/usr/local/share/cmake-3.22
CMake Error: Error executing cmake::LoadCache(). Aborting.

abseil/20220623.0: 
abseil/20220623.0: ERROR: Package '5aa47312f09c1a73ef1a0cf71f2e09f8bf3fadad' build failed
abseil/20220623.0: WARN: Build folder /home/batesste/.conan/data/abseil/20220623.0/_/_/build/5aa47312f09c1a73ef1a0cf71f2e09f8bf3fadad/build/Release
ERROR: abseil/20220623.0: Error in build() method, line 119
	cmake.configure()
	ConanException: Error 1 while executing cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/home/batesste/.conan/data/abseil/20220623.0/_/_/build/5aa47312f09c1a73ef1a0cf71f2e09f8bf3fadad/build/Release/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/home/batesste/.conan/data/abseil/20220623.0/_/_/package/5aa47312f09c1a73ef1a0cf71f2e09f8bf3fadad" -DCMAKE_POLICY_DEFAULT_CMP0067="NEW" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/home/batesste/.conan/data/abseil/20220623.0/_/_/build/5aa47312f09c1a73ef1a0cf71f2e09f8bf3fadad/src"
conan install failed
make: *** [Makefile:151: build-3rdparty] Error 1
batesste@bunbeg:~/Projects/milvus$ sudo apt install cmake
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
cmake is already the newest version (3.22.1-1ubuntu1.22.04.1).
The following packages were automatically installed and are no longer required:
  linux-tools-5.15.0-75 linux-tools-5.15.0-75-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
batesste@bunbeg:~/Projects/milvus$ cmake --version
-bash: /usr/local/bin/cmake: cannot execute binary file: Exec format error
batesste@bunbeg:~/Projects/milvus$ file /usr/local/bin/cmake
/usr/local/bin/cmake: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, BuildID[sha1]=df733db12cf95adca59848e53741e1b8f8a03ff0, stripped
```
