### ISSUE TITLE
[Enhancement]: milvus Top1000 performance problem

### ISSUE THREAD

**Issue by sunwsh** [milvus-io/milvus#24914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

	private static final String ID_FIELD = "userID";
	private static final String VECTOR_FIELD = "userFace";
	private static final String TITLE_FIELD = "userTitle";
	private static final String TYPE_FIELD = "userType";
	private static final Integer VECTOR_DIM = 128;
	private static final String INDEX_NAME = "userFaceIndex";
	private static final String SEARCH_PARAM = "{\"nprobe\":20}";
		
System.out.format("========== createCollection: %s\n", collectionName);
		FieldType fieldType1 = FieldType.newBuilder()
				.withName(ID_FIELD)
				.withDescription("user identification")
				.withDataType(DataType.Int64)
				.withPrimaryKey(true)
				.withAutoID(false)
				.build();

		FieldType fieldType2 = FieldType.newBuilder()
				.withName(VECTOR_FIELD)
				.withDescription("face embedding")
				.withDataType(DataType.FloatVector)
				.withDimension(VECTOR_DIM)
				.build();

		FieldType fieldType3 = FieldType.newBuilder()
				.withName(TITLE_FIELD)
				.withDescription("user title")
				.withDataType(DataType.VarChar)
				.withMaxLength(64)
				.build();

		CreateCollectionParam createCollectionReq = CreateCollectionParam.newBuilder()
				.withCollectionName(collectionName)
				.withDescription("customer collection info")
				.withShardsNum(2)
				.withEnableDynamicField(false)
				.addFieldType(fieldType1)
				.addFieldType(fieldType2)
				.addFieldType(fieldType3)
				.build();

		R<RpcStatus> response = milvusClient.withTimeout(timeoutMilliseconds, TimeUnit.MILLISECONDS)
				.createCollection(createCollectionReq);
		if (response.getStatus() != R.Status.Success.getCode()) {
			System.out.println(response);
			return false;
		}
		System.out.format("========== insertColumnsExpr: %s, count: %d, offset: %d\n", collectionName, count, offset);

		List<List<Float>> vectors = generateFloatVectorsV2(count);

		List<Long> bookIds = new ArrayList<>();
		List<String> titleFields = new ArrayList<>();
		for (long i = 0L; i < count; ++i) {
			Long id = (long)(offset + i);
			bookIds.add(id);
			titleFields.add(String.format("profile%d", ((i + offset) % 10)));
		}

		List<InsertParam.Field> fields = new ArrayList<>();
		fields.add(new InsertParam.Field(ID_FIELD, bookIds));
		fields.add(new InsertParam.Field(TITLE_FIELD, titleFields));
		fields.add(new InsertParam.Field(VECTOR_FIELD, vectors));

		InsertParam insertParam = InsertParam.newBuilder()
				.withCollectionName(collectionName)
				.withFields(fields)
				.build();

		R<MutationResult> response = milvusClient.insert(insertParam);
		if (response.getStatus() != R.Status.Success.getCode()) {
			System.out.println(response);
			return false;
		}
		System.out.format("========== createIndex: %s\n", collectionName);
		R<RpcStatus> response = milvusClient.createIndex(CreateIndexParam.newBuilder()
				.withCollectionName(collectionName)
				.withFieldName(VECTOR_FIELD)
				.withIndexName(INDEX_NAME)
				.withIndexType(IndexType.IVF_FLAT)
				.withMetricType(MetricType.L2)
				.withExtraParam("{\"nlist\":512}")
				.withSyncMode(Boolean.TRUE)
				.build());
		if (response.getStatus() != R.Status.Success.getCode()) {
			System.out.println(response);
			return false;
		}
		
               System.out.format("========== search: %s batch: %d topk: %d\n", collectionName, batch, topk);
		List<List<Float>> vectors = generateFloatVectorsV2(batch);

		List<String> outFields = new ArrayList<>();
		outFields.add(ID_FIELD);
		outFields.add(TITLE_FIELD);

		searchParam = SearchParam.newBuilder()
					.withCollectionName(collectionName)
					.withConsistencyLevel(ConsistencyLevelEnum.EVENTUALLY)
					.withMetricType(MetricType.L2)
					.withOutFields(outFields)
					.withTopK(topk)
					.withVectors(vectors)
					.withVectorFieldName(VECTOR_FIELD)
					.withParams(SEARCH_PARAM)
					.build();
             R<SearchResults> response = milvusClient.search(searchParam);

### Why is this needed?

When querying, the input parameter is a vector, and the return parameter setting returns a scalar. Why is the performance so slow when topk > 1000 is set?

		List<String> outFields = new ArrayList<>();
		outFields.add(ID_FIELD);
		outFields.add(TITLE_FIELD);

		searchParam = SearchParam.newBuilder()
					.withCollectionName(collectionName)
					.withConsistencyLevel(ConsistencyLevelEnum.EVENTUALLY)
					.withMetricType(MetricType.L2)
					.withOutFields(outFields)
					.withTopK(1000)
					.withVectors(vectors)
					.withVectorFieldName(VECTOR_FIELD)
					.withParams(SEARCH_PARAM)
					.build();

<html>
<body>
<table class="relative-table confluenceTable stickyTableHeaders" resolved="" style="border-collapse: collapse; margin: 0px; overflow-x: auto; width: 881.307px; padding: 0px;"><thead class="tableFloatingHeaderOriginal"><tr><th class="confluenceTh" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px; background-color: rgb(244, 245, 247); font-weight: bold; color: rgb(23, 43, 77);">采集点</th><th class="confluenceTh" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px; background-color: rgb(244, 245, 247); font-weight: bold; color: rgb(23, 43, 77);">延迟</th><th class="confluenceTh" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px; background-color: rgb(244, 245, 247); font-weight: bold; color: rgb(23, 43, 77);">topK=1</th><th class="confluenceTh" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px; background-color: rgb(244, 245, 247); font-weight: bold; color: rgb(23, 43, 77);">topK=1000</th><th colspan="1" class="confluenceTh" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px; background-color: rgb(244, 245, 247); font-weight: bold; color: rgb(23, 43, 77);">topk=2000</th><th colspan="1" class="confluenceTh" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px; background-color: rgb(244, 245, 247); font-weight: bold; color: rgb(23, 43, 77);">topk=5000</th></tr></thead><colgroup><col style="width: 167.571px;"><col style="width: 154.673px;"><col style="width: 145.298px;"><col style="width: 137.102px;"><col style="width: 137.102px;"><col style="width: 138.651px;"></colgroup><tbody><tr><td rowspan="4" class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;"><p style="margin: 0px; padding: 0px;">客户端</p><p style="margin: 10px 0px 0px; padding: 0px;">req： withVectors</p><p style="margin: 10px 0px 0px; padding: 0px;">resp：(返回向量id)</p></td><td class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">P50</td><td class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">4.1ms</td><td class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">6.8ms</td><td colspan="1" class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">9.0ms</td><td colspan="1" class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">15.9ms</td></tr><tr><td class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">P90</td><td class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">4.6ms</td><td class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">7.6ms</td><td colspan="1" class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">10.3ms</td><td colspan="1" class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">18.5ms</td></tr><tr><td class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">P95</td><td class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">5.0ms</td><td class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">8.3ms</td><td colspan="1" class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">11.1ms</td><td colspan="1" class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">19.5ms</td></tr><tr><td class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">P99</td><td class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">5.9ms</td><td class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">10.5ms</td><td colspan="1" class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">13.4ms</td><td colspan="1" class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">21.9ms</td></tr><tr><td rowspan="4" class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;"><p style="margin: 0px; padding: 0px;">客户端</p><p style="margin: 10px 0px 0px; padding: 0px;">req： withVectors</p><p style="margin: 10px 0px 0px; padding: 0px;">resp:</p><p style="margin: 10px 0px 0px; padding: 0px;">(向量id + 其他属性)</p></td><td colspan="1" class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">P50</td><td colspan="1" class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">4.28ms</td><td colspan="1" class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">58ms</td><td colspan="1" class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">212ms</td><td colspan="1" class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;"><br></td></tr><tr><td colspan="1" class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">P90</td><td colspan="1" class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">4.8ms</td><td colspan="1" class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">72ms</td><td colspan="1" class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">275ms</td><td colspan="1" class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;"><br></td></tr><tr><td colspan="1" class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">P95</td><td colspan="1" class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">5.3ms</td><td colspan="1" class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">76ms</td><td colspan="1" class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">342ms</td><td colspan="1" class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;"><br></td></tr><tr><td colspan="1" class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">P99</td><td colspan="1" class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">6.3ms</td><td colspan="1" class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">99ms</td><td colspan="1" class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;">647ms</td><td colspan="1" class="confluenceTd" style="border: 1px solid rgb(193, 199, 208); padding: 7px 10px; vertical-align: top; text-align: left; min-width: 8px;"><br style="color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
</body>
</html>

**Comment by xiaofan-luan** [comment]
@sunwsh 
how long is your varchar avg size?

**Comment by xiaofan-luan** [comment]
typical size is less than 64

**Comment by zhagnlu** [comment]
@sunwsh Could you provide more info about: 1. milvus code version/branch  2. the test base data size( how many rows in your collections) 3.  the  其他属性 including which columns

**Comment by sunwsh** [comment]
1. milvus code version/branch = 2.2.8
2.  vector number = 100w
3.  VECTOR_DIM = 128， nlist = 500， ivfflat

**Comment by xiaofan-luan** [comment]
I think the overall performance looks ok to me. 
retrieval vector out is very slow -> 2.3 improves  it. 
Other than that the other performance is very reasonable

**Comment by xiaofan-luan** [comment]
> 1. milvus code version/branch = 2.2.8
> 2. vector number = 100w
> 3. VECTOR_DIM = 128， nlist = 500， ivfflat

What is the estimation though? We can try to see if it is achievable

**Comment by sunwsh** [comment]
expectation
