### ISSUE TITLE
[Feature]: Support exists or json_contains for json filtering

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#24932]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

{"widget": {
    "debug": "on",
    "window": {
        "title": "Sample Konfabulator Widget",
        "name": "main_window",
        "width": 500,
        "height": 500
    },
}}    

for the json above, figure out if widget.debug is in.
the expression could be json_contains(json, "widget.debug") or exist json["widget.debug"]
Need to do more investigation on which is better

**Comment by xiaofan-luan** [comment]
already supported, need document

**Comment by dcalsky** [comment]
Do you mind sharing the document for this? As far as I tested, `json_contains` can't be used for checking existing of an object key.
