### ISSUE TITLE
[Bug]: collection.search/query not work 

### ISSUE THREAD

**Issue by j506130598** [milvus-io/milvus#24930]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus v2.2.11
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

<img width="1120" alt="微信截图_20230615201132" src="https://github.com/milvus-io/milvus/assets/42927502/f449f4c6-e442-4802-be26-d32a23fcca5b">
<img width="911" alt="微信截图_20230615201210" src="https://github.com/milvus-io/milvus/assets/42927502/a1e7a9b9-6938-48a5-9431-2a51da77f6bf">

在图一中，可以搜索到数据库中存在application（json类型）列中有两条数据：’对内机器人‘：’true‘和’对外机器人‘：’true‘
但是在图二中使用application['对外机器人'] == 'true'的语句搜索却搜不出结果
我测试过==、like等方法都无法匹配出结果
另外抱怨一下，pythonsdk升级到最新版本依旧无法使用json_contains，字符串字段也不支持%str%这样的全文匹配格式，感觉非常难用

### Expected Behavior

在调用collection.query("application['对外机器人'] == 'true'")

**Comment by xiaofan-luan** [comment]
we don't test chinese charactor yet. 
but we could work on investigate the reason

**Comment by yah01** [comment]
Hi @j506130598, we just published a new [PyMilvus release ](https://github.com/milvus-io/pymilvus/releases/tag/v2.2.12), and now it supports to query/search with Chinese, **but you need to re-insert your data**.

**Comment by xiaofan-luan** [comment]
@yah01 Fast Reply!

**Comment by xiaocai2333** [comment]
Hi @j506130598 , json_contains is only supported on master. you need to wait master release.
