### ISSUE TITLE
[Enhancement]: Support Bulkinsert in new Restful API

### ISSUE THREAD

**Issue by soothing-rain** [milvus-io/milvus#24947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

We are releasing the new restful API in couple weeks and we will support bulkinsert via restfulAPI after that

**Comment by jaime0815** [comment]
related to https://github.com/milvus-io/milvus/issues/24746

**Comment by xiaofan-luan** [comment]
keep it

**Comment by xiaofan-luan** [comment]
keep it.
I believe this is an important feature for RestfulAP
