### ISSUE TITLE
[Bug]:  A lot of CollectionNotExits logs after restart

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#24940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.9
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Other components can not find the collection of dopping state during GC stage after restart, which will lead to GC failure for this collection.

reproduce step :
1. create collection A
2. drop collection A
3. create collection A
4. restart milvus immediately

**Comment by xiaofan-luan** [comment]
Good catch!
