### ISSUE TITLE
[Feature]: Support Azure

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#24944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

We want Milvus to work well with Azure cloud.

This project including the following task:

1. Support Azure blog storage -> Including IAM 
2. Adapt with Azure EKS
3. Test performance on Azure
4.  Generate a document about how to deploy on Azure

**Comment by jaime0815** [comment]
related to #22276
