### ISSUE TITLE
[Enhancement]: Add a feature similar to `explain with tracing`

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#24958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Add a feature similar to `explain with tracing`
To be specific, one could find the whole procedure of a `search` request execution:
- Which components did this request go through
- Which segments participated in this search
- IDs / offsets of each partial result
- Step by step time consumed

### Why is this needed?

With this feature, it will be more convenient to perform debug and performance tuning

**Comment by congqixia** [comment]
/reopen
keep it

**Comment by xiaofan-luan** [comment]
keep it
nice feature
