### ISSUE TITLE
[Bug]:  corruption detected: short output block

### ISSUE THREAD

**Issue by devenami** [milvus-io/milvus#24967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.9
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.9
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 4/8Gi
- GPU: 
- Others:
```

### Current Behavior

dataNode crash when compaction

### Expected Behavior

normal running

### Milvus Log

[2023/06/17 10:59:31.298 +00:00] [INFO] [datanode/compaction_executor.go:91] ["start to execute compaction"] [planID=442236512587492959]
[2023/06/17 10:59:31.298 +00:00] [INFO] [datanode/compactor.go:425] ["compaction start"] [planID=442236512587492959] ["wait duration"=73.515µs]
[2023/06/17 10:59:31.298 +00:00] [INFO] [datanode/compaction_executor.go:91] ["start to execute compaction"] [planID=442236512587492960]
[2023/06/17 10:59:31.298 +00:00] [INFO] [datanode/compactor.go:425] ["compaction start"] [planID=442236512587492960] ["wait duration"=39.924µs]
[2023/06/17 10:59:31.298 +00:00] [INFO] [datanode/compactor.go:450] ["compaction start"] [planID=442236512587492959] ["timeout in seconds"=300]
[2023/06/17 10:59:31.298 +00:00] [INFO] [datanode/compactor.go:185] ["mergeDeltalogs end"] [planID=442236512587492959] ["number of pks to compact in insert logs"=0] ["elapse in ms"=0.005131]
[2023/06/17 10:59:31.298 +00:00] [INFO] [datanode/compactor.go:450] ["compaction start"] [planID=442236512587492960] ["timeout in seconds"=300]
[2023/06/17 10:59:31.298 +00:00] [INFO] [datanode/compactor.go:185] ["mergeDeltalogs end"] [planID=442236512587492960] ["number of pks to compact in insert logs"=0] ["elapse in ms"=0.000535]
[2023/06/17 10:59:34.121 +00:00] [INFO] [datanode/compactor.go:628] ["download deltalogs elapse in ms"] [planID=442236512587492959] [elapse=0.025007]
[2023/06/17 10:59:34.121 +00:00] [INFO] [datanode/compactor.go:567] ["inject elapse in ms"] [planID=442236512587492959] [elapse=0.010096]
panic: corruption detected: short output block

goroutine 26326 [running]:
github.com/apache/arrow/go/v8/parquet/compress.zstdCodec.Decode({}, {0xc009a76000, 0xc001801488?, 0x100040}, {0xc006e4c000, 0xe5a38, 0x160781})
        /go/pkg/mod/github.com/apache/arrow/go/v8@v8.0.0-20220322092137-778b1772fd20/parquet/compress/zstd.go:57 +0x73
github.com/apache/arrow/go/v8/parquet/file.(*serializedPageReader).decompress(0xc00090d1d0, 0xe5a38, {0xc009a76000, 0x100007, 0x100040})
        /go/pkg/mod/github.com/apache/arrow/go/v8@v8.0.0-20220322092137-778b1772fd20/parquet/file/page_reader.go:403 +0x166
github.com/apache/arrow/go/v8/parquet/file.(*serializedPageReader).Next(0xc00090d1d0)
        /go/pkg/mod/github.com/apache/arrow/go/v8@v8.0.0-20220322092137-778b1772fd20/parquet/file/page_reader.go:542 +0x1085
github.com/apache/arrow/go/v8/parquet/file.(*columnChunkReader).readNewPage(0xc0016d8900)
        /go/pkg/mod/github.com/apache/arrow/go/v8@v8.0.0-20220322092137-778b1772fd20/parquet/file/column_reader.go:226 +0x33
github.com/apache/arrow/go/v8/parquet/file.(*columnChunkReader).HasNext(...)
        /go/pkg/mod/github.com/apache/arrow/go/v8@v8.0.0-20220322092137-778b1772fd20/parquet/file/column_reader.go:193
github.com/apache/arrow/go/v8/parquet/file.(*columnChunkReader).readBatch(0xc0016d8900, 0x17d06, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0xc0016cff90)
        /go/pkg/mod/github.com/apache/arrow/go/v8@v8.0.0-20220322092137-778b1772fd20/parquet/file/column_reader.go:473 +0x1b3
github.com/apache/arrow/go/v8/parquet/file.(*FixedLenByteArrayColumnChunkReader).ReadBatch(0x23c000?, 0x23b890?, {0xc006aa4000?, 0x1000255ea2b?, 0x7f235f1c2418?}, {0x0?, 0x7f258d76a5b8?, 0x23c000?}, {0x0, 0x0, ...})
        /go/pkg/mod/github.com/apache/arrow/go/v8@v8.0.0-20220322092137-778b1772fd20/parquet/file/column_reader_types.gen.go:296 +0x87
github.com/milvus-io/milvus/internal/storage.ReadDataFromAllRowGroups[...](0xc0001b3340, {0xc006aa4000, 0x17d06, 0x17d06}, 0x0, 0xc0016d00f0)
        /go/src/github.com/milvus-io/milvus/internal/storage/payload_reader.go:368 +0x1a6
github.com/milvus-io/milvus/internal/storage.(*PayloadReader).GetFloatVectorFromPayload(0xc001800990)
        /go/src/github.com/milvus-io/milvus/internal/storage/payload_reader.go:325 +0xb2
github.com/milvus-io/milvus/internal/storage.(*InsertCodec).DeserializeInto(0x44bac10?, {0xc001a93740, 0x8, 0xc0016d04d0?}, 0x14d4f13?, 0xc0036c9760)
        /go/src/github.com/milvus-io/milvus/internal/storage/data_codec.go:788 +0x19ac
github.com/milvus-io/milvus/internal/storage.(*InsertCodec).DeserializeAll(0xc11b82656f461459?, {0xc001a93740, 0x8, 0x8})
        /go/src/github.com/milvus-io/milvus/internal/storage/data_codec.go:533 +0xbc
github.com/milvus-io/milvus/internal/storage.(*InsertCodec).Deserialize(...)
        /go/src/github.com/milvus-io/milvus/internal/storage/data_codec.go:867
github.com/milvus-io/milvus/internal/storage.NewInsertBinlogIterator({0xc001a93740?, 0x44bc3a0?, 0x5b86160?}, 0x64, 0x5)
        /go/src/github.com/milvus-io/milvus/internal/storage/binlog_iterator.go:67 +0x55
github.com/milvus-io/milvus/internal/datanode.(*compactionTask).merge(0xc0036fe160, {0x44bc3a0, 0xc00378a5a0}, {0xc002d00300, 0x10, 0x0?}, 0x4f21c0?, 0xc00003126f?, 0xc003597380, 0xc0036ecc90)
        /go/src/github.com/milvus-io/milvus/internal/datanode/compactor.go:328 +0x816
github.com/milvus-io/milvus/internal/datanode.(*compactionTask).compact(0xc0036fe160)
        /go/src/github.com/milvus-io/milvus/internal/datanode/compactor.go:641 +0x1427
github.com/milvus-io/milvus/internal/datanode.(*compactionExecutor).executeTask(0xc00057e370, {0x44c7de8, 0xc0036fe160})
        /go/src/github.com/milvus-io/milvus/internal/datanode/compaction_executor.go:93 +0x183
created by github.com/milvus-io/milvus/internal/datanode.(*compactionExecutor).executeWithState
        /go/src/github.com/milvus-io/milvus/internal/datanode/compaction_executor.go:72 +0x95

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```gfm
> - Milvus version: 2.2.9
> - Deployment mode(standalone or cluster): cluster
> - MQ type(rocksmq, pulsar or kafka): pulsar
> - SDK version(e.g. pymilvus v2.0.0rc2): 2.2.9
> - OS(Ubuntu or CentOS): CentOS
> - CPU/Memory: 4/8Gi
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> dataNode crash when compaction
> 
> ### Expected Behavior
> normal running
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> [2023/06/17 10:59:31.298 +00:00] [INFO] [datanode/compaction_executor.go:91] ["start to execute compaction"] [planID=442236512587492959] [2023/06/17 10:59:31.298 +00:00] [INFO] [datanode/compactor.go:425] ["compaction start"] [planID=442236512587492959] ["wait duration"=73.515µs] [2023/06/17 10:59:31.298 +00:00] [INFO] [datanode/compaction_executor.go:91] ["start to execute compaction"] [planID=442236512587492960] [2023/06/17 10:59:31.298 +00:00] [INFO] [datanode/compactor.go:425] ["compaction start"] [planID=442236512587492960] ["wait duration"=39.924µs] [2023/06/17 10:59:31.298 +00:00] [INFO] [datanode/compactor.go:450] ["compaction start"] [planID=442236512587492959] ["timeout in seconds"=300] [2023/06/17 10:59:31.298 +00:00] [INFO] [datanode/compactor.go:185] ["mergeDeltalogs end"] [planID=442236512587492959] ["number of pks to compact in insert logs"=0] ["elapse in ms"=0.005131] [2023/06/17 10:59:31.298 +00:00] [INFO] [datanode/compactor.go:450] ["compaction start"] [planID=442236512587492960] ["timeout in seconds"=300] [2023/06/17 10:59:31.298 +00:00] [INFO] [datanode/compactor.go:185] ["mergeDeltalogs end"] [planID=442236512587492960] ["number of pks to compact in insert logs"=0] ["elapse in ms"=0.000535] [2023/06/17 10:59:34.121 +00:00] [INFO] [datanode/compactor.go:628] ["download deltalogs elapse in ms"] [planID=442236512587492959] [elapse=0.025007] [2023/06/17 10:59:34.121 +00:00] [INFO] [datanode/compactor.go:567] ["inject elapse in ms"] [planID=442236512587492959] [elapse=0.010096] panic: corruption detected: short output block
> 
> goroutine 26326 [running]: github.com/apache/arrow/go/v8/parquet/compress.zstdCodec.Decode({}, {0xc009a76000, 0xc001801488?, 0x100040}, {0xc006e4c000, 0xe5a38, 0x160781}) /go/pkg/mod/github.com/apache/arrow/go/v8@v8.0.0-20220322092137-778b1772fd20/parquet/compress/zstd.go:57 +0x73 github.com/apache/arrow/go/v8/parquet/file.(*serializedPageReader).decompress(0xc00090d1d0, 0xe5a38, {0xc009a76000, 0x100007, 0x100040}) /go/pkg/mod/github.com/apache/arrow/go/v8@v8.0.0-20220322092137-778b1772fd20/parquet/file/page_reader.go:403 +0x166 github.com/apache/arrow/go/v8/parquet/file.(*serializedPageReader).Next(0xc00090d1d0) /go/pkg/mod/github.com/apache/arrow/go/v8@v8.0.0-20220322092137-778b1772fd20/parquet/file/page_reader.go:542 +0x1085 github.com/apache/arrow/go/v8/parquet/file.(*columnChunkReader).readNewPage(0xc0016d8900) /go/pkg/mod/github.com/apache/arrow/go/v8@v8.0.0-20220322092137-778b1772fd20/parquet/file/column_reader.go:226 +0x33 github.com/apache/arrow/go/v8/parquet/file.(*columnChunkReader).HasNext(...) /go/pkg/mod/github.com/apache/arrow/go/v8@v8.0.0-20220322092137-778b1772fd20/parquet/file/column_reader.go:193 github.com/apache/arrow/go/v8/parquet/file.(*columnChunkReader).readBatch(0xc0016d8900, 0x17d06, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0xc0016cff90) /go/pkg/mod/github.com/apache/arrow/go/v8@v8.0.0-20220322092137-778b1772fd20/parquet/file/column_reader.go:473 +0x1b3 github.com/apache/arrow/go/v8/parquet/file.(*FixedLenByteArrayColumnChunkReader).ReadBatch(0x23c000?, 0x23b890?, {0xc006aa4000?, 0x1000255ea2b?, 0x7f235f1c2418?}, {0x0?, 0x7f258d76a5b8?, 0x23c000?}, {0x0, 0x0, ...}) /go/pkg/mod/github.com/apache/arrow/go/v8@v8.0.0-20220322092137-778b1772fd20/parquet/file/column_reader_types.gen.go:296 +0x87 github.com/milvus-io/milvus/internal/storage.ReadDataFromAllRowGroups[...](0xc0001b3340, {0xc006aa4000, 0x17d06, 0x17d06}, 0x0, 0xc0016d00f0) /go/src/github.com/milvus-io/milvus/internal/storage/payload_reader.go:368 +0x1a6 github.com/milvus-io/milvus/internal/storage.(*PayloadReader).GetFloatVectorFromPayload(0xc001800990) /go/src/github.com/milvus-io/milvus/internal/storage/payload_reader.go:325 +0xb2 github.com/milvus-io/milvus/internal/storage.(*InsertCodec).DeserializeInto(0x44bac10?, {0xc001a93740, 0x8, 0xc0016d04d0?}, 0x14d4f13?, 0xc0036c9760) /go/src/github.com/milvus-io/milvus/internal/storage/data_codec.go:788 +0x19ac github.com/milvus-io/milvus/internal/storage.(*InsertCodec).DeserializeAll(0xc11b82656f461459?, {0xc001a93740, 0x8, 0x8}) /go/src/github.com/milvus-io/milvus/internal/storage/data_codec.go:533 +0xbc github.com/milvus-io/milvus/internal/storage.(*InsertCodec).Deserialize(...) /go/src/github.com/milvus-io/milvus/internal/storage/data_codec.go:867 github.com/milvus-io/milvus/internal/storage.NewInsertBinlogIterator({0xc001a93740?, 0x44bc3a0?, 0x5b86160?}, 0x64, 0x5) /go/src/github.com/milvus-io/milvus/internal/storage/binlog_iterator.go:67 +0x55 github.com/milvus-io/milvus/internal/datanode.(*compactionTask).merge(0xc0036fe160, {0x44bc3a0, 0xc00378a5a0}, {0xc002d00300, 0x10, 0x0?}, 0x4f21c0?, 0xc00003126f?, 0xc003597380, 0xc0036ecc90) /go/src/github.com/milvus-io/milvus/internal/datanode/compactor.go:328 +0x816 github.com/milvus-io/milvus/internal/datanode.(*compactionTask).compact(0xc0036fe160) /go/src/github.com/milvus-io/milvus/internal/datanode/compactor.go:641 +0x1427 github.com/milvus-io/milvus/internal/datanode.(*compactionExecutor).executeTask(0xc00057e370, {0x44c7de8, 0xc0036fe160}) /go/src/github.com/milvus-io/milvus/internal/datanode/compaction_executor.go:93 +0x183 created by github.com/milvus-io/milvus/internal/datanode.(*compactionExecutor).executeWithState /go/src/github.com/milvus-io/milvus/internal/datanode/compaction_executor.go:72 +0x95
> 
> ### Anything else?
> _No response_

Seems that the file has been corrupted.
Did you ever do anything on your minio or the file?
If not could you upload the load with issue?

**Comment by xiaofan-luan** [comment]
to recover you will need to find the log with error and remove.
But the root cause remain to be investigated

**Comment by xiaofan-luan** [comment]
if you can offer datacoord log, datanode log, and all the files in the compacted segment.
We can help you to located the corrupted log

**Comment by devenami** [comment]
> if you can offer datacoord log, datanode log, and all the files in the compacted segment. We can help you to located the corrupted log

thx, i restart minio server, the problem has been soloved
