### ISSUE TITLE
[Bug]:  fail to search on all shard leaders, err=All attempts results: attempt #1:code: UnexpectedError, error: fail to Search, QueryNode ID=2, reason=Search 2 failed, reason [UnexpectedError] [json.exception.out_of_range.403] key 'ef' not found err %!w(<nil>) attempt #2:context canceled

### ISSUE THREAD

**Issue by jxyxiangyu** [milvus-io/milvus#24987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.8
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):milvus-sdk-java 2.2.6
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

when I search vector from mivlus, throws error
But when I search the other collection, not throws this error

**Comment by xiaofan-luan** [comment]
you have to speficy ef paramers when search for old releases

**Comment by yanliang567** [comment]
/assign @jxyxiangyu 
could you please share the code snippet to reproduce this issue?

/unassign
