### ISSUE TITLE
[Bug]: Milvus not starting on Oracle Linux 

### ISSUE THREAD

**Issue by davorbettercare** [milvus-io/milvus#24993]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.1
- Deployment mode(standalone or cluster): docker compose
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Oracle Linux 8
- CPU/Memory: 4CPU/32G
- GPU: 
- Others: docker 24.0.2
```

### Current Behavior

Not even starting, bacislly no stdout
```docker compose logs -f milvus
milvus-standalone  | 2023/06/19 07:01:06 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
```
this is only output

### Expected Behavior

info, warning, error stdout...

### Steps To Reproduce

```markdown
Copy docker-compose.yml file from https://milvus.io/docs/configure-docker.md and start with docker compose up -d
```

**Comment by yanliang567** [comment]
@davorbettercare The community did not test it on Oracle Linux, what's the version of your docker? Was your cpu instruction set listed in the support list here: https://milvus.io/docs/prerequisite-docker.md

/assign @davorbettercare

**Comment by davorbettercare** [comment]
Yes all CPU instruction are available.
Docker version 24.0.2

**Comment by yanliang567** [comment]
/assign @LoveEachDay 
any ideas?

**Comment by davorbettercare** [comment]
I have just noticed an issue.
Etcd has issues assigning port.

And Milvus is just waiting etcd.
I would recommend adding some stdout that Milvus is waiting etcd

**Comment by davorbettercare** [comment]
I was able to solve this. NAT Proxy was causing me an issues. After disabling proxy in docker, it started working.
Only suggestion would be to add somekind of stdout in milvus that is waiting for etcd.

**Comment by davorbettercare** [comment]
I was able to solve this. NAT Proxy was causing me an issues. After disabling proxy in docker, it started working.
Only suggestion would be to add somekind of stdout in milvus that is waiting for etcd.

**Comment by yanliang567** [comment]
great to know that, and appreciated your sharing solution.
