### ISSUE TITLE
[Bug]: Search iterator results are sometimes missing

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#25022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230620-247f1170
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0.dev75
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search iterator results are sometimes missing.
I don't set radius and range_filter. Is it related to default radius?

1. search with expression:
```
>       assert len(set(pk_list)) == 1000
E       assert 993 == 1000
E         +993
E         -1000
```

2. search without expression:
```
>       assert len(set(pk_list)) == default_nb
E       assert 2999 == 3000
E         +2999
E         -3000
```

### Expected Behavior

return all results

### Steps To Reproduce

```markdown
1. create a collection
2. insert 3000 data
3. create index L2, load
*4. use expression to chose 1000 data
5. search iterator 
6. count the total results
```

### Milvus Log

```python
@pytest.mark.tags(CaseLabel.L1)
    @pytest.mark.parametrize("metrics", ct.float_metrics[:1])
    def test_search_iterator_with_expression(self, metrics):
        """
        target: test search iterator normal
        method: 1. search iterator
                2. check the result, expect pk not repeat and meet the expr requirements
        expected: search successfully
        """
        # 1. initialize with data
        limit = 100
        dim = 128
        collection_w = self.init_collection_general(prefix, True, dim=dim, is_index=False)[0]
        collection_w.create_index(field_name, {"metric_type": metrics})
        collection_w.load()
        # 2. search iterator
        search_params = {"metric_type": metrics}
        expression = "1000.0 <= float < 2000.0"
        search_iterator = collection_w.search_iterator(vectors[:1], field_name, search_params,
                                                       limit, output_fields=['float'], expr=expression)[0]
        # 3. check the result
        page_idx = 0
        pk_list = []
        while True:
            res = search_iterator.next()
            if len(res[0]) == 0:
                log.info("search iteration finished, close")
                search_iterator.close()
                break
            for i in range(len(res[0])):
                # log.info(res[0][i])
                pk_list.append(res[0][i].id)
            page_idx += 1
        log.info(len(pk_list))
        assert len(set(pk_list)) == 1000
```

**Comment by shunjiezhao** [comment]
Hello @NicoYuan1986 , i test in your pr https://github.com/milvus-io/milvus/pull/25039 and pass ,can you test my pr again 😃 
https://github.com/milvus-io/pymilvus/pull/1551

**Comment by xiaofan-luan** [comment]
> Hello @NicoYuan1986 , i test in your pr #25039 and pass ,can you test my pr again 😃 [milvus-io/pymilvus#1551](https://github.com/milvus-io/pymilvus/pull/1551)

Wow! good job

**Comment by NicoYuan1986** [comment]
> Hello @NicoYuan1986 , i test in your pr #25039 and pass ,can you test my pr again 😃 [milvus-io/pymilvus#1551](https://github.com/milvus-io/pymilvus/pull/1551)

Thanks for your help! 🌻 
I will test it later.

**Comment by XuanYang-cn** [comment]
should be fixed at dev 79

**Comment by MrPresent-Han** [comment]
I checked the radius and range_filter for every iteration round, showed as following:
{'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 0.0}}
page1--------page_size100-----------------
{'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 28.89669418334961}}
page2--------page_size100-----------------
{'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.029569625854492}}
page3--------page_size100-----------------
{'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.11724281311035}}
page4--------page_size100-----------------
{'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.192583084106445}}
page5--------page_size100-----------------
{'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.26207733154297}}
page6--------page_size100-----------------
{'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.34310531616211}}
page7--------page_size100-----------------
{'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.436540603637695}}
page8--------page_size100-----------------
{'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.52791404724121}}
page9--------page_size100-----------------
{'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.683496475219727}}
page10--------page_size97-----------------
{'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 30.41278648376465}}


it seems that the radius and range_filter were updated normally, but it still lacks 3 items.

**Comment by shunjiezhao** [comment]
> I checked the radius and range_filter for every iteration round, showed as following: {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 0.0}} page1--------page_size100----------------- {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 28.89669418334961}} page2--------page_size100----------------- {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.029569625854492}} page3--------page_size100----------------- {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.11724281311035}} page4--------page_size100----------------- {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.192583084106445}} page5--------page_size100----------------- {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.26207733154297}} page6--------page_size100----------------- {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.34310531616211}} page7--------page_size100----------------- {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.436540603637695}} page8--------page_size100----------------- {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.52791404724121}} page9--------page_size100----------------- {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.683496475219727}} page10--------page_size97----------------- {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 30.41278648376465}}
> 
> it seems that the radius and range_filter were updated normally, but it still lacks 3 items.

Good afternoon,I just noticed that I didn't del the skip Tag in pytest, i will see now

**Comment by xiaofan-luan** [comment]
> I checked the radius and range_filter for every iteration round, showed as following: {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 0.0}} page1--------page_size100----------------- {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 28.89669418334961}} page2--------page_size100----------------- {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.029569625854492}} page3--------page_size100----------------- {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.11724281311035}} page4--------page_size100----------------- {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.192583084106445}} page5--------page_size100----------------- {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.26207733154297}} page6--------page_size100----------------- {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.34310531616211}} page7--------page_size100----------------- {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.436540603637695}} page8--------page_size100----------------- {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.52791404724121}} page9--------page_size100----------------- {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.683496475219727}} page10--------page_size97----------------- {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 30.41278648376465}}
> 
> it seems that the radius and range_filter were updated normally, but it still lacks 3 items.
@shunjiezhao @MrPresent-Han 
could this be as expected? 
because range search is not exact match but approximate search

**Comment by MrPresent-Han** [comment]
> I checked the radius and range_filter for every iteration round, showed as following: {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 0.0}} page1--------page_size100----------------- {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 28.89669418334961}} page2--------page_size100----------------- {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.029569625854492}} page3--------page_size100----------------- {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.11724281311035}} page4--------page_size100----------------- {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.192583084106445}} page5--------page_size100----------------- {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.26207733154297}} page6--------page_size100----------------- {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.34310531616211}} page7--------page_size100----------------- {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.436540603637695}} page8--------page_size100----------------- {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.52791404724121}} page9--------page_size100----------------- {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 29.683496475219727}} page10--------page_size97----------------- {'metric_type': 'L2', 'params': {'radius': 999999.0, 'range_filter': 30.41278648376465}}
> 
> it seems that the radius and range_filter were updated normally, but it still lacks 3 items. @shunjiezhao @MrPresent-Han could this be as expected? because range search is not exact match but approximate search

Perhaps, but according to [NicoYuan1986](https://github.com/NicoYuan1986) the same code out of pytest can correctly get 1000 items. This is a little weird

**Comment by xiaofan-luan** [comment]
> 

Try larger dataset and result might be different

**Comment by MrPresent-Han** [comment]
> Try larger dataset and result might be different

It's true that hnsw can overlook minor set of the result. But the same code I mentioned can get 1000 items every time, whereas the code pytest will get 993~997 items every time. Although we can enlarge the dataset and verify that range search may leave some items, we still cannot explain this phenomenon. 

[NicoYuan1986](https://github.com/NicoYuan1986) has tested various variables and the only left possibility is the DataFrame used by pytest

**Comment by xiaofan-luan** [comment]
> > Try larger dataset and result might be different
> 
> It's true that hnsw can overlook minor set of the result. But the same code I mentioned can get 1000 items **every time**, whereas the code pytest will get 993~997 items **every time**. Although we can enlarge the dataset and verify that range search may leave some items, we still cannot explain this phenomenon.
> 
> [NicoYuan1986](https://github.com/NicoYuan1986) has tested various variables and the only left possibility is the DataFrame used by pytest

understand!
If you get 10000+ items and try to iterate top 1000 you should definitely get 1000 results.

**Comment by shunjiezhao** [comment]
![image](https://github.com/milvus-io/milvus/assets/90906581/3927ecbf-2fa6-46b8-8cf1-e5445b4674e1)
i extract id not in [1000,2000), and try to query all data。
``` python

class TestSearchIterator(TestcaseBase):
    """ Test case of search iterator """
    @pytest.mark.tags(CaseLabel.L2)
    @pytest.mark.parametrize("metrics", ct.float_metrics[:1])
    def test_search_iterator_with_expression(self, metrics):
        """
        target: test search iterator normal
        method: 1. search iterator
                2. check the result, expect pk not repeat and meet the expr requirements
        expected: search successfully
        """
        # 1. initialize with data
        limit = 100
        dim = 128
        collection_w = self.init_collection_general(prefix, True, dim=dim, is_index=False)[0]
        collection_w.create_index(field_name, {"metric_type": metrics})
        collection_w.load()
        # 2. search iterator
        search_params = {"metric_type": metrics}
        expression = "1000.0 <= float < 2000.0"
        search_iterator = collection_w.search_iterator(vectors[:1], field_name, search_params,
                                                       limit, output_fields=['float'], expr=expression)[0]
        # 3. check the result
        page_idx = 0
        pk_list = []
        while True:
            res = search_iterator.next()
            if len(res[0]) == 0:
                log.info("search iteration finished, close")
                search_iterator.close()
                break
            
            for i in range(len(res[0])):
                pk_list.append(res[0][i].id)
            page_idx += 1
        log.info(len(pk_list))
        notExistId=[]
        pk_set = set(pk_list)
        if len(pk_set) == 1000:
            return

        for i in range(1000,2000):
            if i not in pk_set:
                notExistId.append(i)

        print("find not exist id", notExistId)
        expression = f"float not in {notExistId} "
        # print("search with expression", expression, 'limit', limit, 'param', search_param , 'name',field_name)
        # res =collection_w.search(vectors[:1], field_name, search_params, limit, expr=expression)
        # print('search result:',res[0])

        print("query with expression", expression)
        res = collection_w.query(expression, output_fields=['float'])
        pk_list = []
        for i in range(len(res[0])):
            pk_list.append(res[0][i]['int64'])
        # print(res[0][-1])
        se = set(pk_list)
        for i in range(0,2000):
            if i not in se:
                print(f'{i} not in query result')
        assert False

```

**Comment by xiaofan-luan** [comment]
> ![image](https://user-images.githubusercontent.com/90906581/247524837-3927ecbf-2fa6-46b8-8cf1-e5445b4674e1.png) i extract id not in [1000,2000), and try to query all data。
> 
> ```python
> class TestSearchIterator(TestcaseBase):
>     """ Test case of search iterator """
>     @pytest.mark.tags(CaseLabel.L2)
>     @pytest.mark.parametrize("metrics", ct.float_metrics[:1])
>     def test_search_iterator_with_expression(self, metrics):
>         """
>         target: test search iterator normal
>         method: 1. search iterator
>                 2. check the result, expect pk not repeat and meet the expr requirements
>         expected: search successfully
>         """
>         # 1. initialize with data
>         limit = 100
>         dim = 128
>         collection_w = self.init_collection_general(prefix, True, dim=dim, is_index=False)[0]
>         collection_w.create_index(field_name, {"metric_type": metrics})
>         collection_w.load()
>         # 2. search iterator
>         search_params = {"metric_type": metrics}
>         expression = "1000.0 <= float < 2000.0"
>         search_iterator = collection_w.search_iterator(vectors[:1], field_name, search_params,
>                                                        limit, output_fields=['float'], expr=expression)[0]
>         # 3. check the result
>         page_idx = 0
>         pk_list = []
>         while True:
>             res = search_iterator.next()
>             if len(res[0]) == 0:
>                 log.info("search iteration finished, close")
>                 search_iterator.close()
>                 break
>             
>             for i in range(len(res[0])):
>                 pk_list.append(res[0][i].id)
>             page_idx += 1
>         log.info(len(pk_list))
>         notExistId=[]
>         pk_set = set(pk_list)
>         if len(pk_set) == 1000:
>             return
> 
>         for i in range(1000,2000):
>             if i not in pk_set:
>                 notExistId.append(i)
> 
>         print("find not exist id", notExistId)
>         expression = f"float not in {notExistId} "
>         # print("search with expression", expression, 'limit', limit, 'param', search_param , 'name',field_name)
>         # res =collection_w.search(vectors[:1], field_name, search_params, limit, expr=expression)
>         # print('search result:',res[0])
> 
>         print("query with expression", expression)
>         res = collection_w.query(expression, output_fields=['float'])
>         pk_list = []
>         for i in range(len(res[0])):
>             pk_list.append(res[0][i]['int64'])
>         # print(res[0][-1])
>         se = set(pk_list)
>         for i in range(0,2000):
>             if i not in se:
>                 print(f'{i} not in query result')
>         assert False
> ```

Any reasons?

**Comment by MrPresent-Han** [comment]
> > ![image](https://user-images.githubusercontent.com/90906581/247524837-3927ecbf-2fa6-46b8-8cf1-e5445b4674e1.png) i extract id not in [1000,2000), and try to query all data。
> > ```python
> > class TestSearchIterator(TestcaseBase):
> >     """ Test case of search iterator """
> >     @pytest.mark.tags(CaseLabel.L2)
> >     @pytest.mark.parametrize("metrics", ct.float_metrics[:1])
> >     def test_search_iterator_with_expression(self, metrics):
> >         """
> >         target: test search iterator normal
> >         method: 1. search iterator
> >                 2. check the result, expect pk not repeat and meet the expr requirements
> >         expected: search successfully
> >         """
> >         # 1. initialize with data
> >         limit = 100
> >         dim = 128
> >         collection_w = self.init_collection_general(prefix, True, dim=dim, is_index=False)[0]
> >         collection_w.create_index(field_name, {"metric_type": metrics})
> >         collection_w.load()
> >         # 2. search iterator
> >         search_params = {"metric_type": metrics}
> >         expression = "1000.0 <= float < 2000.0"
> >         search_iterator = collection_w.search_iterator(vectors[:1], field_name, search_params,
> >                                                        limit, output_fields=['float'], expr=expression)[0]
> >         # 3. check the result
> >         page_idx = 0
> >         pk_list = []
> >         while True:
> >             res = search_iterator.next()
> >             if len(res[0]) == 0:
> >                 log.info("search iteration finished, close")
> >                 search_iterator.close()
> >                 break
> >             
> >             for i in range(len(res[0])):
> >                 pk_list.append(res[0][i].id)
> >             page_idx += 1
> >         log.info(len(pk_list))
> >         notExistId=[]
> >         pk_set = set(pk_list)
> >         if len(pk_set) == 1000:
> >             return
> > 
> >         for i in range(1000,2000):
> >             if i not in pk_set:
> >                 notExistId.append(i)
> > 
> >         print("find not exist id", notExistId)
> >         expression = f"float not in {notExistId} "
> >         # print("search with expression", expression, 'limit', limit, 'param', search_param , 'name',field_name)
> >         # res =collection_w.search(vectors[:1], field_name, search_params, limit, expr=expression)
> >         # print('search result:',res[0])
> > 
> >         print("query with expression", expression)
> >         res = collection_w.query(expression, output_fields=['float'])
> >         pk_list = []
> >         for i in range(len(res[0])):
> >             pk_list.append(res[0][i]['int64'])
> >         # print(res[0][-1])
> >         se = set(pk_list)
> >         for i in range(0,2000):
> >             if i not in se:
> >                 print(f'{i} not in query result')
> >         assert False
> > ```
> 
> Any reasons?

I suppose the difference between two segments code is that the code from @NicoYuan1986 searching the growing segment. So the final result is generated by violent calculation without using HNSW. While code inside e2e test used HNSW as expected. I got the following log inside querynode.log

[2023/06/25 16:42:13.982 +08:00] [INFO] [segments/search.go:94] ["search growing/sealed segments without indexes"] [traceID=9340d5430619b939f618f915e907779f] [segmentIDs="[442410230948028121]"]

**Comment by MrPresent-Han** [comment]
I found that the code provided by @NicoYuan1986 lack 'collection flushed' operation, leading to the search request towards growing segments. I believe this is root cause for the inconsistency of two segments of code. And this issue is not a bug under the semantic meaning of search_iterator

**Comment by NicoYuan1986** [comment]
It is by design. So close the issue. Thanks for help!
