### ISSUE TITLE
[Bug]: search error

### ISSUE THREAD

**Issue by yesletgo** [milvus-io/milvus#25023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.10
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 60 cores/ 370G
- GPU: 
- Others:
```

### Current Behavior

A total of 60 million data, with an index type of HNSW.
Search error.
error: exception=StatusRuntimeException: UNAVAILABLE: io exception, status=-3, data=null

### Milvus Log

https://video-tag-lib-1251808348.cos.ap-beijing.myqcloud.com/milvus_log/k8s_logs_06_20_36h.tar.gz

**Comment by yanliang567** [comment]
@yesletgo is this a new deployment of v2.2.10 or upgraded from an previous version?

/assign @congqixia

**Comment by yesletgo** [comment]
> @yesletgo is this a new deployment of v2.2.10 or upgraded from an previous version?
> 
> /assign @congqixia

new deployment of v2.2.10

**Comment by xiaofan-luan** [comment]
UNAVAILABLE: io exception,
You have to check your environemnt.
This is not a milvus exception

**Comment by xiaofan-luan** [comment]
and from milvus log, there is no error message.
Try to make sure your client and server has available network connection

**Comment by yesletgo** [comment]
> and from milvus log, there is no error message. Try to make sure your client and server has available network connection

ok. a new problem appear.
With milvus-sdk-java version is 2.2.7, milvus cluster version is 2.2.10, java api can not search, but can search  by attu.
![image](https://github.com/milvus-io/milvus/assets/21998052/1624ecd5-6279-46dc-a3c1-1ab2b2dfef64)
![image](https://github.com/milvus-io/milvus/assets/21998052/b3ed9dfa-58a7-427b-8a12-7553ca728ebe)

**Comment by yanliang567** [comment]
ef shall be not less than topK. 
Attu might help you correct the ef, while java sdk did not

**Comment by yesletgo** [comment]
> ef shall be not less than topK. Attu might help you correct the ef, while java sdk did not

Milvus version 2.2.8 can search with ef less than topK.

**Comment by xiaofan-luan** [comment]
> > ef shall be not less than topK. Attu might help you correct the ef, while java sdk did not
> 
> Milvus version 2.2.8 can search with ef less than topK.

The limitation is always there.
Might because we correct the ef in previous version somewhere

**Comment by yesletgo** [comment]
> > > ef shall be not less than topK. Attu might help you correct the ef, while java sdk did not
> > 
> > 
> > Milvus version 2.2.8 can search with ef less than topK.
> 
> The limitation is always there. Might because we correct the ef in previous version somewhere

Thank you.
