### ISSUE TITLE
Search performance decreased between 4.17-4.23

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#2502]
**Describe the bug**
sift-1b: nprobe: 32

44e8e0206537046ccd89306951ca704a545e0417 | 47.09 | 2020-04-22 15:54:36.054176 |  
-- | -- | -- | --
59035d9892831400041e529a3bc69e8b297903a3 | 32.94 | 2020-04-17 17:44:33.040732

nq: 1000, topk: 1000

1,587,562,392 | 62.12 | 2020-04-22 15:54:36.114591 |  
-- | -- | -- | --
1,587,137,658 | 48.32 | 2020-04-17 17:44:33.085790

**Steps/Code to reproduce behavior**

**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by cydrain** [comment]
This issue should be caused by the data set change between 0417 and 0422.
Following is the statistics running 0422 image on db_data_7 and db_data_8.
```
commit 44e8e0206537046ccd89306951ca704a545e0417
Author: Yoya <taydycn@gmail.com>
Date:   Wed Apr 22 20:16:55 2020 +0800
```
Statistics on db_data_7:

**Comment by cydrain** [comment]
test with 0.10.0
```
commit 34b4d72517de2cf2f6e300af0cf954c5147a1d75
Author: Jin Hai <hai.jin@zilliz.com>
Date:   Mon Jun 8 21:16:22 2020 +0800
```
Run on db_data_7:
```
╭─────────────┬─────────────┬─────────────╮
│  Nq/Top-k   │     10      │     100     │
├─────────────┼─────────────┼─────────────┤
│         100 │        6.25 │        5.73 │
│        1000 │       33.13 │       33.45 │
╰─────────────┴─────────────┴─────────────╯
```
