### ISSUE TITLE
I don't know how to compile and use canon when encountering this error

### ISSUE THREAD

**Issue by hotwinters** [milvus-io/milvus#25044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.9
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): ubuntu.20
- CPU/Memory: arm64
- GPU: 
- Others:
```

### Current Behavior

just   make

**Comment by hotwinters** [comment]
![image](https://github.com/milvus-io/milvus/assets/34262412/7f7af0d6-551d-4e73-995a-d92fc9d02209)

**Comment by hotwinters** [comment]
I can manually delete to resolve this error and ensure successful compilation, but Conan still knows how to delete the file after successful compilation, download it from the internet again, and continue to report errors. I don't know what to do

**Comment by jiaoew1991** [comment]
Hi @hotwinters，Which branch are you trying to compile?  Conan is not used in 2.2, only master is used. I see the environment information you provided is in version 2.2.9 and in the arm environment?

**Comment by hotwinters** [comment]
@jiaoew1991 Yes, I didn't pay attention. I am using code from master version 2.2.10

**Comment by hotwinters** [comment]
@jiaoew1991 yes， in the arm environment

**Comment by jiaoew1991** [comment]
Milvus has not been compiled in any arm environment other than Mac M1.

> I can manually delete to resolve this error and ensure successful compilation

Are you suggesting deleting the ~/.conan/data/crc32 directory?

**Comment by hotwinters** [comment]
@jiaoew1991 The cmakelist file in crc32 forces the enable of Werror, but there is a warning during the compilation process, which prevents the compilation from proceeding properly, and I don't know how to operate it

**Comment by jiaoew1991** [comment]
> @jiaoew1991 The cmakelist file in crc32 forces the enable of Werror, but there is a warning during the compilation process, which prevents the compilation from proceeding properly, and I don't know how to operate it

You can try editing the ~/.conan/profiles/default file and add CFLAGS and CXXFLAGS under [env].
```
CFLAGS=-Wno-error
CXXFLAGS=-Wno-error
```

**Comment by hotwinters** [comment]
@jiaoew1991 it error,too.    After I made the modifications, it still doesn't work properly

**Comment by hotwinters** [comment]
@jiaoew1991 And this tag cannot be used in the default file, I tried

**Comment by jiaoew1991** [comment]
@hotwinters  Milvus does not yet support arm Linux. You can try to compile and develop in an x86 Linux environment.

**Comment by xiaofan-luan** [comment]
> @hotwinters Milvus does not yet support arm Linux. You can try to compile and develop in an x86 Linux environment.

we should already support compile to milvus
@Presburger

**Comment by Presburger** [comment]
before compile milvus, add this env
```
export CXXFLAGS="-Wno-address"
export CCFLAGS="-Wno-address"
```

**Comment by xiaofan-luan** [comment]
> 
for X86, do we need the same flag?

**Comment by jiaoew1991** [comment]
It seems to be a unique problem that occurs only when compiling with crc32 on ARM architecture, which requires the use of crc32c_arm_linux_check.h.

**Comment by jiaoew1991** [comment]
If we want to solve this problem, we need to maintain a crc32 version on JFrog and skip the address check, or submit modifications to the official Conan source, which will take some time.

**Comment by Presburger** [comment]
> for X86, do we need the same flag?

no

This is just some compilation over-diagnosis, and the newer and more modern compilers are more likely to have these problems. conan we rely on to compile everything from source can easily trigger these kinds of problems.

**Comment by hotwinters** [comment]
> 如果我们想解决这个问题，我们需要在 JFrog 上维护一个 crc32 版本并跳过地址检查，或者向柯南官方源提交修改，这将需要一些时间。

Okay, looking forward to successful release
