### ISSUE TITLE
[Bug]: session KeepAliveOnce may stuck sometimes

### ISSUE THREAD

**Issue by wayblink** [milvus-io/milvus#25070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.9/2.2.10
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Case in Cloud.
When ETCD leader crash accidentally, milvus session's keepalive will disconnected.
We add retry KeepAlive in #24574. 
It can recover but sometimes we found KeepAliveOnce get stuck.

**Comment by wayblink** [comment]
![image](https://github.com/milvus-io/milvus/assets/18096561/700c5bb2-b192-4e40-9786-7347b6961a30)
Call KeepAliveOnce after KeepAlive close, and it stucks

**Comment by wayblink** [comment]
![image](https://github.com/milvus-io/milvus/assets/18096561/29049f79-2510-4322-9380-b463776bac47)
I can reproduce it sometimes not always.  Found it stuck in gRPC between etcd client and server, waiting for the server's response. https://github.com/etcd-io/etcd/blob/v3.5.5/client/v3/lease.go#L423

**Comment by xiaofan-luan** [comment]
> ![image](https://user-images.githubusercontent.com/18096561/247463948-29049f79-2510-4322-9380-b463776bac47.png) I can reproduce it sometimes not always. Found it stuck in gRPC between etcd client and server, waiting for the server's response. https://github.com/etcd-io/etcd/blob/v3.5.5/client/v3/lease.go#L423

I guess for some reason it connect to the old server?

**Comment by jiaoew1991** [comment]
Does the `KeepAlive` API have a timeout, or can it be canceled using ctx timing? 🤔

**Comment by xiaofan-luan** [comment]
> 

according to etcd document, it can be canceled by context
