### ISSUE TITLE
[Bug]: task queue is full

### ISSUE THREAD

**Issue by 670133189** [milvus-io/milvus#25089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.3
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.1.3
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 8/16
- GPU: none
- Others:
```

### Current Behavior

Hello, in the default configuration (milvus. yml), when I open 10 '`.insert()`' at the same time, after about 1 minute, I will prompt "**task queue is full**"

May I ask how to set it up? For example, 10 processes simultaneously?

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version:2.1.3
> - Deployment mode(standalone or cluster): standalone
> - MQ type(rocksmq, pulsar or kafka):    
> - SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.1.3
> - OS(Ubuntu or CentOS): CentOS
> - CPU/Memory: 8/16
> - GPU: none
> - Others:
> ```
> 
> ### Current Behavior
> Hello, in the default configuration (milvus. yml), when I open 10 '`.insert()`' at the same time, after about 1 minute, I will prompt "**task queue is full**"
> 
> May I ask how to set it up? For example, 10 processes simultaneously?
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

Task queue is full means the server can not catch up the write throughput.

To improve:
1. use latest 2.2.10 branch
2. try to batch your insert
3. if still not working, try to use bulkinsert instead of streaming insert

**Comment by 670133189** [comment]
Thank you for your reply!
At present, I have been resolved, as I `.release()` every time I `.insert()`, which leads to the above issue.
