### ISSUE TITLE
[Bug]: Remove the frequent log print

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#25093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

We always see the frequent logs 
invalid character when deserialize statslog.
Try to reduce the number of log printed

**Comment by xiaofan-luan** [comment]
logs look like
 ["failed to deserialize stats"] [error="invalid character 'A' looking for beginning of value"]

**Comment by yanliang567** [comment]
is it completed @xiaofan-luan
