### ISSUE TITLE
[Bug]: fix typos in a wiki page `Hybrid Search`

### ISSUE THREAD

**Issue by roykoand** [milvus-io/milvus#25099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

> Conduct a similariy search with an expression filtering ID column

TYPO: similariy

> FLOAT | Float nubmers such as 1.0, 2.0.

TYPO: nubmers

### Expected Behavior

similariy -> similarity
nubmers -> numbers

**Comment by xiaofan-luan** [comment]
feel free to fix it~ Thanks for the feedback

**Comment by roykoand** [comment]
@xiaofan-luan thank you! Fixed typos here: https://github.com/milvus-io/milvus/wiki/Hybrid-Search/57722d347b179b019bfb1ba45b1e4767192dfc59
I didn't know everyone has an ability to edit the wiki page. Just curious, from your open-source experience how safe is it?

**Comment by xiaofan-luan** [comment]
I actually don't know know we have a wiki page here~~
But anyway thanks for the contribution!
