### ISSUE TITLE
[Bug]: fail to search after insert and delete slowly for a few hours

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#25105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230621-6d139d97
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
```

### Current Behavior

after insert and delete slowly for a few hours, search failed
```
06/25/2023 03:27:50 AM - ERROR - RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
attempt #1:All attempts results:
attempt #1:fail to get shard leaders from QueryCoord: channel yanliang-20cu-rootcoord-dml_0_442323864287453969v0 is not available in any replica, err=NodeOffline(nodeID=27)
```

### Expected Behavior

search, delete, insert, all requests succeed

### Steps To Reproduce

```markdown
1. create a collection with 512d-10m vectors
2. delete 100 vectors and insert 100 vectors per second
3. keep searching in the other clinet (search covers to success after ~70s in this client)
```

### Milvus Log

pod names:
```
yanliang-20cu-milvus-datanode-6577d4d86c-g2vsx                    1/1     Running       0                3d21h   10.102.9.133    devops-node13   <none>           <none>
yanliang-20cu-milvus-indexnode-56c6457c8d-28p5g                   1/1     Running       1 (3d17h ago)    3d21h   10.102.9.126    devops-node13   <none>           <none>
yanliang-20cu-milvus-indexnode-56c6457c8d-768t9                   1/1     Running       3 (162m ago)     3d17h   10.102.7.27     devops-node11   <none>           <none>
yanliang-20cu-milvus-mixcoord-7c57659fb9-td95d                    1/1     Running       1 (3d18h ago)    3d21h   10.102.9.119    devops-node13   <none>           <none>
yanliang-20cu-milvus-proxy-8d49fd575-xbpql                        1/1     Running       0                3d21h   10.102.9.120    devops-node13   <none>           <none>
yanliang-20cu-milvus-querynode-867cc74dfd-9kbfd                   1/1     Running       0                3d21h   10.102.6.153    devops-node10   <none>           <none>
yanliang-20cu-milvus-querynode-867cc74dfd-kjmb9                   1/1     Running       0                3d21h   10.102.10.83    devops-node20   <none>           <none>
yanliang-20cu-milvus-querynode-867cc74dfd-nknl8                   1/1     Running       5 (83m ago)      3d21h   10.102.9.108    devops-node13   <none>           <none>
yanliang-20cu-milvus-querynode-867cc74dfd-q8h79                   1/1     Running       1 (3d18h ago)    3d21h   10.102.7.214    devops-node11   <none>           <none>
yanliang-20cu-milvus-querynode-867cc74dfd-rqx4z                   1/1     Running       0                3d21h   10.102.5.177    devops-node21   <none>           <none>
```

### Anything else?

the timetick lag is big at that moment:
![image](https://github.com/milvus-io/milvus/assets/82361606/28c81264-6c30-4269-8347-fa3f5f03e4cb)

**Comment by xiaofan-luan** [comment]
The concurrent insert/delete/search performance will be a major concern we need to work with

**Comment by MrPresent-Han** [comment]
I will have a look at this

**Comment by yanliang567** [comment]
last night the slow insert interrupted due to #25017 , but after insert interrupted for 30mins, the search became fail for mixcoord and one of querynode restarted almost at the same time.
Search fails at (querynode and mixcoord crash)
`06/26/2023 22:27:22 PM - ERROR - RPC error: [search], <MilvusException: (code=1, message=syncTimestamp Failed:err: find no available rootcoord, check rootcoord state`
Search recovers at
`06/26/2023 22:51:46 PM - INFO - collection insert_slowly search 1000 times in thread0: cost 1454.3472, qps 0.6876, avg 1.4543, p99 10.0043`
Insert slow start at
`06/26/2023 10:46:52 AM - INFO - start to insert with nb=100, interval=1, timeout=86400`
Failed and interruptted at 
`06/26/2023 21:53:59 PM - ERROR - RPC error: [batch_insert], <MilvusException: (code=1, message=getSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)>,`

pods in devops cluster:
```
yanliang-20cu-milvus-datanode-6577d4d86c-g2vsx                    1/1     Running       0               5d18h
yanliang-20cu-milvus-indexnode-84bc9cd4bb-2whzk                   0/1     Running       3 (29h ago)     39h
yanliang-20cu-milvus-mixcoord-7c57659fb9-td95d                    1/1     Running       3 (3h16m ago)   5d18h
yanliang-20cu-milvus-proxy-8d49fd575-xbpql                        1/1     Running       0               5d18h
yanliang-20cu-milvus-querynode-867cc74dfd-9kbfd                   1/1     Running       1 (3h16m ago)   5d18h
yanliang-20cu-milvus-querynode-867cc74dfd-kjmb9                   1/1     Running       0               5d18h
yanliang-20cu-milvus-querynode-867cc74dfd-nknl8                   1/1     Running       5 (46h ago)     5d18h
yanliang-20cu-milvus-querynode-867cc74dfd-q8h79                   1/1     Running       1 (5d15h ago)   5d18h
yanliang-20cu-milvus-querynode-867cc74dfd-rqx4z                   1/1     Running       0               5d18h
```

**Comment by xiaofan-luan** [comment]
> last night the slow insert interrupted due to #25017 , but after insert interrupted for 30mins, the search became fail for mixcoord and one of querynode restarted almost at the same time. Search fails at (querynode and mixcoord crash) `06/26/2023 22:27:22 PM - ERROR - RPC error: [search], <MilvusException: (code=1, message=syncTimestamp Failed:err: find no available rootcoord, check rootcoord state` Search recovers at `06/26/2023 22:51:46 PM - INFO - collection insert_slowly search 1000 times in thread0: cost 1454.3472, qps 0.6876, avg 1.4543, p99 10.0043` Insert slow start at `06/26/2023 10:46:52 AM - INFO - start to insert with nb=100, interval=1, timeout=86400` Failed and interruptted at `06/26/2023 21:53:59 PM - ERROR - RPC error: [batch_insert], <MilvusException: (code=1, message=getSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)>,`
> 
> pods in devops cluster:
> 
> ```
> yanliang-20cu-milvus-datanode-6577d4d86c-g2vsx                    1/1     Running       0               5d18h
> yanliang-20cu-milvus-indexnode-84bc9cd4bb-2whzk                   0/1     Running       3 (29h ago)     39h
> yanliang-20cu-milvus-mixcoord-7c57659fb9-td95d                    1/1     Running       3 (3h16m ago)   5d18h
> yanliang-20cu-milvus-proxy-8d49fd575-xbpql                        1/1     Running       0               5d18h
> yanliang-20cu-milvus-querynode-867cc74dfd-9kbfd                   1/1     Running       1 (3h16m ago)   5d18h
> yanliang-20cu-milvus-querynode-867cc74dfd-kjmb9                   1/1     Running       0               5d18h
> yanliang-20cu-milvus-querynode-867cc74dfd-nknl8                   1/1     Running       5 (46h ago)     5d18h
> yanliang-20cu-milvus-querynode-867cc74dfd-q8h79                   1/1     Running       1 (5d15h ago)   5d18h
> yanliang-20cu-milvus-querynode-867cc74dfd-rqx4z                   1/1     Running       0               5d18h
> ```

Is this testing etcd running on ssds?
We should probably looking into details about ssd issue

**Comment by MrPresent-Han** [comment]
2023-06-25 11:27:39
[2023/06/25 03:27:39.604 +00:00] [ERROR] [querynode/query_node.go:220] ["Query Node disconnected from etcd, process will exit"] ["Server Id"=27] [stack="github.com/milvus-io/milvus/internal/querynode.(*QueryNode).Register.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/query_node.go:220"]
2023-06-25 11:27:39
[2023/06/25 03:27:39.604 +00:00] [WARN] [sessionutil/session_util.go:728] ["connection lost detected, shuting down"]
2023-06-25 11:27:39
[2023/06/25 03:27:39.604 +00:00] [WARN] [sessionutil/session_util.go:444] ["fail to keepAliveOnce"] [error="etcdserver: requested lease not found"]
2023-06-25 11:27:38
[2023/06/25 03:27:38.973 +00:00] [INFO] [sessionutil/session_util.go:438] ["start try to KeepAliveOnce"] [serverName=querynode]
2023-06-25 11:27:38
[2023/06/25 03:27:38.973 +00:00] [WARN] [sessionutil/session_util.go:433] ["session keepalive channel closed"]

QueryNode lost connection to etcd and had to shut down itself

**Comment by MrPresent-Han** [comment]
most of restart are due to connection lost with etcd, except for the index node:


signal arrived during cgo execution
--
  |   | 2023-06-26 00:19:45 | PC=0x7f3beed1700b m=16 sigcode=18446744073709551610
  |   | 2023-06-26 00:19:45 | SIGABRT: abort
  |   | 2023-06-26 00:19:45 | what():  Error:PutObjectBuffer:  curlCode: 28, Timeout was reached
  |   | 2023-06-26 00:19:45 | terminate called after throwing an instance of 'milvus::storage::S3ErrorException'


it seems write S3 process ran into timeout too
