### ISSUE TITLE
Require an interface to get the uptime of server

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#2512]
**Is your feature request related to a problem? Please describe.**
With this function, we can make sure how long the server has been started.

**Describe the solution you'd like**
when calling `info` or other function, and then it will return uptime as part of the results.

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by del-zhenwu** [comment]
```
mysql> status
--------------
mysql  Ver 8.0.19 for Linux on x86_64 (MySQL Community Server - GPL)

Connection id:		67040274
Current database:	
Current user:		root@localhost
SSL:			Not in use
Current pager:		stdout
Using outfile:		''
Using delimiter:	;
Server version:		8.0.19 MySQL Community Server - GPL
Protocol version:	10
Connection:		Localhost via UNIX socket
Server characterset:	utf8mb4
Db     characterset:	utf8mb4
Client characterset:	latin1
Conn.  characterset:	latin1
UNIX socket:		/var/run/mysqld/mysqld.sock
Binary data as:		Hexadecimal
Uptime:			99 days 22 hours 5 min 42 sec

```

**Comment by BossZou** [comment]
We may reuse API `_cmd` to do this.

**Comment by scsven** [comment]
Done, using cmd("status") to get.
