### ISSUE TITLE
[Bug]: The indexnode keeps unhealthy for hours 

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#25129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20230621-6d139d97
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):  pulsar
```

### Current Behavior

indexnode keeps unhealthy for hours
![image](https://github.com/milvus-io/milvus/assets/82361606/c4b39bfa-6aef-46dd-a385-66b8fcc0f281)
 
describe the pod:
 ` Warning  Unhealthy  13s (x566 over 4h45m)  kubelet  Readiness probe failed: Get "http://10.102.7.227:9091/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
`

### Expected Behavior

indexnode turns to healthy, if it does not, it shall restart itself to get healthy.

### Steps To Reproduce

```markdown
1. create a collection with 10m-512d vectors
2. keeps deleting 100 vectors and inserting 100 vectors per second for 24 hours
```

### Milvus Log

pod names:
```
yanliang-20cu-milvus-datanode-6577d4d86c-g2vsx                    1/1     Running       0                4d18h   10.102.9.133    devops-node13   <none>           <none>
yanliang-20cu-milvus-indexnode-84bc9cd4bb-2whzk                   0/1     Running       3 (5h9m ago)     15h     10.102.7.227    devops-node11   <none>           <none>
yanliang-20cu-milvus-mixcoord-7c57659fb9-td95d                    1/1     Running       1 (4d15h ago)    4d18h   10.102.9.119    devops-node13   <none>           <none>
yanliang-20cu-milvus-proxy-8d49fd575-xbpql                        1/1     Running       0                4d18h   10.102.9.120    devops-node13   <none>           <none>
yanliang-20cu-milvus-querynode-867cc74dfd-9kbfd                   1/1     Running       0                4d18h   10.102.6.153    devops-node10   <none>           <none>
yanliang-20cu-milvus-querynode-867cc74dfd-kjmb9                   1/1     Running       0                4d18h   10.102.10.83    devops-node20   <none>           <none>
yanliang-20cu-milvus-querynode-867cc74dfd-nknl8                   1/1     Running       5 (22h ago)      4d18h   10.102.9.108    devops-node13   <none>           <none>
yanliang-20cu-milvus-querynode-867cc74dfd-q8h79                   1/1     Running       1 (4d15h ago)    4d18h   10.102.7.214    devops-node11   <none>           <none>
yanliang-20cu-milvus-querynode-867cc74dfd-rqx4z                   1/1     Running       0                4d18h   10.102.5.177    devops-node21   <none>           <none>
```

**Comment by xiaocai2333** [comment]
![image](https://github.com/milvus-io/milvus/assets/46207236/ec7194dd-b12e-4ff3-aa9c-ab33eca77db2)

The logs abruptly stopped, and no issues could be identified. @LoveEachDay please take a quick look from the operations perspective.

**Comment by xiaocai2333** [comment]
```


2023-06-26 04:43:42 | signal arrived during cgo execution
-- | --
  |   | 2023-06-26 04:43:42 | PC=0x7f6b5b4cc00b m=17 sigcode=18446744073709551610
  |   | 2023-06-26 04:43:42 | SIGABRT: abort
  |   | 2023-06-26 04:43:42 | what():  Error:PutObjectBuffer:  curlCode: 28, Timeout was reached
  |   | 2023-06-26 04:43:42 | terminate called after throwing an instance of 'milvus::storage::S3ErrorException'
```

And previously, the reason for the pod restart was due to a timeout while storing objects in Minio.

**Comment by xiaofan-luan** [comment]
> ```
> 
> 
> 2023-06-26 04:43:42 | signal arrived during cgo execution
> -- | --
>   |   | 2023-06-26 04:43:42 | PC=0x7f6b5b4cc00b m=17 sigcode=18446744073709551610
>   |   | 2023-06-26 04:43:42 | SIGABRT: abort
>   |   | 2023-06-26 04:43:42 | what():  Error:PutObjectBuffer:  curlCode: 28, Timeout was reached
>   |   | 2023-06-26 04:43:42 | terminate called after throwing an instance of 'milvus::storage::S3ErrorException'
> ```
> 
> And previously, the reason for the pod restart was due to a timeout while storing objects in Minio.

Is this due to error handling of S3 not correct? Should not be aborted due to S3 aerror anyway

**Comment by xiaocai2333** [comment]
The root cause of the error was a timeout while uploading a file to S3. However, we should not have panicked the program. Although the exception was caught during the S3 operation, the use of the 'noexcept' modifier in the call chain ultimately led to the program panicking.

![image](https://github.com/milvus-io/milvus/assets/46207236/906172ae-9eb3-4da3-a5c1-de5aaa9f2ab1)
![image](https://github.com/milvus-io/milvus/assets/46207236/36a8a4e2-a812-4e75-96ce-96a1353e1ec8)

**Comment by yanliang567** [comment]
it occurs again on 2.2.0-20230717-4140ec09
```
yanliang-parkey-etcd-0                                         1/1     Running            0                 13h
yanliang-parkey-milvus-standalone-689d4966f5-hmqbz             0/1     Running            0                 13h
yanliang-parkey-minio-777dfb88d8-rchdd                         1/1     Running            0                 13h
```
describe the pod info:
```
Normal   Killing    31m (x103 over 12h)     kubelet  Container standalone failed liveness probe, will be restarted
  Warning  Unhealthy  6m52s (x1513 over 12h)  kubelet  Readiness probe failed: Get "http://10.102.6.45:9091/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  112s (x74 over 11h)     kubelet  Readiness probe failed: Get "http://10.102.6.45:9091/healthz": dial tcp 10.102.6.45:9091: i/o timeout (Client.Timeout exceeded while awaiting headers)
```

**Comment by xiaocai2333** [comment]
/assign @yanliang567 
It should be fixed, is it reproduced?

**Comment by yanliang567** [comment]
not reproduce recently, close for now
