### ISSUE TITLE
Milvus ut failed on case 'DBTest2.INSERT_DUPLICATE_ID'

### ISSUE THREAD

**Issue by BossZou** [milvus-io/milvus#2513]
**Describe the bug**
```
[ RUN      ] DBTest2.INSERT_DUPLICATE_ID
unknown file: Failure
C++ exception with description "out of memory: out of memory" thrown in the test body.
[  FAILED  ] DBTest2.INSERT_DUPLICATE_ID (82 ms)
[----------] 8 tests from DBTest2 (1151 ms total)

```

**Steps/Code to reproduce behavior**

**Expected behavior**

**Environment details**

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
Crashed in sqlite 

![Screenshot from 2020-06-11 19-41-41](https://user-images.githubusercontent.com/2282099/84381413-9a3ced00-ac1b-11ea-8e8f-f8c103eb8dfe.png)

**Comment by fishpenguin** [comment]
I located the "out of memory" exception in SqliteMetaImpl::Initialize(): ConnectorPtr->pragma.journal_mode(journal_mode::WAL);  // WAL => write ahead log.

**Comment by BossZou** [comment]
This is a bug in which thirdparty sqlite-orm occurred. In latest milvus v0.11.0, the thirdparty sqlite-orm has been removed.

-------------------------------------------------------------------------------------
close it.
