### ISSUE TITLE
[Bug]: The P99 increased 40% after adding more cpu cores for the Proxy pod

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#25148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230621-6d139d97
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2):
```

### Current Behavior

when the proxy cpu core limit is 4
```
proxy:
      replicas: 1
      resources:
        limits:
          cpu: "4"
          memory: "8Gi"
        requests: {}
```
the p99 is ~ 17ms and qps is ~6740.
But after changing the proxy cpu core limit to 8
the p99 turns to ~24ms and the qps keeps ~6740.
![image](https://github.com/milvus-io/milvus/assets/82361606/91e0cbea-9539-40df-b513-a32e67779265)

### Expected Behavior

The performance shall at least keeps stable, instead of getting worse.

### Steps To Reproduce

```markdown
1. create a collection 
Dataset: 20k-768d random vectors
{'index_type': 'HNSW', 'params': {'M': 30, 'efConstruction': 360}, 'metric_type': 'L2'}
Search params: nq=1, topk=10, ef=64
2. search with go bench
3. change the proxy cpu core limit
4. search again
```

### Milvus Log

pods in 4am:
```
yanliang-small-milvus-datanode-74679bfc5b-hd695                   1/1     Running     0               8m41s   10.104.24.41    4am-node29   <none>           <none>
yanliang-small-milvus-indexnode-697655c6fc-mp4pj                  1/1     Running     0               8m41s   10.104.17.138   4am-node23   <none>           <none>
yanliang-small-milvus-mixcoord-5c5d5f677f-7hv4s                   1/1     Running     0               8m41s   10.104.17.139   4am-node23   <none>           <none>
yanliang-small-milvus-proxy-6576747847-j2wg4                      1/1     Running     0               8m41s   10.104.15.170   4am-node20   <none>           <none>
yanliang-small-milvus-querynode-5475dffbbb-dgqhv                  1/1     Running     0               8m41s   10.104.22.60    4am-node26   <none>           <none>
```
after changing the proxy cpu core limit:
`yanliang-small-milvus-proxy-cb4dd6477-vvd46                       1/1     Running            0               4m41s   10.104.23.252   4am-node27   <none>           <none>`

### Anything else?

it seems that the search group size became larger after adding more cpu cores for proxy. I guess the group size should depends on querynode cpu cores instead of proxy cpu cores.
![image](https://github.com/milvus-io/milvus/assets/82361606/204b7bf2-7b69-4676-b534-12e313049457)

**Comment by xiaofan-luan** [comment]
the group size go up is as expected.
Seems that group size increased by 30%  but the segcore latency goes up to 2.5 times

**Comment by xiaofan-luan** [comment]
@yanliang567 
could we try to run the same test on knowhere
say nq =20 and nq =40 and see the performance difference?

**Comment by yanliang567** [comment]
> @yanliang567 Can I have some info about resources usage, such as CPU usage, Thread number, etc.

check the metrics on grafana with the pod names.

**Comment by liliu-z** [comment]
@yanliang567 any updates? From the info we have, I don't have too much thoughts.
