### ISSUE TITLE
[Bug]: The specified key does not exist

### ISSUE THREAD

**Issue by 670133189** [milvus-io/milvus#25140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.10
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.9
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 4/32
- GPU: 0
- Others:
```

### Current Behavior

Hello, according to “https://milvus.io/docs/bulk_insert.md” : **You can use either MiniO or the local hard disk for storage in Milvus. For local storage, copy the data files into a directory of the local disk**

Does it mean I don't need to upload files through `minio`? After `np.save() `directly produces `.npy`, call [utility.do_ Bulk_ Insert()](url)?

If so, I will receive an error prompt of “**Failed reason: failed to get file size of 'xxx.npy', error:The specified key does not exist**”
May I ask how to solve it? Thank you!

**Comment by ganhb** [comment]
我在milvus v2.2.10 standalone docker方式部署下也 遇到问题一样  试了多种方式 还是没解决 mark下
![image](https://github.com/milvus-io/milvus/assets/18379253/01248c0f-2ab1-417a-a5a5-830b5e8f2ebd)

首先,根据官网介绍
![image](https://github.com/milvus-io/milvus/assets/18379253/1f80a1ff-f4af-4571-bc33-500f450a4621)
我是手动上传文件到docker容器内,容器内和容器外都有相同文件,已经确保权限都开放,且文件都存在;但是还是一样的错误;

我也尝试用minio,服务器防火墙都已关闭
![image](https://github.com/milvus-io/milvus/assets/18379253/b30db7f1-eddd-4c46-8ec3-bb3533b726df)
访问其9000端口,失败

**Comment by zhuwenxing** [comment]
>Does it mean I don't need to upload files through minio? After np.save() directly produces .npy, call [utility.do_ Bulk_ Insert()](https://github.com/milvus-io/milvus/issues/url)?

@670133189 

Where are your npy files saved? It should be in `volumes/minio/a-bucket`

**Comment by zhuwenxing** [comment]
And we suggest using minio API or CLI to upload the file to the bucket.

**Comment by ganhb** [comment]
> > Does it mean I don't need to upload files through minio? After np.save() directly produces .npy, call [utility.do_ Bulk_ Insert()](https://github.com/milvus-io/milvus/issues/url)?
> 
> @670133189
> 
> Where are your npy files saved? It should be in `volumes/minio/a-bucket`
我上传到volumes/minio/a-bucket目录下面 结果还是一样The specified key does not exist  所以standalone方式一定得通过minioAPI/cli上传吗

**Comment by zhuwenxing** [comment]
@ganhb 
Yes! But if you want to use minio web console, you need to modify the docker-compose.yaml.
![image](https://github.com/milvus-io/milvus/assets/12268675/ea4b7ac5-cd95-41e9-8601-4ff384c432cf)
Then you can access it.
![image](https://github.com/milvus-io/milvus/assets/12268675/10abd305-d974-439b-a715-e72da44d53f6)

**Comment by ganhb** [comment]
> @ganhb Yes! But if you want to use minio web console, you need to modify the docker-compose.yaml. ![image](https://user-images.githubusercontent.com/12268675/248709797-ea4b7ac5-cd95-41e9-8601-4ff384c432cf.png) Then you can access it. ![image](https://user-images.githubusercontent.com/12268675/248710046-10abd305-d974-439b-a715-e72da44d53f6.png)

我通过minio web console 上传了file,
![image](https://github.com/milvus-io/milvus/assets/18379253/4c9901d5-8bf2-424f-99e4-6ec8aa66d4ab)

```java
BulkInsertParam param = BulkInsertParam.newBuilder()
        .withCollectionName("book")
        .addFile("agan.json")
        .build()```
此时这个file应该是什么路径 是/a-bucket/agan.json吗

**Comment by zhuwenxing** [comment]
@ganhb 
a relative path to the bucket. so it is just `agan.json`

**Comment by 670133189** [comment]
Thank you for your reply. With your guidance, I have successfully uploaded using **minio sdk** and imported in bulk through `.utility.get_bulk_insert_state()`.

I suggest posting a simple code uploaded through **minio sdk** on the "https://milvus.io/docs/bulk_insert.md" for users to quickly get started.
For example:

```
from minio import Minio # pip3 install minio

def main():
    client = Minio(
        "x.x.x.x:9000",
        access_key="minioadmin",
        secret_key="minioadmin",
        secure=False
    )

    bucket = "a-bucket"

    if not client.bucket_exists(bucket):
        client.make_bucket(bucket)

    try:
        res = client.fput_object(
            bucket_name=bucket,
            object_name="xxx.json",
            file_path="/xxx/xxx.json",
            part_size=500 * 1024, # 500k
            num_parallel_uploads=3
        )

        print(res.object_name)
    except Exception as err:
        print(err)

if __name__ == "__main__":
    main()
```

**Comment by bygzyz** [comment]
@zhuwenxing in docker-compose.yml, i change milvus-standalone's     
environment:
      MINIO_BUCKETNAME: milvus-data

the milvus-minio has a bucket named milvus-data as the data storage bucket, but when i use ./milvus-backup create, got errors: 
 [WARN] [storage/minio_chunk_manager.go:437] ["listWithPrefix error"] [bucket=milvus-data] [prefix=files/insert_log/456138580661258187/456138580661258192/457094595417019657/0/457094595417019666] [error="The specified bucket does not exist"]
