### ISSUE TITLE
[Bug]: grpc: received message larger than max

### ISSUE THREAD

**Issue by cuisws** [milvus-io/milvus#25149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.10
- Deployment mode(standalone or cluster):standalone 
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.2.12
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Insert 5w pieces of data

### Expected Behavior

success

### Milvus Log

pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.RESOURCE_EXHAUSTED
	details = "grpc: received message larger than max (327989637 vs. 67108864)"
	debug_error_string = "{"created":"@1687766568.030000000","description":"Error received from peer ipv4:8.140.158.98:19530","file":"src/core/lib/surface/call.cc","file_line":967,"grpc_message":"grpc: received message larger than max (327989637 vs. 67108864)","grpc_status":8}"

### Anything else?

When the Milvus version is 2.1.4, there is no problem inserting the same data

**Comment by xiaofan-luan** [comment]
milvus add the limitaiton to 64M.

Currently then insert is more than 300M and is too large. I would suggest to split the data into chunks before insert.

On the otherside, you can change the configs to increase the config to 512m to solve this issue

**Comment by yanliang567** [comment]
@cuisws we added the limit as comments above. 

/assign @cuisws 
/unassign

**Comment by cuisws** [comment]
> milvus add the limitaiton to 64M.
> 
> Currently then insert is more than 300M and is too large. I would suggest to split the data into chunks before insert.
> 
> On the otherside, you can change the configs to increase the config to 512m to solve this issue

Thank you for your answer

So, is the restriction modified through the serverMaxSendSize configuration item in grpc under milvus.yaml?
