### ISSUE TITLE
[Bug]: Error: INSTALLATION FAILED: Get "https://github.com/milvus-io/milvus-helm/releases/download/milvus-4.0.25/milvus-4.0.25.tgz": unexpected EOF

### ISSUE THREAD

**Issue by HongLouyemeng** [milvus-io/milvus#25156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Centos7
- CPU/Memory: 16G
- GPU: 
- Others:
```

### Current Behavior

helm install my-release milvus/milvus --set cluster.enabled=false --set etcd.replicaCount=1 --set minio.mode=standalone --set pulsar.enabled=false

**Comment by HongLouyemeng** [comment]
I am a k8s newbie, so I can only feedback the final error to you, before I configured daemon.json.milvus really hard to install.

**Comment by locustbaby** [comment]
@HongLouyemeng Already solved?
