### ISSUE TITLE
[Enhancement]:  Add errcode info to minio chunk manager exception

### ISSUE THREAD

**Issue by zhagnlu** [milvus-io/milvus#25153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Before, minio chunkmanager only output error message to exception. But aws sdk give not matched message to user in some situation.  For example, for request with only header response, sdk will hide real info to caller,  So add a response code to help  developer to find the true cause.

**Comment by xiaofan-luan** [comment]
does this has to be on 2.2 also?

**Comment by zhagnlu** [comment]
> does this has to be on 2.2 also?

yes, I will cherry-pick it to 2.2
