### ISSUE TITLE
[Bug]: During concurrent searches, some requests remain stuck and do not return

### ISSUE THREAD

**Issue by yesletgo** [milvus-io/milvus#25150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.10  2.2.8 
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 72 cores/ 550G
- GPU: 
- Others:
```

### Current Behavior

A total of 30 million data, with an index type of HNSW and topk 1000, ef is 1000.

1:During concurrent searches, some requests remained stuck and did not return. For example, 5 concurrent 10 concurrent or more.

2: milvus vesion 2.2.10 is lower then milvus vesion 2.2.8. For example, with 5 concurrent, 2.2.8 seach time is 700ms,but 2.2.10 search time is 2s.

### Milvus Log

**milvus 2.2.10:**
https://video-tag-lib-1251808348.cos.ap-beijing.myqcloud.com/milvus_log/logs_new_milvus_2.2.10_202306266h.tar.gz

**milvus 2.2.8:**
https://video-tag-lib-1251808348.cos.ap-beijing.myqcloud.com/milvus_log/logs_new_milvus_2.2.8_202306266h.tar.gz

**Comment by yanliang567** [comment]
@yesletgo thank you for the feedback. I did not find any search requests in the 2.2.10 logs, could you please help to reproduce the issue and recollect the logs?
also I assume that your question is that milvus 2.2.10 has bigger search latency than v2.2.8, am I right? could you please attach the milvus metric with grafana if convenient. 

/assign @yesletgo

**Comment by yesletgo** [comment]
> @yesletgo thank you for the feedback. I did not find any search requests in the 2.2.10 logs, could you please help to reproduce the issue and recollect the logs? also I assume that your question is that milvus 2.2.10 has bigger search latency than v2.2.8, am I right? could you please attach the milvus metric with grafana if convenient.
> 
> /assign @yesletgo

Now I have set up 2.2.8 through Milvus operator again, and the issue of not returning has not occurred. However, with sufficient resources, a single digit concurrency of 30 million data is very slow, with 1 concurrency of 600ms, 5 concurrency of 1.2s,  20 concurrency of 3s, and 10 concurrency of 1.6s .
mivus grafana:
https://snapshots.raintank.io/dashboard/snapshot/eJWXlA74aXsHnQ6XXzDzj2oi102rzcVi
server grafana:
https://snapshots.raintank.io/dashboard/snapshot/VBCP93W88rucupFyK5HjyihwuyyK6KXb

**Comment by xiaofan-luan** [comment]
> > @yesletgo thank you for the feedback. I did not find any search requests in the 2.2.10 logs, could you please help to reproduce the issue and recollect the logs? also I assume that your question is that milvus 2.2.10 has bigger search latency than v2.2.8, am I right? could you please attach the milvus metric with grafana if convenient.
> > /assign @yesletgo
> 
> Now I have set up 2.2.8 through Milvus operator again, and the issue of not returning has not occurred. However, with sufficient resources, a single digit concurrency of 30 million data is very slow, with 1 concurrency of 600ms, 5 concurrency of 1.2s, 20 concurrency of 3s, and 10 concurrency of 1.6s . mivus grafana: https://snapshots.raintank.io/dashboard/snapshot/eJWXlA74aXsHnQ6XXzDzj2oi102rzcVi https://snapshots.raintank.io/dashboard/snapshot/akRTYogDt5zl2Kda6qPkGNzOC2L3M0o9 server grafana: https://snapshots.raintank.io/dashboard/snapshot/KaxtQyo6nXYGucG4ldkXdUXoSVIGkXU8 https://snapshots.raintank.io/dashboard/snapshot/yb8juGHvfwFbsPCvxmqD9d5bZASEx3Zs https://snapshots.raintank.io/dashboard/snapshot/JujhzFyGX1LHW6MCV2mTLwvuSlM0pFSq
> 
> Why queue for a long time when single digit concurrency occurs ？ ![image](https://user-images.githubusercontent.com/21998052/251096933-877a3871-85d5-49e7-8278-fdd97309d53d.png)

thanks for the detailed metrics.
Looks like you have many segments, could you give us some details about how you insert you data?
1. how many partitions do you have?
2. did you run manual flush operations?
3. when you do search, did you only search partial partitions or the whole collection?
Could you share you code about how you do ingest and search?
<img width="481" alt="image" src="https://github.com/milvus-io/milvus/assets/83447078/f648faa9-60e4-4647-b276-f9ccbb8dd3ee">

**Comment by yanliang567** [comment]
@yesletgo Thank you for detailed feedback, it helps a lot. Could you please attach the etcd backup for investigation？ Check this: https://github.com/milvus-io/birdwatcher for details about how to backup etcd with birdwatcher

**Comment by yesletgo** [comment]
> > > @yesletgo thank you for the feedback. I did not find any search requests in the 2.2.10 logs, could you please help to reproduce the issue and recollect the logs? also I assume that your question is that milvus 2.2.10 has bigger search latency than v2.2.8, am I right? could you please attach the milvus metric with grafana if convenient.
> > > /assign @yesletgo
> > 
> > 
> > Now I have set up 2.2.8 through Milvus operator again, and the issue of not returning has not occurred. However, with sufficient resources, a single digit concurrency of 30 million data is very slow, with 1 concurrency of 600ms, 5 concurrency of 1.2s, 20 concurrency of 3s, and 10 concurrency of 1.6s . mivus grafana: https://snapshots.raintank.io/dashboard/snapshot/eJWXlA74aXsHnQ6XXzDzj2oi102rzcVi https://snapshots.raintank.io/dashboard/snapshot/akRTYogDt5zl2Kda6qPkGNzOC2L3M0o9 server grafana: https://snapshots.raintank.io/dashboard/snapshot/KaxtQyo6nXYGucG4ldkXdUXoSVIGkXU8 https://snapshots.raintank.io/dashboard/snapshot/yb8juGHvfwFbsPCvxmqD9d5bZASEx3Zs https://snapshots.raintank.io/dashboard/snapshot/JujhzFyGX1LHW6MCV2mTLwvuSlM0pFSq
> > Why queue for a long time when single digit concurrency occurs ？ ![image](https://user-images.githubusercontent.com/21998052/251096933-877a3871-85d5-49e7-8278-fdd97309d53d.png)
> 
> thanks for the detailed metrics. Looks like you have many segments, could you give us some details about how you insert you data?
> 
> 1. how many partitions do you have?
> 2. did you run manual flush operations?
> 3. when you do search, did you only search partial partitions or the whole collection?
>    Could you share you code about how you do ingest and search?
> 
> <img alt="image" width="481" src="https://user-images.githubusercontent.com/83447078/251126586-f648faa9-60e4-4647-b276-f9ccbb8dd3ee.png">



> > > @yesletgo thank you for the feedback. I did not find any search requests in the 2.2.10 logs, could you please help to reproduce the issue and recollect the logs? also I assume that your question is that milvus 2.2.10 has bigger search latency than v2.2.8, am I right? could you please attach the milvus metric with grafana if convenient.
> > > /assign @yesletgo
> > 
> > 
> > Now I have set up 2.2.8 through Milvus operator again, and the issue of not returning has not occurred. However, with sufficient resources, a single digit concurrency of 30 million data is very slow, with 1 concurrency of 600ms, 5 concurrency of 1.2s, 20 concurrency of 3s, and 10 concurrency of 1.6s . mivus grafana: https://snapshots.raintank.io/dashboard/snapshot/eJWXlA74aXsHnQ6XXzDzj2oi102rzcVi https://snapshots.raintank.io/dashboard/snapshot/akRTYogDt5zl2Kda6qPkGNzOC2L3M0o9 server grafana: https://snapshots.raintank.io/dashboard/snapshot/KaxtQyo6nXYGucG4ldkXdUXoSVIGkXU8 https://snapshots.raintank.io/dashboard/snapshot/yb8juGHvfwFbsPCvxmqD9d5bZASEx3Zs https://snapshots.raintank.io/dashboard/snapshot/JujhzFyGX1LHW6MCV2mTLwvuSlM0pFSq
> > Why queue for a long time when single digit concurrency occurs ？ ![image](https://user-images.githubusercontent.com/21998052/251096933-877a3871-85d5-49e7-8278-fdd97309d53d.png)
> 
> thanks for the detailed metrics. Looks like you have many segments, could you give us some details about how you insert you data?
> 
> 1. how many partitions do you have?
> 2. did you run manual flush operations?
> 3. when you do search, did you only search partial partitions or the whole collection?
>    Could you share you code about how you do ingest and search?
> 
> <img alt="image" width="481" src="https://user-images.githubusercontent.com/83447078/251126586-f648faa9-60e4-4647-b276-f9ccbb8dd3ee.png">
1.
only three partition and one partition has data.
![image](https://github.com/milvus-io/milvus/assets/21998052/57183d09-f865-4ca8-95fe-c529b443f867)
2. I didn't do it manually flush.
3. search the whole collection
4.
insert by bulkinsert.
![image](https://github.com/milvus-io/milvus/assets/21998052/43de6fa3-49d3-4031-bd70-b47ab8682109)
![image](https://github.com/milvus-io/milvus/assets/21998052/37a8b980-bfae-4a09-8c28-e5e172c17f4b)
![image](https://github.com/milvus-io/milvus/assets/21998052/022e0991-af24-4a8d-a1d8-2cd6002c4e2a)
seach:
![image](https://github.com/milvus-io/milvus/assets/21998052/3202ef85-05ab-4020-b6df-adc6bedbbb9b)

**Comment by yanliang567** [comment]
@yesletgo what is the dim of your vectors? I think there are too many segments for a 30m collection with ~1000 segments.  Could you please attach the etcd backup for investigation？ Check this: https://github.com/milvus-io/birdwatcher for details about how to backup etcd with birdwatcher

**Comment by xiaofan-luan** [comment]
The bulkinsert file size is too small.
You can try to trigger one compaction manually and see if the performance improved

**Comment by xiaofan-luan** [comment]
on the otherside, I believe compaction and index build should happened. you could check your indexnode cpu usage see if there are still many compaction and insert operations?

**Comment by yesletgo** [comment]
> @yesletgo what is the dim of your vectors? I think there are too many segments for a 30m collection with ~1000 segments. Could you please attach the etcd backup for investigation？ Check this: https://github.com/milvus-io/birdwatcher for details about how to backup etcd with birdwatcher
My vector is 1024 dim.  I inserted data through bulkinsert with  500M per file to test performance. After I finished inserting, I started concurrent testing.
I found some things :
How can port 2379 of ETCD be mapped out for clusters installed through milvus operator? I am modifying from clusterIp to NodePort through kubectl edit svc my release etcd type, butI don't think it's correct. The birdwatch show collection is empty, and there is no other data available.  Is it right ?

![image](https://github.com/milvus-io/milvus/assets/21998052/fc62edad-3213-4dce-9087-c1b9c139b392)
![image](https://github.com/milvus-io/milvus/assets/21998052/7c818be5-da3e-4c42-bc27-83643956ff96)

**Comment by yesletgo** [comment]
> > on the otherside, I believe compaction and index build should happened. you could check your indexnode cpu usage see if there are still many compaction and insert operations?
> 
 You are right. At that time, the search was slow. Although bulksert was already completed, compact was in progress and now compact ended. The search for 1 to 100 concurrent times ranged from 400 to 900 milliseconds.
![image](https://github.com/milvus-io/milvus/assets/21998052/596f487c-c6f9-4d2b-9f44-eefecb97a206)
![image](https://github.com/milvus-io/milvus/assets/21998052/15e7bb3f-6d91-4f84-854a-b0228b2bb9a2)
![image](https://github.com/milvus-io/milvus/assets/21998052/e79f90dc-6f5c-4b96-a159-3a8883ca6aad)


Each file in the bulkset is 500MB, and your team told me that 1GB is the best practice. I also want to know that if the file is large, it is equivalent to a large Java object, and the Java heap is easy to fill

**Comment by yesletgo** [comment]
> The bulkinsert file size is too small. You can try to trigger one compaction manually and see if the performance improved

I set each file in the bulkset is 500MB,and your team told me that 1GB is the best practice. I also want to know that if the file is large, it is equivalent to a large Java object, and the Java heap is easy to fill.

Cluster configuration segment 2G, querynode 40G.

<img width="946" alt="1688613165614" src="https://github.com/milvus-io/milvus/assets/21998052/3ee9cf7a-bc88-422b-a5ff-c5f96853b0d8">

![1688613165662](https://github.com/milvus-io/milvus/assets/21998052/a38e2883-310d-4344-ac63-0b16f7ea5132)

![1688614178025](https://github.com/milvus-io/milvus/assets/21998052/b2f47984-e443-470f-ad07-a1053de61b50)
<img width="942" alt="1688614189840" src="https://github.com/milvus-io/milvus/assets/21998052/03f8ba55-c6e6-478d-ae05-d7f92ad657be">

**Comment by yesletgo** [comment]
After continuous attempts, export the etcd using the following command,
‘connect -- etcd my-release-etcd-headless. default. svc. cluster. local: 2379 --rootPath my-release ’

https://video-tag-lib-1251808348.cos.ap-beijing.myqcloud.com/milvus_log/bw_etcd_ALL.230601-175320.bak.gz

https://video-tag-lib-1251808348.cos.ap-beijing.myqcloud.com/milvus_log/k8s_logs_0706_36h.tar.gz

**Comment by yesletgo** [comment]
Now I have to manually trigger compact, but it doesn't seem to work.

It has been in the following state for a long time.
 R{status=0, data=status {
}
state: Executing
executingPlanNo: 60
}

**Comment by xiaofan-luan** [comment]
could you offer datanode and datacoord log so we can expect why compaction is not happening?

**Comment by yanliang567** [comment]
I see healthy collections in the backup file. All the segments are small and need to be compacted.  Need to figure out why it did not.
```
SegmentID: 441420634105182642 State: Flushed, Row Count:5992
SegmentID: 441420634105182856 State: Flushed, Row Count:6077
SegmentID: 441420634105182936 State: Flushed, Row Count:6102
--- Growing: 0, Sealed: 0, Flushed: 850
--- Total Segments: 850, row count: 9471269
```

**Comment by yesletgo** [comment]
> 

Yea, I have manually called compact, but it has no effect.

**Comment by yanliang567** [comment]
@yesletgo any chance you could retry on milvus v2.2.13, which has a fix on compaction
