### ISSUE TITLE
[Bug]: cannot parse expression: exist 

### ISSUE THREAD

**Issue by NaivePawn** [milvus-io/milvus#25157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

mycode
ms.query(connection_name, query_embedding, 10, expr='exist stock_id_list["stock_ids"]')

error
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=failed to create query plan: cannot parse expression: exist stock_id_list["stock_ids"], error: invalid expression: exist stock_id_list["stock_ids"])>

**Comment by NaivePawn** [comment]
in this document, "exist" op can work, but when i use 'exist', i got this error[https://milvus.io/docs/json_data_type.md](url)

**Comment by xiaofan-luan** [comment]
what milvus is it?
I believe this is supported on 2.2.10 @xiaocai2333

**Comment by xiaocai2333** [comment]
@NaivePawn @xiaofan-luan sorry about it, the keyword we support is `exists`, not `exist`. It's a documentation error, and we will correct it immediately.

**Comment by xiaocai2333** [comment]
https://milvus.io/docs/json_data_type.md  has fixed.
/close

**Comment by geeker-smallwhite** [comment]
> https://milvus.io/docs/json_data_type.md has fixed. /close

The link won't open

**Comment by xiaocai2333** [comment]
> > https://milvus.io/docs/json_data_type.md has fixed. /close
> 
> The link won't open

@geeker-smallwhite 
https://milvus.io/docs/use-json-fields.md   The page is updated.
 The keyword is `exists`, not `exist`.
