### ISSUE TITLE
[Feature]: The array attribute of the JSON data type should support intersection queries.

### ISSUE THREAD

**Issue by pofey** [milvus-io/milvus#25162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

json data:
`{ "genre": ["comedy", "documentary"] }`

I need to query data where the genre includes 'documentary' and 'plot' values, which is currently not supported. However, Pinecone can implement this with the $in keyword.

For example, queries with the following filters will match the vector:
`{"genre": {"$in":["documentary","action"]}}`

**Comment by jiaoew1991** [comment]
Hi @pofey Would you like to contribute this feature?

**Comment by pofey** [comment]
> 

I'm sorry, I just stated my needs. Did I choose the wrong category?

**Comment by pofey** [comment]
> Hi @pofey Would you like to contribute this feature?

I'm sorry, I just stated my needs. Did I choose the wrong category?

**Comment by jiaoew1991** [comment]
> > Hi @pofey Would you like to contribute this feature?
> 
> I'm sorry, I just stated my needs. Did I choose the wrong category?

Nope, feel free to open issues. we will put the feature in backlog until someone working on it.

**Comment by pofey** [comment]
> > > Hi @pofey Would you like to contribute this feature?
> > 
> > 
> > I'm sorry, I just stated my needs. Did I choose the wrong category?
> 
> Nope, feel free to open issues. we will put the feature in backlog until someone working on it.

Thank you for your support. Could I know approximately how long it would take to complete this support?

**Comment by jiaoew1991** [comment]
The support for the array type is already on the roadmap and is expected to be available in the 2.3.x series around August, If it doesn't go smoothly, it will go to a later version. Functions like intersection and difference will be supported first on the array type.

**Comment by wuyf1831** [comment]
Hi @jiaoew1991 I'm new to this community and I would like to contribute. But I recognized that you said this feather is on the roadmap and will be available soon, so I wonder if this issue is available to be assigned now. If it's available, can you tell me where to get started?

**Comment by xiaofan-luan** [comment]
I thought these on two different functionalities? 
currently milvus already support json_contains functionalities,  I guess it already support contains a list?
@xiaocai2333

**Comment by xiaocai2333** [comment]
> I thought these on two different functionalities? currently milvus already support json_contains functionalities, I guess it already support contains a list? @xiaocai2333

@xiaofan-luan @pofey  We currently do not support lists, but this requirement can be converted to `json_contains(genre, action) or json_contains(genre, documentary)` . Moreover, this feature is only available in version 2.3.

**Comment by xiaocai2333** [comment]
@xiaofan-luan  Additionally, I think that to fulfill this requirement, it would be beneficial to introduce a new function called `json_contains_any(array, list or element)`.

**Comment by xiaofan-luan** [comment]
> json_contains_any

Is there a reason json_contains can not cover it?

**Comment by xiaocai2333** [comment]
> > json_contains_any
> 
> Is there a reason json_contains can not cover it?

It can achieve this functionality by combining `json_contains` with `or`. Currently, `json_contains` does not support elements that are lists, but if necessary, I will prioritize supporting it.

**Comment by xiaocai2333** [comment]
trace by  #25276

**Comment by jiaoew1991** [comment]
track the feature in https://github.com/milvus-io/milvus/issues/25276, close it
