### ISSUE TITLE
[Bug]: After importing data through .do_bulk_insert(), an additional "Entities ID" will be added.

### ISSUE THREAD

**Issue by 670133189** [milvus-io/milvus#25168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.10
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.9
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 4/32
- GPU: 0
- Others:
```

### Current Behavior

Hello, I found that after importing data through `.do_bulk_insert()`, the `.get_bulk_insert_state()` of the result will display an additional ID, such as:

```
Imported row count: 3
Entities ID array generated by this task: [442452833759602372, 442452833759602373, 442452833759602374, 442452833759602375]
```

The last **442452833759602375** is not in the current search results, and after importing it again, **442452833759602375** will appear in the first place (_Entities ID array generated by this task_). Afterwards, a new seemingly redundant **442452833759602378** will also appear at the end:

```
Imported row count: 3
Entities ID array generated by this task: [442452833759602375, 442452833759602376, 442452833759602377, 442452833759602378]
```

Therefore, what is the purpose of the ID at the end after performing the import?

**Comment by yhmo** [comment]
Good catch!
This is a bug of SDK side. The last id is redundant.

**Comment by yhmo** [comment]
This bug only exist on python sdk. Fixed by this pr  https://github.com/milvus-io/pymilvus/pull/1620

**Comment by yhmo** [comment]
Already fixed on sdk side.
