### ISSUE TITLE
[Bug]: hree pods are normal, but can not connect milvus what is the reason

### ISSUE THREAD

**Issue by HongLouyemeng** [milvus-io/milvus#25167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.10
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Centos7
- CPU/Memory: 16G
- GPU: 
- Others:
```

### Current Behavior

python3.8 hello_milvus.py
![image](https://github.com/milvus-io/milvus/assets/48181529/92618f2a-3419-4795-8390-12319c595c60)

![image](https://github.com/milvus-io/milvus/assets/48181529/186af243-02e9-4bf6-a438-d85b42c43141)

### Milvus Log

I installed it by helm, and using log export can only export 3 empty folders

**Comment by HongLouyemeng** [comment]
![image](https://github.com/milvus-io/milvus/assets/48181529/98cb495e-e478-4da3-aeb0-53334d8f1374)

**Comment by xiaofan-luan** [comment]
could you try to ping or telnet 19530 see if the network is available?

**Comment by HongLouyemeng** [comment]
> could you try to ping or telnet 19530 see if the network is available?

My script was started locally and there is no firewall installed. It's strange that Milvus cannot connect

**Comment by HongLouyemeng** [comment]
https://github.com/milvus-io/milvus/issues/1664#issuecomment-1487681553 solve my problem
