### ISSUE TITLE
[Bug]: Can't build an index on scalars with java sdk.

### ISSUE THREAD

**Issue by Linzaer** [milvus-io/milvus#25164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.10
- Deployment mode(standalone or cluster): standalone 
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): java-sdk 2.2.7
- OS(Ubuntu or CentOS): Centos
- CPU/Memory:  Intel(R) Xeon(R) Platinum 8369B CPU @ 2.90GHz/ 128G
- GPU: A100
- Others:
```

### Current Behavior

1. Java SDK does not support scalar index types .
2. Currently the Java sdk must pass MetricType .

### Expected Behavior

1. Java SDK support scalar index types .
2. No need to pass MetricType .

### Steps To Reproduce

```markdown
1.The type of 'FileVectorConst.Field.FILE_ID' is Int64.
2.R<RpcStatus> fileIdResponse = milvusClient.createIndex(CreateIndexParam.newBuilder()
                .withCollectionName(collectionName)
                .withFieldName(FileVectorConst.Field.FILE_ID)
                .withIndexName("idx_file_id")
                .withExtraParam("{\"index_type\":\"sort\"}")
                .withSyncMode(Boolean.FALSE)
                .build());
```

**Comment by yhmo** [comment]
Index for scalar is supported in Java SDK v2.2.9
Example: https://github.com/milvus-io/milvus-sdk-java/blob/65ae173dd7bd2ee15df9ad8d25527a07c2c4d1af/examples/main/java/io/milvus/SimpleExample.java#L90
