### ISSUE TITLE
[Enhancement]: Milvus Cpp S3 call too many headObjects request, which is very expensive

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#25189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

We should avoid calling unnecessary headObjects and it may trigger rate limiter of S3 and is very expensive operations

**Comment by yah01** [comment]
I'm working on optimizing the load op, changing it to load batch by batch, then we don't need to call `HeadObject` to calculate the concurrent level

**Comment by yah01** [comment]
related #25142

**Comment by xiaofan-luan** [comment]
Good to know!
This seems to be very important for the memory usage

**Comment by yah01** [comment]
Keep it

**Comment by yah01** [comment]
related #25642
