### ISSUE TITLE
[Bug]: Invalid Go Module setup

### ISSUE THREAD

**Issue by ramialt** [milvus-io/milvus#25190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2+
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Cannot install Milvus v2 with `go install github.com/milvus-io/milvus@latest`.
This gives output: `go: downloading github.com/milvus-io/milvus v1.1.1` and continues

### Expected Behavior

Expect to be able to download milvus v2 and later

**Comment by yanliang567** [comment]
@ramialt thank you for the feedback.
I don't quite get the problem. if you want o install milvus, please refer here: https://milvus.io/docs/install_standalone-docker.md

/assign @ramialt 
/unassign

**Comment by congqixia** [comment]
Hi @ramialt currently, Milvus does not support to be imported as dependency. It is recommended to use compiled binary or images.
Could you please elaborate why is it needed to import milvus as a thirdparty lib in your project?

**Comment by ramialt** [comment]
Sorry, I will use the provided install docs
