### ISSUE TITLE
[Bug]: [benchmark][growing segment] After the growing segment index is turned on, the growing segment increases the memory usage by about 20%~30% compared to the previous one.

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#25228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230426-ed8836cd 
- Deployment mode(standalone or cluster):both
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Shard number: 1
Segment number: 1
Segment type: Growing segment

We compare the memory comparison between pure growing segment with indexing on and without indexing on and find that the memory increase is higher, about 20 to 30%. The growing segment memory needs to be optimized

#### standalone:
 
**No growing segment index:**
<img src="https://github.com/milvus-io/milvus/assets/48523564/4b41c072-b0e9-49ae-9611-40bfb2ce9d10" width=60% />

**Turn on growing segment index:**
<img src="https://github.com/milvus-io/milvus/assets/48523564/edbf00aa-b839-4dea-bf45-4b1cb2e978a3" width=60% />

#### cluter querynode memory usage:
**No growing segment index:**
<img src="https://github.com/milvus-io/milvus/assets/48523564/88abe593-c167-45b5-a3bc-dbbc94f65d0e" width=60%/>
**Turn on growing segment index:**
<img src="https://github.com/milvus-io/milvus/assets/48523564/5ab09e98-0c1d-4c6c-87a1-fdb4761ddf76" width=60%/>

### Expected Behavior

Turning on growing segment index uses more memory as expected, but some optimizations can be made so that memory does not grow as much when indexing is turned on

### Steps To Reproduce

```markdown
1. modify the parameters of segment in milvus.yaml to keep segment as growing 
2. set the parameters on the client side and set the number of shards
3. create a collection
4. build the index
5. insert vector
6. build the index
7. load collection
8. concurrent search
```

**Comment by xiaofan-luan** [comment]
@foxspy 
Is this because the trained data not released issue?

**Comment by elstic** [comment]
After verification, I believe that the memory usage is as expected.   
Verified image: master-20230707-2d1ed6af

#### standalone: 

close growing segment index, memory usage:
![image](https://github.com/milvus-io/milvus/assets/48523564/fd047227-743f-4d65-90a6-de3e93b8c946)


open growing segment index, memory usage:
![image](https://github.com/milvus-io/milvus/assets/48523564/de52c3d5-4944-4f1e-a92c-aceb325e75de)



#### cluster:
close growing segment index, querynode memory usage:
![image](https://github.com/milvus-io/milvus/assets/48523564/6c62a404-e557-432a-ac93-e8bfd3b91ea1)

open growing segment index, querynode memory usage:
![image](https://github.com/milvus-io/milvus/assets/48523564/1fa497dd-efc8-4dc4-bf6b-dd633ffb5a64)
