### ISSUE TITLE
[Bug]: Small segments(row#<1024) without index maybe discorded in corner case

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#25234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 8750be1
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

All segment without index(not completed and Small Segment) all loaded as growing one.
Say small segments (100,100,100)  are compacted into new small one, it will still be treated as growing one BUT WILL NOT BE LOADED
If the old one meet the criteria in which they could be released, the data integrity will be damaged

### Expected Behavior

Small segment index shall be treated as sealed segment

### Anything else?

The could lead to lots of unstable CI cases failure

**Comment by xiaofan-luan** [comment]
so we need to build a fake index on these files?

**Comment by congqixia** [comment]
> so we need to build a fake index on these files?

@xiaofan-luan IMO it's ok to leave them in sealed segment list, querynode shall handle this case (sealed segment without index) and execute brute-force search automatically.

**Comment by congqixia** [comment]
Next step is to support in-place segment replacement, closing this issue
