### ISSUE TITLE
[Enhancement]: Collection schema should not be cached while switching alias

### ISSUE THREAD

**Issue by soothing-rain** [milvus-io/milvus#25239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

See:
https://github.com/milvus-io/milvus/issues/25040

The root cause is that the schema of a project is cached, for example `collection.description`, `collection.name`, `collection.num_shards`. These cached fields will not be updated when collection alias is altered.

(The good thing is, after altering the collection alias, the old collection object will be pointed to the correct collection. Only the schema is wrongly cached and returned.)

**Comment by xiaofan-luan** [comment]
so the cache is on SDK?
I think describe and other operation might need to skip cache

**Comment by soothing-rain** [comment]
@XuanYang-cn WDYT?
