### ISSUE TITLE
[Bug]: QueryNode Graceful stop always get timeout (30s)

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#25249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.x
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The `Stop` tries to wait all segments released by a channel, but this channel never works as expected, the `Stop` method always takes 30s timeout if any segment exists

**Comment by SimFG** [comment]
What is the approximate size of the data

**Comment by yah01** [comment]
This channel never get closed as there is any segment, so the `Stop` method always waits until timeout
