### ISSUE TITLE
[Bug]: 2核4G机器x3台，插入3百万条数据后，连接不上了

### ISSUE THREAD

**Issue by llllyq77** [milvus-io/milvus#25261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

RPC error: [__internal_register], <MilvusException: (code=56, message=role rootcoord[nodeID: 0] is not serving, reason: sate c
ode: Abnormal)>, <Time:{'RPC start': '2023-06-30 15:13:49.109418', 'RPC error': '2023-06-30 15:13:55.685253'}>
---------------------------------------------------------------------------
MilvusException                           Traceback (most recent call last)
File ~/anaconda3/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py:120, in GrpcHandler._wait_for_channel_ready(self
, timeout)
    119 grpc.channel_ready_future(self._channel).result(timeout=timeout)
--> 120 self._setup_identifier_interceptor(self._user)
    121 return

File ~/anaconda3/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py:220, in GrpcHandler._setup_identifier_intercepto
r(self, user)
    219 host = socket.gethostname()
--> 220 self._identifier = self.__internal_register(user, host)
    221 self._identifier_interceptor = interceptor.header_adder_interceptor(["identifier"], [str(self._identifier)])

File ~/anaconda3/lib/python3.10/site-packages/pymilvus/decorators.py:109, in error_handler.<locals>.wrapper.<locals>.handler(*
args, **kwargs)
    108     LOGGER.error(f"RPC error: [{inner_name}], {e}, <Time:{record_dict}>")
--> 109     raise e
    110 except grpc.FutureTimeoutError as e:

File ~/anaconda3/lib/python3.10/site-packages/pymilvus/decorators.py:105, in error_handler.<locals>.wrapper.<locals>.handler(*
args, **kwargs)
    104     record_dict["RPC start"] = str(datetime.datetime.now())
--> 105     return func(*args, **kwargs)
    106 except MilvusException as e:

File ~/anaconda3/lib/python3.10/site-packages/pymilvus/decorators.py:136, in tracing_request.<locals>.wrapper.<locals>.handler
(self, *args, **kwargs)
    135     self.set_onetime_request_id(req_id)
--> 136 ret = func(self, *args, **kwargs)
    137 return ret

File ~/anaconda3/lib/python3.10/site-packages/pymilvus/decorators.py:85, in retry_on_rpc_failure.<locals>.wrapper.<locals>.han
dler(self, *args, **kwargs)
     84     else:
---> 85         raise e
     86 except Exception as e:

File ~/anaconda3/lib/python3.10/site-packages/pymilvus/decorators.py:50, in retry_on_rpc_failure.<locals>.wrapper.<locals>.han
dler(self, *args, **kwargs)
     49 try:
---> 50     return func(self, *args, **kwargs)
     51 except grpc.RpcError as e:
     52     # DEADLINE_EXCEEDED means that the task wat not completed
     53     # UNAVAILABLE means that the service is not reachable currently
     54     # Reference: https://grpc.github.io/grpc/python/grpc.html#grpc-status-code

File ~/anaconda3/lib/python3.10/site-packages/pymilvus/decorators.py:171, in upgrade_reminder.<locals>.handler(*args, **kwargs
)
    170 except Exception as e:
--> 171     raise e

File ~/anaconda3/lib/python3.10/site-packages/pymilvus/decorators.py:163, in upgrade_reminder.<locals>.handler(*args, **kwargs
)
    162 try:
--> 163     return func(*args, **kwargs)
    164 except grpc.RpcError as e:
]
File ~/anaconda3/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py:1361, in GrpcHandler.__internal_register(self, u
ser, host)
   1360 if response.status.error_code != common_pb2.Success:
-> 1361     raise MilvusException(response.status.error_code, response.status.reason)
   1362 return response.identifier

MilvusException: <MilvusException: (code=56, message=role rootcoord[nodeID: 0] is not serving, reason: sate code: Abnormal)>

The above exception was the direct cause of the following exception:

MilvusException                           Traceback (most recent call last)
Cell In[2], line 1
----> 1 c = connections.connect("default", host="10.175.192.63", port="19530")

File ~/anaconda3/lib/python3.10/site-packages/pymilvus/orm/connections.py:349, in Connections.connect(self, alias, user, passw
ord, db_name, token, **kwargs)
    345         if parsed_uri.scheme == "https":
    346             kwargs["secure"] = True
--> 349     connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
    350     return
    352 # 2nd Priority, connection configs from env

File ~/anaconda3/lib/python3.10/site-packages/pymilvus/orm/connections.py:282, in Connections.connect.<locals>.connect_milvus(
**kwargs)
    279 t = kwargs.get("timeout")
    280 timeout = t if isinstance(t, (int, float)) else Config.MILVUS_CONN_TIMEOUT
--> 282 gh._wait_for_channel_ready(timeout=timeout)
    283 kwargs.pop('password')
    284 kwargs.pop("token", None)

File ~/anaconda3/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py:123, in GrpcHandler._wait_for_channel_ready(self
, timeout)
    121         return
    122     except (grpc.FutureTimeoutError,  MilvusException) as e:
--> 123         raise MilvusException(Status.CONNECT_FAILED,
    124                               f'Fail connecting to server on {self._address}. Timeout') from e
    126 raise MilvusException(Status.CONNECT_FAILED, 'No channel in handler, please setup grpc channel first')

MilvusException: <MilvusException: (code=2, message=Fail connecting to server on 10.175.192.63:19530. Timeout)>

**Comment by yanliang567** [comment]
@llllyq77 thank you for the feedback, but we need more info to investigate the issue. Which milvus version are you running, and how did you deploy milvus? 
According to the error msg, i guess the etcd or pulsar is not working well at that time. Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs so that we could address the issue?

/assign @llllyq77 
/unassign

**Comment by llllyq77** [comment]
![image](https://github.com/milvus-io/milvus/assets/131153740/5fa92e52-28a0-40c4-bcc9-b56b965642e9)

**Comment by llllyq77** [comment]
![image](https://github.com/milvus-io/milvus/assets/131153740/88988903-8cd7-48f7-8261-a51ff4682d3c)

**Comment by llllyq77** [comment]
> @llllyq77 thank you for the feedback, but we need more info to investigate the issue. Which milvus version are you running, and how did you deploy milvus? According to the error msg, i guess the etcd or pulsar is not working well at that time. Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs so that we could address the issue?
> 
> /assign @llllyq77 /unassign

基于milvus/configs/milvus.yaml适配厂内中间件做的部署，为什么导不出日志
