### ISSUE TITLE
[Bug]: connect timeout when acces the milvus on remote server

### ISSUE THREAD

**Issue by luojunhui1** [milvus-io/milvus#25263]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.11
- Deployment mode(standalone or cluster): standalone 
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.2.13
- OS(Ubuntu or CentOS): CentOS
```

### Current Behavior

I start the milvus on the server with commend 
``` shell
docker compose up -d
```
and the output is
``` shell
 ✔ Network milvus               Created                                                                                                                                                                                   0.1s 
 ✔ Container milvus-minio       Started                                                                                                                                                                                   0.7s 
 ✔ Container milvus-etcd        Started                                                                                                                                                                                   0.7s 
 ✔ Container milvus-standalone  Started         
```
then i tried to use pymilvus to connect milvus on the server like
``` python 
from pymilvus import connections
connections.connect("default", host = "localhost", port = "19530")
```
it works well, and the `hello milvus` https://milvus.io/docs/example_code.md also works.
but when i tried to use milvus-cli to connect milvus like:
```
milvus_cli > connect -h localhost -p 19530 -a default
```
the output is:
```shell
<MilvusException: (code=2, message=Fail connecting to server on localhost:19530. Timeout)>
```
moreover, when i try to connect the milvus on the remote server, i cann't connect to it successfully anyhow, the output is always Timeout

### Expected Behavior

i wannt to be able to acces the remote milvus service on the server, locally, for that i can debug the remote project.

**Comment by yanliang567** [comment]
/assign @locustbaby 
do we need to upgrade the cli for milvus connection?

/unassign

**Comment by xiaofan-luan** [comment]
try to expose 19530

    # expose 19530 port so we can directly access milvus inside build container
    # ports:
    #  - "19530:19530"

@LoveEachDay 
any reason we don't want to implement it by default?

**Comment by luojunhui1** [comment]
i have tried to install milvus_cli through pip, it worked well, but the milvus_cli installed through docker still cann't connect to the milvus, it seems that the most possible reason is the version problem.
![image](https://github.com/milvus-io/milvus/assets/41661108/497e8e21-66a4-432c-8b2f-2275d4ef0143)

**Comment by luojunhui1** [comment]
still i cannot connect to the milvus on the remote server through anyway, the docker config file is [milvus 2.2.11](https://github.com/milvus-io/milvus/releases/download/v2.2.11/milvus-standalone-docker-compose.yml)
the docker container running status is 
![image](https://github.com/milvus-io/milvus/assets/41661108/958c1c22-030f-40df-a82a-026e59b739e7)

the output on the local machine is 
![image](https://github.com/milvus-io/milvus/assets/41661108/d714e4c4-b9f7-43a6-afa3-d781abecb409)

what else can i do for this

**Comment by luojunhui1** [comment]
> try to expose 19530
> 
>     # expose 19530 port so we can directly access milvus inside build container
>     # ports:
>     #  - "19530:19530"
> 
> @LoveEachDay 
> any reason we don't want to implement it by default?

where should i add or expose this configuration？i found this comment in your repo docker-compose.yml，but there are two comments looks like this, in the builder and gpubuilder,respectively , and when i tried to add the builder part in my docker-compose.yml, i got a failure when tring to run the container throungh the command `docker compose up -d`

**Comment by xiaofan-luan** [comment]
remote the comments should work

**Comment by luojunhui1** [comment]
> remote the comments should work

sorry, i do not get it, can you explain more specially, thank you for your time

**Comment by xiaofan-luan** [comment]
remove the comments and restart the docker should work.
You have to expose the port outside the docker.

**Comment by krisskad** [comment]
How to expose port and how to connect to remote connection?

connections.connect("default", host="172.174.70.230", port="19530")

Im also getting Timeout issue

**Comment by luojunhui1** [comment]
> 

For me, the most probably reasone for milvus_cli cann't connect to the milvus server is the milvus_cli version is not correct, the 
 version of milvus_cli installed by `pip` is `0.3.3` but the version for milvus_cli installed by `docker` is `0.3.0`. Last night, i found the real  resone for the `Timeout` issue, even though i changed the `FireWall Configuration` of my server, 
![remote server port validation](https://github.com/milvus-io/milvus/assets/41661108/5287a96c-787b-4add-87c2-1116fb69d6c7)

but still i cann't connect  to the `{IP of my server}:port`, then i tried to change the `FireWall Rule` on the cloud-server platform(https://cloud.tencent.com/), once add the port(19530) to the  rule-list, i can connect to the remote milvus server correctly.
![image](https://github.com/milvus-io/milvus/assets/41661108/407ff2d5-b229-440b-b888-135b85cf6ff3)

**Comment by xiaofan-luan** [comment]
telnet host port to see if it's connectable.
let us know if it's connect otherwise you have to figure out why your network is not connectable.

if telnet is working please share detailed milvus log, otherwise you have to take care about how to expose port in docker compose.  as I just siad, docker compose up -d relies on a dockercompose.yml.
you can share the current file you used

**Comment by rcland12** [comment]
@luojunhui1 what helped me was adding a timeout to the connection command. My api was trying to connect to Milvus before the docker containers were fully healthy.
`connections.connect(alias="default", uri=milvus_uri, timeout=60)`

**Comment by lkyuier** [comment]
I encounter same issues , does there anyone know how to resolve it ??

**Comment by yanliang567** [comment]
please file a new issue and attach your milvus logs, connection timeout could be caused by different reasons.

> I encounter same issues , does there anyone know how to resolve it ??
