### ISSUE TITLE
[Bug]: indexnode crash with create HNSW  index

### ISSUE THREAD

**Issue by bingbb47** [milvus-io/milvus#25264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.11& v2.2.10&v 2.2.9
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

This problem may not always recur, but once triggered, it cannot be restored. 

### Milvus Log

[milvus-indexnode.txt](https://github.com/milvus-io/milvus/files/11915922/milvus-indexnode.txt)

**Comment by bingbb47** [comment]
Is there any way to cancel this build task and restore the cluster to a healthy state

**Comment by bingbb47** [comment]
ok i got the reason, the indexnode node is 8c ,create index with param {"M": 64,"efConstruction":512}. Problems caused by insufficient threads. Can I limit it through configuration？

**Comment by xiaofan-luan** [comment]
/assign @xige-16 
seems to be a aws sdk issue

**Comment by xiaofan-luan** [comment]
> ok i got the reason, the indexnode node is 8c ,create index with param {"M": 64,"efConstruction":512}. Problems caused by insufficient threads. Can I limit it through configuration？

seems like a aws cpp sdk issue

[2023/06/30 18:35:48.623 +08:00] [INFO] [indexnode/task.go:346] [\"Successfully build index\"] [buildID=442523530484324902] [Collection=442523530484124853] [SegmentID=442523530484324867]
Fatal error condition occurred in /go/src/github.com/milvus-io/milvus/cmake_build/3rdparty_download/aws-sdk-subbuild/src/aws_sdk_s3_ep/crt/aws-crt-cpp/crt/aws-c-io/source/event_loop.c:72: aws_thread_launch(\u0026cleanup_thread, s_event_loop_destroy_async_thread_fn, el_group, \u0026thread_options) == AWS_OP_SUCCESS
Exiting Application

**Comment by bingbb47** [comment]
> > ok i got the reason, the indexnode node is 8c ,create index with param {"M": 64,"efConstruction":512}. Problems caused by insufficient threads. Can I limit it through configuration？
> 
> seems like a aws cpp sdk issue
> 
> [2023/06/30 18:35:48.623 +08:00] [INFO] [indexnode/task.go:346] ["Successfully build index"] [buildID=442523530484324902] [Collection=442523530484124853] [SegmentID=442523530484324867] Fatal error condition occurred in /go/src/github.com/milvus-io/milvus/cmake_build/3rdparty_download/aws-sdk-subbuild/src/aws_sdk_s3_ep/crt/aws-crt-cpp/crt/aws-c-io/source/event_loop.c:72: aws_thread_launch(\u0026cleanup_thread, s_event_loop_destroy_async_thread_fn, el_group, \u0026thread_options) == AWS_OP_SUCCESS Exiting Application

its interesting,Adding the CPU configuration of indexnode did indeed eliminate this issue. I tried searching for this AWS issue, but nothing valuable.

**Comment by yanliang567** [comment]
@bingbb47 how much memory did you configure for the index node pod?

**Comment by xiaofan-luan** [comment]
> @bingbb47 how much memory did you configure for the index node pod?

My guess is that docker has some limitations of thread creation and thus cause thread creation failure.
With more cpus maybe the limitation relaxed

**Comment by bingbb47** [comment]
> > @bingbb47 how much memory did you configure for the index node pod?
> 
> My guess is that docker has some limitations of thread creation and thus cause thread creation failure. With more cpus maybe the limitation relaxed

i think so, there are 2 indexnode with 16c32G, and the utilization both not high; 0.o

![image](https://github.com/milvus-io/milvus/assets/111261344/fd988a55-844e-4c20-a3bd-f7ae27e6a775)
Should I lower this value？

**Comment by xiaofan-luan** [comment]
good catch, I guess that worth trying.
And for index node I would recommend to have at lease 4c16G

**Comment by bingbb47** [comment]
> good catch, I guess that worth trying. And for index node I would recommend to have at lease 4c16G

it is worked, but incomplete worked.

i have tired to change the threadCoreCoefficient 10->8, when start a HNSW index job with params {"M": 64,"efConstruction":512}, the indexnode do not crash;

Immediately after,  i start a another index job, the indexnode crash;

and then, i change the threadCoreCoefficient 8->6 the indexnode worked.

**Comment by xiaofan-luan** [comment]
we should reduce the aws sdk version to 1.8.186 for now and release 2.2.12 later

**Comment by xige-16** [comment]
Please use milvus 2.2.12 to avoid encountering this issue.
