### ISSUE TITLE
[Bug]:  <MilvusException: (code=1, message=proxy not healthy)>

### ISSUE THREAD

**Issue by llllyq77** [milvus-io/milvus#25273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.13
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

<MilvusException: (code=1, message=proxy not healthy)>

**Comment by llllyq77** [comment]
![image](https://github.com/milvus-io/milvus/assets/131153740/7c9c97a4-73e5-4cf8-83f8-eb5b53914c1e)

**Comment by yanliang567** [comment]
I don't think your milvus is running in healthy statue after deployment. a dup to #25274.
