### ISSUE TITLE
[Bug]: SegmentIDAllocator failRemainRequest unexpecror

### ISSUE THREAD

**Issue by llllyq77** [milvus-io/milvus#25274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/131153740/a778de4a-33a4-4e03-b861-e5453e00bec2)

**Comment by xiaofan-luan** [comment]
did you check your etcd?
seems that the etcd is slow

**Comment by yanliang567** [comment]
@llllyq77 thank you for the feedback. please help to double check whether the milvus service and dependent services are running well. For the etcd and pulsar bookkeeper, it need ssd volumes. 
Also could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @llllyq77

**Comment by llllyq77** [comment]
> 
![image](https://github.com/milvus-io/milvus/assets/131153740/f53731cb-d6a4-4abb-9e9b-2f0f21150cd9)

基于milvus/configs/milvus.yaml适配厂内中间件做的部署，请问为什么导不出日志

**Comment by yanliang567** [comment]
/assign @LoveEachDay 
could you please help to export the log as description above?

**Comment by llllyq77** [comment]
![image](https://github.com/milvus-io/milvus/assets/131153740/6f73035e-9810-4974-8c67-300f992fc06f)
里面就是几个目录结构，但是每个目录下都没有文件

**Comment by hao-cyber** [comment]
一样的问题导不出日志，请问有解决方案吗

**Comment by yanliang567** [comment]
> ![image](https://user-images.githubusercontent.com/131153740/250443597-6f73035e-9810-4974-8c67-300f992fc06f.png) 里面就是几个目录结构，但是每个目录下都没有文件

please upload the milvis-log.tar.gz
