### ISSUE TITLE
[Bug]: MilvusException: (code=1, message=syncTimestamp Fail

### ISSUE THREAD

**Issue by llllyq77** [milvus-io/milvus#25275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/131153740/4483493d-0c66-4a60-82d6-75e7535276a9)

**Comment by yanliang567** [comment]
lets track the issue in #25274
