### ISSUE TITLE
[Bug]: Milvus container crashed unexpectedly while writing data

### ISSUE THREAD

**Issue by darkerin** [milvus-io/milvus#25296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.8
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):  default  
- SDK version(e.g. pymilvus v2.0.0rc2): v2.2.8
- OS(Ubuntu or CentOS):  Ubuntu20.04
- CPU/Memory:  4C
- GPU:  8G
- Others:
```

### Current Behavior

Milvus container crashed unexpectedly while creating collection and save data,  approximately 500K of text data, around 100,000 words.

Additionally, I would like to ask if it is normal for my Milvus container to maintain high CPU usage even when there is no access after it has been started?
<img width="678" alt="image" src="https://github.com/milvus-io/milvus/assets/136887833/624bb52a-34f8-4ff0-be04-0496097c684b">

### Milvus Log

When I use "docker logs" to view the logs of exited container, I can only see rapidly scrolling logs: 

2023/07/03 10:40:51.967 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=84.449µs]
[2023/07/03 10:40:51.967 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=38.132µs]
[2023/07/03 10:40:51.967 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=34.786µs]
[2023/07/03 10:40:51.969 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=76.886µs]
[2023/07/03 10:40:51.970 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=41.087µs]
[2023/07/03 10:40:51.972 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=45.235µs]
[2023/07/03 10:40:51.972 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=213.521µs]
xxxxxxxxxxxxxxxxxx

Additionally, during normal operation, the logs are also rapidly outputting, which leads to the rapid expansion of the json.log file in the Docker container. Is this normal?

**Comment by yanliang567** [comment]
@darkerin thank you for the issue. 
1. the CPU usage issue is a known issue, that we are trying to fix it in next release
2. we need completed milvus logs to address the crash issue. Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?


/assign @darkerin

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version: v2.2.8
> - Deployment mode(standalone or cluster): standalone
> - MQ type(rocksmq, pulsar or kafka):  default  
> - SDK version(e.g. pymilvus v2.0.0rc2): v2.2.8
> - OS(Ubuntu or CentOS):  Ubuntu20.04
> - CPU/Memory:  4C
> - GPU:  8G
> - Others:
> ```
> 
> ### Current Behavior
> Milvus container crashed unexpectedly while creating collection and save data, approximately 500K of text data, around 100,000 words.
> 
> Additionally, I would like to ask if it is normal for my Milvus container to maintain high CPU usage even when there is no access after it has been started? <img alt="image" width="678" src="https://user-images.githubusercontent.com/136887833/250534052-624bb52a-34f8-4ff0-be04-0496097c684b.png">
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> When I use "docker logs" to view the logs of exited container, I can only see rapidly scrolling logs:
> 
> 2023/07/03 10:40:51.967 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=84.449µs] [2023/07/03 10:40:51.967 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=38.132µs] [2023/07/03 10:40:51.967 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=34.786µs] [2023/07/03 10:40:51.969 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=76.886µs] [2023/07/03 10:40:51.970 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=41.087µs] [2023/07/03 10:40:51.972 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=45.235µs] [2023/07/03 10:40:51.972 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=213.521µs] xxxxxxxxxxxxxxxxxx
> 
> Additionally, during normal operation, the logs are also rapidly outputting, which leads to the rapid expansion of the json.log file in the Docker container. Is this normal?
> 
> ### Anything else?
> _No response_

How many collections do you have? The high memory usage might be due to index creation or too many collections

**Comment by shenyunlong** [comment]
the same problem

**Comment by darkerin** [comment]
> > ### Is there an existing issue for this?
> > 
> > * [x]   I have searched the existing issues
> > 
> > ### Environment
> > ```
> > - Milvus version: v2.2.8
> > - Deployment mode(standalone or cluster): standalone
> > - MQ type(rocksmq, pulsar or kafka):  default  
> > - SDK version(e.g. pymilvus v2.0.0rc2): v2.2.8
> > - OS(Ubuntu or CentOS):  Ubuntu20.04
> > - CPU/Memory:  4C
> > - GPU:  8G
> > - Others:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Current Behavior
> > Milvus container crashed unexpectedly while creating collection and save data, approximately 500K of text data, around 100,000 words.
> > Additionally, I would like to ask if it is normal for my Milvus container to maintain high CPU usage even when there is no access after it has been started? <img alt="image" width="678" src="https://user-images.githubusercontent.com/136887833/250534052-624bb52a-34f8-4ff0-be04-0496097c684b.png">
> > ### Expected Behavior
> > _No response_
> > ### Steps To Reproduce
> > _No response_
> > ### Milvus Log
> > When I use "docker logs" to view the logs of exited container, I can only see rapidly scrolling logs:
> > 2023/07/03 10:40:51.967 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=84.449µs] [2023/07/03 10:40:51.967 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=38.132µs] [2023/07/03 10:40:51.967 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=34.786µs] [2023/07/03 10:40:51.969 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=76.886µs] [2023/07/03 10:40:51.970 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=41.087µs] [2023/07/03 10:40:51.972 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=45.235µs] [2023/07/03 10:40:51.972 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=213.521µs] xxxxxxxxxxxxxxxxxx
> > Additionally, during normal operation, the logs are also rapidly outputting, which leads to the rapid expansion of the json.log file in the Docker container. Is this normal?
> > ### Anything else?
> > _No response_
> 
> How many collections do you have? The high memory usage might be due to index creation or too many collections



> > ### Is there an existing issue for this?
> > 
> > * [x]   I have searched the existing issues
> > 
> > ### Environment
> > ```
> > - Milvus version: v2.2.8
> > - Deployment mode(standalone or cluster): standalone
> > - MQ type(rocksmq, pulsar or kafka):  default  
> > - SDK version(e.g. pymilvus v2.0.0rc2): v2.2.8
> > - OS(Ubuntu or CentOS):  Ubuntu20.04
> > - CPU/Memory:  4C
> > - GPU:  8G
> > - Others:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Current Behavior
> > Milvus container crashed unexpectedly while creating collection and save data, approximately 500K of text data, around 100,000 words.
> > Additionally, I would like to ask if it is normal for my Milvus container to maintain high CPU usage even when there is no access after it has been started? <img alt="image" width="678" src="https://user-images.githubusercontent.com/136887833/250534052-624bb52a-34f8-4ff0-be04-0496097c684b.png">
> > ### Expected Behavior
> > _No response_
> > ### Steps To Reproduce
> > _No response_
> > ### Milvus Log
> > When I use "docker logs" to view the logs of exited container, I can only see rapidly scrolling logs:
> > 2023/07/03 10:40:51.967 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=84.449µs] [2023/07/03 10:40:51.967 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=38.132µs] [2023/07/03 10:40:51.967 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=34.786µs] [2023/07/03 10:40:51.969 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=76.886µs] [2023/07/03 10:40:51.970 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=41.087µs] [2023/07/03 10:40:51.972 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=45.235µs] [2023/07/03 10:40:51.972 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=213.521µs] xxxxxxxxxxxxxxxxxx
> > Additionally, during normal operation, the logs are also rapidly outputting, which leads to the rapid expansion of the json.log file in the Docker container. Is this normal?
> > ### Anything else?
> > _No response_
> 
> How many collections do you have? The high memory usage might be due to index creation or too many collections

Thank you for your reminder! 

I have hundreds of collections. These collections have a requirement for business isolation, and I don't want to load them all into memory at once, so I split them into multiple collections.  But I think if I release the collection after each vector query, it shouldn't continue to occupy memory. Is it because the memory needs to store metadata and indexes of the collections? And how many collections can a machine with 16GB of memory approximately support?

Regarding scenarios with large amounts of data like this, is there a better way to prevent memory overflow?

**Comment by yanliang567** [comment]
> > @darkerin thank you for the issue.
> > 
> > 1. the CPU usage issue is a known issue, that we are trying to fix it in next release
> > 2. we need completed milvus logs to address the crash issue. Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
> > 
> > /assign @darkerin
> 
> Thank` you for your response
> 
> 1. May I ask if this issue exists in all version 2.x? If not, could you recommend a recent stable version that does not have this problem?  Additionally, if the next version resolves this issue, can I simply pull the latest image and still be able to use the data in my "volumes" directory?
> 2. After my container exits, I have already execute  "docker compose down" and then "docker compose down up" command to restart the container. I am wondering if this method will still provide me with valid logs?

1. I think we have some improvement in latest release v2.2.11 in disk usage. 
2. if it reproduced to me after restart, please collect the logs.

**Comment by darkerin** [comment]
> 1. ink we have some improvem

ok, if my data is compatible when I upgrade image from 2.2.8 to 2.2.11?

**Comment by yanliang567** [comment]
> > 1. ink we have some improvem
> 
> ok, if my data is compatible when I upgrade image from 2.2.8 to 2.2.11?

yes

**Comment by darkerin** [comment]
> > > @darkerin thank you for the issue.
> > > 
> > > 1. the CPU usage issue is a known issue, that we are trying to fix it in next release
> > > 2. we need completed milvus logs to address the crash issue. Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
> > > 
> > > /assign @darkerin
> > 
> > 
> > Thank` you for your response
> > 
> > 1. May I ask if this issue exists in all version 2.x? If not, could you recommend a recent stable version that does not have this problem?  Additionally, if the next version resolves this issue, can I simply pull the latest image and still be able to use the data in my "volumes" directory?
> > 2. After my container exits, I have already execute  "docker compose down" and then "docker compose down up" command to restart the container. I am wondering if this method will still provide me with valid logs?
> 
> 1. I think we have some improvement in latest release v2.2.11 in disk usage.
> 2. if it reproduced to me after restart, please collect the logs.

@yanliang567 
Today, there was another container exit again, and causing the machine to crash. We had to restart the server and container in order to quickly restore service, so did not have time to execute log script.

Before the restart, I saw some logs about "rmq produce too slowly", and here are some log fragments:

```
[2023/07/04 05:27:09.835 +00:00] [DEBUG] [proxy/task_insert.go:468] ["Proxy Insert Execute done"] [msgID=442616625139023873] ["collection name"=168844836345] ["send message duration"=16.475253ms] ["execute duration"=148.724564ms]
```

**Comment by darkerin** [comment]
> 



> > > ### Is there an existing issue for this?
> > > 
> > > * [x]    I have searched the existing issues
> > > 
> > > ### Environment
> > > ```
> > > - Milvus version: v2.2.8
> > > - Deployment mode(standalone or cluster): standalone
> > > - MQ type(rocksmq, pulsar or kafka):  default  
> > > - SDK version(e.g. pymilvus v2.0.0rc2): v2.2.8
> > > - OS(Ubuntu or CentOS):  Ubuntu20.04
> > > - CPU/Memory:  4C
> > > - GPU:  8G
> > > - Others:
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ### Current Behavior
> > > Milvus container crashed unexpectedly while creating collection and save data, approximately 500K of text data, around 100,000 words.
> > > Additionally, I would like to ask if it is normal for my Milvus container to maintain high CPU usage even when there is no access after it has been started? <img alt="image" width="678" src="https://user-images.githubusercontent.com/136887833/250534052-624bb52a-34f8-4ff0-be04-0496097c684b.png">
> > > ### Expected Behavior
> > > _No response_
> > > ### Steps To Reproduce
> > > _No response_
> > > ### Milvus Log
> > > When I use "docker logs" to view the logs of exited container, I can only see rapidly scrolling logs:
> > > 2023/07/03 10:40:51.967 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=84.449µs] [2023/07/03 10:40:51.967 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=38.132µs] [2023/07/03 10:40:51.967 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=34.786µs] [2023/07/03 10:40:51.969 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=76.886µs] [2023/07/03 10:40:51.970 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=41.087µs] [2023/07/03 10:40:51.972 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=45.235µs] [2023/07/03 10:40:51.972 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=213.521µs] xxxxxxxxxxxxxxxxxx
> > > Additionally, during normal operation, the logs are also rapidly outputting, which leads to the rapid expansion of the json.log file in the Docker container. Is this normal?
> > > ### Anything else?
> > > _No response_
> > 
> > 
> > How many collections do you have? The high memory usage might be due to index creation or too many collections
> 
> > > ### Is there an existing issue for this?
> > > 
> > > * [x]    I have searched the existing issues
> > > 
> > > ### Environment
> > > ```
> > > - Milvus version: v2.2.8
> > > - Deployment mode(standalone or cluster): standalone
> > > - MQ type(rocksmq, pulsar or kafka):  default  
> > > - SDK version(e.g. pymilvus v2.0.0rc2): v2.2.8
> > > - OS(Ubuntu or CentOS):  Ubuntu20.04
> > > - CPU/Memory:  4C
> > > - GPU:  8G
> > > - Others:
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ### Current Behavior
> > > Milvus container crashed unexpectedly while creating collection and save data, approximately 500K of text data, around 100,000 words.
> > > Additionally, I would like to ask if it is normal for my Milvus container to maintain high CPU usage even when there is no access after it has been started? <img alt="image" width="678" src="https://user-images.githubusercontent.com/136887833/250534052-624bb52a-34f8-4ff0-be04-0496097c684b.png">
> > > ### Expected Behavior
> > > _No response_
> > > ### Steps To Reproduce
> > > _No response_
> > > ### Milvus Log
> > > When I use "docker logs" to view the logs of exited container, I can only see rapidly scrolling logs:
> > > 2023/07/03 10:40:51.967 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=84.449µs] [2023/07/03 10:40:51.967 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=38.132µs] [2023/07/03 10:40:51.967 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=34.786µs] [2023/07/03 10:40:51.969 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=76.886µs] [2023/07/03 10:40:51.970 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=41.087µs] [2023/07/03 10:40:51.972 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=45.235µs] [2023/07/03 10:40:51.972 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=213.521µs] xxxxxxxxxxxxxxxxxx
> > > Additionally, during normal operation, the logs are also rapidly outputting, which leads to the rapid expansion of the json.log file in the Docker container. Is this normal?
> > > ### Anything else?
> > > _No response_
> > 
> > 
> > How many collections do you have? The high memory usage might be due to index creation or too many collections
> 
> Thank you for your reminder!
> 
> I have hundreds of collections. These collections have a requirement for business isolation, and I don't want to load them all into memory at once, so I split them into multiple collections. But I think if I release the collection after each vector query, it shouldn't continue to occupy memory. Is it because the memory needs to store metadata and indexes of the collections? And how many collections can a machine with 16GB of memory approximately support?
> 
> Regarding scenarios with large amounts of data and collections like this, is there a better way to prevent memory overflow?

@xiaofan-luan  @yanliang567 
Hello, whenever I start the container, it consumes approximately 100% of CPU (1 core) and 40% of memory. Is this normal? Is there any way to reduce it?

**Comment by yanliang567** [comment]
I believe it is because there are hundreds of collections, we are trying to improve it in next release.

**Comment by darkerin** [comment]
> > > @darkerin thank you for the issue.
> > > 
> > > 1. the CPU usage issue is a known issue, that we are trying to fix it in next release
> > > 2. we need completed milvus logs to address the crash issue. Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
> > > 
> > > /assign @darkerin
> > 
> > 
> > Thank` you for your response
> > 
> > 1. May I ask if this issue exists in all version 2.x? If not, could you recommend a recent stable version that does not have this problem?  Additionally, if the next version resolves this issue, can I simply pull the latest image and still be able to use the data in my "volumes" directory?
> > 2. After my container exits, I have already execute  "docker compose down" and then "docker compose down up" command to restart the container. I am wondering if this method will still provide me with valid logs?
> 
> 1. I think we have some improvement in latest release v2.2.11 in disk usage.
> 2. if it reproduced to me after restart, please collect the logs.

@xiaofan-luan @yanliang567 
Just experienced a container crash again, after attempting to create a collection and write approximately 2MB of text data.

``` 
[2023/07/04 12:48:24.278 +00:00] [WARN] [server/rocksmq_impl.go:764] ["rocksmq consume too slowly"] [topic=by-dev-rootcoord-dml_4] ["get lock elapse"=3306] ["iterator elapse"=1] ["moveConsumePosTime elapse"=0] ["total consume elapse"=3307]
[2023/07/04 12:48:24.279 +00:00] [WARN] [server/rocksmq_impl.go:764] ["rocksmq consume too slowly"] [topic=by-dev-rootcoord-dml_4] ["get lock elapse"=3303] ["iterator elapse"=1] ["moveConsumePosTime elapse"=0] ["total consume elapse"=3304]
[2023/07/04 12:48:24.280 +00:00] [WARN] [server/rocksmq_impl.go:764] ["rocksmq consume too slowly"] [topic=by-dev-rootcoord-dml_4] ["get lock elapse"=3289] ["iterator elapse"=2] ["moveConsumePosTime elapse"=0] ["total consume elapse"=3291]
[2023/07/04 12:48:24.390 +00:00] [WARN] [server/rocksmq_impl.go:764] ["rocksmq consume too slowly"] [topic=by-dev-rootcoord-dml_4] ["get lock elapse"=3289] ["iterator elapse"=109] ["moveConsumePosTime elapse"=0] ["total consume elapse"=3399]
[2023/07/04 12:48:24.430 +00:00] [WARN] [server/rocksmq_impl.go:628] ["rocksmq produce too slowly"] [topic=by-dev-rootcoord-dml_4] ["get lock elapse"=3423] ["alloc elapse"=0] ["write elapse"=6] ["updatePage elapse"=3] ["produce total elapse"=3432]
[2023/07/04 12:48:24.431 +00:00] [WARN] [server/rocksmq_impl.go:764] ["rocksmq consume too slowly"] [topic=by-dev-rootcoord-dml_4] ["get lock elapse"=3428] ["iterator elapse"=1] ["moveConsumePosTime elapse"=0] ["total consume elapse"=3429]
[2023/07/04 12:48:24.432 +00:00] [WARN] [server/rocksmq_impl.go:764] ["rocksmq consume too slowly"] [topic=by-dev-rootcoord-dml_4] ["get lock elapse"=3421] ["iterator elapse"=1] ["moveConsumePosTime elapse"=0] ["total consume elapse"=3422]
[2023/07/04 12:48:24.434 +00:00] [WARN] [server/rocksmq_impl.go:764] ["rocksmq consume too slowly"] [topic=by-dev-rootcoord-dml_4] ["get lock elapse"=3408] ["iterator elapse"=1] ["moveConsumePosTime elapse"=0] ["total consume elapse"=3409]
[2023/07/04 12:48:24.436 +00:00] [DEBUG] [rmq/rmq_producer.go:47] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=3.438578893s]
[2023/07/04 12:48:24.446 +00:00] [WARN] [server/rocksmq_impl.go:764] ["rocksmq consume too slowly"] [topic=by-dev-rootcoord-dml_4] ["get lock elapse"=3409] ["iterator elapse"=12] ["moveConsumePosTime elapse"=0] ["total consume elapse"=3421]
[2023/07/04 12:48:24.447 +00:00] [WARN] [server/rocksmq_impl.go:764] ["rocksmq consume too slowly"] [topic=by-dev-rootcoord-dml_4] ["get lock elapse"=3404] ["iterator elapse"=0] ["moveConsumePosTime elapse"=0] ["total consume elapse"=3404]
[2023/07/04 12:48:24.448 +00:00] [WARN] [server/rocksmq_impl.go:764] ["rocksmq consume too slowly"] [topic=by-dev-rootcoord-dml_4] ["get lock elapse"=3404] ["iterator elapse"=1] ["moveConsumePosTime elapse"=0] ["total consume elapse"=3405]
[2023/07/04 12:48:24.452 +00:00] [WARN] [server/rocksmq_impl.go:764] ["rocksmq consume too slowly"] [topic=by-dev-rootcoord-dml_4] ["get lock elapse"=3386] ["iterator elapse"=3] ["moveConsumePosTime elapse"=0] ["total consume elapse"=3389]
[2023/07/04 12:48:24.456 +00:00] [WARN] [server/rocksmq_impl.go:764] ["rocksmq consume too slowly"] [topic=by-dev-rootcoord-dml_4] ["get lock elapse"=3388] ["iterator elapse"=3] ["moveConsumePosTime elapse"=0] ["total consume elapse"=3391]
```

**Comment by darkerin** [comment]
> > > 1. ink we have some improvem
> > 
> > 
> > ok, if my data is compatible when I upgrade image from 2.2.8 to 2.2.11?
> 
> yes

Encountering some startup issues: https://github.com/milvus-io/milvus/issues/25321
