### ISSUE TITLE
[Enhancement]: refactor etcd watch usages

### ISSUE THREAD

**Issue by yiwangdr** [milvus-io/milvus#25309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Currently, datacoord and datanode uses etcd watch() during channel creation. It's essentially a way to decouple message read & write, so that channel creation is processed in a semi-async way. This is due to historical reasons which no longer exist. Thus we'd like to refactor this part to use RPC instead of Watch().

Another upside of this refactory is that milvus will be able to use other scalable KV services as our metadata storage. The metadata size will no longer be limited by etcd's horizontal scalability issue.

**Comment by XuanYang-cn** [comment]
keep it open

**Comment by xiaofan-luan** [comment]
leave it?
