### ISSUE TITLE
[Bug]: Recommender System docs (Quick deploy) - expired link 

### ISSUE THREAD

**Issue by Gdahuks** [milvus-io/milvus#25314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus (docs) version: v2.2x
Documentation as of 4.07.2023
```

### Current Behavior

The link on the documentation page [Recommender System](https://milvus.io/docs/recommendation_system.md) for [Quick deploy ](https://github.com/milvus-io/bootcamp/blob/master/solutions/nlp/recommender_system/quick_deploy) leads to a non-existent file.
![image](https://github.com/milvus-io/milvus/assets/71979732/7f83b0cc-9f66-4c10-a8cb-86becd61ba7b)
![image](https://github.com/milvus-io/milvus/assets/71979732/251d216c-d7c2-43cf-8e11-bdfb0f2ef2bd)

**Comment by Gdahuks** [comment]
I created a PR: https://github.com/milvus-io/milvus-docs/pull/2224

**Comment by yanliang567** [comment]
@Gdahuks thank you for the pr.
/assign @Gdahuks 
/unassign
