### ISSUE TITLE
[Bug]: MultiThreadedRendezvous of RPC that terminated 

### ISSUE THREAD

**Issue by cuisws** [milvus-io/milvus#25312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.10
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.2.12
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I insert or query data

### Expected Behavior

success

### Milvus Log

RPC error: [query], <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Stream removed"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:8.140.158.98:19530 {grpc_message:"Stream removed", grpc_status:2, created_time:"2023-07-03T09:06:59.163803908+00:00"}"
>)>, <Time:{'RPC start': '2023-07-03 17:06:44.659022', 'RPC error': '2023-07-03 17:06:59.164271'}>

**Comment by yanliang567** [comment]
@cuisws Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @cuisws 
/unassign

**Comment by fuleige** [comment]
Has this problem been solved? I've also encountered it

**Comment by xiaofan-luan** [comment]
> Has this problem been solved? I've also encountered it

please offer all the logs.
this is simply a timeout error message. maybe your node crashed for some reason. We can not judge it by only the error message

**Comment by fuleige** [comment]
> > Has this problem been solved? I've also encountered it
> 
> please offer all the logs. this is simply a timeout error message. maybe your node crashed for some reason. We can not judge it by only the error message

Thank you for your reply.
Actually, I am using the outdated version 1.1.1 (milvus), and clinet is pymilvus==1.1.2. In fact, this type of error does not have any error logs and is directly output in the standard error

###  1. problem reproduction
My example code is as follows
```python
# 1. create a new client
client = Milvus(host=ip, port=port)

# 2. pytorch style extracts vectors (using cuda)
for data in dataloader(image_datasets):
    vecs = model(data).tolist()
    # 2.1 search vector
    client.search(vecs)
```
There is no problem when the data volume is 100000, but there will be problems when it reaches millions, with an error reported at some stage in between

### 2. It seems to be a solution
I also suspected that the problem was caused by the client's grpc framework, so I made some changes to the code and it ran normally
```python
# pool default value is "SingletonThread"
Milvus(host=ip, port=port, pool="QueuePool")
```

**Comment by xiaofan-luan** [comment]
> > > Has this problem been solved? I've also encountered it
> > 
> > 
> > please offer all the logs. this is simply a timeout error message. maybe your node crashed for some reason. We can not judge it by only the error message
> 
> Thank you for your reply. Actually, I am using the outdated version 1.1.1 (milvus), and clinet is pymilvus==1.1.2. In fact, this type of error does not have any error logs and is directly output in the standard error
> 
> ### 1. problem reproduction
> My example code is as follows
> 
> ```python
> # 1. create a new client
> client = Milvus(host=ip, port=port)
> 
> # 2. pytorch style extracts vectors (using cuda)
> for data in dataloader(image_datasets):
>     vecs = model(data).tolist()
>     # 2.1 search vector
>     client.search(vecs)
> ```
> 
> There is no problem when the data volume is 100000, but there will be problems when it reaches millions, with an error reported at some stage in between
> 
> ### 2. It seems to be a solution
> I also suspected that the problem was caused by the client's grpc framework, so I made some changes to the code and it ran normally
> 
> ```python
> # pool default value is "SingletonThread"
> Milvus(host=ip, port=port, pool="QueuePool")
> ```

Milvus 1.x is not mantianed for two years.
right now the latest version is 2.4.x. 
Sorry for the inconvenience
