### ISSUE TITLE
Run Milvus docker image report illegal instruction

### ISSUE THREAD

**Issue by xulu666666** [milvus-io/milvus#2532]
**Describe the bug**
./start_server.sh: line 3:     7 Illegal instruction     (core dumped) ../bin/milvus_server -c ../conf/server_config.yaml

**Environment details**
- Hardware/Softward conditions 
       CPU：Linux version 3.10.0-514.el7.x86_64 
                 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) 
                 (GCC) ) #1 
- Method of installation (Docker 19.03.11)
- Milvus version (v0.9.0 和 v0.9.1)
- Milvus configuration (server_config.yaml版本0.4，未更改任何配置)

**Screenshots**
[root@localhost milvus]# docker ps -a
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS                       PORTS               NAMES
e483c27d01a2        milvusdb/milvus:0.9.1-cpu-d052920-e04ed5   "/var/lib/milvus/doc…"   5 minutes ago       Exited (132) 5 minutes ago                       milvus_cpu_0.9.1
[root@localhost milvus]# docker logs e483c27d01a2
./start_server.sh: line 3:     7 Illegal instruction     (core dumped) ../bin/milvus_server -c ../conf/server_config.yaml

**Additional context**

**Comment by xulu666666** [comment]
服务器支持sse4.2

**Comment by scsven** [comment]
@xulu666666 Could you provide the info level log file in path `/var/lib/milvus/logs/` ?

**Comment by xulu666666** [comment]
> @xulu666666 Could you provide the info level log file in path `/var/lib/milvus/logs/` ?

The docker container cannot run, so i cannot go into it to see that, and the local  path "/home/xulu/logs/" is empty

**Comment by scsven** [comment]
@xulu666666 Please run `cat /proc/cpuinfo` and paste the output here.

**Comment by xulu666666** [comment]
run cat /proc/cpuinfo(other processors are same):
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 44
model name	: Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
stepping	: 2
microcode	: 0x10
cpu MHz		: 1600.000
cache size	: 12288 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 popcnt aes lahf_lm ida arat epb dtherm tpr_shadow vnmi flexpriority ept vpid
bogomips	: 4799.96
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

**Comment by cydrain** [comment]
Please download
[avx_test.zip](https://github.com/milvus-io/milvus/files/4791311/avx_test.zip)

This is a small testing package to check whether your machine can run SSE4_2 instruction set.
Unzip this package and build then run the executable,
it's expected to see output like this:
```
SSE
16
PASS!
```

**Comment by xulu666666** [comment]
@cydrain i got this: 
![image](https://user-images.githubusercontent.com/8776507/84880514-2ee19800-b0bf-11ea-8584-d54b40b4c3ad.png)

**Comment by cydrain** [comment]
please try this again
[avx_test1.tar.gz](https://github.com/milvus-io/milvus/files/4791659/avx_test1.tar.gz)

**Comment by xulu666666** [comment]
@cydrain i tried the second and it was the same as before

**Comment by cydrain** [comment]
Milvus use some asm code (the code your machine reports build error) to get the CPU flags to decide to use AVX or SSE.
I think your machine is too old to support this asm command.
Milvus supports CPUs newer than Intel Sandy Bridge.

**Comment by scsven** [comment]
@xulu666666 Can you try to upgrade g++ compiler to 4.9 or higher?

**Comment by xulu666666** [comment]
@scsven i update gcc to 7.3.1, it dosen't work

**Comment by xulu666666** [comment]
@cydrain i fixed some problems , the avx_test1.tar.gz can run and i got this:
SSE
16
PASS!

**Comment by scsven** [comment]
@xulu666666 So upgrade g++ compiler makes it work or avx_test1.tar.gz already work with g++ 4.8.5 ?

**Comment by xulu666666** [comment]
@scsven avx_test1.tar.gz already work with g++ 4.8.5

**Comment by cydrain** [comment]
@xulu666666  we made a fix, can you help to have a try ?
[avx_test2.tar.gz](https://github.com/milvus-io/milvus/files/4796812/avx_test2.tar.gz)

**Comment by xulu666666** [comment]
@cydrain i tried avx_test2.tar.gz as below:
![image](https://user-images.githubusercontent.com/8776507/84990025-1f258a80-b177-11ea-82d8-9c56eec0127e.png)

**Comment by ofTheo** [comment]
@xulu666666 what the problems you fixed that got it to pass? 
Would be really helpful as we are using an older docker image and can't build from source. 

> @cydrain i fixed some problems , the avx_test1.tar.gz can run and i got this:
> SSE
> 16
> PASS!

**Comment by scsven** [comment]
@ofTheo On older CPU microarchitectures than `Sandy Bridge`, some assembly instructions used to get `cpuid` will makes Milvus core dumped(7 Illegal instruction). We found a better solution and update it here #2598
