### ISSUE TITLE
[Bug]: sudo docker-compose up -d doesn't work

### ISSUE THREAD

**Issue by mranjank** [milvus-io/milvus#25322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.11
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    none
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: Ec2 8/16
- GPU: none
- Others:
```

### Current Behavior

followed this documentation https://milvus.io/docs/install_standalone-docker.md
I have setup docker
$ docker-compose version
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
after wget https://github.com/milvus-io/milvus/releases/download/v2.2.11/milvus-standalone-docker-compose.yml -O docker-compose.yml
when I run sudo docker-compose up -d
it says 

sudo: docker-compose: command not found

I have also tried docker compose

### Steps To Reproduce

```markdown
follow the documentation at https://milvus.io/docs/install_standalone-docker.md
```

**Comment by yangshuai0711** [comment]
> 

I don't think this is a bug. Docker Compose needs to be installed separately, it is not installed with Docker by default.

**Comment by mranjank** [comment]
its installed separately, I have pasted the version output

**Comment by yangshuai0711** [comment]
> its installed separately, I have pasted the version output

Can you confirm whether docker-compose is in the PATH of the root user?

**Comment by yanliang567** [comment]
/assign @locustbaby 
any suggestions for this?

/unassign

**Comment by mranjank** [comment]
its an ec2 instance with ec2-user
After I login I do sudo su - and did everything in root only
to hide the root/ip I only pasted after the $ prompt

**Comment by mranjank** [comment]
I might be doing something wrong in the docker-compose install
if someone can post a link that explains step by step milvus installation along with docker-compose on RHEL or Ubuntu that would be really helpful

**Comment by locustbaby** [comment]
```
apt -y install docker-compose
docker-compose version
wget https://github.com/milvus-io/milvus/releases/download/v2.2.11/milvus-standalone-docker-compose.yml -O docker-compose.yml
docker-compose up -d
docker-compose -h
docker-compose stop
```
Run on a Ubuntu EC2, works well

**Comment by mranjank** [comment]
Thanks @locustbaby , Last night I did setup an Ubuntu EC2 and it worked like a charm. For some reason in Amazon Linux or RHEL it's a bit tricky.
