### ISSUE TITLE
[Bug]: it’s a bug? only one log file is created when run milvus with mixture mode

### ISSUE THREAD

**Issue by yangshuai0711** [milvus-io/milvus#25323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: ~ 2.2.11
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): attu
- OS(Ubuntu or CentOS):  centos7.6
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I run Milvus with the mixture mode, only one log file is created in the log directory, and its name is always uncertain. Sometimes it is named rootcoord-n.log, and sometimes it is named indexcoord-n.log.
Is there a configuration option to separate them into their own files?

**command**: milvus run mixture -rootcoord -datacoord -querycoord -indexcoord
cd  /var/milvus/logs/ && ll

![image](https://github.com/milvus-io/milvus/assets/4221876/1a15ee00-74be-4c6f-ab2a-c4593ae15615)

### Expected Behavior

each node has its own log file.

### Steps To Reproduce

```markdown
1. command: milvus run mixture -rootcoord -datacoord -querycoord -indexcoord
2. ls /var/milvus/logs/
```

**Comment by yanliang567** [comment]
/assign @LoveEachDay 
could you please help on this issue?

/unassign
