### ISSUE TITLE
[Bug]: The search in queue latency of different users at the querynode is unfair when search with same nq

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#25342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230704-4a87b9f6
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.4.0.dev81
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. deploy milvus cluster
```
spec:
  components:
    dataNode:
      replicas: 1
      resources:
        limits:
          cpu: "1"
          memory: 16Gi
        requests:
          cpu: "1"
          memory: 4Gi
    indexNode:
      replicas: 1
      resources:
        limits:
          cpu: "2"
          memory: 16Gi
        requests:
          cpu: "2"
          memory: 4Gi
    queryNode:
      replicas: **2**
      resources:
        limits:
          cpu: "4"
          memory: 16Gi
        requests:
          cpu: "2"
          memory: 8Gi
  config:
    common:
      security:
        authorizationEnabled: true
    log:
      level: debug
    queryNode:
      scheduler:
        scheduleReadPolicy:
          name: user-task-polling
```
2. test: 10 users run the following test stpes in parallel (part users failed)
- create collection with shards 2
- create hnsw index
- insert 128d-5m entities and flush
- create same index again
- load collection and concurrent 50 users search with nq=100, top_k=100

3. From grafana metrics knows that:
- in querynode-2, the avg search queue latency are not roughly equal for all users, but basically form 2 groups of trends
![d8611ae4-0be1-490c-9340-738cc4f7e35e](https://github.com/milvus-io/milvus/assets/27288593/0fa78c0b-71c2-4667-9e49-6a997ef662e7)

in querynode-5, the avg search queue latency of all users are also not equal, but there is no grouping
![d7f2f549-be9e-4602-a492-ca7489047067](https://github.com/milvus-io/milvus/assets/27288593/b4200c23-3b4b-4627-a8dc-c04a8e198ad6)

- in querynode-5, the p99 queue latency has some larger peaks latency value
![Uploading a171fcce-d654-4f1c-b0ef-bbb5309450f0.jpeg…]()

### Expected Behavior

- avg search queue latency is about the same for all users
- p99 search queue latency trend is smoothing

### Steps To Reproduce

```markdown
- 4am argo name: `fouramf-concurrent-rbac-5m2`
- 4am qa-milvus ns server pods:

fouramf-concurrent-rbac-5m2-etcd-0                                1/1     Running             0                16h     10.104.23.184   4am-node27   <none>           <none>
fouramf-concurrent-rbac-5m2-etcd-1                                1/1     Running             0                16h     10.104.16.9     4am-node21   <none>           <none>
fouramf-concurrent-rbac-5m2-etcd-2                                1/1     Running             0                16h     10.104.17.60    4am-node23   <none>           <none>
fouramf-concurrent-rbac-5m2-milvus-datacoord-946f9b8b4-gfxck      1/1     Running             0                16h     10.104.23.207   4am-node27   <none>           <none>
fouramf-concurrent-rbac-5m2-milvus-datanode-59b49d56fb-4xvwb      1/1     Running             0                16h     10.104.23.204   4am-node27   <none>           <none>
fouramf-concurrent-rbac-5m2-milvus-indexcoord-8d5bcb5b-pk4nb      1/1     Running             0                16h     10.104.17.61    4am-node23   <none>           <none>
fouramf-concurrent-rbac-5m2-milvus-indexnode-69574d8c9d-gbbzr     1/1     Running             0                16h     10.104.16.22    4am-node21   <none>           <none>
fouramf-concurrent-rbac-5m2-milvus-proxy-5f5cddcb7-n8w5v          1/1     Running             0                16h     10.104.17.62    4am-node23   <none>           <none>
fouramf-concurrent-rbac-5m2-milvus-querycoord-64589cb69b-5hbgg    1/1     Running             0                16h     10.104.22.243   4am-node26   <none>           <none>
fouramf-concurrent-rbac-5m2-milvus-querynode-69cffb8544-52bnl     1/1     Running             0                16h     10.104.5.6      4am-node12   <none>           <none>
fouramf-concurrent-rbac-5m2-milvus-querynode-69cffb8544-bl2cs     1/1     Running             0                16h     10.104.23.206   4am-node27   <none>           <none>
fouramf-concurrent-rbac-5m2-milvus-rootcoord-665f6c9796-ll76v     1/1     Running             0                16h     10.104.22.244   4am-node26   <none>           <none>
fouramf-concurrent-rbac-5m2-minio-0                               1/1     Running             0                16h     10.104.23.183   4am-node27   <none>           <none>
fouramf-concurrent-rbac-5m2-minio-1                               1/1     Running             0                16h     10.104.16.7     4am-node21   <none>           <none>
fouramf-concurrent-rbac-5m2-minio-2                               1/1     Running             0                16h     10.104.22.242   4am-node26   <none>           <none>
fouramf-concurrent-rbac-5m2-minio-3                               1/1     Running             0                16h     10.104.1.40     4am-node10   <none>           <none>
fouramf-concurrent-rbac-5m2-pulsar-bookie-0                       1/1     Running             0                16h     10.104.23.189   4am-node27   <none>           <none>
fouramf-concurrent-rbac-5m2-pulsar-bookie-1                       1/1     Running             0                16h     10.104.16.12    4am-node21   <none>           <none>
fouramf-concurrent-rbac-5m2-pulsar-bookie-2                       1/1     Running             0                16h     10.104.9.254    4am-node14   <none>           <none>
fouramf-concurrent-rbac-5m2-pulsar-bookie-init-ndrhz              0/1     Completed           0                16h     10.104.23.174   4am-node27   <none>           <none>
fouramf-concurrent-rbac-5m2-pulsar-broker-0                       1/1     Running             0                16h     10.104.23.178   4am-node27   <none>           <none>
fouramf-concurrent-rbac-5m2-pulsar-proxy-0                        1/1     Running             0                16h     10.104.23.179   4am-node27   <none>           <none>
fouramf-concurrent-rbac-5m2-pulsar-pulsar-init-h5nql              0/1     Completed           0                16h     10.104.23.175   4am-node27   <none>           <none>
fouramf-concurrent-rbac-5m2-pulsar-recovery-0                     1/1     Running             0                16h     10.104.16.6     4am-node21   <none>           <none>
fouramf-concurrent-rbac-5m2-pulsar-zookeeper-0                    1/1     Running             0                16h     10.104.23.188   4am-node27   <none>           <none>
fouramf-concurrent-rbac-5m2-pulsar-zookeeper-1                    1/1     Running             0                16h     10.104.16.14    4am-node21   <none>           <none>
fouramf-concurrent-rbac-5m2-pulsar-zookeeper-2                    1/1     Running             0                16h     10.104.5.253    4am-node12   <none>           <none>
```
```


### Milvus Log

_No response_

### Anything else?

case params:
```
{'dataset_params': {'metric_type': 'L2',
                                                    'dim': 128,
                                                    'dataset_name': 'sift',
                                                    'dataset_size': '5m',
                                                    'ni_per': 50000},
                                 'collection_params': {'other_fields': []},
                                 'load_params': {},
                                 'query_params': {},
                                 'search_params': {},
                                 'database_user_params': {'reset_rbac': False,
                                                          'reset_db': False},
                                 'index_params': {'index_type': 'HNSW',
                                                  'index_param': {'M': 8,
                                                                  'efConstruction': 200}},
                                 'concurrent_params': {'concurrent_number': 50,
                                                       'during_time': '4h',
                                                       'interval': 60,
                                                       'spawn_rate': None},
                                 'concurrent_tasks': [{'type': 'search',
                                                       'weight': 1,
                                                       'params': {'nq': 100,
                                                                  'timeout': 600,
                                                                  'top_k': 100,
                                                                  'search_param': {'ef': 120},
                                                                  'random_data': True}}]},
```

**Comment by ThreadDao** [comment]
Same issue when search with different nq (nq=1 or nq=1000)
 4am argo workflow name: `fouramf-concurrent-rbac-nq5`

there are total 2 querynodes, on qn-1 all user's search queue latency:
![image](https://github.com/milvus-io/milvus/assets/27288593/ff68d97d-f49b-4ced-897a-87de4ea551a8)

on qn-4 all user's search queue latency:
![image](https://github.com/milvus-io/milvus/assets/27288593/1b4e321e-91c7-4cce-8792-fc794141edca)

grafana link: https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=qa-milvus&var-instance=fouramf-concurrent-rbac-nq5&var-collection=All&var-app_name=milvus&from=1688712839362&to=1688738747688

**Comment by chyezh** [comment]
A search shard task may be split and assigned to multiple query node.
The number of subtasks will increase due to this process.
The more tasks, the longer the queue of this user's task and the greater queue latency.

Difference between high queue time and low queue time
- High queue latency, there's two tasks here:
![image](https://github.com/milvus-io/milvus/assets/20332315/b7d6985e-c4fc-4e91-9aaf-3c9f3f05b2d4)
- Low queue latency, there's only one task here:
![image](https://github.com/milvus-io/milvus/assets/20332315/4a06198c-3f53-4a17-bd13-40fd3eca2c92)
So high queue users have double queue length of low queue time users.

I will provide a PR to reduce the task granularity to segment granularity in scheduler, to solve this problem

**Comment by chyezh** [comment]
# Another problem
Two query node's workloads and latency are completely different.
- Segcore request rate. 
![image](https://github.com/milvus-io/milvus/assets/20332315/bf30b0de-5214-45e9-a743-277d6408e1cf)
- Segment loaded count.
![image](https://github.com/milvus-io/milvus/assets/20332315/796c774c-6443-4b6d-988a-ac3814d23176)
- Average entity per collection on different query nodes.
![image](https://github.com/milvus-io/milvus/assets/20332315/d3516600-5723-4c45-b4a4-9755be8d7c16)
- Bug the segcore average lantency is different.
![image](https://github.com/milvus-io/milvus/assets/20332315/7a6ef9ba-6aa0-4ae8-90a7-a9d421e13eb8)
- [workloads](https://grafana-4am.zilliz.cc/d/6581e46e4e5c7ba40a07646395ef7b23/kubernetes-compute-resources-pod?orgId=1&from=1689079963311&to=1689092181323&var-datasource=prometheus&var-cluster=&var-namespace=qa-milvus&var-pod=fouramf-concurrent-rbac-5m5-yz6-milvus-querynode-85fd5664fc55x8)
![image](https://github.com/milvus-io/milvus/assets/20332315/9b80a373-fb22-4b58-8b7e-2cb6f33101aa)
![image](https://github.com/milvus-io/milvus/assets/20332315/065617e1-596d-40c6-8ccf-37f7ea2645b9)

# Debug
- It seems that the unfair user task scheduler causes clients of different collections to send search requests with different qps.
- For example, Collection `442780864668438509` has high queue latency and slower QPS, and its main segment is on the quernode `85fd5664fc55x8` （874123791 vs 507460949）. So `85fd5664fc55x8` gets lower workloads.

**Comment by yanliang567** [comment]
@chyezh any updates
