### ISSUE TITLE
[Bug]:["failed to get client address"] [error="find no available rootcoord, check rootcoord state"] 

### ISSUE THREAD

**Issue by hubin1108** [milvus-io/milvus#25355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.8
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS):Ubuntu
- CPU/Memory: 400G
- GPU: 
- Others: 
    go = 1.20.5
    cmake = 3.18
    gcc=7.5.0
```

### Current Behavior

我是想编译源码方式安装milvus，但是编译源码一直没走通。于是，我尝试进入docker把容器里编译好的milvus拷贝到本地启动，相关的lib环境也export了，然后通过./bin/milvus run standalone启动

### Steps To Reproduce

```markdown
1、依赖组件启动：
   /developments/docker/dev执行docker-compose up -d
2、启动milvus：
   cd /milvus
   $LIBJEMALLOC = /milvus/lib/libjemalloc.so
   export LD_PRELOAD = "$LIBJEMALLOC"
   export LD_LIBRARY_PATH = $PWD/lib/
   ./bin/milvus run standalone
```

### Milvus Log

[standalone.log](https://github.com/milvus-io/milvus/files/11963843/standalone.log)

**Comment by jiaoew1991** [comment]
@hubin1108 Your usage is very unconventional. Although it can work, I do not recommend doing so.

**Comment by jiaoew1991** [comment]
From the logs, it can be seen that the configuration was not read, and at the same time, etcd failed to connect correctly. 

If you want to use Milvus, it is best to use it in k8s or Docker Compose. Otherwise, you will encounter many strange environmental issues.

**Comment by hubin1108** [comment]
The official only provides a docker-based deployment solution, but in some businesses, it is not required to use docker. So you can only compile and install based on source code or my method. Please help me to see the error log, thank you very much @jiaoew1991

**Comment by xiaofan-luan** [comment]
the error is ":The Access Key Id you provided does not exist in our records.
"

**Comment by xiaofan-luan** [comment]
which means you don't provide a valid access ID for minio or S3
