### ISSUE TITLE
[Bug]: k8s install milvus cluster failed

### ISSUE THREAD

**Issue by tianyunzqs** [milvus-io/milvus#25373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I get the error when install the milvus with k8s. I have not idea to solve it. Can you helper me with it?

`kubectl get pods | grep my-release`
![image](https://github.com/milvus-io/milvus/assets/23567448/6d884d3b-749d-469e-8366-1498747b7d3c)

`kubectl describe pod my-release-etcd-0` 
![image](https://github.com/milvus-io/milvus/assets/23567448/a74c1ce3-be72-48ec-8dbe-eeec81e93866)

`kubectl get pvc`
![image](https://github.com/milvus-io/milvus/assets/23567448/8f2869d6-2af6-412c-88b1-a92ea0fa6df4)

**Comment by yanliang567** [comment]
@tianyunzqs could you please describe the pod and attach the info?

/assign @tianyunzqs 
/unassign
