### ISSUE TITLE
[Bug]: The JSON column data returned by the query interface is incorrect.

### ISSUE THREAD

**Issue by lentitude2tk** [milvus-io/milvus#25385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.11-hotfix-xxx
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka): kafka 
- SDK version(e.g. pymilvus v2.0.0rc2): milvus-java-sdk & pymilvus
- OS(Ubuntu or CentOS): Macos
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Create a schema column with a JSON Type and insert multiple rows of data. One of the data entries is as follows:
```
"id": "162ebdcc-b7e9-4afc-b668-dcdc03dbe788",
"type": 1,
"meta": {
	"xxx": abc
}
```
However, when querying using the milvus-java-sdk and specifying multiple IDs, such as id in ["a", "b", "162ebdcc-b7e9-4afc-b668-dcdc03dbe788", "xxx", ...], when examining the fieldsData information returned by Milvus, the meta data for the third entry in meta is not the meta data corresponding to "162ebdcc-b7e9-4afc-b668-dcdc03dbe788". The order of the data in the returned meta is not guaranteed, while the order of other fields is correct.

### Expected Behavior

The order of the data in fieldsData for id, type, and meta remains consistent.

### Steps To Reproduce

```markdown
1. Use insert or bulkInsert to write the following data.
2. Call the query interface to query data using id in [a, b, c].
3. Check the returned fieldsData and observe that the meta data is disordered, for example, the meta data of 'c' is the first one instead of 'a'.
```

**Comment by lentitude2tk** [comment]
The relevant data files are as follows.
[invalidJsonReturn.txt](https://github.com/milvus-io/milvus/files/11968551/invalidJsonReturn.txt)

**Comment by lentitude2tk** [comment]
Additionally, if there is only one condition for the query, such as id in ["162ebdcc-b7e9-4afc-b668-dcdc03dbe788"], the data obtained will be correct. The inconsistency in the order of the JSON column data with respect to other columns occurs only when querying multiple data entries.

**Comment by lentitude2tk** [comment]
The same issue exists when using pymilvus to perform a query.

**Comment by lentitude2tk** [comment]
The created collection is shown below:
```
FieldType fieldType1 = FieldType.newBuilder()
                .withName("id")
                .withDataType(DataType.VarChar)
                .withMaxLength(100)
                .withPrimaryKey(true)
                .withAutoID(false)
                .build();

        FieldType fieldType2 = FieldType.newBuilder()
                .withName("alias_vector")
                .withDataType(DataType.FloatVector)
                .withDimension(1536)
                .build();

        FieldType fieldType3 = FieldType.newBuilder()
                .withName("type")
                .withDataType(DataType.Int64)
                .build();

        FieldType fieldType4 = FieldType.newBuilder()
                .withName("meta")
                .withDataType(DataType.JSON)
                .build();

        CreateCollectionParam createCollectionReq = CreateCollectionParam.newBuilder()
                .withCollectionName("testErrorData")
                .withShardsNum(2)
                .withEnableDynamicField(false)
                .addFieldType(fieldType1)
                .addFieldType(fieldType2)
                .addFieldType(fieldType3)
                .addFieldType(fieldType4)
                .build();
```

**Comment by xiaofan-luan** [comment]
I think we always order the data by pk and distance in search, not by any value

**Comment by yanliang567** [comment]
@xiaocai2333 any updates? please let us know if it requires new tests.
/unassign

**Comment by xiaocai2333** [comment]
The JSON column was not being swapped during sorting of the PK column. fixing it.

**Comment by yah01** [comment]
our tests should shuffle the primary keys to test the segment-level, channel-level and collection-level reduce/sort, the tests currently generate increasing primary keys, then we can't find bug in reduce/sort process.

@yanliang567 any thought about this?

**Comment by binbinlv** [comment]
> our tests should shuffle the primary keys to test the segment-level, channel-level and collection-level reduce/sort, the tests currently generate increasing primary keys, then we can't find bug in reduce/sort process.
> 
> @yanliang567 any thought about this?

@yah01 
we will add some tests to cover the primary keys not in order.

**Comment by xiaofan-luan** [comment]
has been fixed. Wait for 2.2.12
