### ISSUE TITLE
User authentication and authorization

### ISSUE THREAD

**Issue by JinHai-CN** [milvus-io/milvus#254]
**Is your feature request related to a problem? Please describe.**
Currently, Milvus doesn't have the concept of user. 

**Describe the solution you'd like**
As traditional SQL DB, Milvus should provide user authentication / authorization function

**Comment by kbbk16** [comment]
![5D15FA3E-EB42-4D49-BF02-5822BDD022A9](https://user-images.githubusercontent.com/57279351/68523177-5fd53100-0283-11ea-9907-d39059282369.png)

**Comment by JinHai-CN** [comment]
@kbbk16 Please check you are replying the right topic. Thank you.

**Comment by yhmo** [comment]
Will be considered in v2.x

**Comment by yhmo** [comment]
Close this one. Tracked by #6647
