### ISSUE TITLE
[Enhancement]: Read from mmap copies data (golang chunk manager)

### ISSUE THREAD

**Issue by sunby** [milvus-io/milvus#25430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Call syscall.Mmap/syscall.Munmap directly and cache/release the data to avoid copy when reading it.

### Why is this needed?

Avoid a copy from mmaped data.

**Comment by shunjiezhao** [comment]
Good Morning~~
It is possible to read the `data` field in the `mmap.ReadAt` struct using reflection, without the need to modify the interface.
```go
readAt, err := mmap.Open(filePath)
if err != nil {
return nil, err
}
readAtType := reflect.TypeOf(readAt).Elem()    
dataField, _ := readAtType.FieldByName("data") 

readAtValue := reflect.ValueOf(readAt).Elem()         
dataValue := readAtValue.FieldByIndex(dataField.Index)  
num := dataValue.Len()
c := dataValue.Cap()
data := &[]byte{}

ptr := unsafe.Pointer(&data)  
*(*reflect.SliceHeader)(ptr) = reflect.SliceHeader{
Data: dataValue.UnsafeAddr(),
Len:  num,
Cap:  c,
}
fmt.Println(*data)
```
Can I use this method to do it ?

**Comment by sunby** [comment]
> Good Morning~~ It is possible to read the `data` field in the `mmap.ReadAt` struct using reflection, without the need to modify the interface.
> 
> ```go
> readAt, err := mmap.Open(filePath)
> if err != nil {
> return nil, err
> }
> readAtType := reflect.TypeOf(readAt).Elem()    
> dataField, _ := readAtType.FieldByName("data") 
> 
> readAtValue := reflect.ValueOf(readAt).Elem()         
> dataValue := readAtValue.FieldByIndex(dataField.Index)  
> num := dataValue.Len()
> c := dataValue.Cap()
> data := &[]byte{}
> 
> ptr := unsafe.Pointer(&data)  
> *(*reflect.SliceHeader)(ptr) = reflect.SliceHeader{
> Data: dataValue.UnsafeAddr(),
> Len:  num,
> Cap:  c,
> }
> fmt.Println(*data)
> ```
> 
> Can I use this method to do it ?

Thanks for your reply!

IMHO, my suggestion is calling the syscall.Mmap directly to get the memory slice, just like what the mmap.Open actually do. But considering different mmap system call usage for different operating systems, maybe this problem is more complicated than I think.

Back to your method, I am not sure if the reflection's performance is better than copying the memory. Maybe we should test and compare them. If there's no big difference between the performance of these two methods, we still prefer to have a copy which has simple and clean codes.

**Comment by shunjiezhao** [comment]
> > Good Morning~~ It is possible to read the `data` field in the `mmap.ReadAt` struct using reflection, without the need to modify the interface.
> > ```go
> > readAt, err := mmap.Open(filePath)
> > if err != nil {
> > return nil, err
> > }
> > readAtType := reflect.TypeOf(readAt).Elem()    
> > dataField, _ := readAtType.FieldByName("data") 
> > 
> > readAtValue := reflect.ValueOf(readAt).Elem()         
> > dataValue := readAtValue.FieldByIndex(dataField.Index)  
> > num := dataValue.Len()
> > c := dataValue.Cap()
> > data := &[]byte{}
> > 
> > ptr := unsafe.Pointer(&data)  
> > *(*reflect.SliceHeader)(ptr) = reflect.SliceHeader{
> > Data: dataValue.UnsafeAddr(),
> > Len:  num,
> > Cap:  c,
> > }
> > fmt.Println(*data)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Can I use this method to do it ?
> 
> Thanks for your reply!
> 
> IMHO, my suggestion is calling the syscall.Mmap directly to get the memory slice, just like what the mmap.Open actually do. But considering different mmap system call usage for different operating systems, maybe this problem is more complicated than I think.
> 
> Back to your method, I am not sure if the reflection's performance is better than copying the memory. Maybe we should test and compare them. If there's no big difference between the performance of these two methods, we still prefer to have a copy which has simple and clean codes.

sorry, the method I proposed is really not applicable.

I see that the build environment only supports macos and linux, they both have mmap, parameter differences and I'll look at their documentation in a minute.
> Avoid a copy from mmaped data.

Does this mean that the slices we return are **the same as** the slices in the local chunk manager cache?

**Comment by jiaoew1991** [comment]
keep it
