### ISSUE TITLE
[Enhancement]: Support in-place Index replacement for loaded segment

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#25443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Support in-place index replacement for loaded segment

### Why is this needed?

Load segment without index as growing segment has lot of drawbacks such as
- High memory pressure for shard leader
- Confusing logic for sealed as growing patch

**Comment by congqixia** [comment]
- [ ] Add index info in `GetDataDistribution`
- [ ] Add load-index sync operation
- [ ] Add segment in-place replacement in `segment`

**Comment by xiaofan-luan** [comment]
LGTM.
We should still separate non-indexed segment and growing segment

**Comment by congqixia** [comment]
mark as done
