### ISSUE TITLE
[Bug]: Grafana dashboard cannot find Milvus instance

### ISSUE THREAD

**Issue by Erzangel** [milvus-io/milvus#25456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): X
- OS(Ubuntu or CentOS): X
- CPU/Memory: 
- GPU: 
- Others: Milvus Helm Chart version milvus-4.0.27
```

### Current Behavior

When following the steps in the docs to [set up monitoring](https://milvus.io/docs/monitor.md) and [visualize Milvus metrics in Grafana](https://milvus.io/docs/visualize.md), the imported dashboard does not find my Milvus instance.

<img width="1295" alt="image" src="https://github.com/milvus-io/milvus/assets/57399897/f444aa72-c22d-4eb3-9887-f086b76090b7">

- I have set `metrics.serviceMonitor.enabled` to `true`;
- `kubectl get servicemonitor -n milvus` does yield the `milvus-cluster` ServiceMonitor;
- Milvus pods have the `app.kubernetes.io/instance=milvus-cluster` label.

I use:
- Kubernetes 1.25 deployed on Azure AKS;
- A Milvus deployment with the latest version of the Helm chart, in a `milvus` namespace and with a release named `milvus-cluster`;
- kube-prometheus on branch `release-0.12` (for compatibility with Kubernetes 1.25);
- the JSON dashboard (2.2.0) which can be found [here](https://github.com/milvus-io/milvus/blob/master/deployments/monitor/grafana/milvus-dashboard.json). I also tried 2.1.0 and 2.3.0, which did not work either.

### Expected Behavior

The Grafana dashboard should be able to find my instance, as `milvus-cluster`, and display the metrics.

### Steps To Reproduce

```markdown
1. Use a fresh & clean Kubernetes cluster on 1.25.
2. Deploy Milvus using the Helm chart (with default values): `helm upgrade --install milvus-cluster milvus/milvus --namespace milvus --create-namespace`
3. Deploy kube-prometheus from their repo, using the `release-0.12 branch`: 


git clone https://github.com/prometheus-operator/kube-prometheus.git
cd kube-prometheus
git checkout release-0.12
kubectl apply --server-side -f manifests/setup
kubectl wait \
        --for condition=Established \
        --all CustomResourceDefinition \
        --namespace=monitoring
kubectl apply -f manifests/


4. Port-forward the two Prometheus & Grafana services on dedicated terminal windows:
   - `kubectl --namespace monitoring --address 0.0.0.0 port-forward svc/prometheus-k8s 9090`
   - `kubectl --namespace monitoring --address 0.0.0.0 port-forward svc/grafana 3000`

5. Update the Helm chart to enable the serviceMonitor: `helm upgrade milvus-cluster -n milvus milvus/milvus --set metrics.serviceMonitor.enabled=true --reuse-values`

6. Access your web browser on localhost:3000, connect to Grafana using `admin:admin`

7. Import the following Grafana dashboard: `wget https://raw.githubusercontent.com/milvus-io/milvus/2.2.0/deployments/monitor/grafana/milvus-dashboard.json`

8. Try to visualize metrics
```

**Comment by Erzangel** [comment]
Figured out what was going wrong: the `kube-prometheus` basic setup only detects serviceMonitors from the `default` and `monitoring` namespace.

As I was deploying the Milvus cluster in the `milvus` namespace, neither Prometheus nor Grafana could detect the serviceMonitor:

```
Failed to watch *v1.Pod: failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:monitoring:prometheus-k8s\" cannot list resource \"pods\" in API group \"\" in the namespace \"milvus\""
```

Setting up monitoring for other namespaces can be done by following [those docs to customize the kube-prometheus manifests](https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/monitoring-other-namespaces.md). After following those steps, monitoring worked great!

The docs should mention this: deploying Milvus in `default` works fine, but using any other namespace prevents Prometheus from discovering the serviceMonitor.

Closing this issue.

**Comment by yuan8180** [comment]
thanks Erzangel，I have the same problem. I solve the problem by your link:https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/monitoring-other-namespaces.md

My experience is as following:
#参考文章：
#修改kube-prometheus调整namespace：https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/monitoring-other-namespaces.md
#使它生效：https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/customizing.md
#前提：可连外网+已安装golang

mkdir my-kube-prometheus; cd my-kube-prometheus
go install -a github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb@latest
# Creates the initial/empty `jsonnetfile.json`，如果报错command not found，参考 https://github.com/jsonnet-bundler/jsonnet-bundler#install
jb init  
#安装依赖包Creates `vendor/` & `jsonnetfile.lock.json`, and fills in `jsonnetfile.json`
jb install github.com/prometheus-operator/kube-prometheus/jsonnet/kube-prometheus@main
wget https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/main/example.jsonnet -O example.jsonnet
wget https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/main/build.sh -O build.sh
chmod +x build.sh
jb update
#安装工具：gojsontoyaml和jsonnet
go install github.com/brancz/gojsontoyaml@latest
go install github.com/google/go-jsonnet/cmd/jsonnet@latest
#因为我把要监控的milvus放在namespace=milvus_search，所以修改 example.jsonnet如下：
===================================================
  {
    values+:: {
      common+: {
        namespace: 'monitoring',
      },
    },
  };
改为
  {
    values+:: {
      common+: {
        namespace: 'monitoring',
      },

      prometheus+:: {
        namespaces: ["default", "kube-system", "monitoring", "milvus_search"],
      },
    },
  };

===================================================
# 编译
./build.sh example.jsonnet
# Update the namespace and CRDs, and then wait for them to be available before creating the remaining resources
kubectl apply --server-side -f manifests/setup
kubectl wait \
      --for condition=Established \
      --all CustomResourceDefinition \
      --namespace=monitoring
kubectl apply -f manifests/
#删除监控：
kubectl delete --ignore-not-found=true -f manifests/ -f manifests/setup
#查看pod是否启动
kubectl get pods -n monitoring
#启动监控：
kubectl --namespace monitoring --address 0.0.0.0 port-forward svc/prometheus-k8s 3002:9090 > ~/workspace/log_k8s/pf3002_prometheus.out & 
kubectl --namespace monitoring --address 0.0.0.0 port-forward svc/grafana 3003:3000 > ~/workspace/log_k8s/pf3003_grafana.out & 
#绑定监控milvus：
cd ~/workspace/go/src/milvus_search/svc/search_service/k8s/
helm upgrade my-release milvus/milvus  --set metrics.serviceMonitor.enabled=true --reuse-values -n milvus-search
#查看监控状态：
kubectl get servicemonitor -n milvus-search
============================
NAME                AGE
my-release-milvus   21s
============================
#打开网页：http://x.x.x.x:3003/login
#用户名：admin
#密码：admin（已改milvus）
#加载监控参数：
wget https://raw.githubusercontent.com/milvus-io/milvus/2.3.0/deployments/monitor/grafana/milvus-dashboard.json
#uuid：uLf5cJ3Gz
#左上角菜单栏展开，点击dashboard，出来页面点击New展开，点击Import，点击Upload dashboard json file，选择上面下载的json：milvus-dashboard.json，确认uuid是对的，点击Import
#选择namespace=milvus-search（milvus应用所在命名空间），选择instance=my-release（我的应用叫这个名字），选择后，下面会显示监控结果，如果等1分钟某个图表里一直显示no data，说明没监控上。
