### ISSUE TITLE
Inserting the same vectors (/w ids) results in multiple copies in the index

### ISSUE THREAD

**Issue by mromaios** [milvus-io/milvus#2545]
**Describe the bug**
When inserting already existing vectors (w/ fixed ids) these appear multiple times in the index and are also returned multiple times during search
e.g. 
`client.insert(collection_name=collection, records=vectors, ids=ids)
 client.insert(collection_name=collection, records=vectors, ids=ids)`
will result in a collection with count_entities = 2 x len(vectors)
Tried flushing, compacting, rebuilding the index.
The problem appears also during search.

**Steps/Code to reproduce behavior**
```python
from milvus import Milvus, IndexType, MetricType, Status
import random

client = Milvus(host='localhost', port='19530')
collection = "DupVBug"
param = {'collection_name': collection, 'dimension': 300, 'index_file_size': 1024, 'metric_type': MetricType.L2}
client.create_collection(param)
records = [[random.random() for _ in range(300)] for _ in range(10)]
ids = list(range(len(records)))
client.insert(collection_name=collection, records=records, ids=ids)
client.count_entities(collection)
```
```python
In [79]: client.count_entities(collection)                                                                                                                                                                 
Out[79]: (Status(code=0, message='Success!'), 10)
```
```.python
client.insert(collection_name=collection, records=records, ids=ids)
client.count_entities(collection)
```
```python
In [87]: client.count_entities(collection)                                                                                                                                                                 
Out[87]: (Status(code=0, message='Success!'), 20)
```
```python
client.flush([collection])
client.compact(collection)
client.count_entities(collection)
```
```python
In [87]: client.count_entities(collection)                                                                                                                                                                 
Out[87]: (Status(code=0, message='Success!'), 20)
```
```python
ivf_param = {}
client.create_index(collection, IndexType.FLAT, ivf_param)
r = client.get_entity_by_id(collection_name=collection, ids=[1])                                                                                                                                  
client.search(collection_name=collection, top_k=5, query_records=r[1])  
```                                                                                                                          
```Out[92]: 
(Status(code=0, message='Search vectors successfully!'),
 [ [
 (id:1, distance:0.0),
 (id:1, distance:0.0),
 (id:6, distance:45.0120849609375),
 (id:6, distance:45.0120849609375),
 (id:0, distance:46.12508010864258)
 ] ])
```

**Expected behavior**
Would expect inserting the same vector with an already existing id to not produce duplicates. Count_entities (and collection_stats) should show unique vectors based on their ids.
Search shouldn't return the vector more than once 

**Environment details**
- Method of installation : Docker (Both CPU and GPU versions)
- Milvus version: 0.9.0

**Comment by tinkerlin** [comment]
Milvus cannot guarantee the uniqueness of vectors.
@mromaios

**Comment by mromaios** [comment]
@tinkerlin oh, must have missed that in the documentation, thanks.

Feels counterintuitive to be able to store different vectors with the same id though and not be able to keep only the latest addition.

**Comment by tinkerlin** [comment]
I feel the same way as you do. In order to maintain uniqueness, Milvus must add more checking mechanisms, which can make a huge difference in insertion(searching) performance. We are also discussing finding a good solution.
@mromaios

**Comment by mromaios** [comment]
@tinkerlin true. Another idea might be to do this on index creation time (or have some function to do this). So it would be an "eventually" non duplicate system.  
That might feel as an incomplete solution to some as well though...

Whatever the case, thank you for your responses!

**Comment by nizamsp** [comment]
Thanks for the great library.

while creating the schema, I have set is_primary=True and auto_id=False.  Doesn't that convey that the primary key should be unique? 
What's the use of the is_primary field. Can you please enlighten me?

**Comment by xiaofan-luan** [comment]
> Thanks for the great library.
> 
> while creating the schema, I have set is_primary=True and auto_id=False. Doesn't that convey that the primary key should be unique? What's the use of the is_primary field. Can you please enlighten me?

if auto_id = False, then user should control primary key is unique.  Primary key is usually used to keep mapping with other database. 
When doing search milvus will return PK, Score so you can use PK to get other field
