### ISSUE TITLE
[Enhancement]: Add e2e test case for query result

### ISSUE THREAD

**Issue by xiaocai2333** [milvus-io/milvus#25484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Add test for query result.
example:
insert data:
```
{"id": 0, "number": 1, json:{"a": "a", "b": "b"}, "str": "abc"}
{"id": 1, "number": 2, json:{"aa": "aa", "bb": "bb"}, "str": "def"}
{"id": 2, "number": 3, json:{"aaa": "aaa", "bbb": "bbb"}, "str": "ghi"}
```
query:
```
res = Query("pk in [0, 1, 2]")
```

check result:
```
for r in res:
  if r["id"] == 0:
    assert r["number"] == 1
    assert r["json"] == "{a": "a", "b": "b"}"
    assert r["str"] == "abc"
...
```

**Comment by yanliang567** [comment]
/assign @binbinlv 
please help to follow up

**Comment by binbinlv** [comment]
We have check for query result, I think here you want to address is to add tests about inserted data which is not in order, then check the query result?

This is in progress.
