### ISSUE TITLE
[Bug]: [restful] Data is None (or null) when result is empty

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#25497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The data will be None when there is no collection for list collections or no result for get and query.

```
{'code': 200, 'data': None}
```

### Expected Behavior

It would be more reasonable to change it be []. (empty list)

And for the serverless restful API, it behaves like the way above (use [] rather than None)

**Comment by zhuwenxing** [comment]
/assign @PowderLi 

PLAT

**Comment by PowderLi** [comment]
place a get/query request return None, please
