### ISSUE TITLE
[Feature]: Support TiKV as metadata storage

### ISSUE THREAD

**Issue by yiwangdr** [milvus-io/milvus#25506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Currently, we only support etcd as the metadata storage.
ETCD has a lot of nice features but it is limited by its horizontal scalability. We would like to support a more scalable metadata storage: TiKV.

**Comment by xiaofan-luan** [comment]
we just need another layer of meta KV abstraction so we support other KV storage too

**Comment by yiwangdr** [comment]
> we just need another layer of meta KV abstraction so we support other KV storage too

`MetaKv` will be that layer after (1) interface refactory and (2) watch clean up.
These two items are on track.
