### ISSUE TITLE
[Enhancement]: a better policy for nq merge 

### ISSUE THREAD

**Issue by weiliu1031** [milvus-io/milvus#25501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

1. if milvus pass a large nq request to knowhere, such as 50000, which may cause a worse latency and qps
2. if milvus pass a small nq request to knowhere, such as 50, which may cause low usage of cpu resource.

### Why is this needed?

we supposed that knowhere has different vps for different index type, so the nq limit shouldn't be a fixed value. we expect a better way that milvus could get the exec speed and  workload on knowhere and make decision based on those infos

**Comment by xiaofan-luan** [comment]
any detailed plans and numbers could be shared?
