### ISSUE TITLE
[Bug]:  Attu cannot log in

### ISSUE THREAD

**Issue by lymbjtungirc** [milvus-io/milvus#25523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.11
- Deployment mode(standalone or cluster):standalone   
- OS(Ubuntu or CentOS): CentOS
```

### Current Behavior

 I can connect to Milvus using the SDK and operate the database, which proves that Milvus has started normally, and the IP address and port are correct. After installing Attu, I added it to the docker-compose.yml file according to the official website's example. The web page can start normally, but when I try to log in using the IP address and port, it prompts me "Error: Milvus is not ready yet.". I don't understand this error, and there is no reference available. As shown in the picture below, what should I do?
![image](https://github.com/milvus-io/milvus/assets/139320184/a94c0c99-80a1-4f4a-bea4-66cd21e04dc8)
![image](https://github.com/milvus-io/milvus/assets/139320184/f4afcf02-377c-4880-9da3-bdd955a0e61a)

**Comment by yanliang567** [comment]
@lymbjtungirc could you please try to connect the milvus via sdk, such as pymilvus

/assign @lymbjtungirc 
/unassign

**Comment by yanliang567** [comment]
@lymbjtungirc which version of Attu are you using?

/assign @shanghaikid 
could you please help on this？

/unassign

**Comment by shanghaikid** [comment]
could you upgrade attu to the latest version?

**Comment by lymbjtungirc** [comment]
@shanghaikid。Hello, thank you for your answer. I'm using Attu version v2.2.6, which might be the latest version. How can I check the version of Milvus I have installed? I think I installed Milvus version v2.2.11, but when I run docker ps, it shows milvusdb/milvus:v2.0.0, which is a bit confusing. （Are you Chinese? Can I use Chinese then, haha?）As shown in the picture below:
![image](https://github.com/milvus-io/milvus/assets/139320184/23013940-7fb8-4d8b-8242-d8185b3f9553)

**Comment by shanghaikid** [comment]
简单说一下，attu常见连不上的原因是网络问题，因为attu是cs结构，因为你装的是docker版本，所以首先确保attu和milvus在一个docker network下，然后你在界面上输入的ip地址是会通过attu 这个server去访问milvus的，所以请确保你输入的milvus 的ip地址，从attu docker里面是可以访问到的。 

不过从你的现象来看，checkHealth 失败才会报这个错， 看起来你是milvus版本不对。checkHealth 这个函数不支持老版本的milvus。 你是从哪里看到的文档？ 感觉好老。

**Comment by shanghaikid** [comment]
https://github.com/milvus-io/milvus/releases/download/v2.2.11/milvus-standalone-docker-compose.yml 

应该用这个文件

**Comment by lymbjtungirc** [comment]
@shanghaikid  哥，抱歉再打扰下，我按照你的链接更新了docker-compose.yml。目前milvus-minio这个容器启动不了看起来，您方便看看嘛：
![image](https://github.com/milvus-io/milvus/assets/139320184/906dfe7d-0967-49ed-a650-6c639c21be02)
![image](https://github.com/milvus-io/milvus/assets/139320184/36c05671-ee59-44c1-ac22-fd15fd751216)

**Comment by shanghaikid** [comment]
@yanliang567 你能帮忙看一下吗？

**Comment by lymbjtungirc** [comment]
@yanliang567 好像是说启动失败的原因是它无法使用 /minio_data 驱动器。错误信息为：ERROR Unable to use the drive /minio_data: Drive /minio_data: found backend type fs, expected xl or xl-single - to migrate to a supported backend visit https://min.io/docs/minio/linux/operations/install-deploy-manage/migrate-fs-gateway.html: Invalid arguments specified
![image](https://github.com/milvus-io/milvus/assets/139320184/abde0712-c6ee-40b9-9e3e-2c949fe82adf)

**Comment by lymbjtungirc** [comment]
@yanliang567 谢谢谢谢，解决了，sudo rm -rf  volumes  ，运行这个后重新sudo docker-compose up -d 就好了

**Comment by lymbjtungirc** [comment]
@yanliang567 @shanghaikid Attu也可以上了，确实是我自己milvus版本太老了。感谢两位大佬的支持

**Comment by yanliang567** [comment]
seems to be a minio issue? If you can lose all the existing data in the current milvus, you can try
1. docker compose down all the milvus pods
2. delete the volume folder
3. and then docker compose up again
