### ISSUE TITLE
[Bug]: 2.2.0 branch unit tests crashed

### ISSUE THREAD

**Issue by sunby** [milvus-io/milvus#25530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Unit tests crashed.
![i2yn33AuF5](https://github.com/milvus-io/milvus/assets/9817127/af561b7c-8f60-48f7-98e3-20ad481e3163)

**Comment by xiaofan-luan** [comment]
we find this might related to the segment is leaked under some test.

try to add node.metaReplica.freeAll() and this might help
