### ISSUE TITLE
[Bug]: An upsert error was raised when updating pymilvus version to 2.4.0.dev90

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#25535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 82cdeec
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0.dev90
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

An upsert error was raised when updating pymilvus version to 2.4.0.dev90.
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-25479/4/pipeline/129/

![image](https://github.com/milvus-io/milvus/assets/109071306/5b1398b3-ebde-4774-b50a-be24ec7a2bef)

### Expected Behavior

pass

**Comment by smellthemoon** [comment]
related with https://github.com/milvus-io/pymilvus/pull/1581

**Comment by NicoYuan1986** [comment]
upsert error fixed.
