### ISSUE TITLE
Can't build milvus 0.9.1 from source

### ISSUE THREAD

**Issue by AyushP123** [milvus-io/milvus#2553]
OS: Ubuntu 18.04
CUDA Version: 10.1
protobuf version: 3.12.2

I ran `./ubuntu_build_deps.sh` from `milvus/core` and followed it by `./build -g -t Release`

Build completes for 100% and then I get this error.
```
make[2]: *** No rule to make target 'grpc_ep-prefix/src/grpc_ep/libs/opt/protobuf/libprotobuf.a', needed by 'src/milvus_server'.  Stop.
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:527: recipe for target 'src/CMakeFiles/milvus_server.dir/all' failed
make[1]: *** [src/CMakeFiles/milvus_server.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by JinHai-CN** [comment]
Error message isn't enough. And we recommend you to use docker image mentioned here: https://github.com/milvus-io/milvus/blob/master/INSTALL.md#requirements to build Milvus.

**Comment by ucasFL** [comment]
Did you fixed this problem? @AyushP123

**Comment by innerNULL** [comment]
> OS: Ubuntu 18.04
> CUDA Version: 10.1
> protobuf version: 3.12.2
> 
> I ran `./ubuntu_build_deps.sh` from `milvus/core` and followed it by `./build -g -t Release`
> 
> Build completes for 100% and then I get this error.
> 
> ```
> make[2]: *** No rule to make target 'grpc_ep-prefix/src/grpc_ep/libs/opt/protobuf/libprotobuf.a', needed by 'src/milvus_server'.  Stop.
> make[2]: *** Waiting for unfinished jobs....
> CMakeFiles/Makefile2:527: recipe for target 'src/CMakeFiles/milvus_server.dir/all' failed
> make[1]: *** [src/CMakeFiles/milvus_server.dir/all] Error 2
> Makefile:129: recipe for target 'all' failed
> make: *** [all] Error 2
> ```

Hi, did you finally solved this problem?
