### ISSUE TITLE
milvus server链接判断问题

### ISSUE THREAD

**Issue by cutdir** [milvus-io/milvus#2554]
**What is your question?**
当client与server的链接状态变为ConnectivityState.IDLE时，此时channel并没有被显式的中断，client应该也是connected to Milvus server，但是MilvusGrpcClient.isConnected()方法只是判断链接状态为ConnectivityState.READY，这里为什么不判断是否为ConnectivityState.IDLE呢？sdk版本为0.8.1。
源码如下：
public boolean isConnected() {
    if (channel == null) {
      return false;
    }
    ConnectivityState connectivityState = channel.getState(false);
    return connectivityState == ConnectivityState.READY;
  }

**Comment by fishpenguin** [comment]
You are right, ConnectivityState.IDLE should be added to isConnected(). 
However, in 0.9.0 and later version, we cancelled connect() and isConnected() interface, because we just create a channel in connect interface, not real connect, grpc connect is stateless.

**Comment by cutdir** [comment]
感谢回复，针对高版本中去掉这两个接口，有一些疑惑，去掉后client和server如何建立链接呢？channel依然会存在，因为要用来保证长连接的，既然是长连接，那么channel应该是建立在网络的连接层上，那么肯定是有链接状态存在的，对于grpc，我理解只是应用层rpc请求框架，与channel的链接状态没有必然关系。

**Comment by fishpenguin** [comment]
We build connect(I think it is more accurate to call it a channel establishment) when generating a ClientTest instance, the connect state will keep in the instance. And rpc request will use the channel.
