### ISSUE TITLE
[Enhancement]: Need to support compare varchar string which contains special character like "\n" "\t"

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#25554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Currently, if a varchar string contains special characters like "\n" "\t", the search expression cannot do correctly filtering for this kind of string.

**Comment by xiaocai2333** [comment]
same as #24847 ,
support with pr #24848 
only supported on master.

**Comment by xiaocai2333** [comment]
/assign @yhmo 
/assign @yanliang567 
We have support compare escape strings, you can do some simple tests.

**Comment by yanliang567** [comment]
/assign @NicoYuan1986 
could you please add some tests accordingly?

**Comment by NicoYuan1986** [comment]
I will add test cases accordingly.
