### ISSUE TITLE
[Feature]: Enable milvus containers to run as a non-root user

### ISSUE THREAD

**Issue by jarradtp** [milvus-io/milvus#25565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Referencing this: https://github.com/milvus-io/milvus/issues/22516#issuecomment-1452904799

Running containers as root can pose a security risk and is generally not recommended, in certain environment running of container as root is strictly prohibited and prevents milvus from being deployed.

In addition, certain flavors of Kubernetes e.g openshift by default, runs containers with a non-root user (for security reasons) which causes milvus container pods to fail with "write failed: open /milvus/configs/milvus.yaml: permission denied error

### Describe the solution you'd like.

Enable milvus containers to be able to run as a non-root user.

**Comment by tmechineni12** [comment]
Hi, 

Looks like I am having a same issue. Can you please tell what is the status of this. I opened a new issue. See this. https://github.com/zilliztech/milvus-helm/issues/43

**Comment by xiaofan-luan** [comment]
/assign @LoveEachDay 
is there a specific reason for running milvus as root?

**Comment by koflerm** [comment]
+1 for this feature. It seems the only reason it is running as root are wrong file permissions, which can be easily fixed with a proper Dockerfile.

**Comment by jarradtp** [comment]
Coming back to check if there are any updates or plan to fix this.

**Comment by guimou** [comment]
Has anyone started working on this? Otherwise I'll take a stab at it to enrich the ecosystem around OpenShift AI.

**Comment by koflerm** [comment]
I can just explain the procedure how to fix it. It seems it is a simple file/folder permission issue which means should be straight forward to fix it by modifying the Dockerfile of the images of problematic components to include chmod g+rwx and chgrp root on the affected folders. OpenShift requires the root group to have the necessary permissions as all containers by default start with a random UID but each user is in the root group. Hope this helps

**Comment by guimou** [comment]
Yeah, this is what I may do on the short term, this is quite standard procedure to fix ownership/permissions on those types of container.
On the longer term, we may want to contribute a proper UBI-based image.
