### ISSUE TITLE
[Bug]: In the case of repeated loaded sets, memory will continue to rise

### ISSUE THREAD

**Issue by IamCancan** [milvus-io/milvus#25560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.3
- SDK version: java SDK 2.2.8
- OS(Ubuntu or CentOS): CentOS
- CPU  8 Intel(R) Xeon(R) CPU E3-1230 v5 @ 3.40GHz 
- Memory: 32G
```

### Current Behavior

In the case of repeated loaded sets, memory will continue to rise

### Steps To Reproduce

```markdown
milvus 集合face_home数据量 约84w人脸向量

表结构
result_pic_id | Int64
user_feature | FloatVectordim: 512 | _default_idx_101 | IVF_FLAT | metric_type:L2nlist:64
feature_str | VarCharmax: 3000


重启milvus 内存占用0.3%

第一次loaded 集合 fece_home 内存占用 28.8%
第一次unloaded  集合 fece_home 等待五分钟 内存占用 20.8%
 
第二次loaded 集合 fece_home 内存占用  41.7%
第二次unloaded  集合 fece_home 等待五分钟 内存占用 33.2%

第三次loaded 集合 fece_home 内存占用  47.1%
第三次unloaded  集合 fece_home 等待五分钟 内存占用 41.3%

第四次loaded 集合 fece_home 内存占用  47.1%
第四次unloaded  集合 fece_home 等待五分钟 内存占用 41.5%

第五次loaded 集合 fece_home 内存占用 56.1%  load进度60% 
然后程序挂掉了
```

### Milvus Log

{"log":"{\"level\":\"ERROR\",\"time\":\"2023/07/13 07:23:54.408 +00:00\",\"caller\":\"grpcclient/client.go:305\",\"message\":\"ClientBase ReCall grpc second call get error\",\"role\":\"datacoord\",\"error\":\"err: find no available datacoord, check datacoord state\\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:304 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\\n/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:126 github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).GetComponentStates\\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:65 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1\\n/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:37 github.com/milvus-io/milvus/internal/util/retry.Do\\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:89 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates\\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:104 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentHealthy\\n/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:193 github.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).init\\n/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:98 github.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).Run\\n/go/src/github.com/milvus-io/milvus/cmd/components/query_coord.go:53 github.com/milvus-io/milvus/cmd/components.(*QueryCoord).Run\\n\",\"stack\":\"github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\\n\\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:305\\ngithub.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).GetComponentStates\\n\\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:126\\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1\\n\\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:65\\ngithub.com/milvus-io/milvus/internal/util/retry.Do\\n\\t/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:37\\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates\\n\\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:89\\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentHealthy\\n\\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:104\\ngithub.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).init\\n\\t/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:193\\ngithub.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).Run\\n\\t/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:98\\ngithub.com/milvus-io/milvus/cmd/components.(*QueryCoord).Run\\n\\t/go/src/github.com/milvus-io/milvus/cmd/components/query_coord.go:53\\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\\n\\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:104\"}\n","stream":"stdout","time":"2023-07-13T07:23:54.408419948Z"}

**Comment by yanliang567** [comment]
/assign @ThreadDao 
could you please help to reproduce this issue on docker compose deployment?

**Comment by IamCancan** [comment]
可以，milvus都是配置都是默认的，没有改过&nbsp;


徐灿
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月13日(星期四) 下午4:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [milvus-io/milvus] [Bug]: In the case of repeated loaded sets, memory will continue to rise (Issue #25560)





 
/assign @ThreadDao
 could you please help to reproduce this issue on docker compose deployment?

**Comment by xiaofan-luan** [comment]
could you reproduce this on milvus latest?
2.2.11?

**Comment by yanliang567** [comment]
@IamCancan any chance you could retry on v2.2.13
