### ISSUE TITLE
[Feature]: Support empty expression on query

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#25561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Some times user only want the first 1000 data when query.
There is no need to force an expression but the offset limit mechanism should work.

**Comment by xiaofan-luan** [comment]
/assign @longjiquan 
please help on it

**Comment by chasingegg** [comment]
Maybe we could also have something like randomly pick 1000 data, like a commonly used operation `show collection` , currently seems we can not specify the num of results while querying.

**Comment by xiaofan-luan** [comment]
> Maybe we could also have something like randomly pick 1000 data, like a commonly used operation `show collection` , currently seems we can not specify the num of results while querying.

you can use offset and limit together with queries
