### ISSUE TITLE
[Bug]: [bulk insert] should not allow to bulk insert a specific partition if partition key is on

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#25586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230713-587237a3
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
```

### Current Behavior

try to bulk insert a specific partition when the partition key is on.
Notes: although it imported the data into the correct partition instead of the specified partition, but it is still confusing.

### Expected Behavior

report an error msg, e.g. "not support manually specifying the partition names if partition key mode is used"

### Steps To Reproduce

```markdown
task_id, _ = self.utility_wrap.do_bulk_insert(
            collection_name=c_name,
            partition_name=self.collection_wrap.partitions[0].name,
            files=files,)
```

**Comment by yhmo** [comment]
Not a bug.
Allows partition_name because the backup tool requires it.
For a collection with partition key, the backup tool downloads all the binlog files to the local disk, and calls the bulkinsert interface to import binlog files one partition by one partition.

**Comment by yanliang567** [comment]
this would be confusing to an user, could you please add a warn in the doc to info the users. @yhmo @AnthonyTsu1984

**Comment by yanliang567** [comment]
I still prefer adding a check in proxy to avoid confusing to our users. @yhmo

**Comment by yhmo** [comment]
Fix has been merged both on master and 2.2.0 branch

**Comment by yanliang567** [comment]
working on verification

**Comment by yanliang567** [comment]
forgot to mention: verified on miluvs v2.3.0

**Comment by juanandreas** [comment]
how do we write with bulk insert with the partition key on the collection? There is an error that says 
```
milvus.do_bulk_insert(collection_name=COLLECTION, files=list_of_files, partition_name=partition_name)

RPC error: [do_bulk_insert], <MilvusException: (code=2100, message=not allow to set partition name for collection with partition key: importing data failed)>
```

if we exclude the partition_name,

```
milvus.do_bulk_insert(collection_name=COLLECTION, files=list_of_files)

TypeError: do_bulk_insert() missing 1 required positional argument: 'partition_name'
```

This seems contradictory.

**Comment by yanliang567** [comment]
> how do we write with bulk insert with the partition key on the collection? There is an error that says
> 
> ```
> milvus.do_bulk_insert(collection_name=COLLECTION, files=list_of_files, partition_name=partition_name)
> 
> RPC error: [do_bulk_insert], <MilvusException: (code=2100, message=not allow to set partition name for collection with partition key: importing data failed)>
> ```
> 
> if we exclude the partition_name,
> 
> ```
> milvus.do_bulk_insert(collection_name=COLLECTION, files=list_of_files)
> 
> TypeError: do_bulk_insert() missing 1 required positional argument: 'partition_name'
> ```
> 
> This seems contradictory.

which version of milvus and pymilvus are you running

**Comment by juanandreas** [comment]
> > how do we write with bulk insert with the partition key on the collection? There is an error that says
> > ```
> > milvus.do_bulk_insert(collection_name=COLLECTION, files=list_of_files, partition_name=partition_name)
> > 
> > RPC error: [do_bulk_insert], <MilvusException: (code=2100, message=not allow to set partition name for collection with partition key: importing data failed)>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > if we exclude the partition_name,
> > ```
> > milvus.do_bulk_insert(collection_name=COLLECTION, files=list_of_files)
> > 
> > TypeError: do_bulk_insert() missing 1 required positional argument: 'partition_name'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This seems contradictory.
> 
> which version of milvus and pymilvus are you running

2.4.3 pymilvus

**Comment by yanliang567** [comment]
what about milvus version

**Comment by juanandreas** [comment]
> what about milvus version

2.4.1. Do I need to update to a later version?

**Comment by yanliang567** [comment]
please upgrade to milvus 2.4.4 which fixed a critical issue for bulk insert
