### ISSUE TITLE
[Bug]: Offset Param Not Working as Expected With Collection.search()

### ISSUE THREAD

**Issue by hakan458** [milvus-io/milvus#25587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.11
- Deployment mode(standalone or cluster): Cluster on GCP
- MQ type(rocksmq, pulsar or kafka): Kafka    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.2.11
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When performing a vector query using `collection.search()` , it seems the `offset` param has no affect on the results
However it seems that the `offset` param still works with `collection.query()` 

For example I am running this 
```
results = collection.search(
    data=[[0.5] * 512],
    anns_field='Image',
    param={'metric_type': 'L2', 'params': {'ef': 64}},
    limit=30,
    offset=0,
    output_fields=['id', 'sync_id', 'candidate_task_id', 'storage_id'],
)
```
Looking at the first result, I see an entity with `id: 1` 

If I run this, now using `offset=100` , I get the same results, first one is `id: 1` (all 30 are the same since Im using `limit=30`) 
```
results = collection.search(
    data=[[0.5] * 512],
    anns_field='Image',
    param={'metric_type': 'L2', 'params': {'ef': 64}},
    limit=30,
    offset=100,  <-----------------------
    output_fields=['id', 'sync_id', 'candidate_task_id', 'storage_id'],
)
```

No matter what `offset` value I use, I am getting the same results. I feel like this was working fine in the past, and as I stated before it still seems to work fine when using `collection.query()`

### Expected Behavior

When I provide an `offset` param, the search results should be offset by that number

### Steps To Reproduce

```markdown
Seems like any `collection.search()` with an `offset` param Im able to reproduce this
```

### Anything else?

Slack thread with Filip on this topic
https://milvusio.slack.com/archives/CMNHUC371/p1689280905558039

**Comment by xiaofan-luan** [comment]
@yanliang567 
can we reproduce and add test on this issue?

**Comment by XuanYang-cn** [comment]
``` python
results = collection.search(
    data=[[0.5] * 512],
    anns_field='Image',
    param={
        offset=100,  <----------------------- should be placed here
        'metric_type': 'L2',
        'params': {'ef': 64}},
    limit=30,
    output_fields=['id', 'sync_id', 'candidate_task_id', 'storage_id'],
)
```
@hakan458

**Comment by XuanYang-cn** [comment]
```python
results = collection.search(
    data=[[0.5] * 512],
    anns_field='Image',
    param={
        "offset": 100,  <----------------------- should be here
        'metric_type': 'L2',
        'params': {'ef': 64}},
    limit=30,
    output_fields=['id', 'sync_id', 'candidate_task_id', 'storage_id'],
)
```

**Comment by xiaofan-luan** [comment]
Thanks for the correction

**Comment by hakan458** [comment]
Interesting! The docs are not very clear on this it seems 
Under https://milvus.io/docs/search.md#Prepare-search-parameters , I see that `limit` and `offset` are listed under search params
But both `limit` and `offset` are also listed as parameters of the `search()` function, similar to `query()` 
https://milvus.io/docs/search.md#Conduct-a-vector-search

So in reality - `limit` is an arg to `search()` and `query()` functions 
and `offset` is still a param to `query()` , but for `search()` it needs to be under the `param` arg like your example above? 

One issue Im running into with this - when I perform the following search on a collection with a HNSW index, I am getting an error
```
results = collection.search(
    data=[[0.5] * 512],
    anns_field='Image',
    param={'metric_type': 'L2', 'params': {'ef': 64}, 'offset': 100},
    limit=10,
    output_fields=['id', 'sync_id', 'candidate_task_id', 'storage_id'],
)[0]

Param 'ef'(64) is not in range [110, 9223372036854775807]
```

It seems like this is a bug. I know `ef` is supposed to be in the range `[top_k, 32768]`
However why would `offset` affect this? Shouldnt it just be `limit`? 
If I want to use `offset` I always need to adjust my `ef` value accordingly?

**Comment by hakan458** [comment]
After talking with a colleague, I think the `ef` issue I mentioned is not a bug, and it does make sense to me now. 

Still just want confirmation on this though, then I will close!

```
So in reality - limit is an arg to search() and query() functions, not in search params
and offset is still a param to query() , but for search() it needs to be under the param arg like your example above?
```

**Comment by xiaofan-luan** [comment]
> Interesting! The docs are not very clear on this it seems Under https://milvus.io/docs/search.md#Prepare-search-parameters , I see that `limit` and `offset` are listed under search params But both `limit` and `offset` are also listed as parameters of the `search()` function, similar to `query()` https://milvus.io/docs/search.md#Conduct-a-vector-search
> 
> So in reality - `limit` is an arg to `search()` and `query()` functions and `offset` is still a param to `query()` , but for `search()` it needs to be under the `param` arg like your example above?
> 
> One issue Im running into with this - when I perform the following search on a collection with a HNSW index, I am getting an error
> 
> ```
> results = collection.search(
>     data=[[0.5] * 512],
>     anns_field='Image',
>     param={'metric_type': 'L2', 'params': {'ef': 64}, 'offset': 100},
>     limit=10,
>     output_fields=['id', 'sync_id', 'candidate_task_id', 'storage_id'],
> )[0]
> 
> Param 'ef'(64) is not in range [110, 9223372036854775807]
> ```
> 
> It seems like this is a bug. I know `ef` is supposed to be in the range `[top_k, 32768]` However why would `offset` affect this? Shouldnt it just be `limit`? If I want to use `offset` I always need to adjust my `ef` value accordingly?

Hi hakan,

To implement offset + limit, milvus actually search offset+limit results, so offset + limit is actually the topk you are using to do search. That's why offset + limit has to smaller than ef.

On the newer release of milvus, we already dynamically changed ef to offset+limit if user specified value smaller than offset + limit so usr won't be confused about it

**Comment by kirill-sidorchuk** [comment]
> ```python
> results = collection.search(
>     data=[[0.5] * 512],
>     anns_field='Image',
>     param={
>         "offset": 100,  <----------------------- should be here
>         'metric_type': 'L2',
>         'params': {'ef': 64}},
>     limit=30,
>     output_fields=['id', 'sync_id', 'candidate_task_id', 'storage_id'],
> )
> ```

The documentation says it wong then?
https://milvus.io/docs/hybridsearch.md

If it is wrong - please fix

**Comment by xiaofan-luan** [comment]
we are gonna to fix the document soon~ thanks

**Comment by yanliang567** [comment]
/assign @NicoYuan1986 
@NicoYuan1986 please help to double confirm where offset we should put in search requests, and update the case if needed.

/unassign @kirill-sidorchuk

**Comment by xiaofan-luan** [comment]
> Try the search on v2.2.11 Only `offset` in collection.search(..., param={ 'offset': } , ...) can work now.
> 
> ![image](https://user-images.githubusercontent.com/109071306/254793065-57a389a5-4a65-47a3-886f-e8efe655c890.png)

It seems that the document for search is messed up on both language
@NicoYuan1986 could you work with wenjia on a fix?

**Comment by NicoYuan1986** [comment]
> > Try the search on v2.2.11 Only `offset` in collection.search(..., param={ 'offset': } , ...) can work now.
> > ![image](https://user-images.githubusercontent.com/109071306/254793065-57a389a5-4a65-47a3-886f-e8efe655c890.png)
> 
> It seems that the document for search is messed up on both language @NicoYuan1986 could you work with wenjia on a fix?

Of course.  
One more update. I think it easy to mix up when using offset. So i contact with @XuanYang-cn, and discuss if we can support both 2 usages. And the preliminary conclusion is yes.

**Comment by XuanYang-cn** [comment]
@NicoYuan1986 Try pymilvus-2.2.15.dev4 and pymilvus-2.4.0.dev111 plz
/unassign

**Comment by NicoYuan1986** [comment]
Verify it work well on both master and 2.2 branch.
