### ISSUE TITLE
[DOC] Best practice document

### ISSUE THREAD

**Issue by JinHai-CN** [milvus-io/milvus#256]
## Report needed documentation

**Report needed documentation**
Milvus can provide a BEST PRACTICE document to help use Milvus in the best way.

**Describe the documentation you'd like**
There are several types of index, lots of parameters in Milvus. This document should tell us how to choose the indexes and how to set the parameters to get better performance.

**Comment by cydrain** [comment]
https://medium.com/@milvusio/how-to-choose-an-index-in-milvus-4f3d15259212
https://medium.com/@milvusio/best-practices-for-milvus-configuration-f38f1e922418
