### ISSUE TITLE
[Bug]: failed to build index

### ISSUE THREAD

**Issue by llllyq77** [milvus-io/milvus#25614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

datanode  4C8G x1
querynode 4C8G x2
indexnode 4C16G x2

### Milvus Log

[ERROR] [indexnode/task.go:340] ["failed to build index"] [error="[UnexpectedError] Error:GetObjectSize[errcode:404, exception:, errmessage:No response body.]"] [stack="github.com/milvus-io/milvus/internal/indexnode.(*indexBuildTask).BuildIndex\n\t/go/src/github.com/milvus-io/milvus/internal/indexnode/task.go:340\ngithub.com/milvus-io/milvus/internal/indexnode.(*TaskScheduler).processTask.func1\n\t/go/src/github.com/milvus-io/milvus/internal/indexnode/task_scheduler.go:207\ngithub.com/milvus-io/milvus/internal/indexnode.(*TaskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/indexnode/task_scheduler.go:220\ngithub.com/milvus-io/milvus/internal/indexnode.(*TaskScheduler).indexBuildLoop.func1\n\t/go/src/github.com/milvus-io/milvus/internal/indexnode/task_scheduler.go:253"]
root@milvus-up-m96b48767dd92e53e-indexnode-y-5bbd784bbd-f4xl2:/tmp/milvus/logs# date

**Comment by yanliang567** [comment]
@llllyq77 which milvus version are you running? Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @llllyq77 
/unassign

**Comment by xiaofan-luan** [comment]
seems to be an issue for aws SDK.

**Comment by xiaofan-luan** [comment]
@llllyq77 
did you try to setup  "export AWS_REGION=us-west-2" your aws region manually see if it can be solved?
