### ISSUE TITLE
[Bug]: Drop collection, datanode has memory pressure

### ISSUE THREAD

**Issue by xTerry** [milvus-io/milvus#25615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: V2.2.10
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): kafka
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.8
- OS(Ubuntu or CentOS): Centos
- CPU/Memory: 24C192GB
- GPU: 
- Others:
```

### Current Behavior

Milvus cluster version, with an estimated input of 30000000 vectors per day, with daily collection established and data retained for 7 days. When the number of collections exceeds 7 days or the total data volume exceeds 300 million, the earliest collection with the earliest date will be deleted in a rolling manner. After a few days of continuous deletion, the datanode has memory pressure and constantly restarts.

Want to understand how to optimize related parameters, improve deletion efficiency, and reduce memory usage

<img width="786" alt="c0f1439e462fe348b4398c558bec2be" src="https://github.com/milvus-io/milvus/assets/2304854/4abcd7d3-1e17-4cc8-8a5d-5a4052a1d691">
<img width="686" alt="e38e1fcbbeb8b6f5f2f2ddef92a2600" src="https://github.com/milvus-io/milvus/assets/2304854/593cdaf4-82fd-49fe-b7bf-e38b41550e32">
<img width="646" alt="e971fece16223055f7929f84384bbba" src="https://github.com/milvus-io/milvus/assets/2304854/236a70bc-fbc4-4e58-8670-52cf5dd18a88">
<img width="707" alt="93ccd0a2e857a012d12c7b8126edd0c" src="https://github.com/milvus-io/milvus/assets/2304854/c9fdd79e-6ade-4662-9dc7-a4c1ac1d20c3">

**Comment by xiaofan-luan** [comment]
/assign @xTerry 
Hi terry, could you generate a PProf of your datanode?


@yanliang567 anyway we can reproduce on our side on master?

**Comment by xTerry** [comment]
> /assign @xTerry Hi terry, could you generate a PProf of your datanode?
> 
> @yanliang567 anyway we can reproduce on our side on master?

@xiaofan-luan Sorry, in order to restore the business system, Milvus has been reinstalled and the data has been cleared

**Comment by jiaoew1991** [comment]
Create a partition every day, and write the data of that day into the corresponding partition. Simply drop partitions that are older than 7 days. This approach may be more suitable for your scenario. What do you think @xiaofan-luan ?

**Comment by xiaofan-luan** [comment]
> Create a partition every day, and write the data of that day into the corresponding partition. Simply drop partitions that are older than 7 days. This approach may be more suitable for your scenario. What do you think @xiaofan-luan ?

Or we can simply use TTL features?

**Comment by xTerry** [comment]
> Create a partition every day, and write the data of that day into the corresponding partition. Simply drop partitions that are older than 7 days. This approach may be more suitable for your scenario. What do you think @xiaofan-luan ?
Partition does not support deletion and does not support individual release. The collection must be released before deletion.
Xiaolong said that only V2.3 version supports deleting partitions @jiaoew1991

**Comment by xTerry** [comment]
![image](https://github.com/milvus-io/milvus/assets/2304854/19a76182-bd77-46f7-9aa0-1a28f795bd72)
upgrade to v2.2.12 memory persist，wait a moment ，datanode auto restart

**Comment by xiaofan-luan** [comment]
could you do pprof and check what is consuming the cpu?

**Comment by xiaofan-luan** [comment]
and could please offer logs about datanode and datacoord?
The cpu usage of datanode seems to be too high
