### ISSUE TITLE
[Enhancement]: Upsert API first queries whether the primary key exists and then decides whether to write the delete message

### ISSUE THREAD

**Issue by jiaoew1991** [milvus-io/milvus#25633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

The current implementation of upsert does not check whether the primary key exists. It directly sends delete and insert messages, which is a simple approach. However, this can result in excessive delete messages, causing compaction pressure and impacting search performance. Upsert is a strong requirement in many user scenarios, and it is likely that the usage of upsert will exceed that of insert. To ensure system stability, we need to optimize this behavior by first executing a `query by id` step to determine if the primary key exists. If it doesn't exist, we can skip the delete message and only send an insert message.

When designing this optimization, we need to consider the following factors:
- Impact on rate limiting logic
- Impact on query load

**Comment by jiaoew1991** [comment]
This optimization needs to be completed in version 2.3.1.

**Comment by xiaofan-luan** [comment]
need to make the collection is loaded

**Comment by xiaofan-luan** [comment]
keep it
