### ISSUE TITLE
[Enhancement]: Print Aws-sdk-cpp log to std::out

### ISSUE THREAD

**Issue by xige-16** [milvus-io/milvus#25651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Milvus can be configured to log to either standard output or a log file. However, currently Milvus has enabled logging for aws-sdk-cpp, but this log can only be outputted to a log file.

### Why is this needed?

 It is expected to also be able to output based on Milvus configuration to std::out.

**Comment by xiaofan-luan** [comment]
it should be configured by user~
