### ISSUE TITLE
[Bug]: There is an error in the documentation

### ISSUE THREAD

**Issue by groobyming** [milvus-io/milvus#25686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.11
- Deployment mode: standalone
- MQ type(rocksmq, pulsar or kafka):   
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.2.4
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I execute the following code in the document, I get the error "The file does not exist"

【DOCUMENT】：https://milvus.io/docs/search.md

【CODE】：
<img width="988" alt="image" src="https://github.com/milvus-io/milvus/assets/34335395/0b0f54b3-2a3f-4e07-95fa-65b615ec4a7e">

【ERROR】：
<img width="1155" alt="image" src="https://github.com/milvus-io/milvus/assets/34335395/1d8c5ae1-18c3-49df-9843-fc175bfbd5c0">

### Milvus Log

<img width="1155" alt="image" src="https://github.com/milvus-io/milvus/assets/34335395/2a9d9bf0-2085-43cc-9675-11bf5116da42">

**Comment by xiaofan-luan** [comment]
@groobyming 
in the example there is a field named "title"
I guess under your case there is no suche field in your collection

**Comment by yanliang567** [comment]
/assign @AnthonyTsu1984
please help to update the sample code
/unassign
