### ISSUE TITLE
Update oatpp 1.1.0

### ISSUE THREAD

**Issue by lganzzzo** [milvus-io/milvus#2568]
Hello @BossZou , guys,

The new oatpp version `1.1.0` has been released.
It introduces some breaking changes so please feel free to contact me in case you have any difficulties to migrate.

You can find the changelog [here](https://github.com/oatpp/oatpp/blob/master/changelog/1.1.0.md)

Best Regards,
Leonid

**Comment by yhmo** [comment]
@Iganzzzo
Thank you! We will have a try in necessary.
