### ISSUE TITLE
[Bug]: Compaction failed and there are many small segments

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#25681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20230710-4dd02836
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.2.13.dev3
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Test steps:
1. create collection with 1 shard, a int64 pk-auto field, a float vector field 128dim, strong consistency level
2. create index `{"index_type": "IVF_SQ8", "metric_type": "L2", "params": {"nlist": 64}}`
3. load 
4. loop insert-flush 1million 128d entities loop: insert 10 entities and flush once

the final segment stats:
![image](https://github.com/milvus-io/milvus/assets/27288593/f0f5667a-03f8-4a45-8bb8-7dbf0cbc078f)

```
Milvus(zong-test-cluster1) > show segment --collection 442783417150742678
SegmentID: 442794068871404655 State: Dropped, Row Count:697460
SegmentID: 442794068871404913 State: Dropped, Row Count:230
SegmentID: 442794068871405003 State: Dropped, Row Count:10
SegmentID: 442794068871405045 State: Flushing, Row Count:697700
SegmentID: 442794068872099535 State: Dropped, Row Count:10
SegmentID: 442794068872099627 State: Dropped, Row Count:157540
SegmentID: 442794068872099724 State: Dropped, Row Count:10
SegmentID: 442794068872099761 State: Flushing, Row Count:157560
SegmentID: 442794068872757155 State: Flushed, Row Count:10
SegmentID: 442794068872757186 State: Flushed, Row Count:10
SegmentID: 442794068872757321 State: Flushed, Row Count:10
SegmentID: 442794068872757511 State: Flushed, Row Count:10
SegmentID: 442794068872757543 State: Flushed, Row Count:10
SegmentID: 442794068872757570 State: Flushed, Row Count:10
SegmentID: 442794068872757618 State: Flushed, Row Count:10
SegmentID: 442794068872757652 State: Flushed, Row Count:10
SegmentID: 442794068872757775 State: Flushed, Row Count:10
SegmentID: 442794068872757842 State: Flushed, Row Count:10
SegmentID: 442794068872757919 State: Flushed, Row Count:10
SegmentID: 442794068872757997 State: Flushed, Row Count:10
SegmentID: 442794068872758025 State: Flushed, Row Count:10
SegmentID: 442794068872758047 State: Flushed, Row Count:10
SegmentID: 442794068872758112 State: Flushed, Row Count:10
SegmentID: 442794068872758142 State: Flushed, Row Count:10
SegmentID: 442794068872758278 State: Flushed, Row Count:10
SegmentID: 442794068872758305 State: Flushed, Row Count:10
SegmentID: 442794068872758334 State: Flushed, Row Count:10
SegmentID: 442794068872758457 State: Flushed, Row Count:10
SegmentID: 442794068872758488 State: Flushed, Row Count:10
SegmentID: 442794068872758525 State: Flushed, Row Count:10
SegmentID: 442794068872758580 State: Flushed, Row Count:10
SegmentID: 442794068872758610 State: Flushed, Row Count:10
SegmentID: 442794068872758734 State: Flushed, Row Count:10
SegmentID: 442794068872758843 State: Flushed, Row Count:10
SegmentID: 442794068872758901 State: Flushed, Row Count:10
SegmentID: 442794068872758932 State: Flushed, Row Count:10
SegmentID: 442794068872758958 State: Flushed, Row Count:10
SegmentID: 442794068872758967 State: Flushed, Row Count:144400
SegmentID: 442794068872759056 State: Flushed, Row Count:50
--- Growing: 0, Sealed: 0, Flushed: 33
--- Total Segments: 33, row count: 1000000
```

### Expected Behavior

compaction and merge the 10-count segments to more large segments

### Steps To Reproduce

```markdown
import pandas as pd

from pymilvus import connections
from base.collection_wrapper import ApiCollectionWrapper
from base.schema_wrapper import ApiCollectionSchemaWrapper
from utils.util_log import test_log as log
from common import common_func as cf
from common import common_type as ct


class TestInsertFlush:
    """ Test case of Insert interface """

    def test_insert_flush(self):
        """
        target: test insert DataFrame data
        method: 1.create collection
                2.insert dataframe data
        expected: assert num entities
        """
        nb = 1000000
        ni = 10
        dim = 128

        #  connect
        connections.connect(host=cf.param_info.param_host, port=cf.param_info.param_port)

        # create collection with 1 shard and auto id

        c_name = cf.gen_unique_str("insert_flush")
        fields = [cf.gen_int64_field(is_primary=True), cf.gen_float_vec_field(dim=dim)]
        schema, _ = ApiCollectionSchemaWrapper().init_collection_schema(fields=fields, description=ct.default_desc,
                                                                        primary_field=ct.default_int64_field_name,
                                                                        auto_id=True)
        collection_w = ApiCollectionWrapper()
        collection_w.init_collection(name=c_name, schema=schema, shards_num=1)

        # create index
        index_params = {"index_type": "IVF_SQ8", "metric_type": "L2", "params": {"nlist": 64}}
        collection_w.create_index(ct.default_float_vec_field_name, index_params, index_name=ct.default_index_name)

        # load
        collection_w.load()

        # insert for loop
        ni_count = nb // ni
        for i in range(ni_count):
            float_vec_values = cf.gen_vectors(ni, dim)
            df = pd.DataFrame({
                ct.default_float_vec_field_name: float_vec_values
            })
            mutation_res, _ = collection_w.insert(data=df)
            assert mutation_res.insert_count == ni
            # flush
            assert collection_w.num_entities == ni*(i+1)

        log.info(f'Insert collection {collection_w.name} success with entities {collection_w.num_entities}')
```
```


### Milvus Log

devops cluster argo workflow:  https://argo-qa-devops.zilliz.cc/archived-workflows/qa/fb19aef8-e694-41a7-bf82-a92183b3f8dd?nodeId=walmart-test-29h94
devops cluster server pods:
```
zong-test-cluster1-etcd-0                                      1/1     Running            0                5d23h   10.102.9.8      devops-node13   <none>           <none>
zong-test-cluster1-etcd-1                                      1/1     Running            1 (5d23h ago)    5d23h   10.102.5.231    devops-node21   <none>           <none>
zong-test-cluster1-etcd-2                                      1/1     Running            0                5d23h   10.102.6.62     devops-node10   <none>           <none>
zong-test-cluster1-milvus-datacoord-bf8dbc575-l9xr8            1/1     Running            0                5d23h   10.102.7.249    devops-node11   <none>           <none>
zong-test-cluster1-milvus-datanode-557c94d67b-586nh            1/1     Running            0                5d23h   10.102.9.30     devops-node13   <none>           <none>
zong-test-cluster1-milvus-indexcoord-799c77b5d5-2sng6          1/1     Running            0                5d23h   10.102.7.6      devops-node11   <none>           <none>
zong-test-cluster1-milvus-indexnode-7d4d874b-mmhfr             1/1     Running            0                5d23h   10.102.9.31     devops-node13   <none>           <none>
zong-test-cluster1-milvus-proxy-77bd789b4d-w9k4t               1/1     Running            0                5d23h   10.102.7.253    devops-node11   <none>           <none>
zong-test-cluster1-milvus-querycoord-5c84cddb7c-rmtrm          1/1     Running            0                5d23h   10.102.5.242    devops-node21   <none>           <none>
zong-test-cluster1-milvus-querynode-794789d788-t5p8v           1/1     Running            0                5d23h   10.102.9.42     devops-node13   <none>           <none>
zong-test-cluster1-milvus-rootcoord-78bcfc586d-v5tn4           1/1     Running            1 (5d11h ago)    5d23h   10.102.7.2      devops-node11   <none>           <none>
zong-test-cluster1-minio-0                                     1/1     Running            0                5d23h   10.102.5.229    devops-node21   <none>           <none>
zong-test-cluster1-minio-1                                     1/1     Running            0                5d23h   10.102.6.59     devops-node10   <none>           <none>
zong-test-cluster1-minio-2                                     1/1     Running            0                5d23h   10.102.9.9      devops-node13   <none>           <none>
zong-test-cluster1-minio-3                                     1/1     Running            0                5d23h   10.102.7.243    devops-node11   <none>           <none>
zong-test-cluster1-pulsar-bookie-0                             1/1     Running            0                5d23h   10.102.7.240    devops-node11   <none>           <none>
zong-test-cluster1-pulsar-bookie-1                             1/1     Running            0                5d23h   10.102.6.54     devops-node10   <none>           <none>
zong-test-cluster1-pulsar-bookie-2                             1/1     Running            0                5d23h   10.102.9.6      devops-node13   <none>           <none>
zong-test-cluster1-pulsar-bookie-init-gvxjg                    0/1     Completed          0                5d23h   10.102.5.225    devops-node21   <none>           <none>
zong-test-cluster1-pulsar-broker-0                             1/1     Running            0                5d23h   10.102.9.241    devops-node13   <none>           <none>
zong-test-cluster1-pulsar-broker-1                             1/1     Running            0                5d23h   10.102.7.232    devops-node11   <none>           <none>
zong-test-cluster1-pulsar-proxy-0                              1/1     Running            0                5d23h   10.102.7.231    devops-node11   <none>           <none>
zong-test-cluster1-pulsar-proxy-1                              1/1     Running            0                5d23h   10.102.5.227    devops-node21   <none>           <none>
zong-test-cluster1-pulsar-pulsar-init-jc5q5                    0/1     Completed          0                5d23h   10.102.5.226    devops-node21   <none>           <none>
zong-test-cluster1-pulsar-recovery-0                           1/1     Running            0                5d23h   10.102.7.230    devops-node11   <none>           <none>
zong-test-cluster1-pulsar-zookeeper-0                          1/1     Running            0                5d23h   10.102.7.241    devops-node11   <none>           <none>
zong-test-cluster1-pulsar-zookeeper-1                          1/1     Running            0                5d23h   10.102.6.92     devops-node10   <none>           <none>
zong-test-cluster1-pulsar-zookeeper-2                          1/1     Running            0                5d23h   10.102.9.22     devops-node13   <none>           <none>
```

### Anything else?

_No response_

**Comment by ThreadDao** [comment]
Please check out these metrics by the way. thank you
- datacoord: segment num
Why the flushing and dropped segments numbers are negative ?
![image](https://github.com/milvus-io/milvus/assets/27288593/084c4302-0d27-4fc9-9c46-ac3621473f32)

- indexcoord: Index Task Count
Why the inprogress task and unissued task count are always 0 ?
![image](https://github.com/milvus-io/milvus/assets/27288593/bd79f342-fa96-4229-8d4a-716dee47c063)

- querynode: loaded segments
 There is only 1 collection and 1 shard, is the growing segments metric right ? or does it include the flushed but not-indexing segments?
![image](https://github.com/milvus-io/milvus/assets/27288593/e2d4465f-0fd1-4ef3-a2f8-86d1b2da336b)

**Comment by xiaofan-luan** [comment]
This is a interesting test and could be fixed by modify the compaction policy.

Try to merge as many as the small segments could somewhat solve the problem

**Comment by xiaofan-luan** [comment]
Current the compaction always try to pick one large segment and merge with small segments.
But we might want to compact many segments with similar sizes in order to avoid duplicated compactions

**Comment by xiaofan-luan** [comment]
if the segment row numbers is

300, 100, 100, 100, 100
and the limit is 500,
we'd better compact 4* 100 segment together rather than compact twice with 300+100 and 100+100+100

**Comment by XuanYang-cn** [comment]
This is a typical index - load - insert - flush tests.

DC has been generating compaction plans for these small segments all the time, but DN executing all of them failed for "cannot found segment 442794068872099761".

Looks like its another sync-segments error causing this problem.

**Comment by XuanYang-cn** [comment]
```
2023-07-15 11:56:10	
[2023/07/15 03:56:10.876 +00:00] [ERROR] [datanode/data_node.go:953] ["Cannot block flowGraph for sync segments, release generated segment meta and stats log"] [traceID=724d3cd3157717eb] [planID=442794068872099760] ["target segmentID"=442794068872099761] [stack="github.com/milvus-io/milvus/internal/datanode.(*DataNode).SyncSegments\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/data_node.go:953\ngithub.com/milvus-io/milvus/internal/distributed/datanode.(*Server).SyncSegments\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datanode/service.go:396\ngithub.com/milvus-io/milvus/internal/proto/datapb._DataNode_SyncSegments_Handler.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:7394\ngithub.com/milvus-io/milvus/internal/util/interceptor.ClusterValidationUnaryServerInterceptor.func1\n\t/go/src/github.com/milvus-io/milvus/internal/util/interceptor/cluster_interceptor.go:69\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/milvus-io/milvus/internal/util/logutil.UnaryTraceLoggerInterceptor\n\t/go/src/github.com/milvus-io/milvus/internal/util/logutil/grpc_interceptor.go:22\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34\ngithub.com/milvus-io/milvus/internal/proto/datapb._DataNode_SyncSegments_Handler\n\t/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:7396\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1295\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1636\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:932"]Show context
2023-07-15 11:56:01	
[2023/07/15 03:56:01.461 +00:00] [INFO] [datanode/channel_meta.go:440] ["Successfully load pk stats"] [segmentID=442794068872099761] [time=585.154132ms] [size=1737533]
2023-07-15 11:56:00	
[2023/07/15 03:56:00.876 +00:00] [INFO] [datanode/channel_meta.go:379] ["begin to init pk bloom filter"] [segmentID=442794068872099761] [statsBinLogsLen=1]
2023-07-15 11:56:00	
[2023/07/15 03:56:00.876 +00:00] [INFO] [datanode/data_node.go:888] ["DataNode receives SyncSegments"] [traceID=724d3cd3157717eb] [planID=442794068872099760] ["target segmentID"=442794068872099761] ["compacted from"="[442794068872099627,442794068872099724,442794068872099535]"] [numOfRows=157560]
```

**Comment by XuanYang-cn** [comment]
SyncSegments failed for segment 442794068872099761 because tryLock failed.
This error should be fixed by this PR https://github.com/milvus-io/milvus/pull/25703
/assign @ThreadDao 
Please help verify!

**Comment by XuanYang-cn** [comment]
![image](https://github.com/milvus-io/milvus/assets/51370125/4f276e53-f7af-482c-85c1-b86e7a492b79)
DN restarted and everything recovered just fine.

**Comment by ThreadDao** [comment]
@yanliang567 
Test again. Insert 1000 entities and flush. The final segment num is 1. So compact successfully

![image](https://github.com/milvus-io/milvus/assets/27288593/9946aa7b-b52b-40c5-8160-beb0f0a7456b)

![image](https://github.com/milvus-io/milvus/assets/27288593/b18eb5c1-53ef-48c9-bb52-b3265665b216)

**Comment by yanliang567** [comment]
great to hear that. close the issue again
