### ISSUE TITLE
[Bug]: when I tried to run docker compose up -d command, it reported me an issue as below:network milvus was found but has incorrect label com.docker.compose.network set to "milvus"

### ISSUE THREAD

**Issue by dongb83** [milvus-io/milvus#25684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

<img width="709" alt="image" src="https://github.com/milvus-io/milvus/assets/38278410/1dea7c8e-9c76-4dda-a8fd-96f781c9cd2e">

### Anything else?

<img width="709" alt="image" src="https://github.com/milvus-io/milvus/assets/38278410/f2c63762-57c1-431b-a35d-5727fa8c0f18">

**Comment by yanliang567** [comment]
@dongb83 which version are you running, could you attache the docker compose yaml for reference?
/assign @dongb83

**Comment by dongb83** [comment]
> @dongb83 which version are you running, could you attache the docker compose yaml for reference? /assign @dongb83

version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.11
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvus

**Comment by yanliang567** [comment]
@locustbaby could you please help on this problem?

/assign @locustbaby 
/unassign

**Comment by gree2** [comment]
docker network ls

**Comment by gree2** [comment]
use `docker network ls` list all networks, then you will find one named `milvus`, use `docker network rm milvus` delete milvus network. run `docker compose up` again will work.

**Comment by yiwangdr** [comment]
https://github.com/docker/compose/issues/10797
This issue is associated with new versions of docker compose. 

@yanliang567 @locustbaby, the `docker network rm milvus` + `docker compose up` solution could be a temp fix. It's probably better for us to add this temp fix to our documentation until docker fixes it.

**Comment by pingliu** [comment]
upgrade to the latest version  would fix the issue, please refer to https://docs.docker.com/compose/install/
