### ISSUE TITLE
[Bug]: Fail to start Milvus -standalone docker(master)

### ISSUE THREAD

**Issue by leonllzhang** [milvus-io/milvus#25696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
3.5
- Deployment mode(standalone or cluster):
standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
macos 13.2.1 (22D68)
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

here are docker-compose.yml
version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2020-12-03T00-03-10Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.0.2
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvus

after execute :"sudo docker-compose up -d" 
the standalone container can not start.  the logs as below:
[2023/07/18 03:40:57.695 +00:00] [DEBUG] [rocksmq_impl.go:157] ["Start rocksmq "] ["max proc"=8] [parallism=1]
2023-07-18 11:40:57 panic: Corruption: Unsupported compression method or corrupted compressed block contents: ZSTD
2023-07-18 11:40:57 
2023-07-18 11:40:57 goroutine 1 [running]:
2023-07-18 11:40:57 github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run(0xc000623ee0, 0x1, 0x0, 0x0)
2023-07-18 11:40:57     /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:356 +0x110e
2023-07-18 11:40:57 main.main()
2023-07-18 11:40:57     /go/src/github.com/milvus-io/milvus/cmd/main.go:296 +0x692

**Comment by yanliang567** [comment]
please try the latest release v2.2.11 as description here: https://milvus.io/docs/install_standalone-docker.md

/assign @leonllzhang 
/unassign

**Comment by leonllzhang** [comment]
@yanliang567  thanks alot.   try version 2.2.11.  but found out the milvus-minio  fail to start. and will automatically exit.
the log indicate "invalid arguments..."   it is very appreciate if you could help. 

2023-07-18 12:06:09 WARNING: MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated.
2023-07-18 12:06:09          Please use MINIO_ROOT_USER and MINIO_ROOT_PASSWORD
2023-07-18 12:06:09 ERROR Unable to use the drive /minio_data: Drive /minio_data: found backend type fs, expected xl or xl-single - to migrate to a supported backend visit https://min.io/docs/minio/linux/operations/install-deploy-manage/migrate-fs-gateway.html: Invalid arguments specified

**Comment by yanliang567** [comment]
sounds like a minio issue.
/assign @locustbaby 
any ideas?
/unassign

**Comment by locustbaby** [comment]
hi @leonllzhang , sorry for the late, where are you running this docker-compose,
![image](https://github.com/milvus-io/milvus/assets/21237232/9899c271-f068-4988-a9b1-f6e1b35af7c1)
From my side, all works ok with the newest version.

**Comment by leonllzhang** [comment]
Hi, @locustbaby , i am running this on macIntel Core i9,   docker desktop. Only the Minio will automatically exit. 
![image](https://github.com/milvus-io/milvus/assets/8869480/59fc799d-67ff-4dc8-b206-32715d80e55b)
check the detail will find out: 
![image](https://github.com/milvus-io/milvus/assets/8869480/8e7cc13c-8a31-4ed9-a550-d4e9a42976a3)

**Comment by leonllzhang** [comment]
I will try the latest version for safe. :)

**Comment by lijiajun3029** [comment]
> I will try the latest version for safe. :)
I encountered the same problem on the newest version,have you solved it?

**Comment by lijiajun3029** [comment]
> I will try the latest version for safe. :)

I encountered the same problem on the newest version, have you solved it?

**Comment by lijiajun3029** [comment]
> > I will try the latest version for safe. :)
> 
> I encountered the same problem on the newest version, have you solved it?
The answer is here.
https://github.com/milvus-io/milvus/issues/25523#issuecomment-1632214565

**Comment by Hansimov** [comment]
Same issue here. The cause is that the data formats are incompatible between version switching.

Solved by removing the `volumes` directory and rerun.

**Comment by Hansimov** [comment]
Same issue here. The cause is that the data formats are incompatible between version switching.

Solved by removing the `volumes` directory and rerun.
