### ISSUE TITLE
[Bug]: 请问s3里的文件误删了怎么恢复

### ISSUE THREAD

**Issue by llllyq77** [milvus-io/milvus#25690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

s3里的文件误删了怎么恢复

**Comment by jiaoew1991** [comment]
If you are using a public cloud service, it is recommended to contact the support of the cloud provider. If it is a self-built S3, it is recommended to contact your operations team.

**Comment by jiaoew1991** [comment]
Milvus provides a backup tool and it is recommended to regularly back up data during daily maintenance. https://github.com/zilliztech/milvus-backup
