### ISSUE TITLE
Insert performance decreased

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#2569]
**Describe the bug**
![Screenshot_2020-06-16 insert_perf](https://user-images.githubusercontent.com/56623710/84721986-9101a680-afb4-11ea-999a-0bb81f3f5775.png)

**Steps/Code to reproduce behavior**

**Expected behavior**

**Environment details**
master

**Screenshots**

**Additional context**

**Comment by tinkerlin** [comment]
I've got some statistics about the overhead of insert operation during server and sdk side.
Each Insert(about 10 thousand vector) cost average 0.01s on the server side, but after pass back from SDK increase to 0.55s. In the days before, it only cost 0.12s. The overhead is inacceptable.

**Comment by del-zhenwu** [comment]
no-reproduced
