### ISSUE TITLE
cannot find -lz when compiling c++ sdk from source

### ISSUE THREAD

**Issue by WangJianRepo** [milvus-io/milvus#2570]
**Describe the bug**
cannot find -lz when compiling c++ sdk.

**Steps/Code to reproduce behavior**
The build.sh script shows cannot find -lz when I use it to build c++ sdk.

**Expected behavior**
No error shown.

**Environment details**
- Ubuntu 18.04 in a clean container, gcc 7.5.0 , cmake-3.18.0
- Method of installation: source
- sdk dir in Milvus version (v0.10.0)

**Screenshots**
![image](https://user-images.githubusercontent.com/15922226/84722321-767bfd00-afb5-11ea-9bac-c67e028f9e21.png)

**Additional context**
Problem is solved using apt-get install zlib1g-dev.

**Comment by tinkerlin** [comment]
Before compile milvus project, make sure run the ubuntu_build_deps.sh under the /milvus/core folder, to install tools required by milvus.

**Comment by WangJianRepo** [comment]
Sorry I did not make it clearly. I mean when I compile client sdk for c++ in [https://github.com/milvus-io/milvus/tree/master/sdk](url). not the whole milvus project.

**Comment by tinkerlin** [comment]
https://stackoverflow.com/questions/3373995/usr-bin-ld-cannot-find-lz

**Comment by yhmo** [comment]
Thank you!
We can add this into README of sdk.
