### ISSUE TITLE
[Bug]: module 'pymilvus.orm.utility' has no attribute 'calc_distance'

### ISSUE THREAD

**Issue by groobyming** [milvus-io/milvus#25704]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.11
- Deployment mode: standalone
- MQ type(rocksmq, pulsar or kafka):   
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.2.4
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I execute the following code as documented, I get the error "AttributeError: module 'pymilvus.orm.utility' has no attribute 'calc_distance'"

document ： https://milvus.io/docs/calculate_distance.md
code：
<img width="925" alt="image" src="https://github.com/milvus-io/milvus/assets/34335395/32f38ab4-2b1b-42a0-a3ca-73f70a0e5658">

<img width="853" alt="image" src="https://github.com/milvus-io/milvus/assets/34335395/de9b1dd7-de00-4a52-8fce-4f5dab91f6ee">

**Comment by yanliang567** [comment]
@groobyming  calc_distance() is deprecated from the latest release.

/assign @groobyming 
/unassign

**Comment by groobyming** [comment]
@groobyming Thanks, so how can I calculate the distance between two vector

**Comment by groobyming** [comment]
@yanliang567  Since calc_distance() is deprecated, please update the doc
