### ISSUE TITLE
[Bug]: milvus becomes much slower if inserting 1000 vectors 

### ISSUE THREAD

**Issue by fuchunming11** [milvus-io/milvus#25719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.2
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

批量插入1000条需要10分钟。

### Expected Behavior

批量插入100条之前只需要几秒钟

### Milvus Log

[log_file.log](https://github.com/milvus-io/milvus/files/12079184/log_file.log)

**Comment by yanliang567** [comment]
@fuchunming11 could you please retry with latest release v2.2.11?

**Comment by xiaofan-luan** [comment]
seems that the dml channel watch failure.
upgrade to latest release may solve this problem automatically
