### ISSUE TITLE
[Bug]: Search Iterator can only turn one page when collection num_entities >= 100k

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#25722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230717-5afea0e5 
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0.dev101
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search Iterator can only turn one page when collection num_entities >= 100k.
collection.num_entities: 100k

1. limit=100:
![image](https://github.com/milvus-io/milvus/assets/109071306/b93aa8b4-a419-490a-b9fc-ae1bfdb011c2)

2. limit=1000:
![image](https://github.com/milvus-io/milvus/assets/109071306/556aceb8-f29e-45bf-863e-eac24bc2fcdc)

3. limit=10000:
![image](https://github.com/milvus-io/milvus/assets/109071306/62748f97-c65b-4e7a-9a44-a9640e2df69d)

It works well when collection.num_entities==10k, but the same situation when collection.num_entities==1m.

### Expected Behavior

pass

### Steps To Reproduce

```markdown
from pymilvus import CollectionSchema, FieldSchema, Collection, connections, DataType, Partition, utility
import numpy as np
import random
connections.connect()

# create collection
dim = 128
fields = [
    FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True),
    FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
]
schema = CollectionSchema(fields=fields)
collection = Collection("test_001", schema=schema)

# insert data
nb = 100000
step = 10000
for i in range(0, nb, step):
    vectors = [[random.random() for _ in range(dim)] for _ in range(step)]
    data = [[j for j in range(i, i+step)], vectors]
    print(f"insert data {i} - {i + step}")
    collection.insert(data)

collection.create_index("float_vector", {"metric_type": "COSINE"})
collection.load()

limit = 10000
search_params = {"metric_type": "COSINE"}
vectors = [[random.random() for _ in range(dim)] for _ in range(2)]
search_iterator = collection.search_iterator(vectors[:1], "float_vector", search_params, limit)

page_idx = 0
while True:
    res = search_iterator.next()  # 翻下一页
    if len(res[0]) == 0:
        print("search iteration finished, close")
        search_iterator.close()  # close
        break
    for i in range(len(res[0])):
        # print(res[0][i])
    page_idx += 1
    print(f"page{page_idx}-------------------------{len(res[0])}")
```

**Comment by yanliang567** [comment]
set it as critical urgent, as this is a 2.3 feature

**Comment by xiaofan-luan** [comment]
@NicoYuan1986 
What is the error for large collections?

“Search Iterator can only turn one page when collection num_entities ” what happens when I do next?

**Comment by xiaofan-luan** [comment]
For the iterator features, we probably need to test on a 1B data size and iterate all the data out

**Comment by NicoYuan1986** [comment]
No error message. It's just lack data.

**Comment by MrPresent-Han** [comment]
firstly, the test code above didn't flush data before build+load index, so before the segment was sealed and indexed, the iterator will search growing segments on query node, in which radius and range_filter doesn't work, resulting iteration cannot stop.

**Comment by MrPresent-Han** [comment]
secondly, after flushed and indexed, I use radius=-2.0 and range_filter=0.75 as the params, and milvus will not return the second page. But if I set radius to -0.74 and range_filter=0.75, 10000 entities will be returned. It seems that some the range has sth to do with result

**Comment by xiaofan-luan** [comment]
> firstly, the test code above didn't flush data before build+load index, so before the segment was sealed and indexed, the iterator will search growing segments on query node, in which radius and range_filter doesn't work, resulting iteration cannot stop.

1. Growing Segment should also support range search1
2. we need to figure out why this is happeening

**Comment by xiaofan-luan** [comment]
> 

@NicoYuan1986 what is the data distribution of your range_filter?

1. Why is the redius can be a negative value?
2. What's the relationship between radius and filter?

**Comment by NicoYuan1986** [comment]
> > 
> 
> @NicoYuan1986 what is the data distribution of your range_filter?
> 
> 1. Why is the redius can be a negative value?
> 2. What's the relationship between radius and filter?

1. Radius can be positive or negative data. They are all valid. The main different is that when we set a negative radius(L2), no search result will be returned.
2. For metrics 'IP' and 'COSINE', radius<distance<=range_filter. For metrics 'L2', range_filter<=distance<radius

I did not set radius and range_filter as the code shows above. 
So it should use the default radius and range_filter. And i think in this case, all results should be returned without giving a range.  @MrPresent-Han  Could you tell us the default value of radius and range_filter at present?

**Comment by cydrain** [comment]
There is a bug in knowhere HNSW range search, please re-test this case when following PR merged:
https://github.com/milvus-io/knowhere/pull/1000

**Comment by cydrain** [comment]
> There is a bug in knowhere HNSW range search, please re-test this case when following PR merged:
> [milvus-io/knowhere#1000](https://github.com/milvus-io/knowhere/pull/1000)

There is a bug in knowhere HNSW range search, please re-test this case when following PR merged:
https://github.com/milvus-io/knowhere/pull/1000

**Comment by cydrain** [comment]
> secondly, after flushed and indexed, I use radius=-2.0 and range_filter=0.75 as the params, and milvus will not return the second page. But if I set radius to -0.74 and range_filter=0.75, 10000 entities will be returned. It seems that some the range has sth to do with result

There is a bug in knowhere HNSW range search, please re-test this case when following PR merged:
https://github.com/milvus-io/knowhere/pull/1000

**Comment by liliu-z** [comment]
> firstly, the test code above didn't flush data before build+load index, so before the segment was sealed and indexed, the iterator will search growing segments on query node, in which radius and range_filter doesn't work, resulting iteration cannot stop.

/assign @foxspy

**Comment by cydrain** [comment]
Hi @NicoYuan1986 , please retest this issue

**Comment by MrPresent-Han** [comment]
I suspect there is still another problem regarding this issue: running the provided code above, and it turns out that when searching growing segments, the result returned are not intact. There will be only 2 pages available. I analyze the log and find out only 40000 rows were correctly indexed and searched, whereas the left 60000 rows are excluded from search scope until the whole segment was flushed and sealIndexed was built. I'm sure it's sth to do with growing index, because when turning enable.growingIndex off, the brute force result will be returned and all rows are available.

**Comment by MrPresent-Han** [comment]
according to the log, all entities have been added into the knowhere indexNode, and I didn't some status error inside segcore.  I'm curious whether the following 60000 entities are visible for the following search.
Please help us @foxspy  

W20230727 10:40:07.554569 9021848 FieldIndexing.cpp:145] [SEGCORE][AppendSegmentIndex][] reserved_offset:0, size:40000
W20230727 10:40:09.540062 9025769 FieldIndexing.cpp:145] [SEGCORE][AppendSegmentIndex][] reserved_offset:40000, size:10000
W20230727 10:40:10.135407 9023839 FieldIndexing.cpp:145] [SEGCORE][AppendSegmentIndex][] reserved_offset:50000, size:10000
W20230727 10:40:10.703794 9025765 FieldIndexing.cpp:145] [SEGCORE][AppendSegmentIndex][] reserved_offset:60000, size:10000
W20230727 10:40:11.266882 9025762 FieldIndexing.cpp:145] [SEGCORE][AppendSegmentIndex][] reserved_offset:70000, size:10000
W20230727 10:40:11.826189 9025764 FieldIndexing.cpp:145] [SEGCORE][AppendSegmentIndex][] reserved_offset:80000, size:10000
W20230727 10:40:12.394834 9025766 FieldIndexing.cpp:145] [SEGCORE][AppendSegmentIndex][] reserved_offset:90000, size:10000

**Comment by MrPresent-Han** [comment]
according to @foxspy, this partly data invisible is planned and will be enhanced in the following versions, so this issue has no more problems. Please help verify the result and close this issue if possible. @NicoYuan1986

**Comment by NicoYuan1986** [comment]
verify:
Before flush, only 176k results can be returned.
After flush, 1m results can be all returned.
![image](https://github.com/milvus-io/milvus/assets/109071306/41b45c40-ea8b-4efe-9895-fff75c19a3da)
