### ISSUE TITLE
[Bug]: Not able to change Default milvus Database in Attu V 2.2.7

### ISSUE THREAD

**Issue by siva22101991** [milvus-io/milvus#25720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus
- OS(Ubuntu or CentOS):  Ubuntu 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Attu always connects to default Database

### Expected Behavior

There should be a toggle between databases in Attu

**Comment by shanghaikid** [comment]
Yes，attu doesn't support select non-default db yet. It will be fixed in the next release.

**Comment by shanghaikid** [comment]
https://github.com/zilliztech/attu/releases/tag/v2.2.8 
v2.2.8 is released,  you can manage database now.
