### ISSUE TITLE
[Bug]: rootCoord.importTaskExpiration param not valid

### ISSUE THREAD

**Issue by yelusion2** [milvus-io/milvus#25727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.11.hotfix
- Deployment mode(standalone or cluster):2.2.11.hotfix
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When i import 23GB numpy file, and change to rootCoord.importTaskExpiration for 900s to 21600s, and the import task still cancle after 15min an the import failed.

### Expected Behavior

When i import 23GB numpy file, and change to rootCoord.importTaskExpiration for 900s to 21600s, and the import task will cancled after 21600s an the import failed.

### Steps To Reproduce

```markdown
1.perpare 23GB numpy file
2.upload the numpy file to the milvus storage 
3.import file
4.get import state
```

**Comment by yhmo** [comment]
The timeout configuration has been added by the #25785. I have verified the configuration can work.

**Comment by yanliang567** [comment]
@yelusion2 any chance to verify it?
