### ISSUE TITLE
[Bug]: Starting multiple nodes within one container, but unable to retrieve the logs

### ISSUE THREAD

**Issue by hao-cyber** [milvus-io/milvus#25732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Starting multiple nodes within one container, but unable to retrieve the logs

I start the proxy and root cord in one container, and only receive proxy logs
index cord, data cord, query cord in one container, and only receive data corrd logs

starting order is following:
1. proxy
2. root cord
3. data cord
4. query cord
5. index cord

**Comment by hao-cyber** [comment]
Log configuration is shown below
![1689735429100](https://github.com/milvus-io/milvus/assets/89575785/94a5f818-e61b-4eec-93d6-98a239406634)

**Comment by yanliang567** [comment]
@hao-cyber try standalone, which start milvus in one container/

/assign @hao-cyber 
/unassign

**Comment by hao-cyber** [comment]
In my situation, how can I retrieve the log？I want to maintain the elasticity of service..

**Comment by hao-cyber** [comment]
please help, We want to promote Milvus on a large scale, but we are facing the issue of log

**Comment by xiaofan-luan** [comment]
> please help, We want to promote Milvus on a large scale, but we are facing the issue of log

You can either deploy one role in one pod, 
or you can deploy mixcoord.
But we never tried to deploy muliple process in one pod
