### ISSUE TITLE
[Bug]: Hybrid Search with advanced filter logic

### ISSUE THREAD

**Issue by weihaopeng** [milvus-io/milvus#25754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.8
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    no
- SDK version(e.g. pymilvus v2.0.0rc2): attu v2.2.5, pymilvus v2.2.6
- OS(Ubuntu or CentOS): Centos
- CPU/Memory: 2.60GHz
- GPU: no
- Others:
```

### Current Behavior

When I use vector search in Attu( also try pymilvus's search and query function, the result is the same, for screenshots to view, I'll use attu search.):
1. If I search vector with advanced filter, I may have `No result`.
2. If I delete advanced filter, I'll get topK's results.
3. If I do data query with the same advanced filter, I can get the datas.

I think this is because hybrid search is to find the topK most similar documents first, and then filter the results through advanced filter. Is that right? But I think it should be find topK most similar documents in the results filted through advanced filter. Or are there any optional configuration items here?

## vector search without advanced filter:

![2023-07-19 16-38-25 的屏幕截图](https://github.com/milvus-io/milvus/assets/33681454/75ebe625-3087-4596-a23b-caaabe459028)

## add advanced filter:

![image](https://github.com/milvus-io/milvus/assets/33681454/033c46dd-1c1d-451c-bddc-716d259bc905)

## vector search with advanced filter, no result: 

![image](https://github.com/milvus-io/milvus/assets/33681454/3dc313b9-e094-4e7a-9c85-173b33f8c1e1)

## advanced filter, single search, have result:

![image](https://github.com/milvus-io/milvus/assets/33681454/3f40f097-b9a1-4646-a385-ff9820e9e806)

**Comment by yanliang567** [comment]
@weihaopeng thank you for the feedback. Actually Milvus do filter the expr first, and then do ann search to get the topk of the similar vectors. So I'd suggest you retry on the latest release v2.2.11 and if it still reproduced to you:
please share the code to reproduce this issue?  Also please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @weihaopeng

**Comment by weihaopeng** [comment]
I'll try now and give more feedback. I thought it should be filter expr first, then search to find topk. But the result is not. T_T

**Comment by weihaopeng** [comment]
[logs.tar.gz](https://github.com/milvus-io/milvus/files/12101322/logs.tar.gz)

**Comment by weihaopeng** [comment]
@yanliang567 I'm trying to get all data, about 9000. get error: `"grpc: trying to send message larger than max (69316834 vs. 67108864)"`

Can this be the reason?

**Comment by yanliang567** [comment]
> @yanliang567 I'm trying to get all data, about 9000. get error: `"grpc: trying to send message larger than max (69316834 vs. 67108864)"`
> 
> Can this be the reason?

it returns an error if the request message is larger than the max.

**Comment by xiaofan-luan** [comment]
Which means your filtering condition is too long > 64M
