### ISSUE TITLE
how to restore data 

### ISSUE THREAD

**Issue by cbqin** [milvus-io/milvus#2575]
hi, how to restore data/index in a new machine from milvus which is in another machine?

**Comment by yhmo** [comment]
Which milvus version?
For 0.9.1, to reusing data in a new machine, the steps:
1. copy milvus data folder to the new machine, data folder is defined in the server_config.yaml
```
storage_config:
  primary_path: /aaa/bbb
```
For example, in the machine A, the data path is defined as "/aaa/bbb", copy the whole folder to machine B, we say "/ccc/ddd"

2. start milvus
- if you are using SQLite as meta server, just download milvus docker image in machine B, and start a milvus container with a server_config.yaml which primary_path is "/ccc/ddd"

- if you are using MySQL as meta server, make sure the server_config.yaml is using same MySQL server
```
db_config:
  backend_url: mysql://xxx:xxxxxx@192.168.1.xx:3306/milvus
```

**Comment by cbqin** [comment]
thanks
