### ISSUE TITLE
[Bug]: I encountered a problem. I created a new collection and inserted a piece of data. After immediately searching in this collection, I found that no content was found. I set opt:=client. WithSearchQueryConsistencyLevel (entity. ClStrong), but still couldn't find it. What should I do

### ISSUE THREAD

**Issue by hotwinters** [milvus-io/milvus#25753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:docker 2.2.10
- Deployment mode(standalone or cluster):standalone 
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):go new
- OS(Ubuntu or CentOS): Ubuntu 
- CPU/Memory: -
- GPU: -
- Others: -
```

### Current Behavior

as same titile，and search opt := client.WithSearchQueryConsistencyLevel(entity.ClStrong)，shardNum=4，idxHNSW, err = entity.NewIndexHNSW(entity.IP, 16, 256)

**Comment by hotwinters** [comment]
and I have another question to ask. My devices perform 10000 data insertions in approximately 1 second. How should I choose a server and what is the server configuration? Thank you for your help

**Comment by hotwinters** [comment]
imageFeature = append(imageFeature, imageFeatureT)
	imageId = append(imageId, ImageId)
	faceId = append(faceId, FaceId)
	norm = append(norm, Norm)
	blur = append(blur, Blur)
	angle = append(angle, Angle)
	archivistId = append(archivistId, ArchivistId)
	gender = append(gender, Gender)
	dataTime = append(dataTime, time.Now().Format(time.DateTime))

	idImage := entity.NewColumnVarChar("image_Id", imageId)
	timeData := entity.NewColumnVarChar("data_Time", dataTime)
	normData := entity.NewColumnDouble("norm", norm)
	blurData := entity.NewColumnDouble("blur", blur)
	angleData := entity.NewColumnDouble("angle", angle)
	idFace := entity.NewColumnVarChar("face_Id", faceId)
	idArchivist := entity.NewColumnVarChar("archivist_Id", archivistId)
	genderData := entity.NewColumnInt32("gender", gender)
	featureImage := entity.NewColumnFloatVector("image_Feature", 512, imageFeature)
	// use or create patition
	partitionName := ""
	if PartitionId != "" {
		partitionName = PartitionId
	}
	ptName, err := m.MilvusGetPartition(RepositoryId, partitionName)
	_, err = m.milvusClient.Insert(
		context.Background(), // ctx
		RepositoryId,         // CollectionName
		ptName,               // partitionName
		idImage,              // columnarData
		normData,             // columnarData
		blurData,             // columnarData
		angleData,            // columnarData
		featureImage,         // columnarData
		idFace,               // columnarData
		idArchivist,          // columnarData
		timeData,             // columnarData
		genderData,           // columnarData
	)

**Comment by hotwinters** [comment]
@yanliang567 Do you need anything else

**Comment by yanliang567** [comment]
/assign @ThreadDao 
could you please help to reproduce it on milvus 2.2.13?
