### ISSUE TITLE
[Bug]: Why can't i connect to standalone milvus server on windows but attu can

### ISSUE THREAD

**Issue by trezae4475** [milvus-io/milvus#25760]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2/2.3
- Deployment mode(standalone or cluster):standalone 
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 
- OS(Ubuntu or CentOS): Windows 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I was using milvus light for testing and it worked prefectly.
I wanted to try milvus standalone so i tried the compiled exe first which didnt work but whatever, after that i followed line by line the docs installation for milvus standalone with docker compose, the containers are running (i can see them on the desktop app), they are accesible via attu on 127.0.0.1:19530 but whatever i try with python i can't connect to the server (i tried localhost, 127.0.0.1, the container ip, and some more)... It always end up with :
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on 127.0.0.1:19530. Timeout)>

I tried to disable my firewall alltogether to see if it was part of the issue but nothing changed. Also the fact that Attu desktop app can access it shows that i should be able to do the same in python without changing anything in my firewall...

### Expected Behavior

i should be able to connect to the server

### Steps To Reproduce

```markdown
1.Install docker on windows
2.Follow the doc for milvus standalone server installation 2.2.x
3.Try to connect to it via the python interpreter, anaconda, cmd + python
4.Enjoy the timeout
```

**Comment by yanliang567** [comment]
@trezae4475 quick questions:
1. how do you access attu service?
2. could you please telnet the port 19530

/assign @trezae4475

**Comment by trezae4475** [comment]
@yanliang567 1- i access attu via the desktop application found here : https://github.com/zilliztech/attu/releases/ (
attu-Setup-2.2.7.exe )
it allow me to connect to the server and if i stop the docker it fail to connect so i'm sure it's really connectiong to the container.

2- if i telnet to 127.0.0.1 19530 i get "♠♦@"

**Comment by trezae4475** [comment]
Update, i can connect to milvus standalone via milvus-cli which is python based i think so it's even weirder

**Comment by trezae4475** [comment]
Ok i solved it after hours of trying : pymilvus 2.2.13 is not working as expected with standalone server on windows but 2.2.1 works fine,

Running : pip install pymilvus==2.2.1 solved the problem

**Comment by yanliang567** [comment]
so what is the milvus again?

**Comment by trezae4475** [comment]
@yanliang567 issue was that milvus 2.3.0 do not work with version 2.2.13 of pymilvus. 
However milvus 2.2.11 and pymilvus 2.2.13 work fine together and milvus 2.3.0 work fine with pymilvus 2.2.1

/asassign @yanliang567

**Comment by yanliang567** [comment]
Milvus 2.3 is still in beta release, if you do want milvus 2.3, you need to install a dev pymilvus e.g.: pip install -i https://test.pypi.org/simple/ pymilvus==2.4.0.dev106
But please note that 2.3 is only for test purpose for now.

/assign @trezae4475 
/unassign
