### ISSUE TITLE
[Bug]: Conditionally log warning when DropSegment fails

### ISSUE THREAD

**Issue by tedyu** [milvus-io/milvus#25775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

In garbageCollector#clearEtcd, a warning would be logged whenever `gc.meta.DropSegment` is called.

### Expected Behavior

warning is logged only when there is error dropping segment.

**Comment by xiaofan-luan** [comment]
Thanks for the contribution!
