### ISSUE TITLE
failed to open database: Wal init error!

### ISSUE THREAD

**Issue by Bennu-Li** [milvus-io/milvus#2577]
**Describe the bug**
When starting milvus0.10.0, the db directory maps to the previous db directory of milvus 0.9, and an error will occur:
![image](https://user-images.githubusercontent.com/53458891/84760706-fb3d3a00-affa-11ea-8a84-01bb5c5b2f0e.png)
After closing wal, it can start successfully.
And mapping a new db directory can also start successfully.

**Comment by shengjun1985** [comment]
Can you show me the logs and the remained WAL file names?

**Comment by Bennu-Li** [comment]
When starting milvus, I did not map the wal directory.

[logs.zip](https://github.com/milvus-io/milvus/files/4796626/logs.zip)

**Comment by shengjun1985** [comment]
The default value of the config item wal.recovery_error_ignore is changed to "false" in 0.10.0.
Thus not to map the wal directory will cause that error.

**Comment by shengjun1985** [comment]
>> [2020-06-18 14:21:36,813][DEBUG][WAL][Init][milvus_server] start_lsn 0 end_lsn 9917079561633
>> [2020-06-18 14:21:36,813][ERROR][WAL][Init][milvus_server] bad wal file 0
Futhermore, the log files show another bug that the global LSN equals 0.
Fortunatly, it is fixed in issue #2378.
