### ISSUE TITLE
[Bug]: 创建collection提示permission deny

### ISSUE THREAD

**Issue by leoterry-ulrica** [milvus-io/milvus#25785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.7
- Deployment mode(standalone or cluster): cluster
- OS(Ubuntu or CentOS): ubuntu
```

### Current Behavior

通过attu GUI端创建collection，提示permission deny：
![image](https://github.com/milvus-io/milvus/assets/18339429/53c22b01-5c49-417a-b7ba-4de0c2bff967)

### Milvus Log
[INFO] [proxy/privilege_interceptor.go:160] ["permission deny"] [username=milvus] [role_names="[public]"] [object_type=Global] [object_privilege=PrivilegeCreateCollection] [db_name=default] [object_index=-1] [object_name=*] [object_indexs=0] [object_names="[]"] [policy_info="{\"PType\":\"p\",\"V0\":\"public\",\"V1\":\"Collection-*.*\",\"V2\":\"PrivilegeIndexDetail\"},{\"PType\":\"p\",\"V0\":\"public\",\"V1\":\"Global-*.*\",\"V2\":\"PrivilegeDescribeCollection\"},{\"PType\":\"p\",\"V0\":\"public\",\"V1\":\"Global-*.*\",\"V2\":\"PrivilegeShowCollections\"}"] [policy="[{\"PType\":\"p\",\"V0\":\"public\",\"V1\":\"Collection-*.*\",\"V2\":\"PrivilegeIndexDetail\"},{\"PType\":\"p\",\"V0\":\"public\",\"V1\":\"Global-*.*\",\"V2\":\"PrivilegeDescribeCollection\"},{\"PType\":\"p\",\"V0\":\"public\",\"V1\":\"Global-*.*\",\"V2\":\"PrivilegeShowCollections\"}]"] [roles="[public]"]

_No response_

**Comment by yanliang567** [comment]
it seems that the user 'milvus' was not granted for createCollection request. please check. @leoterry-ulrica 
/assign @leoterry-ulrica 
/unassign

**Comment by leoterry-ulrica** [comment]
> it seems that the user 'milvus' was not granted for createCollection request. please check. @leoterry-ulrica /assign @leoterry-ulrica /unassign

The problem is resolved. Log in as the root account.
