### ISSUE TITLE
[Bug]: etcd cannot restart

### ISSUE THREAD

**Issue by weihaopeng** [milvus-io/milvus#25797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.8 & 2.2.11
- Deployment mode(standalone or cluster):standalone, helm
- MQ type(rocksmq, pulsar or kafka):    no
- SDK version(e.g. pymilvus v2.0.0rc2): no
- OS(Ubuntu or CentOS): Centos
- CPU/Memory: 2.60GHz
- GPU: no
- Others:
```

### Current Behavior

1. stage k8s update milvus from 2.2.8 to 2.2.11 yesterday, no data.
2. prd k8s is always 2.2.8, little data.

About 12:00 pm today(noon), an etcd restart failed，milvus is temporarily normal.

After delete pod and then add, the etcd still have error on same etcd.

error log: [etcd.log](https://github.com/milvus-io/milvus/files/12102802/etcd.log)

 {"level":"info","ts":"2023-07-20T06:41:17.041Z","caller":"etcdserver/backend.go:85","msg":"db file is flocked by another process, or taking too long","path":"/bitnami/etcd/data/member/snap/db","took":"10.000064992s"}

### Anything else?

same as #22082, but after delete pod and then add, the etcd-1 still have error.

![image](https://github.com/milvus-io/milvus/assets/33681454/b10f0d63-8b24-41af-ac0e-bbbc5b5284a6)

**Comment by weihaopeng** [comment]
1. why it restart? How to avoid?
2. why it cannot restart successful?

**Comment by weihaopeng** [comment]
Not delete pod, delete the pvc mounted on the pod, and then restart. Seems work.

**Comment by yanliang567** [comment]
sounds like an ectd reliability issue. @LoveEachDay  any ideas?

/assign @LoveEachDay 
/unassign

**Comment by cliu701** [comment]
Met same issue for one etcd pod

**Comment by 1361515623** [comment]
> Not delete pod, delete the pvc mounted on the pod, and then restart. Seems work.
I tried that and solved it, but I can't find the process which lock the db file
