### ISSUE TITLE
[Enhancement]: can benchmark of milvus can measure recall? it can only measure rps and lantency now.

### ISSUE THREAD

**Issue by yanxiaoqi932** [milvus-io/milvus#25791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

can benchmark of milvus measure recall? it can only measure rps and lantency now.

**Comment by xiaofan-luan** [comment]
try https://github.com/zilliztech/VectorDBBench?

**Comment by yanxiaoqi932** [comment]
can we calculate recall in milvus benchmark through some modifies？
