### ISSUE TITLE
[Bug]: collection load fail, the reason is ：”get memory failed when checkSegmentSize“

### ISSUE THREAD

**Issue by Cactus-L** [milvus-io/milvus#25796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.9
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): milvus-sdk-java 2.2.8
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I release the collection, reload the collection.
collection load failed

### Milvus Log

[
2023/07/19 13:42:54.470 +00:00] [ERROR] [hardware/hardware_info.go:162] ["\"/sys/fs/cgroup/cpuacct/cpuacct.stat\" is expected to have 4 fields"] [stack="github.com/milvus-io/milvus/internal/util/hardware.GetUsedMemoryCount
\t/go/src/github.com/milvus-io/milvus/internal/util/hardware/hardware_info.go:162
github.com/milvus-io/milvus/internal/querynode.getSystemInfoMetrics
\t/go/src/github.com/milvus-io/milvus/internal/querynode/metrics_info.go:106
github.com/milvus-io/milvus/internal/querynode.(*QueryNode).GetMetrics
\t/go/src/github.com/milvus-io/milvus/internal/querynode/impl.go:1289
github.com/milvus-io/milvus/internal/distributed/querynode.(*Server).GetMetrics
\t/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:332
github.com/milvus-io/milvus/internal/proto/querypb._QueryNode_GetMetrics_Handler.func1
\t/go/src/github.com/milvus-io/milvus/internal/proto/querypb/query_coord.pb.go:5812
github.com/milvus-io/milvus/internal/util/logutil.UnaryTraceLoggerInterceptor
\t/go/src/github.com/milvus-io/milvus/internal/util/logutil/grpc_interceptor.go:22
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25
github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1
\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1
\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34
github.com/milvus-io/milvus/internal/proto/querypb._QueryNode_GetMetrics_Handler
\t/go/src/github.com/milvus-io/milvus/internal/proto/querypb/query_coord.pb.go:5814
google.golang.org/grpc.(*Server).processUnaryRPC
\t/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1283
google.golang.org/grpc.(*Server).handleStream
\t/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1620
google.golang.org/grpc.(*Server).serveStreams.func1.2
\t/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:922"]

[2023/07/19 13:42:54.471 +00:00] [ERROR] [hardware/hardware_info.go:97] ["\"/sys/fs/cgroup/cpuacct/cpuacct.stat\" is expected to have 4 fields"] [stack="github.com/milvus-io/milvus/internal/util/hardware.GetMemoryCount
\t/go/src/github.com/milvus-io/milvus/internal/util/hardware/hardware_info.go:97
github.com/milvus-io/milvus/internal/querynode.getSystemInfoMetrics
\t/go/src/github.com/milvus-io/milvus/internal/querynode/metrics_info.go:107
github.com/milvus-io/milvus/internal/querynode.(*QueryNode).GetMetrics
\t/go/src/github.com/milvus-io/milvus/internal/querynode/impl.go:1289
github.com/milvus-io/milvus/internal/distributed/querynode.(*Server).GetMetrics
\t/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:332
github.com/milvus-io/milvus/internal/proto/querypb._QueryNode_GetMetrics_Handler.func1
\t/go/src/github.com/milvus-io/milvus/internal/proto/querypb/query_coord.pb.go:5812
github.com/milvus-io/milvus/internal/util/logutil.UnaryTraceLoggerInterceptor
\t/go/src/github.com/milvus-io/milvus/internal/util/logutil/grpc_interceptor.go:22
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25
github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1
\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1
\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34
github.com/milvus-io/milvus/internal/proto/querypb._QueryNode_GetMetrics_Handler
\t/go/src/github.com/milvus-io/milvus/internal/proto/querypb/query_coord.pb.go:5814
google.golang.org/grpc.(*Server).processUnaryRPC
\t/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1283
google.golang.org/grpc.(*Server).handleStream
\t/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1620
google.golang.org/grpc.(*Server).serveStreams.func1.2
\t/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:922"]

[2023/07/19 13:42:55.241 +00:00] [ERROR] [hardware/hardware_info.go:162] ["\"/sys/fs/cgroup/cpuacct/cpuacct.stat\" is expected to have 4 fields"] [stack="github.com/milvus-io/milvus/internal/util/hardware.GetUsedMemoryCount
\t/go/src/github.com/milvus-io/milvus/internal/util/hardware/hardware_info.go:162
github.com/milvus-io/milvus/internal/querynode.(*segmentLoader).checkSegmentSize
\t/go/src/github.com/milvus-io/milvus/internal/querynode/segment_loader.go:795
github.com/milvus-io/milvus/internal/querynode.(*segmentLoader).LoadSegment
\t/go/src/github.com/milvus-io/milvus/internal/querynode/segment_loader.go:152
github.com/milvus-io/milvus/internal/querynode.(*loadSegmentsTask).Execute
\t/go/src/github.com/milvus-io/milvus/internal/querynode/load_segment_task.go:81
github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).processTask
\t/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:108
github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).taskLoop
\t/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:130"]

[2023/07/19 13:42:55.241 +00:00] [ERROR] [hardware/hardware_info.go:131] ["\"/sys/fs/cgroup/cpuacct/cpuacct.stat\" is expected to have 4 fields"] [stack="github.com/milvus-io/milvus/internal/util/hardware.GetAvailableMemoryCount
\t/go/src/github.com/milvus-io/milvus/internal/util/hardware/hardware_info.go:131
github.com/milvus-io/milvus/internal/querynode.(*segmentLoader).checkSegmentSize
\t/go/src/github.com/milvus-io/milvus/internal/querynode/segment_loader.go:796
github.com/milvus-io/milvus/internal/querynode.(*segmentLoader).LoadSegment
\t/go/src/github.com/milvus-io/milvus/internal/querynode/segment_loader.go:152
github.com/milvus-io/milvus/internal/querynode.(*loadSegmentsTask).Execute
\t/go/src/github.com/milvus-io/milvus/internal/querynode/load_segment_task.go:81
github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).processTask
\t/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:108
github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).taskLoop
\t/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:130"]

[2023/07/19 13:42:55.241 +00:00] [ERROR] [querynode/segment_loader.go:154] ["load failed, OOM if loaded"] [collectionID=442799110303762160] [segmentType=Sealed] ["loadSegmentRequest msgID"=13833351] [error="get memory failed when checkSegmentSize, collectionID = 442799110303762160"] [stack="github.com/milvus-io/milvus/internal/querynode.(*segmentLoader).LoadSegment
\t/go/src/github.com/milvus-io/milvus/internal/querynode/segment_loader.go:154
github.com/milvus-io/milvus/internal/querynode.(*loadSegmentsTask).Execute
\t/go/src/github.com/milvus-io/milvus/internal/querynode/load_segment_task.go:81
github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).processTask
\t/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:108
github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).taskLoop
\t/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:130"]

**Comment by jiaoew1991** [comment]
Hi @Cactus-L, when Milvus loads data, it tries to obtain the remaining system memory. From the error message, it seems that you are running Milvus in a container. 
We use https://github.com/containerd/cgroups to retrieve memory status. It is possible that the version of this library is too low. Can you please try upgrading cgroups in your environment? We don't have the same environment, so it's difficult for us to reproduce this issue.

**Comment by Cactus-L** [comment]
> Hi @Cactus-L, when Milvus loads data, it tries to obtain the remaining system memory. From the error message, it seems that you are running Milvus in a container. We use https://github.com/containerd/cgroups to retrieve memory status. It is possible that the version of this library is too low. Can you please try upgrading cgroups in your environment? We don't have the same environment, so it's difficult for us to reproduce this issue.

Ok, thank you for the solution, I will try it

**Comment by Cactus-L** [comment]
> 

The cgroups version we are currently using is v2, which is the latest version. Doesn’t milvus support this version?

**Comment by xiaofan-luan** [comment]
this mechanism might need to be refined
1. if we can not get memory usage, we just do load and see if it works
2. with the new mmap strategy should we still need this check?

**Comment by jiaoew1991** [comment]
> > 
> 
> The cgroups version we are currently using is v2, which is the latest version. Doesn’t milvus support this version?

You can try upgrading the version of containerd/cgroups in the go.mod file of Milvus, and then recompile a Milvus to test it.

**Comment by jiaoew1991** [comment]
> this mechanism might need to be refined
> 
> 1. if we can not get memory usage, we just do load and see if it works
> 2. with the new mmap strategy should we still need this check?

I think we can give it a try on the master branch. There is no mmap in 2.2 either, so let's maintain the current situation for now 🤔

**Comment by Cactus-L** [comment]
> 

Is there any way for me to quickly verify that I am not particularly familiar with go

**Comment by Cactus-L** [comment]
> > Is there any way for me to quickly verify that I am not particularly familiar with go

**Comment by Cactus-L** [comment]
> This should be related to the linux version. I have such a problem in Linux version 5.10.0, but it works in Linux version 3.10.0.
