### ISSUE TITLE
[Bug]: data service save bin log path failed, reason = role datacoord[nodeID: 3] is not serving, reason: sate code: Abnormal

### ISSUE THREAD

**Issue by yandechao** [milvus-io/milvus#25800]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.2.11
- Deployment mode(standalone or cluster):standalone 
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

2023/07/19 09:04:24 maxprocs: Leaving GOMAXPROCS=16: CPU quota undefined

    __  _________ _   ____  ______    
   /  |/  /  _/ /| | / / / / / __/    
  / /|_/ // // /_| |/ / /_/ /\ \    
 /_/  /_/___/____/___/\____/___/     

Welcome to use Milvus!
Version:   v2.2.11
Built:     Thu Jun 29 13:44:44 UTC 2023
GitCommit: 4501c426
GoVersion: go version go1.18.3 linux/amd64

open pid file: /run/milvus/standalone.pid
lock pid file: /run/milvus/standalone.pid
{"level":"warn","ts":"2023-07-20T06:20:05.536Z","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00053ae00/etcd:2379","attempt":0,"error":"rpc error: code = Unavailable desc = etcdserver: request timed out"}
{"level":"warn","ts":"2023-07-20T06:20:25.100Z","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00053ae00/etcd:2379","attempt":0,"error":"rpc error: code = Unavailable desc = etcdserver: request timed out"}
{"level":"warn","ts":"2023-07-20T06:20:25.490Z","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00067d6c0/etcd:2379","attempt":0,"error":"rpc error: code = Unavailable desc = etcdserver: request timed out"}
{"level":"warn","ts":"2023-07-20T06:20:32.102Z","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00053ae00/etcd:2379","attempt":0,"error":"rpc error: code = Unavailable desc = etcdserver: request timed out"}
{"level":"warn","ts":"2023-07-20T06:20:32.493Z","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00067d6c0/etcd:2379","attempt":0,"error":"rpc error: code = Unavailable desc = etcdserver: request timed out"}
{"level":"warn","ts":"2023-07-20T06:20:35.547Z","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc002135180/etcd:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
{"level":"warn","ts":"2023-07-20T06:20:39.103Z","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00053ae00/etcd:2379","attempt":0,"error":"rpc error: code = Unavailable desc = etcdserver: request timed out"}
{"level":"warn","ts":"2023-07-20T06:20:39.496Z","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00067d6c0/etcd:2379","attempt":0,"error":"rpc error: code = Unavailable desc = etcdserver: request timed out"}
{"level":"warn","ts":"2023-07-20T06:20:44.458Z","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc002294380/etcd:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
{"level":"warn","ts":"2023-07-20T06:20:46.500Z","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00067d6c0/etcd:2379","attempt":0,"error":"rpc error: code = Unavailable desc = etcdserver: request timed out"}
{"level":"warn","ts":"2023-07-20T06:20:50.387Z","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00053ae00/etcd:2379","attempt":0,"error":"rpc error: code = Unavailable desc = etcdserver: request timed out"}
{"level":"warn","ts":"2023-07-20T06:20:50.387Z","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0015fe1c0/etcd:2379","attempt":0,"error":"rpc error: code = Unavailable desc = etcdserver: request timed out"}
panic: All attempts results:
attempt #1:data service save bin log path failed, reason = role datacoord[nodeID: 3] is not serving, reason: sate code: Abnormal
attempt #2:data service save bin log path failed, reason = role datacoord[nodeID: 3] is not serving, reason: sate code: Abnormal
attempt #3:data service save bin log path failed, reason = role datacoord[nodeID: 3] is not serving, reason: sate code: Abnormal
attempt #4:data service save bin log path failed, reason = role datacoord[nodeID: 3] is not serving, reason: sate code: Abnormal
attempt #5:data service save bin log path failed, reason = role datacoord[nodeID: 3] is not serving, reason: sate code: Abnormal
attempt #6:data service save bin log path failed, reason = role datacoord[nodeID: 3] is not serving, reason: sate code: Abnormal
attempt #7:data service save bin log path failed, reason = role datacoord[nodeID: 3] is not serving, reason: sate code: Abnormal
attempt #8:data service save bin log path failed, reason = role datacoord[nodeID: 3] is not serving, reason: sate code: Abnormal
attempt #9:data service save bin log path failed, reason = role datacoord[nodeID: 3] is not serving, reason: sate code: Abnormal
attempt #10:data service save bin log path failed, reason = role datacoord[nodeID: 3] is not serving, reason: sate code: Abnormal
attempt #11:data service save bin log path failed, reason = role datacoord[nodeID: 3] is not serving, reason: sate code: Abnormal

goroutine 4255283 [running]:
github.com/milvus-io/milvus/internal/datanode.flushNotifyFunc.func1(0xc005891db0)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:874 +0x148f
github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).waitFinish(0xc001474600, 0xc008181e00, 0xc008a52950)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:204 +0xdb
created by github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).init.func1
	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:121 +0xf1
	
	
	

### Milvus Log

[Uploading milvus-standalone.log.tar.gz…]()

**Comment by yandechao** [comment]
日志文件：
[https://github.com/yandechao/milvus-standalone/blob/main/milvus-standalone.log.tar.gz](url)

**Comment by yanliang567** [comment]
it seems that your etcd service is not healthy. please double check

/assign @yandechao 
/unassign
