### ISSUE TITLE
[Enhancement]: Add eventlog component for Milvus

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#25810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Add eventlog component for Milvus

### Why is this needed?

By supporting event logger, we could
- Persistent events into storage service(minio/s3, kv or local file)
- Online debug with event streaming

This feature could increasing the observability of system and make it easier to debug system behavior

**Comment by congqixia** [comment]
![image](https://github.com/milvus-io/milvus/assets/84113973/dc8b0dfe-3c41-4835-90b9-b3028f5a6e6e)
simple example implemented locally

**Comment by jiaoew1991** [comment]
We still need at least event logs for jobs like compaction, flush, build index, and garbage collection.
