### ISSUE TITLE
[Bug]: Exception when insert 760,000 row with text, integer and 768 dim vector

### ISSUE THREAD

**Issue by thusinh1969** [milvus-io/milvus#25829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.13
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 
- OS(Ubuntu or CentOS): Ubuntu 20,04
- CPU/Memory: dual Xeon 6410 total 72 threads / 320G RAM
- GPU: 2xRTX3090
- Others: plenty of disk space (7TBytes)
```

### Current Behavior

Field schema likes this:
id = FieldSchema(
    name="id",
    dtype=DataType.INT64,
    is_primary=True,
    auto_id = True,
    description = "Auto-increment row ID"
)
created_date = FieldSchema(
    name="created_date",
    dtype=DataType.INT64,
    description = "created_date"
)
updated_date = FieldSchema(
    name="updated_date",
    dtype=DataType.INT64,
    description = "updated_date"
)
created_by = FieldSchema(
    name="created_by",
    dtype=DataType.VARCHAR,
    max_length=128,
    description = "created_by"
)
doc_category = FieldSchema(
    name="doc_category",
    dtype=DataType.INT16,
    description = "doc_category"
)
doc_id = FieldSchema(
    name="doc_id",
    dtype=DataType.INT16,
    description = "doc_id"
)
doc_desc = FieldSchema(
    name="doc_desc",
    dtype=DataType.VARCHAR,
    max_length=2048,
    description = "doc_desc"
)
doc_dir = FieldSchema(
    name="doc_dir",
    dtype=DataType.VARCHAR,
    max_length=2048,
    description = "doc_dir"
)
doc_filename = FieldSchema(
    name="doc_filename",
    dtype=DataType.VARCHAR,
    max_length=4096,
    description = "doc_filename"
)
doc_url = FieldSchema(
    name="doc_url",
    dtype=DataType.VARCHAR,
    max_length=4096,
    description = "doc_url"
)
doc_chunk_content = FieldSchema(
    name="doc_chunk_content",
    dtype=DataType.VARCHAR,
    max_length=8096,
    description = "doc_chunk_content"
)
doc_chunk_num = FieldSchema(
    name="doc_chunk_num",
    dtype=DataType.INT16,
    description = "doc_chunk_num"
)
doc_token_index_from = FieldSchema(
    name="doc_token_index_from",
    dtype=DataType.INT16,
    description = "doc_token_index_from"
)
doc_token_index_to = FieldSchema(
    name="doc_token_index_to",
    dtype=DataType.INT16,
    description = "doc_token_index_to"
)
vector = FieldSchema(
    name="vector",
    dtype=DataType.FLOAT_VECTOR,
    dim=768,
    description = "vector"
)
vector_norm = FieldSchema(
    name="vector_norm",
    dtype=DataType.FLOAT_VECTOR,
    dim=768,
    description = "vector_norm"
)

for data in dict_values:
    mr = collection.insert(data)
collection.flush()

There are 750,000 rows of the above schema in dict_values. The insert works fine for couple minutes (9178 rows inserted) and then the exception occurred.

### Expected Behavior

It should insert Ok then flush.

### Milvus Log

RPC error: [insert_rows], <MilvusException: (code=1, message=the 0th element (33409) out of range: [-32768, 32767])>, <Time:{'RPC start': '2023-07-21 13:12:30.117377', 'RPC error': '2023-07-21 13:12:30.121196'}>
---------------------------------------------------------------------------
MilvusException                           Traceback (most recent call last)
Cell In[268], line 2
      1 for data in dict_values:
----> 2     mr = collection.insert(data)

File ~/env/lib/python3.10/site-packages/pymilvus/orm/collection.py:448, in Collection.insert(self, data, partition_name, timeout, **kwargs)
    446         return MutationFuture(res)
    447 else:
--> 448     res = conn.insert_rows(self._name, data, partition_name,
    449                            timeout=timeout, schema=self._schema_dict, **kwargs)
    450 return MutationResult(res)

File ~/env/lib/python3.10/site-packages/pymilvus/decorators.py:109, in error_handler.<locals>.wrapper.<locals>.handler(*args, **kwargs)
    107     record_dict["RPC error"] = str(datetime.datetime.now())
    108     LOGGER.error(f"RPC error: [{inner_name}], {e}, <Time:{record_dict}>")
--> 109     raise e
    110 except grpc.FutureTimeoutError as e:
    111     record_dict["gRPC timeout"] = str(datetime.datetime.now())

File ~/env/lib/python3.10/site-packages/pymilvus/decorators.py:105, in error_handler.<locals>.wrapper.<locals>.handler(*args, **kwargs)
    103 try:
    104     record_dict["RPC start"] = str(datetime.datetime.now())
--> 105     return func(*args, **kwargs)
    106 except MilvusException as e:
    107     record_dict["RPC error"] = str(datetime.datetime.now())

File ~/env/lib/python3.10/site-packages/pymilvus/decorators.py:136, in tracing_request.<locals>.wrapper.<locals>.handler(self, *args, **kwargs)
    134 if req_id:
    135     self.set_onetime_request_id(req_id)
--> 136 ret = func(self, *args, **kwargs)
    137 return ret

File ~/env/lib/python3.10/site-packages/pymilvus/decorators.py:85, in retry_on_rpc_failure.<locals>.wrapper.<locals>.handler(self, *args, **kwargs)
     83         back_off = min(back_off * back_off_multiplier, max_back_off)
     84     else:
---> 85         raise e
     86 except Exception as e:
     87     raise e

File ~/env/lib/python3.10/site-packages/pymilvus/decorators.py:50, in retry_on_rpc_failure.<locals>.wrapper.<locals>.handler(self, *args, **kwargs)
     48 while True:
     49     try:
---> 50         return func(self, *args, **kwargs)
     51     except grpc.RpcError as e:
     52         # DEADLINE_EXCEEDED means that the task wat not completed
     53         # UNAVAILABLE means that the service is not reachable currently
     54         # Reference: https://grpc.github.io/grpc/python/grpc.html#grpc-status-code
     55         if e.code() != grpc.StatusCode.DEADLINE_EXCEEDED and e.code() != grpc.StatusCode.UNAVAILABLE:

File ~/env/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py:447, in GrpcHandler.insert_rows(self, collection_name, entities, partition_name, timeout, **kwargs)
    445     raise MilvusException(response.status.error_code, response.status.reason)
    446 except Exception as err:
--> 447     raise err

File ~/env/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py:445, in GrpcHandler.insert_rows(self, collection_name, entities, partition_name, timeout, **kwargs)
    442         ts_utils.update_collection_ts(collection_name, m.timestamp)
    443         return m
--> 445     raise MilvusException(response.status.error_code, response.status.reason)
    446 except Exception as err:
    447     raise err

MilvusException: <MilvusException: (code=1, message=the 0th element (33409) out of range: [-32768, 32767])>
collection.flush()

### Anything else?

Any help is appreciated.

Thanks,
Steve

**Comment by yanliang567** [comment]
@thusinh1969 thank you for feedbacks. the latest milvus release is v2.2.11, so Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @thusinh1969

**Comment by thusinh1969** [comment]
I am running docker-compose standalone mode. How to I generate log ? What is instance-name anyway ?

Steve

**Comment by yanliang567** [comment]
For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.

**Comment by thusinh1969** [comment]
Here come the log.

https://drive.google.com/file/d/1NpiUFjfpQehhcRpcOo7oW5zElfOEiAqu/view?usp=sharing

Thanks,
Steve

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version: 2.2.13
> - Deployment mode(standalone or cluster): standalone
> - SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 
> - OS(Ubuntu or CentOS): Ubuntu 20,04
> - CPU/Memory: dual Xeon 6410 total 72 threads / 320G RAM
> - GPU: 2xRTX3090
> - Others: plenty of disk space (7TBytes)
> ```
> 
> ### Current Behavior
> Field schema likes this: id = FieldSchema( name="id", dtype=DataType.INT64, is_primary=True, auto_id = True, description = "Auto-increment row ID" ) created_date = FieldSchema( name="created_date", dtype=DataType.INT64, description = "created_date" ) updated_date = FieldSchema( name="updated_date", dtype=DataType.INT64, description = "updated_date" ) created_by = FieldSchema( name="created_by", dtype=DataType.VARCHAR, max_length=128, description = "created_by" ) doc_category = FieldSchema( name="doc_category", dtype=DataType.INT16, description = "doc_category" ) doc_id = FieldSchema( name="doc_id", dtype=DataType.INT16, description = "doc_id" ) doc_desc = FieldSchema( name="doc_desc", dtype=DataType.VARCHAR, max_length=2048, description = "doc_desc" ) doc_dir = FieldSchema( name="doc_dir", dtype=DataType.VARCHAR, max_length=2048, description = "doc_dir" ) doc_filename = FieldSchema( name="doc_filename", dtype=DataType.VARCHAR, max_length=4096, description = "doc_filename" ) doc_url = FieldSchema( name="doc_url", dtype=DataType.VARCHAR, max_length=4096, description = "doc_url" ) doc_chunk_content = FieldSchema( name="doc_chunk_content", dtype=DataType.VARCHAR, max_length=8096, description = "doc_chunk_content" ) doc_chunk_num = FieldSchema( name="doc_chunk_num", dtype=DataType.INT16, description = "doc_chunk_num" ) doc_token_index_from = FieldSchema( name="doc_token_index_from", dtype=DataType.INT16, description = "doc_token_index_from" ) doc_token_index_to = FieldSchema( name="doc_token_index_to", dtype=DataType.INT16, description = "doc_token_index_to" ) vector = FieldSchema( name="vector", dtype=DataType.FLOAT_VECTOR, dim=768, description = "vector" ) vector_norm = FieldSchema( name="vector_norm", dtype=DataType.FLOAT_VECTOR, dim=768, description = "vector_norm" )
> 
> for data in dict_values: mr = collection.insert(data) collection.flush()
> 
> There are 750,000 rows of the above schema in dict_values. The insert works fine for couple minutes (9178 rows inserted) and then the exception occurred.
> 
> ### Expected Behavior
> It should insert Ok then flush.
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> ## RPC error: [insert_rows], <MilvusException: (code=1, message=the 0th element (33409) out of range: [-32768, 32767])>, <Time:{'RPC start': '2023-07-21 13:12:30.117377', 'RPC error': '2023-07-21 13:12:30.121196'}>
> MilvusException Traceback (most recent call last) Cell In[268], line 2 1 for data in dict_values: ----> 2 mr = collection.insert(data)
> 
> File ~/env/lib/python3.10/site-packages/pymilvus/orm/collection.py:448, in Collection.insert(self, data, partition_name, timeout, **kwargs) 446 return MutationFuture(res) 447 else: --> 448 res = conn.insert_rows(self._name, data, partition_name, 449 timeout=timeout, schema=self._schema_dict, **kwargs) 450 return MutationResult(res)
> 
> File ~/env/lib/python3.10/site-packages/pymilvus/decorators.py:109, in error_handler..wrapper..handler(*args, **kwargs) 107 record_dict["RPC error"] = str(datetime.datetime.now()) 108 LOGGER.error(f"RPC error: [{inner_name}], {e}, Time:{record_dict}") --> 109 raise e 110 except grpc.FutureTimeoutError as e: 111 record_dict["gRPC timeout"] = str(datetime.datetime.now())
> 
> File ~/env/lib/python3.10/site-packages/pymilvus/decorators.py:105, in error_handler..wrapper..handler(*args, **kwargs) 103 try: 104 record_dict["RPC start"] = str(datetime.datetime.now()) --> 105 return func(*args, **kwargs) 106 except MilvusException as e: 107 record_dict["RPC error"] = str(datetime.datetime.now())
> 
> File ~/env/lib/python3.10/site-packages/pymilvus/decorators.py:136, in tracing_request..wrapper..handler(self, *args, **kwargs) 134 if req_id: 135 self.set_onetime_request_id(req_id) --> 136 ret = func(self, *args, **kwargs) 137 return ret
> 
> File ~/env/lib/python3.10/site-packages/pymilvus/decorators.py:85, in retry_on_rpc_failure..wrapper..handler(self, *args, **kwargs) 83 back_off = min(back_off * back_off_multiplier, max_back_off) 84 else: ---> 85 raise e 86 except Exception as e: 87 raise e
> 
> File ~/env/lib/python3.10/site-packages/pymilvus/decorators.py:50, in retry_on_rpc_failure..wrapper..handler(self, *args, **kwargs) 48 while True: 49 try: ---> 50 return func(self, *args, **kwargs) 51 except grpc.RpcError as e: 52 # DEADLINE_EXCEEDED means that the task wat not completed 53 # UNAVAILABLE means that the service is not reachable currently 54 # Reference: https://grpc.github.io/grpc/python/grpc.html#grpc-status-code 55 if e.code() != grpc.StatusCode.DEADLINE_EXCEEDED and e.code() != grpc.StatusCode.UNAVAILABLE:
> 
> File ~/env/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py:447, in GrpcHandler.insert_rows(self, collection_name, entities, partition_name, timeout, **kwargs) 445 raise MilvusException(response.status.error_code, response.status.reason) 446 except Exception as err: --> 447 raise err
> 
> File ~/env/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py:445, in GrpcHandler.insert_rows(self, collection_name, entities, partition_name, timeout, **kwargs) 442 ts_utils.update_collection_ts(collection_name, m.timestamp) 443 return m --> 445 raise MilvusException(response.status.error_code, response.status.reason) 446 except Exception as err: 447 raise err
> 
> MilvusException: <MilvusException: (code=1, message=the 0th element (33409) out of range: [-32768, 32767])> collection.flush()
> 
> ### Anything else?
> Any help is appreciated.
> 
> Thanks, Steve

Seems that your data is overflow.
some of the int16 datatypes has a value of 33409
