### ISSUE TITLE
performance degradation

### ISSUE THREAD

**Issue by xwqb** [milvus-io/milvus#2584]
milvus version is:0.8.0
java sdk version: 0.7.0
centos 7

1，milvus在服务器静止的时候客户端压测，性能正常

2，这时提高服务器cpu负载(其他程序抢占服务器资源)，客户端不停止压测，qps性能降低60%

3，停止压测与服务器其他程序抢占资源还原为静止状态

4，继续启动客户端压测，这时qps性能仍然降低60%

5，重启客户端，重新压测性能才能达到第1步的程度

**Comment by tinkerlin** [comment]
Pleasae provide more information about your test environment, milvus configuration, index_type, and more. This helps us reproduce the issue you're having and resolve the issue more quickly.

You can refer to the following template.

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report.

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Comment by del-zhenwu** [comment]
![Screenshot_2020-07-02 Locust](https://user-images.githubusercontent.com/56623710/86332194-beb94180-bc7c-11ea-893b-cf30b1b2c3e9.png)
As the above screenshot shows, this issue can not re-produce using locust. 
The first gap happened when doing `stress -c 6`, and then the qps value back to normal.
The second gap happened at `stress -c 12`, and then it is expected.
