### ISSUE TITLE
[Bug]: Data loss in database after some time

### ISSUE THREAD

**Issue by HantaoCai** [milvus-io/milvus#25878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.11
- Deployment mode (standalone or cluster): cluster
- MQ type (rocksmq, pulsar or kafka) : pulsar
- SDK version(e.g. pymilvus v2.0.0 rc2): pymilvus 2.2.13
- OS (Ubuntu or CentOS) : k8s/centos
- CPU/Memory: 12/24
- GPU: None
- Others:
```

### Current Behavior

During our utilization of Milvus, we encountered a situation where all the data within a singular table was lost. This signifies that the entire contents of a single table have been wiped clean.

In terms of our operative process, we are segmenting users' files and then interacting with the OpenAI interface. The embedded responses received from OpenAI are subsequently stored in the vector field. For repeatability and data consistency purposes, identical paragraphs will use the same primary key ID when inserting data.

Our current issue is that over time, all the data in the database tables disappear. 

### Expected Behavior

-

### Steps To Reproduce

```markdown
-
```

### Milvus Log

[milvus.zip](https://github.com/milvus-io/milvus/files/12145518/milvus.zip)

### Anything else?

-

**Comment by HantaoCai** [comment]
[2023/07/21 08:25:59.899 +00:00] [INFO] [rootcoord/import_manager.go:177] ["(in cleanupLoop) trying to expire old tasks from memory and Etcd"]
[2023/07/21 08:25:59.899 +00:00] [INFO] [rootcoord/import_manager.go:180] ["(in cleanupLoop) start removing bad import segments"]
[2023/07/21 08:25:59.900 +00:00] [INFO] [rootcoord/import_manager.go:182] ["(in cleanupLoop) start cleaning hanging busy DataNode"]

**Comment by xiaofan-luan** [comment]
> We put the data in the oss of aliyun, the following log may be more useful:
> 
> [2023/07/21 08:25:10.781 +00:00] [INFO] [datacoord/services.go:824] ["datacoord append channelInfo in GetRecoveryInfo"] [collectionID=44293180531907386 6] [partitionIDs="[]"] [channelInfo="collectionID:442931805319073866 channelName:"by-dev-rootcoord-dml_0_442931805319073866v0" seek_position:<channel _name:"by-dev-rootcoord-dml_0_442931805319073866v0" msgID:"\010\363\002\020\202\212\002\030\000 \000" msgGroup:"by-dev-dataNode-667-by-d ev-rootcoord-dml_0_442931805319073866v0" timestamp:443004454371065858 > unflushedSegmentIds:442931805319278447 "] [2023/07/21 08:25:10.781 +00:00] [INFO] [datacoord/services.go:788] ["get recovery info request received"] [collectionID=442931805319075166] [partition IDs="[]"] [2023/07/21 08:25:10.782 +00:00] [INFO] [datacoord/handler.go:119] [GetQueryVChanPositions] [collectionID=442931805319075166] [channel=by-dev-rootcoord -dml_1_442931805319075166v0] [numOfSegments=1] [2023/07/21 08:25:10.782 +00:00] [INFO] [datacoord/handler.go:288] ["channel seek position set from channel checkpoint meta"] [channel=by-dev-rootcoord-dml_1_442931805319075166v0] [posTs=443004454371065858] [posTime=2023/07/21 08:24:40.749 +00:00] [2023/07/21 08:25:10.782 +00:00] [INFO] [datacoord/services.go:824] ["datacoord append channelInfo in GetRecoveryInfo"] [collectionID=442931805319075166] [partitionIDs="[]"] [channelInfo="collectionID:442931805319075166 channelName:"by-dev-rootcoord-dml_1_442931805319075166v0" seek_position:<channel_name:"by-dev-rootcoord-dml_1_442931805319075166v0" msgID:"\010\364\002\020\204\355\001\030\000 \000" msgGroup:"by-dev-dataNode-667-by-dev-rootcoord-dml_1_442931805319075166v0" timestamp:443004454371065858 > unflushedSegmentIds:442933696215352080 "] [2023/07/21 08:25:40.780 +00:00] [INFO] [datacoord/services.go:788] ["get recovery info request received"] [collectionID=442931805319073866] [partitionIDs="[]"] [2023/07/21 08:25:40.781 +00:00] [INFO] [datacoord/handler.go:119] [GetQueryVChanPositions] [collectionID=442931805319073866] [channel=by-dev-rootcoord-dml_0_442931805319073866v0] [numOfSegments=1] [2023/07/21 08:25:40.781 +00:00] [INFO] [datacoord/handler.go:288] ["channel seek position set from channel checkpoint meta"] [channel=by-dev-rootcoord-dml_0_442931805319073866v0] [posTs=443004454371065858] [posTime=2023/07/21 08:24:40.749 +00:00] [2023/07/21 08:25:40.781 +00:00] [INFO] [datacoord/services.go:824] ["datacoord append channelInfo in GetRecoveryInfo"] [collectionID=442931805319073866] [partitionIDs="[]"] [channelInfo="collectionID:442931805319073866 channelName:"by-dev-rootcoord-dml_0_442931805319073866v0" seek_position:<channel_name:"by-dev-rootcoord-dml_0_442931805319073866v0" msgID:"\010\363\002\020\202\212\002\030\000 \000" msgGroup:"by-dev-dataNode-667-by-dev-rootcoord-dml_0_442931805319073866v0" timestamp:443004454371065858 > unflushedSegmentIds:442931805319278447 "] [2023/07/21 08:25:40.781 +00:00] [INFO] [datacoord/services.go:788] ["get recovery info request received"] [collectionID=442931805319075166] [partitionIDs="[]"] [2023/07/21 08:25:40.782 +00:00] [INFO] [datacoord/handler.go:119] [GetQueryVChanPositions] [collectionID=442931805319075166] [channel=by-dev-rootcoord-dml_1_442931805319075166v0] [numOfSegments=1] [2023/07/21 08:25:40.782 +00:00] [INFO] [datacoord/handler.go:288] ["channel seek position set from channel checkpoint meta"] [channel=by-dev-rootcoord-dml_1_442931805319075166v0] [posTs=443004454371065858] [posTime=2023/07/21 08:24:40.749 +00:00] [2023/07/21 08:25:40.782 +00:00] [INFO] [datacoord/services.go:824] ["datacoord append channelInfo in GetRecoveryInfo"] [collectionID=442931805319075166] [partitionIDs="[]"] [channelInfo="collectionID:442931805319075166 channelName:"by-dev-rootcoord-dml_1_442931805319075166v0" seek_position:<channel_name:"by-dev-rootcoord-dml_1_442931805319075166v0" msgID:"\010\364\002\020\204\355\001\030\000 \000" msgGroup:"by-dev-dataNode-667-by-dev-rootcoord-dml_1_442931805319075166v0" timestamp:443004454371065858 > unflushedSegmentIds:442933696215352080 "] [2023/07/21 08:26:04.388 +00:00] [INFO] [datacoord/policy.go:585] ["node channel count is not much larger than average, skip reallocating"] [nodeID=667] [channelCount=3] [channelCountPerNode=3] [2023/07/21 08:26:04.388 +00:00] [INFO] [datacoord/policy.go:604] ["Channel Balancer got new reAllocations:"] [reAllocations="[]"] [2023/07/21 08:26:04.388 +00:00] [INFO] [datacoord/channel_manager.go:276] ["channel manager bg check balance"] [toReleases="[]"] [2023/07/21 08:26:05.099 +00:00] [INFO] [datacoord/garbage_collector.go:198] ["scan file to do garbage collection"] [total=136] [valid=136] [missing=0] [removedKeys="[]"] [2023/07/21 08:26:10.780 +00:00] [INFO] [datacoord/services.go:788] ["get recovery info request received"] [collectionID=442931805319073866] [partitionIDs="[]"] [2023/07/21 08:26:10.781 +00:00] [INFO] [datacoord/handler.go:119] [GetQueryVChanPositions] [collectionID=442931805319073866] [channel=by-dev-rootcoord-dml_0_442931805319073866v0] [numOfSegments=1] [2023/07/21 08:26:10.781 +00:00] [INFO] [datacoord/handler.go:288] ["channel seek position set from channel checkpoint meta"] [channel=by-dev-rootcoord-dml_0_442931805319073866v0] [posTs=443004470099705858] [posTime=2023/07/21 08:25:40.749 +00:00]
> 
> [2023/07/21 08:25:59.899 +00:00] [INFO] [rootcoord/import_manager.go:177] ["(in cleanupLoop) trying to expire old tasks from memory and Etcd"] [2023/07/21 08:25:59.899 +00:00] [INFO] [rootcoord/import_manager.go:180] ["(in cleanupLoop) start removing bad import segments"] [2023/07/21 08:25:59.900 +00:00] [INFO] [rootcoord/import_manager.go:182] ["(in cleanupLoop) start cleaning hanging busy DataNode"]
> 
> [2023/07/22 08:26:04.389 +00:00] [INFO] [datacoord/policy.go:585] ["node channel count is not much larger than average, skip reallocating"] [nodeID=667 ] [channelCount=3] [channelCountPerNode=3] [2023/07/22 08:26:04.389 +00:00] [INFO] [datacoord/policy.go:604] ["Channel Balancer got new reAllocations:"] [reAllocations="[]"] [2023/07/22 08:26:04.389 +00:00] [INFO] [datacoord/channel_manager.go:276] ["channel manager bg check balance"] [toReleases="[]"] [2023/07/22 08:26:04.455 +00:00] [INFO] [datacoord/garbage_collector.go:271] ["GC segment"] [segmentID=442933696215352080] [segmentID=44293369621535208 0] [2023/07/22 08:26:05.115 +00:00] [INFO] [datacoord/meta.go:282] ["meta update: dropping segment"] ["segment ID"=442933696215352080] [2023/07/22 08:26:05.125 +00:00] [INFO] [datacoord/meta.go:300] ["meta update: dropping segment - complete"] ["segment ID"=442933696215352080] [2023/07/22 08:26:05.182 +00:00] [INFO] [datacoord/garbage_collector.go:198] ["scan file to do garbage collection"] [total=0] [valid=0] [missing=0] [re movedKeys="[]"]

please show your code of usage?
My guess is 
1)  you create a collection with TTL(time to leave)
2) you are using some third party connection that drop collection under some cases

**Comment by yanliang567** [comment]
> Sorry sir, ttl is set in my code. I apologize again.
> 
If TTL is set, then the data in the collection will be cleanup as it met the TTL. This is by design. Please do not set TTL if you need the data persist permanently. 

/assign @HantaoCai
