### ISSUE TITLE
Use environment variables in the configuration

### ISSUE THREAD

**Issue by jeffoverflow** [milvus-io/milvus#2587]
**Is your feature request related to a problem? Please describe.**
I want to use `/var/lib/milvus/bin/milvus_server` to start the milvus server. 
Configurable through command-line flags and environment variables. 
Options set on the command line take precedence over those from the environment.

**Comment by ZhifengZhang-CN** [comment]
refer to [etcd Configuration flags](https://etcd.io/docs/v3.2.17/op-guide/configuration/)

**Comment by JinHai-CN** [comment]
Similar issue #3217
