### ISSUE TITLE
[Bug]: Error from server (BadRequest): error when creating "milvus_cluster.yaml": Milvus in version "v1beta1" cannot be handled as a Milvus: strict decoding error: unknown field "spec.components.proxy.grpc"

### ISSUE THREAD

**Issue by Vance0124** [milvus-io/milvus#25894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
# This is a sample to deploy a milvus cluster in milvus-operator's default configurations.
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
  labels:
    app: milvus
spec:
  mode: cluster
  dependencies: {}
  components:
    image: milvusdb/milvus:v2.2.8
    proxy:
      port: 19530
      grpc:
        serverMaxRecvSize: 2147483648   # 2GB
        serverMaxSendSize: 2147483648
        clientMaxRecvSize: 2147483648
        clientMaxSendSize: 2147483648
  config: {}
```

### Current Behavior

I want to use the `kubectl` command to modify the `gRPC` transmission size limit in the proxy, but it tells me that this is an **unknown field**: Error from server (BadRequest): error when creating "milvus_cluster.yaml": Milvus in version "v1beta1" cannot be handled as a Milvus: strict decoding error: unknown field "spec.components.proxy.grpc"

### Expected Behavior

How to solve it? please tell me.

**Comment by haorenfsa** [comment]
@Vance0124 Hi, sry for the delay. It should be configured in `spec.config.proxy.grpc`
For more information check this out: https://github.com/milvus-io/milvus-operator/blob/main/docs/CRD/milvus.md

**Comment by Vance0124** [comment]
> 

OK, thank you~

**Comment by Vance0124** [comment]
> @Vance0124 Hi, sry for the delay. It should be configured in `spec.config.proxy.grpc` For more information check this out: https://github.com/milvus-io/milvus-operator/blob/main/docs/CRD/milvus.md

Ok, thank you~
