### ISSUE TITLE
[Bug]: The GPU configuration has not taken effect!

### ISSUE THREAD

**Issue by Yufei447** [milvus-io/milvus#25898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.11
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I added gpu section in the milvus.yaml while creating index and searching. However, when i tried to write embeddings or searching, it seems that it still used cpu to execute. Is there any way I can do to enable gpu mode?
===========
gpu:
  enable: true
  cache.enable: false
  cache_size: 1GB
  gpu_search_threshold: 1000
  search_devices:
    - gpu0
  build_index_devices:
    - gpu0
========

**Comment by yanliang567** [comment]
GPU is not supported in v2.2.x release. We have a 2.3.0 beta release for GPU support, if you do want to try.

**Comment by Yufei447** [comment]
what's version of this? https://hub.docker.com/r/milvusdb/milvus

**Comment by yanliang567** [comment]
the beta gpu image is here: [v2.3.0-gpu-beta](https://hub.docker.com/layers/milvusdb/milvus/v2.3.0-gpu-beta/images/sha256-b72c2f25bbedc6e475b7e2cb689cc94e37effb21a469aa50183a4b94bf397f33?context=explore)
