### ISSUE TITLE
[Bug]: Insert gets tt delay deny error but the tt delay metrics of datanode do not reach the maxTimeTickDelay config

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#25903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230725-a6808e64
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):   rocksmq 
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.4.0.dev100
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. deploy milvus and config ttProtection and metricInterval:
```
spec:
  components:
    metricInterval: "10s"
  config:
    log:
      level: debug
    quotaAndLimits:
      dml:
        enabled: true
        insertRate:
          collection:
            max: 8
          max: -1
      enabled: true
      limitWriting:
        ttProtection:
          enabled: true
          maxTimeTickDelay: 0.6
```
2. Client concurrent insert and delete and gets tt delay deny error
```
'concurrent_params': {'concurrent_number': 20,
                                                       'during_time': '30m',
                                                       'interval': 60,
                                                       'spawn_rate': None},
                                 'concurrent_tasks': [{'type': 'insert',
                                                       'weight': 5,
                                                       'params': {'nb': 1000,
                                                                  'timeout': 600,
                                                                  'random_id': True,
                                                                  'random_vector': True}},
                                                      {'type': 'delete',
                                                       'weight': 1,
                                                       'params': {'delete_length': 10,
                                                                  'timeout': 600}},
                                                      {'type': 'scene_insert_partition',
                                                       'weight': 4,
                                                       'params': {'ni': 100,
                                                                  'data_size': '1w',
                                                                  'with_flush': False,
                                                                  'timeout': 6000}}]}
```
client first deny error:
![image](https://github.com/milvus-io/milvus/assets/27288593/3a0f57c4-08dc-487e-a483-2091213738ab)

3. server deny log. Notice that client first tt deny error at `09:14:22,307`, but the server first tt deny log at `09:16:10.162`. It's weird.
![image](https://github.com/milvus-io/milvus/assets/27288593/c6f14363-4c24-423e-ad10-e16d6f833a0a)

4. datanode tt delay metrics with **10s** interval. From the picture it can be seen that even the maximum tt delay value does not reach 0.6s. 
![image](https://github.com/milvus-io/milvus/assets/27288593/5d96283a-ec7b-4aec-90cf-736580257cac)

![image](https://github.com/milvus-io/milvus/assets/27288593/4294fb34-eb54-4f98-922c-27a5c1ed016d)

### Expected Behavior

1. It seems that the current grafana metrics indicators have not yet reached the config `maxTimeTickDelay`. Is the insert deny error as expected?
2. Why the server did not print the tt deny log error but the client insert gets deny error first? Is the insert rate limit really calculated according to the datanode's tt delay value?

### Steps To Reproduce

```markdown
- 4am argo wofkflow: https://argo-workflows.zilliz.cc/archived-workflows/qa/ccb358fb-0d82-4b25-a950-6ade2e1c2593?nodeId=master-insert-tt-7

- grafana link: https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=qa-milvus&var-instance=quota-limit-3&var-collection=All&var-app_name=milvus&from=1690275597761&to=1690278851845

- server pods:

quota-limit-3-etcd-0                                              1/1     Running                  0               5d2h
quota-limit-3-milvus-standalone-74d9d487f5-6l9js                  1/1     Running                  0               169m
quota-limit-3-minio-575986b859-l78gm                              1/1     Running                  0               5d2h
```
```


### Milvus Log

_No response_

### Anything else?

_No response_

**Comment by bigsheeper** [comment]
The tt lag monitoring in the DataNode is determined by comparing the consumed tt with the current time `time.Now()`:
https://github.com/milvus-io/milvus/blob/2c6c7749e24d8b1a326c07b1413e6d9389b33d4c/internal/util/flowgraph/input_node.go#L91-L101

And the RootCoord/QuotaCenter performs tt lag checks by comparing tt with `GenerateTSO`:
https://github.com/milvus-io/milvus/blob/2c6c7749e24d8b1a326c07b1413e6d9389b33d4c/internal/rootcoord/quota_center.go#L436-L439

A deviation of approximately hundreds milliseconds between `GenerateTSO` and `time.Now()` is considered within the realm of normalcy. @ThreadDao

**Comment by bigsheeper** [comment]
@ThreadDao time tick delay monitoring in rootCoord is more accurate:
![image](https://github.com/milvus-io/milvus/assets/42060877/32535044-c964-4616-be85-f08ac7033766)
