### ISSUE TITLE
[Feature]:  Expose a count function to count items for a query

### ISSUE THREAD

**Issue by geminigeek** [milvus-io/milvus#25906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Provide a count function that sends only count of the items found of a query result, currently query sends ids, i don't want ids i just want a count

in addition to this  https://milvus.io/api-reference/node/v2.2.x/Data/query.md

### Describe the solution you'd like.

1. it might help in many cases where a queue/process is feeding the data into a collection, to track count of items present
2. it will be good for analytics of a specific meta data field
3. items added in last n minutes / hours

### Anything else? (Additional Context)

reference https://github.com/milvus-io/milvus-sdk-node/issues/208

**Comment by jiaoew1991** [comment]
Hi @geminigeek, We have added the count API in 2.3.0, 2.3.0 is expected to be released in the near future

**Comment by geminigeek** [comment]
excellent, thanks!
