### ISSUE TITLE
[Bug]: search result returning less than "limit":

### ISSUE THREAD

**Issue by Yufei447** [milvus-io/milvus#25918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.11
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I specify the limit parameter for search() to be 100, but result only returns 17. Why is that? How can i get the exactly 100 topk results?

### Expected Behavior

return just the number of result that I specify

**Comment by yanliang567** [comment]
@Yufei447 could you attach the code to reproduce this issue? Also please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @Yufei447 
/unassign

**Comment by Yufei447** [comment]
tried it another time, it returns expected num. Don't know why....
