### ISSUE TITLE
[Bug]: Number of entities does not equal query all ids

### ISSUE THREAD

**Issue by cyrusvahidi** [milvus-io/milvus#25910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I am querying all entities in a collection:

`all = collection.query(expr="id > 0", output_fields=[x.name for x in collection.collection.schema.fields])`

However, the length of `all` does not equal `collection.num_entities`

### Expected Behavior

I expect the number of entities queried to equal `collection.num_entities`. Are they not equal because I have duplicate primary keys?

**Comment by yanliang567** [comment]
collection.num_entities is not precise, especially when there were delete operations. This is limitation for now, and we would offer a feature count(*) to return a precise num entities of a collection in milvus 2.3. Please stay tune.

/assign @cyrusvahidi 
/unassign

**Comment by hakan458** [comment]
@cyrusvahidi I have also seen this myself when there are duplicate primary keys, yes 
Query function de-duplicates when returning results so you only get one record per-primary-key, but num_entities seems to include duplicates

**Comment by vidda13** [comment]
I still see this issue in 2.4.3 and also tried to do print num_entities right after flush() but don't see the correct count.

**Comment by yanliang567** [comment]
if you have delete or upsert operations, please try query(expr='', output_fields=["count(*)"]) to get the actual number of entities.
