### ISSUE TITLE
[Bug]: QueryNode metric error

### ISSUE THREAD

**Issue by weiliu1031** [milvus-io/milvus#25927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

<img width="625" alt="img_v2_dc52cb70-0bd3-46ea-a18c-0296cc4851fg" src="https://github.com/milvus-io/milvus/assets/108661493/28e928e3-5bb2-4c40-8cfb-79491d533d11">

**Comment by congqixia** [comment]
Introduced by 25849
The reason was mq msgstream msgpack Begin/EndTs not set
Patch shall be #25924
FYI
@weiliu1031
