### ISSUE TITLE
[Bug]: milvus-minio  sbnormal disk usage

### ISSUE THREAD

**Issue by QAQwaitme** [milvus-io/milvus#25921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.11
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.5
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When the data volume is 25 million, each of the four minio nodes occupies 100G of disk space; Then when the data volume reached 60 million, each of the four mini nodes occupied 815GB of disk space, more than doubling the data volume, but the disk space occupied 8 times more

### Milvus Log

Here is log of minio ,for more logs ：https://pan.baidu.com/s/1Qg5DBcH4DLgJvSV0gHCixA?pwd=npcx 
secret：npcx 

API: SYSTEM()
Time: 17:51:12 UTC 07/25/2023
DeploymentID: 7ce0f0a8-de61-4d66-b70e-da393851c0db
Error: write tcp 192.168.199.199:9000->192.168.125.199:33314: write: broken pipe at Buf (msgp.errWrapped)
       3: internal/logger/logger.go:258:logger.LogIf()
       2: cmd/storage-rest-server.go:541:cmd.(*storageRESTServer).ReadXLHandler()
       1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()

API: SYSTEM()
Time: 17:58:45 UTC 07/25/2023
DeploymentID: 7ce0f0a8-de61-4d66-b70e-da393851c0db
Error: write tcp 192.168.199.199:9000->192.168.88.136:56414: write: broken pipe at Buf (msgp.errWrapped)
       3: internal/logger/logger.go:258:logger.LogIf()
       2: cmd/storage-rest-server.go:541:cmd.(*storageRESTServer).ReadXLHandler()
       1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()

API: SYSTEM()
Time: 17:58:46 UTC 07/25/2023
DeploymentID: 7ce0f0a8-de61-4d66-b70e-da393851c0db
Error: write tcp 192.168.199.199:9000->192.168.88.136:56486: write: broken pipe at Buf (msgp.errWrapped)
       3: internal/logger/logger.go:258:logger.LogIf()
       2: cmd/storage-rest-server.go:541:cmd.(*storageRESTServer).ReadXLHandler()
       1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()

API: SYSTEM()
Time: 17:58:46 UTC 07/25/2023
DeploymentID: 7ce0f0a8-de61-4d66-b70e-da393851c0db
Error: write tcp 192.168.199.199:9000->192.168.125.199:34938: write: broken pipe at Buf (msgp.errWrapped)
       3: internal/logger/logger.go:258:logger.LogIf()
       2: cmd/storage-rest-server.go:541:cmd.(*storageRESTServer).ReadXLHandler()
       1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()

API: SYSTEM()
Time: 18:10:45 UTC 07/25/2023
DeploymentID: 7ce0f0a8-de61-4d66-b70e-da393851c0db
Error: write tcp 192.168.199.199:9000->192.168.88.136:33578: write: broken pipe at Buf (msgp.errWrapped)
       3: internal/logger/logger.go:258:logger.LogIf()
       2: cmd/storage-rest-server.go:541:cmd.(*storageRESTServer).ReadXLHandler()
       1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()

API: SYSTEM()
Time: 18:32:17 UTC 07/25/2023
DeploymentID: 7ce0f0a8-de61-4d66-b70e-da393851c0db
Error: write tcp 192.168.199.199:9000->192.168.125.199:46178: write: broken pipe at Buf (msgp.errWrapped)
       3: internal/logger/logger.go:258:logger.LogIf()
       2: cmd/storage-rest-server.go:541:cmd.(*storageRESTServer).ReadXLHandler()
       1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()

API: SYSTEM()
Time: 18:32:17 UTC 07/25/2023
DeploymentID: 7ce0f0a8-de61-4d66-b70e-da393851c0db
Error: write tcp 192.168.199.199:9000->192.168.88.136:38056: write: broken pipe at Buf (msgp.errWrapped)
       3: internal/logger/logger.go:258:logger.LogIf()
       2: cmd/storage-rest-server.go:541:cmd.(*storageRESTServer).ReadXLHandler()
       1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()

API: SYSTEM()
Time: 20:57:12 UTC 07/25/2023
DeploymentID: 7ce0f0a8-de61-4d66-b70e-da393851c0db
Error: write tcp 192.168.199.199:9000->192.168.88.136:60062: write: broken pipe at Buf (msgp.errWrapped)
       3: internal/logger/logger.go:258:logger.LogIf()
       2: cmd/storage-rest-server.go:541:cmd.(*storageRESTServer).ReadXLHandler()
       1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()

API: SYSTEM()
Time: 21:12:15 UTC 07/25/2023
DeploymentID: 7ce0f0a8-de61-4d66-b70e-da393851c0db
Error: write tcp 192.168.199.199:9000->192.168.88.136:40104: write: broken pipe at Buf (msgp.errWrapped)
       3: internal/logger/logger.go:258:logger.LogIf()
       2: cmd/storage-rest-server.go:541:cmd.(*storageRESTServer).ReadXLHandler()
       1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()

API: SYSTEM()
Time: 21:12:15 UTC 07/25/2023
DeploymentID: 7ce0f0a8-de61-4d66-b70e-da393851c0db
Error: write tcp 192.168.199.199:9000->192.168.88.136:40090: write: broken pipe at Buf (msgp.errWrapped)
       3: internal/logger/logger.go:258:logger.LogIf()
       2: cmd/storage-rest-server.go:541:cmd.(*storageRESTServer).ReadXLHandler()
       1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()

API: SYSTEM()
Time: 01:28:55 UTC 07/26/2023
DeploymentID: 7ce0f0a8-de61-4d66-b70e-da393851c0db
Error: write tcp 192.168.199.199:9000->192.168.88.136:47548: write: broken pipe at Buf (msgp.errWrapped)
       3: internal/logger/logger.go:258:logger.LogIf()
       2: cmd/storage-rest-server.go:541:cmd.(*storageRESTServer).ReadXLHandler()
       1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()

API: SYSTEM()
Time: 01:29:10 UTC 07/26/2023
DeploymentID: 7ce0f0a8-de61-4d66-b70e-da393851c0db
Error: write tcp 192.168.199.199:9000->192.168.125.199:47576: write: broken pipe at Buf (msgp.errWrapped)
       3: internal/logger/logger.go:258:logger.LogIf()
       2: cmd/storage-rest-server.go:541:cmd.(*storageRESTServer).ReadXLHandler()
       1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()

**Comment by yanliang567** [comment]
@QAQwaitme As you inserted more vectors, Milvus generate more segments, and these segments would be compacted into bigger segments. then the small segments will be cleanup in disk in next GC operation, which by default occurs in 24 hours.
so could you double check the minio disk in 24 hours ?

/assign @QAQwaitme 
/unassign

**Comment by QAQwaitme** [comment]
> @QAQwaitme As you inserted more vectors, Milvus generate more segments, and these segments would be compacted into bigger segments. then the small segments will be cleanup in disk in next GC operation, which by default occurs in 24 hours. so could you double check the minio disk in 24 hours ?
> 
> /assign @QAQwaitme /unassign

It's been 24 hours now，the  disk using rised fro 1.1TB

**Comment by yanliang567** [comment]
related issue: #25955

**Comment by yanliang567** [comment]
close this issue as it is tracked by #25955
