### ISSUE TITLE
How to specify version installation

### ISSUE THREAD

**Issue by Zzt1993** [milvus-io/milvus#25935]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/95836616/8df0531a-1d1b-4c56-8e6c-96393f8358aa)

I am using the installation method shown in the above figure, and the installed version is 2.2.11. I want to install version 2.2.10. May I know which yaml parameters need to be modified

**Comment by yanliang567** [comment]
@Zzt1993 you can just specify the milvus image tag in the milvus yaml file. More info here: https://github.com/milvus-io/milvus-operator
```
spec:
  # Omit other fields ...
  components:
   image: milvusdb/milvus:v2.2.10
```

BTW, Milvus 2.2.12 was released early this week. I suggest you run the latest release, which fixed many issues.

**Comment by Zzt1993** [comment]
Thank you. I can understand the configuration you mentioned, but I don't know which file to add it to

**Comment by Zzt1993** [comment]
![image](https://github.com/milvus-io/milvus/assets/95836616/782dace4-8ed7-44bf-818e-da4fb06b9b3d)

**Comment by Zzt1993** [comment]
![image](https://github.com/milvus-io/milvus/assets/95836616/fb581a4f-e0da-4ac8-8d7b-43b5f48c4e4b)
May I ask if this is the case with you

**Comment by yanliang567** [comment]
yes, try it. 
here listed more samples: https://github.com/milvus-io/milvus-operator/tree/main/config/samples
