### ISSUE TITLE
[Bug]: 不使用docker-compose，standalone单节点启动报错

### ISSUE THREAD

**Issue by kxytalk** [milvus-io/milvus#25947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.12
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): kafka    
- SDK version(e.g. pymilvus v2.0.0rc2): milvus-sdk-java 2.2.x
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 16C/32G
- GPU: 无
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/68372769/edc0dc6e-99dc-436d-bce6-d585796ccee1)
<img width="780" alt="image" src="https://github.com/milvus-io/milvus/assets/68372769/0eee6931-ca4e-4938-8d65-1003f5e64408">

我们只有容器化的环境，没有任何命令行的操作界面，只能通过编写k8s yaml文件去拉起服务，
现在需要启动一个单节点，发现报错

### Steps To Reproduce

```markdown
![image](https://github.com/milvus-io/milvus/assets/68372769/edc0dc6e-99dc-436d-bce6-d585796ccee1)
```

### Milvus Log

<img width="780" alt="image" src="https://github.com/milvus-io/milvus/assets/68372769/0eee6931-ca4e-4938-8d65-1003f5e64408">

**Comment by yanliang567** [comment]
/assign @locustbaby 
could you please help on this?
/unassign

**Comment by locustbaby** [comment]
1. Can you install milvus by helm/operator?
2. Can you share the yaml you using now?  and all the logs of milvus will help.

**Comment by kxytalk** [comment]
> 1. Can you install milvus by helm/operator?
> 2. Can you share the yaml you using now?  and all the logs of milvus will help.

1、不能使用 helm/operator 安装；
2、第一个是启动脚本，第二个是日志文件（日志太多，被系统截取，有部分获取不到了）

[Deployment.yaml.txt](https://github.com/milvus-io/milvus/files/12181686/Deployment.yaml.txt)
[logs-from-milvus-in-milvus-b5d5d76bc-ld8qk.txt](https://github.com/milvus-io/milvus/files/12181688/logs-from-milvus-in-milvus-b5d5d76bc-ld8qk.txt)

**Comment by kxytalk** [comment]
> 1. 您可以通过舵手/操作员安装 milvus 吗？
> 2. 你能分享你现在使用的yaml吗？米尔武斯的所有日志都会有所帮助。

有结果吗

**Comment by locustbaby** [comment]
日志没有太多信息，看你的yaml 部署的有问题，metrics的port没有暴露
你可以用helm  dry run 生成deployment等配置，参考更改
