### ISSUE TITLE
[Enhancement]: coodinator节点开启HA后，只有一个节点正常，另外一个节点日志报错，连接不上rootCoodinator or queryCoodinator

### ISSUE THREAD

**Issue by herozeng** [milvus-io/milvus#25943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

[Enhancement]: coodinator节点开启HA后，只有一个节点正常，另外一个节点日志报错，连接不上rootCoodinator or queryCoodinator, 经过多次手动重启后才正常看到standby日志

**Comment by yanliang567** [comment]
@herozeng thanks for your feedback. Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @herozeng
