### ISSUE TITLE
[Bug]: MILVUS GETTING DIFFERENT SEARCHING RESULT FROM FAISS

### ISSUE THREAD

**Issue by Yufei447** [milvus-io/milvus#25941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Now I want to compare the searching result returning by FAISS and milvus. I want to build the exactly same index and use same parameter to search.

Using FAISS, I create index like this:
quantizer = faiss.IndexFlatIP(DIMENSION)
index = faiss.IndexIVFFlat(quantizer, DIMENSION, NLIST, faiss.METRIC_INNER_PRODUCT)

Before search, I normalize the vector to be search:
faiss.normalize_L2(vectors)

Using Milvus, I create index like this:
index = {"index_type":"IVF_FLAT", "metric_type": "IP", "params": {"nlist": NLIST}}

The search params I specify is like this:
search_params = {"metric_type": "IP", "params": {"nprobe": NPROBE}}

I have 3 questions:

FAISS can build quantizer, can milvus build quantizer like FAISS? If not, is there any performance difference?
FAISS has function normalize_L2() to normalize vectors, do milvus has function which can achieve same function?
Is the index I build using FAISS the same as I build with Milvus? If so, why is there such a big difference between the result returned by Milvus and the result returned by FAISS?
For the result returning by milvus, there is a field called "distance". But I specify the search metric to be IP(inner product), why the field is distance not similarity?

**Comment by cydrain** [comment]
Hi @Yufei447 
Q1: FAISS can build quantizer, can milvus build quantizer like FAISS? If not, is there any performance difference?
Answer: you don't need build quantizer in Milvus, you just need tell Milvus which index type you want and the index parameters.

Q2: FAISS has function normalize_L2() to normalize vectors, do milvus has function which can achieve same function?
Answer: you can select the metric type "COSINE", it will do normalization firstly, then do IP calculation

Q3: Is the index I build using FAISS the same as I build with Milvus? If so, why is there such a big difference between the result returned by Milvus and the result returned by FAISS?
For the result returning by milvus, there is a field called "distance". But I specify the search metric to be IP(inner product), why the field is distance not similarity?
Answer: 
you get different result between Milvus and Faiss, one possibility is you did not do normalization when using Milvus; another possibility is Milvus create 2 or more segments while faiss only create 1 segment, so Milvus will return results with higher recall rate. Actually, you need not compare the result between Milvus and Faiss one by one, you can compare their recall rate.
Milvus' result always has 2 output fields, one is "labels", the other one is "distances". The "similarity" you said, I think you mean "score", Milvus does not support it now.
