### ISSUE TITLE
High latency when querying vectors

### ISSUE THREAD

**Issue by rahul2393** [milvus-io/milvus#2594]
**Describe the bug**
Please help to find why latency is high at 90RPS

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**
The requirement is to gain high speed in querying vectors, currently latency is more than 5sec at 90RPS

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
Ubuntu Ubuntu 18.04.4 LTS, 16core CPU, 32GB RAM
- Method of installation (Docker, or from source)
From source
- Milvus version (v0.3.1, or v0.4.0)
v0.10.0
- Milvus configuration (Settings you made in `server_config.yaml`)
same as server_config template in code
```
cache:
  cache_size: 25GB
  insert_buffer_size: 1GB
  preload_collection: 
```
**Screenshots**
![Screenshot 2020-06-17 at 8 38 49 PM](https://user-images.githubusercontent.com/18293335/84921357-fdc68f00-b0e1-11ea-9663-ef32f399c2b0.png)

**Additional context**
30 million vectors with 128 dimension were indexed for load test with index type IVFPQ

**Comment by tinkerlin** [comment]
RPS means?

**Comment by rahul2393** [comment]
Request per second

**Comment by rahul2393** [comment]
```
{
   "collections":[
      {
         "collection_name":"product",
         "count":30000000,
         "dimension":128,
         "index":"IVFPQ",
         "index_file_size":1024,
         "index_params":"{\"m\":16,\"nlist\":1024}",
         "metric_type":"L2"
      }
   ],
   "count":1
}
```
Above is the collection configuration, it created 13 segments on machine with just to add more to info

**Comment by yhmo** [comment]
I just do some test on my machine(12 core cpu):
- milvus 0.10.0-cpu-d061620-5f3c00  from [hub.docker.com](hub.docker.com)
- 30M vectors, dimension=128
- IVF_PQ, m=16, nlist=1024, L2
- index_file_size=1024MB, 14 segments
- search 1 vector, topk=100, nprobe=8, time cost: about 20ms
- search 10 vector, topk=100, nprobe=8, time cost: about 100ms

**Comment by yhmo** [comment]
@rahul2393 
Could you send me the log of milvus to me?
by this steps:
1. restart milvus container
2. perform twice search action
3. compress the log files under /milvus/logs and send to yihua.mo@zilliz.com

**Comment by rahul2393** [comment]
Hi @yhmo have sent you the zip file of logs

**Comment by yhmo** [comment]
In 0.10.1 branch, we optimize the search combine strategy.
Now user can specify max nq of combined request to balance single request latency and QPS.
Use client SDK to specify max nq of combined request:
python SDK:
`MILVUS.set_config("engine_config", "search_combine_nq", "32")`
restful API:
`curl -X PUT "http://127.0.0.1:19121/system/task" -H "accept: application/json" -d "{\"config\": {\"engine_config\": {\"search_combine_nq\":\"32\"}}}"`

**Comment by rahul2393** [comment]
@yhmo thanks

**Comment by yhmo** [comment]
@rahul2393 The resful api usage should be:
`curl -X PUT "http://127.0.0.1:19121/system/config" -H "accept: application/json" -d "{\"engine_config\": {\"search_combine_nq\": \"32\"}}"`
