### ISSUE TITLE
[Bug]: With TTL used,we got unusual disk occupation

### ISSUE THREAD

**Issue by QAQwaitme** [milvus-io/milvus#25955]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.3
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

With same profile ,I have start Milvus 2.2.3 for twice. First time I start cluster with TTL , then it comes a unusual disk occupation for 4  million vector occupy 100G disk space on each MinIO (we get four for it ). The second time  without TTL ,50 milion vector only use 15G disk space for on MinIO. Are there  something wrong with using TTL to delete data automatic?
One more thing , we have used Milvus 2.2.8, 2.2.10,2.2.11 with TTL ,they all got unusual disk occupation ,30 miliion vector used almost 1 TB disk space. Maybe there's really a problem with TTL?

**Comment by yanliang567** [comment]
good catch. We will try to reproduce it in house. 
@binbinlv could you please help on this?

/assign @binbinlv 
/unassign

**Comment by binbinlv** [comment]
> good catch. We will try to reproduce it in house. @binbinlv could you please help on this?
> 
> /assign @binbinlv /unassign

OK, working.

**Comment by yanliang567** [comment]
@QAQwaitme we are trying to reproduce it in house. some quick questions to help us make it:
1. did you run the same scripts(the only difference is disable/enable ttl) when insert 4m and 50m vectors?
2. what is the dim for vectors? any scalar fields, such as varchar?
3. what value did you set for the ttl?
4. what value did you set for gc?
![image](https://github.com/milvus-io/milvus/assets/82361606/85fba298-8be5-459e-b4d0-1c6c7764778b)
5. when checking the minio disk usage, how long did you wait after inserting completed ?

**Comment by yanliang567** [comment]
it would be a great help if you could share some code snippets about inserting. @QAQwaitme

**Comment by QAQwaitme** [comment]
1.Yes,we  used the same scripts to insert vectors,only difference is enable/disable TTL
2.128 dim vectors, with scalar fields like vachar ,int64,int32
3.With different collection ,it got ttl value for 45days or 20 days.
4.I havent seen the configuration in your screenshot, its not in milvus_manifest.yaml?
5.with TTL ,after 8 hours we checked the minio disk, its rised highly 


Here is some of my insert code snippets ,with java SDK:
List<String>  idList = new LinkedList<>();
List<String> nameList= new LinkedList<>();
List<List<Float>> featureList = new LinkedList<>();
List<InsertParam.Field> fields = new ArrayList<>();
idList .add("9564b8ab4eab43a");
featureList.add(feature);
nameList.add("name");
fields.add(new InsertParam.Field("id",idList ));
fields.add(new InsertParam.Field("feature",featureList));
fields.add(new InsertParam.Field("name",nameList));
milvusServiceClient.insert(InsertParam.newBuilder()
        .withCollectionName(collection).withPartitionName(partition)
        .withFields(fields)
        .build());

**Comment by yanliang567** [comment]
> 1.Yes,we used the same scripts to insert vectors,only difference is enable/disable TTL 2.128 dim vectors, with scalar fields like vachar ,int64,int32 3.With different collection ,it got ttl value for 45days or 20 days. 4.I havent seen the configuration in your screenshot, its not in milvus_manifest.yaml? 5.with TTL ,after 8 hours we checked the minio disk, its rised highly
> 
> Here is some of my insert code snippets ,with java SDK: List idList = new LinkedList<>(); List nameList= new LinkedList<>(); List<List> featureList = new LinkedList<>(); List<InsertParam.Field> fields = new ArrayList<>(); idList .add("9564b8ab4eab43a"); featureList.add(feature); nameList.add("name"); fields.add(new InsertParam.Field("id",idList )); fields.add(new InsertParam.Field("feature",featureList)); fields.add(new InsertParam.Field("name",nameList)); milvusServiceClient.insert(InsertParam.newBuilder() .withCollectionName(collection).withPartitionName(partition) .withFields(fields) .build());

did you manually call flush() after every insert request?

**Comment by QAQwaitme** [comment]
never do that

**Comment by binbinlv** [comment]
with TTL ,after 8 hours we checked the minio disk, its rised highly

@QAQwaitme 
here which you mean is after you insert  4 million vectors, at the beginning it occupies normal size, and do nothing, then it rised highly to 100G util 8 hours later?

Or it just occupy 100G at the beginning when you inserted 4 million vectors?

**Comment by QAQwaitme** [comment]
> with TTL ,after 8 hours we checked the minio disk, its rised highly
> 
> @QAQwaitme here which you mean is after you insert 4 million vectors, at the beginning it occupies normal size, and do nothing, then it rised highly to 100G util 8 hours later?
> 
> Or it just occupy 100G at the beginning when you inserted 4 million vectors?

it occupy 100G after I hava inserted 4 milion vectors ,to reduce the pressure of milvus, i slowly inserted 4 milion vectors in 8 hours, then it happend.
for now ,  i have inserted 100 million vectors in 48 hours ,and it only used 30G on each minio node

**Comment by binbinlv** [comment]
Reproduced this issue using milvus v2.1.11, but did not reproduce in the latest version: v2.1.12

@QAQwaitme hello, I see you just try 2.2.8, 2.2.10, and 2.2.11. It seems you did not try v2.1.12. Could you please try the lastest version: v2.1.12?

Test details:
inserted 5 million,  dim=256

V2.1.11:
Without ttl: 12.9G (not increase in an hour of measurement)
![4TYKFv21f3](https://github.com/milvus-io/milvus/assets/83755740/d0d7d8f2-401c-4f89-a62e-ef73b19a6301)

With ttl (set ttl as 45 days): increasing as the time goes, 10G+, 20G+, 30G+, 40G+...
![bIjYT6OQgO](https://github.com/milvus-io/milvus/assets/83755740/15ceccd0-0416-446b-82e7-5d733362d548)
![bIjYT6OQgO](https://github.com/milvus-io/milvus/assets/83755740/2861630f-2568-4562-b739-e939e60ac301)



V2.1.12: 
Without ttl: 4.8G (not increase in an hour of measurement)
![1hexzYdctr](https://github.com/milvus-io/milvus/assets/83755740/ecbcad50-0a6a-42c8-a3ab-b88264fb62c5)

With ttl (set ttl as 45 days): 4.8G  (not increase in an hour of measurement)
![qbQLPgfiuJ](https://github.com/milvus-io/milvus/assets/83755740/e8109403-9080-4210-bccb-19608d17773a)

**Comment by xiaofan-luan** [comment]
> 

Thanks for the test!
This seems to be reasonable since we changed gc policy in 2.2.12

**Comment by QAQwaitme** [comment]
> Reproduced this issue using milvus v2.2.11, but did not reproduce in the latest version: v2.2.12
> 
> @QAQwaitme hello, I see you just try 2.2.8, 2.2.10, and 2.2.11. It seems you did not try v2.1.12. Could you please try the lastest version: v2.1.12? In my trials, this issue was fixed by v2.1.12.
> 
> Test details: inserted 5 million, dim=256
> 
> v2.2.11: Without ttl: 12.9G (not increase in an hour of measurement) ![4TYKFv21f3](https://user-images.githubusercontent.com/83755740/256797261-d0d7d8f2-401c-4f89-a62e-ef73b19a6301.jpg)
> 
> With ttl (set ttl as 45 days): increasing as the time goes, 10G+, 20G+, 30G+, 40G+... ![bIjYT6OQgO](https://user-images.githubusercontent.com/83755740/256800261-15ceccd0-0416-446b-82e7-5d733362d548.jpg) ![lhRUdm8IPy](https://user-images.githubusercontent.com/83755740/256802266-bbb68929-4348-464b-b07e-cc011f693fb5.jpg)
> 
> v2.2.12: Without ttl: 4.8G (not increase in an hour of measurement) ![1hexzYdctr](https://user-images.githubusercontent.com/83755740/256797417-ecbcad50-0a6a-42c8-a3ab-b88264fb62c5.jpg)
> 
> With ttl (set ttl as 45 days): 4.8G (not increase in an hour of measurement) ![qbQLPgfiuJ](https://user-images.githubusercontent.com/83755740/256797565-e8109403-9080-4210-bccb-19608d17773a.jpg)

Thanks for that! The latest version is 2.2.11 when we test , I will try for 2.2.12, about 2 days i can get a conclusion

**Comment by xiaofan-luan** [comment]
> Reproduced this issue using milvus v2.2.11, but did not reproduce in the latest version: v2.2.12
> 
> @QAQwaitme hello, I see you just try 2.2.8, 2.2.10, and 2.2.11. It seems you did not try v2.1.12. Could you please try the lastest version: v2.1.12? In my trials, this issue was fixed by v2.1.12.
> 
> Test details: inserted 5 million, dim=256
> 
> v2.2.11: Without ttl: 12.9G (not increase in an hour of measurement) ![4TYKFv21f3](https://user-images.githubusercontent.com/83755740/256797261-d0d7d8f2-401c-4f89-a62e-ef73b19a6301.jpg)
> 
> With ttl (set ttl as 45 days): increasing as the time goes, 10G+, 20G+, 30G+, 40G+... ![bIjYT6OQgO](https://user-images.githubusercontent.com/83755740/256800261-15ceccd0-0416-446b-82e7-5d733362d548.jpg) ![lhRUdm8IPy](https://user-images.githubusercontent.com/83755740/256802266-bbb68929-4348-464b-b07e-cc011f693fb5.jpg)
> 
> v2.2.12: Without ttl: 4.8G (not increase in an hour of measurement) ![1hexzYdctr](https://user-images.githubusercontent.com/83755740/256797417-ecbcad50-0a6a-42c8-a3ab-b88264fb62c5.jpg)
> 
> With ttl (set ttl as 45 days): 4.8G (not increase in an hour of measurement) ![qbQLPgfiuJ](https://user-images.githubusercontent.com/83755740/256797565-e8109403-9080-4210-bccb-19608d17773a.jpg)

But it still seems that we are doing many compactions during the TTL (Which may lead to extra index build cost). It there a log I can take a look?

**Comment by QAQwaitme** [comment]
@xiaofan-luan 
here is the whole logs of the cluster for 2.2.11, its too large you may have to dowload it :
https://pan.baidu.com/s/1Qg5DBcH4DLgJvSV0gHCixA?pwd=npcx
secret：npcx

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan here is the whole logs of the cluster for 2.2.11, its too large you may have to dowload it : https://pan.baidu.com/s/1Qg5DBcH4DLgJvSV0gHCixA?pwd=npcx secret：npcx

Great, thanks for the feedback.
Let's see what we can do to improve

**Comment by yanliang567** [comment]
I doubt one of reason could be GC does not cleanup the dropped segments if TTL does not expired. in my test of master image, I can see many dropped segments lasts for hours(though the gc  interval and dropTolerance is 1 hour) in birdwatcher backups.

/assign @jiaoew1991

**Comment by yanliang567** [comment]
seems that GC is working, but the compaction keeps working.
![image](https://github.com/milvus-io/milvus/assets/82361606/ea2bd4ab-f334-4a13-ab73-5ca7a26de299)

**Comment by xiaofan-luan** [comment]
> seems that GC is working, but the compaction keeps working. ![image](https://user-images.githubusercontent.com/82361606/256964076-ea2bd4ab-f334-4a13-ab73-5ca7a26de299.png)

That's what I'm saying. Compaction due to expired data is happened too frequent, causing memory usage going up.

**Comment by yanliang567** [comment]
if TTL disabled, the minio disk uage is okay.
![image](https://github.com/milvus-io/milvus/assets/82361606/0022f5a0-5833-4b4b-bbd7-5394d9736751)
if TTL is enabled and not building index, the minio usage is ok as well
![image](https://github.com/milvus-io/milvus/assets/82361606/837f137f-2b6a-4cab-b2b6-ac10df9ed4a1)

**Comment by QAQwaitme** [comment]
I have seen your words,is there somthing wrong with 2.2.12? Considering it will cost  a lot for update 2.2.3 to 2.2.12 ,should I waiting for the fix of the problem or what ?

**Comment by yanliang567** [comment]
The minio disk retrun to 0B after 24+hours(the ttl was  set 24h)
![image](https://github.com/milvus-io/milvus/assets/82361606/fbb8dead-5e54-4815-a6ce-bd6c4b1b1cce)

**Comment by wayblink** [comment]
This is a bug. 

Compacted segments didn't update binlog's timestampFrom, timestampTo field(default 0). Cause compaction_trigger always think compacted segment has too many expired data, needs a single compaction. So segments will be compacted endlessly until meet collection TTL. During this time, a lot of segment copys are generated. 

Preparing fix PR

**Comment by wayblink** [comment]
@yanliang567 @binbinlv PRs ready, we can verify this now.

**Comment by yanliang567** [comment]
verified on 2.2.0-20230808-4d4e8cd8
![image](https://github.com/milvus-io/milvus/assets/82361606/65f03c93-d77a-4c88-b2b9-0eb3cd5c0668)

**Comment by yanliang567** [comment]
verified on master-20230808-21eeb37c as well

**Comment by xiaofan-luan** [comment]
good to know
