### ISSUE TITLE
[Bug]:  We need to set enableActiveStandby to true so that the search is not interrupted during the upgrade.

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#25957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):cluster 
- MQ type(rocksmq, pulsar or kafka):     
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

We want to set the `enableActiveStandby` value for rootCoord, dataCoord, queryCoord, and indexCoord to `true` by default.

The advantage of this is that there will be no search failures when users upgrade, and milvus will not be interrupted.

### Anything else?

According to our experiments, when upgrading without enableActiveStandby turned on, it takes 5 seconds to start the new rootcoord

**Comment by yanliang567** [comment]
this config item is for milvus-operator rolling upgrade. I suggest we enable it in 2.3.0 by default. 

/assign @xiaofan-luan @haorenfsa  @LoveEachDay 
any comments?
