### ISSUE TITLE
How to use azure blob to save message instead of minio ? How to write yaml file to make this work?  Our team spare no effort to do this but it still does not work.

### ISSUE THREAD

**Issue by psmgogogo** [milvus-io/milvus#25960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
azuregateway:

  enabled: true




externalS3:

  enabled: true

  host: "pptest1124.blob.core.windows.net"

  port: 443

  accessKey: "pptest1124"

  secretKey: "***"

  useSSL: true

  bucketName: "milvus"

  rootPath: "/milvus"

  useIAM: false

  cloudProvider: "aws"

  iamEndpoint: ""
```

### Current Behavior

Can not connect azure blob.

### Expected Behavior

save message to azure blob 

### Steps To Reproduce

```markdown
just please tell me how to save messsage to azure blob
```

### Milvus Log

...

### Anything else?

.......

**Comment by yanliang567** [comment]
I don't think we have supported azure blob for now. But we are working on it.
/assign @jaime0815 
any updates?
/unassign

**Comment by psmgogogo** [comment]
> 
https://milvus.io/docs/v2.0.x/azure.md#Deploy-Milvus-on-Azure-with-AKS this docs said milvus can using azure blob storage

**Comment by yanliang567** [comment]
> > 
> 
> https://milvus.io/docs/v2.0.x/azure.md#Deploy-Milvus-on-Azure-with-AKS this docs said milvus can using azure blob storage

it used a minio.azuregateway to connect, but minio does not support the gateway any more. Now we are developing a native support to azure blob.

**Comment by psmgogogo** [comment]
> 

也就是说现在没办法用azure blob来存储数据的是吧

**Comment by yanliang567** [comment]
@jaime0815 any suggestion?

**Comment by psmgogogo** [comment]
> > > 
> > 
> > 
> > https://milvus.io/docs/v2.0.x/azure.md#Deploy-Milvus-on-Azure-with-AKS this docs said milvus can using azure blob storage
> 
> it used a minio.azuregateway to connect, but minio does not support the gateway any more. Now we are developing a native support to azure blob.

So it means that there is no way to use Azure Blob to store data now, r

> > > 
> > 
> > 
> > https://milvus.io/docs/v2.0.x/azure.md#Deploy-Milvus-on-Azure-with-AKS this docs said milvus can using azure blob storage
> 
> it used a minio.azuregateway to connect, but minio does not support the gateway any more. Now we are developing a native support to azure blob.

Thank you for response，Does it mean there is no way to storage message on azure blob with milvus?  respect!

**Comment by psmgogogo** [comment]
> @jaime0815 any suggestion?

 Our team want to use milvus and stoarge message in azure blob any suggestion? thank you

**Comment by jaime0815** [comment]
> > @jaime0815 any suggestion?
> 
> Our team want to use milvus and stoarge message in azure blob any suggestion? thank you

@PowderLi works on support azure blob storage.
related to #22276

**Comment by PowderLi** [comment]
related to #24944
