### ISSUE TITLE
[Bug]: I am trying to install the milvus standalone using docker 

### ISSUE THREAD

**Issue by neel17** [milvus-io/milvus#25962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.12
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: ARM 
- GPU: None
- Others:
```

### Current Behavior

```   ! standalone (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s```

### Steps To Reproduce

```markdown
- wget https://github.com/milvus-io/milvus/releases/download/v2.2.12/milvus-standalone-docker-compose.yml -O docker-compose.yml

- docker compose up -d
```

**Comment by yanliang567** [comment]
Milvus has not supported ARM yet.  But we are working on it. Please try x86 CPU for now. @neel17
