### ISSUE TITLE
[Bug]: Milvus is not able to load collection after etcd disaster and snapshot restore 

### ISSUE THREAD

**Issue by punkerpunker** [milvus-io/milvus#25999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.9
- Deployment mode(standalone or cluster): Cluster
- MQ type(rocksmq, pulsar or kafka): Pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.9
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: -
- GPU: -
- Others: -
```

### Current Behavior

Hi! I had a disaster with Milvus etcd cluster and I had to restore it from snapshot. etcd restored and started successfully, however, none of the existing collections are able to load into memory. 

I am getting this errors on query-node: 

```
[2023/07/28 11:17:53.711 +00:00] [ERROR] [querynode/segment_loader.go:205] ["load segment failed when load data into memory"] [collectionID=442197531118847347] [segmentType=Sealed] [partitionID=442197531118847348] [segmentID=442197531120064516] [error="[UnexpectedError] Error:GetObjectSize:  No response body."] [stack="github.com/milvus-io/milvus/internal/querynode.(*segmentLoader).LoadSegment.func3\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/segment_loader.go:205\ngithub.com/milvus-io/milvus/internal/util/funcutil.ProcessFuncParallel.func3\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/parallel.go:83"]
[2023/07/28 11:17:53.712 +00:00] [ERROR] [funcutil/parallel.go:85] [loadSegmentFunc] [error="[UnexpectedError] Error:GetObjectSize:  No response body."] [idx=0] [stack="github.com/milvus-io/milvus/internal/util/funcutil.ProcessFuncParallel.func3\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/parallel.go:85"]
```

I was thinking that my data might be corrupted because of the disaster in etcd. I was trying to remove shouting segments from etcd using `birdwatcher`, but each time I am getting a same error on the new segment until I run out of segments. Anyone experienced this or at least can help me finding what is possibly going wrong there?

### Expected Behavior

I was expecting that Milvus would work with a restored etcd cluster

### Steps To Reproduce

```markdown
1. Start cluster-mode Milvus
2. Create a collection
3. Make a snapshot of etcd
4. Kill etcd
5. Restore etcd from a snapshot
6. Restart Milvus
```

**Comment by yanliang567** [comment]
I think Milvus will check the metadata consistency with etcd, mq and minio. So i don't think it would working,  if only restore the etcd snapshot.
/assign @jiaoew1991 
any comments?

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version: 2.2.9
> - Deployment mode(standalone or cluster): Cluster
> - MQ type(rocksmq, pulsar or kafka): Pulsar
> - SDK version(e.g. pymilvus v2.0.0rc2): 2.2.9
> - OS(Ubuntu or CentOS): CentOS
> - CPU/Memory: -
> - GPU: -
> - Others: -
> ```
> 
> ### Current Behavior
> Hi! I had a disaster with Milvus etcd cluster and I had to restore it from snapshot. etcd restored and started successfully, however, none of the existing collections are able to load into memory.
> 
> I am getting this errors on query-node:
> 
> ```
> [2023/07/28 11:17:53.711 +00:00] [ERROR] [querynode/segment_loader.go:205] ["load segment failed when load data into memory"] [collectionID=442197531118847347] [segmentType=Sealed] [partitionID=442197531118847348] [segmentID=442197531120064516] [error="[UnexpectedError] Error:GetObjectSize:  No response body."] [stack="github.com/milvus-io/milvus/internal/querynode.(*segmentLoader).LoadSegment.func3\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/segment_loader.go:205\ngithub.com/milvus-io/milvus/internal/util/funcutil.ProcessFuncParallel.func3\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/parallel.go:83"]
> [2023/07/28 11:17:53.712 +00:00] [ERROR] [funcutil/parallel.go:85] [loadSegmentFunc] [error="[UnexpectedError] Error:GetObjectSize:  No response body."] [idx=0] [stack="github.com/milvus-io/milvus/internal/util/funcutil.ProcessFuncParallel.func3\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/parallel.go:85"]
> ```
> 
> I was thinking that my data might be corrupted because of the disaster in etcd. I was trying to remove shouting segments from etcd using `birdwatcher`, but each time I am getting a same error on the new segment until I run out of segments. Anyone experienced this or at least can help me finding what is possibly going wrong there?
> 
> ### Expected Behavior
> I was expecting that Milvus would work with a restored etcd cluster
> 
> ### Steps To Reproduce
> ```
> 1. Start cluster-mode Milvus
> 2. Create a collection
> 3. Make a snapshot of etcd
> 4. Kill etcd
> 5. Restore etcd from a snapshot
> 6. Restart Milvus
> ```
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

Seems that you are trying to load some data into memory but not exist in etcd.
What might happens is some compaction happened after your snapshot and those files are already garbage collected

**Comment by punkerpunker** [comment]
> Seems that you are trying to load some data into memory but not exist in etcd.
What might happens is some compaction happened after your snapshot and those files are already garbage collected

Are there any suggestions of steps to follow when migrating etcd cluster let's say? 

Also, does that mean that basically if etcd is gone for some reason, collections are pretty much unrecoverable?

**Comment by xiaofan-luan** [comment]
> > Seems that you are trying to load some data into memory but not exist in etcd.
> > What might happens is some compaction happened after your snapshot and those files are already garbage collected
> 
> Thank you for your answer.
> 
> Are there any suggestions of steps to follow when migrating etcd cluster let's say?
> 
> Also, does that mean that basically if etcd is gone for some reason, collections are pretty much unrecoverable?

if you want to migrate your etcd cluster. best way is to shut down your milvus cluster ensure then you do a snapshot on it.

Or you can directly use milvus backup tool to backup milvus cluster and migrate the whole milvus cluster.

**Comment by punkerpunker** [comment]
> if you want to migrate your etcd cluster. best way is to shut down your milvus cluster ensure then you do a snapshot on it.

Or you can directly use milvus backup tool to backup milvus cluster and migrate the whole milvus cluster.

That is really helpful, thanks!
