### ISSUE TITLE
[Bug]: Milvus is not able to load collection or insert entities after switching message queues

### ISSUE THREAD

**Issue by zirota** [milvus-io/milvus#26002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.12
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): kafka / pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.2.13
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 2 - 32 Gb
- GPU: -
- Others: 
  rootCoord.dmlChannelNum: 16
```

### Current Behavior

I switched my messageQueue from Kafka to Pulsar. Pulsar is on **2.10.4**
After doing so, my collections cannot be loaded (it is stuck at 0%). Entity insertion also hangs with no response.

Cluster seems healthy from Kubernetes and Milvus healthcheck.

Could this error be due to the Pulsar version?
On that note, how critical is the message queue to the infrastructure? Since the topics will be provisioned with a retention period, I assume we can afford to lose data here. If the message queue goes down or data is lost will Milvus be able to recover from this?

### Expected Behavior

Message queue should be able to reset without breaking insertion and collection loading.

### Milvus Log

Upon further inspection of the logs, my data node and index is giving this warnings, there are no exception being thrown:

```
["retry func failed"] ["retry time"=10] [error:"proto: illegal wireType 7"]
["retry func failed"] ["retry time"=10] [error:"proto: illegal wireType 7"]
["retry func failed"] ["retry time"=10] [error:"proto: illegal wireType 6"]
["retry func failed"] ["retry time"=10] [error:"wrong wireType = 6 for field LedgerId"]
["retry func failed"] ["retry time"=10] [error:"proto: unexpected EOF"]
["retry func failed"] ["retry time"=10] [error:"proto: unexpected EOF"]
["retry func failed"] ["retry time"=10] [error:"proto: MessageIdData: illegal tag 0 (write type 0)"]
```

**Comment by yanliang567** [comment]
I believe Milvus does not support switching MQ after deployment. When loading or inserting, milvus need to read data from MQ to make the things consistent.  So for now this is by design
/assign @zirota 
/unassign

**Comment by zirota** [comment]
alright, thanks @yanliang567
