### ISSUE TITLE
[Bug]: When the query result volume is greater than 4M, grpc will report an error

### ISSUE THREAD

**Issue by hotwinters** [milvus-io/milvus#26011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.8
- Deployment mode(standalone or cluster):standalone 
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):go SDK 2.2.2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I am conducting a scalar query. In order to query the returned features, due to the large quantity, the returned results exceeded 4m. I saw an error message indicating that the GRPC size is limited to 4m. However, I found in the server milvus.yaml that the GRPC limit is actually more than 4m. Therefore, I would like to ask if I should do some operations on the GO client side 

### Expected Behavior

Release or modify grpc restrictions

### Milvus Log

It was about a month ago, and today it suddenly occurred to me that there was no log anymore

**Comment by xiaofan-luan** [comment]
> 

This is as expected.
You have to use limit offset (but there is still a limit of 65536 entities at most)

**Comment by yanliang567** [comment]
the max value of limit is 16384. check here for more details. https://milvus.io/docs/v2.0.x/limitations.md#Milvus-Limits

/assign @hotwinters 
/unassign

**Comment by hotwinters** [comment]
@xiaofan-luan There is only approximately over 1000 512 dimensional data in the database. Do you mean adding this restriction to the query(opt := client.WithLimit(700))

**Comment by xiaofan-luan** [comment]
> 1000

each 512 dimensional is about 2k, 700 is about 1.4M. maybe you get some other scalar datas?

**Comment by hotwinters** [comment]
@xiaofan-luan There are some scalar fields, maybe I remember the quantity incorrectly. Finally, I saw a prompt in milvus and docker logs indicating that the data size is close to 5m, exceeding 4m, and GRPC reported an error

**Comment by xiaofan-luan** [comment]
milvus 2.3 support iterator, now you can use iterator to query all the vector back
