### ISSUE TITLE
[Enhancement]: Abandon the time travel feature

### ISSUE THREAD

**Issue by jiaoew1991** [milvus-io/milvus#26070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

In the early versions, Milvus added the time travel feature. However, it did not achieve the expected results in terms of community feedback and actual effectiveness. Instead, it introduced many obstacles to stability and other feature designs. For example, when designing functions such as TTL, compaction, and garbage collection, compatibility with time travel must be considered, resulting in significant complexity.

Considering the reasons mentioned above, it is recommended to remove the time travel feature in version 2.3.0 upgrade.

**Comment by jiaoew1991** [comment]
We should follow the following steps to execute:

- [ ] Deprecated the time travel parameter in Milvus interface, remove related implementations and test cases internally
- [ ] Remove relevant introductions from the documentation
- [ ] Remove time travel support from SDK

**Comment by xiaofan-luan** [comment]
Agreed.
Remove timetravel can improve the search performance by
1. pre calculate delete bitset
2. sort the data by pk instead of timestamp and save pk index.

and maybe more ....

**Comment by jiaoew1991** [comment]
The current handling of `search` and `query` for `travel_ts` is different.

1. If the user does not set `travel_ts`, search will use `max_ts`. Previously, we attempted to change the default value to the query time, but it had a significant impact on the merging of search tasks because the merging conditions include whether the `travel_ts` of two search tasks are equal. Therefore, the current search does not guarantee mvcc.

2. If the user does not set `travel_ts` in a query, proxy will use the query time, which ensures mvcc.

We can delete all `travel_ts` on the search path because consistency is not necessary for search, and performance is more important. However, the `travel_ts` of the query needs to be retained but renamed as mvcc. Consistency is necessary for subsequent scenarios such as deduplication of primary keys and delete by expr where querying is done before writing.

**Comment by jiaoew1991** [comment]
finished it
