### ISSUE TITLE
[Bug]: Behavior differs between 2.2 and master branch when using not existing database

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#26074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. The behavior when call `using_db` with not existing database with different branch
 -  image: `2.2.0-20230801-53a23fc8`
return error `connect fail, database not found: bjkW`

- image: `master-20230801-eade5f9b`
using database no error but gets error `database:HTOP not found` after call ListCollections

2. The behavior when call `using_db` with not existing database with different branch
- 2.2 image: `2.2.0-20230801-53a23fc8`
return error `connect fail, database not found: pmWo`

- master image `master-20230801-eade5f9b`
using database no error but gets error `error: database:Wrpg not found` when call List Collections

### Expected Behavior

The behavior of master branch is the same with 2.2 branch

### Steps To Reproduce

```markdown
go sdk repo cases:
- TestUsingDb
- TestClientWithDb
```

**Comment by jaime0815** [comment]
related to #24399

**Comment by ThreadDao** [comment]
Fixed
