### ISSUE TITLE
[Bug]: Passing limit parameter to query returns less results than expected

### ISSUE THREAD

**Issue by hakan458** [milvus-io/milvus#26077]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.11
- Deployment mode(standalone or cluster): Cluster in GCP
- MQ type(rocksmq, pulsar or kafka): Kafka
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.2.11
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I have a collection that I am running `query` on with a basic filter that should return me all results. This works fine when I dont provide a `limit` parameter to `query` 

However, if I provide a `limit` that is higher than the number of records in the collection matching the expression, I get way less records in the result. 

### Expected Behavior

When I provide a `limit`, I should get up to that many records, and it should not reduce the number of records I get in the result set for no reason 

### Steps To Reproduce

```markdown
Here is an example. There are 10 records in the collection matching this expr filter. In all of these cases, I should get all 10 back. Why would a limit of 30 give me 2 results when there are 10? There is clearly some wrong logic here. 

>>> collection = Collection("D3b21e882_6f25_4a46_8b31_a4d6779f459d")
>>> results = collection.query(expr='candidate_task_id != " "')
>>> len(results)
10
>>> results = collection.query(expr='candidate_task_id != " "', limit=30)
>>> len(results)
2
>>> results = collection.query(expr='candidate_task_id != " "', limit=10)
>>> len(results)
1
>>> results = collection.query(expr='candidate_task_id != " "', limit=1000)
>>> len(results)
10
>>> results = collection.query(expr='candidate_task_id != " "', limit=100)
>>> len(results)
7

```
```


### Milvus Log

_No response_

### Anything else?

_No response_

**Comment by hakan458** [comment]
Ok I have dug further into this and think I know why this is happening. 

`collection.num_entities` returns `144` 
But my `query` which should give me all records e.g. `id != ' '` , only gives me 10 results. 
It seems there are records in the collection with duplicate IDs, and it seems limit is applied before `query` "de-duplicates" these results. 
When I pass `limit = 144` , I get all 10 records back in the result. 

It seems `query` will never return duplicate IDs, but MIlvus allows duplicate PKs to be inserted in the first place

**Comment by yanliang567** [comment]
> Ok I have dug further into this and think I know why this is happening.
> 
> `collection.num_entities` returns `144` But my `query` which should give me all records e.g. `id != ' '` , only gives me 10 results. It seems there are records in the collection with duplicate IDs, and it seems limit is applied before `query` "de-duplicates" these results. When I pass `limit = 144` , I get all 10 records back in the result.
> 
> It seems `query` will never return duplicate IDs, but MIlvus allows duplicate PKs to be inserted in the first place
> 
> * How can I check to see if there are duplicate IDs, if `query` doesnt return duplicates?
> * Would there be a way to apply `limit` after this de-duplication happens in `query` ?
> * Why are users allowed to insert data with duplicate PK in the first place?

thanks for sharing the investigation. Right now Milvus does allows duplicate PKs and will do de-dup before returning the search/query results. The PK de-dup is one of the new features in our roadmap.
for now, you have to dedup the PKs before inserting into Milvus.

**Comment by maggonravi** [comment]
If the duplicates are actually present in Milvus, do we know how we can identify the same as no API seems to return it and it's not showing up in Milvus Attu either.

**Comment by xiaofan-luan** [comment]
> If the duplicates are actually present in Milvus, do we know how we can identify the same as no API seems to return it and it's not showing up in Milvus Attu either?

unfortunately I don't know there is a way to do so. Maybe we shoud has a command on birdwatcher
