### ISSUE TITLE
[Bug]: Multi collection concurrent search gets UnexpectedError: Assert "failed to search: out of range in json..." 

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#26085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230801-eade5f9b
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.4.0.dev109
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

- multi collections concurrent search and client gets search failed error
```
[2023-08-01 13:10:02,513 -  INFO - fouram]: Ramping to 100 users at a rate of 20.00 per second (runners.py:495)
[2023-08-01 13:10:03,661 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=1, message=attempt #0: fail to Search, QueryNode ID=9, reason=worker(9) query failed: UnexpectedError: Assert "failed to search: out of range in json: " at /go/src/github.com/milvus-io/milvus/internal/core/src/index/VectorMemIndex.cpp:247: channel=fouramf-vz27m-op-40-8858-rootcoord-dml_13_443254719794192202v0: fail to access shard delegator: fail to search on all shard leaders)>, <Time:{'RPC start': '2023-08-01 13:10:02.575283', 'RPC error': '2023-08-01 13:10:03.661516'}> (decorators.py:126)
[2023-08-01 13:10:03,664 - ERROR - fouram]: (api_response) : <MilvusException: (code=1, message=attempt #0: fail to Search, QueryNode ID=9, reason=worker(9) query failed: UnexpectedError: Assert "failed to search: out of range in json: " at /go/src/github.com/milvus-io/milvus/internal/core/src/index/VectorMemIndex.cpp:247: channel=fouramf-vz27m-op-40-8858-rootcoord-dml_13_443254719794192202v0: fail to access shard delegator: fail to search on all shard leaders)> (api_request.py:53)
[2023-08-01 13:10:03,664 - ERROR - fouram]: [CheckFunc] search request check failed, response:<MilvusException: (code=1, message=attempt #0: fail to Search, QueryNode ID=9, reason=worker(9) query failed: UnexpectedError: Assert "failed to search: out of range in json: " at /go/src/github.com/milvus-io/milvus/internal/core/src/index/VectorMemIndex.cpp:247: channel=fouramf-vz27m-op-40-8858-rootcoord-dml_13_443254719794192202v0: fail to access shard delegator: fail to search on all shard leaders)> (func_check.py:46)
```

- test: 9 collection operate the following steps in-parallel
1. create collection with 1 shard
2. create index ` {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 8, 'efConstruction': 200}}`
3. insert 50w 768d data
4. flush
5. create same index again
6. load collection
7. concurrent search and gets bellow error

- argo link: https://argo-workflows.zilliz.cc/archived-workflows/qa/aa38fe74-fbf3-4b08-a287-b98cbd1eb35e?nodeId=master-concurrent-insert-search-2
- grafana link: https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=qa-milvus&var-instance=fouramf-vz27m-op-40-8858&var-collection=All&var-app_name=milvus&from=1690891333692&to=1690911383523

### Steps To Reproduce

```markdown
1. deploy with resource

  components:
    dataNode:
      paused: false
      replicas: 2
      resources:
        limits:
          cpu: "1"
          memory: 8Gi
        requests:
          cpu: "1"
          memory: 2Gi
    indexNode:
      paused: false
      replicas: 2
      resources:
        limits:
          cpu: "8"
          memory: 16Gi
        requests:
          cpu: "4"
          memory: 8Gi
    proxy:
      paused: false
      replicas: 1
      resources:
        limits:
          cpu: "1"
          memory: 4Gi
    queryNode:
      paused: false
      replicas: 4
      resources:
        limits:
          cpu: "4"
          memory: 16Gi
        requests:
          cpu: "2"
          memory: 8Gi
```
2. client params
```
  config.yaml: |
    collection_params:
      shards_num: 1
    dataset_params:
      dataset_name: gist
      dim: 768 
      dataset_size: '50w'
      ni_per: 5000
      metric_type: L2
    index_params:
      index_type: HNSW
      index_param:
        M: 8
        efConstruction: 200 
    load_params:
      skip_load: false
    concurrent_params:
      concurrent_number: 100 
      during_time: '3h'
      interval: 60
    concurrent_tasks:
      -   
        type: insert
        weight: 2
        params:
          nb: 100 
          timeout: 600 
          random_id: true
          random_vector: true
      -   
        type: search
        weight: 88
        params:
          nq: 100 
          top_k: 100 
          search_param:
            ef: 64
          random_data: true
          timeout: 600 
```
```


### Milvus Log

4am server pods:
```
fouramf-vz27m-op-40-8858-etcd-0                                   1/1     Running                  0                 17h
fouramf-vz27m-op-40-8858-etcd-1                                   1/1     Running                  0                 17h
fouramf-vz27m-op-40-8858-etcd-2                                   1/1     Running                  0                 17h
fouramf-vz27m-op-40-8858-milvus-datacoord-5f5775f7fb-ncprg        1/1     Running                  0                 17h
fouramf-vz27m-op-40-8858-milvus-datanode-584b7b8776-gxlbz         1/1     Running                  0                 14h
fouramf-vz27m-op-40-8858-milvus-datanode-584b7b8776-tpmzs         1/1     Running                  0                 14h
fouramf-vz27m-op-40-8858-milvus-indexcoord-68f65bc548-qcx9m       1/1     Running                  0                 17h
fouramf-vz27m-op-40-8858-milvus-indexnode-684df6bc8d-f54dz        1/1     Running                  0                 17h
fouramf-vz27m-op-40-8858-milvus-indexnode-684df6bc8d-r9v28        1/1     Running                  0                 17h
fouramf-vz27m-op-40-8858-milvus-proxy-5c4776dbc5-dsh4s            1/1     Running                  0                 17h
fouramf-vz27m-op-40-8858-milvus-querycoord-7d5b49557b-dkxtx       1/1     Running                  8 (10h ago)       17h
fouramf-vz27m-op-40-8858-milvus-querynode-6c94b56d9b-csqgd        1/1     Running                  0                 17h
fouramf-vz27m-op-40-8858-milvus-querynode-6c94b56d9b-fdzpc        1/1     Running                  0                 17h
fouramf-vz27m-op-40-8858-milvus-querynode-6c94b56d9b-pdndb        1/1     Running                  0                 17h
fouramf-vz27m-op-40-8858-milvus-querynode-6c94b56d9b-rgcnm        1/1     Running                  0                 17h
fouramf-vz27m-op-40-8858-milvus-rootcoord-5dff489ccb-bmjkv        1/1     Running                  0                 17h
fouramf-vz27m-op-40-8858-minio-0                                  1/1     Running                  0                 17h
fouramf-vz27m-op-40-8858-minio-1                                  1/1     Running                  0                 17h
fouramf-vz27m-op-40-8858-minio-2                                  1/1     Running                  0                 17h
fouramf-vz27m-op-40-8858-minio-3                                  1/1     Running                  0                 17h
fouramf-vz27m-op-40-8858-pulsar-bookie-0                          1/1     Running                  0                 17h
fouramf-vz27m-op-40-8858-pulsar-bookie-1                          1/1     Running                  0                 17h
fouramf-vz27m-op-40-8858-pulsar-bookie-2                          1/1     Running                  0                 17h
fouramf-vz27m-op-40-8858-pulsar-bookie-init-t5rpn                 0/1     Completed                0                 17h
fouramf-vz27m-op-40-8858-pulsar-broker-0                          1/1     Running                  0                 17h
fouramf-vz27m-op-40-8858-pulsar-proxy-0                           1/1     Running                  0                 17h
fouramf-vz27m-op-40-8858-pulsar-pulsar-init-mw8gw                 0/1     Completed                0                 17h
fouramf-vz27m-op-40-8858-pulsar-recovery-0                        1/1     Running                  0                 17h
fouramf-vz27m-op-40-8858-pulsar-zookeeper-0                       1/1     Running                  0                 17h
fouramf-vz27m-op-40-8858-pulsar-zookeeper-1                       1/1     Running                  0                 17h
fouramf-vz27m-op-40-8858-pulsar-zookeeper-2                       1/1     Running                  0                 17h
```

### Anything else?

_No response_

**Comment by yah01** [comment]
`top_k` can't be greater than 'ef' in search params. Will improve the error message

**Comment by ThreadDao** [comment]
wait for knowhere version updat

**Comment by yah01** [comment]
> wait for knowhere version updat

Could you try with the newest commit? the update just merged
