### ISSUE TITLE
[Bug]: Collections with diskann indexes cannot be loaded successfully

### ISSUE THREAD

**Issue by lbj1110** [milvus-io/milvus#26090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.6
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The queryNode node loads the collection data, and after about 25%, there is no progress for up to 10+ minutes, and then it fails

### Expected Behavior

load success

### Steps To Reproduce

```markdown
1. Establish a diskann index on a dataset of 3 million; 
2. Load data into memory; The queryNode node currently allocates 16G of memory
```

### Milvus Log

![1871690961015_ pic_hd](https://github.com/milvus-io/milvus/assets/29877539/2834ea65-6526-4136-a2bb-0a90bd5442d5)

**Comment by yanliang567** [comment]
quick questions:
1. how much disks does the querynode allocate? besides there should be enough disk on querynode, it is recommended to use nvme disks, or you would get a very poor performance.
2. could you please retry on miluvs v2.2.12?
/assign @lbj1110 
/unassign

**Comment by lbj1110** [comment]
At present, the queryNode node resource configuration is 4 nodes* (40G ssd + 16G memory), although it is an ordinary SSD, but this should not be the main reason why the cluster cannot be pulled up, right? Is there any other reason? To illustrate, the diskann index was successfully built after many attempts, does this have an impact on loading?

**Comment by yanliang567** [comment]
@lbj1110 any chance you could retry on milvus v2.3.0?
