### ISSUE TITLE
[Enhancement]: Add pursuit mode for mqtt msgstream

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#26097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Add pursuit mode for mqtt msgstream

### Why is this needed?

When system recover from some abnormal state, datanode & querynode may need to consume lots of msg
Using current policy is time consuming and cause system recovery tool slow.
The proposal is to add pursuit mode: merge msg packs from mqtt msgstream if the time lag is too large(lag threshold configurable). So flowgraphs could can handle these messages in larger batch and skip lots of useless processing.

**Comment by xiaofan-luan** [comment]
/assign @chyezh 
could you pleas help on review the implementation

**Comment by xiaofan-luan** [comment]
> For consuming 100 batch *10000 768 dim vectors, older implementation cost about 60 seconds while pursuit mode costs only 7 seconds

what about the all timetick case?

**Comment by congqixia** [comment]
> what about the all timetick case?

@xiaofan-luan with mock unit test case (mock datacoord time ticker as empty op), normal mode and pursuit mode all takes about 2 second to consume time tick msg of 1 hour (5*60*60).
I guess in real world scenario, operations for time tick sender was the step that consume most of the time for empty time tick msg packs.

**Comment by congqixia** [comment]
@xiaofan-luan  
also @yanliang567 is doing tests in test deployment to get baseline before this enhancement. FYI.

**Comment by yanliang567** [comment]
the baseline is 
50m_768d entities(295 growing segments) was inserted during the datanode was scale down to 0. It costs 55 mins to catch up the tt lag with one datanode on, almost regardless of insert batch(1000, 2000 or 5000) or waiting time after insertion(1h, 4h or 10h).

**Comment by xiaofan-luan** [comment]
looking forward to the result!
And the test way is actually very smart! I would expect 2-3 times performance improvement

**Comment by yanliang567** [comment]
for now it was blocked by #26177
