### ISSUE TITLE
[Bug]: The continuous increase in storage

### ISSUE THREAD

**Issue by Zzt1993** [milvus-io/milvus#26093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
helm install milvus cluster 2.2.10
storageClass made by juicefs
```

### Current Behavior

I installed milvus using helm
The storage uses a storageClass created by Juicefs. Juicefs' metadata is stored in Redis, and Objects are stored in mini

When the cluster is not in use and only installed
The storage scale of mini in the Milvus cluster has been continuously increasing

Approximately 12 hours of storage for 3G，May I ask how to troubleshoot where these data came from

![image](https://github.com/milvus-io/milvus/assets/95836616/d122b9f5-a5dc-4574-a75f-f653ddc7ac75)
![image](https://github.com/milvus-io/milvus/assets/95836616/e42351f5-1cb8-446b-9940-7d4509dd3723)
![image](https://github.com/milvus-io/milvus/assets/95836616/eb027b82-f57f-408b-a284-7034e90a8c09)
I downloaded a file from Minio, but due to formatting issues, I don't know what it is for. Can you take a look，
Due to the format limitations of Github's uploaded files, I have added a. txt file that you can remove after downloading
[609001_0_4096.txt](https://github.com/milvus-io/milvus/files/12238330/609001_0_4096.txt)

**Comment by Zzt1993** [comment]
[419305_0_49715.zip](https://github.com/milvus-io/milvus/files/12238622/419305_0_49715.zip)

**Comment by yanliang567** [comment]
@Zzt1993 thank you for the feedback. quick questions:
1. are you sure you have not ever insert a piece of data into milvus?
2. could you please attach the milvus.yaml to help us understand your deployment?
Please remember to remove any sensitive data in the yaml file.

/assign @Zzt1993

**Comment by Zzt1993** [comment]
Thank you for your answer. I am certain that no data has been inserted as there is no way to use it externally
My deployment command is: helm install my release milvus/milvus -- version 4.0.25
No modifications have been made to the configuration file
[values.zip](https://github.com/milvus-io/milvus/files/12246068/values.zip)

**Comment by yanliang567** [comment]
/assign @LoveEachDay 
could you please help on this issue?

/unassign

**Comment by Zzt1993** [comment]
Could you please try to help investigate? Thank you

**Comment by Zzt1993** [comment]
[dump-2023-08-02-014356.json.gz](https://github.com/milvus-io/milvus/files/12256478/dump-2023-08-02-014356.json.gz)

**Comment by Zzt1993** [comment]
Can you tell if the logs are being stored based on these data

**Comment by Zzt1993** [comment]
Can you tell if the logs are being stored based on these data

**Comment by longjiquan** [comment]
Another question, any chance you reused the storage in different milvus cluster?

**Comment by longjiquan** [comment]
I have read the juicefs's documentation and maybe it's not suitable in the stream processing situation, here for example pulsar. It's more suitable in the batch processing, especially can be a replacement of HDFS.
Can you test the effect when you don't use the juicefs as the storage? @Zzt1993
