### ISSUE TITLE
[FEATURE] Integrate ANNOY into Milvus

### ISSUE THREAD

**Issue by JinHai-CN** [milvus-io/milvus#261]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Milvus need to integrate ANNOY (https://github.com/spotify/annoy) as the index library.

**Comment by shengjun1985** [comment]
@youny626 Please help to add Java sdk.
@fishpenguin Please help to add Go and C++ sdk.
@BossZou Please help to add python sdk.
Thanks.

**Comment by BossZou** [comment]
Reopen this issue. Need SDK support.

**Comment by BossZou** [comment]
Index `ANNOY`  has been added into python SDK. Run cmd `pip install git+https://github.com/BossZou/pymilvus.git@index-annoy` to install python SDK.
Use `IndexType.ANNOY` to get annoy index.

**Comment by fishpenguin** [comment]
Index ANNOY has been added into Go sdk

**Comment by BossZou** [comment]
@del-zhenwu

**Comment by BossZou** [comment]
Index annoy has been integrated into `pymilvus-test 0.3.4`

**Comment by youny626** [comment]
Available in Java SDK 0.7.0-SNAPSHOT
