### ISSUE TITLE
[Enhancement]: Support array datatype

### ISSUE THREAD

**Issue by xiaocai2333** [milvus-io/milvus#26108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Support array DataType for milvus.

### Why is this needed?

Support array DataType for milvus.

**Comment by ruslaniv** [comment]
This is not stale. I'm interested in this too. 
Is there any update on this?

**Comment by xiaocai2333** [comment]
/keep it

@ruslaniv  This feature is in progress and will be released in the next release.
