### ISSUE TITLE
[Bug]: PartitionNotFound if the partition was new created and never be flushed

### ISSUE THREAD

**Issue by sunmingqiaa** [milvus-io/milvus#26113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.12
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus v2.0.0
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Reproduction Process:

Create a table named "test" with two partitions, labeled as 1 and 2.
Insert a record into each partition, one in partition 1 and another in partition 2.
Perform searches on both partitions 1 and 2, which should return the respective records successfully.
Next, create a new partition labeled as 3 and insert a record into it. When attempting to search specifically in partition 3, the result shows "reason=stream operation failed: PartitionNotFound(partitionID=443277368143647844)".
After performing a flush operation, searches on partition 3 return the record normally.
After conducting multiple tests, it was observed that when creating one or two partitions initially and following steps 1, 2, and 3, searches work correctly. However, when executing step 4, an exception is encountered.

### Expected Behavior

it should normal return result

### Steps To Reproduce

```markdown
Reproduction Process:

Create a table named "test" with two partitions, labeled as 1 and 2.
Insert a record into each partition, one in partition 1 and another in partition 2.
Perform searches on both partitions 1 and 2, which should return the respective records successfully.
Next, create a new partition labeled as 3 and insert a record into it. When attempting to search specifically in partition 3, the result shows "reason=stream operation failed: PartitionNotFound(partitionID=443277368143647844)".
After performing a flush operation, searches on partition 3 return the record normally.
After conducting multiple tests, it was observed that when creating one or two partitions initially and following steps 1, 2, and 3, searches work correctly. However, when executing step 4, an exception is encountered.
```

### Milvus Log

Failed to search vectors in Milvus: <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:\nattempt #1:code: UnexpectedError, error: fail to Search, QueryNode ID=6, reason=stream operation failed: PartitionNotFound(partitionID=443277368143647844)\nattempt #2:context canceled\n)

**Comment by yanliang567** [comment]
@jiaoew1991 sound like a corner issue that milvus did not sync the meta at once as partition created.
/assign @jiaoew1991 
/unassign

**Comment by yanliang567** [comment]
/assign @NicoYuan1986 
can we add a new test for this

**Comment by xiaofan-luan** [comment]
we are not support create partition while collection is loaded.
this is as expected in 2.2.12, we only load partitions list on the load

**Comment by dickreuter** [comment]
We are having this issue as well, sometimes when we create a partition, it is not actually created. It seems to happen randomly. Any idea why?

**Comment by yanliang567** [comment]
please retry on latest milvus 2.5.12 and file a new issue if it reproduced to you

**Comment by dickreuter** [comment]
We are using milvus on zilliz, so it does use the latest version

**Comment by yanliang567** [comment]
> We are using milvus on zilliz, so it does use the latest version

if so, please file a zilliz cloud support ticket and provide the info such as collection name, partition name and timestamp you make the requests, etc in the ticket.

**Comment by xiaofan-luan** [comment]
> We are having this issue as well, sometimes when we create a partition, it is not actually created. It seems to happen randomly. Any idea why?

Hi Nicholas,
please let me the ticket id or you can directly send the error message and isntance id to james.luan@zilliz.com so I can followup
