### ISSUE TITLE
[Bug]: Double-write delete and insert error

### ISSUE THREAD

**Issue by Saxon0918** [milvus-io/milvus#26148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.4
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus=2.2.0
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I double-write data into primary and backup Milvus databases, they both return success. However, when I search for the same data in two databases, they sometimes return differently. Sometimes the data can only be searched in the primary database, and sometimes it can only be searched in the backup milvus. The probability of such errors occurring is around 10%, thus it should test for one day maybe we can observe this error.

Here is my code for double-write data in two databases. The 'host' and 'port' of primary and backup databases are different. And collection_name in both databases is the same. To ensure the data is up-to-date, I first delete the data with the same ID in two databases and then insert the new data.

`expr = 'id in [{xxxx}]'

pri_collection = Collection(name='collection_name', consistency_level='Strong', using='xxx')
pri_delete_result = pri_collection.delete(expr=expr)
pri_insert_result = pri_collection.insert(data='xxx', partition_name='xxx')

backup_collection = Collection(name='collection_name', consistency_level='Strong', using='xxx')
backup_delete_result = backup_collection.delete(expr=expr)
backup_insert_result = backup_collection.insert(data='xxx', partition_name='xxx')`

In order to find the reason behind this error, I have printed all return fields of the insert and delete operations in the log. 'insert_result1' and 'insert_backup1' are the logs of the primary database and backup database, respectively. 
'delete_xxx_xxx' is the return field of the delete operation, such as 'delete_delete_count'、'delete_success_index'.
'insert_xxx_xxx' is the return field of the insert operation, such as 'insert_delete_count'、'insert_insert_count'.
![2](https://github.com/milvus-io/milvus/assets/26076141/18db7f7d-ecb5-408f-a0e1-09e12ea47854)

### Expected Behavior

The search results of the two databases are consistent.

### Steps To Reproduce

```markdown
for one ID:
delete this ID in the primary database
insert this ID in the primary database

delete this ID in the backup database
insert this ID in the backup database

test for one day
```

**Comment by yanliang567** [comment]
@Saxon0918 thank you for feedbacks. when you say "Sometimes the data can only be searched in the primary database, and sometimes it can only be searched in the backup milvus.", what error did you get from the "not working milvus", could you please reproduce the error and attach the milvus logs? please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs

/assign @Saxon0918 
/unassign

**Comment by Saxon0918** [comment]
> @Saxon0918 thank you for feedbacks. when you say "Sometimes the data can only be searched in the primary database, and sometimes it can only be searched in the backup milvus.", what error did you get from the "not working milvus", could you please reproduce the error and attach the milvus logs? please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs
> 
> /assign @Saxon0918 /unassign

I'm sorry to make you confused. 
First, about the error you mentioned 'what error did you get from the "not working Milvus"'. For example, if I insert data that ID=10 into primary and backup databases. After executing the insert operation, when I search this data in both databases, it can just be searched in one database. The correct result should be that this data can be searched in both databases. However, the log of the insert operation did not indicate any errors, and the 'insert_count' field of the insert operation returned 1 just like the screenshot above.

And I am very sorry that due to the presence of sensitive information in the log, only the return value fields of the insert operation can be shown, and the result is the screenshot above. 

However, I strongly recommend that you check this bug. For example, you should insert data with an ID of 10. The operation flow is as follows: 
1. Regardless of whether data with ID=10 already exists in the database, first execute a deletion operation. 
2. Insert new data with ID=10 into the database. 
As shown in the flow chart, the identical operation is performed linearly in both the primary and backup databases. After testing around 10,000 data entries, you will likely discover this bug.
![whiteboard_exported_image](https://github.com/milvus-io/milvus/assets/26076141/8af9d6e3-2e70-4764-800e-d583f1f7b677)

**Comment by Saxon0918** [comment]
> @Saxon0918 thank you for feedbacks. when you say "Sometimes the data can only be searched in the primary database, and sometimes it can only be searched in the backup milvus.", what error did you get from the "not working milvus", could you please reproduce the error and attach the milvus logs? please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs
> 
> /assign @Saxon0918 /unassign

I'm sorry to make you confused. 
First, about the error you mentioned 'what error did you get from the "not working Milvus"'. For example, if I insert data that ID=10 into primary and backup databases. After executing the insert operation, when I search this data in both databases, it can just be found in one database. The correct result should be that this data can be searchable in both databases. However, the log of the insert operation did not indicate any errors, and the 'insert_count' field of the insert operation returned 1 just like the screenshot above.
And I am very sorry that due to the presence of sensitive information in the log, only the return value fields of the insert operation can be shown, and the result is the screenshot above. 

However, I strongly recommend that you check this bug. For example, you should insert data with an ID of 10. The operation flow is as follows: 
1. Regardless of whether data with ID=10 already exists in the database, first execute a deletion operation. 
2. Insert new data with ID=10 into the database. 
As shown in the flow chart, the identical operation is performed linearly in both the primary and backup databases. After testing around 10,000 data entries, you will likely discover this bug.
![whiteboard_exported_image](https://github.com/milvus-io/milvus/assets/26076141/7e3fc625-565f-4ae7-8f56-c529485bd0c5)

**Comment by xiaofan-luan** [comment]
1.  I thought there are some issue in delete handling, please test on 2.2.12
2. On 2.3 we support CDC(change data capture), and a easier to support primary backup is to simply use change data capture to connect to clusters.
If you still find similar issue in 2.2.12, could you offer a quick script to reproduce this issue so we could work on investigation details? This might be reasonable behaviour if the difference chance is small.

**Comment by Saxon0918** [comment]
> 1. I thought there are some issue in delete handling, please test on 2.2.12
> 2. On 2.3 we support CDC(change data capture), and a easier to support primary backup is to simply use change data capture to connect to clusters.
>    If you still find similar issue in 2.2.12, could you offer a quick script to reproduce this issue so we could work on investigation details? This might be reasonable behaviour if the difference chance is small.

Thanks for your reminder. I have resolved this issue.
