### ISSUE TITLE
[Enhancement]: Support get vector from storage

### ISSUE THREAD

**Issue by bigsheeper** [milvus-io/milvus#26141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

For index which doesn't have raw data like IVF_PQ、IVF_SQ8，we should retrive vector from storage.

**Comment by bigsheeper** [comment]
We should implement a chunk cache with cpp.

see also: https://github.com/milvus-io/milvus/issues/21296

**Comment by xiaofan-luan** [comment]
reopen since it's not merged yet
