### ISSUE TITLE
[Feature]: provide data export and import tools, data formats such as csv etc.

### ISSUE THREAD

**Issue by xxxrain** [milvus-io/milvus#26147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I cannot export data to csv format, especially if the data is large

**Comment by CaoHaiNam** [comment]
Hi @jiaoew1991 @xiaofan-luan , Is this feature implemented or still needed? I can work on it if necessary.

**Comment by xiaofan-luan** [comment]
I think csv import is already supported ~

closed it for now

**Comment by CaoHaiNam** [comment]
I think in this issue, the author want to **export** data from a milvus collection to a csv file, not **import** data from csv file into a milvus collection.

**Comment by xiaofan-luan** [comment]
feel free to take it.
We believe the best way to do it is through milvus backup
