### ISSUE TITLE
[Bug]: set_properties() 报错

### ISSUE THREAD

**Issue by huan415** [milvus-io/milvus#26158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:milus:v2.2.12
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.2.14
- OS(Ubuntu or CentOS): window
- CPU/Memory: CPU
- GPU: 
- Others:
```

### Current Behavior

 pymilvus==2.2.14：set_properties 设置ttl报错
 (pymilvus==2.2.11 set_properties 没报错，但是ttl时间后，通过milvus-insight观察了很久，数据没被删除)
 
![image](https://github.com/milvus-io/milvus/assets/37132274/ec7e2e1f-a5da-4f54-92cb-38d73ae08043)

代码如下：
`field1 = FieldSchema(name="id", dtype=DataType.INT64, descrition="int64", is_primary=True, auto_id=True)
 field2 = FieldSchema(name="embedding", dtype=DataType.FLOAT_VECTOR, descrition="float vector",
                                     dim=VECTOR_DIMENSION, is_primary=False)
schema = CollectionSchema(fields=[field1, field2, field3], description="collection description")
self.collection = Collection(name=collection_name, schema=schema)
self.collection.set_properties({"collection.ttl.seconds": 1200})`

**Comment by yanliang567** [comment]
please try
`collection.set_properties(properties={"collection.ttl.seconds": 1200})
`

/assign @huan415 
/unassign
