### ISSUE TITLE
[Bug]: datanode memory usage increased to 150GB when there are 50m vectors to be flush

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#26177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230805-241117dd
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I scaled the datanode down to 0, and insert 50m_768d vectors. Then I scaled the datanode up to 1, the datanode memory usage increased to 150GB in 15 mins
![image](https://github.com/milvus-io/milvus/assets/82361606/9c2c07a8-1205-4f8a-9ce7-c12fc0c3af3b)

### Expected Behavior

the baseline on master-20230802-df26b909: datanode memory usage is about 2.3-1.3GB for the same size of vectors.

### Steps To Reproduce

```markdown
1. create a collection with 20k_768d vectors, build hnsw index
2. scale down the datanode to 0
3. insert 50m_768d vectors
4. scale up the datanode back to 1
5. wait and check the tt lag, datanode cpu and memory
```

### Milvus Log

pod names on devops:
```
yanliang-ttlag-milvus-datanode-cbf79cbdc-bx4h6                  1/1     Running       0               34m     10.102.7.245    devops-node11   <none>           <none>
yanliang-ttlag-milvus-indexnode-6699c566d7-9l49n                1/1     Running       2 (2m16s ago)   6h54m   10.102.7.231    devops-node11   <none>           <none>
yanliang-ttlag-milvus-mixcoord-987654d85-pfzg2                  1/1     Running       0               6h54m   10.102.7.238    devops-node11   <none>           <none>
yanliang-ttlag-milvus-proxy-df7b5955f-5twjd                     1/1     Running       0               6h54m   10.102.7.239    devops-node11   <none>           <none>
yanliang-ttlag-milvus-querynode-76cf9c9b55-rcwx9                1/1     Running       0               6h54m   10.102.7.232    devops-node11   <none>           <none>
```

### Anything else?
the suspected pr: #26144

**Comment by congqixia** [comment]
from the pprof, there are lot's of msg pack buffered in memory
![image](https://github.com/milvus-io/milvus/assets/84113973/fee93a8d-e45d-4aae-9747-8ecfda9c3e8b)

there are some channels that are too large which could cause this problem:
- MsgStream buffers(mq buffer & receive buffer) 1024*2
- Flowgraph node buffer (input node -> dd node -> insert buffer node) 1024*2

in high read pressure, all channels shall be full with will lead to 1024*4*8MB memory cost

And the flush manager will buffer flush task as well, which will multiply this memory cost.

**Comment by congqixia** [comment]
@yanliang567 after #26179 merged, could you please verify with this parameter enlarged
```yaml
dataNode:
  dataSync:
    maxParallelSyncTaskNum: 2 # Maximum number of sync tasks executed in parallel in each flush manager
```

**Comment by xiaofan-luan** [comment]
can we simplify the mqstream logic to make it easier to understand?

**Comment by yanliang567** [comment]
@congqixia any plans for fixing this issue in v2.3.2?

**Comment by congqixia** [comment]
@yanliang567 nope, l0 delta and datanode refine will be implemented after 2.3.2

**Comment by yanliang567** [comment]
moving to 2.3.3

**Comment by yanliang567** [comment]
moving to 2.4 for L0 deletion

**Comment by congqixia** [comment]
@yanliang567 now we shall verify where this problem persists when l0 segment is enabled
/assign @yanliang567

**Comment by yanliang567** [comment]
will do as L0 segment enabled.
/unassign @congqixia

**Comment by yanliang567** [comment]
test on 2.4-20240407-e3b65203-amd64
datanode memory goes to 38GB
![image](https://github.com/milvus-io/milvus/assets/82361606/81ea60ba-cd9c-4874-9a14-67bf6fe83b1b)

and ttlag catch up from 5.3h to 200ms in about 60mins
![image](https://github.com/milvus-io/milvus/assets/82361606/eb814fdf-9196-417c-9766-0d085c909a99)

**Comment by xiaofan-luan** [comment]
I thought the key might to increase flush concurrency make sure flush can catch up insertion rate

**Comment by congqixia** [comment]
@xiaofan-luan the scenario here is to verify the datanode behavior when datanode is down for a long time

@yanliang567 the last run did not limit the memory of datanode. Memory usage went to arount 40GB. Maybe it's still an issue here. Let's check what the behavior is when datanode has memory limit. 

The catch-up time is about one hour for 5 hour ttlag with insertion. Does this value good enough for our system? @xiaofan-luan @yanliang567 @tedxu @jaime0815

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan the scenario here is to verify the datanode behavior when datanode is down for a long time
> 
> @yanliang567 the last run did not limit the memory of datanode. Memory usage went to arount 40GB. Maybe it's still an issue here. Let's check what the behavior is when datanode has memory limit.
> 
> The catch-up time is about one hour for 5 hour ttlag with insertion. Does this value good enough for our system? @xiaofan-luan @yanliang567 @tedxu @jaime0815 

1. How long do we stop the cluster? 
2. Is there anything we can improve? what is the bottleneck?

**Comment by yanliang567** [comment]
we did not stop the cluster, we just scale down the datanode replica to 0, and insert for 6 hours(~50M_768d data), and then bring one datanode up. 
@congqixia is trying to make a pr

**Comment by yanliang567** [comment]
on master-20240426-bed6363f, the tt lag catches up quickly, but the datanode uses memory without any limitation, OOM occurs for times in a 8c32g datanode pod.
![image](https://github.com/milvus-io/milvus/assets/82361606/1020c110-1447-4c35-adfd-95e805903d00)
![image](https://github.com/milvus-io/milvus/assets/82361606/7e1f421d-fd8d-47fd-8187-ad54df85243a)
