### ISSUE TITLE
[Bug]: Incorrect result while retrieving int8 type data

### ISSUE THREAD

**Issue by smellthemoon** [milvus-io/milvus#26170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

incorrect result while retrieving int8 type data
<img width="843" alt="1" src="https://github.com/milvus-io/milvus/assets/64083300/31358750-40d5-4872-8d12-578c472a15de">

**Comment by smellthemoon** [comment]
Whether there is an int8 type schema test in the test? @yanliang567

**Comment by xiaofan-luan** [comment]
good catch!

**Comment by yanliang567** [comment]
/assign @binbinlv 
could you please help to check if there are related cases?
/unassign

**Comment by binbinlv** [comment]
> /assign @binbinlv
> could you please help to check if there are related cases?
> /unassign

Yes, we have different scalar data type (like int8) as output_fields, but it has been skipped for [issue ](https://github.com/milvus-io/milvus/issues/23646) before, now it could be open.

**Comment by binbinlv** [comment]
Verified and enabled the test case, close this issue.

pymilvus: 2.3.0.post1.dev13
milvus: master-20230918-4f6122dd
```
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0", output_fields=["int8"])
>>> res[0][0]
id: 0, distance: 0.00029392066062428057, entity: {'int8': 0}
>>> res[0][1]
id: 1802, distance: 13.975786209106445, entity: {'int8': 10}
```
