### ISSUE TITLE
[Enhancement]: Support Tencent cos as object storage

### ISSUE THREAD

**Issue by groobyming** [milvus-io/milvus#26185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Support Tencent cos as object storage

### Why is this needed?

Currently we have purchased Tencent Cloud's cos as an object storage service, hoping to reuse these resources

**Comment by xiaofan-luan** [comment]
Mark it as good first issue. 
Contribution is welcomed

**Comment by lisirrx** [comment]
hi, I'm new to Milvus, and I just go through a document of Tencent COS, and I found it is [S3 API 
compatible ](https://cloud.tencent.com/document/product/436/37421).
So I guess COS can be intergrated like how milvus do with aliyun oss.
Can you assign this issue to me, and I want to have a try.

**Comment by xiaofan-luan** [comment]
/assign @lisirrx 
thanks for the interest!
