### ISSUE TITLE
关于Milvus 0.9.0  查询偶尔返回 Result count doesn\'t match target vectors count 的异常

### ISSUE THREAD

**Issue by liuruifeng-git** [milvus-io/milvus#2619]
**Describe the bug**
Milvus 0.9.0  查询偶尔返回 Result count doesn\'t match target vectors count 的异常

**Steps/Code to reproduce behavior**
1.底库只存了一个向量
2.使用多线程查询 
3. 偶尔会报Result count doesn\'t match target vectors count 异常

**Comment by shengjun1985** [comment]
same as #2578

**Comment by yhmo** [comment]
already fixed by #2591 in 0.10.1 and master branch
