### ISSUE TITLE
[Bug]: Improve bulkinsert read performance for varchar

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#26197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.12
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Currently, the bulkinsert task read varchar numpy file row by row. Change the logic to batch read.

**Comment by xiaofan-luan** [comment]
Very important, good to see the improvement

**Comment by yhmo** [comment]
Pr has been merged. In practice, it improves the performance by 10%~15%.
