### ISSUE TITLE
[Bug]: milvus enables standby mode, and when the primary node crashes, an error occurs: role xxxxcoord[nodeID: xxx] is not serving, reason: StandBy.

### ISSUE THREAD

**Issue by obailiumingo** [milvus-io/milvus#26219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.10
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):  pymilvus  2.2.12
- OS(Ubuntu or CentOS): redhat
- CPU/Memory: 16c 64G
- GPU: 
- Others:
```

### Current Behavior

etcd上的coord记录已经切换到备用节点，但是连接到coord的客户端(proxy/indexnoode/datanood等)会连接到之前挂掉又重启的节点上，该节点重启后已经不是主节点了

### Expected Behavior

主节点挂掉后，自动切换到备用节点，应用访问正常

### Steps To Reproduce

```markdown
1. 使用k8s 部署，coord deployment绑定固定节点，并且网络模式设定为hostnetwork，确保重启后ip不会改变
2. 所有的coord均开启1主两副本
3. 主动删除coord主节点(会自动重启)
4. 访问应用报错
```

### Milvus Log

```
io.milvus.client.AbstractMilvusGrpcClient.logError(AbstractMilvusGrpcClient.java:3064):QueryRequest failed:
checkIfLoaded failed when query, collection:test_0803_1, partitions:[], err = GetCollectionInfo failed, collection = test_0803_1, err = role querycoord[nodeID: 117] is not serving, reason: StandBy

```

### Anything else?

猜测：
milvus 服务发现的触发机制貌似是 "服务启动" 及 "grpc连接报错" 的时候，
如果主节点发生重启，备节点变成主节点，客户端（proxy、indexnode等）仍然会连接到原本的节点上去，grpc连接本身不会报错，但是原节点角色已经由主节点变为备节点，导致应用使用的时候故障

建议：
服务发现的机制需要优化一下：除了重启和报错的时候去发现，每隔几秒就应该去etcd中查询，否则对发生主备切换的反应会很迟钝，可能由于各种各样的原因导致连接到备用节点上去。

**Comment by wayblink** [comment]
@obailiumingo Nice analysis. I think it is because you bind service to IP, so client won't get a error when connect to the old IP and won't switch. We will think about it.

**Comment by obailiumingo** [comment]
> @obailiumingo Nice analysis. I think it is because you bind service to IP, so client won't get a error when connect to the old IP and won't switch. We will think about it.

所见略同。服务重启和绑定静态IP有其意义，milvus其他部分的代码还没仔细阅读，除了我遇到的这种情况，也许其他人也会因为别的原因报standby 错误。从机制上分析，提升服务发现敏捷度可能才是彻底解决同类问题的关键。

**Comment by obailiumingo** [comment]
> @obailiumingo Nice analysis. I think it is because you bind service to IP, so client won't get a error when connect to the old IP and won't switch. We will think about it.

所见略同。服务重启和绑定静态IP有其意义，milvus其他部分的代码还没仔细阅读，除了我遇到的这种情况，也许其他人也会因为别的原因报standby 错误。从机制上分析，提升服务发现敏捷度可能才是彻底解决同类问题的关键。

**Comment by obailiumingo** [comment]
@yanliang567 @wayblink 最新发现，在运行状态也会因为未知原因导致组件连接到备用节点上，当时查看了主备节点都没有重启的迹象，我暂时关闭了standby模式，因为是排查问题，原始日志没保存下来，大概是这样的(datacoord节点)：
```
servername datacoord is in standby
servername datacoord is in standby
servername datacoord is in standby
servername datacoord is in standby
servername datacoord is in standby
get *** request received
get *** request received
get *** request received
get *** request received
servername datacoord is in standby
get *** request received
get *** request received
get *** request received
servername datacoord is in standby
servername datacoord is in standby
servername datacoord is in standby
servername datacoord is in standby
servername datacoord is in standby
servername datacoord is in standby
servername datacoord is in standby
```

**Comment by wayblink** [comment]
/assign @congqixia 
Let's think about adding active detection logic～

**Comment by xiaofan-luan** [comment]
we are working on the fix~

**Comment by obailiumingo** [comment]
[Add server id validation interceptor #26395](https://github.com/milvus-io/milvus/pull/26395)
这个pr真的能修复这个缺陷吗？表示有点怀疑。初步看了一下似乎是在grpc协议中加了一个nodeId 字段，并在server端通过intercepter进行校验，但是我没看到这个字段的更新逻辑（要么在客户端，要么在服务端 去取真正生效的主节点ID）。

另外如果可以通过intercepter 去做，直接校验一下当前节点的状态，是standby就报错是否更高效一些？还不用加一个额外的字段。

**Comment by obailiumingo** [comment]
[Add server id validation interceptor #26395](https://github.com/milvus-io/milvus/pull/26395)
这个pr真的能修复这个缺陷吗？表示有点怀疑。初步看了一下似乎是在grpc协议中加了一个nodeId 字段，并在server端通过intercepter进行校验，但是我没看到这个字段的更新逻辑（要么在客户端，要么在服务端 去取真正生效的主节点ID）。

另外如果可以通过intercepter 去做，直接校验一下当前节点的状态，是standby就报错是否更高效一些？还不用加一个额外的字段。

**Comment by bigsheeper** [comment]
> [Add server id validation interceptor #26395](https://github.com/milvus-io/milvus/pull/26395) 这个pr真的能修复这个缺陷吗？表示有点怀疑。初步看了一下似乎是在grpc协议中加了一个nodeId 字段，并在server端通过intercepter进行校验，但是我没看到这个字段的更新逻辑（要么在客户端，要么在服务端 去取真正生效的主节点ID）。


Hello @obailiumingo, If the server id mismatch error occurs, the connection will be closed, and  the client will search for the newest active node, and rebuild the connection.
https://github.com/milvus-io/milvus/blob/148446cfb9bf9a285ef13c99b2df8c17c47e0122/internal/util/grpcclient/client.go#L315

> 
> 另外如果可以通过intercepter 去做，直接校验一下当前节点的状态，是standby就报错是否更高效一些？还不用加一个额外的字段。

It is a frequently employed approach for addressing comparable problems, not limited to just the active-standby switch scenario, whereby if the server ID specified by the client does not correspond with the actual server's ID.

**Comment by bigsheeper** [comment]
@yanliang567 please help to make a verify for this issue.

**Comment by obailiumingo** [comment]
好的 了解了 谢谢，重启后serverid会重新生成，确实可以解决。另外关于分支问题，可否提一个pr到2.2.10？&nbsp;



发自我的iPhone


------------------ Original ------------------
From: yihao.dai ***@***.***&gt;
Date: Wed,Aug 23,2023 11:39 AM
To: milvus-io/milvus ***@***.***&gt;
Cc: 白留明 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [milvus-io/milvus] [Bug]: milvus enables standby mode, and whenthe primary node crashes, an error occurs: role xxxxcoord[nodeID: xxx] is notserving, reason: StandBy. (Issue #26219)





  
Add server id validation interceptor #26395 这个pr真的能修复这个缺陷吗？表示有点怀疑。初步看了一下似乎是在grpc协议中加了一个nodeId 字段，并在server端通过intercepter进行校验，但是我没看到这个字段的更新逻辑（要么在客户端，要么在服务端 去取真正生效的主节点ID）。
  
Hello @obailiumingo, If the server id mismatch error occurs, the connection will be closed, and  the client will search for the newest active node, and rebuild the connection.
 https://github.com/milvus-io/milvus/blob/148446cfb9bf9a285ef13c99b2df8c17c47e0122/internal/util/grpcclient/client.go#L315
  
另外如果可以通过intercepter 去做，直接校验一下当前节点的状态，是standby就报错是否更高效一些？还不用加一个额外的字段。
  
It is a frequently employed approach for addressing comparable problems, not limited to just the active-standby switch scenario, whereby if the server ID specified by the client does not correspond with the actual server's ID.

**Comment by bigsheeper** [comment]
> 好的 了解了 谢谢，重启后serverid会重新生成，确实可以解决。另外关于分支问题，可否提一个pr到2.2.10？&nbsp; 发自我的iPhone
>

Hello, @obailiumingo this fix will be released to 2.2.14 these days.
