### ISSUE TITLE
[Bug]:  WARN log  "processDeleteMessage"

### ISSUE THREAD

**Issue by bingbb47** [milvus-io/milvus#26214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.12
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

when cluster upgrade to 2.2.12, the querynode always print WARN log as

[2023/08/06 00:00:00.345 +08:00] [WARN] [querynode/flow_graph_insert_node.go:320] [processDeleteMessage] [vchannel=milvus-test-rootcoord-dml_2_443273039397313288v0] [segmentIDs="[]"] [paritions="[0]"]

This doesn't seem to affect the normal functionality of the cluster. Do you have any clues about this phenomenon

### Milvus Log

[2023/08/06 00:00:00.345 +08:00] [WARN] [querynode/flow_graph_insert_node.go:320] [processDeleteMessage] [vchannel=milvus-test-rootcoord-dml_2_443273039397313288v0] [segmentIDs="[]"] [paritions="[0]"]

**Comment by bingbb47** [comment]
There are no other logs besides this one

**Comment by yanliang567** [comment]
I think this is expected for now.
what's your expectation?
/assign @bingbb47 
/unassign

**Comment by bingbb47** [comment]
> I think this is expected for now. what's your expectation? /assign @bingbb47 /unassign

Alright i get，Is this WARN log expected to have a frequency of approximately 5 entries per second for each querynode? What is the querynode doing when it appears

**Comment by xiaofan-luan** [comment]
should change this to debug

**Comment by smellthemoon** [comment]
> > I think this is expected for now. what's your expectation? /assign @bingbb47 /unassign
> 
> Alright i get，Is this WARN log expected to have a frequency of approximately 5 entries per second for each querynode? What is the querynode doing when it appears
Thanks, in the 2.2.13, the log level has become 'Info', related with #26059 , this log means that execute delete operations for growing segments, it's ok to log it.

**Comment by bingbb47** [comment]
> 
Ok, thanks for reply~
