### ISSUE TITLE
[Bug]: 2.3.0-gpu-beta failed to start with `milvus run standalone`

### ISSUE THREAD

**Issue by lidh15** [milvus-io/milvus#26212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.0-gpu-beta
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: amd64
- GPU: Nvidia
- Others:
```

### Current Behavior

milvus-standalone container failed to start
I'm using official docker-compose.yml and updated the image for 2.2.9 to 2.3.0-gpu-beta:
```yml
  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.3.0-gpu-beta
    command: ["milvus", "run", "standalone"]
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
```

### Milvus Log

docker logs said:
```sh
2023-08-08 08:55:22,982 INFO [default] [KNOWHERE][operator()][milvus] simd type: AVX512
2023/08/08 08:55:23 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined

    __  _________ _   ____  ______
   /  |/  /  _/ /| | / / / / / __/
  / /|_/ // // /_| |/ / /_/ /\ \
 /_/  /_/___/____/___/\____/___/

Welcome to use Milvus!
Version:   v2.3.0-beta-gpu
Built:     Mon Mar 20 14:07:30 UTC 2023
GitCommit: f547c1f
GoVersion: go version go1.18.3 linux/amd64

open pid file: /run/milvus/standalone.pid
lock pid file: /run/milvus/standalone.pid
[2023/08/08 08:55:23.029 +00:00] [INFO] [roles/roles.go:196] ["starting running Milvus components"]
[2023/08/08 08:55:23.029 +00:00] [INFO] [roles/roles.go:124] ["Enable Jemalloc"] ["Jemalloc Path"=/milvus/lib/libjemalloc.so]
[2023/08/08 08:55:23.032 +00:00] [INFO] [config/refresher.go:58] ["start refreshing configurations"] [source=FileSource]
[2023/08/08 08:55:23.035 +00:00] [INFO] [config/refresher.go:58] ["start refreshing configurations"] [source=EtcdSource]
[2023/08/08 08:55:23.036 +00:00] [INFO] [paramtable/hook_config.go:18] ["hook config"] [hook={}]
[2023/08/08 08:55:23.037 +00:00] [DEBUG] [server/global_rmq.go:48] ["initializing global rmq"] [path=/var/lib/milvus/rdb_data]
[2023/08/08 08:55:23.038 +00:00] [DEBUG] [server/rocksmq_impl.go:158] ["Start rocksmq "] ["max proc"=8] [parallism=1] ["lru cache"=4036021862]
panic: Not implemented: Unsupported compression method for this build: ZSTD

```

**Comment by yanliang567** [comment]
/assign @jiaoew1991 
seems to be a known issue, please help
/unassign

**Comment by jiaoew1991** [comment]
/assign @Presburger 

Is it enough to upgrade to the latest master version? 🤔

**Comment by xiaofan-luan** [comment]
For test, you can remove the disk directory of rocksmq since there are some incompatible change.
For production mode, 2.3 formal release is not ready yet, please wait until next Tuesday.

**Comment by lidh15** [comment]
> For test, you can remove the disk directory of rocksmq since there are some incompatible change.
> For production mode, 2.3 formal release is not ready yet, please wait until next Tuesday.

next Tuesday is not too late for me as long as that release is a usable version. 
Will you release a image on docker hub by that time or release in other approach?

**Comment by danigc98** [comment]
I am also facing many issues with the 2.3.0 beta, could you confirm that a release is coming this week?

**Comment by lidh15** [comment]
it's Wednesday today and there is no reply. I'd like to introduce Pinecone to people who opened this issue.

**Comment by jiaoew1991** [comment]
> it's Wednesday today and there is no reply. I'd like to introduce Pinecone to people who opened this issue.

@lidh15 Milvus community is still working hard to fix bugs for the 2.3.0 release. There are several critical bugs that need to be resolved, so it is not recommended to use it directly in a production environment. If you want to experience the features of version 2.3.0, you can compile the master branch and build your own Docker image. If you want to quickly deploy in a production environment, you can use Zilliz Cloud instead.
In addition, if you want to expedite the release of version 2.3.0, you can fix a few bugs in the community and welcome to contribute code.

**Comment by lidh15** [comment]
I understand that you are hard-working, and I would like to contribute if I were a Golang developer.
I just want to say if you know it is too critical to fix before Tuesday, you should not promise users that you can make it.
Good luck to you guys.

**Comment by jiaoew1991** [comment]
I think this issue can be closed now.

**Comment by xiaofan-luan** [comment]
> I understand that you are hard-working, and I would like to contribute if I were a Golang developer. I just want to say if you know it is too critical to fix before Tuesday, you should not promise users that you can make it. Good luck to you guys.


Thanks for your patience. But please notice as an open source  community we never have any "promise". Please feel free to take all the business offerings and I guess that should offer what you want.

And to whom who might be interested, GPU is just a beta feature in 2.3 and please be careful to use it in production environment

**Comment by xiaofan-luan** [comment]
and the reason for this issue is try to upgrade from some version with ZSTD support to no ZSTD support, and it should be a issue for 2.3.
