### ISSUE TITLE
[Bug]: Querynode or standalone pod restarted several times during test after upgrade 

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#26249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230808-b84f5c56
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):puldar    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

log looks like 
![image](https://github.com/milvus-io/milvus/assets/12268675/a7c70953-5da6-464c-a26b-81932bc38b10)

maybe this is caused by querynode restart

![image](https://github.com/milvus-io/milvus/assets/12268675/05910ada-0355-4f42-902e-6f45549844fa)

### Expected Behavior

all test cases pass

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_cron/detail/deploy_test_cron/1126/pipeline
log:

[artifacts-pulsar-cluster-upgrade-1126-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/12308436/artifacts-pulsar-cluster-upgrade-1126-server-logs.tar.gz)

### Anything else?

For standalone, standalone pod also will restart.

```
[2023/08/08 10:25:53.191 +00:00] [INFO] [segments/search.go:97] ["search growing/sealed segments without indexes"] [traceID=a717857fbe480c2062fb9f276499710e] [segmentIDs="[443413145022342787]"]
[2023/08/08 10:25:53.191 +00:00] [INFO] [segments/search.go:97] ["search growing/sealed segments without indexes"] [traceID=a717857fbe480c2062fb9f276499710e] [segmentIDs="[443414020826211408,443413145022342789,443414020826211297]"]
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4770fca290c80 pc=0x7f0204cf00c1]

runtime stack:
runtime.throw({0x3f512ed?, 0x7f0204ce89da?})
	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0x7efc6478ef10 sp=0x7efc6478eee0 pc=0x15367d1
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:802 +0x3a9 fp=0x7efc6478ef60 sp=0x7efc6478ef10 pc=0x154d489

goroutine 331341 [syscall]:
non-Go function
	pc=0x7f0204cf00c1
non-Go function
	pc=0x7f0204d44949
non-Go function
	pc=0x7f0204d38713
non-Go function
	pc=0x7f0204d3994c
non-Go function
	pc=0x7f0204d3eb4b
_cgo_98a85cac14ef_Cfunc_ReduceSearchResultsAndFillData
	/tmp/go-build/cgo-gcc-prolog:103 pc=0x374e38b
runtime.cgocall(0x374e350, 0xc00c73d9a0)
	/usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc00c73d978 sp=0xc00c73d940 pc=0x14ff6bc
github.com/milvus-io/milvus/internal/querynodev2/segments._Cfunc_ReduceSearchResultsAndFillData(0xc00da228f0, 0x7efcc5c4f000, 0xc00e112b90, 0x2, 0xc00d5dabc8, 0xc00d5dabc0, 0x1)
	_cgo_gotypes.go:726 +0x55 fp=0xc00c73d9a0 sp=0xc00c73d978 pc=0x3474735
github.com/milvus-io/milvus/internal/querynodev2/segments.ReduceSearchResultsAndFillData.func1(0x390b120?, 0xc00da228e8?, 0x43ee910?, 0xc00267c580?, 0xc000549a20?, 0x0?, 0x0?)
	/go/src/github.com/milvus-io/milvus/internal/querynodev2/segments/reduce.go:100 +0xdd fp=0xc00c73da30 sp=0xc00c73d9a0 pc=0x347d15d
github.com/milvus-io/milvus/internal/querynodev2/segments.ReduceSearchResultsAndFillData(0xc00d167d10, {0xc00e112b80, 0x2, 0xc00267c580?}, 0x4aa6334?, {0xc00d5dabc8, 0x1, 0x0?}, {0xc00d5dabc0, 0x1, ...})
	/go/src/github.com/milvus-io/milvus/internal/querynodev2/segments/reduce.go:100 +0x2bc fp=0xc00c73dae0 sp=0xc00c73da30 pc=0x347cf9c
github.com/milvus-io/milvus/internal/querynodev2/tasks.(*SearchTask).Execute(0xc004343140)
	/go/src/github.com/milvus-io/milvus/internal/querynodev2/tasks/task.go:177 +0x598 fp=0xc00c73deb8 sp=0xc00c73dae0 pc=0x34a3218
github.com/milvus-io/milvus/internal/querynodev2/tasks.(*scheduler).exec.func1()
	/go/src/github.com/milvus-io/milvus/internal/querynodev2/tasks/concurrent_safe_scheduler.go:193 +0xec fp=0xc00c73df28 sp=0xc00c73deb8 pc=0x34a066c
github.com/milvus-io/milvus/pkg/util/conc.(*Pool[...]).Submit.func1()
	/go/src/github.com/milvus-io/milvus/pkg/util/conc/pool.go:78 +0xbc fp=0xc00c73df88 sp=0xc00c73df28 pc=0x300009c
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
	/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.2/worker.go:67 +0x97 fp=0xc00c73dfe0 sp=0xc00c73df88 pc=0x2e00137
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00c73dfe8 sp=0xc00c73dfe0 pc=0x156b9e1
created by github.com/panjf2000/ants/v2.(*goWorker).run
	/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.2/worker.go:48 +0x65

```
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_cron/detail/deploy_test_cron/1125/pipeline

log:
[artifacts-rocksmq-standalone-upgrade-1125-server-logs (2).tar.gz](https://github.com/milvus-io/milvus/files/12308464/artifacts-rocksmq-standalone-upgrade-1125-server-logs.2.tar.gz)

[artifacts-rocksmq-standalone-upgrade-1125-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/12308465/artifacts-rocksmq-standalone-upgrade-1125-pytest-logs.tar.gz)

**Comment by yah01** [comment]
No release, no target changed

**Comment by yanliang567** [comment]
> No release, no target changed

what do you mean?

**Comment by yah01** [comment]
> > No release, no target changed
> 
> what do you mean?

Just a debug note...

**Comment by yah01** [comment]
There are dup segments that one is growing and the other one is sealed, for both shards:
![image](https://github.com/milvus-io/milvus/assets/12216890/4e864eca-0dde-4ed0-95ec-5b7aea74e161)
![image](https://github.com/milvus-io/milvus/assets/12216890/7f8f9e11-1a69-4ca2-97c6-0285f3000f3f)

**Comment by yah01** [comment]
segments are not reduced done yet:
v0 (growing): 443413145022342789, 443414020826211297, 443414020826211408
v1 (sealed): 443413260285250033, 443413145022342787

growing 443413145022342789 recently got a delete operation

**Comment by xiaofan-luan** [comment]
please help on it~

**Comment by zhagnlu** [comment]
Can get coredump stack ?

**Comment by zhagnlu** [comment]
@zhuwenxing  help get the coredump to see more detail because log stack not enough and  core interface has many subinsterface.

**Comment by zhuwenxing** [comment]
@yah01 
It still reproduced in master-20230814-ae780e03
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_cron/detail/deploy_test_cron/1151/pipeline
log:

[artifacts-pulsar-cluster-upgrade-1151-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/12332668/artifacts-pulsar-cluster-upgrade-1151-server-logs.tar.gz)
[artifacts-pulsar-cluster-upgrade-1151-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/12332671/artifacts-pulsar-cluster-upgrade-1151-pytest-logs.tar.gz)

**Comment by yah01** [comment]
@liliu-z this test upgrades milvus from v2.2.5 to latest master, any incompatible changes in Knowhere between them?

**Comment by yah01** [comment]
/assign @cydrain 
Could you help with this? The index type is `BIN_IVF_FLAT`, and with `HAMMING` metric

**Comment by cydrain** [comment]
test with following Milvus + Knowhere combinations

Milvus commit | Knowhere commit | status
--------------------|--------------------------|--------
0717-5afea0   | 0721-f805be | ok
0717-5afea0   | 0810-aa4a42 |
0814-ae780e | 0721-f805be | panic


https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_cron/detail/deploy_test_cron/1175/pipeline/

**Comment by liliu-z** [comment]
Caused by enum order mismatch. Fix is on the way.

**Comment by cydrain** [comment]
verified:
https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_cron/detail/deploy_test_cron/1187/pipeline/

**Comment by yah01** [comment]
/assign @zhuwenxing 
This fixed and Knowhere upgraded, plz help check it

**Comment by zhuwenxing** [comment]
Verified and passed in image tag master-20230818-74fb244b
