### ISSUE TITLE
[Enhancement]: The error message is not clear

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#26275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

![img_v2_6a6141fd-2e3b-4b32-bf2e-08d16ca20f4g](https://github.com/milvus-io/milvus/assets/83447078/3248d634-ffa3-40a9-b954-933801a95e47)

We should print out what is the operation we are not supporting.

**Comment by leximAI** [comment]
I spent hours trying to troubleshoot the inability to insert records into Zilliz/Milvus. The local version worked fine, but the cloud version (Zilliz) kept throwing an exception that looked something like "need to connect". When I used the connection APIs, all the connections, collections, etc. were correct. 

Also, when enumerating connections, I would prefer a return value than an output to the terminal. Likewise, some of the other APIs do not return values, instead, they throw exceptions. This is a questionable software engineering practice...making it very hard to troubleshoot, and requiring exception handlers around every pymilvus call.

**Comment by xiaofan-luan** [comment]
> I spent hours trying to troubleshoot the inability to insert records into Zilliz/Milvus. The local version worked fine, but the cloud version (Zilliz) kept throwing an exception that looked something like "need to connect". When I used the connection APIs, all the connections, collections, etc. were correct.
> 
> Also, when enumerating connections, I would prefer a return value than an output to the terminal. Likewise, some of the other APIs do not return values, instead, they throw exceptions. This is a questionable software engineering practice...making it very hard to troubleshoot, and requiring exception handlers around every pymilvus call.

This indicate "unsupported expr proto" means you are trying to use some unknown expr.

If you can show your code about what expr you are using that would be super helpful.

Unfortunately all the error details are in the error message and to maintain error code is a difficult task on a distributed system because the error goes through 2-3 diffenrent nodes and error will be wrapped multiple times. So far we'd like to improve it case by case.

**Comment by xiaofan-luan** [comment]
/assign @jiaoew1991 
/assign @longjiquan 
could you work on improve this error message? at least I want to know what the wrong expr is

**Comment by longjiquan** [comment]
I think this error was raised during rolling upgrade, especially when we upgrade the FE before the BE. Anyway, the error message is not clear and I will fix this.

**Comment by longjiquan** [comment]
Already fixed by #26365 and #26366

**Comment by jiaoew1991** [comment]
keep it
