### ISSUE TITLE
[Bug]: After milvus runs for a day, the overall response becomes slow and the service is unavailable

### ISSUE THREAD

**Issue by Cactus-L** [milvus-io/milvus#26307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.12
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): jdk
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 32c 128g *3
- GPU: no
- Others:
```

### Current Behavior

After milvus runs for a day, the overall response becomes slow and the service is unavailable
the err msg for response is  : DEADLINE_EXCEEDED: deadline exceeded after 19.999893177s

use background：
a lot of collections were created on this day, about 500
and all of these collection indexes are created by FLAT

### Milvus Log

milvus log info：
https://pan.baidu.com/s/1lNSwDdKLzm-0raNY-fDR-A?pwd=nmnu

**Comment by xiaofan-luan** [comment]
We have to fix the collection number issue. at least the limitation should not be a few hundred

**Comment by Cactus-L** [comment]
> We have to fix the collection number issue. at least the limitation should not be a few hundred

what is the meaning? Is there any way to solve this problem now?

**Comment by yanliang567** [comment]
@Cactus-L could you please share more info about your 500 collections? any chance you could use partition key feature as a workaround or a better solution for now?

/unassign

**Comment by yanliang567** [comment]
> @Cactus-L could you please share more info about your 500 collections? any chance you could use partition key feature as a workaround or a better solution for now?  Click here for more info about partition key:https://milvus.io/docs/partition_key.md#Partition-Key
> 
> /unassign

**Comment by Cactus-L** [comment]
> 

> > @Cactus-L could you please share more info about your 500 collections? any chance you could use partition key feature as a workaround or a better solution for now?  Click here for more info about partition key:https://milvus.io/docs/partition_key.md#Partition-Key
> > /unassign
ok, I can try the way of partition key. 
Can you tell me the main reason for the current problem? I will try my best to avoid it.

**Comment by aoiasd** [comment]
> > 
> 
> > > @Cactus-L could you please share more info about your 500 collections? any chance you could use partition key feature as a workaround or a better solution for now?  Click here for more info about partition key:https://milvus.io/docs/partition_key.md#Partition-Key
> > > /unassign
> > > ok, I can try the way of partition key.
> > > Can you tell me the main reason for the current problem? I will try my best to avoid it.

Every shard of collection will send empty message to message queue for push time tick, so too much collection means produce and consume will be very frequent. 
And set a larger proxy.timeTickInterval could help reduce frequency, but search or query will wait longer if use strong consistency.

And because we limit topic num of message queue, if shard num more than your dmlChannelNum, some shard will use same topic of message queue, and will read some invaild data of other shard, and will increase pressure on message queue.
So set a larger rootCoord.dmlChannelNum could help.

**Comment by Cactus-L** [comment]
> 

got it, thx
