### ISSUE TITLE
[Bug]: IndexNode panic while create job if the storage config is nil

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#26301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/12216890/dc1ad88a-a040-4d82-8e63-fe39ec731594)

**Comment by yanliang567** [comment]
how to get the storage config nil?

**Comment by yah01** [comment]
> how to get the storage config nil?

Some tests use empty request to conduct, the Milvus never use a nil storage config
