### ISSUE TITLE
[Enhancement]: Use shared pointer to protect segment from releasing while reduce

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#26313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

- The segment should be wrapped with a shared pointer (now it's unique pointer)
- The search result should store the segment with a shared pointer (now it's `void*`)

### Why is this needed?

We have suffered from the reduce panic too many times, this should be avoided in segcore no matter what the Milvus implementation is.

**Comment by xiaofan-luan** [comment]
I think we have segment level lock right?
Why not keep the read lock until we finish reduce?

**Comment by yah01** [comment]
> I think we have segment level lock right? Why not keep the read lock until we finish reduce?

The current impl splits search and reduce into two steps, the lock is not held during the gap of the two steps

**Comment by yah01** [comment]
> I think we have segment level lock right? Why not keep the read lock until we finish reduce?

Keep the lock held is also not easy to maintain, it requires us to be careful to manage the errors, and maybe we have to provide additional CGO function to release the lock if we got error

**Comment by yah01** [comment]
We shall not depend the impl of Milvus, all done in Segcore would be perfect. We can't directly use shared pointer to protect the segment as we need to export the segment to C binding, two ways to reach our goals:
- Use `boost::intrusive_ptr`, it's embedded ref count pointer
- Use a static map to ref the `std::shared_ptr`

**Comment by xiaofan-luan** [comment]
> We shall not depend the impl of Milvus, all done in Segcore would be perfect. We can't directly use shared pointer to protect the segment as we need to export the segment to C binding, two ways to reach our goals:
> 
> * Use `boost::intrusive_ptr`, it's embedded ref count pointer
> * Use a static map to ref the `std::shared_ptr`

This is not actually doable for the following reasons:
1) We are not limited at only using data ptr when reduce, we may use many other info in segment so these has to be guarded too. 
2) Use shared ptr may risk at memory leakage. especially we don't have any idea about when golang do gc

**Comment by xiaofan-luan** [comment]
Milvus user has to take care about segcore anyway. 
I want to think of way to guarantee no concurrent release/load at same time.
The easiast way is to add a segment level read write lock
