### ISSUE TITLE
[Bug]: The cpu usage is too high and data migration encounters problems

### ISSUE THREAD

**Issue by darkerin** [milvus-io/milvus#26327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.11, v2.2.12
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.8
- OS(Ubuntu or CentOS): ubuntu 18.04
- CPU/Memory: 4C/32G
- GPU: 
- Others:
```

### Current Behavior

In fact, I encountered three problems

1. The first is the problem of high CPU usage. I have more than 500 collections. When there is no query, the CPU load basically remains at 400%. Refer to #24812 
<img width="475" alt="image" src="https://github.com/milvus-io/milvus/assets/136887833/8abf3439-5a10-4f73-a3f0-7e07a37f3a68">
<img width="540" alt="image" src="https://github.com/milvus-io/milvus/assets/136887833/97147ec3-2e9a-4c81-a94f-80e312991eb4">

2.When I know that this problem may be improved in 2.2.12, I try to upgrade the version, I just modified the image version in docker-compose.yml and restart containers, but it can't even start properly, docker keeps scrolling the following logs:
```
[2023/08/12 17:48:33.950 +00:00] [WARN] [flowgraph/node.go:204] ["Invalid operate message input"] ["input length"=0]
[2023/08/12 17:48:33.950 +00:00] [WARN] [flowgraph/node.go:204] ["Invalid operate message input"] ["input length"=0]
[2023/08/12 17:48:33.950 +00:00] [WARN] [server/rocksmq_impl.go:768] ["rocksmq consume too slowly"] [topic=by-dev-rootcoord-dml_0] ["get lock elapse"=232] ["iterator elapse"=0] ["moveConsumePosTime elapse"=0] ["total consume elapse"=232]
[2023/08/12 17:48:33.951 +00:00] [WARN] [server/rocksmq_impl.go:768] ["rocksmq consume too slowly"] [topic=by-dev-rootcoord-dml_0] ["get lock elapse"=233] ["iterator elapse"=0] ["moveConsumePosTime elapse"=0] ["total consume elapse"=233]
[2023/08/12 17:48:33.952 +00:00] [WARN] [flowgraph/node.go:204] ["Invalid operate message input"] ["input length"=0]
[2023/08/12 17:48:33.952 +00:00] [WARN] [flowgraph/node.go:204] ["Invalid operate message input"] ["input length"=0]
[2023/08/12 17:48:33.952 +00:00] [WARN] [flowgraph/node.go:204] ["Invalid operate message input"] ["input length"=0]
[2023/08/12 17:48:33.952 +00:00] [WARN] [flowgraph/node.go:204] ["Invalid operate message input"] ["input length"=0]
[2023/08/12 17:48:33.952 +00:00] [WARN] [flowgraph/node.go:204] ["Invalid operate message input"] ["input length"=0]
[2023/08/12 17:48:33.954 +00:00] [WARN] [flowgraph/node.go:204] ["Invalid operate message input"] ["input length"=0]
[2023/08/12 17:48:33.954 +00:00] [WARN] [flowgraph/node.go:204] ["Invalid operate message input"] ["input length"=0]
[2023/08/12 17:48:33.954 +00:00] [WARN] [flowgraph/node.go:204] ["Invalid operate message input"] ["input length"=0]
[2023/08/12 17:48:33.954 +00:00] [WARN] [flowgraph/node.go:204] ["Invalid operate message input"] ["input length"=0]
[2023/08/12 17:48:33.954 +00:00] [WARN] [flowgraph/node.go:204] ["Invalid operate message input"] ["input length"=0]
[2023/08/12 17:48:33.954 +00:00] [WARN] [flowgraph/node.go:204] ["Invalid operate message input"] ["input length"=0]
[2023/08/12 17:48:33.954 +00:00] [WARN] [flowgraph/node.go:204] ["Invalid operate message input"] ["input length"=0]
[2023/08/12 17:48:33.955 +00:00] [WARN] [server/rocksmq_impl.go:768] ["rocksmq consume too slowly"] [topic=by-dev-rootcoord-dml_0] ["get lock elapse"=237] ["iterator elapse"=0] ["moveConsumePosTime elapse"=0] ["total consume elapse"=237]
[2023/08/12 17:48:33.956 +00:00] [WARN] [flowgraph/node.go:204] ["Invalid operate message input"] ["input length"=0]
[2023/08/12 17:48:33.956 +00:00] [WARN] [flowgraph/node.go:204] ["Invalid operate message input"] ["input length"=0]
[2023/08/12 17:48:33.956 +00:00] [WARN] [flowgraph/node.go:204] ["Invalid operate message input"] ["input length"=0]
[2023/08/12 17:48:33.956 +00:00] [WARN] [flowgraph/node.go:204] ["Invalid operate message input"] ["input length"=0]
[2023/08/12 17:48:33.956 +00:00] [WARN] [flowgraph/node.go:204] ["Invalid operate message input"] ["input length"=0]
[2023/08/12 17:48:33.956 +00:00] [WARN] [flowgraph/node.go:204] ["Invalid operate message input"] ["input length"=0]
[2023/08/12 17:48:33.956 +00:00] [WARN] [flowgraph/node.go:204] ["Invalid operate message input"] ["input length"=0]
[2023/08/12 17:48:33.956 +00:00] [WARN] [flowgraph/node.go:204] ["Invalid operate message input"] ["input length"=0]
[2023/08/12 17:48:33.956 +00:00] [WARN] [flowgraph/node.go:204] ["Invalid operate message input"] ["input length"=0]
```

3. I can only switch back to version 2.2.11 and try to change to a server with a better CPU. So I first stopped the milvus container, sent the entire `volumes` directory (about 30G) to the new server via `scp` command, with the same system version and milvus version. 

However, after starting the containers on the new machine, the program runs successfully, but it doesn't look like there is any data (cpu and memory usage are close to 0), and I can't see any collection when using `attu`.

[milvus (3).log](https://github.com/milvus-io/milvus/files/12331623/milvus.3.log)

<img width="1448" alt="image" src="https://github.com/milvus-io/milvus/assets/136887833/0b677f33-68cc-4b5a-9402-a07dedcb723b">

### Expected Behavior

I hope I can reduce the CPU usage and be able to migrate data normally.

**Comment by xiaofan-luan** [comment]
please help on verifying it

**Comment by darkerin** [comment]
This is an online problem, hope to get help, thanks a lot.

Other friends who may pay attention to this issue cc @yud11 @shenyunlong @Cactus-L

**Comment by xiaofan-luan** [comment]
> 3\. sent the entire `volumes`

To solve the probelm, you will need to reserve data for minio and etcd and only remove data in /rdb directory

**Comment by xiaofan-luan** [comment]
I think that is the fastest way you can recover the cluster.
Also,  if you need further support, please your contact info to xiaofan.luan@zilliz.com and we can try our best to help

**Comment by darkerin** [comment]
> To solve the probelm, you will need to reserve data for minio and etcd and only remove data in /rdb directory

Is my vector data in collections still there after deleting the /rdb directory?

**Comment by xiaofan-luan** [comment]
another to recover
proxy.timeTickInterval: change to 1000 ms

This will help to create more collection. Make sure you use bounded staleness consistency or eventual consistency

**Comment by darkerin** [comment]
> all the sealed segment will be on minio. You may lose part of your data if it insert recently and didn't flush to disk.

Hi, this is the file size of my volums directory 

<img width="610" alt="image" src="https://github.com/milvus-io/milvus/assets/136887833/0d9a022d-e7fc-45ca-97ad-6180a31313b0">

<img width="702" alt="image" src="https://github.com/milvus-io/milvus/assets/136887833/4a19894b-857e-495e-888e-52748378580c">

It seems that the data is concentrated in the milvus directory, and the data will not be lost after deletion?

**Comment by darkerin** [comment]
> another to recover proxy.timeTickInterval: change to 1000 ms
> 
> This will help to create more collection. Make sure you use bounded staleness consistency or eventual consistency

OK, I will to try this method. But I observed that another friend couldn't start after modifying this configuration, so I want to confirm the compatibility of the data first

<img width="950" alt="image" src="https://github.com/milvus-io/milvus/assets/136887833/cb024a97-50d6-4ef3-a906-8dc68918e7cd">

**Comment by xiaofan-luan** [comment]
> > another to recover proxy.timeTickInterval: change to 1000 ms
> > This will help to create more collection. Make sure you use bounded staleness consistency or eventual consistency
> 
> OK, I will to try this method. But I observed that another friend couldn't start after modifying this configuration, so I want to confirm the compatibility of the data first
> 
> <img alt="image" width="950" src="https://user-images.githubusercontent.com/136887833/260389126-cb024a97-50d6-4ef3-a906-8dc68918e7cd.png">

I guess there might be some other reason of not able to start the service. We Start to work on improving multi collection performance but seems reduce time tick interval seems to be a good tradeoff

**Comment by darkerin** [comment]
> > all the sealed segment will be on minio. You may lose part of your data if it insert recently and didn't flush to disk.
> 
> Hi, this is the file size of my volums directory
> 
> <img alt="image" width="610" src="https://user-images.githubusercontent.com/136887833/260388411-0d9a022d-e7fc-45ca-97ad-6180a31313b0.png"> <img alt="image" width="702" src="https://user-images.githubusercontent.com/136887833/260388494-4a19894b-857e-495e-888e-52748378580c.png">
> It seems that the data is concentrated in the milvus directory, and the data will not be lost after deletion?

How to solve this problem, If I can delete rdb_data and rdb_meta_key directly, my minio directory is only 2.2M size

**Comment by xiaofan-luan** [comment]
because you already delete your volume?

**Comment by darkerin** [comment]
> because you already delete your volume?

I have never actively deleted data. The picture below is the `volums` directory that I am currently running online. The picture above is copied a few days ago

<img width="528" alt="image" src="https://github.com/milvus-io/milvus/assets/136887833/53a04d69-8ddf-468f-b62f-34cfd2a46221">

This volums directory has undergone a server migration a month ago and has been upgraded from version 2.2.8 to version 2.2.11. At that time, I tried several times and then succeeded.  (I remember that it was about 60g before the migration, and it suddenly became 15G one day later without my intervention. since the service can run, I didn't care)

**Comment by xiaofan-luan** [comment]
> > because you already delete your volume?
> 
> I have never actively deleted data. The picture below is the `volums` directory that I am currently running online. The picture above is copied a few days ago
> 
> <img alt="image" width="528" src="https://user-images.githubusercontent.com/136887833/260422331-53a04d69-8ddf-468f-b62f-34cfd2a46221.png">
> This volums directory has undergone a server migration a month ago and has been upgraded from version 2.2.8 to version 2.2.11. At that time, I tried several times and then succeeded. (I remember that it was about 60g before the migration, and it suddenly became 15G one day later without my intervention. since the service can run, I didn't care)

but is there a estimation on how many data you should have?

**Comment by xiaofan-luan** [comment]
data volume decrease might be simply because garbage collection logic

**Comment by xiaofan-luan** [comment]
you can estimated your data size by 
entity count * dim * 4 * 3

**Comment by xiaofan-luan** [comment]
and  didn't see a reason that 2G minio directory suddenly went to 2.2M without any delete or TTL

**Comment by darkerin** [comment]
> you can estimated your data size by entity count * dim * 4 * 3

thanks a lot, from this point of view, maybe 2G is all the data, maybe some data in scp is not completely transferred, I'll try again tonight

**Comment by punkerpunker** [comment]
It feels like I am experiencing similar behaviour. I'll gather more details and will drop another line here

**Comment by darkerin** [comment]
> timeTickInterval

Thanks, this problem has been improved. May I ask if I can continue to increase the timeTickInterval parameter to get more collections. For example, can a standAlone node maintain 10000 collections? (The limit in the docs is 65535)

**Comment by darkerin** [comment]
> > timeTickInterval

@xiaofan-luan 

Thanks a lot, this problem has been improved. May I ask if I can continue to increase the timeTickInterval parameter to get more collections. For example, can a standAlone node maintain 10000 collections? (The limit in the docs is 65535)

**Comment by xiaofan-luan** [comment]
> > > timeTickInterval
> 
> @xiaofan-luan
> 
> Thanks a lot, this problem has been improved. May I ask if I can continue to increase the timeTickInterval parameter to get more collections. For example, can a standAlone node maintain 10000 collections? (The limit in the docs is 65535)

I don't think it's a good idea to do so.

Think of using partition key to split data in different tenant.

Or you can verify on 2.3, which may significantly reduce the overhead to send timetick

**Comment by xiaofan-luan** [comment]
But again I'm not confident 2.3 can serve 10000 collections.

**Comment by xiaofan-luan** [comment]
/assign @yanliang567 

can we test on it?

**Comment by darkerin** [comment]
> > > > timeTickInterval
> > 
> > 
> > @xiaofan-luan
> > Thanks a lot, this problem has been improved. May I ask if I can continue to increase the timeTickInterval parameter to get more collections. For example, can a standAlone node maintain 10000 collections? (The limit in the docs is 65535)
> 
> I don't think it's a good idea to do so.
> 
> Think of using partition key to split data in different tenant.
> 
> Or you can verify on 2.3, which may significantly reduce the overhead to send timetick

Thanks,  now I want to try to use partition for data isolation, but my existing data is in the "Default partition" of each collection, so I try to add a custom parition to the existing collection.

<img width="1649" alt="image" src="https://github.com/milvus-io/milvus/assets/136887833/6e51051e-6410-401c-89f7-7488925d94d4">

But when I want to load the default partition, I get an error:

```
 <MilvusException: (code=1, message=partition is not exist: Default partition)>
```

How should I distinguish between the "Default parititon" and the newly added parittion? If I don't specify a parittion when loading collection and searching, will I only query the data in "Default partition" or all data in collection?

**Comment by darkerin** [comment]
> But again I'm not confident 2.3 can serve 10000 collections.

Thanks, looking forward to the results of the pressure test

**Comment by darkerin** [comment]
> > > > timeTickInterval
> > 
> > 
> > @xiaofan-luan
> > Thanks a lot, this problem has been improved. May I ask if I can continue to increase the timeTickInterval parameter to get more collections. For example, can a standAlone node maintain 10000 collections? (The limit in the docs is 65535)
> 
> I don't think it's a good idea to do so.
> 
> Think of using partition key to split data in different tenant.
> 
> Or you can verify on 2.3, which may significantly reduce the overhead to send timetick

I try to use partition to split data, I can't seem to load partitions separately in a collection, this makes my current model unable to run under the partitions.
see https://github.com/milvus-io/milvus/issues/26700
