### ISSUE TITLE
[Bug]: Searching on a collection with FLAT index does not give the correct output

### ISSUE THREAD

**Issue by ArijitSinghEDA** [milvus-io/milvus#26337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.6
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq   
- SDK version(e.g. pymilvus v2.0.0rc2): None
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: Intel Gold (Do not know the exact specifics as not an administrator of the server)
- GPU: None
- Others: None
```

### Current Behavior

I have created a collection with FLAT index, and when I search on it, it gives a lot less output than when I searched locally using loops. It missed a lot of entries. Also need to explain the fact that my collection created has ```nlist``` param set to 27. Is this interfering with the results?

### Expected Behavior

In both cases should get same number of output.

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version: 2.2.6
> - Deployment mode(standalone or cluster): standalone
> - MQ type(rocksmq, pulsar or kafka): rocksmq   
> - SDK version(e.g. pymilvus v2.0.0rc2): None
> - OS(Ubuntu or CentOS): Ubuntu
> - CPU/Memory: Intel Gold (Do not know the exact specifics as not an administrator of the server)
> - GPU: None
> - Others: None
> ```
> 
> ### Current Behavior
> I have created a collection with FLAT index, and when I search on it, it gives a lot less output than when I searched locally using loops. It missed a lot of entries. Also need to explain the fact that my collection created has `nlist` param set to 27. Is this interfering with the results?
> 
> ### Expected Behavior
> In both cases should get same number of output.
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

FLAT index don't have nlist param. Are you sure you are using FLAT index? could you show your code?

**Comment by ArijitSinghEDA** [comment]
![Milvus](https://github.com/milvus-io/milvus/assets/132063833/07f6e41d-1b2d-4753-9d44-f491ee5d9690)

**Comment by ArijitSinghEDA** [comment]
`fields = [
    FieldSchema(
        name="id",
        dtype=DataType.INT64,
        description="ID",
        is_primary=True,
        auto_id=True
    ),
    FieldSchema(
        name="_path",
        dtype=DataType.VARCHAR,
        max_length=65000,
        description='_path'
    ),
    FieldSchema(
        name="embeddings",
        dtype=DataType.FLOAT_VECTOR,
        description="embeddings",
        dim=dim
    )
]

schema = CollectionSchema(
    fields=fields,
    description="A"
)

name = "img_224_crop"

if utility.has_collection(name):
    utility.drop_collection(name)

coll = Collection(
    name=name,
    schema=schema
)

index_params = {
    'metric_type': 'IP',
    'index_type': 'FLAT',
    'params': {
        'nlist': int(dim ** 0.5)
    }
}

coll.create_index(field_name='embeddings', index_params=index_params)`

**Comment by xiaofan-luan** [comment]
what is data? and how do you run search?

**Comment by ArijitSinghEDA** [comment]
> and what is the recall you get? I'm not sure why you use FLAT index with nlist params?

I do not how to get the recall
I had copy pasted the code from some other file I had written which used IVF_FLAT indexing, so forgot to take out the ```nlist``` parameter. But shouldn't the searching ignore this parameter because of FLAT indexing?

**Comment by ArijitSinghEDA** [comment]
> what is data? and how do you run search?

It is a dataset of path to photos with their embeddings.
This is the search I run:
```
search_params = {
        "metric_type": 'IP'
    }

coll.search(
                data=d.tolist(),
                anns_field="embeddings",
                param=search_params,
                limit=2,
                expr=None,
                partition_names=partitions,
                output_fields=['_path'],
                round_decimal=6,
                consistency_level="Strong"
            )
```

**Comment by xiaofan-luan** [comment]
> > what is data? and how do you run search?
> 
> It is a dataset of path to photos with their embeddings. This is the search I run:
> 
> ```
> search_params = {
>         "metric_type": 'IP'
>     }
> 
> coll.search(
>                 data=d.tolist(),
>                 anns_field="embeddings",
>                 param=search_params,
>                 limit=2,
>                 expr=None,
>                 partition_names=partitions,
>                 output_fields=['_path'],
>                 round_decimal=6,
>                 consistency_level="Strong"
>             )
> ```

your code seems to be ok. what is the sample data, the result you expect and the actual result?
did you have a chance to try Milvus 2.2.13?

**Comment by xiaofan-luan** [comment]
and it would be better if you write a script to reproduce on latest 2.2.13, it will make our life much easier.

**Comment by ArijitSinghEDA** [comment]
> and it would be better if you write a script to reproduce on latest 2.2.13, it will make our life much easier.

I work on a system with an AMD processor so I cannot use Milvus locally, and the server where I use Milvus has restricted access where I cannot code as per my convenience. I would have loved to try the latest stable version, but currently am stuck with version 2.2.6. If you can provide a solution for this version, it would help me a lot

**Comment by xiaofan-luan** [comment]
> > and it would be better if you write a script to reproduce on latest 2.2.13, it will make our life much easier.
> 
> I work on a system with an AMD processor so I cannot use Milvus locally, and the server where I use Milvus has restricted access where I cannot code as per my convenience. I would have loved to try the latest stable version, but currently am stuck with version 2.2.6. If you can provide a solution for this version, it would help me a lot

Without the data I guess we can not reproduce it.

**Comment by yanliang567** [comment]
FLAT is a special index type that it actually use brute force search, so it should not return less results. My suggestion is that you can compare the distances between 2 results. If Milvus returns that results that did not match the distance to the ground truth, it would be a bug.
/assign @ArijitSinghEDA 
/unassign

**Comment by xiaofan-luan** [comment]
> FLAT is a special index type that it actually use brute force search, so it should not return less results. My suggestion is that you can compare the distances between 2 results. If Milvus returns that results that did not match the distance to the ground truth, it would be a bug. /assign @ArijitSinghEDA /unassign

Is there any known bug for FLAT index to ignore some data?

**Comment by yanliang567** [comment]
> > FLAT is a special index type that it actually use brute force search, so it should not return less results. My suggestion is that you can compare the distances between 2 results. If Milvus returns that results that did not match the distance to the ground truth, it would be a bug. /assign @ArijitSinghEDA /unassign
> 
> Is there any known bug for FLAT index to ignore some data?

No

**Comment by ArijitSinghEDA** [comment]
> FLAT is a special index type that it actually use brute force search, so it should not return less results. My suggestion is that you can compare the distances between 2 results. If Milvus returns that results that did not match the distance to the ground truth, it would be a bug. /assign @ArijitSinghEDA /unassign

The distances are same for both results

**Comment by xiaofan-luan** [comment]
> > FLAT is a special index type that it actually use brute force search, so it should not return less results. My suggestion is that you can compare the distances between 2 results. If Milvus returns that results that did not match the distance to the ground truth, it would be a bug. /assign @ArijitSinghEDA /unassign
> 
> The distances are same for both results

can you define your data, your query , the expect result and they result you get more clearly

**Comment by xiaofan-luan** [comment]
currently I define this not as a bug but the misunderstanding of the system behaviour

**Comment by ArijitSinghEDA** [comment]
> > > FLAT is a special index type that it actually use brute force search, so it should not return less results. My suggestion is that you can compare the distances between 2 results. If Milvus returns that results that did not match the distance to the ground truth, it would be a bug. /assign @ArijitSinghEDA /unassign
> > 
> > 
> > The distances are same for both results
> 
> can you define your data, your query , the expect result and they result you get more clearly

Data:
    A dataset containing path to images and their respective embeddings (~13000 rows)
Query:
    Need to find the top 1 similar image for each image. Both should have a minimum cosine similarity of 0.999996
Expected result:
    After arranging the results, a dataset of ~500 rows should be created in the form

    | image_1 | image_2 | cosine_similarity |
    | --------- | --------- | ------------------ |
    | path/to/image_1 | path/to/image_2 | 1.00 |
    | path/to/image_3 | path/to/image_4 | 0.999998 |
    | path/to/image_5 | path/to/image_6 | 0.999997 |

Actual result:
    After arranging the results, a dataset of ~160 rows are being created in the form

    | image_1 | image_2 | cosine_similarity |
    | --------- | --------- | ------------------ |
    | path/to/image_1 | path/to/image_2 | 1.00 |
    | path/to/image_3 | path/to/image_4 | 0.999998 |
    | path/to/image_5 | path/to/image_6 | 0.999997 |

**Comment by xiaofan-luan** [comment]
> > > > FLAT is a special index type that it actually use brute force search, so it should not return less results. My suggestion is that you can compare the distances between 2 results. If Milvus returns that results that did not match the distance to the ground truth, it would be a bug. /assign @ArijitSinghEDA /unassign
> > > 
> > > 
> > > The distances are same for both results
> > 
> > 
> > can you define your data, your query , the expect result and they result you get more clearly
> 
> Data: A dataset containing path to images and their respective embeddings (~13000 rows) (_The embeddings are normalized_)
> 
> Query: Need to find the top 1 similar image for each image. Both should have a minimum cosine similarity of 0.999996
> 
> Expected result: After arranging the results, a dataset of ~500 rows should be created in the form
> 
> image_1	image_2	cosine_similarity
> path/to/image_1	path/to/image_2	1.00
> path/to/image_3	path/to/image_4	0.999998
> path/to/image_5	path/to/image_6	0.999997
> Actual result: After arranging the results, a dataset of ~160 rows are being created in the form
> 
> image_1	image_2	cosine_similarity
> path/to/image_1	path/to/image_2	1.00
> path/to/image_3	path/to/image_4	0.999998
> path/to/image_5	path/to/image_6	0.999997

I did see any difference from what you expected and what you actaully get?

**Comment by ArijitSinghEDA** [comment]
> I did see any difference from what you expected and what you actaully get?

Yes. Some rows which I got locally weren't available when searched using Milvus.

**Comment by xiaofan-luan** [comment]
but these seems to be very close to each other, I'm not sure what's your expectation of your search result would be. Sorry I can't help.
And with that small amount of embeddings, you can simply use faiss or numpy maybe?

**Comment by ArijitSinghEDA** [comment]
> but these seems to be very close to each other, I'm not sure what's your expectation of your search result would be. Sorry I can't help. And with that small amount of embeddings, you can simply use faiss or numpy maybe?

The FLAT index should work like the way @yanliang567 described, so I believe there should not be such a huge difference.

The small data is just a sample. It will grow to 10 million or more.


Anyway, I am guessing that ```nlist``` parameter is interfering in some way, so I will just avoid it.

**Comment by ArijitSinghEDA** [comment]
I am trying to create a FLAT index using
```
index_params = {
    'metric_type': 'IP',
    'index_type': 'FLAT'
}
```

It is throwing error:
```
pymilvus.exceptions.ParamError: <ParamError: (code=1, message=Params must contains key: 'params')>
```

In the documentation online, there is no mentioned index param for FLAT index

**Comment by yanliang567** [comment]
try to give an empty params, e.g.:
```
index_params = {
    'metric_type': 'IP',
    'index_type': 'FLAT',
    'params': {}
}
```

**Comment by ArijitSinghEDA** [comment]
> try to give an empty params, e.g.:
> 
> ```
> index_params = {
>     'metric_type': 'IP',
>     'index_type': 'FLAT',
>     'params': {}
> }
> ```

Thanks ! Will try it now

**Comment by ArijitSinghEDA** [comment]
> Thanks ! Will try it now

I did get the same number of rows, but the thing is that the speed for searching using FLAT and IVF_FLAT are comparable. Is it because 13000 rows are too less for Milvus?

**Comment by yanliang567** [comment]
> > Thanks ! Will try it now
> 
> I did get the same number of rows, but the thing is that the speed for searching using FLAT and IVF_FLAT are comparable. Is it because 13000 entities are too less for Milvus?

yes

**Comment by ArijitSinghEDA** [comment]
Closing the issue now.
