### ISSUE TITLE
[Bug]: milvus api timeout after run for over months

### ISSUE THREAD

**Issue by sunnyningsu** [milvus-io/milvus#26351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.7
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.8
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz / 8G
- GPU: N/A
- Others:
```

### Current Behavior

the calls from python lib(pymilvus) got timeouts after 2 months I deployed the milvus.

### Expected Behavior

the api call should return right result

### Steps To Reproduce

```markdown
1. I have deployed the standalone milvus with docker
2. integrate the flask app with pymilvus
3. the behavior is normal at the beginning 2 months
4. all the pymilvus call got timeout after 2 months, then I restarted milvus docker service and it works.
```

### Milvus Log

{"log":"runtime: unexpected return pc for runtime.sigpanic called from 0x0\n","stream":"stderr","time":"2023-08-09T09:51:07.802089866Z"}
{"log":"stack: frame={sp:0xc0011a7d00, fp:0xc0011a7d50} stack=[0xc0011a7000,0xc0011a8000)\n","stream":"stderr","time":"2023-08-09T09:51:07.80211303Z"}
{"log":"0x000000c0011a7c00:  0x000000c0011a7c08  0x00000000013f8aa0 \u003cruntime.addOneOpenDeferFrame.func1+0x0000000000000000\u003e \n","stream":"stderr","time":"2023-08-09T09:51:07.802212496Z"}
{"log":"0x000000c0011a7c10:  0x0000000001410516 \u003cruntime.sigpanic+0x0000000000000336\u003e  0x000000c0011a7d00 \n","stream":"stderr","time":"2023-08-09T09:51:07.802322692Z"}
{"log":"0x000000c0011a7c20:  0x000000c0037d9380  0x0000000000000000 \n","stream":"stderr","time":"2023-08-09T09:51:07.802389209Z"}
{"log":"0x000000c0011a7c30:  0x000000c0011a7cf0  0x00000000013f9266 \u003cruntime.gopanic+0x0000000000000106\u003e \n","stream":"stderr","time":"2023-08-09T09:51:07.802522006Z"}
{"log":"0x000000c0011a7c40:  0x000000c0011a7d88  0x000000c000060500 \n","stream":"stderr","time":"2023-08-09T09:51:07.802639336Z"}
{"log":"0x000000c0011a7c50:  0x000000c0011a89b0  0x000000c0011a8a40 \n","stream":"stderr","time":"2023-08-09T09:51:07.802696793Z"}
{"log":"0x000000c0011a7c60:  0x0000000000000000  0x000000c005e976c0 \n","stream":"stderr","time":"2023-08-09T09:51:07.802787209Z"}
{"log":"0x000000c0011a7c70:  0x0000000000000100  0x00007f6439d4a090 \n","stream":"stderr","time":"2023-08-09T09:51:07.802832445Z"}
{"log":"0x000000c0011a7c80:  0x0000000000000007  0x0000000000000000 \n","stream":"stderr","time":"2023-08-09T09:51:07.802926075Z"}
{"log":"0x000000c0011a7c90:  0x000000c00103a000  0x0000000000000000 \n","stream":"stderr","time":"2023-08-09T09:51:07.802982688Z"}
{"log":"0x000000c0011a7ca0:  0x0000000000008000  0x000000c0037d93a0 \n","stream":"stderr","time":"2023-08-09T09:51:07.803084373Z"}
{"log":"0x000000c0011a7cb0:  0x000000c0037d9380  0x0000000000000000 \n","stream":"stderr","time":"2023-08-09T09:51:07.803091068Z"}
{"log":"0x000000c0011a7cc0:  0x0000000003a54ca0  0x00000000056ca170 \n","stream":"stderr","time":"2023-08-09T09:51:07.803155429Z"}
{"log":"0x000000c0011a7cd0:  0x0000000000000000  0x0000000000000000 \n","stream":"stderr","time":"2023-08-09T09:51:07.803259062Z"}
{"log":"0x000000c0011a7ce0:  0x0000000000000000  0x0000000000000000 \n","stream":"stderr","time":"2023-08-09T09:51:07.803309406Z"}
{"log":"0x000000c0011a7cf0:  0x000000c0011a7d40  0x0000000001410516 \u003cruntime.sigpanic+0x0000000000000336\u003e \n","stream":"stderr","time":"2023-08-09T09:51:07.803406587Z"}
{"log":"0x000000c0011a7d00: \u003c0x0000000003a54ca0  0x00000000056ca170 \n","stream":"stderr","time":"2023-08-09T09:51:07.803456649Z"}
{"log":"0x000000c0011a7d10:  0xffffffffffffffe0  0x0000000001448c7b \u003csyscall.Syscall+0x000000000000001b\u003e \n","stream":"stderr","time":"2023-08-09T09:51:07.803611022Z"}
{"log":"0x000000c0011a7d20:  0x000000c0011a8960  0x0000000001448c7b \u003csyscall.Syscall+0x000000000000001b\u003e \n","stream":"stderr","time":"2023-08-09T09:51:07.803663032Z"}
{"log":"0x000000c0011a7d30:  0x0000000000000202  0x002b000000000033 \n","stream":"stderr","time":"2023-08-09T09:51:07.803861541Z"}
{"log":"0x000000c0011a7d40:  0x002b000000000033 !0x0000000000000000 \n","stream":"stderr","time":"2023-08-09T09:51:07.803932069Z"}
{"log":"0x000000c0011a7d50: \u003e0x0000000000000000  0x0000000000000000 \n","stream":"stderr","time":"2023-08-09T09:51:07.803995851Z"}
{"log":"0x000000c0011a7d60:  0x000000c0011a7e40  0x0000000000000002 \n","stream":"stderr","time":"2023-08-09T09:51:07.804060961Z"}
{"log":"0x000000c0011a7d70:  0x0000000000000000  0x0000000001010080 \n","stream":"stderr","time":"2023-08-09T09:51:07.804110787Z"}
{"log":"0x000000c0011a7d80:  0x0000000000000000  0x0000000000000002 \n","stream":"stderr","time":"2023-08-09T09:51:07.80416166Z"}
{"log":"0x000000c0011a7d90:  0x0000000000203001  0x0000000000000000 \n","stream":"stderr","time":"2023-08-09T09:51:07.804256126Z"}
{"log":"0x000000c0011a7da0:  0x000000c007b17900  0x0000000000000000 \n","stream":"stderr","time":"2023-08-09T09:51:07.804308987Z"}
{"log":"0x000000c0011a7db0:  0xffffffffffffffff  0x0000000000000000 \n","stream":"stderr","time":"2023-08-09T09:51:07.804395693Z"}
{"log":"0x000000c0011a7dc0:  0x0000000000000010  0x0000000000000001 \n","stream":"stderr","time":"2023-08-09T09:51:07.804447676Z"}
{"log":"0x000000c0011a7dd0:  0x0000000000000001  0x0000000000000002 \n","stream":"stderr","time":"2023-08-09T09:51:07.804603641Z"}
{"log":"0x000000c0011a7de0:  0x00000000013cf625 \u003cruntime.mallocgc+0x00000000000006c5\u003e  0x00007f643592a5b8 \n","stream":"stderr","time":"2023-08-09T09:51:07.80527518Z"}
{"log":"0x000000c0011a7df0:  0x000000c00e390700  0x000000c0011a7ecc \n","stream":"stderr","time":"2023-08-09T09:51:07.805757744Z"}
{"log":"[2023/08/09 09:51:07.805 +00:00] [INFO] [proxy/impl.go:4798] [\"current rates in proxy\"] [proxyNodeID=72] [rates=\"[{\\\"rt\\\":6,\\\"r\\\":1.7976931348623157e+308},{\\\"rt\\\":7,\\\"r\\\":1.7976931348623157e+308},{\\\"rt\\\":5,\\\"r\\\":1.7976931348623157e+308},{\\\"rt\\\":8,\\\"r\\\":1.7976931348623157e+308},{\\\"rt\\\":9,\\\"r\\\":1.7976931348623157e+308}]\"]\n","stream":"stdout","time":"2023-08-09T09:51:07.806007308Z"}
{"log":"0x000000c0011a7e00:  0x000000c0037d9380  0x000000c0011a7f38 \n","stream":"stderr","time":"2023-08-09T09:51:07.806304005Z"}
{"log":"0x000000c0011a7e10:  0x000000c003999500  0x000000c0038e9f80 \n","stream":"stderr","time":"2023-08-09T09:51:07.806732734Z"}
{"log":"0x000000c0011a7e20:  0x000000c003999500  0x0000000000000040 \n","stream":"stderr","time":"2023-08-09T09:51:07.807158462Z"}
{"log":"0x000000c0011a7e30:  0x000000c0037d9408  0x000000c0037d94c8 \n","stream":"stderr","time":"2023-08-09T09:51:07.807534978Z"}
{"log":"0x000000c0011a7e40:  0x000000000000037f  0x00007f643a13e363 \n","stream":"stderr","time":"2023-08-09T09:51:07.807545742Z"}
{"log":"fatal error: unknown caller pc\n","stream":"stderr","time":"2023-08-09T09:51:07.807548941Z"}
{"log":"\n","stream":"stderr","time":"2023-08-09T09:51:07.809665539Z"}
{"log":"runtime stack:\n","stream":"stderr","time":"2023-08-09T09:51:07.809673431Z"}
{"log":"runtime.throw({0x3de1709?, 0x571a760?})\n","stream":"stderr","time":"2023-08-09T09:51:07.812799233Z"}
{"log":"\u0009/usr/local/go/src/runtime/panic.go:992 +0x71\n","stream":"stderr","time":"2023-08-09T09:51:07.81280942Z"}
{"log":"runtime.gentraceback(0x17f63968df7a0?, 0x7f63968df7a8?, 0xc008e0f520?, 0xc0037d9380?, 0x0, 0x0, 0x7fffffff, 0x7f63968df7c8, 0x400000002?, 0x0)\n","stream":"stderr","time":"2023-08-09T09:51:07.812906037Z"}
{"log":"\u0009/usr/local/go/src/runtime/traceback.go:254 +0x1a36\n","stream":"stderr","time":"2023-08-09T09:51:07.812913521Z"}
{"log":"runtime.addOneOpenDeferFrame.func1()\n","stream":"stderr","time":"2023-08-09T09:51:07.812917634Z"}
{"log":"\u0009/usr/local/go/src/runtime/panic.go:599 +0x6b\n","stream":"stderr","time":"2023-08-09T09:51:07.8129212Z"}
{"log":"runtime.systemstack()\n","stream":"stderr","time":"2023-08-09T09:51:07.812924022Z"}
{"log":"\u0009/usr/local/go/src/runtime/asm_amd64.s:469 +0x49\n","stream":"stderr","time":"2023-08-09T09:51:07.813330738Z"}
{"log":"\n","stream":"stderr","time":"2023-08-09T09:51:07.813338327Z"}
{"log":"goroutine 1364 [running]:\n","stream":"stderr","time":"2023-08-09T09:51:07.813342135Z"}
{"log":"runtime.systemstack_switch()\n","stream":"stderr","time":"2023-08-09T09:51:07.813346564Z"}
{"log":"\u0009/usr/local/go/src/runtime/asm_amd64.s:436 fp=0xc0011a7c00 sp=0xc0011a7bf8 pc=0x142c480\n","stream":"stderr","time":"2023-08-09T09:51:07.813354145Z"}
{"log":"runtime.addOneOpenDeferFrame(0xc0011a7d88?, 0xc000060500?, 0xc0011a89b0?)\n","stream":"stderr","time":"2023-08-09T09:51:07.813358427Z"}
{"log":"\u0009/usr/local/go/src/runtime/panic.go:598 +0x69 fp=0xc0011a7c40 sp=0xc0011a7c00 pc=0x13f8a49\n","stream":"stderr","time":"2023-08-09T09:51:07.81336229Z"}
{"log":"panic({0x3a54ca0, 0x56ca170})\n","stream":"stderr","time":"2023-08-09T09:51:07.813366527Z"}
{"log":"\u0009/usr/local/go/src/runtime/panic.go:798 +0x106 fp=0xc0011a7d00 sp=0xc0011a7c40 pc=0x13f9266\n","stream":"stderr","time":"2023-08-09T09:51:07.813370356Z"}
{"log":"runtime: unexpected return pc for runtime.sigpanic called from 0x0\n","stream":"stderr","time":"2023-08-09T09:51:07.813378053Z"}
{"log":"stack: frame={sp:0xc0011a7d00, fp:0xc0011a7d50} stack=[0xc0011a7000,0xc0011a8000)\n","stream":"stderr","time":"2023-08-09T09:51:07.813381653Z"}
{"log":"0x000000c0011a7c00:  0x000000c0011a7c08  0x00000000013f8aa0 \u003cruntime.addOneOpenDeferFrame.func1+0x0000000000000000\u003e \n","stream":"stderr","time":"2023-08-09T09:51:07.813385434Z"}
{"log":"0x000000c0011a7c10:  0x0000000001410516 \u003cruntime.sigpanic+0x0000000000000336\u003e  0x000000c0011a7d00 \n","stream":"stderr","time":"2023-08-09T09:51:07.813389398Z"}
{

**Comment by xiaofan-luan** [comment]
is it recovered after panic?

**Comment by xiaofan-luan** [comment]
if not could you offer more detailed logs from the querynode

**Comment by yanliang567** [comment]
@sunnyningsu Could you please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
As it recovered to be working, i guess it could be some cache issue. 
/assign @sunnyningsu

**Comment by sunnyningsu** [comment]
Hi @yanliang567 I have exported the logs around the incident time and it has about 7000+ rows, how I give you the logs

**Comment by yanliang567** [comment]
attach it in the issue, or upload to cloud disk such as baidu, google, etc.

**Comment by sunnyningsu** [comment]
here is the [log](https://docs.google.com/spreadsheets/d/1GwYxFZVz44Lbhdyg12DnFJdqOeZEqckFiZMHJY9UGR8/edit#gid=0) 
I think the L750 is the incident point

**Comment by yanliang567** [comment]
/assign @jiaoew1991 
there was a panic... :(
/unassign

**Comment by yanliang567** [comment]
@sunnyningsu BTW, I'd suggest you upgrade to milvus v2.2.13, which fixed many issues.

**Comment by jiaoew1991** [comment]
```
{"log":"runtime: unexpected return pc for runtime.sigpanic called from 0x0\n","stream":"stderr","time":"2023-08-09T09:51:07.802089866Z"}
```

The cause of the panic appears to be a known issue in earlier versions of 2.2, which has been fixed in the 2.2.11
Upgrade to milvus 2.2.13 will fix the issue

**Comment by sunnyningsu** [comment]
thanks, that helps

**Comment by jiaoew1991** [comment]
I think we can close this issue now  😄
