### ISSUE TITLE
[Bug]: Param `limit` should be set as a necessary one in api query_iterator

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#26358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0.dev15
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Param `limit` should be set as a necessary one in api query_iterator.

now, it will raise error if we use `query_iterator = collection.query_iterator(expr=expression)`
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/iterator.py", line 112, in next
    self.__maybe_cache(res)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/iterator.py", line 84, in __maybe_cache
    if len(result) < 2 * self._kwargs[LIMIT]:
KeyError: 'limit'
```

### Expected Behavior

The api query_iterator is different from query. for query, limit is not necessary. But for query_iterator, the param limit represents another meaning -- the number of results per page. And it is necessary.
So we'd better set `limit` the same grade as 'expr'.
And if users do not send limit, it will raise a reasonable error message like 'should set limit..'

![image](https://github.com/milvus-io/milvus/assets/109071306/99e5c357-30be-42e9-9030-5e0e696e682f)

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version:
> - Deployment mode(standalone or cluster):
> - MQ type(rocksmq, pulsar or kafka):    
> - SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0.dev15
> - OS(Ubuntu or CentOS): 
> - CPU/Memory: 
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> Param `limit` should be set as a necessary one in api query_iterator.
> 
> now, it will raise error if we use `query_iterator = collection.query_iterator(expr=expression)`
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 2, in <module>
>   File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/iterator.py", line 112, in next
>     self.__maybe_cache(res)
>   File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/iterator.py", line 84, in __maybe_cache
>     if len(result) < 2 * self._kwargs[LIMIT]:
> KeyError: 'limit'
> ```
> 
> ### Expected Behavior
> The api query_iterator is different from query. for query, limit is not necessary. But for query_iterator, the param limit represents another meaning -- the number of results per page. And it is necessary. So we'd better set `limit` the same grade as 'expr'. And if users do not send limit, it will raise a reasonable error message like 'should set limit..'
> 
> ![image](https://user-images.githubusercontent.com/109071306/260644826-99e5c357-30be-42e9-9030-5e0e696e682f.png)
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

@MrPresent-Han 
Personally I don't like the idea of resuing limit as another meaning.
We can introduce another query param like batch and by default it can be set to 1000

**Comment by MrPresent-Han** [comment]
@NicoYuan1986  as I have modified the code and limit in iterator has had a brand new meaning for limit the sum of output, is this issue ok to close?

**Comment by NicoYuan1986** [comment]
Yes. 
Param `limit` now means the number of all results returned. It is not necessary now.
Param `batch_size` now means the number of every page results returned. It has a default value 1000 now.
