### ISSUE TITLE
[Bug]: e2e cases might fail due to flush timeout

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#26367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: ec65a4e
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

e2e cases might fail due to flush timeout

### Expected Behavior

e2e cases shall pass stably

### Anything else?

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-26356/3/pipeline

**Comment by zhuwenxing** [comment]
same issue 
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-26377/1/pipeline/199

**Comment by congqixia** [comment]
no recurrence in 2 weeks, closing
