### ISSUE TITLE
[Bug]: TestMultiLogicalExprsOptimization fails on M2 Macbook

### ISSUE THREAD

**Issue by unfode** [milvus-io/milvus#26384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment
M2 Macbook

### Current Behavior

I `git clone` this repo and ran `make unittest` three times on M2 Macbook. `TestMultiLogicalExprsOptimization` failed twice:

![image](https://github.com/milvus-io/milvus/assets/95689995/3d91d3ec-a8e8-4981-bfb1-3b463ac196b0)

**Comment by yah01** [comment]
/assign @zhagnlu 
The optimization make the execution slower 2x on M2 Mac, it may be a platform-related problem

**Comment by zhagnlu** [comment]
I will check it

**Comment by yah01** [comment]
/assign @unfode 
Hi @unfode, please help check this as #26394 merged

**Comment by unfode** [comment]
The test passes now!
