### ISSUE TITLE
[Enhancement]: milvus schema字段支持数组（列表）

### ISSUE THREAD

**Issue by citePerson** [milvus-io/milvus#26386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

我希望milvus只是数组（列表）并且支持列表的常规操作，交集、in、元素是否存在等查询

### Why is this needed?

接收到的是数组（列表），源数据也是数组（列表）

### Anything else?

接收到的是数组（列表），源数据也是数组（列表）

**Comment by xiaofan-luan** [comment]
please use english on issues, Thanks!
this is duplicated with https://github.com/milvus-io/milvus/issues/26108, track there.

Thanks!

**Comment by citePerson** [comment]
ok. 
When can it be launched? 
it support all regular operations on arrays?

**Comment by xiaofan-luan** [comment]
we will support contains, contains_any and contains_all operator.
So far milvus will NOT support any kind of wildcard matching

**Comment by citePerson** [comment]
May I ask if it belongs to a field type or is it included in a JSON field?

**Comment by citePerson** [comment]
> we will support contains, contains_any and contains_all operator. So far milvus will NOT support any kind of wildcard 
First, we need to implement storage [1,2,3,4,5,6]
Then receive data as [1,2,3]
Can we achieve their intersection [1,2,3]?

**Comment by xiaofan-luan** [comment]
> > we will support contains, contains_any and contains_all operator. So far milvus will NOT support any kind of wildcard
> > First, we need to implement storage [1,2,3,4,5,6]
> > Then receive data as [1,2,3]
> > Can we achieve their intersection [1,2,3]?

claim a field as array
insert an entity with array [1,2,3,4,5,6] and search/query with expression if array contains_all [1,2,3]
