### ISSUE TITLE
[Bug]: Suggest a more direct error exception as regards query_iterator

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#26397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: f8bcf60e
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):     rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0.dev115
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Suggest a more direct error exception as regards query_iterator.

Now using an invalid limit will not raise error
![image](https://github.com/milvus-io/milvus/assets/109071306/cf21397b-fb3d-48a9-80f8-17880d03c347)

it raises error when next()
![image](https://github.com/milvus-io/milvus/assets/109071306/d6379e10-b456-44a6-9dc2-042db2da8e01)

![image](https://github.com/milvus-io/milvus/assets/109071306/68ed4f28-2c65-44bb-a631-3ea7570f9fbf)

### Expected Behavior

report error immediately when quoting query_iterator.
Since limit and offset have different meaning from query().
limit + offset <= 16384 is not working here.
Do we need to set a maximum?

**Comment by xiaofan-luan** [comment]
exactly, @MrPresent-Han 
I think we should name it as batch and distinguish it with original limit

**Comment by MrPresent-Han** [comment]
Fine, I will fix this

**Comment by NicoYuan1986** [comment]
verify fixed. 
now error:
error = {"err_code": 1, "err_msg": "batch size cannot be less than zero"}

milvus: master-20230831-3752ebb4
pymilvus: 2.3.0
