### ISSUE TITLE
[Bug]: etcd container doesn't run with `docker-compose-apple-silicon.yml`

### ISSUE THREAD

**Issue by unfode** [milvus-io/milvus#26409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

M2 Macbook

### Current Behavior

When running

```bash
cd deployments/docker/dev
docker-compose -f docker-compose-apple-silicon.yml up -d
```

I get

![image](https://github.com/milvus-io/milvus/assets/95689995/5ec26702-5880-419e-bce8-12e6d29d6ee3)

Same as this [issue](https://github.com/etcd-io/etcd/issues/14321#issuecomment-1416681122) under etcd. It's probably due to `m2/arm64`.

### Steps To Reproduce

```bash
cd deployments/docker/dev
docker-compose -f docker-compose-apple-silicon.yml up -d
```

**Comment by jiaoew1991** [comment]
@LoveEachDay please help on this issue

**Comment by unfode** [comment]
@LoveEachDay I checked my ports with `sudo Isof -i -p -n i grep LISTEN`, but 2830 wasn't in use:
![image](https://github.com/milvus-io/milvus/assets/95689995/5d632914-b332-48c1-9946-0bb710022d17)

It seems to be a bug of etcd on m1/arm machines according to this [issue](https://github.com/etcd-io/etcd/issues/14321) of etcd.
