### ISSUE TITLE
[Enhancement]:  Add dynamic modify thread number to thread pool

### ISSUE THREAD

**Issue by zhagnlu** [milvus-io/milvus#26406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Now thread pool init a bunch of threads when init and keep not change number. But maybe cost a lot of resource especially memory.  Add a function that support auto dynamic modify threads number when running.

**Comment by xiaofan-luan** [comment]
we should change to folly thread pool?
