### ISSUE TITLE
[Bug]: Getting a DataNotMatchException even though the declared datatype is same.

### ISSUE THREAD

**Issue by FSDSAbhi** [milvus-io/milvus#26415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): MacOS M1
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I declare the fields and index as below:

fields = [
    FieldSchema(name='id', dtype=DataType.INT64, is_primary=True, auto_id=False),
    FieldSchema(name='chunk_vector', dtype=DataType.FLOAT_VECTOR, dim=384)
]
schema = CollectionSchema(fields=fields)
collection = Collection(name=COLLECTION_NAME, schema=schema)

index_params = {
    'metric_type':'L2',
    'index_type':"IVF_FLAT",
    'params':{'nlist': 384}
}
collection.create_index(field_name="chunk_vector", index_params=index_params)
collection.load()

I get the below error.
pymilvus.exceptions.DataNotMatchException: <DataNotMatchException: (code=1, message=The data type of field chunk_vector doesn't match, expected: FLOAT_VECTOR, got VARCHAR)>

I have not declared my field as VARCHAR, not sure why it is saying so.

### Milvus Log

ile "/Users/env/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 441, in insert
    check_insert_data_schema(self._schema, data)
  File "/Users/env/lib/python3.10/site-packages/pymilvus/orm/schema.py", line 423, in check_insert_data_schema
    check_infer_fields_valid(infer_fields, tmp_fields, isinstance(data, pandas.DataFrame))
  File "/Usersenv/lib/python3.10/site-packages/pymilvus/orm/schema.py", line 491, in check_infer_fields_valid
    raise DataNotMatchException(
pymilvus.exceptions.DataNotMatchException: <DataNotMatchException: (code=1, message=The data type of field chunk_vector doesn't match, expected: FLOAT_VECTOR, got VARCHAR)>

**Comment by yanliang567** [comment]
I am not able to reproduce the issue on Milvus v2.2.13 with pymilvus 2.2.14, could you please double check your milvus and pymilvus versions?
/assign @FSDSAbhi 
/unassign
