### ISSUE TITLE
[Bug]: I encountered an issue with broken links on the Milvus documentation page.

### ISSUE THREAD

**Issue by viamo-sl** [milvus-io/milvus#26412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The links for Python, Java, and Go on the documentation page (https://milvus.io/docs/api.md) are not functional. When clicking on these links, I receive a "404 Uoops...something went wrong!" error message.

### Expected Behavior

I expected the links for Python, Java, and Go on the documentation page to lead me to their respective API documentation pages without any errors.

### Steps To Reproduce

```markdown
1. Visit the Milvus documentation page: https://milvus.io/docs/api.md
2. Attempt to click on the links for Python, Java, and Go under the API documentation section.
```

**Comment by yanliang567** [comment]
@viamo-sl thank you for your feedback, we will fix it soon.

/assign @AnthonyTsu1984 
/unassign

**Comment by AnthonyTsu1984** [comment]
This page is a legacy page and has been removed.
