### ISSUE TITLE
[Bug]: VectorDBBench performance degradation in v2.2.13 (compare with v2.2.12)

### ISSUE THREAD

**Issue by baosince** [milvus-io/milvus#26425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.13
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): 
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.2.15
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: docker-compose resource 4c16g
- GPU: 
- Others:
```

### Current Behavior

I use vectorDBBench to test Milvus-v2.2.13 and Milvus-v2.2.12. The deployment mode is standalone. 
The results of bench show that the QPS and Latency of Milvus-v2.2.13 are worse than Milvus-v2.2.12.
Milvus resource 4C16G, IVF_FLAT and IVF_SQ8，nlist=1000, nprobe=10
![20230817-151943](https://github.com/milvus-io/milvus/assets/24970415/c75ad883-d91a-4f6d-bd16-4484fab56b5c)
![20230817-152140](https://github.com/milvus-io/milvus/assets/24970415/fb13f358-cf38-405d-bb82-8606fec104ba)

### Steps To Reproduce

```markdown
use VectorDBBench to run a test, IVF_* param is {nlist:1000, nprobe:10}, just change the version of milvus from 2.2.12 to 2.2.13.
```

### Milvus Log

[milvus_2_2_13_IVF_FLAT.log](https://github.com/milvus-io/milvus/files/12365311/milvus_2_2_13_IVF_FLAT.log)

**Comment by yanliang567** [comment]
According to the serial latency, I believe there are some growing segments in milvus v2.2.13 tests.  Could you please attach the etcd backup of both milvus isntances for investigation? Check this: https://github.com/milvus-io/birdwatcher for details about how to backup etcd with birdwatcher. 

/assign @baosince 
/unassign

/assign @liliu-z 
@liliu-z how do we ensure all the segments are sealed before starting searching test in VectorDBBench?

**Comment by liliu-z** [comment]
/assign @XuanYang-cn 
This is a known issue caused by API  function change in Milvus. Will fix this

**Comment by baosince** [comment]
u fixed it, thx! VDB seems well now!
