### ISSUE TITLE
COMBINE_SEARCH_TEST timeout on GPU

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#2643]
**Describe the bug**
http://internal.zilliz.com:18080/jenkins/blue/organizations/jenkins/milvus-ci/detail/0.8.1/16/pipeline/515
http://internal.zilliz.com:18080/jenkins/blue/organizations/jenkins/milvus-ci/detail/0.8.1/16/pipeline/492
```
[2020-06-20T17:09:15.417Z] [       OK ] RpcHandlerTest.SEARCH_TEST (89 ms)

[2020-06-20T17:09:15.417Z] [ RUN      ] RpcHandlerTest.COMBINE_SEARCH_TEST

[2020-06-20T19:18:08.126Z] Sending interrupt signal to process
```
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
0.8.1

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
Fixed by pr2645
