### ISSUE TITLE
[Bug]: [json_contains]Json_contains_any sometimes get wrong results when enable_dynamic_field=True

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#26436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230817-855a0453
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):     rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0.dev117
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Json_contains_any sometimes get wrong results when enable_dynamic_field=True.

collection schema: 
![image](https://github.com/milvus-io/milvus/assets/109071306/086cce53-4991-492b-8c83-8ead648d2945)

insert data:
![image](https://github.com/milvus-io/milvus/assets/109071306/8fecb0cd-b56c-45f3-b0e6-07ed15517524)

search:
![image](https://github.com/milvus-io/milvus/assets/109071306/978c93c6-c749-481e-9b68-17d4ea84f870)

result: (It is wrong)
![image](https://github.com/milvus-io/milvus/assets/109071306/1fe713e3-a4bc-4bfc-91e0-d11467ee03df)

### Expected Behavior

return empty

**Comment by xiaocai2333** [comment]
Please use a fresh table for each test, and use the strong consistency level.

**Comment by NicoYuan1986** [comment]
Not reproduced by wait and strong consistency level.
