### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'pymilvus'

### ISSUE THREAD

**Issue by LarryStewart2022** [milvus-io/milvus#26442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.15
- Deployment mode(standalone):
- MQ type(rocksmq, pulsar or kafka):    
- SDK pymilvus 
- OS(vs code env): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Just starting out. I created a new python environment and started to follow your docs:

COMPLETED THE FOLLOWING:
Requirements
Python 3.7 or later is required.
Google protobuf is installed. You can install it with the command pip3 install protobuf==3.20.0.
grpcio-tools is installed. You can install it with the command pip3 install grpcio-tools.

Clicked on what's next and ran this
from pymilvus import connections

And it get this error 
Traceback (most recent call last):
  File "c:\Milvustest\app.py", line 1, in <module>
    from pymilvus import connections
ModuleNotFoundError: No module named 'pymilvus'

**Comment by xiaofan-luan** [comment]
@XuanYang-cn 
@longjiquan 
any idea about the pymilvus install?

**Comment by yanliang567** [comment]
I guess there are some conflict dependence in the python env. could you please retry with some virtual python env?
/assign @LarryStewart2022

**Comment by dgarnitz** [comment]
I am also running into this issue

**Comment by longjiquan** [comment]
No offense, but did you already install the pymilvus? I noticed that you only installed the `protobuf` and `grpcio-tools`. @LarryStewart2022

**Comment by longjiquan** [comment]
> Did you already install the pymilvus? I noticed that you only installed the `protobuf` and `grpcio-tools`. @LarryStewart2022 Btw, can you tell us which documentation you refered to use milvus, maybe it's not up-to-date now and we'll update it if anything is changed.

@dgarnitz plz also take a look and we'll apreciate it very much.

**Comment by LarryStewart2022** [comment]
What a nightmare. so, I decide to just start from scratch. I removed all of milvus from my Ubuntu Docker server and reinstalled it. I am using (https://milvus.io/docs/)  On this Page (https://milvus.io/docs/install_standalone-docker.md) i installed and started Milvus without any issues. In vscode on my windows machine i created and environment and I'm running Python 3.11.4.
(python3 -m pip install pymilvus==2.3.0)  I also ran (python3 -c "from pymilvus import Collection") no issues. I downloaded hello_milvus.py and changed the connection to my server (connections.connect("default", host="192.168.0.48", port="19530")) AND then this RPC error: [__internal_register], <MilvusException: (code=1, message=this version of sdk is incompatible with server, please downgrade your sdk or upgrade your server)>, <Time:{'RPC start': '2023-08-24 10:38:03.485577', 'RPC error': '2023-08-24 10:38:03.491746'}> I still have yet made a connectoin to this server. Why so many issues?

**Comment by yanliang567** [comment]
/assign @XuanYang-cn 
please help

**Comment by longjiquan** [comment]
@LarryStewart2022 sorry, but as the message mentioned, maybe you should try to upgrade the version of your server.

**Comment by LarryStewart2022** [comment]
[longjiquan], As my post mentions clearly. I followed you docs perfectly. So, update your docs. I'm done messing around with this. All of your replies have not been helpful at all. Why respond?
