### ISSUE TITLE
[Bug]: panic: unexpected segment type

### ISSUE THREAD

**Issue by zhuanxuhit** [milvus-io/milvus#26456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

in querynode i see painc message "panic: unexpected segment type"

**Comment by xiaofan-luan** [comment]
1. what is the version of Milvus?
2. what action your did? load, query or whatever?
3. could you offer detailed logs.
Highly recommend run with latest 2.2.13 version

**Comment by zhuanxuhit** [comment]
1. milvus is latest master version
2. load segment
3. the code is 
https://github.com/milvus-io/milvus/blob/master/internal/querynodev2/segments/segment_loader.go#L973

```
infos := loader.prepare(commonpb.SegmentState_SegmentStateNone, version, loadInfo)
```
it use commonpb.SegmentState_SegmentStateNone to call prepeare
and in prepare function，it  then call 
```
loader.manager.Segment.UpdateSegmentVersion(segmentType, segment.SegmentID, version)
```
and finnally in 
https://github.com/milvus-io/milvus/blob/master/internal/querynodev2/segments/manager.go#L190
it panic

**Comment by xiaofan-luan** [comment]
> 1. milvus is latest master version
> 2. load segment
> 3. the code is
>    https://github.com/milvus-io/milvus/blob/master/internal/querynodev2/segments/segment_loader.go#L973
> 
> ```
> infos := loader.prepare(commonpb.SegmentState_SegmentStateNone, version, loadInfo)
> ```
> 
> it use commonpb.SegmentState_SegmentStateNone to call prepeare and in prepare function，it then call
> 
> ```
> loader.manager.Segment.UpdateSegmentVersion(segmentType, segment.SegmentID, version)
> ```
> 
> and finnally in https://github.com/milvus-io/milvus/blob/master/internal/querynodev2/segments/manager.go#L190 it panic

Thanks for the feedback, I made the fix

**Comment by xiaofan-luan** [comment]
@zhuanxuhit 
already fixed in master! thanks for the feedback
