### ISSUE TITLE
[Bug]: Unit test `Util.read_from_fd` fails on M2 Macbook

### ISSUE THREAD

**Issue by unfode** [milvus-io/milvus#26452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

M2/arm Macbook

### Current Behavior

When I `make unittest`, `Util.read_from_fd` fails:

![image](https://github.com/milvus-io/milvus/assets/95689995/fc4c9937-aa0c-4607-996a-4a5fff8a7bef)

Relevant code:

https://github.com/milvus-io/milvus/blob/bdc8c507ea026a62ac9f9a995ca39088eeb45e42/internal/core/unittest/test_utils.cpp#L162-L165

**Comment by yah01** [comment]
/assign @xige-16 
please help check this as https://github.com/milvus-io/milvus/pull/26392/files introduced this
