### ISSUE TITLE
[Bug]: Milvus  cpu is too high and shutdown 

### ISSUE THREAD

**Issue by huan415** [milvus-io/milvus#26472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.2.12
- Deployment mode(standalone or cluster):standalone 
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.2.14
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 2C4G
- GPU: 
- Others:
```

### Current Behavior

I have two collections,   48,743 Entities
When I press test, milvus shutdown.    And after the restart milvus success, but a few minutes shutdown (Don't have any request)

delete a collection, i can restart restart milvus and running well

### Milvus Log

Without any error

top
top -Hp pid
watch pstack tid
#0  0x00007fa2f6f6132c in ?? ()
#1  0xfffffffffffe9818 in ?? ()
#2  0x00007fa2b5fe6700 in ?? ()
#3  0x00007fa2bb6f18a0 in ?? ()

**Comment by yanliang567** [comment]
For Milvus installed with docker-compose, could you please use docker-compose logs > milvus.log to export the logs. Also could you share more info about the press test you did, if you could share the reproduce code it would be perfect.

/assign @huan415
/unassign
