### ISSUE TITLE
[Bug]: not pass in dbName in query request

### ISSUE THREAD

**Issue by smellthemoon** [milvus-io/milvus#26479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

<img width="561" alt="1" src="https://github.com/milvus-io/milvus/assets/64083300/78e5ada2-6cc1-4e34-9134-a4adf66ccad7">
not pass in dbName in query request

### Expected Behavior

need to pass

**Comment by yanliang567** [comment]
@jaime0815 is this a serial of updates for database related APIs?
