### ISSUE TITLE
[Bug]: unstable unittest test_TimeTickDelayFactor_factors

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#26499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/12216890/baec7168-ae3e-4726-91d8-c8866f45a617)

**Comment by weiliu1031** [comment]
same as #26458
