### ISSUE TITLE
[BUG] Search time doubles when using ivf_sq8_GPU searching and nq set 1000 compared with nq set 1

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#265]
**Describe the bug**
index_type: ivf_sq8
search_resources: gpu0, gpu1
dataset: random_50m_512d_ip, index_file_size: 1024
Search time cost too much when nprobe set 32, and nq = 1000;
The gpu search performance is totally different on the same dataset with IVF_FLAT index_type, and if dataset changed, such as sift_1b_128d_ip, the gpu search performance is stable, whether the nq value is 1 or 1000

**Steps/Code to reproduce behavior**
Use the given dataset, search with nq=1 and nq=1000

**Expected behavior**
The search performance is stable when between nq=1 and nq=1000

**Environment details**
server_version: 0.5.3-release

**Screenshots**
null

**Additional context**
null

**Comment by JinHai-CN** [comment]
I guess it's reasonable, but it is necessary for us to give a explanation on the result. @scsven

**Comment by scsven** [comment]
It's not a bug, search cost much time. We will optimize search cost future.
