### ISSUE TITLE
[Bug]: range search get unclear error message

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus#26503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```javascript
it(`Exec simple search with range filter should success`, async () => {
    const limit = 8;
    const res = await milvusClient.search({
      collection_name: COLLECTION_NAME,
      filter: 'height < 10000',
      vector: [1, 2, 3, 4],
      limit: limit,
      params: { nprobe: 1024, radius: 10, range_filter: 20 },
    });

    console.log('range ', res);

    expect(res.status.error_code).toEqual(ErrorCode.SUCCESS);
    res.results.forEach(r => {
      expect(Number(r.height)).toBeLessThan(10000);
    });
  });

```

```bash 
range  {
      status: {
        error_code: 'UnexpectedError',
        reason: 'attempt #0: fail to Search, QueryNode ID=1, reason=worker(1) query failed: UnexpectedError: Assert "Assert "range_filter < radius" at /go/src/github.com/milvus-io/milvus/internal/core/src/common/RangeSearchHelper.cpp:126\n' +
          ' => range_filter must be less than radius for L2/HAMMING/JACCARD" at /go/src/github.com/milvus-io/milvus/internal/core/src/query/SearchBruteForce.cpp:103: channel=by-dev-rootcoord-dml_5_443700359105080880v0: fail to search/query shard leader: attempt #1: no available shard delegator found: service unavailable: fail to search on all shard leaders',
        code: 0
      },
      results: []
    }
```

I don't understand the error message. 

`=> range_filter must be less than radius for L2/HAMMING/JACCARD"` what is the correct radius?

**Comment by jiaoew1991** [comment]
@shanghaikid 意思是对于L2/HAMMING/JACCARD，For L2/HAMMING/JACCARD, the `range_filter` parameter needs to be smaller than the `range`. In this case, where `range` equals 10, the `range_filter` should be less than 10.

**Comment by shanghaikid** [comment]
> @shanghaikid For L2/HAMMING/JACCARD, the `range_filter` parameter needs to be smaller than the `range`. In this case, where `range` equals 10, the `range_filter` should be less than 10.

I think it should return an empty result if the range_filter is not set correctly.

**Comment by jiaoew1991** [comment]
> > @shanghaikid For L2/HAMMING/JACCARD, the `range_filter` parameter needs to be smaller than the `range`. In this case, where `range` equals 10, the `range_filter` should be less than 10.
> 
> I think it should return an empty result if the range_filter is not set correctly.

For L2/HAMMING/JACCARD, the range_filter should be smaller than the range. However, for other metrics, the range should be larger than the range_filter. If an empty value is returned, it can easily lead to misuse here. If an empty value is returned, users may mistakenly think that there is no problem with their parameters and that there is simply no data available.

**Comment by shanghaikid** [comment]
> > > @shanghaikid For L2/HAMMING/JACCARD, the `range_filter` parameter needs to be smaller than the `range`. In this case, where `range` equals 10, the `range_filter` should be less than 10.
> > 
> > 
> > I think it should return an empty result if the range_filter is not set correctly.
> 
> For L2/HAMMING/JACCARD, the range_filter should be smaller than the range. However, for other metrics, the range should be larger than the range_filter. If an empty value is returned, it can easily lead to misuse here. If an empty value is returned, users may mistakenly think that there is no problem with their parameters and that there is simply no data available.


In database world, if you write a incorrect sql, it should return an error, if you write a correct sql but with a wrong where condition, it just return empty.  should we follow this?

**Comment by jiaoew1991** [comment]
> 

it should be considered as a incorrect sql 🤔

**Comment by shanghaikid** [comment]
@xiaofan-luan   @yanliang567 what do you guys think?
