### ISSUE TITLE
[Bug]: datanode OOM when inserting with 15000 qps

### ISSUE THREAD

**Issue by caoping6** [milvus-io/milvus#26504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.8
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):  pulsar  
- SDK version(e.g. pymilvus v2.0.0rc2): milvus-sdk-java 2.2.5
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 4C8G
- GPU: 
- Others:
```

### Current Behavior

1.创建一个向量维度是256、shard=1的集合
2.以最大15000的qps通过java的sdk调用insert写入，一次200条
3.datanode内存设置为8G
4.datanode的内存一直增长然后OOM重启
5.重启后datanode的id会发生改变，导致pulsar中新增一个消费者从当前开始消费，导致数据丢失

### Expected Behavior

1.期望datanode不会oom
2.期望datanode重启不会发生id改变

### Steps To Reproduce

```markdown
1.创建一个向量维度是256、shard=1的集合
2.以最大15000的qps通过java的sdk调用insert写入，一次200条
3.datanode内存设置为8G
4.datanode的内存一直增长然后OOM重启
5.重启后datanode的id会发生改变，导致pulsar中新增一个消费者从当前开始消费，导致数据丢失
```

### Milvus Log

nothing

### Anything else?

nothing

**Comment by xiaofan-luan** [comment]
1. data won't be loss, because milvus always consume from checkpoint when datanode restart.
2. you can tune auto flush parameters, make sure flush can catch up write throughput, change to 2.2.13 might help a little bit

**Comment by xiaofan-luan** [comment]
@yanliang567 
please try to reproduce this issue see if possible

**Comment by caoping6** [comment]
> 

感谢，我看到了代码，checkpoint是根据集合id保存的，与datanode的id无关

**Comment by xiaofan-luan** [comment]
we will still test on verifying why datanode OOM~

**Comment by caoping6** [comment]
> we will still test on verifying why datanode OOM~

好的。我们将datanode扩大到30G的内存，目前观察到datanode增长到20G左右保持稳定，我猜想是否和创建的集合多少有关系呢，因为多创建一个集合就会多一个flowgraph（同时多一个groupid）

**Comment by caoping6** [comment]
> 

目前写入的qps大概是2万多， 如果有十个groupid，就相当于是20万的吞吐量
