### ISSUE TITLE
[Bug]: list_grant() does not list the granted privileges

### ISSUE THREAD

**Issue by wgzesg** [milvus-io/milvus#26500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.13
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.15
- OS(Ubuntu or CentOS): Ubuntu
```

### Current Behavior

Using Pymilvus to create roles. 
After I grant privileges to database other than "Default", those grant will not be listed  by `list_grant()` method

I tested with accessing from Attu UI and Pymilvus scripts. Correct privileges are given but just not displayed in list_gran()

### Expected Behavior

When listing grants, it should give out all grants in all databases.

Or is there a `using=xx` to select which database's grant should be listed?

### Steps To Reproduce

```markdown
1. Create a role
2. Create a new database "ABC"
3. Grant role some access to database "ABC"
4. list grants. None will be shown
```

### Milvus Log

...

### Anything else?

![image](https://github.com/milvus-io/milvus/assets/53573749/3c6aa5f5-cba8-4b00-a327-6432717ab64d)

**Comment by yanliang567** [comment]
/assign @binbinlv 
could you please help to reproduce it in house?
/unassign

**Comment by binbinlv** [comment]
working on it.

**Comment by binbinlv** [comment]
@wgzesg 
There is parameter "db_name" to be specified for list_grants interface, the db_name is "default" if it is not specified.
```python
 def list_grants(self, db_name: str = "default"):
...
```

So if you want to list the grants for the non-default database "ds", you need to write the code as the following:

```
>>> role.list_grants(db_name="ds")
GrantInfo groups:
- GrantItem: <object:Collection>, <object_name:*>, <db_name:ds>, <role_name:roleA>, <grantor_name:root>, <privilege:*>
- GrantItem: <object:Collection>, <object_name:*>, <db_name:ds>, <role_name:roleA>, <grantor_name:root>, <privilege:Search>
```
