### ISSUE TITLE
[Bug]: After restarting the milvus cluster, it was found that some collections could not be retrieved

### ISSUE THREAD

**Issue by Cactus-L** [milvus-io/milvus#26567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.13
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):jdk
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 32c 128g *3
- GPU: 
- Others:
```

### Current Behavior

After restarting the milvus cluster, it was found that some collections could not be retrieved

I currently suspect that there is an abnormality in data loading, but there is no progress, so I will ask the community for help

there are some err log：
search failed, collection : xxx, error msg : DEADLINE_EXCEEDED: deadline exceeded after 19.999784793s. 

### Milvus Log

milvus log info：
 https://pan.baidu.com/s/1mjt9_6HrM82qqAfyO-igPQ?pwd=vjeh

**Comment by yanliang567** [comment]
@Cactus-L could you please share more info to help us addres the issue?
1. the collection name that can not be retrieved
2. how to stop the milvus, and anything you do to milvus or milvus related folders/files?
3. please attach the etcd backup for investigation？ Check this: https://github.com/milvus-io/birdwatcher for details about how to backup etcd with birdwatcher
/assign @Cactus-L

**Comment by Cactus-L** [comment]
> @Cactus-L could you please share more info to help us addres the issue?
> 
> 1. the collection name that can not be retrieved
> 2. how to stop the milvus, and anything you do to milvus or milvus related folders/files?
> 3. please attach the etcd backup for investigation？ Check this: https://github.com/milvus-io/birdwatcher for details about how to backup etcd with birdwatcher
>    /assign @Cactus-L
1、collection（it's just one of them）：ee_xiaok_ee_xiaok_question
2、do nothing

**Comment by aoiasd** [comment]
Log download link out of date.

**Comment by Cactus-L** [comment]
> Log download link out of date.

log: https://pan.baidu.com/s/12xLMPun4gWpicm0Kf9MDUA?pwd=ik34 
etcd: https://pan.baidu.com/s/1D_iFhK7KERv69spC8fB7Qw?pwd=eihw

**Comment by aoiasd** [comment]
Failed to load etcd backup with NO EOF, seems end before backup success finish.
And because limit log size, i could only see log of a few minutes.
All search failed was relate query node 907, but because log lack, we could not see what cause it.

And find another question, querynode flowgraph get so many empty messages that we can only see "Invalid operate message input" in querynode logs.
