### ISSUE TITLE
[Bug]: [benchmark] Concurrent search or query with vector return with milvus reboot and high failure rate

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#26570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230823-7af0f7d9-amd64
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.4.0.dev81
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Insert 1 million vectors, create diskann index, perform concurrent query, return with vectors.

param:
```
limit: 1
offset: 10
expr:
  float_1:
    GT: -1
    LT: 5000
```

server : 
problem: milvus restart
```
new-stable-mastqtn54-2-88-9844-etcd-0                             1/1     Running     1 (104m ago)    4h11m   10.104.9.149    4am-node14   <none>           <none>
new-stable-mastqtn54-2-88-9844-milvus-standalone-7df8b877clvw7w   1/1     Running     1 (101m ago)    4h11m   10.104.19.158   4am-node28   <none>           <none>
new-stable-mastqtn54-2-88-9844-minio-54fc47b89f-wtpbk             1/1     Running     0               4h11m   10.104.14.104   4am-node18   <none>           <none> 
```

client error log :
client pod : new-stable-master-qtn54-2955744536
![image](https://github.com/milvus-io/milvus/assets/48523564/43f8a2e0-a61b-4665-9f78-df12aac38faa)

The total number of requests was 720,449, with 38,760 failures, a failure rate of about 5%.

### Expected Behavior

can search or query normally even if you return vectors

### Steps To Reproduce

```markdown
1. create a collection  
        2. build index on vector column
        3. insert a certain number of vectors
        4. flush collection
        5. build index on vector column with the same parameters
        6. count the total number of rows
        7. load collection
        8. perform concurrent operations 
        9. clean all collections
```

**Comment by elstic** [comment]
HNSW index inserts 1M data, concurrently searches and returns vector also has this problem

server:
```
new-stable-mastqtn54-1-93-2609-etcd-0                             1/1     Running     1 (107m ago)    4h13m   10.104.9.137    4am-node14   <none>           <none>
new-stable-mastqtn54-1-93-2609-milvus-standalone-95b6b76dbpzbbr   1/1     Running     1 (103m ago)    4h13m   10.104.21.116   4am-node24   <none>           <none>
new-stable-mastqtn54-1-93-2609-minio-5c9bdf5758-xdfhd             1/1     Running     0               4h13m   10.104.9.136    4am-node14   <none>           <none>
```

**Comment by binbinlv** [comment]
/assign @bigsheeper 

could you please have a look? Thanks.

**Comment by LoveEachDay** [comment]
```
Liveness probe failed: command \"/opt/bitnami/scripts/etcd/healthcheck.sh\" timed out
Container etcd failed liveness probe, will be restarted
```

**Comment by bigsheeper** [comment]
session keepalive failed:
![image](https://github.com/milvus-io/milvus/assets/42060877/5088da1c-f030-4322-8f9f-1e60d1dd0dca)
https://grafana-4am.zilliz.cc/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bpod%3D%5C%22new-stable-mastqtn54-1-93-2609-milvus-standalone-95b6b76dbpzbbr%5C%22%7D%20%7C~%20%5C%22GitCommit%7Cpanic%5C%22%22,%22queryType%22:%22range%22,%22hide%22:true%7D,%7B%22refId%22:%22B%22,%22expr%22:%22%7Bpod%3D%5C%22new-stable-mastqtn54-1-93-2609-milvus-standalone-95b6b76dbpzbbr%5C%22%7D%22,%22hide%22:true%7D,%7B%22refId%22:%22C%22,%22expr%22:%22%7Bpod%3D%5C%22new-stable-mastqtn54-1-93-2609-milvus-standalone-95b6b76dbpzbbr%5C%22%7D%20%7C~%20%5C%22WARN%7CERROR%7CGitCommit%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%221692766510000%22,%22to%22:%221692766771000%22%7D%7D

same as: https://github.com/milvus-io/milvus/issues/25863

however, cpu usage is quite normal:
![image](https://github.com/milvus-io/milvus/assets/42060877/7f8b00cc-30e5-4ebe-9095-3431510e4d73)

**Comment by pingliu** [comment]
![20230823-194843](https://github.com/milvus-io/milvus/assets/6415493/141e6ffa-33b9-46e4-b3cc-01d0fd681635)
![20230823-194839](https://github.com/milvus-io/milvus/assets/6415493/0c620032-4bfd-43f6-a0c1-864c2e17d363)

mayby the node has problem

**Comment by elstic** [comment]
> /assign @elstic

ok, I'll remove the critical tag, but leave it open for a while and watch for a while. If it reappears I will comment .

**Comment by elstic** [comment]
it reappeared recently
1. This is a case of compaction scenario
server
```
fouramf-stable-726d7-4-59-6583-etcd-0                             1/1     Running     1 (72m ago)      153m   10.104.13.22    4am-node16   <none>           <none>
fouramf-stable-726d7-4-59-6583-milvus-standalone-76fc9f78ft5thb   1/1     Running     1 (68m ago)      153m   10.104.9.29     4am-node14   <none>           <none>
fouramf-stable-726d7-4-59-6583-minio-5f58c5d964-c2427             1/1     Running     0                153m   10.104.12.153   4am-node17   <none>           <none>
```

2. This is a case of concurrent search with vector returns
```
new-stable-mastqvgqj-2-100-2887-etcd-0                            1/1     Running     1 (73m ago)      154m   10.104.13.21    4am-node16   <none>           <none>
new-stable-mastqvgqj-2-100-2887-milvus-standalone-68d85cbcbgkz2   1/1     Running     1 (71m ago)      154m   10.104.6.57     4am-node13   <none>           <none>
new-stable-mastqvgqj-2-100-2887-minio-66f4f5c455-p4slj            1/1     Running     0                154m   10.104.21.24    4am-node24   <none>           <none>
```
