### ISSUE TITLE
[Bug]: panic: runtime error: slice bounds out of range [:-2147219860]

### ISSUE THREAD

**Issue by kkr37** [milvus-io/milvus#26584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.13
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

milvus unable to start because of "[slice bounds out of range](panic: runtime error: slice bounds out of range)"

### Milvus Log

[2023/08/23 08:14:34.889 +00:00] [WARN] [flowgraph/node.go:204] ["Invalid operate message input"] ["input length"=0]
[2023/08/23 08:14:34.889 +00:00] [WARN] [flowgraph/node.go:204] ["Invalid operate message input"] ["input length"=0]
[2023/08/23 08:14:34.889 +00:00] [WARN] [flowgraph/node.go:204] ["Invalid operate message input"] ["input length"=0]
[2023/08/23 08:14:34.889 +00:00] [WARN] [flowgraph/node.go:204] ["Invalid operate message input"] ["input length"=0]
[2023/08/23 08:14:34.889 +00:00] [INFO] [querynode/flow_graph_insert_node.go:320] [processDeleteMessage] [vchannel=by-dev-rootcoord-dml_4_441986384141459451v0] [segmentIDs="[]"] [paritions="[0]"]
[2023/08/23 08:14:34.889 +00:00] [WARN] [flowgraph/node.go:204] ["Invalid operate message input"] ["input length"=0]
[2023/08/23 08:14:34.889 +00:00] [WARN] [flowgraph/node.go:204] ["Invalid operate message input"] ["input length"=0]
[2023/08/23 08:14:34.889 +00:00] [INFO] [querynode/flow_graph_insert_node.go:320] [processDeleteMessage] [vchannel=by-dev-rootcoord-dml_0_441986384131789491v0] [segmentIDs="[]"] [paritions="[0]"]
panic: runtime error: slice bounds out of range [:-2147219860]

goroutine 3069 [running]:
[github.com/apache/arrow/go/v8/parquet/pqarrow.writeDenseArrow](http://github.com/apache/arrow/go/v8/parquet/pqarrow.writeDenseArrow)(0xc04def12c0, {0x471a5c8, 0xc00130d800}, {0x471c668?, 0xc04def14a0?}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...)
	/go/pkg/mod/[github.com/apache/arrow/go/v8@v8.0.0-20220322092137-778b1772fd20/parquet/pqarrow/encode_arrow.go:438](http://github.com/apache/arrow/go/v8@v8.0.0-20220322092137-778b1772fd20/parquet/pqarrow/encode_arrow.go:438) +0x2ffb
[github.com/apache/arrow/go/v8/parquet/pqarrow.WriteArrowToColumn](http://github.com/apache/arrow/go/v8/parquet/pqarrow.WriteArrowToColumn)({0x47093d8, 0xc0ba576d80}, {0x471a5c8, 0xc00130d800}, {0x471c668?, 0xc04def14a0?}, {0x0, 0x0, 0x0}, {0x0, ...}, ...)
	/go/pkg/mod/[github.com/apache/arrow/go/v8@v8.0.0-20220322092137-778b1772fd20/parquet/pqarrow/encode_arrow.go:226](http://github.com/apache/arrow/go/v8@v8.0.0-20220322092137-778b1772fd20/parquet/pqarrow/encode_arrow.go:226) +0x24c
[github.com/apache/arrow/go/v8/parquet/pqarrow.(*ArrowColumnWriter).Write](http://github.com/apache/arrow/go/v8/parquet/pqarrow.(*ArrowColumnWriter).Write)(0xc1a817c890, {0x47093d8, 0xc0ba576d80})
	/go/pkg/mod/[github.com/apache/arrow/go/v8@v8.0.0-20220322092137-778b1772fd20/parquet/pqarrow/encode_arrow.go:194](http://github.com/apache/arrow/go/v8@v8.0.0-20220322092137-778b1772fd20/parquet/pqarrow/encode_arrow.go:194) +0x533
[github.com/apache/arrow/go/v8/parquet/pqarrow.(*FileWriter).WriteColumnChunked](http://github.com/apache/arrow/go/v8/parquet/pqarrow.(*FileWriter).WriteColumnChunked)(0xc094fe6540, 0x0?, 0x0?, 0x3e5ab20?)
	/go/pkg/mod/[github.com/apache/arrow/go/v8@v8.0.0-20220322092137-778b1772fd20/parquet/pqarrow/file_writer.go:281](http://github.com/apache/arrow/go/v8@v8.0.0-20220322092137-778b1772fd20/parquet/pqarrow/file_writer.go:281) +0xf1
[github.com/apache/arrow/go/v8/parquet/pqarrow.(*FileWriter).WriteTable.func1](http://github.com/apache/arrow/go/v8/parquet/pqarrow.(*FileWriter).WriteTable.func1)(0x0?, 0x0?)
	/go/pkg/mod/[github.com/apache/arrow/go/v8@v8.0.0-20220322092137-778b1772fd20/parquet/pqarrow/file_writer.go:231](http://github.com/apache/arrow/go/v8@v8.0.0-20220322092137-778b1772fd20/parquet/pqarrow/file_writer.go:231) +0x9a
[github.com/apache/arrow/go/v8/parquet/pqarrow.(*FileWriter).WriteTable](http://github.com/apache/arrow/go/v8/parquet/pqarrow.(*FileWriter).WriteTable)(0xc094fe6540, {0x4712e28, 0xc0ba576a50}, 0x40000000)
	/go/pkg/mod/[github.com/apache/arrow/go/v8@v8.0.0-20220322092137-778b1772fd20/parquet/pqarrow/file_writer.go:247](http://github.com/apache/arrow/go/v8@v8.0.0-20220322092137-778b1772fd20/parquet/pqarrow/file_writer.go:247) +0x2db
[github.com/apache/arrow/go/v8/parquet/pqarrow.WriteTable](http://github.com/apache/arrow/go/v8/parquet/pqarrow.WriteTable)({0x4712e28, 0xc0ba576a50}, {0x46ead60, 0xc0b173f4a0}, 0x0?, 0x0?, {{0x46fa430, 0x5f38960}, 0x0, 0x0, ...})
	/go/pkg/mod/[github.com/apache/arrow/go/v8@v8.0.0-20220322092137-778b1772fd20/parquet/pqarrow/file_writer.go:42](http://github.com/apache/arrow/go/v8@v8.0.0-20220322092137-778b1772fd20/parquet/pqarrow/file_writer.go:42) +0xa9
[github.com/milvus-io/milvus/internal/storage.(*NativePayloadWriter).FinishPayloadWriter(0xc094b4cb90)](http://github.com/milvus-io/milvus/internal/storage.(*NativePayloadWriter).FinishPayloadWriter(0xc094b4cb90))
	/go/src/[github.com/milvus-io/milvus/internal/storage/payload_writer.go:443](http://github.com/milvus-io/milvus/internal/storage/payload_writer.go:443) +0x43e
[github.com/milvus-io/milvus/internal/storage.(*baseEventWriter).Finish(0xc094b4cbe0)](http://github.com/milvus-io/milvus/internal/storage.(*baseEventWriter).Finish(0xc094b4cbe0))
	/go/src/[github.com/milvus-io/milvus/internal/storage/event_writer.go:145](http://github.com/milvus-io/milvus/internal/storage/event_writer.go:145) +0x37
[github.com/milvus-io/milvus/internal/storage.(*baseBinlogWriter).Finish(0xc094b10b40)](http://github.com/milvus-io/milvus/internal/storage.(*baseBinlogWriter).Finish(0xc094b10b40))
	/go/src/[github.com/milvus-io/milvus/internal/storage/binlog_writer.go:120](http://github.com/milvus-io/milvus/internal/storage/binlog_writer.go:120) +0x1c2
[github.com/milvus-io/milvus/internal/storage.(*InsertCodec).Serialize](http://github.com/milvus-io/milvus/internal/storage.(*InsertCodec).Serialize)(0xc088b5fa58, 0xc0ba61d290?, 0x67?, 0xc02a5fd6a0)
	/go/src/[github.com/milvus-io/milvus/internal/storage/data_codec.go:475](http://github.com/milvus-io/milvus/internal/storage/data_codec.go:475) +0x11ec
[github.com/milvus-io/milvus/internal/datanode.(*rendezvousFlushManager).flushBufferData](http://github.com/milvus-io/milvus/internal/datanode.(*rendezvousFlushManager).flushBufferData)(0xc003af4840, 0xc003b1c300, 0x623c28c89f1a756, 0x56?, 0x0?, 0x1ee?)
	/go/src/[github.com/milvus-io/milvus/internal/datanode/flush_manager.go:383](http://github.com/milvus-io/milvus/internal/datanode/flush_manager.go:383) +0x2dc
[github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Sync.func1()](http://github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Sync.func1())
	/go/src/[github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:499](http://github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:499) +0x6c
[github.com/milvus-io/milvus/internal/util/retry.Do](http://github.com/milvus-io/milvus/internal/util/retry.Do)({0x4709330, 0xc0023d5000}, 0xc1a817d8c8, {0xc0ba61d7f8, 0x1, 0x0?})
	/go/src/[github.com/milvus-io/milvus/internal/util/retry/retry.go:42](http://github.com/milvus-io/milvus/internal/util/retry/retry.go:42) +0x110
[github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Sync](http://github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Sync)(0xc002338ea0, 0x5f38960?, {0x5f38960?, 0x0?, 0xc094b2bc20?}, 0xc094b2bc80)
	/go/src/[github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:498](http://github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:498) +0x939
[github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate](http://github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate)(0xc002338ea0, {0xc094b33590, 0x1, 0x1})
	/go/src/[github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:211](http://github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:211) +0x9e9
[github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc00135fa40)](http://github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc00135fa40))
	/go/src/[github.com/milvus-io/milvus/internal/util/flowgraph/node.go:127](http://github.com/milvus-io/milvus/internal/util/flowgraph/node.go:127) +0x2ac
created by [github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start](http://github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start)
	/go/src/[github.com/milvus-io/milvus/internal/util/flowgraph/node.go:71](http://github.com/milvus-io/milvus/internal/util/flowgraph/node.go:71) +0x79

**Comment by yah01** [comment]
Hi @kkr37, could you provide the schema of your collection? it may be helpful as I guess this could be reproduced by only some data type

**Comment by kkr37** [comment]
> Hi @kkr37, could you provide the schema of your collection? it may be helpful as I guess this could be reproduced by only some data type

<img width="1075" alt="image" src="https://github.com/milvus-io/milvus/assets/83685980/d9f9b623-6903-45db-a5a6-6f296964968c">
This is the schema of my collection, which contains approximately 10 million records.
I tried mounting the directory named "milvus" from the data directory into an empty directory. The Milvus service was able to start, and all the data is still intact.

**Comment by yanliang567** [comment]
/assign @LoveEachDay 
i don't think milvus supports move the "milvus" folder, it that the reason?
/unassign

**Comment by xiaofan-luan** [comment]
> > Hi @kkr37, could you provide the schema of your collection? it may be helpful as I guess this could be reproduced by only some data type
> 
> <img alt="image" width="1075" src="https://user-images.githubusercontent.com/83685980/262638403-d9f9b623-6903-45db-a5a6-6f296964968c.png"> This is the schema of my collection, which contains approximately 10 million records. I tried mounting the directory named "milvus" from the data directory into an empty directory. The Milvus service was able to start, and all the data is still intact.

you have to cleanup the meta in etcd also.
Otherwise there is mismatch in data and meta

**Comment by kkr37** [comment]
> 

@xiaofan-luan Thank you for your reply. After attempting to empty the directories where Milvus and etcd were mounted, all the data was lost. Could you please confirm whether I misunderstood your instruction to "cleanup the meta in etcd"?

**Comment by xiaofan-luan** [comment]
when you clean up the etcd, it means you create a new cluster.
If you want to upgrade, you will need to reserve both data dir(on S3), meta dir(on etcd ) and log on kafka/pulsar
