### ISSUE TITLE
[Bug]: create gpu index  then indexnode crash

### ISSUE THREAD

**Issue by lmyyao** [milvus-io/milvus#26582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.0beta
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.0b
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When i create_index, index_params={
  "metric_type":"L2",
  "index_type":"GPU_IVF_FLAT",
  "params":{"nlist":1024}
}, the indexnode crash 

### Milvus Log

[2023/08/23 09:18:29.804 +00:00] [INFO] [indexnode/task.go:532] ["indexnode deserialize data success"] ["index id"=0] ["index name"=] [collectionID=443752090469405252] [partition
ID=443752090469405253] [segmentID=443752090475808261]
[2023/08/23 09:18:29.804 +00:00] [INFO] [indexnode/task.go:235] ["Successfully load data"] [buildID=443752090482812389] [Collection=443752090469405252] [SegmentIf=443752090475808
261]
milvus: /go/src/github.com/milvus-io/milvus/cmake_build/thirdparty/knowhere/knowhere-src/src/common/factory.cc:19: knowhere::Index<knowhere::IndexNode> knowhere::IndexFactory::Cr
eate(const string&, const knowhere::Object&): Assertion `func_mapping_.find(name) != func_mapping_.end()' failed.
SIGABRT: abort
PC=0x7f6f466dd00b m=15 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 317 [syscall]:
non-Go function
	pc=0x7f6f466dd00b
non-Go function
	pc=0x7f6f466bc858
non-Go function
	pc=0x7f6f466bc728
non-Go function
	pc=0x7f6f466cdfd5
non-Go function
	pc=0x7f6f45f1d76e
runtime.cgocall(0x2f59010, 0xc0003cd348)
	/usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc0003cd2e0 sp=0xc0003cd2a8 pc=0x122bb7c
github.com/milvus-io/milvus/internal/util/indexcgowrapper._Cfunc_CreateIndex(0x65, 0x7f6d90008000, 0x7f6d9000b000, 0xc00060e658, {0x7f6d90000020, 0x7f6d9000e000, 0x7f6d9000e010,
0x7f6d9000e020, 0x7f6d9000f000, 0x7f6d9000f008, ...})
	_cgo_gotypes.go:196 +0x5b fp=0xc0003cd348 sp=0xc0003cd2e0 pc=0x28d959b

**Comment by liliu-z** [comment]
It caused by mismatch of the versions of pymilvus and Milvus. @Presburger can you help check the version?

Also you can use Milvus 2.3 to avoid this mismatch and better perfromance.

**Comment by lmyyao** [comment]
> It caused by mismatch of the versions of pymilvus and Milvus. @Presburger can you help check the version?
> 
> Also you can use Milvus 2.3 to avoid this mismatch and better perfromance.

i installed using helm milvus/milvus         4.0.11          2.3.0-beta, 
pymilvus==2.3.0b1

**Comment by Presburger** [comment]
please use gpu image docker pull milvusdb/milvus:v2.3.0-gpu

**Comment by xiaofan-luan** [comment]
> please use gpu image docker pull milvusdb/milvus:v2.3.0-gpu

we should throw error if image don't support gpu rather than crash?
