### ISSUE TITLE
[Bug]: Upsert data to collection which enable dynamic field gets error json field '$meta' is illegal

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#26595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230823-8d3398c1
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.4.0.dev115
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. create collection with a pk_int64_field and a float_vector field, and enable dynamic field
2. insert 100 entities only pk, vector columns
3. flush
4. upsert 10 entities only pk, vector column (no dynamic field), gets an error:
```
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=json field '$meta' is illegal, array type mismatch: expected=need string array, actual=got nil: invalid parameter)>
```

### Expected Behavior

I don't know. Maybe I expected to upsert successfully

### Steps To Reproduce

```markdown
def test_upsert_data_debug(self):
        self._connect()
        collection_w = ApiCollectionWrapper()
        collection_w.init_collection(name=cf.gen_unique_str(prefix),
                                     schema=cf.gen_default_collection_schema(enable_dynamic_field=True))
        df = cf.gen_df_pk_vec(100)
        collection_w.insert(df)
        collection_w.flush()

        upsert_df = cf.gen_df_pk_vec(10, start=100)
        collection_w.upsert(data=upsert_df)
```
gen_df_pk_vec:
```
def gen_df_pk_vec(nb=ct.default_nb, dim=ct.default_dim, start=0, size=10000):
    int_values = pd.Series(data=[i for i in range(start, start + nb)])
    float_vec_values = gen_vectors(nb, dim)
    df = pd.DataFrame({
        ct.default_int64_field_name: int_values,
        ct.default_float_vec_field_name: float_vec_values
    })
    return df
```
```


### Milvus Log

_No response_

### Anything else?

_No response_

**Comment by smellthemoon** [comment]
@ThreadDao pr merged, plz help to verify.

**Comment by athbagde** [comment]
Has there been any solution on this... Still facing this issue

**Comment by yanliang567** [comment]
> Has there been any solution on this... Still facing this issue

We believe this was fixed. Please retry on latest release Milvus v 2.5.5, if it reproduces, file a new issue and attach the milvus logs.

**Comment by athbagde** [comment]
I am a bit new to the Milvus.... How do i get Milvus logs?

**Comment by xiaofan-luan** [comment]
Could you please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation? For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.

**Comment by athbagde** [comment]
Thanks... I will do so and create a new issue
