### ISSUE TITLE
[Bug]: metrics "milvus_datacoord_datanode_num" value is inaccurate

### ISSUE THREAD

**Issue by yaliqin** [milvus-io/milvus#26605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.8
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):  
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

We have two milvus cluster. There are 6 data nodes in cluster 1, but the metrics value is 4; There are 1 data node in another cluster, but I can't find this metrics from datacoord metrics endpoint at all.

### Expected Behavior

The metrics value can be aligned with the real number of  data node.

**Comment by wukathy21** [comment]
Could you reveal the practical use cases in which you are utilizing Chroma DB and the reasons behind your choice of using Chroma DB as the vector database?

**Comment by yaliqin** [comment]
> Chroma DB and the reasons behind your choice of using Chroma DB as the vector database?

We have two clusters. Both have planed node number. I don't think we change the numbers after deployment. We can try v2.3.0. Will update the results.
