### ISSUE TITLE
[Bug]:  Index recreation

### ISSUE THREAD

**Issue by caoping6** [milvus-io/milvus#26606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.8
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): java-sdk
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

操作方式：已经向集合写入了14亿256维向量数据，在attu上配置创建索引，页面无响应，然后多点击创建了几次
异常现象：索引生成之后，发现无法删除索引，通过sdk调用删除索引接口，返回异常信息：R{exception=Exception: there are multiple indexes, please specify the index_name, status=1, data=null}
排查etcd元数据以及s3索引目录均生成俩份索引文件
![image](https://github.com/milvus-io/milvus/assets/40586262/251f2375-5a3e-4726-80fc-27d0df1950c7)

**Comment by caoping6** [comment]
![image](https://github.com/milvus-io/milvus/assets/40586262/a46535f7-ea90-4a4d-93be-49d30d5dac4d)

**Comment by xiaofan-luan** [comment]
this means your index is already done.

if you want to recreate index, you need to drop index and recreate

**Comment by xiaofan-luan** [comment]
And index building is a very very long task.
It's not a good idea to use attu to create index

**Comment by czs007** [comment]
@caoping6 
To delete through the SDK, you need to provide the index name. From what I gather, it seems that you have created indexes for multiple fields. You can use Attu to check how many fields have been indexed. Additionally, Attu also allows you to directly delete indexes.
