### ISSUE TITLE
[Bug]: MILVUS uses all memory on EC2

### ISSUE THREAD

**Issue by Andriy1989** [milvus-io/milvus#26614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.12 (and older versions)
- Deployment mode: standalone 

- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.2.12
- OS(Ubuntu or CentOS): Ubuntu 
- CPU/Memory: 16,0	Gb
- GPU: -
- Others: AWS EC2 instance
```

### Current Behavior

Hello! 
I installed milvus standalone on an EC2 instance (Type t2.xlarge). 
Now I have two collections, and each has many partitions. 
The problem is that milvus uses more and more memory. 
Until it uses all available memory.
During operation, files are created in the volumes/milvus folder.

I am now solving the problem by simply deleting this folder. 
I already wrote about this problem before, then I was advised to simply reduce the number of collections, but increase the number of partitions. 
These breaths only slowed down the memory loss. 
The problem is that milvus doesn't delete temporary files by itself.

### Expected Behavior

Configure milvus to delete its temporary files by itself.

### Steps To Reproduce

```markdown
- Milvus version:2.2.12 (and older versions)
- Deployment mode: standalone 
- Others: AWS EC2 instance
```

**Comment by yanliang567** [comment]
@Andriy1989 this is a known issue, and we had some improvement in milvus v2.3.0 in disk and memory usage. Please try.  Also could you please share more info about for what you need many partitions? have you try partition key feature for your scenarios? https://milvus.io/docs/partition_key.md#Partition-key-based-Multi-tenancy

/assign @Andriy1989 
/unassign

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version:2.2.12 (and older versions)
> - Deployment mode: standalone 
> 
> - SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.2.12
> - OS(Ubuntu or CentOS): Ubuntu 
> - CPU/Memory: 16,0	Gb
> - GPU: -
> - Others: AWS EC2 instance
> ```
> 
> ### Current Behavior
> Hello! I installed milvus standalone on an EC2 instance (Type t2.xlarge). Now I have two collections, and each has many partitions. The problem is that milvus uses more and more memory. Until it uses all available memory. During operation, files are created in the volumes/milvus folder.
> 
> I am now solving the problem by simply deleting this folder. I already wrote about this problem before, then I was advised to simply reduce the number of collections, but increase the number of partitions. These breaths only slowed down the memory loss. The problem is that milvus doesn't delete temporary files by itself.
> 
> ### Expected Behavior
> Configure milvus to delete its temporary files by itself.
> 
> ### Steps To Reproduce
> ```
> - Milvus version:2.2.12 (and older versions)
> - Deployment mode: standalone 
> - Others: AWS EC2 instance
> ```
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

multiple partitions will consume memories.
and also milvus is trying to fully utilize all the memories on EC2 if possible.

1. think of not using partitions collections to isolate your data
2. think of use pod to limit milvus memory if possible

**Comment by Andriy1989** [comment]
@yanliang567 and @xiaofan-luan thank you for your quick reply. 
My task is to find similar products, either by image or by description. 
So I have two collections for these two types, and many partitions for each product category. T
he names of the partitions look like this {"name": "PANTS_MEN", "collection_name": "X", "description": ""}..... 
I have a hybrid search with a database where I first search the database for a selection of products, and only then find the most similar among this sample in the specified partition. 
I will try not to use partitions at all and set a memory limit for milvus data usage. I will report the result later. 

By the way, I encountered such a technique when working with milvus, that instead of storing collections, people created them "on the fly", searched for similar objects and deleted them afterwards. 
It is important that I have only a few thousand products, I think that the maximum number will be in the tens of thousands, and a one-time search will be between hundreds of products.

**Comment by Andriy1989** [comment]
Hello! In the settings I added a limit on memory usage and it worked, but only after sudo docker-compose down and exceeding the limit.

**Comment by yanliang567** [comment]
> Hello! In the settings I added a limit on memory usage and it worked, but only after sudo docker-compose down and exceeding the limit.

I think this is expected. @LoveEachDay could you please confirm that?
/assign @LoveEachDay
