### ISSUE TITLE
Database option in Attu UI

### ISSUE THREAD

**Issue by harivaats** [milvus-io/milvus#26610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[Bug]: I read in the Milvus documentation that we can create multiple databases inside Milvus. But I am not able to see any option in Attu to manage the database. It is showing only collection under default database. Could you please clarify.

**Comment by shanghaikid** [comment]
Which version is your attu?  You need to click here to manage your database in Milvus.
![image](https://github.com/milvus-io/milvus/assets/185051/a5e1128a-8f1f-4d84-85eb-294b0915e2e8)

**Comment by harivaats** [comment]
Thank you. Which version should I suppose to upgrade. I am currently using  v2.2.7

**Comment by shanghaikid** [comment]
> @shanghaikid Thank you. Which version should I suppose to upgrade. I am currently using v2.2.7

v2.2.8 add database support

**Comment by harivaats** [comment]
Thank you !
