### ISSUE TITLE
[Bug]: drop_partition() doesn't remove data in the partition

### ISSUE THREAD

**Issue by xiyuecangxin** [milvus-io/milvus#26615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.4
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    none
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.2.4
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: -
- GPU: -
- Others: -
```

### Current Behavior

Here is the code(I wrapped the client and it works correctly):
```
    from client import milvus_client
    milvus_client.drop_collection("test")
    coll = milvus_client.create_collection("test", 2)
    coll.create_partition("testpart")
    coll.insert([["1"], [[0.5, 0.5]], ["title"]], "testpart")
    coll.load()
    print(coll.query('pk != -1', partition_names=["testpart"]))
    coll.release()
    coll.drop_partition("testpart")
    print(coll.has_partition("testpart"))
    coll.load()
    print(coll.query('pk != -1'))
    print(coll.query('pk != -1', partition_names=["testpart"])) #fail
```
And the result is
```
[{'pk': 443791116992905994}]
False
[{'pk': 443791116992905994}]
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=partition name testpart not found)>
```    

### Expected Behavior

The second query should return []

### Steps To Reproduce

```markdown
-
```

### Milvus Log

-

### Anything else?

-

**Comment by yanliang567** [comment]
@xiyuecangxin sounds like an issue that was fixed in latest release. could you please retry on v2.3.0?
/assign @xiyuecangxin 
/unassign

**Comment by xiyuecangxin** [comment]
> @xiyuecangxin sounds like an issue that was fixed in latest release. could you please retry on v2.3.0? /assign @xiyuecangxin /unassign

Thanks, I'll try tomorrow. Will milvus lost data if I copy volumes/* to 2.3.0 from 2.2.4?

**Comment by xiaofan-luan** [comment]
if all your etcd, rocksdb and minio use volumes directory, then the answer is no.
but please check all the directory is under volumes

**Comment by xiyuecangxin** [comment]
> @xiyuecangxin sounds like an issue that was fixed in latest release. could you please retry on v2.3.0? /assign @xiyuecangxin /unassign

2.3.0 is right. thanks
