### ISSUE TITLE
[Bug]: meta存储为 mysql的时候，milvus databse 信息是否未作持久化存储？

### ISSUE THREAD

**Issue by obailiumingo** [milvus-io/milvus#26620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.10， 2.2.14
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):     kafka
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.2.12
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1.当我从2.2.10升级到2.2.14 的时候发现之前创建的database全部丢失。
2. 在2.1.14版本上创建新的database ，然后重启rootcoord，发现稳定浮现

### Expected Behavior

升级或者重启不会造成数据丢失

### Steps To Reproduce

```markdown
1. 创建database
2. 在该database下创建collection
3. 删除rootcoord
4. 查询database 和 collection信息，发现重现
```

### Anything else?

两个疑点：
1. milvus 的 metadata中没有database 以及 database 与 collection的映射关系，请问这些数据是存在哪里的？
2. 通过阅读rootcoord相关源码，发现database 是存储在内存中的，并且我们复现了一下，感觉印证了这一猜想，如果我们猜想不对可否回答一下我们的疑惑？

**Comment by xiaofan-luan** [comment]
we no longer support mysql as meta store

**Comment by xiaofan-luan** [comment]
@jaime0815 
could you remove the document and legacy code?

**Comment by obailiumingo** [comment]
> we no longer support mysql as meta store

好的，谢谢，了解了
