### ISSUE TITLE
When a collection is creating index, another collection can not insert vector 

### ISSUE THREAD

**Issue by zhang19941219** [milvus-io/milvus#2663]
milvus version： 0.10.0

pymilvus: 0.2.13

the first collection:   
> collection: 10070000
> dimension: 128
> index: IVFPQ
> index_file_size: 1024
> metric_type: L2
> m: 16
>nlist: 16384

the second collection:
> count: 79742(unimportant)
> dimension: 128
> index: HNSW
> index_file_size: 1024
> metric_type: L2
> M: 16
> efConstruction: 1000

milvus conf:
>  version: 0.5
> cpu cache: 4GB

**I use milvus admin to create index in the first collection, and I insert vectors to the second collection continuously at the same time. The insert process was blocked by the first collection's action. (All this two collections‘ metadata was stored in another mysql server， and use cpu only)**

**I can not insert vector as I create index, is this a bug?**

**Comment by yhmo** [comment]
It is a known issue. Insert and CreateIndex request is similar since they both need to change data. When server receive Insert or CreateIndex request, the server put them into a queue to execute one by one. 
To avoid this, we can break CreateIndex operation by Ctrl+C. After terminate the client, milvus server will put indexBuild task to background, so that the main thread can process request from other clients

**Comment by zhang19941219** [comment]
> It is a known issue. Insert and CreateIndex request is similar since they both need to change data. When server receive Insert or CreateIndex request, the server put them into a queue to execute one by one.
> To avoid this, we can break CreateIndex operation by Ctrl+C. After terminate the client, milvus server will put indexBuild task to background, so that the main thread can process request from other clients

thank you very much! Will this issue be fixed in a future version?

**Comment by yhmo** [comment]
Not yet plan it since its priority is low.

**Comment by yhmo** [comment]
The v1.1.1 is stable, we only fix critical bugs for v1.x, no more features/improvement.
Abandoned this feature.
