### ISSUE TITLE
attu approxEntityCount value didn't change when deleting successfully

### ISSUE THREAD

**Issue by stoneLee81** [milvus-io/milvus#26654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.5
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.6 java sdk
- OS(Ubuntu or CentOS): macos
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

In the attu interface, the deleted data, the data is indeed deleted, but the approxEntityCount has not changed.
[image](https://user-images.githubusercontent.com/18001708/263738089-d7e9f07c-c38a-4e02-8896-1f7e92bc7efe.png)
in fact, there is no data left, i deleted all, but the approxEntityCount field is still show 3 data left.

### Expected Behavior

approxEntityCount changed to 0

### Steps To Reproduce

```markdown
use milvus sdk to insert 3 data, then delete them,check the approxEntityCount value,it should be 0,but it's still 3.
```

**Comment by yanliang567** [comment]
I think this is by design for now, as it was implemented by the api of milvus num_entities. 
@shanghaikid any plan to use count(*) for the implement?

/assign @shanghaikid 
/unassign
