### ISSUE TITLE
query/search without loadCollection to local memory?

### ISSUE THREAD

**Issue by stoneLee81** [milvus-io/milvus#26659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

When the demo of milvus executes the query, it needs to execute the loadCollection operation to load the memory locally. This is somewhat uncontrollable for the local memory，It may cause insufficient memory benefits to the service, resulting in the service immediately crash，Whether milvus supports the query without loading the memory to the local before querying/searching. After searching some related docs about milvus, I did not find a similar introduction demo.

**Comment by stoneLee81** [comment]
@yanliang567 Do you have time to check and answer this question?

**Comment by yanliang567** [comment]
Milvus is a memory based database, which means you have to load the data(raw data or index data) into memory locally before you are able to search/query.  If you are using diskAnn index, it just save the memory but it still requires load the index data or meta data into memory first. 
@stoneLee81

**Comment by stoneLee81** [comment]
In this way, if my API service server is a multi cluster, I have to load the collection data locally into each of my services server. In this way, is it a waste of computing resources for my API service? @yanliang567

**Comment by xiaofan-luan** [comment]
Don't quite understand your use case. But milvus is a client/server architecture, and usually all data is host in server's memory by loading colelction

**Comment by stoneLee81** [comment]
When using Milvus java-sdk to use searching, I need to loadCollection to load data into local memory before performing query-related operations. In this case, If this funcion of milvus is in my back-end biz service and this service have other biz apis not just milvus apis, when starting these biz services instances, each biz service instance needs to run loadCollection into memory, because milvus needs to loadCollection to local memory before searching,and it's waste of memory for the biz backend service. 
Does it support http api calling such as chroma does? this will save a lot of memory when the milvus api merged into biz services. @xiaofan-luan

**Comment by xiaofan-luan** [comment]
> 

Milvus  is a client server software.

for your backend service, each of the service only need to connect to server to get data. and data is only needed to load once

**Comment by xiaofan-luan** [comment]
data is not gonna to load on your service, which is the client of milvus

**Comment by stoneLee81** [comment]
I talked server side, because milvus api merged with biz apis, and wrap it into service. if milvus must load data into local, I have to split milvus api service from biz as independent service @xiaofan-luan

**Comment by stoneLee81** [comment]
我用中文来表达这个吧，英语确实差。

我现在使用的场景是，milvus java sdk封装的函数，是集成在业务的服务中，这些服务在k8s环境里面会起多份，因为是业务的服务，并没有太大的内存波动，每个服务开启的资源（cpu,内存）都不大。

现在的问题是，如果，我将milvus的封装的函数，比如查询，新增的也集成在这个业务服务中，因为，milvus需要将数据载入到本地内存里面，这样，我这些服务就都需要因为milvus的这个特性，额外增加内存,这个内存随着数据增加，是需要不断增加的。

我查看了一下，同类的，比如chroma, weaviate, pinecone, 不需要将数据载入本地内存，也可以进行查询相关操作。所以，问题的出发，是想咨询，milvus目前是必须将数据载入内存才能后续查询操作，是否有类似的，查询不需要载入内存到本地，也能进行查询到？ @xiaofan-luan

**Comment by yanliang567** [comment]
@stoneLee81 据我所知上面那几个同类服务其实并不是不需要加载数据到内存，他们只是默认就加载，没有把加载的选择权交给用户而已。从这个角度讲Milvus更能让用户有效自主的控制内存使用，提高内存使用效率。
