### ISSUE TITLE
[Bug]: After deleting entities, 'is_empty' or 'num_entities' do not work (despite using 'flush()')

### ISSUE THREAD

**Issue by ZhanyuanLi** [milvus-io/milvus#26658]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster): standalone 
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.0
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

After clearing all data in 'collection', the 'is_empty' operation is still 'False'. However, if waiting for a long time, the result of 'is_empty' becomes True.

**Comment by yanliang567** [comment]
this is by design for now.  if you want a precise count, please try count(*) in milvus 2.3.0. 
check here for more details: https://milvus.io/docs/query.md#Count-entities

**Comment by xiaofan-luan** [comment]
for Milvus 2.3, you can use count to get exact number of entities
