### ISSUE TITLE
[Bug]: proxy LookAsideBalancer don't remove offline node

### ISSUE THREAD

**Issue by zhuanxuhit** [milvus-io/milvus#26665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.0
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

when old query node down, proxy don't remove it from LookAsideBalancer
<img width="1440" alt="image" src="https://github.com/milvus-io/milvus/assets/9429354/f814b532-f26e-4339-a484-8cbd3da3bc0b">

**Comment by weiliu1031** [comment]
by design, the look aside balancer will remove the querynode if heartbeat failed for more than 3 times and the heartbeat timeout is 3s, which means 9s in total.

so if you saw failure to a offline query node which last for more than a few seconds, please upload the proxy logs.

**Comment by zhuanxuhit** [comment]
[proxy.log](https://github.com/milvus-io/milvus/files/12471010/proxy.log)
https://github.com/milvus-io/milvus/blob/master/internal/proxy/look_aside_balancer.go#L210 
I am unable to locate the code for removing a node from the metricsUpdateTs struct.

**Comment by weiliu1031** [comment]
> [proxy.log](https://github.com/milvus-io/milvus/files/12471010/proxy.log) https://github.com/milvus-io/milvus/blob/master/internal/proxy/look_aside_balancer.go#L210 I am unable to locate the code for removing a node from the metricsUpdateTs struct.

by design, we will keep doing heartbeat to query node which is unreachable, cause it may came back in heavy workload case. and as you mentioned, here need another policy to stop the heartbeat for nodes won't came back
