### ISSUE TITLE
[Bug]: memory usage of datanode increased to 65GB when inserting with 4 clients concurrently

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#26673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230828-905d4b38
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):  pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
```

### Current Behavior

memory of datanode increased to 65GB when there are 4 clients inserting concurrently.
![image](https://github.com/milvus-io/milvus/assets/82361606/d5a51b4c-4f2a-4319-a3c2-97510108dd53)

### Expected Behavior

memory usage of datanode should be stable, and not more than 2GB if possible

### Steps To Reproduce

```markdown
1. create a collection with 768d vectors and a few scalar fields such as string, int, float
2. start 4 client to do insert concurrently (no manual flush, not build index)
   2.1. each client insert ni=5000 for 2000 times
```

### Milvus Log

pod names in devops:
```
yanliang-insert3-milvus-datanode-9fd4b58f-d4r9v                 1/1     Running             0                151m
yanliang-insert3-milvus-indexnode-5f6dcc59b9-cqr8d              1/1     Running             0                151m
yanliang-insert3-milvus-mixcoord-5cc6c5c865-z2jt4               1/1     Running             0                151m
yanliang-insert3-milvus-proxy-5cbd87899-ws8f8                   1/1     Running             0                151m
yanliang-insert3-milvus-querynode-546f875dd9-nk8jz              1/1     Running             0                151m
```

### Anything else?

![profile001](https://github.com/milvus-io/milvus/assets/82361606/7e9ce787-9175-4e0c-86d5-20fd28079710)

**Comment by xiaofan-luan** [comment]
I think it's kind of a problem that flush manager can not catch up.

@bigsheeper can you help on this?

**Comment by bigsheeper** [comment]
> I think it's kind of a problem that flush manager can not catch up.
> 
> @bigsheeper can you help on this?

@xiaofan-luan You're right, DataNode submitted **318** sync tasks:
![image](https://github.com/milvus-io/milvus/assets/42060877/0652afa3-3a1f-48ef-85a1-3572f7c590b5)

But only **164** tasks finished:
![image](https://github.com/milvus-io/milvus/assets/42060877/42d42ecf-025c-4f23-bbbd-890b61d73686)

**Comment by bigsheeper** [comment]
![image](https://github.com/milvus-io/milvus/assets/42060877/2a9e055f-0b64-40ed-8aa1-48b46e66bc8a)
