### ISSUE TITLE
[Bug]: Milvus 2.3 getMetrics get wrong node infos

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus#26678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: e11f84ff-dev-gpu
- Deployment mode(standalone or cluster): standalone
```

### Current Behavior

The data returned from `GetMetrics` is incorrect.  Every identifier of these child nodes is `1`. 

Because of this, the system view in attu is broken. 

![image](https://github.com/milvus-io/milvus/assets/185051/0836d6f3-037e-483b-880d-4f99d7684199)

### Expected Behavior

This is correct result. 
![image](https://github.com/milvus-io/milvus/assets/185051/e618fa38-abf0-48ca-bfb7-b2f22a9696ba)

**Comment by smellthemoon** [comment]
![1](https://github.com/milvus-io/milvus/assets/64083300/efa98c94-73c6-458d-b854-d6e7a74e702a)
![2](https://github.com/milvus-io/milvus/assets/64083300/b6008bea-8174-4ad6-90b0-f1c983772a82)
it's ok to use fe7f7ea237ef77b38a343b475acca8518e2abe90 and Attu 2.2.8. Please help to check it. Thank you very much. @shanghaikid
