### ISSUE TITLE
[Enhancement]: Fix warning "github.com/golang/protobuf/proto" is deprecated

### ISSUE THREAD

**Issue by jiaoew1991** [milvus-io/milvus#26674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

"github.com/golang/protobuf/proto" package is deprecated. We should use "google.golang.org/protobuf/proto" package to instead it.

**Comment by JadeFlute0127** [comment]
The upgrade of the protobuf package involves too many files, and I plan to gradually complete it in a certain order
