### ISSUE TITLE
[Bug]: Memory leaked in QueryNode

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#26684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![img_v2_908fdc8e-eff5-4255-9c6b-8d064420081g](https://github.com/milvus-io/milvus/assets/12216890/4481f4b4-6131-4aa4-a362-624ae42d12cc)
QueryNode reports a high memory usage with only few segments:
![img_v2_1aed09cf-f5c5-4079-b0cd-567c3fd60e2g](https://github.com/milvus-io/milvus/assets/12216890/86049fe7-c315-4be8-bbfc-4cba15e3d45a)

**Comment by yanliang567** [comment]
@yah01 could you please share more info about how to reproduce this issue?
/assign @yah01
