### ISSUE TITLE
[Bug]: Index coordinator unable to connect to active root coordinator

### ISSUE THREAD

**Issue by zirota** [milvus-io/milvus#26681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.12
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
```

### Current Behavior

I have deployed Milvus coordinators with `enableActiveStandby: true`. With replica set to 2.

rootCoord and dataCoord started successfully in active-standby mode.
queryCoord unable to start as it cannot find any active indexCoord 
indexCoord seem to stuck in standby mode, keeps connecting to the standby rootCoord.

I suspect the traffic from the rootCoord K8s service is not going to the active rootCoord. Does it matter?

### Expected Behavior

indexCoord should connect to an active rootCoord

### Steps To Reproduce

```markdown
Startup Milvus with coordinator replica set to 2 each and config `enableActiveStandby: true`
```

### Milvus Log

Both my index coordinators are giving the following log:

```
[2023/08/29 09:36:25.730 +00:00] [DEBUG] [indexcoord/index_coord.go:418] ["IndexCoord GetComponentStates"] ["IndexCoord component state"="nodeID:-1 role:\"IndexCoord\" state_code:StandBy "][2023/08/29 09:36:25.730 +00:00] [DEBUG] [indexcoord/index_coord.go:418] ["IndexCoord GetComponentStates"] ["IndexCoord component state"="nodeID:-1 role:\"IndexCoord\" state_code:StandBy "][2023/08/29 09:36:31.565 +00:00] [WARN] [retry/retry.go:44] ["retry func failed"] ["retry time"=32160] [error="WaitForComponentStates, not meet, rootcoord current state: StandBy"]
``

### Anything else?

_No response_

**Comment by wayblink** [comment]
@zirota Hi, please use https://github.com/milvus-io/milvus/tree/master/deployments/export-log to collect complete logs for us to investigate. And we recommend to use 2.2.14, there are some fixs about rpc connections.

**Comment by zirota** [comment]
hey @wayblink, unfortunately I do not have access to `kubectl` or the pod so I will not be able to collect the complete logs.

For now to resolve the issue, I have scaled the coordinators to 1 replica which is working fine for me.
I will also look to upgrade to 2.2.14.
