### ISSUE TITLE
[Docker] What can the http web server do?

### ISSUE THREAD

**Issue by zhxh1** [milvus-io/milvus#2669]
## Report needed documentation

**Report needed documentation**
The official [installation guide](https://milvus.io/docs/guides/get_started/install_milvus/gpu_milvus_docker.md) is great! However, [this step](https://milvus.io/docs/guides/get_started/install_milvus/gpu_milvus_docker.md#Step-4-Start-Docker-container) does not explain what can the web server, listening at port 19121, do.

**Describe the documentation you'd like**
A guide on how to use the web server (or what can it do).

**Steps taken to search for needed documentation**
Skimmed all the offficial docs.
The only thing I can find is in the server config:
```
 #----------------------+------------------------------------------------------------+------------+-----------------+
 # Network Config       | Description                                                | Type       | Default         |
 #----------------------+------------------------------------------------------------+------------+-----------------+
 # bind.address         | IP address that Milvus server monitors.                    | IP         | 0.0.0.0         |
 #----------------------+------------------------------------------------------------+------------+-----------------+
 # bind.port            | Port that Milvus server monitors. Port range (1024, 65535) | Integer    | 19530           |
 #----------------------+------------------------------------------------------------+------------+-----------------+
 # http.enable          | Enable web server or not.                                  | Boolean    | true            |
 #----------------------+------------------------------------------------------------+------------+-----------------+
 # http.port            | Port that Milvus web server monitors.                      | Integer    | 19121           |
 #                      | Port range (1024, 65535)                                   |            |                 |
 #----------------------+------------------------------------------------------------+------------+-----------------+
```

**Comment by zhxh1** [comment]
Visiting the server with a browser, I can only see: `Welcome to milvus`

**Comment by BossZou** [comment]
Http server provide several endpoints to operate milvus. You may see [README.md](https://github.com/milvus-io/milvus/blob/master/core/src/server/web_impl/README.md) to find how to use it.

**Comment by simon-atom** [comment]
The README link in the comment from June 29, 2020 gives a 404
