### ISSUE TITLE
[Bug]: ERROR: arrow/11.0.0: option 'with_thrift' doesn't exist

### ISSUE THREAD

**Issue by unfode** [milvus-io/milvus#26697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
Platform: M2/arm MacOS
```

### Current Behavior

When I run `make test-go`, I get:
![image](https://github.com/milvus-io/milvus/assets/95689995/d3177659-cd2a-43d7-9c56-f07056e60276)

**Comment by yah01** [comment]
Hi @unfode, this has been fixed, rebase the newest master branch and clear your conan cache should help, clear only arrow cache with: `rm -rf ~/.conan/data/arrow`

**Comment by unfode** [comment]
Clearing the cache works. Thank you!

**Comment by caesarjuly** [comment]
I have the same issue while buiding milvus in docker. Clearing the cache doesn't work for me. 
```
docker exec -ti milvus_builder_1 bash                                                                                                                        ✔  3s   06:36:22 PM  
root@6db508c45391:/go/src/github.com/milvus-io/milvus# make
Download milvus-proto repo ...
Build 3rdparty ...
WARN: Cannot find /go/src/github.com/milvus-io/milvus/internal/core/output/lib/libjemalloc.so
/go/src/github.com/milvus-io/milvus/cmake_build /go/src/github.com/milvus-io/milvus
Running on ubuntu20.04
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

WARN: rocksdb/6.29.5: requirement zstd/1.5.2 overridden by your conanfile to zstd/1.5.4 
ERROR: arrow/11.0.0: option 'with_thrift' doesn't exist
Possible options are ['shared', 'fPIC', 'gandiva', 'parquet', 'substrait', 'skyhook', 'acero', 'cli', 'compute', 'dataset_modules', 'deprecated', 'encryption', 'filesystem_layer', 'hdfs_bridgs', 'plasma', 'simd_level', 'runtime_simd_level', 'with_backtrace', 'with_boost', 'with_csv', 'with_cuda', 'with_flight_rpc', 'with_flight_sql', 'with_gcs', 'with_gflags', 'with_glog', 'with_grpc', 'with_jemalloc', 'with_mimalloc', 'with_json', 'with_llvm', 'with_openssl', 'with_opentelemetry', 'with_orc', 'with_protobuf', 'with_re2', 'with_s3', 'with_utf8proc', 'with_brotli', 'with_bz2', 'with_lz4', 'with_snappy', 'with_zlib', 'with_zstd']
conan install failed
make: *** [Makefile:162: build-3rdparty] Error 1
```
Here is the environment settings:
```
IMAGE_REPO=milvusdb
IMAGE_ARCH=amd64
OS_NAME=ubuntu20.04
DATE_VERSION=20230830-30ca458
LATEST_DATE_VERSION=20230823-32307db
GPU_DATE_VERSION=20230822-a64488a
LATEST_GPU_DATE_VERSION=20230317-a1c7b0c
MINIO_ADDRESS=minio:9000
PULSAR_ADDRESS=pulsar://pulsar:6650
ETCD_ENDPOINTS=etcd:2379

```
Is there any solution? Thank you

**Comment by jiaoew1991** [comment]
> Hi @unfode, this has been fixed, rebase the newest master branch and clear your conan cache should help, clear only arrow cache with: `rm -rf ~/.conan/data/arrow`

Hi @caesarjuly  You can try this solution

**Comment by caesarjuly** [comment]
> > Hi @unfode, this has been fixed, rebase the newest master branch and clear your conan cache should help, clear only arrow cache with: `rm -rf ~/.conan/data/arrow`
> 
> Hi @caesarjuly You can try this solution

As I mentioned above, I tried but it didn't work. I don't have this directory in the container.

**Comment by caesarjuly** [comment]
> > Hi @unfode, this has been fixed, rebase the newest master branch and clear your conan cache should help, clear only arrow cache with: `rm -rf ~/.conan/data/arrow`
> 
> Hi @caesarjuly You can try this solution

I tried. But this error still exists. I don't have this folder in the container.
The latest .env I'm using is:
```
IMAGE_REPO=milvusdb
IMAGE_ARCH=amd64
OS_NAME=ubuntu20.04
DATE_VERSION=20230907-2a755ba
LATEST_DATE_VERSION=20230907-2a755ba
GPU_DATE_VERSION=20230822-a64488a
LATEST_GPU_DATE_VERSION=20230317-a1c7b0c
MINIO_ADDRESS=minio:9000
PULSAR_ADDRESS=pulsar://pulsar:6650
ETCD_ENDPOINTS=etcd:2379

```

**Comment by jiaoew1991** [comment]
> > > Hi @unfode, this has been fixed, rebase the newest master branch and clear your conan cache should help, clear only arrow cache with: `rm -rf ~/.conan/data/arrow`
> > 
> > 
> > Hi @caesarjuly You can try this solution
> 
> I tried. But this error still exists. I don't have this folder in the container. The latest .env I'm using is:
> 
> ```
> IMAGE_REPO=milvusdb
> IMAGE_ARCH=amd64
> OS_NAME=ubuntu20.04
> DATE_VERSION=20230907-2a755ba
> LATEST_DATE_VERSION=20230907-2a755ba
> GPU_DATE_VERSION=20230822-a64488a
> LATEST_GPU_DATE_VERSION=20230317-a1c7b0c
> MINIO_ADDRESS=minio:9000
> PULSAR_ADDRESS=pulsar://pulsar:6650
> ETCD_ENDPOINTS=etcd:2379
> ```

Are you developing inside a dev container? If so, you need to clean up the /home/milvus/.conan/data/arrow directory.
