### ISSUE TITLE
[Bug]: install_standalone-docker.md etcd  unhealthy v2.3.0

### ISSUE THREAD

**Issue by ZhangErling** [milvus-io/milvus#26692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
Rocky Linux release 9.1 (Blue Onyx)
Docker Compose version v2.20.2
Docker Engine version 23.0.1, build a5ee5b1
https://milvus.io/docs/install_standalone-docker.md  v2.3.0
```

### Current Behavior

容器`etcd`没有安装`curl`命令，导致`etcd`是不健康的，不影响`milvus`使用，但是影响`compose.yml`的`depends_on`指定为`condition: service_healthy`
![image](https://github.com/milvus-io/milvus/assets/45256786/00d52e4e-f326-4435-9a5f-9d5081f17fea)

### Expected Behavior

etcd healthy
或者不检查`etcd`健康状态

### Steps To Reproduce

[Milvus Standalone](https://milvus.io/docs/install_standalone-docker.md)
### 一、Download the YAML file

```shell
wget https://github.com/milvus-io/milvus/releases/download/v2.3.0/milvus-standalone-docker-compose.yml -O docker-compose.yml
```

### 二、Start Milvus

```shell
sudo docker compose up -d
```

### Milvus Log

docker etcd health logs 
[root@localhost milvus]# docker inspect --format "{{json .State.Health }}" milvus-etcd | jq
{
  "Status": "unhealthy",
  "FailingStreak": 45,
  "Log": [
    {
      "Start": "2023-08-29T20:32:07.338255927+08:00",
      "End": "2023-08-29T20:32:07.381501423+08:00",
      "ExitCode": -1,
      "Output": "OCI runtime exec failed: exec failed: unable to start container process: exec: \"curl\": executable file not found in $PATH: unknown"
    },
    {
      "Start": "2023-08-29T20:32:37.38298206+08:00",
      "End": "2023-08-29T20:32:37.421960156+08:00",
      "ExitCode": -1,
      "Output": "OCI runtime exec failed: exec failed: unable to start container process: exec: \"curl\": executable file not found in $PATH: unknown"
    },
    {
      "Start": "2023-08-29T20:33:07.424246833+08:00",
      "End": "2023-08-29T20:33:07.470652528+08:00",
      "ExitCode": -1,
      "Output": "OCI runtime exec failed: exec failed: unable to start container process: exec: \"curl\": executable file not found in $PATH: unknown"
    },
    {
      "Start": "2023-08-29T20:33:37.47285436+08:00",
      "End": "2023-08-29T20:33:37.518846991+08:00",
      "ExitCode": -1,
      "Output": "OCI runtime exec failed: exec failed: unable to start container process: exec: \"curl\": executable file not found in $PATH: unknown"
    },
    {
      "Start": "2023-08-29T20:34:07.520981273+08:00",
      "End": "2023-08-29T20:34:07.560787134+08:00",
      "ExitCode": -1,
      "Output": "OCI runtime exec failed: exec failed: unable to start container process: exec: \"curl\": executable file not found in $PATH: unknown"
    }
  ]
}

**Comment by piers-walter-ibm** [comment]
I found that changing the healthcheck in the docker-compose file for etcd from `test: ["CMD", "curl", "-f", "http://localhost:2379/health"]` to `test: ["CMD", "etcdctl", "endpoint", "health"]` should resolve this
