### ISSUE TITLE
[Bug]: FutureTimeoutError

### ISSUE THREAD

**Issue by VjDharnish** [milvus-io/milvus#26691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:  2.3.0
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.2.0
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 16GB
- GPU: 
- Others:
```

### Current Behavior

FutureTimeoutError                        Traceback (most recent call last)
File [/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py:131](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py:131), in GrpcHandler._wait_for_channel_ready(self, timeout)
    130 try:
--> 131     grpc.channel_ready_future(self._channel).result(timeout=timeout)
    132     self._setup_identifier_interceptor(self._user)

File [/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/grpc/_utilities.py:151](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/grpc/_utilities.py:151), in _ChannelReadyFuture.result(self, timeout)
    150 def result(self, timeout: Optional[float] = None) -> None:
--> 151     self._block(timeout)

File [/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/grpc/_utilities.py:97](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/grpc/_utilities.py:97), in _ChannelReadyFuture._block(self, timeout)
     96 if remaining < 0:
---> 97     raise grpc.FutureTimeoutError()
     98 else:

FutureTimeoutError: 

The above exception was the direct cause of the following exception:

**Comment by yanliang567** [comment]
@VjDharnish could you please provide more info such as reproduce code snippet? also you'd better use pymilvus 2.3.0 with milvus v2.3.0/

/assign @VjDharnish 
/unassign
