### ISSUE TITLE
with docker on windows has a problem config file not exits: ../conf/server_config file.yaml  but i am sure the file exist   , i am in /c/milvus/conf dir

### ISSUE THREAD

**Issue by dotsonliu** [milvus-io/milvus#2670]
**Describe the bug**

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by JinHai-CN** [comment]
Please follow: https://milvus.io/docs/v0.10.0/guides/get_started/install_milvus/cpu_milvus_docker.md#Install-Milvus-on-Windows to start Milvus on Windows.

**Comment by dotsonliu** [comment]
i follow https://milvus.io/docs/v0.10.0/guides/get_started/install_milvus/cpu_milvus_docker.md#Install-Milvus-on-Windows


but  has the same problem,


Welcome to use Milvus!
Milvus Release version: v0.10.0, built at 2020-06-15 14:51.51, with OpenBLAS library.
You are using Milvus CPU edition
Last commit id: 5f3c0052478a08d07d68c5dc1aab57a42293f430

Loading configuration from: ../conf/server_config.yaml
Config file not exist: ../conf/server_config.yaml
ERROR: Milvus server fail to load config file
Config file not exist: ../conf/server_config.yaml
Milvus server exit...

how to resolve it???

**Comment by JinHai-CN** [comment]
We do lots of testing on Windows. Due to lots of compatible issues, Milvus won't support Windows officially.
