### ISSUE TITLE
[Bug]: failed to load partitions, but it has not been loaded before

### ISSUE THREAD

**Issue by darkerin** [milvus-io/milvus#26700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.11, v2.2.12
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.8
- OS(Ubuntu or CentOS): ubuntu 18.04
- CPU/Memory: 4C/32G
- GPU: 
- Others:
```

### Current Behavior

I have a collection with a default partition called "_default" and a partition I created.  

I released the collection first, and when I wanted to load the two partitions separately, an error was reported when loading the second one:

exception msg:

```bash
pymilvus.exceptions.MilvusException: <MilvusException: (code=5, message=failed to load partitions, err=some partitions [443520182994056563] of collection 443520182994056562 has been loaded into QueryNode, please release partitions firstly[LoadParameterMismatched])>
```

first try, raise exception in line 3:
```
collection = Collection("xxx")
collection.load(partition_names=["_default"])
collection.load(partition_names=["test_part"])
```

another way of writing, raise exception in line 5:
```
collection = Collection("xxx")
partition1 = Partition(collection, "_default")
partition2 = Partition(collection, "test_part")
partition1.load()
partition2.load()
```

**Comment by yanliang567** [comment]
for now this is by design on milvus 2.2.x, please try v2.3.0, which supports load partitions cascading @darkerin 
/unassign

**Comment by xiaofan-luan** [comment]
you need to release collection before reload partitions
