### ISSUE TITLE
milvus-standalone exited with code 134

### ISSUE THREAD

**Issue by stoneLee81** [milvus-io/milvus#26717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.0
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): centOS
- CPU/Memory: 
- GPU: /
- Others:
```

### Current Behavior

start milvus service failed

### Steps To Reproduce

```markdown
standalone mode to start, steps:
1 wget https://github.com/milvus-io/milvus/releases/download/v2.3.0/milvus-standalone-docker-compose.yml -O docker-compose.yml download yml file
2 sudo docker compose up start milvus service
3 error occurs
```

### Milvus Log

[error.log](https://github.com/milvus-io/milvus/files/12473516/error.log)

**Comment by xiaofan-luan** [comment]
milvus-standalone  | [2023/08/30 08:27:56.877 +00:00] [WARN] [segments/cgo_util.go:94] ["get local used size failed, segcore error: UnexpectedError: Error:DirExist:Operation not permitted\n"]
milvus-standalone  | [2023/08/30 08:27:56.877 +00:00] [WARN] [querynodev2/server.go:263] ["get local used size failed"] [error="UnexpectedError: Error:DirExist:Operation not permitted"]

**Comment by xiaofan-luan** [comment]
Seems that local disk has no permission

**Comment by stoneLee81** [comment]
I used root to create the folder and execute it, and the folder have right to read and write.

> [root@VM-1-13-centos milvus-2.3.0]# ls -lh
> total 8.0K
> -rwxrwxrwx 1 root root 1.7K Aug 23 23:36 docker-compose.yml
> drwxr-xr-x 5 root root 4.0K Aug 31 10:10 volumes

you pasted the error is Error:DirExist:Operation not permitted, which folder is it?
@xiaofan-luan

**Comment by LoveEachDay** [comment]
The directory should be: `/var/lib/milvus/data`.

**Comment by stoneLee81** [comment]
it's docker created in container path, right? that should no right permission, it's created by docker.

**Comment by 999wwx** [comment]
> it's docker created in container path, right? that should no right permission, it's created by docker. @LoveEachDay

Have you solved this problem? I also encountered the same problem

**Comment by wyfeng001** [comment]
@999wwx Hello， can u share more information on this?  such as all your operations between the first time u download the compose file and the error occur.    Did you meet this problem when u run docker-compose up the first time?

**Comment by 999wwx** [comment]
> @999wwx Hello， can u share more information on this? such as all your operations between the first time u download the compose file and the error occur. Did you meet this problem when u run docker-compose up the first time?

After downloading the Docker Compose file, I only changed the image name to the company intranet image source name. The Minio and ETCD versions have been validated with version 2.2.9 and are not problematic.
Sorry, due to company information security requirements, I am unable to upload the Docker Compose file.

**Comment by freefoxcm** [comment]
I also encountered the same problem. Did you solve it?

**Comment by freefoxcm** [comment]
I solved this problem, referring to it.
https://github.com/milvus-io/milvus/issues/27028

**Comment by xiaofan-luan** [comment]
> I solved this problem, referring to it. #27028

Nice，thanks for the feedback!

**Comment by stoneLee81** [comment]
> I solved this problem, referring to it. #27028

add this part to docker_composer.xml file, in services->etcd part?

security_opt:
      - seccomp:unconfined

**Comment by freefoxcm** [comment]
> > I solved this problem, referring to it. #27028
> 
> add this part to docker_composer.xml file, in services->etcd part?
> 
> security_opt: - seccomp:unconfined

no, add to milvus part

**Comment by stoneLee81** [comment]
> > > I solved this problem, referring to it. #27028
> > 
> > 
> > add this part to docker_composer.xml file, in services->etcd part?
> > security_opt: - seccomp:unconfined
> 
> no, add to milvus part

it works. thanks.
