### ISSUE TITLE
[Bug]: Importing data into a collection with 10 shards and 6 partitions fails, and the error keeps reporting: "channel not found incurrent dataNode. "

### ISSUE THREAD

**Issue by lbj1110** [milvus-io/milvus#26719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.12
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):  kafka  
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 128c/2T
- GPU: 
- Others:
```

### Current Behavior

Importing data into a collection with 10 shards and 6 partitions fails, and the error keeps reporting: "channel not found incurrent dataNode. "Resource allocation in the current import stage: 8 dataNodes, each memory allocation of 64G

### Expected Behavior

insert success

### Steps To Reproduce

```markdown
1. The milvus cluster environment is deployed for k8s, version 2.2.12, dataNode nodes are 8; 2. Import 1 billion 512 dimensional data files to minio; 
3. Call the API interface to import files to milvus; 
4. During the import period, it will be interrupted until the import reaches about 400 million, and the import has been failing, and it is currently impossible to import at all;
```

### Milvus Log

[datanode.log](https://github.com/milvus-io/milvus/files/12473798/datanode.log)

**Comment by yanliang567** [comment]
/assign @yhmo 
could you please help on this issue?

/unassign

**Comment by xiaofan-luan** [comment]
@lbj1110 
could you offer datacoord log?

**Comment by xiaofan-luan** [comment]
@yanliang567 
I think we should also test bulkinsert on multiple datanode, both correctness and performance

**Comment by lbj1110** [comment]
[datacoord.log](https://github.com/milvus-io/milvus/files/12481447/datacoord.log)

**Comment by lbj1110** [comment]
Would using insert be better in terms of stability than bulkinsert? For example, there will be no frequent interruptions

**Comment by lbj1110** [comment]
@xiaofan-luan 
Can you give me some advice? Now the development progress has stopped

**Comment by yhmo** [comment]
@lbj1110 
Might be a bug of datacoord, this error indicates some segments have been sent to the incorrect data node to flush.
In the current stage, use the insert api instead.

**Comment by xiaofan-luan** [comment]
> @lbj1110 Might be a bug of datacoord, this error indicates some segments have been sent to the incorrect data node to flush. In the current stage, use the insert api instead.

？？ any reason or fix?

**Comment by xiaofan-luan** [comment]
/assign @bigsheeper 
could you help on this?

**Comment by bigsheeper** [comment]
working on it

**Comment by bigsheeper** [comment]
```
[2023/08/31 01:04:52.539 +00:00] [WARN] [datacoord/channel_manager.go:628] ["datanode watch channel failed or timeout, will release"] [nodeID=177] [channel=by-dev-rootcoord-dml_15_443751649435949191v1]
```

Channel watch failed at DataNode.  @lbj1110 Can you offer the latest datanode log? It's even better if log is from  *[2023/08/31 00:53:48.642 +00:00]* to *[2023/08/31 01:32:59.074 +00:00]*.
