### ISSUE TITLE
[Bug]: miss to handle error

### ISSUE THREAD

**Issue by smellthemoon** [milvus-io/milvus#26711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

<img width="821" alt="1" src="https://github.com/milvus-io/milvus/assets/64083300/f5e11724-9b29-45de-965c-05f174d049f1">

**Comment by xiaofan-luan** [comment]
good catch!
