### ISSUE TITLE
win2019 server docker EE 19.03.5出现disk I/O error

### ISSUE THREAD

**Issue by ccbay** [milvus-io/milvus#2672]
**Describe the bug**
milvus0.10启动出现错误

**Environment details**
- 至强2680v2
- Method of installation (Docker, or from source)
- v0.10
- 0.5

**Screenshots**
Loading configuration from: ../conf/server_config.yaml
WARNNING: You are using SQLite as the meta data management, which can't be used in production. Please change it to MySQL!
Supported CPU instruction sets: sse4_2
FAISS hook SSE42
Error: failed to open database: disk I/O error: disk I/O error. Possible reason: out of storage, meta schema is damaged or created by in-compatible Milvus version.
/var/lib/milvus/docker-entrypoint.sh: line 7:     6 User defined signal 1   ./start_server.sh
**Additional context**

**Comment by ccbay** [comment]
改用mysql,新增向量时出现错误
错误信息：Error init mmap: Invalid argument
Error, unmapping memory: Invalid argument
Error, Could not create bitmap with file
Milvus server is going to shutdown ...

重新启动milvus,错误提示
Error: failed to open database: Can't construct MySQL connection. Possible reason: out of storage, meta schema is damaged or created by in-compatible Milvus version.
/var/lib/milvus/docker-entrypoint.sh: line 7:     7 User defined signal 1   ./start_server.sh

**Comment by tinkerlin** [comment]
- Can you paste the command you run milvus docker?

- Does milvus data folder mount on host system?

**Comment by ccbay** [comment]
就是按照官方的命令运行的，数据目录加载了

**Comment by ccbay** [comment]
方便的话可以加微信远程操作

**Comment by yhmo** [comment]
The two error messages are thrown from /milvus/core/thirdparty/dablooms/dablooms.cpp (bloom-filter)
```
Error init mmap: Invalid argument
Error, unmapping memory: Invalid argument
```
A possible reason is : code is running inside a VirtualBox VM, and the file to mmap() is in a shared directory on host machine. The VirtualBox virtual filesystem apparently doesn’t implement mmap() with the MAP_SHARED.

mmap() is system api, it seems win server 2019 has different declaration to linux system. Current source code could not compatible with win server 2019.
