### ISSUE TITLE
[Bug]: After setting the permissions, the user cannot see the collection created by himself

### ISSUE THREAD

**Issue by weimingdiit** [milvus-io/milvus#26729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
attu:v2.2.3
Milvus server 2.2.10
Pymilvus version: 2.2.1
```

### Current Behavior

step1:create a user testUser
step2:create a role testRole
step3:create a collection testCollection
step4:  
role.add_user("testUser")
role.grant("Collection", "testCollection", "GetStatistics")
step5:
The collection created by testUser  cannot be seen on attu

**Comment by weimingdiit** [comment]
> which user are used to login into attu?

login attu with `testUser`

**Comment by weimingdiit** [comment]
What is the concept of `Global`  in RBAC ？

https://milvus.io/docs/v2.2.x/users_and_roles.md

**Comment by SimFG** [comment]
@weimingdiit This is caused the lack of permissions, because the attu uses some other privileges to show the collection info.
you can try to grant all privileges about the collection, like:
```python
role.grant("Collection", "testCollection", "*")
```

**Comment by weimingdiit** [comment]
> @weimingdiit This is caused the lack of permissions, because the attu uses some other privileges to show the collection info. you can try to grant all privileges about the collection, like:
> 
> ```python
> role.grant("Collection", "testCollection", "*")
> ```

when i use 
role.revoke("Collection", "testCollection", "GetStatistics")
role.grant("Collection", "testCollection", "*")
I will not see any collection, including my own creation on attu

**Comment by SimFG** [comment]
@weimingdiit Do you have other collections excluding the `testCollection `

**Comment by weimingdiit** [comment]
> testCollection

Yes, there are many collections,

//no collection i can see
role.grant("Collection", "testCollection", "GetStatistics")

// all collection i can see ，include not created  by myself
role.grant("Collection", "*", "GetStatistics")

**Comment by SimFG** [comment]
@weimingdiit thanks your feedbac. The reason for this part is that rbac does not currently support partial results based on privileges, and attu will query all collection data in this case. This part will be optimized later

**Comment by weimingdiit** [comment]
> thanks your feedback. The reason for this part is that rbac does not currently support partial results based on privileges, and attu will query all collection data in this case. This part will be optimized later

@SimFG Thanks for you
