### ISSUE TITLE
[Bug]: It takes much time and memory to query iterator with output vector field

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#26727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230828-bc6b376c
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):   pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.0
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

It takes much time and memory to query iterator with output vector field.

1. query 10000 data, output vector:
It takes about 3.5474s

2. query iterator, batch_size=10000, output vector, concurrency number=1
It takes about 4.4705s per page.
memory usage: 960M
https://grafana-4am.zilliz.cc/d/6581e46e4e5c7ba40a07646395ef7b23/kubernetes-compute-resources-pod?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=qa&var-pod=fouramf-nico-qjkkq-3968153518&from=1693389679613&to=1693390531101

3. query iterator, batch_size=10000, output vector, concurrency number=5
It takes about 16.7294s per page.
memory usage: 2.14G 
https://grafana-4am.zilliz.cc/d/6581e46e4e5c7ba40a07646395ef7b23/kubernetes-compute-resources-pod?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=qa&var-pod=fouramf-nico-5s9dp-1025212363&from=1693392121801&to=1693392719360

### Expected Behavior

take less memory and time

**Comment by MrPresent-Han** [comment]
“query 10000 data, output vector:It takes about 3.5474s”
how much memory does 10000 data cost? is there an overall estimation?

**Comment by MrPresent-Han** [comment]
query 10000 takes 3.5474s
conc=1_perpage takes 4.4s
conc=5_perpage takes 16.7s
it seems that the latency increased linearly

**Comment by xiaofan-luan** [comment]
@NicoYuan1986 
Can you give details about your schema and test code?
