### ISSUE TITLE
[Bug]: etcd healthcheck is broken

### ISSUE THREAD

**Issue by ixomaxip** [milvus-io/milvus#26733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.3.0
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Etcd container unhealthy every time because of absence curl in etcd image.

### Expected Behavior

etcd container helathcheck must be healthy.

### Steps To Reproduce

Run milvus standlone with all sidecars from docker-compose https://github.com/milvus-io/milvus/blob/master/deployments/docker/standalone/docker-compose.yml

**Comment by piers-walter-ibm** [comment]
I found that changing the healthcheck in the docker-compose file for etcd from `test: ["CMD", "curl", "-f", "http://localhost:2379/health"]` to `test: ["CMD", "etcdctl", "endpoint", "health"]` should resolve this. The issue is the curl command isn't available on the etcd image being used
