### ISSUE TITLE
[Feature]: Can you recover Superstructure and Substructure metrics?

### ISSUE THREAD

**Issue by jooewood** [milvus-io/milvus#26751]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.
When I try to use previous verion, but it alwasy failed during installation. like:
![image](https://github.com/milvus-io/milvus/assets/93376510/6db51ee5-7a2c-4c65-9a1e-746a50692a1a)
Superstructure and Substructure metrics are very useful in drug discovery, can you recover the two metrics in the future?

### Describe the solution you'd like.

Superstructure and Substructure metrics are very useful in drug discovery, can you keep these two metrics?

**Comment by liliu-z** [comment]
Let's add it back in 2.3.1

**Comment by cydrain** [comment]
metric types TANIMOTO/SUPERSTRUCTURE/SUBSTRUCTURE are disable in PR #25708,
I'll add SUPERSTRUCTURE/SUBSTRUCTURE back

**Comment by cydrain** [comment]
Hi @NicoYuan1986 ,
please confirm metric type SUBSTRUCTURE/SUPERSTRUCTURE is ok now, and close this issue.

**Comment by NicoYuan1986** [comment]
Metric type SUBSTRUCTURE/SUPERSTRUCTURE is ok now.
I have add test case test_create_binary_index_all_metrics, and it works well in nightly test.
So close the issue now. latest version: master-20231007-cfe475a2
