### ISSUE TITLE
[Enhancement]: Remove save bin log call

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#26758]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Now, datanode flush relies on datacoord alive.
This brings complexity and also error prone, especially on the use case of rolling upgrade.

I'd like to suggest to remove save bin log path, and datanode directly operate on txnkv.

The side effect is datacoord never cache segment checkpoint info and file path anymore. This may have some side effect on datacoord performance

**Comment by congqixia** [comment]
/reopen
still WIP

**Comment by congqixia** [comment]
/reopen
still WIP
