### ISSUE TITLE
[Bug]:  list_collections () can't get connection when not set connection alias to default

### ISSUE THREAD

**Issue by yengogo** [milvus-io/milvus#26755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.10
- Deployment mode(standalone or cluster):standalone 
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.3.0
- OS(Ubuntu or CentOS): Ubuntu
```

### Current Behavior

Hi I am confused about milvus connection,
when I set connection alias to 'test', and called the api list_collections(), it showed ConnectionNotExistException,
however set alias to "defalut" ,api could work . 
``` 
connections.connect(
          host=host,
          port=port,
          user=username,
          password=passwd,
          alias='test'
                       )
print(utility.list_collections())
```
Traceback :pymilvus.exceptions.ConnectionNotExistException: <ConnectionNotExistException: (code=1, message=should create connect first.)>

How do use list_collections() or  other  **utility functions** by used  other alias of connection?

**Comment by yanliang567** [comment]
@yengogo as you are connected with connection 'test', so you have to specify the connection when calling list collection like this:
`utility.list_collections(using='test')`
