### ISSUE TITLE
[Bug]: unable to load collection with more than 128 partitions

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#26762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

with the etcd tx limit, Milvus can't load collection with more than 128 partitions

**Comment by yanliang567** [comment]
/assign @yah01  @binbinlv 
@binbinlv lets add the multiple partition tests back.

**Comment by binbinlv** [comment]
> /assign @yah01 @binbinlv @binbinlv lets add the multiple partition tests back.

OK

**Comment by binbinlv** [comment]
@NicoYuan1986  is working on this.
