### ISSUE TITLE
[Bug]: Increasing memory continuously and reboot of datanode and datacoord

### ISSUE THREAD

**Issue by quanqigu** [milvus-io/milvus#26764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.12
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.12
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I am doing some testing on creating collection.
I created about 1000 collections **in cocurrent**.
Each collection has 1 default partition and 1 default shard.
The scheam has 3 columns as following code. The index type is FLAT and metric type is IP.
```
        field1 = FieldSchema(name="embed_id", dtype=DataType.VARCHAR, is_primary=True, auto_id=False,
                             max_length=100)
        field2 = FieldSchema(name="embed_vector", dtype=DataType.FLOAT_VECTOR, descrition="feature vector",
                             dim=512)
        field3 = FieldSchema(name="embed_url", dtype=DataType.VARCHAR, descrition="url", max_length=255)

default_index = {"index_type": "FLAT", "metric_type": "IP", "params": {}}
```
When creating collection, I also created index and loaded this collection into memory. 

But when creating 1000 collection continuously without inserting any data, the memory is increasing continuously up to 12G of datanode and datacoord until it reboot.
After reboot it still increasing memory to 12G until reboot.

The operation of creating collection was stopped at 10:05, but memory and cpu is not stoped.

![image](https://github.com/milvus-io/milvus/assets/80673452/fcae950b-00d3-41a5-8d92-14b17cfb3424)

### Expected Behavior

When creating collections in concurrent, the memory should behave normal.

### Steps To Reproduce

```markdown
1. Create collection like code above **in concurrent** with 2 qps.
2. Observer memory.
```

### Milvus Log

[milvus-datanode-bc9689449-sm7zq_datanode.log](https://github.com/milvus-io/milvus/files/12483506/milvus-datanode-bc9689449-sm7zq_datanode.log)
[milvus-datacoord-84597bc69c-l4lv8_datacoord.log](https://github.com/milvus-io/milvus/files/12483510/milvus-datacoord-84597bc69c-l4lv8_datacoord.log)

**Comment by quanqigu** [comment]
This is our create collection code:
```
        time_s1 = time.time()
        field1 = FieldSchema(name="embed_id", dtype=DataType.VARCHAR, is_primary=True, auto_id=False,
                             max_length=100)
        field2 = FieldSchema(name="embed_vector", dtype=DataType.FLOAT_VECTOR, descrition="feature vector",
                             dim=512)
        field3 = FieldSchema(name="embed_url", dtype=DataType.VARCHAR, descrition="s3 url", max_length=255)
        schema = CollectionSchema(fields=[field1, field2, field3], description="feature collection")
        self.collection = Collection(name=collection_name, schema=schema)
        time_s2 = time.time()
        logger.info(f"create collection cost:{(time_s2 - time_s1):.3f}s")
        # create index
        default_index = {"index_type": "FLAT", "metric_type": "IP", "params": {}}
        status = self.collection.create_index(field_name="embed_vector", index_params=default_index, timeout=self.timeout)
        time_s3 = time.time()
        logger.info(f"create index cost:{(time_s3 - time_s2):.3f}s")
        if not status.code:
            logger.info(
                f"Successfully create index in collection:{collection_name} with param:{default_index}")
        self.collection.load(timeout=self.timeout)
        logger.info(f"load collection cost:{(time.time() - time_s3):.3f}s")
        logger.info(f"Create Milvus collection success: {collection_name}")
```

**Comment by xiaofan-luan** [comment]
1000 collections might be too much for milvus right now.
We are working on optimizing it but so far I think Milvus 2.2 can not handle that much collections

**Comment by yanliang567** [comment]
/assign @sunby 
I am trying to reproduce this in house, not for now no luck.

/unassign

**Comment by quanqigu** [comment]
@xiaofan-luan acutally, we have more than 10k+ collections. maybe we need rethink about collection, maybe we can use several collections with some partitions to support our requirement. If I use 3000+ partitions in a collection, is there any performance issue?

**Comment by quanqigu** [comment]
@yanliang567 I also tried with v2.3.0, creating 1000 collections in one thread continuously. After creating 500 collections, it will report timeout about loading collections. I have set timeout 10s when calling `self.collection.load(timeout=10)`.

**Comment by yanliang567** [comment]
@quanqigu did you try partition key for your scenarios? I think that could be a good option for you. https://milvus.io/docs/partition_key.md#Partition-Key

**Comment by quanqigu** [comment]
@yanliang567 yeah, looks that is a good option. I am trying, thanks very much.
