### ISSUE TITLE
[Enhancement]: Decouple segment sync/flush & compaction

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#26772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Decouple segment sync/flush & compaction

### Why is this needed?

Make `sealed segment` actually sealed and remove injection during compaction

**Comment by xiaofan-luan** [comment]
Any designed documets attached?

**Comment by congqixia** [comment]
See #27349

**Comment by congqixia** [comment]
WIP
/reopen

**Comment by congqixia** [comment]
closing this and remove to #27349
