### ISSUE TITLE
[Bug]:  drop index but GPU does not free up memory

### ISSUE THREAD

**Issue by lmyyao** [milvus-io/milvus#26774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvus2.3.0 GPU
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: T4
- Others:
```

### Current Behavior

when i release a collection and drop the gpu index. After a long period of time, the GPU still does not release memory
<img width="623" alt="截屏2023-08-31 17 00 05" src="https://github.com/milvus-io/milvus/assets/6326405/7bafe0ed-2330-407d-9aa7-a3ea15f86a40">

**Comment by liliu-z** [comment]
/assign @Presburger

Do we reclaim the GPU memory right after releasing?

**Comment by Presburger** [comment]
@lmyyao hi,  we use gpu memory pool, so milvus will hold gpu memory resource all time.

**Comment by lmyyao** [comment]
@Presburger Got it。 2.3.0 暂是仅支持单卡，GPU多卡大概什么时间支持？

**Comment by yanliang567** [comment]
> @Presburger Got it。 2.3.0 暂是仅支持单卡，GPU多卡大概什么时间支持？

it is in the roadmap, and it could be supported in 2023 if everything goes well.

**Comment by yanliang567** [comment]
> @Presburger Got it。 2.3.0 暂是仅支持单卡，GPU多卡大概什么时间支持？

it is in the roadmap, and it could be supported in 2023 if everything goes well.

**Comment by Presburger** [comment]
> @Presburger Got it。 2.3.0 暂是仅支持单卡，GPU多卡大概什么时间支持？

under develop, maybe next version.
