### ISSUE TITLE
[Bug]: index_name in QuerySegmentInfo is always empty

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus#26782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.x - 2.3.x
- Deployment mode(standalone or cluster): standalone
```

### Current Behavior

index_name in `GetQuerySegmentInfoResponse` is always an empty string

```
{
    "data": {
        "infos": [
            {
                "nodeIds": [
                    "1"
                ],
                "segmentID": "443860616207674194",
                "collectionID": "443860616207674071",
                "partitionID": "443860616207674072",
                "mem_size": "0",
                "num_rows": "100",
                "index_name": "",
                "indexID": "0",
                "nodeID": "0",
                "state": "Sealed"
            }
        ],
        "status": {
            "error_code": "Success",
            "reason": "",
            "code": 0
        }
    },
    "statusCode": 200
}
```

### Expected Behavior

it should return real index name

![image](https://github.com/milvus-io/milvus/assets/185051/2209638e-198a-4dfc-8eb9-e6993e6ba78e)
![image](https://github.com/milvus-io/milvus/assets/185051/d47ccb88-e295-47cf-8f62-9f30433179a4)

**Comment by yanliang567** [comment]
@shanghaikid please help to verify it
/unassign

**Comment by shanghaikid** [comment]
verified on `master-20230913-2ed13ba6`.
