### ISSUE TITLE
[Bug]: trace not check valid in querynode using it.

### ISSUE THREAD

**Issue by zhagnlu** [milvus-io/milvus#26789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

when user not set trace exporter,  querynode  using this tracer and not check trace id valid or not. causing querynode coredump
core code:
![image](https://github.com/milvus-io/milvus/assets/11935707/7924d482-5510-4516-9ba6-47c178c125d2)
not check valid and convert null value to uint8_t*.

**Comment by yah01** [comment]
same as #26754
