### ISSUE TITLE
build from source error without any logs, how can I find which step caused the issue?

### ISSUE THREAD

**Issue by intothephone** [milvus-io/milvus#26798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.8
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.0.0rc2
- OS(Ubuntu or CentOS): Ubuntu 20.04
- CPU/Memory: Intel(R) Xeon(R) Platinum 8255C/43G
- GPU: RTX 3090(24GB)
- Others: cmake 3.26.5, go 1.18.3, gcc 9.4.0
```

### Current Behavior

everything is ok, but in the end following output:

make[4]: Leaving directory '/root/milvus/cmake_build/3rdparty_download/aws-sdk-subbuild/src/aws_sdk_s3_ep'
[ 70%] Completed 'aws_sdk_s3_ep'
make[3]: Leaving directory '/root/milvus/cmake_build'
[ 70%] Built target aws_sdk_s3_ep
make[2]: Leaving directory '/root/milvus/cmake_build'
make[1]: *** [Makefile:156: all] Error 2
make[1]: Leaving directory '/root/milvus/cmake_build'
make: *** [Makefile:140: build-cpp] Error 1

### Expected Behavior

should have the bin directory

### Steps To Reproduce

```markdown
1. cloned v2.2.8 source code from github
2. scripts/install_deps.sh
3. make
```

**Comment by intothephone** [comment]
Found the root cause: xsimd, after installing this package, the build could continue without any issues.

**Comment by weimingdiit** [comment]
@intothephone   Can you show your environmental information? I encountered the same problem，thanks

**Comment by xiaofan-luan** [comment]
> @intothephone Can you show your environmental information? I encountered the same problem，thanks

did you runt  ./scripts/install_deps.sh?
