### ISSUE TITLE
[Enhancement]: Need API to show compact/flush task list

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus#26805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

In attu, user should be able to do compaction/flush task, but there is no way to know is there any task is doing the same thing. 

I hope this api, user can get a list of these task, for each task, it should return
- compaction/flush plan id
- target collection
- state
- created time
- finished time?

**Comment by xiaofan-luan** [comment]
/assign @jaime0815 
please help on it

**Comment by xiaofan-luan** [comment]
/assign @jaime0815 
could you help on this?
