### ISSUE TITLE
[Bug]: It cannot correctly calculate the length of Chinese strings 不能正确计算中文字符串长度

### ISSUE THREAD

**Issue by Pickupppp** [milvus-io/milvus#26806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.0
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.3.0
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 128GB
- GPU: RTX4090 24GB x 2
- Others:
```

### Current Behavior

I am currently using Milvus version 2.3.0. I have set a field as VARCHAR and inserted Chinese characters into it. However, I have noticed that when calculating the length, Milvus calculates the length based on the character encoding rather than the actual character count. This often leads to exceeding the maximum length.

### Expected Behavior

For example, when I provide a string like "字" (which contains one Chinese character), I expect its length to be 1, not 3.

### Steps To Reproduce

```markdown
for example:

fields = [
    FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, auto_id=False),
    FieldSchema(name="random", dtype=DataType.VARCHAR, max_length=1),
    FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=8),
]
schema = CollectionSchema(
    fields, "hello_milvus is the simplest demo to introduce the APIs"
)
hello_milvus = Collection("hello_milvus", schema)

entities = [
    [i for i in range(4)],  # field pk
    ["字", "中", "汉", "词"],  # field random
    [[random.random() for _ in range(8)] for _ in range(4)],  # field embeddings
]
insert_result = hello_milvus.insert(entities)

In the code above, I have set the maximum length of the VARCHAR field to 1 and inserted only one Chinese character. However, when running this program, I am encountering the following error:
```python
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=the length (3) of 0th string exceeds max length (1): expected=valid length string, actual=string length exceeds max length: invalid parameter)>
```
```


### Milvus Log

_No response_

### Anything else?

_No response_

**Comment by jiaoew1991** [comment]
> I guess this is by design. @jiaoew1991 could you please help to confirm that? /assign @jiaoew1991 /unassign

Currently, it is by design and calculates the number of bytes.

**Comment by Pickupppp** [comment]
> > I guess this is by design. @jiaoew1991 could you please help to confirm that? /assign @jiaoew1991 /unassign
> 
> Currently, it is by design and calculates the number of bytes.


Sure, but may I ask why this version is designed this way? In fact, I have tested it on version 2.1.3 of Milvus and found that for VARCHAR type fields, the maximum length must be at least one character longer than the character length, or else it will generate an error.
for example:
```python
fields = [
    FieldSchema(name="id", dtype=DataType.INT64, is_primary=True),
    FieldSchema(name="random", dtype=DataType.VARCHAR, max_length=1),
    FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=768),
]
schema = CollectionSchema(
    fields,
    "hello_milvus is the simplest demo to introduce the APIs",
    enable_dynamic_field=True,
)
hello_milvus = Collection("hello_milvus", schema)

entities = [
    [1, 2, 3, 4],  # field pk
    ["中", "中", "中", "中"],  # field random
    [
        np.random.rand(768).tolist(),
        np.random.rand(768).tolist(),
        np.random.rand(768).tolist(),
        np.random.rand(768).tolist(),
    ],  # field embeddings
]
insert_result = hello_milvus.insert(entities)
```
When I run the above code, I encounter the following error:
```python
pymilvus.exceptions.DataNotMatchException: <DataNotMatchException: (code=0, message=The data in the same column must be of the same type.)>
```
However, when I set the maximum length to 2, it ran successfully.
```python
fields = [
    FieldSchema(name="id", dtype=DataType.INT64, is_primary=True),
    FieldSchema(name="random", dtype=DataType.VARCHAR, max_length=2),
    FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=768),
]
schema = CollectionSchema(
    fields,
    "hello_milvus is the simplest demo to introduce the APIs",
    enable_dynamic_field=True,
)
hello_milvus = Collection("hello_milvus", schema)

entities = [
    [1, 2, 3, 4],  # field pk
    ["中", "中", "中", "中"],  # field random
    [
        np.random.rand(768).tolist(),
        np.random.rand(768).tolist(),
        np.random.rand(768).tolist(),
        np.random.rand(768).tolist(),
    ],  # field embeddings
]
insert_result = hello_milvus.insert(entities)
print(insert_result)

(insert count: 4, delete count: 0, upsert count: 0, timestamp: 443961382084804612, success count: 4, err count: 0)
```
Although this error seems quite puzzling, it is clear that in Milvus version 2.1.3, the length of Chinese characters is determined by their character length rather than their encoding length. I hope these two issues can be fixed in the future.

**Comment by xiaofan-luan** [comment]
> > > I guess this is by design. @jiaoew1991 could you please help to confirm that? /assign @jiaoew1991 /unassign
> > 
> > 
> > Currently, it is by design and calculates the number of bytes.
> 
> Sure, but may I ask why this version is designed this way? In fact, I have tested it on version 2.1.3 of Milvus and found that for VARCHAR type fields, the maximum length must be at least one character longer than the character length, or else it will generate an error. for example:
> 
> ```python
> fields = [
>     FieldSchema(name="id", dtype=DataType.INT64, is_primary=True),
>     FieldSchema(name="random", dtype=DataType.VARCHAR, max_length=1),
>     FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=768),
> ]
> schema = CollectionSchema(
>     fields,
>     "hello_milvus is the simplest demo to introduce the APIs",
>     enable_dynamic_field=True,
> )
> hello_milvus = Collection("hello_milvus", schema)
> 
> entities = [
>     [1, 2, 3, 4],  # field pk
>     ["中", "中", "中", "中"],  # field random
>     [
>         np.random.rand(768).tolist(),
>         np.random.rand(768).tolist(),
>         np.random.rand(768).tolist(),
>         np.random.rand(768).tolist(),
>     ],  # field embeddings
> ]
> insert_result = hello_milvus.insert(entities)
> ```
> 
> When I run the above code, I encounter the following error:
> 
> ```python
> pymilvus.exceptions.DataNotMatchException: <DataNotMatchException: (code=0, message=The data in the same column must be of the same type.)>
> ```
> 
> However, when I set the maximum length to 2, it ran successfully.
> 
> ```python
> fields = [
>     FieldSchema(name="id", dtype=DataType.INT64, is_primary=True),
>     FieldSchema(name="random", dtype=DataType.VARCHAR, max_length=2),
>     FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=768),
> ]
> schema = CollectionSchema(
>     fields,
>     "hello_milvus is the simplest demo to introduce the APIs",
>     enable_dynamic_field=True,
> )
> hello_milvus = Collection("hello_milvus", schema)
> 
> entities = [
>     [1, 2, 3, 4],  # field pk
>     ["中", "中", "中", "中"],  # field random
>     [
>         np.random.rand(768).tolist(),
>         np.random.rand(768).tolist(),
>         np.random.rand(768).tolist(),
>         np.random.rand(768).tolist(),
>     ],  # field embeddings
> ]
> insert_result = hello_milvus.insert(entities)
> print(insert_result)
> 
> (insert count: 4, delete count: 0, upsert count: 0, timestamp: 443961382084804612, success count: 4, err count: 0)
> ```
> 
> Although this error seems quite puzzling, it is clear that in Milvus version 2.1.3, the length of Chinese characters is determined by their character length rather than their encoding length. I hope these two issues can be fixed in the future.

Milvus counts length by byte but not by character. And we don't really want to handle the confusing UTF,ASC,UNICODE conversion.  Each chinese character takes more than 1 byte for sure. Based on what character set you are using it might takes different bytes

**Comment by psc0606** [comment]
It is better to use a default charset(eg：utf8) than a misleading semantics(the offcial document: Maximum length of strings allowed to be inserted). More charset can be supported later. But now it is a bug.

**Comment by xiaofan-luan** [comment]
we are thinking of maintain the encoding

**Comment by jiaoew1991** [comment]
tracking the issue here https://github.com/milvus-io/milvus/issues/27652

**Comment by yanliang567** [comment]
okay, i'd close this one if you don't mind.
