### ISSUE TITLE
[Bug]: Milvus 2.3.0 need a much long time for startup success after stop in standalone mode.

### ISSUE THREAD

**Issue by matrixji** [milvus-io/milvus#26815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.0
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq   
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.0
- OS(Ubuntu or CentOS): Ubuntu2004
- CPU/Memory: N/A
- GPU: N/A
- Others:
```

### Current Behavior

I first met this issue when trying to port milvus standalone to milvus-lite.  It could be reproduced by milvus standalone mode (docker-compose)
The milvus could be started at the first time, and then I stop it and start it again, it could not get healthy.

### Steps To Reproduce

```markdown
1. docker-compose up -d
2. run hello_milvus.py -> success
3. docker-compose stop
4. docker-compose start
5. run hello_milvus.py -> connect failed (actually it need wait a long time)

If I remove the volume data and restart the milvus again, then everything go OK again.
```

### Milvus Log

[standalone.log.gz](https://github.com/milvus-io/milvus/files/12506109/standalone.log.gz)

**Comment by matrixji** [comment]
It seems could be reconnected after a long time(about 60s), close it, If I have more info about this issue, will reopen it.

**Comment by matrixji** [comment]
/reopen
change the title

**Comment by matrixji** [comment]
I could find some log in my milvus-lite integration process:
```
./milvus-stdout.log:[2023/09/03 21:30:28.389 +08:00] [WARN] [grpcclient/client.go:390] ["Server ID mismatch, start to reset connection"] [role=datanode] [error="rpc error: code = Unknown desc = expected=%!s(int64=2), actual=%!s(int64=4): server ID mismatch"]
```

It seems the nodeID/serverID mismatch, after several retries(that's why need to wait for a long time), the Server ID will be updated, then the internal connection will go OK and the milvus server will work fine.

**Comment by xiaofan-luan** [comment]
we'll keep a look on it.
This might be happened on rolling upgrade

/assign @SimFG

**Comment by matrixji** [comment]
> @matrixji it has been improved in the latest master, details: #26795

Great news. 🌷

**Comment by matrixji** [comment]
Now we have tested with v2.3.1 it seems still needs a long time for the 2nd and later startup. I'll try to do some investigations on it later.
