### ISSUE TITLE
[Bug]: COSINE distance result not equal normalized L2

### ISSUE THREAD

**Issue by UrszulaCzerwinska** [milvus-io/milvus#26811]
#### Is there an existing issue for this?
no

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.0
- Deployment mode(standalone or cluster): EKS
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.0
- OS(Ubuntu or CentOS): MacOS/Ubuntu
```

### Current Behavior

According to [litterature ](https://en.wikipedia.org/wiki/Cosine_similarity#Angular_similarity) euclidean distance applied to L2 normalized vectors should be monotonically equal to cosine distance.
In my test in create a collection with random vectors that I index with COSINE and a collection with random vectors (same seed) where I normalize vectors and index with L2.
When using Milvus and comparing both results of serach, I obtain different ranking.
I include code to reproduce. I have put normalized data intentionally to  a different collection to make sure computation is independent.

### Expected Behavior

I expect the returned ids order to be the same for norm L2 indexed and COSINE indexed  for a search of the same vector.

### Steps To Reproduce

```markdown
import random
from pymilvus import CollectionSchema, FieldSchema, DataType, utility, Collection, connections
import numpy as np
HOST = <host>
PORT = <port>

connections.connect(
    alias="default",
    host=HOST,
    port=PORT
)

book_id = FieldSchema(
    name="book_id",
    dtype=DataType.INT64,
    is_primary=True,
)
book_name = FieldSchema(
    name="book_name",
    dtype=DataType.VARCHAR,
    max_length=200,
)
word_count = FieldSchema(
    name="word_count",
    dtype=DataType.INT64,
)
book_intro = FieldSchema(
    name="book_intro",
    dtype=DataType.FLOAT_VECTOR,
    dim=2
)
schema = CollectionSchema(
    fields=[book_id, book_name, word_count, book_intro],
    description="Test book search",
    enable_dynamic_field=True
)


random.seed(4)
data = [
    [i for i in range(2000)],
    [str(i) for i in range(2000)],
    [i for i in range(10000, 12000)],
    [[random.random() for _ in range(2)] for _ in range(2000)]
]
random.seed(4)
data_2 = [
    [i for i in range(2000)],
    [str(i) for i in range(2000)],
    [i for i in range(10000, 12000)],
    [[random.random() for _ in range(2)] for _ in range(2000)]
]
print(data[3][0], data_2[3][0])
norm = [(lambda x: x / np.linalg.norm(x, axis=0))(x) for x in data_2[3] ]
data_2[3] = norm
print(data[3][0], data_2[3][0])


collection_name = "book_cosine"

collection_cosine = Collection(
    name=collection_name,
    schema=schema,
    using='default',
    shards_num=2
)

collection_cosine = Collection("book_cosine")  # Get an existing collection.
mr = collection_cosine.insert(data)

print(mr)

index_params_cosine = {
    "metric_type": "COSINE",
    "index_type": "IVF_FLAT",
    "params": {"nlist": 1024}
}

# Get an existing collection.
collection_cosine.create_index(
    field_name="book_intro",
    index_params=index_params_cosine
)

utility.index_building_progress("book_cosine")
collection_cosine.load()

search_params = {"metric_type": "COSINE", "params": {"nprobe": 10}}
vec = [0.1, 0.2]
results_cosine = collection_cosine.search(
    data=[vec],
    anns_field="book_intro",
    param=search_params,
    limit=100,
    expr=None,
    # set the names of the fields you want to retrieve from the search result.
    output_fields=['book_name'],
    consistency_level="Strong"
)


collection_name = "book_L2"

collection_L2 = Collection(
    name=collection_name,
    schema=schema,
    using='default',
    shards_num=2
)

collection_L2 = Collection("book_L2")  # Get an existing collection.
mr = collection_L2.insert(data_2) # norm data

print(mr)

index_params_l2 = {
    "metric_type": "L2",
    "index_type": "IVF_FLAT",
    "params": {"nlist": 1024}
}

# Get an existing collection.
collection_L2.create_index(
    field_name="book_intro",
    index_params=index_params_l2
)

utility.index_building_progress("book_L2")
collection_L2.load()

search_params = {"metric_type": "L2", "params": {"nprobe": 10}}

vec = [0.1, 0.2]
vec_norm = vec / np.linalg.norm(vec, axis=0)
print(vec_norm)
results_l2 = collection_L2.search(
    data=[vec_norm],
    anns_field="book_intro",
    param=search_params,
    limit=100,
    expr=None,
    output_fields=['book_name'],
    consistency_level="Strong"
)


print("1st query - ids - cosine")
print(results_cosine[0].ids)

print("1st query - distances - cosine")
print(results_cosine[0].distances)

print("1st query - ids - norm l2 ")
print(results_l2[0].ids)

print("1st query  - distances - norm l2")
print(results_l2[0].distances)
assert results_l2[0].ids==results_cosine[0].ids

---
[0.23604808973743452, 0.1031660342307158] [0.23604808973743452, 0.1031660342307158]
[0.23604808973743452, 0.1031660342307158] [0.91630695 0.40047668]
(insert count: 2000, delete count: 0, upsert count: 0, timestamp: 443963064429838337, success count: 2000, err count: 0)
(insert count: 2000, delete count: 0, upsert count: 0, timestamp: 443963064770363395, success count: 2000, err count: 0)
[0.4472136  0.89442719]
1st query - ids - cosine
[1782, 1581, 477, 1119, 1881, 81, 1811, 1901, 558, 1609, 1329, 1718, 393, 737, 750, 1164]
1st query - distances - cosine
[1.3193317651748657, 1.3003243207931519, 1.2985436916351318, 1.2977688312530518, 1.2968133687973022, 1.2945204973220825, 1.2929881811141968, 1.2880606651306152, 1.2858190536499023, 1.2816205024719238, 1.2812448740005493, 1.2798080444335938, 1.2705821990966797, 1.267196774482727, 1.2662878036499023, 1.2643071413040161]
1st query  - ids - norm l2 
[1452, 243, 1473, 1592, 1993, 1507, 1026, 1394, 620, 1771, 1923, 1056, 1572, 1838, 1412, 379]
1st query - distances - norm l2
[1.2767828572179951e-08, 4.48934088126407e-07, 7.528682317570201e-07, 1.24749578844785e-06, 1.4332275668493821e-06, 2.6215270736429375e-06, 3.5826562907459447e-06, 4.226939381624106e-06, 5.427424184745178e-06, 1.0056272003566846e-05, 1.2473562492232304e-05, 2.5216813810402527e-05, 5.8861660363618284e-05, 7.413388084387407e-05, 8.314756269101053e-05, 9.490150114288554e-05]
Traceback (most recent call last):
    assert results_l2[0].ids==results_cosine[0].ids
AssertionError
```

### Anything else?

Using different `limit`values (same for both) I am getting very different results, for low values such as 10, I am getting the same ids order and only 2 matching ids, for limit `30` I am getting 4 ids in the same order, with higher limit, the order does not match. 

I also remarqued cosine > 1 which is something mentioned in a different thread

**Comment by UrszulaCzerwinska** [comment]
sorry input vector for L2 needs to be normalized as well

**Comment by yanliang567** [comment]
@UrszulaCzerwinska  it seems that you inserted 2 different data into the 2 test collections. I think you shall use the same vectors for this test.
 @liliu-z I tthink IP with normalized is same as conise, instead of L2, right?
/assign @liliu-z 
/unassign

**Comment by UrszulaCzerwinska** [comment]
Thank you addressing the issue quickly.

I have inserted exactly the same data, one has normalized vectors using l2 norm as you explained in your tutorials and as litterature recommends. You can see that in the code. I am using the same see for the data and I double check with the print the data is the same.

You are right that normalized IP should give the same scores as cosine. I did not check that here because this  interest me less.

My issue here is that normalized euclidean should give the same order of results (monotonicity) as cosine.
https://en.wikipedia.org/wiki/Cosine_similarity#Angular_similarity

This is not what happens in my example. 


Also, you didn't address the fact that changing 'limit' param in the search I receive very different results (not only number but also order changes).

**Comment by xiaofan-luan** [comment]
> @UrszulaCzerwinska it seems that you inserted 2 different data into the 2 test collections. I think you shall use the same vectors for this test. @liliu-z I tthink IP with normalized is same as conise, instead of L2, right? /assign @liliu-z /unassign

With normalization, IP and L2 both equaled to Cosine.

I thought there are still some bugs, please fix it ASAP and release in 2.3.1

@cydrain @liliu-z @yanliang567

**Comment by liliu-z** [comment]
Yes, the absolute distance can be different for Cosine and  norm-L2, but they should be monotonically equal(actually 2-2*cosine_dis = norm_l2_dis).

It looks absolutely like a big, since the cosine distance should never be bigger than 1. Let’s reproduce it and get back to you ASAP.

@UrszulaCzerwinska

**Comment by UrszulaCzerwinska** [comment]
Yes, exactly what I ment.

**Comment by UrszulaCzerwinska** [comment]
Was this fixed?

**Comment by liliu-z** [comment]
> Was this fixed?

Yes, in latest 2.3.1. Plz take a try and feel free to ping us again if still some problems

**Comment by yanliang567** [comment]
/assign @NicoYuan1986 
please help to verify the fix

**Comment by NicoYuan1986** [comment]
verify fixed. 
version: v2.3.1
