### ISSUE TITLE
[Bug]: incorrect resource calculation for sync set segment resulting longer unavailable time

### ISSUE THREAD

**Issue by MrPresent-Han** [milvus-io/milvus#26813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

In the process of laion1Y test, we found that when scaling milvus querynode from 5 to 3, the unserviceable time was so long, over 45s, which is absolutely unexpected under such circumstances

### Expected Behavior

service keep being available throughout the whole process

### Steps To Reproduce

```markdown
related: https://github.com/milvus-io/milvus/issues/26623
```

### Anything else?

the whole process is as following:
1. scale qn from 5 to 3, resulting node66 and node70 graceful stopping.
2. channelv0 was on node 70
3. qc firstly saw 70 down, so move chv0 from 70 to 66
4. then qc saw 66 down, so move chv0 from 66 to 71
5. on qc, the delegator change was seen timely and correctly, but the new delegator could not see many previous segments on node71 and node72:(segment lack err)

reason: it's expected that the leader observer can rectify the distribution. And the log turned that the mechanism on qc side ran correctly. But sync_set_load_segments request all failed on query nodes side because of 'request limit', and the bug here is that, most of these segments are already loaded and there's no need to calculate the requested resource for them. But current codes just checked the current commitnum and poolside and directly return error, leading to 'false error' for sync_set_load_request.

**Comment by MrPresent-Han** [comment]
[2023/08/30 07:09:06.505 +00:00] [INFO] [segments/segment_loader.go:155] ["start loading..."] [traceID=fc318809ac4019f46350a53b357132df] [collectionID=443707252933697852] [segmentType=Sealed] [segmentNum=10] [afterFilter=0]

afterFilter=0 means that all segments inside the request were already on the node. but the resource judgement failed: 
limit=640: request limit exceeded

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version: master
> - Deployment mode(standalone or cluster):
> - MQ type(rocksmq, pulsar or kafka):    
> - SDK version(e.g. pymilvus v2.0.0rc2):
> - OS(Ubuntu or CentOS): 
> - CPU/Memory: 
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> In the process of laion1Y test, we found that when scaling milvus querynode from 5 to 3, the unserviceable time was so long, over 45s, which is absolutely unexpected under such circumstances
> 
> ### Expected Behavior
> service keep being available throughout the whole process
> 
> ### Steps To Reproduce
> ```
> related: https://github.com/milvus-io/milvus/issues/26623
> ```
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> the whole process is as following:
> 
> 1. scale qn from 5 to 3, resulting node66 and node70 graceful stopping.
> 2. channelv0 was on node 70
> 3. qc firstly saw 70 down, so move chv0 from 70 to 66
> 4. then qc saw 66 down, so move chv0 from 66 to 71
> 5. on qc, the delegator change was seen timely and correctly, but the new delegator could not see many previous segments on node71 and node72:(segment lack err)
> 
> reason: it's expected that the leader observer can rectify the distribution. And the log turned that the mechanism on qc side ran correctly. But sync_set_load_segments request all failed on query nodes side because of 'request limit', and the bug here is that, most of these segments are already loaded and there's no need to calculate the requested resource for them. But current codes just checked the current commitnum and poolside and directly return error, leading to 'false error' for sync_set_load_request.

what do you mean by "request limit"?
is it because out of memory limit due to calulate more resources expected?

**Comment by MrPresent-Han** [comment]
> > ### Is there an existing issue for this?
> > 
> > * [x]   I have searched the existing issues
> > 
> > ### Environment
> > ```
> > - Milvus version: master
> > - Deployment mode(standalone or cluster):
> > - MQ type(rocksmq, pulsar or kafka):    
> > - SDK version(e.g. pymilvus v2.0.0rc2):
> > - OS(Ubuntu or CentOS): 
> > - CPU/Memory: 
> > - GPU: 
> > - Others:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Current Behavior
> > In the process of laion1Y test, we found that when scaling milvus querynode from 5 to 3, the unserviceable time was so long, over 45s, which is absolutely unexpected under such circumstances
> > ### Expected Behavior
> > service keep being available throughout the whole process
> > ### Steps To Reproduce
> > ```
> > related: https://github.com/milvus-io/milvus/issues/26623
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Milvus Log
> > _No response_
> > ### Anything else?
> > the whole process is as following:
> > 
> > 1. scale qn from 5 to 3, resulting node66 and node70 graceful stopping.
> > 2. channelv0 was on node 70
> > 3. qc firstly saw 70 down, so move chv0 from 70 to 66
> > 4. then qc saw 66 down, so move chv0 from 66 to 71
> > 5. on qc, the delegator change was seen timely and correctly, but the new delegator could not see many previous segments on node71 and node72:(segment lack err)
> > 
> > reason: it's expected that the leader observer can rectify the distribution. And the log turned that the mechanism on qc side ran correctly. But sync_set_load_segments request all failed on query nodes side because of 'request limit', and the bug here is that, most of these segments are already loaded and there's no need to calculate the requested resource for them. But current codes just checked the current commitnum and poolside and directly return error, leading to 'false error' for sync_set_load_request.
> 
> what do you mean by "request limit"? is it because out of memory limit due to calulate more resources expected?

No, it's a newly-built mechanism to judge whether the current worker/memory/disk usage and needed resource for new load segments operation can exceed the total resources, the main implementation is in "func (loader *segmentLoader) requestResource"
