### ISSUE TITLE
[Enhancement]: Milvus insert failed for 'message send timeout'

### ISSUE THREAD

**Issue by MrPresent-Han** [milvus-io/milvus#26824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

according to @ThreadDao test towards 1Y data in milvus, in the process of inserting, client failed for MilvusException:
[2023-08-30 17:39:03,516 - ERROR - fouram]: RPC error: [batch_insert], <MilvusException: (code=1, message=message send timeout: Time
outError)>, <Time:{'RPC start': '2023-08-30 17:38:33.377477', 'RPC error': '2023-08-30 17:39:03.516179'}> (decorators.py:126)
[2023-08-30 17:39:03,519 - ERROR - fouram]: (api_response) : <MilvusException: (code=1, message=message send timeout: TimeoutError)>
 (api_request.py:53)
[2023-08-30 17:39:03,519 - ERROR - fouram]: [CheckFunc] insert request check failed, response:<MilvusException: (code=1, message=mes
sage send timeout: TimeoutError)> (func_check.py:52)

### Why is this needed?

to enhance the stability of insertion process

**Comment by MrPresent-Han** [comment]
at this time, pulsar bookie failed for losing connection to pulsar-broker:
17:38:33.184 [bookie-io-1-6] INFO  org.apache.bookkeeper.proto.BookieRequestHandler - Channels disconnected: [id: 0x0b4339b1, L:/10.104.24.199:3181 ! R:/10.104.23.166:54576]

**Comment by MrPresent-Han** [comment]
according to zk log, it shows that this close operation is triggered by request:

17:38:35.977 [pulsar-ordered-OrderedExecutor-5-0-EventThread] INFO  org.apache.pulsar.zookeeper.ZooKeeperSessionWatcher - Received zookeeper notification, eventType=None, eventState=Closed
----------------------------------------------------------------------------------------------------------------------
17:38:36.197 [RequestThrottler] INFO  org.apache.zookeeper.server.ZooKeeperServer - Submitting global closeSession request for session 0x1053b8b1ede001f
17:38:36.090 [RequestThrottler] INFO  org.apache.zookeeper.server.ZooKeeperServer - Submitting global closeSession request for session 0x30536398f330016
17:38:35.741 [RequestThrottler] INFO  org.apache.zookeeper.server.ZooKeeperServer - Submitting global closeSession request for session 0x1053b8b1ede0020

**Comment by MrPresent-Han** [comment]
I don't think this is a commonly-occurred problem and just post infos here in case it reoccur in the future.
look forward to any advices from other classmates

**Comment by ThreadDao** [comment]
@MrPresent-Han @yanliang567 
Oh~ Now it's the "further".
I tried to insert 100m-768dim data twice and encountered this issue every time.
I'm curious about two questions:
1. Is this error all because of pulsar connection?
2. Would it be better to try again after encountering this error on the SDK side? I really don't want to fail midway when inserting a large amount of data?
