### ISSUE TITLE
the enviroment problem

### ISSUE THREAD

**Issue by persuelx** [milvus-io/milvus#2682]
Does the environment support Ubuntu 16.04？

**Comment by JinHai-CN** [comment]
Yes, you can compile or run Milvus in Ubuntu 16.04.

**Comment by persuelx** [comment]
@JinHai-CN  ok，thanku，which version do you use in your programme?

**Comment by JinHai-CN** [comment]
Ubuntu 18.04

**Comment by persuelx** [comment]
@JinHai-CN thank you Ihave  compiled the source code successfully

**Comment by persuelx** [comment]
HI，the cpu version，but i compile the gpu version many problems have occured。


[100%] Linking CXX executable milvus_server
libmilvus_engine.a(KnowhereResource.cpp.o): In function `milvus::engine::KnowhereResource::Initialize()':
KnowhereResource.cpp:(.text+0x619): undefined reference to `knowhere::FaissGpuResourceMgr::GetInstance()'
KnowhereResource.cpp:(.text+0x62d): undefined reference to `knowhere::FaissGpuResourceMgr::InitDevice(long, long, long, long)'
libmilvus_engine.a(KnowhereResource.cpp.o): In function `milvus::engine::KnowhereResource::Finalize()':
KnowhereResource.cpp:(.text+0x6e5): undefined reference to `knowhere::FaissGpuResourceMgr::GetInstance()'
KnowhereResource.cpp:(.text+0x6ed): undefined reference to `knowhere::FaissGpuResourceMgr::Free()'
libmilvus_engine.a(VecImpl.cpp.o): In function `milvus::engine::VecIndexImpl::GetDeviceId()':
VecImpl.cpp:(.text+0x144): undefined reference to `knowhere::GPUIndex::GetGpuDevice()'
libmilvus_engine.a(VecImpl.cpp.o): In function `milvus::engine::VecIndexImpl::CopyToGpu(long const&, std::shared_ptr<knowhere::Cfg> const&)':
VecImpl.cpp:(.text+0x2128): undefined reference to `knowhere::cloner::CopyCpuToGpu(std::shared_ptr<knowhere::VectorIndex> const&, long const&, std::shared_ptr<knowhere::Cfg> const&)'
libmilvus_engine.a(VecImpl.cpp.o): In function `milvus::engine::VecIndexImpl::CopyToCpu(std::shared_ptr<knowhere::Cfg> const&)':

the gpu 2080ti ，cuda10.0，NVIDIA-SMI 410.48         Driver Version: 410.48

**Comment by JinHai-CN** [comment]
Please check the compilation requirements: https://github.com/milvus-io/milvus/blob/master/INSTALL.md#requirements

**Comment by persuelx** [comment]
I just compile according to this step except for the version of the gpu-driver and system。

**Comment by JinHai-CN** [comment]
Yes, the GPU driver is important. I suggest you upgrade it.

As for the other compiling errors. it seems the information you provide is not enough.
