### ISSUE TITLE
[Enhancement]: Optimize MergeInsertData() to remove runtime.memmove overhead

### ISSUE THREAD

**Issue by bjzhjing** [milvus-io/milvus#26838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

I'd like to refactor MergeInsertData() for performance improvement.

### Why is this needed?

Benchmark Milvus with https://github.com/qdrant/vector-db-benchmark and specify the datasets as 'deep-image-96-angular'. Meanwhile, do perf profiling during 'upload + index' stage of vector-db-benchmark and see the following hot spots.

    39.59%--github.com/milvus-io/milvus/internal/storage.MergeInsertData
            |
            |--21.43%--github.com/milvus-io/milvus/internal/storage.MergeFieldData
            |          |
            |          |--17.22%--runtime.memmove
            |                     |
            |                     |--1.53%--asm_exc_page_fault
            |                     ......
            |
            |--18.16%--runtime.memmove
                       |
                       |--1.66%--asm_exc_page_fault
                       ......

To avoid the above overhead, update storage.MergeInsertData() by appending addedBuffer to buffer.buffer, instead of moving buffer.buffer and addedBuffer to a new 'InsertData'.

**Comment by xiaofan-luan** [comment]
@bjzhjing 
Bingo!

Good catch!

Any performance number after the optimization

**Comment by bjzhjing** [comment]
Thanks a bunch for helping review and merging the fix! Yes, I can share the improved ratio, that the 'upload + index' time of vector-db-benchmark is reduced around 60% :-)

**Comment by bjzhjing** [comment]
Let's close it for the fix is merged.
