### ISSUE TITLE
[Bug]: etcd start failed: max entry size limit exceeded

### ISSUE THREAD

**Issue by darkerin** [milvus-io/milvus#26855]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.3.0
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu18.04
- CPU/Memory:  4C32G
- GPU: 
- Others:
```

### Current Behavior

etcd container start faied and output error:

```
{"level":"info","ts":"2023-09-05T11:05:51.158Z","caller":"embed/etcd.go:371","msg":"closing etcd server","name":"default","data-dir":"/etcd","advertise-peer-urls":["http://localhost:2380"],"advertise-client-urls":["http://127.0.0.1:2379"]}
{"level":"info","ts":"2023-09-05T11:05:51.158Z","caller":"embed/etcd.go:373","msg":"closed etcd server","name":"default","data-dir":"/etcd","advertise-peer-urls":["http://localhost:2380"],"advertise-client-urls":["http://127.0.0.1:2379"]}
{"level":"fatal","ts":"2023-09-05T11:05:51.158Z","caller":"etcdmain/etcd.go:204","msg":"discovery failed","error":"wal: max entry size limit exceeded, recBytes: 256, fileSize(64000000) - offset(63999936) - padBytes(0) = entryLimit(64)","stacktrace":"go.etcd.io/etcd/server/v3/etcdmain.startEtcdOrProxyV2\n\t/tmp/etcd-release-3.5.5/etcd/release/etcd/server/etcdmain/etcd.go:204\ngo.etcd.io/etcd/server/v3/etcdmain.Main\n\t/tmp/etcd-release-3.5.5/etcd/release/etcd/server/etcdmain/main.go:40\nmain.main\n\t/tmp/etcd-release-3.5.5/etcd/release/etcd/server/main.go:32\nruntime.main\n\t/usr/local/google/home/siarkowicz/.gvm/gos/go1.16.15/src/runtime/proc.go:225"}
```

### Milvus Log

milvus.log:
[milvus.log](https://github.com/milvus-io/milvus/files/12522710/milvus.log)

etcd
[etcd.log](https://github.com/milvus-io/milvus/files/12522714/etcd.log)

**Comment by xiaofan-luan** [comment]
seems that you need to bring up your etcd cluster first. 

From https://github.com/etcd-io/etcd/issues/14025, this is bug before etcd 3.5.5

But milvus should use etcd 3.5.5

are you sharing the etcd with other service?

**Comment by xiaofan-luan** [comment]
And I don't think milvus could generate a 64M wal entry?

**Comment by yanliang567** [comment]
@darkerin  as comments above, please share more info about how you deploy milvus and any updates for configurations.
/assign @darkerin 
/unassign

**Comment by darkerin** [comment]
@xiaofan-luan @yanliang567 

etcd 3.5.5 container is only provided for milvus use. 

Before this i try to create 500 partitions in a collection, and modified the etcd parameter ETCD_MAX_TXN_OPS
see https://github.com/milvus-io/milvus/issues/26748.

When I shut down the container and tried to start it again it failed

**Comment by xiaofan-luan** [comment]
/assign @yanliang567 
could you try to reproduce this issue on 2.3.x with 4096 partitions?

**Comment by xiaofan-luan** [comment]
let us try to reproduce this issue

**Comment by darkerin** [comment]
> let us try to reproduce this issue

thanks a lot

**Comment by yanliang567** [comment]
i did not reproduce this on latest 2.3.0 image.

**Comment by yhmo** [comment]
Another user encountered this error with standalone(embedded etcd).
There is another issue in etcd says this bug is fixed in etcd v3.5.7
https://github.com/etcd-io/etcd/issues/15090

**Comment by tianshihan818** [comment]
> Another user encountered this error with standalone(embedded etcd). ![etcd](https://private-user-images.githubusercontent.com/2282099/323456389-4980c1e6-7a0c-4fa2-b4c9-d02044a36cf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMjU5NzEsIm5iZiI6MTcxNDAyNTY3MSwicGF0aCI6Ii8yMjgyMDk5LzMyMzQ1NjM4OS00OTgwYzFlNi03YTBjLTRmYTItYjRjOS1kMDIwNDRhMzZjZjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjVUMDYxNDMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmU4MzA3MWZmZjU1MWMyZTBhMGNmNTIwMmIzYjJhMDlkYTJhNWUxNzRlNWEyNGVmMTYwOTliMDZmNjQ0MTA0NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.byppBogMlLkHeoT20mvCwnmlWz1yZZy_pyjlMpLjymc)
> 
> There is another issue in etcd says this bug is fixed in etcd v3.5.7 [etcd-io/etcd#15090](https://github.com/etcd-io/etcd/issues/15090)

Hi! Did milvus support to deploy etcd v3.5.7 now?

**Comment by xiaofan-luan** [comment]
@LoveEachDay

**Comment by AlexeyIvanov8** [comment]
Hi! I have the same issue with etcd 3.5.5-r2 installed from Milvus operator. Up question above:

> Hi! Did milvus support to deploy etcd v3.5.7 now?

**Comment by xiaofan-luan** [comment]
we are upgrading to 3.5.14 or 3.5.15 in the latest releasse

**Comment by Niceies** [comment]
Can directly upgrading the etcd version solve this problem smoothly?

**Comment by xiaofan-luan** [comment]
> Can directly upgrading the etcd version solve this problem smoothly?

Don't think so. Basically this means milvus write a large entry into etcd. After several improvement we didn't see this happens oftens. 

1. you can tune this at etcd side -- etcd --max-request-bytes=6291456
2. Or you may need to figure out why your milvus hit into this issue, why is the key so large and we might need to modify the code

**Comment by Niceies** [comment]
This seems to be a bug in the 3.5.5 version of etcd, not caused by milvus. I have tried to increase the size to 6M, 10M, and 15M, but none of them worked. After updating to version 3.5.9, etcd started normally.

> 另一个用户在使用独立（嵌入式 etcd）时遇到了此错误。 ![etcd](https://github.com/milvus-io/milvus/assets/2282099/4980c1e6-7a0c-4fa2-b4c9-d02044a36cf2)
> 
> etcd 中还有另一个问题，该错误已在 etcd v3.5.7 中修复 [etcd-io/etcd#15090](https://github.com/etcd-io/etcd/issues/15090)
