### ISSUE TITLE
[Bug]: Is it necessary for the disk to be SSD when installing the cluster version?

### ISSUE THREAD

**Issue by zk903956028** [milvus-io/milvus#26853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

[root@devtest3 2.0]# kubectl get pods --all-namespaces
NAMESPACE      NAME                                            READY   STATUS     RESTARTS   AGE
default        my-release-etcd-0                               0/1     Pending    0          4m40s
default        my-release-etcd-1                               0/1     Pending    0          4m40s
default        my-release-etcd-2                               0/1     Pending    0          4m40s
default        my-release-milvus-datacoord-c98b6bffd-7kv94     0/1     Running    1          4m40s
default        my-release-milvus-datanode-79b5bd94cf-7pt9z     0/1     Running    1          4m40s
default        my-release-milvus-indexcoord-7678586d8c-bczn4   1/1     Running    0          4m40s
default        my-release-milvus-indexnode-65c6967bc6-lgfth    0/1     Running    1          4m40s
default        my-release-milvus-proxy-f467759cc-9bw95         0/1     Running    1          4m40s
default        my-release-milvus-querycoord-64b979b88d-95znk   0/1     Running    1          4m40s
default        my-release-milvus-querynode-7f449f676b-7dvbt    0/1     Running    1          4m40s
default        my-release-milvus-rootcoord-5db8b47c5b-m92f5    0/1     Running    1          4m40s
default        my-release-minio-0                              0/1     Pending    0          4m40s
default        my-release-minio-1                              0/1     Pending    0          4m40s
default        my-release-minio-2                              0/1     Pending    0          4m40s
default        my-release-minio-3                              0/1     Pending    0          4m40s
default        my-release-pulsar-bookie-0                      0/1     Pending    0          4m40s
default        my-release-pulsar-bookie-1                      0/1     Pending    0          4m40s
default        my-release-pulsar-bookie-2                      0/1     Pending    0          4m40s
default        my-release-pulsar-bookie-init-wl2ms             0/1     Init:0/1   0          4m40s
default        my-release-pulsar-broker-0                      0/1     Init:0/2   0          4m40s
default        my-release-pulsar-proxy-0                       0/1     Init:0/2   0          4m40s
default        my-release-pulsar-pulsar-init-srdcw             0/1     Init:0/2   0          4m40s
default        my-release-pulsar-recovery-0                    0/1     Init:0/1   0          4m40s
default        my-release-pulsar-zookeeper-0                   0/1     Pending    0          4m40s

### Expected Behavior

the etcd service is running

### Steps To Reproduce

```markdown
no
```

### Milvus Log

                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  5s (x7 over 119s)  default-scheduler  0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.

### Anything else?

no

**Comment by yanliang567** [comment]
for etcd and pulsar bookie services, it requires SSD volumes. If you want to use diskAnn index, querynodes require Nvme volumes.  @zk903956028
