### ISSUE TITLE
[Bug]: fail to start milvus by kubectl apply -f milvus_manifest.yaml 

### ISSUE THREAD

**Issue by xiaomujiang** [milvus-io/milvus#26850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.0
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):     pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): centos7.9
- CPU/Memory:  2cpu 4g
- GPU: 
- Others:
```

### Current Behavior

https://milvus.io/docs/install_offline-helm.md  采用离线的方式进行安装milvus集群
kubectl apply -f milvus_manifest.yaml 之后一直没有成功

[root@k8s-master01 ~]# kubectl get pods -o wide
NAME                                            READY   STATUS     RESTARTS   AGE   IP           NODE           NOMINATED NODE   READINESS GATES
my-release-etcd-0                               0/1     Pending    0          52m   <none>       <none>         <none>           <none>
my-release-etcd-1                               0/1     Pending    0          52m   <none>       <none>         <none>           <none>
my-release-etcd-2                               0/1     Pending    0          52m   <none>       <none>         <none>           <none>
my-release-milvus-datacoord-7bc59bc599-z6jsr    0/1     Init:0/1   0          52m   <none>       node1          <none>           <none>
my-release-milvus-datanode-9c4494c98-7kznm      0/1     Init:0/1   0          52m   <none>       node1          <none>           <none>
my-release-milvus-indexcoord-7f69d95df4-w7ngm   0/1     Running    3          52m   10.244.0.4   k8s-master01   <none>           <none>
my-release-milvus-indexnode-766b657b6f-qv5d4    0/1     Init:0/1   0          52m   <none>       node1          <none>           <none>
my-release-milvus-proxy-65565d8444-ztdzb        0/1     Init:0/1   0          52m   <none>       node1          <none>           <none>
my-release-milvus-querycoord-96bd56765-s7fq2    0/1     Init:0/1   0          52m   <none>       node1          <none>           <none>
my-release-milvus-querynode-5f99f7f4b7-gmkk2    0/1     Init:0/1   0          52m   <none>       node1          <none>           <none>
my-release-milvus-rootcoord-6767769f49-qwhrn    0/1     Init:0/1   0          52m   <none>       node1          <none>           <none>
my-release-minio-0                              0/1     Pending    0          52m   <none>       <none>         <none>           <none>
my-release-minio-1                              0/1     Pending    0          52m   <none>       <none>         <none>           <none>
my-release-minio-2                              0/1     Pending    0          52m   <none>       <none>         <none>           <none>
my-release-minio-3                              0/1     Pending    0          52m   <none>       <none>         <none>           <none>
my-release-pulsar-bookie-0                      0/1     Pending    0          52m   <none>       <none>         <none>           <none>
my-release-pulsar-bookie-1                      0/1     Pending    0          52m   <none>       <none>         <none>           <none>
my-release-pulsar-bookie-2                      0/1     Pending    0          52m   <none>       <none>         <none>           <none>
my-release-pulsar-bookie-init-hlwfz             0/1     Init:0/1   0          52m   10.244.0.5   k8s-master01   <none>           <none>
my-release-pulsar-broker-0                      0/1     Pending    0          52m   <none>       <none>         <none>           <none>
my-release-pulsar-proxy-0                       0/1     Pending    0          52m   <none>       <none>         <none>           <none>
my-release-pulsar-pulsar-init-4w56n             0/1     Init:0/2   0          52m   10.244.0.7   k8s-master01   <none>           <none>
my-release-pulsar-recovery-0                    0/1     Init:0/1   0          52m   10.244.0.6   k8s-master01   <none>           <none>
my-release-pulsar-zookeeper-0                   0/1     Pending    0          52m   <none>       <none>         <none>           <none>

通过 describe 查看 pod/my-release-milvus-indexcoord-7f69d95df4-w7ngm

[root@k8s-master01 ~]# kubectl describe pod/my-release-milvus-indexcoord-7f69d95df4-w7ngm
Name:         my-release-milvus-indexcoord-7f69d95df4-w7ngm
Namespace:    default
Priority:     0
Node:         k8s-master01/10.0.4.16
Start Time:   Tue, 05 Sep 2023 13:58:56 +0800
Labels:       app.kubernetes.io/instance=my-release
              app.kubernetes.io/name=milvus
              component=indexcoord
              pod-template-hash=7f69d95df4
Annotations:  checksum/config: 7ef99c73c0dc15d914de19f6e98caf2b5ce93632f734e633b29c08ac512bf53b
Status:       Running
IP:           10.244.0.4
IPs:
  IP:           10.244.0.4
Controlled By:  ReplicaSet/my-release-milvus-indexcoord-7f69d95df4
Init Containers:
  config:
    Container ID:  docker://ccba63b4f44e97f02d41b7ecbca71fb448dde84e8b53afa462cce37849c1153c
    Image:         milvusdb/milvus-config-tool:v0.1.1
    Image ID:      docker-pullable://milvusdb/milvus-config-tool@sha256:6cb6f5fa9331a7d4449b74b55115db19aa51847e19922b9fef2a4b2ec6e42262
    Port:          <none>
    Host Port:     <none>
    Command:
      /cp
      /run-helm.sh,/merge
      /milvus/tools/run-helm.sh,/milvus/tools/merge
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 05 Sep 2023 13:58:58 +0800
      Finished:     Tue, 05 Sep 2023 13:58:58 +0800
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /milvus/tools from tools (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-xz7p7 (ro)
Containers:
  indexcoord:
    Container ID:  docker://1f9a4daa7ab9fd7b70786449a8aebae6545b97ad99ed83b028c112bc21347c76
    Image:         milvusdb/milvus:v2.3.0
    Image ID:      docker-pullable://milvusdb/milvus@sha256:6a467052e1a38a2ceef9bfaf384cba0a359eadf366d3ffa9e7e32c4725b87877
    Ports:         31000/TCP, 9091/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      /milvus/tools/run-helm.sh
      milvus
      run
      indexcoord
    State:          Running
      Started:      Tue, 05 Sep 2023 14:52:17 +0800
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 05 Sep 2023 14:48:17 +0800
      Finished:     Tue, 05 Sep 2023 14:52:16 +0800
    Ready:          False
    Restart Count:  4
    Liveness:       http-get http://:metrics/healthz delay=90s timeout=5s period=30s #success=1 #failure=5
    Readiness:      http-get http://:metrics/healthz delay=90s timeout=5s period=10s #success=1 #failure=5
    Environment:    <none>
    Mounts:
      /milvus/configs/default.yaml from milvus-config (ro,path="default.yaml")
      /milvus/configs/user.yaml from milvus-config (ro,path="user.yaml")
      /milvus/tools from tools (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-xz7p7 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  milvus-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      my-release-milvus
    Optional:  false
  tools:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  default-token-xz7p7:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-xz7p7
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  53m                  default-scheduler  Successfully assigned default/my-release-milvus-indexcoord-7f69d95df4-w7ngm to k8s-master01
  Normal   Pulled     53m                  kubelet            Container image "milvusdb/milvus-config-tool:v0.1.1" already present on machine
  Normal   Created    53m                  kubelet            Created container config
  Normal   Started    53m                  kubelet            Started container config
  Warning  Unhealthy  13m                  kubelet            Liveness probe failed: Get "http://10.244.0.4:9091/healthz": dial tcp 10.244.0.4:9091: i/o timeout (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  12m (x2 over 13m)    kubelet            Readiness probe failed: Get "http://10.244.0.4:9091/healthz": dial tcp 10.244.0.4:9091: i/o timeout (Client.Timeout exceeded while awaiting headers)
  Normal   Killing    12m                  kubelet            Container indexcoord failed liveness probe, will be restarted
  Normal   Started    12m (x2 over 53m)    kubelet            Started container indexcoord
  Normal   Pulled     12m (x2 over 53m)    kubelet            Container image "milvusdb/milvus:v2.3.0" already present on machine
  Normal   Created    12m (x2 over 53m)    kubelet            Created container indexcoord
  Warning  Unhealthy  10m (x13 over 14m)   kubelet            Readiness probe failed: Get "http://10.244.0.4:9091/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  4m7s (x12 over 14m)  kubelet            Liveness probe failed: Get "http://10.244.0.4:9091/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

[root@k8s-master01 ~]# kubectl logs pod/my-release-milvus-indexcoord-7f69d95df4-w7ngm
Error from server: Get "https://10.0.4.16:10250/containerLogs/default/my-release-milvus-indexcoord-7f69d95df4-w7ngm/indexcoord": dial tcp 10.0.4.16:10250: i/o timeout

### Anything else?

10.0.4.16 master的内网地址

**Comment by yanliang567** [comment]
/assign @LoveEachDay 
please help to take a look at this issue.
/unassign
