### ISSUE TITLE
[Bug]: Milvus2.3, describeCollection, "autoID" is always false

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus#26866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.3.0   
- SDK version(e.g. pymilvus v2.0.0rc2): node sdk
```

### Current Behavior

Related to https://github.com/zilliztech/attu/issues/260
Same sdk code, different behaviour 

![2710f43c-a0a1-4b41-913e-d45dc22193df](https://github.com/milvus-io/milvus/assets/185051/8f5829cd-3444-4727-8810-ec90296fbda3)

![b7768df5-6c30-4ae4-beab-15eed00ea09a](https://github.com/milvus-io/milvus/assets/185051/7554cfce-b20c-45ed-a6c2-d5d8bf59e86a)

**Comment by shanghaikid** [comment]
it looks like pymilvus is working. any change on grpc format?

**Comment by congqixia** [comment]
@shanghaikid just checked v2.3.0 and v2.2.14 the `AutoID` under schema is discarded
the actually working field is `AutoID` under `Field` definition
Not sure which field did Attu use creating collection

**Comment by shanghaikid** [comment]
you are correct. close the issue.
