### ISSUE TITLE
[Bug]: Abnormal Scheduler bahaviour on MixCoord

### ISSUE THREAD

**Issue by MrPresent-Han** [milvus-io/milvus#26877]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.0
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

In the process of inserting, the actions of scheduler on mixcoord seemed confusing and inefficient for replacing index for sealed segments on query node.

### Expected Behavior

mixCoord timely replace unindexed segments and search performance recovered to normal level promptly,

### Milvus Log

cluster: 4am
namespace: qa-milvus
instance: laion-test-3
time range: 2023-08-30 17:36:55 to 2023-08-30 18:15:55

**Comment by MrPresent-Han** [comment]
![ue00sVOA61](https://github.com/milvus-io/milvus/assets/116052805/4ef2e4ea-ca17-41fd-ac32-06887d60a282)

**Comment by yanliang567** [comment]
did not see any PRs linked, was it fixed ? @MrPresent-Han
