### ISSUE TITLE
ERROR: Milvus server fail to load config file

### ISSUE THREAD

**Issue by dotsonliu** [milvus-io/milvus#2687]
when i use milvus on windows docker
 
Loading configuration from: ../conf/server_config.yaml
Config file not exist: ../conf/server_config.yaml
ERROR: Milvus server fail to load config file
Config file not exist: ../conf/server_config.yaml
Milvus server exit...

but server_config.yaml locate in /c/milvus/server_config.yaml
how to resolve it???

**Comment by Bennu-Li** [comment]
Can you paste the command you run milvus docker?

**Comment by kwalcock** [comment]
Please see #273 for an example.
