### ISSUE TITLE
[Bug]:  How to set the Release compilation option for the knowhere component in milvus

### ISSUE THREAD

**Issue by cheetahsec** [milvus-io/milvus#26886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.0
- Deployment mode(standalone or cluster):standalone 
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

 The libknowhere.so file generated by building knowhere alone is only 8mb, but the libknowhere.so generated by building the milvus project is 160mb, readelf check and find that there are debugging symbols, it should be a debug version, but in the cmake file of the milvus project, the libknowhere compilation option is output as Release, here it is more confusing and does not locate the reason, Expect to wait until some help. Are there other compilation configuration switch settings?   

**the libknowhere.so generated by building the milvus project is 160mb**
> root@c7d3e0ed8ab3:/go/src/github.com/milvus-io/milvus# ls /go/src/github.com/milvus-io/milvus/internal/core/output/lib/ -lh
> total 1.1G
> drwxr-xr-x 3 root root 4.0K Sep  5 12:00 cmake
> -rw-r--r-- 1 root root 211K Sep  5 12:36 libboost_bitset_ext.a
> -rw-r--r-- 1 root root 158M Sep  5 11:58 libdiskann.a
> -rw-r--r-- 1 root root 172M Sep  5 12:36 libfaiss.a
> lrwxrwxrwx 1 root root   26 Sep  5 12:00 libgflags_nothreads.so -> libgflags_nothreads.so.2.2
> lrwxrwxrwx 1 root root   28 Sep  5 12:00 libgflags_nothreads.so.2.2 -> libgflags_nothreads.so.2.2.2
> -rw-r--r-- 1 root root 204K Aug 31 07:46 libgflags_nothreads.so.2.2.2
> lrwxrwxrwx 1 root root   12 Sep  5 12:00 libglog.so -> libglog.so.1
> -rw-r--r-- 1 root root 251K Aug 31 08:02 libglog.so.0.6.0
> lrwxrwxrwx 1 root root   16 Sep  5 12:00 libglog.so.1 -> libglog.so.0.6.0
> -rwxr-xr-x 1 root root  27M Sep  5 12:00 libjemalloc.a
> lrwxrwxrwx 1 root root   16 Sep  5 12:00 libjemalloc.so -> libjemalloc.so.2
> -rwxr-xr-x 1 root root 6.5M Sep  5 12:00 libjemalloc.so.2
> -rwxr-xr-x 1 root root  27M Sep  5 12:00 libjemalloc_pic.a
> -rw-r--r-- 1 root root 163M Sep  5 12:36 libknowhere.so
> -rw-r--r-- 1 root root 1.2M Sep  5 12:36 libknowhere_utils.a
> -rw-r--r-- 1 root root  40M Sep  6 09:46 libmilvus_common.so
> -rw-r--r-- 1 root root 2.7M Sep  6 09:46 libmilvus_config.a
> -rw-r--r-- 1 root root 1.7M Sep  6 09:46 libmilvus_exceptions.a
> -rw-r--r-- 1 root root  30M Sep  6 09:46 libmilvus_index.so
> -rw-r--r-- 1 root root  12M Sep  6 09:46 libmilvus_indexbuilder.so
> -rw-r--r-- 1 root root 506K Sep  5 12:36 libmilvus_log.a
> -rw-r--r-- 1 root root  22M Sep  6 09:46 libmilvus_proto.a
> -rw-r--r-- 1 root root 190M Sep  6 09:46 libmilvus_query.a
> -rw-r--r-- 1 root root 130M Sep  6 09:46 libmilvus_segcore.so
> -rw-r--r-- 1 root root  75M Sep  6 09:46 libmilvus_storage.so
> -rw-r--r-- 1 root root 421K Sep  5 12:36 libmilvus_utils.a
> lrwxrwxrwx 1 root root   16 Sep  5 12:00 libopenblas.so -> libopenblas.so.0
> lrwxrwxrwx 1 root root   18 Sep  5 12:00 libopenblas.so.0 -> libopenblas.so.0.3
> -rw-r--r-- 1 root root  38M Aug 31 08:30 libopenblas.so.0.3
> lrwxrwxrwx 1 root root   17 Sep  5 12:00 librdkafka++.so -> librdkafka++.so.1
> -rw-r--r-- 1 root root 236K Aug 31 08:42 librdkafka++.so.1
> lrwxrwxrwx 1 root root   15 Sep  5 12:00 librdkafka.so -> librdkafka.so.1
> -rw-r--r-- 1 root root 7.3M Aug 31 08:42 librdkafka.so.1
> lrwxrwxrwx 1 root root   15 Sep  5 12:00 librocksdb.so -> librocksdb.so.6
> lrwxrwxrwx 1 root root   20 Sep  5 12:00 librocksdb.so.6 -> librocksdb.so.6.29.5
> -rw-r--r-- 1 root root  13M Aug 31 08:38 librocksdb.so.6.29.5
> -rw-r--r-- 1 root root  12M Sep  5 12:36 libsimdjson.a
> lrwxrwxrwx 1 root root   12 Sep  5 12:00 libtbb.so -> libtbb.so.12
> lrwxrwxrwx 1 root root   14 Sep  5 12:00 libtbb.so.12 -> libtbb.so.12.7
> -rw-r--r-- 1 root root 320K Aug 31 08:35 libtbb.so.12.7
> lrwxrwxrwx 1 root root   19 Sep  5 12:00 libtbbbind_2_5.so -> libtbbbind_2_5.so.3
> lrwxrwxrwx 1 root root   21 Sep  5 12:00 libtbbbind_2_5.so.3 -> libtbbbind_2_5.so.3.7
> -rw-r--r-- 1 root root 387K Aug 31 08:35 libtbbbind_2_5.so.3.7
> drwxr-xr-x 2 root root 4.0K Sep  5 12:00 pkgconfig

 **readelf check and find that there are debugging symbols**
> root@c7d3e0ed8ab3:/go/src/github.com/milvus-io/milvus# readelf -S /go/src/github.com/milvus-io/milvus/internal/core/output/lib/libknowhere.so
> There are 40 section headers, starting at offset 0xa284728:
> 
> Section Headers:
>   [Nr] Name              Type             Address           Offset
>        Size              EntSize          Flags  Link  Info  Align
>   [ 0]                   NULL             0000000000000000  00000000
>        0000000000000000  0000000000000000           0     0     0
>   [ 1] .note.gnu.build-i NOTE             0000000000000270  00000270
>        0000000000000024  0000000000000000   A       0     0     4
>   [ 2] .gnu.hash         GNU_HASH         0000000000000298  00000298
>        000000000001b7f4  0000000000000000   A       3     0     8
>   [ 3] .dynsym           DYNSYM           000000000001ba90  0001ba90
>        00000000000603c0  0000000000000018   A       4     1     8
>   [ 4] .dynstr           STRTAB           000000000007be50  0007be50
>        0000000000173673  0000000000000000   A       0     0     1
>   [ 5] .gnu.version      VERSYM           00000000001ef4c4  001ef4c4
>        0000000000008050  0000000000000002   A       3     0     2
>   [ 6] .gnu.version_r    VERNEED          00000000001f7518  001f7518
>        00000000000003c0  0000000000000000   A       4     9     8
>   [ 7] .rela.dyn         RELA             00000000001f78d8  001f78d8
>        00000000000717d8  0000000000000018   A       3     0     8
>   [ 8] .rela.plt         RELA             00000000002690b0  002690b0
>        0000000000025020  0000000000000018  AI       3    25     8
>   [ 9] .init             PROGBITS         000000000028f000  0028f000
>        0000000000000020  0000000000000000  AX       0     0     4
>   [10] .plt              PROGBITS         000000000028f020  0028f020
>        0000000000018ad0  0000000000000010  AX       0     0     16
>   [11] .plt.got          PROGBITS         00000000002a7af0  002a7af0
>        0000000000000340  0000000000000008  AX       0     0     8
>   [12] .text             PROGBITS         00000000002a8000  002a8000
>        00000000007ba260  0000000000000000  AX       0     0     4096
>   [13] .fini             PROGBITS         0000000000a62260  00a62260
>        000000000000000d  0000000000000000  AX       0     0     4
>   [14] .rodata           PROGBITS         0000000000a63000  00a63000
>        000000000009a5c0  0000000000000000   A       0     0     64
>   [15] .eh_frame_hdr     PROGBITS         0000000000afd5c0  00afd5c0
>        000000000001f60c  0000000000000000   A       0     0     4
>   [16] .eh_frame         PROGBITS         0000000000b1cbd0  00b1cbd0
>        00000000000bb288  0000000000000000   A       0     0     8
>   [17] .gcc_except_table PROGBITS         0000000000bd7e58  00bd7e58
>        0000000000030b13  0000000000000000   A       0     0     4
>   [18] .tdata            PROGBITS         0000000000c0a250  00c09250
>        0000000000000008  0000000000000000 WAT       0     0     16
>   [19] .tbss             NOBITS           0000000000c0a260  00c09258
>        0000000000000200  0000000000000000 WAT       0     0     16
>   [20] .init_array       INIT_ARRAY       0000000000c0a260  00c09260
>        00000000000001d0  0000000000000008  WA       0     0     8
>   [21] .fini_array       FINI_ARRAY       0000000000c0a430  00c09430
>        0000000000000008  0000000000000008  WA       0     0     8
>   [22] .data.rel.ro      PROGBITS         0000000000c0a440  00c09440
>        000000000003aea0  0000000000000000  WA       0     0     32
>   [23] .dynamic          DYNAMIC          0000000000c452e0  00c442e0
>        0000000000000290  0000000000000010  WA       4     0     8
>   [24] .got              PROGBITS         0000000000c45570  00c44570
>        0000000000003a88  0000000000000008  WA       0     0     8
>   [25] .got.plt          PROGBITS         0000000000c49000  00c48000
>        000000000000c578  0000000000000008  WA       0     0     8
>   [26] .data             PROGBITS         0000000000c55580  00c54580
>        0000000000001ff0  0000000000000000  WA       0     0     32
>   [27] .bss              NOBITS           0000000000c57580  00c56570
>        00000000000b62f8  0000000000000000  WA       0     0     128
>   [28] .comment          PROGBITS         0000000000000000  00c56570
>        0000000000000057  0000000000000001  MS       0     0     1
>   [29] .note.stapsdt     NOTE             0000000000000000  00c565c8
>        00000000000000fc  0000000000000000           0     0     4
>   [30] .debug_aranges    PROGBITS         0000000000000000  00c566c4
>        000000000001e8b0  0000000000000000           0     0     1
>   [31] .debug_info       PROGBITS         0000000000000000  00c74f74
>        0000000003a64d34  0000000000000000           0     0     1
>   [32] .debug_abbrev     PROGBITS         0000000000000000  046d9ca8
>        00000000000a14ce  0000000000000000           0     0     1
>   [33] .debug_line       PROGBITS         0000000000000000  0477b176
>        000000000091b579  0000000000000000           0     0     1
>   [34] .debug_str        PROGBITS         0000000000000000  050966ef
>        0000000000f72c80  0000000000000001  MS       0     0     1
>   [35] .debug_loc        PROGBITS         0000000000000000  0600936f
>        0000000003364515  0000000000000000           0     0     1
>   [36] .debug_ranges     PROGBITS         0000000000000000  0936d884
>        0000000000cc6860  0000000000000000           0     0     1
>   [37] .symtab           SYMTAB           0000000000000000  0a0340e8
>        0000000000087120  0000000000000018          38   6629     8
>   [38] .strtab           STRTAB           0000000000000000  0a0bb208
>        00000000001c939a  0000000000000000           0     0     1
>   [39] .shstrtab         STRTAB           0000000000000000  0a2845a2
>        0000000000000184  0000000000000000           0     0     1
> Key to Flags:
>   W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
>   L (link order), O (extra OS processing required), G (group), T (TLS),
>   C (compressed), x (unknown), o (OS specific), E (exclude),
>   l (large), p (processor specific)

**The release version, built separately using the knowhere project, is only 8MB in size**
> root@16b277cb5d74:/go/src/github.com/milvus-io/knowhere/build/Release# ls -lh
> total 86M
> -rw-r--r-- 1 root root  30K Sep  5 01:54 CMakeCache.txt
> drwxr-xr-x 1 root root 4.0K Sep  6 07:37 CMakeFiles
> -rw-r--r-- 1 root root 142K Sep  6 07:36 Makefile
> -rw-r--r-- 1 root root 3.7K Sep  5 01:54 cmake_install.cmake
> -rw-r--r-- 1 root root 225K Sep  6 07:36 compile_commands.json
> drwxr-xr-x 1 root root 4.0K Sep  5 01:49 generators
> -rw-r--r-- 1 root root 8.9M Sep  5 01:56 libfaiss.a
> -rwxrwxrwx 1 root root  68M Sep  6 08:09 libknowhere.i64
> -rwxr-xr-x 1 root root 8.0M Sep  6 07:37 libknowhere.so
> -rw-r--r-- 1 root root  42K Sep  5 01:54 libknowhere_utils.a
> drwxr-xr-x 1 root root 4.0K Sep  5 01:54 tests

### Milvus Log

[build.log](https://github.com/milvus-io/milvus/files/12537373/build.log)

**Comment by cydrain** [comment]
compare one file's compile options between Milvus and Knowhere:

Milvus:
```
/usr/bin/c++ ... -Wall -fPIC -std=gnu++17  -g   -fPIC -DELPP_THREAD_SAFE -fopenmp -Werror -O3 -fPIC -Wno-error -fopenmp -fopenmp -O3 -DNDEBUG -fPIC ... -fopenmp -std=gnu++17 -o CMakeFiles/knowhere.dir/src/index/ivf/ivf.cc.o -c /home/caiyd/vec/milvus/cmake_build/thirdparty/knowhere/knowhere-src/src/index/ivf/ivf.cc
```

Knowhere:
```
/usr/bin/c++ ... -Wall -fPIC -std=gnu++17 -m64 -fopenmp -O3 -DNDEBUG -fPIC -fopenmp -std=gnu++17 -o CMakeFiles/knowhere.dir/src/index/ivf/ivf.cc.o -c /home/caiyd/vec/knowhere/src/index/ivf/ivf.cc",
```

**Comment by cydrain** [comment]
The only difference is that Milvus adds a "-g" build option which is introduced with PR #26354.

**Comment by cheetahsec** [comment]
> @cheetahsec
> 
> The only difference is that Milvus adds a "-g" build option which is introduced with PR #26354.
> 
> We can confirm that knowhere build in Milvus is _RELEASE_ version. Or you can remove the "-g" option by reverting PR #26354.

 Thanks again for your help, I rechecked the documentation for GCC, the “-g” option in GCC compiler is used to generate debugging information. This debugging information includes details like line numbers of the source code, local and global variables, etc.
