### ISSUE TITLE
Construct Knowhere Index Without Data

### ISSUE THREAD

**Issue by sahuang** [milvus-io/milvus#2689]
**Is your feature request related to a problem? Please describe.**

Currently Milvus uses Faiss Index to perform operations such as searching. For example, IVFFLAT index will include an inverted list, which contains ivf id list and codes list. However, when it comes to MVCC and distributed architecture, we want to transform as fewer data as possible, and storing data in index can make index data very large. **This is especially true in IVFFLAT, HNSW and NSG.**

**Describe the solution you'd like**

We aim to reconstruct Faiss index to let index only store offsets rather than raw data. In this way we can save lots of memory and greatly reduce data transformation time.

In order to achieve this, we will pass raw data from Milvus engine to knowhere, and construct appropriate data in knowhere Load(). **The index will not store data.** We then pass offset-only index and constructed data into searching operations. Search time will not be affected.

**Additional context**

Only IVFFLAT, HNSW and NSG are implemented. Reconstructing other index types is unnecessary (e.g. IVFSQ8 and IVFPQ) because they use compressed codes and will not save much space. It also costs much time to compute.

**Comment by shengjun1985** [comment]
@del-zhenwu Please pay attention. The related indexes built before can not be used.
