### ISSUE TITLE
[Bug]: IndexNode failed to build index due to error "parse magic number failed, expected: 16775868, actual: 808464433"

### ISSUE THREAD

**Issue by linjunzhe** [milvus-io/milvus#26903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.12
- Deployment mode(standalone or cluster): Cluster
- MQ type(rocksmq, pulsar or kafka):   Kafka
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.2.15
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 4 indexnode replica with 16cores/32GB for each pod
- GPU: 0
- Others:
```

### Current Behavior

I use Milvus Operator to build the cluster mode Milvus (with an external S3 storage). Then I try to run [hello_milvus.py ](https://github.com/milvus-io/pymilvus/blob/master/examples/hello_milvus.py)to test the arability. However, the hello milvus script get stuck in create index. 

I did some research, find that there's some strange logs in IndexNode like following. 
```
[2023/09/05 10:34:17.774 +00:00] [INFO] [indexnode/indexnode_service.go:47] ["IndexNode building index ..."] [traceID=6b04edaaa34cafea] [ClusterID=prod2] [IndexBuildID=444047694527674537] [IndexID=0] [IndexName=] [IndexFilePrefix=milvus/index_files] [IndexVersion=120] [DataPaths="[milvus/insert_log/444047694527473587/444047694527473588/444047694527674513/102/444047694527674531]"] [TypeParams="[{\"key\":\"dim\",\"value\":\"8\"}]"] [IndexParams="[{\"key\":\"index_type\",\"value\":\"IVF_FLAT\"},{\"key\":\"metric_type\",\"value\":\"L2\"},{\"key\":\"nlist\",\"value\":\"128\"}]"] [num_rows=3000]
[2023/09/05 10:34:17.774 +00:00] [INFO] [indexnode/indexnode_service.go:112] ["IndexNode successfully scheduled"] [traceID=6b04edaaa34cafea] [IndexBuildID=444047694527674537] [ClusterID=prod2] [indexName=]
[2023/09/05 10:34:17.774 +00:00] [INFO] [indexnode/task.go:153] ["Begin to prepare indexBuildTask"] [buildID=444047694527674537] [Collection=0] [SegmentIf=0] ["queue duration"=58.862µs]
[2023/09/05 10:34:17.775 +00:00] [INFO] [indexnode/task.go:183] ["Successfully prepare indexBuildTask"] [buildID=444047694527674537] [Collection=0] [SegmentIf=0]
[2023/09/05 10:34:17.778 +00:00] [WARN] [indexnode/task.go:248] ["parse field meta from binlog failed"] [error="parse magic number failed, expected: 16775868, actual: 808464433"]
[2023/09/05 10:34:17.778 +00:00] [INFO] [indexnode/taskinfo_ops.go:42] ["IndexNode store task state"] [clusterID=prod2] [buildID=444047694527674537] [state=Retry] ["fail reason"="parse magic number failed, expected: 16775868, actual: 808464433"]
```
808464433 in hex is 0x30303031, which is "1000" in ASCII. I downloaded the insert log from S3, and use a hex viewer to check it. I find that S3 added a chunk length and chunk signature in the front of the real data. 
```
n;chunk-signature=<hash>
real data
n;chunk-signature=<hash>
```
![image](https://github.com/milvus-io/milvus/assets/1384807/ee56b2d9-682f-42eb-8a1b-97e1cdbb8214)
As above screenshot shows, milvus try to read the magic number (int32) from the beginning of the file, but it get 0x30303031, which caused the read fail and build index fail. The actually magic number is after the chunk info.

Since the external S3 in this case, is a company internal project, so I'm not quite sure if it's a Milvus S3 write/read code bug, or our S3 infrastructure issue. BTW, I tried to replace the external S3 to Minio, it works perfectly with Minio, no issue. Please help me to investigate how I can disable this chunk signature behavior.  

### Expected Behavior

The [hello_milvus.py ](https://github.com/milvus-io/pymilvus/blob/master/examples/hello_milvus.py) should be able to create index with external S3

### Steps To Reproduce
1. Create a Milvus CR like following

```markdown
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: debug-s3
  labels:
    app: milvus-debug-s3
spec:
  mode: cluster
  components:
    podLabels: {}
    nodeSelector: {}
    dataCoord:
      resources:
        limits:
          cpu: 2
          memory: 4Gi
    queryCoord:
      resources:
        limits:
          cpu: 2
          memory: 4Gi
    indexCoord:
      resources:
        limits:
          cpu: 2
          memory: 4Gi
    rootCoord:
      resources:
        limits:
          cpu: 2
          memory: 4Gi
    dataNode:
      replicas:  1
      resources:
        limits:
          cpu: 2
          memory: 8Gi
    indexNode:
      replicas: 4
      resources:
        limits:
          cpu: 16
          memory: 32Gi
    queryNode:
      replicas: 4
      resources:
        limits:
          cpu: 8
          memory: 32Gi
    proxy:
      replicas: 1
      resources:
        limits:
          cpu: 1
          memory: 4Gi
      serviceType: LoadBalancer
  config:
    minio:
      bucketName: milvus-debug
      rootPath: milvus
      useSSL: false
  dependencies:
    etcd:
      inCluster:
        values:
          metrics:
            enabled: true
            podAnnotations: {}
          clusterDomain: "xxx.internal.local"
          podLabels: {}
          nodeSelector: {}
          persistence:
            accessMode: ReadWriteOnce
            enabled: true
            size: 30Gi 
            storageClass: csi-rbd-storageclass
          replicaCount: 3
          resources:
            limits:
              cpu: 4
              memory: 8Gi
            requests:
              cpu: 4
              memory: 8Gi
    msgStreamType: kafka
    kafka:
      inCluster:
        values:
          heapOpts: "-Xmx8192M -Xms8192M"
          clusterDomain: "xxx.internal.local"
          podLabels: {}
          nodeSelector: {}
          persistence:
            enabled: true
            storageClass: csi-rbd-storageclass
            accessMode: ReadWriteOnce
            size: 60Gi
          resources:
            limits:
              cpu: 4
              memory: 25Gi
          zookeeper:
            enabled: true
            replicaCount: 3
            heapSize: 2048  
            persistence:
              enabled: true
              storageClass: csi-rbd-storageclass
              accessModes:
                - ReadWriteOnce
              size: 20Gi 
            resources:
              limits:
                cpu: 2
                memory: 4Gi
    storage:
      external: true
      type: S3
      endpoint: xxx.internal.s3.com:80
      secretRef: "milvus-debug-s3-secret"
```
2. Wait for Milvus Operator to create the Milvus Cluster. 
3. Run [hello_milvus.py ](https://github.com/milvus-io/pymilvus/blob/master/examples/hello_milvus.py) it will stuck in create index step
### Milvus Log
```
[2023/09/05 10:34:17.774 +00:00] [INFO] [indexnode/indexnode_service.go:47] ["IndexNode building index ..."] [traceID=6b04edaaa34cafea] [ClusterID=prod2] [IndexBuildID=444047694527674537] [IndexID=0] [IndexName=] [IndexFilePrefix=milvus/index_files] [IndexVersion=120] [DataPaths="[milvus/insert_log/444047694527473587/444047694527473588/444047694527674513/102/444047694527674531]"] [TypeParams="[{\"key\":\"dim\",\"value\":\"8\"}]"] [IndexParams="[{\"key\":\"index_type\",\"value\":\"IVF_FLAT\"},{\"key\":\"metric_type\",\"value\":\"L2\"},{\"key\":\"nlist\",\"value\":\"128\"}]"] [num_rows=3000]
[2023/09/05 10:34:17.774 +00:00] [INFO] [indexnode/indexnode_service.go:112] ["IndexNode successfully scheduled"] [traceID=6b04edaaa34cafea] [IndexBuildID=444047694527674537] [ClusterID=prod2] [indexName=]
[2023/09/05 10:34:17.774 +00:00] [INFO] [indexnode/task.go:153] ["Begin to prepare indexBuildTask"] [buildID=444047694527674537] [Collection=0] [SegmentIf=0] ["queue duration"=58.862µs]
[2023/09/05 10:34:17.775 +00:00] [INFO] [indexnode/task.go:183] ["Successfully prepare indexBuildTask"] [buildID=444047694527674537] [Collection=0] [SegmentIf=0]
[2023/09/05 10:34:17.778 +00:00] [WARN] [indexnode/task.go:248] ["parse field meta from binlog failed"] [error="parse magic number failed, expected: 16775868, actual: 808464433"]
[2023/09/05 10:34:17.778 +00:00] [INFO] [indexnode/taskinfo_ops.go:42] ["IndexNode store task state"] [clusterID=prod2] [buildID=444047694527674537] [state=Retry] ["fail reason"="parse magic number failed, expected: 16775868, actual: 808464433"]
```
### Anything else?

I tested on both v2.2.12 and v2.2.14, see the same error.
The issue is also reported in Slack channel https://milvusio.slack.com/archives/CMNHUC371/p1693969271176639?thread_ts=1693905201.068279&cid=CMNHUC371

**Comment by xiaofan-luan** [comment]
I don't think we heard such bug from other users.
when did this index file generated?
Very old version seems to have index file corrupt issue(before 2.2.5)

If your index is generated on 2.2.12 or 2.2.14 my guess this is due to your storage corrupt the data.
Is it S3?

**Comment by xiaofan-luan** [comment]
Is it reproducible? could you offer your index file?

**Comment by linjunzhe** [comment]
@xiaofan-luan  Yes. It's S3. 
[444070042118072143.gz](https://github.com/milvus-io/milvus/files/12557133/444070042118072143.gz) this is the error binlog.

**Comment by xiaofan-luan** [comment]
/assign @xiaocai2333 
could you help on the index log?

**Comment by xiaocai2333** [comment]
working no it~

**Comment by xiaofan-luan** [comment]
> working no it~

@linjunzhe 
Is is reproducible or it only happened once?

@xiaocai2333 
we should try to analyze the error bin log see if we can get some clue

**Comment by xiaocai2333** [comment]
> 

Yes, I am trying to run the normal file locally and compare it to see what the difference is.

**Comment by xiaocai2333** [comment]
@linjunzhe The chunk-signature is included because x-amz-content-sha256 is specified in the request header. Check your S3 configuration to see if the relevant parameters are configured.

**Comment by linjunzhe** [comment]
@xiaocai2333 Yes. We find the root cause. The GetObject interface in Our company's internal S3's behavior is not  compatible with AWS S3/Minio. It returns text/plain with chunk signature around the real data, but Minio returns application/octet-stream content type which is expected. Check the highlight part of following screenshot from TCPDump. 
![image](https://github.com/milvus-io/milvus/assets/1384807/5718cf0e-095c-458e-9d94-20a83773ec85)

It because Minio client default behavior on HTTP is adding chunk signature to make sure the data body will not be modified. To disable this behavior, we can add `minio.PutObjectOptions{DisableContentSha256: true}` when call PutObject https://github.com/milvus-io/milvus/blob/c45c32fad4d8bedfd8de847edc94feddf2744949/internal/storage/minio_chunk_manager.go#L210. 

So my request becomes, is that possible to add a config on Milvus to disable the chunk signature when write data to S3? It maybe other users having the same issue, AWS S3 is sooooo complicated, and any company developed internal storage can't guarantee it's 100% compatible with AWS S3.

**Comment by xiaocai2333** [comment]
You can first check your milvus configuration.
If `minio.useSSL` is true, try changing it to false.

In addition, check whether the putObjectData you implemented has set DisableContentSha256 to true.

**Comment by linjunzhe** [comment]
@xiaocai2333 Yes,`minio.useSSL` is false. The storage implementation of PutObject is out of my control. What I'm asking is that possible to let Milvus expose a config to disable the chunk encoding upload behavior? Since compared with AWS S3 SDK by default disable that, it's Minio client default behavior to enable the chunk upload.

**Comment by xiaocai2333** [comment]
> @xiaocai2333 Yes,`minio.useSSL` is false. The storage implementation of PutObject is out of my control. What I'm asking is that possible to let Milvus expose a config to disable the chunk encoding upload behavior? Since compared with AWS S3 SDK by default disable that, it's Minio client default behavior to enable the chunk upload.

We need to discuss about this. But the stable image also needs to be included in the next release.

**Comment by linjunzhe** [comment]
> > @xiaocai2333 Yes,`minio.useSSL` is false. The storage implementation of PutObject is out of my control. What I'm asking is that possible to let Milvus expose a config to disable the chunk encoding upload behavior? Since compared with AWS S3 SDK by default disable that, it's Minio client default behavior to enable the chunk upload.
> 
> We need to discuss about this. But the stable image also needs to be included in the next release.

Any update for the discussion? Do we have plan to support that?

**Comment by xiaocai2333** [comment]
> > > @xiaocai2333 Yes,`minio.useSSL` is false. The storage implementation of PutObject is out of my control. What I'm asking is that possible to let Milvus expose a config to disable the chunk encoding upload behavior? Since compared with AWS S3 SDK by default disable that, it's Minio client default behavior to enable the chunk upload.
> > 
> > 
> > We need to discuss about this. But the stable image also needs to be included in the next release.
> 
> Any update for the discussion? Do we have plan to support that?

Are you sure you only need to use `DisableContentSha256` as a configuration item? I can provide you with a test image. You can test whether your test can work normally after enabling this field.
