### ISSUE TITLE
[Bug]: [ERROR] [datacoord/services.go:415] ["failed to get segment"] [segmentID=443860185928301150]

### ISSUE THREAD

**Issue by GLL550C** [milvus-io/milvus#26937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

[milvus-standalone (1).log](https://github.com/milvus-io/milvus/files/12557123/milvus-standalone.1.log)

**Comment by GLL550C** [comment]
The single-node deployment service has been restarted recently
![Uploading 830daa75b40eee8234a7d1e99517645.png…]()

**Comment by GLL550C** [comment]
The single-node deployment service has been restarted recently
![830daa75b40eee8234a7d1e99517645](https://github.com/milvus-io/milvus/assets/64561461/bb380fb8-6e23-4bb9-8155-cdff73669edd)

**Comment by GLL550C** [comment]
https://github.com/milvus-io/milvus/issues/26937

**Comment by yanliang567** [comment]
@GLL550C fail to get any useful info in the attached logs. Could you please specify which version of milvus are you running? if possible, please retry on milvus 2.3.0, and provide more info about how to reproduce the issue.

/assign @GLL550C 
/unassign

**Comment by GLL550C** [comment]
> @GLL550C无法在附加日志中获取任何有用的信息。您能具体说明您运行的是哪个版本的 milvus 吗？如果可能，请在 milvus 2.3.0 上重试，并提供有关如何重现该问题的更多信息。
> 
> /分配@GLL550C /取消分配

version  2.1.3

**Comment by xiaofan-luan** [comment]
please upgrade to 2.2.14.
This is an fixed issue~
