### ISSUE TITLE
[Bug]: docker start milvus2.3.0, exit without logs

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#26938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.0 cpu
- Deployment mode(standalone or cluster):standalone docker
- MQ type(rocksmq, pulsar or kafka):rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):N/A
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 16c/64g
- GPU: N/A
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/53512883/a2c30783-f8b3-4032-9595-7a977f680505)
![image](https://github.com/milvus-io/milvus/assets/53512883/15c6e330-9b5e-4535-a199-3599c368c3cb)

### Expected Behavior

start milvus successfully

### Steps To Reproduce

```markdown
1. download docker-compose.yml
2. docker compose up -d
```

### Milvus Log

Exit without logs.

**Comment by wmwsagara** [comment]
I also have the very same issue on Ubuntu too. Any fix yet?

**Comment by cydrain** [comment]
disable SIMD in knowhere/src/simd and core/src/simd, all using GENERIC APIs, Milvus still cannot bootup.
So this issue should not be related with SIMD.

All logs are with size 0, need check if it's related with glog.
/assign @jiaoew1991

**Comment by superpandaaa** [comment]
Meet similar issue. Exited(134) is reported. Log is   
```
what():  std::bad_alloc
qemu: uncaught target signal 6 (Aborted) - core dumped
```

**Comment by jiaoew1991** [comment]
related to this issue https://github.com/milvus-io/milvus/issues/25609

**Comment by jiaoew1991** [comment]
For x86 version, the CPU is too old and not suitable. You need to check the `Flags` of `lscpu`, at least it should support sse4.2 instruction set.

For arm version, you can use it directly.

**Comment by JackLCL** [comment]
> For x86 version, the CPU is too old and not suitable. You need to check the `Flags` of `lscpu`, at least it should support sse4.2 instruction set.
> 
> For arm version, you can use it directly.

But I can start milvus2.2.12 on the same machine.
![image](https://github.com/milvus-io/milvus/assets/53512883/7d0ee158-4292-4044-a3e4-253a57418afc)

**Comment by jiaoew1991** [comment]
> > For x86 version, the CPU is too old and not suitable. You need to check the `Flags` of `lscpu`, at least it should support sse4.2 instruction set.
> > For arm version, you can use it directly.
> 
> But I can start milvus2.2.12 on the same machine. ![image](https://user-images.githubusercontent.com/53512883/267289254-7d0ee158-4292-4044-a3e4-253a57418afc.png)
> 
> The same machine can run the old version of Milvus but cannot run the new version of Milvus. I think this is unreasonable.

Milvus 2.3.0 + knowhere 2.0 has undergone a lot of refactoring. This CPU is too old and the maintenance cost is high, so it has been decided not to support it anymore.
Generally, this type of CPU model may appear in scenarios where the KVM virtualization parameters are not set correctly. Please contact the operations team to reconfigure it.

**Comment by superpandaaa** [comment]
> For x86 version, the CPU is too old and not suitable. You need to check the `Flags` of `lscpu`, at least it should support sse4.2 instruction set.
> 
> For arm version, you can use it directly.

Yes I am using Mac M1 for 2.3.0 and get this error

**Comment by filip-halt** [comment]
> > For x86 version, the CPU is too old and not suitable. You need to check the `Flags` of `lscpu`, at least it should support sse4.2 instruction set.
> > For arm version, you can use it directly.
> 
> Yes I am using Mac M1 for 2.3.0 and get this error


@liliu-z Anyone run into this running Apple hardware in Knowhere? bad_alloc()

**Comment by jiaoew1991** [comment]
> > For x86 version, the CPU is too old and not suitable. You need to check the `Flags` of `lscpu`, at least it should support sse4.2 instruction set.
> > For arm version, you can use it directly.
> 
> Yes I am using Mac M1 for 2.3.0 and get this error

@superpandaaa Are you using the ARM version image or the x86 version image? It is fine to use the ARM version image on Mac. 🤔

**Comment by superpandaaa** [comment]
I use the docker compose file [here](https://milvus.io/docs/install_standalone-docker.md) so i think it is ARM version right.

**Comment by jiaoew1991** [comment]
> > For x86 version, the CPU is too old and not suitable. You need to check the `Flags` of `lscpu`, at least it should support sse4.2 instruction set.
> > For arm version, you can use it directly.
> 
> Yes I am using Mac M1 for 2.3.0 and get this error

You can use the command to inspect the architecture
```
docker inspect --format='{{index .Os}}/{{index .Architecture}}' <image_name_or_id>
```

**Comment by superpandaaa** [comment]
> > > For x86 version, the CPU is too old and not suitable. You need to check the `Flags` of `lscpu`, at least it should support sse4.2 instruction set.
> > > For arm version, you can use it directly.
> > 
> > 
> > Yes I am using Mac M1 for 2.3.0 and get this error
> 
> You can use the command to inspect the architecture
> 
> ```
> docker inspect --format='{{index .Os}}/{{index .Architecture}}' <image_name_or_id>
> ```

it returns me `linux/amd64`, is that correct version?

**Comment by jiaoew1991** [comment]
> > > > For x86 version, the CPU is too old and not suitable. You need to check the `Flags` of `lscpu`, at least it should support sse4.2 instruction set.
> > > > For arm version, you can use it directly.
> > > 
> > > 
> > > Yes I am using Mac M1 for 2.3.0 and get this error
> > 
> > 
> > You can use the command to inspect the architecture
> > ```
> > docker inspect --format='{{index .Os}}/{{index .Architecture}}' <image_name_or_id>
> > ```
> 
> it returns me `linux/amd64`, is that correct version?

It means you are using x86 version

**Comment by xiaofan-luan** [comment]
for mac m1, you have to use arm image

**Comment by xiaofan-luan** [comment]
because milvus 2.3 support arm, it's actually runs much faster
