### ISSUE TITLE
[Bug]: got segv during `search segment without index`

### ISSUE THREAD

**Issue by weiliu1031** [milvus-io/milvus#26968]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.14
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/108661493/4c13bf5c-8090-4119-a45f-ebda339391de)

got segv during `search segment without index`

**Comment by yanliang567** [comment]
@weiliu1031 any updates

**Comment by weiliu1031** [comment]
> @weiliu1031 any updates

can't reproduce it in local env, and lack of logs before segv
