### ISSUE TITLE
[Bug]: Collection loaded metrics is not accurate 

### ISSUE THREAD

**Issue by athletic-geek** [milvus-io/milvus#26969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.0
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):  pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

In Attu dashboard, loaded collection number is 6, all collection number is 8,
In Prometheus, milvus_rootcoord_collection_num is 10
`sum(milvus_rootcoord_collection_num{app_kubernetes_io_instance="my-release", app_kubernetes_io_name="milvus",kubernetes_namespace="milvus"}) by (app_kubernetes_io_instance)`

### Expected Behavior

milvus_rootcoord_collection_num is supposed to be 8

**Comment by xiaofan-luan** [comment]
/assign @xige-16 
please help on correct the monitoring metrics

**Comment by yanliang567** [comment]
@xige-16 any updates
