### ISSUE TITLE
All api need code status in http api response

### ISSUE THREAD

**Issue by nameczz** [milvus-io/milvus#2699]
**Is your feature request related to a problem? Please describe.**
Some API like :
GET /collections  
GET /devices
GET /system/config
PUT /collections/{segment}/vectors
GET /collections/{collection_name}/partitions
GET /collections/{collection_name}
...more api

**Describe the solution you'd like**
return response like:
{
   code: 0,
   data: ....
}

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by BossZou** [comment]
I see. I may need add field 'code' and 'message' in response to indicate what happend in server?
