### ISSUE TITLE
[DOC] Update roadmap

### ISSUE THREAD

**Issue by JinHai-CN** [milvus-io/milvus#270]
## Report incorrect documentation

**Location of incorrect documentation**
https://milvus.io/docs/en/roadmap/

**Describe the problems or issues found in the documentation**
According to the new plan, we need to update the roadmap and lots of new feature will be included in the roadmap.

**Comment by jielinxu** [comment]
The Roadmap topic before v0.6.0 is already deprecated. Will publish new Roadmap 2020 Q1 soon.
