### ISSUE TITLE
[Bug]: Pulsar Bookie keeps piling up logs under "ledger" causing Disk to run of space

### ISSUE THREAD

**Issue by ganderaj** [milvus-io/milvus#27003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.11
- Deployment mode(standalone or cluster): Cluster
- MQ type(rocksmq, pulsar or kafka): Pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): v2.2.15
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

PVC backing up ledgers for Pulsar Bookie was initially set to 200G and our Milvus has 1 DB with  ~1000 Vectors which consumed the whole 200G Disk. We have provisioned our cluster per Milvus Sizing Tool for 1M vectors and yet it breaks for  1000vectors.

We have noticed several xx.log files of each 1.1G in size.

### Expected Behavior

Pulsar Bookie scavenges ledger data as applicable and do not consume disk at this rapid rate. 

### Milvus Log

[milvus-log-231011.tar.gz](https://github.com/milvus-io/milvus/files/12579690/milvus-log-231011.tar.gz)

### Anything else?

Could you please help us with the below ?

- What does the Pulsar Bookie Ledger signify for Milvus ? What triggers creation of such xx.log files ?
- What is the typical log retention for such data ?
- Hopefully, attached log helps you with our cluster configuration and what's wrong with Pulsar. Apparently, a cluster with mere 1000 vectors consumed 200G for Pulsar ledgers. What is the ideal disk consumption and any recommended configurations ?

Your help is appreciated.

**Comment by LoveEachDay** [comment]
@ganderaj From the attached log, we can see that you have many collections, which we'll store internal data for each collection in the message queue. That's why pulsar ledger will consume so many disk space.

**Comment by LoveEachDay** [comment]
You can try to lower the pulsar retention settings (in pulsar broker), by default it will keep another 7 days after all the messages are consumed. You can change this to one day like this:
```
defaultRetentionTimeInMinutes: "1440"
```

**Comment by ganderaj** [comment]
> @ganderaj From the attached log, we can see that you have many collections, which we'll store internal data for each collection in the message queue. That's why pulsar ledger will consume so many disk space.

There was another DB with 600+collections but that was not being used and now dropped.

Is it safe to assume as collections increase ledger data also increases ? What does triggers data creation ?

**Comment by ganderaj** [comment]
> You can try to lower the pulsar retention settings (in pulsar broker), by default it will keep another 7 days after all the messages are consumed. You can change this to one day like this:
> 
> ```
> defaultRetentionTimeInMinutes: "1440"
> ```

How do we pass this configuration ? Is the below right way to push the change ?

`extraConfigFiles:
  user.yaml: |+
    pulsar:
      defaultRetentionTimeInMinutes: "1440"`

**Comment by LoveEachDay** [comment]
If you use milvus-helm, you can set in the `values.yaml` like this:
```
pulsar:
  broker:
    configData:
        defaultRetentionTimeInMinutes: "1440"
```

**Comment by ganderaj** [comment]
Appreciate your prompt response. Will make changes as advised.

Can you please let us know whether is 200G in ledger data expected for ~800 collections and ~2K vectors ? What is the purpose of this data and/or what causes the creation ?

**Comment by LoveEachDay** [comment]
@ganderaj To maintain data consistency level, rootcoord will periodically(every 200ms) sent time-tick message into all the topic where collection dml channel reside.

**Comment by ganderaj** [comment]
We have noticed that our Pulsar Ledger logs are close to a **TB**. What can we do to avoid such pile up of Pulsar Logs. Do we really need these logs ? Can you help us in avoiding piling up Pulsar logs ?

![milvus_pular_ledger_logs](https://github.com/milvus-io/milvus/assets/41026744/9c18ad6d-17dd-4cc6-aa91-34fd7209f5a6)
