### ISSUE TITLE
[Bug]: How to recover from an inconsistent state

### ISSUE THREAD

**Issue by Donglong** [milvus-io/milvus#27006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.13
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.2.13
- Minio: aliyun
```

### Current Behavior

report an error when loading collection: NoSuchKey

### Expected Behavior

successfully loaded data

**Comment by yanliang567** [comment]
try to restart the querycoord and release and reload the collection. If it does not help, please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation.

/assign @Donglong 
/unassign

**Comment by 344310362** [comment]
connection : keep-alive
content-length : 385
content-type : application/xml
date : Tue, 12 Sep 2023 02:36:03 GMT
server : AliyunOSS
x-amz-request-id : 64FFCE93CF2DD13130C82E8A
x-oss-ec : 0026-00000001
x-oss-err : PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPEVycm9yPgogIDxDb2RlPk5vU3VjaEtleTwvQ29kZT4KICA8TWVzc2FnZT5UaGUgc3BlY2lmaWVkIGtleSBkb2VzIG5vdCBleGlzdC48L01lc3NhZ2U+CiAgPFJlcXVlc3RJZD42NEZGQ0U5M0NGMkREMTMxMzBDODJFOEE8L1JlcXVlc3RJZD4KICA8SG9zdElkPms4cy1taWx2dXMub3NzLWNuLWJlaWppbmctaW50ZXJuYWwuYWxpeXVuY3MuY29tPC9Ib3N0SWQ+CiAgPEtleT5wcm9kL2luc2VydF9sb2cvNDQzNzI4OTM1MzA4NzAyMzExLzQ0MzcyODkzNTMwODcwMjMxMi80NDM3Mjg5MzUzMTE0NzE2OTkvMC80NDM3Mjg5MzUzMTE0NzUwMjM8L0tleT4KICA8RUM+MDAyNi0wMDAwMDAwMTwvRUM+CjwvRXJyb3I+Cg==
x-oss-server-time : 3

[2023/09/12 02:36:03.414 +00:00] [WARN] [querynode/cgo_helper.go:56] ["LoadFieldData failed, C Runtime Exception: [UnexpectedError] Error:GetObjectSize[errcode:404, exception:, errmessage:No response body.]\n"]
[2023/09/12 02:36:03.420 +00:00] [ERROR] [querynode/segment_loader.go:204] ["load segment failed when load data into memory"] [collectionID=443728935308702311] [segmentType=Growing] [partitionID=443728935308702312] [segmentID=443728935311471699] [error="[UnexpectedError] Error:GetObjectSize[errcode:404, exception:, errmessage:No response body.]"] [stack="github.com/milvus-io/milvus/internal/querynode.(*segmentLoader).LoadSegment.func3\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/segment_loader.go:204\ngithub.com/milvus-io/milvus/internal/util/funcutil.ProcessFuncParallel.func3\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/parallel.go:83"]
[2023/09/12 02:36:03.420 +00:00] [ERROR] [funcutil/parallel.go:85] [loadSegmentFunc] [error="[UnexpectedError] Error:GetObjectSize[errcode:404, exception:, errmessage:No response body.]"] [idx=0] [stack="github.com/milvus-io/milvus/internal/util/funcutil.ProcessFuncParallel.func3\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/parallel.go:85"]
[2023/09/12 02:36:03.420 +00:00] [INFO] [gc/gc_tuner.go:84] ["GC Tune done"] ["previous GOGC"=200] ["heapuse "=23] ["total memory"=57] ["next GC"=49] ["new GOGC"=200] [gc-pause=76.081µs] [gc-pause-end=1694486163418873529]
[2023/09/12 02:36:03.420 +00:00] [INFO] [querynode/segment.go:320] ["delete segment from memory"] [collectionID=443728935308702311] [partitionID=443728935308702312] [segmentID=443728935311471699] [segmentType=Growing]
2023-09-12 02:36:03,420 | INFO | default | [SEGCORE][ProcessFormattedStatement][milvus] [AWS LOG] [ERROR] 2023-09-12 02:36:03.420 AWSClient [140537206048512] HTTP response code: 404
Resolved remote host IP address: 100.118.58.6

**Comment by Donglong** [comment]
@yanliang567
[milvus_logs.zip](https://github.com/milvus-io/milvus/files/12582080/milvus_logs.zip)

**Comment by Donglong** [comment]
could you tell me what the problem is and how to fix it quickly by me？ @yanliang567

**Comment by Donglong** [comment]
> I guess maybe because of config useVirtualHost, in 2.2.13, we add new parameters. ![image](https://user-images.githubusercontent.com/11935707/267294601-cd44c6e1-cf26-42d3-9bf8-85ea5e24c402.png) and for oss, only support true, set this parameter to true and try it again

yes. the item has been set to true. and there is no error in test env, but we encountered this error in prod env.

**Comment by Donglong** [comment]
is there any other solution? @jiaoew1991 @zhagnlu @yanliang567

**Comment by xiaofan-luan** [comment]
Error:GetObjectSize
you can search for this error.
this usually means the object storage is not setup correctly

**Comment by Donglong** [comment]
> Error:GetObjectSize you can search for this error. this usually means the object storage is not setup correctly

I created a collection and it was working normally, but suddenly it failed to load and gave me this error. this is all i know and don't know how to reproduce it.  @xiaofan-luan

**Comment by xiaofan-luan** [comment]
> > Error:GetObjectSize you can search for this error. this usually means the object storage is not setup correctly
> 
> I created a collection and it was working normally, but suddenly it failed to load and gave me this error. this is all i know and don't know how to reproduce it. @xiaofan-luan

It works becasue you are doing flush and has to communication with S3.

you need to figure object storage correctly. There are a lot of similar issue and please search on them

**Comment by Donglong** [comment]
I don’t quite understand. Is this a usage issue or a deployment issue?

**Comment by xiaofan-luan** [comment]
> I don’t quite understand. Is this a usage issue or a deployment issue?

Yes, your S3 is not configured correctly

**Comment by Donglong** [comment]
![image](https://github.com/milvus-io/milvus/assets/13818608/56868baf-987b-41a1-a830-267ad0a8eca6)
This is my config, is there any problem?

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan
> 
> I have same issue.
> 
> The first collection load went well, but after the query node rollout restart, the "load segment failed when load data into memory" error occurs.
> 
> ```
> [error="[UnexpectedError] Error:GetObjectSize[errcode:404, exception:, errmessage:No response body.]"]
> ```
> 
> It worked fine on the first load, but why am I getting errors after restarting the query node?

It happens because your object storage is misconfigured.

on Milvus 2.3.3 we add more default configs to help on the object configuraitons.

We've seen that it might be reason of failed to set correct minio port, or forget to setup useVirtualHost Params

**Comment by Uijeong97** [comment]
@xiaofan-luan

Thank you for your answer.

What exactly do you mean by using a virtual host?
I'm having a hard time understanding it.

> It happens because your object storage is misconfigured.
on Milvus 2.3.3 we add more default configs to help on the object configuraitons.
We've seen that it might be reason of failed to set correct minio port, or forget to setup useVirtualHost Params

In my situation, I was able to access S3 on the first load, 
but when I tried to re-release it, I got an error.
so I don't think there was something wrong with the miniport settings. 

Can you tell me what the use virtual host option does in this situation?

**Comment by yanliang567** [comment]
it is a minio config in milvus.yaml
![image](https://github.com/milvus-io/milvus/assets/82361606/0a929fb3-610f-428d-a92f-54ff34ee326d)
In Milvus 2.3.3, you don't have to configure it any more, as milvus will automatically pick a working value for you
