### ISSUE TITLE
[Bug]: HA test problem. pods are not restarting.

### ISSUE THREAD

**Issue by Rachel-42maru** [milvus-io/milvus#27019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.0
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): kafka
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v.2.3.0
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I deployed milvus cluster with helm on 3 GCP vm nodes.
I've been doing HA test by stopping kubelet or vm itself. I'm expecting terminated pods(etcd, minio, kafaka, etc...) restart on other 2 nodes, and milvus is working well.
But kafka, minio, etcd terminating pods are not assgined to another pod. Also, when node or coord pods are restarted, loading collection is not completely done. I tested the cases of 3 coords & 1 node, 1 coord & 3 nodes, and 1 coord & 1 node.

![image (1)](https://github.com/milvus-io/milvus/assets/63443220/0c36557d-d5bb-4e90-b132-fcacc9cc9be4)

Is there any proper setting to apply milvus on production level?
Let me know if it needs certain pod logs to look at it. I have logs of every pods based on github log script you provided, but it's too many to upload on git.

### Expected Behavior

 I'm expecting terminated pods(etcd, minio, kafaka, etc...) restart on other 2 nodes, and milvus is working well when one of worker nodes goes down.

**Comment by yanliang567** [comment]
@Rachel-42maru great to hear that you are running HA tests. Could you please share more detailed steps, more details about your milvus configurations, and more details about the collection info,  about how you did the test? Technically all the terminated pods are going to be re-assigned to spare nodes by k8s, no matter they are milvus pods or any other pods. I guess there are not enough resource for all the pods to re-located onto the 2 exiting nodes. 

/assign @Rachel-42maru 
/unassign

**Comment by Rachel-42maru** [comment]
I have 1 master node and 3 worker nodes. I purposely stopped kubelet to see milvus cluster HA.

**Comment by Rachel-42maru** [comment]
I made collection with two fields. One for id, with scalar index, and one for embedding, with vector index (FLAT/ IP).
Collections are not loaded properly after terminating one worker node.

**Comment by Rachel-42maru** [comment]
Test Steps:
1. Install milvus cluster with helm on One Master node & Three Worker nodes.
2. Pods are assigned on worker nodes only, and pv, pvc are made  with nfc pv clients.
![image (2)](https://github.com/milvus-io/milvus/assets/63443220/2a987fcc-37f6-4107-84f6-3036580b83f2)

3. When every pods are running, I killed kubelet on one worker node. One of every kafka, etcd, zookeeper, minio are terminating. Also, nodes and coords which were one not-ready worker node are terminated. Node and coords pods are assigned on another ready worker node. 
![image (1)](https://github.com/milvus-io/milvus/assets/63443220/ef8af6de-c196-417c-9b74-194075b7281b)

However, terminating node of kafka, etcd, zookeeper, minio are not assgined on another ready worker node,
and then, milvus are not working properly. Creating new collection, loading collection, etc... all functions are not working, except searching already loaded collection.
 
Let me know if you need any logs.

**Comment by yanliang567** [comment]
as kafka, etcd  etc, dependent services are clustered deployment, I don't think milvus should not work if there are only one of dependent pods are down. @Rachel-42maru Could you please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @LoveEachDay 
could you please help to take a look?

**Comment by Rachel-42maru** [comment]
[logs.tar.gz](https://github.com/milvus-io/milvus/files/12592025/logs.tar.gz)
This is full logs when one node turned into not ready.

**Comment by xiaofan-luan** [comment]
> Test Steps:
> 
> 1. Install milvus cluster with helm on One Master node & Three Worker nodes.
> 2. Pods are assigned on worker nodes only, and pv, pvc are made  with nfc pv clients.
> 
> ![image (3)](https://user-images.githubusercontent.com/63443220/267272494-6d807d71-2ccd-4435-94f5-9c2073a0bf51.png)
> 
> 3. When every pods are running, I killed kubelet on one worker node. One of every kafka, etcd, zookeeper, minio are terminating. Also, nodes and coords which were one not-ready worker node are terminated. Node and coords pods are assigned on another ready worker node.
> 
> ![image (1)](https://user-images.githubusercontent.com/63443220/267267830-ef8af6de-c196-417c-9b74-194075b7281b.png)
> 
> However, terminating node of kafka, etcd, zookeeper, minio are not assgined on another ready worker node, and then, milvus are not working properly. Creating new collection, loading collection, etc... all functions are not working, except searching already loaded collection.
> 
> Let me know if you need any logs.
> 
> /assign @yanliang567 /unassign

I thought this should be handled by k8s itself to bring up new etcd node and minio node.
If not did you check your k8s logs of why?

**Comment by xiaofan-luan** [comment]
this is definitely not related to milvus but more about how you setup your cluster.
Also with one node down, all the milvus service should be recovered later

**Comment by xiaofan-luan** [comment]
My guess is you don't have enough resource to allocate those pods to with only 2 vm left.

**Comment by LoveEachDay** [comment]
@Rachel-42maru Pods with Terminating status won't be deleted only after the original worker node back to online. You can delete the pod in terminating status forcefully.

For dependencies like minio, etcd and kafka, the pods are controller by statefulset which required the old pods to be deleted, then new pod can be scheduled. In your case, the old pods like `milvus-cluster-etcd-0` won't be deleted automatically, so `milvus-cluster-etcd-0` cannot be reassigned to a new worker node.

And for the default settings from milvus-helm, milvus can tolerate one pod of each dependencies unavailable.

**Comment by xiaofan-luan** [comment]
> @Rachel-42maru Pods with Terminating status won't be deleted only after the original worker node back to online. You can delete the pod in terminating status forcefully.
> 
> For dependencies like minio, etcd and kafka, the pods are controller by statefulset which required the old pods to be deleted, then new pod can be scheduled. In your case, the old pods like `milvus-cluster-etcd-0` won't be deleted automatically, so `milvus-cluster-etcd-0` cannot be reassigned to a new worker node.
> 
> And for the default settings from milvus-helm, milvus can tolerate one pod of each dependencies unavailable.

So what is the best way to chaos test kafka? any ideas/
