### ISSUE TITLE
[Bug]: Proxy,querycoord and datanode can not be recovery after etcd follower pod failure chaos 

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#27021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230911-ac45af58
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/12268675/ac026709-293b-4cd1-8932-0edbc0e51ff6)

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-cron/detail/chaos-test-kafka-cron/7295/pipeline

log:
[artifacts-etcd-followers-pod-failure-7295-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/12583372/artifacts-etcd-followers-pod-failure-7295-pytest-logs.tar.gz)

[artifacts-etcd-followers-pod-failure-7295-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/12583373/artifacts-etcd-followers-pod-failure-7295-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
There are many querycoord panic problems. It may happen when no chaos is applied, after the chaos is deleted, or during tests after the chaos is deleted.

**Comment by zhuwenxing** [comment]
This is also reproduced in 2.3.0-20230911-30003e83
![image](https://github.com/milvus-io/milvus/assets/12268675/54573016-0649-4896-8a53-118481e94a6b)

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release-cron/detail/chaos-test-kafka-for-release-cron/7256/pipeline

log:
[artifacts-etcd-followers-pod-failure-7256-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/12583660/artifacts-etcd-followers-pod-failure-7256-pytest-logs.tar.gz)
[artifacts-etcd-followers-pod-failure-7256-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/12583662/artifacts-etcd-followers-pod-failure-7256-server-logs.tar.gz)

**Comment by weiliu1031** [comment]
for now, milvus behavior is not as expected after kill etcd. for datanode, it will lost connection with etcd, then try to retry keep alive logic, but the retry won't success, cause it will retry to the killed etcd until context deadline, then datanode will kill itself.

during etcd chaos progress, this will happens again and again

**Comment by zhuwenxing** [comment]
2.3.0-20230918-dde27711-amd64

![image](https://github.com/milvus-io/milvus/assets/12268675/26f82f54-a4f1-49a4-b7aa-dc516d4de3df)


failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release-cron/detail/chaos-test-for-release-cron/7333/pipeline

log:

[artifacts-etcd-pod-failure-7333-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/12655632/artifacts-etcd-pod-failure-7333-pytest-logs.tar.gz)
[artifacts-etcd-pod-failure-7333-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/12655633/artifacts-etcd-pod-failure-7333-server-logs.tar.gz)

**Comment by xiaofan-luan** [comment]
how many etcd nodes?

I'm hightly doubing kill 1 etcd follower on a 3 etcd deployment affect lease renew

**Comment by weiliu1031** [comment]
> how many etcd nodes?
> 
> I'm hightly doubing kill 1 etcd follower on a 3 etcd deployment affect lease renew

3 etcd node, and kill 2 node during chaos progress.

**Comment by weiliu1031** [comment]
> > how many etcd nodes?
> > I'm hightly doubing kill 1 etcd follower on a 3 etcd deployment affect lease renew
> 
> 3 etcd node, and kill 2 node during chaos progress.

![07a43dcb-9825-431c-be45-6a0f5204eac9](https://github.com/milvus-io/milvus/assets/108661493/c71f68e2-5270-4933-a8cc-0336bc4440fa)

proxy restart due to panic, then proxy can't recover, because proxy can't get dc's session during init pogress.

**Comment by xiaofan-luan** [comment]
> > how many etcd nodes?
> > I'm hightly doubing kill 1 etcd follower on a 3 etcd deployment affect lease renew
> 
> 3 etcd node, and kill 2 node during chaos progress.

etcd can not support kill 2 node

**Comment by weiliu1031** [comment]
> > > how many etcd nodes?
> > > I'm hightly doubing kill 1 etcd follower on a 3 etcd deployment affect lease renew
> > 
> > 
> > 3 etcd node, and kill 2 node during chaos progress.
> 
> etcd can not support kill 2 node
ok, i will fix the proxy's panic first

**Comment by xiaofan-luan** [comment]
I think for etcd we have to wait for quorum

**Comment by weiliu1031** [comment]
> quorum

if etcd suffer a failure period, such as most follower has been killed, after all etcd  follower recovered, milvus can't recovered, is it expected?

**Comment by xiaofan-luan** [comment]
> > quorum
> 
> if etcd suffer a failure period, such as most follower has been killed, after all etcd follower recovered, milvus can't recovered, is it expected?

milvus should recovered after etcd fully recovered.

**Comment by xiaofan-luan** [comment]
node up doesn't mean etcd is recovered.
If Milvus didn't recover after 3 minutes after etcd fully worked this might be an issue

**Comment by zhuwenxing** [comment]
>milvus should recovered after etcd fully recovered.

This issue is this case. Milvus did not recover when etcd already running and waited for 3 minutes
