### ISSUE TITLE
[Bug]: Using disk index, 10million vector load failed

### ISSUE THREAD

**Issue by neblen** [milvus-io/milvus#27031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.14
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Debian GNU/Linux 11 (bullseye)
- CPU/Memory: CPU 
- GPU: 
- Others:
```

### Current Behavior

When there are 10 million vectors in the collection, load will fail.
**Note that when load fails, all pods are not restarted except attu pod.
When the 10 million data load fails, if the small batch data can load succeefully, the time will be very slow.**
warn log is as follows.
```
[2023/09/12 08:27:58.815 +00:00] [INFO] [querynode/flow_graph_insert_node.go:320] [processDeleteMessage] [vchannel=by-dev-rootcoord-dml_2_443927634084115734v0] [segmentIDs="[]"] [paritions="[0]"]
[2023/09/12 08:27:58.884 +00:00] [INFO] [querynode/impl_utils.go:30] ["LoadSegment start to transfer load with shard cluster"] [traceID=26f9d476022fef8a] [shard=by-dev-rootcoord-dml_6_443927634086918564v0] [segmentIDs="[443927634097367836,443927634097380680,443927634097378257,443927634097374364,443927634097376777,443927634097369345,443927634097363913,443927634097370769]"]
[2023/09/12 08:27:58.884 +00:00] [WARN] [querynode/shard_cluster.go:516] ["node not in cluster"] [collectionID=443927634086918564] [channel=by-dev-rootcoord-dml_6_443927634086918564v0] [replicaID=443927720062877702] [dstNodeID=766] [segmentIDs="[443927634097367836,443927634097380680,443927634097378257,443927634097374364,443927634097376777,443927634097369345,443927634097363913,443927634097370769]"]
[2023/09/12 08:27:58.884 +00:00] [WARN] [querynode/impl_utils.go:61] ["shard cluster failed to load segments"] [traceID=26f9d476022fef8a] [shard=by-dev-rootcoord-dml_6_443927634086918564v0] [segmentIDs="[443927634097367836,443927634097380680,443927634097378257,443927634097374364,443927634097376777,443927634097369345,443927634097363913,443927634097370769]"] [error="node not in cluster 766"]
[2023/09/12 08:27:58.966 +00:00] [INFO] [querynode/flow_graph_insert_node.go:320] [processDeleteMessage] [vchannel=by-dev-rootcoord-dml_1_443927634083230773v0] [segmentIDs="[]"] [paritions="[0]"]
```
![image](https://github.com/milvus-io/milvus/assets/49058548/05e30031-476e-4e3c-a926-84f48852b4e8)

### Expected Behavior

Even if the loading time is long, 10 million vectors can be loaded successfully

### Steps To Reproduce

```markdown
1.build a collection with disk index
2.insert 1000W vector 
3.collection load 
code as follows 
    wds_id_lists = split_list(wds_id_list[0:10000], 1000)
    for index, wds_ids in enumerate(wds_id_lists):
            id_total = []
            for i in range(1000):
                id_total.append(index * 1000 * 1000 + wds_index * 1000 + i + 4178000)
            wds_id_total = [wds_id for i in range(1, 1000 + 1)]
            data_npy_content_list = np.load(data_npy_sub_path)
            data_entities = [id_total, data_txt_total, wds_id_total, data_npy_content_list.tolist()]
            collection.insert(data_entities)
    collection.flush()
    collection.load()
```
```


### Milvus Log

[milvus-querynode.log](https://github.com/milvus-io/milvus/files/12586099/milvus-querynode.log)


### Anything else?

_No response_

**Comment by yanliang567** [comment]
@neblen are you sure there are enough free memory for querynode to load all the collections? Could you please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
/assign @neblen 
/unassign

**Comment by neblen** [comment]
> @neblen are you sure there are enough free memory for querynode to load all the collections? Could you please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation? /assign @neblen /unassign

Okay, I'll export a log as soon as possible

**Comment by neblen** [comment]
[milvus-log-093102-0.tar.gz](https://github.com/milvus-io/milvus/files/12594410/milvus-log-093102-0.tar.gz)
[milvus-log-093102-1.tar.gz](https://github.com/milvus-io/milvus/files/12594413/milvus-log-093102-1.tar.gz)
[milvus-log-093102-2.tar.gz](https://github.com/milvus-io/milvus/files/12594415/milvus-log-093102-2.tar.gz)
I divided the tar.gz file into 3 parts and used the following command to merge the 3 files into one.
```
cat  milvus-log-093102-* > milvus-log-093102.tar.gz
```

**Comment by smellthemoon** [comment]
the warn log "shard cluster failed to load segments" means that the request is visiting the old node, always happened when node down. It's ok to warn that.
the root cause is that load is timeout. The load index  time of some segment  is 30-40 min cause that.
<img width="747" alt="1" src="https://github.com/milvus-io/milvus/assets/64083300/41b2025d-bbbe-40f1-8973-06f5f27db7e8">

**Comment by neblen** [comment]
> the warn log "shard cluster failed to load segments" means that the request is visiting the old node, always happened when node down. It's ok to warn that. the root cause is that load is timeout. The load index time of some segment is 30-40 min cause that. <img alt="1" width="747" src="https://user-images.githubusercontent.com/64083300/270217137-41b2025d-bbbe-40f1-8973-06f5f27db7e8.png">

I have a confusion: Is there any way to load successfully?   For example, 10 million vectors are loaded in batches of segments. After a part is successfully loaded, all of them cannot be loaded successfully. 
I have tried loading 10million data by disk index many times. Generally, the log shows that Using sample queries to generate cache time is about 1600s.
![image](https://github.com/milvus-io/milvus/assets/4905854
There is also a log here of the recent load failure.Would you please take a look again?

[milvus-querynode-6679bd4775-nwls6-1000w-alllog.log](https://github.com/milvus-io/milvus/files/12710719/milvus-querynode-6679bd4775-nwls6-1000w-alllog.log)

**Comment by smellthemoon** [comment]
> > the warn log "shard cluster failed to load segments" means that the request is visiting the old node, always happened when node down. It's ok to warn that. the root cause is that load is timeout. The load index time of some segment is 30-40 min cause that. <img alt="1" width="747" src="https://user-images.githubusercontent.com/64083300/270217137-41b2025d-bbbe-40f1-8973-06f5f27db7e8.png">
> 
> Thanks for your reply~ I have a confusion: Is there any way to load successfully? For example, 10 million vectors are loaded in batches of segments. After a part is successfully loaded, all of them cannot be loaded successfully. I have tried loading 10million data by disk index many times. Generally, the log shows that Using sample queries to generate cache time is about 1600s.The load time will not be affected, as long as the load is successful.
> 
> ![image](https://user-images.githubusercontent.com/49058548/270219251-095c677c-68cc-41d5-8f00-a4a36294bd99.png)
> 
> There is also a log here of the recent load failure.Would you please take a look again?
> 
> [milvus-querynode-6679bd4775-nwls6-1000w-alllog.log](https://github.com/milvus-io/milvus/files/12710719/milvus-querynode-6679bd4775-nwls6-1000w-alllog.log)

Thanks for your help. It seems that the time of generate cache is not normal cause load not success, I will persistently investigate and solve it.

**Comment by smellthemoon** [comment]
@cqy123456 could you please take look a look the time of generate cache in spare time? Thanks.
