### ISSUE TITLE
[Bug]: Drop collection does not clear entries from S3 bucket

### ISSUE THREAD

**Issue by wmwsagara** [milvus-io/milvus#27034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.14
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.2.14
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: i5/16GB
- GPU: None
- Others: None
```

### Current Behavior

1. I ran https://raw.githubusercontent.com/milvus-io/pymilvus/master/examples/hello_milvus.py
2. After the hello_milvus.py run, I listed the S3 bucket, there are 10 entries. Bucket was empty before run the program.

Here are the bucket contents:
Bucket: test-milvus
File: files/delta_log/444208219715282054/444208219715282055/444208219715482064/444208219715482151, Size: 615, Created Date: 2023-09-12 12:29:17.888000+00:00
File: files/index_files/444208219715482091/1/444208219715282055/444208219715482064/IVF, Size: 10159, Created Date: 2023-09-12 12:29:09.040000+00:00
File: files/index_files/444208219715482091/1/444208219715282055/444208219715482064/RAW_DATA, Size: 87389, Created Date: 2023-09-12 12:29:09.061000+00:00
File: files/insert_log/444208219715282054/444208219715282055/444208219715482064/0/444208219715482080, Size: 8046, Created Date: 2023-09-12 12:29:07.997000+00:00
File: files/insert_log/444208219715282054/444208219715282055/444208219715482064/1/444208219715482081, Size: 458, Created Date: 2023-09-12 12:29:08.088000+00:00
File: files/insert_log/444208219715282054/444208219715282055/444208219715482064/100/444208219715482077, Size: 6843, Created Date: 2023-09-12 12:29:07.522000+00:00
File: files/insert_log/444208219715282054/444208219715282055/444208219715482064/101/444208219715482078, Size: 28960, Created Date: 2023-09-12 12:29:07.667000+00:00
File: files/insert_log/444208219715282054/444208219715282055/444208219715482064/102/444208219715482079, Size: 101020, Created Date: 2023-09-12 12:29:07.817000+00:00
File: files/stats_log/444208219715282054/444208219715282055/444208219715482064/100/444208219715482082, Size: 5627, Created Date: 2023-09-12 12:29:08.179000+00:00

### Expected Behavior

The expected behaviour was the bucket to be empty since the bucket was empty before run the program.

**Comment by xiaofan-luan** [comment]
it will be cleanuped up asyncly.
@wmwsagara

**Comment by xiaofan-luan** [comment]
you may expect it to cleanedup after 1 day by default if I'm correct

**Comment by yanliang567** [comment]
/assign @wmwsagara 
as comments above

**Comment by wmwsagara** [comment]
Thanks for the replies.

I re-ran the hello_milvus. I'll check again the S3 bucket after 24hrs and update here.

**Comment by wmwsagara** [comment]
Yes, after 24hrs, the S3 bucket got cleared. Note, this is for drop collection. I want to do another test for delete entries without drop the collection.

**Comment by yanliang567** [comment]
> Yes, after 24hrs, the S3 bucket got cleared. Note, this is for drop collection. I want to do another test for delete entries without drop the collection.

Then I suggest you delete 20%+ entities to ensure the segment compaction triggered, so that the dropped segments will be clean up on S3.

**Comment by wmwsagara** [comment]
Yes. Deleted more than 20%. One block of entries was on the before image now gone from the S3 bucket. So I can conclude deleting entries without drop the collection get cleared off from the S3 bucket. Thanks.

**Comment by wmwsagara** [comment]
I close this as no issue.
