### ISSUE TITLE
There is no functions to get milvus SegmentName in milvus-jdk 0.8.1,but which is supported in milvus-jdk 0.7.0???

### ISSUE THREAD

**Issue by Swidasya** [milvus-io/milvus#2705]
As the title says, when I upgrade milvus from 0.8.0 to 0.9.1, the milvus-jdk upgrade from 0.7.0 to 0.8.1, but how can I get the SegmentSName?

I want to get all the milvusId by use 
`listIDInSegment(string collectionName, string segmentName)`

but there is no way to get segmentName....

**Comment by sahuang** [comment]
In Java SDK 0.8.1, you can use
`GetCollectionInfoResponse getCollectionInfoResponse = client.getCollectionInfo(collectionName);`
to obtain collection info, which is essentially a JSON string that contains partitions, segments in partitions and name of those segments.

Example output:
```json
{
	"partitions":[
		{
			"row_count":10000,
			"segments":[
				{
					"data_size":5200000,
					"index_name":"IDMAP",
					"name":"1587627144905721000",
					"row_count":10000
				}
			],
			"tag":"_default"
		}
	],
	"row_count":10000
}
```

Get the `"name"` in the segment you want and then call `listIDInSegment(string collectionName, string segmentName)`.

**Comment by sahuang** [comment]
In addition, you can refer to [SDK examples](https://github.com/milvus-io/milvus-sdk-java/blob/master/examples/src/main/java/MilvusClientExample.java#L143) and check program output. 

There's also some explanation for [getCollectionStats](https://milvus-io.github.io/milvus-sdk-java/javadoc/io/milvus/client/MilvusClient.html#getCollectionStats(java.lang.String)).
