### ISSUE TITLE
[Bug]: Lack a lot of message of collection.describe()

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#27055]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230913-4fa878d0
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.0
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Now, collection.describe() contains the following information:

{'collection_name': 'collection_2av13OaL', 'auto_id': False, 'num_shards': 1, 'description': '', 'fields': [{'field_id': 100, 'name': 'int64', 'description': '', 'type': 5, 'params': {}, 'is_primary': True}, {'field_id': 101, 'name': 'float', 'description': '', 'type': 10, 'params': {}}, {'field_id': 102, 'name': 'varchar', 'description': '', 'type': 21, 'params': {'max_length': 65535}}, {'field_id': 103, 'name': 'json_field', 'description': '', 'type': 23, 'params': {}}, {'field_id': 104, 'name': 'float_vector', 'description': '', 'type': 101, 'params': {'dim': 128}}], 'aliases': [], 'consistency_level': 0, 'properties': [], 'num_partitions': 1}

But before, collection.describe() also returns `is_partition_key`, `is_dynamic`, `enable_dynamic_field`.

### Expected Behavior

add necessary message.

**Comment by xiaofan-luan** [comment]
keep it

**Comment by xiaofan-luan** [comment]
/assign @smellthemoon 
could you help on this one?

**Comment by NicoYuan1986** [comment]
fixed. master-20231218-95ada1b6
