### ISSUE TITLE
RestFul Respon Error[Bug]: 

### ISSUE THREAD

**Issue by chenjinjun** [milvus-io/milvus#27073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.0
- Deployment mode:standalone 
- SDK version(pymilvus v2.3.0):
```

### Current Behavior

I found a bug. There is a field named id in my FiledName, and my primary key is named pk. I used the Python SDK to perform a similarity search and the value of the id in the data obtained was correct, but I used the search in RestFul. The id obtained by the interface directly returns the pk value of my primary key.

### Expected Behavior

The returned id is my own id instead of my primary key pk

### Anything else?

RESTful  Request

{
    "dbName": "fpvector",
    "collectionName": "FpProjectVector",
    "outputFields": ["id","pk", "pname", "text"],
    "vector":[0.5717199403518398,],
    "limit":1,
    "offset":0

}

------------------------------

RESTful  Respon

{
	"code": 200,
	"data": [
		{
			"distance": 0.22393069,
			"id": 444227901683519088,
			"pk": 444227901683519088,
			"pname": "xxxxx",
			"text": "xxxxx"
		}
	]
}

**Comment by yanliang567** [comment]
/assign @zhuwenxing 
please help to reproduce in house
/unassign

**Comment by yanliang567** [comment]
@zhuwenxing any updates?
