### ISSUE TITLE
[Feature]: 多向量

### ISSUE THREAD

**Issue by itzpm** [milvus-io/milvus#27070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

我想在一条数据中使用多个向量,想问一下milvus有这个打算吗?
如果有这个想法那么打算在哪个版本上线?
如果没有就当我没问
谢谢!!!

**Comment by jiaoew1991** [comment]
tracking it with https://github.com/milvus-io/milvus/issues/25639

**Comment by itzpm** [comment]
thanks

**Comment by itzpm** [comment]
> tracking it with #25639
How soon will the 2.4 release be available?
