### ISSUE TITLE
[Bug]: Deploying Milvus on a custom Namespace breaks Prometheus Targets thereby Grafana Dashboard

### ISSUE THREAD

**Issue by ganderaj** [milvus-io/milvus#27088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.11
- Deployment mode(standalone or cluster): Cluster
- MQ type(rocksmq, pulsar or kafka): Pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Going by the [Milvus Documentation](https://milvus.io/docs/monitor.md) to install Prometheus/Grafana and enabling ServiceMonitor will not work.

Default installation for Prometheus only supports _"default"_ and _"monitoring"_ namespaces and Roles and Rolebindings needs to be created explicitly to ensure Service Monitors are recognized by Prometheus.

For more information, check out https://github.com/milvus-io/milvus/discussions/26967

### Expected Behavior

Documentation should warn readers on the challenges with deploying milvus under custom namespace and include manifest files for Role and Rolebindings.

(or)

Helm chart for Milvus, [milvus-helm](https://github.com/zilliztech/milvus-helm) should include creation of Role and Rolebindings should a user choose `metrics.serviceMonitor.enabled=true` under values.yaml

**Comment by yanliang567** [comment]
@LoveEachDay any updates?

**Comment by LoveEachDay** [comment]
@ganderaj You'd better allow prometheus to monitoring `servicemonitor` in the namespace where your milvus cluster reside in. 

You may need a clusterrole for `prometheus operator` which will monitoring `servicemonitor` cr then updating the prometheus scraping targets.

**Comment by ganderaj** [comment]
> @ganderaj You'd better allow prometheus to monitoring `servicemonitor` in the namespace where your milvus cluster reside in.
> 
> You may need a clusterrole for `prometheus operator` which will monitoring `servicemonitor` cr then updating the prometheus scraping targets.

@LoveEachDay resolution is well discussed. I’ve opened this request so this gets documented and/or have the helm deployment updated to support creation of roles dynamically.
