### ISSUE TITLE
[Bug]: attu collecttion didn't show correctly if the collection is too long

### ISSUE THREAD

**Issue by master006** [milvus-io/milvus#27098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![企业微信截图_169467978844](https://github.com/milvus-io/milvus/assets/25217361/1d1ed30e-2b3d-43f4-aaf4-a39b528a4809)

**Comment by jiaoew1991** [comment]
It is more appropriate to move the issue in the attu repository. https://github.com/zilliztech/attu

**Comment by xiaofan-luan** [comment]
@master006 
also please use english for the convenience of other community members, thanks
