### ISSUE TITLE
[Bug]: attu report error if database didn't support list databases

### ISSUE THREAD

**Issue by master006** [milvus-io/milvus#27100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/25217361/dcaf2844-4de7-4894-a6d8-52fd1cca7c83)

**Comment by yanliang567** [comment]
@master006 please try upgrade attu then.
/assign @master006 
/unassign
