### ISSUE TITLE
[Bug]: Growing index judge whether indexing has raw data or not  after index has built

### ISSUE THREAD

**Issue by foxspy** [milvus-io/milvus#27104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

`HasRawData` could only be determined after index building because some indexes holding raw data or not  are determined by the build config. With knowhere PR https://github.com/zilliztech/knowhere/pull/77, `HasRawData` will directly return false when index has not built, and `Knowhere Auto Commit` ut failed https://github.com/milvus-io/milvus/pull/27067. This will trigger the bug of `HasRawData` judgement in segcore as follows, when index has not built, then `indexing.has_raw_data()` will return false but growing segment can retrieve data from raw chunk data. 
```
 HasRawData(FieldId fieldId) const {
        if (is_in(fieldId)) {
            const FieldIndexing& indexing = get_field_indexing(fieldId);
            return indexing.has_raw_data();
        }
        return false;
    }
```

**Comment by foxspy** [comment]
@yanliang567 PR merged and knowhere auto commit successed with this PR.

**Comment by yanliang567** [comment]
close as comments above
