### ISSUE TITLE
[Bug]:  The time of running Pulsar is twice the time of standalone (CI: L0 L1 cases)

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#27120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.0-20230914-bfe1afae
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.0.post1.dev8
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The time of running Pulsar is twice the time of standalone (CI: L0 L1 cases).

standalone
![image](https://github.com/milvus-io/milvus/assets/109071306/06e5cbbe-ddf7-48a4-a923-4e73bb0787f1)

pulsar
![image](https://github.com/milvus-io/milvus/assets/109071306/d099c3bf-9e28-43c8-a759-9c09e8690a3d)

### Expected Behavior

take the same time

### Milvus Log

https://grafana-devops.zilliz.cc/d/uLf5cJ3Gzx/milvus2-0?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=chaos-testing&var-instance=verify-231-dfeid&var-collection=All&var-app_name=milvus&from=1694745253345&to=1694749974953

**Comment by yanliang567** [comment]
/assign @czs007 
could be a flush issue caused more slower. 

/unassign

**Comment by NicoYuan1986** [comment]
Fixed. 2.3.0-20230915-3f550cee
