### ISSUE TITLE
[Bug]: Return no results when search by args:expr and limit

### ISSUE THREAD

**Issue by xiyuecangxin** [milvus-io/milvus#27136]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.0
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.3.0
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I execute `search(expr="doc_id in [xxx, xxx]", limit=10, ...)` the `search` function return no results. I noticed that the distances between the embeddings of these doc_ids and the input embedding are quite large, implying they should be outside of the top 10 results. I am wondering if the search function calculates the top 10 results first and then applies the expr filter afterwards?
```
search_param={"metric_type": "IP", "params": {"ef": 10}}
index_params={"metric_type": "IP", "index_type": "HNSW", "params": {"M": 8, "efConstruction": 64}}
```

**Comment by xiaofan-luan** [comment]
> doc_id in [xxx, xxx]

did you try to query with doc_id in [xxx, xxx]?
I',m afraid there will be no data inside

**Comment by yanliang567** [comment]
1. Milvus do expr filter first, and then reduce the results to top K.
2. If the doc ids in the doc_id list is quite far from the search vector, it could be not reachable for HNSW index. Besides the suggestion above, I suggest you do the same search without setting any expr(maybe using top 1000), and check whether the tok 1000 results contains any doc ids in the doc_id list.  

/assign @xiyuecangxin 
/unassign
