### ISSUE TITLE
[Feature]: Support insert entities from CSV file

### ISSUE THREAD

**Issue by KumaJie** [milvus-io/milvus#27148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

CSV file is common way to store data, many datasets save as CSV. But milvus now only support import json and numpy file. 

### Describe the solution you'd like.

I'd like to emulate the implement of JSON file import, use row-based.

1. Add csv_parser.go and csv_handler.go
2. Fix import_wrapper.go to support csv file extension
3. Fix import_manager.go, add rowbased change

**Comment by xiaofan-luan** [comment]
@KumaJie 
Thanks for the contribution.

What will the csv file looks like?
Is there any document to explain?

**Comment by xiaofan-luan** [comment]
/assign @yhmo 
could you help on reviewing the pr also?

**Comment by KumaJie** [comment]
> @KumaJie Thanks for the contribution.
> 
> What will the csv file looks like? Is there any document to explain?

this is my reference csv file when implement.
https://www.kaggle.com/datasets/shiyu22chen/cleaned-medium-articles-dataset

**Comment by yiwen92** [comment]
@KumaJie for now, you can use pymilvus 2.2.16 to change csv format to json/npy as workaround: https://docs.zilliz.com/docs/use-bulkwriter-for-data-import

**Comment by yiwen92** [comment]
But I also agree csv format support is a reasonable request :-)

**Comment by xiaofan-luan** [comment]
@wayblink 
any update on the csv?

**Comment by yhmo** [comment]
@xiaofan-luan 
I suppose this feature is for v2.4?

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan I suppose this feature is for v2.4?

Should be on 2.3.4

**Comment by yhmo** [comment]
@KumaJie 
Since this feature is in v2.3.4, could you cherry-pick the pr #27149 to the [2.3 branch](https://github.com/milvus-io/milvus/tree/2.3)?

**Comment by yhmo** [comment]
@KumaJie 
Seems the https://github.com/milvus-io/milvus/pull/28080 is based on the code change of https://github.com/milvus-io/milvus/pull/28161. I think you can merge https://github.com/milvus-io/milvus/pull/28080 to this pr https://github.com/milvus-io/milvus/pull/28161, and submit in one pr.

**Comment by KumaJie** [comment]
> @KumaJie Seems the #28080 is based on the code change of #28161. I think you can merge #28080 to this pr #28161, and submit in one pr.

get it.

**Comment by yhmo** [comment]
The feature is already done, close this issue.
