### ISSUE TITLE
[Bug]: Can not query JSON field

### ISSUE THREAD

**Issue by zrg-team** [milvus-io/milvus#27147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
v2.3.0-dev
- Deployment mode(standalone or cluster):
STANDALONE
- MQ type(rocksmq, pulsar or kafka):    
DEFAULT
- SDK version(e.g. pymilvus v2.0.0rc2):
DEFAULT
- OS(Ubuntu or CentOS): 
MACOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

<img width="274" alt="image" src="https://github.com/milvus-io/milvus/assets/38390571/eec7b723-0fa2-4b35-8f8b-cc0d2c7df7de">

Query with JSON 

<img width="1111" alt="image" src="https://github.com/milvus-io/milvus/assets/38390571/04202ae5-2715-4209-94b6-2bf53195c423">

Can not query

### Expected Behavior

Query JSON field correctly

### Steps To Reproduce

```markdown
1. Add props field with JSON type
2. Add data { "ids": [1] }
3. Do query json_contains(props["ids"], [1])
```

**Comment by xiaofan-luan** [comment]
it should be  json_contains(props["ids"], 1) right?

**Comment by xiaofan-luan** [comment]
contains can not run with a array, only contains_any or contains_all

**Comment by zrg-team** [comment]
same result 
![image](https://github.com/milvus-io/milvus/assets/38390571/9229aef6-0e89-4b39-a6d3-d37e787e97b6)

**Comment by xiaofan-luan** [comment]
could you share your code?

**Comment by xiaofan-luan** [comment]
the expression is correct, what is 2.3.0-dev? the latest master branch?

**Comment by xiaofan-luan** [comment]
1. could you offer the querynode logs, we can. investigate on if there are any other errors?
2.  did you ever try this could work in pymilvus?

**Comment by zrg-team** [comment]
@xiaofan-luan 
v2.3.0-dev is latest docker image for standalone version
pymilvus
I'm using nodejs sdk 

yes let me provide some log from Milvus standalone docker

**Comment by xiaofan-luan** [comment]
we will keep investigating on this issue too

**Comment by xiaocai2333** [comment]
@zrg-team  The latest image does not have this problem. You can try again with the latest image.

**Comment by zrg-team** [comment]
![image](https://github.com/milvus-io/milvus/assets/38390571/7dacabf0-8410-421d-aa72-9fd4d44f08d4)

json_contains(references["table_definition_ids"], [120])

still not work 

/reopen

**Comment by yanliang567** [comment]
/assign @elstic 
please help to check if it reproduces on v2.3.4

**Comment by anakidkin** [comment]
not sure about arrays and json_contains, but even a simple search is not working with JSON.
example: `meta["myfield"] == "abc"`
It was checked on 2.3.1 and 2.3.7

**Comment by xiaocai2333** [comment]
> ![image](https://private-user-images.githubusercontent.com/38390571/294145064-7dacabf0-8410-421d-aa72-9fd4d44f08d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDAzNTQsIm5iZiI6MTcxMTU0MDA1NCwicGF0aCI6Ii8zODM5MDU3MS8yOTQxNDUwNjQtN2RhY2FiZjAtODQxMC00MjFkLWFhNzItOWZkNGQ0NGYwOGQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDExNDczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxM2Q5OTJlNzQwMmYwMDA3MDM3OWE5YTNhMjhmYjhiZTY1NzNmYTRlMDhiN2ZlM2ExY2UxZjFjZGQzMzZjMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dZdGWh0yZVEGpkL6FwBJBgMW-zOEmyRfWGmqU2NeqLo)
> 
> json_contains(references["table_definition_ids"], [120])
> 
> still not work
> 
> /reopen

Do you want to search a list? If you just want to check whether it contains the element 120, the expression should be `json_contains(references["table_definition_ids"], 120)`

**Comment by xiaocai2333** [comment]
/assign @zrg-team 
unassign

**Comment by Aries-ckt** [comment]
@xiaocai2333 @zrg-team Does Milvus version 2.2.9 support json_contains filter function?

**Comment by xiaocai2333** [comment]
> @xiaocai2333 @zrg-team Does Milvus version 2.2.9 support json_contains filter function?

@Aries-ckt we support json_contains in v2.2.12. 
https://github.com/milvus-io/milvus/releases/tag/v2.2.12
