### ISSUE TITLE
[Bug]:  can't find collection while the collection is exist

### ISSUE THREAD

**Issue by dzqoo** [milvus-io/milvus#27165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.9
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): java
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 6/36
- GPU: 
- Others:
```

### Current Behavior

When I search milvus based on java sdk, I got the following error "code: UnexpectedError, reason: code: CollectionNotExists, reason: can't find collection" while this collection is really exist.
I got the following info message from proxy node:
![6bcafcaccf1afc7834e44702d92ba91](https://github.com/milvus-io/milvus/assets/8862305/272a1044-49a5-45c5-a21e-f9d0e7a3c2f6)

**Comment by dzqoo** [comment]
[milvus.log.tar.gz](https://github.com/milvus-io/milvus/files/12645846/milvus.log.tar.gz)

**Comment by jiaoew1991** [comment]
Hi @dzqoo The keyword "can't find collection" or similar phrases were not found in the log. The annotated behavior in the screenshot is reasonable and belongs to the cache expiration that Milvus can handle automatically internally.

**Comment by dzqoo** [comment]
> Hi @dzqoo The keyword "can't find collection" or similar phrases were not found in the log. The annotated behavior in the screenshot is reasonable and belongs to the cache expiration that Milvus can handle automatically internally.
I got this log from queryCoor：
{"level":"WARN","time":"2023/09/18 07:53:28.402 +00:00","caller":"retry/retry.go:44","message":"retry func failed","retry time":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
{"level":"WARN","time":"2023/09/18 07:53:28.402 +00:00","caller":"grpcclient/client.go:318","message":"ClientBase ReCall grpc first call get error","role":"querynode","error":"err: rpc error: code = DeadlineExceeded desc = context deadline exceeded\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:317 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:104 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).GetComponentStates\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:221 github.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).GetComponentStates.func1\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:241 github.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).send\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:220 github.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).GetComponentStates\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/services.go:1000 github.com/milvus-io/milvus/internal/querycoordv2.(*Server).checkNodeHealth.func1\n/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 golang.org/x/sync/errgroup.(*Group).Go.func1\n/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit\n"}
{"level":"WARN","time":"2023/09/18 07:53:28.403 +00:00","caller":"retry/retry.go:44","message":"retry func failed","retry time":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
{"level":"WARN","time":"2023/09/18 07:53:28.403 +00:00","call
