### ISSUE TITLE
[Feature]: How to use GPU in the official provided GPU version Docker image of version 2.3.0?

### ISSUE THREAD

**Issue by AndreWanga** [milvus-io/milvus#27175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I used the official GPU image to build an index, but I noticed that the GPU is still not being utilized. 
First, I'd like to ask if there are any specific settings required in the configuration file. 
Secondly, if I want to build an index for a massive dataset, such as billions of records, and utilize multiple GPUs, do I need to use a method similar to index_cpu_to_all_gpus in Faiss to evenly distribute the data across multiple GPUs? 
Finally, I'm wondering if there is a detailed usage guide available to help me use the GPU version of Milvus.

**Comment by xiaofan-luan** [comment]
You have to use gpu image.
What is the current image you are using?

**Comment by AndreWanga** [comment]
> You have to use gpu image. What is the current image you are using?
Please take a look at my description above; I'm using the GPU image.

**Comment by AndreWanga** [comment]
> You have to use gpu image. What is the current image you are using?

You have to use gpu image. What is the current image you are using?
Please take a look at my description above; I'm using the GPU image.

**Comment by AndreWanga** [comment]
> You have to use gpu image. What is the current image you are using?

Please take a look at my description above; I'm using the GPU image.
