### ISSUE TITLE
Cannot start milvus server due to "Illegal instruction" error

### ISSUE THREAD

**Issue by 670133189** [milvus-io/milvus#2717]
系统：CentOS Linux release 7.8.2003 (Core)

输入：【docker logs id】，提示：【./start_server.sh: line 3:7 Illegal instruction(core dumped) ../bin/milvus_server -c ../conf/server_config.yaml】

**Comment by tinkerlin** [comment]
Please provide following information:

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Docker version
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Comment by 670133189** [comment]
系统：CentOS Linux release 7.8.2003 (Core)
CPU：4核 Intel(R) Xeon(R) CPU E5-2640 v2 @ 2.00GHz
内存：8G
磁盘：250G
Docker：19.03.12
Milvus：v0.6.0至v0.10.0
server_config.yaml：https://raw.githubusercontent.com/milvus-io/milvus/v0.10.0/core/conf/demo/server_config.yaml





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tinkerrr"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月2日(星期四) 晚上11:31
收件人:&nbsp;"milvus-io/milvus"<milvus@noreply.github.com&gt;;
抄送： &nbsp;“桢少” <670133189@qq.com&gt;;“作者” <author@noreply.github.com&gt;;
主题:&nbsp;Re: [milvus-io/milvus] 无法运行milvus (#2717)





 
请提供以下信息：
 
环境细节
  
硬件/软件条件（操作系统，CPU，GPU，内存）
 
Docker版本
 
Milvus版本（v0.3.1或v0.4.0）
 
Milvus配置（您在中进行的设置server_config.yaml）
   
— 
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by yhmo** [comment]
https://www.milvus.io/cn/docs/v0.10.0/faq/operational_faq.md#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E7%9A%84-Milvus-%E5%9C%A8%E5%90%AF%E5%8A%A8%E6%97%B6%E8%BF%94%E5%9B%9E-Illegal-instruction

You need to run this command to know whether your cpu supported 'avx' instruction:
`cat /proc/cpuinfo`
