### ISSUE TITLE
[Bug]: fail to build index for a scalar field in Attu

### ISSUE THREAD

**Issue by groobyming** [milvus-io/milvus#27187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.12
- Deployment mode: cluster
- MQ type: pulsar
- attu: 2.3.0
```

### Current Behavior

When I use Attu ui (version 2.3.0) to index the scalar field of a collection, I get the message "can only use 'STL_SORT' when scalar field expect Varchar"
<img width="1705" alt="image" src="https://github.com/milvus-io/milvus/assets/34335395/c901fce6-e53b-4f38-a0a4-e54fc090965a">
But indexing can be done normally using python sdk

### Expected Behavior

I want to be able to index scalar fields through attu ui

**Comment by xiaofan-luan** [comment]
/assign @shanghaikid 
any special reason for that?

**Comment by xiaocai2333** [comment]
@groobyming We only support `STL_SORT` index for int columns.

**Comment by xiaofan-luan** [comment]
> @groobyming We only support `STL_SORT` index for int columns.

can we do a backward compatible?

we can directly change Asceneding to STL_SORT for backward compaibility

**Comment by weimingdiit** [comment]
I encountered the same problem, please follow up on this question，thanks

**Comment by xiaofan-luan** [comment]
@xige-16 
please help on the compatibility

**Comment by xige-16** [comment]
Fix it soon

**Comment by shanghaikid** [comment]
it is fixed in the latest release. https://github.com/zilliztech/attu/releases/tag/v2.3.2
