### ISSUE TITLE
[Bug]: GPU start failed with official docker image v2.3.0 gpu version

### ISSUE THREAD

**Issue by AndreWanga** [milvus-io/milvus#27194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.3.0-GPU
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.3.0
- OS(Ubuntu or CentOS): official docker image
- CPU/Memory: 
- GPU: V100
- Others:
```

### Current Behavior

When I build index, gpu is not used. Because GPU RAM remain unchanged.

### Expected Behavior

Build index by using GPU

**Comment by yanliang567** [comment]
@AndreWanga any error code or msg you get? could you please use docker-compose logs > milvus.log to export the logs?

/assign @AndreWanga 
/unassign

**Comment by AndreWanga** [comment]
> @AndreWanga any error code or msg you get? could you please use docker-compose logs > milvus.log to export the logs?
> 
> /assign @AndreWanga /unassign

I used the GPU_IVF_FLAT index when creating the index, but after creation, GPU memory was not allocated, and during searches, GPU usage did not increase; it still relies on the CPU for searching. The search performance is poor; for 10,000 384-dimensional vectors, it takes 300ms for a single search.

**Comment by yanliang567** [comment]
/assign @LoveEachDay 
do we miss any configurations here for gpu index?
/unassign

**Comment by AndreWanga** [comment]
I'd like to know is this issue being dealing with? @yanliang567

**Comment by xiaofan-luan** [comment]
@AndreWanga 
could you share you code?

especially how to create your index?

**Comment by xiaofan-luan** [comment]
@AndreWanga 
could you share you code?

**Comment by liliu-z** [comment]
@AndreWanga Do you mind to check this to see if it is the same problem
https://github.com/milvus-io/milvus/issues/27377

**Comment by AndreWanga** [comment]
> @AndreWanga Do you mind to check this to see if it is the same problem #27377

Tanks for this information. But I wander how to create multi indexes for data isolation if I delete the index_name object. @liliu-z

**Comment by AndreWanga** [comment]
Now I have successfully created an index, and I can see that Milvus is using GPU memory. However, during the search process, the GPU utilization rate does not increase.

Here is my search code:
```
collection = Collection("test") # already created
search_params = {"metric_type": "L2", "params": {"nprobe": 20}}
collection.search(data, "embedding", search_params, 10)
```
@liliu-z @xiaofan-luan

**Comment by AndreWanga** [comment]
Additionally, I use
```
 collection.release()
 collection.drop_index()
```
can NOT release the GPU memory that milvus allocated

**Comment by AndreWanga** [comment]
Hi, please check my newest reply, there are still some issues needed to be done. @yanliang567

**Comment by yanliang567** [comment]
@binbinlv is trying to reproduce the issue in house

**Comment by AndreWanga** [comment]
> @binbinlv is trying to reproduce the issue in house

thanks for dealing with my issues. I hope could fix these promblems then we could use milvus in product. @yanliang567

**Comment by liliu-z** [comment]
> Additionally, I use
> 
> ```
>  collection.release()
>  collection.drop_index()
> ```
> 
> can NOT release the GPU memory that milvus allocated @liliu-z @xiaofan-luan @yanliang567

GPU memory will be hold by a memory pool inside Milvus for reusing.

**Comment by liliu-z** [comment]
> Now I have successfully created an index, and I can see that Milvus is using GPU memory. However, during the search process, the GPU utilization rate does not increase.
> 
> Here is my search code:
> 
> ```
> collection = Collection("test") # already created
> search_params = {"metric_type": "L2", "params": {"nprobe": 20}}
> collection.search(data, "embedding", search_params, 10)
> ```
> 
> @liliu-z @xiaofan-luan

@Presburger can help take a check on this? Thanks

**Comment by binbinlv** [comment]
> @binbinlv is trying to reproduce the issue in house

Yes, the GPU memory is not released after release and drop_index()，and drop_collection.

```
nvidia-smi -i 1
|   1  NVIDIA GeForce RTX 2080 Ti     Off | 00000000:03:00.0 Off |                  N/A |
| 27%   28C    P8              21W / 250W |   5679MiB / 11264MiB |      0%      Default |
|                                         |                      |                  N/A |
nvidia-smi -i 3
|   3  NVIDIA GeForce RTX 2080 Ti     Off | 00000000:84:00.0 Off |                  N/A |
| 27%   28C    P8               1W / 250W |   5677MiB / 11264MiB |      0%      Default |
|                                         |                      |                  N/A |
```

**Comment by AndreWanga** [comment]
> > @binbinlv is trying to reproduce the issue in house
> 
> Yes, through my reproduction, the GPU memory is not released after release, drop_index()，and drop_collection.
> 
> ```
> nvidia-smi -i 1
> |   1  NVIDIA GeForce RTX 2080 Ti     Off | 00000000:03:00.0 Off |                  N/A |
> | 27%   28C    P8              21W / 250W |   5679MiB / 11264MiB |      0%      Default |
> |                                         |                      |                  N/A |
> nvidia-smi -i 3
> |   3  NVIDIA GeForce RTX 2080 Ti     Off | 00000000:84:00.0 Off |                  N/A |
> | 27%   28C    P8               1W / 250W |   5677MiB / 11264MiB |      0%      Default |
> |                                         |                      |                  N/A |
> ```

Thanks for your reproduction

**Comment by liliu-z** [comment]
Hi @AndreWanga just want to double check:
1. About the GPU memory release concerns, the answer is that GPU mem pool will hod it for the future usage.
2. About the GPU utility rate doesn't change issue, is that still a concern?

**Comment by AndreWanga** [comment]
> Hi @AndreWanga just want to double check:
> 
> 1. About the GPU memory release concerns, the answer is that GPU mem pool will hod it for the future usage.
> 2. About the GPU utility rate doesn't change issue, is that still a concern?

number 2 is still a concern@liliu-z

**Comment by AndreWanga** [comment]
@liliu-z

**Comment by Presburger** [comment]
@AndreWanga hi, can you share me some logs printed by milvus container?

**Comment by AndreWanga** [comment]
this is the log:
[standalone-3.log](https://github.com/milvus-io/milvus/files/12933068/standalone-3.log)
this is my code:
[test.txt](https://github.com/milvus-io/milvus/files/12933219/test.txt)
@Presburger

**Comment by AndreWanga** [comment]
@liliu-z @Presburger  Is my log and code been received?

**Comment by Presburger** [comment]
@AndreWanga  hi, I checked this problem,  this task is so slight for GPU.  you can make search vector data bigger and nprobe largger on search params, then you can see the gpu usage move.

**Comment by AndreWanga** [comment]
> @AndreWanga hi, I checked this problem, this task is so slight for GPU. you can make search vector data bigger and nprobe largger on search params, then you can see the gpu usage move.
> 
> ```
> search_params = {"metric_type": "L2", "params": {"nprobe": 30}}
> #change to
> search_params = {"metric_type": "L2", "params": {"nprobe": 800}}
> ```
> 
> or
> 
> ```
> data_search = np.random.random(size=(1000, 384)).astype(np.float32)
> ```

thanks for dealing with my issue, by the way, I'd like to ask how to use multi-gpu for large data. Just like the function in 
Faiss that is "index_cpu_gpu_list".

**Comment by yanliang567** [comment]
multi-gpu support will be available in Milvus 2.3.1, which will be soon released this week.

**Comment by Presburger** [comment]
@AndreWanga  Hi
The multi-GPU version of Milvus is almost indistinguishable in terms of usage compared to the single-GPU version. You just need to correctly expose multiple GPUs to the Milvus image, and Milvus will automatically execute multi-card load balancing mechanisms.

**Comment by AndreWanga** [comment]
Thanks you guys very much! Last question I'm curious that why the performance of my code show the request time average is about 200ms, but if I use faiss to create gpu index of this size of data, it only cost below 10ms. How could I replicate the single-node performance provided in your official benchmark report? @Presburger  @yanliang567
