### ISSUE TITLE
[Bug]: garbage collector may recycle file by mistake if `List` operations exceeds `missingTolerance`

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#27202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.3.0 & v2.2.14
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

garbage collector may recycle file by mistake if `List` operations exceeds `missingTolerance`

### Expected Behavior

garbage collector shall treat files correctly even the `List` operation costs lots of time

**Comment by congqixia** [comment]
- [x] Fix garbage collector logic
  - [x] master #27203 
  - [x] 2.3.1 #27204 
  - [x] 2.2.x #27205 
- [ ] Add metrics for garbage collector

**Comment by congqixia** [comment]
Wait for release

- [x] v2.3.1
- [ ] v2.2.15

**Comment by xiaofan-luan** [comment]
@congqixia 
Any followups for improving list performance?
