### ISSUE TITLE
Always prompt invalid CPU cache size: 4GB

### ISSUE THREAD

**Issue by WanMMao** [milvus-io/milvus#2720]
This is  log:

Welcome to use Milvus!
Milvus Release version: v0.10.0, built at 2020-06-15 14:51.51, with OpenBLAS library.
You are using Milvus CPU edition
Last commit id: 5f3c0052478a08d07d68c5dc1aab57a42293f430

Loading configuration from: ../conf/server_config.yaml
Config check fail: Invalid cpu cache size: 4GB. Possible reason: cache.cache_size exceeds system memory.
ERROR: Milvus server fail to load config file
Invalid cpu cache size: 4GB. Possible reason: cache.cache_size exceeds system memory.
Milvus server exit...

my server_config.yaml:

version: 0.5

cluster:
  enable: false
  role: rw

general:
  timezone: UTC+8
  meta_uri: sqlite://:@:/

network: 
  bind.address: 0.0.0.0
  bind.port: 19530
  http.enable: true
  http.port: 19121

storage:
  path: /var/lib/milvus
  auto_flush_interval: 1

wal:
  enable: true
  recovery_error_ignore: false
  buffer_size: 256MB
  path: /var/lib/milvus/wal

cache:
  cache_size: 1GB
  insert_buffer_size: 1GB
  preload_collection:

gpu:
  enable: false
  cache_size: 1GB
  gpu_search_threshold: 1000
  search_devices:
    - gpu0
  build_index_devices:
    - gpu0

logs:
  level: debug
  trace.enable: true
  path: /var/lib/milvus/logs
  max_log_file_size: 1024MB
  log_rotate_num: 0

metric:
  enable: false
  address: 127.0.0.1
  port: 9091

this is docker info :

Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 1
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.18.0-147.8.1.el8_1.x86_64
 Operating System: CentOS Linux 8 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.552GiB
 Name: BEIJING-2C4G-H002
 ID: VWYN:SBD2:I6VM:7GSV:WPGF:TPPP:3A6P:DXOR:CAO2:PABV:KBBO:IPQ6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

Even if I change the cache_ The size log remains unchanged

Please help me. Thank you

**Comment by yhmo** [comment]
There possible reason is, the config file path is not mapped correctly. Milvus is still using default config file(inside the container) to start.

Assume your `server_config.yaml` is under `/home/xxx/conf` folder,  use this command to start milvus:
` docker run -it -p 19530:19530 -v /home/xxx/conf:/var/lib/milvus/conf -d milvusdb/milvus:0.10.0-cpu-d061620-5f3c00`

**Comment by WanMMao** [comment]
> There possible reason is, the config file path is not mapped correctly. Milvus is still using default config file(inside the container) to start.
> 
> Assume your `server_config.yaml` is under `/home/xxx/conf` folder, use this command to start milvus:
> ` docker run -it -p 19530:19530 -v /home/xxx/conf:/var/lib/milvus/conf -d milvusdb/milvus:0.10.0-cpu-d061620-5f3c00`

According to what you said, my problem has been solved. Can you tell me that I use docker run - TD -- name face_ milvs -p 19530:19530 -p 8080:8080 -v /home/milvus/db:/opt/milvus/db -v /home/milvus/conf:/opt/milvus/conf -v /home/milvus/conf/logs:/opt/milvus/logs milvusdb/ milvus:0.10.0-cpu-d061620-5f3c00 Why is this command wrong? Thank you

**Comment by yhmo** [comment]
These mapping folders is wrong:
`-v /home/milvus/db:/opt/milvus/db -v /home/milvus/conf:/opt/milvus/conf -v /home/milvus/conf/logs:/opt/milvus/logs`

We deploy milvus to `/opt/milvus` folder in old version(0.6.0). Now milvus is deployed to `/var/lib/milvus` folder.

**Comment by WanMMao** [comment]
> 这些映射文件夹是错误的：
> `-v /home/milvus/db:/opt/milvus/db -v /home/milvus/conf:/opt/milvus/conf -v /home/milvus/conf/logs:/opt/milvus/logs`
> 
> 我们曾经将milvus部署到`/opt/milvus`旧版本（0.6.0）的文件夹中。现在，milvus已部署到`/var/lib/milvus`文件夹。

ok,thank you
