### ISSUE TITLE
[Bug]: build failed with docker

### ISSUE THREAD

**Issue by xiedeyantu** [milvus-io/milvus#27221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2ed13ba6d5679cd29f9c3d1c48a6c4710856361e
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu 20.04
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
~/code/milvus ~/code/milvus
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.builder: 'platform'
```

**Comment by jiaoew1991** [comment]
hi @xiedeyantu It seems your Docker version is too low. You need to upgrade your Docker.

**Comment by xiedeyantu** [comment]
> hi @xiedeyantu It seems your Docker version is too low. You need to upgrade your Docker.

@jiaoew1991 
root@cz:~/code/milvus# docker version
Client: Docker Engine - Community
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:32:12 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:12 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by jiaoew1991** [comment]
@xiedeyantu You need upgrade docker compose newer than 2.4
https://docs.docker.com/compose/compose-file/compose-file-v2/#platform
