### ISSUE TITLE
[Bug]: the memory usage of the nodes is uneven

### ISSUE THREAD

**Issue by zk903956028** [milvus-io/milvus#27246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

My cluster deployment is using version 2.3.0, and when deploying with k8s, it does not automatically create PV. I manually created the PV on my side. Now, after data is written, only one node has high memory usage, while other nodes have low memory usage. The server's disk is not an SSD. I would like to know the reason why the memory usage of the nodes is uneven。

### Expected Behavior

no thing

### Steps To Reproduce

```markdown
no thing
```

### Milvus Log

no thing

### Anything else?

no thing

**Comment by yanliang567** [comment]
@zk903956028 i don't quite understand the issue, could you please share more info:
1. which node or milvus pod has high memory usage? how much 
2. Only etcd, minio, pulsar services and querynode pods(if you are using diskAnn index) require PV, and it is recommended to use SSD volume for etcd and pulsar bookie services.
3. Could you please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
/assign @zk903956028 
/unassign

**Comment by zk903956028** [comment]
> @zk903956028 i don't quite understand the issue, could you please share more info:
> 
> 1. which node or milvus pod has high memory usage? how much
> 2. Only etcd, minio, pulsar services and querynode pods(if you are using diskAnn index) require PV, and it is recommended to use SSD volume for etcd and pulsar bookie services.
> 3. Could you please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
>    /assign @zk903956028
>    /unassign
Currently, the data is approximately 6 million rows, with a vector dimension of 1024. I am not using the diskAnn index. The querynode occupies 30G of memory, the indexnote only occupies 3.30G of memory, and the datanote only occupies 0.56G.

**Comment by yanliang567** [comment]
the raw data(6 million + 1024dim) could be 22 GB, so i think it is reasonable for querynode to use 30GB after load the collection.
