### ISSUE TITLE
[Bug]: Pulsar Broker can not start well.

### ISSUE THREAD

**Issue by markdma1** [milvus-io/milvus#27256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.13
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):   pulsar  
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Pulsar Broker can not start well.
![image](https://github.com/milvus-io/milvus/assets/145532460/7d4f0f96-d880-44ea-972e-4ef94b43504c)

![image](https://github.com/milvus-io/milvus/assets/145532460/0a3dff7c-8f4c-4c41-b6f4-2d5f4afe0cb0)

**Comment by yanliang567** [comment]
@markdma1 did you change any configurations when deploying Milvus? does the issue reproduce when initialing milvus deployment or any other operations you did? 
/assign @markdma1 
/unassign

**Comment by markdma1** [comment]
> @markdma1 did you change any configurations when deploying Milvus? does the issue reproduce when initialing milvus deployment or any other operations you did? /assign @markdma1 /unassign

i did not change configuration when deploying milvus. yes,it  reproduce when initialing milvus deployment.
