### ISSUE TITLE
[Bug]:  Milvus standalone 2.2.13 High memory usage causes milvus to disconnect the program

### ISSUE THREAD

**Issue by z666k** [milvus-io/milvus#27267]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.13
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS7.9 
- CPU/Memory: 8C/91G
- GPU: 
- Others:
```

### milvus.yml include below three section:  
 1、 memProtection:
      enabled: true
      # When memory usage > memoryHighWaterLevel, all dml requests would be rejected;
      # When memoryLowWaterLevel < memory usage < memoryHighWaterLevel, reduce the dml rate;
      # When memory usage < memoryLowWaterLevel, no action.
      # memoryLowWaterLevel should be less than memoryHighWaterLevel.
      dataNodeMemoryLowWaterLevel: 0.85 # (0, 1], memoryLowWaterLevel in DataNodes
      dataNodeMemoryHighWaterLevel: 0.95 # (0, 1], memoryHighWaterLevel in DataNodes
      queryNodeMemoryLowWaterLevel: 0.85 # (0, 1], memoryLowWaterLevel in QueryNodes
      queryNodeMemoryHighWaterLevel: 0.95 # (0, 1], memoryHighWaterLevel in QueryNodes

2、queryNode:
  cacheSize: 32 # GB, default 32 GB, `cacheSize` is the memory used for caching data for faster query. The `ca
cheSize` must be less than system memory size.  port: 21123
  loadMemoryUsageFactor: 3 # The multiply factor of calculating the memory usage while loading segments
  enableDisk: true # enable querynode load disk index, and search on disk index
  maxDiskUsagePercentage: 95
  gracefulStopTimeout: 30

  stats:
    publishInterval: 1000 # Interval for querynode to report node information (milliseconds)
  dataSync:
    flowGraph:
      maxQueueLength: 1024 # Maximum length of task queue in flowgraph
      maxParallelism: 1024 # Maximum number of tasks executed in parallel in the flowgraph
  segcore:
    chunkRows: 1024 # The number of vectors in a chunk.
    knowhereThreadPoolNumRatio: 4 # Use more threads to make good use of SSD throughput
    # Note: we have disabled segment small index since @2022.05.12. So below related configurations won't work
.    # We won't create small index for growing segments and search on these segments will directly use brutefor
ce scan.    smallIndex:
      nlist: 128 # small index nlist, recommend to set sqrt(chunkRows), must smaller than chunkRows/8
      nprobe: 16 # nprobe to search small index, based on your accuracy requirement, must smaller than nlist
  cache:
    enabled: true
    memoryLimit: 2147483648 # 2 GB, 2 * 1024 *1024 *1024

3、dataNode:
  port: 21124
  dataSync:
    flowGraph:
      maxQueueLength: 1024 # Maximum length of task queue in flowgraph
      maxParallelism: 1024 # Maximum number of tasks executed in parallel in the flowgraph
    maxParallelSyncTaskNum: 2 # Maximum number of sync tasks executed in parallel in each flush manager
  segment:
    # Max buffer size to flush for a single segment.
    insertBufSize: 16777216 # Bytes, 16 MB
    # Max buffer size to flush del for a single channel
    deleteBufBytes: 67108864 # Bytes, 64MB
    # The period to sync segments if buffer is not empty.
    syncPeriod: 600 # Seconds, 10min

  memory:
    forceSyncEnable: true # `true` to force sync if memory usage is too high
    forceSyncSegmentNum: 1 # number of segments to sync, segments with top largest buffer will be synced.
    watermarkStandalone: 0.2 # memory watermark for standalone, upon reaching this watermark, segments will be
 synced.    watermarkCluster: 0.5 # memory watermark for cluster, upon reaching this watermark, segments will be synce
d.
  timetick:
    byRPC: true # 'true' to use RPC instead of msgstream to report datanode timetick message

### Actual resource usage：
<img width="713" alt="企业微信截图_16951921856359" src="https://github.com/milvus-io/milvus/assets/127073101/8587b9ab-f164-4ebe-b4ad-a26b05c8000e">

<img width="928" alt="企业微信截图_16951922234641" src="https://github.com/milvus-io/milvus/assets/127073101/61e25c1d-d860-4702-afd2-04baa2a42257">

**Comment by z666k** [comment]
SDK version(e.g. pymilvus v2.0.0rc2): 2.2.15

**Comment by yanliang567** [comment]
@z666k how many vectors did you load, and what are the dimensions? please offer full milvus logs for investigation. For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.

/assign @z666k 
/unassign

**Comment by z666k** [comment]
The default database library is empty,only one database patient_db is use
vector quantity：21841386
dimensions： 128

![image](https://github.com/milvus-io/milvus/assets/127073101/ea8a8214-930e-4b5b-937b-e78c374879d6)

### ERROR log
milvus-standalone | [2023/09/19 19:32:34.954 +00:00] [ERROR] [grpcclient/client.go:353] ["ClientBase ReCall grpc second call get error
"] [role=querycoord] [error="err: find no available querycoord, check querycoord state\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:352 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/client/client.go:121 github.com/milvus-io/milvus/internal/distributed/querycoord/client.(*Client).GetComponentStates\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:67 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1\n/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:42 github.com/milvus-io/milvus/internal/util/retry.Do\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:91 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:106 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentHealthy\n/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:600 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).init\n/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:345 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Run\n/go/src/github.com/milvus-io/milvus/cmd/components/proxy.go:51 github.com/milvus-io/milvus/cmd/components.(*Proxy).Run\n"] [stack="github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:353\ngithub.com/milvus-io/milvus/internal/distributed/querycoord/client.(*Client).GetComponentStates\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/client/client.go:121\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:67\ngithub.com/milvus-io/milvus/internal/util/retry.Do\n\t/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:42\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:91\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentHealthy\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:106\ngithub.com/milvus-io/milvus/internal/distributed/proxy.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:600\ngithub.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:345\ngithub.com/milvus-io/milvus/cmd/components.(*Proxy).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/proxy.go:51\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:120"]milvus-standalone | [2023/09/19 19:32:34.954 +00:00] [WARN] [retry/retry.go:44] ["retry func failed"] ["retry time"=0] [error="err: fi
nd no available querycoord, check querycoord state\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:352 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/client/client.go:121 github.com/milvus-io/milvus/internal/distributed/querycoord/client.(*Client).GetComponentStates\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:67 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1\n/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:42 github.com/milvus-io/milvus/internal/util/retry.Do\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:91 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:106 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentHealthy\n/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:600 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).init\n/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:345 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Run\n/go/src/github.com/milvus-io/milvus/cmd/components/proxy.go:51 github.com/milvus-io/milvus/cmd/components.(*Proxy).Run\n"]milvus-standalone | [2023/09/19 19:32:34.959 +00:00] [INFO] [datanode/channel_meta.go:440] ["Successfully load pk stats"] [segmentID=4
44372043372291165] [time=19.595025ms] [size=1568051]milvus-standalone | [2023/09/19 19:32:34.959 +00:00] [INFO] [datanode/data_sync_service.go:256] ["recover sealed segments form checkpo
ints"] [vChannelName=by-dev-rootcoord-dml_11_443487147300296268v0] [segmentID=443487147307910696] [numRows=65317]milvus-standalone | [2023/09/19 19:32:34.959 +00:00] [INFO] [datanode/channel_meta.go:210] ["adding segment"] [type=Flushed] [segmentI
D=443487147307026060] [collectionID=443487147300296268] [partitionID=443487147300296269] [channel=by-dev-rootcoord-dml_11_443487147300296268v0] [startPosition=<nil>] [endPosition=<nil>] [recoverTs=444373902226096130] [importing=false]milvus-standalone | [2023/09/19 19:32:34.959 +00:00] [INFO] [datanode/channel_meta.go:379] ["begin to init pk bloom filter"] [segmentI
D=443487147307026060] [statsBinLogsLen=1]

**Comment by z666k** [comment]
Since restarting the service cannot release the memory, we temporarily delete the data and then import it. The memory occupied in this way is slowly increasing and has reached 71.68GB of data.
You can see from the picture below that they are all occupied by queryNode.

<img width="872" alt="企业微信截图_16952684004768" src="https://github.com/milvus-io/milvus/assets/127073101/666f4d36-03a8-4356-8b32-ec300113b837">

We try to set    loadMemoryUsageFactor : 1, the default is loadMemoryUsageFactor: 3
In this way, the queryNode cache can reach up to 32G, instead of the previous 32*3=96G. This should solve the first problem, let me try it here. But the second question is, why is the memory not released when the service is restarted?

**Comment by z666k** [comment]
![image](https://github.com/milvus-io/milvus/assets/127073101/506b3e8d-08dc-4fd7-938b-f8c33d7996fe)

**Comment by xiaofan-luan** [comment]
> Since restarting the service cannot release the memory, we temporarily delete the data and then import it. The memory occupied in this way is slowly increasing and has reached 71.68GB of data. You can see from the picture below that they are all occupied by queryNode.
> 
> <img alt="企业微信截图_16952684004768" width="872" src="https://user-images.githubusercontent.com/127073101/269480747-666f4d36-03a8-4356-8b32-ec300113b837.png">
> We try to set loadMemoryUsageFactor : 1, the default is loadMemoryUsageFactor: 3 In this way, the queryNode cache can reach up to 32G, instead of the previous 32*3=96G. This should solve the first problem, let me try it here. But the second question is, why is the memory not released when the service is restarted?

This is actually a bug in Milvus 2.2.X since the cache is not a single instance.
In 2.3 we moved the chunk cache in go and changed it into cpp as a single instance. 
If you want to retrieve vector, I would recommend you to use HNSW or IVFFLAT to avoid querynode cache

**Comment by z666k** [comment]
thank you!
