### ISSUE TITLE
Couldn't build milvus sdk v0.10.0

### ISSUE THREAD

**Issue by jockeyyan** [milvus-io/milvus#2726]
I want to build milvus sdk v0.10.0 on ubuntu18, after grpc_ep was built, prompt as following:

[ 32%] Completed 'grpc_ep'
[ 32%] Built target grpc_ep
Scanning dependencies of target milvus_sdk
[ 34%] Building CXX object CMakeFiles/milvus_sdk.dir/interface/ConnectionImpl.cpp.o
make[2]: *** 没有规则可制作目标“grpc_ep-prefix/src/grpc_ep/libs/opt/protobuf/libprotobuf.a”，由“libmilvus_sdk.so” 需求。 停止。
make[2]: *** 正在等待未完成的任务....
[ 38%] Building CXX object CMakeFiles/milvus_sdk.dir/grpc/ClientProxy.cpp.o
[ 38%] Building CXX object CMakeFiles/milvus_sdk.dir/interface/Status.cpp.o
[ 40%] Building CXX object CMakeFiles/milvus_sdk.dir/grpc/GrpcClient.cpp.o
[ 42%] Building CXX object CMakeFiles/milvus_sdk.dir/grpc-gen/gen-milvus/milvus.grpc.pb.cc.o
[ 46%] Building CXX object CMakeFiles/milvus_sdk.dir/grpc-gen/gen-status/status.pb.cc.o
[ 46%] Building CXX object CMakeFiles/milvus_sdk.dir/grpc-gen/gen-status/status.grpc.pb.cc.o
[ 48%] Building CXX object CMakeFiles/milvus_sdk.dir/grpc-gen/gen-milvus/milvus.pb.cc.o
CMakeFiles/Makefile2:211: recipe for target 'CMakeFiles/milvus_sdk.dir/all' failed
make[1]: *** [CMakeFiles/milvus_sdk.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

I built the protobuffer 3.9.0 by myself, and install to /usr/local, so what should I do ?
Thanks.

**Comment by fishpenguin** [comment]
It is because your system already has installed protobuffer, and grpc cannot make uninstall your protobuffer. So you need to uninstall your own protobuffer manually.

**Comment by fishpenguin** [comment]
If you decide to make uninstall your own protobuffer, please be careful. Do not delete the "*protobuf*" file in /usr/lib/, or your system may not be able to reboot.

**Comment by jockeyyan** [comment]
I have removed protobuffer in /usr/local/bin, /usr/local/lib, /usr/local/include, but compiler complained "protoc couldn't be found".

**Comment by fishpenguin** [comment]
Remove your cmake_build file in milvus/sdk, and rebuild it.
