### ISSUE TITLE
[Bug]: CPU usage of querynode is close to 400% but there is no operation

### ISSUE THREAD

**Issue by become-nice** [milvus-io/milvus#27281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.14
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): kafka
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.6
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: querynode 8c32g
- GPU: 
- Others:
```

### Current Behavior

There is no operation, but the CPU usage of querynode is close to 400%. 2 cores are allocated to the process, and up to 8 cores can be used.The cluster has close to 400 collections.
![cpu_usage](https://github.com/milvus-io/milvus/assets/56624819/4c50636a-2147-416c-b012-3a92b2edfc49)
This scenario is similar to the previous [issue](https://github.com/milvus-io/milvus/issues/24812), but it uses rocksmq and is in standalone mode. I used the pprof tool to generate a pdf, and the pdf showed that kafka consumed most of the cpu.<br/>
[output.pdf](https://github.com/milvus-io/milvus/files/12679746/output.pdf)<br/>
In version 2.2.10, there were up to 400 collections in the cluster, but there was no similar scenario.

**Comment by xiaofan-luan** [comment]
I think this happens with many collections.
so far we won't solve it on 2.2.x but 2.3 should support more than 10000 collections

**Comment by become-nice** [comment]
> I think this happens with many collections. so far we won't solve it on 2.2.x but 2.3 should support more than 10000 collections

Is this error accidental? When I was using version 2.2.10, the number of collections reached more than 300, but this scenario never happened.

**Comment by xiaofan-luan** [comment]
this is only depend on how many collections you have.
a few hundred collection might be ok

**Comment by yanliang567** [comment]
/assign @become-nice 
if you could share the scenarios why you need so many collections, we might be find some new options.

/unassign

**Comment by xiaofan-luan** [comment]
> /assign @become-nice if you could share the scenarios why you need so many collections, we might be find some new options.
> 
> /unassign

We need to solve the issue. 400 collection is not a big number

**Comment by become-nice** [comment]
> /assign @become-nice if you could share the scenarios why you need so many collections, we might be find some new options.

I have documents from many projects, and the data of these documents are relatively small, so I put them all in one instance.Now there is a problem that when there are too many collections, the querynode node will keep printing `Invalid operate message input milvus` logs. Is there any way to prevent the querynode from continuously printing such logs without changing the log level?

**Comment by xiaofan-luan** [comment]
use partitionkey features might be what you need

**Comment by become-nice** [comment]
> use partitionkey features might be what you need

Using partition key can indeed solve the problem of large collections, but there is resistance in terms of business. Different projects want to isolate permissions, but permissions cannot be set for a single partition. Currently, the cluster has been outputting the log I mentioned above. Is there any way to stop the query node from outputting this log?

**Comment by medram** [comment]
Milvus is creating a huge amount of logs,
Is there any that could disable it?

**Comment by xiaofan-luan** [comment]
> Milvus is creating a huge amount of logs, Is there any that could disable it?

usually you should change the log level to info but not debug
