### ISSUE TITLE
[Bug]:  When I use certain index types to create index，Milvus hang

### ISSUE THREAD

**Issue by yanxiaoqi932** [milvus-io/milvus#27290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I use certain index types to create index，Milvus hang，especially IVF_PQ, RHNSW_FLAT and so on. But FLAT and HNSW is in regular service.

**Comment by yanliang567** [comment]
@yanxiaoqi932 please reproduce the issue and off full milvus logs. Could you please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.

/assign @yanxiaoqi932 
/unassign

**Comment by xiaofan-luan** [comment]
I dont think we support RHNSW_FLAT right now.
IVFPQ should be working.
