### ISSUE TITLE
[Bug]: CreateCollectionParam，use DataType.String will Exceptions

### ISSUE THREAD

**Issue by TaoWolf** [milvus-io/milvus#27296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.30
- Deployment mode(standalone or cluster): standalone 
- MQ type(rocksmq, pulsar or kafka): no   
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 32C / 64G
- GPU: no
- Others: no
```

### Current Behavior

private static CreateCollectionParam initCreateCollectionParam() {
        FieldType fieldType1 = FieldType.newBuilder()
                .withName("funcId")
                .withDataType(DataType.Int64)
                .withPrimaryKey(true)
                .withAutoID(true)
                .build();
        FieldType fieldType2 = FieldType.newBuilder()
                .withName("funcNameId")
                .withDataType(DataType.Int64)
                .build();
//        FieldType fieldType3 = FieldType.newBuilder()
//                .withName("funcInfo")
//                .withDataType(DataType.String)
//                .build();
        FieldType fieldType4 = FieldType.newBuilder()
                .withName("func_vector")
                .withDataType(DataType.FloatVector)
                .withDimension(1536)
                .build();
        CreateCollectionParam createCollectionReq = CreateCollectionParam.newBuilder()
                .withCollectionName(colName)
                .withDescription("云丝函数分析")
                .withShardsNum(2)
                .addFieldType(fieldType1)
                .addFieldType(fieldType2)
//                .addFieldType(fieldType3)
                .addFieldType(fieldType4)
                .withEnableDynamicField(true)
                .build();
        return createCollectionReq;
    }

### Expected Behavior

如果去掉注释部分(使用DataType.String)，则无法建立CollectionParam

### Steps To Reproduce

```markdown
如果去掉注释部分(使用DataType.String)，则无法建立CollectionParam
```

### Milvus Log

no

### Anything else?

no

**Comment by yanliang567** [comment]
@TaoWolf Sorry for confusion, but DataType.String is not supported yet, if you want to use string, please try DataType.varchar. 
/assign @TaoWolf 
/unassign

**Comment by TaoWolf** [comment]
Ok, I've used Varchar instead of String. thanks for reminding.
A tip for other users：remember to set the maximum length~

**Comment by xiaofan-luan** [comment]
@xige-16 
what is the major difference between string and varchar?
