### ISSUE TITLE
[Bug]: milvus_backup only the meta directory is backed up, not the binlog directory

### ISSUE THREAD

**Issue by Cloud0916** [milvus-io/milvus#27293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:4.1.0
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 96/755GiB
- GPU: 
- Others:
```

### Current Behavior

Only the meta directory is backed up by the milvus_backup, and there is no binlog directory

### Milvus Log

[backup.log](https://github.com/milvus-io/milvus/files/12681706/backup.log)

**Comment by Cloud0916** [comment]
We find that the definition of the milvus "rootPath" is "Null",but the configuration of the backup script is "file".When i change the backup configuration of "rootPath" to "",the backup process is correct.Wondering that we didn't change any configurations during deployment before this time,why this problem could be happening?

**Comment by wayblink** [comment]
> We find that the definition of the milvus "rootPath" is "Null",but the configuration of the backup script is "file".When i change the backup configuration of "rootPath" to "",the backup process is correct.Wondering that we didn't change any configurations during deployment before this time,why this problem could be happening?

`file` is just a default value in backup.yaml. I think it is not a problem
