### ISSUE TITLE
[QUESTION] is milvus working on windows?  

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus#273]
windows server 2018 r2 with docker installed?

**Comment by JinHai-CN** [comment]
In theory, it's OK. But we never tested it on Windows before.

**Comment by kwalcock** [comment]
Well, not on the first try, at least.
```
    __  _________ _   ____  ______
   /  |/  /  _/ /| | / / / / / __/
  / /|_/ // // /_| |/ / /_/ /\ \
 /_/  /_/___/____/___/\____/___/

Welcome to use Milvus!
Milvus Release version: v0.10.0, built at 2020-06-15 14:51.51, with OpenBLAS library.
You are using Milvus CPU edition
Last commit id: 5f3c0052478a08d07d68c5dc1aab57a42293f430

Loading configuration from: ../conf/server_config.yaml
Config file not exist: ../conf/server_config.yaml
ERROR: Milvus server fail to load config file
Config file not exist: ../conf/server_config.yaml
Milvus server exit...
```
given
```
$ ls /e/Users/kwa/Applications/milvus/conf
server_config.yaml
```
and
```
docker run -d --name milvus_cpu_0.10.0 \
-p 19530:19530 \
-p 19121:19121 \
-v /e/Users/kwa/Applications/milvus/db:/var/lib/milvus/db \
-v /e/Users/kwa/Applications/milvus/conf:/var/lib/milvus/conf \
-v /e/Users/kwa/Applications/milvus/logs:/var/lib/milvus/logs \
-v /e/Users/kwa/Applications/milvus/wal:/var/lib/milvus/wal \
milvusdb/milvus:0.10.0-cpu-d061620-5f3c00
```

**Comment by kwalcock** [comment]
Isn't this implying that the working directory is /var/lib/milvus/something so that when it looks for ../conf/server_config.yaml, it can be found?  That would be very strange.  Docker says ` "WorkingDir": "/var/lib/milvus"`.

**Comment by JackLCL** [comment]
This error may be that your docker version is too low. 
Milvus official website requires that the version of docker is not less than 19.03. 
So please check your docker version first.

**Comment by kwalcock** [comment]
Thank you.  I had checked.
```
$ docker info                                                                                                                                                                            Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 79
 Server Version: 19.03.5
```

**Comment by kwalcock** [comment]
It does seem to run on a Ubuntu VM on the same computer.  So, Windows -> VM -> Docker -> milvus seems to work while Windows -> Docker -> milvus does not.  This happens to be `Server Version: 19.03.3` of Docker.  Thus far, all the evidence I've seen regarding running milvus on Windows has been negative.  I'd really like to hear about experiences to the contrary.

**Comment by kwalcock** [comment]
The problem has to do with the volumes not being shared by my installation of docker for Windows.  It doesn't seem to be related directly to milvus.
