### ISSUE TITLE
[Bug]: indexnode do not work. what is the reason?

### ISSUE THREAD

**Issue by markdma1** [milvus-io/milvus#27301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.13
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/145532460/767f8d47-c32b-41cf-98e1-e69d5fa621ff)
![image](https://github.com/milvus-io/milvus/assets/145532460/b3088dd1-bd49-4567-b076-939f4e6c3cf6)

**Comment by xiaofan-luan** [comment]
you probabaly need at least 4G memory to start indexnode.
Or you have to reduce segment size to 128MB

**Comment by yanliang567** [comment]
/assign @markdma1 
as comments above, if it does not work, Could you please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.

/unassign
