### ISSUE TITLE
[Bug]: [laion-1b] When querying concurrently, the avg latency on one queryNode is approximately ten times that of the other queryNodes

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#27307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230918-fd732135
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):  kafka
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.0b0.post1.dev127
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. milvus cluster
"""
queryNode: 5 replicas, each queryNode resource 16Cpus 128G memory
proxy: 3 replicas
"""
2. collection:
cluster only have one loaded collection, count(*) 100,000,000 entities, 94 segments, schema is
```
{'auto_id': False, 'description': '', 'fields': [{'name': 'id', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float_vector', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 768}}, {'name': 'varchar_caption', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'varchar_NSFW', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'float64_similarity', 'description': '', 'type': <DataType.FLOAT: 10>}, {'name': 'int64_width', 'description': '', 'type': <DataType.INT64: 5>}, {'name': 'int64_height', 'description': '', 'type': <DataType.INT64: 5>}, {'name': 'int64_original_width', 'description': '', 'type': <DataType.INT64: 5>}, {'name': 'int64_original_height', 'description': '', 'type': <DataType.INT64: 5>}, {'name': 'varchar_md5', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}]}
```

3. query with concurrency 100 and expr: "id < 1000", and the queryNode's query latency and segments distribution are shown in the figure below:
The delegators are qn-109 and qn-111, It can be seen from the figure below that the latency of the two delegators is so high. This is because the latency (about 900ms) of qn-112 is about ten times higher than query workers.  But qn-112 has same segments and entities with qn-113. The query latency of qn-113 a is only about 5ms.

![image](https://github.com/milvus-io/milvus/assets/27288593/557cd8b7-ade9-4a59-a637-07392ce9f47f)

![image](https://github.com/milvus-io/milvus/assets/27288593/e42390bb-7c94-473e-b172-1b2aa89d24e4)

![image](https://github.com/milvus-io/milvus/assets/27288593/8364c425-a96e-4b52-b13b-4b7be455b15b)

### Steps To Reproduce

```markdown
- 4am qa argo: https://argo-workflows.zilliz.cc/archived-workflows/qa/d3cc72ed-aff1-45b1-aea7-3a98ddcd3694?nodeId=laion-test-100m-concurrent-query-1

- server metrics: https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=qa-milvus&var-instance=laion-test-3&var-collection=All&var-app_name=milvus&from=1695101912315&to=1695106727129
```

### Milvus Log

laion-test-3-etcd-0                                               1/1     Running     10 (14d ago)    31d     10.104.14.95    4am-node18   <none>           <none>
laion-test-3-etcd-1                                               1/1     Running     5 (10d ago)     31d     10.104.12.76    4am-node17   <none>           <none>
laion-test-3-etcd-2                                               1/1     Running     0               31d     10.104.24.195   4am-node29   <none>           <none>
laion-test-3-milvus-datanode-686968489b-5hgcj                     1/1     Running     0               2d9h    10.104.16.229   4am-node21   <none>           <none>
laion-test-3-milvus-datanode-686968489b-jgfxv                     1/1     Running     0               2d9h    10.104.15.165   4am-node20   <none>           <none>
laion-test-3-milvus-indexnode-6dc5c4fdd4-kvj9c                    1/1     Running     0               2d9h    10.104.15.169   4am-node20   <none>           <none>
laion-test-3-milvus-indexnode-6dc5c4fdd4-pqfmf                    1/1     Running     0               2d9h    10.104.20.134   4am-node22   <none>           <none>
laion-test-3-milvus-indexnode-6dc5c4fdd4-r9xgg                    1/1     Running     0               2d9h    10.104.20.133   4am-node22   <none>           <none>
laion-test-3-milvus-indexnode-6dc5c4fdd4-wjvkt                    1/1     Running     0               2d9h    10.104.15.168   4am-node20   <none>           <none>
laion-test-3-milvus-mixcoord-76644b57b8-xhsxd                     1/1     Running     0               2d9h    10.104.16.228   4am-node21   <none>           <none>
laion-test-3-milvus-proxy-57db9644cd-876jh                        1/1     Running     0               2d9h    10.104.16.230   4am-node21   <none>           <none>
laion-test-3-milvus-proxy-57db9644cd-p9rk2                        1/1     Running     0               2d9h    10.104.20.131   4am-node22   <none>           <none>
laion-test-3-milvus-proxy-57db9644cd-pntrg                        1/1     Running     0               2d9h    10.104.15.166   4am-node20   <none>           <none>
laion-test-3-milvus-querynode-5dd557c4dc-489qd                    1/1     Running     0               2d9h    10.104.16.233   4am-node21   <none>           <none>
laion-test-3-milvus-querynode-5dd557c4dc-8zs5k                    1/1     Running     0               2d9h    10.104.16.232   4am-node21   <none>           <none>
laion-test-3-milvus-querynode-5dd557c4dc-97czj                    1/1     Running     0               2d9h    10.104.16.231   4am-node21   <none>           <none>
laion-test-3-milvus-querynode-5dd557c4dc-g9sdw                    1/1     Running     0               2d9h    10.104.20.132   4am-node22   <none>           <none>
laion-test-3-milvus-querynode-5dd557c4dc-k7kxj                    1/1     Running     0               2d9h    10.104.15.167   4am-node20   <none>           <none>
laion-test-3-minio-0                                              1/1     Running     0               31d     10.104.13.182   4am-node16   <none>           <none>
laion-test-3-minio-1                                              1/1     Running     0               31d     10.104.14.97    4am-node18   <none>           <none>
laion-test-3-minio-2                                              1/1     Running     0               31d     10.104.12.78    4am-node17   <none>           <none>
laion-test-3-minio-3                                              1/1     Running     0               31d     10.104.1.2      4am-node10   <none>           <none>
laion-test-3-pulsar-bookie-0                                      1/1     Running     0               31d     10.104.24.199   4am-node29   <none>           <none>
laion-test-3-pulsar-bookie-1                                      1/1     Running     0               31d     10.104.1.3      4am-node10   <none>           <none>
laion-test-3-pulsar-bookie-2                                      1/1     Running     0               31d     10.104.12.82    4am-node17   <none>           <none>
laion-test-3-pulsar-bookie-init-jkh2k                             0/1     Completed   0               31d     10.104.24.193   4am-node29   <none>           <none>
laion-test-3-pulsar-broker-0                                      1/1     Running     0               21d     10.104.9.148    4am-node14   <none>           <none>
laion-test-3-pulsar-proxy-0                                       1/1     Running     0               31d     10.104.13.180   4am-node16   <none>           <none>
laion-test-3-pulsar-pulsar-init-wr8kc                             0/1     Completed   0               31d     10.104.14.91    4am-node18   <none>           <none>
laion-test-3-pulsar-recovery-0                                    1/1     Running     0               31d     10.104.14.93    4am-node18   <none>           <none>
laion-test-3-pulsar-zookeeper-0                                   1/1     Running     8 (20d ago)     31d     10.104.14.98    4am-node18   <none>           <none>
laion-test-3-pulsar-zookeeper-1                                   1/1     Running     3 (10d ago)     31d     10.104.12.89    4am-node17   <none>           <none>
laion-test-3-pulsar-zookeeper-2                                   1/1     Running     6 (2d19h ago)   31d

**Comment by yanliang567** [comment]
keep it

**Comment by ThreadDao** [comment]
The issue now is that the segments hit by the query expression are on qn-51 and qn-49 respectively, but the query delay of qn-51 is much higher than that of qn-49.

![image](https://github.com/milvus-io/milvus/assets/27288593/b6be5f0f-2bc1-4df2-84b6-f3db5dcd3787)

the grafana link: 
https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&from=1698389152161&to=1698394277609&var-datasource=prometheus&var-cluster=&var-namespace=qa-milvus&var-instance=laion-test-100mry-1-op-33-9883&var-collection=All&var-app_name=milvus
