### ISSUE TITLE
[Bug]: There is only one node with an increase in memory, with a data volume of approximately 28 million and a vector dimension of 1024.

### ISSUE THREAD

**Issue by zk903956028** [milvus-io/milvus#27310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: V2.3.0
- Deployment mode(standalone or cluster): cluster with three nodes
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): milvus-sdk-java:2.3.1
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

As shown in the screenshot below, only the querynode occupies about 150G, while the other nodes occupy very little.

![企业微信截图_16953505241716](https://github.com/milvus-io/milvus/assets/35655035/26ce735e-af57-49af-b57b-c8e8567d2183)
![企业微信截图_16953503174644](https://github.com/milvus-io/milvus/assets/35655035/46732459-4d2e-40d1-904c-45509e621593)
![企业微信截图_16953503538633](https://github.com/milvus-io/milvus/assets/35655035/d555bef7-932d-40b4-b44b-aaeae894d70f)
![企业微信截图_16953503698919](https://github.com/milvus-io/milvus/assets/35655035/bb115a17-c6ce-4d9c-a81e-e832ae40f986)

### Expected Behavior

The desired cluster configuration aims for evenly distributed memory usage across all nodes.

### Steps To Reproduce

```markdown
no thing
```

### Milvus Log

no thing

### Anything else?

no thing

**Comment by zk903956028** [comment]
![企业微信截图_1695351055742](https://github.com/milvus-io/milvus/assets/35655035/5b397835-d903-4ec2-b8ff-528ac5165c68)

**Comment by yanliang567** [comment]
different pods play different roles in Milvus cluster. Querynode loads all the data into memory for search/query operatiosn, so it is expected to have the most memory usage.

/assign @zk903956028
/unassign

**Comment by zk903956028** [comment]
> different pods play different roles in Milvus cluster. Querynode loads all the data into memory for search/query operatiosn, so it is expected to have the most memory usage.
> 
> /assign @zk903956028 /unassign

Can the memory of only one node be utilized in the cluster version? Or can the querynode pod be distributed across multiple nodes?

**Comment by xiaofan-luan** [comment]
> > different pods play different roles in Milvus cluster. Querynode loads all the data into memory for search/query operatiosn, so it is expected to have the most memory usage.
> > /assign @zk903956028 /unassign
> 
> Can the memory of only one node be utilized in the cluster version? Or can the querynode pod be distributed across multiple nodes?

you can create multiple querynode, but only specified 1

**Comment by zk903956028** [comment]
> > > different pods play different roles in Milvus cluster. Querynode loads all the data into memory for search/query operatiosn, so it is expected to have the most memory usage.
> > > /assign @zk903956028 /unassign
> > 
> > 
> > Can the memory of only one node be utilized in the cluster version? Or can the querynode pod be distributed across multiple nodes?
> 
> you can create multiple querynode, but only specified 1
Is it done by modifying the 'replicas' parameter in the milvus_manifest.yaml file during installation? Can it be changed after the installation is complete?

**Comment by xiaofan-luan** [comment]
> > > 
> > 
> > 
> > Can the memory of only one node be utilized in the cluster version? Or can the querynode pod be distributed across multiple nodes?
> 
> you can create multiple querynode, but only specified 1

you can change any time as long as you have enough resources in your K8s cluster.
Helm install and K8s install both supportedt
