### ISSUE TITLE
[scalar-field-filtering] Server destroyed after `delete by id`

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#2732]
**Describe the bug**
No error raised 
No error logs print
```
4dc8020aa88d        registry.zilliz.com/milvus/engine:scalar-field-filtering-cpu-centos7-release   "/var/lib/milvus/bin…"    3 minutes ago       Exited (137) 3 minutes ago                                                        beautiful_shirley

```
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by fishpenguin** [comment]
Already fixed, waiting for testing.
