### ISSUE TITLE
[Bug]: when query (by PK) is performed with ignore_growing = False it returns outdated data for growing segment

### ISSUE THREAD

**Issue by ice-cronus** [milvus-io/milvus#27324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.0
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): etcd   
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.0
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 
- GPU: no
- Others: docker
```

### Current Behavior

When I update collection's state with upsert and dont call flush after that (and do not wait until autoflush is triggered, so updated data remains in growing segment), and after that perform a scalar query based on query by PK with `ignore_growing = False` it returns outdated (previously flushed) data.
If I call flush before the search, data is updated in response.
Sample:
```
    fields = [
        FieldSchema(name="user_id", dtype=DataType.VARCHAR, max_length=40, is_primary=True),
        FieldSchema(name="emotion_sequence", dtype=DataType.INT64),
        ...
 ]


    user_id = "1111"
    res = users.query(
        expr = f"user_id == \"{user_id}\"",
        offset = 0,
        limit = 1,
        output_fields = ["user_id","emotion_sequence"],
        ignore_growing = False,
    )
```

### Expected Behavior

Data is found, and there is an updated data in response, cuz `ignore_growing = False`

**Comment by yanliang567** [comment]
@ice-cronus please try setting consistency_level=strong in collection schema or search params, referring to https://milvus.io/docs/consistency.md#Consistency-levels and https://milvus.io/docs/search.md

/assign @ice-cronus 
/unassign

**Comment by xiaofan-luan** [comment]
> Well, I tried to decrease PROXY_TIME_TICK_INTERVAL to 10 ( from 200) and it syncs faster now. Will we get any issue with lower value (let's say 25-50 ms) on production workloads (millions of vectors, at least 500 qps)? What's the best value with tradeoff of search time and performance to set?

If you set PROXY_TIME_TICK_INTERVAL to smaller value, you will see many timetick in your log stream which may significantly slower your failure recovery and higher cpu usage.

I would recommend you to set PROXY_TIME_TICK_INTERVAL to 50ms or more.

This is something we could improve but Milvus is currently not designed for strong consistent query with high performance.
The other alternative is to introduce another system to support query?

**Comment by xiaofan-luan** [comment]
We are targeting to improve this on Milvus 3.0 but it's a long term plan

**Comment by yanliang567** [comment]
@ice-cronus here is a doc about consistency level for your reference: https://milvus.io/docs/consistency.md#Consistency-levels
