### ISSUE TITLE
[Bug]: JSON fields slowing down the search latency.

### ISSUE THREAD

**Issue by tommykoctur** [milvus-io/milvus#27328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.0 and 2.2.13 
- Deployment mode(standalone or cluster): Standalone and Cluster
- MQ type(rocksmq, pulsar or kafka):  Kafka (on cluster)   
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.0 and 2.2.13
- OS(Ubuntu or CentOS):  Ubuntu (standalone docker), amazon linux on Cluster
- CPU/Memory: 10core/20thread i9 intel/32 GB ... AMD on amazon EC2. Memory 32 per workernode 4 workernodes.
- GPU: NVIDIA A6000 on standalone/ Cpu only on cluster
- Others:
```

### Current Behavior

In our setup we are using vectors with D=768, index IVF_FLAT, and we have ~160K samples in indexed in DB.
When we use JSON columns in the structure then search latency is double (no filters, just vector search) compared to using VARCHAR columns wiht json.dumps encoded dictionaries in it.

This structure with the same data runs twice slower than structure below.
```python
fields = [
            FieldSchema(name='c_id', dtype=DataType.VARCHAR, description='xxx', max_length=300,
                        is_primary=True, auto_id=False),
            FieldSchema(name='text_string', dtype=DataType.VARCHAR, description='xxx',
                        max_length=65535),
            FieldSchema(name='weight', dtype=DataType.INT64, description='xxx', max_length=1),
            FieldSchema(name='metadata', dtype=DataType.JSON, description='xxx'),
            FieldSchema(name='sf', dtype=DataType.JSON, description='xxx', ),
            FieldSchema(name='nsf', dtype=DataType.JSON, description='xxx'),
            FieldSchema(name='embedding', dtype=DataType.FLOAT_VECTOR, description='xxx',
                        dim=self.n_dim)
        ]
```

```python
fields = [
            FieldSchema(name='c_id', dtype=DataType.VARCHAR, description='xxx', max_length=300,
                        is_primary=True, auto_id=False),
            FieldSchema(name='text_string', dtype=DataType.VARCHAR, description='xxx',
                        max_length=65535),
            FieldSchema(name='weight', dtype=DataType.INT64, description='xxx', max_length=1),
            FieldSchema(name='metadata', dtype=DataType.VARCHAR, description='xxx', max_length=65535),
            FieldSchema(name='sf', dtype=DataType.VARCHAR, description='xxx',
                        max_length=65535),
            FieldSchema(name='nsf', dtype=DataType.VARCHAR, description='xxxt',
                        max_length=65535),
            FieldSchema(name='embedding', dtype=DataType.FLOAT_VECTOR, description='xxx',
                        dim=self.n_dim)
        ]
```

### Expected Behavior

The roughly same latency in both cases when JSON field VARCHAR field is used.

### Anything else?

Behaviour tested on both versions, in both standalone and cluster.
Worth to mention that our workaround with VARCHAR field with json.dumps(metadata) works significantly faster on 2.2.13 compared to 2.3.0.

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version: 2.3.0 and 2.2.13 
> - Deployment mode(standalone or cluster): Standalone and Cluster
> - MQ type(rocksmq, pulsar or kafka):  Kafka (on cluster)   
> - SDK version(e.g. pymilvus v2.0.0rc2): 2.3.0 and 2.2.13
> - OS(Ubuntu or CentOS):  Ubuntu (standalone docker), amazon linux on Cluster
> - CPU/Memory: 10core/20thread i9 intel/32 GB ... AMD on amazon EC2. Memory 32 per workernode 4 workernodes.
> - GPU: NVIDIA A6000 on standalone/ Cpu only on cluster
> - Others:
> ```
> 
> ### Current Behavior
> In our setup we are using vectors with D=768, index IVF_FLAT, and we have ~160K samples in indexed in DB. When we use JSON columns in the structure then search latency is double (no filters, just vector search) compared to using VARCHAR columns wiht json.dumps encoded dictionaries in it.
> 
> This structure with the same data runs twice slower than structure below.
> 
> ```python
> fields = [
>             FieldSchema(name='c_id', dtype=DataType.VARCHAR, description='xxx', max_length=300,
>                         is_primary=True, auto_id=False),
>             FieldSchema(name='text_string', dtype=DataType.VARCHAR, description='xxx',
>                         max_length=65535),
>             FieldSchema(name='weight', dtype=DataType.INT64, description='xxx', max_length=1),
>             FieldSchema(name='metadata', dtype=DataType.JSON, description='xxx'),
>             FieldSchema(name='sf', dtype=DataType.JSON, description='xxx', ),
>             FieldSchema(name='nsf', dtype=DataType.JSON, description='xxx'),
>             FieldSchema(name='embedding', dtype=DataType.FLOAT_VECTOR, description='xxx',
>                         dim=self.n_dim)
>         ]
> ```
> 
> ```python
> fields = [
>             FieldSchema(name='c_id', dtype=DataType.VARCHAR, description='xxx', max_length=300,
>                         is_primary=True, auto_id=False),
>             FieldSchema(name='text_string', dtype=DataType.VARCHAR, description='xxx',
>                         max_length=65535),
>             FieldSchema(name='weight', dtype=DataType.INT64, description='xxx', max_length=1),
>             FieldSchema(name='metadata', dtype=DataType.VARCHAR, description='xxx', max_length=65535),
>             FieldSchema(name='sf', dtype=DataType.VARCHAR, description='xxx',
>                         max_length=65535),
>             FieldSchema(name='nsf', dtype=DataType.VARCHAR, description='xxxt',
>                         max_length=65535),
>             FieldSchema(name='embedding', dtype=DataType.FLOAT_VECTOR, description='xxx',
>                         dim=self.n_dim)
>         ]
> ```
> 
> ### Expected Behavior
> The roughly same latency in both cases when JSON field VARCHAR field is used.
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> Behaviour tested on both versions, in both standalone and cluster. Worth to mention that our workaround with VARCHAR field with json.dumps(metadata) works significantly faster on 2.2.13 compared to 2.3.0.

hi tommy, so you are saying you didn't filter on json and varchar field but the performance is doubled when you use varchar field?

1. did you specify output field?'
2. scan I see your test code if possible?

**Comment by xiaofan-luan** [comment]
@yanliang567 

please help on verifying this, thanks

**Comment by yanliang567** [comment]
working on it

**Comment by yanliang567** [comment]
@tommykoctur I tried to create 2 collections with the schema you provided above on a 2c8g standalone miluvs instance. Unfortunately, I did not reproduce the issue, the 2 collections  search latency is similar. I inserted 200k entities, indexed with ivf_flat, nilist=1024, searched with nprobe=32 without output_fields (or with output_fields=['c_id', 'sf'] and expr filters. 

could you please provide more info for us to investigate the issue?
1. refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs 
2. please attach the etcd backup for investigation？ Check this: https://github.com/milvus-io/birdwatcher for details about how to backup etcd with birdwatcher
3. please share the search code snippet if possible.

/assign @tommykoctur

**Comment by yanliang567** [comment]
@tommykoctur any updates?
