### ISSUE TITLE
[Bug]: The result of search iterator is not equal with inserted entity number with FLAT index and (COSINE or L2) metric type 

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#27325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230921-206cc14d
- Deployment mode(standalone or cluster):both
- MQ type(rocksmq, pulsar or kafka):  all  
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.0.post1.dev13
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The result of search iterator is not equal with inserted entity number with FLAT index and COSINE metric type

### Expected Behavior

The result of search iterator is equal with inserted entity number with FLAT index and COSINE metric type

### Steps To Reproduce

```python
from pymilvus import CollectionSchema, FieldSchema
from pymilvus import Collection
from pymilvus import connections
from pymilvus import DataType
from pymilvus import Partition
from pymilvus import utility
import time
import numpy as np
import random
import pandas as pd
import pyarrow.parquet as pq
import pyarrow as pa

connections.connect(host="***", port="19530")
dim = 768
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
bool_field = FieldSchema(name="bool", dtype=DataType.BOOL)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
schema = CollectionSchema(fields=[int64_field, float_field, bool_field, float_vector])
collection = Collection("test_search_iterator_6", schema=schema)
import random
nb = 1000000
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
insert_batch_num = 10000
for i in range(int(nb/insert_batch_num)):
    batch_vectors = vectors[i*insert_batch_num:(i+1)*insert_batch_num]
    print("get %d vectors" % len(batch_vectors))
    res = collection.insert([[i for i in range(i*insert_batch_num, (i+1)*insert_batch_num)], [np.float32(i) for i in range(i*insert_batch_num, (i+1)*insert_batch_num)], [np.bool_(i) for i in range(i*insert_batch_num, (i+1)*insert_batch_num)], batch_vectors])
    print("inserted %d %d " % (i, insert_batch_num))
index_param = {"index_type": "FLAT", "metric_type": "COSINE"}
collection.create_index("float_vector", index_param, index_name="index_name")
collection.load()
default_search_params = {"metric_type": "COSINE"}
collection.flush()
time.sleep(30)
collection.num_entities
batch_size = 10000
search_iterator = collection.search_iterator(vectors[:1], "float_vector", default_search_params, batch_size=batch_size)
page_idx = 0
distance_struct_array = []
while True:
     res = search_iterator.next()
     if len(res) == 0:
           print("search iteration finished, close")
           search_iterator.close()
           break
     print(len(res))
     page_idx += 1
     print(f"page{page_idx}-------------------------")
     for i in range(len(res)):
            distance_struct_array.append({'id': res[i].id, 'distance': res[i].distance})

print(len(distance_struct_array))
print(distance_struct_array[:100])
assert len(distance_struct_array)==nb
collection.drop()
```

**Comment by binbinlv** [comment]
1. Random data + FLAT+ L2: good

2. Random data + FLAT + COSINE: the result number is less than the inserted entity number

3. cohere data set + FLAT + L2: good

4. cohere data set + FLAT + COSINE: the result number is more than the inserted entity number

**Comment by binbinlv** [comment]
So from the trials, it seems that the metric type (COSINE) + search iterator is bad.

**Comment by MrPresent-Han** [comment]
I found that the result got by sdk is not strictly sorted by distance, there may be some flaws on reduce logic.
![SDF7K4mLlU](https://github.com/milvus-io/milvus/assets/116052805/1e32f8d2-9639-4b87-899e-699a9953ab5e)

**Comment by binbinlv** [comment]
More trials:
Using gist- 768 dataset, search_iterator (FLAT+L2) has the same issue too: (sometimes less, sometimes more):
```
...
page998-------------------------
1000
page999-------------------------
933
page1000-------------------------
34
page1001-------------------------
13
page1002-------------------------
10
page1003-------------------------
4
page1004-------------------------
search iteration finished, close
>>> len(distance_struct_array)
999994
```

**Comment by xiaofan-luan** [comment]
the distance is overflowed. 
float number only have 6/7 valid digit

**Comment by liliu-z** [comment]
> the distance is overflowed.
> float number only have 6/7 valid digit

Yes, but iterator is using distance to do truncation. Suspect there is some type transformation related precision loss. Under investigation

**Comment by MrPresent-Han** [comment]
> the distance is overflowed.
> float number only have 6/7 valid digit

1. in the image I post, the distance mutual disorder at the 6th bit not 7th bit
2. in Golang, float32 can present the different at the 6th digit, I tested this
3. in proxy, it logged out some disorder of score/distance from 6th bit

**Comment by cydrain** [comment]
add log in ReduceHelper::RefreshSearchResult() (after segcore reduce), see distance values are strictly sorted in descending order
![Screenshot from 2023-09-27 15-11-11](https://github.com/milvus-io/milvus/assets/3992404/aff67ad6-4bc6-430b-84cc-f7ee5f0421b4)

also add log in reduceSearchResultData (after proxy reduce), see distance value disordered from the 6th digit after the decimal pointer
![Screenshot from 2023-09-27 15-12-00](https://github.com/milvus-io/milvus/assets/3992404/5b24440c-f11c-47dc-8b84-ca77fe484888)

**Comment by jiaoew1991** [comment]
```
type SearchResultData struct {
	NumQueries           int64        `protobuf:"varint,1,opt,name=num_queries,json=numQueries,proto3" json:"num_queries,omitempty"`
	TopK                 int64        `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	FieldsData           []*FieldData `protobuf:"bytes,3,rep,name=fields_data,json=fieldsData,proto3" json:"fields_data,omitempty"`
	Scores               []float32    `protobuf:"fixed32,4,rep,packed,name=scores,proto3" json:"scores,omitempty"`
	Ids                  *IDs         `protobuf:"bytes,5,opt,name=ids,proto3" json:"ids,omitempty"`
	Topks                []int64      `protobuf:"varint,6,rep,packed,name=topks,proto3" json:"topks,omitempty"`
	OutputFields         []string     `protobuf:"bytes,7,rep,name=output_fields,json=outputFields,proto3" json:"output_fields,omitempty"`
}
```

I think the reason is the type of Scores is float32

**Comment by cydrain** [comment]
we use float32 in both knowhere and segcore

**Comment by binbinlv** [comment]
do we have any update?

**Comment by yanliang567** [comment]
/assign @jiaoew1991 
please help to take a look for this issue.

**Comment by MrPresent-Han** [comment]
part of the reason: the reduce logic for search doesn't promise strict distance decling relationship and may return larger distances

**Comment by MrPresent-Han** [comment]
Additionally, the judgement for float value relationship ignored the precision too much, resulting the disorder when reducing inside segcore:
![ghLIQBsC4r](https://github.com/milvus-io/milvus/assets/116052805/1f9c782d-7e8c-4e57-bab5-5e774133d24e)
when commenting this piece of code, the disorder disappear

**Comment by xiaofan-luan** [comment]
is there a specify reason we overwrite the > operator?

**Comment by MrPresent-Han** [comment]
> is there a specify reason we overwrite the > operator?

segcore reduce used heap to maintain the top with highest score

**Comment by MrPresent-Han** [comment]
this version of fix has been testified before merging, please retest it again
/assign [binbinlv](https://github.com/binbinlv)

**Comment by binbinlv** [comment]
Verified and fixed.
pymilvus: 2.3.4
milvus: 2.3-20231208-10d32246-amd64

results:
```
page91-------------------------
10000
page92-------------------------
10000
page93-------------------------
10000
page94-------------------------
10000
page95-------------------------
10000
page96-------------------------
10000
page97-------------------------
10000
page98-------------------------
10000
page99-------------------------
10000
page100-------------------------
search iteration finished, close
1000000
```

**Comment by binbinlv** [comment]
Will verify master branch when the master latest image is generated, cancel urgent first.

**Comment by binbinlv** [comment]
Verified and fixed in master branch.
pymilvus: 2.3.4 (or 2.4.0rc5)
milvus: master-20231218-438f39e2

results: running different vectors for multiple times.
```
page90-------------------------
10000
page91-------------------------
10000
page92-------------------------
10000
page93-------------------------
10000
page94-------------------------
10000
page95-------------------------
10000
page96-------------------------
10000
page97-------------------------
10000
page98-------------------------
10000
page99-------------------------
10000
page100-------------------------
search iteration finished, close
1000000
```
