### ISSUE TITLE
[Bug]: CVE list of etcd in milvus helm? Can we fix them or upgrade a new etcd version?

### ISSUE THREAD

**Issue by weiZhenkun** [milvus-io/milvus#27339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvus 2.3.1
- Milvus helm version: milvus helm 4.1.2
```

### Current Behavior

- Milvus has built a milvus own etcd image, which has not upgrade for 7 months https://github.com/milvus-io/bitnami-docker-etcd/blob/3.5.0-new/3.5/debian-11/Dockerfile.

- We cannot use [bitnami-etcd](https://hub.docker.com/r/bitnami/etcd/) directly, so can you upgrade this etcd image and make it without any cve?

- Security compliance is also important for an open source project, because it determines whether a company that pays attention to security compliance can use the project?

- Here is the CVE list: [issues-etcd.xlsx](https://github.com/milvus-io/milvus/files/12711300/issues-etcd.xlsx)

### Expected Behavior

Any user can use milvus without any CVE.

**Comment by xiaofan-luan** [comment]
/assign @zwd1208 
can we take a look at this?

**Comment by zwd1208** [comment]
@weiZhenkun
We need to update the etcd base image version, and we need to test it. maybe we will release it with the next milvus release.

/unassign
/assign @LoveEachDay

**Comment by weiZhenkun** [comment]
milvusdb/etcd:3.5.5-r2 (debian 11.6)

1. Total: 110 (UNKNOWN: 0, LOW: 66, MEDIUM: **24**, HIGH: **18**, CRITICAL: 2)


milvusdb/etcd:v3.5.5-r3 (debian 11.8))

1. Total: 85 (UNKNOWN: 0, LOW: 66, MEDIUM: **11**, HIGH: 6, CRITICAL: 2)

bitnami/minideb:bullseye (debian 11.8)

1. Total: 83 (UNKNOWN: 0, LOW: 66, MEDIUM: **9**, HIGH: 6, CRITICAL: 2)

It is a big process for 
Can you adopt the latest minideb:bullseye and build a new version the milvusdb/etcd:v3.5.5-r4, then apply into the milvus chart?

Can we using the milvusdb/etcd:v3.5.5-r3 in our prod env?

**Comment by LoveEachDay** [comment]
@weiZhenkun We have tested the newly build `milvusdb/etcd:v3.5.5-r3` with the most recent `minideb:bullseye`. It still has 2 critical cve issues.

**Comment by weiZhenkun** [comment]
@LoveEachDay  Yes, you are right, but the CVE number have changed from 110 to 85. As the  Bitnami CVE policies says, these 2 critical CVEs must be not fixable CVEs. So it is a version worth upgrading to.

**Comment by LoveEachDay** [comment]
@weiZhenkun You can try to use `milvusdb/etcd:v3.5.5-r3` instead of `milvusdb/etcd:v3.5.5-r2`. We have released the new version at dockerhub.
