### ISSUE TITLE
[Bug]: the sha256 numbers are not match for Milvus 2.3.0 & Milvus 2.3.1 images

### ISSUE THREAD

**Issue by weiZhenkun** [milvus-io/milvus#27332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.0 & 2.3.1
```

### Current Behavior

<img width="1157" alt="7e0ac63158eacfacca43a3529820e51" src="https://github.com/milvus-io/milvus/assets/27683687/80ad8947-0b98-460f-b5cb-ba7faa494b98">
<img width="1078" alt="888a3e25be1b87dccc29c963ced8154" src="https://github.com/milvus-io/milvus/assets/27683687/9d82a679-f10c-4784-8ac1-880ffa2ea69f">

**Comment by xiaofan-luan** [comment]
/assign @LoveEachDay 
could you help on taking a look?

**Comment by LoveEachDay** [comment]
@weiZhenkun From milvus v2.3.0,  we have published the milvus images with two cpu platforms: `linux/amd64` and `linux/arm64/v8`.

![image](https://github.com/milvus-io/milvus/assets/1573213/137cb6a1-4541-4106-97e4-c1aa1c360940)

By default, `docker pull` will try to pull the image depends on your cpu type(amd64/arm64). 

According to this issue(https://github.com/docker/hub-feedback/issues/1925), DockerHub has some issue to show image digest with images that has multiple arch supports.

We can reproduce the same like the above attached images:
<img width="1524" alt="image" src="https://github.com/milvus-io/milvus/assets/1573213/e0062989-50c2-4107-b6be-81aee0b5697b">
