### ISSUE TITLE
[Bug]: Milvus Down and pods go into crashloop ["unable to create role because the number of roles has reached the limit"] [max_role_num=10]

### ISSUE THREAD

**Issue by karthikmsc05** [milvus-io/milvus#27356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.12
- Deployment mode(standalone or cluster): AKS
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 16/64
- GPU: 
- Others:
```

### Current Behavior

The below pods are going crashloop backoff status and the pods are not coming up and hence not able to bring up milvus.

Pods that are down:

milvus-dev-cluster-datacoord-5d76f767c5-kpcft
milvus-dev-cluster-datanode-ccd499f84-9bp6z
milvus-dev-cluster-indexcoord-dff84989d-zhvgc
milvus-dev-cluster-proxy-5456fb5c4b-kdkb7
milvus-dev-cluster-querycoord-79c857c68f-49lkw
milvus-dev-cluster-rootcoord-66448c4959-mvs9j

### Expected Behavior

the pods should come up and able to access milvus

### Milvus Log

[2023/09/25 08:57:43.568 +00:00] [ERROR] [rootcoord/meta_table.go:1185] ["unable to create role because the number of roles has reached the limit"] [max_role_num=10] [stack="github.com/milvus-io/milvus/internal/rootcoord.(*MetaTable).CreateRole\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/meta_table.go:1185\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).initRbac\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:553\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).initInternal\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:490\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).Init.func2\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:532\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:68\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:59\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).Init\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:531\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:225\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:155\ngithub.com/milvus-io/milvus/cmd/components.(*RootCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/root_coord.go:56\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:120"]

[2023/09/25 08:57:43.569 +00:00] [ERROR] [components/root_coord.go:57] ["RootCoord starts error"] [error="unable to create role because the number of roles has reached the limit"] [stack="github.com/milvus-io/milvus/cmd/components.(*RootCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/root_coord.go:57\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:120"]

2023/09/25 09:03:24.089 +00:00] [ERROR] [grpcclient/client.go:353] ["ClientBase ReCall grpc second call get error"] [role=rootcoord] [error="err: find no available rootcoord, check rootcoord state\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:352 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:130 github.com/milvus-io/milvus/internal/distributed/rootcoord/client.(*Client).GetComponentStates\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:67 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1\n/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:42 github.com/milvus-io/milvus/internal/util/retry.Do\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:91 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:106 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentHealthy\n/go/src/github.com/milvus-io/milvus/internal/distributed/datanode/service.go:280 github.com/milvus-io/milvus/internal/distributed/datanode.(*Server).init\n/go/src/github.com/milvus-io/milvus/internal/distributed/datanode/service.go:177 github.com/milvus-io/milvus/internal/distributed/datanode.(*Server).Run\n/go/src/github.com/milvus-io/milvus/cmd/components/data_node.go:52 github.com/milvus-io/milvus/cmd/components.(*DataNode).Run\n"] [stack="github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:353\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord/client.(*Client).GetComponentStates\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:130\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:67\ngithub.com/milvus-io/milvus/internal/util/retry.Do\n\t/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:42\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:91\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentHealthy\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:106\ngithub.com/milvus-io/milvus/internal/distributed/datanode.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datanode/service.go:280\ngithub.com/milvus-io/milvus/internal/distributed/datanode.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datanode/service.go:177\ngithub.com/milvus-io/milvus/cmd/components.(*DataNode).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/data_node.go:52\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:120"

**Comment by xiaofan-luan** [comment]
it is because you chaned to rbac limit

**Comment by xiaofan-luan** [comment]
you simply need to change the rbac limit to more than 10 @karthikmsc05

**Comment by yanliang567** [comment]
@NicoYuan1986 please help to check if there are cases for the limit of rbac roles. I think Milvus shall not down/crash in any cases.
/assign @NicoYuan1986 
/unassign

**Comment by SimFG** [comment]
@karthikmsc05 it will be fixed, details: https://github.com/milvus-io/milvus/pull/27361
As a temporary solution, you can adjust the upper limit of role, key: proxy.maxRoleNum

**Comment by IndhumathiParamasivam** [comment]
Hi @SimFG @yanliang567 @xiaofan-luan ,
We have already set the **proxy.maxRoleNum to 100** and deployed the milvus in the cluster and it was working fine. When user created the roles, the pod crashed, and it is down stating the below error message:

[Milvus Down and pods go into crashloop ["unable to create role because the number of roles has reached the limit"] **[max_role_num=10]]**(https://github.com/milvus-io/milvus/issues/27356#top)

Please find the configuration below for reference:
proxy:
  enabled: true
  replicas: 1
  resources: {}
  nodeSelector: 
    agentpool: milvusdevusr
  affinity: {}
  tolerations: []
  extraEnv: []
  heaptrack:
    enabled: false
  profiling:
    enabled: false  # Enable live profiling
  http:
    enabled: true  # whether to enable http rest server
    debugMode:
      enabled: false
  **maxRoleNum: 100
  maxUserNum: 500**

> @karthikmsc05 it will be fixed, details: #27361 As a temporary solution, you can adjust the upper limit of role, key: proxy.maxRoleNum

**Comment by SimFG** [comment]
@IndhumathiParamasivam Actually, I don't quite understand what you mean. Does it mean that even if the config is changed, this problem still occurs?

**Comment by IndhumathiParamasivam** [comment]
> @IndhumathiParamasivam Actually, I don't quite understand what you mean. Does it mean that even if the config is changed, this problem still occurs?

@SimFG ,
yes, we tried setting up the maxRoleNum  to 100, still it is not working.

**Comment by SimFG** [comment]
@IndhumathiParamasivam you should stop the milvus instance, and change the `milvus.yaml` config. If you use the docker to deploy the milvus, you need to check the `milvus.yaml` (path: /milvus/configs/milvus.yaml) in the docker.

**Comment by xiaofan-luan** [comment]
> @SimFG , We are using helm chart to deploy milvus into Kubernetes cluster

How did you change your config? 

you should check this docuemnt https://milvus.io/docs/configure-helm.md

**Comment by SimFG** [comment]
@IndhumathiParamasivam 
I will close the issue. If you meet other problem, please open a new issue
