### ISSUE TITLE
[Bug]: After running the database for 2 days, it suddenly failed to parse the expr expression. 

### ISSUE THREAD

**Issue by zk903956028** [milvus-io/milvus#27352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.0
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![企业微信截图_16956351805901](https://github.com/milvus-io/milvus/assets/35655035/e2cc1c70-772d-46d9-a252-d95be32afb57)

### Expected Behavior

The query is executed normally

### Steps To Reproduce

```markdown
no thing
```

### Milvus Log

no thing

### Anything else?

no thing

**Comment by yanliang567** [comment]
@zk903956028 could you please provide the collection schema and refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @zk903956028 
/unassign
