### ISSUE TITLE
[Bug]: Getting wrong results when doing cosine similarity retrieval

### ISSUE THREAD

**Issue by adiiityap** [milvus-io/milvus#27368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.0
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.3.0
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 8/32
- GPU: NA
- Others: NA
```

### Current Behavior

When I'm trying to do vector search by setting limit <=99 then getting results as expected but when i set the limit >= 100 then the cosine scores and the result data is different. For ex. 
when setting limit = 99 (vector search)
result : rfp.xlsx 0.6343
rfp_structured 0.631
data_py.docx 0.612
healthcarew.pdf 0.56.......
when setting limit = 100 (vector search)
result : idc_san.csv 0.181
idc_2021 0.179
rfp.xlsx 0.173
rfp.csv 0.162

The result data and score both change

### Expected Behavior

when i set the limit = 100 the expected behaviour is that i get same top100 results as when i set limit as 99 , with just the 100th entry getting added to the result

### Steps To Reproduce

```markdown
1. locally setup milvus standalone 2.3.0
2. create a flat index with cosine similarity metric
3. then do bulk insert of the data and then perform vector search on the vector column
```

### Anything else?

This issue persists only for 1 out of 10 collections it is working fine for the rest of the collections(i.e. when setting limit as 99 or >100) but for a single collection getting this weird behaviour

**Comment by xiaofan-luan** [comment]
please try 2.3.1 and this should be already be solved
