### ISSUE TITLE
[Bug]: boost build error

### ISSUE THREAD

**Issue by BUPTAnderson** [milvus-io/milvus#27370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.1
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

<code>
error: Invalid property '<boost.locale.iconv.lib>libc': unknown feature 'boost.locale.iconv.lib'.
</code>

### Expected Behavior

build success

### Steps To Reproduce

```markdown
cd /opt/milvus
make
```

### Milvus Log

<code>
boost/1.82.0: Applying build-requirement: b2/4.9.6
boost/1.82.0: WARN: Build folder is dirty, removing it: /home/hadoop/.conan/data/boost/1.82.0/_/_/build/9bb382e9c85821936d59f1c4ea5134768df38de2
boost/1.82.0: Building your package in /home/hadoop/.conan/data/boost/1.82.0/_/_/build/9bb382e9c85821936d59f1c4ea5134768df38de2
boost/1.82.0: Generator txt created conanbuildinfo.txt
boost/1.82.0: Calling generate()
boost/1.82.0: Aggregating env generators
boost/1.82.0: Calling build()
boost/1.82.0: WARN: replace_in_file didn't find pattern '/* thread_local */' in '/home/hadoop/.conan/data/boost/1.82.0/_/_/source/src/boost/stacktrace/detail/libbacktrace_impls.hpp' file.
boost/1.82.0: WARN: replace_in_file didn't find pattern '/* static __thread */' in '/home/hadoop/.conan/data/boost/1.82.0/_/_/source/src/boost/stacktrace/detail/libbacktrace_impls.hpp' file.
boost/1.82.0: WARN: replace_in_file didn't find pattern 'local generic-os = [ set.difference $(all-os) : aix darwin vxworks solaris osf hpux ] ;' in '/home/hadoop/.conan/data/boost/1.82.0/_/_/source/src/tools/build/src/tools/gcc.jam' file.
boost/1.82.0: WARN: replace_in_file didn't find pattern 'local no-threading = android beos haiku sgi darwin vxworks ;' in '/home/hadoop/.conan/data/boost/1.82.0/_/_/source/src/tools/build/src/tools/gcc.jam' file.
boost/1.82.0: WARN: replace_in_file didn't find pattern '    <conditional>@numa' in '/home/hadoop/.conan/data/boost/1.82.0/_/_/source/src/libs/fiber/build/Jamfile.v2' file.
boost/1.82.0: WARN: Patching user-config.jam
boost/1.82.0: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
boost/1.82.0: WARN:
using zlib : 1.2.13 : <include>"/home/hadoop/.conan/data/zlib/1.2.13/_/_/package/dfbe50feef7f3c6223a476cd5aeadb687084a646/include" <search>"/home/hadoop/.conan/data/zlib/1.2.13/_/_/package/dfbe50feef7f3c6223a476cd5aeadb687084a646/lib" <name>z ;
using bzip2 : 1.0.8 : <include>"/home/hadoop/.conan/data/bzip2/1.0.8/_/_/package/c32092bf4d4bb47cf962af898e02823f499b017e/include" <search>"/home/hadoop/.conan/data/bzip2/1.0.8/_/_/package/c32092bf4d4bb47cf962af898e02823f499b017e/lib" <name>bz2 ;
using "gcc" :  :  "/opt/rh/devtoolset-11/root/usr/bin/g++" :
<compileflags>"-I/home/hadoop/.conan/data/libbacktrace/cci.20210118/_/_/package/dfbe50feef7f3c6223a476cd5aeadb687084a646/include" <linkflags>"-L/home/hadoop/.conan/data/libbacktrace/cci.20210118/_/_/package/dfbe50feef7f3c6223a476cd5aeadb687084a646/lib"  ;
boost/1.82.0: WARN: b2 -q numa=on target-os=linux architecture=x86 address-model=64 binary-format=elf abi=sysv --layout=system --user-config=/home/hadoop/.conan/data/boost/1.82.0/_/_/source/src/tools/build/user-config.jam -sNO_ZLIB=0 -sNO_BZIP2=0 -sNO_LZMA=1 -sNO_ZSTD=1 boost.locale.icu=off --disable-icu boost.locale.iconv=on boost.locale.iconv.lib=libc threading=multi visibility=hidden link=static variant=release --with-atomic --with-chrono --with-container --with-context --with-contract --with-coroutine --with-date_time --with-exception --with-fiber --with-filesystem --with-graph --with-iostreams --with-json --with-locale --with-log --with-math --with-nowide --with-program_options --with-random --with-regex --with-serialization --with-stacktrace --with-system --with-test --with-thread --with-timer --with-type_erasure --with-url --with-wave toolset=gcc define=_GLIBCXX_USE_CXX11_ABI=0 pch=on -sLIBBACKTRACE_PATH=/home/hadoop/.conan/data/libbacktrace/cci.20210118/_/_/package/dfbe50feef7f3c6223a476cd5aeadb687084a646 linkflags="" cxxflags="-fPIC -DBOOST_STACKTRACE_ADDR2LINE_LOCATION=/usr/bin/addr2line" install --prefix=/home/hadoop/.conan/data/boost/1.82.0/_/_/package/9bb382e9c85821936d59f1c4ea5134768df38de2 -j32 --abbreviate-paths -d0 --debug-configuration --build-dir="/home/hadoop/.conan/data/boost/1.82.0/_/_/build/9bb382e9c85821936d59f1c4ea5134768df38de2/build-release"
notice: found boost-build.jam at /home/hadoop/.conan/data/boost/1.82.0/_/_/source/src/boost-build.jam
notice: loading B2 from /home/hadoop/.conan/data/b2/4.9.6/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/.b2/kernel/bootstrap.jam
notice: Searching '/etc' '/home/hadoop' '/home/hadoop/.conan/data/b2/4.9.6/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/.b2/kernel' '/home/hadoop/.conan/data/b2/4.9.6/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/.b2/util' '/home/hadoop/.conan/data/b2/4.9.6/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/.b2/build' '/home/hadoop/.conan/data/b2/4.9.6/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/.b2/tools' '/home/hadoop/.conan/data/b2/4.9.6/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/.b2/contrib' '/home/hadoop/.conan/data/b2/4.9.6/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/.b2/.' for site-config configuration file 'site-config.jam'.
notice: Configuration file 'site-config.jam' not found in '/etc' '/home/hadoop' '/home/hadoop/.conan/data/b2/4.9.6/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/.b2/kernel' '/home/hadoop/.conan/data/b2/4.9.6/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/.b2/util' '/home/hadoop/.conan/data/b2/4.9.6/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/.b2/build' '/home/hadoop/.conan/data/b2/4.9.6/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/.b2/tools' '/home/hadoop/.conan/data/b2/4.9.6/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/.b2/contrib' '/home/hadoop/.conan/data/b2/4.9.6/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/.b2/.'.
notice: Loading explicitly specified user configuration file:
    /home/hadoop/.conan/data/boost/1.82.0/_/_/source/src/tools/build/user-config.jam
notice: Searching '/home/hadoop/.conan/data/boost/1.82.0/_/_/source/src/tools/build' for user-config configuration file 'user-config.jam'.
notice: Loading user-config configuration file 'user-config.jam' from '/home/hadoop/.conan/data/boost/1.82.0/_/_/source/src/tools/build'.
notice: [zlib] Using pre-installed library
notice: [zlib] Condition
notice: [bzip2] Using pre-installed library
notice: [bzip2] Condition
notice: will use '/opt/rh/devtoolset-11/root/usr/bin/g++' for gcc, condition <toolset>gcc-11
notice: using gcc libraries :: <toolset>gcc-11 :: /opt/rh/devtoolset-11/root/usr/bin /opt/rh/devtoolset-11/root/usr/lib /opt/rh/devtoolset-11/root/usr/lib32 /opt/rh/devtoolset-11/root/usr/lib64
notice: using gcc archiver :: <toolset>gcc-11 :: /opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ar
warning: toolset gcc initialization: can not find tool windres
warning: initialized from /home/hadoop/.conan/data/boost/1.82.0/_/_/source/src/tools/build/user-config.jam:5
notice: using rc compiler :: <toolset>gcc-11 :: /opt/rh/devtoolset-11/root/usr/bin/as
notice: Searching '.' for project-config configuration file 'project-config.jam'.
notice: Loading project-config configuration file 'project-config.jam' from '.'.
notice: [zlib] zlib is already configured
notice: [bzip2] bzip is already configured
notice: iostreams: not using lzma compression
notice: iostreams: not using zstd compression
notice: [python-cfg] Configuring python...
notice: [python-cfg] Checking interpreter command "python"...
notice: [python-cfg] running command 'python -c "from sys import *; print('version=%d.%d\nplatform=%s\nprefix=%s\nexec_prefix=%s\nexecutable=%s' % (version_info[0],version_info[1],platform,prefix,exec_prefix,executable))" 2>&1'
notice: [python-cfg] ...requested configuration matched!
notice: [python-cfg] Details of this Python configuration:
notice: [python-cfg]   interpreter command: "python"
notice: [python-cfg]   include path: "/usr/include/python3.6m"
notice: [python-cfg]   library path: "/usr/lib/python3.6/config" "/usr/lib"
notice: [python-cfg] Checking for NumPy...
notice: [python-cfg] running command 'python -c "import sys; sys.stderr = sys.stdout; import numpy; print(numpy.get_include())"'
notice: [python-cfg] NumPy enabled
/home/hadoop/.conan/data/b2/4.9.6/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/.b2/build/property.jam:354: in validate1 from module property
error: Invalid property '<boost.locale.iconv.lib>libc': unknown feature 'boost.locale.iconv.lib'.
/home/hadoop/.conan/data/b2/4.9.6/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/.b2/build/property.jam:363: in property.validate from module property
/home/hadoop/.conan/data/b2/4.9.6/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/.b2/build/build-request.jam:286: in convert-command-line-element from module build-request
/home/hadoop/.conan/data/b2/4.9.6/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/.b2/build/build-request.jam:222: in build-request.convert-command-line-elements from module build-request
/home/hadoop/.conan/data/b2/4.9.6/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/.b2/build-system.jam:774: in load from module build-system
/home/hadoop/.conan/data/b2/4.9.6/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/.b2/kernel/modules.jam:294: in import from module modules
/home/hadoop/.conan/data/b2/4.9.6/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/.b2/kernel/bootstrap.jam:135: in module scope from module

boost/1.82.0:
boost/1.82.0: ERROR: Package '9bb382e9c85821936d59f1c4ea5134768df38de2' build failed
boost/1.82.0: WARN: Build folder /home/hadoop/.conan/data/boost/1.82.0/_/_/build/9bb382e9c85821936d59f1c4ea5134768df38de2/build-release
ERROR: boost/1.82.0: Error in build() method, line 887
	self.run(full_command)
	ConanException: Error 1 while executing b2 -q numa=on target-os=linux architecture=x86 address-model=64 binary-format=elf abi=sysv --layout=system --user-config=/home/hadoop/.conan/data/boost/1.82.0/_/_/source/src/tools/build/user-config.jam -sNO_ZLIB=0 -sNO_BZIP2=0 -sNO_LZMA=1 -sNO_ZSTD=1 boost.locale.icu=off --disable-icu boost.locale.iconv=on boost.locale.iconv.lib=libc threading=multi visibility=hidden link=static variant=release --with-atomic --with-chrono --with-container --with-context --with-contract --with-coroutine --with-date_time --with-exception --with-fiber --with-filesystem --with-graph --with-iostreams --with-json --with-locale --with-log --with-math --with-nowide --with-program_options --with-random --with-regex --with-serialization --with-stacktrace --with-system --with-test --with-thread --with-timer --with-type_erasure --with-url --with-wave toolset=gcc define=_GLIBCXX_USE_CXX11_ABI=0 pch=on -sLIBBACKTRACE_PATH=/home/hadoop/.conan/data/libbacktrace/cci.20210118/_/_/package/dfbe50feef7f3c6223a476cd5aeadb687084a646 linkflags="" cxxflags="-fPIC -DBOOST_STACKTRACE_ADDR2LINE_LOCATION=/usr/bin/addr2line" install --prefix=/home/hadoop/.conan/data/boost/1.82.0/_/_/package/9bb382e9c85821936d59f1c4ea5134768df38de2 -j32 --abbreviate-paths -d0 --debug-configuration --build-dir="/home/hadoop/.conan/data/boost/1.82.0/_/_/build/9bb382e9c85821936d59f1c4ea5134768df38de2/build-release"
conan install failed
make: *** [Makefile:162: build-3rdparty] Error 1
make: Leaving directory '/opt/milvus'
</code>

**Comment by jiaoew1991** [comment]
@BUPTAnderson It seems that you are trying to compile Milvus on the RHEL series of Linux, and there may be missing system libraries on your system causing this. Why not try using the Milvus Docker image? This way, you won't have these compilation issues.

**Comment by BUPTAnderson** [comment]
@jiaoew1991 I have solve this issue by skip the config check. but it occurred a another error!
```
make[3]: Leaving directory '/opt/milvus/cmake_build'
make[3]: Entering directory '/opt/milvus/cmake_build'
[ 62%] Building CXX object src/common/CMakeFiles/milvus_common.dir/Schema.cpp.o
[ 62%] Building CXX object src/common/CMakeFiles/milvus_common.dir/SystemProperty.cpp.o
[ 62%] Building CXX object src/common/CMakeFiles/milvus_common.dir/Slice.cpp.o
[ 62%] Building CXX object src/common/CMakeFiles/milvus_common.dir/init_c.cpp.o
[ 63%] Building CXX object src/common/CMakeFiles/milvus_common.dir/Common.cpp.o
[ 63%] Building CXX object src/common/CMakeFiles/milvus_common.dir/RangeSearchHelper.cpp.o
[ 63%] Building CXX object src/common/CMakeFiles/milvus_common.dir/IndexMeta.cpp.o
[ 64%] Linking CXX shared library ../../lib/libmilvus_common.so
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: cannot find -latomic
collect2: error: ld returned 1 exit status
make[3]: *** [src/common/CMakeFiles/milvus_common.dir/build.make:281: lib/libmilvus_common.so] Error 1
make[3]: Leaving directory '/opt/milvus/cmake_build'
make[2]: *** [CMakeFiles/Makefile2:1786: src/common/CMakeFiles/milvus_common.dir/all] Error 2
make[2]: Leaving directory '/opt/milvus/cmake_build'
make[1]: *** [Makefile:146: all] Error 2
make[1]: Leaving directory '/opt/milvus/cmake_build'
make: *** [Makefile:172: build-cpp] Error 1
make: Leaving directory '/opt/milvus'
```

because I deployde milvus on centos7 before, i want to update it to the latest version.

**Comment by jiaoew1991** [comment]
> @jiaoew1991 I have solve this issue by skip the config check. but it occurred a another error!
> 
> ```
> make[3]: Leaving directory '/opt/milvus/cmake_build'
> make[3]: Entering directory '/opt/milvus/cmake_build'
> [ 62%] Building CXX object src/common/CMakeFiles/milvus_common.dir/Schema.cpp.o
> [ 62%] Building CXX object src/common/CMakeFiles/milvus_common.dir/SystemProperty.cpp.o
> [ 62%] Building CXX object src/common/CMakeFiles/milvus_common.dir/Slice.cpp.o
> [ 62%] Building CXX object src/common/CMakeFiles/milvus_common.dir/init_c.cpp.o
> [ 63%] Building CXX object src/common/CMakeFiles/milvus_common.dir/Common.cpp.o
> [ 63%] Building CXX object src/common/CMakeFiles/milvus_common.dir/RangeSearchHelper.cpp.o
> [ 63%] Building CXX object src/common/CMakeFiles/milvus_common.dir/IndexMeta.cpp.o
> [ 64%] Linking CXX shared library ../../lib/libmilvus_common.so
> /opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: cannot find -latomic
> collect2: error: ld returned 1 exit status
> make[3]: *** [src/common/CMakeFiles/milvus_common.dir/build.make:281: lib/libmilvus_common.so] Error 1
> make[3]: Leaving directory '/opt/milvus/cmake_build'
> make[2]: *** [CMakeFiles/Makefile2:1786: src/common/CMakeFiles/milvus_common.dir/all] Error 2
> make[2]: Leaving directory '/opt/milvus/cmake_build'
> make[1]: *** [Makefile:146: all] Error 2
> make[1]: Leaving directory '/opt/milvus/cmake_build'
> make: *** [Makefile:172: build-cpp] Error 1
> make: Leaving directory '/opt/milvus'
> ```
> 
> because I deployed milvus on centos7 before, i want to update it to the latest version.

You should install libatomic to resolve this problem
```
yum install -y libatomic 
```

**Comment by BUPTAnderson** [comment]
> > @jiaoew1991 I have solve this issue by skip the config check. but it occurred a another error!
> > ```
> > make[3]: Leaving directory '/opt/milvus/cmake_build'
> > make[3]: Entering directory '/opt/milvus/cmake_build'
> > [ 62%] Building CXX object src/common/CMakeFiles/milvus_common.dir/Schema.cpp.o
> > [ 62%] Building CXX object src/common/CMakeFiles/milvus_common.dir/SystemProperty.cpp.o
> > [ 62%] Building CXX object src/common/CMakeFiles/milvus_common.dir/Slice.cpp.o
> > [ 62%] Building CXX object src/common/CMakeFiles/milvus_common.dir/init_c.cpp.o
> > [ 63%] Building CXX object src/common/CMakeFiles/milvus_common.dir/Common.cpp.o
> > [ 63%] Building CXX object src/common/CMakeFiles/milvus_common.dir/RangeSearchHelper.cpp.o
> > [ 63%] Building CXX object src/common/CMakeFiles/milvus_common.dir/IndexMeta.cpp.o
> > [ 64%] Linking CXX shared library ../../lib/libmilvus_common.so
> > /opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: cannot find -latomic
> > collect2: error: ld returned 1 exit status
> > make[3]: *** [src/common/CMakeFiles/milvus_common.dir/build.make:281: lib/libmilvus_common.so] Error 1
> > make[3]: Leaving directory '/opt/milvus/cmake_build'
> > make[2]: *** [CMakeFiles/Makefile2:1786: src/common/CMakeFiles/milvus_common.dir/all] Error 2
> > make[2]: Leaving directory '/opt/milvus/cmake_build'
> > make[1]: *** [Makefile:146: all] Error 2
> > make[1]: Leaving directory '/opt/milvus/cmake_build'
> > make: *** [Makefile:172: build-cpp] Error 1
> > make: Leaving directory '/opt/milvus'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > because I deployed milvus on centos7 before, i want to update it to the latest version.
> 
> You should install libatomic to resolve this problem
> 
> ```
> yum install -y libatomic 
> ```

I solved this problem by exec:

`yum install devtoolset-11-libatomic-devel`

and at last, it print another error:
```
--
-- Milvus Build Option options:
--   Build GPU version                                                      OFF   [default] [MILVUS_GPU_VERSION]
--
-- Thirdparty options:
--   Method to use for acquiring MILVUS's build dependencies                "BUNDLED" [default] [MILVUS_DEPENDENCY_SOURCE] [AUTO|BUNDLED|SYSTEM]
--   Use ccache when compiling (if available)                               ON        [default] [MILVUS_USE_CCACHE]
--   Show output from ExternalProjects rather than just logging to files    ON        [default] [MILVUS_VERBOSE_THIRDPARTY_BUILD]
--
-- Test and benchmark options:
--   Build the MILVUS googletest unit tests                                 OFF   [default] [MILVUS_BUILD_TESTS]
-- Thirdparty downloaded file path: /opt/milvus/cmake_build/3rdparty_download/download
-- Building knowhere- from source
-- Release
-- Populating knowhere
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/milvus/cmake_build/3rdparty_download/knowhere-subbuild
No such file or directory
CMake Error: Generator: execution of make failed. Make command was: /opt/rh/devtoolset-11/root/usr/bin/gmake -f Makefile &&
CMake Error at /usr/share/cmake/Modules/FetchContent.cmake:1604 (message):
  Build step for knowhere failed: 1
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FetchContent.cmake:1744:EVAL:2 (__FetchContent_directPopulate)
  /usr/share/cmake/Modules/FetchContent.cmake:1744 (cmake_language)
  thirdparty/knowhere/CMakeLists.txt:41 (FetchContent_Populate)


-- Configuring incomplete, errors occurred!
See also "/opt/milvus/cmake_build/CMakeFiles/CMakeOutput.log".
See also "/opt/milvus/cmake_build/CMakeFiles/CMakeError.log".
make[1]: *** [cmake_check_build_system] Error 1
make[1]: Leaving directory `/opt/milvus/cmake_build'
make: *** [build-cpp] Error 1
make: Leaving directory `/opt/milvus'
```

[CMakeError.log](https://github.com/milvus-io/milvus/files/12735405/CMakeError.log)

**Comment by jiaoew1991** [comment]
```
/opt/rh/devtoolset-11/root/usr/bin/cc    -DCHECK_FUNCTION_EXISTS=sgemm_  -Wl,-uHMAC_Update,-uHMAC_Final,-uHMAC_Init_ex,-uHMAC_CTX_new,-uHMAC_CTX_free,-uHMAC_CTX_reset   CMakeFiles/cmTC_b8039.dir/CheckFunctionExists.c.o -o cmTC_b8039 
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: CMakeFiles/cmTC_b8039.dir/CheckFunctionExists.c.o: in function `main':
CheckFunctionExists.c:(.text+0x10): undefined reference to `sgemm_'
collect2: error: ld returned 1 exit status
```

From this error message, it seems that the dependency openblas of Milvus was not found. Did Milvus fail to compile after adding the openblas dependency in conanfile.py?

**Comment by jiaoew1991** [comment]
```
No such file or directory
CMake Error: Generator: execution of make failed. Make command was: /opt/rh/devtoolset-11/root/usr/bin/gmake -f Makefile &&
CMake Error at /usr/share/cmake/Modules/FetchContent.cmake:1604 (message):
  Build step for knowhere failed: 1
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FetchContent.cmake:1744:EVAL:2 (__FetchContent_directPopulate)
  /usr/share/cmake/Modules/FetchContent.cmake:1744 (cmake_language)
  thirdparty/knowhere/CMakeLists.txt:41 (FetchContent_Populate)
```

However, from this log, it seems to be a network issue. The download from Knowhere was not successful.

**Comment by BUPTAnderson** [comment]
> ```
> No such file or directory
> CMake Error: Generator: execution of make failed. Make command was: /opt/rh/devtoolset-11/root/usr/bin/gmake -f Makefile &&
> CMake Error at /usr/share/cmake/Modules/FetchContent.cmake:1604 (message):
>   Build step for knowhere failed: 1
> Call Stack (most recent call first):
>   /usr/share/cmake/Modules/FetchContent.cmake:1744:EVAL:2 (__FetchContent_directPopulate)
>   /usr/share/cmake/Modules/FetchContent.cmake:1744 (cmake_language)
>   thirdparty/knowhere/CMakeLists.txt:41 (FetchContent_Populate)
> ```
> 
> However, from this log, it seems to be a network issue. The download from Knowhere was not successful.

The machine is network-accessible. The following is the log printed throughout the make process.

[compile_milvus.log](https://github.com/milvus-io/milvus/files/12735892/compile_milvus.log)

**Comment by jiaoew1991** [comment]
It seems that the code of knowhere is not cloned, you can check these two directories
```
-- Thirdparty downloaded file path: /opt/milvus/cmake_build/3rdparty_download/download
-- Building knowhere- from source
-- Release
-- Populating knowhere
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/milvus/cmake_build/3rdparty_download/knowhere-subbuild

```

**Comment by BUPTAnderson** [comment]
> /opt/milvus/cmake_build/3rdparty_download/knowhere-subbuild

/opt/milvus/cmake_build/3rdparty_download/download is empty.
```
$ ll /opt/milvus/cmake_build/3rdparty_download/download
total 0
$ ll /opt/milvus/cmake_build/3rdparty_download/knowhere-subbuild
total 24
-rw-rw-r-- 1 hadoop hadoop 4529 Sep 26 18:25 CMakeCache.txt
drwxrwxr-x 5 hadoop hadoop  307 Sep 27 15:35 CMakeFiles
-rw-rw-r-- 1 hadoop hadoop 1564 Sep 26 18:25 cmake_install.cmake
-rw-r--r-- 1 hadoop hadoop 1521 Sep 26 18:25 CMakeLists.txt
drwxrwxr-x 4 hadoop hadoop   28 Sep 26 18:25 knowhere-populate-prefix
-rw-rw-r-- 1 hadoop hadoop 4682 Sep 27 15:35 Makefile
```

**Comment by BUPTAnderson** [comment]
![截屏2023-09-27 19 15 24](https://github.com/milvus-io/milvus/assets/13449703/c6a4bbf6-066a-4953-bbce-54a95bd8e274)
![截屏2023-09-27 19 18 58](https://github.com/milvus-io/milvus/assets/13449703/3cee88f2-7095-431d-bf09-8186d6d4de16)
Any suggestions ?

**Comment by jiaoew1991** [comment]
Your environment is very strange. There seem to be at least three issues: first, the system does not support pthread; second, the environment is mistakenly recognized as arm64 architecture; third, openblas cannot be found. I don't recommend you to compile in this environment. 🤔

**Comment by BUPTAnderson** [comment]
> Your environment is very strange. There seem to be at least three issues: first, the system does not support pthread; second, the environment is mistakenly recognized as arm64 architecture; third, openblas cannot be found. I don't recommend you to compile in this environment. 🤔

@jiaoew1991 thx, This machine was previously used to compile version 2.2.X. I re-selected a blank machine to compile 2.3.1 and it now compiles successfully.
