### ISSUE TITLE
[Bug]: hello_milvus.py link not working 

### ISSUE THREAD

**Issue by pauldintel** [milvus-io/milvus#27387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

wget https://raw.githubusercontent.com/milvus-io/pymilvus/v2.0.x/examples/hello_milvus.py

that URL is broken in the Milvus documentation hence I got the code from here :  
$wget https://github.com/milvus-io/pymilvus/blob/master/examples/hello_milvus.py

however problem with this code is there is error on Python : false vs False , true vs True and null vs None
After replacing this : python3 hello_milvus.py doesn't show any output 

### Expected Behavior

python3 hello_milvus.py show output as per what state in documentation

### Steps To Reproduce

```markdown
$wget https://github.com/milvus-io/pymilvus/blob/master/examples/hello_milvus.py
$python3 hello_milvus.py

nothing happens
```

### Milvus Log

nA

### Anything else?

no

**Comment by yanliang567** [comment]
I downloaded the hello_milvus.py in https://milvus.io/docs/example_code.md,  and run the script successfully on milvus v2.3.1. 
@pauldintel  could you please double check the python version >=3.8, pymilvus version is consistent to your milvus server, and the milvus host is correctly updated in the script.

/assign @pauldintel 
/unassign

**Comment by pauldintel** [comment]
I am seeing the problem I stated with Milvus 2.0.2 version . with 2.3.x no problem with wget 
ubuntu@ip-172-31-1-111:~$ sudo docker compose up -d
network milvus was found but has incorrect label com.docker.compose.network set to "milvus"
what is the fix here  ?
 I have Docker V2 : 
ubuntu@ip-172-31-1-111:~$ docker-compose version
Docker Compose version v2.20.3

**Comment by pauldintel** [comment]
I am seeing the problem I stated with Milvus 2.0.2 version . with 2.3.x no problem with wget 
ubuntu@ip-172-31-1-111:~$ sudo docker compose up -d
network milvus was found but has incorrect label com.docker.compose.network set to "milvus"
what is the fix here  ?
 I have Docker V2 : 
ubuntu@ip-172-31-1-111:~$ docker-compose version
Docker Compose version v2.20.3

**Comment by pauldintel** [comment]
I am seeing the problem I stated with Milvus 2.0.2 version . with 2.3.x no problem with wget 
sudo docker compose up -d
network milvus was found but has incorrect label com.docker.compose.network set to "milvus"

what is the fix here  ?
 I have Docker V2 : 
ubuntu@ip-172-31-1-111:~$ docker-compose version
Docker Compose version v2.20.3
