### ISSUE TITLE
[Bug]: [benchmark] SCANN index recall too low when with_raw_data is false

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#27397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230926-e02670ea
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

index: SCANN 
argo task : fouramf-kjggg 

with_raw_data is false and the test parameter for the SCANN index is :
```
"dataset_name": "sift-128-euclidean
top_k：10, nq = 1000 
 "reorder_k":100 
 "nlist": 1024, "with_raw_data": false

nprobe values from 1 to 512.
nprobe: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512] 
```
recall: [0.329,0.425,0.513,0.568,0.599,0.61, 0.613,0.613,0.613,0.613]

recall only up to 0.613

### Anything else?

test env: 4am, qa-milvus namespace

**Comment by liliu-z** [comment]
Do we have similar test on a larger dim?

**Comment by elstic** [comment]
> Do we have similar test on a larger dim?

Our current tests for recall are only on the sift (128d) and glove (200d) datasets.

**Comment by liliu-z** [comment]
This sounds as expected to me. Recall of without refine SCANN on a small-dim is low.

**Comment by yanliang567** [comment]
> This sounds as expected to me. Recall of without refine SCANN on a small-dim is low.

@liliu-z what is refine SCANN, does it mean the SCANN is not good for production if dim is low?

/assign @liliu-z 
/unassign

**Comment by chasingegg** [comment]
This is as expected, you could try IVF_PQ with build param `m=dim/2, nbits=4` its behavior is similar to SCANN and recall is just slightly higher than SCANN(because SCANN has more quantization operations), also reach its upper bound recall at around 0.65~0.7.

**Comment by xiaofan-luan** [comment]
do we have test result with BF16 or Float32 refine?

**Comment by liliu-z** [comment]
Yes, with refine the recall will be much better.

I think we can close this issue

**Comment by elstic** [comment]
> Yes, with refine the recall will be much better.
> 
> I think we can close this issue

Can you tell me if it will be improved later or is it already improved now?

**Comment by elstic** [comment]
> If with_raw_data is true, recall is normal. 
> nprobe: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512] 
> recall : 0.385,0.541,0.704,0.839,0.93,0.977,0.994,0.997,0.997,0.997 

with_raw_data is false, recall is low and there doesn't seem to be a need for this parameter
