### ISSUE TITLE
CreateCollectionParam.newBuilder().withDatabaseName(DatabaseName)[Bug]: Redundancy and Confusion in Database Name Specification When Creating Collections in Milvus Java SDK

### ISSUE THREAD

**Issue by TaoWolf** [milvus-io/milvus#27395]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.0
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    none
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.1
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 16/32
- GPU: none
- Others: none
```

### Current Behavior

I would like to report a bug or design flaw in Milvus, specifically in the following method:

java
Copy code
CreateCollectionParam.newBuilder().withDatabaseName(DatabaseName)
Including the DatabaseName parameter while creating a collection is redundant and potentially confusing for new users, as it overlaps with the DatabaseName parameter used when creating the MilvusServiceClient.

Many Java users of Milvus, while following the official example code for client creation, encounter issues. The official example code is as follows:

java
Copy code
final MilvusServiceClient milvusClient = new MilvusServiceClient(
  ConnectParam.newBuilder()
    .withHost("localhost")
    .withPort(19530)
    .build()
);
This example does not set the withDatabaseName parameter.

If users create their own database and connect using this example, then proceed to create a collection using the withDatabaseName parameter, the subsequent index creation will be ineffective. This is because the index will be created in the default database.

As a result, various operations fail, leading to a difficult user experience filled with unsolvable issues. Some users even believe that Milvus' ability to create custom databases is a sham, and that one can only successfully proceed with operations when using the default database, which is extremely unfriendly.

Suggestions:

Include the withDatabaseName parameter in the official Java example for client creation.
Remove the withDatabaseName parameter from the method used to create a new collection to avoid user confusion.
Clearly state in the documentation that the database should be specified during client initialization using the withDatabaseName parameter.

### Expected Behavior

Currently, when using the Milvus Java SDK to create a new collection, the CreateCollectionParam.newBuilder().withDatabaseName(DatabaseName) method allows for the specification of a database name. However, this is redundant and potentially confusing as the MilvusServiceClient also has a withDatabaseName parameter during initialization. Many users, following the official example code, do not set the withDatabaseName parameter when initializing the client. This leads to issues when creating indexes, as they are created in the default database, rendering them ineffective for collections in custom databases.

The expected behavior would be for the database name to be specified only once, either during the client initialization or when creating a new collection, but not both. This would eliminate redundancy and reduce confusion for new users. Ideally, the official example should also include the withDatabaseName parameter to guide users effectively.

### Steps To Reproduce

```markdown
Initialize MilvusServiceClient without setting the withDatabaseName parameter, as per the official example：
final MilvusServiceClient milvusClient = new MilvusServiceClient(
  ConnectParam.newBuilder()
    .withHost("localhost")
    .withPort(19530)
    .build()
);
Create a new database in Milvus.
Create a new collection using CreateCollectionParam.newBuilder().withDatabaseName(CustomDatabaseName).
Attempt to create an index for this new collection.
Observe that the index is ineffective because it is created in the default database, not the custom database specified during collection creation.
```

### Milvus Log

No logs are required for this issue as it is more of a design flaw rather than a runtime error. The issue can be easily replicated by following the 'Steps To Reproduce' section.

### Anything else?

no

**Comment by yanliang567** [comment]
@yhmo sounds like java sdk does not fully support database or not user friendly? could you please take a look?
/assign @yhmo 
/unassign

**Comment by TaoWolf** [comment]
> @yhmo sounds like java sdk does not fully support database or not user friendly? could you please take a look? /assign @yhmo /unassign

yes,java sdk does not fully support database and not user friendly
