### ISSUE TITLE
[Feature]: [L0 Delta] Meta and RPC design - Alternative

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#27402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Treat L0 Delta as a new type of segment
# Meta
```protobuf
message SegmentInfo {
  int64 ID = 1;
  int64 collectionID = 2;
  int64 partitionID = 3;
  string insert_channel = 4;
  /// ... reserve all existing fields
  SegmentLevel seg_level = 20; // newly added field, marking L0, L1, default value shall be equivalent to L1
}
```

# RPC
no new RPC needed, modify exist `GetQueryVChannelInfo`
## GetQueryVChanPosition
```protobuf
message VchannelInfo {                                                                                                  
  int64 collectionID = 1;                                                                                               
  string channelName = 2;                                                                                               
  // ...
  repeated int64 indexed_segmentIds = 10;
  repeated SegmentInfo indexed_segments = 11;
  repeated SegmentInfo l0_segments = 12; // <--- new fields, optional, maybe querycoord could check segment level first
} 
```

### Describe the solution you'd like.

Treating L0 delta as segments may utilize all existing policy applied to segments as well. No extra grpc needed and GC policy can also be the same.

### Describe an alternate solution.

#27350

**Comment by congqixia** [comment]
@yah01 any comments on extra field or not?

**Comment by congqixia** [comment]
With this design, it's also possible to put insert data from all partitions into one L0 segment

**Comment by yah01** [comment]
`seg_level` -> `level`
others LGTM, prefer this.
