### ISSUE TITLE
[Bug]: `test_delete_expr_json_contains_base` case is not stable

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#27407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: a8ce1b6
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Case may fail randomly

### Anything else?

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-27394/4/pipeline

**Comment by yanliang567** [comment]
@congqixia any suggestion for testcase updating?

**Comment by congqixia** [comment]
> @congqixia any suggestion for testcase updating?

@aoiasd may have some idea here

**Comment by aoiasd** [comment]
> @congqixia any suggestion for testcase updating?

Should query with strong consistency before delete or flush data before load to make sure data is queryable.  Wait 5s could work too.

**Comment by yanliang567** [comment]
> > @congqixia any suggestion for testcase updating?
> 
> Should query with strong consistency before delete or flush data before load to make sure data is queryable. Wait 5s could work too.

@aoiasd how can a user query with strong consistency, I don't think we have the param in query()

**Comment by yanliang567** [comment]
In e2e/ci tests, the test collection was created with strong consistency level by default already. I reran the tests(master-20231007) for 10 times and all passed.
