### ISSUE TITLE
[Bug]: docs bug - Java API

### ISSUE THREAD

**Issue by fgreco55** [milvus-io/milvus#27416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Bottom of page: https://milvus.io/api-reference/java/v2.3.x/Query%20and%20Search/search().md

System.out.println("Search results:");
for (int i = 0; i < targetVectors.size(); ++i) {
    List<SearchResultsWrapper.IDScore> scores = **results**.getIDScore(i);       // "results" should be "wrapper"
    for (SearchResultsWrapper.IDScore score:scores) {
        System.out.println(score);
    }
}

### Expected Behavior

    List<SearchResultsWrapper.IDScore> scores = **results**.getIDScore(i);       // "results" should be "wrapper"

**Comment by yhmo** [comment]
The doc has been updated.
