### ISSUE TITLE
Error occurred when searching an empty collection

### ISSUE THREAD

**Issue by WangJianRepo** [milvus-io/milvus#2741]
**Is your feature request related to a problem? Please describe.**
Error occurred when searching an empty collection. 
C++ SDK returns an error said num of results is not equal num of queries（I did not remember how it said exactly.）, when I search in an empty collection created just now. 

**Describe the solution you'd like**
It will be better if sdk return an empty result with the same size of queries instead of an error, I think.

**Describe alternatives you've considered**
Handling the error and skip.

**Additional context**
Ubuntu 16.04
milvus:0.10.0-cpu-d061620-5f3c00, run in Docker 19.03.5
Index: IVFFLAT
Binary Vector
Metric: Hamming

**Comment by tinkerlin** [comment]
tks for you advice, we will discuss this issue.

**Comment by yhmo** [comment]
May relate to #2578 which was already fixed by #2591 in 0.10.1 and master branch
