### ISSUE TITLE
[Bug]: Not able to install GO sdk for v2.3.1

### ISSUE THREAD

**Issue by adityap23** [milvus-io/milvus#27432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.1
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): NA    
- SDK version(e.g. pymilvus v2.0.0rc2): go sdk v2.3.1
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 8/32
- GPU: NA
- Others: NA
```

### Current Behavior

When I'm trying to install milvus Go sdk using the command : go get -u github.com/milvus-io/milvus-sdk-go/v2
I'm getting an error : 
cannot find package "github.com/milvus-io/milvus-sdk-go/v2" in any of:
        /usr/local/go/src/github.com/milvus-io/milvus-sdk-go/v2 (from $GOROOT)
        /home/aditya_pandey/go/src/github.com/milvus-io/milvus-sdk-go/v2 (from $GOPATH)
And also when I'm visiting the github site it shoes 404 not found error

### Expected Behavior

The go get command should install the Go sdk without any issues

### Steps To Reproduce

```markdown
1. Just run the go get command for the GO sdk installation
```

**Comment by SimFG** [comment]
it should be `go get -u github.com/milvus-io/milvus-sdk-go/v2`
![image](https://github.com/milvus-io/milvus/assets/21985684/d20779ca-d418-4fc1-9e5a-77a42bae62dc)

**Comment by adityap23** [comment]
> it should be `go get -u github.com/milvus-io/milvus-sdk-go/v2` ![image](https://user-images.githubusercontent.com/21985684/271204285-d20779ca-d418-4fc1-9e5a-77a42bae62dc.png)

Yeah sorry that was my mistake while typing this issue 
Its giving same error for this command too go get -u github.com/milvus-io/milvus-sdk-go/v2

**Comment by SimFG** [comment]
![image](https://github.com/milvus-io/milvus/assets/21985684/721e975c-513b-4807-98c2-951b10ffbf93)
It seems like no error occurred here
@adityap23

**Comment by congqixia** [comment]
@adityap23 thanks for the feedback, quick question, which go version did you use when trying to download go sdk? and in which directory when executing the command? and does the folder contains `go.mod` file?

**Comment by adityap23** [comment]
> @adityap23 thanks for the feedback, quick question, which go version did you use when trying to download go sdk? and in which directory when executing the command? and does the folder contains `go.mod` file?

So i was trying to run the command directly, do i need to create a go.mod file
I was trying to install the v2.3.1 Go sdk 
Can you let me know the steps to follow to install this library . TIA

**Comment by adityap23** [comment]
@congqixia any update on this?

**Comment by adityap23** [comment]
@congqixia any update on this?

**Comment by congqixia** [comment]
@adityap23 sorry for the late reply
go sdk is simply a dependency for your Go project, so it shall be install under a folder with `go.mod` file.
