### ISSUE TITLE
[Bug]: Out of Memory Error when data node consume kafka data

### ISSUE THREAD

**Issue by dingyingjie-patsnap** [milvus-io/milvus#27430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.8
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.8
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I insert about 120 million 256 dimension data to the cluster, the data node have some restart, by reading the log, there's some out of memory error, even after we add the resource limit to 50g, and after all insertion finished, there's some data loss

### Expected Behavior

no OOM for data node, and no data loss even if there's data node restart

### Steps To Reproduce

```markdown
1. start a cluster with the following config
dataNode:
  replicas: 2
  resources:
    limits:
      cpu: 6
      memory: 10Gi
    requests:
      cpu: 10m
      memory: 1Gi
  nodeSelector:
    env: xxx
2.  create a collection with id(long) and vector(256 float)
3. insert 120 million data
4. there's some restart in data node and data insert speed is very slow
```

**Comment by yanliang567** [comment]
@dingyingjie-patsnap could you please retry on latest milvus v2.3.1, as we fixed many issues from 2.2.8 to 2.3.1.
/assign @dingyingjie-patsnap 
/unassign
