### ISSUE TITLE
[Bug]: Growing segment HasIndex interface bug

### ISSUE THREAD

**Issue by zhagnlu** [milvus-io/milvus#27438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Growing segment's HasIndex interface return all true for all field. but actually has different situation. need refactor it.
![image](https://github.com/milvus-io/milvus/assets/11935707/65ba58bb-3baf-4a5c-ba12-ec1f2a5c0aa6)

### Expected Behavior

1. for non-vector field, return false
2. for vector field, check whether using dynamic index for growing segment.

**Comment by xiaofan-luan** [comment]
good catch
