### ISSUE TITLE
[Bug]: i cant‘t find why the search latency  and mutation latency become larger 

### ISSUE THREAD

**Issue by ronghuaihai** [milvus-io/milvus#27440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.11
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):   2.2.13
- OS(Ubuntu or CentOS): Centos
- CPU/Memory: 96逻辑核  Intel(R) Xeon(R) Gold 5318Y CPU @ 2.10GHz   memory 503G  per Machine
- GPU: no
- Others:
```

### Current Behavior

search lantency and  mutation latency  become high，i can’t find who caused this problem and locate the cause of the problem.

<img width="595" alt="image" src="https://github.com/milvus-io/milvus/assets/14067712/254f89f3-5d4f-43be-87c5-e97984b422d5">
<img width="608" alt="image" src="https://github.com/milvus-io/milvus/assets/14067712/34e28d44-e8b3-4780-8e5a-ca53d9172a46">

### Expected Behavior

i want to know which query cause of the problem - search lantency and  mutation latency  become high

### Steps To Reproduce

```markdown
1.the content of the values.yaml which to use intall milvus cluster in the attachment files names “values.yaml.20230928.zip”
```

### Milvus Log

[20230928_48h.tar.gz](https://github.com/milvus-io/milvus/files/12748173/20230928_48h.tar.gz)
[values.yaml.20230928.zip](https://github.com/milvus-io/milvus/files/12748194/values.yaml.20230928.zip)

**Comment by xiaofan-luan** [comment]
1. is there a way we can get full metrics?
2. what is the index type, expected latency, qps and batch per query?
3. what is the vector dimension and data size?

The first thing you want to check is cpu usage, then check about k8s throttling.
If the hardware is all fine, then next part is to test nq combination logic. 
change queryNode.grouping.maxNQ to 100 might help

**Comment by yanliang567** [comment]
@ronghuaihai besides, a few more quick questions:
1. did you do inserting while do searching?
2. According to the search latency, I doubt that Milvus was doing brute force similarity search. Could you please attach the etcd backup for investigation？ Check this: https://github.com/milvus-io/birdwatcher for details about how to backup etcd with birdwatcher

/assign @ronghuaihai 
/unassign

**Comment by buptubuntu** [comment]
![image](https://github.com/milvus-io/milvus/assets/6237116/4966b82f-fc0e-4c83-a20b-f4e512fdf1d6)
![image](https://github.com/milvus-io/milvus/assets/6237116/54edb2ac-f66b-466d-b85a-f941d4acd0df)

Search Segment Latency seem ok, but cache update latency from proxy seems not

**Comment by ronghuaihai** [comment]
i have backup the etcd using birdwatcher ，as follows：
[bw_etcd_ALL.231007-105645.bak.gz](https://github.com/milvus-io/milvus/files/12836374/bw_etcd_ALL.231007-105645.bak.gz)
@yanliang567

**Comment by ronghuaihai** [comment]
1.is there a way we can get full metrics?
i have collected information about k8s milvus pod logs and etcd backup files  in the folllow zip files：
[mivlus集群检索为2秒左右-检索延迟问题定位.zip](https://github.com/milvus-io/milvus/files/12925478/mivlus.2.-.zip)

2. what is the index type, expected latency, qps and batch per query?
index type is HNSW, expected latency is 300ms ,qps is 300   
![collection schema and index type](https://github.com/milvus-io/milvus/assets/14067712/ee7cb9c2-a64e-43ef-86c6-72a83d9b98de)


3.what is the vector dimension and data size?
vector is  1024 dimension ,expected  data size 10 million ,now actually the num of collection and  entities show in the flollow picture:

![collection entities nums and collection nums](https://github.com/milvus-io/milvus/assets/14067712/ddb85d62-1c1e-4a6a-94c0-be0331ef038c)
