### ISSUE TITLE
[Bug]: The package name in the documentation is wrong

### ISSUE THREAD

**Issue by Tangent-90C** [milvus-io/milvus#27443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.0
```

### Current Behavior

Just open [https://milvus.io/api-reference/pymilvus/v2.3.x/MilvusClient/Client/MilvusClient().md](https://milvus.io/api-reference/pymilvus/v2.3.x/MilvusClient/Client/MilvusClient().md)

### Expected Behavior

![image](https://github.com/milvus-io/milvus/assets/28804414/9ae9c73c-9b8e-4085-a6c3-cec4ac6aea30)

**Comment by xiaofan-luan** [comment]
commit the PR, thanks for the feedback

**Comment by yanliang567** [comment]
verified fix
