### ISSUE TITLE
[Bug]: ami-0d8d212151031f51c is not valid. Please list full filter criteria for AMI

### ISSUE THREAD

**Issue by nallagangus** [milvus-io/milvus#27448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

$ terraform apply results in ami-0d8d212151031f51c does not exist.

**Comment by xiaofan-luan** [comment]
@nallagangus 
I don't have any context, where did you see ami-0d8d212151031f51c and which document?

**Comment by xiaofan-luan** [comment]
/assign @zwd1208 
it would be great if we can provide terraform deploment for both zilliz cloud and opensource milvus

**Comment by nallagangus** [comment]
https://milvus.io/docs/aws.md#Prepare-variablestf 

Above refers to an AMI that is not available. When you terraform apply you get AMI not found error.

**Comment by yanliang567** [comment]
/assign @zwd1208 
looks like a deployment issue on AWS. please help.

/unassign
