### ISSUE TITLE
[Bug]: When I use the Varchar data type and insert Chinese data, I find that the Chinese characters in the query results have been converted to a different encoding and do not display as normal Chinese characters. Is this a bug?

### ISSUE THREAD

**Issue by TaoWolf** [milvus-io/milvus#27446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.1
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):none
- SDK version(e.g. pymilvus v2.0.0rc2):Java-2.3.1
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 16/32
- GPU: none
- Others: none
```

### Current Behavior

When I use the Varchar data type and insert Chinese data, I find that the Chinese characters in the query results have been converted to a different encoding and do not display as normal Chinese characters. Is this a bug?

### Expected Behavior

![image](https://github.com/milvus-io/milvus/assets/16403888/82c458bc-d40c-4416-b8e7-5060d294ad2c)

### Steps To Reproduce

```markdown
1. Use JavaSDK-2.3.1 create collection Use DataType.Varchar   
2. Insert Chinese characters     
3. Qurey this Data  And debug in Idea IDE    
4. see…… Images IN "Expected Behavior"    
Chinese characters have been converted to:    
"\344\270\200\344\270\252\346\237\245\350\257\242\345\225\206\345\223\201\346\225\260\351\207\217\347\232\204\346\226\271\346\263\225\357\274\214\344\275\277\347\224\250\346\210\221\345\217\257\344\273\245\346\237\245\345\207\272\346\235\245\345\225\206\345\223\201\346\225\260\351\207\217\343\200\202"
```

### Milvus Log

topks: 2
output_fields: "funcId"
output_fields: "funcName"
output_fields: "funcInfo"
, milvus.proto.milvus.SearchResults.collection_name=funcCollectionIndexCosine}
R{status=0, data=status {
}
results {
  num_queries: 1
  top_k: 2
  fields_data {
    type: Int64
    field_name: "funcId"
    scalars {
      long_data {
        data: 444574215431260493
        data: 444574215431260492
      }
    }
    field_id: 100
  }
  fields_data {
    type: VarChar
    field_name: "funcName"
    scalars {
      string_data {
        data: "getProductPrice"
        data: "getProductAmount"
      }
    }
    field_id: 101
  }
  fields_data {
    type: VarChar
    field_name: "funcInfo"
    scalars {
      string_data {
        data: "\344\270\200\344\270\252\346\237\245\350\257\242\345\225\206\345\223\201\344\273\267\346\240\274\347\232\204\346\226\271\346\263\225\357\274\214\344\275\277\347\224\250\346\210\221\345\217\257\344\273\245\346\237\245\345\207\272\346\235\245\345\225\206\345\223\201\344\273\267\346\240\274\343\200\202"
        data: "\344\270\200\344\270\252\346\237\245\350\257\242\345\225\206\345\223\201\346\225\260\351\207\217\347\232\204\346\226\271\346\263\225\357\274\214\344\275\277\347\224\250\346\210\221\345\217\257\344\273\245\346\237\245\345\207\272\346\235\245\345\225\206\345\223\201\346\225\260\351\207\217\343\200\202"
      }
    }
    field_id: 102
  }
  scores: 0.8118237
  scores: 0.6665597
  ids {
    int_id {
      data: 444574215431260493
      data: 444574215431260492
    }
  }
  topks: 2
  output_fields: "funcId"
  output_fields: "funcName"
  output_fields: "funcInfo"
}
collection_name: "funcCollectionIndexCosine"
}
OK

### Anything else?

none

**Comment by TaoWolf** [comment]
I've noticed something interesting about your code. It's actually in octal UTF-8 encoding, but JavaSDK-2.3.1 didn't handle it properly and showed it to the user as is. Do you think this could be a bug in the SDK? By the way, is the SDK open source? Maybe I can lend a hand in fixing it!

**Comment by xiaofan-luan** [comment]
milvus usually don't handle the encoding and let the user handle it by themselves.
But agreed it will be more friendly if we can show the data in utf8 format.

**Comment by jiaoew1991** [comment]
we need a encoding properties for `column` like other db

**Comment by jiaoew1991** [comment]
tracking it in https://github.com/milvus-io/milvus/issues/27652

**Comment by yanliang567** [comment]
if you don't mind, I'd close this one then

**Comment by Enkar-Bolat** [comment]
is there any solutions? why is this closed

**Comment by yanliang567** [comment]
i was tracking in  https://github.com/milvus-io/milvus/issues/27652
