### ISSUE TITLE
[Feature]: Enable object store inventory to do GC

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#27450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Many cloud storage support inventory command, for example 

S3 https://docs.aws.amazon.com/AmazonS3/latest/userguide/storage-inventory-location.html
gcs https://cloud.google.com/storage/docs/insights/inventory-reports?hl=zh-cn
oss https://help.aliyun.com/zh/oss/developer-reference/inventory

inventory is faster and better for garbage collection usage.
However, there are many object storage doesn't support inventory, for ex, Minio.

To handle this, 
1. for cloud system, the inventory thread is disabled, S3 and gcs did the inventory automatically.
2. for minio and other unsupported systemes, the inventory thread is enabled, do the inventory every 1 hour by listing the bucket.
3. garbage collection handler only read the eventory and do the gc based on gc period. GC period should usually be longer than inventory period.

**Comment by xiaofan-luan** [comment]
Anyone interested please take a look on it

**Comment by xiaofan-luan** [comment]
And we need to make sure all the cloud provider have same inventory format.

**Comment by haorenfsa** [comment]
Azure also supports inventory, FYI

https://learn.microsoft.com/en-us/azure/storage/blobs/blob-inventory
