### ISSUE TITLE
[Bug]: Folly corrupted binary and memalign issues on Apple M2

### ISSUE THREAD

**Issue by filip-halt** [milvus-io/milvus#27464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: Master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): MacOS 13.5
```

### Current Behavior

I have been trying to build Milvus on M2 and running into issues building folly.

The main issue is that memalign() is not compatible on Mac, Mac supports posix_memalign:
<img width="955" alt="image" src="https://github.com/milvus-io/milvus/assets/81822489/a08d6860-c1e8-4f1d-9295-4a97d750b068">

The most likely thing that is going on is that a flag isn't being set correctly for make, which is true as seen here:
<img width="942" alt="image" src="https://github.com/milvus-io/milvus/assets/81822489/2436e8c1-e8de-48e0-95fc-26461f059f4e">

When looking further I noticed that folly is using a corrupted binary:
<img width="818" alt="image" src="https://github.com/milvus-io/milvus/assets/81822489/613a1afd-e337-4ff5-a5ec-9c7e54d8f0c8">

What are the next steps?

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version: Master
> - Deployment mode(standalone or cluster):
> - MQ type(rocksmq, pulsar or kafka):    
> - SDK version(e.g. pymilvus v2.0.0rc2):
> - OS(Ubuntu or CentOS): MacOS 13.5
> ```
> 
> ### Current Behavior
> I have been trying to build Milvus on M2 and running into issues building folly.
> 
> The main issue is that memalign() is not compatible on Mac, Mac supports posix_memalign: <img alt="image" width="955" src="https://user-images.githubusercontent.com/81822489/272086787-a08d6860-c1e8-4f1d-9295-4a97d750b068.png">
> 
> The most likely thing that is going on is that a flag isn't being set correctly for make, which is true as seen here: <img alt="image" width="942" src="https://user-images.githubusercontent.com/81822489/272086952-2436e8c1-e8de-48e0-95fc-26461f059f4e.png">
> 
> When looking further I noticed that folly is using a corrupted binary: <img alt="image" width="818" src="https://user-images.githubusercontent.com/81822489/272087159-613a1afd-e337-4ff5-a5ec-9c7e54d8f0c8.png">
> 
> What are the next steps?
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

Hi FIlip,
you have to use arm image to start standalone I guess.
From 2.3 Milvus split into arm and x86 binds.

**Comment by fanwenyuan** [comment]
I followed the instructions for build on M1 and I'm meeting the same error

**Comment by xiaofan-luan** [comment]
@filip-halt 
did you try to run setup scripts/setenv.sh?

@jiaoew1991 
could you take a look on it?

**Comment by filip-halt** [comment]
@xiaofan-luan Yes, setup scripts, manually linking compilers, etc. The only way around it was using LLVM@17 but using it required changes to Conan and setenv that ended up breaking linking later on.

**Comment by alexanderguzhva** [comment]
This is how I was able to build milvus on M2:
0. install prerequisites
1. run `brew install llvm@16`
2. use the following conan profile (`./~conan/profiles/default` file should contain this):
```
[settings]
os=Macos
os_build=Macos
arch=armv8
arch_build=armv8
compiler=clang
compiler.version=16
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
CC=/opt/homebrew/Cellar/llvm@16/16.0.6/bin/clang
CXX=/opt/homebrew/Cellar/llvm@16/16.0.6/bin/clang++
```
3. run `make`

**Comment by alexanderguzhva** [comment]
btw, apple clang-14 won't work, brew's clang-14 wont work either

**Comment by xiaofan-luan** [comment]
> This is how I was able to build milvus on M2:
> 
> 1. install prerequisites
> 2. run `brew install llvm@16`
> 3. use the following conan profile (`./~conan/profiles/default` file should contain this):
> 
> ```
> [settings]
> os=Macos
> os_build=Macos
> arch=armv8
> arch_build=armv8
> compiler=clang
> compiler.version=16
> compiler.libcxx=libc++
> build_type=Release
> [options]
> [build_requires]
> [env]
> CC=/opt/homebrew/Cellar/llvm@16/16.0.6/bin/clang
> CXX=/opt/homebrew/Cellar/llvm@16/16.0.6/bin/clang++
> ```
> 
> 4. run `make`
> 
> btw, apple clang-14 won't work, brew's clang-14 wont work either
> 
> Also, there was one of conan packages (rocksdb) that wanted to use the most recent clang. So, if you have both llvm@16 and llvm@17 installed, then this rocksdb will auto-use llvm@17 and cause a conflict. In my experiments, the only llvm version that I had installed was llvm@16

What kind of error did you get?
I thought LLVM might be different with filip's issue.
His error seems to be compile with x86 arch

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan Yes, setup scripts, manually linking compilers, etc. The only way around it was using LLVM@17 but using it required changes to Conan and setenv that ended up breaking linking later on.

I think for some reason you are building with X86 arch, could you check your conan config? @filip-halt

**Comment by filip-halt** [comment]
We looked through Alex's build logs and his folly also compiles using the x86 default. Im downgrading my Mac to 13.5.2, both 13.6 and 14 were having similar problems so maybe a recent change was causing failures. LLVM 17 seems to get past it.

**Comment by filip-halt** [comment]
> > @xiaofan-luan Yes, setup scripts, manually linking compilers, etc. The only way around it was using LLVM@17 but using it required changes to Conan and setenv that ended up breaking linking later on.
> 
> I think for some reason you are building with X86 arch, could you check your conan config? @filip-halt

Conan is getting set correctly. 

[settings]
os=Macos
os_build=Macos
arch=armv8
arch_build=armv8
compiler=clang
compiler.version=15
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
CC=/opt/homebrew/Cellar/llvm@15/15.0.7/bin/clang
CXX=/opt/homebrew/Cellar/llvm@15/15.0.7/bin/clang++

**Comment by filip-halt** [comment]
It seems like the macro in folly isn't aligning with what the OS uses. Not sure if this is a bug or a deprecation: 

Within folly/memory.h and a few other places:
```cpp
#if (defined(_POSIX_C_SOURCE) && _POSIX_C_SOURCE >= 200112L) || \
    (defined(_XOPEN_SOURCE) && _XOPEN_SOURCE >= 600) ||         \
    (defined(__ANDROID__) && (__ANDROID_API__ > 16)) ||         \
    (defined(__APPLE__) &&                                      \
     (__MAC_OS_X_VERSION_MIN_REQUIRED >= __MAC_10_6 ||          \
      __IPHONE_OS_VERSION_MIN_REQUIRED >= __IPHONE_3_0)) ||     \
    defined(__FreeBSD__) || defined(__wasm32__)

inline void* aligned_malloc(size_t size, size_t align) {
  // use posix_memalign, but mimic the behaviour of memalign
  void* ptr = nullptr;
  int rc = posix_memalign(&ptr, align, size);
  return rc == 0 ? (errno = 0, ptr) : (errno = rc, nullptr);
}

inline void aligned_free(void* aligned_ptr) {
  free(aligned_ptr);
}
```

`__MAC_OS_X_VERSION_MIN_REQUIRED` for some reason evaluates to the incorrect value ( string= `__ENVIRONMENT_OS_VERSION_MIN_REQUIRED__ `) . In LLVM, my clang uses `#define __ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__ 130000`. In order to fix it I replaced all the instances of  `__MAC_OS_X_VERSION_MIN_REQUIRED` with `__ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__` and managed to get the build working.


In addition to this, it looks like more recent CommandLineTools and  Appleclang15 changed up some things that need to be fixed in the future.

<img width="982" alt="image" src="https://github.com/milvus-io/milvus/assets/81822489/803452b9-d61d-449a-9124-8cbbc99447c1">

**Comment by filip-halt** [comment]
Final Update:

The cause of all these failures in building is that Apple Command Line Tools 15 is incompatible with building folly. Even if you use a brew install LLVM, the Command Line Tool is deciding the preprocess definition, and Apple Clang 15 is missing the required one. For some reason llvm@17 works but it brings other issues to the build. For now the best route if your `clang --version` shows Apple Clang Version > 15 is to uninstall Command line tools and reinstall  [v14](https://developer.apple.com/download/all/?q=xcode) <- don't need a developer account, just use your AppleID regular account. This should fix the errors.

**Comment by xiaofan-luan** [comment]
> Final Update:
> 
> The cause of all these failures in building is that Apple Command Line Tools 15 is incompatible with building folly. Even if you use a brew install LLVM, the Command Line Tool is deciding the preprocess definition, and Apple Clang 15 is missing the required one. For some reason llvm@17 works but it brings other issues to the build. For now the best route if your `clang --version` shows Apple Clang Version >= 15 is to uninstall Command line tools and reinstall [v14](https://developer.apple.com/download/all/?q=xcode) <- don't need a developer account, just use your AppleID regular account. This should fix the errors.

can we solve this by upgrading folly version?

**Comment by filip-halt** [comment]
> > Final Update:
> > The cause of all these failures in building is that Apple Command Line Tools 15 is incompatible with building folly. Even if you use a brew install LLVM, the Command Line Tool is deciding the preprocess definition, and Apple Clang 15 is missing the required one. For some reason llvm@17 works but it brings other issues to the build. For now the best route if your `clang --version` shows Apple Clang Version >= 15 is to uninstall Command line tools and reinstall [v14](https://developer.apple.com/download/all/?q=xcode) <- don't need a developer account, just use your AppleID regular account. This should fix the errors.
> 
> can we solve this by upgrading folly version?

Im not too sure, the master branch of folly is using the same [macros](https://github.com/facebook/folly/blob/bd351502b62c7983eff0b593df010b840bccc11c/folly/Memory.h#L45) which makes me think that's not possible. What might be worth doing is making sure everything is compatible with llvm17.

**Comment by jiaoew1991** [comment]
> > > Final Update:
> > > The cause of all these failures in building is that Apple Command Line Tools 15 is incompatible with building folly. Even if you use a brew install LLVM, the Command Line Tool is deciding the preprocess definition, and Apple Clang 15 is missing the required one. For some reason llvm@17 works but it brings other issues to the build. For now the best route if your `clang --version` shows Apple Clang Version >= 15 is to uninstall Command line tools and reinstall [v14](https://developer.apple.com/download/all/?q=xcode) <- don't need a developer account, just use your AppleID regular account. This should fix the errors.
> > 
> > 
> > can we solve this by upgrading folly version?
> 
> Im not too sure, the master branch of folly is using the same [macros](https://github.com/facebook/folly/blob/bd351502b62c7983eff0b593df010b840bccc11c/folly/Memory.h#L45) which makes me think that's not possible. What might be worth doing is making sure everything is compatible with llvm17.

Hi @filip-halt , Folly is a version that we forked under milvus-io, and we can fix it quickly.

**Comment by matrixji** [comment]
I've also met such problem on macos arm. Currently when I'm compiling milvus-lite, my solution is modify the Memory.h to let continue job works.

**Comment by jiaoew1991** [comment]
should fix by this PR https://github.com/milvus-io/folly/pull/10, I will create a PR to upgrade folly in milvus

**Comment by xiaofan-luan** [comment]
should be already fixed on master branch.

**Comment by wzhfy** [comment]
hi @jiaoew1991 is it possible to submit this fix to folly? This problem bothered me for a long time... it would be great to also fix it in mainstream

**Comment by xiaofan-luan** [comment]
> hi @jiaoew1991, many thanks for the fix! Is it possible to submit this fix to folly? This problem bothered me for a long time... it would be great to also fix it in mainstream.

this should be fixed on master branch.

**Comment by xiaofan-luan** [comment]
see https://github.com/milvus-io/folly/pull/10

**Comment by wzhfy** [comment]
> see [milvus-io/folly#10](https://github.com/milvus-io/folly/pull/10)

@xiaofan-luan  thanks, but I meant could you also submit this fix to folly's main branch (https://github.com/facebook/folly)? Other projects using folly may have the same problem, so it would be great to also fix it there.

**Comment by xiaofan-luan** [comment]
> > see [milvus-io/folly#10](https://github.com/milvus-io/folly/pull/10)
> 
> @xiaofan-luan thanks, but I meant could you also submit this fix to folly's main branch (https://github.com/facebook/folly)? Other projects using folly may have the same problem, so it would be great to also fix it there.

Sure, we will send the pr to folly see if they accept it
