### ISSUE TITLE
[Bug]: Links to DNA Sequence 

### ISSUE THREAD

**Issue by RobViren** [milvus-io/milvus#27474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

None of the links to the examples on the following page works

https://milvus.io/docs/dna_sequence_classification.md

**Comment by yanliang567** [comment]
/assign @AnthonyTsu1984 
does this link still valid ?
/unassign
