### ISSUE TITLE
[Bug]: pymilvus.exceptions.MilvusException: <MilvusException: (code=5, message=the length (1748) of 0th string exceeds max length (1746): expected=valid length string, actual=string length exceeds max length: invalid parameter)>

### ISSUE THREAD

**Issue by parth-patel2023** [milvus-io/milvus#27470]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 16 GB RAM
- GPU: No
- Others:
```

### Current Behavior

pymilvus.exceptions.MilvusException: <MilvusException: (code=5, message=the length (1748) of 0th string exceeds max length (1746): expected=valid length string, actual=string length exceeds max length: invalid parameter)>

### Expected Behavior

It should be execute and add the data int Milvus db

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version: 2.2.0
> - Deployment mode(standalone or cluster): standalone
> - MQ type(rocksmq, pulsar or kafka):    
> - SDK version(e.g. pymilvus v2.0.0rc2):
> - OS(Ubuntu or CentOS): Ubuntu
> - CPU/Memory: 16 GB RAM
> - GPU: No
> - Others:
> ```
> 
> ### Current Behavior
> pymilvus.exceptions.MilvusException: <MilvusException: (code=5, message=the length (1748) of 0th string exceeds max length (1746): expected=valid length string, actual=string length exceeds max length: invalid parameter)>
> 
> ### Expected Behavior
> It should be execute and add the data int Milvus db
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

you have to specify large max length.
currently your varchar max lengh is 1746 and less than your insertion.
I would recommend 4096 at least

**Comment by parth-patel2023** [comment]
@xiaofan-luan 
Thanks for your reply.
Can you please help me because I am not able to find where I can set the max_length ?

I am using this code to store the embeddings of text so I can ask question related to that content 
vector_store = Milvus.from_documents(
    docs,
    embedding=embeddings,
    collection_name = "document",
    text_field = 'document_intro',
    connection_args={"host": MILVUS_HOST, "port": MILVUS_PORT},
)

**Comment by xiaofan-luan** [comment]
it is defined when you create collection. 
which document did you refer to?

**Comment by mmgitub** [comment]
I am also getting exactly this error.

Trying examples from this document - https://milvus.io/docs/integrate_with_langchain.md

Below step is throwing this error

In below image it create a collection name of its own. Even if I provide collection_name parameter 
![image](https://github.com/milvus-io/milvus/assets/89238340/4ee837cf-ffe3-40d9-9fe2-edf73af6dd46)

`
embeddings = OpenAIEmbeddings()

vector_store = Milvus.from_documents(
    docs,
    embedding=embeddings,
    collection_name = "my_collection",
    connection_args={"host": _MILVUS_HOST, "port": _MILVUS_PORT}
)`

Few other questions -

1. Why its not creating a collection with name we specify.
2. How to overcome this error
3. What its unloaded state

**Comment by yanliang567** [comment]
/assign @AnthonyTsu1984 
@AnthonyTsu1984  is trying to fix the doc issue.
/unassign

**Comment by gsantopaolo** [comment]
[insert_rows], <MilvusException: (code=0, message=the length (68362) of 10250th string exceeds max length (65536): expected=valid length string, actual=string length exceeds max length: invalid parameter)>, <Time:{'RPC start': '2024-07-08 23:21:27.634777', 'RPC error': '2024-07-08 23:21:28.962498'}>
 
` def store_chunk_list(self, chunk_list: List[ChunkedItem], collection_name: str, model_name: str,
                         model_dimension: int):
        entities = []

        connections.connect(
            alias=milvus_alias,
            host=milvus_host,
            port=milvus_port,
            user=milvus_user,
            password=milvus_pass
        )

        fields = [
            FieldSchema(name="id", dtype=DataType.INT64, is_primary=True, auto_id=True),
            FieldSchema(name="document_id", dtype=DataType.INT64),
            FieldSchema(name="parent_id", dtype=DataType.INT64),
            FieldSchema(name="content", dtype=DataType.VARCHAR, max_length=65535),
            FieldSchema(name="vector", dtype=DataType.FLOAT_VECTOR, dim=model_dimension),
        ]

        schema = CollectionSchema(fields=fields, enable_dynamic_field=True)
        collection = Collection(name=collection_name, schema=schema)

        index_params = {
            "index_type": milvus_index_type,
            "metric_type": milvus_metric_type,
        }

        collection.create_index(field_name="vector", index_params=index_params)
        collection.load()

        for item in chunk_list:
            content_length = len(item.content.encode('utf-8'))
            self.logger.debug(f"Original content length: {content_length}")

            # Check if the content exceeds milvus limit
            if content_length > 65535:
                truncated_content = item.content.encode('utf-8')[:65535].decode('utf-8', 'ignore')
            else:
                truncated_content = item.content

            truncated_length = len(truncated_content.encode('utf-8'))
            self.logger.debug(f"Truncated content length: {truncated_length}")

            embedding = self.embedd(truncated_content, model_name)
            json_content = {"content": truncated_content}

            json_content_length = len(str(json_content).encode('utf-8'))
            self.logger.debug(f"JSON content length: {json_content_length}")

            entities.append({
                "document_id": item.document_id,
                "parent_id": item.parent_id,
                "content": json_content,
                "vector": embedding
            })

        collection.insert(entities)
        collection.flush()
        success = True
        self.logger.debug(f"Elements successfully inserted in collection")`


pymilvus==2.4.3
milvus:v2.3.0

any suggestion?

**Comment by yanliang567** [comment]
@gsantopaolo it looks like you defined a varchar field while you are trying to insert a json value to it?
