### ISSUE TITLE
[Bug]: count(*) returns incorrect after upsert for many times

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#27515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20231007-80eb5434
- Deployment mode(standalone or cluster): standalone or cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
```

### Current Behavior

count(*) return more  after upsert for many times.  If you wait for a few minutes/hours, count(*) returns correct then.

### Expected Behavior

count(*) always returns correct. 

### Steps To Reproduce

```markdown
1. create a collection and insert 1 million entities 
2. upsert 200 entities 
3. repeat step#2 for 1000 times
4. flush() once
5. count(*) returns more than 1 million, which is incorrect.
Notes: The ids for every upsert batch are unique, but the ids could be dup between different upsert times.
6. after 1 few minutes or hours(not sure), count(*) returns 1 million correctly again.
```

### Milvus Log

pod names in devops:
```
yanliang-2c8g-etcd-0                                           1/1     Running            0                  17h     10.102.7.210    devops-node11   <none>           <none>
yanliang-2c8g-milvus-standalone-85c94f8c99-25zgm               1/1     Running            0                  17h     10.102.7.219    devops-node11   <none>           <none>
yanliang-2c8g-minio-76c6d58596-zkftp                           1/1     Running            0                  17h     10.102.7.214    devops-node11   <none>           <none>
```

### Anything else?

argo task: https://argo-qa-devops.zilliz.cc/workflows/qa/milvus-ops-upsert2-sx72z?tab=workflow&nodeId=milvus-ops-upsert2-sx72z&nodePanelView=summary

**Comment by xiaofan-luan** [comment]
is this strong consistency count?

**Comment by yanliang567** [comment]
I guess there are some dup ids in different upsert times, and the count(*) might have an issue in growing segment?
/assign @jiaoew1991 
/unassign

**Comment by xiaofan-luan** [comment]
/assign @longjiquan 
could you help on it

**Comment by xiaofan-luan** [comment]
> I guess there are some dup ids in different upsert times, and the count(*) might have an issue in growing segment? /assign @jiaoew1991 /unassign

count don't handle duplicate ids. but upsert should handle it

**Comment by yanliang567** [comment]
> is this strong consistency count?

collection params are all default, so i think no. But how does count(*) work with consistency level?

**Comment by xiaofan-luan** [comment]
@yanliang567 
is this still an issue?

**Comment by yanliang567** [comment]
yes, it still reproduces on 2.3-20231215-7facaa0c-amd64

**Comment by xiaofan-luan** [comment]
this seems to be a master issue but not related to 2.3

**Comment by yanliang567** [comment]
verified not repro on 2.3-20231227-51cab791-amd64
