### ISSUE TITLE
[Bug]: Installation

### ISSUE THREAD

**Issue by zbyso23** [milvus-io/milvus#27512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.2 & Docker version (i don't know now)
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):  ?
- SDK version(e.g. pymilvus v2.0.0rc2): ?
- OS(Ubuntu or CentOS): Ubuntu 22
- CPU/Memory: KVM (Virtual server)
- GPU: no
- Others:
```

### Current Behavior

I cannot try even `hello_milvus.py` 
with standalone version i install by deb package, but when install default version pymilvus kick me out, because deb server installed is 2.0.2 (Why?), then i install pymilvus 2.0.2, but `hello_world.py` crashed on `VARCHAR`... 
then i remove this and install docker version, that failed with exit code 132 (?)

My question is - can I try standalone/docker version properly on Ubuntu 22? this is crap, i searching for alternatives to `pg_vector` but i don't want move project to something where is problem even "Hello World", thanks

### Expected Behavior

Working `hello_milvus.py`

### Steps To Reproduce

```markdown
exactly same steps from Docs
```

**Comment by yanliang567** [comment]
@zbyso23 please try the latest release milvus v2.3.1. v2.0.2 is quite a old version and it does not support varchar
/assign @zbyso23 
/unassign
