### ISSUE TITLE
[Bug]: Query error when express has `"`

### ISSUE THREAD

**Issue by haxung** [milvus-io/milvus#27513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:  v2.2.11
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2): Go SDK v2.3.1
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When use `Query function`, if question mark `"` is in express, then function returns `error` or `nil result`.

If express is `question=="英语中颜色形容词如"green"的用法"` or `question=="英语中颜色形容词如\"green\"的用法"`, `Query function` returns `parse express error` or `nil result`.

### Expected Behavior

When express is `question=="英语中颜色形容词如\"green\"的用法"`, Query function should returns right result.

### Anything else?

This is my collection schema:
![image](https://github.com/milvus-io/milvus/assets/36329819/3f1bec74-6c5b-4b43-b22f-901ed7b1475e)

And here is a example data:
[query_result.csv](https://github.com/milvus-io/milvus/files/12839582/query_result.csv)

If express is `id=="12528c68-1904-43c0-b918-f64d7f64629c_6"`, `Query function` returns right result. But if express is `question=="英语中颜色形容词如"green"的用法"` or `question=="英语中颜色形容词如\"green\"的用法"`, `Query function` returns `parse express error` or `nil result`.

**Comment by longjiquan** [comment]
I think @JackLCL has already solved this.
/assign @JackLCL 
/unassign

**Comment by JackLCL** [comment]
When I use milvus2.2.11, I can't get results by using this expr: question == "英语中颜色形容词如\"green\"的用法"
![image](https://github.com/milvus-io/milvus/assets/53512883/31c159b0-70e0-406e-8a52-a5818c618f71)

But when I upgrade milvus to 2.3.0, I can get results by using this expr: question == "英语中颜色形容词如\"green\"的用法"
![44402bf0-d52c-4f68-bc12-09581f665ee6](https://github.com/milvus-io/milvus/assets/53512883/d7df5bad-d5af-48e3-b1a0-4568dcc1bee2)

**Comment by haxung** [comment]
> When I use milvus2.2.11, I can't get results by using this expr: question == "英语中颜色形容词如"green"的用法" ![image](https://user-images.githubusercontent.com/53512883/273436261-31c159b0-70e0-406e-8a52-a5818c618f71.png)
> 
> But when I upgrade milvus to 2.3.0, I can get results by using this expr: question == "英语中颜色形容词如"green"的用法" ![44402bf0-d52c-4f68-bc12-09581f665ee6](https://user-images.githubusercontent.com/53512883/273436301-d7df5bad-d5af-48e3-b1a0-4568dcc1bee2.jpeg)

Sorry that I cannot upgrade milvus version from 2.2.11 to 2.3.0, very few companies use the latest milvus version, and my company is not in them.

**Comment by czs007** [comment]
@haxung We have not properly handled the escape characters in the string. We plan to rectify this in version 2.2.15.

**Comment by yanliang567** [comment]
/assign @NicoYuan1986 
shall we check this kinkd of expr in our tests?
/unassign

**Comment by NicoYuan1986** [comment]
> /assign @NicoYuan1986 shall we check this kinkd of expr in our tests? /unassign

We already have similar test cases like `string == "2"`.
The issue seems to be caused by Chinese. I will add Chinese check case accordingly.
