### ISSUE TITLE
怎么在docker中安装2.3.1

### ISSUE THREAD

**Issue by zihao2981** [milvus-io/milvus#27528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

怎么在docker中使用tar.gz文件安装milvus

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What would you like to be added?
> 怎么在docker中使用tar.gz文件安装milvus
> 
> ### Why is this needed?
> _No response_
> 
> ### Anything else?
> _No response_

why not use docker compose?
