### ISSUE TITLE
R{exception=StatusRuntimeException: INTERNAL: Panic! This is a bug!, status=-3, data=null}

### ISSUE THREAD

**Issue by zihao2981** [milvus-io/milvus#27521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.1
- Deployment mode(standalone or cluster):standalone 
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): cent
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

这个bug是什么情况，使用java操作发现的

**Comment by yanliang567** [comment]
@zihao2981 could you please provide the code snippet to reproduce the issue? also it would be helpful to have full milvus logs for investigation.
/assign @zihao2981 
/unassign

**Comment by zihao2981** [comment]
R<RpcStatus> response = milvusServiceClient.loadPartitions(
                LoadPartitionsParam
                        .newBuilder()
                        .withCollectionName(collectionName)   
                        .withPartitionNames(partitionsNameList)
                        .build()
        );

**Comment by zihao2981** [comment]
这段代码就报错了

**Comment by yanliang567** [comment]
/assign @yhmo 
could you please help on this issue?

/unassign

**Comment by zihao2981** [comment]
> /assign @yhmo 
> 
> could you please help on this issue?
> 
> 
> 
> /unassign

需要我怎么做

**Comment by zihao2981** [comment]
需要我怎么做，不太会使用email

On Oct 8, 2023, at 15:06, yanliang567 ***@***.***> wrote:

﻿

/assign @yhmo<https://github.com/yhmo>
could you please help on this issue?

/unassign

**Comment by zihao2981** [comment]
> unassign

@yanliang567 需要我怎么做

**Comment by zihao2981** [comment]
> /assign @yhmo could you please help on this issue?
> 
> /unassign

@yanliang567 怎么能保持迅速联系，我这边开发有点急，你有电话吗？

**Comment by xiaofan-luan** [comment]
seems to due to jar conflict
https://github.com/milvus-io/milvus-sdk-java/issues/618

**Comment by zihao2981** [comment]
yes，我认为是jar包冲突导致的，现在报错是nosuchmethod

Caused by: java.lang.NoSuchMethodError: io.netty.buffer.PooledByteBufAllocator.<init>(ZIIIIIIZ)V

On Oct 8, 2023, at 17:41, Xiaofan ***@***.***> wrote:

﻿

seems to due to jar conflict
milvus-io/milvus-sdk-java#618<https://github.com/milvus-io/milvus-sdk-java/issues/618>

**Comment by zihao2981** [comment]
@xiaofan-luan 请问能帮忙看下吗

**Comment by yhmo** [comment]
@zihao2981 
说实话，我们也没法重现这个问题，所以原因也无法知。你可以pin一下那个[milvus-io/milvus-sdk-java#618]解决了该问题的用户，问下他是怎么解决的。
