### ISSUE TITLE
Milvus format vector data to double-precision and return to http client 

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#2752]
**Describe the bug**
Milvus format vector data to double-precision and return to http client 

**Steps/Code to reproduce behavior**
1. start milvus server
2. create a collection, insert some vectors
3. use restful api to get vector by id

result:
client receive json string like [0.22993213002321423, 0.78535038300384498...]

**Expected behavior**
json string should be [0.22993213, 0.78535038...]

**Environment details**
- Milvus version 0.10.0

**Comment by yhmo** [comment]
This is caused by nlohmann::json, a thirdparty library for json construct/parse. In function json::dump().

**Comment by nantonop** [comment]
Hello,  will we see a fix for this issue implemented in version 0.10.1?

Thanks,

Nick

**Comment by yhmo** [comment]
@nantonop 

Not sure, I have reported an issue to nlohmann::json:
https://github.com/nlohmann/json/issues/2254

**Comment by yhmo** [comment]
Use 
`nlohmann::basic_json<std::map, std::vector, std::string, bool, std::int64_t, std::uint64_t, float> json;`
to replace 
`nlohmann::json`

**Comment by yhmo** [comment]
Fixed by pr2789 in 0.10.1 branch

**Comment by nantonop** [comment]
Thank you!
