### ISSUE TITLE
[Bug]: All indexNode CrashLoopBackOff during the index building

### ISSUE THREAD

**Issue by icodersky** [milvus-io/milvus#27533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.1
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.3.1
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 700GB
- GPU: 
- Others:
```

### Current Behavior

At present, we have encountered some issues using version 2.3.1. We have reported errors several times and were unable to import. However, when we imported 170 million pieces of data, we did not create any index and the import was completed normally. 

Currently, when we added a vector index to my set that has already been imported, we reported an error. At this time, all indexnodes have automatically restarted and CrashLoopBackOff.

Help me see what's going on?

### Milvus Log

Here is the log:
[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/12840414/milvus-log.tar.gz)

**Comment by yanliang567** [comment]
@icodersky it seems that indexnode did not get the data successfully, what kind of object storage are you using?
/assign @icodersky 
/unassign

**Comment by icodersky** [comment]
> @icodersky it seems that indexnode did not get the data successfully, what kind of object storage are you using? /assign @icodersky /unassign

we use nfs.

**Comment by icodersky** [comment]
The nft had 3.5TB milvus data.
<img width="788" alt="20231008190204" src="https://github.com/milvus-io/milvus/assets/86787724/4963203c-8a3f-4966-a6e9-02220be5174d">
<img width="1056" alt="2" src="https://github.com/milvus-io/milvus/assets/86787724/e8610355-9c76-44ee-a614-17b66d852813">

**Comment by LoveEachDay** [comment]
@icodersky Using nfs as minio backend is not recommended. You cannot guarantee to read after writes.
```
Network File System Volumes Break Consistency Guarantees

MinIO’s strict read-after-write and list-after-write consistency model requires local drive filesystems.

MinIO cannot provide consistency guarantees if the underlying storage volumes are NFS or a similar network-attached storage volume.

For deployments that require using network-attached storage, use NFSv4 for best results.
```

**Comment by LoveEachDay** [comment]
@icodersky Could you also upload the logs for minio pods?

**Comment by icodersky** [comment]
> @icodersky Using nfs as minio backend is not recommended. You cannot guarantee to read after writes.
> 
> ```
> Network File System Volumes Break Consistency Guarantees
> 
> MinIO’s strict read-after-write and list-after-write consistency model requires local drive filesystems.
> 
> MinIO cannot provide consistency guarantees if the underlying storage volumes are NFS or a similar network-attached storage volume.
> 
> For deployments that require using network-attached storage, use NFSv4 for best results.
> ```

What kind of object storage is recommend?

**Comment by icodersky** [comment]
> @icodersky Could you also upload the logs for minio pods?
here is the minio's log:
[minio.zip](https://github.com/milvus-io/milvus/files/12840509/minio.zip)

**Comment by congqixia** [comment]
Similar error message in this issue as well:
https://github.com/milvus-io/milvus/issues/27374

**Comment by congqixia** [comment]
@icodersky quick question, did you update `useVirtualHost` value under minio section?

**Comment by icodersky** [comment]
> @icodersky quick question, did you update `useVirtualHost` value under minio section?

we install milvus2.3.1 use follow command:

helm upgrade --install --set log.level=error --set indexNode.replicas=200 --set dataNode.replicas=50 --set proxy.replicas=20 --set queryCoord.replicas=1 --set queryNode.replicas=50  --set attu.enabled=true --set storage.mmap.enabled=true --set queryNode.mmapDirPath=/home/milvus_mmap  hx-release milvus/milvus --version=4.1.4

**Comment by icodersky** [comment]
we want to use mmap like this:
https://mp.weixin.qq.com/s/N-_X_YF8ZSzQvaCut2tr-Q

**Comment by LoveEachDay** [comment]
> > @icodersky Using nfs as minio backend is not recommended. You cannot guarantee to read after writes.
> > ```
> > Network File System Volumes Break Consistency Guarantees
> > 
> > MinIO’s strict read-after-write and list-after-write consistency model requires local drive filesystems.
> > 
> > MinIO cannot provide consistency guarantees if the underlying storage volumes are NFS or a similar network-attached storage volume.
> > 
> > For deployments that require using network-attached storage, use NFSv4 for best results.
> > ```
> 
> What kind of object storage is recommend?

We officially support minio with local block storage, aws s3, gcp gcs, aliyun oss.

**Comment by icodersky** [comment]
By the way, we use helm to install milvus2.3.1 in k8s, the k8s 's storage class use nfs-client-provisioner:v3.1.0.

Why we can insert all vectordata to the milvus, but can't build the index, is only reason of the nfs?

**Comment by icodersky** [comment]
Maybe is my setting of the MMap cause the error?

**Comment by icodersky** [comment]
> @icodersky quick question, did you update `useVirtualHost` value under minio section?

we did not update the `useVirtualHost` value.

**Comment by icodersky** [comment]
In addition, we previously tested that indexing and loading data were normal after importing 1.2 million data. But after importing the data later, the indexNode crashed, and we reinstalled and re imported it later on

**Comment by icodersky** [comment]
At present, I have found that I imported a small amount of data, 460000 pieces of data, which are indexed and loaded normally, and the query is also normal.


<img width="1058" alt="16968361399821" src="https://github.com/milvus-io/milvus/assets/86787724/f444e53d-5115-49a2-acce-6e785a1558c5">

**Comment by icodersky** [comment]
Hello, have you found the problem?

**Comment by xiaofan-luan** [comment]
@icodersky 
So far it's pretty sure it's a object store timeout.
Is this your S3 or minio or other deployment?
could you use https://github.com/zhagnlu/milvus-store-tool  to check the S3 connector can connect to your cluster?

**Comment by icodersky** [comment]
> @icodersky So far it's pretty sure it's a object store timeout. Is this your S3 or minio or other deployment? could you use [https://github.com/zhagnlu/milvus-store-tool ](https://github.com/zhagnlu/milvus-store-tool%C2%A0) to check the S3 connector can connect to your cluster?

OK,Let's give it a try.

**Comment by icodersky** [comment]
> @icodersky So far it's pretty sure it's a object store timeout. Is this your S3 or minio or other deployment? could you use [https://github.com/zhagnlu/milvus-store-tool ](https://github.com/zhagnlu/milvus-store-tool%C2%A0) to check the S3 connector can connect to your cluster?


When we make install, the following error occurred. How to handle it.


<img width="928" alt="16969063385982" src="https://github.com/milvus-io/milvus/assets/86787724/37db8ef6-7f26-42c3-b5de-b39e1426475a">

**Comment by zhagnlu** [comment]
> > @icodersky So far it's pretty sure it's a object store timeout. Is this your S3 or minio or other deployment? could you use [https://github.com/zhagnlu/milvus-store-tool ](https://github.com/zhagnlu/milvus-store-tool%C2%A0) to check the S3 connector can connect to your cluster?
> 
> When we make install, the following error occurred. How to handle it.
> 
> <img alt="16969063385982" width="928" src="https://user-images.githubusercontent.com/86787724/273761975-37db8ef6-7f26-42c3-b5de-b39e1426475a.png">

Hi, Could you update this repo and try it again, we fixed it right now.  After  building it,  you can modify configuration in  src/configs/milvus.yaml as you need. 
![image](https://github.com/milvus-io/milvus/assets/11935707/e0f17bf8-4292-4511-99c2-992d400e0d62)
We will post a document about configuration details afterwards, you can configure it as you known.

**Comment by icodersky** [comment]
> > > @icodersky So far it's pretty sure it's a object store timeout. Is this your S3 or minio or other deployment? could you use [https://github.com/zhagnlu/milvus-store-tool ](https://github.com/zhagnlu/milvus-store-tool%C2%A0) to check the S3 connector can connect to your cluster?
> > 
> > 
> > When we make install, the following error occurred. How to handle it.
> > <img alt="16969063385982" width="928" src="https://user-images.githubusercontent.com/86787724/273761975-37db8ef6-7f26-42c3-b5de-b39e1426475a.png">
> 
> Hi, Could you update this repo and try it again, we fixed it right now. After building it, you can modify configuration in src/configs/milvus.yaml as you need. ![image](https://user-images.githubusercontent.com/11935707/273815950-e0f17bf8-4292-4511-99c2-992d400e0d62.png) We will post a document about configuration details afterwards, you can configure it as you known.

OK, I try.

**Comment by zhagnlu** [comment]
Could you provide  a minimize  "Steps To Reproduce" and we try to reproduce it

**Comment by icodersky** [comment]
My nfs configuration is:

1. Configuring nfs provisioner using plugin nfs subdir external provisioner: v4.0.0
2. Create users and roles rbac roles
3. Create storage class storage class

we run milvus-store-tool , the result as follow:

<img width="1052" alt="16971616621321" src="https://github.com/milvus-io/milvus/assets/86787724/08f4d623-dff0-4677-be5f-3fd518792c92">

**Comment by xiaofan-luan** [comment]
seems that this is caused by performance limitation of your storage?

**Comment by xiaofan-luan** [comment]
@zhagnlu 
could we just retry on 503 and longer the timeout?
set it to 30s by default

**Comment by icodersky** [comment]
> @zhagnlu could we just retry on 503 and longer the timeout? set it to 30s by default

What is 503? where to set?

**Comment by zhagnlu** [comment]
> > @zhagnlu could we just retry on 503 and longer the timeout? set it to 30s by default
> 
> What is 503? where to set?

503 slow down indicates your storage server opens the rate limiting rules, you can modify this rule in server configure.  Could you check your storage server and close this policy and try ?

**Comment by xiaofan-luan** [comment]
> > > @zhagnlu could we just retry on 503 and longer the timeout? set it to 30s by default
> > 
> > 
> > What is 503? where to set?
> 
> 503 slow down indicates your storage server opens the rate limiting rules, you can modify this rule in server configure. Could you check your storage server and close this policy and try ?

we should retry on S3 if 503 happened in MinioChunkManager?

**Comment by icodersky** [comment]
> > > > @zhagnlu could we just retry on 503 and longer the timeout? set it to 30s by default
> > > 
> > > 
> > > What is 503? where to set?
> > 
> > 
> > 503 slow down indicates your storage server opens the rate limiting rules, you can modify this rule in server configure. Could you check your storage server and close this policy and try ?
> 
> we should retry on S3 if 503 happened in MinioChunkManager?

we don't had S3, we use nfs.

**Comment by xiaofan-luan** [comment]
> > > > > @zhagnlu could we just retry on 503 and longer the timeout? set it to 30s by default
> > > > 
> > > > 
> > > > What is 503? where to set?
> > > 
> > > 
> > > 503 slow down indicates your storage server opens the rate limiting rules, you can modify this rule in server configure. Could you check your storage server and close this policy and try ?
> > 
> > 
> > we should retry on S3 if 503 happened in MinioChunkManager?
> 
> we don't had S3, we use nfs.

We use S3 connector, and nfs throw 503 error, which is rate limiting I guess

**Comment by zhagnlu** [comment]
> > > > > > @zhagnlu could we just retry on 503 and longer the timeout? set it to 30s by default
> > > > > 
> > > > > 
> > > > > What is 503? where to set?
> > > > 
> > > > 
> > > > 503 slow down indicates your storage server opens the rate limiting rules, you can modify this rule in server configure. Could you check your storage server and close this policy and try ?
> > > 
> > > 
> > > we should retry on S3 if 503 happened in MinioChunkManager?
> > 
> > 
> > we don't had S3, we use nfs.
> 
> We use S3 connector, and nfs throw 503 error, which is rate limiting I guess

yes,  I think returning these server behavior to client is better.  For this kind of error, alert user is better and user modify it to fix.  Anyway, retry maybe not fix  such as low requests per second.
