### ISSUE TITLE
[Enhancement]: Refine flushmanger

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#27532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

1. Current flush manager is not a single instance on the datanode thus hard to manage concurreny and global memory
2. Current flush manager abuse goroutine usage and may cause go routine number increate fast.
3. Flush failed will cause system panic, however flush can be handled asyncly.
4. The inject policy could be removed after L0 delete.

Thus I propose to refine flushmanager with the new singleton implementation.
All the check(memory, concurrency) can be handled by background go routine.
All the data buffer is managed by flushmanager
If flush failed, there should be a reschedule go routine to handle reflush
If memory is overflowed, flush manager can stall all the msg stream to avoid OOM.
Flush is executed by a pool, concurrency is easier to control

**Comment by congqixia** [comment]
/reopen
WIP
