### ISSUE TITLE
[Bug]: e2e failed in build step 

### ISSUE THREAD

**Issue by weiliu1031** [milvus-io/milvus#27549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

e2e failed in build step.

link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-26929/10/pipeline/

**Comment by yanliang567** [comment]
not e2e related, @congqixia could you please help on it?
/assign @congqixia 
/unassign
