### ISSUE TITLE
How to choose the distance calculation method?

### ISSUE THREAD

**Issue by 670133189** [milvus-io/milvus#2754]
For example, I choose ivfsq8, which means that there are two automatic distance calculation methods: Euclidean distance (L2), inner product (IP)?

**Comment by tinkerlin** [comment]
when create collection you can choose that.

Refer to https://github.com/milvus-io/pymilvus and check `Create/Drop collections` chapter.

**Comment by yhmo** [comment]
The difference is: 
If you want to use inner product(IP), you need to normalize your vectors, like this:
![NumberedEquation1](https://user-images.githubusercontent.com/2282099/86696548-1fab9580-c040-11ea-8769-75bc7bae4563.gif)

Euclidean distance(L2) no need to do that.
