### ISSUE TITLE
[Bug]: The etcd service of milvus generates a lot of zombie processes

### ISSUE THREAD

**Issue by cyxinda** [milvus-io/milvus#27544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.1
- Deployment mode(cluster ):
- MQ type( pulsar  ):    
- OS(rocky 9.2 ): 
- CPU/Memory: 
- GPU: 
- Others: kubernetes version v1.24.16
```

### Current Behavior

About ten hours after I deployed milvus, the etcd service generated a lot of zombie processes.
![截图 2023-10-09 10-51-57](https://github.com/milvus-io/milvus/assets/7237898/5f3eb82c-3cba-4f58-8ebb-9f4e4124c110)
After I traced the zombie process tree, I'm sure that these zombie processes were caused by the etcd service of milvus .
The tracking process  attached below:
```bash
[root@sc-midware-3 ~]# ps -aux | grep defunct
1001     3312846  0.0  0.0      0     0 ?        Z    20:11   0:00 [etcdctl] <defunct>
1001     3313141  0.0  0.0      0     0 ?        Z    20:11   0:00 [etcdctl] <defunct>
1001     3313444  0.0  0.0      0     0 ?        Z    20:12   0:00 [etcdctl] <defunct>
1001     3313446  0.0  0.0      0     0 ?        Z    20:12   0:00 [etcdctl] <defunct>
1001     3313748  0.0  0.0      0     0 ?        Z    20:12   0:00 [etcdctl] <defunct>
1001     3314042  0.0  0.0      0     0 ?        Z    20:12   0:00 [etcdctl] <defunct>
........
```
![截图 2023-10-09 11-03-11](https://github.com/milvus-io/milvus/assets/7237898/9ce05674-bd80-4179-90c2-69317829d177)
```bash
[root@sc-midware-3 ~]# ps -ef|grep 3312846
1001     3312846 3302563  0 20:11 ?        00:00:00 [etcdctl] <defunct>
root     3634864 1270316  0 23:03 pts/2    00:00:00 grep --color=auto 3312846
[root@sc-midware-3 ~]# ps -ef|grep 3302563
1001     3302563 1329669  0 20:06 ?        00:01:07 etcd
1001     3312846 3302563  0 20:11 ?        00:00:00 [etcdctl] <defunct>
1001     3313141 3302563  0 20:11 ?        00:00:00 [etcdctl] <defunct>
1001     3313444 3302563  0 20:12 ?        00:00:00 [etcdctl] <defunct>
1001     3313446 3302563  0 20:12 ?        00:00:00 [etcdctl] <defunct>
1001     3313748 3302563  0 20:12 ?        00:00:00 [etcdctl] <defunct>
1001     3314042 3302563  0 20:12 ?        00:00:00 [etcdctl] <defunct>
1001     3314167 3302563  0 20:12 ?        00:00:00 [etcdctl] <defunct>
1001     3314414 3302563  0 20:12 ?        00:00:00 [etcdctl] <defunct>
1001     3314447 3302563  0 20:12 ?        00:00:00 [etcdctl] <defunct>
1001     3382359 3302563  0 20:49 ?        00:00:00 [etcdctl] <defunct>
1001     3382360 3302563  0 20:49 ?        00:00:00 [etcdctl] <defunct>
1001     3382616 3302563  0 20:49 ?        00:00:00 [etcdctl] <defunct>
1001     3382914 3302563  0 20:49 ?        00:00:00 [etcdctl] <defunct>
1001     3383261 3302563  0 20:50 ?        00:00:00 [etcdctl] <defunct>
1001     3383269 3302563  0 20:50 ?        00:00:00 [etcdctl] <defunct>
1001     3383522 3302563  0 20:50 ?        00:00:00 [etcdctl] <defunct>
1001     3383692 3302563  0 20:50 ?        00:00:00 [etcdctl] <defunct>
1001     3383897 3302563  0 20:50 ?        00:00:00 [etcdctl] <defunct>
1001     3384244 3302563  0 20:50 ?        00:00:00 [etcdctl] <defunct>
1001     3384253 3302563  0 20:50 ?        00:00:00 [etcdctl] <defunct>
1001     3441701 3302563  0 21:21 ?        00:00:00 [etcdctl] <defunct>
1001     3441994 3302563  0 21:21 ?        00:00:00 [etcdctl] <defunct>
1001     3442340 3302563  0 21:21 ?        00:00:00 [etcdctl] <defunct>
1001     3442350 3302563  0 21:21 ?        00:00:00 [etcdctl] <defunct>
1001     3442598 3302563  0 21:21 ?        00:00:00 [etcdctl] <defunct>
1001     3442894 3302563  0 21:21 ?        00:00:00 [etcdctl] <defunct>
1001     3443073 3302563  0 21:21 ?        00:00:00 [etcdctl] <defunct>
1001     3443307 3302563  0 21:22 ?        00:00:00 [etcdctl] <defunct>
1001     3443338 3302563  0 21:22 ?        00:00:00 [etcdctl] <defunct>
1001     3443579 3302563  0 21:22 ?        00:00:00 [etcdctl] <defunct>
1001     3443912 3302563  0 21:22 ?        00:00:00 [etcdctl] <defunct>
[root@sc-midware-3 ~]# ps -aux|grep 3302563
1001     3302563  0.6  0.0 5978252 70440 ?       Ssl  20:06   1:11 etcd
root     3635591  0.0  0.0   3876  2088 pts/2    S+   23:04   0:00 grep --color=auto 3302563
[root@sc-midware-3 ~]# ctr -n k8s.io container ls > /tmp/container.list && ctr -n k8s.io task ls > /tmp/task.list && awk 'FNR==NR {dict[$1]=$0;next}{if($1 in dict){$1=dict[$1]" "$2" "$3}print $1}' /tmp/task.list /tmp/container.list|grep 3302563
e48b181f1e32ca7f5f434072e6f255122e4844d190d8b04026094e03d81ec6a6    3302563    RUNNING docker.io/milvusdb/etcd:3.5.5-r2 io.containerd.runc.v2
[root@sc-midware-3 ~]# kubectl -n milvus-1 get pods -owide |grep sc-midware-3
elasticsearch-etcd-1                               1/1     Running     4 (3h1m ago)     20h   10.244.48.91     sc-midware-3   <none>           <none>
elasticsearch-milvus-querynode-864fbdfd99-tjzpc    1/1     Running     8 (36m ago)      20h   10.244.48.82     sc-midware-3   <none>           <none>
elasticsearch-minio-0                              1/1     Running     0                20h   10.244.48.96     sc-midware-3   <none>           <none>
elasticsearch-minio-3                              1/1     Running     0                20h   10.244.48.86     sc-midware-3   <none>           <none>
elasticsearch-pulsar-bookie-0                      1/1     Running     0                20h   10.244.48.87     sc-midware-3   <none>           <none>
elasticsearch-pulsar-recovery-0                    1/1     Running     0                20h   10.244.48.83     sc-midware-3   <none>           <none>
elasticsearch-pulsar-zookeeper-0                   1/1     Running     0                20h   10.244.48.106    sc-midware-3   <none>           <none>
[root@sc-midware-3 ~]# kubectl -n milvus-1 describe pod  elasticsearch-etcd-1 |grep e48b181f1e32ca7f5f434072e6f255122e4844d190d8b04026094e03d81ec6a6
    Container ID:   containerd://e48b181f1e32ca7f5f434072e6f255122e4844d190d8b04026094e03d81ec6a6
```
![截图 2023-10-09 11-09-15](https://github.com/milvus-io/milvus/assets/7237898/f49c2214-de49-4d4c-9d25-2b6c57668e22)
![截图 2023-10-09 11-14-32](https://github.com/milvus-io/milvus/assets/7237898/6164be7f-f674-40be-b219-cb28bd501545)

The same thing happened with the other two etcd services .

**Comment by yanliang567** [comment]
/assign @LoveEachDay 
please help to check it.
/unassign

**Comment by LoveEachDay** [comment]
By default we enabled pod readiness and liveness probe with a script like this:
<img width="1448" alt="image" src="https://github.com/milvus-io/milvus/assets/1573213/563bf8a5-c171-433a-a1b5-f942a22da34d">
And in this `healthcheck.sh`, it invokes `etcdctl endpoint health` to check endpoint healthy.

Kubelet will use this script to detect pod readiness and liveness periodically. That's why there are many zoobie process if your etcd cluster is not healthy.

You'd first check the etcd log to find why the `etcdctl endpoint health` takes so long to complete. Could you upload the log of etcd pod?

**Comment by LoveEachDay** [comment]
See also https://github.com/bitnami/charts/issues/13989

**Comment by knowdee** [comment]
file:///data2/etcd.log


> 默认情况下，我们使用如下脚本启用了 pod 就绪性和活性探测： 在这个脚本中，它调用来检查端点是否健康。 <img alt="图像" width="1448" src="https://user-images.githubusercontent.com/1573213/273517838-563bf8a5-c171-433a-a1b5-f942a22da34d.png">`healthcheck.sh``etcdctl endpoint health`
> 
> Kubelet 将使用此脚本定期检测 pod 的准备情况和活跃度。这就是为什么如果你的 etcd 集群不健康的话会有很多zoobie进程。
> 
> 您首先要检查 etcd 日志，找出为什么需要`etcdctl endpoint health`这么长时间才能完成。可以上传一下etcd pod的日志吗？

**Comment by knowdee** [comment]
> 默认情况下，我们使用如下脚本启用了 pod 的稳定性和活性： 在该脚本中，它调用来检查端点是否健康。 <img alt="图像" width="1448" src="https://user-images.githubusercontent.com/1573213/273517838-563bf8a5-c171-433a-a1b5-f942a22da34d.png">`healthcheck.sh``etcdctl endpoint health`
> 
> Kubelet 将使用此脚本定期检测 pod 的准备情况和活跃程度。这就是为什么如果您的 etcd 集群不健康的话会有很多zoobie进程。
> 
> 您首先要检查etcd日志，找出为什么需要`etcdctl endpoint health`这么长时间才能完成。可以上传一下etcd pod的日志吗？

[etcd.log](https://github.com/milvus-io/milvus/files/12845383/etcd.log)

**Comment by cyxinda** [comment]
> By default we enabled pod readiness and liveness probe with a script like this: <img alt="image" width="1448" src="https://user-images.githubusercontent.com/1573213/273517838-563bf8a5-c171-433a-a1b5-f942a22da34d.png"> And in this `healthcheck.sh`, it invokes `etcdctl endpoint health` to check endpoint healthy.
> 
> Kubelet will use this script to detect pod readiness and liveness periodically. That's why there are many zoobie process if your etcd cluster is not healthy.
> 
> You'd first check the etcd log to find why the `etcdctl endpoint health` takes so long to complete. Could you upload the log of etcd pod?

my etcd pod log as follow:
[etcd.log](https://github.com/milvus-io/milvus/files/12845395/etcd.log)

**Comment by xiaofan-luan** [comment]
> By default we enabled pod readiness and liveness probe with a script like this: <img alt="image" width="1448" src="https://user-images.githubusercontent.com/1573213/273517838-563bf8a5-c171-433a-a1b5-f942a22da34d.png"> And in this `healthcheck.sh`, it invokes `etcdctl endpoint health` to check endpoint healthy.
> 
> Kubelet will use this script to detect pod readiness and liveness periodically. That's why there are many zoobie process if your etcd cluster is not healthy.
> 
> You'd first check the etcd log to find why the `etcdctl endpoint health` takes so long to complete. Could you upload the log of etcd pod?

Should the process left even if health check failed?

**Comment by cyxinda** [comment]
> > By default we enabled pod readiness and liveness probe with a script like this: <img alt="image" width="1448" src="https://user-images.githubusercontent.com/1573213/273517838-563bf8a5-c171-433a-a1b5-f942a22da34d.png"> And in this `healthcheck.sh`, it invokes `etcdctl endpoint health` to check endpoint healthy.
> > Kubelet will use this script to detect pod readiness and liveness periodically. That's why there are many zoobie process if your etcd cluster is not healthy.
> > You'd first check the etcd log to find why the `etcdctl endpoint health` takes so long to complete. Could you upload the log of etcd pod?
> 
> Should the process left even if health check failed?

I increased the parameter value of the operating system to limit the number of files. Since then, the zoobie process has not appeared, and the etcd service has not been restarted.
like this:
- /etc/sysctl.conf
```bash
cat > /etc/sysctl.conf << EOF
fs.file-max=102400
net.nf_conntrack_max = 1024000
net.netfilter.nf_conntrack_max = 1024000
EOF
```
- /etc/security/limits.conf 
```bash
cat > /etc/security/limits.conf << EOF
* hard nofile 102400
* soft nofile 102400
EOF
``` 
So let’s assume that this is the cause of the problem.And I will continue to observe that later.

**Comment by knowdee** [comment]
@LoveEachDay @xiaofan-luan 
Two days later, the zoobie process appeared again in the pod of the milvus ectd service.And no ectd  service pod restart.
I think the reason for the zombie process is that the check script did not wait for the etcdctl subprocess to end when it exited. After the etcdctl child process ends and its parent process no longer exists, the child process will become an orphan process and be taken over by the process with process number 1. The orphan process at this time is a zombie process. In the operating system, the process with process number 1 is the init process. The Init process can wait for the child process and then terminate it. However, in the docker environment, the process with process number 1 is not the init process of the operating system, and cannot perform the behavior of the init process and terminate the etcd child process.
So I suggest the `wait()` should been add to  the check script(/opt/bitnami/scripts/etcd/healthcheck.sh)
```bash

 #!/bin/bash

# shellcheck disable=SC1091

set -o errexit
set -o pipefail
set -o nounset

# Load libraries
. /opt/bitnami/scripts/libos.sh
. /opt/bitnami/scripts/libnet.sh
. /opt/bitnami/scripts/libetcd.sh

# Load etcd environment settings
. /opt/bitnami/scripts/etcd-env.sh

read -r -a advertised_array <<< "$(tr ',;' ' ' <<< "$ETCD_ADVERTISE_CLIENT_URLS")"
host="$(parse_uri "${advertised_array[0]}" "host")"
port="$(parse_uri "${advertised_array[0]}" "port")"
read -r -a extra_flags <<< "$(etcdctl_auth_flags)"
extra_flags+=("--endpoints=${host}:${port}")
if [[ $ETCD_AUTO_TLS = true ]]; then
     extra_flags+=("--insecure-skip-tls-verify")
fi
if etcdctl endpoint health "${extra_flags[@]}"; then
    wait
    exit 0
else
    error "Unhealthy endpoint!"
    wait
    exit 1
fi
```

**Comment by cyxinda** [comment]
> @LoveEachDay @xiaofan-luan Two days later, the zoobie process appeared again in the pod of the milvus ectd service.And no ectd service pod restart. I think the reason for the zombie process is that the check script did not wait for the etcdctl subprocess to end when it exited. After the etcdctl child process ends and its parent process no longer exists, the child process will become an orphan process and be taken over by the process with process number 1. The orphan process at this time is a zombie process. In the operating system, the process with process number 1 is the init process. The Init process can wait for the child process and then terminate it. However, in the docker environment, the process with process number 1 is not the init process of the operating system, and cannot perform the behavior of the init process and terminate the etcd child process. So I suggest the `wait()` should been add to the check script(/opt/bitnami/scripts/etcd/healthcheck.sh)
> 
> ```shell
>  #!/bin/bash
> 
> # shellcheck disable=SC1091
> 
> set -o errexit
> set -o pipefail
> set -o nounset
> 
> # Load libraries
> . /opt/bitnami/scripts/libos.sh
> . /opt/bitnami/scripts/libnet.sh
> . /opt/bitnami/scripts/libetcd.sh
> 
> # Load etcd environment settings
> . /opt/bitnami/scripts/etcd-env.sh
> 
> read -r -a advertised_array <<< "$(tr ',;' ' ' <<< "$ETCD_ADVERTISE_CLIENT_URLS")"
> host="$(parse_uri "${advertised_array[0]}" "host")"
> port="$(parse_uri "${advertised_array[0]}" "port")"
> read -r -a extra_flags <<< "$(etcdctl_auth_flags)"
> extra_flags+=("--endpoints=${host}:${port}")
> if [[ $ETCD_AUTO_TLS = true ]]; then
>      extra_flags+=("--insecure-skip-tls-verify")
> fi
> if etcdctl endpoint health "${extra_flags[@]}"; then
>     wait
>     exit 0
> else
>     error "Unhealthy endpoint!"
>     wait
>     exit 1
> fi
> ```
> 
> The wait() function is used to block the parent process (that is, the process that calls wait()) until a child process ends or the process receives a specified signal.

I test this way after I add wait function to the script of  /opt/bitnami/scripts/etcd/healthcheck.sh .
There are still zombie process appare.

**Comment by cyxinda** [comment]
> See also [bitnami/charts#13989](https://github.com/bitnami/charts/issues/13989)

I add `shareProcessNamespace: true` to the yaml of the etcd yaml ,It works.
Another way to recycle orphan processes is to add tini to the pod that spawn the zombie process.
refer to https://github.com/krallin/tini
