### ISSUE TITLE
There is no gpu_resource_config in the document

### ISSUE THREAD

**Issue by arya0812** [milvus-io/milvus#2755]
## Report incorrect documentation

**Location of incorrect documentation**
[下载并修改配置文件](https://milvus.io/cn/docs/v0.10.0/guides/get_started/install_milvus/gpu_milvus_docker.md#%E4%B8%8B%E8%BD%BD%E5%B9%B6%E4%BF%AE%E6%94%B9%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6)

**Comment by tinkerlin** [comment]
Some errors did appear in the documentation, thks!
