### ISSUE TITLE
[Bug]: DiskANN param compatibility between 2.2 and 2.3

### ISSUE THREAD

**Issue by foxspy** [milvus-io/milvus#27556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

DISKANN move search cache generation from load stage to build stage to reduce the loading cost, so param `searchCache` will be delivered at build stage to limit the memory resource, and milvus add a param checking to guarantee the param delivering. However, the old milvus image does not deliver the `searchCache` param and when the `IndexNode` has been upgraded to 2.3 but `proxy` is still 2.2, the building diskann index task will be failed for param checking.

**Comment by yanliang567** [comment]
@foxspy could you please share more details about the solution you fix the issue?
/assign @foxspy 
/unassign
