### ISSUE TITLE
[Bug]: e2e failed in case `test_delete_string_expressions_normal`

### ISSUE THREAD

**Issue by weiliu1031** [milvus-io/milvus#27550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-27362/7/pipeline/164/

**Comment by yanliang567** [comment]
I reran the test for 10+ times with 6 concurrents, but not reproduced...:(

**Comment by yanliang567** [comment]
close for now, not reproduced after the case updated
