### ISSUE TITLE
Milvus cannot connect to etcd when set etcd auth enabled

### ISSUE THREAD

**Issue by chenraoCR** [milvus-io/milvus#27555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster): standalone 
- MQ type(rocksmq, pulsar or kafka): kafka
- Metadata storage: etcd with auth enabled
- S3: minio
```

### Current Behavior

when startup external etcd server, and then enable etcd auth, then startup milvus to connect the external etcd, cannot connect it. there will have flowing errors:
![image](https://github.com/milvus-io/milvus/assets/45187622/3a333c92-622f-478e-a446-08356cbfb59b)

### Expected Behavior

when etcd server enables auth, milvus should be able to config ectd username & password, then milvus can connect etcd server

### Steps To Reproduce

```markdown
1. startup etcd server
2. enable ectd auth with cmd: `etcdctl --endpoinits=localhost:2379 auth enable` (if root user not exists, add it first)
3. config milvus.yaml, config etcd.endpoints to connect ectd server, set metastore.type to etcd
4. startup milvus
```

### Milvus Log

![image](https://github.com/milvus-io/milvus/assets/45187622/3a333c92-622f-478e-a446-08356cbfb59b)

**Comment by yanliang567** [comment]
@chenraoCR I am afraid that Milvus does not support setting etcd auth enabled for now.
/assign @chenraoCR 
/unassign

**Comment by chenraoCR** [comment]
@yanliang567 okay, got it and thanks, and could I know do you have the plan to set ectd auth enabled in the future?
