### ISSUE TITLE
[Bug]: Attu using `in` or `not in` in expressions returns `cannot parse expressions` error if primary key(id) is `varchar`

### ISSUE THREAD

**Issue by haxung** [milvus-io/milvus#27568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.14
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2): Go SDK v2.3.1
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

How to use query expr `in` or `not in` if primary key `id` is `varchar` data type?

If expr is `id in [12528c68-1904-43c0-b918-f64d7f64629c_6]`, then returns error like below:
![image](https://github.com/milvus-io/milvus/assets/36329819/e4857006-a00a-4a09-9dba-5a70822ab913).

Then if expr is `id in ["12528c68-1904-43c0-b918-f64d7f64629c_6"]`, then returns error like below:
![image](https://github.com/milvus-io/milvus/assets/36329819/6d2e47d1-88c2-4879-bd55-38712bb5990e)

Finally expr is `id in [\"12528c68-1904-43c0-b918-f64d7f64629c_6\"]`, then returns error like below:
![image](https://github.com/milvus-io/milvus/assets/36329819/a3d55714-65b0-48cc-ab31-feb2f32dc438)

If use go SDK, for example:

```go
......
expr := fmt.Sprintf(`id in [%s]`, `"12528c68-1904-43c0-b918-f64d7f64629c_6"`)
resultSet, err = c.Query(context.Background(), coll, nil, expr, []string{"id"})
if err != nil {
	panic(err)
}
fmt.Println(len(resultSet), resultSet.GetColumn("id").Len())
```
This returns right result.

**Comment by shanghaikid** [comment]
you can open the issue here:  https://github.com/zilliztech/attu

**Comment by haxung** [comment]
> you can open the issue here: https://github.com/zilliztech/attu

Thanks.
