### ISSUE TITLE
[Bug]: cannot find -latomic

### ISSUE THREAD

**Issue by BUPTAnderson** [milvus-io/milvus#27594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): v2.3.1
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 64cores/256GB
- GPU: 
- Others:
```

### Current Behavior

compile milvus(master) via make error.

### Expected Behavior

compile milvus successfully

### Steps To Reproduce

```markdown
cd milvus sorce files directory
exec `make`
```

### Milvus Log

[ 65%] Performing install step for 'jemalloc_ep'
make[4]: Entering directory `/opt/milvus/cmake_build/3rdparty_download/jemalloc-subbuild/src/jemalloc_ep'
make[4]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
/bin/install -c -m 755 bin/jemalloc-config /opt/milvus/internal/core/output/bin
/bin/install -c -m 755 bin/jemalloc.sh /opt/milvus/internal/core/output/bin
/bin/install -c -m 755 bin/jeprof /opt/milvus/internal/core/output/bin
/bin/install -c -m 644 include/jemalloc/jemalloc.h /opt/milvus/internal/core/output/include/jemalloc
/bin/install -c -m 755 lib/libjemalloc.a /opt/milvus/internal/core/output/lib
/bin/install -c -m 755 lib/libjemalloc_pic.a /opt/milvus/internal/core/output/lib
/bin/install -c -m 644 jemalloc.pc /opt/milvus/internal/core/output/lib/pkgconfig
Missing xsltproc.  doc/jemalloc.html not (re)built.
Missing xsltproc.  doc/jemalloc.3 not (re)built.
/bin/install -c -m 644 doc/jemalloc.html /opt/milvus/internal/core/output/share/doc/jemalloc
/bin/install -c -m 644 doc/jemalloc.3 /opt/milvus/internal/core/output/share/man/man3
make[4]: Leaving directory `/opt/milvus/cmake_build/3rdparty_download/jemalloc-subbuild/src/jemalloc_ep'
[ 65%] Completed 'jemalloc_ep'
make[3]: Leaving directory `/opt/milvus/cmake_build'
[ 65%] Built target jemalloc_ep
[ 66%] Linking CXX shared library ../../lib/libmilvus_common.so
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: cannot find -latomic
collect2: error: ld returned 1 exit status
make[3]: *** [lib/libmilvus_common.so] Error 1
make[3]: Leaving directory `/opt/milvus/cmake_build'
make[2]: *** [src/common/CMakeFiles/milvus_common.dir/all] Error 2
make[2]: Leaving directory `/opt/milvus/cmake_build'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/opt/milvus/cmake_build'
make: *** [build-cpp] Error 1

**Comment by yanliang567** [comment]
/assign @BUPTAnderson  @jiaoew1991 
@jiaoew1991  please help to confirm the issue and review the pr

/unassign
