### ISSUE TITLE
[Bug]: failed to get channels, collection not loaded: collection not found

### ISSUE THREAD

**Issue by Gy1900** [milvus-io/milvus#27596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.3
- Deployment mode(standalone or cluster): standalone 
- MQ type(rocksmq, pulsar or kafka):    default
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.5
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

可以新建collection，但是数据无法insert，在 attu上看 过去的collection也无法load。

![5](https://github.com/milvus-io/milvus/assets/27496549/ca470bee-ebfe-4a9b-9707-c33f49966fbd)

### Expected Behavior

正常load

### Steps To Reproduce

```markdown
国庆放假后发现 milvus load collection失败。起先以为是因为之前 更改了python的一些包，后来恢复后，还是有问题。
sdk：
[get_loading_progress] retry:9, cost: 60.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNAVAILABLE: ipv4::19530: Socket closed>

error: <MilvusUnavailableException: (code=1, message=server Unavailable: Retry run out of 10 retry times)>
info: Traceback (most recent call last):
  File "/app/xyjlllm/anaconda3/lib/python3.9/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/app/xyjlllm/anaconda3/lib/python3.9/site-packages/pymilvus/client/grpc_handler.py", line 758, in get_loading_progress
    response = self._stub.GetLoadingProgress.future(request, timeout=timeout).result()
  File "/app/xyjlllm/anaconda3/lib/python3.9/site-packages/grpc/_channel.py", line 797, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
     status = StatusCode.UNAVAILABLE
     details = "failed to connect to all addresses; last error: UNKNOWN: ipv4::19530: Failed to connect to remote host: FD Shutdown"
     debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4::19530: Failed to connect to remote host: FD Shutdown {grpc_status:14, created_time:"2023-10-09T22:26:47.970292568+08:00"}"
```

### Milvus Log

[milvus-compose.log](https://github.com/milvus-io/milvus/files/12854148/milvus-compose.log)

### Anything else?

attu日志
![3](https://github.com/milvus-io/milvus/assets/27496549/634505e9-80d3-43c7-abec-400e0aa98008)
![4](https://github.com/milvus-io/milvus/assets/27496549/1eaf2eca-4136-4536-8d47-b6d7956a29d1)
![1](https://github.com/milvus-io/milvus/assets/27496549/a51e781c-cf1f-4cd2-9b59-597050083853)
![2](https://github.com/milvus-io/milvus/assets/27496549/d879186d-c74f-4b21-b8bf-9701a1963fc6)

**Comment by yanliang567** [comment]
similar to  #27485

**Comment by Gy1900** [comment]
![6](https://github.com/milvus-io/milvus/assets/27496549/e32e126e-9a59-48fc-9e69-83f30d4c943a)
![7](https://github.com/milvus-io/milvus/assets/27496549/b3c9d0be-24db-4ce2-a044-af7526f67364)

**Comment by Gy1900** [comment]
> similar to #27485

yes, but in the standalone, i tried modify the retention param of rocktsmq, it doesn`t work

**Comment by Gy1900** [comment]
"ClientBase ReCall grpc second call get error"] [role=rootcoord] [address=] [error="err: rpc error: code = Unknown desc = expected=%!s(int64=22), actual=%!s(int64=23): server ID mismatch". 如何解决这个 mismatch？ @yanliang567 @weiliu1031

**Comment by Gy1900** [comment]
> 可以正常load了。我将所有的collection删除了，然后将docker里面的4个镜像全部重启，数据就可以正常insert + load了。但问题是：我的所有数据全部没有了。 我想请问下：
> 
> 1. 是否可以使用数据迁移，将所有的数据删除后再恢复？
> 2. 如果是消息中间件的问题，是否改为pulsar能解决？
> 3. 过往运行几个月都没有问题期间也重启过，但是为什么过了8天左右没有启动，就会发生这种问题？
>    ![9](https://user-images.githubusercontent.com/27496549/273833407-3a1b09d2-210a-4f9f-ac94-7354c993f0d8.png)
>    ![10](https://user-images.githubusercontent.com/27496549/273833420-53d7f4c2-3796-485c-b4cd-6d7081fde49f.png)

@yanliang567
