### ISSUE TITLE
[Bug]:milvus2.2.8滚动升级到 2.3.1版本报错

### ISSUE THREAD

**Issue by master006** [milvus-io/milvus#27591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

执行命令报错：
![image](https://github.com/milvus-io/milvus/assets/25217361/e070ca00-d2cc-4185-bb28-6a868c0d1395)

### Expected Behavior

配置：
![image](https://github.com/milvus-io/milvus/assets/25217361/4223336c-0650-4787-b649-4a82cb57f022)

执行命令报错：
![image](https://github.com/milvus-io/milvus/assets/25217361/e070ca00-d2cc-4185-bb28-6a868c0d1395)

**Comment by yanliang567** [comment]
@master006 did you upgrade the milvus-operator first?
/assign @master006

**Comment by master006** [comment]
how to upgrade milvus-operator



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月10日(周二) 中午12:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [milvus-io/milvus] [Bug]:milvus2.2.8滚动升级到 2.3.1版本报错 (Issue #27591)




 
@master006 did you upgrade the milvus-operator first?
 /assign @master006

**Comment by yanliang567** [comment]
please refer to readme in https://github.com/zilliztech/milvus-operator

**Comment by master006** [comment]
![image](https://github.com/milvus-io/milvus/assets/25217361/cf847d1b-31d9-4047-bc73-c0d24feab0a4)
![image](https://github.com/milvus-io/milvus/assets/25217361/a6821ce5-3725-4800-8701-fee77a68e545)

**Comment by master006** [comment]
create  milvus-operator namespace successful ,but excution  kubectl apply -f rollingUpgrade.yaml  erro.
![image](https://github.com/milvus-io/milvus/assets/25217361/0c20ed36-2e6f-44d8-a998-70b923d008a1)

**Comment by master006** [comment]
执行升级命令报错









F007
***@***.***





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "milvus-io/milvus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月11日(星期三) 上午10:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [milvus-io/milvus] [Bug]:milvus2.2.8滚动升级到 2.3.1版本报错 (Issue #27591)





 
please refer to readme in https://github.com/zilliztech/milvus-operator

**Comment by yanliang567** [comment]
/assign @haorenfsa 
please help to take a look at this issue
/unassign

**Comment by haorenfsa** [comment]
> helm repo add milvus-operator https://zilliztech.github.io/milvus-operator/
> helm repo update milvus-operator --create-namespace
> helm -n milvus-operator upgrade --install milvus-operator milvus-operator/milvus-operator
