### ISSUE TITLE
[Bug]: There are many search and query failure when sending requests concurrently

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#27605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20231008-a7151653-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/12268675/0fd50d12-4def-49c7-b610-920cd4a59c1c)

![image](https://github.com/milvus-io/milvus/assets/12268675/56dc8697-a4a6-40dc-bfbd-af21005ab7d8)

### Expected Behavior

no failure requests

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_cron/detail/deploy_test_cron/1443/pipeline

log:
[artifacts-pulsar-cluster-reinstall-1443-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/12854855/artifacts-pulsar-cluster-reinstall-1443-pytest-logs.tar.gz)
[artifacts-pulsar-cluster-reinstall-1443-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/12854858/artifacts-pulsar-cluster-reinstall-1443-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
This will block the reinstallation test. Because it failed at the first stage before reinstalling and making the test can not continue to the second stage.

**Comment by yanliang567** [comment]
@zhuwenxing shall we think of add the stage I into the CI testing?

**Comment by yanliang567** [comment]
/assign @weiliu1031 
please help to take a look
/unassign

**Comment by zhuwenxing** [comment]
Not reproduced in master-20231018-630636c4
