### ISSUE TITLE
[Bug]: datanode is periodic restart

### ISSUE THREAD

**Issue by gateray** [milvus-io/milvus#27620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.14
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):go-sdk
- OS(Ubuntu or CentOS):ubuntu 
- CPU/Memory:32core256G 
- GPU: no
- Others:
```

### Current Behavior

datanode is periodic restart，other milvus’s component with very large warn level log message

### Expected Behavior

datanode not restart and server log should only has a small warning messages

### Milvus Log

* datanode重启前日志：
[datanode日志-data-2023-10-10 23_54_20.csv](https://github.com/milvus-io/milvus/files/12859229/datanode.-data-2023-10-10.23_54_20.csv)
* datanode重启前其他组件日志：
[服务日志-data-2023-10-10 23_57_53.csv](https://github.com/milvus-io/milvus/files/12859235/-data-2023-10-10.23_57_53.csv)

### Anything else?

* collection schema is below:
![collection-schema](https://github.com/milvus-io/milvus/assets/8119875/c1496e94-82e9-4ba7-b84a-31c8540d2ca9)
* about 450 million data and 1k vector/s speed insert (include vector delete operate)
![insert rate](https://github.com/milvus-io/milvus/assets/8119875/96d63a15-f4b8-413c-b08c-81b7b1226612)

**Comment by yanliang567** [comment]
@gateray it seems that the datanode is OOM,  Could you please attach the etcd backup for investigation？ Check this: https://github.com/milvus-io/birdwatcher for details about how to backup etcd with birdwatcher. As a quick workaround, you could increase the cpu and memory for datanode or decrease the insert/delete throughput. 

/assign @gateray

**Comment by xiaofan-luan** [comment]
[2023/10/10 12:27:59.915 +00:00] [WARN] [indexnode/task.go:248] ["parse field meta from binlog failed"] [error="empty insert paths"]

**Comment by xiaofan-luan** [comment]
@gateray what operation did you do?
did you try to change any meta or filesystem path?

**Comment by xiaofan-luan** [comment]
I don't have a very long period of logs but seems that meta is already messed up

**Comment by gateray** [comment]
> @gateray it seems that the datanode is OOM, Could you please attach the etcd backup for investigation？ Check this: https://github.com/milvus-io/birdwatcher for details about how to backup etcd with birdwatcher. As a quick workaround, you could increase the cpu and memory for datanode or decrease the insert/delete throughput.
> 
> /assign @gateray

ok，i try to export etcd backup，but i see the container last exit code it not seem oom，current memory limit i think is large enough，as below：
```
Containers:
  datanode:
    Container ID:  docker://f299561e31bd871723115c2f6e5269551b2acdb7f88328ec4ab7a824bb84b995
    Image:         hub-mirror.wps.cn/sreopen/milvusdb-milvus:v2.2.14
    Image ID:      docker-pullable://hub-mirror.wps.cn/sreopen/milvusdb-milvus@sha256:099bd246ae15242eeb6e4ba9263b977eb9d92d069f28b3f51e1a4986cab0f90d
    Ports:         21124/TCP, 9091/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      /milvus/tools/run-helm.sh
      milvus
      run
      datanode
    State:          Running
      Started:      Wed, 11 Oct 2023 11:18:18 +0800
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Wed, 11 Oct 2023 11:00:48 +0800
      Finished:     Wed, 11 Oct 2023 11:18:17 +0800
    Ready:          True
    Restart Count:  11
    Limits:
      cpu:     16
      memory:  32Gi
    Requests:
      cpu:        4
      memory:     4Gi
    Liveness:     http-get http://:metrics/healthz delay=90s timeout=5s period=30s #success=1 #failure=5
    Readiness:    http-get http://:metrics/healthz delay=90s timeout=5s period=10s #success=1 #failure=5

**Comment by gateray** [comment]
> I don't have a very long period of logs but seems that meta is already messed up
it is 5min duration log around restart time point and exclude INFO log level，because full log is too large

**Comment by gateray** [comment]
> @gateray what operation did you do? did you try to change any meta or filesystem path?

no change，the storage is use kingsoft cloud ks3

**Comment by gateray** [comment]
> @gateray it seems that the datanode is OOM, Could you please attach the etcd backup for investigation？ Check this: https://github.com/milvus-io/birdwatcher for details about how to backup etcd with birdwatcher. As a quick workaround, you could increase the cpu and memory for datanode or decrease the insert/delete throughput.
> 
> /assign @gateray

* etcd backup：
[bw_etcd_ALL.231011-115015.bak.gz](https://github.com/milvus-io/milvus/files/12864654/bw_etcd_ALL.231011-115015.bak.gz)

**Comment by yanliang567** [comment]
@gateray it seems that you updated the maxSegmentSize to 2GB, and there are dismatched meta in the etcd backup file.
So if you have milvus metices, could you please attach the grafana srceenshots of datanode for us?

**Comment by gateray** [comment]
> @gateray it seems that you updated the maxSegmentSize to 2GB, and there are dismatched meta in the etcd backup file. So if you have milvus metices, could you please attach the grafana srceenshots of datanode for us?


![datanode1](https://github.com/milvus-io/milvus/assets/8119875/401fbcd4-a9d7-43bf-b903-d5a4e7688161)
![datanode2](https://github.com/milvus-io/milvus/assets/8119875/c8fb11b2-7100-4996-9df1-0f20d27eb0e0)

**Comment by yanliang567** [comment]
Mmm... the TT lag is empty. @congqixia  any ideas?
/assign @congqixia
