### ISSUE TITLE
[Bug]: no matches for kind "Milvus" in version "milvus.io/v1beta1"

### ISSUE THREAD

**Issue by gaoyuan5251** [milvus-io/milvus#27637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.1
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):   pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: k8s-1.23.0
```

### Current Behavior

https://milvus.io/docs/install_cluster-helm.md

### Steps To Reproduce

```markdown
1.https://github.com/zilliztech/milvus-operator/blob/main/config/samples/milvus_cluster_minimum.yaml

2.kubectl apply -f milvus_cluster_minimum.yaml 
error: unable to recognize "milvus_cluster_minimum.yaml": no matches for kind "Milvus" in version "milvus.io/v1beta1"
```

**Comment by yanliang567** [comment]
@gaoyuan5251 did you upgrade the milvus-operator to latest?
/assign @gaoyuan5251 
/unassign

**Comment by gaoyuan5251** [comment]
![image](https://github.com/milvus-io/milvus/assets/38758293/8c559415-9e34-4e55-a2d4-89a26eba3abc)
@yanliang567  here bro

**Comment by xiaofan-luan** [comment]
we will release the tool image for arm
