### ISSUE TITLE
[Bug]: Standby instances metrics aren't accessible through metrics port

### ISSUE THREAD

**Issue by punkerpunker** [milvus-io/milvus#27654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.1
- Deployment mode(standalone or cluster): Cluster
- MQ type(rocksmq, pulsar or kafka): Pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): v2.0.0rc2
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: -
- GPU: -
- Others: -
```

### Current Behavior

When coordinators are deployed in active/standby HA mode, suggested `ServiceMonitor` expecting metrics to be accessible from both active and standby node, but apparently standby node is not returning any. That results in a `TargetDown` alerts. 

### Expected Behavior

I wonder myself what's the expected behaviour here. Thinking of the fact that the pod is running - I guess it supposed to send some meaningful metrics even though it's in standby mode. (I don't have strong opinions, up to discussion).

**Comment by yanliang567** [comment]
/assign @wayblink 
any comments?
/unassign

**Comment by wayblink** [comment]
@punkerpunker Nice catch. Yes, currently standby coordinator skip return metrics. I think it it a reasonable need. I will try fix it. cc @yanliang567
