### ISSUE TITLE
[Bug]: The load average of the machine CPU soared particularly high. When uploading files to the cluster minio,

### ISSUE THREAD

**Issue by Cactus-L** [milvus-io/milvus#27659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 32C/128G
- GPU: 
- Others:
```

### Current Behavior

When I upload a file to the cluster minio, the load average of the machine's CPU soars extremely high, and then the overall response times out, causing the file upload to fail.

Operation command：mc cp --recursive ./datadir xxx/xxx/backup/

error log:
mc: <ERROR> Failed to copy `/home/work/minio/m1011p3/binlogs/insert_log/443118090920072955/443118090920072956/443118090920073153/102/443118090920073159`. Put "http://x.x.x.x:9000/search-hbb/backup/m1011p3/binlogs/insert_log/443118090920072955/443118090920072956/443118090920073153/102/443118090920073159": read tcp x.x.x.x:55264->x.x.x.x:9000: read: connection reset by peer

**Comment by yanliang567** [comment]
It sounds like a minio issue? and may i ask why do you upload files to minio cluster manually, because Milvus could not read the files that manually uploaded.
/assign @Cactus-L 
/unassign

**Comment by Cactus-L** [comment]
> It sounds like a minio issue? and may i ask why do you upload files to minio cluster manually, because Milvus could not read the files that manually uploaded. /assign @Cactus-L /unassign

I need to perform cross-cluster data migration
