### ISSUE TITLE
Abnormal query performance

### ISSUE THREAD

**Issue by Bennu-Li** [milvus-io/milvus#2767]
**Describe the bug**
milvus0.10.0
vector num: one billion
vector dim: 64
index_file_size: 2048
nlist: 16384
index: sq8h

When nprobe>1024, query performance is better than nprobe <= 1024.

nprobe = 1040:
nq | topk | time
-- | -- | --
1 | 1 | 0.068
1 | 50 | 0.066
50 | 1 | 0.067
50 | 50 | 0.068
100 | 1 | 0.068
100 | 50 | 0.066

When nprobe>1024, query performance is similar to nprobe=1025

nprobe = 64:
nq | topk | time
-- | -- | --
1 | 1 | 0.25
1 | 50 | 0.27
50 | 1 | 0.81
50 | 50 | 1.12
100 | 1 | 1.14
100 | 50 | 1.72

nprobe = 1024:
nq | topk | time
-- | -- | --
1 | 1 | 0.44
1 | 50 | 0.50
50 | 1 | 9.75
50 | 50 | 10.27
100 | 1 | 18.91
100 | 50 | 18.72

**Comment by op-hunter** [comment]
According to the document: https://github.com/facebookresearch/faiss/wiki/Faiss-on-the-GPU .
FAISS has a limitations of topk and nprobe on GPU version.
Milvus doesn't get the right limitation value, this is a bug and I will fix it as soon as possible.

**Comment by shengjun1985** [comment]
There are 3 bugs in the issue.
(1) 'nprobe' limitation on GPU version is never mentioned in the DOC.
It will be added in the next version.
(2) 'nprobe' limitation is wrong.
It is fixed.
(3) Exception catched in XSearchTask::Execute() is never notified to the SDK client.
@scsven Please help to confirm.

**Comment by cqy123456** [comment]
> (3) Exception catched in XSearchTask::Execute() is never notified to the SDK client.

Done,
