### ISSUE TITLE
[Bug]: Connection error when deployed to GKE

### ISSUE THREAD

**Issue by iameminmammadov** [milvus-io/milvus#27684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.1
- Deployment mode(standalone or cluster): GKE cluster
- MQ type(rocksmq, pulsar or kafka): Pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.3.1
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 4 CPU (deployed on e2-highmem-4)
- GPU: 0
- Others:
```

### Current Behavior

I followed this documentation to deploy Milvus on GKE: https://milvus.io/docs/gcp.md. 

Installed the following pip packages:
`pymilvus==2.3.1; grpcio-tools==1.58.0; protobuf==4.24.4`

Got external-ip address as shown in the link above.

When I run the following command from my local PC:
```
from pymilvus import connections
connections.connect(
                    alias="default",
                    host="AA.XXX.YY.ZZZ",
                    secure=True,
                    port='19530')

```
I get:
`pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on `

### Expected Behavior

Expected to connect to the cluster

### Milvus Log

[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/12887971/milvus-log.tar.gz)

### Anything else?

GKE would produce an error with the version `1.20.8-gke.900`, and thus, I am using `1.27.3-gke.100`.

I have also noticed in the Workload that quite a lot of pods are pending or produce an error.

![Screenshot from 2023-10-12 21-15-50](https://github.com/milvus-io/milvus/assets/24482886/ba64c92a-e1ae-484d-b2f2-9e3b58932d92)

**Comment by yanliang567** [comment]
@iameminmammadov You can not connect to milvus before the milvus dependent services(etcd and pulsar) are not ready.  Please describe the related pod to check the errors.
/assign @iameminmammadov 
/unassign

**Comment by iameminmammadov** [comment]
Hey @yanliang567 . Thanks. I have followed the documentation to the core and yet, I cannot get the pods running. Is there an updated version for GCP?

I will def. explore the source of the errors and get back to you on that.

**Comment by 17nshul** [comment]
> Hey @yanliang567 . Thanks. I have followed the documentation to the core and yet, I cannot get the pods running. Is there an updated version for GCP?

hey were you able to run the pods, i am facing same issue.

**Comment by xiaofan-luan** [comment]
you probably need to expose 19530 port to the outside of the cluster

**Comment by iameminmammadov** [comment]
> > Hey @yanliang567 . Thanks. I have followed the documentation to the core and yet, I cannot get the pods running. Is there an updated version for GCP?
> 
> hey were you able to run the pods, i am facing same issue.

Yup. Try to change the region in GCP. My problem was lack of resources in that particular zone. Go with region, instead of zone. If EU won't work, try in US.
