### ISSUE TITLE
[Bug]: The return field IDs of the delete interface in milvus:2.3.2 is empty, causing an error in the java-sdk delete interface.

### ISSUE THREAD

**Issue by yongpengli-z** [milvus-io/milvus#27701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.3.2
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):java-sdk 2.3.1
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

HighLevel APi-- delete error:No found insertIds, please check your requests
milvus2.3.2:
![img_v2_500d522d-fd67-44c6-a67c-d1efd655c6dg](https://github.com/milvus-io/milvus/assets/103410837/c92465cc-8685-4985-998a-9638117704db)
milvus2.3.1:
![img_v2_8ac3e51c-49ab-4557-a7e3-022ba3de9adg](https://github.com/milvus-io/milvus/assets/103410837/3abe2e7c-a9dd-468c-a737-9dc0522eb523)

**Comment by xiaofan-luan** [comment]
/assign @aoiasd 
please help on it

**Comment by aoiasd** [comment]
we need discuss if we still need return pk of delete entity. Because now we could delete range, if we return deleted pk, it may over the rpc limit. If we should add a new field to delete request as return limit?

**Comment by aoiasd** [comment]
In fact, now go and python sdk even not return this field to user though delete rpc return result with this deleted pks.

**Comment by xiaofan-luan** [comment]
@aoiasd 
we should return ids of deleted entities is posible
