### ISSUE TITLE
[Bug]: The RPS of Range search is 10X slower than search with the same amount entities returned

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#27705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20231008-a7151653
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):   pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2):  pymilvus latest
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The RPS of Range search is 10X slower than search with the same amount entities returned

![U9b2Ec1Jty](https://github.com/milvus-io/milvus/assets/83755740/e1f3a54b-71f0-49fb-9a66-0bf9cc753cbc)

### Expected Behavior

The RPS of Range search could be faster, and not much slower than search 

### Steps To Reproduce

```markdown
create IVF_FLAT index, nlist=1000
1. search with limit=1000 [95.2% recall,  gist 768, L2, 'nlist': 1000, range_filter: 1.4503270387649536, radius: 1.452926516532898, nq = 1, limit = 1000, but actual return 952 entities which meet the radius range]
2. range search with distance range which includes 1000 entities
```

### Milvus Log

https://grafana-4am.zilliz.cc/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcluster%3D%5C%224am%5C%22,namespace%3D%5C%22qa-milvus%5C%22,pod%3D~%5C%22range-1011-wqzor.*%5C%22%7D%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D

**Comment by cydrain** [comment]
it does not make sense to compare the QPS of search and range search in this way:

**Comment by binbinlv** [comment]
From the debug log using the debug image, range search using the above configuration searched about 260 buckets: (different segments searched different number buckets)
![ql1AsIduiD](https://github.com/milvus-io/milvus/assets/83755740/f5a03e2b-87f8-4059-807e-c8bdb7486326)

Then the QPS of range search in this issue is 10X slower than search (nprobe=16), so it is as expected.

**Comment by binbinlv** [comment]
Setting the search nprobe as 260, then the RPS of range search(the configuration in this issue) and search is similar:
![7J3ypxu4H8](https://github.com/milvus-io/milvus/assets/83755740/401a1565-ecb0-4411-a3a1-52fbed223622)

**Comment by binbinlv** [comment]
So the above test resluts behave as design, right? @cydrain

**Comment by cydrain** [comment]
> So the above test resluts behave as design, right? @cydrain

Yes, in current IVF range search strategy, this performance is as expected.

**Comment by binbinlv** [comment]
> > So the above test resluts behave as design, right? @cydrain
> 
> Yes, in current IVF range search strategy, this performance is as expected.

OK, close it.

**Comment by xiaofan-luan** [comment]
is there a reason we want to test that much bucket?
What happens if reduce the bucket into half?

**Comment by cydrain** [comment]
> is there a reason we want to test that much bucket? What happens if reduce the bucket into half?

Current IVF range search strategy is: iterate all buckets from close to far, stop till we find no valid vector in one bucket.
We cannot control how many buckets to search except we change this strategy.

**Comment by xiaofan-luan** [comment]
> > is there a reason we want to test that much bucket? What happens if reduce the bucket into half?
> 
> Current IVF range search strategy is: iterate all buckets from close to far, stop till we find no valid vector in one bucket. We cannot control how many buckets to search except we change this strategy.

Should there be config we set how many result as a limit?

If we can sacrifice recall for preformance, that might be help

**Comment by cydrain** [comment]
> > > is there a reason we want to test that much bucket? What happens if reduce the bucket into half?
> > 
> > 
> > Current IVF range search strategy is: iterate all buckets from close to far, stop till we find no valid vector in one bucket. We cannot control how many buckets to search except we change this strategy.
> 
> Should there be config we set how many result as a limit?
> 
> If we can sacrifice recall for preformance, that might be help

currently thirdparty only accepts "radius" for range search,

**Comment by xiaofan-luan** [comment]
> > > > is there a reason we want to test that much bucket? What happens if reduce the bucket into half?
> > > 
> > > 
> > > Current IVF range search strategy is: iterate all buckets from close to far, stop till we find no valid vector in one bucket. We cannot control how many buckets to search except we change this strategy.
> > 
> > 
> > Should there be config we set how many result as a limit?
> > If we can sacrifice recall for preformance, that might be help
> 
> currently thirdparty only accepts "radius" for range search, it may help if we can let thirdparty accept both "radius" and "range_filter".

We can add a search_param to tune recall/perf?
