### ISSUE TITLE
[Enhancement]: Support million level segments

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#27710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

On a  4c 16g cluster
1. Support at least 1K collections
2. Support more than 100K segments

On a  32c 128g cluster or more
1. Support at least 10K collections
3. Support more than 1m segments

This is for the multitenant requirement. Althogh milvus support partition key, there are still some requirement to support more  collections and partitions.

### Why is this needed?

In this project, we will figure out what could be the bottle neck to support more collections, and fix these limitations.

**Comment by yanliang567** [comment]
/assign @ThreadDao 
please help an eye on it

**Comment by XuanYang-cn** [comment]
Might need extra attention on L0 Compaction, which will load all segments's bf of a partition.
@xiaofan-luan 1m segments for 10k collection, Could it be 1M segments for 1 collection or just 100 segments for 1 collection in avg.

**Comment by xiaofan-luan** [comment]
> Might need extra attention on L0 Compaction, which will load all segments's bf of a partition. @xiaofan-luan 1m segments for 10k collection, Could it be 1M segments for 1 collection or just 100 segments for 1 collection in avg.

I think the exist implementation is to cache all BF into datanode/lognode? 

and when compaction happened, we check PK oracle in batch to datnaode logndoe

**Comment by xiaofan-luan** [comment]
@yanliang567 
how is current test going on?

**Comment by xiaofan-luan** [comment]
let's keep this.

The current goal is 
100collection *. 4096 partitions

**Comment by xiaofan-luan** [comment]
this could be done on a distributed cluster with 4c16g coordinator + 4 * 64g querynode

**Comment by yanliang567** [comment]
keep it
