### ISSUE TITLE
[Bug]: Milvus Roles and Privileges not working in partition granularity

### ISSUE THREAD

**Issue by sahusasank** [milvus-io/milvus#27731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 4.0.31
- Deployment mode(standalone or cluster): Cluster
- MQ type(rocksmq, pulsar or kafka):  kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

i build a milvus cluster in my OpenShift Kubernetes cluster.

I followed the below steps,

A) Deployed the milvus cluster with attached values file.

helm upgrade --install milvus -f my-release-milvus-4.0.31.yaml milvus/milvus --version 4.0.31 --debug

B) After that logged in to ATTU console and created a test user (sasanka) with testrole having access for collection serach in Sasanka partition (not allowing default). However, this user can do anything in the default partition, as we experience.
[my-release-milvus-4.0.31.txt](https://github.com/milvus-io/milvus/files/12915741/my-release-milvus-4.0.31.txt)

**Comment by xiaofan-luan** [comment]
you have to make sure
common.security.authorizationEnabled is set to true

**Comment by yanliang567** [comment]
@sahusasank for now, Milvus only supports the privileges in collection granularity, instead of partition granularity. please refer to https://milvus.io/docs/users_and_roles.md

/assign @sahusasank 
/unassign
