### ISSUE TITLE
[Bug]:  milvus 升级失败 Milvus upgrade failed

### ISSUE THREAD

**Issue by master006** [milvus-io/milvus#27737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I originally wanted to upgrade Milvus, but found out that I needed to install Milvus operator. I installed it based on this article
https://github.com/zilliztech/milvus-operator#install--upgrade-milvus-operator-of-a-specific-version

By executing commands
kubectl apply -f https://raw.githubusercontent.com/zilliztech/milvus-operator/v0.8.2/deploy/manifests/deployment.yaml
As a result, this situation occurred. The Milvus operator image could not be downloaded, and the pod reported an error. Please take a look at which link went wrong and provide me with a Milvus operator upgrade plan. The main purpose is to upgrade Milvus. If there is a better plan for upgrading Milvus, please advise me. Thank you.
![5fb3d969f44e2a0a3ab0072f0c33552](https://github.com/milvus-io/milvus/assets/25217361/bc1b6733-e83e-45a4-931d-d82b45e9b842)
![7b01ccf2e365a3baea1ace3a9ef2410](https://github.com/milvus-io/milvus/assets/25217361/88dde9b4-7cb5-4956-affa-9b0412d9f14d)

**Comment by yanliang567** [comment]
@master006 quick questions:
1. what is the source and target milvus versions you want to deal with？
2. how did you initially deploy milvus? I mean if you installed it with helm then you should upgrade it with helm, and if you installed it with milvus-operator then you should upgrade it with operator.

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version:
> - Deployment mode(standalone or cluster):
> - MQ type(rocksmq, pulsar or kafka):    
> - SDK version(e.g. pymilvus v2.0.0rc2):
> - OS(Ubuntu or CentOS): 
> - CPU/Memory: 
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> I originally wanted to upgrade Milvus, but found out that I needed to install Milvus operator. I installed it based on this article https://github.com/zilliztech/milvus-operator#install--upgrade-milvus-operator-of-a-specific-version
> 
> By executing commands kubectl apply -f https://raw.githubusercontent.com/zilliztech/milvus-operator/v0.8.2/deploy/manifests/deployment.yaml As a result, this situation occurred. The Milvus operator image could not be downloaded, and the pod reported an error. Please take a look at which link went wrong and provide me with a Milvus operator upgrade plan. The main purpose is to upgrade Milvus. If there is a better plan for upgrading Milvus, please advise me. Thank you. ![5fb3d969f44e2a0a3ab0072f0c33552](https://user-images.githubusercontent.com/25217361/275565273-bc1b6733-e83e-45a4-931d-d82b45e9b842.png) ![7b01ccf2e365a3baea1ace3a9ef2410](https://user-images.githubusercontent.com/25217361/275565302-88dde9b4-7cb5-4956-affa-9b0412d9f14d.png)
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

seems that you are trying to upgrade milvus operator on milvus repo.
The operator has been moved to zilliz tech, please be aware

**Comment by master006** [comment]
i am milvus 2.2.8 upgrading 2.3.1. The installation of milvus operator was successful, and an error was reported when executing the upgrade command
![image](https://github.com/milvus-io/milvus/assets/25217361/470b2956-3f37-4bac-af2a-38a45c07ec7a)

![企业微信截图_16975115125544](https://github.com/milvus-io/milvus/assets/25217361/f8f46bee-6791-45fa-832c-09c5c968d503)

**Comment by yanliang567** [comment]
/assign @haorenfsa 
could u please take a look?

/unassign

**Comment by haorenfsa** [comment]
set `enableRollingUpdate` to `false`.  The reason is stated in the error msg, `enableRollingupdate is not supported for msgStream rocksmq`

**Comment by master006** [comment]
I have made changes to the execution without any errors, but Milvus has not been upgraded.
![企业微信截图_16975374432316](https://github.com/milvus-io/milvus/assets/25217361/60a443b1-68e7-4017-8bca-fabdb418cdd5)
![企业微信截图_16975374161321](https://github.com/milvus-io/milvus/assets/25217361/4cc13d87-10cd-40a3-8f0c-0e87246527a0)

**Comment by haorenfsa** [comment]
According to your snapshots, you're in fact changing a milvus from mode cluster to mode standalone, which is not supported.
If you want to upgrade your cluster only, you need to set all fields same as they were when you creating it. Or when updating , use `kubectl patch` rather than `kubectl apply`
