### ISSUE TITLE
关于search方法的范围搜索文档此处注释是否有误？

### ISSUE THREAD

**Issue by lmdegit** [milvus-io/milvus#27743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
v2.3.x 文档，  链接https://milvus.io/docs/within_range.md
```

### Current Behavior

L2 距离的范围搜索文档，原文如下，其中的注释 smaller（已加粗）应该改为 greater 吧 ：
search_params = {
     # use `L2` as the metric to calculate the distance
    "metric_type": "L2",
    "params": {
        # search for vectors with a distance smaller than 10.0
        "radius": 10.0,
        # filter out vectors with a distance **smaller** than or equal to 5.0
        "range_filter" : 5.0
    }
}

**Comment by yanliang567** [comment]
nice catch.
@AnthonyTsu1984 could you please update the doc accordingly.

/assign @AnthonyTsu1984 
/unassign
