### ISSUE TITLE
[Bug]: stream operation failed: Timestamp lag too large lag

### ISSUE THREAD

**Issue by zhangxt2016** [milvus-io/milvus#27762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

fail to search on all shard leaders, err=All attempts results: attempt #1:code: UnexpectedError, error: fail to Search, QueryNode ID=135, reason=stream operation failed: Timestamp lag too large lag(125h35m52.058s) max(24h0m0s) attempt #2:context canceled

**Comment by congqixia** [comment]
@zhangxt2016 from the error message, the channel checkpoint is way behind current time. It looks like the datanode cannot update the checkpoint correctly.
Can your instance recover after restart? If the problem persist, could you please provide the log and birdwatcher backup? https://github.com/milvus-io/birdwatcher
