### ISSUE TITLE
[Bug]: milvus 2.3.1 GPU集群

### ISSUE THREAD

**Issue by ReganWz** [milvus-io/milvus#27779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

milvus 2.3.1 GPU集群版本什么时候支持A10

**Comment by liliu-z** [comment]
Will support in Milvus 2.3.2
Knowhere PR: https://github.com/zilliztech/knowhere/pull/66

**Comment by Yherealtita** [comment]
Okay
