### ISSUE TITLE
[Bug]: milvus 2.3.1 gpu 配置多卡

### ISSUE THREAD

**Issue by ReganWz** [milvus-io/milvus#27778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

milvus 2.3.1 gpu 配置多卡

![企业微信截图_16976362646324](https://github.com/milvus-io/milvus/assets/110969686/440dbab1-d5cd-4e0f-9979-6eb1b80746ef)

检索和插入过程中只出现一张卡可以使用，其他两张未使用

**Comment by yanliang567** [comment]
this is by design in v2.3.1, which will be enhanced to support multiple GPU in v2.3.2.
