### ISSUE TITLE
[Bug]: Session try to connect to etcd

### ISSUE THREAD

**Issue by gaoyuan5251** [milvus-io/milvus#27796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.1
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS):  CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

按照https://milvus.io/docs/install_standalone-helm.md  文档
helm 部署安装milvus单节点

### Steps To Reproduce

```markdown
1. 按文档部署(k8s单独部署的)
2. kubectl get pods
NAME                                            READY   STATUS    RESTARTS      AGE
my-release-etcd-0                               1/1     Running   0             37m
my-release-milvus-standalone-8466884d68-5fkb7   0/1     Running   9 (62s ago)   37m
my-release-minio-cbf6bf666-55lzt                1/1     Running   0             37m
发现没有启动成功。
3. 查看日志：kubectl logs my-release-milvus-standalone-8466884d68-5fkb7 > my-release-standalone-log.txt
```

### Milvus Log

[my-release-standalone-log.txt](https://github.com/milvus-io/milvus/files/13038961/my-release-standalone-log.txt)
[my-release-etcd-0.txt](https://github.com/milvus-io/milvus/files/13039086/my-release-etcd-0.txt)

**Comment by jiaoew1991** [comment]
@gaoyuan5251  From the logs, it seems that there is a network issue. Can you provide your Helm configuration?

**Comment by jiaoew1991** [comment]
/assign @LoveEachDay 

please help to check the helm config

**Comment by gaoyuan5251** [comment]
> @gaoyuan5251 From the logs, it seems that there is a network issue. Can you provide your Helm configuration?

Helm configuration? how to do?

**Comment by gaoyuan5251** [comment]
> @gaoyuan5251 From the logs, it seems that there is a network issue. Can you provide your Helm configuration?

Helm configuration? how to do, bro? @LoveEachDay @jiaoew1991

**Comment by chanhchuachin** [comment]
I also encountered the same problem :(

**Comment by LoveEachDay** [comment]
@gaoyuan5251 @chanhchuachin Could you check the `etcd service` whether it has active endpoints to connect? Milvus connect to etcd via kubernetes service. By default `kube-proxy` control pod to access service. Check your kube-proxy pod

From the attached etcd log, the etcd pod started normally.

**Comment by RGEsteves** [comment]
Same problem here. Someone solved ?

**Comment by xiaofan-luan** [comment]
> Same problem here. Someone solved ?

1. make sure you are using ssd for your etcd
2. make sure you upgrade to 2.3.21 or 2.4.10. We did some optimize so cgo thread will not block etcd session renew
