### ISSUE TITLE
[Bug]: <MilvusException: (code=1, message=proxy not healthy)>

### ISSUE THREAD

**Issue by yiwalk23li** [milvus-io/milvus#27799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.8
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Error when I try to debug it using gdb:
![image](https://github.com/milvus-io/milvus/assets/148437483/caaa4092-8d36-457a-8efe-afc70532b89b)
All python codes can couse this program.

**Comment by yanliang567** [comment]
the error msg indicates that milvus service is not ready for servicing.  could you please try to connect to milvus without gdb? also using a latest milvus release v2.3.1 is recommended. 
/assign @yiwalk23li 
/unassign

**Comment by yanliang567** [comment]
/assign @jiaoew1991 
@jiaoew1991 is this the same issue you just fixed a few days ago?
/unassign

**Comment by jiaoew1991** [comment]
@yiwalk23li Are you using gdb to debug the client written in pymlivus? Or are you using gdb to debug the milvus server?

**Comment by yiwalk23li** [comment]
I'm using gdb to debug the milvus server@jiaoew1991

**Comment by jiaoew1991** [comment]
Have you added a lot of breakpoints to Milvus? If so, it may cause the lease between Milvus and etcd to expire, resulting in a "not healthy" situation when accessing Milvus using the SDK.

**Comment by yiwalk23li** [comment]
I tried not to set any breakpoints before, but this error still occurred at that time. I tried again today, although I don't know why, it worked fine this time. thank you
