### ISSUE TITLE
[Bug]: High CPU Utilization of the VM where the Milvus is hosted as Standalone docker container when users count increases

### ISSUE THREAD

**Issue by IndhumathiParamasivam** [milvus-io/milvus#27795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.6
- Deployment mode(standalone or cluster): Standalone
- MQ type(rocksmq, pulsar or kafka):  rocksmq  
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 32vcpus 128 GiB RAM (Azure VM)
```

### Current Behavior

Earlier we have hosted the standalone Milvus in VM with 16vcpus and 64 GiB RAM. When we did a restart of the milvus container, the CPU utilization percentage of the VM increased to 94%-95% and it stayed there constantly and never came down, which in turn caused the DB calls to Milvus to failure. So, we resized the VM to 32vcpus and 128 GiB RAM. This made the CPU utilization came down to 50% and DB calls to milvus responded as expected. 
After 10 days, again we did a restart and the CPU Utilization of the VM spiked to 80 % and it still increasing. The DB calls starts to fail now. We could see the below error for the DB calls from the standalone Milvus container.

<MilvusException: (code=1, message=collection:user_***** or partition:[] not loaded into memory when search)>\",\"code\":5003}", "MYD_traceback": "Traceback (most recent call last):\n      logObj[\"MYD_answer\"] = ['response']\nKeyError: 'response'\n", "MYD_end_time": 1697690086, "MYD_time_taken": 12, "data_dt": "20231019"}

 Being in Production, we left out with no other option than increasing hardware cpus to 96 or 112 on coming days but we are not sure if we are gonna face the issue once again with this hardware requirements.

 Is there any alternate way to handle the issue instead of going for resizing the VMs, so that we do not end up in going for more resources than the threshold limit that we have (i.e vcpus 112)

### Expected Behavior

CPU Utilization requires to be below 50 % and responses the DB calls as expected without any exceptions.

### Milvus Log

[2023/10/19 04:41:25.155 +00:00] [WARN] [server/rocksmq_impl.go:628] ["rocksmq produce too slowly"] [topic=by-dev-rootcoord-delta_11] ["get lock elapse"=213] ["alloc elapse"=0] ["write elapse"=0] ["updatePage elapse"=0] ["produce total elapse"=213]

**Comment by karthikmsc05** [comment]
[milvus-standalone.log](https://github.com/milvus-io/milvus/files/13223685/milvus-standalone.log)
Team,
PFA the log files as requested. This is the warning messages we are able to see on the logs when the cluster response is too slow or no response. Could you please check this and let us know a solution to bring down that consistent CPU growth % to stay lower ?

**Comment by karthikmsc05** [comment]
> @IndhumathiParamasivam quick questions:
> 
> 1. are there any other services/applications running on the same VM with milvus?
         - No Its an independent VM where we are running milvus alone.
> 2. did the business requests increase or data entities increase during that 10 days?
          - The data growth is in a nominal level like as usual and we didn't see any noticeable spike on those days.
> 3. I suggest you upgrade to latest milvus release, such as v2.3.1. Milvus 2.2.6 is quite old, and we have fixed a lot of issues.
         - Being production we are nervous to do a version upgrade as we  don't have a chance to run into any situation where we are struck and not able to bring up the instance, data loss etc kind of issues. Do you still suggest this is safe and reliable option ? Could you also provide the best practices/steps/precautions to be followed while or before running an upgrade which can avoid us getting into unexpected issues and problems ? 
> 4. please attach the milvus full logs for us to address the issue.  please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
    -  Attached on the below comment FYR.
    
>    For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.
> 
> /assign @yanliang567  /unassign

**Comment by yanliang567** [comment]
one more question, how may collections and partitions do you have?

**Comment by IndhumathiParamasivam** [comment]
@yanliang567 , approximately 5k collections would be there

**Comment by IndhumathiParamasivam** [comment]
@yanliang567 ,
Any update on the issue?

**Comment by yanliang567** [comment]
this could be a known issue which reproduces when there are thousands of collections. We are working on an enhancement  #27710 to improve on this.
