### ISSUE TITLE
[Bug]: Proxy keep restart after etcd pod kill chaos

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#27818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20231018-2b13078b
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): kafka   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/12268675/8ceccf86-974c-435a-a99d-4136e7634b1d)

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-cron/detail/chaos-test-kafka-cron/8330/pipeline

log:
[artifacts-etcd-pod-kill-8330-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/13049676/artifacts-etcd-pod-kill-8330-pytest-logs.tar.gz)

[artifacts-etcd-pod-kill-8330-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/13049677/artifacts-etcd-pod-kill-8330-server-logs.1.tar.gz)

**Comment by zhuwenxing** [comment]
It reproduced again
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-cron/detail/chaos-test-kafka-cron/8443/pipeline

log:
[artifacts-etcd-pod-kill-8443-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/13068776/artifacts-etcd-pod-kill-8443-pytest-logs.tar.gz)
[artifacts-etcd-pod-kill-8443-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/13068778/artifacts-etcd-pod-kill-8443-server-logs.tar.gz)

![image](https://github.com/milvus-io/milvus/assets/12268675/0c5ab5f6-5283-4287-ade3-413b92ab305a)

**Comment by czs007** [comment]
working on it

**Comment by zhuwenxing** [comment]
not reproduced in 2.3-20231205-3d7bcb5e-amd64
