### ISSUE TITLE
[Bug]: librdkafka has wrong dynamic library link

### ISSUE THREAD

**Issue by BUPTAnderson** [milvus-io/milvus#27811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.0
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): kafka
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.3.1
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

librdkafka.so does not link to cyrus-sasl and cyrus-sasl-gssapi, so the milvus can not access to kafka cluster which open kerberos.

### Expected Behavior

librdkafka.so  link to cyrus-sasl and cyrus-sasl-gssapi, like below:
![截屏2023-10-19 20 50 44](https://github.com/milvus-io/milvus/assets/13449703/d7ba8d0f-d5d4-47fb-89f6-3726f0238319)

### Steps To Reproduce

```markdown
build the milvus source and exec ldd lib64/librdkafka.so
```

### Milvus Log

![截屏2023-10-19 20 57 08](https://github.com/milvus-io/milvus/assets/13449703/71e8d8c1-ea86-41ee-814d-5a1fdcb46fd0)

### Anything else?

What confuses me is that librdkafka++.so  can link to cyrus-sasl and cyrus-sasl-gssapi successfully.
![截屏2023-10-19 21 00 48](https://github.com/milvus-io/milvus/assets/13449703/07d2efe8-1593-4817-94b3-4e4aaa40cede)

**Comment by BUPTAnderson** [comment]
@jiaoew1991 Any suggestion ？

**Comment by jiaoew1991** [comment]
> @jiaoew1991 Any suggestion ？

Sorry, I did not get your problem. And I cannot find the problem through the screenshots.

**Comment by BUPTAnderson** [comment]
> > @jiaoew1991 Any suggestion ？
> 
> Sorry, I did not get your problem. And I cannot find the problem through the screenshots.

Milvus use its own `librdkafka.so` library to access Kafka cluster, but it does not link to `cyrus-sasl-gssapi`. This causes milvus to report errors when accessing kafka clusters with `kerberos` authentication.

`%2|1697710689.602|LIBSASL|rdkafka#producer-1| [thrd:sasl_plaintext://hadoop2038.rz.momo.com:9092/bootstrap]: sasl_plaintext://hadoop2038.rz.momo.com:9092/bootstrap: Cyrus/libsasl2 is missing a GSSAPI module: make sure the libsasl2-modules-gssapi-mit or cyrus-sasl-gssapi packages are installed`
(cyrus-sasl-gssapi  has installed, it seems that $miluvs_home/lib64/librdkafka.so lack of dynamic links)

When I installed the `librdkafka-devel` independently(CentOS: `yum install -y librdkafka-deve`, Ubuntu: `apt-get install -y librdkafka-dev`), `librdkafka.so` will alse be installed on the machine(in CentOS, the path is `/usr/lib64/librdkafka.so`), `/usr/lib64/librdkafka.so` links to dynamic libraries related to sasl/gssapi(cyrus-sasl-gssapi)。

**Comment by xiaofan-luan** [comment]
> Any progress so far?

We support SSL for kafka, is there anything special for kerberos cluster?

**Comment by BUPTAnderson** [comment]
> We support SSL for kafka, is there anything special for kerberos cluster?

When we compile and install librdkafka, it automatically compiles kerberos related dependencies into the target library. So we need to install the kerberos libraries beforehand.

## step 1 install kerberos related dependencies
> for Ubuntu
```shell
apt-get install -y libsasl2-dev
apt-get install -y libsasl2-modules
# Cyrus/libsasl2 is missing a GSSAPI module: make sure the libsasl2-modules-gssapi-mit or cyrus-sasl-gssapi packages are installed
apt-get install -y libsasl2-modules-gssapi-mit
# Optionally for kafka open zstd/zlib
# "zstd" (ZStandard) is not supported as a compression type,
apt-get install -y libzstd-dev
# zlib
apt install zlib1g-dev
``` 
> for CentOS
```shell
yum install cyrus-sasl cyrus-sasl-devel
# Cyrus/libsasl2 is missing a GSSAPI module: make sure the libsasl2-modules-gssapi-mit or cyrus-sasl-gssapi packages are installed
yum install cyrus-sasl-gssapi
# Optionally for kafka open zstd/zlib
yum install -y libzstd-devel zlib-devel
``` 

## step 2 install librdkafka
> for Ubuntu
```shell
# I haven't verified that the version is correct
apt-get install -y librdkafka-dev
```
> for CentOS
```shell
# It is highly recommended to specify the librdkafka version, 
# if you use yum install librdkafka-devel, a lower version maybe installed
yum install -y librdkafka-devel-1.9.0-1.cflt.el7.x86_64
```
## step 2 question
Milvus use conan to install librdkafka, It looks like the `librdkafka` installed via `conan` don't link to the `kerberos` related dynamic libraries.

## step 3 milvus support kerberos
we nedd modify `service_param.go` and `kafka_client.go` to support `Kerberos`
service_param.go
```go
type KafkaConfig struct {
	Address                 ParamItem  `refreshable:"false"`
	SaslUsername            ParamItem  `refreshable:"false"`
	SaslPassword            ParamItem  `refreshable:"false"`
	SaslMechanisms          ParamItem  `refreshable:"false"`
	SecurityProtocol        ParamItem  `refreshable:"false"`
        // Add the following three configuration items to support kerberos
	SaslKerberosServiceName ParamItem  `refreshable:"false"`
	SaslKerberosKeytab      ParamItem  `refreshable:"false"`
	SaslKerberosPrincipal   ParamItem  `refreshable:"false"`
	ConsumerExtraConfig     ParamGroup `refreshable:"false"`
	ProducerExtraConfig     ParamGroup `refreshable:"false"`
	ReadTimeout             ParamItem  `refreshable:"true"`
}

func (k *KafkaConfig) Init(base *BaseTable) {
// other code ....
	k.SaslKerberosServiceName = ParamItem{
		Key:          "kafka.sasl.kerberos.service.name",
		DefaultValue: "",
		Version:      "2.1.0",
		Export:       true,
	}
	k.SaslKerberosServiceName.Init(base.mgr)

	k.SaslKerberosKeytab = ParamItem{
		Key:          "kafka.sasl.kerberos.keytab",
		DefaultValue: "",
		Version:      "2.1.0",
		Export:       true,
	}
	k.SaslKerberosKeytab.Init(base.mgr)

	k.SaslKerberosPrincipal = ParamItem{
		Key:          "kafka.sasl.kerberos.principal",
		DefaultValue: "",
		Version:      "2.1.0",
		Export:       true,
	}
	k.SaslKerberosPrincipal.Init(base.mgr)
// other code ...
```
kafka_client.go
```go
func NewKafkaClientInstanceWithConfig(config *paramtable.KafkaConfig) *kafkaClient {
// other code ...
        if config.SaslMechanisms.GetValue() == "GSSAPI" {
		kafkaConfig.SetKey("sasl.mechanisms", config.SaslMechanisms.GetValue())
		kafkaConfig.SetKey("security.protocol", config.SecurityProtocol.GetValue())
		kafkaConfig.SetKey("sasl.kerberos.service.name", config.SaslKerberosServiceName.GetValue())
		kafkaConfig.SetKey("sasl.kerberos.keytab", config.SaslKerberosKeytab.GetValue())
		kafkaConfig.SetKey("sasl.kerberos.principal", config.SaslKerberosPrincipal.GetValue())
		log.Info(">>>>>>>>>> Kerberos config: ", zap.String("sasl.mechanisms", config.SaslMechanisms.GetValue()),
			zap.String("security.protocol", config.SecurityProtocol.GetValue()),
			zap.String("sasl.kerberos.service.name", config.SaslKerberosServiceName.GetValue()),
			zap.String("sasl.kerberos.keytab", config.SaslKerberosKeytab.GetValue()),
			zap.String("sasl.kerberos.principal", config.SaslKerberosPrincipal.GetValue()))
	}
// other code ...
```

**Comment by jaime0815** [comment]
@BUPTAnderson   It looks good, cloud you submit a PR to support config kerberos on the kafka client ?
