### ISSUE TITLE
[Bug]: The attu cannot load the cluster index , Indexes exceeding 10 million cannot be loaded

### ISSUE THREAD

**Issue by li904775857** [milvus-io/milvus#27829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.8 ==> 2.3.1
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): centos
- CPU/Memory:  560/3500G
- GPU: 
- Others:
```

### Current Behavior

After three months of operation of the original service, a large number of nodes crashed. After I restarted the overall service, the loading index was particularly slow, and it took 5 hours to load 70 million, and it could not be retrieved after loading.

After 2.3.1 is upgraded, nodes can start normally, but the attu cannot load indexes

minio uses nfs with 20 terabytes of storage

### Milvus Log

 [milvus-log.zip](https://github.com/milvus-io/milvus/files/13051423/milvus-log.zip)
This is the log for all components

**Comment by yanliang567** [comment]
1. it is not recommended use nfs as the minio backend, which would cause data inconsistency. If it is a production env, please not use nfs ASAP.  
2. please try to use sdk, such as pymilvus to load, to check whether it is an attu specific issue or not.

/assign @li904775857

**Comment by li904775857** [comment]
I have used pymilvus to try to load, loading 100,000 can be successful, but loading more than 20 million will have a timeout error

**Comment by li904775857** [comment]
Is the loading failure due to nfs storage? Because this problem suddenly appeared after 3 months of running the program, no data was added in the following month, and it was only used as a query

**Comment by li904775857** [comment]
Is there any quick solution to my problem?

**Comment by yanliang567** [comment]
> Is the loading failure due to nfs storage? Because this problem suddenly appeared after 3 months of running the program, no data was added in the following month, and it was only used as a query

it could be. If so I'd suggest you reinstall a new milvus with non_nfs minio and reinsert all the data.

**Comment by li904775857** [comment]
I have set up the new cluster, but I can't find the import tutorial on the official website. Can you provide it?

**Comment by li904775857** [comment]
Can I migrate data from the old cluster to the new cluster?

**Comment by yanliang567** [comment]
we suppose the data in the minio is inconsistent now, so you shall not migrate data from it. You have to re-insert the data into a new cluster.

**Comment by li904775857** [comment]
I created a new cluster, nfs mounted the storage, and then re-imported about 3 million data, found that the loading is still slow, loading into the query can not be queried, should be the storage machine problem, or other problems? I am trying to use oss as storage, can I import my existing data for testing or do I have to re-transfer it all?

**Comment by yanliang567** [comment]
/assign @LoveEachDay 
any ideas?

/unassign

**Comment by LoveEachDay** [comment]
You can transfer all the data to oss storage. Have you resolved the slow loading problem when you change the object storage to aliyun oss @li904775857

**Comment by li904775857** [comment]
> You can transfer all the data to oss storage. Have you resolved the slow loading problem when you change the object storage to aliyun oss 您可以将所有数据传输到oss存储。您是否解决了将对象存储更改为aliyun oss时加载缓慢的问题@li904775857

I cleaned up the data and stored it on a local disk, which didn't happen for a while
