### ISSUE TITLE
[Bug]: collection load fail with an exception '(code=1, message=show collection failed: legacy error code:1, reason: limit=200: request limit exceeded)'

### ISSUE THREAD

**Issue by cheetahsec** [milvus-io/milvus#27828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3
- Deployment mode(standalone or cluster): standalone 
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu 
- CPU/Memory: 200G
- GPU: 
- Others:
```

### Current Behavior

When loading a collection, the API call returns an exception, and the quantity scale is 385 million. When a single collection has a data scale of 100 million, the test is normal. The machine performance should be sufficient. When monitoring errors are reported, the machine load does not exceed the limit.

> RPC error: [get_loading_progress], <MilvusException: (code=1, message=show collection failed: legacy error code:1, reason: limit=200: request limit exceeded)>, <Time:{'RPC start': '2023-10-20 13:35:16.240361', 'RPC error': '2023-10-20 13:35:19.600411'}>
> RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=show collection failed: legacy error code:1, reason: limit=200: request limit exceeded)>, <Time:{'RPC start': '2023-10-20 13:25:13.693260', 'RPC error': '2023-10-20 13:35:19.601382'}>
> RPC error: [load_collection], <MilvusException: (code=1, message=show collection failed: legacy error code:1, reason: limit=200: request limit exceeded)>, <Time:{'RPC start': '2023-10-20 13:25:13.577261', 'RPC error': '2023-10-20 13:35:19.602382'}>

Similar issues：(https://github.com/milvus-io/milvus/issues/27286)

### Milvus Log

[milvus_1.log](https://github.com/milvus-io/milvus/files/13051098/milvus_1.log)

**Comment by xiaofan-luan** [comment]
seems to be the rete limitation triggered?
can you show the code you?

**Comment by cheetahsec** [comment]
There is nothing special about the code. Data insertion and indexing are successful. The RPC alarm log is triggered when `collection.load()` is called. I guessed that it may be related to the disk IO performance. The 400 million data is about 100GB or more. After moving the docker volumes to SSD, this problem was solved.
