### ISSUE TITLE
[Enhancement]:  When proxy's context is done,  err msg should be propagated

### ISSUE THREAD

**Issue by haorenfsa** [milvus-io/milvus#27833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

When proxy's context is done, the err msg is not propagated, so we can't know what the err is from log.

```go
// WaitToFinish waits until the TaskCondition is notified or context done or canceled
func (tc *TaskCondition) WaitToFinish() error {
	select {
	case <-tc.ctx.Done():
		return errors.New("proxy TaskCondition context Done")
	case err := <-tc.done:
		return err
	}
}
```

shoud use `tc.ctx.Err()` instead of creating a new err

**Comment by xiaofan-luan** [comment]
Good catch
