### ISSUE TITLE
When the search method traffic surges to a certain level, a response timeout will occur. But when it slowly increases to the above level, the response is normal.

### ISSUE THREAD

**Issue by wutachiang** [milvus-io/milvus#27832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.11
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2): milvus-sdk-java v2.2.11
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 64C128G * 6
- GPU: None
- Others:
```

### Current Behavior

When there is an instantaneous sudden increase in traffic, such as from 1000qps to 5000qps instantaneously, the response time of the search method of milvus will slow down, from the previous tens of milliseconds to tens of seconds, and will return to normal after a few seconds. But when the traffic increases steadily from 1000qps to 5000qps, the response of the search method of milvus is relatively normal. The current qps supported by the cluster is about 10,000 qps, so the above situation is very strange.
 The monitoring of prometheus is as follows:

![2023-10-20_16-34](https://github.com/milvus-io/milvus/assets/13926708/2f4c5636-cb38-4c27-8243-66b07fd8a36c)
![2023-10-20_16-35](https://github.com/milvus-io/milvus/assets/13926708/0e37b285-38f2-4169-9796-8a7dcbb785e4)
![2023-10-20_16-37](https://github.com/milvus-io/milvus/assets/13926708/941a5be4-ef7e-4b14-ad4e-b57a373d110a)
![2023-10-20_16-38](https://github.com/milvus-io/milvus/assets/13926708/bb389923-7d13-40a7-94f1-f4f2c040da75)
![2023-10-20_16-39](https://github.com/milvus-io/milvus/assets/13926708/2e03a00f-f151-4b02-816b-e37176812cf9)

### Expected Behavior

The search method under instantaneous traffic surge should be consistent with the performance of steady increase.

### Steps To Reproduce

```markdown
1. You can observe the performance of the service in this situation by temporarily increasing the traffic and then immediately returning it to before.
```

### Milvus Log

Relevant log information is attached to the network disk link below.
https://pan.baidu.com/s/1RocYduOAqkOCR6TNo84YjQ

**Comment by yanliang567** [comment]
I this was caused by the policy of nq combination. @czs007 could you please help to double check?
/assign @czs007 
/unassign

**Comment by bigsheeper** [comment]
Hi,  @wutachiang
Could you please provide us with the differences in NQ monitorings between the normal scenario and the abnormal scenario? The monitorings in question are as follows:

![image](https://github.com/milvus-io/milvus/assets/42060877/b4567fbc-a12c-4c07-916e-851d60c42a6c)
![image](https://github.com/milvus-io/milvus/assets/42060877/cf33f998-8b21-4a02-bf5d-3ad59474cf8a)
