### ISSUE TITLE
[Bug]: fail to get shard leaders from QueryCoord: collection=xxx: collection not loaded: unrecoverable error: fail to search on all shard leaders in Milvus cluster 2.3.0 

### ISSUE THREAD

**Issue by chan001** [milvus-io/milvus#27846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.0
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.14
- OS(Ubuntu or CentOS): Red Hat Enterprise Linux release 8.5
- CPU/Memory: 8c/16g
- GPU: /
- Others:
```

### Current Behavior

Search the vector data in many times,and then happen error 
![4298c165254fa2f5ae369270f43fbea](https://github.com/milvus-io/milvus/assets/16756392/e17b44e2-095e-4078-995f-2fe1604d3aeb)

![673608e6e02ef6baab8413bb9e9a25a](https://github.com/milvus-io/milvus/assets/16756392/7110461a-e243-429f-b68f-6dc13429c41e)
![97b0ed650195e919dea8961f822cd50](https://github.com/milvus-io/milvus/assets/16756392/0395c339-5cb7-44b3-98e3-a4e2cda283d4)
follow is the collection and index info
![d7646842f5e5eef901df0f4653c3d38](https://github.com/milvus-io/milvus/assets/16756392/f6a845cb-2294-422e-9887-3f5a93290742)
collection size :631459
additional milvus cluster status
![98c0b668889156e5c0fc74b5275cfbc](https://github.com/milvus-io/milvus/assets/16756392/1e7faa4c-ac45-4d84-9d5d-5954191ecee3)

### Milvus Log
This is part of milvus-proxy's logs (sorry, Server is running in intranet and can't take out the logs),this error not match with the error of above ,but the basic reason may is the same..
![6321ed8e795c1cd398692b3cbf4f297](https://github.com/milvus-io/milvus/assets/16756392/c88cc598-54e3-4520-a40a-11edad47f0a5)

**Comment by chan001** [comment]
additional milvus cluster status
![98c0b668889156e5c0fc74b5275cfbc](https://github.com/milvus-io/milvus/assets/16756392/8f2f42cc-3da8-4806-a07c-d92377d05f85)

**Comment by yanliang567** [comment]
it seems that the search failures are caused by milvus pod restart, to investigate why the pods restarted, please collect the full milvus logs and attach them in the issue. Could you please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @chan001 
/unassign

**Comment by chan001** [comment]
> /assign @chan001

today I retry to operate the Milvus,and it refuse the connect...see the part of Milvus Log

**Comment by xiaofan-luan** [comment]
seems that datanode and indexnode is all crashed for some reason.
I guess this might be a S3 config error.
