### ISSUE TITLE
[Bug]: datacoord and querynode CrashLoopBackOff

### ISSUE THREAD

**Issue by yuan8180** [milvus-io/milvus#27853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.1
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2):milvus-sdk-go 2.3.1
- OS(Ubuntu or CentOS): Ubuntu 
- CPU/Memory: 70/220gb
- GPU: no use
- Others:
```

### Current Behavior

can't flush data, the datacoord is the status of CrashLoopBackOff, so I unstall milvus without delete the pvc, then install the milvus,but it shows that datacoord and querynode CrashLoopBackOff.

km get all | grep -E "my-release|NAME"
NAME                                                READY   STATUS             RESTARTS        AGE
pod/my-release-etcd-0                               1/1     Running            0               21m
pod/my-release-etcd-1                               1/1     Running            0               21m
pod/my-release-etcd-2                               1/1     Running            0               21m
pod/my-release-milvus-attu-74d6fb8f8f-x6vhz         1/1     Running            0               21m
pod/my-release-milvus-datacoord-7b5989d6f5-6vz7z    0/1     CrashLoopBackOff   8 (3m36s ago)   21m
pod/my-release-milvus-datanode-6bf6df77c8-w8pb4     0/1     Running            5 (47s ago)     21m
pod/my-release-milvus-indexcoord-578f764648-fm5zs   1/1     Running            0               21m
pod/my-release-milvus-indexnode-6db5fc999-plr9s     1/1     Running            0               21m
pod/my-release-milvus-indexnode-6db5fc999-snzgp     1/1     Running            0               21m
pod/my-release-milvus-proxy-5b5bf8dc98-gx467        0/1     Running            5 (47s ago)     21m
pod/my-release-milvus-querycoord-55669f695c-nmmft   0/1     Running            5 (47s ago)     21m
pod/my-release-milvus-querynode-58b4b5c484-79vjr    0/1     CrashLoopBackOff   8 (4m ago)      21m
pod/my-release-milvus-querynode-58b4b5c484-jlrgk    0/1     CrashLoopBackOff   8 (4m6s ago)    21m
pod/my-release-milvus-querynode-58b4b5c484-t5dvn    0/1     CrashLoopBackOff   8 (3m47s ago)   21m
pod/my-release-milvus-rootcoord-65dc6fc9d8-nl8l5    1/1     Running            0               21m
pod/my-release-pulsar-bookie-0                      1/1     Running            0               21m
pod/my-release-pulsar-bookie-1                      1/1     Running            0               21m
pod/my-release-pulsar-bookie-2                      1/1     Running            0               21m
pod/my-release-pulsar-bookie-init-lh8xk             0/1     Completed          0               21m
pod/my-release-pulsar-broker-0                      1/1     Running            0               21m
pod/my-release-pulsar-broker-1                      1/1     Running            0               21m
pod/my-release-pulsar-proxy-0                       1/1     Running            0               21m
pod/my-release-pulsar-proxy-1                       1/1     Running            0               21m
pod/my-release-pulsar-pulsar-init-tkw6x             0/1     Completed          0               21m
pod/my-release-pulsar-recovery-0                    1/1     Running            0               21m
pod/my-release-pulsar-zookeeper-0                   1/1     Running            0               21m
pod/my-release-pulsar-zookeeper-1                   1/1     Running            0               20m
pod/my-release-pulsar-zookeeper-2                   1/1     Running            0               20m
NAME                                   TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                               AGE
service/my-release-etcd                ClusterIP   10.102.154.126   <none>        2379/TCP,2380/TCP                     21m
service/my-release-etcd-headless       ClusterIP   None             <none>        2379/TCP,2380/TCP                     21m
service/my-release-milvus              ClusterIP   10.109.220.44    <none>        19530/TCP,9091/TCP                    21m
service/my-release-milvus-attu         ClusterIP   10.99.78.5       <none>        3000/TCP                              21m
service/my-release-milvus-datacoord    ClusterIP   10.108.231.214   <none>        13333/TCP,9091/TCP                    21m
service/my-release-milvus-datanode     ClusterIP   None             <none>        9091/TCP                              21m
service/my-release-milvus-indexcoord   ClusterIP   10.104.176.53    <none>        31000/TCP,9091/TCP                    21m
service/my-release-milvus-indexnode    ClusterIP   None             <none>        9091/TCP                              21m
service/my-release-milvus-querycoord   ClusterIP   10.105.1.210     <none>        19531/TCP,9091/TCP                    21m
service/my-release-milvus-querynode    ClusterIP   None             <none>        9091/TCP                              21m
service/my-release-milvus-rootcoord    ClusterIP   10.96.157.28     <none>        53100/TCP,9091/TCP                    21m
service/my-release-pulsar-bookie       ClusterIP   None             <none>        3181/TCP,8000/TCP                     21m
service/my-release-pulsar-broker       ClusterIP   None             <none>        8080/TCP,6650/TCP                     21m
service/my-release-pulsar-proxy        ClusterIP   10.102.178.225   <none>        80/TCP,6650/TCP                       21m
service/my-release-pulsar-recovery     ClusterIP   None             <none>        8000/TCP                              21m
service/my-release-pulsar-zookeeper    ClusterIP   None             <none>        8000/TCP,2888/TCP,3888/TCP,2181/TCP   21m
NAME                                           READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/my-release-milvus-attu         1/1     1            1           21m
deployment.apps/my-release-milvus-datacoord    0/1     1            0           21m
deployment.apps/my-release-milvus-datanode     0/1     1            0           21m
deployment.apps/my-release-milvus-indexcoord   1/1     1            1           21m
deployment.apps/my-release-milvus-indexnode    2/2     2            2           21m
deployment.apps/my-release-milvus-proxy        0/1     1            0           21m
deployment.apps/my-release-milvus-querycoord   0/1     1            0           21m
deployment.apps/my-release-milvus-querynode    0/3     3            0           21m
deployment.apps/my-release-milvus-rootcoord    1/1     1            1           21m
NAME                                                      DESIRED   CURRENT   READY   AGE
replicaset.apps/my-release-milvus-attu-74d6fb8f8f         1         1         1       21m
replicaset.apps/my-release-milvus-datacoord-7b5989d6f5    1         1         0       21m
replicaset.apps/my-release-milvus-datanode-6bf6df77c8     1         1         0       21m
replicaset.apps/my-release-milvus-indexcoord-578f764648   1         1         1       21m
replicaset.apps/my-release-milvus-indexnode-6db5fc999     2         2         2       21m
replicaset.apps/my-release-milvus-proxy-5b5bf8dc98        1         1         0       21m
replicaset.apps/my-release-milvus-querycoord-55669f695c   1         1         0       21m
replicaset.apps/my-release-milvus-querynode-58b4b5c484    3         3         0       21m
replicaset.apps/my-release-milvus-rootcoord-65dc6fc9d8    1         1         1       21m
NAME                                           READY   AGE
statefulset.apps/my-release-etcd               3/3     21m
statefulset.apps/my-release-pulsar-bookie      3/3     21m
statefulset.apps/my-release-pulsar-broker      2/2     21m
statefulset.apps/my-release-pulsar-proxy       2/2     21m
statefulset.apps/my-release-pulsar-recovery    1/1     21m
statefulset.apps/my-release-pulsar-zookeeper   3/3     21m
NAME                                      COMPLETIONS   DURATION   AGE
job.batch/my-release-pulsar-bookie-init   1/1           111s       21m
job.batch/my-release-pulsar-pulsar-init   1/1           115s       21m

### Expected Behavior

all pod are running

### Steps To Reproduce

```markdown
minikube delete --all && minikube start --driver=kvm2 --cpus=70 --memory='220gb' --disk-size='500gb' --wait-timeout=3m --v=2 --force
helm install my-release milvus2.3.x/milvus -n milvus-search --set attu.enabled=true -f helmConfigYml.yml
```

### Milvus Log

[log-my-release-milvus-datacoord-7b5989d6f5-6vz7z.txt](https://github.com/milvus-io/milvus/files/13066981/log-my-release-milvus-datacoord-7b5989d6f5-6vz7z.txt)
[log-my-release-milvus-querynode-58b4b5c484-79vjr.txt](https://github.com/milvus-io/milvus/files/13066982/log-my-release-milvus-querynode-58b4b5c484-79vjr.txt)
[log-my-release-milvus-querynode-58b4b5c484-jlrgk.txt](https://github.com/milvus-io/milvus/files/13066983/log-my-release-milvus-querynode-58b4b5c484-jlrgk.txt)
[log-my-release-milvus-querynode-58b4b5c484-t5dvn.txt](https://github.com/milvus-io/milvus/files/13066984/log-my-release-milvus-querynode-58b4b5c484-t5dvn.txt)
[log-describe-error-pod.txt](https://github.com/milvus-io/milvus/files/13067049/log-describe-error-pod.txt)

[helmConfigYml.yml.txt](https://github.com/milvus-io/milvus/files/13067053/helmConfigYml.yml.txt)

**Comment by xiaofan-luan** [comment]
/assign @zhagnlu 
could you help on it?

**Comment by zhagnlu** [comment]
From the log error, minio server address may make a mistake, could you provide the detail of setting file: milvus.yaml , and check the minio address, like show as below:
![image](https://github.com/milvus-io/milvus/assets/11935707/f569bc1c-777e-4025-9f61-b3fc770c580c)
check whether this address is correct

**Comment by yuan8180** [comment]
I deploy it by helm, there is no milvus.yaml,but I find minio's config in values.yaml as below
depending on your info, I think the problem is related to minio, because I created another minio in the same namespace, they have the same port, although the forwarding port is the same, but maybe milvus has problems in finding the local minio, I try to put them in different namespaces should be solved.
![image](https://github.com/milvus-io/milvus/assets/140597641/8a38b35b-6a77-4938-aa56-a6ef9739c129)
![image](https://github.com/milvus-io/milvus/assets/140597641/6b863f37-bd21-4775-8865-921e923e81a4)
thanks

**Comment by Bennu-Li** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version:2.3.1
> - Deployment mode(standalone or cluster):cluster
> - MQ type(rocksmq, pulsar or kafka):    pulsar 
> - SDK version(e.g. pymilvus v2.0.0rc2):milvus-sdk-go 2.3.1
> - OS(Ubuntu or CentOS): Ubuntu 
> - CPU/Memory: 70/220gb
> - GPU: no use
> - Others:
> ```
> 
> ### Current Behavior
> can't flush data, the datacoord is the status of CrashLoopBackOff, so I unstall milvus without delete the pvc, then install the milvus,but it shows that datacoord and querynode CrashLoopBackOff.
> 
> km get all | grep -E "my-release|NAME" NAME READY STATUS RESTARTS AGE pod/my-release-etcd-0 1/1 Running 0 21m pod/my-release-etcd-1 1/1 Running 0 21m pod/my-release-etcd-2 1/1 Running 0 21m pod/my-release-milvus-attu-74d6fb8f8f-x6vhz 1/1 Running 0 21m pod/my-release-milvus-datacoord-7b5989d6f5-6vz7z 0/1 CrashLoopBackOff 8 (3m36s ago) 21m pod/my-release-milvus-datanode-6bf6df77c8-w8pb4 0/1 Running 5 (47s ago) 21m pod/my-release-milvus-indexcoord-578f764648-fm5zs 1/1 Running 0 21m pod/my-release-milvus-indexnode-6db5fc999-plr9s 1/1 Running 0 21m pod/my-release-milvus-indexnode-6db5fc999-snzgp 1/1 Running 0 21m pod/my-release-milvus-proxy-5b5bf8dc98-gx467 0/1 Running 5 (47s ago) 21m pod/my-release-milvus-querycoord-55669f695c-nmmft 0/1 Running 5 (47s ago) 21m pod/my-release-milvus-querynode-58b4b5c484-79vjr 0/1 CrashLoopBackOff 8 (4m ago) 21m pod/my-release-milvus-querynode-58b4b5c484-jlrgk 0/1 CrashLoopBackOff 8 (4m6s ago) 21m pod/my-release-milvus-querynode-58b4b5c484-t5dvn 0/1 CrashLoopBackOff 8 (3m47s ago) 21m pod/my-release-milvus-rootcoord-65dc6fc9d8-nl8l5 1/1 Running 0 21m pod/my-release-pulsar-bookie-0 1/1 Running 0 21m pod/my-release-pulsar-bookie-1 1/1 Running 0 21m pod/my-release-pulsar-bookie-2 1/1 Running 0 21m pod/my-release-pulsar-bookie-init-lh8xk 0/1 Completed 0 21m pod/my-release-pulsar-broker-0 1/1 Running 0 21m pod/my-release-pulsar-broker-1 1/1 Running 0 21m pod/my-release-pulsar-proxy-0 1/1 Running 0 21m pod/my-release-pulsar-proxy-1 1/1 Running 0 21m pod/my-release-pulsar-pulsar-init-tkw6x 0/1 Completed 0 21m pod/my-release-pulsar-recovery-0 1/1 Running 0 21m pod/my-release-pulsar-zookeeper-0 1/1 Running 0 21m pod/my-release-pulsar-zookeeper-1 1/1 Running 0 20m pod/my-release-pulsar-zookeeper-2 1/1 Running 0 20m NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE service/my-release-etcd ClusterIP 10.102.154.126 2379/TCP,2380/TCP 21m service/my-release-etcd-headless ClusterIP None 2379/TCP,2380/TCP 21m service/my-release-milvus ClusterIP 10.109.220.44 19530/TCP,9091/TCP 21m service/my-release-milvus-attu ClusterIP 10.99.78.5 3000/TCP 21m service/my-release-milvus-datacoord ClusterIP 10.108.231.214 13333/TCP,9091/TCP 21m service/my-release-milvus-datanode ClusterIP None 9091/TCP 21m service/my-release-milvus-indexcoord ClusterIP 10.104.176.53 31000/TCP,9091/TCP 21m service/my-release-milvus-indexnode ClusterIP None 9091/TCP 21m service/my-release-milvus-querycoord ClusterIP 10.105.1.210 19531/TCP,9091/TCP 21m service/my-release-milvus-querynode ClusterIP None 9091/TCP 21m service/my-release-milvus-rootcoord ClusterIP 10.96.157.28 53100/TCP,9091/TCP 21m service/my-release-pulsar-bookie ClusterIP None 3181/TCP,8000/TCP 21m service/my-release-pulsar-broker ClusterIP None 8080/TCP,6650/TCP 21m service/my-release-pulsar-proxy ClusterIP 10.102.178.225 80/TCP,6650/TCP 21m service/my-release-pulsar-recovery ClusterIP None 8000/TCP 21m service/my-release-pulsar-zookeeper ClusterIP None 8000/TCP,2888/TCP,3888/TCP,2181/TCP 21m NAME READY UP-TO-DATE AVAILABLE AGE deployment.apps/my-release-milvus-attu 1/1 1 1 21m deployment.apps/my-release-milvus-datacoord 0/1 1 0 21m deployment.apps/my-release-milvus-datanode 0/1 1 0 21m deployment.apps/my-release-milvus-indexcoord 1/1 1 1 21m deployment.apps/my-release-milvus-indexnode 2/2 2 2 21m deployment.apps/my-release-milvus-proxy 0/1 1 0 21m deployment.apps/my-release-milvus-querycoord 0/1 1 0 21m deployment.apps/my-release-milvus-querynode 0/3 3 0 21m deployment.apps/my-release-milvus-rootcoord 1/1 1 1 21m NAME DESIRED CURRENT READY AGE replicaset.apps/my-release-milvus-attu-74d6fb8f8f 1 1 1 21m replicaset.apps/my-release-milvus-datacoord-7b5989d6f5 1 1 0 21m replicaset.apps/my-release-milvus-datanode-6bf6df77c8 1 1 0 21m replicaset.apps/my-release-milvus-indexcoord-578f764648 1 1 1 21m replicaset.apps/my-release-milvus-indexnode-6db5fc999 2 2 2 21m replicaset.apps/my-release-milvus-proxy-5b5bf8dc98 1 1 0 21m replicaset.apps/my-release-milvus-querycoord-55669f695c 1 1 0 21m replicaset.apps/my-release-milvus-querynode-58b4b5c484 3 3 0 21m replicaset.apps/my-release-milvus-rootcoord-65dc6fc9d8 1 1 1 21m NAME READY AGE statefulset.apps/my-release-etcd 3/3 21m statefulset.apps/my-release-pulsar-bookie 3/3 21m statefulset.apps/my-release-pulsar-broker 2/2 21m statefulset.apps/my-release-pulsar-proxy 2/2 21m statefulset.apps/my-release-pulsar-recovery 1/1 21m statefulset.apps/my-release-pulsar-zookeeper 3/3 21m NAME COMPLETIONS DURATION AGE job.batch/my-release-pulsar-bookie-init 1/1 111s 21m job.batch/my-release-pulsar-pulsar-init 1/1 115s 21m
> 
> ### Expected Behavior
> all pod are running
> 
> ### Steps To Reproduce
> ```
> minikube delete --all && minikube start --driver=kvm2 --cpus=70 --memory='220gb' --disk-size='500gb' --wait-timeout=3m --v=2 --force
> helm install my-release milvus2.3.x/milvus -n milvus-search --set attu.enabled=true -f helmConfigYml.yml
> ```
> 
> ### Milvus Log
> [log-my-release-milvus-datacoord-7b5989d6f5-6vz7z.txt](https://github.com/milvus-io/milvus/files/13066981/log-my-release-milvus-datacoord-7b5989d6f5-6vz7z.txt) [log-my-release-milvus-querynode-58b4b5c484-79vjr.txt](https://github.com/milvus-io/milvus/files/13066982/log-my-release-milvus-querynode-58b4b5c484-79vjr.txt) [log-my-release-milvus-querynode-58b4b5c484-jlrgk.txt](https://github.com/milvus-io/milvus/files/13066983/log-my-release-milvus-querynode-58b4b5c484-jlrgk.txt) [log-my-release-milvus-querynode-58b4b5c484-t5dvn.txt](https://github.com/milvus-io/milvus/files/13066984/log-my-release-milvus-querynode-58b4b5c484-t5dvn.txt) [log-describe-error-pod.txt](https://github.com/milvus-io/milvus/files/13067049/log-describe-error-pod.txt)
> 
> [helmConfigYml.yml.txt](https://github.com/milvus-io/milvus/files/13067053/helmConfigYml.yml.txt)
> 
> ### Anything else?
> _No response_

Why is there no minio pod here? Did you enable the externalS3 configuration?

**Comment by yuan8180** [comment]
I am sorry that I did not consider this reason before, so the information about minio cluster was removed from the screenshot. I created the minio cluster independently, and I enable the externalS3 configuration. But the minio service of the minio cluster conflicted with the minio service port in the milvus cluster.

**Comment by LoveEachDay** [comment]
@yuan8180 To set `externalS3.enabled=true`, you'd set `minio.enabled=false` also.
