### ISSUE TITLE
[Bug]: Conan version 1.58.0 can no longer install googleapis/cci.20221108

### ISSUE THREAD

**Issue by ashkrisk** [milvus-io/milvus#27869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- OS: Ubuntu 20.04
- Linux/x86_64
```

### Current Behavior

The workflow to compile Milvus on a fresh Ubuntu 20.04 machine no longer works.

From a clean Ubuntu 20.04 machine, first run `scripts/install_deps.sh`. Among other things, this installs Conan version `1.58.0`.

Now, try to build Milvus locally with `make`. The build fails quickly because of the following error:
```
ERROR: googleapis/cci.20221108: Cannot load recipe.
(...) Current Conan version (1.58.0) does not satisfy the defined one (>=1.60.0 <2 || >=2.0.5).
conan install failed
```

### Expected Behavior

On a clean install of Ubuntu 20.04, `./install_deps.sh` followed by `make` should successfully build Milvus.

### Steps To Reproduce

```markdown
1. Clean install of Ubuntu 20.04 (x86_64)
2. Clone the milvus repository (this repository)
3. Install cmake and go
4. Run the install script `scripts/setup_deps.sh`
5. Run `make`
6. The build fails quickly with this error:

googleapis/cci.20221108: Not found in local cache, looking in remotes...
googleapis/cci.20221108: Trying with 'conancenter'...
Downloading conanmanifest.txt completed [0.31k]                                          
Downloading conanfile.py completed [10.38k]                                              
Downloading conan_export.tgz completed [2.53k]                                           
Decompressing conan_export.tgz completed [0.00k]                                         
googleapis/cci.20221108: Downloaded recipe revision bbf3991516a8b3ce0923209c3df92665
ERROR: googleapis/cci.20221108: Cannot load recipe.
Error loading conanfile at '/root/.conan/data/googleapis/cci.20221108/_/_/export/conanfile.py': Current Conan version (1.58.0) does not satisfy the defined one (>=1.60.0 <2 || >=2.0.5).
conan install failed
```

### Anything else?

Possibly, the build was broken by this update to the googleapis/20221108 recipe: https://github.com/conan-io/conan-center-index/pull/19971. As part of that PR, the required conan version was updated:

<img width="521" alt="Screenshot 2023-10-23 at 10 06 34 PM" src="https://github.com/milvus-io/milvus/assets/137368647/0ebaf6b4-40d5-496a-984c-3718047ac568">

---
Updating the conan version to `1.60.0` is enough to resolve the issue

**Comment by jiaoew1991** [comment]
we need to upgrade conan version 🤔
