### ISSUE TITLE
[Enhancement]: migrate milvus cluster mode from docker-compose to milvus cluster mode on kubernetes

### ISSUE THREAD

**Issue by MayurDuduka** [milvus-io/milvus#27868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

- **source:** Milvus version on docker-compose:  v2.3.1 (cluster mode)
- **destination:** Milvus version on Kubernetes:  v2.3.1 (cluster mode)

**We want to migrate all the collections to Kubernetes Milvus from Milvus docker-compose.**

Can someone please assist with the steps here?

Thanks

### Why is this needed?

- **source:** Milvus version on docker-compose:  v2.3.1 (cluster mode)
- **destination:** Milvus version on Kubernetes:  v2.3.1 (cluster mode)

**We want to migrate all the collections to Kubernetes Milvus from Milvus docker-compose.**

Can someone please assist with the steps here?

Thanks

**Comment by jiaoew1991** [comment]
hi @MayurDuduka you can use backup tool https://github.com/zilliztech/milvus-backup
