### ISSUE TITLE
[Bug]:  Reduce RPC from DC to RC during DC startup stage

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#27863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master & 2.2.0
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Initialization DC needs to unwatch dropped channels during the startup stage, but it depends on multiple describe collection RPC with RC. It is easy to block or startup fail if some DDL is executed in the task queue on the RC.

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version: master & 2.2.0
> - Deployment mode(standalone or cluster):
> - MQ type(rocksmq, pulsar or kafka):    
> - SDK version(e.g. pymilvus v2.0.0rc2):
> - OS(Ubuntu or CentOS): 
> - CPU/Memory: 
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> Initialization DC needs to unwatch dropped channels during the startup stage, but it depends on multiple describe collection RPC with RC. It is easy to block or startup fail if some DDL is executed in the task queue on the RC.
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

we just need to list all the channel right?

**Comment by xiaofan-luan** [comment]
As discussed, we decide to remove the has collection dependency between datacoord to rootcoord.

**Comment by xiaofan-luan** [comment]
2.2.8 or any previous version might be affected if they upgrade to 2.3.2
we will give tools if anyone hit the issue.
