### ISSUE TITLE
[Bug]:   Search Deadline Exceeded grpc_status:4

### ISSUE THREAD

**Issue by xTerry** [milvus-io/milvus#27888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.10
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2): v2.2.8
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 32C256G * 5 + 16C128G * 3
- GPU: none
- Others:
```

### Current Behavior

Collection : 70;
Data num: 1.2 billion+
Max Collection data num: 60 million+

When I searched vectors, timeout set to 30s, nprobe set to 32, single user request threads: 10. Frequent occurrence of timeout phenomenon.
Logs :
2023-10-24 16:33:32,984|vcp-profile-head-query-grpc-5976c57dcc-twlh9:1|WARNING|milvus_helpers.py,422 - 0:collection_name:ait_algo_profile_fk_10103_5_pro;load_status:3
RPC error: [search], <MilvusException: (code=1, message=<_InactiveRpcError of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "UNKNOWN:Deadline Exceeded {grpc_status:4, created_time:"2023-10-24T16:33:33.179364374+08:00"}"
>)>, <Time:{'RPC start': '2023-10-24 16:33:03.178244', 'RPC error': '2023-10-24 16:33:33.179845'}>
2023-10-24 16:33:33,180|vcp-profile-head-query-grpc-5976c57dcc-twlh9:1|ERROR|milvus_helpers.py,378 - 0:Failed to search vectors in Milvus: <MilvusException: (code=1, message=<_InactiveRpcError of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "UNKNOWN:Deadline Exceeded {grpc_status:4, created_time:"2023-10-24T16:33:33.179364374+08:00"}"
>)>,will load data to memory:ait_algo_profile_fk_10103_6_pro,None
2023-10-24 16:33:33,185|vcp-profile-head-query-grpc-5976c57dcc-twlh9:1|WARNING|milvus_helpers.py,422 - 0:collection_name:ait_algo_profile_fk_10103_6_pro;load_status:3
RPC error: [search], <MilvusException: (code=1, message=<_InactiveRpcError of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "UNKNOWN:Deadline Exceeded {grpc_status:4, created_time:"2023-10-24T16:33:33.37831871+08:00"}"
>)>, <Time:{'RPC start': '2023-10-24 16:33:03.377461', 'RPC error': '2023-10-24 16:33:33.378673'}>
2023-10-24 16:33:33,378|vcp-profile-head-query-grpc-5976c57dcc-twlh9:1|ERROR|milvus_helpers.py,378 - 0:Failed to search vectors in Milvus: <MilvusException: (code=1, message=<_InactiveRpcError of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "UNKNOWN:Deadline Exceeded {grpc_status:4, created_time:"2023-10-24T16:33:33.37831871+08:00"}"
>)>,will load data to memory:ait_algo_profile_fk_10103_7_pro,None
2023-10-24 16:33:33,383|vcp-profile-head-query-grpc-5976c57dcc-twlh9:1|WARNING|milvus_helpers.py,422 - 0:collection_name:ait_algo_profile_fk_10103_7_pro;load_status:3
RPC error: [search], <MilvusException: (code=1, message=<_InactiveRpcError of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2023-10-24T16:33:33.578325374+08:00", grpc_status:4}"
>)>, <Time:{'RPC start': '2023-10-24 16:33:03.577632', 'RPC error': '2023-10-24 16:33:33.578758'}>
2023-10-24 16:33:33,578|vcp-profile-head-query-grpc-5976c57dcc-twlh9:1|ERROR|milvus_helpers.py,378 - 0:Failed to search vectors in Milvus: <MilvusException: (code=1, message=<_InactiveRpcError of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2023-10-24T16:33:33.578325374+08:00", grpc_status:4}"
>)>,will load data to memory:ait_algo_profile_fk_10103_8_pro,None
2023-10-24 16:33:33,583|vcp-profile-head-query-grpc-5976c57dcc-twlh9:1|WARNING|milvus_helpers.py,422 - 0:collection_name:ait_algo_profile_fk_10103_8_pro;load_status:3
RPC error: [search], <MilvusException: (code=1, message=<_InactiveRpcError of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "UNKNOWN:Deadline Exceeded {grpc_status:4, created_time:"2023-10-24T16:33:33.779320402+08:00"}"
>)>, <Time:{'RPC start': '2023-10-24 16:33:03.778559', 'RPC error': '2023-10-24 16:33:33.779744'}>
2023-10-24 16:33:33,780|vcp-profile-head-query-grpc-5976c57dcc-twlh9:1|ERROR|milvus_helpers.py,378 - 0:Failed to search vectors in Milvus: <MilvusException: (code=1, message=<_InactiveRpcError of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "UNKNOWN:Deadline Exceeded {grpc_status:4, created_time:"2023-10-24T16:33:33.779320402+08:00"}"

### Milvus Log

Logs fils：
URL：https://pan.baidu.com/s/1H4YQ7siCU7xmb86gM05DSw 
Extracted code：uftd

**Comment by yah01** [comment]
Hi @xTerry, could you post the create index params of the collections you do searching?

**Comment by xTerry** [comment]
> Hi @xTerry, could you post the create index params of the collections you do searching?

index_param = {
                        "metric_type": "IP",
                        "index_type": "IVF_SQ8",
                        "params": {"nlist": 4096}
                    }

**Comment by xTerry** [comment]
> Hi @xTerry, could you post the create index params of the collections you do searching?
@yah01 
index_param = {
                        "metric_type": "IP",
                        "index_type": "IVF_SQ8",
                        "params": {"nlist": 4096}
                    }

**Comment by yah01** [comment]
@xTerry the machines should be enough to process your dataset, some parameters may make searching much slower:
- The `output_fields` contains many fields, or large field (long varchar)
- The `consistency_level` is strong level, strong level makes Milvus to wait for the time tick to promise you can see the latest data, try session level, bounded or eventually level according to your requirements

You can try to adjust the parameters mentioned above, and check whether the performance improved.

If it doesn't work, please provide your parameters, and the `expr` you are using while searching, the dimension of your vector data, and the schema of your collection (providing only fields' type is enough, fields' name could be removed if it's sensitive)

Also, if you deployed Prometheus for Milvus, it would help a lot for analyze your performance issue

**Comment by xTerry** [comment]
consistency_level
Can I make modifications while retaining data?

**Comment by xTerry** [comment]
> consistency_level Can I make modifications while retaining data?

milvus.search(data=vectors,anns_field="vectors",limit=top_k,param=search_params,partition_names=partition_tags,expr=expr,timeout=MILVUS_SEARCH_TIMEOUT,consistency_level="Eventually")

**Comment by xTerry** [comment]
> consistency_level Can I make modifications while retaining data?

milvus.search(data=vectors,anns_field="vectors",limit=top_k,param=search_params,partition_names=partition_tags,expr=expr,timeout=MILVUS_SEARCH_TIMEOUT,consistency_level="Eventually")

timeout still exist，probability：50%
@yah01

**Comment by yah01** [comment]
@xTerry Could you provide the search parameters:
- topk
- vector dimension
- schema
- expr

**Comment by xTerry** [comment]
> @xTerry Could you post the search parameters:
> 
> * topk ：50
> * vector dimension ：256
> * schema ：
![image](https://github.com/milvus-io/milvus/assets/2304854/967cf77b-8a0f-4462-afd0-464fc7135e54)

> * expr: NONE
nprobe:32
