### ISSUE TITLE
[Bug]: Delete records' timestamp may be reordered

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#27940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

We filter out the delete records if the primary key not exists in the segment, but the timestamp is not ordered following the primary keys

**Comment by yanliang567** [comment]
any tips to reproduce and verify the issue? @yah01

**Comment by yah01** [comment]
@yanliang567 run test at `vectordb-testbricks/milvus-bricks/upsert2.py`, modify the following code to help reproduce faster:
![img_v2_b071f48a-5ad7-42e0-942e-cdd204e1802g](https://github.com/milvus-io/milvus/assets/12216890/220a1624-c51c-4204-82f6-677b7c50d0eb)
replace the code in red pane with:
```
new_max_id = collection.query(expr="", output_fields=["count(*)"], consistency_level="Strong")[0].get("count(*)")
        if new_max_id != maxid:
            logging.info(f"max_id: {maxid}, new_max_id: {new_max_id}")
            exit(0)
```

**Comment by yanliang567** [comment]
is this a fix for #27515 ? @yah01

**Comment by yah01** [comment]
> is this a fix for #27515 ? @yah01

Yes, I would link to this issue too

**Comment by yanliang567** [comment]
it reproduced on milvus v2.3.3. :(
/unassign

**Comment by yanliang567** [comment]
@yah01 any updates?

**Comment by yah01** [comment]
@yanliang567 the timestamp unordered fixed, now there may be another problems, let's track this on https://github.com/milvus-io/milvus/issues/29272
