### ISSUE TITLE
[Bug]: querycoord pod has high CPU usage

### ISSUE THREAD

**Issue by pakelley** [milvus-io/milvus#27976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.1
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.1
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The CPU usage for querycoord is steadily increasing, and we've had to incrementally increase the CPU to keep the cluster running. We have asked in the slack, and they [seem to think](https://milvusio.slack.com/archives/CMNHUC371/p1698030481479459?thread_ts=1696424851.039199&cid=CMNHUC371) the cpu should be low there too.

### Expected Behavior

I expect the CPU usage in the querycoord pod to be generally low.

### Steps To Reproduce

```markdown
I can try to come up with this if necessary, but this is just a state our running Milvus cluster has gotten into.
```

### Milvus Log

[querycoord.log](https://github.com/milvus-io/milvus/files/13182140/querycoord.log)

**Comment by yanliang567** [comment]
@pakelley could you please provide more info about your workload? eg. data size? insert frequency? search qps?,etc. Also you'd better provide all the  mivlus metrics in grafana and full milvus pods logs. please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs

/assign @pakelley 
/unassign

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version: 2.3.1
> - Deployment mode(standalone or cluster): cluster
> - MQ type(rocksmq, pulsar or kafka):    kafka
> - SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.1
> - OS(Ubuntu or CentOS): 
> - CPU/Memory: 
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> The CPU usage for querycoord is steadily increasing, and we've had to incrementally increase the CPU to keep the cluster running. We have asked in the slack, and they [seem to think](https://milvusio.slack.com/archives/CMNHUC371/p1698030481479459?thread_ts=1696424851.039199&cid=CMNHUC371) the cpu should be low there too.
> 
> ### Expected Behavior
> I expect the CPU usage in the querycoord pod to be generally low.
> 
> ### Steps To Reproduce
> ```
> I can try to come up with this if necessary, but this is just a state our running Milvus cluster has gotten into.
> ```
> 
> ### Milvus Log
> [querycoord.log](https://github.com/milvus-io/milvus/files/13182140/querycoord.log)
> 
> ### Anything else?
> _No response_

Can we see the pprof of your querycoord?
seems to be many collection from the logs, this might be the main reason. 

@yanliang567 you should see the same behaviour if we have many collections

/assign @sunby
