### ISSUE TITLE
[Bug]: there is -dev tag in release v2.3.2

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#27989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.3.2
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/82361606/f9cc0728-984a-4b0f-b1bb-8dc20d7acab8)

**Comment by jiaoew1991** [comment]
fixed by https://github.com/milvus-io/milvus/pull/28316
