### ISSUE TITLE
[Bug]: restful api msg pls retrun the error when request api failed

### ISSUE THREAD

**Issue by yelusion2** [milvus-io/milvus#27988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.14
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

example: when i insert data and the dim not match, restfulapi retrun
{"code":1804,"message":"fail to deal the insert data"}  
i cannot see the error msg, how can i fast find the failed reson?  
i think not only insert api, check all restful api response.

### Expected Behavior

{"code":1804,"message":"fail to deal the insert data, error="vector length diff from dimension""}  

### Steps To Reproduce

```markdown
1.create a collection, dim = 8
2. insert data through restful api, and dim=4
```

**Comment by xiaofan-luan** [comment]
/assign @PowderLi 
could you help on refine the error message of restful API?

**Comment by PowderLi** [comment]
/unassign
/assign @yelusion2 
fixed already, need to recheck
