### ISSUE TITLE
[Bug]: Search yielded no results, but the query did produce results.

### ISSUE THREAD

**Issue by sevenold** [milvus-io/milvus#27986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.11
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.2
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 48GB
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/41443157/510dc23b-91e4-4e50-b0b8-bfc9c62b7aa4)
![image](https://github.com/milvus-io/milvus/assets/41443157/ff1ace82-b8d1-4871-a62e-94573bf936c9)
![image](https://github.com/milvus-io/milvus/assets/41443157/8b70e79c-f542-4225-8419-5db884f3109c)
![image](https://github.com/milvus-io/milvus/assets/41443157/8d6698b4-f6b5-491c-b5f9-1da836adb5f1)

### Steps To Reproduce

```markdown
1. insert data
2. flush()
3. Search yielded results
4. Wait a few minutes
5. Search yielded no results, but the query did produce results.
```

### Milvus Log

[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/13186434/milvus-log.tar.gz)

**Comment by yanliang567** [comment]
@sevenold do you mean you are trying to search specific vector and the return results do not contain that vector?
/assign @sevenold

**Comment by sevenold** [comment]
@yanliang567 When I first searched for it, I could find it, but after a while, I couldn't find it. However, if I query it by its ID, I can still get it.

**Comment by yanliang567** [comment]
does it reproduce for the only vector, or it reproduces for any other vectors?

**Comment by sevenold** [comment]
![image](https://github.com/milvus-io/milvus/assets/41443157/053a48d0-e152-4cd2-a4bd-defe3cfdb224)

**Comment by sevenold** [comment]
Some of the data comes from the migration from 1.1.1, some of the data was recorded after upgrading to 2.x. The data recorded in 2.x is all of this case. @yanliang567

**Comment by sevenold** [comment]
@yanliang567 I attempted to upgrade to version 2.3.2, but the same issue persisted. However, after manually creating a collection and importing all the data into it, the problem was resolved. I suspect that the issue was caused by a mixture of data from two different versions in the collection, which was preventing the search from working properly.

**Comment by yanliang567** [comment]
that could be the reason. could you just use the new collection?

**Comment by sevenold** [comment]
The new collection solved this problem
