### ISSUE TITLE
[Bug]: I upgraded the standalone version of Milvus using Docker Compose from version 2.28 to version 2.3.1 erro

### ISSUE THREAD

**Issue by master006** [milvus-io/milvus#27991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I upgraded the standalone version of Milvus using Docker Compose from version 2.2.8 to version 2.3.1, but only modified the image and reported an error during startup. May I ask what is the reason for this?

I noticed that version 2.2.8 of MiniO and version 2.3.1 of MiniO are using the same version and have not been upgraded. I searched online for a change in the MiniO data path (reference file: https://www.cnblogs.com/liangyy/p/17614441.html ）, and then modified the path, it can start normally, but the data query cannot be performed. May I ask what is the reason for this? Thank you.
![企业微信截图_1698400932154](https://github.com/milvus-io/milvus/assets/25217361/e53078e4-6e82-4dfc-a77d-aab66206d661)

But when I rolled back and started using milvus 2.2.8, I found that the 2.2.8 version couldn't start either, and an error was reported as follows:

![企业微信截图_16984015737755](https://github.com/milvus-io/milvus/assets/25217361/1a14f188-ef35-4578-9d84-eef024ab8556)
![企业微信截图_1698401587197](https://github.com/milvus-io/milvus/assets/25217361/29b308a5-afbf-465b-8fd3-f91b7f5a166a)

**Comment by xiaofan-luan** [comment]
you can remove the rocksmq dir and restart. this should automatically recovered

**Comment by master006** [comment]
Where is the rocksmq folder located?

**Comment by xiaofan-luan** [comment]
by default it's   path: /var/lib/milvus/rdb_data
