### ISSUE TITLE
[Bug]: =Timestamp lag too large lag(43h50m44.322s) max(24h0m0s): attempt #1: no available shard delegator found: service unavailable

### ISSUE THREAD

**Issue by master006** [milvus-io/milvus#27996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/25217361/53b9d976-cee0-4b60-b9e0-8e1df7efcb2d)

failed to search: attempt #0: failed to search/query delegator 78 for channel by-dev-rootcoord-dml_1_443770043000165365v1: fail to Search, QueryNode ID=78, reason=Timestamp lag too large lag(43h50m44.322s) max(24h0m0s): attempt #1: no available shard delegator found: service unavailable

What is the reason for encountering this problem? What is the solution? My version is a standalone version of Milvus 2.2.8 deployed using Docker Compose

Is there any way to adjust this lag time?

**Comment by xiaofan-luan** [comment]
please offer detailed server log.
especially datacoord and datanode log

**Comment by master006** [comment]
![image](https://github.com/milvus-io/milvus/assets/25217361/a47915ba-f859-4cd0-ac09-4d1dfde73506)
I am a standalone version of Milvus, and I am connected using ATTU. How do I view the logs?
Someone said this is the reason, but I can't find the rocksdb directory and file path

**Comment by xiaofan-luan** [comment]
> ![image](https://user-images.githubusercontent.com/25217361/278854845-a47915ba-f859-4cd0-ac09-4d1dfde73506.png) I am a standalone version of Milvus, and I am connected using ATTU. How do I view the logs? Someone said this is the reason, but I can't find the rocksdb directory and file path

remove the rocksmq dir should fix the problem.
by default the dir is 

rocksmq:
  # The path where the message is stored in rocksmq
  # please adjust in embedded Milvus: /tmp/milvus/rdb_data
  path: /var/lib/milvus/rdb_data
