### ISSUE TITLE
[DOC]server_config.yaml

### ISSUE THREAD

**Issue by lym777** [milvus-io/milvus#280]
## Report incorrect documentation
primary_path : /temp/milvus

**Location of incorrect documentation**
10

**Describe the problems or issues found in the documentation**
if data and meta store in /temp/milvus ，there is no data outside the docker

**Suggested fix for documentation**
primary_path : /opt/milvus

**Comment by JinHai-CN** [comment]
Do you mean the default primary path?

**Comment by lym777** [comment]
https://raw.githubusercontent.com/milvus-io/docs/master/assets/server_config.yaml
server_config.yaml downloaded via this link is different from the default server_config.yaml.

**Comment by JinHai-CN** [comment]
In fact, the data fold should be /var/lib/milvus

**Comment by jielinxu** [comment]
Changed the `primary_path` to /var/lib/milvus in v0.6.0.
