### ISSUE TITLE
Memory usage is not expected when searching with IVF_PQ

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#2803]
**Please state you issue using the following template and, most importantly, in English.**
files info:
```
➜  sift_10m_1024_128_l2 du -sh *               
1.2G	1587216155817005000
1.2G	1587216637678696000
1.2G	1587217123179194000
1.2G	1587217618071286000
876M	1587217984210009000

➜  1587217123179194000 ll
total 1.2G
-rwxrwxrwx 1 1026 users 1.1G 4月  19 13:40 1587217123179194000.rv
-rwxrwxrwx 1 1026 users  17M 4月  19 13:40 1587217123179194000.uid
-rwxrwxrwx 1 1026 users  89M 4月  19 19:20 1587295191439386000
-rwxrwxrwx 1 1026 users  17M 4月  19 13:40 bloom_filter
-rwxrwxrwx 1 1026 users    8 4月  19 13:40 deleted_docs

```
The size of index files is less than 1Gib, but server used more than 5Gib actually.

**Describe the bug**

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
0.10.1

**Screenshots**

**Additional context**

**Comment by shengjun1985** [comment]
[milvus verison]
0.10.1 cpu

[test case]
index_file_size = 1024
n = 1000000, d = 128
index_type = IVF_PQ, metric_type = IP, m =16, nlist = 1024
nq = 5, topK = 10, nprobe = 32

[operation and memory]
[operation and memory]
|             |   VIRT  |  RES  | SHR |  S | %CPU | %MEM |
| ------------| ------- | ------| --- | --- |----- | --- |
|start milvus | 1482456 | 41412 | 20372 | S |  0.7 | 0.3 |
|insert       | 1908456 | 571680| 21200 | S |  0.7 | 3.5 |
|create index | 2490116 | 643624| 21712 | S |  0.3 | 4.0 |
|preload      | 2563848 | 691788| 21840 | S |  0.3 | 4.2 |
|search       | 3211044 | 691788| 21840 | S |  0.3 | 4.2 |
|stop milvus  | | | | | | |
|start milvus | 1482456 | 139256 | 22184 | S | 0.3 | 0.9 |
|search       | 2417032 | 171620 | 22440 | S | 0.3 | 1.1 |

[file in disc]
-rw-r--r-- 1 zilliz zilliz 489M 7月  13 17:10 1594631436003991000.rv
-rw-r--r-- 1 zilliz zilliz 7.7M 7月  13 17:10 1594631436003991000.uid
-rw-r--r-- 1 zilliz zilliz  24M 7月  13 17:11 1594631438919658000
-rw------- 1 zilliz zilliz 2.7M 7月  13 17:10 bloom_filter
-rw-r--r-- 1 zilliz zilliz    8 7月  13 17:10 deleted_docs

My local test showed that the memory used in IVF_PQ had no problem.
Please confirm whether other operations affect.

**Comment by del-zhenwu** [comment]
with GPU version

**Comment by op-hunter** [comment]
I reproduce this issue on my local environment, this is a normal phenomenon, not a bug.
I will give more details tommrow.

**Comment by sahuang** [comment]
This is expected because in GPU, faiss will call `cudaHostAlloc`. The memory returned by this call will be considered as pinned memory by all CUDA contexts, not just the one that performed the allocation.
