### ISSUE TITLE
[Bug]: [Nightly]Nightly runs 20+ minutes slower than before

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#28036]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 7c9d24c
- Deployment mode(standalone or cluster):cluster standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Nightly runs 20+ minutes slower than before.
before(1h 30+min): https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/537/pipeline/237
slow(2h+): https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/538/pipeline/237

I found it started to become slower from e0222b2. So it may be that one of the following commits has an impact.
![image](https://github.com/milvus-io/milvus/assets/109071306/9ed102e6-ee69-478b-a696-c0d08463ced6)
![image](https://github.com/milvus-io/milvus/assets/109071306/984c511c-0479-4c5e-84cc-62a591b3d706)

### Expected Behavior

return normal

**Comment by yanliang567** [comment]
@NicoYuan1986 it seems that we have ~120 more tests in the nightly e2e...
/assign @NicoYuan1986
