### ISSUE TITLE
[Bug]: [mmap]The performance of IVF_FLAT index is severely degraded after turning on mmap

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#28037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.3.2
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Our test method is to compare the performance with and without mmap, given querynode resources.

After testing, we found that when using IVF_FLAT index, with the same amount of data, the performance of turning on mmap is about 10 times lower than that of not turning on mmap, and if the amount of data with mmap turned on is 4 times that of not turning on mmap, the performance is about 93 times lower than that of not turning on mmap.

|  base    |perf |performance degradation |    argo task |
|  ----  | ----  |----  |----  |
| mem  | 'RPS': 59.07,'RT_avg': 331.55, |1 |       fouramf-wgn8h |
| 1x  |'RPS': 5.07,'RT_avg': 3929.08, | 10 times lower performance |fouramf-b9td9 |
| 2x  |'RPS': 0.81,'RT_avg': 24759.91 |72 times lower performance |fouramf-85grz |
| 4x  | 'RPS': 0.63,'RT_avg': 31581.63, |93 times lower performance |fouramf-wfchl |

</b></b> 
Multiple tests were performed using the IVF_FLAT index with querynode resources of 1.5c6g and a baseline data size of 4 million 128-dimensional vectors and 2 column scalars of 4 million each. This is the maximum amount of data that can be loaded by a given 6g querynode without mmap turned on. 4x has 16m 128 dimensional vectors and 2 column scalars of 16m each.

### Expected Behavior

Performance should not degrade when mmap is turned on and the amount of data is equal to that without mmap. When mmap is turned on and the amount of data is more than twice as large as when it is not turned on, there is only a slight performance degradation.

### Anything else?

IVF_SQ8 indexes also suffer performance degradation when mmap is turned on.

**Comment by yah01** [comment]
After many tests:
- High concurrency will significantly downgrade the performance when enabled mmap, the reason is the system can't leverage the page cache well
- The performance improved much after using MADV_RANDOM like we did for HNSW
- With mmap, the IVF performance downgrades more than HNSW, and is not usable

So we are going to disable the mmap support for IVF index.

**Comment by bo-er** [comment]
> After many tests:
> 
> * High concurrency will significantly downgrade the performance when enabled mmap, the reason is the system can't leverage the page cache well
> * The performance improved much after using MADV_RANDOM like we did for HNSW
> * With mmap, the IVF performance downgrades more than HNSW, and is not usable
> 
> So we are going to disable the mmap support for IVF index.

Memory mapped I/O is a bad idea for any serious database since it has:
- Page fault overhead
- TLB miss overhead
- PTE construction overhead
