### ISSUE TITLE
[Enhancement]: Discontinued CentOS Support. New distribution version

### ISSUE THREAD

**Issue by AndreiPaulau** [milvus-io/milvus#28044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Hello Gents,

Small clarification question related to docs update as well.
I've briefly poke around the closed issues and find some info, but still would like to hear from you. =)

In 2.3.0 release you've mentioned about [Discontinued CentOS Support](https://milvus.io/docs/release_notes.md#Discontinued-CentOS-Support)

Could you please shed some light on new amazonlinux distribution, since they really differs.

Also would be great to hear about you plans over pining rpm packages back to releases.

Many thanks!

**Comment by xiaofan-luan** [comment]
We are actually thinking of using rocky linux as the successor of centos.
any thoughts on this @LoveEachDay @jiaoew1991

**Comment by AndreiPaulau** [comment]
JFYI
Recently I've created a table for my own purposes related to decommissioning of Centos7, might be handy for you as well
<html>
<body>


Distro | glibc | gcc | binutils | End Of Life (Active) | End Of Life (Security) | Provider Availability (Official sources)
-- | -- | -- | -- | -- | -- | --
centos:7 | 2.17 | 4.8.5 | 2.27 | Ended3y ago | 06/24 | AWS/GCP
amazonlinux:2 | 2.26 | 7.3 | 2.29 | 07/25 | 07/25 | AWS
rockylinux:8 | 2.28 | 8.5 | 2.30 | 06/24 | 06/29 | AWS/GCP/Azure
almalinux:8 | 2.28 | 8.5 | 2.30 | 05/24 | 05/29 | AWS/Azure
amazonlinux:2023 | 2.34 | 11.2 | 2.35 | 03/25 | 03/25 | AWS


</body>
</html>

**Comment by jiaoew1991** [comment]
hi @AndreiPaulau removed support for centos7 for the following reasons:
1. The versions of gcc, glibc, and other components are too old, causing many compilation environment issues.
2. centos7 has reached the end of its lifecycle many years ago.
In addition, the amazonlinux image is relatively new and supports software related to yum sources. It is similar to the rhel environment, so we decided to replace centos with amazonlinux.

**Comment by jiaoew1991** [comment]
@AndreiPaulau Do you think rockylinux:8 or rockylinux:9 is more appropriate? Version 8 will reach end of life in half a year 😅

**Comment by AndreiPaulau** [comment]
First of all, active support, not the security one.☺️ And smooth transition from 8 to 9 is possible in future, why not?
Just from the glibc perspective (my case) - compiled on rocky9, won’t work on rocky8…
