### ISSUE TITLE
[Bug]: Querycoord and datanode keep restart after etcd pod failure chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#28059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20231031-e88212ba-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):  kafka  
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/12268675/e1169185-c996-4852-aee6-1e777a8b6e86)

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-cron/detail/chaos-test-kafka-cron/8710/pipeline

log:
[artifacts-etcd-pod-failure-8710-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/13223046/artifacts-etcd-pod-failure-8710-pytest-logs.tar.gz)
[artifacts-etcd-pod-failure-8710-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/13223047/artifacts-etcd-pod-failure-8710-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
/assign @jiaoew1991 
PTAL

**Comment by smellthemoon** [comment]
Datanode starting DataCoord client and waiting for DataCoord state ok.
<img width="1289" alt="1" src="https://github.com/milvus-io/milvus/assets/64083300/a67157b3-c1f0-4577-9875-bb7ae2559bee">
Datanode got the correct DataCoord address. And DataCoord is successfully started.
<img width="955" alt="2" src="https://github.com/milvus-io/milvus/assets/64083300/6743582c-23b2-4d23-8639-e87aa152d19b">
<img width="950" alt="3" src="https://github.com/milvus-io/milvus/assets/64083300/91164eb0-0f32-46f9-8c70-43ff85a92e72">
so add some log when create client and get component states, #28160 
by the way, is it reproducible? @zhuwenxing

**Comment by zhuwenxing** [comment]
Not a stable reproduced issue.
It passed with image `master-20231104-bf2f62c1-amd64`

**Comment by zhuwenxing** [comment]
verified and not reproduced in master-20231218-95ada1b6
