### ISSUE TITLE
[Enhancement]: Optimize the problem of using clear text passwords in restful api token

### ISSUE THREAD

**Issue by weimingdiit** [milvus-io/milvus#28070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

curl --request GET \
    --url '${MILVUS_HOST}:${MILVUS_PORT}/v1/vector/collections' \
    --header 'Authorization: Bearer <TOKEN>' \
    --header 'accept: application/json' \
    --header 'content-type: application/json'

TOKEN need user_name:passwd

**Comment by xiaofan-luan** [comment]
you should enable tls for encryption if possible?

**Comment by xiaofan-luan** [comment]
but we can definitly support encoded password

**Comment by weimingdiit** [comment]
> but we can definitly support encoded password

thanks, I can see if tls can meet the needs, but using plaintext for restful passwd is really not suitable
