### ISSUE TITLE
[Enhancement]: Improve log prompt

### ISSUE THREAD

**Issue by WLBRich** [milvus-io/milvus#28076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

      Suppose the port number mapped at container startup is 19531, and the port number connected to the server is 19530. When the two do not match, this error occurs: “pymilvus.exceptions.MilvusException: <MilvusException:  (code=1, message=this version of sdk is incompatible with server, please downgrade your sdk or upgrade your server)> ", I think this post is misleading to developers.
      You can add other possible reasons to this log, such as incorrect host or port. The log should be as complete as possible, and then the developer can check one by one.

### Why is this needed?

I think this post is misleading to developers.

**Comment by xiaofan-luan** [comment]
this is a issue need to be fixed in pymilvus
