### ISSUE TITLE
[Enhancement]: Work around go=1.18 csv reader has no inputOffSet method

### ISSUE THREAD

**Issue by wayblink** [milvus-io/milvus#28081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

https://github.com/milvus-io/milvus/pull/27149 
CSV import support needs csv_reader inputOffSet method only supported in go>=1.19.
This break the limitation: milvus depends on go=1.18

**Comment by xiaofan-luan** [comment]
bump to 1.20 might be a option too?

**Comment by wayblink** [comment]
As master start using go 1.20. We may not need it in v2.3.4+
