### ISSUE TITLE
[SDK Enhancement]: add version info for this incompatible issue between sdk and milvus

### ISSUE THREAD

**Issue by yiwen92** [milvus-io/milvus#28085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

![img_v2_390cdfcf-591e-4bd0-a2eb-c26b9049a25g](https://github.com/milvus-io/milvus/assets/34636520/ed037b08-4d53-4c4b-a323-8453156be2f1)
When I see this error, it means the incompatible between sdk and milvus, so it's better to print more useful info e.g. explicit version info

### Why is this needed?

Without version info, it costs lots of time to resolve this problem

**Comment by xiaofan-luan** [comment]
python should always use 19530 while restful use 19531
