### ISSUE TITLE
[Bug]: 用Milvus Operator 在K8S上安装standalone之后 connections.connect 报错 timeout issue 

### ISSUE THREAD

**Issue by techgeniuswang** [milvus-io/milvus#28097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.3.2
- Deployment mode(standalone or cluster): standalone on K8S
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): v2.3.2
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 4/8G
- GPU: 
- Others:
```

### Current Behavior

在K8S上安装完standalone版本后，用python 连接的时候，出现timeout

### Expected Behavior

希望python的能正常连接。

### Steps To Reproduce

```markdown
启动minikube 
root@milvus:/data/medium/milvus# minikube start --force
😄  minikube v1.31.2 on Ubuntu 20.04
❗  minikube skips various validations when --force is supplied; this may lead to unexpected behavior
✨  Using the docker driver based on existing profile
🛑  The "docker" driver should not be used with root privileges. If you wish to continue as root, use --force.
💡  If you are running minikube within a VM, consider using --driver=none:
📘    https://minikube.sigs.k8s.io/docs/reference/drivers/none/
💡  Tip: To remove this root owned cluster, run: sudo minikube delete
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🤷  docker "minikube" container is missing, will recreate.
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...
🐳  Preparing Kubernetes v1.27.4 on Docker 24.0.4 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring bridge CNI (Container Networking Interface) ...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner
💡  kubectl not found. If you need it, try: 'minikube kubectl -- get pods -A'
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
root@milvus:/data/medium/milvus# 

查看集群状态：
root@milvus:/data/medium/milvus# minikube status
minikube
type: Control Plane
host: Running
kubelet: Running
apiserver: Running
kubeconfig: Configured

kubectl不是单独安装的，是由minikube 配置的，所以我这样查看集群状态。

**但是此时有个很诡异的问题就是DNS在minikube启动之后失效了。**

root@milvus:/data/medium/milvus#minikube kubectl -- cluster-info
Error caching kubectl: download failed: https://dl.k8s.io/release/v1.27.4/bin/linux/amd64/kubectl?checksum=file:https://dl.k8s.io/release/v1.27.4/bin/linux/amd64/kubectl.sha256: 
getter: &{Ctx:context.Background Src:https://dl.k8s.io/release/v1.27.4/bin/linux/amd64/kubectl?checksum=file:
https://dl.k8s.io/release/v1.27.4/bin/linux/amd64/kubectl.sha256 Dst:/root/.minikube/cache/linux/amd64/v1.27.4/kubectl.download Pwd: Mode:2 Umask:---------- Detectors:
[0x3f9c8a8 0x3f9c8a8 0x3f9c8a8 0x3f9c8a8 0x3f9c8a8 0x3f9c8a8 0x3f9c8a8] Decompressors:map[bz2:0xc0004d1f10 gz:0xc0004d1f18 tar:0xc0004d1ec0 tar.bz2:
0xc0004d1ed0 tar.gz:0xc0004d1ee0 tar.xz:0xc0004d1ef0 tar.zst:0xc0004d1f00 tbz2:0xc0004d1ed0 tgz:0xc0004d1ee0 txz:0xc0004d1ef0 tzst:0xc0004d1f00 xz:0xc0004d1f20 zip:0xc0004d1f30 zst:
0xc0004d1f28] Getters:map[file:0xc000e20c60 http:0xc000e0a320 https:0xc000e0a370] Dir:false ProgressListener:0x3f579a0 Insecure:false DisableSymlinks:false Options:[0x12d0880]}: 
invalid checksum: Error downloading checksum file: Get "https://dl.k8s.io/release/v1.27.4/bin/linux/amd64/kubectl.sha256": dial tcp: lookup dl.k8s.io on [::1]:53: read udp [::1]:45520->[::1]:53: read: connection refused

**此时一些大站ping不通**

/etc/resolv.conf文件不存在，之前也没有特意检查过。
root@milvus:/data/medium/milvus# cat /etc/resolv.conf
cat: /etc/resolv.conf: No such file or directory

检查 systemd-resolved 服务是否正在运行
root@milvus:/data/medium/milvus# systemctl status systemd-resolved
● systemd-resolved.service - Network Name Resolution
     Loaded: loaded (/lib/systemd/system/systemd-resolved.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2023-10-31 06:17:56 UTC; 52min ago
       Docs: man:systemd-resolved.service(8)
             https://www.freedesktop.org/wiki/Software/systemd/resolved
             https://www.freedesktop.org/wiki/Software/systemd/writing-network-configuration-managers
             https://www.freedesktop.org/wiki/Software/systemd/writing-resolver-clients
    Process: 854 ExecStart=/lib/systemd/systemd-resolved (code=exited, status=226/NAMESPACE)
   Main PID: 854 (code=exited, status=226/NAMESPACE)

Oct 31 06:17:56 milvus systemd[1]: systemd-resolved.service: Scheduled restart job, restart counter is at 5.
Oct 31 06:17:56 milvus systemd[1]: Stopped Network Name Resolution.
Oct 31 06:17:56 milvus systemd[1]: systemd-resolved.service: Start request repeated too quickly.
Oct 31 06:17:56 milvus systemd[1]: systemd-resolved.service: Failed with result 'exit-code'.
Oct 31 06:17:56 milvus systemd[1]: Failed to start Network Name Resolution.

查看 systemd-resolved 服务的日志
root@milvus:/data/medium/milvus# journalctl -xe -u systemd-resolved
Journal file /var/log/journal/8d85be8d7e71400f9d2e400f4bb32bd6/system.journal is truncated, ignoring file.
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- An ExecStart= process belonging to unit systemd-resolved.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 226.
Oct 31 06:17:56 milvus systemd[1]: systemd-resolved.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit systemd-resolved.service has entered the 'failed' state with result 'exit-code'.
Oct 31 06:17:56 milvus systemd[1]: Failed to start Network Name Resolution.
-- Subject: A start job for unit systemd-resolved.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit systemd-resolved.service has finished with a failure.
-- 
-- The job identifier is 284 and the job result is failed.
Oct 31 06:17:56 milvus systemd[1]: systemd-resolved.service: Scheduled restart job, restart counter is at 5.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Automatic restarting of the unit systemd-resolved.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Oct 31 06:17:56 milvus systemd[1]: Stopped Network Name Resolution.
-- Subject: A stop job for unit systemd-resolved.service has finished
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A stop job for unit systemd-resolved.service has finished.
-- 
-- The job identifier is 292 and the job result is done.
Oct 31 06:17:56 milvus systemd[1]: systemd-resolved.service: Start request repeated too quickly.
Oct 31 06:17:56 milvus systemd[1]: systemd-resolved.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit systemd-resolved.service has entered the 'failed' state with result 'exit-code'.
Oct 31 06:17:56 milvus systemd[1]: Failed to start Network Name Resolution.
-- Subject: A start job for unit systemd-resolved.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit systemd-resolved.service has finished with a failure.
-- 
-- The job identifier is 292 and the job result is failed.



查看一下 /etc/systemd/resolved.conf 文件内容

root@milvus:/data/medium/milvus# cat /etc/systemd/resolved.conf
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.
#
# Entries in this file show the compile time defaults.
# You can change settings by editing this file.
# Defaults can be restored by simply deleting this file.
#
# See resolved.conf(5) for details

[Resolve]
#DNS=
#FallbackDNS=
#Domains=
#LLMNR=no
#MulticastDNS=no
#DNSSEC=no
#DNSOverTLS=no
#Cache=no-negative
#DNSStubListener=yes
#ReadEtcHosts=yes
root@milvus:/data/medium/milvus# 

重建 resolv.conf 并使它生效
root@milvus:/data/medium/milvus# systemctl restart systemd-resolved


此时ping一些大站都能ping通

现在再查看集群的状态
root@milvus:/data/medium/milvus# minikube kubectl -- cluster-info
Kubernetes control plane is running at https://192.168.49.2:8443
CoreDNS is running at https://192.168.49.2:8443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

查看命名空间中的 Pods 
root@milvus:/data/medium/milvus# minikube kubectl -- get po -A
NAMESPACE     NAME                               READY   STATUS    RESTARTS      AGE
kube-system   coredns-5d78c9869d-lp9vv           1/1     Running   0             53m
kube-system   etcd-minikube                      1/1     Running   0             53m
kube-system   kube-apiserver-minikube            1/1     Running   0             53m
kube-system   kube-controller-manager-minikube   1/1     Running   0             53m
kube-system   kube-proxy-c4kf4                   1/1     Running   0             53m
kube-system   kube-scheduler-minikube            1/1     Running   0             53m
kube-system   storage-provisioner                1/1     Running   1 (53m ago)   53m
```

### Milvus Log

log里面error挺多的。

[my-release-milvus-standalone.log](https://github.com/milvus-io/milvus/files/13233648/my-release-milvus-standalone.log)

**Comment by techgeniuswang** [comment]
部分内容超出长度了，这里补上哈。
查看StorageClass
root@milvus:/data/medium/milvus# minikube kubectl -- get sc
NAME                 PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
standard (default)   k8s.io/minikube-hostpath   Delete          Immediate           false                  59m


安装 cert-manager

root@milvus:/data/medium/milvus# 
root@milvus:/data/medium/milvus# minikube kubectl -- apply -f https://github.com/jetstack/cert-manager/releases/download/v1.5.3/cert-manager.yaml
customresourcedefinition.apiextensions.k8s.io/certificaterequests.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/certificates.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/challenges.acme.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/clusterissuers.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/issuers.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/orders.acme.cert-manager.io created
namespace/cert-manager created
serviceaccount/cert-manager-cainjector created
serviceaccount/cert-manager created
serviceaccount/cert-manager-webhook created
clusterrole.rbac.authorization.k8s.io/cert-manager-cainjector created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-issuers created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-clusterissuers created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-certificates created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-orders created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-challenges created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-ingress-shim created
clusterrole.rbac.authorization.k8s.io/cert-manager-view created
clusterrole.rbac.authorization.k8s.io/cert-manager-edit created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-approve:cert-manager-io created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-certificatesigningrequests created
clusterrole.rbac.authorization.k8s.io/cert-manager-webhook:subjectaccessreviews created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-cainjector created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-issuers created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-clusterissuers created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-certificates created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-orders created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-challenges created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-ingress-shim created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-approve:cert-manager-io created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-certificatesigningrequests created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-webhook:subjectaccessreviews created
role.rbac.authorization.k8s.io/cert-manager-cainjector:leaderelection created
role.rbac.authorization.k8s.io/cert-manager:leaderelection created
role.rbac.authorization.k8s.io/cert-manager-webhook:dynamic-serving created
rolebinding.rbac.authorization.k8s.io/cert-manager-cainjector:leaderelection created
rolebinding.rbac.authorization.k8s.io/cert-manager:leaderelection created
rolebinding.rbac.authorization.k8s.io/cert-manager-webhook:dynamic-serving created
service/cert-manager created
service/cert-manager-webhook created
deployment.apps/cert-manager-cainjector created
deployment.apps/cert-manager created
deployment.apps/cert-manager-webhook created
mutatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook created
validatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook created

查看cert的安装情况
root@milvus:/data/medium/milvus# minikube kubectl -- get pods -n cert-manager
NAME                                       READY   STATUS    RESTARTS   AGE
cert-manager-8457df4d9c-qntxq              1/1     Running   0          66s
cert-manager-cainjector-7d7c8b7fbb-js95t   1/1     Running   0          66s
cert-manager-webhook-698b6fbdc7-brrbx      1/1     Running   0          66s

安装Milvus Operator
root@milvus:/data/medium/milvus# 
root@milvus:/data/medium/milvus# minikube kubectl -- apply -f https://raw.githubusercontent.com/zilliztech/milvus-operator/main/deploy/manifests/deployment.yaml
namespace/milvus-operator created
serviceaccount/milvus-operator-checker created
serviceaccount/milvus-operator created
customresourcedefinition.apiextensions.k8s.io/milvusclusters.milvus.io created
customresourcedefinition.apiextensions.k8s.io/milvuses.milvus.io created
customresourcedefinition.apiextensions.k8s.io/milvusupgrades.milvus.io created
clusterrole.rbac.authorization.k8s.io/milvus-operator-checker-role created
clusterrole.rbac.authorization.k8s.io/milvus-operator-manager-role created
clusterrolebinding.rbac.authorization.k8s.io/milvus-operator-checker-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/milvus-operator-manager-rolebinding created
role.rbac.authorization.k8s.io/milvus-operator-leader-election-role created
rolebinding.rbac.authorization.k8s.io/milvus-operator-leader-election-rolebinding created
service/milvus-operator-metrics-service created
service/milvus-operator-webhook-service created
deployment.apps/milvus-operator created
job.batch/milvus-operator-checker created
mutatingwebhookconfiguration.admissionregistration.k8s.io/milvus-operator-mutating-webhook-configuration created
validatingwebhookconfiguration.admissionregistration.k8s.io/milvus-operator-validating-webhook-configuration created

查看Milvus Operator 运行状态
root@milvus:/data/medium/milvus# minikube kubectl -- get pods -n milvus-operator 
NAME                               READY   STATUS      RESTARTS   AGE
milvus-operator-6f7bc67846-vwmtp   1/1     Running     0          90s
milvus-operator-checker-xxg6r      0/1     Completed   0          90s


安装 Install Milvus standalone， 这一步大概执行了两分钟
root@milvus:/data/medium/milvus# minikube kubectl -- apply -f https://raw.githubusercontent.com/zilliztech/milvus-operator/main/config/samples/milvus_default.yaml

milvus.milvus.io/my-release created


查看Milvus standalone
root@milvus:/data/medium/milvus# minikube kubectl -- get milvus my-release -o yaml
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"milvus.io/v1beta1","kind":"Milvus","metadata":{"annotations":{},"name":"my-release","namespace":"default"}}
    milvus.io/dependency-values-merged: "true"
    milvus.io/pod-service-label-added: "true"
  creationTimestamp: "2023-10-31T07:59:21Z"
  finalizers:
  - milvus.milvus.io/finalizer
  generation: 1
  labels:
    milvus.io/operator-version: 0.8.4
  name: my-release
  namespace: default
  resourceVersion: "6339"
  uid: cae1bc26-bf27-451f-8b9a-5f5085947bac
spec:
  components:
    disableMetric: false
    image: milvusdb/milvus:v2.3.2
    imageUpdateMode: rollingUpgrade
    metricInterval: ""
    paused: false
    standalone:
      paused: false
      replicas: 1
      serviceType: ClusterIP
  config: {}
  dependencies:
    etcd:
      endpoints:
      - my-release-etcd.default:2379
      external: false
      inCluster:
        deletionPolicy: Retain
        values:
          auth:
            rbac:
              enabled: false
          autoCompactionMode: revision
          autoCompactionRetention: "1000"
          enabled: true
          extraEnvVars:
          - name: ETCD_QUOTA_BACKEND_BYTES
            value: "4294967296"
          - name: ETCD_HEARTBEAT_INTERVAL
            value: "500"
          - name: ETCD_ELECTION_TIMEOUT
            value: "2500"
          image:
            pullPolicy: IfNotPresent
            repository: milvusdb/etcd
            tag: 3.5.5-r2
          livenessProbe:
            enabled: true
            timeoutSeconds: 10
          name: etcd
          pdb:
            create: false
          persistence:
            accessMode: ReadWriteOnce
            enabled: true
            size: 10Gi
            storageClass: null
          readinessProbe:
            enabled: true
            periodSeconds: 20
            timeoutSeconds: 10
          replicaCount: 1
          service:
            peerPort: 2380
            port: 2379
            type: ClusterIP
    kafka:
      external: false
    msgStreamType: rocksmq
    natsmq:
      persistence:
        persistentVolumeClaim:
          spec: null
    pulsar:
      endpoint: ""
      external: false
    rocksmq:
      persistence:
        persistentVolumeClaim:
          spec: null
    storage:
      endpoint: my-release-minio.default:9000
      external: false
      inCluster:
        deletionPolicy: Retain
        values:
          accessKey: minioadmin
          bucketName: milvus-bucket
          enabled: true
          existingSecret: ""
          gcsgateway:
            enabled: false
            gcsKeyJson: /etc/credentials/gcs_key.json
            projectId: ""
            replicas: 1
          iamEndpoint: ""
          image:
            pullPolicy: IfNotPresent
            tag: RELEASE.2023-03-20T20-16-18Z
          livenessProbe:
            enabled: true
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          mode: standalone
          name: minio
          persistence:
            accessMode: ReadWriteOnce
            enabled: true
            existingClaim: ""
            size: 500Gi
            storageClass: null
          podDisruptionBudget:
            enabled: false
          readinessProbe:
            enabled: true
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          region: ""
          resources:
            requests:
              memory: 2Gi
          rootPath: file
          secretKey: minioadmin
          service:
            port: 9000
            type: ClusterIP
          startupProbe:
            enabled: true
            failureThreshold: 60
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          useIAM: false
          useVirtualHost: false
      secretRef: my-release-minio
      type: MinIO
  hookConfig: null
  mode: standalone
status:
  componentsDeployStatus:
    standalone:
      generation: 1
      image: milvusdb/milvus:v2.3.2
      status:
        availableReplicas: 1
        conditions:
        - lastTransitionTime: "2023-10-31T08:01:47Z"
          lastUpdateTime: "2023-10-31T08:01:47Z"
          message: Deployment has minimum availability.
          reason: MinimumReplicasAvailable
          status: "True"
          type: Available
        - lastTransitionTime: "2023-10-31T08:01:05Z"
          lastUpdateTime: "2023-10-31T08:01:47Z"
          message: ReplicaSet "my-release-milvus-standalone-6d8744d5f" has successfully
            progressed.
          reason: NewReplicaSetAvailable
          status: "True"
          type: Progressing
        observedGeneration: 1
        readyReplicas: 1
        replicas: 1
        updatedReplicas: 1
  conditions:
  - lastTransitionTime: "2023-10-31T08:01:05Z"
    message: Etcd endpoints is healthy
    reason: EtcdReady
    status: "True"
    type: EtcdReady
  - lastTransitionTime: "2023-10-31T08:00:25Z"
    reason: StorageReady
    status: "True"
    type: StorageReady
  - lastTransitionTime: "2023-10-31T07:59:56Z"
    message: MsgStream is ready
    reason: MsgStreamReady
    status: "True"
    type: MsgStreamReady
  - lastTransitionTime: "2023-10-31T08:01:51Z"
    message: All Milvus components are healthy
    reason: ReasonMilvusHealthy
    status: "True"
    type: MilvusReady
  - lastTransitionTime: "2023-10-31T08:01:51Z"
    message: Milvus components are all updated
    reason: MilvusComponentsUpdated
    status: "True"
    type: MilvusUpdated
  endpoint: my-release-milvus.default:19530
  ingress:
    loadBalancer: {}
  observedGeneration: 1
  replicas:
    standalone: 1
  status: Healthy
root@milvus:/data/medium/milvus# 


再查看下全部的 minikube kubectl -- get po -A
root@milvus:/data/medium/milvus# minikube kubectl -- get po -A
NAMESPACE         NAME                                           READY   STATUS    RESTARTS      AGE
cert-manager      cert-manager-8457df4d9c-qntxq                  1/1     Running   0             17m
cert-manager      cert-manager-cainjector-7d7c8b7fbb-js95t       1/1     Running   0             17m
cert-manager      cert-manager-webhook-698b6fbdc7-brrbx          1/1     Running   0             17m
default           my-release-etcd-0                              1/1     Running   0             5m45s
default           my-release-milvus-standalone-6d8744d5f-ztqhj   1/1     Running   0             4m3s
default           my-release-minio-694f47c966-v59lt              1/1     Running   0             5m45s
kube-system       coredns-5d78c9869d-lp9vv                       1/1     Running   0             84m
kube-system       etcd-minikube                                  1/1     Running   0             84m
kube-system       kube-apiserver-minikube                        1/1     Running   0             84m
kube-system       kube-controller-manager-minikube               1/1     Running   0             84m
kube-system       kube-proxy-c4kf4                               1/1     Running   0             84m
kube-system       kube-scheduler-minikube                        1/1     Running   0             84m
kube-system       storage-provisioner                            1/1     Running   1 (84m ago)   84m
milvus-operator   milvus-operator-6f7bc67846-vwmtp               1/1     Running   0             15m


查看端口的监听情况
root@milvus:/data/medium/milvus# nc -zv localhost 19530
nc: connect to localhost port 19530 (tcp) failed: Connection refused

root@milvus:/data/medium/milvus# nc -zv localhost 9091
nc: connect to localhost port 9091 (tcp) failed: Connection refused

root@milvus:/data/medium/milvus# netstat -tuln | grep LISTEN
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:33403         0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:32768         0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:32769         0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:32770         0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:32771         0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:32772         0.0.0.0:*               LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN

**Comment by techgeniuswang** [comment]
我遇到的这个问题和 https://github.com/milvus-io/milvus/issues/1664 很接近。

和 https://stackoverflow.com/questions/74347672/cant-connect-to-milvus-using-pymilvus-inside-docker-milvusexception-code-2 也非常类似，这不过这里有人提到 pymilvus 降级到2.2.0之后能解决问题。我试过pymilvus 降级到2.2.0，我这里无效。

**Comment by techgeniuswang** [comment]
后来还尝试过用helm在K8S上安装standalone，执行到 这一步会一直没有返回。后来重启电脑之后，能有返回。但是python的连接 依然timeout

minikube kubectl -- get pod my-release-by-helm-milvus-standalone-6c6fb46756-dflhm --template='{{(index (index .spec.containers 0).ports 0).containerPort}}{{"\n"}}'19530

**Comment by yanliang567** [comment]
@techgeniuswang according to the logs, I see milvus service is ready to serve since 2023/11/01 02:42:28.979, and there are no connect requests received since then.  could you please double check the network between milvus clients and milvus server is accessable?
[2023/11/01 02:42:28.979 +00:00] [DEBUG] [proxy/service.go:596] ["init Proxy done"]
---Milvus Proxy successfully initialized and ready to serve!---
[2023/11/01 02:42:28.979 +00:00] [DEBUG] [proxy/service.go:370] ["init Proxy server done"]

/assign @techgeniuswang 
/unassign

**Comment by techgeniuswang** [comment]
fixed this issue by adjust ip/port
