### ISSUE TITLE
[Bug]: After using it for a period of time, rootcoord will report error="collection not found" when restarting.

### ISSUE THREAD

**Issue by StandardStudent** [milvus-io/milvus#28104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.3
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus:2.2.6
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 1core1Gi
- GPU: 
- Others:
```

### Current Behavior

When rootcoord restart, i see this log
![image](https://github.com/milvus-io/milvus/assets/29202679/83d5dca8-4572-42a5-aa62-517a534d5f39)
then i check milvus mysql database, and see this
![image](https://github.com/milvus-io/milvus/assets/29202679/0443a9c4-7cb8-4315-93c3-8c40d5be56d8)
i only insert data to milvus and query them , don't know why this kind of data had built

i build milvus on kubernetes, use kafka and mysql from aws cloud

could you please tell me is this a bug? update to the latest version could help?

### Expected Behavior

restart rootcoord correct

**Comment by xiaofan-luan** [comment]
please upgrade to 2.2.14 or 2.3.2 and this seems to be all fixed bugs
