### ISSUE TITLE
There are two links dead in README

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#2810]
**Please state you issue using the following template and, most importantly, in English.**
There are two links dead in README

**Location of incorrect documentation**
https://github.com/milvus-io/milvus

**Describe the problems or issues found in the documentation**
These two links are dead.
https://www.milvus.io/docs/about_milvus/overview.md
https://www.milvus.io/docs/guides/get_started/example_code.md

**Steps taken to verify documentation is incorrect**
List any steps you have taken:

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.

---

**Comment by PahudPlus** [comment]
- https://www.milvus.io/docs/overview.md
- https://www.milvus.io/docs/example_code.md
