### ISSUE TITLE
FAQs in offical website aren't up-to-date

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#2811]
**Please state you issue using the following template and, most importantly, in English.**
https://www.milvus.io/docs/v0.10.0/performance_faq.md
https://www.milvus.io/docs/v0.10.0/product_faq.md
https://www.milvus.io/docs/v0.10.0/operational_faq.md

These FAQs are for milvusv0.6.0, are too old to follow

**Comment by PahudPlus** [comment]
Updated.
