### ISSUE TITLE
[Bug]: 'Collection' object has no attribute 'properties'. Did you mean: 'set_properties'?

### ISSUE THREAD

**Issue by peilongchencc** [milvus-io/milvus#28116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.3.2
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.2
- OS(Ubuntu or CentOS): Ubuntu 18.4
- CPU/Memory: 
- GPU: 
- Others:
```

I installed Milvus v2.3.2 following the **Install Milvus Standalone with Docker Compose (CPU)** documentation.The link is:

```txt
https://milvus.io/docs/install_standalone-docker.md
```

### Current Behavior

When I run the following two pieces of code sequentially, it gives me the error message `AttributeError: 'Collection' object has no attribute 'properties'. Did you mean: 'set_properties'?` What should I do?

test_set_prop.py:
```python
from pymilvus import connections, Collection, FieldSchema, CollectionSchema, DataType
connections.connect(host='localhost', port='19530')
fields = [
    FieldSchema("film_id", DataType.INT64, is_primary=True),
    FieldSchema("films", dtype=DataType.FLOAT_VECTOR, dim=128)
    ]
schema = CollectionSchema(fields=fields)
collection = Collection("test_set_properties", schema)
collection.set_properties({"collection.ttl.seconds": 60})
```

test_get_prop.py:
```python
from pymilvus import connections, Collection, FieldSchema, CollectionSchema, DataType
connections.connect(host='localhost', port='19530')

collection = Collection("test_set_properties")
print(f"the name of collection is :{collection.name}")
print(f"the expiration time of collection is :{collection.properties}")
```

Error Information:
```txt
the name of collection is :test_set_properties
Traceback (most recent call last):
  File "/milvus_use/test_get_prop.py", line 6, in <module>
    print(f"the expiration time of collection is :{collection.properties}")
AttributeError: 'Collection' object has no attribute 'properties'. Did you mean: 'set_properties'?
```

### Expected Behavior

Please tell me whether the expiration time has been set successfully and how to correctly check the expiration time?

### Steps To Reproduce

```markdown
1. run test_set_prop.py
2. run test_get_prop.py
```

### Milvus Log

None

### Anything else?

None

**Comment by peilongchencc** [comment]
@xiaofan-luan 
Hi, I saw a similar issue in #21802 , but my system version, Milvus version and PyMilvus version are different from his. However, I encountered the same `AttributeError: 'Collection' object has no attribute 'properties'. Did you mean: 'set_properties'?` error. Please help me🙏🙏🙏

**Comment by xiaofan-luan** [comment]
/assign @SimFG 
could you help on this?

**Comment by SimFG** [comment]
@peilongchencc 
if you want to get the collection properties, you can try to use the `describe` method of the collection. like:
```
print(hello_milvus.describe())
print(hello_milvus.describe().get("properties"))
```

**Comment by peilongchencc** [comment]
@SimFG @xiaofan-luan 
Thank you, this resolved my issue. Here is my modified code:

test_get_prop.py:
```python
from pymilvus import connections, Collection, FieldSchema, CollectionSchema, DataType
connections.connect(host='localhost', port='19530')

collection = Collection("test_set_properties")
print(f"the name of collection is :{collection.name}")

expiration_time = collection.describe().get("properties")
print(f"the expiration time of collection is :{expiration_time}")
```

The content displayed in the terminal is as follows:

```txt
the name of collection is :test_set_properties
the expiration time of collection is :[key: "collection.ttl.seconds"
value: "60"
]
```
