### ISSUE TITLE
[Bug]: Restful Endpoints doesn't work at all

### ISSUE THREAD

**Issue by BioNuc** [milvus-io/milvus#28133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.2
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): Restful API
```

### Current Behavior

When I try any of the endpoints in the documentation, I get 404
This is because urls stated are not correct
Parameters are not correct
Returned Response is not correct

### Expected Behavior

We need to sync the documentation with the actual implementation as it is rocket science now to use the service without making guesses and corrections

**Comment by SimFG** [comment]
Can you give a example?

**Comment by xiaofan-luan** [comment]
please give more details about your usage so we could help, including your server version, your restful api code and which document you refered to. Thanks
Thanks.

**Comment by BioNuc** [comment]
Hey,

One example is this endpoint
https://milvus.io/api-reference/restful/v2.3.x/Vector%20Operations/search.md

The endpoint stated is available at /v1/vector/search but when I tried this on Milvus Standalone version (Installed via Docker), I received 404 error and I found the endpoint available at /v1/search only and the parameters are not complying with the documentation as well

I installed Milvus via this guide instructions
https://milvus.io/docs/install_standalone-docker.md
Then used its REST endpoints instead of gRPC and connected to the proper port for that

Milvus version is 2.3.x as stated on the corresponding endpoints' documentation

Thanks

**Comment by xiaofan-luan** [comment]
/assign @PowderLi 
any clue on this?

**Comment by xiaofan-luan** [comment]
> Hey,
> 
> One example is this endpoint https://milvus.io/api-reference/restful/v2.3.x/Vector%20Operations/search.md
> 
> The endpoint stated is available at /v1/vector/search but when I tried this on Milvus Standalone version (Installed via Docker), I received 404 error and I found the endpoint available at /v1/search only and the parameters are not complying with the documentation as well
> 
> I installed Milvus via this guide instructions https://milvus.io/docs/install_standalone-docker.md Then used its REST endpoints instead of gRPC and connected to the proper port for that
> 
> Milvus version is 2.3.x as stated on the corresponding endpoints' documentation
> 
> Thanks

you are using 9091 port right?

**Comment by SimFG** [comment]
@BioNuc I follow the two documents to operate the milvus service, and don't found the error you met. The following are the steps I took:

```bash
➜ mkdir github-online
➜ cd github-online/
➜ wget https://github.com/milvus-io/milvus/releases/download/v2.3.2/milvus-standalone-docker-compose.yml -O docker-compose.yml
➜ docker-compose up -d
```

![image](https://github.com/milvus-io/milvus/assets/21985684/f19c7f43-9552-4538-96da-9f4d815338cf)

**Comment by BioNuc** [comment]
I tried things now on this port and it is working fine
Maybe I was using a wrong port

Sorry for the inconvenience

Thanks

**Comment by SimFG** [comment]
@BioNuc thanks your feedback, and i will close the issue.
