### ISSUE TITLE
Can you list the Milvus and Enterprise compatibility？

### ISSUE THREAD

**Issue by shiyu22** [milvus-io/milvus#2816]
## Report needed documentation

**Report needed documentation**
Can you list the Milvus and Enterprise compatibility？The Enterprise version used before is too old to display the amount of data.

**Describe the documentation you'd like**
For example:
milvus 0.7 -> em 0.1 
milvus 0.8 -> em 0.2 
milvus 0.9 -> em 0.3 
milvus 0.10 -> em 0.4

**Comment by shanghaikid** [comment]
https://github.com/milvus-io/www.milvus.io/issues/184 open the issue here, please close this one.
