### ISSUE TITLE
[Enhancement]: refactor segcore expr framework

### ISSUE THREAD

**Issue by zhagnlu** [milvus-io/milvus#28165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

refactor expr runtime and execute framework

**Comment by xiaofan-luan** [comment]
please give more details about the refactoring.
THanks

**Comment by mykittylover** [comment]
Is there a detailed design document here?

**Comment by xiaofan-luan** [comment]
@zhagnlu 
I think we need to put some of the documents here
