### ISSUE TITLE
[Bug]: The insert operation speed of milvus cluster is much slower than that of milvus stand-alone version.

### ISSUE THREAD

**Issue by yanxiaoqi932** [milvus-io/milvus#28172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1
- Deployment mode(standalone or cluster):standalone and cluster
- MQ type(rocksmq, pulsar or kafka): 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): ubuntu 20
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The insert operation speed of milvus cluster is much slower than that of milvus stand-alone version, I deploy milvus on a cluster which consists 3 machines by helm, but its insert operation is so slow that it needs 30 minutes to insert 1000000 entries, but milvus stand-alone only need 2 minutes.
The index creating speed of milvus is close for cluster and stand-alone.
My milvus module running normally on my cluster, I can't find the problem for a long time.

**Comment by xiaofan-luan** [comment]
Please try Milvus 2.3.2 instead if possible.
Should be much faster than 2.1 under most cases.

**Comment by yanliang567** [comment]
also please make sure the client and milvus server is in the same network to save the latency.
/assign @yanxiaoqi932 
/unassign

**Comment by yanxiaoqi932** [comment]
> also please make sure the client and milvus server is in the same network to save the latency.
> /assign @yanxiaoqi932 
> /unassign

yes，I test the insert operation on the  machine which is in the milvus cluster. Speak specifically, I run a benchmark named vector-db-benchmark on the machine, and find that the speed of upload is too slow, the benchmark need 30 minuts to insert 1000000 entries on the milvus cluster.

**Comment by yanxiaoqi932** [comment]
I run the benchmark on the machine included by milvus cluster, maybe the insert speed will be much slower while client and proxy on the same machine?

**Comment by yanxiaoqi932** [comment]
> Please try Milvus 2.3.2 instead if possible. Should be much faster than 2.1 under most cases.

Yes you are right, insert operation of milvus 2.3.2 is much faster than 2.1, my god! Milvus 2.3.2 only use 1 minutes to upload data while 2.1 need 30 minutes. It's crazy, thank you so much!
