### ISSUE TITLE
[Bug]: docker-compose-devcontainer is not exist in repo!

### ISSUE THREAD

**Issue by trukhinyuri** [milvus-io/milvus#28173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
docker-compose-devcontainer is not exist in repo!
{
    "name": "Milvus Distributed Dev Container Definition",
    "dockerComposeFile": ["./docker-compose-devcontainer.yml"],
    "service": "builder",
    "initializeCommand": "scripts/devcontainer.sh",
    "workspaceFolder": "/go/src/github.com/milvus-io/milvus",
    "remoteEnv": { "GOPROXY": "https://goproxy.cn" },
    "extensions": [
      "ms-vscode.cpptools",
      "golang.go"
    ]
}
```

### Current Behavior

docker-compose-devcontainer is not exist in repo!

### Expected Behavior

docker-compose-devcontainer exist in repo

**Comment by LoveEachDay** [comment]
@trukhinyuri You need to run `./scripts/devcontainers.sh up` which will automatically generate a `docker-compose-devcontainer.yml` for you.
