### ISSUE TITLE
[Enhancement]: disable auto balance when old node exist

### ISSUE THREAD

**Issue by weiliu1031** [milvus-io/milvus#28208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

during rolling upgrade between 2.2 and 2.3 in standalone mode, there's a period when querynode/datanode exists with both version 2.2 and version 2.3,   if we balance channel from version 2.2's data node to version 2.3's datanode, due to datanode with version 2.3 doesn't write delete msg to delta channel anymore,  and querynode with version 2.2 is still consume from delta channel to update it's `tsafe`. which cause a huge lag in `tSafe` and block all search/query until timeout in `waitTsafe`

### Why is this needed?

to solve the problems above, we add control to `auto balance` in datanode and querynode, `auto balance` is set to false by default, and after querycoord with version 2.3 start, it will start a groutine in background, and it will check whether there exist querynode with version 2.2,  if all old node down, it will set `auto balance` to `true`.

**Comment by xiaofan-luan** [comment]
it's might be more make sense to disable balance by a command?

**Comment by xiaofan-luan** [comment]
automatically make the decision might be very tricky under certain cases
