### ISSUE TITLE
[Bug]: 在K8s中用Helm安装mikvus，无法启动indexnode

### ISSUE THREAD

**Issue by Geapefurit** [milvus-io/milvus#28215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

当前K8s已经部署了一个Minio
现在用Helm部署一个Milvus，在部署时也允许安装milvus的charts中自带的minio，并且前缀为milvus（最终pod名字为milvus-minio-***），此时indexnode无法启动，报错
![ddee56a6da69ab8a89f55a3f1afd2da](https://github.com/milvus-io/milvus/assets/25075249/d5cb025b-d91a-435f-9452-8d5e775dffa2)

### Expected Behavior

按道理milvus自带安装的minio有前缀名称，向其他pod注入的env也是带milvus前缀的，理应不会混淆
不知道是不是环境变量或者配置解析错误

**Comment by xiaofan-luan** [comment]
<img width="1000" alt="image" src="https://github.com/milvus-io/milvus/assets/83447078/4a3b0eba-db2a-4a71-8df8-8f8c80445bf4">

seems to be a configuration issue.

**Comment by Geapefurit** [comment]
I guess this problem arises from handling environment variable prefixes.Becuase I have deployed other minio beside the minio of milvus

**Comment by xiaofan-luan** [comment]
> I guess this problem arises from handling environment variable prefixes.Becuase I have deployed other minio beside the minio of milvus

did you check SSL features?
if minio SSL enbaled/disabeld, milvus must match their requirment

**Comment by Geapefurit** [comment]
If I remove the default without prefix,then the milvus will start successfully.So the SSL config is right.

**Comment by Geapefurit** [comment]
I check the env in datanode pod like this
```Shell
MINIO_SERVICE_HOST=10.68.28.237
MINIO_PORT_9000_TCP_PORT=9000
MINIO_PORT_9000_TCP=tcp://10.68.28.237:9000
MILVUS_MINIO_PORT_9000_TCP_PORT=9000
MILVUS_MINIO_PORT_9000_TCP=tcp://10.68.84.171:9000
MILVUS_MINIO_PORT_9000_TCP_PROTO=tcp
MILVUS_MINIO_PORT=tcp://10.68.84.171:9000
MINIO_PORT_9000_TCP_PROTO=tcp
MINIO_PORT=tcp://10.68.28.237:9000
MILVUS_MINIO_SERVICE_PORT=9000
MINIO_SERVICE_PORT=9000
MINIO_PORT_9000_TCP_ADDR=10.68.28.237
MILVUS_MINIO_SERVICE_HOST=10.68.84.171
MINIO_SERVICE_PORT_HTTP=9000
MILVUS_MINIO_PORT_9000_TCP_ADDR=10.68.84.171
MILVUS_MINIO_SERVICE_PORT_HTTP=9000
```

So I guess there is something wrong with environment variable handling

**Comment by Geapefurit** [comment]
I check the env in datanode pod like this
```Shell
MINIO_SERVICE_HOST=10.68.28.237
MINIO_PORT_9000_TCP_PORT=9000
MINIO_PORT_9000_TCP=tcp://10.68.28.237:9000
MILVUS_MINIO_PORT_9000_TCP_PORT=9000
MILVUS_MINIO_PORT_9000_TCP=tcp://10.68.84.171:9000
MILVUS_MINIO_PORT_9000_TCP_PROTO=tcp
MILVUS_MINIO_PORT=tcp://10.68.84.171:9000
MINIO_PORT_9000_TCP_PROTO=tcp
MINIO_PORT=tcp://10.68.28.237:9000
MILVUS_MINIO_SERVICE_PORT=9000
MINIO_SERVICE_PORT=9000
MINIO_PORT_9000_TCP_ADDR=10.68.28.237
MILVUS_MINIO_SERVICE_HOST=10.68.84.171
MINIO_SERVICE_PORT_HTTP=9000
MILVUS_MINIO_PORT_9000_TCP_ADDR=10.68.84.171
MILVUS_MINIO_SERVICE_PORT_HTTP=9000
```

So I guess there is something wrong with environment variable handling

**Comment by Geapefurit** [comment]
Ok,thx!
I just want to think of a way for two minios to coexist!

**Comment by LoveEachDay** [comment]
You can install a minio cluster with a more specific name instead of `minio`.

**Comment by Geapefurit** [comment]
Thank you very much !!!
