### ISSUE TITLE
[Bug]: v2.3.0版本编译失败

### ISSUE THREAD

**Issue by shenfreedom233** [milvus-io/milvus#28251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.0
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

我们基于2.3.0的版本，执行命令./script/devcontainer.sh拉取开发镜像。进入milvusdb/milvus-env:gpu-ubuntu20.04-20230822-a64488a， 执行make命令进行编译。
【error】“/home/milvus/.conan/data/googleapis/cci.20221108/_/_/export/c”会报conan版本太低错误，我们对conan版本进行了升级后问题解决。
【error】arrow/11.0.0编译失败，提示boost库找不到。我们手动安装boost库后该问题解决。
【error】最后链接生成可执行程序时失败。报错信息：
libmilvus_storage.so: undefined reference  to 're2::RE2::Arg::parse_stringpiece(char const*, unsigned long, void*)
libmilvus_storage.so: undefined reference to 're2:RE2:Arg::parse_string(char const* unsigned long, void*)

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version: 2.3.0
> - Deployment mode(standalone or cluster):
> - MQ type(rocksmq, pulsar or kafka):    
> - SDK version(e.g. pymilvus v2.0.0rc2):
> - OS(Ubuntu or CentOS): Ubuntu 
> - CPU/Memory: 
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> 我们基于2.3.0的版本，执行命令./script/devcontainer.sh拉取开发镜像。进入milvusdb/milvus-env:gpu-ubuntu20.04-20230822-a64488a， 执行make命令进行编译。 【error】“/home/milvus/.conan/data/googleapis/cci.20221108/_/_/export/c”会报conan版本太低错误，我们对conan版本进行了升级后问题解决。 【error】arrow/11.0.0编译失败，提示boost库找不到。我们手动安装boost库后该问题解决。 【error】最后链接生成可执行程序时失败。报错信息： libmilvus_storage.so: undefined reference to 're2::RE2::Arg::parse_stringpiece(char const*, unsigned long, void*) libmilvus_storage.so: undefined reference to 're2:RE2:Arg::parse_string(char const* unsigned long, void*)
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

did you do install_deps.sh

**Comment by shenfreedom233** [comment]
是的，已经运行过 install_deps.sh脚本了的

**Comment by jiaoew1991** [comment]
The docker image of gpu version  is a little bit old, I will update it

**Comment by shenfreedom233** [comment]
为了解决这个问题，我们比对了2.3.0和2.3.2的版本差异，将2.3.2版本里internal\core\conanfile.py文件的部分更新同步到2.3.0上后，顺利编译成功，麻烦问一下，这种修改方式是否有风险？
同步部分：
    default_options = {
        "librdkafka:shared": True,
        "librdkafka:zstd": True,
        "librdkafka:sasl": False,
        "rocksdb:shared": True,
        "rocksdb:with_zstd": True,
        "arrow:parquet": True,
        "arrow:compute": True,
        "arrow:with_zstd": True,
        "arrow:shared": False,
        "arrow:with_jemalloc": True,
        "aws-sdk-cpp:text-to-speech": False,
        "aws-sdk-cpp:transfer": False,
        "gtest:build_gmock": False,
        "boost:without_locale": False,
        "glog:with_gflags": True,
        "glog:shared": True,
        "prometheus-cpp:with_pull": False,
        "fmt:header_only": True,
        "onetbb:tbbmalloc": False,
        "onetbb:tbbproxy": False,
        "openblas:shared": True,
        "openblas:dynamic_arch": True,
    }

**Comment by jiaoew1991** [comment]
> 为了解决这个问题，我们比对了2.3.0和2.3.2的版本差异，将2.3.2版本里internal\core\conanfile.py文件的部分更新同步到2.3.0上后，顺利编译成功，麻烦问一下，这种修改方式是否有风险？ 同步部分： default_options = { "librdkafka:shared": True, "librdkafka:zstd": True, "librdkafka:sasl": False, "rocksdb:shared": True, "rocksdb:with_zstd": True, "arrow:parquet": True, "arrow:compute": True, "arrow:with_zstd": True, "arrow:shared": False, "arrow:with_jemalloc": True, "aws-sdk-cpp:text-to-speech": False, "aws-sdk-cpp:transfer": False, "gtest:build_gmock": False, "boost:without_locale": False, "glog:with_gflags": True, "glog:shared": True, "prometheus-cpp:with_pull": False, "fmt:header_only": True, "onetbb:tbbmalloc": False, "onetbb:tbbproxy": False, "openblas:shared": True, "openblas:dynamic_arch": True, }

Looks like there's no problem.
