### ISSUE TITLE
[Bug]: More than 10 million data were loaded, causing the cluster to crash

### ISSUE THREAD

**Issue by mybabyiscue** [milvus-io/milvus#28259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Centos
- CPU/Memory: 
- GPU: 
- Others: master ：8cores/128g  slave*60:4cores/16g
```

### Current Behavior

20 million pieces of data are stored in the database, but when loading, it will cause the milvus cluster to crash. Checked environment cpu and kernel. No exception found
Checked mino's log as follows
![89cfc63d12bd521c62e452f562bd126](https://github.com/milvus-io/milvus/assets/96758134/941f547b-c46e-402c-97df-423f73c80ede)
![113ebd056f7975a32271268ca130109](https://github.com/milvus-io/milvus/assets/96758134/5f42e3ce-21b8-4067-89de-1e2936eae0dc)

**Comment by yanliang567** [comment]
@mybabyiscue which version of milvus are you running?  Could you please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @mybabyiscue 
/unassign

**Comment by mybabyiscue** [comment]
Using milvus2.2.13，
![image](https://github.com/milvus-io/milvus/assets/96758134/d528ed52-11bf-4889-aef7-783d3d4078e3)
This is the error log of proxy pod
The current cluster means that as soon as I load it, the entire connection is disconnected. I also tried loading small data without any problems.

**Comment by mybabyiscue** [comment]
Another problem is that after I installed milvus, port 19530 was unavailable. I need to configure it as nodeport to use it normally
![image](https://github.com/milvus-io/milvus/assets/96758134/d93e0c5c-491a-4de1-bf77-72e6e969e28e)

**Comment by yanliang567** [comment]
hi, we need full milvus logs to figure out what is going on for that collection, could you please share them?

**Comment by mybabyiscue** [comment]
[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/13292334/milvus-log.tar.gz)

OK

**Comment by yanliang567** [comment]
it seems that milvus pods lost the connection with the dependencies. @congqixia could you please double check the logs?
/assign @congqixia
