### ISSUE TITLE
[Bug]: Missing c++ monitoring about remote object storage

### ISSUE THREAD

**Issue by PowderLi** [milvus-io/milvus#28277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3
- Deployment mode(standalone or cluster): both
```

### Current Behavior

curl "http://${milvus_host}:9091/metrics" | grep milvus_storage
we find op_count, kv_size, request_latency, which are all from go monitoring.

### Expected Behavior

Add c++ monitoring about remote object storage

**Comment by xiaofan-luan** [comment]
@cydrain 
do we need to keep this issue.
