### ISSUE TITLE
[Bug]: one of the etcd list ip is disconnected, the datacoord server will stop refreshing configurations and crash

### ISSUE THREAD

**Issue by huluhaziqi** [milvus-io/milvus#28273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.14
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): java 2.2.9
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 16c24g
- GPU: 
- Others:
```

### Current Behavior

first i use ectd list contains 4 etcd ip . now one of the ips is disconnected, the datacoord server will not useful. when this happened when I insert data

### Expected Behavior

the ectd client could auto retry and load balance. and insert data to milvus is success

### Steps To Reproduce

```markdown
1、use client to insert milvus data
2、when the data is inserting, let one of the etcd ip disconnect (total 5 etcd ip)
3、now check the insert data, find that is failed. the datacoord is crash.
4、milvus manager is not useful now.
```

### Milvus Log

23922 {"level":"INFO","time":"2023/11/08 15:26:41.362 +08:00","caller":"config/etcd_source.go:155","message":"stop refreshing configurations"}
23923 {"level":"ERROR","time":"2023/11/08 15:26:47.929 +08:00","caller":"config/etcd_source.go:151","message":"can not pull configs","error":"context deadline exceeded","stack":"github.com/milvus-io/milvus/internal/config      .(*EtcdSource).refreshConfigurationsPeriodically\n\t/root/projects/friday-vecdb-compile/internal/config/etcd_source.go:151"}
23924 {"level":"INFO","time":"2023/11/08 15:26:47.929 +08:00","caller":"config/etcd_source.go:155","message":"stop refreshing configurations"}
23925 {"level":"INFO","time":"2023/11/08 15:26:49.410 +08:00","caller":"datacoord/services.go:792","message":"get recovery info request received","collectionID":445159665229656557,"partitionIDs":[]}
23926 {"level":"ERROR","time":"2023/11/08 15:26:58.329 +08:00","caller":"config/etcd_source.go:151","message":"can not pull configs","error":"context deadline exceeded","stack":"github.com/milvus-io/milvus/internal/config      .(*EtcdSource).refreshConfigurationsPeriodically\n\t/root/projects/friday-vecdb-compile/internal/config/etcd_source.go:151"}
23927 {"level":"INFO","time":"2023/11/08 15:26:58.329 +08:00","caller":"config/etcd_source.go:155","message":"stop refreshing configurations"}
23928 {"level":"INFO","time":"2023/11/08 15:26:59.613 +08:00","caller":"datacoord/services.go:792","message":"get recovery info request received","collectionID":445159665229656557,"partitionIDs":[]}
23929 {"level":"ERROR","time":"2023/11/08 15:27:01.325 +08:00","caller":"config/etcd_source.go:151","message":"can not pull configs","error":"context deadline exceeded","stack":"github.com/milvus-io/milvus/internal/config      .(*EtcdSource).refreshConfigurationsPeriodically\n\t/root/projects/friday-vecdb-compile/internal/config/etcd_source.go:151"}
23930 {"level":"INFO","time":"2023/11/08 15:27:01.325 +08:00","caller":"config/etcd_source.go:155","message":"stop refreshing configurations"}
23931 {"level":"ERROR","time":"2023/11/08 15:27:01.338 +08:00","caller":"config/etcd_source.go:151","message":"can not pull configs","error":"context deadline exceeded","stack":"github.com/milvus-io/milvus/internal/config      .(*EtcdSource).refreshConfigurationsPeriodically\n\t/root/projects/friday-vecdb-compile/internal/config/etcd_source.go:151"}
23932 {"level":"INFO","time":"2023/11/08 15:27:01.341 +08:00","caller":"config/etcd_source.go:155","message":"stop refreshing configurations"}
23933 {"level":"INFO","time":"2023/11/08 15:27:10.019 +08:00","caller":"datacoord/services.go:792","message":"get recovery info request received","collectionID":445159665229656557,"partitionIDs":[]}
23934 {"level":"WARN","time":"2023/11/08 15:27:10.591 +08:00","caller":"etcd/etcd_kv.go:729","message":"Slow etcd operation save","time spent":"30.000668598s","key":"milvus-prod-backup/meta/datacoord-meta/channel-cp/milvu      s-rootcoord-dml_2_444976245392701267v0"}
23935 {"level":"WARN","time":"2023/11/08 15:27:10.591 +08:00","caller":"datacoord/services.go:1427","message":"failed to UpdateChannelCheckpoint","vChannel":"milvus-rootcoord-dml_2_444976245392701267v0","error":"context d      eadline exceeded"}
23936 {"level":"WARN","time":"2023/11/08 15:27:10.591 +08:00","caller":"datacoord/metrics_info.go:169","message":"invalid metrics of DataNode was found","error":"context canceled"}
23937 {"level":"WARN","time":"2023/11/08 15:27:10.591 +08:00","caller":"datacoord/metrics_info.go:169","message":"invalid metrics of DataNode was found","error":"context canceled"}
23938 {"level":"WARN","time":"2023/11/08 15:27:10.591 +08:00","caller":"datacoord/metrics_info.go:169","message":"invalid metrics of DataNode was found","error":"context canceled"}

23983 {"level":"WARN","time":"2023/11/08 15:27:40.620 +08:00","caller":"retry/retry.go:44","message":"retry func failed","retry time":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
23984 {"level":"INFO","time":"2023/11/08 15:27:40.620 +08:00","caller":"datacoord/services.go:897","message":"received get flushed segments request","collectionID":445159665228148030,"partitionID":-1}
23985 {"level":"WARN","time":"2023/11/08 15:27:40.621 +08:00","caller":"grpcclient/client.go:368","message":"ClientBase ReCall grpc first call get error","role":"datanode","error":"err: rpc error: code = DeadlineExceeded       desc = context deadline exceeded\n, /root/projects/friday-vecdb-compile/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/root/projects/friday-vecdb-compile/internal/      util/grpcclient/client.go:367 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n/root/projects/friday-vecdb-compile/internal/distributed/datanode/client/client.go:206 github.com/milvus-      io/milvus/internal/distributed/datanode/client.(*Client).GetMetrics\n/root/projects/friday-vecdb-compile/internal/datacoord/metrics_info.go:167 github.com/milvus-io/milvus/internal/datacoord.(*Server).getDataNodeMet      rics\n/root/projects/friday-vecdb-compile/internal/datacoord/metrics_info.go:82 github.com/milvus-io/milvus/internal/datacoord.(*Server).getSystemInfoMetrics\n/root/projects/friday-vecdb-compile/internal/datacoord/s      ervices.go:1036 github.com/milvus-io/milvus/internal/datacoord.(*Server).GetMetrics\n/root/projects/friday-vecdb-compile/internal/distributed/datacoord/service.go:360 github.com/milvus-io/milvus/internal/distributed      /datacoord.(*Server).GetMetrics\n/root/projects/friday-vecdb-compile/internal/proto/datapb/data_coord.pb.go:6630 github.com/milvus-io/milvus/internal/proto/datapb._DataCoord_GetMetrics_Handler.func1\n/root/projects/      friday-vecdb-compile/internal/util/interceptor/server_id_interceptor.go:66 github.com/milvus-io/milvus/internal/util/interceptor.ServerIDValidationUnaryServerInterceptor.func1\n/root/go/pkg/mod/github.com/grpc-ecosy      stem/go-grpc-middleware@v1.3.0/chain.go:25 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n"}
23986 {"level":"WARN","time":"2023/11/08 15:27:40.621 +08:00","caller":"datacoord/metrics_info.go:169","message":"invalid metrics of DataNode was found","error":"context deadline exceeded"}
23987 {"level":"WARN","time":"2023/11/08 15:27:40.621 +08:00","caller":"datacoord/metrics_info.go:169","message":"invalid metrics of DataNode was found","error":"context deadline exceeded"}
23988 {"level":"DEBUG","time":"2023/11/08 15:27:40.624 +08:00","caller":"datacoord/meta.go:1249","message":"UpdateChannelCheckpoint done","vChannel":"milvus-rootcoord-dml_2_445159665229402615v0","ts":445494958576631826,"t      ime":"2023/11/08 15:26:40.332 +08:00"}
23989 {"level":"INFO","time":"2023/11/08 15:27:45.431 +08:00","caller":"datacoord/services.go:792","message":"get recovery info request received","collectionID":445159665229656557,"partitionIDs":[]}
23990 {"level":"INFO","time":"2023/11/08 15:27:58.434 +08:00","caller":"datacoord/services.go:792","message":"get recovery info request received","collectionID":445159665229656557,"partitionIDs":[]}
23991 {"level":"WARN","time":"2023/11/08 15:28:10.624 +08:00","caller":"etcd/etcd_kv.go:729","message":"Slow etcd operation save","time spent":"30.000622956s","key":"milvus-prod-backup/meta/datacoord-meta/channel-cp/milvu      s-rootcoord-dml_7_445159665230755062v0"}
23992 {"level":"WARN","time":"2023/11/08 15:28:10.624 +08:00","caller":"datacoord/services.go:1427","message":"failed to UpdateChannelCheckpoint","vChannel":"milvus-rootcoord-dml_7_445159665230755062v0","error":"context d      eadline exceeded"}
23993 {"level":"WARN","time":"2023/11/08 15:28:10.625 +08:00","caller":"datacoord/metrics_info.go:169","message":"invalid metrics of DataNode was found","error":"context deadline exceeded"}
23994 {"level":"WARN","time":"2023/11/08 15:28:10.625 +08:00","caller":"datacoord/metrics_info.go:169","message":"invalid metrics of DataNode was found","error":"context deadline exceeded"}
23995 {"level":"WARN","time":"2023/11/08 15:28:10.625 +08:00","caller":"datacoord/metrics_info.go:169","message":"invalid metrics of DataNode was found","error":"context canceled"}
23996 {"level":"WARN","time":"2023/11/08 15:28:10.625 +08:00","caller":"datacoord/metrics_info.go:169","message":"invalid metrics of DataNode was found","error":"context canceled"}

**Comment by yanliang567** [comment]
@huluhaziqi quick questions: do the 4 etcd ips belong to the same etcd cluster? it works only when they belong to the same etcd cluster.  If yes, please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation
/assign @huluhaziqi 
/unassign

**Comment by huluhaziqi** [comment]
> @huluhaziqi quick questions: do the 4 etcd ips belong to the same etcd cluster? it works only when they belong to the same etcd cluster. If yes, please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation /assign @huluhaziqi /unassign

they belong to one etcd cluster,and due to network reason one etcd is not reachable

**Comment by huluhaziqi** [comment]
> let one of the etcd ip disconnect：
> 
> is this Kill -9 or Kill -stop or other operations? This might be a etcd issue under leader change

due to the network reason, one etcd ip is disconnect . this issue is not under leader change.
or let one datacoord can not connect to one etcd ip (these etcd ips are belong to one cluster)

**Comment by xiaofan-luan** [comment]
> > let one of the etcd ip disconnect：
> > is this Kill -9 or Kill -stop or other operations? This might be a etcd issue under leader change
> 
> due to the network reason, one etcd ip is disconnect . this issue is not under leader change. or let one datacoord can not connect to one etcd ip (these etcd ips are belong to one cluster)

but you should be config multiple etcd ips right?

**Comment by yanliang567** [comment]
As xiaofan said, milvus does not switch the etcd ips in the config list, and etcd service does that. please provide full milvus and etcd logs for deeper investigations/

**Comment by huluhaziqi** [comment]
> > > let one of the etcd ip disconnect：
> > > is this Kill -9 or Kill -stop or other operations? This might be a etcd issue under leader change
> > 
> > 
> > due to the network reason, one etcd ip is disconnect . this issue is not under leader change. or let one datacoord can not connect to one etcd ip (these etcd ips are belong to one cluster)
> 
> but you should be config multiple etcd ips right?

<img width="622" alt="image" src="https://github.com/milvus-io/milvus/assets/7227963/50a8c3d6-6417-4b3c-8a94-435ecdf4cc78">
i have config the multiple etcd ips,and if one ip is disconnect, this problem will happen

**Comment by huluhaziqi** [comment]
> As xiaofan said, milvus does not switch the etcd ips in the config list, and etcd service does that. please provide full milvus and etcd logs for deeper investigations/

[Uploading datacoord-322.log…]()
this is the whole log of datacoord

**Comment by huluhaziqi** [comment]
> > As xiaofan said, milvus does not switch the etcd ips in the config list, and etcd service does that. please provide full milvus and etcd logs for deeper investigations/
> 
> Uploading datacoord-322.log… this is the whole log of datacoord

<img width="908" alt="image" src="https://github.com/milvus-io/milvus/assets/7227963/1a0abfed-4251-419b-9ddc-36c5581627aa">
as the code ,i think the method of etcd client do not have retry or load balance policy when the etcd is muitlple config

**Comment by huluhaziqi** [comment]
[datacoord-322.log](https://github.com/milvus-io/milvus/files/13303001/datacoord-322.log)
datacoord whole log
