### ISSUE TITLE
[Bug]: Error from server (BadRequest): error when creating "manifests/prometheus-prometheus.yaml"

### ISSUE THREAD

**Issue by yokie121** [milvus-io/milvus#28287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.2
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 16c/64G
- GPU: 
- Others:
```

### Current Behavior

https://milvus.io/docs/monitor.md

prometheus.yaml": Prometheus in version "v1" cannot be handled as a Prometheus: strict decoding error: unknown field "spec.enableFeatures", unknown field "spec.scrapeConfigNamespaceSelector", unknown field "spec.scrapeConfigSelector"

### Expected Behavior

.

### Steps To Reproduce

```markdown
.
```

### Milvus Log

.

### Anything else?

.

**Comment by locustbaby** [comment]
Seems version conflict, will investigate.

**Comment by locustbaby** [comment]
@yokie121 Hi, may I know the version of your k8s? The installation works for me with k8s 1.27
