### ISSUE TITLE
[Enhancement]: Add Search/Query context information to tracing span 

### ISSUE THREAD

**Issue by sunby** [milvus-io/milvus#28315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

We can not find the specific dsl if the log level is info and higher level.
Add search/query context information to tracing span.

**Comment by VishalMCF** [comment]
Hi, I am a new wannabe contributor here. Can someone please tell me how to get started to understand the architecture of the database? Meanwhile I will refer to the docs. Also it will be helpful to suggest looking at that part of the code which is the most important one and has no dependency on other modules.

**Comment by xiaofan-luan** [comment]
> Hi, I am a new wannabe contributor here. Can someone please tell me how to get started to understand the architecture of the database? Meanwhile I will refer to the docs. Also it will be helpful to suggest looking at that part of the code which is the most important one and has no dependency on other modules.

Hi Vishal, welcome to the community~

So want to work on the trace project? 

Did you go through docuemnt on milvus.io already?

**Comment by VishalMCF** [comment]
@xiaofan-luan I am not sure I can take this up as of now. I need some time to go through the docs. But yes I do want to be part of the community. Maybe be Christmas end i will be able to take up Good First Issues.

**Comment by VishalMCF** [comment]
@xiaofan-luan I want to start working on this issue. Can you please tell me about what DSL means in the context or suggest anything to read about it? What is the tracing span and what context information needs to be added? Are there any already existing implementations that I can extend for the above issue?

**Comment by xiaofan-luan** [comment]
To learn about trace, starf from
1. traceConfig -> this is how we config trace for cp
2. all the gprc start from grpc_interceptor.go
3. for message go through kafka, see messagestream/trace.go

**Comment by VishalMCF** [comment]
@xiaofan-luan I have some questions. I started analyzing it 2 days back and I came up with the following understanding:-
1. In grpc_interceptor there is a method withLevelAndTrace where based upon the properties in the context metadata we are putting the log object with the desired level of logging.
2. In component_parameter we are declaring structs with some config. That is where we have declared traceConfig. But all the properties are predefined. 
3. Now in trace.go we have a method "MsgSpanFromCtx" where we can extract span from context and attach some tags to it.
Now whatever pieces i put together what I observed is that from the context I can read which logging level it is. If it's more than info then I need to add the search/query context info as tags to the span. And we can have all the information in trace if spans are properly tagged with the context info of the search/query.
So if I am on the correct path, I would like to ask two questions:-
1. How i can get this search/query info from the context?
2. And do I need to edit the same method of "MsgSpanFromCtx"?

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan I have some questions. I started analyzing it 2 days back and I came up with the following understanding:-
> 
> 1. In grpc_interceptor there is a method withLevelAndTrace where based upon the properties in the context metadata we are putting the log object with the desired level of logging.
> 2. In component_parameter we are declaring structs with some config. That is where we have declared traceConfig. But all the properties are predefined.
> 3. Now in trace.go we have a method "MsgSpanFromCtx" where we can extract span from context and attach some tags to it.
>    Now whatever pieces i put together what I observed is that from the context I can read which logging level it is. If it's more than info then I need to add the search/query context info as tags to the span. And we can have all the information in trace if spans are properly tagged with the context info of the search/query.
>    So if I am on the correct path, I would like to ask two questions:-
> 4. How i can get this search/query info from the context?
> 5. And do I need to edit the same method of "MsgSpanFromCtx"?

For all the trace ctx in memory, i believe it should be carried together with go ctx, and GRPC should carry this ctx between nodes(You may need to run extra test on it, I'm not 100% sure).

There are two special cases:
1. Request go through message queue -> they use MsgSpanFromCtx and fill the trace info into message so the downstream consumer could get the trace info from upstream
2. In querynode - the CGO boundary need special handling. I believe this is not handle properly for now so there are no tracing in cpp code right now

**Comment by VishalMCF** [comment]
@xiaofan-luan Can you suggest a way to debug this? So that i can see what info is present in the context when MsgSpanFromCtx is called.

**Comment by xiaofan-luan** [comment]
The easiest way is to start a milvus standalone and add some logs.

Or you can start a integration test and do an insertion, add a breakpoint at MsgSpanFromCtx

**Comment by VishalMCF** [comment]
@xiaofan-luan Is it okay if I can stop working on this issue as I find it a bit challenging? I think I should start by writing test cases and getting familiar with the codebase and implementation. If you know any module which needs code coverage then please suggest one.
