### ISSUE TITLE
[Enhancement]: Transition from Rebase Merging to Squash Merging

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#28312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

#### PR Title
The PR title must fit in the format: `type: [what the PR does]`
the type must be one of:
- feat: new feature
- enhance: improvement to existing code
- fix: bug fix patch

The bot adds `kind` label according to the type, `fix` type PR requires a related issue link

#### PR Description
The PR description why this PR is needed, how it reaches the target.

#### Additional Commits
Developers simply commits fix patches for their PR, all commit messages should describe what it does, to make reviewer know what the author fixed

#### Squash Merging
The bot squashes and merges the PR, the squashed commit would be:
- Title: the PR title
- Body: the PR description

Edit the PR title and description if it changed

### Changes
- [ ] CODE_REVIEW.md: remove the description about requiring only 1 commit in PR @yah01 
- [ ] Bot: remove the 1 commit requirement, and `kind` label according to the PR title type @samhuang-z
- [ ] Mergify: requires format-well PR title, non-empty PR description @samhuang-z

### Deprecated

- [ ] Deprecated the `/kind` command @samhuang-z

### Why is this needed?

Propose transitioning our repository's merging strategy from "rebase merging" to "squash merging." This shift is intended to streamline our development process, improve code quality, and enhance the overall efficiency of our version control workflow.

Advantages:

- Better Reviewing Experience: Allowing reviewers to determine the latest changes by comparing commits, to make reviewing easier.

- Keep Commits History: It will be easier for developers to roll back to old commits when necessary as the commits history is reserved.

- Developers Friendly: Developers no longer need to manually squash multiple commits to meet the merge requirements, which reduces the barrier for contributing code to the community and makes the development process more natural and seamless.

**Comment by congqixia** [comment]
@yah01 what about improvement?

**Comment by yah01** [comment]
> @yah01 what about improvement?

enhance type would add the `kind/improvement` label, "improvement" is OK but "enhance" is shorter

**Comment by congqixia** [comment]
we have four kinds for PR here:
- feature
- enhancement
- improvement
- bug
any idea to match your strategy?

**Comment by yah01** [comment]
> we have four kinds for PR here:
> 
> * feature
> * enhancement
> * improvement
> * bug
>   any idea to match your strategy?

Is it necessary to have both `enhancement` and `improvement`? Like to remove `improvement`, change the `related issue` requirement to:
- kind/bug
- or the PR reaches size/L (100 lines) or larger 
@xiaofan-luan @czs007 @jiaoew1991 @congqixia any comment about this?

**Comment by jiaoew1991** [comment]
> > we have four kinds for PR here:
> > 
> > * feature
> > * enhancement
> > * improvement
> > * bug
> >   any idea to match your strategy?
> 
> Is it necessary to have both `enhancement` and `improvement`? Like to remove `improvement`, change the `related issue` requirement to:
> 
> * kind/bug or kind/feature
> * or the PR reaches size/L (100 lines) or larger
> 
> @xiaofan-luan @czs007 @jiaoew1991 @congqixia any comment about this?

I think keep one is enough 🤔
