### ISSUE TITLE
[Bug]: metric type not match: expected=L2, actual=COSINE: invalid parameter

### ISSUE THREAD

**Issue by YasmineMh** [milvus-io/milvus#28317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.14
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.0
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The issue is caused by a mismatch in the metric type being used. The expected metric type is "L2," but the actual metric type being used is "COSINE," which is considered an invalid parameter for the operation.

I don't understand why we need to use the same metric in the search as specified during indexing, or why it's necessary to pass the metric during indexing when it could be useful in search to test multiple metrics for returning relevant vectors.

In my use case, I aim to retrieve similar documents by experimenting with multiple metrics without the need to create a new index. Is this feasible?

Thank you!

### Expected Behavior

do the search based on the metric_type parameter.

### Milvus Log

RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
attempt #1:code: UnexpectedError, error: fail to Search, QueryNode ID=13, reason=collection:xxx, metric type not match: expected=L2, actual=COSINE: invalid parameter
attempt #2:context canceled
)>, <Time:{'RPC start': '2023-11-09 10:57:01.299939', 'RPC error': '2023-11-09 10:57:01.358375'}> [pymilvus.decorators] dd.span_id=0 dd.trace_id=0

**Comment by yanliang567** [comment]
@liliu-z any comments?
/assign @liliu-z

**Comment by xiaofan-luan** [comment]
milvus 2.2.14 didn't support cosine?

**Comment by xiaofan-luan** [comment]
it has to be 2.3 or above. We highly recommend 2.3.3

**Comment by YasmineMh** [comment]
@xiaofan-luan yes, I think version 2.2.14 does not support cosine similarity. 
I think the latest version is 2.3.2, not 2.3.3.
The same issue arises when I use the IP metric in search and L2 metric in indexing. If the metric_type parameter is meant for search, why is it necessary to specify it in index_params?

**Comment by liliu-z** [comment]
> @xiaofan-luan yes, I think version 2.2.14 does not support cosine similarity. I think the latest version is 2.3.2, not 2.3.3. The same issue arises when I use the IP metric in search and L2 metric in indexing. If the metric_type parameter is meant for search, why is it necessary to specify it in index_params?

@YasmineMh Milvus only allows same search metric type and indexing metric type for now, and I think the reason why we have the `metric_type` in the search param is for backward compatible. 
Since we didn't see use cases that need different search/indexing metric types, so we make it the same. Plz let us know the cases to help us improve this project, Thanks!

**Comment by YasmineMh** [comment]
Hey @xiaofan-luan, Thank you for your response!

In my use case, after indexing my documents, I am attempting to apply various distance metrics during the search process to evaluate the results of each one. This allows me to determine the most effective metric for my needs.

For instance, if the search metric distance is set in the admin page settings on the frontend, it becomes challenging to replicate this in the backend due to compatibility issues between the search metric type and indexing metric type.

As a potential solution, I am considering indexing the documents with multiple metrics and selecting the appropriate collection during the search based on the specified metric. I am unsure if this approach makes sense, and I would appreciate your insights.

Thank you!

**Comment by liliu-z** [comment]
> Hey @liliu-z , Thank you for your response!
> 
> In my use case, after indexing my documents, I am attempting to apply various distance metrics during the search process to evaluate the results of each one. This allows me to determine the most effective metric for my needs.
> 
> For instance, if the search metric distance is set in the admin page settings on the frontend, it becomes challenging to replicate this in the backend due to compatibility issues between the search metric type and indexing metric type.
> 
> As a potential solution, I am considering indexing the documents with multiple metrics and selecting the appropriate collection during the search based on the specified metric. I am unsure if this approach makes sense, and I would appreciate your insights.
> 
> Thank you!

To our experience, build/search need to use the same metric to get a promising accuracy. So Milvus force using the same metric type for both build and search. It is complicated for us to change this rules and we don't have any plan to do so yet.
So sorry that the legacy API is misleading, since it asks for metric type for both search/build.
If you do want to test the scenarios that build/search use different metric type, doing some modification on Milvus' [index engine](https://github.com/zilliztech/Knowhere) directly will be faster.

**Comment by YasmineMh** [comment]
Thank you @liliu-z !

**Comment by thompsonmj** [comment]
>So Milvus force using the same metric type for both build and search

It would be helpful if this was incorporated into the error message 🙂

**Comment by xiaofan-luan** [comment]
What we recommended on this is to specify metrics types on index build and don't specify anything on search.

**Comment by yanliang567** [comment]
besides, please upgrade pymilvus to latest version if you met this issue.
