### ISSUE TITLE
[Bug]: k8s集群 helm安装milvus失败

### ISSUE THREAD

**Issue by Xf-Zhou** [milvus-io/milvus#28322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.x
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS 7
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

k8s version：1.24
helm version:3.12.0
`kubectl get sc`
![image](https://github.com/milvus-io/milvus/assets/59157563/c3f58689-2b7d-4575-988f-4d805c77602c)

按照 https://milvus.io/docs/install_cluster-helm.md#Install-Helm-Chart-for-Milvus执行以下命令：
`helm repo add milvus https://zilliztech.github.io/milvus-helm/
helm repo update
helm install my-release milvus/milvus`
etcd和minio pod都是pending状态，events是0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling
![image](https://github.com/milvus-io/milvus/assets/59157563/6ff0bbcc-4223-43c8-b92d-061b298bd1a5)

请问下这里的minio该如何配置

### Expected Behavior

pod正常running

**Comment by Xf-Zhou** [comment]
这是pvc 的信息
![image](https://github.com/milvus-io/milvus/assets/59157563/b0081de2-2f96-42c5-96ce-74cc6bd4db83)

**Comment by xiaofan-luan** [comment]
/assign @locustbaby 
please help on it

**Comment by locustbaby** [comment]
> 我安装了minio operator，但是不知道milvus安装时是否需要配置

不需要配置，看你的报错是pv没建出来
你的storageclass是正常的吗？之前有测试过吗
发一下你的values 我看一下

**Comment by Xf-Zhou** [comment]
```
more minio-storage-class.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minio-storage
provisioner: minio.min.io
```

**Comment by locustbaby** [comment]
> more minio-storage-class.yaml
> apiVersion: storage.k8s.io/v1
> kind: StorageClass
> metadata:
>   name: minio-storage
> provisioner: minio.min.io

minio-storage-class 这个是你自己定义的？为什么要配置这个sc呢？
local-storage那个可以用吗？
安装时helm的参数是啥，有单独指定配置吗？

目前报错是pv没建出来，如果你这个sc不work，那换一个试试？把local那个设置为default，然后重新install 一个milvus？

**Comment by Xf-Zhou** [comment]
> > more minio-storage-class.yaml
> > apiVersion: storage.k8s.io/v1
> > kind: StorageClass
> > metadata:
> > name: minio-storage
> > provisioner: minio.min.io
> 
> minio-storage-class 这个是你自己定义的？为什么要配置这个sc呢？ local-storage那个可以用吗？ 安装时helm的参数是啥，有单独指定配置吗？
> 
> 目前报错是pv没建出来，如果你这个sc不work，那换一个试试？把local那个设置为default，然后重新install 一个milvus？

 local也不work，能问下这里如何利用minio 配置sc吗

**Comment by locustbaby** [comment]
sc是集群资源，并不是minio提供的任何服务如果需要使用pvc的能力，都需要一个可用的sc这个集群有别的服务吗，之前有创建过pv和pvc吗在 2023年11月10日，18:36，Xf-Zhou ***@***.***> 写道：﻿


more minio-storage-class.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: minio-storage
provisioner: minio.min.io

minio-storage-class 这个是你自己定义的？为什么要配置这个sc呢？ local-storage那个可以用吗？ 安装时helm的参数是啥，有单独指定配置吗？
目前报错是pv没建出来，如果你这个sc不work，那换一个试试？把local那个设置为default，然后重新install 一个milvus？

local也不work，能问下这里如何利用minio 配置sc吗

**Comment by Xf-Zhou** [comment]
> sc是集群资源，并不是minio提供的任何服务如果需要使用pvc的能力，都需要一个可用的sc这个集群有别的服务吗，之前有创建过pv和pvc吗在 2023年11月10日，18:36，Xf-Zhou ***@***.***> 写道：﻿ more minio-storage-class.yaml apiVersion: storage.k8s.io/v1 kind: StorageClass metadata: name: minio-storage provisioner: minio.min.io minio-storage-class 这个是你自己定义的？为什么要配置这个sc呢？ local-storage那个可以用吗？ 安装时helm的参数是啥，有单独指定配置吗？ 目前报错是pv没建出来，如果你这个sc不work，那换一个试试？把local那个设置为default，然后重新install 一个milvus？ local也不work，能问下这里如何利用minio 配置sc吗 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>

这个集群是我刚建的，没有创建过pv和pvc

**Comment by locustbaby** [comment]
https://github.com/rancher/local-path-provisioner @Xf-Zhou try this one and set as default

**Comment by Xf-Zhou** [comment]
> https://github.com/rancher/local-path-provisioner @Xf-Zhou try this one and set as default

非常感谢，安装成功了
