### ISSUE TITLE
[Bug]: Wrong title

### ISSUE THREAD

**Issue by Kevinello** [milvus-io/milvus#28337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

<img width="1479" alt="image" src="https://github.com/milvus-io/milvus/assets/56342249/f228a088-a5a1-43a4-b3d0-a3722510ddc4">

**Comment by yanliang567** [comment]
@Kevinello thanks for the issue.
@AnthonyTsu1984 please help to fix it.
/assign @AnthonyTsu1984 
/unassign
