### ISSUE TITLE
[Enhancement]: Support the trace request

### ISSUE THREAD

**Issue by SimFG** [milvus-io/milvus#28348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

In order to locate the problem faster and obtain more useful information when the system is abnormal, the system supports tracing user requests.

Supports multiple trace modes, including:
0: Close, (default option) no additional request information is output
1: Output some simple information in the request, such as current user, collection/db name, etc.
2: Output request details

Settings: **common.traceLogMode**

Tasks:
- [X] trace the grpc request https://github.com/milvus-io/milvus/pull/28349
- [ ] trace the error resp https://github.com/milvus-io/milvus/pull/28685
- [ ] trace restful api https://github.com/milvus-io/milvus/pull/28685

**Comment by xiaofan-luan** [comment]
@SimFG 
Let's put it into restful as well

**Comment by LoveEachDay** [comment]
@SimFG Could we add an config option only trace request when request failed?
