### ISSUE TITLE
[Bug]: VectorDBBench configuration and testing

### ISSUE THREAD

**Issue by mybabyiscue** [milvus-io/milvus#28346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

According to the introduction on the official website, python3.11.0 has been configured and the required plug-ins have been installed.

But running init bench directly reports an error. I checked that streamlit is installed. Not sure what the problem is
![image](https://github.com/milvus-io/milvus/assets/96758134/7a2b3d24-c2c9-46d7-a31b-ef78668a7643)

**Comment by XuanYang-cn** [comment]
@mybabyiscue 
Can you invoke `streamlit help` and get the following infomation?
![image](https://github.com/milvus-io/milvus/assets/51370125/a07cf246-93f9-4e93-acc2-0fb5c2a736dc)

**Comment by XuanYang-cn** [comment]
@mybabyiscue also can you call `init_bench` without `python3` outside of `bin`? It seems the `.../bin` are not in your systems executable files' search path. Maybe you could add the `.../bin` into $PATH and try again.
