### ISSUE TITLE
[Enhancement]: Avoid too frequent request to get segment info for all collections

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#28355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

We need to protocol to avoid unnecessary chore job in querycoord to load collection.

The way we fix it, split the request into two step
first step: 
issues a request to compare between datacoord and querycoord collection segment stats. We could do a special hash function on all segment states and send to querycoord the stats hash. Datacoord will return how many collections maybe changed during the last period.

Second step:
iterate by collection and get the detailed difference. 

We can even use datastructure like a merkle tree to make the compare a bit faster

**Comment by yah01** [comment]
The target updating conditions:
- different segment list (flushing, compaction or index building happened)
- channel checkpoint lag reaches the threshold

So, I will introduce the `collection fingerprint` struct:
```golang
{
    segmentListHash [][]byte // hashing values with length 2, the growing segments hashing, sealed segments hashing, it's extensible to add L0 segments hashing, or more
    checkpoints map[string]uint64 // checkpoints of collection channels
}
```
The request contains collections' fingerprint, and the DataCoord calculates the hashing value (maybe cached while flushing, compaction or index building done), and compares with the collections' fingerprint, returns the new target if conditions satisfied.

The new pull target request could be:
```golang
{
    fingerprints map[int64]*Fingerprint  // or map[collectionID]map[partitionID]
}
```
Then we can pull the targets in batch

@xiaofan-luan any comment about this?

**Comment by xiaofan-luan** [comment]
sounds like a plan.
We could name it  Anti-Entropy. 
Anti-Entropy is used to cover the inconsistency and fix.
Be make sure 10000 collection's anti entropy can be compressed into one call

**Comment by xiaofan-luan** [comment]
keep it
