### ISSUE TITLE
[Bug]: sudo add-apt-repository ppa:milvusdb/milvus-standalone fail

### ISSUE THREAD

**Issue by xiezhipeng-git** [milvus-io/milvus#28359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ununtu
- CPU/Memory: 
- GPU: 
- Others: WSL2
```

### Current Behavior

sudo apt install software-properties-common
sudo add-apt-repository ppa:milvusdb/milvus-standalone
sudo apt update
sudo apt install milvus
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
software-properties-common is already the newest version (0.99.22.7).
0 upgraded, 0 newly installed, 0 to remove and 105 not upgraded.
Repository: 'deb https://ppa.launchpadcontent.net/milvusdb/milvus-standalone/ubuntu/ jammy main'
More info: https://launchpad.net/~milvusdb/+archive/ubuntu/milvus-standalone
Adding repository.
Press [ENTER] to continue or Ctrl-c to cancel.
Found existing deb entry in /etc/apt/sources.list.d/milvusdb-ubuntu-milvus-standalone-jammy.list
Adding deb entry to /etc/apt/sources.list.d/milvusdb-ubuntu-milvus-standalone-jammy.list
Found existing deb-src entry in /etc/apt/sources.list.d/milvusdb-ubuntu-milvus-standalone-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/milvusdb-ubuntu-milvus-standalone-jammy.list
Adding key to /etc/apt/trusted.gpg.d/milvusdb-ubuntu-milvus-standalone.gpg with fingerprint 602E528C012F4CAB1A0697CA7A6B89977DE46391
Get:1 file:/var/cuda-repo-wsl-ubuntu-11-8-local  InRelease [1575 B]
Get:1 file:/var/cuda-repo-wsl-ubuntu-11-8-local  InRelease [1575 B]
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Ign:6 https://ppa.launchpadcontent.net/milvusdb/milvus-standalone/ubuntu jammy InRelease
Err:7 https://ppa.launchpadcontent.net/milvusdb/milvus-standalone/ubuntu jammy Release
  404  Not Found [IP: 185.125.190.52 443]
Reading package lists... Done
E: The repository 'https://ppa.launchpadcontent.net/milvusdb/milvus-standalone/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Get:1 file:/var/cuda-repo-wsl-ubuntu-11-8-local  InRelease [1575 B]
Get:1 file:/var/cuda-repo-wsl-ubuntu-11-8-local  InRelease [1575 B]
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Ign:6 https://ppa.launchpadcontent.net/milvusdb/milvus-standalone/ubuntu jammy InRelease
Err:7 https://ppa.launchpadcontent.net/milvusdb/milvus-standalone/ubuntu jammy Release
  404  Not Found [IP: 185.125.190.52 443]
Reading package lists... Done
E: The repository 'https://ppa.launchpadcontent.net/milvusdb/milvus-standalone/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package milvus

### Expected Behavior

install success

### Steps To Reproduce

```markdown
open https://milvus.io/
then Use web show install function
run 
# Install via Launchpad PPA on Ubuntu
sudo apt install software-properties-common
sudo add-apt-repository ppa:milvusdb/milvus-standalone
sudo apt update
sudo apt install milvus
```

### Milvus Log

E: The repository 'https://ppa.launchpadcontent.net/milvusdb/milvus-standalone/ubuntu jammy Release' does not have a Release file

**Comment by yanliang567** [comment]
@xiezhipeng-git sorry, I did not find the page for Install via Launchpad PPA on Ubuntu in milvus.io, could ypu please paste the link ?
/assign @xiezhipeng-git 
/unassign

**Comment by CharlesBuell** [comment]
@yanliang567 you need to scroll down below the "Fuel your machine learning deployment" section. Then, you'll see this:
![image](https://github.com/milvus-io/milvus/assets/137217010/8971e2e2-8690-4ccc-89e3-8ebf7afb708d)

I'm having the same issue as the author.

**Comment by yanliang567** [comment]
Oh, I found it. I think this is something out of date. If you want to install milvus please refer to https://milvus.io/docs/install_standalone-docker.md. I will check with the community and update the milvus.io ASAP.

**Comment by CharlesBuell** [comment]
Looks like the Ubuntu and CentOS section from that portion of the website were removed. Only Docker and Kubernetes remain. Is the PPA no longer supported on Ubuntu, and it's equivalent on CentOS?

**Comment by yanliang567** [comment]
right, we are not going to support PPA on Ubuntu or CentOS, as there are few people using that.  please try docker and k8s, which is more popular and get more rapid updated in the community.

**Comment by CharlesBuell** [comment]
Alright, just making sure. Docker works perfectly fine for me, since the beginning. Thank you!
