### ISSUE TITLE
[Bug]:  Query failed with double quotes

### ISSUE THREAD

**Issue by baiyuelanshan** [milvus-io/milvus#28365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.9
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): milvus-sdk-java 2.2.9
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

when I used scalar filtering on a varchar fieldd with double quotes,  I met an expression error:
```
Error: failed to create query plan: cannot parse expression: tag == "A "test"", error: invalid expression: tag == "A "test"" 
```

code for setting the expression:
searchParam = builder.withExpr("tag == \"A \"test\"\"").build();

**Comment by xiaofan-luan** [comment]
you have to do it like  'A "test"' or you have to use Escape character

**Comment by yanliang567** [comment]
/assign @baiyuelanshan 
please retry as comments above.

/unassign

**Comment by baiyuelanshan** [comment]
acctually, I have use Escape charater, but the text editor didn't display it .
![milvus_code](https://github.com/milvus-io/milvus/assets/48544598/efac0234-f705-4218-8ed0-74a4caca029a)
![milvus_error](https://github.com/milvus-io/milvus/assets/48544598/a707213e-82f5-4776-92f1-29cf487f6f84)

**Comment by xiaofan-luan** [comment]
@yanliang567 
could you try on 2.2.9 and latest 2.3.3?

**Comment by NicoYuan1986** [comment]
Reproduced on v2.2.9 and master-latest. Needs repair. @yanliang567

**Comment by xiaofan-luan** [comment]
/assign @xiaocai2333 
could you help on it

**Comment by xiaofan-luan** [comment]
@NicoYuan1986 
is this reproducible on python sdk also?

**Comment by NicoYuan1986** [comment]
> @NicoYuan1986 is this reproducible on python sdk also?

Yes.
milvus v2.2.9, I use pymilvus==2.2.9
milvus master-latest, I use pymilvus==2.3.3
I think it's related

**Comment by xiaocai2333** [comment]
@baiyuelanshan If your expression contains a string, the string must be enclosed in double quotes or single quotes. You can try this:
```
.withExpr("question == 'A \"test\"'")
```

**Comment by NicoYuan1986** [comment]
if insert "A \"test\"" or 'A "test"', can search with expr="tag == \"A \\\"test\\\"\""
if insert "A 'test'", can search with expr="tag == \"A 'test'\""

**Comment by chenxin6** [comment]
> if insert "A "test"" or 'A "test"', can search with expr="tag == "A \"test\""" if insert "A 'test'", can search with expr="tag == "A 'test'""

sorry, I don't understand on this. is there a typo?

**Comment by chenxin6** [comment]
> if insert "A "test"" or 'A "test"', can search with expr="tag == "A \"test\""" if insert "A 'test'", can search with expr="tag == "A 'test'""

I have inserted a string like `A "test" B`. But I can't search this data by using the expr `tag == "A \"test\" B"`.

**Comment by xiaocai2333** [comment]
> > if insert "A "test"" or 'A "test"', can search with expr="tag == "A "test""" if insert "A 'test'", can search with expr="tag == "A 'test'""
> 
> I have inserted a string like `A "test" B`. But I can't search this data by using the expr `tag == "A \"test\" B"`.

Thank you for bringing up this issue. Our handling of escaped characters in strings wasn't very robust previously. We plan to address this in a future release.
And recommend avoiding escaped characters in the meantime when using the current version.

**Comment by yanliang567** [comment]
@xiaocai2333 @NicoYuan1986 can we close this issue now?

**Comment by xiaocai2333** [comment]
> @xiaocai2333 @NicoYuan1986 can we close this issue now?

I think it has been fixed.
@NicoYuan1986 please verify it.

**Comment by NicoYuan1986** [comment]
> > @xiaocai2333 @NicoYuan1986 can we close this issue now?
> 
> I think it has been fixed. @NicoYuan1986 please verify it.

Test case `test_search_expression_with_double_quotes` has been added. And it performs well in nightly tests.
So close the issue now. version: master-20240111-930735c4
