### ISSUE TITLE
[Bug]: Rootcoord keeps restart due to faild to connect to etcd  and made other components also restart  after etcd pod kill chaos

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#28377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.3.3-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/12268675/9a00ed6b-f6a0-48fe-a863-567516a874fb)

### Expected Behavior

all pods can be running after etcd chaos

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release-cron/detail/chaos-test-for-release-cron/7996/pipeline

log:
[artifacts-etcd-pod-kill-7996-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/13331806/artifacts-etcd-pod-kill-7996-pytest-logs.tar.gz)
[artifacts-etcd-pod-kill-7996-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/13331807/artifacts-etcd-pod-kill-7996-server-logs.1.tar.gz)

**Comment by xiaofan-luan** [comment]
this is as expected.
If etcd failed and can not recover in 30s, all other milvus components fail

**Comment by zhuwenxing** [comment]
```

[2023-11-12T23:43:56.447Z] [2023-11-12 23:43:55 - INFO - ci_test]: chaos injected (test_chaos_apply.py:102)

[2023-11-12T23:43:56.447Z] [2023-11-12 23:43:55 - INFO - ci_test]: chaos inject result: Schedule, test-etcd-pod-kill-1699832635 (test_chaos_apply.py:107)

[2023-11-12T23:51:02.932Z] test-etcd-pod-kill-1699832635

[2023-11-12T23:51:02.933Z] [2023-11-12 23:50:55 - INFO - ci_test]: delete custom resource response: {'kind': 'Status', 'apiVersion': 'v1', 'metadata': {}, 'status': 'Success', 'details': {'name': 'test-etcd-pod-kill-1699832635', 'group': 'chaos-mesh.org', 'kind': 'schedules', 'uid': '90ea81d9-1017-4f84-a5b1-9f7eb3bb7bf8'}} (cus_resource_opts.py:54)

[2023-11-12T23:51:02.933Z] [2023-11-12 23:50:55 - INFO - ci_test]: chaos deleted (test_chaos_apply.py:112)
```
etcd pod kill chaos starts at 2023-11-12 23:43:55 and ends at 2023-11-12 23:50:55.
However at 2023-11-13T00:12:06.491Z, when all etcd pods were running , milvus components were still not ready

**Comment by xiaofan-luan** [comment]
etcd is not available until 00:03.

{"level":"info","ts":"2023-11-13T00:03:54.651Z","caller":"etcdserver/server.go:2054","msg":"published local member to cluster through raft","local-member-id":"cabc2b05fd849318","local-member-attributes":"{Name:etcd-pod-kill-7996-2 ClientURLs:[http://etcd-pod-kill-7996-2.etcd-pod-kill-7996-headless.chaos-testing.svc.cluster.local:2379]}","request-path":"/0/members/cabc2b05fd849318/attributes","cluster-id":"9c55fb1fa7debe1c","publish-timeout":"10s"}
{"level":"info","ts":"2023-11-13T00:03:54.651Z","caller":"embed/serve.go:100","msg":"ready to serve client requests"}
{"level":"info","ts":"2023-11-13T00:03:54.651Z","caller":"etcdmain/main.go:44","msg":"notifying init daemon"}

**Comment by zhuwenxing** [comment]
There are two issues:
* after etcd chaos, why does it still restart four times
* why all etcd pods are running, but Milvus can still not connect to it?

/assign @LoveEachDay 
Please take a look.

**Comment by LoveEachDay** [comment]
`10.255.86.80` is the `etcd svc cluster ip`, and kube-proxy will rewrite iptable rules to redirect `10.255.86.80` to etcd pod ip.

We have encountered some issues to add new iptable rules for new kubernetes service. And this issue is momentary.

**Comment by xiaofan-luan** [comment]
@LoveEachDay 
but it seems to take too long to recover?

**Comment by LoveEachDay** [comment]
> @LoveEachDay but it seems to take too long to recover?

It may take up to 1 minutes to sync the new iptable rules for new kubernetes service.

**Comment by xiaofan-luan** [comment]
> > @LoveEachDay but it seems to take too long to recover?
> 
> It may take up to 1 minutes to sync the new iptable rules for new kubernetes service.

seems that it take almost 15 minutes until etcd service recovered

**Comment by xiaofan-luan** [comment]
kill happens on 2023-11-12 23:50:55
but the etcd service is not recovered until  00:03 and milvus is tried to connect to 10.255.86.80 and failed
