### ISSUE TITLE
[Bug]: Why search milvus return not same results

### ISSUE THREAD

**Issue by BlueTeamQQ1** [milvus-io/milvus#28370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I search milvus not same results.
![48b2bf062665423ba4533dfbd9508a6a](https://github.com/milvus-io/milvus/assets/63582498/6faa3d41-7ead-4b2e-aff5-a74e96a2f383)
I use index GPU_IVF_FLAT.
Please help me!!!

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version:
> - Deployment mode(standalone or cluster):
> - MQ type(rocksmq, pulsar or kafka):    
> - SDK version(e.g. pymilvus v2.0.0rc2):
> - OS(Ubuntu or CentOS): 
> - CPU/Memory: 
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> When I search milvus not same results. ![48b2bf062665423ba4533dfbd9508a6a](https://user-images.githubusercontent.com/63582498/282373433-6faa3d41-7ead-4b2e-aff5-a74e96a2f383.png) I use index GPU_IVF_FLAT. Please help me!!!
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

your embedding seems to have a nan?
which means your embedding distance is always maximum

**Comment by BlueTeamQQ1** [comment]
but why the result returned for each search is different for 1 query?

**Comment by BlueTeamQQ1** [comment]
This only happens when I add expr.
![32cbad4e6dc34b5883e387ceba5bd280](https://github.com/milvus-io/milvus/assets/63582498/d0ce4cae-bcba-4e3a-882e-b293d7fbc59e)

**Comment by BlueTeamQQ1** [comment]
![61d4c1b34f8d46aab3487f96b07a6a9a](https://github.com/milvus-io/milvus/assets/63582498/128810d3-84eb-4e22-bc7f-70be7ed105ad)
The distance will not always be nan

**Comment by xiaofan-luan** [comment]
but how can a vector has nan?

**Comment by xiaofan-luan** [comment]
this is the out of expectation I guess.

**Comment by yanliang567** [comment]
/assign @BlueTeamQQ1 
how did you insert a nan vector into milvus?

**Comment by BlueTeamQQ1** [comment]
Perhaps you did not understand my point.. Nan above picture is distance. I solved the problem by switch GPU_IVF_FLAT to IVF_FLAT. I guess the problem is at GPU index.

**Comment by BlueTeamQQ1** [comment]
/assign @yanliang567

I have checked the data, and there is no nan vector. I think it's impossible for a nan vector to occur.

**Comment by yanliang567** [comment]
/assign @liliu-z 
could you please take look?
/unassign

**Comment by Presburger** [comment]
@BlueTeamQQ1 Hi, I'm sorry for the unpleasant experience I've caused you. Are you using a metrics IP?"

**Comment by xiaofan-luan** [comment]
> /assign @yanliang567
> 
> I have checked the data, and there is no nan vector. I think it's impossible for a nan vector to occur.

can you give some sample input of your vector datas, and the sample query?
