### ISSUE TITLE
Hybrid search with SPLADE (V2) and vector

### ISSUE THREAD

**Issue by skairali** [milvus-io/milvus#28381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Support for Hybrid search with SPALDE V2 and vector

### Why is this needed?

A merger of sparse and dense retrieval is now possible through [hybrid search](https://docs.pinecone.io/docs/hybrid-search), and learnable sparse embeddings help minimize the traditional drawbacks of sparse retrieval.

SPLADE V2 seems to be a lot more promising than BM25.   Since community has already considered BM25 scoring - can we consider SPLADE V2 as well as this is much more efficient than BM25

**Comment by xiaofan-luan** [comment]
I've been working on this for a while.
Please stay tuned. Milvus 2.4 shoudl support sparse vector, multi vector and hybrid search

**Comment by skairali** [comment]
@xiaofan-luan    Can you please let me know when this will be available ,   will we get Milvus 2.4 with Hybrid search by Jan 2024?

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan Can you please let me know when this will be available , will we get Milvus 2.4 with Hybrid search by Jan 2024?

Very likely.
For current plan, we are targeting on deliver this feature mid of Jan.

**Comment by xiaofan-luan** [comment]
keep it, we are actively working on hybrid search

**Comment by lynnssi** [comment]
@xiaofan-luan I am eagerly looking forward to being able to do a hybrid of keyword / sparse and vector search in Milvus. Is the feature still on track to be included in Milvus 2.4 in mid-January?

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan I am eagerly looking forward to being able to do a hybrid of keyword / sparse and vector search in Milvus. Is the feature still on track to be included in Milvus 2.4 in mid-January?

Unfortunately no. 
Due the lag of current implementation, the sparse embedding feature support is delayed to later version of 3.0. We may release a beta version of sparse embedding support on 2.4.x.

@liliu-z @zhengbuqian what do you think could be a possible target to release sparse embedding support?

**Comment by vipul25-ds** [comment]
> > @xiaofan-luan I am eagerly looking forward to being able to do a hybrid of keyword / sparse and vector search in Milvus. Is the feature still on track to be included in Milvus 2.4 in mid-January?
> 
> Unfortunately no. Due the lag of current implementation, the sparse embedding feature support is delayed to later version of 3.0. We may release a beta version of sparse embedding support on 2.4.x.
> 
> @liliu-z @zhengbuqian what do you think could be a possible target to release sparse embedding support?

Hello @xiaofan-luan @zhengbuqian , could you please check on the possible release date of 3.0/ looking forward for the hybrid/keyword search

**Comment by xiaofan-luan** [comment]
Here is the plan:
2.4.0 - Jan.30 with tantivy invert index support, multi vector support
3.0-beta - Feb.28 with sparse embedding support
3.0 - March.30

**Comment by skairali** [comment]
@xiaofan-luan  is there anyway I can look into even non released branch code of Milvus which supports Spade V2 or hybrid search?  I want to run some experiments if you have it.

**Comment by xiaofan-luan** [comment]
@zhengbuqian 
Any estimation when we can release a preview version?
I think early Feb could be an estimation

**Comment by skairali** [comment]
@zhengbuqian. @xiaofan-luan   I will be happy to participate in testing this one. 

I have really need for Milvus + Splade V2 .  So we can get the details documented as well.

Please do let me know when can we get the pre release version

**Comment by skairali** [comment]
Any updates   @zhengbuqian. @xiaofan-luan ?

**Comment by zhengbuqian** [comment]
Hi @skairali I have been actively working on adding unit tests these days. If you want a "developer preview" version, you can checkout to https://github.com/milvus-io/milvus/pull/29421 (and update go.mod, go.sum based on https://github.com/milvus-io/milvus/pull/30400 ) and build milvus. For SDK use https://github.com/milvus-io/pymilvus/pull/1902 (refer to https://github.com/milvus-io/pymilvus?tab=readme-ov-file#faq on how to use local version PyMilvus SDK), it includes a simple demo script.

**Comment by skairali** [comment]
@zhengbuqian  working on it

**Comment by skairali** [comment]
@zhengbuqian   Please see the compilation issue we are facing   https://github.com/milvus-io/milvus/pull/29421#issuecomment-1948022826

**Comment by vipul25-ds** [comment]
> Here is the plan: 2.4.0 - Jan.30 with tantivy invert index support, multi vector support 3.0-beta - Feb.28 with sparse embedding support 3.0 - March.30

Hello @xiaofan-luan, just wanted to check if the beta version is released.

**Comment by xiaofan-luan** [comment]
> > Here is the plan: 2.4.0 - Jan.30 with tantivy invert index support, multi vector support 3.0-beta - Feb.28 with sparse embedding support 3.0 - March.30
> 
> Hello @xiaofan-luan, just wanted to check if the beta version is released.

We will bring the code this week, and the code freeze is targeting at 3.14 and release is targeting at 3.18

**Comment by khaddeep143** [comment]
> > > Here is the plan: 2.4.0 - Jan.30 with tantivy invert index support, multi vector support 3.0-beta - Feb.28 with sparse embedding support 3.0 - March.30
> > 
> > 
> > Hello @xiaofan-luan, just wanted to check if the beta version is released.
> 
> We will bring the code this week, and the code freeze is targeting at 3.14 and release is targeting at 3.18

Is this released?

**Comment by xiaofan-luan** [comment]
> > > > Here is the plan: 2.4.0 - Jan.30 with tantivy invert index support, multi vector support 3.0-beta - Feb.28 with sparse embedding support 3.0 - March.30
> > > 
> > > 
> > > Hello @xiaofan-luan, just wanted to check if the beta version is released.
> > 
> > 
> > We will bring the code this week, and the code freeze is targeting at 3.14 and release is targeting at 3.18
> 
> Is this released?

code is in but still under testing, targeting March 18th in Milvus 2.4

**Comment by zhengbuqian** [comment]
Milvus has just released a beta version for 2.4, which provides beta support for Sparse Vectors. Feel free to try it out! 

The doc is at https://milvus.io/docs/sparse_vector.md. the new pymilvus SDK also provides an optional `model` module(`pip install pymilvus[model]`), you can use that to easily generate SPLADE sparse embeddings https://milvus.io/docs/embed-with-splade.md. For a complete guide of performing hybrid search on sparse/dense embeddings, see https://github.com/milvus-io/pymilvus/blob/master/examples/hello_hybrid_sparse_dense.py.

**Comment by khaddeep143** [comment]
from pymilvus.model.hybrid import BGEM3EmbeddingFunction is not loaded

**Comment by xiaofan-luan** [comment]
did you do pip install pymilvus[model]?

**Comment by khaddeep143** [comment]
> did you do pip install pymilvus[model]?

thanks, was able to install with pip install pymilvus['model'] on my mac

**Comment by khaddeep143** [comment]
I thought I can mix sparse and vector embeddings together just like weaviate and pinecone and store it at a single field. when is this feature coming?

**Comment by xiaofan-luan** [comment]
> I thought I can mix sparse and vector embeddings together just like weaviate and pinecone and store it at a single field. when is this feature coming?

Nope. this is a hacky solution and never gonna to work

**Comment by xiaofan-luan** [comment]
if you can give some evalution that would be interesting, but ideally:
1. it is much slower -> dense embedding is fixed size and usually memory aligned.
2. search quality will be bad -> sparse and dense embedding don't have same dinstance metrics
3. memory usage will be huge.
Unless there is a clue that mix them all together will help, we will be more focus on hybrid search + retrieve + reranking styple

**Comment by khaddeep143** [comment]
Not sure but it's giving accurate result to my retrieval use case. I used milvus sparse BM25 and it's super slow.

**Comment by wxywb** [comment]
@khaddeep143 
hello, could I get your use case to figure out the reason?

**Comment by khaddeep143** [comment]
> @khaddeep143 hello, could I get your use case to figure out the reason?

Never mind, it's working satisfactorily now.

**Comment by khaddeep143** [comment]
when is the milvus 2.4.0 coming to zillzcloud?

**Comment by xiaofan-luan** [comment]
> when is the milvus 2.4.0 coming to zillzcloud?

targeting beta on Mid may

**Comment by khaddeep143134** [comment]
When is hybrid search coming on Milvus lite?

**Comment by khaddeep143134** [comment]
> When is hybrid search coming on Milvus lite?
@xiaofan-luan

**Comment by zhengbuqian** [comment]
@junjiejiangjjj may help answer hybrid search on Milvus lite

**Comment by junjiejiangjjj** [comment]
> When is hybrid search coming on Milvus lite?

miluvs-lite 2.4.8 supports hybrid_search. Use `pip install -U milvus-lite` to install the latest version.

**Comment by khaddeep** [comment]
> > When is hybrid search coming on Milvus lite?
> 
> miluvs-lite 2.4.8 supports hybrid_search. Use `pip install -U milvus-lite` to install the latest version. from pymilvus import connections
connections.connect(uri="./milvus_demo.db") doesn't seem to be working, for other way we only have documentation for dense vector search.

Great thanks, can I get some documentation to run milvus-lite hybrid?

**Comment by junjiejiangjjj** [comment]
> > > When is hybrid search coming on Milvus lite?
> > 
> > 
> > miluvs-lite 2.4.8 supports hybrid_search. Use `pip install -U milvus-lite` to install the latest version. from pymilvus import connections
> > connections.connect(uri="./milvus_demo.db") doesn't seem to be working, for other way we only have documentation for dense vector search.
> 
> Great thanks, can I get some documentation to run milvus-lite hybrid?

You can refer to the code here,  make sure milvus-lite is 2.4.8
https://github.com/milvus-io/milvus-lite/blob/main/tests/test_hybrid_search.py
