### ISSUE TITLE
NVIDIA-Container-Toolkit is required to install GPU-enabled Milvus

### ISSUE THREAD

**Issue by Bennu-Li** [milvus-io/milvus#2839]
**Location of incorrect documentation**
https://milvus.io/cn/docs/v0.10.0/gpu_milvus_docker.md#%E8%BD%AF%E4%BB%B6

**Describe the problems or issues found in the documentation**
NVIDIA-Container-Toolkit is required to install GPU-enabled Milvus. This requirement is not written in the documentation。
![image](https://user-images.githubusercontent.com/53458891/87284573-17b09180-c529-11ea-8831-39056d11b35d.png)

**Suggested fix for documentation**
Install NVIDIA-Container-Toolkit:
https://github.com/NVIDIA/nvidia-docker

**Comment by PahudPlus** [comment]
The webpage has been updated. See: https://www.milvus.io/docs/v0.10.1/gpu_milvus_docker.md
