### ISSUE TITLE
[Bug]: Clustering and storing large data sets into the database will cause the buff/size of the master node to increase rapidly.

### ISSUE THREAD

**Issue by mybabyiscue** [milvus-io/milvus#28408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.2 
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):     pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS):  Centos
- CPU/Memory:  master:256G  slave{1..60}:16G
- GPU: 
- Others:
![image](https://github.com/milvus-io/milvus/assets/96758134/e67d4f7c-d07c-4078-878a-9547d3bde92e)

```

### Current Behavior

1. The master node machine is configured with 256G memory, and the storage class is mounted on the master node using nfs.
2. The data is 256 dimensions. Data volume is 28 million
3. When warehousing, I used nmon to monitor and found that the memory usage was low, but I found that the buff/size increased too quickly. Even after I stopped, the cache could not be cleared.
![image](https://github.com/milvus-io/milvus/assets/96758134/7db19be7-e0a9-4c23-8ac5-f60692cf8cb8)
4. The situation of this cache. If I delete echo3 like this, it will cause the cluster to collapse. Similarly, it is unreasonable to occupy so much cache with only 30 million pieces of data.

**Comment by yanliang567** [comment]
"buff/cache" is memory that Linux uses for disk caching, and that will be freed whenever applications require it. So you don't have to worry if a large amount is being shown in this field, as it doesn't count as "used" memory. 

/assign @mybabyiscue 
/unassign
