### ISSUE TITLE
[Bug]: 基于k8s部署milvus 版本 2.2.11 查询报错

### ISSUE THREAD

**Issue by xxxrain** [milvus-io/milvus#28413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.11
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): kafka
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 48c128g
- GPU: 
- Others:
```

### Current Behavior

进行向量查询时，报如下错误
<MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
attempt #1:code: UnexpectedError, error: fail to Search, QueryNode ID=357, reason=Search 357 failed, reason Timestamp lag too large lag(83h58m40.315s) max(24h0m0s) err %!w(<nil>)
attempt #2:context canceled
)>

**Comment by yanliang567** [comment]
@xxxrain according to the error msg, the tt lag is too large. what happen to the milvus before searching? I'd suggest you restart the datacoord and datanode and wait for a few hours  to catch up the tt lag

/assign @xxxrain 
/unassign

**Comment by yanliang567** [comment]
if it still reproduces after that, please  refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation
