### ISSUE TITLE
[Bug]: At present, we are experiencing a recall delay: the newly inserted data is recalled immediately, but the data cannot be recalled right away, and it will take about half an hour to recall.

### ISSUE THREAD

**Issue by WenShaoHub** [milvus-io/milvus#28421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.2
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    3.1.0
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.15
- OS(Ubuntu or CentOS): os:Ubuntu 20.04.4 LTS (Focal Fossa)
- CPU/Memory: 16/64g
- GPU: 无
- Others:
```

### Current Behavior

At present, we are experiencing a recall delay: the newly inserted data is recalled immediately, but the data cannot be recalled, and it will take about half an hour to recall.
and
when we insert a new data，
use query api can recall right now
use search api experiencing a recall delay

### Expected Behavior

insert new data,we can search  and get data right away

### Milvus Log

[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/13346046/milvus-log.tar.gz)
[log-2.zip](https://github.com/milvus-io/milvus/files/13347176/log-2.zip)

**Comment by yanliang567** [comment]
try to use consistency_level=strong to query and search the new insert data immediately. check here for details: https://milvus.io/docs/consistency.md#Consistency-levels
/assign @WenShaoHub 
/unassign

**Comment by WenShaoHub** [comment]
I've tried consistency_level=strong before, but it didn't work.

**Comment by yanliang567** [comment]
could you please share the reproduce code snippet? Also please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation.

**Comment by WenShaoHub** [comment]
this is my  reproduce code,   milvus use HNSW index。 Please refer to the above log, has been uploaded
search_params = {
        "expr": params.expr,
        "metric_type": params.metricType,
        "data": params.vectors,
        "anns_field": params.vectorFieldName,
        "output_fields": params.outFields,
        "param": {"ef":40},
        "limit": params.topK,
        "consistency_level":"Strong"
    }
    query_results_raw = collection.search(**search_params)

**Comment by yanliang567** [comment]
@NicoYuan1986  could you please help to reproduce it on milvus 2.3.3?
@liliu-z  is it something wrong with the growing segment index?
/assign @liliu-z  @NicoYuan1986

**Comment by WenShaoHub** [comment]
One thing needs to be mentioned, we have adjusted the size of segement before, the size is 2g at present, and the recall delay problem will not come up after we replace HNSW index with Flat index

**Comment by xiaofan-luan** [comment]
> the newly inserted data is recalled immediately, but the data cannot be recalled, and it will take about half an hour to recall.

 the newly inserted data is recalled immediately, but the data cannot be recalled, and it will take about half an hour to recall.

can you give a example?
what do you mean by recalled? and data cannot be recalled?

**Comment by xiaofan-luan** [comment]
Does that mean that you can search the result but you can not query the result out, or the output field doesn't contain your value?

**Comment by NicoYuan1986** [comment]
cannot reproduce in house on milvus 2.3.3.
Can you provide more steps about this issue?  for example, Insert first then index or Index load first then insert, What is the size of the new inserted data volume?

**Comment by WenShaoHub** [comment]
Total data: 40 million
The amount of new data added is about 100 insert per second

**Comment by WenShaoHub** [comment]
This phenomenon does not occur all the time, but once every few hours, when the index node cpu is increased, the phenomenon of not searching data will be resolved

**Comment by yanliang567** [comment]
sounds like a growing segment indexing performance issue, @liliu-z could you please help to take a look?
also @WenShaoHub could you please try colleciton.query() to get the new inserted data?

**Comment by WenShaoHub** [comment]
We have already changed the index method to solve this problem, and the issue cannot be reproduced at present, so it is useless to change the configuration.
