### ISSUE TITLE
Remove restriction on the metric port?

### ISSUE THREAD

**Issue by thirstycrow** [milvus-io/milvus#2842]
**Please state you issue using the following template and, most importantly, in English.**

**Describe the bug**
Milvus cannot start using a metric port of 80. It is already documented in the configuration reference that metric port should be in range (1024, 65536), but I can't think of a good reason for this restriction.

**Comment by tinkerlin** [comment]
https://www.w3.org/Daemon/User/Installation/PrivilegedPorts.html

**Stop asking questions about such basics. Google is enough to solve this kind of problem.**

**Comment by thirstycrow** [comment]
The metric port is used by pushgateway, and pushgateway talks HTTP. So it does not violate the spec for well-known ports to put a pushgateway behind a public gateway which serves in the 80 port.
