### ISSUE TITLE
为什么milvus创建索引时 cpu load那么高，到达了90%几超过10分钟，有什么配置层面可以改或者其它方案解决吗

### ISSUE THREAD

**Issue by kyle-kai** [milvus-io/milvus#2843]
400万条128维的数据，在16核32G机器上创建索引时，cpu 使用率高达90%多，导致查询检索服务基本此时不可用，而且会持续10分钟到半小时不止，请问这个问题可以怎么解决？配置哪里可以配吗

**Comment by tinkerlin** [comment]
Hi there kyle-kai,

Thank you for filing an issue with Milvus. But, could we ask you to describe your issue in English instead?

Milvus has an international team of developers and quite many of them cannot read Chinese. Issues written in English usually get fixed much faster than in other languages. So, we would appreciate it if you can reiterate your issue in English.

Many thanks,
Milvus developer team

**Comment by kyle-kai** [comment]
OK， I have already described the issue in English.
