### ISSUE TITLE
[Bug]: count(*) returns more than actual size

### ISSUE THREAD

**Issue by safehumeng** [milvus-io/milvus#28434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.3.3
- Deployment mode(standalone or cluster):standalone 
- MQ type(rocksmq, pulsar or kafka):  default
- SDK version(e.g. pymilvus v2.0.0rc2): v2.3.3
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 8/64G
- GPU: no use
- Others:
```

### Current Behavior

When I do
query_res = t_milvus.query(expr="", output_fields=["count(*)"])
print(query_res[0]["count(*)"])
got 17
but
query_res = t_milvus.query(expr="", limit=16384)
print(len(query_res))
got 15

### Expected Behavior

expect 
query_res0 = t_milvus.query(expr="", output_fields=["count(*)"])
query_res1 = t_milvus.query(expr="", limit=16384)
should
query_res0[0]["count(*)"] == len(query_res1)

### Steps To Reproduce

```markdown
I don't know how it happened
```

### Milvus Log

use
./export-milvus-log.sh -i my-release -s 24h
got
[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/13359219/milvus-log.tar.gz)
but it is empty

**Comment by yanliang567** [comment]
@NicoYuan1986 please help to reproduce it in house
/assign @NicoYuan1986

**Comment by yanliang567** [comment]
@safehumeng do you have duplicated PK data in mulvus?

**Comment by safehumeng** [comment]
> @safehumeng do you have duplicated PK data in mulvus?

use t_milvus.upsert to update existent data by the same PK

**Comment by yanliang567** [comment]
okay, then i could be a known issue #27515, which was fixed in milvus v2.3.3, please try it.

**Comment by safehumeng** [comment]
> okay, then i could be a known issue #27515, which was fixed in milvus v2.3.3, please try it.

I had found this issue and update milvus from v2.3.2 to v2.3.3，and update pymilvus  from v2.3.2 to v2.3.3，but got the same result which is incorrect

**Comment by yanliang567** [comment]
/assign @yah01 
could you please help to take a look?

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version:v2.3.3
> - Deployment mode(standalone or cluster):standalone 
> - MQ type(rocksmq, pulsar or kafka):  default
> - SDK version(e.g. pymilvus v2.0.0rc2): v2.3.3
> - OS(Ubuntu or CentOS): CentOS
> - CPU/Memory: 8/64G
> - GPU: no use
> - Others:
> ```
> 
> ### Current Behavior
> When I do query_res = t_milvus.query(expr="", output_fields=["count(_)"]) print(query_res[0]["count(_)"]) got 17 but query_res = t_milvus.query(expr="", limit=16384) print(len(query_res)) got 15
> 
> ### Expected Behavior
> expect query_res0 = t_milvus.query(expr="", output_fields=["count(_)"]) query_res1 = t_milvus.query(expr="", limit=16384) should query_res0[0]["count(_)"] == len(query_res1)
> 
> ### Steps To Reproduce
> ```
> I don't know how it happened
> ```
> 
> ### Milvus Log
> use ./export-milvus-log.sh -i my-release -s 24h got [milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/13359219/milvus-log.tar.gz) but it is empty
> 
> ### Anything else?

could you offer the code you reproduce the issue?
Did you try to use strong consistency to do query?

**Comment by xiaofan-luan** [comment]
if you default setup is bounded staleness, there is a 3 seconds window that you insert/delete and data is not visible

**Comment by yanliang567** [comment]
> > okay, then i could be a known issue #27515, which was fixed in milvus v2.3.3, please try it.
> 
> I had found this issue and update milvus from v2.3.2 to v2.3.3，and update pymilvus from v2.3.2 to v2.3.3，but got the same result which is incorrect
> 
> should I drop the datebase first, then reinsert data?

If convenient, please try to drop the collection and reinsert data

**Comment by safehumeng** [comment]
> if you default setup is bounded staleness, there is a 3 seconds window that you insert/delete and data is not visible



> > ### Is there an existing issue for this?
> > 
> > * [x]   I have searched the existing issues
> > 
> > ### Environment
> > ```
> > - Milvus version:v2.3.3
> > - Deployment mode(standalone or cluster):standalone 
> > - MQ type(rocksmq, pulsar or kafka):  default
> > - SDK version(e.g. pymilvus v2.0.0rc2): v2.3.3
> > - OS(Ubuntu or CentOS): CentOS
> > - CPU/Memory: 8/64G
> > - GPU: no use
> > - Others:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Current Behavior
> > When I do query_res = t_milvus.query(expr="", output_fields=["count(_)"]) print(query_res[0]["count(_)"]) got 17 but query_res = t_milvus.query(expr="", limit=16384) print(len(query_res)) got 15
> > ### Expected Behavior
> > expect query_res0 = t_milvus.query(expr="", output_fields=["count(_)"]) query_res1 = t_milvus.query(expr="", limit=16384) should query_res0[0]["count(_)"] == len(query_res1)
> > ### Steps To Reproduce
> > ```
> > I don't know how it happened
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Milvus Log
> > use ./export-milvus-log.sh -i my-release -s 24h got [milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/13359219/milvus-log.tar.gz) but it is empty
> > ### Anything else?
> 
> could you offer the code you reproduce the issue? Did you try to use strong consistency to do query?

from pymilvus import (
    connections,
    utility,
    FieldSchema, CollectionSchema, DataType,
    Collection,
)
connections.connect("default", host=host, port="19530")
db_name = "face"
dim = 512
has = utility.has_collection(db_name)
print(f"Does collection face exist in Milvus: {has}")
fields = [
    FieldSchema(name="pk", dtype=DataType.VARCHAR, is_primary=True, auto_id=False, max_length=100),
    FieldSchema(name="info", dtype=DataType.JSON),
    FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=dim)
]

schema = CollectionSchema(fields, "face db")

face_milvus = Collection(db_name, schema, consistency_level="Strong")


# index = {
#     "index_type": "IVF_FLAT",
#     "metric_type": "IP",
#     "params": {"nlist": 128},
# }
#
# face_milvus.create_index("embeddings", index)
# face_milvus.load()
#
# ids = ["cf524e15-6989-4c61-9d0e-4c67df47a044"]
# query_res = face_milvus.query(f"pk in {ids}")
# print(query_res)
print(face_milvus.num_entities)
query_res = face_milvus.query(expr="", output_fields=["count(*)"])
print(query_res[0]["count(*)"])

query_res = face_milvus.query(expr="", limit=16384)
print(query_res)

**Comment by safehumeng** [comment]
> > ### Is there an existing issue for this?
> > 
> > * [x]   I have searched the existing issues
> > 
> > ### Environment
> > ```
> > - Milvus version:v2.3.3
> > - Deployment mode(standalone or cluster):standalone 
> > - MQ type(rocksmq, pulsar or kafka):  default
> > - SDK version(e.g. pymilvus v2.0.0rc2): v2.3.3
> > - OS(Ubuntu or CentOS): CentOS
> > - CPU/Memory: 8/64G
> > - GPU: no use
> > - Others:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Current Behavior
> > When I do query_res = t_milvus.query(expr="", output_fields=["count(_)"]) print(query_res[0]["count(_)"]) got 17 but query_res = t_milvus.query(expr="", limit=16384) print(len(query_res)) got 15
> > ### Expected Behavior
> > expect query_res0 = t_milvus.query(expr="", output_fields=["count(_)"]) query_res1 = t_milvus.query(expr="", limit=16384) should query_res0[0]["count(_)"] == len(query_res1)
> > ### Steps To Reproduce
> > ```
> > I don't know how it happened
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Milvus Log
> > use ./export-milvus-log.sh -i my-release -s 24h got [milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/13359219/milvus-log.tar.gz) but it is empty
> > ### Anything else?
> 
> could you offer the code you reproduce the issue? Did you try to use strong consistency to do query?


The data was written long ago, so I don't know what operation caused it

**Comment by safehumeng** [comment]
> > ### Is there an existing issue for this?
> > 
> > * [x]   I have searched the existing issues
> > 
> > ### Environment
> > ```
> > - Milvus version:v2.3.3
> > - Deployment mode(standalone or cluster):standalone 
> > - MQ type(rocksmq, pulsar or kafka):  default
> > - SDK version(e.g. pymilvus v2.0.0rc2): v2.3.3
> > - OS(Ubuntu or CentOS): CentOS
> > - CPU/Memory: 8/64G
> > - GPU: no use
> > - Others:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Current Behavior
> > When I do query_res = t_milvus.query(expr="", output_fields=["count(_)"]) print(query_res[0]["count(_)"]) got 17 but query_res = t_milvus.query(expr="", limit=16384) print(len(query_res)) got 15
> > ### Expected Behavior
> > expect query_res0 = t_milvus.query(expr="", output_fields=["count(_)"]) query_res1 = t_milvus.query(expr="", limit=16384) should query_res0[0]["count(_)"] == len(query_res1)
> > ### Steps To Reproduce
> > ```
> > I don't know how it happened
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Milvus Log
> > use ./export-milvus-log.sh -i my-release -s 24h got [milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/13359219/milvus-log.tar.gz) but it is empty
> > ### Anything else?
> 
> could you offer the code you reproduce the issue? Did you try to use strong consistency to do query?

@yanliang567 
I drop the collection and reinsert data 
and got the reason:
```
entities = [
    [],
    [],
    []
]
#face.size = 2
for face in faces:
    entities[0].append("4948fe06-91ea-4a9b-8a36-b496c36e584d")
    entities[1].append({"name": "4948fe06-91ea-4a9b-8a36-b496c36e584d"})
    entities[2].append(face.normed_embedding)
insert_result = face_milvus.upsert(entities)
face_milvus.flush()
```
mean that has duplicate pk in once upsert

**Comment by yanliang567** [comment]
@safehumeng that makes sense, because count(*) return the exact number of the entities, and regular query/search returns results after de-duplicated.

**Comment by safehumeng** [comment]
> @safehumeng that makes sense, because count(*) return the exact number of the entities, and regular query/search returns results after de-duplicated.

thanks！Is there any way to find and fix such errors instead of “ drop the collection and reinsert data ”

**Comment by yanliang567** [comment]
I think you need to do de-dup for inserting into milvus.

**Comment by safehumeng** [comment]
> I think you need to do de-dup before inserting into milvus.

thanks！
