### ISSUE TITLE
[Enhancement]:  Add compaction policy to trigger compaction for segments with index version lower than the current value.

### ISSUE THREAD

**Issue by jiaoew1991** [milvus-io/milvus#28441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Milvus has upgraded the index engine and recorded the version of the index engine in the index data. There are format and performance differences for indexes built by different versions of the engine. We need to use compaction to compact these outdated segments into new ones.

**Comment by xiaofan-luan** [comment]
keep this

**Comment by xiaofan-luan** [comment]
/assign @xige-16 

could you help on this?
