### ISSUE TITLE
milvus when it create index for the vectors， the cpu usage percent will be above 90% at least 10 min，how can I solve it？Is there any configuration I can modify ？

### ISSUE THREAD

**Issue by kyle-kai** [milvus-io/milvus#2844]
the data set is 4000,000 records, and each record is 128 dimensions, I deploy milvus on a 16core, 32G server, when the milvus create the index, the cpu usage percent will be above 90, and it continue 10min or more. If I change the n_list parameter to 10,000, the cost time will more than 30min,  in this time, the search service is basically can not work normally, how can I solve it?

**Comment by tinkerlin** [comment]
**Please provide you Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Comment by kyle-kai** [comment]
1. cent OS 7.X CPU, no GPU
2. Dokcer installed
3. version 0.10.0
4. the milvus configuration file is just the example configuration file which the site given.

**Comment by yhmo** [comment]
Milvus has CPU version and GPU version.
I guess you are using CPU version. For CPU version, build index operation require all cpu cores and much more slower than gpu. When build index operation is running, search operation could not get enough cpu cores to compute and get very bad performance.

To avoid conflict between build index and search, I suggest you use GPU version. The default configuration file will specify the No.0 gpu cards for building index. And for search operation, if nq < 1000, Milvus will use CPU to do searching. So build index operation and search operation will not affect each other.
