### ISSUE TITLE
[Bug]: Milvus fails to start after changing minio's MINIO_ACCESS_KEY

### ISSUE THREAD

**Issue by liyuweihuo** [milvus-io/milvus#28458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.3
- Deployment mode(standalone or cluster):standalone 
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS7.6
- CPU/Memory: 8/22
- GPU: no
- Others:
```

### Current Behavior

first: wget https://github.com/milvus-io/milvus/releases/download/v2.3.3/milvus-standalone-docker-compose.yml -O docker-compose.yml
second: i change docker-compose.yml minio(MINIO_ACCESS_KEY and MINIO_SECRET_KEY)
etcd and minio started successfully. milvus startup failed

### Expected Behavior

milvus startup failed

### Steps To Reproduce

change MINIO_ACCESS_KEY and MINIO_SECRET_KEY

**Comment by liyuweihuo** [comment]
who can help me

**Comment by LoveEachDay** [comment]
@liyuweihuo You'd also change the following two config options in `milvus.yaml`:
```
minio:
   accessKeyID: <new-access-key>
   secretAccessKey: <new-secret-key>
```

**Comment by yanliang567** [comment]
/assign @liyuweihuo 
please try as comment above

/unassign
