### ISSUE TITLE
[Bug]: E2e case may fail randomly with `segment lacks` error

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#28466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: f7d2ab6
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

E2e case may fail randomly with `segment lacks` error

### Expected Behavior

e2e shall passes stably

### Anything else?

Some run:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-28450/1/pipeline
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-28320/21/pipeline

**Comment by yanliang567** [comment]
@congqixia give me a link please?

**Comment by congqixia** [comment]
@yanliang567 pasted some link in the issue content, FYI
