### ISSUE TITLE
[Bug]: Search output a non-existed field behaves differently when dynamicField is enabled or not

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#28465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20231115-0b905078
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1.If enable dynamic field and insert data, search output a non-existed field successfully, and return {} entity
["['id: 1207, distance: 0.8480451703071594, entity: {}', 'id: 141, distance: 0.8437869548797607, entity: {}', 'id: 202,...
2. If disable dynamic field, search output a non-existed gets a error: <MilvusException: (code=65535, message=field int63 not exist)>

The behavior should be consistent regardless of whether dynamicField is enabled.

### Steps To Reproduce

```markdown
@pytest.mark.tags(CaseLabel.L2)
    @pytest.mark.parametrize("enable_dynamic", [True])
    def test_search_with_output_fields_not_exist(self, enable_dynamic):
        """
        target: test search with output fields
        method: search with non-exist output_field
        expected: raise exception
        """
        # 1. initialize with data
        collection_w = self.init_collection_general(prefix, insert_data=True, enable_dynamic_field=enable_dynamic)[0]
        # 2. search
        log.info("test_search_with_output_fields_not_exist: Searching collection %s" %
                 collection_w.name)
        collection_w.search(vectors[:default_nq], default_search_field,
                            default_search_params, default_limit,
                            default_search_exp, output_fields=["int63"],
                            check_task=CheckTasks.err_res,
                            check_items={ct.err_code: 65535,
                                         ct.err_msg: "field int63 not exist"})
```

**Comment by ThreadDao** [comment]
when output_fields=[""]
1. if enable dynamic, error error: parse output field name failed: 
2. if not enable dynamic field, error field  not exist

**Comment by yah01** [comment]
> when output_fields=[""]
> 
> 1. if enable dynamic, error error: parse output field name failed:
> 2. if not enable dynamic field, error field  not exist

this may be expected as we don't require the inserted JSON data to follow the field name rule, an empty string could also be a valid JSON key

**Comment by ThreadDao** [comment]
image: master-20240322-c27db43b-amd64 and 2.4-20240321-6afbc8a6-amd64
Now in the test case, different assertions are made for enabling and disabling dynamic columns for non-existent column names.
