### ISSUE TITLE
[Bug]: not found the privilege name[Alias]

### ISSUE THREAD

**Issue by shawnatmeredith** [milvus-io/milvus#28474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.0
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): N/A (Attu 2.3.2)
- OS(Ubuntu or CentOS): N/A
- CPU/Memory: N/A
- GPU: N/A
- Others:
```

### Current Behavior

When trying to setup the `Alias` privilege with Attu on Milvus 2.3.0 I see this error:

> not found the privilege name[Alias]

All other privileges seem fine when applying.

### Expected Behavior

The `Alias` privilege should apply without error.

### Steps To Reproduce

```markdown
1. Add a new role with Attu
2. Select the `Alias` privilege
3. Save
```

**Comment by xiaofan-luan** [comment]
/assign @SimFG 

please help on it whenever possible

**Comment by SimFG** [comment]
@shawnatmeredith I have check the privilege, and the `alias` isn't existed. I have asked my colleagues who develop attu to deal with this issue.

**Comment by shanghaikid** [comment]
@xiaofan-luan 
Milvus should provide an api that return all valid privileges. 
Right now the list is hardcoded in the sdk,  and the sdk is following the docs, the problem is that there was an error on the doc.  no matter how attu is implemented this feature(via sdk or not), if the doc is wrong, it will be wrong.

**Comment by shanghaikid** [comment]
Invalid privileges are removed in the latest version of attu.

**Comment by SimFG** [comment]
@shawnatmeredith when you have other problem, welcome to open a new issue
