### ISSUE TITLE
[Bug]: MixCoord may failed to start at first time

### ISSUE THREAD

**Issue by haorenfsa** [milvus-io/milvus#28487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.3.3
- Deployment mode(standalone or cluster): cluster, mixcoord mode
- MQ type(rocksmq, pulsar or kafka): kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

MixCoord may failed to start at first time, after restart the pod, it recovers.

I try 5 times,  it occurs twice.

<img width="710" alt="image" src="https://github.com/milvus-io/milvus/assets/15938850/a44c43fc-33e9-4e92-8990-1452cb0f1508">

### Steps To Reproduce

```markdown
deploy with milvus-operator, using following yaml:


---
apiVersion: v1
kind: Namespace
metadata:
  name: mc-sit
---
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: milvus
  namespace: mc-sit
  labels:
    app: milvus
spec:
  mode: "cluster"
  components:
    # runWithSubProcess: true
    proxy:
      ingress:
        hosts: ["mc-sit.milvus.io"]
    mixCoord:
      replicas: 1
  dependencies:
    etcd:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
        values:
          replicaCount: 1
    msgStreamType: kafka
    kafka:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
        values:
          heapOpts: -Xmx512m -Xms320m
          defaultReplicationFactor: 1
          offsetsTopicReplicationFactor: 1
          replicaCount: 1
          zookeeper:
            replicaCount: 1
    storage:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
        values:
          mode: standalone
  config:
    rootCoord:
      enableActiveStandby: true
    dataCoord:
      enableActiveStandby: true
    queryCoord:
      enableActiveStandby: true
    indexCoord:
      enableActiveStandby: true
    milvus:
      log:
        level: debug
    component:
      proxy:
        timeTickInterval: 150
```

### Milvus Log

[before-restart.log](https://github.com/milvus-io/milvus/files/13373077/before-restart.log)
[after-restart.log](https://github.com/milvus-io/milvus/files/13373076/after-restart.log)

**Comment by haorenfsa** [comment]
Looks like queryCoord not activated? 

![c5ecaa3c-2b7b-41e2-900c-7670652bdc99](https://github.com/milvus-io/milvus/assets/15938850/a2b7f4c6-d25b-462c-b256-9284a38ab34c)

**Comment by jaime0815** [comment]
Querycoord waiting for Rootcorod become to healthy and the pod is killed after  5 min.
It seems the Rootcoord is stuck during initializing.
```
[2023/11/16 03:22:06.748 +00:00] [INFO] [rootcoord/meta_table.go:204] ["RootCoord meta table reload done"] [duration=6.791076ms]
```

**Comment by xiaofan-luan** [comment]
if meta is large, it may take longer for root coord to start? do we know which part it stucks?

**Comment by jaime0815** [comment]
> if meta is large, it may take longer for root coord to start? do we know which part it stucks?

Reloading meta has been finished,  but no more logs to know the stuck position. 
![image](https://github.com/milvus-io/milvus/assets/4024711/cfbccf3f-2bc7-40fd-9f89-be1c4bc01924)

**Comment by xiaofan-luan** [comment]
Let's start from one log for each stage?

Other coord init should also follow similar idea.

So we have better control on init process

**Comment by haorenfsa** [comment]
keep active
