### ISSUE TITLE
[Bug]: Meta cannot be cleared after dropping the collection

### ISSUE THREAD

**Issue by xige-16** [milvus-io/milvus#28496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2 && master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. Repeat create collection and drop collection
2. meta key "by-dev/meta/snapshots/root-coord/fields/xxxx " and "by-dev/meta/snapshots/root-coord/partitions/xxx" have never been cleared

### Expected Behavior

Meta can be cleared after dropping collection.

**Comment by yanliang567** [comment]
is it related to #28343, which fails to release the memory after collection dropped. @wayblink 
/assign @wayblink 
/unassign

**Comment by wayblink** [comment]
> is it related to #28343, which fails to release the memory after collection dropped. @wayblink /assign @wayblink /unassign

A little different. @xige-16 FYI, may face the same etcd txn issue in #28343
