### ISSUE TITLE
[Bug]: Connection retry 75, no way to override

### ISSUE THREAD

**Issue by mdcooper-mc** [milvus-io/milvus#28508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

when connecting if creds are wrong milvus retries 75 times with no way to override this property. This means that my jobs wait for a very long time before being able to manage the connection failure.

Please allow this to be manually set or change it to 1.

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version:
> - Deployment mode(standalone or cluster):
> - MQ type(rocksmq, pulsar or kafka):    
> - SDK version(e.g. pymilvus v2.0.0rc2):
> - OS(Ubuntu or CentOS): 
> - CPU/Memory: 
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> when connecting if creds are wrong milvus retries 75 times with no way to override this property. This means that my jobs wait for a very long time before being able to manage the connection failure.
> 
> Please allow this to be manually set or change it to 1.
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

Currently you can tune timeout parameters to avoid retry too many times.
But Agreed we should be able to set retry params

**Comment by mdcooper-mc** [comment]
No you cant, he timeout doesn't work, set it to 0 and it doesn't try, anything else just repeats 75 times...

**Comment by mdcooper-mc** [comment]
This is an issue; to give some context here, this is only causing me an issue because there is a hard coded root username and password.

**Comment by xiaofan-luan** [comment]
> No you cant, he timeout doesn't work, set it to 0 and it doesn't try, anything else just repeats 75 times...

From  the code, if timeout reaches it will throw timeout error

**Comment by xiaofan-luan** [comment]
feel free to fix the issue in pymilvus. 
otherwise @XuanYang-cn will be working on a fix next pymilvus release

**Comment by xiaofan-luan** [comment]
code should be here
https://github.com/milvus-io/pymilvus/blame/142820167b1edc4948f76049659377140de60ae9/pymilvus/decorators.py#L30

**Comment by mdcooper-mc** [comment]
I would love to mate but my boss doent want me working on this. :)

**Comment by xiaofan-luan** [comment]
keep it

We should be able to tune retries and timeout

**Comment by xiaofan-luan** [comment]
/assign @czs007 

please help on it

**Comment by czs007** [comment]
@mdcooper-mc   pleaser refer to https://github.com/milvus-io/pymilvus/issues/1629
The fix for this on the Milvus side will be available in version 2.3.4.
For now, you can update the pymilvus version to 2.3.4, which addresses the problem of timeout not being effective.

**Comment by XuanYang-cn** [comment]
We'll be able to config the retry_times in pymilvus 2.3.5 and 2.4

**Comment by XuanYang-cn** [comment]
/assign @NicoYuan1986
Please help verify

**Comment by Classic298** [comment]
I am experiencing the same issue and it seems it was not solved.

There is no way to set a custom timeout or a higher number of retry allowance.

It is my hardware milvus is running on, why can't i then allow higher number of retries?

The Milvus Error literally reads that the request gets rejected by the grpc RateLimiter middleware.

I want to set higher Rate Limits. I need to set higher rate limits.

**Comment by xiaofan-luan** [comment]
you should be able to specify timeout per request. like
res = client.query(
    collection_name="test_collection",
    filter="id in [6,7,8]",
    timeout=10.0  
)

**Comment by xiaofan-luan** [comment]
I want to set higher Rate Limits -> by default milvus shouldn't have quota limitations, unless it's a backpressure becuase to flush stalled or index  stalled

**Comment by Classic298** [comment]
Yes the flush rate limits are way too low. Unfortunately i couldn't find anything on the docs about this
