### ISSUE TITLE
[Bug]: non-dict JSON could be inserted

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#28519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master/2.3
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

we requires the JSON must be a dict, but the JSON standard accepts string, number as valid JSON.

**Comment by xiaofan-luan** [comment]
so string is also valid JSON?

**Comment by yah01** [comment]
> so string is also valid JSON?

Yes, any value in JSON (number, string, array) is also a valid JSON.

#28602 fixed this
