### ISSUE TITLE
[Enhancement]: Load Operation concurrency should be scaled with more querynodes

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#28529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

From the current implementation, this seems to be a fixed value.
My suggestion is to change to NodeNumber * TaskExecutionCap.
By default the TaskExctuionCap should be set to 32 or 64.

**Comment by yah01** [comment]
The current impl is as the described, scales with QueryNodes, see `querycoordv2/server.go: 705`.

But the TaskExecutionCap per Node is `256` for now

**Comment by xiaofan-luan** [comment]
close it for now.
