### ISSUE TITLE
[Bug]: milvus-2.2.15 arm 构建失败

### ISSUE THREAD

**Issue by zzh928253398** [milvus-io/milvus#28551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.15
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS8
- CPU/Memory:  arm服务器
- GPU: 
- Others:
```

### Current Behavior

I compile the milvus-2.2.15 version in a docker container on the arm server.The base image of the container is ubuntu20.04
The compilation command is ：“make TARGETARCH=arm64 BUILD_DISK_ANN=ON -j16 milvus.”
I didn’t find any “ download errors ” in the logs.
I downloaded the dependency packages that showed download errors in the log before and put them in the specified directory manually.

There are several lines of error message as follows:
c++: error: unrecognized command line option '-mf16c'
c++: error: unrecognized command line option '-mavx2'
c++: error: unrecognized command line option '-msse4.2'
the last failed as follows:
make[4]: Leaving directory '/home/milvus-2.2.15/cmake_build/3rdparty_download/aws-sdk-subbuild/src/aws_sdk_s3_ep'
[ 71%] Completed 'aws_sdk_s3_ep'
make[3]: Leaving directory '/home/milvus-2.2.15/cmake_build'
[ 71%] Built target aws_sdk_s3_ep
make[2]: Leaving directory '/home/milvus-2.2.15/cmake_build'
make[1]: *** [Makefile:166: all] Error 2
make[1]: Leaving directory '/home/milvus-2.2.15/cmake_build'
make: *** [Makefile:138: build-cpp] Error 1

### Steps To Reproduce

```markdown
1、arm build milvus-2.2.15
2、run command "make -e TARGETARCH=arm64 -e BUILD_DISK_ANN=ON -j32 milvus"
3、error occur:
c++: error: unrecognized command line option '-mf16c'
c++: error: unrecognized command line option '-mavx2'
c++: error: unrecognized command line option '-msse4.2'
4、compile faild：
the last failed log is 
make[4]: Leaving directory '/home/milvus-2.2.15/cmake_build/3rdparty_download/aws-sdk-subbuild/src/aws_sdk_s3_ep'
[ 71%] Completed 'aws_sdk_s3_ep'
make[3]: Leaving directory '/home/milvus-2.2.15/cmake_build'
[ 71%] Built target aws_sdk_s3_ep
make[2]: Leaving directory '/home/milvus-2.2.15/cmake_build'
make[1]: *** [Makefile:166: all] Error 2
make[1]: Leaving directory '/home/milvus-2.2.15/cmake_build'
make: *** [Makefile:138: build-cpp] Error 1
```

### Milvus Log

Complete error message  is as follows:
[  5%] Building CXX object knowhere/utils/CMakeFiles/utils_sse.dir/distances_simd_sse.cpp.o
[  5%] Building CXX object knowhere/utils/CMakeFiles/utils_avx.dir/distances_simd_avx.cpp.o
[  7%] Building CXX object knowhere/utils/CMakeFiles/utils_avx512.dir/distances_simd_avx512.cpp.o
[ 10%] Creating directories for 'faiss_ep'
make[3]: Entering directory '/home/milvus-2.2.15/cmake_build'
[ 60%] Building CXX object src/pb/CMakeFiles/milvus_proto.dir/schema.pb.cc.o
[ 60%] Building CXX object src/pb/CMakeFiles/milvus_proto.dir/common.pb.cc.o
[ 60%] Building CXX object src/pb/CMakeFiles/milvus_proto.dir/segcore.pb.cc.o
[ 61%] Building CXX object src/pb/CMakeFiles/milvus_proto.dir/index_cgo_msg.pb.cc.o
[ 61%] Building CXX object src/pb/CMakeFiles/milvus_proto.dir/plan.pb.cc.o
  c++: error: unrecognized command line option '-mf16c'
  c++: error: unrecognized command line option '-mavx2'
[ 12%] No download step for 'faiss_ep'
  c++: error: unrecognized command line option '-msse4.2'
make[6]: *** [knowhere/utils/CMakeFiles/utils_avx.dir/build.make:76: knowhere/utils/CMakeFiles/utils_avx.dir/distances_simd_avx.cpp.o] Error 1
make[6]: Leaving directory '/home/milvus-2.2.15/cmake_build/thirdparty/knowhere/knowhere-bin'
make[5]: *** [CMakeFiles/Makefile2:301: knowhere/utils/CMakeFiles/utils_avx.dir/all] Error 2
make[5]: *** Waiting for unfinished jobs....
make[6]: *** [knowhere/utils/CMakeFiles/utils_sse.dir/build.make:76: knowhere/utils/CMakeFiles/utils_sse.dir/distances_simd_sse.cpp.o] Error 1
make[6]: Leaving directory '/home/milvus-2.2.15/cmake_build/thirdparty/knowhere/knowhere-bin'
make[5]: *** [CMakeFiles/Makefile2:275: knowhere/utils/CMakeFiles/utils_sse.dir/all] Error 2
c++: error: unrecognized command line option '-mf16c'
c++: error: unrecognized command line option '-mavx512f'
c++: error: unrecognized command line option '-mavx512dq'
c++: error: unrecognized command line option '-mavx512bw'
make[6]: *** [knowhere/utils/CMakeFiles/utils_avx512.dir/build.make:76: knowhere/utils/CMakeFiles/utils_avx512.dir/distances_simd_avx512.cpp.o] Error 1
make[6]: Leaving directory '/home/milvus-2.2.15/cmake_build/thirdparty/knowhere/knowhere-bin'
[ 15%] No update step for 'faiss_ep'
make[5]: *** [CMakeFiles/Makefile2:327: knowhere/utils/CMakeFiles/utils_avx512.dir/all] Error 2
...
...
...
make[4]: Leaving directory '/home/milvus-2.2.15/cmake_build/3rdparty_download/aws-sdk-subbuild/src/aws_sdk_s3_ep'
[ 71%] Completed 'aws_sdk_s3_ep'
make[3]: Leaving directory '/home/milvus-2.2.15/cmake_build'
[ 71%] Built target aws_sdk_s3_ep
make[2]: Leaving directory '/home/milvus-2.2.15/cmake_build'
make[1]: *** [Makefile:166: all] Error 2
make[1]: Leaving directory '/home/milvus-2.2.15/cmake_build'
make: *** [Makefile:138: build-cpp] Error 1

**Comment by zzh928253398** [comment]
@yanliang567 @xiaofan-luan

**Comment by yanliang567** [comment]
Arm-compatible images is supported since 2.3.0, please retry it

**Comment by henryhust** [comment]
when i use the 2.3.0 arm docker， it could not run on HUAWEI Kunpeng 920。@yanliang567

**Comment by xiaofan-luan** [comment]
please try 2.3.3?
Milvus 2.2 don't support armm but 2.3.3 should.
We never tried Huawei kunpeng but Apple M2 and AWS graviton works

**Comment by xiaohezi205** [comment]
加我1079361253微信 2.2.12版本arm64镜像免费送
