### ISSUE TITLE
[Enhancement]: Use process's memory info for memory protection

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#28553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

For now, Milvus reads the container's memory info while running in container, or the system memory info while running in a virtual machine for memory protection (loading, throttling...)

This value may be diff with the real Milvus process memory usage.

**Comment by xiaofan-luan** [comment]
good catch.
The container memory contains page cache and other info which might be correct.

@bigsheeper 
could you also verify on your test machines
