### ISSUE TITLE
[Bug]: fail to get shard leaders from QueryCoord:node=43;node offline;channel not available

### ISSUE THREAD

**Issue by 1271653627** [milvus-io/milvus#28563]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.0
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):   pulsar  
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

following is milvus cluster：
![iwEcAqNwbmcDAQTRAeYF0QLqBrAYyFapXSBGzQVIlUcpALsAB9MAAAAAxGBefAgACaJpbQoAC9IAAL1u png_720x720q90](https://github.com/milvus-io/milvus/assets/44419838/94f25c2f-a013-4971-95c9-5c862cc575f8)
following is all of collection in Attu:
![iwEcAqNwbmcDAQTRBuAF0QM6BrCgoFi3aPUOSgVMNXUlQLAAB9MAAAAAxGBefAgACaJpbQoAC9IAAa1j png_720x720q90](https://github.com/milvus-io/milvus/assets/44419838/c2d4cfff-8af3-42cc-8f37-ecb159ceaef5)
![iwEcAqNwbmcDAQTRByoF0QMcBrDRcS6lp32dQAVMRm24QBAAB9MAAAAAxGBefAgACaJpbQoAC9IAAcaP png_720x720q90](https://github.com/milvus-io/milvus/assets/44419838/8e83d4be-ad24-4653-b32a-6c6c13416d21)
![iwEcAqNwbmcDAQTRBusF0QMKBrClNgVQoMhFPwVMR3FwQKcAB9MAAAAAxGBefAgACaJpbQoAC9IAAS3j png_720x720q90](https://github.com/milvus-io/milvus/assets/44419838/a934276f-2240-4cd4-b8a5-0bb1e6dd52bc)
following is the error collection:
![iwEcAqNwbmcDAQTRBzUF0QMlBrDquEaQsp8-uwVMR4MPQKcAB9MAAAAAxGBefAgACaJpbQoAC9IAAVsd png_720x720q90](https://github.com/milvus-io/milvus/assets/44419838/ee391ee1-0bf0-4637-b9bd-66270dcd92f4)
![iwEcAqNwbmcDAQTRBucF0QLPBrDSy6hmTL_rDAVMR5UXAKcAB9MAAAAAxGBefAgACaJpbQoAC9IAAPuz png_720x720q90](https://github.com/milvus-io/milvus/assets/44419838/484b0a5e-ad7e-43df-bb4c-f5027ef88160)
![iwEcAqNwbmcDAQTRB0kF0QNeBrBldfdnkD0gRgVMR_WAQKcAB9MAAAAAxGBefAgACaJpbQoAC9IAAwsy png_720x720q90](https://github.com/milvus-io/milvus/assets/44419838/4ff64c95-8708-4fcf-af5b-adfd95628a0b)

### Expected Behavior

Data Preview can display data properly, and the collection can query data.

### Steps To Reproduce

```markdown
1.deploy a milvus using docker swarm
2.create a collection
3.build index
4.load the collection
5.insert data
```

**Comment by yanliang567** [comment]
dup to #28561
