### ISSUE TITLE
[Bug]: A collection has 1900w entities and loaded.Data Preview of this collection has no data in Attu,and can't query data

### ISSUE THREAD

**Issue by 1271653627** [milvus-io/milvus#28561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.0
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

A collection has 1900w entities and loaded.Data Preview of this collection has no data in Attu,and can't query data
following is milvus cluster：
![iwEcAqNwbmcDAQTRAzsF0QImBrC1ykC65K-1bAVHSJUjQBQAB9MAAAAAxGBefAgACaJpbQoAC9IAA0I6 png_720x720q90](https://github.com/milvus-io/milvus/assets/44419838/53aec6ee-9253-4502-9db1-2927646ef3e1)
The following is the configuration of the Milvus cluster nodes：
![iwEcAqNwbmcDAQTRAeYF0QLqBrAYyFapXSBGzQVIlUcpALsAB9MAAAAAxGBefAgACaJpbQoAC9IAAL1u png_720x720q90](https://github.com/milvus-io/milvus/assets/44419838/e6f1b8d1-3d0d-4970-a9ae-dcefd035cb4f)
The following is collection in Attu：
![iwEcAqNwbmcDAQTRBmUF0QFxBrASIt91qDGHsAVMNO_5gJ4BB9MAAAAAxGBefAgACaJpbQoAC9IAAJ68 png_720x720q90](https://github.com/milvus-io/milvus/assets/44419838/1270f2be-4f1a-449d-a947-235bbb9d0bed)
![iwEcAqNwbmcDAQTRBr8F0QHtBrBU33NsUABprwVMNO_5wJ4BB9MAAAAAxGBefAgACaJpbQoAC9IAALP6 png_720x720q90](https://github.com/milvus-io/milvus/assets/44419838/3596f339-6b36-4fc6-b17f-220f5f207ba2)
![iwEcAqNwbmcDAQTRBtsF0QGmBrAqDBMp0Ku6BAVMNO_5wJ4CB9MAAAAAxGBefAgACaJpbQoAC9IAAKkz png_720x720q90](https://github.com/milvus-io/milvus/assets/44419838/f9f89b2d-20ff-424c-b650-fc404a59a274)
![iwEcAqNwbmcDAQTRBuYF0QHNBrDiBa9fs-bGFAVMNO_5wJ4AB9MAAAAAxGBefAgACaJpbQoAC9IAAJMi png_720x720q90](https://github.com/milvus-io/milvus/assets/44419838/37899805-b263-40e1-9dec-28ec5c248fce)
![iwEcAqNwbmcDAQTRBtYF0QMCBrDWj2BDzv6k1AVMNO_5gJ4AB9MAAAAAxGBefAgACaJpbQoAC9IAAQ9f png_720x720q90](https://github.com/milvus-io/milvus/assets/44419838/80cd61ee-9d7c-41ea-a927-77a49d655b0c)
![iwEcAqNwbmcDAQTRBuAF0QM6BrCgoFi3aPUOSgVMNXUlQLAAB9MAAAAAxGBefAgACaJpbQoAC9IAAa1j png_720x720q90](https://github.com/milvus-io/milvus/assets/44419838/e16a714d-ead9-4c4d-bbb3-da18db7a072c)

### Expected Behavior

Data Preview can display data properly, and the collection can query data.

### Steps To Reproduce

```markdown
1.deploy a milvus using docker swarm
2.create a collection
3.build index
4.load the collection
5.insert data
```

**Comment by yanliang567** [comment]
@1271653627 Could you please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.

We need full milvus logs to address what was happening?

/assign @1271653627

**Comment by 1271653627** [comment]
@yanliang567 The Milvus cluster is set up using Docker Swarm, and there is no Docker Compose. After reviewing the log exporting script, I feel like my deployment method might not be compatible with the script you provided for exporting log.

**Comment by 1271653627** [comment]
@yanliang567  Could you provide an alternative way to retrieve logs, or specify which service's logs you need? I can obtain logs for a specific service or a few services.

**Comment by yanliang567** [comment]
Sorry, I don't have exporting scripts for Docker Swarm, could you please update one based on the one we provided?

**Comment by 1271653627** [comment]
Sorry, I might not be able to deploy using the method you provided. Which node's logs do you need? I can export them for you. @yanliang567

**Comment by 1271653627** [comment]
[milvus-proxy&milvus-querynode1.zip](https://github.com/milvus-io/milvus/files/13411747/milvus-proxy.milvus-querynode1.zip)
There is milvus proxy and querynode1 logs @yanliang567 ,thanks for your assistance

**Comment by xiaofan-luan** [comment]
error="limit=160: request limit exceeded"

Are you set some rate limit on S3?

**Comment by xiaofan-luan** [comment]
it seems that you have multiple querynodes and we only get log from 1 node.
From what we can get seems that we get a quota limitation and this might be from the object storage

**Comment by xiaofan-luan** [comment]
The current log you offered is not completed enough.
query node failed because there are too many segments.

To learn more details, we need
1. querycoord logs
2. or querynode logs (using export log scripts should be easier)
3. use birdwatcher https://github.com/milvus-io/birdwatcher to inspect how many segments are there in your collection and file stats of each segment

**Comment by 1271653627** [comment]
attach is logs.
[query_querycoord_log.tar.gz](https://github.com/milvus-io/milvus/files/13455576/query_querycoord_log.tar.gz)
following is collections and segments info from birdwatcher:
![iwEcAqNwbmcDAQTRBBoF0QMQBrCaM_oLdhS19AVRbnc1tzQAB9MAAAAAxGBefAgACaJpbQoAC9IAA9nU png_720x720q90](https://github.com/milvus-io/milvus/assets/44419838/2d7ff44e-eea2-4c90-9e7b-2db168e88851)
![iwEcAqNwbmcDAQTRBBoF0QKPBrAywvDbOAzA0QVRbnc1tzQDB9MAAAAAxGBefAgACaJpbQoAC9IAAzCM png_720x720q90](https://github.com/milvus-io/milvus/assets/44419838/e4efa42e-46b8-4914-8f3b-db4cdc18ebcb)
![iwEcAqNwbmcDAQTRBGEF0QMgBrCwGx7pVIQP8wVRbnc1QlcAB9MAAAAAxGBefAgACaJpbQoAC9IABAg- png_720x720q90](https://github.com/milvus-io/milvus/assets/44419838/ebb7df46-1266-4238-ad9c-72b824e0c4b4)
![iwEcAqNwbmcDAQTRBDMF0QMfBrAX-LC7XQzpZQVRbnc1tzQBB9MAAAAAxGBefAgACaJpbQoAC9IAA-YG png_720x720q90](https://github.com/milvus-io/milvus/assets/44419838/1fbf928f-4101-487f-ae14-c7e0e50e2d44)
![iwEcAqNwbmcDAQTRBEMF0QLgBrD7fhPJoZ7xzQVRbnc1tzQCB9MAAAAAxGBefAgACaJpbQoAC9IAA4y0 png_720x720q90](https://github.com/milvus-io/milvus/assets/44419838/e15c2130-8e14-440f-834c-19bf8ada3128)
![iwEcAqNwbmcDAQTRBDwF0QIYBrDe5ldsZNjprwVRbnc1QlcBB9MAAAAAxGBefAgACaJpbQoAC9IAAo7J png_720x720q90](https://github.com/milvus-io/milvus/assets/44419838/c110145f-8090-4d72-8ff3-b249a0e00123)
![iwEcAqNwbmcDAQTRAboF0QMoBrBTwycllJyxRQVRbrryt68AB9MAAAAAxGBefAgACaJpbQoAC9IABBiQ png_720x720q90](https://github.com/milvus-io/milvus/assets/44419838/a8d488b7-c1c7-4b31-8880-d08fbf118b0c)
![iwEcAqNwbmcDAQTRAakF0QNPBrCI_zxwyQaGMAVRbrr0qjsAB9MAAAAAxGBefAgACaJpbQoAC9IABHZ0 png_720x720q90](https://github.com/milvus-io/milvus/assets/44419838/d5eea22b-5edf-4f27-998a-66308c5a31e7)
![iwEcAqNwbmcDAQTRAawF0QNPBrCF9RhIj_uvIwVRbrr1s6IAB9MAAAAAxGBefAgACaJpbQoAC9IABH1y png_720x720q90](https://github.com/milvus-io/milvus/assets/44419838/adde8608-f913-4190-8161-c99cc5855d25)
![iwEcAqNwbmcDAQTRAacF0QNRBrBpQzIcoQq0iQVRbrsDZqAAB9MAAAAAxGBefAgACaJpbQoAC9IABIPM png_720x720q90](https://github.com/milvus-io/milvus/assets/44419838/263f7447-aa57-437a-a735-59b385a2afad)
![iwEcAqNwbmcDAQTRAbYF0QNBBrAqRQN3hvIAmwVRbrsAiHkAB9MAAAAAxGBefAgACaJpbQoAC9IABHAK png_720x720q90](https://github.com/milvus-io/milvus/assets/44419838/d7345b1b-73ff-4ebe-9aec-2a4b6374d2a0)
thanks for you help@xiaofan-luan

**Comment by yanliang567** [comment]
@1271653627 any chance that you could retry on milvus 2.3.4, which is going to be release this week
