### ISSUE TITLE
[Bug]: HNSW may return less results

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#28603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I noticed that the testcase `test_search_output_field_vector_after_different_index_metrics` failed occasionally, and it's always the HNSW search returns 1999 results, but expected 2000.

The index params is:
`M=48, efConstruction=500`

The search params is:
`topk=2000, ef=32768`

The dataset is random 2000 entities.

**Comment by yah01** [comment]
failed pipeline: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-28424/28/pipeline/

**Comment by yanliang567** [comment]
/assign @liliu-z 
i remember there was a similar issue before. could you please help to take a look?
/unassign

**Comment by fjunqueira** [comment]
Not sure if related to this (or if its usefull info at all), but I'm having a similar problem on zilliz. Sometimes when running a search with `topK=3` I get 2 results in the response (this happens in a large collection, not sure how many documents).

On zilliz I'm using the `AUTOINDEX` index type. I don't know if it uses HNSW under the hood.

**Comment by xiaofan-luan** [comment]
> Not sure if related to this (or if its usefull info at all), but I'm having a similar problem on zilliz. Sometimes when running a search with `topK=3` I get 2 results in the response (this happens in a large collection, not sure how many documents).
> 
> On zilliz I'm using the `AUTOINDEX` index type. I don't know if it uses HNSW under the hood.

Thanks for the feedback.
What kind of metrics you are using?
Is there any filtering?

**Comment by fjunqueira** [comment]
No problem!

This is the index creation code:

```kt
        client.createIndex(
            CreateIndexParam.newBuilder()
                .withCollectionName(collectionName)
                .withFieldName("embeddings")
                .withIndexType(IndexType.AUTOINDEX)
                .withMetricType(MetricType.L2)
                .withExtraParam("{\"nlist\":1024}")
                .withSyncMode(false)
                .build()
        )
```

These are the search parameters:

```kt
        SearchParam.newBuilder()
            .withCollectionName(collectionName)
            .withVectorFieldName("embeddings")
            .withVectors(input)
            .withParams("{\"metric_type\": \"L2\"}")
            .withTopK(sectionsToReturn)
            .withOutFields(fieldsToSearch)
            .withExpr("customer == '${customer}' AND label == '${label}'")
            .build()
```

There is some filtering done, but we have made multiple checks and we are sure that there are more than three entries that satisfy the filter condition.

Maybe it's also noteworthy that the problem seems to happen only for specific input vectors. Depending on the query vector, all 3 entries will be returned as expected. We haven't been able to pinpoint what in the query vector causes the issue though.

**Comment by congqixia** [comment]
@fjunqueira quick question, are there any duplicated entries(with same primary key) in your collection?

**Comment by liliu-z** [comment]
> No problem!
> 
> This is the index creation code:
> 
> ```kotlin
>         client.createIndex(
>             CreateIndexParam.newBuilder()
>                 .withCollectionName(collectionName)
>                 .withFieldName("embeddings")
>                 .withIndexType(IndexType.AUTOINDEX)
>                 .withMetricType(MetricType.L2)
>                 .withExtraParam("{\"nlist\":1024}")
>                 .withSyncMode(false)
>                 .build()
>         )
> ```
> 
> These are the search parameters:
> 
> ```kotlin
>         SearchParam.newBuilder()
>             .withCollectionName(collectionName)
>             .withVectorFieldName("embeddings")
>             .withVectors(input)
>             .withParams("{\"metric_type\": \"L2\"}")
>             .withTopK(sectionsToReturn)
>             .withOutFields(fieldsToSearch)
>             .withExpr("customer == '${customer}' AND label == '${label}'")
>             .build()
> ```
> 
> There is some filtering done, but we have made multiple checks and we are sure that there are more than three entries that satisfy the filter condition.
> 
> Maybe it's also noteworthy that the problem seems to happen only for specific input vectors. Depending on the query vector, all 3 entries will be returned as expected. We haven't been able to pinpoint what in the query vector causes the issue though.

@fjunqueira Any estimation on the filtering ratio (Num of Vectors get filtered out/Total Num of Vectors) ?

**Comment by fjunqueira** [comment]
> @fjunqueira quick question, are there any duplicated entries(with same primary key) in your collection?

There is a possibility of this happening. We are using our mongodb document id as the entry id in zilliz (and when an update is performed in our mongo document, we do a delete-insert in zilliz). Perhaps if something goes wrong during the deletion, we might be inserting duplicates. I'll give it a check.



> > No problem!
> > This is the index creation code:
> > ```kotlin
> >         client.createIndex(
> >             CreateIndexParam.newBuilder()
> >                 .withCollectionName(collectionName)
> >                 .withFieldName("embeddings")
> >                 .withIndexType(IndexType.AUTOINDEX)
> >                 .withMetricType(MetricType.L2)
> >                 .withExtraParam("{\"nlist\":1024}")
> >                 .withSyncMode(false)
> >                 .build()
> >         )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > These are the search parameters:
> > ```kotlin
> >         SearchParam.newBuilder()
> >             .withCollectionName(collectionName)
> >             .withVectorFieldName("embeddings")
> >             .withVectors(input)
> >             .withParams("{\"metric_type\": \"L2\"}")
> >             .withTopK(sectionsToReturn)
> >             .withOutFields(fieldsToSearch)
> >             .withExpr("customer == '${customer}' AND label == '${label}'")
> >             .build()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > There is some filtering done, but we have made multiple checks and we are sure that there are more than three entries that satisfy the filter condition.
> > Maybe it's also noteworthy that the problem seems to happen only for specific input vectors. Depending on the query vector, all 3 entries will be returned as expected. We haven't been able to pinpoint what in the query vector causes the issue though.
> 
> @fjunqueira Any estimation on the filtering ratio (Num of Vectors get filtered out/Total Num of Vectors) ?

I'd say the ratio sits around 0.03 on average. Additionally, I've noticed the following behavior: When I remove the filter, I consistently receive 3 documents, as expected with topK=3. In most cases, the third document appears to be one that would have been filtered out if the filter were applied.

I've also observed in one instance that increasing the topK parameter to a larger number, while keeping the filter applied, affects the output. For example, if I set topK to 10 and consider the top 3 results, I get different outcomes compared to when I set topK to 30 and then look at the top 3 results.

Not sure if I can reproduce this though.

**Comment by fjunqueira** [comment]
FYI: updated my previous reply with the correct ratio

**Comment by liliu-z** [comment]
> > @fjunqueira quick question, are there any duplicated entries(with same primary key) in your collection?
> 
> There is a possibility of this happening. We are using our mongodb document id as the entry id in zilliz (and when an update is performed in our mongo document, we do a delete-insert in zilliz). Perhaps if something goes wrong during the deletion, we might be inserting duplicates. I'll give it a check.
> 
> > > No problem!
> > > This is the index creation code:
> > > ```kotlin
> > >         client.createIndex(
> > >             CreateIndexParam.newBuilder()
> > >                 .withCollectionName(collectionName)
> > >                 .withFieldName("embeddings")
> > >                 .withIndexType(IndexType.AUTOINDEX)
> > >                 .withMetricType(MetricType.L2)
> > >                 .withExtraParam("{\"nlist\":1024}")
> > >                 .withSyncMode(false)
> > >                 .build()
> > >         )
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > These are the search parameters:
> > > ```kotlin
> > >         SearchParam.newBuilder()
> > >             .withCollectionName(collectionName)
> > >             .withVectorFieldName("embeddings")
> > >             .withVectors(input)
> > >             .withParams("{\"metric_type\": \"L2\"}")
> > >             .withTopK(sectionsToReturn)
> > >             .withOutFields(fieldsToSearch)
> > >             .withExpr("customer == '${customer}' AND label == '${label}'")
> > >             .build()
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > There is some filtering done, but we have made multiple checks and we are sure that there are more than three entries that satisfy the filter condition.
> > > Maybe it's also noteworthy that the problem seems to happen only for specific input vectors. Depending on the query vector, all 3 entries will be returned as expected. We haven't been able to pinpoint what in the query vector causes the issue though.
> > 
> > 
> > @fjunqueira Any estimation on the filtering ratio (Num of Vectors get filtered out/Total Num of Vectors) ?
> 
> I'd say the ratio sits around 0.95 on average. Additionally, I've noticed the following behavior: When I remove the filter, I consistently receive 3 documents, as expected with topK=3. In most cases, the third document appears to be one that would have been filtered out if the filter were applied.
> 
> I've also observed in one instance that increasing the topK parameter to a larger number, while keeping the filter applied, affects the output. For example, if I set topK to 10 and consider the top 3 results, I get different outcomes compared to when I set topK to 30 and then look at the top 3 results.
> 
> Not sure if I can reproduce this though.

Double confirm, your cases is:
1. No filter, top3 get 3 results as expected.
2. With filter, top3 get 2 results, and the 3rd disappear.
Questions:
1. In the case with filter, did the disappeared 3rd one match the filter (should be filtered out)?
2. In the case with filter, did we only get 2 results, or still 3 with a different 3rd one.

**Comment by fjunqueira** [comment]
> > > @fjunqueira quick question, are there any duplicated entries(with same primary key) in your collection?
> > 
> > 
> > There is a possibility of this happening. We are using our mongodb document id as the entry id in zilliz (and when an update is performed in our mongo document, we do a delete-insert in zilliz). Perhaps if something goes wrong during the deletion, we might be inserting duplicates. I'll give it a check.
> > > > No problem!
> > > > This is the index creation code:
> > > > ```kotlin
> > > >         client.createIndex(
> > > >             CreateIndexParam.newBuilder()
> > > >                 .withCollectionName(collectionName)
> > > >                 .withFieldName("embeddings")
> > > >                 .withIndexType(IndexType.AUTOINDEX)
> > > >                 .withMetricType(MetricType.L2)
> > > >                 .withExtraParam("{\"nlist\":1024}")
> > > >                 .withSyncMode(false)
> > > >                 .build()
> > > >         )
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > These are the search parameters:
> > > > ```kotlin
> > > >         SearchParam.newBuilder()
> > > >             .withCollectionName(collectionName)
> > > >             .withVectorFieldName("embeddings")
> > > >             .withVectors(input)
> > > >             .withParams("{\"metric_type\": \"L2\"}")
> > > >             .withTopK(sectionsToReturn)
> > > >             .withOutFields(fieldsToSearch)
> > > >             .withExpr("customer == '${customer}' AND label == '${label}'")
> > > >             .build()
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > There is some filtering done, but we have made multiple checks and we are sure that there are more than three entries that satisfy the filter condition.
> > > > Maybe it's also noteworthy that the problem seems to happen only for specific input vectors. Depending on the query vector, all 3 entries will be returned as expected. We haven't been able to pinpoint what in the query vector causes the issue though.
> > > 
> > > 
> > > @fjunqueira Any estimation on the filtering ratio (Num of Vectors get filtered out/Total Num of Vectors) ?
> > 
> > 
> > I'd say the ratio sits around 0.95 on average. Additionally, I've noticed the following behavior: When I remove the filter, I consistently receive 3 documents, as expected with topK=3. In most cases, the third document appears to be one that would have been filtered out if the filter were applied.
> > I've also observed in one instance that increasing the topK parameter to a larger number, while keeping the filter applied, affects the output. For example, if I set topK to 10 and consider the top 3 results, I get different outcomes compared to when I set topK to 30 and then look at the top 3 results.
> > Not sure if I can reproduce this though.
> 
> Double confirm, your cases is:
> 
> 1. No filter, top3 get 3 results as expected.
> 2. With filter, top3 get 2 results, and the 3rd disappear.
>    Questions:
> 3. In the case with filter, did the disappeared 3rd one match the filter (should be filtered out)?
> 4. In the case with filter, did we only get 2 results, or still 3 with a different 3rd one.

1. Correct
2. Correct
3. Yes, the third one should be filtered out. I expected another entry would take its place.
4. Only 2 results

**Comment by congqixia** [comment]
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-28700/3/pipeline 
other pipeline failed, FYI

**Comment by liliu-z** [comment]
> > > > @fjunqueira quick question, are there any duplicated entries(with same primary key) in your collection?
> > > 
> > > 
> > > There is a possibility of this happening. We are using our mongodb document id as the entry id in zilliz (and when an update is performed in our mongo document, we do a delete-insert in zilliz). Perhaps if something goes wrong during the deletion, we might be inserting duplicates. I'll give it a check.
> > > > > No problem!
> > > > > This is the index creation code:
> > > > > ```kotlin
> > > > >         client.createIndex(
> > > > >             CreateIndexParam.newBuilder()
> > > > >                 .withCollectionName(collectionName)
> > > > >                 .withFieldName("embeddings")
> > > > >                 .withIndexType(IndexType.AUTOINDEX)
> > > > >                 .withMetricType(MetricType.L2)
> > > > >                 .withExtraParam("{\"nlist\":1024}")
> > > > >                 .withSyncMode(false)
> > > > >                 .build()
> > > > >         )
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > These are the search parameters:
> > > > > ```kotlin
> > > > >         SearchParam.newBuilder()
> > > > >             .withCollectionName(collectionName)
> > > > >             .withVectorFieldName("embeddings")
> > > > >             .withVectors(input)
> > > > >             .withParams("{\"metric_type\": \"L2\"}")
> > > > >             .withTopK(sectionsToReturn)
> > > > >             .withOutFields(fieldsToSearch)
> > > > >             .withExpr("customer == '${customer}' AND label == '${label}'")
> > > > >             .build()
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > There is some filtering done, but we have made multiple checks and we are sure that there are more than three entries that satisfy the filter condition.
> > > > > Maybe it's also noteworthy that the problem seems to happen only for specific input vectors. Depending on the query vector, all 3 entries will be returned as expected. We haven't been able to pinpoint what in the query vector causes the issue though.
> > > > 
> > > > 
> > > > @fjunqueira Any estimation on the filtering ratio (Num of Vectors get filtered out/Total Num of Vectors) ?
> > > 
> > > 
> > > I'd say the ratio sits around 0.95 on average. Additionally, I've noticed the following behavior: When I remove the filter, I consistently receive 3 documents, as expected with topK=3. In most cases, the third document appears to be one that would have been filtered out if the filter were applied.
> > > I've also observed in one instance that increasing the topK parameter to a larger number, while keeping the filter applied, affects the output. For example, if I set topK to 10 and consider the top 3 results, I get different outcomes compared to when I set topK to 30 and then look at the top 3 results.
> > > Not sure if I can reproduce this though.
> > 
> > 
> > Double confirm, your cases is:
> > 
> > 1. No filter, top3 get 3 results as expected.
> > 2. With filter, top3 get 2 results, and the 3rd disappear.
> >    Questions:
> > 3. In the case with filter, did the disappeared 3rd one match the filter (should be filtered out)?
> > 4. In the case with filter, did we only get 2 results, or still 3 with a different 3rd one.
> 
> 1. Correct
> 2. Correct
> 3. Yes, the third one should be filtered out. I expected another entry would take its place.
> 4. Only 2 results

1. For filtering ratio between 80~95% (roughly est number), the accuracy will decrease. We made a big optimization on the latest version (beta on the Cloud now).
2. In your case, it is possible:
  1. Your filtering ratio fell into this inaccurate range.
  2. There are only 2 results in your base that meet the filtering criteria
4. About why larger K can work, because larger K will ask algorithm to lookup more candidates which can provide better accuracy.

**Comment by liliu-z** [comment]
> https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-28700/3/pipeline other pipeline failed, FYI

This is caused by some isolated points in the graph, and is expected. We can try to turn to BF if K>=NumOfSegemnt @chasingegg

**Comment by yah01** [comment]
As we have not seen this problem for a long time, close it for now
