### ISSUE TITLE
[Bug]: Enhance constraints for inserting duplicate primary key data.

### ISSUE THREAD

**Issue by lentitude2tk** [milvus-io/milvus#28615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.3
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka): None
- SDK version(e.g. pymilvus v2.0.0rc2): go-sdk
- OS(Ubuntu or CentOS): None
- CPU/Memory: None
- GPU: None
- Others: None
```

### Current Behavior

1. Allowing the insertion of data with duplicate primary keys.
```
List<List<Float>> vectors = generateFloatVectors(count);
Random ran = new Random();
List<Long> ages = new ArrayList<>();
Long data = ran.nextLong();
for (long i = 0L; i < count; ++i) {
    ages.add(data);
}

List<InsertParam.Field> fields = new ArrayList<>();
fields.add(new InsertParam.Field(ID_FIELD, ages));
fields.add(new InsertParam.Field(VECTOR_FIELD, vectors));

InsertParam insertParam = InsertParam.newBuilder()
        .withCollectionName(COLLECTION_NAME)
        .withFields(fields)
        .build();

R<MutationResult> response = milvusClient.insert(insertParam);
```
2. During query/search, duplicate data will be deduplicated. Once there are duplicates, the Limit parameter provided through Restful or SDK requests may be unreliable. For example, with a Query Limit=10, you might actually retrieve only 5 unique records because of 5 duplicates. However, with Query Limit=11, you might get 6 records or still just 5.
3. Similarly, situations may arise where querying with offset=0&&limit=2 yields (a, b), but when using offset=2&&limit=2, you can still retrieve (b, c) because the current mechanism involves fetching data first and then deduplicating.
4. The results obtained from count(*) queries are not deduplicated, making it impossible to reliably combine them with the limit parameter.

### Expected Behavior

1. Restricting the insertion of duplicate primary key data or automatically using upsert for duplicate data.
2. Avoid deduplication in query/search results; even if deduplication is performed, it should be done first, followed by a secondary processing of offset/limit. However, this approach to overall data processing can be cumbersome, and estimating the amount of data to be retrieved becomes challenging.
3. The behavior of count() should align with that of query/search. If deduplication is applied in query/search, count() results should also be deduplicated. This allows users to obtain relevant data through pagination. However, this conflicts with the actual data volume.

In essence, resolving similar issues through method 1 is still the preferred solution, and it is hoped that Milvus will provide a better resolution.

### Steps To Reproduce

```markdown
1. Insert 20 records, with 10 of them being duplicates.
2. Retrieve the first 10 records based on the limit. Ultimately, only 1 records can be obtained; however, there are actually more data records available.
```

### Milvus Log

Retrieve logs related to skipping duplicated queries.
![image](https://github.com/milvus-io/milvus/assets/108672767/28503630-8cca-4c34-8b6f-3d9681629ad4)

**Comment by yanliang567** [comment]
/assign @jiaoew1991 
any plans to enhance it?
/unassign
