### ISSUE TITLE
[Bug]: One of querynodes OOM and the other querynode memory keeps stable, when doing upsert

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#28620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3-20231119-1383680b
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
```

### Current Behavior

One of querynodes becomes OOM, and the other one keeps stable
![image](https://github.com/milvus-io/milvus/assets/82361606/bbb8b008-3d0e-482a-8944-c0a6da0d2218)

### Expected Behavior

the 2 querynodes shall be balance for memory usage to avoid OOM

### Steps To Reproduce

```markdown
1. Deploy miluvs cluster with 2 querynode(memory limit 32GB)
2. insert 2m_768d data
3. keep searching
4. do upsert(5000 entities per time for 200 times)
```

### Milvus Log

Milvus pod names in devops cluster:
```
yanliang-cd-hnsw2-milvus-datanode-5556ccc47c-xl9pl             1/1     Running            0               3h12m   10.102.6.146    devops-node10   <none>           <none>
yanliang-cd-hnsw2-milvus-indexnode-5754d8dddb-mzs87            1/1     Running            0               3h12m   10.102.9.106    devops-node13   <none>           <none>
yanliang-cd-hnsw2-milvus-indexnode-5754d8dddb-ngm2x            1/1     Running            0               3h12m   10.102.6.147    devops-node10   <none>           <none>
yanliang-cd-hnsw2-milvus-mixcoord-986f654cf-llfwh              1/1     Running            0               3h12m   10.102.10.144   devops-node20   <none>           <none>
yanliang-cd-hnsw2-milvus-proxy-7cd86885dc-nvfx6                1/1     Running            0               3h12m   10.102.6.144    devops-node10   <none>           <none>
yanliang-cd-hnsw2-milvus-querynode-69fc777684-dt9hv            1/1     Running            1 (42m ago)     3h12m   10.102.9.111    devops-node13   <none>           <none>
yanliang-cd-hnsw2-milvus-querynode-69fc777684-dzzsl            1/1     Running            0               3h12m   10.102.7.2      devops-node11   <none>           <none>

```

### Anything else?

Sometimes the querynode(delegator) does not OOM, but memory usage is very high, and keeps high even upsert requests stopped for hours. So I think the balance policy is not working in this case.

**Comment by xiaofan-luan** [comment]
@yanliang567 
do we have any pprof on this?

**Comment by yanliang567** [comment]
the pods are still running, and you can get the pprof by visist
_<pod_ip>:9091/debug/pprof/goroutine?debug=2
<pod_ip>:9091/debug/pprof/heap_

**Comment by yanliang567** [comment]
I rerun a similar scenario that use upsert as insert(many users do that to ensure no dup pk into milvus):
1. create an empty collection with 768d vector field, and build index
2. upsert 2000 entities for 1000 times (PKs in one upsert request is unique)
result: 
a) one of querynode memory extremely increased 
![image](https://github.com/milvus-io/milvus/assets/82361606/4acc6f2c-4fa5-4ab3-982c-c46870714fa5)
b) search/query fails during upserting(will recover a few mins after upsert ocmpleted)
c)pprof
![image](https://github.com/milvus-io/milvus/assets/82361606/644f4e38-6f30-4f80-ad76-87cedf209c20)

**Comment by congqixia** [comment]
/assign @aoiasd 
please help investigate this

**Comment by yanliang567** [comment]
the msgstream memory leak issue is verified fix.
![image](https://github.com/milvus-io/milvus/assets/82361606/cbb176f1-c86a-47de-8737-c4e9ceca2c91)
 But meet a new issue that interrupt search and query when doing upsert. will track the new issue in #29332
