### ISSUE TITLE
[Bug]: 如果使用java的sdk的话，在使用搜索的时候，sdk里面要求向量必须为List<List<Float>>，但是float类型在java里面是有精度问题的，我们的数据库里面目前精度是小数点后面20位，看能否java版本SDK采用bigDecimal

### ISSUE THREAD

**Issue by youngStarlit** [milvus-io/milvus#28640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

[Bug]: 如果使用java的sdk的话，在使用搜索的时候，sdk里面要求向量必须为List<List<Float>>，但是float类型在java里面是有精度问题的，我们的数据库里面目前精度是小数点后面20位，看能否java版本SDK采用bigDecimal

**Comment by xiaofan-luan** [comment]
Milvus currently only support Float32 vectors.

And it seems that all models is generally under int8, fp16 and fp32. There is not much difference on recall for double or larger float numbers.

**Comment by xiaofan-luan** [comment]
by the way, please refine your issue name into english, thanks

**Comment by youngStarlit** [comment]
What I’m talking about here is the problem in the SDK. In the float type in Java, only about 6 digits can be retained after the decimal point. Since I use cosine similarity (cos (θ)), the value range is from -1 (not similar). ) to 1 (very similar), the larger the amount of data, the greater the deviation, so it is recommended to change it to bigdecimal, because it has higher accuracy and will not lose accuracy.

**Comment by yhmo** [comment]
Milvus stores the vectors as float32 and computes the similarity as float32, then what is the difference that you input single-precision or double-precision values?

The RPC proto between Milvus and SDK is using float32 to transfer vectors. Even SDK allows you to input double-precision, your 
values will be converted to float32 before RPC call.

**Comment by yhmo** [comment]
ANN search is "Approximate Nearest Neighbor search". The "Approximate" already indicates it doesn't require high digit precision.

Assume there are two photos, we convert them to two vectors. Then we use ANN search to compare the two photos with another photo. The similarity of A and C is 0.888888888888881, the similarity of B and C is 0.888888888888882, can we say A is more similar than B?

**Comment by youngStarlit** [comment]
你没理解我的意思啊，我说的是java里面float是只能保留小数点后6位左右的数字，像你说的0.888888888888881，那么float就可能是0.888888或者是0.888889，这个相差的偏移量就会很大了，

**Comment by yhmo** [comment]
0.888888和0.888889对于ANN search来说没什么区别。内部所于的计算都是基于float32来做的，就算你输入float64的值，也一样会被转为float32。高维向量本身就是一个模糊概念，搜索也是“相似搜索”。比如有两个人，一个人的头发数量是888888888888880根，另一个人的头发数量是888888888888881根，那你说他俩长得像不像？

**Comment by yhmo** [comment]
Close this disscussion.
