### ISSUE TITLE
how to insert  structured data to milvus

### ISSUE THREAD

**Issue by vdogmcgee** [milvus-io/milvus#2864]
I am doing face recognition and want to insert some structured data into milvus, such as name, label, etc. When I query a certain person, I can get information about that person, so does milvus support the insertion of structured data? If it supports If so, how should I insert this data?

**Comment by yhmo** [comment]
At present Milvus doesn't support insert structured data. The new version with this feature is still in developing.
You can store structured data in OLTP database or key-value database, mapping milvus vectors by a 64 bit integer ID.

**Comment by ZonghaoWang** [comment]
milvus recommend two methods past, one is by postgres record the id of feature(first feature and property last), one is partition the table by category property(first property and feature last). but these methods not brief I think.

so, how to merge the feature ann search and property fileter organic？
