### ISSUE TITLE
[Enhancement]: Add efficient distance computations in Go 

### ISSUE THREAD

**Issue by chasingegg** [milvus-io/milvus#28656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

calc_distance is no longer used as an external API but still needed internally. We could do some distance computations at Go side like delegator, https://github.com/mmcloughlin/avo is a good tool to generate efficient go assembly, we would like to adopt it.

### Why is this needed?

related to #28410 , we get a 10x improvement on distance calculation by using simd over pure go implementation.
```
b.Run("pure go", func(b *testing.B) {
for i := 0; i < b.N; i++ {
	L2PureGo(x, y)
}
})

b.Run("AVX", func(b *testing.B) {
for i := 0; i < b.N; i++ {
	asm.L2(x, y)
}
})
```
result
```
Benchmark_L2_PureGo_VS_AVX/vector_dim=128
=== RUN   Benchmark_L2_PureGo_VS_AVX/vector_dim=128/pure_go
Benchmark_L2_PureGo_VS_AVX/vector_dim=128/pure_go
Benchmark_L2_PureGo_VS_AVX/vector_dim=128/pure_go-12            18732463                65.83 ns/op            0 B/op          0 allocs/op
=== RUN   Benchmark_L2_PureGo_VS_AVX/vector_dim=128/AVX
Benchmark_L2_PureGo_VS_AVX/vector_dim=128/AVX
Benchmark_L2_PureGo_VS_AVX/vector_dim=128/AVX-12                143581339                8.312 ns/op           0 B/op          0 allocs/op
=== RUN   Benchmark_L2_PureGo_VS_AVX/vector_dim=256
Benchmark_L2_PureGo_VS_AVX/vector_dim=256
=== RUN   Benchmark_L2_PureGo_VS_AVX/vector_dim=256/pure_go
Benchmark_L2_PureGo_VS_AVX/vector_dim=256/pure_go
Benchmark_L2_PureGo_VS_AVX/vector_dim=256/pure_go-12             9745783               122.4 ns/op             0 B/op          0 allocs/op
=== RUN   Benchmark_L2_PureGo_VS_AVX/vector_dim=256/AVX
Benchmark_L2_PureGo_VS_AVX/vector_dim=256/AVX
Benchmark_L2_PureGo_VS_AVX/vector_dim=256/AVX-12                83226051                14.51 ns/op            0 B/op          0 allocs/op
=== RUN   Benchmark_L2_PureGo_VS_AVX/vector_dim=768
Benchmark_L2_PureGo_VS_AVX/vector_dim=768
=== RUN   Benchmark_L2_PureGo_VS_AVX/vector_dim=768/pure_go
Benchmark_L2_PureGo_VS_AVX/vector_dim=768/pure_go
Benchmark_L2_PureGo_VS_AVX/vector_dim=768/pure_go-12             3360249               359.8 ns/op             0 B/op          0 allocs/op
=== RUN   Benchmark_L2_PureGo_VS_AVX/vector_dim=768/AVX
Benchmark_L2_PureGo_VS_AVX/vector_dim=768/AVX
Benchmark_L2_PureGo_VS_AVX/vector_dim=768/AVX-12                37726705                31.27 ns/op            0 B/op          0 allocs/op
=== RUN   Benchmark_L2_PureGo_VS_AVX/vector_dim=1024
Benchmark_L2_PureGo_VS_AVX/vector_dim=1024
=== RUN   Benchmark_L2_PureGo_VS_AVX/vector_dim=1024/pure_go
Benchmark_L2_PureGo_VS_AVX/vector_dim=1024/pure_go
Benchmark_L2_PureGo_VS_AVX/vector_dim=1024/pure_go-12            2510828               472.8 ns/op             0 B/op          0 allocs/op
=== RUN   Benchmark_L2_PureGo_VS_AVX/vector_dim=1024/AVX
Benchmark_L2_PureGo_VS_AVX/vector_dim=1024/AVX
Benchmark_L2_PureGo_VS_AVX/vector_dim=1024/AVX-12               30531214                38.76 ns/op            0 B/op          0 allocs/op
```

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What would you like to be added?
> calc_distance is no longer used as an external API but still needed internally. We could do some distance computations at Go side like delegator, https://github.com/mmcloughlin/avo is a good tool to generate efficient go assembly, we would like to adopt it.
> 
> ### Why is this needed?
> related to #28410 , we get a 10x improvement on distance calculation by using simd over pure go implementation.
> 
> ```
> b.Run("pure go", func(b *testing.B) {
> for i := 0; i < b.N; i++ {
> 	L2PureGo(x, y)
> }
> })
> 
> b.Run("AVX", func(b *testing.B) {
> for i := 0; i < b.N; i++ {
> 	asm.L2(x, y)
> }
> })
> ```
> 
> result
> 
> ```
> Benchmark_L2_PureGo_VS_AVX/vector_dim=128
> === RUN   Benchmark_L2_PureGo_VS_AVX/vector_dim=128/pure_go
> Benchmark_L2_PureGo_VS_AVX/vector_dim=128/pure_go
> Benchmark_L2_PureGo_VS_AVX/vector_dim=128/pure_go-12            18732463                65.83 ns/op            0 B/op          0 allocs/op
> === RUN   Benchmark_L2_PureGo_VS_AVX/vector_dim=128/AVX
> Benchmark_L2_PureGo_VS_AVX/vector_dim=128/AVX
> Benchmark_L2_PureGo_VS_AVX/vector_dim=128/AVX-12                143581339                8.312 ns/op           0 B/op          0 allocs/op
> === RUN   Benchmark_L2_PureGo_VS_AVX/vector_dim=256
> Benchmark_L2_PureGo_VS_AVX/vector_dim=256
> === RUN   Benchmark_L2_PureGo_VS_AVX/vector_dim=256/pure_go
> Benchmark_L2_PureGo_VS_AVX/vector_dim=256/pure_go
> Benchmark_L2_PureGo_VS_AVX/vector_dim=256/pure_go-12             9745783               122.4 ns/op             0 B/op          0 allocs/op
> === RUN   Benchmark_L2_PureGo_VS_AVX/vector_dim=256/AVX
> Benchmark_L2_PureGo_VS_AVX/vector_dim=256/AVX
> Benchmark_L2_PureGo_VS_AVX/vector_dim=256/AVX-12                83226051                14.51 ns/op            0 B/op          0 allocs/op
> === RUN   Benchmark_L2_PureGo_VS_AVX/vector_dim=768
> Benchmark_L2_PureGo_VS_AVX/vector_dim=768
> === RUN   Benchmark_L2_PureGo_VS_AVX/vector_dim=768/pure_go
> Benchmark_L2_PureGo_VS_AVX/vector_dim=768/pure_go
> Benchmark_L2_PureGo_VS_AVX/vector_dim=768/pure_go-12             3360249               359.8 ns/op             0 B/op          0 allocs/op
> === RUN   Benchmark_L2_PureGo_VS_AVX/vector_dim=768/AVX
> Benchmark_L2_PureGo_VS_AVX/vector_dim=768/AVX
> Benchmark_L2_PureGo_VS_AVX/vector_dim=768/AVX-12                37726705                31.27 ns/op            0 B/op          0 allocs/op
> === RUN   Benchmark_L2_PureGo_VS_AVX/vector_dim=1024
> Benchmark_L2_PureGo_VS_AVX/vector_dim=1024
> === RUN   Benchmark_L2_PureGo_VS_AVX/vector_dim=1024/pure_go
> Benchmark_L2_PureGo_VS_AVX/vector_dim=1024/pure_go
> Benchmark_L2_PureGo_VS_AVX/vector_dim=1024/pure_go-12            2510828               472.8 ns/op             0 B/op          0 allocs/op
> === RUN   Benchmark_L2_PureGo_VS_AVX/vector_dim=1024/AVX
> Benchmark_L2_PureGo_VS_AVX/vector_dim=1024/AVX
> Benchmark_L2_PureGo_VS_AVX/vector_dim=1024/AVX-12               30531214                38.76 ns/op            0 B/op          0 allocs/op
> ```
> 
> ### Anything else?
> _No response_

when did we use distance calculation in go?

**Comment by chasingegg** [comment]
when we compute query with cluster centroids which are held by delegator,  link the issue #28410
