### ISSUE TITLE
[Bug]: Error reported when s3 using aliyun-oss .the error message is' (Aws MultiChunkedEncoding is not supported)

### ISSUE THREAD

**Issue by qiyunsheng** [milvus-io/milvus#28670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.13
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

when insert ，datanode err log：
["flush task error detected"] [error="All attempts results:\nattempt #1:All attempts results:\nattempt #1:Aws MultiChunkedEncoding is not supported.\nattempt #2:Aws MultiChunkedEncoding is not supported.\nattempt #3:Aws MultiChunkedEncoding is not supported.\nattempt #4:Aws MultiChunkedEncoding is not supported.\nattempt #5:Aws MultiChunkedEncoding is not supported.\n\nattempt #2:All attempts results:\nattempt #1:Aws MultiChunkedEncoding is not supported.\nattempt #2:Aws MultiChunkedEncoding is not supported.\nattempt #3:Aws MultiChunkedEncoding is not supported.\nattempt #4:Aws MultiChunkedEncoding is not supported.\nattempt #5:Aws MultiChunkedEncoding is not supported.\n\nattempt #

### Expected Behavior

using

**Comment by qiyunsheng** [comment]
minio:
      address: oss-cn-baoding-gwmclxxxxxxxxxxxxxxxxxxxxxxm.cn
      port: 80
      accessKeyID: Exxxxxxxxxxxxxxxxxx
      secretAccessKey: bxxxxxxxxxxxxxxxxxxxxxxxx
      useSSL: false
      bucketName: onxxxxxxxxxxx
      rootPath: adxxxxxt/test01
      useIAM: false
      cloudProvider: aliyun
      iamEndpoint:
      logLevel: info
      region: ""
      useVirtualHost: false

**Comment by yanliang567** [comment]
please set useVirtualHost=True, or retry on milvus v2.3.3 which set that for aliyun-oss. @qiyunsheng 
/assign

**Comment by qiyunsheng** [comment]
Can be closed......Privatization of Alibaba Cloud OSS does not support S3
