### ISSUE TITLE
can't connect to mysql server on 127.0.0.1

### ISSUE THREAD

**Issue by HotIcewater** [milvus-io/milvus#2868]
Install mysql under centos8 under the virtual machine, the link is determined to be available, but after executing the program, an error is reported and the mysql host cannot be found.

error log 
![22](https://user-images.githubusercontent.com/20943226/87504500-3897f480-c699-11ea-9b29-d71c44c1bb32.png)
conf
![image](https://user-images.githubusercontent.com/20943226/87504535-5bc2a400-c699-11ea-8292-dbae2b154ef1.png)
log
![image](https://user-images.githubusercontent.com/20943226/87504677-bcea7780-c699-11ea-8776-8d262357f51a.png)

please me  thank you

**Comment by yhmo** [comment]
- What is the MySQL version?
- Use real IP to replace the "127.0.0.1"

**Comment by HotIcewater** [comment]
> * 什么是MySQL版本？
> * 使用真实IP替换“ 127.0.0.1” 
>   ，例如：`mysql://root:123456@192.168.101.100:3306/milvus`

mysql 版本为 5.7.18  我换成真实的ip还是同样的错误，连接云上的mysql也是如此

**Comment by HotIcewater** [comment]
> * What is the MySQL version?
> * Use real IP to replace the "127.0.0.1"
>   For example: `mysql://root:123456@192.168.101.100:3306/milvus`

The version of MySQL is 5.7.18. The same error occurs when I change to a real IP address, and the same is true for MySQL connected to the cloud

**Comment by HotIcewater** [comment]
please help me

**Comment by yhmo** [comment]
In command line, try run mysql client to connect MySQL:
`mysql -h127.0.0.1 -uroot -p123456 -Dmilvus`

**Comment by yhmo** [comment]
Some user also report similar problem, try this ways may can solve it:

- close system firewall
- restart machine
- if MySQL server is running from docker, try remove this container, recreate another container

**Comment by HotIcewater** [comment]
> Some users also report similar problem in centos, try these ways may can solve it:
> 
> * close system firewall
> * restart machine
> * if MySQL server is running from docker, try remove this container, recreate another container



> Some users also report similar problem in centos, try these ways may can solve it:
> 
> * close system firewall
> * restart machine
> * if MySQL server is running from docker, try remove this container, recreate another container


非常感谢。问题已解决  错误的原因：需要关闭防火墙，重新启动docker
Thank you very much. Problem resolved. Cause of error: firewall needs to be closed and docker restarted

**Comment by HotIcewater** [comment]
> Some users also report similar problem in centos, try these ways may can solve it:
> 
> * close system firewall
> * restart machine
> * if MySQL server is running from docker, try remove this container, recreate another container

Thank you very much. Problem resolved. Cause of error: firewall needs to be closed and docker restarted
