### ISSUE TITLE
[Bug]: when I try to run  connections.connect, it raised grpc.FutureTimeoutError

### ISSUE THREAD

**Issue by zhaowenZhou** [milvus-io/milvus#28697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.3
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.3
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

minio not showed up througn sudo docker compose ps after sudo docker-compose up -d
and as title, and when I try to run 
connections.connect("default", host="localhost", port="19530")
It raises grpc.FutureTimeoutError

**Comment by zhaowenZhou** [comment]
I do have milvus log but its quite too long to put it here, there are lots of errors and I selected one randomly and put it here
milvus-standalone  | [2023/11/23 10:57:18.260 +00:00] [ERROR] [grpcclient/client.go:429] ["retry func failed"] ["retry time"=4] [error="empty grpc client: find no available datacoord, check datacoord state"] [stack="github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).call\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:429\ngithub.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:513\ngithub.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:529\ngithub.com/milvus-io/milvus/internal/distributed/datacoord/client.wrapGrpcCall[...]\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:102\ngithub.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).GetMetrics\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:397\ngithub.com/milvus-io/milvus/internal/rootcoord.(*QuotaCenter).syncMetrics.func2\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/quota_center.go:216\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75"]

**Comment by zhaowenZhou** [comment]
This one is the latest
milvus-standalone  | [2023/11/23 10:57:50.859 +00:00] [ERROR] [components/query_node.go:54] ["QueryNode starts error"] [error="attempt #0: Get \"http://minio:9000/a-bucket/?location=\": dial tcp: lookup minio on 127.0.0.11:53: server misbehaving: attempt #1: Get \"http://minio:9000/a-bucket/?location=\": dial tcp: lookup minio on 127.0.0.11:53: server misbehaving: attempt #2: Get \"http://minio:9000/a-bucket/?location=\": dial tcp: lookup minio on 127.0.0.11:53: server misbehaving: attempt #3: Get \"http://minio:9000/a-bucket/?location=\": dial tcp: lookup minio on 127.0.0.11:53: server misbehaving: attempt #4: Get \"http://minio:9000/a-bucket/?location=\": dial tcp: lookup minio on 127.0.0.11:53: server misbehaving: attempt #5: Get \"http://minio:9000/a-bucket/?location=\": dial tcp: lookup minio on 127.0.0.11:53: server misbehaving: attempt #6: Get \"http://minio:9000/a-bucket/?location=\": dial tcp: lookup minio on 127.0.0.11:53: server misbehaving: attempt #7: Get \"http://minio:9000/a-bucket/?location=\": dial tcp: lookup minio on 127.0.0.11:53: server misbehaving: attempt #8: Get \"http://minio:9000/a-bucket/?location=\": dial tcp: lookup minio on 127.0.0.11:53: server misbehaving: attempt #9: Get \"http://minio:9000/a-bucket/?location=\": dial tcp: lookup minio on 127.0.0.11:53: server misbehaving: attempt #10: Get \"http://minio:9000/a-bucket/?location=\": dial tcp: lookup minio on 127.0.0.11:53: server misbehaving: attempt #11: Get \"http://minio:9000/a-bucket/?location=\": dial tcp: lookup minio on 127.0.0.11:53: server misbehaving: attempt #12: Get \"http://minio:9000/a-bucket/?location=\": dial tcp: lookup minio on 127.0.0.11:53: server misbehaving: attempt #13: Get \"http://minio:9000/a-bucket/?location=\": dial tcp: lookup minio on 127.0.0.11:53: server misbehaving: attempt #14: Get \"http://minio:9000/a-bucket/?location=\": dial tcp: lookup minio on 127.0.0.11:53: server misbehaving: attempt #15: Get \"http://minio:9000/a-bucket/?location=\": dial tcp: lookup minio on 127.0.0.11:53: server misbehaving: attempt #16: Get \"http://minio:9000/a-bucket/?location=\": dial tcp: lookup minio on 127.0.0.11:53: server misbehaving: attempt #17: Get \"http://minio:9000/a-bucket/?location=\": dial tcp: lookup minio on 127.0.0.11:53: server misbehaving: attempt #18: Get \"http://minio:9000/a-bucket/?location=\": dial tcp: lookup minio on 127.0.0.11:53: server misbehaving: attempt #19: Get \"http://minio:9000/a-bucket/?location=\": dial tcp: lookup minio on 127.0.0.11:53: server misbehaving"] [stack="github.com/milvus-io/milvus/cmd/components.(*QueryNode).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/query_node.go:54\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:113"]

**Comment by yanliang567** [comment]
it seems that your minio service is not working, please help to double check. Also you could use docker-compose logs > milvus.log to export the logs.

**Comment by zhaowenZhou** [comment]
> it seems that your minio service is not working, please help to double check. Also you could use docker-compose logs > milvus.log to export the logs.

How to make it work? I followed the instruction provided by tutorial: sudo docker-compose up -d

**Comment by zhaowenZhou** [comment]
I saved all logs to a txt file
[log.txt](https://github.com/milvus-io/milvus/files/13449265/log.txt)

**Comment by zhaowenZhou** [comment]
@yanliang567

**Comment by yanliang567** [comment]
have you deployed milvus before, did you clean up the milvus volumes? it seem that the current milvus is trying to connect etcd with some exiting meta. 
```
milvus-standalone  | [2023/11/23 10:54:58.000 +00:00] [WARN] [server/rocksmq_impl.go:398] ["rocksmq topic already exists "] [topic=by-dev-rootcoord-dml_14]
milvus-standalone  | [2023/11/23 10:54:58.000 +00:00] [INFO] [msgstream/common_mq_factory.go:31] ["Msg Stream state"] [can_produce=true]
milvus-standalone  | [2023/11/23 10:54:58.000 +00:00] [WARN] [server/rocksmq_impl.go:398] ["rocksmq topic already exists "] [topic=by-dev-rootcoord-dml_15]
milvus-standalone  | [2023/11/23 10:54:58.000 +00:00] [INFO] [rootcoord/dml_channels.go:215] ["init dml channels"] [prefix=by-dev-rootcoord-dml] [num=16]
milvus-standalone  | [2023/11/23 10:54:58.000 +00:00] [INFO] [rootcoord/timeticksync.go:126] ["recover physical channels"] [collectionID=444979618623520769] ["physical channels"="[by-dev-rootcoord-dml_0,by-dev-rootcoord-dml_1]"]
milvus-standalone  | [2023/11/23 10:54:58.000 +00:00] [INFO] [rootcoord/timeticksync.go:126] ["recover physical channels"] [collectionID=445536272938372417] ["physical channels"="[by-dev-rootcoord-dml_0,by-dev-rootcoord-dml_1]"]
milvus-standalone  | [2023/11/23 10:54:58.000 +00:00] [INFO] [rootcoord/timeticksync.go:126] ["recover physical channels"] [collectionID=443058036732329985] ["physical channels"="[by-dev-rootcoord-dml_10,by-dev-rootcoord-dml_11]"]
milvus-standalone  | [2023/11/23 10:54:58.000 +00:00] [INFO] [rootcoord/timeticksync.go:126] ["recover physical channels"] [collectionID=444429165594673153] ["physical channels"="[by-dev-rootcoord-dml_0,by-dev-rootcoord-dml_1]"]
```

**Comment by zhaowenZhou** [comment]
> have you deployed milvus before, did you clean up the milvus volumes? it seem that the current milvus is trying to connect etcd with some exiting meta.
> 
> ```
> milvus-standalone  | [2023/11/23 10:54:58.000 +00:00] [WARN] [server/rocksmq_impl.go:398] ["rocksmq topic already exists "] [topic=by-dev-rootcoord-dml_14]
> milvus-standalone  | [2023/11/23 10:54:58.000 +00:00] [INFO] [msgstream/common_mq_factory.go:31] ["Msg Stream state"] [can_produce=true]
> milvus-standalone  | [2023/11/23 10:54:58.000 +00:00] [WARN] [server/rocksmq_impl.go:398] ["rocksmq topic already exists "] [topic=by-dev-rootcoord-dml_15]
> milvus-standalone  | [2023/11/23 10:54:58.000 +00:00] [INFO] [rootcoord/dml_channels.go:215] ["init dml channels"] [prefix=by-dev-rootcoord-dml] [num=16]
> milvus-standalone  | [2023/11/23 10:54:58.000 +00:00] [INFO] [rootcoord/timeticksync.go:126] ["recover physical channels"] [collectionID=444979618623520769] ["physical channels"="[by-dev-rootcoord-dml_0,by-dev-rootcoord-dml_1]"]
> milvus-standalone  | [2023/11/23 10:54:58.000 +00:00] [INFO] [rootcoord/timeticksync.go:126] ["recover physical channels"] [collectionID=445536272938372417] ["physical channels"="[by-dev-rootcoord-dml_0,by-dev-rootcoord-dml_1]"]
> milvus-standalone  | [2023/11/23 10:54:58.000 +00:00] [INFO] [rootcoord/timeticksync.go:126] ["recover physical channels"] [collectionID=443058036732329985] ["physical channels"="[by-dev-rootcoord-dml_10,by-dev-rootcoord-dml_11]"]
> milvus-standalone  | [2023/11/23 10:54:58.000 +00:00] [INFO] [rootcoord/timeticksync.go:126] ["recover physical channels"] [collectionID=444429165594673153] ["physical channels"="[by-dev-rootcoord-dml_0,by-dev-rootcoord-dml_1]"]
> ```

You are right, i deployed it before, could you show me how to clean up volume? And after I did it, what's the next step? Thank you

**Comment by yanliang567** [comment]
jsut delete the folder /volume/, which locates the same folder with docker-compose.yaml. 
or create s new folder and copy the yaml into it.

**Comment by zhaowenZhou** [comment]
> jsut delete the folder /volume/, which locates the same folder with docker-compose.yaml. or create s new folder and copy the yaml into it.

A big thank you for your great help. BTW could you tell me the logic behind it? Why I lost connections to the db yesterday and what happened after I deleted volumes folder

**Comment by yanliang567** [comment]
the milvus was not running healthy yesterday, so you are not able to connect to it.

**Comment by zhaowenZhou** [comment]
Sorry for asking again
What does deleting the /volume folder mean? Does this mean remove existed
data? If yes this is quite dangerous.
Is there anyway that I can keep previous data and reconnect to milvus?

yanliang567 ***@***.***> 于2023年11月24日周五 15:29写道：

**Comment by zhaowenZhou** [comment]
> the milvus was not running healthy yesterday, so you are not able to connect to it.

Sorry for asking again
What does deleting the /volume folder mean? Does this mean remove existed data? If yes this is quite dangerous.
Is there anyway that I can keep previous data and reconnect to milvus?

**Comment by yanliang567** [comment]
then you can create a new folder and run docker compose in the new created folder.
