### ISSUE TITLE
[Bug]: Compaction can not succeed with "all segments' binlogs are empty"

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#28742]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

please check https://github.com/milvus-io/milvus/discussions/28724.

My guess is that delete or ttl generate a empty segment.
1) empty segment should not be generated on 2.3.3 because handoff no matter depends on it.
2) why can we handle empty compaction?

**Comment by yanliang567** [comment]
@chyezh any updates?

**Comment by yanliang567** [comment]
@chyezh I think this was fixed, please help to confirm.
