### ISSUE TITLE
[Bug]: Log can not reduce level

### ISSUE THREAD

**Issue by aoiasd** [milvus-io/milvus#28749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master, 2.3, 2.2
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When we reduce log level by http interface, it not works.

**Comment by yanliang567** [comment]
/assign @ThreadDao 
please help to verify the fix accordingly.
/assign @aoiasd 
/unassign
