### ISSUE TITLE
I wish I could build the data index offline and then import to Milvus

### ISSUE THREAD

**Issue by dhg012** [milvus-io/milvus#2875]
**Please state you issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**
Creating index is expensive operating.  I wish I could build the data index offline and then import to Milvus.  During the test, we found that the CPU load was particularly high when creating the index. This may affect the online query service. 

**Describe the solution you'd like**
 User build the data index and then import to Milvus instance with some ways.

**Comment by JinHai-CN** [comment]
We are designing the distributed solution to assign the index building task to specific node.
