### ISSUE TITLE
[Enhancement]: Remove the support for CSV in bulk insert.

### ISSUE THREAD

**Issue by czs007** [milvus-io/milvus#28778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

I propose the elimination of the CSV support in bulk insert.

### Why is this needed?

The support for complex data types like arrays in CSV format is rather intricate. I recommend utilizing both Parquet and JSON formats in the future to accommodate these complex data types. In order to minimize maintenance costs, it is advisable to eliminate the CSV support in bulk insert.

**Comment by xiaocai2333** [comment]
done!
/close
