### ISSUE TITLE
[Bug]: Milvus instance on Kubernetes stopped working all of a sudden

### ISSUE THREAD

**Issue by realech** [milvus-io/milvus#28775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.3.1
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.3.1
- Machine Type: [n2-highmem-16](https://gcloud-compute.com/n2-highmem-16.html)
- GPU: None
- Others: Using GCS as storage
```

### Current Behavior

Collection loading gets stuck at about ~50%, instance was working properly until Saturday midday when it suddenly stopped working

### Expected Behavior

Collection should be able to load properly: increasing the replicas to 4 index nodes and 5 query nodes does not help

### Milvus Log

[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/13477437/milvus-log.tar.gz)

### Anything else?

Seeing a bunch of errors like this in data node (for insert logs and delta logs):
`[2023/11/27 08:28:03.027 +00:00] [WARN] [datanode/binlog_io.go:87] ["downloading failed, retry in 50ms"] `

Also, this error in index coord:
`["Query failed to WaitToFinish"] [traceID=9882b2e2b8bb8d963de66825022592a4] [role=proxy] [db=production] [collection=embeddings] [partitions="[]"] [error="failed to query: attempt #0: fail to get shard leaders from QueryCoord: segment=445066603348655343: segment lacks: channel=by-dev-rootcoord-dml_1_445066603348649979v0: channel not available: attempt #1: fail to get shard leaders from QueryCoord:`

And these ones in query node:
`[2023/11/27 08:33:03.304 +00:00] [INFO] [segments/segment_loader.go:186] ["start loading..."] [traceID=a48f53b4df026ff808460b1c3e0bb749] [collectionID=445066603348649979] [segmentType=Sealed] [segmentNum=1] [afterFilter=1]
[2023/11/27 08:33:03.304 +00:00] [WARN] [delegator/delegator_data.go:392] ["worker failed to load segments"] [traceID=a48f53b4df026ff808460b1c3e0bb749] [collectionID=445066603348649979] [channel=by-dev-rootcoord-dml_1_445066603348649979v0] [replicaID=445066637805879297] [workID=10] [segments="[445066603348699021]"] [error="limit=160: request limit exceeded"]`

Finally, I see that pulsar-recovery is getting OOM errors:

`16:11:57.999 [bookkeeper-io-3-25] ERROR org.apache.bookkeeper.common.allocator.impl.ByteBufAllocatorImpl - Unable to allocate memory
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 67108864, max: 67108864)`

Is there any way we can load the collections even if there is slight data loss? Our production instance has been down for a lot now

**Comment by yanliang567** [comment]
fail to read file in querycoord logs, @jiaoew1991 could you please take a look?
`[2023/11/27 15:57:43.156 +00:00] [WARN] [task/executor.go:191] ["failed to load segment"] [taskIDs="[1701095635815]"] [collectionID=445066603348649979] [replicaID=445931979298832397] [shard=by-dev-rootcoord-dml_1_445066603348649979v0] [segmentIDs="[445066603348854578]"] [nodeID=43] [source=1] [error="legacy error code:1, reason: failed to read file/stats_log/445066603348649979/445066603348649980/445066603348854578/100/1: NoSuchKey(key=file/stats_log/445066603348649979/445066603348649980/445066603348854578/100/1)"]
`

/assign @jiaoew1991 
/unassign

**Comment by xiaofan-luan** [comment]
From the log,

the cluster can not start because of

file/stats_log/445066603348649979/445066603348649980/445066603348660939/100/445066603348661012
is missing.

From the current log there is not enough log about why 445066603348661012 is missing.

Did you do anything special such as create a new cluster, delete file directly on S3 or etcd? From the current there is no reason why 445066603348661012 this file is deleted.

To recover the cluster:
1. use birdwatcher check whether the segment stats, and see how many binlogs are there in the segment
2. if there is no binlogs or you can remove the datas, simply remove the segment and it should recover.
3. Otherwise we need to backup the data, remove the data and reingest the data from binlog

**Comment by xiaofan-luan** [comment]
if you have previous logs, search datacoord logs on 445066603348661012 and check if we can find the reason of why this log is missing

**Comment by realech** [comment]
I used birdwatcher to delete that segment but the collections are still not loading, is it possible that there are more missing segments?

```
Milvus(by-dev) > show segment
SegmentID: 445066603348649999 State: Flushed, Row Count:8422
SegmentID: 445066603348653805 State: Flushed, Row Count:38862
SegmentID: 445066603348653887 State: Flushed, Row Count:29697
SegmentID: 445066603348653953 State: Flushed, Row Count:30606
SegmentID: 445066603348654019 State: Flushed, Row Count:32403
SegmentID: 445066603348654093 State: Flushed, Row Count:30698
SegmentID: 445066603348654159 State: Flushed, Row Count:36828
SegmentID: 445066603348654241 State: Flushed, Row Count:28868
SegmentID: 445066603348654307 State: Flushed, Row Count:29419
SegmentID: 445066603348655343 State: Flushed, Row Count:29743
SegmentID: 445066603348655466 State: Flushed, Row Count:34341
SegmentID: 445066603348655599 State: Flushed, Row Count:34052
SegmentID: 445066603348655759 State: Flushed, Row Count:32856
SegmentID: 445066603348655888 State: Flushed, Row Count:33911
SegmentID: 445066603348656145 State: Flushed, Row Count:30845
SegmentID: 445066603348656238 State: Flushed, Row Count:29547
SegmentID: 445066603348656333 State: Flushed, Row Count:29108
SegmentID: 445066603348657195 State: Flushed, Row Count:30305
SegmentID: 445066603348657648 State: Flushed, Row Count:28661
SegmentID: 445066603348657864 State: Flushed, Row Count:34423
SegmentID: 445066603348658072 State: Flushed, Row Count:34396
SegmentID: 445066603348658198 State: Flushed, Row Count:30662
SegmentID: 445066603348658329 State: Flushed, Row Count:28202
SegmentID: 445066603348658568 State: Flushed, Row Count:28567
SegmentID: 445066603348658699 State: Flushed, Row Count:29356
SegmentID: 445066603348658903 State: Flushed, Row Count:29470
SegmentID: 445066603348659114 State: Flushed, Row Count:34691
SegmentID: 445066603348659207 State: Flushed, Row Count:29090
SegmentID: 445066603348659418 State: Flushed, Row Count:28525
SegmentID: 445066603348659850 State: Flushed, Row Count:28406
SegmentID: 445066603348660073 State: Flushed, Row Count:33048
SegmentID: 445066603348660393 State: Flushed, Row Count:35055
SegmentID: 445066603348660663 State: Flushed, Row Count:35377
SegmentID: 445066603348660802 State: Flushed, Row Count:35887
SegmentID: 445066603348660939 State: Flushed, Row Count:35407
SegmentID: 445066603348661068 State: Flushed, Row Count:34348
SegmentID: 445066603348661202 State: Flushed, Row Count:29765
SegmentID: 445066603348661374 State: Flushed, Row Count:29762
SegmentID: 445066603348663503 State: Flushed, Row Count:7262
SegmentID: 445066603348664919 State: Flushed, Row Count:6616
SegmentID: 445066603348666731 State: Flushed, Row Count:3509
SegmentID: 445066603348667286 State: Flushed, Row Count:757
SegmentID: 445066603348677004 State: Flushed, Row Count:35003
SegmentID: 445066603348679899 State: Flushed, Row Count:949
SegmentID: 445066603348681011 State: Flushed, Row Count:651
SegmentID: 445066603348686241 State: Flushed, Row Count:34348
SegmentID: 445066603348686385 State: Flushed, Row Count:33059
SegmentID: 445066603348687322 State: Flushed, Row Count:8608
SegmentID: 445066603348690108 State: Flushed, Row Count:33062
SegmentID: 445066603348690656 State: Flushed, Row Count:1626
SegmentID: 445066603348690728 State: Flushed, Row Count:30138
SegmentID: 445066603348691405 State: Flushed, Row Count:2598
SegmentID: 445066603348693211 State: Flushed, Row Count:30849
SegmentID: 445066603348693527 State: Flushed, Row Count:1936
SegmentID: 445066603348693575 State: Flushed, Row Count:13552
SegmentID: 445066603348693713 State: Flushed, Row Count:9827
SegmentID: 445066603348694427 State: Flushed, Row Count:910
SegmentID: 445066603348694631 State: Flushed, Row Count:2880
SegmentID: 445066603348694788 State: Flushed, Row Count:6025
SegmentID: 445066603348694929 State: Flushed, Row Count:725
SegmentID: 445066603348695045 State: Flushed, Row Count:9519
SegmentID: 445066603348695759 State: Flushed, Row Count:984
SegmentID: 445066603348695849 State: Flushed, Row Count:2977
SegmentID: 445066603348697071 State: Flushed, Row Count:29912
SegmentID: 445066603348697660 State: Flushed, Row Count:2623
SegmentID: 445066603348698402 State: Flushed, Row Count:1578
SegmentID: 445066603348698550 State: Flushed, Row Count:31481
SegmentID: 445066603348699021 State: Flushed, Row Count:1273
SegmentID: 445066603348699112 State: Flushed, Row Count:30804
SegmentID: 445066603348699516 State: Flushed, Row Count:57
SegmentID: 445066603348850024 State: Flushed, Row Count:28056
SegmentID: 445066603348850226 State: Flushed, Row Count:28410
SegmentID: 445066603348850427 State: Flushed, Row Count:28056
SegmentID: 445066603348850541 State: Flushed, Row Count:28357
SegmentID: 445066603348850841 State: Flushed, Row Count:28056
SegmentID: 445066603348851256 State: Flushed, Row Count:28056
SegmentID: 445066603348851642 State: Flushed, Row Count:28056
SegmentID: 445066603348851752 State: Flushed, Row Count:28595
SegmentID: 445066603348852083 State: Flushed, Row Count:28056
SegmentID: 445066603348852187 State: Flushed, Row Count:28298
SegmentID: 445066603348852497 State: Flushed, Row Count:28056
SegmentID: 445066603348852605 State: Flushed, Row Count:28322
SegmentID: 445066603348852913 State: Flushed, Row Count:28056
SegmentID: 445066603348853023 State: Flushed, Row Count:28318
SegmentID: 445066603348853452 State: Flushed, Row Count:28056
SegmentID: 445066603348853567 State: Flushed, Row Count:28323
SegmentID: 445066603348853916 State: Flushed, Row Count:28056
SegmentID: 445066603348854130 State: Flushed, Row Count:28995
SegmentID: 445066603348854356 State: Flushed, Row Count:28056
SegmentID: 445066603348854578 State: Flushed, Row Count:28463
SegmentID: 445066603348854795 State: Flushed, Row Count:28056
SegmentID: 445066603348854900 State: Flushed, Row Count:28281
SegmentID: 445066603348855234 State: Flushed, Row Count:28056
SegmentID: 445066603348855647 State: Flushed, Row Count:28056
SegmentID: 445066603348856061 State: Flushed, Row Count:28056
SegmentID: 445066603348856476 State: Flushed, Row Count:28056
SegmentID: 445066603348856968 State: Flushed, Row Count:28811
SegmentID: 445066603348857387 State: Flushed, Row Count:28319
SegmentID: 445066603351059163 State: Flushed, Row Count:1454
SegmentID: 445066603351173319 State: Flushed, Row Count:6777
SegmentID: 445066603351186970 State: Flushed, Row Count:968
SegmentID: 445066603351358715 State: Flushed, Row Count:1028
SegmentID: 445066603351517361 State: Flushed, Row Count:5789
SegmentID: 445066603351603255 State: Flushed, Row Count:2284
SegmentID: 445066603351704843 State: Flushed, Row Count:1160
SegmentID: 445066603351840724 State: Flushed, Row Count:3102
SegmentID: 445066603351935546 State: Flushed, Row Count:6152
SegmentID: 445066603353296800 State: Flushed, Row Count:1389
SegmentID: 445066603363811994 State: Flushed, Row Count:1017
SegmentID: 445066603374993790 State: Flushed, Row Count:1495
SegmentID: 445066603375326289 State: Flushed, Row Count:3004
SegmentID: 445066603375875865 State: Flushed, Row Count:3931
SegmentID: 445066603376452187 State: Flushed, Row Count:1517
SegmentID: 445066603377848079 State: Flushed, Row Count:1120
SegmentID: 445066603383820146 State: Flushed, Row Count:6092
SegmentID: 445066603390637524 State: Flushed, Row Count:1040
SegmentID: 445066603401045730 State: Flushed, Row Count:5806
SegmentID: 445066603404824471 State: Flushed, Row Count:3861
SegmentID: 445066603406607338 State: Flushed, Row Count:2863
SegmentID: 445066603407720573 State: Flushed, Row Count:1163
SegmentID: 445066603410627264 State: Flushed, Row Count:1415
SegmentID: 445066603412318861 State: Flushed, Row Count:8071
SegmentID: 445066603414303454 State: Flushed, Row Count:7517
SegmentID: 445066603415672659 State: Flushed, Row Count:8517
SegmentID: 445066603424018930 State: Flushed, Row Count:1101
SegmentID: 445066603425809502 State: Flushed, Row Count:2148
SegmentID: 445066603437409057 State: Flushed, Row Count:1073
SegmentID: 445066603441750883 State: Flushed, Row Count:1596
SegmentID: 445066603444495483 State: Flushed, Row Count:3154
SegmentID: 445066603444817393 State: Flushed, Row Count:1847
SegmentID: 445066603444964995 State: Flushed, Row Count:1246
--- Growing: 0, Sealed: 0, Flushed: 131, Dropped: 0
--- Total Segments: 131, row count: 2450792
```

```
segment info ID:445066603348660939 collectionID:445066603348649979 partitionID:445066603348649980 insert_channel:"by-dev-rootcoord-dml_1_445066603348649979v0" num_of_rows:35407 state:Flushed max_row_num:32063 last_expire_time:445150396286763013 start_position:<channel_name:"by-dev-rootcoord-dml_1_445066603348649979v0" msgID:"\010\001\020\256'\030\000 \000" timestamp:445068265562046467 > dml_position:<channel_name:"by-dev-rootcoord-dml_1_445066603348649979v0" msgID:"\010\251\014\020\316\314\001\030\000 \000" msgGroup:"datanode-5-by-dev-rootcoord-dml_1_445066603348649979v0-true" timestamp:445884053220491265 > createdByCompaction:t
```

```
Milvus(by-dev) > remove segment --segment 445066603348660939 --run
[WARNING] about to remove segment from etcd
audit delete by-dev/meta/datacoord-meta/s/445066603348649979/445066603348649980/445066603348660939
audit delete by-dev/meta/datacoord-meta/binlog/445066603348649979/445066603348649980/445066603348660939
failed to delete binlogs from etcd for segment 445066603348660939, err: Error getting prev kv in removeWithPrevKV for key: by-dev/meta/datacoord-meta/binlog/445066603348649979/445066603348649980/445066603348660939
audit delete by-dev/meta/datacoord-meta/deltalog/445066603348649979/445066603348649980/445066603348660939
failed to delete deltalogs from etcd for segment 445066603348660939, err: Error getting prev kv in removeWithPrevKV for key: by-dev/meta/datacoord-meta/deltalog/445066603348649979/445066603348649980/445066603348660939
audit delete by-dev/meta/datacoord-meta/statslog/445066603348649979/445066603348649980/445066603348660939
failed to delete statslogs from etcd for segment 445066603348660939, err: Error getting prev kv in removeWithPrevKV for key: by-dev/meta/datacoord-meta/statslog/445066603348649979/445066603348649980/445066603348660939
Remove segment 445066603348660939 from Etcd failed, err: Error getting prev kv in removeWithPrevKV for key: by-dev/meta/datacoord-meta/statslog/445066603348649979/445066603348649980/445066603348660939
 ```

**Comment by xiaofan-luan** [comment]
there might be still some memory cache in datacoord that's why you need to reboot

**Comment by xiaofan-luan** [comment]
And from the log, there are many other logs are misising.

2023-11-26T01:09:14+01:00	[2023/11/26 00:09:14.381 +00:00] [WARN] [delegator/delegator_data.go:353] ["failed to load bloom filter set for segment"] [traceID=196adb443d60951ebdcadd563fed9532] [collectionID=445066603348649979] [channel=by-dev-rootcoord-dml_1_445066603348649979v0] [replicaID=445066637805879297] [workID=10] [segments="[445066603348854578]"] [error="failed to read file/stats_log/445066603348649979/445066603348649980/445066603348854578/100/1: NoSuchKey(key=file/stats_log/445066603348649979/445066603348649980/445066603348854578/100/1)"]

for example "445066603348854578"

use birdwatcher verify segment command and check what segment actually missing a file?

**Comment by xiaofan-luan** [comment]
almost all the segments missed stats log.
Did you got a chance to check that all your files is still there on S3?
like what is under "file/stats_log/445066603348649979/445066603348649980/445066603348854578"

**Comment by realech** [comment]
> > I used birdwatcher to delete that segment but the collections are still not loading, is it possible that there are more missing segments?
> > ```
> > Milvus(by-dev) > show segment
> > SegmentID: 445066603348649999 State: Flushed, Row Count:8422
> > SegmentID: 445066603348653805 State: Flushed, Row Count:38862
> > SegmentID: 445066603348653887 State: Flushed, Row Count:29697
> > SegmentID: 445066603348653953 State: Flushed, Row Count:30606
> > SegmentID: 445066603348654019 State: Flushed, Row Count:32403
> > SegmentID: 445066603348654093 State: Flushed, Row Count:30698
> > SegmentID: 445066603348654159 State: Flushed, Row Count:36828
> > SegmentID: 445066603348654241 State: Flushed, Row Count:28868
> > SegmentID: 445066603348654307 State: Flushed, Row Count:29419
> > SegmentID: 445066603348655343 State: Flushed, Row Count:29743
> > SegmentID: 445066603348655466 State: Flushed, Row Count:34341
> > SegmentID: 445066603348655599 State: Flushed, Row Count:34052
> > SegmentID: 445066603348655759 State: Flushed, Row Count:32856
> > SegmentID: 445066603348655888 State: Flushed, Row Count:33911
> > SegmentID: 445066603348656145 State: Flushed, Row Count:30845
> > SegmentID: 445066603348656238 State: Flushed, Row Count:29547
> > SegmentID: 445066603348656333 State: Flushed, Row Count:29108
> > SegmentID: 445066603348657195 State: Flushed, Row Count:30305
> > SegmentID: 445066603348657648 State: Flushed, Row Count:28661
> > SegmentID: 445066603348657864 State: Flushed, Row Count:34423
> > SegmentID: 445066603348658072 State: Flushed, Row Count:34396
> > SegmentID: 445066603348658198 State: Flushed, Row Count:30662
> > SegmentID: 445066603348658329 State: Flushed, Row Count:28202
> > SegmentID: 445066603348658568 State: Flushed, Row Count:28567
> > SegmentID: 445066603348658699 State: Flushed, Row Count:29356
> > SegmentID: 445066603348658903 State: Flushed, Row Count:29470
> > SegmentID: 445066603348659114 State: Flushed, Row Count:34691
> > SegmentID: 445066603348659207 State: Flushed, Row Count:29090
> > SegmentID: 445066603348659418 State: Flushed, Row Count:28525
> > SegmentID: 445066603348659850 State: Flushed, Row Count:28406
> > SegmentID: 445066603348660073 State: Flushed, Row Count:33048
> > SegmentID: 445066603348660393 State: Flushed, Row Count:35055
> > SegmentID: 445066603348660663 State: Flushed, Row Count:35377
> > SegmentID: 445066603348660802 State: Flushed, Row Count:35887
> > SegmentID: 445066603348660939 State: Flushed, Row Count:35407
> > SegmentID: 445066603348661068 State: Flushed, Row Count:34348
> > SegmentID: 445066603348661202 State: Flushed, Row Count:29765
> > SegmentID: 445066603348661374 State: Flushed, Row Count:29762
> > SegmentID: 445066603348663503 State: Flushed, Row Count:7262
> > SegmentID: 445066603348664919 State: Flushed, Row Count:6616
> > SegmentID: 445066603348666731 State: Flushed, Row Count:3509
> > SegmentID: 445066603348667286 State: Flushed, Row Count:757
> > SegmentID: 445066603348677004 State: Flushed, Row Count:35003
> > SegmentID: 445066603348679899 State: Flushed, Row Count:949
> > SegmentID: 445066603348681011 State: Flushed, Row Count:651
> > SegmentID: 445066603348686241 State: Flushed, Row Count:34348
> > SegmentID: 445066603348686385 State: Flushed, Row Count:33059
> > SegmentID: 445066603348687322 State: Flushed, Row Count:8608
> > SegmentID: 445066603348690108 State: Flushed, Row Count:33062
> > SegmentID: 445066603348690656 State: Flushed, Row Count:1626
> > SegmentID: 445066603348690728 State: Flushed, Row Count:30138
> > SegmentID: 445066603348691405 State: Flushed, Row Count:2598
> > SegmentID: 445066603348693211 State: Flushed, Row Count:30849
> > SegmentID: 445066603348693527 State: Flushed, Row Count:1936
> > SegmentID: 445066603348693575 State: Flushed, Row Count:13552
> > SegmentID: 445066603348693713 State: Flushed, Row Count:9827
> > SegmentID: 445066603348694427 State: Flushed, Row Count:910
> > SegmentID: 445066603348694631 State: Flushed, Row Count:2880
> > SegmentID: 445066603348694788 State: Flushed, Row Count:6025
> > SegmentID: 445066603348694929 State: Flushed, Row Count:725
> > SegmentID: 445066603348695045 State: Flushed, Row Count:9519
> > SegmentID: 445066603348695759 State: Flushed, Row Count:984
> > SegmentID: 445066603348695849 State: Flushed, Row Count:2977
> > SegmentID: 445066603348697071 State: Flushed, Row Count:29912
> > SegmentID: 445066603348697660 State: Flushed, Row Count:2623
> > SegmentID: 445066603348698402 State: Flushed, Row Count:1578
> > SegmentID: 445066603348698550 State: Flushed, Row Count:31481
> > SegmentID: 445066603348699021 State: Flushed, Row Count:1273
> > SegmentID: 445066603348699112 State: Flushed, Row Count:30804
> > SegmentID: 445066603348699516 State: Flushed, Row Count:57
> > SegmentID: 445066603348850024 State: Flushed, Row Count:28056
> > SegmentID: 445066603348850226 State: Flushed, Row Count:28410
> > SegmentID: 445066603348850427 State: Flushed, Row Count:28056
> > SegmentID: 445066603348850541 State: Flushed, Row Count:28357
> > SegmentID: 445066603348850841 State: Flushed, Row Count:28056
> > SegmentID: 445066603348851256 State: Flushed, Row Count:28056
> > SegmentID: 445066603348851642 State: Flushed, Row Count:28056
> > SegmentID: 445066603348851752 State: Flushed, Row Count:28595
> > SegmentID: 445066603348852083 State: Flushed, Row Count:28056
> > SegmentID: 445066603348852187 State: Flushed, Row Count:28298
> > SegmentID: 445066603348852497 State: Flushed, Row Count:28056
> > SegmentID: 445066603348852605 State: Flushed, Row Count:28322
> > SegmentID: 445066603348852913 State: Flushed, Row Count:28056
> > SegmentID: 445066603348853023 State: Flushed, Row Count:28318
> > SegmentID: 445066603348853452 State: Flushed, Row Count:28056
> > SegmentID: 445066603348853567 State: Flushed, Row Count:28323
> > SegmentID: 445066603348853916 State: Flushed, Row Count:28056
> > SegmentID: 445066603348854130 State: Flushed, Row Count:28995
> > SegmentID: 445066603348854356 State: Flushed, Row Count:28056
> > SegmentID: 445066603348854578 State: Flushed, Row Count:28463
> > SegmentID: 445066603348854795 State: Flushed, Row Count:28056
> > SegmentID: 445066603348854900 State: Flushed, Row Count:28281
> > SegmentID: 445066603348855234 State: Flushed, Row Count:28056
> > SegmentID: 445066603348855647 State: Flushed, Row Count:28056
> > SegmentID: 445066603348856061 State: Flushed, Row Count:28056
> > SegmentID: 445066603348856476 State: Flushed, Row Count:28056
> > SegmentID: 445066603348856968 State: Flushed, Row Count:28811
> > SegmentID: 445066603348857387 State: Flushed, Row Count:28319
> > SegmentID: 445066603351059163 State: Flushed, Row Count:1454
> > SegmentID: 445066603351173319 State: Flushed, Row Count:6777
> > SegmentID: 445066603351186970 State: Flushed, Row Count:968
> > SegmentID: 445066603351358715 State: Flushed, Row Count:1028
> > SegmentID: 445066603351517361 State: Flushed, Row Count:5789
> > SegmentID: 445066603351603255 State: Flushed, Row Count:2284
> > SegmentID: 445066603351704843 State: Flushed, Row Count:1160
> > SegmentID: 445066603351840724 State: Flushed, Row Count:3102
> > SegmentID: 445066603351935546 State: Flushed, Row Count:6152
> > SegmentID: 445066603353296800 State: Flushed, Row Count:1389
> > SegmentID: 445066603363811994 State: Flushed, Row Count:1017
> > SegmentID: 445066603374993790 State: Flushed, Row Count:1495
> > SegmentID: 445066603375326289 State: Flushed, Row Count:3004
> > SegmentID: 445066603375875865 State: Flushed, Row Count:3931
> > SegmentID: 445066603376452187 State: Flushed, Row Count:1517
> > SegmentID: 445066603377848079 State: Flushed, Row Count:1120
> > SegmentID: 445066603383820146 State: Flushed, Row Count:6092
> > SegmentID: 445066603390637524 State: Flushed, Row Count:1040
> > SegmentID: 445066603401045730 State: Flushed, Row Count:5806
> > SegmentID: 445066603404824471 State: Flushed, Row Count:3861
> > SegmentID: 445066603406607338 State: Flushed, Row Count:2863
> > SegmentID: 445066603407720573 State: Flushed, Row Count:1163
> > SegmentID: 445066603410627264 State: Flushed, Row Count:1415
> > SegmentID: 445066603412318861 State: Flushed, Row Count:8071
> > SegmentID: 445066603414303454 State: Flushed, Row Count:7517
> > SegmentID: 445066603415672659 State: Flushed, Row Count:8517
> > SegmentID: 445066603424018930 State: Flushed, Row Count:1101
> > SegmentID: 445066603425809502 State: Flushed, Row Count:2148
> > SegmentID: 445066603437409057 State: Flushed, Row Count:1073
> > SegmentID: 445066603441750883 State: Flushed, Row Count:1596
> > SegmentID: 445066603444495483 State: Flushed, Row Count:3154
> > SegmentID: 445066603444817393 State: Flushed, Row Count:1847
> > SegmentID: 445066603444964995 State: Flushed, Row Count:1246
> > --- Growing: 0, Sealed: 0, Flushed: 131, Dropped: 0
> > --- Total Segments: 131, row count: 2450792
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > segment info ID:445066603348660939 collectionID:445066603348649979 partitionID:445066603348649980 insert_channel:"by-dev-rootcoord-dml_1_445066603348649979v0" num_of_rows:35407 state:Flushed max_row_num:32063 last_expire_time:445150396286763013 start_position:<channel_name:"by-dev-rootcoord-dml_1_445066603348649979v0" msgID:"\010\001\020\256'\030\000 \000" timestamp:445068265562046467 > dml_position:<channel_name:"by-dev-rootcoord-dml_1_445066603348649979v0" msgID:"\010\251\014\020\316\314\001\030\000 \000" msgGroup:"datanode-5-by-dev-rootcoord-dml_1_445066603348649979v0-true" timestamp:445884053220491265 > createdByCompaction:t
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > Milvus(by-dev) > remove segment --segment 445066603348660939 --run
> > [WARNING] about to remove segment from etcd
> > audit delete by-dev/meta/datacoord-meta/s/445066603348649979/445066603348649980/445066603348660939
> > audit delete by-dev/meta/datacoord-meta/binlog/445066603348649979/445066603348649980/445066603348660939
> > failed to delete binlogs from etcd for segment 445066603348660939, err: Error getting prev kv in removeWithPrevKV for key: by-dev/meta/datacoord-meta/binlog/445066603348649979/445066603348649980/445066603348660939
> > audit delete by-dev/meta/datacoord-meta/deltalog/445066603348649979/445066603348649980/445066603348660939
> > failed to delete deltalogs from etcd for segment 445066603348660939, err: Error getting prev kv in removeWithPrevKV for key: by-dev/meta/datacoord-meta/deltalog/445066603348649979/445066603348649980/445066603348660939
> > audit delete by-dev/meta/datacoord-meta/statslog/445066603348649979/445066603348649980/445066603348660939
> > failed to delete statslogs from etcd for segment 445066603348660939, err: Error getting prev kv in removeWithPrevKV for key: by-dev/meta/datacoord-meta/statslog/445066603348649979/445066603348649980/445066603348660939
> > Remove segment 445066603348660939 from Etcd failed, err: Error getting prev kv in removeWithPrevKV for key: by-dev/meta/datacoord-meta/statslog/445066603348649979/445066603348649980/445066603348660939
> > ```
> 
> did you restart datacoord? If it is not helping, let me know and I need the new log

yes, we restarted the datacoord, here's the new logs: 
[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/13488717/milvus-log.tar.gz)

**Comment by xiaofan-luan** [comment]
looks like there still missing some files 
"[2023/11/28 13:32:40.734 +00:00] [WARN] [datanode/channel_meta.go:431] ["failed to load bloom filter files"] [segmentID=445066603348852083] [error="failed to read file/stats_log/445066603348649979/445066603348649980/445066603348852083/100/1: NoSuchKey(key=file/stats_log/445066603348649979/445066603348649980/445066603348852083/100/1)"]"

**Comment by xiaofan-luan** [comment]
use verify-segment command and it will show how many file are missing in your cluster

**Comment by realech** [comment]
> did you got a chance to check file/stats_log/445066603348649979/445066603348649980/445066603348852083/100/1 has any files? or parent directory file/stats_log/445066603348649979/445066603348649980/445066603348852083.
> 
> One possibility is that you are trying to deploy two milvus cluster on same minio with same prefix and they wipe out the other cluster

The `file/stats_log/445066603348649979/445066603348649980/445066603348852083` folder does not exist, but `file/stats_log/445066603348649979/445066603348649980` does

> use verify-segment command and it will show how many file are missing in your cluster

Running verify-segment with birdwatcher does not output anything for me:

```
Milvus(by-dev) > verify-segment
BucketName: xxx
Address: storage.googleapis.com
✔ yes
✔ AK/SK
Use authen:  AK/SK
Milvus(by-dev) > 
```

**Comment by realech** [comment]
At the end, we were not able to fix it so we had to wipe the storage and start populating it from scratch to keep providing service, so we cannot provide more logs about the situation: we updated the milvus version from 2.3.1 to 2.3.3 just in case it is fixed.
