### ISSUE TITLE
[Bug]: Error handling for CGO calls

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#28795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master/2.3
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

For now we handle the SegCore errors by returning a CStatus struct, this protects Milvus from crashing, but not all CGO interfaces follow the style (e.g. `NewSegment`, `NewCollection` ...)

### Expected Behavior

I'm proposing to make all CGO interfaces follow the signature:
```
CStatus MethodName(...)
```

**Comment by congqixia** [comment]
keep this issue

**Comment by congqixia** [comment]
keep this
