### ISSUE TITLE
[Bug]: 所有的表都查不到数据

### ISSUE THREAD

**Issue by suchenghui** [milvus-io/milvus#28790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.3.0
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

所有的表都查不到数据
，报错日志如下：
attempt #0: fail to get shard leaders from QueryCoord: segment=444255720359958542: segment lacks: channel=by-dev-rootcoord-dml_3_444255720359958467v0: channel not available: attempt #1: fail to get shard leaders from QueryCoord: segment=444255720359958542: segment lacks: channel=by-dev-rootcoord-dml_3_444255720359958467v0: channel not available: attempt #2: fail to get shard leaders from QueryCoord: segment=444255720359958542: segment lacks: channel=by-dev-rootcoord-dml_3_444255720359958467v0: channel not available: attempt #3: fail to get shard leaders from QueryCoord: segment=444255720359958542: segment lacks: channel=by-dev-rootcoord-dml_3_444255720359958467v0: channel not available: attempt #4: fail to get shard leaders from QueryCoord: segment=444255720359958542: segment lacks: channel=by-dev-rootcoord-dml_3_444255720359958467v0: channel not available: attempt #5: fail to get shard leaders from QueryCoord: segment=444255720359958542: segment lacks: channel=by-dev-rootcoord-dml_3_444255720359958467v0: channel not available: attempt #6: fail to get shard leaders from QueryCoord: segment=444255720359958542: segment lacks: channel=by-dev-rootcoord-dml_3_444255720359958467v0: channel not available: context done during sleep after run#6: context deadline exceeded: fail to search on all shard leaders

### Milvus Log

报错日志如下：
attempt #0: fail to get shard leaders from QueryCoord: segment=444255720359958542: segment lacks: channel=by-dev-rootcoord-dml_3_444255720359958467v0: channel not available: attempt #1: fail to get shard leaders from QueryCoord: segment=444255720359958542: segment lacks: channel=by-dev-rootcoord-dml_3_444255720359958467v0: channel not available: attempt #2: fail to get shard leaders from QueryCoord: segment=444255720359958542: segment lacks: channel=by-dev-rootcoord-dml_3_444255720359958467v0: channel not available: attempt #3: fail to get shard leaders from QueryCoord: segment=444255720359958542: segment lacks: channel=by-dev-rootcoord-dml_3_444255720359958467v0: channel not available: attempt #4: fail to get shard leaders from QueryCoord: segment=444255720359958542: segment lacks: channel=by-dev-rootcoord-dml_3_444255720359958467v0: channel not available: attempt #5: fail to get shard leaders from QueryCoord: segment=444255720359958542: segment lacks: channel=by-dev-rootcoord-dml_3_444255720359958467v0: channel not available: attempt #6: fail to get shard leaders from QueryCoord: segment=444255720359958542: segment lacks: channel=by-dev-rootcoord-dml_3_444255720359958467v0: channel not available: context done during sleep after run#6: context deadline exceeded: fail to search on all shard leaders

**Comment by xiaofan-luan** [comment]
seems that all the channel can not be loaded.
please offer full logs with export_log.sh so we can know the detailed reason
