### ISSUE TITLE
[Bug]: Unexpected compaction behavior

### ISSUE THREAD

**Issue by WuYiFan0108** [milvus-io/milvus#28799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.16 && 2.3.3
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.2.17 for Milvus 2.2.16 && pymilvus v2.3.3 for Milvus 2.2.3
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I was recently testing the `compact()` function of Milvus and wanted to know the data compaction ratio of Milvus. But I discovered some very strange behavior: every time `compact()` is called, the hard disk size of the collection data increases.
![screenshot-20231128-154557](https://github.com/milvus-io/milvus/assets/139840531/d5ade7f9-a015-404f-b311-202c8082656f)

### Expected Behavior

Hard disk size of the collection data decreases after calling `compact()`.

### Steps To Reproduce

```markdown
1. Disable AutoCompaction according to https://milvus.io/docs/configure-docker.md and https://milvus.io/docs/v2.2.x/configure_datacoord.md#dataCoordcompactionenableAutoCompaction
2. Deploy a new Milvus Standalone instance using Docker Compose.
3. Create a collection named sift10m which contains two fields named id (primary key field) and embedding (vector field)
4. Insert dataset sift10m into collection sift10m and flush it.
5. Build FLAT index on field embedding.(Compaction won't work unless collection has a vector index according to my test.)
6. Use command du -sh volumes/minio to check the hard disk size of the collection sift10m.(1.6G in my test, I think it's to small for sift10m.)
7. Call compact() and use get_compaction_state() to check compaction state
8. When the compression status shows Completed, use command du -sh volumes/minio again to check the hard disk size of the collection sift10m.
9. Repeat step 6 to step 8 if necessary.
```

### Milvus Log

[milvus.log](https://github.com/milvus-io/milvus/files/13485458/milvus.log)

**Comment by xiaofan-luan** [comment]
compaction will rewrite the segment and the old segment will not be garbage collected util a while.

please wait for gc.tolerance and check if data is purged

**Comment by yanliang567** [comment]
/assign @WuYiFan0108 
as commented above. 
/unassign

**Comment by WuYiFan0108** [comment]
The hard disk size of the collection sift10m after gc drop back to 1.6G, which is the same as the hard disk size of the collection that I observed after inserting sift10m data with AutoCompaction disabled. So I guess Milvus just inserts compacted data, no matter AutoCompaction is enabled or not？

**Comment by xiaofan-luan** [comment]
> The hard disk size of the collection sift10m after gc drop back to 1.6G, which is the same as the hard disk size of the collection that I observed after inserting sift10m data with AutoCompaction disabled. So I guess Milvus just inserts compacted data, no matter AutoCompaction is enabled or not？

autoCompaction is a strategy to merge all the new inserted data. 
We recommend you to enable auto compaction especially under frequent insert/delete
