### ISSUE TITLE
[Bug]: 余弦值大于1 

### ISSUE THREAD

**Issue by wanzhixiao** [milvus-io/milvus#28822]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

使用向量库搜索时，metric_type设置为COSINE，为什么distance会大于1
![image](https://github.com/milvus-io/milvus/assets/43194221/3894824d-b5a7-43c8-b0b5-5204b3c2c2e2)
```python
 result = self.db.search(
                collection_name=self.post_collection_name, 
                anns_field=anns_field,
                query_vec=[query_vec], 
                partition_names=[f_corp_code], 
                output_fields=output_fields,
                expr=expr,
                limit=recall_cnt_per_chanel,
                metric_type=self.metric_type
            )
f_post_qids = res.ids
dis = res.distances
 for i, hit in enumerate(res):
       f_post_qid = f_post_qids[i]
       distance = dis[i]
```

**Comment by yanliang567** [comment]
@wanzhixiao what is the milvus version, this was fixed in Milvus 2.3.3. Please retry.
/assign @wanzhixiao 
/unassign

**Comment by wanzhixiao** [comment]
> what is the milvus version, this was fixed in Milvus 2.3.3. Please retry.

2.3.0

**Comment by wanzhixiao** [comment]
使用的是单机版本，需要更新同时docker和pymilvus吗

**Comment by yanliang567** [comment]
it would be perfect.

**Comment by xiaofan-luan** [comment]
this has been fixed in 2.3.3

**Comment by wanzhixiao** [comment]
请问milvus支持倒排索引召回吗？

**Comment by xiaofan-luan** [comment]
Inverted index is under development and could be ready 2024 Q1
