### ISSUE TITLE
[Bug]: milvus-standalone can not started on arm architecture

### ISSUE THREAD

**Issue by ronghuaihai** [milvus-io/milvus#28843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.3.3
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):     rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):  
- OS(Ubuntu or CentOS):  Centos
- CPU/Memory:  aarch64    192 逻辑核  958G总内存
- GPU: 
- Others: 
the os is centos 7.9 on arm  Huawei AIO (All-in-One) Desktop
[root@localhost ~]# uname -a
Linux localhost.localdomain 4.14.0-115.el7a.0.1.aarch64 #1 SMP Sun Nov 25 20:54:21 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux
```

### Current Behavior

i deploy milvus standalone  v2.3.3 on arm  Huawei AIO (All-in-One) Desktop，when i use
 command "docker compose up -d "  ,the docker mivlus-starndalone can'not started ,the content in the docker logs as
 follows:
<img width="1594" alt="image" src="https://github.com/milvus-io/milvus/assets/14067712/95c8b0f2-2329-4f56-b06a-43c0da98bfaf">

[root@localhost milvus]# docker logs 0c23e0a142b0
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
[FATAL tini (1)] Failed to allocate memory for child args: 'Cannot allocate memory'

how i can start the mivlus standalone ?

### Expected Behavior

i want the standalone milvus can start up

### Steps To Reproduce

```markdown
1.wget https://github.com/milvus-io/milvus/releases/download/v2.3.3/milvus-standalone-docker-compose.yml
2.mv milvus-standalone-docker-compose.yml  docker-compose.yml
3.docker compose up -d
4.docker ps -a|grep -i milvus
5.docker logs 0c23e0a142b0
[root@localhost ~]# docker logs 0c23e0a142b0
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
[FATAL tini (1)] Failed to allocate memory for child args: 'Cannot allocate memory'
```

### Milvus Log

[root@localhost ~]# docker logs 0c23e0a142b0
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
[FATAL tini (1)] Failed to allocate memory for child args: 'Cannot allocate memory'

**Comment by xiaofan-luan** [comment]
this might be related

https://github.com/milvus-io/milvus/issues/27726

**Comment by Presburger** [comment]
@ronghuaihai  please check the your system, run this command
```
getconf PAGESIZE
```
