### ISSUE TITLE
[Bug]:  Executing hello_milvus.py according to the official documentation example will result in an error: 'Collection' object has no attribute 'flush'.

### ISSUE THREAD

**Issue by lentitude2tk** [milvus-io/milvus#28863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.3
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka): -
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus
- OS(Ubuntu or CentOS): MacOS
- CPU/Memory: -
- GPU: -
- Others: -
```

### Current Behavior

Created a standalone according to the Milvus official documentation(https://milvus.io/docs/install_standalone-docker.md), then executed hello_milvus.py following the provided link(https://milvus.io/docs/example_code.md), and encountered an error in the end.
```
python3 hello_milvus.py

=== start connecting to Milvus     ===

Does collection hello_milvus exist in Milvus: False

=== Create collection `hello_milvus` ===


=== Start inserting entities       ===

Traceback (most recent call last):
  File "/Users/zilliz/work/milvus-example/hello_milvus.py", line 81, in <module>
    hello_milvus.flush()
AttributeError: 'Collection' object has no attribute 'flush'
```

### Expected Behavior

The expectation is that it should execute smoothly according to the official documentation, and there shouldn't be any code issues.

### Steps To Reproduce

```markdown
1. Created a standalone of version 2.3.3 according to the Milvus documentation(https://milvus.io/docs/install_standalone-docker.md). 
2. Executed hello_milvus.py following the documentation link(https://milvus.io/docs/example_code.md), and encountered an error.
```

**Comment by zhuwenxing** [comment]
What is your pymilvus version? In some old version, this may happed

**Comment by lentitude2tk** [comment]
> happed

Yes, after upgrading the pymilvus version, it indeed resolved the issue. It feels like these kinds of consistently occurring standard error scenarios could be explained in the documentation.
