### ISSUE TITLE
The exception stops the WebServer container directly.

### ISSUE THREAD

**Issue by yu258** [milvus-io/milvus#2889]
Addr [1xxx.xxx:19530] has_collection Rpc error: <_MultiThreadedRendezvous of RPC that terminated with: status = StatusCode.DEADLINE_EXCEEDED details = "Deadline Exceeded" debug_error_string = "{"created":"@1594866741.875701717","description":"Error received from peer ipv4:1xxx.xxx:19530","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Deadline Exceeded","grpc_status":4}"
{'API start': '2020-07-16 02:31:51.772573', 'RPC start': '2020-07-16 02:31:51.871143', 'RPC error': '2020-07-16 02:32:21.876246'} error_code: ILLEGAL_COLLECTION_NAME reason: "Collection already exists"

![image](https://user-images.githubusercontent.com/34839719/87660573-db339e80-c791-11ea-8583-090f7112fdbe.png)

**Comment by tinkerlin** [comment]
which type of client application you used, python SDK or restful api?

**Comment by yu258** [comment]
> which type of client application you used, python SDK or restful api?

python SDK

**Comment by BossZou** [comment]
Which status is your server in? I doubt that some problem happend in your server? May you provide log file of your server and 
 configure file?

**Comment by tinkerlin** [comment]
Is the **webserver** your own application or Milvus? As i see, the GRPC exception cause **webserver** stop. The **webserver** should do some handle exception mechanism.
