### ISSUE TITLE
Write data suggestion

### ISSUE THREAD

**Issue by touch888** [milvus-io/milvus#2891]
If duplicate ID is found in the data writing, can the data be overwritten like elasticsearch instead of prompting that the ID already exists and refusing to write

**Comment by JinHai-CN** [comment]
Thank you for the suggestion, we are planning the ID deduplication function to solve the issue.

**Comment by touch888** [comment]
Thank you very much

**Comment by shengjun1985** [comment]
This is a duplicate issue with #2545.
Please allow me to close it.
Thank you for your concern and support for our project.
