### ISSUE TITLE
[Enhancement]: Insecure connection for OpenTelemetry GRPC communication

### ISSUE THREAD

**Issue by wolfganghuse** [milvus-io/milvus#28914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Currently it is not possible to configure insecure connection when exporting traces to OpenTelemetry.
Milvus uses otlptracegrpc@v1.13.0 which does not allow to switch to insecure by using different endpoint http://localhost:4317, this was introduced with otlptracegrpc@v1.20.0.

### Why is this needed?

especially when running otel-collector as sidecar a secured communication is not always necessary. By allowing insecure endpoint collecting observability data is much easier to configure.

### Anything else?

Find some more details here: [Discussion](https://github.com/milvus-io/milvus/discussions/28883)

**Comment by LoveEachDay** [comment]
@wolfganghuse It's reasonable to not have a tls connection. We'll try to reproduce this issue inhouse shortly.

**Comment by LoveEachDay** [comment]
@wolfganghuse We are now support to export tracing insecure. You can setup like this:
```
trace:
  exporter: otlp
  sampleFraction: 1
  otlp:
    endpoint: localhost:4317
    secure: false
```
