### ISSUE TITLE
[Bug]: Load collection call got stuck and crashed milvus cluster with 4096 partitions, bulk inserts timing out

### ISSUE THREAD

**Issue by kdabbir** [milvus-io/milvus#28919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.2
- Deployment mode(standalone or cluster): Milvus cluster deployed in kubernetes
- MQ type(rocksmq, pulsar or kafka):   External Kafka (AWS MSK)
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.2
num_shards of collection: 16 
1 collection with 4095 partitions & 16 shards
Vector dim: 768
Scale: 1 billion
- CPU/Memory:
The underlying data/query nodes are based on r5.4xlarge node having 14 cores/128gb memory. 12 cores/64gb memory for index nodes based on c5.9xlarge node.

Referred to milvus sizing tool & scaled up 4 index nodes, 18 data nodes (16 are active due to 16 shards), 20 query nodes.

- Also increased etcd ETCD_MAX_TXN_OPS to 6000 to support operations for 4095 partitions.
```

### Current Behavior

We were running a script to ingest 1 billion vectors of 768 dimension, in 1 collection with 16 shards & 4096 partitions. Data is equally distributed to all partitions in the collection.

- Inserted around 180 million vectors 
- Did a loadCollection on the cluster, then saw the below error from GRPC call during search:
```
2023-11-30 09:32:50,306 | ERROR | grpc RpcError: [search], <_InactiveRpcError: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2023-11-30 09:32:48.304529', 'gRPC error': '2023-11-30 09:32:50.306269'}>
2023-11-30 09:32:50,306 | INFO | Exception during search: 
2023-11-30 09:32:50,306 | INFO | <_InactiveRpcError of RPC that terminated with:
    status = StatusCode.DEADLINE_EXCEEDED
    details = "Deadline Exceeded"
    debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2023-11-30T09:32:50.305942553+00:00", grpc_status:4}"

```
- Milvus did restart all of the pods and data coord is not coming up post this. Waited for a day, didn't auto-recover. Tried restarting all deployment, but was seeing this error on data coord all the time:

```
[2023/12/01 20:24:39.783 +00:00] [INFO] [datacoord/server.go:560] ["data coordinator successfully connected to metadata store"] [metaType=etcd]
[2023/12/01 20:24:42.862 +00:00] [WARN] [etcd/etcd_kv.go:648] ["Slow etcd operation(WalkWithPagination)"] ["time spent"=3.078494816s] [prefix=by-dev/meta/datacoord-meta/s]
[2023/12/01 20:24:44.595 +00:00] [DEBUG] [config/etcd_source.go:141] ["etcd refreshConfigurations"] [prefix=by-dev/config] [endpoints="[milvuspartitionspoctest-etcd:2379]"]
[2023/12/01 20:24:49.595 +00:00] [DEBUG] [config/etcd_source.go:141] ["etcd refreshConfigurations"] [prefix=by-dev/config] [endpoints="[milvuspartitionspoctest-etcd:2379]"]
{"level":"warn","ts":"2023-12-01T20:24:49.784Z","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0011e68c0/milvuspartitionspoctest-etcd:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
[2023/12/01 20:24:49.784 +00:00] [ERROR] [datacoord/server.go:571] ["retry func failed"] ["retry time"=0] [error="context deadline exceeded"] [stack="github.com/milvus-io/milvus/internal/datacoord.(*Server).initMeta\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:571\ngithub.com/milvus-io/milvus/internal/datacoord.(*Server).initDataCoord\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:340\ngithub.com/milvus-io/milvus/internal/datacoord.(*Server).Init\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:323\ngithub.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:126\ngithub.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:249\ngithub.com/milvus-io/milvus/cmd/components.(*DataCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/data_coord.go:50\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:113"]
[2023/12/01 20:24:52.959 +00:00] [WARN] [etcd/etcd_kv.go:648] ["Slow etcd operation(WalkWithPagination)"] ["time spent"=2.974251969s] [prefix=by-dev/meta/datacoord-meta/s]
```

- Query coord, data nodes are complaining that data coord is down: `find no available datacoord`, this brings whole cluster down. GRPC calls give below error:
```
 2023-11-30 11:01:57,202 | INFO | <MilvusException: (code=65535, message=stack trace: Execute
/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:455 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask
/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:482 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop
/usr/local/go/src/runtime/asm_amd64.s:1598 runtime.goexit: attempt #0: empty grpc client: find no available datacoord, check datacoord state: attempt #1: empty grpc client: find no available datacoord,

```
- Attached log export of milvus in below section. 
- Prior to load collection, bulk inserts was timing out with below error: 
```
<Bulk insert state:
    
taskID          : 445957139263196164,
state           : Failed and cleaned,
row_count       : 9999,
infos           : {'files': 'reviews2.json', 'collection': 'TestScalePartition', 'partition': 'TestScalePartition0', 'failed_reason': 'the import task has timed out', 'progress_percent': '90', 'persist_cost': '118.54'},
id_ranges       : [445957139250376831, 445957139250377855, 445957139250377871, 445957139250378895, 445957139250378918, 445957139250379942, 445957139250379956, 445957139250380980, 445957139250380980, 445957139250382004, 445957139250382004, 445957139250383028, 445957139250383028, 445957139250384052, 445957139250384052, 445957139250385076, 445957139250385076, 445957139250386100, 445957139250386100, 445957139250386883],
create_ts       : 2023-11-29 16:36:05
>
```

### Expected Behavior

Milvus cluster should be stable with loadCollection noting that the scale was very less around 180 million.
Wanted to understand how to make this cluster working and if having 4096 partitions & 16 shards is a feasible option for 1 billion vector scale, we expect search latencies for k= 16384 under 100ms.

### Steps To Reproduce

```markdown
1. Setup milvus cluster with 1 collection having 16 shards, 4095 partitions. Scale nodes as per sizing tool. 
2. Insert data in all partitions equally.
3. Call load collection which times out and search fails with above exceptions
4. Cluster is unstable and not auto-recovering even after a day.
```

### Milvus Log

Splunk logs-historical logs. Took logs from timeframe when loadCollection is called and post that inserts/searches stopped working
[milvus-splunk-logs.zip](https://github.com/milvus-io/milvus/files/13537082/milvus-splunk-logs.zip)

Below log has pod_describe and some logs after the cluster crashed:
[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/13533393/milvus-log.tar.gz)

### Anything else?

- I was discussing this setup with yhmo from milvus in discord, [Discussion thread](https://discord.com/channels/1160323594396635310/1179350344057229373/1179613960417316984). Before load collection, normal insert was working but bulk insert was timing out and his observation:
> - the data node is busy with compaction tasks for a large amount of segments and bulk insert is timing out

- Having too many segments created because of 4095 partitions & 16 shards in 1 collection could stuck the loading process [Discussion thread](https://discord.com/channels/1160323594396635310/1179350344057229373/1179733281151914096)

- Wanted to double check this understanding and also understand if there is a way to revive this cluster, thanks.

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version: 2.3.2
> - Deployment mode(standalone or cluster): Milvus cluster deployed in kubernetes
> - MQ type(rocksmq, pulsar or kafka):   External Kafka (AWS MSK)
> - SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.2
> num_shards of collection: 16 
> 1 collection with 4095 partitions & 16 shards
> Vector dim: 768
> Scale: 1 billion
> - CPU/Memory:
> The underlying data/query nodes are based on r5.4xlarge node having 14 cores/128gb memory. 12 cores/64gb memory for index nodes based on c5.9xlarge node.
> 
> Referred to milvus sizing tool & scaled up 4 index nodes, 18 data nodes (16 are active due to 16 shards), 20 query nodes.
> 
> - Also increased etcd ETCD_MAX_TXN_OPS to 6000 to support operations for 4095 partitions.
> ```
> 
> ### Current Behavior
> We were running a script to ingest 1 billion vectors of 768 dimension, in 1 collection with 16 shards & 4096 partitions. Data is equally distributed to all partitions in the collection.
> 
> * Inserted around 180 million vectors
> * Did a loadCollection on the cluster, then saw the below error from GRPC call during search:
> 
> ```
> 2023-11-30 09:32:50,306 | ERROR | grpc RpcError: [search], <_InactiveRpcError: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2023-11-30 09:32:48.304529', 'gRPC error': '2023-11-30 09:32:50.306269'}>
> 2023-11-30 09:32:50,306 | INFO | Exception during search: 
> 2023-11-30 09:32:50,306 | INFO | <_InactiveRpcError of RPC that terminated with:
>     status = StatusCode.DEADLINE_EXCEEDED
>     details = "Deadline Exceeded"
>     debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2023-11-30T09:32:50.305942553+00:00", grpc_status:4}"
> ```
> 
> * Milvus did restart all of the pods and data coord is not coming up post this. Waited for a day, didn't auto-recover. Tried restarting all deployment, but was seeing this error on data coord all the time:
> 
> ```
> [2023/12/01 20:24:39.783 +00:00] [INFO] [datacoord/server.go:560] ["data coordinator successfully connected to metadata store"] [metaType=etcd]
> [2023/12/01 20:24:42.862 +00:00] [WARN] [etcd/etcd_kv.go:648] ["Slow etcd operation(WalkWithPagination)"] ["time spent"=3.078494816s] [prefix=by-dev/meta/datacoord-meta/s]
> [2023/12/01 20:24:44.595 +00:00] [DEBUG] [config/etcd_source.go:141] ["etcd refreshConfigurations"] [prefix=by-dev/config] [endpoints="[milvuspartitionspoctest-etcd:2379]"]
> [2023/12/01 20:24:49.595 +00:00] [DEBUG] [config/etcd_source.go:141] ["etcd refreshConfigurations"] [prefix=by-dev/config] [endpoints="[milvuspartitionspoctest-etcd:2379]"]
> {"level":"warn","ts":"2023-12-01T20:24:49.784Z","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0011e68c0/milvuspartitionspoctest-etcd:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
> [2023/12/01 20:24:49.784 +00:00] [ERROR] [datacoord/server.go:571] ["retry func failed"] ["retry time"=0] [error="context deadline exceeded"] [stack="github.com/milvus-io/milvus/internal/datacoord.(*Server).initMeta\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:571\ngithub.com/milvus-io/milvus/internal/datacoord.(*Server).initDataCoord\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:340\ngithub.com/milvus-io/milvus/internal/datacoord.(*Server).Init\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:323\ngithub.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:126\ngithub.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:249\ngithub.com/milvus-io/milvus/cmd/components.(*DataCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/data_coord.go:50\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:113"]
> [2023/12/01 20:24:52.959 +00:00] [WARN] [etcd/etcd_kv.go:648] ["Slow etcd operation(WalkWithPagination)"] ["time spent"=2.974251969s] [prefix=by-dev/meta/datacoord-meta/s]
> ```
> 
> * Query coord, data nodes are complaining that data coord is down: `find no available datacoord`, this brings whole cluster down. GRPC calls give below error:
> 
> ```
>  2023-11-30 11:01:57,202 | INFO | <MilvusException: (code=65535, message=stack trace: Execute
> /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:455 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask
> /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:482 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop
> /usr/local/go/src/runtime/asm_amd64.s:1598 runtime.goexit: attempt #0: empty grpc client: find no available datacoord, check datacoord state: attempt #1: empty grpc client: find no available datacoord,
> ```
> 
> * Attached log export of milvus in below section.
> * Prior to load collection, bulk inserts was timing out with below error:
> 
> ```
> <Bulk insert state:
>     
> taskID          : 445957139263196164,
> state           : Failed and cleaned,
> row_count       : 9999,
> infos           : {'files': 'reviews2.json', 'collection': 'TestScalePartition', 'partition': 'TestScalePartition0', 'failed_reason': 'the import task has timed out', 'progress_percent': '90', 'persist_cost': '118.54'},
> id_ranges       : [445957139250376831, 445957139250377855, 445957139250377871, 445957139250378895, 445957139250378918, 445957139250379942, 445957139250379956, 445957139250380980, 445957139250380980, 445957139250382004, 445957139250382004, 445957139250383028, 445957139250383028, 445957139250384052, 445957139250384052, 445957139250385076, 445957139250385076, 445957139250386100, 445957139250386100, 445957139250386883],
> create_ts       : 2023-11-29 16:36:05
> >
> ```
> 
> ### Expected Behavior
> Milvus cluster should be stable with loadCollection noting that the scale was very less around 180 million. Wanted to understand how to make this cluster working and if having 4096 partitions & 16 shards is a feasible option for 1 billion vector scale, we expect search latencies for k= 16384 under 100ms.
> 
> ### Steps To Reproduce
> ```
> 1. Setup milvus cluster with 1 collection having 16 shards, 4095 partitions. Scale nodes as per sizing tool. 
> 2. Insert data in all partitions equally.
> 3. Call load collection which times out and search fails with above exceptions
> 4. Cluster is unstable and not auto-recovering even after a day.
> ```
> 
> ### Milvus Log
> [milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/13533393/milvus-log.tar.gz)
> 
> ### Anything else?
> * I was discussing this setup with yhmo from milvus in discord, [Discussion thread](https://discord.com/channels/1160323594396635310/1179350344057229373/1179613960417316984). Before load collection, normal insert was working but bulk insert was timing out and his observation:
> 
> > * the data node is busy with compaction tasks for a large amount of segments and bulk insert is timing out
> 
> * Having too many segments created because of 4095 partitions & 16 shards in 1 collection could stuck the loading process [Discussion thread](https://discord.com/channels/1160323594396635310/1179350344057229373/1179733281151914096)
> * Wanted to double check this understanding and also understand if there is a way to revive this cluster, thanks.

You seemed to have too many partitions + shards at same time.

I have bunch of questions about your deployment

1. how many qps you expected?
2.  is this a cloud deployment? What kind of storage, message queue you are using?
3. is there a specific reason you want to have so many partitions? what is the use cases? can we use multiple collections or partition key feature? With 4096 partition and 16 shards, you will have more thnn 40k segments and entities in each segments is gonna to be very samll.

1. From the log, your etcd seems to be always slow. is it deploy on ssd disk? can you use birdwatcher to dump your etcd and let us check?
2. Is there a specfic reason of why you need  that much datanode? I would suggest to have 2-4 
4. Any reason you need that much shard? Each shard can host at least 100M dataset(could be more than 1B) so under your case with 180 million datas 2-4 shards is recommended 
5. You have way less indexnode, that might cause index can not catch up with insertion. I would suggest to have 8 indexnodes when you are inserting but you can shrink to 2-4 if you don't further writes/deletes
6. We've fixed the bug of having 4096 partitions, but it still seems to be really challenge task on milvus, especially when you have so much shards.

**Comment by xiaofan-luan** [comment]
and also, you do need to deploy prometheus and loki for logs and monitorings otherwise there is no way you can manage such a large cluster. 

Most of the logs you offered is unreadable, with the following error:

unable to retrieve container logs for containerd://10207206e4602528b60baeb1da9635ad61aa6655bd1c3b5b95a9558c660d4460

From the current error message:
1. rootcoord/timeticksync.go:313] ["rootcoord send tt to all channels too slowly"] [chanNum=16] [span=2428] -> means your message queus is slow, usually it takes less than 200ms but now it takes 2s.
2. Slow etcd operation(WalkWithPagination)"] ["time spent"=3.078494816s] [prefix=by-dev/meta/datacoord-meta/s] -> means your etcd is slow, takes 3s to run one single action.

So my advice is to check all your dependencies, make sure they all deploy on SSD disk. And you are welcome to send email to james.luan@zilliz.com so our devops team can help you on the initial setup

**Comment by kdabbir** [comment]
@xiaofan-luan  Thanks for your revert. Answers to your queries:

> 1. how many qps you expected?
We haven't estimated this, but it will be very huge, we plan to limit 1 milvus cluster to a set of tenants so that milvus can perform queries within 100-200ms latency

> 2. is this a cloud deployment? What kind of storage, message queue you are using?
Yes, it is deployed in a kubernetes cluster hosted in AWS and managed by Salesforce. Storage is on EC2. For MQ, we use AWS MSK (Managed Streaming for Apache Kafka (MSK).

>3. is there a specific reason you want to have so many partitions? what is the use cases? can we use multiple collections or partition key feature? With 4096 partition and 16 shards, you will have more thnn 40k segments and entities in each segments is gonna to be very samll.

Reason to have multiple partitions is for multi-tenancy. We can load/unload a tenants data using load/unload partition, as each can have huge data and we have an option to deprovision tenants as well. Plan is to keep 1 tenants data in 1 partition.  Using partition_key we cannot use bulk insert which is another reason we wanted to have partitions created.

We can also switch to using multiple collections, but we saw increased load in kafka, timetick issues when we created over 10000 collections. So, I have 2 below questions on this:
 - How many count of collections is estimated to be stable with billions of vectors scale and what is number you recommend?
 - And for these collections, what is the `shards_num` and number of partitions that you recommend? 

> 4. From the log, your etcd seems to be always slow. is it deploy on ssd disk? can you use birdwatcher to dump your etcd and let us check?
For now, we haven't configured birdwatcher, let us look into it

> 5. Is there a specfic reason of why you need that much datanode? I would suggest to have 2-4
16 shards would need 16 data nodes, added 2 just for buffer but they are not being used.

> 6. Any reason you need that much shard? Each shard can host at least 100M dataset(could be more than 1B) so under your case with 180 million datas 2-4 shards is recommended
We created 16 shards to increase insertion throughput as we saw better ingestion rates when we were inserting upto 1 billion vectors in batches

> 7. You have way less indexnode, that might cause index can not catch up with insertion. I would suggest to have 8 indexnodes when you are inserting but you can shrink to 2-4 if you don't further writes/deletes
Noted, I kept to 4 as I had stopped insertion, during insertion I was monitoring memory of index nodes and was upscaling nodes.

> 8. We've fixed the bug of having 4096 partitions, but it still seems to be really challenge task on milvus, especially when you have so much shards.
What is reasonable number we can set per collection? and how many collections can we create? We plan to use 768 dim vector and scale is upto 1-2 Billion per cluster. Plan is to have 1 partition for 1 tenant's data.

**Comment by kdabbir** [comment]
> your message queus is slow, usually it takes less than 200ms but now it takes 2s.

> means your etcd is slow, takes 3s to run one single action.

Is there any etcd/kafka configuration we can use to fix this issue? 

We have logs flowing to splunk, will check if I can find more logs to help understand. 
This is a cluster in dev environment, we plan to add prometheus and observality to monitor it better.

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan Thanks for your revert. Answers to your queries:
> 
> > 1. how many qps you expected?
> 
> We haven't estimated this, but it will be very huge, we plan to limit 1 milvus cluster to a set of tenants so that milvus can perform queries within 100-200ms latency
> 
> > 2. is this a cloud deployment? What kind of storage, message queue you are using?
> 
> Yes, it is deployed in a kubernetes cluster hosted in AWS and managed by Salesforce. Storage is on EC2. For MQ, we use AWS MSK (Managed Streaming for Apache Kafka (MSK).
> 
> > 3. is there a specific reason you want to have so many partitions? what is the use cases? can we use multiple collections or partition key feature? With 4096 partition and 16 shards, you will have more thnn 40k segments and entities in each segments is gonna to be very samll.
> 
> Reason to have multiple partitions is for multi-tenancy. We can load/unload a tenants data using load/unload partition, as each can have huge data and we have an option to deprovision tenants as well. Plan is to keep 1 tenants data in 1 partition. Using partition_key we cannot use bulk insert which is another reason we wanted to have partitions created.
> 
> We can also switch to using multiple collections, but we saw increased load in kafka, timetick issues when we created over 10000 collections. So, I have 2 below questions on this:
> 
> * How many count of collections is estimated to be stable with 1-2billions of vectors scale and what is number you recommend?
> * And for these collections, what is the `shards_num` and number of partitions that you recommend?
> 
> > 4. From the log, your etcd seems to be always slow. is it deploy on ssd disk? can you use birdwatcher to dump your etcd and let us check?
> 
> For now, we haven't configured birdwatcher, let us look into it
> 
> > 5. Is there a specfic reason of why you need that much datanode? I would suggest to have 2-4
> >    16 shards would need 16 data nodes, added 2 just for buffer but they are not being used.
> 
> > 6. Any reason you need that much shard? Each shard can host at least 100M dataset(could be more than 1B) so under your case with 180 million datas 2-4 shards is recommended
> 
> We created 16 shards to increase insertion throughput as we saw better ingestion rates when we were inserting upto 1 billion vectors in batches
> 
> > 7. You have way less indexnode, that might cause index can not catch up with insertion. I would suggest to have 8 indexnodes when you are inserting but you can shrink to 2-4 if you don't further writes/deletes
> 
> Noted, I kept to 4 as I had stopped insertion, during insertion I was monitoring memory of index nodes and was upscaling nodes.
> 
> > 8. We've fixed the bug of having 4096 partitions, but it still seems to be really challenge task on milvus, especially when you have so much shards.
> 
> What is reasonable number of partitions we can set per collection? and how many collections can we create? We plan to use 768 dim vector and scale is upto 1-2 Billion per cluster. Plan is to have 1 partition for 1 tenant's data. We can spin up multiple milvus clusters if 1 cluster cannot support so much collections/partitions, but we are doing these tests to understand that limitation.

1. using resource group might help you on isolate multiple users.
2. Our cloud service also use AWS MSK so this should not be a problem. Is this shared with other services? Any config changes on MSK?
3. Unfortunately, multi tenancy with both 1000+ partitions or collections is an unsolved issue for current release. Our recommendation is to use partition key to do logical isolation. For physical isolation, Milvus 2.3.4 will support at least 10000+ collections and that should help on most cases. Here is more details about multi tenancy in milvus https://milvus.io/docs/multi_tenancy.md
4. For 1 billion collection, 4-8 shard might be a good start, and it can scale to 10 billion at least

We are also working on improving multi colleciton/partition use cases in house, please stay tuned for MIlvus 2.3.4.

Also, please ensure your etcd is on SSD persistent volume, this is super important

**Comment by kdabbir** [comment]
@xiaofan-luan  Thanks for your response:

> 1. using resource group might help you on isolate multiple users.

We can look at scaling more query nodes for few collections where tenant data is more, but still we need to figure out how many collections/partitions to store our data.

> 2. Our cloud service also use AWS MSK so this should not be a problem. Is this shared with other services? Any config changes on MSK?

- Dont see any issue with MSK so far, its not shared with other services and we are changing topic names for each milvus cluster. CPU and disk utilization is fine.

> 3. Unfortunately, multi tenancy with both 1000+ partitions or collections is an unsolved issue for current release. Our recommendation is to use partition key to do logical isolation. For physical isolation, Milvus 2.3.4 will support at least 10000+ collections and that should help on most cases. Here is more details about multi tenancy in milvus https://milvus.io/docs/multi_tenancy.md

Till 2.3.4 gets released, can we work with 100 collections & 4 shards, each collection holding 10 Million vector data, is this feasible?

> 4. For 1 billion collection, 4-8 shard might be a good start, and it can scale to 10 billion at least
Noted, we will stick to 4 shards mostly.

> We are also working on improving multi colleciton/partition use cases in house, please stay tuned for MIlvus 2.3.4.

-  Can I know what optimisations your team is doing in 2.3.4 to support 10k collections? When we read your docs and spoke to Yi Wang, Frank from milvus, we understood that with more collections rootcoord will be bombarded with timetick requests, as rootcord sends a timetick every 200ms per partition in a collection, eventually crashing the cluster. Also, load on kafka will be more. 
- When can we expect 2.3.4 to be released? Any ETA? We would love to test this feature out with 10k collections once it is out.

> Also, please ensure your etcd is on SSD persistent volume, this is super important

Noted, we are moving all etcd to SSD volumes. Any other node such as query/data/index need SSD? 
Exception is If diskANN is used yes, we need ssd for data,query node.

**Comment by kdabbir** [comment]
All our persistent volumes are on SSD and still see this issue.

<img width="1724" alt="Screenshot 2023-12-06 at 1 10 55 PM" src="https://github.com/milvus-io/milvus/assets/29181508/5c7e568e-7b52-4609-9355-459559a974ec">

@xiaofan-luan @czs007 @wayblink is there a way to increase timeout of initial initilization of datacoord with etcd? The deadline exceeded suggests that the etcd operation didn't complete in time and is there a config to increase this timeout so eventually it may succeed?

**Comment by kdabbir** [comment]
And I found this thread where a fix is released to increase timeout, can I know details on this patch? and can we prioritize on releasing this fix for 2.3.3 very soon? It would help us to try our POCs out: https://discord.com/channels/1160323594396635310/1180319455478284288/1181863881845522503

**Comment by yanliang567** [comment]
we have merged a few PRs to improve the resource usage with thousands of partitions, there are a few PRs pending for merge.

**Comment by yanliang567** [comment]
@kdabbir any chance you could retry on milvus v2.3.5 and please  feel free to keep us posted
