### ISSUE TITLE
[Bug]: No error will be reported when the number of created collections exceeds the limit 4096

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#28937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20231130-34b47cf3 
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

conditions:
pymilvus 2.3.x
milvus 2.2.x

action:
create 4097 partitions

behaviour:
```
>>> 
>>> exist_partition_num = len(collection.partitions)
>>> exist_partition_num
4096
>>> partition_name = "partition_4097"
>>> res = collection.create_partition(partition_name)
>>> partition_name = "partition_4098"
>>> res = collection.create_partition(partition_name)
>>> partition_name = "partition_4099"
>>> res = collection.create_partition(partition_name)
>>> partition_name = "partition_5000"
>>> res = collection.create_partition(partition_name)
>>> 
>>> exist_partition_num = len(collection.partitions)
>>> exist_partition_num
4096
>>> 
>>> 
```

No error will be reported when the number of created collections exceeds the limit 4096.
And the creation is a failure actually.
And it may cause data loss problems.

### Expected Behavior

report error

**Comment by yanliang567** [comment]
almost every requests with pymilvus 2.3.x do not return errors if connecting to milvus 2.2.x, which could cause data lost for users.  please help.

**Comment by XuanYang-cn** [comment]
I see its already done by this PR, https://github.com/milvus-io/pymilvus/pull/1805/\
@NicoYuan1986 Please help verify pymilvus==2.3.3.post1.dev7
/unassign

**Comment by NicoYuan1986** [comment]
verify fixed. 
pymilvus==2.3.4
