### ISSUE TITLE
[Bug]:  Accesslog print wrong error code

### ISSUE THREAD

**Issue by aoiasd** [milvus-io/milvus#28940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Only print "OK" even method failed.

**Comment by aoiasd** [comment]
> access log does not turn on error messages by default

Will refine with SDK Version support. https://github.com/milvus-io/milvus/pull/28835

**Comment by elstic** [comment]
Please don't close the issue yourself, you should ask me to verify it before closing it.  @aoiasd

**Comment by elstic** [comment]
The error msg has been verified. 
![image](https://github.com/milvus-io/milvus/assets/48523564/39776e30-9ef5-417d-a3cb-3b9a30305963)

Verify image:2.3-20231208-bba0e159-amd64
