### ISSUE TITLE
[Bug]: Build Issue on Linux 

### ISSUE THREAD

**Issue by harshakhmk** [milvus-io/milvus#28957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster): standalone 
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu 20.04
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I am building milvus using "make" command, I have followed the same steps mentioned [here](https://github.com/milvus-io/milvus/blob/master/DEVELOPMENT.md#building-milvus-on-a-local-osshell-environment)

I am getting the error: 
```
Conan install error unrecognised arguments --install-folder conan
ERROR: Existing with code:2
Conan install failed
make: *** [Makefile:200: build-3rdparty] Error1
```
Here is the complete log
``` 
Download milvus -proto repo
Build 3rd party
WARN: Cannot find /home/test/user/milvus/internal/core/output/lib/libjemalloc.so
Running on
Conan install error unrecognised arguments --install-folder conan
ERROR: Existing with code:2
Conan install failed
make: *** [Makefile:200: build-3rdparty] Error1

```

### Expected Behavior

Expected to build 

### Steps To Reproduce

```markdown
1)$ git clone https://github.com/milvus-io/milvus.git
2)$ cd milvus/
3)$ ./scripts/install_deps.sh
4)$ make
```

**Comment by harshakhmk** [comment]
I am using Ubuntu 20.04 and I have taken latest code of milvus

**Comment by harshakhmk** [comment]
Hi, could anyone provide any help with the build process

**Comment by yah01** [comment]
hey @harshakhmk, this should be a problem while compiling with conan v2.0, Milvus requires the conan 1.61.0, you could try to uninstall your conan and install the v1.61.0 by `pip install conan==1.61.0`

**Comment by harshakhmk** [comment]
I installed the conan package version 1.61.0, but I am getting below error
```
Exception error downloading file https://github.com/google/googletest/archive /release -1.8.1.tar.gz  Https connect pool(host=github.com, port =443)      Max retries exceed with URL   /google/googletest/archive /release-1.8.1.tar.gz cost by SSL error SSL shirt verification error SSL certificate verify failed e certificate key to weak
conan install failed.
```

**Comment by chiru091096** [comment]
> I installed the conan package version 1.61.0, but I am getting below error
> 
> ```
> Exception error downloading file https://github.com/google/googletest/archive /release -1.8.1.tar.gz  Https connect pool(host=github.com, port =443)      Max retries exceed with URL   /google/googletest/archive /release-1.8.1.tar.gz cost by SSL error SSL shirt verification error SSL certificate verify failed e certificate key to weak
> conan install failed.
> ```

Even I'm facing same issue when building with make command. How to fix this issue

**Comment by xiaofan-luan** [comment]
can you share your compile error info?
which command trigger this error?
we've test on ubuntu 20.04 and works perfect. 

hopefully this issue can help https://github.com/conan-io/conan/issues/9649

**Comment by chiru091096** [comment]
gtest/1.8.1: ERROR: Error downloading file https://github.com/google/googletest/archive/release-1.8.1.tar.gz: 'HTTPSConnectionPool(host='[github.com](http://github.com/)', port=443): Max retries exceeded with url: /google/googletest/archive/release-1.8.1.tar.gz (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))'
gtest/1.8.1: Waiting 5 seconds to retry...
ERROR: gtest/1.8.1: Error in source() method, line 106
get(self, **self.conan_data["sources"][self.version], strip_root=True)
ConanException: Error downloading file https://github.com/google/googletest/archive/release-1.8.1.tar.gz: 'HTTPSConnectionPool(host='[github.com](http://github.com/)', port=443): Max retries exceeded with url: /google/googletest/archive/release-1.8.1.tar.gz (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))'
conan install failed
make: *** [Makefile:200: build-3rdparty] Error 1

**Comment by xiaofan-luan** [comment]
@chiru091096 
did you try to download  https://github.com/google/googletest/archive/release-1.8.1.tar.gz with your network?
Seems that this is more  like a network issue?

**Comment by chiru091096** [comment]
@xiaofan-luan 
I'm able to download  [ https://github.com/google/googletest/archive/release-1.8.1.tar.gz ](https://github.com/google/googletest/archive/release-1.8.1.tar.gz)  with "wget", however, I still face the issue. I even commented gtest in conanFile.py, however, I'm facing same error with other packages.

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan I'm able to download [ https://github.com/google/googletest/archive/release-1.8.1.tar.gz ](https://github.com/google/googletest/archive/release-1.8.1.tar.gz) with "wget", however, I still face the issue. I even commented gtest in conanfile.py, however, I'm facing same error with other packages. Is there any way to disable the ssl certificate verification for packages mentioned in conanfile.py . I disabled ssl certificate verification for links present in conan remote list, however, I still get the same error.

this means this is a network issue.  You will need to try to use network proxy to fix.

Try to not build with googletest see if it works
cmake/DefineOptions.cmake:    define_option(MILVUS_BUILD_TESTS "Build the MILVUS googletest unit tests" ON)
cmake/DefineOptions.cmake:    define_option(MILVUS_BUILD_TESTS "Build the MILVUS googletest unit tests" OFF)

**Comment by chiru091096** [comment]
@xiaofan-luan, thanks for the suggestion. I'll try that.

**Comment by chiru091096** [comment]
I'm able to build now without any issues. thanks for the support. 
I tried to run milvus cluster (_./scripts/start_cluster.sh_) and it runs fine. However, I tried to start milvus standalone (._/scripts/start_standalone.sh_) but milvus process stops automatically within few seconds. How to fix this

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan, I'm able to build now without any issues. thanks for the support. I tried to run milvus cluster (_./scripts/start_cluster.sh_) and it runs fine. However, I tried to start milvus standalone (._/scripts/start_standalone.sh_) but milvus process stops automatically within few seconds. How to fix this

did you check the log? I guess this is due to port binding or some other reasons but you will need to check the detailed log.

Usually I would suggest you to deploy docker image directly

**Comment by chiru091096** [comment]
@xiaofan-luan ,
I can see below logs at the end.. I'm thinking of building from source and use milvus, so I can't use docker. 

```
[WARN] [sessionutil/session_util.go:1173] ["not found server info file path"] [filepath=/tmp/milvus/server_id_646122] [error="stat /tmp/milvus/server_id_646122: no such file or directory"]
[WARN] [milvus/util.go:209] ["not found session info, skip to clean sessions"]
subprocess exit, signal: aborted
```

**Comment by xiaofan-luan** [comment]
this simply means the server received a terminate signal .
could you upload the full log?

**Comment by chiru091096** [comment]
> this simply means the server received a terminate signal . could you upload the full log?

@xiaofan-luan 
I tried same on different systems and I face the same issue. I have attached the full logs below

[standalone.log](https://github.com/milvus-io/milvus/files/13829936/standalone.log)

**Comment by chiru091096** [comment]
@xiaofan-luan , any suggestions on how to fix this will be extremely helpful.

**Comment by chiru091096** [comment]
@yhmo , thank you for the [fix](https://discord.com/channels/1160323594396635310/1171824088109547561/threads/1192770702529544312)

**Comment by chiru091096** [comment]
> > this simply means the server received a terminate signal . could you upload the full log?
> 
> @xiaofan-luan I tried same on multiple systems and I face the same issue. I have attached the full logs below. Issue happens only with standalone.
> 
> [standalone.log](https://github.com/milvus-io/milvus/files/13829936/standalone.log)

@yhmo , thank you for the [fix](https://discord.com/channels/1160323594396635310/1171824088109547561/threads/1192770702529544312)

**Comment by chiru091096** [comment]
@yhmo 
thank you for below fix. milvus standalone now runs continuously

`error="mkdir /var/lib/milvus: permission denied"

Before you run the start_standalone.sh, modify the configs/milvus.yaml
Replace all the "/var/lib/milvus" with "/tmp/milvus" (you can specify to any local path that has permission to write)`

**Comment by chiru091096** [comment]
Now my milvus server runs continuously. However, I'm not able to use pymilvus sdk as I either get the error
 ```
"pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530. Timeout)>"    or
 "ImportError: cannot import name 'MilvusClient' from 'pymilvus' ".
```
 Is this happening due to version mismatch of milvus server and pymilvus? I tried with various versions of milvus and pymilvus. However, I'm not able to make it work. Kindly help me with the right versions of pymilvus  and milvus(standalone and to be built from source for x86)  I need to use to make it work.

**Comment by chiru091096** [comment]
Issue solved after following these [steps](https://github.com/milvus-io/milvus/discussions/23420#discussioncomment-5611034). Thank you @yhmo
