### ISSUE TITLE
[Bug]: don't log sensitive info from kafka config

### ISSUE THREAD

**Issue by yiwangdr** [milvus-io/milvus#28967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://github.com/milvus-io/milvus/blob/ab630548f49495a677555b91cd34bccde7d6924f/pkg/mq/msgstream/mqwrapper/kafka/kafka_client.go#L52-L55

We print everything out as plain text, which contains sensitive info such as saslPassword

### Expected Behavior

Don't print out sensitive fields such as saslUsername and saslPassword.

**Comment by yanliang567** [comment]
/assign @yiwangdr 
could you please help to fix it?
/unassign
