### ISSUE TITLE
Modification of building index process

### ISSUE THREAD

**Issue by sunby** [milvus-io/milvus#28994]

**Comment by yanliang567** [comment]
could you please share more info about why we need to update it, what will it looks like?

**Comment by sunby** [comment]
> could you please share more info about why we need to update it, what will it looks like? @sunby

Sure, it's context is in #28376. 
After integrating storagev2 in index building, we could build index in milvus based on storagev2 and index files will be saved in storagev2. Before that we already integrate storagev2 in segcore and write path in datanode.
