### ISSUE TITLE
[Bug]: RESTful API, the parameter 'params' in the search operation is invalid

### ISSUE THREAD

**Issue by hanchikang** [milvus-io/milvus#29004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.3.3
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 0
- Others:
```

### Current Behavior

**Anticipated**：
![image](https://github.com/milvus-io/milvus/assets/20742865/cfa3ffb1-b914-48af-8e6a-5968282d1ff2)

**Actual**
![image](https://github.com/milvus-io/milvus/assets/20742865/dfe53f15-ea79-447f-9706-37eb43e515cc)

**Comment by yanliang567** [comment]
@hanchikang does it reproduce with the other sdk, such as pymilvus?
@czs007 could you please take a look?
/assign @czs007 
/unassign
