### ISSUE TITLE
[Bug]: Milvus standalone automatically disconnects，why？

### ISSUE THREAD

**Issue by gggdroa** [milvus-io/milvus#29028]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.3
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Tutorial link：https://milvus.io/docs/install_standalone-gpu-docker.md
When I follow the tutorial to start：sudo docker compose up -d，In a few seconds，milvus-standalone Automatic shutdown
![image](https://github.com/milvus-io/milvus/assets/106646583/0d9c58f5-1286-4e93-8076-edf4ff9974ae)
![image](https://github.com/milvus-io/milvus/assets/106646583/e268d460-2605-4959-82be-8ad58cd42ae9)

Attu：
![image](https://github.com/milvus-io/milvus/assets/106646583/e1bcc6e3-4ebb-4e0c-a3a8-3ab3d883122d)

**Comment by yanliang567** [comment]
@gggdroa please attach milvus logs: For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.

/assign @gggdroa

**Comment by yanliang567** [comment]
please attach the log files

**Comment by gggdroa** [comment]
> please attach the log files

[milvus.log](https://github.com/milvus-io/milvus/files/13593398/milvus.log)

**Comment by sunby** [comment]
> > please attach the log files
> 
> [milvus.log](https://github.com/milvus-io/milvus/files/13593398/milvus.log)

Do you have enough disk space for minio. It complains that 'Storage backend has reached its minimum free drive threshold. Please delete a few objects to proceed.'

**Comment by yanliang567** [comment]
I'd close this issue as comments above. please feel free to file one if any new issues
