### ISSUE TITLE
[Enhancement]: Support deploying Milvus cluster on K8s on Arm64 architecture server

### ISSUE THREAD

**Issue by chengwz** [milvus-io/milvus#29059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Support deploying Milvus cluster on K8s on Arm64 architecture server

### Why is this needed?

We have several Arm64 architecture servers that have already been deployed with K8s, and now we need to deploy a Milvus cluster.

**Comment by xiaofan-luan** [comment]
Milvus 2.3.3 should already support ARM

**Comment by ssddn** [comment]
遇到了相同问题，请问如何解决？
