### ISSUE TITLE
The Milvus cluster resulted in the loss of data files.

### ISSUE THREAD

**Issue by wuxiaomei92** [milvus-io/milvus#2908]
**Describe the bug**
The Milvus cluster resulted in the loss of data files.

**Steps/Code to reproduce behavior**
I deployed a cluster of 1 write node and 3 read nodes(There are two machines,one deploys the write and read nodes,and another one deploy two read nodes ). After deployment, I used the API to query the collection status, but was prompted that the file path could not be found.
![image](https://user-images.githubusercontent.com/15917470/87842976-2e693680-c8e3-11ea-9a73-f9e0d334488e.png)
The cluster data is from the original standalone node, It's using the same directory of data.And I deployed the cluster manually instead of using K8S deployment.I'm not sure if it's because I didn't close the original standalone node.
After that I use rebuild the cluster index, background debug log always indicates that some file is being used.

**Environment details**
- Hardware/Softward conditions (GPU nividia p4)
- Method of installation (Docker)
- Milvus version (v0.10.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Comment by tinkerlin** [comment]
Do they share the same file system?

**Comment by tinkerlin** [comment]
And Milvus native distributed deploy is not supported. lt's rely on Mishards or user develop application. As you mentioned before, you using k8s to deploy distribute milvus, is by [milvus-helm](https://github.com/milvus-io/milvus-helm)?

**Comment by wuxiaomei92** [comment]
> Do they share the same file system?

Yes.

**Comment by wuxiaomei92** [comment]
> And Milvus native distributed deploy is not supported. lt's rely on Mishards or user develop application. As you mentioned before, you using k8s to deploy distribute milvus, is by [milvus-helm](https://github.com/milvus-io/milvus-helm)?

I'm not using k8s.I deploy nfs,and start milvus cluster manually.

**Comment by tinkerlin** [comment]
You must shared the metadata db and data both.

**Comment by tinkerlin** [comment]
First plz make sure the machines can access the same datafolder and metadb.

**Comment by wuxiaomei92** [comment]
> You must shared the metadata db and data both.
Yes,I did.

**Comment by wuxiaomei92** [comment]
> You must shared the metadata db and data both.

Yes,I did.

**Comment by wuxiaomei92** [comment]
> First plz make sure the machines can access the same datafolder and metadb.
I'm sure.

**Comment by wuxiaomei92** [comment]
> First plz make sure the machines can access the same datafolder and metadb.

I'm sure it works.

**Comment by tinkerlin** [comment]
This type of deployment will only work if your data files are no longer changing (all background data merging and indexing tasks are over). The read node does not perceive any change in the write node. It's going to create a lot of inconsistencies.

**Comment by wuxiaomei92** [comment]
> This type of deployment will only work if your data files are no longer changing (all background data merging and indexing tasks are over). The read node does not perceive any change in the write node. It's going to create a lot of inconsistencies.

Ok, I see. Milvus cluster  is not suitable for our usage scenario.

**Comment by tinkerlin** [comment]
We have developed an experimental distributed middleware [mishards](https://github.com/milvus-io/milvus/tree/master/shards). I hope this helps.

**Comment by wuxiaomei92** [comment]
> We have developed an experimental distributed middleware [mishards](https://github.com/milvus-io/milvus/tree/master/shards). I hope this helps.

 I mentioned above is deployed by Mishard.

**Comment by tinkerlin** [comment]
> This type of deployment will only work if your data files are no longer changing (all background data merging and indexing tasks are over). The read node does not perceive any change in the write node. It's going to create a lot of inconsistencies.

There is some misunderstanding here, I thought you didn't use mishards. The above is for cases that don't rely on middleware to deploy. @wuxiaomei92

**Comment by wuxiaomei92** [comment]
> > This type of deployment will only work if your data files are no longer changing (all background data merging and indexing tasks are over). The read node does not perceive any change in the write node. It's going to create a lot of inconsistencies.
> 
> There is some misunderstanding here, I thought you didn't use mishards. The above is for cases that don't rely on middleware to deploy. @wuxiaomei92
> 
> Can you write down the steps on how to reproduce it?

I had a machine that deployed a single node of Milvus.We had frequent query requirements, so we wanted to see if the Milvus cluster could improve the efficiency of concurrent queries.We added another machine to do the cluster,  the deployment is as follows:
![image](https://user-images.githubusercontent.com/15917470/87846605-9d568780-c903-11ea-9560-cbb0336b4e65.png)

I installed NFS service on machine1, sharing the write node data directory of machine1 to the data directories of both read nodes of machine 2.Then start four nodes(one rw node, three ro nodes) and one Mishards.After startup, the problem I mentioned above occurs.

**Comment by tinkerlin** [comment]
> I'm not sure if it's because I didn't close the original standalone node.
After that I use rebuild the cluster index, background debug log always indicates that some file is being used.

Two write nodes(rw+standalone) can not exist at the same time. Can you try closing the standalone node?
