### ISSUE TITLE
[Bug]: Querynode crash when setting mmap path to an existing system directory after deployment 

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#29091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3-20231204-2873be92-amd64
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. deploy milvus using helm 
2. modify the instance's configmaps and set the mmap path to /milvus. 
3. reboot the queryrnode and crash it. 

![image](https://github.com/milvus-io/milvus/assets/48523564/d4ef419c-1353-4aa3-aced-c02b94db95eb)

For example, these directories:  /,   /sys,    /milvus

### Expected Behavior

If a user accidentally sets an existing system directory, hopefully a subfolder of mmap can be created to hold the data instead of the crash 

### Anything else?

 deployment also fails if you use an existing system directory set to mmap during deployment.

**Comment by yah01** [comment]
the core reason is that the program has no write access to the given directory, it's impossible to create a subfolder in it. @elstic 

I would add a check whether the given directory is valid, but prefer to panic if it's invalid, any comment? @xiaofan-luan

**Comment by yanliang567** [comment]
@yah01 any updates
