### ISSUE TITLE
[Enhancement]: Replace tecbot/gorocksdb

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#29098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

The tecbot/gorocksdb is not actively maintained, and didn't support rocksdb latest rocksdb 7.x/8.x version.

https://github.com/linxGnu/grocksdb seems to be a reasonbale replacement and it is actively maintained.

We want to make sure this is same as the old tecbot and we can upgrade with no compatibility issue.

**Comment by smellthemoon** [comment]
have checked the code, it's ok to upgrade. try to replace it.
