### ISSUE TITLE
[Bug]: Integrating Milvus with GKE Anthos Service Mesh

### ISSUE THREAD

**Issue by iameminmammadov** [milvus-io/milvus#29096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.2
- Deployment mode(standalone or cluster): standalone on GKE cluster
- MQ type(rocksmq, pulsar or kafka): None
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.2
- OS(Ubuntu or CentOS):  Ubuntu
- CPU/Memory: 
- GPU: None
- Others:
```

### Current Behavior

Hey guys,

Trying to integrate Milvus with ASM. It reaches https: // DNS with 443 but fails to get response from gRPC. I get 404 from POST in K8s logs, and in terminal I get "invalid content-type". I provided all of the screenshots and can provide DestionationRule and VirtualService yamls as well. 

Port forwarding works and connection is fine. Curl from inside of pod works fine as well (milvus.milvus.svc.cluster.local/api/v1/health). 

![error_connection](https://github.com/milvus-io/milvus/assets/24482886/ed612fe4-9e95-43b0-8dec-5642f469920c)
![error2](https://github.com/milvus-io/milvus/assets/24482886/2d8e5b23-4844-43da-a7fa-2d7d504e5439)

### Expected Behavior

I should be able to connect to DNS with 443 exposed.

### Milvus Log

Provided a screenshot from K8s logs. The pod logs are identical.

**Comment by yanliang567** [comment]
/assign @wyfeng001
please help to take a look

/unassign

**Comment by iameminmammadov** [comment]
Thank you @yanliang567 . Seems like @wyfeng001 couldn't get assigned. Is there someone else who can take a look? Thanks.

**Comment by yanliang567** [comment]
don't worry, i have sent him a message.

**Comment by iameminmammadov** [comment]
Thank you

**Comment by wyfeng001** [comment]
Does the ASM component sit between your miluvs client  and the milvus proxy service? My guess is that the reverse proxy (ASM) is not passing the correct content-type .  

Can you try connecting Milvus service via pyMilvus/milvus_cli ? And then try using curl directly. 
`curl -s --request POST \
     --url "${HOST}:${PORT}/v1/vector/collections/create" \
     --header "accept: application/json" \
     --header "content-type: application/json" \
     -d '{...}'`
Can both methods be successful?

https://github.com/grpc/grpc/issues/29706

**Comment by iameminmammadov** [comment]
Hey @wyfeng001 . Thank you for getting back to me. I will get back to you with results on Wednesday, Dec. 27th. Thanks.

**Comment by iameminmammadov** [comment]
Connection fails via PyMilvus or Milvus CLI. Helm is deployed successfully. The above error appears. No point in POST as no connection can be established.

**Comment by iameminmammadov** [comment]
Hey @wyfeng001 . Would you have any tips?

**Comment by haorenfsa** [comment]
Hi, @iameminmammadov,  As I know, GKE requires its backend for https to enable tls as well. You can try updating you milvus with `common.security.tlsMode=1`

There maybe more than one problem. So please provide us with the details about how you deploy & expose your milvus. For example, your `helm values`, the configuration of your `ingress` and etc.
