### ISSUE TITLE
[Bug]: install offline external kafka, Minio has no data when inserting data

### ISSUE THREAD

**Issue by qiyunsheng** [milvus-io/milvus#29103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.13
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): centoss
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Use milvus_manifest.yaml install offline on k8s,  and external etcd ,external kafka,external minio.    Minio has no data when inserting data.  Kafka has automatically created  topic . It seems that there is no consumption.  No error messages were found, what is the problem generally

### Milvus Log

datanode log only [INFO] [datanode/flow_graph_time_tick_node.go:115] ["UpdateChannelCheckpoint success"] [channel=by-dev-rootcoord-dml_1_446147159700424532v0] [cpTs=446237123281158145]

**Comment by xiaofan-luan** [comment]
1. please offer full milvus log
2. please offer you milvus.yaml file, (or operater,helm config file)

Most likely this is the configuration problem

**Comment by qiyunsheng** [comment]
[datacoord.log.log](https://github.com/milvus-io/milvus/files/13631505/datacoord.log.log)
[datanode.log.log](https://github.com/milvus-io/milvus/files/13631507/datanode.log.log)
[indexcoord.log.log](https://github.com/milvus-io/milvus/files/13631509/indexcoord.log.log)
[indexnode.log.log](https://github.com/milvus-io/milvus/files/13631510/indexnode.log.log)
[milvus_manifest_ex3.yaml.log](https://github.com/milvus-io/milvus/files/13631511/milvus_manifest_ex3.yaml.log)
[proxy.log.log](https://github.com/milvus-io/milvus/files/13631512/proxy.log.log)
[querycoord.log.log](https://github.com/milvus-io/milvus/files/13631513/querycoord.log.log)
[querynode.log.log](https://github.com/milvus-io/milvus/files/13631514/querynode.log.log)
[roodcoord.log.log](https://github.com/milvus-io/milvus/files/13631515/roodcoord.log.log)

**Comment by qiyunsheng** [comment]
File upload. Please help find the problem Thanks!!

**Comment by yanliang567** [comment]
/assign @wyfeng001 
could you please help to take a look first?
/unassign
