### ISSUE TITLE
myeasylog.log generated in milvus dir

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#2910]
**Please state you issue using the following template and, most importantly, in English.**

**Describe the bug**
```
[root@93ef23b13482 milvus]# ll
total 28
drwxr-xr-x 2 root root 4096 Jul 17 15:36 bin
drwxr-xr-x 2 root root 4096 Jul 17 15:36 conf
drwxr--r-- 3 root root 4096 Jul 18 03:10 db
drwxr-xr-x 2 root root 4096 Jul 17 15:36 lib
-rw-r----- 1 root root    0 Jul 18 01:46 lock
drwxr-x--x 2 root root 4096 Jul 18 01:46 logs
-rw-r--r-- 1 root root    0 Jul 18 01:46 myeasylog.log
drwxr-xr-x 3 root root 4096 Jul 17 15:36 scripts
drwxr-xr-x 2 root root 4096 Jul 18 03:11 wal

```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**
log files should be generated in logs dir

**Environment details**
0.10.1
default config files

**Screenshots**

**Additional context**

**Comment by scsven** [comment]
Not needed.
