### ISSUE TITLE
[Bug]: Proxy consumes too much CPU during high read payload with RBAC enabled

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#29113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master, 2.3.3-hotfix & 2.2.16
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Proxy consumes more CPU then expected when search/query request payload is high when RBAC is enabled

### Expected Behavior

Proxy shall consume tiny part of the CPU during the whole search/query process

**Comment by xiaofan-luan** [comment]
@SimFG 
is there any special reason why we want to initializing casbin each time?

**Comment by SimFG** [comment]
There is no special reason. I didn’t pay attention to this part at the time, thinking that the object was relatively small.

**Comment by xiaofan-luan** [comment]
> There is no special reason. I didn’t pay attention to this part at the time, thinking that the object was relatively small.

Sure, please help review on the PR once it's ready

**Comment by congqixia** [comment]
> @SimFG is there any special reason why we want to initializing casbin each time?

if I recall correctly, there was a concurrent issue about the casbin model since it's not thread-safe.

**Comment by SimFG** [comment]
@congqixia The last time it was caused by policy model
![image](https://github.com/milvus-io/milvus/assets/21985684/1b079abb-9151-4aa4-89c8-af75e4b3b5e9)
