### ISSUE TITLE
[Bug]: Bulkinsert may lose deletion data 

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#29122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2 
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1.  launch insert and delete requests to generate test data.
2. stop to write the collection 
3. create a backup with Milvus backup tool
4. restore the backup to a new cluster

We saw a loss of data occurs in step 3 and step 4,  backup data lost some delta logs and bulkinsert skipped some delta logs.

**Comment by jaime0815** [comment]
Strictly speaking, we should disable auto compaction before starting the backup,  it also might lead to inconsistent data between the backup data and the original data.

**Comment by wayblink** [comment]
cc @zhuwenxing Let‘s make a case to verify this.

**Comment by wayblink** [comment]
https://github.com/zilliztech/milvus-backup/pull/257 one catch and fix

**Comment by jaime0815** [comment]
https://github.com/milvus-io/milvus/issues/29162

**Comment by xiaofan-luan** [comment]
so this might due to the loss of delta log while flush all right?

**Comment by yanliang567** [comment]
I think we have verified the fix. @jaime0815 please help to double confirm
