### ISSUE TITLE
[Bug]:  Data Preview with DISKANN in Attu doesn't work after segments are flushed.

### ISSUE THREAD

**Issue by naty88** [milvus-io/milvus#29120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.14
- Attu version: v2.3.1 --> v2.3.3 (the same problem).
- Deployment mode (standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): kafka
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.13
- OS(Ubuntu or CentOS): Ubuntu
```

### Current Behavior

Data preview after Segments are flushed is not possible anymore.

**Error:**
`fail to search on all shard leaders, err=All attempts results: attempt #1:code: UnexpectedError, error: fail to Search, QueryNode ID=6, reason=Search 6 failed, reason [UnexpectedError] Error in void knowhere::{anonymous}::CheckNumericParamAndSet(const Config&, const string&, std::optional<_Tp>, std::optional<_Tp>, T&) [with T = unsigned int; knowhere::Config = nlohmann::basic_json<>; std::string = std::__cxx11::basic_string<char>] at IndexDiskANNConfig.cpp:142: Param 'search_list_size'(20) is not in range [100, 4294967295] err %!w(<nil>) attempt #2:context canceled`

![Screenshot from 2023-12-11 11-40-45](https://github.com/milvus-io/milvus/assets/44298164/5667b6a3-8178-4b8e-9c41-46dd66517f66)

### Expected Behavior

Data preview is possible at any time as long as a collection exists. 

### Steps To Reproduce

```markdown
1. Create collection with DISKANN index Type for embeddings. 
2. Check "Data Preview" --> it should work
3. Wait for the firs data flashing.
4. Check "Data Preview" again --> Error.
```

### Milvus Log

[attu.log](https://github.com/milvus-io/milvus/files/13634318/attu.log)

**Comment by naty88** [comment]
Should I post it here: https://github.com/zilliztech/attu/issues?

**Comment by shanghaikid** [comment]
I don't think it is attu's problem.  

` Param 'search_list_size'(20) is not in range [100, 4294967295]` @yanliang567  what does this mean?

**Comment by yanliang567** [comment]
search_list is a search param for diskann index, if Attu does not specify it, I think the issue is in milvus or knowhere.
/assign @xige-16 
could you please help to take a look?
/unassign @shanghaikid

**Comment by naty88** [comment]
> yeah, attu set the `search_list`. I will fix it in the soon.
So that's attu problem, isn't it?

**Comment by shanghaikid** [comment]
> > yeah, attu set the `search_list`. I will fix it in the soon.
> > So that's attu problem, isn't it?

yeah.

**Comment by shanghaikid** [comment]
The issue has been fixed in https://github.com/zilliztech/attu/releases/tag/v2.3.5
