### ISSUE TITLE
[Enhancement]: Disable partition name as reg exp feature by default

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#29177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Add a config item for partition name as regexp feature and disable it by default

### Why is this needed?

Partition name as regexp is a legacy feature from 1.x
Actually this behavior will have performance impact when partition number is big
So add a config for it and set to disabled by default

**Comment by xiaofan-luan** [comment]
Running regular expression on each search is definitely not a good idea

**Comment by xiaofan-luan** [comment]
fixed and close it for now
