### ISSUE TITLE
[Bug]: Panic (negative WaitGroup counter) If DataNode.StartWatchChannels call multi times.

### ISSUE THREAD

**Issue by chyezh** [milvus-io/milvus#29170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-02621e131cd4e6868234d21281d0f077134df137
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): MacOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Panic when datanode shutdown.

### Expected Behavior

no panic should be produced.

### Steps To Reproduce

```markdown
1. Start a Milvus, break the etcd or etcd client down.
2. Stop the Milvus.
```

### Milvus Log

panic: sync: negative WaitGroup counter

goroutine 413971 [running]:
panic({0x107e36f00?, 0x1085b1048?})
        /opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/panic.go:1017 +0x3cc fp=0x1403227db20 sp=0x1403227da70 pc=0x104f0e04c
sync.(*WaitGroup).Add(0x1403227db88?, 0x14042b37240?)
        /opt/homebrew/Cellar/go/1.21.5/libexec/src/sync/waitgroup.go:62 +0x108 fp=0x1403227db50 sp=0x1403227db20 pc=0x104f6b9d8
sync.(*WaitGroup).Done(0x108438c40?)
        /opt/homebrew/Cellar/go/1.21.5/libexec/src/sync/waitgroup.go:87 +0x20 fp=0x1403227db70 sp=0x1403227db50 pc=0x104f6ba20
github.com/milvus-io/milvus/internal/datanode.(*DataNode).StartWatchChannels.func1()
        /Users/zilliz/repo/github/chyezh/milvus/internal/datanode/event_manager.go:43 +0x28 fp=0x1403227db90 sp=0x1403227db70 pc=0x107044b68
github.com/milvus-io/milvus/internal/datanode.(*DataNode).StartWatchChannels(0x14001043860, {0x1085ee060?, 0x1400061d680})
        /Users/zilliz/repo/github/chyezh/milvus/internal/datanode/event_manager.go:54 +0x310 fp=0x1403227dfa0 sp=0x1403227db90 pc=0x107044560
github.com/milvus-io/milvus/internal/datanode.(*DataNode).StartWatchChannels.func2()
        /Users/zilliz/repo/github/chyezh/milvus/internal/datanode/event_manager.go:64 +0x30 fp=0x1403227dfd0 sp=0x1403227dfa0 pc=0x107044b00
runtime.goexit()
        /opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x1403227dfd0 sp=0x1403227dfd0 pc=0x104f48c84
created by github.com/milvus-io/milvus/internal/datanode.(*DataNode).StartWatchChannels in goroutine 634
        /Users/zilliz/repo/github/chyezh/milvus/internal/datanode/event_manager.go:64 +0x73c

**Comment by chyezh** [comment]
StartWatchChannels do not wrap the stopWaiter up.

<img width="763" alt="image" src="https://github.com/milvus-io/milvus/assets/20332315/fbe67de1-799f-4351-a7d8-91373103179a">

**Comment by xiaofan-luan** [comment]
keep it
