### ISSUE TITLE
[Bug]: Milvus pod restarted for 10 times when trying to create 10k collections

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#29179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3-20231213-78865c02-amd64
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):
```

### Current Behavior

1. Milvus pod restarted for 10 times
2. Milvus became more and more slow, insert(125_768d) latency increased from 0.2s to 80s
```
12/14/2023 00:58:55 AM - INFO - multi_c_9351 insert 0 costs 82.066
12/14/2023 00:59:17 AM - INFO - collection entities: 125
```

### Expected Behavior

1. Milvus no restarts
2. Milvus insert latency keeps fast and stable

### Steps To Reproduce

```markdown
1. Deploy a milvus standalone with 2c8g
2. create a collection and insert 125_768d data into it, no index built, not load
3. repeat step2 for 10k times
```

### Milvus Log

pod names in 4am:
```
yanliang-2c8g-etcd-0                                              1/1     Running            0                 22h     10.x.x.xx    4am-node38   <none>           <none>
yanliang-2c8g-milvus-standalone-77d8767f74-r9jt7                  1/1     Running            10 (42m ago)      22h     10.x.x.xxx   4am-node20   <none>           <none>
yanliang-2c8g-minio-5b5cbf7d49-8kv27                              1/1     Running            0                 22h     10.x.x.xx   4am-node38   <none>           <none>
```

### Anything else?

CPU, Memory and Goroutines keep increasing during creation
![image](https://github.com/milvus-io/milvus/assets/82361606/98d1f38c-e4cd-44da-bcca-9a1a7fe6df99)

**Comment by MrPresent-Han** [comment]
after this pr merged, try this test again,
https://github.com/milvus-io/milvus/pull/29563
it's expected that the cpu load should be reduced significantly
