### ISSUE TITLE
[Bug]: Miss the grant info when using the SelectGrant api with the default db

### ISSUE THREAD

**Issue by SimFG** [milvus-io/milvus#29172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
connections.connect("default",
                    uri="http://localhost:19530",
                    token="root:Milvus")

r = Role("public")
print(r.list_grants())
print(r.list_grants(db_name="*"))

print(r.list_grant(object="Collection", object_name="*"))
print(r.list_grant(object="Collection", object_name="*", db_name="*"))
```

![image](https://github.com/milvus-io/milvus/assets/21985684/c3049a50-4af6-4a76-96c1-0adada49b0d1)

### Expected Behavior

![image](https://github.com/milvus-io/milvus/assets/21985684/936206b3-6513-4b10-b20c-8a2930d7fae1)

**Comment by PowderLi** [comment]
For example, role1 has such privileges
|no|db_name|<objectType, object, action>|
|--|--|--|
|1|*|<Global, *, CreateCollection|
|2|default|<Collection, *, Load>
|3|test|<Collection, *, Insert>

review the result of list_grants(db_name=?)

|db_name|history|now|expected|
|--|--|--|--|
|*|1|1|1,2,3|
|default|2|1,2|1,2|
|test|3|1,3|1,3|
the number corresponds to the privilege in the above table
list_grants(db_name=*) only return No.1 privilege: <Global, *, CreateCollection
