### ISSUE TITLE
[Bug]: Wrong datanode flowgraph buffer size metrics

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#29229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.15
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. v2.2.15 milvus
2. concurrent insert + delete + flush + search
3. datanode flowgraph buffer size metrics
![img_v3_0265_1dd6eb05-965f-4d3e-b370-e3fb7f4f256g](https://github.com/milvus-io/milvus/assets/27288593/8ff60cd4-4c54-462d-9c7f-2c20531d370e)

- https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=qa-milvus&var-instance=yanliang-est-128cu&var-collection=All&var-app_name=milvus&from=1702567818064&to=1702610758719

**Comment by xiaofan-luan** [comment]
do we have similar issue in 2.3 or master?

We probably don't want to fix any issues in 2.2 branch.

All the test should also be on 2.3 branch I guess
