### ISSUE TITLE
[Feature]: Support upsert in autoincrement collections

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#29258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Currently, milvus didn't support to upsert on collections with auto increment PK.
However, it seems to very reasonable to delete old primary key and reinsert with the same PK.

This could keep milvus API consistent and avoid misunderstanding.

**Comment by yanliang567** [comment]
working on it
/assign

filed one issue: #34668

**Comment by yanliang567** [comment]
tests added in e2e.
