### ISSUE TITLE
[Bug]: Milvus crash when loading ivf-flat index

### ISSUE THREAD

**Issue by MrPresent-Han** [milvus-io/milvus#29263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-latest
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

when trying to run workflow, it inserted  data, build index, load and  crash

### Expected Behavior

argo flow: test-delete-stable-partition-key-hanchun-1215-3-n49p5
namespace: qa-milvus
instance-name: delta-par-key3

**Comment by MrPresent-Han** [comment]
![img_v3_0268_cf57f786-ded1-407b-9458-3c2f51fe3f0g](https://github.com/milvus-io/milvus/assets/116052805/8cc1938f-cf24-4a8e-9e6c-ecf05afef8f0)

**Comment by MrPresent-Han** [comment]
logfile:
[querynode_1218.log](https://github.com/milvus-io/milvus/files/13699008/querynode_1218.log)

**Comment by yhmo** [comment]
@MrPresent-Han 
Some questions:
- how many entities in the collection?
- what value of the vector dimension?
- did you use partition_key? how many partitions in the collection?

**Comment by yanliang567** [comment]
any updates?

**Comment by yanliang567** [comment]
keep it active
