### ISSUE TITLE
[Bug]: Optimize the reading and parsing logic of Azure Parquet to reduce memory usage.

### ISSUE THREAD

**Issue by lentitude2tk** [milvus-io/milvus#29292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master、2.3
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS):
- CPU/Memory: 
- GPU:
- Others:
```

### Current Behavior

From the code, it can be observed that the current file reading process for Azure Parquet involves loading the entire file into memory for reading, unlike other clouds that are capable of parsing and processing in batches. This leads to a significant and uncontrollable increase in memory consumption（The current kernel has a default limit of 16GB for the batch size of data, specifically for Numpy and JSON.）. Particularly for instances with lower specifications or limited available memory, this approach poses a risk of Out of Memory (OOM) issues.

https://github.com/milvus-io/milvus/blob/2d33c7fe417a775d26598d2d278f513df5aced11/internal/storage/file.go#L105
```

func NewAzureFile(body io.ReadCloser) *AzureFile {
	data, err := io.ReadAll(body)
	defer body.Close()
	if err != nil && err != io.EOF {
		log.Warn("create azure file failed, read data failed", zap.Error(err))
		return &AzureFile{
			NewMemoryFile(nil),
		}
	}

	return &AzureFile{
		NewMemoryFile(data),
	}
}
```

### Expected Behavior

The expectation is that file reading in Azure Parquet can be performed similarly to other clouds supported by Minio (AWS, GCP), enabling the ability to read and parse in batches directly from disk, thus avoiding the need to load the entire dataset into memory at once.

### Steps To Reproduce

```markdown
1. For bulk insert operations on large Parquet files (e.g., 10GB), check the memory usage.
```

**Comment by lentitude2tk** [comment]
Locally read and parse a 1GB Parquet file, containing 1GB of data with 128 dimensions and 1.53 million rows. During the parsing process, memory usage can reach up to 3.8GB.

![image](https://github.com/milvus-io/milvus/assets/108672767/fa44649f-c209-44d1-8bed-da7f977ebb02)

**Comment by xiaofan-luan** [comment]
/assign @xiaocai2333 

make sense to me.

We can not read the entire file for bulkinsertion, it takes too much memory?

**Comment by xiaofan-luan** [comment]
@lentitude2tk 
good catch! do we have similar behaviour on other cloud storage?

**Comment by lentitude2tk** [comment]
> /assign @xiaocai2333
> 
> make sense to me.
> 
> We can not read the entire file for bulkinsertion, it takes too much memory?

Yes, the expected scenario is to load the file into memory either line by line or in batches, rather than reading the entire file into memory at once.

**Comment by lentitude2tk** [comment]
> @lentitude2tk good catch! do we have similar behaviour on other cloud storage?

From the code, it appears that other cloud storage services directly interface with Minio, using a strategy of loading into memory in batches, thus avoiding this issue. 

However, this situation has already been communicated to the relevant personnel @zhuwenxing for performance-related testing, covering scenarios of 1GB, 10GB, and 15GB. We can assess whether the service meets expectations based on the test results.

**Comment by zhuwenxing** [comment]
Minio seems to also have this issue.

file size 1GB
```
[2023-12-19 11:33:09 - INFO - ci_test]: {446309949809239523: <Bulk insert state:
    - taskID          : 446309949809239523,
    - state           : Completed,
    - row_count       : 310000,
    - infos           : {'files': 'data-fields-9-rows-310000-dim-128-file-num-1-error-none-1702956574.parquet', 'collection': 'bulk_insert_Xd1w0g1f', 'partition': '_default', 'failed_reason': '', 'progress_percent': '100', 'persist_cost': '53.57'},
    - id_ranges       : [446309949809348108, 446309949809355036],
    - create_ts       : 2023-12-19 11:32:14
>} (utility_wrapper.py:150)
[2023-12-19 11:33:09 - INFO - ci_test]: wait for bulk load tasks completed successfully, cost time: 54.80706596374512 (utility_wrapper.py:152)
[2023-12-19 11:33:09 - INFO - ci_test]: bulk insert state:True in 55.874608755111694 with states:{446309949809239523: <Bulk insert state:
    - taskID          : 446309949809239523,
    - state           : Completed,
    - row_count       : 310000,
    - infos           : {'files': 'data-fields-9-rows-310000-dim-128-file-num-1-error-none-1702956574.parquet', 'collection': 'bulk_insert_Xd1w0g1f', 'partition': '_default', 'failed_reason': '', 'progress_percent': '100', 'persist_cost': '53.57'},
    - id_ranges       : [446309949809348108, 446309949809355036],
    - create_ts       : 2023-12-19 11:32:14
>} (test_bulk_insert_benchmark.py:122)

```

during bulk insert, the memory reached a very high peak.
![image](https://github.com/milvus-io/milvus/assets/12268675/ea18a6bc-fffb-49d6-8cb8-e9f63869560b)

**Comment by xiaocai2333** [comment]
fixed, please verify.
/assign @lentitude2tk

**Comment by lentitude2tk** [comment]
> fixed, please verify. /assign @lentitude2tk
From my point of view, it has passed without any problem. @zhuwenxing also help to confirm

**Comment by zhuwenxing** [comment]
![image](https://github.com/milvus-io/milvus/assets/12268675/a7bfc1cc-6cf8-4955-8bc0-c153855e5c75)

![image](https://github.com/milvus-io/milvus/assets/12268675/110fc5d8-428b-4234-b59a-25103ae0eeef)
