### ISSUE TITLE
[Bug]: [benchmark]Concurrency test 5h milvus crash and reboot over 40 times

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#29319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20231218-95ada1b6
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.3
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Continuous concurrent upsert, search, query, load after inserting 1m data, milvus restarted 44 times 

case_params:
fouramf-client-upsert-compact
case_name:
test_concurrent_locust_hnsw_dml_dql_filter_standalone
argo task : new-stable-master-1702922400 , id : 7 

client pod : new-stable-master-1702922400-2907953617
client error log:
![image](https://github.com/milvus-io/milvus/assets/48523564/e3d74145-f76c-498f-bfa8-8b47aff6f61b)

server:
```
new-stable-mast22400-7-37-6055-etcd-0                             1/1     Running            0                2m42s   10.104.9.64     4am-node14   <none>           <none>
new-stable-mast22400-7-37-6055-milvus-standalone-6c8f457bd7pqwb   1/1     Running            0                2m42s   10.104.29.47    4am-node35   <none>           <none>
new-stable-mast22400-7-37-6055-minio-7d56f9c65-2h2s2              1/1     Running            0                2m42s   10.104.9.63     4am-node14   <none>           <none> (base.py:218)
[2023-12-18 23:08:32,254 -  INFO - fouram]: [Cmd Exe]  kubectl get pods  -n qa-milvus  -o wide | grep -E 'STATUS|new-stable-mast22400-7-37-6055-milvus|new-stable-mast22400-7-37-6055-minio|new-stable-mast22400-7-37-6055-etcd|new-stable-mast22400-7-37-6055-pulsar|new-stable-mast22400-7-37-6055-kafka'  (util_cmd.py:14)
[2023-12-18 23:08:41,810 -  INFO - fouram]: [CliClient] pod details of release(new-stable-mast22400-7-37-6055): 
 I1218 23:08:33.501707     467 request.go:665] Waited for 1.16486353s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/apis/apiregistration.k8s.io/v1?timeout=32s
NAME                                                              READY   STATUS             RESTARTS         AGE     IP              NODE         NOMINATED NODE   READINESS GATES
new-stable-mast22400-7-37-6055-etcd-0                             1/1     Running            0                5h6m    10.104.9.64     4am-node14   <none>           <none>
new-stable-mast22400-7-37-6055-milvus-standalone-6c8f457bd7pqwb   1/1     Running            44 (7m23s ago)   5h6m    10.104.29.47    4am-node35   <none>           <none>
new-stable-mast22400-7-37-6055-minio-7d56f9c65-2h2s2              1/1     Running            0                5h6m    10.104.9.63     4am-node14   <none>           <none> (cli_client.py:132)
```

OOM has occurred :
prometheus `kube_pod_container_status_last_terminated_reason{namespace="qa-milvus",pod=~"new-stable-mast22400-7-37-6055-milvus-standalone-6c8f457bd7pqwb"}`
![image](https://github.com/milvus-io/milvus/assets/48523564/dd9acb38-7e9d-4477-bf92-d07088701d6c)

memory usage:
![image](https://github.com/milvus-io/milvus/assets/48523564/e84ec691-8380-4b6e-8f1a-5342c9bd1901)

 

### Expected Behavior

There shouldn't be search failures and milvus reboots.

### Steps To Reproduce

```markdown
1. create a collection  
  2. build HNSW index  
  3. insert 1 million vectors
  4. flush collection
  5. build index on vector column with the same parameters  
  6. count the total number of rows
  7. load collection
  8. execute concurrent upsert、search、 query、load  
  9. step 8 lasts 5h
```

### Anything else?

test env: 4am cluster , qa-milvus  namespace

**Comment by elstic** [comment]
I think there was a memory leak, after cranking up the resources the memory went up to over 50g in 20 minutes. 
![image](https://github.com/milvus-io/milvus/assets/48523564/dbf282da-7d64-41ff-b9c3-27aa4aead5c4)

**Comment by elstic** [comment]
This issue does not appear in images from December 17th and before

**Comment by elstic** [comment]
### milvus appears OOM in more scenarios  

OOM for concurrent range search, query, ,load,insert,delete,flush scenarios

deploy_config:
fouramf-server-standalone-8c16m
case_params:
fouramf-client-scann-comapct
case_name:
test_concurrent_locust_custom_parameters

server:
```
new-stable-mast81600-2-90-9969-etcd-0                             1/1     Running            0               2m16s   10.104.34.35    4am-node37   <none>           <none>
new-stable-mast81600-2-90-9969-milvus-standalone-865489b587hf6t   1/1     Running            0               2m16s   10.104.30.231   4am-node38   <none>           <none>
new-stable-mast81600-2-90-9969-minio-7bd45dd6f5-2vgg4             1/1     Running            0               2m16s   10.104.30.229   4am-node38   <none>           <none> (base.py:218)
[2023-12-21 22:05:47,775 -  INFO - fouram]: [Cmd Exe]  kubectl get pods  -n qa-milvus  -o wide | grep -E 'STATUS|new-stable-mast81600-2-90-9969-milvus|new-stable-mast81600-2-90-9969-minio|new-stable-mast81600-2-90-9969-etcd|new-stable-mast81600-2-90-9969-pulsar|new-stable-mast81600-2-90-9969-kafka'  (util_cmd.py:14)
[2023-12-21 22:05:57,240 -  INFO - fouram]: [CliClient] pod details of release(new-stable-mast81600-2-90-9969): 
 I1221 22:05:49.019984     562 request.go:665] Waited for 1.178103207s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/apis/batch/v1beta1?timeout=32s
NAME                                                              READY   STATUS                   RESTARTS         AGE     IP              NODE         NOMINATED NODE   READINESS GATES
new-stable-mast81600-2-90-9969-etcd-0                             1/1     Running                  0                4h3m    10.104.34.35    4am-node37   <none>           <none>
new-stable-mast81600-2-90-9969-milvus-standalone-865489b587hf6t   1/1     Running                  3 (47m ago)      4h3m    10.104.30.231   4am-node38   <none>           <none>
new-stable-mast81600-2-90-9969-minio-7bd45dd6f5-2vgg4             1/1     Running                  0                4h3m    10.104.30.229   4am-node38   <none>           <none> (cli_client.py:132)

```

![image](https://github.com/milvus-io/milvus/assets/48523564/e6e394a6-543f-4ebf-b3dc-fcd1d1f88af5)

memory usage:
![image](https://github.com/milvus-io/milvus/assets/48523564/39a19a60-6b10-4578-b679-c7ddb23179ff)

**Comment by elstic** [comment]
@czs007  Any updates?

**Comment by zhagnlu** [comment]
Could you narrow down the range? oom when upset or search or query ,and the specify query mode

**Comment by zhagnlu** [comment]
test upsert, search, query separatey, memory shows:
query and search keep steady:
![image](https://github.com/milvus-io/milvus/assets/11935707/15c5ccda-5c48-47c6-a748-1582564d59e0)
but upsert. has a growing every recursive:
![image](https://github.com/milvus-io/milvus/assets/11935707/039a2300-3adf-407f-808f-39d8872ab0ce)
maybe exist memory leak

**Comment by xiaofan-luan** [comment]
could this becasue of compaction can not catch up?

**Comment by zhagnlu** [comment]
for newest master version, already exist error for this situation: search start, others upsert data, seach failed because inconsistent:
![image](https://github.com/milvus-io/milvus/assets/11935707/5e5ab447-3acc-42d6-9ce6-4d301b1f52d5)
just as figure shows

**Comment by elstic** [comment]
Search fails on upsert, please see if it's the same problem. @zhagnlu 

[Bug]: Fail to search/query when doing upsert for 2000 times  https://github.com/milvus-io/milvus/issues/29332

**Comment by elstic** [comment]
This issue has been fixed
Verification image:  master-20231231-5f00bad4-amd64
