### ISSUE TITLE
[Bug]: Unknown Cause of Crashed - Milvus Standalone

### ISSUE THREAD

**Issue by puja93** [milvus-io/milvus#29322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.3
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): -  
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.3
- OS(Ubuntu or CentOS): Debian GNU/Linux 11 (bullseye)
- CPU/Memory: 16vCPU/64GB
- GPU: -
- Others: 
    Total data 28 million records
    The instance also serves image enhancement fastapi
    The instance also serves elasticserver 1GB max memory
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/10529614/d388146a-f0bc-406b-81ac-08a3f71e2f8d)

### Milvus Log

[https://hjf3rx3aoy2.sg.larksuite.com/file/MrGSbEkqooMAp7xrNBQlX5cFgDf?from=from_copylink](url)

### Anything else?

Here is for mq config
![image](https://github.com/milvus-io/milvus/assets/10529614/2755260e-020d-4075-8b6a-08b9a873a1d2)

**Comment by xiaofan-luan** [comment]
/assign @MrPresent-Han 
could you please help on it

**Comment by yanliang567** [comment]
@puja93 I cannot open the link for the milvus logs, could you please double check the link?
/assign @puja93 
/unassign

**Comment by puja93** [comment]
@yanliang567, try this link for the log

https://drive.google.com/file/d/1Wj_LQgvYn4aMEhIGssvatQkFLbyNxH-k/view?usp=share_link

**Comment by MrPresent-Han** [comment]
@puja93 hello,
It seems that memory calculation of milvus query-node encounter some accidents, for the time-being, I recommend you to adjust such parameter values:
queryNode: 
   loadMemoryUsageFactor: 2
   
the larger this value is, the more conservative when milvus assessing the memory usage, so it can effectively avoid such accidents.

**Comment by xiaofan-luan** [comment]
> @puja93 hello, It seems that memory calculation of milvus query-node encounter some accidents, for the time-being, I recommend you to adjust such parameter values: queryNode: loadMemoryUsageFactor: 2
> 
> the larger this value is, the more conservative when milvus assessing the memory usage, so it can effectively avoid such accidents.

Then the load might fail right?
Usually this means we need more memory?

**Comment by puja93** [comment]
So @xiaofan-luan , should i or shouldn't i follow @MrPresent-Han  instruction?

**Comment by xiaofan-luan** [comment]
> So @xiaofan-luan , should i or shouldn't i follow @MrPresent-Han instruction?

Did you check the memory usage of your clsuter?
Have you deployed monitoring system?
