### ISSUE TITLE
[Bug]: [benchmark] Concurrent search with vector return fails

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#29321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20231218-95ada1b6 
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):   
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Concurrent search with vector return fails with error: "incomplete query result, missing id %!s(int64=27002)," 

argo task : new-stable-master-1702922400 , id : 5 
deploy_config:
fouramf-server-standalone-8c16m
case_params:
client-hnsw-search-output-vector

server:
```
new-stable-mast22400-5-82-2771-etcd-0                             1/1     Running            0                3m56s   10.104.9.62     4am-node14   <none>           <none>
new-stable-mast22400-5-82-2771-milvus-standalone-7444588d9z6hqg   1/1     Running            1 (114s ago)     3m57s   10.104.33.37    4am-node36   <none>           <none>
new-stable-mast22400-5-82-2771-minio-7bd49bd67d-4mh2f             1/1     Running            0                3m57s   10.104.9.59     4am-node14   <none>           <none> (base.py:218)
```

client pod : new-stable-master-1702922400-3766535951 
client error log :
![image](https://github.com/milvus-io/milvus/assets/48523564/a6d3bdd7-6374-4e99-94bc-6954319fcb7b)

search param:
```
	params:
	  nq: 10
	  top_k: 10
	  search_param:
	    ef: 16
	  expr:
	    float_1:
	      GT: -1
	      LT: 500000
```

### Expected Behavior

no search failures

### Steps To Reproduce

```markdown
1. create a collection 
  2. build an HNSW index on the vector column
  3. insert 1 million vectors
  4. flush collection
  5. build index on vector column with the same parameters  
  6. count the total number of rows
  7. load collection
  8. concurrently searches and returns the vector field
  9. step 8 lasts 5h
```

**Comment by yah01** [comment]
search with output vector:
1. search the primary keys
2. proxy submits a query request to retrieve vectors

the step 2 failed as the query results contain no data

**Comment by yah01** [comment]
#29394 is fixing this

**Comment by xiaofan-luan** [comment]
why #29394 could solve this problem?

**Comment by xiaofan-luan** [comment]
Thought 29394 is more like an acceleration

**Comment by xiaofan-luan** [comment]
should we hold the segment in memory before we retrieve?

**Comment by yah01** [comment]
> should we hold the segment in memory before we retrieve?

in this case the segment had not been released, also this may be in risk if the request timeout after the search done but requery not submitted to QueryNode

**Comment by xiaofan-luan** [comment]
> > should we hold the segment in memory before we retrieve?
> 
> in this case the segment had not been released, also this may be in risk if the request timeout after the search done but requery not submitted to QueryNode

we can pin the segment for the last req timeout?

or we should simply refresh segemnt location and send the request to the new location

**Comment by yah01** [comment]
> > > should we hold the segment in memory before we retrieve?
> > 
> > 
> > in this case the segment had not been released, also this may be in risk if the request timeout after the search done but requery not submitted to QueryNode
> 
> we can pin the segment for the last req timeout?
> 
> or we should simply refresh segemnt location and send the request to the new location

requery would be sent to the new location if the segment has been balanced (as what query does), also it only remembers the primary keys, not segment ids.

But it need to set travel timestamp, what is missed now

**Comment by elstic** [comment]
This issue has been fixed
Verification image: master-20231231-5f00bad4-amd64
