### ISSUE TITLE
log file path/name can be specified based on environment variable

### ISSUE THREAD

**Issue by sunyaofei** [milvus-io/milvus#2934]
**Please state you issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**
in k8s, multi pod will share the same file name causing file override

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by scsven** [comment]
@sunyaofei What kind of solution would you like? Add some field in log filename likes <hostname>, <pid> or other ?

**Comment by sunyaofei** [comment]
> @sunyaofei What kind of solution would you like? Add some field in log filename likes hostname, pid or other ?

for example: 
i write log file path in config file as /home/log/${var1}/${var2}/xx.log,  and i set environment variable var1=xxx, var=yyy，finally the log will be write in file /home/log/xxx/yyy/xx.log

**Comment by JinHai-CN** [comment]
Connected to #2587
