### ISSUE TITLE
[Bug]: go 1.19 can not build milvus because 1.19 not support sync/atomic atomic.Int64

### ISSUE THREAD

**Issue by aoiasd** [milvus-io/milvus#29376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

We use atomic.Int64 in sync/atomic but go before v1.20 not support this struct.

### Expected Behavior

Should use  atomic.Int64 in go.uber.org/atomic

**Comment by xiaofan-luan** [comment]
@aoiasd 
maybe we should upgrade milvus to go 1.20 in milvus 2.4?

**Comment by aoiasd** [comment]
> @aoiasd maybe we should upgrade milvus to go 1.20 in milvus 2.4?

Master branch has update go version to 1.20, but 2.3 branch still use 1.18.
