### ISSUE TITLE
The result of list_partitions should be an instance of list, with strings in it

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#2937]
**Please state you issue using the following template and, most importantly, in English.**

**Describe the bug**
```
______________________________________________________________________________________________ TestShowBase.test_show_multi_partitions _________________________________________________________________________________________________

self = <test_partition.TestShowBase object at 0x7fbc3fe082e8>, connect = <milvus.client.stub.Milvus object at 0x7fbc3fef5b00>, collection = 'partition_vttAoKkZ'

    def test_show_multi_partitions(self, connect, collection):
        '''
        target: test show partitions, check status and partitions returned
        method: create partitions first, then call function: list_partitions
        expected: status ok, partitions correct
        '''
        tag_new = gen_unique_str()
        connect.create_partition(collection, tag)
        connect.create_partition(collection, tag_new)
        res = connect.list_partitions(collection)
>       assert tag in res
E       AssertionError: assert '1970-01-01' in [(collection_name='partition_vttAoKkZ', tag='_default'), (collection_name='partition_vttAoKkZ', tag='1970-01-01'), (collection_name='partition_vttAoKkZ', tag='test_I7OYLaGg')]

```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by BossZou** [comment]
Fixed. Now the return value of 'list_partitions' is a instance of list.
