### ISSUE TITLE
[Enhancement]: Refine chunkRows config to save memory possibly

### ISSUE THREAD

**Issue by MrPresent-Han** [milvus-io/milvus#29388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Currently, the minimum chunk_rows is 1024, when inserted rows is much less than this number, a lot of memory is left empty. 

### Why is this needed?

There are several things to do:
1. change the minimum limit
2. maybe adapt this value to usage dynamically

**Comment by xiaofan-luan** [comment]
this is very important on support large amount of partitions/collections

If user concurrently write to multiple collections, each collections only inserted a few entities, 1024 chunk size become a big problem.

The design for chunk is more for memory locality I would believe chunk of 64 or 128 could be good enough
