### ISSUE TITLE
[Bug]: Get command will get wrong results in High level api

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#29395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20231221-f699be79
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.4
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Get command will get wrong results in High level api.
```
    @pytest.mark.tags(CaseLabel.L1)
    def test_high_level_get(self):
        default_dim = 2
        client = self._connect(enable_high_level_api=True)
        collection_name = cf.gen_unique_str(prefix)
        # 1. create collection
        client_w.create_collection(client, collection_name, default_dim, consistency_level="Strong")
        # 2. insert
        default_nb = 20000
        rng = np.random.default_rng(seed=19530)
        rows = [{default_primary_key_field_name: i, default_vector_field_name: list(rng.random((1, default_dim))[0]),
                 default_float_field_name: i * 1.0, default_string_field_name: str(i)} for i in range(default_nb)]
        pks = client_w.insert(client, collection_name, rows)[0]
        client_w.flush(client, collection_name)
        assert client_w.num_entities(client, collection_name)[0] == default_nb
        # 3. get first primary key
        first_pk_data = client_w.get(client, collection_name, [i for i in range(10)])[0]
        log.info(first_pk_data)
        log.info(len(first_pk_data))
```
get 10 ids, 20 entities were returned. (10000 data)
get 10 ids, 30 entities were returned. (20000 data)

### Expected Behavior

pass

**Comment by ThreadDao** [comment]
By the way, go-sdk 2.2.8 call high-level API `NewCollection`, the collection index name is changed from `_default_idx_101` to $field_name. There should be no potential incompatibility risk ？

**Comment by yanliang567** [comment]
> By the way, go-sdk 2.2.8 call high-level API `NewCollection`, the collection index name is changed from `_default_idx_101` to $field_name. There should be no potential incompatibility risk ？

this is a milvus server side change, as long as sdk does not specify the index_name in sdk code when trying to describe/get the index info, this is expected
