### ISSUE TITLE
[Bug]:  S3 Insert Entities from Files always cannot find file

### ISSUE THREAD

**Issue by Ice-YcY** [milvus-io/milvus#29397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.3.1
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I want to insert entities into a collection by using the insert function with files. In my cluster, I am utilizing S3 as the storage, and the  rootPath is set as "/example." I have uploaded the npy file to the directory "/example/test/," and the file paths I am passing to the do_bulk_insert() function include '/example/test/xx.npy', 'test/xx.npy,' and '/test/xx.npy' but all failed.

```
Failed reason: failed to get file size of 'test/doc_id.npy', error: The specified key does not exist.
Failed reason: failed to get file size of '/test/doc_id.npy', error: The specified key does not exist.
Failed reason: failed to get file size of '/example/test/doc_id.npy', error: The specified key does not exist.
```
I am unsure which file path I should provide for the bulk insert operation.

### Expected Behavior

Insert entities successfully

### Steps To Reproduce

```markdown
Using utility.do_bulk_insert to insert entities and the Cluster storage is S3
```

### Milvus Log

```
Failed reason: failed to get file size of 'test/doc_id.npy', error: The specified key does not exist.
Failed reason: failed to get file size of '/test/doc_id.npy', error: The specified key does not exist.
Failed reason: failed to get file size of '/example/test/doc_id.npy', error: The specified key does not exist.
```

**Comment by xiaofan-luan** [comment]
did you check your S3 or minio do has this file in the bucket?

**Comment by xiaofan-luan** [comment]
seems that /example/test/doc_id.npy don't have this file

**Comment by Ice-YcY** [comment]
> did you check your S3 or minio do has this file in the bucket?

Yes, I checked, it exists on s3.

**Comment by xiaofan-luan** [comment]
> > did you check your S3 or minio do has this file in the bucket?
> 
> Yes, I checked, it exists on s3.

Then this must be a config issue right.
Did you enable log storage on your cluster?

Seems that your cluster is trying to access local disk but not a S3 bucket
