### ISSUE TITLE
[Enhancement]: Improve the MTTR and rolling upgrade 

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#29409]
Coordinator Init Optimization @yiwangdr -> Reduce Coordinator recovery time to 30 seconds (Deadline: Jan. 30)

Coordinator Master-Slave Switch Detection Time @jaime0815 -> Shorten Session Timeout Period (Deadline: Jan. 1)

Remove Unnecessary Coordinator Dependencies, Ensure Query Availability when Coordinator is Unserviceable @czs007 (Deadline: Jan. 30)

Segment Loading Speed Optimization - Can 64GB Memory Achieve 1-minute Load Completion? (Deadline: Jan.30) @liliu-z @xige-16

Streaming Data Split Log Optimization (Deadline: Jan.30)  @congqixia

Rolling Upgrade Process Refinement (Deadline: Jan. 16) @weiliu1031 @LoveEachDay

Multi-Replica Availability Report (Deadline: Jan. 30) @weiliu1031

Ensure Search Availability when Partial Data is Available (Deadline: Jan 30) @xige-16

Implement a GUI for Better Visibility of Cluster State (Deadline: Jan 16) @jaime0815

Cpp Monitoring and Logging (Deadline: Jan 16) @liliu-z

**Comment by xiaofan-luan** [comment]
MTTR is one of the most import goal of Milvus 2.4.
Let's move team!

**Comment by congqixia** [comment]
keep it
