### ISSUE TITLE
[Feature]: Add Sparse Float Vector support

### ISSUE THREAD

**Issue by zhengbuqian** [milvus-io/milvus#29419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Now milvus supports only dense vectors and lack the ability to store/index/search sparse vectors(vectors with up to million dimensions while only a handful of them are non zero). We wish to add sparse float vector support to Milvus so users can insert, index and search them with ease.

**Comment by zhengbuqian** [comment]
This comment is to track the implementation progress of sparse vector support in Milvus.

- Happy path of the general usage: 
	- [ ] Create a collection with a sparse vector type field
	- [ ] Insert sparse vectors into the collection and persist to binlog
	- [ ] Load sparse vectors from binlog for brute force search, segment compaction, etc
	- [ ] Build index to accelerate searching on sparse vector field with tunable recall/performance
	- [ ] The ability to perform index search
	- [ ] The ability to retrieve the original vectors(GetVectorByIds)
- Advanced features:
	- [ ] Add sparse vector support in import utils
	- [ ] Add sparse vector support in proxy/httpserver
	- [ ] Do we need sparse vector support in row based message?
	- [ ] How to estimate the byte size of a sparse float vector?
	- [ ] `internal/core/src/storage/Util.cpp and parquet_c.h` how is this used? How do we handle sparse?
	- [ ] Mmap support for sparse field data
	- [ ] Sealed segment to generate temp binlog index
- Testing TODOs
	- [ ] Fix/Add unit tests for all modified files in PR
	- [ ] End 2 End tests
- Advanced feature support:
	- [ ] Range search
	- [ ] GroupBy
	- [ ] ...

**Comment by zhengbuqian** [comment]
Knowhere tracking issue: https://github.com/zilliztech/knowhere/issues/193

**Comment by xiaofan-luan** [comment]
Exciting about the new feature!

**Comment by zhengbuqian** [comment]
I have added unit tests, splitted the impl code and created chain of PRs:

* [ ] #30357 
* [ ] #30629 
* [ ] #30630 

Each PR currently contains commits of previous PRs due to the limitation of GitHub but I'll rebase/merge them one by one.

**Comment by zhengbuqian** [comment]
basic sparse support has been added to master branch with the merge of #30357, #30629, #30630 and pymilvus [#1920](https://github.com/milvus-io/pymilvus/pull/1902).

**Comment by zhengbuqian** [comment]
For SDK owners:

We also need to support sparse float vector in C#/NodeJs/Java/Go SDK.

* PyMilvus PR for reference: https://github.com/milvus-io/pymilvus/pull/1902
* Python code example to use sparse float vector: https://github.com/milvus-io/pymilvus/blob/master/examples/hello_sparse.py
* Data representation in proto: https://github.com/milvus-io/milvus-proto/blob/5423fd39943c646c722a08617402f4a890e40e74/proto/schema.proto#L131

The accepted sparse input format:

* if your language community already has a widely used representation of sparse float vector, we should accept that. For example PyMilvus supports the [`scipy.sparse`](https://docs.scipy.org/doc/scipy/reference/sparse.html) representations as input.
* if not, support a map representation like `{30: 0.34, 78: 0.11, 22: 0.66}`.

When sending requests to milvus(both insert and search), use one proto `bytes` to represent a single sparse vector, and encode it as densely packed bytes: `idx, val, idx, val, ...`. Indices in the packed bytes should be in `uint32` range and **ordered in ascending order**(the user input can be unordered though). No duplicate indices allowed.

Thanks a lot for the efforts!
