### ISSUE TITLE
[Bug]:  Search by java sdk is ok while search by attu is timeout.

### ISSUE THREAD

**Issue by dzqoo** [milvus-io/milvus#29415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.14
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.14
- OS(Ubuntu or CentOS): 
- CPU/Memory: 32
- GPU: 
- Others:
```

### Current Behavior

When I  search by java sdk is ok while search by attu is timeout.
And I got following log in rootCoor:
[rootCoord.log](https://github.com/milvus-io/milvus/files/13747704/rootCoord.log)

**Comment by yanliang567** [comment]
/assign @shanghaikid 
sounds like an attu issue.
/unassign

**Comment by shanghaikid** [comment]
how do you search with java sdk?  can you show me the code？  
what is your index ?

**Comment by dzqoo** [comment]
> how do you search with java sdk? can you show me the code？ what is your index ?
    public static String search(MilvusServiceClient client,
                              String collectionName,
                              List<Float> vector) {

        String SEARCH_PARAM = "{\"ef\": 256}";
        SearchParam requestParam = SearchParam.newBuilder()
                .withCollectionName(collectionName)
                .withConsistencyLevel(ConsistencyLevelEnum.BOUNDED)
                .withTopK(100)
                .withMetricType(MetricType.IP)
                .withVectorFieldName("vector")
                .withVectors(Collections.singletonList(vector))
                .withOutFields(Arrays.asList("id", "quality", "status", "is_xgk"))
                .withParams(SEARCH_PARAM)
                //.withOutFields(Arrays.asList("feature_id", "feature_type", "feature_vector"))
                .build();
        R<SearchResults> search = client.search(requestParam);
        List<String> strId = new ArrayList<>(search.getData().getResults().getIds().getStrId().getDataList());
        SearchResultsWrapper searchResultsWrapper = new SearchResultsWrapper(search.getData().getResults());
        List<Map<String, Object>> collect = searchResultsWrapper.getRowRecords().stream().map(row -> row.getFieldValues()).collect(Collectors.toList());
        List<Map<String, Object>> collectNew = IntStream.range(0, strId.size())
                .mapToObj(index -> {
                    Map<String, Object> stringObjectMap = collect.get(index);
                    stringObjectMap.put("id", strId.get(index));
                    return stringObjectMap;
                }).collect(Collectors.toList());
        String json = JsonUtil.toJson(collectNew);
        return json;
    }

My index is HNSW.

**Comment by shanghaikid** [comment]
what is your attu version? 
how much data do you have in the collection?  
Maybe you can try the latest version of attu.

**Comment by dzqoo** [comment]
> what is your attu version? how much data do you have in the collection? Maybe you can try the latest version of attu.

2.3.0

**Comment by dzqoo** [comment]
We have searched in java under version2.2.7, and it is also stucked and search timeout...

**Comment by shanghaikid** [comment]
/assign @yanliang567 
sounds like an milvus issue.
/unassign

**Comment by yanliang567** [comment]
/assign @yhmo 
could you please take a look? it succeeds in search with java sdk 2.2.7 while stuck with java 2.2.15.

/unassign

**Comment by yhmo** [comment]
It is pretty simple for sdk to call the search interface: prepare the parameters, perform a RPC call and wait for the response.
I believe it is stuck on the server-side.

@dzqoo Could you provide the log of rootcoord/querycoord/querynode?

**Comment by dzqoo** [comment]
> It is pretty simple for sdk to call the search interface: prepare the parameters, perform a RPC call and wait for the response. I believe it is stuck on the server-side.
> 
> @dzqoo Could you provide the log of rootcoord/querycoord/querynode?

[rootcoord_querycoord.log](https://github.com/milvus-io/milvus/files/13776123/rootcoord_querycoord.log)
[querynode.hjmqd.log](https://github.com/milvus-io/milvus/files/13776205/querynode.hjmqd.log)
[querynode.n2w6d.log](https://github.com/milvus-io/milvus/files/13776209/querynode.n2w6d.log)
[querynode.4k92n.log](https://github.com/milvus-io/milvus/files/13776210/querynode.4k92n.log)

**Comment by dzqoo** [comment]
> > It is pretty simple for sdk to call the search interface: prepare the parameters, perform a RPC call and wait for the response. I believe it is stuck on the server-side.
> > @dzqoo Could you provide the log of rootcoord/querycoord/querynode?
> 
> [rootcoord_querycoord.log](https://github.com/milvus-io/milvus/files/13776123/rootcoord_querycoord.log) [querynode.hjmqd.log](https://github.com/milvus-io/milvus/files/13776205/querynode.hjmqd.log) [querynode.n2w6d.log](https://github.com/milvus-io/milvus/files/13776209/querynode.n2w6d.log) [querynode.4k92n.log](https://github.com/milvus-io/milvus/files/13776210/querynode.4k92n.log)

@yhmo Looking forwarding your reply~
