### ISSUE TITLE
[Bug]: [laion1b-test] The mixcoord failed to start after being oomkilled multiple times and increasing memory

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#29439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: cardinal-milvus-io-2.3-b69543c-20231222
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):     pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus .3.3
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. Based on the collection of 50+ million data, do search + query + insert_delete_flush concurrently
2. 1 querynode terminated due to SIGSEV error (known issue #29417), the mixcoord being oomkilled multiple times (issue #29296)
![image](https://github.com/milvus-io/milvus/assets/27288593/7d0dcfd6-de39-455b-b4f2-8f5a3062eccf)
3. increase mixcoord memory requests and limit, but mixcoord pod restated failed
```
laion1b-test-2-milvus-mixcoord-585d7d7cd4-lqhf2                   0/1     Running            13 (4m13s ago)   72m     10.104.4.213    4am-node11   <none>           <none>
```
[mix_lqhf2_2.log](https://github.com/milvus-io/milvus/files/13761070/mix_lqhf2_2.log)
[mix_lqhf2_3.log](https://github.com/milvus-io/milvus/files/13761071/mix_lqhf2_3.log)

### Expected Behavior

mixcoord starts successfully after increasing memory

### Steps To Reproduce

```markdown
argo: https://argo-workflows.zilliz.cc/archived-workflows/qa/3c919820-dd74-473f-b285-20f36a77a3ae
```

### Milvus Log

pods:
```
laion1b-test-2-milvus-datanode-567756cd8f-52r7w                   1/1     Running            0                46h     10.104.21.66    4am-node24   <none>           <none>
laion1b-test-2-milvus-datanode-567756cd8f-mmnrk                   1/1     Running            1 (46h ago)      46h     10.104.29.230   4am-node35   <none>           <none>
laion1b-test-2-milvus-indexnode-76c946c967-6c7px                  1/1     Running            0                46h     10.104.29.231   4am-node35   <none>           <none>
laion1b-test-2-milvus-indexnode-76c946c967-hcpw9                  1/1     Running            0                46h     10.104.12.21    4am-node17   <none>           <none>
laion1b-test-2-milvus-indexnode-76c946c967-hfch2                  1/1     Running            0                46h     10.104.34.146   4am-node37   <none>           <none>
laion1b-test-2-milvus-indexnode-76c946c967-m5hr9                  1/1     Running            0                46h     10.104.31.65    4am-node34   <none>           <none>
laion1b-test-2-milvus-indexnode-76c946c967-ph2wz                  1/1     Running            0                46h     10.104.15.219   4am-node20   <none>           <none>
laion1b-test-2-milvus-mixcoord-585d7d7cd4-lqhf2                   0/1     Running            13 (4m13s ago)   72m     10.104.4.213    4am-node11   <none>           <none>
laion1b-test-2-milvus-proxy-5c8df98f98-gv57m                      1/1     Running            0                46h     10.104.21.67    4am-node24   <none>           <none>
laion1b-test-2-milvus-proxy-5c8df98f98-jjdmh                      1/1     Running            1 (46h ago)      46h     10.104.32.95    4am-node39   <none>           <none>
laion1b-test-2-milvus-querynode-89866ddf4-56vdc                   1/1     Running            5 (40h ago)      46h     10.104.32.98    4am-node39   <none>           <none>
laion1b-test-2-milvus-querynode-89866ddf4-7jfg8                   1/1     Running            0                46h     10.104.1.92     4am-node10   <none>           <none>
laion1b-test-2-milvus-querynode-89866ddf4-bpf4j                   1/1     Running            0                46h     10.104.28.21    4am-node33   <none>           <none>
laion1b-test-2-milvus-querynode-89866ddf4-p7hgk                   1/1     Running            1 (5h9m ago)     46h     10.104.33.71    4am-node36   <none>           <none>
laion1b-test-2-milvus-querynode-89866ddf4-q57t7                   1/1     Running            1 (41h ago)      46h     10.104.20.83    4am-node22   <none>           <none>
laion1b-test-2-milvus-querynode-89866ddf4-w4kk2                   1/1     Running            0                46h     10.104.5.176    4am-node12   <none>           <none>
laion1b-test-2-milvus-querynode-89866ddf4-wvlzb                   1/1     Running            0                46h     10.104.9.3      4am-node14   <none>           <none>
laion1b-test-2-milvus-querynode-89866ddf4-xvtq6                   1/1     Running            0                46h     10.104.14.82    4am-node18   <none>           <none>
laion1b-test-2-milvus-querynode-89866ddf4-xzsmg                   1/1     Running            0                46h     10.104.18.244   4am-node25   <none>           <none>
laion1b-test-2-milvus-querynode-89866ddf4-zw9b8                   1/1     Running            0                46h     10.104.16.31    4am-node21   <none>           <none>
```

**Comment by chyezh** [comment]
mixcoord cannot startup recently at laion1b-test.
- MixCoord start at 14:22:02
![image](https://github.com/milvus-io/milvus/assets/20332315/8dd148c9-b782-4840-9319-c614e3246646)
- Rootcoord ready at 14:22:03
![image](https://github.com/milvus-io/milvus/assets/20332315/44b9b92e-defa-492b-aa02-73f57fc33509)
- Datacoord ready at 14:26:09
![image](https://github.com/milvus-io/milvus/assets/20332315/767a94dd-fdc7-4473-9cf9-3c91a06a2b45)
- But receive kill signal at 14:24:56
![image](https://github.com/milvus-io/milvus/assets/20332315/316f3474-9c5a-44d2-908f-229654add1d2)
- Datacoord cost about 4-5 minutes to restore meta info.
![image](https://github.com/milvus-io/milvus/assets/20332315/367be0e2-53d0-4915-9aa9-283be299e2e2)
<img width="1494" alt="image" src="https://github.com/milvus-io/milvus/assets/20332315/7cf5cf4b-78d7-4733-bf77-5a12d5a2a478">

**Comment by chyezh** [comment]
too much dropped segments, 151k.
<img width="114" alt="image" src="https://github.com/milvus-io/milvus/assets/20332315/c5672ca7-1712-4467-922a-7d4ddc176ac0">

**Comment by chyezh** [comment]
<img width="843" alt="image" src="https://github.com/milvus-io/milvus/assets/20332315/0551e09c-80de-428f-b022-17e6dfe06a95">
main memory cost at recovery

**Comment by chyezh** [comment]
256(partition)*2(shard) segment is generated when every flush operation is applied.
About 500 times flush is applied to cluster in an hour.
<img width="1575" alt="image" src="https://github.com/milvus-io/milvus/assets/20332315/f8afb1cf-5002-4a0f-bddd-dc2ac08e7210">

Generate 256*100=250k segments per hour.
GC operation is applied every hour.
There will be at least 250k small segments cannot be dropped.
Too much meta info of dropped segment in mixcoord.
Mixcoord memory usage increases as the dropped segment increases.

And at 9:46, a query delegator is down, huge operation is applied on mixcoord, causing the OOM. 
@ThreadDao  Can we use lower flush rate in these test?

**Comment by xiaofan-luan** [comment]
Seems to be a similar problem like @SimFG is solved

**Comment by xiaofan-luan** [comment]
related to #29296

**Comment by ThreadDao** [comment]
> Seems to be a similar problem like @SimFG is solved

This test image contains SimFG's fix commit

**Comment by xiaofan-luan** [comment]
> #29296

same as https://github.com/milvus-io/milvus/issues/29296, 
dropped segment generation speed is much faster than gc

**Comment by chyezh** [comment]
There's configuration at server side can prevent from generating too much segment by client force flush.
But it's disable now by default, should we enable it?

```
  flushRate:
    enabled: false
    max: -1 # qps, default no limit, rate for flush
```

**Comment by chyezh** [comment]
Add flush rate control: #29568

**Comment by ThreadDao** [comment]
mixcoord gets running after upgrade mixcoord deployment config `startupProbe.periodSeconds` from 10 to 60
