### ISSUE TITLE
[Bug]: Standalone pod restart with `Reason Error, Exit Code 137` 

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#29449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3-20231223-60a90463
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
NAME                                                     READY   STATUS    RESTARTS        AGE
cdc-test-upstream-11-milvus-standalone-fc9f7dbcf-sswdk   1/1     Running   1 (3h44m ago)   3h52m
```

### Anything else?

cluster: 4am
namespace: chaos-testing
release name: cdc-test-upstream-11
pod name: cdc-test-upstream-11-milvus-standalone-fc9f7dbcf-sswdk

**Comment by yanliang567** [comment]
@zhuwenxing is this issue reproduced with cdc?

**Comment by zhuwenxing** [comment]
> Is this issue reproduced with the CDC?
No, it's just a deployment issue.
The problem is that the pod will restart one time during the deployment stage.

**Comment by yanliang567** [comment]
please help to collection more log info if it reproduced @zhuwenxing 
/assign @zhuwenxing
