### ISSUE TITLE
[Enhancement]: refactor leader_observer to leader_checker

### ISSUE THREAD

**Issue by weiliu1031** [milvus-io/milvus#29453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

add leader_checker which generate load/release task to correct the leader view, instead of calling sync distribution by rpc

### Why is this needed?

sync distribution by rpc will also call loadSegment/releaseSegment, which may cause all kinds of concurrent case on same segment, such as concurrent load and release on one segment

**Comment by xiaofan-luan** [comment]
keep ti

**Comment by xiaofan-luan** [comment]
@weiliu1031 
I think we still need to refactor this part and make the leader check work
