### ISSUE TITLE
[Bug]:  requery failed when concurrent search with outfield

### ISSUE THREAD

**Issue by zhagnlu** [milvus-io/milvus#29467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

when concurrent do search with output, the second stage of search will requery milvus with specify pk . but at same time others maybe delete this pk, so this requery will failed because of inconsistent

### Expected Behavior

can travel this delete pk

### Steps To Reproduce

```markdown
1. create collection
2. insert data, create vector index
3. concurrent search collection with output in client.
```

**Comment by xiaofan-luan** [comment]
This is related to no mvcc.
So a deleted entity can not be retrieved.

**Comment by yanliang567** [comment]
@zhagnlu do you mean the requery request shall have the same tt with search request to make the output results consistent? and we did not do that for now?

**Comment by chasingegg** [comment]
The expected result should get these deleted result which are not deleted in the fist search ?
