### ISSUE TITLE
[Bug]: Problem with using the docker script from https://milvus.io/docs/install_standalone-docker.md

### ISSUE THREAD

**Issue by oppiet30** [milvus-io/milvus#29469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I download the script from https://milvus.io/docs/install_standalone-docker.md and I do docker compose up -d I get an error: 
[oppie@dell milvus-docker]$ docker compose up -d
[+] Running 4/4
 ✔ Network milvus               Created                                    0.4s
 ✔ Container milvus-minio       Created                                    1.0s
 ✔ Container milvus-etcd        Started                                    1.1s
 ✔ Container milvus-standalone  Created                                    1.0s
Error response from daemon: driver failed programming external connectivity on endpoint milvus-minio (a0dbc3a8f4bff2a97980daf487d08e010c2e3f856f4c42be2f242cde140bf4d6): Bind for 0.0.0.0:9001 failed: port is already allocated
 
I do ss -n -l -p -e | grep 9001 and I get:
tcp   LISTEN 0      4096                                                                              0.0.0.0:9001             0.0.0.0:*    ino:13218 sk:294 cgroup:/system.slice/docker.service <->

tcp   LISTEN 0      4096                                                                                 [::]:9001                [::]:*    ino:14769 sk:29c cgroup:/system.slice/docker.service v6only:1 <->

So should I change this line:
  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
----- 

Should I change the 9001:9001 to something else?

### Expected Behavior

When I do:
docker compose up -d
It should work

### Steps To Reproduce

```markdown
I am running docker-ce on fedora 39.
[oppie@dell milvus-docker]$ docker --version
Docker version 24.0.7, build afdd53b
[oppie@dell milvus-docker]$ sudo dnf list installed | grep docker
[sudo] password for oppie:
containerd.io.x86_64                                 1.6.26-3.1.fc39                     @docker-ce-stable
docker-buildx-plugin.x86_64                          0.11.2-1.fc39                       @docker-ce-stable
docker-ce.x86_64                                     3:24.0.7-1.fc39                     @docker-ce-stable
docker-ce-cli.x86_64                                 1:24.0.7-1.fc39                     @docker-ce-stable
docker-ce-rootless-extras.x86_64                     24.0.7-1.fc39                       @docker-ce-stable
docker-compose-plugin.x86_64                         2.21.0-1.fc39                       @docker-ce-stable
python3-docker.noarch                                6.1.3-1.fc39                        @fedora
```

**Comment by yanliang567** [comment]
/assign @wyfeng001 
please help to take look

/unassign

**Comment by User235514** [comment]
Same Question.

**Comment by xiaofan-luan** [comment]
> Same Question.

Port is allocated.
The easiest way is to find which process is actaully using this port and kill it to release this port.

Or you can change the port of minio and milvus to 9002 or any port you like
