### ISSUE TITLE
[Bug]: where is include_role_info？

### ISSUE THREAD

**Issue by jixianyihao** [milvus-io/milvus#29466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

[Bug]: where is include_role_info？

### Steps To Reproduce

```markdown
[Bug]: where is include_role_info？
```

**Comment by yanliang567** [comment]
@jixianyihao sorry, I don't understand the issue, could you please share more details about what you are looking for, and what is the actual results?
/assign @jixianyihao 
/unassign
