### ISSUE TITLE
[Bug]: existingClaim doesn't work with storageClass set as ""

### ISSUE THREAD

**Issue by maxgjt** [milvus-io/milvus#29475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

 I have created PV/PVC in  our k8s cluster, and we don't allow storageClass to automatically create pvc. Thus I want to set existingClaim in helm charts values.yaml, with storageClass set as "".  But data-xxxx-etcd-0 and other pvcs still automatically created。

**Comment by LoveEachDay** [comment]
Set storageClass to empty, kubernetes will use the default storageclass to automatically provision a pv/pvc.

**Comment by maxgjt** [comment]
> p

![image](https://github.com/milvus-io/milvus/assets/17487197/6f22d35b-9223-4f38-9046-83270d8f6d82)

then how  to set  the storageClass.   

“-” is aso illegal and error will occur in  statefulset.yaml in inner chart  folders.
