### ISSUE TITLE
[Bug]: Milvus displays 0% Is Loaded

### ISSUE THREAD

**Issue by stan5215** [milvus-io/milvus#29484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.3
- Deployment mode(standalone or cluster):Milvus Standalone with Docker Compose (CPU)
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):milvus-sdk-java 2.3.0
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 8/8GB
- GPU: no
- Others:
```

### Current Behavior

After upgrading to v2.3.x, I have been using it normally for two months. But after restarting the server, it suddenly prompts 0% Is Loaded, and then it can no longer run normally.

It happened once a month ago. I restored it through backup at that time, but now the backup also failed.

How do I fix it?

### Milvus Log

[milvus.log](https://github.com/milvus-io/milvus/files/13769631/milvus.log)
[backup.log](https://github.com/milvus-io/milvus/files/13769632/backup.log)

### Anything else?

The most related GitHub Discussions link
[28138](https://github.com/milvus-io/milvus/issues/28138)
[26754](https://github.com/milvus-io/milvus/issues/26754)
I tried the solution in issues, but it didn't work.

docker-compose.yml
[docker-compose.txt](https://github.com/milvus-io/milvus/files/13769637/docker-compose.txt)

**Comment by zhuwenxing** [comment]
Hi, I have no idea what's issue with the MIlvus server, but I checked your backup log, and found that it was failed at flush.
Actually, Milvus can backup data without flush with -f subcommand. Hope it can solve your problem temporary.
![image](https://github.com/milvus-io/milvus/assets/12268675/55e6bfbd-6522-411f-8b34-7f07b094a1a9)

**Comment by stan5215** [comment]
> Hi, I have no idea what's issue with the MIlvus server, but I checked your backup log, and found that it was failed at flush. Actually, Milvus can backup data without flush with -f subcommand. Hope it can solve your problem temporary. ![image](https://private-user-images.githubusercontent.com/12268675/292829619-55e6bfbd-6522-411f-8b34-7f07b094a1a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NzkzNzAsIm5iZiI6MTcwMzU3OTA3MCwicGF0aCI6Ii8xMjI2ODY3NS8yOTI4Mjk2MTktNTVlNmJmYmQtNjUyMi00MTFmLThiMzQtN2YwN2IwOTRhMWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDA4MjQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4NzA0ODUzOTEyMzIwYmUzOGY4ZTM4M2NiZDBiMjYzYWM5YTI1NmJjZDIwNzMzZmE3ZmM3Mzg5NzEzMDVlYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jCtGoVbKK83RBG0Kbz1xbYxC9mwpK8VPOLhYWqJyYfw)

Thank you very much. I tried it and the backup was successful.

**Comment by yanliang567** [comment]
@stan5215 it seems that some detadata was dirtied, so milvus fail to load/find the collection. How did you restart the server? what did you do before/after restart milvus? did you change anything to etcd/minio?

/assign @stan5215

**Comment by stan5215** [comment]
@yanliang567 
Milvus has been running normally for more than a month, but the physical server suddenly lost power. After I restarted milvus using  `docker compose up -d` , the collection could not be loaded. I did not perform any other operations.

**Comment by stan5215** [comment]
@weiliu1031 
Thank you. It was 0% after several hours of restarting, but I don’t have a complete log. If the reason cannot be seen in the log below, I will post the log again when the problem occurs next time.
[milvus20231225.zip](https://github.com/milvus-io/milvus/files/13782721/milvus20231225.zip)

Now the problem will not occur after restarting the system using  `reboot`. It should only occur when there is a sudden power outage.

**Comment by ThinkThinkSyn** [comment]
We met the same problem that stucking in 0% loading after restarting from a sudden electricity supply lost. Has anyone solved the problem?
