### ISSUE TITLE
[Bug]: A large number of 【meta update: add allocation】 operations occur in the datacoord, causing the CPU usage to increase.

### ISSUE THREAD

**Issue by Richard-lrg** [milvus-io/milvus#29493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.3
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): jdk
- OS(Ubuntu or CentOS):  CentOS
- CPU/Memory: 32C 128G * 3
- GPU: 
- Others:
```

### Current Behavior

A large number of 【meta update: add allocation】 operations occur in the datacoord, causing the CPU usage to increase.
But I don't know what triggers it

some logs:
[2023/12/26 07:40:05.088 +00:00] [INFO] [datacoord/services.go:180] ["handle assign segment request"] [traceID=ac3cb142401d0e6fa93e5d3f2fa56c27] [collectionID=444181922422872669      ] [partitionID=444181922422872670] [channelName=search-hba-rootcoord-dml_55_444181922422872669v0] [count=8] [isImport=false] ["import task ID"=0]
 1210 [2023/12/26 07:40:05.088 +00:00] [DEBUG] [datacoord/meta.go:920] ["meta update: add allocation"] [segmentID=445795537962892161] [allocation="SegmentID: 445795537962892161, NumOf      Rows: 8, ExpireTime: 2023-12-26 07:40:07.063 +0000 UTC"]
 1211 [2023/12/26 07:40:05.088 +00:00] [INFO] [datacoord/meta.go:934] ["meta update: add allocation - complete"] [segmentID=445795537962892161]
 1212 [2023/12/26 07:40:05.088 +00:00] [INFO] [datacoord/services.go:219] ["success to assign segments"] [traceID=ac3cb142401d0e6fa93e5d3f2fa56c27] [collectionID=444181922422872669] [      assignments="[{\"SegmentID\":445795537962892161,\"NumOfRows\":8,\"ExpireTime\":446582333653123074}]"]
 1213 [2023/12/26 07:40:05.598 +00:00] [DEBUG] [datacoord/server.go:753] ["Updating segment number of rows"] [segmentID=445795537962892161] ["old value"=1308] ["new value"=1385]
 1214 [2023/12/26 07:40:10.072 +00:00] [INFO] [datacoord/services.go:429] ["receive SaveBinlogPaths request"] [traceID=ecb5ef56ca0eb9c42ce6572db2c530ac] [nodeID=1175] [collectionID=44      5795537918996829] [segmentID=445795537963210245] [isFlush=false] [isDropped=false] [startPositions=null] [checkpoints="[{\"segmentID\":445795537963210245,\"position\":{\"channel      _name\":\"search-hba-rootcoord-dml_44_445795537918996829v0\",\"msgID\":\"CK3WFxCyiAIYACAA\",\"msgGroup\":\"datanode-1175-search-hba-rootcoord-dml_44_445795537918996829v0-true\",      \"timestamp\":446582331922972673},\"num_of_rows\":2557}]"]
 1215 [2023/12/26 07:40:10.072 +00:00] [DEBUG] [datacoord/meta.go:454] ["meta update: update flush segments info"] [segmentId=445795537963210245] [binlog=14] ["stats log"=1] ["delta l      ogs"=1] [flushed=false] [dropped=false] ["check points"="[{\"segmentID\":445795537963210245,\"position\":{\"channel_name\":\"search-hba-rootcoord-dml_44_445795537918996829v0\",\      "msgID\":\"CK3WFxCyiAIYACAA\",\"msgGroup\":\"datanode-1175-search-hba-rootcoord-dml_44_445795537918996829v0-true\",\"timestamp\":446582331922972673},\"num_of_rows\":2557}]"] ["s      tart position"=null] [importing=false]

> 

### Milvus Log

full datacoord log:  https://pan.baidu.com/s/1P5sEI7azrJlb82JelPqKzg?pwd=7cym 

[Uploading dc_part.log…]()

**Comment by xiaofan-luan** [comment]
@Cactus-L did you trigger flush manually and has a lot of collections, partitions?

**Comment by Cactus-L** [comment]
> @Cactus-L did you trigger flush manually and has a lot of collections, partitions?

no, I don't

**Comment by MrPresent-Han** [comment]
@Cactus-L hello, two points:
1. the log file dc_1226 is datanode's log, not datacoord's
2. according to datanode's log, there are contiguous insert operations coming into the datanodes and 28 new segments are created between 00:15 and 08:55, which is as expected based on current design.

<img width="1191" alt="截屏2023-12-28 11 09 58" src="https://github.com/milvus-io/milvus/assets/116052805/198dfe18-185c-43ba-b4af-824ae363bff5">

in the existing framework of milvus, whenever inserting new data into the collections, proxy will try to get an assignment from datacoord and when the previous-allocated segments have been large enough, new segments will be allocated and assigned to insert request accordingly. So the logs you post above may not be something unexpected.

Additionally, if you can provide logs file for proxy and datacoord, I can have a better sight of your problem.

**Comment by Cactus-L** [comment]
> @Cactus-L hello, two points:
> 
> 1. the log file dc_1226 is datanode's log, not datacoord's
> 2. according to datanode's log, there are contiguous insert operations coming into the datanodes and 28 new segments are created between 00:15 and 08:55, which is as expected based on current design.
> 
> <img alt="截屏2023-12-28 11 09 58" width="1191" src="https://private-user-images.githubusercontent.com/116052805/293129901-198dfe18-185c-43ba-b4af-824ae363bff5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MzUyMzIsIm5iZiI6MTcwMzczNDkzMiwicGF0aCI6Ii8xMTYwNTI4MDUvMjkzMTI5OTAxLTE5OGRmZTE4LTE4NWMtNDNiYS1iNGFmLTgyNGFlMzYzYmZmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQwMzQyMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01N2ZhMjc5NzY4YzdkYmFhOWUzZjE2YmJlZjY0MWQzODFlYTk5YmUxMWI5ZTU2Zjc4MmRiMTQyNjI2N2I0OWY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._YVUcPtsDUFKWjwnbp8D6UGfdfztag3AC1c4VPh6J1Q">
> in the existing framework of milvus, whenever inserting new data into the collections, proxy will try to get an assignment from datacoord and when the previous-allocated segments have been large enough, new segments will be allocated and assigned to insert request accordingly. So the logs you post above may not be something unexpected.
> 
> Additionally, if you can provide logs file for proxy and datacoord, I can have a better sight of your problem.

thx, here are the logs of proxy and datacoord.
datacoord: https://pan.baidu.com/s/1Pk6gl2cxRYlQxWO5VXbGqA?pwd=jraw
proxy: https://pan.baidu.com/s/1RSD1mphxF3wPPfVkWFW3Ow?pwd=t2rg

**Comment by MrPresent-Han** [comment]
according to proxy log provided, continuous upsert requests kept going into the milvus:
'''
(base) zilliz@hc-mac proxy % grep "Enqueue upsert request in Proxy" * |wc
    8713  156834 2445592
'''

that's the reason for keeping assigning segments, because upsert=delete+insert
