### ISSUE TITLE
[Bug]: Compaction can be never done with Array type

### ISSUE THREAD

**Issue by yah01** [milvus-io/milvus#29503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

the compactor missing to handle array type, the system could go normally with the original flushed segments, but these segments can be never compacted

**Comment by yah01** [comment]
@yanliang567 also we need a e2e testcase to manually compact a collection with array type

**Comment by yanliang567** [comment]
/assign @ThreadDao @elstic 
please help to add the array type in compaction e2e and stability nightly.
