### ISSUE TITLE
[Bug]: milvus-standalone docker restarting, unable to function properly

### ISSUE THREAD

**Issue by Aristomd** [milvus-io/milvus#29509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:milvusdb/milvus:v2.2.8
- Deployment mode(standalone or cluster):standlone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

docker log报错
milvus-standalone容器一直重启，始终无法正常运行

### Milvus Log

{"log":"[2023/12/26 03:24:24.656 +00:00] [WARN] [rootcoord/quota_center.go:129] [\"quotaCenter sync metrics failed\"] [error=\"quotaCenter get Query cluster failed, err = role querycoord[nodeID: 2334] is not serving, reason: Initializing\"]\n","stream":"stdout","time":"2023-12-26T03:24:24.656504386Z"}
{"log":"[2023/12/26 03:24:24.656 +00:00] [WARN] [rootcoord/proxy_client_manager.go:239] [\"proxy client is empty, GetMetrics will not send to any client\"]\n","stream":"stdout","time":"2023-12-26T03:24:24.656742523Z"}

{"log":"[2023/12/26 03:24:24.660 +00:00] [WARN] [retry/retry.go:44] [\"retry func failed\"] [\"retry time\"=0] [error=\"role querycoord[nodeID: 2334] is not serving, reason: Initializing\"]\n","stream":"stdout","time":"2023-12-26T03:24:24.661162357Z"}

{"log":"[2023/12/26 03:24:26.176 +00:00] [WARN] [retry/retry.go:44] [\"retry func failed\"] [\"retry time\"=0] [error=\"rpc error: code = DeadlineExceeded desc = context deadline exceeded\"]\n","stream":"stdout","time":"2023-12-26T03:24:26.176556117Z"}
{"log":"[2023/12/26 03:24:26.176 +00:00] [WARN] [grpcclient/client.go:318] [\"ClientBase ReCall grpc first call get error\"] [role=datacoord] [error=\"err: rpc error: code = DeadlineExceeded desc = context deadline exceeded\\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:317 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\\n/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:435 github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).GetRecoveryInfoV2\\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/coordinator_broker.go:153 github.com/milvus-io/milvus/internal/querycoordv2/meta.(*CoordinatorBroker).GetRecoveryInfoV2\\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/target_manager.go:203 github.com/milvus-io/milvus/internal/querycoordv2/meta.(*TargetManager).PullNextTargetV2.func1\\n/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:42 github.com/milvus-io/milvus/internal/util/retry.Do\\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/target_manager.go:225 github.com/milvus-io/milvus/internal/querycoordv2/meta.(*TargetManager).PullNextTargetV2\\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/target_manager.go:121 github.com/milvus-io/milvus/internal/querycoordv2/meta.(*TargetManager).updateCollectionNextTarget\\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/target_manager.go:113 github.com/milvus-io/milvus/internal/querycoordv2/meta.(*TargetManager).UpdateCollectionNextTarget\\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/server.go:586 github.com/milvus-io/milvus/internal/querycoordv2.(*Server).recoverCollectionTargets.func1\\n\"]\n","stream":"stdout","time":"2023-12-26T03:24:26.176668636Z"}
{"log":"[2023/12/26 03:24:26.176 +00:00] [ERROR] [meta/coordinator_broker.go:155] [\"get recovery info failed\"] [collectionID=442936578926462225] [partitionIDs=\"[]\"] [error=\"context deadline exceeded\"] [stack=\"github.com/milvus-io/milvus/internal/querycoordv2/meta.(*CoordinatorBroker).GetRecoveryInfoV2\\n\\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/coordinator_broker.go:155\\ngithub.com/milvus-io/milvus/internal/querycoordv2/meta.(*TargetManager).PullNextTargetV2.func1\\n\\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/target_manager.go:203\\ngithub.com/milvus-io/milvus/internal/util/retry.Do\\n\\t/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:42\\ngithub.com/milvus-io/milvus/internal/querycoordv2/meta.(*TargetManager).PullNextTargetV2\\n\\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/target_manager.go:225\\ngithub.com/milvus-io/milvus/internal/querycoordv2/meta.(*TargetManager).updateCollectionNextTarget\\n\\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/target_manager.go:121\\ngithub.com/milvus-io/milvus/internal/querycoordv2/meta.(*TargetManager).UpdateCollectionNextTarget\\n\\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/target_manager.go:113\\ngithub.com/milvus-io/milvus/internal/querycoordv2.(*Server).recoverCollectionTargets.func1\\n\\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/server.go:586\\ngithub.com/milvus-io/milvus/internal/util/retry.Do\\n\\t/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:42\\ngithub.com/milvus-io/milvus/internal/querycoordv2.(*Server).recoverCollectionTargets\\n\\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/server.go:585\\ngithub.com/milvus-io/milvus/internal/querycoordv2.(*Server).recover.func1\\n\\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/server.go:570\\ngolang.org/x/sync/errgroup.(*Group).Go.func1\\n\\t/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57\"]\n","stream":"stdout","time":"2023-12-26T03:24:26.176853579Z"}
{"log":"[2023/12/26 03:24:26.176 +00:00] [WARN] [retry/retry.go:44] [\"retry func failed\"] [\"retry time\"=0] [error=\"context deadline exceeded\"]\n","stream":"stdout","time":"2023-12-26T03:24:26.176901126Z"}

**Comment by yanliang567** [comment]
@Aristomd Could you please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.
BTW, according to the logs you attach, i guess milvus lost connection with etcd or minio, could you please double check that the etcd and minio service are healthy?

/assign @Aristomd 
/unassign
