### ISSUE TITLE
[Bug]: DataNode stuck in Abnormal state after etcd pods lose quorum

### ISSUE THREAD

**Issue by chern** [milvus-io/milvus#29511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.3.2 amd64
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): Kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When performing etcd resiliency testing, I noticed that when etcd loses quorum (e.g. 3+ out of the 5 etcd pods become unavailable), the Milvus DataNode pod gets stuck in an `Abnormal` state and is unable to get into Ready state for a long period of time. This persists even after the etcd pods are recreated and availability has recovered.

### Expected Behavior

Once the etcd pods are recreated and etcd availability recovers to ready, the DataNode should reconnect with etcd and not be stuck in Abnormal state.

### Steps To Reproduce

```markdown
Setup: An AWS EKS cluster with an etcd cluster deployed separately from Milvus. The etcd endpoint is configured in the ConfigMap for the Milvus cluster.

Steps for the etcd resiliency tests that led to this behavior:
1. Deploy etcd with 5 pods
2. For 3 pods, cordon and then delete the nodes on which the pods are running
   - This takes down those pods and makes the etcd cluster unavailable, due to losing quorum
```

### Milvus Log

DataNode logs around the time that etcd goes down:

```
[2023/12/27 00:39:02.835 +00:00] [DEBUG] [config/etcd_source.go:141] ["etcd refreshConfigurations"] [prefix=milvus-william-2/config] [endpoints="[etcd-milvus-default:2379]"]
[2023/12/27 00:39:06.900 +00:00] [DEBUG] [datanode/services.go:69] ["DataNode current state"] [State=Abnormal]
```

Logs for all Milvus pods are in the attached [logs.zip](https://github.com/milvus-io/milvus/files/13774661/logs.zip)

### Anything else?

I saw that this issue was previously raised in https://github.com/milvus-io/milvus/issues/26868; however, this issue is still present in v2.3.2. The logs/errors and behavior seem to be identical between that issue and this one, but the [Discord discussion](https://discord.com/channels/1160323594396635310/1171824088109547561/threads/1183930319167041576) asked me to create a new issue.

**Comment by yanliang567** [comment]
@chern if convenient, please retry the test on latest 2.3 build, e.g. [2.3-20231226-6eeb4b7f](https://hub.docker.com/layers/milvusdb/milvus/2.3-20231226-6eeb4b7f/images/sha256-681ef01e5af8928c2f7c1b445ce8034efd95868fd819a98c8ca97ca63ff53147?context=explore), and help to attach all the milvus and etcd pods logs for investigations.  
meanswhile @weiliu1031 please help to check the attached logs 

/assign @weiliu1031 
/unassign

**Comment by chern** [comment]
Thanks @yanliang567; so far I have not yet been able to reproduce this issue using the 2.3-20231226-6eeb4b7f build. I will update and post logs if I see this issue come up again in further testing.
