### ISSUE TITLE
If there are multi segments, the result of IVF_PQ IP is wrong

### ISSUE THREAD

**Issue by shengjun1985** [milvus-io/milvus#2952]
**Please state you issue using the following template and, most importantly, in English.**

**Describe the bug**
If there are multi segments, the result of IVF_PQ IP is wrong.
There is a bug in merging task result.

**Steps/Code to reproduce behavior**
(0) create collection whose metric_type is IP
(1) inset data and product multi segments
(2) create IVF_PQ 
(3) query the topK nearest items
The result is wrong.

**Expected behavior**
The result is correct.

**Environment details**
- Milvus version (v0.10.1)

**Screenshots**
none

**Additional context**
from source review

**Comment by dvzubarev** [comment]
What is "multi segments" ? I searched this repository and found nothing except this issue and PRs.

**Comment by shengjun1985** [comment]
When the total data in a collection is large enough, ie. multiple gigabytes, Milvus will organize the data in multiple slices, or "segments". For instance, 1 GB of vector data per segment. Then, Milvus will build index for each of the data segment. 

Thus, if you have a collection containing 10 GB of vector data, and 1GB per segment, we will have 10 segments. 
That is where the "multi-segments" come from.

**Comment by dvzubarev** [comment]
Thank you, for explanation
