### ISSUE TITLE
[Bug]: unknown method Upsert for service milvus.proto.milvus.MilvusService

### ISSUE THREAD

**Issue by zgpsuper888** [milvus-io/milvus#29536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.1
- Deployment mode(standalone or cluster): distributed
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus2.3.4
- OS(Ubuntu or CentOS): macOS 14.2.1
- CPU/Memory: M3 Pro /18G
- GPU: 
- Others:
```

### Current Behavior

upsert the record of id =1

### Expected Behavior

success

### Steps To Reproduce

```markdown
from pymilvus import (
    connections,
    utility,
    FieldSchema,CollectionSchema,DataType,
    Collection,
)
import numpy as np
from datetime import datetime,timedelta
# num_entities = 2000000
# dim = 768
num_entities = 20000
dim = 128
col_name = "test_collection1227_768"
host = "**.**.**.***"

def create_connect(host,name='default',port='19530'):
    connections.connect(name,host=host,port=port)

def create_collection(col_name):
    fields = [
        FieldSchema(name="id", dtype = DataType.VARCHAR, is_primary=True,auto_id=False,max_length=10),
        FieldSchema(name="level1",dtype=DataType.INT16),
        FieldSchema(name="embeddings",dtype=DataType.FLOAT_VECTOR,dim=dim),
        FieldSchema(name="dt",dtype=DataType.VARCHAR,max_length=100)
    ]
    schema = CollectionSchema(fields,"test milvus1226")
    col = Collection(col_name,schema,consistency_level="Strong")
    return col

def create_data(collection):
    rng = np.random.default_rng(seed=19530)
    batch_size = 5000
    num_batch = num_entities//batch_size
    ids  = 0
    start_date = datetime(year=2023,month=1,day=1)
    end_date = datetime(year=2023,month=12,day=31)

    start_timestamp = start_date.timestamp()
    end_timestamp = end_date.timestamp()

    for i in range(num_batch):
        random_timestamps = rng.uniform(start_timestamp,end_timestamp,size=batch_size)
        random_dates = [datetime.fromtimestamp(ts) for ts in random_timestamps]
        entities = [
            [str(ids+i) for i in range(batch_size)],
            rng.integers(low=1,high = 201,size =batch_size).tolist(),
            rng.random((batch_size,dim)),
            [date.strftime("%Y%m%d") for date in random_dates]
        ]
        collection.insert(entities)
        ids += batch_size
    collection.flush()
    index = {
        "index_type":"IVF_SQ8",
        "metric_type":"L2",
        "params":{"nlist":4096}
    }
    collection.create_index("embeddings",index)

def upsert_demo(collection):
    rng = np.random.default_rng(seed=19530)

    entities = [
            ['1'],
            rng.integers(low=1, high=201, size=1).tolist(),
            rng.random((1, dim)),
            [datetime(year=2023,month=1,day=1).strftime("%Y%m%d")]
        ]
    mr = collection.upsert(entities)
    collection.flush()
def query_demo(host):
    connections.connect('default', host=host, port='19530')
    collection = Collection(col_name)
    collection.load()
    res = collection.query(
        expr="id in ['1','2','3','4','5','6','7','8','9','10']",
        offset=0,
        limit=10,
        # output_fields=["id", "level1", "embeddings","dt"],
        output_fields=["id", "level1","dt"],
    )

    for e in res:
        print(e)


if __name__ == '__main__':
    create_connect(host=host)
    # newCollection = create_collection(col_name)

    # create_data(newCollection)
    # 更新前
    # query_demo()
    collection = Collection(col_name)
    collection.load()
    # query_demo(host=host)
    upsert_demo(collection)
    # upsert_demo(newCollection)
    # upsert_demo(Collection(col_name))
    # 更新后
    # query_demo()
```

### Milvus Log

/usr/bin/python3 /Users/zhanggaopan/PycharmProjects/knowledge_data_pro/service/test_script/application-upsert-data.py 
[upsert] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNIMPLEMENTED, unknown method Upsert for service milvus.proto.milvus.MilvusService>
[upsert] retry:5, cost: 0.81s, reason: <_MultiThreadedRendezvous: StatusCode.UNIMPLEMENTED, unknown method Upsert for service milvus.proto.milvus.MilvusService>
[upsert] retry:6, cost: 2.43s, reason: <_MultiThreadedRendezvous: StatusCode.UNIMPLEMENTED, unknown method Upsert for service milvus.proto.milvus.MilvusService>
[upsert] retry:7, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNIMPLEMENTED, unknown method Upsert for service milvus.proto.milvus.MilvusService>
[upsert] retry:8, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNIMPLEMENTED, unknown method Upsert for service milvus.proto.milvus.MilvusService>
Traceback (most recent call last):
  File "/Library/Python/3.9/site-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
  File "/Library/Python/3.9/site-packages/pymilvus/client/grpc_handler.py", line 647, in upsert
    raise err from err
  File "/Library/Python/3.9/site-packages/pymilvus/client/grpc_handler.py", line 640, in upsert
    response = rf.result()
  File "/Library/Python/3.9/site-packages/grpc/_channel.py", line 881, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "unknown method Upsert for service milvus.proto.milvus.MilvusService"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2023-12-27T15:51:23.709599+08:00", grpc_status:12, grpc_message:"unknown method Upsert for service milvus.proto.milvus.MilvusService"}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhanggaopan/PycharmProjects/knowledge_data_pro/service/test_script/application-upsert-data.py", line 98, in <module>
    upsert_demo(collection)
  File "/Users/zhanggaopan/PycharmProjects/knowledge_data_pro/service/test_script/application-upsert-data.py", line 69, in upsert_demo
    mr = collection.upsert(entities)
  File "/Library/Python/3.9/site-packages/pymilvus/orm/collection.py", line 617, in upsert
    res = conn.upsert(
  File "/Library/Python/3.9/site-packages/pymilvus/decorators.py", line 125, in handler
    return func(*args, **kwargs)
  File "/Library/Python/3.9/site-packages/pymilvus/decorators.py", line 164, in handler
    return func(self, *args, **kwargs)
  File "/Library/Python/3.9/site-packages/pymilvus/decorators.py", line 90, in handler
    time.sleep(back_off)
KeyboardInterrupt

Process finished with exit code 130 (interrupted by signal 2: SIGINT)

### Anything else?

python3.9

**Comment by yanliang567** [comment]
@zgpsuper888 It does not reproduce to me with milvus v2.3.1 and pymilvus 2.3.1/2.3.3. But my python is 3.8, but i don't think it matters. Could you please double check your milvus and pymilvus version, and rerun the code?
/assign @zgpsuper888 
/unassign

**Comment by zgpsuper888** [comment]
sorry，The database engineer installed the incorrect version of Milvus.
