### ISSUE TITLE
[Enhancement]: milvus supports huaweicloud obs as external S3

### ISSUE THREAD

**Issue by yulingfan97** [milvus-io/milvus#29537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Now milvus supports aws/gcp/aliyun as external S3，but not supports huaweicloud. I hope milvus can support huaweicloud obs as external S3, and I think there are some other people use huaweicloud obs, who hope to use milvus with obs too.

### Why is this needed?

Some other people use huaweicloud object storage (OBS）, and they hope to use obs as external S3 in using milvus.

**Comment by xiaofan-luan** [comment]
@yulingfan97 
We don't have any test environment on huawei cloud.
Does it compatible with S3?

**Comment by xiaofan-luan** [comment]
from your pr it seems you can directly use S3 client for huwei obs

**Comment by yulingfan97** [comment]
yes, it is compatible with S3. However, maybe we should make people  know it can support huaweicloud OBS ?
