### ISSUE TITLE
[Bug]: Cosine similarity score exceed 1.0 when searching with filter

### ISSUE THREAD

**Issue by billyinhao** [milvus-io/milvus#29540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.3
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq  
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.3.3
- OS(Ubuntu or CentOS): CentOS 7.9.2009
- CPU/Memory: 8 CPUs, 62G Mem
- GPU: No
- Others:
```

### Current Behavior

I use DiskANN index type on 1024 dim embedding field, with COSINE metric type, and partition key `hotel_id`. 
When I execute the search without expr as below:
`search_params = {
  'metric_type': 'COSINE',
  'params': {
      'k': 20,
      'search_list': 200
  }
}`
`resp = collection.search(vectors_to_search, "embedding", search_params, limit=20)`
I got a result that looks correct (although the max score value still exceeds 1.0):
![image](https://github.com/milvus-io/milvus/assets/18389927/ecc94461-fff9-478a-a436-5a479acebfe9)

But when I execute the search with expr as below (filtered on partition key):
`search_params = {
  'metric_type': 'COSINE',
  'params': {
      'k': 20,
      'search_list': 200
  }
}`
`resp = collection.search(vectors_to_search, "embedding", search_params, expr=f'hotel_id == "1266769"', limit=20)`
I got the result that all scores far above 1.0: 
![image](https://github.com/milvus-io/milvus/assets/18389927/3cf97a1d-a4e4-4d0d-bbae-9eaff7f85980)

The result displayed on Attu is the same as I searching in the pymilvus client.

**Comment by yanliang567** [comment]
/assign @elstic 
please help to reproduce the issue in house
/unassign

**Comment by elstic** [comment]
I am using v2.3.3 and the glove dataset but it does not reproduce. Can you take a look at this issue?  @cydrain

**Comment by cydrain** [comment]
Milvus 2.3.3 is using knowhere v2.2.2, similar issue has been fixed in knowhere v2.2.3
Fixed by https://github.com/zilliztech/knowhere/pull/251

**Comment by cydrain** [comment]
duplicated with https://github.com/milvus-io/milvus/issues/28821

**Comment by billyinhao** [comment]
@cydrain So I have to wait until the next version of milvus with knowhere v2.2.3 to fix this issue? Otherwise I need to change the metric type to `IP`, but this requires normalizing all the embeddings in collection.
