### ISSUE TITLE
[Bug]: batch data insert freeze after 50 batches in sequence on milvus standalone

### ISSUE THREAD

**Issue by dove-young** [milvus-io/milvus#29542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.3
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    N/A
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): RHEL 8
- CPU/Memory: 8 CPU, 64GB
- GPU: 
- Others:
```

### Current Behavior

1. Create collection schema like this

```
    common_major_point_fields = [
        FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, auto_id=True),
        FieldSchema(name="ts", dtype=DataType.VARCHAR, max_length=20),
        FieldSchema(name="major_point_embedding", dtype=DataType.FLOAT_VECTOR, dim=dim),
    ]
```

2. run application with pymivuls,  get embeddings, and populate data into a matrix, a 2 column list. each list is no longer than 10 elements, insert the matrix into milvus.
```
2023-12-27 02:34:08 - milvus.py:335 - INFO: <Collection>:
-------------
<name>: all_MiniLM_L12_v1_raw_text
<description>: all_MiniLM_L12_v1_raw_text
<schema>: {'auto_id': True, 'description': 'all_MiniLM_L12_v1_raw_text', 'fields': [{'name': 'pk', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': True}, {'name': 'ts', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 20}}, {'name': 'major_point_embedding', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 384}}]}
 insert result = (insert count: 28, delete count: 0, upsert count: 0, timestamp: 446607720131592196, success count: 28, err count: 0)
2023-12-27 02:34:08 - common-messages-to-vectordb-in-batch.py:164 - DEBUG: index = 510  len of text_list = 14
```
3. after 50 inserts, it hangs up, and freeze for couple of minutes. 

```
2023-12-27 02:34:10 - common-messages-to-vectordb-in-batch.py:170 - DEBUG: index = 510
2023-12-27 02:34:10 - common-messages-to-vectordb-in-batch.py:171 - DEBUG: len of embeddings = 14

2023-12-27 02:34:10 - common-messages-to-vectordb-in-batch.py:172 - DEBUG: len of embedding_colume = 14

2023-12-27 02:34:10 - milvus.py:333 - DEBUG: length of matritx = 2

```

4. this problem is reproduceable

### Steps To Reproduce

```markdown
1. Run milvus standalone on a VM
2. Run pymilvus application in another VM
3. Make sure network connection is clear, you can verify via `tcpdump`
4. after about 50 batch inserts, it hangs up.
```

### Anything else?

```
docker ps -a
CONTAINER ID   IMAGE                                      COMMAND                  CREATED        STATUS                  PORTS                                              NAMES
2bd3fb1a60ee   milvusdb/milvus:v2.3.3                     "/tini -- milvus run…"   43 hours ago   Up 43 hours             0.0.0.0:9091->9091/tcp, 0.0.0.0:19530->19530/tcp   milvus-standalone
866bbd73c225   minio/minio:RELEASE.2023-03-20T20-16-18Z   "/usr/bin/docker-ent…"   43 hours ago   Up 43 hours (healthy)   9000/tcp                                           milvus-minio
354cf6631241   quay.io/coreos/etcd:v3.5.5                 "etcd -advertise-cli…"   43 hours ago   Up 43 hours             2379-2380/tcp                                      milvus-etcd
```

**Comment by dove-young** [comment]
[milvus-standalone.log.tar.gz](https://github.com/milvus-io/milvus/files/13777948/milvus-standalone.log.tar.gz)

**Comment by yanliang567** [comment]
@dove-young quick questions:
1. how big is your each insert batch size?
2. do you have SSD volumes running for milvus/etcd pods?

/assign @dove-young

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version:2.3.3
> - Deployment mode(standalone or cluster): standalone
> - MQ type(rocksmq, pulsar or kafka):    N/A
> - SDK version(e.g. pymilvus v2.0.0rc2):
> - OS(Ubuntu or CentOS): RHEL 8
> - CPU/Memory: 8 CPU, 64GB
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> 1. Create collection schema like this
> 
> ```
>     common_major_point_fields = [
>         FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, auto_id=True),
>         FieldSchema(name="ts", dtype=DataType.VARCHAR, max_length=20),
>         FieldSchema(name="major_point_embedding", dtype=DataType.FLOAT_VECTOR, dim=dim),
>     ]
> ```
> 
> 2. run application with pymivuls,  get embeddings, and populate data into a matrix, a 2 column list. each list is no longer than 10 elements, insert the matrix into milvus.
> 
> ```
> 2023-12-27 02:34:08 - milvus.py:335 - INFO: <Collection>:
> -------------
> <name>: all_MiniLM_L12_v1_raw_text
> <description>: all_MiniLM_L12_v1_raw_text
> <schema>: {'auto_id': True, 'description': 'all_MiniLM_L12_v1_raw_text', 'fields': [{'name': 'pk', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': True}, {'name': 'ts', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 20}}, {'name': 'major_point_embedding', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 384}}]}
>  insert result = (insert count: 28, delete count: 0, upsert count: 0, timestamp: 446607720131592196, success count: 28, err count: 0)
> 2023-12-27 02:34:08 - common-messages-to-vectordb-in-batch.py:164 - DEBUG: index = 510  len of text_list = 14
> ```
> 
> 3. after 50 inserts, it hangs up, and freeze for couple of minutes.
> 
> ```
> 2023-12-27 02:34:10 - common-messages-to-vectordb-in-batch.py:170 - DEBUG: index = 510
> 2023-12-27 02:34:10 - common-messages-to-vectordb-in-batch.py:171 - DEBUG: len of embeddings = 14
> 
> 2023-12-27 02:34:10 - common-messages-to-vectordb-in-batch.py:172 - DEBUG: len of embedding_colume = 14
> 
> 2023-12-27 02:34:10 - milvus.py:333 - DEBUG: length of matritx = 2
> ```
> 
> 4. this problem is reproduceable
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> ```
> 1. Run milvus standalone on a VM
> 2. Run pymilvus application in another VM
> 3. Make sure network connection is clear, you can verify via `tcpdump`
> 4. after about 50 batch inserts, it hangs up.
> ```
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> ```
> docker ps -a
> CONTAINER ID   IMAGE                                      COMMAND                  CREATED        STATUS                  PORTS                                              NAMES
> 2bd3fb1a60ee   milvusdb/milvus:v2.3.3                     "/tini -- milvus run…"   43 hours ago   Up 43 hours             0.0.0.0:9091->9091/tcp, 0.0.0.0:19530->19530/tcp   milvus-standalone
> 866bbd73c225   minio/minio:RELEASE.2023-03-20T20-16-18Z   "/usr/bin/docker-ent…"   43 hours ago   Up 43 hours (healthy)   9000/tcp                                           milvus-minio
> 354cf6631241   quay.io/coreos/etcd:v3.5.5                 "etcd -advertise-cli…"   43 hours ago   Up 43 hours             2379-2380/tcp                                      milvus-etcd
> ```

What kind of error did you hit?
Didn't quite get what doe you mean by freeze?

**Comment by xiaofan-luan** [comment]
It's not very reasonable you can reproduce all the time.
Make sure
1. you have enough disk space
2. you have enough memory

**Comment by dove-young** [comment]
-   how big is your each insert batch size?
  20 records in each batch. each record consists of one ID field and one embedding field.

-    do you have SSD volumes running for milvus/etcd pods?
No
-    you have enough disk space
Yes. over hundred Gs free disk
-    you have enough memory
Yes. 64GB memory

And I noticed it only happened when I access to Milvus from another VM. 

When I move Milvus to the same VM the application runs, it works well.

**Comment by xiaofan-luan** [comment]
then this sounds like a network bandwidth issue.
Do you have any bandwidth limitation across multiple machines

**Comment by yanliang567** [comment]
@dove-young any updates?

**Comment by dove-young** [comment]
no more update.  When I run milvus and application on the same VM, this is not reproduced.

**Comment by yanliang567** [comment]
close as comments above
