### ISSUE TITLE
[Bug]: 压测milvus插入跟删除接口,发现报错Channel Close错误! 并发数:10,语言:python 

### ISSUE THREAD

**Issue by jiaochuangen** [milvus-io/milvus#29552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.3
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.4
- OS(Ubuntu or CentOS):  Ubuntu
- CPU/Memory: 12核/89G
- GPU: 16G
- Others:
```

### Current Behavior

![21d029925629e8d43b499de02c6950b](https://github.com/milvus-io/milvus/assets/53078519/df1cbf92-ba81-444b-bd0a-734feeb06fa6)
![dfca2d3ffcabb26fbae6abfa8e53b47](https://github.com/milvus-io/milvus/assets/53078519/9757070a-b5b9-47cc-a563-337477173ab8)
压测的时候,有的成功有的失败,失败率在20%左右,报错的话,如上图,代码如上图,查询百度说是连接关闭等,想看看啥问题,请求帮助

**Comment by binbinlv** [comment]
@jiaochuangen 
Hello, may I ask some questions: 
1. what is the number of your entities for your each insert batch?
2. could you please upload your milvus log? 

Thanks.

**Comment by jiaochuangen** [comment]
connections.disconnet()  is Thread Sharing
