### ISSUE TITLE
[Bug]: Frequent OOM Reboot for Data Node while Bulk Ingestion

### ISSUE THREAD

**Issue by thunderboy-SJTU** [milvus-io/milvus#29615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.1
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): Java 2.3.1
- OS(Ubuntu or CentOS): 
- CPU/Memory: 12 data nodes with 1C/4G
- GPU: 
- Others:
```

### Current Behavior

We have met timeout issues & segment sealing failure issues frequently (almost every day) while running daily bulk insert jobs on a K8s cluster with 12 data nodes (1C/4G). The bulk ingestion request contains about 1000+ jobs and each job holds one JSON file with 20000 items (about 200~400MB in total).

The details of the error logs are listed in the Milvus log part.

After investigation, we found above two issues are all caused by data node breakdown (OOM). If a normal data node is down, 
the tasks executed before that time point within a short period on the abnormal node will be lost, so those tasks will be marked as failed with timeout because there are no further responses from them. If a shard leader is down, the flush requests cannot be successfully executed, so those jobs sealing the segments at that time point will also be marked as failed without automatic retry.

However, it is hard for us to determine the root cause of the OOM. The OOM can only be found while the data ingestion job is running, and it occurs on different data nodes each day. 

The OOM logs we found in K8s are like below:<code>
Reason:      OOMKilled<br/>
Exit Code:   137 <br/>
Started:     Sat, 09 Dec 2023 18:22:45 -0800 <br/>
Finished:    Fri, 22 Dec 2023 18:39:13 -0800<br/></code>

We also checked the memory usage of these reboot nodes, some of them have a significant spike to 4G
![image](https://github.com/milvus-io/milvus/assets/32996417/08676286-ef11-4462-8ad4-4efaa8e49ef3)
whereas we also found some cases rebooting because of OOM without touching the line of 4G.
<img width="1285" alt="image" src="https://github.com/milvus-io/milvus/assets/32996417/3ff639a5-7653-42f2-aca8-6296b883f776">

Could you help check why this issue can be caused? Many thanks for that!

### Expected Behavior

No frequent OOM be found.

### Milvus Log

In some error cases, the logs are like this:
`[2023/11/20 07:56:21.490 +00:00][INFO] [rootcoord/import_manager.go:913] 
["a working task has expired and will be marked as failed"] 
["task ID"=445699504559623160] [startTs=1700466059] [ImportTaskExpiration=900]`

Also, we found errors like:
`[2023/11/20 07:17:47.130 +00:00] [INFO] [rootcoord/import_manager.go:609] ["importManager update task info"] [toPersistImportTaskInfo="id:445699504559621838 datanode_id:491 collection_id:445699504559616856 partition_id:445699504559616857 channel_names:\"by-dev-rootcoord-dml_7_445699504559616856v0\" files:\"raw_data/2.3.1/smart_receipt_perf_test/20231117/part-00043.json\" create_ts:1700464520 state:<stateCode:ImportFailed error_message:\"failed to seal segment, shard id 0, segment id 445699504559625390, channel 'by-dev-rootcoord-dml_7_445699504559616856v0', error: attempt #0: failed to save import segment, reason = stack trace: /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace\\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:485 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call\\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:499 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\\n/go/src/github.com/milvus-io/milvus/internal/distributed/datanode/client/client.go:93 github.com/milvus-io/milvus/internal/distributed/datanode/client.wrapGrpcCall[...]\\n/go/src/github.com/milvus-io/milvus/internal/distributed/datanode/client/client.go:220 github.com/milvus-io/milvus/internal/distributed/datanode/client.(*Client).AddImportSegment\\n/go/src/github.com/milvus-io/milvus/internal/datacoord/services.go:1609 github.com/milvus-io/milvus/internal/datacoord.(*Server).SaveImportSegment\\n/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:389 github.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).SaveImportSegment\\n/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:6713 github.com/milvus-io/milvus/internal/proto/datapb._DataCoord_SaveImportSegment_Handler.func1\\n/go/src/github.com/milvus-io/milvus/pkg/util/interceptor/server_id_interceptor.go:54 github.com/milvus-io/milvus/pkg/util/interceptor.ServerIDValidationUnaryServerInterceptor.func1\\n/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1: attempt #0: rpc error: code = Unknown desc = expectedNodeID=469, actualNodeID=492: node not match: attempt #1: rpc error: code = Unknown desc = expectedNodeID=469, actualNodeID=492: node not match: attempt #2: rpc error: code = Unknown desc = expectedNodeID=469, actualNodeID=492: node not match: attempt #3: rpc error: code = Canceled desc = grpc: the client connection is closing: attempt #4: rpc error: code = Canceled desc = grpc: the client connection is closing: attempt #5: rpc error: code = Canceled desc = grpc: the client connection is closing: attempt #6: rpc error: code = Canceled desc = grpc: the client connection is closing: attempt #7: rpc error: code = Canceled desc = grpc: the client connection is closing: attempt #8: rpc error: code = Canceled desc = grpc: the client connection is closing: attempt #9: rpc error: code = Canceled desc = grpc: the client connection is closing: unrecoverable error\" > collection_name:\"smart_receipt_perf_test_6\" partition_name:\"_default\" infos:<key:\"progress_percent\" value:\"89\" > start_ts:1700464593 "]`

**Comment by yanliang567** [comment]
/assign @czs007 
I think you are working on the bulk insert improvement
/unassign

**Comment by czs007** [comment]
@bigsheeper please help check this.
