### ISSUE TITLE
[Enhancement]: Eliminate the unnecessary usage of `proto.Clone` in the read path.

### ISSUE THREAD

**Issue by czs007** [milvus-io/milvus#29620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

In order to modify the TargetID in the read request, we have cloned the original request in our code.

![image](https://github.com/milvus-io/milvus/assets/59249785/836c3010-8c2f-4620-939a-b0b7c01cc70e)

![image](https://github.com/milvus-io/milvus/assets/59249785/18777e5c-fd96-4ad3-8a72-874ab1e7e035)

This would introduce a significant overhead (memory copy).

Therefore, I suggest removing the unnecessary `proto.Clone` in the read path.

### Why is this needed?

performance matters.

**Comment by xiaofan-luan** [comment]
could this related to we try to modify the request and sent to different server.
