### ISSUE TITLE
[Bug]: no memory protection for proxy

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#29649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master & 2.3.4
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):   any
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

when client search/query milvus with large concurrency and output has large vector of big dimension, proxy may crash with OOM

### Expected Behavior

there shall be a memory protection for proxy component

**Comment by xiaofan-luan** [comment]
is it because of large topk + nq + output field?

What kind of limitation will we set?

**Comment by congqixia** [comment]
> is it because of large topk + nq + output field?
> 
> What kind of limitation will we set?

yes. when we test proxy performance with "infinite" querynode, when collection schema has large vector field, say 16384, and output fields contains vector field, proxy crashed due to OOM.
