### ISSUE TITLE
We need detailed interface list of python sdk

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#2965]
Although we already have milvus python sdk documentation (https://github.com/milvus-io/pymilvus), the interfaces introduced here are not very comprehensive, such as get_entity_by_id which are not mentioned. So if there is a complete and detailed milvus python sdk interface list, it will be more user-friendly and convenient.

**Comment by BossZou** [comment]
We'll provide a detailed API for sdk when verson 0.11.0 released.

**Comment by BossZou** [comment]
@JackLCL ,How about this: https://pymilvus.readthedocs.io/en/0.3.0/api.html#methods
