### ISSUE TITLE
[Enhancement]: Change the filter threshold in HNSW as a configurable data volume

### ISSUE THREAD

**Issue by GitHuY** [milvus-io/milvus#29723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

I would like to request change the filter threshold in HNSW as a configurable data volume instead of the percentage. 

> _Currently,  if less than 10% nodes in HNSW match the condition, we convert the search to brute-force search instead of HNSW, which means we only compute the 10% vectors by brute-force._

### Why is this needed?

For the huge volume collection, like 20M vectors, the performance of brute force search on 20M *10% = 2M is also very bad. So we need a configurable data volume to decide whether fallback to brute force search.

**Comment by xiaofan-luan** [comment]
For each of the colleciton, data will be splited into multiple segments.
Each segments is usually 512M by default. Which means around 100K - 1M entities. 

For graph index, if less than 10% nodes match the filtering condition, even if you use the index it's gonna to be much slower and not accurate comapred to brutefoce search. Unless you have some other trick like our in house index.

A config is definitely good, but it's not gonna to help too much on your use case. @GitHuY

**Comment by GitHuY** [comment]
@xiaofan-luan thanks for your clarification, I understand that the high filter rate means more nodes will be scanned in HNSW,  that definitely will impact the search performance. 
In the high filter rate scenario, could you suggest some other index types which can provide better performance?

**Comment by liliu-z** [comment]
> @xiaofan-luan thanks for your clarification, I understand that the high filter rate means more nodes will be scanned in HNSW, that definitely will impact the search performance. In the high filter rate scenario, could you suggest some other index types which can provide better performance?

Brute Force is very efficient for super high filter rate. And IVF-based index can also work.
