### ISSUE TITLE
[Bug]: Unable to enable run against GPU with docker version v2.3.0-gpu (or 2.3.x-gpu), but works with v2.3.0-gpu-beta

### ISSUE THREAD

**Issue by mingusmax** [milvus-io/milvus#29729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.4-gpu
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka): NA   
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.4
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 128GB
- GPU: Nvidia RTX 3090
- Others:
```

### Current Behavior

I'm using docker-compose (not swarm). 
When I run v2.3.0-gpu-beta, I see milvus listed as a GPU process in nvidia-smi:
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090        On  | 00000000:0A:00.0  On |                  N/A |
| 30%   47C    P2             113W / 350W |   1466MiB / 24576MiB |      5%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      2182      G   /usr/lib/xorg/Xorg                          277MiB |
|    0   N/A  N/A      2514      C   ...libexec/gnome-remote-desktop-daemon      613MiB |
|    0   N/A  N/A      2561      G   /usr/bin/gnome-shell                         84MiB |
|    0   N/A  N/A      2793      G   ...libexec/gnome-remote-desktop-daemon        0MiB |
|    0   N/A  N/A    948661      C   milvus                                        0MiB |
+---------------------------------------------------------------------------------------+

Conversely, when I run any other v2.3.x-gpu build, I do not. 
My docker-compose entry:

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.3.0-gpu-beta #works, v2.3.0-gpu does not
    command: [ "milvus", "run", "standalone" ]
    build:
      context: ./src/infra/milvus
      dockerfile: Dockerfile
    image: milvusdb/milvus:master-latest-gpu
    command: ["milvus", "run", "standalone"]
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
              device_ids: ["0"]
    depends_on:
      - "etcd"
      - "minio"

Removing the 'deploy' section in the docker-compose entry has no effect on v2.3.0-gpu-beta; it leverages the gpu successfully. 

What am I missing? 
Thanks. 

### Steps To Reproduce

```markdown
1. Launch v2.3.0-gpu-beta via docker compose
2. Run nvidia-smi 

Milvus is listed in the GPU processes

1. Launch v2.3.4-gpu (or any v2.3.x) via docker compose
2. Run nvidia-smi

Milvus is NOT listed in the GPU processes
```

**Comment by yanliang567** [comment]
/assign @wyfeng001 
please help to take a look
/unassign
