### ISSUE TITLE
[Enhancement]: Increase max supported dimension.

### ISSUE THREAD

**Issue by I-Good-Vegetable** [milvus-io/milvus#29730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Currently, max supported dim is set to 32768; nevertheless, I'm wondering whether such limitation can be removed.

### Why is this needed?

 In our situation, minimum dim of vectors is 1B (10^9). Really need a larger solution

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What would you like to be added?
> Currently, max supported dim is set to 32768; nevertheless, I'm wondering whether such limitation can be removed.
> 
> ### Why is this needed?
> In our situation, minimum dim of vectors is 1B (10^9). Really need a larger solution
> 
> ### Anything else?
> _No response_

LOL
what kind of use case is that?
1B might be too large for a dense embedding and I guess not all your dimension has value and you should use sparse embedding?
