### ISSUE TITLE
Build Milvus v0.10.1 from source get mysqlpp error

### ISSUE THREAD

**Issue by LionelDong** [milvus-io/milvus#2974]
**Describe the bug**
Build Milvusv0.10.1 from source, find mysqlppv3.2.4 build bug like this
sorry, when I find this problem in building from source, I forgot screenshot. so use **ref** screenshot.
![image](https://user-images.githubusercontent.com/7533395/88187131-babf8480-cc68-11ea-9b75-8205d7702589.png)

**ref**: https://tangentsoft.com/mysqlpp/tktview?name=5e73e7ddd8
This is due to the removal of the libmysqld embedded DB server feature in MySQL 8.0.1. 

**Expected behavior**
In milvus/core/cmake/ThirdPartyPackages.cmake line 262
suggest: can we replace SQLITE_SOURCE_URL like this to solve network problem in China. This url is mirror of sqlite
![image](https://user-images.githubusercontent.com/7533395/88186083-505a1480-cc67-11ea-8947-ba56c00e68e0.png)

In milvus/core/cmake/ThirdPartyPackages.cmake line 441
I follow https://tangentsoft.com/mysqlpp/tktview?name=5e73e7ddd8 to replace options.cpp in mysql++-3.2.4.tar.gz
And change cmake externalproject_add URL to local file path.
![image](https://user-images.githubusercontent.com/7533395/88186666-13dae880-cc68-11ea-9c1a-35b6313f41e8.png)
suggest: can we replace mysqlpp url to mirror git to solve network problem in China and fix this problem

Finally, build milvus v0.10.1 from source successfully.

**Environment details**
- Ubuntu20.04
- Method of installation ( from source)
- Milvus version (v0.10.1)

**Comment by scsven** [comment]
@LionelDong It's a good idea. Would you like create a pull request for this ? Add the mirror URL into SQLITE_SOURCE_URL that cmake will to try it if the origin URL unavailable.

**Comment by LionelDong** [comment]
> @LionelDong It's a good idea. Would you like create a pull request for this ? Add the mirror URL into SQLITE_SOURCE_URL that cmake will to try it if the origin URL unavailable.

Yes, I will. 
But, I rebuild **Milvus v0.10.0 cpu vsersion**  from source that use mysqlpp_eq with **mysql++-v3.2.4.tar.gz** get error like this:
![image](https://user-images.githubusercontent.com/7533395/88257431-45979200-ccf0-11ea-92f1-7c47a1cbf491.png)
I don't know that only happen on my machine **Ubuntu20.04** or that's a bug of mysqlpp v3.2.4 in mysqlpp source lib **options.cpp**

Maybe this is due to the removal of the libmysqld embedded DB server feature in MySQL 8.0.1. I follow https://tangentsoft.com/mysqlpp/tktview?name=5e73e7ddd8 replace options.cpp to solve this problem.

**Comment by shengjun1985** [comment]
inactive. close.
