### ISSUE TITLE
[Bug]: Milvus standalone fails to handle client requests.

### ISSUE THREAD

**Issue by chiru091096** [milvus-io/milvus#29742]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: latest master branch
- Deployment mode(standalone or cluster): standalone (built from source for x86)
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus - 2.3.5 (tried with various other versions too)
- OS(Ubuntu or CentOS): Ubuntu 22.04.2 LTS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I'm able to build milvus from source and run the standalone (./scripts/start_standalone.sh) which results in two milvus processes running. However trying to use the client causes issue. I tried to run this [example.py](https://github.com/milvus-io/pymilvus/blob/master/examples/example.py)(**need to change port to 19531 as 19530 fails to connect**) which results in below error.
`pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=this version of sdk is incompatible with server, please downgrade your sdk or upgrade your server)`>

I tried with various lower versions of pymilvus and above error is resolved with 2.2.8. However, instead I get below error.
```
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
status = StatusCode.UNIMPLEMENTED
details = "unknown service milvus.proto.milvus.MilvusService"
debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:19531 {created_time:"2024-01-07T17:39:40.741080501+05:30", grpc_status:12, grpc_message:"unknown service milvus.proto.milvus.MilvusService"}"
```
How can this issue be fixed.

**Comment by xiaofan-luan** [comment]
you will need to make sure you SDK version is compatible with server version.
If server is 2.3.4, latest pymilvus is recommened.
If server is 2.2.x, then think of using pymilvus 2.2.x

https://milvus.io/docs/release_notes.md#Release-Notes
![image](https://github.com/milvus-io/milvus/assets/83447078/6a41d501-4f56-4267-b677-a81f915f9a59)

each version has recommended sdk version

**Comment by chiru091096** [comment]
@xiaofan-luan 
Got it. Isn't master branch v2.x. ? Can I know what version of pymilvus I need to use with milvus standalone master branch built from source for x86?

**Comment by xiaofan-luan** [comment]
Master is 2.4
if you want to build 2.3.x, you will need to checkout tag v2.3.4.
if you want to build latest 2.3, then you need to checkout 2.3 branch

**Comment by chiru091096** [comment]
@xiaofan-luan , thanks for the information. I will do that.

**Comment by chiru091096** [comment]
@xiaofan-luan 
I freshly cloned and built milvus v2.3.4 (standalone, built from source) and when running client (using pymilvus 2.3.4) I get below error.

`pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=this version of sdk is incompatible with server, please downgrade your sdk or upgrade your server)>`

Did I miss anything or this a know bug?

**Comment by xiaofan-luan** [comment]
this is becasue your sdk version is too high.
which pymilvus and server version you are using?

**Comment by xiaofan-luan** [comment]
search for server side log

connect received

**Comment by xiaofan-luan** [comment]
it will print
"	fields := []zap.Field{
		zap.String("sdk_type", info.GetSdkType()),
		zap.String("sdk_version", info.GetSdkVersion()),
		zap.String("local_time", info.GetLocalTime()),
		zap.String("user", info.GetUser()),
		zap.String("host", info.GetHost()),
	}"

**Comment by xiaofan-luan** [comment]
if e.code() == grpc.StatusCode.UNIMPLEMENTED:
                msg = (
                    "this version of sdk is incompatible with server, "
                    "please downgrade your sdk or upgrade your server"
                )
                raise MilvusException(message=msg) from e

**Comment by xiaofan-luan** [comment]
and from the code, it's pymilvus try to access an interface not exist, so check your server version

**Comment by chiru091096** [comment]
> and from the code, it's pymilvus try to access an interface not exist, so check your server version

I can see below logs on server side (stadalone.log)

```
Welcome to use Milvus!
Version:   v2.3.4
Built:     Sunday 07 January 2024 05:56:51 PM UTC
GitCommit: 7a192da87
GoVersion: go version go1.21.5 linux/amd64
```

This is my pymilvus version

```
$ pip freeze | grep milvus
pymilvus==2.3.4
```

**Comment by xiaofan-luan** [comment]
from the log you offered

127.0.0.1:2379: connect: connection refused

you need to check your milvus pod connectivity with your etcd.

**Comment by xiaofan-luan** [comment]
if you see milvus standalone keep crashing, that is because of etcd service is not available

**Comment by chiru091096** [comment]
@xiaofan-luan ,
Thanks. I now launched etcd and minio docker and I'm able to make it work. 
I just have one question now. Is there any way to use milvus standalone without using etcd and minio containers. I mean, can I build and run etcd and minio locally and use milvus without using docker containers
