### ISSUE TITLE
[Bug]: failed to list all collections: task queue is full

### ISSUE THREAD

**Issue by hotwinters** [milvus-io/milvus#29752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.13
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):go 
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

go sdk listcollections

### Milvus Log

![Snipaste_2024-01-08_10-35-18](https://github.com/milvus-io/milvus/assets/34262412/83facf40-0411-4ab7-b0dc-30f982e50586)

### Anything else?

It has been running steadily for several months now, but for some reason, it suddenly stopped working. I deleted the database and container, but it still couldn't run properly

**Comment by hotwinters** [comment]
failed to list all collections: task queue is full

**Comment by yanliang567** [comment]
@hotwinters any chance you could upgrade to the latest milvus release v2.3.4? v2.1.8 is quite old... If it reproduces on v2.3.4, please offer full milvus logs for investigation. please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.

/assign @hotwinters
