### ISSUE TITLE
[Bug]: etcd/milvus always exit every day in docker-compose `milvus-standalone-version 2.3.4`

### ISSUE THREAD

**Issue by yinfeng2018i** [milvus-io/milvus#29778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.4
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): 
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: no limit
- GPU: no limit
- Others:
```

### Current Behavior

no operation

### Steps To Reproduce

```markdown
According to the log, etcd exits first
```

### Milvus Log

[etcd.log](https://github.com/milvus-io/milvus/files/13867896/etcd.log)
[milvus.log](https://github.com/milvus-io/milvus/files/13867897/milvus.log)

**Comment by yanliang567** [comment]
we can see many timeout logs in etcd
`{"level":"warn","ts":"2024-01-08T14:07:00.876Z","caller":"etcdserver/server.go:1159","msg":"failed to revoke lease","lease-id":"694d8cd331ae59cf","error":"etcdserver: request timed out"}`

/assign @aoiasd 
could you please help to take a look
/unassign

**Comment by yinfeng2018i** [comment]
How to solve it, deploy cluster?

**Comment by yanliang567** [comment]
are you running ssd volumes against etcd service?

**Comment by yinfeng2018i** [comment]
![image](https://github.com/milvus-io/milvus/assets/40986323/9f426307-8560-4c15-8fb1-97d743fb166d)

yes

**Comment by yinfeng2018i** [comment]
I found that there was a suspected time error, whether it was related to the time zone, and the 'server shutdown' log appeared after these two warnings

1.The picture shows the etcd and milvus time logs
![image](https://github.com/milvus-io/milvus/assets/40986323/441aaabf-565d-473d-80b4-54a717a77876)
![image](https://github.com/milvus-io/milvus/assets/40986323/dd1c0d68-da8a-44b3-80e3-d2c32dbfb43c)
2.`server shutdown` log
[error.log](https://github.com/milvus-io/milvus/files/13883528/error.log)

**Comment by aoiasd** [comment]
![image](https://github.com/milvus-io/milvus/assets/45024769/3fe6a7ec-b077-4474-9034-756f8af6f38f)

Milvus can't keep alive because etcd connect failed or very slow for a while(In this cause success etcd operation use more than 5 Second and even more failed) , so milvus kill itself.
Check the network environment or etcd docker network setting.

**Comment by aoiasd** [comment]
May relate https://github.com/milvus-io/milvus/issues/29926.
