### ISSUE TITLE
[Bug]: workernode - crashloopbackoff

### ISSUE THREAD

**Issue by nkarthik** [milvus-io/milvus#29823]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.4
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):   pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

i am using external S3 and installing milvus using 'helm'. Milvus worker node keep failing with "crashloopbackoff'

root@node2:~# kubectl get pods
NAME                                            READY   STATUS             RESTARTS        AGE
my-release-etcd-0                               1/1     Running            0               8m2s
my-release-etcd-1                               1/1     Running            0               8m2s
my-release-etcd-2                               1/1     Running            0               8m2s
my-release-milvus-datacoord-6b8f6664dc-fnsm6    0/1     CrashLoopBackOff   5 (70s ago)     4m11s
my-release-milvus-datanode-5d7784554c-jcl4b     0/1     CrashLoopBackOff   5 (81s ago)     4m13s
my-release-milvus-datanode-669cd6f5b7-z2dg5     1/1     Running            0               8m3s
my-release-milvus-indexcoord-6b9cb689ff-7cm6t   0/1     CrashLoopBackOff   5 (78s ago)     4m11s
my-release-milvus-indexnode-6c77bc588b-bg988    1/1     Running            0               8m3s
my-release-milvus-indexnode-7fb64f6fbf-p24qw    0/1     CrashLoopBackOff   5 (72s ago)     4m13s
my-release-milvus-proxy-788c57b845-tmh8q        0/1     Running            1 (3m32s ago)   8m3s
my-release-milvus-proxy-86d7f77d8f-2pzs6        0/1     CrashLoopBackOff   5 (78s ago)     4m13s
my-release-milvus-querycoord-8686dd999f-mdmt6   0/1     CrashLoopBackOff   5 (40s ago)     3m41s
my-release-milvus-querynode-56844b7b48-6ssnv    1/1     Running            0               8m3s
my-release-milvus-querynode-8594cfb4df-zdfxc    0/1     CrashLoopBackOff   5 (78s ago)     4m13s
my-release-milvus-rootcoord-67c7ddd759-jlrwb    0/1     CrashLoopBackOff   5 (62s ago)     4m5s
my-release-pulsar-bookie-0                      1/1     Running            0               8m3s
my-release-pulsar-bookie-1                      1/1     Running            0               8m3s
my-release-pulsar-bookie-2                      1/1     Running            0               8m3s
my-release-pulsar-bookie-init-25845             0/1     Completed          0               8m3s
my-release-pulsar-broker-0                      1/1     Running            0               8m3s
my-release-pulsar-broker-1                      1/1     Running            0               8m3s
my-release-pulsar-proxy-0                       1/1     Running            0               8m3s
my-release-pulsar-proxy-1                       1/1     Running            0               8m3s
my-release-pulsar-pulsar-init-65hhs             0/1     Completed          0               8m3s
my-release-pulsar-recovery-0                    1/1     Running            0               8m3s
my-release-pulsar-zookeeper-0                   1/1     Running            0               8m3s
my-release-pulsar-zookeeper-1                   1/1     Running            0               7m31s
my-release-pulsar-zookeeper-2                   1/1     Running            0               6m59s
root@node2:~#

### Expected Behavior

I would like to use milvus with external storage using HTTP. 

### Milvus Log

[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/13881273/milvus-log.tar.gz)

### Anything else?

please help me to install milvus with external S3 with http.

**Comment by yanliang567** [comment]
@nkarthik could you please share your milvus config yaml, so that we could check how to fix that?
/assign @nkarthik 
/unassign

**Comment by yanliang567** [comment]
/assign @wyfeng001 
could you please help to give a hand here?
/unassign

**Comment by wyfeng001** [comment]
Can take a look at the logs of worker nodes to see why they crashed
