### ISSUE TITLE
[Bug]: Search or query failed: segment not found: segment not loaded

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#29838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20240109-a903ae64-amd64
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):  pulsar  
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.4.0rc15
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. deploy milvus with 3 querynodes
2. create collection `fouram_KTDS31IS` with a partition_key field `int64_1` and 64 num_partitions -> build HNSW index -> insert 10m-128d data -> flush -> index again -> load collection
3. concurrent query + search + upsert + flush -> 70% search resuests failed with the following error:
```
[2024-01-09 05:07:57,697 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=503, message=failed to search: lastHB=2024-01-09 05:07:47.617667623 +0000 UTC: node offline[node=6]: channel not available[channel=delta-par-key-3-rootcoord-dml_0_446895680102072890v0])>, <Time:{'RPC start': '2024-01-09 05:07:57.504382', 'RPC error': '2024-01-09 05:07:57.696966'}> (decorators.py:134)
[2024-01-09 05:07:57,700 - ERROR - fouram]: (api_response) : <MilvusException: (code=503, message=failed to search: lastHB=2024-01-09 05:07:47.617667623 +0000 UTC: node offline[node=6]: channel not available[channel=delta-par-key-3-rootcoord-dml_0_446895680102072890v0])> (api_request.py:54)
[2024-01-09 05:07:57,700 - ERROR - fouram]: [CheckFunc] search request check failed, response:<MilvusException: (code=503, message=failed to search: lastHB=2024-01-09 05:07:47.617667623 +0000 UTC: node offline[node=6]: channel not available[channel=delta-par-key-3-rootcoord-dml_0_446895680102072890v0])> (func_check.py:48)

[2024-01-09 05:16:09,641 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=65535, message=fail to search on QueryNode 6: worker(5) query failed: segment not found: segment not loaded[segment=446895680116153030])>, <Time:{'RPC start': '2024-01-09 05:15:59.814637', 'RPC error': '2024-01-09 05:16:09.641162'}> (decorators.py:134)
[2024-01-09 05:16:09,642 - ERROR - fouram]: (api_response) : <MilvusException: (code=65535, message=fail to search on QueryNode 6: worker(5) query failed: segment not found: segment not loaded[segment=446895680116153030])> (api_request.py:54)
[2024-01-09 05:16:09,642 - ERROR - fouram]: [CheckFunc] search request check failed, response:<MilvusException: (code=65535, message=fail to search on QueryNode 6: worker(5) query failed: segment not found: segment not loaded[segment=446895680116153030])> (func_check.py:48)
[2024-01-09 05:16:09,884 - ERROR - fouram]: RPC error: [query], <MilvusException: (code=65535, message=fail to Query on QueryNode 6: worker(5) query failed: segment not found: segment not loaded[segment=446895680116153030])>, <Time:{'RPC start': '2024-01-09 05:15:59.816918', 'RPC error': '2024-01-09 05:16:09.884191'}> (decorators.py:134)
[2024-01-09 05:16:09,884 - ERROR - fouram]: (api_response) : <MilvusException: (code=65535, message=fail to Query on QueryNode 6: worker(5) query failed: segment not found: segment not loaded[segment=446895680116153030])> (api_request.py:54)
``` 
![image](https://github.com/milvus-io/milvus/assets/27288593/60b5c986-33db-4189-8e7a-fc0951ac67bc)

### Steps To Reproduce

```markdown
argo: https://argo-workflows.zilliz.cc/archived-workflows/qa/992e99aa-90bf-4eed-858e-888dfb5289b7?nodeId=delta-stable-2-3930892858
```

### Milvus Log

4am pods:
```
delta-par-key-3-etcd-0                                            1/1     Running     0               26h     10.104.28.49    4am-node33   <none>           <none>
delta-par-key-3-etcd-1                                            1/1     Running     0               26h     10.104.16.74    4am-node21   <none>           <none>
delta-par-key-3-etcd-2                                            1/1     Running     0               26h     10.104.20.19    4am-node22   <none>           <none>
delta-par-key-3-milvus-datanode-898ccb69f-cqh4z                   1/1     Running     0               26h     10.104.6.241    4am-node13   <none>           <none>
delta-par-key-3-milvus-datanode-898ccb69f-nlkk4                   1/1     Running     0               26h     10.104.5.113    4am-node12   <none>           <none>
delta-par-key-3-milvus-indexnode-56b76fd796-865nr                 1/1     Running     0               26h     10.104.32.122   4am-node39   <none>           <none>
delta-par-key-3-milvus-indexnode-56b76fd796-rj78d                 1/1     Running     0               26h     10.104.25.83    4am-node30   <none>           <none>
delta-par-key-3-milvus-mixcoord-847c5db598-fchpl                  1/1     Running     0               26h     10.104.16.82    4am-node21   <none>           <none>
delta-par-key-3-milvus-proxy-66b59fdfbd-dnjrr                     1/1     Running     0               26h     10.104.5.114    4am-node12   <none>           <none>
delta-par-key-3-milvus-querynode-66f6966d8c-jl4jm                 1/1     Running     0               26h     10.104.20.43    4am-node22   <none>           <none>
delta-par-key-3-milvus-querynode-66f6966d8c-psrnh                 1/1     Running     0               26h     10.104.15.131   4am-node20   <none>           <none>
delta-par-key-3-milvus-querynode-66f6966d8c-qhkpz                 1/1     Running     0               26h     10.104.26.53    4am-node32   <none>           <none>
delta-par-key-3-minio-0                                           1/1     Running     0               26h     10.104.32.99    4am-node39   <none>           <none>
delta-par-key-3-minio-1                                           1/1     Running     0               26h     10.104.17.249   4am-node23   <none>           <none>
delta-par-key-3-minio-2                                           1/1     Running     0               26h     10.104.25.73    4am-node30   <none>           <none>
delta-par-key-3-minio-3                                           1/1     Running     0               26h     10.104.29.46    4am-node35   <none>           <none>
delta-par-key-3-pulsar-bookie-0                                   1/1     Running     0               26h     10.104.17.252   4am-node23   <none>           <none>
delta-par-key-3-pulsar-bookie-1                                   1/1     Running     0               26h     10.104.32.105   4am-node39   <none>           <none>
delta-par-key-3-pulsar-bookie-2                                   1/1     Running     0               26h     10.104.34.189   4am-node37   <none>           <none>
delta-par-key-3-pulsar-bookie-init-tgmvj                          0/1     Completed   0               26h     10.104.1.197    4am-node10   <none>           <none>
delta-par-key-3-pulsar-broker-0                                   1/1     Running     0               26h     10.104.1.196    4am-node10   <none>           <none>
delta-par-key-3-pulsar-proxy-0                                    1/1     Running     0               26h     10.104.12.15    4am-node17   <none>           <none>
delta-par-key-3-pulsar-pulsar-init-rx98m                          0/1     Completed   0               26h     10.104.12.14    4am-node17   <none>           <none>
delta-par-key-3-pulsar-recovery-0                                 1/1     Running     0               26h     10.104.32.97    4am-node39   <none>           <none>
delta-par-key-3-pulsar-zookeeper-0                                1/1     Running     0               26h     10.104.32.103   4am-node39   <none>           <none>
delta-par-key-3-pulsar-zookeeper-1                                1/1     Running     0               26h     10.104.25.81    4am-node30   <none>           <none>
delta-par-key-3-pulsar-zookeeper-2                                1/1     Running     0               26h     10.104.18.97    4am-node25   <none>           <none>
```

### Anything else?

[grafana metrics](https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=qa-milvus&var-instance=delta-par-key-3&var-collection=All&var-app_name=milvus&from=1704771600000&to=1704808800000)

**Comment by XuanYang-cn** [comment]
/assign @weiliu1031
/unassign @congqixia 

LeaderView isn't updated.

**Comment by aoiasd** [comment]
May relate with https://github.com/milvus-io/milvus/issues/29841.

**Comment by ThreadDao** [comment]
image: master-20240118-c91254f7
error:
```
[2024-01-18 18:34:59,954 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=2, message=failed to search: service unavailable: all available nodes are unreachable)>, <Time:{'RPC start': '2024-01-18 18:34:59.331121', 'RPC error': '2024-01-18 18:34:59.954946'}> (decorators.py:134)
[2024-01-18 18:34:59,955 - ERROR - fouram]: (api_response) : <MilvusException: (code=2, message=failed to search: service unavailable: all available nodes are unreachable)> (api_request.py:54)

[2024-01-18 18:35:19,345 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=503, message=failed to search: channel lacks[channel=channel not subscribed]: channel not available[channel=chaos-level-par-key-1-rootcoord-dml_0_447111259334123393v0])>, <Time:{'RPC start': '2024-01-18 18:35:19.338146', 'RPC error': '2024-01-18 18:35:19.345349'}> (decorators.py:134)
[2024-01-18 18:35:19,345 - ERROR - fouram]: (api_response) : <MilvusException: (code=503, message=failed to search: channel lacks[channel=channel not subscribed]: channel not available[channel=chaos-level-par-key-1-rootcoord-dml_0_447111259334123393v0])> (api_request.py:54)
[2024-01-18 18:35:19,345 - ERROR - fouram]: [CheckFunc] search request check failed, response:<MilvusException: (code=503, message=failed to search: channel lacks[channel=channel not subscribed]: channel not available[channel=chaos-level-par-key-1-rootcoord-dml_0_447111259334123393v0])> (func_check.py:48)
```
- argo:  https://argo-workflows.zilliz.cc/archived-workflows/qa/34ebdee2-6e55-4685-8443-ca6577916c70?nodeId=chaos-level-par-key-1
- pods:
```
chaos-level-par-key-1-milvus-datanode-5f89859767-ns6h8      Running     0            24m     10.104.14.20      4am-node18     
chaos-level-par-key-1-milvus-datanode-5f89859767-q45fl      Running     0            24m     10.104.4.165      4am-node11     
chaos-level-par-key-1-milvus-indexnode-bc9bc98-j22hk        Running     0            24m     10.104.24.129     4am-node29     
chaos-level-par-key-1-milvus-indexnode-bc9bc98-p6rj9        Running     0            24m     10.104.16.213     4am-node21     
chaos-level-par-key-1-milvus-mixcoord-7599dcb9bb-qcpjd      Running     0            24m     10.104.4.164      4am-node11     
chaos-level-par-key-1-milvus-proxy-6579589488-2f5d8         Running     0            24m     10.104.24.128     4am-node29     
chaos-level-par-key-1-milvus-querynode-6c6555587f-jc4kq     Running     0            24m     10.104.13.17      4am-node16     
chaos-level-par-key-1-milvus-querynode-6c6555587f-phrkf     Running     0            24m     10.104.16.212     4am-node21     
chaos-level-par-key-1-milvus-querynode-6c6555587f-xzrtk     Running     0            24m     10.104.25.106     4am-node30   
```

**Comment by aoiasd** [comment]
> channel not available

Querycoord can't reassign segment in offline node, cause some segment use offline node. Was different from this case, relate: https://github.com/milvus-io/milvus/pull/30258

**Comment by aoiasd** [comment]
> image: master-20240118-c91254f7 error:
> 
> ```
> [2024-01-18 18:34:59,954 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=2, message=failed to search: service unavailable: all available nodes are unreachable)>, <Time:{'RPC start': '2024-01-18 18:34:59.331121', 'RPC error': '2024-01-18 18:34:59.954946'}> (decorators.py:134)
> [2024-01-18 18:34:59,955 - ERROR - fouram]: (api_response) : <MilvusException: (code=2, message=failed to search: service unavailable: all available nodes are unreachable)> (api_request.py:54)
> 
> [2024-01-18 18:35:19,345 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=503, message=failed to search: channel lacks[channel=channel not subscribed]: channel not available[channel=chaos-level-par-key-1-rootcoord-dml_0_447111259334123393v0])>, <Time:{'RPC start': '2024-01-18 18:35:19.338146', 'RPC error': '2024-01-18 18:35:19.345349'}> (decorators.py:134)
> [2024-01-18 18:35:19,345 - ERROR - fouram]: (api_response) : <MilvusException: (code=503, message=failed to search: channel lacks[channel=channel not subscribed]: channel not available[channel=chaos-level-par-key-1-rootcoord-dml_0_447111259334123393v0])> (api_request.py:54)
> [2024-01-18 18:35:19,345 - ERROR - fouram]: [CheckFunc] search request check failed, response:<MilvusException: (code=503, message=failed to search: channel lacks[channel=channel not subscribed]: channel not available[channel=chaos-level-par-key-1-rootcoord-dml_0_447111259334123393v0])> (func_check.py:48)
> ```
> 
> * argo:  https://argo-workflows.zilliz.cc/archived-workflows/qa/34ebdee2-6e55-4685-8443-ca6577916c70?nodeId=chaos-level-par-key-1
> * pods:
> 
> ```
> chaos-level-par-key-1-milvus-datanode-5f89859767-ns6h8      Running     0            24m     10.104.14.20      4am-node18     
> chaos-level-par-key-1-milvus-datanode-5f89859767-q45fl      Running     0            24m     10.104.4.165      4am-node11     
> chaos-level-par-key-1-milvus-indexnode-bc9bc98-j22hk        Running     0            24m     10.104.24.129     4am-node29     
> chaos-level-par-key-1-milvus-indexnode-bc9bc98-p6rj9        Running     0            24m     10.104.16.213     4am-node21     
> chaos-level-par-key-1-milvus-mixcoord-7599dcb9bb-qcpjd      Running     0            24m     10.104.4.164      4am-node11     
> chaos-level-par-key-1-milvus-proxy-6579589488-2f5d8         Running     0            24m     10.104.24.128     4am-node29     
> chaos-level-par-key-1-milvus-querynode-6c6555587f-jc4kq     Running     0            24m     10.104.13.17      4am-node16     
> chaos-level-par-key-1-milvus-querynode-6c6555587f-phrkf     Running     0            24m     10.104.16.212     4am-node21     
> chaos-level-par-key-1-milvus-querynode-6c6555587f-xzrtk     Running     0            24m     10.104.25.106     4am-node30   
> ```

Querycoord can't reassign segment in offline node, cause some segment use offline node. Was different from this case, relate: https://github.com/milvus-io/milvus/pull/30258

**Comment by XuanYang-cn** [comment]
@ThreadDao this is dup with #30150, segment not found: segment not loaded should be fixed

> image: master-20240118-c91254f7 error:
> 
> ```
> [2024-01-18 18:34:59,954 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=2, message=failed to search: service unavailable: all available nodes are unreachable)>, <Time:{'RPC start': '2024-01-18 18:34:59.331121', 'RPC error': '2024-01-18 18:34:59.954946'}> (decorators.py:134)
> [2024-01-18 18:34:59,955 - ERROR - fouram]: (api_response) : <MilvusException: (code=2, message=failed to search: service unavailable: all available nodes are unreachable)> (api_request.py:54)
> 
> [2024-01-18 18:35:19,345 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=503, message=failed to search: channel lacks[channel=channel not subscribed]: channel not available[channel=chaos-level-par-key-1-rootcoord-dml_0_447111259334123393v0])>, <Time:{'RPC start': '2024-01-18 18:35:19.338146', 'RPC error': '2024-01-18 18:35:19.345349'}> (decorators.py:134)
> [2024-01-18 18:35:19,345 - ERROR - fouram]: (api_response) : <MilvusException: (code=503, message=failed to search: channel lacks[channel=channel not subscribed]: channel not available[channel=chaos-level-par-key-1-rootcoord-dml_0_447111259334123393v0])> (api_request.py:54)
> [2024-01-18 18:35:19,345 - ERROR - fouram]: [CheckFunc] search request check failed, response:<MilvusException: (code=503, message=failed to search: channel lacks[channel=channel not subscribed]: channel not available[channel=chaos-level-par-key-1-rootcoord-dml_0_447111259334123393v0])> (func_check.py:48)
> ```
> 
> * argo:  https://argo-workflows.zilliz.cc/archived-workflows/qa/34ebdee2-6e55-4685-8443-ca6577916c70?nodeId=chaos-level-par-key-1
> * pods:
> 
> ```
> chaos-level-par-key-1-milvus-datanode-5f89859767-ns6h8      Running     0            24m     10.104.14.20      4am-node18     
> chaos-level-par-key-1-milvus-datanode-5f89859767-q45fl      Running     0            24m     10.104.4.165      4am-node11     
> chaos-level-par-key-1-milvus-indexnode-bc9bc98-j22hk        Running     0            24m     10.104.24.129     4am-node29     
> chaos-level-par-key-1-milvus-indexnode-bc9bc98-p6rj9        Running     0            24m     10.104.16.213     4am-node21     
> chaos-level-par-key-1-milvus-mixcoord-7599dcb9bb-qcpjd      Running     0            24m     10.104.4.164      4am-node11     
> chaos-level-par-key-1-milvus-proxy-6579589488-2f5d8         Running     0            24m     10.104.24.128     4am-node29     
> chaos-level-par-key-1-milvus-querynode-6c6555587f-jc4kq     Running     0            24m     10.104.13.17      4am-node16     
> chaos-level-par-key-1-milvus-querynode-6c6555587f-phrkf     Running     0            24m     10.104.16.212     4am-node21     
> chaos-level-par-key-1-milvus-querynode-6c6555587f-xzrtk     Running     0            24m     10.104.25.106     4am-node30   
> ```

/assign @ThreadDao 
/unassign @aoiasd @weiliu1031

**Comment by ThreadDao** [comment]
Fixed
