### ISSUE TITLE
[Bug]: IO failed: json: cannot unmarshal string into Go value of type map[string]interface {}

### ISSUE THREAD

**Issue by zrg-team** [milvus-io/milvus#29837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.4
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2): @zilliz/milvus2-sdk-node
- OS(Ubuntu or CentOS): MacOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/38390571/290168ea-0382-4d96-b0a4-bae1ce6d1cc4)

### Expected Behavior

Stored successfuly

### Steps To Reproduce

```markdown
const insertDatas = [
{
    langchain_text: '<?php\n' +
      '\n' +
      'use App\\Http\\Controllers\\Api\\HealthCheckController;\n' +
      'use Illuminate\\Support\\Facades\\Route;\n' +
      '\n' +
      '/*\n' +
      '|--------------------------------------------------------------------------\n' +
      '| API Routes\n' +
      '|--------------------------------------------------------------------------\n' +
      '|\n' +
      '| Here is where you can register API routes for your application. These\n' +
      '| routes are loaded by the RouteServiceProvider within a group which\n' +
      '| is assigned the "api" middleware group. Enjoy building your API!\n' +
      '|\n' +
      '*/\n' +
      "Route::any('/health-check', [HealthCheckController::class, 'index'])->name('health-check');\n",
    langchain_vector: [
       0.0031071606,  0.0025551352,      0.00460344,   -0.016425177,
       -0.012570684,  0.0016835161, 0.0000075472226,   -0.020466907,
        0.011628044, -0.0074442727,    0.0015753708,   -0.023049483,
      -0.0064725787,  0.0023436868,     0.011156724,    0.008141568,
        0.032747053, -0.0032572728,      0.01940805,   -0.023630561,
       -0.012551315,   0.027271993,     0.009200424,    0.005562221,
       -0.026703827,  0.0030877914,   -0.0055686776,   -0.016321875,
        0.014914371,  -0.014436594,     0.025309235,   -0.030551864,
        0.013326087,  -0.019072317,    -0.025593318,    0.015263018,
        0.009452225,  -0.013442303,     0.014643201,   0.0084062815,
        0.029028144,  -0.008445021,    0.0028537454,  0.00022072946,
        0.012493207,    0.03112003,   -0.0021467656, -0.00058914995,
      0.00006839789,   0.022791225,     0.011595762,    0.008548323,
       -0.050386038,  -0.003673713,     0.012564228,     0.01940805,
       -0.011247114,   0.005329789,     0.008871146,   -0.010059129,
        0.007095625, -0.0013380967,    -0.039487574,   -0.009684657,
       -0.014010469,  0.0072699487,      0.00806409,     0.03220471,
        -0.02456029,  0.0014720678,      0.02685878,   -0.019911654,
       0.0077089868,  -0.001563265,     0.019795438,    -0.02586449,
       -0.010988857,  -0.036672566,    0.0019692136,   -0.014914371,
        0.013377739,  -0.012525489,     -0.03341852,     0.02142246,
      -0.0033412066,  -0.025257584,     0.019627571,     0.03300531,
      -0.0033444348,   -0.02443116,    0.0078703975,   0.0017093419,
       0.0035155304,   0.013855515,     -0.03866115,    0.027297819,
       0.0074765547,   0.028666584,    0.0011928269,   -0.020854294,
      ... 1436 more items
    ],
    layer: 'BACKEND',
    origin: 'CODEGEN',
    module: '',
    feature: '',
    category: '',
    branch: '',
    api_id: -1,
    usecase_id: -1,
    business_logic_id: -1,
    table_definition_id: -1,
    references: '{"api_ids":[],"usecase_ids":[],"business_logic_ids":[],"table_definition_ids":[],"column_definition_ids":[]}',
    description: '',
    parameters: '{"_type":"parameters"}',
    props: '{"_type":"props"}',
    source: '/routes/api.php',
    type: 'code',
    loc: '{"lines":{"from":1,"to":17}}'
  }
]

const insertResp = await this.client.insert({
            collection_name: this.collectionName,
            fields_data: insertDatas,
});
```

**Comment by xiaofan-luan** [comment]
this seems to be a nodejs sdk issue?

**Comment by xiaofan-luan** [comment]
could you offer your server side log?

**Comment by yanliang567** [comment]
@zrg-team Could you please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.

/assign @zrg-team

**Comment by meako689** [comment]
Getting same error when trying to insert JSON field with python SDK.
local standalone deployment with official docker-compose

- pymilvus = "^2.3.5"
- milvusdb/milvus:v2.3.5
- mac OS (ARM)

error seems to appear no matter what data is being submited into json field

logs from docker compose


```
2024-01-19 15:14:37 [2024/01/19 13:14:37.274 +00:00] [WARN] [proxy/validate_util.go:349] ["insert invalid JSON data"] [data="[]"] [error="json: cannot unmarshal array into Go value of type map[string]interface {}"]
2024-01-19 15:14:37 [2024/01/19 13:14:37.275 +00:00] [WARN] [proxy/task_scheduler.go:450] ["Failed to pre-execute task: IO failed: json: cannot unmarshal array into Go value of type map[string]interface {}"] [traceID=100a481b675e38f0ce0374e3d730e646]
2024-01-19 15:14:37 [2024/01/19 13:14:37.275 +00:00] [WARN] [proxy/impl.go:2271] ["Failed to execute insert task in task scheduler: IO failed: json: cannot unmarshal array into Go value 


```



```
2024-01-19 16:11:45 [2024/01/19 14:11:45.666 +00:00] [WARN] [proxy/validate_util.go:349] ["insert invalid JSON data"] [data="[[204.8402099609375,587.0944213867188],[258.6357116699219,588.836669921875],[235.42904663085938,620.1851806640625],[210.71731567382812,648.8920288085938],[249.49220275878906,650.4305419921875]]"] [error="json: cannot unmarshal array into Go value of type map[string]interface {}"]
2024-01-19 16:11:45 [2024/01/19 14:11:45.666 +00:00] [WARN] [proxy/task_scheduler.go:450] ["Failed to pre-execute task: IO failed: json: cannot unmarshal array into Go value of type map[string]interface {}"] [traceID=1286bf2f3d90589423d6a8cb9d92ec43]
2024-01-19 16:11:45 [2024/01/19 14:11:45.666 +00:00] [WARN] [proxy/impl.go:2271] ["Failed to execute insert task in task scheduler: IO failed: json: cannot unmarshal array into Go value of type map[string]interface {}"] [traceID=1286bf2f3d90589423d6a8cb9d92ec43] [role=proxy] [db=default] [collection=faces] [partition=] [len(FieldsData)=9] [len(HashKeys)=0] [NumRows=1]
2024-01-19 16:11:50 [2024/01/19 14:11:50.446 +00:00] [INFO] [server/rocksmq_impl.go:272] ["Rocksmq stats"] [cache=96] ["rockskv memtable "=25167872] ["rockskv table readers"=0] ["rockskv pinned"=96] ["store memtable "=30410752] ["store table readers"=0] ["store pinned"=96] ["store l0 file num"=0] ["store l1 file num"=0] ["store l2 file num"=0] ["store l3 file num"=0] ["store l4 file num"=0]

```

```
2024-01-19 16:13:51 [2024/01/19 14:13:51.150 +00:00] [WARN] [proxy/validate_util.go:349] ["insert invalid JSON data"] [data="\"{}\""] [error="json: cannot unmarshal string into Go value of type map[string]interface {}"]
2024-01-19 16:13:51 [2024/01/19 14:13:51.150 +00:00] [WARN] [proxy/task_scheduler.go:450] ["Failed to pre-execute task: IO failed: json: cannot unmarshal string into Go value of type map[string]interface {}"] [traceID=820b4b7abecd67091517a56652e98e0c]
2024-01-19 16:13:51 [2024/01/19 14:13:51.150 +00:00] [WARN] [proxy/impl.go:2271] ["Failed to execute insert task in task scheduler: IO failed: json: cannot unmarshal string into Go value
```

shcema definition:

```
fields = [
    FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, auto_id=True),
    FieldSchema(name="created_at", dtype=DataType.INT64),
    FieldSchema(name="embedding", dtype=DataType.FLOAT_VECTOR, dim=512),
    FieldSchema(name="det_score", dtype=DataType.FLOAT),
    FieldSchema(name="bbox", dtype=DataType.ARRAY, max_capacity=4, element_type=DataType.FLOAT),
    FieldSchema(name="kps", dtype=DataType.JSON),
]
schema = CollectionSchema(fields=fields, enable_dynamic_field=False, description=" collection")
```

**Comment by meako689** [comment]
Getting same error with python SDK
standalone deployment via official docker-compose

- milvusdb/milvus:v2.3.5 
- pymilvus = "^2.3.5"


```
2024-01-19 16:36:52 [2024/01/19 14:36:52.296 +00:00] [WARN] [proxy/validate_util.go:349] ["insert invalid JSON data"] [data="[[204.8402099609375,587.0944213867188],[258.6357116699219,588.836669921875],[235.42904663085938,620.1851806640625],[210.71731567382812,648.8920288085938],[249.49220275878906,650.4305419921875]]"] [error="json: cannot unmarshal array into Go value of type map[string]interface {}"]
2024-01-19 16:36:52 [2024/01/19 14:36:52.296 +00:00] [WARN] [proxy/task_scheduler.go:450] ["Failed to pre-execute task: IO failed: json: cannot unmarshal array into Go value of type map[string]interface {}"] [traceID=9978073a6ca4973b25e1a2e5666d8af6]
2024-01-19 16:36:52 [2024/01/19 14:36:52.296 +00:00] [WARN] [proxy/impl.go:2271] ["Failed to execute insert task in task scheduler: IO failed: json: cannot unmarshal array into Go value
```

**Comment by zrg-team** [comment]
Log for version "2.3.7"
[milvus-standalone.log](https://github.com/milvus-io/milvus/files/14092976/milvus-standalone.log)

**Comment by congqixia** [comment]
@zrg-team 
From the error message below:
```
[2024/01/30 04:55:17.580 +00:00] [WARN] [proxy/validate_util.go:349] ["insert invalid JSON data"] [data="\"{\\\"api_ids\\\":[],\\\"usecase_ids\\\":[],\\\"business_logic_ids\\\":[],\\\"table_definition_ids\\\":[],\\\"column_definition_ids\\\":[]}\""] [error="json: cannot unmarshal string into Go value of type map[string]interface {}"]
```
The Json field is not a "Valid" json but a string. It looks like the code performing insert does not treat this json as a `JSON` but a string so the validation fails. 
Could you please kindly provide the script for insert this data?

**Comment by zrg-team** [comment]
@congqixia 
```typescript
const insertDatas = [
{
    langchain_text: '<?php\n' +
      '\n' +
      'use App\\Http\\Controllers\\Api\\HealthCheckController;\n' +
      'use Illuminate\\Support\\Facades\\Route;\n' +
      '\n' +
      '/*\n' +
      '|--------------------------------------------------------------------------\n' +
      '| API Routes\n' +
      '|--------------------------------------------------------------------------\n' +
      '|\n' +
      '| Here is where you can register API routes for your application. These\n' +
      '| routes are loaded by the RouteServiceProvider within a group which\n' +
      '| is assigned the "api" middleware group. Enjoy building your API!\n' +
      '|\n' +
      '*/\n' +
      "Route::any('/health-check', [HealthCheckController::class, 'index'])->name('health-check');\n",
    langchain_vector: [
       0.0031071606,  0.0025551352,      0.00460344,   -0.016425177,
       -0.012570684,  0.0016835161, 0.0000075472226,   -0.020466907,
        0.011628044, -0.0074442727,    0.0015753708,   -0.023049483,
      -0.0064725787,  0.0023436868,     0.011156724,    0.008141568,
        0.032747053, -0.0032572728,      0.01940805,   -0.023630561,
       -0.012551315,   0.027271993,     0.009200424,    0.005562221,
       -0.026703827,  0.0030877914,   -0.0055686776,   -0.016321875,
        0.014914371,  -0.014436594,     0.025309235,   -0.030551864,
        0.013326087,  -0.019072317,    -0.025593318,    0.015263018,
        0.009452225,  -0.013442303,     0.014643201,   0.0084062815,
        0.029028144,  -0.008445021,    0.0028537454,  0.00022072946,
        0.012493207,    0.03112003,   -0.0021467656, -0.00058914995,
      0.00006839789,   0.022791225,     0.011595762,    0.008548323,
       -0.050386038,  -0.003673713,     0.012564228,     0.01940805,
       -0.011247114,   0.005329789,     0.008871146,   -0.010059129,
        0.007095625, -0.0013380967,    -0.039487574,   -0.009684657,
       -0.014010469,  0.0072699487,      0.00806409,     0.03220471,
        -0.02456029,  0.0014720678,      0.02685878,   -0.019911654,
       0.0077089868,  -0.001563265,     0.019795438,    -0.02586449,
       -0.010988857,  -0.036672566,    0.0019692136,   -0.014914371,
        0.013377739,  -0.012525489,     -0.03341852,     0.02142246,
      -0.0033412066,  -0.025257584,     0.019627571,     0.03300531,
      -0.0033444348,   -0.02443116,    0.0078703975,   0.0017093419,
       0.0035155304,   0.013855515,     -0.03866115,    0.027297819,
       0.0074765547,   0.028666584,    0.0011928269,   -0.020854294,
      ... 1436 more items
    ],
    layer: 'BACKEND',
    origin: 'CODEGEN',
    module: '',
    feature: '',
    category: '',
    branch: '',
    api_id: -1,
    usecase_id: -1,
    business_logic_id: -1,
    table_definition_id: -1,
    references: '{"api_ids":[],"usecase_ids":[],"business_logic_ids":[],"table_definition_ids":[],"column_definition_ids":[]}',
    description: '',
    parameters: '{"_type":"parameters"}',
    props: '{"_type":"props"}',
    source: '/routes/api.php',
    type: 'code',
    loc: '{"lines":{"from":1,"to":17}}'
  }
]

const insertResp = await this.client.insert({
            collection_name: this.collectionName,
            fields_data: insertDatas,
});
```

**Comment by xiaofan-luan** [comment]
langchain_text: '<?php\n' +
      '\n' +
      'use App\\Http\\Controllers\\Api\\HealthCheckController;\n' +
      'use Illuminate\\Support\\Facades\\Route;\n' +
      '\n' +
      '/*\n' +
      '|--------------------------------------------------------------------------\n' +
      '| API Routes\n' +
      '|--------------------------------------------------------------------------\n' +
      '|\n' +
      '| Here is where you can register API routes for your application. These\n' +
      '| routes are loaded by the RouteServiceProvider within a group which\n' +
      '| is assigned the "api" middleware group. Enjoy building your API!\n' +
      '|\n' +
      '*/\n' +
      "Route::any('/health-check', [HealthCheckController::class, 'index'])->name('health-check');\n"

**Comment by xiaofan-luan** [comment]
this seems not a valid string

**Comment by zrg-team** [comment]
@xiaofan-luan it no promblem with string. It just combine string with "+"
```
'<?php\n' +
      '\n' +
      'use App\\Http\\Controllers\\Api\\HealthCheckController;\n' +
      'use Illuminate\\Support\\Facades\\Route;\n' +
      '\n' +
      '/*\n' +
      '|--------------------------------------------------------------------------\n' +
      '| API Routes\n' +
      '|--------------------------------------------------------------------------\n' +
      '|\n' +
      '| Here is where you can register API routes for your application. These\n' +
      '| routes are loaded by the RouteServiceProvider within a group which\n' +
      '| is assigned the "api" middleware group. Enjoy building your API!\n' +
      '|\n' +
      '*/\n' +
      "Route::any('/health-check', [HealthCheckController::class, 'index'])->name('health-check');\n"
```

**Comment by zrg-team** [comment]
No i don't it raw text.
```
references: '{"api_ids":[],"usecase_ids":[],"business_logic_ids":[],"table_definition_ids":[],"column_definition_ids":[]}',
description: '',
parameters: '{"_type":"parameters"}',
props: '{"_type":"props"}',
source: '/routes/api.php',
type: 'code',
loc: '{"lines":{"from":1,"to":17}}'
```

**Comment by xiaofan-luan** [comment]
this is not the same string you send right. 
please try to use http://json.parser.online.fr/ and validate the json you generate is valid

**Comment by xiaofan-luan** [comment]
from our error message, golang can not parse your data so there is nothing we can do. Sorry about it

**Comment by xiaofan-luan** [comment]
[
  {
    "langchain_text": "<?php\n\nuse App\\Http\\Controllers\\Api\\HealthCheckController;\nuse Illuminate\\Support\\Facades\\Route;\n\n/*\n|--------------------------------------------------------------------------\n| API Routes\n|--------------------------------------------------------------------------\n|\n| Here is where you can register API routes for your application. These\n| routes are loaded by the RouteServiceProvider within a group which\n| is assigned the \"api\" middleware group. Enjoy building your API!\n|\n*/\nRoute::any('/health-check', [HealthCheckController::class, 'index'])->name('health-check');\n",
    "langchain_vector": [
      0.0031071606,
      0.0025551352,
      0.00460344,
      -0.016425177,
      -0.012570684,
      0.0016835161,
      0.0000075472226,
      -0.020466907,
      0.011628044,
      -0.0074442727,
      0.0015753708,
      -0.023049483,
      -0.0064725787,
      0.0023436868,
      0.011156724,
      0.008141568,
      0.032747053,
      -0.0032572728,
      0.01940805,
      -0.023630561,
      -0.012551315,
      0.027271993,
      0.009200424,
      0.005562221,
      -0.026703827,
      0.0030877914,
      -0.0055686776,
      -0.016321875,
      0.014914371,
      -0.014436594,
      0.025309235,
      -0.030551864,
      0.013326087,
      -0.019072317,
      -0.025593318,
      0.015263018,
      0.009452225,
      -0.013442303,
      0.014643201,
      0.0084062815,
      0.029028144,
      -0.008445021,
      0.0028537454,
      0.00022072946,
      0.012493207,
      0.03112003,
      -0.0021467656,
      -0.00058914995,
      0.00006839789,
      0.022791225,
      0.011595762,
      0.008548323,
      -0.050386038,
      -0.003673713,
      0.012564228,
      0.01940805,
      -0.011247114,
      0.005329789,
      0.008871146,
      -0.010059129,
      0.007095625,
      -0.0013380967,
      -0.039487574,
      -0.009684657,
      -0.014010469,
      0.0072699487,
      0.00806409,
      0.03220471,
      -0.02456029,
      0.0014720678,
      0.02685878,
      -0.019911654,
      0.0077089868,
      -0.001563265,
      0.019795438,
      -0.02586449,
      -0.010988857,
      -0.036672566,
      0.0019692136,
      -0.014914371,
      0.013377739,
      -0.012525489,
      -0.03341852,
      0.02142246,
      -0.0033412066,
      -0.025257584,
      0.019627571,
      0.03300531,
      -0.0033444348,
      -0.02443116,
      0.0078703975,
      0.0017093419,
      0.0035155304,
      0.013855515,
      -0.03866115,
      0.027297819,
      0.0074765547,
      0.028666584,
      0.0011928269
    ],
    "layer": "BACKEND",
    "origin": "CODEGEN",
    "module": "",
    "feature": "",
    "category": "",
    "branch": "",
    "api_id": -1,
    "usecase_id": -1,
    "business_logic_id": -1,
    "table_definition_id": -1,
    "references": "{\"api_ids\":[],\"usecase_ids\":[],\"business_logic_ids\":[],\"table_definition_ids\":[],\"column_definition_ids\":[]}",
    "description": "",
    "parameters": "{\"_type\":\"parameters\"}",
    "props": "{\"_type\":\"props\"}",
    "source": "/routes/api.php",
    "type": "code",
    "loc": "{\"lines\":{\"from\":1,\"to\":17}}"
  }
]

**Comment by xiaofan-luan** [comment]
try to use this json see if we see if you still hit the same issue

**Comment by xiaofan-luan** [comment]
The reason is the json 

> try to use this json see if we see if you still hit the same issue

From the log, the error json 

{\\\"api_ids\\\":[],\\\"usecase_ids\\\":[],\\\"business_logic_ids\\\":[],\\\"table_definition_ids\\\":[],\\\"column_definition_ids\\\":[]}

I don't know what the original json insert is, maybe you add some extra ""

**Comment by xiaofan-luan** [comment]
> Getting same error with python SDK standalone deployment via official docker-compose
> 
> * milvusdb/milvus:v2.3.5
> * pymilvus = "^2.3.5"
> 
> ```
> 2024-01-19 16:36:52 [2024/01/19 14:36:52.296 +00:00] [WARN] [proxy/validate_util.go:349] ["insert invalid JSON data"] [data="[[204.8402099609375,587.0944213867188],[258.6357116699219,588.836669921875],[235.42904663085938,620.1851806640625],[210.71731567382812,648.8920288085938],[249.49220275878906,650.4305419921875]]"] [error="json: cannot unmarshal array into Go value of type map[string]interface {}"]
> 2024-01-19 16:36:52 [2024/01/19 14:36:52.296 +00:00] [WARN] [proxy/task_scheduler.go:450] ["Failed to pre-execute task: IO failed: json: cannot unmarshal array into Go value of type map[string]interface {}"] [traceID=9978073a6ca4973b25e1a2e5666d8af6]
> 2024-01-19 16:36:52 [2024/01/19 14:36:52.296 +00:00] [WARN] [proxy/impl.go:2271] ["Failed to execute insert task in task scheduler: IO failed: json: cannot unmarshal array into Go value
> ```

we support only json map

it should be [{'a':1}{'b':1}{'c':1}]

**Comment by zrg-team** [comment]
@xiaofan-luan you mean we can not store ?
'{"api_ids":[],"usecase_ids":[],"business_logic_ids":[],"table_definition_ids":[],"column_definition_ids":[]}'

Weird it worked well before ^2.3.3

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan you mean we can not store ?
> 
> ```
> '{"api_ids":[],"usecase_ids":[],"business_logic_ids":[],"table_definition_ids":[],"column_definition_ids":[]}'
> ```
> 
> Weird it worked well before ^2.3.3
> 
> Do we have any plan to support it ? and can we store as below instead ?
> 
> ```
> [{'key': 'api_ids', data: [1, 2, 3]}{'key': 'usecase_ids', data: []}]
> ```

yep we actually add more checks. to the data strucutre.

because if it's an array then milvus could not search on it

**Comment by zrg-team** [comment]
@xiaofan-luan thanks for fast reply. I didn't tested yet but would it support, nested level ? 
```
[{'key': 'api_ids', data: [1, 2, 3]}{'key': 'usecase_ids', data: []}]
```
Like data: can be object or array ?

**Comment by zrg-team** [comment]
@xiaofan-luan
It is a critical change. We can not update our Milvus to version higher than v1.3.3 Do we have any plan to be backward compatible? it is ok to not support query on JSON field if that is not a map

**Comment by xiaocai2333** [comment]
@zrg-team  Could you please specify your requirements?

 We indeed implemented some more detailed checks after a certain version. Because even if you insert some data, it might not pass the expression filtering.

Are you also only interested in inserting and retrieving?

**Comment by zrg-team** [comment]
@xiaocai2333 
`<v1.3.3` it is supported to store columns with free JSON type. Example:
references: { ids: [1, 3, 4], text: 'hello' }
But from `>v1.3.3`
If we store the same structure of data it will throw 
```
2024-01-19 16:36:52 [2024/01/19 14:36:52.296 +00:00] [WARN] [proxy/task_scheduler.go:450] ["Failed to pre-execute task: IO failed: json: cannot unmarshal array into Go value of type map[string]interface {}"] [traceID=9978073a6ca4973b25e1a2e5666d8af6]
2024-01-19 16:36:52 [2024/01/19 14:36:52.296 +00:00] [WARN] [proxy/impl.go:2271] ["Failed to execute insert task in task scheduler: IO failed: json: cannot unmarshal array into Go value
```
It blocked us from upgrading to a newer version.
So my point is it great if we could continue to support free JSON. Even can not query on that field

**Comment by xiaocai2333** [comment]
@zrg-team Got it, we will support free-form JSON in the new version, and it will also be filterable.
follow the issue: #31051 

Before v2.3.3, we only support JSON data in key-value pair format, but forgot to check the inserted data. This was fixed in v2.3.3.

**Comment by zrg-team** [comment]
Thank you @xiaocai2333

**Comment by xiaocai2333** [comment]
You can upgrade to v2.4.0-rc1 or wait until v2.4.0 is released soon.
/close

**Comment by zrg-team** [comment]
@xiaocai2333 thanks. We will do testing now

**Comment by stay-leave** [comment]
Previously, there wasn't a strict approach to constructing JSON data, as some fields contained values that were both JSON and strings. However, now there's a need to construct strictly formatted JSON data.
