### ISSUE TITLE
[Bug]: [groupBy] results are not same if searching with groupby PK and searching with no groupby

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#29883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20240109-60e88fb8-amd64
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):   
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.4.0rc19
```

### Current Behavior

1. results are not same if searching with group by pk and searching by no groupby

### Expected Behavior

1. the results are same

### Steps To Reproduce

```markdown
1. create a collection and insert 3000 vectors
2. build hnsw, L2 index
3. search with group by pk and search with no group by
```

### Milvus Log

res1 = collection_w.search(data=search_vectors, anns_field=ct.default_float_vec_field_name,
                                     param=search_params, limit=10,
                                     group_by_field=ct.default_int64_field_name)
res2 = collection_w.search(data=search_vectors, anns_field=ct.default_float_vec_field_name,
                                    param=search_params, limit=10)
assert res1 == res2

**Comment by xiaofan-luan** [comment]
how often does this happen?

can we list top10 result and compare?

Ideally there is no strong guarantee groupby get exact same result as topn but it should be very similar

**Comment by yanliang567** [comment]
1. I manually called flush() after insert 30*100 vectors
2. sleep 30s before load
3. it repros 50%, the pk are:
[446898203710803026, 446898203710801363, 446898203710802590, 446898203710801634, 446898203710802924, 446898203710801600, 446898203710801744, 446898203710801845, 446898203710802285, 446898203710802316] != 
[446898203710803026, 446898203710801363, 446898203710802590, 446898203710801634, 446898203710802924,
 446898203710801587, 446898203710802588, 446898203710801600, 446898203710801744, 446898203710801359]

**Comment by xiaofan-luan** [comment]
> 1. I manually called flush() after insert 30*100 vectors
> 2. sleep 30s before load
> 3. it repros 50%, the pk are:
>    [446898203710803026, 446898203710801363, 446898203710802590, 446898203710801634, 446898203710802924, 446898203710801600, 446898203710801744, 446898203710801845, 446898203710802285, 446898203710802316] !=
>    [446898203710803026, 446898203710801363, 446898203710802590, 446898203710801634, 446898203710802924,
>    446898203710801587, 446898203710802588, 446898203710801600, 446898203710801744, 446898203710801359]

Can we print the score of each vector? Just need some rough guess about is it reasonable.

Because the current iteration monotonicity is not strict, it might a bug not. 
Another guess is that although flush is done index build is done.

**Comment by yanliang567** [comment]
But I don't think it is reasonable if the results are different when searching with groupby PK and with no groupby

**Comment by xiaofan-luan** [comment]
> But I don't think it is reasonable if the results are different when searching with groupby PK and with no groupby

Let's first check what happened, might be simply because flushed segment didn't build index yet.

but anyway since the implementation is different there is no ganruatee that the returned result is exactly similiar

**Comment by yanliang567** [comment]
BTW, if using binary vectors, the top10 are totally different, which seems to zoom in on the issue

**Comment by xiaofan-luan** [comment]
> BTW, if using binary vectors, the top10 are totally different, which seems to zoom in on the issue

emm, do we support binary vector on hnsw?

**Comment by yanliang567** [comment]
> > BTW, if using binary vectors, the top10 are totally different, which seems to zoom in on the issue
> 
> emm, do we support binary vector on hnsw?

yes, we do

**Comment by MrPresent-Han** [comment]
Currently, knowhere iterator doesn't guarantee the stability of the output. So the top100 output of knowhere iterator cannot be promised identical to search top100

**Comment by yanliang567** [comment]
@xiaofan-luan @MrPresent-Han Additional, I found that not every entity in groupby results is the top1 for that value of the group_by_field(it usually reproduces around top10 of the groupby results)

**Comment by yanliang567** [comment]
one more test:
1. insert 1 million 128d vectors
2. build HNSW index {"index_type": "HNSW", "metric_type": metric, "params": {"M": 32, "efConstruction": 256}}
3. load
4. wait for compaction completed
5. search with groupby PK topk=10
6. search with no groupby topk=10

results:
1. only 2 of them are same {447392587460059090, 447392587460052492}
2. results with no groupby has more accurate results(closer distance)
res_grpby:
['id: 447392587460059090, distance: 0.33108294010162354, entity: {}', 'id: 447392587460052492, distance: 0.3343840539455414, entity: {}', 'id: 447392587459743941, distance: 0.33855530619621277, entity: {}', 'id: 447392587460245799, distance: 0.34074312448501587, entity: {}', 'id: 447392587460049729, distance: 0.3445034325122833, entity: {}', 'id: 447392587460140060, distance: 0.34654510021209717, entity: {}', 'id: 447392587459646698, distance: 0.347501277923584, entity: {}', 'id: 447392587459891108, distance: 0.347683846950531, entity: {}', 'id: 447392587459670281, distance: 0.35074102878570557, entity: {}', 'id: 447392587460003669, distance: 0.3519127368927002, entity: {}']
res_no_grpby:
['id: 447392587460103744, distance: 0.3203863501548767, entity: {}', 'id: 447392587459946963, distance: 0.3204832971096039, entity: {}', 'id: 447392587460023605, distance: 0.32055485248565674, entity: {}', 'id: 447392587459964554, distance: 0.3248538374900818, entity: {}', 'id: 447392587459409046, distance: 0.3254329264163971, entity: {}', 'id: 447392587460048447, distance: 0.3263985216617584, entity: {}', 'id: 447392587460059090, distance: 0.33108294010162354, entity: {}', 'id: 447392587460270111, distance: 0.33117109537124634, entity: {}', 'id: 447392587460032570, distance: 0.33267897367477417, entity: {}', 'id: 447392587460052492, distance: 0.3343840539455414, entity: {}']

**Comment by yanliang567** [comment]
7. search with nq=10, only 55/100 ids are same.

**Comment by yanliang567** [comment]
on master-20240221-77eb6def with 1m(500*2000_grpby_fields) and limit=100, 
1. if searching with grouby PK, the groupby results is >95% same with results of searching with no groupby
2. if searching with expr="grpby_field==grpby_field_top1_value", the correct rate is around 70%-80%
The #2 is not good enough.

**Comment by yanliang567** [comment]
close for now as the comments above
