### ISSUE TITLE
Server crashes when frequently inserting, deleting and searching

### ISSUE THREAD

**Issue by csjiangwm** [milvus-io/milvus#2993]
我们维护大概25w x 512d的向量库，会频繁进行插入，删除，和查询操作，milvus服务会偶尔崩溃。

**Comment by tinkerlin** [comment]
Thank you for filing an issue with Milvus. But, could we ask you to describe your issue in English instead?

Milvus has an international team of developers and quite many of them cannot read Chinese. Issues written in English usually get fixed much faster than in other languages. So, we would appreciate it if you can reiterate your issue in English.

Many thanks,
Milvus developer team

**Comment by shengjun1985** [comment]
＠csjiangwm
Would you like to provide more information, such as Milvus server version, CPU or GPU, index_file_size, index_type and so on?

**Comment by csjiangwm** [comment]
> ＠csjiangwm
> Would you like to provide more information, such as Milvus server version, CPU or GPU, index_file_size, index_type and so on?

there are no more problems when I upgrade the milvus 0.8.0 to 0.10.0, thanks.
