### ISSUE TITLE
Override insert has no effect

### ISSUE THREAD

**Issue by csjiangwm** [milvus-io/milvus#2994]
我们插入多个同样id的向量后，系统中向量会同时存在，通过get_id来获取向量为最近一次上传的向量，但是通过search来进行向量搜索时，前几次id的向量同样会参与搜索

**Comment by tinkerlin** [comment]
Thank you for filing an issue with Milvus. But, could we ask you to describe your issue in English instead?

Milvus has an international team of developers and quite many of them cannot read Chinese. Issues written in English usually get fixed much faster than in other languages. So, we would appreciate it if you can reiterate your issue in English.

Many thanks,
Milvus developer team

**Comment by tinkerlin** [comment]
refer to #2545

**Comment by csjiangwm** [comment]
> refer to #2545

thanks
