### ISSUE TITLE
[Bug]: milvus v2.3.4 crashes after connecting with attu

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus#29956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.3.4
```

### Current Behavior

milvus crashes. 

```bash

 GET 200 /api/v1/milvus/metrics 27.409 ms @ Fri, 12 Jan 2024 23:34:20 GMT ::ffff:127.0.0.1 from http://localhost:3001/ Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

ws client connected ::ffff:127.0.0.1

 GET 304 /api/v1/collections 45.194 ms @ Fri, 12 Jan 2024 23:34:20 GMT ::ffff:127.0.0.1 from http://localhost:3001/ Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

GET /api/v1/users/roles 500 fail to select the role

 GET 304 /api/v1/milvus/metrics 21.025 ms @ Fri, 12 Jan 2024 23:34:23 GMT ::ffff:127.0.0.1 from http://localhost:3001/ Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36


 GET 200 /api/v1/users 10021.845 ms @ Fri, 12 Jan 2024 23:34:30 GMT ::ffff:127.0.0.1 from http://localhost:3001/ Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

GET /api/v1/users/roles 500 fail to select the role

 GET 500 /api/v1/users/roles 10029.064 ms @ Fri, 12 Jan 2024 23:34:30 GMT ::ffff:127.0.0.1 from http://localhost:3001/ Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

GET /api/v1/collections/statistics 500 Error: 14 UNAVAILABLE: No connection established
```

### Steps To Reproduce

```markdown
1. create v2.3.4 standalone
2. do nothing
3. connect it with attu
4. click some pages
5. it crashes
```

### Milvus Log

https://grafana-4am.zilliz.cc/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bpod%3D%5C%22node2344test-eqkhk-milvus-standalone-86475574d9-h5lxq%5C%22%7D%22,%22hide%22:true%7D,%7B%22refId%22:%22B%22,%22expr%22:%22%7Bpod%3D%5C%22node2344test-eqkhk-milvus-standalone-86475574d9-h5lxq%5C%22%7D%7C~%5C%22%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%22now-3h%22,%22to%22:%22now%22%7D%7D

### Anything else?

This happened on a fresh installed milvus, 

not sure if it is the same issue https://github.com/milvus-io/milvus/issues/29944, this one was running for days.

**Comment by czs007** [comment]
![image](https://github.com/milvus-io/milvus/assets/59249785/15f0bf83-a7c0-4479-8eea-a81ada2ce2c5)
Could you please verify if our deployment of etcd is correct?

**Comment by czs007** [comment]
@longjiquan  confirm if this issue still exists
