### ISSUE TITLE
[Bug]: log for mixture type

### ISSUE THREAD

**Issue by didalaviva** [milvus-io/milvus#29969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

when I run mivlus with command:  ./milvus run mixture -rootcoord=true -proxy=true ...
to start all roles, my log dir is  /tmp ,  I found the log file is  /tmp/-0.log , In the code the file name type is [rolename]-[id].log,  It likely there is no rolename for mixture

### Expected Behavior

since the /tmp/-0.log can not be opened, can I get some meaningful log name

### Steps To Reproduce

```markdown
Linux
config file milvus.yaml: 
log:
   rootpath: /tmp/
   ...


./milvus run mixture -rootcoord=true -proxy=true
```

### Milvus Log

the log file
/tmp/-0.log
and it cannot be opened

### Anything else?

no

**Comment by sunby** [comment]
@didalaviva Thanks for your bug report, Indeed it's a bug and I will fix it.
/assign
