### ISSUE TITLE
[Bug]: [groupBy] fail to search if groupby a indexed varchar field 

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#29965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20240109-60e88fb8-amd64
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):   
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.4.0rc19
```

### Current Behavior

Fail to search if searching groupby an indexed varchar field. If the varchar field has no index, it search successfully with groupby the varchar field.
`<MilvusException: (code=65535, message=fail to search on QueryNode 1: worker(1) query failed: Assert "get_bit(field_data_ready_bitset_, field_id)" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:622
`

### Expected Behavior

search successfully.

### Steps To Reproduce

```markdown
1. create a collection and insert data
2. index the vector field and the varchar field
3. load
4. search with groupby the varchar field

it reproduces not only for varchar fileds, but also for the other fields such as Int
```

### Milvus Log

pod name on 4am cluster:
`yanliang-grb-milvus-standalone-6cc694668b-bjxdz                   1/1     Running     0               5d1h    10.104.9.98     4am-node14   <none>           <none>`

**Comment by xiaofan-luan** [comment]
good catch.
We need retrieve from index

**Comment by MrPresent-Han** [comment]
/assign [yanliang567](https://github.com/yanliang567)
please help verify this change

**Comment by yanliang567** [comment]
search successfully now, but the results are not perfect enough, tracking in #30309 29883
