### ISSUE TITLE
[Feature]: Bitmap index supported

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#29960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

https://en.wikipedia.org/wiki/Bitmap_index

bitmap could be very efficient for low cardinality data like date and enums.
We can add bitmap index on numeric numbers and special field of JSON, this would greatly improve the filtering speed.

**Comment by czs007** [comment]
@zhagnlu can we close this?
