### ISSUE TITLE
[Bug]: deadlock on datanode's blockAll logic

### ISSUE THREAD

**Issue by weiliu1031** [milvus-io/milvus#29970]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.3
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. data node consume_delete_tt  is normal while deleting date
2. Auto Sync is blocked
3. UpdateChannelCheckpoint is blocked.

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version: 2.3.3
> - Deployment mode(standalone or cluster):
> - MQ type(rocksmq, pulsar or kafka):    
> - SDK version(e.g. pymilvus v2.0.0rc2):
> - OS(Ubuntu or CentOS): 
> - CPU/Memory: 
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> 1. data node consume_delete_tt  is normal while deleting date
> 2. Auto Sync is blocked
> 3. UpdateChannelCheckpoint is blocked.
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

1. why do UpdateChannelCheckpoint relelated to flowgraph lock?
By design, flowgraph lock is a mutex go guard flowgraph consumpation and compaction . It should has nothing to do with UpdateChannelCheckpoint

**Comment by chyezh** [comment]
maybe related to: #29245?

**Comment by weiliu1031** [comment]
> > ### Is there an existing issue for this?
> > 
> > * [x]   I have searched the existing issues
> > 
> > ### Environment
> > ```
> > - Milvus version: 2.3.3
> > - Deployment mode(standalone or cluster):
> > - MQ type(rocksmq, pulsar or kafka):    
> > - SDK version(e.g. pymilvus v2.0.0rc2):
> > - OS(Ubuntu or CentOS): 
> > - CPU/Memory: 
> > - GPU: 
> > - Others:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Current Behavior
> > 
> > 1. data node consume_delete_tt  is normal while deleting date
> > 2. Auto Sync is blocked
> > 3. UpdateChannelCheckpoint is blocked.
> > 
> > ### Expected Behavior
> > _No response_
> > ### Steps To Reproduce
> > _No response_
> > ### Milvus Log
> > _No response_
> > ### Anything else?
> > _No response_
> 
> 1. why do UpdateChannelCheckpoint relelated to flowgraph lock?
>    By design, flowgraph lock is a mutex go guard flowgraph consumpation and compaction . It should has nothing to do with UpdateChannelCheckpoint

![image](https://github.com/milvus-io/milvus/assets/108661493/7dcc7a3d-44e2-48a7-a96c-d1b3c36730e5)
![image](https://github.com/milvus-io/milvus/assets/108661493/eff4e7f2-146a-42f8-ba91-c2b7040edddd)

when ttNode call `Operate`, it will trigger `updateChannelCP`

**Comment by xiaofan-luan** [comment]
> > > ### Is there an existing issue for this?
> > > 
> > > * [x]    I have searched the existing issues
> > > 
> > > ### Environment
> > > ```
> > > - Milvus version: 2.3.3
> > > - Deployment mode(standalone or cluster):
> > > - MQ type(rocksmq, pulsar or kafka):    
> > > - SDK version(e.g. pymilvus v2.0.0rc2):
> > > - OS(Ubuntu or CentOS): 
> > > - CPU/Memory: 
> > > - GPU: 
> > > - Others:
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ### Current Behavior
> > > 
> > > 1. data node consume_delete_tt  is normal while deleting date
> > > 2. Auto Sync is blocked
> > > 3. UpdateChannelCheckpoint is blocked.
> > > 
> > > ### Expected Behavior
> > > _No response_
> > > ### Steps To Reproduce
> > > _No response_
> > > ### Milvus Log
> > > _No response_
> > > ### Anything else?
> > > _No response_
> > 
> > 
> > 
> > 1. why do UpdateChannelCheckpoint relelated to flowgraph lock?
> >    By design, flowgraph lock is a mutex go guard flowgraph consumpation and compaction . It should has nothing to do with UpdateChannelCheckpoint
> 
> ![image](https://private-user-images.githubusercontent.com/108661493/296638933-7dcc7a3d-44e2-48a7-a96c-d1b3c36730e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyODgyMzgsIm5iZiI6MTcwNTI4NzkzOCwicGF0aCI6Ii8xMDg2NjE0OTMvMjk2NjM4OTMzLTdkY2M3YTNkLTQ0ZTItNDhhNy1hOTZjLWQxYjNjMzY3MzBlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQwMzA1MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNmY0MjY1MzA2NDYxYmVmYjhkNjViOWQ5ZmM1OWQyNmYwYmMzZmEyZDI3OTk2MzA5MDE0NDNkMTUwOTI1YzEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AkGZrRJzip_vXC0Equ5J-_IW8e3rsEHjjr9H7OcWcag) ![image](https://private-user-images.githubusercontent.com/108661493/296639163-eff4e7f2-146a-42f8-ba91-c2b7040edddd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyODgyMzgsIm5iZiI6MTcwNTI4NzkzOCwicGF0aCI6Ii8xMDg2NjE0OTMvMjk2NjM5MTYzLWVmZjRlN2YyLTE0NmEtNDJmOC1iYTkxLWMyYjcwNDBlZGRkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQwMzA1MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZWFmNDlkMGVkYTdjMzhmYTU5NjY5MThmNGEzNjM0MTBjMjhiYWE0MmM0OWIwOWFlZDI4ZjU4MDRiNzUzZTY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BkfvJRduqoo9RgZWTtnM5q39XfNfY_Vjmr544qWuydg)
> 
> when ttNode call `Operate`, it will trigger `updateChannelCP`

when the Operate, it actually hold the lock

**Comment by xiaofan-luan** [comment]
could this be:

Compaction -> wait for get the blockAll due to the flush
Flush ->  for some reason, it blocked(might be memory full?) usually this should not be a blocking 

So the overall reason might be flush can not be succesful under some cases

**Comment by weiliu1031** [comment]
> could this be:
> 
> Compaction -> wait for get the blockAll due to the flush Flush -> for some reason, it blocked(might be memory full?) usually this should not be a blocking
> 
> So the overall reason might be flush can not be succesful under some cases

![image](https://github.com/milvus-io/milvus/assets/108661493/e4cc6eb0-92ee-4009-b771-9ae68942fc6f)
it's ralated to #29245, the first SyncSegment call BlockAll, and stuck at `insert_buffer_node`, and which takes 15s. before the first `BlockAll` func call finished, the second SyncSegment request arrive, which trigger another `BlockAll` func call. 

then the concurrent `BlockAll` may causes dead lock to the random iterate order of map
![image](https://github.com/milvus-io/milvus/assets/108661493/3965d9f1-b09a-4b89-9493-b4e62fe676c7)
