### ISSUE TITLE
Suggest to use "topk" instead of "topK".

### ISSUE THREAD

**Issue by AmyYH** [milvus-io/milvus#2998]
**Please state you issue using the following template and, most importantly, in English.**

**Location of incorrect documentation**
For example, [Index Types/HNSW](https://milvus.io/docs/v0.10.0/index.md#HNSW).

**Describe the problems or issues found in the documentation**
A clear and concise description of what you found to be incorrect.

**Steps taken to verify documentation is incorrect**
List any steps you have taken:

**Suggested fix for documentation**
For consistency, suggest to use "topk" across the documentation.

---

## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken:

**Comment by JinHai-CN** [comment]
This document is under repo: https://github.com/milvus-io/docs
