### ISSUE TITLE
[Feature]: support fuzzy matching, not only prefix matching

### ISSUE THREAD

**Issue by tiandidoushidali** [milvus-io/milvus#29988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

i faced a problem, we want to fuzzy match a filed, but now ,only support prefix matching

**Comment by mokeyish** [comment]
> @tiandidoushidali could you explain what is the use case while fuzzy matching is a must?
> 
> even if milvus supoort wildcard matching, it might be still very slow(Like mysql support Like but it's super slow)
> 
> So I need to know more details on why this is a must.

In my case, I need to do keyword filter before vector similarity search.

**Comment by xiaofan-luan** [comment]
By asking fuzzy match, does that mean
Like %ABC% or calculate  levenshtein distance to find fuzzy similarity between "abc" and "acb"

**Comment by mokeyish** [comment]
just `Like %ABC%`

**Comment by xiaofan-luan** [comment]
This on our feature list of 2.4.
But honestly speaking, even with index, this search pattern is gonna to really bad.

With our test, each core can only run 28QPS 1million dataset for queries Like %ABC%

**Comment by mokeyish** [comment]
I think the feature must be there first, and as for performance, that is a follow-up matter. The amount of data is not large and the difference is not obvious.

**Comment by yiwen92** [comment]
> mokeyish

We have supported fuzzy matching and inverted indexing in milvus 2.4.0, please try it and give us feedback, thanks!

**Comment by xiaofan-luan** [comment]
close it for now.
Any comments is welcomed
