### ISSUE TITLE
Qps descreased if using multi clients comparing with using single client

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#2999]
**Please state you issue using the following template and, most importantly, in English.**

**Describe the bug**
single connection:

```
11:42:13  [2020-07-24 03:42:12,829] test-benchmark-milvus-benchmark-0.10.2-6-m909l-wgq73/INFO/locust.main: Running teardowns...
11:42:13   Name                                                          # reqs      # fails     Avg     Min     Max  |  Median   req/s failures/s
11:42:13  --------------------------------------------------------------------------------------------------------------------------------------------
11:42:13   grpc query                                                    347135     0(0.00%)      60       2     885  |      56 1145.28    0.00
11:42:13  --------------------------------------------------------------------------------------------------------------------------------------------
11:42:13   Aggregated                                                    347135     0(0.00%)      60       2     885  |      56 1145.28    0.00
11:42:13  
11:42:13  Percentage of the requests completed within given times
11:42:13   Type                 Name                                                           # reqs    50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100%
11:42:13  ------------------------------------------------------------------------------------------------------------------------------------------------------
11:42:13   grpc                 query                                                          347135     56     69     79     86    100    120    140    150    180    230    880
11:42:13  ------------------------------------------------------------------------------------------------------------------------------------------------------
11:42:13   None                 Aggregated                                                     347135     56     69     79     86    100    120    140    150    180    230    880
```

multi connections:
```
11:23:57  [2020-07-24 03:23:57,343] test-benchmark-milvus-benchmark-0.10.2-5-28h2v-4t695/INFO/locust.main: Running teardowns...
11:23:57   Name                                                          # reqs      # fails     Avg     Min     Max  |  Median   req/s failures/s
11:23:57  --------------------------------------------------------------------------------------------------------------------------------------------
11:23:57   grpc query                                                    108653     0(0.00%)      39       2     805  |      38  359.85    0.00
11:23:57  --------------------------------------------------------------------------------------------------------------------------------------------
11:23:57   Aggregated                                                    108653     0(0.00%)      39       2     805  |      38  359.85    0.00
11:23:57  
11:23:57  Percentage of the requests completed within given times
11:23:57   Type                 Name                                                           # reqs    50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100%
11:23:57  ------------------------------------------------------------------------------------------------------------------------------------------------------
11:23:57   grpc                 query                                                          108653     38     42     45     48     56     64     72     78     95    110    800
11:23:57  ------------------------------------------------------------------------------------------------------------------------------------------------------
11:23:57   None                 Aggregated                                                     108653     38     42     45     48     56     64     72     78     95    110    800
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
0.10.1/2

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
Test with 0.10.2/0.10.3/0.10.4
Collection: index_file_size=256M, insert 1000000 vectors, 128 dimensional
Index: IVF_FLAT nlist=2048
Search parameter: nq=1, topk=10, nprobe=32

**0.10.4**
insert 100w: 12.5 sec
create IVF_FLAT index: 105.5 sec

single thread search 10000 times:
	total cost: 37.05250430107117 average: 0.003705250430107117 QPS: 269.88729071440673

100 thread search 10000 times:
	multi total cost: 13.453328609466553 average: 0.0013453328609466552 QPS: 743.3104691253444


**0.10.3**
insert 100w: 12.8 sec
create IVF_FLAT index: 105.3 sec

single thread search 10000 times:
	total cost: 41.43617343902588 average: 0.004143617343902588 QPS: 241.33502613882024

100 thread search 10000 times:
	total cost: 11.34516429901123 average: 0.001134516429901123 QPS: 881.432805770079

**0.10.2**
insert 100w: 12.8 sec
create IVF_FLAT index: 104.9 sec

single thread search 10000 times:
	total cost: 39.95635938644409 average: 0.00399563593864441 QPS: 250.2730517383593

100 thread search 10000 times:
	total cost: 11.690181970596313 average: 0.0011690181970596314 QPS: 855.4186774125897

**Comment by del-zhenwu** [comment]
> Test with 0.10.2/0.10.3/0.10.4
> Collection: index_file_size=256M, insert 1000000 vectors, 128 dimensional
> Index: IVF_FLAT nlist=2048
> Search parameter: nq=1, topk=10, nprobe=32
> 
> **0.10.4**
> insert 100w: 12.5 sec
> create IVF_FLAT index: 105.5 sec
> 
> single thread search 10000 times:
> total cost: 37.05250430107117 average: 0.003705250430107117 QPS: 269.88729071440673
> 
> 100 thread search 10000 times:
> multi total cost: 13.453328609466553 average: 0.0013453328609466552 QPS: 743.3104691253444
> 
> **0.10.3**
> insert 100w: 12.8 sec
> create IVF_FLAT index: 105.3 sec
> 
> single thread search 10000 times:
> total cost: 41.43617343902588 average: 0.004143617343902588 QPS: 241.33502613882024
> 
> 100 thread search 10000 times:
> total cost: 11.34516429901123 average: 0.001134516429901123 QPS: 881.432805770079
> 
> **0.10.2**
> insert 100w: 12.8 sec
> create IVF_FLAT index: 104.9 sec
> 
> single thread search 10000 times:
> total cost: 39.95635938644409 average: 0.00399563593864441 QPS: 250.2730517383593
> 
> 100 thread search 10000 times:
> total cost: 11.690181970596313 average: 0.0011690181970596314 QPS: 855.4186774125897

we should test based on the same thread number, and different connection number.

**Comment by shengjun1985** [comment]
Whether the threads use different connections or use a same connection, the server will merger the queries.
