### ISSUE TITLE
[BUG] Some troubleshoot messages in Milvus do not provide enough information

### ISSUE THREAD

**Issue by yamasite** [milvus-io/milvus#30]
**Describe the bug**
Some troubleshoot messages in the Milvus software do not provide enough information. Users still need to refer to the documentation for details. This might have a negative effect on user experience. We need to improve these messages in the software.

**Expected behavior**
Please refer to the suggested text below:

Topic | Old Message | New Message
------------ | ------------- | ---------------
General | Invalid table name: xxx | Invalid table name: xxx. A table name can only contain numbers, letters, and underscores. The first character of a table name must not be a number. The length of a table name must be less than 255 characters.
General | Table xxx not exist | Table xxx does not exist. Use milvus.has_table to verify whether the table exists. You also can check if the table name exists.
CreateTable | Invalid table dimension: xxx | Invalid table dimension: xxx. The table dimension must be within the range of 1 ~ 16384.
CreateTable | Invalid index file size: xxx | Invalid index file size: xxx. The index file size must be within the range of 1 ~ 4096.
CreateTable | Invalid index metric type: xxx | Invalid index metric type: xxx. Make sure the metric type is either MetricType.L2 or MetricType.IP.
CreateIndex | Invalid index type: xxx | Invalid index type: xxx. Make sure the index type is among FLAT, IVFLAT, and IVF_SQ8.
CreateIndex | Invalid index nlist: xxx | Invalid index nlist: xxx. The index nlist must be greater than 0.
Insert | Row record array is empty | The row record array is empty. Make sure you have entered vector records.
Insert | Size of vector ids is not equal to row record array size | The size of vector ID array must be equal to the size of the vector. 
Insert | Table vector ids are user defined, please provide id for this batch | Table vector IDs are user-defined. Please provide IDs for all vectors of this table.
Insert | Table vector ids are auto generated, no need to provide id for this batch | Table vector IDs are auto-generated. All vectors of this table must use auto-generated IDs.
Insert | Row record float array is empty | The row record float array must not be empty.
Insert | Invalid row record dimension: xxx vs. table dimension: xxx | The row record dimension must be equal to the table dimension.
Search | Invalid topk: xxx | Invalid topk: xxx. The topk must be within the range of 1~2048.
Search | Invalid nprobe: xxx | Invalid nprobe: xxx. The nprobe must be within the range of 1 ~ index nlist.
Search | Query record float array is empty | The query record float array is empty. Make sure the vectors you want to search have values.
Search | Invalid query record dimension: xxx vs. table dimension: xxx | The vector dimension must be equal to the table dimension.

Refer to [Milvus Documentation](https://milvus.io/docs/en/userguide/troubleshoot/) for all troubleshooting messages documented in the current release.

Note that the original descriptions are based on the current Milvus documentation. If there are any software changes that are not captured by the documentation or the suggested text is not technically accurate, please let me know.

**Comment by yhmo** [comment]
After discussion, we redefine the error messages:

ERROR CODE | ERROR MESSAGE | API | REASON | ACTION
-- | -- | -- | -- | --
9 | Table name should not be empty. | most of sdk api | should not be empty | table name should not be empty
9 | Invalid table name: xxx. The length of a table name must be less than 255 characters. | most of sdk api | table name is illegal | ensure character less than 255
9 | Invalid table name: xxx. The first character of a table name must be an underscore or letter. | most of sdk api | table name is illegal | first character should be underscore or character
9 | Invalid table name: xxx. Table name can only contain numbers, letters, and underscores. | most of sdk api | table name is illegal | table name only contains underscore/alphanumber
7 | Invalid table dimension: xxx. The table dimension must be within the range of 1 ~ 16384. | CreateTable | table dimension is illegal | dimension range: 1 ~ 16384
5 | Invalid index file size: xxx. The index file size must be within the range of 1 ~ 4096. | CreateTable | index file size is illegal | range: 1 ~ 4096
23 | Invalid index metric type: xxx. Make sure the metric type is either MetricType.L2 or MetricType.IP. | CreateTable | metric type is illegal | 1: L2    2:Inner Product
4 | Table xxx not exist. Use milvus.has_table to verify whether the table exists. You also can check if the table name exists. | most of sdk api | table not found | make sure the table is exist and table name is correct
8 | Invalid index type: xxx. Make sure the index type is in IndexType list. | CreateIndex | index type is illegal | 1:FLAT 2:IVFLAT 3:IVF_SQ8 4:MIX_NSG
22 | Invalid index nlist: xxx. The index nlist must be greater than 0. | CreateIndex | nlist value is illegal | value > 0
11 | The row record array is empty. Make sure you have entered vector records. | Insert/Search | insert empty vectors into milvus | insert vector must has value
11 | The row record float array must not be empty. | Insert/Search | vector data is empty |  
12 | The size of vector ID array must be equal to the size of the vector. | Insert | vector id array size not equal to vector size | if  you want to use user-custom id for insert vectors, make sure vector id  array size equal to vector size. if you didn't provide user-custom ids,  keep the id array empty and milvus will generate id for these vectors
12 | Table vector IDs are user-defined. Please provide IDs for all vectors of this table. | Insert | some vectors of this table use user-custom id, all vectors must use user-custom id | provide user-custom id to insert vector
12 | Table vector IDs are auto-generated. All vectors of this table must use auto-generated IDs. | Insert | some vectors of this table use auto-generated id, all vectors must use auto-generated id | don't provide user-custom id to insert vector
7 | The row record dimension must be equal to the table dimension. | Insert/Search | vector dimension is not equal to table dimension | make sure vector dimension is equal to table dimension
10 | Invalid topk: xxx. The topk must be within the range of 1 ~ 2048. | Search | search parameter topk is illegal | range: 1 ~2048
5 | Invalid nprobe: xxx. The nprobe must be within the range of 1 ~ index nlist. | Search | search parameter nprobe is illegal | range: 1 ~ index nlist
11 | The query record float array is empty. Make sure the vectors you want to search have values. | Search | vector data is empty | for example, dimension=512, you must provide 512 float values for each vector
7 | The vector dimension must be equal to the table dimension. | Search | vector dimension is not equal to table dimension | make sure vector dimension is equal to table dimension

**Comment by yhmo** [comment]
Already implemented
