### ISSUE TITLE
[Bug]: Data nodes crashing with error: failed to update channel checkpoint and  context deadline exceeded in milvus version 2.3.4

### ISSUE THREAD

**Issue by kdabbir** [milvus-io/milvus#30004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.4
- Deployment mode(standalone or cluster): Milvus cluster deployed in kubernetes
- MQ type(rocksmq, pulsar or kafka):   External Kafka (AWS MSK)
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.4
num_shards of collection: 1 
total of 10000 collections with 1 shards
Vector dim: 768
Scale: 5 billion
- CPU/Memory:
The underlying data/query nodes are based on r5.4xlarge node having 14 cores/128gb memory. 12 cores/64gb memory for index nodes based on c5.9xlarge node.

Referred to milvus sizing tool & scaled up 12 index nodes, 6 data nodes, 80 query nodes.

- Also increased etcd ETCD_MAX_TXN_OPS to 6000 to support more operations
```

### Current Behavior

We are testing 2.3.4 milvus version capabilties. Have created 10 thousand collections (no partitions created) with 1 shard and started ingesting 10k records per collection.
After an insertion of around 80 million vectors in the collection, collection load is timing out, unable to load collections and do search. Note that we are using bulk insert to insert vectors in the collection.

I can see below errors in data node:

 [`WARN] [broker/datacoord.go:102] ["failed to update channel checkpoint"] [channelName=by-dev-milvuscollectionstest234-dml_2_44702248727934064 ] [ (3) attempt #0: rpc error: code = DeadlineExceeded desc = context deadline exceeded\nError types: (1) *withstack.withStack (2) ]`

### Expected Behavior

As we were having discussions with @xiaofan-luan , 2.3.4 milvus version is expected to support 10k collections and handle bigger scale upto 5 billion, Cluster is crashing and not stable with 80 million vectors with 10k collections, please suggest how to fix this error.

### Steps To Reproduce

```markdown
1. Create a milvus cluster with 2.3.4
2. Create 10k collections
3. Ingest 10k vectors of 768 dimension in each collection, keeping it in a loop to insert one after another
4. Perform collection load and search, facing the issue.
```

### Milvus Log

[LogFiles1.zip](https://github.com/milvus-io/milvus/files/13939702/LogFiles1.zip)
[Logfiles2.zip](https://github.com/milvus-io/milvus/files/13939707/Logfiles2.zip)
[LogFiles3.zip](https://github.com/milvus-io/milvus/files/13939708/LogFiles3.zip)

**Comment by yanliang567** [comment]
/assign @MrPresent-Han 
could u please help to take a look?

**Comment by MrPresent-Han** [comment]
Hi, [kdabbir](https://github.com/kdabbir), it seems that datanode crushed with code134 but log files of datanode is so short that hard to guess the root cause, is it convenient for you to help exporting intact log files using the script above:
https://github.com/milvus-io/milvus/tree/master/deployments/export-log

**Comment by become-nice** [comment]
We also encountered this problem, the version we used is 2.3.9.

**Comment by become-nice** [comment]
![POPO-20240228-110649](https://github.com/milvus-io/milvus/assets/56624819/c4b5dcf7-83c1-4682-9440-1a2cb709e4ec)

**Comment by xiaofan-luan** [comment]
> ![POPO-20240228-110649](https://private-user-images.githubusercontent.com/56624819/308404650-c4b5dcf7-83c1-4682-9440-1a2cb709e4ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwOTE2NjAsIm5iZiI6MTcwOTA5MTM2MCwicGF0aCI6Ii81NjYyNDgxOS8zMDg0MDQ2NTAtYzRiNWRjZjctODNjMS00NjgyLTk0NDAtMWEyY2I3MDllNGVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDAzMzYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiNTYwMmQ1NjI2YmZlZWY1YTIwYjFlYzQ0MzA1ZGQ5YmU3MjAxODI2M2ZmZDViOWMzNTcyN2M4OTI0NmMzZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rJsPPpJxOBQ6gijiJz-BaCLn9oUZXfhZ9lzJo9jCT4E)

could you offer a pprof for your datanode and data coord?
How many collections, partitions do you have?

**Comment by become-nice** [comment]
[dataCoord.log](https://github.com/milvus-io/milvus/files/14431148/dataCoord.log)

**Comment by become-nice** [comment]
datanode:
[pprof.milvus.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz](https://github.com/milvus-io/milvus/files/14431393/pprof.milvus.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz)
[pprof.milvus.goroutine.001.pb.gz](https://github.com/milvus-io/milvus/files/14431400/pprof.milvus.goroutine.001.pb.gz)
[pprof.milvus.samples.cpu.001.pb.gz](https://github.com/milvus-io/milvus/files/14431401/pprof.milvus.samples.cpu.001.pb.gz)

**Comment by bigsheeper** [comment]
There are 1000 `UpdateChannelCheckpoint` goroutines currently running. Even if the collection number is normal, when the updating speed lags behind, the datanode will submit tasks per time tick, leading to a backlog of tasks waiting to be executed.
![image](https://github.com/milvus-io/milvus/assets/42060877/019b2b6a-31ca-48a7-a467-647e71bc0793)

I believe there are two enhancements:
1. Reduce the concurrency of CP updating; 1000 is too burdensome for DataCoord.
2. Always ensure that only one task with the same vchannel is kept in the CP updater.

**Comment by become-nice** [comment]
![POPO-20240228-183132](https://github.com/milvus-io/milvus/assets/56624819/54566dbc-ced5-48e0-85e3-cfc13dbfd89f)

**Comment by kdabbir** [comment]
we ran two new tests with Milvus version 2.3.9 and seeing the same issue with just 1000 collections with 1 shard. Attached the log and details about the tests in another issue: https://github.com/milvus-io/milvus/issues/30905

**Comment by xiaofan-luan** [comment]
From our current analysis:
update check point is too frequent when there are too many collections, and this brings two problems
 1) https://github.com/milvus-io/milvus/pull/30903/files the update check point lock need to be fine grained
 2) current newChannelCheckpointUpdater update checkpoint per each rpc. we need to batch it under  many collections use cases.

@kdabbir 
My guess is import smaller files could cause this problem 

Could you reproduce this issue with:
1.  pprof file of your datanode and datacoord?
2. list how many segments are there in your test before it crash?  ideally you should have 10k collections * 10 segments(each segments has 10k data)
