### ISSUE TITLE
[Bug]: Delete data in batches and execute in a single thread all the time. After a period of time, the queryNode node disk will continue to increase, occupying 50 GB of memory within 10 minutes, resulting in node downtime.

### ISSUE THREAD

**Issue by WenShaoHub** [milvus-io/milvus#30069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.2
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus v2.3.0
- OS(Ubuntu or CentOS): TencentOS Server 3.1 (TK4)
- CPU/Memory: 16 cores/64GB
- GPU:
- Others:
```

### Current Behavior

My requirement is to delete 100 million data, now 500 records are deleted once, but after the program runs for a period of time, the disk usage of the queryNode node will suddenly increase, filling up the entire machine (50GB) in 10 minutes, resulting in node downtime.

example:
expr=resource_id in [16670002,16670004,16670006,16670013,16670016,16670025,16670026,16670027,16670031,16670032,16670033,16670034,16670035,16670039,16670047,16670048,16670050,16670053,16670055,16670063,16670070,16670083,16670084,16670090,16670092,16670095,16670106,16670108,16670109,16670111,16670115,16670117,16670118,16670120,16670121,16670122,16670124,16670129,16670133,16670139,16670140,16670141,16670150,16670154,16670158,16670159,16670163,16670165,16670171,16670172,16670179,16670186,16670197,16670200,16670201,16670204,16670210,16670211,16670212,16670214,16670216,16670224,16670230,16670231,16670239,16670240,16670242,16670245,16670248,16670249,16670252,16670260,16670261,16670264,16670267,16670271,16670273,16670274,16670275,16670276,16670277,16670278,16670282,16670287,16670288,16670289,16670290,16670294,16670301,16670309,16670310,16670311,16670312,16670317,16670320,16670323,16670329,16670330,16670331,16670333,16670336,16670337,16670338,16670339,16670351,16670353,16670361,16670363,16670366,16670371,16670375,16670377,16670378,16670386,16670390,16670396,16670401,16670410,16670411,16670418,16670420,16670421,16670423,16670425,16670427,16670428,16670436,16670439,16670440,16670443,16670445,16670447,16670448,16670449,16670450,16670461,16670479,16670484,16670487,16670488,16670492,16670501,16670504,16670508,16670516,16670521,16670522,16670523,16670531,16670533,16670536,16670537,16670540,16670544,16670546,16670549,16670551,16670552,16670556,16670559,16670565,16670566,16670567,16670568,16670572,16670573,16670579,16670583,16670588,16670595,16670597,16670606,16670610,16670613,16670616,16670619,16670620,16670622,16670626,16670632,16670639,16670640,16670648,16670649,16670657,16670662,16670663,16670665,16670671,16670672,16670676,16670677,16670683,16670686,16670687,16670688,16670689,16670690,16670696,16670698,16670701,16670702,16670704,16670705,16670706,16670708,16670715,16670716,16670718,16670727,16670729,16670734,16670741,16670743,16670745,16670746,16670748,16670749,16670750,16670752,16670756,16670757,16670759,16670761,16670764,16670765,16670767,16670769,16670771,16670773,16670777,16670778,16670783,16670784,16670788,16670794,16670798,16670801,16670803,16670806,16670808,16670814,16670815,16670817,16670819,16670822,16670824,16670825,16670826,16670829,16670837,16670842,16670846,16670847,16670852,16670858,16670860,16670865,16670867,16670868,16670872,16670873,16670874,16670881,16670882,16670883,16670886,16670887,16670889,16670891,16670893,16670896,16670904,16670905,16670911,16670913,16670920,16670923,16670925,16670938,16670942,16670944,16670945,16670948,16670950,16670951,16670956,16670960,16670963,16670965,16670966,16670971,16670972,16670975,16670980,16670982,16670984,16670986,16670988,16670990,16670993,16670995,16670996,16670997,16670999,16671000,16671001]

### Expected Behavior

My requirement is to delete 100 million data, now 500 records are deleted once, but after the program runs for a period of time, the disk usage of the queryNode node will suddenly increase, filling up the entire machine (50GB) in 10 minutes, resulting in node downtime.

**Comment by xiaofan-luan** [comment]
@WenShaoHub 

could you give more details about what dir takes the disk space?

**Comment by WenShaoHub** [comment]
![WechatIMG75](https://github.com/milvus-io/milvus/assets/32670073/2a77c24f-8206-477e-a5d6-c8cac78c6f54)
/milvus@xiaofan-luan

**Comment by xiaofan-luan** [comment]
I think you hit a core dump some how and the system is trying to generate a coredump file.

We don't recommend you to delete too much data at once. 

it seems that you memory is larger than 50G  so the core dump file can not be generated

**Comment by xiaofan-luan** [comment]
you can also try 2.3.5 since 2.3.4 and 2.3.5 fixed bunch of delete issue

**Comment by xiaofan-luan** [comment]
> /assign @LoveEachDay /unassign

This seems to be a core dump

**Comment by WenShaoHub** [comment]
I know it is a core dump, but we need to know why this file is generated, whether it is deleting too much data, too fast or what. This bug is mandatory and has happened several times. Why does deleting it cause the query node to fail

**Comment by WenShaoHub** [comment]
Can you explain the internal logic of the deletion, from the execution of expr statement to delete memory data, and then to delete disk data, which steps go through, whether to go through queryNode, kafka,indexNode,dataNode

**Comment by yanliang567** [comment]
@LoveEachDay any updates for questions above

**Comment by LoveEachDay** [comment]
> Can you explain the internal logic of the deletion, from the execution of expr statement to delete memory data, and then to delete disk data, which steps go through, whether to go through queryNode, kafka,indexNode,dataNode

@WenShaoHub When you executing a `delete by expr`, the proxy will first make a query based on the expr to retrieve all the primary keys back, then proxy will save the delete msg into the message queue which will be consumed by the datanode and querynode.  

Could you upload the complete log for the milvus querynode? 

By the way, to disable to the coredump, you may need to run `ulimit -c 0` in the worker node or the host machine.
