### ISSUE TITLE
[Bug]:  create_index efConstruction out of range: [1, 2147483647]

### ISSUE THREAD

**Issue by AlexNilone** [milvus-io/milvus#30064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.4
- Deployment mode(standalone or cluster):standalone 
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus  2.3.4
- OS(Ubuntu or CentOS): centos7
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

when I create index ,some errors show

### Milvus Log

2024-01-17 15:20:27,101 - decorators.py[line:128] - ERROR: RPC error: [create_index], <MilvusException: (code=65535, message=efConstruction out of range: [1, 2147483647])>, <Time:{'RPC start': '2024-01-17 15:20:27.095948', 'RPC error': '2024-01-17 15:20:27.101323'}>

But the create index result is successful.

others:
pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=cannot parse expression: pk in ['447078961691763099'], error: value ''447078961691763099'' in list cannot be casted to Int64)>

**Comment by xiaofan-luan** [comment]
@AlexNilone 
could it be  pk in [447078961691763099] since pk is a int not a string

**Comment by yanliang567** [comment]
/assign @AlexNilone 
please retry as comments above

/unassign

**Comment by yanliang567** [comment]
if it reproduce to you, please share the reproduce code and data sample

**Comment by AlexNilone** [comment]
> @AlexNilone could it be pk in [447078961691763099] since pk is a int not a string

是的。它就是一个主键。里面有这个记录但是就是提示这个问题。一会儿说是长度越界了，一会儿说是无法转换为int64

**Comment by AlexNilone** [comment]
> if it reproduce to you, please share the reproduce code and data sample

我这边是因为和别的第三方的组件langchainChatChat集成的过程出现的，不是我自己的代码产生的问题

**Comment by smellthemoon** [comment]
@AlexNilone 
If it's convenient, can you describe in detail how to reproduce this phenomenon and what code sample you have used？
I have used langchainChatChat, but it seems ok.

**Comment by aotsukiqx** [comment]
same issue, but it happened after upgrade langchain-chatchat from 0.2.9 t0 0.2.10.
after upgrade, the issue can be reproduced by run 'python init_database.py --recreate-vs' at repo's root directory.

**Comment by smellthemoon** [comment]
The root cause is that pk is int64 type, but when generating the query expr, use str directly.

**Comment by smellthemoon** [comment]
related with https://github.com/chatchat-space/Langchain-Chatchat/pull/2868
