### ISSUE TITLE
[Bug]:  Looks like there's something wrong with the queryNode target update

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#30081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20240117-9a383721-amd64
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):  pulsar  
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.4.0rc19
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

- Test steps:
  1. create collection -> create index -> insert 3m data into 3 partitions -> flush -> index -> load
  2. concurrent from 2024-01-17 09:16:47 to 2024-01-17 13:16:48
    - search
    - scene_insert_partition: each locust user insert 200 entities into a random one of the 10 partitions. The pk id started from 3m and increases automatically.
    - delete with expr: id > 3m
   3. Apply pod kill chaos at approximately 2024-01-17 10:14 during concurent requests. Kill all 3 querynodes every two minutes and remove chaos after ten minutes.
   4. Starting around 2024-01-17 10:28:48, the request to restore was successful.
- After test done, the birdwatcher segment info is:
```
Milvus(chaos-delta-multi-par-1) > show segment --collection 447081999996815133 --format line
SegmentID: 447081999997019655 State: Flushed, Level: L1, Row Count:500186
SegmentID: 447081999997219673 State: Flushed, Level: L1, Row Count:499814
SegmentID: 447082000040558772 State: Growing, Level: L1, Row Count:8219
SegmentID: 447082000040558980 State: Growing, Level: L1, Row Count:7576
SegmentID: 447081999997019630 State: Flushed, Level: L1, Row Count:499820
SegmentID: 447081999997219564 State: Flushed, Level: L1, Row Count:500180
SegmentID: 447082000040154904 State: Growing, Level: L1, Row Count:26098
SegmentID: 447082000040355886 State: Growing, Level: L1, Row Count:22043
SegmentID: 447081999997019593 State: Flushed, Level: L1, Row Count:500322
SegmentID: 447081999997219616 State: Flushed, Level: L1, Row Count:499679
SegmentID: 447082000040356161 State: Growing, Level: L1, Row Count:24053
SegmentID: 447082000040356722 State: Growing, Level: L1, Row Count:20827
SegmentID: 447082000040760145 State: Growing, Level: L1, Row Count:4993
SegmentID: 447082000040760164 State: Growing, Level: L1, Row Count:4917
SegmentID: 447082000040558236 State: Growing, Level: L1, Row Count:11417
SegmentID: 447082000040558622 State: Growing, Level: L1, Row Count:9983
SegmentID: 447082000040154737 State: Growing, Level: L1, Row Count:27096
SegmentID: 447082000040155082 State: Growing, Level: L1, Row Count:25689
SegmentID: 447082000040559816 State: Growing, Level: L1, Row Count:5116
SegmentID: 447082000040760827 State: Growing, Level: L1, Row Count:1539
SegmentID: 447082000040155292 State: Growing, Level: L1, Row Count:26193
SegmentID: 447082000040355924 State: Growing, Level: L1, Row Count:23978
SegmentID: 447081999997019761 State: Flushed, Level: L1, Row Count:109
SegmentID: 447081999997219752 State: Flushed, Level: L1, Row Count:91
SegmentID: 447081999997019760 State: Flushed, Level: L1, Row Count:105
SegmentID: 447081999997219753 State: Flushed, Level: L1, Row Count:95
--- Growing: 16, Sealed: 0, Flushed: 10, Dropped: 0
--- Small Segments: 4, row count: 400    Other Segments: 6, row count: 3000001
--- Total Segments: 26, row count: 3250138
```
- query count(*) results:
```
c.query('id >=0', output_fields=["count(*)"], partition_names=par, consistency_level="Strong")
[{'count(*)': 3001801}]
par
['_default', 'partition_1', 'partition_2', 'p_J7RY9mql', 'p_nQeO0gwM', 'p_XZkZsJw8', 'p_oorhcu2Q', 'p_dBrzCPyJ', 'p_d1Wo4AqH', 'p_sKxjjt9j']
```
- queryNode loaded segment num and queryable entity num:
![image](https://github.com/milvus-io/milvus/assets/27288593/d61dd9ce-ff6e-436f-b083-b0a3c64e73e0)

![image](https://github.com/milvus-io/milvus/assets/27288593/312e56f8-89ce-4844-b4e7-87c54a0af990)

- after release-load, querynode loaded segments are same with birdwatcher:
```
c.release()
c.load()
c.query('id >=0', output_fields=["count(*)"], partition_names=par, consistency_level="Strong")
[{'count(*)': 3001801}]
```
![image](https://github.com/milvus-io/milvus/assets/27288593/4f8d544f-5ef6-4a89-aa8d-6b636610de06)
![image](https://github.com/milvus-io/milvus/assets/27288593/5ad0a868-eee6-4d78-8f03-d6831aadefdf)

### Expected Behavior

Which row count is correct ?

### Milvus Log

- argo: [chaos-delta-multi-par-1](https://argo-workflows.zilliz.cc/archived-workflows/qa/40043439-04e5-4815-af9e-aedf8468ca8f?nodeId=chaos-delta-multi-par-1)
- grafana: [metrics of chaos-delta-multi-par-1](https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=qa-milvus&var-instance=chaos-delta-multi-par-1&var-collection=All&var-app_name=milvus&from=1705482600000&to=1705510800000)
- pods:
```
chaos-delta-multi-par-1-milvus-datanode-77559dbd95-gmmxr          1/1     Running        0                6h51m   10.104.29.112   4am-node35   <none>           <none>
chaos-delta-multi-par-1-milvus-datanode-77559dbd95-hwth9          1/1     Running        0                6h51m   10.104.21.184   4am-node24   <none>           <none>
chaos-delta-multi-par-1-milvus-indexnode-6fdc64f784-4pz95         1/1     Running        0                6h51m   10.104.21.185   4am-node24   <none>           <none>
chaos-delta-multi-par-1-milvus-indexnode-6fdc64f784-zqd72         1/1     Running        0                6h51m   10.104.20.100   4am-node22   <none>           <none>
chaos-delta-multi-par-1-milvus-mixcoord-77ff5865cd-j7hwt          1/1     Running        0                6h51m   10.104.12.205   4am-node17   <none>           <none>
chaos-delta-multi-par-1-milvus-proxy-774db7474b-dm5nh             1/1     Running        0                6h51m   10.104.6.105    4am-node13   <none>           <none>
chaos-delta-multi-par-1-milvus-querynode-5f84ff5969-7trqh         1/1     Running        0                5h35m   10.104.12.233   4am-node17   <none>           <none>
chaos-delta-multi-par-1-milvus-querynode-5f84ff5969-qxtqt         1/1     Running        0                5h35m   10.104.29.142   4am-node35   <none>           <none>
chaos-delta-multi-par-1-milvus-querynode-5f84ff5969-qz4js         1/1     Running        0                5h35m   10.104.33.36    4am-node36   <none>           <none>
```

**Comment by ThreadDao** [comment]
By the way, Please help confirm whether the target upgrade is normal. From the picture below, we can see that the growing segments have been increasing but not decreasing. I guess the early memory is enough to update target
![image](https://github.com/milvus-io/milvus/assets/27288593/831ad7de-6408-446d-b9f3-6ab0c27e62a2)
![image](https://github.com/milvus-io/milvus/assets/27288593/7c013597-2ba8-4d9d-9013-d3d61f25a6c3)
![image](https://github.com/milvus-io/milvus/assets/27288593/ce88d41e-e00d-41eb-a18d-217385acdc5a)

**Comment by yah01** [comment]
the system constantly tried to subscribe a channel, which has even been subscribed
