### ISSUE TITLE
[Bug]: string validation index number is wrong

### ISSUE THREAD

**Issue by reecerussell** [milvus-io/milvus#30082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.0
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): n/a
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.0
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 2Core, 2GB
- GPU: n/a
- Others: n/a
```

### Current Behavior

When I attempt to insert data into a string field, that exceeds the max length, the error message returned isn't helpful. For example, I received the error message below, which states the 730th item in the array was too long for the field, however, it was actually the 731st item that was too long. This is because when the error message is constructed, the index is used as a position, but as Go arrays are 0-based, the index in the error message is off by 1.
```
the length (4990) of 730th string exceeds max length (4096): expected=valid length string, actual=string length exceeds max length: invalid parameter
```

### Expected Behavior

If the 731st item in the array is too long for the specified field, the error message should indicate the index to be "730" instead.

### Steps To Reproduce

```markdown
- Create a collection with a string field.
- Attempt to values into it, the first being valid, and the second being too long.
- An error should be returned, similar to the above, stating the "1th" item is too big, but actually it should say the "2nd".
```

**Comment by yanliang567** [comment]
thanks for the issue and pr, this really a noisy issue.
/assign @reecerussell 
/assign @czs007 
@czs007 please help to review the pr

**Comment by reecerussell** [comment]
@yanliang567 / @czs007, I've only updated this for the string validation, but I'm more than happy to update it elsewhere. 

On a side note, are there any docs to get a dev environment set up locally? I'm running on an Apple chip (M1 Pro) and unable to generate the protos locally.
