### ISSUE TITLE
[Bug]: When I restart the broker, rootcoord cannot restart.

### ISSUE THREAD

**Issue by 1271653627** [milvus-io/milvus#30088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.2.1
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I restart the broker, rootcoord cannot find a certain topic, which prevents rootcoord from starting.

### Expected Behavior

cluster should be working

### Milvus Log

[rootcoord.txt](https://github.com/milvus-io/milvus/files/13971840/rootcoord.txt)

**Comment by 1271653627** [comment]
After I entered the Pulsar Broker container and executed bin/pulsar-admin topics list public/default, it returned an HTTP 500 error.

**Comment by yanliang567** [comment]
it seems that the milvus is not connect to etcd or pulsar, could you please
1. retry on latest milvus version, v2.3.5
2. remove all the pvc of milvus pods and etcd, pulsar pods,
3. and re-deploy a new milvus cluster

**Comment by yanliang567** [comment]
if it reproduce to you for the latest milvus, please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @1271653627

**Comment by 1271653627** [comment]
I did not upgrade the Milvus version, but I deleted the cluster's persistent data and redeployed the entire cluster. The cluster is back to normal now, but this method is not suitable for production use.
Sorry,i cannot export milvus logs refer the way you providing,because i deploy the cluster using docker swarm @yanliang567
