### ISSUE TITLE
[Bug]: restful删除接口错误码65535

### ISSUE THREAD

**Issue by dushulin** [milvus-io/milvus#30092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.2
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):use http request
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

使用删除接口：https://milvus.io/api-reference/restful/v2.3.x/Vector%20Operations/delete.md，schema如下：
![image](https://github.com/milvus-io/milvus/assets/25276301/17c773cc-9a74-4409-8dbd-406edc9e78ed)
删除接口调用后报错如下：
![image](https://github.com/milvus-io/milvus/assets/25276301/d233939c-109b-4690-b314-88742f482392)

### Milvus Log

![image](https://github.com/milvus-io/milvus/assets/25276301/d070f886-1857-406f-a509-fdb889ec947a)

**Comment by dushulin** [comment]
信件已收到      【自动回复】

**Comment by SimFG** [comment]
This seems to be a bug when handling the request format.
you can try to use:
```
curl --request POST \
     --url "${MILVUS_HOST}:${MILVUS_PORT}/v1/vector/delete" \
     --header "Authorization: Bearer ${TOKEN}" \
     --header "accept: application/json" \
     --header "content-type: application/json" \
     -d '{
       "collectionName": "robot_test",
       "filter": "id in [\"robot/raw-data-storage/M92A-01/001/cam0/20230914/102948/1694658698357589000.jpg\"]"
     }'
```

**Comment by dushulin** [comment]
> This seems to be a bug when handling the request format. you can try to use:
> 
> ```
> curl --request POST \
>      --url "${MILVUS_HOST}:${MILVUS_PORT}/v1/vector/delete" \
>      --header "Authorization: Bearer ${TOKEN}" \
>      --header "accept: application/json" \
>      --header "content-type: application/json" \
>      -d '{
>        "collectionName": "robot_test",
>        "filter": "id in [\"robot/raw-data-storage/M92A-01/001/cam0/20230914/102948/1694658698357589000.jpg\"]"
>      }'
> ```

thanks，it works，maybe the restful doc should update：https://milvus.io/api-reference/restful/v2.3.x/Vector%20Operations/delete.md
