### ISSUE TITLE
[Bug]: Error message is confusing when insert data datatype is mismatch(insert data datatype is array, defined field is int64)

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#30094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master and 2.3
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
    default_fields = [
        FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True),
        FieldSchema(name="float", dtype=DataType.FLOAT),
        FieldSchema(name="varchar", dtype=DataType.VARCHAR, max_length=65535),
        FieldSchema(name="array_int", dtype=DataType.INT64),
        FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim),
    ]
```

```
[[0, 1], [0.0, 1.0], ['0', '1'], [[1, 2], [1, 2]], [[0.8642411687042985, 0.0006037921939255897], [0.7523176566888036, 0.38738388003625346]]]
RPC error: [batch_insert], <DataNotMatchException: (code=1, message=The data in the same column must be of the same type.)>, <Time:{'RPC start': '2024-01-18 15:28:48.981430', 'RPC error': '2024-01-18 15:28:48.981735'}>

```

I made a mistake in setting ARRAY to INT64 datatype. The error is `The data in the same column must be of the same type`
but I think this error should be a mismatch of the datatype of true data and defined schema.

`The data in the same column must be of the same type` should report when I set the datatype to int64, but I insert data like this [1,2,"3", 2.0]

**Comment by talhaanwarch** [comment]
I have set int to int and it give the same error. very confusing error
this is what my metadata look like
```
'source': {'id_pk': 48755}
```
and all are int, its not a mix at all. 
but changing it to string fix the issue
```
'source': {'id_pk': '48755'}
```

**Comment by xiaofan-luan** [comment]
> I have set int to int and it give the same error. very confusing error this is what my metadata look like
> 
> ```
> 'source': {'id_pk': 48755}
> ```
> 
> and all are int, its not a mix at all. but changing it to string fix the issue
> 
> ```
> 'source': {'id_pk': '48755'}
> ```
it's probably because you claim your datatype as string and try to insert a int?

**Comment by talhaanwarch** [comment]
> > I have set int to int and it give the same error. very confusing error this is what my metadata look like
> > ```
> > 'source': {'id_pk': 48755}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and all are int, its not a mix at all. but changing it to string fix the issue
> > ```
> > 'source': {'id_pk': '48755'}
> > ```
> 
> it's probably because you claim your datatype as string and try to insert a int?

hard to tell. as i am using langchain

**Comment by yanliang567** [comment]
@smellthemoon any updates for this?
