### ISSUE TITLE
[BUG] Client get error "Table file doesn't exist" for 4096 dimension table

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#301]
**Describe the bug**
Create a table with 4096 dimensions.
Insert 500000 vectors into the table.
Search.
Client(python) get error message "Table file doesn't exist"

**Environment details**
- Milvus version (v0.6.0)

**Comment by yhmo** [comment]
I create 5 files each file contain 100000 vectors(4096 dimensions). And read the files one by one and insert in to milvus.
The root cause of this issue is:  python client consumes too much system memory to load the data files(3GB each file) and serialize. Milvus also need memory to merge file. My machine cpu memory is 64GB.  Milvus failed to merge file due to out-of-memory, but meta system still record the file, so we get this error message 'Table file doesn't exist' when we perform search.

**Comment by JinHai-CN** [comment]
Shouldn't the files are merged before update the meta?

**Comment by yhmo** [comment]
Could not reproduce in 0.6.0
