### ISSUE TITLE
[Bug]: [restful]Search result distance is not sorted as order in restful search response

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#30102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 631ebb1f0778308a598f5ddea96b44a1d61ebe5a
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/12268675/fc96a976-590f-4647-a6ff-d854fcffc60e)

### Milvus Log

failed ci job: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-30036/11/pipeline/

**Comment by PowderLi** [comment]
restful search api didn't support metricsType `IP`, it use `L2` as default
so the distances in the result is in order, rather than in reserver order

**Comment by zhuwenxing** [comment]
metric type is set in the create collection API,  not in the search API.

**Comment by PowderLi** [comment]
the real problem is not the order, but the `SearchResultData.Scores` whose type is float32
for example:
grpc return 0.29036086797714233, but it was translated to be -0.29036087

**Comment by zhuwenxing** [comment]
The strange thing is that this case passed in the 2.3 image.  So why do images built in two branches behave differently?

**Comment by czs007** [comment]
@zhuwenxing please help verify this

**Comment by zhuwenxing** [comment]
verified and passed
