### ISSUE TITLE
[Bug]: leader checker can't remove segment from leader view

### ISSUE THREAD

**Issue by weiliu1031** [milvus-io/milvus#30150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master and 2.3.5
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

when leader view has dirty segments, it will generate a release segment to correct leader view.

### Expected Behavior

the leader view can be corrected by leader checker

**Comment by XuanYang-cn** [comment]
Might related to: https://github.com/milvus-io/milvus/issues/29838#issuecomment-1909486125
