### ISSUE TITLE
[Bug]: When executing a query, the results will appear in the log

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#30172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20240117-1185e4dc
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/12268675/33a82998-a94f-49ac-b842-594845b7cd06)

**Comment by zhuwenxing** [comment]
/assign @longjiquan 
PTAL

**Comment by zhagnlu** [comment]
not result, this log is plan description, proto has '\n'  so result log is too long.

**Comment by yanliang567** [comment]
@zhagnlu if it was fixed, please assign back us for verification, thx

**Comment by xiaofan-luan** [comment]
This is only enabled on debug node
