### ISSUE TITLE
[Enhancement]: compilation using GCC-13

### ISSUE THREAD

**Issue by alexanderguzhva** [milvus-io/milvus#30190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

milvus to be compilable using GCC-13

### Why is this needed?

newer versions of linux distributions

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What would you like to be added?
> milvus to be compilable using GCC-13
> 
> ### Why is this needed?
> newer versions of linux distributions
> 
> ### Anything else?
> _No response_

could ubuntu 20.04 support gcc13?
we need to support aws linux, some version of ubuntu and rocky linux in the future

**Comment by alexanderguzhva** [comment]
It is possible to install gcc-13 on ubuntu 20.04. For example, run the following inside a fresh `docker -it --rm ubuntu:20.04` container
```
apt update
apt-get install software-properties-common
add-apt-repository ppa:ubuntu-toolchain-r/test
apt install g++-13
```
It won't be possible to compile milvus from the scratch though, because MANY of conan packages will be missing `#include <cstddef>` and `#include <cstdint>` if you are using gcc-13. But it is fixable and ultimately milvus can be successfully compiled if #30149 is applied for milvus code itself.

**Comment by alexanderguzhva** [comment]
@douglarek Yes. Besides the changes or Milvus, listed above, `RocksDB`, `google-cloud-cpp` also needs to be patched.  Corresponding master branches on github have been patched, but we're using old packages.

Basically, all the complaints are because of the missing `cstdint` header.
As a quick hack, you need to add `#include <cstdint>` in the following files (the files GCC generates error in):
* `~/.conan/data/rocksdb/6.29.5/milvus/dev/source/source_subfolder/table/block_based/data_block_hash_index.h`
* `~/.conan/data/rocksdb/6.29.5/milvus/dev/source/source_subfolder/util/string_util.h`
* `~/.conan/data/rocksdb/6.29.5/milvus/dev/source/source_subfolder/utilities/checkpoint/checkpoint_impl.h`
* `~/.conan/data/rocksdb/6.29.5/milvus/dev/source/source_subfolder/include/rocksdb/utilities/checkpoint.h`
* `~/.conan/data/google-cloud-cpp/2.5.0/milvus/dev/source/src/google/cloud/internal/curl_handle.h`
* `~/.conan/data/google-cloud-cpp/2.5.0/milvus/dev/source/src/google/cloud/internal/rest_response.h`
* `~/.conan/data/google-cloud-cpp/2.5.0/milvus/dev/source/src/google/cloud/storage/bucket_cors_entry.h`
* `~/.conan/data/google-cloud-cpp/2.5.0/milvus/dev/source/src/google/cloud/storage/iam_policy.h`
* `~/.conan/data/google-cloud-cpp/2.5.0/milvus/dev/source/src/google/cloud/storage/internal/hash_function_impl.h`
* `~/.conan/data/google-cloud-cpp/2.5.0/milvus/dev/source/src/google/cloud/storage/internal/object_read_source.h`

And recompile Milvus. 
I've tested this today in a fresh docker container. 

Alternatively, you may wish to make Milvus to use newer packages, but it is untested.

Alternatively, you may wish to compile using `clang-17` or `clang-18` (as I do), but you'll need to get rid of `gcc --dumpversion` from Milvus `scripts/3rdparty_build.sh` and allow conan to use clang versions 17 and 18 by patching `~/.conan/settings.yml`

@xiaofan-luan any plans on upgrading packages?

**Comment by alexanderguzhva** [comment]
@douglarek It would be great to have your feedback on GCC 14 performance, if you could provide any numbers that you may meet during your work. If possible, of course. :)

**Comment by sfmqrb** [comment]
Thanks for this, @alexanderguzhva. Maybe it's worth adding a link to this issue in the developer docs?

I needed to tweak some paths though.
For future reference:

---

If you're hitting missing `<cstdint>` errors when compiling [[Milvus](https://github.com/milvus-io/milvus/issues/30190#issuecomment-2112994173)](https://github.com/milvus-io/milvus/issues/30190#issuecomment-2112994173), patch the Conan headers as follows:

---

### Patch `google-cloud-cpp` headers

```bash
for hdr in \
  ~/.conan/data/google-cloud-cpp/2.5.0/milvus/2.4/source/src/google/cloud/internal/curl_handle.h \
  ~/.conan/data/google-cloud-cpp/2.5.0/milvus/2.4/source/src/google/cloud/internal/rest_response.h \
  ~/.conan/data/google-cloud-cpp/2.5.0/milvus/2.4/source/src/google/cloud/storage/bucket_cors_entry.h \
  ~/.conan/data/google-cloud-cpp/2.5.0/milvus/2.4/source/src/google/cloud/storage/iam_policy.h \
  ~/.conan/data/google-cloud-cpp/2.5.0/milvus/2.4/source/src/google/cloud/storage/internal/hash_function_impl.h \
  ~/.conan/data/google-cloud-cpp/2.5.0/milvus/2.4/source/src/google/cloud/storage/internal/object_read_source.h
do
  [ -f "$hdr" ] || continue
  grep -q '<cstdint>' "$hdr" || sed -i '1i#include <cstdint>' "$hdr"
  echo "Patched $hdr"
done
```

---

### Patch `rocksdb` headers

```bash
for hdr in \
  ~/.conan/data/rocksdb/6.29.5/milvus/dev/source/source_subfolder/table/block_based/data_block_hash_index.h \
  ~/.conan/data/rocksdb/6.29.5/milvus/dev/source/source_subfolder/util/string_util.h \
  ~/.conan/data/rocksdb/6.29.5/milvus/dev/source/source_subfolder/utilities/checkpoint/checkpoint_impl.h \
  ~/.conan/data/rocksdb/6.29.5/milvus/dev/source/source_subfolder/include/rocksdb/utilities/checkpoint.h
do
  [ -f "$hdr" ] || continue
  grep -q '<cstdint>' "$hdr" || sed -i '1i#include <cstdint>' "$hdr"
  echo "Patched $hdr"
done
```

---

Run both scripts before building Milvus to avoid compilation errors.
