### ISSUE TITLE
[Bug]: milvus LOAD API not functioning as expected

### ISSUE THREAD

**Issue by haorenfsa** [milvus-io/milvus#30212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.3.1
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): java sdk
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:  transfer from https://github.com/zilliztech/milvus-helm/issues/34
```

### Current Behavior

cc @shaiktas

Milvus Version: 2.3.1
Exeucuting below operation on milvus Client using JAVA Client

1. CreatedCollection with 4 fields
2. Inserted 10 elements/entries into a  collection created in Step 1
3. CreatedIndex
4. Loading Collection
 The Load collection API is struck and after some time it finishing, but load is not performed. From Attu UI it intitially displyed as 50%, after Load API finish execution, it it visiable as unloaded.  
Attaching here
Attaching queryNode logs for reference:
[milvus-querynodelogs-loadAPI.txt](https://github.com/milvus-io/milvus/files/13234115/milvus-querynodelogs-loadAPI.txt)

Attu UI.

![image](https://github.com/milvus-io/milvus/assets/15938850/c61dff57-61b1-49c9-acc7-83591cccb103)
![image](https://github.com/milvus-io/milvus/assets/15938850/b7b4fe4d-4140-48f9-9bf9-6c91be552c90)

[milvus-querycoorlogs-loadAPI-0211.txt](https://github.com/milvus-io/milvus/files/13240874/milvus-querycoorlogs-loadAPI-0211.txt) [milvus-querynodelogs-loadAPI-0211.txt](https://github.com/milvus-io/milvus/files/13240881/milvus-querynodelogs-loadAPI-0211.txt)
[javaClientAPI.txt](https://github.com/milvus-io/milvus/files/13234122/javaClientAPI.txt)

**Comment by shaiktas** [comment]
Pls close this issue, it is fixed after configuring rootPath under storage. with empty rootPath the issue was existed
