### ISSUE TITLE
[Bug]:  dead lock while getting configs

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#30219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The loadFromFile method will hold the write lock, it might cause the dead lock due to invoking GetConfigurationByKey method in FileSource object which needs to acquire a read lock.
![image](https://github.com/milvus-io/milvus/assets/4024711/cfa98fc9-a4e7-4236-b3bf-28509aebbd2f)

![image](https://github.com/milvus-io/milvus/assets/4024711/9c393384-d2af-44e2-8784-42dbb622b09e)

In this case, it occurs during the initialization phase of milvus, the time tick will not be synchronized for all channels.

**Comment by xiaofan-luan** [comment]
this could be fixed by @weiliu1031 already

**Comment by jaime0815** [comment]
@xiaofan-luan it is a different issue
