### ISSUE TITLE
[Bug]: Timestamp lagtoo large lag(688h29m20.95s) max(24h0m0s): attempt #1: noavailable shard delegator found: service unavailable

### ISSUE THREAD

**Issue by liuxiaoxin-happy** [milvus-io/milvus#30236]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I restart milvus in my server, my collection is aways not loaded success and push error message.

### Milvus Log

[milvus-runtime.log](https://github.com/milvus-io/milvus/files/14031763/milvus-runtime.log)

**Comment by ljx112922** [comment]
milvus version is milvus:v2.3.2

**Comment by ljx112922** [comment]
milvus version is milvus-standalone:v2.3.2

**Comment by xiaofan-luan** [comment]
/assign @PowderLi 
could you help on investigation this?

**Comment by ljx112922** [comment]
> @ljx112922 could you please upload milvus.log from when you restart it?

I have uploaded log, you can read it

**Comment by PowderLi** [comment]
pay attention to the time range of the log file you uploaded
only covered [2024/01/24 02:06:48.586 +00:00, 2024/01/24 02:07:30.984 +00:00]
I believe you haven't restart the milvus in such a short duration.
the log just imply that the milvus was in an abnormal state, but some unusual events must happened at a historical moment
please uploaded more log before 2024/01/24 02:06:48.586 +00:00, better if from when you restart the milvus

**Comment by PowderLi** [comment]
I want to emphasize **"some unusual events must happened at a historical moment"**, however it must not be [2024/01/24 02:06:48.586 +00:00, 2024/01/24 02:07:30.984 +00:00], so I cannot found more useful information from the log you uploaded.

there may be 2 things that we can do:
1. could you please upload more logs, maybe you can do some things to reduce the log
   1.1 filter by log level. only reserve [ERROR] / [WARN], ignore [INFO].
   1.2 could you please do a precheck when is the exception most likely to occur? logs around that moment is ok.
2. could you please told us how to produce
   2.1 collections' schema, including the indexes schema
   2.2 have you insert many data into the collection

`when I start milvus-alone, my collection is not loaded`
collection is always not loaded after creation, unless you automatically call loadCollectio

**Comment by liuxiaoxin-happy** [comment]
It has occur more than ten times, but now I hava reinstalled my server. this problem has disappear.
