### ISSUE TITLE
[Bug]: bulk insert failed for binary vector with numpy and parquet file format

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#30243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20240117-1185e4dc
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

code to generate binary vector 
```
def gen_binary_vectors(nb, dim):
    # binary: each int presents 8 dimension
    # so if binary vector dimension is 16，use [x, y], which x and y could be any int between 0 and 255
    vectors = [[random.randint(0, 255) for _ in range(dim)] for _ in range(nb)]
    return vectors
```

numpy error 
```
illegal data type Int64 of numpy file for binary vector field 'binary_vec_field': importing data failed
```

parquet error 
```
field schema is not match, collection field dataType: BinaryVector, file field dataType:list: importing data failed
```

works well with json file format

### Milvus Log

example file:
[example.zip](https://github.com/milvus-io/milvus/files/14032747/example.zip)

**Comment by xiaofan-luan** [comment]
/assign @xiaocai2333 

please help on it

**Comment by zhuwenxing** [comment]
with the suggestion of @yhmo, the binary vector should set its datatype as unit 8, and it works well.

However, I am unable to obtain any advice from the error message and do not know how to fix it.

**Comment by xiaofan-luan** [comment]
why not use binary datatype for binary embedding?

**Comment by zhuwenxing** [comment]
It will use a unit8 value to represent each 8-bit. Therefore, a 128-dimensional binary vector will be transformed into a 16-dimensional unit8 datatype vector (128 divided by 8)

**Comment by xiaofan-luan** [comment]
w h y

**Comment by xiaofan-luan** [comment]
why not use BYTE_ARRAY but int8?

**Comment by yhmo** [comment]
Numpy:
```
arr = np.array([v1, v2, v3,,....], dtype=np.dtype("uint8"))
np.save(str(full_file_name), arr)
```

Parquet:
```
vector_arr = []
for vec in binary_vectors:
  vector_arr.append(np.array(vec, dtype=np.dtype("uint8")))

data_frame[vector_field_name] = pd.Series(vector_arr)
```

**Comment by xiaocai2333** [comment]
@zhuwenxing 
For paruqet: Binary_Vector can be imported by arrow.binary or uint8.
But I'm not clear on how to construct arrow.binary data in python. Here is a go example:
```
builder := array.NewBinaryBuilder(mem, &arrow.BinaryType{})
for i := 0; i < rows; i++ {
	element := make([]byte, dim/8)
	for j := 0; j < dim/8; j++ {
		element[j] = randomString(1)[0]
	}
	builder.Append(element)
}
return builder.NewBinaryArray()
```
