### ISSUE TITLE
[Bug]: If MetricType and IndexType are not specified when creating the index (CreateIndex), they will also not be returned during DescIndex, rendering the Search interface unusable.

### ISSUE THREAD

**Issue by lentitude2tk** [milvus-io/milvus#30241]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2、2.3
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka): xxx
- SDK version(e.g. pymilvus v2.0.0rc2): java-sdk && pymilvus
- OS(Ubuntu or CentOS): xxx
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

If CreateIndex does not specify indexType or metricType, the kernel will provide default values, allowing for normal creation.
```
private R<RpcStatus> createIndex() {
  System.out.println("========== createIndex() ==========");
  // create index for vector field
  R<RpcStatus> response = milvusClient.createIndex(CreateIndexParam.newBuilder()
          .withCollectionName("a")
          .withFieldName("Vectorfield")
          .withIndexName(INDEX_NAME)
          .withExtraParam(INDEX_PARAM)
          .withSyncMode(Boolean.TRUE)
          .build());

  // create index for scalar field
  response = milvusClient.createIndex(CreateIndexParam.newBuilder()
          .withCollectionName("a")
          .withFieldName("c")
          .withIndexName("c")
          .withExtraParam(INDEX_PARAM)
          .withSyncMode(Boolean.TRUE)
          .build());
```

However, the results obtained through the descIndex query do not include indexType and metricType, causing the search interface to be unusable. The descIndex results for vector columns do not provide indexType and metricType.
```
R{status=0, data=status {
}
index_descriptions {
  index_name: "userFaceIndex"
  indexID: 447168497195892638
  params {
    key: "params"
    value: "{\"nlist\":128}"
  }
  field_name: "Vectorfield"
  state: Finished
}
}
```

The descIndex results for scalar columns do not include indexType.
```
R{status=0, data=status {
}
index_descriptions {
  index_name: "c"
  indexID: 447168497195892641
  params {
    key: "params"
    value: "{\"nlist\":128}"
  }
  field_name: "c"
  state: Finished
}
}
```

### Expected Behavior

If indexType and metricType are not specified during createIndex, the kernel can set corresponding default values. However, during descIndex, it is necessary to return the currently assigned default indexType and metricType.

### Steps To Reproduce

```markdown
1. Call the createIndex interface using pymilvus or java-sdk (without specifying indexType and metricType).
2. Invoke the descIndex interface, and the returned results do not include the indexType and metricType fields.
3. This results in users being unable to determine the indexType and metricType for current scalar and vector indexes, making it impossible to use the search interface. If users are forced to rely on awareness of kernel default values, any subsequent adjustments to kernel default values would lead to inconsistency in behavior between old and new kernel versions.
```

**Comment by lentitude2tk** [comment]
Update: In the search interface, not passing the metricType actually allows the kernel to perform search operations. However, this introduces another question. If users cannot query the metricType corresponding to the current index, they also cannot determine whether the current search results are calculated using IP or L2 algorithms.

**Comment by yanliang567** [comment]
/assign @czs007 
is it about the autoindex configuration? any ideas?
/unassign

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version: 2.2、2.3
> - Deployment mode(standalone or cluster):standalone
> - MQ type(rocksmq, pulsar or kafka): xxx
> - SDK version(e.g. pymilvus v2.0.0rc2): java-sdk && pymilvus
> - OS(Ubuntu or CentOS): xxx
> - CPU/Memory: 
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> If CreateIndex does not specify indexType or metricType, the kernel will provide default values, allowing for normal creation.
> 
> ```
> private R<RpcStatus> createIndex() {
>   System.out.println("========== createIndex() ==========");
>   // create index for vector field
>   R<RpcStatus> response = milvusClient.createIndex(CreateIndexParam.newBuilder()
>           .withCollectionName("a")
>           .withFieldName("Vectorfield")
>           .withIndexName(INDEX_NAME)
>           .withExtraParam(INDEX_PARAM)
>           .withSyncMode(Boolean.TRUE)
>           .build());
> 
>   // create index for scalar field
>   response = milvusClient.createIndex(CreateIndexParam.newBuilder()
>           .withCollectionName("a")
>           .withFieldName("c")
>           .withIndexName("c")
>           .withExtraParam(INDEX_PARAM)
>           .withSyncMode(Boolean.TRUE)
>           .build());
> ```
> 
> However, the results obtained through the descIndex query do not include indexType and metricType, causing the search interface to be unusable. The descIndex results for vector columns do not provide indexType and metricType.
> 
> ```
> R{status=0, data=status {
> }
> index_descriptions {
>   index_name: "userFaceIndex"
>   indexID: 447168497195892638
>   params {
>     key: "params"
>     value: "{\"nlist\":128}"
>   }
>   field_name: "Vectorfield"
>   state: Finished
> }
> }
> ```
> 
> The descIndex results for scalar columns do not include indexType.
> 
> ```
> R{status=0, data=status {
> }
> index_descriptions {
>   index_name: "c"
>   indexID: 447168497195892641
>   params {
>     key: "params"
>     value: "{\"nlist\":128}"
>   }
>   field_name: "c"
>   state: Finished
> }
> }
> ```
> 
> ### Expected Behavior
> If indexType and metricType are not specified during createIndex, the kernel can set corresponding default values. However, during descIndex, it is necessary to return the currently assigned default indexType and metricType.
> 
> ### Steps To Reproduce
> ```
> 1. Call the createIndex interface using pymilvus or java-sdk (without specifying indexType and metricType).
> 2. Invoke the descIndex interface, and the returned results do not include the indexType and metricType fields.
> 3. This results in users being unable to determine the indexType and metricType for current scalar and vector indexes, making it impossible to use the search interface. If users are forced to rely on awareness of kernel default values, any subsequent adjustments to kernel default values would lead to inconsistency in behavior between old and new kernel versions.
> ```
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

Why do we need to describe index while search?
Upon the basic agreement, there should not be any check on client side.
All the metric check are happened on server side

**Comment by lentitude2tk** [comment]
> > ### Is there an existing issue for this?
> > 
> > * [x]   I have searched the existing issues
> > 
> > ### Environment
> > ```
> > - Milvus version: 2.2、2.3
> > - Deployment mode(standalone or cluster):standalone
> > - MQ type(rocksmq, pulsar or kafka): xxx
> > - SDK version(e.g. pymilvus v2.0.0rc2): java-sdk && pymilvus
> > - OS(Ubuntu or CentOS): xxx
> > - CPU/Memory: 
> > - GPU: 
> > - Others:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Current Behavior
> > If CreateIndex does not specify indexType or metricType, the kernel will provide default values, allowing for normal creation.
> > ```
> > private R<RpcStatus> createIndex() {
> >   System.out.println("========== createIndex() ==========");
> >   // create index for vector field
> >   R<RpcStatus> response = milvusClient.createIndex(CreateIndexParam.newBuilder()
> >           .withCollectionName("a")
> >           .withFieldName("Vectorfield")
> >           .withIndexName(INDEX_NAME)
> >           .withExtraParam(INDEX_PARAM)
> >           .withSyncMode(Boolean.TRUE)
> >           .build());
> > 
> >   // create index for scalar field
> >   response = milvusClient.createIndex(CreateIndexParam.newBuilder()
> >           .withCollectionName("a")
> >           .withFieldName("c")
> >           .withIndexName("c")
> >           .withExtraParam(INDEX_PARAM)
> >           .withSyncMode(Boolean.TRUE)
> >           .build());
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > However, the results obtained through the descIndex query do not include indexType and metricType, causing the search interface to be unusable. The descIndex results for vector columns do not provide indexType and metricType.
> > ```
> > R{status=0, data=status {
> > }
> > index_descriptions {
> >   index_name: "userFaceIndex"
> >   indexID: 447168497195892638
> >   params {
> >     key: "params"
> >     value: "{\"nlist\":128}"
> >   }
> >   field_name: "Vectorfield"
> >   state: Finished
> > }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The descIndex results for scalar columns do not include indexType.
> > ```
> > R{status=0, data=status {
> > }
> > index_descriptions {
> >   index_name: "c"
> >   indexID: 447168497195892641
> >   params {
> >     key: "params"
> >     value: "{\"nlist\":128}"
> >   }
> >   field_name: "c"
> >   state: Finished
> > }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Expected Behavior
> > If indexType and metricType are not specified during createIndex, the kernel can set corresponding default values. However, during descIndex, it is necessary to return the currently assigned default indexType and metricType.
> > ### Steps To Reproduce
> > ```
> > 1. Call the createIndex interface using pymilvus or java-sdk (without specifying indexType and metricType).
> > 2. Invoke the descIndex interface, and the returned results do not include the indexType and metricType fields.
> > 3. This results in users being unable to determine the indexType and metricType for current scalar and vector indexes, making it impossible to use the search interface. If users are forced to rely on awareness of kernel default values, any subsequent adjustments to kernel default values would lead to inconsistency in behavior between old and new kernel versions.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Milvus Log
> > _No response_
> > ### Anything else?
> > _No response_
> 
> Why do we need to describe index while search? Upon the basic agreement, there should not be any check on client side. All the metric check are happened on server side

The reason for descIndex is another inconsistency issue. Initially, both pymilvus and milvus-java-sdk search defaulted to passing L2. However, later, pymilvus changed its default behavior to not pass it, but on the milvus-java-sdk side, this adjustment was not synchronized. As a result, when using milvus-java-sdk, it is necessary to pass the metricType, hence the need for descIndex. I will confirm and coordinate with the relevant personnel to align it with pymilvus.

**Comment by yanliang567** [comment]
@czs007 was this fixed?

**Comment by xiaofan-luan** [comment]
we are not gonna to fix this on milvus but more on java sdk side
