### ISSUE TITLE
[Bug]: Segment Loss Due to Garbage Collector Process in Milvus

### ISSUE THREAD

**Issue by Uijeong97** [milvus-io/milvus#30254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.3
- Deployment mode(standalone or cluster): cluster (using milvus-helm)
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.3.5
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 
- GPU: X
- Others:
```

### Description

A problem has arisen in the Milvus system where the garbage collector process is suspected to cause loss of segment data.

### Situation Summary

**failure detection**:

* Query Node restarts and 503 errors occurred at a specific time.
* In Query Coord logs, `NoSuchKey` errors found.

```
[2024/01/17 14:55:46.941 +09:00] [WARN] [task/executor.go:192] ["failed to load segment"] [taskIDs="[1704706239817]"] [collectionID=446878159987278943] [replicaID=446878160436854786] [shard=by-dev-rootcoord-dml_0_446878159987278943v0] [segmentIDs="[446878159991884951]"] [nodeID=140] [source=segment_checker] [error="failed to read stats_log/446878159987278943/446878159987278944/446878159991884951/100/1: NoSuchKey(key=stats_log/446878159987278943/446878159987278944/446878159991884951/100/1)"]
[2024/01/17 14:55:46.941 +09:00] [INFO] [task/executor.go:202] ["execute action done, remove it"] [taskID=1704706239817] [step=0] [error="failed to read stats_log/446878159987278943/446878159987278944/446878159991884951/100/1: NoSuchKey(key=stats_log/446878159987278943/446878159987278944/446878159991884951/100/1)"]
[2024/01/17 14:55:46.967 +09:00] [WARN] [task/scheduler.go:687] ["task scheduler recordSegmentTaskError"] [taskID=1704706239817] [collectionID=446878159987278943] [replicaID=446878160436854786] [segmentID=446878159991884951] [taskStatus=5] [error="failed to read stats_log/446878159987278943/446878159987278944/446878159991884951/100/1: NoSuchKey(key=stats_log/446878159987278943/446878159987278944/446878159991884951/100/1)"]
[2024/01/17 14:55:46.967 +09:00] [WARN] [meta/failed_load_cache.go:97] ["FailedLoadCache put failed record"] [collectionID=446878159987278943] [error="failed to read stats_log/446878159987278943/446878159987278944/446878159991884951/100/1: NoSuchKey(key=stats_log/446878159987278943/446878159987278944/446878159991884951/100/1)"]
```
<br></br>

**Log Analysis**:

* Missing insert_log, delta_log, stats_log files in S3 storage.
  - Specifically, all the segments were empty.

* There is a history of many delete operations performed on object storage.
  - All segments were deleted long before the query node failure.
  - <img width="779" alt="스크린샷 2024-01-24 오후 6 06 54" src="https://github.com/milvus-io/milvus/assets/44829274/f26f31f9-76de-46d1-b174-07a19efc713c">

* All data nodes were disconnected from etcd and there were no logs

```
[2024/01/09 16:30:51.777 +09:00] [WARN] [datanode/event_manager.go:69] ["datanode watch channel canceled"] [error="etcdserver: mvcc: required revision has been compacted"]
[2024/01/09 16:30:51.777 +09:00] [WARN] [sessionutil/session_util.go:890] ["Watch service found compacted error"] [error="etcdserver: mvcc: required revision has been compacted"]
[2024/01/09 16:30:51.777 +09:00] [INFO] [datanode/event_manager.go:48] ["Start watch channel"] [prefix=channelwatch/135]
[2024/01/09 16:35:01.436 +09:00] [WARN] [grpclog/grpclog.go:46] ["[core][Channel #4 SubChannel #5] grpc: addrConn.createTransport failed to connect to {\n  \"Addr\": \"paip-etcd-milvus-headless.pai-staging-milvus.svc.cluster.local:2379\",\n  \"ServerName\": \"paip-etcd-milvus-headless.pai-staging-milvus.svc.cluster.local\",\n  \"Attributes\": null,\n  \"BalancerAttributes\": null,\n  \"Type\": 0,\n  \"Metadata\": null\n}. Err: connection error: desc = \"error reading server preface: read tcp 10.175.134.101:38998->10.175.140.38:2379: read: connection reset by peer\""]
[2024/01/09 16:35:01.436 +09:00] [WARN] [grpclog/grpclog.go:46] ["[core][Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {\n  \"Addr\": \"paip-etcd-milvus-headless.pai-staging-milvus.svc.cluster.local:2379\",\n  \"ServerName\": \"paip-etcd-milvus-headless.pai-staging-milvus.svc.cluster.local\",\n  \"Attributes\": null,\n  \"BalancerAttributes\": null,\n  \"Type\": 0,\n  \"Metadata\": null\n}. Err: connection error: desc = \"error reading server preface: read tcp 10.175.134.101:39000->10.175.140.38:2379: read: connection reset by peer\""]
[2024/01/09 16:37:59.905 +09:00] [WARN] [grpclog/grpclog.go:46] ["[core][Channel #4 SubChannel #5] grpc: addrConn.createTransport failed to connect to {\n  \"Addr\": \"paip-etcd-milvus-headless.pai-staging-milvus.svc.cluster.local:2379\",\n  \"ServerName\": \"paip-etcd-milvus-headless.pai-staging-milvus.svc.cluster.local\",\n  \"Attributes\": null,\n  \"BalancerAttributes\": null,\n  \"Type\": 0,\n  \"Metadata\": null\n}. Err: connection error: desc = \"error reading server preface: read tcp 10.175.134.101:49662->10.175.142.216:2379: read: connection reset by peer\""]
[2024/01/09 16:37:59.905 +09:00] [WARN] [grpclog/grpclog.go:46] ["[core][Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {\n  \"Addr\": \"paip-etcd-milvus-headless.pai-staging-milvus.svc.cluster.local:2379\",\n  \"ServerName\": \"paip-etcd-milvus-headless.pai-staging-milvus.svc.cluster.local\",\n  \"Attributes\": null,\n  \"BalancerAttributes\": null,\n  \"Type\": 0,\n  \"Metadata\": null\n}. Err: connection error: desc = \"error reading server preface: read tcp 10.175.134.101:49664->10.175.142.216:2379: read: connection reset by peer\""]
{"level":"warn","ts":"2024-01-10T14:37:03.099+0900","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0003de000/paip-etcd-milvus-headless.pai-staging-milvus.svc.cluster.local:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
[2024/01/10 14:37:03.099 +09:00] [ERROR] [config/refresher.go:72] ["can not pull configs"] [error="context deadline exceeded"] [stack="github.com/milvus-io/milvus/pkg/config.(*refresher).refreshPeriodically\n\t/opt/bitnami/milvus/pkg/config/refresher.go:72"]

```

* Running birdwatcher `verify-segment` command, I found `failed to check` log in all segments (insert_log, stats_log)
```
path files/insert_log/446878159987278943/446878159987278944/446878159993887323/103/446878159993626093 false
failed to check  files/insert_log/446878159987278943/446878159987278944/446878159993887323/103/446878159993642451 The specified key does not exist. NoSuchKey
path files/insert_log/446878159987278943/446878159987278944/446878159993887323/103/446878159993642451 false
failed to check  files/insert_log/446878159987278943/446878159987278944/446878159993887323/103/446878159993658809 The specified key does not exist. NoSuchKey
path files/insert_log/446878159987278943/446878159987278944/446878159993887323/103/446878159993658809 false
failed to check  files/insert_log/446878159987278943/446878159987278944/446878159993887323/103/446878159993668249 The specified key does not exist. NoSuchKey
path files/insert_log/446878159987278943/446878159987278944/446878159993887323/103/446878159993668249 false
Segment(446878159993887323) binlog done
failed to check  files/stats_log/446878159987278943/446878159987278944/446878159993887323/100/446878159993609732 The specified key does not exist. NoSuchKey
failed to check  files/stats_log/446878159987278943/446878159987278944/446878159993887323/100/446878159993626090 The specified key does not exist. NoSuchKey
failed to check  files/stats_log/446878159987278943/446878159987278944/446878159993887323/100/446878159993642448 The specified key does not exist. NoSuchKey
failed to check  files/stats_log/446878159987278943/446878159987278944/446878159993887323/100/446878159993658806 The specified key does not exist. NoSuchKey
failed to check  files/stats_log/446878159987278943/446878159987278944/446878159993887323/100/446878159993668246 The specified key does not exist. NoSuchKey
failed to check  files/stats_log/446878159987278943/446878159987278944/446878159993887323/100/1 The specified key does not exist. NoSuchKey
Segment(446878159993887323) statslog done
Segment(446878159993887323) deltalog done
```

* Running birdwatcher `storage-analysis` command, I found `key does not exist` log in all segments.
<img width="444" alt="스크린샷 2024-01-24 오후 6 11 29" src="https://github.com/milvus-io/milvus/assets/44829274/3240eeb1-9a3f-4d52-a349-4a2de81f40d8">

<br></br>

**Cause Analysis**:

* 0108: Data bulk insert performed.
* 0108: Connection between data node and etcd interrupted.
* 0109-0110: All segments in object storage deleted.
* 0116: Query node restarts; search query problem arise.

I thought garbage collect was the cause of the deletion of all segments.
And I think the connection between etcd and the datanode is closed, which can cause GC.
but if there is something else, please explain.

### Anything else?

**Questions:**

1. How does the garbage collector function when the Data Node loses connection with etcd?

I know that garbage collectors delete segments not found in etcd but present in s3.
But, this case is different, as segments are in meta but not in S3.
How do I make sense of this situation?

2. How does k8s pod's liveness detection work during etcd and S3 communication loss?

The data node's etcd connection was lost, but the pod was still running.
This suggests that the livenessProbe didn't detect the failure.

3. Transaction handling and rollback mechanisms of the garbage collector.

Deletions from S3 were not reflected in etcd. 
In my opinion, deleting segment from etcd, s3, should be managed as a transaction for greater reliability.
Also, I was wondering if there is a rollback mechanism for errors during garbage collection.

**Additional Questions**

4. What role does etcd play in the data node and query node?

I assumed coordinators use etcd, and worker nodes use S3. 
But the code shows worker nodes accessing etcd too.

I apologize for the many questions.
I look forward to your answers.

**Comment by yanliang567** [comment]
/assign @congqixia 
was this fixed in milvus 2.3.6? could you please help to answer the questions above?

**Comment by xiaofan-luan** [comment]
> ### Anything else?
> **Questions:**
> 
> 1. How does the garbage collector function when the Data Node loses connection with etcd?
> 
> I know that garbage collectors delete segments not found in etcd but present in s3. But, this case is different, as segments are in meta but not in S3. How do I make sense of this situation?
> 
> 2. How does k8s pod's liveness detection work during etcd and S3 communication loss?
> 
> The data node's etcd connection was lost, but the pod was still running. This suggests that the livenessProbe didn't detect the failure.
> 
> 3. Transaction handling and rollback mechanisms of the garbage collector.
> 
> Deletions from S3 were not reflected in etcd. In my opinion, deleting segment from etcd, s3, should be managed as a transaction for greater reliability. Also, I was wondering if there is a rollback mechanism for errors during garbage collection.
> 
> **Additional Questions**
> 
> 4. What role does etcd play in the data node and query node?

Hi @Uijeong97 

Thanks, for the detailed feedback. Your analysis is very close to what might happen.
We have fixed some of the issues might be related,

like: https://github.com/milvus-io/milvus/issues/29691 this is due to etcd operation is not performed as transaction

Those fix should be very corner cases and shouldn't affect all your segments.

If all your segment is garbage collected, this might means:
1. the collection is dropped and their might be a inconsistency between meta and data - check the log see if the collection has been dropped.
2. there might be another cluster use the same object storage and the other cluster did gc. Please make sure all the cluster has own its cluster prefix .

**Comment by xiaofan-luan** [comment]
Regarding to your questions

Questions:

How does the garbage collector function when the Data Node loses connection with etcd?
If etcd are not serviceable, then datacoord for abort itself after session timeout. And all etcd access will fail and no garbage collection can proceed.
Currently, by default settings, a file will not be garbage collected after its creation in 3 hours. If there are certain cases where we create a file on object storage and did etcd operation after 3 hours that might be dangerous. But so far i believe there are no such path.

How does k8s pod's liveness detection work during etcd and S3 communication loss?
All milvus node will panic under etcd failure. Under S3 failure,all the node should still be alive but not able to do compaction, flush, load and gc.

The data node's etcd connection was lost, but the pod was still running.
Datanode should trigger a stop and will panic after a while

Transaction handling and rollback mechanisms of the garbage collector.
1. first step is mark etcd as drop
2. drop S3
3. drop etcd keyvalue
4. scan S3 and find orphan files, this usaully happens if I write a S3 file but not able to sync etcd yet but got crash.
There are no rollback currently.

Additional Questions

What role does etcd play in the data node and query node?
etcd works as service discovery for all nodes. It also works as meta store for coordinator

**Comment by Uijeong97** [comment]
@xiaofan-luan 

Thank you for answer.

>1. the collection is dropped and their might be a inconsistency between meta and data - check the log see if the collection has been dropped.

The collection was not deleted; it was in a loaded state. 
The issue surfaced 7 days after the query node restarted. 
The key difference I noticed was the disconnection of the data node from etcd.

> 2. there might be another cluster use the same object storage and the other cluster did gc. Please make sure all the cluster has own its cluster prefix .

This situation doesn't apply to my case. I only share a log broker (Kafka) with multiple Milvus clusters.

> like: https://github.com/milvus-io/milvus/issues/29691 this is due to etcd operation is not performed as transaction

The PR you mentioned seems to synchronize segmentInfo in ETCD with data coord memory path information during compaction. 
In my situation, there was no compaction, and all segments were deleted.

It seems that the issues you mentioned don't apply to my case.
I believe that disconnecting the data node from etcd might reproduce the problem.

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan
> 
> Thank you for answer.
> 
> > 1. the collection is dropped and their might be a inconsistency between meta and data - check the log see if the collection has been dropped.
> 
> The collection was not deleted; it was in a loaded state. The issue surfaced 7 days after the query node restarted. The key difference I noticed was the disconnection of the data node from etcd.
> 
> > 2. there might be another cluster use the same object storage and the other cluster did gc. Please make sure all the cluster has own its cluster prefix .
> 
> This situation doesn't apply to my case. I only share a log broker (Kafka) with multiple Milvus clusters.
> 
> > like: #29691 this is due to etcd operation is not performed as transaction
> 
> The PR you mentioned seems to synchronize segmentInfo in ETCD with data coord memory path information during compaction. In my situation, there was no compaction, and all segments were deleted.
> 
> It seems that the issues you mentioned don't apply to my case. I believe that disconnecting the data node from etcd might reproduce the problem.

When datacoord disconnect from etcd, it should directly abort itself, but in your case it's not?

**Comment by xiaofan-luan** [comment]
please provide more detailed logs for further investigation, datacoord logs could be enough.

So you are saying your datacoord is disconnected with etcd since Jan 8, but it is not stopped until Jan 9, might be due to an unfinished bulkinsert?

**Comment by xiaofan-luan** [comment]
0108: Data bulk insert performed.
0108: Connection between data node and etcd interrupted.
0109-0110: All segments in object storage deleted.
0116: Query node restarts; search query problem arise.

0116 is the date right? what happened between 0108 and 0109?
do we still have the datacoord log of 0108?

**Comment by congqixia** [comment]
@yanliang567 Previously known issue about data loss is fixed in v2.3.2. So this shall not be same root cause from meta scan & oss scan sequence problem.

Currently, this only known similar case is #30165, which is caused by fast garbage collection after compaction

**Comment by xiaofan-luan** [comment]
> @yanliang567 Previously known issue about data loss is fixed in v2.3.2. So this shall not be same root cause from meta scan & oss scan sequence problem.
> 
> Currently, this only known similar case is #30165, which is caused by fast garbage collection after compaction

The user is using 2.3.3

**Comment by Uijeong97** [comment]
@xiaofan-luan 

> When datacoord disconnect from etcd, it should directly abort itself, but in your case it's not?

The data coord was not disconnected from etcd, only the data node was disconnected from etcd

> please provide more detailed logs for further investigation, datacoord logs could be enough.

I would have provided it, but the K8S policy deleted stdout due to overflowing log capacity. 🥲
I have modified the value to leave the log on the filesystem.

> So you are saying your datacoord is disconnected with etcd since Jan 8, but it is not stopped until Jan 9, might be due to an unfinished bulkinsert?

The bulk insert was completed and the collection loaded without a hitch. 
The data code was not the problem, the data node was disconnected.

--


There doesn't seem to be anything known about this issue.
I will experiment to see if it is reproducible when disconnecting the data node.

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan
> 
> > When datacoord disconnect from etcd, it should directly abort itself, but in your case it's not?
> 
> The data coord was not disconnected from etcd, only the data node was disconnected from etcd
> 
> > please provide more detailed logs for further investigation, datacoord logs could be enough.
> 
> I would have provided it, but the K8S policy deleted stdout due to overflowing log capacity. 🥲 I have modified the value to leave the log on the filesystem.
> 
> > So you are saying your datacoord is disconnected with etcd since Jan 8, but it is not stopped until Jan 9, might be due to an unfinished bulkinsert?
> 
> The bulk insert was completed and the collection loaded without a hitch. The data code was not the problem, the data node was disconnected.
> 
> --
> 
> There doesn't seem to be anything known about this issue. I will experiment to see if it is reproducible when disconnecting the data node.

If we can reproduce this and share logs, maybe we can find more clues.
My wild guess is that milvus stayed up while etcd disconnected. it would be great if we have a pprof so we can understand why milvus stuck at stop
