### ISSUE TITLE
[Bug]: Partition key optimization is not applied to requery process

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#30250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master & 2.3.6
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When a search contains vector output fields, it shall retrieve via `Requery` process. Now requery cannot utilize partition key optimization to reduce segment number when querying.

### Expected Behavior

Utilize pre-calculated partition ids when doing requery

**Comment by xiaofan-luan** [comment]
this has to be in 2.3.6

**Comment by congqixia** [comment]
mark as completed
