### ISSUE TITLE
[Bug]: flush cause vectordb crash

### ISSUE THREAD

**Issue by Simple6K** [milvus-io/milvus#30268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.3.1
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus2.3.2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

当我插入使用客户端的方式连接向量库，client = MilvusClient(-----)，在插入数据client.inster或删除数据client.delte后，使用clien.flush提交后，在批量的情况下会引起向量库的奔溃，

**Comment by yanliang567** [comment]
@Simple6K how many vectors did you insert and how many did you delete? how much resource(cpu & memory)did you limit for the milvus pods?  Could you please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.

/assign @Simple6K 
/unassign

**Comment by xiaofan-luan** [comment]
by the way, we recommend to use milvus 2.3.5 or above

**Comment by Simple6K** [comment]
@yanliang567 我没办法给查到日志，我用了文档的方法导出文档发现一个问题。该bug会导致向量库节点奔溃，然后自动重启，每次重启就会刷新覆盖一个新的。但是我可以描述我的数据量.插入是一个持续的过程，每次20个inster请求同时发起，每个请求一条长度1024，一直持续到共2000次，删除则是数百个请求，也是类似需要删掉2000次。我也有批量多个的请求，但是在高频次的情况下，flush很容易奔溃，同时我还测试到在持续插入的过程中，如果使用查询，会直接奔溃，需要手动重启向量库。

**Comment by Simple6K** [comment]
@xiaofan-luan 我的项目在23年的10月启动，11月确定服务器环境使用2.3.2已经是最新，你不可能24年1月分上线了2.3.5就说推荐使用2.3.5或最高，这是不合理的，若明确2.3.5会解决该问题，同时该类似的问题，在21年已经有类似的问题出现，我猜测是因为向量库的一致性问题导致的，我试过把级别降到最低，也只是有所缓解，却无法解决。

**Comment by yanliang567** [comment]
we cannot tell the root cause without logs, but according to the descriptions above, I guess there are too many insert/delete requests for the MQ to hold(or for the datanode to hold). please try to add more resource to the MQ and datanode.  @Simple6K

**Comment by xiaofan-luan** [comment]
> @yanliang567 我没办法给查到日志，我用了文档的方法导出文档发现一个问题。该bug会导致向量库节点奔溃，然后自动重启，每次重启就会刷新覆盖一个新的。但是我可以描述我的数据量.插入是一个持续的过程，每次20个inster请求同时发起，每个请求一条长度1024，一直持续到共2000次，删除则是数百个请求，也是类似需要删掉2000次。我也有批量多个的请求，但是在高频次的情况下，flush很容易奔溃，同时我还测试到在持续插入的过程中，如果使用查询，会直接奔溃，需要手动重启向量库。

1. please use english if possible, there are many non chinese speaker in the community
2. we will need to get detailed logs until we can do further investigation
3. There are many reasons might cause your node crash, like out of disk space, out of memory. may be you can analyze by yourself for some basics, like memory, disk and error message. I won't say this is a BUG until we get more details

**Comment by Simple6K** [comment]
这是一个很容易复现的错误。只要启动一个最低条件的K8S部署的分布式milvus，for循环一万次inster+flush的操作，每次一条1024的数据，集合的索引选择autoindex。或许这不是一个错误，但至少是一个缺陷，milvus数据库本身应该对这种频繁请求设置一个阈值，用来保护自身不会奔溃，建议后期还是添加类似连接池，使用最大连接数来保护向量库。目前我们在检测磁盘和内存没有发现溢出，同时目前这个向量库的奔溃带来一个新的问题：
1、在上述的奔溃中，如果collection中已有数据，重启后会出现collection无法查询或插入的情况，但它可以loading。
2、如果要解决这个问题需要把原有collection删掉重新建才可以修复。
3、后面我进一步尝试发现这个原因是因为创建collection时，一致性级别选择Bounded ，特别是strong时，不用奔溃也会无法使用。最后我选择了最低级别的Consistency才保证在向量库奔溃后能够继续插入使用。
4、所以根据上述情况，我更多地倾向于认为向量库在做一致性同步时，在面对高频率flush时产生的IO，会因为不及时出现错误导致向量库奔溃，同时该问题在重启后无法自我恢复。
最后，因为我们自己无法解决milvus在频繁flush时奔溃的问题，我们决定在项目的下一个版本放弃了milvus的使用，很感谢各位社区大佬的回复。 @yanliang567 @xiaofan-luan

**Comment by yanliang567** [comment]
@Simple6K thank you for your feedbacks. May I ask the reasons that you need to manually call flush() so frequently after every insert(). As we mentioned in milvus.io, calling flush() too frequently fragmented data, and every flush() request leads to heavy IO operations.  https://milvus.io/docs/insert_data.md#Flush-the-Data-in-Milvus.
Additionally, you can enable flush rate to protect milvus from frequently flush() by setting quotaAndLimits.flushRate.enabled
```
quotaAndLimits:  
  flushRate:
    enabled: true
    max: 1      # 1 request per second
```
In the community release, we don't enable it by default because different users have different scenarios, and we leave the options to users. 
BTW, if you don't want to maintain milvus cluster yourself, please try [zilliz cloud ](https://zilliz.com.cn/), which provides cloud-native experience with a complete feature set, and we have hangzhou and beijing region available in China.
Thanks again for your interests.

**Comment by xiaofan-luan** [comment]
> 这是一个很容易复现的错误。只要启动一个最低条件的K8S部署的分布式milvus，for循环一万次inster+flush的操作，每次一条1024的数据，集合的索引选择autoindex。或许这不是一个错误，但至少是一个缺陷，milvus数据库本身应该对这种频繁请求设置一个阈值，用来保护自身不会奔溃，建议后期还是添加类似连接池，使用最大连接数来保护向量库。目前我们在检测磁盘和内存没有发现溢出，同时目前这个向量库的奔溃带来一个新的问题： 1、在上述的奔溃中，如果collection中已有数据，重启后会出现collection无法查询或插入的情况，但它可以loading。 2、如果要解决这个问题需要把原有collection删掉重新建才可以修复。 3、后面我进一步尝试发现这个原因是因为创建collection时，一致性级别选择Bounded ，特别是strong时，不用奔溃也会无法使用。最后我选择了最低级别的Consistency才保证在向量库奔溃后能够继续插入使用。 4、所以根据上述情况，我更多地倾向于认为向量库在做一致性同步时，在面对高频率flush时产生的IO，会因为不及时出现错误导致向量库奔溃，同时该问题在重启后无法自我恢复。 最后，因为我们自己无法解决milvus在频繁flush时奔溃的问题，我们决定在项目的下一个版本放弃了milvus的使用，很感谢各位社区大佬的回复。 @yanliang567 @xiaofan-luan

Thanks for the notification. We will fix the bug if we can repproduce it. 
However, if there are no more detailed logs, there is nothing we can futher help .
