### ISSUE TITLE
[Bug]: failed to write part of pymilvus insert "failed to connect to all addresses"

### ISSUE THREAD

**Issue by dengxiaohai** [milvus-io/milvus#30267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.3
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.3.3
- OS(Ubuntu or CentOS): CentOS8
```

### Current Behavior

4 proxies, and the following problems occur when tps exceeds 20。With the increase of TPS, there will be approximately 1-3 connection failures for 20,000 write operations：

<MilvusException: (code=<bound method _MultiThreadedRendezvous.code of <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:xxxx:19530: tcp handshaker shutdown"
        debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:xxxx:19530: tcp handshaker shutdown {grpc_status:14, created_time:"2024-01-24T18:52:24.929049287+08:00"}"
>>, message=Retry run out of 75 retry times, message=failed to connect to all addresses; last error: UNKNOWN: ipv4:xxxx:19530: tcp handshaker shutdown)>

### Steps To Reproduce

```markdown
In writing tests with Pymilvus, this problem occurs when the TPS exceeds 20
```

### Milvus Log

<MilvusException: (code=<bound method _MultiThreadedRendezvous.code of <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:xxxx:19530: tcp handshaker shutdown"
        debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:xxxx:19530: tcp handshaker shutdown {grpc_status:14, created_time:"2024-01-24T18:52:24.929049287+08:00"}"
>>, message=Retry run out of 75 retry times, message=failed to connect to all addresses; last error: UNKNOWN: ipv4:xxxx:19530: tcp handshaker shutdown)>

### Anything else?

no

**Comment by yanliang567** [comment]
@dengxiaohai i guess the MQ or minio is not able to hold the high throughput of insert. Could you please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.
/assign @dengxiaohai 
/unassign

**Comment by darkar18** [comment]
Facing the same issue:

```ERROR 20-02-2024 14:30:38 : req[a3fd8e52] : handler - RPC error: [has_collection], <MilvusException: (code=<bound method _MultiThreadedRendezvous.code of <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:192.168.16.4:19530: Failed to connect to remote host: No route to host"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:192.168.16.4:19530: Failed to connect to remote host: No route to host", grpc_status:14, created_time:"2024-02-20T14:30:38.03824538+05:30"}"
>>, message=Retry run out of 75 retry times, message=failed to connect to all addresses; last error: UNKNOWN: ipv4:192.168.16.4:19530: Failed to connect to remote host: No route to host)>, <Time:{'RPC start': '2024-02-20 14:27:07.127517', 'RPC error': '2024-02-20 14:30:38.038661'}>
INFO  20-02-2024 14:30:38 : req[a3fd8e52] : custom_route_handler - [API EXCEPTION] Curropted Base64```

**Comment by xiaofan-luan** [comment]
> Facing the same issue:
> 
> ```
> 	status = StatusCode.UNAVAILABLE
> 	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:192.168.16.4:19530: Failed to connect to remote host: No route to host"
> 	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:192.168.16.4:19530: Failed to connect to remote host: No route to host", grpc_status:14, created_time:"2024-02-20T14:30:38.03824538+05:30"}"
> >>, message=Retry run out of 75 retry times, message=failed to connect to all addresses; last error: UNKNOWN: ipv4:192.168.16.4:19530: Failed to connect to remote host: No route to host)>, <Time:{'RPC start': '2024-02-20 14:27:07.127517', 'RPC error': '2024-02-20 14:30:38.038661'}>
> INFO  20-02-2024 14:30:38 : req[a3fd8e52] : custom_route_handler - [API EXCEPTION] Curropted Base64```
> ```

this seems to be a network issue.
You could try to ping 192.168.16.4 from your client see if it is connectable.

Under most cases, you failed to export port outside k8s or you have some firewall

**Comment by darkar18** [comment]
Thanks for the reply, it randomly seems to disconnect. It could be working fine for 30 hours or more but then abruptly causes disconnection error mentioned above, sorry I couldn't reproduce the issue at will. Don't know what's causing it.

**Comment by weiyusheng** [comment]
Well, I met this problem too. After some test, I can always reproduce it by using Process from multiprocessing with pymilvus.
Only if I tried to connect the database in a subprocess of python, the connection would never success.
Env:

milvus&pymilvus 2.4.0
python 3.11.5
multiprocessing  0.70.14

Here are some test python code:

from pymilvus import (
    connections,
)

class RetrieveDatabase:
    def __init__(self, host, port):
        connections.connect(host = host, port = port)

if __name__ == "__main__":
    host = ""
    port = ""
    db = RetrieveDatabase(host, port)
    from multiprocessing import Process
    p = Process(target=RetrieveDatabase, args=(host, port, ))
    p.start()
    p.join()

@yanliang567 @xiaofan-luan

**Comment by XuanYang-cn** [comment]
@weiyusheng This is a known issue of using grpc channel with multiprocessing. Try setting start method spawn, this will fix the dead lock.

```python
import multiprocessing as mp
mp.set_start_method("spawn", force=True)
```

**Comment by weiyusheng** [comment]
Thanks for your rapid reply. It works.Thanks again.
