### ISSUE TITLE
[Enhancement]: Is it possible to increase supported vector dimensions?

### ISSUE THREAD

**Issue by Rroscha** [milvus-io/milvus#30285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Hi,
Is it possible to increase the supported vector dimensions?
I notice that the current version only supports dimensions between 1 to 32768, however, in our scenario, we need 65536 dimensions for one sample.

### Why is this needed?

In our scenario, we need a 65536-dimensional vector for one sample; otherwise, the performance in the retrieving task will decrease significantly.

**Comment by Rroscha** [comment]
Hi， I also wonder if we directly change the constraint from DefaultMaxDim = 32768 to DefaultMaxDim = 65536, does Milvus system still work?

**Comment by xiaofan-luan** [comment]
32768 is usually a very large dim limitation. 

For most of the existing models, dimension is usually less than 4096.
What model did you use? is it sarse embedding or dense embedding?

**Comment by xiaofan-luan** [comment]
I'm not sure if binary vector has same dimension limitation.
the limitation is usually float vector

**Comment by Rroscha** [comment]
> I'm not sure if binary vector has same dimension limitation. the limitation is usually float vector

Could we change the dimension constraint in code (https://github.com/milvus-io/milvus/blob/a27c0e86fde05b4409bfa7130b62e0089d25bad0/pkg/util/indexparamcheck/constraints.go#L21) to avoid this limitation for binary vector? 

We have used faiss previously with hamming distance in 65536 dimensions, but faiss right now does not support jaccard distance.

**Comment by Rroscha** [comment]
> I believe 65536 should be doable.
> 
> We just need more clue on the limitation in knowhere

Ok, thank you very much!

**Comment by yanliang567** [comment]
/assign @elstic 
please help to update the e2e tests accordingly when the pr merged.

**Comment by elstic** [comment]
> /assign @elstic please help to update the e2e tests accordingly when the pr merged.

ok,  @xiaofan-luan  is the limit on the maximum dimension of binary vectors removed? Instead of adjusting the maximum binary dimension?

**Comment by elstic** [comment]
> ok, @xiaofan-luan is the limit on the maximum dimension of binary vectors removed? Instead of adjusting the dimension of the maximum binary vector?

When I set very large dimensional binary vectors to initialize the collection I get an error ``binary vector dimension should be in range 2 ~ 262144``, is the maximum dimension limit 21643?

**Comment by xiaofan-luan** [comment]
> > ok, @xiaofan-luan is the limit on the maximum dimension of binary vectors removed? Instead of adjusting the dimension of the maximum binary vector?
> 
> When I set very large dimensional binary vectors to initialize the collection I get an error `binary vector dimension should be in range 2 ~ 262144`, is the maximum dimension limit 262144?

Yes it is 8 times of 32768 by default

**Comment by xiaofan-luan** [comment]
not sure what might happen for larger dimensions so I keep it convervative

**Comment by elstic** [comment]
> > > ok, @xiaofan-luan is the limit on the maximum dimension of binary vectors removed? Instead of adjusting the dimension of the maximum binary vector?
> > 
> > 
> > When I set very large dimensional binary vectors to initialize the collection I get an error `binary vector dimension should be in range 2 ~ 262144`, is the maximum dimension limit 262144?
> 
> Yes it is 8 times of 32768 by default

ok
