### ISSUE TITLE
[Bug]: Datacoord hang under stop 

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#30310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. currently, etcd disconnect will trigger SIGINT
2. SIGINT will wait for all ther request done, which may take very long time than expectation.
3. If that happens, garbage collector and the compaction trigger may run some on expected logic while datacoord is not leader

**Comment by yanliang567** [comment]
keep it

**Comment by yanliang567** [comment]
keep it
