### ISSUE TITLE
[Bug]: standalone version,10000 data, but milvus-standalone memory increased over 8G.

### ISSUE THREAD

**Issue by rushant001** [milvus-io/milvus#30325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:milvus-standalone
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):   None 
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.13
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 4C 8G
- GPU: 
- Others: deploy by image in k8s cluster
```

### Current Behavior

when I read and write 10000 vectors(1024 dim) to milvus for 2 month, it`s memory inscreased to 8G.

### Expected Behavior

The memory iincreased too fast.

### Steps To Reproduce

```markdown
1. read and write. About 20 times one day.
```

### Milvus Log

None

### Anything else?

None

**Comment by xiaofan-luan** [comment]
1. can you share what is the version of milvus?
2. and logs?
3. if you keep inserting into milvus, how did you purge you data? is is by delete of ttl?

**Comment by yanliang567** [comment]
@rushant001 Could you please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.
/assign @rushant001 
/unassign

**Comment by xiaofan-luan** [comment]
if you insert 10000 data 20 times, then you get 200000 data for each day,
For a 8GB memory node, it holds 1.5M 768 dimension vector data at most
