### ISSUE TITLE
[Bug]: some typo

### ISSUE THREAD

**Issue by smellthemoon** [milvus-io/milvus#30322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

some typo
<img width="1071" alt="1" src="https://github.com/milvus-io/milvus/assets/64083300/52a460d9-ccbf-4bf7-a0da-897b0d53cf66">

**Comment by yanliang567** [comment]
keep it

**Comment by smellthemoon** [comment]
will do the change in null feature pr.
