### ISSUE TITLE
[Bug]: Exception while trying to get field data

### ISSUE THREAD

**Issue by madogar** [milvus-io/milvus#30340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

We created a collection(dpc_test_collection) with fields userFace(vector field) and userAge(int), inserted sample rows and did ANN search with search expression "userAge > 50". While trying to get field data we get exception message as "io.milvus.exception.ParamException: Illegal field name: userAge". Following is the code for search logic and the exception is thrown for the final statement wrapper.getFieldData(AGE_FIELD, i):

    String searchExpr = AGE_FIELD + " > 50";

    log.info("========== searchFace() ==========");
    long begin = System.currentTimeMillis();

    List<String> outFields = Collections.singletonList(AGE_FIELD);
    List<List<Float>> vectors = generateFloatVectors(5);

    SearchParam searchParam =
        SearchParam.newBuilder()
            .withCollectionName(DPC_TEST_COLLECTION)
            .withMetricType(MetricType.L2)
            .withOutFields(outFields)
            .withTopK(SEARCH_K)
            .withVectors(vectors)
            .withVectorFieldName(VECTOR_FIELD)
            .withExpr(searchExpr)
            .withParams(SEARCH_PARAM)
            .build();

    R<SearchResults> searchResponse = milvusClient.getMilvusServiceClient().search(searchParam);
    handleResponseStatus(searchResponse);
    long end = System.currentTimeMillis();
    long cost = (end - begin);
    log.info("Search time cost: " + cost + "ms");

    SearchResultsWrapper wrapper = new SearchResultsWrapper(searchResponse.getData().getResults());
    for (int i = 0; i < vectors.size(); ++i) {
      log.info(
          "Search result of No. {} has scores {} and output field as {}",
          i,
          wrapper.getIDScore(i),
          wrapper.getFieldData(AGE_FIELD, i));
    }

### Expected Behavior

We expected the rows in response to contain userAge field.

### Anything else?

[milvus_query_logs.json](https://github.com/milvus-io/milvus/files/14083736/milvus_query_logs.json)

**Comment by yanliang567** [comment]
what's the version of your milvus and java sdk? 
/assign @madogar 
/unassign

**Comment by madogar** [comment]
You can see the exact exception in the logs at line 14:
io.milvus.exception.ParamException: Illegal field name: userAge\n\tat io.milvus.response.SearchResultsWrapper.getFieldData(SearchRes    ultsWrapper.java:100)

**Comment by xiaofan-luan** [comment]
and the segment 

> You can see the exact exception in the logs at line 14: io.milvus.exception.ParamException: Illegal field name: userAge\n\tat io.milvus.response.SearchResultsWrapper.getFieldData(SearchRes ultsWrapper.java:100)

I think there is some wrong with your expression?

userAge\n\tat

There shouldn't be any \n in your expression?

**Comment by xiaofan-luan** [comment]
<img width="578" alt="image" src="https://github.com/milvus-io/milvus/assets/83447078/2a88eddd-ebf2-4fd9-82ed-70047f9d0a95">

from the code, the fieldname you pass in is with \n and \tat

**Comment by madogar** [comment]
@xiaofan-luan \n and \tat are coming from the log dump/export tool that I am using. The actual expression in the code is(I have pasted entire code in the bug description as well):
String searchExpr = AGE_FIELD + " > 50";

where variable AGE_FIELD="userAge"

**Comment by madogar** [comment]
Also, re-iterating the same code is scheduled to run once in 15 mins and works fine most of the times. There are only sporadic errors(like 5-6 times a day).

**Comment by yanliang567** [comment]
/assign @yhmo 
please help to take a look
/unassign

**Comment by madogar** [comment]
hi, any update on this issue?

**Comment by yanliang567** [comment]
> hi, any update on this issue?

sorry for the late response, as we are on the chinese new year. 
@yhmo could you please take a look at this

**Comment by yhmo** [comment]
I could not reproduce this issue.
There is only one possible reason cause this error "Illegal field name: xxx":  the server returns a result that doesn't contain this field.
