### ISSUE TITLE
[Bug]: Bulk Insert not working properly due to flush failures

### ISSUE THREAD

**Issue by roy-akash** [milvus-io/milvus#30359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.5
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): kafka (MSK)
- SDK version(e.g. pymilvus v2.0.0rc2): java
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I have a client that is calling the bulk insert API and trying to insert data into milvus. Initially the bulk insert API was working as expected but we had to restart all the milvus components i.e workers and coordinators multiple times. 

After these restarts the rate of ingestion via bulk insert drastically reduced. from 2million vectors per minute -> 30k per minute

Also i can see segment missing error logs in active data-coordinator

### Expected Behavior

Even with restarts for milvus components there should be a recovery mechanism that guarantees optimal rate of ingestion via Bulk Insert API .

### Steps To Reproduce

```markdown
1. Repeatedly call bulk insert API
2. Repeatedly restart all components every 15 mins
```

### Milvus Log

[2024/01/30 05:01:34.127 +00:00] [INFO] [datacoord/services.go:1421] ["start flushing segments"] [traceID=2660b8a836542b07cf1e61559d567412] ["segment IDs"="[447370961137897595,447367497959742841,447369701551505648,447369071816683303,447370016479327759,447366573366520767,447366869925575747,447370331932528251,447369071816281797,447369071816886726,447367497959342182,447368124667145430,447368124667145429,447370016479329458,447370016478724688,447367497959943561,447368124666740885,447370331932929380,447367188670597514,447367497959947724,447367188669993637,447369383860055582,447368124666941624,447368124667145511,447370016479327770,447368757275081951,447369383859854760,447370961138100279,447370016479327560,447367497959542560,447368440776044049,447369071816683379,447370331933133551,447369701551911488,447367812499575251,447370961137697178,447368757275080599,447369701551706340,447368440776044295,447368440776044293,447368440776045916,447369071816482228,447370961137697292,447367497960148226,447370647651826679,447366573366520781,447368440775642728,447367188670194015,447370961138098692,447367188670594335,447366869925574407,447370647651623430,447367497959947642,447370331932929713,447368757274878443,447370647651422536,447369383859654090,447367188670597513,447370647651825077,447368124666740926,447367188670594336,447368440776047527,447368757274880233,447366869924970773,447366869925575748,447370331932933079,447368440775843258,447366573366520779,447367812499976048,447366573366720890,447367812499976127,447368757274476982,447369383860055873,447369701551911483,447367812500379585,447368757274677600,447366869925170844,447368757274878556,447367812499976317,447370647651221556,447370016478724619,447368757275081700,447370647651826642,447369071816885332,447366869925572198,447366869925572274,447368440775642730,447366869925371175,447367812500379586,447368124667145431,447368757274878096,447370331932929790,447368757274878519,447370016479125931,447370647651623080,447369701552311626,447370016478925201,447370647651825079,447369383860057514,447370331932528249,447369383860059148,447368440776044280,447369383860055804,447367812499374427,447367188670595812,447368440776045917,447367812500379587,447367188669792290,447369071816682886,447370647651623429,447369383860057616,447370961138101967,447367497959947644,447370331932929982,447367188670595811,447370331932931547,447369071816281760,447366869925574182,447367497959947643,447370331932728610,447366869925572276,447367812500379583,447368757274476981,447370647651221554,447370961138100309,447370331932931548,447367497959943895,447368440776047529,447369383860059146,447370961138101965,447369701551505646,447367188670594337,447370961138098573,447369071816886909,447370016479126134,447370961138098574,447367188669792291,447369383860055806,447370647651623513,447369383859454088,447369071816685064,447367812499374356,447371275412177048,447371275412177050,447371275412377580,447371275412580310,447371275414193217,447371275414193232,447371275414193233,447371275414193235,447371275414193236,447371275414193237,447371275414193238,447371275414998678,447371275414998680,447371275414998682,447371275414998684,447371275414998685,447371275414998686,447371275414998687,447371275415203863,447371275415203864,447371275415203866,447371275415403925,447371275415403926,447371275415403928,447371275415604301,447371275415604303,447371275415604304,447371275415604418,447371275415604419]"]
[milvus-log-instance1.tar.gz](https://github.com/milvus-io/milvus/files/14093169/milvus-log-instance1.tar.gz)

[2024/01/30 05:01:34.128 +00:00] [ERROR] [datacoord/session_manager.go:179] ["flush call (perhaps partially) failed"] ["dataNode ID"=304] [error="failed to get flush channel has this segment: segment not found[segment=447370961137897595]"] [stack="github.com/milvus-io/milvus/internal/datacoord.(*SessionManagerImpl).execFlush\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/session_manager.go:179"]

**Comment by xiaofan-luan** [comment]
/assign @bigsheeper 
could you take a look on this?

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version: 2.3.5
> - Deployment mode(standalone or cluster): cluster
> - MQ type(rocksmq, pulsar or kafka): kafka (MSK)
> - SDK version(e.g. pymilvus v2.0.0rc2): java
> - OS(Ubuntu or CentOS): Ubuntu
> - CPU/Memory: 
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> I have a client that is calling the bulk insert API and trying to insert data into milvus. Initially the bulk insert API was working as expected but we had to restart all the milvus components i.e workers and coordinators multiple times.
> 
> After these restarts the rate of ingestion via bulk insert drastically reduced. from 2million vectors per minute -> 30k per minute
> 
> Also i can see segment missing error logs in active data-coordinator
> 
> ### Expected Behavior
> Even with restarts for milvus components there should be a recovery mechanism that guarantees optimal rate of ingestion via Bulk Insert API .
> 
> ### Steps To Reproduce
> ```
> 1. Repeatedly call bulk insert API
> 2. Repeatedly restart all components every 15 mins
> ```
> 
> ### Milvus Log
> [2024/01/30 05:01:34.127 +00:00] [INFO] [datacoord/services.go:1421] ["start flushing segments"] [traceID=2660b8a836542b07cf1e61559d567412] ["segment IDs"="[447370961137897595,447367497959742841,447369701551505648,447369071816683303,447370016479327759,447366573366520767,447366869925575747,447370331932528251,447369071816281797,447369071816886726,447367497959342182,447368124667145430,447368124667145429,447370016479329458,447370016478724688,447367497959943561,447368124666740885,447370331932929380,447367188670597514,447367497959947724,447367188669993637,447369383860055582,447368124666941624,447368124667145511,447370016479327770,447368757275081951,447369383859854760,447370961138100279,447370016479327560,447367497959542560,447368440776044049,447369071816683379,447370331933133551,447369701551911488,447367812499575251,447370961137697178,447368757275080599,447369701551706340,447368440776044295,447368440776044293,447368440776045916,447369071816482228,447370961137697292,447367497960148226,447370647651826679,447366573366520781,447368440775642728,447367188670194015,447370961138098692,447367188670594335,447366869925574407,447370647651623430,447367497959947642,447370331932929713,447368757274878443,447370647651422536,447369383859654090,447367188670597513,447370647651825077,447368124666740926,447367188670594336,447368440776047527,447368757274880233,447366869924970773,447366869925575748,447370331932933079,447368440775843258,447366573366520779,447367812499976048,447366573366720890,447367812499976127,447368757274476982,447369383860055873,447369701551911483,447367812500379585,447368757274677600,447366869925170844,447368757274878556,447367812499976317,447370647651221556,447370016478724619,447368757275081700,447370647651826642,447369071816885332,447366869925572198,447366869925572274,447368440775642730,447366869925371175,447367812500379586,447368124667145431,447368757274878096,447370331932929790,447368757274878519,447370016479125931,447370647651623080,447369701552311626,447370016478925201,447370647651825079,447369383860057514,447370331932528249,447369383860059148,447368440776044280,447369383860055804,447367812499374427,447367188670595812,447368440776045917,447367812500379587,447367188669792290,447369071816682886,447370647651623429,447369383860057616,447370961138101967,447367497959947644,447370331932929982,447367188670595811,447370331932931547,447369071816281760,447366869925574182,447367497959947643,447370331932728610,447366869925572276,447367812500379583,447368757274476981,447370647651221554,447370961138100309,447370331932931548,447367497959943895,447368440776047529,447369383860059146,447370961138101965,447369701551505646,447367188670594337,447370961138098573,447369071816886909,447370016479126134,447370961138098574,447367188669792291,447369383860055806,447370647651623513,447369383859454088,447369071816685064,447367812499374356,447371275412177048,447371275412177050,447371275412377580,447371275412580310,447371275414193217,447371275414193232,447371275414193233,447371275414193235,447371275414193236,447371275414193237,447371275414193238,447371275414998678,447371275414998680,447371275414998682,447371275414998684,447371275414998685,447371275414998686,447371275414998687,447371275415203863,447371275415203864,447371275415203866,447371275415403925,447371275415403926,447371275415403928,447371275415604301,447371275415604303,447371275415604304,447371275415604418,447371275415604419]"] [milvus-log-instance1.tar.gz](https://github.com/milvus-io/milvus/files/14093169/milvus-log-instance1.tar.gz)
> 
> [2024/01/30 05:01:34.128 +00:00] [ERROR] [datacoord/session_manager.go:179] ["flush call (perhaps partially) failed"] ["dataNode ID"=304] [error="failed to get flush channel has this segment: segment not found[segment=447370961137897595]"] [stack="github.com/milvus-io/milvus/internal/datacoord.(*SessionManagerImpl).execFlush\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/session_manager.go:179"]
> 
> ### Anything else?
> _No response_

Did you have many partitions in your current collections? Looks like the flush takes long time

**Comment by roy-akash** [comment]
I just have 1 collection in this milvus cluster and it has 2 partitions. Please find below response for show partition call
`INFO: ShowPartitionsParam{collectionName='dpc_test_collection', partitionNames='[]', showType=All}
status {
}
partition_names: "_default"
partition_names: "random"
partitionIDs: 447360916570617391
partitionIDs: 447360916570618023
created_timestamps: 447362819480616964
created_timestamps: 447362852379688964
created_utc_timestamps: 1706553724215
created_utc_timestamps: 1706553849715`

**Comment by xiaofan-luan** [comment]
did you try to reboot the datanode?

**Comment by roy-akash** [comment]
we rebooted everything and that led to this. 
Do you mean to fix this i should try to reboot datanode ?

**Comment by xiaofan-luan** [comment]
yes, reboot the datanode.
Currently what happens is that datacoord has 1 more segments than datanode, which is 447370961137897595.
From current guess, this might be generated by bulkinsert , but from the log we don't have too much clue.

One possible way to fix that is using birdwatcher to remove  447370961137897595. https://github.com/milvus-io/birdwatcher
Once you remove it and restart the cluster should be fixed.

**Comment by roy-akash** [comment]
Sure i will try to do it, but in the long term i think bulk insert should be resilient to such failures.

In our use case we have to restart milvus instance once every week so if bulk insert is running at the time we would again run into this issue and it would require us to fix this manually.

Also i suspect the manual fix would lead to some data loss.

**Comment by roy-akash** [comment]
I have attached logs for coordinators and datanode at the time this issue started occuring
[logs_at_issue_start.tar.gz](https://github.com/milvus-io/milvus/files/14094018/logs_at_issue_start.tar.gz)

**Comment by bigsheeper** [comment]
Hello @roy-akash ,I am curious as to why you need to restart all components every 15 minutes.

**Comment by roy-akash** [comment]
On average, we want to insert ~120 million vectors per hour, this is required when we are loading a lot of data in a new milvus cluster.

In our real use case we would restart milvus components once every week as we intend to do AMI patching for EKS nodes on which all these milvus components would be running on.

During this patching process all the components would restart. For now we are doing this every 15 minutes as a test to identify any issues.

**Comment by xiaofan-luan** [comment]
Upon our analysis, restart the cluster will break the bulkinsert task.

And our guess is that 447370961137897595 is left by a failed bulkinsert task

**Comment by roy-akash** [comment]
I think its fine even if a bulkinsert task fails due to restarts, clients can track the task status and retry the task if required. 
This failure although should not slow down the rate of bulk ingestion.

**Comment by xiaofan-luan** [comment]
This garbage will be clean up after 15 minutes.
And during that time no flush can be succeeded 

The easy fix should just ignore segment under importing state, but TBH the current test seems not to be very reasonable.

It is very hard to expect the service can be recovered under such high frequent reboot

**Comment by xiaofan-luan** [comment]
did you still have the log of the cluster? What might happen when datacoord reboot?
If you keep this environment, we can have a quick fix  image see if it can solve the problem

**Comment by roy-akash** [comment]
That'll be great, yeah i have this environment still and i can keep it running for us to test the quick fix image. 

Didn't understand the first point. Do you want me to restart datacoord and share the logs before and after the restart event ?

**Comment by bigsheeper** [comment]
@roy-akash Very well, I'll make a quick fix and offer you the fix image soon.

**Comment by roy-akash** [comment]
@bigsheeper is there an update ? should i keep the environment running ?

**Comment by bigsheeper** [comment]
> @bigsheeper is there an update ? should i keep the environment running ?

I apologize, @roy-akash. The update will be provided in the coming days. You can simply halt the environment without cleaning the data and metadata.

**Comment by roy-akash** [comment]
@bigsheeper  no worries. I see your PR is merged does that mean build is available now ?

**Comment by bigsheeper** [comment]
> @bigsheeper no worries. I see your PR is merged does that mean build is available now ?

Yes @roy-akash, if you urgently need it, I can immediately provide you with a dev image. If it's not urgent, we plan to release version 2.3.8 today or tomorrow.

**Comment by roy-akash** [comment]
@bigsheeper i'd like to test it as soon as possible as this is kind of blocking issue for us. 

I found this milvusdb/milvus:2.3-20240203-3c5ff624-amd64 image in docker hub .. i guess this is created from milvus master branch and since your change is in master this image should have it correct ?

**Comment by bigsheeper** [comment]
> @bigsheeper i'd like to test it as soon as possible as this is kind of blocking issue for us.
> 
> I found this milvusdb/milvus:2.3-20240203-3c5ff624-amd64 image in docker hub .. i guess this is created from milvus master branch and since your change is in master this image should have it correct ?

This image is created from the 2.3 branch, and yes, you can test with this image.

**Comment by yanliang567** [comment]
@roy-akash any updates for the new image test?

**Comment by roy-akash** [comment]
Yeah, bulk inserts are working fine now. Thanks !

**Comment by yanliang567** [comment]
@roy-akash thank you for your updates.
I'd close the issue as comments above.
