### ISSUE TITLE
[Bug]: ListAlias dosen't return collection_name

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus#30369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master
```

### Current Behavior

```
{
      aliases: [ 'alias_0hu6ijcc' ],
      status: {
        error_code: 'Success',
        reason: '',
        code: 0,
        retriable: false,
        detail: ''
      },
      db_name: '',
      collection_name: ''
    }
```

### Expected Behavior

The collection name shouldn't be empty.

**Comment by czs007** [comment]
this is by design.
The function "describe_alias" can fulfill this requirement.

**Comment by shanghaikid** [comment]
verified.
