### ISSUE TITLE
[Bug]: DescribeAlias & ListAliases don't work if we set up database globally through GRPC interceptor. 

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus#30368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.x or master
```

### Current Behavior

DescribeAlias & ListAliases don't work if we set up database globally through the GRPC interceptor. 

### Steps To Reproduce

```markdown
1. create a database
2. use that database
3. create a collection
4. create the alias
5. desribe or list alias.
```

**Comment by xiaofan-luan** [comment]
/assign @SimFG 
could you take a look into it

**Comment by SimFG** [comment]
@xiaofan-luan ok, i will checkout it

**Comment by SimFG** [comment]
@xiaofan-luan I have found the reason, which is the database interceptor isn't work for these apis.
same as: https://github.com/milvus-io/milvus/issues/30392
i will fix it tomorrow.

**Comment by yanliang567** [comment]
@SimFG was this fixed

**Comment by SimFG** [comment]
@yanliang567 has fixed. and ruiyi has checked
