### ISSUE TITLE
[Enhancement]: Add build option to determine whether to compile OpenDAL

### ISSUE THREAD

**Issue by czs007** [milvus-io/milvus#30373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Currently, Milvus does not actively promote the use of OpenDAL to interface with various object storages. To accelerate the compilation speed in most scenarios, I suggest adding the option "BUILD_OPENDAL" to determine whether to compile OpenDAL.

When `BUILD_OPENDAL=ON`, OpenDAL compilation will be enabled.
When `BUILD_OPENDAL=OFF`, OpenDAL compilation will be disabled.

**Comment by zhagnlu** [comment]
defaut value is on or off?
