### ISSUE TITLE
[Bug]: DescribeIndex doesn't return mmap info

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus#30393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
```

### Current Behavior

```
  console.log
    alter {
      error_code: 'Success',
      reason: '',
      code: 0,
      retriable: false,
      detail: ''
    }

      at test/grpc/Index.spec.ts:370:13

  console.log
    describe [
      { key: 'index_type', value: 'IVF_FLAT' },
      { key: 'metric_type', value: 'L2' },
      { key: 'params', value: '{"nlist":1024}' }
    ]
```

**Comment by yanliang567** [comment]
any upates @yah01

**Comment by yanliang567** [comment]
/assign @elstic 
please help to confirm whether it is a mivus issue

**Comment by elstic** [comment]
@shanghaikid please provide the sdk and version used, as well as the milvus image.

**Comment by elstic** [comment]
![image](https://github.com/milvus-io/milvus/assets/48523564/e99783b7-a744-4fe8-bff0-ea4ec45b6393)
@shanghaikid  You can get mmap information by looking at the index params

**Comment by shanghaikid** [comment]
fixed in the latest version.
