### ISSUE TITLE
[Bug]: [hybrid_search] Insert multiple vector fields failed with error message "The Input data type is inconsistent with defined schema" when enable dynamic field 

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#30394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20240129-74cfba02
- Deployment mode(standalone or cluster):both
- MQ type(rocksmq, pulsar or kafka):   all 
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0rc26
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

 Insert multiple vector fields failed with error message "The Input data type is inconsistent with defined schema"when enable dynamic field 

```
pymilvus.exceptions.DataNotMatchException: <DataNotMatchException: (code=1, message=The Input data type is inconsistent with defined schema, please check it.)>
```

### Expected Behavior

Insert successfully

### Steps To Reproduce

```python
from pymilvus import CollectionSchema, FieldSchema
from pymilvus import Collection
from pymilvus import connections
from pymilvus import DataType
from pymilvus import Partition
from pymilvus import utility
import numpy as np
import json

dim = 128
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
schema = CollectionSchema(fields=[int64_field, float_vector], enable_dynamic_field=True)
connections.connect()
collection = Collection("test_search_collection_dynamic_1", schema=schema)
nb=1000
import random
rng = np.random.default_rng(seed=19530)

rows = [{"int64": i, "float_vector": rng.random((1, dim))[0], "float_vector0": rng.random((1, dim))[0]} for  i in range(0, nb)]
res = collection.insert(rows)
```

**Comment by binbinlv** [comment]
Fail:
rows = [{"int64": i, "float_vector": rng.random((1, dim))[0], "float_vector0": rng.random((1, dim))[0]} for  i in range(0, nb)]

Success:
 [{"int64": i, "float_vector": [random.random() for _ in range(dim)], "float_vector0": [random.random() for _ in range(dim)]} for  i in range(0, nb)]

**Comment by xiaocai2333** [comment]
If you want to create multiple vector fields, you need to explicitly specify each vector field in your schema.. Such as:
```
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
float_vector0 = FieldSchema(name="float_vector0", dtype=DataType.FLOAT_VECTOR, dim=dim)
schema = CollectionSchema(fields=[int64_field, float_vector, float_vector0], enable_dynamic_field=True)
```

**Comment by xiaocai2333** [comment]
In your case, you are actually inserting a dynamic field called `float_vector0`. The reason why the insertion fails is that you are writing to numpy.ndarray, json.dump cannot directly take effect on it. It needs to be converted into a list first. I will fix it in pymilvus.

**Comment by binbinlv** [comment]
> If you want to create multiple vector fields, you need to explicitly specify each vector field in your schema.. Such as:
> 
> ```
> int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
> float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
> float_vector0 = FieldSchema(name="float_vector0", dtype=DataType.FLOAT_VECTOR, dim=dim)
> schema = CollectionSchema(fields=[int64_field, float_vector, float_vector0], enable_dynamic_field=True)
> ```

OK, got it, thanks.

**Comment by binbinlv** [comment]
Verified and fixed:
pymilvus: 2.4.0rc28
milvus: master-20240203-20c9cfc5

results:
```
>>> rows = [{"int64": i, "float_vector": rng.random((1, dim))[0], "float_vector0": rng.random((1, dim))[0]} for  i in range(0, nb)]
>>>
>>> res = collection.insert(rows)
>>> res
(insert count: 1000, delete count: 0, upsert count: 0, timestamp: 447484045642432516, success count: 1000, err count: 0)
```
