### ISSUE TITLE
[Bug]: failed to search: collection not loaded

### ISSUE THREAD

**Issue by weiyi88** [milvus-io/milvus#30403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
mac m1 
milvus docker-composer

attu
```

### Current Behavior

![WX20240131-144755@2x](https://github.com/milvus-io/milvus/assets/32037147/22fc2ce6-6f35-4d78-8797-8570b4e3e1c0)

**Comment by shanghaikid** [comment]
you should load your collection first.

**Comment by yanliang567** [comment]
@weiyi88 as it said, you shall load the collection first.
/assign @weiyi88 
/unassign
