### ISSUE TITLE
[Enhancement]:  Optimize memory usage of deserialize delta log.

### ISSUE THREAD

**Issue by aoiasd** [milvus-io/milvus#30404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Delta log deserialize has a large overheads at memory peak.
Optimize memory usage of deserialize delta log.

### Why is this needed?

relate: https://github.com/milvus-io/milvus/issues/30110

**Comment by congqixia** [comment]
still WIP

**Comment by xiaofan-luan** [comment]
keep this issue
