### ISSUE TITLE
[Bug]: querycoord throws querynode[nodeID: 1276] is unhealthy, reason: inner error: context deadline exceeded

### ISSUE THREAD

**Issue by TonyAnn** [milvus-io/milvus#30418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.11
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 400core / 7T
- GPU: 
- Others:
```

### Current Behavior

Two days ago, the minio storage was full, causing some server nodes in the cluster to be evicted；
After that, the problem of full storage was solved by adding minio service pool. 

After that, the querynode memory was full, causing the cluster to be unavailable. By expanding the querynode, reload the index; during this process, the load data could not be queried normally. Rootcoord was throwing a pulsar topic and there was accumulation, which was later manually cleaned up. pulsar is used to make the cluster available.

However, there are still some problems in the current cluster, such as querycoord throwing
querynode[nodeID: 1276] is unhealthy, reason: inner error: context deadline exceeded
rootcoord throws [2024/01/31 08:17:17.874 +00:00] [WARN] [rootcoord/timeticksync.go:305] ["rootcoord send tt to all channels too slowly"] [chanNum=16] [span= 205]

Please help me find out how to troubleshoot the problem

### Milvus Log

[milvus_log.zip](https://github.com/milvus-io/milvus/files/14111192/milvus_log.zip)

**Comment by yanliang567** [comment]
@TonyAnn any chance you could upgrade to milvus 2.3.7, as 2.2.11 is quite an old release. Also did you try to restart the milvus cluster?
/assign @TonyAnn

**Comment by TonyAnn** [comment]
@yanliang567 hi yanliang，I have tried setting querycoord and querynode replica to 0 before, but the problem still exists. 

For upgrading, there are several issues that need to be confirmed.
1. Can version 2.2.11 be directly upgraded to 2.3.7?
2. What are the possible risks of upgrading?
3. Is there any upgrade reference document for the cluster deployed by helm?

**Comment by yanliang567** [comment]
1. yes, you can do that. I'd suggest you backup the data before upgrading
2. milvus might stop service for a few seconds or mins depending on how much data you are running
3. https://milvus.io/docs/upgrade_milvus_standalone-helm.md
