### ISSUE TITLE
[Bug]: timestampFrom and timestampTo is not stored

### ISSUE THREAD

**Issue by smellthemoon** [milvus-io/milvus#30451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

timestampTo and timestampFrom is needed when ttl.
<img width="691" alt="1" src="https://github.com/milvus-io/milvus/assets/64083300/a7920bf4-757e-4f82-b1e9-5db0cfe94788">

**Comment by xiaofan-luan** [comment]
good catch～

**Comment by xiaofan-luan** [comment]
is there anywhere using this?

**Comment by smellthemoon** [comment]
> is there anywhere using this?

if user set ttl, the timestampFrom and timestampTo will still be 0, which may make ttl failed.

**Comment by xiaofan-luan** [comment]
@smellthemoon 
please cherrypick  this to 2.3 if necessary
