### ISSUE TITLE
The server keep waiting when the server cannot connect MySQL during flushing

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#3046]
**Please state you issue using the following template and, most importantly, in English.**

**Describe the bug**

1. Flush operation should be return exceptions or status not ok, instead of waiting, when we use network-partition of chaos-mesh to make Milvus server cannot connect MySQL during flushing
2. This is the server's log:
```
[2020-07-28 14:23:01,183][INFO][SERVER][Flush][grpcpp_sync_ser] Request [10489] Flush begin.
[2020-07-28 14:23:01,184][INFO][WAL][Flush][reqsched_thread] test_lAb8Lopk want to be flush, lsn 146041503298
...
```

**Steps/Code to reproduce behavior**
1. create Milvus and set `try_connect=False`  using Python SDK
2. set disable_auto_flush
3. insert 800,000 vectors and dim = 128
4. create network-partition
5. flush manually

**Expected behavior**
rarise exception or status not ok, with msg: "can not connect mysql"

**Environment details**
0.10.1

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
In Milvus, almost all the operations are depend on meta system, it could not work if remote meta server(MySQL) is not available.

**Comment by BossZou** [comment]
May be we need set connection timeout for mysql:
'''
        auto conn = new mysqlpp::Connection();
        conn->set_option(new mysqlpp::ReconnectOption(true));
        conn->set_option(new mysqlpp::ConnectTimeoutOption(5));
'''

**Comment by shengjun1985** [comment]
In this case, Milvus can no longer work.
Please think about whether it is more reasonable to exit?
