### ISSUE TITLE
[Bug]: Milvus will automatically exit, sometimes even unable to restart

### ISSUE THREAD

**Issue by LuJH12** [milvus-io/milvus#30488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: V2.2.16
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 8G and 16G
- GPU: 
- Others:
```

### Current Behavior

When I use the Milvus function normally, it will occasionally automatically disconnect. After checking, I found that the container milvus standalone automatically exits with an exit code of 0.

I have two virtual machines, one with 8GB of memory and the other with 16GB of memory. They have both been experiencing this issue recently
![exit(0),16g](https://github.com/milvus-io/milvus/assets/78155731/254087f7-4bf4-4f3e-8ddc-ef8446576889)
![exit(0),8g](https://github.com/milvus-io/milvus/assets/78155731/6ddca569-62e8-4e2f-ad21-d96f40e828d4)

### Expected Behavior

I want to know how to prevent this from happening

### Steps To Reproduce

```markdown
I didn't use Milvus, it automatically hung up after a while, which had never happened a few months ago
```

### Milvus Log

[milvus.log](https://github.com/milvus-io/milvus/files/14155124/milvus.log)

**Comment by yanliang567** [comment]
@LuJH12 it seems that the milvus pod fails to connect to the etcd service and exit. Could you please double check the etcd service, and if possible upload the etcd and minio logs for investigation.  
/assign @LuJH12 
`[32mmilvus-standalone |[0m [2024/02/01 22:35:04.188 +00:00] [ERROR] [rootcoord/root_coord.go:304] ["Root Coord disconnected from etcd, process will exit"] ["Server Id"=3] [stack="github.com/milvus-io/milvus/internal/rootcoord.(*Core).Register.func1\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:304"]
`

**Comment by LuJH12** [comment]
> @LuJH12 it seems that the milvus pod fails to connect to the etcd service and exit. Could you please double check the etcd service, and if possible upload the etcd and minio logs for investigation. /assign @LuJH12 `�[32mmilvus-standalone |�[0m [2024/02/01 22:35:04.188 +00:00] [ERROR] [rootcoord/root_coord.go:304] ["Root Coord disconnected from etcd, process will exit"] ["Server Id"=3] [stack="github.com/milvus-io/milvus/internal/rootcoord.(*Core).Register.func1\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:304"] `

This is the logs for etcd and minio. Thank you for coming and helping to check them

[etcd.log](https://github.com/milvus-io/milvus/files/14155337/etcd.log)

[minio.log](https://github.com/milvus-io/milvus/files/14155338/minio.log)

**Comment by yanliang567** [comment]
/assign @LoveEachDay 
PTAL

/unassign
