### ISSUE TITLE
[Bug]: Loading collection stuck at 0% after server's sudden electricity lost

### ISSUE THREAD

**Issue by ThinkThinkSyn** [milvus-io/milvus#30501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.4
- Deployment mode(standalone or cluster): standalone(GPU)
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): Attu 2.3.6
- OS(Ubuntu or CentOS): Ubuntu 22.04.3 LTS
- CPU/Memory: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz 64GB
- GPU: RTX 1060 6G
```

### Current Behavior

After server restart from a sudden electricity lost, Milvus cannot load collection into memory. I have tried to load it for over 12 hours but it just keep stucking.

I am doing the load action in attu, it is observed to have 2 possible apperances(randomly):
1. stuck at 0% forever
2. error with msg `Error: 4 DEADLINE_EXCEEDED` and the loading process stop automatically.

I have search for similar issue and I found https://github.com/milvus-io/milvus/issues/29484 facing to the same problem. What makes different is seems his stucking is resulted by the `milvus-backup`, while I have not installed that ever. 

### Milvus Log

I have tried to figure out problems in log, but I could only find trash log jumping out like: `[2024/02/04 08:24:38.336 +00:00] [INFO] [msgstream/mq_msgstream.go:918] ["skip msg"] [msg="base:<msg_type:TimeTick timestamp:447290085443633154 sourceID:6 > "]`

I have tried `grep "[ERROR]" <my docker container log file>` but the latest error is happened in Jan 26 (while the electricity lost is happened on 2/2), which means that there has no helpful error msg.

**Comment by weiliu1031** [comment]
@ThinkThinkSyn please export the log for investigating, [export log script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log)

**Comment by ThinkThinkSyn** [comment]
[milvus.zip](https://github.com/milvus-io/milvus/files/14156859/milvus.zip)
Sorry for late reply. This is my docker log.
Please be noticed that since the log is to large, this is just a part of log from Feb1 till it die

**Comment by ThinkThinkSyn** [comment]
> @ThinkThinkSyn please export the log for investigating, [export log script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log)

[milvus.zip](https://github.com/milvus-io/milvus/files/14156866/milvus.zip)
Sorry for late reply. This is the docker log.
Please be noticed that since the log is to large, this is just a part of log from Feb1 till it die

**Comment by weiliu1031** [comment]
> > @ThinkThinkSyn please export the log for investigating, [export log script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log)
> 
> [milvus.zip](https://github.com/milvus-io/milvus/files/14156866/milvus.zip) Sorry for late reply. This is the docker log. Please be noticed that since the log is to large, this is just a part of log from Feb1 till it die

after the milvus server restart, it will try to reload the collections. and i want to know why the loading progress stucks, so i need the logs since the milvus service restart

**Comment by ThinkThinkSyn** [comment]
> > > @ThinkThinkSyn please export the log for investigating, [export log script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log)
> > 
> > 
> > [milvus.zip](https://github.com/milvus-io/milvus/files/14156866/milvus.zip) Sorry for late reply. This is the docker log. Please be noticed that since the log is to large, this is just a part of log from Feb1 till it die
> 
> after the milvus server restart, it will try to reload the collections. and i want to know why the loading progress stucks, so i need the logs since the milvus service restart

I have tried reloaded all collection for serveral times, even tried to wait for loading over 10 hrs but still stuck in 0%. 

For logs, I am not sure how to output the latest log. For the above log it is just outputed by simply calling `docker-compose logs > milvus.log`. As mention at the begining, I have looked into the latest rolling log and it is filled by a plantey of useless log "skip msg" like this:
![image](https://github.com/milvus-io/milvus/assets/152035088/965dcad5-167a-475a-823a-946d53fe9be2)

**Comment by ThinkThinkSyn** [comment]
Update: I have output the latest log by calling `--tail=...`. 
Since it is too big(almost fill with useless `"skip msg"` log), I have `grep` out those "ERROR"/"WARN" log. Please have a check.
[error_logs.txt](https://github.com/milvus-io/milvus/files/14162974/error_logs.txt)

**Comment by yanliang567** [comment]
@ThinkThinkSyn i saw milvus fails to find the index for the collection _law_original_content_,  and i did not find any logs about load task. could you please a) try to load the collection b)and then export the logs again.
`[33mmilvus-standalone |[0m [2024/02/05 08:44:02.278 +00:00] [WARN] [proxy/task_scheduler.go:458] ["Failed to execute task: "] [traceID=45c066b7f89ff71ae95accff4aff2ddc] [error="index not found[collection=law_original_content]"]
`
/assign @ThinkThinkSyn

**Comment by yanliang567** [comment]
@ThinkThinkSyn also Could you please attach the etcd backup for investigation？ Check this: https://github.com/milvus-io/birdwatcher for details about how to backup etcd with birdwatcher

**Comment by ThinkThinkSyn** [comment]
> @ThinkThinkSyn i saw milvus fails to find the index for the collection _law_original_content_, and i did not find any logs about load task. could you please a) try to load the collection b)and then export the logs again. �`[33mmilvus-standalone |�[0m [2024/02/05 08:44:02.278 +00:00] [WARN] [proxy/task_scheduler.go:458] ["Failed to execute task: "] [traceID=45c066b7f89ff71ae95accff4aff2ddc] [error="index not found[collection=law_original_content]"] ` /assign @ThinkThinkSyn

Yes, that collection `law_original_content`'s index was deleted yesterday cuz I wanna test whether Milvus will be runnable again after the recreation of index.  Other collections' index are not deleted, but it is still unavailable to load. The below shows an example:

![image](https://github.com/milvus-io/milvus/assets/152035088/2d53017e-3b3e-4c1a-9026-5c3737dfd259)

with the latest log of this stuck: 
[latest-50000-erros.log](https://github.com/milvus-io/milvus/files/14166023/latest-50000-erros.log)

**Comment by ThinkThinkSyn** [comment]
update: the collection `law_full_content_summarized_embedding` above have just successful loaded for once with unknown reason.  

But after I release it, it stuck with 0% in loading again.

**Comment by xiaofan-luan** [comment]
1. did you check your message queue state?using kafkacli or pulsarctl to check if all the kafka is working.
2. Did you tried to restart the cluster

**Comment by ThinkThinkSyn** [comment]
> 1. did you check your message queue state?using kafkacli or pulsarctl to check if all the kafka is working.您檢查訊息佇列狀態了嗎？使用 kafkacli 或 pulsarctl 檢查所有 kafka 是否正常運作。
> 2. Did you tried to restart the cluster您是否嘗試過重啟集群

For 2, we have just restart the container and now it loads successfully, but new error came out with `failed to search/query delegator 11 for channel by-dev-rootcoord-dml_4_447474321364366830v0: fail to Search, QueryNode ID=11, reason=Timestamp lag too large` when viewing the data. 

For 1, I am sorry for not familiar with the tools you mention. I will check it later.

**Comment by yanliang567** [comment]
@ThinkThinkSyn  there are only 2 mins  logs in the new attached files, and the only msg i can see about 447474321364366830 is a warn as below.  I agree that you shall check the MQ service first, and if possible attach the MQ logs, and more logs would be great help.
`[33mmilvus-standalone |[0m [2024/02/05 13:02:37.678 +00:00] [WARN] [task/executor.go:397] ["failed to subscribe channel"] [taskID=1706979178640] [collectionID=447059354952351200] [replicaID=447474321491492875] [channel=by-dev-rootcoord-dml_11_447059354952351200v0] [node=9] [source=channel_checker] [error="the other same channel is unsubscribing: channel reduplicates[channel=by-dev-rootcoord-dml_11_447059354952351200v0]"]`

**Comment by ThinkThinkSyn** [comment]
> @ThinkThinkSyn there are only 2 mins logs in the new attached files, and the only msg i can see about 447474321364366830 is a warn as below. I agree that you shall check the MQ service first, and if possible attach the MQ logs, and more logs would be great help. 新附加文件中只有 2 分鐘的日誌，我能看到的關於 447474321364366830 的唯一訊息是如下警告。我同意你應該先檢查MQ服務，如果可能的話附上MQ日誌，更多的日誌會很有幫助。 `�[33mmilvus-standalone |�[0m [2024/02/05 13:02:37.678 +00:00] [WARN] [task/executor.go:397] ["failed to subscribe channel"] [taskID=1706979178640] [collectionID=447059354952351200] [replicaID=447474321491492875] [channel=by-dev-rootcoord-dml_11_447059354952351200v0] [node=9] [source=channel_checker] [error="the other same channel is unsubscribing: channel reduplicates[channel=by-dev-rootcoord-dml_11_447059354952351200v0]"]`

Sorry for late reply. May I have some document refs on how to check the message queue u have mentioned? Seems I can't find some useful information for it.

**Comment by weiliu1031** [comment]
> > @ThinkThinkSyn there are only 2 mins logs in the new attached files, and the only msg i can see about 447474321364366830 is a warn as below. I agree that you shall check the MQ service first, and if possible attach the MQ logs, and more logs would be great help. 新附加文件中只有 2 分鐘的日誌，我能看到的關於 447474321364366830 的唯一訊息是如下警告。我同意你應該先檢查MQ服務，如果可能的話附上MQ日誌，更多的日誌會很有幫助。 `�[33mmilvus-standalone |�[0m [2024/02/05 13:02:37.678 +00:00] [WARN] [task/executor.go:397] ["failed to subscribe channel"] [taskID=1706979178640] [collectionID=447059354952351200] [replicaID=447474321491492875] [channel=by-dev-rootcoord-dml_11_447059354952351200v0] [node=9] [source=channel_checker] [error="the other same channel is unsubscribing: channel reduplicates[channel=by-dev-rootcoord-dml_11_447059354952351200v0]"]`
> 
> Sorry for late reply. May I have some document refs on how to check the message queue u have mentioned? Seems I can't find some useful information for it.

base on the logs above, seems that you deploy a milvus standalone instance, which uses internal rocksmq, for now, it's status maintained by milvus itself

**Comment by yanliang567** [comment]
@weiliu1031 any ideas of how to get more helpful info?

**Comment by weiliu1031** [comment]
> +1. My python workers exceeded RAM on the machine and Milvus-stanalone has been crashed. After restarting loading collection stuck at 0% for a long time and no progress appears. Logs (I've dropped "skip msg" rows) - [milvus.log](https://github.com/milvus-io/milvus/files/14361438/milvus.log)

this logs helps a lot! we found that after the milvus instance restart, reloading collection stuck at consuming data from rocksmq when subscribing channel.

guess that after a sudden reboot of the physical machine, RocksDB may have left a file lock, blocking subsequent operations to read data from RocksDB. i will do some tests to figure it out

**Comment by xiaofan-luan** [comment]
> Hello! Is there any progress on this?

1. did you have enough memory for now?
2. we need detailed log to judge if this is same issue. If it's the same issue, remove the file lock on rdb directory could solve the issue

**Comment by xiaofan-luan** [comment]
@smellthemoon think of how we can remove the lock automaticlly when service start? It shouldn't be very hard to do

**Comment by xiaofan-luan** [comment]
the easy fix is to clean the RDB directory next time you hit this.
We will fix that soon

**Comment by AI-Candy-Yang** [comment]
> the easy fix is to clean the RDB directory next time you hit this. We will fix that soon

What about the previous data

**Comment by AI-Candy-Yang** [comment]
> > > Hello! Is there any progress on this?
> > 
> > 
> > 
> > 1. did you have enough memory for now?
> > 2. we need detailed log to judge if this is same issue. If it's the same issue, remove the file lock on rdb directory could solve the issue
> 
>     1. Yes, I did. But I wouldn't want to get this problem again
> 
>     2. I can't provide a new journal right now because this problem rarely occurs, I have only previous one

May I ask if the problem of the collection load being stuck has been resolved

**Comment by xiaofan-luan** [comment]
> > > > Hello! Is there any progress on this?
> > > 
> > > 
> > > 
> > > 1. did you have enough memory for now?
> > > 2. we need detailed log to judge if this is same issue. If it's the same issue, remove the file lock on rdb directory could solve the issue
> > 
> > 
> > ```
> > 1. Yes, I did. But I wouldn't want to get this problem again
> > 
> > 2. I can't provide a new journal right now because this problem rarely occurs, I have only previous one
> > ```
> 
> May I ask if the problem of the collection load being stuck has been resolved

I'm not sure if you hitting into the same issue since there is no logs offered and "Loading stuck at 0%" might be triggered by different reasons.

But if you hit the same issue, remove the lock file of rocksdb could ideally solve the problem.

**Comment by junjie-landing** [comment]
> But if you hit the same issue, remove the lock file of rocksdb could ideally solve the problem.

Where do I remove the lock file when running standalone version in k8s?

**Comment by zrg-team** [comment]
@xiaofan-luan Where do I remove the lock file when running standalone version ?

**Comment by xiaofan-luan** [comment]
the rocksmq dir. usually it's under /var/lib. check your milvus.yaml file config

**Comment by pavluka6** [comment]
I also have this issue, and it happened on system restart. How can avoid this happening in the future, and how to resolve this?

**Comment by xiaofan-luan** [comment]
/assign @yanliang567 
please help on reproducing this issue

**Comment by xiaofan-luan** [comment]
this is important and we saw this happened multiple times

**Comment by m-ajer** [comment]
Is there any news on this? I had to restart my server due to a power outage, Milvus from docker is having trouble starting (status unhealthy), I do not want to reindex the whole collection again

**Comment by yanliang567** [comment]
we can not reproduce this issue in house. @m-ajer I suggest you manually stop the milvus service before the power outage.

**Comment by xiaofan-luan** [comment]
> Is there any news on this? I had to restart my server due to a power outage, Milvus from docker is having trouble starting (status unhealthy), I do not want to reindex the whole collection again

Could you offer a log and your milvus version if your service can not start?
Upgrade to milvus latest might be able to help

**Comment by xiaofan-luan** [comment]
we'd like to further track if there are more clues.

**Comment by m-ajer** [comment]
I retried it again with the same result - milvus-standalone remains unhealthy despite increasing the wait time for other instances to load in the docker configuration. Here are the logs and the docker-compose: [files.zip](https://github.com/user-attachments/files/18300634/files.zip). Another factor that could be the case or error is that we are not using an SSD, but the collection indexed normally before, so we didn't think it would be an issue. The current volume size is around 110 GB.

**Comment by yanliang567** [comment]
@m-ajer the logs you attached is all about INFO logs, which does not have enough info. Could you please set the milvus log level to DEBUG, and recollect the log?

**Comment by xiaofan-luan** [comment]
change this queryCoord.channelTaskTimeout config to 600000 and see if it works.

We recommend you to upgrade 2.4-latest and this pr might solve the problem https://github.com/milvus-io/milvus/pull/36617

**Comment by m-ajer** [comment]
thank you! where do I change the parameter? also, is it possible to incorporate this PR using a docker image? this is the way I start the milvus services

**Comment by m-ajer** [comment]
bump

**Comment by xiaofan-luan** [comment]
The error collection not found[collection=447632070540965294]

1. 2.3.1 is too old, please try 2.4.21 on this test and see if the result reproduced.
2. make sure your /etcd directory is on disk(And should be SSD), simply glance the log.
3. if it still can be reproduced, can you offer a minimal process to reproduce this issue?

Thanks
@m-ajer

**Comment by eskinmi** [comment]
Have the exact same [issue](https://github.com/milvus-io/milvus/issues/39562), in my case it happened when we were moving the deployment to TF, some pods had to be redeployed and now the collection load is stuck.

**Comment by xiaofan-luan** [comment]
[2025/02/11 12:15:19.453 +00:00] [WARN] [segments/segment_loader.go:878] ["no sufficient resource to load segments"] [traceID=1d3a4482cb20caf5344c618566d5fa91] [segmentIDs="[454581286461785401]"] [error="load segment failed, OOM if load, maxSegmentSize = 1446.868426322937 MB,  memUsage = 27445.33984375 MB, predictMemUsage = 28892.208270072937 MB, totalMem = 31919.05078125 MB thresholdFactor = 0.900000"]


@m-ajer 
it seems that you might end up with out of memory if you load it. 

how many data do you have?  I would suggest to upgrade to 2.4.21 and scale to larger machines if possible

**Comment by m-ajer** [comment]
I upgraded to 2.4.21 already, as suggested before. The machine has 32 GB RAM, we scaled down from a larger machine to this one. Not sure about the size of the data, since we can't load the collection, but it is around 110 GB of Milvus data in total.
Could the issue be multiple commands for loading Milvus? Or is RAM the bottleneck?

**Comment by xiaofan-luan** [comment]
if you have 32GB memory but your data size is far more than that,
then you will need either:
1. use index like IVFSQ8, use quantization to reduce memory usage
2. use mmap
3. use index like diskann if your machine has local nvme ssd

**Comment by m-ajer** [comment]
I used the sizing tool you provide to estimate the required hardware and just want to do a sanity check whether I understand the values properly. 
1. Does 'Loading memory' specify the maximum RAM that will be occupied when I load and use the database? We are looking into upgrading the system and want to opt for 64 GB. The sizing tool determined I would need 50 GB for my data.
2. What is the difference between 'Memory' and 'Storage'? The data will occupy around 210 GB of memory, that I understand, but I don't understand the Storage requirement of 2.64 TB. Does this just specify what the SSD capacity should be ideally?

Actually, the best you could do is explain everything in the attached sizing tool. Sorry this is unrelated for the issue, thank you for your help!

![Image](https://github.com/user-attachments/assets/23a58074-b428-4640-95cb-f6631e54d3fc)

**Comment by yanliang567** [comment]
Loading memory means the memory usage for query nodes if loading the collection. And the Storage 2.64TB in the attached screenshot is the storage size for etcd, pular and minio storage. Please use SSD volumes for etcd and pulsar bookie, and the others can use sata volumes.  @m-ajer
