### ISSUE TITLE
[Bug]: Entity Loaded Num is removed from source code, but still displayed in Garafana dashboard

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#30527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.3.x
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The "Entity Loaded Num" always shows "No data" for Milvus v2.3.x

![Screenshot from 2024-02-05 11-53-35](https://github.com/milvus-io/milvus/assets/2282099/f7940da1-e25b-4b6a-8fda-b5d402666789)

### Expected Behavior

Remove this metric from dashboard

**Comment by yanliang567** [comment]
@LoveEachDay any updates

**Comment by yanliang567** [comment]
any updates @LoveEachDay
