### ISSUE TITLE
[Bug]: GetCollectionInfo can not specify both name and id

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#30524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

<img width="1044" alt="image" src="https://github.com/milvus-io/milvus/assets/83447078/7b0d40e9-5cd3-42b1-b4b1-a617d3fdc978">

There is no way that a caller know both id and name

**Comment by yanliang567** [comment]
keep it

**Comment by chyezh** [comment]
keep it
