### ISSUE TITLE
[Bug]: querynode panic again and again after mq shutdown

### ISSUE THREAD

**Issue by weiliu1031** [milvus-io/milvus#30544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master and 2.3
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

after mq shutdown, if querynode try to load segment, then it will fail to create consumer and panic.
![image](https://github.com/milvus-io/milvus/assets/108661493/d9d080d5-c220-43db-b277-56aa595f2e11)

### Expected Behavior

after mq shutdown, load segment could fail, but query node shouldn't panic.  search/query is unavailable due to lack of segment before `partitial search` is ready

**Comment by yanliang567** [comment]
@weiliu1031 any updates?

**Comment by weiliu1031** [comment]
> @weiliu1031 any updates?

known issue,  we will reduce the dependency on S3 and MQ in the future
