### ISSUE TITLE
[Bug]: requery of search lack records when compaction trigger 

### ISSUE THREAD

**Issue by zhagnlu** [milvus-io/milvus#30576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

requery which is second phase of search,  although now we add mvcc timestamp for it, but if compaction triggers between search and requery process,  requery can not see these records that should be visible with mvcc timestamp
![20240207-145325](https://github.com/milvus-io/milvus/assets/11935707/7110bdf8-3fc9-44d6-a65e-3bca66dfa2a8)

### Expected Behavior

requery see correct records, compact should consider query/search timestamp snapshot

**Comment by xiaofan-luan** [comment]
emmm..
What could be a fix for that?

maybe we should just return error and let SDK retry?

**Comment by xiaofan-luan** [comment]
I don't think of a good way to do so. We can reserve some recent deletes  but there seems to be no guarantee.

It is hard to hold original segments  in main memory because the proxy might crash or timeout

**Comment by xiaofan-luan** [comment]
after discussion, we could just retry
