### ISSUE TITLE
[Enhancement]:  Support rate limiter based on db level and partition level 

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#30577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

The rate limiter function only supports cluster level and collection level currently, extending the function to set limiter parameters based on db or partition level.

**Comment by xiaofan-luan** [comment]
> @jaime0815 I would love to work on this issue. If possible can you provide me some more information? such as which files you think would help me to read and so on.

Hi @arashmpr 
May I know more details? Are you trying to use this somewhere?
I'd like to help you to finish the feature

**Comment by arashmpr** [comment]
> > @jaime0815 I would love to work on this issue. If possible can you provide me some more information? such as which files you think would help me to read and so on.
> 
> Hi @arashmpr May I know more details? Are you trying to use this somewhere? I'd like to help you to finish the feature

No I wanted to fix the issue but I was asking for help to see if you or @jaime0815 can provide me some more information about the issue and where (as in which files are related to this issue) I can start working on this issue.

**Comment by jaime0815** [comment]
> > > @jaime0815 I would love to work on this issue. If possible can you provide me some more information? such as which files you think would help me to read and so on.
> > 
> > 
> > Hi @arashmpr May I know more details? Are you trying to use this somewhere? I'd like to help you to finish the feature
> 
> No I wanted to fix the issue but I was asking for help to see if you or @jaime0815 can provide me some more information about the issue and where (as in which files are related to this issue) I can start working on this issue.

Hi @arashmpr , I am working on this issue [PR](https://github.com/milvus-io/milvus/pull/30579/files), but still have a lot of work that needs to be done,  we can finish it together if possible.  the rate limiter mechanism depends on Rootcoord component as a quota center([quota_center.go](https://github.com/milvus-io/milvus/blob/master/internal/rootcoord/quota_center.go)) to collect metrics and send them to Proxy component, the GRPC interceptor will capture some requests [rate_limit_interceptor.go](https://github.com/milvus-io/milvus/blob/master/internal/proxy/rate_limit_interceptor.go) and [check](https://github.com/milvus-io/milvus/blob/master/internal/proxy/multi_rate_limiter.go#L72) them with locally rate values on the proxy side.

**Comment by jaime0815** [comment]
I am reconstructing the rate limiter code to support more dimensions,  It is difficult if we try to add rate limiters of db and partition levels into the previous implementations directly.

**Comment by arashmpr** [comment]
> I am reconstructing the rate limiter code to support more dimensions, It is difficult if we try to add rate limiters of db and partition levels into the previous implementations directly.

Meanwhile do you think it's okay for me to look at the current approach and the files that you mentioned so I can get more familiar? If there is anything for me to do, I'd like to help while you are doing this

**Comment by jaime0815** [comment]
> > I am reconstructing the rate limiter code to support more dimensions, It is difficult if we try to add rate limiters of db and partition levels into the previous implementations directly.
> 
> Meanwhile do you think it's okay for me to look at the current approach and the files that you mentioned so I can get more familiar? If there is anything for me to do, I'd like to help while you are doing this

Hi, @arashmpr, reconstructing the rate limiter code is almost done,  i am trying to add more uts.  you can try to add a disk usage limiter of the db level and partition level to my PR if you are interested in it,  you can see https://github.com/milvus-io/milvus/blob/12acaf3e4f188d38144ee5573f5ed36b65af3e63/internal/rootcoord/quota_center.go#L763  about checking disk quota.

**Comment by arashmpr** [comment]
> > > I am reconstructing the rate limiter code to support more dimensions, It is difficult if we try to add rate limiters of db and partition levels into the previous implementations directly.
> > 
> > 
> > Meanwhile do you think it's okay for me to look at the current approach and the files that you mentioned so I can get more familiar? If there is anything for me to do, I'd like to help while you are doing this
> 
> Hi, @arashmpr, reconstructing the rate limiter code is almost done, i am trying to add more uts. you can try to add a disk usage limiter of the db level and partition level to my PR if you are interested in it, you can see
> 
> https://github.com/milvus-io/milvus/blob/12acaf3e4f188d38144ee5573f5ed36b65af3e63/internal/rootcoord/quota_center.go#L763
> 
> about checking disk quota.

Hi, @jaime0815. That's great news. Yes that would be awesome I'll start doing that. :) Thank you
