### ISSUE TITLE
[Bug]: when reload collection,can not load success,and the log print invalid json key max_length

### ISSUE THREAD

**Issue by XiaoweiKhan** [milvus-io/milvus#30596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.3
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

E20240211 01:35:15.265908   182 config.cc:65] [KNOWHERE][FormatAndCheck][milvus] invalid json key max_length
I20240211 01:35:15.234535   182 MinioChunkManager.cpp:324] [SEGCORE][MinioChunkManager][milvus] init MinioChunkManager with parameter[endpoint: 'minio:9000', default_bucket_name:'a-bucket', root_path:'files', use_secure:'false']
I20240211 01:35:15.234571   182 factory.cc:20] [KNOWHERE][Create][milvus] create knowhere index IVF_FLAT with version 1
 => failed to build index, invalid param in json
E20240211 01:35:16.235594  3291 config.cc:65] [KNOWHERE][FormatAndCheck][milvus] invalid json key max_length
I20240211 01:35:16.212652  3291 MinioChunkManager.cpp:324] [SEGCORE][MinioChunkManager][milvus] init MinioChunkManager with parameter[endpoint: 'minio:9000', default_bucket_name:'a-bucket', root_path:'files', use_secure:'false']
I20240211 01:35:16.212688  3291 factory.cc:20] [KNOWHERE][Create][milvus] create knowhere index IVF_FLAT with version 1
 => failed to build index, invalid param in json
<img width="978" alt="image" src="https://github.com/milvus-io/milvus/assets/9071035/2ab711ef-f5b2-42e2-bee8-845c97705103">

**Comment by xiaofan-luan** [comment]
failed to build index, invalid param in json 
this means your index params has some unrecognized params.

Could you share more details about how you create the cluster, how you import your data?

**Comment by jiauy** [comment]
Now I build a milvus server copy from the fail machine in the same machine, and this problem has gone, maybe just restart the fail server can be ok :)

**Comment by yanliang567** [comment]
thanks for sharing. I'd close this issue as comments above
