### ISSUE TITLE
[Bug]: Pymilvus Langchain Integration AttributeError: 'Milvus' object has no attribute 'from_documents'

### ISSUE THREAD

**Issue by nutmilk10** [milvus-io/milvus#30592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.6
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 10/10
- GPU: None
- Others:
```

### Current Behavior

When I run 
```
from pymilvus import connections, db, Milvus
vector_store = Milvus(
    embedding_function=embeddings,
    connection_args=connection_args,
    collection_name=COLLECTION_NAME,
    drop_old=True,
).from_documents(
    all_splits,
    embedding=embeddings,
    collection_name=COLLECTION_NAME,
    connection_args=connection_args,
)
```

I get the error AttributeError: 'Milvus' object has no attribute 'from_documents'

### Expected Behavior

Per Milvus documentation:

`vector_store = Milvus(
    embedding_function=embeddings,
    connection_args=connection_args,
    collection_name=COLLECTION_NAME,
    drop_old=True,
).from_documents(
    all_splits,
    embedding=embeddings,
    collection_name=COLLECTION_NAME,
    connection_args=connection_args,
)`

**Comment by fzliu** [comment]
The `from_documents` function is specific to the [Langchain integration](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/milvus.py).

You'll want to use `from langchain.vectorstores import Milvus` instead.
