### ISSUE TITLE
[Bug]: Delete collection call failing with error Failed to enqueue delete task: failed to create expr plan

### ISSUE THREAD

**Issue by kdabbir** [milvus-io/milvus#30606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.8
- Deployment mode(standalone or cluster): Cluster deployed on EKS
- MQ type(rocksmq, pulsar or kafka): Kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Delete collection call is failing with error `Failed to enqueue delete task: failed to create expr plan` added the entire stack trace from proxy in milvus log section.
Can we understand why this call is failing and how to fix this error?

### Expected Behavior

Delete collection should be successful

### Milvus Log

`[2024/02/13 16:50:07.798 +00:00] [ERROR] [proxy/impl.go:2361] ["Failed to enqueue delete task: failed to create expr plan, expr = RecordId__c in [c546d205-3d8b-40a9-8b80-27cc0ef8a9d4,d5e4bf5a-62a4-4fb7-b1aa-f1bf41bc8ade,1b6c63fd-2246-44bb-b26a-cb6b48ba697c,f3b31319-96fc-47d4-b2db-631932b1bd78,5b0dc6ef-063e-4370-8aec-e12f599f14c9,98acb628-5488-4449-8b2e-c87d450b7b8d,fbc271c5-ccfd-4f52-aaab-f84e96abdb92,3ad03bee-2399-4b8f-9749-052c6a095db6,4595707f-8356-4f44-b451-b9d50d9c0150,c8eda890-8e51-4354-b965-b1f7449d2d7a]"] [traceID=c0e96a4595e9e197748bf6de1fb6258f] [role=proxy] [db=milvusdefaultv2] [collection=a360_falcondev_9c5486ca5bcf4cdca0adf0277ae7a26b_subh_gcs_udmo_si_e2e_4_vector__dlm] [partition=] [expr="RecordId__c in [c546d205-3d8b-40a9-8b80-27cc0ef8a9d4,d5e4bf5a-62a4-4fb7-b1aa-f1bf41bc8ade,1b6c63fd-2246-44bb-b26a-cb6b48ba697c,f3b31319-96fc-47d4-b2db-631932b1bd78,5b0dc6ef-063e-4370-8aec-e12f599f14c9,98acb628-5488-4449-8b2e-c87d450b7b8d,fbc271c5-ccfd-4f52-aaab-f84e96abdb92,3ad03bee-2399-4b8f-9749-052c6a095db6,4595707f-8356-4f44-b451-b9d50d9c0150,c8eda890-8e51-4354-b965-b1f7449d2d7a]"] [stack="github.com/milvus-io/milvus/internal/proxy.(*Proxy).Delete\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/impl.go:2361\ngithub.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Delete\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:874\ngithub.com/milvus-io/milvus-proto/go-api/v2/milvuspb._MilvusService_Delete_Handler.func1\n\t/go/pkg/mod/github.com/milvus-io/milvus-proto/go-api/v2@v2.3.8/milvuspb/milvus.pb.go:12291\ngithub.com/milvus-io/milvus/internal/proxy/connection.KeepActiveInterc
[data-coord-milvusdefaultv2.csv](https://github.com/milvus-io/milvus/files/14272093/data-coord-milvusdefaultv2.csv)
eptor\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/connection/util.go:60\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/milvus-io/milvus/internal/proxy/accesslog.UnaryUpdateAccessInfoInterceptor\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/accesslog/util.go:47\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/milvus-io/milvus/internal/proxy.RateLimitInterceptor.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/rate_limit_interceptor.go:55\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/milvus-io/milvus/pkg/util/logutil.UnaryTraceLoggerInterceptor\n\t/go/src/github.com/milvus-io/milvus/pkg/util/logutil/grpc_interceptor.go:23\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/milvus-io/milvus/internal/proxy.UnaryServerInterceptor.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/privilege_interceptor.go:82\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/milvus-io/milvus/internal/proxy.UnaryServerHookInterceptor.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/hook_interceptor.go:118\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/milvus-io/milvus/internal/proxy.DatabaseInterceptor.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/database_interceptor.go:15\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/grpc-ecosystem/go-grpc-middleware/auth.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/auth/auth.go:47\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngo.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1\n\t/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.38.0/interceptor.go:342\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/milvus-io/milvus/internal/proxy/accesslog.UnaryAccessLogInterceptor\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/accesslog/util.go:38\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34\ngithub.com/milvus-io/milvus-proto/go-api/v2/milvuspb._MilvusService_Delete_Handler\n\t/go/pkg/mod/github.com/milvus-io/milvus-proto/go-api/v2@v2.3.8/milvuspb/milvus.pb.go:12293\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:1345\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:1722\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:966"]`

[logs_part1.zip](https://github.com/milvus-io/milvus/files/14272140/logs_part1.zip)

**Comment by kdabbir** [comment]
[logs_part2.zip](https://github.com/milvus-io/milvus/files/14272147/logs_part2.zip)
Adding data coord and data worker node logs here.
Rest of the logs are uploaded in the post as logs_part1.zip, all milvus logs are exported via splunk and uploaded

**Comment by kdabbir** [comment]
@yanliang567 @xiaofan-luan please look into this issue, this is blocking our feature testing

**Comment by PowderLi** [comment]
first, please check the dataType of field `RecordId__c`, if VARCHAR, the expr should be like
```
expr="RecordId__c in [\"c546d205-3d8b-40a9-8b80-27cc0ef8a9d4\",\"d5e4bf5a-62a4-4fb7-b1aa-f1bf41bc8ade\",\"1b6c63fd-2246-44bb-b26a-cb6b48ba697c\",\"f3b31319-96fc-47d4-b2db-631932b1bd78\"]"
// quotations are needed
```
second, please told us the sdk you used, make it clear how it generate the expression?

**Comment by kdabbir** [comment]
we used java SDK. i'll check logic generation part

**Comment by kdabbir** [comment]
thanks for your help @PowderLi , for now we can treat this issue as closed, there was an issue with our expression. we changed the way we call milvus api and it worked. Though we have few follow-up questions which we want to discuss further
