### ISSUE TITLE
[Bug]: invalid index type: ANNOY

### ISSUE THREAD

**Issue by azhagammal96** [milvus-io/milvus#30608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: latest
- Deployment mode(standalone or cluster): standalone   
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.6
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: Yes
```

### Current Behavior

I am trying to create an index for my embeddings using index_type ANNOY. However I get the error message "invalid index type: ANNOY"

`RPC error: [create_index], <MilvusException: (code=65535, message=invalid index type: ANNOY)>, <Time:{'RPC start': '2024-02-14 17:28:49.261796', 'RPC error': '2024-02-14 17:28:49.267255'}>
---------------------------------------------------------------------------
MilvusException                           Traceback (most recent call last)
    [... skipping hidden 1 frame]

Cell In[11], line 6
      1 index_params = {
      2   "metric_type":"L2",
      3   "index_type":"ANNOY",
      4   "n_trees":256
      5 }
----> 6 collection.create_index(
      7   field_name="embeddings", 
      8   index_params=index_params,
      9   index_name="vec_index"
     10 )

File ~/.local/lib/python3.10/site-packages/pymilvus/orm/collection.py:1218, in Collection.create_index(self, field_name, index_params, timeout, **kwargs)
   1217 conn = self._get_connection()
-> 1218 return conn.create_index(self._name, field_name, index_params, timeout=timeout, **kwargs)

File ~/.local/lib/python3.10/site-packages/pymilvus/decorators.py:135, in error_handler.<locals>.wrapper.<locals>.handler(*args, **kwargs)
    134     LOGGER.error(f"RPC error: [{inner_name}], {e}, <Time:{record_dict}>")
--> 135     raise e from e
    136 except grpc.FutureTimeoutError as e:

File ~/.local/lib/python3.10/site-packages/pymilvus/decorators.py:131, in error_handler.<locals>.wrapper.<locals>.handler(*args, **kwargs)
    130     record_dict["RPC start"] = str(datetime.datetime.now())
--> 131     return func(*args, **kwargs)
    132 except MilvusException as e:

File ~/.local/lib/python3.10/site-packages/pymilvus/decorators.py:170, in tracing_request.<locals>.wrapper.<locals>.handler(self, *args, **kwargs)
    169     self.set_onetime_request_id(req_id)
--> 170 return func(self, *args, **kwargs)

File ~/.local/lib/python3.10/site-packages/pymilvus/decorators.py:110, in retry_on_rpc_failure.<locals>.wrapper.<locals>.handler(*args, **kwargs)
    109     else:
--> 110         raise e from e
    111 except Exception as e:

File ~/.local/lib/python3.10/site-packages/pymilvus/decorators.py:74, in retry_on_rpc_failure.<locals>.wrapper.<locals>.handler(*args, **kwargs)
     73 try:
---> 74     return func(*args, **kwargs)
     75 except grpc.RpcError as e:
     76     # Reference: https://grpc.github.io/grpc/python/grpc.html#grpc-status-code

File ~/.local/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py:858, in GrpcHandler.create_index(self, collection_name, field_name, params, timeout, **kwargs)
    857 status = future.result()
--> 858 check_status(status)
    860 if kwargs.get("sync", True):

File ~/.local/lib/python3.10/site-packages/pymilvus/client/utils.py:54, in check_status(status)
     53 if status.code != 0 or status.error_code != 0:
---> 54     raise MilvusException(status.code, status.reason, status.error_code)

MilvusException: <MilvusException: (code=65535, message=invalid index type: ANNOY)>

The above exception was the direct cause of the following exception:

MilvusException                           Traceback (most recent call last)
    [... skipping hidden 1 frame]

Cell In[11], line 6
      1 index_params = {
      2   "metric_type":"L2",
      3   "index_type":"ANNOY",
      4   "n_trees":256
      5 }
----> 6 collection.create_index(
      7   field_name="embeddings", 
      8   index_params=index_params,
      9   index_name="vec_index"
     10 )

File ~/.local/lib/python3.10/site-packages/pymilvus/orm/collection.py:1218, in Collection.create_index(self, field_name, index_params, timeout, **kwargs)
   1217 conn = self._get_connection()
-> 1218 return conn.create_index(self._name, field_name, index_params, timeout=timeout, **kwargs)

File ~/.local/lib/python3.10/site-packages/pymilvus/decorators.py:135, in error_handler.<locals>.wrapper.<locals>.handler(*args, **kwargs)
    134     LOGGER.error(f"RPC error: [{inner_name}], {e}, <Time:{record_dict}>")
--> 135     raise e from e
    136 except grpc.FutureTimeoutError as e:

File ~/.local/lib/python3.10/site-packages/pymilvus/decorators.py:131, in error_handler.<locals>.wrapper.<locals>.handler(*args, **kwargs)
    130     record_dict["RPC start"] = str(datetime.datetime.now())
--> 131     return func(*args, **kwargs)
    132 except MilvusException as e:

File ~/.local/lib/python3.10/site-packages/pymilvus/decorators.py:170, in tracing_request.<locals>.wrapper.<locals>.handler(self, *args, **kwargs)
    169     self.set_onetime_request_id(req_id)
--> 170 return func(self, *args, **kwargs)

File ~/.local/lib/python3.10/site-packages/pymilvus/decorators.py:110, in retry_on_rpc_failure.<locals>.wrapper.<locals>.handler(*args, **kwargs)
    109     else:
--> 110         raise e from e
    111 except Exception as e:

File ~/.local/lib/python3.10/site-packages/pymilvus/decorators.py:74, in retry_on_rpc_failure.<locals>.wrapper.<locals>.handler(*args, **kwargs)
     73 try:
---> 74     return func(*args, **kwargs)
     75 except grpc.RpcError as e:
     76     # Reference: https://grpc.github.io/grpc/python/grpc.html#grpc-status-code

File ~/.local/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py:858, in GrpcHandler.create_index(self, collection_name, field_name, params, timeout, **kwargs)
    857 status = future.result()
--> 858 check_status(status)
    860 if kwargs.get("sync", True):

File ~/.local/lib/python3.10/site-packages/pymilvus/client/utils.py:54, in check_status(status)
     53 if status.code != 0 or status.error_code != 0:
---> 54     raise MilvusException(status.code, status.reason, status.error_code)

MilvusException: <MilvusException: (code=65535, message=invalid index type: ANNOY)>

The above exception was the direct cause of the following exception:

MilvusException                           Traceback (most recent call last)
Cell In[11], line 6
      1 index_params = {
      2   "metric_type":"L2",
      3   "index_type":"ANNOY",
      4   "n_trees":256
      5 }
----> 6 collection.create_index(
      7   field_name="embeddings", 
      8   index_params=index_params,
      9   index_name="vec_index"
     10 )

File ~/.local/lib/python3.10/site-packages/pymilvus/orm/collection.py:1218, in Collection.create_index(self, field_name, index_params, timeout, **kwargs)
   1180 """Creates index for a specified field, with a index name.
   1181 
   1182 Args:
   (...)
   1215     Status(code=0, message='')
   1216 """
   1217 conn = self._get_connection()
-> 1218 return conn.create_index(self._name, field_name, index_params, timeout=timeout, **kwargs)

File ~/.local/lib/python3.10/site-packages/pymilvus/decorators.py:135, in error_handler.<locals>.wrapper.<locals>.handler(*args, **kwargs)
    133     record_dict["RPC error"] = str(datetime.datetime.now())
    134     LOGGER.error(f"RPC error: [{inner_name}], {e}, <Time:{record_dict}>")
--> 135     raise e from e
    136 except grpc.FutureTimeoutError as e:
    137     record_dict["gRPC timeout"] = str(datetime.datetime.now())

File ~/.local/lib/python3.10/site-packages/pymilvus/decorators.py:131, in error_handler.<locals>.wrapper.<locals>.handler(*args, **kwargs)
    129 try:
    130     record_dict["RPC start"] = str(datetime.datetime.now())
--> 131     return func(*args, **kwargs)
    132 except MilvusException as e:
    133     record_dict["RPC error"] = str(datetime.datetime.now())

File ~/.local/lib/python3.10/site-packages/pymilvus/decorators.py:170, in tracing_request.<locals>.wrapper.<locals>.handler(self, *args, **kwargs)
    168 if req_id:
    169     self.set_onetime_request_id(req_id)
--> 170 return func(self, *args, **kwargs)

File ~/.local/lib/python3.10/site-packages/pymilvus/decorators.py:110, in retry_on_rpc_failure.<locals>.wrapper.<locals>.handler(*args, **kwargs)
    108         back_off = min(back_off * back_off_multiplier, max_back_off)
    109     else:
--> 110         raise e from e
    111 except Exception as e:
    112     raise e from e

File ~/.local/lib/python3.10/site-packages/pymilvus/decorators.py:74, in retry_on_rpc_failure.<locals>.wrapper.<locals>.handler(*args, **kwargs)
     72 while True:
     73     try:
---> 74         return func(*args, **kwargs)
     75     except grpc.RpcError as e:
     76         # Reference: https://grpc.github.io/grpc/python/grpc.html#grpc-status-code
     77         if e.code() in (
     78             grpc.StatusCode.DEADLINE_EXCEEDED,
     79             grpc.StatusCode.PERMISSION_DENIED,
   (...)
     83             grpc.StatusCode.RESOURCE_EXHAUSTED,
     84         ):

File ~/.local/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py:858, in GrpcHandler.create_index(self, collection_name, field_name, params, timeout, **kwargs)
    855     return index_future
    857 status = future.result()
--> 858 check_status(status)
    860 if kwargs.get("sync", True):
    861     index_success, fail_reason = self.wait_for_creating_index(
    862         collection_name=collection_name,
    863         index_name=index_name,
    864         timeout=timeout,
    865         field_name=field_name,
    866     )

File ~/.local/lib/python3.10/site-packages/pymilvus/client/utils.py:54, in check_status(status)
     52 def check_status(status: Status):
     53     if status.code != 0 or status.error_code != 0:
---> 54         raise MilvusException(status.code, status.reason, status.error_code)

MilvusException: <MilvusException: (code=65535, message=invalid index type: ANNOY)>`

**Comment by xiaofan-luan** [comment]
hi @azhagammal96,
We are not supporting Annoy anymore due to it lacks bot efficiency and accuracy.
Please try HSNW or any index type in Faiss

**Comment by azhagammal96** [comment]
hey @xiaofan-luan , thank you.
It's still a valid index_type in the [documentation](https://milvus.io/docs/v2.0.x/build_index.md), so I would suggest removing it to avoid further confusion.

**Comment by baptvit** [comment]
Hey everyone, 

> hey @xiaofan-luan , thank you. It's still a valid index_type in the [documentation](https://milvus.io/docs/v2.0.x/build_index.md), so I would suggest removing it to avoid further confusion.

Hey every one, Im also face the same problem with the RHNSW_FLAT, RHNSW_PQ and RHNSW_SQ. So, would be nice to remove them if there arent any support on those indexs.

**Comment by yanliang567** [comment]
please  try to read the latest(2.4.x) docs: https://milvus.io/docs/index.md

**Comment by baptvit** [comment]
> those index are removed since rare people are using it. but let us know if there are some special reason you want to use it

@xiaofan-luan I was trying to do a benchmark using different indexs for my particular use case. Other then that, I was curius to see why there are some references in the docs and actually I coundt implement them.

Thanks @yanliang567 I migth have only seen the olds docs.
