### ISSUE TITLE
[Bug]: element_type for array field is missing from collection schema when collection is reinitialised from database

### ISSUE THREAD

**Issue by HongShihan** [milvus-io/milvus#30616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.5
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.3.6
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I reinitialize a collection from the database (through collection = Collection(name)), the element_type for array fields becomes missing, this also causes data insertion to the collection to fail with error UnSupported element type: None for Array field.

### Expected Behavior

element_type for array fields should persist 

### Steps To Reproduce

```markdown
import random
from pymilvus import (
    connections,
    FieldSchema, CollectionSchema, DataType,
    Collection,
    utility
)

# Create a Milvus connection
def create_connection(_HOST, _PORT):
    print(f"\nCreate connection...")
    connections.connect("default", host=_HOST, port=_PORT)
    print(f"\nList connections:")
    print(connections.list_connections())
    
def has_collection(name):
    return utility.has_collection(name)

# Drop a collection in Milvus
def drop_collection(name):
    collection = Collection(name)
    collection.drop()
    print("\nDrop collection: {}".format(name))


def test():
    _HOST = 'localhost'
    _PORT = 19530
    
    # create a connection
    create_connection(_HOST, _PORT)
    
    fieldList = []
    colName = "Dummy"
    if has_collection(colName):
        drop_collection(colName)

    field = FieldSchema(name="ID", dtype=DataType.INT64, description="Auto primary key", is_primary=True, auto_id=True)
    fieldList.append(field)

    field = FieldSchema(name="Bounding_Box", dtype=DataType.ARRAY, element_type=DataType.INT16, max_capacity=4)
    fieldList.append(field)

    field = FieldSchema(name="Embedding", dtype=DataType.FLOAT_VECTOR, dim=512)
    fieldList.append(field)

    schema = CollectionSchema(fields=fieldList, description="Collection for face")
    collection = Collection(name=colName, data=None, schema=schema, properties={"collection.ttl.seconds": 0})
    
    print(collection.schema)

    # If comment this line will have no errors
    collection = Collection("Dummy")
    
    # Schema after reinit will be missing element_type for array field Bounding_Box
    print(collection.schema)
    
    #Data insertion will fail with error UnSupported element type: None for Array field
    toInsert = [[[0,1,2,3]], [[random.random() for _ in range(512)]]]
    collection.insert(toInsert)

if __name__ == '__main__':
    test()
```

**Comment by PowderLi** [comment]
similar to #27322

**Comment by yanliang567** [comment]
please try milvus 2.3.8
/assign @HongShihan 
/unassign

**Comment by HongShihan** [comment]
Appears that 2.3.8 is only available (via pip) for macOS now? Possible to add for Linux as well?

**Comment by xiaofan-luan** [comment]
> Appears that 2.3.8 is only available (via pip) for macOS now? Possible to add for Linux as well?

Don't think there is a difference between linux and macOS?

Any details?

**Comment by HongShihan** [comment]
I cannot pip install milvus==2.3.8, pip cannot find this version for linux, error code as follows:

ERROR: Could not find a version that satisfies the requirement milvus==2.3.8 (from versions: 2.1.0, 2.2.4, 2.2.4.post1, 2.2.5, 2.2.6, 2.2.8, 2.2.9, 2.2.10, 2.2.11, 2.2.12, 2.2.13, 2.2.13.post1, 2.2.13.post2, 2.2.13.post3, 2.2.14, 2.2.15, 2.2.16, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5)
ERROR: No matching distribution found for milvus==2.3.8

**Comment by xiaofan-luan** [comment]
latest pymilvus version of 2.3.x is 2.3.6.
2.3.8 is the server side version

**Comment by xiaofan-luan** [comment]
you will need to upgrade to milvus server side version rathert than upgrade pip install

**Comment by HongShihan** [comment]
I see, sorry for the confusion, it works after I upgraded my docker compose to the 2.3.8 version. Thank you.
