### ISSUE TITLE
[Bug]: Cluster consumes too much storage

### ISSUE THREAD

**Issue by Ibax1** [milvus-io/milvus#30615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.5
- Deployment mode: cluster
- MQ type: kafka 
- SDK version: pymilvus 2.2.5
- OS: AWS EKS
- CPU/Memory: 2 EC2 t3a.xlarge instances (EKS)
- GPU: none
- Others:
```

### Current Behavior

We are running helm cluster on AWS EKS in production and recently noticed that AWS S3 bucket is consuming ridiculous amount of storage (~10TB).

There are 3 collections with 1024 dim float vector with INF_FLAT index. They have ~100,000, ~15,000 and ~30 records currently.

We do quite a bit of hybrid search requests and some insertions. Few record deletes were done only on collection with ~30 records. 

Helm chart: [helm-milvus-values.zip](https://github.com/milvus-io/milvus/files/14305367/helm-milvus-values.zip)

ncdu JSON which shows tree of S3 with storage consumption: [milvus-ncdu.zip](https://github.com/milvus-io/milvus/files/14305462/milvus-ncdu.zip)
Use `ncdu -f milvus-ncdu.json` to look through it.

Graph of S3 size over time:
![image](https://github.com/milvus-io/milvus/assets/16698358/be8e2a4d-5eac-44a7-a514-5d264fbce2e9)
Although cluster is used since April of 2023 and had about same usage whole period, those 10TB were created approximately between mid August and mid September 2023. Growth was ok before and after this period. The business logic working with milvus did not change at this time. Also we did not notice significant change in amount of usage/traffic at this period.

We haven't downloaded logs with recommended script - please tell if it is needed for our case.

We've read https://github.com/milvus-io/milvus/issues/23400, https://github.com/milvus-io/milvus/issues/25815 and https://github.com/milvus-io/milvus/issues/26093. It seems there were some storage bugs prior to 2.2.11-2.2.12. Also in issue discussion it is advised to not do manual flushes - what we do after every insert.

So what is best way to solve problem? I guess we will stop manual flushing. Is there way to get rid of excessive storage on current cluster or should we create new cluster with new version and migrate all vectors?

At the time we haven't seen recommendation to not flush in documentation - is there any list of all recommendations? How stable is current version? If we follow best practices is there guarantee that there will no similar problems in future?

**Comment by yanliang567** [comment]
@Ibax1 thank you for the feedbacks. what did you do special between mid August and mid September 2023?  
1. Could you please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
2. Could you please attach the etcd backup for investigation？ Check this: https://github.com/milvus-io/birdwatcher for details about how to backup etcd with birdwatcher

/assign @Ibax1
