### ISSUE TITLE
llama index guide is incomplete

### ISSUE THREAD

**Issue by 7flash** [milvus-io/milvus#30621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://docs.zilliz.com/docs/documentation-qa-using-zilliz-cloud-and-llamaindex

So I run this script and it works

```
import os

from llama_index.core import download_loader, VectorStoreIndex, ServiceContext
from llama_index.legacy.vector_stores.milvus import MilvusVectorStore
from llama_index.legacy.embeddings import OpenAIEmbedding

from glob import glob

MarkdownReader = download_loader("MarkdownReader")
markdownreader = MarkdownReader()

docs = []
for file in glob("./milvus-docs/site/en/**/*.md", recursive=True):
    docs.extend(markdownreader.load_data(file=file))
print(len(docs))

vector_store = MilvusVectorStore(
    uri=os.getenv('PUBLIC_ENDPOINT'), 
    token=os.getenv('TOKEN'), 
    collection_name=os.getenv('COL'), 
    similarity_metric="L2",
    dim=os.getenv('DIMENSION'),
)

embed_model = OpenAIEmbedding()
service_context = ServiceContext.from_defaults(embed_model=embed_model)

index = VectorStoreIndex.from_documents(
    documents=docs, 
    service_context=service_context,
    show_progress=True
)

query_engine = index.as_query_engine()
response = query_engine.query("What is IVF_FLAT?")
print(str(response))
```

But every time is regenerates embeddings, and vector_store is not being used. How can I use it to actually store embeddings in milvus?

**Comment by yanliang567** [comment]
@fzliu could you please help on this question? or please help to assign someone who can help.

/assign @fzliu 
/unassign

**Comment by codingjaguar** [comment]
Thanks for reporting this. There is a bug in the example code. We are working on fixing it.

**Comment by jaelgu** [comment]
The Zilliz doc is outdated and we will update it soon. Please refer to https://milvus.io/docs/integrate_with_llamaindex.md.
