### ISSUE TITLE
[Bug]: index node panic because AWS S3 SignatureDoesNotMatch

### ISSUE THREAD

**Issue by taptao** [milvus-io/milvus#30631]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.3.3
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: -
- GPU: -
- Others: Milvus opreator version is 0.8.4
```

### Current Behavior

indexnode panics after continuing to print SignatureDoesNotMatch logs. Other nodes will not have similar problems.
```
20240207 16:49:23.978120   127 MinioChunkManager.cpp:85] [SEGCORE][ProcessFormattedStatement][milvus] [AWS LOG] [WARN] 2024-02-07 16:49:23.978 AWSErrorMarshaller [139637781690112] Encountered AWSError 'SignatureDoesNotMatch': The request signature we calculated does not match the signature you provided. Check your key and signing method.
I20240207 16:49:23.978173   127 MinioChunkManager.cpp:85] [SEGCORE][ProcessFormattedStatement][milvus] [AWS LOG] [ERROR] 2024-02-07 16:49:23.978 AWSClient [139637781690112] HTTP response code: 403
Resolved remote host IP address: [52.92.206.56](http://52.92.206.56/)
Request ID: R7GBC1H10VC6JX2H
Exception name: SignatureDoesNotMatch
Error message: The request signature we calculated does not match the signature you provided. Check your key and signing method.
7 response headers:
connection : close
content-type : application/xml
date : Wed, 07 Feb 2024 16:49:23 GMT
server : AmazonS3
transfer-encoding : chunked
x-amz-id-2 : xnAD+PX/YLN2ijMXer4CUyriuEHCYnyO1j10N6R/s9fXn08zh60z80hdENIBQMgdWVFxNPE3WP0=
x-amz-request-id : R7GBC1H10VC6JX2H
```
<img width="1346" alt="image" src="https://github.com/milvus-io/milvus/assets/33219531/de895de0-fe2f-40a3-8daf-8eea8c31e609">

AWS S3 does not have directories named "index_files."
![image](https://github.com/milvus-io/milvus/assets/33219531/e49b74a2-deb5-4432-b5ec-07c0195c4fa8)

I've already checked the S3 AK/SK configuration, it's correct.

### Expected Behavior

indexnode creates index files normally without panic

**Comment by yanliang567** [comment]
/assign @LoveEachDay 
any ideas about the error? it seems to be a config issue

/unassign

**Comment by vpanghal** [comment]
@LoveEachDay we also hitting this issue in our deployment with the 2.3.3 release. I see the s3 bucket contains insert_log and stats_log directories. We see the reported issue in index node logs.   We will be going into production in a few days. Any update would be helpful. Thanks

**Comment by vpanghal** [comment]
@taptao  I am able to resolve this by setting rootPath to an empty string in the external S3 storage config
`-  rootPath: "/"
+  rootPath: ""`
