### ISSUE TITLE
[Bug]: [restful v2]rowCount in `collections/get_stats` is still 0 after 3000 entities has been insert and count(*) already be 3000

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#30663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20240218-91b02b5d
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/12268675/3659c537-16fd-414b-a8d1-9a63fd3d3ad3)

### Expected Behavior

`collections/get_stats` can get real-time row count

**Comment by zhuwenxing** [comment]
> This might be by design right? Unless you do flush manually?

it depends on where data comes from in the `get_stats` API.  It can get row count by num entities or count(*).

if we can use count(*) to get real-time data, why not use it as the data source for `get_stats`

**Comment by xiaofan-luan** [comment]
count(*) need to scan all the data so it might be slower but the result is more instant.

get_stats only fetch meta data.

The reason pymilvus can get right result is probably did a preflush before count

**Comment by yanliang567** [comment]
@PowderLi so what is the design and correct expectation for this api?

**Comment by zhuwenxing** [comment]
@xiaofan-luan 
> Unless you do flush manually?
yes , if i manually do a flush, then the row count is right.

> The reason pymilvus can get right result is probably did a preflush before count
count(*) may not did a prefulsh
my step:
1. insert 3000 entities
2. count(*) get 3000
3. /get_stats get 0

count(*) is before get_stats, so if count(*) did a pre flush, then the row count should be 3000, but the result is still 0. so i guess count(*) should not did a flush.

so i can say that the get_stats is counterpart to num_entities, not the count(*)?

**Comment by xiaofan-luan** [comment]
count won't do any flush, it simply scan all data.

For pymilvus, then do flush before num_entities. but restful api don't do such trick

If you do manual flush before get_stats, you should get 3000 as a result
