### ISSUE TITLE
[Bug]: knowhere coredump when do test in arm cpu

### ISSUE THREAD

**Issue by zhagnlu** [milvus-io/milvus#30683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-18c351efa6e97492929
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

when do cpp test in arm machine, core dump when do test related to knowhere module
![image](https://github.com/milvus-io/milvus/assets/11935707/c08f2b4b-0723-457c-8160-a368a6308ff4)

### Steps To Reproduce

```markdown
cmake_build/bin/all_tests --gtest_filter='*Indexing_With_binary_Predicate_Range*'
```

**Comment by zhagnlu** [comment]
openblas compile problem, milvus using conan openblas as dependent lib,  but if I build openblas by myself and not use conan lib,  this test success.

**Comment by Presburger** [comment]
Please check if there is any openblas related lib(cblas, lapack ... etc) in the system environment.

**Comment by xiaofan-luan** [comment]
is this reproducible?

**Comment by Presburger** [comment]
> is this reproducible?

The problem is that openblas compiled by conan uses the sve instruction, which will crash on the arm platform without sve support.

**Comment by liliu-z** [comment]
#31308 Can solve it
