### ISSUE TITLE
[Bug]: [restful v2]create user failed with unclear error message `decode password fail: illegal base64 data at input byte 4`

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#30730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
method: post, 
url: http://10.104.25.173:19530/v2/vectordb/users/create, 
cost time: 0.028103113174438477, 
header: {'Content-Type': 'application/json', 'Authorization': 'Bearer root:Milvus', 'RequestId': '0753930c-d09f-11ee-bb08-b29c4acc8bb7'}, 
payload: {"userName": "test_user", "password": "123456"}, 
response: {"code":65535,"message":"decode password fail: illegal base64 data at input byte 4"} (milvus.py:17)
```
error message is unclear, I have no idea how to fix this. I guess the actual error may be the length of the password is short? because it is successful when the password is "12345678"

### Anything else?

> The password must be a string of 8 to 64 characters and must include at least three of the following character types: uppercase letters, lowercase letters, numbers, and special characters.

most passwords should follow the above rule, so I think "12345678" should also fail as well. 
well, it is just a suggestion.

**Comment by zhuwenxing** [comment]
the error message contains Unicode
```
5 out of range 6 \u003c= value \u003c= 256
```
can it be translated to `5 out of range 6 <= value <= 256`?

@PowderLi

**Comment by PowderLi** [comment]
please upload the log of milvus
https://github.com/milvus-io/milvus/blob/master/pkg/util/merr/utils.go#L944

**Comment by PowderLi** [comment]
```
>>> import json
>>> res = json.loads('{"code":1100,"message":"invalid password length: invalid parameter[5 out of range 6 \u003c= value \u003c= 256]"}')
>>> res
{'code': 1100, 'message': 'invalid password length: invalid parameter[5 out of range 6 <= value <= 256]'}
```
