### ISSUE TITLE
[Bug]: milvus异常down

### ISSUE THREAD

**Issue by yaojin3616** [milvus-io/milvus#30733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.10
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): No
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.16
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 
- GPU: No
- Others:
```

### Current Behavior

milvus 突然异常退出
![image](https://github.com/milvus-io/milvus/assets/3382757/1ea97a01-88e8-433c-b520-d7248cdced83)
![image](https://github.com/milvus-io/milvus/assets/3382757/937f1cb3-2db9-4e69-a497-746d6a88810e)
![image](https://github.com/milvus-io/milvus/assets/3382757/1427527d-2bd0-495a-b388-5b57990c77ef)

重启过程中，长时间cpu 一致超负荷，日志刷新非常多
![image](https://github.com/milvus-io/milvus/assets/3382757/8fb8c8be-6686-47ea-8635-188dd64cf0c6)
![image](https://github.com/milvus-io/milvus/assets/3382757/42ca657d-7c27-46c5-b7c4-c4260e0ce069)

启动导致etcd 异常
![image](https://github.com/milvus-io/milvus/assets/3382757/e3294003-c626-478a-8d1d-bfbad0c1fc18)
etcd 使用内存到2G

### Expected Behavior

正常稳定运行

### Steps To Reproduce

```markdown
standalone， 运行一段时间后出现
```

### Milvus Log

![image](https://github.com/milvus-io/milvus/assets/3382757/bb5ef6d6-8a9c-4c47-902a-d405e0da8925)

### Anything else?

其他

**Comment by yanliang567** [comment]
please attache the full log files for investigation. For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs. @yaojin3616 
/assign @yaojin3616
