### ISSUE TITLE
[Bug]: load collection failed

### ISSUE THREAD

**Issue by neblen** [milvus-io/milvus#30763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.14
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.14
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Created a collection, kept writing data to 2000w, started loading, load always showed 0, datacoord cpu utilization is very high, there are 25 cores.
The number of querynodes is sufficient, with 34 query nodes. 8c 32g per querynode
The default loadTimeoutSeconds is 1800s and has been increased to 10800s, which is 3 hours. 
![image](https://github.com/milvus-io/milvus/assets/49058548/00484ac4-a038-45f5-a59b-d22fb3141c75)

![image](https://github.com/milvus-io/milvus/assets/49058548/f9020901-7937-47d1-81c9-3e7cf375646d)

### Expected Behavior

load collection success 

### Milvus Log

[milvus-datacoord-56f779c89d-n8ghr-022201.log](https://github.com/milvus-io/milvus/files/14371238/milvus-datacoord-56f779c89d-n8ghr-022201.log)
[milvus-querycoord-57756495b9-w5c9v-022202.log](https://github.com/milvus-io/milvus/files/14371242/milvus-querycoord-57756495b9-w5c9v-022202.log)

**Comment by xiaofan-luan** [comment]
There is seems to be too many segment in your cluster.
1. How did you insert your data?

I guess you did frequent flush or num_entity calls during insertion

2. You did frequent delete + insert and compaction can not catch up.

To fix the issue, you can try to add more datanode and see if compaction could catch up . So far there seems to be too many task in queue

With 20m data there is no way you have more than 10k + segments

**Comment by yanliang567** [comment]
@neblen please try as comments above
/assign @neblen

**Comment by neblen** [comment]
> There is seems to be too many segment in your cluster.
> 
> 1. How did you insert your data?
> 
> I guess you did frequent flush or num_entity calls during insertion
> 
> 2. You did frequent delete + insert and compaction can not catch up.
> 
> To fix the issue, you can try to add more datanode and see if compaction could catch up . So far there seems to be too many task in queue
> 
> With 20m data there is no way you have more than 10k + segments

Thanks Reply. 
Let me explain the situation again
1. It is true that there are too many flushes, and not only 20m of data, but also 80m of data have been inserted into the database. The current phenomenon is that some collections can be loaded, and some collections have failed to load. As long as it can be loaded successfully once, it can be loaded again.
2. Since the load failed, no data has been inserted again.
3.datacoord cpu is not always high, and the load fails when the cpu is low. The phenomenon is that the datacoord CPU will increase a lot when loading collection, but the datanode will not change much. It seems that the datanode has not become a bottleneck.
I would like to know where can I see the number of queues?
![image](https://github.com/milvus-io/milvus/assets/49058548/198f566f-f9d1-4659-b83d-57e8a21c7ddb)

**Comment by neblen** [comment]
[milvus-datacoord-56f779c89d-n8ghr-022204.log](https://github.com/milvus-io/milvus/files/14372316/milvus-datacoord-56f779c89d-n8ghr-022204.log)

**Comment by neblen** [comment]
[milvus-indexcoord-7664b797b4-h76ls-022206.log](https://github.com/milvus-io/milvus/files/14372317/milvus-indexcoord-7664b797b4-h76ls-022206.log)

**Comment by neblen** [comment]
[milvus-proxy-599887c646-dfs4q-022203.log](https://github.com/milvus-io/milvus/files/14372345/milvus-proxy-599887c646-dfs4q-022203.log)

**Comment by yanliang567** [comment]
@LoveEachDay could you please give some comments with a few metric scrrenshots to explain the task queue and compaction status?
/assign @LoveEachDay 
/unassign

**Comment by neblen** [comment]
Are there any some possible reasons? Currently some collections still fail to load. The relevant logs are above. @xiaofan-luan  thanks a lot~

**Comment by LoveEachDay** [comment]
@neblen Could you use `birdwatcher` to create a backup? We can analyze the collection segment distribution from there.

**Comment by neblen** [comment]
> @neblen Could you use `birdwatcher` to create a backup? We can analyze the collection segment distribution from there.

[bw_etcd_ALL.240226-140651.bak.gz](https://github.com/milvus-io/milvus/files/14401450/bw_etcd_ALL.240226-140651.bak.gz)
it's here
