### ISSUE TITLE
[FEATURE] Inserted vectors should can be queried instantly

### ISSUE THREAD

**Issue by Joe-zhuo** [milvus-io/milvus#308]
Some scenarios have this requirement。after inserted data will be searching immediately for hot query just inserted?
Whether the performance can be improved，now it takes about a second。

**Comment by JinHai-CN** [comment]
Hi Joe, Would you please describe the requirements in detail? How many data do you have and How often you insert the data? What's the expected performance from your side?

**Comment by Joe-zhuo** [comment]
Hi,
&nbsp; &nbsp;I already discussed with your guys (顾均) in the wechat group,he asked me to commit a issue on github.



------------------

Best Regards
Joe



 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by yhmo** [comment]
Consider to add a SyncTable/FlushTable api to make sure buffer data be persisted so can be search-able.

**Comment by JinHai-CN** [comment]
I suppose Flush in 0.7.0 is same as this feature.

**Comment by JinHai-CN** [comment]
0.7.0 is release. The vectors can be queried after FLUSH is called by user.
