### ISSUE TITLE
[Bug]: Swap usage 

### ISSUE THREAD

**Issue by Elytum** [milvus-io/milvus#30808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.9
- Deployment mode(standalone or cluster): standalone
- OS(Ubuntu or CentOS): Ubuntu 22.04
- CPU/Memory: 5Gb
- GPU: No
```

### Current Behavior

OOM even through there's available swap

### Expected Behavior

When swap is available, milvus-standalone should use it instead of running into OOM

### Steps To Reproduce

```markdown
1. Allocate some swap (512GB)
2. Set mem_limit to a low amount (5GB) and memswap_limit to a higher one (512GB) in docker-compose.
3. Start milvus
4. Create a database and load vectors into it, for more than mem_limit (100GB)
5. Query the database (It works)
6. Unload the database
7. Load the database (It doesn't work)
```

### Anything else?

When the database cannot fit in RAM (Requirements higher than a TB), and the request rate is pretty low, it's often recommended to use swap in order to load the DB.
This does work when creating the database, but as soon as you unload and reload it, the loading process will try to use RAM only.

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version: 2.3.9
> - Deployment mode(standalone or cluster): standalone
> - OS(Ubuntu or CentOS): Ubuntu 22.04
> - CPU/Memory: 5Gb
> - GPU: No
> ```
> 
> ### Current Behavior
> OOM even through there's available swap
> 
> ### Expected Behavior
> When swap is available, milvus-standalone should use it instead of running into OOM
> 
> ### Steps To Reproduce
> ```
> 1. Allocate some swap (512GB)
> 2. Set mem_limit to a low amount (5GB) and memswap_limit to a higher one (512GB) in docker-compose.
> 3. Start milvus
> 4. Create a database and load vectors into it, for more than mem_limit (100GB)
> 5. Query the database (It works)
> 6. Unload the database
> 7. Load the database (It doesn't work)
> ```
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> When the database cannot fit in RAM (Requirements higher than a TB), and the request rate is pretty low, it's often recommended to use swap in order to load the DB. This does work when creating the database, but as soon as you unload and reload it, the loading process will try to use RAM only.

1. How do you allocate swap? not all of milvus data can be put into swap as far as I know. I'm assuming you already use mmap.
2. We still want to do some memory limitation even if use mmap features because not all the data can be mapped.

**Comment by xiaofan-luan** [comment]
"This does work when creating the database, but as soon as you unload and reload it, the loading process will try to use RAM only."

This is not as expected. What error did you get? 
This could possibly because some memory calculation issue.

**Comment by xiaofan-luan** [comment]
load takes many internal memory, like copy data, and those data can not be mapped to disk. 

From your use case, you have 5 GB memory and there is no way to load 100GB index into memroy.

**Comment by Elytum** [comment]
**_From your use case, you have 5 GB memory and there is no way to load 100GB index into memroy._**

I technically have more, this was a test.
What's weird is that as long as I didn't unload anything it did indeed work, Milvus used the swap as expected

**Comment by xiaofan-luan** [comment]
can you sepcify a little bit more about what is swap?
did you enable the mmap feature?
or you try to use swap in docker?

**Comment by xiaofan-luan** [comment]
if want to understand how milvus collect memory used, the code you should read is mem_info.go and container_linux.go.

we never tried to run milvus on any swap so sorry we could not give any further help. Our recommendation is to use mmap and map your data to a high perfamnce disk(Definitely not SATA, NVMe SSD is recommend)

**Comment by xiaofan-luan** [comment]
Otherwise, think of use pure memory index, SQ/PQ can help you to save memory. But so far there is no magic to help to host 500GB data into 5GB memory. With mmap enabled our best try is to host 100GB data into 8GB memory

**Comment by Elytum** [comment]
**_"milvus only see 5GB memory, and it will not use any of the swap memory you claimed."_**

I re-ran the test and it indeed does work:

![Screenshot from 2024-02-26 13-30-13](https://github.com/milvus-io/milvus/assets/7513527/27dcfd12-4fb4-4262-8449-f6b1709bef9a)
![Screenshot from 2024-02-26 13-33-36](https://github.com/milvus-io/milvus/assets/7513527/5ea561a5-0856-42f9-b3b2-63c590f6f4fb)
![Screenshot from 2024-02-26 13-38-25](https://github.com/milvus-io/milvus/assets/7513527/5102bf51-9e26-4234-bed8-3fafc16b5951)

It seems that the loaded checks if there's available memory by chunks, but doesn't take into account the fact that you can allocate more memory than you have RAM (It's implicit, Milvus doesn't have to worry about it).
The thing is, on insert, the function checking for RAM isn't called, that's why it works. Out of curiosity, is it possible to disable the OOM check on load ?

**_"You could try to use lsof /var/lib/milvus/mmap see who else is mapping the file."_**

I tried figuring it out and right now I'm stuck, I'll try to look more into it.
Anyway, if mmap only needs 8GB of memory per 100GB, that means 5TB is only 410GB, I'm totally fine with that.
The only reason I limited it to 5GB right now is because I want to make sure it can scale.

**Comment by xiaofan-luan** [comment]
you got it. 
DOCKER_VOLUME_DIRECTORY -> is the root data directory and mmap director should be created by milvus

**Comment by xiaofan-luan** [comment]
BTW, did you get chance to test on performance? 
running everything on swap memory could be super slow.
I would rather only put data on swap

**Comment by elstic** [comment]
> By swap, I just mean a regular swap file used by the system when not enough memory is available. With "mem_limit" and "memswap_limit" enabled in the docker-compose.yaml, the milvus container correctly used swap when I loaded data into the database while indexing in real time, which is why I don't understand why I can't re-load it now just like it initially did.
> 
> I tried enabling mmap with the Docker container (See original answer to yanliang567), but I keep running into `panic: unlinkat /var/lib/milvus/mmap: device or resource busy`. Is there anything special to do to enable it with Docker ?
> 
> Thanks for taking the time !

@Elytum   

 Hi, I'm using docker-compose to deploy v2.3.9 of milvus with mmap enabled. There was no crash , and loaded 3 million 128 dimensional vectors with 2g limit memory set. Here is how I used it for your reference
1. Update docker-compose.yaml to configure the mapping of milvus.yaml and enable mmap in milvus.yaml.
```
services:
  ……
  standalone:
    container_name: milvus-standalone-n
    image: milvusdb/milvus:v2.3.9
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
      - /Users/elstic/Documents/milvus.yaml:/milvus/configs/milvus.yaml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      ……
```
 Configuration path: `services.standalone.volumes`
 If you use this method remember to download milvus.yaml and set its path to the real path on your computer.


2. edit /Users/elstic/Documents/milvus.yaml:
```
 queryNode:
   # This is the configuration for turning on mmap
   mmapDirPath: /var/lib/milvus/mmap 
```
 Added mmapDirPath configuration in milvus.yaml 
   

 
3. start/restart milvus. 

```
docker-compose --compatibility up -d
```

Other info: above is how I set up docker-compose to turn on mmap, but I'm assuming that even with mmap turned on it won't be able to load 100g of data with 5g memory. The current version of mmap can load up to 4 times the maximum amount of data.

**Comment by Elytum** [comment]
@xiaofan-luan 

**_running everything on swap memory could be super slow._**

Honestly, it wasn't. Insert speed and query speed was much faster. Might have been because I was using IVF_SQ8, or because I was at a sweet-spot (250M * 500) and maybe it wouldn't have scaled that well further, or maybe the disk writes would have been exponential and ruined my disk much faster with tons more writes, but performance-only, IVF_SQ8 over swap was much better (Even on a basic 870 qvo).
Kinda wondering if building a cluster with cheap refurbished DDR3 isn't better

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan
> 
> **_running everything on swap memory could be super slow._**
> 
> Honestly, it wasn't. Insert speed and query speed was much faster. Might have been because I was using IVF_SQ8, or because I was at a sweet-spot (250M * 500) and maybe it wouldn't have scaled that well further, or maybe the disk writes would have been exponential and ruined my disk much faster with tons more writes, but performance-only, IVF_SQ8 over swap was much better (Even on a basic 870 qvo). Kinda wondering if building a cluster with cheap refurbished DDR3 isn't better

Good to know!
If you want share your experience with others in the community about how you run milvus on swap that would be amazing.
We'd like to post it on Milvus blog and help more people

**Comment by Elytum** [comment]
@xiaofan-luan 

I really like Milvus so I'm totally for it, main issue is mainly a lack of time but if I find some, absolutely !
Thing is, it doesn't really work because it only works as long as you neither unload the database nor restart milvus, which makes it  quite difficult to really run: You would have to re-insert everything at each start, which takes quite a while.
Having a way to disable `OOM if load`, or add swap into the RAM calculation would probably fix it.
Not sure at scale (Billions / tens of billions of entries) if the swap would still work and wouldn't just exhaust the disk's TBW, but for cases where you need to find a needle in a gigantic haystack, like something similar to google images search but local, as long as the request rate is low enough you could scale incredibly high.

No matter how big your infrastructure is, when you need (tens of) TBs of memory, at some point RAM alone is just not a solution.

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan
> 
> I really like Milvus so I'm totally for it, main issue is mainly a lack of time but if I find some, absolutely ! Thing is, it doesn't really work because it only works as long as you neither unload the database nor restart milvus, which makes it quite difficult to really run: You would have to re-insert everything at each start, which takes quite a while. Having a way to disable `OOM if load`, or add swap into the RAM calculation would probably fix it. Probably as an option, because I see the point of not using the swap and rather refusing to load when you need high request rate. Not sure at scale (Billions / tens of billions of entries) if the swap would still work and wouldn't just exhaust the disk's TBW, but for cases where you need to find a needle in a gigantic haystack, like something similar to google images search but local, as long as the request rate is low enough you could scale incredibly high.
> 
> No matter how big your infrastructure is, when you need (tens of) TBs of memory, at some point RAM alone is just not a realistic solution for a few cases.

you should be able to disable the check by change configs.

queryCoord.overloadedMemoryThresholdPercentage by default the overloadedMemoryThread  is 90%, which means data load can only be no higher than 90% of your memory. 

You could change to 200 to avoid the OOM check.

On our Zilliz cloud, we actually have totally different implementation to reduce huge amount of data.
1. Leverage data mmap to fully utilize high performance NVMe disk
2. Swap in and out between S3 and Milvus under some latency unaware cases to store data in cold storage
