### ISSUE TITLE
[Enhancement]: Upgrade Pulsar to 3.x

### ISSUE THREAD

**Issue by haorenfsa** [milvus-io/milvus#30812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Upgrade Pulsar to 3.x

### Why is this needed?

- Enables Milvus to be run in with Pulsar in OpenShift https://github.com/apache/pulsar/pull/13376
- Fix a stability issue of pulsar https://github.com/apache/pulsar/issues/14779

### Anything else?

ref: 
- https://github.com/zilliztech/milvus-helm/issues/43
- https://github.com/milvus-io/milvus/pull/30775

dependency:
- https://github.com/milvus-io/milvus/pull/36435

**Comment by rere950303** [comment]
@haorenfsa thanks for your works, 
Do you have any plans to increase the pulsar version to 3.0.1? I would like to change the pulsar version used in milvus 2.3.12 to 2.10.0 because of openshift-related issues. I don't think there will be any big issues when referring to the minor version release note. Are there any expected issues? I would appreciate it if you could comment briefly.

**Comment by xiaofan-luan** [comment]
> @haorenfsa thanks for your works, Do you have any plans to increase the pulsar version to 3.0.1? I would like to change the pulsar version used in milvus 2.3.12 to 2.10.0 because of volume directive issues in dockerfile. I don't think there will be any big issues when referring to the minor version release note. Are there any expected issues? I would appreciate it if you could comment briefly.

So which version you are targeting to use? 2.10 or 3.0.1? We would recommend to use 3.0.1 since we test it thoroughly

**Comment by xiaofan-luan** [comment]
keep this. 
@haorenfsa is there a deadline for this?

**Comment by haorenfsa** [comment]
@xiaofan-luan One must first upgrade pulsar to some other 2.x version before one can upgrade to 3.0.1.
@LoveEachDay will write a doc about the upgrading route, before we change the default version to 3.0.1 in helm chart.
/assign @LoveEachDay

**Comment by haorenfsa** [comment]
keep alive

**Comment by haorenfsa** [comment]
milvus-operator now supports pulsar v3 https://github.com/zilliztech/milvus-operator/pull/182#event-14169040762
but only for new milvus instance. Manifest example is in https://github.com/zilliztech/milvus-operator/blob/main/config/samples/milvus_pulsar_v3.yaml.

The upgrade plan from v2 is still under design.

**Comment by haorenfsa** [comment]
https://github.com/milvus-io/milvus/pull/36435

**Comment by haorenfsa** [comment]
keep alive

**Comment by xiaofan-luan** [comment]
can we do it in Milvus 2.5?

**Comment by haorenfsa** [comment]
Yes
