### ISSUE TITLE
[Bug]: [groupby] There exists dup values of groupby_fields in different pagination results if  searching with groupby+offset

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#30828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20240226-a0531b72-amd64
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.4.- rc36
```

### Current Behavior

There exists dup values of grouby_fields in search results if searching with groupby+offset

### Expected Behavior

the values of groupby_fields shall be unique in search groupby+offset

### Steps To Reproduce

```markdown
1. create a collection 
2. insert 50 sets of entities, every set has 100 entities with a field named int32(value:0-99) as the groupby field
3. flush
4. build hnsw and load
5. search for 3 rounds: search with groupby_field with offset=limit*round, limit=10 (3 pages in 3 searches)

expected: the values of groupby_fields shall be unique for all the 3-search results.
acutal: there exist 1-3 dup values

6. at this moment if you search limit=30 in one search with groupby, the values of groupby_fileds are unique
```

**Comment by MrPresent-Han** [comment]
please help verify the fix:
@yanliang567

**Comment by yanliang567** [comment]
it occasionally reproduces on master-20240311-a99143dd

**Comment by yanliang567** [comment]
the behavior now is that the last record in the first page could be the same with the 1st record in the next page. This is kind of by design. I update the tests to assert the hit rate be larger than 85%. and need more discussion and change the design if it is not acceptable in production.
