### ISSUE TITLE
[Bug]: [restful] insert data without vector fields, shouldn't return "vector length diff from dimension"

### ISSUE THREAD

**Issue by PowderLi** [milvus-io/milvus#30870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3 & master
- SDK version(e.g. pymilvus v2.0.0rc2): restful
```

### Current Behavior

all the collection has at least one vector field
use restful api to insert data into collection without vector field, the server returned "vector length diff from dimension"

### Expected Behavior

should return "missing vector field"

**Comment by zhuwenxing** [comment]
response changed to 
```
{"code":1802,"message":"missing required parameters, required parameters: [collectionName, vector]"}
```
verified and fix
