### ISSUE TITLE
[Bug]: Unable to authenticate after enabling authentication

### ISSUE THREAD

**Issue by NobleMathews** [milvus-io/milvus#30919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.5
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): Command included in reproduction steps   
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.4
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: N.A.
- GPU: N.A.
- Others: chart milvus-4.1.12
```

### Current Behavior

When I attempt to logic with default credentials 

```
from pymilvus import connections, utility
connections.connect(host='x.x.x.x',port='yyyy',user='root',password='Milvus')
```

```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAUTHENTICATED
        details = "auth check failure, please check username and password are correct"
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"auth check failure, please check username and password are correct", grpc_status:16, created_time:"2024-02-28T23:08:56.442801-05:00"}"
```

### Expected Behavior

Should accept default credentials so i can reset the password

### Steps To Reproduce

```markdown
1. Use helm to spinup milvus
2. Use the following command
helm install milvus-service milvus/milvus \
  --set cluster.enabled=false \
  --set etcd.replicaCount=1 \
  --set minio.mode=standalone \
  --set pulsar.enabled=false --values milvus-values.yaml

-values.yaml
extraConfigFiles:
  user.yaml: |+
    common:
      security:
        authorizationEnabled: true


3. Attempt to login
```

### Milvus Log

[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/14442719/milvus-log.tar.gz)

### Anything else?

Same issue can be reproduced on the latest version, I also attempted to add the following based on a blog but that didn't help either. Further went through previous issues that mention similar issues but none of the discussion seemed to help

```
authorization:
   enabled: true
```

**Comment by binbinlv** [comment]
OK，working

**Comment by NobleMathews** [comment]
I've managed to resolve the problem on my end. It turns out that despite uninstalling helm and completely removing all persistent volumes, the old password change for the root user from before enabling authentication was persisting. I apologize for any confusion or inconvenience this may have caused!
