### ISSUE TITLE
failed to get flush channel has this segment: segment not found[Bug]: 

### ISSUE THREAD

**Issue by xiao9510** [milvus-io/milvus#30912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.5
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): centos7
- CPU/Memory: datanode 1C 4G
- GPU: 
- Others:
```

### Current Behavior

The error has been, do not know how to stop and solve,The log contents are as follows

datanode log:
﻿[ERROR] [datanode/services.go:130] ["no flush channel found for the segment, unable to flush"] [segmentID=447188730532014373] [error="failed to get flush channel has this segment: segment not found[segment=447188730532014373]"] [errorVerbose="failed to get flush channel has this segment: segment not found[segment=447188730532014373]\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/pkg/util/merr.WrapErrSegmentNotFound\n  | \t/go/src/github.com/milvus-io/milvus/pkg/util/merr/utils.go:588\n  | github.com/milvus-io/milvus/internal/datanode.(*flowgraphManager).getFlushCh\n  | \t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_manager.go:171\n  | github.com/milvus-io/milvus/internal/datanode.(*DataNode).FlushSegments\n  | \t/go/src/github.com/milvus-io/milvus/internal/datanode/services.go:128\n  | github.com/milvus-io/milvus/internal/distributed/datanode.(*Server).FlushSegments\n  | \t/go/src/github.com/milvus-io/milvus/internal/distributed/datanode/service.go:332\n  | github.com/milvus-io/milvus/internal/proto/datapb._DataNode_FlushSegments_Handler.func1\n  | \t/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:7778\n  | github.com/milvus-io/milvus/pkg/util/interceptor.ServerIDValidationUnaryServerInterceptor.func1\n  | \t/go/src/github.com/milvus-io/milvus/pkg/util/interceptor/server_id_interceptor.go:54\n  | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n  | \t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\n  | github.com/milvus-io/milvus/pkg/util/interceptor.ClusterValidationUnaryServerInterceptor.func1\n  | \t/go/src/github.com/milvus-io/milvus/pkg/util/interceptor/cluster_interceptor.go:48\n  | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n  | \t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\n  | github.com/milvus-io/milvus/pkg/util/logutil.UnaryTraceLoggerInterceptor\n  | \t/go/src/github.com/milvus-io/milvus/pkg/util/logutil/grpc_interceptor.go:23\n  | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n  | \t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\n  | go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1\n  | \t/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.38.0/interceptor.go:342\n  | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n  | \t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\n  | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1\n  | \t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34\n  | github.com/milvus-io/milvus/internal/proto/datapb._DataNode_FlushSegments_Handler\n  | \t/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:7780\n  | google.golang.org/grpc.(*Server).processUnaryRPC\n   | \t/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:1345\n  | google.golang.org/grpc.(*Server).handleStream\n  | \t/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:1722\n  | google.golang.org/grpc.(*Server).serveStreams.func1.2\n  | \t/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:966\n  | runtime.goexit\n  | \t/usr/local/go/src/runtime/asm_amd64.s:1598\nWraps: (2) failed to get flush channel has this segment\nWraps: (3) segment not found[segment=447188730532014373]\nError types: (1) *withstack.withStack (2) *errutil.withPrefix (3) merr.milvusError"] [stack="github.com/milvus-io/milvus/internal/datanode.(*DataNode).FlushSegments\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/services.go:130\ngithub.com/milvus-io/milvus/internal/distributed/datanode.(*Server).FlushSegments\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datanode/service.go:332\ngithub.com/milvus-io/milvus/internal/proto/datapb._DataNode_FlushSegments_Handler.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:7778\ngithub.com/milvus-io/milvus/pkg/util/interceptor.ServerIDValidationUnaryServerInterceptor.func1\n\t/go/src/github.com/milvus-io/milvus/pkg/util/interceptor/server_id_interceptor.go:54\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/milvus-io/milvus/pkg/util/interceptor.ClusterValidationUnaryServerInterceptor.func1\n\t/go/src/github.com/milvus-io/milvus/pkg/util/interceptor/cluster_interceptor.go:48\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/milvus-io/milvus/pkg/util/logutil.UnaryTraceLoggerInterceptor\n\t/go/src/github.com/milvus-io/milvus/pkg/util/logutil/grpc_interceptor.go:23\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngo.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1\n\t/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.38.0/interceptor.go:342\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34\ngithub.com/milvus-io/milvus/internal/proto/datapb._DataNode_FlushSegments_Handler\n\t/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:7780\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:1345\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:1722\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:966"]
﻿
datacoord log:
024-02-29T01:21:17.145442415Z [2024/02/29 01:21:17.145 +00:00] [ERROR] [datacoord/session_manager.go:179] ["flush call (perhaps partially) failed"] ["dataNode ID"=1679] [error="failed to get flush channel has this segment: segment not found[segment=447188730532014373]"] [stack="github.com/milvus-io/milvus/internal/datacoord.(*SessionManagerImpl).execFlush\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/session_manager.go:179"]
2024-02-29T01:21:17.351319885Z [2024/02/29 01:21:17.351 +00:00] [INFO] [datacoord/services.go:1421] ["start flushing segments"] [traceID=4b9314212a238e29c7054c3865f9278f] ["segment IDs"="[447188730808523384]"]
2024-02-29T01:21:17.352074364Z [2024/02/29 01:21:17.352 +00:00] [ERROR] [datacoord/session_manager.go:179] ["flush call (perhaps partially) failed"] ["dataNode ID"=1678] [error="failed to get flush channel has this segment: segment not found[segment=447188730808523384]"] [stack="github.com/milvus-io/milvus/internal/datacoord.(*SessionManagerImpl).execFlush\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/session_manager.go:179"]
﻿

### Expected Behavior

When I do bulk ingestion, it should not raise the SEGMENT NOT FOUND error which caused timeout issues for data ingestion.

When I do bulk ingestion, it should not raise the SEGMENT NOT FOUND error

### Steps To Reproduce

```markdown
Not sure how to reproduce it.
```

### Milvus Log

datanode log:
﻿[ERROR] [datanode/services.go:130] ["no flush channel found for the segment, unable to flush"] [segmentID=447188730532014373] [error="failed to get flush channel has this segment: segment not found[segment=447188730532014373]"] [errorVerbose="failed to get flush channel has this segment: segment not found[segment=447188730532014373]\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/pkg/util/merr.WrapErrSegmentNotFound\n  | \t/go/src/github.com/milvus-io/milvus/pkg/util/merr/utils.go:588\n  | github.com/milvus-io/milvus/internal/datanode.(*flowgraphManager).getFlushCh\n  | \t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_manager.go:171\n  | github.com/milvus-io/milvus/internal/datanode.(*DataNode).FlushSegments\n  | \t/go/src/github.com/milvus-io/milvus/internal/datanode/services.go:128\n  | github.com/milvus-io/milvus/internal/distributed/datanode.(*Server).FlushSegments\n  | \t/go/src/github.com/milvus-io/milvus/internal/distributed/datanode/service.go:332\n  | github.com/milvus-io/milvus/internal/proto/datapb._DataNode_FlushSegments_Handler.func1\n  | \t/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:7778\n  | github.com/milvus-io/milvus/pkg/util/interceptor.ServerIDValidationUnaryServerInterceptor.func1\n  | \t/go/src/github.com/milvus-io/milvus/pkg/util/interceptor/server_id_interceptor.go:54\n  | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n  | \t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\n  | github.com/milvus-io/milvus/pkg/util/interceptor.ClusterValidationUnaryServerInterceptor.func1\n  | \t/go/src/github.com/milvus-io/milvus/pkg/util/interceptor/cluster_interceptor.go:48\n  | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n  | \t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\n  | github.com/milvus-io/milvus/pkg/util/logutil.UnaryTraceLoggerInterceptor\n  | \t/go/src/github.com/milvus-io/milvus/pkg/util/logutil/grpc_interceptor.go:23\n  | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n  | \t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\n  | go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1\n  | \t/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.38.0/interceptor.go:342\n  | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n  | \t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\n  | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1\n  | \t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34\n  | github.com/milvus-io/milvus/internal/proto/datapb._DataNode_FlushSegments_Handler\n  | \t/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:7780\n  | google.golang.org/grpc.(*Server).processUnaryRPC\n   | \t/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:1345\n  | google.golang.org/grpc.(*Server).handleStream\n  | \t/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:1722\n  | google.golang.org/grpc.(*Server).serveStreams.func1.2\n  | \t/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:966\n  | runtime.goexit\n  | \t/usr/local/go/src/runtime/asm_amd64.s:1598\nWraps: (2) failed to get flush channel has this segment\nWraps: (3) segment not found[segment=447188730532014373]\nError types: (1) *withstack.withStack (2) *errutil.withPrefix (3) merr.milvusError"] [stack="github.com/milvus-io/milvus/internal/datanode.(*DataNode).FlushSegments\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/services.go:130\ngithub.com/milvus-io/milvus/internal/distributed/datanode.(*Server).FlushSegments\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datanode/service.go:332\ngithub.com/milvus-io/milvus/internal/proto/datapb._DataNode_FlushSegments_Handler.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:7778\ngithub.com/milvus-io/milvus/pkg/util/interceptor.ServerIDValidationUnaryServerInterceptor.func1\n\t/go/src/github.com/milvus-io/milvus/pkg/util/interceptor/server_id_interceptor.go:54\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/milvus-io/milvus/pkg/util/interceptor.ClusterValidationUnaryServerInterceptor.func1\n\t/go/src/github.com/milvus-io/milvus/pkg/util/interceptor/cluster_interceptor.go:48\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/milvus-io/milvus/pkg/util/logutil.UnaryTraceLoggerInterceptor\n\t/go/src/github.com/milvus-io/milvus/pkg/util/logutil/grpc_interceptor.go:23\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngo.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1\n\t/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.38.0/interceptor.go:342\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34\ngithub.com/milvus-io/milvus/internal/proto/datapb._DataNode_FlushSegments_Handler\n\t/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:7780\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:1345\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:1722\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:966"]
﻿
datacoord log:
024-02-29T01:21:17.145442415Z [2024/02/29 01:21:17.145 +00:00] [ERROR] [datacoord/session_manager.go:179] ["flush call (perhaps partially) failed"] ["dataNode ID"=1679] [error="failed to get flush channel has this segment: segment not found[segment=447188730532014373]"] [stack="github.com/milvus-io/milvus/internal/datacoord.(*SessionManagerImpl).execFlush\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/session_manager.go:179"]
2024-02-29T01:21:17.351319885Z [2024/02/29 01:21:17.351 +00:00] [INFO] [datacoord/services.go:1421] ["start flushing segments"] [traceID=4b9314212a238e29c7054c3865f9278f] ["segment IDs"="[447188730808523384]"]
2024-02-29T01:21:17.352074364Z [2024/02/29 01:21:17.352 +00:00] [ERROR] [datacoord/session_manager.go:179] ["flush call (perhaps partially) failed"] ["dataNode ID"=1678] [error="failed to get flush channel has this segment: segment not found[segment=447188730808523384]"] [stack="github.com/milvus-io/milvus/internal/datacoord.(*SessionManagerImpl).execFlush\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/session_manager.go:179"]
﻿

### Anything else?

No response

**Comment by xiao9510** [comment]
Loaded Collections：86

All Collections：86

Entities：16,526

partition：1

index：IVF_FLAT

**Comment by yanliang567** [comment]
@xiao9510 Could you please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @xiao9510
