### ISSUE TITLE
[Bug]: datanode down

### ISSUE THREAD

**Issue by Richard-lrg** [milvus-io/milvus#30921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.3 
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):   pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Problem: 
It has been discovered that Milvus has triggered a large amount of data compression for some reason, with a large number of segments being flushed, causing a large number of reads and writes to the minio. The CPU load on the machine where the minio is located is high, resulting in minio write timeouts and causing datanode crashes.

How to control the read and write rate of minio when Milvus automatically performs data compression?

What impact will it have on the system if dataCoord.com action. enableAutoComparison is set to false?
（My collection is indexed using FLAT）

**Comment by xiaofan-luan** [comment]
if you mean compaction, by default there is a concurrency of compaction set to be 10. 

you could turn dataCoord.compaction.maxParallelTaskNum to smaller number. And I highly recommend you to assign more resource to datanode
