### ISSUE TITLE
  How to prevent inserting repeated vectors

### ISSUE THREAD

**Issue by prophyfang** [milvus-io/milvus#3093]
When updating data, vectors of old data may be inserted repeatedly. Can milvus could be set non repeating mode?

**Comment by prophyfang** [comment]
This function is very important in our business scenario. Does Milvus plan to develop this function in the future.

**Comment by tinkerlin** [comment]
refer to #2545

**Comment by JinHai-CN** [comment]
This is about entity ID deduplication. We do have the plan to solve this issue.

**Comment by shengjun1985** [comment]
This is a duplicate issue.
And we will solve it in the feature.
Thank you for your concern and support for our project.
