### ISSUE TITLE
[Bug]: paramtable always use "/" to read disk total when disk limit env is not provided

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#30943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 0c7474d & 2.3.10
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

when `LOCAL_STORAGE_SIZE` is not set, milvus will check disk total to limit load resource
However it always checks "/" instead of localStorage path, which may causing reading wrong device

### Expected Behavior

Use local storage path to check disk capacity

**Comment by xiaofan-luan** [comment]
good catch, this should be fixed by 2.3
