### ISSUE TITLE
[Bug]: count result of query less than expect with Mmap enabled

### ISSUE THREAD

**Issue by bacchusch** [milvus-io/milvus#30957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.9
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):v2.3.3
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 8/32
- GPU: 
- Others:
```

### Current Behavior

count entities that meet specific conditions:
1. create collection
FieldSchema(name="pk", dtype=DataType.VARCHAR, is_primary=True, auto_id=False, max_length=100),
FieldSchema(name="random", dtype=DataType.DOUBLE),
FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=dim)
3. insert 3000 rows of data
4. build index and load collection
5. count entities that meet specific conditions
result = hello_milvus.query(consistency_level="Strong", expr=f'pk in ["0","100","200","300","400"]', output_fields=["count(*)"])
print(f"Total {result}")
result = hello_milvus.query(consistency_level="Strong", expr=f'pk in ["0","100","200","300","400"]', output_fields=["pk"])
print(f"Total {len(result)}")
result = hello_milvus.query(consistency_level="Strong", expr=f"",output_fields=["pk"], limit=3000)
print(f"Total {len(result)}")
7. the count result is:
Total [{'count(*)': 2}]
Total 2
Total 108

### Expected Behavior

expect result should be:
Total [{'count(*)': 5}]
Total 5
Total 3000

### Steps To Reproduce

```markdown
import numpy as np
from pymilvus import (
    connections,
    utility,
    FieldSchema, CollectionSchema, DataType,
    Collection,
)

host = '10.224.0.1'

fmt = "\n=== {:30} ===\n"
search_latency_fmt = "search latency = {:.4f}s"
num_entities, dim = 3000, 8

print(fmt.format("start connecting to Milvus"))
connections.connect("default", host=host, port="19530")

has = utility.has_collection("hello_milvus")
print(f"Does collection hello_milvus exist in Milvus: {has}")

if has:
    hello_milvus = Collection("hello_milvus")
    print(fmt.format("start drop collection"))
    hello_milvus.drop()

fields = [
    FieldSchema(name="pk", dtype=DataType.VARCHAR, is_primary=True, auto_id=False, max_length=100),
    FieldSchema(name="random", dtype=DataType.DOUBLE),
    FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=dim)
]

schema = CollectionSchema(fields, "hello_milvus is the simplest demo to introduce the APIs")

print(fmt.format("Create collection `hello_milvus`"))
hello_milvus = Collection("hello_milvus", schema, consistency_level="Strong")

print(fmt.format("Start inserting entities"))
rng = np.random.default_rng(seed=19530)
entities = [
    # provide the pk field because `auto_id` is set to False
    [str(i) for i in range(num_entities)],
    rng.random(num_entities).tolist(),  # field random, only supports list
    rng.random((num_entities, dim)),    # field embeddings, supports numpy.ndarray and list
]
hello_milvus.insert(entities)

hello_milvus.flush()
print(f"Number of entities in Milvus: {hello_milvus.num_entities}")  # check the num_entities

print(fmt.format("Start Creating index IVF_FLAT"))
index = {
    "index_type": "IVF_FLAT",
    "metric_type": "L2",
    "params": {"nlist": 128},
}

hello_milvus.create_index("embeddings", index)

hello_milvus.load()

print(fmt.format("Start count"))
result = hello_milvus.query(consistency_level="Strong", expr=f'pk in ["0","100","200","300","400"]', output_fields=["count(*)"])
print(f"Total {result}")

result = hello_milvus.query(consistency_level="Strong", expr=f'pk in ["0","100","200","300","400"]', output_fields=["pk"])
print(f"Total {len(result)}")

result = hello_milvus.query(consistency_level="Strong", expr=f"",output_fields=["pk"], limit=3000)
print(f"Total {len(result)}")
```

**Comment by yanliang567** [comment]
@bacchusch  I ran the code sample you attached above for 3 times on milvus v2.3.9, but it returns as expected
![image](https://github.com/milvus-io/milvus/assets/82361606/32248341-84e6-4cad-9191-f94a18b1d6ad)

/assign @bacchusch 
/unassign

**Comment by bacchusch** [comment]
please enable mmap, and run it again

**Comment by bacchusch** [comment]
@yanliang567

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version:2.3.9
> - Deployment mode(standalone or cluster):cluster
> - MQ type(rocksmq, pulsar or kafka):    kafka
> - SDK version(e.g. pymilvus v2.0.0rc2):v2.3.3
> - OS(Ubuntu or CentOS): ubuntu
> - CPU/Memory: 8/32
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> count entities that meet specific conditions:
> 
> 1. create collection
>    FieldSchema(name="pk", dtype=DataType.VARCHAR, is_primary=True, auto_id=False, max_length=100),
>    FieldSchema(name="random", dtype=DataType.DOUBLE),
>    FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=dim)
> 2. insert 3000 rows of data
> 3. build index and load collection
> 4. count entities that meet specific conditions
>    result = hello_milvus.query(consistency_level="Strong", expr=f'pk in ["0","100","200","300","400"]', output_fields=["count(*)"])
>    print(f"Total {result}")
>    result = hello_milvus.query(consistency_level="Strong", expr=f'pk in ["0","100","200","300","400"]', output_fields=["pk"])
>    print(f"Total {len(result)}")
>    result = hello_milvus.query(consistency_level="Strong", expr=f"",output_fields=["pk"], limit=3000)
>    print(f"Total {len(result)}")
> 5. the count result is:
>    Total [{'count(*)': 2}]
>    Total 2
>    Total 108
> 
> ### Expected Behavior
> expect result should be: Total [{'count(*)': 5}] Total 5 Total 3000
> 
> ### Steps To Reproduce
> ```
> import numpy as np
> from pymilvus import (
>     connections,
>     utility,
>     FieldSchema, CollectionSchema, DataType,
>     Collection,
> )
> 
> host = '10.224.0.1'
> 
> fmt = "\n=== {:30} ===\n"
> search_latency_fmt = "search latency = {:.4f}s"
> num_entities, dim = 3000, 8
> 
> print(fmt.format("start connecting to Milvus"))
> connections.connect("default", host=host, port="19530")
> 
> has = utility.has_collection("hello_milvus")
> print(f"Does collection hello_milvus exist in Milvus: {has}")
> 
> if has:
>     hello_milvus = Collection("hello_milvus")
>     print(fmt.format("start drop collection"))
>     hello_milvus.drop()
> 
> fields = [
>     FieldSchema(name="pk", dtype=DataType.VARCHAR, is_primary=True, auto_id=False, max_length=100),
>     FieldSchema(name="random", dtype=DataType.DOUBLE),
>     FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=dim)
> ]
> 
> schema = CollectionSchema(fields, "hello_milvus is the simplest demo to introduce the APIs")
> 
> print(fmt.format("Create collection `hello_milvus`"))
> hello_milvus = Collection("hello_milvus", schema, consistency_level="Strong")
> 
> print(fmt.format("Start inserting entities"))
> rng = np.random.default_rng(seed=19530)
> entities = [
>     # provide the pk field because `auto_id` is set to False
>     [str(i) for i in range(num_entities)],
>     rng.random(num_entities).tolist(),  # field random, only supports list
>     rng.random((num_entities, dim)),    # field embeddings, supports numpy.ndarray and list
> ]
> hello_milvus.insert(entities)
> 
> hello_milvus.flush()
> print(f"Number of entities in Milvus: {hello_milvus.num_entities}")  # check the num_entities
> 
> print(fmt.format("Start Creating index IVF_FLAT"))
> index = {
>     "index_type": "IVF_FLAT",
>     "metric_type": "L2",
>     "params": {"nlist": 128},
> }
> 
> hello_milvus.create_index("embeddings", index)
> 
> hello_milvus.load()
> 
> print(fmt.format("Start count"))
> result = hello_milvus.query(consistency_level="Strong", expr=f'pk in ["0","100","200","300","400"]', output_fields=["count(*)"])
> print(f"Total {result}")
> 
> result = hello_milvus.query(consistency_level="Strong", expr=f'pk in ["0","100","200","300","400"]', output_fields=["pk"])
> print(f"Total {len(result)}")
> 
> result = hello_milvus.query(consistency_level="Strong", expr=f"",output_fields=["pk"], limit=3000)
> print(f"Total {len(result)}")
> ```
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

could you print all your result out and check if the pk is as expected

**Comment by bacchusch** [comment]
for the third query, there is no any filter,  so it should return all data, the count result should be 3000. Right?

result = hello_milvus.query(consistency_level="Strong", expr=f"",output_fields=["pk"], limit=3000)
print(f"Total {len(result)}")

**Comment by yanliang567** [comment]
/assign @elstic 
please try to reproduce the issue with mmap enabled.

**Comment by elstic** [comment]
> /assign @elstic please try to reproduce the issue with mmap enabled.

Yes, I reproduced the problem when mmap was turned on, the query did not return id > 107

**Comment by yanliang567** [comment]
/assign @sunby  
please help to take a look

**Comment by sunby** [comment]
I've found the problem and am working on it

**Comment by sunby** [comment]
@yanliang567 https://github.com/milvus-io/milvus/pull/30848 this pr already fix it.

**Comment by sunby** [comment]
> @yanliang567 #30848 this pr already fix it.

2.4 would not have this problems, but we need to cherry pick this pr to 2.3 branch if we continue to release v2.3.12.

**Comment by longjiquan** [comment]
already cherry-picked, see https://github.com/milvus-io/milvus/pull/31274

**Comment by elstic** [comment]
> already cherry-picked, see #31274


Verified and fixed
Verify image: v2.3.12-20240315-50bfde92-amd64
