### ISSUE TITLE
[Bug]: Segment version doesn't update as expected.

### ISSUE THREAD

**Issue by weiliu1031** [milvus-io/milvus#30950]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master and 2.3
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

when querynode handle load request, if the segment is in loading state, it will try to do following things:
1. skip load segment
2. to to update segment version
3. wait until segment loaded.

but if the loading goroutine hasn't put segment to manager yet, try to update segment version will do nothing, then the segment's version doesn't update as expected.

### Expected Behavior

when querynode handle load request, if the segment is in loading state, it will try to do following things:
1. skip load segment
2. wait until segment loaded.
3. to to update segment version

**Comment by yanliang567** [comment]
@weiliu1031 just make sure that segment version is nothing about segment index version, right?
/unassign

**Comment by weiliu1031** [comment]
> @weiliu1031 just make sure that segment version is nothing about segment index version, right? /unassign

the segment version is exactly segment load version, to verify which segment is latest when duplicates happens

**Comment by weiliu1031** [comment]
when segment version doesn't update as expected, duplicate segment with different version may exist at same time. and the  segment with older version can't be released by segment_checker.
