### ISSUE TITLE
[Bug]: Failed to allocate memory for child args: 'Cannot allocate memory'

### ISSUE THREAD

**Issue by 15038092523** [milvus-io/milvus#30990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:milvus:v2.3.10
- Deployment mode(standalone or cluster):standalone :
- OS(Ubuntu or CentOS): Linux S-919 4.19.90-24.4.v2101.ky10.aarch64
```

### Current Behavior

When I use docker compose to start milvus on Kylin v10 system and Kunpeng cpu, it Cannot start due to exception. Failed to allocate memory for child args: 'Cannot allocate memory'. The image used is milvus:v2.3.10-20240223-2896f5eb-arm64

### Expected Behavior

milvus was started normally on the server with Kylin v10 Kunpeng processor

### Steps To Reproduce

```markdown
This is my docker-compose.yml:

version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.3.10-20240223-2896f5eb-arm64
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvus
```

### Milvus Log

[root@S-919 milvus]# docker logs 1be56517d00e
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
[FATAL tini (1)] Failed to allocate memory for child args: 'Cannot allocate memory'
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
[FATAL tini (1)] Failed to allocate memory for child args: 'Cannot allocate memory'

**Comment by yanliang567** [comment]
@15038092523 we don't have any milvus tests on Kylin v10 system or Kunpeng cpu. Please read [Install Milvus with docker compose](https://milvus.io/docs/install_standalone-docker-compose.md) for the supported os.

/assign @15038092523 
/unassign

**Comment by xiaofan-luan** [comment]
you will need to rebuild milvus with -DMILVUS_JEMALLOC_LG_PAGE=16 to enable 64kB for kylin system.

@zwd1208 
what may happen if add this config to ubuntu image?

**Comment by zwd1208** [comment]
@xiaofan-luan I'm not sure yet.  I will try it.

**Comment by ALLinLLM** [comment]
> @zwd1208 @xiaofan-luan I tried to rebuild milvus with -DMILVUS_JEMALLOC_LG_PAGE=16 on ubuntu image, and run milvus with docker compose without problems on arm64 system.

could you upload the arm64 docker image with -DMILVUS_JEMALLOC_LG_PAGE=16 to dockerhub? I have an ECS on HUAWEI Clound with arm64 and kunpeng cpu

**Comment by xiaofan-luan** [comment]
if 64k works for both ubuntu and kylin system, we coud set -DMILVUS_JEMALLOC_LG_PAGE=16 by default

**Comment by pingliu** [comment]
@ALLinLLM I upload the arm64 docker image with -DMILVUS_JEMALLOC_LG_PAGE=16 to your test ecs, and run milvus with docker compose without problems.

this image works for both ubuntu(4k pagesize) and kylin(64k pagesize) system.

**Comment by ALLinLLM** [comment]
> @ALLinLLM I upload the arm64 docker image with -DMILVUS_JEMALLOC_LG_PAGE=16 to your test ecs, and run milvus with docker compose without problems.
> 
> this image works for both ubuntu(4k pagesize) and kylin(64k pagesize) system.

@pingliu  Thanks for your rapid test. I can use this image to use.
I wonder what will the pagesize affect the benchmark of io or seach?

**Comment by ALLinLLM** [comment]
docker pull poboinfo/milvus:latest-arm64

**Comment by 15038092523** [comment]
> For me, the problem has solved now. I pushed the docker image on arm64 ECS to dockerhub, and verify it on my local machine with Kylin V10 arm64 OS. For those who use arm64 OS with 64K pagesize, such as Kylin V10 and OpenEuler 20.03/22.03, you can download this docker image, and modify your docker_compose.yml, it should work. `docker pull poboinfo/milvus:latest-arm64`

By using this arm image, my problem is solved, thanks.

**Comment by shilei4260** [comment]
怎么解决的

**Comment by ALLinLLM** [comment]
@shilei4260 use milvus >= 2.3.12

**Comment by shilei4260** [comment]
我安装的2.4.1 安装成功后，容器启动就会报错

**Comment by shilei4260** [comment]
@ALLinLLM

**Comment by xiaofan-luan** [comment]
1.  make sure you are using arm image.
2. if you are using Kylin and some other OS, there is a memoray allocator page issue. you can search on github to find a way to work

**Comment by shilei4260** [comment]
我是openeuler系统

**Comment by xiaofan-luan** [comment]
please check this document https://github.com/milvus-io/milvus/blob/555df49d256ed6ea1e95f2c679b6cf80146cd1c8/DEVELOPMENT.md?plain=1#L27
about Check OS PAGESIZE

**Comment by CHNVigny** [comment]
> [@zwd1208](https://github.com/zwd1208) [@xiaofan-luan](https://github.com/xiaofan-luan) I tried to rebuild milvus with -DMILVUS_JEMALLOC_LG_PAGE=16 on ubuntu image, and run milvus with docker compose without problems on arm64 system.

can you give your dockerfile to me? i'll appreciate for you!!!!!!
