### ISSUE TITLE
[Enhancement]: Refine proxy connection manager

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#31007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Change proxy connection to concurrent RW safe object and remove blocking logic

### Why is this needed?

Proxy connection manager may occupy lots of memory and goroutine if the client invoke `Connect` grpc per request by mistake

**Comment by congqixia** [comment]
after some offline discussion, we need to add auto-pruning logic for connection manager
/assign @longjiquan

**Comment by longjiquan** [comment]
already fixed by #31037 
/close
