### ISSUE TITLE
[Bug]: [restful v2]search api lack of anns_field param

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#31010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

method: post, 
url: http://10.104.19.54:19530/v2/vectordb/entities/search, 
cost time: 0.1985950469970703, 
header: {'Content-Type': 'application/json', 'Authorization': 'Bearer root:Milvus', 'Accept-Type-Allow-Int64': 'true', 'RequestId': '00e7a5f2-da19-11ee-8e74-acde48001122'}, 
payload: {"collectionName": "test_collection_2024_03_04_19_18_56_432669zhGgaUJc", "filter": "word_count > 100", "groupingField": "user_id", "outputFields": ["*"], "searchParams": {"metricType": "COSINE", "params": {"radius": "0.1", "range_filter": "0.8"}}, "limit": 100}, 
response: {"code":65535,"message":"multiple anns_fields exist, please specify a anns_field in search_params"}

**Comment by zhuwenxing** [comment]
@czs007 
in Milvus client doc, ann_fields was also missed

```
search(
    collection_name: str,
    data: Union[List[list], list],
    filter: str = "",
    limit: int = 10,
    output_fields: Optional[List[str]] = None,
    search_params: Optional[dict] = None,
    timeout: Optional[float] = None,
    partition_names: Optional[List[str]] = None,
    **kwargs,
) -> List[dict]
```

**Comment by zhuwenxing** [comment]
a minor suggestion
[float_vector, float16_vector,,,]  --> [float_vector, float16_vector, ...]

**Comment by bryantmo** [comment]
I resolved the issue using the following approach:

1. Identified the version of the Milvus cluster: `image: milvusdb/milvus:v2.5.8`
2. Reviewed the Milvus documentation for the target version: https://milvus.io/docs/zh/v2.5.x/single-vector-search.md
3. Finally, found a working code example for vector search: ```
res = client.search(
collection_name="quick_setup",
anns_field="vector",
data=[query_vector],
limit=3,
search_params={"metric_type": "IP"}
)
```
