### ISSUE TITLE
[Bug]: FlushedSegmentFileNum is not accurate

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#31033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

currently metrics.FlushedSegmentFileNum is only increase on postFlush but never decrease even if the segment has been dropped or compacted

**Comment by XuanYang-cn** [comment]
@xiaofan-luan I didnt see it at grafana dashboard in Milvus2.0 and Milvus2.0-v2, how did you identify the bug? so that we're able to verify its fixed.

@LoveEachDay isit reasonable for FileNum to use Histogram metric type? didn't find this metric in Dashboard, so I'm curious what are we monitoring.

**Comment by xiaocai2333** [comment]
The metrics type is histogram, instead gauge.
Maybe there is no bug.

**Comment by xiaofan-luan** [comment]
> The metrics type is histogram, instead gauge. Maybe there is no bug.

FlushedSegmentFileNum 
why should this be a histogram? 

if recorded how many files generated maybe we should name it?

**Comment by czs007** [comment]
This monitoring endeavor captures the distribution of line numbers within individual binlog files, with the aim of scrutinizing the occurrence of diminutive files.

**Comment by czs007** [comment]
Indeed, a renaming might be necessary for this metric
