### ISSUE TITLE
CentOS8.0 docker milvus-0.10.0 start ERROR "7 Illegal instruction"

### ISSUE THREAD

**Issue by wqch22** [milvus-io/milvus#3103]
**Please state you issue using the following template and, most importantly, in English.**

**Describe the bug**
install refer to :https://milvus.io/cn/docs/v0.10.0/cpu_milvus_docker.md

[wqch@localhost ~]$ sudo docker run -d --name milvus_cpu_0.10.0 -p 19530:19530 -p 19121:19121 -v /home/wqch/milvus/db:/var/lib/milvus/db -v /home/wqch/milvus/conf:/var/lib/milvus/conf -v /home/wqch/milvus/logs:/var/lib/milvus/logs -v /home/wqch/milvus/wal:/var/lib/milvus/wal milvusdb/milvus:0.10.0-cpu-d061620-5f3c00
af3537785e1750a851f64f408d513dd1afc0e2dae547ca138754d432aae77d6c
[wqch@localhost ~]$ sudo docker ps -a
CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS                       PORTS               NAMES
af3537785e17        milvusdb/milvus:0.10.0-cpu-d061620-5f3c00   "/var/lib/milvus/doc…"   6 seconds ago       Exited (132) 2 seconds ago                       milvus_cpu_0.10.0
[wqch@localhost ~]$ sudo docker logs af3537785e17
./start_server.sh: line 3:     7 Illegal instruction     (core dumped) ../bin/milvus_server -c ../conf/server_config.yaml

**Expected behavior**
milvus start up OKKK

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

`server_config.yaml` : the same from demo
CentOS8.0
milvus version: milvusdb/milvus:0.10.0-cpu-d061620-5f3c00
[root@localhost ~]# cat /proc/cpuinfo | grep sse4
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 movbe popcnt tsc_deadline_timer rdrand lahf_lm 3dnowprefetch epb pti ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid tsc_adjust smep erms dtherm ida arat md_clear

**Comment by JinHai-CN** [comment]
Please try v0.10.1.

**Comment by wqch22** [comment]
[wqch@localhost conf]$ sudo docker run -d --name milvus_cpu_0.10.1 \
> -p 19530:19530 \
> -p 19121:19121 \
> -v /home/$USER/milvus/db:/var/lib/milvus/db \
> -v /home/$USER/milvus/conf:/var/lib/milvus/conf \
> -v /home/$USER/milvus/logs:/var/lib/milvus/logs \
> -v /home/$USER/milvus/wal:/var/lib/milvus/wal \
> milvusdb/milvus:0.10.1-cpu-d072020-bd02b1
1a1db7b29000d1afd4d301ad4523b5e630a9f33b5dfdbc7009bc097f81ca9a54
[wqch@localhost conf]$ sudo docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
[wqch@localhost conf]$ sudo docker logs 1a1db7b29000d1afd4d301ad4523b5e630a9f33b5dfdbc7009bc097f81ca9a54
[wqch@localhost conf]$ sudo docker ps -a
CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS                        PORTS               NAMES
1a1db7b29000        milvusdb/milvus:0.10.1-cpu-d072020-bd02b1   "/var/lib/milvus/bin…"   44 seconds ago      Exited (132) 41 seconds ago                       milvus_cpu_0.10.1
af3537785e17        milvusdb/milvus:0.10.0-cpu-d061620-5f3c00   "/var/lib/milvus/doc…"   25 hours ago        Exited (132) 25 hours ago                         milvus_cpu_0.10.0
[wqch@localhost conf]$ sudo docker logs 1a1db7b29000
[wqch@localhost conf]$ sudo docker rm af3537785e17
af3537785e17
[wqch@localhost conf]$ sudo docker ps -a
CONTAINER ID        IMAGE                                       COMMAND                  CREATED              STATUS                            PORTS               NAMES
1a1db7b29000        milvusdb/milvus:0.10.1-cpu-d072020-bd02b1   "/var/lib/milvus/bin…"   About a minute ago   Exited (132) About a minute ago                       milvus_cpu_0.10.1

**Comment by tinkerlin** [comment]
You need to run this command to know whether your cpu supports 'avx2' instruction.
```
cat /proc/cpuinfo
```

**Comment by cydrain** [comment]
@wqch22 this issue is similar with #3532
Can you download avx_test2.tar.gz and try if you can run this code in your machine ?

**Comment by ucas010** [comment]
hi ,dear
what does it mean ?
-v /home/$USER/milvus/db:/var/lib/milvus/db
-v /home/$USER/milvus/conf:/var/lib/milvus/conf
-v /home/$USER/milvus/logs:/var/lib/milvus/logs
-v /home/$USER/milvus/wal:/var/lib/milvus/wal \

-v /home/** is what and the /var/** is what ?
thx
