### ISSUE TITLE
[Bug]: binlogs are not released in CleanData

### ISSUE THREAD

**Issue by sunby** [milvus-io/milvus#31042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

clean files in segment CleanData

**Comment by xiaofan-luan** [comment]
Quick question.
did we can't binlogs as part of LRU cache?
@sunby 
I'm worried about current lru implementation can not estimate disk usage well.

easier implementation is to purge disk usage based on disk usage.
We start from 85% of the disk capacity and purged to 75% each time.

**Comment by sunby** [comment]
> Quick question. did we can't binlogs as part of LRU cache? @sunby I'm worried about current lru implementation can not estimate disk usage well.
> 
> easier implementation is to purge disk usage based on disk usage. We start from 85% of the disk capacity and purged to 75% each time.

yes, we plan to add segment disk usage estimation for lru cache and use disk usage as the capacity.

**Comment by xiaofan-luan** [comment]
may not need for 2.4
