### ISSUE TITLE
[Bug]: Collection in datacoord is leaked

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#31053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The collection object is leaked because of not cleaning up when collection is dropped

**Comment by jaime0815** [comment]
related to https://github.com/milvus-io/milvus/pull/32175
