### ISSUE TITLE
[Bug]: The non-delegator queryNode oomkilled and search continues to fail after recovery

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#31074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. deploy milvus with flushRate: 0.016
```
quotaAndLimits:
    flushRate:
      enabled: true
      max: 0.016 
```
2. prepare test: create collection with partition-key field, 32 num_partitions, -> hnsw index -> load -> insert 30M -> flush -> index again -> load again
3. concurrent requests: upsert + search + flush
```
[2024-03-04 09:08:21,357 -  INFO - fouram]: [check_params] scene_concurrent_locust required params: {'dataset_params': {'metric_type': 'L2', 'dim': 128, 'scalars_params': {'int64_1': {'params': {'is_partition_key': True}}}, 'dataset_name': 'sift', 'dataset_size': '30m', 'ni_per': 50000}, 'collection_params': {'other_fields': ['int64_1'], 'shards_num': 2, 'num_partitions': 32}, 'load_params': {}, 'release_params': {'release_of_reload': True}, 'index_params': {'index_type': 'HNSW', 'index_param': {'M': 8, 'efConstruction': 200}}, 'concurrent_params': {'concurrent_number': 50, 'during_time': '10h', 'interval': 120}, 'concurrent_tasks': [{'type': 'search', 'weight': 30, 'params': {'nq': 100, 'top_k': 100, 'output_fields': ['int64_1'], 'search_param': {'ef': 128}, 'timeout': 120}}, {'type': 'flush', 'weight': 1, 'params': {'timeout': 120}}, {'type': 'upsert', 'weight': 19, 'params': {'nb': 200, 'timeout': 120, 'start_id': 0, 'random_id': True, 'random_vector': True}}]} (params_check.py:33)
```
4. a non-delegator querynode-chq8 oomkilled at 2024-03-04 11:01
[pod_last_terminated_reason](https://grafana-4am.zilliz.cc/explore?panes=%7B%22nhf%22:%7B%22datasource%22:%22P1809F7CD0C75ACF3%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22kube_pod_container_status_last_terminated_reason%7Bpod%3D~%5C%22level-zero-par-key-op-48-9325-milvus-.%2A%5C%22%7D%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P1809F7CD0C75ACF3%22%7D,%22editorMode%22:%22code%22,%22legendFormat%22:%22__auto%22,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%221709543801335%22,%22to%22:%221709690265124%22%7D%7D%7D&schemaVersion=1&orgId=1)
```
09:07 dn completed
09:09 proxy completed
11:01 qn-chq8 oom
14:38 qn-nkbp etcd-conn terminated
```
5. queryNode loaded segment before first oom
![image](https://github.com/milvus-io/milvus/assets/27288593/73589e56-5c45-4ed5-a76f-39f2f6199e4a)

6. loaded segment num after recover from qn terminated, the num of sealed-L1 segment has not decreased
![image](https://github.com/milvus-io/milvus/assets/27288593/81052e2f-6cea-4ffa-92a5-04fe0e516c39)

### Expected Behavior

1. why qn-chq8 oomkilled only with 400 sealed segments?
2. search always failed after qn-chq8 recovered from oom ?

### Milvus Log

- argo: https://argo-workflows.zilliz.cc/archived-workflows/qa/6266c692-5bef-4428-a06f-a39f6bd51428?nodeId=level-zero-stable-9dkbz-2516508747
-  [Metrics of level-zero-par-key-op-48-9325](https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=P1809F7CD0C75ACF3&var-cluster=&var-namespace=qa-milvus&var-instance=level-zero-par-key-op-48-9325&var-collection=All&var-app_name=milvus&from=1709541751032&to=1709609302252)
-  [client logs](https://grafana-4am.zilliz.cc/explore?panes=%7B%22Qa9%22:%7B%22datasource%22:%22vhI6Vw67k%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcluster%3D%5C%224am%5C%22,%20namespace%3D%5C%22qa%5C%22,%20pod%3D%5C%22level-zero-stable-74bfg-3275937321%5C%22%7D%20%7C%3D%20%5C%22ERROR%5C%22%20%7C%3D%20%5C%22Collection.search%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22vhI6Vw67k%22%7D,%22editorMode%22:%22code%22,%22hide%22:false%7D,%7B%22refId%22:%22C%22,%22expr%22:%22%7Bcluster%3D%5C%224am%5C%22,%20namespace%3D%5C%22qa%5C%22,%20pod%3D%5C%22level-zero-stable-74bfg-3275937321%5C%22%7D%20%7C%3D%20%5C%22ERROR%5C%22%20%7C%3D%20%5C%22Collection.upsert%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22vhI6Vw67k%22%7D,%22editorMode%22:%22code%22,%22hide%22:true%7D%5D,%22range%22:%7B%22from%22:%221709546411000%22,%22to%22:%221709583498000%22%7D%7D%7D&schemaVersion=1&orgId=1)

**Comment by aoiasd** [comment]
Sealed segment can't release because some querynode restart and channel balance cause segment checker filter remove release task till next task loaded. But this instance can't load next target till this invalid segment released because memory lack. Cause a deadlock.

**Comment by aoiasd** [comment]
Will fixed bu @weiliu1031

**Comment by aoiasd** [comment]
Reproduce the first OMM.
Close indexnode after collection create index, and then insert 3M data(dim 128 with partition key)  and flush every 10W data.
Then search with high concurrency and add timeout limit make sure most of them will timeout.
Will get that querynode suddenly OOM even though data only use 3GB memory and pod has 32GB memory.
![image](https://github.com/milvus-io/milvus/assets/45024769/85ce6dbf-3623-43db-be12-3005a4ce5318)
![image](https://github.com/milvus-io/milvus/assets/45024769/54a18646-2b56-464d-8332-95749e3ed063)

**Comment by xiaofan-luan** [comment]
> Reproduce the first OMM. Close indexnode after collection create index, and then insert 3M data(dim 128 with partition key) and flush every 10W data. Then search with high concurrency(100 concurrency and 20nq) and add timeout limit make sure most of them will timeout. Will get that querynode suddenly OOM even though data only use 3GB memory and pod has 32GB memory. ![image](https://private-user-images.githubusercontent.com/45024769/312785734-85ce6dbf-3623-43db-be12-3005a4ce5318.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNTI1NzYsIm5iZiI6MTcxMjI1MjI3NiwicGF0aCI6Ii80NTAyNDc2OS8zMTI3ODU3MzQtODVjZTZkYmYtMzYyMy00M2RiLWJlMTItMzAwNWE0Y2U1MzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDE3Mzc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzZmIwYTA5MDE3NTVmNGIwZGNjYWU0YzMyMzMyZWJiMDgzZDQzNWE2YzhjOTZmZDRmYjA5Mjk2OTMyMGUxMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JnKnfFE3judpWdzwIlkN1tXaKqXkdnIqET6h5WIw0c0) ![image](https://private-user-images.githubusercontent.com/45024769/312786101-54a18646-2b56-464d-8332-95749e3ed063.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNTI1NzYsIm5iZiI6MTcxMjI1MjI3NiwicGF0aCI6Ii80NTAyNDc2OS8zMTI3ODYxMDEtNTRhMTg2NDYtMmI1Ni00NjRkLTgzMzItOTU3NDllM2VkMDYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDE3Mzc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiMjVlMGQ3YjlmOGVkYzIxMGQxMTc5YTAxNmI4MzVkMmY1ZDgwZjYzODgzM2NiNjA3MWU2ZTJmYWI1YTM2OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3S-yKL5GD25s-IQ05Ky-ke7Sph02kCSYZB1AauCt2eI)

That is becasue too many request in Queue right? 

We can not simply use one go routine for each request or wait in a call. There must be somewhere we didn't have enough concurrency control and queue memory control

**Comment by yanliang567** [comment]
@aoiasd @weiliu1031 so whats the latest news for this issue?

**Comment by xiaofan-luan** [comment]
> 重现第一个OMM。 集合创建索引后关闭indexnode，然后插入3M数据（带分区键的dim 128）并每10W数据flush一次。 然后使用高并发（100并发和20nq）搜索并添加超时限制，确保大多数都会超时。 即使数据仅使用 3GB 内存而 pod 有 32GB 内存，查询节点也会突然 OOM。 ![图像](https://private-user-images.githubusercontent.com/45024769/312785734-85ce6dbf-3623-43db-be12-3005a4ce5318.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODc0NjMsIm5iZiI6MTcxNjE4NzE2MywicGF0aCI6Ii80NTAyNDc2OS8zMTI3ODU3MzQtODVjZTZkYmYtMzYyMy00M2RiLWJlMTItMzAwNWE0Y2U1MzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA2MzkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMjA3MTg5MWYwODI2ZjA0Yzc4OTU1MDk4ODRiNTY0MTQ2OTY1ODQ0NzQyYzNkOGQ4YWYzNDM5YmFjZWU3NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NlwWAdEOEJeC229YV_dq4VRCbgrw3vBneNpqlhDLons) ![图像](https://private-user-images.githubusercontent.com/45024769/312786101-54a18646-2b56-464d-8332-95749e3ed063.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODc0NjMsIm5iZiI6MTcxNjE4NzE2MywicGF0aCI6Ii80NTAyNDc2OS8zMTI3ODYxMDEtNTRhMTg2NDYtMmI1Ni00NjRkLTgzMzItOTU3NDllM2VkMDYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA2MzkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxYzZkNzBjNWE5OWIxYzkwZmEzZGFiMWIzNGJhNTI5YmNiZGM3NWI1MjBjZDRlM2NkNTZkYzQ5NTk4NjY3Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jek-kknB_gjH0r0W-qmiWx4Nhi6Pigk9pSVSajccyc4)



> > Reproduce the first OMM. Close indexnode after collection create index, and then insert 3M data(dim 128 with partition key) and flush every 10W data. Then search with high concurrency(100 concurrency and 20nq) and add timeout limit make sure most of them will timeout. Will get that querynode suddenly OOM even though data only use 3GB memory and pod has 32GB memory. ![image](https://private-user-images.githubusercontent.com/45024769/312785734-85ce6dbf-3623-43db-be12-3005a4ce5318.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNTI1NzYsIm5iZiI6MTcxMjI1MjI3NiwicGF0aCI6Ii80NTAyNDc2OS8zMTI3ODU3MzQtODVjZTZkYmYtMzYyMy00M2RiLWJlMTItMzAwNWE0Y2U1MzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDE3Mzc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzZmIwYTA5MDE3NTVmNGIwZGNjYWU0YzMyMzMyZWJiMDgzZDQzNWE2YzhjOTZmZDRmYjA5Mjk2OTMyMGUxMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JnKnfFE3judpWdzwIlkN1tXaKqXkdnIqET6h5WIw0c0) ![image](https://private-user-images.githubusercontent.com/45024769/312786101-54a18646-2b56-464d-8332-95749e3ed063.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNTI1NzYsIm5iZiI6MTcxMjI1MjI3NiwicGF0aCI6Ii80NTAyNDc2OS8zMTI3ODYxMDEtNTRhMTg2NDYtMmI1Ni00NjRkLTgzMzItOTU3NDllM2VkMDYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDE3Mzc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiMjVlMGQ3YjlmOGVkYzIxMGQxMTc5YTAxNmI4MzVkMmY1ZDgwZjYzODgzM2NiNjA3MWU2ZTJmYWI1YTM2OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3S-yKL5GD25s-IQ05Ky-ke7Sph02kCSYZB1AauCt2eI)
> 
> That is becasue too many request in Queue right?
> 
> We can not simply use one go routine for each request or wait in a call. There must be somewhere we didn't have enough concurrency control and queue memory control

We need a fixed size queue to host all the request, otherwise all the request is in queue and milvus will for sure fall into out of memory

**Comment by ThreadDao** [comment]
image: milvus-io-2.4-eeba851-20240612
1. search succeeds after all queryNode (3 qn) restarted [argo: zong-chaos-cluster-24-issue](https://argo-workflows.zilliz.cc/archived-workflows/qa/09624759-bd11-42d4-a122-57a9714b3755?nodeId=zong-chaos-cluster-24-issue)
2. The problem of building a temporary index causing the queryNode to oom has not been reproduced [argo: zong-chaos-cluster-24-issue-2](https://argo-workflows.zilliz.cc/archived-workflows/qa/6439cf3d-da8b-49c9-ad4d-3ea93416f1bb?nodeId=zong-chaos-cluster-24-issue-2)
the num of sealed segment is increasing and there are no indexNode to building index. So qn need to build tmp index. However, the qn's memory did not surge to 32Gi
![image](https://github.com/milvus-io/milvus/assets/27288593/867ebd95-d32e-47a2-ac4d-9d1361651d5f)
![image](https://github.com/milvus-io/milvus/assets/27288593/8596e2c0-7809-4e70-a773-8b2804bd8242)
