### ISSUE TITLE
[Bug]:  unstable integration test case TestClearCompactionTask

### ISSUE THREAD

**Issue by weiliu1031** [milvus-io/milvus#31106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master 
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

unstable integration test
![image](https://github.com/milvus-io/milvus/assets/108661493/59e4db00-660c-4102-834f-bf11abb55a39)

failed job:
https://github.com/milvus-io/milvus/actions/runs/8168284702/job/22332486304?pr=31061

**Comment by weiliu1031** [comment]
https://github.com/milvus-io/milvus/actions/runs/8181831427/job/22373490444?pr=31084

**Comment by XuanYang-cn** [comment]
- [ ] Skip first, this test doesnt influshence correctness.
- [ ] Debug and fix it
