### ISSUE TITLE
[Bug]: When using the REST API /v1/vector/get, the ID value requires escaped quotes

### ISSUE THREAD

**Issue by benauriemma** [milvus-io/milvus#31189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.0
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): none - REST API
- OS(Ubuntu or CentOS): linux
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When using the /get endpoint with the REST API, I need to wrap the ID value in escaped double quotes for it to work.

This API request fails:

```
curl --request POST \
    --url 'http://localhost:19530/v1/vector/get' \
    --header 'Authorization: Bearer MY_TOKEN' \
    --header "accept: application/json" \
    --header "content-type: application/json" \
    --data '{
      "collectionName": "dd933572_de72_11ee_a950_8fdac8a91deb",
      "outputFields": ["chunkId", "content", "sourceId"],
     "id": "myChunkId"
    }'
```

And this one succeeds:

```
curl --request POST \
    --url 'http://localhost:19530/v1/vector/get' \
    --header 'Authorization: Bearer MY_TOKEN' \
    --header "accept: application/json" \
    --header "content-type: application/json" \
    --data '{
      "collectionName": "dd933572_de72_11ee_a950_8fdac8a91deb",
      "outputFields": ["chunkId", "content", "sourceId"],
     "id": "\"myChunkId\""
    }'
```

The docs make it look like it should be the other way around: https://milvus.io/api-reference/restful/v2.3.x/Vector%20Operations/get.md

### Expected Behavior

This API request should succeed:

```
curl --request POST \
    --url 'http://localhost:19530/v1/vector/get' \
    --header 'Authorization: Bearer MY_TOKEN' \
    --header "accept: application/json" \
    --header "content-type: application/json" \
    --data '{
      "collectionName": "dd933572_de72_11ee_a950_8fdac8a91deb",
      "outputFields": ["chunkId", "content", "sourceId"],
     "id": "myChunkId"
    }'
```

**Comment by benauriemma** [comment]
The /delete endpoint has the same issue

**Comment by PowderLi** [comment]
related to #30092
please use the latest version

**Comment by benauriemma** [comment]
@PowderLi - I see that in https://github.com/milvus-io/milvus/issues/30092 they had the same issue that I'm having, but there was not a resolution in that ticket.

The original reporter is using the same workaround I found (using escaped quotes), but this method is not what the docs say to do.

Additionally, it seems clear that the workaround is not the intended behavior, but rather a bug in the parsing logic.  Could this bug be addressed?

/assign @PowderLi

**Comment by PowderLi** [comment]
the same issue has been solved by PR [30217](https://github.com/milvus-io/milvus/pull/30217), please use the latest version of milvus
