### ISSUE TITLE
[Bug]: Deleting entities with MMAP doesn't work

### ISSUE THREAD

**Issue by pascucg** [milvus-io/milvus#31186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.10 and 2.3.11
- Deployment mode: cluster
- SDK version: pymilvus 2.3.6
```

### Current Behavior

When I load the data with MMAP and delete a list of records they still appear when I launch a query.

### Expected Behavior

This does not happen when I load the data without MMAP.

### Anything else?

It seems that when you load the data with MMAP the Data Nodes and Query Nodes do not reflect the deletions until you do a flush. I don't see it being efficient to have to perform a flush for each deletion.

**Comment by xiaofan-luan** [comment]
this has nothing to do with mmap.

@pascucg could you share you code to reproduce it?

**Comment by pascucg** [comment]
Thanks for the reply.

**I have this deployment in cluster:**
![Captura desde 2024-03-11 23-29-28](https://github.com/milvus-io/milvus/assets/163001308/a1f4797a-ff9d-4dcf-9b2e-de59e030b6bc)

**MMAP is enabled as indicated:**
https://milvus.io/docs/mmap.md

**Below I provide you code to reproduce it:**
`from pymilvus import connections, Collection, FieldSchema, DataType, CollectionSchema, utility
import time
import random

def create_collection(name, schema):    
    try:  
        collection = Collection(name=name, schema=schema, consistency_level="Strong", using='default')
        index_param = {
            'metric_type':'IP',
            'index_type':"HNSW",
            'params':{'M': 8, 'efConstruction': 64}
        }
        collection.create_index(field_name="embedding", index_params=index_param)
    except Exception as e:
        print("Error creating collection: " + str(e))

def get_schema_embeddings_collection():
    id_field = FieldSchema(name="id", dtype=DataType.VARCHAR, max_length=1024, is_primary=True)
    embedding_field = FieldSchema(name="embedding", dtype=DataType.FLOAT_VECTOR, dim=1536)
    id_client_field = FieldSchema(name="id_client", dtype=DataType.VARCHAR, max_length=1024)
    case_field = FieldSchema(name="case", dtype=DataType.VARCHAR, max_length=1024)
    text_field = FieldSchema(name="text", dtype=DataType.VARCHAR, max_length=5000)
    timestamp_field = FieldSchema(name="timestamp", dtype=DataType.VARCHAR, max_length=1024)
    filename_field = FieldSchema(name="filename", dtype=DataType.VARCHAR, max_length=1024)
    document_type_field = FieldSchema(name="document_type", dtype=DataType.VARCHAR, max_length=1024)
    index_chunk_field = FieldSchema(name="index_chunk", dtype=DataType.INT64, max_length=1024)
    page_number_field = FieldSchema(name="page_number", dtype=DataType.VARCHAR, max_length=1024)
    language_field = FieldSchema(name="language", dtype=DataType.VARCHAR, max_length=1024)
    schema = CollectionSchema(fields=[id_field, id_client_field, embedding_field, text_field, case_field, timestamp_field, filename_field, document_type_field, index_chunk_field, page_number_field, language_field], auto_id=False)
    return schema

def search_db(collection, expr, output_fields):
    search_query_embedding = 1536*[random.random()]
    result = collection.search(
            data=[search_query_embedding], 
            anns_field="embedding", 
            param={"metric_type": "IP"},
            limit=16384, 
            expr=expr,
            consistency_level="Strong",
            output_fields=output_fields
    )
    return result

connections.connect(
  alias="default", 
  host="localhost", 
  port="19532"
)
schema = get_schema_embeddings_collection()
collection_name = "test_mmap"
if not utility.has_collection(collection_name):
    schema = get_schema_embeddings_collection()
    create_collection(collection_name, schema)
collection = Collection(name=collection_name, schema=schema, consistency_level="Strong", using='default')
collection.load()

print("Insert data...")
n_inserts = 100
id_client = "1_1_1"
for i in range(n_inserts):
    timestamp = str(time.time()).replace(".", "")
    id_record = timestamp + "@" + str(random.randint(0, 10000000000))
    embedding = 1536*[random.random()]
    text = "This is an example text" 
    list_text = text.split(" ")
    random.shuffle(list_text)
    text = " ".join(list_text)
    case = str(random.randrange(100))
    filename_db = "document_test"
    document_type = "pdf"
    index_chunk = 0
    page_number = "[1,2,3]"
    language = "eng"
    collection.insert([[id_record], [id_client], [embedding], [text], [case], [timestamp], [filename_db], [document_type], [index_chunk], [page_number], [language]])
collection.flush()

print("Search data before deletes...")
id_client = "1_1_1"
output_fields = ["id"]
expr = "id_client == \"" + str(id_client) + "\""
result = search_db(collection, expr, output_fields)
list_ids = []
for hits in result:
    for hit in hits:
        list_ids.append(hit.entity.get("id"))
print(list_ids)

print("Delete data...")
res = collection.delete(expr=f'id in ' + str(list_ids))
print(res)

print("Reload collection...")
collection.release()
collection.load()

print("Search data after deletes...")
id_client = "1_1_1"
output_fields = ["id"]
expr = "id_client == \"" + str(id_client) + "\""
result = search_db(collection, expr, output_fields)
list_ids = []
for hits in result:
    for hit in hits:
        list_ids.append(hit.entity.get("id"))
print(list_ids)`

**The output of the code in my tests:**
Insert data...
Search data before deletes...
['17101974663488317@5178189314', '17101974705250168@5108809479', '17101974613107893@7827916338', '17101974625154371@71819602', '1710197467220631@6698510068', '17101974621884432@4351794461', '171019746513154@6959900753', '17101974656952503@4437624805', '17101974702948818@4588821916', '17101974680804038@1040730154', '17101974673274431@1117163688', '17101974603110776@7169891657', '17101974632736764@7880073662', '17101974693158216@3279993437', '17101974608575313@4429113751', '17101974668919475@695416616', '17101974698603992@2474474615', '1710197462294779@9403116284', '17101974638189218@2750073165', '171019746829722@5162007797', '17101974654737945@1203096104', '17101974690914235@3919068389', '1710197462730638@4078943782', '1710197470083063@6504698216', '17101974686292455@3884817518', '17101974649042375@6094836137', '17101974696427226@8001269927', '17101974684045002@215972696', '17101974676479306@4878260102', '17101974679699416@8180781099', '17101974653604228@6100506452', '17101974631675236@4552622494', '17101974617389607@5117900686', '1710197467110083@5853987845', '17101974667811685@2362376652', '1710197462074146@9853376523', '17101974615281246@8096064805', '171019746468778@6080514747', '17101974677548501@769244994', '17101974664565063@4572900463', '17101974637084124@8904123547', '17101974650215814@2580711747', '17101974597339354@3434447526', '17101974694224079@7272781095', '17101974681865017@1496659839', '17101974695340366@1541464442', '17101974628443737@1834501722', '17101974645736227@1336647925', '1710197470404382@4308691784', '17101974641416576@3007164623', '17101974678643456@7987518877', '17101974655817223@1806685493', '17101974630581925@8766608429', '17101974661295624@5006950352', '17101974640345032@8441506807', '17101974600959632@8795791768', '1710197470635401@5399298336', '17101974604245548@4063263684', '17101974670000308@1473334521', '17101974611858623@5057690657', '1710197465908652@3071914989', '17101974610746732@6373158495', '17101974658025086@2792450272', '17101974624039385@7990841013', '17101974662433202@4622711213', '17101974699715254@9559124110', '17101974635950632@1984464700', '17101974701882274@1680676385', '17101974665634713@2859975334', '17101974626226273@8456188202', '17101974639267638@2951100586', '17101974644631379@1976614835', '17101974619537747@2719446049', '17101974599786625@1825764571', '17101974643546119@8582540905', '17101974697513776@9631937686', '17101974687411149@7773669673', '17101974609636004@5384359318', '17101974674343212@6770102194', '17101974629503555@7920375277', '1710197461846516@3602571854', '17101974685145228@8212460175', '17101974605338256@7845105408', '17101974633793788@5795763120', '17101974602041943@6535794401', '17101974598572145@4882672232', '171019746667485@4986463710', '17101974616324415@4814135359', '1710197460640523@8257061703', '1710197464795996@5215175352', '1710197464248383@6363361042', '17101974614168787@8082930933', '1710197468968438@2222360775', '17101974688497899@8054453380', '17101974607471414@984459360', '17101974675420492@5434712738', '17101974660194628@7124133101', '17101974652409637@3966699077', '17101974634877849@4999275498', '17101974692041957@3514437750']
Delete data...
(insert count: 0, delete count: 100, upsert count: 0, timestamp: 0, success count: 0, err count: 0)
Reload collection...
Search data after deletes...
['17101974663488317@5178189314', '17101974705250168@5108809479', '17101974613107893@7827916338', '17101974625154371@71819602', '1710197467220631@6698510068', '17101974621884432@4351794461', '171019746513154@6959900753', '17101974656952503@4437624805', '17101974702948818@4588821916', '17101974680804038@1040730154', '17101974673274431@1117163688', '17101974603110776@7169891657', '17101974632736764@7880073662', '17101974693158216@3279993437', '17101974608575313@4429113751', '17101974668919475@695416616', '17101974698603992@2474474615', '1710197462294779@9403116284', '17101974638189218@2750073165', '171019746829722@5162007797', '17101974654737945@1203096104', '17101974690914235@3919068389', '1710197462730638@4078943782', '1710197470083063@6504698216', '17101974686292455@3884817518', '17101974649042375@6094836137', '17101974696427226@8001269927', '17101974684045002@215972696', '17101974676479306@4878260102', '17101974679699416@8180781099', '17101974653604228@6100506452', '17101974631675236@4552622494', '17101974617389607@5117900686', '1710197467110083@5853987845', '17101974667811685@2362376652', '1710197462074146@9853376523', '17101974615281246@8096064805', '171019746468778@6080514747', '17101974677548501@769244994', '17101974664565063@4572900463', '17101974637084124@8904123547', '17101974650215814@2580711747', '17101974694224079@7272781095', '17101974681865017@1496659839', '17101974695340366@1541464442', '17101974628443737@1834501722', '17101974645736227@1336647925', '1710197470404382@4308691784', '17101974641416576@3007164623', '17101974678643456@7987518877', '17101974655817223@1806685493', '17101974630581925@8766608429', '17101974661295624@5006950352', '17101974640345032@8441506807', '17101974600959632@8795791768', '1710197470635401@5399298336', '17101974604245548@4063263684', '17101974670000308@1473334521', '17101974611858623@5057690657', '1710197465908652@3071914989', '17101974610746732@6373158495', '17101974658025086@2792450272', '17101974624039385@7990841013', '17101974662433202@4622711213', '17101974699715254@9559124110', '17101974635950632@1984464700', '17101974701882274@1680676385', '17101974665634713@2859975334', '17101974626226273@8456188202', '17101974639267638@2951100586', '17101974644631379@1976614835', '17101974619537747@2719446049', '17101974599786625@1825764571', '17101974643546119@8582540905', '17101974697513776@9631937686', '17101974687411149@7773669673', '17101974609636004@5384359318', '17101974674343212@6770102194', '17101974629503555@7920375277', '1710197461846516@3602571854', '17101974685145228@8212460175', '17101974605338256@7845105408', '17101974633793788@5795763120', '17101974602041943@6535794401', '171019746667485@4986463710', '17101974616324415@4814135359', '1710197460640523@8257061703', '1710197464795996@5215175352', '1710197464248383@6363361042', '17101974614168787@8082930933', '1710197468968438@2222360775', '17101974688497899@8054453380', '17101974607471414@984459360', '17101974675420492@5434712738', '17101974660194628@7124133101', '17101974652409637@3966699077', '17101974634877849@4999275498', '17101974692041957@3514437750']

**Comment by yanliang567** [comment]
@pascucg sounds like a dup to #30957, we are trying to fix it.
/assign @sunby 
/unassign

**Comment by sunby** [comment]
I've found the problem and am working on it

**Comment by sunby** [comment]
already fixed in https://github.com/milvus-io/milvus/pull/30848, @yanliang567

**Comment by yanliang567** [comment]
@elstic  i think we have verified the fix. Please help to confirm

/assign @elstic
