### ISSUE TITLE
[Bug]: While insert a very first record getting error as "	 ERROR:pymilvus.decorators:RPC error: [insert_rows], <ParamError: (code=1, message=Collection field dim is 1536, but entities field dim is 1536)>"

### ISSUE THREAD

**Issue by MonikaVijayakumar25** [milvus-io/milvus#31233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.1
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

After created and connected db, I have tried to insert a record via api. But the very first record is not getting inserted. Instead, It throws an error as "	
ERROR:pymilvus.decorators:RPC error: [insert_rows], <ParamError: (code=1, message=Collection field dim is 1536, but entities field dim is 1536)>, <Time:{'RPC start': '2024-03-13 10:15:23.340554', 'RPC error': '2024-03-13 10:15:23.341174'}>
"

After the first record error, I tried to insert again with same data, now the record has inserted successfully. I couldn't recreate that issue with same Milvus. Only the very first record insert has the issue. I have tried it in two separate Milvus installation.

### Expected Behavior

If the data is valid, then the insert on very first should works successfully. 

### Steps To Reproduce

```markdown
First install Milvus standalone, and Create database. Then, create collection and insert record. the issue happens only on first time.
```

**Comment by xiaofan-luan** [comment]
@MonikaVijayakumar25 
could you try latest 2.3.12?

**Comment by yanliang567** [comment]
@MonikaVijayakumar25 I tried to reproduce it on milvus 2.3.11 but no luck. If it reproduced to you on milvus 2.3.11, please help to collect and attach the milvus logs here?
Refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs 
For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.

/assign @MonikaVijayakumar25

**Comment by yanliang567** [comment]
> Facing same issue,
> 
> Using Milvus Cluster SDK pymilvus==2.3.6
> 
> Error log:
> 
> RPC error: [batch_insert], <ParamError: (code=1, message=Collection field dim is 384, but entities field dim is 768)>, <Time:{'RPC start': '2024-03-14 15:53:27.264280', 'RPC error': '2024-03-14 15:53:27.264280'}> Failed to insert batch starting at entity: 0/1

what is your milvus version, could you please collect the logs as suggested above
