### ISSUE TITLE
[Bug]: helm upgrade milvus, service cant't restart automatically

### ISSUE THREAD

**Issue by yunurs** [milvus-io/milvus#31234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

helm upgrade csmonitor-release zilliztech/milvus  -f values_yf_test.yaml --namespace monitor-test
i upgrade milvus by helm from v2.3.3 to v2.3.10 , but only attu service restart  automatically，other service cant`t restart automatically

### Expected Behavior

eg:  helm upgrade csmonitor-release zilliztech/milvus  -f values_yf_test.yaml --namespace monitor-test
i upgrade milvus by helm from v2.3.3 to v2.3.10 , but only attu service restart  automatically，other service cant`t restart automatically

**Comment by yanliang567** [comment]
@yunurs I think you should attach more info and logs for investigation. @LoveEachDay  any ideas?

/assign @LoveEachDay 
/unassign
