### ISSUE TITLE
[Bug]: Code error

### ISSUE THREAD

**Issue by weiZhenkun** [milvus-io/milvus#31243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

https://github.com/milvus-io/milvus/blame/master/pkg/util/distance/calc_distance.go#L57-L58

**Comment by chasingegg** [comment]
Thanks for alerting! This is a stupid mistake, I will fix it. 
Currently this piece of code is not used in milvus, but will be used in the future. See #30633 
/assign
