### ISSUE TITLE
[Bug]: RESTful API, the parameter 'params.nprobe' in the search operation is invalid

### ISSUE THREAD

**Issue by hanchikang** [milvus-io/milvus#31276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.3.3
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 0
- Others:
```

### Current Behavior

Anticipated：
![image](https://github.com/milvus-io/milvus/assets/20742865/6e7fd0e7-035d-40de-9834-94907c520fd3)

Actual:
![image](https://github.com/milvus-io/milvus/assets/20742865/b71f5587-722e-4a06-b977-7411d3dad1d9)

missing this parameter
![image](https://github.com/milvus-io/milvus/assets/20742865/21e93016-a024-4e05-a651-fa9f246e8bc3)

**Comment by yanliang567** [comment]
@PowderLi any updates?

**Comment by PowderLi** [comment]
I believe that `nprobe` is out-of-date

**Comment by hanchikang** [comment]
Is RESTful API going to be deprecated?

**Comment by yanliang567** [comment]
> I believe that `nprobe` is out-of-date

what do you mean it is out of date?

**Comment by yanliang567** [comment]
> Is RESTful API going to be deprecated?

No
