### ISSUE TITLE
Can Mishards support multi write-only Milvus node? 

### ISSUE THREAD

**Issue by meton-robean** [milvus-io/milvus#3131]
As I know, Mishards solution only allows one write-only milvus node. Howerver, if most operations in my task are vector insertions, one write-only milvus node cannot meet my need. Is there any cluster solution suggestion for this case ?

**Comment by tinkerlin** [comment]
We have no plans to support multi-node insertion at this time. Here is a special solution to build a milvus cluster without mishards, and insert data into different nodes according to their collection name.

**Comment by yhmo** [comment]
milvus v2.0 support multi write nodes.
