### ISSUE TITLE
[Bug]: GetCompactionPlansResults is not handled

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#31352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

<img width="1075" alt="image" src="https://github.com/milvus-io/milvus/assets/83447078/60059f1a-f013-446c-8dc2-632b6f45f295">

we don't handle rpc error when we check compaction result from datanode.
And this compaction job will be marked as failure from datacoord(while datanode may still running it), and some weird behaviour can hapen.

Fix:
1. only if node session expired can we mark the task as failure
2. if connect to datanode fails, we just skip this round

**Comment by yanliang567** [comment]
@xiaofan-luan is it ready to close?
