### ISSUE TITLE
Low QPS for multi-collections concurrency

### ISSUE THREAD

**Issue by xwqb** [milvus-io/milvus#3138]
**Describe the bug**
Create four sets A, B, C, and D in Milvus
1: Use Jemeter performance test tool to start A thread group with 50 threads per thread group, specify query A set, start pressure test, 50 requests per second to access A set concurrently, 1 vector condition, QPS is about 230
2: Create 4 thread groups, each thread group has 12 concurrent threads, and each thread group corresponds to a set, the total number of threads is 48, simultaneously query the data of 4 sets randomly, then QPS of each thread group drops to about 30

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
CentOS 7.5 
 Intel(R) Xeon(R) CPU E5-4650 v3 @ 2.10GHz *2 
GeForce RTX 2080 *2
128GB memory

- Method of installation (Docker, or from source)
Client: Docker Engine - Community
 Version:           19.03.4

- Milvus version 0.8.0-0.10.1
- Milvus configuration
Mysql metadat set，indes is  IVF_SQ8H，memery set 64GB ,wal set is false

**Screenshots**
![image](https://user-images.githubusercontent.com/11797392/89388289-66230b80-d736-11ea-8278-5b7baef08868.png)
![image](https://user-images.githubusercontent.com/11797392/89388313-6cb18300-d736-11ea-883c-de4a012f1c83.png)
**Additional context**

**Comment by yhmo** [comment]
Link to #2648 Optimize search combine strategy

**Comment by shengjun1985** [comment]
This is a duplicate issue.
And we will improve the performance of the case in the future.
Thank you for your concern and support for our project.
