### ISSUE TITLE
[Bug]: query node still retry fetch segment that already removed

### ISSUE THREAD

**Issue by rh01** [milvus-io/milvus#31382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.12
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):  kafka  
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.6
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 128/1T
- GPU: no
- Others:
```

### Current Behavior

After successfully using the birdwatcher tool to delete the specified missing segment, I mainly removed the corresponding objects in etcd and minio. However, I found that querynode was still trying to fetch the deleted segment. I suspect there might be a buffer inside querynode causing this issue. Therefore, I reloaded all components of the cluster, and everything returned to normal. I am not certain if this is a bug.

Behavior before delete segment, I cannot load collection.

<img width="702" alt="image" src="https://github.com/milvus-io/milvus/assets/10126374/209edee9-136f-4efd-aaf9-664e5630c644">

### Expected Behavior

I hope that after removing the segment, the query node will no longer attempt to fetch the corresponding segment.

**Comment by yanliang567** [comment]
I think this is by design as you birdwatcher is a tool for debugging and maintenance. Milvus keeps all meta in etcd so when you restart the cluster, it refresh the meta. 

/assign @congqixia 
please help to correct me 

/assign @rh01

**Comment by rh01** [comment]
Sure, I understand. Thank you very much.
