### ISSUE TITLE
[Bug]: Non-reproducible index creation

### ISSUE THREAD

**Issue by sinanus** [milvus-io/milvus#31412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.10
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): default    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.6
- OS(Ubuntu or CentOS): Mac & Ubuntu
- CPU/Memory: Mac: Intel i9 2.4GHz 8-core | Ubuntu: AMD Ryzen 9 7900X 12-core
- GPU: Mac: N/A | Ubuntu: RTX 3090 
- Others:
```

### Current Behavior

Binary IVF indices built using identical vectors and index parameters appear to not be identical when number of vectors in the index pass a certain (device and setting dependent) threshold. I suspect this because search results using identical vectors on two indices that should be identically built starts once you pass the threshold.

For example, on my 2019 MBP, results start to differ at around 1.6 million vectors when CollectionSchema has 2 varchar fields (in addition to the vector field) and around 1.9 million vectors when CollectionSchema has 1 varchar field. On my Ubuntu desktop, the results start to differ at 2.7 million vectors and 4.5 million vectors respectively.

### Expected Behavior

I expect that milvus BIN_IVF indices are reproducible / deterministic in their creation regardless of indexed vector count and regardless of CollectionSchema

### Steps To Reproduce

```markdown
Specifically what I do is this:
1) Create some 2 million binary vectors
2) Create a collection in standalone docker version of milvus (BIN_IVF, JACCARD, nlist 100, nprobe 5, topk 3)
3) Insert 1.7 million of the vectors into the collection and flush
4) Search the remaining 300k vectors' top 3 most similar vectors in the index
5) Save results and drop collection
6) Repeat steps 2-5 
7) Compare saved results and observe that they are not identical (on my MBP)

Since the reproduction of this issue depends on settings and device, I have created a repo for anyone to run tests with varying index sizes and settings to reproduce this on their own device: 

https://github.com/sinanus/milvus_index_reproducibility
```

**Comment by xiaofan-luan** [comment]
How large is the difference? 
Vector index is not 100% accurate. Usually what we do is not compare between each run, but calculate the ground truth and check the recall of each search. 90% accuracy or more is expected.

Also, you should check about the search params you use. Under most cases, I would recommend to have nlist to 4096, nprobe to be 128 or 256

**Comment by sinanus** [comment]
`How large is the difference?`
Not clear what you mean here. What I do see is that the topk (set to 3) results returned are sometimes completely different for two searches against identically built indices. In other words, I see `search(index1, vecQ) -> [vecA, vecB, vecC]` and `search(index2, vecQ) -> [vecD, vecE, vecF]`. And as I state above, this only starts to happen after you pass a certain threshold of index size and that threshold is device and schema dependent.

`Vector index is not 100% accurate. Usually what we do is not compare between each run, but calculate the ground truth and check the recall of each search. 90% accuracy or more is expected.`
I am not testing for accuracy here, I am testing for reproducibility. For my actual use case, reproducibility is important for auditability and re-creatability of results.

Also, I though milvus was using FAISS for IVF and FAISS developers says that except for a few exceptions, indices built with same data and parameters are bit exact see [here](https://github.com/facebookresearch/faiss/issues/983) and [here](https://github.com/facebookresearch/faiss/wiki/FAQ#reproducibility) as the random seeds are set. Perhaps this is not done in milvus?

**Comment by xiaofan-luan** [comment]
> `How large is the difference?` Not clear what you mean here. What I do see is that the topk (set to 3) results returned are sometimes completely different for two searches against identically built indices. In other words, I see `search(index1, vecQ) -> [vecA, vecB, vecC]` and `search(index2, vecQ) -> [vecD, vecE, vecF]`. And as I state above, this only starts to happen after you pass a certain threshold of index size and that threshold is device and schema dependent.
> 
> `Vector index is not 100% accurate. Usually what we do is not compare between each run, but calculate the ground truth and check the recall of each search. 90% accuracy or more is expected.` I am not testing for accuracy here, I am testing for reproducibility. For my actual use case, reproducibility is important for auditability and re-creatability of results.
> 
> Also, I though milvus was using FAISS for IVF and FAISS developers says that except for a few exceptions, indices built with same data and parameters are bit exact see [here](https://github.com/facebookresearch/faiss/issues/983) and [here](https://github.com/facebookresearch/faiss/wiki/FAQ#reproducibility) as the random seeds are set. Perhaps this is not done in milvus?

Not same at all seems to be weird. each

Could you change the script to NPROBE 32 and see what happens? NPROBE=5 is usually too small especiaally when your data is randomly generated, which means data is distribued evenly in a high demenional space(On other world, clustering might not work)

**Comment by xiaofan-luan** [comment]
I did go through the test code very carefully. If you are using random dataset thought you might need to store it somewhere or use the same the seed.

**Comment by sinanus** [comment]
Thanks for going through  the code. That function is there but is not being used (one of the function I copy pasted from the example in milvus).

I actually generate the data set once [here](https://github.com/sinanus/milvus_index_reproducibility/blob/73a9cb71d95597b1f7106b41b9686036327160d3/run_repeated_tests.py#L211) and insert them with [this function](https://github.com/sinanus/milvus_index_reproducibility/blob/73a9cb71d95597b1f7106b41b9686036327160d3/run_repeated_tests.py#L143) [here](https://github.com/sinanus/milvus_index_reproducibility/blob/73a9cb71d95597b1f7106b41b9686036327160d3/run_repeated_tests.py#L287)

**Comment by xiaofan-luan** [comment]
make sense.
The test code looks good to me overall.
1. try to increase NProbe number to 64 see that happens.
2. plot the distance of the result you get, see they are very close or not

**Comment by xiaofan-luan** [comment]
I'm still doubting about each time all three vectors will be different.
use BIN_FLAT could help on the verification. It is 100% accurate, so you should be reproduce your result any way

**Comment by yanliang567** [comment]
/assign @liliu-z 
please keep an eye on this issue.

**Comment by sinanus** [comment]
Hi all, did some more tests. Found a few things:

1. With BIN_IVF_FLAT settings nlist = nprobe = 1000, I still get different results between rebuilt indices. (see [here](https://github.com/sinanus/milvus_index_reproducibility?tab=readme-ov-file#sample-results-with-nlist--nprobe--1000))
2. With BIN_FLAT I still get non-reproducible indices, though now the delta is only ~97-98% of searches. That said, I now get occasional differences between searches on the same index. (see [here](https://github.com/sinanus/milvus_index_reproducibility?tab=readme-ov-file#bin_flat-also-can-be-non-reproducible))
3. Somehow BIN_IVF_FLAT with nlist = nprobe is 10x faster than the BIN_FLAT with same number of vectors. While I would expected it to be slightly slower.

I will now transition to try to reproduce my results on FAISS directly. Will report back here with my findings.

**Comment by xiaofan-luan** [comment]
> Hi all, did some more tests. Found a few things:
> 
> 1. With BIN_IVF_FLAT settings nlist = nprobe = 1000, I still get different results between rebuilt indices. (see [here](https://github.com/sinanus/milvus_index_reproducibility?tab=readme-ov-file#sample-results-with-nlist--nprobe--1000))
> 2. With BIN_FLAT I still get non-reproducible indices, though now the delta is only ~97-98% of searches. That said, I now get occasional differences between searches on the same index. (see [here](https://github.com/sinanus/milvus_index_reproducibility?tab=readme-ov-file#bin_flat-also-can-be-non-reproducible))
> 
> > 3. Somehow BIN_IVF_FLAT with nlist = nprobe is 10x faster than the BIN_FLAT with same number of vectors. While I would expected it to be slightly slower.
> 
> Above 3. point was due to a bug not setting nprobe properly. I fixed that and now timing makes. Test for point 1 above was repeated and got similar results. Point 2 also still stands as there is no nprobe settings in BIN_FLAT. I will update my repo soon.
> 
> I will now transition to try to reproduce my results on FAISS directly. Will report back here with my findings: DONE FAISS returns same results. In fact, I can save the indices to file and the saved indices have identical hashes.

1. @liliu-z please invesitgate on that, this could be a bug I guess
2. So you have saying faiss has similar issues? could this because so the vector simply have the same distance?

**Comment by liliu-z** [comment]
There are two reasons might affect the reproducibility:
1. **Compaction**: Milvus will create segments/indexes to serve search ASAP. But small segments/indexes are not efficient, so it will asynchronously rebuild bigger segments/indexes and do replacement once they are ready. So if we are in different stage of compaction, the result varies.
2. **Algorithm Randomness**: IVF indexes cannot ensure absolutely reproducible since it introduces some randomness in its index building. 
3. **Results' Order**: If the scores/distances for two results candidates are the same (we use float32 for distances, so can only ensure accuracy in 7 decimal digits), Milvus cannot ensure the ordering of results will not change.

So, in your cases, 
1. When we do normal tests, the problem can be because of the combination of reason 1 & 2
2. When we set `nprobe==nlist==1000` or use `FLAT` directly, the non-reproducibility can caused by reason 3. You can take a check of the distance to verify this hypothesis.

**Comment by xiaofan-luan** [comment]
and we just make this clarification that 
nprobe = nlist doen't mean KNN search

**Comment by liliu-z** [comment]
> > There are two reasons might affect the reproducibility:
> > 
> > 1. **Compaction**: Milvus will create segments/indexes to serve search ASAP. But small segments/indexes are not efficient, so it will asynchronously rebuild bigger segments/indexes and do replacement once they are ready. So if we are in different stage of compaction, the result varies.
> > 2. **Algorithm Randomness**: IVF indexes cannot ensure absolutely reproducible since it introduces some randomness in its index building.
> > 3. **Results' Order**: If the scores/distances for two results candidates are the same (we use float32 for distances, so can only ensure accuracy in 7 decimal digits), Milvus cannot ensure the ordering of results will not change.
> > 
> > So, in your cases,
> > 
> > 1. When we do normal tests, the problem can be because of the combination of reason 1 & 2
> > 2. When we set `nprobe==nlist==1000` or use `FLAT` directly, the non-reproducibility can caused by reason 3. You can take a check of the distance to verify this hypothesis.
> 
> 1. we don't have interim index on flat index, right?
> 2. there seems to be a necessity to tune interim accuracy

1. Yes, so it can be the reason 3
2. It is tunable, since it is an internal solution, so we put the config in `milvus.yaml`: `queryNode:segcore:interimIndex`.

**Comment by sinanus** [comment]
Alright got some time to do more tests. Here are a couple of observations and questions:

On FAISS used with the python bindings, I always get reproducible results. Namely repeated search and repeated built indices always yield identical results, tested up to 1e7 vector indices.

On  Milvus BIN_FLAT indices:
- The non-reproducibility is explainable by the Results' Order as predicted by [liliu-z](https://github.com/liliu-z). I can tell this as the difference between distances of the topK returned entities is always zero for all searches (see columns called `Repeat_search_on_SAME_index MAE_distance_max` which is always 0 [see [here](https://github.com/sinanus/milvus_index_reproducibility/blob/main/README.md#bin_flat-also-can-be-non-reproducible)]) even if the vector identifiers are not identical. 
In other words: 
if search(vec1, indexX) = [(vecA,dA), (vecB, dB), (vecC, dC)]
and  search(vec2, indexY) = [(vecD,dD), (vecE, dE), (vecF, dF)]
I always get dA=dB & dB=dE & dC=dF
- Hamming distance metric has more of this issue than Jaccard. For example while Jaccard is ~95-97% reproducible, Hamming is ~83-87%. This is off since I would have expected them to be the same. 

On Milvus BIN_IVF_FLAT indices:
-- When nprobe = nlist: 
- Like BIN_FLAT, even if the ids returened by search is not the same, the distances are. Thus the non-reproducibility can be attributed to Milvus not ensuring the order of index entities that have the same distance score to query vector.
-- When nprobe = 5, nlist = 1000:
- Results' Order does not fully explain the difference. The difference between distances of the topK returned entities is not always zero. 
In other words: 
if search(vec1, indexX) = [(vecA,dA), (vecB, dB), (vecC, dC)]
and  search(vec2, indexY) = [(vecD,dD), (vecE, dE), (vecF, dF)]
I sometimes get dA!=dB & dB!=dE & dC!=dF
- Disabling `interimIndex` in milvus.yaml doesn't impact the results

Questions:
1. I know  [liliu-z](https://github.com/liliu-z) said `Milvus cannot ensure the ordering of results will not change` but given that (I think) there is ~3.5% chance of two vectors in the index having the same distances to a randomly generated query vector (Assuming all index vectors are also randomly generated), wouldn't it make sense for milvus to be able to guarantee the ordering of the results are identical?
2. Given that FAISS can guarantee the above and that Milvus does return same order items when index is below a certain threshold size, is there a setting in Milvus that would allow us to get a reproducible results order?

**Comment by xiaofan-luan** [comment]
> Alright got some time to do more tests. Here are a couple of observations and questions:
> 
> On FAISS used with the python bindings, I always get reproducible results. Namely repeated search and repeated built indices always yield identical results, tested up to 1e7 vector indices.
> 
> On Milvus BIN_FLAT indices:
> 
> * The non-reproducibility is explainable by the Results' Order as predicted by [liliu-z](https://github.com/liliu-z). I can tell this as the difference between distances of the topK returned entities is always zero for all searches (see columns called `Repeat_search_on_SAME_index MAE_distance_max` which is always 0 [see [here](https://github.com/sinanus/milvus_index_reproducibility/blob/main/README.md#bin_flat-also-can-be-non-reproducible)]) even if the vector identifiers are not identical.
>   In other words:
>   if search(vec1, indexX) = [(vecA,dA), (vecB, dB), (vecC, dC)]
>   and  search(vec2, indexY) = [(vecD,dD), (vecE, dE), (vecF, dF)]
>   I always get dA=dB & dB=dE & dC=dF
> * Hamming distance metric has more of this issue than Jaccard. For example while Jaccard is ~95-97% reproducible, Hamming is ~83-87%. This is off since I would have expected them to be the same.
> 
> On Milvus BIN_IVF_FLAT indices: -- When nprobe = nlist:
> 
> * Like BIN_FLAT, even if the ids returened by search is not the same, the distances are. Thus the non-reproducibility can be attributed to Milvus not ensuring the order of index entities that have the same distance score to query vector.
>   -- When nprobe = 5, nlist = 1000:
> * Results' Order does not fully explain the difference. The difference between distances of the topK returned entities is not always zero.
>   In other words:
>   if search(vec1, indexX) = [(vecA,dA), (vecB, dB), (vecC, dC)]
>   and  search(vec2, indexY) = [(vecD,dD), (vecE, dE), (vecF, dF)]
>   I sometimes get dA!=dB & dB!=dE & dC!=dF
> * Disabling `interimIndex` in milvus.yaml doesn't impact the results
> 
> Questions:
> 
> 1. I know  [liliu-z](https://github.com/liliu-z) said `Milvus cannot ensure the ordering of results will not change` but given that (I think) there is ~3.5% chance of two vectors in the index having the same distances to a randomly generated query vector (Assuming all index vectors are also randomly generated), wouldn't it make sense for milvus to be able to guarantee the ordering of the results are identical?
> 2. Given that FAISS can guarantee the above and that Milvus does return same order items when index is below a certain threshold size, is there a setting in Milvus that would allow us to get a reproducible results order?

but what's the meaning of main this order?
1.  this also related to the insertion order of all the vectors, in a production environment no one really know the insertion order most of the time. 
2. if 3.5% of this vectors has the same distance, you might need to think of if the embedding do have semantic meaning or not. I strongly recommend you to test with real world dataset rather than random generated dataset.

To conclude, unless there are many people hit this issue in production, I will mark this as no fix. If there are more clues, the easy fix is to sort all result by distance then by id if distance is equal.

Anyone interested please offer more clues

**Comment by sinanus** [comment]
`but what's the meaning of main this order?
`
The important thing for me is the ability of audit certain results by reproducing the index and search results exactly. Guaranteeing the order of results with same distance score is one aspect of this (but it is not the sole issue here).

I have been able to do this (namely bit exact recreation of index and search results)  in FAISS python by keeping track of last index training time, which vectors were used for the IVF index training, and which vectors were inserted post training.

The way I was planing to do this in Milvus was similarly to keep track which vectors (and their primary keys) have been inserted into the Milvus index. My assumption was that if the vector and primary key are the same, and they are inserted in same order, I would end up with the same index. I can then rebuild the index  whenever I need it and re-play any search events exactly as they happened. My tests described above show that this is in fact possible up until a threshold (which I just found is related to segment max size, see end of this comment). 

Now please note my tests also show that , **Index building aside**, even with the **same index** I sometimes get different search results (meaning different vectors/entities with different distances to the query vector are returned by the search)
For example, first search yields:
search(vecQ, indexA) = {‘vecA’:dA, ‘vecB’:dB, ‘vecC’:dC} 
and then a second search sometime yields
search(vecQ, indexA) = {‘vecD’:dD, ‘vecE’:dE, ‘vecF’:dF}  
where dA!=dD, dB!=dE, dC!=dF. 
This is really perplexing, as **ordering of entities with equal distance scores does not explain this difference between searches**. This is an issue regardless of test data being randomly generated or “real world dataset” with semantic meaning (more on that below). 

`1. this also related to the insertion order of all the vectors, in a production environment no one really know the insertion order most of the time.`

This, I understand (as segments will fill and get sealed based on arrival time of vectors), however there are ways to keep track of the arrival/insertion time of things into the database. In fact, I thought Milvus does this automatically with timestamps. Is that not the case?

`
2.if 3.5% of this vectors has the same distance, you might need to think of if the embedding do have semantic meaning or not. I strongly recommend you to test with real world dataset rather than random generated dataset.
`
The reason I have created this issue and spent the time to investigate it is precisely because I have bumped into this non-reproducibility in real world datasets with embeddings that have “semantic meaning”. The random generated dataset is so that I can create a repo for anyone to re-create this issue on their own system (as I can’t share my company’s datasets). 

`To conclude, unless there are many people hit this issue in production, I will mark this as no fix. If there are more clues, the easy fix is to sort all result by distance then by id if distance is equal.
Anyone interested please offer more clues
`
I do not think the “easy fix” you suggest is that easy to implement if one does bulk vector searches (like I do) as it would require doing a topK search then a range search for each query vector (or risk querying a very large range of vectors). More importantly though, it would only fix the ordering issue but not the issue described above with different distance score results returned for the same index and query vector with BIN_IVF_FLAT and nprobe <<nlist.

With all of the above said, here is one more clue:
The threshold entity size (# of vector after search results start to differ) depends on the `dataCoord.segment.maxSize` value. When I increase it from the default 512(MB) to 1024 (MB), the threshold moves from ~3.6 million vectors to ~5.3 million vectors. Similarly when I decrease the value to 128(MB) the threshold modes down to ~1.6 million vectors. 
This suggests that the inconsistency is in how the results from multiple segments is joined together.
