### ISSUE TITLE
[Bug]: [bulk insert v2]when there are a lot of tasks, the datanode will consume a significant amount of memory

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#31432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master/2.4
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/12268675/bb875d9f-0ad5-48bd-bb44-2c10b79a0492)

There are 1000 tasks, each consisting of several tens of rows of data (small files, large volume of tasks). The total increase in memory peak is around 5 GB

**Comment by bigsheeper** [comment]
Memory usage appears to be normal in my test. commitID: 7f201e80 @zhuwenxing 
![image](https://github.com/milvus-io/milvus/assets/42060877/493ed50f-91bd-4164-917c-477e37d95c0f)
![image](https://github.com/milvus-io/milvus/assets/42060877/c65b34d9-48b7-4771-9306-ccbf004aee07)

**Comment by zhuwenxing** [comment]
when only do import, no index and load. memory and cup usage is stable and a reasonable value.

![image](https://github.com/milvus-io/milvus/assets/12268675/33dac76d-0dd1-454e-bf0c-396c872b9257)
