### ISSUE TITLE
[Bug]: Can not get vectors during search/query after copying local storage

### ISSUE THREAD

**Issue by evgeniikrikunov-pr3vision** [milvus-io/milvus#31444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.9, 2.3.12
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.6, 2.3.7
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 20cores/32GB RAM/500GB nvmessd
- GPU: 
- Others:
```

### Current Behavior

Hi!

I want to generate a vector database on one machine (machine 1) and then copy it to another machine (machine 2) to use only as search engine. After copying I faced the problem where i can not extract vectors on both machines during search/query.

The error message:
`RPC error: [search], <MilvusException: (code=65535, message=failed to search/query delegator 4 for channel by-dev-rootcoord-dml_0_448470277133174978v0: fail to Query, QueryNode ID = 4, reason=worker(4) query failed: invalid local pat[h:/var/lib/milvus/data/insert_log/448470277133174978/448470277133174979/448470277133381283/101/448470277133381305](file:///H:/var/lib/milvus/data/insert_log/448470277133174978/448470277133174979/448470277133381283/101/448470277133381305))>, <Time:{'RPC start': '2024-03-20 08:28:06.561899', 'RPC error': '2024-03-20 08:28:07.635699'}>`

More precise scenario:
All files are in my [gdrive](https://drive.google.com/drive/folders/1hhHM7NWWndkt_AJ2sj9TjD9vZpmFXiOZ?usp=sharing)

On machine 1:
1. Firstly i started standalone_embed.sh script to run docker container:
`bash standalone_embed.sh start`
The only thing that i changed is volume paths.
2. I successfully builded the database with 16kk vectors (dim=768) and metadata for them (see generate_db.py).
3. Later i checked search/query functions, **it works as expected** (see check.py).

On machine 2:
1. I copied the local storage from machine 1 to machine 2 using scp. On machine 2 i run the same standalone_embed.sh script with changed volume paths for this machine. But for some reason i could not find database name in db.list_database() (there was only "default"). 
2. I checked #15860 and #22300. Ok, i forgot to stop container before scp. I returned to machine 1, stopped container.
3. From machine 2 I tried to scp one more time but error ".../volumes/milvus/etcd: permission denied" appeared.
4. So in machine 1 I decided to "sudo chmod -R 777 .../volumes" and tried scp from machine 2 again.
5. After this on machine 2 i run standalone_embed.sh script. Now i can connect to database. But when i perform search/query like in example above, i faced the reported error.
6. Moreover, i faced the same error on machine 1, now.

!!! This error disappears if i remove field "embedding" from output_fields. I mean i still can do correct search/query but without outputing vectors ... Looks like the problem appeared when i started procedures on machine 2, but which step ... 

Could you please give some advises:
1. What about this error?
2. How can i return an access to my vectors?
3. What is the proper way to transfer data from one machine to another? Can i just copy (not like me) or i need to use something like milvus_backup?
4. Do i need to do collection.release() before stopping container?

### Expected Behavior

I am able to extract vectors during search/query in both machines.

**Comment by LoveEachDay** [comment]
@evgeniikrikunov-pr3vision You'd better use `milvus-backup` tool to create a backup then restore to another milvus instance instead.

To help diagnose your problem, could use [birdwatcher](https://github.com/milvus-io/birdwatcher) to create a backup?

**Comment by yanliang567** [comment]
/assign @evgeniikrikunov-pr3vision 
copy files between milvus cluster is not recommended, actually it is not tested. please use backup tool as suggested above.

**Comment by xiaofan-luan** [comment]
if you need to copy data:
stop your entire service.
copy both S3, Etcd and rocksdb.

That should work.
or use backup is an easier way

**Comment by evgeniikrikunov-pr3vision** [comment]
Thank you for answers!
I tried to perform generation and search only on machine 2. Everything works fine during last week.
I think we can close this issue.

I will try to use proper tools for copy in the future.
