### ISSUE TITLE
[Bug]: Collection not loading

### ISSUE THREAD

**Issue by SemJeunen** [milvus-io/milvus#31458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.3.9
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): RocksMQ 
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.6
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 2048mb
- GPU: N/A
- Others: I am running this on a VM for developing
```

### Current Behavior

When I do 
collection= Collection(self.collection_name)
collection.load()

The collection keeps loading without an end

### Expected Behavior

When I do 
collection= Collection(self.collection_name)
collection.load()

It should load quickly and allow my application to resume

### Anything else?

I am trying to build a chatbot with a RAG workflow. I am using milvus as the vectorstore. I used to be able to load my collection but right now it doesn't seem to want to load. I thought it might be a issue with my code since I had to rewrite it but I ran into the same issue in my previous versions. I am pretty new to vector stores so I don't know how to fix this.

**Comment by SimFG** [comment]
@SemJeunen you should create index for the collection, and then load it. A base example reference: https://github.com/milvus-io/pymilvus/blob/master/examples/hello_milvus.py
Hope the example can help you.

**Comment by SemJeunen** [comment]
@SimFG Normally I have created the index already so I checked by executing collection.indexes. I got this as a result so I don't think this is the issue: [<pymilvus.orm.index.Index object at 0x0000022FBBFBBF50>]. Anyway thank you for trying to help me out

**Comment by SimFG** [comment]
@SemJeunen you can use the `utility.loading_progress` or `utility.load_state` api to get the collection load status.

**Comment by yanliang567** [comment]
@SemJeunen Could you please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.

/assign @SemJeunen

**Comment by SemJeunen** [comment]
[milvuslog.txt](https://github.com/milvus-io/milvus/files/14742246/milvuslog.txt)
This is the docker log file.

**Comment by SemJeunen** [comment]
Ok so I just made a whole new clean VM and it seems to have gone away. No idea what caused it tho. Thanks for the help

**Comment by yanliang567** [comment]
i'd close the issue as comments above.  please free to file new issues if any problems
