### ISSUE TITLE
[Enhancement]: Sparse index support for mmap 

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#31485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Please support the index of sparse for mmap. 

### Why is this needed?

You cannot use a sparse index with mmap.

**Comment by zhengbuqian** [comment]
/assign @zhengbuqian 

Adding mmap support for sparse index should be done in knowhere, not Milvus. We need mmap for sparse raw data in Milvus.

Both are included in GA todo items, which I'll share more details next week. This is not part of 2.4.0.

**Comment by zhengbuqian** [comment]
Also I will track all GA items for sparse vector in #29419, including mmap, please close this if you don't mind @elstic

**Comment by elstic** [comment]
> Also I will track all GA items for sparse vector in #29419, including mmap, please close this if you don't mind @elstic

ok
