### ISSUE TITLE
[BUG] milvus build fail when set "FAISS_URL"

### ISSUE THREAD

**Issue by cydrain** [milvus-io/milvus#315]
**Describe the bug**
When set "FAISS_URL", build process error out with message:
InvertedLists.cpp:18:10: fatal error: cuda.h: No such file or directory
 #include "cuda.h"

**Steps/Code to reproduce behavior**
1. export FAISS_URL='http://192.168.1.105:6060/jinhai/faiss/-/archive/branch-0.3.0/faiss-branch-0.3.0.tar.gz'
2. run "build.sh" under "milvus/core"

**Expected behavior**
no error expected

**Environment details**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Comment by youny626** [comment]
There's no FAISS_URL anymore. To compile with your own FAISS library, add `-f` option when running build.sh:
```
-f: FAISS root path(default: empty). The path should be an absolute path
    containing the pre-installed lib/ and include/ directory of FAISS. If they can't be found,
    we will build the original FAISS from source instead.
```
If you compile with CMake directly, pass `-DFAISS_ROOT=...`
