### ISSUE TITLE
[Bug]: [bulk insert v2]bf16 and f16 vector datatype are  still not supported 

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#31512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master/2.4
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

bf16 and f16 vector datatype are  still not supported

**Comment by zhuwenxing** [comment]
/assign @cqy123456 

please implement it before 2.4 GA

**Comment by cydrain** [comment]
Plan to support bf16 and fp16 in May

**Comment by zhuwenxing** [comment]
@yhmo 

Milvus already supports f16 and bf16 for bulk insert. does the bulk writer support it?
