### ISSUE TITLE
[Bug]: CPU usage is high with huge collection numbers same as #26157

### ISSUE THREAD

**Issue by Seven2Nine** [milvus-io/milvus#31514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.5
- Deployment mode(standalone or cluster): standalone 
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu 
- CPU/Memory: 4vCPUs 16G--aws t3.xlarge
- GPU: 
- Others:
```

### Current Behavior

1500 collections
each collection 100 entities.

**CPU usage > 70% when idle.**
![image](https://github.com/milvus-io/milvus/assets/61679388/c92ee2a1-d950-48d9-abd5-8f232ec6168d)

### Expected Behavior

[https://github.com/milvus-io/milvus/issues/26157](url)

**Comment by yanliang567** [comment]
please retry on latest milvus v2.3.12, which improved a lot for the scenarios of multi collections @Seven2Nine 
/assign @Seven2Nine 
/unassign

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version: 2.3.5
> - Deployment mode(standalone or cluster): standalone 
> - MQ type(rocksmq, pulsar or kafka): rocksmq
> - SDK version(e.g. pymilvus v2.0.0rc2):
> - OS(Ubuntu or CentOS): Ubuntu 
> - CPU/Memory: 4vCPUs 16G--aws t3.xlarge
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> 1500 collections each collection 100 entities.
> 
> **CPU usage > 70% when idle.** ![image](https://private-user-images.githubusercontent.com/61679388/315892298-c92ee2a1-d950-48d9-abd5-8f232ec6168d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNTE1ODksIm5iZiI6MTcxMTE1MTI4OSwicGF0aCI6Ii82MTY3OTM4OC8zMTU4OTIyOTgtYzkyZWUyYTEtZDk1MC00OGQ5LWFiZDUtOGYyMzJlYzYxNjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDIzNDgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwN2E4YWFmMDUyZTViZTZjN2Q2ZTQ1MDJmZDJkZWU4ZGIzNTExNTRmYWEwM2I2NjlhOGYwYTMzZWM4MDRjNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kV2W59QELKsKoC58yEp2EldueSk7NrhZvalZbeNHYAo)
> 
> ### Expected Behavior
> [https://github.com/milvus-io/milvus/issues/26157](url)
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

Did you have pprof for datacoord? 
how many segments/partititons are there in each collection on avg?

**Comment by xiaofan-luan** [comment]
@yanliang567 
is this still a problem in 2.4?
