### ISSUE TITLE
[Bug]: Query return deleted data when upsert with varchar pk and partitionKey.

### ISSUE THREAD

**Issue by aoiasd** [milvus-io/milvus#31548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.12

- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior
Create collection with schema
```
        [
            pm.FieldSchema(name="pk", dtype=pm.DataType.VARCHAR, description="str", is_primary=True, max_length= 128),
            pm.FieldSchema(name="embeddings", dtype=pm.DataType.FLOAT_VECTOR, dim=8),
            pm.FieldSchema(name="int64", dtype=pm.DataType.INT64, is_partition_key=True),
            pm.FieldSchema(name="version", dtype=pm.DataType.INT64),
        ]
```

Upsert 600M entities with version == 1, int64 field was sequence start from 0.
Flush()
Upsert 200M entities with version == 2(pk and int64 same with first 200M of 600M entities )

Query(version==1 && int64 <200M) find length of result >0.

### Expected Behavior
Return with [].

_No response_

**Comment by xiaofan-luan** [comment]
could you give more detailed reason of why this could happen?
