### ISSUE TITLE
[Bug]: return self._meta_info[self.model_name]["dim"] KeyError: 'dim'

### ISSUE THREAD

**Issue by CyanMystery** [milvus-io/milvus#31556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
pymilvus                      2.4.0
milvus-model                  0.1.0
torch                         2.1.0+cu121
```

### Current Behavior

 File "lib\site-packages\milvus_model\hybrid\bge_m3.py", line 82, in _encode
    sparse_dim = self.dim["sparse"]
  File "lib\site-packages\milvus_model\hybrid\bge_m3.py", line 74, in dim
    return self._meta_info[self.model_name]["dim"]
KeyError: 'dim'

### Steps To Reproduce

```markdown
bge_m3_ef = BGEM3EmbeddingFunction(
        model_name=embed_path,  # use Local bge-m3
        device='cuda:0',  # Specify the device to use, e.g., 'cpu' or 'cuda:0'
        use_fp16=True  # Whether to use fp16. `False` for `device='cpu'`.
    )

bge_m3_ef(doc_list)
```

**Comment by wxywb** [comment]
It is due to you used a local file path to indicate you want to use your local bge-m3, I will avoid hard coding this in a newer version(I expect it will be bge/m3 and stored in your default directory maintained by huggingface).

**Comment by wxywb** [comment]
> /assign @wxyucs /unassign

please assign this to me.

**Comment by wxywb** [comment]
@CyanMystery  now milvus-model v0.2.0 fixed this, please have a try.
