### ISSUE TITLE
[Bug]: Load a very large collection, the memory suddenly drops!

### ISSUE THREAD

**Issue by rh01** [milvus-io/milvus#31589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 1.24.0-rc1
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.6
- OS(Ubuntu or CentOS):  CentOS
- CPU/Memory: 256/2T
- GPU: No
- Others:
```

### Current Behavior

When I load a very large collection, the memory suddenly drops, causing subsequent loads to report insufficient available memory, but we have ample cluster resources, so this is unlikely to happen. and we didn't perform any release operations on the cluster.

![image](https://github.com/milvus-io/milvus/assets/10126374/da5d4b83-99c5-4b0a-a6c0-7874b19e1e42)

![image](https://github.com/milvus-io/milvus/assets/10126374/30c67057-b7c7-4478-bee1-87a8dadc4f28)

![image](https://github.com/milvus-io/milvus/assets/10126374/1ca78a48-20e5-4aae-8376-6a527624bda9)

Do we have any issues with memory allocation? The memory of our Milvus cluster suddenly dropped, and the program couldn't load the data even though there's no problem with the allocated memory. This can only be resolved by restarting the component.

### Milvus Log

[logs.tar.gz](https://github.com/milvus-io/milvus/files/14742260/logs.tar.gz)

**Comment by yanliang567** [comment]
@rh01 As the error msg says, your total memory is ~131072MB, and the thresholdFactor is 0.9, so the maximum memory milvus can use for loading collection is 117964.8, which is larger than your collection index size. 
please try to add more memory for the querynodes

/assign @rh01 
/unassign

**Comment by rh01** [comment]
Memory thresholds of the single query node?

**Comment by xiaofan-luan** [comment]
@rh01 
How many data do you have? 

I think under your case, it's reasonable to change memory threshold to 0.95 to host more data. 0.9 is more like for smaller querynodes.

but you do need to calculate on how many data you have and what's the potential memory requirement.

I'd like to offer help if necessary (xiaofan.luan@zilliz.com)

Also we'd like to know about the loading time on such a larger dataset and see how things could be improved
