### ISSUE TITLE
[Bug]: No etcd Connection with Docker-Compose Standalone

### ISSUE THREAD

**Issue by hno2** [milvus-io/milvus#31590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:milvus:v2.4.0-rc.1-gpu
- Deployment mode(standalone or cluster):standalone/docker-compose
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): Not Relevant
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory:  AMD Ryzen Threadripper PRO 7975WX 32-Cores/256GB
- GPU: 4090 via nvidia-docker
- Others:
```

### Current Behavior

When starting milvus standalone via the released [milvus-standalone-docker-compose-gpu.yml](https://github.com/milvus-io/milvus/releases/download/v2.4.0-rc.1/milvus-standalone-docker-compose-gpu.yml), the milvus-standalone container crashes after a couple of minutes due to a failing etcd connection. 
Full log attached below, the standalone throws several errors of `
```
milvus-standalone  | {"level":"warn","ts":"2024-03-25T09:40:56.830Z","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0015b2fc0/etcd:2379","attempt":0,"error":"rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR"}
```
The etcd container can be pinged from the standalone container, and the etcd service is up and running and values can be put via `etcdctl`.

### Expected Behavior

The docker-compose file should just work out of the box with no configuration.

### Steps To Reproduce

```markdown
1. Download the docker-compose of the latest release
2. Run it via `docker compose up`
3. etcd and minio work with healty healthcheck, milvus standalone crashed after a couple of minutes due to no connection to etcd.
```

### Milvus Log

[log.txt](https://github.com/milvus-io/milvus/files/14742449/log.txt)

**Comment by yanliang567** [comment]
/assign @Presburger 
please help to take a look
/unassign

**Comment by jdgiddings** [comment]
Having this exact issue, too. Any luck?

**Comment by yanliang567** [comment]
> Having this exact issue, too. Any luck?

this issue is about rc and we have already release v2.4.3, please retry. If it reproduced to you, feel free to file a new issue and offer error, logs and configs for investigations.
