### ISSUE TITLE
[Bug]: Compaction failed: segment with flushed state not found: segment not found after upgrading image from 2.3.12 to 2.4

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#31648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.3.12-> 2.4-20240320-7f201e80-amd64
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):  kafka  
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.4.0rc53
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. deploy milvus standalone with v2.3.12
```
f-upgrade-stand-6-milvus-standalone-5c956cb6d8-gbs9g     Running     0            1m      10.104.13.97      4am-node16     
f-upgrade-stand-6-etcd-0                                 Running     0            2m      10.104.30.104     4am-node38     
f-upgrade-stand-6-kafka-0                                Running     0            2m      10.104.30.106     4am-node38     
f-upgrade-stand-6-kafka-1                                Running     0            2m      10.104.24.124     4am-node29     
f-upgrade-stand-6-kafka-2                                Running     1            2m      10.104.15.252     4am-node20     
f-upgrade-stand-6-kafka-zookeeper-0                      Running     0            2m      10.104.30.105     4am-node38     
f-upgrade-stand-6-kafka-zookeeper-1                      Running     0            2m      10.104.24.123     4am-node29     
f-upgrade-stand-6-kafka-zookeeper-2                      Running     0            2m      10.104.33.10      4am-node36     
f-upgrade-stand-6-minio-5b984c894c-55dmp                 Running     0            2m      10.104.30.107     4am-node38  
```
2. run test:
create collection -> index and load -> insert 20m -> flush -> index and load -> concurrent: upsert + flush + search
3. upgrading milvus image from v2.3.12 to 2.4-20240320-7f201e80-amd64 while doing concurrent tests
4. after test finished, the mixCompaction seems to be continuing, but the number of flushed-L1 is not reduced
![image](https://github.com/milvus-io/milvus/assets/27288593/4e2063b8-e51c-4e70-b842-941cfdc49702)

### Steps To Reproduce

```markdown
- argo workflow: https://argo-workflows.zilliz.cc/archived-workflows/qa/c130c824-35a1-4154-9b2d-3300f946740e?nodeId=fouramf-rolling-upgrade-all-stand-6

- grafana:[metrics of f-upgrade-stand-6](https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=P1809F7CD0C75ACF3&var-cluster=&var-namespace=qa-milvus&var-instance=f-upgrade-stand-6&var-collection=All&var-app_name=milvus&from=1711510065554&to=1711529131154)
```

### Milvus Log

pods after upgrading:
```
f-upgrade-stand-6-etcd-0                                          1/1     Running                           0               5h19m   10.104.30.104   4am-node38   <none>           <none>
f-upgrade-stand-6-kafka-0                                         1/1     Running                           0               5h19m   10.104.30.106   4am-node38   <none>           <none>
f-upgrade-stand-6-kafka-1                                         1/1     Running                           0               5h19m   10.104.24.124   4am-node29   <none>           <none>
f-upgrade-stand-6-kafka-2                                         1/1     Running                           1 (5h18m ago)   5h19m   10.104.15.252   4am-node20   <none>           <none>
f-upgrade-stand-6-kafka-zookeeper-0                               1/1     Running                           0               5h19m   10.104.30.105   4am-node38   <none>           <none>
f-upgrade-stand-6-kafka-zookeeper-1                               1/1     Running                           0               5h19m   10.104.24.123   4am-node29   <none>           <none>
f-upgrade-stand-6-kafka-zookeeper-2                               1/1     Running                           0               5h19m   10.104.33.10    4am-node36   <none>           <none>
f-upgrade-stand-6-milvus-standalone-5455ccc6cf-47qtm              1/1     Running                           0               3h14m   10.104.13.152   4am-node16   <none>           <none>
f-upgrade-stand-6-minio-5b984c894c-55dmp                          1/1     Running                           0               5h19m   10.104.30.107   4am-node38   <none>           <none>
```
- [part compaction WARN logs](https://grafana-4am.zilliz.cc/explore?panes=%7B%22Qa9%22:%7B%22datasource%22:%22vhI6Vw67k%22,%22queries%22:%5B%7B%22refId%22:%22E%22,%22expr%22:%22%7Bcluster%3D%5C%224am%5C%22,%20namespace%3D%5C%22qa-milvus%5C%22,%20pod%3D~%5C%22f-upgrade-stand-6-milvus-standalone-5455ccc6cf-47qtm%5C%22%7D%20%7C%3D%20%5C%22WARN%5C%22%20%7C%3D%20%5C%22compact%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22vhI6Vw67k%22%7D,%22editorMode%22:%22code%22,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%221711518754940%22,%22to%22:%221711523381567%22%7D%7D%7D&schemaVersion=1&orgId=1)
![image](https://github.com/milvus-io/milvus/assets/27288593/253c5333-448a-49e3-8e1a-78de89fddf9e)

**Comment by ThreadDao** [comment]
birdwatcher shows:
![image](https://github.com/milvus-io/milvus/assets/27288593/3a6e47df-f38b-4473-8bd8-5c8d77392877)

**Comment by XuanYang-cn** [comment]
![image](https://github.com/milvus-io/milvus/assets/51370125/1c0a164a-c678-4755-8b39-120263a04d3c)

**Comment by XuanYang-cn** [comment]
/assign @ThreadDao
Please help verify it

**Comment by ThreadDao** [comment]
@XuanYang-cn
maybe new issue: There are 4 L0-segment left that have not been compactioned
![image](https://github.com/milvus-io/milvus/assets/27288593/d24d5515-89be-4af2-85f6-5c8e501c2f0b)

- image: 2.3-20240330-47f767cf -> 2.4-20240402-5bfe26f4d-amd64
- argo:  [zong-rolling-upgrade-all-cdca-5bmkk](https://argo-workflows.zilliz.cc/archived-workflows/qa/6063cd0a-2fa7-4a1b-af02-ca1a449ce26c?nodeId=zong-rolling-upgrade-all-cdca-5bmkk)
- grafana: [metrics of zong-upgrade-3](https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=P1809F7CD0C75ACF3&var-cluster=&var-namespace=qa-milvus&var-instance=zong-upgrade-3&var-collection=All&var-app_name=milvus&from=1712024009683&to=1712058959285)

- birdwatcher:
```
Milvus(zong-upgrade-3) > show segment
SegmentID: 448797215869182927 State: Flushed, Level: L0, Row Count:0
SegmentID: 448797215869182928 State: Flushed, Level: L0, Row Count:0
SegmentID: 448797215869182959 State: Flushed, Level: L0, Row Count:0
SegmentID: 448797215869182960 State: Flushed, Level: L0, Row Count:0
SegmentID: 448797215869183371 State: Flushed, Level: L1, Row Count:2350143
SegmentID: 448797215869183449 State: Flushed, Level: L1, Row Count:1980513
SegmentID: 448797215869183515 State: Flushed, Level: L1, Row Count:641048
SegmentID: 448797215869183541 State: Flushed, Level: L1, Row Count:1471455
SegmentID: 448797215869183645 State: Flushed, Level: L1, Row Count:1648469
SegmentID: 448797215869183703 State: Flushed, Level: L1, Row Count:2009471
SegmentID: 448797862925785098 State: Growing, Level: L1, Row Count:1892
SegmentID: 448797862925785099 State: Growing, Level: L1, Row Count:1908
--- Growing: 2, Sealed: 0, Flushed: 10, Dropped: 0
--- Small Segments: 0, row count: 0	 Other Segments: 10, row count: 10101099
--- Total Segments: 12, row count: 10104899
```

**Comment by ThreadDao** [comment]
Same issue when upgrade config: disanle-L0 -> enable L0
- image: 2.4-20240402-8b8a5b4ac-amd64
- argo:  https://argo-workflows.zilliz.cc/archived-workflows/qa/a2d85be5-1146-49fb-bfa0-34f7ac88eb11?nodeId=zong-concurrent-upgrade-config-nfg
- grafana: [metrics of fouram-op-5-4755](https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=P1809F7CD0C75ACF3&var-cluster=&var-namespace=qa-milvus&var-instance=fouram-op-5-4755&var-collection=All&var-app_name=milvus&from=1712057204164&to=1712086349764)
![image](https://github.com/milvus-io/milvus/assets/27288593/ed6451f7-7734-4ff3-ad67-2a378ac99346)

**Comment by XuanYang-cn** [comment]
@ThreadDao L0 segments are left there by design. Because there're still 2 growing segments. The deletes in L0 segments should be applied to the growing segments, but L0 compaction can only operates on `Sealed Segments`, so no L0 Compaction will be triggered.

The L0 compaction condition: `all L0 segments with position <= earliest growing segments start position`

**Comment by XuanYang-cn** [comment]
Call flush at the end, and you will see the L0 segments turns into zero.
