### ISSUE TITLE
[Bug]: milvus standalone service exits unexceptedly abnormally and fails to start

### ISSUE THREAD

**Issue by 0215Arthur** [milvus-io/milvus#31657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.12
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.7
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory:  8Core /32GB
- GPU: -
- Others: docker-compose
```

### Current Behavior

I try to insert data into milvus data (~2M embeddings, insert batch size: 2000),
At the point where about 1.4M pieces of data have been inserted, the exception occurred: milvus exited, and I try to restart the milvus-standalone service, but it doesn't start properly (CPU usage gradually goes to 100%, then the milvus service exits abnormally).

<img width="1686" alt="image" src="https://github.com/milvus-io/milvus/assets/26346750/52c9ca8c-ac10-439d-a376-81b50d0239aa">

### Milvus Log

[milvus.log](https://github.com/milvus-io/milvus/files/14771966/milvus.log)

**Comment by yanliang567** [comment]
@0215Arthur  According to the logs, it seems that the milvus components failed to keep alive with etcd.  as a docker compose deployment, please make sure you are running on SSD volumes.
`milvus-standalone-prod-02  | [2024/03/27 10:14:41.350 +00:00] [WARN] [rootcoord/timeticksync.go:313] ["rootcoord send tt to all channels too slowly"] [chanNum=2] [span=263]
`

/assign @0215Arthur 
/unassign

**Comment by 0215Arthur** [comment]
> @0215Arthur According to the logs, it seems that the milvus components failed to keep alive with etcd. as a docker compose deployment, please make sure you are running on SSD volumes. `milvus-standalone-prod-02 | [2024/03/27 10:14:41.350 +00:00] [WARN] [rootcoord/timeticksync.go:313] ["rootcoord send tt to all channels too slowly"] [chanNum=2] [span=263] `
> 
> /assign @0215Arthur /unassign

Thank you very much for your reply. Very helpful. I'll keep an eye on the performance of the disk
