### ISSUE TITLE
[Bug]: Search Method Does Not Return Top-K Data

### ISSUE THREAD

**Issue by HantaoCai** [milvus-io/milvus#31658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Background
I am unable to retrieve relevant data using the `query` method.

### Parameters
The parameters used are as follows:
```json
{
  "data": [[-0.0072511225, -0.0066715847, 0.017841486, ...]],
  "anns_field": "vector",
  "param": {
    "metric_type": "IP",
    "params": {"ef": 215}
  },
  "limit": 5,
  "expr": "enable == true and ARRAY_CONTAINS_ANY(application, ['知识大脑'])",
  "output_fields": [
    "index_id",
    "application",
    "tags",
    "question_id",
    "question",
    "answer",
    "enable"
  ],
  "round_decimal": 4,
  "consistency_level": "Strong"
}
```
The `search_result` is empty: `[]`.

![query result](https://github.com/milvus-io/milvus/assets/44667064/fa4b42bf-9a82-4825-9e53-65d53eee864a)

Despite adjusting the `ef` value, I'm still unable to fetch any relevant data, and the return is empty. Why might this be happening? What additional information should I provide?

### Additional Context
In the latest version of the Attu client, it's not possible to manually input the Advanced Filter. The selection method does not support conditions like `ARRAY_CONTAINS_ANY(application, ['知识大脑'])`.

![Attu client issue](https://github.com/milvus-io/milvus/assets/44667064/6869a006-df45-4b0c-afe0-a6457e653d95)

Could you please assist me in understanding why I'm unable to retrieve the expected data and how I might be able to specify my complex query condition in the Attu client?

### Expected Behavior

Able to Return Top-K Results Even When Similarity Scores Are Very Low

**Comment by xiaofan-luan** [comment]
1. what milvus version you use? I'm assuming this won't happen on 2.3.12
2. How many datas you have? if you are trying to filter out from 1000w data but the result matches is only 100, this could happen because the graph connectivity is fully destroyed. We add special sauce is latest milvus and it could help 
3. If latest milvus still can not search out your result, can you kindly share your data set? we need to analysis on what's happening.
@liliu-z is ready to help.
@shanghaikid could you take care the attu issue?

**Comment by shanghaikid** [comment]
> 1. what milvus version you use? I'm assuming this won't happen on 2.3.12
> 2. How many datas you have? if you are trying to filter out from 1000w data but the result matches is only 100, this could happen because the graph connectivity is fully destroyed. We add special sauce is latest milvus and it could help
> 3. If latest milvus still can not search out your result, can you kindly share your data set? we need to analysis on what's happening.
>    @liliu-z is ready to help.
>    @shanghaikid could you take care the attu issue?

sure, I will add custom filter input in the search UI.

**Comment by HantaoCai** [comment]
I'm using Milvus 2.3.10. Has this issue been optimized in versions after this one? I'll try upgrading to see if that helps.

**Comment by HantaoCai** [comment]
I've upgraded to the latest version, which is currently 2.3.12, but the issue persists. 
I created a test case, and when I modify the 'ef' and 'limit' parameters, I get different results. 

<img width="1760" alt="image" src="https://github.com/milvus-io/milvus/assets/44667064/84b1bd2e-1451-42a3-ad4d-f0b066d47ede">
<img width="841" alt="image" src="https://github.com/milvus-io/milvus/assets/44667064/cb72314c-0fcb-4904-ad8b-abce8573ef84">

Why is this happening? In the production environment, I only need a limit of 5, and for 'ef' I've set it to 3*limit + 200, but this setup yields no results.
Please help me analyze the reasons why the 'limit' affects the results, and offer me some suggestions.

**Comment by HantaoCai** [comment]
My dataset consists of only about 3000 rows.

**Comment by liliu-z** [comment]
> I've upgraded to the latest version, which is currently 2.3.12, but the issue persists. I created a test case, and when I modify the 'ef' and 'limit' parameters, I get different results.
> 
> <img alt="image" width="1760" src="https://private-user-images.githubusercontent.com/44667064/318322402-84b1bd2e-1451-42a3-ad4d-f0b066d47ede.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NDY1MTgsIm5iZiI6MTcxMTk0NjIxOCwicGF0aCI6Ii80NDY2NzA2NC8zMTgzMjI0MDItODRiMWJkMmUtMTQ1MS00MmEzLWFkNGQtZjBiMDY2ZDQ3ZWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA0MzY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiN2EwNWNlMWNhNTQ2NTRjMjkwNzliOGI4OGVhMzhiYmJiZWIzOTNlOWYyOGRhYTJhODFmYzE5ZjFkM2UxNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L7O_otg6l6dFfbEszpYFQqcXpz6iCHQpsBnJO7JVNo0"> <img alt="image" width="841" src="https://private-user-images.githubusercontent.com/44667064/318322418-cb72314c-0fcb-4904-ad8b-abce8573ef84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NDY1MTgsIm5iZiI6MTcxMTk0NjIxOCwicGF0aCI6Ii80NDY2NzA2NC8zMTgzMjI0MTgtY2I3MjMxNGMtMGZjYi00OTA0LWFkOGItYWJjZTg1NzNlZjg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA0MzY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjN2NjMGU2NTk4ZjZmODM5OTRhY2VmODBlOWVhYTUxMjcyYzI3ODNiYmI3MzQwYTM4YzA1OGJkZmMzOWI2ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qWTrULks0OET8U481Hmge6yww_thJ7U7cxAFHoh-_qs">
> Why is this happening? In the production environment, I only need a limit of 5, and for 'ef' I've set it to 3*limit + 200, but this setup yields no results. Please help me analyze the reasons why the 'limit' affects the results, and offer me some suggestions.

Did you mean `ef = 2000 && limit = 100` didn't yield any results but `ef = 2000 && limit = 500` did?
If so:
1. Can I have more infos like, how many results you get.
2. Any chance you can provide this test dataset so we can help investigate on it.

Thanks

**Comment by HantaoCai** [comment]
1. When I set the limit to 500, it returned the correct 500 results. However, when I set it to 100, it didn't find any data.
2. I'll try to organize a sanitized dataset to reproduce this issue.

**Comment by xiaofan-luan** [comment]
> 1. When I set the limit to 500, it returned the correct 500 results. However, when I set it to 100, it didn't find any data.
> 2. I'll try to organize a sanitized dataset to reproduce this issue.

did you use different ef_search or same ef_search?

**Comment by HantaoCai** [comment]
I exported this data from the production environment to the development environment using a backup tool, and found that the same code can retrieve data. What could be the reason? Are the indexes corrupted? Does the data need to be reloaded? How should I check?

**Comment by liliu-z** [comment]
> I exported this data from the production environment to the development environment using a backup tool and found that the same code can retrieve data (ef = 215, limit = 5). What could be the reason? Is the index corrupted? Does the data need to be reloaded? How should I check?

A step-by-step reproducing instruction and the dataset can help us understand what happened.

**Comment by HantaoCai** [comment]
Let's re-examine the issue:
Here's my test code:
collection = await get_collection(collection_name)
    query = {
        "data": [[-0.0072511225, -0.0066715847, 0.017841486...]],
        "anns_field": "vector",
        "param": {"metric_type": "IP", "params": {"ef": 215}},
        "limit": 5,
        "expr": "enable == true and ARRAY_CONTAINS_ANY(application, ['Knowledge Brain'])",
        "round_decimal": 4,
        "consistency_level": "Strong",
    }
    await collection.load()
    result = await collection.search(**query, timeout=20)
My dataset only contains 3000 records, and currently, in the production environment, no results can be found - the returned result is empty.
However, when I modify the query to:
query = {
        "data": [[-0.0072511225, -0.0066715847, 0.017841486...]],
        "anns_field": "vector",
        "param": {"metric_type": "IP", "params": {"ef": 2000}},
        "limit": 500,
        "expr": "enable == true and ARRAY_CONTAINS_ANY(application, ['Knowledge Brain'])",
        "round_decimal": 4,
        "consistency_level": "Strong",
    }
It can correctly retrieve the top 500 records.
I attempted to submit this dataset of 3000 records as a problematic dataset, but when I import it from the production environment to the development environment and then use the original code
query = {
        "data": [[-0.0072511225, -0.0066715847, 0.017841486...]],
        "anns_field": "vector",
        "param": {"metric_type": "IP", "params": {"ef": 215}},
        "limit": 5,
        "expr": "enable == true and ARRAY_CONTAINS_ANY(application, ['Knowledge Brain'])",
        "round_decimal": 4,
        "consistency_level": "Strong",
    }
It correctly returns the top 5 results. What could be the reason for this phenomenon? Both my development and production environments have been upgraded to version 2.3.12, and calling this method does not produce any error logs. It looks as though the dataset contains no data.

**Comment by HantaoCai** [comment]
After several tests, I've noticed a potential issue with your query process: it seems that vector searches are performed first, followed by scalar field filtering.

When I removed my `expr`, I found that the data retrieved belonged to different applications, indicating that the vector search is executed prior to any scalar filtering. This leads to situations where, if my `limit` is set too low and combined with application filtering, no results are returned.

In my development environment, as the data volume increases, the top results retrieved by the `limit` query belong to different applications. Consequently, when scalar filtering is applied, it results in no data being returned. However, when my `limit` is sufficiently large, I'm able to filter out the relevant data.

I previously consulted with your technical team and was informed that scalar filtering occurs before the vector search. Could you please confirm this? There seems to be a discrepancy in my observations, where it appears that the vector search is performed first, followed by scalar filtering.

**Comment by xiaofan-luan** [comment]
we are doing pre filtierng,which means filtering happened before search.

try to use ef=2000 under topk =5 see if you can search the result

**Comment by HantaoCai** [comment]
set limit 5:
<img width="2367" alt="image" src="https://github.com/milvus-io/milvus/assets/44667064/ab843968-c47f-401b-8050-acae97f616e2">
<img width="1082" alt="image" src="https://github.com/milvus-io/milvus/assets/44667064/b938d06e-bea8-4586-8c7d-b951e9bc22fb">

set limit 500:
<img width="850" alt="image" src="https://github.com/milvus-io/milvus/assets/44667064/4461def1-6021-4eb6-8a77-8802ec5140a3">

**Comment by xiaofan-luan** [comment]
application is “知识大脑” or “天印知识大脑”

**Comment by HantaoCai** [comment]
You can simply think of them as the same.

**Comment by liliu-z** [comment]
> set limit 5: <img alt="image" width="2000" src="https://private-user-images.githubusercontent.com/44667064/318684238-6b9f96b2-6ce1-4ca3-b7d5-9bebb3764a55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNDM0NDYsIm5iZiI6MTcxMjA0MzE0NiwicGF0aCI6Ii80NDY2NzA2NC8zMTg2ODQyMzgtNmI5Zjk2YjItNmNlMS00Y2EzLWI3ZDUtOWJlYmIzNzY0YTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA3MzIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxYTU3MGI0YjQ1MzkyZWRlMmJlNzc5ZTNlMjVkZWQ3YmI2MDZkYTlmY2U2OTg4ZDYxNjgxNTMyYTdmMmVjMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zDZzPNR2DrSLVL-nun5smN3HZK9YZi-H1Dy4xcaoOro">
> 
> <img alt="image" width="1082" src="https://private-user-images.githubusercontent.com/44667064/318674183-b938d06e-bea8-4586-8c7d-b951e9bc22fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNDM0NDYsIm5iZiI6MTcxMjA0MzE0NiwicGF0aCI6Ii80NDY2NzA2NC8zMTg2NzQxODMtYjkzOGQwNmUtYmVhOC00NTg2LThjN2QtYjk1MWU5YmMyMmZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA3MzIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMjg1NGJhYTllZjk1YzVhNWQzODhmYmY1NjJmMDYwMjk2ZjFmMjQyYWJhMDVjYmQ3YTE4MDk1MTk2ZDRkZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r-9omuv5zO_VClj3Tu8iIHcinI3FZ0hfpKaxvVqNFw8">
> set limit 500: <img alt="image" width="1267" src="https://private-user-images.githubusercontent.com/44667064/318674801-ba42778f-9d53-426f-85b2-7cf1821653ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNDM0NDYsIm5iZiI6MTcxMjA0MzE0NiwicGF0aCI6Ii80NDY2NzA2NC8zMTg2NzQ4MDEtYmE0Mjc3OGYtOWQ1My00MjZmLTg1YjItN2NmMTgyMTY1M2NlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA3MzIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhZGExNDM3ZTQ1NjZjZDRlYzM3YTkwYTRjNjE3ZDcwMTZkYmE2MGUxMDVkMTFmZTk0MDEwNjI0OTE5M2I2MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ydWUs1QD9ZEjTqgzP48Wv9IqA9ld9hZ0cfRU6QXPqxc">

In your previous example, you used `limit = 5 && ef = 215` and `limit = 500 && ef = 2000`. Just want double check in this quoted example you used `limit = 5 && ef = 2000` and `limit = 500 && ef = 2000`?

**Comment by HantaoCai** [comment]
In my scenario, I only need the data of top5, so the parameters I initially set are topk =5 and ef =215, but I can't get the data, so I want to try to increase the topk to 500 because the ef needs to be larger than topk, so I can adjust it to top. K 500 ef 2000 It correctly obtained the data I wanted. Then I adjusted whether the topk is equal to 5 ef or 2000 knowledge in order to compare with the former. No data was obtained under this parameter. So judging from this phenomenon, I think you did a vector query first and then filtered the scalar from it. I don't know if I have explained it.

**Comment by liliu-z** [comment]
> In my scenario, I only need the data of top5, so the parameters I initially set are topk =5 and ef =215, but I can't get the data, so I want to try to increase the topk to 500 because the ef needs to be larger than topk, so I can adjust it to topK =500 and ef 2000. It correctly obtained the data I wanted. Then I adjusted whether the topk is equal to 5 and ef =2000 knowledge in order to compare with the former. No data was obtained under this parameter. So judging from this phenomenon, I think you did a vector query first and then filtered the scalar from it. I don't know if I have explained it.

Thanks for this explanation. We are adapting pre-filtering, and what exactly we do is pick `topk` elements out of the `ef` result candidates. So this case sounds definitely abnormal.

It will be helpful if you can provide these datasets.

My email: li.liu@zilliz.com Thanks a lot for your feedback!

**Comment by HantaoCai** [comment]
Has there been any new progress on this issue?

**Comment by hhy3** [comment]
@HantaoCai The problem is that the M parameter you set is 4, which is too small, so the graph quality is low. Some bigger value like 16 or 32 is better. The reason why set limit to 500 will find correct result is that milvus will use brute force if topk is large enough and will not use graph index.

**Comment by liliu-z** [comment]
Also, the high filtering rate make the graph quality even worse.

**Comment by xiaofan-luan** [comment]
> @HantaoCai The problem is that the M parameter you set is 4, which is too small, so the graph quality is low. Some bigger value like 16 or 32 is better. The reason why set limit to 500 will find correct result is that milvus will use brute force if topk is large enough and will not use graph index.

Thanks for the update! seems that M is very important on search qualities

**Comment by HantaoCai** [comment]
Okay, we will re-modify the parameters and rebuild the index. It is recommended to add this to the document.
