### ISSUE TITLE
[Bug]: Frequent Collection Loading Problem (stuck at 0% loading)

### ISSUE THREAD

**Issue by wissamAImahmoud** [milvus-io/milvus#31662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.3.11
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): PyMilvus version: 2.3.1
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: Intel(R) Xeon(R) w5-2465X / 128Gb
- GPU: 2x Nvidia A6000
- Others:
```

### Current Behavior

We've been encountering a recurrent issue with loading Milvus collections (especially large scale ones). First, we couldn't figure out what was going wrong, so we had to resort to a workaround – removing previous volumes and using the backup server to restore the data. However, this workaround isn't sustainable nor efficient, especially considering our data comprises over 14 million records.

Our initial investigations pointed towards the flush operation as a potential culprit, but subsequent debugging and searching efforts haven't yielded any viable solutions. Below, we've provided relevant logs for reference. Any assistance in resolving this issue would be greatly appreciated. If additional information is required, please don't hesitate to reach out. Thank you for your attention to this matter.
(Also attached is a picture of our attu dashboard, the collection that is not loading is wikipedia with collection_id: _447855772133235033_ )

![image](https://github.com/milvus-io/milvus/assets/145332220/6132b2bf-2074-4c51-a528-631d2289870c)

### Expected Behavior

The collection should load normally and be ready for search when calling `collection.load()` or triggering it from attu's interface.

### Milvus Log

[logs.txt](https://github.com/milvus-io/milvus/files/14773521/logs.txt)

**Comment by yanliang567** [comment]
/assign @weiliu1031 
```
boxMind       | [2024/03/26 10:02:53.654 +00:00] [ERROR] [retry/retry.go:46] ["retry func failed"] [traceID=6e48fd0cde210b40b8a81d05ac2201a7] ["retry time"=0] [error="channel not found[channel=by-dev-rootcoord-dml_0_447855772133235033v0]"] [stack="github.com/milvus-io/milvus/pkg/util/retry.Do\n\t/go/src/github.com/milvus-io/milvus/pkg/util/retry/retry.go:46\ngithub.com/milvus-io/milvus/internal/datacoord.
...
```
/unassign
