### ISSUE TITLE
[Bug]: milvus can create collections with illegal DataType fileds

### ISSUE THREAD

**Issue by xiaocai2333** [milvus-io/milvus#31696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

milvus can create collections with illegal DataType fileds.

### Expected Behavior

milvus can only create collections with legal DataType fileds.

**Comment by xiaocai2333** [comment]
/assign @yanliang567 
please add tests for it.

**Comment by yanliang567** [comment]
@xiaocai2333 what is the current result for this issue without the fix? milvus crash?

**Comment by xiaocai2333** [comment]
@yanliang567 The collection can be created successfully, but it will crash when loading.

**Comment by yanliang567** [comment]
ran the milvus 2.3 latest build with pymilvus 2.4, no crashing
