### ISSUE TITLE
[Bug]: [restful v2]error message is confusing when use wrong param to create index

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#31732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4-20240329-c9692b58-amd64
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2024-03-29 16:33:11 - DEBUG - ci_test]: 
method: post, 
url: http://10.104.31.16:19530/v2/vectordb/indexes/create, 
cost time: 0.04935812950134277, 
header: {'Content-Type': 'application/json', 'Authorization': 'Bearer root:Milvus', 'RequestId': 'fa1b6370-eda6-11ee-ade6-acde48001122'}, 
payload: {"collectionName": "test_collection_2024_03_29_16_33_03_907368NddBYEGB", "indexParams": [{"fieldName": "book_intro", "indexName": "book_intro_vector", "metricType": "L2", "indexConfig": {"indexType": "HNSW", "M": "16", "efConstruction": "200"}}], "dbName": "default"}, 
response: {"code":65535,"message":"only metric type can be passed when use AutoIndex"} (milvus.py:20)
```

The request failed because I wrote "index_type" as "indexType," but the error message did not explicitly point out this issue. Additionally, this error is incorrect as other index types can also be set with the metric type

**Comment by PowderLi** [comment]
Such requests using illegal parameter names can be constructed in many ways.
To remind users to use valid parameter names,
  it is not recommended to check on the server side.
  Instead, it is advised that users follow the specifications in the documentation when using the interface. 

> For example, the documentation could provide a prompt stating that if parameter "indexType" is missing, the default value(AutoIndex) will be used.
