### ISSUE TITLE
milvus1.1.2修改为milvus2.4编码错误？

### ISSUE THREAD

**Issue by goldwater668** [milvus-io/milvus#31749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://github.com/milvus-io/milvus/discussions/31748

### Steps To Reproduce

```markdown
https://github.com/milvus-io/milvus/discussions/31748
```

### Milvus Log

https://github.com/milvus-io/milvus/discussions/31748

### Anything else?

https://github.com/milvus-io/milvus/discussions/31748

**Comment by yanliang567** [comment]
not sure that is the error and expectation for this issue. please help to share more info, including milvus error and logs.
@goldwater668 

/assign @goldwater668 
/unassign
