### ISSUE TITLE
[Bug]: [Internal] PR #30454 possible QPS regression

### ISSUE THREAD

**Issue by alexanderguzhva** [milvus-io/milvus#31752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4 RC
- Related to PR #30454
```

### Current Behavior

PR #30454 improves the QPS for the search with i64 filtering, but decreases QPS for the search with varchar filtering 

### Expected Behavior

QPS should not go down

### Steps To Reproduce

```markdown
Internal VDBBench tests
```

**Comment by yanliang567** [comment]
/assign @alexanderguzhva 
I believe you already had PRs for it/
/unassign

**Comment by alexanderguzhva** [comment]
@yanliang567 yes, and I have even PRs more once the provided ones are accepted
