### ISSUE TITLE
[Enhancement]: Support GC control at Database/Collection Level

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#31763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Support GC control at Database/Collection Level

### Why is this needed?

It's needed to pause/resume at collection/database level from maintenance needs at those levels

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What would you like to be added?
> Support GC control at Database/Collection Level
> 
> ### Why is this needed?
> It's needed to pause/resume at collection/database level from maintenance needs at those levels
> 
> ### Anything else?
> _No response_

We should do that, but the problem is we are not order logs with colleciton

**Comment by xiaofan-luan** [comment]
let's hold this modifications. The gc process is already too complicated and introduced many troubles.

If there is no scan, our life will be much easier. Or if we can leave orphan files to 7 days, then we don't need to worry about the gc.
