### ISSUE TITLE
Milvus cluster deployment on AKS

### ISSUE THREAD

**Issue by manas007** [milvus-io/milvus#31818]
Followed the deployment guide here: https://milvus.io/docs/azure.md

kubectl get services 
Output:
<img width="328" alt="image" src="https://github.com/milvus-io/milvus/assets/19229097/744be3a1-1e36-4d45-a97b-c08055908151">

kubectl get pods -o wide
Output:

<img width="526" alt="image" src="https://github.com/milvus-io/milvus/assets/19229097/759c5a78-8dd8-4562-b808-6966caff7468">

Values.yaml 
![image](https://github.com/milvus-io/milvus/assets/19229097/a737cd71-d39e-4f4d-ada7-c7111fa43741)

when connecting to milvus using connection.connect and updated host and port number, running into the error
<MilvusException: (code=2, message=Fail connecting to server on XXXX. Timeout)>

_Originally posted by @manas007 in https://github.com/milvus-io/milvus/discussions/31722_

**Comment by xiaofan-luan** [comment]
did you config the externalS3?

externalS3:
  enabled: true
  host: core.windows.net
  port: 443
  rootPath: my-release
  bucketName: testmilvus # the storage account container name
  cloudProvider: azure
  useSSL: true
  accessKey: "milvustesting1" # the storage account name
  secretKey: "<secret-key>"

**Comment by manas007** [comment]
Yes,

see here : https://github.com/milvus-io/milvus/discussions/31722#discussioncomment-8954438

**Comment by xiaofan-luan** [comment]
could you get milvus logs?  using exportlog.sh could help.

**Comment by manas007** [comment]
> could you get milvus logs? using exportlog.sh could help.

where do i run this ? on the AKS cluster ?

**Comment by xiaofan-luan** [comment]
https://github.com/milvus-io/milvus/blob/db698756dc908f98ce884ef4b81ca2ad553c9905/deployments/export-log/README.md?plain=1#L33

**Comment by xiaofan-luan** [comment]
And if this is a serious production environment, I would recommend to deploy with logging and monitoring metrics

**Comment by xiaofan-luan** [comment]
https://milvus.io/docs/configure_grafana_loki.md

**Comment by xiaofan-luan** [comment]
<img width="919" alt="image" src="https://github.com/milvus-io/milvus/assets/83447078/4ffe4bdd-8b48-42a3-ae46-13c4bf15cb8e">
did you config for your azure storage?

**Comment by manas007** [comment]
yes

![image](https://github.com/milvus-io/milvus/assets/19229097/4a8a01bd-87dc-4070-a746-7f3554deddbc)

**Comment by xiaofan-luan** [comment]
did you enable ssl on object storage? 

Maybe you can debug by try to connect you Azure Storage with cli?

@zhagnlu I think we have a tool to verify object storage connection?

**Comment by zhagnlu** [comment]
@PowderLi  please help check this config for azure firstly.

**Comment by PowderLi** [comment]
please do follow commands to figure out why pod CrashLoopBackOff
```
kubectl describe ${pod}
kubectl logs ${pod} --all-containers
kubectl get events
kubectl get events --field-selector XXX
```
you can find more related information from [k8s_crashloopbackoff](https://cloud-atlas.readthedocs.io/zh-cn/latest/kubernetes/debug/k8s_crashloopbackoff.html)

**Comment by manas007** [comment]
@PowderLi 

kubectl describe pod proxy---
![image](https://github.com/milvus-io/milvus/assets/19229097/82ade1af-c230-4696-9c08-3556107ad2c7)


kubectl describe pod datacoord---
![image](https://github.com/milvus-io/milvus/assets/19229097/bd219489-081a-45e4-b060-8b133c290252)

**Comment by PowderLi** [comment]
I found a similar issue: [1 node(s) had untolerated taint #116133](https://github.com/kubernetes/kubernetes/issues/93533)

list the taint node, then try either
1. Tolerate the taint, i.e., add tolerations on the Pod
2. remove the taint from the single node

```
kubectl get nodes --selector=XX
kubectl describe node ${taint_node}
kubectl taint node ${taint_node}
```

**Comment by manas007** [comment]
@PowderLi 
Thanks, I tried it but it is still the same. 
should I delete the AKS and start with a new one ? I can do that since this is for testing purpose only. 

are there any other end-to-end deployment guides other than the one here : https://milvus.io/docs/azure.md ?

**Comment by magallardo** [comment]
One more update.  I was looking at the logs and found the following entry in the indexnode, 
datacoord, datanode containers:

LogMessage: panic: unsupported cloudProvider:azure


My values.yaml file has the following entry for externalS3 

externalS3:
  enabled: true
  host: core.windows.net
  port: 443
  rootPath: ds-milvus-release
  bucketName: milvuscontainer # the storage account container name
  cloudProvider: azure
  useSSL: true
  accessKey: "dsllmsa" # the storage account name
  secretKey: "****mykey******"

Thanks
Marcelo

**Comment by PowderLi** [comment]
I believe that the version of milvus must > v2.2.x refer to [milvus release notes](https://milvus.io/docs/v2.3.x/release_notes.md),
however the image tag configured in the milvus-helm is v2.2.13
(https://github.com/milvus-io/milvus-helm/blob/master/charts/milvus/values.yaml#L8)

**Comment by magallardo** [comment]
@PowderLi Could you clarify the issue?  As I mentioned, I am following the instructions for installing Milvus 2.4 on AKS.

Is the externalS3 supported?  What is needed to get it working?

Thanks in advance.

**Comment by magallardo** [comment]
I was able to fix the issue by removing the milvus https://milvus-io.github.io/milvus-helm/ helm repo and then adding the new  https://zilliztech.github.io/milvus-helm/ helm repo.

Thanks
