### ISSUE TITLE
[Bug]: [import v2]When importing json files generated using the bulk write, there is an error `dynamic field is enabled, explicit specification of '$meta' is not allowed`

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#31835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master/2.4
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When importing json files generated using the bulk write, there is an error `dynamic field is enabled, explicit specification of '$meta' is not allowed`

### Expected Behavior

import success

**Comment by bigsheeper** [comment]
/assign @zhuwenxing 
should be fixed in master branch, please help to make verify

**Comment by zhuwenxing** [comment]
verified and fixed in `master-20240411-4bf32bbc-amd64`

**Comment by bigsheeper** [comment]
> > Prohibit duplicated keys within the $meta field, for instance, {"id": 1, "vector": [], "x": 6, "$meta": {"x": 8}}
> 
> this issue was still open

Only duplicated keys of dynamic field are not allowed.

**Comment by zhuwenxing** [comment]
verified and fixed

**Comment by zhuwenxing** [comment]
verified and fixed
