### ISSUE TITLE
[Bug]: The metrics dataCoord.Dropped-L1 segment number is negative

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#31891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4-20240402-8b8a5b4ac-amd64
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):   kafka  
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0.rc53
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/27288593/d82912d2-9f4d-4e33-9fb7-e76dc7cf2159)

- grafana: [metrics of delta-insert-op-63-8349](https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=P1809F7CD0C75ACF3&var-cluster=&var-namespace=qa-milvus&var-instance=delta-insert-op-63-8349&var-collection=All&var-app_name=milvus&from=1712074953227&to=1712129327627)

- test: disable L0 segment and concurrent: insert + delete + flush + search
![image](https://github.com/milvus-io/milvus/assets/27288593/7c2a2832-a2ee-400a-9cce-b420b519ef23)

- argo: https://argo-workflows.zilliz.cc/archived-workflows/qa/6f7c1313-02dc-486b-9731-47d38aeab48f?nodeId=delta-stable-1712077200-394633573

**Comment by xiaofan-luan** [comment]
keep it @XuanYang-cn

**Comment by xiaofan-luan** [comment]
keep it

**Comment by ThreadDao** [comment]
- image: 2.4-20240928-9a07c1bc-amd64
![image](https://github.com/user-attachments/assets/18749d38-ea7a-4572-8d97-6c7432385b1f)
- https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=P1809F7CD0C75ACF3&var-namespace=qa-milvus&var-instance=compact-opt-rate-100m-1&var-collection=All&var-app_name=milvus&from=1728359645603&to=1728439443232

**Comment by XuanYang-cn** [comment]
should be fixed now, please help review
/assign @ThreadDao 
/unassign

**Comment by ThreadDao** [comment]
can't reproduce
