### ISSUE TITLE
Hello, I deployed Milvus to the cloud server. The recall took about 1 minute. The document was only a PDF of about 3M. How should I deal with it?

### ISSUE THREAD

**Issue by 19157681683** [milvus-io/milvus#31915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):stanalone
- MQ type(rocksmq, pulsar or kafka):    no
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus
- OS(Ubuntu or CentOS): Centos
- CPU/Memory: 4/8G
- GPU: no
- Others:
```

### Current Behavior

Hello, I deployed Milvus to the cloud server. The recall took about 1 minute. The document was only a PDF of about 3M. How should I deal with it?

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version:
> - Deployment mode(standalone or cluster):stanalone
> - MQ type(rocksmq, pulsar or kafka):    no
> - SDK version(e.g. pymilvus v2.0.0rc2):pymilvus
> - OS(Ubuntu or CentOS): Centos
> - CPU/Memory: 4/8G
> - GPU: no
> - Others:
> ```
> 
> ### Current Behavior
> Hello, I deployed Milvus to the cloud server. The recall took about 1 minute. The document was only a PDF of about 3M. How should I deal with it?
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

We can not answer this question with out any detailed logs and monitorning metrics.
What does this 3 minutes consist?  Embedding time? Generation time? Data loding time? Indexing time?
Search is usually not the bottleneck here

**Comment by yanliang567** [comment]
/assign @19157681683 
besides, we need more info about your collection schema, index types and params, search params, etc.  For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.

/unassign
