### ISSUE TITLE
[Bug]: Cannot connect to milvus database through pymilvus

### ISSUE THREAD

**Issue by 70G37H3R** [milvus-io/milvus#31910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.x
- Deployment mode(standalone or cluster): Zilliz Cloud
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): Latest
- OS(Ubuntu or CentOS): Windows
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

WARNING:pymilvus.decorators:[__internal_register] retry:21, cost: 3.00s, reason: <_InactiveRpcError: StatusCode.UNKNOWN, The action is unavailable under current cluster status STOPPED.>
WARNING:pymilvus.decorators:[__internal_register] retry:22, cost: 3.00s, reason: <_InactiveRpcError: StatusCode.UNKNOWN, The action is unavailable under current cluster status STOPPED.>
WARNING:pymilvus.decorators:[__internal_register] retry:23, cost: 3.00s, reason: <_InactiveRpcError: StatusCode.UNKNOWN, The action is unavailable under current cluster status STOPPED.>

### Expected Behavior

Creating index successfully

### Steps To Reproduce

```markdown
def generate_datasource():
    logger.info("Creating new index")
    # load the documents and create the index
    documents = get_documents()
    store = MilvusVectorStore(
        uri=os.environ["MILVUS_URL"],
        token=os.environ["MILVUS_API_KEY"],
        collection_name=os.environ["MILVUS_COLLECTION_NAME"],
        dim=1536, overwrite=True
    )
    storage_context = StorageContext.from_defaults(vector_store=store)
    VectorStoreIndex.from_documents(
        documents,
        storage_context=storage_context,
        show_progress=True,  # this will show you a progress bar as the embeddings are created
    )
    logger.info(
        f"Successfully created embeddings and save to your MILVUS index {os.environ['MILVUS_COLLECTION_NAME']}"
    )
```

**Comment by yanliang567** [comment]
I guess your cluster on zilliz cloud was stopped.  please file a ticket in https://support.zilliz.com/hc/en-us for privacy issue.
/assign @70G37H3R 
/unassign
