### ISSUE TITLE
[Bug]: PERMISSION_DENIED after upgrading milvus from 2.3.3 to 2.3.12

### ISSUE THREAD

**Issue by xige-16** [milvus-io/milvus#31939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

<_MultiThreadedRendezvous:StatusCode.PERMISSION_DENIED,PrivilegeGetFlushState:permissiondeny to xxxx>
<_MultiThreadedRendezvous: StatusCode.PERMISSION_DENIED, PrivilegeShowPartitions: permission deny to xxxx>

### Expected Behavior

no permission error

### Steps To Reproduce

```markdown
1. upgrage milvus from 2.3.3 to 2.3.12
```

**Comment by SimFG** [comment]
@xige-16 can you show the privileges of the related roles?

**Comment by xige-16** [comment]
> @xige-16 can you show the privileges of the related roles?

I have checked and found that after the upgrade, there is indeed no Privilege on the partition, as well as the Privilege on flushState. I added it manually. @SimFG

**Comment by xige-16** [comment]
Before the upgrade, I did not have grant partition Privilege, but I could operate partition and flsuh.

**Comment by SimFG** [comment]
@xige-16 yes, the related privileges are added in the new version. in the v2.3.x version, if the apis are not required the privileges, you can use it. When you upgrade the v2.4.x version, there are some new privileges, which caused the error.

**Comment by xige-16** [comment]
@SimFG It is best to have compatibility processing, otherwise you will not be able to operate the partition after the upgrade, and it is recommended to provide prompts in the document https://milvus.io/docs/v2.3.x/users_and_roles.md

**Comment by yanliang567** [comment]
any updates for this ?
