### ISSUE TITLE
[Bug]: [loadSegmentFunc] [error="[UnexpectedError] Error:GetObjectSize[errcode:404, exception:, errmessage:No response body.]

### ISSUE THREAD

**Issue by AI-Candy-Yang** [milvus-io/milvus#31941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.16
- Deployment mode(standalone or cluster):standalone 
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.2.17
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 24/128
- GPU: 
- Others:
```

### Current Behavior

can't  load  1200百万数据左右

### Steps To Reproduce

```markdown
load stucking
```

### Milvus Log

[[32mmilvus-standalone](url) |[0m 10 response headers:
[32mmilvus-standalone |[0m accept-ranges : bytes
[32mmilvus-standalone |[0m content-length : 0
[32mmilvus-standalone |[0m content-security-policy : block-all-mixed-content
[32mmilvus-standalone |[0m date : Sun, 07 Apr 2024 03:07:35 GMT
[32mmilvus-standalone |[0m server : MinIO
[32mmilvus-standalone |[0m strict-transport-security : max-age=31536000; includeSubDomains
[32mmilvus-standalone |[0m vary : Accept-Encoding
[32mmilvus-standalone |[0m x-amz-request-id : 17C3E09EC3D3EBA5
[32mmilvus-standalone |[0m x-content-type-options : nosniff
[32mmilvus-standalone |[0m x-xss-protection : 1; mode=block
[32mmilvus-standalone |[0m 
[32mmilvus-standalone |[0m 2024-04-07 03:07:35,826 | INFO | default | [SEGCORE][ProcessFormattedStatement][milvus] [AWS LOG] [ERROR] 2024-04-07 03:07:35.826 AWSClient [140419452524288] HTTP response code: 404
[32mmilvus-standalone |[0m Resolved remote host IP address: 172.19.0.3
[32mmilvus-standalone |[0m Request ID: 
[32mmilvus-standalone |[0m Exception name: 
[32mmilvus-standalone |[0m Error message: No response body.
[32mmilvus-standalone |[0m 10 response headers:
[32mmilvus-standalone |[0m accept-ranges : bytes
[32mmilvus-standalone |[0m content-length : 0
[32mmilvus-standalone |[0m content-security-policy : block-all-mixed-content
[32mmilvus-standalone |[0m date : Sun, 07 Apr 2024 03:07:35 GMT
[32mmilvus-standalone |[0m server : MinIO
[32mmilvus-standalone |[0m strict-transport-security : max-age=31536000; includeSubDomains
[32mmilvus-standalone |[0m vary : Accept-Encoding
[32mmilvus-standalone |[0m x-amz-request-id : 17C3E09EC3D1A20C
[32mmilvus-standalone |[0m x-content-type-options : nosniff
[32mmilvus-standalone |[0m x-xss-protection : 1; mode=block
[32mmilvus-standalone |[0m 
[32mmilvus-standalone |[0m 2024-04-07 03:07:35,826 | INFO | default | [SEGCORE][ProcessFormattedStatement][milvus] [AWS LOG] [ERROR] 2024-04-07 03:07:35.826 AWSClient [140417656485632] HTTP response code: 404
[32mmilvus-standalone |[0m Resolved remote host IP address: 172.19.0.3
[32mmilvus-standalone |[0m Request ID: 
[32mmilvus-standalone |[0m Exception name: 
[32mmilvus-standalone |[0m Error message: No response body.
[32mmilvus-standalone |[0m 10 response headers:
[32mmilvus-standalone |[0m accept-ranges : bytes
[32mmilvus-standalone |[0m content-length : 0
[32mmilvus-standalone |[0m content-security-policy : block-all-mixed-content
[32mmilvus-standalone |[0m date : Sun, 07 Apr 2024 03:07:35 GMT
[32mmilvus-standalone |[0m server : MinIO
[32mmilvus-standalone |[0m strict-transport-security : max-age=31536000; includeSubDomains
[32mmilvus-standalone |[0m vary : Accept-Encoding
[32mmilvus-standalone |[0m x-amz-request-id : 17C3E09EC3D68EFE
[32mmilvus-standalone |[0m x-content-type-options : nosniff
[32mmilvus-standalone |[0m x-xss-protection : 1; mode=block
[32mmilvus-standalone |[0m 
[32mmilvus-standalone |[0m 2024-04-07 03:07:35,826 | INFO | default | [SEGCORE][ProcessFormattedStatement][milvus] [AWS LOG] [ERROR] 2024-04-07 03:07:35.826 AWSClient [140417421489920] HTTP response code: 404
[32mmilvus-standalone |[0m Resolved remote host IP address: 172.19.0.3
[32mmilvus-standalone |[0m Request ID: 
[32mmilvus-standalone |[0m Exception name: 
[32mmilvus-standalone |[0m Error message: No response body.
[32mmilvus-standalone |[0m 10 response headers:
[32mmilvus-standalone |[0m accept-ranges : bytes
[32mmilvus-standalone |[0m content-length : 0
[32mmilvus-standalone |[0m content-security-policy : block-all-mixed-content
[32mmilvus-standalone |[0m date : Sun, 07 Apr 2024 03:07:35 GMT
[32mmilvus-standalone |[0m server : MinIO
[32mmilvus-standalone |[0m strict-transport-security : max-age=31536000; includeSubDomains
[32mmilvus-standalone |[0m vary : Accept-Encoding
[32mmilvus-standalone |[0m x-amz-request-id : 17C3E09EC3D4E9F4
[32mmilvus-standalone |[0m x-content-type-options : nosniff
[32mmilvus-standalone |[0m x-xss-protection : 1; mode=block
[32mmilvus-standalone |[0m 
[32mmilvus-standalone |[0m 2024-04-07 03:07:35,826 | INFO | default | [SEGCORE][ProcessFormattedStatement][milvus] [AWS LOG] [ERROR] 2024-04-07 03:07:35.826 AWSClient [140418713966336] HTTP response code: 404
[32mmilvus-standalone |[0m Resolved remote host IP address: 172.19.0.3
[32mmilvus-standalone |[0m Request ID: 
[32mmilvus-standalone |[0m Exception name: 
[32mmilvus-standalone |[0m Error message: No response body.
[32mmilvus-standalone |[0m 10 response headers:
[32mmilvus-standalone |[0m accept-ranges : bytes
[32mmilvus-standalone |[0m content-length : 0
[32mmilvus-standalone |[0m content-security-policy : block-all-mixed-content
[32mmilvus-standalone |[0m date : Sun, 07 Apr 2024 03:07:35 GMT
[32mmilvus-standalone |[0m server : MinIO
[32mmilvus-standalone |[0m strict-transport-security : max-age=31536000; includeSubDomains
[32mmilvus-standalone |[0m vary : Accept-Encoding
[32mmilvus-standalone |[0m x-amz-request-id : 17C3E09EC3D6AD84
[32mmilvus-standalone |[0m x-content-type-options : nosniff
[32mmilvus-standalone |[0m x-xss-protection : 1; mode=block
[32mmilvus-standalone |[0m 
[32mmilvus-standalone |[0m 2024-04-07 03:07:35,826 | INFO | default | [SEGCORE][ProcessFormattedStatement][milvus] [AWS LOG] [ERROR] 2024-04-07 03:07:35.826 AWSClient [140416758466304] HTTP response code: 404
[32mmilvus-standalone |[0m Resolved remote host IP address: 172.19.0.3
[32mmilvus-standalone |[0m Request ID: 
[32mmilvus-standalone |[0m Exception name: 
[32mmilvus-standalone |[0m Error message: No response body.
[32mmilvus-standalone |[0m 10 response headers:
[32mmilvus-standalone |[0m accept-ranges : bytes
[32mmilvus-standalone |[0m content-length : 0
[32mmilvus-standalone |[0m content-security-policy : block-all-mixed-content
[32mmilvus-standalone |[0m date : Sun, 07 Apr 2024 03:07:35 GMT
[32mmilvus-standalone |[0m server : MinIO
[32mmilvus-standalone |[0m strict-transport-security : max-age=31536000; includeSubDomains
[32mmilvus-standalone |[0m vary : Accept-Encoding
[32mmilvus-standalone |[0m x-amz-request-id : 17C3E09EC3D60B6E
[32mmilvus-standalone |[0m x-content-type-options : nosniff
[32mmilvus-standalone |[0m x-xss-protection : 1; mode=block
[32mmilvus-standalone |[0m 
[32mmilvus-standalone |[0m 2024-04-07 03:07:35,826 | INFO | default | [SEGCORE][ProcessFormattedStatement][milvus] [AWS LOG] [ERROR] 2024-04-07 03:07:35.826 AWSClient [140417345955584] HTTP response code: 404
[32mmilvus-standalone |[0m Resolved remote host IP address: 172.19.0.3
[32mmilvus-standalone |[0m Request ID: 
[32mmilvus-standalone |[0m Exception name: 
[32mmilvus-standalone |[0m Error message: No response body.
[32mmilvus-standalone |[0m 10 response headers:
[32mmilvus-standalone |[0m accept-ranges : bytes
[32mmilvus-standalone |[0m content-length : 0
[32mmilvus-standalone |[0m content-security-policy : block-all-mixed-content
[32mmilvus-standalone |[0m date : Sun, 07 Apr 2024 03:07:35 GMT
[32mmilvus-standalone |[0m server : MinIO
[32mmilvus-standalone |[0m strict-transport-security : max-age=31536000; includeSubDomains
[32mmilvus-standalone |[0m vary : Accept-Encoding
[32mmilvus-standalone |[0m x-amz-request-id : 17C3E09EC3D6F516
[32mmilvus-standalone |[0m x-content-type-options : nosniff
[32mmilvus-standalone |[0m x-xss-protection : 1; mode=block
[32mmilvus-standalone |[0m 
[32mmilvus-standalone |[0m 2024-04-07 03:07:35,826 | INFO | default | [SEGCORE][ProcessFormattedStatement][milvus] [AWS LOG] [ERROR] 2024-04-07 03:07:35.826 AWSClient [140416724895488] HTTP response code: 404
[32mmilvus-standalone |[0m Resolved remote host IP address: 172.19.0.3
[32mmilvus-standalone |[0m Request ID: 
[32mmilvus-standalone |[0m Exception name: 
[32mmilvus-standalone |[0m Error message: No response body.
[32mmilvus-standalone |[0m 10 response headers:
[32mmilvus-standalone |[0m accept-ranges : bytes
[32mmilvus-standalone |[0m content-length : 0
[32mmilvus-standalone |[0m content-security-policy : block-all-mixed-content
[32mmilvus-standalone |[0m date : Sun, 07 Apr 2024 03:07:35 GMT
[32mmilvus-standalone |[0m server : MinIO
[32mmilvus-standalone |[0m strict-transport-security : max-age=31536000; includeSubDomains
[32mmilvus-standalone |[0m vary : Accept-Encoding
[32mmilvus-standalone |[0m x-amz-request-id : 17C3E09EC3D9152D
[32mmilvus-standalone |[0m x-content-type-options : nosniff
[32mmilvus-standalone |[0m x-xss-protection : 1; mode=block
[32mmilvus-standalone |[0m 
[32mmilvus-standalone |[0m 2024-04-07 03:07:35,827 | INFO | default | [SEGCORE][ProcessFormattedStatement][milvus] [AWS LOG] [ERROR] 2024-04-07 03:07:35.826 AWSClient [140417530595072] HTTP response code: 404
[32mmilvus-standalone |[0m Resolved remote host IP address: 172.19.0.3
[32mmilvus-standalone |[0m Request ID: 
[32mmilvus-standalone |[0m Exception name: 
[32mmilvus-standalone |[0m Error message: No response body.
[32mmilvus-standalone |[0m 10 response headers:
[32mmilvus-standalone |[0m accept-ranges : bytes
[32mmilvus-standalone |[0m content-length : 0
[32mmilvus-standalone |[0m content-security-policy : block-all-mixed-content
[32mmilvus-standalone |[0m date : Sun, 07 Apr 2024 03:07:35 GMT
[32mmilvus-standalone |[0m server : MinIO
[32mmilvus-standalone |[0m strict-transport-security : max-age=31536000; includeSubDomains
[32mmilvus-standalone |[0m vary : Accept-Encoding
[32mmilvus-standalone |[0m x-amz-request-id : 17C3E09EC3D91434
[32mmilvus-standalone |[0m x-content-type-options : nosniff
[32mmilvus-standalone |[0m x-xss-protection : 1; mode=block
[32mmilvus-standalone |[0m 
[32mmilvus-standalone |[0m 2024-04-07 03:07:35,827 | INFO | default | [SEGCORE][ProcessFormattedStatement][milvus] [AWS LOG] [ERROR] 2024-04-07 03:07:35.808 AWSClient [140417631307520] HTTP response code: 404
[32mmilvus-standalone |[0m Resolved remote host IP address: 172.19.0.3
[32mmilvus-standalone |[0m Request ID: 
[32mmilvus-standalone |[0m Exception name: 
[32mmilvus-standalone |[0m Error message: No response body.
[32mmilvus-standalone |[0m 10 response headers:
[32mmilvus-standalone |[0m accept-ranges : bytes
[32mmilvus-standalone |[0m content-length : 0
[32mmilvus-standalone |[0m content-security-policy : block-all-mixed-content
[32mmilvus-standalone |[0m date : Sun, 07 Apr 2024 03:07:35 GMT
[32mmilvus-standalone |[0m server : MinIO
[32mmilvus-standalone |[0m strict-transport-security : max-age=31536000; includeSubDomains
[32mmilvus-standalone |[0m vary : Accept-Encoding
[32mmilvus-standalone |[0m x-amz-request-id : 17C3E09EC2C99D45
[32mmilvus-standalone |[0m x-content-type-options : nosniff
[32mmilvus-standalone |[0m x-xss-protection : 1; mode=block
[32mmilvus-standalone |[0m 
[32mmilvus-standalone |[0m 2024-04-07 03:07:35,827 | INFO | default | [SEGCORE][ProcessFormattedStatement][milvus] [AWS LOG] [ERROR] 2024-04-07 03:07:35.808 AWSClient [140417253635840] HTTP response code: 404
[32mmilvus-standalone |[0m Resolved remote host IP address: 172.19.0.3
[32mmilvus-standalone |[0m Request ID: 
[32mmilvus-standalone |[0m Exception name: 
[32mmilvus-standalone |[0m Error message: No response body.
[32mmilvus-standalone |[0m 10 response headers:
[32mmilvus-standalone |[0m accept-ranges : bytes
[32mmilvus-standalone |[0m content-length : 0
[32mmilvus-standalone |[0m content-security-policy : block-all-mixed-content
[32mmilvus-standalone |[0m date : Sun, 07 Apr 2024 03:07:35 GMT
[32mmilvus-standalone |[0m server : MinIO
[32mmilvus-standalone |[0m strict-transport-security : max-age=31536000; includeSubDomains
[32mmilvus-standalone |[0m vary : Accept-Encoding
[32mmilvus-standalone |[0m x-amz-request-id : 17C3E09EC2C6510E
[32mmilvus-standalone |[0m x-content-type-options : nosniff
[32mmilvus-standalone |[0m x-xss-protection : 1; mode=block
[32mmilvus-standalone |[0m 
[32mmilvus-standalone |[0m [2024/04/07 03:07:35.827 +00:00] [WARN] [querynode/cgo_helper.go:56] ["LoadFieldData failed, C Runtime Exception: [UnexpectedError] Error:GetObjectSize[errcode:404, exception:, errmessage:No response body.]\n"]
[32mmilvus-standalone |[0m [2024/04/07 03:07:35.827 +00:00] [ERROR] [querynode/segment_loader.go:204] ["load segment failed when load data into memory"] [collectionID=448713276739290442] [segmentType=Sealed] [partitionID=448713276739295877] [segmentID=448713276739297065] [error="[UnexpectedError] Error:GetObjectSize[errcode:404, exception:, errmessage:No response body.]"] [stack="github.com/milvus-io/milvus/internal/querynode.(*segmentLoader).LoadSegment.func3\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/segment_loader.go:204\ngithub.com/milvus-io/milvus/internal/util/funcutil.ProcessFuncParallel.func3\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/parallel.go:83"]
[32mmilvus-standalone |[0m [2024/04/07 03:07:35.827 +00:00] [ERROR] [funcutil/parallel.go:85] [loadSegmentFunc] [error="[UnexpectedError] Error:GetObjectSize[errcode:404, exception:, errmessage:No response body.]"] [idx=0] [stack="github.com/milvus-io/milvus/internal/util/funcutil.ProcessFuncParallel.func3\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/parallel.go:85"]
[32mmilvus-standalone |[0m [2024/04/07 03:07:35.827 +00:00] [WARN] [querynode/cgo_helper.go:56] ["LoadFieldData failed, C Runtime Exception: [UnexpectedError] Error:GetObjectSize[errcode:404, exception:, errmessage:No response body.]\n"]
[32mmilvus-standalone |[0m [2024/04/07 03:07:35.827 +00:00] [WARN] [querynode/cgo_helper.go:56] ["LoadFieldData failed, C Runtime Exception: [UnexpectedError] Error:GetObjectSize[errcode:404, exception:, errmessage:No response body.]\n"]
[32mmilvus-standalone |[0m [2024/04/07 03:07:35.827 +00:00] [WARN] [querynode/cgo_helper.go:56] ["LoadFieldData failed, C Runtime Exception: [UnexpectedError] Error:GetObjectSize[errcode:404, exception:, errmessage:No response body.]\n"]
[32mmilvus-standalone |[0m [2024/04/07 03:07:35.827 +00:00] [WARN] [querynode/cgo_helper.go:56] ["LoadFieldData failed, C Runtime Exception: [UnexpectedError] Error:GetObjectSize[errcode:404, exception:, errmessage:No response body.]\n"]
[32mmilvus-standalone |[0m [2024/04/07 03:07:35.827 +00:00] [WARN] [querynode/cgo_helper.go:56] ["LoadFieldData failed, C Runtime Exception: [UnexpectedError] Error:GetObjectSize[errcode:404, exception:, errmessage:No response body.]\n"]
[32mmilvus-standalone |[0m [2024/04/07 03:07:35.827 +00:00] [WARN] [querynode/cgo_helper.go:56] ["LoadFieldData failed, C Runtime Exception: [UnexpectedError] Error:GetObjectSize[errcode:404, exception:, errmessage:No response body.]\n"]
[32mmilvus-standalone |[0m [2024/04/07 03:07:35.828 +00:00] [WARN] [querynode/cgo_helper.go:56] ["LoadFieldData failed, C Runtime Exception: [UnexpectedError] Error:GetObjectSize[errcode:404, exception:, errmessage:No response body.]\n"]
[32mmilvus-standalone |[0m [2024/04/07 03:07:35.828 +00:00] [WARN] [querynode/cgo_helper.go:56] ["LoadFieldData failed, C Runtime Exception: [UnexpectedError] Error:GetObjectSize[errcode:404, exception:, errmessage:No response body.]\n"]
[32mmilvus-standalone |[0m [2024/04/07 03:07:35.828 +00:00] [INFO] [task/scheduler.go:750] ["task removed"] [taskID=11138] [taskStatus=4] [channel=by-dev-rootcoord-dml_2_448713276739290442v0]
[32mmilvus-standalone |[0m [2024/04/07 03:07:35.828 +00:00] [INFO] [task/scheduler.go:576] ["processed tasks"] [nodeID=23352] [toProcessNum=55] [failCount=55] [toRemoveNum=1]
[32mmilvus-standalone |[0m [2024/04/07 03:07:35.828 +00:00] [INFO] [task/scheduler.go:582] ["process tasks related to node done"] [nodeID=23352] [processingTaskNum=55] [waitingTaskNum=0] [segmentTaskNum=55] [channelTaskNum=0]
[32mmilvus-standalone |[0m [2024/04/07 03:07:35.827 +00:00] [WARN] [querynode/cgo_helper.go:56] ["LoadFieldData failed, C Runtime Exception: [UnexpectedError] Error:GetObjectSize[errcode:404, exception:, errmessage:No response body.]\n"]
[32mmilvus-standalone |[0m [2024/04/07 03:07:35.828 +00:00] [INFO] [task/scheduler.go:262] ["task added"] [task="[id=11139] [type=1] [collectionID=448713276739290442] [replicaID=448909452186484741] [priority=2] [actionsCount=1] [actions={[type=1][node=23352]}] [channel=by-dev-rootcoord-dml_2_448713276739290442v0]"]
[32mmilvus-standalone |[0m [2024/04/07 03:07:35.830 +00:00] [WARN] [datanode/binlog_io.go:85] ["downloading failed, retry in 50ms"] [paths="[files/insert_log/448713276739290442/448713276739294005/448834055206340074/0/448834055206340101,files/insert_log/448713276739290442/448713276739294005/448834055206340074/1/448834055206340102,files/insert_log/448713276739290442/448713276739294005/448834055206340074/100/448834055206340097,files/insert_log/448713276739290442/448713276739294005/448834055206340074/101/448834055206340098,files/insert_log/448713276739290442/448713276739294005/448834055206340074/102/448834055206340099,files/insert_log/448713276739290442/448713276739294005/448834055206340074/103/448834055206340100]"]
[32mmilvus-standalone |[0m [2024/04/07 03:07:35.831 +00:00] [ERROR] [querynode/segment_loader.go:204] ["load segment failed when load data into memory"] [collectionID=448713276739290442] [segmentType=Sealed] [partitionID=448713276739295877] [segmentID=448713276739297264] [error="[UnexpectedError] Error:GetObjectSize[errcode:404, exception:, errmessage:No response body.]"] [stack="github.com/milvus-io/milvus/internal/querynode.(*segmentLoader).LoadSegment.func3\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/segment_loader.go:204\ngithub.com/milvus-io/milvus/internal/util/funcutil.ProcessFuncParallel.func3\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/parallel.go:83"]
[32mmilvus-standalone |[0m [2024/04/07 03:07:35.831 +00:00] [ERROR] [funcutil/parallel.go:85] [loadSegmentFunc] [error="[UnexpectedError] Error:GetObjectSize[errcode:404, exception:, errmessage:No response body.]"] [idx=5] [stack="github.com/milvus-io/milvus/internal/util/funcutil.ProcessFuncParallel.func3\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/parallel.go:85"]
[32mmilvus-standalone |[0m [2024/04/07 03:07:35.831 +00:00] [ERROR] [querynode/segment_loader.go:204] ["load segment failed when load data into memory"] [collectionID=448713276739290442] [segmentType=Sealed] [partitionID=448713276739290456] [segmentID=448713276739292004] [error="[UnexpectedError] Error:GetObjectSize[errcode:404, exception:, errmessage:No response body.]"] [stack="github.com/milvus-io/milvus/internal/querynode.(*segmentLoader).LoadSegment.func3\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/segment_loader.go:204\ngithub.com/milvus-io/milvus/internal/util/funcutil.ProcessFuncParallel.func3\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/parallel.go:83"]
[32mmilvus-standalone |[0m [2024/04/07 03:07:35.831 +00:00] [ERROR] [funcutil/parallel.go:85] [loadSegmentFunc] [error="[UnexpectedError] Error:GetObjectSize[errcode:404, exception:, errmessage:No response body.]"] [idx=4] [stack="github.com/milvus-io/milvus/internal/util/funcutil.ProcessFuncParallel.func3\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/parallel.go:85"]
[32mmilvus-standalone |[0m [2024/04/07 03:07:35.831 +00:00] [INFO] [gc/gc_tuner.go:84] ["GC Tune done"] ["previous GOGC"=200] ["heapuse "=124] ["total memory"=25996] ["next GC"=270] ["new GOGC"=200] [gc-pause=2.070446ms] [gc-pause-end=1712459255829928198]
[32mmilvus-standalone |[0m [2024/04/07 03:07:35.831 +00:00] [WARN] [datanode/binlog_io.go:85] ["downloading failed, retry in 50ms"] [paths="[files/insert_log/448713276739290442/448713276739290456/448713276742064841/0/448713276742064906,files/insert_log/448713276739290442/448713276739290456/448713276742064841/1/448713276742064907,files/insert_log/448713276739290442/448713276739290456/448713276742064841/100/448713276742064902,files/insert_log/448713276739290442/448713276739290456/448713276742064841/101/448713276742064903,files/insert_log/448713276739290442/448713276739290456/448713276742064841/102/448713276742064904,files/insert_log/448713276739290442/448713276739290456/448713276742064841/103/448713276742064905]"]
[32mmilvus-standalone |[0m [2024/04/07 03:07:35.835 +00:00] [ERROR] [querynode/segment_loader.go:204] ["load segment failed when load data into memory"] [collectionID=448713276739290442] [segmentType=Sealed] [partitionID=448713276739294005] [segmentID=448713276739295004] [error="[UnexpectedError] Error:GetObjectSize[errcode:404, exception:, errmessage:No response body.]"] [stack="github.com/milvus-io/milvus/internal/querynode.(*segmentLoader).LoadSegment.func3\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/segment_loader.go:204\ngithub.com/milvus-io/milvus/internal/util/funcutil.ProcessFuncParallel.func3\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/parallel.go:83"]
[32mmilvus-standalone |[0m [2024/04/07 03:07:35.835 +00:00] [ERROR] [querynode/segment_loader.go:204] ["load segment failed when load data into memory"] [collectionID=448713276739290442] [segmentType=Sealed] [partitionID=448713276739292212] [segmentID=448713276739293553] [error="[UnexpectedError] Error:GetObjectSize[errcode:404, exception:, errmessage:No response body.]"] [stack="github.com/milvus-io/milvus/internal/querynode.(*segmentLoader).LoadSegment.func3\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/segment_loader.go:204\ngithub.com/milvus-io/milvus/internal/util/funcutil.ProcessFuncParallel.func3\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/parallel.go:83"]
[32mmilvus-standalone |[0m [2024/04/07 03:07:35.835 +00:00] [ERROR] [funcutil/parallel.go:85] [loadSegmentFunc] [error="[UnexpectedError] Error:GetObjectSize[errcode:404, exception:, errmessage:No response body.]"] [idx=7] [stack="github.com/milvus-io/milvus/internal/util/funcutil.ProcessFuncParallel.func3\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/parallel.go:85"]
[32mmilvus-standalone |[0m [2024/04/07 03:07:35.835 +00:00] [ERROR] [funcutil/parallel.go:85] [loadSegmentFunc] [error="[UnexpectedError] Error:GetObjectSize[errcode:404, exception:, errmessage:No response body.]"] [idx=3] [stack="github.com/milvus-io/milvus/internal/util/funcutil.ProcessFuncParallel.func3\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/parallel.go:85"]
[32mmilvus-standalone |[0m [2024/04/07 03:07:35.852 +00:00] [INFO] [querynode/segment.go:320] ["delete segment from memory"] [collectionID=448713276739290442] [partitionID=448713276739290450] [segmentID=448713276739291355] [segmentType=Sealed]
[32mmilvus-standalone |[0m [2024/04/07 03:07:35.870 +00:00] [INFO] [querynode/segment.go:320] ["delete segment from memory"] [collectionID=448713276739290442] [partitionID=448713276739292212] [segmentID=448713276739293553] [segmentType=Sealed]

**Comment by xiaofan-luan** [comment]
seems that some of the logs has been missing on S3.
Did you have full logs? 
will restart help?

**Comment by AI-Candy-Yang** [comment]
but my data is in minio

**Comment by AI-Candy-Yang** [comment]
I have full logs,but the logs file is too big,can't upload

**Comment by AI-Candy-Yang** [comment]
[milvus.log](https://github.com/milvus-io/milvus/files/14896126/milvus.log)

**Comment by xiaofan-luan** [comment]
448713276739290442/448713276739294005/448834055206340074/0/448834055206340101,files/insert_log/448713276739290442/448713276739294005/448834055206340074/1/448834055206340102,files/insert_log/448713276739290442/448713276739294005/448834055206340074/100/448834055206340097,files/insert_log/448713276739290442/448713276739294005/448834055206340074/101/448834055206340098,files/insert_log/448713276739290442/448713276739294005/448834055206340074/102/448834055206340099,files/insert_log/448713276739290442/448713276739294005/448834055206340074/103/44883405520634010

**Comment by xiaofan-luan** [comment]
could you check if these files on S3 still exist?

all the files on S3 seems to be missing.
1) some bugs of gc causing this. you need to trace the log from segmentID 448834055206340074 see if there are anything sepcial
2) other reason cause the file missing -> like deploy two milvus cluster use same rootpath, manullay deleted files.

To fix. you will need to use birwatcher to cleanup the meta data of segment 448834055206340074.
Birdwatcher also has a tool to check if all segment file exists.

And we highly recommend to upgrade to 2.3.13. Many of the bugs cause this issue has been fixed
