### ISSUE TITLE
[Bug]: should check l0 segment's location during get shard leaders

### ISSUE THREAD

**Issue by weiliu1031** [milvus-io/milvus#31956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master and 2.4
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

doesn't check l0 segment's location during get shard leaders

### Expected Behavior

should check l0 segment's location during get shard leaders

**Comment by xiaofan-luan** [comment]
get shard leader only return the current valid shard leader

**Comment by xiaofan-luan** [comment]
everything else should be controlled by shard delegator.
