### ISSUE TITLE
[Bug]: Segmentation Fault on ARM-Based Milvus GPU Build (Branch 2.4)

### ISSUE THREAD

**Issue by samhuang-z** [milvus-io/milvus#31953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: Branch 2.4
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu 22.04
- CPU/Memory: 
- GPU: YES
- Others:
```

### Current Behavior

**Description:**
While attempting to build and run Milvus with GPU support on an ARM-based system, I encountered a "Segmentation fault (core dumped)" error. This issue arose during the execution phase, following a seemingly successful build on the 2.4 branch.

### Expected Behavior

Milvus should run without crashing, allowing for further operations and testing.

### Steps To Reproduce

```markdown
Checked out branch 2.4 from the Milvus repository.
Followed the build instructions for an ARM-based system with GPU support.
Executed the Milvus binary.
Encountered the segmentation fault.
```

**Comment by yanliang567** [comment]
/assign @samhuang-z 
I think @Presburger has merged the fix pr. please help to verify
/unassign
