### ISSUE TITLE
[Bug]: Potential Recall Issue in Matching Self with Search Function in v2.4.0-rc.1

### ISSUE THREAD

**Issue by secsilm** [milvus-io/milvus#31965]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.4.0-rc.1
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 12 cores / 64 GB
- GPU: 
- Others:
```

### Current Behavior

Hello Milvus Team,

I've encountered an unexpected behavior while using the search function in Milvus version 2.4.0-rc.1. When searching for vectors that exist in the database, some vectors do not match themselves as expected.

### Expected Behavior

Normally, I would expect a vector searched in the database to return itself with a distance close to 1 (for COSINE similarity) or a very high similarity score. However, this is not always the case.

Here is the data I used:

[test.sample.10.json](https://github.com/milvus-io/milvus/files/14896671/test.sample.10.json)

### Steps To Reproduce

Here is the code and data:

```python
from pymilvus import MilvusClient, DataType

client = MilvusClient(uri="http://localhost:19530")
collection_name = 'test'
iso = 'US'
ids = list(range(5))
query_embed = [item['embed'] for item in client.get(collection_name, ids=ids)]
search_params = {
    "data": query_embed,
    "anns_field": "embed",
    "search_params": {
        "metric_type": "COSINE",
        "params": {"radius": 0.6, "range_filter": 1.0},
    },
    "limit": 10,
    "filter": f"(iso == {iso!r}) and (id in {ids})",
}
client.search(collection_name, **search_params)
```

output:

```python
[[{'id': 0, 'distance': 1.0, 'entity': {}}],
 [{'id': 1, 'distance': 1.0, 'entity': {}}],
 [],   # mismatch, the id should be 2
 [{'id': 3, 'distance': 0.9999999403953552, 'entity': {}}],
 []]   # mismatch, the id should be 2
```

**Comment by xiaofan-luan** [comment]
> ### 这是否存在现有问题？
> * [x] 我已经搜索了现有的问题
> 
> ### 环境
> ```
> - Milvus version: v2.4.0-rc.1
> - Deployment mode(standalone or cluster): standalone
> - MQ type(rocksmq, pulsar or kafka):    
> - SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0
> - OS(Ubuntu or CentOS): Ubuntu
> - CPU/Memory: 12 cores / 64 GB
> - GPU: 
> - Others:
> ```
> 
> ### 目前的行为
> Milvus 团队您好，
> 
> 我在 Milvus 2.4.0-rc.1 版本中使用搜索功能时遇到了意外行为。当搜索数据库中存在的向量时，某些向量与预期不匹配。
> 
> ### 预期行为
> 通常，我希望在数据库中搜索的向量返回其自身的距离接近 1（对于余弦相似度）或非常高的相似度分数。然而，这并非总是如此。
> 
> 这是我使用的数据：
> 
> [测试.样本.10.json](https://github.com/milvus-io/milvus/files/14896671/test.sample.10.json)
> 
> ### 重现步骤
> 这是代码和数据：
> 
> ```python
> from pymilvus import MilvusClient, DataType
> 
> client = MilvusClient(uri="http://localhost:19530")
> collection_name = 'test'
> iso = 'US'
> ids = list(range(5))
> query_embed = [item['embed'] for item in client.get(collection_name, ids=ids)]
> search_params = {
>     "data": query_embed,
>     "anns_field": "embed",
>     "search_params": {
>         "metric_type": "COSINE",
>         "params": {"radius": 0.6, "range_filter": 1.0},
>     },
>     "limit": 10,
>     "filter": f"(iso == {iso!r}) and (id in {ids})",
> }
> client.search(collection_name, **search_params)
> ```
> 
> 输出：
> 
> ```python
> [[{'id': 0, 'distance': 1.0, 'entity': {}}],
>  [{'id': 1, 'distance': 1.0, 'entity': {}}],
>  [],   # mismatch, the id should be 2
>  [{'id': 3, 'distance': 0.9999999403953552, 'entity': {}}],
>  []]   # mismatch, the id should be 2
> ```
> 
> ### Milvus 日志
> _没有反应_
> 
> ### 还要别的吗？
> _没有反应_

As you may notice, range search doesn't guarantee 100% accurate.

And under your case, you have exact same vectors, distance= 1.0 and very similar vectors - distance 0.9999999..., those are all great candidates(And I guess 7 digit float number is already more than float could offer).

1. check your embeddings, those embeddings should be as different as possible. If there are many similar embeddings it destroys the index algorithm
2. When test, shouldn't expect 100% accurate,  if it's 95% accurate or more, which means when you look top 100, 95 of them are correct, then it's actually already working. If it's far below 95%, please offer your dataset and we can analyze on it. Many of the bad cases are usually cased by dataset (Like too many vectors in a small vector space)

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version: v2.4.0-rc.1
> - Deployment mode(standalone or cluster): standalone
> - MQ type(rocksmq, pulsar or kafka):    
> - SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0
> - OS(Ubuntu or CentOS): Ubuntu
> - CPU/Memory: 12 cores / 64 GB
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> Hello Milvus Team,
> 
> I've encountered an unexpected behavior while using the search function in Milvus version 2.4.0-rc.1. When searching for vectors that exist in the database, some vectors do not match themselves as expected.
> 
> ### Expected Behavior
> Normally, I would expect a vector searched in the database to return itself with a distance close to 1 (for COSINE similarity) or a very high similarity score. However, this is not always the case.
> 
> Here is the data I used:
> 
> [test.sample.10.json](https://github.com/milvus-io/milvus/files/14896671/test.sample.10.json)
> 
> ### Steps To Reproduce
> Here is the code and data:
> 
> ```python
> from pymilvus import MilvusClient, DataType
> 
> client = MilvusClient(uri="http://localhost:19530")
> collection_name = 'test'
> iso = 'US'
> ids = list(range(5))
> query_embed = [item['embed'] for item in client.get(collection_name, ids=ids)]
> search_params = {
>     "data": query_embed,
>     "anns_field": "embed",
>     "search_params": {
>         "metric_type": "COSINE",
>         "params": {"radius": 0.6, "range_filter": 1.0},
>     },
>     "limit": 10,
>     "filter": f"(iso == {iso!r}) and (id in {ids})",
> }
> client.search(collection_name, **search_params)
> ```
> 
> output:
> 
> ```python
> [[{'id': 0, 'distance': 1.0, 'entity': {}}],
>  [{'id': 1, 'distance': 1.0, 'entity': {}}],
>  [],   # mismatch, the id should be 2
>  [{'id': 3, 'distance': 0.9999999403953552, 'entity': {}}],
>  []]   # mismatch, the id should be 2
> ```
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

As you may notice, range search doesn't guarantee 100% accurate.

And under your case, you have exact same vectors, distance= 1.0 and very similar vectors - distance 0.9999999..., those are all great candidates(And I guess 7 digit float number is already more than float could offer).

check your embeddings, those embeddings should be as different as possible. If there are many similar embeddings it destroys the index algorithm
When test, shouldn't expect 100% accurate, if it's 95% accurate or more, which means when you look top 100, 95 of them are correct, then it's actually already working. If it's far below 95%, please offer your dataset and we can analyze on it. Many of the bad cases are usually cased by dataset (Like too many vectors in a small vector space)

**Comment by secsilm** [comment]
@xiaofan-luan Thanks for your reply.

If I understand correctly, you mean that range search is not accurate, it does not strictly filter based on score. Can you briefly explain how it works?

Also, I did find that I can get accurate results if I don't use range search.

**Comment by secsilm** [comment]
I know where the problem is now, the **`range_filter` cannot be set to 1**, the actual result may be slightly larger than 1 (I guess it's a floating-point calculation issue), so it needs to be set slightly larger than 1, such as 1.1, that should work.

**Comment by xiaofan-luan** [comment]
@cydrain 
maybe we cn change anthing larger than1 to 1

**Comment by xiaofan-luan** [comment]
> I know where the problem is now, the **`range_filter` cannot be set to 1**, the actual result may be slightly larger than 1 (I guess it's a floating-point calculation issue), so it needs to be set slightly larger than 1, such as 1.1, that should work.
> 
> I think this point needs to be mentioned in the document.

you don't really need to set range_filter

**Comment by secsilm** [comment]
> > I know where the problem is now, the **`range_filter` cannot be set to 1**, the actual result may be slightly larger than 1 (I guess it's a floating-point calculation issue), so it needs to be set slightly larger than 1, such as 1.1, that should work.
> > I think this point needs to be mentioned in the document.
> 
> you don't really need to set range_filter

If I only need results with scores higher than `radius`, then I really don't need to set `range_filter`. But if someone wants to set both values at the same time, then they may need to set these two values a little wider. Or your internal implementation may need something similar to eps.

**Comment by cydrain** [comment]
> @cydrain maybe we cn change anthing larger than1 to 1也许我们 cn 将大于 1 的 anthing 更改为 1

@xiaofan-luan

**Comment by cydrain** [comment]
> @cydrain maybe we cn change anthing larger than1 to 1也许我们 cn 将大于 1 的 anthing 更改为 1

OK, I'll open an issue for this
