### ISSUE TITLE
[Bug]: When the like expression for query is incorrect, it will not throw an error but instead return an empty result

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#31967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3/2.4/master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

the expression is `"color like \"red\""`

the response is empty instead of returning an error

### Expected Behavior

should raise error

**Comment by xiaofan-luan** [comment]
why this should return an error?

"color like \"red\""
seems to be a valid expression

**Comment by yanliang567** [comment]
@longjiquan any comments?

**Comment by zhuwenxing** [comment]
> why this should return an error?
> 
> "color like "red"" seems to be a valid expression

@xiaofan-luan 
lack of `%`

It should be `"color like '%red'"` , `"color like 'red%'"` or `"color like '%red%'"`

**Comment by xiaofan-luan** [comment]
even with out %， this could be a valid expr?

**Comment by xiaofan-luan** [comment]
you just don't have any data match "red"

**Comment by longjiquan** [comment]
"color like 'red'" is equal to "color == 'red'"

**Comment by zhuwenxing** [comment]
ok, I got it. In my previous understanding, I always thought that the "like" expression must be followed by a %.

and yes, it works like `==`
![image](https://github.com/user-attachments/assets/c27e3d84-7fae-4a7f-a1d3-ba361c47cca2)
