### ISSUE TITLE
[Bug]: Can we update the base image version to the latest version without lots of CVEs?

### ISSUE THREAD

**Issue by weiZhenkun** [milvus-io/milvus#31997]
### Is there an existing issue for this?

- [X] I have searched the existing issues

https://github.com/milvus-io/milvus/blob/master/build/docker/milvus/ubuntu20.04/Dockerfile#L12

why we keep the version in the 20220426 and not update to the latest for 8 months?
can we update ubuntu:focal-20220426 to ubuntu:focal or the latest version?

https://github.com/milvus-io/milvus/blob/master/build/docker/milvus/amazonlinux2023/Dockerfile#L12
for amazonlinux:2023, we are use it without date, but for ubuntu,we are use it with date?

**Comment by xiaofan-luan** [comment]
is there a special reason we need to update it?

**Comment by weiZhenkun** [comment]
not a special reason, but when you keep the version in a stable version, it will bring lots of CVEs.

For https://github.com/milvus-io/milvus/blob/master/build/docker/milvus/amazonlinux2023/Dockerfile#L12, you are using a big version, but for ubuntu, you are using the fixed verson. it does not make sence.

**Comment by weiZhenkun** [comment]
![image](https://github.com/milvus-io/milvus/assets/27683687/985633ec-ed52-48cd-8dc9-db8c4081d3d6)

**Comment by LoveEachDay** [comment]
@weiZhenkun We're making sure there is no critical cve vulnerabilities.

**Comment by weiZhenkun** [comment]
> @weiZhenkun We're making sure there is no critical cve vulnerabilities.

any update?

**Comment by yanliang567** [comment]
keep it
