### ISSUE TITLE
[Bug]: rootcoord sendtimetick sync timeout, change plusar  requestTimeout config reload, can not create producer

### ISSUE THREAD

**Issue by JamesBonddu** [milvus-io/milvus#32017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.11
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.6
- OS(Ubuntu or CentOS): ubuntt
- CPU/Memory: 1T
- GPU: 256
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/15228379/b95b2954-43f3-4936-8ad7-cda3acfb986a)

![image](https://github.com/milvus-io/milvus/assets/15228379/cf801ab8-e468-4dd6-af2c-e8bfa8b50c1b)

### Steps To Reproduce

0. docker compose config

2. rootcoord sendtimetick sync timeout
![image](https://github.com/milvus-io/milvus/assets/15228379/940aaf4a-c964-4229-8df4-939a44534e99)

3. change pulsar requestTimeout=600 config 
https://github.com/milvus-io/milvus/pull/26526/files

4. reload config report error
![image](https://github.com/milvus-io/milvus/assets/15228379/9bac95d1-5653-417a-b61c-42a4786dad88)

_No response_

### Milvus Log
[c5ff5383ad20b371778d9b8131a53b535bda8410d66e90f6fe1e67091c212364-json.log](https://github.com/milvus-io/milvus/files/14904616/c5ff5383ad20b371778d9b8131a53b535bda8410d66e90f6fe1e67091c212364-json.log)
[0935401f590919a2654f872ca6b17138d4433992b74ced6670e3810744459a1e-json.log](https://github.com/milvus-io/milvus/files/14904617/0935401f590919a2654f872ca6b17138d4433992b74ced6670e3810744459a1e-json.log)

_No response_

**Comment by xiaofan-luan** [comment]
changing the config may not help too much.

we need to figure out why pulsar get timeout. Did you get a chance to check the states of your pulsar cluster?

**Comment by yanliang567** [comment]
One thing we can check is that whether the pulsar was attached ssd volumes？and does it shared with any other applications/milvus?
/assign @JamesBonddu 
/unassign

**Comment by JamesBonddu** [comment]
> changing the config may not help too much.
> 
> we need to figure out why pulsar get timeout. Did you get a chance to check the states of your pulsar cluster?

we used milvus cluster docker compose pulsar, pulsar backlog quota exceed, cannot create producer

![image](https://github.com/milvus-io/milvus/assets/15228379/710be6ff-b42f-4788-9974-5ddb6ba52261)

**Comment by JamesBonddu** [comment]
> One thing we can check is that whether the pulsar was attached ssd volumes？and does it shared with any other applications/milvus? /assign @JamesBonddu /unassign

we attached pulsar on ssd volumnes,and not share with other application/milvus

**Comment by yanliang567** [comment]
what about changing to the latest image? v2.3.13-gpu?

**Comment by JamesBonddu** [comment]
> what about changing to the latest image? v2.3.13-gpu?

i will try this later, something has changed?

**Comment by JamesBonddu** [comment]
> pulsar backlog quota exceed, cannot create producer

 pulsar backlog quota exceed, cannot create producer is much matter.
