### ISSUE TITLE
[Bug]: excessive memory usage in datanode for 10M-dimensional HNSW index

### ISSUE THREAD

**Issue by douglarek** [milvus-io/milvus#32032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.3.13
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: calculate according to tools sizing tool
- GPU: 
- Others:
```

### Current Behavior

The current datanode's memory usage is too high:

![image](https://github.com/milvus-io/milvus/assets/1488134/2039f3d2-9184-4c66-b42a-1ca940d428ca)

### Expected Behavior

![image](https://github.com/milvus-io/milvus/assets/1488134/5f38780d-f7ad-4c44-81e5-762d691c28fd)

### Steps To Reproduce

```markdown
Without using mmap, create a 4096-dimensional vector, index it with HNSW, and insert 10 million data points.
```

### Milvus Log

Logs captured through `export_milvus_log.sh`: https://drive.google.com/file/d/18jaCfxDUxV_4gE7DDJ29T5ggAzo_UzPA/view?usp=sharing

### Anything else?

Connection information for Kafka, etcd, and other important connections has been sanitized.

**Comment by xiaofan-luan** [comment]
> ```
>  a 4096-dimensional vector, index it with HNSW, and insert 10
> ```

This is the minimum requirment. 
The datanode memory usage is more based on how frequent the write is. (Any partitions, collections number )
@congqixia is still working on optimizing it on 2.4 branch.
I would recommend to have 16GB memory if you have very intensive write workload.

**Comment by yanliang567** [comment]
@douglarek I'd like to know more about how you insert data into milvus? the concurrent number of insertion? the number of entities for each insert request? did you manually call flush() during the insertion? also if possible please share the collection schema info.
/assign @douglarek 
/unassign

**Comment by congqixia** [comment]
@douglarek for datanode workload unbalance issue, it looks like there is only one share for this collection. So only one datanode can have workload, which is by design

**Comment by hjlee9182** [comment]
@yanliang567 
When do I have to do the flash? During the insert? Or after the insert?

**Comment by yanliang567** [comment]
> @yanliang567 When do I have to do the flash? During the insert? Or after the insert?

in most cases, you don't have to do flsuh() manually, Milvus will do it automatically.

**Comment by xiaofan-luan** [comment]
@hjlee9182 

1. could you generate a pprof for the memory usage? 
2. for cluster mode, milvus will use up to 50% of the pod memory. Did you set a memory limit for the pod? That is saying, if you set memory limit to 16G, milvus will use slightly more than 8g

**Comment by hjlee9182** [comment]
I'm not a questioner, I was just commenting out of curiosity, you're asking this person, right? @douglarek

**Comment by xiaofan-luan** [comment]
try to set it to 32GB and I guess it will be 20GB.
Because what milvus can see is your limit.
But anyway I should try to improve the flush speed

**Comment by congqixia** [comment]
> > try to set it to 32GB and I guess it will be 20GB. Because what milvus can see is your limit. But anyway I should try to improve the flush speed
> 
> I've noticed an interesting phenomenon: no matter how many partitions are set for all topics under xxx_rootcoord-dml_xx, and no matter how many datanodes there are, the data always aggregates to the same datanode.

For utilizing multiple datanodes or dml channels, the number or shards shall be increased but with some cost of search performance

**Comment by xiaofan-luan** [comment]
Usually each shard should be split evenly. because the hash all the pk and write into one of the shard by PK.
unless you are trying to write with same PK or the PK has some really weird pattern
