### ISSUE TITLE
Support data resides in GPU memory

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#3204]
As title.

**Comment by suvashishtha** [comment]
@shengjun1985  @JackLCL  - did you also verified if it is the case with cpu also?

I have deleted vectors from a table containing 500K vectors. Dropped Index and 
 The table size was dropped from 2G to 800MB but not reducing further. Is it something related?

**Comment by shengjun1985** [comment]
@suvashishtha 
There is no problem with this phenomenon.
Although the collection is dropped, the data in the Milvus cache will not be cleared.
When the Milvux cache is full, it will automatically GC with LRU strategy.

**Comment by suvashishtha** [comment]
@shengjun1985 
all clear now. thanks for the info

**Comment by shanghaikid** [comment]
@shengjun1985 can we close this?
