### ISSUE TITLE
[Bug]: The query interface parameter 'reduce_stop_for_best=true' does not return some of the expected partial result data.

### ISSUE THREAD

**Issue by lentitude2tk** [milvus-io/milvus#32059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.3.13-91cdada-219	
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka): None 
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. When using pymilvus queryIterator, it was found that the returned batches did not meet expectations. The associated issue is as follows: https://github.com/milvus-io/pymilvus/issues/2017
2. Further analysis reveals that when using the query interface, the parameter reduce_stop_for_best is passed to improve the utilization of query results (returning data beyond the limit).
3. However, during the testing process, it was discovered that in certain scenarios, although there were more data remaining in reality, the returned data was less than the limit.
4. Build a data ID/vector column, the relevant schema information is as follows:
```
fields = [
    FieldSchema(name=USER_ID, dtype=DataType.INT64, is_primary=True,
                        auto_id=False),
            FieldSchema(name=AGE, dtype=DataType.INT64),
            FieldSchema(name=PICTURE, dtype=DataType.FLOAT_VECTOR, dim=DIM)
]
schema = CollectionSchema(fields)
collection = Collection(COLLECTION_NAME, schema, consistency_level=CONSISTENCY_LEVEL, num_shards=2)
```

5. Insert data for USER_ID and AGE from 1 to 5000 for the purpose of tracking whether the iterator is working correctly.
```
def insert_data(collection):
    rng = np.random.default_rng(seed=19530)
    batch_count = 5
    filter_set: set = {}
    for i in range(batch_count):
        entities = [
            [(i * NUM_ENTITIES + ni) for ni in range(NUM_ENTITIES)],
            [(i * NUM_ENTITIES + ni) for ni in range(NUM_ENTITIES)],
            [float(ni) for ni in range(NUM_ENTITIES)],
            rng.random((NUM_ENTITIES, DIM)),
        ]
        collection.insert(entities)
        collection.flush()
        print(f"Finish insert batch{i}, number of entities in Milvus: {collection.num_entities}")
```

6. When using the expression '10 <= userAge <= 110 and userID > 28' with 'reduce_stop_for_best=true', it is expected to retrieve the record with ID 71 (exceeding limit=50).
![image](https://github.com/milvus-io/milvus/assets/108672767/c7a05ac5-b35f-4473-a945-d634951e92d0)

7. When using the expression '10 <= userAge <= 110 and userID > 78' with 'reduce_stop_for_best=true', it is expected to retrieve more records. However, only 29 records are obtained, with the last record being 107. **_This does not meet expectations._**
![image](https://github.com/milvus-io/milvus/assets/108672767/54e1463d-0f02-48c9-afd0-fd035ee2e99f)

8. If the expression '10 <= userAge <= 110 and userID > 78' is used with 'reduce_stop_for_best=false', the data obtained is normal, with the last record being 110. The result meets expectations.
![image](https://github.com/milvus-io/milvus/assets/108672767/2ad6b15c-4730-4033-a94a-8d9be3cd4b7a)

### Expected Behavior

1. When passing the parameter reduce_stop_for_best in the query interface, in cases where data is abundant, the expected number of results retrieved should be greater than or equal to the limit quantity.

### Steps To Reproduce

```markdown
1. Refer to steps 4, 5, 6, 7, and 8 in the 'Current Behavior' section to reliably reproduce the issue.
```

**Comment by xiaofan-luan** [comment]
/assign @MrPresent-Han 

This seems to be a bug

**Comment by xiaofan-luan** [comment]
I believe this is not a bug but definitely something we can improve.

Currently under reduce, the break condition is:
1. reach limit
2. reduceStopForBest && drainOneResult

Problem is :
if one segment has only 1 element, it will be easy to drain result
so if segment returns less than limit result, it means no more data in this segment, so drain drainOneResult should not count this segment

**Comment by lentitude2tk** [comment]
In image version v2.4.11-c1662535-1148, using the same dataset with QueryIterator, it was found that if reduceStopForBest=True is specified, the expected result (userID=100) was not returned during this iteration, causing data stratification. However, this issue does not occur when reduceStopForBest=False is specified.

![image](https://github.com/user-attachments/assets/0081f85a-53e7-4943-b1db-a715a15fc21e)

However, the data for userID=100 actually exists, and it will be returned during the next execution of QueryIterator when the condition (10 <= userAge <= 100) and userID > 99 is applied. Is this an expected and acceptable behavior? @xiaofan-luan @MrPresent-Han
