### ISSUE TITLE
[Bug]: After modifying the configuration and restarting milvus, the load index gets stuck.

### ISSUE THREAD

**Issue by TonyAnn** [milvus-io/milvus#32074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

After modifying the configuration and restarting milvus, the load index gets stuck.

### Milvus Log

[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/14917291/milvus-log.tar.gz)

**Comment by TonyAnn** [comment]
![Uploading index load stuck.png…]()
From the attu point of view, the index status keeps spinning.

**Comment by yanliang567** [comment]
/assign @TonyAnn 
quick questions:
1. which config items did you change, from which value to which?
2. Could you please attach the etcd backup for investigation？ Check this: https://github.com/milvus-io/birdwatcher for details about how to backup etcd with birdwatcher
3. I saw you config the querynode with 2 cpu cores and 72 Gi memory, which does not make sense to me. Generally it is recommend to config a 1:4 or 1:8 for cpu and memory. could you please share more info about this config?

**Comment by TonyAnn** [comment]
> /assign @TonyAnn quick questions:
> 
> 1. which config items did you change, from which value to which?
Add the following parameters to config：
datacoord:
    segment:
    maxSize: 2048
    sealProportion: 0.75
    assignmentExpiration: 50000

> 2. Could you please attach the etcd backup for investigation？ Check this: https://github.com/milvus-io/birdwatcher for details about how to backup etcd with birdwatcher
Reference attachment：
[Uploading bw_etcd_ALL.240129-211500.bak.gz…]()

When backing up, the following error is reported:
backup etcd failed, error: etcdserver: mvcc: required revision has been compacted

> 3. I saw you config the querynode with 2 cpu cores and 72 Gi memory, which does not make sense to me. Generally it is recommend to config a 1:4 or 1:8 for cpu and memory. could you please share more info about this config?

Some configurations are as follows：

queryNode:
  enabled: true
  replicas: 86
  resources:
    limits:
      memory: 72Gi
      cpu: 2
    requests:
      cpu: 1
      memory: 72Gi
indexNode:
  enabled: true
  replicas: 4
  resources:
    limits:
      memory: 16Gi
      cpu: 16
    requests:
      memory: 4Gi
      cpu: 4
rootCoordinator:
  enabled: true
  # You can set the number of replicas greater than 1, only if enable active standby
  replicas: 1  # Run Root Coordinator mode with replication disabled
  resources:
    limits:
      memory: 4Gi
      cpu: 2
dataCoordinator:
  enabled: true
  # You can set the number of replicas greater than 1, only if enable active standby
  replicas: 1           # Run Data Coordinator mode with replication disabled
  resources:
    limits:
      memory: 8Gi
      cpu: 4
    requests:
      memory: 4Gi
      cpu: 2
dataNode:
  enabled: true
  replicas: 4
  resources:
    limits:
      memory: 32Gi
      cpu: 4
    requests:
      memory: 16Gi
      cpu: 2

**Comment by xiaofan-luan** [comment]
backup etcd failed, error: etcdserver: mvcc: required revision has been compacted

seems that the etcd is not able to work.
did you try to use birdwatcher and etcdcli to see if etcd is working correctly?

2. queryNode:
enabled: true
replicas: 86
resources:
limits:
memory: 72Gi
cpu: 2

you are claim for 72GB memory and 86 querynodes. are you sure you have so many memory in your K8s? seems that you only require 2 cores and that is not what recommended. usually core:memory should be 1:2 if it's computation prioritized and 1:8 if it's memory prioritized. 2:72 doens't make any sense to me

**Comment by xiaofan-luan** [comment]
from the log, seems that the etcd is working.

could you explain what did you do to the cluster?

from the log you offered:

**Comment by xiaofan-luan** [comment]
["filter invalid insert message, collection mis-match"] ["Get collID"=448149065612608536] ["Expected collID"=446155861422955863] seems that two collections are actually read from others log, this is unlikely to happen.

Are you trying to upgrade? what is the milvus version before you start and after you start? 
Any other operation you did before you start the cluster?

**Comment by yanliang567** [comment]
/assign @tedxu 
please also keep an eye on this issue.

**Comment by TonyAnn** [comment]
> from the log, seems that the etcd is working.

hi  xiaofan Test results show that etcd is running normally.
[root@~]$ kubectl get svc |grep -i etcd 
my-release-etcd                    ClusterIP   10.96.3.170   <none>        2379/TCP,2380/TCP                     257d
my-release-etcd-headless           ClusterIP   None          <none>        2379/TCP,2380/TCP                     257d
[root@~]$ etcdctl --endpoints=10.96.3.170:2379 endpoint health
10.96.3.170:2379 is healthy: successfully committed proposal: took = 24.819385ms


> 
> could you explain what did you do to the cluster?
I just add some datacoord parameter configuration under the user.yaml module in values.yaml, and then use helm upgrade to update:
The parameters added are as follows:
datacoord:
segment:
maxSize: 2048
sealProportion: 0.75
assignmentExpiration: 50000

> 
> from the log you offered:

**Comment by TonyAnn** [comment]
> ["filter invalid insert message, collection mis-match"] ["Get collID"=448149065612608536] ["Expected collID"=446155861422955863] seems that two collections are actually read from others log, this is unlikely to happen.
> 
> Are you trying to upgrade? what is the milvus version before you start and after you start? Any other operation you did before you start the cluster?

The version has not been upgraded before, the milvus version is 2.2.11
When a problem occurs, just modify some configuration parameters and then update

**Comment by TonyAnn** [comment]
> backup etcd failed, error: etcdserver: mvcc: required revision has been compacted
> 
> seems that the etcd is not able to work. did you try to use birdwatcher and etcdcli to see if etcd is working correctly?
> 
> 2. queryNode:
>    enabled: true
>    replicas: 86
>    resources:
>    limits:
>    memory: 72Gi
>    cpu: 2
> 
> you are claim for 72GB memory and 86 querynodes. are you sure you have so many memory in your K8s? seems that you only require 2 cores and that is not what recommended. usually core:memory should be 1:2 if it's computation prioritized and 1:8 if it's memory prioritized. 2:72 doens't make any sense to me

The k8s cluster memory is 8TB, but there are fewer CPUs, so this restriction is imposed

**Comment by TonyAnn** [comment]
> The parameters added are as follows:
> datacoord:
> segment:
> maxSize: 2048
> sealProportion: 0.75
> assignmentExpiration: 50000

The parameters added are as follows:
datacoord:
segment:
maxSize: 2048
sealProportion: 0.75
assignmentExpiration: 50000

**Comment by xiaofan-luan** [comment]
those seems to be not related.

try to use less querynode with larger pod. and deploy the loking or elk for logs. if you get the all the error logs that could be really helpful. 

filter invalid insert message, collection mis-match"] ["Get collID"=448149065612608536] ["Expected collID"=446155861422955863

this log is weird, but I don't have context about why this could happen.
upgrade to 2.2.17 and use larger pod. see what kind of error logs you get

**Comment by TonyAnn** [comment]
> those seems to be not related.
> 
> try to use less querynode with larger pod. and deploy the loking or elk for logs. if you get the all the error logs that could be really helpful.
> 
> filter invalid insert message, collection mis-match"] ["Get collID"=448149065612608536] ["Expected collID"=446155861422955863
> 
> this log is weird, but I don't have context about why this could happen. upgrade to 2.2.17 and use larger pod. see what kind of error logs you get

Thank you for your support. I will adjust pod size, deploy loking and upgrade version later.

**Comment by yanliang567** [comment]
I'd close this issue and feel free to file a new one if you met any new problems
