### ISSUE TITLE
[Bug]: MilvusClient connect failed in Milvus v2.4.0

### ISSUE THREAD

**Issue by JeremyLee-lrj** [milvus-io/milvus#32085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4.0
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus v2.4.0
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I try to connect the Milvus server from another host, it turns out a bug report.
Here is the code I wrote
```
client = MilvusClient(
    uri="http://10.100.2.241:19530",
    token="root:Milvus",
    db_name="default"
)
```

**Comment by JeremyLee-lrj** [comment]
Here is the Error :
```
Failed to create new connection using: c74fb081bcbc4c3d8f42fbb3e610714d
Traceback (most recent call last):
  File "D:\Pymilvus-benchmark\TextSearch\search.py", line 6, in <module>
    client = MilvusClient(
  File "D:\Python3.8\Pymilvus-benchmark\lib\site-packages\pymilvus\milvus_client\milvus_client.py", line 53, in __init__
    self._using = self._create_connection(
  File "D:\Python3.8\Pymilvus-benchmark\lib\site-packages\pymilvus\milvus_client\milvus_client.py", line 639, in _create_connection
    raise ex from ex
  File "D:\Python3.8\Pymilvus-benchmark\lib\site-packages\pymilvus\milvus_client\milvus_client.py", line 636, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "D:\Python3.8\Pymilvus-benchmark\lib\site-packages\pymilvus\orm\connections.py", line 420, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "D:\Python3.8\Pymilvus-benchmark\lib\site-packages\pymilvus\orm\connections.py", line 371, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "D:\Python3.8\Pymilvus-benchmark\lib\site-packages\pymilvus\client\grpc_handler.py", line 146, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on 10.100.2.241:19530, illegal connection params or server unavailable)>

```

**Comment by xiaofan-luan** [comment]
@JeremyLee-lrj 
1. could you ping 10.100.2.241 or telnet and make sure the network is reachable?
2. any error message from milvus server side?

**Comment by yanliang567** [comment]
@JeremyLee-lrj besides, please attach the milvus logs for investigation. For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.
/assign @JeremyLee-lrj 
/unassign

**Comment by JeremyLee-lrj** [comment]
1. I can ping 10.100.2.241 successfully.
2. after enter command `docker-compose logs>milvus.log`, and I got the log. But milvus.log is too long, so I paste it here https://paste.ubuntu.com/p/cMMPC9QW8S/

**Comment by JeremyLee-lrj** [comment]
I found the reason why this doesn't work.

**Comment by JeremyLee-lrj** [comment]
I found the reason. 
The server's 19530 port is not open.

**Comment by zhdawei** [comment]
@xiaofan-luan hello we met same issue
1) We re-encrypt 19530 port to 443
2) When we connect without VPN(in office network), it works
3) when we connect with VPN opened , out of office, we met "illegal connection params or server unavailable"

**Comment by xiaofan-luan** [comment]
I thought this might be a milvus issue but you your vpn chnaged some of the network package
