### ISSUE TITLE
Improve documentation of Prometheus metrics

### ISSUE THREAD

**Issue by ThomWright** [milvus-io/milvus#3210]
**Report needed documentation**
A list of metrics Milvus exposes, including the *metric names*. Knowing the metric names makes it much easier to use.

**Describe the documentation you'd like**
A table describing the Prometheus metrics exposed by Milvus. The table here shows a good example of how this could be formatted: https://prometheus.io/docs/instrumenting/writing_clientlibs/#process-metrics - notice the name and unit columns.

**Steps taken to search for needed documentation**
The metrics are currently described here: https://milvus.io/docs/v0.10.1/setup_grafana.md

I think this should be taken out of the 'Grafana' section. The exposed metrics are not really related to Grafana (I could use something else to graph them), so at first I didn't look here. They could be in a Prometheus section, or their own section.

**Comment by fishpenguin** [comment]
We will fix the metric names and the documentation in milvus-0.11.0.
