### ISSUE TITLE
[Bug]: Compilation Error on ARM: Missing arm_sve.h

### ISSUE THREAD

**Issue by samhuang-z** [milvus-io/milvus#32129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- **Machine Architecture**: ARM
- **Branch**: 2.4
```

### Current Behavior

Compilation fails due to the inability to locate the `arm_sve.h` header file.

**Issue Description:**
During the compilation process on the ARM machine, an error is encountered in the `sve-impl.h` file, specifically at line 21, which attempts to include `arm_sve.h`. The compiler is unable to find the `arm_sve.h` file, leading to the termination of the compilation process.

**Error Log:**
```
13:12:37 /go/src/github.com/milvus-io/milvus/internal/core/src/bitset/detail/platform/arm/sve-impl.h:21:10: fatal error: arm_sve.h: No such file or directory
13:12:37 21 | #include <arm_sve.h>
13:12:37 | ^~~~~~~~~~~
13:12:37 compilation terminated.
```

**Steps to Reproduce:**
1. Checkout branch 2.4.
2. Initiate the compilation process on an ARM machine.

### Expected Behavior

The source should compile without errors related to missing headers, particularly `arm_sve.h`.

**Comment by zhagnlu** [comment]
https://github.com/alexanderguzhva/bitset/commit/b3f5fd3d50d2ca071d402a5174166dd1cb51abb6  
this solution is better, wait to merge to milvus.=

**Comment by yanliang567** [comment]
/assign @samhuang-z 
please help to verify
