### ISSUE TITLE
Multiple metrics in a collection

### ISSUE THREAD

**Issue by shiyu22** [milvus-io/milvus#3213]
**Is your feature request related to a problem? Please describe.**
I have to create three collections with three metrics and the index type is FLAT.

**Describe the solution you'd like**
When I use the FLAT index, I can choose any one metric to search.

**Comment by shengjun1985** [comment]
It will be supported in 0.11.0.

**Comment by meton-robean** [comment]
> It will be supported in 0.11.0.

when will the 0.11.0 version be released?

**Comment by shengjun1985** [comment]
As planned, 0.11.0 will be released at the end of this month.

**Comment by shengjun1985** [comment]
It will be supported in 0.10.3.
