### ISSUE TITLE
[Bug]:  newly inserted data does not display the correct segment row numbers

### ISSUE THREAD

**Issue by douglarek** [milvus-io/milvus#32161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.13
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: enough
- GPU: 
- Others:
```

### Current Behavior

Executing flush on attu, after writing to disk, shows no data.

![image](https://github.com/milvus-io/milvus/assets/1488134/c77db33a-ca81-4b44-92e2-31fbc8bb9e7b)

But it also shows that the actual number of inserted entries is 445,000.

![image](https://github.com/milvus-io/milvus/assets/1488134/c0043bc4-514d-4968-8747-2ee044bd1c8c)

And what's even more absurd is that although it clearly states 1-22 data entries, only 16 are actually displayed.

![image](https://github.com/milvus-io/milvus/assets/1488134/58562ca0-7917-44eb-83c5-ccd251073a91)

### Anything else?

I'm not sure if this is an issue with attu（version 2.3.10） or not. For attu 2.3.8 and 2.3.10, the segment section always displays 0 rows.

**Comment by yanliang567** [comment]
/assign @shanghaikid 
please help to check if it is a attu issue.
/unassign

**Comment by xiaofan-luan** [comment]
@douglarek I'm assuming this is more like a bug on your usage.
Could you share you code about how you implement?

**Comment by xiaofan-luan** [comment]
@douglarek 
you have to do a manual flush or wait for 24 hours or fill the size of one segment before you can see it.
But that don't affect you search.
I you want to know the exact number of collection, use count.

**Comment by xiaofan-luan** [comment]
if you want to check the correct num entities. then flush could help.
better way is to use count

**Comment by xiaofan-luan** [comment]
what is the number you get if you use pymilvus client?

if it's also 0, could you try to use birdwatcher and check the how entity is there i your meta of your segment?
