### ISSUE TITLE
[Bug]: 34 million HNSW 4096-dimensional vectors is causing excessive memory pressure on certain query nodes

### ISSUE THREAD

**Issue by douglarek** [milvus-io/milvus#32170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.13
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: enough
- GPU: 
- Others:
```

### Current Behavior

30 query node instances configured as follows: request: 8 CPUs, 32GB, limit: 8 CPUs, 64GB. Individual query nodes have reached over 50GB of memory usage.

![image](https://github.com/milvus-io/milvus/assets/1488134/c8e32611-c922-48f2-a1a5-91200a44896b)

### Expected Behavior

Memory usage is relatively uniform.

**Comment by yanliang567** [comment]
@douglarek I guess you have streaming insertion to the milvus cluster, so one of querynode(the delegator) takes most growing segments and leads to more memory usage.  quick questions: how many index nodes do you have, and how much cpu and memory for each of them?

/assign @douglarek

**Comment by yanliang567** [comment]
more questions:
1. how many collections and partitions do you have?
2. how many shards do you set?
3. if possible, please share the metrics for datanode as well

**Comment by yanliang567** [comment]
/assign @douglarek 
Could you please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

**Comment by yanliang567** [comment]
@congqixia 
any upates for this issue
