### ISSUE TITLE
[Bug]: [LRU] potential memory leak when searching with LRU enabled

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#32173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvus-io-lru-dev-6e67e5a-20240411
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus
```

### Current Behavior

memory usage increased 800MB in 10min-searching 
![image](https://github.com/milvus-io/milvus/assets/82361606/5dba01ad-e4d6-41db-9599-7fb34519c54a)

### Expected Behavior

no memory increase

### Steps To Reproduce

```markdown
1. deploy a milvus with LRU enalbed
2. insert 1m-768d, hnsw index and load
3. search
```

### Milvus Log

pod name in 4am cluster:
`lru-yanliang2-milvus-standalone-7d7849f69b-slrc4                  0/1     Running                           4 (30s ago)      129m    10.104.32.10    4am-node39   <none>           <none>
`

**Comment by sunby** [comment]
Maybe it's not a memory leak. Search will trigger loading segment in lazyload mode. I will check it.

**Comment by yanliang567** [comment]
not reproduce on milvus-io-lru-dev-1023c2b-20240415
