### ISSUE TITLE
[Bug]: If the previous import failed, subsequent imports may get stuck.

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#32195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

If the previous import failed, subsequent imports may get stuck.

**Comment by bigsheeper** [comment]
/assign @zhuwenxing 
please help to verify

**Comment by zhuwenxing** [comment]
verified and fixed
