### ISSUE TITLE
[Proposal]: Optimize Milvus Build Process

### ISSUE THREAD

**Issue by samhuang-z** [milvus-io/milvus#32240]
**Current Issue:**
At present, the build process for Milvus involves the use of a runtime Docker container. This approach is not based on a native Docker build, which typically utilizes a Dockerfile to manage the build process. This non-native method complicates the build process and can lead to inconsistencies and inefficiencies.

**Objective:**
The objective of this proposal is to streamline the Milvus build process, ensuring it is both efficient and accessible. We aim to achieve this through the following goals:

1. **Simplify Build Process:** 
   - Transition to a single Dockerfile build approach. This method will not only simplify the construction and maintenance of the build environment but also enhance the overall reliability and reproducibility of the build process. This simplification will facilitate both end-to-end (e2e) and unit testing. In turn, it will enhance user experience, benefit developers and users who wish to build Milvus independently,  further encouraging community contributions and engagement.

2. **Optimize Build Speed:**
   - Maximize the use of Docker's build cache to accelerate the Milvus build process. By efficiently leveraging the cache, we can significantly reduce build times, making the development cycle quicker and more efficient.

### Structured Build Procedure
To enhance the efficiency and clarity of the Milvus build process, we propose organizing it into well-defined stages. This structured approach will not only aid in maintaining the code but will also optimize the utilization of Docker's caching capabilities. The stages are outlined as follows:

1. **Compile Third-Party Dependencies:** Isolate and compile the essential third-party libraries required by Milvus, ensuring these are handled before more frequently changing elements of the build.
2. **Download Go Dependencies:** Acquire all necessary Go dependencies efficiently and reliably.
3. **Download Milvus Protobuf Definitions:** Fetch the latest Milvus protobuf files to ensure up-to-date interfaces for service communication.
4. **Generate Protobuf Files:** Execute commands to generate protobuf files, setting the stage for service interface implementation.
5. **Compile Milvus C++ Components:** Compile all C++ components of Milvus, optimizing for performance and stability.
6. **Compile Milvus Go Components:** Finalize the build by compiling the Go components, integrating seamlessly with the previously compiled C++ binaries.

### Leveraging Docker Build Cache
The order in which commands are executed in a Dockerfile significantly impacts the efficiency of the build process, as changes in earlier layers invalidate the cache for subsequent ones. To optimize this:

1. **Install Less Frequently Changed Dependencies First:** Begin with more stable components, such as third-party dependencies, to leverage Docker's cache more effectively across builds.
2. **Introduce Frequently Changed Elements Later:** Place elements like Milvus's own source code later in the Dockerfile. This strategy ensures that modifications in the source code do not force a rebuild of the entire dependency chain.

For instance, if there are changes only in the Milvus Go source code, Docker can skip rebuilding the C++ components, thus saving time and resources.

### Choosing the Right Cache Storage Backends
Docker Buildx supports various cache storage backends, each suited to different scenarios:

- **Registry:** This backend stores the build cache in a separate Docker image and pushes it to a specified registry. Ideal for distributed environments where multiple builders need access to the cache.
- **Local:** Keeps the build cache in a local directory. This method is straightforward and effective for single-node builds.
- **GHA (GitHub Actions):** Utilizes the GitHub Actions cache to store the build cache, providing a seamless integration for CI/CD pipelines running on GitHub.

For Milvus, combining different backends can optimize the build process across environments. For example:
- **Unit Tests on GitHub Runners:** Utilize the GHA cache backend to enhance speed and efficiency.
- **End-to-End Tests in IDC Environments:** Opt for the registry or local cache backend to ensure quick access to the build cache, minimizing build times.

By strategically implementing these caching mechanisms and structuring the build process, we can significantly enhance the development and deployment workflow for Milvus.

 

**Conclusion:**
Adopting a Dockerfile-based approach for the Milvus build process represents a strategic improvement that aligns with modern development practices. By enhancing the efficiency, reliability, and accessibility of the build process, we can foster a stronger, more vibrant Milvus community and ensure the platform continues to grow and evolve effectively.

**Comment by xiaofan-luan** [comment]
This seems

> **Current Issue:** At present, the build process for Milvus involves the use of a runtime Docker container. This approach is not based on a native Docker build, which typically utilizes a Dockerfile to manage the build process. This non-native method complicates the build process and can lead to inconsistencies and inefficiencies.
> 
> **Objective:** The objective of this proposal is to streamline the Milvus build process, ensuring it is both efficient and accessible. We aim to achieve this through the following goals:
> 
> 1. **Simplify Build Process:**
>    
>    * Transition to a single Dockerfile build approach. This method will not only simplify the construction and maintenance of the build environment but also enhance the overall reliability and reproducibility of the build process. This simplification will facilitate both end-to-end (e2e) and unit testing. In turn, it will enhance user experience, benefit developers and users who wish to build Milvus independently,  further encouraging community contributions and engagement.
> 2. **Optimize Build Speed:**
>    
>    * Maximize the use of Docker's build cache to accelerate the Milvus build process. By efficiently leveraging the cache, we can significantly reduce build times, making the development cycle quicker and more efficient.
> 
> ## Implementation Details
> ### Structured Build Procedure
> To enhance the efficiency and clarity of the Milvus build process, we propose organizing it into well-defined stages. This structured approach will not only aid in maintaining the code but will also optimize the utilization of Docker's caching capabilities. The stages are outlined as follows:
> 
> 1. **Compile Third-Party Dependencies:** Isolate and compile the essential third-party libraries required by Milvus, ensuring these are handled before more frequently changing elements of the build.
> 2. **Download Go Dependencies:** Acquire all necessary Go dependencies efficiently and reliably.
> 3. **Download Milvus Protobuf Definitions:** Fetch the latest Milvus protobuf files to ensure up-to-date interfaces for service communication.
> 4. **Generate Protobuf Files:** Execute commands to generate protobuf files, setting the stage for service interface implementation.
> 5. **Compile Milvus C++ Components:** Compile all C++ components of Milvus, optimizing for performance and stability.
> 6. **Compile Milvus Go Components:** Finalize the build by compiling the Go components, integrating seamlessly with the previously compiled C++ binaries.
> 
> ### Leveraging Docker Build Cache
> The order in which commands are executed in a Dockerfile significantly impacts the efficiency of the build process, as changes in earlier layers invalidate the cache for subsequent ones. To optimize this:
> 
> 1. **Install Less Frequently Changed Dependencies First:** Begin with more stable components, such as third-party dependencies, to leverage Docker's cache more effectively across builds.
> 2. **Introduce Frequently Changed Elements Later:** Place elements like Milvus's own source code later in the Dockerfile. This strategy ensures that modifications in the source code do not force a rebuild of the entire dependency chain.
> 
> For instance, if there are changes only in the Milvus Go source code, Docker can skip rebuilding the C++ components, thus saving time and resources.
> 
> ### Choosing the Right Cache Storage Backends
> Docker Buildx supports various cache storage backends, each suited to different scenarios:
> 
> * **Registry:** This backend stores the build cache in a separate Docker image and pushes it to a specified registry. Ideal for distributed environments where multiple builders need access to the cache.
> * **Local:** Keeps the build cache in a local directory. This method is straightforward and effective for single-node builds.
> * **GHA (GitHub Actions):** Utilizes the GitHub Actions cache to store the build cache, providing a seamless integration for CI/CD pipelines running on GitHub.
> 
> For Milvus, combining different backends can optimize the build process across environments. For example:
> 
> * **Unit Tests on GitHub Runners:** Utilize the GHA cache backend to enhance speed and efficiency.
> * **End-to-End Tests in IDC Environments:** Opt for the registry or local cache backend to ensure quick access to the build cache, minimizing build times.
> 
> By strategically implementing these caching mechanisms and structuring the build process, we can significantly enhance the development and deployment workflow for Milvus.
> 
> **Conclusion:** Adopting a Dockerfile-based approach for the Milvus build process represents a strategic improvement that aligns with modern development practices. By enhancing the efficiency, reliability, and accessibility of the build process, we can foster a stronger, more vibrant Milvus community and ensure the platform continues to grow and evolve effectively.

This seems to be very helpful. 

Can you explain about "use of a runtime Docker container. " versus "native Docker build"?
What might be major difference?

**Comment by samhuang-z** [comment]
Currently, Milvus is built within a container. However, it is expected to transition to being built using a Dockerfile. This change will enhance the build process by making it more independent, resilient, and aligned with industry standards, effectively making it more cloud-native.

The existing approach of building inside a container is akin to building within a virtual machine. This method introduces dependencies and artifacts that are tied to a specific machine, which is not ideal. Furthermore, it's not straightforward. To address these dependencies, we typically have to mount the host path to the container path, which can be cumbersome and frustrating. For instance, in the discussion at Milvus GitHub Issue #32364, a user experienced a broken Conan dependency without making any changes to the Milvus code, necessitating a rebuild from scratch. This process is slow and prone to errors.

Shifting to the proposed method will leverage modern Docker building techniques powered by [BuildKit](https://docs.docker.com/build/buildkit/), which offers numerous advantages. As seen again in Milvus GitHub Issue #32364, all the previously mentioned drawbacks will be mitigated. This shift promises a more efficient and error-free building experience, fully embracing the benefits of modern, cloud-native development practices.

**Comment by samhuang-z** [comment]
**What will really excite me** after shifting to the proposed method:

If there are no changes to Milvus, the new approach will significantly accelerate the build process. Specifically, if Milvus remains unchanged—regardless of location or time—all processes will utilize the cache, allowing the Milvus build to complete in just a few seconds.

If only the Go code in Milvus is modified, then only the Go component will need to be rebuilt during the Milvus build process.

If changes are made exclusively to the C++ code in Milvus, both the C++ component and the Go component will need to be rebuilt. However, this setup will bypass the rebuilding of the Conan dependencies.
