### ISSUE TITLE
[Bug]: GO Unit test script is using non existing directory names and also has name resolution problem inside pkg.

### ISSUE THREAD

**Issue by Ald392** [milvus-io/milvus#32254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When i run the go unit test script the following is the result : 
![image](https://github.com/milvus-io/milvus/assets/166891594/7d53960d-3483-48f8-84d1-20cd4ea6ca83)

1. test_config function is conducting test on non existent milvus/internal/config 
2. In function test_util test is run on non existent directory milvus/internal/util/paramtable and milvus/internal/util/importutil
3. Whenever tests are run on any directories inside milvus/pkg name resolution problem is occurring.

### Expected Behavior

Ideally it should run tests on existing directories and it should be able to run tests inside pkg directory too.

### Steps To Reproduce

```markdown
1. Run the GO unit tests using the steps inside DEVELOPMENT.md
```

**Comment by Ald392** [comment]
Solution:
1. Remove function test_config()
2. Remove the go test of milvus/internal/util/paramtable and milvus/internal/util/importutil from function test_util()
3. Change working directory to milvus/pkg whenever a test is conducted inside milvus/pkg

**Comment by xiaofan-luan** [comment]
/assign @Ald392 
could you issue a pr?
