### ISSUE TITLE
[Bug]: Unable to connect to minio in standalone mode installed in Docker

### ISSUE THREAD

**Issue by yesletgo** [milvus-io/milvus#32265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4.0
- Deployment mode(standalone or cluster):standalone 
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

error="Get " appears http://localhost:9000/a -Bucket/? Location=\“

### Expected Behavior

can connect minio:9000

### Steps To Reproduce

```markdown
I installed it through the following methods:
Wget https://raw.githubusercontent.com/milvus-io/milvus/master/scripts/standalone_embed.sh
Bash standalone embedded. sh start

All are default configurations, so how does mini connect?
Mini:
Address: localhost # Address of MinIO/S3
Port: 9000 # Port of MinIO/S3
AccessKeyID: minioadmin # accessKeyID of MinIO/S3
SecretAccess Key: minioadmin # MinIO/S3 encryption string
UseSSL: false # Access to MinIO/S3 with SSL
BucketName: a-bucket # Bucket name in MinIO/S3
RootPath: files # The root path where the message is stored in MinIO/S3

I also added port mapping, but I couldn't connect.
![image](https://github.com/milvus-io/milvus/assets/21998052/4d99411d-5b57-45b7-9754-c63bb6182431)



```

**Comment by zhuwenxing** [comment]
standalone_embed uses local storage as backend storage, so no minio was installed.
you can follow this link (https://milvus.io/docs/install_standalone-docker-compose.md) to setup

**Comment by yesletgo** [comment]
> standalone_embed uses local storage as backend storage, so no minio was installed. you can follow this link (https://milvus.io/docs/install_standalone-docker-compose.md) to setup

If I just want to use the standalone embedded mode, how do I backup it？

**Comment by yanliang567** [comment]
I'd suggest you not use standalone emedded in this case

> > standalone_embed uses local storage as backend storage, so no minio was installed. you can follow this link (https://milvus.io/docs/install_standalone-docker-compose.md) to setup
> 
> If I just want to use the standalone embedded mode, how do I backup it？

/asign @yesletgo

**Comment by yesletgo** [comment]
> I'd suggest you not use standalone emedded in this case
> 
> > > standalone_embed uses local storage as backend storage, so no minio was installed. you can follow this link (https://milvus.io/docs/install_standalone-docker-compose.md) to setup
> > 
> > 
> > If I just want to use the standalone embedded mode, how do I backup it？
> 
> /asign @yesletgo

Why is it not suitable in this example? Does standalone'embed not require backup, or may I ask how to recover it if there is a malfunction？
