### ISSUE TITLE
[Bug]: Wrong port used to access Pulsar in test files

### ISSUE THREAD

**Issue by Ald392** [milvus-io/milvus#32272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When go tests are conducted inside milvus/pkg/mq/msgstream/mqwrapper/pulsar, following errors are occurring:
<img width="1062" alt="Screenshot 2024-04-15 at 3 12 29 PM" src="https://github.com/milvus-io/milvus/assets/166891594/13c9b40c-ee40-4081-a76b-4beeecaf3594">
<img width="1190" alt="Screenshot 2024-04-15 at 3 59 07 PM" src="https://github.com/milvus-io/milvus/assets/166891594/38afed81-c2af-4365-9aa1-663976416e10">

### Steps To Reproduce

```markdown
1. Run the go test following steps inside DEVELOPMENT.md
```

**Comment by Ald392** [comment]
Reason: Inside https://github.com/milvus-io/milvus/blob/70e3d5b4956e64c82786fe055f98cc5f9204b0ea/deployments/docker/dev/docker-compose.yml#L38
Pulsar containers port 8080 is mapped to localhosts port 18080. But in :
1. https://github.com/milvus-io/milvus/blob/70e3d5b4956e64c82786fe055f98cc5f9204b0ea/pkg/mq/msgstream/mqwrapper/pulsar/pulsar_client_test.go#L753
2. https://github.com/milvus-io/milvus/blob/70e3d5b4956e64c82786fe055f98cc5f9204b0ea/pkg/mq/msgstream/mqwrapper/pulsar/pulsar_consumer_test.go#L185

the new pulsar admin client is giving requests to port 8080 of localhost. 

Solution:
Changing port number to 18080 in both can solve the issue

**Comment by xiaofan-luan** [comment]
that is based on your deployment right?
By default it is 8080 but it's kind like based on your deployment. 

The tricky part here is for pulsarctl, they have two ports 80 and 8080 by default, based on whether you have a proxy deployed

**Comment by xiaofan-luan** [comment]
but 18080 is definitely your internal definition I guess

**Comment by yanliang567** [comment]
/assign @Ald392 
please help to check as comments above.

/unassign

**Comment by Ald392** [comment]
> but 18080 is definitely your internal definition I guess

Port 8080 of pulsar container is forwarded to localhosts port 18080 in the [milvus/deployments/docker/dev/docker-compose.yml](https://github.com/milvus-io/milvus/blob/70e3d5b4956e64c82786fe055f98cc5f9204b0ea/deployments/docker/dev/docker-compose.yml#L38)
Which is the recommended deployment for UT according to https://github.com/milvus-io/milvus/blob/e19d17076f21183883fc8acd648e1a112f8c42fb/DEVELOPMENT.md

So either we have to change the port used to access pulsar in go test files or we have to forward pulsar's 8080 to localhosts 8080 which when i tested was causing some new test failures. Because some other go tests are running on assumption that localhosts 8080 is free. I believe that is the reason for forwarding pulsar to localhosts 18080 in the first place.
So the preferred solution according to me would be to change port used for accessing pulsar in test files to 18080.

**Comment by xiaofan-luan** [comment]
> Port 8080 of pulsar container is forwarded to localhosts port 18080 in the [milvus/deployments/docker/dev/docker-compose.yml](https://github.com/milvus-io/milvus/blob/70e3d5b4956e64c82786fe055f98cc5f9204b0ea/deployments/docker/dev/docker-compose.yml#L38) Which is the recommended deployment for UT according to https://github.com/milvus-io/milvus/blob/e19d17076f21183883fc8acd648e1a112f8c42fb/DEVELOPMENT.md
> 
> So either we have to change the port used to access pulsar in go test files or we have to forward pulsar's 8080 to localhosts 8080 which when i tested was causing some new test failures. Because some other go tests are running on assumption that localhosts 8080 is free. I believe that is the reason for forwarding pulsar to localhosts 18080 in the first place. So the preferred solution according to me would be to change port used for accessing pulsar in test files to 18080.

But I thought not all the user are running with the pod forward? Should it just be changed based on users requirment?
