### ISSUE TITLE
[SDK]: declarative resource group api 

### ISSUE THREAD

**Issue by chyezh** [milvus-io/milvus#32282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Latest milvus server support declarative resource group api.
We need all major SDK to support it.

### Why is this needed?

- Add new parameter `ResourceGroupConfig` into CreateResourceGroup.

- Add new RPC `UpdateResourceGroups`.

- Add new output field in `nodes`, `config` in response of `DescribeResourceGroup`

### Anything else?

Milvus server issue: #30647 
Milvus proto PR:
- https://github.com/milvus-io/milvus-proto/pull/243
- https://github.com/milvus-io/milvus-proto/pull/261

Already supported SDK:

- python: https://github.com/milvus-io/pymilvus/pull/2002
- java v1: https://github.com/milvus-io/milvus-sdk-java/pull/755
- go: https://github.com/milvus-io/milvus-sdk-go/pull/733

@XuanYang-cn @longjiquan @congqixia @yhmo @yelusion2 @shanghaikid @nameczz @czs007

**Comment by chyezh** [comment]
all done

**Comment by xiaofan-luan** [comment]
@chyezh can you go through the document see https://milvus.io/docs/resource_group.md#What-is-a-resource-group good anough?
