### ISSUE TITLE
[Bug]: The backend keeps running under high load

### ISSUE THREAD

**Issue by yesletgo** [milvus-io/milvus#32317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4.0
- Deployment mode(standalone or cluster):standalone embedded
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory:12C/100G 
- GPU: 
- Others:
```

### Current Behavior

The backend keeps running under high load.
![image](https://github.com/milvus-io/milvus/assets/21998052/71339fd0-19f6-47b2-93d0-9340697faec4)

![image](https://github.com/milvus-io/milvus/assets/21998052/d17bcbb3-910a-4fc1-8e1d-901dd83fe128)
![image](https://github.com/milvus-io/milvus/assets/21998052/941781b8-d9e6-462d-b838-eb2642c47adb)

### Expected Behavior

All related backend tasks have been completed, such as establishing indexes.

### Steps To Reproduce

```markdown
1.Create collection
id:Int64
vector:BinaryVector(64)

metric_type:HAMMING
2. Batch insertion of data
totaling 500 million, with each batch costing 100000

3. After all the data is inserted, Long term high load operation in the background, without stopping.
```

### Milvus Log

[milvus-standalone.log](https://github.com/milvus-io/milvus/files/14994068/milvus-standalone.log)
[bw_etcd_ALL.240416-163137.bak.gz](https://github.com/milvus-io/milvus/files/14994069/bw_etcd_ALL.240416-163137.bak.gz)

**Comment by yanliang567** [comment]
@yesletgo according to the etcd backup files, I saw there are many segments pending for building index, which I believe causes high load.
![image](https://github.com/milvus-io/milvus/assets/82361606/ab8da8b2-5c57-4cb9-96e0-5d23788988aa)

/assign @yesletgo 
/unassign
