### ISSUE TITLE
[Bug]: The GPU memory usage is much larger than the actual vector data

### ISSUE THREAD

**Issue by longyxiang** [milvus-io/milvus#32333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.12
- Deployment mode(standalone or cluster):standalone 
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):Go
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: A10
- Others:
```

### Current Behavior

The GPU memory usage is much larger than the actual vector data，512-dimensional vector data

![微信图片_20240416194851](https://github.com/milvus-io/milvus/assets/33796882/79298b35-ccec-4318-afed-36c5a7f36e5b)
![微信图片_20240416194858](https://github.com/milvus-io/milvus/assets/33796882/a656dcc0-71f7-4847-a1ca-984add1f7195)

**Comment by liliu-z** [comment]
Talked offline. This memory is occupied by GPU mem pool. We are working on adding a mem pool usage metrics to help monitor it.

**Comment by liliu-z** [comment]
Another issue to track this : https://github.com/zilliztech/knowhere/issues/507
