### ISSUE TITLE
[Bug]: search方法只能获取138条数据。

### ISSUE THREAD

**Issue by cat-knight** [milvus-io/milvus#32347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

但我使用search方法时，只能获取138条数据。（top-k参数1000）
使用query方法时，query>=0，能够获取全部3100条数据。
![image](https://github.com/milvus-io/milvus/assets/72443535/6c722054-3748-44d4-abe6-c33b60dd3908)

**Comment by cat-knight** [comment]
![image](https://github.com/milvus-io/milvus/assets/72443535/c7a43b2f-1cd2-4e41-a62d-9930fca6a842)

**Comment by cat-knight** [comment]
I just get 138 data by search function.(topk=1000)
I get all data when use query function.

**Comment by xiaofan-luan** [comment]
/assign @liliu-z 
guess it could be the same problem

**Comment by cat-knight** [comment]
I changed the index_type from HNSW to FLAT then the problem has been resolved.

**Comment by liliu-z** [comment]
@cat-knight Can I ask your filter expr?
Also, the param you use to build & search

/assign @PwzXxm 
May be similar to #31658

**Comment by xiaofan-luan** [comment]
> @cat-knight Can I ask your filter expr? Also, the param you use to build & search
> 
> /assign @PwzXxm May be similar to #31658

guess it's similar. Many samilar documents become a isolated island
