### ISSUE TITLE
[Enhancement]: restful v2, support config dbName in the http header

### ISSUE THREAD

**Issue by PowderLi** [milvus-io/milvus#32360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

user want to config the dbName not only in the request body, but also in the http header

**Comment by yiwen92** [comment]
![img_v3_02a1_4594499a-22a6-4c2f-8668-bddba1d0ffeg](https://github.com/milvus-io/milvus/assets/34636520/8e6de296-a177-4803-812c-baeaa2a11410)
Pls apply according to this

**Comment by yiwen92** [comment]
export MILVUS_URI="localhost:19530"

curl --location --request POST "http://${milvus_uri}/v2/vectordb/collections/create" \
--header "Content-Type: application/json" \
--data-raw '{
    "dbName":"default",
    "collectionName": "test_collection",
    "dimension": 5
}'
Now we supported this
-------
curl --location --request POST "http://${milvus_uri}/v2/vectordb/collections/create" \
--header "Content-Type: application/json
                  DB-Name:test_db" \
--data-raw '{
    "collectionName": "custom_quick_setup",
    "dimension": 5
}'
We need to support this, as user-friendly to define a global dbname.
--------
curl --location --request POST "http://${milvus_uri}/v2/vectordb/collections/create" \
--header "Content-Type: application/json
                  DB-Name:test_db" \
--data-raw '{
    "dbName":"default",
    "collectionName": "custom_quick_setup",
    "dimension": 5
}'

If both header and body specific a dbname, then the priority is body > header, so the dbname here is 'default'
