### ISSUE TITLE
[Bug]: Use the Go client to delete the data. After a while, use attu's query interface to query the data. Only part of it was deleted.

### ISSUE THREAD

**Issue by dushulin** [milvus-io/milvus#32369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.2
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2):go sdk v2.3.1
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

some fileds：
![image](https://github.com/milvus-io/milvus/assets/25276301/35f118e1-ca68-41b8-ab1a-83fce8e270e0)
go code（delete func）
![image](https://github.com/milvus-io/milvus/assets/25276301/c5c1fce1-9be3-4959-98dd-b16698e8f21a)
after run this code, no a error info
After a while, use attu's query interface to query the data. Only part of it was deleted.
![image](https://github.com/milvus-io/milvus/assets/25276301/be4990ff-fad3-41ff-b2a6-83187dbf0118)

### Expected Behavior

All entities have been deleted and cannot be queried

**Comment by dushulin** [comment]
When the total amount of data to be deleted is more than 40, this problem will not occur. When the total amount of data is more than 200, this problem will occur.

**Comment by yanliang567** [comment]
/assign @ThreadDao 
please help to reporduce the issue

/unassign

**Comment by dushulin** [comment]
> you can try to set the `consistency_level` param to `Strong` in the delete method

how to call delete method by this param? I did not find api doc

**Comment by dushulin** [comment]
I saw a time traval value mentioned in your document. How long will it take before it will be retrieved by default?

**Comment by SimFG** [comment]
@dushulin maybe the go sdk have not give the param, you can set the collection `consistency_level ` to `strong`, and try to delete the data.

**Comment by dushulin** [comment]
> @dushulin maybe the go sdk have not give the param, you can set the collection `consistency_level ` to `strong`, and try to delete the data.
We need complex expr, so we can only set bounded，can we set consistency_level in query or search function? If not, can you team add this in go sdk?

**Comment by SimFG** [comment]
@congqixia please give this issue a look

**Comment by SimFG** [comment]
@dushulin you can set the `consistency_level` in search and query request
https://github.com/milvus-io/milvus-sdk-go/blob/e697167f1828049c4c6237f0e3646b77b725ebdf/client/options.go#L174-L179

**Comment by dushulin** [comment]
> @dushulin you can set the `consistency_level` in search and query request https://github.com/milvus-io/milvus-sdk-go/blob/e697167f1828049c4c6237f0e3646b77b725ebdf/client/options.go#L174-L179

Are there fields for curl?

**Comment by SimFG** [comment]
here is the client api
```
func (c *GrpcClient) Search(ctx context.Context, collName string, partitions []string,
    expr string, outputFields []string, vectors []entity.Vector, vectorField string, metricType entity.MetricType, topK int, sp entity.SearchParam, opts ...SearchQueryOptionFunc) ([]SearchResult, error) {
```
there is a `SearchQueryOptionFunc` param, it can be use the `WithSearchQueryConsistencyLevel` method to get this param
```
// WithSearchQueryConsistencyLevel specifies consistency level
func WithSearchQueryConsistencyLevel(cl entity.ConsistencyLevel) SearchQueryOptionFunc {
	return func(option *SearchQueryOption) {
		option.ConsistencyLevel = cl
	}
}
```

**Comment by dushulin** [comment]
> here is the client api
> 
> ```
> func (c *GrpcClient) Search(ctx context.Context, collName string, partitions []string,
>     expr string, outputFields []string, vectors []entity.Vector, vectorField string, metricType entity.MetricType, topK int, sp entity.SearchParam, opts ...SearchQueryOptionFunc) ([]SearchResult, error) {
> ```
> 
> there is a `SearchQueryOptionFunc` param, it can be use the `WithSearchQueryConsistencyLevel` method to get this param
> 
> ```
> // WithSearchQueryConsistencyLevel specifies consistency level
> func WithSearchQueryConsistencyLevel(cl entity.ConsistencyLevel) SearchQueryOptionFunc {
> 	return func(option *SearchQueryOption) {
> 		option.ConsistencyLevel = cl
> 	}
> }
> ```

I mean http api param name. ConsistencyLevel=Bounded?

**Comment by SimFG** [comment]
@dushulin you can try to use the attu to delete the data. And the http api currently does not support this parameter.

**Comment by congqixia** [comment]
sorry for the late reply. GoSDK use `strong` only for delete by expr.

**Comment by phlamenco** [comment]
> sorry for the late reply. GoSDK use `strong` only for delete by expr.
current GoSDK delete function does not has a ConsistencyLevel parameter. Do you mean the delete function use strong ConsistencyLevel by default?

**Comment by dushulin** [comment]
信件已收到      【自动回复】

**Comment by dushulin** [comment]
信件已收到      【自动回复】

**Comment by dushulin** [comment]
信件已收到      【自动回复】

**Comment by dushulin** [comment]
信件已收到      【自动回复】

**Comment by dushulin** [comment]
信件已收到      【自动回复】

**Comment by yanliang567** [comment]
close the issue as comments above
