### ISSUE TITLE
[Bug]: Data load from collection results in error 'java.lang.Exception: Fail to describe collection'

### ISSUE THREAD

**Issue by dgoldenberg-ias** [milvus-io/milvus#32388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.4.0-rc.1
- Deployment mode(standalone or cluster): Standalone
- MQ type(rocksmq, pulsar or kafka): Pulsar (?)
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.4.0
- OS(Ubuntu or CentOS): < will find out >
- CPU/Memory: < will find out >
- GPU: < will find out >
- Others: N / A
```

### Current Behavior

When I attempt to load data into a PySpark dataframe, I get the error `java.lang.Exception: Fail to describe collection`. However, the collection does exist on the server (verified programmatically).

### Expected Behavior

The data of the collection should get loaded into the dataframe.

### Steps To Reproduce

```markdown
Code:

from datetime import datetime
from pyspark.sql import SparkSession


from pymilvus import (
   FieldSchema,
   CollectionSchema,
   DataType,
   Collection,
   MilvusClient
)
from pymilvus.milvus_client import IndexParams


columns = ["doc_id", "vector"]
data = [
   ("doc-1", [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0]),
   ("doc-2", [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0]),
   ("doc-3", [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0]),
   ("doc-4", [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0])
]


TEST_ID = datetime.today().strftime("%Y%m%d%H%M%S")
COLLECTION_NAME = f"milvus_spark_test_{TEST_ID}"
NUM_DIMENSIONS = 8


CLUSTER_ENDPOINT = "https://milvus-standalone.alpha.k8s.dev.303net.net:50051"
client = MilvusClient(uri=CLUSTER_ENDPOINT)


field1 = FieldSchema(
   name="doc_id", dtype=DataType.VARCHAR, max_length=32, description="The ID field, prim key",
   is_primary=True, auto_id=False)
field2 = FieldSchema(
   name="vector", dtype=DataType.FLOAT_VECTOR, description="The vector field", dim=NUM_DIMENSIONS,
   is_primary=False)
schema = CollectionSchema(fields=[field1, field2], description="Collection for testing")


index_params = IndexParams()
metric_type = "L2"
index_type = "HNSW"
index_name = f"{COLLECTION_NAME}_idx"
params = {"M": 4, "efConstruction": 200}
index_params.add_index(field_name="vector", metric_type=metric_type, index_type=index_type, index_name=index_name, params=params)


client.create_collection(
   collection_name=COLLECTION_NAME,
   dimension=NUM_DIMENSIONS,
   primary_field_name="doc_id",
   id_type="string",
   vector_field_name="vector",
   metric_type=metric_type,
   auto_id=False,
   timeout=None,
   schema=schema,
   index_params=index_params
)
print()
print(f">> Created test collection '{COLLECTION_NAME}'.")


spark = SparkSession.builder.appName("Milvus-Spark-Connector-Demo").getOrCreate()
sample_df = spark.sparkContext.parallelize(data).toDF(columns)

for row in data:
   client.upsert(COLLECTION_NAME, {"doc_id": row[0], "vector": row[1]})


# -- Read data from Milvus using the Spark connector --
df = spark.read.format("milvus") \
   .option("milvus.host", "milvus-standalone.alpha.k8s.dev.303net.net") \
   .option("milvus.port", "50051") \
   .option("milvus.collection.name", COLLECTION_NAME) \
   .option("milvus.collection.vectorField", "vector") \
   .option("milvus.collection.vectorDim", str(NUM_DIMENSIONS)) \
   .option("milvus.collection.primaryKeyField", "doc_id") \
   .load() \
   .select("doc_id", "vector")

df.show(n=20, truncate=False)
```
```


### Milvus Log

_No response_

### Anything else?

Might this be an HTTP vs HTTPS error? `milvus.host` doesn't let me specify the protocol.

**Comment by xiaofan-luan** [comment]
> Fail to describe collection

could you offer full client side message and also server side log?
We can't see any details in the error message you offered

**Comment by dgoldenberg-ias** [comment]
Hi @xiaofan-luan, below please find the client-side stack trace.  I'll see if I can get a server-side log.

```
java.lang.Exception: Fail to describe collection
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
File <command-3658777111610979>, line 88
     78     client.upsert(COLLECTION_NAME, {"doc_id": row[0], "vector": row[1]})
     80 # -- Read data from Milvus using the Spark connector --
     81 df = spark.read.format("milvus") \
     82     .option("milvus.host", "milvus-standalone.alpha.k8s.dev.303net.net") \
     83     .option("milvus.port", "50051") \
     84     .option("milvus.collection.name", COLLECTION_NAME) \
     85     .option("milvus.collection.vectorField", "vector") \
     86     .option("milvus.collection.vectorDim", str(NUM_DIMENSIONS)) \
     87     .option("milvus.collection.primaryKeyField", "doc_id") \
---> 88     .load() \
     89     .select("doc_id", "vector")
     91 df.show(n=20, truncate=False)

File /databricks/spark/python/pyspark/instrumentation_utils.py:48, in _wrap_function.<locals>.wrapper(*args, **kwargs)
     46 start = time.perf_counter()
     47 try:
---> 48     res = func(*args, **kwargs)
     49     logger.log_success(
     50         module_name, class_name, function_name, time.perf_counter() - start, signature
     51     )
     52     return res

File /databricks/spark/python/pyspark/sql/readwriter.py:314, in DataFrameReader.load(self, path, format, schema, **options)
    312     return self._df(self._jreader.load(self._spark._sc._jvm.PythonUtils.toSeq(path)))
    313 else:
--> 314     return self._df(self._jreader.load())

File /databricks/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py:1355, in JavaMember.__call__(self, *args)
   1349 command = proto.CALL_COMMAND_NAME +\
   1350     self.command_header +\
   1351     args_command +\
   1352     proto.END_COMMAND_PART
   1354 answer = self.gateway_client.send_command(command)
-> 1355 return_value = get_return_value(
   1356    answer, self.gateway_client, self.target_id, self.name)
   1358 for temp_arg in temp_args:
   1359     if hasattr(temp_arg, "_detach"):

File /databricks/spark/python/pyspark/errors/exceptions/captured.py:188, in capture_sql_exception.<locals>.deco(*a, **kw)
    186 def deco(*a: Any, **kw: Any) -> Any:
    187     try:
--> 188         return f(*a, **kw)
    189     except Py4JJavaError as e:
    190         converted = convert_exception(e.java_exception)

File /databricks/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py:326, in get_return_value(answer, gateway_client, target_id, name)
    324 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325 if answer[1] == REFERENCE_TYPE:
--> 326     raise Py4JJavaError(
    327         "An error occurred while calling {0}{1}{2}.\n".
    328         format(target_id, ".", name), value)
    329 else:
    330     raise Py4JError(
    331         "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
    332         format(target_id, ".", name, value))

Py4JJavaError: An error occurred while calling o943.load.
: java.lang.Exception: Fail to describe collection
	at zilliztech.spark.milvus.MilvusCollection.initCollectionMeta(MilvusCollection.scala:57)
	at zilliztech.spark.milvus.MilvusCollection.milvusCollectionMeta$lzycompute(MilvusCollection.scala:22)
	at zilliztech.spark.milvus.MilvusCollection.milvusCollectionMeta(MilvusCollection.scala:22)
	at zilliztech.spark.milvus.MilvusCollection.collectionSchema$lzycompute(MilvusCollection.scala:24)
	at zilliztech.spark.milvus.MilvusCollection.collectionSchema(MilvusCollection.scala:24)
	at zilliztech.spark.milvus.MilvusCollection.schema(MilvusCollection.scala:35)
	at zilliztech.spark.milvus.Milvus.inferSchema(Milvus.scala:127)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Utils$.getTableFromProvider(DataSourceV2Utils.scala:91)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Utils$.loadV2Source(DataSourceV2Utils.scala:138)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$1(DataFrameReader.scala:333)
	at scala.Option.flatMap(Option.scala:271)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:331)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:226)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:397)
	at py4j.Gateway.invoke(Gateway.java:306)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:199)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:119)
	at java.lang.Thread.run(Thread.java:750)
Caused by: io.grpc.StatusRuntimeException: INTERNAL: http2 exception
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
	at io.milvus.grpc.MilvusServiceGrpc$MilvusServiceBlockingStub.describeCollection(MilvusServiceGrpc.java:4421)
	at io.milvus.client.AbstractMilvusGrpcClient.describeCollection(AbstractMilvusGrpcClient.java:691)
	at io.milvus.client.MilvusServiceClient.lambda$describeCollection$9(MilvusServiceClient.java:343)
	at io.milvus.client.MilvusServiceClient.retry(MilvusServiceClient.java:259)
	at io.milvus.client.MilvusServiceClient.describeCollection(MilvusServiceClient.java:343)
	at zilliztech.spark.milvus.MilvusCollection.initCollectionMeta(MilvusCollection.scala:54)
	... 24 more
Caused by: io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:109)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.verifyFirstFrameIsSettings(Http2ConnectionHandler.java:353)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:247)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:453)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
```

**Comment by dgoldenberg-ias** [comment]
@xiaofan-luan this is something about HTTP vs HTTP2.
These seem similar:
https://github.com/grpc/grpc-java/issues/2905
https://stackoverflow.com/questions/73331402/grpc-client-http2exception-first-received-frame-was-not-settings-hex-dump-fo

Any idea?

The server-side logs are clean, no errors.

[serverside-logs-last-50-lines.txt](https://github.com/milvus-io/milvus/files/15017743/serverside-logs-last-50-lines.txt)

[serverside-logs.txt](https://github.com/milvus-io/milvus/files/15017744/serverside-logs.txt)

**Comment by yanliang567** [comment]
/assign @dgoldenberg-ias 
please share some info about how you config tls or deploy milvus?
/unassign

**Comment by yhmo** [comment]
Why the "milvus.port" is "50051"?
Is the 50051 mapped from 19530 of Milvus?

**Comment by dgoldenberg-ias** [comment]
Hi, responding to your comments, @yanliang567, @yhmo:

1. We did not configure TLS or do anything explicit related to it.
2. Regarding the ports, here's the explanation from our devops:

> 50051 is the default port for grpc client
we’re forwarding it to 19530
We restrict 19530 port from the client side

Note that 50051 works from the client side generally, when using pymilvus, e.g. the `MilvusClient`.
3. How the standalone Milvus is currently configured - I'm attaching the values yaml file with all the settings.

Generally, I think there may be a classpath issue whereby grpc is getting http1 dependency jars loaded ahead of http2 dependencies. Can you provide a list of http2 dependencies you think should be there? or http1 jars we could check for on the classpath?

Of note, the code is running as a python notebook in Databricks, with the spark_milvus_1_0_0_SNAPSHOT.jar installed into the Libraries of the Spark cluster.

[milvus_standalone_configs.txt](https://github.com/milvus-io/milvus/files/15042523/milvus_standalone_configs.txt)

**Comment by xiaofan-luan** [comment]
try lastest 2.3.5 might help you since we upgrade grpc and netty version

**Comment by dgoldenberg-ias** [comment]
I think you mean upgrading to 2.4.0, right? We're actually on 2.3.12, just checked.

**-- Side note --**
I've re-run my test on `Databricks 12.2 LTS (includes Apache Spark 3.3.2, Scala 2.12)` which is Spark 3.3.2; that's the version your Spark connector is built for. Spark is all the way up to 3.5.1 now.  Databricks supports Spark up to 3.5.0.

I get the same error, with Spark 3.3.2.  Just thinking that you may want to build the connector for various Spark versions. Maybe upgrade the code to latest Spark.  Spark API's have changed.  For instance, if I do:

```
        <!-- <spark.version>3.3.2</spark.version> -->
        <spark.version>3.4.1</spark.version>
```
I get a build error:
```
[ERROR] /Users/dgoldenberg/tech/milvus/spark-milvus/src/main/java/org/apache/spark/sql/execution/datasources/parquet/MVectorizedParquetRecordReader.java:[268,43] incompatible types: org.apache.spark.sql.execution.vectorized.WritableColumnVector cannot be converted to org.apache.spark.sql.execution.vectorized.ConstantColumnVector
```

**Comment by dgoldenberg-ias** [comment]
Not sure how this is applicable. We're developing using Python. We're using PyMilvus 2.4.0.

How/where would the Milvus Java SDK come into the picture?

**Comment by xiaofan-luan** [comment]
<img width="785" alt="image" src="https://github.com/milvus-io/milvus/assets/83447078/d51e4ec9-a47a-4e89-af3b-eea1f19c2615">
but the error message seems to be from java connector?

**Comment by xiaofan-luan** [comment]
seems that spark connector is using java connector.
could you try to ping your milvus cluster from spark cluster and check if network is avalaible?

**Comment by dgoldenberg-ias** [comment]
> seems that spark connector is using java connector.

Milvus' Spark connector is written in Java. There is no _Spark connector using Java connector_. There is one JAR which is the Milvus Spark connector, it's in Java, therefore the Java stack trace.

> could you try to ping your milvus cluster from spark cluster and check if network is avalaible?

We don't need to do that. Look at the code. As you can see, we first establish a connection with Milvus using the pymilvus MilvusClient, we then create a collection, and feed several documents to it. All of that succeeds.  That means that **network is totally fine**, the port is absolutely correct, and Milvus Standalone is working.

Let's establish that and get past these points, please.

What's not working is the Spark connector. My guess is that there is some classpath issue where HTTP1 dependency libraries are being loaded instead of HTTP2.

**Comment by xiaofan-luan** [comment]
https://github.com/grpc/grpc-java/issues/2905 this might be the issue?

**Comment by dgoldenberg-ias** [comment]
Hi @xiaofan-luan, I don't know if that is "the issue".  It seems to me that at least for the Milvus Spark connector, HTTP2 is expected. Is that true? This doesn't seem to be documented but seems likely.  Then it'd follow that we need to enable TLS.

There is no mention of it in https://milvus.io/docs/integrate_with_spark.md.

I'm thinking we'd then want to follow https://milvus.io/docs/tls.md.

If this is what's happening, I think it'd be definitely worth mentioning in the Spark-Milvus Connector User Guide.

**Comment by xiaofan-luan** [comment]
so far, I don't see the spark connector itself has any tls support.

Java SDK do has -> [withCaPemPath](https://github.com/milvus-io/milvus-sdk-java/blob/master/examples/main/java/io/milvus/TLSExample.java)

If you can help on contributing one that would be great https://github.com/zilliztech/spark-milvus

**Comment by xiaofan-luan** [comment]
Should be very simple to do so.

**Comment by xiaofan-luan** [comment]
> Hmm. If something is missing in the connector, how was it released? It seems to me the issue is that the connector just requires TLS to be installed in Milvus, otherwise it doesn't work. Was going to test that theory.

client need to config all the TLS params. by default there is not TLS on java sdk  https://github.com/milvus-io/milvus-sdk-java/blob/master/examples/main/java/io/milvus/TLSExample.java

you will need to setup TLS from config

**Comment by dgoldenberg-ias** [comment]
So then that's the issue, the Milvus Spark connector doc doesn't let you know that it needs TLS installed.

Since we're not developing in Java, I'm looking at TLSExample.java as well as these:
https://github.com/milvus-io/pymilvus/blob/master/examples/example_tls1.py
https://github.com/milvus-io/pymilvus/blob/master/examples/example_tls2.py

How and where would these examples apply to the Spark connector?

How does the below code need to change in order to involve TLS?
```
df = spark.read.format("milvus") \
   .option("milvus.host", "milvus-standalone.alpha.k8s.dev.303net.net") \
   .option("milvus.port", "50051") \
   .option("milvus.collection.name", COLLECTION_NAME) \
   .option("milvus.collection.vectorField", "vector") \
   .option("milvus.collection.vectorDim", str(NUM_DIMENSIONS)) \
   .option("milvus.collection.primaryKeyField", "doc_id") \
   .load() \
   .select("doc_id", "vector")
```

I don't see anything relevant in `zilliztech/spark/milvus/MilvusOptions.scala` where these options are defined.

**Comment by xiaofan-luan** [comment]
> So then that's the issue, the Milvus Spark connector doc doesn't let you know that it needs TLS installed?
> 
> Since we're not developing in Java, I'm looking at TLSExample.java as well as these: https://github.com/milvus-io/pymilvus/blob/master/examples/example_tls1.py https://github.com/milvus-io/pymilvus/blob/master/examples/example_tls2.py
> 
> How and where would these examples apply to the Spark connector?
> 
> How does the below code need to change in order to involve TLS?
> 
> ```
> df = spark.read.format("milvus") \
>    .option("milvus.host", "milvus-standalone.alpha.k8s.dev.303net.net") \
>    .option("milvus.port", "50051") \
>    .option("milvus.collection.name", COLLECTION_NAME) \
>    .option("milvus.collection.vectorField", "vector") \
>    .option("milvus.collection.vectorDim", str(NUM_DIMENSIONS)) \
>    .option("milvus.collection.primaryKeyField", "doc_id") \
>    .load() \
>    .select("doc_id", "vector")
> ```
> 
> I don't see anything relevant in `zilliztech/spark/milvus/MilvusOptions.scala` where these options are defined.

yes, you will need to implement it by yourself. currently spark connctor doens't support TLS

**Comment by dgoldenberg-ias** [comment]
Are you proposing that I change the connector to support TLS? But a) I'm not a committer, why don't you assign it to an available committer then and b) how does this connector work if it's currently not able to do anything because it doesn't support TLS?

**Comment by dgoldenberg-ias** [comment]
Can you explain this to me because I do not understand:

1. Are you confirming that the Milvus Spark Connector requires TLS, period, whether the server has it enabled or not?
2. If # 1 is true, would you then agree that the Connector was released untested and is simply not working?
3. If it's not in a working condition, why would we file an enhancement request whereas it's really a bug that needs to get fixed?

"A software bug is an error, flaw or [fault](https://en.wikipedia.org/wiki/Fault_(technology)) in the design, development, or operation of [computer software](https://en.wikipedia.org/wiki/Computer_software) that causes it to produce an incorrect or unexpected result, or to behave in unintended ways."

If it is indeed true that it was released untested and not in a working condition, the lack of TLS support needs to be fixed as a bug.  I also further do not understand why you're assigning it to me to fix.

**Comment by xiaofan-luan** [comment]
and if take a look at similar issue, it says the reason is wrong port forwarding
 https://github.com/grpc/grpc-java/issues/2905

**Comment by xiaofan-luan** [comment]
tls is just my guess, you need to check all the configs. Or at least offer all the server side logs, configs and spark logs if you need our help to check.

**Comment by xiaofan-luan** [comment]
And this seems to be the answer https://github.com/grpc/grpc-java/issues/7236

Quote"
I we look at the error, Hex dump for first 5 bytes: 485454502f, we can convert the hex "485454502f" to ASCII, which becomes "HTTP/". So the server is trying to speak HTTP/1.

It seems like you are using an L7 (HTTP) proxy when connecting from local to AKS. You may check to see if it has an "assume HTTP/2" mode for plain-text. You may also check for an L4 (TCP) proxy mode."
