### ISSUE TITLE
Exception message need to be fixed

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#3240]
**Please state you issue using the following template and, most importantly, in English.**

**Describe the bug**
```
test_index.py::TestIndexBase::test_create_index_collection_not_existed 
-------------------------------- live log call ---------------------------------
[2020-08-12 07:11:39-ERROR-milvus.client.grpc_handler]: Error: <BaseException: (code=1, message=Snapshots::GetHolderNoLock: Specified snapshot holder for collection "index_uVt72UVu" not found)> (grpc_handler.py:44)

```
**Steps/Code to reproduce behavior**
1. create index on collection which is not created before

**Expected behavior**
The expected message returned should be clear, for example, instead of the above message returned, may be "Collection not found" is more acceptable.

**Environment details**
master-branch

**Screenshots**

**Additional context**

**Comment by scsven** [comment]
fixed
