### ISSUE TITLE
[Bug]: [restful v2]The search api does not support nq>2. It can only return the top k results for a single query when nq > 1.

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#32419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master/2.4
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The search api does not support nq>2. It can only return the top k results for a single query when nq > 1.

**Comment by PowderLi** [comment]
whatever how many nq in the http request's Data, milvus restful server only send one SearchRequest to grpc server, and return the SearchResults
need i do some extra things with the SearchRequest & SearchResults
/assign @czs007 

|where|what|nqs|topk|
|--|--|--|--|
|http client|send http request|Data|Limit|
|milvus restful server|transfer to grpc search params|PlaceholderGroup|SearchParams|
|milvus grpc server|return SearchResultData|[]*FieldData|TopK|

**Comment by zhuwenxing** [comment]
verified and fixed.
test cases added to ci and passed https://github.com/milvus-io/milvus/pull/33456

but all results were also flattened as https://github.com/milvus-io/milvus/issues/32420
