### ISSUE TITLE
[Enhancement]: row-based import, only allow one JSON file each time

### ISSUE THREAD

**Issue by UshaPravinkumar** [milvus-io/milvus#32434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Hello,

When attempting to import multiple files using the row-based approach, I encounter an error message: "io.milvus.exception.ServerException: row-based import, only allow one JSON file each time."

How can I accomplish bulk insertion using the row-based method?

`List<String> fileList = new ArrayList<>();
            fileList.add("a-bucket/2022/Data_1.json");
            fileList.add("a-bucket/2022/Data_2.json");
            util.bulkInsert(collectionName, fileList);`

**Comment by xiaofan-luan** [comment]
we support only one json file to be imported each time.

this could be improved in 2.4 already.

**Comment by UshaPravinkumar** [comment]
> we support only one json file to be imported each time.
> 
> this could be improved in 2.4 already.

io.milvus:milvus-sdk-java:jar:2.4.0 was not found
When the latest version (or 2.4.0) will be publicly available for use?

**Comment by UshaPravinkumar** [comment]
Hello,
I attempted bulk insertion of multiple files using version 2.4.1, yet the problem persists unchanged.

**Comment by xiaofan-luan** [comment]
/assign @bigsheeper 
 bigsheeper is working on this

**Comment by bigsheeper** [comment]
> Hello, I attempted bulk insertion of multiple files using version 2.4.1, yet the problem persists unchanged.

Hello @UshaPravinkumar , version 2.4.x introduces RESTful API to enable importing multiple files in a single request. You can find more information in the documentation: [RESTful API Documentation](https://milvus.io/api-reference/restful/v2.4.x/v2/Import%20(v2)/Create.md).

**Comment by UshaPravinkumar** [comment]
> > Hello, I attempted bulk insertion of multiple files using version 2.4.1, yet the problem persists unchanged.
> 
> Hello @UshaPravinkumar , version 2.4.x introduces RESTful API to enable importing multiple files in a single request. You can find more information in the documentation: [RESTful API Documentation](https://milvus.io/api-reference/restful/v2.4.x/v2/Import%20(v2)/Create.md).

Let me try that, thanks.
