### ISSUE TITLE
[Bug]: GPU_BRUTE_FORCE Index Milvus Search error

### ISSUE THREAD

**Issue by longyxiang** [milvus-io/milvus#32442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4
- Deployment mode(standalone or cluster):standalone 
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 500G
- GPU: A10 24G
- Others:
```

### Current Behavior

![微信图片_20240418211713](https://github.com/milvus-io/milvus/assets/33796882/49179052-e3a1-472a-b4e2-d8aa44f25f19)

The actual size of the vector data is 100G, and the GPU memory is 144G. However, an abnormality occurred during retrieval, and Milvus error.

**Comment by Presburger** [comment]
fixed
