### ISSUE TITLE
[Bug]: falled to query: node offline

### ISSUE THREAD

**Issue by rh01** [milvus-io/milvus#32456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.0-rc.1
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 1000/1T
- GPU: 
- Others:
```

### Current Behavior

The issue we are currently facing is that when deleting an empty search result, the deletion process gets stuck, causing problems with the cluster. As a result, the cluster is no longer able to perform queries properly in this collection.

```
MilvusException: <MilvusException: (code=503, message=failed to query: node offline[node=77]; node offline[node=77]; segment lacks[segment=448778450427470574]: channel not available[channel=milvus04-rootcoord-dml_1_448670693629703498v0])>
```

![image](https://github.com/milvus-io/milvus/assets/10126374/857ad381-a06f-45d3-a988-f6180c61144b)

### Milvus Log

[logs.tar.gz](https://github.com/milvus-io/milvus/files/15033524/logs.tar.gz)

**Comment by czs007** [comment]
@rh01 we are investing it.

**Comment by xiaofan-luan** [comment]
is there some logs about it?

**Comment by xiaofan-luan** [comment]
might be something fixed already. I know several issue about segment allocaton
