### ISSUE TITLE
[Bug]: Docker arm64 image milvusdb/milvus:v2.4.0: symbol lookup error

### ISSUE THREAD

**Issue by shivabohemian** [milvus-io/milvus#32474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
v2.4.0 (milvusdb/milvus:v2.4.0 arm64)
- Deployment mode(standalone or cluster):
standalone
- MQ type(rocksmq, pulsar or kafka):    
rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I enter the container and execute the binary /milvus/bin/milvus, there is a symbol lookup error, as follows:
```
root@5c73282fdd5a:/milvus/bin# ./milvus
./milvus: symbol lookup error: /milvus/lib/libmilvus_segcore.so: undefined symbol: _ZN6milvus6bitset6detail3arm3sve18OpArithCompareImplIlLNS0_11ArithOpTypeE0ELNS0_13CompareOpTypeE1EE16op_arith_compareEPhPKlRS9_SB_m
```

**Comment by alexanderguzhva** [comment]
I see this behavior with a `milvusdb/milvus:v2.4.0` docker container. 
And I don't see such an error if I compile milvus on my own on AMD64 machine (GCC 11.4 compiler).

**Comment by alexanderguzhva** [comment]
I can reproduce the problem if milvus gets compiled inside a fresh Ubuntu 20.04 for arm64 using the default gcc (9.4.0)

**Comment by alexanderguzhva** [comment]
#32464 
#32463

**Comment by BadMask121** [comment]
Currently facing the same issue, and also previous version of milvus standalone docker version v2.3.0  that was working for me stopped working

**Comment by stephen37** [comment]
Got the same error when upgrading with `helm` on my K8s cluster, it was working for 2.3.x and stopped working for `2.4.x`.

**Comment by shivabohemian** [comment]
So, do we need to re-release the Docker image for version 2.4.0, or should we address the issue in the next version's image?

**Comment by JAlexMcGraw** [comment]
+1 facing this issue. Cannot build milvus-standalone from the [docker compose quickstart docs](https://milvus.io/docs/install_standalone-docker-compose.md)

**Comment by xiaofan-luan** [comment]
@alexanderguzhva  @zhagnlu 
how is the fix going on?

**Comment by zhagnlu** [comment]
> @alexanderguzhva @zhagnlu how is the fix going on?

https://github.com/milvus-io/milvus/pull/32464  fixed it, devops are updating new image, wait for newest image

**Comment by Sayanc2000** [comment]
How do I install a previous version of milvis standalone with helm in the meanwhile

**Comment by stephen37** [comment]
> How do I install a previous version of milvis standalone with helm in the meanwhile
If you were using Helm already before, you can rollback with `helm rollback <name>` 

If you hadn't, then you can specify the version by modifying the manifest. 
1. `helm show values milvus/milvus > milvus_helm.yaml`
2. Open `milvus_helm.yaml` with your usual editor
3. In the image section, replace the tag with `v2.4.0` with another one, for example `v2.3.14`
```
image:
  all:
    repository: milvusdb/milvus
    tag: v2.3.14
```
4. Upgrade your Milvus installation with ` helm upgrade --install --values milvus_helm.yaml <name> milvus/milvus`

**Comment by bharti26** [comment]
I'm facing same issue but getting to previous version worked.

**Comment by weiyi88** [comment]
i have same problem on this , by use docker or docker-compose

**Comment by liliu-z** [comment]
Hi, the image is updated. Plz feel free to take a try

**Comment by shivabohemian** [comment]
I did a simple test, the problem has been fixed, thanks to the team's work.
