### ISSUE TITLE
[Bug]: ARM64 compilation problems

### ISSUE THREAD

**Issue by alexanderguzhva** [milvus-io/milvus#32476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.0
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others: ARM
```

### Current Behavior

* `scripts/install_deps.sh` downloads cmake for x86 despite being run on ARM.

* `scripts/install_deps.sh` does not install blas (`libopenblas-dev` is needed)

* 'build/builder.sh make' fails with 
```
ubuntu@ip-172-31-1-23:~/milvus$ build/builder.sh make
~/milvus ~/milvus
Pulling builder ... done
Creating milvus_builder_run ... done
exec /entrypoint.sh: exec format error
```

### Expected Behavior

no compilation problems

**Comment by yanliang567** [comment]
@alexanderguzhva are you going to make a pr for it?
/assign @alexanderguzhva

**Comment by alexanderguzhva** [comment]
well, let me try, at least
