### ISSUE TITLE
Milvus reports that the number of rows in the collection is fewer than the number of ingested rows.

### ISSUE THREAD

**Issue by jobbine-joseph** [milvus-io/milvus#32500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode: Cluster 
- MQ type: Kafka  
- SDK version: pymilvus 2.4.0
- OS(Ubuntu or CentOS): UBI9 
- CPU/Memory: 
- GPU: 0
- Others: 
{
"rc_cpu": "1", "rc_memory": "2Gi",
                "qc_cpu": "500m", "qc_memory": "500Mi",
                "dc_cpu": "500m", "dc_memory": "500Mi",
                "proxy_cpu": "1", "proxy_memory": "4Gi",
                "qw_cpu": "4", "qw_memory": "16Gi", "qw_replicas": "3",
                "dw_cpu": "2", "dw_memory": "8Gi", "dw_replicas": "1",
                "iw_cpu": "6", "iw_memory": "16Gi", "iw_replicas": "2",
                "iw_nodetype": "bx2.32x128", "qw_nodetype": "bx2.32x128",
                "etcd_cpu": "200m", "etcd_mem": "3800Mi", "etcd_nodetype": "bx2.2x8", "milvus_nodetype": "bx2.32x128",
                "topics": "8",
}
```

### Current Behavior

When inserting a large volume of vectors, such as 5 million, into a Milvus collection, it has been observed that the final count of rows in the collection may be less than the number initially inserted. For instance, in a test involving the insertion of 5 million rows into a small Milvus collection, the resulting count indicated a discrepancy.

### Expected Behavior

In an optimal scenario, when inserting a large volume of vectors into a Milvus collection, such as 5 million, the expected behavior is that the final count of rows in the collection accurately reflects the number of vectors inserted. Thus, after inserting 5 million rows, the collection should precisely report a total of 5 million rows.

### Steps To Reproduce

```markdown
1 . Create a New Collection - Begin by establishing a new collection.
2 . Ingest 5 Million Rows - Proceed to ingest 5 million rows into the Milvus collection. For each batch processed, confirm that the "insert" API call completes successfully and that the number of rows reported as ingested matches the batch size.
3 . Flush the Collection - Flush the collection to seal all segments and solidify the data structure.
4 . Count the Rows - After flushing, count the rows in the collection. It has been noted that the total number of rows can be significantly lower than the number initially inserted.
```

### Anything else?

During tests with 4 million inserts using the Batch Insert API, Milvus accurately captures and reports all 4 million rows. However, when the number of inserts increases to 5 million, discrepancies in the reported counts are observed. For instance, the system reported counts of 3,812,750; 3,955,250; and 3,883,250, indicating missing data.

Notably, these discrepancies appear to involve contiguous blocks of rows. In a test involving approximately 7 million vectors, rows ranging from ID 2,989,250 to ID 4,106,000 were absent, while all other rows, both before and after this range, were accurately recorded. It's important to mention that rows were inserted sequentially according to their IDs, in batches of 750.

Additionally, introducing a one millisecond delay between each insert appears to mitigate the issue, as inserting even up to 7 million rows with this delay results in accurate data capture and reporting.

**Comment by yanliang567** [comment]
@jobbine-joseph quick questions
1. what is the version of your milvus and pymilvus
2. how do you observe the number of entities in Milvus
3. Did you try to manually call collection.flush() after all insert requests done
4. Did you receive any error during the insertion?
5. Could you please attach the etcd backup for investigation？ Check this: https://github.com/milvus-io/birdwatcher for details about how to backup etcd with birdwatcher

/assign @jobbine-joseph

**Comment by jobbine-joseph** [comment]
what is the version of your milvus and pymilvus.   ----> milvusv2.3.5.   pymilvus 2.4.0
how do you observe the number of entities in Milvus. -----> Collection('my_collection').query('', ['count(*)'])
Did you try to manually call collection.flush() after all insert requests done ----> yes
Did you receive any error during the insertion? ------> No

**Comment by yanliang567** [comment]
did you have any upsert or delete requests?
please offer the birdwatcher etcd backup and full milvus logs for investigation. thanks.

**Comment by yanliang567** [comment]
also please offer the full milvus pods logs, thanks
