### ISSUE TITLE
Memory footprint of milvus is not matching with sizing tool recommendations

### ISSUE THREAD

**Issue by suvashishtha** [milvus-io/milvus#3250]
**Describe the bug**
Memory footprint of milvus is not matching with what is being provided by sizing tool. Sizing tool says that to store 4M float vectors of 128 dimmension, it would require 586MB of memory and 2540 MB of disk space with vector type IVFSQ8
![image](https://user-images.githubusercontent.com/26629872/90133197-58d9d280-dd6f-11ea-9318-6a5e485b41c0.png)

**Steps/Code to reproduce behavior**
- create a table with following specifications
     - No. of records - 4M
     - Dimmension  - 128
    - IndexType - IVFSQ8
- make a search query so that index is loaded in memory
- check memory footprint from either grafana/docker stats <container>

**Expected behavior**
memory should be 586MB. instead it's occupying 2.5G

**Environment details**
- Hardware/Softward conditions: MacOS 16G RAM
- Method of installation - docker (6G allocated to docker)
- Milvus version - v0.10.1
- Milvus configuration - Index file size is 2G

**Screenshots**
![image](https://user-images.githubusercontent.com/26629872/90133593-08af4000-dd70-11ea-9fd5-7320e7f6ef3d.png)
![image](https://user-images.githubusercontent.com/26629872/90133650-254b7800-dd70-11ea-8f76-61f3ad9dd56e.png)

Looks like both raw file and index file is loaded in memory. Is it intended behaviour? Or is there a way to only load index files in memory?
However, on restarting container memory footprint looks correct. Now memory is approx 600MB

**Comment by suvashishtha** [comment]
@shengjun1985 
my cache size was 4G. All the data was in cache since it was big enough to hold data. i think it's all fine. what do you think?

**Comment by yhmo** [comment]
4M 128 dimensional vectors data size is 2GB, IVFSQ8 index is about 600MB.
Milvus cache strategy is LRU, assume you specify cache limit = 5GB. 
1. Now you insert 4M 128d vectors, disk cost is 2GB. 
2. If you perform a search action, the 2GB raw data will be loaded into cache, cache occupation is 2GB. 
3. The you build IVFSQ8 index, disk cost = 2GB+600MB = 2.6GB. 
4. If you perform a search action, the index file will be loaded into cache, cache occupation is 2.6GB, since the cache size is less than 5GB, milvus will not evict raw data from memory

**Comment by yhmo** [comment]
If you skip the step 2, then build index and search, the cache occupation will be 600MB.

**Comment by suvashishtha** [comment]
After performing step 1, memory footprint is approx 2 GB. However, it does not increase if I add another 4M vectors.

**Comment by yhmo** [comment]
Use this python script to observe milvus memory cost during inserting:

```
import sys, getopt
import struct
import time
import random
import string
import os
import re
import psutil
import json
import numpy as np
from milvus import Milvus, IndexType, Status
from milvus.client.types import MetricType

SERVER_ADDR = "127.0.0.1"
SERVER_PORT = '19530'
TABLE_NAME = "TEST"
TABLE_DIMENSION = 128
TABLE_PARAM = {'collection_name': TABLE_NAME, 'dimension': TABLE_DIMENSION, 'index_file_size': 1000, 'metric_type':MetricType.L2}

MILVUS = Milvus(host=SERVER_ADDR, port=SERVER_PORT)

def print_memory():
    program_name = "milvus_server"
    order_str = "ps x | grep %s" % program_name
    strs_obj = os.popen(order_str)
    t_strs = strs_obj.read()
    pid_list = re.findall(r"(\d+).+server_config.yaml", t_strs, re.I)
    # process = psutil.Process(os.getpid())
    process = psutil.Process(int(pid_list[0]))
    used = process.memory_info().rss / 1024 / 1024
    print(program_name, 'used memory:', used, 'MB')
    return used

def gen_vec_list(nb, seed=np.random.RandomState(1234)):
    xb = seed.rand(nb, TABLE_DIMENSION).astype("float32")
    vec_list = xb.tolist()
    return vec_list


def main(argv):
    status = MILVUS.create_collection(TABLE_PARAM)
    print(status)

    print('========= Begin Insert =========')
    print_memory()
    time_start = time.time()
    for i in range(400):
        vec_list = gen_vec_list(10000, seed=np.random.RandomState(i + 13))
        status, ids = MILVUS.insert(collection_name=TABLE_NAME, records=vec_list)

    time_end = time.time()
    print("insert vectors:", len(vec_list), " time cost:", time_end - time_start, 'sec')
    print_memory()
    print('========= End Insert =========')

if __name__ == "__main__":
    main(sys.argv[1:])
```

**Comment by yhmo** [comment]
Run the script 3 times on my machine, the result is:

```
➜  python3 ./insert_mem_cost.py               
error_code: ILLEGAL_COLLECTION_NAME
reason: "Collection already exists"

Status(code=9, message='Collection already exists')
========= Begin Insert =========
milvus_server used memory: 476.5390625 MB
insert vectors: 10000  time cost: 61.27790570259094 sec
milvus_server used memory: 611.14453125 MB
========= End Insert =========
➜  python3 ./insert_mem_cost.py
error_code: ILLEGAL_COLLECTION_NAME
reason: "Collection already exists"

Status(code=9, message='Collection already exists')
========= Begin Insert =========
milvus_server used memory: 484.30859375 MB
insert vectors: 10000  time cost: 68.75018334388733 sec
milvus_server used memory: 979.28125 MB
========= End Insert =========
 ➜  python3 ./insert_mem_cost.py
error_code: ILLEGAL_COLLECTION_NAME
reason: "Collection already exists"

Status(code=9, message='Collection already exists')
========= Begin Insert =========
milvus_server used memory: 489.9609375 MB
insert vectors: 10000  time cost: 55.54802751541138 sec
milvus_server used memory: 1417.40625 MB
========= End Insert =========

```

**Comment by yhmo** [comment]
We can see after insert, memory increased(no more than 1GB), but the memory cost will be freed after a while.

**Comment by suvashishtha** [comment]
Hmm.is it defined somewhere how much time it needs to free up memory

**Comment by shengjun1985** [comment]
It seems that all the questions are answered.
Please allow me to close the issue.
If you have more questions, please continue to contact our community.
Thank you.

**Comment by k-for-code** [comment]
I am facing a similar issue, I have raw data in CSV format which accounts for around 6.8GB, 3217379 vectors.
Each vector is of 440 float value length.
When i put these values in sizing tool, it shows 
![image](https://user-images.githubusercontent.com/59497032/159151326-d0daa2d6-95f6-4aac-8c6d-b52792ff4e4a.png)
but on my system, it accounts for 136 GB, which is far far more than expected even if I consider each float value to use 64 bytes it accounts to 3217379 * 440 * 64 = 90 GB, which is still 46 GB less than what volumes folder is occupying.
I saw IVF_FLAT requires more space than raw data size, but 46 GB is too more. 
I want to know if I am making some mistake here, or is this expected.


- Milvus version: 2.0.0
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.0.1
- OS(Ubuntu or CentOS): Ubuntu 20.04 lts
- CPU/Memory: 16 gb ram
- GPU: No
- Others: using default docker-compose.yml from bootcamp, IVF_FLAT indexing
