### ISSUE TITLE
[Bug]: The non-delagator querynode oomkilled during concurrent upsert and search

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#32512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: cardinal-milvus-io-2.3-d63549588-20240412
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. release `laion1b-test-2` has 4 querynodes
2. collection `laion_stable_5` has 2 shards and 54m+ 768dim data
3. release-load collection
4. concurrent: search + query + upsert + flush + load
![image](https://github.com/milvus-io/milvus/assets/27288593/e4a18db0-42a6-42ce-9431-a87125117517)

5. queryNode-pzn7g oomkilled at 04-21 18:44(UTC), and queryNode-pzn7g isn't delegator
6. dataNode-lkdms oomkilled at 04-21 19:44(UTC)
7. dataNode-hxgzw oomkilled at 04-21 22:42
[kube_pod_container_status_last_terminated_reason oomkilled](https://grafana-4am.zilliz.cc/explore?panes=%7B%22SGN%22:%7B%22datasource%22:%22P1809F7CD0C75ACF3%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22kube_pod_container_status_last_terminated_reason%7Bpod%3D~%5C%22laion1b-test-2-milvus-.%2A%5C%22,%20reason%3D%5C%22OOMKilled%5C%22%7D%22,%22range%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P1809F7CD0C75ACF3%22%7D,%22editorMode%22:%22code%22,%22legendFormat%22:%22__auto%22%7D%5D,%22range%22:%7B%22from%22:%221713516336723%22,%22to%22:%221713788547811%22%7D%7D%7D&schemaVersion=1&orgId=1)

### Milvus Log

- argo: https://argo-workflows.zilliz.cc/archived-workflows/qa/0f96f427-a3e0-4e44-bb51-015298fe664e?nodeId=laion1b-test-cron-1713715260
- grafana: [metrics of laion1b-test-2](https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=P1809F7CD0C75ACF3&var-cluster=&var-namespace=qa-milvus&var-instance=laion1b-test-2&var-collection=All&var-app_name=milvus&from=1713715835000&to=1713765600000)
- pods:
```
laion1b-test-2-milvus-datanode-8d8768545-hxgzw                    1/1     Running                           7 (9h ago)      10d     10.104.31.76    4am-node34   <none>           <none>
laion1b-test-2-milvus-datanode-8d8768545-lkdms                    1/1     Running                           15 (16h ago)    13d     10.104.6.34     4am-node13   <none>           <none>
laion1b-test-2-milvus-indexnode-65bd756d8c-76g79                  1/1     Running                           0               13d     10.104.5.106    4am-node12   <none>           <none>
laion1b-test-2-milvus-indexnode-65bd756d8c-dxf6c                  1/1     Running                           1 (6d14h ago)   13d     10.104.19.223   4am-node28   <none>           <none>
laion1b-test-2-milvus-indexnode-65bd756d8c-gm26p                  1/1     Running                           2 (6d ago)      13d     10.104.30.167   4am-node38   <none>           <none>
laion1b-test-2-milvus-mixcoord-794cfb7b6d-m495w                   1/1     Running                           4 (6d4h ago)    10d     10.104.29.207   4am-node35   <none>           <none>
laion1b-test-2-milvus-proxy-fcbf74dfb-tjnqk                       1/1     Running                           0               9d      10.104.34.246   4am-node37   <none>           <none>
laion1b-test-2-milvus-querynode-0-6c76d87fcd-4m98p                1/1     Running                           2 (3d20h ago)   10d     10.104.23.203   4am-node27   <none>           <none>
laion1b-test-2-milvus-querynode-0-6c76d87fcd-pzn7g                1/1     Running                           1 (17h ago)     13d     10.104.24.165   4am-node29   <none>           <none>
laion1b-test-2-milvus-querynode-0-6c76d87fcd-qlhms                1/1     Running                           2 (20h ago)     13d     10.104.17.251   4am-node23   <none>           <none>
laion1b-test-2-milvus-querynode-0-6c76d87fcd-qmw97                1/1     Running                           2 (6d4h ago)    13d     10.104.18.86    4am-node25   <none>           <none>
```

**Comment by aoiasd** [comment]
Etcd disconnected cause one querynode(querynode-0-6c76d87fcd-qlhms) exit and cause querycoord blance channel and segments to another querynode, then cause OOM because concurrent load sealed segments and load channel with growing segements.
