### ISSUE TITLE
Different restrictions on different devices (CPU / GPU)

### ISSUE THREAD

**Issue by shengjun1985** [milvus-io/milvus#3254]
**Please state you issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**
The restrictions on different devices (CPU / GPU) should be different.
For example, the parameter 'M' of index IVF_PQ has more options on the CPU than on the GPU.
But Milvus does not support more even if it only runs on the CPU.

**Describe the solution you'd like**
Relax restrictions on the CPU.

**Describe alternatives you've considered**
The case that the parameters set by the user cannot run on the GPU:
(1) return error
(2) automatically run on the CPU
(3) provide a configure item whether return error or automatically run on the CPU

**Additional context**
none

**Comment by shanghaikid** [comment]
I prefer choosing (2) automatically run on the CPU
.and it would be better print out a warning on the screen, so that user would know what is happening. 

@shengjun1985

**Comment by shengjun1985** [comment]
@del-zhenwu 
[v0.10.3]
IVF_PQ
CPU valid param 'm': m ≡ dim (mod m)
GPU valid param 'm': m ∈ {1, 2, 3, 4, 8, 12, 16, 20, 24, 28, 32, 40, 48, 56, 64, 96}
and (dim / m) ∈ {1, 2, 3, 4, 6, 8, 10, 12, 16, 20, 24, 28, 32}
and m x 1024 <= MaxSharedMemPerBlock of your graphics card.
Note: IVF_PQ GPU search turn into CPU when 'm' is not support on GPU
