### ISSUE TITLE
[Bug]: BulkInsert is incompatible with the original logic regarding the $meta column. An error will occur if $meta.npy is missing.

### ISSUE THREAD

**Issue by lentitude2tk** [milvus-io/milvus#32542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20240415-70e3d5b-909836f	
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. Create a collection and enable Dynamic Schema, for example, schema(a, b).
2. Use the BulkInsert interface to load npy files, passing a.npy and b.npy.
3. An error occurs, indicating that [type=PreImportTask] [reason="no file for field: $meta, files:".[xxxxx]

### Expected Behavior

If Dynamic Schema is enabled and npy files are used for bulkInsert import, $meta should be an optional column. This column is considered advanced for most users and should not be mandatory. It should remain consistent with the original logic.

### Steps To Reproduce

```markdown
The issue can be reliably reproduced following steps 1-3.
```

### Milvus Log

[2024/04/23 11:21:27.542 +00:00] [WARN] [datacoord/import_scheduler.go:239] ["preimport failed"] [taskID=449270987431173741] [jobID=449270987431173728] [collectionID=449270987431166786] [type=PreImportTask] [reason="no file for field: $meta, files: [xxxx/int32.npy xxxx/float.npy xxxx/double.npy xxxx/int16.npy xxxx/floatVector.npy xxxx/varchar.npy xxxx/int8.npy xxxx/bool.npy xxxx/json.npy xxxx/int64.npy]: importing data failed"]

https://grafana-vdc-dev.zilliz.cc/explore?orgId=1&panes=%7B%22mnt%22:%7B%22datasource%22:%22Zgl22j0Vk%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcluster%3D%5C%22sit-vdc-test%5C%22,namespace%3D%5C%22milvus-in01-4544eb3ff99a7bc%5C%22,pod%3D~%5C%22in01-4544eb3ff99a7bc-milvus-.%2A%5C%22%7D%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22Zgl22j0Vk%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1

**Comment by zhuwenxing** [comment]
verified in numpy import.
but if so, i think if no $meta in parquet should also works. 
However, there will be an error `schema not equal, err=field '$meta' not in arrow schema: importing data failed: importing data failed", 'progress_percent': '0'`

**Comment by bigsheeper** [comment]
/assign @zhuwenxing 
/unassign
please help to verify :)

**Comment by zhuwenxing** [comment]
verified and ifxed
