### ISSUE TITLE
[Bug]: User is able to list the collections from unauthorized database

### ISSUE THREAD

**Issue by kish5430** [milvus-io/milvus#32550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

HI Team,
We deployed a Milvus cluster with a multitancy strategy, creating two databases with separate users. Each user has specific privileges assigned through roles. However, users can access and list collections from unauthorized databases but can't search or insert entities. How can we restrict users from seeing the database or collection lists in unauthorized databases?

        role.grant("Global", "*", "CreateCollection", db_name=db_name)
        role.grant("Global",  "*", "DropCollection", db_name=db_name)
        role.grant("Global",  "*", "DescribeCollection", db_name=db_name)
        role.grant("Global",  "*", "ShowCollections", db_name=db_name)
        role.grant("Global",  "*", "SelectOwnership", db_name=db_name)
        role.grant("Global",  "*", "ManageOwnership", db_name=db_name)
        print(f"grant Global admin privilage for role {user}")
        role.grant("Collection", "*", "*", db_name=db_name)

Thanks

**Comment by yanliang567** [comment]
I think this could be a limitation by design for now. @SimFG please help to confirm
/assign @SimFG 
/unassign

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version:
> - Deployment mode(standalone or cluster):
> - MQ type(rocksmq, pulsar or kafka):    
> - SDK version(e.g. pymilvus v2.0.0rc2):
> - OS(Ubuntu or CentOS): 
> - CPU/Memory: 
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> HI Team, We deployed a Milvus cluster with a multitancy strategy, creating two databases with separate users. Each user has specific privileges assigned through roles. However, users can access and list collections from unauthorized databases but can't search or insert entities. How can we restrict users from seeing the database or collection lists in unauthorized databases?
> 
> ```
>     role.grant("Global", "*", "CreateCollection", db_name=db_name)
>     role.grant("Global",  "*", "DropCollection", db_name=db_name)
>     role.grant("Global",  "*", "DescribeCollection", db_name=db_name)
>     role.grant("Global",  "*", "ShowCollections", db_name=db_name)
>     role.grant("Global",  "*", "SelectOwnership", db_name=db_name)
>     role.grant("Global",  "*", "ManageOwnership", db_name=db_name)
>     print(f"grant Global admin privilage for role {user}")
>     role.grant("Collection", "*", "*", db_name=db_name)
> ```
> 
> Thanks
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

this is by design in 2.3 and we want to improve this in 2.4.

I thought for all the list operations we should only show where user has access on. @SimFG did that in 2.4 already?

**Comment by SimFG** [comment]
@kish5430 @xiaofan-luan  This part of the function is under development and version 2.4.1 is expected to be online

**Comment by kish5430** [comment]
> @kish5430 @xiaofan-luan This part of the function is under development and version 2.4.1 is expected to be online

HI @SimFG Can you plz provide an ETA to release 2.4.1 version?

**Comment by yanliang567** [comment]
2.4.1 was released https://github.com/milvus-io/milvus/releases/tag/v2.4.1
