### ISSUE TITLE
[Bug]: GPU_CAGRA Index The top 100 search results do not contain the searched vector.

### ISSUE THREAD

**Issue by longyxiang** [milvus-io/milvus#32585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4
- Deployment mode(standalone or cluster):standalone 
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):Go
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: A10
- Others:
```

### Current Behavior

Neither the case with Partition nor the case without Partition can retrieve the result
![微信图片_20240424211959](https://github.com/milvus-io/milvus/assets/33796882/0312e7c3-86fa-48ce-a454-8686f7a5a732)

**Comment by longyxiang** [comment]
index_params = {
    "metric_type": "IP",
    "index_type": "GPU_CAGRA",
    "params": {
        'intermediate_graph_degree': 64,
        'graph_degree': 32
    }
}
search_params = {
    "metric_type": "IP",
    "params": {
        "itopk_size": 1024,
        "search_width": 4,
        "min_iterations": 0,
        "max_iterations": 0,
        "team_size": 0
    }
}

**Comment by yanliang567** [comment]
@Presburger any updates for this issue?

**Comment by Presburger** [comment]
fixed
