### ISSUE TITLE
[Bug]: [Nightly]Range search with SCANN index will return 0 result

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#32648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2586c2f
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Range search with SCANN index will return 0 result.

```
[2024-04-25T20:51:41.196Z] [2024-04-25 19:39:53 - ERROR - ci_test]: search_results_check: limit(topK) searched (0) is not equal with expected (10) (func_check.py:329)
```

### Expected Behavior

return 10 results

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/723/pipeline/179
2. log: [artifacts-milvus-distributed-kafka-nightly-723-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/723/artifact/artifacts-milvus-distributed-kafka-nightly-723-pymilvus-e2e-logs.tar.gz)
3. failed time: [2024-04-25T19:39:54.470Z] [gw1] [ 66%] FAILED testcases/test_search.py::TestCollectionRangeSearch::test_range_search_after_index_different_metric_type[32-SCANN-params5] 
4. collection: search_collection_ulfibeVg

The case only failed when using SCANN index.

**Comment by yanliang567** [comment]
@liliu-z is it a dup to #32608
/assign @liliu-z 
/unassign

**Comment by yanliang567** [comment]
@NicoYuan1986 does it still reproduce?
@liliu-z any udpates
