### ISSUE TITLE
Memory leak during searching

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#3265]
**Please state you issue using the following template and, most importantly, in English.**

**Describe the bug**
Memory has been increasing during searching.

**Steps/Code to reproduce behavior**
based on sift-1m dataset, build with ivf_sq8 type.

**Expected behavior**

**Environment details**
master-branch
cpu-version

**Screenshots**

**Additional context**

**Comment by del-zhenwu** [comment]
the initial memory usage: 
```
    1 root      20   0   20.9g   2.8g 877600 S   0.0  0.6   3:11.23 milvus_server                                                                                                          

```

**Comment by shengjun1985** [comment]
SearchTask, ExecutionEngineImpl and SegmentReader are not released.

**Comment by suvashishtha** [comment]
+1

**Comment by del-zhenwu** [comment]
```
/ (sda1)   20.0G   187G    398.2   0.5 26.2G 2.59G 23313 root         0 S  49:51.74     0     0 milvus_server -c /var/lib/milvus/conf/milvus.yaml

```
on sift-1m dataset, memory usage still growing
