### ISSUE TITLE
[Bug]: hybrid search failed to use the specified database , always raise error saying collection not find in the default database 

### ISSUE THREAD

**Issue by KaimingFanshi** [milvus-io/milvus#32660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.0
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):   kafka 
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0 
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory:  -- 
- GPU: None
- Others:  --
```

### 1/  load collection 
conn_alias = 'default' 
db_name = 'jifeng_001'
conn = connections.connect(conn_alias, host="remote_server", port="19530"
                           ,user=username, password=password, db_name= db_name)
col_name = 'jifeng_collect_001'   
col_ins = Collection(col_name)
col_ins.load()

### 2/ do hybrid_search 
query = "how to open a future account ? "
query_embeddings = bge_m3([query]) 
dense_req = AnnSearchRequest(data = query_embeddings["dense"], 
                             anns_field = "dense_vector", 
                             param= dense_search_params, 
                             limit=topk,
                             expr = expr )    
sparse_req = AnnSearchRequest(data = query_embeddings["sparse"], 
                              anns_field = "sparse_vector", 
                              param = sparse_search_params, 
                              limit=topk, 
                               expr = expr)

res = col_ins.hybrid_search(reqs = [sparse_req, dense_req], 
                            rerank=RRFRanker(), 
                            limit=topk, 
                            output_fields=output_fields)                     
res = res[0]
use_reranker = True
if use_reranker:
    result_texts = [hit.fields["text"] for hit in res]
    from pymilvus.model.reranker import BGERerankFunction
    bge_rf = BGERerankFunction(device='cpu')
    # rerank the results using BGE CrossEncoder model
    results = bge_rf(query, result_texts, top_k=2)
    for hit in results:
        print(f'text: {hit.text} distance {hit.score}')
else:
    for hit in res:
        print(f'text: {hit.fields["text"]} distance {hit.distance}')

### 3/ specified database deliberately , still get the wrong error 
db.using_database("jifeng_001")

### 4 /error message 
RPC error: [hybrid_search], <MilvusException: (code=100, message=collection not found[database=default][collection=jifeng_collect_001])>, <Time:{'RPC start': '2024-04-28 12:06:19.202507', 'RPC error': '2024-04-28 12:06:19.510437'}>

### Expected Behavior

when doing hybrid search ,  query the  collection in the specified database instead of the default database . 

### Milvus Log

---------------------------------------------------------------------------
MilvusException                           Traceback (most recent call last)
    [... skipping hidden 1 frame]

Cell In[156], line 16
     10 sparse_req = AnnSearchRequest(data = query_embeddings["sparse"], 
     11                               anns_field = "sparse_vector", 
     12                               param = sparse_search_params, 
     13                               limit=topk, 
     14                                expr = expr)
---> 16 res = col_ins.hybrid_search(reqs = [sparse_req, dense_req], 
     17                             rerank=RRFRanker(), 
     18                             limit=topk, 
     19                             output_fields=output_fields)                     
     20 res = res[0]

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/orm/collection.py:936, in Collection.hybrid_search(self, reqs, rerank, limit, partition_names, output_fields, timeout, round_decimal, **kwargs)
    935 conn = self._get_connection()
--> 936 resp = conn.hybrid_search(
    937     self._name,
    938     reqs,
    939     rerank,
    940     limit,
    941     partition_names,
    942     output_fields,
    943     round_decimal,
    944     timeout=timeout,
    945     schema=self._schema_dict,
    946     **kwargs,
    947 )
    949 return SearchFuture(resp) if kwargs.get("_async", False) else resp

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/decorators.py:147, in error_handler.<locals>.wrapper.<locals>.handler(*args, **kwargs)
    146     LOGGER.error(f"RPC error: [{inner_name}], {e}, <Time:{record_dict}>")
--> 147     raise e from e
    148 except grpc.FutureTimeoutError as e:

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/decorators.py:143, in error_handler.<locals>.wrapper.<locals>.handler(*args, **kwargs)
    142     record_dict["RPC start"] = str(datetime.datetime.now())
--> 143     return func(*args, **kwargs)
    144 except MilvusException as e:

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/decorators.py:182, in tracing_request.<locals>.wrapper.<locals>.handler(self, *args, **kwargs)
    181     self.set_onetime_request_id(req_id)
--> 182 return func(self, *args, **kwargs)

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/decorators.py:122, in retry_on_rpc_failure.<locals>.wrapper.<locals>.handler(*args, **kwargs)
    121     else:
--> 122         raise e from e
    123 except Exception as e:

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/decorators.py:87, in retry_on_rpc_failure.<locals>.wrapper.<locals>.handler(*args, **kwargs)
     86 try:
---> 87     return func(*args, **kwargs)
     88 except grpc.RpcError as e:
     89     # Do not retry on these codes

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py:843, in GrpcHandler.hybrid_search(self, collection_name, reqs, rerank, limit, partition_names, output_fields, round_decimal, timeout, **kwargs)
    833 hybrid_search_request = Prepare.hybrid_search_request_with_ranker(
    834     collection_name,
    835     requests,
   (...)
    841     **kwargs,
    842 )
--> 843 return self._execute_hybrid_search(
    844     hybrid_search_request, timeout, round_decimal=round_decimal, **kwargs
    845 )

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py:754, in GrpcHandler._execute_hybrid_search(self, request, timeout, **kwargs)
    753     return SearchFuture(None, None, e)
--> 754 raise e from e

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py:747, in GrpcHandler._execute_hybrid_search(self, request, timeout, **kwargs)
    746 response = self._stub.HybridSearch(request, timeout=timeout)
--> 747 check_status(response.status)
    748 round_decimal = kwargs.get("round_decimal", -1)

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/client/utils.py:60, in check_status(status)
     59 if status.code != 0 or status.error_code != 0:
---> 60     raise MilvusException(status.code, status.reason, status.error_code)

MilvusException: <MilvusException: (code=100, message=collection not found[database=default][collection=jifeng_collect_001])>

The above exception was the direct cause of the following exception:

MilvusException                           Traceback (most recent call last)
    [... skipping hidden 1 frame]

Cell In[156], line 16
     10 sparse_req = AnnSearchRequest(data = query_embeddings["sparse"], 
     11                               anns_field = "sparse_vector", 
     12                               param = sparse_search_params, 
     13                               limit=topk, 
     14                                expr = expr)
---> 16 res = col_ins.hybrid_search(reqs = [sparse_req, dense_req], 
     17                             rerank=RRFRanker(), 
     18                             limit=topk, 
     19                             output_fields=output_fields)                     
     20 res = res[0]

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/orm/collection.py:936, in Collection.hybrid_search(self, reqs, rerank, limit, partition_names, output_fields, timeout, round_decimal, **kwargs)
    935 conn = self._get_connection()
--> 936 resp = conn.hybrid_search(
    937     self._name,
    938     reqs,
    939     rerank,
    940     limit,
    941     partition_names,
    942     output_fields,
    943     round_decimal,
    944     timeout=timeout,
    945     schema=self._schema_dict,
    946     **kwargs,
    947 )
    949 return SearchFuture(resp) if kwargs.get("_async", False) else resp

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/decorators.py:147, in error_handler.<locals>.wrapper.<locals>.handler(*args, **kwargs)
    146     LOGGER.error(f"RPC error: [{inner_name}], {e}, <Time:{record_dict}>")
--> 147     raise e from e
    148 except grpc.FutureTimeoutError as e:

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/decorators.py:143, in error_handler.<locals>.wrapper.<locals>.handler(*args, **kwargs)
    142     record_dict["RPC start"] = str(datetime.datetime.now())
--> 143     return func(*args, **kwargs)
    144 except MilvusException as e:

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/decorators.py:182, in tracing_request.<locals>.wrapper.<locals>.handler(self, *args, **kwargs)
    181     self.set_onetime_request_id(req_id)
--> 182 return func(self, *args, **kwargs)

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/decorators.py:122, in retry_on_rpc_failure.<locals>.wrapper.<locals>.handler(*args, **kwargs)
    121     else:
--> 122         raise e from e
    123 except Exception as e:

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/decorators.py:87, in retry_on_rpc_failure.<locals>.wrapper.<locals>.handler(*args, **kwargs)
     86 try:
---> 87     return func(*args, **kwargs)
     88 except grpc.RpcError as e:
     89     # Do not retry on these codes

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py:843, in GrpcHandler.hybrid_search(self, collection_name, reqs, rerank, limit, partition_names, output_fields, round_decimal, timeout, **kwargs)
    833 hybrid_search_request = Prepare.hybrid_search_request_with_ranker(
    834     collection_name,
    835     requests,
   (...)
    841     **kwargs,
    842 )
--> 843 return self._execute_hybrid_search(
    844     hybrid_search_request, timeout, round_decimal=round_decimal, **kwargs
    845 )

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py:754, in GrpcHandler._execute_hybrid_search(self, request, timeout, **kwargs)
    753     return SearchFuture(None, None, e)
--> 754 raise e from e

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py:747, in GrpcHandler._execute_hybrid_search(self, request, timeout, **kwargs)
    746 response = self._stub.HybridSearch(request, timeout=timeout)
--> 747 check_status(response.status)
    748 round_decimal = kwargs.get("round_decimal", -1)

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/client/utils.py:60, in check_status(status)
     59 if status.code != 0 or status.error_code != 0:
---> 60     raise MilvusException(status.code, status.reason, status.error_code)

MilvusException: <MilvusException: (code=100, message=collection not found[database=default][collection=jifeng_collect_001])>

The above exception was the direct cause of the following exception:

MilvusException                           Traceback (most recent call last)
Cell In[156], line 16
      5 dense_req = AnnSearchRequest(data = query_embeddings["dense"], 
      6                              anns_field = "dense_vector", 
      7                              param= dense_search_params, 
      8                              limit=topk,
      9                              expr = expr )    
     10 sparse_req = AnnSearchRequest(data = query_embeddings["sparse"], 
     11                               anns_field = "sparse_vector", 
     12                               param = sparse_search_params, 
     13                               limit=topk, 
     14                                expr = expr)
---> 16 res = col_ins.hybrid_search(reqs = [sparse_req, dense_req], 
     17                             rerank=RRFRanker(), 
     18                             limit=topk, 
     19                             output_fields=output_fields)                     
     20 res = res[0]
     21 use_reranker = True

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/orm/collection.py:936, in Collection.hybrid_search(self, reqs, rerank, limit, partition_names, output_fields, timeout, round_decimal, **kwargs)
    933     return SearchFuture(None) if kwargs.get("_async", False) else resp
    935 conn = self._get_connection()
--> 936 resp = conn.hybrid_search(
    937     self._name,
    938     reqs,
    939     rerank,
    940     limit,
    941     partition_names,
    942     output_fields,
    943     round_decimal,
    944     timeout=timeout,
    945     schema=self._schema_dict,
    946     **kwargs,
    947 )
    949 return SearchFuture(resp) if kwargs.get("_async", False) else resp

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/decorators.py:147, in error_handler.<locals>.wrapper.<locals>.handler(*args, **kwargs)
    145     record_dict["RPC error"] = str(datetime.datetime.now())
    146     LOGGER.error(f"RPC error: [{inner_name}], {e}, <Time:{record_dict}>")
--> 147     raise e from e
    148 except grpc.FutureTimeoutError as e:
    149     record_dict["gRPC timeout"] = str(datetime.datetime.now())

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/decorators.py:143, in error_handler.<locals>.wrapper.<locals>.handler(*args, **kwargs)
    141 try:
    142     record_dict["RPC start"] = str(datetime.datetime.now())
--> 143     return func(*args, **kwargs)
    144 except MilvusException as e:
    145     record_dict["RPC error"] = str(datetime.datetime.now())

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/decorators.py:182, in tracing_request.<locals>.wrapper.<locals>.handler(self, *args, **kwargs)
    180 if req_id:
    181     self.set_onetime_request_id(req_id)
--> 182 return func(self, *args, **kwargs)

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/decorators.py:122, in retry_on_rpc_failure.<locals>.wrapper.<locals>.handler(*args, **kwargs)
    120         back_off = min(back_off * back_off_multiplier, max_back_off)
    121     else:
--> 122         raise e from e
    123 except Exception as e:
    124     raise e from e

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/decorators.py:87, in retry_on_rpc_failure.<locals>.wrapper.<locals>.handler(*args, **kwargs)
     85 while True:
     86     try:
---> 87         return func(*args, **kwargs)
     88     except grpc.RpcError as e:
     89         # Do not retry on these codes
     90         if e.code() in IGNORE_RETRY_CODES:

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py:843, in GrpcHandler.hybrid_search(self, collection_name, reqs, rerank, limit, partition_names, output_fields, round_decimal, timeout, **kwargs)
    831     requests.append(search_request)
    833 hybrid_search_request = Prepare.hybrid_search_request_with_ranker(
    834     collection_name,
    835     requests,
   (...)
    841     **kwargs,
    842 )
--> 843 return self._execute_hybrid_search(
    844     hybrid_search_request, timeout, round_decimal=round_decimal, **kwargs
    845 )

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py:754, in GrpcHandler._execute_hybrid_search(self, request, timeout, **kwargs)
    752 if kwargs.get("_async", False):
    753     return SearchFuture(None, None, e)
--> 754 raise e from e

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py:747, in GrpcHandler._execute_hybrid_search(self, request, timeout, **kwargs)
    744     return SearchFuture(future, func)
    746 response = self._stub.HybridSearch(request, timeout=timeout)
--> 747 check_status(response.status)
    748 round_decimal = kwargs.get("round_decimal", -1)
    749 return SearchResult(response.results, round_decimal)

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymilvus/client/utils.py:60, in check_status(status)
     58 def check_status(status: Status):
     59     if status.code != 0 or status.error_code != 0:
---> 60         raise MilvusException(status.code, status.reason, status.error_code)

MilvusException: <MilvusException: (code=100, message=collection not found[database=default][collection=jifeng_collect_001])>

**Comment by yanliang567** [comment]
@KaimingFanshi sorry, i did not reproduce the issue with milvus 2.4.0 and pymilvus 2.4.0, could you please double check the versions?  
/assign @KaimingFanshi 
/unassign

**Comment by KaimingFanshi** [comment]
> @KaimingFanshi sorry, i did not reproduce the issue with milvus 2.4.0 and pymilvus 2.4.0, could you please double check the versions? /assign @KaimingFanshi /unassign

Thank you for the reply . I do confirm the version,  pymilvus is v2.4.0, the milvus database version is as follow. it works well when i conduct dense or sparse vector searche separatedly , but raised the error  as described earlier . 
![mivlus2 4 0](https://github.com/milvus-io/milvus/assets/168321983/67539384-c788-43d2-a530-70877c3777b9)

**Comment by xiaofan-luan** [comment]
could you upgrade to 2.4.0 and try?

**Comment by lucassong3000** [comment]
why
