### ISSUE TITLE
[Bug]:  v2.4.0 datanode 内存使用过高

### ISSUE THREAD

**Issue by yesyue** [milvus-io/milvus#32695]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.4.0
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    kafka 
- SDK version(e.g. pymilvus v2.0.0rc2): 2.7
- OS(Ubuntu or CentOS):  CentOS
- CPU/Memory: 544c /4291.6 G at least
- GPU:  0 
- Others: datanode
```

### Current Behavior

参考sizing tools 分配Data Node ， 2 core 8 GB x 2pods ， 实际运行出现OOM ， 扩容后内存占用达40G

### Expected Behavior

参考sizing tools 分配Data Node ， 2 core 8 GB x 2pods ， 实际运行出现OOM ， 扩容后内存占用达40G

### Steps To Reproduce

```markdown
参考sizing tools 分配Data Node ， 2 core 8 GB x 2pods ， 实际运行出现OOM ， 扩容后内存占用达40G
```

**Comment by yesyue** [comment]
datanode log:

[datanode.log](https://github.com/milvus-io/milvus/files/15145433/datanode.log)

**Comment by yanliang567** [comment]
@yesyue please share more info about how you using milvus, e.g. what kinds of requests did you call to milvus, how many, and how frequency of them? also please help all the milvus pods logs for invesgitaion.

/assign @yesyue 
/unassign

**Comment by yesyue** [comment]
100 Million/day entites write to milvus

**Comment by tadinhkien99** [comment]
> 100 Million/day entites write to milvus

after I inserted 10M entites total, then milvus docker stop and crash. I use IVF_SQ8 index, installed milvus with gpu.
I use batch insert 10000 (only insert if enough 10000 entities.

after crash I can't connect to connection again and can't use anything. Any solution?

**Comment by xiaofan-luan** [comment]
1. seems that flush can not catch up the read. 
2. how many partitions do you have? if you have many partitions or collections, the flush and memory consumption will be larger than estimation.
3. there is bunch of configs to tune, like concurrent flush number -> dataNode.dataSync.maxParallelSyncMgrTasks (for 2.4)
memory used for growing segment

**Comment by xiaofan-luan** [comment]
> > 100 Million/day entites write to milvus
> 
> after I inserted 10M entites total, then milvus docker stop and crash. I use IVF_SQ8 index, installed milvus with gpu. I use batch insert 10000 (only insert if enough 10000 entities.
> 
> after crash I can't connect to connection again and can't use anything. Any solution?

how much gpu memory do you have? 
please open another issue with detailed logs so we can help

**Comment by yesyue** [comment]
[querynode (3).log](https://github.com/milvus-io/milvus/files/15206370/querynode.3.log)

**Comment by xiaofan-luan** [comment]
> [querynode (3).log](https://github.com/milvus-io/milvus/files/15206370/querynode.3.log)

1.could you offer log for datanode?
2. it would be great if you have a datanode pprof, so you know which part takes of your memory. Most likely it's insert buffer takes the memory and you can tune the flush parameter

**Comment by xiaofan-luan** [comment]
I saw you in many issues and we'd like to offer help.
feel free to contact me at xiaofan.luan@zilliz.com if necessary
