### ISSUE TITLE
[Bug]: collection not loaded, querynode restart, search/query delegator rpc error

### ISSUE THREAD

**Issue by JamesBonddu** [milvus-io/milvus#32694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.11
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.6
- OS(Ubuntu or CentOS): Ubuntu20.0
- CPU/Memory: 521 core/1T
- GPU: 24G
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/15228379/deb99672-1d5b-4bc6-9441-6f6cb527b8a5)

![image](https://github.com/milvus-io/milvus/assets/15228379/16580c9b-49f9-45ff-b193-34ffd2189654)

![image](https://github.com/milvus-io/milvus/assets/15228379/a95acb88-3b63-419f-8c3f-e7b0e43d78a1)

[milvus.md](https://github.com/milvus-io/milvus/files/15145085/milvus.md)

**Comment by yanliang567** [comment]
@JamesBonddu please offer the full milvus pods logs for investigation. I looks like a known fix that was fixed in milvus 2.3.13, please retry on it.
/assign @JamesBonddu 
/unassign

**Comment by JamesBonddu** [comment]
> @JamesBonddu please offer the full milvus pods logs for investigation. I looks like a known fix that was fixed in milvus 2.3.13, please retry on it. /assign @JamesBonddu /unassign

i had updated milvus 2.4.1-gpu and still has error pulsar Too many requests to the same Bookie while reading.

```sh
docker-compose down 
docker-compose up -d
```

[docker-compose.yaml.md](https://github.com/milvus-io/milvus/files/15218820/docker-compose.yaml.md)


![15ac012ed4afb9c1773ecb679088ef1](https://github.com/milvus-io/milvus/assets/15228379/59539630-91ad-4e92-a756-49c1b7e426fe)

**Comment by yhmo** [comment]
Link to https://github.com/milvus-io/milvus/issues/33171

**Comment by xiaofan-luan** [comment]
@JamesBonddu 
how many collections do you have and how many nodes?
I don't this is likely related to a pulsar issue

**Comment by xiaofan-luan** [comment]
1. when collection number is large, loading all collection from pulsar might be expensive.
Solution:
1. reduce collection number might help
2. upgrade to 2.3.15 might help
3. try to increase pulsar cpu and memory might help
