### ISSUE TITLE
[BUG] Search does not use GPU when index type is FLAT

### ISSUE THREAD

**Issue by cydrain** [milvus-io/milvus#327]
**Describe the bug**
Search does not use GPU when index type is FLAT

**Steps/Code to reproduce behavior**
1. set "search_resources" in server_config.yaml to contains only gpu
  search_resources:
    - gpu0
2. create index with IndexType.FLAT
3. search performance seems as same as CPU search

**Expected behavior**
FLAT GPU performance should be much faster then FLAT CPU

**Environment details**
N/A

**Screenshots**
N/A

**Additional context**

**Comment by scsven** [comment]
done
