### ISSUE TITLE
[Enhancement]: local reduce can be optimized if only one segment is involved

### ISSUE THREAD

**Issue by longjiquan** [milvus-io/milvus#32728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

https://github.com/milvus-io/milvus/blob/77f4f0c5a82f71c148a10e4719df48033dfd4d6c/internal/core/src/segcore/Reduce.cpp#L222-L311

### Why is this needed?

![9PfCtXlffP](https://github.com/milvus-io/milvus/assets/31589260/9390fdd4-b1aa-48ee-917e-7b47a705e527)

If only one segment was involved in the reduce phase, in fact we waste the cpu of heap-sort to complete the reduce. We can do it more simply.

**Comment by longjiquan** [comment]
the tracing can be found in https://github.com/milvus-io/milvus/pull/32734

**Comment by xiaofan-luan** [comment]
seems to be a promising optimization
