### ISSUE TITLE
[Bug]: After enabling dynamic schema, if there is no $meta field, the import of Parquet file format will fail.

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#32729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Even if the dynamic schema is enabled, users may not have dynamic columns in their data, so $meta can be optional.

### Expected Behavior

failed_reason': "schema not equal, err=field '$meta' not in arrow schema: importing data failed: importing data failed", 'progress_percent': '0'}

### Milvus Log

failed ci job:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-32706/3/pipeline/

**Comment by bigsheeper** [comment]
/assign @zhuwenxing 
/unassign

please help to verify
