### ISSUE TITLE
[Bug]: For pk field, it was not allowed to firstly load the index and then load the field data.

### ISSUE THREAD

**Issue by v1incent** [milvus-io/milvus#32744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master branch
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

For sealed segment and pk field, it was not allowed to firstly load the index and then load the field data.
The related code is in LoadFieldData in SegmentSealedImpl.cpp,
```
AssertInfo(insert_record_.empty_pks(), "already exists");
```

**Comment by yanliang567** [comment]
/assign @liliu-z 
please help to take a look at this issue and related pr

/unassign

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version: master branch
> - Deployment mode(standalone or cluster):
> - MQ type(rocksmq, pulsar or kafka):    
> - SDK version(e.g. pymilvus v2.0.0rc2):
> - OS(Ubuntu or CentOS): 
> - CPU/Memory: 
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> For sealed segment and pk field, it was not allowed to firstly load the index and then load the field data. The related code is in LoadFieldData in SegmentSealedImpl.cpp,
> 
> ```
> AssertInfo(insert_record_.empty_pks(), "already exists");
> ```
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

what is the reason we need to load index then origin data?

**Comment by v1incent** [comment]
If the index has no rawdata, then the origin data need to be loaded.
