### ISSUE TITLE
milvus mishards on gcp

### ISSUE THREAD

**Issue by suvashishtha** [milvus-io/milvus#3274]
We are running our application on GKE & want to use milvus for vector storage and search. The documentation for mishards has a note for storage options in AWS & azure. 

https://www.milvus.io/docs/v0.10.1/mishards.md#Notes

Is google cloud storage also an option for storage?

**Comment by suvashishtha** [comment]
i guess it can be supported on gke with filestore

https://cloud.google.com/filestore

**Comment by gujun720** [comment]
> i guess it can be supported on gke with filestore
> 
> https://cloud.google.com/filestore

Hi suvashishtha,

As an open-source project, we only have cloud resources on Azure and AWS  at this moment.
Could you please try Milvus on GCP and maybe you can contribute a document about how to run it on GCP?

Thanks.

**Comment by scsven** [comment]
Not activity.
