### ISSUE TITLE
[Enhancement]: consider using https://github.com/planetscale/vtprotobuf

### ISSUE THREAD

**Issue by alexanderguzhva** [milvus-io/milvus#32759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Faster RPC.
Some benchmarks here, https://github.com/LesnyRumcajs/grpc_bench/wiki/2022-04-23-bench-results

Also, according to the documentation, 
> If you're running a complex GRPC service, you may need to support serializing ProtoBuf messages from different sources, including from external packages that will not have optimized vtprotobuf marshalling code. This is perfectly doable by implementing a custom codec in your own project that serializes messages based on their type. ...

**Comment by xiaofan-luan** [comment]
is this compatible with original protobuf?

**Comment by alexanderguzhva** [comment]
I've closed the issue bcz I've ran benchmarks on an aws machine and discovered that performance-wise current grpc and this one are identical. Maybe, this one was faster in the past, but not today.
