### ISSUE TITLE
[Bug]: Unable to set up development environment in Mac

### ISSUE THREAD

**Issue by dugar-tarun** [milvus-io/milvus#32753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): MacOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

On following the instructions for the dev environment setup, I get the following error while running the make command: 
Download milvus-proto repo ...
Build 3rdparty ...
~/Projects/milvus/cmake_build ~/Projects/milvus
Configuration:
[settings]
arch=armv8
arch_build=armv8
build_type=Release
compiler=clang
compiler.cppstd=17
compiler.libcxx=libc++
compiler.version=15
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

WARN: rocksdb/6.29.5@milvus/dev: requirement zstd/1.5.2 overridden by your conanfile to zstd/1.5.4 
WARN: boost/1.82.0: requirement zlib/[>=1.2.11 <2] overridden by your conanfile to zlib/1.2.13 
WARN: arrow/12.0.1: requirement boost/1.84.0 overridden by your conanfile to boost/1.82.0 
WARN: arrow/12.0.1: requirement zstd/1.5.5 overridden by your conanfile to zstd/1.5.4 
WARN: thrift/0.17.0: requirement boost/1.84.0 overridden by arrow/12.0.1 to boost/1.82.0 
WARN: thrift/0.17.0: requirement openssl/[>=1.1 <4] overridden by arrow/12.0.1 to openssl/3.1.2 
WARN: thrift/0.17.0: requirement zlib/[>=1.2.11 <2] overridden by arrow/12.0.1 to zlib/1.2.13 
WARN: openssl/3.1.2: requirement zlib/[>=1.2.11 <2] overridden by thrift/0.17.0 to zlib/1.2.13 
WARN: libevent/2.1.12: requirement openssl/[>=1.1 <4] overridden by thrift/0.17.0 to openssl/3.1.2 
WARN: aws-sdk-cpp/1.9.234: requirement openssl/[>=1.1 <4] overridden by arrow/12.0.1 to openssl/3.1.2 
WARN: aws-sdk-cpp/1.9.234: requirement libcurl/[>=7.78.0 <9] overridden by arrow/12.0.1 to libcurl/7.86.0 
WARN: libcurl/7.86.0: requirement zlib/[>=1.2.11 <2] overridden by aws-sdk-cpp/1.9.234 to zlib/1.2.13 
WARN: googleapis/cci.20221108: requirement protobuf/3.21.12 overridden by your conanfile to protobuf/3.21.4 
WARN: protobuf/3.21.4: requirement zlib/[>=1.2.11 <2] overridden by googleapis/cci.20221108 to zlib/1.2.13 
WARN: libdwarf/20191104: requirement zlib/[>=1.2.11 <2] overridden by your conanfile to zlib/1.2.13 
WARN: prometheus-cpp/1.1.0: requirement libcurl/[>=7.78.0 <9] overridden by your conanfile to libcurl/7.86.0 
WARN: folly/2023.10.30.08@milvus/dev: requirement boost/1.81.0 overridden by your conanfile to boost/1.82.0 
WARN: folly/2023.10.30.08@milvus/dev: requirement openssl/1.1.1q overridden by your conanfile to openssl/3.1.2 
WARN: folly/2023.10.30.08@milvus/dev: requirement zstd/1.5.2 overridden by your conanfile to zstd/1.5.4 
WARN: folly/2023.10.30.08@milvus/dev: requirement fmt/8.0.1 overridden by your conanfile to fmt/9.1.0 
WARN: google-cloud-cpp/2.5.0@milvus/dev: requirement nlohmann_json/3.10.0 overridden by your conanfile to nlohmann_json/3.11.2 
WARN: google-cloud-cpp/2.5.0@milvus/dev: requirement abseil/20220623.0 overridden by your conanfile to abseil/20230125.3 
WARN: google-cloud-cpp/2.5.0@milvus/dev: requirement libcurl/7.88.1 overridden by your conanfile to libcurl/7.86.0 
WARN: google-cloud-cpp/2.5.0@milvus/dev: requirement openssl/[>=1.1 <4] overridden by your conanfile to openssl/3.1.2 
WARN: grpc/1.50.1: requirement openssl/[>=1.1 <4] overridden by google-cloud-cpp/2.5.0@milvus/dev to openssl/3.1.2 
WARN: grpc/1.50.1: requirement protobuf/3.21.12 overridden by google-cloud-cpp/2.5.0@milvus/dev to protobuf/3.21.4 
WARN: grpc/1.50.1: requirement zlib/[>=1.2.11 <2] overridden by google-cloud-cpp/2.5.0@milvus/dev to zlib/1.2.13 
WARN: opentelemetry-cpp/1.8.1.1@milvus/dev: requirement abseil/20220623.0 overridden by your conanfile to abseil/20230125.3 
WARN: opentelemetry-cpp/1.8.1.1@milvus/dev: requirement openssl/1.1.1t overridden by your conanfile to openssl/3.1.2 
WARN: opentelemetry-cpp/1.8.1.1@milvus/dev: requirement libcurl/7.87.0 overridden by your conanfile to libcurl/7.86.0 
WARN: opentelemetry-cpp/1.8.1.1@milvus/dev: requirement boost/1.81.0 overridden by your conanfile to boost/1.82.0 
WARN: librdkafka/1.9.1: requirement zstd/1.5.5 overridden by your conanfile to zstd/1.5.4 
WARN: librdkafka/1.9.1: requirement openssl/[>=1.1 <4] overridden by your conanfile to openssl/3.1.2 
WARN: cyrus-sasl/2.1.27: requirement openssl/[>=1.1 <4] overridden by librdkafka/1.9.1 to openssl/3.1.2 
aws-c-cal/0.5.13: WARN: Package binary is corrupted, removing: 00ac2e7c1fb86e44b1e5df0cd4cecf2574400432
Version ranges solved
    Version range '>=3.16 <4' required by 'glog/0.6.0' resolved to 'cmake/3.29.2' in local cache
    Version range '>=3.20 <4' required by 'googleapis/cci.20221108' resolved to 'cmake/3.29.2' in local cache

conanfile.py: Installing package
Requirements
    abseil/20230125.3 from 'conancenter' - Cache
    arrow/12.0.1 from 'conancenter' - Cache
    aws-c-auth/0.6.11 from 'conancenter' - Cache
    aws-c-cal/0.5.13 from 'conancenter' - Cache
    aws-c-common/0.8.2 from 'conancenter' - Cache
    aws-c-compression/0.2.15 from 'conancenter' - Cache
    aws-c-event-stream/0.2.7 from 'conancenter' - Cache
    aws-c-http/0.6.13 from 'conancenter' - Cache
    aws-c-io/0.10.20 from 'conancenter' - Cache
    aws-c-mqtt/0.7.10 from 'conancenter' - Cache
    aws-c-s3/0.1.37 from 'conancenter' - Cache
    aws-c-sdkutils/0.1.3 from 'conancenter' - Cache
    aws-checksums/0.1.13 from 'conancenter' - Cache
    aws-crt-cpp/0.17.23 from 'conancenter' - Cache
    aws-sdk-cpp/1.9.234 from 'conancenter' - Cache
    benchmark/1.7.0 from 'conancenter' - Cache
    boost/1.82.0 from 'conancenter' - Cache
    bzip2/1.0.8 from 'conancenter' - Cache
    c-ares/1.19.1 from 'conancenter' - Cache
    crc32c/1.1.1 from 'conancenter' - Cache
    cyrus-sasl/2.1.27 from 'conancenter' - Cache
    double-conversion/3.2.1 from 'conancenter' - Cache
    fmt/9.1.0 from 'conancenter' - Cache
    folly/2023.10.30.08@milvus/dev from 'default-conan-local' - Cache
    gflags/2.2.2 from 'conancenter' - Cache
    glog/0.6.0 from 'conancenter' - Cache
    google-cloud-cpp/2.5.0@milvus/dev from 'default-conan-local' - Cache
    googleapis/cci.20221108 from 'conancenter' - Cache
    grpc/1.50.1 from 'conancenter' - Cache
    gtest/1.13.0 from 'conancenter' - Cache
    libbacktrace/cci.20210118 from 'conancenter' - Cache
    libcurl/7.86.0 from 'conancenter' - Cache
    libdwarf/20191104 from 'conancenter' - Cache
    libelf/0.8.13 from 'conancenter' - Cache
    libevent/2.1.12 from 'conancenter' - Cache
    libiberty/9.1.0 from 'conancenter' - Cache
    libiconv/1.17 from 'conancenter' - Cache
    librdkafka/1.9.1 from 'conancenter' - Cache
    libsodium/cci.20220430 from 'conancenter' - Cache
    lz4/1.9.4 from 'conancenter' - Cache
    lzo/2.10 from 'conancenter' - Cache
    marisa/0.2.6 from 'conancenter' - Cache
    nlohmann_json/3.11.2 from 'conancenter' - Cache
    onetbb/2021.9.0 from 'conancenter' - Cache
    openssl/3.1.2 from 'conancenter' - Cache
    opentelemetry-cpp/1.8.1.1@milvus/dev from 'default-conan-local' - Cache
    opentelemetry-proto/0.19.0 from 'conancenter' - Cache
    prometheus-cpp/1.1.0 from 'conancenter' - Cache
    protobuf/3.21.4 from 'conancenter' - Cache
    rapidxml/1.13 from 'conancenter' - Cache
    re2/20230301 from 'conancenter' - Cache
    rocksdb/6.29.5@milvus/dev from 'default-conan-local' - Cache
    snappy/1.1.9 from 'conancenter' - Cache
    thrift/0.17.0 from 'conancenter' - Cache
    xsimd/9.0.1 from 'conancenter' - Cache
    xz_utils/5.4.0 from 'conancenter' - Cache
    yaml-cpp/0.7.0 from 'conancenter' - Cache
    zlib/1.2.13 from 'conancenter' - Cache
    zstd/1.5.4 from 'conancenter' - Cache
Packages
    abseil/20230125.3:18b65edc78d7ed0cf17680476ae34db3c54ca4a0 - Cache
    arrow/12.0.1:13b3c658ad33c00fccdb85e1a9269f4802c71048 - Build
    aws-c-auth/0.6.11:d9194a6b351ccd8114e8e2eb38ca02f756a45ea1 - Build
    aws-c-cal/0.5.13:00ac2e7c1fb86e44b1e5df0cd4cecf2574400432 - Build
    aws-c-common/0.8.2:abfed910ebc3cd46e798925d9df31705df2e7725 - Cache
    aws-c-compression/0.2.15:00ac2e7c1fb86e44b1e5df0cd4cecf2574400432 - Build
    aws-c-event-stream/0.2.7:01d6e50f8c37b67a9fb7d0541c17e2d59a332e54 - Build
    aws-c-http/0.6.13:d82ffd5e0d43ae3592e0ca1aa98806a776736418 - Build
    aws-c-io/0.10.20:47b0c19cfbef2f62a128367601c0d07ef562b0c0 - Build
    aws-c-mqtt/0.7.10:a354ae525685fccfc0b7bdcc33fa9f145dce4a6c - Build
    aws-c-s3/0.1.37:c1a725a593556449e9320b7e6e9cc63330f853e0 - Build
    aws-c-sdkutils/0.1.3:00ac2e7c1fb86e44b1e5df0cd4cecf2574400432 - Build
    aws-checksums/0.1.13:00ac2e7c1fb86e44b1e5df0cd4cecf2574400432 - Build
    aws-crt-cpp/0.17.23:90865ba92470b8e9c7b13055199b3d97b68b4b32 - Build
    aws-sdk-cpp/1.9.234:19ae3f012805d3aaa22fc0599e7ad9f5d85086fe - Build
    benchmark/1.7.0:0b93393b52ca222af3681666ab53edb06b680f9d - Cache
    boost/1.82.0:3e96470e9dc4865aa52ac29fc2264949467fab69 - Build
    bzip2/1.0.8:51ee4e21c69588e687ed84a20b3314f0261f808f - Cache
    c-ares/1.19.1:65d0c6387c314520223dd15a4a7aadd3107d2214 - Cache
    crc32c/1.1.1:8e571da4843ef00036a7b515c7b68476001d4fb1 - Cache
    cyrus-sasl/2.1.27:6442adaa4efc91586d7252754627bff976c2d238 - Build
    double-conversion/3.2.1:18b65edc78d7ed0cf17680476ae34db3c54ca4a0 - Cache
    fmt/9.1.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    folly/2023.10.30.08@milvus/dev:da17f6aeed1718cf311d6fb06cecba3f9a75c86a - Build
    gflags/2.2.2:80455a1882af522b22cff39ea6c8689ca81b662a - Cache
    glog/0.6.0:fa6cb23103a07f178f9c454303bd4d3b8bc1fe95 - Build
    google-cloud-cpp/2.5.0@milvus/dev:0c8b932ca5fc84e148927535b4fbf45de520d892 - Build
    googleapis/cci.20221108:09b5dd7c323c43b18fca9293254069997e8919ef - Build
    grpc/1.50.1:47cabff9592fcc38e29277750a728db765a4851e - Build
    gtest/1.13.0:8e571da4843ef00036a7b515c7b68476001d4fb1 - Cache
    libbacktrace/cci.20210118:f568eec00a82af2100dc006430c1be98df6d77fa - Cache
    libcurl/7.86.0:ad1a5a644a6eea2b587f13d00aad5f90a90c26d2 - Build
    libdwarf/20191104:28400624abf5a4bc5194b7a7b98fa99fa1d25294 - Build
    libelf/0.8.13:f568eec00a82af2100dc006430c1be98df6d77fa - Build
    libevent/2.1.12:a6dc99ab7b28672602d39689531d060dceeb11b8 - Build
    libiberty/9.1.0:f568eec00a82af2100dc006430c1be98df6d77fa - Cache
    libiconv/1.17:f568eec00a82af2100dc006430c1be98df6d77fa - Cache
    librdkafka/1.9.1:5dad4be5f1860b0ddeb293887de9126bd3f1a73e - Build
    libsodium/cci.20220430:2f84a3c71e72af1f0d7419915319547f6a314b38 - Cache
    lz4/1.9.4:f568eec00a82af2100dc006430c1be98df6d77fa - Cache
    lzo/2.10:f568eec00a82af2100dc006430c1be98df6d77fa - Cache
    marisa/0.2.6:65d0c6387c314520223dd15a4a7aadd3107d2214 - Cache
    nlohmann_json/3.11.2:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    onetbb/2021.9.0:3a9dcdcf620dbce5945dca81a6713b2de46a9144 - Cache
    openssl/3.1.2:92316dc4af529b833e722d166bd3e99a815720ee - Build
    opentelemetry-cpp/1.8.1.1@milvus/dev:27b9f120f696b900812dc19a78071293361b214d - Build
    opentelemetry-proto/0.19.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    prometheus-cpp/1.1.0:f52aa4630c030c8b05dfc05aab4c6c1ca709df01 - Build
    protobuf/3.21.4:bd2be2a8b53548ddd6c9941d952979f99c859162 - Build
    rapidxml/1.13:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    re2/20230301:8e571da4843ef00036a7b515c7b68476001d4fb1 - Cache
    rocksdb/6.29.5@milvus/dev:894a203837f61cdd1040c1655aae2a7cbea8d6a7 - Build
    snappy/1.1.9:8e571da4843ef00036a7b515c7b68476001d4fb1 - Cache
    thrift/0.17.0:5925601e2eba959b630ab60b5a6576df04b4f0ff - Build
    xsimd/9.0.1:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    xz_utils/5.4.0:f568eec00a82af2100dc006430c1be98df6d77fa - Cache
    yaml-cpp/0.7.0:8e571da4843ef00036a7b515c7b68476001d4fb1 - Cache
    zlib/1.2.13:f568eec00a82af2100dc006430c1be98df6d77fa - Cache
    zstd/1.5.4:b66e2864688f2f956134903a4bfb901659fda630 - Cache
Build requirements
    autoconf/2.71 from 'conancenter' - Cache
    automake/1.16.5 from 'conancenter' - Cache
    b2/4.10.1 from 'conancenter' - Cache
    bison/3.8.2 from 'conancenter' - Cache
    cmake/3.29.2 from 'conancenter' - Cache
    flex/2.6.4 from 'conancenter' - Cache
    gnu-config/cci.20210814 from 'conancenter' - Cache
    libtool/2.4.7 from 'conancenter' - Cache
    m4/1.4.19 from 'conancenter' - Cache
    pkgconf/1.9.3 from 'conancenter' - Cache
    pkgconf/2.1.0 from 'conancenter' - Cache
Build requirements packages
    autoconf/2.71:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    automake/1.16.5:3c28ba69276b46fd46e9c2060ba991d725ccab43 - Cache
    b2/4.10.1:4e1751b0fa83186dec61c3f59d918b6b17b28aad - Cache
    bison/3.8.2:82c68759e9a15373ec482afb0806f910cb2244ff - Build
    cmake/3.29.2:cc471ed355602ffa7007968c83aa4e7e648a38b5 - Cache
    flex/2.6.4:82c68759e9a15373ec482afb0806f910cb2244ff - Build
    gnu-config/cci.20210814:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    libtool/2.4.7:ced2f1e9648b922b79d7997fe3771c72f779abb1 - Build
    m4/1.4.19:3eb32b976fb0626f3c40a8b87ace72156aa44204 - Cache
    pkgconf/1.9.3:3eb32b976fb0626f3c40a8b87ace72156aa44204 - Cache
    pkgconf/2.1.0:3eb32b976fb0626f3c40a8b87ace72156aa44204 - Cache

Installing (downloading, building) binaries...
abseil/20230125.3: Already installed!
aws-c-common/0.8.2: Already installed!
b2/4.10.1: Already installed!
benchmark/1.7.0: Already installed!
bzip2/1.0.8: Already installed!
c-ares/1.19.1: Already installed!
cmake/3.29.2: Already installed!
cmake/3.29.2: Appending PATH environment variable: /Users/user/.conan/data/cmake/3.29.2/_/_/package/cc471ed355602ffa7007968c83aa4e7e648a38b5/CMake.app/Contents/bin
cmake/3.29.2: Appending PATH environment variable: /Users/user/.conan/data/cmake/3.29.2/_/_/package/cc471ed355602ffa7007968c83aa4e7e648a38b5/CMake.app/Contents/bin
crc32c/1.1.1: Already installed!
double-conversion/3.2.1: Already installed!
fmt/9.1.0: Already installed!
gflags/2.2.2: Already installed!
gnu-config/cci.20210814: Already installed!
gtest/1.13.0: Already installed!
libbacktrace/cci.20210118: Already installed!
libiberty/9.1.0: Already installed!
libiconv/1.17: Already installed!
libsodium/cci.20220430: Already installed!
lz4/1.9.4: Already installed!
lzo/2.10: Already installed!
m4/1.4.19: Already installed!
marisa/0.2.6: Already installed!
marisa/0.2.6: Appending PATH env var with : '/Users/user/.conan/data/marisa/0.2.6/_/_/package/65d0c6387c314520223dd15a4a7aadd3107d2214/bin'
nlohmann_json/3.11.2: Already installed!
onetbb/2021.9.0: Already installed!
opentelemetry-proto/0.19.0: Already installed!
pkgconf/1.9.3: Already installed!
pkgconf/2.1.0: Already installed!
rapidxml/1.13: Already installed!
re2/20230301: Already installed!
snappy/1.1.9: Already installed!
xsimd/9.0.1: Already installed!
xz_utils/5.4.0: Already installed!
yaml-cpp/0.7.0: Already installed!
zlib/1.2.13: Already installed!
zstd/1.5.4: Already installed!
autoconf/2.71: Already installed!
aws-c-cal/0.5.13: WARN: Build folder is dirty, removing it: /Users/user/.conan/data/aws-c-cal/0.5.13/_/_/build/00ac2e7c1fb86e44b1e5df0cd4cecf2574400432
aws-c-cal/0.5.13: Copying sources to build folder
aws-c-cal/0.5.13: Building your package in /Users/user/.conan/data/aws-c-cal/0.5.13/_/_/build/00ac2e7c1fb86e44b1e5df0cd4cecf2574400432
aws-c-cal/0.5.13: Generator txt created conanbuildinfo.txt
aws-c-cal/0.5.13: Calling generate()
aws-c-cal/0.5.13: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
aws-c-cal/0.5.13: Preset 'release' added to CMakePresets.json. Invoke it manually using 'cmake --preset release'
aws-c-cal/0.5.13: If your CMake version is not compatible with CMakePresets (<3.19) call cmake like: 'cmake <path> -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=/Users/user/.conan/data/aws-c-cal/0.5.13/_/_/build/00ac2e7c1fb86e44b1e5df0cd4cecf2574400432/build/Release/generators/conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release'
aws-c-cal/0.5.13: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
aws-c-cal/0.5.13: Aggregating env generators
aws-c-cal/0.5.13: Calling build()
aws-c-cal/0.5.13: Apply patch (backport): Link to CoreFoundation on Apple
aws-c-cal/0.5.13: CMake command: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/Users/user/.conan/data/aws-c-cal/0.5.13/_/_/build/00ac2e7c1fb86e44b1e5df0cd4cecf2574400432/build/Release/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/Users/user/.conan/data/aws-c-cal/0.5.13/_/_/package/00ac2e7c1fb86e44b1e5df0cd4cecf2574400432" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/Users/user/.conan/data/aws-c-cal/0.5.13/_/_/build/00ac2e7c1fb86e44b1e5df0cd4cecf2574400432/src"
CMake Deprecation Warning at CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Using Conan toolchain: /Users/user/.conan/data/aws-c-cal/0.5.13/_/_/build/00ac2e7c1fb86e44b1e5df0cd4cecf2574400432/build/Release/generators/conan_toolchain.cmake
-- Conan toolchain: Setting CMAKE_POSITION_INDEPENDENT_CODE=ON (options.fPIC)
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
-- The C compiler identification is Clang 15.0.7
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/homebrew/bin/ccache - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test HAS_FPIC_FLAG
-- Performing Test HAS_FPIC_FLAG - Success
-- Performing Test HAS_64BIT_FILE_OFFSET_BY_DEFAULT
-- Performing Test HAS_64BIT_FILE_OFFSET_BY_DEFAULT - Success
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test HAS_WGNU
-- Performing Test HAS_WGNU - Success
-- Performing Test NO_GNU_EXPR
-- Performing Test NO_GNU_EXPR - Success
-- Performing Test HAVE_SYSCONF
-- Performing Test HAVE_SYSCONF - Success
-- Performing Test HAS_SANITIZERS
-- Performing Test HAS_SANITIZERS - Success
-- attempting to use sanitizer list address;undefined
-- Conan: Target declared 'AWS::aws-c-common'
-- Configuring done (1.3s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/user/.conan/data/aws-c-cal/0.5.13/_/_/build/00ac2e7c1fb86e44b1e5df0cd4cecf2574400432/build/Release
aws-c-cal/0.5.13: CMake command: cmake --build "/Users/user/.conan/data/aws-c-cal/0.5.13/_/_/build/00ac2e7c1fb86e44b1e5df0cd4cecf2574400432/build/Release" '--' '-j11'
[ 16%] Building C object CMakeFiles/aws-c-cal.dir/source/darwin/commoncrypto_hmac.c.o
[ 16%] Building C object CMakeFiles/aws-c-cal.dir/source/cal.c.o
[ 25%] Building C object CMakeFiles/aws-c-cal.dir/source/darwin/securityframework_ecc.c.o
[ 33%] Building C object CMakeFiles/aws-c-cal.dir/source/der.c.o
[ 41%] Building C object CMakeFiles/aws-c-cal.dir/source/darwin/commoncrypto_platform_init.c.o
[ 50%] Building C object CMakeFiles/aws-c-cal.dir/source/hash.c.o
[ 58%] Building C object CMakeFiles/aws-c-cal.dir/source/darwin/commoncrypto_sha256.c.o
[ 66%] Building C object CMakeFiles/aws-c-cal.dir/source/darwin/commoncrypto_sha1.c.o
[ 75%] Building C object CMakeFiles/aws-c-cal.dir/source/darwin/commoncrypto_md5.c.o
[ 91%] Building C object CMakeFiles/aws-c-cal.dir/source/ecc.c.o
[ 91%] Building C object CMakeFiles/aws-c-cal.dir/source/hmac.c.o
/Users/user/.conan/data/aws-c-cal/0.5.13/_/_/build/00ac2e7c1fb86e44b1e5df0cd4cecf2574400432/src/source/darwin/securityframework_ecc.c:409:25: warning: call to undeclared function 'SecItemExport'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    OSStatus ret_code = SecItemExport(cc_key_pair->priv_key_ref, kSecFormatOpenSSL, 0, NULL, &sec_key_export_data);
                        ^
/Users/user/.conan/data/aws-c-cal/0.5.13/_/_/build/00ac2e7c1fb86e44b1e5df0cd4cecf2574400432/src/source/darwin/securityframework_ecc.c:409:66: error: use of undeclared identifier 'kSecFormatOpenSSL'
    OSStatus ret_code = SecItemExport(cc_key_pair->priv_key_ref, kSecFormatOpenSSL, 0, NULL, &sec_key_export_data);
                                                                 ^
1 warning and 1 error generated.
make[3]: *** [CMakeFiles/aws-c-cal.dir/source/darwin/securityframework_ecc.c.o] Error 1
make[2]: *** [CMakeFiles/aws-c-cal.dir/all] Error 2
make[1]: *** [all] Error 2
aws-c-cal/0.5.13: 
aws-c-cal/0.5.13: ERROR: Package '00ac2e7c1fb86e44b1e5df0cd4cecf2574400432' build failed
aws-c-cal/0.5.13: WARN: Build folder /Users/user/.conan/data/aws-c-cal/0.5.13/_/_/build/00ac2e7c1fb86e44b1e5df0cd4cecf2574400432/build/Release
ERROR: aws-c-cal/0.5.13: Error in build() method, line 7
        cmake.build()
        ConanException: Error 2 while executing cmake --build "/Users/user/.conan/data/aws-c-cal/0.5.13/_/_/build/00ac2e7c1fb86e44b1e5df0cd4cecf2574400432/build/Release" '--' '-j11'
conan install failed
make: *** [build-3rdparty] Error 1

### Expected Behavior

Expected the build to complete and binaries to be created.

### Steps To Reproduce

```markdown
Execute the make command on a Mac
```

**Comment by xiaofan-luan** [comment]
for this compilation error, it seems that Security/Security.h can not be found.
maybe you can try to change the aws-c-cal version see if it could help.
I'm using same clang version on x86 macos and it works. I believe we also have people working on macos

**Comment by dugar-tarun** [comment]
My MacOs arch is arm64 and aws-c-cal is installed as a dependency of aws-sdk-cpp/1.9.234, can you suggest an alternative version of this dependency that can help me successfully build the code? Please correct me if I'm wrong, I do not have a lot of experience with Conan.

**Comment by xiaofan-luan** [comment]
https://conan.io/center/recipes/aws-sdk-cpp 

with the conanfile, could you be able to run  conan install conanfile.txt --build=missing?

**Comment by dugar-tarun** [comment]
I am able to install this successfully without any issues.

**Comment by xiaofan-luan** [comment]
seems to be a llvm@15 issue

**Comment by dugar-tarun** [comment]
Any workaround that I can try?

**Comment by xiaofan-luan** [comment]
see https://github.com/milvus-io/milvus/blob/master/DEVELOPMENT.md
brew reinstall llvm@15
export LDFLAGS="-L/opt/homebrew/opt/llvm@15/lib"
export CPPFLAGS="-I/opt/homebrew/opt/llvm@15/include"

**Comment by Reidddddd** [comment]
same issue for my new colleague

the way mentioned didn't work

**Comment by xiaofan-luan** [comment]
it's hard to understand the issue without detailed enviroments:
1. os version
2. go version
3. llvm and cpp version
.....
most likely it can not be reproduced on other's mac so easiest way is to use docker or the recommend configs we have

**Comment by dugar-tarun** [comment]
Yep reinstalling llvm@15 and the env variables don't work.
@Reidddddd Updating to llvm@17 worked, thank you! :)

**Comment by tusm123** [comment]
same issue for me
go: 1.22.4
os: x86 mac
llvm:14

**Comment by xiaofan-luan** [comment]
> same issue for me go: 1.22.4 os: x86 mac llvm:14

I saw people this problem by upgraing llvm version.
LLVM 15 is required. LLVM 16 or 17 is recommended

**Comment by tusm123** [comment]
> > same issue for me go: 1.22.4 os: x86 mac llvm:14
> 
> I saw people this problem by upgraing llvm version. LLVM 15 is required. LLVM 16 or 17 is recommended

Updating to llvm@17 worked, thank you! :)

**Comment by adonis0147** [comment]
I also encountered this issue. I think the solution is to add the CFLAGS `-DTARGET_OS_OSX` (or `-DCMAKE_C_FLAGS="-DTARGET_OS_OSX"` for CMake).

Consider the following snippet to simplify the issue.

```c
#include <Security/Security.h>
#include <stdio.h>

int main() {
  printf("%u\n", kSecFormatOpenSSL);
  return 0;
}
```
---
**OS**: macOS 15.2
**arch**: arm64
**Compiler**: llvm@15

On my machine, I can't compile it by llvm@15.

```shell
$ /opt/homebrew/opt/llvm@15/bin/clang test.c -o test && ./test
test.c:5:18: error: use of undeclared identifier 'kSecFormatOpenSSL'
  printf("%u\n", kSecFormatOpenSSL);
                 ^
1 error generated.
```

I succeeded in compiling it using llvm@16.

```cpp
$ /opt/homebrew/opt/llvm@16/bin/clang test.c -o test && ./test
1
```

After adding the CFLAGS `-DTARGET_OS_OSX`, the issue disappeared.

```shell
$ /opt/homebrew/opt/llvm@15/bin/clang -DTARGET_OS_OSX test.c -o test && ./test
1
```

**Comment by aurelianInc** [comment]
Got same error while building with llmv 19. llvm 17 worked.

**Comment by wodadehencou** [comment]
llvm@15 and llvm@19 can not work, llvm@17 worked
