### ISSUE TITLE
[Feature]: cold-hot data cache

### ISSUE THREAD

**Issue by njjry** [milvus-io/milvus#32793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Hello, 

I see on the Milvus document it says: Milvus plans to implement cold-hot data separation on a memory- or SSD-based cache pool. May I know if this feature has been implemented or not? Thanks

**Comment by xiaofan-luan** [comment]
this is under heavy development. 
here is one of the largest pr if you are interested https://github.com/milvus-io/milvus/pull/32567
Not released yet
