### ISSUE TITLE
[Bug]: loading collection stuck in Attu 

### ISSUE THREAD

**Issue by Jonxjdong** [milvus-io/milvus#32834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.16
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/6297023/c2945e80-cc47-460e-be09-8b701ef2bba3)

when loading the collection above with 500million vectors, it stuck at 6% for long time and failed.

**Comment by shanghaikid** [comment]
is it still loading after you refreshed the attu page?

**Comment by xiaofan-luan** [comment]
usually this is not an attu issue.
Please offer server side log and there should be more clue why load fail

**Comment by yanliang567** [comment]
@Jonxjdong Could you please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.
Also if convenient, please try on latest milvus 2.3.15 or 2.4.1 as 2.2.16 is quite old

/assign @Jonxjdong 
/unassign

**Comment by Mr-Shivam-Sinha** [comment]
Facing the same Issue. Collection is not loading. and getting the following error when trying to query the collection through python : 
RPC error: [search], <MilvusException: (code=65535, message=failed to search: attempt #0: collection=449622182549495126: collection not loaded: unrecoverable error)>, <Time:{'RPC start': '2024-06-24 18:16:40.294520', 'RPC error': '2024-06-24 18:16:40.365075'}>

![image](https://github.com/milvus-io/milvus/assets/91791802/4a348335-f999-4bcf-8854-6d630a2094a5)

**Comment by yanliang567** [comment]
@Mr-Shivam-Sinha please offer the full milvus logs as comments above, we cannot help without logs
