### ISSUE TITLE
[Bug]: SIGSEGV when dropping collection if compaction disabled

### ISSUE THREAD

**Issue by zhengbuqian** [milvus-io/milvus#32861]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
```

### Current Behavior

if we disable compaction in milvus.yaml, then try to drop a collection, the program crashes.

cause: in https://github.com/milvus-io/milvus/blob/17a79f4ca90749472899318ffbb6c4684fc7f169/internal/datacoord/services.go#L621, if compaction is disabled, `s.compactionHandler` is null, calling method on it cause SIGSEGV

**Comment by XuanYang-cn** [comment]
ongoing

**Comment by XuanYang-cn** [comment]
https://github.com/milvus-io/milvus/pull/31068

**Comment by XuanYang-cn** [comment]
https://github.com/milvus-io/milvus/issues/31059

**Comment by zhengbuqian** [comment]
did not find https://github.com/milvus-io/milvus/issues/31059, closing this and we can track the issue there.
