### ISSUE TITLE
[Enhancement]: Support ListIndexes with collectionID batch

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#32888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

1. when collection number becomes huge, list index will take many rpcs to run, especially for the index checker.
2. if we can fetch index info per batch, this dramatically reduce the cost of ipc.
3. we can further improve this by only run index checker if there are some recent index changes.

### Why is this needed?

1.  ListIndexes(ctx context.Context, req *indexpb.ListIndexesRequest) (*indexpb.ListIndexesResponse, error)  support a way to fetch all the collection indexInfo (could be multiple rpcs,  everthing wrapped in a helper)
2. Add another LatestIndexVersion check, each time index param change, index version increase. Query can use cached info if latest index version not change.

**Comment by niebayes** [comment]
Please assign to me.

**Comment by xiaofan-luan** [comment]
/assign @niebayes 
thanks for the helping
