### ISSUE TITLE
[Bug]: the Collection can not load , after OOM

### ISSUE THREAD

**Issue by yesyue** [milvus-io/milvus#32894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 16c128g x 41
- GPU: 0
- Others:
```

### Current Behavior

i have 40 query node , every node 128G memory .
1、insert 4000万 entities into one collection ,  and sometimes delete some entities 
2、only one query node , memory increase to  120G+++  , and happen  OOM
3、I reload the collection againt and again ,  and it  always can not load .  Every time i load , only one query node  memory increase to 120G+++ ,  and  always OOM .

### Steps To Reproduce

```markdown
i have 40 query node , every node 128G memory .
1、insert 4000万 entities into one collection ,  and sometimes delete some entities 
2、only one query node , memory increase to  120G+++  , and happen  OOM
3、I reload the collection againt and again ,  and it  always can not load .  Every time i load , only one query node  memory increase to 120G+++ ,  and  always OOM .
```

**Comment by yanliang567** [comment]
my guess there are not enough resource in datanode or indexnode, that could be catch up the writing throughput in the system, which causes too much growing segments in the querynode delegator and then OOM.  @yesyue could you please offer the full milvus pods logs for investigation? Also please attach the etcd backup for investigation, Check this: https://github.com/milvus-io/birdwatcher for details about how to backup etcd with birdwatcher

/assign @yesyue
