### ISSUE TITLE
[Bug]: The query node fails to exit normally during rolling upgrades

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#32901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3-20240508-89e6b6ae-amd64）--> 2.4-20240508-19f09206-amd64 
- Deployment mode(standalone or cluster):mixcoord and cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/12268675/7e6160d7-b838-4145-99f6-7fa6df6c62f6)

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/rolling_update_for_operator_test_simple/detail/rolling_update_for_operator_test_simple/3359/pipeline

log:
[artifacts-kafka-mixcoord-3359-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/15260456/artifacts-kafka-mixcoord-3359-server-logs.tar.gz)

**Comment by weiliu1031** [comment]
please verify this with latest image

**Comment by zhuwenxing** [comment]
verified and fixed in master-20240511-8a9a4219-amd64

**Comment by zhuwenxing** [comment]
failed for v2.4.1 -- > master-20240524-36cbce4d-amd64
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/rolling_update_for_operator_test_simple/detail/rolling_update_for_operator_test_simple/3509/pipeline

log:
[artifacts-kafka-mixcoord-3509-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/15450172/artifacts-kafka-mixcoord-3509-server-logs.tar.gz)

![image](https://github.com/milvus-io/milvus/assets/12268675/2fe45fe4-2db5-488b-b16d-e1c54f6b745a)

**Comment by zhuwenxing** [comment]
2.3-latest --> 2.4-latest : pass
v2.4.1 --> 2.4-latest: pass
2.4.1 --> master-latest: failed

**Comment by zhuwenxing** [comment]
v2.4.1 --> master-20240530-589d4dfd-amd64: pass
