### ISSUE TITLE
[Bug]: Milvus process load operation in async fashion taking 3+ seconds

### ISSUE THREAD

**Issue by prrs** [milvus-io/milvus#32905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.1
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): kafka
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 32/128GB
- GPU: No
- Others: n/a
```

### Current Behavior

1. When a call is made from the client SDK, it loads the partition and returns a response.
2. The client starts polling to check the load status.
3. Milvus, running a checker on ~3 seconds interval, kicks in and checks for all the segments that need to be loaded.
4. It loads the segments asynchronously. 

### Expected Behavior

There should be way through time to trigger the load segment should be minimised. It could be an explicit API or Milvus capability can be enahnced to minimise it.  
![Screenshot 2024-05-08 at 9 37 56 PM](https://github.com/milvus-io/milvus/assets/1429074/95a5b8b9-d5d0-4d77-83cc-5007ffe1ca48)
![Screenshot 2024-05-08 at 9 57 23 PM](https://github.com/milvus-io/milvus/assets/1429074/41483744-9bd6-4805-868f-46f1032496b0)
[segmentloading.csv](https://github.com/milvus-io/milvus/files/15260790/segmentloading.csv)
[loadcall.csv](https://github.com/milvus-io/milvus/files/15260793/loadcall.csv)

I have attached two screenshots from proxy logs, where wen can see that milvus client SDK is polling after load.

### Steps To Reproduce

```markdown
1. Make a load call from the Milvus client SDK.
2. We can observe the sequence of calls in the proxy logs, where the load progress is initiated from the client SDK.
3. In the Milvus server log, it can be seen that it takes a few seconds (approximately 2-3 seconds) to trigger the segment load asynchronously after approximately 2-3 seconds.
```

### Milvus Log

[segmentloading.csv](https://github.com/milvus-io/milvus/files/15260815/segmentloading.csv)
[loadcall.csv](https://github.com/milvus-io/milvus/files/15260816/loadcall.csv)

Loadcall.csv - contains logs when load request is being made
segmentloading.csv - contains the logs where segment loading has been triggered in async to load the collection

### Anything else?

na

**Comment by prrs** [comment]
@xiaofan-luan @yiwangdr ^^

**Comment by yanliang567** [comment]
sounds like a enhancement request
/assign @xiaofan-luan

**Comment by prrs** [comment]
@yiwangdr This is important to meet our SLAs. Do we have a timeline for this to available? Thanks. cc: @xiaofan-luan

**Comment by xiaofan-luan** [comment]
> @yiwangdr This is important to meet our SLAs. Do we have a timeline for this to available? Thanks. cc: @xiaofan-luan

I have a small optimization on it but load could takes a couple of seconds.

**Comment by prrs** [comment]
@xiaofan-luan Do we have an understanding that in what scenario it could take 2-3+ seconds? Yi pointed me [here](https://github.com/milvus-io/milvus/blob/c81be9ed7093c2a575a06bf46db53f6decfc9db6/internal/querycoordv2/observers/collection_observer.go#L91),  the observer is scheduled at 1s. So, where time is going and how are proposing to fix it?

**Comment by xiaofan-luan** [comment]
the segment info stats collection takes 3s. 
so even load succeed, querycoord takes 3s to know it

**Comment by xiaofan-luan** [comment]
we can not reduce this to very smaller number because this might cost cpus on cluster with many collections

**Comment by prrs** [comment]
@xiaofan-luan if I refer to the attached logs, speically below lines. I see load segment has been delayed in query node.

```
[2024/05/08 16:26:22.503 +00:00] [DEBUG] [proxy/task.go:1608] ["loadCollectionTask PostExecute"] [traceID=29b1384b458d3207c41324c600f9d382] [role=proxy] [collectionID=449134457672821234]	2024-05-08T21:56:22.503+05:30	593734508922	1715185583	1715185590	unknown		449134457672821234		perf2		perf2-uswest2		cdp1	[ip-10-28-46-11.us](http://ip-10-28-46-11.us/)-west-2.compute.internal	distapps	cdp-perf2-1-trino1	proxy	milvus	proxy-worker-milvusmmapv2-7b48d8cfb5-85n47	1					us-west-2					proxy		cdp	cdp-data-processing-controller	stdout	cdp	[ip-10-48-199-20.us](http://ip-10-48-199-20.us/)-east-2.compute.internal		aws				29b1384b458d3207c41324c600f9d382	us-west-2a

[2024/05/08 16:26:24.205 +00:00] [INFO] [querynodev2/services.go:413] ["received load segments request"] [traceID=c0cf24041d23a00d537e38d10650dee9] [collectionID=449134457672821234] [partitionID=449134457672821235] [shard=milvusmmapv2-rootcoord-dml_1_449134457672821234v0] [segmentID=449134457673021248] [currentNodeID=193] [version=1715185584205012109] [needTransfer=true] [loadScope=Full]	2024-05-08T21:56:24.205+05:30	593734508922		1715185584	1715185589		unknown			449134457672821234				193			perf2		perf2-uswest2		cdp1	[ip-10-29-91-230.us](http://ip-10-29-91-230.us/)-west-2.compute.internal	distapps				cdp-perf2-1-trino1	querynode	milvus	query-worker-milvusmmapv2-6c9b46cbfd-47qs9		1	Full				TRUE	449134457672821235		us-west-2						449134457673021248					cdp	cdp-data-processing-controller	milvusmmapv2-rootcoord-dml_1_449134457672821234v0			stdout	cdp	[ip-10-48-204-237.us](http://ip-10-48-204-237.us/)-east-2.compute.internal				aws					c0cf24041d23a00d537e38d10650dee9	1715185584205012109		us-west-2b
```

Now, below is my understanding, will need a confirmation from you and team.
1. The load collection call, fetch all the partition for a collection and add in the list in the queryworker node manager
2. check load progress fetch the status for query co-ordinator
3. Colleciton observer in query coordinator will upate it every second


Thought  - If query co-ordinator make a syn call to query worker to load the segment, we can save the addtional seconds.

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan if I refer to the attached logs, speically below lines. I see load segment has been delayed in query node.
> 
> ```
> [2024/05/08 16:26:22.503 +00:00] [DEBUG] [proxy/task.go:1608] ["loadCollectionTask PostExecute"] [traceID=29b1384b458d3207c41324c600f9d382] [role=proxy] [collectionID=449134457672821234]	2024-05-08T21:56:22.503+05:30	593734508922	1715185583	1715185590	unknown		449134457672821234		perf2		perf2-uswest2		cdp1	[ip-10-28-46-11.us](http://ip-10-28-46-11.us/)-west-2.compute.internal	distapps	cdp-perf2-1-trino1	proxy	milvus	proxy-worker-milvusmmapv2-7b48d8cfb5-85n47	1					us-west-2					proxy		cdp	cdp-data-processing-controller	stdout	cdp	[ip-10-48-199-20.us](http://ip-10-48-199-20.us/)-east-2.compute.internal		aws				29b1384b458d3207c41324c600f9d382	us-west-2a
> 
> [2024/05/08 16:26:24.205 +00:00] [INFO] [querynodev2/services.go:413] ["received load segments request"] [traceID=c0cf24041d23a00d537e38d10650dee9] [collectionID=449134457672821234] [partitionID=449134457672821235] [shard=milvusmmapv2-rootcoord-dml_1_449134457672821234v0] [segmentID=449134457673021248] [currentNodeID=193] [version=1715185584205012109] [needTransfer=true] [loadScope=Full]	2024-05-08T21:56:24.205+05:30	593734508922		1715185584	1715185589		unknown			449134457672821234				193			perf2		perf2-uswest2		cdp1	[ip-10-29-91-230.us](http://ip-10-29-91-230.us/)-west-2.compute.internal	distapps				cdp-perf2-1-trino1	querynode	milvus	query-worker-milvusmmapv2-6c9b46cbfd-47qs9		1	Full				TRUE	449134457672821235		us-west-2						449134457673021248					cdp	cdp-data-processing-controller	milvusmmapv2-rootcoord-dml_1_449134457672821234v0			stdout	cdp	[ip-10-48-204-237.us](http://ip-10-48-204-237.us/)-east-2.compute.internal				aws					c0cf24041d23a00d537e38d10650dee9	1715185584205012109		us-west-2b
> ```
> 
> Now, below is my understanding, will need a confirmation from you and team.
> 
> 1. The load collection call, fetch all the partition for a collection and add in the list in the queryworker node manager
> 2. check load progress fetch the status for query co-ordinator
> 3. Colleciton observer in query coordinator will upate it every second
> 
> Thought - If query co-ordinator make a syn call to query worker to load the segment, we can save the addtional seconds.

this is doable. but not a good idea for common use cases
1. load can take long time -> more than 1 minutes, sync call is hard to estimate  timeout
2. too many sync call at the same time means many go routines
