### ISSUE TITLE
[Bug]: Delete might lose under handoff

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#32915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

insert 3000 datas.
delete 1 entity
flush
wait for handoffs
query
some times we can still see the deleted data.

watch DML channel and load segment happens concurrently.
when watch DML channel is not done,  loadL0Segments is not done, so L0 cache is not full.
Load segment will need l0 deletion cache for filling all the delete data.

**Comment by aoiasd** [comment]
May relate https://github.com/milvus-io/milvus/issues/33247.
