### ISSUE TITLE
[Enhancement]: Support monitoring  on standalone

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#32981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

see discussion https://github.com/milvus-io/milvus/discussions/32962#discussioncomment-9391729.

I don't forsee any reason why we couldn't the monitoring in standalone, maybe some physical metrics can not be seperate, like cpu usage and monitoring

**Comment by zhuwenxing** [comment]
![image](https://github.com/milvus-io/milvus/assets/12268675/92aaf393-7274-49e9-88cb-ad4143036891)

it was already supported in standalone

**Comment by king1302217** [comment]
@zhuwenxing This monitor is for k8s cluster version. Info such as namespace, instance can't find in standalone milvus metrics.

**Comment by xiaofan-luan** [comment]
I think you will need to setup prometheus metrics?
it could be still collected but grapfana might need to be modified

**Comment by king1302217** [comment]
@xiaofan-luan I have already setup prometheus metrics. The problem is that I don't want to modify each grafana panel to standalone milvus metrics...

**Comment by zhuwenxing** [comment]
> @zhuwenxing This monitor is for k8s cluster version. Info such as namespace, instance can't find in standalone milvus metrics.

How do you deploy your standalone? k8s or docker?

In my environment, if the instance is deploy by k8s, this panel can be used for standalone and cluster both.
![image](https://github.com/milvus-io/milvus/assets/12268675/f33a20a9-6c64-49f4-9844-0cef0e2950a6)

**Comment by zhuwenxing** [comment]
If the instance is deployed through Docker, then we don't actually provide a corresponding monitoring dashboard. So this issue has nothing to do with standalone or cluster, but rather with whether it's a Docker deployment or a Kubernetes deployment.
