### ISSUE TITLE
[Bug]: partition name breaks the name rule if trying to create a parititon with name="12name"

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#32998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20240508-3d78b90f
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): 2.5.0rc18
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/82361606/ffbdab54-b674-4457-b38d-828598a64275)
"12name" starts with number, so it is not a valid partition name for milvus, but milvus did not check that.

### Expected Behavior

As the doc of https://milvus.io/docs/limitations.md says:
![image](https://github.com/milvus-io/milvus/assets/82361606/b5c814aa-8031-496e-b091-fe2bed457b16)
Milvus shall report error if name is invalid

**Comment by congqixia** [comment]
It's easy to forbid partition name starting with number, but this will cause legacy partitions unable to be operated on after upgraded to this image. 
Can we use non-restrict mode verifying partition name other than `CreatePartition`?
https://github.com/milvus-io/milvus/blob/f6777267e31c4270dbde0e2b02b3a3a46457579c/internal/proxy/util.go#L215-L246
@czs007 @xiaofan-luan @yanliang567  WDYGT?

**Comment by xiaofan-luan** [comment]
keep the old convention？
I don't foresee any reason right now we need to forbid name start with numeric number. but this is not recommneded

**Comment by congqixia** [comment]
> keep the old convention？ I don't foresee any reason right now we need to forbid name start with numeric number. but this is not recommneded

lgtm, +1

**Comment by yanliang567** [comment]
close as won't for compatible with previous releases.
