### ISSUE TITLE
[Enhancement]: consider replacing `bloom filters` with `xor filters` / `binary fuse filters`

### ISSUE THREAD

**Issue by alexanderguzhva** [milvus-io/milvus#32995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

consider replacing `bloom filters` with `xor filters` / `binary fuse filters`

an image from https://github.com/FastFilter/xor_singleheader
<p align="center">
    <img src="https://github.com/FastFilter/xor_singleheader/raw/master/figures/comparison.png", width="600">
</p>

**Comment by xiaofan-luan** [comment]
is there any performance profiling result?

**Comment by alexanderguzhva** [comment]
significantly faster.

https://arxiv.org/pdf/2201.01174

![Untitled](https://github.com/milvus-io/milvus/assets/10901481/2097605f-432b-4a9d-aee7-2c71fbfb8bfe)


Alternatively, we may use `Blocked Bloom filters' (https://save-buffer.github.io/bloom_filter.html; an example of a go package is https://github.com/greatroar/blobloom)

**Comment by xiaofan-luan** [comment]
@weiliu1031 let's profiling all the filter in multiple dimensions:
1. write speed
2. query speed/batch query speed
3. memory utilization
4. if it can merge without loss precision it is a big plus
