### ISSUE TITLE
Broken images in mishard document

### ISSUE THREAD

**Issue by hnyoumfk** [milvus-io/milvus#3299]
**Please state your issue using the following template and, most importantly, in English.**

**Location of incorrect documentation**
https://milvus.io/docs/v0.10.1/mishards.md

**Describe the problems or issues found in the documentation**
Broken images [here](https://milvus.io/docs/v0.10.1/mishards.md), e.g: https://milvus.io/static/c00635f52b4cbe35ebd6bb9ce5af1db2/302a4/image_04.png

**Comment by AmyYH** [comment]
Images fixed. Please refer to https://milvus.io/docs/v0.10.2/mishards.md.
