### ISSUE TITLE
[Bug]: The entities that had been deleted were queried again after a day.

### ISSUE THREAD

**Issue by DingMStar** [milvus-io/milvus#33015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.1
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): Pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2): java 2.3.1
- OS(Ubuntu or CentOS): Ubuntu 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

A day ago, I batch deleted 147 pieces of entity data. Immediately after the deletion, the query returned no results. However, after a day, the deleted data reappeared. I executed the deletion by calling the following method and also received the deletion return information, but why did it recover?
![image](https://github.com/milvus-io/milvus/assets/37872766/dd7a8541-d757-4da7-9094-0ed370294bb5)
![image](https://github.com/milvus-io/milvus/assets/37872766/6978c76c-eeca-46c6-b803-35b3bcbf4d68)

**Comment by xiaofan-luan** [comment]
please use latest 2.3.15, many of the delete issue has been fix @DingMStar

**Comment by zhansg** [comment]
> please use latest 2.3.15, many of the delete issue has been fix @DingMStar

是只需要升级sdk还是milvus库需要升级?

**Comment by yanliang567** [comment]
Upgrade Milvus to 2.3.15 or 2.4.1 could help.
please keep us posted if it does not

/assign @zhansg 
/unassign
