### ISSUE TITLE
Some of the official websites don't work

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#3302]
**Please state your issue using the following template and, most importantly, in English.**

**Location of incorrect documentation**
[https://github.com/milvus-io/bootcamp/blob/0.10.0/benchmark_test/lab1_sift1b_1m.md](url)
[https://www.milvus.io/docs/zh-CN/reference/milvus_config/](url)

**Describe the problems or issues found in the documentation**
The Milvus configuration link in the README section of Bootcamp opens 404

**Comment by AmyYH** [comment]
@JackLCL Please help resolve this bootcamp doc. Thx!
