### ISSUE TITLE
Docs: README links to 2.0.x getting started information instead of latest

### ISSUE THREAD

**Issue by timheuer** [milvus-io/milvus#33056]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

In the README of the repo the getting started links are linking to the 2.0.x docs, which can cause confusion when using the latest as some of the configuration aspects have changed and that 2.0.x page also has bad links on it now as well.

### Current Behavior

Click standalone getting started on README

### Expected Behavior

Go to latest version information

**Comment by yanliang567** [comment]
@xiaofan-luan  I agree that we shall update a new readme. who is the best to do that?
/assign @xiaofan-luan 
/unassign
