### ISSUE TITLE
[Bug]: Pods fail with permission denied error "failed: open /milvus/configs/milvus.yaml: permission denied"

### ISSUE THREAD

**Issue by edwardquarm** [milvus-io/milvus#33057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.4.1
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.1
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU:
- Others:
```

### Current Behavior

When I try to install milvus helm chart on GKE standard cluster, the following pods go into CrashLoopBackOff
- datacoord
- datanode
- indexcoord
- indexnode
- proxy
- pulsar-bookie-init
- querycoord
- querynode
- rootcoord

The pods fail with the message: ``write failed: open /milvus/configs/milvus.yaml: permission denied``
It appears that this issue was reported by another user and fixed here: https://github.com/milvus-io/milvus/issues/22516
However, I'm encountering the same issue.

### Expected Behavior

Milvus should get deployed to GKE standard cluster

### Steps To Reproduce

```markdown
helm repo add zilliztech https://zilliztech.github.io/milvus-helm
helm repo update
helm install milvus zilliztech/milvus -n platform
```

**Comment by yanliang567** [comment]
/assign @LoveEachDay 
please help to take a look
/unassign
