### ISSUE TITLE
[Enhancement]: Enable root password configuration at startup

### ISSUE THREAD

**Issue by timheuer** [milvus-io/milvus#33058]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What would you like to be added?

When using standalone, it would be helpful to set the root password to something other than default using an environment value and/or config. like MILVUS_ROOT_PASSWORD.  This would enable the standalone container to start in a more secure manner and configurable, rather than having to start a Milvus instance, then have a separate client use the default admin password, and update itself.  Saving a step.

### Why is this needed?

The default password for root is well documented. Not having a way to change this in config for startup of the standalone leaves an opening for even authenticated commands to just guess at the default (it's the equivalent of admin/admin).  Other containers I've worked with enable setting the root password as a configurable aspect in environment variables so that it is secure at startup.

**Comment by ckrapu-nv** [comment]
The suggestion from @timheuer would also reduce the frequency of questions like [issues/33495](https://github.com/milvus-io/milvus/issues/33495).

**Comment by xiaofan-luan** [comment]
put password in config or file seems to be a very dangerous behaviour.
Any best practice on a k8s cluster?

**Comment by timheuer** [comment]
A few other db providers do this. Environment variables over file-based configs

**Comment by timheuer** [comment]
Any chance of considering a design here?

**Comment by timheuer** [comment]
The docs only seem to hint at 'change the password' as a solution, but this isn't ideal either versus having a config-based setup that is not a globally-known default. We'd prefer a design consistent with other container runtimes/apps that follow patterns where an ENV variable can be set with a password that upon startup the container knows to use that instead of a default, if set.  Something like `COMMON_SECURITY_ROOT_TOKEN`. For example Qdrant, which uses an API key approach, enables defining the API key in an environment variable and clients need that to connect, but there is no default that is known. It is set at the container ENV level and used upon startup.

**Comment by xiaofan-luan** [comment]
@timheuer 
Agreed that use ENV or configs is for initial setup is an option.

I thought we just need to change a little bit code here

the default username password is a constant at
constant.go
	UserRoot            = "root"
	DefaultRootPassword = "Milvus"

we need to change it to component_param.go as a config similar to AuthorizationEnabled

anyone want to take this feature?

**Comment by timheuer** [comment]
@xiaofan-luan Not a Go developer so the repo is not entirely intuitive to me and I've had onramp issues already with the devcontainer, but with your pointers, is it as simple as this? (of course no tests changed)?

https://github.com/timheuer/milvus/commit/98ce4cb1312aff5b4532380ff2985576cf44e207

Is anyone on core team able to make the change to ensure better security for the container?

**Comment by xiaofan-luan** [comment]
@SimFG could you have on this?

**Comment by SimFG** [comment]
@timheuer I looked at your commit and it basically meets the requirements. I will modify it slightly and submit a PR.

**Comment by timheuer** [comment]
Amazing thank you @xiaofan-luan and @SimFG! How long from a merge to when it shows up in a docker image we can start consuming.  And I assume the pattern to follow of setting an env to `COMMON_SECURITY_DEFAULTROOTPASSWORD` would set it (as well in yaml).  I'd love to give it a spin on a docker image and make the necessary changes then in our platform.

**Comment by SimFG** [comment]
@timheuer  The PR has been merged into the master branch, and will be picked to the 2.4 branch today. What version of milvus are you using now? If you want to include this PR, you can only use the latest master dev image.

**Comment by timheuer** [comment]
Thanks @SimFG I confirmed functionality with `master-20240718-c8bf6c8a-amd64` setting `env` variable `COMMON_SECURITY_DEFAULTROOTPASSWORD` and works.  When might we expect this to get into `2.4-latest` or later (as it looks like that is days old and wouldn't have this)?

**Comment by SimFG** [comment]
@timheuer We should release version 2.4.7 next week, which will have this improvement

**Comment by timheuer** [comment]
Thanks @SimFG! Can you help me understand your docker tagging though? 2.4-latest I would have assumed is the same as at least v2.4.6, but the hashes are different (and release date of 2.4-latest is a week older than v2.4.6)
2.4-latest: https://hub.docker.com/layers/milvusdb/milvus/2.4-latest/images/sha256-a3d2832d6980b01899dde756dab6f97171dc5d16b2f8d3dda2629b4ff95ad696?context=explore
v2.4.6: https://hub.docker.com/layers/milvusdb/milvus/v2.4.6/images/sha256-dd31ca45f5faeb5cbd665ca72a360367a542d4800d23377eeb06f7620c351017?context=explore

**Comment by xiaofan-luan** [comment]
@SimFG 
please also modify the document as well

**Comment by SimFG** [comment]
@timheuer 2.4-latest is expected to be the dev image of the latest 2.4 branch, but due to some problems with the internal pipeline, there may be some problems with the update. Version 2.4.6 is our official version for the public

**Comment by timheuer** [comment]
Thanks for update @SimFG -- you mentioned that `2.4-latest` is a 'dev image' -- I kinda expected it to be a semver production image of `2.4.6`? is that not a correct understanding?  Is there a better doc that describes the tags? We've been trying to snap to major.minor with our dependencies and ideally would follow `major.minor-latest` tagging.

**Comment by SimFG** [comment]
@timheuer no, the `2.4-latest` image is not recommended to use, it has not been fully tested and is only used for internal testing

**Comment by timheuer** [comment]
Thanks @SimFG it sounds like if we want to snap to validated images we'll have to use `major.minor.revision` tagged docker images then as a best practice?

**Comment by SimFG** [comment]
@timheuer yes, link: https://github.com/milvus-io/milvus/releases

**Comment by timheuer** [comment]
Thanks @SimFG I'll await the 2.4.7 official image to make our product change.

I'd ask that you may reconsider container tagging here.  By definition it would seem odd that `2.3-latest` is not meant for production when it has "latest" tagging which is fairly standard for meaning, well, the latest.  Having something that is tagged `v2.4.7` and that does not match `2.4-latest` seems odd as well.  I'd encourage re-thinking the release/tag strategy to adhere to more common expectations of semver + tagging as I would expect anything `-latest` to include the revision latest of the major.minor.  If something is meant for dev-only, then using `-dev-latest` or something would be better as well.  Thanks for considering.

**Comment by SimFG** [comment]
@timheuer I quite agree with your view. @xiaofan-luan what do you think?

**Comment by xiaofan-luan** [comment]
For milvus, every 2.4-branch/2.3-brnch is ready to production. 

but we recommend to use release tag in production because for each of the release QA team will run a full regression and we don't have guarantee on branches.

Generally speaking, we conurrently maintain multiple developing branch and only tags is the actaul release version. As you said, 2.4 branch is 2.4-dev-latest actually

**Comment by timheuer** [comment]
So @xiaofan-luan if I understand you correctly, there is not a 'release' docker image that is semver-compliant. You can't grap a release `2.x` image and expect it to float to any `2.x.y` updates.  And your policy is that consumers should take explicit release versions (`2.x.y`)?

**Comment by xiaofan-luan** [comment]
Exactly. The 2.4 branch functions as the development branch for 2.4. We continuously merge bug fixes and small features into this branch. Once we believe it has reached a stable state and includes all intended features, the maintainer team will create a 2.x.y tag. This tagged version will then be released using all the deployment methods.

Mean time, master works as the dev branch of 2.5. Once 2.5.0 released, master moved to 2.6 latest dev and 2.5 branch becomes active maintained branch.

We maintain 3 different branch at the same:
2.3 - mainly critical bugfix, stable release
2.4 - small features, active bug fixes, stable release with latest features
master - all patches included, 2.5 release candidate

**Comment by xiaofan-luan** [comment]
2.4 latest is the daily build image that mainly for test purpose and user who need instant fix

**Comment by timheuer** [comment]
I understand now @xiaofan-luan I just disagree with the tagging strategy based on how others in the Docker ecosystem do it. Per this strategy there is no production image that is major.minor I can rely on and continue to get production updates. I had incorrectly assumed that `latest` was a production latest tag, and it is not. I'd again ask you to reconsider your tagging strategy, but at least I understand it now that there is no major.minor production images.

Using RabbitMQ (https://hub.docker.com/_/rabbitmq/tags?page=&page_size=&ordering=&name=3.13) as another example, 
latest == 3.13 == 3.13.6

I'll await the official `2.4.7` image that we can change to and snap to that as new minimum for us.

**Comment by Alirexaa** [comment]
@timheuer, `2.4.7` image released. I will open an issue in Aspire for this.

**Comment by timheuer** [comment]
Nice. Verified it works for me. @SimFG seems good to close this I think then.

**Comment by ycyin** [comment]
On initial startup, the environment variable 'COMMON_SECURITY_DEFAULTROOTPASSWORD' works for me. But if  already have data (the `/var/lib/milvus directory` is not empty), how to change the password of the root account, and is there any other design for this?

**Comment by xiaofan-luan** [comment]
you can use modify password to update root password

**Comment by ycyin** [comment]
> you can use modify password to update root password

I only found a way to modify it through the RPC interface, and now there is no way to modify it through the command line?
Now: https://milvus.io/docs/rbac.md
```py
client.update_password(
    user_name='user_1',
    old_password='P@ssw0rd',
    new_password='P@ssw0rd123'
)
```

Expect to have a command-line tool, like ['delete user`](https://milvus.io/docs/cli_commands.md#delete-user):
```bash
update user ...
```
