### ISSUE TITLE
It seems that milvus describes collection for 4 times during a GET /collections request.

### ISSUE THREAD

**Issue by Vergissmeinicht** [milvus-io/milvus#3306]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
I find that milvus do 'DescribeCollection" operation for 4 times for each collection during request getting all collections. Part of the log is shown below.
[milvus_log.txt](https://github.com/milvus-io/milvus/files/5089367/milvus_log.txt)

**Steps/Code to reproduce behavior**
Just request GET /collections.

**Expected behavior**

**Environment details**
- Method of installation (Docker)
- Milvus version (v0.9.1)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
The WebRequestHandler::ShowCollections() called WebRequestHandler::GetCollectionMetaInfo() 
The GetCollectionMetaInfo() called CountCollection()
The CountCollection() called DescribeCollection()

**Comment by Vergissmeinicht** [comment]
> The WebRequestHandler::ShowCollections() called WebRequestHandler::GetCollectionMetaInfo()
> The GetCollectionMetaInfo() called CountCollection()
> The CountCollection() called DescribeCollection()

Thanks,that's how it is implemented.
