### ISSUE TITLE
[Bug]: can not create etcd and minio container by docker-compose

### ISSUE THREAD

**Issue by GreateFang** [milvus-io/milvus#33086]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.3.0-beta
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):v2.2.3
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/32962590/398889d4-9103-4a8d-a68b-3d5b106d1194)
can only start milvusdb，etcd and minio satrt fail
get this error
![image](https://github.com/milvus-io/milvus/assets/32962590/d7e3f90c-325e-4ab3-97fc-e60d3baac165)
Thanks for help!

**Comment by GreateFang** [comment]
ps: I need to install milvus offline， so I run 
sudo python3 save_image.py --manifest docker-compose.yml
in my mac m1 and upload the images to centos

**Comment by GreateFang** [comment]
After updating save_image.py by adding platform arg  , the problem was solved.
![image](https://github.com/milvus-io/milvus/assets/32962590/09db4aff-0cae-4817-997d-f2555fd82efb)

**Comment by yanliang567** [comment]
please try milvus latest release 2.3.15 or 2.4.1

**Comment by GreateFang** [comment]
this problem was solved,and I got a new error. could you help about that?
![image](https://github.com/milvus-io/milvus/assets/32962590/2ea97c5c-8f96-428e-813d-7d5fdf677a8e)
I use hello_milvus.py in
https://github.com/milvus-io/pymilvus/blob/v2.3.0b1/examples/hello_milvus.py

**Comment by yanliang567** [comment]
as the msg says, the memory is not enough to load the data. also please try on latest releaes 2.4.4.
I'd close this issue, please free to file a new one with logs if any problems
