### ISSUE TITLE
fail to deploy ARM Milvus cluster on k8s 

### ISSUE THREAD

**Issue by lijunfeng11** [milvus-io/milvus#33098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.4.1
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS arm64版本
- CPU/Memory: 128
- GPU: VGA compatible controller: Huawei Technologies Co., Ltd. Hi1710 [iBMC Intelligent Management system chip w/VGA support] (rev 01)
- Others:
```

### Current Behavior

使用Helm安装Milvus执行完之后集群系显示的状态一直没有变化

### Milvus Log

[root@master local-path-provisioner]# kubectl describe pod my-milvus
Name:         my-milvus-datacoord-5dff6f95cb-qwfcs
Namespace:    default
Priority:     0
Node:         slave1/192.168.6.243
Start Time:   Thu, 16 May 2024 15:39:05 +0800
Labels:       app.kubernetes.io/instance=my-milvus
              app.kubernetes.io/name=milvus
              component=datacoord
              pod-template-hash=5dff6f95cb
Annotations:  checksum/config: d0865f30b5f61714d042ab10f2b6b2754cbcfe02d2283124495e7522a7b662bd
              cni.projectcalico.org/containerID: 167c4332ccefcf09438fbedc0c7681d9cf1bb6e52f4794d3ff06e85fe0728af2
              cni.projectcalico.org/podIP: 10.244.140.193/32
              cni.projectcalico.org/podIPs: 10.244.140.193/32
Status:       Running
IP:           10.244.140.193
IPs:
  IP:           10.244.140.193
Controlled By:  ReplicaSet/my-milvus-datacoord-5dff6f95cb
Init Containers:
  config:
    Container ID:  docker://77444548187bf8938cc1ea32d5b4f04099d93e64b06f72b6b511d8c642928d4c
    Image:         milvusdb/milvus-config-tool:v0.1.2
    Image ID:      docker-pullable://milvusdb/milvus-config-tool@sha256:c6b78ac8ba1ecd021b28febfd207ca051956599d2381407dd879e74e7e4db612
    Port:          <none>
    Host Port:     <none>
    Command:
      /cp
      /run-helm.sh,/merge
      /milvus/tools/run-helm.sh,/milvus/tools/merge
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 16 May 2024 15:39:08 +0800
      Finished:     Thu, 16 May 2024 15:39:08 +0800
    Ready:          True
    Restart Count:  0
    Environment:    <none>
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  milvus-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      my-milvus
    Optional:  false
  tools:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  kube-api-access-vj8hn:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  56m                  default-scheduler  Successfully assigned default/my-milvus-rootcoord-787d8fd6b8-cl9gd to slave1
  Normal   Pulled     56m                  kubelet            Container image "milvusdb/milvus-config-tool:v0.1.2" already present on machine
  Normal   Created    56m                  kubelet            Created container config
  Normal   Started    56m                  kubelet            Started container config
  Normal   Created    53m (x5 over 56m)    kubelet            Created container rootcoord
  Normal   Started    53m (x5 over 56m)    kubelet            Started container rootcoord
  Normal   Pulled     21m (x10 over 56m)   kubelet            Container image "milvusdb/milvus:v2.4.1" already present on machine
  Warning  BackOff    11m (x63 over 55m)   kubelet            Back-off restarting failed container
  Warning  Unhealthy  66s (x143 over 51m)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 500

**Comment by lijunfeng11** [comment]
[root@master local-path-provisioner]# kubectl get pods
NAME                                    READY   STATUS                  RESTARTS   AGE
my-milvus-datacoord-5dff6f95cb-qwfcs    1/1     Running                 4          40m
my-milvus-datanode-7f4559b69f-fs58l     0/1     Running                 10         40m
my-milvus-etcd-0                        1/1     Running                 0          40m
my-milvus-etcd-1                        1/1     Running                 0          40m
my-milvus-etcd-2                        1/1     Running                 0          40m
my-milvus-indexcoord-8987ddfb7-22zg2    1/1     Running                 0          40m
my-milvus-indexnode-755787b4c4-xjd6s    1/1     Running                 4          40m
my-milvus-minio-0                       1/1     Running                 0          40m
my-milvus-minio-1                       1/1     Running                 0          40m
my-milvus-minio-2                       1/1     Running                 0          40m
my-milvus-minio-3                       1/1     Running                 0          40m
my-milvus-proxy-67c766b8c9-mlwx7        0/1     Running                 10         40m
my-milvus-pulsar-bookie-0               0/1     Init:CrashLoopBackOff   12         40m
my-milvus-pulsar-bookie-1               0/1     Init:CrashLoopBackOff   12         40m
my-milvus-pulsar-bookie-2               0/1     Init:CrashLoopBackOff   12         40m
my-milvus-pulsar-bookie-init-4njzx      0/1     Init:Error              0          38m
my-milvus-pulsar-bookie-init-9k26x      0/1     Init:Error              0          30m
my-milvus-pulsar-bookie-init-jsr85      0/1     Init:Error              0          40m
my-milvus-pulsar-bookie-init-ngssg      0/1     Init:Error              0          40m
my-milvus-pulsar-bookie-init-psczv      0/1     Init:Error              0          39m
my-milvus-pulsar-bookie-init-rzlpr      0/1     Init:Error              0          35m
my-milvus-pulsar-bookie-init-xp9d9      0/1     Init:Error              0          40m
my-milvus-pulsar-broker-0               0/1     Init:CrashLoopBackOff   12         40m
my-milvus-pulsar-proxy-0                0/1     Init:CrashLoopBackOff   12         40m
my-milvus-pulsar-recovery-0             0/1     Init:CrashLoopBackOff   12         40m
my-milvus-pulsar-zookeeper-0            0/1     CrashLoopBackOff        12         40m
my-milvus-querycoord-595cfb67bd-pv8wh   0/1     Running                 10         40m
my-milvus-querynode-54d446464d-nvk28    1/1     Running                 4          40m
my-milvus-rootcoord-787d8fd6b8-cl9gd    0/1     Running                 10         40m

**Comment by yanliang567** [comment]
please check why the pulsar pods are all failed. 
/assign @lijunfeng11 
/unassign

**Comment by yanliang567** [comment]
you need to figure out why pulsar pods are CrashLoopBackOff, describe the pod or share more info about it

**Comment by lijunfeng11** [comment]
> kubectl logs my-milvus-pulsar-bookie-0
Because I don't quite understand k8s, how should I read more error messages

[root@master rbd-eventlog]# kubectl describe pod my-milvus-pulsar-bookie-1
Name:         my-milvus-pulsar-bookie-1
Namespace:    default
Priority:     0
Node:         master/192.168.6.242
Start Time:   Thu, 16 May 2024 17:12:56 +0800
Labels:       app=pulsar
              cluster=my-milvus-pulsar
              component=bookie
              controller-revision-hash=my-milvus-pulsar-bookie-69ddb44cdd
              release=my-milvus
              statefulset.kubernetes.io/pod-name=my-milvus-pulsar-bookie-1
Annotations:  cni.projectcalico.org/containerID: 81309020e6f72da0ef057d6cfe9617eee99a828834cd813a9ca1da6396f1b1f3
              cni.projectcalico.org/podIP: 10.244.219.107/32
              cni.projectcalico.org/podIPs: 10.244.219.107/32
              prometheus.io/port: 8000
              prometheus.io/scrape: true
Status:       Pending
IP:           10.244.219.107
IPs:
  IP:           10.244.219.107
Controlled By:  StatefulSet/my-milvus-pulsar-bookie
Init Containers:
  pulsar-bookkeeper-verify-clusterid:
    Container ID:  docker://ee682c6f895ca9baa3801ca0e0894ad0c6d32ef43b7f10c455dd1950358efc65
    Image:         apachepulsar/pulsar:2.8.2
    Image ID:      docker-pullable://apachepulsar/pulsar@sha256:d538416d5afe03360e10d5beb44bdad33d7303d137fc66c264108426875f61c6
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
    Args:
      
      set -e; bin/apply-config-from-env.py conf/bookkeeper.conf;until bin/bookkeeper shell whatisinstanceid; do
        sleep 3;
      done;
      
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 16 May 2024 17:49:27 +0800
      Finished:     Thu, 16 May 2024 17:49:27 +0800
    Ready:          False
    Restart Count:  12
    Environment Variables from:
      my-milvus-pulsar-bookie  ConfigMap  Optional: false
    Environment:               <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-b4kq2 (ro)
Containers:
  my-milvus-pulsar-bookie:
    Container ID:  
    Image:         apachepulsar/pulsar:2.8.2
    Image ID:      
    Ports:         3181/TCP, 8000/TCP
    Host Ports:    0/TCP, 0/TCP
    Command:
      sh
      -c
    Args:
      bin/apply-config-from-env.py conf/bookkeeper.conf;
      OPTS="${OPTS} -Dlog4j2.formatMsgNoLookups=true" exec bin/pulsar bookie;
      
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:      1
      memory:   2Gi
    Liveness:   http-get http://:8000/api/v1/bookie/state delay=10s timeout=5s period=30s #success=1 #failure=60
    Readiness:  http-get http://:8000/api/v1/bookie/is_ready delay=10s timeout=5s period=30s #success=1 #failure=60
    Environment Variables from:
      my-milvus-pulsar-bookie  ConfigMap  Optional: false
    Environment:               <none>
    Mounts:
      /pulsar/data/bookkeeper/journal from my-milvus-pulsar-bookie-journal (rw)
      /pulsar/data/bookkeeper/ledgers from my-milvus-pulsar-bookie-ledgers (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-b4kq2 (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  my-milvus-pulsar-bookie-journal:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  my-milvus-pulsar-bookie-journal-my-milvus-pulsar-bookie-1
    ReadOnly:   false
  my-milvus-pulsar-bookie-ledgers:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  my-milvus-pulsar-bookie-ledgers-my-milvus-pulsar-bookie-1
    ReadOnly:   false
  kube-api-access-b4kq2:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  41m                  default-scheduler  Successfully assigned default/my-milvus-pulsar-bookie-1 to master
  Normal   Pulled     39m (x5 over 40m)    kubelet            Container image "apachepulsar/pulsar:2.8.2" already present on machine
  Normal   Created    39m (x5 over 40m)    kubelet            Created container pulsar-bookkeeper-verify-clusterid
  Normal   Started    39m (x5 over 40m)    kubelet            Started container pulsar-bookkeeper-verify-clusterid
  Warning  BackOff    44s (x189 over 40m)  kubelet            Back-off restarting failed container

**Comment by lijunfeng11** [comment]
> you need to figure out why pulsar pods are CrashLoopBackOff, describe the pod or share more info about it
zookeeper log
```shell
[root@master rbd-eventlog]# kubectl logs my-milvus-pulsar-zookeeper-0
exec /usr/bin/sh: exec format error
[root@master rbd-eventlog]# kubectl describe pod my-milvus-pulsar-zookeeper-0
Name:         my-milvus-pulsar-zookeeper-0
Namespace:    default
Priority:     0
Node:         master/192.168.6.242
Start Time:   Thu, 16 May 2024 17:12:57 +0800
Labels:       app=pulsar
              cluster=my-milvus-pulsar
              component=zookeeper
              controller-revision-hash=my-milvus-pulsar-zookeeper-5c6946568d
              release=my-milvus
              statefulset.kubernetes.io/pod-name=my-milvus-pulsar-zookeeper-0
Annotations:  cni.projectcalico.org/containerID: f240c1461b1460008d146f49ca2d751087a7a66795c36516b64b1579fa0b64a2
              cni.projectcalico.org/podIP: 10.244.219.106/32
              cni.projectcalico.org/podIPs: 10.244.219.106/32
              prometheus.io/port: 8000
              prometheus.io/scrape: true
Status:       Running
IP:           10.244.219.106
IPs:
  IP:           10.244.219.106
Controlled By:  StatefulSet/my-milvus-pulsar-zookeeper
Containers:
  my-milvus-pulsar-zookeeper:
    Container ID:  docker://4f6ee2fc2b8668d3aa99c9ee8b2cd24e7aa76987bc1854c0a1958a06d73256ce
    Image:         apachepulsar/pulsar:2.8.2
    Image ID:      docker-pullable://apachepulsar/pulsar@sha256:d538416d5afe03360e10d5beb44bdad33d7303d137fc66c264108426875f61c6
    Ports:         8000/TCP, 2181/TCP, 2888/TCP, 3888/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP
    Command:
      sh
      -c
    Args:
      bin/apply-config-from-env.py conf/zookeeper.conf;
      bin/generate-zookeeper-config.sh conf/zookeeper.conf; OPTS="${OPTS} -Dlog4j2.formatMsgNoLookups=true" exec bin/pulsar zookeeper;
      
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 16 May 2024 18:04:38 +0800
      Finished:     Thu, 16 May 2024 18:04:38 +0800
    Ready:          False
    Restart Count:  15
    Requests:
      cpu:      300m
      memory:   1Gi
    Liveness:   exec [bin/pulsar-zookeeper-ruok.sh] delay=10s timeout=5s period=30s #success=1 #failure=10
    Readiness:  exec [bin/pulsar-zookeeper-ruok.sh] delay=10s timeout=5s period=30s #success=1 #failure=10
    Environment Variables from:
      my-milvus-pulsar-zookeeper  ConfigMap  Optional: false
    Environment:
      ZOOKEEPER_SERVERS:  my-milvus-pulsar-zookeeper-0,my-milvus-pulsar-zookeeper-1,my-milvus-pulsar-zookeeper-2
    Mounts:
      /pulsar/data from my-milvus-pulsar-zookeeper-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-s8tv8 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  my-milvus-pulsar-zookeeper-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  my-milvus-pulsar-zookeeper-data-my-milvus-pulsar-zookeeper-0
    ReadOnly:   false
  kube-api-access-s8tv8:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  54m                    default-scheduler  Successfully assigned default/my-milvus-pulsar-zookeeper-0 to master
  Normal   Started    53m (x4 over 54m)      kubelet            Started container my-milvus-pulsar-zookeeper
  Normal   Pulled     53m (x5 over 54m)      kubelet            Container image "apachepulsar/pulsar:2.8.2" already present on machine
  Normal   Created    53m (x5 over 54m)      kubelet            Created container my-milvus-pulsar-zookeeper
  Warning  BackOff    4m37s (x256 over 54m)  kubelet            Back-off restarting failed container
[root@master rbd-eventlog]# kubectl logs my-milvus-pulsar-zookeeper-0
exec /usr/bin/sh: exec format error
[root@master rbd-eventlog]# kubectl describe pod my-milvus-pulsar-zookeeper-0
Name:         my-milvus-pulsar-zookeeper-0
Namespace:    default
Priority:     0
Node:         master/192.168.6.242
Start Time:   Thu, 16 May 2024 17:12:57 +0800
Labels:       app=pulsar
              cluster=my-milvus-pulsar
              component=zookeeper
              controller-revision-hash=my-milvus-pulsar-zookeeper-5c6946568d
              release=my-milvus
              statefulset.kubernetes.io/pod-name=my-milvus-pulsar-zookeeper-0
Annotations:  cni.projectcalico.org/containerID: f240c1461b1460008d146f49ca2d751087a7a66795c36516b64b1579fa0b64a2
              cni.projectcalico.org/podIP: 10.244.219.106/32
              cni.projectcalico.org/podIPs: 10.244.219.106/32
              prometheus.io/port: 8000
              prometheus.io/scrape: true
Status:       Running
IP:           10.244.219.106
IPs:
  IP:           10.244.219.106
Controlled By:  StatefulSet/my-milvus-pulsar-zookeeper
Containers:
  my-milvus-pulsar-zookeeper:
    Container ID:  docker://2dd275871a968cdb3eb1eee8d69f30f228c5c8502f4fdac9a063304c3960ba1f
    Image:         apachepulsar/pulsar:2.8.2
    Image ID:      docker-pullable://apachepulsar/pulsar@sha256:d538416d5afe03360e10d5beb44bdad33d7303d137fc66c264108426875f61c6
    Ports:         8000/TCP, 2181/TCP, 2888/TCP, 3888/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP
    Command:
      sh
      -c
    Args:
      bin/apply-config-from-env.py conf/zookeeper.conf;
      bin/generate-zookeeper-config.sh conf/zookeeper.conf; OPTS="${OPTS} -Dlog4j2.formatMsgNoLookups=true" exec bin/pulsar zookeeper;
      
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 16 May 2024 18:09:44 +0800
      Finished:     Thu, 16 May 2024 18:09:44 +0800
    Ready:          False
    Restart Count:  16
    Requests:
      cpu:      300m
      memory:   1Gi
    Liveness:   exec [bin/pulsar-zookeeper-ruok.sh] delay=10s timeout=5s period=30s #success=1 #failure=10
    Readiness:  exec [bin/pulsar-zookeeper-ruok.sh] delay=10s timeout=5s period=30s #success=1 #failure=10
    Environment Variables from:
      my-milvus-pulsar-zookeeper  ConfigMap  Optional: false
    Environment:
      ZOOKEEPER_SERVERS:  my-milvus-pulsar-zookeeper-0,my-milvus-pulsar-zookeeper-1,my-milvus-pulsar-zookeeper-2
    Mounts:
      /pulsar/data from my-milvus-pulsar-zookeeper-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-s8tv8 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  my-milvus-pulsar-zookeeper-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  my-milvus-pulsar-zookeeper-data-my-milvus-pulsar-zookeeper-0
    ReadOnly:   false
  kube-api-access-s8tv8:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  58m                    default-scheduler  Successfully assigned default/my-milvus-pulsar-zookeeper-0 to master
  Normal   Started    57m (x4 over 58m)      kubelet            Started container my-milvus-pulsar-zookeeper
  Normal   Pulled     56m (x5 over 58m)      kubelet            Container image "apachepulsar/pulsar:2.8.2" already present on machine
  Normal   Created    56m (x5 over 58m)      kubelet            Created container my-milvus-pulsar-zookeeper
  Warning  BackOff    3m13s (x280 over 58m)  kubelet            Back-off restarting failed container
```

**Comment by yanliang567** [comment]
/assign @LoveEachDay 
please help to take a look

**Comment by lijunfeng11** [comment]
> /assign @LoveEachDay please help to take a look

[root@master k8s-Milvus]# kubectl get pods -n  my-milvus-zookeeper-0
No resources found in my-milvus-zookeeper-0 namespace.
我现在换为kafka进行启动，只有zookeeper和kafka启动不了，如应该如何查看
![dccfa22b07fc43497a391e97f535a3d](https://github.com/milvus-io/milvus/assets/51052480/acac19bd-c494-4650-8686-317c9327e88f)

![87ffdec21f8fb77c7cdf079390aa77c](https://github.com/milvus-io/milvus/assets/51052480/e86fedbc-1549-482e-87bf-64245d55cafe)

**Comment by lijunfeng11** [comment]
现在我尝试直接用外部的kafka进行连接配置文件
`rootCoordinator:
  replicas: 1
  resources: 
    limits:
      cpu: 1
      memory: 2Gi
indexCoordinator:
  replicas: 1
  resources: 
    limits:
      cpu: "0.5"
      memory: 0.5Gi
queryCoordinator:
  replicas: 1
  resources: 
    limits:
      cpu: "0.5"
      memory: 0.5Gi
dataCoordinator:
  replicas: 1
  resources: 
    limits:
      cpu: "0.5"
      memory: 0.5Gi
proxy:
  replicas: 1
  resources: 
    limits:
      cpu: 1
      memory: 4Gi
queryNode:
  replicas: 5
  resources: 
    limits:
      cpu: 4
      memory: 16Gi
dataNode:
  replicas: 1
  resources: 
    limits:
      cpu: 1
      memory: 4Gi
indexNode:
  replicas: 2
  resources: 
    limits:
      cpu: 8
      memory: 16Gi
etcd:
  autoCompactionMode: revision
  autoCompactionRetention: "1000"
  extraEnvVars:
  - name: ETCD_QUOTA_BACKEND_BYTES
    value: "4294967296"
  - name: ETCD_HEARTBEAT_INTERVAL
    value: "500"
  - name: ETCD_ELECTION_TIMEOUT
    value: "25000"
  - name: ETCD_SNAPSHOT_COUNT
    value: "10000"
  - name: ETCD_ENABLE_PPROF
    value: "true"
  persistence:
    accessMode: ReadWriteOnce
    enabled: true
    size: 30Gi  #SSD Required
    storageClass:
  replicaCount: 3
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 2
      memory: 4Gi
pulsar:
  enabled: false
extraConfigFiles:
  user.yaml: |+
    kafka:
      brokerList: 192.168.6.242:9092,192.168.6.243:9092,192.168.6.244:9092
      saslUsername:
      saslPassword:
      saslMechanisms:
      securityProtocol: 
minio:
  resources:
    limits:
      cpu: 2
      memory: 8Gi
  persistence:
    storageClass:
    accessMode: ReadWriteOnce
    size: 120Gi
`
运行之后报错
![image](https://github.com/milvus-io/milvus/assets/51052480/0068d780-ad7b-4daa-bc0d-9fcc499213f6)
配置文件是应该这样配置么？尝试了好多次也没有成功

**Comment by lijunfeng11** [comment]
> /assign @LoveEachDay please help to take a look
您好，现在这个问题有什么进展么？我在单独安装zookeeper的时候也是有这个执行不了的问题，应该这个镜像里面没有arm 的包吧
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
be5cb546c61c6ea6df39c65b1584a89522dcab6c87acb8a12bdedc72c866e5d7

在咨询个问题，用外部的kafka的话是需要安装在dokcer里面的么？因为我这个是没有安装在Docker
里面的一直连接不上外部的kafka其中里面也是没有加认证的
