### ISSUE TITLE
[Bug]: Is it possible to test milvus offline by ann_benchmark on Centos?

### ISSUE THREAD

**Issue by GreateFang** [milvus-io/milvus#33106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.0-beta
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.3
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I could test pgvector and other db successfully, while could never connect to mivus. and I couldn't find the package pyknowhere in anywhere.(only package "knowhere" could be found which not support Centos?) 
Thanks for your help, I was so confuse  TT
![image](https://github.com/milvus-io/milvus/assets/32962590/693c8ab9-aaee-4378-aea6-343aba4b60a6)

![image](https://github.com/milvus-io/milvus/assets/32962590/0632b3fa-4faf-4160-9be7-2923a8fe7009)

**Comment by yanliang567** [comment]
@GreateFang try to find some solutions here: https://github.com/milvus-io/milvus/issues/27417

**Comment by GreateFang** [comment]
> @GreateFang try to find some solutions here: #27417

yes, I have seem this issue before. and I have tried using --algorithm 'Milvus(Knowhere)' instead of --algorithm milvus, still got the same error.  

![image](https://github.com/milvus-io/milvus/assets/32962590/e0474fc6-24b7-4366-a33d-8246f28cb22d)
It may be caused by import error, while I cannot find package pyknowhere anywhere.
<img width="581" alt="image" src="https://github.com/milvus-io/milvus/assets/32962590/5e01bdaa-58c1-4253-a2ba-e54c24305ce3">

I stiill wanna to test milvus by ann_benchmark because we have already test other db with it . could you kindly help?

**Comment by yanliang567** [comment]
@liliu-z do you know what is pyknowhere, and how to get it working?

/assign @liliu-z 
/unassign

**Comment by liliu-z** [comment]
You need to build pyknowhere if you want to use it, since we didn't push it into pypi. check https://github.com/zilliztech/knowhere

**Comment by GreateFang** [comment]
> You need to build pyknowhere if you want to use it, since we didn't push it into pypi. check https://github.com/zilliztech/knowhere

Is it supoort to be built in Centos? I didn't found it in Readme @liliu-z

**Comment by xiaofan-luan** [comment]
> > You need to build pyknowhere if you want to use it, since we didn't push it into pypi. check https://github.com/zilliztech/knowhere
> 
> Is it supoort to be built in Centos? I didn't found it in Readme @liliu-z

Milvus is a system, we would recommend to test performance with vectorDB bench.https://github.com/zilliztech/VectorDBBench
