### ISSUE TITLE
[Bug]: unit test may have mem leak caused by gtest framework

### ISSUE THREAD

**Issue by zhengbuqian** [milvus-io/milvus#33139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
```

### Current Behavior

in master branch, always enable asan by modify

from:
```cmake
    if ( USE_ASAN AND false )
        message( STATUS "Building Milvus using AddressSanitizer")
        add_compile_options(-fno-stack-protector -fno-omit-frame-pointer -fno-var-tracking -fsanitize=address)
        add_link_options(-fno-stack-protector -fno-omit-frame-pointer -fno-var-tracking -fsanitize=address)
    endif()
```
to:
```cmake
#    if ( USE_ASAN AND false )
        message( STATUS "Building Milvus using AddressSanitizer")
        add_compile_options(-fno-stack-protector -fno-omit-frame-pointer -fno-var-tracking -fsanitize=address)
        add_link_options(-fno-stack-protector -fno-omit-frame-pointer -fno-var-tracking -fsanitize=address)
#    endif()
```

then `make test-cpp` to build unit test with asan enabled.

Run `./internal/core/output/unittest/all_tests --gtest_list_tests`. NO test will be ran, but after gtest listed all test cases, asan reported memory leak.
![img_v3_02av_decff388-4dd6-4cf6-ad94-3a3d950d3fcg](https://github.com/milvus-io/milvus/assets/12147173/505c809e-14b2-4356-b71a-bd16d2f790e4)

it seems the mem leak is caused by gtest, not our code?

**Comment by zhengbuqian** [comment]
or could it be a globally allocated memory?

**Comment by PwzXxm** [comment]
Maybe caused by some static test suite initialization
