### ISSUE TITLE
[Bug]: Different collection names returned across V1 and V2 of API

### ISSUE THREAD

**Issue by billreynolds007** [milvus-io/milvus#33148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.x
- Deployment mode: Cloud
- MQ type(rocksmq, pulsar or kafka): NA   
- SDK version: NA, using axios and REST
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Given these seeming same API semantics
  https://${MILVUS_URI}/v1/vector/collections
  http://${MILVUS_URI}/v2/vectordb/collections/list

The results are different
  V1 { code: 200, data: [ 'quick_setup', 'medium_articles' ] }
  V2 { code: 200, data: [ 'test_table_2', 'test_table_4', 'test_table_3' ] }

The cloud console shows the V1 names.

### Expected Behavior

Same names no matter the version of the API

### Steps To Reproduce

```markdown
const axios = require("axios");
const endpoint = axios.create({
  baseURL: "FILL_IN",
  headers: {
    "Content-Type": "application/json",
    "Authorization": `Bearer FILL_IN`,
  },
});

async function listCollectionsV1()
{
 // https://${MILVUS_URI}/v1/vector/collections
 try {
   const reply  = await endpoint.get( "/v1/vector/collections");
   console.log('V1', reply .data);
  }
 catch(ex)
  {
  console.log('V1', ex.message);
  // 404
  }
}

async function listCollectionsV2()
{
 // http://${MILVUS_URI}/v2/vectordb/collections/list
 var payload = { "dbName": "default" };
 const reply  = await endpoint.post( "/v2/vectordb/collections/list", payload);
 console.log('V2', reply .data);
 // { code: 200, data: [ 'test_table_2', 'test_table_4', 'test_table_3' ] }
}

listCollectionsV1();
listCollectionsV2();
```

**Comment by yanliang567** [comment]
@billreynolds007 what is the cloud console you mentioned above? is it Attu? how many collection did you created actually?
/assign @billreynolds007 
/unassign

**Comment by billreynolds007** [comment]
The 'console' is the web browser one found at, https://cloud.zilliz.com/orgs. The medium_articles collection was populated via an option button on a web page and the quick_setup collection via https://docs.zilliz.com/docs/quick-start.

**Comment by yanliang567** [comment]
> The 'console' is the web browser one found at, https://cloud.zilliz.com/orgs. The medium_articles collection was populated via an option button on a web page and the quick_setup collection via https://docs.zilliz.com/docs/quick-start.

as you are running on zilliz cloud, please file a ticket in [support.zilliz.com ](https://support.zilliz.com/hc/en-us)for privacy issue. I'd close this issue for now.
