### ISSUE TITLE
[Enhancement]: missing `make cppcheck` in CI

### ISSUE THREAD

**Issue by jiangyinzuo** [milvus-io/milvus#33144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

I run `make cppcheck` manually under master branch and find some code unformatted.

Maybe we need to add `make cppcheck` to CI to ensure code quality.

**Comment by xiaofan-luan** [comment]
/assign @samhuang-z 
any thoughts on this?
