### ISSUE TITLE
[Bug]: collection can not loaded when restart after server's sudden electricity lost

### ISSUE THREAD

**Issue by James-ge** [milvus-io/milvus#33145]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.1
- Deployment mode(standalone or cluster):standalone 
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 16C/64G
- GPU: RTX3090
- Others:
```

### Current Behavior

1. after restart, server consistently print warn log **'failed to get collection rate limit config'** with the same collectionID=449844857107126063
2. collection can not be load correctly 
[warn_and_error_log.log](https://github.com/milvus-io/milvus/files/15365659/warn_and_error_log.log)

**Comment by xiaofan-luan** [comment]
this seems to be an old bug already fixed, 449844857107126063 has been deleted but there are some meta left.
Try:
1. upgrade to 2.3.15 seem it works?
2. if now, use birdwatcher clean all the meta for 449844857107126063 on etcd. then the cluster should be able to load
