### ISSUE TITLE
Add metadata to vector 

### ISSUE THREAD

**Issue by suvashishtha** [milvus-io/milvus#3315]
Is it possible to add some metadata information along with vector? For instance, storing timestamp

**Comment by shengjun1985** [comment]
If the metadata information is provided by the user, the feature will be supported in 0.11.0.
If you want Millus to automatically add meta information to each vector, this requirement needs to be discussed.

**Comment by scsven** [comment]
Supported in release 0.11.0. You can use INT field to store timestamp.
