### ISSUE TITLE
[Bug]: milvus pulsar error too many requests to the same bookie

### ISSUE THREAD

**Issue by JamesBonddu** [milvus-io/milvus#33171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.1
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.4
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 512/1T
- GPU: 3090 * 8
- Others:
```

### Current Behavior

 milvus plusar error too many requests to the same bookie
plusar 2.8.2

### Milvus Log

[milvus-204-05-20.zip](https://github.com/milvus-io/milvus/files/15373815/milvus-204-05-20.zip)

### Anything else？

maybe we can upgrade pulsar  after 2020-1

https://github.com/apache/pulsar/issues/6163

_No response_

**Comment by yanliang567** [comment]
@JamesBonddu is it the same issue with #32694? if yes, please offer logs and more info in that issue. thanks

/assign @JamesBonddu 
/unassign

**Comment by JamesBonddu** [comment]
> @JamesBonddu is it the same issue with #32694? if yes, please offer logs and more info in that issue. thanks
> 
> /assign @JamesBonddu /unassign

not same question, i also asked in pulsar .
![image](https://github.com/milvus-io/milvus/assets/15228379/c82395d9-5f9a-4c6a-8759-259b10e25bf9)
<img width="1167" alt="image" src="https://github.com/milvus-io/milvus/assets/15228379/1c1553ec-382a-4af9-8cfd-c0be13b2e02d">
![image](https://github.com/milvus-io/milvus/assets/15228379/27bab407-db07-4b95-ab4f-99d9bbcff99b)
![image](https://github.com/milvus-io/milvus/assets/15228379/432e4158-b594-451d-bb5d-d911afaa962b)
