### ISSUE TITLE
[Enhancement]: CompactionExecutor use a pool

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#33182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Currently, the compaction is running wit goroutine with unlimited memory.

// These two func are bounded for waitGroup
func (c *compactionExecutor) executeWithState(task compactor) {
	go c.executeTask(task)
}

Use a pool could save memory and also reduce resource contention.

**Comment by atris** [comment]
Can I please take this issue up?

**Comment by xiaofan-luan** [comment]
/assign @atris 
let me know if you need any help

**Comment by forsaken628** [comment]
Please take a look. @xiaofan-luan
