### ISSUE TITLE
[Bug]: NodeNotFound when trying to load collection after milvus update and bulk insert

### ISSUE THREAD

**Issue by zhengbuqian** [milvus-io/milvus#33200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster): standalone
```

### Current Behavior

`hello_milvus.py` mentioned below does create collection, insert data, create index and load index. It does not drop index or colelction. `bulk pytest` refer to `cd tests/python_client/testcases && pytest test_bulk_insert.py::TestBulkInsert::test_bulk_insert_all_field_with_parquet`.

Before every test, everything in etcd and minio are dropped to ensure fresh start.

Commit order: `5c6de47 (3 days ago) -> c6e2dd05 (19 hours ago) -> a7f6193bfc (10 hours ago) -> now (0520 9 pm)`

Test A:

1. built milvus on commit `5c6de47`, run `hello_milvus.py`
2. run `bulk pytest`. all tests passed

Test B:

1. built milvus on commit `5c6de47`, run `hello_milvus.py`
2. rebuilt milvus on commit `a7f6193bfc`
3. run `bulk pytest`. the test fails with `NodeNotFound` error when trying to load the collection `<MilvusException: (code=65535, message=NodeNotFound)> (api_request.py:46)`

Test C:

1. built milvus on commit `5c6de47`, run `hello_milvus.py`
2. rebuilt milvus on commit `c6e2dd05`
3. run `bulk pytest` all tests passed

Test D:

1. built `a7f6193bfc`, run `hello_milvus.py`
6. run `bulk pytest`. all tests passed

From the above test results, seems commit [`a7f6193bfc`](https://github.com/milvus-io/milvus/pull/33104) has introduced some kind of compatibility issue, causing collections with segments created by bulk insert fail to load.

**Comment by weiliu1031** [comment]
please verify this with latest image
