### ISSUE TITLE
[Bug]: Querynode failed to load index when collection has multi indexes

### ISSUE THREAD

**Issue by xige-16** [milvus-io/milvus#33230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Assume that the collection has two indexes, one is the string index index1 and the other is the vector index index2.

Suppose again that flushed segment A only has the string index index1 during load collection. During the construction process of the vector index, querynode load segment with index1, the vector column loads the original vector data, and then load collection is done.

After the vector index index2 is constructed, querycoord triggers a new loadsegment task, source = index checker, LoadScope == querypb.LoadScope_Index, and the load segment request contains {index1, index2}

querynode load index, it is found that the local segment has been loaded with index1, prints index already loaded, and then returns that the load is successful, but the vector index is not loaded successfully

querycoord pack load req code：
https://github.com/milvus-io/milvus/blob/0ae4c8a11cec30a1675ccd5465122c4d4b1b4c96/internal/querycoordv2/task/executor.go#L200-L225

querynode load index code：
https://github.com/milvus-io/milvus/blob/0ae4c8a11cec30a1675ccd5465122c4d4b1b4c96/internal/querynodev2/segments/segment.go#L878-L884

**Comment by congqixia** [comment]
@xige-16 2.3 does not support multi-vector yet
Is there any problem in 2.4 version?

**Comment by xige-16** [comment]
> @xige-16 2.3 does not support multi-vector yet Is there any problem in 2.4 version? Also multi index on same field is not support yet

@congqixia  not use multi-vector, just string indx and vector index on one collection

**Comment by xige-16** [comment]
Sorry, the duplicate index will not be loaded repeatedly, and it will not cause the updated index to fail to load. I misunderstood.
