### ISSUE TITLE
[Bug]: The search vector being too far away can lead to inaccurate result sets.

### ISSUE THREAD

**Issue by zhoujiaqi1998** [milvus-io/milvus#33269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.4.1
- Deployment mode(standalone or cluster): standalone and cluster
- MQ type(rocksmq, pulsar or kafka): rocksmq and pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): v2.3.4
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The search vector is too far away, and the result set contains [0,0] and [1,0].
Search vector:
[1<<25, 0]
Database vector:
[0, 0]
[1, 0]
Search algorithm:
L2
Data storage type:
FLOAT_VECTOR

Test script:
[test.txt](https://github.com/milvus-io/milvus/files/15399378/test.txt)
[root@master-00926-0 root]# python3 test.txt

=== start connecting to Milvus     ===
=== Create collection `hello_milvus` ===
=== Start inserting entities       ===
Number of entities in Milvus: 3000
=== Start Creating index IVF_FLAT  ===
=== Start loading                  ===
=== Start searching based on vector similarity ===
hit: id: 0, distance: 1125899906842624.0, entity: {'random': 0.456112344881892, 'embeddings': [0.0, 0.0]}
hit: id: 1, distance: 1125899906842624.0, entity: {'random': 0.2938152926171026, 'embeddings': [1.0, 0.0]}
hit: id: 2, distance: 1125899906842624.0, entity: {'random': 0.7528276205814994, 'embeddings': [0.0, 0.0]}
hit: id: 3, distance: 1125899906842624.0, entity: {'random': 0.6917658945233224, 'embeddings': [1.0, 0.0]}

### Expected Behavior

[root@master-00926-0 root]# python3 test.py

=== start connecting to Milvus     ===
=== Create collection `hello_milvus` ===
=== Start inserting entities       ===
Number of entities in Milvus: 3000
=== Start Creating index IVF_FLAT  ===
=== Start loading                  ===
=== Start searching based on vector similarity ===
hit: id: 1, distance: 11258991476736.0, entity: {'random': 0.9407890488813064, 'embeddings': [1.0, 0.0]}
hit: id: 3, distance: 11258991476736.0, entity: {'random': 0.9319260020306628, 'embeddings': [1.0, 0.0]}
hit: id: 5, distance: 11258991476736.0, entity: {'random': 0.9496021275858367, 'embeddings': [1.0, 0.0]}
hit: id: 7, distance: 11258991476736.0, entity: {'random': 0.4254195287876559, 'embeddings': [1.0, 0.0]}

**Comment by xiaofan-luan** [comment]
> test.txt

your test data set doens't make any sense.
the test vector is too far away from all the vectors in the database.

**Comment by xiaofan-luan** [comment]
I don't think this is an issue. you need to find a valid data set and query

**Comment by xiaofan-luan** [comment]
all the distance is same 1125899906842624.0, guess it already overflowed
