### ISSUE TITLE
Is there any instruction about to build milvus from source in RHEL 7 or Oracle Linux 7 environment 

### ISSUE THREAD

**Issue by jack1981** [milvus-io/milvus#3327]
**Please state your issue using the following template and, most importantly, in English.**

**Location of incorrect documentation**
Provide links and line numbers if applicable.

**Describe the problems or issues found in the documentation**
A clear and concise description of what you found to be incorrect.

**Steps taken to verify documentation is incorrect**
List any steps you have taken:

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.

---

## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken:

**Comment by sahuang** [comment]
CentOS is an exact copy of RHEL, so you can essentially follow the documentation on building from source in CentOS 7 environment.

**Comment by sahuang** [comment]
If you have further questions please open a separate issue. Thanks.
