### ISSUE TITLE
[Bug]: wrong operate to drop collection/database etc. with prefix in snapshot

### ISSUE THREAD

**Issue by smellthemoon** [milvus-io/milvus#33288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

<img width="843" alt="image" src="https://github.com/milvus-io/milvus/assets/64083300/d95d50a8-738c-499d-ad65-cad2cca4b772">
<img width="883" alt="image" src="https://github.com/milvus-io/milvus/assets/64083300/5a03c1e1-735d-4ef6-91a4-dd245a44e15f">
DropDatabase has already passed the dbID, remove with prefix in snapshot may remove another db which has the same prefix.
In the case that it is not easy to have the same prefix (such as collectionID), load will also have better performance.

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version:
> - Deployment mode(standalone or cluster):
> - MQ type(rocksmq, pulsar or kafka):    
> - SDK version(e.g. pymilvus v2.0.0rc2):
> - OS(Ubuntu or CentOS): 
> - CPU/Memory: 
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> <img alt="image" width="843" src="https://private-user-images.githubusercontent.com/64083300/332785616-d95d50a8-738c-499d-ad65-cad2cca4b772.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NDM3NDEsIm5iZiI6MTcxNjQ0MzQ0MSwicGF0aCI6Ii82NDA4MzMwMC8zMzI3ODU2MTYtZDk1ZDUwYTgtNzM4Yy00OTlkLWFkNjUtY2FkMmNjYTRiNzcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDA1NTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4MDc2OGE3OGQ1YzQ0YWEwNzNlMDMzODcyYThlODJiMjhlYmFkM2E5YjEyODA3OGRmYzQ3ZjQ2YjMwMWZlMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QUDnsO9awq-REDf1sbRTIjgUcNjaCiNUvKfQAxbWgw4"> <img alt="image" width="883" src="https://private-user-images.githubusercontent.com/64083300/332785819-5a03c1e1-735d-4ef6-91a4-dd245a44e15f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NDM3NDEsIm5iZiI6MTcxNjQ0MzQ0MSwicGF0aCI6Ii82NDA4MzMwMC8zMzI3ODU4MTktNWEwM2MxZTEtNzM1ZC00ZWY2LTkxYTQtZGQyNDVhNDRlMTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDA1NTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4Y2VhYmVkZTFhNjVlYmMzYjAzZjA5MDUwYTZkMGQ0ODQwZDdkNTUyM2EwOTQwYTU3Y2JmZTY1OGY5ZTA2MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8SK666vOtkWlMra45XLcpZMtRU-64dZHb2S1R0fs2wo"> DropDatabase has already passed the dbID, remove with prefix in snapshot may remove another db which has the same prefix. In the case that it is not easy to have the same prefix (such as collectionID), load will also have better performance.
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

is there a spliter for the key?
for example, we can remove db/ instead db. 
if we concat the key with some delimiter, this is the fast way to fix

**Comment by smellthemoon** [comment]
> > ### Is there an existing issue for this?
> > 
> > * [x]   I have searched the existing issues
> > 
> > ### Environment
> > ```
> > - Milvus version:
> > - Deployment mode(standalone or cluster):
> > - MQ type(rocksmq, pulsar or kafka):    
> > - SDK version(e.g. pymilvus v2.0.0rc2):
> > - OS(Ubuntu or CentOS): 
> > - CPU/Memory: 
> > - GPU: 
> > - Others:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Current Behavior
> > <img alt="image" width="843" src="https://private-user-images.githubusercontent.com/64083300/332785616-d95d50a8-738c-499d-ad65-cad2cca4b772.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NDM3NDEsIm5iZiI6MTcxNjQ0MzQ0MSwicGF0aCI6Ii82NDA4MzMwMC8zMzI3ODU2MTYtZDk1ZDUwYTgtNzM4Yy00OTlkLWFkNjUtY2FkMmNjYTRiNzcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDA1NTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4MDc2OGE3OGQ1YzQ0YWEwNzNlMDMzODcyYThlODJiMjhlYmFkM2E5YjEyODA3OGRmYzQ3ZjQ2YjMwMWZlMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QUDnsO9awq-REDf1sbRTIjgUcNjaCiNUvKfQAxbWgw4"> <img alt="image" width="883" src="https://private-user-images.githubusercontent.com/64083300/332785819-5a03c1e1-735d-4ef6-91a4-dd245a44e15f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NDM3NDEsIm5iZiI6MTcxNjQ0MzQ0MSwicGF0aCI6Ii82NDA4MzMwMC8zMzI3ODU4MTktNWEwM2MxZTEtNzM1ZC00ZWY2LTkxYTQtZGQyNDVhNDRlMTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDA1NTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4Y2VhYmVkZTFhNjVlYmMzYjAzZjA5MDUwYTZkMGQ0ODQwZDdkNTUyM2EwOTQwYTU3Y2JmZTY1OGY5ZTA2MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8SK666vOtkWlMra45XLcpZMtRU-64dZHb2S1R0fs2wo"> DropDatabase has already passed the dbID, remove with prefix in snapshot may remove another db which has the same prefix. In the case that it is not easy to have the same prefix (such as collectionID), load will also have better performance.
> > ### Expected Behavior
> > _No response_
> > ### Steps To Reproduce
> > _No response_
> > ### Milvus Log
> > _No response_
> > ### Anything else?
> > _No response_
> 
> is there a spliter for the key? for example, we can remove db/ instead db. if we concat the key with some delimiter, this is the fast way to fix

But in fact, the key removed here is the key itself, not the prefix of the key. For example, when creating database, the key  **root-coord/database/db-info/dbid** will be saved. When dropping database, pass in  **root-coord/database/db-info/dbid** as the prefix. If has the same prefixes, will cause other db to be removed too.
multiSaveAndRmove seems more appropriate.

**Comment by xiaofan-luan** [comment]
can you give an example?

**Comment by xiaofan-luan** [comment]
don't quite understand about this part

**Comment by smellthemoon** [comment]
> don't quite understand about this part

For example, you create 11 databases. The id of databases is 0-10. RootCoord will save the key "root-coord/database/db-info/dbID" in snapshot. 
if you want to drop database(id =1),  RootCoord will remove it by writing tombstone. the prefix here is "root-coord/database/db-info/1". snapshot will list all the keys with the prefix, and then save it. So in this case, dbID 10 will be listed for having the same prefix and will be written tombstone.

**Comment by xiaofan-luan** [comment]
the easiest fix is to always drop root-coord/database/db-info/1/ ?

**Comment by smellthemoon** [comment]
> the easiest fix is to always drop root-coord/database/db-info/1/ ?

The keys now do not contain delimiters at the end, may bring some compatibility issues.

**Comment by xiaofan-luan** [comment]
so we just want to delete 1 key?

**Comment by smellthemoon** [comment]
> so we just want to delete 1 key?

yes, from the code, it actually just want to delete 1 key, I have added the **MultiSaveAndRemove** in the snapshot interface.
