### ISSUE TITLE
[Bug]: milvus querynode memory crash, how to locate the cause

### ISSUE THREAD

**Issue by TonyAnn** [milvus-io/milvus#33287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.14
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

During the stress test, 86 querynodes (88 in total) suddenly restarted in the production environment.

During the operation: the memory usage of k8s node was 70%, and the memory usage of pod was about 80%. At the time of the crash, querycoord had an error of insufficient memory for growing index. 

After reloading the data for a while, the following error was reported:
[WARN] [task/scheduler.go:741] ["task scheduler recordSegmentTaskError"] [taskID=911977] [taskStatus=4] [segmentID=449408709593696911] [error="InsufficientMemoryToLoad, err:insufficient memory when shard cluster load segments, err:InsufficientMemoryToLoad, reason:InsufficientMemoryToLoad, load segment failed, OOM if load, collectionID = 449408709592904117, MaxSegmentMemUsage = 6296 MB, concurrency = 1, usedMemAfterLoad = 60735 MB, currentAvailableMemCount = 15091 MB, currentTotalMem = 73728 MB, thresholdFactor = 0.900000"]
[2024/05/22 10:11:16.753 +00:00] [WARN] [meta/failed_load_cache.go:101] ["FailedLoadCache put failed record"] [collectionID=449408709592904117] [errCode=InsufficientMemoryToLoad] [error="InsufficientMemoryToLoad, err:insufficient memory when shard cluster load segments, err:InsufficientMemoryToLoad, reason:InsufficientMemoryToLoad, load segment failed, OOM if load, collectionID = 449408709592904117, MaxSegmentMemUsage = 6296 MB, concurrency = 1, usedMemAfterLoad = 60735 MB, currentAvailableMemCount = 15091 MB, currentTotalMem = 73728 MB, thresholdFactor = 0.900000"]

The detailed time point was around 10:26 pm on the 21st. The log and monitoring chart are as follows:
[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/15402818/milvus-log.tar.gz)

**Comment by yanliang567** [comment]
do you have any insert/upsert/delete operations to the cluster during the test?  I did not find any logs around 10:26pm, but it seems that there are too many growing segments(or something else) and causes milvus to reject loading for protect the system. @TonyAnn 

/assign @TonyAnn

**Comment by TonyAnn** [comment]
In addition, after querynode crashes and restarts, querycoord has the following warning information
[森华 milvus querynode 崩溃 会议纪要.docx](https://github.com/milvus-io/milvus/files/15410590/milvus.querynode.docx)

**Comment by TonyAnn** [comment]
> do you have any insert/upsert/delete operations to the cluster during the test? I did not find any logs around 10:26pm, but it seems that there are too many growing segments(or something else) and causes milvus to reject loading for protect the system. @TonyAnn
> 
> /assign @TonyAnn

hi @yanliang567 
At the time of the failure, the cluster had no insert/upsert/delete operations, only search operations

However, about 10 hours before the failure, a batch of 40 million data was written by bulk insert

**Comment by TonyAnn** [comment]
> do you have any insert/upsert/delete operations to the cluster during the test? I did not find any logs around 10:26pm, but it seems that there are too many growing segments(or something else) and causes milvus to reject loading for protect the system. @TonyAnn
> 
> /assign @TonyAnn

@yanliang567 In addition, after querynode crashes, the warning information seen in querycoord is shown in the screenshot
![崩溃恢复后，querycoord 的日志](https://github.com/milvus-io/milvus/assets/22573548/149dfaed-b0d5-4261-be60-ee1bd3f7307a)

**Comment by yanliang567** [comment]
@TonyAnn 
1. have you calculate the memory size is enough after 40 million data bulk inserted?
2. Could you please attach the etcd backup for investigation？ Check this: https://github.com/milvus-io/birdwatcher for details about how to backup etcd with birdwatcher

**Comment by xiaofan-luan** [comment]
I think you might set segment size to too large. 

If your querynode is 72GB, segment size is recommened to be set at 4GB.
How balance is your current cluster?

**Comment by TonyAnn** [comment]
> I think you might set segment size to too large.
> 
> If your querynode is 72GB, segment size is recommened to be set at 4GB. How balance is your current cluster?

The current segment is set to 2gb. In order to avoid wasting memory, I did not dare to allocate 4gb.
      segment:
        maxSize: 2048
        sealProportion: 0.5
        assignmentExpiration: 5000

**Comment by xiaofan-luan** [comment]
![image](https://github.com/milvus-io/milvus/assets/83447078/c63daeb2-0f1d-4bba-bd0d-d15d96e55a85)

from the log, max segment memory is usage is very large. did you have large scalar field?

**Comment by xiaofan-luan** [comment]
one suggestion is to mmap field to local disk

**Comment by TonyAnn** [comment]
> @TonyAnn
> 
> 1. have you calculate the memory size is enough after 40 million data bulk inserted?
> 2. Could you please attach the etcd backup for investigation？ Check this: https://github.com/milvus-io/birdwatcher for details about how to backup etcd with birdwatcher

@yanliang567 @xiaofan-luan Exported birdwatcher log, please refer to the attachment 
[bw_etcd_ALL.240523-205809.bak.gz](https://github.com/milvus-io/milvus/files/15417164/bw_etcd_ALL.240523-205809.bak.gz)
