### ISSUE TITLE
[BUG] Improve search performance of high-dimension dataset 

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#333]
**Describe the bug**
Here is the search performance of random_1m_4096d_ip dataset performance result:
index_type: IVF_SQ8H
```
│  Nq/Top-k   │      1      │      4      │     16      │     64      │     128     │     256     │     512     │    1000     │
├─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┤
│           1 │        0.79 │        0.69 │        0.69 │        0.58 │        0.54 │        0.57 │        0.56 │        0.57 │
│          10 │        1.12 │        1.26 │        1.14 │        1.04 │        1.07 │        1.18 │        1.11 │        1.16 │
│         100 │         4.7 │         4.8 │        4.63 │        4.87 │        4.76 │        4.84 │        4.81 │        4.68 │
│         500 │       20.66 │       20.61 │       20.81 │       20.06 │        20.3 │       20.56 │        20.8 │       20.62 │
│         800 │       30.78 │       31.83 │       31.54 │       31.07 │          31 │       31.11 │       31.12 │       31.63 │
│        1000 │       37.83 │       37.68 │       37.42 │       38.35 │       37.73 │       37.85 │       38.17 │        38.4 │
```

**Steps/Code to reproduce behavior**
dataset length: 1m
index_file_size: 1024
nprobe: 32
Search params:
```
{'run_count': 1, 'params': [{'dataset': 'random_1m_1024_4096_ip', 'index.index_types': ['ivf_sq8h'], 'index.nlists': [16384], 'nprobes': [32],  'server.use_blas_threshold': 1100, 'server.use_gpu_threshold': 1100, 'server.cpu_cache_capacity': 50, 'server.resources': ['cpu', 'gpu0', 'gpu1'], 'db_path_prefix': '/test/milvus/db_data/random_1m_1024_4096_ip_sq8h'}]}
```

**Expected behavior**
Performance improvement

**Environment details**
server_version: 0.5.3
nvidia-1080*2

**Screenshots**
null

**Additional context**
null

**Comment by del-zhenwu** [comment]
Thu Nov 14 19:36:04 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.34       Driver Version: 430.34       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:02:00.0 Off |                  N/A |
| 38%   62C    P2   114W / 180W |   1063MiB /  8119MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1080    Off  | 00000000:83:00.0 Off |                  N/A |
| 41%   63C    P2    52W / 180W |   1381MiB /  8119MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     47102      C   ../bin/milvus_server                        1043MiB |
|    1     47102      C   ../bin/milvus_server                        1361MiB |

**Comment by fishpenguin** [comment]
CPU search high dimension vectors performance is badly in raw faiss. I propose a issue in faiss. waiting for them to solve.
