### ISSUE TITLE
build index for incremental data

### ISSUE THREAD

**Issue by suvashishtha** [milvus-io/milvus#3331]
How does milvus decide whether to actually trigger index building when index is built on incremental data. 

- Added initial 500K records and built index on them. Result: Success. Index was created(checked metadata entries)
- Added 1K records and called create index. Result: Success. Index file was still flat. (tried this couple of times)
- Added 5K records and called create index. Result: Success. Index file was created for all the records.

Is it based on some percentage? Is it configurable somehow?

**Comment by shengjun1985** [comment]
The following page can answer your questions.
https://www.milvus.io/docs/v0.10.2/index.md
"When the inserted data segment is less than 4096 rows, Milvus does not index it. "

**Comment by shengjun1985** [comment]
If you have more questions, please continue to contact our community.
