### ISSUE TITLE
[Bug]: fail to drop an index if there are multpile indexes of multiple vector fields

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#33327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.4.2
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):     
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus   2.4.3
```

### Current Behavior

1. fail to drop an index if there are multiple indexes
![image](https://github.com/milvus-io/milvus/assets/82361606/7ee87356-9102-4d13-9b3d-352b6372ffa2)

### Expected Behavior

1. drop successfully

### Steps To Reproduce

```markdown
1. create a collection with 3 vector fields
2. build index for the 3 vector fields
3. try to drop one of the vector indexes
```

**Comment by XuanYang-cn** [comment]
should be fixed, please help verify
/assign @yanliang567 
/unassign

**Comment by yanliang567** [comment]
verified on pymilvus 2.4.4rc8  and milvus 2.4-20240614-5fc1370f-amd64
