### ISSUE TITLE
Grafana dashboard for number of records

### ISSUE THREAD

**Issue by suvashishtha** [milvus-io/milvus#3335]
grafana dashboard for data size is based on total number of vector add requests(prometheus metric: add_vectors_request_total)

This is not 100% accurate since it resets to 0 once milvus is restarted.

Is there any other metric which can be used for no. of records?

**Comment by fishpenguin** [comment]
This has already been fixed in master branch, and grafana dashboard for data size becomes the volumn of all entities.
