### ISSUE TITLE
Create collection with 3 fields but get 4 fields in CollectionMapping

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#3336]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

1. The fields when create collection is:
```
   intFields.put("field","int64");
   intFields.put("type",DataType.INT64);
   floatField.put("field","float");
   floatField.put("type",DataType.FLOAT);
   vectorField.put("field","float_vector");
   vectorField.put("type",DataType.VECTOR_FLOAT);
```
2. The fields when get is:
```
GetCollectionInfoResponse res = client.getCollectionInfo(collectionName);
        assert(res.getResponse().ok());
        CollectionMapping tableSchema = res.getCollectionMapping().get();
        List<Map<String,Object>> fields = (List<Map<String, Object>>) tableSchema.getFields();
```
The debug output is:
```
CollectionMapping = {collectionName = collection_eyyMhfnxuZ, fields = [{indexParams=[], field=int64, type=INT64, params=[key: "params"
value: "null"
]}, {indexParams=[], field=float, type=FLOAT, params=[key: "params"
value: "null"
]}, {indexParams=[], field=_id, type=INT64, params=[key: "params"
value: "null"
]}, {indexParams=[], field=float_vector, type=VECTOR_FLOAT, params=[key: "params"
value: "{\"dim\":128}"
]}], params = {"auto_id":true,"segment_row_count":50}}
```
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by sahuang** [comment]
`GrpcRequestHandler::DescribeCollection` has not filtered "_id" yet. Will be fixed later.
