### ISSUE TITLE
[Bug]: [CI] Test case test_compact_during_insert failed frequently for lacking search results

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#33374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 9e8d288
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Test case test_compact_during_insert failed frequently for lacking search results.

There are about 6000 entities in the collection. 
search with topk=10, expect 10 results, but only 9 results were returned

### Expected Behavior

pass

### Steps To Reproduce

```markdown
1. create a collection a collection
2. compact during insert
3. waiting for new segment index and compact
4. compact new segment
5. waiting for new segment index and compact
6. search -> ❌ (expect 10 results, but only 9 results were returned)
```

### Milvus Log

link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-33257/4/pipeline/253

**Comment by yanliang567** [comment]
could be fixed by https://github.com/milvus-io/milvus/pull/33360
@NicoYuan1986 please help to verify as it merged
/assign @NicoYuan1986 
/unassign

**Comment by NicoYuan1986** [comment]
fixed.

**Comment by NicoYuan1986** [comment]
reproduce: 
1. link: https://qa-jenkins.milvus.io/blue/organizations/jenkins/E2E%20Test/detail/E2E%20Test/644/pipeline/
2. log: [artifacts-e2e-test-644-server-logs.tar.gz](https://qa-jenkins.milvus.io/job/E2E%20Test/644/artifact/artifacts-e2e-test-644-server-logs.tar.gz)
3. collection name: compact_R41fDW5X

**Comment by NicoYuan1986** [comment]
reproduce:

1. link: https://qa-jenkins.milvus.io/blue/organizations/jenkins/E2E%20Test/detail/E2E%20Test/668/pipeline
2. log: [artifacts-e2e-test-668-server-logs.tar.gz](https://qa-jenkins.milvus.io/job/E2E%20Test/668/artifact/artifacts-e2e-test-668-server-logs.tar.gz)
3. collection name: compact_hl5H6lYK

**Comment by sunby** [comment]
> reproduce:
> 
> 1. link: https://qa-jenkins.milvus.io/blue/organizations/jenkins/E2E%20Test/detail/E2E%20Test/668/pipeline
> 2. log: [artifacts-e2e-test-668-server-logs.tar.gz](https://qa-jenkins.milvus.io/job/E2E%20Test/668/artifact/artifacts-e2e-test-668-server-logs.tar.gz)
> 3. collection name: compact_hl5H6lYK

I am working on it. Please help run this ut for v2.4.x.
