### ISSUE TITLE
[Bug]: Unsupported type when using sparse vector

### ISSUE THREAD

**Issue by misi0202** [milvus-io/milvus#33384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:milvus 2.4.x
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.4.3
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I use Zilliz for my vectorstore that I tried the sparse vector, but failed.I noticed this type is supported as a demo function in milvus 2.4.x, so I confirmed milvus version is 2.4 x. But still failed, I am confused.
`fields = [
    # Use auto generated id as primary key
    FieldSchema(name="pk", dtype=DataType.VARCHAR,
                is_primary=True, auto_id=True, max_length=100),
    # Store the original text to retrieve based on semantically distance
    FieldSchema(name="text", dtype=DataType.VARCHAR, max_length=512),
    # Milvus now supports both sparse and dense vectors, we can store each in
    # a separate field to conduct hybrid search on both vectors.
    FieldSchema(name="sparse_vector", dtype=DataType.SPARSE_FLOAT_VECTOR),
    FieldSchema(name="dense_vector", dtype=DataType.FLOAT_VECTOR,
                dim=dense_dim),
]`
Error Like that:
`
MilvusException: <MilvusException: (code=<bound method _MultiThreadedRendezvous.code of <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "unsupported data type when creating collection, data type: SparseFloatVector, filed name: sparse_vector"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"unsupported data type when creating collection, data type: SparseFloatVector, filed name: sparse_vector", grpc_status:2, created_time:"2024-05-25T18:57:44.225217268+08:00"}"
>>, message=Retry run out of 75 retry times, message=unsupported data type when creating collection, data type: SparseFloatVector, filed name: sparse_vector)>
`

**Comment by fsj621** [comment]
请问这个问题解决了吗，我也遇到了

**Comment by yanliang567** [comment]
if you are using zilliz cloud, sparse vector is not yet supported; also please file a support ticket if any issues in zilliz cloud for your privacy issues.  @misi0202 @fsj621 
BTW, if you are using community version, sparse vector is beta in milvus 2.4.4

/assign @misi0202
