### ISSUE TITLE
[Bug]: Range Filter Bug

### ISSUE THREAD

**Issue by JackTan25** [milvus-io/milvus#33383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.3
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Get wrong result for range query.

### Expected Behavior

Get null result.

### Steps To Reproduce

```markdown
use my script
```

**Comment by JackTan25** [comment]
[small_data-2.zip](https://github.com/milvus-io/milvus/files/15442435/small_data-2.zip)
cc @czs007 The range search get wrong result.
```shell
$ cd small_data
$ python3.11 ground_truth.py ## we can get all data distances to the query point
$ python3.11 milvus_small_multi_vector.py ## the radius is 100, should get non result, but get took results.
```

**Comment by chasingegg** [comment]
This is not a bug, should be a mis-use of pymilvus api, @JackTan25 help check this.

**Comment by yanliang567** [comment]
> This is not a bug, should be a mis-use of pymilvus api, @JackTan25 help check this.

@chasingegg could you please clarify which part is mis-used, and how to correct it>
/assign @chasingegg 
/unassign

**Comment by JackTan25** [comment]
I find out the api error in my usage. Let's close this one.
