### ISSUE TITLE
[Bug]: Unsupported type when using sparse vector

### ISSUE THREAD

**Issue by misi0202** [milvus-io/milvus#33385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:milvus 2.4.x
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.4.3
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I use Zilliz for my vectorstore that I tried the sparse vector, but failed.I noticed this type is supported as a demo function in milvus 2.4.x, so I confirmed milvus version is 2.4 x. But still failed, I am confused.
`fields = [
    # Use auto generated id as primary key
    FieldSchema(name="pk", dtype=DataType.VARCHAR,
                is_primary=True, auto_id=True, max_length=100),
    # Store the original text to retrieve based on semantically distance
    FieldSchema(name="text", dtype=DataType.VARCHAR, max_length=512),
    # Milvus now supports both sparse and dense vectors, we can store each in
    # a separate field to conduct hybrid search on both vectors.
    FieldSchema(name="sparse_vector", dtype=DataType.SPARSE_FLOAT_VECTOR),
    FieldSchema(name="dense_vector", dtype=DataType.FLOAT_VECTOR,
                dim=dense_dim),
]`

### Milvus Log

MilvusException: <MilvusException: (code=<bound method _MultiThreadedRendezvous.code of <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "unsupported data type when creating collection, data type: SparseFloatVector, filed name: sparse_vector"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"unsupported data type when creating collection, data type: SparseFloatVector, filed name: sparse_vector", grpc_status:2, created_time:"2024-05-25T18:57:44.225217268+08:00"}"
>>, message=Retry run out of 75 retry times, message=unsupported data type when creating collection, data type: SparseFloatVector, filed name: sparse_vector)>

**Comment by xiaofan-luan** [comment]
please share you code, there might be something wrong

also check https://milvus.io/docs/sparse_vector.md#Sparse-Vector

**Comment by SimFG** [comment]
@xiaofan-luan it's a deny data type in the zilliz cloud. and this restriction will be lifted in the near future.

**Comment by xiaofan-luan** [comment]
oh, gotch. Zilliz cloud is still compatible only to milvus 2.3. and Milvus 2.4 related feature will be Beta since end of June

**Comment by yanliang567** [comment]
/assign @misi0202 
please retry as beta available on zilliz cloud. I'd close this issue for now

**Comment by Nik-su** [comment]
I am getting the same error for sparse vectors. Client is not able to define the schema for it as below despite using the version pymilvus==2.4.1:
DEBUG:pymilvus.milvus_client.milvus_client:Created new connection using: ae315cf6a32347198cb1f4bb683dc46c
WARNING:pymilvus.decorators:[create_collection] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNKNOWN, unsupported data type when creating collection, data type: SparseFloatVector, filed name: sparse_vector>


There can be two ways in which thus can be handles 
1. Either change the sparse embedding to dense embeddings and insert in dense embeddings which in my understanding will not be able to get the accurate  results for the milvus search.
2. Second could be the milvus version that need to be taken care of .
Please reply for the debugging

**Comment by yanliang567** [comment]
@Nik-su please try to file a new issue in github is you are running with Milvus community release. Also please share more info about the milvus version and logs for investigations

**Comment by xiaofan-luan** [comment]
> I am getting the same error for sparse vectors. Client is not able to define the schema for it as below despite using the version pymilvus==2.4.1: DEBUG:pymilvus.milvus_client.milvus_client:Created new connection using: ae315cf6a32347198cb1f4bb683dc46c WARNING:pymilvus.decorators:[create_collection] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNKNOWN, unsupported data type when creating collection, data type: SparseFloatVector, filed name: sparse_vector>
> 
> There can be two ways in which thus can be handles
> 
> 1. Either change the sparse embedding to dense embeddings and insert in dense embeddings which in my understanding will not be able to get the accurate  results for the milvus search.
> 2. Second could be the milvus version that need to be taken care of .
>    Please reply for the debugging

if you are open source user, please make sure you are using milvus version with 2.4 or above.(Better to be latest 2.4.4)
