### ISSUE TITLE
[Bug]: milvus exited with code 139 when i insert data

### ISSUE THREAD

**Issue by yuan8180** [milvus-io/milvus#33404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.1
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): milvus-go-sdk 2.3.1
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 48 / 251G
- GPU: 无
- Others:
```

### Current Behavior

使用下面standalone_embed.sh.txt脚本创建单体版milvus
[standalone_embed.sh.txt](https://github.com/milvus-io/milvus/files/15452373/standalone_embed.sh.txt)
插入数据到94万左右后，milvus容器状态变为exited(139），日志内容如下
[milvus-part.log.txt](https://github.com/milvus-io/milvus/files/15453478/milvus-part.log.txt)
在milvus容器挂掉同时，插入数据的golang服务容器也挂了exited(134），且没有报错日志，最后日志卡在数据入库阶段
在挂掉前内存占用快满了（是否是单体版本设置容量有限？）
在微信群咨询过怀疑是etcd消费太慢。说与右侧issue类似https://github.com/milvus-io/milvus/issues/17557
但是上面issue建议升级到2.1.0以上，而目前此issue中出问题的版本是2.3.1，还是有问题。

### Expected Behavior

插入数据正常

### Milvus Log

[milvus-part.log.txt](https://github.com/milvus-io/milvus/files/15453478/milvus-part.log.txt)

### Anything else?

无

**Comment by yanliang567** [comment]
@yuan8180 it seems that both mq and etcd are slow in response, please make sure that you are running the milvus standalone pod against SSD volumes
```
[2024/05/27 05:12:23.263 +00:00] [WARN] [etcd/etcd_kv.go:647] ["Slow etcd operation load with prefix"] ["time spent"=3.095342327s] [keys="[]"]
[2024/05/27 05:12:23.095 +00:00] [INFO] [observers/target_observer.go:276] ["observer trigger update current target"] [collectionID=449731413768668096]
[2024/05/27 05:12:23.286 +00:00] [WARN] [server/rocksmq_impl.go:873] ["rocksmq consume too slowly"] [topic=by-dev-rootcoord-dml_2] ["get lock elapse"=104] ["iterator elapse"=123] ["moveConsumePosTime elapse"=0] ["total consume elapse"=228]
```

**Comment by yuan8180** [comment]
怎么验证running the milvus standalone pod against SSD volumes

**Comment by yuan8180** [comment]
etcd端口可以在脚本里更改吗？因为在同一个服务器上还有用docker-compose启动的tidb数据库，里面有占用2379端口会影响吗？
![image](https://github.com/milvus-io/milvus/assets/140597641/fabc75b4-5559-40b9-ba7b-dace0d5e9a87)
