### ISSUE TITLE
[Bug]: milvus A single querynode memory surge caused the instance to crash

### ISSUE THREAD

**Issue by TonyAnn** [milvus-io/milvus#33409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.14
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

From the monitoring, we can see that the memory usage of a single querynode pod surges, causing the pod to crash, which in turn causes other pods to fail.

The first abnormal pod log：
[ceee627c8c13b4eabedf3347ebb78a9f81ce01427ed865dd439090643029a9b2-json.log](https://github.com/milvus-io/milvus/files/15454398/ceee627c8c13b4eabedf3347ebb78a9f81ce01427ed865dd439090643029a9b2-json.log)

**Comment by xiaofan-luan** [comment]
There didn't seem to be any useful inforation in the log. 
The only observation is there are many deletes. 
You can try:
1. using pprof to get some analysis about where the memory spent.(Maybe the memory is consumed in cpp), then you don't have any way to see it.
2. use birdwatcher to check segment states, see if there are many segments with no index built on it. this could cause memory can not be balanced in older milvus version
3. upgrade to milvus 2.3.16

**Comment by yanliang567** [comment]
/assign @TonyAnn 
please try as suggestions above

/unassign

**Comment by TonyAnn** [comment]
[bw_etcd_ALL.240527-202545.bak.gz](https://github.com/milvus-io/milvus/files/15455836/bw_etcd_ALL.240527-202545.bak.gz)
[bw_pprof_goroutine.240527-202319.tar.gz](https://github.com/milvus-io/milvus/files/15455838/bw_pprof_goroutine.240527-202319.tar.gz)

**Comment by TonyAnn** [comment]
> There didn't seem to be any useful inforation in the log. The only observation is there are many deletes. You can try:
> 
> 1. using pprof to get some analysis about where the memory spent.(Maybe the memory is consumed in cpp), then you don't have any way to see it.
> 2. use birdwatcher to check segment states, see if there are many segments with no index built on it. this could cause memory can not be balanced in older milvus version
> 3. upgrade to milvus 2.3.16

@xiaofan-luan @yanliang567 Uploaded metadata related information, please help analyze it

**Comment by TonyAnn** [comment]
[57da75b36995cc35ad3aefdc0b2fcedf6d7db0902c3f7f3c27d107aa4f3b6b0a-json.log](https://github.com/milvus-io/milvus/files/15456259/57da75b36995cc35ad3aefdc0b2fcedf6d7db0902c3f7f3c27d107aa4f3b6b0a-json.log)

Update, crash logs of other nodes @xiaofan-luan @TonyAnn
