### ISSUE TITLE
[Bug]: When I started the Milvus standalone version, the program crashed, 134

### ISSUE THREAD

**Issue by hotwinters** [milvus-io/milvus#33416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:最新
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 4核/8G
- GPU: 
- Others:
```

### Current Behavior

At first, my go service was running, but I found an rpc error inside, so I restarted milvus and found that the restart failed. The container displayed 134

### Milvus Log

[Uploading log.txt…]()

**Comment by hotwinters** [comment]
[log.txt](https://github.com/milvus-io/milvus/files/15462683/log.txt)

**Comment by hotwinters** [comment]
[2024/05/28 01:19:49.129 +00:00] [FATAL] [msgstream/mq_factory.go:16] ["fail to init rocksmq"] [error="IO error: While lock file: /var/lib/milvus/rdb_data_meta_kv/LOCK: Resource temporarily unavailable"] [stack="github.com/milvus-io/milvus/internal/mq/msgstream.NewRocksmqFactory\n\t/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_factory.go:16\ngithub.com/milvus-io/milvus/internal/util/dependency.(*DefaultFactory).initMQ\n\t/go/src/github.com/milvus-io/milvus/internal/util/dependency/factory.go:92\ngithub.com/milvus-io/milvus/internal/util/dependency.(*DefaultFactory).Init\n\t/go/src/github.com/milvus-io/milvus/internal/util/dependency/factory.go:78\ngithub.com/milvus-io/milvus/internal/datacoord.(*Server).Init\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:306\ngithub.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:126\ngithub.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:253\ngithub.com/milvus-io/milvus/cmd/components.(*DataCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/data_coord.go:52\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:115"]
panic: fail to init rocksmq

**Comment by hotwinters** [comment]
![image](https://github.com/milvus-io/milvus/assets/34262412/68ffa6fa-7ee1-48e6-b18a-66c32048f3a9)
Am I running out of memory？

**Comment by SimFG** [comment]
@hotwinters Do you need to retain the milvus data now? If not, you can directly clean up all the temporary files in milvus, like `rm -rf /var/lib/milvus`

**Comment by hotwinters** [comment]
@SimFG i need my milvus data

**Comment by SimFG** [comment]
ok, you can confirm whether`/var/lib/milvus/rdb_data_meta_kv/LOCK` file exists. If it exists, you can try to put it in another temporary directory, and then try to see if it can be started.

**Comment by xiaofan-luan** [comment]
> [2024/05/28 01:19:49.129 +00:00] [FATAL] [msgstream/mq_factory.go:16] ["fail to init rocksmq"] [error="IO error: While lock file: /var/lib/milvus/rdb_data_meta_kv/LOCK: Resource temporarily unavailable"] [stack="github.com/milvus-io/milvus/internal/mq/msgstream.NewRocksmqFactory\n\t/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_factory.go:16\ngithub.com/milvus-io/milvus/internal/util/dependency.(*DefaultFactory).initMQ\n\t/go/src/github.com/milvus-io/milvus/internal/util/dependency/factory.go:92\ngithub.com/milvus-io/milvus/internal/util/dependency.(*DefaultFactory).Init\n\t/go/src/github.com/milvus-io/milvus/internal/util/dependency/factory.go:78\ngithub.com/milvus-io/milvus/internal/datacoord.(*Server).Init\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:306\ngithub.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:126\ngithub.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:253\ngithub.com/milvus-io/milvus/cmd/components.(*DataCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/data_coord.go:52\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:115"] panic: fail to init rocksmq

you can remove /var/lib/milvus/rdb_data_meta_kv/LOCK manually and then milvus can recovered.
This usually means milvus crashed

**Comment by hotwinters** [comment]
@xiaofan-luan Yes, I started successfully, but I didn't see what my previous data was about, and I didn't see any error type logs in the logs either

**Comment by SimFG** [comment]
@hotwinters How did you view the data?

**Comment by hotwinters** [comment]
@SimFG Through the query interface I wrote 
![image](https://github.com/milvus-io/milvus/assets/34262412/025d0866-f95f-4025-85e4-3df95c1e0b9e)

**Comment by SimFG** [comment]
@hotwinters From the code in the picture, it should only show collections. Now collections can no longer be seen?

**Comment by hotwinters** [comment]
@SimFG Yes, I can't find my previous collection on listcol right now

**Comment by SimFG** [comment]
@hotwinters you can try to our other tools to check the data, link: https://github.com/milvus-io/birdwatcher/releases/tag/v1.0.4
download it and then use it
```
birdwatcher

connect --etcd localhost:2379 --rootPath by-dev

show collection
```
You need to change the etcd address and rootPath according to your own milvus service configuration. These two values ​​​​can be found in the `milvus.yaml` file.

**Comment by hotwinters** [comment]
@SimFG I still need your help. I am using the default ETCD configuration and milvus.yaml, but I was unable to connect to ETCDOffline > connect --etcd 127.0.0.1:2379 --rootPath by-dev
failed to connect to etcd: context deadline exceeded

**Comment by SimFG** [comment]
@hotwinters you need to check the etcd server state, and make sure it's ok. In addition, you can try to see if there are some warn or error logs in the milvus log.

**Comment by hotwinters** [comment]
@SimFG Hello, I connected to etcd and used show collection, but I couldn't detect the original library. Then I suddenly realized that when I couldn't start Docker, I deleted the "volumes/etcd" directory, but kept the "milvus, mini" directory. Is this the reason why I couldn't query the previous database? Is there any way I can recover the data

**Comment by SimFG** [comment]
@hotwinters This is very bad news, because the directory you deleted stores the metadata of milvus. Naturally, milvus cannot read all the system related information now. And this is also irreversible.

**Comment by hotwinters** [comment]
@SimFG Okay, thank you for your help
