### ISSUE TITLE
[Bug]: Generate proto failed with  protoc-gen-go: plugins are not supported

### ISSUE THREAD

**Issue by liorf95** [milvus-io/milvus#33414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: latest
- Deployment mode(standalone or cluster):standalone from source code
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu 
- CPU/Memory: 
- GPU: 
- Others: 
go version go1.21.1 linux/amd64
cmake version 3.28.1
```

### Current Behavior

While doing make the Generate proto failed:

Generate proto ...
~/work/milvus/internal/proto ~/work/milvus
--go_out: protoc-gen-go: plugins are not supported; use 'protoc --go-grpc_out=...' to generate gRPC

See https://grpc.io/docs/languages/go/quickstart/#regenerate-grpc-code for more information.
generate etcd_meta.proto failed
make: *** [Makefile:230: generated-proto] Error 1

### Steps To Reproduce

```markdown
1) ./scripts/install_deps.sh
2) make
```

**Comment by SimFG** [comment]
Have you installed protoc-gen-go before making milvus? If so, you can try to uninstall it and then make. I guess it may be because the protoc-gen-go version does not match. If protoc-gen-go is not found internally, milvus will automatically download version 1.3.2.

**Comment by liorf95** [comment]
That was the problem indeed.
Thanks a lot for your help and quick reply!!
