### ISSUE TITLE
[Bug]: The sample code for integrating langchain in the 2.4.x Docs has the problem of referencing the wrong package.

### ISSUE THREAD

**Issue by xxh18819431660** [milvus-io/milvus#33455]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.x
- Deployment mode(standalone or cluster): standalone 
- MQ type(rocksmq, pulsar or kafka): None   
- SDK version(e.g. pymilvus v2.0.0rc2): None
- OS(Ubuntu or CentOS): None
- CPU/Memory: None
- GPU: None
- Others: None
```

### Current Behavior

When I refer to the docs of version **2.4.x** and run the sample code of **Question Answering over Documents with Milvus and LangChain**, I find that **the code runs with this error**:
`NameError: name 'PromptTemplate' is not defined`
The specific error location is in run of the **Ask your question** code. The specific code is`rag_prompt = PromptTemplate.from_template(template)`.
[https://milvus.io/docs/integrate_with_langchain.md#Ask-your-question](url)

### Expected Behavior

I sincerely hope that the committers can change this code in [https://milvus.io/docs/integrate_with_langchain.md#Prepare-data](url): 
`from langchain_core.prompts import ChatPromptTemplate`
to
`from langchain_core.prompts import PromptTemplate`
In this way, no error will be reported when the package method is called later.

**Comment by xxh18819431660** [comment]
Modified the issue description to locate the problem and the code that needs to be modified more quickly.

**Comment by jaelgu** [comment]
@xxh18819431660 The tutorial has been updated recently. Please check again: https://milvus.io/docs/integrate_with_langchain.md
