### ISSUE TITLE
[Bug]: When using cosine similarity, a situation occurred where the value was greater than 1. 

### ISSUE THREAD

**Issue by happylql** [milvus-io/milvus#33480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.15
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

<img width="480" alt="2a4d2e6b59939241f81cb881a3201c7" src="https://github.com/milvus-io/milvus/assets/45619002/2a6ba2ab-e07d-46ea-bdd3-f79419b17c43">

**Comment by xiaofan-luan** [comment]
this is just a display issue.
I guess this means value is 1.0

**Comment by yanliang567** [comment]
/assign @shanghaikid 
please help to confirm 
/unassign

**Comment by happylql** [comment]
![微信图片_20240531092240](https://github.com/milvus-io/milvus/assets/45619002/79975ce2-4882-419a-8c06-d8e9b4009247)
再次查询时，的确显示为1了。但是此前，使用范围查询时，[0.6,1]并不能搜到此条数据。
