### ISSUE TITLE
[Bug]: Changing password does nothing

### ISSUE THREAD

**Issue by ckrapu-nv** [milvus-io/milvus#33495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.3 
- Deployment mode(standalone or cluster):Standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.3 
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 8/16
- GPU: None
- Others:
```

### Current Behavior

This script should change the password:
```
import os
import pymilvus
from pymilvus import MilvusClient


print(f"PyMilvus version: {pymilvus.__version__}")

# Initial client connection with default password
client = MilvusClient(
    uri='http://localhost:19530', 
    token="root:Milvus"  # Default password
) 

users = client.list_users()
print(f"Milvus users: {users}; deleting all non-root users.")

for user in users:
    if user != 'root':
        client.drop_user(user_name=user)
        
# Update password for root user
client.update_password(
    user_name="root",
    old_password="Milvus",
    new_password="my_new_password"
)
client.close()


```

However, when I run the following, I am able to log into the root user with the old password `Milvus` and it appears the password wasn't changed at all.
```
from pymilvus import MilvusClient

# Initial client connection with default password
client = MilvusClient(
    uri='http://localhost:19530', 
    token="root:Milvus"  # Default password
) 
users = client.list_users()
print(f"Milvus users: {users}; deleting all non-root users.")
```

### Expected Behavior

I shouldn't be able to login with the default login root:Milvus

### Steps To Reproduce

```markdown
Get the docker compose file for 2.4.3.

`pip install pymilvus==2.4.3`

Run the above python script
```

**Comment by SimFG** [comment]
@ckrapu-nv let me check it

**Comment by yanliang567** [comment]
When I run the script above for the 2nd time, I got the error as expected:
"auth check failure, please check username and password are correct",
As authorization is not enabled by default,  you should change the config as the instructions here: https://milvus.io/docs/authenticate.md#Authenticate-User-Access
/assign @ckrapu-nv 
/unassign

**Comment by ckrapu-nv** [comment]
No, I didn't. I wasn't sure how it was supposed to be used with the `docker-compose-yml`

From [here](https://milvus.io/docs/configure-docker.md), it looks like the full configuration is:
- download milvus.yml
- edit security settings
- specify path to milvus.yml in `docker-compose.yml`

Is that right?

**Comment by SimFG** [comment]
@ckrapu-nv You can try to enter the milvus pod and check the `configs/milvus.yaml` file to confirm the configuration value of `authorizationEnabled`. If it is turned on, it should be true. If it is false, you need to carefully check whether there is an error in the docker mount path.

**Comment by ckrapu-nv** [comment]
Editing the `milvus.yaml` fixed it. Now the login with the wrong password is getting rejected properly.
