### ISSUE TITLE
[Feature]: When importing binlog, ensure that the restored entities' TS order is consistent with the previous TS order.

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#33517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

see: https://github.com/milvus-io/milvus/issues/33350#issuecomment-2141590176

**Comment by bigsheeper** [comment]
/assign @zhuwenxing 
/unassign
please help to verify
