### ISSUE TITLE
[Bug]: [configuration] cannot change the localStorage path if milvus is deployed by helm

### ISSUE THREAD

**Issue by tianshihan818** [milvus-io/milvus#33524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.4.1
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I deployed my milvus cluster by helm on k8s, the version is v2.4.1.

I just knew the [chunk cache mechanism](https://milvus.io/docs/chunk_cache.md#Configure-Chunk-Cache) of milvus, and wonder how to customize the local storage path in milvus.
 

> By the way, I think one thing might be corrected here: https://milvus.io/docs/chunk_cache.md#:~:text=off,the%20memory%20cache.
> ![image](https://github.com/milvus-io/milvus/assets/154961771/5634a5ba-009f-479d-b274-7f30d3c80e68)
> Seems that the `off` options of `queryNode.cache.warmup` has been changed to `disable` a few days ago. Ref issue: [enhance: Replace 'off' with 'disable' (https://github.com/milvus-io/milvus/pull/33433)](https://github.com/milvus-io/milvus/commit/bbb69980acd41ef153c5f7cbf5e8fb0d972dbf52)
> https://github.com/milvus-io/milvus/blob/322a4c5b8cbdd0d34fae005c0410556b2e10dca1/configs/milvus.yaml#L338

According to the above docs, Milvus pre-load the data into local storage cache if warmup enabled. And I find the default path is `/var/lib/milvus/data` from here: https://milvus.io/docs/configure_localstorage.md#localStoragepath
 
If I want to customize this path, as the doc shows, I need to set the `localStorage` like this:
```yaml
localStorage:
  enabled: true
  path: /other_dir/milvus/data/
```

I tried but failed, the path is still directed to `/var/lib/milvus/data`. So I checked the helm chart templates, mainly [milvus-helm/charts/milvus/templates/querynode-deployment.yaml](https://github.com/zilliztech/milvus-helm/blob/master/charts/milvus/templates/querynode-deployment.yaml)
The local storage path is hard-coded as `/var/lib/milvus/data` and mounted on a volume named `disk`. [source code](https://github.com/zilliztech/milvus-helm/blob/5b39d7948b4b575da72f2a39494de7fa4f5b3ae4/charts/milvus/templates/querynode-deployment.yaml#L141C1-L144C19)
And this `disk` volume is defined as emptydir. [source code](https://github.com/zilliztech/milvus-helm/blob/5b39d7948b4b575da72f2a39494de7fa4f5b3ae4/charts/milvus/templates/querynode-deployment.yaml#L182C1-L185C17)
So actually it finally directs to the path like `/var/lib/kubelet/pods/{pod_id}/volumes/kubernetes.io~empty-dir/...`.

With these above configurations, when the milvus loads raw vector data into the chuck cache during search or query, the disk usage of `/var` will increase a lot. There is a risk that if the `/var` usage on the nodes is up to 85%, k8s will evict the pods on these nodes, and for etcd with pvc on the specific nodes, it cannot be re-scheduled and recovered, finally leading to milvus crash.

Although there is one solution to allocate more disk space to `/var`, but for people like me without the privilege, it is more reasonable to customize the local-storage path directly.

**Comment by yanliang567** [comment]
/assign @LoveEachDay 
please help to take a look

/unassign

**Comment by tianshihan818** [comment]
@LoveEachDay Hello! Could you help to look?

**Comment by xiaofan-luan** [comment]
we should fix that on next version of helm chart.

@zwd1208  and should ensure there is no more hard coded configs

**Comment by LoveEachDay** [comment]
@tianshihan818 
The root cause of the issue is the use of the emptyDir volume type here, which uses the kubelet working directory as storage. For chunk cache, we recommend using local NVMe disks to achieve better performance. Therefore, the usual approach we suggest is: 1) Schedule the querynode to a worker node with local NVMe disks. 2) Modify the working directory  of kubelet in the worker node with local NVMe disks to point to the NVMe disk's directory.

**Comment by xiaofan-luan** [comment]
> @tianshihan818 The root cause of the issue is the use of the emptyDir volume type here, which uses the kubelet working directory as storage. For chunk cache, we recommend using local NVMe disks to achieve better performance. Therefore, the usual approach we suggest is: 1) Schedule the querynode to a worker node with local NVMe disks. 2) Modify the working directory of kubelet in the worker node with local NVMe disks to point to the NVMe disk's directory.

why can not user specify the disk they want to use?
The problem is helm chard hard coded /var/lib

**Comment by zwd1208** [comment]
@xiaofan-luan ok, we will support all storage path related configuration in the next version of helm chart and operator.

**Comment by LoveEachDay** [comment]
We'll add a extra `hostPath` volume type which allow user to specify extra disk path to store disk index data and chunk cache, other than default `/var/lib/kubelet`.

**Comment by tianshihan818** [comment]
Thanks all! This will be much helpful!

**Comment by tianshihan818** [comment]
@LoveEachDay  Hello! It passed 3 weeks. I checked the latest version update info of milvus-helm, nothing changed about this issue. Would you support the custom path recently?

**Comment by xiaofan-luan** [comment]
after offline discussion, there is actaully much we need to do on hostPath, reason is:
1. when multiple pod load on one physical node, we need to seperate the path for each querynode.
2. when pod is reconciled, the path need to be cleaned.

@LoveEachDay is still working on it.
