### ISSUE TITLE
[Enhancement]: Milvus String Scalar filter is very slow

### ISSUE THREAD

**Issue by JackTan25** [milvus-io/milvus#33538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

I need to know where the scalar string filter code is.

### Why is this needed?

Performance improvement

**Comment by xiaofan-luan** [comment]
milvus string is highly optimized with simd and usually much faster than any other vector DB on the planet.

If you can give more information that would help on the investigation(If you can give advice on how to optimize it that would be even better)

1. what is the expression? what is the varchar avg size
2. what is the current data size and what is the expected latency/qps
3. waht is the estimated cardinality of your data?

**Comment by JackTan25** [comment]
well, can you give the code link of string filter? I hope I can check the core. cc @xiaofan-luan

**Comment by JackTan25** [comment]
The data size is 330922 rows. And I use multi vector search with string filter (0.9 selectivity), but get slow performance. It costs me 3.23s, and the pure multi vector search (without filter) will cost 2.484s. Wait me to upload the script.(btw, the avg string size is 254 of data size),and I use string filter as `not like '%xxxxx%'` the avg of string size is 15.

**Comment by JackTan25** [comment]
@xiaofan-luan Hi, Can you tell me the core code of string fiter in Milvus Project? I would like to study it and try optimize it.

**Comment by xiaofan-luan** [comment]
> The data size is 330922 rows. And I use multi vector search with string filter (0.9 selectivity), but get slow performance. It costs me 3.23s, and the pure multi vector search (without filter) will cost 2.484s

Pure multi vector search (without filter) will cost 2.484s this doesn't seem to make any sense.  If you create the right index, milvus usually takes 10ms in memory or 50 ms with disk.

My suggestion is to not start from code, but from  profiling, see what part takes most of your cpu.

And may I know what cpu you are running on? intel or arm? how many cores? what index did you use?

**Comment by xiaofan-luan** [comment]
what is the milvus version? Honestly speaking I don't expect anyone with knowhere can optimize milvus in 1 months.
All the filtering code is under internal/core/src in case you are interested.

**Comment by xiaofan-luan** [comment]
you can try to create an tantivy index, which may help to improve the like expression.
Like is a regular expression processing so it is slow anyway. Use exact match could be much faster

**Comment by JackTan25** [comment]
well, I use not like '%xxxxxx%', and I can't find the api to create tantivy index in milvus doc. Does milvus generate bitmap to do filter search?? cc @xiaofan-luan

**Comment by xiaofan-luan** [comment]
1. what is the expression you are using?
2. https://milvus.io/docs/index-scalar-fields.md#Custom-indexing inverted index and here is the example https://github.com/milvus-io/pymilvus/blob/2.4/examples/inverted_index_example.py

like is always slow, no matter what database you are using, espeicially when you don't specify prefix
