### ISSUE TITLE
[Bug]: Milvus panic when the disk has no free space 

### ISSUE THREAD

**Issue by iFurySt** [milvus-io/milvus#33545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.3.15
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): milvus-sdk-go/v2 v2.4.0
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 2c4g
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/16201837/1b27932a-1d58-4ba1-a308-37b6c03b3938)

Milvus will panic when the disk has no free space. Is it a reasonable or expected behavior?

### Expected Behavior

 IMHO, I think the service can't panic~ It needs to transmit the error to the upper application(the caller).

**Comment by xiaofan-luan** [comment]
this is as expected. 
you will need to increase disk size and restart milvus. 
if disk is full and milvus do not panic, then data will lose

**Comment by iFurySt** [comment]
okay, it's fine if it's the expected behavior.
