### ISSUE TITLE
[Bug]:  L0 compaction not control parallel count causing DN OOM

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#33547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/51370125/815d3442-ff67-4a30-a3f2-c2b51e435519)

**Comment by ThreadDao** [comment]
@XuanYang-cn 
- image: master-20240531-2c7bb0b8-amd64
Increased dataNode memory limit to 63Gi and also OOM
![image](https://github.com/milvus-io/milvus/assets/27288593/21c6989c-ee35-41ab-b501-4e789632e22c)

- grafana: [metrics of compact-opt-master-op-43-5911](https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=P1809F7CD0C75ACF3&var-cluster=&var-namespace=qa-milvus&var-instance=compact-opt-master-op-43-5911&var-collection=All&var-app_name=milvus&from=1717378622530&to=1717398088485)
- pods:
```
compact-opt-master-op-43-5911-milvus-datanode-5d6654857-kj8rc     1/1     Running            4 (57m ago)        3h56m   10.104.13.37    4am-node16   <none>           <none>
```
- argo: https://argo-workflows.zilliz.cc/archived-workflows/qa/2e2b9cdd-db7d-43e5-bab4-9a35061e1092?nodeId=compact-opt-no-flush-2

**Comment by XuanYang-cn** [comment]
should be fixed, althouth DN are still OOM, not caused by L0 compaction
see #33676
