### ISSUE TITLE
[Enhancement]: consider using `std::vector<>.shrink_to_fit()` to reduce the memory overhead

### ISSUE THREAD

**Issue by alexanderguzhva** [milvus-io/milvus#33572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

`std::vector<>.shrink_to_fit()` to be used together with `std::vector<>.clear()`, if needed

 

### Why is this needed?

`std::vector<>.clear()` does not release the allocated memory. One needs to use `.shrink_to_fit()` to do so:
```
std::vector<int> foo;
...
// the next line does not change vector's capacity
foo.clear();
// the memory is properly released
foo.shrink_to_fit();
```

**Comment by xiaofan-luan** [comment]
this could be helpful @zhagnlu
