### ISSUE TITLE
support HA

### ISSUE THREAD

**Issue by kakasu** [milvus-io/milvus#3358]
Now i can start another milvus write node when the current write node crash base keepalived, like https://blog.csdn.net/ukakasu/article/details/107936799
but, there has some problems like the brain split.
so can support the double write nodes running in the same time , with one active and one standby, like hbase master or hdfs namenode.
Thanks

**Comment by XuPeng-SH** [comment]
Hi @kakasu,
We're investigating some possible solutions for HA now. There are 2 directions. 
1. Master/Backup solution base on log replication
2. Multiple write and read nodes based on shared storage

Please stay tuned.

**Comment by scsven** [comment]
Will be supported in v2.0.

**Comment by M-A-N-I-S-H-K** [comment]
any update on this @scsven  @XuPeng-SH

**Comment by xiaofan-luan** [comment]
> any update on this @scsven @XuPeng-SH

We are moving to v2.0, and HA is automatically supported thanks to K8s

**Comment by M-A-N-I-S-H-K** [comment]
does that mean multiple write nodes can be created? @xiaofan-luan

**Comment by xiaofan-luan** [comment]
> does that mean multiple write nodes can be created? @xiaofan-luan

In 2.0 there is no more concepts like read or write. However we do separate.query node, data node and log storage can be scaled separately and cover failure coverage independently
