### ISSUE TITLE
[Bug]: filter indexed segments failed

### ISSUE THREAD

**Issue by TonyAnn** [milvus-io/milvus#33589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.14
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

milvus is stuck when building an index, 

indexcoord throws [WARN] [indexcoord/node_manager.go:144] ["get IndexNode slots failed"] [nodeID=223] [error="context canceled"]

datacoord throws failed to get index of collection, ["filter indexed segments failed"] [error="context deadline exceeded"

### Milvus Log

[bw_etcd_ALL.240604-133724.bak.gz](https://github.com/user-attachments/files/15543103/bw_etcd_ALL.240604-133724.bak.gz)
[milvus-log.tar.gz](https://github.com/user-attachments/files/15543104/milvus-log.tar.gz)

**Comment by SimFG** [comment]
@TonyAnn How did you deploy milvus? According to the log of index node, it seems that some permissions are missing.
![image](https://github.com/milvus-io/milvus/assets/21985684/83ac4e70-a981-45d2-8330-1a13a72eca57)

**Comment by TonyAnn** [comment]
@SimFG hi sim, milvus cluster deployed via helm in kubernetes

**Comment by SimFG** [comment]
You also need to confirm whether the etcd service is normal, because etcd also has failed operations during the indexnode startup process.
![image](https://github.com/milvus-io/milvus/assets/21985684/35c3333e-4a36-4288-8ff1-22f8ddc088a8)

**Comment by TonyAnn** [comment]
@SimFG By checking the log and command line, etcd is fine.
etcdctl --endpoints=http://10.96.1.142:2379 endpoint  health
http://10.96.1.142:2379 is healthy: successfully committed proposal: took = 2.873091ms

**Comment by SimFG** [comment]
@TonyAnn You can try to redeploy milvus. According to the log, there should be a problem with the index node startup that caused the entire milvus to fail to start.

**Comment by SimFG** [comment]
@TonyAnn What version of milvus did you use?

**Comment by TonyAnn** [comment]
> @TonyAnn What version of milvus did you use?

@SimFG version is 2.2.14

**Comment by SimFG** [comment]
You can try the latest milvus version. I checked the logs and the core reason is not because of permissions. If you want to solve the permission warn, you can try to add the following configuration in the deployment:
```
 securityContext:
   capabilities:
     add: ["SYS_NICE"]
```
It seems to be mainly abnormal in connecting to etcd. I recommend trying the latest version, because we rarely maintain 2.2.x now. The latest version of milvus is 2.4.3

**Comment by yanliang567** [comment]
please use v2.4.4 
/assign @TonyAnn
