### ISSUE TITLE
[Bug]: Import segemnt with row 0 and can never be cleaned

### ISSUE THREAD

**Issue by bigsheeper** [milvus-io/milvus#33604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master & 2.4
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![img_v3_02bh_60d9a23d-c354-4c13-8cf1-af136a8a160g](https://github.com/milvus-io/milvus/assets/42060877/937ab712-6c2a-4c13-92c7-1093b3303a25)

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version: master & 2.4
> - Deployment mode(standalone or cluster):
> - MQ type(rocksmq, pulsar or kafka):    
> - SDK version(e.g. pymilvus v2.0.0rc2):
> - OS(Ubuntu or CentOS): 
> - CPU/Memory: 
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> ![img_v3_02bh_60d9a23d-c354-4c13-8cf1-af136a8a160g](https://private-user-images.githubusercontent.com/42060877/336399870-937ab712-6c2a-4c13-92c7-1093b3303a25.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NDk1MzUsIm5iZiI6MTcxNzk0OTIzNSwicGF0aCI6Ii80MjA2MDg3Ny8zMzYzOTk4NzAtOTM3YWI3MTItNmMyYS00YzEzLTkyYzctMTA5M2IzMzAzYTI1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDE2MDcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxODBjZTM2Y2Y3NzIyYmFmODFiMDBmOWJkYzBkMjVhYjgxN2YwNDk0YzJjMDhjZjNhY2FjMzMwM2NlMGE1M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5iIoMTT9-CTtMyFLwMc5rnhu7Vejq-1Zelh-dTFL1x8)
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

I think this pr's name and description need to be improved.  The generated segemnt with row 0 can never be cleaned and this is a critical bug
