### ISSUE TITLE
[Bug]: System continues to create empty segments after upgrade to 2.4

### ISSUE THREAD

**Issue by Archalbc** [milvus-io/milvus#33646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: from 2.3.12 to 2.4.4
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): kafka
- SDK version(e.g. pymilvus v2.0.0rc2): Go SDK 2.3.2

- MaxSegmentSize: 2048
```

### Current Behavior

After upgrading our Milvus cluster from 2.3.12 to 2.4.4, the system started to continuously create empty segment in all my collections.
![image](https://github.com/milvus-io/milvus/assets/144429952/6893d361-3dd0-4cee-8481-44b6fe3dc7ba)
![image](https://github.com/milvus-io/milvus/assets/144429952/dc1f77c4-5737-4b00-b6a9-4aed62efa5e2)
![image](https://github.com/milvus-io/milvus/assets/144429952/fba74e11-bdbe-4028-ba30-315626b44d40)

This bug should be fixed since 2.3.15 in: https://github.com/milvus-io/milvus/issues/32553.

We decided to downgrade to 2.3.17 and unfortunately we also encountered an issue as our indexes version were upgraded to "4", Querynode in 2.3.17 were not able to load that. 
Sound related to: https://github.com/milvus-io/milvus/issues/33242

Timeline:
* ~11:40 deploy the upgrade from 2.3.12 to 2.4.4
* ~15:15 downgrade to 2.3.17 but figured out the downgrade issue
* ~16:00 stop traffic and restore all collections using milvus-backup, now it's OK.

Client is using Go SDK 2.3.2, we don't think it's an issue (?).

Schema:
![image](https://github.com/milvus-io/milvus/assets/144429952/b08c8790-08cb-4abe-8816-b54f17a8a509)

### Expected Behavior

* No empty segments created
* Being able to rollback to 2.3.

### Steps To Reproduce

```markdown
1. Setup a Milvus cluster in 2.3.12
2. Add collections and start indexing
3. Upgrade to 2.4.4
```

### Milvus Log

Sorry, I don't have logs anymore since we downgraded everything.

**Comment by yanliang567** [comment]
I guess the empty segments actually are not "empty", they are compacted segments and pending for indexing. In Milvus 2.3.12, the default maxSize of a segment is 512MB, while in Milvus 2.4.4 it changed to 1GB, so after upgraded, Milvus is trying to compact the segments to a the new maxSize. If you checking the compaction tasks or indexing tasks, I believe you can see the new tasks.
BTW, a bigger segment size leads to a better search performance in general. But it is not the bigger the better, because a bigger segment also means lower efficiency usage in memory. 

/assign @Archalbc 
/unassign

**Comment by Archalbc** [comment]
> I guess the empty segments actually are not "empty", they are compacted segments and pending for indexing. In Milvus 2.3.12, the default maxSize of a segment is 512MB, while in Milvus 2.4.4 it changed to 1GB, so after upgraded, Milvus is trying to compact the segments to a the new maxSize. If you checking the compaction tasks or indexing tasks, I believe you can see the new tasks. BTW, a bigger segment size leads to a better search performance in general. But it is not the bigger the better, because a bigger segment also means lower efficiency usage in memory.
> 
> /assign @Archalbc /unassign

Hey sorry I completely forget to say that we are already a 2GB for the maxSegmentSize since 2.3.12 as our querynodes are 32GB. (I'm updating the initial post)

**Comment by yanliang567** [comment]
trying to reproduce the issue in house.... @Archalbc any configs else did you change for milvus cluster
/assign @Archalbc

**Comment by Archalbc** [comment]
> trying to reproduce the issue in house.... @Archalbc any configs else did you change for milvus cluster /assign @Archalbc

Hello, here is my  values.yaml for the milvus configuration:
```
extraConfigFiles:
  user.yaml: |+
    queryNode:
      scheduler:
        maxReadConcurrentRatio: 2
    dataCoord:
      segment:
        maxSize: 2048
    queryCoord:
      overloadedMemoryThresholdPercentage: 80

```

**Comment by xiaofan-luan** [comment]
@Archalbc 
are you using bulkinsertion?
https://github.com/milvus-io/milvus/issues/33604 this might be the issue related.
We will fix this soon

**Comment by Archalbc** [comment]
> @Archalbc are you using bulkinsertion? #33604 this might be the issue related. We will fix this soon

My workmate will anwser to you soon.

**Comment by Archalbc** [comment]
New event, after the downgrade to 2.3.17 (so finally I upgraded from 2.3.12 to 2.3.17). Everything was normal until last friday around 1h AM, we encountered again a huge quantities of segments created. But this time, I can't see those segments on ATTU or birdwatcher :o, they are telling me I should have around 100 sealed segments, but this is clearly not the case.
In 2.4.4 I was able to see those empty segments on ATTU.

![image](https://github.com/milvus-io/milvus/assets/144429952/902b78f5-7c80-48b6-96df-55d6723b0103)
![image](https://github.com/milvus-io/milvus/assets/144429952/0379b7e1-033c-4ef8-b098-faa602d54313)

Birdwatcher, right now is saying;
```
--- Growing: 32, Sealed: 0, Flushed: 68, Dropped: 19                                                                                                                                                               
--- Total Segments: 100, row count: 65129835                    
```

and ATTU for the collection ID 450234905777292996:
![image](https://github.com/milvus-io/milvus/assets/144429952/f1d2cc51-5f18-4ec8-94c6-30f022b56a9d)

while the Sealed segment vizualization is saying more than 70 segments.

**Comment by xiaofan-luan** [comment]
> New event, after the downgrade to 2.3.17 (so finally I upgraded from 2.3.12 to 2.3.17). Everything was normal until last friday around 1h AM, we encountered again a huge quantities of segments created. But this time, I can't see those segments on ATTU or birdwatcher :o, they are telling me I should have around 100 sealed segments, but this is clearly not the case. In 2.4.4 I was able to see those empty segments on ATTU.
> 
> ![image](https://private-user-images.githubusercontent.com/144429952/338122678-902b78f5-7c80-48b6-96df-55d6723b0103.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMTczNzcsIm5iZiI6MTcxODAxNzA3NywicGF0aCI6Ii8xNDQ0Mjk5NTIvMzM4MTIyNjc4LTkwMmI3OGY1LTdjODAtNDhiNi05NmRmLTU1ZDY3MjNiMDEwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQxMDU3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjI1OTcwYTVhMGQwMDcwMDgxOTA0ODc5MzBlMzg4ZjBhYjZmODhhMmQ0Y2QwZWNhMTU4OTY3MTUyMjM0NDNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xyjwdhP0z7_q26yWLkbZVTCerUOzYEIru4MJoEr79LE) ![image](https://private-user-images.githubusercontent.com/144429952/338122945-0379b7e1-033c-4ef8-b098-faa602d54313.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMTczNzcsIm5iZiI6MTcxODAxNzA3NywicGF0aCI6Ii8xNDQ0Mjk5NTIvMzM4MTIyOTQ1LTAzNzliN2UxLTAzM2MtNGVmOC1iMDk4LWZhYTYwMmQ1NDMxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQxMDU3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmQxYTI3MDk1NjZkNjg5M2QxMWJmOTdlYTI3NGUzYTdhMzYxZDdhYjg2YjUxOGY2Njg3OWVmNTIyNTNlOGY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0QCi56L7mqLH6VjwgyHUrgdfB7iRLLj1YhZiGv4-0D0)
> 
> Birdwatcher, right now is saying;
> 
> ```
> --- Growing: 32, Sealed: 0, Flushed: 68, Dropped: 19                                                                                                                                                               
> --- Total Segments: 100, row count: 65129835                    
> ```
> 
> and ATTU for the collection ID 450234905777292996: ![image](https://private-user-images.githubusercontent.com/144429952/338123672-f1d2cc51-5f18-4ec8-94c6-30f022b56a9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMTczNzcsIm5iZiI6MTcxODAxNzA3NywicGF0aCI6Ii8xNDQ0Mjk5NTIvMzM4MTIzNjcyLWYxZDJjYzUxLTVmMTgtNGVjOC05NGM2LTMwZjAyMmI1NmE5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQxMDU3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNGZmZmE5MDI4YjdmNmRmZGJhZjViYjJmMzBhYTM0OGE4NzI5YjllYmY3N2VjNTRjMDgxMzMwZTcxMDk1YjhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zMzxbeUymZb1Fae-d0SE1VxPVv8xVq8FqLVsrI5zyis)
> 
> while the Sealed segment vizualization is saying more than 70 segments. As you can see, before the sudden increase of sealed segments, I should have 40 segments for this collection, which is normal because we have 2 replicas.
> 
> I rollback again to 2.3.12, And I got my 40 sealed segments again... ![image](https://private-user-images.githubusercontent.com/144429952/338126944-f5986118-d8c2-4488-a138-7f1bf779f849.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMTczNzcsIm5iZiI6MTcxODAxNzA3NywicGF0aCI6Ii8xNDQ0Mjk5NTIvMzM4MTI2OTQ0LWY1OTg2MTE4LWQ4YzItNDQ4OC1hMTM4LTdmMWJmNzc5Zjg0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQxMDU3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMGQzODU5OWY5MmYyNmQxMGZkYjY5ZWVmZGM2YzI0M2VjZDhmNDFmNWM5YTY3MDg2M2NmNWVkMDk5YWVkMThiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pdQynJAthmiARTC-3rf9b7xXaG6Q5DxPGQIQwo6UsRo)

1. did you have any import and delete at that time? 
2. you have 32 growing segments, which means you might have 32 partitions or enabled partitionkey features. If you have many partitions, has hundred segments might not be a big thing?

**Comment by xiaofan-luan** [comment]
because each time you flush(or auto flush), your segment number will grow by 32. and after compaction the number will decrease

**Comment by Archalbc** [comment]
1. We did nothing special during the night, just usual operations.
2. We always have only one partition per collection.

We don't call flush in the code, we let the system auto-flush.
There is definitively something strange because reverting back to 2.3.12, odd segments disappear and we are back to the normal number of segments. 
We can clearly see that those strange segments are never flushed or compacted, they stay here forever...

**Comment by xiaofan-luan** [comment]
> 1. We did nothing special during the night, just usual operations.
> 2. We always have only one partition per collection.
> 
> We don't call flush in the code, we let the system auto-flush. There is definitively something strange because reverting back to 2.3.12, odd segments disappear and we are back to the normal number of segments. We can clearly see that those strange segments are never flushed or compacted, they stay here forever...

If you only have one collection and one partition, there seems to be no reason you will see 32 growing segments.

did you do import or insert? can you offer full logs for debug?

**Comment by xiaofan-luan** [comment]
I think we need logs and also information about "what operation did you do and see a segemnt with 0 entities"

**Comment by Archalbc** [comment]
> > 1. We did nothing special during the night, just usual operations.
> > 2. We always have only one partition per collection.
> > 
> > We don't call flush in the code, we let the system auto-flush. There is definitively something strange because reverting back to 2.3.12, odd segments disappear and we are back to the normal number of segments. We can clearly see that those strange segments are never flushed or compacted, they stay here forever...
> 
> If you only have one collection and one partition, there seems to be no reason you will see 32 growing segments.
> 
> did you do import or insert? can you offer full logs for debug?

No we have 8 collections, since the rollback to 2.3.12, we have the correct number of segments and it's not growing.
![image](https://github.com/milvus-io/milvus/assets/144429952/e50ebe60-ffce-4b45-9940-7aeec604a2e6)

I'm starting to wonder if this is because client are only using SDK Go 2.3.2 ?

Sorry I cannot provide any logs since each time I rollback ASAP and our logging system is currently under maintenance u_u.
My workmate is not available today to give more insight on the client side.

**Comment by xiaofan-luan** [comment]
I guess this might not be related to SDK version. But we need more clues about why the log is created

**Comment by yanliang567** [comment]
@Archalbc I did not reproduce this issue in my milvus, but i can try more time. If it reproduced to you, could you please attach the etcd backup for investigation？ Check this: https://github.com/milvus-io/birdwatcher for details about how to backup etcd with birdwatcher.
One more question is could you please double check with your workmates that there is no insert or delete operations before/during the system upgrading?

**Comment by flsworld** [comment]
Hi, 
Sorry for late answer
> are you using bulkinsertion?
https://github.com/milvus-io/milvus/issues/33604 this might be the issue related.
We will fix this soon

Sorry for late answer !! We're not using bulk insert. We're upserting each time

**Comment by xiaofan-luan** [comment]
upsert seems to be the issue. becasue upsert also cause one delete on each search.
The segment is under L0 state. If you rollback your cluster version to 2.3, you might lost some deletes in L0 segments(because 2.3 don't recommend these deletes)

The segment number increase might be also related to L0 delete, but this might be as expected and won't affect search performance

**Comment by Archalbc** [comment]
> upsert seems to be the issue. becasue upsert also cause one delete on each search. The segment is under L0 state. If you rollback your cluster version to 2.3, you might lost some deletes in L0 segments(because 2.3 don't recommend these deletes)
> 
> The segment number increase might be also related to L0 delete, but this might be as expected and won't affect search performance

I can understand that upsert operations are kinda tricky, but I don't understand why we have a change of behavior on the cluster. Everything look fine in 2.3.12 and I doubt the cluster will be OK with an infinite number of segments (because you can see in the graph that it never stop creating segments and they are never cleaned.)

How can I securely provide you the etcd backup without exposing it here ?

**Comment by yanliang567** [comment]
please send it to my mail: yanliang.qiao@zilliz.com

**Comment by yanliang567** [comment]
/assign @congqixia 
please keep an eye on it
