### ISSUE TITLE
showPartitions blocked

### ISSUE THREAD

**Issue by whuawell** [milvus-io/milvus#3365]
**Please state your issue using the following template and, most importantly, in English.**
        
**Describe the bug**

            when testing milvus0.8.0-cpu docker , java-sdk-0.7.0,   it occasionally get blocked when running two days over.
      But , when you close sdk grpc client, reconnect , it got ok again. I only get stack infomation of this problem. 
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.
      The main code is below:

 ///////////////
	@Override
	public Object searchPreciseByFeature(String collectionName, List<Float> faceFeature, List<String> tags, int topK) {

		inUseCount.getAndIncrement();

		//client.flush(collectionName);
		List<String> dbTags = getAllTags(collectionName);

		if (!CollectionUtils.isNotEmpty(dbTags)) {

			return FaceReturnWrapper.builder().error().done();
		}

		List<String> filteredTags = filterTags(dbTags, tags);
		if (!CollectionUtils.isNotEmpty(filteredTags)) {

			return FaceReturnWrapper.builder().error().done();
		}

		List<List<Float>> vectors = Lists.newArrayList();
		vectors.add(faceFeature);

		SearchParam searchParam = new SearchParam.Builder(collectionName).withFloatVectors(vectors).withTopK(topK)
				.withPartitionTags(filteredTags).withParamsInJson("{\"nprobe\": 20}").build();

		SearchResponse searchResponse = client.search(searchParam);

		if (!searchResponse.ok()) {

			return FaceReturnWrapper.builder().error().done();
		}
		// You can also get result ids and distances separately
		
		List<List<QueryResult>> rsList = searchResponse.getQueryResultsList();
		
		if( rsList == null) {
			
			return FaceReturnWrapper.builder().error().done();
		}
		
		
	
		Set<FaceSearchRecord> rs = rsList.stream().flatMap(List::stream).map( t ->{
			
			if( t.getVectorId() == -1) {
				
				return null;
			}
			
			FaceSearchRecord rc = new FaceSearchRecord();
			rc.setFaceId(t.getVectorId());
			rc.setScore(t.getDistance() * 100);
			return rc;
			
		}).filter( Objects::nonNull).collect(Collectors.toSet());

		inUseCount.decrementAndGet();

		return FaceReturnWrapper.builder().ok().data(rs).done();

	}
//////////////
**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)

     centos7, Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz, no Gpu, 64G
- Method of installation (Docker, or from source)
       v0.8.0-cpu-docker
- Milvus version (v0.8.0-cpu-docker)
- Milvus configuration (Settings you made in `server_config.yaml`)
     default setting
**Screenshots**
    "Thread-4" #30 prio=5 os_prio=0 tid=0x0000000059661000 nid=0x225f4 waiting on condition [0x00000000660de000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000de4bb4c8> (a io.grpc.stub.ClientCalls$ThreadlessExecutor)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:681)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:133)
        at io.milvus.grpc.MilvusServiceGrpc$MilvusServiceBlockingStub.showPartitions(MilvusServiceGrpc.java:1825)
        at io.milvus.client.MilvusGrpcClient.showPartitions(MilvusGrpcClient.java:383
**Additional context**

**Comment by whuawell** [comment]
@Override
	public List<String> getAllTags(String collectionName) {
		
		return client.showPartitions(collectionName).getPartitionList();
	}

**Comment by sahuang** [comment]
`when testing milvus0.8.0-cpu docker , java-sdk-0.7.0,   it occasionally gets blocked when running two days over.
  But, when you close sdk grpc client, reconnect, it got ok again. I only get stack information of this problem.`

Since restarting SDK client solves the issue, there are two possible reasons that may cause this problem:

1) Callback is broken from Netty transport layer
2) gRPC channels blocking indefinitely and not respecting deadlines on network disconnect

It is hard to figure out the exact reason, but normally, the method blocks because of network issues and fails to reconnect.

**Comment by whuawell** [comment]
ok, i will continuous check this problem. thanks a lot.

**Comment by sahuang** [comment]
No worries.
