### ISSUE TITLE
[Bug]: DataNode oom may be caused by high msgstream memory usage

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#33676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4-20240605-68e5e643-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. deploy milvus with 1 dataNode
```
'dataNode': {'resources': {'limits': {'cpu': '4',
                                                     'memory': '16Gi'},
                                          'requests': {'cpu': '2',
                                                       'memory': '8Gi'}},
```
2. create collection with **1 shard**, enable partition key with **4096 partitions** -> index
3. insert 10m-128d entities -> flush -> index
5. concurrent upsert
```
 'concurrent_params': {'concurrent_number': 30,
                                                       'during_time': '5h',
                                                       'interval': 20,
                                                       'spawn_rate': None},
                                 'concurrent_tasks': [{'type': 'upsert',
                                                       'weight': 19,
                                                       'params': {'nb': 200,
                                                                  'timeout': 120,
                                                                  'start_id': 0,
                                                                  'random_id': True,
                                                                  'random_vector': True}}]},
```
 6. dataNode oomkilled multi times
 7. increased dataNode memory limit to 32Gi and is still oom
![image](https://github.com/milvus-io/milvus/assets/27288593/e62d6b13-237c-4ba4-80e7-e04869eef333)

- grafana: [metrics of compact-opt-op-79-7108](https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=P1809F7CD0C75ACF3&var-cluster=&var-namespace=qa-milvus&var-instance=compact-opt-op-79-7108&var-collection=All&var-app_name=milvus&from=1717584204550&to=1717642910575)

- flowgraph buffer size is always within 1GB
![image](https://github.com/milvus-io/milvus/assets/27288593/646a9884-c101-4710-91f1-3174e3412fc2)

- pprof
![image](https://github.com/milvus-io/milvus/assets/27288593/1a7428db-d914-41c2-a8e9-bb816b94a6f2)

### Steps To Reproduce

```markdown
argo: https://argo-workflows.zilliz.cc/archived-workflows/qa/72b9fe6e-831c-4230-9bd5-4509bf42f8d2?nodeId=compact-opt-no-flush-3
```

**Comment by XuanYang-cn** [comment]
![image](https://github.com/milvus-io/milvus/assets/51370125/11c5850b-894b-44b0-95a3-8dffee60b7c2)

**Comment by XuanYang-cn** [comment]
No Sync Tasks, BufferManager is the bottleneck.

**Comment by XuanYang-cn** [comment]
/assign @ThreadDao 
Seems fixed for DataNode Mem=32GB

**Comment by XuanYang-cn** [comment]
Please help verify @ThreadDao

**Comment by ThreadDao** [comment]
fixed
