### ISSUE TITLE
[Bug]: Async warmup doesn't work

### ISSUE THREAD

**Issue by bigsheeper** [milvus-io/milvus#33685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master&2.4
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Load segment progress is blocked by LoadStateLock in warmup, so async warmup becomes a sync operation.
![image](https://github.com/milvus-io/milvus/assets/42060877/380a0ae5-7b12-4f24-bde9-8095ec478a7a)
![image](https://github.com/milvus-io/milvus/assets/42060877/aee91bcd-e2b3-4c2b-8b6b-c7ca7233d7ea)

### Expected Behavior

Ensure async warmup remains async.

**Comment by chyezh** [comment]
should be fixed
