### ISSUE TITLE
[Bug]:docker pull milvusdb/milvus-operator:v0.9.16

### ISSUE THREAD

**Issue by gaoyuan5251** [milvus-io/milvus#33717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

docker pull milvusdb/milvus-operator:v0.9.16

v0.9.16: Pulling from milvusdb/milvus-operator
619be1103602: Pulling fs layer 
82f369ebafd1: Pulling fs layer 
error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/d6/d63b9dfce3553b3cee62ffd7cd0c2500e11a4ebb695842469cd94fadad1350f0/data?verify=1717745999-vZ8L%2FTd9nDMCZvzls6Do2%2F5DYq0%3D: dial tcp 173.255.209.47:443: connect: connection timed out

### Expected Behavior

docker image can be pulled down

**Comment by yanliang567** [comment]
@gaoyuan5251 I think that's a network issue to dockerhub or your proxy
/assign @gaoyuan5251 
/unassign

**Comment by gaoyuan5251** [comment]
> @gaoyuan5251 I think that's a network issue to dockerhub or your proxy /assign @gaoyuan5251 /unassign

如果是dockerhub的问题我要如何解决？
我已经替换了国内镜像源

**Comment by gaoyuan5251** [comment]
> @gaoyuan5251 I think that's a network issue to dockerhub or your proxy /assign @gaoyuan5251 /unassign
@yanliang567 
gaoyuan@gaoyuandeMacBook-Pro Downloads % docker pull milvusdb/milvus-operator:v0.9.16

v0.9.16: Pulling from milvusdb/milvus-operator
619be1103602: Retrying in 1 second 
82f369ebafd1: Retrying in 1 second 
error pulling image configuration: download failed after attempts=6: dial tcp 199.96.58.157:443: i/o timeout


看样子应该是dockerhub的问题？我在自己mac上也拉不下来。

**Comment by shaoting-huang** [comment]
/assign @gaoyuan5251 It's a network issue. I can pull from my mac. 
`docker pull milvusdb/milvus-operator:v0.9.16
v0.9.16: Pulling from milvusdb/milvus-operator
c6b39de5b339: Pull complete 
e54fdd029c3d: Pull complete 
Digest: sha256:5a051e8807507bf0a0012d4c7d4f29513d6c434016f66facced22423aa8504c0
Status: Downloaded newer image for milvusdb/milvus-operator:v0.9.16
docker.io/milvusdb/milvus-operator:v0.9.16`

**Comment by zxy76** [comment]
我开了ghelper，能在浏览器登录hub.docker.com。但是为啥mac终端访问不了hub.docker.com呢？求解答，谢谢

**Comment by shaoting-huang** [comment]
try this, https://gist.github.com/y0ngb1n/7e8f16af3242c7815e7ca2f0833d3ea6
