### ISSUE TITLE
[Bug]: Milvus Not able to take datatype for sparse vectors

### ISSUE THREAD

**Issue by Nik-su** [milvus-io/milvus#33718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I am getting the same error for sparse vectors. Client is not able to define the schema for it as below despite using the version pymilvus==2.4.1:
DEBUG:pymilvus.milvus_client.milvus_client:Created new connection using: ae315cf6a32347198cb1f4bb683dc46c
WARNING:pymilvus.decorators:[create_collection] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNKNOWN, unsupported data type when creating collection, data type: SparseFloatVector, filed name: sparse_vector>

### Steps To Reproduce

```markdown
There can be two ways in which thus can be handles

Either change the sparse embedding to dense embeddings and insert in dense embeddings which in my understanding will not be able to get the accurate results for the milvus search.
Second could be the milvus version that need to be taken care of .
Please reply for the debugging
```

### Milvus Log

I am getting the same error for sparse vectors. Client is not able to define the schema for it as below despite using the version pymilvus==2.4.1:
DEBUG:pymilvus.milvus_client.milvus_client:Created new connection using: ae315cf6a32347198cb1f4bb683dc46c
WARNING:pymilvus.decorators:[create_collection] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNKNOWN, unsupported data type when creating collection, data type: SparseFloatVector, filed name: sparse_vector>

There can be two ways in which thus can be handles

Either change the sparse embedding to dense embeddings and insert in dense embeddings which in my understanding will not be able to get the accurate results for the milvus search.
Second could be the milvus version that need to be taken care of .
Please reply for the debugging

### Anything else?

Help me find out this debug for Sparse Vector Datatype

**Comment by xiaofan-luan** [comment]
what server version did you use?

**Comment by Nik-su** [comment]
I am using pymilvus==2.4.1 and i am loading the sparse vector in the milvus ziliz cloud and i am getting this error

**Comment by xiaofan-luan** [comment]
> I am using pymilvus==2.4.1 and i am loading the sparse vector in the milvus ziliz cloud and i am getting this error

Zilliz cloud doesn't support sparse embedding for now. Sorry for the misunderstanding. We are targeting on beta milvus 2.4 related feature this month

**Comment by Nik-su** [comment]
Okay thanks for replying ,
I am looking forward for new feature for Sparse embeddings ,which will get me more context for my data 
Thanks

**Comment by xiaofan-luan** [comment]
> Okay thanks for replying , I am looking forward for new feature for Sparse embeddings ,which will get me more context for my data Thanks

You can contact us through zilliz cloud ticket portal. Any question about zilliz cloud will be answered there in time

**Comment by yanliang567** [comment]
I'd close this issue. For the privacy issue, please open tickets in suppot.zilliz.con for any questions for zilliz cloud
