### ISSUE TITLE
[Bug]: Kafka credentials is getting printed in the logs

### ISSUE THREAD

**Issue by Ald392** [milvus-io/milvus#33727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When i run milvus, i am seeing my kafka credentials getting printed in the logs without any masking.

### Expected Behavior

Kafka credentials must be masked in the logs 

### Milvus Log

```
[2024/05/30 04:15:21.354 +00:00] [INFO] [kafka/kafka_client.go:52] ["init kafka Config "]
 [commonConfig="+map[api.version.request:true bootstrap.servers:<servers gets printed> 
reconnect.backoff.max.ms:5000 reconnect.backoff.ms:20 sasl.mechanisms:PLAIN sasl.password:
<plaintext-password-was-printed-here!> sasl.username:<plaintext-username-was-printed-here!> 
security.protocol:SASL_SSL]"] [extraConsumerConfig="+map[]"] [extraProducerConfig="+map[]"]
```

### Anything else?

The printing is done by this line in my case : 
https://github.com/milvus-io/milvus/blob/3729d2c8e77220303daf1d84de3a66e621319e0b/pkg/mq/msgstream/mqwrapper/kafka/kafka_client.go#L52

**Comment by xiaofan-luan** [comment]
thanks for the pr @Ald392 
would you mind backport to 2.4 so we will release a fix soon

**Comment by Ald392** [comment]
@xiaofan-luan Do you want me to raise a PR here : https://github.com/milvus-io/milvus/tree/2.4

**Comment by yanliang567** [comment]
> @xiaofan-luan Do you want me to raise a PR here : https://github.com/milvus-io/milvus/tree/2.4

yes, please

**Comment by yanliang567** [comment]
@Ald392 thanks for contributions. I'd close this issue now
