### ISSUE TITLE
[Enhancement]: Database/Collection Name's are not coming along with the post/get requests

### ISSUE THREAD

**Issue by kish5430** [milvus-io/milvus#33732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

HI Team,

When performing tasks such as creating or dropping collections, inserting vectors, or creating databases, the POST/GET requests lack database or collection names. This makes it challenging to track these requests in logs, especially in a multi-tenant cluster architecture.

Thanks

### Why is this needed?

This makes it challenging to track these requests in logs, especially in a multi-tenant cluster architecture.

**Comment by SimFG** [comment]
What is missing in the get/post request here? I checked the latest restful api and found that the collection and db name can be specified.
refer doc: https://milvus.io/api-reference/restful/v2.4.x/v2/Vector%20(v2)/Insert.md

**Comment by kish5430** [comment]
HI @SimFG Missing database and collection names in the logs. From the example below, it's difficult to determine from which database and collection made the search request

Logs:
240.56.64.157 - - [06/Jun/2024:00:28:23 +0000] "POST /milvus.proto.milvus.MilvusService/Search HTTP/2.0" 200 446 "-" "grpc-java-netty/1.46.0" 1582 0.015 [isds-milvus-isds-milvus-milvus-19530] [] 240.16.21.11:19530 488 0.015 200 9a63416ee0fa0b8912f05019055f1f2d
host = gke-isds-genai-gcp-m-isds-genai-gcp-m-1e36150f-vfyj source = /var/log/containers/ingress-nginx-controller-8c49976fb-q829r_ingress-nginx_controller-dd9d562621a3cd2e9ebae5bdcaaf172961727f6238e019f5a3df83a39715ad39.log sourcetype = kube:container:controller
 

Thanks

**Comment by xiaofan-luan** [comment]
> HI @SimFG Missing database and collection names in the logs. From the example below, it's difficult to determine from which database and collection made the search request
> 
> Logs: 240.56.64.157 - - [06/Jun/2024:00:28:23 +0000] "POST /milvus.proto.milvus.MilvusService/Search HTTP/2.0" 200 446 "-" "grpc-java-netty/1.46.0" 1582 0.015 [isds-milvus-isds-milvus-milvus-19530] [] 240.16.21.11:19530 488 0.015 200 9a63416ee0fa0b8912f05019055f1f2d host = gke-isds-genai-gcp-m-isds-genai-gcp-m-1e36150f-vfyj source = /var/log/containers/ingress-nginx-controller-8c49976fb-q829r_ingress-nginx_controller-dd9d562621a3cd2e9ebae5bdcaaf172961727f6238e019f5a3df83a39715ad39.log sourcetype = kube:container:controller
> 
> Thanks

this is not milvus log right?
you can specify dbname  optionally and collection name is a must. I'm not sure how you get this log but you can definitely add collection name into the log

**Comment by kish5430** [comment]
> > HI @SimFG Missing database and collection names in the logs. From the example below, it's difficult to determine from which database and collection made the search request
> > Logs: 240.56.64.157 - - [06/Jun/2024:00:28:23 +0000] "POST /milvus.proto.milvus.MilvusService/Search HTTP/2.0" 200 446 "-" "grpc-java-netty/1.46.0" 1582 0.015 [isds-milvus-isds-milvus-milvus-19530] [] 240.16.21.11:19530 488 0.015 200 9a63416ee0fa0b8912f05019055f1f2d host = gke-isds-genai-gcp-m-isds-genai-gcp-m-1e36150f-vfyj source = /var/log/containers/ingress-nginx-controller-8c49976fb-q829r_ingress-nginx_controller-dd9d562621a3cd2e9ebae5bdcaaf172961727f6238e019f5a3df83a39715ad39.log sourcetype = kube:container:controller
> > Thanks
> 
> this is not milvus log right? you can specify dbname optionally and collection name is a must. I'm not sure how you get this log but you can definitely add collection name into the log

@SimFG This is only the Milvus log. I was mentioning that the Milvus-level logs do not contain the database name and collection name. I can add them manually, but it's not recommended

**Comment by SimFG** [comment]
@kish5430 How did you get this log, a file or a command?

**Comment by kish5430** [comment]
> @kish5430 How did you get this log, a file or a command?

We are forwarding all milvus logs to splunk. I have captured from splunk

**Comment by SimFG** [comment]
But this log does not seem to be the milvus server log

**Comment by kish5430** [comment]
> But this log does not seem to be the milvus server log

@SimFG Please ignore the above log. I'm not seeing the collection and database names in the logs for search, create, delete, and other operations. I hope you agree with this. Could you plan to add this information?

**Comment by SimFG** [comment]
@kish5430 In addition to the logs above, can you give other the milvus logs you see? Because I don't know where to add this information.
