### ISSUE TITLE
[Bug]: Sync PartitonStats task may block balance tasks

### ISSUE THREAD

**Issue by MrPresent-Han** [milvus-io/milvus#33741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Currently, when sync partition stats was blocked inside scheduler, balance mechanism will be blocked.

**Comment by xiaofan-luan** [comment]
@MrPresent-Han 
do we need to backport this to 2.4?
