### ISSUE TITLE
[Bug]: fail to pull milvus docker image

### ISSUE THREAD

**Issue by limuan123123** [milvus-io/milvus#33748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

为什么拉取milvus官方docker镜像一直超时呢？？

### Expected Behavior

为什么拉取milvus官方docker镜像一直超时呢？？

### Steps To Reproduce

```markdown
为什么拉取milvus官方docker镜像一直超时呢？？
```

### Milvus Log

为什么拉取milvus官方docker镜像一直超时呢？？

### Anything else?

为什么拉取milvus官方docker镜像一直超时呢？？

**Comment by SimFG** [comment]
Can you get other images normally? And can you provide the command you used to pull the image?

**Comment by xiaofan-luan** [comment]
I think you will need a proxy to fetch docker image from dockerhub or use other repo

**Comment by shaoting-huang** [comment]
assign @limuan123123 similar to #33717

**Comment by hahahhuang** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version:
> - Deployment mode(standalone or cluster):
> - MQ type(rocksmq, pulsar or kafka):    
> - SDK version(e.g. pymilvus v2.0.0rc2):
> - OS(Ubuntu or CentOS): 
> - CPU/Memory: 
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> 为什么拉取milvus官方docker镜像一直超时呢？？
> 
> ### Expected Behavior
> 为什么拉取milvus官方docker镜像一直超时呢？？
> 
> ### Steps To Reproduce
> ```
> 为什么拉取milvus官方docker镜像一直超时呢？？
> ```
> 
> ### Milvus Log
> 为什么拉取milvus官方docker镜像一直超时呢？？
> 
> ### Anything else?
> 为什么拉取milvus官方docker镜像一直超时呢？？

请教下，最后解决了吗？我拉镜像也拉不下来。其他的镜像能下载，但是milvus和minio的镜像拉取都超时

**Comment by shaoting-huang** [comment]
try this, https://gist.github.com/y0ngb1n/7e8f16af3242c7815e7ca2f0833d3ea6

**Comment by yanliang567** [comment]
close for this is a network issue
