### ISSUE TITLE
[Enhancement]: Change etcd request default timeout to 30s.

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#33758]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Now the etcd is timeout is 10s.
We've seen under many cases where user try to deploy etcd on sata disk (which is highly unrecommended)， milvus panic due to etcd request failure.
Etcd fail recovered time is typically less than 30s. So change etcd request timeout to 30s might reduce the possibility to etcd unresposiveness.

**Comment by nexuewen** [comment]
How to configure etcd request timeout?
