### ISSUE TITLE
[Bug]: MMAP regression with Milvus 2.4.x

### ISSUE THREAD

**Issue by artin-recollective** [milvus-io/milvus#33808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.4
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): Kafka 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory:
- GPU: 
- Others:
```

### Current Behavior

When upgraded to Milvus 2.4.4 with  mmap enabled, when collection load is triggered, Milvus is evaluating memory size of the segment, instead of evaluating the disk size. This was working fine in 2.3.12 and the issue has been introduced to 2.4.4. I suspect the issue is arising from the following:
```
if predictMemUsage > uint64(float64(totalMem)*paramtable.Get().QueryNodeCfg.OverloadedMemoryThresholdPercentage.GetAsFloat()) {
        return 0, 0, fmt.Errorf("load segment failed, OOM if load, maxSegmentSize = %v MB,  memUsage = %v MB, predictMemUsage = %v MB, totalMem = %v MB thresholdFactor = %f",
            toMB(maxSegmentSize),
            toMB(memUsage),
            toMB(predictMemUsage),
            toMB(totalMem),
            paramtable.Get().QueryNodeCfg.OverloadedMemoryThresholdPercentage.GetAsFloat())
    }

    if predictDiskUsage > uint64(float64(paramtable.Get().QueryNodeCfg.DiskCapacityLimit.GetAsInt64())*paramtable.Get().QueryNodeCfg.MaxDiskUsagePercentage.GetAsFloat()) {
        return 0, 0, merr.WrapErrServiceDiskLimitExceeded(float32(predictDiskUsage), float32(paramtable.Get().QueryNodeCfg.DiskCapacityLimit.GetAsInt64()), fmt.Sprintf("load segment failed, disk space is not enough, diskUsage = %v MB, predictDiskUsage = %v MB, totalDisk = %v MB, thresholdFactor = %f",
            toMB(diskUsage),
            toMB(predictDiskUsage),
            toMB(uint64(paramtable.Get().QueryNodeCfg.DiskCapacityLimit.GetAsInt64())),
            paramtable.Get().QueryNodeCfg.MaxDiskUsagePercentage.GetAsFloat()))
    }
```
In https://github.com/milvus-io/milvus/blob/9ab3058da2750010e013e0b8836dde1b32365c49/internal/querynodev2/segments/segment_loader.go#L1563

This prevents us from loading segments/collections that will not fit into memory, but they will fit onto the disk.

### Expected Behavior

Memory size should not be checked.

### Steps To Reproduce

```markdown
1. Have a collection with huge data/segments in it
2. Enable mmap
3. Try loading a collection (with segments that won't fit into memory)
4.
```

### Milvus Log

[2024/06/10 21:24:22.219 +00:00] [WARN] [segments/segment_loader.go:843] ["no sufficient resource to load segments"] [traceID=e57e258462037859f1e7f964f564a095] [segmentIDs="[449469341520221184]"] [error="load segment failed, OOM if load, maxSegmentSize = 21010.453788757324 MB,  memUsage = 10014.42195224762 MB, predictMemUsage = 31024.875741004944 MB, totalMem = 12288 MB thresholdFactor = 0.900000"]
[2024/06/10 21:24:22.219 +00:00] [WARN] [segments/segment_loader.go:634] ["request resource failed"] [traceID=e57e258462037859f1e7f964f564a095] [collectionID=449469341520987343] [segmentType=Sealed] [requestSegments="[449469341520221184]"] [preparedSegments="[449469341520221184]"] [error="load segment failed, OOM if load, maxSegmentSize = 21010.453788757324 MB,  memUsage = 10014.42195224762 MB, predictMemUsage = 31024.875741004944 MB, totalMem = 12288 MB thresholdFactor = 0.900000"]
[2024/06/10 21:24:22.219 +00:00] [WARN] [delegator/delegator_data.go:472] ["worker failed to load segments"] [traceID=e57e258462037859f1e7f964f564a095] [collectionID=449469341520987343] [channel=by-dev-rootcoord-dml_13_449469341520987343v0] [replicaID=450377500229894145] [workID=816] [segments="[449469341520221184]"] [error="load segment failed, OOM if load, maxSegmentSize = 21010.453788757324 MB,  memUsage = 10014.42195224762 MB, predictMemUsage = 31024.875741004944 MB, totalMem = 12288 MB thresholdFactor = 0.900000"]
[2024/06/10 21:24:22.220 +00:00] [WARN] [querynodev2/services.go:454] ["delegator failed to load segments"] [traceID=e57e258462037859f1e7f964f564a095] [collectionID=449469341520987343] [partitionID=449469341520987344] [shard=by-dev-rootcoord-dml_13_449469341520987343v0] [segmentID=449469341520221184] [currentNodeID=816] [error="load segment failed, OOM if load, maxSegmentSize = 21010.453788757324 MB,  memUsage = 10014.42195224762 MB, predictMemUsage = 31024.875741004944 MB, totalMem = 12288 MB thresholdFactor = 0.900000"]
I20240610 21:24:22.290760    43 DataCodec.cpp:123] [SERVER][DeserializeFileData][milvus] DeserializeFileData_deserialize_duration_ms:3
I20240610 21:24:22.400924    43 DataCodec.cpp:123] [SERVER][DeserializeFileData][milvus] DeserializeFileData_deserialize_duration_ms:12

**Comment by yanliang567** [comment]
/assign @sunby 
please help to check
/unassign

**Comment by sunby** [comment]
@artin-recollective Even with mmap enabled, a segment needs to be first loaded into memory, processed, and then serialized into an mmap file. So, predicting memory usage is expected. The issue here is that you've set the maximum size of the segment larger than the available memory, which prevents the segment from being loaded into memory. This 21010MB segment may be generated by compaction. The reason why v2.3.13 works should be that no segment bigger than memory size is generated.

**Comment by artin-recollective** [comment]
@sunby the data is the same that is being used in 2.3.12, just trying to load the same collection with mmap being enabled. 2.3.12 works, and 2.4.x does not work. I am using the exact same limits, segment sizes and host machine for query node for both versions. To clarify my segment size is 512MB and max segment size is configured at 1024
The same validation in 2.3.12 considers if mmap is enabled first before failing it:
```
if !mmapEnabled && predictMemUsage > uint64(float64(totalMem)*paramtable.Get().QueryNodeCfg.OverloadedMemoryThresholdPercentage.GetAsFloat()) {
		return 0, 0, fmt.Errorf("load segment failed, OOM if load, maxSegmentSize = %v MB, concurrency = %d, memUsage = %v MB, predictMemUsage = %v MB, totalMem = %v MB thresholdFactor = %f",
			toMB(maxSegmentSize),
			concurrency,
			toMB(memUsage),
			toMB(predictMemUsage),
			toMB(totalMem),
			paramtable.Get().QueryNodeCfg.OverloadedMemoryThresholdPercentage.GetAsFloat())
	}

	if mmapEnabled && memUsage > uint64(float64(totalMem)*paramtable.Get().QueryNodeCfg.OverloadedMemoryThresholdPercentage.GetAsFloat()) {
		return 0, 0, fmt.Errorf("load segment failed, OOM if load, maxSegmentSize = %v MB, concurrency = %d, memUsage = %v MB, predictMemUsage = %v MB, totalMem = %v MB thresholdFactor = %f",
			toMB(maxSegmentSize),
			concurrency,
			toMB(memUsage),
			toMB(predictMemUsage),
			toMB(totalMem),
			paramtable.Get().QueryNodeCfg.OverloadedMemoryThresholdPercentage.GetAsFloat())
	}
```

https://github.com/milvus-io/milvus/blob/835862df22c5c8f531fedf6cc024f89f0a50a3c6/internal/querynodev2/segments/segment_loader.go#L1062C2-L1080C3

**Comment by sunby** [comment]
> @sunby the data is the same that is being used in 2.3.12, just trying to load the same collection with mmap being enabled. 2.3.12 works, and 2.4.x does not work. I am using the exact same limits, segment sizes and host machine for query node for both versions. To clarify my segment size is 512MB and max segment size is configured at 1024 The same validation in 2.3.12 considers if mmap is enabled first before failing it:
> 
> ```
> if !mmapEnabled && predictMemUsage > uint64(float64(totalMem)*paramtable.Get().QueryNodeCfg.OverloadedMemoryThresholdPercentage.GetAsFloat()) {
> 		return 0, 0, fmt.Errorf("load segment failed, OOM if load, maxSegmentSize = %v MB, concurrency = %d, memUsage = %v MB, predictMemUsage = %v MB, totalMem = %v MB thresholdFactor = %f",
> 			toMB(maxSegmentSize),
> 			concurrency,
> 			toMB(memUsage),
> 			toMB(predictMemUsage),
> 			toMB(totalMem),
> 			paramtable.Get().QueryNodeCfg.OverloadedMemoryThresholdPercentage.GetAsFloat())
> 	}
> 
> 	if mmapEnabled && memUsage > uint64(float64(totalMem)*paramtable.Get().QueryNodeCfg.OverloadedMemoryThresholdPercentage.GetAsFloat()) {
> 		return 0, 0, fmt.Errorf("load segment failed, OOM if load, maxSegmentSize = %v MB, concurrency = %d, memUsage = %v MB, predictMemUsage = %v MB, totalMem = %v MB thresholdFactor = %f",
> 			toMB(maxSegmentSize),
> 			concurrency,
> 			toMB(memUsage),
> 			toMB(predictMemUsage),
> 			toMB(totalMem),
> 			paramtable.Get().QueryNodeCfg.OverloadedMemoryThresholdPercentage.GetAsFloat())
> 	}
> ```
> 
> https://github.com/milvus-io/milvus/blob/835862df22c5c8f531fedf6cc024f89f0a50a3c6/internal/querynodev2/segments/segment_loader.go#L1062C2-L1080C3

@artin-recollective Thanks for your reply! 
There's a known bug in v2.3.x that compaction may create a very large segment(much larger than the max segment size). That's maybe why this segment is generated.
And IMO the memory check codes in v2.3.x is wrong because the segment should be loaded into memory first. 
As for this 

> 2.3.12 works, and 2.4.x does not work

I think this large segment may be created in v2.3.x but not loaded. Milvus works fine because this segment's ancestors are already be loaded. But after you upgrade to v2.4.x, loading collection will choose this segment to be loaded so loading fails. 

You can try to do a loading in v2.3.x again and I expect it will fail.

**Comment by sunby** [comment]
@artin-recollective If you have the v2.3.x logs, please help to search this keyword "load segments done" and "449469341520221184" (segment id) to check this segment was loaded successfully.

**Comment by artin-recollective** [comment]
> > @sunby the data is the same that is being used in 2.3.12, just trying to load the same collection with mmap being enabled. 2.3.12 works, and 2.4.x does not work. I am using the exact same limits, segment sizes and host machine for query node for both versions. To clarify my segment size is 512MB and max segment size is configured at 1024 The same validation in 2.3.12 considers if mmap is enabled first before failing it:
> > ```
> > if !mmapEnabled && predictMemUsage > uint64(float64(totalMem)*paramtable.Get().QueryNodeCfg.OverloadedMemoryThresholdPercentage.GetAsFloat()) {
> > 		return 0, 0, fmt.Errorf("load segment failed, OOM if load, maxSegmentSize = %v MB, concurrency = %d, memUsage = %v MB, predictMemUsage = %v MB, totalMem = %v MB thresholdFactor = %f",
> > 			toMB(maxSegmentSize),
> > 			concurrency,
> > 			toMB(memUsage),
> > 			toMB(predictMemUsage),
> > 			toMB(totalMem),
> > 			paramtable.Get().QueryNodeCfg.OverloadedMemoryThresholdPercentage.GetAsFloat())
> > 	}
> > 
> > 	if mmapEnabled && memUsage > uint64(float64(totalMem)*paramtable.Get().QueryNodeCfg.OverloadedMemoryThresholdPercentage.GetAsFloat()) {
> > 		return 0, 0, fmt.Errorf("load segment failed, OOM if load, maxSegmentSize = %v MB, concurrency = %d, memUsage = %v MB, predictMemUsage = %v MB, totalMem = %v MB thresholdFactor = %f",
> > 			toMB(maxSegmentSize),
> > 			concurrency,
> > 			toMB(memUsage),
> > 			toMB(predictMemUsage),
> > 			toMB(totalMem),
> > 			paramtable.Get().QueryNodeCfg.OverloadedMemoryThresholdPercentage.GetAsFloat())
> > 	}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://github.com/milvus-io/milvus/blob/835862df22c5c8f531fedf6cc024f89f0a50a3c6/internal/querynodev2/segments/segment_loader.go#L1062C2-L1080C3
> 
> @artin-recollective Thanks for your reply! There's a known bug in v2.3.x that compaction may create a very large segment(much larger than the max segment size). That's maybe why this segment is generated. And IMO the memory check codes in v2.3.x is wrong because the segment should be loaded into memory first. As for this
> 
> > 2.3.12 works, and 2.4.x does not work
> 
> I think this large segment may be created in v2.3.x but not loaded. Milvus works fine because this segment's ancestors are already be loaded. But after you upgrade to v2.4.x, loading collection will choose this segment to be loaded so loading fails.
> 
> You can try to do a loading in v2.3.x again and I expect it will fail.

Thanks for the info @sunby, I actually have reverted back to 2.3.12 and loaded the collection again without any problems. I have done the switch multiple times for testing and the collection actually gets fully loaded.
I haven't investigated the code fully to understand if the whole segment gets loaded into memory first and then offloaded to disk, but it seems to me like in 2.3.12, the mmap functionality is working correctly and flexibility with whatever memory amount is available. That only makes sense since the whole concept of mmap is to use less memory.
I am curious if there's a fix for the big segment size that you mentioned? Is there a way to fix the segments that have grown too big?

**Comment by artin-recollective** [comment]
> @artin-recollective If you have the v2.3.x querycoord logs and the log level is info, please help to search this keyword "load segments done" and "449469341520221184" (segment id) to check this segment was loaded successfully.

I actually checked the logs in 2.3.12 after downgrading from 2.4.4 and I can actually find the `load segments done` logs in both query coord and query node for that segments. In fact I can see the collection has 5 segments and I can find `load segments done`  logs for all 5 segments in both query node and query coord.

querycoord logs:
```
[2024/06/14 15:08:46.293 +00:00] [INFO] [task/executor.go:251] ["load segments done"] [taskID=1718377018226] [collectionID=449469341520987343] [replicaID=450462225059282945] [segmentID=449469341520221184] [node=883] [source=segment_checker] [shardLeader=883] [elapsed=9m23.508329564s]
```

querynode logs:
```
[2024/06/14 15:08:46.000 +00:00] [INFO] [querynodev2/services.go:501] ["load segments done..."] [traceID=74bb001f3eaf6896c63d0b2e78ad90ca] [collectionID=449469341520987343] [partitionID=449469341520987344] [shard=by-dev-rootcoord-dml_13_449469341520987343v0] [segmentID=449469341520221184] [currentNodeID=883] [segments="[449469341520221184]"]
```

**Comment by xiaofan-luan** [comment]
> @artin-recollective Even with mmap enabled, a segment needs to be first loaded into memory, processed, and then serialized into an mmap file. So, predicting memory usage is expected. The issue here is that you've set the maximum size of the segment larger than the available memory, which prevents the segment from being loaded into memory. This 21010MB segment may be generated by compaction. The reason why v2.3.12 works should be that no segment bigger than memory size is generated.

is there a reason we changed to such large segment size?

Our recommendation is to use 4-8g segment size, for the reason:
1. large segment induild is much slower (takes 1 hour or more to build each time)
2. large segment can not be balanced evenly on all querynodes.
3. large segments takes memory to load, we each at least 1 x segment size extra memory to load. which means you have to have at least 20G memory to load a 20G segment even with mmap.(Without mmap that will be even more).

**Comment by xiaofan-luan** [comment]
with 12GB memory, 4GB segment size is what we recommended.

**Comment by xiaofan-luan** [comment]
you can always tune the param to remove the check, but this may cause oom and other unexpected behaviours

**Comment by artin-recollective** [comment]
My segment size is 

> with 12GB memory, 2/4GB segment size is what we recommended.

I am using all the default configs for segment size, so it should be 512 from: https://github.com/milvus-io/milvus/blob/v2.3.12/configs/milvus.yaml

**Comment by artin-recollective** [comment]
> > @sunby the data is the same that is being used in 2.3.12, just trying to load the same collection with mmap being enabled. 2.3.12 works, and 2.4.x does not work. I am using the exact same limits, segment sizes and host machine for query node for both versions. To clarify my segment size is 512MB and max segment size is configured at 1024 The same validation in 2.3.12 considers if mmap is enabled first before failing it:
> > ```
> > if !mmapEnabled && predictMemUsage > uint64(float64(totalMem)*paramtable.Get().QueryNodeCfg.OverloadedMemoryThresholdPercentage.GetAsFloat()) {
> > 		return 0, 0, fmt.Errorf("load segment failed, OOM if load, maxSegmentSize = %v MB, concurrency = %d, memUsage = %v MB, predictMemUsage = %v MB, totalMem = %v MB thresholdFactor = %f",
> > 			toMB(maxSegmentSize),
> > 			concurrency,
> > 			toMB(memUsage),
> > 			toMB(predictMemUsage),
> > 			toMB(totalMem),
> > 			paramtable.Get().QueryNodeCfg.OverloadedMemoryThresholdPercentage.GetAsFloat())
> > 	}
> > 
> > 	if mmapEnabled && memUsage > uint64(float64(totalMem)*paramtable.Get().QueryNodeCfg.OverloadedMemoryThresholdPercentage.GetAsFloat()) {
> > 		return 0, 0, fmt.Errorf("load segment failed, OOM if load, maxSegmentSize = %v MB, concurrency = %d, memUsage = %v MB, predictMemUsage = %v MB, totalMem = %v MB thresholdFactor = %f",
> > 			toMB(maxSegmentSize),
> > 			concurrency,
> > 			toMB(memUsage),
> > 			toMB(predictMemUsage),
> > 			toMB(totalMem),
> > 			paramtable.Get().QueryNodeCfg.OverloadedMemoryThresholdPercentage.GetAsFloat())
> > 	}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://github.com/milvus-io/milvus/blob/835862df22c5c8f531fedf6cc024f89f0a50a3c6/internal/querynodev2/segments/segment_loader.go#L1062C2-L1080C3
> 
> @artin-recollective Thanks for your reply! There's a known bug in v2.3.x that compaction may create a very large segment(much larger than the max segment size). That's maybe why this segment is generated. And IMO the memory check codes in v2.3.x is wrong because the segment should be loaded into memory first. As for this
> 
> > 2.3.12 works, and 2.4.x does not work
> 
> I think this large segment may be created in v2.3.x but not loaded. Milvus works fine because this segment's ancestors are already be loaded. But after you upgrade to v2.4.x, loading collection will choose this segment to be loaded so loading fails.
> 
> You can try to do a loading in v2.3.x again and I expect it will fail.

@sunby is there any way that I can find the segments that are larger than expected? For example in s3 or with a sdk call that shows the segment size in MBs?

**Comment by xiaofan-luan** [comment]
using birdwatcher can get the all the segment size
