### ISSUE TITLE
[Bug]: milvus stand-alone exited with code 134,after inserting 40~50*2048nodes 

### ISSUE THREAD

**Issue by Prototypeex** [milvus-io/milvus#33826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4.4
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka): don't know use docker-compose
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus
- OS(Ubuntu or CentOS): WSL Windows
- CPU/Memory: intel i9-13980hx/32GB
- GPU: 4080laptop
- Others: use llamaindex MilvusVectorStore to build index
```

### Current Behavior

build index and store in Milvus volume using docker-compose。after 40~50*2048nodes embedded，the milvus-standalone exited 134 then the building process is interrupted.If set restart:always,the re-connection consumes time and fail in RPC check where node is not matched
[docker_standalone_exited_134.txt](https://github.com/user-attachments/files/15814828/docker_standalone_exited_134.txt)

### Expected Behavior

index build successfully and stored in volume

**Comment by Prototypeex** [comment]
checked the memory,disk,the space is enough before the exit happened

**Comment by SimFG** [comment]
This error seems to be caused by data corruption, not an internal error of milvus, link: https://answers.microsoft.com/en-us/windows/forum/all/how-to-take-files-off-a-drive-with-a-crc-error/1ab492e5-300c-4819-ae52-9c6287debbc8
![image](https://github.com/milvus-io/milvus/assets/21985684/75de5ad5-71dc-4142-b421-780696271dcf)

**Comment by Prototypeex** [comment]
> This error seems to be caused by data corruption, not an internal error of milvus

thanks for reply.I built index **using same documents successfully in local disk** by using llamaindex SimpleVectorIndex,even though the loading process is time consuming whith led me to Milvus.I tried to build index in smaller amount of texts by Milvus,which successed.This issue is almost 100% to happen when data is over a limit.

**Comment by Prototypeex** [comment]
Loading files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2606/2606 [00:00<00:00, 4358.88file/s]
Loaded 2606 documents. 2024-06-13 14:32:50
Parsing nodes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2606/2606 [01:17<00:00, 33.66it/s] 
Generated 237605 nodes from documents. 2024-06-13 14:34:18
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:15<00:00, 131.83it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:14<00:00, 138.85it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:14<00:00, 139.42it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:15<00:00, 133.42it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:15<00:00, 130.57it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:15<00:00, 134.19it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:15<00:00, 133.60it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:15<00:00, 132.04it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:15<00:00, 134.88it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:15<00:00, 133.06it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:14<00:00, 138.17it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:15<00:00, 133.80it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:15<00:00, 134.64it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:15<00:00, 133.67it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:14<00:00, 138.94it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:14<00:00, 136.64it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:14<00:00, 141.68it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:14<00:00, 145.23it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:14<00:00, 141.54it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:14<00:00, 140.18it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:14<00:00, 141.02it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:14<00:00, 139.02it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:14<00:00, 142.05it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:14<00:00, 141.97it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:14<00:00, 142.72it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:14<00:00, 141.07it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:14<00:00, 142.47it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:14<00:00, 143.78it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:14<00:00, 141.67it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:15<00:00, 133.63it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:14<00:00, 140.97it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:15<00:00, 134.33it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:15<00:00, 129.62it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:15<00:00, 128.44it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:15<00:00, 130.07it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:15<00:00, 128.91it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:15<00:00, 128.80it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:15<00:00, 133.51it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:16<00:00, 126.81it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:15<00:00, 130.59it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:15<00:00, 131.46it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:14<00:00, 143.53it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:14<00:00, 138.98it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:15<00:00, 135.09it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:15<00:00, 133.97it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:15<00:00, 131.66it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:15<00:00, 135.93it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:15<00:00, 132.06it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:15<00:00, 129.33it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:15<00:00, 131.98it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:15<00:00, 134.20it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:15<00:00, 133.34it/s]
[describe_collection] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:19530: Connection refused>
......
RPC error: [describe_collection], <MilvusException: (code=<bound method _MultiThreadedRendezvous.code of <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:19530: Connection refused"
        debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-06-13T06:59:14.8718024+00:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:19530: Connection refused"}"
>>, message=Retry run out of 75 retry times, message=failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:19530: Connection refused)>, <Time:{'RPC start': '2024-06-13 14:55:39.274645', 'RPC error': '2024-06-13 14:59:14.884757'}>
RPC error: [insert_rows], <MilvusException: (code=<bound method _MultiThreadedRendezvous.code of <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:19530: Connection refused"
        debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-06-13T06:59:14.8718024+00:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:19530: Connection refused"}"
>>, message=Retry run out of 75 retry times, message=failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:19530: Connection refused)>, <Time:{'RPC start': '2024-06-13 14:55:39.274645', 'RPC error': '2024-06-13 14:59:14.886764'}>

**Comment by SimFG** [comment]
@Prototypeex When the error `127.0.0.1:19530: Connection refused` appears, you can look at the milvus log and search for `panic` to find the approximate cause and see if it is still `crc check failed`. I think there may be some restrictions on the system for a single file, but this is just my guess.

**Comment by Prototypeex** [comment]
> @Prototypeex When the error `127.0.0.1:19530: Connection refused` appears, you can look at the milvus log and search for `panic` to find the approximate cause and see if it is still `crc check failed`. I think there may be some restrictions on the system for a single file, but this is just my guess.

Sure.I ran another time,found the same CRC check failed.Process juet like the routine above.

![屏幕截图 2024-06-13 152018](https://github.com/milvus-io/milvus/assets/64026922/7c4cb2b8-df80-4297-9c4b-564921e5a27a)

2024-06-13 14:55:35 milvus-standalone  | [2024/06/13 06:55:35.845 +00:00] [INFO] [datacoord/handler.go:302] ["channel seek position set from channel checkpoint meta"] [channel=by-dev-rootcoord-dml_0_450431610976207497v0] [posTs=450431991158669315] [posTime=2024/06/13 06:54:45.023 +00:00]
2024-06-13 14:55:35 milvus-standalone  | [2024/06/13 06:55:35.845 +00:00] [INFO] [datacoord/services.go:834] ["datacoord append channelInfo in GetRecoveryInfo"] [traceID=2cac2d49b87a5748bd981a7f1da94183] [collectionID=450431610976207497] [partitionIDs="[]"] [channel=by-dev-rootcoord-dml_0_450431610976207497v0] ["# of unflushed segments"=1] ["# of flushed segments"=3] ["# of dropped segments"=0] ["# of indexed segments"=0]
2024-06-13 14:55:36 milvus-standalone  | panic: CRC check failed
2024-06-13 14:55:36 milvus-standalone  | 
2024-06-13 14:55:36 milvus-standalone  | goroutine 118988 [running]:
2024-06-13 14:55:36 milvus-standalone  | panic({0x4e25ee0, 0xc0003aa160})
2024-06-13 14:55:36 milvus-standalone  | /usr/local/go/src/runtime/panic.go:987 +0x3bb fp=0xc00210c008 sp=0xc00210bf48 pc=0x1c25f1b
2024-06-13 14:55:36 milvus-standalone  | github.com/apache/arrow/go/v12/parquet/compress.zstdCodec.Decode({}, {0xc013c84000, 0xc0012d84b0?, 0x536580}, {0xc007b36000, 0x94201, 0x9e000})
2024-06-13 14:55:36 milvus-standalone  | /go/pkg/mod/github.com/apache/arrow/go/v12@v12.0.1/parquet/compress/zstd.go:57 +0x73 fp=0xc00210c050 sp=0xc00210c008 pc=0x2ea5c73
2024-06-13 14:55:36 milvus-standalone  | github.com/apache/arrow/go/v12/parquet/compress.(*zstdCodec).Decode(0x5b24a80?, {0xc013c84000?, 0x5b25a20?, 0xc003619810?}, {0xc007b36000?, 0x1c246ff?, 0x10?})
2024-06-13 14:55:36 milvus-standalone  | <autogenerated>:1 +0x4f fp=0xc00210c090 sp=0xc00210c050 pc=0x2ea7eaf

I tried a smaller set.It worked.But how can I build index on whole dataset?300 files:

![屏幕截图 2024-06-13 151915](https://github.com/milvus-io/milvus/assets/64026922/3005bec6-acd2-499b-93bc-5a7485c1f2bb)

**Comment by SimFG** [comment]
I think the standalone mode may not meet your current requirements, you may need to try to deploy the cluster mode. This may be the fastest way to solve your current problem. Of course, redeployment also means that you need to reinsert the existing milvus data.

**Comment by Prototypeex** [comment]
> I think the standalone mode may not meet your current requirements, you may need to try to deploy the cluster mode. This may be the fastest way to solve your current problem. Of course, redeployment also means that you need to reinsert the existing milvus data.

thanks，does this mean that the capacity of standalone is limited? I'll try the cluster.


> crc check fail usually mean persistent disk read the wrong time. you need to check your file system.
> 
> We don't recommend to run milvus on nas or any remote file systems. For distributed cluster, using S3 + local ssd cache. For standalone, make sure you are using cloud disk so no data will lose

milvus runs on win11 docker-desktop.use local ssd to store.I can't scan file system as I'm running os on local disk.so I have to run on virtual machine created in local disk?I don't really think file system has a problem because this is a new pc.

**Comment by xiaofan-luan** [comment]
CRC check failed seems to be a clear signal that file is corrupted
