### ISSUE TITLE
[Feature]: Add new kind support for meta store

### ISSUE THREAD

**Issue by ArenaSu** [milvus-io/milvus#33828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

 The following types of meta store are currently supported by the community: 

- Etcd
- Rocksdb
- Tikv

I want to contribute new kinds.Please help to check which one of the following types is appropriate: 

- Redis
- RoseDB
- LevelDB
- ScyllaDB
- Mysql
- PostgreSQL

### Describe the solution you'd like.

I prefer to  choose RoseDB as it is written by golang. Other option is also ok for me.

**Comment by xiaofan-luan** [comment]
For standalone : use embedded etcd
For smaller cluster : use etcd with 3 nodes
For large cluster : use etcd as service discovery + tikv as distributed meta.

I think add rocksdb support for standalone might be an option. adding sql database is not a option because maintain schema is hard.

**Comment by ArenaSu** [comment]
> For standalone : use embedded etcd For smaller cluster : use etcd with 3 nodes For large cluster : use etcd as service discovery + tikv as distributed meta.
> 
> I think add rocksdb support for standalone might be an option. adding sql database is not a option because maintain schema is hard.

@xiaofan-luan rocksdb is already supported. Could any other kv database be a choose ? Or can add a new MQ(message queue) kind ?

**Comment by xiaofan-luan** [comment]
rocksdb is not supported as meta store yet

**Comment by ArenaSu** [comment]
> rocksdb is not supported as meta store yet

@xiaofan-luan I found internal/kv/rocksdb/rocksdb_kv.go file in milvus master branch. Does this prove that it is supported?
