### ISSUE TITLE
[Bug]: go-sdk can't use upsert.

### ISSUE THREAD

**Issue by Seaiii** [milvus-io/milvus#33835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

There are three fields in the library collection.
I am also passing three fields using the Upsert method.
But it says "the number of fields is less than needed: invalid parameter[expected=3][actual=4]"

**Comment by yanliang567** [comment]
@Seaiii could you please share your collection schema and code snippet of upsert? Also share the versions of milvus and go sdks would be helpful.

/assign @Seaiii 
/unassign

**Comment by Seaiii** [comment]
> @Seaiii could you please share your collection schema and code snippet of upsert? Also share the versions of milvus and go sdks would be helpful.

	embeddings := entity.NewColumnFloatVector("embedding", 1024, [][]float32{embedding})
	contents := entity.NewColumnVarChar("content", []string{action.Content})
	id := entity.NewColumnInt64("id", []int64{action.Id})
	_, err := MilvusClient.milvus.Upsert(context.Background(), collectionName, "", id, embeddings, contents)

embeddings are vectorised values.
content is the varchar content
id is the self-incremented primary key id

milvus version:2.4.1
milvus-sdk-go/v2 v2.4.0


<img width="1009" alt="image" src="https://github.com/milvus-io/milvus/assets/29618214/6ef81cf0-a8e6-4610-a645-afb9147dfd2e">

**Comment by sunby** [comment]
@Seaiii Upsert operations does not support collections with autoID enabled.

**Comment by xiaofan-luan** [comment]
thought @smellthemoon is working on it

**Comment by Seaiii** [comment]
> @Seaiii Upsert operations does not support collections with autoID enabled.

Is this one for sure? In that case I still need to maintain a self-incrementing id myself.

**Comment by smellthemoon** [comment]
> thought @smellthemoon is working on it

pr has hang for a long time. related with https://github.com/milvus-io/milvus/pull/30342, reviewed by @czs007 . I will fix the conflict after review.

**Comment by smellthemoon** [comment]
> Is this one for sure? In that case I still need to maintain a self-incrementing id myself.
> But the error message that milvus replied to me was not due to autoID

yes, I will make the error msg more clear.
/assign

**Comment by Seaiii** [comment]
> autoID

Ok, so when your PR is merged, autoID will be able to use upsert too right?

**Comment by yanliang567** [comment]
> > autoID
> 
> Ok, so when your PR is merged, autoID will be able to use upsert too right?

As you already set autoid for primary key, could you please share more info about why do you still need upsert to keep the same primary key?  The pr will not be merged until it is determined that upsert for autoid is really meaningful to user scenarios. @Seaiii

**Comment by Seaiii** [comment]
> > > autoID

We need the primary key id to self-increment to determine uniqueness. Also we need to update each piece of information. That's all.
If we don't set the primary key id to increment, we need to maintain our own

**Comment by yanliang567** [comment]
> > > > autoID
> 
> We need the primary key id to self-increment to determine uniqueness. Also we need to update each piece of information. That's all. If we don't set the primary key id to increment, we need to maintain our own

so in your case to keep the order of entities, you want the same primary key after doing upsert？is it acceptable for you if we set a new primary key(a new incremented or a bigger id) for the updated entity after doing upsert?

**Comment by Seaiii** [comment]
> so in your case to keep the order of entities, you want the same primary key after doing upsert？is it acceptable for you if we set a new primary key(a new incremented or a bigger id) for the updated entity after doing upsert?

If a new primary key is added cutting larger values is not necessary.
This is because without the upsert interface, we would delete and then create for "updates". It's also a bigger primary key, and the sorting will be messed up.
The effect we want to see is that the primary key remains the same after the update.

**Comment by yanliang567** [comment]
okay, thank you for your feedbacks. We will rethink our design of support for upsert with autoid. 
I'd close this issue as the following up support will be trakced in pr above.

**Comment by xiaofan-luan** [comment]
> action.Id

how did you know action.Id? did you store it some where else?

**Comment by Seaiii** [comment]
> how did you know action.Id? did you store it some where else?

Get all the action.Id for display via the query method.
If I want to modify any of them, I do know what this action.Id is

**Comment by xiaofan-luan** [comment]
@congqixia 
is this still  issue?

**Comment by yanliang567** [comment]
@congqixia @ThreadDao was this fixed
