### ISSUE TITLE
build/deb/build_deb.sh script failed with brz: ERROR: unknown command "dh-make"[Bug]: 

### ISSUE THREAD

**Issue by liorf95** [milvus-io/milvus#33842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu 22.04.2 LTS
- CPU/Memory: 
- GPU: 
- Others: Debian Breezy (brz) 3.2.1
```

### Current Behavior

I am trying to build the Debian package from Milvus source code on Ubuntu 22.04.
However, the build/deb/build_deb.sh script failed with brz: ERROR: unknown command "dh-make".

According to the   Breezy (brz) 3.2.1 changelog:
https://github.com/breezy-team/breezy-debian/blob/master/debian/changelog#L74
Debian Breezy does not support anymore the dh-make command.

How does the current build/deb/build_deb.sh supposed to work?

**Comment by liorf95** [comment]
After downgrading the debian breezer pkg to 2.8.42 (the highest rel which still supports the dh-make command) the build_deb.sh script does work OK however it is interactive since the dh-make command expects the package type and one more confirmation answer.
 The bzr dh-make command does not support the --single --yes flags (or -y -s alternatively).

**Comment by liorf95** [comment]
Any news regarding that issue?
It is very unlikely for that project that the build_deb.sh has not changed at all since its first commit 2 years ago.
I assume you are running some other fixed build Debian script which was not uploaded to the main branch.

**Comment by zwd1208** [comment]
@liorf95  this script has not been verified on Ubuntu 22.04. Can you try it on Ubuntu 20.04?

**Comment by xiaofan-luan** [comment]
@zwd1208 
I thought we also supported 22.04?

**Comment by liorf95** [comment]
> @liorf95 this script has not been verified on Ubuntu 22.04. Can you try it on Ubuntu 20.04?

The same issue also on Ubuntu 20.04.2 LTS

**Comment by xiaofan-luan** [comment]
> > @liorf95 this script has not been verified on Ubuntu 22.04. Can you try it on Ubuntu 20.04?
> 
> The same issue also on Ubuntu 20.04.2 LTS

on ubuntu why don't you simply do make?

**Comment by xiaofan-luan** [comment]
@zwd1208 
please fix  build/deb/build_deb.sh  or remove it.

**Comment by liorf95** [comment]
> > > @liorf95 this script has not been verified on Ubuntu 22.04. Can you try it on Ubuntu 20.04?
> > 
> > 
> > The same issue also on Ubuntu 20.04.2 LTS
> 
> on ubuntu why don't you simply do make?

I do make and its OK  - but afterwards I need to build a debian package installation with it.

**Comment by zwd1208** [comment]
@liorf95  It seems that Ubuntu 22.04 no longer supports dh-make. I suggest you copy the .so and binary files from the Milvus Docker image and then package them using dpkg-deb --build package_name. 
We are trying out this way, and if it works, we will also update the script.

**Comment by liorf95** [comment]
> @liorf95 It seems that Ubuntu 22.04 no longer supports dh-make. I suggest you copy the .so and binary files from the Milvus Docker image and then package them using dpkg-deb --build package_name. We are trying out this way, and if it works, we will also update the script.

You will have to fix also the build/deb/debian/rules accordingly.

**Comment by pingliu** [comment]
we have updated the script. please retry it.

**Comment by liorf95** [comment]
I have made some changes locally in the dh_make script to work interactively and it now builds the Debian package interactively according to our needs.
Thanks.

**Comment by GBrochado** [comment]
Hi, I´m having the same issue trying to create a deb from milvus2.5.5. @liorf95 Can you explain me what did you do to make it working. I already try downgrade brz-debian to 2.8.42 but now it´s stuck in brz dh_make line 
```
root@84fc61fe5ddc:/deb/milvus-deb# bzr dh-make milvus 2.5.5 milvus-2.5.5.tar.gz
Fetching tarball                                                                                                        
Looking for a way to retrieve the upstream tarball
Upstream tarball already exists in build directory, using that
- Apply phase:adding file 0/88 
```

**Comment by liorf95** [comment]
> Hi, I´m having the same issue trying to create a deb from milvus2.5.5. [@liorf95](https://github.com/liorf95) Can you explain me what did you do to make it working. I already try downgrade brz-debian to 2.8.42 but now it´s stuck in brz dh_make line
> 
> ```
> root@84fc61fe5ddc:/deb/milvus-deb# bzr dh-make milvus 2.5.5 milvus-2.5.5.tar.gz
> Fetching tarball                                                                                                        
> Looking for a way to retrieve the upstream tarball
> Upstream tarball already exists in build directory, using that
> - Apply phase:adding file 0/88 
> ```

As far as I recall, they already fixed that issue here:
https://github.com/milvus-io/milvus/commit/21aa23a23e84954f6f298ca91d447a3d301d5283#diff-05ef7782bb9199fe6ce5fa001bdab7583e12be814f84b9f34482aaa32ba9e155

So now you don't need to use any local brz-debian—their new build_deb.sh handles all required dependencies with a docker image.

**Comment by yuchunyu97** [comment]
@pingliu @yanliang567 @xiaofan-luan 
I tried to use the milvusdb/milvus:v2.6.1 image to build the deb package, but it still gave an error. Could you please help me?

The final error log is as follows:

```bash
Setting up libxml-parser-perl:amd64 (2.46-3build1) ...
Setting up brz-debian (2.8.65) ...
Setting up libxml-sax-expat-perl (0.51-1) ...
update-perl-sax-parsers: Registering Perl SAX parser XML::SAX::Expat with priority 50...
update-perl-sax-parsers: Updating overall Perl SAX parser modules info file...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
debconf: falling back to frontend: Readline
Replacing config file /etc/perl/XML/SAX/ParserDetails.ini with new version
Processing triggers for libc-bin (2.35-0ubuntu3.8) ...
Processing triggers for sgml-base (1.30) ...
Setting up docutils-common (0.17.1+dfsg-2) ...
Processing triggers for sgml-base (1.30) ...
Setting up python3-docutils (0.17.1+dfsg-2) ...
brz: ERROR: unknown command "dh-make"
sed: can't read milvus/debian/changelog: No such file or directory
sed: can't read milvus/debian/changelog: No such file or directory
sed: can't read milvus/debian/README.Debian: No such file or directory
sed: can't read milvus/debian/README.source: No such file or directory
cp: target 'milvus/debian/' is not a directory
build_deb.sh: line 63: cd: milvus: No such file or directory
brz: ERROR: Not a branch: "/deb/milvus-deb/debian/source/format/".
brz: ERROR: Not a branch: "/deb/milvus-deb/".
dpkg-buildpackage: error: cannot open file debian/changelog: No such file or directory
```

**Comment by yuchunyu97** [comment]
Is it possible to provide a built deb package on the v2.6.1 Release page?

**Comment by yanliang567** [comment]
> Is it possible to provide a built deb package on the v2.6.1 Release page?

@Linkwei please help

/assign @Linkwei

**Comment by xiaofan-luan** [comment]
it seems the error is don't install dh-make.

could you try
sudo apt install -y dh-make

and see what error you get then?
