### ISSUE TITLE
After  build dockerfile and docker run this image,  but when use example.py, get  an  error

### ISSUE THREAD

**Issue by leidaxia** [milvus-io/milvus#3385]
I use this [dockerfile](https://github.com/milvus-io/milvus/blob/b6090b03ab008e9e5b76ba1501d35f2fe9197c1f/docker/deploy/cpu/ubuntu18.04/Dockerfile) , 
and build a  image sucessfully.
![image](https://user-images.githubusercontent.com/20982126/90861367-345ca680-e3be-11ea-9be5-9cfb1115d91e.png)
But After docker run this image,  I use this example.py,  I get the error
![image](https://user-images.githubusercontent.com/20982126/90861513-6b32bc80-e3be-11ea-8b58-2a10dea87743.png)
error
![image](https://user-images.githubusercontent.com/20982126/90861537-784fab80-e3be-11ea-839e-439a157ba1cd.png)

**Comment by BossZou** [comment]
@leidaxia, which milvus version and sdk version you are using?
