### ISSUE TITLE
[Enhancement]:   refactor string/json load memory mode and search mode

### ISSUE THREAD

**Issue by zhagnlu** [milvus-io/milvus#33874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

for now, string/json load occupy a lot of memory in cache,  almost 16bytes/row/column for string , and 48 bytes/row/column for json. To avoid these memory cost. refactor memory load mode and search mode in engine

**Comment by xiaofan-luan** [comment]
keep it ~

**Comment by xiaofan-luan** [comment]
we need to change Json into Bson to get better performance
