### ISSUE TITLE
[Bug]: Incorrect filter query results for scalar data

### ISSUE THREAD

**Issue by thangTang** [milvus-io/milvus#33877]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.1
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): kafka   
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.4.0
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I query with expr: `name == "tutly.skkt.xeaa_uaetw_qizjp_hblds"`, the result is : `{'id': 282337, 'vector': [0.06682958, 0.5775435, 0.12858126, 0.42314735, 0.16689864], 'name': 'dvkw.rru.cug_wdbl_xpm_bqu'}`

### Expected Behavior

The result should be: `{'id': 6, 'vector': [0.23271117, 0.6470319, 0.07692471, 0.2980429, 0.6095423], 'name': 'tutly.skkt.xeaa_uaetw_qizjp_hblds'}`

### Steps To Reproduce

1. Constructing test data

```python
from pymilvus import Collection, connections, utility, MilvusClient, DataType
import numpy as np
import random
import string

def generate_random_name():
    parts = [''.join(random.choices(string.ascii_lowercase, k=random.randint(3, 5))) for _ in range(6)]
    return f"{parts[0]}.{parts[1]}.{parts[2]}_{parts[3]}_{parts[4]}_{parts[5]}"

# connections.connect("default", host="YOURHOST", port="19530",user='root',password='YOURPSWD')
client = MilvusClient(
    uri="YOURURI",
    user='root',
    password='YOURPSWD'
)

schema = MilvusClient.create_schema()
schema.add_field(field_name="id", datatype=DataType.INT64, is_primary=True)
schema.add_field(field_name="vector", datatype=DataType.FLOAT_VECTOR, dim=5)
schema.add_field(field_name="name", datatype=DataType.VARCHAR, max_length=255)

collection_name = "test_collection2"
client.create_collection(
    collection_name=collection_name,
    schema=schema
)
print("Create collection done.")

index_params = MilvusClient.prepare_index_params()
index_params.add_index(
    field_name="vector", 
    metric_type="L2"
)
index_params.add_index(
    field_name="name"
)
client.create_index(
    collection_name=collection_name,
    index_params=index_params
)
print("Create index done.")

num_entities = 1000000
vectors = [np.random.rand(5).astype(np.float32).tolist() for _ in range(num_entities)]
names = [generate_random_name() for _ in range(num_entities)]

data = [
    {"id": i, "vector": vec, "name": name}
    for i, (vec, name) in enumerate(zip(vectors, names))
]
# print(data)

res = client.insert(
    collection_name=collection_name,
    data=data
)
print("Insert data done.")


connections.connect("default", host="YOURHOST", port="19530",user='root',password='YOURPSWD')

collection = Collection(name=collection_name)
collection.load()
print("Loaded collection.")

expr0 = "id > -9223372036854775807"
id_result = collection.query(expr=expr0,output_fields=["*"],limit=13)
print("Query Result:", id_result)
```

2. 13 pieces of data can be obtained in output:
>Query Result: [{'id': 0, 'vector': [0.935742, 0.91852725, 0.19962192, 0.23454715, 0.8584049], 'name': 'mctxn.mhspb.izym_vxtd_efw_dozam'}, {'id': 1, 'vector': [0.6215701, 0.3533179, 0.44713816, 0.4054737, 0.7761003], 'name': 'hhyg.zdtds.gcwj_ejbiw_kkyvp_kmmgq'}, {'id': 2, 'vector': [0.103285514, 0.92670584, 0.9356521, 0.8440695, 0.08031804], 'name': 'krudt.weht.jzkcy_cbx_gdvhn_jkwgl'}, {'id': 3, 'vector': [0.68555105, 0.010004462, 0.75924337, 0.27405128, 0.050466083], 'name': 'zpf.ohs.nmq_brj_badjj_pnv'}, {'id': 4, 'vector': [0.64018893, 0.63541, 0.3744408, 0.65583557, 0.30072436], 'name': 'gjuis.ceja.teuk_hfxvk_ggws_tsuf'}, {'id': 5, 'vector': [0.7517409, 0.7736187, 0.021146033, 0.22046724, 0.07318554], 'name': 'epz.xfus.baod_xitjx_qzgr_jex'}, {'id': 6, 'vector': [0.23271117, 0.6470319, 0.07692471, 0.2980429, 0.6095423], 'name': 'tutly.skkt.xeaa_uaetw_qizjp_hblds'}, {'id': 7, 'vector': [0.7220278, 0.66486704, 0.53876555, 0.568594, 0.6043031], 'name': 'jpw.enk.mdcmu_pbi_zgmzu_rmqc'}, {'id': 8, 'vector': [0.5418692, 0.24573624, 0.2207807, 0.41422477, 0.3970441], 'name': 'klj.ykt.enbp_tdaf_qous_kwfb'}, {'id': 9, 'vector': [0.1023764, 0.27632314, 0.77322847, 0.67189825, 0.23417017], 'name': 'hfvis.nif.njmu_bka_inkl_huff'}, {'id': 10, 'vector': [0.23267293, 0.08281852, 0.19895878, 0.6237968, 0.27750683], 'name': 'mwbwf.zgnud.jck_hpoa_iphd_dydnh'}, {'id': 11, 'vector': [0.67031515, 0.9655982, 0.29312837, 0.87854815, 0.13017249], 'name': 'kfsdw.ullzp.wwoo_ksdw_pyl_kvs'}, {'id': 12, 'vector': [0.37787765, 0.48849213, 0.054219007, 0.8309143, 0.688605], 'name': 'zme.iqhkq.koa_wog_vlew_zmla'}]

3. Choose anyone and query

```python
from pymilvus import Collection, connections, utility, MilvusClient, DataType

connections.connect("default", host="YOURHOST", port="19530",user='root',password='YOURPSWD')

collection_name = "test_collection2"
collection = Collection(name=collection_name)

name = "tutly.skkt.xeaa_uaetw_qizjp_hblds"

expr = f'name == "{name}"'

name_result = collection.query(expr=expr,output_fields=["*"],limit=100)

if name_result and name == name_result[0]["name"]:
    print("The results match:")
    print("ID Query Result:", name)
    print("Name Query Result:", name_result)
else:
    print("The results do not match:")
    print("ID Query Result:", name)
    print("Name Query Result:", name_result)
```

4. Unexpected result:
>The results do not match:
>ID Query Result: tutly.skkt.xeaa_uaetw_qizjp_hblds
>Name Query Result: [{'id': 282337, 'vector': [0.06682958, 0.5775435, 0.12858126, 0.42314735, 0.16689864], 'name': 'dvkw.rru.cug_wdbl_xpm_bqu'}]

### Anything else?

1. The amount of constructed data cannot be too small, otherwise it cannot be reproduced
2. The script for constructing data and "getting the name as the query condition", and the query script, cannot be put into a same script, otherwise the issue may not be reproduced.
3. The result will be **_as expected_** if **_drop_** the scalar index.

**Comment by xiaofan-luan** [comment]
what index you are using?

**Comment by xiaofan-luan** [comment]
is using 2.4.3, please try v2.4.4 see i the bug as been fixed.
see bug https://github.com/milvus-io/milvus/pull/32858

**Comment by thangTang** [comment]
> what index you are using?

I use AUTO INDEX and do not specify the index type

**Comment by thangTang** [comment]
> is using 2.4.3, please try v2.4.4 see i the bug as been fixed. see bug #32858

Thank you will give a go with the new version.

**Comment by yanliang567** [comment]
/assign @thangTang 
please keep us posted. thanks.

/unassign

**Comment by thangTang** [comment]
> /assign @thangTang please keep us posted. thanks.
> 
> /unassign

Tested on 2.4.5 and confirmed it is fixed. Close this issue. CC @xiaofan-luan with many tks.
