### ISSUE TITLE
[Bug]: cpu-e2e not work for branch 2.3

### ISSUE THREAD

**Issue by xige-16** [milvus-io/milvus#33897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

e2e always failed.
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-33725/6/pipeline

**Comment by xige-16** [comment]
@samhuang-z

**Comment by yanliang567** [comment]
hi @xige-16, thanks for the issues. 

/assign @samhuang-z 
/unassign

**Comment by xige-16** [comment]
link pr:https://github.com/milvus-io/milvus/pull/33725
