### ISSUE TITLE
[Bug]: Querynode memory usage is very unbalanced, some report memory quota exceeded.

### ISSUE THREAD

**Issue by tianshihan818** [milvus-io/milvus#33913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20240612-8cb35059-amd64
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Behaviour: concurrent batch insert. 4000 entites/batch, 30 concurrency.
The workernodes deployment values:
```yaml
queryNode:
  replicas: 16
  resources: 
    limits:
      cpu: 16
      memory: 128Gi

dataNode:
  replicas: 4
  resources: 
    limits:
      cpu: 2
      memory: 8Gi

indexNode:
  replicas: 4
  resources: 
    limits:
      cpu: 8
      memory: 16Gi
```
The collection values:
```python
fields = [
    FieldSchema(name="id", dtype=DataType.VARCHAR, is_primary=True, auto_id=True, max_length=100),
    FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=768)
]
...
collection = Collection(name, schema, consistency_level="Strong", num_shards=4)
```

What happens:
After writed 1.11 billion entites, python SDK insert API reported error and exited.
![image](https://github.com/milvus-io/milvus/assets/154961771/652394bc-e967-4f0d-a2cd-80e97cedd59e)

The logs of rootcoord shows:
<img width="524" alt="企业微信截图_17185943963620" src="https://github.com/milvus-io/milvus/assets/154961771/d00b833c-b96a-4698-8259-efae7a0d22e7">

Checked the metrics, find one querynode memory usage is much higher than others, and its memory usage was increasing suddenly from a moment. Here are the details:

- The normal usage before:
<img width="400" alt="企业微信截图_17185942174714" src="https://github.com/milvus-io/milvus/assets/154961771/f997e826-570e-4fdb-9ab0-d8dfafc097cb">

- Later one querynode memory usage is very high:
<img width="456" alt="企业微信截图_17185942542347" src="https://github.com/milvus-io/milvus/assets/154961771/863745ee-4d8c-4f61-a630-5de14fd941be">

Related metrics:
- Segment Loaded Num
<img width="1246" alt="企业微信截图_17186106389543" src="https://github.com/milvus-io/milvus/assets/154961771/fec47f31-dbee-4efc-bead-d19e0cce2879">

- Segment Num
<img width="414" alt="企业微信截图_1718610629392" src="https://github.com/milvus-io/milvus/assets/154961771/17190e9e-b19b-4464-abb6-a9d3c328ced9">

- Queryable Entity Num
<img width="1237" alt="企业微信截图_1718610634152" src="https://github.com/milvus-io/milvus/assets/154961771/bee9ab3f-3af7-4f30-801e-f57ee813347d">

- Memory
<img width="1248" alt="企业微信截图_1718610627278" src="https://github.com/milvus-io/milvus/assets/154961771/7b0ae870-61a4-45f0-9d31-5275c15d087c">

### Expected Behavior

Insert normally, support large scale data and high insert throughput

**Comment by tianshihan818** [comment]
According to these issues:
https://github.com/milvus-io/milvus/issues/32714
https://github.com/milvus-io/milvus/issues/32894

It seems that this scene is caused by the high writing throughput, thus some datanodes became unhealthy, so there will be too much growing segments in some querynode. (But why the already sealed segment loaded num is decreased? I am not very clearly about what happened inside).

I tried to re-deploy the querynodes and re-load the collection, the memory usage becomes back to normal:
<img width="566" alt="企业微信截图_1718605265848" src="https://github.com/milvus-io/milvus/assets/154961771/bae4069c-33b2-483e-8322-887038e052ee">

Hope there will be some helpful info.
- Should I scale up the datanodes?
- And how to control the writing rate or concurrency for large scale data scene?

**Comment by yanliang567** [comment]
@tianshihan818 thank you for the issue and updates. It seems that something stuck in that querynode, but we cannot tell without milvus logs. Could you please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation? 
BTW, which index type are you running?

/assign @tianshihan818

**Comment by tianshihan818** [comment]
@yanliang567 Thanks! Here are the logs:
[milvus-log.tar.gz](https://github.com/user-attachments/files/15879974/milvus-log.tar.gz)

And I use IVF_SQ8 index type:
![image](https://github.com/milvus-io/milvus/assets/154961771/95299c6a-6bca-4bda-bce3-ab2b573362f0)

**Comment by yanliang567** [comment]
/assign @congqixia 
please help to take a look.

**Comment by tianshihan818** [comment]
Additional info:
The initial logs are lost, so I reproduce this test(concurrent insert), and get the above logs, i.e. 
[milvus-log.tar.gz](https://github.com/user-attachments/files/15882184/milvus-log.tar.gz)

This time the insert API first report error at June 17th 22:50: `pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=message send timeout: TimeoutError)>` （The time on the machine nodes is set to be 8 hours later, so in logs should be around 14:50.)
And I checked the metrics and pods list during this test period.
- Pod list
<img width="459" alt="企业微信截图_17186918952022" src="https://github.com/milvus-io/milvus/assets/154961771/437c2dcd-6bb8-4c84-a502-cef00d8ac45b">

- Memory
<img width="1269" alt="企业微信截图_17186908729771" src="https://github.com/milvus-io/milvus/assets/154961771/6e3363d8-cef2-4e2b-bd83-5d7f437fc2c7">

- Segement Loaded Num
<img width="1240" alt="企业微信截图_17186912067480" src="https://github.com/milvus-io/milvus/assets/154961771/e3b0b4cc-6466-475c-a83d-bf41e3b0b0a3">

- Queryable Entity Num
<img width="1241" alt="企业微信截图_17186912832872" src="https://github.com/milvus-io/milvus/assets/154961771/c617e85b-f948-4fdf-be91-d7ba083df26c">

- Goroutines Total
<img width="1248" alt="企业微信截图_17186922195118" src="https://github.com/milvus-io/milvus/assets/154961771/2145dcb6-3693-4fdf-9bd1-882796402e04">

- Goroutines
<img width="1248" alt="企业微信截图_17186923342838" src="https://github.com/milvus-io/milvus/assets/154961771/743f780b-ad7d-4700-bf78-ceb71bc3eef8">

- CPU
<img width="417" alt="企业微信截图_17186924613424" src="https://github.com/milvus-io/milvus/assets/154961771/a3242aa9-a8ff-4899-84b3-867e96b4a9fd">

- OS Threads
<img width="1248" alt="企业微信截图_17186925929468" src="https://github.com/milvus-io/milvus/assets/154961771/e1b07855-9a76-442d-9109-54ad6689982e">

- GC Max duration seconds
<img width="1252" alt="企业微信截图_17186926669084" src="https://github.com/milvus-io/milvus/assets/154961771/942af394-07b0-4f8d-8a7d-aca5147cd0da">

- Other metrics
<img width="1249" alt="企业微信截图_17186945946792" src="https://github.com/milvus-io/milvus/assets/154961771/4546b0f9-2829-4e4a-8d81-0bf5c7faf4ad">
<img width="1251" alt="企业微信截图_17186947094234" src="https://github.com/milvus-io/milvus/assets/154961771/4649e2de-bd62-43f1-bc94-5d54fd3bf188">

**Comment by tianshihan818** [comment]
And I continue inserting, the memory usage of querynode `miltest-milvus-querynode-5559dc65d-knhn7` is increasing, when it reached the quota water level, will report the same error as before: `pymilvus.exceptions.MilvusException: <MilvusException: (code=9, message=quota exceeded[reason=memory quota exceeded, please allocate more resources])>`

<img width="606" alt="企业微信截图_17186966014880" src="https://github.com/milvus-io/milvus/assets/154961771/a0f67c93-a288-4665-a248-52b9ffe2ac11">

And the logs of this time are here: 
[milvus-log-new.tar.gz](https://github.com/user-attachments/files/15882223/milvus-log-new.tar.gz)

**Comment by xiaofan-luan** [comment]
you can try to increase shard number.

In our design, best practice is to have 100 - 200 million data for each shard.

On your case, you have roughly 1B data, we would recoomend to use 8 shards. 

The reason you see one query nodes cpu very high is because it is the shard delegator. If index build can not catch up, data may accumulate. also since there is only delegator forward request, you may see it becomes the bottleneck on heavy search.

If you can use pprof to check why the memory is high it could be also helpful

**Comment by congqixia** [comment]
@tianshihan818 
The segment is still been loaded into the delegator querynode, which is not by design
could you please provided a birdwatcher backup and output for `show segment-loaded-grpc` command?
https://github.com/milvus-io/birdwatcher/releases/tag/v1.0.4

**Comment by tianshihan818** [comment]
Thank for your reply! @xiaofan-luan @congqixia 

I use birdwatcher to get pprof heap files: 
[bw_pprof_heap.240619-045745.tar.gz](https://github.com/user-attachments/files/15895672/bw_pprof_heap.240619-045745.tar.gz)

And the segment-loaded-grpc list results are in this file: 
[show_segment_loaded_grpc.log](https://github.com/user-attachments/files/15895693/show_segment_loaded_grpc.log)

**Comment by congqixia** [comment]
@tianshihan818 thanks for the quick reply, could you please provided the `backup` file as well?

**Comment by tianshihan818** [comment]
@congqixia The etcd backup is here: 
[bw_etcd_ALL.240619-060804.bak.gz](https://github.com/user-attachments/files/15896141/bw_etcd_ALL.240619-060804.bak.gz)

**Comment by XuanYang-cn** [comment]
DataNode painiked on konwn bugs, should be fixed by #33829
![image](https://github.com/milvus-io/milvus/assets/51370125/52c7c2ee-2295-4241-b5e6-c435b88f1329)

**Comment by tianshihan818** [comment]
@xiaofan-luan Hello! Thanks for sharing the tech detail. I verified in the logs, the "delegator" is indeed on the abnormal querynode. Is this "delegator" responsiable for forwarding the loading or searching request and gathering the search results?
So under the concurrent insert case, once called `collection.load()`, the querynode will load data later automatically, as my collection's consistency_level is set to be "Strong", if the index build process (use IVF_SQ8 index type in this test, ideally the memory usage of the index files will be around 30% of the raw data size) don't catch up the insert speed, the querynode will load the raw data instead of the index files into the memory, thus causing the high memory usage, right?
I am still not very clearly on these things:
- Why only the "delegator" querynode itself bear the load pressure in this case?
- Will it better for "load all data after insert all data"?

**Comment by xiaofan-luan** [comment]
delegator hold all the growing segment data. when segment is sealed and index is built, all other node can take the work .

@XuanYang-cn upgrade to 2.4.5 could solve the problem? do we need special fix for this segment not found error?

**Comment by tianshihan818** [comment]
Hello! Besides the shard number configuration and the datanode known bugs, is there any new findings on this issue recently?

I found the milvus new version v2.4.5 has fixed some bugs about memory usage, and this fix seems to be related,

Delayed loading Bloom filters in delegator to prevent them from being loaded repeatedly when the worker has no more memory (https://github.com/milvus-io/milvus/pull/33650).

Could you share some findings or suggestions? @congqixia Thank you a lot!
