### ISSUE TITLE
[Bug]: CVEs of Milvus base image

### ISSUE THREAD

**Issue by weiZhenkun** [milvus-io/milvus#33945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: Milvus 2.4x & milvus master
```

### Current Behavior

FIX CVEs of milvus base image: LOW: 32,  MEDIUM: 50, **Total FIX: 82** for 2.4.x
![image](https://github.com/milvus-io/milvus/assets/27683687/020fbb73-9a1f-42cb-8224-a595179b3533)
![image](https://github.com/milvus-io/milvus/assets/27683687/fef403a5-c658-4ee6-baf4-ace3a0387799)

FIX CVEs of milvus base image: MEDIUM: 8, **Total FIX: 8** for master branch
![image](https://github.com/milvus-io/milvus/assets/27683687/71708028-265e-4f20-8732-56b7e76864fc)

**Comment by weiZhenkun** [comment]
https://github.com/milvus-io/milvus/pull/33927

**Comment by yanliang567** [comment]
/assign @czs007 
please help to review the issues
/unassign
