### ISSUE TITLE
[Bug]: "core/backup_impl_create_backup.go:80","message":"fail to get milvus version","error":"rpc error: code = Unknown desc = auth check failure, please check username and password are correct","stack":"github.com/zilliztech/milvus-backup/core.(*BackupContext).CreateBackup\ rpc error: code = Unknown desc = auth check failure, please check username and password are correct

### ISSUE THREAD

**Issue by 4-Struggle** [milvus-io/milvus#33974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

./milvus-backup create -n wpx_07

### Steps To Reproduce

```markdown
When common. Security. AuthorizationEnabled = false, I can be successful backup, restore data, but when I set to true, he will be submitted to the corresponding error.
```

### Milvus Log

"caller":"core/backup_impl_create_backup.go:62","message":"backup already exist with the name: wpx_07","stack":"github.com/zilliztech/milvus-backup/core.(*BackupContext).CreateBackup\n\t/home/runner/work/milvus-backup/milvus-backup/core/backup_impl_create_backup.go:62\ngithub.com/zilliztech/milvus-backup/cmd.glob..func2\n\t/home/runner/work/milvus-backup/milvus-backup/cmd/create.go:60\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918\ngithub.com/zilliztech/milvus-backup/cmd.Execute\n\t/home/runner/work/milvus-backup/milvus-backup/cmd/root.go:28\nmain.main\n\t/home/runner/work/milvus-backup/milvus-backup/main.go:24\nruntime.main\n\t/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/proc.go:250"}
backup already exist with the name: wpx_07

**Comment by xiaofan-luan** [comment]
auth check failure, please check username and password are correct  ->  you need to offer correct username password?
