### ISSUE TITLE
[Bug]: Indexed_rows almost remains unchanged, when one day after creating IVF_PQ index

### ISSUE THREAD

**Issue by JeremyLee-lrj** [milvus-io/milvus#33984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4.4
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 1 CPU, 12 cores per CPU, 2 threads per core / 124G
- GPU: 
- Others:
```

### Current Behavior

I attempted create IVF_PQ index on a dataset which contains 1 billion pieces of data(256 dimension, float).
A day later, the creating_index's program is still running, and I use utility.index_building_progress() to check how many data is indexed, and I found that only about 3% (3 million pieces of data) were indexed successfully.

### Milvus Log

Because of the size of milvus_log.txt is too big(about 1.9GB), I have to put it in Baidu Netdisk.

**Comment by xiaofan-luan** [comment]
How many index node you are using? and what is the hardware config?

For IVF PQ, latest intel cpu can build one segmnt(1M) in less than i minutes. 

where is the link of your baidu net disk?

**Comment by JeremyLee-lrj** [comment]
Milvus_log.txt link：https://pan.baidu.com/s/1nXvr3DMLe8_2A_Q-F7E6iw?pwd=x042 
password：x042

**Comment by xiaofan-luan** [comment]
are u using intel cpu?

**Comment by xiaofan-luan** [comment]
2. did you try IVFSQ8? SQ should be much faster than PQ. 
3. can you add more index node and try

**Comment by xiaocai2333** [comment]
@JeremyLee-lrj can you send the log to my email: `cai.zhang@zilliz.com`?

**Comment by JeremyLee-lrj** [comment]
> are u using intel cpu?

Yes
![image](https://github.com/milvus-io/milvus/assets/101927649/d66aa7d4-4db7-42f2-a5af-ad0fa71d5d79)

**Comment by JeremyLee-lrj** [comment]
> 2. did you try IVFSQ8? SQ should be much faster than PQ.
> 3. can you add more index node and try

2. No, I haven't try IVFSQ8, thanks for sharing it, I think I will try IVF_SQ later.
3. I'm sorry that I only have one server right now, So I think I can't add more index node.

**Comment by JeremyLee-lrj** [comment]
> @JeremyLee-lrj can you send the log to my email: `cai.zhang@zilliz.com`?

Sure, I'm sending it right now, but it will take some time to upload the milvus_log.txt to mail.

**Comment by xiaocai2333** [comment]
@JeremyLee-lrj Sorry for late reply.
IVF_PQ is inherently a slow index to build. From the logs you provided, I didn't find any abnormal situations; everything is proceeding normally. I also tested locally, and it indeed takes over 10 minutes to build an index for 200000 data points with 256 dimensions. If you want to build an index quickly, I recommend using HNSW, which also has excellent recall performance.

**Comment by xiaofan-luan** [comment]
IVF_SQ8 could be much faster as well.

**Comment by JeremyLee-lrj** [comment]
> @JeremyLee-lrj Sorry for late reply. IVF_PQ is inherently a slow index to build. From the logs you provided, I didn't find any abnormal situations; everything is proceeding normally. I also tested locally, and it indeed takes over 10 minutes to build an index for 200000 data points with 256 dimensions. If you want to build an index quickly, I recommend using HNSW, which also has excellent recall performance.

It's OK, I'm fine with the reply time, and I appreciate your help very much!
Actually, I use IVF_PQ because I want smaller index size, but I didn't realize the building time is so long. Thanks for your recommendation!

**Comment by JeremyLee-lrj** [comment]
> IVF_SQ8 could be much faster as well.

OK, I got it, appreciate it!

**Comment by yanliang567** [comment]
i'd close this issue, and please feel free to file an new one if any other issues
