### ISSUE TITLE
GetCollectionStatsResponse in Java-SDK is needed

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#3402]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
The response of `collection stats` should not in message, as `GetCollectionInfoResponse` designed, `GetCollectionStatsResponse` in Java-SDK is needed

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by sahuang** [comment]
In addition, example program provides usage:

`Response getCollectionStatsResponse = client.getCollectionStats(collectionName);`
`if (getCollectionStatsResponse.ok()) {`
 `    // Collection info is sent back with JSON type string`
`    String jsonString = getCollectionStatsResponse.getMessage();`
`    System.out.format("Collection Stats: %s\n", jsonString);`
`}`

Might be ok to stay as it is at the moment.
