### ISSUE TITLE
[Bug]: Standalone oomkilled after upgrading mater branch image

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#34055]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: e83ecd50 -> master-20240621-4e414fb7-amd64
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):   rocksmq  
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. standalone pod `zong-go-master-milvus-standalone-5cc75d965b-t46jr` with resource config
```
    Limits:
      cpu:     8
      memory:  16Gi
    Requests:
      cpu:      5
      memory:   9Gi
```
2. upgrade image to `master-20240621-4e414fb7-amd64` and pod oomkilled
3. upgrade standalone pod memory limit to 32Gi and pod is running
 - pod memory usage
 
![image](https://github.com/milvus-io/milvus/assets/27288593/b2e31de2-b8d2-4fc7-93c4-20a42fbb1213)
 - [metrics of zong-go-master](https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=P1809F7CD0C75ACF3&var-cluster=&var-namespace=qa-milvus&var-instance=zong-go-master&var-collection=All&var-app_name=milvus&from=1718933800017&to=1718955256971)

### Milvus Log

pods:
```
zong-go-master-etcd-0                                             1/1     Running                           0              3d      10.104.25.21    4am-node30   <none>           <none>
zong-go-master-milvus-standalone-6cdbf578d-phtls                  1/1     Running                           0              10m     10.104.19.7     4am-node28   <none>           <none>
zong-go-master-minio-55956b966c-s48rt                             1/1     Running                           0              3d      10.104.34.72    4am-node37   <none>           <none>
```

**Comment by yanliang567** [comment]
there are only 20 collections with totally 15k vectors loaded before upgrading, btw

**Comment by xiaofan-luan** [comment]
So we have 20collections with only 15K vectors each collection and 16GB standalone get OOM?

**Comment by sunby** [comment]
same issue: [[Bug]: Upgrading from v2.3.15 to master-20240625-506a9152-amd64 due to DN and QN crash and one index](https://github.com/milvus-io/milvus/issues/34176#issuecomment-2190474237)
