### ISSUE TITLE
[Bug]: Check point meta is empty when backup collection

### ISSUE THREAD

**Issue by xige-16** [milvus-io/milvus#34061]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. run command: ./milvus-backup create -n my_back -c colA -d dbA --config  
2. channel_cp_meta.json was generated
3.  open channel_cp_meta.json file, meta is empty, like {"colA": []}

**Comment by xige-16** [comment]
The master branch works normally.

**Comment by xige-16** [comment]
releated： https://github.com/milvus-io/milvus/issues/32609

**Comment by yanliang567** [comment]
@xige-16 please retry on milvus 2.4.5 if it blocks you
