### ISSUE TITLE
[Enhancement]: Avoid assign too much segment/channels to new querynode

### ISSUE THREAD

**Issue by weiliu1031** [milvus-io/milvus#34095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

When a new query node comes online, the segment_checker, channel_checker, and balance_checker simultaneously attempt to allocate segments to it. If this occurs during the execution of a load task and the distribution of the new query node hasn't been updated, the query coordinator may mistakenly view the new query node as empty. As a result, it assigns segments or channels to it, potentially overloading the new query node with more segments or channels than expected.

**Comment by xiaofan-luan** [comment]
for each balance step, we should set a limit(see only 5 segments can be balanced at the same time)
