### ISSUE TITLE
[Bug]: create collection through pymilvus, no error raised but collection list is still empty

### ISSUE THREAD

**Issue by zydmtaichi** [milvus-io/milvus#34134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4.1
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):2.4.4
- OS(Ubuntu or CentOS): windows
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I connect to milvus db using python SDK ,then create db and collection, the db creation is good but collection can't be created.
my example is pasted below:
```
from pymilvus import connections, MilvusClient, db, FieldSchema, DataType, CollectionSchema, Collection

conn = connections.connect(host="127.0.0.1", port=19530)

#newdatabase = db.create_database("llamatest")

client = MilvusClient(uri="http://127.0.0.1:19530")

db.using_database("llamatest")

res = db.list_database()

print(res)

my_id = FieldSchema(name="id", dtype=DataType.INT64, is_primary=True, description="this is id")
my_vec = FieldSchema(name="vec", dtype=DataType.FLOAT_VECTOR, dim=128, description="embed vec")

fields = [my_id, my_vec]

schema = CollectionSchema(fields=fields, auto_id=False, enable_dynamic_id=True, description="test collection")

my_collection = Collection(name="coll_test", schema=schema, using="default")

res2 = client.list_collections()

print(res2)
```

This example raise nothing,but the `res2` which represents the collections existed is still printed as a empty list.

**Comment by xiaofan-luan** [comment]
@zydmtaichi 
did you enabled rbac? did you current role has access to database llamatest?

**Comment by yanliang567** [comment]
@zydmtaichi checking the code above, you are using 2 connections: conn and client. The working database of conn is llamatest as you called using_database, while the working database of client is default. So try to call utility.list_collection(). BTW, I think you don't need the client connection at all. 
/assign @zydmtaichi 
/unassign

**Comment by xiaofan-luan** [comment]
you seem to mix use two style of apis

when you create collection 
my_collection = Collection(name="coll_test", schema=schema, using="default")

you actaully create a colleciton under default databse, not the database you created.

this is the right API

client.create_collection(
    collection_name="customized_setup_1",
    schema=schema,
    index_params=index_params
)


https://milvus.io/docs/manage-collections.md

**Comment by zydmtaichi** [comment]
> @zydmtaichi checking the code above, you are using 2 connections: conn and client. The working database of conn is llamatest as you called using_database, while the working database of client is default. So try to call utility.list_collection(). BTW, I think you don't need the client connection at all. /assign @zydmtaichi /unassign

yeah,your point is correct,i switch to utility and it shows the collection name as i want

**Comment by zydmtaichi** [comment]
> you seem to mix use two style of apis
> 
> when you create collection my_collection = Collection(name="coll_test", schema=schema, using="default")
> 
> you actaully create a colleciton under default databse, not the database you created.
> 
> this is the right API
> 
> client.create_collection( collection_name="customized_setup_1", schema=schema, index_params=index_params )
> 
> https://milvus.io/docs/manage-collections.md

"default" is a aliase of connection(per doc),i just want to create a collection under the db "llamatest", but `using="llamatest"` is not worked, what should i do

**Comment by yanliang567** [comment]
MilvusClient and utility are two different styles of python sdk for milvus. if you want to use MilvusClient, you can call `client.using_database(db_name= llamatest)
client.list_collections()`

**Comment by yanliang567** [comment]
more info about MilvusClient: https://milvus.io/api-reference/pymilvus/v2.4.x/MilvusClient/Client/MilvusClient.md
