### ISSUE TITLE
[Enhancement]: Support unset properties when using  attu

### ISSUE THREAD

**Issue by xige-16** [milvus-io/milvus#34151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

1. we can use pymilvus.collection.set_properties or attu to set collection's properties, Then we can only modify these properties manually, but you cannot cancel these properties and use the system default values.
2.  a warning log issue: https://github.com/zilliztech/attu/issues/547

So when set property value == "", the behavior can be changed to cancel the manual setting of properties.

**Comment by shanghaikid** [comment]
how to unset them via sdk?

**Comment by xige-16** [comment]
> how to unset them via sdk?

Didn't see any corresponding python function

**Comment by xige-16** [comment]
Is this pr OK?

**Comment by jaime0815** [comment]
It may conflict with some configurations that the value can be configured to "".   we can support add, remove, and modify actions to enhance the alter function. @xige-16

**Comment by xige-16** [comment]
> we can support add and remove

If some configurations need to be set to "", then setting the default value of these configurations to "" can achieve the same effect. Anyway, waiting for your updates. @jaime0815

**Comment by jaime0815** [comment]
It has different effects: @xige-16 

1. Setting the property value to "" by default removes this property during the alter operation, which is treated as invalid.

2. Setting the property value to "" may also be useful for this property, but this deeply depends on the implementation.

**Comment by xiaofan-luan** [comment]
it's better to support a fucntion to remove.

But it seems to fine to keep "" as not set?

**Comment by xiaofan-luan** [comment]
@xige-16 
i think it 's fine to rebase and merge it
