### ISSUE TITLE
[Bug]: When performing a search with Milvus 2.4.5, the Milvus Docker container stops, resulting in an inability to connect to the Milvus server.

### ISSUE THREAD

**Issue by BushJiang** [milvus-io/milvus#34173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4.5
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):2.4.3
- OS(Ubuntu or CentOS): macOS 14.2.1 
- CPU/Memory: 8.16G
- GPU: 
- Others:
```

### Current Behavior

The Chinese text translates to English as: "Using Milvus 2.4.0 to perform searches poses no problem. However, after upgrading from Milvus 2.4.0 to Milvus 2.4.5, it was found that executing code that mixes vector searches and scalar searches causes the Milvus Docker container to stop and disconnect from Milvus. But executing vector searches or scalar searches separately works normally. When executing mixed searches, the Docker CPU and memory usage is a little over half, so it should not be stopping due to excessive CPU or memory usage.

The code that mixes vector searches and scalar searches  is defined by myself:

the searcher.py:

from pymilvus import MilvusClient, CollectionSchema, FieldSchema, DataType, Collection, utility, connections, Partition, WeightedRanker, RRFRanker, AnnSearchRequest
from pymilvus.model.hybrid import BGEM3EmbeddingFunction
# from fastembed.embedding import FlagEmbedding as Embedding
from tqdm import tqdm
import json
import time
import os
import re

class Searcher:
    def __init__(self, host='localhost', port='19530', collection_name="quote"):
        """
        连接到Milvus数据库
        """
        self.host = host
        self.port = port
        self.collection_name = collection_name
        # 属性partition_name初始值为None，后面如果输入它的值，再更新
        self.partition_name = None
        connections.connect(alias="default", host='localhost', port='19530')

    def vectorize_text(self, text, model_name="BAAI/bge-small-zh-v1.5"):
        """
        将查询文本向量化
        """
        bge_m3_ef = BGEM3EmbeddingFunction(
            model_name=model_name,
            device='cpu',
            use_fp16=False
        )
        vectors = bge_m3_ef.encode_documents([text])
        return vectors

    def get_collection_and_partition(self, partition_name=None):
        """
        创建集合或者分区对象
        """
        if utility.has_collection(self.collection_name):
            print(f"Collection {self.collection_name} already exist")
            # 创建集合对象
            self.collection = Collection(self.collection_name)
            # 创建分区对象，并且加载到内存
            # 如果partition_name存在，则创建partition
            if partition_name:
                # print(f"partition_name:{partition_name}")
                # 属性partition_name初始值为None，如果partition_name存在，则更新
                self.partition_name = partition_name
                # 如果collection中存在partition，则创建partition对象
                if self.collection.has_partition(self.partition_name):
                    self.partition = Partition(self.collection_name, self.partition_name)
                    self.partition.load()
                    print(f"Partition {self.partition_name} has been loaded")
                else:
                    print(f"Partition {self.partition_name} does not exist.")
        else:
            print(f"Collection {collection_name} does not exist.")

    # 在集合中搜索向量，时间1秒左右。在分区中搜索向量，0.1秒左右。标量搜索时间更短

    # 向量搜索
    def vector_search(self, text, limit=21):
        """
        查询向量为单个向量，搜索集合（不做任何过滤，直接搜索）
        """
        # 创建集合对象或者分区对象
        self.get_collection_and_partition()
        # 创建检索参数
        search_params = {
            "metric_type": "COSINE",
            "params": {
                "radius": 0.1,
                "range_filter": 1
            }
        }

        vectorize_start_time = time.time()
        query_vectors = [self.vectorize_text(text)['dense'][0].tolist()]
        vectorize_end_time = time.time()
        vectorize_search_time = vectorize_end_time - vectorize_start_time
        print(f"查询文本向量化时间：{vectorize_search_time}")

        start_time = time.time()
        res = self.collection.search(
            data=query_vectors,
            anns_field="vector",
            param=search_params,
            limit=limit,
            output_fields=["paragraphs", "author"],
        )
        end_time = time.time()
        search_time = end_time - start_time
        print(f"向量搜索时间：{search_time}")
        # self.print_vector_search_results(res)
        return res

    def vector_search_author(self, text, author, limit=21):
        """
        查询向量为单个向量，搜索集合，过滤作者
        """
        # 创建集合对象或者分区对象
        self.get_collection_and_partition()
        # 创建检索参数
        search_params = {
            "metric_type": "COSINE",
            "params": {
                "radius": 0.1,
                "range_filter": 1
            }
        }
        vectorize_start_time = time.time()
        query_vectors = [self.vectorize_text(text)['dense'][0].tolist()]
        vectorize_end_time = time.time()
        vectorize_search_time = vectorize_end_time - vectorize_start_time
        print(f"查询文本向量化时间：{vectorize_search_time}")

        start_time = time.time()
        res = self.collection.search(
            data=query_vectors,
            anns_field="vector",
            param=search_params,
            limit=limit,
            expr = f'author == "{author}"',
            output_fields=["paragraphs", "author"],
        )
        end_time = time.time()
        search_time = end_time - start_time
        print(f"向量搜索时间：{search_time}")
        # self.print_vector_search_results(res)
        return res

    def vector_search_type(self, text, partition_name, limit=21):
        """
        查询向量为单个向量，搜索分区（过滤类型）
        """
        # 创建集合对象或者分区对象
        self.get_collection_and_partition(partition_name)

        print(f"partition: {self.partition}")

        # 创建检索参数
        search_params = {
            "metric_type": "COSINE",
            "params": {
                "radius": 0.1,
                "range_filter": 1
            }
        }
        # 计算向量搜索时间
        vectorize_start_time = time.time()
        query_vectors = [self.vectorize_text(text)['dense'][0].tolist()]
        vectorize_end_time = time.time()
        vectorize_search_time = vectorize_end_time - vectorize_start_time
        print(f"查询文本向量化时间：{vectorize_search_time}")

        start_time = time.time()
        res = self.partition.search(
            data=query_vectors,
            anns_field="vector",
            param=search_params,
            limit=limit,
            output_fields=["paragraphs", "author"],
        )
        end_time = time.time()
        search_time = end_time - start_time
        print(f"向量搜索时间：{search_time}")
        # self.print_vector_search_results(res)
        return res

    def vector_search_type_author(self, text, partition_name, author, limit=21):
        """
        查询向量为单个向量，搜索分区（过滤类型），过滤作者
        """
        # 创建集合对象或者分区对象
        self.get_collection_and_partition(partition_name)
        # 创建检索参数
        search_params = {
            "metric_type": "COSINE",
            "params": {
                "radius": 0.1,
                "range_filter": 1
            }
        }
        # 计算向量搜索时间
        vectorize_start_time = time.time()
        query_vectors = [self.vectorize_text(text)['dense'][0].tolist()]
        vectorize_end_time = time.time()
        vectorize_search_time = vectorize_end_time - vectorize_start_time
        print(f"查询文本向量化时间：{vectorize_search_time}")

        start_time = time.time()
        res = self.partition.search(
            data=query_vectors,
            anns_field="vector",
            param=search_params,
            limit=limit,
            expr = f'author == "{author}"',
            output_fields=["paragraphs", "author"],
        )
        end_time = time.time()
        search_time = end_time - start_time
        print(f"向量搜索时间：{search_time}")
        # self.print_vector_search_results(res)
        return res

    # 标量搜索
    def scalar_search_paragraphs(self, text, limit=None):
        """
        标量搜索，搜索paragraphs字段
        """
        # 创建集合对象或者分区对象
        self.get_collection_and_partition()
        # 定义标量查询表达式
        query_expression = f"paragraphs like '%{text}%'"

        # print(f"exp: {query_expression}")

        # 计算标量搜索时间
        start_time = time.time()

        # 使用分区对象执行查询
        res = self.collection.query(
            expr = query_expression,
            # 输出的字段
            output_fields=["paragraphs", "author", "title"],    
        )
        end_time = time.time()
        search_time = end_time - start_time
        print(f"标量搜索时间：{search_time}")

        # print(f"res:{res}")
        
        # self.print_scalar_search_results(res)

        # for hit in res:
        #     print(hit)

        
        # print(f"数量：{len(res)}")
        # for hit in list(res)[:limit]:
        #     print(hit)
        print(list(res)[:limit])
        return list(res)[:limit]
        

    def scalar_search_author(self, author, limit=None):
        """
        标量搜索，搜索author字段
        """
        # 创建集合对象或者分区对象
        self.get_collection_and_partition()
        # 定义标量查询表达式
        query_expression = f"author == '{author}'"

        # 计算标量搜索时间
        start_time = time.time()

        # 使用分区对象执行查询
        res = self.collection.query(
            expr = query_expression,
            # 输出的字段
            output_fields=["paragraphs", "title"],    
        )
        end_time = time.time()
        search_time = end_time - start_time
        
        # self.print_scalar_search_results(res)

        # for hit in list(res):
        #     print(hit)

        # print(f"标量搜索时间：{search_time}")
        # print(f"数量：{len(res)}")
        # print(type(list(res)))
        # print(list(res))
        for hit in list(res)[:limit]:
            print(hit)
        return list(res)[:limit]

    def scalar_search_paragraphs_author(self, text, author, limit=None):
        """
        标量搜索，搜索paragraphs字段 + author字段
        注意：mivlus2.4.0版本，expr包含两个条件，搜索的结果有不分不满足要求。
        但是milvus升级到2.4.1，docker镜像在load时内存占用过多，自动停止，导致无法连接到milvus服务器
        """
        # 创建集合对象或者分区对象
        self.get_collection_and_partition()
        # 定义标量查询表达式
        # query_expression = "paragraphs like '%天上%' && author == '苏轼'" 

        query_expression = f"author == '{author}' && paragraphs like '%{text}%'" 

        # 计算标量搜索时间
        start_time = time.time()

        # 使用分区对象执行查询
        res = self.collection.query(
            expr = query_expression,
            # 输出的字段
            output_fields=["paragraphs", "title", "author"],    
        )
        end_time = time.time()
        search_time = end_time - start_time
        
        # self.print_scalar_search_results(res)

        # for hit in list(res):
        #     print(hit)

        print(f"标量搜索时间：{search_time}")
        print(f"数量：{len(res)}")
        # print(type(list(res)))
        # print(list(res))
        # for hit in list(res)[:limit]:
        #     print(hit)
        return res
        # return list(res)[:limit]

    def scalar_search_author_list_of_partition(self, partition_name):
        """
        标量搜索，返回某类型（partition）下的作者的列表
        """
        # 创建集合对象或者分区对象
        self.get_collection_and_partition(partition_name)
        # 定义标量查询表达式
        query_expression = "author like '%'"

        # 计算标量搜索时间
        start_time = time.time()

        # 使用分区对象执行查询
        res = self.partition.query(
            expr = query_expression,
            # 输出的字段
            output_fields=["author"],    
        )     
        end_time = time.time()
        search_time = end_time - start_time

        # 使用集合为author字段值去重
        authors_set = {hit["author"] for hit in list(res)}
        # 将集合转换为列表
        authors_list = list(authors_set)
        print(authors_list)

        print(f"标量搜索时间：{search_time}")
        print(f"数量：{len(authors_list)}")
        # print(type(list(res)))
        # print(list(res))

    # 混合搜索：向量 + 标量
    def hybrid_vector_search(self, text, limit=21):
        """
        查询向量为单个向量，搜索集合（不做任何过滤，直接搜索） + 标量
        """
        vector_res = self.vector_search(text, limit=4)
        self.print_vector_search_results(vector_res)
        
        scalar_res = self.scalar_search_paragraphs(text, limit=3)
        self.print_scalar_search_results(scalar_res)

·

    def hybrid_vector_search_author(self, text, author, limit=21):
        """
        查询向量为单个向量，搜索集合，过滤作者 + 标量
        """
        # vector_res = self.vector_search_author(text, author, limit=2)
        # self.print_vector_search_results(vector_res)
        
        print(f"text_str: {text}")
        scalar_res = self.scalar_search_paragraphs_author(text, author)

        print(scalar_res)

        # self.print_scalar_search_results(scalar_res)

    def print_vector_search_results(self, res):
        """
        打印向量搜索结果
        """
        # print("4 打印搜索结果")
        # print("============")
        # print(f"res: {res}")
        # print(f"type of res: {type(res)}")

        for item in res:
            # print(f"item: {item}")
            # print(f"type of item: {type(item)}")
            # print(f"attributes distances of Hits: {item.distances}")
            # print(f"attributes ids of Hits: {item.ids}")

            for hit in item:
                # print(f"hit: {hit}")
                # print(f"type of hit: {type(hit)}")
                print(f"distance: {hit.distance}")
                # print(type(hit.distance))
                print(f"id: {hit.id}")
                print(f"paragraphs: {hit.paragraphs}")
                print(f"author: {hit.author}")
                print("----")

    def print_scalar_search_results(self, res):
        """
        打印标量搜索结果
        """
        for hit in res:
            # hit的内容：{'author': '柳永', 'id': 2109, 'paragraphs': '未遂风云便，争不恣狂荡。'}
            # print(f"hit: {hit}")
            # hit的数据类型：<class 'dict'>，搜索结果中的一个命中
            # print(f"type of hit: {type(hit)}")
            # hit的键值对：paragraphs
            print(f"paragraphs: {hit['paragraphs']}")
            # hit的键值对：author
            print(f"author: {hit['author']}")

if __name__ == "__main__":
    searcher = Searcher()
    searcher.single_vector_search(["大风大雨"])
    searcher.hybrid_vector_search(["风云"])

test.py

from pymilvus import MilvusClient, CollectionSchema, FieldSchema, DataType, Collection, utility, connections, Partition
from pymilvus.model.hybrid import BGEM3EmbeddingFunction
from tqdm import tqdm
import json
import time
import os
import re

connections.connect(alias="default", host='localhost', port='19530')
collection_name = "quote"
collection = Collection(collection_name)
collection.load()

# 等待集合加载完成，最多等待10秒
num_max = 10
num = 0
while num <= num_max:
    # 获取集合加载过程
    progress = utility.loading_progress(collection_name)
    if progress['loading_progress'] == '100%':
        print("集合加载完成")
        break
    else:
        print("集合加载中，当前进度:", progress['loading_progress'])
        time.sleep(1)  # 等待1秒
        num += 1
        print(f"")

# 导入类定义
from searcher import Searcher
searcher.hybrid_vector_search("天下")

### Expected Behavior

I hope to find the reason why Docker stops when executing the custom function hybrid_vector_search on Milvus 2.5.4 (also tried with 2.4.4, which had the same problem), as well as the solution to this issue.

### Steps To Reproduce

```markdown
1. Run the following code: python3 test.py

2. The Milvus Docker container stops running.
```

**Comment by yanliang567** [comment]
@BushJiang please offer the milvus logs for investigation.  For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.
/assign @BushJiang 
/unassign

**Comment by BushJiang** [comment]
@yanliang567 Hear is the [milvus.log](https://github.com/user-attachments/files/15989118/milvus.log), and thank you for your help.

**Comment by congqixia** [comment]
@BushJiang from the log you provide, we could find out that the milvus restarted:
- 2024/06/26 13:23:25.905 +00:00
- 2024/06/26 13:26:51.463 +00:00

since the log does not contains the stderr stream, we cannot make sure why the pod restarted
could you please attach the log with stderr log? also you could check docker control info to make sure the pod did not quit due to out-of-memory issue
/assign @BushJiang
