### ISSUE TITLE
Compile Milvus setup on local system Macbook Air M1 chip Sonoma 14.5 fails

### ISSUE THREAD

**Issue by SID262000** [milvus-io/milvus#34217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I follow the below instruction
# Clone github repository.
$ git clone https://github.com/milvus-io/milvus.git

# Install third-party dependencies.
$ cd milvus/
$ ./scripts/install_deps.sh

# Compile Milvus.
$ make

It throws the below error at the last step(when we try compiling Milvus by running the `make` command) as in the screenshot below. Looks like there is a compatibility issue with conan v1 whereas by default conan v2 gets installed.
<img width="1157" alt="Screenshot 2024-06-26 at 4 19 38 PM" src="https://github.com/milvus-io/milvus/assets/46255642/b55adc5e-0a59-446a-8210-b6d8728a7f27">

### Expected Behavior

It should successfully run the `make` command.

**Comment by SimFG** [comment]
@SID262000 You can try to use a lower version of conan, because it does not support the compilation of higher versions.
reference doc: https://github.com/milvus-io/milvus/blob/master/DEVELOPMENT.md#prerequisites

**Comment by yanliang567** [comment]
/assign @SID262000 
feel free to sumbit a pr for this.

/unassign
