### ISSUE TITLE
[Bug]: Intermittent DEADLINE_EXCEEDED exception when milvus operations like create collection/ hasCollection are invoked

### ISSUE THREAD

**Issue by sindhugsgs** [milvus-io/milvus#34216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.3
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):milvus-sdk-java 2.3.3
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

We get DEADLINE_EXCEEDED exception from milvus sometimes when milvus operations like create collection/ hasCollection are invoked, upon retry it succeeds. We use milvus-sdk-java 2.3.3 and we are creating client with below params along with db, host etc -
                .withConnectTimeout(120, TimeUnit.SECONDS)
                .withRpcDeadline(3, TimeUnit.MINUTES) 
                .withConnectTimeout(2, TimeUnit.MINUTES) 
                .withIdleTimeout(1, TimeUnit.MINUTES)
                .withKeepAliveTimeout(30, TimeUnit.SECONDS)

> exception: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 179.991484860s. [closed=[], open=[[wait_for_ready, buffered_nanos=179991547661, waiting_for_connection]]]
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
	at i.m.g.MilvusServiceGrpc$MilvusServiceBlockingStub.hasCollection(MilvusServiceGrpc.java:4453)
	at i.m.c.AbstractMilvusGrpcClient.hasCollection(AbstractMilvusGrpcClient.java:353)
	at i.m.client.MilvusServiceClient.lambda$hasCollection$1(MilvusServiceClient.java:305)
	at i.m.client.MilvusServiceClient.retry(MilvusServiceClient.java:256)
	at i.m.client.MilvusServiceClient.hasCollection(MilvusServiceClient.java:305)

Increasing withRpcDeadline might solve the issue?To what value we have to increase it?
 We also want to know why is it taking so much time in the first place?

### Expected Behavior

We should not get DEADLINE_EXCEEDED exception from Milvus

### Steps To Reproduce

```markdown
build milvusClient and invoke hasCollection/createCollection 

milvusClient.hasCollection(HasCollectionParam.newBuilder().withCollectionName("collectionName").build());
```

**Comment by xiaofan-luan** [comment]
1. please offer server side log for us to investigate
2. please upgrade to 2.3.18 for a more stable experience

**Comment by prrs** [comment]
It was an internal issue, not a milvus issue.

**Comment by yanliang567** [comment]
> It was an internal issue, not a milvus issue.

then I'd close this issue now. thank you for updates
