### ISSUE TITLE
[Bug]: Incompleted query result

### ISSUE THREAD

**Issue by bigsheeper** [milvus-io/milvus#34247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master&2.4
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

In segcore, once the number of query results reaches the required number, it returns:
<img src="https://github.com/milvus-io/milvus/assets/42060877/334aabc5-68d6-4c64-9731-3c9dca0f202c" width=70% height=70%>

So in the scenario with duplicate pks, the results obtained may include duplicates. We need to deduplicate pks in segcore reduce, similar to internal reduce and global reduce.

This issue exists for both growing segments and sealed segments.

**Comment by bigsheeper** [comment]
see also: https://github.com/milvus-io/milvus/issues/34021

**Comment by xiaofan-luan** [comment]
we need to make sure there is no duplicate pK in every segment.

This is done by:
1. Temporarily -> mask entry duplicated PK as delete 
2. Final fix -> when segment is flushed, do an analyze task tor reorder

**Comment by bigsheeper** [comment]
> we need to make sure there is no duplicate pK in every segment.
> 
> This is done by:
> 
> 1. Temporarily -> mask entry duplicated PK as delete
> 2. Final fix -> when segment is flushed, do an analyze task tor reorder

@zhagnlu will help implement feature 1.
