### ISSUE TITLE
[Bug]: Unable to set up development environment in Mac 

### ISSUE THREAD

**Issue by tusm123** [milvus-io/milvus#34262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Building Milvus ... # github.com/tikv/client-go/v2/util /Users/a123/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.7/util/pd_interceptor.go:47:18: cannot use &InterceptedPDClientäå (value of type *InterceptedPDClient) as pd.Client value in variable declaration: *InterceptedPDClient does not implement pd.Client (wrong type for method ScanRegions) 		have ScanRegions(context.Context, ÄÅbyte, ÄÅbyte, int) (ÄÅ*pd.Region, error) 		want ScanRegions(context.Context, ÄÅbyte, ÄÅbyte, int, ...pd.GetRegionOption) (ÄÅ*pd.Region, error) # github.com/milvus-io/milvus/pkg/util/typeutil pkg/util/typeutil/schema.go:593:6: unknown field ValidData in struct literal of type schemapb.FieldData pkg/util/typeutil/schema.go:593:27: fieldData.GetValidData undefined (type *schemapb.FieldData has no field or method GetValidData) # github.com/milvus-io/milvus/pkg/util/etcd pkg/util/etcd/etcd_util.go:238:9: config.LCUrls undefined (type *"go.etcd.io/etcd/server/v3/embed".Config has no field or method LCUrls) pkg/util/etcd/etcd_util.go:243:9: config.LPUrls undefined (type *"go.etcd.io/etcd/server/v3/embed".Config has no field or method LPUrls) # github.com/milvus-io/milvus/internal/metastore/model internal/metastore/model/field.go:113:3: unknown field Nullable in struct literal of type schemapb.FieldSchema internal/metastore/model/field.go:148:32: fieldSchema.Nullable undefined (type *schemapb.FieldSchema has no field or method Nullable) make: *** ÄmilvusÅ Error 1

**Comment by yanliang567** [comment]
@tusm123 what is you mac chip, do you try to compile milvus source?
/assign @tusm123 
/unassign

**Comment by xiaofan-luan** [comment]
how did you build?

you should first run install_dep.sh then directly do make

**Comment by xiaofan-luan** [comment]
seems that under your environment you can not pull the go dependencies

**Comment by tusm123** [comment]
There is a problem with this dependency tikv/client-go/v2@v2.0.7 . There is an incompatibility issue with the github.com/tikv/pd/client version it depends on；

The problem has been solved now
