### ISSUE TITLE
Error should be specified if searching a collection not existed

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#3427]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
2020-08-24 15:41:09 io.milvus.client.MilvusGrpcClient logError 
ERROR: Search failed:
error_code: UNEXPECTED_ERROR
reason: "Snapshots::GetHolderNoLock: Specified snapshot holder for collection \"collection_ZBooRiaOcX_CeRbmbkAGK\" not found"
```

**Steps/Code to reproduce behavior**
```
    @Test(dataProvider = "Collection", dataProviderClass = MainClass.class)
    public void testSearchCollectionNotExisted(MilvusClient client, String collectionName)  {
        String collectionNameNew = Utils.genUniqueStr(collectionName);
        SearchParam searchParam = new SearchParam.Builder(collectionNameNew).withDSL(searchParamStr).build();
        SearchResponse res_search = client.search(searchParam);
        assert (!res_search.getResponse().ok());
    }

```

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by shengjun1985** [comment]
GrpcRequestHandler did not handle the error code "SS_NOT_FOUND_ERROR".
So the client received "UNEXPECTED_ERROR" but not "COLLECTION_NOT_EXISTS".

There may be two solutions.
(1) Transform the error code in DBImpl.
(2) Add a new ErrorMap in GrpcRequestHandler.
