### ISSUE TITLE
Milvus server integrated with opentracing to support distributed tracing

### ISSUE THREAD

**Issue by XuPeng-SH** [milvus-io/milvus#343]
[Opentracing overview](https://opentracing.io/docs/overview/)

**Is your feature request related to a problem? Please describe.**
Developers can use distributed tracing to help debug and optimize their code.

**Describe the solution you'd like**
Integrate Opentracing framework in Milvus

**Comment by youny626** [comment]
Current implementation:
- Uses a separate tracing config file in JSON format
- Dynamically loads tracing shared libraries (Jaeger, Zipkin etc)
- Uses gRPC interceptor and starts / finishes Span on post receive initial metadata / pre-send message 
- Implements customized Context that propagates Span / Trace across process boundaries

Stuff to do:
- Expand and improve tracing configurations

**Comment by JinHai-CN** [comment]
Document isn't provided.

**Comment by scsven** [comment]
Already be integrated into the master branch.
