### ISSUE TITLE
[Bug]: failed to search/query delegator 13 for channel by-dev-rootcoord-dml_10_450726761228907207v0: fail to Search, QueryNode ID=13, reason=Timestamp lag too large

### ISSUE THREAD

**Issue by iwanglei1** [milvus-io/milvus#34320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.3.4
- Deployment mode(standalone or cluster): standalone 
- MQ type(rocksmq, pulsar or kafka): Unknown 
- SDK version(e.g. pymilvus v2.0.0rc2): Attu v2.4.3
- OS(Ubuntu or CentOS): Ubuntu 22.04
- CPU/Memory: 80 core/ 256 G
- GPU: 4 * 3090
- Others:
```

### Current Behavior

This error may be prompted during query. Setting data consistency can avoid the error, but the data cannot be queried.

**Comment by yanliang567** [comment]
usually it is about that datanode is not able to handle so many writing to milvus, but we need the completed logs to tell what was hanppending. Could you please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.

/assign @iwanglei1 
/unassign

**Comment by yanliang567** [comment]
also please try to upgrade to milvus 2.3.18 or 2.4.5, which has fixed many issues in writing.
