### ISSUE TITLE
The row count of segment should be strictly  limited with parameter "segment_row_count"

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#3435]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

1. segment_row_count = 5000
2. Insert  8000 entities at one time
3. The number of segment is 1 rather than 2
```
{"data_size":7029460,"partitions":[{"data_size":7029460,"id":9,"row_count":8000,"segments":[{"data_size":7029460,"files":[{"data_size":68120,"field":"_id","name":"_raw","path":"*"}...],"id":9,"row_count":8000}],"tag":"_default"}],"row_count":8000}
```
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
master

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
fixed by pr3529
