### ISSUE TITLE
[Bug]: Why did externalPulsar authParmas make this mistake?

### ISSUE THREAD

**Issue by 1191510903** [milvus-io/milvus#34412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
pulsar:
      address: 172.20.60.41
      port: 30012
      maxMessageSize: 5242880
      tenant: "xxx"
      namespace: xxx
      authPlugin: org.apache.pulsar.client.impl.auth.AuthenticationToken
      authParams: {"token": "eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJsbG0tcGxhdGZvcm0tdG9rZW4ifQ.g4cejYFJtfUlPHbeOdmNRjMlNWImhvLkcF-YR71YpPjiXihqCTOMxxx"}
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/55501552/b6bdd7af-012d-46e8-bde2-74a2b30a9750)

**Comment by 1191510903** [comment]
看源码发现是go解析jwt token没有解析出来，是否有解决方案呢？

**Comment by SimFG** [comment]
you can try to set `authparams` like:
```
authParams: token:eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJsbG0tcGxhdGZvcm0tdG9rZW4ifQ.g4cejYFJtfUlPHbeOdmNRjMlNWImhvLkcF-YR71YpPjiXihqCTOMxxx
```

**Comment by yanliang567** [comment]
/assign @1191510903 
please try as comments above
/unassign

**Comment by 1191510903** [comment]
> /assign @1191510903 please try as comments above /unassign
resolved，but Why is this configured? 
View the go source Code   does not support this

![image](https://github.com/milvus-io/milvus/assets/55501552/1664747a-feb4-4d1b-bc2e-5044caa1aa8b)

**Comment by 1191510903** [comment]
> > /assign @1191510903 please try as comments above /unassign
> > resolved，but Why is this configured?
> > View the go source Code   does not support this
> 
> ![image](https://private-user-images.githubusercontent.com/55501552/345721619-1664747a-feb4-4d1b-bc2e-5044caa1aa8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNzU2ODYsIm5iZiI6MTcyMDA3NTM4NiwicGF0aCI6Ii81NTUwMTU1Mi8zNDU3MjE2MTktMTY2NDc0N2EtZmViNC00ZDFiLWJjMmUtNTA0NGNhYTFhYThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDA2NDMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjYWQzYzdmYjhjZjllYThjZWE1ODhjN2M3MzY2YjU4ZDI4ODYwZWY2YjBjM2M1ZGFhZmQ3NjVlM2Y2MDM5OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._rbI3ZigdGyBngYOzeBoaiU3ynjY9Cd_MHRVdHF1alo)

I see，This is the syntax of yaml。 thanks !  It's a low-level question ！AI Big models always talk nonsense too
