### ISSUE TITLE
[Bug]: How to communicate pulsar using http protocol 

### ISSUE THREAD

**Issue by 1191510903** [milvus-io/milvus#34419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
pulsar:
      address: "172.20.48.68"
      port: 80
      maxMessageSize: 5.24288e+06
      tenant: "xxx"
      namespace: "xxx"
      authPlugin: "org.apache.pulsar.client.impl.auth.AuthenticationToken"
      authParams: token:eyJhbGciOiJSUzI1NiJ9
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/55501552/99a4ef84-2072-4032-8084-b9ebc7722de6)

### Expected Behavior

expected pulsar://172.20.48.68:80 change to http://172.20.48.68:80,Because there are gateways above pulsar,the address  http://172.20.48.68:80 is the janus gateway。

**Comment by xiaofan-luan** [comment]
try to change address config to 
http://172.20.48.68:80 see if it works

**Comment by 1191510903** [comment]
> try to change address config to http://172.20.48.68:80 see if it works
![img_v3_02cg_0eb12cba-86ca-4c4c-8266-13e2f1ff0fbg](https://github.com/milvus-io/milvus/assets/55501552/4cbf34de-6c75-4b14-9446-9610b63278e1)
Maybe not, but I'll continue to explore the web

**Comment by 1191510903** [comment]
> > try to change address config to http://172.20.48.68:80 see if it works
> > ![img_v3_02cg_0eb12cba-86ca-4c4c-8266-13e2f1ff0fbg](https://private-user-images.githubusercontent.com/55501552/346122092-4cbf34de-6c75-4b14-9446-9610b63278e1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxODI2OTgsIm5iZiI6MTcyMDE4MjM5OCwicGF0aCI6Ii81NTUwMTU1Mi8zNDYxMjIwOTItNGNiZjM0ZGUtNmM3NS00YjE0LTk0NDYtOTYxMGI2MzI3OGUxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDEyMjYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNzZjMzM1ZDAzMTgwZDQ0MjI1YWMxMzc5NWI2ZTdhNGZmYTRhYTMzNTRlOWJlZDI4YjU5ZjE1OGZmMTBiMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X6dimauXkZPAOkzDYMULXfTrPsvHx_1cS8PbixathE8)
> > Maybe not, but I'll continue to explore the web
![image](https://github.com/milvus-io/milvus/assets/55501552/85ff3191-a6d4-4c96-a3f8-6075de6bfb3d)

**Comment by xiaofan-luan** [comment]
<img width="1006" alt="image" src="https://github.com/milvus-io/milvus/assets/83447078/2b14f112-a579-48f1-8b69-3b9699704913">

**Comment by xiaofan-luan** [comment]
the error seems to be no such host , and 404 route not found.

**Comment by 1191510903** [comment]
> <img alt="image" width="1006" src="https://private-user-images.githubusercontent.com/83447078/346245030-2b14f112-a579-48f1-8b69-3b9699704913.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0ODkwMzgsIm5iZiI6MTcyMDQ4ODczOCwicGF0aCI6Ii84MzQ0NzA3OC8zNDYyNDUwMzAtMmIxNGYxMTItYTU3OS00OGYxLThiNjktM2I5Njk5NzA0OTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDAxMzIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0YjFhN2UzMmY0YTJkYTQzMjk2NDFmMzExYTg5NDEzYTM2MDQxZDRjYWE1NDZiOTEwODAzZTI4YTllNTg4MTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qyXudk4h1gv4VlJulyfkIpfeoKByLKuoFFO3vEvNhs8">

which version? 
Just search for this one
![image](https://github.com/milvus-io/milvus/assets/55501552/93395b1d-709c-47cc-8d49-33a40b6a5c03)

**Comment by 1191510903** [comment]
> the error seems to be no such host , and 404 route not found.
![image](https://github.com/milvus-io/milvus/assets/55501552/578beeb3-3ee6-47ca-ba31-1cf266fe5e9e)
see this bug

**Comment by xiaofan-luan** [comment]
why is this a bug, it's already use http address. HTTP will connect with tcp as well.
The failure reason is due to dns lookup up
