### ISSUE TITLE
[Bug]: can not pull docker images which /deployments/docker/dev/docker-compose.yml requests

### ISSUE THREAD

**Issue by tasty-gumi** [milvus-io/milvus#34411]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

`(base) adam@Adam-PC:~/milvus/deployments/docker/dev$ docker-compose up -d
[+] Running 0/1
 ⠸ zookeeper 16 layers [⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]      0B/0B      Pulling                                                                                       176.4s 
error pulling image configuration: download failed after attempts=6: dial tcp [2a03:2880:f12a:83:face:b00c:0:25de]:443: i/o timeout`
I have tried many times ,finally,still can't pull the zookeeper image.
can I find tar format images instead?

**Comment by SimFG** [comment]
maybe you can try this method, reference doc: https://gist.github.com/y0ngb1n/7e8f16af3242c7815e7ca2f0833d3ea6

**Comment by tasty-gumi** [comment]
> maybe you can try this method, reference doc: https://gist.github.com/y0ngb1n/7e8f16af3242c7815e7ca2f0833d3ea6

it helps a lot ,thanks!

**Comment by yanliang567** [comment]
i'd close this issue then. Please free to file new issues if you met anything new.
