### ISSUE TITLE
[Bug]: [GOSDK] Create IVF_PQ index with invalid nbits didn't raise exception

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#34426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvus-io-master-e083d99-20240701
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): gosdk v2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. valid `nbits` for IVF_PQ index is [1, 16]. Create index with invalid params didn't return error
![image](https://github.com/milvus-io/milvus/assets/27288593/6fe65103-ef0d-4111-8ffe-f74811a313e8)
```
// invalid IvfPq params m dim ≡ 0 (mod m), nbits [1, 16]
	for _, invalidNBits := range []int{0, 17} {
		// IvfFlat
		idxIvfPq := index.NewIvfPQIndex(entity.L2, 128, 8, invalidNBits)
		_, err := mc.CreateIndex(ctx, client.NewCreateIndexOption(schema.CollectionName, common.DefaultFloatVecFieldName, idxIvfPq))
		common.CheckErr(t, err, false, "nbits has to be in range [1, 16]")
	}
```

### Steps To Reproduce

```markdown
case TestCreateIndexInvalidParams in index_test.go
```

**Comment by congqixia** [comment]
`nbits` does not have limit actually in practice.
The actually valid range is [1, 64] in knowhere code. Having nbits larger than 64 will make knowhere use auto calculation logic depending on segment row number.
/cc @liliu-z

**Comment by ThreadDao** [comment]
fixed
