### ISSUE TITLE
when use the dockerfile to deploy k8s,   I got an error Deadline Exceeded

### ISSUE THREAD

**Issue by leidaxia** [milvus-io/milvus#3445]
I use the dockerfile 
![image](https://user-images.githubusercontent.com/20982126/91131090-4b153d00-e6df-11ea-9dcc-c9f837d2a489.png)
I can build and run it localhost , and use the python sdk can use it,
But I deploy it on K8s,  I change the cache_size of  the server_config.yaml from 4GB to1GB, and 2 pods, every pod have 2cores and 4GB,  the service is started suceefully,  but I use python sdk to insert some data to it, I got the error
![image](https://user-images.githubusercontent.com/20982126/91132207-b4954b80-e6df-11ea-9a8e-e000d6d1c446.png)

**Comment by BossZou** [comment]
@leidaxia , I think you need to check if your network is ok or your server is running well ? Was there any proxy in your k8s environment?

**Comment by leidaxia** [comment]
> @leidaxia , I think you need to check if your network is ok or your server is running well ? Was there any proxy in your k8s environment?
yes, it is running well,  and the k8s give me a host, I can ping it

**Comment by leidaxia** [comment]
> @leidaxia , I think you need to check if your network is ok or your server is running well ? Was there any proxy in your k8s environment?

![image](https://user-images.githubusercontent.com/20982126/91162439-a99de380-e6fe-11ea-9518-aabfa019b41e.png)
now I find the error
