### ISSUE TITLE
[Bug]: search results are less than limit(topk) even with FLAT index

### ISSUE THREAD

**Issue by park12sj** [milvus-io/milvus#34468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.8
- MQ type(rocksmq, pulsar or kafka): kafka  
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus
```

### Current Behavior

When doing the embedding search as shown below, the output does not come as much as "limit".
In the example, it was given as 3, but only 2 results were returned.
```
search_params = {
    "metric_type": "COSINE",
    "offset": 0,
    "ignore_growing": False,
}
results = image_embedding_collection.search(
    data=[text_embedding],
    anns_field="embedding",
    param=search_params,
    limit=3,
    expr=f"place_id == '387579771'",
    output_fields=["img_urls"],
)
```

Even though there are more than three data in `place_id == '387579771'`
![image](https://github.com/milvus-io/milvus/assets/28818972/137917ed-4b12-4ad8-b2ed-09d116fd07e2)

Schema and index are as follows.
```
from pymilvus import CollectionSchema, DataType, FieldSchema

place_id = FieldSchema(
    name="place_id",
    dtype=DataType.VARCHAR,
    max_length=128,
    is_primary=False,
)
img_url = FieldSchema(
    name="img_url",
    dtype=DataType.VARCHAR,
    max_length=512,
    is_primary=True,
)
model_version = FieldSchema(
    name="model_version",
    dtype=DataType.VARCHAR,
    max_length=64,
    is_primary=False,
)
embedding = FieldSchema(name="embedding", dtype=DataType.FLOAT_VECTOR, dim=768)

schema = CollectionSchema(
    fields=[place_id, img_url, model_version, embedding],
    description="Image Retrieval Vector DB",
    enable_dynamic_field=True,
)

index_settings = [
    {
        "field_name": "embedding",
        "index_name": "vector_index",
        "index_params": {
            "metric_type": "COSINE",
            "index_type": "FLAT",
        },
    },
    {
        "field_name": "place_id",
        "index_name": "place_id_scalar_index",
    },
    {
        "field_name": "model_version",
        "index_name": "model_version_scalar_index",
    },
]

```

I think, there are two reasons that can be inferred
- After embedding serarch, filter with expr
- Certain thresholds exist during embedded search

I wonder if there are any causes and solutions.

There seems to be an [issue](https://github.com/milvus-io/milvus/issues/31658) as a similar issue, but it was difficult to apply that issue because it is related to the ef parameter of HNSW algorithm.

### Expected Behavior

Return result as long as Limit

### Anything else?

No response

**Comment by yanliang567** [comment]
@park12sj which versions of milvus and pymilvus are you running? could you please try to set the consistency level to strong as below:
```
from pymilvus.orm.types import CONSISTENCY_STRONG
results = image_embedding_collection.search(
    data=[text_embedding],
    anns_field="embedding",
    param=search_params,
    limit=3,
    expr=f"place_id == '387579771'",
    output_fields=["img_urls"],
  consistency_level=CONSISTENCY_STRONG
)
```
I tried to reproduce it on latest milvus 2.4.5 and pymilvus 2.4.4, but no luck. if possible, also retry on the latest milvus.

/assign @park12sj 
/unassign

**Comment by park12sj** [comment]
@yanliang567 

i use `milvus==2.3.8`, `pymilvus==2.3.7`
`CONSISTENCY_STRONG` also exist in pymilvus==2.3.7, but it doesn't work.
https://github.com/milvus-io/pymilvus/blob/e0247935fc8f796c4d35f1fb868e6dccbf57cf4f/pymilvus/orm/types.py#L149

I will update the milvus version and try again.
Before that, I have a question. Is it correct that even if `expr` is given as a factor, the serarch output comes out as limit?
I am suspecting that the omission may occur as it is filtered by `expr` after the embedding search, but I did not find the relevant information in the document.

**Comment by yanliang567** [comment]
as long as there are enough entities meet the expr filtering, milvus will always return results as the limit(topk) requires. Because Milvus first will do filtering before ann embedding search.

**Comment by park12sj** [comment]
```
results = image_embedding_collection.search(
    data=[text_embedding],
    anns_field="embedding",
    param=search_params,
    limit=3,
    expr=f"place_id == '387579771'",
    output_fields=["img_urls"],
  consistency_level=CONSISTENCY_STRONG
)
```

The primary key was duplicated in the data that was being uploaded.(because this is data for test)
```
ex)
data = [
  {
      "place_id": place_id,
      "img_url": img_url1,
      "embedding": image_embedding,
      "model_version": model_version,
  },
  {
      "place_id": place_id,
      "img_url": img_url2,
      "embedding": image_embedding,
      "model_version": model_version,
  },
  {
      "place_id": place_id,
      "img_url": img_url3,
      "embedding": image_embedding,
      "model_version": model_version,
  },
  {
      "place_id": place_id,
      "img_url": img_url1,
      "embedding": image_embedding,
      "model_version": model_version,
  },
  {
      "place_id": place_id,
      "img_url": img_url2,
      "embedding": image_embedding,
      "model_version": model_version,
  },
  {
      "place_id": place_id,
      "img_url": img_url3,
      "embedding": image_embedding,
      "model_version": model_version,
  },
  {
      "place_id": place_id,
      "img_url": img_url1,
      "embedding": image_embedding,
      "model_version": model_version,
  },
]
```
In this case, even if I removed the duplication, even though it was 30 data, 14 data were loaded in milvus, and there was a phenomenon that came less than limit when searching.

The phenomenon was resolved when the primary key duplicate was removed from the data that was being uploaded.
This also seems like a bug, but it's not the latest milvus, and I'll close the issue because it's clear how to avoid the status quo.
