### ISSUE TITLE
The version need to be upgraded

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#3449]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
The current server version need to be upgraded to 0.11.0

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
master-branch

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by BossZou** [comment]
Need to upgrade milvus version on master branch to v0.11.0
