### ISSUE TITLE
[Bug]:why the milvus-dashboard.json  storage  separate the proxy contention？ 

### ISSUE THREAD

**Issue by ronghuaihai** [milvus-io/milvus#34522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.16
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

when i download the newest  mivlus-dasboard.json and use it in graphna ，it is unnormal 。the storage parition separate the proxy parition 。
<img width="1741" alt="image" src="https://github.com/milvus-io/milvus/assets/14067712/ff5c5229-3fe7-4ea9-8cad-9b583e3d6a91">

but ，when i use milvus.2.2.14.json ，it is normal。as follows：
<img width="1742" alt="image" src="https://github.com/milvus-io/milvus/assets/14067712/4ad80780-e8b2-4c94-9047-4ebc0759329a">

**Comment by ronghuaihai** [comment]
which one edition should  to use when monitor 2.3.16 mivlus version？ the older 2.2.14 or newest dashboar ？

**Comment by yanliang567** [comment]
@ronghuaihai which link do you download for the newest dashboard? I guess the latest one could be for Milvus 2.4.x. As long as it works, I think you can use the old one unless you are looking for some new metrics.
/assign @ronghuaihai 
/unassign

**Comment by xiaofan-luan** [comment]
/assign @locustbaby 
could you help on answer this?
