### ISSUE TITLE
[Bug]: High CVEs of milvus go lib: go.opentelemetry.io/.... v0.38.0

### ISSUE THREAD

**Issue by weiZhenkun** [milvus-io/milvus#34547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: Milvus 2.4.5 & master
```

### Current Behavior

Can we update to v0.38.0 to 0.46.0?
https://github.com/milvus-io/milvus/blob/master/go.mod#L49C2-L49C85

![image](https://github.com/milvus-io/milvus/assets/27683687/d409c24a-c71f-4eb7-9ec0-c98b8a8b88bb)

### Expected Behavior

Can we update to v0.38.0 to 0.46.0?

**Comment by yanliang567** [comment]
/assign @congqixia @xiaofan-luan 
I think we have some plans for it.
/unassign

**Comment by weiZhenkun** [comment]
pr:34462

**Comment by weiZhenkun** [comment]
fix on 2.4.6 https://github.com/milvus-io/milvus/pull/34693

**Comment by congqixia** [comment]
already fixed, closing this issue
