### ISSUE TITLE
[Enhancement]: Concurrency control of clustering compaction

### ISSUE THREAD

**Issue by wayblink** [milvus-io/milvus#34544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

#34495 

Clustering compaction is much bigger task than normal compaction. And milvus doesn't have a strict memory control. Hence, we need to control the concurrency of clustering compactions.

**Comment by xiaofan-luan** [comment]
what is the memory estimation of a clustering compaction? is it related to segment number * bin log size?

what is the expected memory usage and concurrency?
