### ISSUE TITLE
[Bug]:  Channel-cp meta still exists after the collection GC

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#34545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4 
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

We couldn't find any meta data about collection id: 449684528748778322 in etcd except for `06b84fe16780ed1/meta/datacoord-meta/channel-cp/in01-06b84fe16780ed1-rootcoord-dml_3_449684528748778322v0`

**Comment by xiaofan-luan** [comment]
<img width="1316" alt="image" src="https://github.com/milvus-io/milvus/assets/83447078/77d2a98f-f5d9-4b6e-80ea-dae3a1f43bab">

**Comment by xiaofan-luan** [comment]
this has to be moved out of segment gc loop

**Comment by jaime0815** [comment]
The channel cp meta can not be removed when no dropped segment GC happens, such as:
1. Drop an empty collection that never inserts any data 
2. Import task fails will remove segment meta directly in the older version
