### ISSUE TITLE
[Bug]: Indexnode stuck at stopping progress

### ISSUE THREAD

**Issue by weiliu1031** [milvus-io/milvus#34557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master and 2.4 and 2.3
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

if someone call `ShowConfigurations` API on indexnode, which increase the lifetime's ref counter, but doesn't call `lifetime.Done`,  then stop progress will stuck forever at `lifetime.Wait`

**Comment by xiaofan-luan** [comment]
/assign @yanliang567 
please verify on tis
