### ISSUE TITLE
[Bug]: Not able to reduce segment size in V2.4.5

### ISSUE THREAD

**Issue by sumanthhuddar** [milvus-io/milvus#34550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4.5
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):java
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 32 CPU/120GB 
- GPU: 
- Others:
```

### Current Behavior

I loaded collection with maxsegment size set to 1024 MB , after loading ~4 M , i had ~26 segments. I Changed maxsegment to 4GB , and restarted datacoord node, and nunber of segments reduced from 26 to 8 . Now when i try to increase number of segments by setting maxsegmentsize to 2GB , it is not effective. tried restarting data coord and data nodes , load\unload collection , compact , also tuned with sealProportion with values 0.12,.0.24,.75 but there is no change in segmets\segment size. 

### Expected Behavior

 Decreasing maxsegment should increase number of segments.

**Comment by yanliang567** [comment]
increasing the value of maxsegmentsize is a one-way street for the existing segments. Milvus only has compaction policy to compact small segments to larger ones, but has no policy to split the large segments to smaller ones.  So for now this is expected.  @sumanthhuddar 

/assign @sumanthhuddar 
/unassign

**Comment by xiaofan-luan** [comment]
I thought this is actaully doable.
With the new clustering compaction, segment can be split into the size limtied.

@wayblink  could you please take a look at it

**Comment by wayblink** [comment]
@sumanthhuddar As @yanliang567 mentioned, it is currently expected. We will think about adding policy to split the large segments to smaller ones. Clustering compaction can compact segments to smaller size. However, it needs alter the collection, set clustering key field first, it is not supported now.

I wonder what's your purpose for trying different maxSegmentSize? We can find out best solution for you.

**Comment by xiaofan-luan** [comment]
again we don't recommend to do so, PLEASE keep segment size to be less than 8G, unless you never delete, update and insert

**Comment by xiaofan-luan** [comment]
Build a huge index is not really useful in production environment. You have many other way to optimize performance, and scale or use zilliz cloud is usaully the easiest way.

We have so much pain to use larger index so my suggesion is simply "Don't do that!"

**Comment by sumanthhuddar** [comment]
@xiaofan-luan thanks for the suggestions.

**Comment by xiaofan-luan** [comment]
Segment size of 2GB or 4GG is reasonable. 
We recomend user with 16GB memory or more to use 2GB segment size. 32GB or more to use 4GB segment szie.
The maximum segment size we recommend is 8GB.

The reason is build index a 8GB or more segment is very expensieve (Takes hours to do so with 8core32G index, might even OOM). also frequent update, insert will bring trouble as well
