### ISSUE TITLE
[Bug]:  UT Sealed.LoadFieldDataMmap core dump

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#34589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

 RUN      ] Sealed.LoadFieldDataMmap
*** Aborted at 1720589589 (Unix time, try 'date -d @1720589589') ***
*** Signal 8 (SIGFPE) (0x7f9cd4f1bcd2) received by PID 221 (pthread TID 0x7f9cd16a47c0) (linux TID 221) (code: integer divide by zero), stack trace: ***
(error retrieving stack trace)
./scripts/run_cpp_codecov.sh: line 65:   221 Floating point exception(core dumped) ${MILVUS_CORE_UNITTEST_DIR}/${test}

**Comment by smellthemoon** [comment]
occurred in master too.
