### ISSUE TITLE
[Bug]: Only search output vector is performed, but the monitor sees search and query. 

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#34601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3, 2.4 & master
- Deployment mode(standalone or cluster):all
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I do a seach output vector, the monitor sees that both search and query are going on
![image](https://github.com/milvus-io/milvus/assets/48523564/4e8634d3-9754-4dd7-9808-df6e545bb311)

### Expected Behavior

If I do a search output vector, the monitor only displays the search and not the search and query.

**Comment by yanliang567** [comment]
internal re-query should not be counted into metrics...

**Comment by congqixia** [comment]
master & 2.4 already fixed
doing some code refinement and cherry-pick

**Comment by elstic** [comment]
issue fixed. 
verify image: 2.4 and master's latest image
