### ISSUE TITLE
[Bug]: CVEs of zilliz/attu:v2.4.3

### ISSUE THREAD

**Issue by weiZhenkun** [milvus-io/milvus#34623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- zilliz/attu:v2.4.3
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/27683687/95732103-55bd-47d4-89bc-31fd78befd1e)

### Expected Behavior

1. Can we update the ws from 8.11.0 to 8.17.1?
2. Rebuilding the attu image will fix the 4 high CVEs as his base image has fixed.

![image](https://github.com/milvus-io/milvus/assets/27683687/bc2e092a-5ce5-444a-8834-e7196b92a2d7)

**Comment by xiaofan-luan** [comment]
/assign @shanghaikid 
please help on it

**Comment by weiZhenkun** [comment]
@shanghaikid when can we get a new helm version with this attu fix?

**Comment by shanghaikid** [comment]
> @shanghaikid when can we get a new helm version with this attu fix?

There will be a new attu release in two days.

**Comment by shanghaikid** [comment]
https://github.com/zilliztech/attu/releases/tag/v2.4.5
