### ISSUE TITLE
[Bug]: CVEs of milvus-config-tool:v0.3.0 & milvus-config-tool:v0.1.2

### ISSUE THREAD

**Issue by weiZhenkun** [milvus-io/milvus#34622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: Milvus 2.4.5
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/27683687/13e25f46-d1e0-4e57-b1a8-58afe748e6d1)
![image](https://github.com/milvus-io/milvus/assets/27683687/e632b137-2c4a-43b0-81f3-7ed01763649c)

There are 5 high CVEs in milvus-config-tool.
Is the milvus-config-tool is a open source project?

**Comment by weiZhenkun** [comment]
@LoveEachDay  any update for this?

**Comment by LoveEachDay** [comment]
@weiZhenkun We've removed the milvus-config-tool image for milvus helm deployment.
