### ISSUE TITLE
How to modify the maximum length of the milvus field 'max_length'?

### ISSUE THREAD

**Issue by yangy996** [milvus-io/milvus#34646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![749197952b1b5e5583040a93e8c5e85e](https://github.com/user-attachments/assets/f1c0fba6-331b-41cd-90ab-9d8d37e452db)

**Comment by yanliang567** [comment]
I think you defined the max length in your collection schema. please try to describe the collection schema for the details. Milvus does not support dynamically update the max length for now, you need to create a new collection with a new max length value.
/assign @yangy996 
/unassign

**Comment by yangy996** [comment]
> I think you defined the max length in your collection schema. please try to describe the collection schema for the details. Milvus does not support dynamically update the max length for now, you need to create a new collection with a new max length value.我认为你在集合模式中定义了最大长度。请尝试描述收集方案的细节。Milvus目前不支持动态更新最大长度，您需要创建一个新的集合，并使用新的最大长度值。 /assign @yangy996 /unassign

My god.I have already stored a lot of data. How can I not clear the data and create a new collection?

**Comment by xiaofan-luan** [comment]
@yanliang567 

we already have modify collection request

/assign @PowderLi could you help on modify the schema?

**Comment by xiaofan-luan** [comment]
@yangy996 
mean time, you can use birdwatcher to hack the schema and rewrite into etcd.
simply read it out from etcd, hack the length, write it back and restart rootcoord would work
don't forget to backup before do so

**Comment by yangy996** [comment]
The length of this text is only 2208 characters, but after storing it in Milvus, it shows 5066. Does Milvus store Chinese text in bytes instead of string length?

![6f96f4f71633015dfc70616b0f450e1e](https://github.com/user-attachments/assets/40b1b918-fc01-4a92-b7d4-b7aea29675ca)

**Comment by xiaofan-luan** [comment]
the length of milvus is byte length.
A chinese character is only usually 2-3 bytes.

You can simply set varchar length to 65536

**Comment by mjzcng** [comment]
> @yangy996 mean time, you can use birdwatcher to hack the schema and rewrite into etcd. simply read it out from etcd, hack the length, write it back and restart rootcoord would work don't forget to backup before do so

Hello! I've met the same issue and I just noticed your reply. Now I've installed birdwatcher and connected to etcd, could you please explain how to use birdwatcher to hack the schema and rewrite? I have read help in birdwatcher but still don't understand how to do this. Thank you !

**Comment by yanliang567** [comment]
/assign @congqixia 
please help

**Comment by xiaofan-luan** [comment]
I think modify max length feature is a easy fix.
it should be very easy with load/release
@congqixia  could you help on this?

**Comment by beyondguo** [comment]
> the length of milvus is byte length. A chinese character is only usually 2-3 bytes.
> 
> You can simply set varchar length to 65536

@xiaofan-luan  Hi, I think this is not a common definition for "max_length" especially for NLP. Its hard to truncate my text by `text[:maxlen]` durning pre-processing since I don't know how many bytes it takes.

Can you tell me how the 'max_length' parameter in Milvus will affect the indexing/seraching pertformance? For example, if I simply set varchar length to 65536, will it be quite slow? (even if my average lengh can be quite small)

**Comment by xiaofan-luan** [comment]
> > the length of milvus is byte length. A chinese character is only usually 2-3 bytes.
> > You can simply set varchar length to 65536
> 
> [@xiaofan-luan](https://github.com/xiaofan-luan) Hi, I think this is not a common definition for "max_length" especially for NLP. Its hard to truncate my text by `text[:maxlen]` durning pre-processing since I don't know how many bytes it takes.
> 
> Can you tell me how the 'max_length' parameter in Milvus will affect the indexing/seraching pertformance? For example, if I simply set varchar length to 65536, will it be quite slow? (even if my average lengh can be quite small)

Feel safe to change the it to 256K or little longer than that. But definitely not 10M or above.

We are working on a new data type called Text, which might be suitable for data longer thant 1M
