### ISSUE TITLE
[Bug]: data recovered after removing all the data in the collection for a while

### ISSUE THREAD

**Issue by wzh28x** [milvus-io/milvus#34644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4.5
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

我通过代码把collection清空了，然后确认了collection里没数据，也没有其他操作，过了一段时间数据又回来了

**Comment by yanliang567** [comment]
thats weird, could you please share the full milvus logs for investigation? also how did you insert and cleanup the collection?
@wzh28x 
/assign @wzh28x

**Comment by yanliang567** [comment]
In case you don't know how to collection the logs: please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs
For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.

**Comment by xiaofan-luan** [comment]
how did you clean your data, can you explain what you do?

You need to run drop collection to clean the data.

**Comment by wzh28x** [comment]
> In case you don't know how to collection the logs: please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.

我没做任何操作，日志一直在更新，看不清信息
![企业微信截图_17210071167593](https://github.com/user-attachments/assets/35be2780-087b-446b-930e-67fa0da0a438)

**Comment by wzh28x** [comment]
> how did you clean your data, can you explain what you do?
> 
> You need to run drop collection to clean the data.

我用代码和attu的删除都试过，我先用代码插入了110条数据，过段时间就变成330条，然后我又清了数据，插入110条，过段时间就变成440条

**Comment by wzh28x** [comment]
> In case you don't know how to collection the logs: please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.

我释放collection后日志内容
![企业微信截图_17210103889215](https://github.com/user-attachments/assets/d8939779-62b5-4169-8a03-713f452307da)

**Comment by xiaofan-luan** [comment]
please share you code to insert and how you delete.

also the full log.

Otherwise we will not be able to help

**Comment by xiaofan-luan** [comment]
your collection is not even loaded, not sure did you read the quickstart carefully and implement hello milvus

**Comment by wzh28x** [comment]
> please share you code to insert and how you delete.
> 
> also the full log.
> 
> Otherwise we will not be able to help
这是插入的代码
    client = MilvusClient(
        uri="",
        db_name=""
    )
    client.load_collection(collection_name="")
    mr = client.insert(collection_name="", data=data) 
    client.release_collection(collection_name="") 
    client.close()

这是清空collection的代码，我也使用过attu进行清空collection
    client = MilvusClient(
        uri="",
        db_name=""
    )
    res = client.delete(
        collection_name="",
        filter="id != ''",
    )

**Comment by yanliang567** [comment]
@wzh28x i have a guess, before that could you please also share the code how you check the entity_numbers

**Comment by wzh28x** [comment]
> i have a guess, before that could you please also share the code how you check the entity_numbers

我没有检查entity_numbers的代码，我是通过attu查看的collection数据的数量，而且我通过代码查询数据时也发现数据重复的问题

**Comment by yanliang567** [comment]
> > i have a guess, before that could you please also share the code how you check the entity_numbers
> 
> 我没有检查entity_numbers的代码，我是通过attu查看的collection数据的数量，而且我通过代码查询数据时也发现数据重复的问题

okay, how many databases did you create in the milvus?  could you please offer full logs for investigation?

**Comment by wzh28x** [comment]
> > > i have a guess, before that could you please also share the code how you check the entity_numbers
> > 
> > 
> > 我没有检查entity_numbers的代码，我是通过attu查看的collection数据的数量，而且我通过代码查询数据时也发现数据重复的问题
> 
> okay, how many databases did you create in the milvus? could you please offer full logs for investigation?

三个，有没有设置让日志不要一直刷，我没有操作也在一直刷，不方便查看我要找的内容

**Comment by yanliang567** [comment]
I still fail to reproduce this issue, I think you have to offer full milvus logs to us.

**Comment by yanliang567** [comment]
@wzh28x please send me the full milvus logs or your email/wechat to my mail(yanliang.qiao@zilliz.com) for further discussion about the issue.

**Comment by yanliang567** [comment]
we have fixed an occasional issue for deletion in milvus 2.4.8, please retry if you met this issue.

**Comment by yanliang567** [comment]
not receive new reports for this issue. i'd close this issue after talking to @wzh28x , if it reproduced to anyone, please help to attach the milvus logs for investigation.
