### ISSUE TITLE
[Bug]: policy related metadataCache got removed and lead to permission denied errors

### ISSUE THREAD

**Issue by balloon1995** [milvus-io/milvus#34667]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.5
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

com.paypal.dataprocessing.search.pojo.VectorSearchRequest@12ea29c5&io.grpc.StatusRuntimeException: PERMISSION_DENIED: PrivilegeSearch: permission deny to xxxx at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:268) at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:249) at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:167) at io.milvus.grpc.MilvusServiceGrpc$MilvusServiceBlockingStub.search(MilvusServiceGrpc.java:4217) at io.milvus.client.AbstractMilvusGrpcClient.search(AbstractMilvusGrpcClient.java:1596) at com.paypal.vector.milvus.client.TlsMilvusServiceClient.lambda$search$35(TlsMilvusServiceClient.java:477) at com.paypal.vector.milvus.client.TlsMilvusServiceClient.retry(TlsMilvusServiceClient.java:226) at com.paypal.vector.milvus.client.TlsMilvusServiceClient.search(TlsMilvusServiceClient.java:477) at com.paypal.vector.milvus.client.MilvusServiceDRClient.search(MilvusServiceDRClient.java:305) at com.paypal.vector.milvus.utils.MilvusUtils.searchVector(MilvusUtils.java:284) at com.paypal.dataprocessing.search.service.VectorSearchService.doSearch(VectorSearchService.java:135) at com.paypal.dataprocessing.search.impl.VectorSearchControllerImpl.vectorSearch(VectorSearchControllerImpl.java:69) at jdk.internal.reflect.GeneratedMethodAccessor173.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170) at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130) at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660) at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524) at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)### 

### Expected Behavior

keep previous metadataCache instead of removing it when the response is invalid

### Milvus Log

[2024/07/04 00:59:56.173 +00:00] [INFO] [proxy/privilege_interceptor.go:176] ["permission deny"] [username=xxxx] [role_names="[public]"] [object_type=Collection] [object_privilege=PrivilegeLoad] [db_name=default] [object_index=2] [object_name=xxxxxxxx] [object_indexs=0] [object_names="[]"] [roles="[public]"]
....

**Comment by yanliang567** [comment]
/assign @congqixia 
please help to review the issue and pr, thanks
/unassign

**Comment by SimFG** [comment]
@xiaofan-luan ok, i will check it.
