### ISSUE TITLE
[Bug]: l0 compaction saveSegmentMeta may lost set segments

### ISSUE THREAD

**Issue by wayblink** [milvus-io/milvus#34681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

l0 compaction saveSegmentMeta may lost set segments because get from plan. Plan may be nil if datacoord crash and restart at this time.

### Expected Behavior

use task.InputSegments instead

**Comment by yanliang567** [comment]
/assign @wayblink 
/unassign

does this reproduce to 2.4 branch
