### ISSUE TITLE
[Bug]: [major] The datanode is continously restarted for OOM after major compaction for 50M (768) dataset

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#34703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4-latest
- Deployment mode(standalone or cluster):both
- MQ type(rocksmq, pulsar or kafka):    all
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-latest
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The datanode is continously restarted for OOM after major compaction for 50M (768) dataset

### Expected Behavior

No crash

### Steps To Reproduce

```markdown
1. create collection with partition key enabled (partition key as clustering key)
2. insert 50M (768)
3. major compaction
```

**Comment by xiaocai2333** [comment]
The failure to reset the `flushedRowNum` of the writerBuffer resulted in subsequent segments in this buffer continually meeting the pack conditions, leading to the creation of numerous segments. The datanode couldn't load the BloomFilters for so many segments, causing an OOM error.

**Comment by binbinlv** [comment]
The OOM issue still exists when major compaction on 50M (768) data:
image: v2.4.6-nightly-176034d1-872

**Comment by xiaocai2333** [comment]
/unassign
/assign @binbinlv 
maybe  it can be closed?

**Comment by binbinlv** [comment]
it is fixed in the previous image.
