### ISSUE TITLE
[Bug]: The version in the log is not v2.3.19 after v2.3.19 image installed

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#34706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.3.19
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    all
- SDK version(e.g. pymilvus v2.0.0rc2): v2.3.7
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The version in the log is not v2.3.19 after v2.3.19 image installed

```

2024-07-16 11:37:18.291 | GoVersion: go version go1.20.7 linux/amd64 |  
-- | -- | --
  |   | 2024-07-16 11:37:18.291 | GitCommit: 64dc848 |  
  |   | 2024-07-16 11:37:18.291 | Built:     Mon Jul 15 08:59:58 UTC 2024 |  
  |   | 2024-07-16 11:37:18.291 | Version:   64dc848 |  
  |   | 2024-07-16 11:37:18.291 | Welcome to use Milvus! |  
  |   | 2024-07-16 11:37:18.291 |   |  
  |   | 2024-07-16 11:37:18.291 | /_/  /_/___/____/___/\____/___/ |  
  |   | 2024-07-16 11:37:18.291 | / /\|_/ // // /_\| \|/ / /_/ /\ \ |  
  |   | 2024-07-16 11:37:18.291 | /  \|/  /  _/ /\| \| / / / / / __/ |  
  |   | 2024-07-16 11:37:18.291 | __  _________ _   ____  ______


```

### Expected Behavior

The version in the log is v2.3.19 after v2.3.19 image installed

### Steps To Reproduce

```markdown
1. install milvus using v2.3.19 image
2. check log
```

### Milvus Log

https://grafana-4am.zilliz.cc/explore?orgId=1&panes=%7B%22ELK%22:%7B%22datasource%22:%22vhI6Vw67k%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcluster%3D%5C%22devops%5C%22,namespace%3D%5C%22chaos-testing%5C%22,pod%3D~%5C%22release-check-mogcv.%2A%5C%22%7D%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22vhI6Vw67k%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1

**Comment by yellow-shine** [comment]
fixed
