### ISSUE TITLE
[Bug]: index type not match: invalid parameter[expected=STL_SORT][actual=Ascending]

### ISSUE THREAD

**Issue by xige-16** [milvus-io/milvus#34707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

[2024/07/03 13:03:20.074 +00:00] [ERROR] [core/backup_impl_restore_backup.go:357]
["executeRestoreCollectionTask failed"] [TargetDBName=default] [TargetCollectionName=retrieve]
[error="index type not match: invalid parameter[expected=STL_SORT][actual=Ascending]"]
[errorVerbose="index type not match: invalid parameter[expected=STL_SORT][actual=Ascending]\n(1) attached stack trace\n -- stack trace:\n
| github.com/milvus-io/milvus-sdk-go/v2/client.handleRespStatus\n
| \t/go/pkg/mod/github.com/wayblink/milvus-sdk-go/[v2@v2.3.0-beta4.0.20240607085051-1ac5aaf24c6d](mailto:v2@v2.3.0-beta4.0.20240607085051-1ac5aaf24c6d)/client/collection.go:39\n
| github.com/milvus-io/milvus-sdk-go/v2/client.(*GrpcClient).CreateIndex\n
| \t/go/pkg/mod/github.com/wayblink/milvus-sdk-go/[v2@v2.3.0-beta4.0.20240607085051-1ac5aaf24c6d](mailto:v2@v2.3.0-beta4.0.20240607085051-1ac5aaf24c6d)/client/index.go:132\n
| github.com/zilliztech/milvus-backup/core.(*MilvusClient).CreateIndex\n
| \t/app/core/milvus_sdk_wrapper.go:186\n
| github.com/zilliztech/milvus-backup/core.(*BackupContext).executeRestoreCollectionTask\n
| \t/app/core/backup_impl_restore_backup.go:541\n
| github.com/zilliztech/milvus-backup/core.(*BackupContext).executeRestoreBackupTask.func1\n
| \t/app/core/backup_impl_restore_backup.go:355\n
| github.com/zilliztech/milvus-backup/internal/common.(*WorkerPool).work.func1\n
| \t/app/internal/common/workerpool.go:70\n
| golang.org/x/sync/errgroup.(*Group).Go.func1\n
| \t/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75\n
| runtime.goexit\n
| \t/usr/local/go/src/runtime/asm_amd64.s:1571

\nWraps: (2) index type not match: invalid parameter[expected=STL_SORT][actual=Ascending]\nError types: (1) *withstack.withStack (2) *errutil.leafError"] [stack="
github.com/zilliztech/milvus-backup/core.(*BackupContext).executeRestoreBackupTask.func1\n\t
/app/core/backup_impl_restore_backup.go:357\n
github.com/zilliztech/milvus-backup/internal/common.(*WorkerPool).work.func1\n\t/app/internal/common/workerpool.go:70\n
golang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75"]

**Comment by xige-16** [comment]
link issue: https://github.com/milvus-io/milvus/issues/27187
fix pr has typos

**Comment by yanliang567** [comment]
/assign @czs007 
please help to review the pr
/unassign
