### ISSUE TITLE
[Bug]: GrowingRawData of test groupby failed

### ISSUE THREAD

**Issue by zhagnlu** [milvus-io/milvus#34713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

TEST(GroupBY, GrowingRawData) failed

**Comment by zhagnlu** [comment]
@MrPresent-Han

**Comment by zhagnlu** [comment]
related with: #34586

**Comment by MrPresent-Han** [comment]
I will handle this

**Comment by MrPresent-Han** [comment]
has found the cause, a bug I introduced last week
