### ISSUE TITLE
[Bug]: metric type not correctly propagated to knowhere when using group by

### ISSUE THREAD

**Issue by zhengbuqian** [milvus-io/milvus#34730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when using groupby, even if we have set metric type to other metrics in SDK, knowhere will always see L2.

**Comment by zhengbuqian** [comment]
this is currently blocking #34700.

**Comment by xiaofan-luan** [comment]
do we need to backport to 2.3?

**Comment by zhengbuqian** [comment]
> do we need to backport to 2.3?

No we don't. Usage of KW Iterator and GroupBy is introduced in 2.4
