### ISSUE TITLE
[Bug]: Devcontainer definition is no longer valid

### ISSUE THREAD

**Issue by timheuer** [milvus-io/milvus#34742]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Opening the devcontainer in VSCode fails as the docker-compose file is non existent

### Expected Behavior

I should be able to use VSCode to open as devcontainer. It fails

### Steps To Reproduce

1. Clone repo
2. Open repo in VSCode
3. Accept prompt to open in container using .devcontainer.json file definition
FAIL

**Comment by yanliang567** [comment]
@timheuer is this something you are looking for? https://github.com/milvus-io/milvus/blob/master/build/README.md, what error msg did you get?
/assign @timheuer

**Comment by timheuer** [comment]
@yanliang567 no not exactly. The `.devcontainer.json` (https://github.com/milvus-io/milvus/blob/master/.devcontainer.json)  file included includes a reference to a docker compose file that does not exist: https://github.com/milvus-io/milvus/blob/4939f82d4f4e9bd0be1dc8f1e2410b2499a66f38/.devcontainer.json#L3

Because of this when VSCode tries to open the repo using the devcontainer definition it fails because the definition isn't valid anymore. I'm not sure if this devcontainer definition has been explored for a while (as it looks 3 years old) but other things look wrong too (workspace path to /go/src/...)

**Comment by yanliang567** [comment]
/assign @czs007 
any ideas about this?
/unassign
