### ISSUE TITLE
[Bug]: milvusdb/milvus:v2.4.6-gpu do not support gpu index

### ISSUE THREAD

**Issue by Wiley-Z** [milvus-io/milvus#34747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4.6
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus v2.4.3
- OS(Ubuntu or CentOS): Ubuntu 22.04
- CPU/Memory: 
- GPU: A100
- Others: deployed via docker compose
```

### Current Behavior

I updated milvus-standalone image from v2.4.5-gpu to v2.4.6-gpu, as I encountered similar problem with https://github.com/milvus-io/milvus/issues/34416. milvus-standalone no longer exited.
However, when creating gpu index it throw an error that `failed to create index, C Runtime Exception: index not supported
: segcore unsupported error[segcoreCode=2003]`. The same index had been created successfully using v2.4.5-gpu.
Also, I noticed that the SIZE of v2.4.6-gpu is 3.97GB while v2.4.5-gpu is 5.12GB. Is there something missing in the lastest gpu image?

### Milvus Log

milvus-standalone  | [2024/07/17 03:41:23.000 +00:00] [INFO] [datacoord/index_service.go:682] ["receive DescribeIndex request"] [traceID=fdc1f4d362c132fb10a70f18d0624730] [collectionID=450727100544144323] [indexName=] [timestamp=0]
milvus-standalone  | [2024/07/17 03:41:23.000 +00:00] [INFO] [datacoord/index_service.go:603] ["completeIndexInfo success"] [collectionID=450727100544144323] [indexID=450727100547094867] [totalRows=2941080] [indexRows=2941080] [pendingIndexRows=0] [state=Finished] [failReason=]
milvus-standalone  | [2024/07/17 03:41:23.000 +00:00] [INFO] [datacoord/index_service.go:603] ["completeIndexInfo success"] [collectionID=450727100544144323] [indexID=451198684209087671] [totalRows=2941080] [indexRows=0] [pendingIndexRows=2941080] [state=Failed] [failReason="450769781926134430: failed to create index, C Runtime Exception: index not supported\n: segcore unsupported error[segcoreCode=2003];450751514745766776: failed to create index, C Runtime Exception: index not supported\n: segcore unsupported error[segcoreCode=2003];450751514745766350: failed to create index, C Runtime Exception: index not supported\n: segcore unsupported error[segcoreCode=2003];450769781926134103: failed to create index, C Runtime Exception: index not supported\n: segcore unsupported error[segcoreCode=2003];450769781926134104: failed to create index, C Runtime Exception: index not supported\n: segcore unsupported error[segcoreCode=2003];450751514745766556: failed to create index, C Runtime Exception: index not supported\n: segcore unsupported error[segcoreCode=2003];"]
milvus-standalone  | [2024/07/17 03:41:23.000 +00:00] [INFO] [datacoord/index_service.go:730] ["DescribeIndex success"] [traceID=fdc1f4d362c132fb10a70f18d0624730] [collectionID=450727100544144323] [indexName=]

### Anything else?

I've tried to compile milvus and build image for v2.4.5-gpu, it works fine besides the same problem encountered that `index not supported` when creating gpu index. And the size is 3.88GB, very close to the official v2.4.6-gpu image which is 3.97GB, but much less to 5.12GB. So I was wondering that if the same problem occured.
My aim is to change the gpu top-k quota btw, I've changed the regular top-k limit but I couldn't find the param for gpu limit. Could you please help me with that? Thank you!

**Comment by yanliang567** [comment]
/assign @Presburger 
please help to take a look

/unassign

**Comment by Wiley-Z** [comment]
I tried to build image for v2.4.5 with lib that `docker cp` from milvusdb/milvus:v2.4.5-gpu, and it seems working and has the same size with official image. image built with lib from `builder_gpu.sh make install` failed building gpu index as well as milvusdb/milvus:v2.4.6-gpu did.

**Comment by Presburger** [comment]
@Wiley-Z Hello, are you saying that the 2.4.6 image encounters an issue with index creation failure? Could you please provide the name of the index you created and its parameters? I will test it out.

**Comment by Wiley-Z** [comment]
> @Wiley-Z Hello, are you saying that the 2.4.6 image encounters an issue with index creation failure? Could you please provide the name of the index you created and its parameters? I will test it out.

`index_params = MilvusClient.prepare_index_params()

index_params.add_index(
    field_name="embedding",
    metric_type="IP",
    index_type="GPU_IVF_PQ",
    index_name="embedding_gpu_ivf65536_pq96",
    params={ "nlist": 65536, "m": 96, "nbits": 8 }
)

client.create_index(
    collection_name="test",
    index_params=index_params
)`

**Comment by xiaofan-luan** [comment]
1. how did you compile? what changes did you made?
2. why there isn't a config for topk change? I don't think it nede to rebuild to upgrade 
3. we need detailed logs for why index is not supported, please offer full log

**Comment by Wiley-Z** [comment]
> 1. how did you compile? what changes did you made?
> 2. why there isn't a config for topk change? I don't think it nede to rebuild to upgrade
> 3. we need detailed logs for why index is not supported, please offer full log

1. by `./build/builder_gpu.sh make install`. I changed some numbers in pkg/util/paramtable/quota_param.go, quotaAndLimits.limits.topK. some other changes are for network or docker version. you can see https://github.com/Wiley-Z/milvus/commit/f2a03a8cfabaad34447da3c9e7b991e07cbea66c#diff-ab50761ed71e005a6f6c56997a5b55b6361b280e8b9a397c8a4f8bd213a31bbf for all the changes from v2.4.5.
2. I need more topk results than the limit 16384, or 1024 for gpu. for now, I think the topk limit is hard coded in milvus while gpu limit is in knowhere, is there a config file to change the settings?
3. I've realized that I should use `./build/builder_gpu.sh make gpu-install` instead, and successfully compiled usable gpu version yesterday. but now I can't repetite the building process as I've been stucked here for a while, for both v2.4.5 and master. Is there something no longer supported in conan?
![image](https://github.com/user-attachments/assets/ad0b88b5-9ac1-42e3-9744-b699821916f3)

**Comment by xiaofan-luan** [comment]
> * I've realized that I should use `./build/builder_gpu.sh make gpu-install` instead, and successfully compiled usable gpu version yesterday. but now I can't repetite the building process as I've been stucked here for a while, for both v2.4.5 and master. Is there something no longer supported in conan?

1. the topk limit is not on milvus side, but GPU index itself.
2. if you do need larger topk , think of using IVF index or GPU FLAT index, Cagra is a graph index and has a limitation of 1024.
3. this is a compile issue and we'll be working on it, sty tuned

**Comment by Wiley-Z** [comment]
> 1\. the topk limit is not on milvus side, but GPU index itself.

Yes, I believe this limit is coded in knowhere, so I can change it when milvus compile 3rd party dependencies.

> 3\. this is a compile issue and we'll be working on it, sty tuned

Thank you for the info. I am looking forward to updating.

> 2\. if you do need larger topk , think of using IVF index or GPU FLAT index, Cagra is a graph index and has a limitation of 1024.

I was using GPU_IVF_PQ, it has a topk limitation 1024 too. I think GPU_BRUTE_FORCE is not suitable for a vector dataset can't fit in GPU mem. So IVF(_PQ) on cpu is recommended, right?

**Comment by Presburger** [comment]
@Wiley-Z  hi, The support for GPU indexing and the limitations on top-k is not merely a hardcoded restriction. This is because the on-chip cache of GPUs is limited, and an excessively large top-k can directly cause the milvus to crash. If you need to handle a very large top-k, I suggest trying to partition your data into multiple databases and then aggregate the results from each database.

**Comment by Presburger** [comment]
@Wiley-Z We apologize for the issue. The devops team recently adjusted the packaging strategy, which caused problems with the 2.4.6-gpu image. docker pull the images from docker hub renew, this problem has fixed.
