### ISSUE TITLE
[Bug]: sparse index's Train

### ISSUE THREAD

**Issue by ldak4747** [milvus-io/milvus#34753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
https://github.com/zilliztech/knowhere.git，main分支
```

### Current Behavior

在InvertedIndex::Train中，首先算出全部样本的，非零维的计数总和amount，然后"std::vector<T> vals(amount);"构造vals数组，数组容量是amount，也就是数组前amount成员值都是0。
然后将全部样本的非零维的值，追加到数组vals，也就是vals长度为2*amount，前amount为0，后amount为非0值。
再通过std::nth_element寻找vals的全部成员中，第drop_ratio_build小的，这个很容易就是0。
请问这是符合预期的么？

**Comment by yanliang567** [comment]
/assign @liliu-z 
please give a hand on this 
/unassign

**Comment by ldak4747** [comment]
您这边还没有反馈～

**Comment by zhengbuqian** [comment]
您好，这的确是不符合预期的，本意是`std::vector vals; vals.reserve(amount)`。现在的实现会导致少于`drop_ratio_build`的小值被丢弃，导致精度偏高，性能偏低。

感谢反馈！我会尽快提交一个fix https://github.com/zilliztech/knowhere/issues/720。

**Comment by yanliang567** [comment]
@zhengbuqian was this fix in mivlus 2.4.9?
