### ISSUE TITLE
[Bug]: compaction task not be cleaned correctly

### ISSUE THREAD

**Issue by wayblink** [milvus-io/milvus#34764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master/2.4
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

compaction task should be cleaned after finished for a certain time. But the gc doesn't work for now. It is because the wrong handling of time units.

**Comment by xiaofan-luan** [comment]
seems that this has to be in 2.4.7

**Comment by wayblink** [comment]
> seems that this has to be in 2.4.7

yes
