### ISSUE TITLE
[Bug]:  Segment lack caused by deduplicate segment task

### ISSUE THREAD

**Issue by weiliu1031** [milvus-io/milvus#34781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3/2.4/master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

when balance segment hasn't finished yet, query coord may found 2 loaded copy of segment, then it will generate task to deduplicate, which may cancel the balance task. then the old copy has been released, and the new copy hasn't be ready yet but canceled, then search failed by segment lack.

**Comment by xiaofan-luan** [comment]
I think we need report those segemnts as loading.
and if there are any segments under loading state, we should simply avoid trigger any other action
