### ISSUE TITLE
[Bug]: NULL Pointer Dereference Vulnerability

### ISSUE THREAD

**Issue by Ald392** [milvus-io/milvus#34835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Static Scan reported [NULL Pointer Dereference Vulnerability](https://cwe.mitre.org/data/definitions/476.html) due to the following lines : 

- https://github.com/milvus-io/milvus/blob/e4e18cb8c38f6616c2069660d47097aa6eb4371e/internal/core/src/indexbuilder/init_c.cpp#L25
- https://github.com/milvus-io/milvus/blob/e4e18cb8c38f6616c2069660d47097aa6eb4371e/internal/core/src/log/Log.cpp#L107
- https://github.com/milvus-io/milvus/blob/e4e18cb8c38f6616c2069660d47097aa6eb4371e/internal/core/src/segcore/metrics_c.cpp#L21
- https://github.com/milvus-io/milvus/blob/e4e18cb8c38f6616c2069660d47097aa6eb4371e/internal/core/src/segcore/segcore_init_c.cpp#L76

**Comment by yanliang567** [comment]
/assign @congqixia 
please help to review the pr
/unassign

**Comment by Ald392** [comment]
@congqixia Can you please look into PR: https://github.com/milvus-io/milvus/pull/34836
