### ISSUE TITLE
[Bug]: RSS memory too high in datanode when continuously create collections and insert data

### ISSUE THREAD

**Issue by cqy123456** [milvus-io/milvus#34844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.x
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- OS(Ubuntu or CentOS): Ubuntu
```

### Current Behavior

Client continuously create collections and insert data, and not call flush api:
<img width="456" alt="image" src="https://github.com/user-attachments/assets/d57af333-bae5-4661-addd-6c7393a8a022">
datanode: rss memory keep on increasing
<img width="1413" alt="image" src="https://github.com/user-attachments/assets/3b965134-f3a4-4b50-8389-07a1605663b4">
https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&from=1721027730327&to=1721216990618&var-datasource=P1809F7CD0C75ACF3&var-cluster=&var-namespace=qa-milvus&var-instance=fouramf-crr4p-73-9070&var-collection=All&var-app_name=milvus&viewPanel=123133

### Steps To Reproduce

```markdown
1. cluster info:
fouramf-v845w-63-6466-etcd-0                                      1/1     Running       0                20m     10.104.34.68    4am-node37   <none>           <none>
fouramf-v845w-63-6466-etcd-1                                      1/1     Running       0                20m     10.104.20.235   4am-node22   <none>           <none>
fouramf-v845w-63-6466-etcd-2                                      1/1     Running       0                20m     10.104.19.12    4am-node28   <none>           <none>
fouramf-v845w-63-6466-milvus-datacoord-54954c9576-lsjbp           1/1     Running       3 (19m ago)      20m     10.104.9.105    4am-node14   <none>           <none>
fouramf-v845w-63-6466-milvus-datanode-7db9fd4cbd-8wwbv            1/1     Running       0                10m     10.104.1.108    4am-node10   <none>           <none>
fouramf-v845w-63-6466-milvus-indexcoord-5c7b4fd9f-6vrfx           1/1     Running       0                20m     10.104.14.49    4am-node18   <none>           <none>
fouramf-v845w-63-6466-milvus-indexnode-cdf766768-m8vk2            1/1     Running       3 (19m ago)      20m     10.104.9.104    4am-node14   <none>           <none>
fouramf-v845w-63-6466-milvus-proxy-78bb884b8-xtxd9                1/1     Running       0                10m     10.104.1.104    4am-node10   <none>           <none>
fouramf-v845w-63-6466-milvus-querycoord-5ff4bf8bf6-l248g          1/1     Running       4 (15m ago)      20m     10.104.33.201   4am-node36   <none>           <none>
fouramf-v845w-63-6466-milvus-querynode-59d9595f8f-w2gbw           1/1     Running       0                10m     10.104.34.103   4am-node37   <none>           <none>
fouramf-v845w-63-6466-milvus-rootcoord-8487c944d8-tcmhs           1/1     Running       3 (19m ago)      20m     10.104.14.48    4am-node18   <none>           <none>
fouramf-v845w-63-6466-minio-0                                     1/1     Running       0                20m     10.104.34.67    4am-node37   <none>           <none>
fouramf-v845w-63-6466-minio-1                                     1/1     Running       0                20m     10.104.19.11    4am-node28   <none>           <none>
fouramf-v845w-63-6466-minio-2                                     1/1     Running       0                20m     10.104.20.236   4am-node22   <none>           <none>
fouramf-v845w-63-6466-minio-3                                     1/1     Running       0                20m     10.104.18.157   4am-node25   <none>           <none>
fouramf-v845w-63-6466-pulsar-bookie-0                             1/1     Running       0                20m     10.104.34.70    4am-node37   <none>           <none>
fouramf-v845w-63-6466-pulsar-bookie-1                             1/1     Running       0                20m     10.104.19.16    4am-node28   <none>           <none>
fouramf-v845w-63-6466-pulsar-bookie-2                             1/1     Running       0                20m     10.104.32.86    4am-node39   <none>           <none>
fouramf-v845w-63-6466-pulsar-bookie-init-7sdj8                    0/1     Completed     0                20m     10.104.14.46    4am-node18   <none>           <none>
fouramf-v845w-63-6466-pulsar-broker-0                             1/1     Running       0                20m     10.104.4.165    4am-node11   <none>           <none>
fouramf-v845w-63-6466-pulsar-proxy-0                              1/1     Running       0                20m     10.104.13.193   4am-node16   <none>           <none>
fouramf-v845w-63-6466-pulsar-pulsar-init-45fxk                    0/1     Completed     0                20m     10.104.34.60    4am-node37   <none>           <none>
fouramf-v845w-63-6466-pulsar-recovery-0                           1/1     Running       0                20m     10.104.20.231   4am-node22   <none>           <none>
fouramf-v845w-63-6466-pulsar-zookeeper-0                          1/1     Running       0                20m     10.104.19.10    4am-node28   <none>           <none>
fouramf-v845w-63-6466-pulsar-zookeeper-1                          1/1     Running       0                20m     10.104.30.142   4am-node38   <none>           <none>
fouramf-v845w-63-6466-pulsar-zookeeper-2                          1/1     Running       0                19m     10.104.23.207   4am-node27   <none>           <none>

2. Milvus config info:
 maxCollectionNum: 65534
 maxShardNum: 1024
 maxGeneralCapacity: 65536
 rootCoord.dmlChannelNum: 16
 queryNode.segcore.interimIndex.enableIndex: false
```

**Comment by yanliang567** [comment]
seems to be expected, as there are 4.8k growing segments, and they are small, so they gonna be sealed only after maxLife(24h). @congqixia  please help to confirm

/assign @congqixia 
/unassign

**Comment by elstic** [comment]
> seems to be expected, as there are 4.8k growing segments, and they are small, so they gonna be sealed only after maxLife(24h). @congqixia please help to confirm
> 
> /assign @congqixia /unassign

Maybe not, here the segment has been converted to sealed, but the datanode memory hasn't dropped.
![img_v3_02cu_e0d9c1de-8db7-4f3e-8af6-800613f0a7bg](https://github.com/user-attachments/assets/797cc92f-9f29-4e13-8915-73b40a564913)

![img_v3_02cu_5f67ee6e-e203-4b2c-b39a-feeb8027e9dg](https://github.com/user-attachments/assets/eca00f3f-ff6f-4350-a031-5e8a0365c3c7)

**Comment by xiaofan-luan** [comment]
this is most likes occupied by Bloom filters

**Comment by xiaofan-luan** [comment]
@bigsheeper  is working on remove bf on datanodes(only used when compaction happpened)

**Comment by cqy123456** [comment]
but all segments is growing segment in this case

**Comment by elstic** [comment]
I think the datanode memory not dropping is also related to the mq, when I use kafka as the mq , after about ten minutes, the datanode memory is also dropping. 
![image](https://github.com/user-attachments/assets/0f33b59a-ab2a-4645-abd5-517124446e56)

4am cluster:
```
fouramf-8rg7d-20-6143-etcd-0                                      1/1     Running            0                 46m     10.104.21.245   4am-node24   <none>           <none>
fouramf-8rg7d-20-6143-etcd-1                                      1/1     Running            0                 46m     10.104.15.242   4am-node20   <none>           <none>
fouramf-8rg7d-20-6143-etcd-2                                      1/1     Running            0                 46m     10.104.19.55    4am-node28   <none>           <none>
fouramf-8rg7d-20-6143-kafka-0                                     1/1     Running            2 (45m ago)       46m     10.104.19.52    4am-node28   <none>           <none>
fouramf-8rg7d-20-6143-kafka-1                                     1/1     Running            2 (45m ago)       46m     10.104.21.248   4am-node24   <none>           <none>
fouramf-8rg7d-20-6143-kafka-2                                     1/1     Running            2 (45m ago)       46m     10.104.15.246   4am-node20   <none>           <none>
fouramf-8rg7d-20-6143-milvus-datacoord-54bbd6744b-k2m57           1/1     Running            3 (45m ago)       46m     10.104.6.70     4am-node13   <none>           <none>
fouramf-8rg7d-20-6143-milvus-datanode-84d7669485-zc25p            1/1     Running            3 (45m ago)       46m     10.104.26.175   4am-node32   <none>           <none>
fouramf-8rg7d-20-6143-milvus-indexcoord-fb7b94d69-pjw74           1/1     Running            0                 46m     10.104.9.22     4am-node14   <none>           <none>
fouramf-8rg7d-20-6143-milvus-indexnode-59757d5d5d-56rs9           1/1     Running            3 (45m ago)       46m     10.104.9.24     4am-node14   <none>           <none>
fouramf-8rg7d-20-6143-milvus-proxy-6b67b58845-5p2cq               1/1     Running            3 (45m ago)       46m     10.104.9.23     4am-node14   <none>           <none>
fouramf-8rg7d-20-6143-milvus-querycoord-5b8dc56c8-jx7q5           1/1     Running            3 (45m ago)       46m     10.104.6.69     4am-node13   <none>           <none>
fouramf-8rg7d-20-6143-milvus-querynode-79bc897964-296lp           1/1     Running            3 (45m ago)       46m     10.104.4.224    4am-node11   <none>           <none>
fouramf-8rg7d-20-6143-milvus-rootcoord-567c68b578-fd9pd           1/1     Running            3 (45m ago)       46m     10.104.6.74     4am-node13   <none>           <none>
fouramf-8rg7d-20-6143-minio-0                                     1/1     Running            0                 46m     10.104.19.51    4am-node28   <none>           <none>
fouramf-8rg7d-20-6143-minio-1                                     1/1     Running            0                 46m     10.104.20.222   4am-node22   <none>           <none>
fouramf-8rg7d-20-6143-minio-2                                     1/1     Running            0                 46m     10.104.15.243   4am-node20   <none>           <none>
fouramf-8rg7d-20-6143-minio-3                                     1/1     Running            0                 46m     10.104.21.251   4am-node24   <none>           <none>
fouramf-8rg7d-20-6143-zookeeper-0                                 1/1     Running            0                 46m     10.104.20.221   4am-node22   <none>           <none>
fouramf-8rg7d-20-6143-zookeeper-1                                 1/1     Running            0                 46m     10.104.19.53    4am-node28   <none>           <none>
fouramf-8rg7d-20-6143-zookeeper-2                                 1/1     Running            0                 46m     10.104.21.252   4am-node24   <none>           <none>
```

Test Steps:
1. create 200 collections and insert 10,000 pieces of data into each collection
2. do nothing

**Comment by xiaofan-luan** [comment]
> I think the datanode memory not dropping is also related to the mq, when I use kafka as the mq , after about ten minutes, the datanode memory is also dropping. ![image](https://private-user-images.githubusercontent.com/48523564/352484830-0f33b59a-ab2a-4645-abd5-517124446e56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNzE5MjQsIm5iZiI6MTcyMjA3MTYyNCwicGF0aCI6Ii80ODUyMzU2NC8zNTI0ODQ4MzAtMGYzM2I1OWEtYWIyYS00NjQ1LWFiZDUtNTE3MTI0NDQ2ZTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDA5MTM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMTk4YzI3NTA3YzIxYWNlMGJlMmJlNzMzYmRlYzUxYmVlNDAyMDA1ODBmYjMzZmE0OTlmYzAxYjUyM2RhNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EAeKy4Ve9_FplLWmi-INSDaF1aDDIS8nxVzhlroA-mE)
> 
> 4am cluster:
> 
> ```
> fouramf-8rg7d-20-6143-etcd-0                                      1/1     Running            0                 46m     10.104.21.245   4am-node24   <none>           <none>
> fouramf-8rg7d-20-6143-etcd-1                                      1/1     Running            0                 46m     10.104.15.242   4am-node20   <none>           <none>
> fouramf-8rg7d-20-6143-etcd-2                                      1/1     Running            0                 46m     10.104.19.55    4am-node28   <none>           <none>
> fouramf-8rg7d-20-6143-kafka-0                                     1/1     Running            2 (45m ago)       46m     10.104.19.52    4am-node28   <none>           <none>
> fouramf-8rg7d-20-6143-kafka-1                                     1/1     Running            2 (45m ago)       46m     10.104.21.248   4am-node24   <none>           <none>
> fouramf-8rg7d-20-6143-kafka-2                                     1/1     Running            2 (45m ago)       46m     10.104.15.246   4am-node20   <none>           <none>
> fouramf-8rg7d-20-6143-milvus-datacoord-54bbd6744b-k2m57           1/1     Running            3 (45m ago)       46m     10.104.6.70     4am-node13   <none>           <none>
> fouramf-8rg7d-20-6143-milvus-datanode-84d7669485-zc25p            1/1     Running            3 (45m ago)       46m     10.104.26.175   4am-node32   <none>           <none>
> fouramf-8rg7d-20-6143-milvus-indexcoord-fb7b94d69-pjw74           1/1     Running            0                 46m     10.104.9.22     4am-node14   <none>           <none>
> fouramf-8rg7d-20-6143-milvus-indexnode-59757d5d5d-56rs9           1/1     Running            3 (45m ago)       46m     10.104.9.24     4am-node14   <none>           <none>
> fouramf-8rg7d-20-6143-milvus-proxy-6b67b58845-5p2cq               1/1     Running            3 (45m ago)       46m     10.104.9.23     4am-node14   <none>           <none>
> fouramf-8rg7d-20-6143-milvus-querycoord-5b8dc56c8-jx7q5           1/1     Running            3 (45m ago)       46m     10.104.6.69     4am-node13   <none>           <none>
> fouramf-8rg7d-20-6143-milvus-querynode-79bc897964-296lp           1/1     Running            3 (45m ago)       46m     10.104.4.224    4am-node11   <none>           <none>
> fouramf-8rg7d-20-6143-milvus-rootcoord-567c68b578-fd9pd           1/1     Running            3 (45m ago)       46m     10.104.6.74     4am-node13   <none>           <none>
> fouramf-8rg7d-20-6143-minio-0                                     1/1     Running            0                 46m     10.104.19.51    4am-node28   <none>           <none>
> fouramf-8rg7d-20-6143-minio-1                                     1/1     Running            0                 46m     10.104.20.222   4am-node22   <none>           <none>
> fouramf-8rg7d-20-6143-minio-2                                     1/1     Running            0                 46m     10.104.15.243   4am-node20   <none>           <none>
> fouramf-8rg7d-20-6143-minio-3                                     1/1     Running            0                 46m     10.104.21.251   4am-node24   <none>           <none>
> fouramf-8rg7d-20-6143-zookeeper-0                                 1/1     Running            0                 46m     10.104.20.221   4am-node22   <none>           <none>
> fouramf-8rg7d-20-6143-zookeeper-1                                 1/1     Running            0                 46m     10.104.19.53    4am-node28   <none>           <none>
> fouramf-8rg7d-20-6143-zookeeper-2                                 1/1     Running            0                 46m     10.104.21.252   4am-node24   <none>           <none>
> ```
> 
> Test Steps:
> 
> 1. create 200 collections and insert 10,000 pieces of data into each collection
> 2. do nothing

10 minutes seems to be the flush interval?
