### ISSUE TITLE
[Bug]: `milvus_proxy_insert_vectors_count` is missing in the monitor metrics

### ISSUE THREAD

**Issue by secsilm** [milvus-io/milvus#34897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.4.5
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.4.4
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: None
- Others:
```

### Current Behavior

We want to monitor the insertion rate. According to the [documentation](https://milvus.io/docs/metrics_dashboard.md), there is a `milvus_proxy_insert_vectors_count` metric, but it is not available on the `/metrics` page.

**Comment by xiaofan-luan** [comment]
I thought there is one in the latest milvus v2 graphna.

**Comment by xiaofan-luan** [comment]
on proxy metrics

**Comment by yanliang567** [comment]
/assign @LoveEachDay 
could you please help to double check if we need to update the config accordingly?
/unassign
