### ISSUE TITLE
[Bug]: The lower version of IndexNode cannot create vector indexes for the higher version of QueryNode

### ISSUE THREAD

**Issue by foxspy** [milvus-io/milvus#34900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

failed to create index, C Runtime Exception: Assert "knowhere::Version::VersionSupport(knowhere::Version(version))" => version not support : 5 , knowhere current version 4 at /root/milvus/internal/core/src/index/VectorIndex.h:113 : segcore error[segcoreCode=2001]

**Comment by xiaocai2333** [comment]
fixed, verify it please @foxspy 
/assign @foxspy
