### ISSUE TITLE
[Enhancement]: Can we have different weights for each collection while doing a similarity search?

### ISSUE THREAD

**Issue by ricksaha2000** [milvus-io/milvus#34905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

I had one use case that I am facing challenges on, Suppose we have "n" collections, I want to do a single similarity search on these two collections on a common vector field. Now I want to give weights to each of these collections which will bring affect to the search results. Is there anything for this type of scenarios?

### Why is this needed?

Better holistic similarity search

### Anything else?

Even if it is not a different collection, Can i get the search results on a based on weights given to different values of a
particular metadata column?

**Comment by xiaofan-luan** [comment]
So far we don't any search across multiple collections.
But maybe you can simply do it by yourself on the client side?

**Comment by ricksaha2000** [comment]
But I don't think it is possible in one similarity search right?

Also as a separate idea, suppose in the same collection itself I have a metadata column "Source" which contains the different sources the vector db has been created from. Now imagine, Source column which contains 10 unique sources, and I want to give weights to each of this source so that that Weight is percolated into the similarity function. 

I would want to have an alpha-beta balance between the similarity score and the weight to give the final rank of retrieved results. 

How does that sound?

**Comment by xiaofan-luan** [comment]
even in hybrids saerch, it's actually two diferent search inside vector DB.

I still thought it's reasonable to search 10 collections and rerank on your client side

**Comment by ricksaha2000** [comment]
Correct, but in the hybrid search, correct me if I am wrong, the search takes place in two vector fields of the same row. 

But I want to make the search based on a metadata, say the source of ingestion of data source, suppose source A is having weight 0.6 and Source B has weight 0.4, so I want to use those weights in the similarity search.

Currently the weighted ranker doea that on a row basis, and not on an overall basis.

I think it can be an excellent use case, else the client side needs several api calls. Now in my current scenario, for a real time application, the SLA increases by a lot. Hence, I'm highlighting this issue. 

Do you suggest any fix on this?

**Comment by xiaofan-luan** [comment]
For hybrid search, you need to enable multi vector in single collection.
Milvus now don't support any operation across collections

**Comment by ricksaha2000** [comment]
Correct, that's clear with me. 
But as I mentioned another use case, where there is a 'Source' column as a metadata in the same collection. And based on the Source the data is coming from "to the same collection"  

Now suppose I have a collection A and I have ingested data from Source X  and Source Y, to tthe collection A. Now Source X is a good quality data source hence I want to assign it a higher weight say 0.8 ans Source Y, is a slightly unsure type of data source, and I assign it a Weight 0.5. 

Now I want to incorporate these weights, while doing a similarity search on Collection A, hence a custom similarity function.

I hope I could explain my query. Thank you.
