### ISSUE TITLE
Where do I modify the "use_blas_threhold" parameter?

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#3491]
link：https://www.milvus.io/cn/docs/v0.10.2/performance_faq.md#%E5%A6%82%E4%BD%95%E8%BF%9B%E8%A1%8C%E6%80%A7%E8%83%BD%E8%B0%83%E4%BC%98

![image](https://user-images.githubusercontent.com/53512883/91512207-13dba180-e914-11ea-858e-04dbf24e5564.png)

**Comment by shengjun1985** [comment]
I am sorry that the configuration item is removed now.
And we will fix the doc as soon as possible.

**Comment by AmyYH** [comment]
Documentation has been updated. See [如何进行性能调优](https://milvus.io/cn/docs/v0.10.2/performance_faq.md#%E5%A6%82%E4%BD%95%E8%BF%9B%E8%A1%8C%E6%80%A7%E8%83%BD%E8%B0%83%E4%BC%98).
