### ISSUE TITLE
[Bug]: Can not load old collection, always pending at 33%

### ISSUE THREAD

**Issue by garyyang85** [milvus-io/milvus#34955]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.1
- Deployment mode(standalone or cluster): standalone, helm chart
- MQ type(rocksmq, pulsar or kafka): rocksmq   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: unlimited
- GPU: 
- Others:
```

### Current Behavior

When I load some old collections, it always pending at 33%. But the load works on newly created collections.

### Expected Behavior

All the collection can be loaded successfully.

### Steps To Reproduce

```markdown
1.load the collection from attu web page. The collection name: _664daa9ba65b774d54530bc0_summary
```

### Milvus Log

[milvus-standalone-5f6f96d94c-f4vj5-standalone.log](https://github.com/user-attachments/files/16359020/milvus-standalone-5f6f96d94c-f4vj5-standalone.log)

**Comment by bigsheeper** [comment]
[2024/07/24 08:02:24.682 +00:00] [WARN] [retry/retry.go:46] ["retry func failed"] [retried=0] [error="The specified key does not exist.: key not found[key=file/stats_log/450092984836881773/450092984836881774/450092984836881825/100/450092984831517753]"] [errorVerbose="The specified key does not exist.: key not found[key=file/stats_log/450092984836881773/450092984836881774/450092984836881825/100/450092984831517753]

**Comment by bigsheeper** [comment]
@garyyang85 Did these old collections ever have data imported (not insert)?

**Comment by garyyang85** [comment]
@bigsheeper Yes, the data was from another milvus instance by backup and restore. 
And it works for weeks, found problem from last week.

**Comment by bigsheeper** [comment]
> @bigsheeper Yes, the origin data of the old collection was from another milvus instance by backup and restore. And it works for weeks, found problem from last week.

Sorry @garyyang85 , version 2.4.1 has a bug that causes the stats log from imports to be mistakenly garbage collected (see:https://github.com/milvus-io/milvus/issues/33476). Fixing this is really complicated. It's much easier to upgrade to version 2.4.6 and then re-insert or re-import your data. Again, sorry for the trouble.

**Comment by garyyang85** [comment]
Got. Thanks very much!
