### ISSUE TITLE
[Bug]: "drop_partition" delete Partition Error: ERROR:pymilvus.decorators:RPC error: [has_partition], <ParamError: (code=1, message=`partition_name` value 1439114954827296 is illegal)>,

### ISSUE THREAD

**Issue by yangy996** [milvus-io/milvus#34993]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version:  milvusdb/milvus:v2.3.4
- Deployment mode(standalone or cluster): standalone 
- SDK version(e.g. pymilvus v2.0.0rc2):  2.3.4
- OS(Ubuntu or CentOS): Ubuntu 
```

### Current Behavior

![1cbfd775c3c77dcad06053173d01ffea](https://github.com/user-attachments/assets/6210bd6c-5391-4a74-a043-25093495b501)

 ERROR:pymilvus.decorators:RPC error: [has_partition], <ParamError: (code=1, message=`partition_name` value 1439114954827296 is illegal)>,
![1c359ea4e80e006202cd7b3557fe2ad1](https://github.com/user-attachments/assets/8f372c4d-c053-4fe5-8f24-581dbe564211)

**Comment by yanliang567** [comment]
it does not reproduce to me with pymilvus 2.4.3, please try to upgrade and retry
```
>>> c.create_partition('1439114954827296')
{"name": "1439114954827296", "collection_name": "test", "description": ""}
from pymilvus import Partition
>>> p=Partition(c, '1439114954827296')
>>> p.name
'1439114954827296'
>>> c.has_partition('1439114954827296')
True
```
