### ISSUE TITLE
recall test use flat index cannot get 100%

### ISSUE THREAD

**Issue by zhouyongxiu** [milvus-io/milvus#3499]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
recall test use flat index cannot get 100%

**Steps/Code to reproduce behavior**
My test step as https://github.com/milvus-io/bootcamp/blob/master/benchmark_test/lab1_sift1b_1m.md
step1: python3.5 main.py --collection ann_1m_flat --dim 128 -c
step2: python3.5 main.py --collection=ann_1m_flat --load
step3: python3.5 main.py --collection=ann_1m_flat --search_param 128 --recall
and get the result:
collection name: ann_1m_flat query list: 500 topk: 500 search_params: {'nprobe': 128}
time_search =  1.9792087078094482
topk= 1 , total accuracy 92.2 %
topk= 10 , total accuracy 94.89999999999999 %
topk= 100 , total accuracy 96.6 %
topk= 500 , total accuracy 97.5 % 

**Method of installation**
- [ ] Docker/gpu

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
milvusdb/milvus:0.10.2-gpu-d081520-8a2393

**Comment by Bennu-Li** [comment]
Is the data you imported complete? Can you check your index information with milvus.get_index_info()? And can you refer to the ?document to import the data again to see if the accuracy is still the same

**Comment by zhouyongxiu** [comment]
> Is the data you imported complete? Can you check your index information with milvus.get_index_info()? And can you refer to the document to import the data again to see if the accuracy is still the same?

python3.5 main.py --collection=ann_1m_flat --rows
1000000
Data is imported complete, I find that recall result is different such as index=1， the result top1 is 528450, but gt is 588616

**Comment by Bennu-Li** [comment]
Can you try to import the data again。Which version of your milvus

**Comment by zhouyongxiu** [comment]
> Can you try to import the data again。Which version of your milvus

I test again , get the some result, my milvus is 0.10.2

**Comment by Bennu-Li** [comment]
I’ll try it and see the result

**Comment by shengjun1985** [comment]
@zhouyongxiu @Bennu-Li 
Thank you very much.
We have reproduced the issue.
And we will investigate it as soon as possible.

**Comment by shengjun1985** [comment]
This is a bug of bootcamp which is fixed by the following PR.
https://github.com/milvus-io/bootcamp/pull/290

Thank you for your concern and support for our project.
If you have more questions, please continue to contact our community.

**Comment by zhouyongxiu** [comment]
It is work normal now, thanks.

**Comment by zhouyongxiu** [comment]
@Bennu-Li  But when I set the index as sq8, the recall also is 100%, it seems that IS_UINT8 int config.py control the recall, not index.

**Comment by Bennu-Li** [comment]
> @Bennu-Li But when I set the index as sq8, the recall also is 100%, it seems that IS_UINT8 int config.py control the recall, not index.

Are you building the index before or after inserting data.
After inserting the data, you should build the index again.

**Comment by zhouyongxiu** [comment]
> > @Bennu-Li But when I set the index as sq8, the recall also is 100%, it seems that IS_UINT8 int config.py control the recall, not index.
> 
> Are you building the index before or after inserting data.
> After inserting the data, you should build the index again.

It is ok now, thanks
