### ISSUE TITLE
[Bug]: bulksearch with (nq=500,nlist=1024,nprobe=32) is very slow,feature is orb feature with 256 dim and indexed by BIN_IVF_FLAT

### ISSUE THREAD

**Issue by kkpssr** [milvus-io/milvus#34997]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: AMD 5950,128G 
- GPU: 
- Others:
```

### Current Behavior

the performance is very instability, sometime cost 800ms or more, sometimes cost 300ms in 2m data ,but is far from example in FAQ shows only cost 200ms when nq=1000 in 50m data.

**Comment by kkpssr** [comment]
repeat

**Comment by xiaofan-luan** [comment]
There are might be many reasons
1. too many segments, you can change segment size to 2G see if it works.
2. cpu doesn't support SIMD -> I think 5950 should at least support AVX2, but might not AVX512

if you can offer pprof or minitoring that could be really helpful
