### ISSUE TITLE
[Enhancement]: skip creating index when there is no querynode

### ISSUE THREAD

**Issue by longjiquan** [milvus-io/milvus#35004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Skip creating index when there is no querynode.

### Why is this needed?

Avoid the index version rollbacked to 0.

**Comment by xiaofan-luan** [comment]
why we skip create index when there is no qn?

**Comment by czs007** [comment]
@xiaofan-luan Currently ,we query the all the QueryNode to determine the index engine version of Knowhere.

**Comment by xiaofan-luan** [comment]
if there are no querynodes, simply use latest version as a fallback?

**Comment by xiaofan-luan** [comment]
assuming all the new brought up nodes should be new versions
