### ISSUE TITLE
[Bug]: no idle index node found and failed to build index

### ISSUE THREAD

**Issue by kkpssr** [milvus-io/milvus#35032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4.2
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 7
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![Uploading 1760F3C5-AF1C-4fe8-8E09-F0C2E3456883.png…]()

**Comment by kkpssr** [comment]
![Uploading 1760F3C5-AF1C-4fe8-8E09-F0C2E3456883.png…]()

**Comment by kkpssr** [comment]
![1760F3C5-AF1C-4fe8-8E09-F0C2E3456883](https://github.com/user-attachments/assets/6b280587-cbbb-4c64-82f1-687ef0d1effe)

**Comment by xiaofan-luan** [comment]
@kkpssr 
it seems that you have no alive index node and there are 700+ pending task.

1. check your config, you should have at least 1 replica of index node (since you have many data to build index on, you should have more data)
2. check your indexnode, if it's a panic, we need to check the log and understand why.

**Comment by kkpssr** [comment]
> @kkpssr it seems that you have no alive index node and there are 700+ pending task.
> 
> 1. check your config, you should have at least 1 replica of index node (since you have many data to build index on, you should have more data)
> 2. check your indexnode, if it's a panic, we need to check the log and understand why.
so how to add more indexnode in config? Is the buildParallel option in scheduler?
![27b24ab50b3070bb62eb634c22ca190d](https://github.com/user-attachments/assets/40fb8bc4-ae8c-4d91-bab8-5e7b9fa91712)

**Comment by xiaofan-luan** [comment]
it based on what is your deployment.

Is there any indexnodes log alive? cna you share the index log?
