### ISSUE TITLE
how can we read the index files directly

### ISSUE THREAD

**Issue by stopit** [milvus-io/milvus#3505]
**Please state your issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**
N
**Describe the solution you'd like**
I want to read index files through python application,so I can cluster the vectors with dbscan or any other algorithms. I try to read .rv files in /milvus/db/tables/*  but they are all hex files. Can U show some methods to tell us how we can read these files in memory. I will try to read the file directly and consider to make a spark interface.

**Describe alternatives you've considered**
N
**Additional context**
N

**Comment by shengjun1985** [comment]
【v0.10.x】
core/src/index/knowhere/knowhere/index/Index.h
Index::Serialize()
Index::Load()
These are the serialization and deserialization interfaces that every index will inherit.
And they will be used when the system writes index files to the disk.

core/src/index/knowhere/knowhere/index/vector_index
There are various index implementations in this directory.

core/src/codecs/default/DefaultVectorIndexFormat.h
class DefaultVectorIndexFormat 
It is the class used to read and write index files.

**Comment by shengjun1985** [comment]
If you have more questions, please continue to contact our community.
Thank you.
