### ISSUE TITLE
[Bug]: load segment may cause long tSafe latency

### ISSUE THREAD

**Issue by weiliu1031** [milvus-io/milvus#35070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3/2.4/master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

cause load segment will hold delete buffer lock to consume msg from stream, which may block process delete for a few seconds, and cause a peek in tSafe latency.

**Comment by xiaofan-luan** [comment]
I think this is not must?
Once we split all the existing delete log there is no need to hold the delete log?

@XuanYang-cn
