### ISSUE TITLE
[Bug]: 0 search results, when searching immediately after inserting the records

### ISSUE THREAD

**Issue by vipul25-ds** [milvus-io/milvus#35090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4.1
- Deployment mode(standalone or cluster):Cluster
- MQ type(rocksmq, pulsar or kafka):   
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus
- OS(Ubuntu or CentOS): 
- CPU/Memory: CPU
- GPU: 
- Others:
```

### Current Behavior

When I search using client.query, I get zero results immediately after insertion. Tried setting query node graceful time parameter, but that doesnt seem to be working. 

Tried setting gracefulTime like below:
queryNode:
  enabled: true
  gracefulTime: 1000

https://milvus.io/docs/configure_querynode.md

Question:
1. How can we reduce this lag between insertion and search

### Expected Behavior

Immediate search results after insertion

**Comment by congqixia** [comment]
What's the consistency level when performing the search? It's by design if the consistency level is not strong. 
Maybe this document shall help to understand what's going on when using different level when performing search/query request.
https://milvus.io/docs/consistency.md#Consistency-levels

**Comment by xiaofan-luan** [comment]
usually it take at least 200 milliseconds for all the data to be seen. if you set strong consistency you will simply wait for another 200 ms.
