### ISSUE TITLE
[Bug]: milvus vector db got corrupted during the insertion

### ISSUE THREAD

**Issue by haseebkhawaja** [milvus-io/milvus#35117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.4.6
- Deployment mode(standalone or cluster): standalone 
- OS: Ubuntu
- CPU/Memory: 32 cores/ 32 GB RAM
- other: Running at VM
```

### Current Behavior

Hey, My milvus vector db got corrupted during the insertion. It happened during the power loss of server. 

**I am looking for the solution to recover the collections**.

### Anything else?

I also saw in the issues... and they suggested that delete the data ... but want to recover the data...

**Comment by haseebkhawaja** [comment]
@yanliang567 @dandv @lhotari @tedxu 
Hey
Anyone can help me...?

**Comment by binbinlv** [comment]
@haseebkhawaja 
could you please paste the detailed log of milvus here?
And the reproduced script is better to have if it is convinient, thanks.

**Comment by dandv** [comment]
Why was I tagged here...?

**Comment by binbinlv** [comment]
@haseebkhawaja 
what you mean is you insert failed because of the power loss of server? And the milvus crashed at the same time?

And when your server is up, the collection data is lost? Could you please give more detailed information? Thanks

**Comment by xiaofan-luan** [comment]
@haseebkhawaja 
could you provided logs by export log.sh, this tool help you to automatically gather logs

**Comment by yanliang567** [comment]
@haseebkhawaja Could you please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.

/assign @haseebkhawaja 
/unassign
