### ISSUE TITLE
[Bug]: segments have 0 rows count after inserting data into the new collection

### ISSUE THREAD

**Issue by douglarek** [milvus-io/milvus#35131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.12
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I created a collection on attu and tried to insert sample data. After the insertion was completed, no data segments were generated in the segment.

![图片](https://github.com/user-attachments/assets/d9db11e3-5209-4612-9ced-31ba6deec8b0)

**Comment by binbinlv** [comment]
@douglarek 
could you please provide the detailed milvus log?

**Comment by binbinlv** [comment]
> > @douglarek could you please provide the detailed milvus log?
> 
> Which specific components are they? I do have logs, and the log for just the query node alone is 2GB. I understand that only the logs of datacord and datanode are needed, right?

 I think upload these logs first is OK, and will ask it if we need more.

**Comment by binbinlv** [comment]
@congqixia 
could you please have a look about whether it is similar to the above issues? Thanks.

**Comment by xiaofan-luan** [comment]
[2024/07/29 10:47:28.757 +00:00] [WARN] [kafka/kafka_consumer.go:138] ["consume msg failed"] [topic=milvus-zxy-mmap-rootcoord-dml_8] [groupID=datanode-1682-milvus-zxy-mmap-rootcoord-dml_8_448935071136970251v0-true] [error="Local: Timed out"]

**Comment by xiaofan-luan** [comment]
from the log, kafka consumed is fully timeout.

And even the log format is weird

**Comment by xiaofan-luan** [comment]
if you check the first log file you offered you will understand what I'm saying.

**Comment by xiaofan-luan** [comment]
I don't think the cluster is setup correctly so don't spent time on checking it. The best way is problem setup a meeting with us and we can give you advice to rebuild the cluster.  The problem you hit definitely have nothing to do with any of the bugs. 

Contact xiaofan.luan@zilliz.com

**Comment by xiaofan-luan** [comment]
> > [2024/07/29 10:47:28.757 +00:00] [WARN] [kafka/kafka_consumer.go:138] ["consume msg failed"] [topic=milvus-zxy-mmap-rootcoord-dml_8] [groupID=datanode-1682-milvus-zxy-mmap-rootcoord-dml_8_448935071136970251v0-true] [error="Local: Timed out"]
> 
> I think this is a normal log. You can tell by looking at the source code. If it takes more than 30 seconds to consume, it will report this warning, which is not an issue.

It said timeout. at least you need to make kafka work

**Comment by xiaofan-luan** [comment]
I don't think kafka consumption takes 30 seconds is expected. And you have many these logs on one of the datanode.

If you open the log of another datanode, you know what I'm saying

**Comment by xiaofan-luan** [comment]
I agree there are definitely some issue here. But you don't offer any coord log. 
And from log you offered, the most important I can see is kafka timeout. that might be the reason you see 0 entities. because datanode consumption stucks.

**Comment by xiaofan-luan** [comment]
Glad you fix the problem. Recommended to upgrade to 2.3.20 for better stability

**Comment by xiaofan-luan** [comment]
from the log offered, it's keep timeout.
BTW, thanks for pointing out, the code is reviewed by me so I'm very familiar with it

**Comment by xiaofan-luan** [comment]
> > from the log offered, it's keep timeout.
> 
> Even if it's like you said, how do I distinguish whether there is no message waiting or Kafka is really stuck? Is there any source code or other facilities in Milvus that can help locate this?

It's not possible. If milvus is working correctly , there should always be a timetick every 200ms

**Comment by xiaofan-luan** [comment]
the timetick is written by rootcoord
