### ISSUE TITLE
[Enhancement]: CRITICAL Vulnerability in stdlib related to net/netip

### ISSUE THREAD

**Issue by A-Jatin** [milvus-io/milvus#35142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

I was testing for vulnerabilities before deploying milvus in our environment and found a critical issue(see image below)

However this issue is fixed with latest version of stdlib but milvus doesnt support that currently. Can we please have an update for this to resolve this vulnerability?
![image](https://github.com/user-attachments/assets/1113c7f4-d429-47ee-a4a7-2e72d1039183)

### Why is this needed?

To deploy milvus without any CRITICAL vulnerabilities.

### Anything else?

Using Trivy - https://github.com/aquasecurity/trivy for vulnerability scan of the container.

**Comment by xiaofan-luan** [comment]
@shaoting-huang 
seems that we need 1.21.11 for 2.4

**Comment by A-Jatin** [comment]
this is still causing the issue - milvusdb/milvus-config-tool   v0.3.0

**Comment by xiaofan-luan** [comment]
@zwd1208 
can you please help on fix the CVE

**Comment by zwd1208** [comment]
ok,  @haorenfsa will fix it soon.
