### ISSUE TITLE
[Bug]: the distance of IVF_PQ, GPU_IVF_PQ search results are wrong

### ISSUE THREAD

**Issue by liangbug** [milvus-io/milvus#35151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.6-gpu
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.4.4
- OS(Ubuntu or CentOS): Ubuntu 22.04
- CPU/Memory: Intel(R) Xeon(R) Gold 6240, 512GB ram
- GPU: Nvidia RTX 8000
- Others:
```

### Current Behavior

I inserted 90k unit vectors with 384 dim, length 1 and created IVF_PQ, GPU_IVF_PQ GPU index with metric: IP,  "m": 8, "nlist": 1024.
Then I found that I search exactly the same vectors from db and the distance of top 1 results (the exact vector),  some are less than 1, some equal 1 .

**Comment by binbinlv** [comment]
@liangbug 
could you please paste the detailed milvus log here? Thanks.

**Comment by liangbug** [comment]
The below figures are made by zilliztech/attu
![image](https://github.com/user-attachments/assets/b7973c76-edb6-48f1-9609-5d1ca0a22ad7)

![image](https://github.com/user-attachments/assets/e3403c08-7aef-4fe6-bcb2-69855a07186f)

![image](https://github.com/user-attachments/assets/4bb06ad0-99e5-4474-92a5-9898d4bb4d65)

![image](https://github.com/user-attachments/assets/cdbee342-0c78-45d6-b4c4-e3b71a54b15e)
The pymilvus also make the same results.

**Comment by xiaofan-luan** [comment]
don't quite understand what you are saying, there is no guarantee that same search can return same result, especially under your case you are using IVFPQ and the recall is very low.

We can not guarantee same result to be returned becasue:
1. growing index can be handoff to sealed
2. sealed segment can be compacted.

I suggest you use better search parameters
1. do not use PQ
2. use larger nprobe. For nlist=1024, nprobe=32 or 64 is recommended

**Comment by liangbug** [comment]
@binbinlv

> @liangbug could you please paste the detailed milvus log here? Thanks.
> 
> And here what you mean is the distance of top1 result is different when you search twice using the same vector?

I don't see anything unusual in the milvus standalone info log.  
What kind of log do you need?  Can you describe in detail?

The search twice or more returns always return the same result.

The id 450885682672689422 vector and id 450885682672689423 vector are length 1.
I searched using 450885682672689423 vector and got result 450885682672689423 vector with distance (score) of 0.99.
But I searched using 450885682672689422 vector and got result 450885682672689422 vector with distance (score) of 0.8.
Why are they different ?

**Comment by cqy123456** [comment]
1. Is the input data normalized？ If not, IP<x, x> = x^2, there is a high probability that it is not 1；
2. you use M = 8 with dim = 384, it means the distance of Metric<x, y> is the sum of 8 code distances.  and it is an erroneous way to calculate distance.

**Comment by cqy123456** [comment]
cpu index: IVF_FLAT, HNSW, and SCANN;
gpu index:  GPU_CAGRA, GPU_IVF_FLAT, and GPU_BRUTE_FORCE.
