### ISSUE TITLE
[Bug]: make error：[Makefile:118: get-proto-deps] Error 1

### ISSUE THREAD

**Issue by devillaws** [milvus-io/milvus#35171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:last
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):  rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 
- OS(Ubuntu or CentOS): Ubuntu 22.04
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

after run ./scripts/install_deps.sh, i do the “make milvus” in ./milvus folder. the console export that:
![image](https://github.com/user-attachments/assets/1ad56b18-9ce0-443a-88b0-95814f6b6391)

### Milvus Log

![image](https://github.com/user-attachments/assets/18801b60-5774-4c31-8c5e-448e47edf31b)

**Comment by binbinlv** [comment]
@devillaws 
Hello, which branch are you building milvus?

**Comment by devillaws** [comment]
> @devillaws Hello, which branch are you building milvus?

hello,i build v2.3.20[v2.3.20](https://github.com/milvus-io/milvus/releases/tag/v2.3.20)

**Comment by devillaws** [comment]
> /assign @czs007 /unassign

what is this

**Comment by devillaws** [comment]
![image](https://github.com/user-attachments/assets/15351b57-501f-4652-9fd7-8857c8934a7b)
now i try the root to build, the same error.
the key world looks like "go" and "oauth2".
anyway, i have tried vpn and agent.
