### ISSUE TITLE
[Bug]: Urgent: Bulkinsert access in multi-tenency cluster

### ISSUE THREAD

**Issue by kish5430** [milvus-io/milvus#35203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

HI Team,

We have deployed a Milvus cluster with a multi-tenancy architecture and onboarded multiple teams. One of the teams has requested a bulk insert feature, so we created a sub-bucket for them. They have uploaded their file and started using it with their Milvus user account. However, the issue is that these files are also accessible to other users within the same Milvus cluster. How can we restrict access to this sub-bucket to specific Milvus users only?

Thanks

**Comment by zhuwenxing** [comment]
> However, the issue is that these files are also accessible to other users within the same Milvus cluster.

What is the specific manifestation of this sentence? Can other users see it through MinIO/S3 or Milvus SDK?

**Comment by kish5430** [comment]
> > However, the issue is that these files are also accessible to other users within the same Milvus cluster.
> 
> What is the specific manifestation of this sentence? Can other users see it through MinIO/S3 or Milvus SDK?

If multiple users created in  Milvus, they can all access the files in the S3 bucket through the Milvus SDK bulk insert code.

**Comment by zhuwenxing** [comment]
Yes, this possibility exists. However, the prerequisite is that another user needs to know the specific file name. I recall that the bulk insert interface should not be able to pass the file value through glob, right?

One possible solution is to give different users folders with UUID commands, which may reduce the likelihood of file conflicts.

**Comment by xiaofan-luan** [comment]
We recommend you to maintain a service to copy between different S3 bucket.
It is too heavy for milvus to access multiple bucket， there could be multiple network issue or access issue.
