### ISSUE TITLE
[Bug]: standalone v2.4.5 docker milvus cannot start

### ISSUE THREAD

**Issue by disperaller** [milvus-io/milvus#35213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4.5
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.4.4
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: Intel(R) Xeon(R) Gold 6226R CPU @ 2.90GHz
- GPU: RTX 3090, 24G
- Others:
```

### Current Behavior

when using `bash standalone.sh start` the milvus container will start for 10 seconds, and then crashed.

This issue happens after i inserted about 5 million records into the milvus, and during those insertion, milvus works fine. But at some point, it'll just break and can't start up anymore. Possible causes and solutions i tried:
1. I have checked the disk usage, it's never full. 
2. I tried 3 times and every time this issue appears.
3. Add --restart=always in the standalone.sh file, and when the issue happens, it did restart, but it just restarts over and over and ATTU can't connect to it.

Below are the logs:
[log_milvus.log](https://github.com/user-attachments/files/16465740/log_milvus.log)
In this log, the container restarts for 3 times, and all show successfully started, but after 1 minutes, all crashed.

**Comment by smellthemoon** [comment]
<img width="990" alt="image" src="https://github.com/user-attachments/assets/81a8c3a8-3f2d-4501-96cf-24b17aa1c140">
memory limit exceed. could you please check your memory and try it again？
@disperaller

**Comment by xiaofan-luan** [comment]
@disperaller 
how much data do you have? from log that the total memory usage is 40G.Even it's only 5m, I believe even 1536dim data takes 10-15GB. but it seems that the data size is far more than it.
