### ISSUE TITLE
[Bug]: milvus rootcoord always crashes and restarts, the error message is oomkill, the memory has been allocated to 48G

### ISSUE THREAD

**Issue by TonyAnn** [milvus-io/milvus#35230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.16
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

milvus rootcoord always crashes and restarts, the error message is oomkill, the memory has been allocated to 48G

### Expected Behavior

The detailed rootcoord log is shown in the attachment
[rootcoord_280160cbb3b-json.log](https://github.com/user-attachments/files/16466439/rootcoord_280160cbb3b-json.log)
[rootcoord_json.log](https://github.com/user-attachments/files/16466443/rootcoord_json.log)
[rootcoord_280160cbb3b-json.log](https://github.com/user-attachments/files/16466448/rootcoord_280160cbb3b-json.log)

**Comment by xiaofan-luan** [comment]
are you sure it's coordinator reach memory limit?

from the log querynode-11298 is full of memory and this numbers shows that some node reboot a lot of times.

If you do say coordinators have so much memory usage, please offer a pprof file of rootcoord so we can do futher analysis

**Comment by xiaofan-luan** [comment]
I don't think it is possible for rootcoord to have a lot of memory in a short period of time.

**Comment by xiaofan-luan** [comment]
from the log, rootcoord works find without seeing any problems

**Comment by yanliang567** [comment]
@TonyAnn it looks like you have created thousands of  collections in the cluster, which could be already improved in latest milvus relase. could you please retry on milvus 2.4.7 or 2.3.20

**Comment by xiaofan-luan** [comment]
> @TonyAnn it looks like you have created thousands of collections in the cluster, which could be already improved in latest milvus relase. could you please retry on milvus 2.4.7 or 2.3.20

even with 10k collections, the memory usage is not expected?

**Comment by xiaofan-luan** [comment]
we need pprof to understand why. maybe it's due to some kind of retry

**Comment by yanliang567** [comment]
[pprof.milvus.alloc_objects.alloc_space.inuse_objects.inuse_space.002.pb.gz](https://github.com/user-attachments/files/16492225/pprof.milvus.alloc_objects.alloc_space.inuse_objects.inuse_space.002.pb.gz)
here received the pprof from user
/assign @congqixia 
please help to take a look

**Comment by congqixia** [comment]
![image](https://github.com/user-attachments/assets/00569db9-86ab-438f-a35b-50e9f0345910)
inuse space is very low, but the alloc space is huge
how many collection do you have in you instance?
@TonyAnn

**Comment by congqixia** [comment]
@TonyAnn also 2.2.16 is a very old version. There might be some optimization related to this issue in 2.3.x and 2.4.x. It highly recommended to upgrade you cluster to a more stable version

**Comment by TonyAnn** [comment]
> ![image](https://private-user-images.githubusercontent.com/84113973/355006405-00569db9-86ab-438f-a35b-50e9f0345910.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzQ4MTUsIm5iZiI6MTcyMjkzNDUxNSwicGF0aCI6Ii84NDExMzk3My8zNTUwMDY0MDUtMDA1NjlkYjktODZhYi00MzhmLWEzNWItNTBlOWYwMzQ1OTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA4NTUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkOTRjMWE3ZjU3ZGY0ZjNiNDY5MTdhODA0YTE2ZWZhYWRhY2M5Mjg4Yzk0Yjg0MjQwNzMyMjI5NzJhMDYxYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.isDVH_NCqkd01TIy7SlWQ7V_0EJC3lx1SK_p2Pl9KXY) inuse space is very low, but the alloc space is huge how many collection do you have in you instance? @TonyAnn

@congqixia  There are a large number of collections in the cluster. There is a liveness detection script that continuously creates and deletes collections. This script may be the cause.

**Comment by TonyAnn** [comment]
> why

OK, it will be upgraded in a while.
