### ISSUE TITLE
[Bug]: delete by expr may failed in retry progress

### ISSUE THREAD

**Issue by weiliu1031** [milvus-io/milvus#35240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3/2.4/master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

delete by expr shard the same err object between channels, so if one channel's query failed, it will fail all channel, which will break channel level retry policy, and make delete operation failed.

**Comment by xiaofan-luan** [comment]
I don't think that is a big problem,
User can simply retry same expr.
