### ISSUE TITLE
[Bug]: key of `DataCoordTicklePath` is wrong

### ISSUE THREAD

**Issue by Reidddddd** [milvus-io/milvus#35259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
Not environment related, it is a code bug
```

### Current Behavior

```
	p.DataCoordWatchSubPath = ParamItem{
		Key:          "msgChannel.subNamePrefix.dataCoordWatchSubPath",
		Version:      "2.1.0",
		DefaultValue: "channelwatch",
		PanicIfEmpty: true,
	}

	p.DataCoordTicklePath = ParamItem{
		Key:          "msgChannel.subNamePrefix.dataCoordWatchSubPath",
		Version:      "2.2.3",
		DefaultValue: "tickle",
		PanicIfEmpty: true,
	}
```

Both `DataCoordTicklePath` and `DataCoordWatchSubPath` shares a same key.

### Expected Behavior

`DataCoordTicklePath` should use a different key, probably is a copy-paste error.

**Comment by yanliang567** [comment]
/assign @congqixia 
please help to take a look
/unassign

**Comment by xiaofan-luan** [comment]
thanks for the founding!
@aoiasd 
are we still using this key?

**Comment by Reidddddd** [comment]
> thanks for the founding! @aoiasd are we still using this key?

no where use it in fact, at least in community version. But I'm not sure whether it's appropriate to delete it, so just change to a correct key name.

**Comment by xiaofan-luan** [comment]
> > thanks for the founding! @aoiasd are we still using this key?
> 
> no where use it in fact, at least in community version. But I'm not sure whether it's appropriate to delete it, so just change to a correct key name.

Maybe simply remove it?

**Comment by Reidddddd** [comment]
> > > thanks for the founding! @aoiasd are we still using this key?
> > 
> > 
> > no where use it in fact, at least in community version. But I'm not sure whether it's appropriate to delete it, so just change to a correct key name.
> 
> Maybe simply remove it?

removed as review, please check the latest PR

**Comment by Reidddddd** [comment]
Hi @xiaofan-luan 

shall i need to ping anyone else for reviews, seems there is no progress forward

**Comment by Reidddddd** [comment]
the PR is merged, marked as fixed
