### ISSUE TITLE
[Bug]:  message=multiple vector fields is not supported, fields name: embedding, embedding1

### ISSUE THREAD

**Issue by yuhp-zts** [milvus-io/milvus#35269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster): standalone 
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-2.4.4
- OS(Ubuntu or CentOS):  Ubuntu 
- CPU/Memory: 
- GPU:  GPU
- Others:
```

### Current Behavior

fields = [
        FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, auto_id=False),
        FieldSchema(name="embedding", dtype=DataType.FLOAT_VECTOR, dim=dim),
        FieldSchema(name="embedding1", dtype=DataType.FLOAT_VECTOR, dim=dim)
    ]
schema = CollectionSchema(fields, description="Demo collection for keyword and vector search")
 collection = Collection(name=collection_name, schema=schema)
raise error：
raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=0, message=multiple vector fields is not supported, fields name: embedding, embedding1)>

![image](https://github.com/user-attachments/assets/8ed2f7e8-e6da-422c-90c1-a05a700faf6e)

**Comment by binbinlv** [comment]
@yuhp-zts 
what is the version of your milvus, it seems that you used a version which not supported multiple vector?

**Comment by yuhp-zts** [comment]
> @yuhp-zts what is the version of your milvus, it seems that you used a version which not supported multiple vector?

pymilvus-2.4.4

**Comment by yuhp-zts** [comment]
> collection = Collection(name=collection_name, schema=schema)

![image](https://github.com/user-attachments/assets/12579886-d455-4a08-9318-39981a5a6f03)
