### ISSUE TITLE
[Bug]: C++ OpenTelemetry stucks at initialization when set OTLP as exporter

### ISSUE THREAD

**Issue by PwzXxm** [milvus-io/milvus#35298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4/master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When `otlp` is set as the trace exporter, QueryNode reports initialization timeout and fails to start.

### Expected Behavior

Querynode successfully starts, tracing can be utilized.

**Comment by PwzXxm** [comment]
This issue is caused by mixing several libraries in Conan, triggering a gRPC++ bug, and creating an infinite loop when traversing linked lists.

**Comment by PwzXxm** [comment]
Fix via patching grpc

**Comment by PwzXxm** [comment]
Possible refactor and fix in gRPC v1.65.0 but it fails to build at this point of time.

**Comment by PwzXxm** [comment]
For ref
https://github.com/grpc/grpc/issues/20690
https://github.com/grpc/grpc/issues/20757

**Comment by PwzXxm** [comment]
grpc 1.54.3 compile fails on M1 MacOs, fallback to grpc 1.50.1 and repatch

**Comment by LoveEachDay** [comment]
In-house verification has been successful. This issue can now be closed.
