### ISSUE TITLE
The loaded collection cannot be queried.

### ISSUE THREAD

**Issue by TonyAnn** [milvus-io/milvus#35310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.16
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The loaded collection cannot query results. First, it reports

fail to Search, QueryNode ID=2168, reason=Search 2158 failed, reason Timestamp lag too large lag(28h20m1.999s) max(24h0m0s) err %!w(<nil>) attempt #2:code: UnexpectedError

After restarting pod 2158, the query directly times out and does not return any results

For detailed log, refer to the following

### Milvus Log

[querynode_2158.log](https://github.com/user-attachments/files/16507933/querynode_2158.log)
[milvus-log.tar.gz](https://github.com/user-attachments/files/16507937/milvus-log.tar.gz)

**Comment by congqixia** [comment]
According to the error message you provided, the "Timestamp lag too large" means the tsafe failed to advance and the jetlag is too large(more than one day).
Since the version was 2.2.16, the tsafe could be cause by either of reasons below:
- Root coort failed to produce timetick
- Datanode failed to forward delete msg
- Querynode failed to consume either of there messages

**Comment by TonyAnn** [comment]
> According to the error message you provided, the "Timestamp lag too large" means the tsafe failed to advance and the jetlag is too large(more than one day). Since the version was 2.2.16, the tsafe could be cause by either of reasons below:
> 
> * Root coort failed to produce timetick
> * Datanode failed to forward delete msg
> * Querynode failed to consume either of there messages

How to locate the specific cause and fix the exception? @congqixia

**Comment by yanliang567** [comment]
i'd suggest you upgrade milvus to latest 2.4.6 or 2.3.20, which fixed/improved the jetlag issues already.
/assign @TonyAnn 
/unassign

**Comment by TonyAnn** [comment]
![0c7eac02ed7dc12998778d062f896ca](https://github.com/user-attachments/assets/5050c0ef-679c-4788-9a0d-b80a08f5fb71)

Query from metadata, abnormal collecton, no channel information, and checkpoint is no longer updated
How to proceed with the next step of troubleshooting
