### ISSUE TITLE
Index type need check by field type

### ISSUE THREAD

**Issue by nameczz** [milvus-io/milvus#3531]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
When entities count < segment row count , we can create Hamming/Jaccard Index type for vector_float field.  

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**
Need check index type by field type before it's really created.
And throw an error.

**Method of installation**
- [x] Docker/cpu

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
master

**Configuration file**
Default Config

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by fishpenguin** [comment]
Already fixed
