### ISSUE TITLE
[Bug]: make: *** [Makefile:253: generated-proto] Error 1

### ISSUE THREAD

**Issue by devillaws** [milvus-io/milvus#35355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.4.7
- Deployment mode(standalone or cluster):can't make
- MQ type(rocksmq, pulsar or kafka):can't make    
- SDK version(e.g. pymilvus v2.0.0rc2):can't make
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: can't make
- GPU: can't make
- Others: can't make
```

### Current Behavior

After i have install the protoc-gen-go sucessfully, the new ERROR has occurs
![image](https://github.com/user-attachments/assets/e06349be-dacb-409e-b480-114231221e73)

### Expected Behavior

I want to make the milvus sucessfully, not by the docker-compose. It is somebody help me ,I have read a lot of milvus making tutorial. but never seem this ERROR(T T )

### Steps To Reproduce

```markdown
1.runing ./scripts/install_deps.sh to install requirements
2.make the project.
3.ERROR occurs.
```

**Comment by devillaws** [comment]
seems the /scripts/generate proto.sh has some problem

**Comment by xiaofan-luan** [comment]
how did you do make?
seems that you didn't down load proto

**Comment by xiaofan-luan** [comment]
simply do make should work

**Comment by devillaws** [comment]
> how did you do make? seems that you didn't down load proto
![image](https://github.com/user-attachments/assets/8a3d31c0-6b66-4d55-8034-f891e99464bb)
![image](https://github.com/user-attachments/assets/06827313-10bf-438c-85e3-d849d9768dcb)
yes! it seems /cmake_build/thirdparty/milvus-proto/proto is none! but why?
I just simply do make after ./scripts/install_deps.sh

**Comment by xiaofan-luan** [comment]
try make generated-proto and see what happens

**Comment by devillaws** [comment]
> try make generated-proto and see what happens

**seems this path is wrong!**
![image](https://github.com/user-attachments/assets/021512b5-be1b-4c72-854f-90efbf21f997)

**Comment by xiaofan-luan** [comment]
https://github.com/milvus-io/milvus-proto 
it is there. probably need to check how github is configured

**Comment by devillaws** [comment]
> https://github.com/milvus-io/milvus-proto it is there. probably need to check how github is configured

thank you!I follow a guide teach me to use git@github.com/milvus-io/milvus-proto.git by ssh, seems it doesnt work. 
now it is making and need to wait for a while.

**Comment by devillaws** [comment]
> https://github.com/milvus-io/milvus-proto it is there. probably need to check how github is configured

**excuse me,my expert, now it comes a new ERROR, i try many times ,the ERROR is same.Looks like from making faiss**
![image](https://github.com/user-attachments/assets/cff3f769-17c4-4f09-89d2-d3f4eb771c01)
![image](https://github.com/user-attachments/assets/98e186a2-d307-4ca8-8f9a-e54424c0b00f)

**Comment by devillaws** [comment]
> simply do make should work
 
excuse me ,is that succeeded?
![image](https://github.com/user-attachments/assets/d4f4b036-030b-4030-8b7a-8905cf037c41)

**Comment by shaoting-huang** [comment]
yes, it's working now!

**Comment by shaoting-huang** [comment]
Hello @devillaws , have you encountered any other problems related to compiling?

**Comment by devillaws** [comment]
> Hello @devillaws , have you encountered any other problems related to compiling?

Hello,thank you reply me!
Now,my other vps occurs the different ERROR in same environment. Seems because of building knowhere faiss? 
![image](https://github.com/user-attachments/assets/074a122d-b8d3-4b88-bdc4-671e134ed218)
![image](https://github.com/user-attachments/assets/c851b6c6-beb9-4ef4-a360-c3cb978ba297)

**Comment by shaoting-huang** [comment]
this is warning from faiss, please scroll up to get actual error logs

**Comment by devillaws** [comment]
> this is warning from faiss, please scroll up to get actual error logs

thanks for reply，the error is started here. I cant see any problem.
![image](https://github.com/user-attachments/assets/bc3ed706-b5d8-4598-8c56-251367da72f5)

**Comment by xiaofan-luan** [comment]
how much memory you have? it seems that your compilation is killed.
