### ISSUE TITLE
[Bug]: is too hard to make the project,i try my best.

### ISSUE THREAD

**Issue by devillaws** [milvus-io/milvus#35367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
I try many different pod to make this project,now the main environment is here:
- Milvus version:2.4.7 or laster
- OS(Ubuntu or CentOS): ubuntu 22.04
- cmake : cmake version 3.28.1
- go : go version go1.21.6 linux/amd64
- python : Python 3.11.0rc1
- gcc : gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
- network : agent or direct
```

### Current Behavior

After i git clone the laster code.git，just simply run the ./scripts/install_deps.sh, and do the make. some new ERROR occures again.
**Situation 1：it looks building milvus_segcore**
![image](https://github.com/user-attachments/assets/15eede5b-e01a-4fea-9cc5-42921c54982c)

**Situation 2：it looks building faiss**
![image](https://github.com/user-attachments/assets/0df6d922-ca02-4f99-8f18-af26262fe828)

**Situation 3：seems it finish build, but can not runing**
![image](https://github.com/user-attachments/assets/35ebe787-a5f0-475b-8183-ac2b001f1f73)

### Expected Behavior

I just want to make the project suceessfully, not the docker-compose

### Steps To Reproduce

```markdown
1.runing ./scripts/install_deps.sh to install requirements
2.make the project.
3.ERROR occurs.
```

### Anything else?

Maybe I do so bad, but i never give up

**Comment by yanliang567** [comment]
/assign @Presburger 
please give a hand on this issue.
/unassign

**Comment by Presburger** [comment]
@devillaws Hi, The "killed" message occurs due to insufficient memory. If an "so" file is not found during execution, you can use `find` to locate the path of the "so" file and then add it to the `LD_LIBRARY_PATH` environment variable to make Milvus functional.

**Comment by devillaws** [comment]
> @devillaws Hi, The "killed" message occurs due to insufficient memory. If an "so" file is not found during execution, you can use `find` to locate the path of the "so" file and then add it to the `LD_LIBRARY_PATH` environment variable to make Milvus functional.

Expressing gratitude for your reply,my friends, I have solved the  "so" file is not found problem in execution. but when i make in other system from same envrionment, the Situation 2 The "killed" message is always occurs and the memory is normal. i cant solved this Situation 2。
![image](https://github.com/user-attachments/assets/62e39478-d112-4b42-8c4c-a7c21e551d79)

**Comment by xiaofan-luan** [comment]
how much memory do you have?
I suggest you at least have 2Gb or more memory for the building

**Comment by devillaws** [comment]
> how much memory do you have? I suggest you at least have 2Gb or more memory for the building

Thanks for reply ,seems is enough
![image](https://github.com/user-attachments/assets/c3341e03-d881-437c-8a65-eec94136ce48)

**Comment by Presburger** [comment]
@devillaws How many cores does your environment have?

**Comment by devillaws** [comment]
> @devillaws How many cores does your environment have?

Thanks,it is 96 
![image](https://github.com/user-attachments/assets/9b1fcca7-e948-46f8-a5d1-de5c85a0f0d5)

**Comment by xiaofan-luan** [comment]
@devillaws 
maybe you can start from building knowhere see what is the error you meet? There isn't enough error message

**Comment by Presburger** [comment]
@devillaws The issue here seems to be that during compilation, `make` executed many parallel compilation processes, leading to insufficient memory, which in turn caused the compilation process to be killed.

**Comment by xiaofan-luan** [comment]
> @devillaws The issue here seems to be that during compilation, `make` executed many parallel compilation processes, leading to insufficient memory, which in turn caused the compilation process to be killed.

@Presburger the machine seesm to be huge, with 512GB memory so I guess that is not the issue.

**Comment by Presburger** [comment]
@xiaofan-luan It seems that since the machine has a relatively high number of cores, `make` likely determines the level of concurrency based on the number of cores.
