### ISSUE TITLE
[Bug]: The `authorizationEnabled` flag reverts to its original state in Milvus standalone mode when using Docker.

### ISSUE THREAD

**Issue by arian360** [milvus-io/milvus#35375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.4.1
- Deployment mode(standalone or cluster):standalone 
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 
- OS(Ubuntu or CentOS): Ubuntu 
- CPU/Memory: 8 CPU/32 DB RAM
- GPU: 
- Others: 70 GB HDD
```

### Current Behavior

Enabled `authorizationEnabled: true` in `/milvus/config.milvus.yaml`, but after restarting Milvus, the flag reverted to `authorizationEnabled: false`.

### Expected Behavior

Enabled `authorizationEnabled: true` in `/milvus/config.milvus.yaml`. After restarting Milvus, the flag should be set to `true`, and the Milvus server should prompt for a username and password to log in.

### Steps To Reproduce

```markdown
sudo docker exec -it milvus-standalone cat /milvus/configs/milvus.yaml
cd /milvus/config/
changed  authorizationEnabled: false to true in milvus.yaml
sudo docker compose down
sudo docker compose up -d

still showing old flag  authorizationEnabled: false
```

### Anything else?

Here are the milvus.yaml and docker-compose.yaml files 
[docker-compose.txt](https://github.com/user-attachments/files/16548417/docker-compose.txt)
[milvus.txt](https://github.com/user-attachments/files/16548419/milvus.txt)

**Comment by xiaofan-luan** [comment]
did you follow this document?
https://milvus.io/docs/configure-docker.md?tab=component

**Comment by yanliang567** [comment]
i think you should mount the updated milvus.yaml into the dockcompse file as the document(attached above) says.
please retry
/assign @arian360 
/unassign
