### ISSUE TITLE
[Bug]: Unable to Delete Data from Collection After Field Modification in Milvus

### ISSUE THREAD

**Issue by HantaoCai** [milvus-io/milvus#35371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: V2.4.6
- Deployment mode(standalone or cluster):STANDALONE
- MQ type(rocksmq, pulsar or kafka):  pulsar
```

### Current Behavior

1. We have an existing collection named `gemini_library_v5` with the following fields:
```python
def dataset_fields() -> List:
    return [
        FieldSchema(name="index_id", dtype=DataType.VARCHAR, max_length=110, is_primary=True),
        FieldSchema(name="vector", dtype=DataType.FLOAT_VECTOR, dim=1536),
        FieldSchema(name="partition_id", dtype=DataType.INT64, is_partition_key=True),
        FieldSchema(name="file_id", dtype=DataType.INT64),
        FieldSchema(name="chunk_id", dtype=DataType.INT64),
        FieldSchema(name="tags", dtype=DataType.ARRAY, element_type=DataType.VARCHAR, max_capacity=1024, max_length=200),
        FieldSchema(name="enable", dtype=DataType.BOOL)
    ]
```
2.We created a new collection named 'gemini_library' with an upgraded vector field dimension:
```python
def dataset_fields() -> List:
    return [
        FieldSchema(name="index_id", dtype=DataType.VARCHAR, max_length=110, is_primary=True),
        FieldSchema(name="vector", dtype=DataType.FLOAT_VECTOR, dim=3072),
        FieldSchema(name="partition_id", dtype=DataType.INT64, is_partition_key=True),
        FieldSchema(name="file_id", dtype=DataType.INT64),
        FieldSchema(name="chunk_id", dtype=DataType.INT64),
        FieldSchema(name="tags", dtype=DataType.ARRAY, element_type=DataType.VARCHAR, max_capacity=1024, max_length=200),
        FieldSchema(name="enable", dtype=DataType.BOOL)
    ]
```
3.Both collections contain data with identical attributes except for the vector field dimension. When attempting to delete data by index_id in the first collection (dataset_library), the operation succeeds.
4.However, when attempting to delete data by the same index_id in the second collection (dataset_library_v2), the operation fails and the data cannot be deleted.

https://github.com/user-attachments/assets/7ad48d36-650e-4255-9bab-671d221714c7

Even when I set the consistency level to 'strong', the issue persists.

### Expected Behavior

Data should be deletable by index_id in both collections.

**Comment by xiaofan-luan** [comment]
might be related to https://github.com/milvus-io/milvus/pull/35390
