### ISSUE TITLE
[Bug]: Strong consistency , delete action, doesnt actually deletes immediately, i could still see the search results

### ISSUE THREAD

**Issue by janaki-sasidhar** [milvus-io/milvus#35389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: I am using zilliz hosted
- Deployment mode(standalone or cluster): Zilliz
- MQ type(rocksmq, pulsar or kafka):    zilliz
- SDK version(e.g. pymilvus v2.0.0rc2): langchain - pymilvus (pymilvus==2.4.4)
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 4vcpu/8gb 
- GPU: No
- Others:
```

### Current Behavior

I am using python-langchain and zilliz hosted milvus. I have set consistency level to "Strong", and I am not using complex boolean expressions either. but still when i issue delete action, it shows the delete count, but i could still query again. My use case is i want to be able to delete and insert new embeddings and do similarity search on the new vectors. Could you please help. 

![image](https://github.com/user-attachments/assets/cdc56f0b-df5b-4979-a06f-430b58a09086)

### Expected Behavior

Old embeddings should be deleted immediately and querying shouldnt return old results that i just  deleted

### Steps To Reproduce

```markdown
expr = f'order_id == {order_id} && source == "{document_type.name}"'
pks = vector_store.get_pks(expr)
vector_store.delete(pks)

pks = vector_store.get_pks(expr)

I could see them again
```

### Milvus Log

![image](https://github.com/user-attachments/assets/b89cbabc-bccc-4c94-8912-2cca3ad17a94)

### Anything else?

No

**Comment by xiaofan-luan** [comment]
might be related to https://github.com/milvus-io/milvus/pull/35390

please try 2.4.7

**Comment by janaki-sasidhar** [comment]
Thanks @xiaofan-luan , is this a bug for deletion actually or just the count that's shown?

**Comment by xiaofan-luan** [comment]
you may lose delete if this bug is triggered

**Comment by yanliang567** [comment]
@janaki-sasidhar please open a ticket in to zilliz cloud support team, they will help to fix the issue. Also I'd close this issue as zilliz cloud questions would be handled in zilliz cloud support team for privacy and security issues.
