### ISSUE TITLE
[Bug]: watch channel stuck forever

### ISSUE THREAD

**Issue by weiliu1031** [milvus-io/milvus#35395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master and 2.4
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

data node try to get all segment info during watch channnel, if too much segment exist,  the rpc may exceed to the max rpc message limit, which will fail the watch progress, and watch channel will stuck forever.

**Comment by yanliang567** [comment]
/unassign
@weiliu1031 how many is too many in this case?

**Comment by xiaofan-luan** [comment]
> /unassign @weiliu1031 how many is too many in this case?

I think couple of thousand segments + enough binlogs
