### ISSUE TITLE
[Bug]: err has degenerated into a new variable, which cannot be captured in defer.

### ISSUE THREAD

**Issue by fengjun2016** [milvus-io/milvus#35412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

err has degenerated into a new variable, making it impossible to capture it in defer, 
and ultimately unable to execute the relevant processing logic that err is not empty.

![截屏2024-08-11 00 17 14](https://github.com/user-attachments/assets/2f5a1b4b-12cf-4219-8d51-f2b144efcede)

**Comment by yanliang567** [comment]
/assign @longjiquan 
please help to double check the review the pr
/unassign
