### ISSUE TITLE
[Bug]: Unable to load the collection

### ISSUE THREAD

**Issue by kish5430** [milvus-io/milvus#35441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4.4
- Deployment mode(standalone or cluster): Cluster
- MQ type(rocksmq, pulsar or kafka): Kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

We created a collection and inserted 1.5 billion vectors. 
When attempting to load the collection, the querynode and datanode pods crashed with OOM errors at 19% due to resource limitations. 
We unloaded the collection, increased the memory for the querynode and datanode pods, and restarted all pods. 
Upon retrying to load the collection, the progress jumped directly from 0% to 19% but then stalled. 
We noticed that one datanode and querynode reached 90% usage and crashed, while the other nodes were only using around 20%.

Then we tried to load the collection with 'collection.load(replica_number=50)' method. There was no pod crashes but still unable to load the collection

### Steps To Reproduce
>>> collection.load(replica_number=50)
RPC error: [get_loading_progress], <MilvusException: (code=101, message=collection not loaded[collection=451400828653517657])>, <Time:{'RPC start': '2024-08-12 22:39:38.687809', 'RPC error': '2024-08-12 22:39:38.852918'}>
RPC error: [wait_for_loading_collection], <MilvusException: (code=101, message=collection not loaded[collection=451400828653517657])>, <Time:{'RPC start': '2024-08-12 22:29:37.771889', 'RPC error': '2024-08-12 22:39:38.858449'}>
RPC error: [load_collection], <MilvusException: (code=101, message=collection not loaded[collection=451400828653517657])>, <Time:{'RPC start': '2024-08-12 22:29:32.098361', 'RPC error': '2024-08-12 22:39:38.858811'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kishorereddyannadi/Library/Python/3.12/lib/python/site-packages/pymilvus/orm/collection.py", line 424, in load
    conn.load_collection(
  File "/Users/kishorereddyannadi/Library/Python/3.12/lib/python/site-packages/pymilvus/decorators.py", line 147, in handler
    raise e from e
  File "/Users/kishorereddyannadi/Library/Python/3.12/lib/python/site-packages/pymilvus/decorators.py", line 143, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kishorereddyannadi/Library/Python/3.12/lib/python/site-packages/pymilvus/decorators.py", line 182, in handler
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kishorereddyannadi/Library/Python/3.12/lib/python/site-packages/pymilvus/decorators.py", line 122, in handler
    raise e from e
  File "/Users/kishorereddyannadi/Library/Python/3.12/lib/python/site-packages/pymilvus/decorators.py", line 87, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kishorereddyannadi/Library/Python/3.12/lib/python/site-packages/pymilvus/client/grpc_handler.py", line 1148, in load_collection
    self.wait_for_loading_collection(collection_name, timeout, is_refresh=_refresh)
  File "/Users/kishorereddyannadi/Library/Python/3.12/lib/python/site-packages/pymilvus/decorators.py", line 147, in handler
    raise e from e
  File "/Users/kishorereddyannadi/Library/Python/3.12/lib/python/site-packages/pymilvus/decorators.py", line 143, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kishorereddyannadi/Library/Python/3.12/lib/python/site-packages/pymilvus/decorators.py", line 182, in handler
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kishorereddyannadi/Library/Python/3.12/lib/python/site-packages/pymilvus/decorators.py", line 122, in handler
    raise e from e
  File "/Users/kishorereddyannadi/Library/Python/3.12/lib/python/site-packages/pymilvus/decorators.py", line 87, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kishorereddyannadi/Library/Python/3.12/lib/python/site-packages/pymilvus/client/grpc_handler.py", line 1168, in wait_for_loading_collection
    progress = self.get_loading_progress(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kishorereddyannadi/Library/Python/3.12/lib/python/site-packages/pymilvus/decorators.py", line 147, in handler
    raise e from e
  File "/Users/kishorereddyannadi/Library/Python/3.12/lib/python/site-packages/pymilvus/decorators.py", line 143, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kishorereddyannadi/Library/Python/3.12/lib/python/site-packages/pymilvus/decorators.py", line 182, in handler
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kishorereddyannadi/Library/Python/3.12/lib/python/site-packages/pymilvus/decorators.py", line 122, in handler
    raise e from e
  File "/Users/kishorereddyannadi/Library/Python/3.12/lib/python/site-packages/pymilvus/decorators.py", line 87, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kishorereddyannadi/Library/Python/3.12/lib/python/site-packages/pymilvus/client/grpc_handler.py", line 1267, in get_loading_progress
    check_status(response.status)
  File "/Users/kishorereddyannadi/Library/Python/3.12/lib/python/site-packages/pymilvus/client/utils.py", line 62, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=101, message=collection not loaded[collection=451400828653517657])>
>>> 
_No response_

**Comment by congqixia** [comment]
`replica_number=50` meaning milvus shall load same collection 50 times in different sets of querynodes. Quick question, does your cluster have enough querynodes to hold 50 replicas?

**Comment by kish5430** [comment]
> `replica_number=50` meaning milvus shall load same collection 50 times in different sets of querynodes. Quick question, does your cluster have enough querynodes to hold 50 replicas?

Please ignore above process.

I attempted to load the collection without using replicas. During the process, one DataNode's memory usage reached 92%, causing it to restart. This pattern continued with other DataNodes, each reaching over 90% memory usage and then restarting. The load is not being evenly distributed across all DataNodes simultaneously, leading to the collection load failing.

**Comment by congqixia** [comment]
Can I assume that your collection has only one shard? This means that the whole work load could be handled only be single datanode. The current solution might be scale-up your datanode memory, not scale-out

**Comment by kish5430** [comment]
> Can I assume that your collection has only one shard? This means that the whole work load could be handled only be single datanode. The current solution might be scale-up your datanode memory, not scale-out

Yes, this collection has only one shard, but no OOM errors have been found in the data nodes. Are you still recommending increasing the data node memory and reducing the number of data node replicas?

**Comment by kish5430** [comment]
> > Can I assume that your collection has only one shard? This means that the whole work load could be handled only be single datanode. The current solution might be scale-up your datanode memory, not scale-out
> 
> Yes, this collection has only one shard, but no OOM errors have been found in the data nodes. Are you still recommending increasing the data node memory and reducing the number of data node replicas?

I increased the memory for the data node and reduced the number of replicas, but loading is still failing.

**Comment by congqixia** [comment]
> Error: 2024/08/14 02:06:53.281 +00:00] [WARN] [querynodev2/services.go:315] ["failed to load growing segments"] [traceID=1777f0303ebb3f44ca3c721448bc9665] [collectionID=451400828653517657] [channel=isds-milvus-prod-east2-2-vista-rootcoord-dml_7_451400828653517657v0] [currentNodeID=3130] [error="load segment failed, OOM if load, maxSegmentSize = 1663.657211303711 MB, memUsage = 20965.7265625 MB, predictMemUsage = 366486.11928367615 MB, totalMem = 102400 MB thresholdFactor = 0.900000"]

This error means the memory of querynode is not enough to load even the growing segments. This problem is caused by too many growing segments left without flushing them. It shall be fixed when data node success to go up and serving. You could trigger `Flush` operation to make sure all gorwing segment turned into flushed ones.

**Comment by yanliang567** [comment]
please also check the building index progress, 
`utility.index_building_progress(collection_name, index_name)`
i guess you could add more resources for index nodes as well to speed up the building index progress.

**Comment by kish5430** [comment]
> > Error: 2024/08/14 02:06:53.281 +00:00] [WARN] [querynodev2/services.go:315] ["failed to load growing segments"] [traceID=1777f0303ebb3f44ca3c721448bc9665] [collectionID=451400828653517657] [channel=isds-milvus-prod-east2-2-vista-rootcoord-dml_7_451400828653517657v0] [currentNodeID=3130] [error="load segment failed, OOM if load, maxSegmentSize = 1663.657211303711 MB, memUsage = 20965.7265625 MB, predictMemUsage = 366486.11928367615 MB, totalMem = 102400 MB thresholdFactor = 0.900000"]
> 
> This error means the memory of querynode is not enough to load even the growing segments. This problem is caused by too many growing segments left without flushing them. It shall be fixed when data node success to go up and serving. You could trigger `Flush` operation to make sure all gorwing segment turned into flushed ones.

When I tried to execute utility.flush_all(), it has been displaying the following messages for the past 12 hours without any progress. No pods have crashed."

>>> utility.flush_all()
E0814 08:02:36.829494000 6200356864 hpack_parser.cc:999]               Error parsing 'content-type' metadata: invalid value
E0814 08:03:36.955125000 6200356864 hpack_parser.cc:999]               Error parsing 'content-type' metadata: invalid value
E0814 08:04:37.102384000 6200356864 hpack_parser.cc:999]               Error parsing 'content-type' metadata: invalid value
E0814 08:05:37.351339000 6200356864 hpack_parser.cc:999]               Error parsing 'content-type' metadata: invalid value
[flush_all] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNKNOWN, Stream removed>
E0814 08:06:37.734810000 6200356864 hpack_parser.cc:999]               Error parsing 'content-type' metadata: invalid value
[flush_all] retry:5, cost: 0.81s, reason: <_MultiThreadedRendezvous: StatusCode.UNKNOWN, Stream removed>

**Comment by kish5430** [comment]
> please also check the building index progress, `utility.index_building_progress(collection_name, index_name)` i guess you could add more resources for index nodes as well to speed up the building index progress.

Please find below result and suggest
>>> utility.index_building_progress("CVL_image_vfm","embedding_index")
{'total_rows': 1344094667, 'indexed_rows': 1344094667, 'pending_index_rows': 0}
>>> collection.num_entities
1466464075

**Comment by kish5430** [comment]
Currently we have configured 30 querynodes and each querynode having 180GB memory. But still getting below OOM issues.

Error:
[2024/08/15 14:53:47.268 +00:00] [INFO] [task/executor.go:136] ["execute action done, remove it"] [taskID=1723522881759] [step=0] 
[error="load segment failed, OOM if load, maxSegmentSize = 3628.4139099121094 MB,  memUsage = 34450.08984375 MB, 
predictMemUsage = 278614.65684223175 MB, totalMem = 184320 MB thresholdFactor = 0.900000"]

**Comment by yanliang567** [comment]
could you please share the metrics screenshots for querynode? also please share the collection schema info, i guess the delegator has too much workloads than the other. @kish5430

**Comment by kish5430** [comment]
@yanliang567 Please find below details.

Collection Schema and entities:
>>> collection.schema
{'auto_id': False, 'description': 'Vista embeddings: 256 dimensions', 'fields': [{'name': 'uuid', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 50}, 'is_primary': True, 'auto_id': False}, {'name': 'phash', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 50}}, {'name': 'embedding', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 256}}, {'name': 'path', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 512}}, {'name': 'meta_data', 'description': '', 'type': <DataType.JSON: 23>}, {'name': 'dataset_id', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 50}}], 'enable_dynamic_field': False}
>>> 
>>> 

>>> collection.num_entities
1685465315

>>> utility.index_building_progress("CVL_image_vfm","embedding_index")
{'total_rows': 1528380301, 'indexed_rows': 1528380301, 'pending_index_rows': 0}



Querynode Metrics:
<img width="1498" alt="image" src="https://github.com/user-attachments/assets/5b76cb52-509f-407a-856b-e69bd5c434a6">

<img width="1497" alt="image" src="https://github.com/user-attachments/assets/9f2d016b-4bc9-4feb-90f4-2de40858e6ba">

<img width="1488" alt="image" src="https://github.com/user-attachments/assets/6e4c5f46-6264-4066-9d69-a0236405914e">

**Comment by yanliang567** [comment]
please hover the cursor to Segment Loaded Num, let's check the growing/sealed segments.  also please share the Runtime metrics screenshots.

**Comment by kish5430** [comment]
Segment Loaded Num:
<img width="1055" alt="image" src="https://github.com/user-attachments/assets/c8337dd1-cf62-4d10-974b-f433802d440a">


Runtime Metrics:
<img width="1475" alt="image" src="https://github.com/user-attachments/assets/5a766330-ef37-4ff4-bd8c-d24e126a115d">
<img width="1464" alt="image" src="https://github.com/user-attachments/assets/dfc31036-0086-41cc-9214-ddbe6f04ad2c">

<img width="987" alt="image" src="https://github.com/user-attachments/assets/d24afb4c-1b70-451b-a318-efae2690c48a">

**Comment by xiaofan-luan** [comment]
<img width="480" alt="image" src="https://github.com/user-attachments/assets/241123a7-a9e4-4a4d-b28c-0942baa6178c">

**Comment by xiaofan-luan** [comment]
memory seems to be really balanced under this case.

I guess what you said "We noticed that one datanode and querynode reached 90% usage and crashed, while the other nodes were only using around 20%." is cpu usage.

I think you need to think of the following things to support 1.5 billion vectors. (Dimension also need to be considered)

1. how many memories you need? if use hnsw you will roughly need 10TB memory, which will be huge. use DiskANN you need at least 1-2TB memories.
2. for 1.5 billion vectors, we would recommend to create 4-8 shards in advance. 1 shard might be to small for it.
3. You need more datanode and indexnode(4 datanode is recommend, indexnode the more the better)

I'd like to give you extra help if necessary. Contact me at james.luan@zilliz.com

**Comment by kish5430** [comment]
HI @xiaofan-luan We are no longer seeing the issue where a datanode or querynode reaches 90% and crashes.
Please find below details and suggest.

1. We are using 'IVF_FLAT' .
2. We have only defaults shards that is 1.
3. We have configured the recommended and index nodes. Plz check below screenshot
<img width="396" alt="image" src="https://github.com/user-attachments/assets/3da534c3-33b0-4698-8e25-4488a78cb024">

**Comment by xiaofan-luan** [comment]
> HI @xiaofan-luan We are no longer seeing the issue where a datanode or querynode reaches 90% and crashes. Please find below details and suggest.
> 
> 1. We are using 'IVF_FLAT' .
> 2. We currently have only the default shard, which is set to 1.
> 3. We have configured the recommended index nodes. Please see the screenshot below for details.
> 
> <img alt="image" width="396" src="https://private-user-images.githubusercontent.com/45558360/358659141-3da534c3-33b0-4698-8e25-4488a78cb024.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MzExMzksIm5iZiI6MTcyMzgzMDgzOSwicGF0aCI6Ii80NTU1ODM2MC8zNTg2NTkxNDEtM2RhNTM0YzMtMzNiMC00Njk4LThlMjUtNDQ4OGE3OGNiMDI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDE3NTM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNGIyYTA1ZmNiMjgxYTc5ZmM4MDg0MGMxODhlMGViMjAwZTBmY2M2OWY0NDI0N2ZkY2NiMTRlNzNmY2MxM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QLrCJwlO7a3k0cp9BxW2TIK3VD9UZfvdOQgB_xUiiaU">

what is the vector dimension? Let me assuming we are using 768(OpenAI embedding)

Quick math

you need roughly 5TB memory for IVFFLAT
you have 30 *180GB ~= roughly 5.4TB memory. so I'm assuming memory is tight but should work.

I would suggest you to rebuild a cluster with 8 shards, and change the cluster with 32 query nodes.

Other than that, try
1. increase the segment size to 4G to improve performance
2. if you still have 20-30% extra memory, try HSNW index
3. you probably need more cpus on index node
4. you don't really need 5 datanodes, unless you have more shards. once you have 8 shards, 4 datanodes is recommended.
5. increase the cpu of datacoord to at least 2c8g
6. take care of the proxy. Some times proxy can become a performance bottleneck, especially under high QPS or large topk, you probably need HPA on top it.

Good luck with it!

**Comment by kish5430** [comment]
> > HI @xiaofan-luan We are no longer seeing the issue where a datanode or querynode reaches 90% and crashes. Please find below details and suggest.
> > 
> > 1. We are using 'IVF_FLAT' .
> > 2. We currently have only the default shard, which is set to 1.
> > 3. We have configured the recommended index nodes. Please see the screenshot below for details.
> > 
> > <img alt="image" width="396" src="https://private-user-images.githubusercontent.com/45558360/358659141-3da534c3-33b0-4698-8e25-4488a78cb024.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MzExMzksIm5iZiI6MTcyMzgzMDgzOSwicGF0aCI6Ii80NTU1ODM2MC8zNTg2NTkxNDEtM2RhNTM0YzMtMzNiMC00Njk4LThlMjUtNDQ4OGE3OGNiMDI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDE3NTM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNGIyYTA1ZmNiMjgxYTc5ZmM4MDg0MGMxODhlMGViMjAwZTBmY2M2OWY0NDI0N2ZkY2NiMTRlNzNmY2MxM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QLrCJwlO7a3k0cp9BxW2TIK3VD9UZfvdOQgB_xUiiaU">
> 
> what is the vector dimension? Let me assuming we are using 768(OpenAI embedding)
> 
> Quick math
> 
> you need roughly 5TB memory for IVFFLAT you have 30 *180GB ~= roughly 5.4TB memory. so I'm assuming memory is tight but should work.
> 
> I would suggest you to rebuild a cluster with 8 shards, and change the cluster with 32 query nodes.
> 
> Other than that, try
> 
> 1. increase the segment size to 4G to improve performance
> 2. if you still have 20-30% extra memory, try HSNW index
> 3. you probably need more cpus on index node
> 4. you don't really need 5 datanodes, unless you have more shards. once you have 8 shards, 4 datanodes is recommended.
> 5. increase the cpu of datacoord to at least 2c8g
> 6. take care of the proxy. Some times proxy can become a performance bottleneck, especially under high QPS or large topk, you probably need HPA on top it.
> 
> Good luck with it!

@xiaofan-luan Here are some points for your review and suggestions:

1.  We're using 256 dimensions for this collection.
2.  You suggested rebuild the cluster with 8 shards and 32 query nodes. Should this be a new cluster or a new collection?
3.  I plan to add more CPUs to the index nodes.
4.  If we have multiple collections with different shard configurations, what's the recommended number of data nodes?
5.  I’ll increase the CPUs for the data coordinator.
6.  The current proxy resources are sufficient, but I’ll scale them up if needed.


Thanks

**Comment by yanliang567** [comment]
@kish5430 is it still an issue for you, or we can just track it in #36318?

**Comment by yanliang567** [comment]
lets track in the issue above
