### ISSUE TITLE
[Bug]: Only one queryNode performs the loading job when the index_type is DISKANN.

### ISSUE THREAD

**Issue by dragonborn-lxc** [milvus-io/milvus#35440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.10
- Deployment mode(standalone or cluster): cluster on K8s
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.4.0
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU:
- Others:
```

### Current Behavior

I have added podAntiAffinity configuration to ensure that the queryNode pods will not be deployed on the same K8s node.
When the index_type is IVF_FLAT, I noticed the following log in two queryNode pods:
![image](https://github.com/user-attachments/assets/0367f6c5-bbed-4fba-98b8-c8d93f157e52)
![image](https://github.com/user-attachments/assets/97b7d0be-894d-4289-bad7-bb82a5d956f6)
and I observed that the memory usage in each queryNode pod was increasing.
However, when the index_type is DISKANN, only one queryNode displayed the aforementioned log, and the index files were created in the this pod:
![image](https://github.com/user-attachments/assets/0116e641-ae82-431d-9c68-c353319e02f0)
but the index files were not generated in the other queryNode.
The image below shows the information for two queryNodes:
![image](https://github.com/user-attachments/assets/4d0c0ae7-cff0-45c8-a204-bd1682b930ff)

### Expected Behavior

I think that when using DISKANN, multiple queryNodes should generate the index files evenly, just like using IVF_FLAT. Is this right?

**Comment by yanliang567** [comment]
I guess you have streaming data inserting into the collection when observing the memory usage of query node. or if you only insert a few data, that's caused by diskann index has a bigger segment size and there is only one segment need to be loaded. 
I suggest you to check the metric of query node, you can see the segment loaded num in different querynodes:
![image](https://github.com/user-attachments/assets/434ef515-619d-4339-85ac-3ec4e67023e3)

/assign @dragonborn-lxc 
/unassign

**Comment by dragonborn-lxc** [comment]
> I guess you have streaming data inserting into the collection when observing the memory usage of query node. or if you only insert a few data, that's caused by diskann index has a bigger segment size and there is only one segment need to be loaded. I suggest you to check the metric of query node, you can see the segment loaded num in different querynodes: ![image](https://private-user-images.githubusercontent.com/82361606/357654441-434ef515-619d-4339-85ac-3ec4e67023e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MDQ5MjIsIm5iZiI6MTcyMzYwNDYyMiwicGF0aCI6Ii84MjM2MTYwNi8zNTc2NTQ0NDEtNDM0ZWY1MTUtNjE5ZC00MzM5LTg1YWMtM2VjNGU2NzAyM2UzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDAzMDM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxOTY1Mjc2NmY0NmM2ZGIyYmE0MjE4MzZlM2NiN2E0OGQ5ZjhjYzY3NDFiMmEyZWQzNDdjN2RkZThlOWJlNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Jw6MOo2PcAoFrsRwD8lRH_kX4vbG5t4yPD7p7CGEfxo)
> 
> /assign @dragonborn-lxc /unassign

Yes, I have observed that when more data is added, another query node will be utilized :).
Additionally, I have another question about DISKANN: why the read speed is limited to 27MBps when performing a search?
![image](https://github.com/user-attachments/assets/26a2a910-41e7-4bff-b3cd-5c3aa5fd76bb)
I can confirm that the minimum throughput of this disk is 170MBps. Are there any specific configurations related to limiting read speed in DISKANN?

**Comment by yanliang567** [comment]
how many data are we talking about here? maybe it is easier to set shard_number=4 when creating a collection.
/assign @dragonborn-lxc

**Comment by dragonborn-lxc** [comment]
> how many data are we talking about here? maybe it is easier to set shard_number=4 when creating a collection. /assign @dragonborn-lxc

3 million.
I found a parameter named `LoadNumThreadRatio` in https://github.com/milvus-io/milvus/blob/v2.3.10/configs/milvus.yaml which was not mentioned in the configuration document. What does this parameter mean?
![image](https://github.com/user-attachments/assets/8c490122-05db-4718-8ade-a480fc6d9a98)

**Comment by dragonborn-lxc** [comment]
I found that when using the DISKANN index, the disk's IOPS are not fully utilized, the limit is 11800, but only reaching around 7000, so how to improve the utilization of IOPS?

**Comment by dragonborn-lxc** [comment]
I modified the parameters below, but it seems that the IOPS utilization rate has not improved.
![image](https://github.com/user-attachments/assets/ac34f936-5248-459d-ab72-12da7d75ac22)

**Comment by dragonborn-lxc** [comment]
@yanliang567

**Comment by xiaofan-luan** [comment]
1. we'd recommened you to use 2.3.21
2. How large is each querynode? for 4 querynode (assume it's 4c16g) I think you don't really need disk index. Memory is good enough for memory index.
3. you can try to increase knowhereThreadPoolNumRatio see if there are any performance improvement. How many iops is also related top topk and many other parameters

We need more details, like your pod size, your required qps and your search to give your more detailed advice

**Comment by dragonborn-lxc** [comment]
> 1. we'd recommened you to use 2.3.21
> 2. How large is each querynode? for 4 querynode (assume it's 4c16g) I think you don't really need disk index. Memory is good enough for memory index.
> 3. you can try to increase knowhereThreadPoolNumRatio see if there are any performance improvement. How many iops is also related top topk and many other parameters
> 
> We need more details, like your pod size, your required qps and your search to give your more detailed advice

Our K8s has 4 nodes, each node's size is 24C96G. I have currently imported approximately 3 million data for testing DISKANN. In reality, we plan to import about 200 million data into Milvus, so I think the node size is not enough for using IVF_FLAT.
I attempted to adjust the value of knowhereThreadPoolNumRatio, but it seems to have no impact as the IOPS remains around 7000 (the limit is 11800).

**Comment by dragonborn-lxc** [comment]
@xiaofan-luan

**Comment by xiaofan-luan** [comment]
4 * 96G is not enough for 200m data(768 dim). that is true

On the other size, IOPs might be another headable. even if we can fully utilize 11800 that won't be enough for diskann(bases on qps you are looking or)

Suggestions:
1. try to tune segment size to larger(by default is 512MB, for you machine size I recommend to change it to 4GB)
2. try to find better performance disk 
3.  did you check what is the disk util and some system metrics? So far I don't think there is not too much we can do on the open source side.

**Comment by xiaofan-luan** [comment]
if it's possible maybe simply try zilliz cloud, host 200m data use 40CU which takes you 7000$/40000¥ per month
