### ISSUE TITLE
[Bug]: The password can contain`: `separators, which may cause errors when parsing the token as user+password.

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#35449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master/2.4/2.3
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Username is `root`, password is `N7:<u!u5;LB4m$kU9D9WhE,Vg~7{04Jg`.
If you connect using the username and password method, there's no issue, but if you use a token='root:N7:<uLB4m$kU9D9WhE,Vg~7{04Jg' you'll run into problems.

**Comment by zhuwenxing** [comment]
/assign @SimFG 
PTAL

**Comment by yanliang567** [comment]
so we cannot set colon in the password?

**Comment by SimFG** [comment]
@yanliang567 we can, just a little adjustment.

**Comment by zhuwenxing** [comment]
It is a mistake in test. Some symbols were omitted when concatenating tokens, resulting in password parsing errors.
