### ISSUE TITLE
[Enhancement]: Mark query node as read only after suspend

### ISSUE THREAD

**Issue by weiliu1031** [milvus-io/milvus#35493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

after querynode has been suspended, it's not allow to load segment/channel on it, which means the node is read only. to be compatible with resource group design, after query node has been suspend, we remove it from it's original resource group, make it a read only query node in replica. then two things will happens:

it's original resource group will be lacking of query nodes, query coord will assign new node to it.
querycoord will try to move out all segments/channels after querynode has been suspended

**Comment by xiaofan-luan** [comment]
we already have the stopping node.
DO we really need some mechanism new? think about it.
