### ISSUE TITLE
[Bug]: deletion problem

### ISSUE THREAD

**Issue by zs856** [milvus-io/milvus#35491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.8
- Deployment mode(standalone or cluster): standalone 
- MQ type(rocksmq, pulsar or kafka):    None
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.4.5
- OS(Ubuntu or CentOS): Ubuntu 22.04
- CPU/Memory: 32GB
- GPU: None
- Others:
```

### Current Behavior

Today, while I was following the official documentation to practice the deletion operation, I found that the data was not successfully deleted. You can check the uploaded .ipynb file to see the code I ran. The development environment can also be reproduced using pyproject.toml and Docker Compose.

[milvus-deletion-bug.zip](https://github.com/user-attachments/files/16622982/milvus-deletion-bug.zip)

### Expected Behavior

I expect the data in the Collection to be successfully deleted as it is executed in the code of the official documentation.

### Steps To Reproduce

```markdown
1. Deploy milvus using the docker compose file I provided
2. Set up development environment using the pyproject (1).toml I provided
3. Run the code inside 删除bug.ipynb
```

**Comment by XuanYang-cn** [comment]
@zs856 Hi, thx for the detailed bug report and reproducable codes. 
I noticed that you're using`client.get_collection_stats(collection_name='quick_setup')` to verify correcteness of deletion. Accually get_collection_stats are neither realtime nor accurate.

Please try to use query(count(*)), or query() those deleted pks with strong consistency level. See https://milvus.io/docs/get-and-scalar-query.md#Use-Advanced-Operators
```python
client.query(...., output_fields=["count(*)"], consistency_level="Strong")
```
