### ISSUE TITLE
[Enhancement]: Optimize the retrieval operations for dynamic fields.

### ISSUE THREAD

**Issue by czs007** [milvus-io/milvus#35514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

For collections with the dynamic field feature enabled, when retrieving data with dynamic fields specified in the output fields (which are not part of the static schema), the kernel returns all data from the dynamic field column. When there is a high concurrency of big top-k queries, the proxy faces significant pressure on both memory and downstream transmission bandwidth.

In light of the aforementioned situation, it is essential to modify the kernel to return only a portion of the data from the dynamic field, based on the specified dynamic field list, rather than the complete dataset.

### Why is this needed?

Prevent proxy out-of-memory errors and reduce retrieval latency.

**Comment by xiaofan-luan** [comment]
this is actually a great optimization, especially think of the network bandwidtch
