### ISSUE TITLE
[Bug]:  Service Fails to Restart with GRPC Connection Errors After Being Killed with SIGKILL

### ISSUE THREAD

**Issue by shizheng163** [milvus-io/milvus#35518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.0
- Deployment mode：standalone
- MQ type： rocksmq
- OS：Ubuntu 20.04
```

### Current Behavior

I am encountering an issue when restarting a Milvus service container managed by docker-compose.  When I start the service using docker-compose up and then forcefully terminate it (e.g., with Ctrl+C), the service fails to restart properly.  Specifically, upon attempting to restart the service, I encounter numerous gRPC errors related to failed connection attempts and session verification failures.

The service starts successfully when launched for the first time, but subsequent attempts to restart it after being forcefully killed (using kill -9) result in these gRPC errors.  The service's entrypoint script includes signal handling logic to attempt a graceful shutdown (SIGTERM and SIGINT), but this logic does not seem to be executed when the service is stopped using docker-compose stop.

The entrypoint script performs configuration modifications and starts the Milvus service, but the service does not properly handle the termination signal, leading to issues during the next startup attempt.

```Dockerfile
FROM milvusdb/milvus:v2.4.0

COPY ./configs /milvus/configs
COPY ./entrypoint.sh /milvus
RUN chmod 777 /milvus/entrypoint.sh

EXPOSE 19530
EXPOSE 9091
EXPOSE 2379

CMD ["bash", "/milvus/entrypoint.sh"]
```

```bash
if [ -z "${MYENV_MILVUS_VOLUMES}" ]; then
  echo "MYENV_MILVUS_VOLUMES environment variable is not set"
  exit 1
fi

find /milvus/configs -type f -name '*' -exec sed -i "s|MYENV_MILVUS_VOLUMES|${MYENV_MILVUS_VOLUMES}|g" {} +

milvus run standalone

# exec milvus run standalone
```

I use docker-compose to start container, yaml config is

```yaml
services:
  mymlivus:
    image: mymlivus
    tty: true
    command: "bash /milvus/entrypoint.sh"
    network_mode: host
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./milvus_volumes:/milvus_volumes
    env_file:
      - .env
```

I used `exec milvus run standalone` to resolved the problem, but the problem still existed , I can't ensure my process alwaya normal closed at future.

### Steps To Reproduce

```markdown
1. bash /milvus/entrypoint.sh
2. (another terminal) ps -ef | grep milvus
3. (another terminal) kill -9 {PID} # milvus PID
4. bash /milvus/entrypoint.sh # start the milvus again, the problem will appear
```

### Milvus Log

Error log(a part of whole log)：
```
master-1  | [2024/08/16 07:20:53.139 +00:00] [WARN] [grpcclient/client.go:408] ["call received grpc error"] [clientRole=proxy-2] [error="rpc error: code = Canceled desc = grpc: the client connection is closing"]
master-1  | [2024/08/16 07:20:53.139 +00:00] [WARN] [grpcclient/client.go:408] ["call received grpc error"] [clientRole=querynode-2] [error="rpc error: code = Unknown desc = node not match[expectedNodeID=2][actualNodeID=3]"]
master-1  | [2024/08/16 07:20:53.139 +00:00] [WARN] [grpcclient/client.go:489] ["start to reset connection because of specific reasons"] [client_role=querynode-2] [error="rpc error: code = Unknown desc = node not match[expectedNodeID=2][actualNodeID=3]"]
master-1  | [2024/08/16 07:20:53.156 +00:00] [WARN] [grpcclient/client.go:408] ["call received grpc error"] [clientRole=querynode-2] [error="rpc error: code = Unknown desc = node not match[expectedNodeID=2][actualNodeID=3]"]
master-1  | [2024/08/16 07:20:53.156 +00:00] [WARN] [grpcclient/client.go:489] ["start to reset connection because of specific reasons"] [client_role=querynode-2] [error="rpc error: code = Unknown desc = node not match[expectedNodeID=2][actualNodeID=3]"]
master-1  | [2024/08/16 07:20:53.362 +00:00] [WARN] [grpcclient/client.go:408] ["call received grpc error"] [traceID=887c5db42668e7ef3c8cad034df9ff94] [clientRole=datanode-2] [error="rpc error: code = Unknown desc = node not match[expectedNodeID=2][actualNodeID=3]"]
master-1  | [2024/08/16 07:20:53.362 +00:00] [WARN] [grpcclient/client.go:408] ["call received grpc error"] [clientRole=proxy-2] [error="rpc error: code = Unknown desc = node not match[expectedNodeID=2][actualNodeID=3]"]
master-1  | [2024/08/16 07:20:53.362 +00:00] [WARN] [grpcclient/client.go:408] ["call received grpc error"] [traceID=e5176d205519c73a34bc366666414ed1] [clientRole=querynode-2] [error="rpc error: code = Unknown desc = node not match[expectedNodeID=2][actualNodeID=3]"]
master-1  | [2024/08/16 07:20:53.363 +00:00] [WARN] [grpcclient/client.go:373] ["fail to get session"] [traceID=887c5db42668e7ef3c8cad034df9ff94] [clientRole=datanode-2] [error="context canceled"]
```

**Comment by xiaofan-luan** [comment]
you probably need to wait until session timeout on etcd.
By default it takes 30-45 seconds. You can also manually kill the session on etcd.

**Comment by yanliang567** [comment]
/assign @shizheng163 
please retry as comments above
/unassign

**Comment by shizheng163** [comment]
thank you, I will verify the comment ASAP at next week.

**Comment by shizheng163** [comment]
I didn't connect to the ETCD service to delete the session because it was foreign to me.
I tried to retry immediately after the kill -9 ended the service, and it did return to normal after a while.
However, if I do not retry immediately after kill -9 ends the service, but wait a few minutes and try again, it still takes some time to use.
I don't know if the above phenomenon is normal, this is just a report, not my issue

**Comment by xiaofan-luan** [comment]
after Kill -9, it might need  45s for the session to be expired.
If you don't bring up the service, docker might bring up the  service automatically. So I guess you don't really need to bring it up by yourself
