### ISSUE TITLE
[Bug]: lock was not released in time

### ISSUE THREAD

**Issue by fengjun2016** [milvus-io/milvus#35524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![截屏2024-08-16 19 26 07](https://github.com/user-attachments/assets/dbbaf7f8-d997-4d5c-b979-db2662fa55d0)

**Comment by xiaofan-luan** [comment]
seems to be a good catch. why we remove this pr?
@fengjun2016 
hi feng, I saw your contribution and it looks amazing. Shall we emeet each other? My email, james.luan@zilliz.com

**Comment by chyezh** [comment]
> seems to be a good catch. why we remove this pr? @fengjun2016 hi feng, I saw your contribution and it looks amazing. Shall we emeet each other? My email, [james.luan@zilliz.com](mailto:james.luan@zilliz.com)

`ContextCond` is the semantics of condition variable. The wait operation releases the mutex lock until it is awakened, and if err is returned, it means that the lock will not be held after waiting for timeout.
So it's not a bug here.

**Comment by xiaofan-luan** [comment]
> ContextCond

Thanks for the clarification.
