### ISSUE TITLE
[Bug]: After restarting the milvus cluster, one of the querynodes takes up a lot of memory

### ISSUE THREAD

**Issue by liuzh-sa** [milvus-io/milvus#35538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.4.4
- Deployment mode(standalone or cluster): cluster with 6 querynodes
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS): BigCloud Enterprise Linux For Euler 22.10
- CPU/Memory: 16C 84G three nodes
- GPU: 
- Others:
```

### Current Behavior

All virtual machines in the milvus cluster were restarted due to misoperation. After recovery, one of the querynodes occupied a lot of memory and would not be released.
![image](https://github.com/user-attachments/assets/33f2f594-6563-4900-904a-29748163788a)
![image](https://github.com/user-attachments/assets/17145345-3de9-47d6-8789-fdc15817633c)

### Expected Behavior

The memory usage of 6 querynodes should be balanced

### Steps To Reproduce

```markdown
Because it is a production environment, I cannot restart the cluster to reproduce this problem.
```

### Milvus Log

The log of the querynode that takes up a lot of memory is as follows:
![image](https://github.com/user-attachments/assets/55c74829-8048-4a99-8bc0-84338fc63ad2)
The logs of other querynodes are as follows：
![image](https://github.com/user-attachments/assets/c6a20d61-245f-4404-8e3f-63f5d899eb83)
The log of querycoord is as follows:
![image](https://github.com/user-attachments/assets/ffc2b69f-57f9-46f3-90f9-8ae79a693119)

**Comment by liuzh-sa** [comment]
I deployed attu, and I found that the system-view in attu only showed 1 querynode.
![image](https://github.com/user-attachments/assets/fb23a040-5295-4af2-9da3-481b12b015ca)

**Comment by xiaofan-luan** [comment]
did you know why the other querynodes didn't brought up?
And you have 9 datanodes, that seems to be very much

**Comment by liuzh-sa** [comment]
other querynodes are running 
![image](https://github.com/user-attachments/assets/960e2e74-6ec9-4bca-898d-403124bd17e9)
There are no 9 datanodes, this is just what is shown on attu

**Comment by xiaofan-luan** [comment]
Could you please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation? For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.

**Comment by xiaofan-luan** [comment]
it seems that your other querynode is not registerted successfully to etcd.

**Comment by liuzh-sa** [comment]
> Could you please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation? For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.

[milvus-log.tar.gz](https://github.com/user-attachments/files/16683929/milvus-log.tar.gz)

**Comment by liuzh-sa** [comment]
> it seems that your other querynode is not registerted successfully to etcd.
the log shows registered is successfully
![image](https://github.com/user-attachments/assets/893a506e-d969-4add-b908-cce403369dbc)

**Comment by xiaofan-luan** [comment]
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/196ed326-db3c-4346-9616-1c029376bda3">

it seems that all the pod has been stucked

**Comment by xiaofan-luan** [comment]
this is the last log we can see.
Maybe you can reboot all the querynode.

**Comment by liuzh-sa** [comment]
> <img alt="image" width="1440" src="https://private-user-images.githubusercontent.com/83447078/359692023-196ed326-db3c-4346-9616-1c029376bda3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMDIyNjksIm5iZiI6MTcyNDIwMTk2OSwicGF0aCI6Ii84MzQ0NzA3OC8zNTk2OTIwMjMtMTk2ZWQzMjYtZGIzYy00MzQ2LTk2MTYtMWMwMjkzNzZiZGEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDAwNTkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMDQzNDVhNThkYTM5ZGZhNTJmOTlhYTdmYzMzYzg4N2JlNzc4NjYzZDkzMGZhMDY3MDAzMjQ2ODk2NGJmNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4a9iXyorSGJmiKrugb0VxVNQgebglsYF9RqccCVoRJA">
> it seems that all the pod has been stucked

What does pod stucked mean?

**Comment by xiaofan-luan** [comment]
this is the last log we can see .. register success, and that is a log from 08/12

**Comment by liuzh-sa** [comment]
> this is the last log we can see. Maybe you can reboot all the querynode.



> this is the last log we can see .. register success, and that is a log from 08/12

**Comment by liuzh-sa** [comment]
> this is the last log we can see .. register success, and that is a log from 08/12

As I mentioned before, the entire cluster was restarted due to a virtual machine restart on August 12th. Since then, only one querynode has taken up a lot of memory.

**Comment by liuzh-sa** [comment]
After restarted, other querynodes don’t seem to be working.

**Comment by liuzh-sa** [comment]
What is the root cause of the problem?

**Comment by xiaofan-luan** [comment]
> > this is the last log we can see .. register success, and that is a log from 08/12
> 
> As I mentioned before, the entire cluster was restarted due to a virtual machine restart on August 12th. Since then, only one querynode has taken up a lot of memory.

that's because the other querynode are stucked. We don't know why but might be a K8s issue?

**Comment by liuzh-sa** [comment]
> > > this is the last log we can see .. register success, and that is a log from 08/12
> > 
> > 
> > As I mentioned before, the entire cluster was restarted due to a virtual machine restart on August 12th. Since then, only one querynode has taken up a lot of memory.
> 
> that's because the other querynode are stucked. We don't know why but might be a K8s issue?

Is it just a matter of restarting those stucked pods?

**Comment by xiaofan-luan** [comment]
maybe you can do a pprof all those pods see where the goroutines are. 
Yes simply reboot the cluster should work

**Comment by liuzh-sa** [comment]
> maybe you can do a pprof all those pods see where the goroutines are. Yes simply reboot the cluster should work

thanks  i will try.
