### ISSUE TITLE
nvidia-docker run error

### ISSUE THREAD

**Issue by atomtony** [milvus-io/milvus#356]
Welcome to use Milvus by Zilliz!
Milvus release version: v0.3.1 built at 2019-07-24 13:57.15
Loading configuration from: ../conf/server_config.yaml
Initial log config from: ../conf/log_config.conf
Error: cpu_cache_capacity execeed system memory
/opt/docker-entrypoint.sh: line 9: exec: start: not found

**Comment by jielinxu** [comment]
You can troubleshoot this problem following below steps:

1. Download config files to /home/<$USER>/milvus/conf by `wget https://raw.githubusercontent.com/milvus-io/docs/master/assets/server_config.yaml`

2. Change `cpu_cache_capacity` to a suitable value. (The default value for `cpu_cache_capacity` is 16 GB. The sum of `cpu_cache_capacity` and `insert_buffer_size` must be less than your total CPU memory size.)

3. Restart Milvus by `docker run -td --gpus all -e "TZ=Asia/Shanghai" -p 19530:19530 -p 8080:8080 -v /home/<$USER>/milvus/db:/opt/milvus/db -v /home/<$USER>/milvus/conf:/opt/milvus/conf -v /home/<$USER>/milvus/logs:/opt/milvus/logs milvusdb/milvus:latest`

**Comment by gujun720** [comment]
Hi, Milvus 0.3.1 is a little bit out of date.
You can follow below instructions to run the demo on the latest version 0.5.3.
https://github.com/milvus-io/bootcamp/tree/0.5.2

**Comment by cydrain** [comment]
This is config issue.
"Error: cpu_cache_capacity execeed system memory" means "cpu_cache_capacity" in server_config.yaml is set too big, you need set that value smaller.

This is not related with nvidia-docker.
