### ISSUE TITLE
Get entities should return empty after insert entities with disable autoflush

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#3560]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
The test case is:
```
    def test_insert_disable_auto_flush(self, connect, collection):
        '''
        target: test insert entities, with disable autoflush
        method: disable autoflush and insert, get entity
        expected: the count is equal to 0
        '''
        disable_flush(connect)
        ids = connect.insert(collection, entities)
        res = connect.get_entity_by_id(collection, ids[:500])
        assert len(res) == 0
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
-0.11.0

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
Server returned 500 ids and all valid_rows are false, client sdk should handle the valid_rows.

**Comment by BossZou** [comment]
checking ...

**Comment by BossZou** [comment]
I think it's not a bug, because client will fill results with None if corresponding id not exist in db.
