### ISSUE TITLE
The vector returned by function get_entity_by_id includes 0.0

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#3562]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
The test case is:
```
    def test_get_entity_multi_thread(self, connect, collection):
        ids = connect.insert(collection, entities)
        connect.flush([collection])
        get_id = ids[:1000]

        def insert_and_get():
            connect.insert(collection, entities)
            connect.flush([collection])
            res = connect.get_entity_by_id(collection, get_id)
            assert len(res) == len(get_id)
            for i in range(len(res)):
                assert_equal_vector(res[i].get(default_float_vec_field_name), entities[-1]["values"][i])

        with concurrent.futures.ThreadPoolExecutor(max_workers=3) as executor:
            future_results = {executor.submit(
                insert_and_get): i for i in range(10)}
            for future in concurrent.futures.as_completed(future_results):
                future.result()
```
The console output is as follows, and the vector returned by get_entity_by_id fun is v1, the vector insert is v2.
```
v1 = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...]
v2 = [0.12699986810204308, 0.05317814098161831, 0.015504925627234045, 0.03097918728026507, 0.003990995914138623, 0.13645583284233073, ...]

    def assert_equal_vector(v1, v2):
        if len(v1) != len(v2):
            assert False
        for i in range(len(v1)):
>           assert abs(v1[i] - v2[i]) < epsilon
E           AssertionError

```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
-0.11.0

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
Cannot reproduce this issue with latest 0.11.0. I suppose it has been fixed.
