### ISSUE TITLE
[Feature]: 作为一家中国公司开源的国产化数据库，为什么中文文档那么少，连官网也是英文的？

### ISSUE THREAD

**Issue by OpenSourceApp-coder** [milvus-io/milvus#35632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

作为一家中国公司开源的国产化数据库，为什么中文文档那么少，连官网也是英文的？

### Describe the solution you'd like.

作为一家中国公司开源的国产化数据库，为什么中文文档那么少，连官网也是英文的？

**Comment by ALLinLLM** [comment]
the robot's reply is quite humorous

**Comment by xiaofan-luan** [comment]
Hi @OpenSourceApp-coder 
Majority of the milvus contributor team is from china but we want to build a global team and global community.
Easiest way is to check chinese doc on zilliz.cloud.cn or use ChatGPT to translate. 

Thanks

**Comment by OpenSourceApp-coder** [comment]
从来没看过一家不重视自己国家文化的企业能走长远，中文成为了你们建设全球化团队的障碍了？

**Comment by OpenSourceApp-coder** [comment]
还是你们团队认为嘴里说出来的是英文就与众不同，就国际化了？
