### ISSUE TITLE
[0.10.1  GPU]When I indexed with HNSW, I was actually using a CPU, and the GPU was not being used

### ISSUE THREAD

**Issue by Haohao966** [milvus-io/milvus#3565]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

when I use index HNSW ,the CPU is used to 100%， and the Gpu is used 0%, BUT when  I  use index  IVF_FLAT, the GPU used is to 100% 
   
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [x] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)
GPU：NVIDIA GeForce GTX 1080 Ti   11760M  
CPU：24U  Xeon(R) CPU E5-2650 v4 @2.20GHz
MEMORY：64GB
disk：1T

- Milvus version (master or released version)

[0.10.1]
**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```
gpu:
     enable: true
    cache_size: 4G
    gpu_search_threshold: 1
   search_devices:
             - gpu0
   build_index_devices:
             - gpu0

**Screenshots**

**Additional context**
![image](https://user-images.githubusercontent.com/70635373/91968918-f3627b80-ed47-11ea-8f94-234ea9ad4b92.png)

**Comment by JinHai-CN** [comment]
HNSW doesn't use GPU to build and search vector. This is expected behavior.

**Comment by Haohao966** [comment]
> HNSW doesn't use GPU to build and search vector. This is expected behavior.

OK! Thank you !

**Comment by shengjun1985** [comment]
Which index types are supported by GPU can be got on this document.
https://milvus.io/docs/v0.10.2/milvus_distributions.md
