### ISSUE TITLE
Encountered two problems while building and compiling milvus from the source (version: milvus-0.10.2)

### ISSUE THREAD

**Issue by lighteningzhang** [milvus-io/milvus#3567]
**Error1:** 
milvus/milvus-0.10.2/core/src/index/thirdparty/SPTAG/AnnService/src/Core/BKT/BKTIndex.cpp:4:10: fatal error: inc/Core/BKT/Index.h: No such file or directory
 #include "inc/Core/BKT/Index.h"
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
src/index/knowhere/CMakeFiles/SPTAGLibStatic.dir/build.make:81: recipe for target 'src/index/knowhere/CMakeFiles/SPTAGLibStatic.dir/__/thirdparty/SPTAG/AnnService/src/Core/BKT/BKTIndex.cpp.o' failed
make[2]: *** [src/index/knowhere/CMakeFiles/SPTAGLibStatic.dir/__/thirdparty/SPTAG/AnnService/src/Core/BKT/BKTIndex.cpp.o] Error 1
CMakeFiles/Makefile2:697: recipe for target 'src/index/knowhere/CMakeFiles/SPTAGLibStatic.dir/all' failed
make[1]: *** [src/index/knowhere/CMakeFiles/SPTAGLibStatic.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....`]

**Error2**

milvus/milvus-0.10.2/core/cmake_build/sqlite_ep-prefix/src/sqlite_ep/missing: line 81: aclocal-1.15: command not found
WARNING: 'aclocal-1.15' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
Makefile:412: recipe for target 'aclocal.m4' failed
make[3]: *** [aclocal.m4] Error 127
CMakeFiles/sqlite_ep.dir/build.make:131: recipe for target 'sqlite_ep-prefix/src/sqlite_ep-stamp/sqlite_ep-build' failed
make[2]: *** [sqlite_ep-prefix/src/sqlite_ep-stamp/sqlite_ep-build] Error 2
CMakeFiles/Makefile2:452: recipe for target 'CMakeFiles/sqlite_ep.dir/all' failed
make[1]: *** [CMakeFiles/sqlite_ep.dir/all] Error 2

The above text is the two errors I faced.

1. For the first error, I didn't see the requirements of the library SPTAG in the installation tutorial, should I install it manually?
2. For the second error, I installed autoconf-2.69 and automake-1.16.2，the version of aclocal is 1.16，what should I do to handle this error?

Thank you very much!

**Comment by shengjun1985** [comment]
I am sorry that we have not reproduced your problem.
Can you tell us your system environment and the compilation steps?
Furthermore, did you run 'ubuntu_build_deps.sh' or 'centos7_build_deps.sh' in the folder 'core' ?
