### ISSUE TITLE
[Bug]:Wrong L2 distance returned

### ISSUE THREAD

**Issue by BBjie** [milvus-io/milvus#35681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Currently, I'm encountering an issue with getting accurate results back by L2 searching. This is my code 
```
v =  [12.398712,4.6340704,1.9631956,24.852571]  
 
collection.search(
    data=[v],
    anns_field="last_name",
    param={"metric_type": "L2", "params": {"level": 1}},
    output_fields=['truth_row_num',"last_name"],
    limit=2)

```  
and it returns the output 
`data: ['["id: 451951264905112005, distance: 0.001152675598859787, entity: {\'truth_row_num\': 355153, \'last_name\': [12.399810791015625, 4.628012657165527, 1.9622713327407837, 24.93383026123047]}", "id: 451951264905371361, distance: 0.001152675598859787, entity: {\'truth_row_num\': 614509, \'last_name\': [12.399810791015625, 4.628012657165527, 1.9622713327407837, 24.93383026123047]}"]'], cost: 6`

So I go back to the record with the same truth_row_num returned by output and manually check the L2 distance calculation by the following code 
```
import math
def l2_distance(vec1, vec2):
    squared_diffs = [(x - y)**2 for x, y in zip(vec1, vec2)]
    return sum(squared_diffs)
truth_3= [12.398712,4.6340704,1.9631956,24.852571]  
truth_355153= [12.399810791015625, 4.628012657165527, 1.9622713327407837, 24.93383026123047]
distance = l2_distance(truth_3, truth_355153)
print(f"The L2 distance between the vectors is: {distance:.14f}")
``` 
 and the output is 

`The L2 distance between the vectors is: 0.00664182539563
`

which is not aligned with the distance attribute returned by the search query. Is there anything Im doing wrong?

_Originally posted by @BBjie in https://github.com/milvus-io/milvus/discussions/35680_

**Comment by yanliang567** [comment]
I believe that is because Milvus only caculates the value before applying square root when Euclidean distance is chosen as the distance metric. https://milvus.io/docs/metric.md?tab=floating#Euclidean-distance-L2
/assign @BBjie 
/unassign

**Comment by BBjie** [comment]
> I believe that is because Milvus only caculates the value before applying square root when Euclidean distance is chosen as the distance metric. https://milvus.io/docs/metric.md?tab=floating#Euclidean-distance-L2
> 
> /assign @BBjie 
> 
> /unassign
> 
> 

yes so in my code I also only calculated the value before applying square root but the distance is still not matched

**Comment by yanliang567** [comment]
/assign @cydrain 
any ideas?
/unassign @BBjie

**Comment by osirisQdt2810** [comment]
I meet the same error when using milvus-sdk-cpp version 2.0, the calculated L2 distance is different from returned score from SearchResult. Is there any idea to solve this problem? And if the score is wrong, I wonder and question whether the returned feature result is indeed the best search?

**Comment by cydrain** [comment]
Hi @BBjie ,
Could you show me your expected results and the results returned by Milvus ?
And can you give me your scripts to reproduce this issue ?

**Comment by cydrain** [comment]
Hi @BBjie ,
The default data type for milvus vector data type is float, supporting a precision of approximately 7 decimal digits.
So when you do search with this vector,
```
truth_355153= [12.399810791015625, 4.628012657165527, 1.9622713327407837, 24.93383026123047]
```
it's similar to search with this vector:
```
truth_355153= [12.39985, 4.628012, 1.962271, 24.93383]
```
Milvus cannot guarantee the accuracy of the results after 7 decimal places
