### ISSUE TITLE
[FEATURE] Update the default cpu_cache_size value for developers

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#357]
**Is your feature request related to a problem? Please describe.**
The default value is 16Gb, why not change it to 8Gb, it's maybe the max memory for most personal computers

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yhmo** [comment]
Change default value of these fields：
insert_buffer_size： 1
cpu_cache_capacity： 6
