### ISSUE TITLE
[Enhancement]: about clinet.insert

### ISSUE THREAD

**Issue by eigen2017** [milvus-io/milvus#35709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

the concept need to be cleared

### Why is this needed?

some blog said, after client.insert, we must client.load_collection, in order to load new records to memory.
my question is : client.insert will not load new records to memory right?

### Anything else?

no

**Comment by xiaofan-luan** [comment]
loaded or not is a collection property.

If you do
create collection
load
index
insert
then each data will be autaomatically in memory.

While on the other side,
if you do
create collection
insert 
index build
load
then, insert will not automatically load

**Comment by xiaofan-luan** [comment]
yes, no data will be loaded until you do collection.load.
Collection.load need to be happened after index build

**Comment by eigen2017** [comment]
i see. thks~~~
load should be called immedietly after create collection
