### ISSUE TITLE
[Bug]: unknown type name 'AuthorizationRef' when compiling on M1 mac

### ISSUE THREAD

**Issue by lookou** [milvus-io/milvus#35710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master version 
- OS(Ubuntu or CentOS):  MacOS
- CPU/Memory: M1 MAX / 32G 
- GPU: 
- Others: 14.6 (23G80)
- llvm version:  16.0.6
- go version:  go1.21.4 darwin/arm64
- Conan version:  1.61.0
```

### Current Behavior

c-ares/1.33.0: CMake command: cmake --build "/Users/xxx/.conan/data/c-ares/1.33.0/_/_/build/aa424c3b8d58a9506811f973948500f1f0993dbe/build/Release" '--' '-j10'
`
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCPreferences.h:196:6: error: unknown type name 'AuthorizationRef'
                                        AuthorizationRef        __nullable      authorization
                                        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCPreferences.h:196:23: error: nullability specifier '_Nullable' cannot be applied to non-pointer type 'int'
                                        AuthorizationRef        __nullable      authorization
                                                                ^
<built-in>:337:20: note: expanded from here
#define __nullable _Nullable
`

when i compile it on M1 Max, it come out the error above.  But i can compile c-ares 1.33 independently.

**Comment by xiaofan-luan** [comment]
check this pr https://github.com/milvus-io/milvus/pull/35385


make sure you rollback grpc version to 1.50.1 and see how it works?

**Comment by yanliang567** [comment]
/assign @lookou 
please retry as comments above.

**Comment by lookou** [comment]
> /assign @lookou please retry as comments above.

Nothing change. The same error!

**Comment by xiaofan-luan** [comment]
this is related https://github.com/milvus-io/milvus/discussions/35614

**Comment by xiaofan-luan** [comment]
same as #35614

**Comment by tinswzy** [comment]
The error SCPreferences.h:196:6: error: unknown type name 'AuthorizationRef' occurs because, when installing c-ares, there is an environment issue with SCPreferences.h in this code:
```
#if !TARGET_OS_IPHONE
#include <Security/Security.h>
#else // !TARGET_OS_IPHONE
typedef const struct AuthorizationOpaqueRef * AuthorizationRef;
#endif // !TARGET_OS_IPHONE
```
The solution is to adjust the compilation settings to ensure it can locate and reference this header file. A workaround is to comment out the other lines temporarily.
And one workaround is to comment out other lines and retain typedef const struct AuthorizationOpaqueRef * AuthorizationRef; 
```
//#if !TARGET_OS_IPHONE
//#include <Security/Security.h>
//#else // !TARGET_OS_IPHONE
typedef const struct AuthorizationOpaqueRef * AuthorizationRef;
//#endif // !TARGET_OS_IPHONE
```

**Comment by xiaofan-luan** [comment]
good to know that! 
thanks for the feedback. 
could you create a fix for that.

**Comment by tinswzy** [comment]
> good to know that! thanks for the feedback. could you create a fix for that.

Of course, I’ll look into it and see what needs to be done to fix it.

**Comment by mhsmith** [comment]
```
SCPreferences.h:196:6: error: unknown type name 'AuthorizationRef'
                                        AuthorizationRef        __nullable      authorization
```

I got this error in the following situation:
* `xcode-select` was set to use my XCode installation, which was version 14.
* My XCode command line tools (installed separately) were version 16.

It was resolved by updating XCode to be version 16 as well.

**Comment by proost** [comment]
Hi @lookou ! do you solve the issue? same thing happens to me.

**Comment by CharlesJames13586** [comment]
1、If you llvm version < 16, please 
```shell
brew install llvm@17
export LDFLAGS="-L/usr/local/opt/llvm@17/lib"
export CPPFLAGS="-I/usr/local/opt/llvm@17/include"
```
2、Delete all conan libraries
```shell
conan remove "*"
```

3、make，and good luck to you。

**Comment by lmzzzzz1** [comment]
> 1、If you llvm version < 16, please
> 
> brew install llvm@17
> export LDFLAGS="-L/usr/local/opt/llvm@17/lib"
> export CPPFLAGS="-I/usr/local/opt/llvm@17/include"
> 2、Delete all conan libraries
> 
> conan remove "*"
> 3、make，and good luck to you。

After looking around, I found this to be the most useful. So, the macOS compile dependencies for the M1/2/3/4 chip should be:
go: >= 1.21 (this is fine)
cmake: >= 3.26.4 (but cmake 4.x won't work, as it's incompatible with conan 1.x)
llvm: >= 15 (tested only llvm 17 can work; llvm 20 is also incompatible with Conan 1.x)
python: > 3.8 and <= 3.11 (this is fine)
