### ISSUE TITLE
[Enhancement]: Deny database reading by modifying its properties.

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#35744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Set `database.force.deny.reading` in database properties to restrict read access.

**Comment by xiaofan-luan** [comment]
why not use quota limitation to do deny write?

**Comment by xiaofan-luan** [comment]
I thought all the write deny is done by setting quota to 0

**Comment by jaime0815** [comment]
> why not use quota limitation to do deny write?
1. Quota limits will be regularly updated with collected metrics data.
2. The goal is to provide an API that prioritizes denying database read or write access over setting quota configurations.
