### ISSUE TITLE
[Bug]: milvus query is hang

### ISSUE THREAD

**Issue by liuzh-sa** [milvus-io/milvus#35752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.4
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

query hang

### Milvus Log

[milvus-log.tar.gz](https://github.com/user-attachments/files/16776090/milvus-log.tar.gz)

**Comment by xiaofan-luan** [comment]
file/delta_log/451293960015077677/451293960015077678/451293960016289982/451792976385935885 

there seems to be some delta log missing..

you probably need to check the log on how many files are missing.
If there are only 1-2 files missing maybe simply use birdwatcher to remove the meta.

**Comment by liuzh-sa** [comment]
> file/delta_log/451293960015077677/451293960015077678/451293960016289982/451792976385935885
> 
> there seems to be some delta log missing..
> 
> you probably need to check the log on how many files are missing. If there are only 1-2 files missing maybe simply use birdwatcher to remove the meta.

How to delete？

**Comment by congqixia** [comment]
@liuzh-sa 
1. how to check how many files is missing
birdwatcher has a command to scan all missing file `verify-segment --collection [colleciton_id]`

2. use `remove binlog` to remove error binlog if found

**Comment by liuzh-sa** [comment]
> 1. verify-segment --collection

![image](https://github.com/user-attachments/assets/6f6f9272-b70c-4a27-a0c8-0521f23f69cd)
Do we need to delete all of these?

**Comment by xiaofan-luan** [comment]
> > 1. verify-segment --collection
> 
> ![image](https://private-user-images.githubusercontent.com/61768861/362220453-6f6f9272-b70c-4a27-a0c8-0521f23f69cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MDgwNTgsIm5iZiI6MTcyNDkwNzc1OCwicGF0aCI6Ii82MTc2ODg2MS8zNjIyMjA0NTMtNmY2ZjkyNzItYjcwYy00YTI3LWEwYzgtMDUyMWYyM2Y2OWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA1MDIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNTE4ZDMwZWVmMzMyMzA4YmI4ZWRmYjFmODUxNWI4ZmZlMDYyYTIxMDgxNGZhY2IyY2E1NDgwMWQ2MTdlMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vqhiMlqUFpLTkRd5fh9j7cTdtfYWuJaJ6bNsNh9WCaE) Do we need to delete all of these?

seems that you are missing a lot of data.

Could you explain what operation you did to this cluster?

**Comment by liuzh-sa** [comment]
> > > 1. verify-segment --collection
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/61768861/362220453-6f6f9272-b70c-4a27-a0c8-0521f23f69cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MDgwNTgsIm5iZiI6MTcyNDkwNzc1OCwicGF0aCI6Ii82MTc2ODg2MS8zNjIyMjA0NTMtNmY2ZjkyNzItYjcwYy00YTI3LWEwYzgtMDUyMWYyM2Y2OWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA1MDIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNTE4ZDMwZWVmMzMyMzA4YmI4ZWRmYjFmODUxNWI4ZmZlMDYyYTIxMDgxNGZhY2IyY2E1NDgwMWQ2MTdlMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vqhiMlqUFpLTkRd5fh9j7cTdtfYWuJaJ6bNsNh9WCaE) Do we need to delete all of these?
> 
> seems that you are missing a lot of data.
> 
> Could you explain what operation you did to this cluster?

We imported data into the cluster. Before the import started, the cluster became unreadable. Then we restarted the cluster and that was it.
