### ISSUE TITLE
[Bug]: When milvus standalone version reports an error "service not ready" after running for a period of time

### ISSUE THREAD

**Issue by lanlli** [milvus-io/milvus#35781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.16
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus v2.4.3
- OS(Ubuntu or CentOS): Ubuntu 
- CPU/Memory: 256G
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/user-attachments/assets/fc728e02-142e-4344-bd6b-0692f5d2c2f3)
When my milvus service encountered the above error while storing one million pieces of data, it was able to recover after restarting the milvus service, but it only lasted for less than an hour before the above error occurred again

**Comment by lanlli** [comment]
Milvus Log 
[standalone-144.zip](https://github.com/user-attachments/files/16782790/standalone-144.zip)

**Comment by yanliang567** [comment]
did not find any valuable errors in the logs, @congqixia could u please help to check it again?
`[2024/08/28 10:03:29.190 +00:00] [WARN] [datacoord/index_service.go:687] ["DataCoord 144 is not ready"] [traceID=34cc88140e1eec18bd0b0c95039647ee] [collectionID=451860409955178601] [error="service not ready[standalone=144]: Abnormal"]
`
/assign @congqixia 
/unassign

**Comment by congqixia** [comment]
@yanliang567  @lanlli 
since the log is not complete, the root cause why datacoord is not ready cannot be found. could you please provide the full starting log if possbile?

**Comment by lanlli** [comment]
[log-20240828.tar.gz](https://github.com/user-attachments/files/16799262/log-20240828.tar.gz)
This is yesterday's ERROR level log
