### ISSUE TITLE
[Bug]: Storage backend has reached its minimum free drive threshold when there are plenty of space

### ISSUE THREAD

**Issue by pycui** [milvus-io/milvus#35791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4.9  
- Deployment mode(standalone or cluster): standardalone
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.4.5
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: no limit
- GPU: 1
- Others: use a distributed file system as mounts for `milvus-data-disk` and `export` for minio
```

### Current Behavior

Set up a new standalone instance, inserting a few rows is OK, but after starting larger ingestion, milvus started to crashbackoffloop, and see a lot of these error:

Storage backend has reached its minimum free drive threshold. Please delete a few objects to proceed.

The milvus-data-disk dir on hostPath is only using 744MB, while the filesystem have XX TB still available.

Error log:
[error_log.txt](https://github.com/user-attachments/files/16790332/error_log.txt)

### Expected Behavior

milvus server not crashing

### Steps To Reproduce

```markdown
start up a standalone instance use https://zilliztech.github.io/milvus-helm/, with these two modifications:
- in Milvus, change the milvus-data-disk mount (for persistent.enaled=False) from EmptyDir to a distributed file system path available in all hosts.
- in Minio, change the export mount (for persistent.enaled=False) from EmptyDir to a distributed file system path available in all hosts (different from Milvus one)
- starting ingestion
```

**Comment by pycui** [comment]
> I think you need to change the config of minio.

Can you elaborate? what need to be changed?

**Comment by LoveEachDay** [comment]
@pycui Could you upload the minio pod log? From the attached milvus log we can see:
```
[2024/08/29 00:13:02.226 +00:00] [WARN] [storage/remote_chunk_manager.go:152] ["failed to put object"] [bucket=milvus-bucket] [path=file/insert_log/452169028714899333/452169028714899334/452169028715099349/100/452169658882326639] [error="IO failed[key=file/insert_log/452169028714899333/452169028714899334/452169028715099349/100/452169658882326639]: Storage backend has reached its minimum free drive threshold. Please delete a few objects to proceed."]
```
You can login the minio pod via `kubectl exec -it <minio-pod> -- bash` command. Then Run `df -h` to find out the `/export` disk size limit.

**Comment by pycui** [comment]
The full minio log
```
WARNING: MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated.
         Please use MINIO_ROOT_USER and MINIO_ROOT_PASSWORD
Formatting 1st pool, 1 set(s), 1 drives per set.
WARNING: Host local has more than 0 drives of set. A host failure will result in data becoming unavailable.
WARNING: Detected default credentials 'minioadmin:minioadmin', we recommend that you change these values with 'MINIO_ROOT_USER' and 'MINIO_ROOT_PASSWORD' environment variables
MinIO Object Storage Server
Copyright: 2015-2023 MinIO, Inc.
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Version: RELEASE.2023-03-20T20-16-18Z (go1.19.7 linux/amd64)

Status:         1 Online, 0 Offline. 
API: http://10.96.106.119:9000  http://127.0.0.1:9000     
Console: http://10.96.106.119:43557 http://127.0.0.1:43557   

Documentation: https://min.io/docs/minio/linux/index.html
Warning: The standard parity is set to 0. This can lead to data loss.

 You are running an older version of MinIO released 1 year ago 
 Update: Run `mc admin update` 
```
within the minio pod, `df -h` shows /export have 75T available space.

**Comment by LoveEachDay** [comment]
@pycui Could you run the following command to show your minio cluster info:
```
mc admin info <alias>
```

Read more for `mc` command from: https://min.io/docs/minio/linux/reference/minio-mc.html

**Comment by pycui** [comment]
Seeing this:
```
mc: <ERROR>  Unable to display service info, server is too old
```

**Comment by xiaofan-luan** [comment]
I'm assuming you are using docker compose.

minio:
  container_name: milvus-minio
  image: minio/minio:RELEASE.2023-03-20T20-16-18Z
  environment:
    MINIO_ACCESS_KEY: minioadmin
    MINIO_SECRET_KEY: minioadmin
  volumes:
    - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
  command: minio server /minio_data


dis you set the right volumes for your minio?  you need to check the size of your volume

**Comment by LoveEachDay** [comment]
@pycui Have you enable the metrics scrape for minio pod? If so, you can query the metric like this to find available disk size for minio cluster:
```
minio_node_disk_free_bytes{disk="/export"}
```

To enable minio metrics scrape using milvus -helm, you can add following values:
```
minio:
  metrics:
    podMonitor:
       enabled: true
```

**Comment by pycui** [comment]
I there there probably were storage stress when this happened, even though it showed quite some space. After we clean up more space, the error was gone. Closing this for now.
