### ISSUE TITLE
Milvus memory changes

### ISSUE THREAD

**Issue by Doimet** [milvus-io/milvus#3580]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

Today, Milvus memory suddenly dropped from 43g to 20g, and now it has risen to 37G.

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

Memory: 64G

- Milvus version (master or released version)

0.10.2

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by JinHai-CN** [comment]
Please provide the log and milvus configuration file for reference.

**Comment by Doimet** [comment]
> Please provide the log and milvus configuration file for reference.

This is a compressed file. Please remove the .txt at the end of the file name
[server_config.part01.rar.txt](https://github.com/milvus-io/milvus/files/5173540/server_config.part01.rar.txt)
[server_config.part02.rar.txt](https://github.com/milvus-io/milvus/files/5173541/server_config.part02.rar.txt)

**Comment by shengjun1985** [comment]
I have checked the log file and the cache items were not released any.
I guess this issue may be caused by task GC whose strategy is adjusted in PR3609.
Please wait for v0.10.3.
And we will continue to observe this phenomenon. If you have new clues, please contact us in time.
Thank you very much.

**Comment by Doimet** [comment]
ok
