### ISSUE TITLE
[Bug]: When mmap is enabled to load 100 million vectors, an error will be reported when the load reaches 50%

### ISSUE THREAD

**Issue by lefeiwang** [milvus-io/milvus#35848]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.4.6
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==v2.4.5
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 8/64GB, 64/128GB
- GPU: 
- Others:
```

### Current Behavior

1. Two querynode nodes
2. Through the attu web page, the loading process will stop when it reaches 50%
3.  code
```
from pymilvus import Collection

collection = Collection(...)

collection.set_properties(
    properties={
        "mmap.enabled": True
    }
)

collection .load()
...
```
error log:
![1](https://github.com/user-attachments/assets/946dcc9c-efa1-46cc-bebd-689f00b20c39)

### Milvus Log

querynode log:

node1: CPU/Memory: 8/64GB 
![2](https://github.com/user-attachments/assets/032aca03-d45c-43a6-a7e8-a4ecf9b6bb1c)

node2: CPU/Memory: 64/128GB 
![3](https://github.com/user-attachments/assets/2585b58e-0cfe-4898-9ad9-5093da3b33c5)

**Comment by xiaofan-luan** [comment]
@lefeiwang 
can you collect logs by https://github.com/milvus-io/milvus/tree/master/deployments/export-log.
From the log you offered, there is something happened that could potentially cause the load rollback,
maybe lack of memory or disk

**Comment by lefeiwang** [comment]
1. After dropping a collection, the 100 million data collection was successfully loaded. But the query times was wrong, and the reload began

search err log:
![4](https://github.com/user-attachments/assets/1d7c993b-3452-41bd-ba85-4d220815b094)

node1: CPU/Memory: 8/64GB
[milvus_1.log](https://github.com/user-attachments/files/16814760/milvus_1.log)

node2: CPU/Memory: 64/128GB
[milvus_2.log](https://github.com/user-attachments/files/16814762/milvus_2.log)


2. In addition, I would like to ask how a cluster can achieve faster write speeds than a standalone.  Need to deploy multiple minio nodes?

**Comment by yanliang567** [comment]
/assign @sunby 
@lefeiwang for your 2nd question, i suggest you add more resources for pulsar(MQ) and datanode.

/unassign

**Comment by yanliang567** [comment]
@sunby any updates for this issue
