### ISSUE TITLE
[Bug]: Compilation error with go 1.23.0

### ISSUE THREAD

**Issue by jiangyinzuo** [milvus-io/milvus#35878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master (311f860676133e94c5fc8367bc447a46b09b948c)
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu 22.04
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I run `make` to compile compile milvus, I got an error:
```
Go Version: go version go1.23.0 linux/amd64
Building Milvus ...
link: github.com/bytedance/sonic/ast: invalid reference to encoding/json.safeSet
```

### Expected Behavior

According to https://github.com/bytedance/sonic/issues/660 and https://github.com/bytedance/sonic/releases/tag/v1.12.2, we should bump bytedance/sonic to v1.12.2

### Steps To Reproduce

```markdown
make
```

**Comment by yanliang567** [comment]
/assign @congqixia 
please help to take a look
/unassign
