### ISSUE TITLE
[Enhancement]: When an unrecoverable error occurs, return instead of swap

### ISSUE THREAD

**Issue by fengjun2016** [milvus-io/milvus#35913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

When an unrecoverable error occurs, return error directly instead of swap

![截屏2024-09-02 23 24 54](https://github.com/user-attachments/assets/854c4cc8-ea05-49c7-8970-66e1c99c2e79)

### Why is this needed?

![截屏2024-09-02 22 53 15](https://github.com/user-attachments/assets/aa6d8f6d-98dd-4ac7-9011-853e35fcf9af)
![截屏2024-09-02 22 53 30](https://github.com/user-attachments/assets/f20af42f-689f-4126-8ec9-18b04b4cca0a)
![截屏2024-09-02 22 54 13](https://github.com/user-attachments/assets/01657661-1394-44ef-9637-0171d76ab482)

**Comment by chyezh** [comment]
`producerWithResumingError` type is a utility type to handle the `Condvar` logic for `ResumableProducer`.
So after creating the producer, we must record the error and producer in `producerWithResumingError` to notify the method `Produce`.

So we cannot move the `SwapProducer` to the position after error handling.

**Comment by chyezh** [comment]
closed, as previous comment.
