### ISSUE TITLE
Memory should be released after collection dropped

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#3597]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                
16966 root      20   0 19.956g 0.013t  16820 S   0.0 43.7  29:37.37 milvus_server                                                                                                          

```
actually, collection has been dropped:
```
[root@4f965558a67f db]# du -sh *
4.0K	collections
4.8M	meta.sqlite
32K	meta.sqlite-shm
4.0M	meta.sqlite-wal

```
**Steps/Code to reproduce behavior**
1. create collection
2. insert entities concurrently (vector length = 1 for each request)
3. drop collection

**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`
default config yaml

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by XuPeng-SH** [comment]
The root cause is that right now our background MergeOp will load segment data into LRU cache and MergeOp is always triggered by InsertOp. From the user's view, it's very weird that InsertReq will take up more memory usage than expected. However, it has the advantage of reducing cold data loading time during query. Here we have to make a good trade-off.

**Comment by BossZou** [comment]
See https://github.com/milvus-io/milvus/pull/3645

**Comment by del-zhenwu** [comment]
After concurrently inserting.

```

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                
26098 root      20   0 11.165g 5.540g  20484 S   8.0 17.8  30:06.18 milvus_server  
```

**Comment by BossZou** [comment]
In this case we need know the configuration about cache. If the usage of memory can keep stable, I think is not a bug.

**Comment by del-zhenwu** [comment]
default yaml

**Comment by godchen0212** [comment]
@del-zhenwu This memory usage can be controlled by config cache.max_concurrent_insert_request_size in PR #3830
