### ISSUE TITLE
[Bug]: mistake in the docs

### ISSUE THREAD

**Issue by mina58** [milvus-io/milvus#35983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is a small mistake in the docs:
![image](https://github.com/user-attachments/assets/54925ab3-a05f-4390-9b3f-73f001a0da88)
here 
data = [
    {"id": i, "vector": vectors[i], "text": docs[i], "subject": "history"}
]
should be
data = [
    {"id": i, "vector": vectors[i], "text": docs[i], "subject": "history"} for i in range(len(docs))
]

can you point to me this page in the docs to fix it

**Comment by zhuwenxing** [comment]
@mina58 

For the document issue, you can correct it by clicking `Edit the page`.
for example
![image](https://github.com/user-attachments/assets/8f5ba326-7239-43fd-b31e-822dcd5ab36d)

**Comment by yanliang567** [comment]
/assign @mina58 
please feel free to submit a pr to fix it. thx
/unassign

**Comment by AnthonyTsu1984** [comment]
Thank you for pointing out this bug and we have fixed it as expected.
