### ISSUE TITLE
The response of dsl search with empty query vector should not ok

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#3599]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
1.The test case is:
```
public void  testSearchVectorNotExisted(MilvusClient client, String collectionName) {
        InsertParam insertParam = new InsertParam.Builder(collectionName).withFields(Constants.defaultEntities).build();
        InsertResponse res = client.insert(insertParam);
        assert(res.getResponse().ok());
        client.flush(collectionName);
        List<List<Float>> query = new ArrayList<>();
        System.out.println(query.size());
        String dsl = String.format(
                "{\"bool\": {"
                        + "\"must\": [{"
                        + "    \"range\": {"
                        + "        \"int64\": {\"GT\": -10, \"LT\": 1000}"
                        + "    }},{"
                        + "    \"vector\": {"
                        + "        \"float_vector\": {"
                        + "            \"topk\": %d, \"metric_type\": \"L2\", \"type\": \"float\", \"query\": %s, \"params\": {\"nprobe\": 20}"
                        + "    }}}]}}",
                top_k, query);
        SearchParam searchParam = new SearchParam.Builder(collectionName).withDSL(dsl).build();
        SearchResponse resSearch = client.search(searchParam);
        Assert.assertFalse(resSearch.getResponse().ok());
    }
```
2. The console output is:
```
java.lang.AssertionError: expected [false] but found [true]
Expected :false
Actual   :true
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**
response not ok

**Method of installation**
- [ ] Docker/cpu
- [x] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
-0.11.0

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by shengjun1985** [comment]
@shanghaikid 
I don't think it should return error when nq=0. 
Please confirm.

**Comment by shanghaikid** [comment]
you are correct, if nq = 0,  we should not return error, but we'd better print out a search warning.
