### ISSUE TITLE
[Bug]: The combination of Iterator query  and expr has "or" expression results in an infinite loop 

### ISSUE THREAD

**Issue by Ice-YcY** [milvus-io/milvus#35995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4.9
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):milvus-sdk-java:2.4.0
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The combination of Iterator query  and expr has "or" expression results in an infinite loop 
![image](https://github.com/user-attachments/assets/a7c5c86d-ba8b-454c-ac82-b8c523a92ac0)
![image](https://github.com/user-attachments/assets/23131a94-4030-425a-951c-1f56057dd1b5)
![image](https://github.com/user-attachments/assets/63c10425-6ab3-481c-b76f-5af99a3b3e74)

### Expected Behavior

get results successful

### Steps To Reproduce

```markdown
execute iterator query with expression(contains "or")
```

**Comment by xiaofan-luan** [comment]
I think this should be more like a java sdk bug.

**Comment by Ice-YcY** [comment]
this error is caused by java sdk issues.
I have created a PR for this : https://github.com/milvus-io/milvus-sdk-java/pull/1058.

**Comment by yanliang567** [comment]
I'd close this issue as comments above.
