### ISSUE TITLE
[Bug]: the original idea here is to just return nil if there is no key.

### ISSUE THREAD

**Issue by fengjun2016** [milvus-io/milvus#36023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![截屏2024-09-05 23 01 25](https://github.com/user-attachments/assets/55d8f83f-28d1-495c-9922-3c0e33ff61ae)

**Comment by xiaofan-luan** [comment]
@xiaocai2333 
please check on it

**Comment by xiaocai2333** [comment]
It should be return the error here.

**Comment by xiaocai2333** [comment]
fiexed, close it
/close
