### ISSUE TITLE
[Bug]: Encountered backlog problems when using preCreatedTopic

### ISSUE THREAD

**Issue by xige-16** [milvus-io/milvus#36021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When using preCreatedTopic, each pre-created topic has a pre-created-topic-check-xxx consumer group, but the corresponding consumer never consumes messages. It seems that this subscription is only used to check whether the topic exists, and the subscription is not unsubscribed after the check. This causes the topic to have a backlog.

https://github.com/milvus-io/milvus/blob/15ed76d1d63c7c10e173749cacfd30601916ea49/internal/rootcoord/dml_channels.go#L187-L199

**Comment by xiaofan-luan** [comment]
this is obviously a bug

**Comment by yanliang567** [comment]
@xige-16 would you please to fix this issue ?

**Comment by xige-16** [comment]
> @xige-16 would you please to fix this issue ?

Okey
