### ISSUE TITLE
[Bug]: Large segment list cause DataNode watch channel failed.

### ISSUE THREAD

**Issue by aoiasd** [milvus-io/milvus#36025]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:Master and 2.4.10
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When watch channel with large num of segment, because GetSegmentInfo will timeout.
Even through we split large segment list to small requests, but now we have to get all result within 5s.

### Expected Behavior

Each request needs its own timeout.

**Comment by xiaofan-luan** [comment]
is this still a bug?
