### ISSUE TITLE
[Bug]: In milvus-standalone docker container. Automaticly exits with code 134 after sometime. If no collection is loaded, no problem is caused

### ISSUE THREAD

**Issue by NamNX1409** [milvus-io/milvus#36041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.10
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.4.6
- OS(Ubuntu or CentOS): Ubuntu 20.04
- CPU/Memory:
- GPU: 
- Others:
```

### Current Behavior

container milvus-standalone automatically exits after I insert data to a collection.

### Milvus Log

[milvus.log](https://github.com/user-attachments/files/16902965/milvus.log)

**Comment by yanliang567** [comment]
@NamNX1409 how did you config/deploy your minio, it seems not working
_2024-09-06 11:33:20 [2024/09/06 04:33:20.064 +00:00] [WARN] [retry/retry.go:46] ["retry func failed"] [retried=0] [error="failed to write files/insert_log/452337435696709883/452337435696709884/452337435696909953/102/452354935055712590: IO failed[key=files/insert_log/452337435696709883/452337435696709884/452337435696909953/102/452354935055712590]: Resource requested is unreadable, please reduce your request rate"]_

/assign @NamNX1409 
/unassign

**Comment by NamNX1409** [comment]
Here is my docker-compose.yml file:

version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: [ "CMD", "etcdctl", "endpoint", "health" ]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.4.10
    command: [ "milvus", "run", "standalone" ]
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9091/healthz" ]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvus

I just followed the instructions and didn't change anything.

**Comment by jaime0815** [comment]
Hi, @NamNX1409. The minio service may be unhealthy. Please check the minio log, this issue is similar to  https://github.com/minio/minio/discussions/16341.

**Comment by NamNX1409** [comment]
Hi, @jaime0815. Thanks for the advice. When I check with `docker compose ps -a`, the status still shows as "healthy" (as seen in the picture below). However, when I check the MinIO log, it says: `Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to initialize config system: migrateConfigToMinioSys: Storage resources are insufficient for the write operation .minio.sys/config/config.json). I also can't find the config.json file` (to be exact, there's nothing in the config folder).

![image](https://github.com/user-attachments/assets/4bef152f-2e36-4b79-8871-f65db1cb2931)

Here is my minio log: 
[minio.log](https://github.com/user-attachments/files/16904393/minio.log)

**Comment by jaime0815** [comment]
Is there enough disk space for MinIO?

**Comment by yanliang567** [comment]
/assign @LoveEachDay 
any ideas?

**Comment by xiaofan-luan** [comment]
Storage resources are insufficient for the write operation

**Comment by NamNX1409** [comment]
There was something wrong with my MinIO settings, but I’ve solved it. Thanks, everyone!
