### ISSUE TITLE
GPU memory usage

### ISSUE THREAD

**Issue by vdogmcgee** [milvus-io/milvus#3605]
I would like to ask, how is the memory usage of milvus calculated, sometimes it uses 200M, sometimes increased to 900M, my gpu related parameters are: cache_size:1GB, gpu_search_threshold: 1000, I hope someone can answer my confusion, thank you

**Comment by shengjun1985** [comment]
There may be two reasons for this phenomenon.
(1) When the number of the query (nq) is less than 'gpu_search_threshold', Milvus will execute the query on CPU.
If the nq of multiple queries is different, the GPU usage will be different.
(2) Milvus has not implement to cache the GPU index now.
After each task is executed, the GPU cache will be released.
Are the above reasons consistent with your cases?

**Comment by shengjun1985** [comment]
If you have more questions, please continue to contact our community.
Thank you very much.
