### ISSUE TITLE
[Bug]: binlogReader is not released in time

### ISSUE THREAD

**Issue by fengjun2016** [milvus-io/milvus#36077]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![截屏2024-09-06 20 38 31](https://github.com/user-attachments/assets/c1b2f60a-13cc-483c-bae3-4b0f1aad1829)

**Comment by yanliang567** [comment]
/assign @congqixia 
please help to check whether it should be merge into 2.4 as well?

/unassign

**Comment by xiaofan-luan** [comment]
this is actaully a good catch.
