### ISSUE TITLE
[Bug]: BinlogDeserializeReader leak

### ISSUE THREAD

**Issue by fengjun2016** [milvus-io/milvus#36086]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![截屏2024-09-07 21 04 01](https://github.com/user-attachments/assets/32174f56-576b-4de4-8369-f8072fb52b1c)

![截屏2024-09-07 21 13 15](https://github.com/user-attachments/assets/8bf59e73-d31c-4856-8f91-5da3070bf06a)

![截屏2024-09-07 21 13 53](https://github.com/user-attachments/assets/8701a701-943f-4cea-83ed-89f045135ee0)

**Comment by yanliang567** [comment]
/assign @congqixia 
please help to review
/unassign
