### ISSUE TITLE
Better / tr 

### ISSUE THREAD

**Issue by Hexx333** [milvus-io/milvus#36150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When is too less informations in file thant cannot be pushed and work
 
![Sei e lei](https://github.com/user-attachments/assets/c84c4e08-4c6b-409d-bdd2-9220936ebb1c)

### Expected Behavior

<while{31-+111>
With this config name Better / tr destroy xbug 
Run ; version 7.ak 1/291.?.2.exe 
Fill Code version ctrl push 
See error with 'syntax' js

### Steps To Reproduce

```markdown
In this environment with my Hexx333 will work. Please eeply and reply ;) 
Run;
```

**Comment by xiaofan-luan** [comment]
how does that related to milvus? Sorry I don't get it

**Comment by Hexx333** [comment]
You v been saying , that is a problem , bug , and this is receipe for fix. This is my opinion , technically

**Comment by yanliang567** [comment]
I  do not get what does this issue about? could you please share more details about the reproduce steps and expectations
/assign @Hexx333 
/unassign

**Comment by Hexx333** [comment]
Ok

sob., 9 lis 2024, 17:02 użytkownik stale[bot] ***@***.***>
napisał:

**Comment by yanliang567** [comment]
I'd close this issue as we don't get the idea of it. please file a new one with english if it still blocked anyone.
