### ISSUE TITLE
[Bug]: [ERROR] [grpclog/grpclog.go:55] [\"[transport]transport: loopyWriter.run returning.  log":"SIGPIPE Swallowed

### ISSUE THREAD

**Issue by TonyAnn** [milvus-io/milvus#36167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.16
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The milvus querynode CPU usage is over 90%, the search latency is high, and the failure rate is also high. Please help me find out whether it is caused by the CPU bottleneck or other abnormalities.

### Milvus Log

[milvus-log.tar (2).gz](https://github.com/user-attachments/files/16956441/milvus-log.tar.2.gz)
[querynode-6cbccb98bc-j5shf.log](https://github.com/user-attachments/files/16956443/querynode-6cbccb98bc-j5shf.log)

**Comment by yanliang567** [comment]
over 90% cpu useage will definitely cause heavy search latency.  about to the error, as the logs are set info level, there is no much info to know what was happening at that moment. 
Again, we recommend you upgrade to latest milvus release for a better performance and stability experience.

/assign @TonyAnn 
/unassign

**Comment by TonyAnn** [comment]
[milvus-log.tar (2).gz](https://github.com/user-attachments/files/16959844/milvus-log.tar.2.gz)

Hi liangyan, the log file after changing log to info is as attached
@yanliang567

**Comment by TonyAnn** [comment]
[milvus-debug-log.tar.gz](https://github.com/user-attachments/files/16960358/milvus-debug-log.tar.gz)

Update the debug log, see the attachment for details @yanliang567

**Comment by yanliang567** [comment]
it indicates that you are have 162 querynodes in the cluster, I think you'd better upgrade to latest milvus which performs much better with such a large cluster.

**Comment by yanliang567** [comment]
close as we discussed offline
