### ISSUE TITLE
[Bug]: Standalone Milvus crush while trying to create IVF_FLAT index on sift1M dataset (dim=128).

### ISSUE THREAD

**Issue by liorf95** [milvus-io/milvus#36162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone):
- MQ type(rocksmq):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I reproduce the crush each time with sift1M (with siftsmall 10K vectors it runs OK).
Happens with nlist 128 and 4096 (and any metric type L2 or IP).
While trying to create IVF_FLAT index, the Milvus was crushed with a Segmentation fault and from that point, the dataNode is not accessible anymore even after Milvus is started.
There are no memory or disk space issues on the platform.

Is there any memory configuration for the dataNode (or other nodes) that might be needed on the milvus.yaml for the 1M IVF_FLAT index?

### Expected Behavior

Some validation errors if the index creation params are not suitable for the dataset size.

### Milvus Log

Sep 10 15:23:37 liorftry milvus[123225]: I20240910 15:23:37.688453 123316 thread_pool.h:60] [KNOWHERE][operator()][knowhere_build1] Successfully set priority of knowhere thread.
Sep 10 15:23:37 liorftry milvus[123225]: SIGNAL CATCH BY NON-GO SIGNAL HANDLER
Sep 10 15:23:37 liorftry milvus[123225]: SIGNO: 8; SIGNAME: Floating point exception; SI_CODE: 1; SI_ADDR: 0x7f9907dae9b4
Sep 10 15:23:37 liorftry milvus[123225]: BACKTRACE:
Sep 10 15:23:37 liorftry milvus[123225]: (null)
Sep 10 15:23:37 liorftry milvus[123225]:         (null):0 pc=0x7f9907dae9b4
Sep 10 15:23:37 liorftry milvus[123225]: (null)
Sep 10 15:23:37 liorftry milvus[123225]:         (null):0 pc=0x7f9907db5b3f
Sep 10 15:23:37 liorftry milvus[123225]: (null)
Sep 10 15:23:37 liorftry milvus[123225]:         (null):0 pc=0x7f99035bac92
Sep 10 15:23:37 liorftry milvus[123225]: (null)
Sep 10 15:23:37 liorftry milvus[123225]:         (null):0 pc=0x7f990354f9b2
Sep 10 15:23:37 liorftry milvus[123225]: (null)

**Comment by xiaofan-luan** [comment]
Hi @liorf95

Are you simply running test on SIFT dataset? we run a lot of test on SIFT so this is unlikely to help


1. could you offer us your scripts on test? 
2. can you do a backup of your data(either physical or logical so we can check if there are some special data)

**Comment by yanliang567** [comment]
/assign @liorf95 
a few more quick questions:
3. which version of milvus are you running?
4. how did you deploy milvus, did you update any configurations? 
5. what is your OS

/unassign

**Comment by liorf95** [comment]
> Hi @liorf95
> 
> Are you simply running test on SIFT dataset? we run a lot of test on SIFT so this is unlikely to help
> 
> 1. could you offer us your scripts on test?
> 2. can you do a backup of your data(either physical or logical so we can check if there are some special data)

1. I use Milvus bootcamp over pymilvus to create the collection and create_index.
2. My data is sift_base.fvecs from ftp://ftp.irisa.fr/local/texmex/corpus/sift.tar.gz

**Comment by liorf95** [comment]
> /assign @liorf95 a few more quick questions: 3. which version of milvus are you running? 4. how did you deploy milvus, did you update any configurations? 5. what is your OS
> 
> /unassign

3. I use Milvus code cloned from 09 Sep 24.
4. Deployed with Debian package without any updated configurations.
5. Ubuntu 22.04.4 LTS

**Comment by liliu-z** [comment]
Hi @liorf95 , Can I have some info to reproduce this:
1. What is the commit id of your Milvus
2. What is the step-by-step instruction, I guess it is `create collection` -> `insert data` -> `create index`? It will be great if you can provide the script you used.

Best

**Comment by liorf95** [comment]
The issue was crush in knowhere on the 1st attempt to access some pre-required cblass function.
This issue was handled with knowhere commit as follows:
https://github.com/zilliztech/knowhere/commit/2d04d3b818a3b157e84ec7b54476ed3aee9f0e64

We have updated our knowhere repo merged with knowhere GitHub from 19 Sep and the issue was solved.

**Comment by liliu-z** [comment]
> The issue was crush in knowhere on the 1st attempt to access some pre-required cblass function. This issue was handled with knowhere commit as follows: [zilliztech/knowhere@2d04d3b](https://github.com/zilliztech/knowhere/commit/2d04d3b818a3b157e84ec7b54476ed3aee9f0e64)
> 
> We have updated our knowhere repo merged with knowhere GitHub from 19 Sep and the issue was solved.

Great to know that. Thx for this following up! Plz feel free to let us know if anything else we can help.
