### ISSUE TITLE
[Bug]: Sparse Float Vector raw data mmap is broken

### ISSUE THREAD

**Issue by zhengbuqian** [milvus-io/milvus#36182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.6 to 2.4.10 and master
```

### Current Behavior

* Sparse Float Vector Raw data mmap was added in https://github.com/milvus-io/milvus/pull/33652 and available on v2.4.5. 
* Later #32633 modified `Column` to use `ChunkManager` based mmap instead of `File` based mmap. In this effort the implementation for Sparse Float Vector Raw data mmap was broken. 
* In the broken version, trying to read data will continue to work, but the data returned is wrong.
* #35437 is a temp fix on 2.4

**Comment by xiaofan-luan** [comment]
what is the problem of the current mmap solution?

**Comment by zhengbuqian** [comment]
> what is the problem of the current mmap solution?

the original Column.h was already complicated and the tmp fix #35437 works but makes the code even more unmaintainable. #36183 does a little bit of refactoring and updates the fix to match raw design of Column.h

**Comment by yanliang567** [comment]
@zhengbuqian any new prs for this issue?
