### ISSUE TITLE
when i use milvus sdk, it crashed

### ISSUE THREAD

**Issue by cuijianxxx0** [milvus-io/milvus#3619]
![image](https://user-images.githubusercontent.com/60396890/92301283-09b14700-ef95-11ea-9597-7dbf801f0d80.png)
[](url)
maybe the proto in my project is conflict with milvus

**Comment by shengjun1985** [comment]
Excuse me, would you like to provide more info such as Milvus version, SDK version, the query command and so on?

**Comment by cuijianxxx0** [comment]
sdk version:0.10.2 & 0.10.3
i wrote an my.so based on the sdk example, and my proto version is higher than milvus
it crashed when my program call the dlopen function in my.so
so maybe i have 2 ways to solve this problem 
1.use milvus static library
2.update the proto version in milvus
can you help me how to do in milvus in the above 2 ways

**Comment by BossZou** [comment]
This is an error in C++ sdk.

**Comment by fishpenguin** [comment]
You need to remove your own protobuffer.

**Comment by cuijianxxx0** [comment]
i only can update the grpc version of milvus, could you tell me how to do it ?

**Comment by cuijianxxx0** [comment]
my proto version is 3.11.x , and milvus is 3.9.x , may i amend the build.sh or CMakeLists to update version?

**Comment by fishpenguin** [comment]
In 0.10.x version, we cannot update the grpc version of milvus, because we used make to build the project and did not pass any cmake parameters.
However, we will provide a way to update the grpc version of milvus in later version.

**Comment by cuijianxxx0** [comment]
i found how to update grpc version, and I've solved it
