### ISSUE TITLE
[Bug]: Unable to insert data into sparse vector field using BM25 embedding function.

### ISSUE THREAD

**Issue by dygwon** [milvus-io/milvus#36225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.5
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): n/a
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.4.6
- OS(Ubuntu or CentOS): Ubuntu (WSL)
- CPU/Memory: 13th Gen Intel i7
- GPU: n/a
- Others: I am using a standalone Milvus instance deployed locally on docker (https://milvus.io/docs/install_standalone-docker.md).
```

### Current Behavior

When I try to insert BM25 embeddings into a sparse vector field, I get an invalid data type error. I've tried inserting the data in different forms (e.g., as a list of dictionaries) and they are still not accepted. According to the documentation, a csr_array should be accepted (below is example code that I'm running along with the given error message).

### Code
![image](https://github.com/user-attachments/assets/676db4cb-5bd9-4a77-adf9-05d795a6eff7)
![image](https://github.com/user-attachments/assets/abd38c0b-e9fe-4249-8c44-9a62d4be236a)
![image](https://github.com/user-attachments/assets/6641dc79-916d-44cf-ae77-878781975d6b)

### Error
![image](https://github.com/user-attachments/assets/0ce15c50-31f2-4dc1-9c6b-eaa5f95effb5)

### Expected Behavior

The five documents above should be added as entries into the `test_sparse_vector` collection and should be searchable against new queries.

### Steps To Reproduce

```markdown
Run the code above in a single module.
```

### Milvus Log

Not running on k8s.

### Anything else?

Code above is adapted from documentation for Milvus 2.4.x for [BM25 ](https://milvus.io/docs/embed-with-bm25.md) and [Sparse Vectors](https://milvus.io/docs/sparse_vector.md).

I know sparse vectors are in beta until version 3.0.0, but I have an application that was successfully using lookups with BM25 until recently.

**Comment by yanliang567** [comment]
I guess the data format in doc BM25 is not fit for Milvus sparse insertion. @jaelgu could you please help to take a look?
/assign @jaelgu 
/unassign

**Comment by wxywb** [comment]
please change your insert line to
```python
client.insert(collection_name="test_sparse_vector", data=[{"sparse_vector": docs_embeddings}])
```

**Comment by dygwon** [comment]
Still getting errors. I've tried what @wxywb suggested above (all document embeddings as the value in a single dictionary) and I've also tried insert with a separate dictionary for each document embedding like so:

![image](https://github.com/user-attachments/assets/f0110efc-e708-4153-af14-f1c9b96d63a5)
![image](https://github.com/user-attachments/assets/9e0765d7-c010-42f8-8af7-b0642deea134)


Both give me the same error:

![image](https://github.com/user-attachments/assets/deade15c-3f63-405d-a704-ea346b841938)

![image](https://github.com/user-attachments/assets/bca94769-718f-4c51-bb7a-76d64a10a943)

**Comment by wxywb** [comment]
```python
from pymilvus.model.sparse.bm25.tokenizers import build_default_analyzer
from pymilvus.model.sparse import BM25EmbeddingFunction


analyzer = build_default_analyzer(language="en")
corpus = [
  "Artificial intelligence was founded as an academic discipline iin 1956.",
  "Alan Turing was the first person to conduct substantial research in AI.",
  "Born in Maida Vale, London, Turing was raised in southernn England."]
bm25_ef = BM25EmbeddingFunction(analyzer)
bm25_ef.fit(corpus)
docs = [
  "The field of artificial intelligence was established as aan academic subject in 1956.",
  "Alan Turing was the pioneer in conducting significant research in arttificial intelligence.",
  "Originating in Maida Vale, London, Turing grew up in the southern regions of England.",
  "In 1956, artificial intelligence emerged as a scholarly field." ,
  "Turing, originally from Maida Vale, London, was brought uup in the south of England."]
docs_embeddings = bm25_ef.encode_documents(docs)
print(docs_embeddings.shape)

from pymilvus import MilvusClient, DataType
client = MilvusClient(uri="test.db")
client.drop_collection(collection_name='test_sparse_vector')
schema = client.create_schema(auto_id=True, enable_dynamic_fields=True)
schema.add_field(field_name="pk", datatype=DataType.VARCHAR, is_primary=True, max_length=100)
schema.add_field(field_name="sparse_vector", datatype=DataType.SPARSE_FLOAT_VECTOR) # set `datatype` to SPARSE_FLOAT_VECTOR
client.create_collection(collection_name="test_sparse_vector", schema=schema)

client.insert(collection_name="test_sparse_vector", data=[{"sparse_vector": docs_embeddings[[i]]} for i in range(docs_embeddings.shape[0])])
index_params = client.prepare_index_params()
index_params.add_index(
    field_name="sparse_vector",
    index_name="sparse_inverted_index",
    index_type="SPARSE_INVERTED_INDEX", # the type of index to be created. setSPARSE_INVERTED_INDEX' or SPARSE_WAND
    metric_type="IP", # the metric type to be used for the index. Currentlyy, only `IP`(Inner Product) is supported
    params={"drop_ratio_build": 0.2}, # the ratio of small vector vvalues to be dropped during indexing
)
client.create_index(collection_name="test_sparse_vector", index_params=index_params)
client.load_collection(collection_name="test_sparse_vector")


queries= ["When was artificial intelligence founded","Where was Alan Turing born?"]
query_embeddings = bm25_ef.encode_queries(queries)
search_params = {
  "metric_type": "IP",
  "params": {"drop_ratio_search": 0.0}, # the ratio of ssmall vector values to be dropped during search
}
search_res = client.search(
  collection_name="test_sparse_vector",
  data=query_embeddings,
  limit=3,
  output_fields=["pk"],
  search_params=search_params,
)
print(search_res)
print(query_embeddings)
for hits in search_res:
    for hit in hits:
        print(f"hit:{hit}")

```

**Comment by dygwon** [comment]
@wxywb This works, and I really appreciate the quick response!

I thought there was a bug on insertion, but it seems there's a problem elsewhere. When using the client to get information about the collection, it is showing as having no data:
![image](https://github.com/user-attachments/assets/81f21c6a-358f-44b9-8b8d-10183f7e2faf)

This also happens with milvus_cli 1.0.0:
![image](https://github.com/user-attachments/assets/0cf77608-ab34-4e95-a6ae-68713089e991)

I assumed the insertion failed without an error because of these results.

**Comment by wxywb** [comment]
use  this to get how many inserted data in collection
```python
print(client.query(collection_name="test_sparse_vector", output_fields=["count(*)"]))
```
checkout [this page](https://milvus.io/api-reference/pymilvus/v2.4.x/MilvusClient/Collections/get_collection_stats.md) for why `get_collection_stats`is 0 , and notice there is a AI bot in doc page which can help you for using milvus.
