### ISSUE TITLE
[Bug]: The proxy hostNetwork is set to true and the configuration does not take effect

### ISSUE THREAD

**Issue by Richard-lrg** [milvus-io/milvus#36234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.11
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

How to set the proxy hostNetwork to true in the latest version of cluster mode? I found that the configuration will be overwritten by milvus-operator, resulting in ineffectiveness

**Comment by haorenfsa** [comment]
Are you referring to this? https://github.com/zilliztech/milvus-operator/pull/141

**Comment by Richard-lrg** [comment]
> zilliztech/milvus-operator#141

Yes, when proxy hostNetwork  is set to true, milvus-operator will always overwrite the configuration, causing the configuration to fail.

**Comment by haorenfsa** [comment]
@Richard-lrg  It seems you're using alpha api. It's deprecated since 2 years ago. Please use beta api instead.
