### ISSUE TITLE
[Bug]: [Nightly] Streaming service failed to bulk insert numpy 

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#36230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 8395c8a
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    Streaming service
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Streaming service failed to bulk insert numpy.

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI(new)/detail/master/115/pipeline/157
2. failure starting time: [pytest : test] testcases/test_bulk_insert.py::TestBulkInsert::test_bulk_insert_all_field_with_numpy[True-True-True-2000-128-True] FAILED [ 15%]

### Expected Behavior

pass

**Comment by chyezh** [comment]
same with #36016

**Comment by chyezh** [comment]
please verify it with latest master image

**Comment by NicoYuan1986** [comment]
Fixed.
Now it can pass all bulk insert test cases. 89397d1
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI(new)/detail/master/122/pipeline/139/
