### ISSUE TITLE
[Bug]: BinlogDeserializeReader leak in mix_compactor.go

### ISSUE THREAD

**Issue by fengjun2016** [milvus-io/milvus#36269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![截屏2024-09-13 22 48 10](https://github.com/user-attachments/assets/a3121b50-51c3-4ab1-abb5-f91da6726522)

**Comment by yanliang567** [comment]
/assign @congqixia 
please help to review the issue and pr

/unassign
