### ISSUE TITLE
[Bug]: milvus didn't return the same number of records as parameter "limit"

### ISSUE THREAD

**Issue by lukeisanniesdaddy** [milvus-io/milvus#36268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I searched use limit=10, but only 6 records returned from milvus, there are thousands of records in milvus

**Comment by yanliang567** [comment]
@lukeisanniesdaddy please share more info about the issue you met
1. milvus version, sdk version
2. collection schema, index type and params,  and reproduce code if convenient
3. Milvus log files 

/assign @lukeisanniesdaddy 
/unassign

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version:
> - Deployment mode(standalone or cluster):
> - MQ type(rocksmq, pulsar or kafka):    
> - SDK version(e.g. pymilvus v2.0.0rc2):
> - OS(Ubuntu or CentOS): 
> - CPU/Memory: 
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> When I searched use limit=10, but only 6 records returned from milvus, there are thousands of records in milvus
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

usually means your pk is duplicated

**Comment by lukeisanniesdaddy** [comment]
> > ### Is there an existing issue for this?
> > 
> > * [x]   I have searched the existing issues
> > 
> > ### Environment
> > ```
> > - Milvus version:
> > - Deployment mode(standalone or cluster):
> > - MQ type(rocksmq, pulsar or kafka):    
> > - SDK version(e.g. pymilvus v2.0.0rc2):
> > - OS(Ubuntu or CentOS): 
> > - CPU/Memory: 
> > - GPU: 
> > - Others:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Current Behavior
> > When I searched use limit=10, but only 6 records returned from milvus, there are thousands of records in milvus
> > ### Expected Behavior
> > _No response_
> > ### Steps To Reproduce
> > _No response_
> > ### Milvus Log
> > _No response_
> > ### Anything else?
> > _No response_
> 
> usually means your pk is duplicated

Thanks, the root cause was primary key duplicated. It's so strange that milvus allows primary key duplicate.

**Comment by xiaofan-luan** [comment]
> > > ### Is there an existing issue for this?
> > > 
> > > * [x]    I have searched the existing issues
> > > 
> > > ### Environment
> > > ```
> > > - Milvus version:
> > > - Deployment mode(standalone or cluster):
> > > - MQ type(rocksmq, pulsar or kafka):    
> > > - SDK version(e.g. pymilvus v2.0.0rc2):
> > > - OS(Ubuntu or CentOS): 
> > > - CPU/Memory: 
> > > - GPU: 
> > > - Others:
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ### Current Behavior
> > > When I searched use limit=10, but only 6 records returned from milvus, there are thousands of records in milvus
> > > ### Expected Behavior
> > > _No response_
> > > ### Steps To Reproduce
> > > _No response_
> > > ### Milvus Log
> > > _No response_
> > > ### Anything else?
> > > _No response_
> > 
> > 
> > usually means your pk is duplicated
> 
> Thanks, the root cause was primary key duplicated. It's so strange that milvus allows primary key duplicate.

this is something we will handle in the future. A legacy issue but thanks for pointing this out
