### ISSUE TITLE
[Bug]: [null & default] bulk writer does not support "None" data

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#36265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

bulk writer does not support "None" data

```
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Illegal scalar value for field 'int_scalar', value overflow or type mismatch)>
```

### Expected Behavior

bulk writer supports "None" data

### Steps To Reproduce

```markdown
NA
```

**Comment by smellthemoon** [comment]
by design.

**Comment by smellthemoon** [comment]
it plans to support it in 2.5.x.

**Comment by smellthemoon** [comment]
related with https://github.com/milvus-io/pymilvus/issues/2313 all the type(json, csv, parquet) can use bulk writer to write null now, could you help to verify it? @binbinlv

**Comment by xiaofan-luan** [comment]
should be fixed already

**Comment by binbinlv** [comment]
Verified and fixed.
