### ISSUE TITLE
[Bug]: collection loading failed

### ISSUE THREAD

**Issue by Richard-lrg** [milvus-io/milvus#36261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.11
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

collection loading failed, The number of collection entities is 5817258.
<img width="622" alt="9924caa490a320ce5624cadee" src="https://github.com/user-attachments/assets/ca5f11e0-8c00-490a-908d-042fbee14dfd">

Here are some logs when the collection fails to load.
[datacoord1.log](https://github.com/user-attachments/files/16992966/datacoord1.log)
[querycoord_part.log](https://github.com/user-attachments/files/16992997/querycoord_part.log)
[querynode1.log](https://github.com/user-attachments/files/16993003/querynode1.log)

**Comment by Richard-lrg** [comment]
export log by https://github.com/milvus-io/milvus/tree/master/deployments/export-log
[newlogs.tar.gz](https://github.com/user-attachments/files/16993808/newlogs.tar.gz)
[logs.tar.gz](https://github.com/user-attachments/files/16993809/logs.tar.gz)

**Comment by yanliang567** [comment]
@Richard-lrg which collection is failing in loading? do you have enough memory for loading it? I am asking because i found more than 1 collections in the cluster, and one of them has some large size of varchar fields.

/assign @xiaocai2333 
please help to take a look

/unassign

**Comment by Richard-lrg** [comment]
> @Richard-lrg which collection is failing in loading? do you have enough memory for loading it? I am asking because i found more than 1 collections in the cluster, and one of them has some large size of varchar fields.
> 
> /assign @xiaocai2333 please help to take a look
> 
> /unassign

Memory is enough

collection name: wendaPlugin

**Comment by xiaofan-luan** [comment]
seems that all the task is assigned to search-hbb-milvus-querycoord-84467c78fb for some reason.
can you reboot this server see if it can work?

**Comment by xiaofan-luan** [comment]
@weiliu1031 
can you add some logs and analuze why nodeID 9823 is always picked

**Comment by chyezh** [comment]
@Richard-lrg Could you please help to confirm the following issues:
1. Has the cluster been upgraded from v2.4.3-v2.4.5 to the current version.
2. Whether to use bulk-insert to insert data.

**Comment by xiaofan-luan** [comment]
how long did you wait for the loading to be done?
It seems that you get many collections and may take a while to load.

**Comment by chyezh** [comment]
Following logs found:

```
search-hbb-milvus-querycoord-84467c78fb-vbgm2.log:[2024/09/13 11:41:54.955 +00:00] [WARN] [observers/collection_observer.go:348] ["failed to manual check current target, skip update load status"] [collectionID=448355483134723882] [partitionID=448355483134723941]
```

**Comment by chyezh** [comment]
@Richard-lrg The log is not complete.
could you please provide the logs of `querycoord`,`querynode`,`proxy`,`datacoord` between 11:30 - 11:50?

**Comment by weiliu1031** [comment]
> seems that all the task is assigned to search-hbb-milvus-querycoord-84467c78fb for some reason. can you reboot this server see if it can work?

by design, all `l0 segment` need to be loaded at delegator node. and the collection `448355483134723882 ` is stuck at loading `l0 segment`. seems that there are much more l0 segment, did you delete lots of records on this collection? /cc @Richard-lrg

**Comment by Richard-lrg** [comment]
> @Richard-lrg Could you please help to confirm the following issues:
> 
> 1. Has the cluster been upgraded from v2.4.3-v2.4.5 to the current version.
> 2. Whether to use bulk-insert to insert data.

v2.4.0 to v2.4.11
yes, I used bulk-insert to insert data.

**Comment by Richard-lrg** [comment]
> > seems that all the task is assigned to search-hbb-milvus-querycoord-84467c78fb for some reason. can you reboot this server see if it can work?
> 
> by design, all `l0 segment` need to be loaded at delegator node. and the collection `448355483134723882 ` is stuck at loading `l0 segment`. seems that there are much more l0 segment, did you delete lots of records on this collection? /cc @Richard-lrg

No, I didn't delete it.

**Comment by Richard-lrg** [comment]
> how long did you wait for the loading to be done? It seems that you get many collections and may take a while to load.

I don't remember
The collection will fail to load after about 10 minutes?(This value may not be accurate)

**Comment by Richard-lrg** [comment]
> @weiliu1031 can you add some logs and analuze why nodeID 9823 is always picked

The accident scene no longer exists.
I guess it has something to do with the partition _default_5, which has a very large amount of data.

**Comment by weiliu1031** [comment]
> > @weiliu1031 can you add some logs and analuze why nodeID 9823 is always picked
> 
> The accident scene no longer exists. I guess it has something to do with the partition _default_5, which has a very large amount of data. ![image](https://private-user-images.githubusercontent.com/30857401/369350085-704c3f54-6aed-4a38-bf83-30da2299170f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MjUxNTMsIm5iZiI6MTcyNjgyNDg1MywicGF0aCI6Ii8zMDg1NzQwMS8zNjkzNTAwODUtNzA0YzNmNTQtNmFlZC00YTM4LWJmODMtMzBkYTIyOTkxNzBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA5MzQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmNThlMWVkOTk4MjA0OTZkOTViZDI4MzgyMDA1ZjYzNDRjY2MyOTA5NGM1YzQxNTdmMWU3OTQ5NzRhOGEyN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jeyod-gOb9kQ7Kba6EMjJPCPChcPBPmonflm2j1UCj8)

as mentioned above. it pick nodeID 9823 to load `l0 segment`, which is by design. if those accident scene gone, which means compaction finished or all `l0 segments` has been loaded

**Comment by weiliu1031** [comment]
> > > seems that all the task is assigned to search-hbb-milvus-querycoord-84467c78fb for some reason. can you reboot this server see if it can work?
> > 
> > 
> > by design, all `l0 segment` need to be loaded at delegator node. and the collection `448355483134723882 ` is stuck at loading `l0 segment`. seems that there are much more l0 segment, did you delete lots of records on this collection? /cc @Richard-lrg
> 
> No, I didn't delete it.

did you do `upsert` on this collection?

**Comment by Richard-lrg** [comment]
> > > > seems that all the task is assigned to search-hbb-milvus-querycoord-84467c78fb for some reason. can you reboot this server see if it can work?
> > > 
> > > 
> > > by design, all `l0 segment` need to be loaded at delegator node. and the collection `448355483134723882 ` is stuck at loading `l0 segment`. seems that there are much more l0 segment, did you delete lots of records on this collection? /cc @Richard-lrg
> > 
> > 
> > No, I didn't delete it.
> 
> did you do `upsert` on this collection?

yes

**Comment by weiliu1031** [comment]
> > > > > seems that all the task is assigned to search-hbb-milvus-querycoord-84467c78fb for some reason. can you reboot this server see if it can work?
> > > > 
> > > > 
> > > > by design, all `l0 segment` need to be loaded at delegator node. and the collection `448355483134723882 ` is stuck at loading `l0 segment`. seems that there are much more l0 segment, did you delete lots of records on this collection? /cc @Richard-lrg
> > > 
> > > 
> > > No, I didn't delete it.
> > 
> > 
> > did you do `upsert` on this collection?
> 
> yes

make sense, upsert contains a internal delete operation, which generates lots of delete records.

**Comment by Richard-lrg** [comment]
> > > > > > seems that all the task is assigned to search-hbb-milvus-querycoord-84467c78fb for some reason. can you reboot this server see if it can work?
> > > > > 
> > > > > 
> > > > > by design, all `l0 segment` need to be loaded at delegator node. and the collection `448355483134723882 ` is stuck at loading `l0 segment`. seems that there are much more l0 segment, did you delete lots of records on this collection? /cc @Richard-lrg
> > > > 
> > > > 
> > > > No, I didn't delete it.
> > > 
> > > 
> > > did you do `upsert` on this collection?
> > 
> > 
> > yes
> 
> make sense, upsert contains a internal delete operation, which generates lots of delete records.

Is there any reason for this error? 
What steps can help me avoid this?

**Comment by xiaofan-luan** [comment]
> > > > > > > seems that all the task is assigned to search-hbb-milvus-querycoord-84467c78fb for some reason. can you reboot this server see if it can work?
> > > > > > 
> > > > > > 
> > > > > > by design, all `l0 segment` need to be loaded at delegator node. and the collection `448355483134723882 ` is stuck at loading `l0 segment`. seems that there are much more l0 segment, did you delete lots of records on this collection? /cc @Richard-lrg
> > > > > 
> > > > > 
> > > > > No, I didn't delete it.
> > > > 
> > > > 
> > > > did you do `upsert` on this collection?
> > > 
> > > 
> > > yes
> > 
> > 
> > make sense, upsert contains a internal delete operation, which generates lots of delete records.
> 
> Is there any reason for this error? What steps can help me avoid this?

Right now we think it's just too many deletes that cause failure recovery to be slow. 

To avoid that retry not to use upsert but use insert instead, or increase the datanode size to increase the compaction speed.

We are also working on optimizing load performance of delete segment load but it's still necessary to control the size of L0

**Comment by xiaofan-luan** [comment]
@weiliu1031 
it seems that there is only 1.6 million data in the collection. Do we have any idea about how much deletion is there in one account?

**Comment by Richard-lrg** [comment]
> > > > > > > > seems that all the task is assigned to search-hbb-milvus-querycoord-84467c78fb for some reason. can you reboot this server see if it can work?
> > > > > > > 
> > > > > > > 
> > > > > > > by design, all `l0 segment` need to be loaded at delegator node. and the collection `448355483134723882 ` is stuck at loading `l0 segment`. seems that there are much more l0 segment, did you delete lots of records on this collection? /cc @Richard-lrg
> > > > > > 
> > > > > > 
> > > > > > No, I didn't delete it.
> > > > > 
> > > > > 
> > > > > did you do `upsert` on this collection?
> > > > 
> > > > 
> > > > yes
> > > 
> > > 
> > > make sense, upsert contains a internal delete operation, which generates lots of delete records.
> > 
> > 
> > Is there any reason for this error? What steps can help me avoid this?
> 
> Right now we think it's just too many deletes that cause failure recovery to be slow.
> 
> To avoid that retry not to use upsert but use insert instead, or increase the datanode size to increase the compaction speed.
> 
> We are also working on optimizing load performance of delete segment load but it's still necessary to control the size of L0

Got it, thx.
