### ISSUE TITLE
[Bug]: The BM25 "Function" module error messages are not user-friendly

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#36300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2024-09-14 18:27:30 - ERROR - ci_test]: (api_response) : <ParamError: (code=1, message=Function output field not found in collection schema.)> (api_request.py:46)
```
In the BM25 function, the output field uses a non-existent field, and the error message does not indicate which field does not exist.

### Expected Behavior

It's better to specify which field does not exist, as users may use multiple BM25 functions.

**Comment by zhengbuqian** [comment]
fixed in pymilvus https://github.com/milvus-io/pymilvus/blob/4ed5d3e4d89c5989652c5cbeaaedc1ac1533f6f7/pymilvus/orm/schema.py#L204

in milvus, the error message already indicates the missing field
