### ISSUE TITLE
[Bug]: pulsar error

### ISSUE THREAD

**Issue by lzhin** [milvus-io/milvus#36308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.5
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://public/default/by-dev-rootcoord-dml_10] Backlog quota exceeded. Cannot create producer [standalone-0-26]
23:33:02.925 [pulsar-io-18-1] INFO  org.apache.pulsar.broker.service.ServerCnx - [/10.137.100.86:1194][persistent://public/default/by-dev-rootcoord-dml_10] Creating producer. producerId=19
23:33:02.925 [pulsar-io-18-1] INFO  org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://public/default/by-dev-rootcoord-dml_10] Backlog quota exceeded. Cannot create producer [standalone-0-5]
23:33:02.926 [pulsar-io-18-3] INFO  org.apache.pulsar.broker.service.ServerCnx - [/10.137.100.81:1220][persistent://public/default/by-dev-rootcoord-dml_10] Creating producer. producerId=27
23:33:02.926 [pulsar-io-18-3] INFO  org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://public/default/by-dev-rootcoord-dml_10] Backlog quota exceeded. Cannot create producer [standalone-0-11]

**Comment by yanliang567** [comment]
@lzhin in which situations or steps, it happens?  
from the error message, there are 2 possible problem here
a. there are some orphan subscription left in you pulsar, you could try to use pulsarctl to check which topics and subscriptions are causing this problem.
b. the datanode failed to consume and digest the dml data, which causing the backlog size continue to raise.

/assign @lzhin 
/unassign

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version:2.3.5
> - Deployment mode(standalone or cluster):
> - MQ type(rocksmq, pulsar or kafka):    
> - SDK version(e.g. pymilvus v2.0.0rc2):
> - OS(Ubuntu or CentOS): 
> - CPU/Memory: 
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://public/default/by-dev-rootcoord-dml_10] Backlog quota exceeded. Cannot create producer [standalone-0-26] 23:33:02.925 [pulsar-io-18-1] INFO org.apache.pulsar.broker.service.ServerCnx - [/10.137.100.86:1194][persistent://public/default/by-dev-rootcoord-dml_10] Creating producer. producerId=19 23:33:02.925 [pulsar-io-18-1] INFO org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://public/default/by-dev-rootcoord-dml_10] Backlog quota exceeded. Cannot create producer [standalone-0-5] 23:33:02.926 [pulsar-io-18-3] INFO org.apache.pulsar.broker.service.ServerCnx - [/10.137.100.81:1220][persistent://public/default/by-dev-rootcoord-dml_10] Creating producer. producerId=27 23:33:02.926 [pulsar-io-18-3] INFO org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://public/default/by-dev-rootcoord-dml_10] Backlog quota exceeded. Cannot create producer [standalone-0-11]
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

It seems that certain pulsar topic hit backlog exceed. 
This usually happened when consumer can not consume data correctly.

You can use pulsar ctl to check which consumer actaully cause this problem.

Meantime, strongly recommend you to upgrade to Milvus 2.3.21 or 2.4.12

**Comment by lzhin** [comment]
> > ### Is there an existing issue for this?
> > 
> > * [x]   I have searched the existing issues
> > 
> > ### Environment
> > ```
> > - Milvus version:2.3.5
> > - Deployment mode(standalone or cluster):
> > - MQ type(rocksmq, pulsar or kafka):    
> > - SDK version(e.g. pymilvus v2.0.0rc2):
> > - OS(Ubuntu or CentOS): 
> > - CPU/Memory: 
> > - GPU: 
> > - Others:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Current Behavior
> > org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://public/default/by-dev-rootcoord-dml_10] Backlog quota exceeded. Cannot create producer [standalone-0-26] 23:33:02.925 [pulsar-io-18-1] INFO org.apache.pulsar.broker.service.ServerCnx - [/10.137.100.86:1194][persistent://public/default/by-dev-rootcoord-dml_10] Creating producer. producerId=19 23:33:02.925 [pulsar-io-18-1] INFO org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://public/default/by-dev-rootcoord-dml_10] Backlog quota exceeded. Cannot create producer [standalone-0-5] 23:33:02.926 [pulsar-io-18-3] INFO org.apache.pulsar.broker.service.ServerCnx - [/10.137.100.81:1220][persistent://public/default/by-dev-rootcoord-dml_10] Creating producer. producerId=27 23:33:02.926 [pulsar-io-18-3] INFO org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://public/default/by-dev-rootcoord-dml_10] Backlog quota exceeded. Cannot create producer [standalone-0-11]
> > ### Expected Behavior
> > _No response_
> > ### Steps To Reproduce
> > _No response_
> > ### Milvus Log
> > _No response_
> > ### Anything else?
> > _No response_
> 
> It seems that certain pulsar topic hit backlog exceed. This usually happened when consumer can not consume data correctly.
> 
> You can use pulsar ctl to check which consumer actaully cause this problem.
> 
> Meantime, strongly recommend you to upgrade to Milvus 2.3.21 or 2.4.12

I upgrade to Milvus 2.3.21，but occur a new problem, the root  space Utilization rate of querynode is  100%.
![image](https://github.com/user-attachments/assets/a62006a1-f65b-48bb-a224-a2e00303565d)

**Comment by xiaofan-luan** [comment]
> > > ### Is there an existing issue for this?
> > > 
> > > * [x]    I have searched the existing issues
> > > 
> > > ### Environment
> > > ```
> > > - Milvus version:2.3.5
> > > - Deployment mode(standalone or cluster):
> > > - MQ type(rocksmq, pulsar or kafka):    
> > > - SDK version(e.g. pymilvus v2.0.0rc2):
> > > - OS(Ubuntu or CentOS): 
> > > - CPU/Memory: 
> > > - GPU: 
> > > - Others:
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ### Current Behavior
> > > org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://public/default/by-dev-rootcoord-dml_10] Backlog quota exceeded. Cannot create producer [standalone-0-26] 23:33:02.925 [pulsar-io-18-1] INFO org.apache.pulsar.broker.service.ServerCnx - [/10.137.100.86:1194][persistent://public/default/by-dev-rootcoord-dml_10] Creating producer. producerId=19 23:33:02.925 [pulsar-io-18-1] INFO org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://public/default/by-dev-rootcoord-dml_10] Backlog quota exceeded. Cannot create producer [standalone-0-5] 23:33:02.926 [pulsar-io-18-3] INFO org.apache.pulsar.broker.service.ServerCnx - [/10.137.100.81:1220][persistent://public/default/by-dev-rootcoord-dml_10] Creating producer. producerId=27 23:33:02.926 [pulsar-io-18-3] INFO org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://public/default/by-dev-rootcoord-dml_10] Backlog quota exceeded. Cannot create producer [standalone-0-11]
> > > ### Expected Behavior
> > > _No response_
> > > ### Steps To Reproduce
> > > _No response_
> > > ### Milvus Log
> > > _No response_
> > > ### Anything else?
> > > _No response_
> > 
> > 
> > It seems that certain pulsar topic hit backlog exceed. This usually happened when consumer can not consume data correctly.
> > You can use pulsar ctl to check which consumer actaully cause this problem.
> > Meantime, strongly recommend you to upgrade to Milvus 2.3.21 or 2.4.12
> 
> I upgrade to Milvus 2.3.21，but occur a new problem, the root space Utilization rate of querynode is 100%. ![image](https://private-user-images.githubusercontent.com/17926066/370526824-a62006a1-f65b-48bb-a224-a2e00303565d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MjE2MjcsIm5iZiI6MTcyNzQyMTMyNywicGF0aCI6Ii8xNzkyNjA2Ni8zNzA1MjY4MjQtYTYyMDA2YTEtZjY1Yi00OGJiLWEyMjQtYTJlMDAzMDM1NjVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDA3MTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNzhiZWViMTkzNTU4NWNlNmU0OWU3YTcyN2EzYjIwOTMzOTk3NTk0MWQ2NWM2MjBhMTE1Mjc1OGFjMDkzY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jYQCWrzRrH_EY-P4bb_ZdUtVgrQXA9wJz5-6VAJAE6Q)

did you config the right disk space?
How much data you want to insert and how much disk space you have?

**Comment by lzhin** [comment]
> > > > ### Is there an existing issue for this?
> > > > 
> > > > * [x]     I have searched the existing issues
> > > > 
> > > > ### Environment
> > > > ```
> > > > - Milvus version:2.3.5
> > > > - Deployment mode(standalone or cluster):
> > > > - MQ type(rocksmq, pulsar or kafka):    
> > > > - SDK version(e.g. pymilvus v2.0.0rc2):
> > > > - OS(Ubuntu or CentOS): 
> > > > - CPU/Memory: 
> > > > - GPU: 
> > > > - Others:
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ### Current Behavior
> > > > org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://public/default/by-dev-rootcoord-dml_10] Backlog quota exceeded. Cannot create producer [standalone-0-26] 23:33:02.925 [pulsar-io-18-1] INFO org.apache.pulsar.broker.service.ServerCnx - [/10.137.100.86:1194][persistent://public/default/by-dev-rootcoord-dml_10] Creating producer. producerId=19 23:33:02.925 [pulsar-io-18-1] INFO org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://public/default/by-dev-rootcoord-dml_10] Backlog quota exceeded. Cannot create producer [standalone-0-5] 23:33:02.926 [pulsar-io-18-3] INFO org.apache.pulsar.broker.service.ServerCnx - [/10.137.100.81:1220][persistent://public/default/by-dev-rootcoord-dml_10] Creating producer. producerId=27 23:33:02.926 [pulsar-io-18-3] INFO org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://public/default/by-dev-rootcoord-dml_10] Backlog quota exceeded. Cannot create producer [standalone-0-11]
> > > > ### Expected Behavior
> > > > _No response_
> > > > ### Steps To Reproduce
> > > > _No response_
> > > > ### Milvus Log
> > > > _No response_
> > > > ### Anything else?
> > > > _No response_
> > > 
> > > 
> > > It seems that certain pulsar topic hit backlog exceed. This usually happened when consumer can not consume data correctly.
> > > You can use pulsar ctl to check which consumer actaully cause this problem.
> > > Meantime, strongly recommend you to upgrade to Milvus 2.3.21 or 2.4.12
> > 
> > 
> > I upgrade to Milvus 2.3.21，but occur a new problem, the root space Utilization rate of querynode is 100%. ![image](https://private-user-images.githubusercontent.com/17926066/370526824-a62006a1-f65b-48bb-a224-a2e00303565d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MjE2MjcsIm5iZiI6MTcyNzQyMTMyNywicGF0aCI6Ii8xNzkyNjA2Ni8zNzA1MjY4MjQtYTYyMDA2YTEtZjY1Yi00OGJiLWEyMjQtYTJlMDAzMDM1NjVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDA3MTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNzhiZWViMTkzNTU4NWNlNmU0OWU3YTcyN2EzYjIwOTMzOTk3NTk0MWQ2NWM2MjBhMTE1Mjc1OGFjMDkzY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jYQCWrzRrH_EY-P4bb_ZdUtVgrQXA9wJz5-6VAJAE6Q)
> 
> did you config the right disk space? How much data you want to insert and how much disk space you have?

the config is right ,when use 2.3.5, dont have the problem that space abnormal 。  the data is tens of millions，the dim is 128.   the disk of / is 10G.

**Comment by yanliang567** [comment]
did you check the pulsar as suggested above?

**Comment by lzhin** [comment]
> did you check the pulsar as suggested above?

didnot , I just upgrade to 2.3.21 directly

**Comment by yanliang567** [comment]
please try it and keep us posted

**Comment by lzhin** [comment]
> please try it and keep us posted

I had upgrade to 2.3.21, and the pulsar error is not occur again
