### ISSUE TITLE
Search time cost too much 

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#3630]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
dataset: `sift-50m`
index_type: `flat`
no other fields in collection

```
03:57:18  2020-09-05:19:57:08,857 INFO     [runner.py:231] Min query time: 391.88
03:57:18  2020-09-05:19:57:08,887 INFO     [k8s_runner.py:369] Search param: {"nprobe": 8}
03:57:18  ╭─────────────┬─────────────┬─────────────┬─────────────┬─────────────╮
03:57:18  │  Nq/Top-k   │      1      │     10      │     100     │    1000     │
03:57:18  ├─────────────┼─────────────┼─────────────┼─────────────┼─────────────┤
03:57:18  │           1 │        1.42 │         2.1 │        1.58 │        1.97 │
03:57:18  │          10 │        4.89 │        2.53 │        2.02 │        5.17 │
03:57:18  │         100 │        7.71 │        7.89 │       11.05 │       43.48 │
03:57:18  │         200 │       14.18 │       14.78 │       21.18 │       78.97 │
03:57:18  │         500 │       39.05 │       42.92 │       57.41 │      199.99 │
03:57:18  │        1000 │       80.39 │        83.9 │      116.59 │      391.88 │
03:57:18  ╰─────────────┴─────────────┴─────────────┴─────────────┴─────────────╯
03:57:18  2020-09-05:19:57:08,890 INFO     [client.py:383] Server command: mode, result: CPU
03:57:18  2020-09-05:19:57:08,891 INFO     [client.py:383] Server command: build_commit_id, result: ed50cb303f0a1b16a7a1ab0a41b190f48434db2f
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by shengjun1985** [comment]
same as #3846

**Comment by del-zhenwu** [comment]
need regression
