### ISSUE TITLE
[Bug]: Including unsupported csv delimiter

### ISSUE THREAD

**Issue by OxalisCu** [milvus-io/milvus#36309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The list of unsupported CSV delimiters is currently incomplete.

### Expected Behavior

Add unicode replacement character (0xFFFD) to the list of unsupported delimiters

**Comment by yanliang567** [comment]
/assign @czs007 
please help to review the code

/unassign

**Comment by xiaofan-luan** [comment]
@OxalisCu 
do we have any sample csv to test?

**Comment by OxalisCu** [comment]
You can use pymilvus to configure supported delimiters to generate csv files for testing. However, characters such as \0 or 0xFFFD cannot be written into csv files as delimiters (the go or python library will report an error when writing), so there is no relevant csv file for importing.
