### ISSUE TITLE
[Bug]: Async operation is not working as expected for search in collection by using pymilvus 

### ISSUE THREAD

**Issue by V-N-Bhat** [milvus-io/milvus#36316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:latest
```

### Current Behavior

I am trying to perform searching in the collection asynchronously and  using pymilvus by passing _async as true along with a call back function  it was running in the sync way instead of async . And tried to run the same collection.search. on different threads then also the database it self is running the search operation one by one .

### Expected Behavior

The query should run in parallelly or  asynchronously.  and  produce result in less amount of time.

### Steps To Reproduce

```markdown
def milvus_search(embedding_query):
    collection = Collection("bank")
    return collection.search(data=[embedding_query],
                                      anns_field="vector",
                                      param=search_params,
                                      limit=10,
                                      kwargs={"_async": True, "_callback": handle_result}
                                      )

async def search() -> SearchResult:
    embedding_function = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
    embedding_query = embedding_function.embed_query("sso")
    search_future = await asyncio.to_thread(
        milvus_search,
        embedding_query
    )
return search_future


async def something() -> None:
    start =time.time()

    search_tasks = [search() for _ in range(2)]
    await asyncio.gather(*search_tasks)
    end = time.time()

    print(f"took{start - end} ")


if __name__ == "__main__":
    asyncio.run(something())
```

**Comment by XuanYang-cn** [comment]
@V-N-Bhat Sadlly PyMilvus doesn't support asyncio currently.  The underneath of `_async` is a synchronous grpc channel.

**Comment by V-N-Bhat** [comment]
@XuanYang-cn  Thank you  for the answer. I am closing the issue

**Comment by xiaofan-luan** [comment]
> @V-N-Bhat Sadlly PyMilvus doesn't support asyncio currently. The underneath of `_async` is a synchronous grpc channel.

what need to be done to support asyncio?

**Comment by xiaofan-luan** [comment]
@XuanYang-cn any thoughts?
