### ISSUE TITLE
The RPS of create collection is decrease dramatically when collection num reaches about 1300-1500

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#3633]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

![Screenshot_2020-09-07 Locust](https://user-images.githubusercontent.com/27288593/92365604-a22b0100-f126-11ea-8a42-d8c06a1c162a.png)

**Steps/Code to reproduce behavior**
create a collection with fields:
```
default_fields = {
        "fields": [
            {"field": "int64", "type": DataType.INT64},
            {"field": "float", "type": DataType.FLOAT},
            {"field": default_float_vec_field_name, "type": DataType.FLOAT_VECTOR, "params": {"dim": dim}},
        ],
        "segment_row_count": segment_row_count,
        "auto_id" : auto_id
    }
```
**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [x] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by shengjun1985** [comment]
＠ThreadDao
The meta system is modified a lot.
Please allow me to close the old issue.
If it can be reproduced in the new version, please assign to BossZou.
