### ISSUE TITLE
The RPS of create collection is too low

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#3634]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
The RPS of create collection is between 28 and 10.The num_users is 100, spawn_rate is 20, step_users is 20 and step_time is 1m.
![image](https://user-images.githubusercontent.com/27288593/92366347-9a1f9100-f127-11ea-9608-6d16a4717400.png)

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [x] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
-0.11.0

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
steps or script...

**Comment by del-zhenwu** [comment]
```
 Name                                                          # reqs      # fails     Avg     Min     Max  |  Median   req/s failures/s
--------------------------------------------------------------------------------------------------------------------------------------------
 grpc create_collection                                         13152     0(0.00%)   14577      27   47300  |   13000   22.40    0.00
--------------------------------------------------------------------------------------------------------------------------------------------
 Aggregated                                                     13152     0(0.00%)   14577      27   47300  |   13000   22.40    0.00

```
