### ISSUE TITLE
[Bug]: When specifying a key of dynamic data to output, the keys of the entire dynamic fields is returned #820

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#36340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4-20240916-72f18238
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://github.com/milvus-io/milvus-sdk-go/issues/820

**Comment by zhagnlu** [comment]
same as https://github.com/milvus-io/milvus-sdk-go/issues/820

**Comment by yanliang567** [comment]
is it a go sdk issue or a milvus server issue? @zhagnlu 
/assign @zhagnlu 
/unassign

**Comment by czs007** [comment]
@ThreadDao fix pr has been merged, please help verify this.

**Comment by ThreadDao** [comment]
fixed
