### ISSUE TITLE
[Bug]: [streamingnode]After enabling the streaming node, all test cases hung after Milvus recovering from the minio pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#36388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20240919-f6526121-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/user-attachments/assets/7fda3fbb-5b3c-424b-8c0d-c09e37fcab41)

flush and describe collection cost a lot of time
![image](https://github.com/user-attachments/assets/c90923bc-93ac-4fc2-bbe7-b8470af74059)

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-straming-node-cron/detail/chaos-test-straming-node-cron/19/pipeline
log:
[artifacts-s3-pod-kill-19-server-logs.tar.gz](https://github.com/user-attachments/files/17070710/artifacts-s3-pod-kill-19-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
/assign @chyezh 
PTAL

**Comment by chyezh** [comment]
There's an error-handling bug at Txn of streaming service.
Cause a dead lock forever.
```
			defer func() {
				if err != nil {
					txnSession.AddNewMessageFail()
				}
				// perform keepalive for the transaction session if append success.
				txnSession.AddNewMessageDoneAndKeepalive(msg.TimeTick())
			}()
```

**Comment by zhuwenxing** [comment]
verified and passed with image tag `master-20240925-aee046e5-amd64`
![image](https://github.com/user-attachments/assets/13305eb6-f295-4232-bac3-a1ebfa19b31d)
