### ISSUE TITLE
[Bug]:  illegal connection params or server unavailable)>

### ISSUE THREAD

**Issue by lonngxiang** [milvus-io/milvus#36383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
environs-9.5.0 milvus-lite-2.4.10 milvus-model-0.2.5 onnxruntime-1.16.3 pymilvus-2.4.6
```

### Current Behavior

run error？？

from pymilvus import MilvusClient

client = MilvusClient("milvus_demo.db")

### Milvus Log

/home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/milvus: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/milvus)
/home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/milvus: /lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/milvus)
/home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/milvus: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/milvus)
/home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/milvus: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/milvus)
/home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/milvus: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/milvus)
/home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/milvus: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/milvus)
/home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/milvus: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/milvus)
/home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/milvus: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/libknowhere.so)
/home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/milvus: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/libknowhere.so)
/home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/milvus: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/libknowhere.so)
/home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/milvus: /lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/libknowhere.so)
/home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/milvus: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/libknowhere.so)
/home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/milvus: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/libknowhere.so)
/home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/milvus: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/libknowhere.so)
/home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/milvus: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/libglog.so.1)
/home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/milvus: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/libglog.so.1)
/home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/milvus: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/libglog.so.1)
/home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/milvus: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/libglog.so.1)
/home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/milvus: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/libgflags_nothreads.so.2.2)
/home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/milvus: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/libgflags_nothreads.so.2.2)
/home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/milvus: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/libgflags_nothreads.so.2.2)
/home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/milvus: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/libgflags_nothreads.so.2.2)
/home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/milvus: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/libtbb.so.12)
/home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/milvus: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/anaconda3/envs/llm/lib/python3.10/site-packages/milvus_lite/lib/libtbb.so.12)
Failed to create new connection using: ce0ce204ba554cbb9fa375302bde5324
---------------------------------------------------------------------------
MilvusException                           Traceback (most recent call last)
    [... skipping hidden 1 frame]

Cell In[1], line 3
      1 from pymilvus import MilvusClient
----> 3 client = MilvusClient("milvus_demo.db")

File /home/anaconda3/envs/llm/lib/python3.10/site-packages/pymilvus/milvus_client/milvus_client.py:59, in MilvusClient.__init__(self, uri, user, password, db_name, token, timeout, **kwargs)
     47 """A client for the common Milvus use case.
     48 
     49 This client attempts to hide away the complexity of using Pymilvus. In a lot ofcases what
   (...)
     57         to None.
     58 """
---> 59 self._using = self._create_connection(
     60     uri, user, password, db_name, token, timeout=timeout, **kwargs
     61 )
     62 self.is_self_hosted = bool(utility.get_server_type(using=self._using) == "milvus")

File /home/anaconda3/envs/llm/lib/python3.10/site-packages/pymilvus/milvus_client/milvus_client.py:656, in MilvusClient._create_connection(self, uri, user, password, db_name, token, **kwargs)
    655     logger.error("Failed to create new connection using: %s", using)
--> 656     raise ex from ex
    657 else:

File /home/anaconda3/envs/llm/lib/python3.10/site-packages/pymilvus/milvus_client/milvus_client.py:653, in MilvusClient._create_connection(self, uri, user, password, db_name, token, **kwargs)
    652 try:
--> 653     connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
    654 except Exception as ex:

File /home/anaconda3/envs/llm/lib/python3.10/site-packages/pymilvus/orm/connections.py:449, in Connections.connect(self, alias, user, password, db_name, token, **kwargs)
    447         kwargs["secure"] = True
--> 449 connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
    450 return

File /home/anaconda3/envs/llm/lib/python3.10/site-packages/pymilvus/orm/connections.py:400, in Connections.connect.<locals>.connect_milvus(**kwargs)
    398 timeout = t if isinstance(t, (int, float)) else Config.MILVUS_CONN_TIMEOUT
--> 400 gh._wait_for_channel_ready(timeout=timeout)
    401 if kwargs.get("keep_alive", False):

File /home/anaconda3/envs/llm/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py:150, in GrpcHandler._wait_for_channel_ready(self, timeout)
    149 except grpc.FutureTimeoutError as e:
--> 150     raise MilvusException(
    151         code=Status.CONNECT_FAILED,
    152         message=f"Fail connecting to server on {self._address}, illegal connection params or server unavailable",
    153     ) from e
    154 except Exception as e:

MilvusException: <MilvusException: (code=2, message=Fail connecting to server on uni[x:/tmp/tmpmfvqqaaz_milvus_demo.db.sock](file:///X:/tmp/tmpmfvqqaaz_milvus_demo.db.sock), illegal connection params or server unavailable)>

The above exception was the direct cause of the following exception:

MilvusException                           Traceback (most recent call last)
    [... skipping hidden 1 frame]

Cell In[1], line 3
      1 from pymilvus import MilvusClient
----> 3 client = MilvusClient("milvus_demo.db")

File /home/anaconda3/envs/llm/lib/python3.10/site-packages/pymilvus/milvus_client/milvus_client.py:59, in MilvusClient.__init__(self, uri, user, password, db_name, token, timeout, **kwargs)
     47 """A client for the common Milvus use case.
     48 
     49 This client attempts to hide away the complexity of using Pymilvus. In a lot ofcases what
   (...)
     57         to None.
     58 """
---> 59 self._using = self._create_connection(
     60     uri, user, password, db_name, token, timeout=timeout, **kwargs
     61 )
     62 self.is_self_hosted = bool(utility.get_server_type(using=self._using) == "milvus")

File /home/anaconda3/envs/llm/lib/python3.10/site-packages/pymilvus/milvus_client/milvus_client.py:656, in MilvusClient._create_connection(self, uri, user, password, db_name, token, **kwargs)
    655     logger.error("Failed to create new connection using: %s", using)
--> 656     raise ex from ex
    657 else:

File /home/anaconda3/envs/llm/lib/python3.10/site-packages/pymilvus/milvus_client/milvus_client.py:653, in MilvusClient._create_connection(self, uri, user, password, db_name, token, **kwargs)
    652 try:
--> 653     connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
    654 except Exception as ex:

File /home/anaconda3/envs/llm/lib/python3.10/site-packages/pymilvus/orm/connections.py:449, in Connections.connect(self, alias, user, password, db_name, token, **kwargs)
    447         kwargs["secure"] = True
--> 449 connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
    450 return

File /home/anaconda3/envs/llm/lib/python3.10/site-packages/pymilvus/orm/connections.py:400, in Connections.connect.<locals>.connect_milvus(**kwargs)
    398 timeout = t if isinstance(t, (int, float)) else Config.MILVUS_CONN_TIMEOUT
--> 400 gh._wait_for_channel_ready(timeout=timeout)
    401 if kwargs.get("keep_alive", False):

File /home/anaconda3/envs/llm/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py:150, in GrpcHandler._wait_for_channel_ready(self, timeout)
    149 except grpc.FutureTimeoutError as e:
--> 150     raise MilvusException(
    151         code=Status.CONNECT_FAILED,
    152         message=f"Fail connecting to server on {self._address}, illegal connection params or server unavailable",
    153     ) from e
    154 except Exception as e:

MilvusException: <MilvusException: (code=2, message=Fail connecting to server on uni[x:/tmp/tmpmfvqqaaz_milvus_demo.db.sock](file:///X:/tmp/tmpmfvqqaaz_milvus_demo.db.sock), illegal connection params or server unavailable)>

The above exception was the direct cause of the following exception:

MilvusException                           Traceback (most recent call last)
Cell In[1], line 3
      1 from pymilvus import MilvusClient
----> 3 client = MilvusClient("milvus_demo.db")

File /home/anaconda3/envs/llm/lib/python3.10/site-packages/pymilvus/milvus_client/milvus_client.py:59, in MilvusClient.__init__(self, uri, user, password, db_name, token, timeout, **kwargs)
     37 def __init__(
     38     self,
     39     uri: str = "http://localhost:19530",
   (...)
     45     **kwargs,
     46 ) -> None:
     47     """A client for the common Milvus use case.
     48 
     49     This client attempts to hide away the complexity of using Pymilvus. In a lot ofcases what
   (...)
     57             to None.
     58     """
---> 59     self._using = self._create_connection(
     60         uri, user, password, db_name, token, timeout=timeout, **kwargs
     61     )
     62     self.is_self_hosted = bool(utility.get_server_type(using=self._using) == "milvus")

File /home/anaconda3/envs/llm/lib/python3.10/site-packages/pymilvus/milvus_client/milvus_client.py:656, in MilvusClient._create_connection(self, uri, user, password, db_name, token, **kwargs)
    654 except Exception as ex:
    655     logger.error("Failed to create new connection using: %s", using)
--> 656     raise ex from ex
    657 else:
    658     logger.debug("Created new connection using: %s", using)

File /home/anaconda3/envs/llm/lib/python3.10/site-packages/pymilvus/milvus_client/milvus_client.py:653, in MilvusClient._create_connection(self, uri, user, password, db_name, token, **kwargs)
    651 using = uuid4().hex
    652 try:
--> 653     connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
    654 except Exception as ex:
    655     logger.error("Failed to create new connection using: %s", using)

File /home/anaconda3/envs/llm/lib/python3.10/site-packages/pymilvus/orm/connections.py:449, in Connections.connect(self, alias, user, password, db_name, token, **kwargs)
    446         if parsed_uri.scheme == "https":
    447             kwargs["secure"] = True
--> 449     connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
    450     return
    452 # 2nd Priority, connection configs from env

File /home/anaconda3/envs/llm/lib/python3.10/site-packages/pymilvus/orm/connections.py:400, in Connections.connect.<locals>.connect_milvus(**kwargs)
    397 t = kwargs.get("timeout")
    398 timeout = t if isinstance(t, (int, float)) else Config.MILVUS_CONN_TIMEOUT
--> 400 gh._wait_for_channel_ready(timeout=timeout)
    401 if kwargs.get("keep_alive", False):
    402     gh.register_state_change_callback(
    403         ReconnectHandler(self, alias, kwargs_copy).reconnect_on_idle
    404     )

File /home/anaconda3/envs/llm/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py:150, in GrpcHandler._wait_for_channel_ready(self, timeout)
    148     self._setup_identifier_interceptor(self._user, timeout=timeout)
    149 except grpc.FutureTimeoutError as e:
--> 150     raise MilvusException(
    151         code=Status.CONNECT_FAILED,
    152         message=f"Fail connecting to server on {self._address}, illegal connection params or server unavailable",
    153     ) from e
    154 except Exception as e:
    155     raise e from e

MilvusException: <MilvusException: (code=2, message=Fail connecting to server on unix:/tmp/tmpmfvqqaaz_milvus_demo.db.sock, illegal connection params or server unavailable)>

**Comment by junjiejiangjjj** [comment]
hi @lonngxiang , what system are you using?  Milvus Lite currently supports the following environmnets:

Ubuntu >= 20.04 (x86_64 and arm64)
MacOS >= 11.0 (Apple Silicon M1/M2 and x86_64)

**Comment by lonngxiang** [comment]
> hi @lonngxiang , what system are you using? Milvus Lite currently supports the following environmnets:
> 
> Ubuntu >= 20.04 (x86_64 and arm64) MacOS >= 11.0 (Apple Silicon M1/M2 and x86_64)

centos is not support too?

**Comment by junjiejiangjjj** [comment]
> > hi @lonngxiang , what system are you using? Milvus Lite currently supports the following environmnets:
> > Ubuntu >= 20.04 (x86_64 and arm64) MacOS >= 11.0 (Apple Silicon M1/M2 and x86_64)
> 
> centos is not support too?

It has not been tested on CentOS. Currently, it is confirmed that CentOS 7 and earlier versions do not support it.

**Comment by lonngxiang** [comment]
> > > hi @lonngxiang , what system are you using? Milvus Lite currently supports the following environmnets:
> > > Ubuntu >= 20.04 (x86_64 and arm64) MacOS >= 11.0 (Apple Silicon M1/M2 and x86_64)
> > 
> > 
> > centos is not support too?
> 
> It has not been tested on CentOS. Currently, it is confirmed that CentOS 7 and earlier versions do not support it.

if use docker version then all platform can supoort?

**Comment by junjiejiangjjj** [comment]
> > > > hi @lonngxiang , what system are you using? Milvus Lite currently supports the following environmnets:
> > > > Ubuntu >= 20.04 (x86_64 and arm64) MacOS >= 11.0 (Apple Silicon M1/M2 and x86_64)
> > > 
> > > 
> > > centos is not support too?
> > 
> > 
> > It has not been tested on CentOS. Currently, it is confirmed that CentOS 7 and earlier versions do not support it.
> 
> if use docker version then all platform can supoort?

It should be OK to use Ubuntu >= 20.04 in Docker

**Comment by yanliang567** [comment]
close as comments above
