### ISSUE TITLE
[Bug]: flaky test case `test_compact_max_time_interval` in ci

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#36437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-36381/6/pipeline
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-36381/7/pipeline

two ci tests all failed at `test_compact_max_time_interval`

**Comment by zhuwenxing** [comment]
/assign @XuanYang-cn 
PTAL

**Comment by yanliang567** [comment]
@zhuwenxing any updates for this issue? @XuanYang-cn
