### ISSUE TITLE
Server crashed when concurrent insert and flush one collection

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#3644]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
docker image: `registry.zilliz.com/milvus/engine:0.11.0-gpu-centos7-release`
when run insert and flush use locust, the docker container stopped automatically and no useful logs left.
[milvus-20-09-08-11:17-info.log](https://github.com/milvus-io/milvus/files/5185985/milvus-20-09-08-11.17-info.log)
[milvus-20-09-08-11:17-debug.log](https://github.com/milvus-io/milvus/files/5185988/milvus-20-09-08-11.17-debug.log)

**Steps/Code to reproduce behavior**
segment_row_count = 10000
1. create a collection with float_vector field only
2. insert and flush 50000 vectors per time
3. locust run: -u 500 -r20 -step user 40 -step time 2m
`locust -f flush_task.py --step-load
`
```
connection_type = "single"
host = "192.168.1.6"
port = 19530
collection_name = "create_collection_ThreadDao"
dim = 128
segment_row_count = 10000
nb = 50000
m = MilvusClient(host=host, port=port, collection_name=collection_name)
m.clean_db()
m.create_collection(dim, segment_row_count, data_type=DataType.FLOAT_VECTOR, auto_id=True, other_fields=None)
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
entities = m.generate_entities(vectors)


class FlushTask(User):
    wait_time = between(0.001, 0.002)
    if connection_type == "single":
        client = MilvusTask(m=m)
    else:
        client = MilvusTask(host=host, port=port, collection_name=collection_name)

    @task(1)
    def flush(self):
        self.client.insert(entities)
        self.client.flush(collection_name)
```

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [x] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)
-0.11.0

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by ThreadDao** [comment]
```
import random
from locust import User, task, between
from locust_task import MilvusTask
from client import MilvusClient
from milvus import DataType
```

**Comment by BossZou** [comment]
Cannot reproduced.

**Comment by ThreadDao** [comment]
ubuntu system logs
```
53218 Sep  8 20:17:28 Dao kernel: [102280.561111] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=f73ac17815cf476ec48ae84a7afc3e9cb54825ae0f583bfcae184b394be3f4d4,mems_allowed=0,global_oom,task_memcg=/docker/f73ac17815cf476ec48ae84a7afc3e9cb54825ae0f583bfcae184b394be3f4d4,task=      milvus_server,pid=6697,uid=0
53219 Sep  8 20:17:28 Dao kernel: [102280.561178] Out of memory: Killed process 6697 (milvus_server) total-vm:64356980kB, anon-rss:55270776kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:112972kB oom_score_adj:0

```

**Comment by BossZou** [comment]
> ubuntu system logs
> 
> ```
> 53218 Sep  8 20:17:28 Dao kernel: [102280.561111] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=f73ac17815cf476ec48ae84a7afc3e9cb54825ae0f583bfcae184b394be3f4d4,mems_allowed=0,global_oom,task_memcg=/docker/f73ac17815cf476ec48ae84a7afc3e9cb54825ae0f583bfcae184b394be3f4d4,task=      milvus_server,pid=6697,uid=0
> 53219 Sep  8 20:17:28 Dao kernel: [102280.561178] Out of memory: Killed process 6697 (milvus_server) total-vm:64356980kB, anon-rss:55270776kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:112972kB oom_score_adj:0
> ```

I think this is a memory oom problem.

**Comment by BossZou** [comment]
@ThreadDao , need to regerssion.
