### ISSUE TITLE
proxy node  错误日志：reason="collection not found

### ISSUE THREAD

**Issue by 1292253144** [milvus-io/milvus#36474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4.1
```

### Current Behavior

使用 alias进行search 报错 ：search/query channel failed, node not available
[error.log](https://github.com/user-attachments/files/17111510/error.log)

**Comment by yanliang567** [comment]
@1292253144 do you mean it is successful if searching with collection name, while fails if using collection alias? could you please share your reproduce code and milvus logs?

/assign @1292253144 
please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation.
For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.

**Comment by 1292253144** [comment]
[error="failed to search: failed to get delegator 103 for channel by-dev-rootcoord-dml_9_4521319
67248875912v1: can not find client of node 103"] [errorVerbose="failed to search: failed to get delegator 103 for channel by-dev-rootc
oord-dml_9_452131967248875912v1: can not find client of node 103

**Comment by xiaofan-luan** [comment]
Could you share the code of how u use alias?

**Comment by xiaofan-luan** [comment]
seems that there is collection not found error here

**Comment by 1292253144** [comment]
1. Create an alias aa and bind it to collection 1
2. Add collection 2
3. Bind alias aa to collection 2 for query

**Comment by xiaofan-luan** [comment]
@yanliang567 
could we test on this?

@1292253144 
so basically 


client.create_alias(
    collection_name="collection1",
    alias="test"
)

client.create_collection(
    collection_name="collection2",
    dimension=100
)

client.alter_alias(
    collection_name="collection2",
    alias="test"
)

**Comment by yanliang567** [comment]
actually, we have ci/e2e test for this case. @1292253144 could you please share some code snippets to reproduce this issue?
