### ISSUE TITLE
[Bug]: Querynode can't comunicate with GCS cloud 

### ISSUE THREAD

**Issue by Trourest186** [milvus-io/milvus#36517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.4.1
- Deployment mode(standalone or cluster): Cluster
- MQ type(rocksmq, pulsar or kafka):  Kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Query node can't comunicate with GCS cloud

### Expected Behavior

Querynode have "Running" status

### Steps To Reproduce

```markdown
1. In the GKE, I deployed HelmChart with image version above. With configure:

externalS3:
  enabled: true
  host: "storage.googleapis.com"
  port: "443"
  accessKey: ""
  secretKey: ""
  useSSL: true
  bucketName: "sotabox-milvus"
  rootPath: "milvus/my-release"
  useIAM: false
  cloudProvider: "gcp"
  iamEndpoint: ""
  region: "asia-northeast1"
  useVirtualHost: false
```
```


### Milvus Log

![image](https://github.com/user-attachments/assets/39a08dbb-42db-43f9-8238-e3eee82cf50b)


### Anything else?

Get for all milvus' node
![image](https://github.com/user-attachments/assets/5599bc52-ca75-404a-8f18-60c7d387d6cd)

**Comment by yanliang567** [comment]
@Trourest186 did you follow the instruction here: https://milvus.io/docs/gcp.md? if yes, please attach the log files for milvus pods. please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs
/assign @Trourest186 
/unassign

**Comment by Trourest186** [comment]
> @Trourest186 did you follow the instruction here: https://milvus.io/docs/gcp.md? if yes, please attach the log files for milvus pods. please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs /assign @Trourest186 /unassign

Yes, i have worked based on this ref document. I send you log.tar of me. Hope you support, thanks.

[logs.tar.gz](https://github.com/user-attachments/files/17144182/logs.tar.gz)
