### ISSUE TITLE
[Bug]: grant_privilege method does not work correctly when using db_name parameter

### ISSUE THREAD

**Issue by 553589912** [milvus-io/milvus#36524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4.X last
- Deployment mode(standalone or cluster):standalone docker
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.6
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I try to use client.grant_privilege() with the db_name parameter, the privilege is not granted to the role. The output of client.describe_role() shows an empty privileges list, even though the privilege was supposed to be granted.

For example, when I run the following code:
>>> client.describe_role(role_name='role_test')
{'role': 'role_test', 'privileges': []}
>>>
>>> client.grant_privilege(
...     role_name="role_test",
...     object_type="Collection",
...     privilege="Query",
...     db_name="test",
...     object_name="*"
... )
>>> client.describe_role(role_name='role_test')
{'role': 'role_test', 'privileges': []}
>>>
>>> client.grant_privilege(
...     role_name="role_test",
...     object_type="Collection",
...     privilege="Query",
...     object_name="*"
... )
>>> client.describe_role(role_name='role_test')
{'role': 'role_test', 'privileges': [{'object_type': 'Collection', 'object_name': '*', 'db_name': 'default', 'role_name': 'role_test', 'privilege': 'Query', 'grantor_name': 'root'}]}

**Comment by SimFG** [comment]
you can try:
```
client.describe_role(role_name='role_test', db_name='test')
```

**Comment by yanliang567** [comment]
also please share the code snippet how you call grant privilege method. @553589912 
/assign @553589912 
/unassign

**Comment by 553589912** [comment]
> 还请分享如何调用授予特权方法的代码片段。@553589912 /分配@553589912 /取消分配
您说的是这个吗？ 
.grant_privilege（
... role_name =“role_test”，
... object_type =“Collection”，
... permission =“Query”，
... object_name =“ ”
... ）

**Comment by 553589912** [comment]
> you can try:
> 
> ```
> client.describe_role(role_name='role_test', db_name='test')
> ```

>>> client.describe_role(role_name='role_test', db_name='test')
{'role': 'role_test', 'privileges': [{'object_type': 'Collection', 'object_name': '*', 'db_name': 'test', 'role_name': 'role_test', 'privilege': 'CreateIndex', 'grantor_name': 'root'}, {'object_type': 'Collection', 'object_name': '*', 'db_name': 'test', 'role_name': 'role_test', 'privilege': 'Insert', 'grantor_name': 'root'}, {'object_type': 'Collection', 'object_name': '*', 'db_name': 'test', 'role_name': 'role_test', 'privilege': 'Query', 'grantor_name': 'root'}, {'object_type': 'Global', 'object_name': '*', 'db_name': 'test', 'role_name': 'role_test', 'privilege': 'All', 'grantor_name': 'root'}]}

"Yes, that works! Thank you for the guidance."  However, it might be beneficial to enhance the user experience regarding this return.

**Comment by SimFG** [comment]
This is because when accessing, if you do not specify a db, you access the resources under the default db. Different dbs cannot access each other.

**Comment by 553589912** [comment]
> This is because when accessing, if you do not specify a db, you access the resources under the default db. Different dbs cannot access each other.

>>> from pymilvus import MilvusClient,Role,connections
>>>
>>>
>>> client = MilvusClient(
...     uri='http://localhost:19530', # replace with your own Milvus server address
...     token="root:xx_dba"
... )
>>>
>>> conn = connections.connect(host="127.0.0.1", port=19530,token="root:xx_dba",db_name="test")
>>>
>>> client.create_role(role_name="role_test03",)
>>> client.grant_privilege(
...     role_name='role_test03',
...     object_type='Collection',
...     privilege='Insert',
...     object_name='*',
...     db_name='test'
... )
>>>
>>> client.describe_role(role_name='role_test03')
{'role': 'role_test03', 'privileges': []}
>>> client.grant_privilege(
...     role_name='role_test03',
...     object_type='Collection',
...     privilege='Insert',
...     object_name=["role_test03"],
...     db_name='test'
... )

I specified db_name='test' when creating the connection, but executing client.describe_role(role_name='role_test03') still does not show any results. It seems that the specified database name during the connection setup does not take effect.
