### ISSUE TITLE
[Feature]: Implement custom function module in milvus expr

### ISSUE THREAD

**Issue by jiangyinzuo** [milvus-io/milvus#36559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

OSPP 2024 project: https://summer-ospp.ac.cn/org/prodetail/247410235?list=org&navpage=org

@zhagnlu 

At present, the milvus scalar query system has implemented some operator support and has implemented an extensible system framework, but for developers,

If you want to easily and dynamically extend your own defined operators, avoid redundant operator definitions, etc., and still lack a custom operator basic component,

This component mainly implements the registration and query functions for operator functions, and is integrated with the front-end Plan definition. Based on this component, developers can quickly E2E develop operators. This project mainly implements this basic component and extends some operators on it.

### Describe the solution you'd like.

- add CallExpr in planparserv2, plan.proto, `core/src/exec`
- add a global function factory
- implement some custom functions

**Comment by xiaofan-luan** [comment]
@jiangyinzuo 
is there a document on how user can implement their own functions?

**Comment by jiangyinzuo** [comment]
> @jiangyinzuo 
> is there a document on how user can implement their own functions?

I have written a document in Chinese. I would translate it into English and push the English doc to this repo if needed.

**Comment by xiaofan-luan** [comment]
> > @jiangyinzuo
> > is there a document on how user can implement their own functions?
> 
> I have written a document in Chinese. I would translate it into English and push the English doc to this repo if needed.

Simply use llm to translate at send it to the document team
