### ISSUE TITLE
[Bug]: [Security]store Kafka crendential in config map

### ISSUE THREAD

**Issue by Ice-YcY** [milvus-io/milvus#36551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4.9
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):kafka
- SDK version(e.g. pymilvus v2.0.0rc2):2.4.0
- OS(Ubuntu or CentOS): Ubuntu 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

store Kafka crendential in config map

### Expected Behavior

store Kafka crendential in secret

**Comment by yanliang567** [comment]
/assign @xiaofan-luan 
please help to take a look

**Comment by xiaofan-luan** [comment]
@Ice-YcY do you want to take this?

**Comment by xiaofan-luan** [comment]
@jaime0815 
could you take a look at it?
