### ISSUE TITLE
Manual compaction is skipped on the collection without indexes

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#36576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master/2.4
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Manual compaction is skipped if the collection does not create an index

### Expected Behavior

Force compaction can be performed on the collection without indexes.

**Comment by xiaofan-luan** [comment]
the rule is milvus won't allow to compact on segment without index.
Why will we need this?

**Comment by xiaofan-luan** [comment]
I guess this may block many rule like gc

**Comment by jaime0815** [comment]
> the rule is milvus won't allow to compact on segment without index. Why will we need this?

Generally, the process for writing to and reading from Milvus involves the following steps:

1. Create a collection.
2. Create an index.
3. Insert data.
4. Query or search.

When an insert operation occurs after creating an index, it can result in the creation of many small segments. These segments are then indexed, and as they eventually compact into larger segments, the index on the larger segments needs to be rebuilt. This process can waste significant compute resources due to the need for compaction and re-indexing.

To avoid this issue, we aim to insert and compact data before indexing; however, this approach is not currently supported in Milvus.

**Comment by jaime0815** [comment]
There is also a problem that manual compaction does not respond when the collection has no indexes currently, which will lead to user confusion.
