### ISSUE TITLE
When get entity by deleted id, Null should be returned instead of not return

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#3659]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
@Test(dataProvider = "Collection", dataProviderClass = MainClass.class)
    public void testGetEntityByIdAfterDelete(MilvusClient client, String collectionName) {
        InsertParam insertParam = new InsertParam.Builder(collectionName).withFields(Constants.defaultEntities).build();
        InsertResponse resInsert = client.insert(insertParam);
        List<Long> ids = resInsert.getEntityIds();
        Response res_delete = client.deleteEntityByID(collectionName, Collections.singletonList(ids.get(1)));
        assert(res_delete.ok());
        client.flush(collectionName);
        List<Long> getIds = ids.subList(0,2);
        GetEntityByIDResponse res = client.getEntityByID(collectionName, getIds);
        assert (res.getResponse().ok());
        List<Map<String, Object>> fieldsMap = res.getFieldsMap();
        Assert.assertEquals(fieldsMap.size(), getIds.size());
        Assert.assertEquals(fieldsMap.get(0).get("float_vector"), Constants.vectors.get(0));
        Assert.assertNull(res.getFieldsMap().get(1));
    }
```
**Steps/Code to reproduce behavior**

1. insert nb=8000 entities and get entities ids
2. delete entity ids[1]
3. get entities ids [0,1]

**Expected behavior**
the size of returned fieldsMap should equal get_ids, the entity deleted should be Null

**Method of installation**
- [ ] Docker/cpu
- [x] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
-0.11.0 java-sdk

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by sahuang** [comment]
Please check for update.
