### ISSUE TITLE
[Bug]: All queryNodes oomkilled and L0 Compaction failed after deleting a large number of varchar  pks

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#36614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4-20240928-9a07c1bc-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### server config
**quotaAndLimits.limits.maxOutputSize: 209715200 (200MB)**
```
  config:
    dataCoord:
      enableActiveStandby: true
      segment:
        expansionRate: 1.15
        maxSize: 512
        sealProportion: 0.12
    indexCoord:
      enableActiveStandby: true
    log:
      level: debug
    minio:
      accessKeyID: miniozong
      bucketName: bucket-zong
      rootPath: compact
      secretAccessKey: miniozong
    queryCoord:
      enableActiveStandby: true
    queryNode:
      levelZeroForwardPolicy: RemoteLoad
    quotaAndLimits:
      dml:
        deleteRate:
          max: 0.5
        enabled: false
        insertRate:
          max: 8
        upsertRate:
          max: 8
      growingSegmentsSizeProtection:
        enabled: false
        highWaterLevel: 0.2
        lowWaterLevel: 0.1
      limitWriting:
        memProtection:
          dataNodeMemoryHighWaterLevel: 0.9
          dataNodeMemoryLowWaterLevel: 0.85
          queryNodeMemoryHighWaterLevel: 0.9
          queryNodeMemoryLowWaterLevel: 0.85
      limits:
        complexDeleteLimitEnable: true
        maxOutputSize: 209715200 (200MB)
    rootCoord:
      enableActiveStandby: true
    trace:
      exporter: jaeger
      jaeger:
        url: http://tempo-distributor.tempo:14268/api/traces"
      sampleFraction: 1
```
### test steps:
1. delete 100m entities by complex expr ` "id != '' " ` gets error:
```
RPC error: [delete], <MilvusException: (code=65535, message=failed to search/query delegator 123 for channel compact-opt-rate-100m-1-rootcoord-dml_0_452746410398065847v0: rpc error: code = Unavailable desc = error reading from server: EOF)>, <Time:{'RPC start': '2024-09-29 13:00:07.399641', 'RPC error': '2024-09-29 13:00:12.658231'}>
```
2. There are 5 qn, and the memory usage of each qn before the delete is about 55 %. After deleting, all nodes oomkilled and cannot be running
![image](https://github.com/user-attachments/assets/1ac9bb79-d5e0-4f3d-91c6-642d407dfd07)

3. L0 compaction failed
![image](https://github.com/user-attachments/assets/5bebd03d-feb0-482d-969f-498432dcbcda)

### metrics
https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=P1809F7CD0C75ACF3&var-namespace=qa-milvus&var-instance=compact-opt-rate-100m-1&var-collection=All&var-app_name=milvus&from=1727586389000&to=1727589451156

### Steps To Reproduce

```markdown
delete scripts:

def delete_all(_host, _name):
    connections.connect(host=_host)
    c = Collection(name=_name)
    expr = "id != ''"
    log.info(f"num entities before delete: {c.num_entities}")
    count_before = c.query(expr, output_fields=["count(*)"], consistency_level="Strong")
    log.info(f"count(*) before delete: {count_before}")

    log.info(f"start to delete with expr {expr}")
    start = time.time()
    res = c.delete(expr)
    cost = time.time() - start
    log.info(f"delete {res} cost {cost}s")

    count_after = c.query(expr, output_fields=["count(*)"], consistency_level="Strong")
    log.info(f"count(*) after delete: {count_after}")


if __name__ == '__main__':
    host = "10.104.21.xx"
    name = "fouram_rf7If1S0"
    delete_all(host, name)
```
```


### Milvus Log

pods:
```
compact-opt-rate-100m-1-etcd-0                                    1/1     Running            0                 18d     10.104.34.182   4am-node37   <none>           <none>
compact-opt-rate-100m-1-etcd-1                                    1/1     Running            0                 18d     10.104.21.2     4am-node24   <none>           <none>
compact-opt-rate-100m-1-etcd-2                                    1/1     Running            0                 18d     10.104.32.142   4am-node39   <none>           <none>
compact-opt-rate-100m-1-milvus-datanode-6b474b5fd7-dkjkt          1/1     Running            0                 25h     10.104.6.81     4am-node13   <none>           <none>
compact-opt-rate-100m-1-milvus-indexnode-7ddc848744-6ksjl         1/1     Running            0                 25h     10.104.1.207    4am-node10   <none>           <none>
compact-opt-rate-100m-1-milvus-indexnode-7ddc848744-7x48x         1/1     Running            0                 25h     10.104.4.62     4am-node11   <none>           <none>
compact-opt-rate-100m-1-milvus-indexnode-7ddc848744-cdv5w         1/1     Running            0                 25h     10.104.6.80     4am-node13   <none>           <none>
compact-opt-rate-100m-1-milvus-mixcoord-5c8dc5cc66-drt5b          1/1     Running            0                 25h     10.104.32.168   4am-node39   <none>           <none>
compact-opt-rate-100m-1-milvus-proxy-6d7bcddcbd-gzsqw             1/1     Running            0                 25h     10.104.21.141   4am-node24   <none>           <none>
compact-opt-rate-100m-1-milvus-querynode-1-d4d7c6f67-74cc9        0/1     CrashLoopBackOff   220 (3m32s ago)   25h     10.104.13.155   4am-node16   <none>           <none>
compact-opt-rate-100m-1-milvus-querynode-1-d4d7c6f67-g54qd        0/1     CrashLoopBackOff   221 (2m18s ago)   22h     10.104.4.84     4am-node11   <none>           <none>
compact-opt-rate-100m-1-milvus-querynode-1-d4d7c6f67-jnzdh        0/1     CrashLoopBackOff   223 (66s ago)     25h     10.104.32.186   4am-node39   <none>           <none>
compact-opt-rate-100m-1-milvus-querynode-1-d4d7c6f67-nddkx        0/1     CrashLoopBackOff   226 (4m46s ago)   25h     10.104.1.209    4am-node10   <none>           <none>
compact-opt-rate-100m-1-milvus-querynode-1-d4d7c6f67-nw9hm        1/1     Running            219 (6m ago)      25h     10.104.5.252    4am-node12   <none>           <none>
compact-opt-rate-100m-1-pulsar-bookie-0                           1/1     Running            0                 18d     10.104.32.141   4am-node39   <none>           <none>
compact-opt-rate-100m-1-pulsar-bookie-1                           1/1     Running            0                 18d     10.104.15.12    4am-node20   <none>           <none>
compact-opt-rate-100m-1-pulsar-bookie-2                           1/1     Running            0                 18d     10.104.34.188   4am-node37   <none>           <none>
compact-opt-rate-100m-1-pulsar-broker-0                           1/1     Running            0                 25h     10.104.13.138   4am-node16   <none>           <none>
compact-opt-rate-100m-1-pulsar-proxy-0                            1/1     Running            0                 25h     10.104.13.137   4am-node16   <none>           <none>
compact-opt-rate-100m-1-pulsar-recovery-0                         1/1     Running            0                 18d     10.104.5.222    4am-node12   <none>           <none>
compact-opt-rate-100m-1-pulsar-zookeeper-0                        1/1     Running            0                 18d     10.104.32.139   4am-node39   <none>           <none>
compact-opt-rate-100m-1-pulsar-zookeeper-1                        1/1     Running            0                 18d     10.104.23.68    4am-node27   <none>           <none>
compact-opt-rate-100m-1-pulsar-zookeeper-2                        1/1     Running            0                 18d     10.104.16.247   4am-node21   <none>           <none>
```

### Anything else?

_No response_

**Comment by XuanYang-cn** [comment]
No L0Compaction problems should be fixed

**Comment by XuanYang-cn** [comment]
/assign @ThreadDao 
/unassign @tedxu @XuanYang-cn 
Should be fixed, plz help verify

**Comment by ThreadDao** [comment]
fixed
