### ISSUE TITLE
[Bug]: Catastropic Data Loss (Again)

### ISSUE THREAD

**Issue by Karlusk** [milvus-io/milvus#36648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4.4gpu
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Windows Docker Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I shut down my docker, restarted the workstation and restarted docker.
I think restarted my milvus stack (milvus, etcd, minio)
I use attu to go look at my collections and its 0 collections

When I go into minio, its got an empty a bucket that was just made

I have done literally nothing other than shut down and restart the machine.

### Milvus Log

Here is the important line from etcd

2024-10-04 14:39:33 {"level":"info","ts":"2024-10-04T18:39:33.273Z","caller":"embed/etcd.go:306","msg":"starting an etcd server","etcd-version":"3.5.5","git-sha":"19002cfc6","go-version":"go1.16.15","go-os":"linux","go-arch":"amd64","max-cpu-set":20,"max-cpu-available":20,"member-initialized":false,"name":"default","data-dir":"/etcd","wal-dir":"","wal-dir-dedicated":"","member-dir":"/etcd/member","force-new-cluster":false,"heartbeat-interval":"100ms","election-timeout":"1s","initial-election-tick-advance":true,"snapshot-count":50000,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["http://localhost:2380"],"listen-peer-urls":["http://localhost:2380"],"advertise-client-urls":["http://127.0.0.1:2379"],"listen-client-urls":["http://0.0.0.0:2379"],"listen-metrics-urls":[],"cors":["*"],"host-whitelist":["*"],"initial-cluster":"default=http://localhost:2380","initial-cluster-state":"new","initial-cluster-token":"etcd-cluster","quota-backend-bytes":4294967296,"max-request-bytes":1572864,"max-concurrent-streams":4294967295,"pre-vote":true,"initial-corrupt-check":false,"corrupt-check-time-interval":"0s","compact-check-time-enabled":false,"compact-check-time-interval":"1m0s","auto-compaction-mode":"revision","auto-compaction-retention":"1µs","auto-compaction-interval":"1µs","discovery-url":"","discovery-proxy":"","downgrade-check-interval":"5s"}
2024-10-04 14:39:33 {"level":"warn","ts":1728067173.2742214,"caller":"fileutil/fileutil.go:57","msg":"check file permission","error":"directory \"/etcd\" exist, but the permission is \"drwxr-xr-x\". The recommended permission is \"-rwx------\" to prevent possible unprivileged access to the data"}

### Anything else?

Second time this has happened. I'm not sure if I am the only one experiencing this, but I cant keep losing my milvus data.

**Comment by Karlusk** [comment]
Ok, its being triggered by reboot. Even if I do a clean shutdown in docker, when I restart and bring up docker and start milvus, it starts over and my data is gone. I have no idea what is causing this. The logs are there, so I know my container is the same one, but beyond that, I am baffled.

**Comment by Karlusk** [comment]
I uninstalled Docker Desktop, nuked the directories, reinstalled and now milvus collections can survive reboot. Have no idea what was happening. We can close this ticket.

**Comment by xiaofan-luan** [comment]
> I uninstalled Docker Desktop, nuked the directories, reinstalled and now milvus collections can survive reboot. Have no idea what was happening. We can close this ticket.

Hi @Karlusk 
How did you setup your persistent volume? 
Which deployment docuemnt you are refering to? 

https://milvus.io/docs/install_standalone-docker-compose.md

refer to this document and if you want to reuse the data don't do  sudo rm -rf volumes.
volumes is where you data persists

**Comment by billsenxu** [comment]
I encountered the same case, just stop milvus and restart the server, all collections were gone. The Milvus version is 2.4.13, OS is Ubuntu 22.04

**Comment by xiaofan-luan** [comment]
> > @billsenxu quick questions
> > 
> > 1. how did you deploy milvus, how did you configure your persistent volume for mivlus? did you change any other configurations when deploying milvus?
> > 2. how did you stop and restart the server? can you check the milvus-related files in the persistent volume?
> 
> 1. No change, just deployed with default docker-compose option;
> 2. Before restart, docker compose down, then shut down OS and start later after the resource expansion;
>    The detailed process: the disk was found full, per check the swap occupied the full disk. To address this issue,  docker compose down, then shut down OS, the disk was expanded with additional 10G space and the memory was expanded to 128GB, then check the data with Attu and in the application side, all data gone, forgot to check the persistent volumes. Just checked, the disk is full again. Don't know if this is the root cause, will observe/check further.
> 
> Appreciate if you could give insights or tips for addressing the full-swap issue and measures preventing from data loss. @yanliang567. Thanks a lot.

Whcih directory are u using? Are u sure you mount it to persistent disk instead of temp fs?

**Comment by xiaofan-luan** [comment]
milvus does use swap unless you enabeld mmap. 
So guess your deployment is using some temporay fs eat up your swap memory

**Comment by billsenxu** [comment]
> > > @billsenxu quick questions
> > > 
> > > 1. how did you deploy milvus, how did you configure your persistent volume for mivlus? did you change any other configurations when deploying milvus?
> > > 2. how did you stop and restart the server? can you check the milvus-related files in the persistent volume?
> > 
> > 
> > 
> > 1. No change, just deployed with default docker-compose option;
> > 2. Before restart, docker compose down, then shut down OS and start later after the resource expansion;
> >    The detailed process: the disk was found full, per check the swap occupied the full disk. To address this issue,  docker compose down, then shut down OS, the disk was expanded with additional 10G space and the memory was expanded to 128GB, then check the data with Attu and in the application side, all data gone, forgot to check the persistent volumes. Just checked, the disk is full again. Don't know if this is the root cause, will observe/check further.
> > 
> > Appreciate if you could give insights or tips for addressing the full-swap issue and measures preventing from data loss. @yanliang567. Thanks a lot.
> 
> Whcih directory are u using? Are u sure you mount it to persistent disk instead of temp fs?

Just use the default setting of docker-compose.yml, here in my case is a big PCIE SSD attached.

**Comment by billsenxu** [comment]
> milvus does use swap unless you enabeld mmap. So guess your deployment is using some temporay fs eat up your swap memory

Sorry for misinformation of swap matter/concern. Per further check, it's the issue of one container who grows very rapidly on the og(/var/lib/docker/containers/29b706b4e8b8eea70226ad9b2b702c931ffe206c29e0856062278efd0085eaff), see below info:
-rw-r-----  1 root root  41G Dec 17 15:14 29b706b4e8b8eea70226ad9b2b702c931ffe206c29e0856062278efd0085eaff-json.log

Actually the volumes size is just 1+ GB only:
1.7G    volumes/

Only 4 dockers are running:
CONTAINER ID   IMAGE                                      COMMAND                  CREATED       STATUS                 PORTS                                                                                      NAMES
8b8e991b7444   zilliz/attu:v2.4                           "docker-entrypoint.s…"   2 weeks ago   Up 2 weeks             0.0.0.0:8000->3000/tcp, :::8000->3000/tcp                                                  gallant_brown
29b706b4e8b8   milvusdb/milvus:v2.4.13                    "/tini -- milvus run…"   2 weeks ago   Up 2 weeks (healthy)   0.0.0.0:9091->9091/tcp, :::9091->9091/tcp, 0.0.0.0:19530->19530/tcp, :::19530->19530/tcp   milvus-standalone
c1669b565504   minio/minio:RELEASE.2023-03-20T20-16-18Z   "/usr/bin/docker-ent…"   2 weeks ago   Up 2 weeks (healthy)   0.0.0.0:9000-9001->9000-9001/tcp, :::9000-9001->9000-9001/tcp                              milvus-minio
4d961dde0f12   quay.io/coreos/etcd:v3.5.5                 "etcd -advertise-cli…"   2 weeks ago   Up 2 weeks (healthy)   2379-2380/tcp                                                                              milvus-etcd

For your further advice. @xiaofan-luan Thanks.
