### ISSUE TITLE
Docker exit without any logs

### ISSUE THREAD

**Issue by godchen0212** [milvus-io/milvus#3668]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Docker exit without any logs.

**Steps/Code to reproduce behavior**
Run docker with the scripts:

```
docker run --rm --name milvus_master \
    -p 19530:19530 \
    --gpus all\
    --cpus="4" \
    -m 800M \
    milvus:v0.11.0
```

Run pytest with command:
```
for i in {1..1000}; pytest -s -v -x test_search.py::TestSearchBase::test_search_ip_after_index
```

After approximately half an hour, docker exit without any logs.

dmesg logs as follows:
```
[498038.547140] Memory cgroup out of memory: Killed process 14269 (milvus_server) total-vm:6423144kB, anon-rss:801060kB, file-rss:19260kB, shmem-rss:0kB, UID:0 pgtables:6412kB oom_score_adj:0
```

**Expected behavior**
Docker exits and prints logs with oom warning.

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

- Milvus version (master or released version)
0.11.0 developing

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
cache:
  cache_size: 4GB
  insert_buffer_size: 1GB
  preload_collection:
```

**Comment by BossZou** [comment]
I think this issue is like #3644 , which caused by oom.
