### ISSUE TITLE
Doc: Manage Metadata with MySQL

### ISSUE THREAD

**Issue by Bennu-Li** [milvus-io/milvus#3670]
**Please state your issue using the following template and, most importantly, in English.**

**Location of incorrect documentation**
https://milvus.io/cn/docs/v0.10.2/data_manage.md
https://milvus.io/docs/v0.10.2/data_manage.md

**Describe the problems or issues found in the documentation**
Add a semicolon after "create database milvus"

**Suggested fix for documentation**
create database milvus;

**Comment by PahudPlus** [comment]
Issue fixed.
