### ISSUE TITLE
[Bug]: upsert rows when set autoid==true fail

### ISSUE THREAD

**Issue by smellthemoon** [milvus-io/milvus#36710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

raise DataNotMatchException(message=ExceptionsMessage.DataTypeInconsistent) from e
pymilvus.exceptions.DataNotMatchException: <DataNotMatchException: (code=1, message=The Input data type is inconsistent with defined schema, please check it.)>

**Comment by yanliang567** [comment]
which milvus version are you running?

**Comment by smellthemoon** [comment]
> which milvus version are you running?
2.4.10

**Comment by smellthemoon** [comment]
> which milvus version are you running?

2.4.10

**Comment by yanliang567** [comment]
@smellthemoon could you please share the reproduce code or steps, we already had tests for upsert with autoid==true

**Comment by yanliang567** [comment]
@smellthemoon did this fix cp to 2.4 branch?

**Comment by smellthemoon** [comment]
> @smellthemoon did this fix cp to 2.4 branch?

yes, update pymilvus version to 2.4.13 can fix it. the problem will only occurs when upsert by rows.

**Comment by smellthemoon** [comment]
> @smellthemoon could you please share the reproduce code or steps, we already had tests for upsert with autoid==true

import time
import numpy as np
from pymilvus import (
    MilvusClient, DataType
)

dim = 3
collection_name = "hello_milvus"
milvus_client = MilvusClient("http://localhost:19530/")

milvus_client.drop_collection(collection_name)

schema = milvus_client.create_schema(
    auto_id=True,
)

schema.add_field(field_name="id", datatype=DataType.INT64, is_primary=True)
schema.add_field(field_name="vector", datatype=DataType.FLOAT_VECTOR, dim=dim)

index_params = milvus_client.prepare_index_params()
index_params.add_index(field_name = "vector", index_type="IVF_FLAT", metric_type="L2", nlist=10)

milvus_client.create_collection(
    collection_name=collection_name,
    schema=schema,
    index_params=index_params
)
milvus_client.load_collection(collection_name=collection_name)
milvus_client.insert(collection_name=collection_name, data={"vector":[1,2,3]})
milvus_client.insert(collection_name=collection_name, data={"vector":[2,3,4]})
milvus_client.insert(collection_name=collection_name, data={"vector":[3,4,5]})

res = milvus_client.query(collection_name=collection_name, consistency_level="Strong", filter="id > 0")
for r in res:
    print(r)
    milvus_client.upsert(collection_name=collection_name, data={"id": r["id"], "vector": [0.1, 0.1, 0.1]})

res = milvus_client.query(collection_name=collection_name, consistency_level="Strong", filter="id > 0")
for r in res:
    print(r)

**Comment by yanliang567** [comment]
working on test verifivcation and development

**Comment by yanliang567** [comment]
verified on master-20241012-d45e2677-amd64
