### ISSUE TITLE
[Bug]: json['key'] in [] expr failed and oom 

### ISSUE THREAD

**Issue by zhagnlu** [milvus-io/milvus#36718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

 json['key'] in []  for this type expr, when do it maybe failed
for master:
fail to Query on QueryNode 13: worker(13) query failed: Operator::GetOutput failed for [Operator:PhyFilterBitsNode, plan node id: 1901] : Assert "(bitset.size() == need_process_rows_)"  at /home/silverxia/workspace/milvus/internal/core/src/exec/operator/FilterBitsNode.cpp:85

for 2.4:
querynode OOM

**Comment by yanliang567** [comment]
the expected behavior is return empty results, return results with null values(matches the expr), or return an error? @zhagnlu

**Comment by zhagnlu** [comment]
> the expected behavior is return empty results, return results with null values(matches the expr), or return an error? @zhagnlu

no error, only empty result

**Comment by yanliang567** [comment]
verified on master-20241010-b1e678dc
