### ISSUE TITLE
[Bug]: DataNode keeps restarting due to error: failed to serialize merged stats log: shall not serialize zero length statslog list

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#36723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: cardinal-milvus-io-2.4-9a07c1bca9-20240929
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### server
An milvus cluster that has been running for a long time, which has 2 dataNodes and 4 queryNodes

### test steps
1. collection `laion_stable_9` has 100m-768d entities, 
```
{'auto_id': False, 'description': '', 'fields': [{'name': 'id', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float_vector', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 768}}, {'name': 'int64_pk_5b', 'description': '', 'type': <DataType.INT64: 5>, 'is_partition_key': True}, {'name': 'varchar_caption', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 8192}}, {'name': 'varchar_NSFW', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 8192}}, {'name': 'float64_similarity', 'description': '', 'type': <DataType.FLOAT: 10>}, {'name': 'int64_width', 'description': '', 'type': <DataType.INT64: 5>}, {'name': 'int64_height', 'description': '', 'type': <DataType.INT64: 5>}, {'name': 'int64_original_width', 'description': '', 'type': <DataType.INT64: 5>}, {'name': 'int64_original_height', 'description': '', 'type': <DataType.INT64: 5>}, {'name': 'varchar_md5', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 8192}}], 'enable_dynamic_field': True}
```
2. In the previous test, many L0 segments (1.8k) were left behind and there was no time to perform L0 compaction. In addition, queryNode memory was tight.
3. concurrent requests: Flush + load + search + query + upsert
4. dataNode rkeeps restarting with error
![image](https://github.com/user-attachments/assets/d7b0e5d6-6e3f-4653-a814-9f33767c168a)
5. L0 compaction seems to no longer be triggered
![image](https://github.com/user-attachments/assets/974e5ed4-29d2-4799-823f-1ae51977641c)

# links
- argo: [workflow](https://argo-workflows.zilliz.cc/archived-workflows/qa/df6ec24f-43d3-417c-94fd-a0cc891a0d39?nodeId=laion1b-test-cron-1727971980)
- metrics: [metrics](https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=P1809F7CD0C75ACF3&var-namespace=qa-milvus&var-instance=laion1b-test-2&var-collection=All&var-app_name=milvus&from=1727883600000&to=1728315347000)
- Loki logs: [Loki logs](https://grafana-4am.zilliz.cc/explore?panes=%7B%22RYA%22:%7B%22datasource%22:%22vhI6Vw67k%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcluster%3D%5C%224am%5C%22,%20namespace%3D%5C%22qa-milvus%5C%22,%20pod%3D%5C%22laion1b-test-2-milvus-datanode-7b8f94796b-9wb45%5C%22%7D%20%7C%3D%20%5C%22failed%20to%20serialize%20merged%20stats%20log%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22vhI6Vw67k%22%7D,%22editorMode%22:%22code%22,%22hide%22:false%7D,%7B%22refId%22:%22B%22,%22expr%22:%22%7Bcluster%3D%5C%224am%5C%22,%20namespace%3D%5C%22qa-milvus%5C%22,%20pod%3D%5C%22laion1b-test-2-milvus-datanode-7b8f94796b-hrvq2%5C%22%7D%20%7C%3D%20%5C%22failed%20to%20serialize%20merged%20stats%20log%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22vhI6Vw67k%22%7D,%22editorMode%22:%22code%22,%22hide%22:true%7D%5D,%22range%22:%7B%22from%22:%221727970016000%22,%22to%22:%221728316800000%22%7D%7D%7D&schemaVersion=1&orgId=1)
- pod restart reason: [container restart reason](https://grafana-4am.zilliz.cc/explore?panes=%7B%22ZT1%22:%7B%22datasource%22:%22P1809F7CD0C75ACF3%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22kube_pod_container_status_last_terminated_reason%7Bpod%3D~%5C%22laion1b-test-2-.%2A%5C%22%7D%22,%22range%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P1809F7CD0C75ACF3%22%7D,%22editorMode%22:%22code%22,%22legendFormat%22:%22__auto%22%7D%5D,%22range%22:%7B%22from%22:%221727702015684%22,%22to%22:%221728476709372%22%7D%7D%7D&schemaVersion=1&orgId=1)

### Milvus Log

pods:
```
laion1b-test-2-etcd-0                                             1/1     Running     1 (4d23h ago)    38d    10.104.25.207   4am-node30   <none>           <none>
laion1b-test-2-etcd-1                                             1/1     Running     0                97d    10.104.30.186   4am-node38   <none>           <none>
laion1b-test-2-etcd-2                                             1/1     Running     0                299d   10.104.34.225   4am-node37   <none>           <none>
laion1b-test-2-milvus-datanode-7b8f94796b-9wb45                   1/1     Running     95 (11h ago)     10d    10.104.1.226    4am-node10   <none>           <none>
laion1b-test-2-milvus-datanode-7b8f94796b-hrvq2                   1/1     Running     54 (4d12h ago)   10d    10.104.20.103   4am-node22   <none>           <none>
laion1b-test-2-milvus-indexnode-7fc94494bd-cfgkh                  1/1     Running     2 (8d ago)       10d    10.104.19.46    4am-node28   <none>           <none>
laion1b-test-2-milvus-indexnode-7fc94494bd-m7xcf                  1/1     Running     0                10d    10.104.30.115   4am-node38   <none>           <none>
laion1b-test-2-milvus-indexnode-7fc94494bd-mf42d                  1/1     Running     0                10d    10.104.32.231   4am-node39   <none>           <none>
laion1b-test-2-milvus-indexnode-7fc94494bd-q88hf                  1/1     Running     0                10d    10.104.16.70    4am-node21   <none>           <none>
laion1b-test-2-milvus-mixcoord-b484b7777-ggxcn                    1/1     Running     1 (8d ago)       10d    10.104.30.114   4am-node38   <none>           <none>
laion1b-test-2-milvus-proxy-787965c494-kzlrp                      1/1     Running     0                10d    10.104.32.230   4am-node39   <none>           <none>
laion1b-test-2-milvus-querynode-1-7b7568c78b-24wr8                1/1     Running     3 (5d15h ago)    10d    10.104.26.61    4am-node32   <none>           <none>
laion1b-test-2-milvus-querynode-1-7b7568c78b-5wp66                1/1     Running     2 (4d12h ago)    10d    10.104.24.214   4am-node29   <none>           <none>
laion1b-test-2-milvus-querynode-1-7b7568c78b-8gztc                1/1     Running     2 (4d23h ago)    10d    10.104.15.164   4am-node20   <none>           <none>
laion1b-test-2-milvus-querynode-1-7b7568c78b-g8lsb                1/1     Running     3 (4d23h ago)    10d    10.104.27.130   4am-node31   <none>           <none>
laion1b-test-2-pulsar-bookie-0                                    1/1     Running     0                299d   10.104.33.107   4am-node36   <none>           <none>
laion1b-test-2-pulsar-bookie-1                                    1/1     Running     0                102d   10.104.18.97    4am-node25   <none>           <none>
laion1b-test-2-pulsar-bookie-2                                    1/1     Running     0                38d    10.104.25.206   4am-node30   <none>           <none>
laion1b-test-2-pulsar-broker-0                                    1/1     Running     1 (171d ago)     180d   10.104.1.147    4am-node10   <none>           <none>
laion1b-test-2-pulsar-proxy-0                                     1/1     Running     0                168d   10.104.32.209   4am-node39   <none>           <none>
laion1b-test-2-pulsar-recovery-0                                  1/1     Running     1 (168d ago)     200d   10.104.31.87    4am-node34   <none>           <none>
laion1b-test-2-pulsar-zookeeper-0                                 1/1     Running     0                299d   10.104.29.87    4am-node35   <none>           <none>
laion1b-test-2-pulsar-zookeeper-1                                 1/1     Running     0                180d   10.104.21.196   4am-node24   <none>           <none>
laion1b-test-2-pulsar-zookeeper-2                                 1/1     Running     0                299d   10.104.34.229   4am-node37   <none>           <none>
```

**Comment by XuanYang-cn** [comment]
Some segments stay in "Sealed" state, but cp has been advanced. And DataNode failed to flush those sealed segments and keeps panicking itself.

After rebooting DataCoord, those sealed segment becomes flushed, and no panic since.

**Comment by XuanYang-cn** [comment]
![image](https://github.com/user-attachments/assets/73d61592-fa29-4e51-af37-6f2f37550020)

**Comment by ThreadDao** [comment]
hard to find the root cause
