### ISSUE TITLE
After MySQL is configured, Milvus cannot be started.

### ISSUE THREAD

**Issue by 670133189** [milvus-io/milvus#3673]
Error report: **possible reason: out of storage, meta schema is damaged or created by in compatible Milvus version.**

Milvus version: 0.10.2, CPU

**Comment by 670133189** [comment]
mysql version: **mysql  Ver 14.14 Distrib 5.7.31, for Linux (x86_64) using  EditLine wrapper**

**Comment by rosaline1995** [comment]
Same issue here. And I am running on ubuntu 18.04, GPU.
Thanks!

**Comment by Bennu-Li** [comment]
please refer to this link:
https://github.com/milvus-io/milvus/issues/3809#issuecomment-697089405
