### ISSUE TITLE
[Bug]:  Attu Error: Milvus is not ready yet

### ISSUE THREAD

**Issue by yesyue** [milvus-io/milvus#36744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.11
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 16/128
- GPU:  
- Others:
```

### Current Behavior

the cluster is no run normal ， the collection no load success to the querynode

### Steps To Reproduce

```markdown
1、create some new collection 
2、Import data to those collection
3、load to memory
4、error happend : only little collection loaded , error
```

### Milvus Log

[llm-paas-milvus02-logs.tar.gz](https://github.com/user-attachments/files/17325520/llm-paas-milvus02-logs.tar.gz)

**Comment by yesyue** [comment]
Have you found the reason ?? /assign @yanliang567

**Comment by yanliang567** [comment]
/assign @shaoting-huang 
could you please hlep to take a look?
