### ISSUE TITLE
[Bug]: how to disable collection loading when execute bash standalone_embed.sh start？

### ISSUE THREAD

**Issue by kksasa** [milvus-io/milvus#36757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4.6
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Milvus cannot start with loading data, but if remove data can work.Doubt data was broken, so how to disable collection loading when start milvus?

**Comment by liliu-z** [comment]
Check https://github.com/milvus-io/milvus/discussions/36756
