### ISSUE TITLE
[Bug]: Milvus connection exception etcd, generate coredump.

### ISSUE THREAD

**Issue by zhoujiaqi1998** [milvus-io/milvus#36774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4.12
- Deployment mode(standalone or cluster):standalone and cluster
- MQ type(rocksmq, pulsar or kafka):    rocksmq and pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

[coredump.zip](https://github.com/user-attachments/files/17340393/coredump.zip)
![图片](https://github.com/user-attachments/assets/3ca3bc80-34c7-4d20-922a-4b25a2967332)

### Steps To Reproduce

```markdown
Create a new milvus and configure non-existent etcd.
```

### Milvus Log

[milvus.log](https://github.com/user-attachments/files/17340422/milvus.log)

**Comment by xiaofan-luan** [comment]
this is expected.
Milvus can not serve with etcd. On other word, etcd is strong dependency for milvus

**Comment by zhoujiaqi1998** [comment]
The program can exit, but I think generating a core dump is abnormal.
@xiaofan-luan
