### ISSUE TITLE
[Bug]: [CI] The query iterator ended unexpectedly after fetching a batch of results

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#36787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): 2.5.0rc88
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-36768/1/pipeline

1. insert 2000 entities
2. query iterator with expr: `int64 >= 0`, offset 500, batch_size 777
3. expected to fetch 2000 - 500 entities with batch 777, but only first batch 777 entities returned

**I guess it's a problem with pymilvus 2.5.0rc88**

**Comment by NicoYuan1986** [comment]
same error: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-36764/2/pipeline/106

expect 1500 results, only 200 returned. (batch_size=100)

**Comment by ThreadDao** [comment]
updrade pymilvus to 2.5.0rc92+
