### ISSUE TITLE
[Enhancement]: ZenAudit Integration for Milvus Access Logging

### ISSUE THREAD

**Issue by Jeri-jose** [milvus-io/milvus#36828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

This enhancement proposes the integration of ZenAudit functionality into Milvus' access logging system using a plugin-based approach. The ZenAudit plugin will provide a modular, easily configurable way to enhance Milvus' audit logging capabilities. This plugin approach allows for a more robust and centralized way to handle audit logs, improving observability and compliance capabilities while maintaining flexibility and minimizing impact on the core Milvus functionality.

### Why is this needed?

- Enhance Milvus' audit logging capabilities through a modular plugin system
- Centralize audit logs for easier analysis and management
- Improve compliance with various data regulations
- Provide more detailed and structured audit information
- Allow easy enabling/disabling of advanced audit logging features

**Comment by xiaofan-luan** [comment]
Hi @Jeri-jose 
are you willing to offer a pr for the intergation?

**Comment by Jeri-jose** [comment]
Hi @xiaofan-luan 
yes
