### ISSUE TITLE
[Bug]: Invalid trace stack for exception of type: raft::cuda_error

### ISSUE THREAD

**Issue by HWZhang1234** [milvus-io/milvus#36836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4.6
- Deployment mode(standalone or cluster):standalone 
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

bash standalone_embed.sh start fail

### Expected Behavior

bash standalone_embed.sh start successful

### Steps To Reproduce

```markdown
bash standalone_embed.sh start
fail
```

### Milvus Log

[milvus.log](https://github.com/user-attachments/files/17359201/milvus.log)

### Anything else?

No

**Comment by xiaofan-luan** [comment]
1. u have to use GPU image
2. check the command offered in https://github.com/milvus-io/milvus/issues/36355

**Comment by PwzXxm** [comment]
> /assign @PwzXxm Could you help to check the initialization of cpp tracer?

It seems not related to cpp tracer, rather settings related to raft. Please check the comments as @xiaofan-luan said, if the problem consistent, please let us know and we will take a closer look. Cheers.

**Comment by HWZhang1234** [comment]
I have used GPU images.And it can start normally before.Not sure what happened now that can't start.
whui-gv{75}> nvidia-smi
Mon Oct 14 15:36:43 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.78                 Driver Version: 550.78         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3090        Off |   00000000:17:00.0 Off |                  N/A |
| 35%   46C    P8             23W /  370W |    2631MiB /  24576MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

**Comment by HWZhang1234** [comment]
I also download 2.4.23 and report same issue.
[milvus_2_4_13.log](https://github.com/user-attachments/files/17362605/milvus_2_4_13.log)
[error.txt](https://github.com/user-attachments/files/17362608/error.txt)

**Comment by HWZhang1234** [comment]
I think the root cause is below.What shoul I do.
W20241014 10:21:25.296236    56 ExceptionTracer.cpp:187] Invalid trace stack for exception of type: raft::cuda_error
terminate called after throwing an instance of 'raft::cuda_error'
  what():  CUDA error encountered at: file=/workspace/source/cmake_build/thirdparty/knowhere/knowhere-src/src/common/raft/integration/raft_initialization.cc line=53: call='cudaGetDeviceCount(&result)', Reason=**_cudaErrorInsufficientDriver:CUDA driver version is insufficient for CUDA runtime version
Obtained 6 stack frames_**

**Comment by Presburger** [comment]
@HWZhang1234 Hello, is the Milvus GPU binary version you are using manually compiled by you, or are you using the container version we provided?

**Comment by Presburger** [comment]
This issue appears to be caused by using a newer CUDA runtime to build Milvus, while the driver version is incompatible with that CUDA runtime version.

**Comment by HWZhang1234** [comment]
Hi @Presburger I am using the container version you provided.I also update NV driver and CUDA.But it also doesn't work.Is there any suggestions.
Before:| NVIDIA-SMI 550.78 Driver Version: 550.78 CUDA Version: 12.4 |
Now:NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6

**Comment by HWZhang1234** [comment]
I fix this issue by start with docker compose
