### ISSUE TITLE
some of Prometheus APIs seems useless

### ISSUE THREAD

**Issue by cydrain** [milvus-io/milvus#3685]
**Please state your issue using the following template and, most importantly, in English.**

**What would you like to be added ?**
need check Prometheus APIs, remove useless ones.
such as:
AddVectorsPerSecondGaugeSet()
QueryIndexTypePerSecondSet()

following APIs can be merged into one:
ConnectionGaugeIncrement()
ConnectionGaugeDecrement()

**Why is this needed ?**
make code clean

**Comment by scsven** [comment]
Done
