### ISSUE TITLE
[Bug]: panic: runtime error: slice bounds out of range [1:0]

### ISSUE THREAD

**Issue by 1292253144** [milvus-io/milvus#36867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.0
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):  pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Proxy log error: panic: runtime error: slice bounds out of range [1:0]. Node restart
What is the reason for this

### Milvus Log

[2024/10/13 09:00:51.689 +00:00] [INFO] [proxy/meta_cache.go:904] ["expire all shard leader cache"] [database=default] [collections="[base_quality_bge_negative_partition]"]
[2024/10/13 09:00:59.246 +00:00] [INFO] [proxy/meta_cache.go:790] ["no shard cache for collection, try to get shard leaders from QueryCoord"] [traceID=e8e3be8d4b876f9648ba498dbefeaec3] [collectionName=base_quality_bge_negative_partition] [collectionID=444794842163586393]
panic: runtime error: slice bounds out of range [1:0]

goroutine 2066914 [running]:
panic({0x3dab720, 0xc001af0f48})
   /usr/local/go/src/runtime/panic.go:987 +0x3bb fp=0xc001f7ca88 sp=0xc001f7c9c8 pc=0x153fbdb
runtime.goPanicSliceB(0x1, 0x0)
   /usr/local/go/src/runtime/panic.go:153 +0x7f fp=0xc001f7cac8 sp=0xc001f7ca88 pc=0x153dcdf
github.com/milvus-io/milvus/internal/parser/planparserv2.(*ParserVisitor).VisitString(0x44f9740?, 0x44b5390?)
/go/src/github.com/milvus-io/milvus/internal/parser/planparserv2/parser_visitor.go:135 +0x25f fp=0xc001f7cb50
 sp=0xc001f7cac8 pc=0x334b6bf
github.com/milvus-io/milvus/internal/parser/planparserv2/generated.(*StringContext).Accept(0xc001c38e58?, {0x44b
5390?, 0xc001c43b40})
   /go/src/github.com/milvus-io/milvus/internal/parser/planparserv2/generated/plan_parser.go:321 +0x9d fp=0xc001
f7cb98 sp=0xc001f7cb50 pc=0x32d98bd
 github.com/milvus-io/milvus/internal/parser/planparserv2.(*ParserVisitor).VisitEquality(0x44f9740?, 0xc001c38e58
)
   /go/src/github.com/milvus-io/milvus/internal/parser/planparserv2/parser_visitor.go:326 +0xc2 fp=0xc001f7cc30
sp=0xc001f7cb98 pc=0x334c8a2
 github.com/milvus-io/milvus/internal/parser/planparserv2/generated.(*EqualityContext).Accept(0xc001d754d0?, {0x4
4b5390?, 0xc001c43b40})
    /go/src/github.com/milvus-io/milvus/internal/parser/planparserv2/generated/plan_parser.go:728 +0x9a fp=0xc001
f7cc78 sp=0xc001f7cc30 pc=0x32dc17a
 github.com/milvus-io/milvus/internal/parser/planparserv2.(*ParserVisitor).VisitLogicalAnd(0xc001c43b40?, 0x44b53
90?)

**Comment by yanliang567** [comment]
@1292253144  please retry on milvus 2.3.22 or 2.4.13. if it reproduced to you, please share the reproduce steps or code , and attach the full milvus logs. 
Please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation.

/assign @1292253144 
/unasssign

**Comment by 1292253144** [comment]
Is this a bug from this version? This can only be resolved through a version upgrade

**Comment by xiaofan-luan** [comment]
2.3.0 is actually back to long time ago, so it's better to try latest 2.3 or 2.4
