### ISSUE TITLE
[Bug]: Can't get more than 16384 entries from a collection. Is that possible?

### ISSUE THREAD

**Issue by vd-omermazig** [milvus-io/milvus#36895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.10
- Deployment mode: docker standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version: 2.4.7
```

### Current Behavior

I get:

`MilvusException: <MilvusException: (code=65535, message=invalid max query result window, (offset+limit) should be in range [1, 16384], but got 20000)>`

### Expected Behavior

Get 20,000 entries

### Steps To Reproduce

```markdown
from pymilvus import Collection, FieldSchema, CollectionSchema, DataType
import random

schema = CollectionSchema([
    FieldSchema("film_id", DataType.INT64, is_primary=True),
    FieldSchema("film_date", DataType.INT64),
    FieldSchema("films", dtype=DataType.FLOAT_VECTOR, dim=2)
])
collection = Collection("test_collection_query", schema)
# insert
data = [
    [i for i in range(100_000)],
    [i + 2000 for i in range(100_000)],
    [[random.random() for _ in range(2)] for _ in range(100_000)],
]
collection.insert(data)
index_param = {"index_type": "FLAT", "metric_type": "L2", "params": {}}
collection.create_index("films", index_param)
collection.load()
# query
expr = "film_id != -1"
res = collection.query(expr, output_fields=["film_date"], offset=0, limit=20000)
assert len(res) == 10000
print(f"- Query results: {res}")
```

### Anything else?

Even if I try to split to several queries (by doing offset=0, limit=20000 in the example), I get the same error.

**Comment by yanliang567** [comment]
@vd-omermazig this is expected to the design for now. please check https://milvus.io/docs/limitations.md#Search-limits.
but I believe we can change this limit with a config item, although this is not recommended.  @yhmo could you please help on this?

/assign @yhmo 
/unassign

**Comment by xiaofan-luan** [comment]
you can use query iterator to get more data.
https://milvus.io/docs/with-iterators.md

**Comment by vd-omermazig** [comment]
@xiaofan-luan That worked! Thank you!

Small suggestion - I wasn't able to find this solution by myself and I've looked for some time in the repos issues and documentation. Maybe you should append to the error message a suggestion to use iterators.

**Comment by sduqlsc** [comment]
> you can use query iterator to get more data. https://milvus.io/docs/with-iterators.md

@xiaofan-luan why no iterator in golang sdk?

**Comment by xiaofan-luan** [comment]
> > you can use query iterator to get more data. https://milvus.io/docs/with-iterators.md
> 
> [@xiaofan-luan](https://github.com/xiaofan-luan) why no iterator in golang sdk?

This is already in latest golang SDK. the document is not ready yets

**Comment by sduqlsc** [comment]
> > > you can use query iterator to get more data. https://milvus.io/docs/with-iterators.md
> > 
> > 
> > [@xiaofan-luan](https://github.com/xiaofan-luan) why no iterator in golang sdk?
> 
> This is already in latest golang SDK. the document is not ready yets

i found searchiterator no queryiterator in sdk 2.6.0

**Comment by xiaofan-luan** [comment]
@congqixia comments?
