### ISSUE TITLE
[Enhancement]: Limit import job number

### ISSUE THREAD

**Issue by bigsheeper** [milvus-io/milvus#36890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Limit import job number to 4096.

**Comment by xiaofan-luan** [comment]
what do we limit this number can keep as many task and we can combine multiple task into one if possible?

**Comment by bigsheeper** [comment]
> what do we limit this number can keep as many task and we can combine multiple task into one if possible?

Only tasks in the pending state can be merged. After introducing pooling, there will be fewer tasks in the pending state, making merging ineffective. 
We can set the limit lower so that users importing single files will easily hit the limit. At that point, the error message can guide and encourage users to perform multi-file imports.
