### ISSUE TITLE
error: python hello_milvus.py(milvus:2.4.6)

### ISSUE THREAD

**Issue by zhangqirui199421** [milvus-io/milvus#36898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):   docker  
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus v2.4.6
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

[Bug]: RPC error: [query], <MilvusException: (code=65535, message=fail to Query on QueryNode 8: worker(8) query failed: getrandom)>, <Time:{'RPC start': '2024-10-16 09:33:15.565184', 'RPC error': '2024-10-16 09:33:16.560900'}> Traceback (most recent call last):   File "/data/zhangqr/find_friends/hello_milvus.py", line 132, in <module>     result = hello_milvus.query(expr="random > 0.5", output_fields=["random", "embeddings"])   File "/opt/anaconda2/envs/py39/lib/python3.9/site-packages/pymilvus/orm/collection.py", line 1076, in query     return conn.query(   File "/opt/anaconda2/envs/py39/lib/python3.9/site-packages/pymilvus/decorators.py", line 148, in handler     raise e from e   File "/opt/anaconda2/envs/py39/lib/python3.9/site-packages/pymilvus/decorators.py", line 144, in handler     return func(*args, **kwargs)   File "/opt/anaconda2/envs/py39/lib/python3.9/site-packages/pymilvus/decorators.py", line 183, in handler     return func(self, *args, **kwargs)   File "/opt/anaconda2/envs/py39/lib/python3.9/site-packages/pymilvus/decorators.py", line 123, in handler     raise e from e   File "/opt/anaconda2/envs/py39/lib/python3.9/site-packages/pymilvus/decorators.py", line 87, in handler     return func(*args, **kwargs)   File "/opt/anaconda2/envs/py39/lib/python3.9/site-packages/pymilvus/client/grpc_handler.py", line 1536, in query     check_status(response.status)   File "/opt/anaconda2/envs/py39/lib/python3.9/site-packages/pymilvus/client/utils.py", line 63, in check_status     raise MilvusException(status.code, status.reason, status.error_code) pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=fail to Query on QueryNode 8: worker(8) query failed: getrandom)>

**Comment by yanliang567** [comment]
@zhangqirui199421 I think your milvus is not running healthy.  Please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation.
For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.

/assign @zhangqirui199421 
/unassign

**Comment by zhangqirui199421** [comment]
ok, thank you
