### ISSUE TITLE
[Bug]: milvus pulsar bookie Uses a lot of memory

### ISSUE THREAD

**Issue by neblen** [milvus-io/milvus#36901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.16
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I wrote tens of millions of data to milvus 2.2.16, and then found that the bookie memory grew to a large size and could not be reduced.
![image](https://github.com/user-attachments/assets/fbbf3e97-71b6-460b-aed6-bcd75621109f)

### Expected Behavior

Bookie memory returns to normal

**Comment by neblen** [comment]
now the milvus cluster is no longer writing data, and all data is stored in milvus. Can I restart bookie? After restarting bookie, the bookie memory should return to normal.

**Comment by yanliang567** [comment]
/assign @LoveEachDay 
any ideas

/unassign
