### ISSUE TITLE
[Bug]: In the milvus cluster, the single table offline_recall_common frequently has query errors. Could you please help me locate the cause?

### ISSUE THREAD

**Issue by TonyAnn** [milvus-io/milvus#36902]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.16
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

[milvus-log.tar.gz](https://github.com/user-attachments/files/17388652/milvus-log.tar.gz)
![649c56c55251bd697330bcea5f2b132](https://github.com/user-attachments/assets/abde233f-745d-4da1-854e-f655af9fa163)

**Comment by xiaofan-luan** [comment]
we need more detailed log from Querynode.
Right now it said not ready to serve

**Comment by yanliang567** [comment]
there are only INFO logs in the attachments, so there is not enough info to analyze the issue. please try to update the log log to debug, and upgrading to latest release is also strongly recommended. 
/assign @TonyAnn 
/unassign
