### ISSUE TITLE
[Bug]: [new_indexes]  The name for new HNSW SQ/PQ/PRQ indexes are "FAISS_HNSW_**" not "HNSW_**"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#36925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20241015-f3b6792a
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    all 
- SDK version(e.g. pymilvus v2.0.0rc2): 2.5.0rc97
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The name for new HNSW SQ/PQ/PRQ indexes are "FAISS_HNSW_**" not "HNSW_**":

FAISS_HNSW_FLAT
FAISS_HNSW_SQ
FAISS_HNSW_PQ
FAISS_HNSW_PRQ

### Expected Behavior

HNSW_FLAT
HNSW_SQ
HNSW_PQ
HNSW_PRQ

### Steps To Reproduce

```markdown
NA
```

**Comment by alexanderguzhva** [comment]
this is temporarily while we finish all checks

**Comment by foxspy** [comment]
@alexanderguzhva Have you tried building index and loading it with FAISS HNSW? If you change the name, you should take care it can successfully load the index built before

**Comment by alexanderguzhva** [comment]
@foxspy that was my first question to @liliu-z  and @xiaofan-luan

**Comment by foxspy** [comment]
track: https://github.com/zilliztech/knowhere/issues/921

**Comment by liliu-z** [comment]
Also we need to support both `HNSW` and `HNSW_FLAT` as the name for this version

**Comment by binbinlv** [comment]
working on verification

**Comment by binbinlv** [comment]
Verified and fixed, all index names are changed.

milvus: master-20241114-1304b405-amd64
pymilvus: 2.5.0rc119
