### ISSUE TITLE
[Bug]: Collection info cannot be recovered from metakv after restart if all snapshots gc-ed

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#36933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: c271c21 & 2.4.13
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Collection info cannot be recovered from metakv after restart if all snapshots gc-ed
if all snapshot are gc-ed, collection info will be missing and system will become abnormal

**Comment by yanliang567** [comment]
data persisted in etcd and minio is safe, so Milvus will automatically recover after upgrading to hotfix-2.4.13.
