### ISSUE TITLE
milvus server 开启metric后 pushgate收不到milvus server的监控数据序列

### ISSUE THREAD

**Issue by joychowchow** [milvus-io/milvus#3693]
操作系统：CentOS Linux release 7.8.2003 (Core)
milvus 版本 V0.10.1 
grafana-7.1.5  
 pushgateway-1.2.0 
prometheus-2.20.1

启动顺序先启动pushgateway 再启动milvus
vim /home/root/milvus/conf/server_config.yaml
metric:
  enable: true
  address: 127.0.0.1
  port: 9091

vim prometheus.yml

global:
  scrape_interval:     2s # Set the scrape interval every 2 seconds. The default is every 1 minute.
  evaluation_interval: 2s # Evaluate rules every 2 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
   - "alert_rules.yml" # add alerting rules

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any time series scraped from this config.
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

   # Allows ephemeral and batch jobs to expose their metrics to Prometheus 
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
    - targets: ['localhost:9091']
#

**Comment by fishpenguin** [comment]
Did you start milvus server in docker? If so, you may need to change the address(127.0.0.1) in metric in server_config.yaml to your native ip started by 192.168.x.x

**Comment by joychowchow** [comment]
it works , thank you!

> Did you start milvus server in docker? If so, you may need to change the address(127.0.0.1) in metric in server_config.yaml to your native ip started by 192.168.x.x
