### ISSUE TITLE
[Bug]: How do I migrate one of my milvus databases offline to another server?

### ISSUE THREAD

**Issue by 0sengseng0** [milvus-io/milvus#37005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.1
- Deployment mode(standalone or cluster):standalone 
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I transferred the volume of the source server, packaged, and offline to the target location of another server.  After restarting the milvus of the target server, the data on the source server could not be smoothly recognized.  Milvus-backup does not seem to be able to transfer milvus data offline to another server.

### Expected Behavior

How do I migrate one of my milvus databases offline to another server?

### Steps To Reproduce

```markdown
How do I migrate one of my milvus databases offline to another server?
```

**Comment by yanliang567** [comment]
@0sengseng0 as you get the backup files with milvus-backup, you can restore them you any other milvus servers. I don't find any other options for now.

/assign @0sengseng0 
/unassign

**Comment by 0sengseng0** [comment]
> @0sengseng0 as you get the backup files with milvus-backup, you can restore them you any other milvus servers. I don't find any other options for now.
> 
> /assign @0sengseng0 /unassign

After I do./milvus-backup create -n bk3. I see that the storage directory of minIO is about 500M, and the storage space of milvus is 5G. This storage gap left me wondering what I should download from the minIO in order to migrate the entire milvus data offline to another server.

**Comment by deep1401** [comment]
@0sengseng0  this might help: https://github.com/zilliztech/milvus-migration

**Comment by xiaofan-luan** [comment]
https://github.com/zilliztech/vts is more recommended
