### ISSUE TITLE
recreate IVFPQ, search result distance not same

### ISSUE THREAD

**Issue by lqqnjust** [milvus-io/milvus#3701]
After first create IVFPQ index，put features, then  i can search myself with distance is 1.
When I drop the index, and create again , i search myself with distance 0.8 or others, but not 1

**Comment by shengjun1985** [comment]
> After first create IVFPQ index，put features, then i can search myself with distance is 1.
The index may not be built yet. Or some reasons may cause the index not to be established.
https://milvus.io/docs/v0.10.2/index.md#Create-indexes

> When I drop the index, and create again , i search myself with distance 0.8 or others, but not 1
It is a correct behavior. IVF_PQ will cause a loss of accuracy.
https://milvus.io/docs/v0.10.2/index.md#IVF_PQ

**Comment by lqqnjust** [comment]
> > After first create IVFPQ index，put features, then i can search myself with distance is 1.
> > The index may not be built yet. Or some reasons may cause the index not to be established.
> > https://milvus.io/docs/v0.10.2/index.md#Create-indexes
> 
> > When I drop the index, and create again , i search myself with distance 0.8 or others, but not 1
> > It is a correct behavior. IVF_PQ will cause a loss of accuracy.
> > https://milvus.io/docs/v0.10.2/index.md#IVF_PQ

I used 100 million features, and milvus log show index has been created. loss of accuracy means there's a big difference in distance value？

**Comment by shengjun1985** [comment]
> loss of accuracy means there's a big difference in distance value？

Yes. If the distance returns 1, it means that IVFPQ is not used when querying.
Another possible reason is that the index of that segment is not built.
https://milvus.io/docs/v0.10.2/storage_concept.md#Partition-and-segment
If you are still confused, please provide more detailed information such as Milvus version, SDK version, DEBUG log.

**Comment by lqqnjust** [comment]
> > loss of accuracy means there's a big difference in distance value？
> 
> Yes. If the distance returns 1, it means that IVFPQ is not used when querying.
> Another possible reason is that the index of that segment is not built.
> https://milvus.io/docs/v0.10.2/storage_concept.md#Partition-and-segment
> If you are still confused, please provide more detailed information such as Milvus version, SDK version, DEBUG log.

milvus version 0.10.2-gpu-d081520-8a2393, sdk pymilvus 0.2.14。 Index file can be found in tables directory. 
You can try to generate some data to test, and search some data in inserted features.
