### ISSUE TITLE
[Bug]: VARCHAR field length exceeded for texts within max_length limit despite validation

### ISSUE THREAD

**Issue by MatzeKiel** [milvus-io/milvus#37026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: Docker milvusdb/milvus:v2.4.13-gpu-hotfix
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.4.8
- OS(Ubuntu or CentOS): Windows 10 Pro Version: 22H2
- CPU/Memory: Intel(R) Core(TM) i7-6700K / 64,0 GB
- GPU: 2x Geforce RTX 3090
```

### Current Behavior

I followed the Milvus Hybrid Search Tutorial (https://milvus.io/docs/de/hybrid_search_with_milvus.md)"

When inserting data into a collection with a VARCHAR field, I receive an error message indicating that the length of the varchar field exceeds the maximum allowed length. This occurs despite reducing the max_chunk_length value from 1024 to 1000 and verifying that no chunk is longer than 1000 characters.

df['length'] = df['chunk'].str.len()
print(df['length'].describe())
-----------------------------------
count     990.00000
mean      652.40303
std       265.60261
min         0.00000
25%       455.25000
50%       717.00000
75%       880.00000
**max      1000.00000**

The error message I receive is:

<MilvusException: (code=1100, message=length of varchar field text exceeds max length, row number: 1, length: 1029, max length: 1024: invalid parameter)>

Despite reducing the max_chunk_length value to 1000, some chunks still exceed this limit.
The chunk lengths are verified using pandas, and no chunk is longer than 1000 characters. However, the error message indicates that a chunk with a length of 1029 exceeds the maximum allowed length.

### Expected Behavior

I expect the data to be inserted successfully into the collection without any errors, as I have taken steps to ensure that all chunks are within the allowed length limit.

### Steps To Reproduce

```markdown
Create a collection with a VARCHAR field using the following FieldSchema:
fields = [
    # Use auto generated id as primary key
    FieldSchema(
        name="pk", dtype=DataType.VARCHAR, is_primary=True, auto_id=True, max_length=100
    ),
    # Store the original text to retrieve based on semantically distance
    FieldSchema(name="text", dtype=DataType.VARCHAR, max_length=1024),
    # Milvus now supports both sparse and dense vectors,
    # we can store each in a separate field to conduct hybrid search on both vectors
    FieldSchema(name="sparse_vector", dtype=DataType.SPARSE_FLOAT_VECTOR),
    FieldSchema(name="dense_vector", dtype=DataType.FLOAT_VECTOR, dim=dense_dim),
]
Generate chunks of data with lengths up to 1000 characters.
Verify the chunk lengths using pandas:
df['length'] = df['chunk'].str.len()
print(df['length'].describe())
Attempt to insert the data into the collection using col.insert(batched_entities).
```

**Comment by yanliang567** [comment]
I believe it is because Milvus use bytes when chekcing length, while pandas uses number of characters as the length.
@MatzeKiel please double check it.

/assign @MatzeKiel 
/unassign

**Comment by MatzeKiel** [comment]
Yes, you were correct. The length for VARCHAR is calculated by Milvus in bytes. I think this kind of thing can't be emphasized enough in the documentation... did I overlook the point where it says that the length of VARCHAR is in bytes?

**Comment by xiaofan-luan** [comment]
thanks for the feedback.
We need to emphasize on that

**Comment by liyun95** [comment]
> @liyun95 please help to improve it in the doc /assign @liyun95

user doc updated - https://github.com/milvus-io/milvus-docs/pull/2843/files
