### ISSUE TITLE
[Bug]: ExceptionTracer.cpp invalid trace stack for exception of type: milvus::SegcoreError what(): Error:RemoveDir:Directory not empty

### ISSUE THREAD

**Issue by heyufeng666888** [milvus-io/milvus#37070]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: 3.4.13
- Deployment mode(standalone or cluster): standalone to k8s deployment
- MQ type(rocksmq, pulsar or kafka):     rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): java 2.4.8
- OS(Ubuntu or CentOS): Linux xc155 5.4.0-125-generic #141-ubuntu SMP wed Aug 10 14:03:41 UTc 2022 aarch64 aarch64 aarch64 GNu/Linux#
- CPU/Memory: HUAWEI Kunpeng 920 5221K 64c/256G 
- GPU: no
- Others:
```

### Current Behavior

1、Milvus standalone version runs on k8s cluster, etcd single node, minio single node
<img width="1167" alt="Snipaste_2024-10-23_14-39-42" src="https://github.com/user-attachments/assets/e70f63d9-5a5f-4084-b778-ef884dafa856">

2、Syncing 10 million data through Java SDK 2.4.8, but restarting after synchronizing tens of thousands，the schema is:
{"autoID":false,"collectionName":"voiceMain","collectionSchema":{"fieldSchemaList":[{"autoID":false,"dataType":"Int64","description":"","dimension":0,"elementType":"None","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":true,"maxCapacity":0,"maxLength":65535,"name":"id"},{"autoID":false,"dataType":"FloatVector","description":"","dimension":1024,"elementType":"None","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":0,"maxLength":65535,"name":"model"},{"autoID":false,"dataType":"VarChar","description":"","dimension":0,"elementType":"None","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":0,"maxLength":128,"name":"modelId"},{"autoID":false,"dataType":"VarChar","description":"","dimension":0,"elementType":"None","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":0,"maxLength":128,"name":"targetId"},{"autoID":false,"dataType":"VarChar","description":"","dimension":0,"elementType":"None","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":0,"maxLength":16,"name":"dateId"},{"autoID":false,"dataType":"Array","description":"","dimension":0,"elementType":"VarChar","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":10,"maxLength":65535,"name":"genderId"},{"autoID":false,"dataType":"Array","description":"","dimension":0,"elementType":"VarChar","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":10,"maxLength":65535,"name":"sourceId"},{"autoID":false,"dataType":"Array","description":"","dimension":0,"elementType":"VarChar","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":10,"maxLength":65535,"name":"personTypeId"},{"autoID":false,"dataType":"Array","description":"","dimension":0,"elementType":"VarChar","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":10,"maxLength":65535,"name":"languageId"},{"autoID":false,"dataType":"Array","description":"","dimension":0,"elementType":"VarChar","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":10,"maxLength":65535,"name":"homeAreaId"},{"autoID":false,"dataType":"Array","description":"","dimension":0,"elementType":"VarChar","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":10,"maxLength":65535,"name":"tag1"},{"autoID":false,"dataType":"Array","description":"","dimension":0,"elementType":"VarChar","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":10,"maxLength":65535,"name":"tag2"},{"autoID":false,"dataType":"Array","description":"","dimension":0,"elementType":"VarChar","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":10,"maxLength":65535,"name":"tag3"},{"autoID":false,"dataType":"Array","description":"","dimension":0,"elementType":"VarChar","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":10,"maxLength":65535,"name":"tag4"},{"autoID":false,"dataType":"Array","description":"","dimension":0,"elementType":"VarChar","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":10,"maxLength":65535,"name":"tag5"},{"autoID":false,"dataType":"Array","description":"","dimension":0,"elementType":"VarChar","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":10,"maxLength":65535,"name":"tag6"},{"autoID":false,"dataType":"Array","description":"","dimension":0,"elementType":"VarChar","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":10,"maxLength":65535,"name":"tag7"},{"autoID":false,"dataType":"Array","description":"","dimension":0,"elementType":"VarChar","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":10,"maxLength":65535,"name":"tag8"},{"autoID":false,"dataType":"Array","description":"","dimension":0,"elementType":"VarChar","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":10,"maxLength":65535,"name":"tag9"},{"autoID":false,"dataType":"Array","description":"","dimension":0,"elementType":"VarChar","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":10,"maxLength":65535,"name":"tag10"}]},"consistencyLevel":"STRONG","createTime":453419734033498116,"databaseName":"default","description":"","enableDynamicField":true,"fieldNames":["id","model","modelId","targetId","dateId","genderId","sourceId","personTypeId","languageId","homeAreaId","tag1","tag2","tag3","tag4","tag5","tag6","tag7","tag8","tag9","tag10"],"numOfPartitions":1,"primaryFieldName":"id","properties":{},"vectorFieldNames":["model"]}

### Milvus Log
[milvus-error.txt](https://github.com/user-attachments/files/17486201/milvus-error.txt)

**Comment by heyufeng666888** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version: 3.4.13
> - Deployment mode(standalone or cluster): standalone to k8s deployment
> - MQ type(rocksmq, pulsar or kafka):     rocksmq
> - SDK version(e.g. pymilvus v2.0.0rc2): java 2.4.8
> - OS(Ubuntu or CentOS): Linux xc155 5.4.0-125-generic #141-ubuntu SMP wed Aug 10 14:03:41 UTc 2022 aarch64 aarch64 aarch64 GNu/Linuxroot@xc155:/data/yuanjian/update/20241015/attu#
> - CPU/Memory: HUAWEI Kunpeng 920 5221K 64c/256G
> - GPU: no
> - Others:
> ```
> 
> ### Current Behavior
> 1、Milvus standalone version runs on k8s cluster, etcd single node, minio single node ![WechatIMG440](https://private-user-images.githubusercontent.com/49221269/379122164-4a65e47e-a65e-4962-8b9e-913ef2498aa0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NjQ3MTUsIm5iZiI6MTcyOTY2NDQxNSwicGF0aCI6Ii80OTIyMTI2OS8zNzkxMjIxNjQtNGE2NWU0N2UtYTY1ZS00OTYyLThiOWUtOTEzZWYyNDk4YWEwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA2MjAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1MDhlNDQwOTk5OTBlYjk3YzM2YmM3NDExYzAzZDYxYTJkOTgyNjI2ZTgyNjRhNDY5MGZiZDU2NDdhNGJiZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5m57aaL2VBcv0_dxwwi7UmDtQOuW3rxFbffEgT1x5Do)
> 
> 2、Syncing 10 million data through Java SDK 2.4.8, but restarting after synchronizing tens of thousands，the schema is: {"autoID":false,"collectionName":"voiceMain","collectionSchema":{"fieldSchemaList":[{"autoID":false,"dataType":"Int64","description":"","dimension":0,"elementType":"None","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":true,"maxCapacity":0,"maxLength":65535,"name":"id"},{"autoID":false,"dataType":"FloatVector","description":"","dimension":1024,"elementType":"None","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":0,"maxLength":65535,"name":"model"},{"autoID":false,"dataType":"VarChar","description":"","dimension":0,"elementType":"None","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":0,"maxLength":128,"name":"modelId"},{"autoID":false,"dataType":"VarChar","description":"","dimension":0,"elementType":"None","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":0,"maxLength":128,"name":"targetId"},{"autoID":false,"dataType":"VarChar","description":"","dimension":0,"elementType":"None","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":0,"maxLength":16,"name":"dateId"},{"autoID":false,"dataType":"Array","description":"","dimension":0,"elementType":"VarChar","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":10,"maxLength":65535,"name":"genderId"},{"autoID":false,"dataType":"Array","description":"","dimension":0,"elementType":"VarChar","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":10,"maxLength":65535,"name":"sourceId"},{"autoID":false,"dataType":"Array","description":"","dimension":0,"elementType":"VarChar","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":10,"maxLength":65535,"name":"personTypeId"},{"autoID":false,"dataType":"Array","description":"","dimension":0,"elementType":"VarChar","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":10,"maxLength":65535,"name":"languageId"},{"autoID":false,"dataType":"Array","description":"","dimension":0,"elementType":"VarChar","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":10,"maxLength":65535,"name":"homeAreaId"},{"autoID":false,"dataType":"Array","description":"","dimension":0,"elementType":"VarChar","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":10,"maxLength":65535,"name":"tag1"},{"autoID":false,"dataType":"Array","description":"","dimension":0,"elementType":"VarChar","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":10,"maxLength":65535,"name":"tag2"},{"autoID":false,"dataType":"Array","description":"","dimension":0,"elementType":"VarChar","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":10,"maxLength":65535,"name":"tag3"},{"autoID":false,"dataType":"Array","description":"","dimension":0,"elementType":"VarChar","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":10,"maxLength":65535,"name":"tag4"},{"autoID":false,"dataType":"Array","description":"","dimension":0,"elementType":"VarChar","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":10,"maxLength":65535,"name":"tag5"},{"autoID":false,"dataType":"Array","description":"","dimension":0,"elementType":"VarChar","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":10,"maxLength":65535,"name":"tag6"},{"autoID":false,"dataType":"Array","description":"","dimension":0,"elementType":"VarChar","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":10,"maxLength":65535,"name":"tag7"},{"autoID":false,"dataType":"Array","description":"","dimension":0,"elementType":"VarChar","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":10,"maxLength":65535,"name":"tag8"},{"autoID":false,"dataType":"Array","description":"","dimension":0,"elementType":"VarChar","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":10,"maxLength":65535,"name":"tag9"},{"autoID":false,"dataType":"Array","description":"","dimension":0,"elementType":"VarChar","isClusteringKey":false,"isPartitionKey":false,"isPrimaryKey":false,"maxCapacity":10,"maxLength":65535,"name":"tag10"}]},"consistencyLevel":"STRONG","createTime":453419734033498116,"databaseName":"default","description":"","enableDynamicField":true,"fieldNames":["id","model","modelId","targetId","dateId","genderId","sourceId","personTypeId","languageId","homeAreaId","tag1","tag2","tag3","tag4","tag5","tag6","tag7","tag8","tag9","tag10"],"numOfPartitions":1,"primaryFieldName":"id","properties":{},"vectorFieldNames":["model"]}
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> ![WechatIMG393](https://private-user-images.githubusercontent.com/49221269/379118619-0209ad5d-d62e-4883-ae5c-741e2aad5560.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NjQ3MTUsIm5iZiI6MTcyOTY2NDQxNSwicGF0aCI6Ii80OTIyMTI2OS8zNzkxMTg2MTktMDIwOWFkNWQtZDYyZS00ODgzLWFlNWMtNzQxZTJhYWQ1NTYwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA2MjAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyMjBkZjVmNTgyMjBmZDcyZTc3OTZkY2YwYzg3ODQ5MzJjY2M2ZmE1NDVjNWEwNDAxMTI4NDk3MDlkYTYwMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lS7r7H0cTnlcOWXiPKnVYolzv2_vu4b64cnht60NNlM) ![WechatIMG318](https://private-user-images.githubusercontent.com/49221269/379118641-14915f4c-0da6-4695-93c5-f8c99229221e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NjQ3MTUsIm5iZiI6MTcyOTY2NDQxNSwicGF0aCI6Ii80OTIyMTI2OS8zNzkxMTg2NDEtMTQ5MTVmNGMtMGRhNi00Njk1LTkzYzUtZjhjOTkyMjkyMjFlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA2MjAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NGIyMmY0YjFmYzM5MDQ1Mzc0ZTBiMzg1OTE4NjIxNWE5YzYyODc4YzJlM2VjYjE2MjgxMDZkODZlOGE4OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XGSbW_yukkIK8zVXxhkWOQ7-eYNUaCRXBocYLCUUCRo) ![WechatIMG300](https://private-user-images.githubusercontent.com/49221269/379118646-f412ee55-fea3-41e7-8e04-4bcff0d32cbf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NjQ3MTUsIm5iZiI6MTcyOTY2NDQxNSwicGF0aCI6Ii80OTIyMTI2OS8zNzkxMTg2NDYtZjQxMmVlNTUtZmVhMy00MWU3LThlMDQtNGJjZmYwZDMyY2JmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA2MjAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZTk5OTliNjczZTViM2ZhZThiMWI2ZjU4OTY0OGJhMmMxNjkwYzcxZjJjODkzODMxOTg4ODFkOWI5YzA5ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hptimlGp6cieZnft718QRuee9eUVjry2xJi7KQXdWNY) ![WechatIMG299](https://private-user-images.githubusercontent.com/49221269/379118652-997bd516-5d9e-4471-9e21-a7d7089a3208.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NjQ3MTUsIm5iZiI6MTcyOTY2NDQxNSwicGF0aCI6Ii80OTIyMTI2OS8zNzkxMTg2NTItOTk3YmQ1MTYtNWQ5ZS00NDcxLTllMjEtYTdkNzA4OWEzMjA4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA2MjAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkN2I2OTBkY2NiMzk0MDYyYTllYzNkYWM3OWRiN2UyMjY4MWE5OWFlZmQ3ZmZmMTcyYzUxZTk1MDk4Y2FkYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dFOM4PhM99fVym_4Xhi2EBV1HYcb9Ubp6YwVMUBlGrQ) ![WechatIMG408](https://private-user-images.githubusercontent.com/49221269/379118662-739a0492-e446-4bad-9582-883c58bda81b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NjQ3MTUsIm5iZiI6MTcyOTY2NDQxNSwicGF0aCI6Ii80OTIyMTI2OS8zNzkxMTg2NjItNzM5YTA0OTItZTQ0Ni00YmFkLTk1ODItODgzYzU4YmRhODFiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA2MjAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNzRjOGEwMTI1ODk2NWU1ZmM0ZDkwNmE5N2I4M2E0ZWQ5ZjYxYjZmNTdiMTY3ZTIxZjZmZDI4YTBkMmZkZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Cppg5zoG0mRQdsJ1pRkYpVE59invoJyEfq5D1kZe7e4)
> 
> ### Anything else?
> _No response_

**Comment by yanliang567** [comment]
/assign @liliu-z 
it seems that milvus/knowhere crashed after building index

/unassign

**Comment by foxspy** [comment]
> /assign @liliu-z it seems that milvus/knowhere crashed after building index
> 
> /unassign

@yanliang567 
This shouldn't have much to do with building index; based on the logs, the error occurred while trying to delete a non-empty directory. HNSW does not rely on the file system during construction and loading. It seems this exception occurred during the resource cleanup of the Release segment.

**Comment by foxspy** [comment]
@heyufeng666888 
What is the correct milvus version? 3.4.13 is not a valid version, please provide the correct one. And it seems that https://github.com/milvus-io/milvus/issues/33587 milvus 2.4.5 has fixed the issue.

**Comment by heyufeng666888** [comment]
sorry, milvus version is 2.4.13-hotfix,I saw that the problem #33587 is indeed quite similar, but it has reappeared

**Comment by foxspy** [comment]
> sorry, milvus version is 2.4.13-hotfix,I saw that the problem #33587 is indeed quite similar, but it has reappeared

Could you provide more log information? Specifically, logs from five minutes before the error

**Comment by heyufeng666888** [comment]
Sorry, the site has been rolled back to version 2.3. x. The site is in a formal environment and is not easy to modify, so we cannot provide logs
