### ISSUE TITLE
[Bug]: The mixCompaction task timeout causes level compaction tasks to be blocked

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#37108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4-20241023-2abc28ec-amd64
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

## server config
```
   dataCoord:
      compaction:
        taskPrioritizer: level
```
## test 
collection `fouram_rf7If1S0` has 76987021 entities, delete 2284000 pks with 2000 batch by `pk in` expr
## result
- proxy delete rate
![image](https://github.com/user-attachments/assets/f9bc0385-ee5f-43ab-83f6-eb840e031d24)
- dataCoord segment num and compaction executing, mixCompaction timeout and unable to execute level compaction
![image](https://github.com/user-attachments/assets/e1675c94-4372-470f-92a3-147402bc1714)
![image](https://github.com/user-attachments/assets/ce2481e0-65c7-45f4-ba20-9a1e455a141d)

[metris](https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=db7e3557-d29c-4d2b-be40-9f465bcec112&var-namespace=qa-milvus&var-instance=compact-opt-rate-100m-1&var-collection=All&var-app_name=milvus&from=1729754090805&to=1729758418326)

### Expected Behavior

remove dataCoord compaction timeout

### Milvus Log

pods:
```
compact-opt-rate-100m-1-milvus-datanode-55cc78cff8-jnn5b          1/1     Running     0               20h     10.104.15.226   4am-node20   <none>           <none>
compact-opt-rate-100m-1-milvus-indexnode-5c7f96664f-gq2bb         1/1     Running     0               20h     10.104.34.66    4am-node37   <none>           <none>
compact-opt-rate-100m-1-milvus-indexnode-5c7f96664f-n6dg9         1/1     Running     0               20h     10.104.20.75    4am-node22   <none>           <none>
compact-opt-rate-100m-1-milvus-indexnode-5c7f96664f-trrgf         1/1     Running     0               20h     10.104.23.34    4am-node27   <none>           <none>
compact-opt-rate-100m-1-milvus-mixcoord-57bf64ccc6-76gz4          1/1     Running     0               20h     10.104.13.41    4am-node16   <none>           <none>
compact-opt-rate-100m-1-milvus-proxy-6c566745d6-g8kn6             1/1     Running     0               20h     10.104.15.227   4am-node20   <none>           <none>
compact-opt-rate-100m-1-milvus-querynode-0-7847bc8bf4-2fcgt       1/1     Running     0               20h     10.104.18.167   4am-node25   <none>           <none>
compact-opt-rate-100m-1-milvus-querynode-0-7847bc8bf4-5hktm       1/1     Running     0               20h     10.104.15.221   4am-node20   <none>           <none>
compact-opt-rate-100m-1-milvus-querynode-0-7847bc8bf4-9qmft       1/1     Running     0               20h     10.104.30.146   4am-node38   <none>           <none>
compact-opt-rate-100m-1-milvus-querynode-0-7847bc8bf4-cjg8z       1/1     Running     0               20h     10.104.20.76    4am-node22   <none>           <none>
compact-opt-rate-100m-1-milvus-querynode-0-7847bc8bf4-fnjvp       1/1     Running     0               20h     10.104.34.74    4am-node37   <none>           <none>
```

**Comment by XuanYang-cn** [comment]
varchar too large, making DC creates too many MixCompaction tasks
```
		2024-10-24 18:59:41.684	
[2024/10/24 10:59:41.300 +00:00] [DEBUG] [datacoord/compaction_trigger.go:752] ["check whether segment has too many delete data"] [segmentID=453426408654343968] [numRows=2450808] ["deleted rows"=6579] ["delete log size"=6789528] [result=true]
```

**Comment by xiaofan-luan** [comment]
> varchar too large, making DC creates too many MixCompaction tasks
> 
> ```
> 		2024-10-24 18:59:41.684	
> [2024/10/24 10:59:41.300 +00:00] [DEBUG] [datacoord/compaction_trigger.go:752] ["check whether segment has too many delete data"] [segmentID=453426408654343968] [numRows=2450808] ["deleted rows"=6579] ["delete log size"=6789528] [result=true]
> ```

why do varchar releated mixcompaction? did you mean L0 compaction?

**Comment by XuanYang-cn** [comment]
PK is varchar, tooMuch delete count ratio and delete bytes(2MB) will generate MixCompaction.  This'll generate too many MixCompaction tasks.
![img_v3_02fv_87e301a0-4e8a-41aa-8758-ed49d12e1f4g](https://github.com/user-attachments/assets/b90154d0-ef2f-46e1-b02f-e3745c6986f8)

**Comment by xiaofan-luan** [comment]
understand.
Seems that it's better to use delete count instead of delete size to trigger mix compaction?
Do you have meta info or delete count instead?

**Comment by XuanYang-cn** [comment]
/assign @ThreadDao 
/unassign
should be fixed, please help verify

**Comment by ThreadDao** [comment]
fxied
