### ISSUE TITLE
[Bug]: When concurrent DQL and Upsert to varchar pk collection, cpu usage varies significantly between the delegator and qn

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#37152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20241024-0dbf9482-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

## server config
- qn 2*8c32g

## test steps
1. create a collection: varchar pk field (max_length=32) + 128dim vector field + int64 cluster_key
```
{'auto_id': False, 'description': '', 'fields': [{'name': 'id', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 32}, 'is_primary': True, 'auto_id': False}, {'name': 'float_vector', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 128}}, {'name': 'int64_ck', 'description': '', 'type': <DataType.INT64: 5>, 'is_clustering_key': True}], 'enable_dynamic_field': False}
```
2. create HNSW index -> insert 30m -> flush -> index again -> load
3. concurrent requests: search + query + upsert
```
concurrent_tasks = [
            ConcurrentParams.params_search(
                weight=15, nq=10, top_k=100, search_param={"ef": 120},
                output_fields=['id'], timeout=None, check_task=CheckTasks.checkSearchOutput,
                check_items={"nq": 10},
            ),
            ConcurrentParams.params_query(
                weight=10, expr=" ", random_data=True, random_count=20, random_range=[0, 50000000],
                field_name=cluster_key_field, timeout=None,
            ),
            ConcurrentParams.params_upsert(weight=5, nb=200, random_id=True, random_vector=True, timeout=None)
        ]
```
## results
1. delegator cpu usage is always 100%, the other one is very low cpu usage
![image](https://github.com/user-attachments/assets/cd88733f-6d67-404e-8ec3-fef24e35c6a8)
![image](https://github.com/user-attachments/assets/bd18d8b4-a200-4e51-9703-dafe8fa9a67d)
![image](https://github.com/user-attachments/assets/43322b6c-de7e-4710-8c42-c997b588fd70)

![image](https://github.com/user-attachments/assets/49fd80bc-2043-4b5b-b676-c18f439fed85)

### Steps To Reproduce

```markdown
https://argo-workflows.zilliz.cc/archived-workflows/qa/d9435fd5-8c71-4fa0-a740-3ec43803aedc?nodeId=zong-stats-clustering-24h-3c
```

### Milvus Log

- metrics: https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=P1809F7CD0C75ACF3&var-namespace=qa-milvus&var-instance=stats-varchar-cring-op-27-8989&var-collection=All&var-app_name=milvus&from=1729843186844&to=1729845156866
- pods:
```
stats-varchar-cring-op-27-8989-milvus-datanode-549c45b995-822ch   1/1     Running     0               20h     10.104.16.168   4am-node21   <none>           <none>
stats-varchar-cring-op-27-8989-milvus-indexnode-6c85c6b98-dg25f   1/1     Running     0               20h     10.104.33.147   4am-node36   <none>           <none>
stats-varchar-cring-op-27-8989-milvus-indexnode-6c85c6b98-xxc72   1/1     Running     0               20h     10.104.6.13     4am-node13   <none>           <none>
stats-varchar-cring-op-27-8989-milvus-mixcoord-56bf4b58fd-g88n9   1/1     Running     0               20h     10.104.16.169   4am-node21   <none>           <none>
stats-varchar-cring-op-27-8989-milvus-proxy-74d8c498bf-xmxlc      1/1     Running     0               20h     10.104.33.146   4am-node36   <none>           <none>
stats-varchar-cring-op-27-8989-milvus-querynode-0-84f676848nzvz   1/1     Running     0               20h     10.104.15.98    4am-node20   <none>           <none>
stats-varchar-cring-op-27-8989-milvus-querynode-0-84f67684scdrr   1/1     Running     0               20h     10.104.9.96     4am-node14   <none>           <none>
```

**Comment by xiaofan-luan** [comment]
/assign @zhagnlu 
we should remove the views and avoid copy

**Comment by xiaofan-luan** [comment]
I think it's better to give each chunk an iterator interface so we don't need to view it

**Comment by xiaofan-luan** [comment]
@xiaocai2333 
this seems to be a SearchPK issue

**Comment by chasingegg** [comment]
seems Views() was introduced to reduce variable column memory occupation, so we construct the views at runtime. But as least, there is a problem that Views() does not reserve std::vector space at first which will make reallocate expensive.

**Comment by xiaocai2333** [comment]
It seems that using views introduces additional memory overhead. Accessing the raw data directly to search for pk can help reduce this overhead. I will fix it.

**Comment by xiaofan-luan** [comment]
/assign @ThreadDao 
please help on verifying the master
