### ISSUE TITLE
[Enhancement]: Make meta read requests non-sequential to avoid affecting tsafe

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#37183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Make meta read requests non-sequential to avoid affecting tsafe
proxy could utilize meta cache to avoid rpc calls to rootcoord

### Why is this needed?

currently, large amount of meta read request(say HasCollection, DescribeCollection, etc) will wait in line in rootcoord scheduler which may cause timetick delay

**Comment by xiaofan-luan** [comment]
questions:
does that mean create collection return succeed and user will get wrong result when they do has collection?

That doesn't really make sense to me unless we put purge collection meta before return succeed

**Comment by xiaofan-luan** [comment]
I still don't think it's a good idea to read from proxy cache @congqixia @SimFG

**Comment by SimFG** [comment]
@xiaofan-luan I remember that this interface was previously said to be deprecated, should use the describe collection.
