### ISSUE TITLE
[Bug]: <ConnectionConfigException: (code=1, message=Open local milvus failed)>

### ISSUE THREAD

**Issue by pandabo1985** [milvus-io/milvus#37213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4.10
- Deployment mode(standalone or cluster):  milvus_lite
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.3
- OS(Ubuntu or CentOS): macos
- CPU/Memory: Intel Core i9/64 GB 
- GPU: 
- Others:
```

### Current Behavior

fastapi 封装接口，本地运行gunicorn -c gunicorn_conf_test.py app.main:app  

# Gunicorn 配置文件
import multiprocessing
import datetime

current_date = datetime.datetime.now().strftime("%Y_%m_%d_%H_%M")
# 绑定的IP和端口
#bind = "127.0.0.1:8010"
bind = "0.0.0.0:8000"

# 工作进程数
workers = multiprocessing.cpu_count() * 2 + 1 
#workers = 1
# 工作模式
worker_class = "uvicorn.workers.UvicornWorker"

# 超时时间
timeout = 120

# 允许处理的最大并发量
max_requests = 2000
max_requests_jitter = 200

# 日志配置
accesslog = f"./logs/access_{current_date}.log"
errorlog = f"./logs/error_{current_date}.log"
loglevel = "info"

# 后台运行
daemon = True

# 进程文件
pidfile = "./run/gunicorn.pid"

### Expected Behavior

当工作进程大于 1 时候，workers = multiprocessing.cpu_count() * 2 + 1  ，第一次接口请求成功后，再次请求就会报错。
<ConnectionConfigException: (code=1, message=Open local milvus failed)>。
只有workers = 1，才不会报错。

### Steps To Reproduce

```markdown
1.代码一样。本地部署，唯一变量workers = multiprocessing.cpu_count() * 2 + 1
或者workers = 1
```

### Milvus Log

<ConnectionConfigException: (code=1, message=Open local milvus failed)> 提示报错信息

**Comment by yanliang567** [comment]
I doubt that milvus lite does not support running against multi-processing work load. @junjiejiangjjj please help to take a look

/assign @junjiejiangjjj

**Comment by junjiejiangjjj** [comment]
hi @pandabo1985 ,  milvus-lite does not support multiple processes opening the same file, which will cause data confusion

**Comment by pandabo1985** [comment]
👌 thanks
