### ISSUE TITLE
Unfit property name "segment_row_count"  in 0.11

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus#3722]
**Please state your issue using the following template and, most importantly, in English.**
Unfit property name "segment_row_count" 

**What would you like to be added ?**
maybe "segment_row_limit" is a better name 

**Why is this needed ?**
The property name is not self-explanatory.

**Comment by JinHai-CN** [comment]
Yes, I also prefer the name: segment_row_limit.

**Comment by scsven** [comment]
done
