### ISSUE TITLE
[Bug]: Brute force search should set segment offsets for chunked segment

### ISSUE THREAD

**Issue by sunby** [milvus-io/milvus#37244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master/2.5
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

search results' offsets is chunk offset.
lack some unittests for brute force search.

**Comment by liliu-z** [comment]
@sunby Can we close this?

**Comment by sunby** [comment]
> @sunby Can we close this?

yes, it's fixed.
