### ISSUE TITLE
[Bug]: Build error in docker

### ISSUE THREAD

**Issue by shawnwang1024** [milvus-io/milvus#37243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.13
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

[ 68%] Built target aws-cpp-sdk-config
gmake[2]: Leaving directory '/home/milvus/.conan/data/aws-sdk-cpp/1.9.234/_/_/build/de2508abd0f06d2f5a48b45338929e9b87d742e9/build/Release'
gmake[1]: *** [Makefile:136: all] Error 2
gmake[1]: Leaving directory '/home/milvus/.conan/data/aws-sdk-cpp/1.9.234/_/_/build/de2508abd0f06d2f5a48b45338929e9b87d742e9/build/Release'
aws-sdk-cpp/1.9.234: 
aws-sdk-cpp/1.9.234: ERROR: Package 'de2508abd0f06d2f5a48b45338929e9b87d742e9' build failed
aws-sdk-cpp/1.9.234: WARN: Build folder /home/milvus/.conan/data/aws-sdk-cpp/1.9.234/_/_/build/de2508abd0f06d2f5a48b45338929e9b87d742e9/build/Release
ERROR: aws-sdk-cpp/1.9.234: Error in build() method, line 441
	cmake.build()
	ConanException: Error 2 while executing cmake --build "/home/milvus/.conan/data/aws-sdk-cpp/1.9.234/_/_/build/de2508abd0f06d2f5a48b45338929e9b87d742e9/build/Release" '--' '-j2'
conan install failed

### Steps To Reproduce

```markdown
run build/builder.sh make
```

**Comment by Presburger** [comment]
@shawnwang1024 Could you provide some more detailed error information?

**Comment by iamvbenz49** [comment]
Did you find any way to solve this issue? @shawnwang1024
