### ISSUE TITLE
[Bug]: `pymilvus.Collection.upsert` bug, 

### ISSUE THREAD

**Issue by Desperado-Jia** [milvus-io/milvus#37283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.14
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.4.4
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 16G
- GPU: None
- Others:
```

### Current Behavior

For an existing doc in the library, when the same pk upsert is specified, a new document will be created instead of updating the original doc.

```
fields = [
    FieldSchema(
        name="pk",
        dtype=DataType.VARCHAR, max_length=65535,
        is_primary=True, auto_id=False
    ),
    FieldSchema(
        name="data",
        dtype=DataType.ARRAY,
        element_type=DataType.VARCHAR,
        max_length=65535,
        max_capacity=4096,
    ),  # `List[str]`
    FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=1024)
]
collection = Collection(
    name="default",
    schema=CollectionSchema(fields=self.fields, enable_dynamic_field=False),
    **{"consistency_level": "Strong"}
)

docs = [["id-1", "111", [1.0 for _ in range(1024)]], ["id-2", "222", [2.0 for _ in range(1024)]]]

print(collection.num_entities)  # 0
collection.upsert(docs)
collection.flush()
print(collection.num_entities)  # 2

collection.upsert(docs)
collection.flush()
print(collection.num_entities)  # **4**
```

ERROR FOR NUM ENTITIES after upsert again

### Expected Behavior

0
2
2

### Milvus Log

<img width="676" alt="image" src="https://github.com/user-attachments/assets/7d5d917d-dfcd-4c1a-a50a-297cfc7abf58">

### Anything else?

None

**Comment by yanliang567** [comment]
collection.num_entities is not accurate in this case, it only updates after compaction completed. please try to use query count(*) to get a accurate entities https://milvus.io/docs/get-and-scalar-query.md#Use-Advanced-Operators. @Desperado-Jia 
/assign @Desperado-Jia 
/unassign
