### ISSUE TITLE
[Bug]: the status is nill when the has collection task is successful

### ISSUE THREAD

**Issue by SimFG** [milvus-io/milvus#37323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/user-attachments/assets/ccadf89f-cfa0-4915-9fc0-fa611d426740)
related issue: #37183

**Comment by zhuwenxing** [comment]
https://github.com/milvus-io/milvus/issues/37257
Are these two issues duplicates? @wayblink  has also submitted a PR https://github.com/milvus-io/milvus/pull/37254 to fix it.
