### ISSUE TITLE
[Bug]: restful bug

### ISSUE THREAD

**Issue by smellthemoon** [milvus-io/milvus#37370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. when autoid but still insert pk, pk will just be ingnored, not throw err.
2. query json data, user will see the byte, not json format.

3. insert pass pk when autoid==true,but set dynamic field, will thought pk is in dynamic.
4. if pass more field, restful will just ignore those extra field.
5. add nullable and default value describe.
6. pass "$meta" when enable dynamic field should report error.
7. describe collection field should not contains "$meta"

**Comment by qixuan0212** [comment]
@smellthemoon When field in a collection is set to default or nullable, the response body of the describe collection interface does not contain default or nullable information.

**Comment by smellthemoon** [comment]
> @smellthemoon When field in a collection is set to default or nullable, the response body of the describe collection interface does not contain default or nullable information.

has added it in the issue describe.

**Comment by smellthemoon** [comment]
@zhuwenxing could you help to add some test about the issue?
