### ISSUE TITLE
[Bug]: [benchmark][cluster] deploy milvus panic, init Proxy server failed: context deadline exceeded

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#37372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.5-20241101-47337ea8-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task: fouramf-jwltv
test case name: test_concurrent_locust_diskann_dml_dql_filter_cluster

server:
```
NAME                                                              READY   STATUS             RESTARTS        AGE     IP              NODE         NOMINATED NODE   READINESS GATES
streaming-node-corn-1730430000-1-etcd-0                           1/1     Running            0               30m     10.104.19.234   4am-node28   <none>           <none>
streaming-node-corn-1730430000-1-etcd-1                           1/1     Running            0               30m     10.104.16.138   4am-node21   <none>           <none>
streaming-node-corn-1730430000-1-etcd-2                           1/1     Running            0               30m     10.104.26.29    4am-node32   <none>           <none>
streaming-node-corn-1730430000-1-milvus-datanode-8b98f4c897hbgb   0/1     CrashLoopBackOff   10 (2m1s ago)   30m     10.104.26.27    4am-node32   <none>           <none>
streaming-node-corn-1730430000-1-milvus-indexnode-5b44fd8fk55tz   0/1     CrashLoopBackOff   10 (75s ago)    30m     10.104.9.115    4am-node14   <none>           <none>
streaming-node-corn-1730430000-1-milvus-mixcoord-979c5cb5-f8psv   0/1     CrashLoopBackOff   10 (3m ago)     30m     10.104.15.121   4am-node20   <none>           <none>
streaming-node-corn-1730430000-1-milvus-proxy-68c8cbf5d5-bkk9l    0/1     CrashLoopBackOff   10 (2m3s ago)   30m     10.104.15.122   4am-node20   <none>           <none>
streaming-node-corn-1730430000-1-milvus-querynode-6696fd4bntqlc   0/1     CrashLoopBackOff   10 (99s ago)    30m     10.104.15.120   4am-node20   <none>           <none>
streaming-node-corn-1730430000-1-minio-0                          1/1     Running            0               30m     10.104.30.250   4am-node38   <none>           <none>
streaming-node-corn-1730430000-1-minio-1                          1/1     Running            0               30m     10.104.19.236   4am-node28   <none>           <none>
streaming-node-corn-1730430000-1-minio-2                          1/1     Running            0               30m     10.104.16.139   4am-node21   <none>           <none>
streaming-node-corn-1730430000-1-minio-3                          1/1     Running            0               30m     10.104.34.237   4am-node37   <none>           <none>
streaming-node-corn-1730430000-1-pulsar-bookie-0                  1/1     Running            0               30m     10.104.15.125   4am-node20   <none>           <none>
streaming-node-corn-1730430000-1-pulsar-bookie-1                  1/1     Running            0               30m     10.104.24.144   4am-node29   <none>           <none>
streaming-node-corn-1730430000-1-pulsar-bookie-2                  1/1     Running            0               30m     10.104.16.144   4am-node21   <none>           <none>
streaming-node-corn-1730430000-1-pulsar-bookie-init-m4zmk         0/1     Completed          0               30m     10.104.18.7     4am-node25   <none>           <none>
streaming-node-corn-1730430000-1-pulsar-broker-0                  1/1     Running            0               30m     10.104.18.8     4am-node25   <none>           <none>
streaming-node-corn-1730430000-1-pulsar-proxy-0                   1/1     Running            0               30m     10.104.30.247   4am-node38   <none>           <none>
streaming-node-corn-1730430000-1-pulsar-pulsar-init-vr5nx         0/1     Completed          0               30m     10.104.18.9     4am-node25   <none>           <none>
streaming-node-corn-1730430000-1-pulsar-recovery-0                1/1     Running            0               30m     10.104.30.248   4am-node38   <none>           <none>
streaming-node-corn-1730430000-1-pulsar-zookeeper-0               1/1     Running            0               30m     10.104.19.237   4am-node28   <none>           <none>
streaming-node-corn-1730430000-1-pulsar-zookeeper-1               1/1     Running            0               29m     10.104.15.143   4am-node20   <none>           <none>
streaming-node-corn-1730430000-1-pulsar-zookeeper-2               1/1     Running            0               28m     10.104.32.24    4am-node39   <none>           <none>
```

`kubectl describe pod streaming-node-corn-1730430000-1-milvus-proxy-68c8cbf5d5-bkk9l -n qa-milvus`
![image](https://github.com/user-attachments/assets/85d6d089-3d3a-497b-ad91-869122f70b86)

`kubectl logs streaming-node-corn-1730430000-1-milvus-proxy-68c8cbf5d5-bkk9l -n qa-milvus`
![image](https://github.com/user-attachments/assets/18b79f16-d3d0-411c-8feb-1e9f9715bda3)
<img width="1920" alt="截屏2024-11-01 20 13 58" src="https://github.com/user-attachments/assets/fbd4d55b-bb4a-4fe6-a64e-20b7cccbcb78">

### Anything else?

server config:
```
{
     "queryNode": {
          "resources": {
               "limits": {
                    "cpu": "4.0",
                    "memory": "4Gi"
               },
               "requests": {
                    "cpu": "3.0",
                    "memory": "3Gi"
               }
          },
          "replicas": 1
     },
     "indexNode": {
          "resources": {
               "limits": {
                    "cpu": "2.0",
                    "memory": "4Gi"
               },
               "requests": {
                    "cpu": "2.0",
                    "memory": "3Gi"
               }
          },
          "replicas": 1
     },
     "dataNode": {
          "resources": {
               "limits": {
                    "cpu": "2.0",
                    "memory": "2Gi"
               },
               "requests": {
                    "cpu": "2.0",
                    "memory": "2Gi"
               }
          }
     },
     "cluster": {
          "enabled": true
     },
     "pulsar": {},
     "kafka": {},
     "minio": {
          "metrics": {
               "podMonitor": {
                    "enabled": true
               }
          }
     },
     "etcd": {
          "metrics": {
               "enabled": true,
               "podMonitor": {
                    "enabled": true
               }
          }
     },
     "metrics": {
          "serviceMonitor": {
               "enabled": true
          }
     },
     "log": {
          "level": "debug"
     },
     "image": {
          "all": {
               "repository": "harbor.milvus.io/milvus/milvus",
               "tag": "2.5-20241101-47337ea8-amd64"
          }
     }
}
```

**Comment by xiaofan-luan** [comment]
this seems to be an network issue, not a milvus bug

**Comment by MrPresent-Han** [comment]
Case1: Deadline exceed due to cpu contention
this case may fail because cpu contention:
![20241103-233340](https://github.com/user-attachments/assets/e883cae9-3a6e-41a8-9226-80ec8d049c6b)
![20241103-233333](https://github.com/user-attachments/assets/eaa13379-acf9-484b-8e6d-9440efd939dc)
![20241103-233314](https://github.com/user-attachments/assets/e9e84b7f-1d62-4abe-ac6b-71bc81654584)

as images above, the querynode is blocked by cpu contention because milvus-build and milvus-cpp-unit-test grab some cpu cycles at the same time period

**Comment by wangting0128** [comment]
> Case1: Deadline exceed due to cpu contention this case may fail because cpu contention: ![20241103-233340](https://private-user-images.githubusercontent.com/116052805/382640850-e883cae9-3a6e-41a8-9226-80ec8d049c6b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDI4ODIsIm5iZiI6MTczMDcwMjU4MiwicGF0aCI6Ii8xMTYwNTI4MDUvMzgyNjQwODUwLWU4ODNjYWU5LTNhNmUtNDFhOC05MjI2LTgwZWM4ZDA0OWM2Yi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQwNjQzMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MmE3OTJmM2ZmZTBmNzgwMmEwOTRjOWJhYWZjYWIxZWFkODE3NTIyYWRiMmYxMGQyNGI4MDlmY2QwNzRhYWE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.P_nrCZYBgzaSoCd2vQ0bE2bfrO8kM-6_aaSRv6HM6Oo) ![20241103-233333](https://private-user-images.githubusercontent.com/116052805/382640852-eaa13379-acf9-484b-8e6d-9440efd939dc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDI4ODIsIm5iZiI6MTczMDcwMjU4MiwicGF0aCI6Ii8xMTYwNTI4MDUvMzgyNjQwODUyLWVhYTEzMzc5LWFjZjktNDg0Yi04ZTZkLTk0NDBlZmQ5MzlkYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQwNjQzMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTcwZDU0MjhmZjY5YzMzMzQyYWNiZmZmOTcyNzczZDFkZDgyMWRmYWZmNTkzYTI0ZDViNDc1ZjZjNjFkOGFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SO8Q-kiRPtv1QDtUVJ1apntL7waNcvTZUTyOKLtcnIc) ![20241103-233314](https://private-user-images.githubusercontent.com/116052805/382640854-e9e84b7f-1d62-4abe-ac6b-71bc81654584.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDI4ODIsIm5iZiI6MTczMDcwMjU4MiwicGF0aCI6Ii8xMTYwNTI4MDUvMzgyNjQwODU0LWU5ZTg0YjdmLTFkNjItNGFiZS1hYzZiLTcxYmM4MTY1NDU4NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQwNjQzMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MGNlMDIzY2JlN2I0ZWQ4MGY5NWNiYjQwNWRhYmFjMjU4ODk5YzBkOWNmYTNhN2VhODIwOWY4MDQ4NTIyMWYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gMqt3W5xt1iFxP1VkOO9pFKSVXipHJYewmIw-OLAStY)
> 
> as images above, the querynode is blocked by cpu contention because milvus-build and milvus-cpp-unit-test grab some cpu cycles at the same time period

The problem is caused by not adding CPU limit to the building task
@yellow-shine  will deal with this problem later

**Comment by wangting0128** [comment]
After limiting the CPU of build cpp, this problem has not occurred recently.
