### ISSUE TITLE
[Bug]: Does Milvus actually perform deduplication?

### ISSUE THREAD

**Issue by barzan-hayati** [milvus-io/milvus#37389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.12
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.4.7
- OS(Ubuntu or CentOS): Ubuntu 18.04
- CPU/Memory: CPU Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHZ / Memory 380G
- GPU: 
- Others:
```

### Current Behavior

I have a collection with `500,000` rows, each with `512` dimensions. 
I indexed it using `HNSW` and now I'm looking to add some duplicate data to this collection. 
Initially, I added a row with ID `10011261403` and conducted an approximate nearest neighbor (ANN) search for 
that specific vector with top-k set to `50`. 
Milvus successfully returned the expected similarity results, with the first entry being the most 
similar, having a similarity score of 1. It's important to note that the collection size was then `500,001`.

`
results [[{'imageId': 10011261403, 'similarity': '100.00'}, {'imageId': 686648, 'similarity': '45.58'}, {'imageId': 737397, 'similarity': '45.04'}, {'imageId': 643527, 'similarity': '43.79'}, {'imageId': 741502, 'similarity': '43.72'}, {'imageId': 528172, 'similarity': '43.18'}, {'imageId': 544907, 'similarity': '43.12'}, {'imageId': 919014, 'similarity': '42.36'}, {'imageId': 968839, 'similarity': '42.22'}, {'imageId': 578254, 'similarity': '42.21'}, {'imageId': 878153, 'similarity': '41.68'}, {'imageId': 729624, 'similarity': '41.62'}, {'imageId': 688188, 'similarity': '41.62'}, {'imageId': 826066, 'similarity': '41.45'}, {'imageId': 791482, 'similarity': '41.41'}, {'imageId': 810394, 'similarity': '41.25'}, {'imageId': 540039, 'similarity': '41.23'}, {'imageId': 639523, 'similarity': '40.80'}, {'imageId': 695039, 'similarity': '40.77'}, {'imageId': 765151, 'similarity': '40.76'}, {'imageId': 869630, 'similarity': '40.65'}, {'imageId': 709693, 'similarity': '40.58'}, {'imageId': 817638, 'similarity': '40.50'}, {'imageId': 716985, 'similarity': '40.25'}, {'imageId': 564771, 'similarity': '40.17'}, {'imageId': 851161, 'similarity': '40.10'}, {'imageId': 580435, 'similarity': '40.03'}, {'imageId': 928875, 'similarity': '40.00'}, {'imageId': 775113, 'similarity': '39.93'}, {'imageId': 827685, 'similarity': '39.82'}, {'imageId': 843015, 'similarity': '39.72'}, {'imageId': 658483, 'similarity': '39.68'}, {'imageId': 822411, 'similarity': '39.42'}, {'imageId': 663101, 'similarity': '39.26'}, {'imageId': 680329, 'similarity': '39.24'}, {'imageId': 859585, 'similarity': '39.20'}, {'imageId': 789022, 'similarity': '39.06'}, {'imageId': 537471, 'similarity': '39.00'}, {'imageId': 898023, 'similarity': '38.95'}, {'imageId': 866630, 'similarity': '38.77'}, {'imageId': 679900, 'similarity': '38.55'}, {'imageId': 556711, 'similarity': '38.51'}, {'imageId': 666701, 'similarity': '38.47'}, {'imageId': 933191, 'similarity': '38.44'}, {'imageId': 938204, 'similarity': '38.39'}, {'imageId': 907738, 'similarity': '38.34'}, {'imageId': 910243, 'similarity': '38.29'}, {'imageId': 595638, 'similarity': '38.20'}, {'imageId': 622850, 'similarity': '38.19'}, {'imageId': 763131, 'similarity': '38.07'}]]
`

Next, I added the duplicate row with ID `10011261403` to the collection again, bringing the collection size to `500,002`. 
When I conducted another ANN search for that vector with top-k set to 50, it only returned one of the 
duplicate vectors, not both. 

`
results [[{'imageId': 10011261403, 'similarity': '100.00'}, {'imageId': 686648, 'similarity': '45.58'}, {'imageId': 737397, 'similarity': '45.04'}, {'imageId': 643527, 'similarity': '43.79'}, {'imageId': 741502, 'similarity': '43.72'}, {'imageId': 528172, 'similarity': '43.18'}, {'imageId': 544907, 'similarity': '43.12'}, {'imageId': 919014, 'similarity': '42.36'}, {'imageId': 968839, 'similarity': '42.22'}, {'imageId': 578254, 'similarity': '42.21'}, {'imageId': 878153, 'similarity': '41.68'}, {'imageId': 729624, 'similarity': '41.62'}, {'imageId': 688188, 'similarity': '41.62'}, {'imageId': 826066, 'similarity': '41.45'}, {'imageId': 791482, 'similarity': '41.41'}, {'imageId': 810394, 'similarity': '41.25'}, {'imageId': 540039, 'similarity': '41.23'}, {'imageId': 639523, 'similarity': '40.80'}, {'imageId': 695039, 'similarity': '40.77'}, {'imageId': 765151, 'similarity': '40.76'}, {'imageId': 869630, 'similarity': '40.65'}, {'imageId': 709693, 'similarity': '40.58'}, {'imageId': 817638, 'similarity': '40.50'}, {'imageId': 716985, 'similarity': '40.25'}, {'imageId': 564771, 'similarity': '40.17'}, {'imageId': 851161, 'similarity': '40.10'}, {'imageId': 580435, 'similarity': '40.03'}, {'imageId': 928875, 'similarity': '40.00'}, {'imageId': 775113, 'similarity': '39.93'}, {'imageId': 827685, 'similarity': '39.82'}, {'imageId': 843015, 'similarity': '39.72'}, {'imageId': 658483, 'similarity': '39.68'}, {'imageId': 822411, 'similarity': '39.42'}, {'imageId': 663101, 'similarity': '39.26'}, {'imageId': 680329, 'similarity': '39.24'}, {'imageId': 859585, 'similarity': '39.20'}, {'imageId': 789022, 'similarity': '39.06'}, {'imageId': 537471, 'similarity': '39.00'}, {'imageId': 898023, 'similarity': '38.95'}, {'imageId': 866630, 'similarity': '38.77'}, {'imageId': 679900, 'similarity': '38.55'}, {'imageId': 556711, 'similarity': '38.51'}, {'imageId': 666701, 'similarity': '38.47'}, {'imageId': 933191, 'similarity': '38.44'}, {'imageId': 938204, 'similarity': '38.39'}, {'imageId': 907738, 'similarity': '38.34'}, {'imageId': 910243, 'similarity': '38.29'}, {'imageId': 595638, 'similarity': '38.20'}, {'imageId': 622850, 'similarity': '38.19'}, {'imageId': 763131, 'similarity': '38.07'}]]
`

Does this mean that Milvus only performs deduplication for the final results, rather than within the collection rows themselves, as illustrated by my example?

### Expected Behavior

The collection size should **remain unchanged** when upserting duplicate rows.

### Anything else?

with this config:

```
    def create_collection(self):
        """
        Create collection using fields. It has a primary key.

        Args:

        Returns:

        """
        __pk_field = FieldSchema(
            name=self.__id_field_name,
            dtype=DataType(self.__id_field_value),
            is_primary=True,
            auto_id=False,
            description="primary key",
        )
        __vector_field = FieldSchema(
            name=self.__vector_field_name,
            dtype=DataType(self.__vector_field_value),
            dim=self.__dim,
        )
        if self.__use_partition_key is True:
            __category_field = FieldSchema(
                name=self.__category_field_name,
                dtype=DataType(self.__category_field_value),
                max_length=self.__max_length_category,
                is_partition_key=True,
            )
            schema = CollectionSchema(
                fields=[
                    __pk_field,
                    __vector_field,
                    __category_field,
                ],
                enable_dynamic_field=True,
                description="collection with partition key",
            )
            self.__collection = Collection(
                name=self.__collection_name,
                schema=schema,
                partition_key_field=self.__category_field_name,
            )
        else:
            schema = CollectionSchema(
                fields=[
                    __pk_field,
                    __vector_field,
                ]
            )
            self.__collection = Collection(name=self.__collection_name, schema=schema)
        MilvusCollection.__logger.info(f"collection {self.__collection_name} created")
        replicas = self.__collection.get_replicas()
        MilvusCollection.__logger.info(f"replicas {replicas}")
        return
```

and upserting:

```
mutation_result = self.__collection.upsert(
                    data=data_collection,
                )
```

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```
> - Milvus version: 2.4.12
> - Deployment mode(standalone or cluster): standalone
> - MQ type(rocksmq, pulsar or kafka):    
> - SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.4.7
> - OS(Ubuntu or CentOS): Ubuntu 18.04
> - CPU/Memory: CPU Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHZ / Memory 380G
> - GPU: 
> - Others:
> ```
> 
> ### Current Behavior
> I have a collection with `500,000` rows, each with `512` dimensions. I indexed it using `HNSW` and now I'm looking to add some duplicate data to this collection. Initially, I added a row with ID `10011261403` and conducted an approximate nearest neighbor (ANN) search for that specific vector with top-k set to `50`. Milvus successfully returned the expected similarity results, with the first entry being the most similar, having a similarity score of 1. It's important to note that the collection size was then `500,001`.
> 
> `results [[{'imageId': 10011261403, 'similarity': '100.00'}, {'imageId': 686648, 'similarity': '45.58'}, {'imageId': 737397, 'similarity': '45.04'}, {'imageId': 643527, 'similarity': '43.79'}, {'imageId': 741502, 'similarity': '43.72'}, {'imageId': 528172, 'similarity': '43.18'}, {'imageId': 544907, 'similarity': '43.12'}, {'imageId': 919014, 'similarity': '42.36'}, {'imageId': 968839, 'similarity': '42.22'}, {'imageId': 578254, 'similarity': '42.21'}, {'imageId': 878153, 'similarity': '41.68'}, {'imageId': 729624, 'similarity': '41.62'}, {'imageId': 688188, 'similarity': '41.62'}, {'imageId': 826066, 'similarity': '41.45'}, {'imageId': 791482, 'similarity': '41.41'}, {'imageId': 810394, 'similarity': '41.25'}, {'imageId': 540039, 'similarity': '41.23'}, {'imageId': 639523, 'similarity': '40.80'}, {'imageId': 695039, 'similarity': '40.77'}, {'imageId': 765151, 'similarity': '40.76'}, {'imageId': 869630, 'similarity': '40.65'}, {'imageId': 709693, 'similarity': '40.58'}, {'imageId': 817638, 'similarity': '40.50'}, {'imageId': 716985, 'similarity': '40.25'}, {'imageId': 564771, 'similarity': '40.17'}, {'imageId': 851161, 'similarity': '40.10'}, {'imageId': 580435, 'similarity': '40.03'}, {'imageId': 928875, 'similarity': '40.00'}, {'imageId': 775113, 'similarity': '39.93'}, {'imageId': 827685, 'similarity': '39.82'}, {'imageId': 843015, 'similarity': '39.72'}, {'imageId': 658483, 'similarity': '39.68'}, {'imageId': 822411, 'similarity': '39.42'}, {'imageId': 663101, 'similarity': '39.26'}, {'imageId': 680329, 'similarity': '39.24'}, {'imageId': 859585, 'similarity': '39.20'}, {'imageId': 789022, 'similarity': '39.06'}, {'imageId': 537471, 'similarity': '39.00'}, {'imageId': 898023, 'similarity': '38.95'}, {'imageId': 866630, 'similarity': '38.77'}, {'imageId': 679900, 'similarity': '38.55'}, {'imageId': 556711, 'similarity': '38.51'}, {'imageId': 666701, 'similarity': '38.47'}, {'imageId': 933191, 'similarity': '38.44'}, {'imageId': 938204, 'similarity': '38.39'}, {'imageId': 907738, 'similarity': '38.34'}, {'imageId': 910243, 'similarity': '38.29'}, {'imageId': 595638, 'similarity': '38.20'}, {'imageId': 622850, 'similarity': '38.19'}, {'imageId': 763131, 'similarity': '38.07'}]]`
> 
> Next, I added the duplicate row with ID `10011261403` to the collection again, bringing the collection size to `500,002`. When I conducted another ANN search for that vector with top-k set to 50, it only returned one of the duplicate vectors, not both.
> 
> `results [[{'imageId': 10011261403, 'similarity': '100.00'}, {'imageId': 686648, 'similarity': '45.58'}, {'imageId': 737397, 'similarity': '45.04'}, {'imageId': 643527, 'similarity': '43.79'}, {'imageId': 741502, 'similarity': '43.72'}, {'imageId': 528172, 'similarity': '43.18'}, {'imageId': 544907, 'similarity': '43.12'}, {'imageId': 919014, 'similarity': '42.36'}, {'imageId': 968839, 'similarity': '42.22'}, {'imageId': 578254, 'similarity': '42.21'}, {'imageId': 878153, 'similarity': '41.68'}, {'imageId': 729624, 'similarity': '41.62'}, {'imageId': 688188, 'similarity': '41.62'}, {'imageId': 826066, 'similarity': '41.45'}, {'imageId': 791482, 'similarity': '41.41'}, {'imageId': 810394, 'similarity': '41.25'}, {'imageId': 540039, 'similarity': '41.23'}, {'imageId': 639523, 'similarity': '40.80'}, {'imageId': 695039, 'similarity': '40.77'}, {'imageId': 765151, 'similarity': '40.76'}, {'imageId': 869630, 'similarity': '40.65'}, {'imageId': 709693, 'similarity': '40.58'}, {'imageId': 817638, 'similarity': '40.50'}, {'imageId': 716985, 'similarity': '40.25'}, {'imageId': 564771, 'similarity': '40.17'}, {'imageId': 851161, 'similarity': '40.10'}, {'imageId': 580435, 'similarity': '40.03'}, {'imageId': 928875, 'similarity': '40.00'}, {'imageId': 775113, 'similarity': '39.93'}, {'imageId': 827685, 'similarity': '39.82'}, {'imageId': 843015, 'similarity': '39.72'}, {'imageId': 658483, 'similarity': '39.68'}, {'imageId': 822411, 'similarity': '39.42'}, {'imageId': 663101, 'similarity': '39.26'}, {'imageId': 680329, 'similarity': '39.24'}, {'imageId': 859585, 'similarity': '39.20'}, {'imageId': 789022, 'similarity': '39.06'}, {'imageId': 537471, 'similarity': '39.00'}, {'imageId': 898023, 'similarity': '38.95'}, {'imageId': 866630, 'similarity': '38.77'}, {'imageId': 679900, 'similarity': '38.55'}, {'imageId': 556711, 'similarity': '38.51'}, {'imageId': 666701, 'similarity': '38.47'}, {'imageId': 933191, 'similarity': '38.44'}, {'imageId': 938204, 'similarity': '38.39'}, {'imageId': 907738, 'similarity': '38.34'}, {'imageId': 910243, 'similarity': '38.29'}, {'imageId': 595638, 'similarity': '38.20'}, {'imageId': 622850, 'similarity': '38.19'}, {'imageId': 763131, 'similarity': '38.07'}]]`
> 
> Does this mean that Milvus only performs deduplication for the final results, rather than within the collection rows themselves, as illustrated by my example?
> 
> ### Expected Behavior
> The collection size should **remain unchanged** when upserting duplicate rows.
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> with this config:
> 
> ```
>     def create_collection(self):
>         """
>         Create collection using fields. It has a primary key.
> 
>         Args:
> 
>         Returns:
> 
>         """
>         __pk_field = FieldSchema(
>             name=self.__id_field_name,
>             dtype=DataType(self.__id_field_value),
>             is_primary=True,
>             auto_id=False,
>             description="primary key",
>         )
>         __vector_field = FieldSchema(
>             name=self.__vector_field_name,
>             dtype=DataType(self.__vector_field_value),
>             dim=self.__dim,
>         )
>         if self.__use_partition_key is True:
>             __category_field = FieldSchema(
>                 name=self.__category_field_name,
>                 dtype=DataType(self.__category_field_value),
>                 max_length=self.__max_length_category,
>                 is_partition_key=True,
>             )
>             schema = CollectionSchema(
>                 fields=[
>                     __pk_field,
>                     __vector_field,
>                     __category_field,
>                 ],
>                 enable_dynamic_field=True,
>                 description="collection with partition key",
>             )
>             self.__collection = Collection(
>                 name=self.__collection_name,
>                 schema=schema,
>                 partition_key_field=self.__category_field_name,
>             )
>         else:
>             schema = CollectionSchema(
>                 fields=[
>                     __pk_field,
>                     __vector_field,
>                 ]
>             )
>             self.__collection = Collection(name=self.__collection_name, schema=schema)
>         MilvusCollection.__logger.info(f"collection {self.__collection_name} created")
>         replicas = self.__collection.get_replicas()
>         MilvusCollection.__logger.info(f"replicas {replicas}")
>         return
> ```
> 
> and upserting:
> 
> ```
> mutation_result = self.__collection.upsert(
>                     data=data_collection,
>                 )
> ```

If you just use same PK and trying to overwrite, the answer is maybe.

Right now milvus don't guarantee the new enetity with PK will overwrite the older one.
You have to use upsert explicitly.

**Comment by xiaofan-luan** [comment]
upsert do a delete + insert so the old data will be guarantee to be deleted

**Comment by barzan-hayati** [comment]
> the old data will be guarantee to be deleted

I don't observe any old data in the search results, yet the `collection.num_entities` increases each time I perform an upsert operation for a specific primary key.

**Comment by xiaofan-luan** [comment]
1. sometimes the older data will be overwritten, but not always. for example older data is in top10 but newer vector is not.
2. collection.num_entities won't be decrease unless compaction happens, even if you do delete. this is just a meta used for estimation. use count so you can get more accurate result

**Comment by yanliang567** [comment]
please check [here](https://milvus.io/docs/get-and-scalar-query.md#Use-Advanced-Operators) for count(*) to get an accurate entities in a loaded collection.
