### ISSUE TITLE
[Bug]: Large growing segment

### ISSUE THREAD

**Issue by bigsheeper** [milvus-io/milvus#37387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4&2.5&master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When inserts happen too quickly, segments may not have time to seal, resulting in the allocation of segments with `maxRows` (2.5GB). However, the ideal segment size should be `maxRows * sealProportion`.
![img_v3_02g4_4ab2a14f-bf08-497d-b060-d252ccb44d1g](https://github.com/user-attachments/assets/10ea3d31-9ffc-4021-9178-ddbba2e1601d)
![img_v3_02g4_e0188e62-2790-445a-8b37-6c2b23da049g](https://github.com/user-attachments/assets/292dbb73-5fc5-4e25-825a-d6e40f17772e)

**Comment by bigsheeper** [comment]
/assign @yongpengli-z 
please help to verify

**Comment by yongpengli-z** [comment]
Verification passed.
![img_v3_02h0_c4733ed5-77e8-48be-b9dc-6dec48f278eg](https://github.com/user-attachments/assets/14f485d6-3643-4e81-aa78-b94acbf8572c)
![img_v3_02h0_e8895970-bcee-4315-a336-c457c1cdc4bg](https://github.com/user-attachments/assets/cbfa546c-6f62-45a5-962d-3bcdc7c71fbd)
