### ISSUE TITLE
[BUG] sdk_simple return empty result

### ISSUE THREAD

**Issue by cydrain** [milvus-io/milvus#374]
**Describe the bug**
sdk_simple always return empty result

**Steps/Code to reproduce behavior**
1. start Milvus
2. run sdk_simple

**Expected behavior**
should return valid result

**Environment details**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Comment by fishpenguin** [comment]
Already fixed by commit [0aa90ea](https://github.com/milvus-io/milvus/commit/cd80cdba02f489f68dc56980baa07e517ec50916)
