### ISSUE TITLE
[Bug]: Milvus fails to register components to etcd, which causes milvus not healthy

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#37402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20241104-f54cf418-amd64
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):
```

### Current Behavior

milvus is not running healthy
```
yanliang-mas-etcd-0                                               1/1     Running            0                 24m     10.104.25.193   4am-node30   <none>           <none>
yanliang-mas-milvus-standalone-5c44d54476-fdmbb                   0/1     Running            0                 22m     10.104.25.212   4am-node30   <none>           <none>
yanliang-mas-minio-5f56fd8764-p5s94                               1/1     Running            0                 24m     10.104.25.192   4am-node30   <none>           <none>
```

### Expected Behavior

running healthy

### Steps To Reproduce

```markdown
delpey milvus with that tag
```

### Milvus Log

logs from milvus:
![image](https://github.com/user-attachments/assets/36a431fc-7b29-46fa-b078-1a4d4ee0fd24)
![image](https://github.com/user-attachments/assets/19e60828-9f76-4984-a1f2-e844d6be697d)
logs from etcd:
![image](https://github.com/user-attachments/assets/6baf2e35-bc3c-4398-80ab-4edbd190d49e)

**Comment by congqixia** [comment]
```
[INFO] [rootcoord/service.go:154] ["RootCoord listen on"] [address="[::]:53100"] [port=53100]
```

Looks like the IP address returned from lib is an IPv6 address and not readable into session
working on why this happened

**Comment by yanliang567** [comment]
I can deploy milvus standalone successfully now with the pr https://github.com/milvus-io/milvus/pull/37418

**Comment by congqixia** [comment]
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI(new)/detail/master/173/pipeline
last nightly run started successfully after #37445 merged, could you please verify
/assign @yanliang567

**Comment by yanliang567** [comment]
verified
