### ISSUE TITLE
[Feature]: Enhance CPUs Utilization

### ISSUE THREAD

**Issue by barzan-hayati** [milvus-io/milvus#37455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I’ve attached some screenshots showing the CPU usage during indexing and searching, and it appears that Milvus isn't fully utilizing all the CPUs , as it never exceeds `55%` usage. Is that correct? Do you have any plans to address this in the future?

![Screenshot from 2024-10-06 15-50-36](https://github.com/user-attachments/assets/79357dc1-6f7d-4c0f-8a73-b98d70cf6c61)

![Screenshot from 2024-10-06 15-50-11](https://github.com/user-attachments/assets/1b7cc49d-7a08-43dd-9e13-f744dc2228b8)

![Screenshot from 2024-10-06 15-50-06](https://github.com/user-attachments/assets/cbab0bc1-0fa3-4e85-a685-0723d7ec3406)

**Comment by xiaofan-luan** [comment]
don't quite understand what you doing here. why there are so many milvus standalone process?
<img width="1107" alt="image" src="https://github.com/user-attachments/assets/bbe8149c-919a-4aa5-9c15-3197e20efa8e">

and also the standalone cpu usage seems to be already high 4800%,  are u saying u are running on 96 core machine but it can use up all the cpu?

Questions:
1. how much data do you have? what dimension?
2. how many QPS you are expecting? and what is the idea latency? 
3. What index are u using? What's the current QPS you get?
4. How many client do you have? Do you have enough pressure? What happened if you increase concurrency?
5. could you create a pprof to futher analysis?

there might be some bottlenecks for running milvus on super huge machines(Typically we do 16/32/64 core). We don't have 96 core machines in house. if you can offer us a pprof we can help on profing.

an e-meet is also welcomed, connect me at james.luan@zilliz.com and I can help you on investigating the issue
