### ISSUE TITLE
[BUG] Can we create the same partition name under different tables?

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#375]
Consider the situation, we have different tables in our db, maybe each table has its owner, the partition name conflict may happen.
But we cannot support with current arch

```
drwxr--r-- 2 root root 4096 Nov 16 07:33 partition/
drwxr--r-- 2 root root 4096 Nov 16 07:33 test_add_NOWlTbUV/
```

**Comment by yhmo** [comment]
Similar to MySQL and Postgresql, partition is internally a table, partition name actually is a table name, it must be unique.

**Comment by yhmo** [comment]
Partition name actually is an unique table name. Two partitions with same partition name is not allowed, even they belong to different tables.
