### ISSUE TITLE
Count entities not correct occasionally if run in parallel

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#3754]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
___________ TestDeleteBase.test_insert_same_ids_after_delete_binary ____________
[gw2] linux -- Python 3.6.8 /usr/local/bin/python3

self = <test_delete.TestDeleteBase object at 0x7f1b442f8278>
connect = <milvus.client.stub.Milvus object at 0x7f1b7a50c128>
binary_id_collection = 'test_delete_RwSgJokC'

    def test_insert_same_ids_after_delete_binary(self, connect, binary_id_collection):
        '''
        method: add entities, with the same id and delete the ids
        expected: status DELETED, all id deleted
        '''
        insert_ids = [i for i in range(nb)]
        ids = connect.insert(binary_id_collection, binary_entities, insert_ids)
        connect.flush([binary_id_collection])
        delete_ids = [ids[0], ids[-1]]
        status = connect.delete_entity_by_id(binary_id_collection, delete_ids)
        assert status
        new_ids = connect.insert(binary_id_collection, binary_entity, [ids[0]])
        assert new_ids == [ids[0]]
        connect.flush([binary_id_collection])
        res_count = connect.count_entities(binary_id_collection)
>       assert res_count == nb - 1
E       assert 1201 == 1199
E         -1201
E         +1199

entity/test_delete.py:232: AssertionError
```
**Steps/Code to reproduce behavior**
checkout `milvus git:(parallel_case)`
run pytest with params: `-n 4`

**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
Multi-clients do insert/delete at the same time, the operations sequence is random, the result could not be same.

**Comment by scsven** [comment]
@del-zhenwu Cannot reproduce, milvus logs is needed. And please make sure there is ONLY ONE CLIENT insert/delete a collection at the same time. The behavior of multi-client insert/delete the same collection is undefined.

**Comment by del-zhenwu** [comment]
try to produce with cmd `pytest -n 4`

**Comment by del-zhenwu** [comment]
can not be reproduced
