### ISSUE TITLE
[Bug]: non-stop repeated segment compaction

### ISSUE THREAD

**Issue by zhengbuqian** [milvus-io/milvus#37549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
```

### Current Behavior

Used scripts in https://pastebin.com/8KLQ8WyT, to simply insert 200M data. After compaction, 5 segments are left, each with ~400k rows. Then those 5 segments compact indefinitely.

See birdwatcher segment results here: https://pastebin.com/aZ6M7Y2U

Segment A, B, C, D, E was compacted inito A1, B1, C1, D1, E1, then A2, B2, C2, D2, E2, ... Each time compaction happens the old index was dropped and the new index was recreated. 

Likely due to: the compaction trigger thought A+B can be merged into a larger segment say F, but the actual compactor thought F would be too large and simply writes A and B to A1 and B1 unchanged.

**Comment by XuanYang-cn** [comment]
/assign @zhengbuqian
Should be fix, please help verify
