### ISSUE TITLE
[Bug]: [null & default] An occasional pulsar crash occurs when search requests continue to be made in gradient increment concurrent mode

### ISSUE THREAD

**Issue by qixuan0212** [milvus-io/milvus#37546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20241106-87147743-amd64
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar  
- SDK version(e.g. pymilvus v2.0.0rc2): 2.5.0rc99
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Gradient Increase concurrency mode (10/20/40) Continuously sends search requests for 6 hours，pulsar crash：
`2024-11-06T18:06:37,078+0000 [pulsar-io-4-73] WARN  org.apache.pulsar.broker.service.ServerCnx - [/10.102.7.133:34334][persistent://public/default/by-dev-rootcoord-dml_10][datanode-5-by-dev-rootcoord-dml_10_453741133122427421v0-false] Failed to create consumer: consumerId=1206, Subscription is fenced`
![WechatIMG681](https://github.com/user-attachments/assets/7bf33381-edb3-46a8-ae4e-b579340da11d)

[https://grafana-devops.zilliz.cc/d/uLf5cJ3Gzx/milvus2-0?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=chaos-testing&var-instance=default-none-perf-oagsp&var-collection=All&var-app_name=milvus&from=1730901371748&to=1730923860559](url)

### Expected Behavior

Search successfully

### Steps To Reproduce

```markdown
1. Set the nullable ratio to 10%, 20%, and 50%
2. Send search requests in gradient increment mode (10/20/40), each gradient lasting 20 minutes
```

### Milvus Log

[https://grafana-4am.zilliz.cc/explore?orgId=1&panes=%7B%22bGP%22:%7B%22datasource%22:%22vhI6Vw67k%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcluster%3D%5C%22devops%5C%22,namespace%3D%5C%22chaos-testing%5C%22,pod%3D~%5C%22default-none-perf-oagsp.%2A%5C%22%7D%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22vhI6Vw67k%22%7D%7D%5D,%22range%22:%7B%22from%22:%221730916270246%22,%22to%22:%221730916397213%22%7D%7D%7D&schemaVersion=1](url)

**Comment by smellthemoon** [comment]
<img width="1195" alt="image" src="https://github.com/user-attachments/assets/41ed8d14-b2fa-4fd1-b00b-9e9fc763825f">
<img width="1352" alt="image" src="https://github.com/user-attachments/assets/791a1b25-eb10-418b-a33d-865b7b45e9c5">
may related with #37433 , could you help to do the test again in the latest image? thx @qixuan0212

**Comment by xiaofan-luan** [comment]
@smellthemoon 
what is this subscription fenced mean?

**Comment by liliu-z** [comment]
> Failed to create consumer: consumerId=1206, Subscription is fenced

Looks like a double consuming

**Comment by liliu-z** [comment]
> https://grafana-devops.zilliz.cc/d/uLf5cJ3Gzx/milvus2-0?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=chaos-testing&var-instance=default-none-perf-thdnl&var-collection=All&var-app_name=milvus&from=1731237868777&to=1731265210549

Any concern for this? The reason of the long/failed queries is that the collection was still under loading.

**Comment by qixuan0212** [comment]
> > https://grafana-devops.zilliz.cc/d/uLf5cJ3Gzx/milvus2-0?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=chaos-testing&var-instance=default-none-perf-thdnl&var-collection=All&var-app_name=milvus&from=1731237868777&to=1731265210549
> 
> @qixuan0212 Any concern for this? The reason of the long/failed queries is that the collection was still under loading.

No query or search request is invoked manually before the load completes. How is the query request triggered here? @liliu-z

**Comment by liliu-z** [comment]
> > > https://grafana-devops.zilliz.cc/d/uLf5cJ3Gzx/milvus2-0?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=chaos-testing&var-instance=default-none-perf-thdnl&var-collection=All&var-app_name=milvus&from=1731237868777&to=1731265210549
> > 
> > 
> > @qixuan0212 Any concern for this? The reason of the long/failed queries is that the collection was still under loading.
> 
> No query or search request is invoked manually before the load completes. How is the query request triggered here? @liliu-z

Milvus will not trigger query automatically. Plz try to reproduce this.

**Comment by qixuan0212** [comment]
I got it. When I use attu to view the collection information on the interface during the collection load process, the query request will be triggered
![image](https://github.com/user-attachments/assets/b984fdf5-942c-4b8f-b8f4-b09abbac6713)
