### ISSUE TITLE
MySQL version described in doc is wrong.

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#3758]
**Please state your issue using the following template and, most importantly, in English.**

**Location of incorrect documentation**
https://milvus.io/cn/docs/v0.10.2/data_manage.md

**Describe the problems or issues found in the documentation**

The WARING says 
> WARNING
>In CentOS, Milvus does not support MySQL 8.0 or higher.

And the doc recommends pulling the **latest** image of MySQL( which is **higher than 8.0**)
> $ docker pull mysql:latest

1. The doc says 8.0 is unavailable for CentOS but still recommend to pull the latest version( > 8.0)(Milvus docker image is based on CentOS)
2. And the users may think they can use MySQL 8.0 or higher on Ubuntu (or other Linux OS)

### Moreover, there are some misleading on the doc.

- First of all, we recommend using **MySQL 5.7**, no matter what Linux OS is,  cause milvus is fully tested under **MySQL 5.7**, so it's recommended to pull version 5.7 of MySQL as below:

```shell
$ docker pull mysql:5.7
```
- Secondly, it's not recommended to instruct a user downloading a **latest** version of some software, cause latest version of a software may change unnoticedly and bugs may occur. So it's recommended that **every software should be attached a specific version** when introduced to the users rather than using the latest version.

**Steps taken to verify documentation is incorrect**
List any steps you have taken:

**Suggested fix for documentation**

Change all `mysql:latest` to `mysql:5.7`

**Comment by scsven** [comment]
It's a serious mistake, `latest` label should not be used in this document. By the way, Milvus is tested with MySQL 5.7, so the recommended version of MySQL is 5.7

@PahudPlus Please update commands as below:

```
 docker pull mysql:latest
```
change to 
```
 docker pull mysql:5.7
```

**Comment by PahudPlus** [comment]
Issue fixed. See: https://www.milvus.io/docs/v0.10.3/data_manage.md.
