### ISSUE TITLE
[Bug]: [new_indexes] It does not report error when creating new HNSW PRQ index with invalid refine type

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#37587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20241107-994f52fa-amd64
- Deployment mode(standalone or cluster): 2.5.0rc107
- MQ type(rocksmq, pulsar or kafka):    all
- SDK version(e.g. pymilvus v2.0.0rc2): both
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

It does not report error when creating new HNSW PRQ index with invalid refine type

### Expected Behavior

Report error when creating new HNSW PRQ index with invalid refine type

### Steps To Reproduce

```python
    @pytest.mark.tags(CaseLabel.L1)
    def test_create_hnsw_prq_index_invalid_refine_type(self, invalid_refine_type):
        """
        target: test create hnsw_prq index with all allowed parameters including refine parameters
        method: create index with only one field name
        expected: create successfully
        """
        collection_w = self.init_collection_general(prefix, is_index=False)[0]
        index_params = {"index_type": ct.HNSW_PRQ, "metric_type": "L2",
                        "params": {"m": 32, "nbits": 8, "nrq": 6, "refine_type": invalid_refine_type}}
        collection_w.create_index(default_field_name, index_params,
                                  check_task=CheckTasks.err_res,
                                  check_items={"err_code": 1100,
                                               "err_msg": "invalid refine type: invalid parameter"
                                                          "[expected=valid index params][actual=invalid index params]"})
```

### Milvus Log

https://grafana-4am.zilliz.cc/explore?orgId=1&panes=%7B%22gmL%22:%7B%22datasource%22:%22vhI6Vw67k%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcluster%3D%5C%22devops%5C%22,namespace%3D%5C%22chaos-testing%5C%22,pod%3D~%5C%22test-null-master-cjqsw.%2A%5C%22%7D%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22vhI6Vw67k%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1

### Anything else?

collection name: index_KTMDxtxm

**Comment by binbinlv** [comment]
It could report error for "FAISS_HNSW_SQ" index:
```
code=1100, message=invalid refine type type: invalid parameter[expected=valid index params][actual=invalid index params]
```

It does not report error for "FAISS_HNSW_PQ" and "FAISS_HNSW_PRQ".

**Comment by binbinlv** [comment]
working on verification.

**Comment by binbinlv** [comment]
Verified and fixed:

milvus: master-20241114-1304b405-amd64
pymilvus: 2.5.0rc119

results:
```
invalid refine type type: invalid parameter[expected=valid index params][actual=invalid index params]
```

**Comment by binbinlv** [comment]
But the type in error "invalid refine type type" is duplicated?

**Comment by alexanderguzhva** [comment]
@binbinlv this typo is fixed in https://github.com/zilliztech/knowhere/pull/945

**Comment by binbinlv** [comment]
working on verification.

**Comment by binbinlv** [comment]
Verified and fixed:

milvus: master-20241115-d1596297-amd64
pymilvus: 2.5.0rc121

results:
```
invalid refine type : invalid, optional types are [sq6, sq8, fp16, bf16, fp32, flat]: invalid parameter[expected=valid index params][actual=invalid index params]
```
