### ISSUE TITLE
[Bug]: Missing collection and index information after upgrading from Milvus v2.1.4 to v2.3.x

### ISSUE THREAD

**Issue by philic** [milvus-io/milvus#37614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.1.4
- Deployment mode(standalone or cluster): Cluster
- MQ type(rocksmq, pulsar or kafka): Pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.4.3
- OS(Ubuntu or CentOS): Ubuntu
- GPU: None
```

### Current Behavior

1. I followed the upgrade instructions at https://milvus.io/docs/upgrade_milvus_cluster-helm.md , using the command:
```
./migrate.sh ... -s 2.1.4 -t 2.2.0 --w milvusdb/milvus:v2.2.0 -o migrate
```
Note: As upgrading directly from Milvus 2.1.4 to 2.3.x results in an error, I set the target version to 2.2.0.

2. Although the migration script indicated a successful upgrade, the `rootCoord` component failed to start, resulting in `CrashLoopBackOff`.

3. I then manually updated the container image to version 2.3.21, which allowed all pods to start successfully. However, no segments were loaded in the `queryNode`.

4. After some investigation, collection and index information seemed to be missing:
```
pymilvus.exceptions.PrimaryKeyException: <PrimaryKeyException: (code=1, message=Schema must have a primary key field.)>
```

**Comment by yanliang567** [comment]
there is a breaking change when upgrading from 2.1.x to 2.2.0, so I believe you have to first upgrade to 2.2.0 successfully before you can upgade to 2.3 or 2.4. 
could you please offer milvus logs when upgading to 2.2.0? @philic 
/assign @philic 

/assign @LoveEachDay 
any suggestion?
