### ISSUE TITLE
[Bug]: When function is added in schema, the insert interface will call describe collection, resulting in a describe collection call every time an insert is performed.

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#37622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):2.5.0rc118
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/user-attachments/assets/4275ef18-cf91-4076-9960-28a52e59adf8)

### Expected Behavior

collection info should be cached in client

### Milvus Log

```
from pymilvus import (connections, Collection, FieldSchema, CollectionSchema, DataType, FunctionType, list_collections,
                      Function)
from loguru import logger
import time
from faker import Faker
faker = Faker()
connections.connect(host = "10.104.16.127")

collection_name = "demo_collection"
analyzer_params = {
    "tokenizer": "standard"
}
fields = [
    FieldSchema(name="id", dtype=DataType.INT64, is_primary=True),
    FieldSchema(name="text", dtype=DataType.VARCHAR, max_length=25536,
                enable_analyzer=True, analyzer_params=analyzer_params, enable_match=True),
    FieldSchema(name="sparse", dtype=DataType.SPARSE_FLOAT_VECTOR),
]
schema = CollectionSchema(fields=fields, description="beir test collection")
bm25_function = Function(
    name="text_bm25_emb",
    function_type=FunctionType.BM25,
    input_field_names=["text"],
    output_field_names=["sparse"],
    params={},
)
schema.add_function(bm25_function)
collection = Collection(collection_name, schema)

collection.create_index(
    "sparse",
    {
        "index_type": "SPARSE_INVERTED_INDEX",
        "metric_type": "BM25",
        "params": {
            "bm25_k1": 1.5,
            "bm25_b": 0.75,
        }
    }
)
collection.load()
logger.info("Collection setup completed successfully")

batch_size = 10
data = [
    {
        "id": int(time.time() * (10 ** 6)),
        "text": faker.text(max_nb_chars=300),
    }
    for _ in range(batch_size)
]
for i in range(1000):
    collection.insert(data)
    print(f"Inserting {batch_size} vectors")

```

**Comment by xiaofan-luan** [comment]
mark this as critical

**Comment by yanliang567** [comment]
also reproduce to schema without Function defined

**Comment by zhengbuqian** [comment]
/unassign

/assign @XuanYang-cn 

assigning to XuanYang-cn as this is also reproduced when without Function

**Comment by yanliang567** [comment]
/assign @zhengbuqian 
sorry for false alarm, it only reproduces with Function.

**Comment by zhengbuqian** [comment]
https://github.com/milvus-io/pymilvus/blob/5ec0a601bb6683c787d9bdb88ee35f1c49a49586/pymilvus/client/grpc_handler.py#L484-L516

`_prepare_row_insert_request` checks if schema is dict, if not it tries to get the schema from the server. 

when `insert_rows` calls `_prepare_row_insert_request`, schema was not passed in the argument list. actually if a timeout is provided to `insert_rows`, `timeout` will be passed to the `schema` argument of `_prepare_row_insert_request`.

That is why `if not isinstance(schema, dict):` is always true, and pymilvus always call `describe_collection` RPC of each insert.

**Comment by XuanYang-cn** [comment]
@yanliang567 Seems insert by rows always will describe collection
/assign @zhuwenxing
/unassign
Please help verify, THX

**Comment by zhuwenxing** [comment]
verified with 2.5.0rc121

![image](https://github.com/user-attachments/assets/0ea8e143-a56b-4979-bce9-936c06e9d000)
