### ISSUE TITLE
Support show Milvus in WAL recovery status

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#3763]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Currently the grpc/web server started after the WAL recovery, so how can we know the process of WAL recovery without grpc/http interfaces.
Some tools or another interfaces are needed.

**Steps/Code to reproduce behavior**

**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
WAL recovery happens before grpc service initialize. So, once you can connect to milvus server, the wal recovery has been finished.

**Comment by yhmo** [comment]
Once debug.log shows "End wal recovery", that means wal recovery has been finished.

**Comment by JinHai-CN** [comment]
Connected with #3690
