### ISSUE TITLE
[Bug]: GetIndexInfos RPC is called too frequently

### ISSUE THREAD

**Issue by bigsheeper** [milvus-io/milvus#37634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4&master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The `IndexChecker` in querycoord calls the `GetIndexInfos` RPC too frequently.
![image](https://github.com/user-attachments/assets/60be3cf5-9cce-4acd-acc8-583cf7ab3f39)

### Expected Behavior

We should batch segments into a single `GetIndexInfos` RPC call to avoid frequent RPCs. On the other hand, the frequency of the index checker (currently every 10 seconds) may could be reduced.
https://github.com/milvus-io/milvus/blob/30d396f476598a204c4e77ad4de85495ce51d241/internal/querycoordv2/checkers/index_checker.go#L135-L141

**Comment by bigsheeper** [comment]
related to: https://github.com/milvus-io/milvus/issues/37630

**Comment by xiaofan-luan** [comment]
@bigsheeper 

sems that we can remove the broker since datacoord and indexcoord are now merged?

**Comment by bigsheeper** [comment]
> @bigsheeper
> 
> sems that we can remove the broker since datacoord and indexcoord are now merged?

@xiaofan-luan These GetIndexInfos invokes are from querycoord.
