### ISSUE TITLE
[Bug]: Metrics consume a lot of memory

### ISSUE THREAD

**Issue by bigsheeper** [milvus-io/milvus#37636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When there are a large number of segments, the metrics consume a lot of memory.
![image](https://github.com/user-attachments/assets/8b9df831-7c91-4273-9804-af43ee062794)

### Expected Behavior

Segment-level metrics are unnecessary; collection-level metrics are sufficient.
![image](https://github.com/user-attachments/assets/dc2f186f-1ce2-4221-becb-c119e19cb8bf)

**Comment by bigsheeper** [comment]
related to: https://github.com/milvus-io/milvus/issues/37630

**Comment by xiaofan-luan** [comment]
probbaly we don't need segment level tag?

**Comment by bigsheeper** [comment]
> probbaly we don't need segment level tag?

Yes, I will remove it.
