### ISSUE TITLE
[Bug]: Balance channel may stuck at increasing replica number case

### ISSUE THREAD

**Issue by weiliu1031** [milvus-io/milvus#37640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4 and mater
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

cause balance channel will wait until new delegator becomes serviceable, but new delegator need to sync target version then becomes serviceable, and sync target version need to be wait all replica load done. so if increasing replica number and balance channel happens at same time, logic dead lock occurs.

**Comment by xiaofan-luan** [comment]
@weiliu1031 
how do we reproduce and verify this?
