### ISSUE TITLE
[Bug]: Connecting to Milvus with authentication, receiving gRPC error

### ISSUE THREAD

**Issue by strugc** [milvus-io/milvus#37714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Set common.security.authorizationEnabled to true in the Milvus configuration file milvus.yaml

Error code:
raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAUTHENTICATED
        details = "auth check failure, please check username and password are correct"
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"auth check failure, please check username and password are correct", grpc_status:16, created_time:"2024-11-15T07:55:36.6657145+00:00"}"

Try setting reset password 
common:
    security:
        superUsers: root, foo

Restart docker, Running the script still reports an error gRPC

from pymilvus import MilvusClient
client = MilvusClient(
    uri='http://locahost:19530', 
    token="root:Milvus"
) 
print(client.has_collection("test_collection"))

**Comment by SimFG** [comment]
Which version of milvus and pymilvus are you using? Can you also show me all the values ​​under common.security?

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> _No response_
> 
> ### Current Behavior
> Set common.security.authorizationEnabled to true in the Milvus configuration file milvus.yaml
> 
> Error code: raise _InactiveRpcError(state) # pytype: disable=not-instantiable grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with: status = StatusCode.UNAUTHENTICATED details = "auth check failure, please check username and password are correct" debug_error_string = "UNKNOWN:Error received from peer {grpc_message:"auth check failure, please check username and password are correct", grpc_status:16, created_time:"2024-11-15T07:55:36.6657145+00:00"}"
> 
> Try setting reset password common: security: superUsers: root, foo
> 
> Restart docker, Running the script still reports an error gRPC
> 
> from pymilvus import MilvusClient client = MilvusClient( uri='http://locahost:19530', token="root:Milvus" ) print(client.has_collection("test_collection"))
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> _No response_
> 
> ### Anything else?
> _No response_

you need later milvus version, better to be 2.4.15.

Older milvus don't support token like user:passwod but you need to pass username and password seperatly
