### ISSUE TITLE
[Bug]:compile the standalone version of milvus in BClinux8.8

### ISSUE THREAD

**Issue by zs001122** [milvus-io/milvus#37716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.14.5
- Deployment mode(standalone or cluster):standalone 
- OS(Ubuntu or CentOS): BClinux8.8-kvm-x86_64
```

### Current Behavior

![image](https://github.com/user-attachments/assets/1210ea01-3f78-4756-9770-2c27d1eed418)

### Steps To Reproduce

```markdown
1. Run the./scripts/install_deps.sh command under milvus
2.make-j4 (Tried to add BUILD_WITHOUT_AZURE=ON before core_builh.sh, still not working)
```

**Comment by xiaofan-luan** [comment]
@zs001122 
this seems to be not a error
simply some warnings here.

**Comment by Presburger** [comment]
@zs001122 Hello, may I ask if you have Conan installed in your environment? Conan requires python3.8 or python3.9
