### ISSUE TITLE
Add support run on FPGA for milvus

### ISSUE THREAD

**Issue by jackhouchina** [milvus-io/milvus#3773]
**Please state your issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**
due to the high Parallel capability and large memory in  fpga , I want to run milvus on FPGA , so i suggest to add a feature to support it in milvus, In this model ,currently, we can train index use cpu or gpu , and search on fpga。

**Describe the solution you'd like**
 **solution** :
if we want to support run on fpga, we should add some feature, detail as below,
1 . add a compile option for fpga, we can build a fpga version, such as ./build.sh -a -t Debug
2 .add some fpga config option in config file , such as enable/disable  
3 . implement search algorithm on fpga under this folder(milvus/core/src/index/knowhere/knowhere/index/vector_index/fpga)
4 .implement fpga index cache manage.
5 .implement fpga resource manage
6 .and so on

**Describe alternatives you've considered**
no

**Additional context**
copy Index from cpu to FPGA:
void
FPGAIVFPQ::CopyIndexToFpga(){

    auto fpgaIndex = FpgaIndex::GetInstance();
    auto ivf_index = static_cast<faiss::IndexIVFPQ*>(index_.get());
    ivf_index->make_direct_map();
    fpgaIndex ->setIndex(ivf_index);
    fpgaIndex >CopyIndexToFPGA();  
}
void
FPGAIVFPQ::QueryImpl(int64_t n, const float* data, int64_t k, float* distances, int64_t* labels, const Config& config) {

    std::lock_guard<std::mutex> lk(mutex_);
   try{ 

        auto params = GenParams(config);
         int nprobe =params->nprobe;
        LOG_ENGINE_DEBUG_ <<"nprobe:"<<nprobe<<"n:"<<n<<"k:"<<k;
        auto fpgaIndex = fpga::FpgaInst::GetInstance();
        vector<faiss::Index::idx_t> vlabels(n*k);
        vector<float> vdistances(n*k);
        auto t0 = Elapsed();
        fpgaIndex ->BatchAnnQuery(nprobe,n,(float*)data, k, vlabels, vdistances);
        auto t1= Elapsed();
        LOG_ENGINE_DEBUG_ <<" vlabels size:"<<vlabels.size()<<"search time:"<<t1-t0; 
        auto elems = n * k;
        size_t p_id_size = sizeof(int64_t) * elems;
        size_t p_dist_size = sizeof(float) * elems;      
        memcpy(distances,vdistances.data(),p_dist_size);
        memcpy(labels,vlabels.data(),p_id_size);
   }catch(...)
   {

   }
  }

**Comment by shengjun1985** [comment]
Done in 0.10.4
