### ISSUE TITLE
[Enhancement]: optimize  brurtforce search implement

### ISSUE THREAD

**Issue by cqy123456** [milvus-io/milvus#37798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

task:

- [x]  remove the bitset copy if row count % 8 != 0;

- [x]  remove knowhere default id and outer id convert；

- [ ] knowhere do the real fp16/bf16 search, get rid of memory copy

**Comment by xiaofan-luan** [comment]
impressive improvement!
