### ISSUE TITLE
[Bug]: milvus container can't start server

### ISSUE THREAD

**Issue by TongKevin** [milvus-io/milvus#37832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.15
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.17
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 
- GPU: 
- Others: docker deployment
```

### Current Behavior

The service in the Docker container suddenly reported an error and terminated. Upon checking the logs of the Milvus container in Docker, it was found that the timezone was 8 hours behind, while the host machine's time was confirmed to be correct.
detail log below
[milvus_docker.log](https://github.com/user-attachments/files/17824306/milvus_docker.log)

**Comment by TongKevin** [comment]
tks !

but I start docker container by follow command, I can't find etcd service

`./standalone_embed.sh  start`

and how to add more resources to milvus service? where to config it ? 

standalone_embed.sh below

[standalone_embed.txt](https://github.com/user-attachments/files/17824680/standalone_embed.txt)

@yanliang567

**Comment by yanliang567** [comment]
/assign @LoveEachDay 
please help to take a look

/unassign
