### ISSUE TITLE
[Bug]: The SearchReq in the Milvus Java SDK does not provide a place to specify the ef、search_list parameter.

### ISSUE THREAD

**Issue by xiaojunxiang2023** [milvus-io/milvus#37837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
Java SDK 2.4.3
```

### **1. The `ef` parameter is only invoked during iterator-based searches.**
![cb8cc9777cd923156794e17a42faa72](https://github.com/user-attachments/assets/42d663bf-5ece-4fe9-893e-84b140e58e48)
![1154dc2c0a286f7f6f58e8fadc27fd1](https://github.com/user-attachments/assets/4a7d8104-79d2-4ed6-967a-489adb4d95d8)

### **2. The `search_list` parameter for the DiskANN index was not found.**
![0852432db92af3e4e68c19e1d575718](https://github.com/user-attachments/assets/1b810df0-46b3-43d3-9d54-8e038a0ff426)
![8fae917703ced90c1931f492b092ab6](https://github.com/user-attachments/assets/484ac431-70a7-4528-8b70-4ccf49a826bd)

### Expected Behavior

I can specify the ef、search_list parameter.

**Comment by yanliang567** [comment]
@xiaojunxiang2023 I think you can add the ef, search_list in params(), check the doc here: https://milvus.io/api-reference/java/v2.4.x/v2/Vector/searchIterator.md
/assign @xiaojunxiang2023 
/unassign

**Comment by xiaojunxiang2023** [comment]
> @xiaojunxiang2023 I think you can add the ef, search_list in params(), check the doc here: https://milvus.io/api-reference/java/v2.4.x/v2/Vector/searchIterator.md /assign @xiaojunxiang2023 /unassign

Okay, I have verified it. Based on the hints from the Proxy debug logs and a comparison with the Attu interface search, it is evident that my specified ef=351 was successfully applied.

![image](https://github.com/user-attachments/assets/cbe483dd-fbe4-42c7-8a65-c895d890d7a3)
![image](https://github.com/user-attachments/assets/d5c04419-2dca-4f42-b55f-5beec6fc5168)
