### ISSUE TITLE
[Bug]: [null & default] The query results by restful varchar_array type is dict when insert [None] data on nullable varchar_array field

### ISSUE THREAD

**Issue by qixuan0212** [milvus-io/milvus#37860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20241119-484c6b5c-amd64
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2): restful
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

insert [None] data on nullable varchar_array field, query result by restful api: varchar_array type is dict, not array
varchar_array like: 
{"fieldName": "varchar_array", "dataType": "Array", "elementDataType": "VarChar","elementTypeParams": {"max_capacity": "1024", "max_length": "256"}, "nullable": True}
query result:
`{'book_describe': None, 'book_id': 454051733008962701, 'bool': True, 'bool_array': None, 'dynamic_field_1': 1, 'int_array': None, 'json': '{"key": null}', 'text_emb': [0.08731436, 0.0019547634, 0.06909488, 0.036958225, 0.022001823, 0.006276716, 0.12887427, 0.06308743, 0.11855973, 0.037827667, 0.016843097, 0.13005646, 0.026528358, 0.0074208993, 0.14652808, 0.108544126, 0.036459364, 0.046841998, 0.04474532, 0.02500188, 0.110745996, 0.06691977, 0.13636574, 0.10028594, 0.04280329, 0.14389469, 0.14971527, 0.02986749, 0.0025921538, 0.027062379, 0.129474, 0.030709501, 0.14813851, 0.1255752, 0.105876744, 0.017549178, 0.027267559, 0.038606618, 0.067999266, 0.14265275, 0.120779485, 0.06648917, 0.077517904, 0.12316366, 0.064339235, 0.10058104, 0.01300987, 0.07705124, 0.09840901, 0.027143786, 0.050590366, 0.041322976, 0.089545116, 0.124802314, 0.031291865, 0.11632085, 0.016089993, 0.065220304, 0.08120166, 0.08243144, 0.078599244, 0.115945615, 0.11264004, 0.050223753, 0.08080398, 0.14665575, 0.0723433, 0.027183978, 0.004668991, 0.053059705, 0.14525126, 0.019798841, 0.05218402, 0.0846017, 0.107511505, 0.04444099, 0.1267866, 5.1763192e-05, 0.005751226, 0.13590373, 0.030099042, 0.13115674, 0.029896926, 0.11509683, 0.11738821, 0.07237062, 0.13017897, 0.1483169, 0.053246975, 0.09291263, 0.10510687, 0.1460436, 0.098458804, 0.116029605, 0.058047693, 0.10607036, 0.03415628, 0.13439599, 0.023431258, 0.07465251, 0.042279, 0.014087379, 0.15414023, 0.119718775, 0.029767303, 0.060280267, 0.07043855, 0.13603045, 0.086431086, 0.09803248, 0.093379535, 0.10985339, 0.0070275385, 0.118191615, 0.14004801, 0.0942584, 0.06981395, 0.10578158, 0.041218024, 0.13381706, 0.0943932, 0.09895753, 0.0722928, 0.049669366, 0.020078696, 0.11220895, 0.00092899275, 0.055245925], 'user_id': 1, 'varchar_array': {'Data': {'StringData': {'data': ['']}}}, 'word_count': 8888}`

### Expected Behavior

the type of varchar_array on query result is same as type of inserted varchar_array

### Steps To Reproduce

```python
`   @pytest.mark.parametrize("insert_round", [1])
    @pytest.mark.parametrize("auto_id", [True])
    @pytest.mark.parametrize("is_partition_key", [True])
    @pytest.mark.parametrize("enable_dynamic_schema", [True])
    @pytest.mark.parametrize("nb", [3000])
    @pytest.mark.parametrize("dim", [128])
    def test_query_entities_with_default_none(self, nb, dim, insert_round, auto_id,
                                                     is_partition_key, enable_dynamic_schema):
        """
        Insert a vector with a simple payload
        """
        # create a collection
        name = gen_collection_name()
        payload = {
            "collectionName": name,
            "schema": {
                "autoId": auto_id,
                "enableDynamicField": enable_dynamic_schema,
                "fields": [
                    {"fieldName": "book_id", "dataType": "Int64", "isPrimary": True, "elementTypeParams": {}},
                    {"fieldName": "user_id", "dataType": "Int64", "isPartitionKey": is_partition_key,
                     "elementTypeParams": {}},
                    {"fieldName": "word_count", "dataType": "Int64", "elementTypeParams": {}, "defaultValue": 8888},
                    {"fieldName": "book_describe", "dataType": "VarChar", "elementTypeParams": {"max_length": "25536"},
                     "nullable": True},
                    {"fieldName": "bool", "dataType": "Bool", "elementTypeParams": {}, "nullable": True},
                    {"fieldName": "json", "dataType": "JSON", "elementTypeParams": {}, "nullable": True},
                    {"fieldName": "int_array", "dataType": "Array", "elementDataType": "Int64",
                     "elementTypeParams": {"max_capacity": "1024"}, "nullable": True},
                    {"fieldName": "varchar_array", "dataType": "Array", "elementDataType": "VarChar",
                     "elementTypeParams": {"max_capacity": "1024", "max_length": "256"}, "nullable": True},
                    {"fieldName": "bool_array", "dataType": "Array", "elementDataType": "Bool",
                     "elementTypeParams": {"max_capacity": "1024"}, "nullable": True},
                    {"fieldName": "text_emb", "dataType": "FloatVector", "elementTypeParams": {"dim": f"{dim}"}},
                ]
            },
            "indexParams": [
                {"fieldName": "text_emb", "indexName": "text_emb", "metricType": "L2"},
            ]
        }
        rsp = self.collection_client.collection_create(payload)
        assert rsp['code'] == 0
        rsp = self.collection_client.collection_describe(name)
        logger.info(f"rsp: {rsp}")
        assert rsp['code'] == 0
        # insert data
        for i in range(insert_round):
            data = []
            for i in range(nb):
                if auto_id:
                    tmp = {
                        "user_id": i,
                        "word_count": None,
                        "book_describe": None,
                        "bool": random.choice([True, False]),
                        "json": {"key": None},
                        "int_array": None,
                        "varchar_array": [None],
                        "bool_array": None,
                        "text_emb": preprocessing.normalize([np.array([random.random() for _ in range(dim)])])[0].tolist(),
                    }
                else:
                    tmp = {
                        "book_id": i,
                        "user_id": i,
                        "word_count": None,
                        "book_describe": None,
                        "bool": random.choice([True, False]),
                        "json": {"key": None},
                        "int_array": None,
                        "varchar_array": [None],
                        "bool_array": None,
                        "text_emb": preprocessing.normalize([np.array([random.random() for _ in range(dim)])])[0].tolist(),
                    }
                if enable_dynamic_schema:
                    tmp.update({f"dynamic_field_{i}": i})
                data.append(tmp)
            payload = {
                "collectionName": name,
                "data": data,
            }
            rsp = self.vector_client.vector_insert(payload)
            assert rsp['code'] == 0
            assert rsp['data']['insertCount'] == nb
        # query data to make sure the data is inserted
        # 1. query for int64
        payload = {
            "collectionName": name,
            "filter": "user_id > 0",
            "limit": 50,
            "outputFields": ["*"]
        }
        rsp = self.vector_client.vector_query(payload)
        assert rsp['code'] == 0
        assert rsp['data'][0]['book_describe'] is None
        assert rsp['data'][0]['word_count'] == 8888`
```

### Milvus Log

https://grafana-4am.zilliz.cc/explore?orgId=1&panes=%7B%22wN0%22:%7B%22datasource%22:%22vhI6Vw67k%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcluster%3D%5C%224am%5C%22,namespace%3D%5C%22qa-milvus%5C%22,pod%3D~%5C%22default-none-qx-stlif.%2A%5C%22%7D%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22vhI6Vw67k%22%7D%7D%5D,%22range%22:%7B%22from%22:%221732110758759%22,%22to%22:%221732110777940%22%7D%7D%7D&schemaVersion=1

### Anything else?

N/A

**Comment by smellthemoon** [comment]
Here, array.data is directly printed without checking the next layer structure of array.data. I have communicated with @qixuan0212 offline. If varchar_arrary:none is directly inserted (the new insertion method supported after nullable is true), the search result here will be none. I will open another issue to record for this problem and optimize it later.
