### ISSUE TITLE
[Bug]: Deadlock in `CreateTextIndex`

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#37895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: b983ef9
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Cgo call stuck in `CreateTextIndex` for 2 hours and still lasts

### Expected Behavior

No deadlock

### Anything else?

Also caused goroutine number grow consistently

**Comment by chyezh** [comment]
should be fixed
