### ISSUE TITLE
Searching time increased comparing with 0.10.* on index IVF_PQ when nq equals 1

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#3791]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
![scrnli_9_17_2020_6-21-20 PM](https://user-images.githubusercontent.com/56623710/93458353-c6e75b80-f912-11ea-9c59-006a3a52e25a.png)

if nq equals 100/1000, there is no performance gap between 0.10.* and 0.11.0:
![scrnli_9_17_2020_6-32-48 PM](https://user-images.githubusercontent.com/56623710/93459531-68bb7800-f914-11ea-89ee-38e18b2c1392.png)

**Steps/Code to reproduce behavior**
Tested on the same machine.
```
dataset: sift-10m
index_type: ivf_pq
index_param:
  m: 32
  nlist: 16384
```
**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by del-zhenwu** [comment]
searching on ivf_flat:
![scrnli_9_18_2020_2-07-04 PM](https://user-images.githubusercontent.com/56623710/93562275-4da24400-f9b8-11ea-9c2a-e0a32dec4e82.png)

**Comment by shengjun1985** [comment]
may be the same as #3846

**Comment by del-zhenwu** [comment]
![scrnli_9_27_2020_10-42-46 AM](https://user-images.githubusercontent.com/56623710/94354497-347f4e80-00ae-11eb-8233-fcec3f4d0964.png)
fixed
