### ISSUE TITLE
[Bug]: Error trying to up milvus docker-conteiner ERROR 134

### ISSUE THREAD

**Issue by GBrochado** [milvus-io/milvus#37956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.15
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: i7 11th / 124GB RAM
- GPU: RTX 3060
- Others:
```

### Current Behavior

milvus-standalone  | [2024/11/22 18:11:57.873 +00:00] [ERROR] [querynodev2/server.go:359] ["QueryNode init segcore failed"] [error="[UnknownError] precheck chunk manager client failed, error:Error in ListObjects[errcode:400, exception:AuthorizationQueryParametersError, errmessage:Unable to parse ExceptionName: AuthorizationQueryParametersError Message: Error parsing the X-Amz-Credential parameter; incorrect date format. This date in the credential must be in the format \"yyyyMMdd\"., params:params, bucket=a-bucket, prefix=justforconnectioncheck], configuration:[address=minio:9000, bucket_name=a-bucket, root_path=files, storage_type=remote, cloud_provider=aws, iam_endpoint=, log_level=fatal, region=, useSSL=false, sslCACert=19, useIAM=false, useVirtualHost=false, requestTimeoutMs=10000]"] [errorVerbose="[UnknownError] precheck chunk manager client failed, error:Error in ListObjects[errcode:400, exception:AuthorizationQueryParametersError, errmessage:Unable to parse ExceptionName: AuthorizationQueryParametersError Message: Error parsing the X-Amz-Credential parameter; incorrect date format. This date in the credential must be in the format \"yyyyMMdd\"., params:params, bucket=a-bucket, prefix=justforconnectioncheck], configuration:[address=minio:9000, bucket_name=a-bucket, root_path=files, storage_type=remote, cloud_provider=aws, iam_endpoint=, log_level=fatal, region=, useSSL=false, sslCACert=19, useIAM=false, useVirtualHost=false, requestTimeoutMs=10000]\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/internal/util/initcore.HandleCStatus\n  | \t/workspace/source/internal/util/initcore/init_core.go:218\n  | github.com/milvus-io/milvus/internal/util/initcore.InitRemoteChunkManager\n  | \t/workspace/source/internal/util/initcore/init_core.go:171\n  | github.com/milvus-io/milvus/internal/querynodev2.(*QueryNode).InitSegcore\n  | \t/workspace/source/internal/querynodev2/server.go:244\n  | github.com/milvus-io/milvus/internal/querynodev2.(*QueryNode).Init.func1\n  | \t/workspace/source/internal/querynodev2/server.go:357\n  | sync.(*Once).doSlow\n  | \t/usr/local/go/src/sync/once.go:74\n  | sync.(*Once).Do\n  | \t/usr/local/go/src/sync/once.go:65\n  | github.com/milvus-io/milvus/internal/querynodev2.(*QueryNode).Init\n  | \t/workspace/source/internal/querynodev2/server.go:276\n  | github.com/milvus-io/milvus/internal/distributed/querynode.(*Server).init\n  | \t/workspace/source/internal/distributed/querynode/service.go:143\n  | github.com/milvus-io/milvus/internal/distributed/querynode.(*Server).Run\n  | \t/workspace/source/internal/distributed/querynode/service.go:222\n  | github.com/milvus-io/milvus/cmd/components.(*QueryNode).Run\n  | \t/workspace/source/cmd/components/query_node.go:59\n  | github.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n  | \t/workspace/source/cmd/roles/roles.go:126\n  | runtime.goexit\n  | \t/usr/local/go/src/runtime/asm_amd64.s:1650\nWraps: (2) [UnknownError] precheck chunk manager client failed, error:Error in ListObjects[errcode:400, exception:AuthorizationQueryParametersError, errmessage:Unable to parse ExceptionName: AuthorizationQueryParametersError Message: Error parsing the X-Amz-Credential parameter; incorrect date format. This date in the credential must be in the format \"yyyyMMdd\"., params:params, bucket=a-bucket, prefix=justforconnectioncheck], configuration:[address=minio:9000, bucket_name=a-bucket, root_path=files, storage_type=remote, cloud_provider=aws, iam_endpoint=, log_level=fatal, region=, useSSL=false, sslCACert=19, useIAM=false, useVirtualHost=false, requestTimeoutMs=10000]\nError types: (1) *withstack.withStack (2) *errutil.leafError"] [stack="github.com/milvus-io/milvus/internal/querynodev2.(*QueryNode).Init.func1\n\t/workspace/source/internal/querynodev2/server.go:359\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:74\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:65\ngithub.com/milvus-io/milvus/internal/querynodev2.(*QueryNode).Init\n\t/workspace/source/internal/querynodev2/server.go:276\ngithub.com/milvus-io/milvus/internal/distributed/querynode.(*Server).init\n\t/workspace/source/internal/distributed/querynode/service.go:143\ngithub.com/milvus-io/milvus/internal/distributed/querynode.(*Server).Run\n\t/workspace/source/internal/distributed/querynode/service.go:222\ngithub.com/milvus-io/milvus/cmd/components.(*QueryNode).Run\n\t/workspace/source/cmd/components/query_node.go:59\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/workspace/source/cmd/roles/roles.go:126"]
milvus-standalone  | [2024/11/22 18:11:57.873 +00:00] [ERROR] [querynode/service.go:144] ["QueryNode init error: "] [error="[UnknownError] precheck chunk manager client failed, error:Error in ListObjects[errcode:400, exception:AuthorizationQueryParametersError, errmessage:Unable to parse ExceptionName: AuthorizationQueryParametersError Message: Error parsing the X-Amz-Credential parameter; incorrect date format. This date in the credential must be in the format \"yyyyMMdd\"., params:params, bucket=a-bucket, prefix=justforconnectioncheck], configuration:[address=minio:9000, bucket_name=a-bucket, root_path=files, storage_type=remote, cloud_provider=aws, iam_endpoint=, log_level=fatal, region=, useSSL=false, sslCACert=19, useIAM=false, useVirtualHost=false, requestTimeoutMs=10000]"] [errorVerbose="[UnknownError] precheck chunk manager client failed, error:Error in ListObjects[errcode:400, exception:AuthorizationQueryParametersError, errmessage:Unable to parse ExceptionName: AuthorizationQueryParametersError Message: Error parsing the X-Amz-Credential parameter; incorrect date format. This date in the credential must be in the format \"yyyyMMdd\"., params:params, bucket=a-bucket, prefix=justforconnectioncheck], configuration:[address=minio:9000, bucket_name=a-bucket, root_path=files, storage_type=remote, cloud_provider=aws, iam_endpoint=, log_level=fatal, region=, useSSL=false, sslCACert=19, useIAM=false, useVirtualHost=false, requestTimeoutMs=10000]\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/internal/util/initcore.HandleCStatus\n  | \t/workspace/source/internal/util/initcore/init_core.go:218\n  | github.com/milvus-io/milvus/internal/util/initcore.InitRemoteChunkManager\n  | \t/workspace/source/internal/util/initcore/init_core.go:171\n  | github.com/milvus-io/milvus/internal/querynodev2.(*QueryNode).InitSegcore\n  | \t/workspace/source/internal/querynodev2/server.go:244\n  | github.com/milvus-io/milvus/internal/querynodev2.(*QueryNode).Init.func1\n  | \t/workspace/source/internal/querynodev2/server.go:357\n  | sync.(*Once).doSlow\n  | \t/usr/local/go/src/sync/once.go:74\n  | sync.(*Once).Do\n  | \t/usr/local/go/src/sync/once.go:65\n  | github.com/milvus-io/milvus/internal/querynodev2.(*QueryNode).Init\n  | \t/workspace/source/internal/querynodev2/server.go:276\n  | github.com/milvus-io/milvus/internal/distributed/querynode.(*Server).init\n  | \t/workspace/source/internal/distributed/querynode/service.go:143\n  | github.com/milvus-io/milvus/internal/distributed/querynode.(*Server).Run\n  | \t/workspace/source/internal/distributed/querynode/service.go:222\n  | github.com/milvus-io/milvus/cmd/components.(*QueryNode).Run\n  | \t/workspace/source/cmd/components/query_node.go:59\n  | github.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n  | \t/workspace/source/cmd/roles/roles.go:126\n  | runtime.goexit\n  | \t/usr/local/go/src/runtime/asm_amd64.s:1650\nWraps: (2) [UnknownError] precheck chunk manager client failed, error:Error in ListObjects[errcode:400, exception:AuthorizationQueryParametersError, errmessage:Unable to parse ExceptionName: AuthorizationQueryParametersError Message: Error parsing the X-Amz-Credential parameter; incorrect date format. This date in the credential must be in the format \"yyyyMMdd\"., params:params, bucket=a-bucket, prefix=justforconnectioncheck], configuration:[address=minio:9000, bucket_name=a-bucket, root_path=files, storage_type=remote, cloud_provider=aws, iam_endpoint=, log_level=fatal, region=, useSSL=false, sslCACert=19, useIAM=false, useVirtualHost=false, requestTimeoutMs=10000]\nError types: (1) *withstack.withStack (2) *errutil.leafError"] [stack="github.com/milvus-io/milvus/internal/distributed/querynode.(*Server).init\n\t/workspace/source/internal/distributed/querynode/service.go:144\ngithub.com/milvus-io/milvus/internal/distributed/querynode.(*Server).Run\n\t/workspace/source/internal/distributed/querynode/service.go:222\ngithub.com/milvus-io/milvus/cmd/components.(*QueryNode).Run\n\t/workspace/source/cmd/components/query_node.go:59\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/workspace/source/cmd/roles/roles.go:126"]
milvus-standalone  | [2024/11/22 18:11:57.874 +00:00] [ERROR] [components/query_node.go:60] ["QueryNode starts error"] [error="[UnknownError] precheck chunk manager client failed, error:Error in ListObjects[errcode:400, exception:AuthorizationQueryParametersError, errmessage:Unable to parse ExceptionName: AuthorizationQueryParametersError Message: Error parsing the X-Amz-Credential parameter; incorrect date format. This date in the credential must be in the format \"yyyyMMdd\"., params:params, bucket=a-bucket, prefix=justforconnectioncheck], configuration:[address=minio:9000, bucket_name=a-bucket, root_path=files, storage_type=remote, cloud_provider=aws, iam_endpoint=, log_level=fatal, region=, useSSL=false, sslCACert=19, useIAM=false, useVirtualHost=false, requestTimeoutMs=10000]"] [errorVerbose="[UnknownError] precheck chunk manager client failed, error:Error in ListObjects[errcode:400, exception:AuthorizationQueryParametersError, errmessage:Unable to parse ExceptionName: AuthorizationQueryParametersError Message: Error parsing the X-Amz-Credential parameter; incorrect date format. This date in the credential must be in the format \"yyyyMMdd\"., params:params, bucket=a-bucket, prefix=justforconnectioncheck], configuration:[address=minio:9000, bucket_name=a-bucket, root_path=files, storage_type=remote, cloud_provider=aws, iam_endpoint=, log_level=fatal, region=, useSSL=false, sslCACert=19, useIAM=false, useVirtualHost=false, requestTimeoutMs=10000]\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/internal/util/initcore.HandleCStatus\n  | \t/workspace/source/internal/util/initcore/init_core.go:218\n  | github.com/milvus-io/milvus/internal/util/initcore.InitRemoteChunkManager\n  | \t/workspace/source/internal/util/initcore/init_core.go:171\n  | github.com/milvus-io/milvus/internal/querynodev2.(*QueryNode).InitSegcore\n  | \t/workspace/source/internal/querynodev2/server.go:244\n  | github.com/milvus-io/milvus/internal/querynodev2.(*QueryNode).Init.func1\n  | \t/workspace/source/internal/querynodev2/server.go:357\n  | sync.(*Once).doSlow\n  | \t/usr/local/go/src/sync/once.go:74\n  | sync.(*Once).Do\n  | \t/usr/local/go/src/sync/once.go:65\n  | github.com/milvus-io/milvus/internal/querynodev2.(*QueryNode).Init\n  | \t/workspace/source/internal/querynodev2/server.go:276\n  | github.com/milvus-io/milvus/internal/distributed/querynode.(*Server).init\n  | \t/workspace/source/internal/distributed/querynode/service.go:143\n  | github.com/milvus-io/milvus/internal/distributed/querynode.(*Server).Run\n  | \t/workspace/source/internal/distributed/querynode/service.go:222\n  | github.com/milvus-io/milvus/cmd/components.(*QueryNode).Run\n  | \t/workspace/source/cmd/components/query_node.go:59\n  | github.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n  | \t/workspace/source/cmd/roles/roles.go:126\n  | runtime.goexit\n  | \t/usr/local/go/src/runtime/asm_amd64.s:1650\nWraps: (2) [UnknownError] precheck chunk manager client failed, error:Error in ListObjects[errcode:400, exception:AuthorizationQueryParametersError, errmessage:Unable to parse ExceptionName: AuthorizationQueryParametersError Message: Error parsing the X-Amz-Credential parameter; incorrect date format. This date in the credential must be in the format \"yyyyMMdd\"., params:params, bucket=a-bucket, prefix=justforconnectioncheck], configuration:[address=minio:9000, bucket_name=a-bucket, root_path=files, storage_type=remote, cloud_provider=aws, iam_endpoint=, log_level=fatal, region=, useSSL=false, sslCACert=19, useIAM=false, useVirtualHost=false, requestTimeoutMs=10000]\nError types: (1) *withstack.withStack (2) *errutil.leafError"] [stack="github.com/milvus-io/milvus/cmd/components.(*QueryNode).Run\n\t/workspace/source/cmd/components/query_node.go:60\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/workspace/source/cmd/roles/roles.go:126"]

**Comment by davloperez** [comment]
@GBrochado take a look at https://github.com/milvus-io/milvus/issues/34983, it could be the same issue

**Comment by yanliang567** [comment]
/assign @GBrochado 
could you please try with the suggestions in the issue above.
/unassign

**Comment by GBrochado** [comment]
Thanks for the help, I just add internal: true  in networks on docker-compose and now its working. Thanks a lot
