### ISSUE TITLE
[Bug]: [privilege_group]  The result of list collection is empty when login with the user added in the role granted with the built-in privilege group "DatabaseReadOnly"/"DatabaseReadWrite"/"DatabaseAdmin"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#38041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-latest
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):   all 
- SDK version(e.g. pymilvus v2.0.0rc2): 2.5.0rc126
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The result of list collection is empty when login with the user added in the role granted with the built-in privilege group "DatabaseReadOnly"/"DatabaseReadWrite"/"DatabaseAdmin"

### Expected Behavior

 The result of list collection is not empty when login with the user added in the role granted with the built-in privilege group "DatabaseReadOnly"/"DatabaseReadWrite"/"DatabaseAdmin"

### Steps To Reproduce

```python
from pymilvus import connections
from pymilvus import CollectionSchema, FieldSchema
from pymilvus import Collection
from pymilvus import connections
from pymilvus import DataType
from pymilvus import Partition
from pymilvus import utility
from pymilvus import MilvusClient
from pymilvus import Role

connections.connect(host="***", user="root", password="Milvus")
client = MilvusClient(uri="http://***:19530", user="root", password="Milvus")
client.create_collection("binbin_new", dimension=128)
role = Role("binbin")
role.create()
utility.list_roles(True)
utility.create_user(user="user1", password="Milvus")
role.add_user("user1")
utility.list_roles(True)
role.list_grants()
role.grant_v2(privilege="DatabaseReadOnly", db_name="default", collection_name="*")
role.list_grants()

connections.disconnect('default')
connections.connect(host="", user="user1", password="Milvus")
utility.list_collections()
```

**Comment by binbinlv** [comment]
And the followings in red "N" do not work as expected:

![c89993eb-fce5-4c32-b7b3-476e2024911a](https://github.com/user-attachments/assets/848e0b55-9af8-4d4d-803b-b2858731fe2d)

**Comment by shaoting-huang** [comment]
same problem with issue: https://github.com/milvus-io/milvus/issues/38041

**Comment by binbinlv** [comment]
The "showCollections" privilege is default now, so as designed. 

And if not grant the collection operation previleges like (Createcollection, Insert, upsert, ...), list_collections will be empty.

"list_collections" here in privilege  scenario means list all the collections that user has operation previleges.

So close this issue.
