### ISSUE TITLE
[Bug]: get_bulk_insert_state returns missing fields

### ISSUE THREAD

**Issue by abd-770** [milvus-io/milvus#38051]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Running bulk_insert and use `get_bulk_insert_state `does not return all the properties listed in the milvus [documentation](https://milvus.io/api-reference/pymilvus/v2.4.x/ORM/utility/get_bulk_insert_state.md).
Currently, only 7 fields are returned.

```
task_id = utility.do_bulk_insert(collection_name=collection_names, files=['pk.npy', 'vector.npy'])
task = utility.get_bulk_insert_state(task_id=task_id)
print("Printing Task: ", task)
```

```
Printing Task:  <Bulk insert state:
    - taskID          : 454172419327013759,
    - state           : Completed,
    - row_count       : 1000000,
    - infos           : {'failed_reason': '', 'progress_percent': '100'},
    - id_ranges       : [],
    - create_ts       : 2024-11-26 22:23:32
```

### Expected Behavior

`get_bulk_insert_state` should return all the fields mentioned in the milvus documentation.

**Comment by yanliang567** [comment]
/assign @xiaocai2333 @zhuwenxing 
is it something we should update in the doc?
/unassign

**Comment by xiaofan-luan** [comment]
is there an importnat field missing?

**Comment by bigsheeper** [comment]
@abd-770 The documentable you're referring to is outdated. We're in the process of removing it to avoid confusion. For the most up-to-date information, please refer to the latest documentation here: https://milvus.io/docs/import-data.md.

**Comment by abd-770** [comment]
@bigsheeper 
Okay got it.
So I believe `get_bulk_insert_state()` is deprecated, and `get_import_progress` and `list_import_jobs` are the alternative functions which are mentioned in the latest doc.

**Comment by abd-770** [comment]
@bigsheeper @xiaofan-luan We are using milvus v2.4.x, and referring to the 2.4.x documentation.
Can you verify why all the fields are not returned in the function response

**Comment by abd-770** [comment]
@yanliang567 @bigsheeper Can you update on this issue?

**Comment by bigsheeper** [comment]
> @yanliang567 @bigsheeper Can you update on this issue?

![image](https://github.com/user-attachments/assets/2cf25dea-f7ff-4db9-8862-f25dd0fdadcb)
