### ISSUE TITLE
[Bug]: [docs] Open the build-rag-with-milvus.md document, but the document does not exist(404 - page not found)

### ISSUE THREAD

**Issue by HuaSheng2000** [milvus-io/milvus#38054]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I click on the tutorial link below, the document does not exist and show a 404 error, indicating that the page not found.
https://github.com/milvus-io/milvus?tab=readme-ov-file#demos-and-tutorials
![image](https://github.com/user-attachments/assets/cfbc354b-905a-4b61-ab35-06687bcdd9cf)
I looked at the Chinese documentation and found that there is no tutorial chapter, only a demo chapter. Is the tutorial chapter in the English documentation no longer needed?

**Comment by yanliang567** [comment]
I believe the correct links shall be in https://milvus.io/docs/tutorials-overview.md @HuaSheng2000  please check the links there. We will fix the readme soon

**Comment by HuaSheng2000** [comment]
@yanliang567 
Thanks for your answer

**Comment by yanliang567** [comment]
@HuaSheng2000 thank you for your contribution. 
pr merged.
