### ISSUE TITLE
Error should be raised if create index on non-vector field

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#3806]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
_______________________________________________________________ TestIndexBase.test_create_index_on_field[get_simple_index0] _______________________________________________________________

self = <test_index.TestIndexBase object at 0x7f414f9b7da0>, connect = <milvus.client.stub.Milvus object at 0x7f414f9b79e8>, collection = 'index_kyr0py4m'
get_simple_index = {'index_type': 'FLAT', 'metric_type': 'L2', 'params': {'nlist': 128}}

    def test_create_index_on_field(self, connect, collection, get_simple_index):
        '''
        target: test create index interface
        method: create collection and add entities in it, create index on other field
        expected: error raised
        '''
        tmp_field_name = "int64"
        ids = connect.insert(collection, entities)
        with pytest.raises(Exception) as e:
>           connect.create_index(collection, tmp_field_name, get_simple_index)
E           Failed: DID NOT RAISE <class 'Exception'>

test_index.py:88: Failed
----------------------------------------------------------------------------------- Captured log setup ------------------------------------------------------------------------------------
[2020-09-18 17:32:54-INFO-root]: {'index_type': 'FLAT', 'metric_type': 'L2', 'params': {'nlist': 128}} (test_index.py:35)

```
**Steps/Code to reproduce behavior**
1. create collection, with field: int64/float_vector
2. create index on field int64

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by cydrain** [comment]
if non-vector field also support create index, need do more strict index type check.

**Comment by yhmo** [comment]
Fix this in request level.

**Comment by yhmo** [comment]
[pr3848](https://github.com/milvus-io/milvus/pull/3848) will fix this issue.
For non-vector field, the index type must be "SORTED", otherwise return error message "Invalid index type"

**Comment by del-zhenwu** [comment]
close
