### ISSUE TITLE
What is milvus::CollectionParam?

### ISSUE THREAD

**Issue by rosaline1995** [milvus-io/milvus#3810]
**Describe the bug**
Since `CreateCollection(const Mapping& mapping, const std::string& extra_params) = 0;` doesn't work as I stated [here](https://github.com/milvus-io/milvus/issues/3809) on my device, I wanna switch to `CreateCollection(collection_param);` as shown in the [example](https://github.com/milvus-io/milvus/blob/836a247b6ab9cd023c16b5c0a2c799adb88157f1/sdk/examples/qps/src/ClientTest.cpp#L146) . However, I didn't find the definition of either the function or the struct. 

However, I saw some people said they used it before, but there was no code for reference. So may I ask what it is and where I can find it? How should I use it? (I think the method should be similar to  `CreateCollection(const Mapping& mapping, const std::string& extra_params) = 0;`, but since it didn't work on my device, I have no idea).

Thanks for any possible help!

**Comment by shengjun1985** [comment]
Can you run the example C++ SDK?
https://github.com/milvus-io/milvus/tree/0.10.2/sdk/examples/simple

Here is the C++ simple code.
https://github.com/milvus-io/milvus/blob/0.10.2/sdk/examples/simple/src/ClientTest.cpp

**Comment by fishpenguin** [comment]
Did you use master branch?

**Comment by fishpenguin** [comment]
Did you use master branch? If so, you can use milvus::CollectionParam like line 58 and 59 in milvus/sdk/examples/simple/src/ClientTest.cpp, the address and port is your milvus server ip and port.

**Comment by rosaline1995** [comment]
Hi, thanks for your quick response.
No, I don't think I can run the example. My issue is already stated here https://github.com/milvus-io/milvus/issues/3809.

I run `./build.sh` first and then find `sdk_simple` to run. But I saw the following information:
`Client start...
Connect function call status: OK
ListCollections function call status: OK
Collection list: 
Invalid collection dimension: 0. The collection dimension must be within the range of 1 ~ 32768.
CreateCollection function call status: Invalid collection dimension: 0. The collection dimension must be within the range of 1 ~ 32768.
Collection C_2020_9_23_5_19_55 does not exist. Use milvus.has_collection to verify whether the collection exists. You also can check whether the collection name exists.
Collection stats: 
GetCollectionStats function call status: Collection C_2020_9_23_5_19_55 does not exist. Use milvus.has_collection to verify whether the collection exists. You also can check whether the collection name exists.
ListCollections function call status: OK
Collection list: 
Collection C_2020_9_23_5_19_55 does not exist. Use milvus.has_collection to verify whether the collection exists. You also can check whether the collection name exists.
Collection C_2020_9_23_5_19_55 entity count: -1
Build entities No.0 begin...
Build entities No.0 totally cost: 99 ms
Insert rpc failed!
InsertEntities function call status: 
Returned id array count: 10000
Build entities No.1 begin...
Build entities No.1 totally cost: 76 ms
Insert rpc failed!
InsertEntities function call status: 
Returned id array count: 10000
Build entities No.2 begin...
Build entities No.2 totally cost: 63 ms
Insert rpc failed!
InsertEntities function call status: 
Returned id array count: 10000
Build entities No.3 begin...
Build entities No.3 totally cost: 64 ms
Insert rpc failed!
InsertEntities function call status: 
Returned id array count: 10000
Build entities No.4 begin...
Build entities No.4 totally cost: 63 ms
Insert rpc failed!
InsertEntities function call status: 
Returned id array count: 10000
Build entities No.5 begin...
Build entities No.5 totally cost: 67 ms
Insert rpc failed!
InsertEntities function call status: 
Returned id array count: 10000
Build entities No.6 begin...
Build entities No.6 totally cost: 63 ms
Insert rpc failed!
InsertEntities function call status: 
Returned id array count: 10000
Build entities No.7 begin...
Build entities No.7 totally cost: 62 ms
Insert rpc failed!
InsertEntities function call status: 
Returned id array count: 10000
Build entities No.8 begin...
Build entities No.8 totally cost: 62 ms
Insert rpc failed!
InsertEntities function call status: 
Returned id array count: 10000
Build entities No.9 begin...
Build entities No.9 totally cost: 62 ms
Insert rpc failed!
InsertEntities function call status: 
Returned id array count: 10000
Flush begin...
Collection C_2020_9_23_5_19_55 does not exist. Use milvus.has_collection to verify whether the collection exists. You also can check whether the collection name exists.
Flush function call status: OK
Flush totally cost: 0 ms
Collection C_2020_9_23_5_19_55 does not exist. Use milvus.has_collection to verify whether the collection exists. You also can check whether the collection name exists.
Collection C_2020_9_23_5_19_55 entity count: -1
Create index begin...
Wait until create all index done
===========================================
Index collection name: C_2020_9_23_5_19_55
Index field name: field_vec
Index extra_params: {"index_type":"IVF_FLAT","metric_type":"L2","params":{"nlist":1024}}
===========================================
Collection C_2020_9_23_5_19_55 does not exist. Use milvus.has_collection to verify whether the collection exists. You also can check whether the collection name exists.
CreateIndex function call status: Collection C_2020_9_23_5_19_55 does not exist. Use milvus.has_collection to verify whether the collection exists. You also can check whether the collection name exists.
===========================================
Index collection name: C_2020_9_23_5_19_55
Index field name: field_vec
Index extra_params: {"index_type":"IVF_FLAT","metric_type":"L2","params":{"nlist":1024}}
===========================================
Create index totally cost: 0 ms
Collection C_2020_9_23_5_19_55 does not exist. Use milvus.has_collection to verify whether the collection exists. You also can check whether the collection name exists.
===========================================
Collection name: C_2020_9_23_5_19_55
Collection extra params: 
===========================================
GetCollectionInfo function call status: Collection C_2020_9_23_5_19_55 does not exist. Use milvus.has_collection to verify whether the collection exists. You also can check whether the collection name exists.
Search rpc failed!

L2 Search function call result: 
L2 Search function call status: 
Search rpc failed!

IP Search function call result: 
IP Search function call status: 
Collection C_2020_9_23_5_19_55 does not exist. Use milvus.has_collection to verify whether the collection exists. You also can check whether the collection name exists.
DropCollection function call status: Collection C_2020_9_23_5_19_55 does not exist. Use milvus.has_collection to verify whether the collection exists. You also can check whether the collection name exists.
Client stop...
Destroy connection function call status: OK`

To me, it seems that all collection creations  were failed. I just used the original code without modifying at all.

**Comment by rosaline1995** [comment]
As for my question related to CollectionParam, what I am confused is, could you please help me point out where its source code/definition is? I didn't find it in the folder named `sdk`.

Also, I wonder if it's possible to run code in `qps` and `partition`. I didn't find executable files. Thanks!

**Comment by shengjun1985** [comment]
Here is the C++ SDK Api.
https://github.com/milvus-io/milvus/blob/0.10.3/sdk/include/MilvusApi.h

**Comment by Bennu-Li** [comment]
Here is the benchmark-test:
https://github.com/milvus-io/ann-benchmarks

**Comment by yhmo** [comment]
I just build the 0.10.2 C++ sdk and run the sdk_simple, it seems ok:

```
Client start...
Connect function call status: OK
Server version: 0.10.2
SDK version: 0.10.0
ShowCollections function call status: OK
All collections: 
CreateCollection function call status: OK
===========================================
Collection name: C_2020_9_23_10_39_48
Collection dimension: 512
Collection index file size: 1024
Collection metric type: L2 distance
===========================================
Collection is created
DescribeCollection function call status: OK
===========================================
Collection name: C_2020_9_23_10_39_48
Collection dimension: 512
Collection index file size: 1024
Collection metric type: L2 distance
===========================================
Build entities No.0 begin...
Build entities No.0 totally cost: 734 ms
Insert 100000 entities No.0 begin...
InsertEntities function call status: OK
Returned id array count: 100000
Insert 100000 entities No.0 totally cost: 965 ms
Build entities No.1 begin...
Build entities No.1 totally cost: 675 ms
Insert 100000 entities No.1 begin...
InsertEntities function call status: OK
Returned id array count: 100000
Insert 100000 entities No.1 totally cost: 759 ms
Build entities No.2 begin...
Build entities No.2 totally cost: 695 ms
Insert 100000 entities No.2 begin...
InsertEntities function call status: OK
Returned id array count: 100000
Insert 100000 entities No.2 totally cost: 756 ms
Build entities No.3 begin...
Build entities No.3 totally cost: 684 ms
Insert 100000 entities No.3 begin...
InsertEntities function call status: OK
Returned id array count: 100000
Insert 100000 entities No.3 totally cost: 733 ms
Build entities No.4 begin...
Build entities No.4 totally cost: 701 ms
Insert 100000 entities No.4 begin...
InsertEntities function call status: OK
Returned id array count: 100000
Insert 100000 entities No.4 totally cost: 798 ms
Flush begin...
Flush function call status: OK
Flush totally cost: 1873 ms
Collection info: {"partitions":[{"row_count":500000,"segments":[{"data_size":117109760,"index_name":"IDMAP","name":"1600828796593501000","row_count":56960},{"data_size":822400000,"index_name":"IDMAP","name":"1600828796756451000","row_count":400000},{"data_size":88490240,"index_name":"IDMAP","name":"1600828796837179000","row_count":43040}],"tag":"_default"}],"row_count":500000}
GetCollectionStats function call status: OK
GetEntityByID begin...
GetEntityByID function call status: OK
GetEntityByID totally cost: 16 ms
No.0 id:50000	[0, 0, 0, 0, 0, 0, 1, 4, 6, 0, 6, 0, 11, 8, 0, 4, 1, 6, 16, 0, 15, 6, 6, 12, 0, 24, 15, 8, 17, 0, 4, 20, 6, 18, 15, 24, 2, 16, 24, 20, 39, 36, 5, 28, 15, 6, 45, 36, 22, 0, 18, 24, 15, 42, 50, 36, 54, 46, 9, 0, 19, 4, 15, 52, 50, 6, 51, 52, 6, 50, 45, 60, 22, 2, 0, 16, 50, 24, 14, 20, 42, 80, 51, 36, 35, 48, 75, 28, 82, 60, 50, 52, 66, 92, 35, 84, 48, 22, 6, 0, 4, 18, 42, 76, 15, 68, 24, 96, 69, 50, 39, 36, 41, 54, 75, 104, 24, 68, 1, 60, 6, 80, 39, 4, 100, 78, 62, 52, 48, 50, 58, 72, 92, 118, 15, 52, 95, 6, 60, 120, 45, 116, 50, 132, 75, 22, 120, 76, 36, 0, 119, 92, 69, 50, 35, 24, 17, 14, 15, 20, 29, 42, 59, 80, 105, 134, 0, 36, 76, 120, 168, 48, 103, 162, 50, 116, 9, 82, 159, 60, 144, 50, 141, 52, 150, 66, 171, 92, 15, 130, 58, 180, 113, 48, 180, 120, 62, 6, 151, 100, 51, 4, 162, 120, 80, 42, 6, 180, 149, 120, 93, 68, 45, 24, 5, 204, 190, 178, 168, 160, 154, 150, 148, 148, 150, 154, 160, 168, 178, 190, 204, 220, 5, 24, 45, 68, 93, 120, 149, 180, 213, 6, 42, 80, 120, 162, 206, 4, 51, 100, 151, 204, 6, 62, 120, 180, 242, 48, 113, 180, 249, 58, 130, 204, 15, 92, 171, 252, 66, 150, 236, 52, 141, 232, 50, 144, 240, 60, 159, 260, 82, 186, 9, 116, 225, 50, 162, 276, 103, 220, 48, 168, 290, 120, 245, 76, 204, 36, 167, 0, 134, 270, 105, 244, 80, 222, 59, 204, 42, 190, 29, 180, 20, 174, 15, 172, 14, 174, 17, 180, 24, 190, 35, 204, 50, 222, 69, 244, 92, 270, 119, 300, 150, 0, 185, 36, 224, 76, 267, 120, 314, 168, 22, 220, 75, 276, 132, 336, 193, 50, 258, 116, 327, 186, 45, 260, 120, 338, 199, 60, 282, 144, 6, 232, 95, 324, 188, 52, 285, 150, 15, 252, 118, 358, 225, 92, 336, 204, 72, 320, 189, 58, 310, 180, 50, 306, 177, 48, 308, 180, 52, 316, 189, 62, 330, 204, 78, 350, 225, 100, 376, 252, 128, 4, 285, 162, 39, 324, 202, 80, 369, 248, 127, 6, 300, 180, 60, 358, 239, 120, 1, 304, 186, 68, 375, 258, 141, 24, 336, 220, 104, 420, 305, 190, 75, 396, 282, 168, 54, 380, 267, 154, 41, 372, 260, 148, 36, 372, 261, 150, 39, 380, 270, 160, 50, 396, 287, 178, 69, 420, 312, 204, 96, 452, 345, 238, 131, 24, 386, 280, 174, 68, 435, 330, 225, 120, 15, 388, 284, 180, 76, 454, 351, 248, 145, 42, 426, 324, 222, 120, 18, 408, 307, 206, 105, 4, 400, 300, 200, 100, 0, 402, 303, 204, 105, 6, 414, 316, 218, 120, 22, 436]
No.1 id:150000	[0, 0, 1, 0, 0, 4, 6, 4, 7, 0, 5, 4, 2, 6, 10, 4, 7, 16, 0, 0, 13, 16, 2, 4, 0, 2, 7, 20, 25, 10, 29, 20, 16, 24, 20, 16, 28, 0, 28, 20, 40, 34, 30, 16, 25, 2, 29, 4, 13, 0, 7, 28, 4, 34, 5, 20, 19, 54, 4, 40, 40, 60, 34, 20, 15, 16, 20, 24, 25, 20, 6, 52, 12, 28, 25, 0, 27, 28, 0, 20, 7, 40, 36, 76, 75, 30, 25, 60, 46, 70, 41, 48, 91, 76, 0, 52, 41, 62, 16, 0, 14, 58, 29, 28, 55, 4, 86, 88, 7, 60, 28, 20, 36, 76, 25, 112, 106, 4, 41, 100, 60, 40, 40, 60, 100, 34, 113, 84, 73, 80, 105, 16, 76, 20, 115, 92, 85, 94, 119, 20, 76, 6, 93, 52, 25, 12, 13, 28, 57, 100, 6, 76, 7, 104, 60, 28, 8, 0, 4, 20, 48, 88, 140, 40, 115, 36, 134, 76, 28, 160, 133, 116, 109, 112, 125, 148, 4, 46, 98, 160, 51, 132, 40, 140, 65, 184, 126, 76, 34, 0, 165, 148, 139, 138, 145, 160, 183, 16, 54, 100, 154, 14, 83, 160, 40, 132, 25, 132, 38, 160, 79, 4, 148, 86, 30, 196, 153, 116, 85, 60, 41, 28, 21, 20, 25, 36, 53, 76, 105, 140, 181, 228, 48, 106, 170, 4, 79, 160, 8, 100, 198, 60, 169, 40, 160, 40, 171, 60, 202, 100, 2, 160, 71, 240, 160, 84, 12, 202, 139, 80, 25, 236, 190, 148, 110, 76, 46, 20, 267, 250, 237, 228, 223, 222, 225, 232, 243, 258, 277, 20, 46, 76, 110, 148, 190, 236, 286, 52, 109, 170, 235, 12, 84, 160, 240, 28, 115, 206, 2, 100, 202, 6, 115, 228, 40, 160, 284, 104, 235, 60, 198, 28, 173, 8, 160, 0, 159, 4, 170, 20, 193, 48, 228, 88, 275, 140, 7, 204, 76, 280, 157, 36, 250, 134, 20, 244, 135, 28, 262, 160, 60, 304, 209, 116, 25, 282, 196, 112, 30, 300, 223, 148, 75, 4, 290, 224, 160, 98, 38, 340, 285, 232, 181, 132, 85, 40, 364, 324, 286, 250, 216, 184, 154, 126, 100, 76, 54, 34, 16, 0, 367, 356, 347, 340, 335, 332, 331, 332, 335, 340, 347, 356, 367, 380, 0, 16, 34, 54, 76, 100, 126, 154, 184, 216, 250, 286, 324, 364, 406, 40, 85, 132, 181, 232, 285, 340, 397, 38, 98, 160, 224, 290, 358, 4, 75, 148, 223, 300, 379, 30, 112, 196, 282, 370, 25, 116, 209, 304, 401, 60, 160, 262, 366, 28, 135, 244, 355, 20, 134, 250, 368, 36, 157, 280, 405, 76, 204, 334, 7, 140, 275, 412, 88, 228, 370, 48, 193, 340, 20, 170, 322, 4, 159, 316, 0, 160, 322, 8, 173, 340, 28, 198, 370, 60, 235, 412, 104, 284, 466, 160, 345, 40, 228, 418, 115, 308, 6, 202, 400, 100, 301, 2, 206, 412, 115, 324, 28, 240, 454, 160, 377, 84]
No.2 id:250000	[0, 0, 2, 0, 0, 2, 4, 4, 8, 0, 4, 8, 6, 4, 5, 4, 13, 8, 3, 0, 11, 4, 21, 20, 0, 6, 26, 4, 4, 20, 23, 20, 26, 30, 25, 8, 17, 22, 32, 20, 0, 32, 12, 4, 35, 44, 13, 20, 4, 0, 47, 32, 46, 26, 15, 4, 41, 4, 58, 20, 0, 54, 53, 52, 45, 26, 56, 64, 44, 60, 38, 44, 2, 54, 50, 60, 4, 32, 65, 20, 53, 0, 21, 32, 30, 12, 62, 4, 10, 80, 32, 44, 23, 60, 60, 20, 34, 4, 26, 0, 24, 98, 16, 84, 95, 46, 41, 80, 54, 70, 17, 4, 31, 98, 90, 4, 71, 58, 81, 20, 114, 0, 41, 116, 100, 116, 37, 116, 98, 110, 21, 92, 60, 56, 80, 132, 75, 44, 39, 60, 107, 38, 136, 116, 120, 2, 53, 128, 78, 50, 44, 60, 98, 4, 85, 32, 156, 144, 152, 20, 67, 134, 58, 0, 125, 104, 101, 116, 149, 30, 98, 12, 115, 62, 25, 4, 176, 10, 37, 80, 139, 32, 122, 44, 165, 116, 81, 60, 53, 60, 81, 116, 165, 34, 110, 4, 107, 26, 156, 100, 56, 24, 4, 200, 0, 16, 44, 84, 136, 200, 65, 152, 38, 148, 55, 188, 116, 54, 2, 180, 149, 128, 117, 116, 125, 144, 173, 212, 32, 90, 158, 4, 91, 188, 60, 176, 65, 200, 106, 20, 183, 114, 53, 0, 200, 164, 136, 116, 104, 100, 104, 116, 136, 164, 200, 244, 39, 98, 165, 240, 62, 152, 250, 92, 205, 60, 188, 56, 199, 80, 238, 132, 32, 212, 125, 44, 246, 178, 116, 60, 10, 248, 211, 180, 155, 136, 123, 116, 115, 120, 131, 148, 171, 200, 235, 276, 26, 78, 136, 200, 270, 44, 125, 212, 0, 98, 202, 4, 119, 240, 56, 188, 13, 156, 305, 144, 304, 152, 4, 180, 41, 228, 98, 296, 175, 58, 272, 164, 60, 290, 195, 104, 17, 268, 190, 116, 46, 318, 257, 200, 147, 98, 53, 12, 320, 288, 260, 236, 216, 200, 188, 180, 176, 176, 180, 188, 200, 216, 236, 260, 288, 320, 356, 32, 75, 122, 173, 228, 287, 350, 46, 116, 190, 268, 350, 60, 149, 242, 339, 60, 164, 272, 1, 116, 235, 358, 98, 228, 362, 110, 251, 4, 152, 304, 65, 224, 387, 156, 326, 100, 277, 56, 240, 24, 215, 4, 202, 404, 201, 0, 212, 16, 235, 44, 270, 84, 317, 136, 376, 200, 26, 276, 107, 364, 200, 38, 305, 148, 422, 270, 120, 404, 259, 116, 410, 272, 136, 2, 309, 180, 53, 370, 248, 128, 10, 340, 227, 116, 7, 350, 246, 144, 44, 400, 305, 212, 121, 32, 404, 320, 238, 158, 80, 4, 395, 324, 255, 188, 123, 60, 470, 412, 356, 302, 250, 200, 152, 106, 62, 20, 461, 424, 389, 356, 325, 296, 269, 244, 221, 200, 181, 164, 149, 136, 125, 116, 109, 104, 101, 100, 101, 104, 109, 116, 125, 136, 149, 164, 181, 200, 221, 244]
No.3 id:350000	[0, 0, 0, 0, 0, 0, 2, 4, 0, 0, 3, 0, 10, 2, 0, 4, 2, 0, 6, 0, 9, 14, 17, 12, 0, 10, 18, 16, 12, 0, 17, 20, 3, 2, 30, 0, 6, 6, 36, 20, 1, 30, 37, 36, 0, 40, 44, 36, 44, 0, 36, 36, 35, 18, 25, 44, 6, 12, 53, 0, 21, 48, 9, 20, 10, 36, 25, 36, 63, 30, 70, 36, 65, 6, 0, 44, 58, 36, 51, 20, 18, 42, 6, 72, 70, 80, 12, 36, 63, 0, 23, 40, 48, 44, 25, 84, 27, 44, 36, 0, 34, 36, 3, 36, 30, 88, 103, 72, 101, 80, 6, 100, 26, 6, 40, 12, 36, 112, 2, 60, 47, 82, 42, 48, 100, 72, 88, 20, 123, 10, 68, 36, 44, 92, 45, 36, 65, 132, 98, 100, 138, 70, 36, 36, 70, 138, 93, 80, 99, 0, 82, 44, 36, 58, 110, 36, 147, 130, 141, 20, 86, 18, 139, 124, 135, 6, 68, 156, 101, 70, 63, 80, 121, 12, 100, 36, 171, 152, 155, 0, 46, 114, 21, 132, 80, 48, 36, 44, 72, 120, 188, 84, 191, 124, 75, 44, 31, 36, 59, 100, 159, 34, 128, 36, 165, 106, 63, 36, 25, 30, 51, 88, 141, 210, 80, 180, 79, 210, 138, 80, 36, 6, 213, 212, 0, 26, 66, 120, 188, 40, 135, 12, 134, 36, 185, 112, 51, 2, 204, 180, 168, 168, 180, 204, 240, 42, 101, 172, 6, 100, 206, 72, 201, 88, 240, 148, 66, 252, 191, 140, 99, 68, 47, 36, 35, 44, 63, 92, 131, 180, 239, 36, 114, 202, 25, 132, 249, 98, 234, 100, 255, 138, 29, 212, 120, 36, 247, 180, 121, 70, 27, 284, 258, 240, 230, 228, 234, 248, 270, 0, 37, 82, 135, 196, 265, 36, 120, 212, 3, 110, 225, 36, 166, 304, 135, 288, 132, 300, 157, 20, 210, 86, 291, 180, 75, 302, 210, 124, 44, 300, 233, 172, 117, 68, 25, 324, 294, 270, 252, 240, 234, 234, 240, 252, 270, 294, 324, 12, 53, 100, 153, 212, 277, 348, 70, 152, 240, 334, 75, 180, 291, 46, 168, 296, 65, 204, 349, 132, 288, 80, 247, 48, 226, 36, 225, 44, 244, 72, 283, 120, 342, 188, 38, 276, 135, 384, 252, 124, 0, 270, 155, 44, 330, 228, 130, 36, 343, 258, 177, 100, 27, 360, 296, 236, 180, 128, 80, 36, 405, 370, 339, 312, 289, 270, 255, 244, 237, 234, 235, 240, 249, 262, 279, 300, 325, 354, 387, 424, 36, 80, 128, 180, 236, 296, 360, 428, 63, 138, 217, 300, 387, 36, 130, 228, 330, 436, 99, 212, 329, 0, 124, 252, 384, 66, 205, 348, 38, 188, 342, 40, 201, 366, 72, 244, 420, 134, 317, 36, 226, 420, 147, 348, 80, 288, 25, 240, 459, 204, 430, 180, 413, 168, 408, 168, 415, 180, 434, 204, 465, 240, 17, 288, 70, 348, 135, 420, 212, 6, 301, 100, 402, 206, 12, 324, 135, 454, 270, 88, 417, 240, 65, 404]
No.4 id:450000	[0, 0, 1, 0, 0, 4, 0, 4, 1, 0, 2, 4, 1, 0, 10, 4, 8, 10, 9, 0, 7, 2, 13, 4, 0, 14, 10, 0, 20, 10, 11, 20, 13, 8, 0, 28, 32, 28, 1, 20, 2, 28, 19, 24, 10, 36, 28, 4, 35, 0, 25, 40, 24, 10, 35, 28, 28, 20, 48, 40, 42, 42, 28, 52, 40, 46, 61, 8, 13, 0, 31, 28, 55, 32, 25, 28, 35, 40, 37, 20, 64, 2, 74, 28, 25, 62, 49, 68, 27, 10, 14, 36, 73, 28, 85, 52, 20, 84, 46, 0, 44, 76, 93, 92, 70, 24, 58, 64, 39, 90, 106, 84, 21, 28, 105, 20, 1, 48, 42, 100, 101, 42, 43, 104, 100, 28, 12, 52, 19, 40, 115, 112, 28, 128, 10, 76, 55, 82, 18, 0, 28, 102, 79, 100, 20, 128, 133, 32, 120, 100, 120, 28, 127, 112, 135, 40, 138, 116, 130, 20, 105, 64, 57, 84, 145, 74, 35, 28, 53, 110, 28, 148, 127, 136, 0, 68, 166, 116, 94, 100, 134, 14, 103, 36, 180, 166, 178, 28, 91, 180, 104, 52, 24, 20, 40, 84, 152, 46, 161, 100, 61, 44, 49, 76, 125, 196, 82, 196, 123, 70, 37, 24, 31, 58, 105, 172, 42, 148, 55, 200, 144, 106, 86, 84, 100, 134, 186, 28, 115, 220, 112, 20, 177, 118, 75, 48, 37, 42, 63, 100, 153, 222, 64, 164, 35, 166, 66, 228, 157, 100, 57, 28, 13, 12, 25, 52, 93, 148, 217, 40, 136, 246, 107, 244, 130, 28, 205, 128, 63, 10, 240, 212, 196, 192, 200, 220, 252, 18, 73, 140, 219, 28, 130, 244, 85, 222, 84, 244, 127, 20, 214, 128, 52, 280, 225, 180, 145, 120, 105, 100, 105, 120, 145, 180, 225, 280, 38, 112, 196, 290, 83, 196, 6, 138, 280, 116, 277, 130, 310, 180, 58, 266, 161, 64, 300, 220, 148, 84, 28, 310, 271, 240, 217, 202, 195, 196, 205, 222, 247, 280, 321, 28, 84, 148, 220, 300, 41, 136, 239, 0, 118, 244, 25, 166, 315, 116, 280, 94, 273, 100, 294, 134, 343, 196, 55, 286, 158, 36, 289, 180, 77, 352, 262, 178, 100, 28, 339, 280, 227, 180, 139, 104, 75, 52, 35, 24, 19, 20, 27, 40, 59, 84, 115, 152, 195, 244, 299, 360, 28, 100, 178, 262, 352, 44, 145, 252, 365, 76, 200, 330, 55, 196, 343, 82, 240, 404, 157, 332, 94, 280, 51, 248, 28, 236, 25, 244, 42, 272, 79, 320, 136, 388, 213, 42, 310, 148, 427, 274, 125, 420, 280, 144, 12, 328, 205, 86, 418, 308, 202, 100, 2, 360, 271, 186, 105, 28, 412, 344, 280, 220, 164, 112, 64, 20, 445, 410, 379, 352, 329, 310, 295, 284, 277, 274, 275, 280, 289, 302, 319, 340, 365, 394, 427, 464, 20, 64, 112, 164, 220, 280, 344, 412, 484, 66, 145, 228, 315, 406, 2, 100, 202, 308, 418, 28, 145, 266, 391, 12, 144, 280, 420, 52]
GetEntityByID function call status: OK
Search begin...
Search function call status: OK
Entity 50000 top 10 search result:
	50000	0
	50001	511
	50002	21123
	50003	138546
	50004	140389
	50005	145707
	50006	150837
	50007	162081
	50008	167474
	50009	173888
Entity 150000 top 10 search result:
	150000	0
	150001	83940
	150002	279677
	150003	576960
	150005	643994
	150004	644384
	150006	644738
	150007	646229
	150008	655935
	150009	659727
Entity 250000 top 10 search result:
	250000	0
	250001	280824
	250002	282916
	250003	283530
	249999	427073
	250004	523038
	250005	523492
	250006	524979
	249998	570063
	249996	826883
Entity 350000 top 10 search result:
	350000	0
	350001	5410
	350002	190726
	350003	249643
	349998	579706
	349999	581274
	349997	647482
	350004	649474
	350005	709872
	349994	746455
Entity 450000 top 10 search result:
	450000	0
	450001	511
	450002	2049
	450003	4582
	450004	8117
	450005	57298
	450006	82186
	450007	87612
	450008	94729
	449999	191990
Search totally cost: 1075 ms
```

**Comment by rosaline1995** [comment]
> Here is the C++ SDK Api.
> https://github.com/milvus-io/milvus/blob/0.10.3/sdk/include/MilvusApi.h

Thanks! I can find struct with similar names such as IndexParam, VectorParam and so on. But I cannot find a struct named CollectionParam in this file... That is why I am confused and ask this question.

**Comment by rosaline1995** [comment]
> Here is the benchmark-test:
> https://github.com/milvus-io/ann-benchmarks

Thanks! I can run those tests, but may I ask if it's possible to run the C++ code in qps (https://github.com/milvus-io/milvus/tree/0.10.3/sdk/examples/qps) and partion (https://github.com/milvus-io/milvus/tree/0.10.3/sdk/examples/partition)? After running `build.sh` and checking the source code, I didn't find related code to generate executable files for these two. There are only `sdk_simple` and `sdk_binary`.

**Comment by shengjun1985** [comment]
> > Here is the C++ SDK Api.
> > https://github.com/milvus-io/milvus/blob/0.10.3/sdk/include/MilvusApi.h
> 
> Thanks! I can find struct with similar names such as IndexParam, VectorParam and so on. But I cannot find a struct named CollectionParam in this file... That is why I am confused and ask this question.

Line 66
Did you checkout the branch 0.10.3?

**Comment by rosaline1995** [comment]
Oh! Thank you so much, @shengjun1985 ! I finally realize the reason! I kept using the code from the master branch and didn't even notice other versions. Then it makes much more sense. Sorry for the trouble caused. And thank you very much for your patience!

**Comment by shengjun1985** [comment]
You may be facing a common problem.
Later, we will update our documents to improve the operation process.
Thank you for your concern and support for our project.
