### ISSUE TITLE
c++ sdk segmentation fault

### ISSUE THREAD

**Issue by zhoukk** [milvus-io/milvus#3811]
**Describe the bug**
will crash, the  client_ptr_ in ClientProxy is null ptr

https://github.com/milvus-io/milvus/blob/836a247b6ab9cd023c16b5c0a2c799adb88157f1/sdk/grpc/ClientProxy.cpp#L411

**Steps/Code to reproduce behavior**
std::shared_ptr<milvus::Connection> db = milvus::Connection::Create();
milvus::Status stat = db->Connected();

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [*] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
master

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by fishpenguin** [comment]
This is because that you didn't call Connect(param) to connect server, you can call connect fucntion first.
However, this is a bug that we don't give a clear explain why it will segment fault, We will fix it soon.

**Comment by shengjun1985** [comment]
Fixed in 0.11.0
