### ISSUE TITLE
Big gap in client and server handling on inserting entities

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#3813]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
client log:
```
10:43:28  2020-09-19 02:43:27,622 - milvus_benchmark.runner - INFO - Start id: 471400000, end id: 471500000
10:43:28  INFO:milvus_benchmark.runner:Start id: 471400000, end id: 471500000
10:43:43  2020-09-19 02:43:41,676 - milvus_benchmark.client - INFO - Milvus insert run in 13.94s
10:43:43  INFO:milvus_benchmark.client:Milvus insert run in 13.94s
10:43:43  2020-09-19 02:43:41,690 - milvus_benchmark.client - DEBUG - Row count: 471400000 in collection: <sift_1b_4000000_128_l2>
10:43:43  DEBUG:milvus_benchmark.client:Row count: 471400000 in collection: <sift_1b_4000000_128_l2>
10:43:43  2020-09-19 02:43:41,693 - milvus_benchmark.runner - DEBUG - 471400000
10:43:43  DEBUG:milvus_benchmark.runner:471400000
```
client insert time per request: `13s`
the time spend in server log: `in 1s`
```
[2020-09-19 10:45:46,692][INFO][SERVER][Insert][grpcpp_sync_ser] Request [14164] Insert begin.
[2020-09-19 10:45:46,801][INFO][SERVER][OnExecute][reqsched_thread] [insert][0] Execute InsertReq.
[2020-09-19 10:45:46,840][INFO][SERVER][Insert][grpcpp_sync_ser] Request [14164] Insert end.
[2020-09-19 10:45:47,060][INFO][SERVER][CountCollection][grpcpp_sync_ser] Request [14165] CountCollection begin.
[2020-09-19 10:45:47,061][INFO][SERVER][CountCollection][grpcpp_sync_ser] Request [14165] CountCollection end.
[2020-09-19 10:46:06,275][INFO][SERVER][DescribeCollection][grpcpp_sync_ser] Request [14166] DescribeCollection begin.
[2020-09-19 10:46:06,276][INFO][SERVER][DescribeCollection][grpcpp_sync_ser] Request [14166] DescribeCollection end.
[2020-09-19 10:46:15,668][INFO][SERVER][Insert][grpcpp_sync_ser] Request [14167] Insert begin.
[2020-09-19 10:46:15,772][INFO][SERVER][OnExecute][reqsched_thread] [insert][0] Execute InsertReq.
[2020-09-19 10:46:15,812][INFO][SERVER][Insert][grpcpp_sync_ser] Request [14167] Insert end.
[2020-09-19 10:46:16,066][INFO][SERVER][CountCollection][grpcpp_sync_ser] Request [14168] CountCollection begin.
[2020-09-19 10:46:16,067][INFO][SERVER][CountCollection][grpcpp_sync_ser] Request [14168] CountCollection end.
[2020-09-19 10:46:35,523][INFO][SERVER][DescribeCollection][grpcpp_sync_ser] Request [14169] DescribeCollection begin.
[2020-09-19 10:46:35,531][INFO][SERVER][DescribeCollection][grpcpp_sync_ser] Request [14169] DescribeCollection end.

```
**Steps/Code to reproduce behavior**
dataset; sift-1b
vector length: 100000
server deployed on Apollo by `milvus-helm`, data stored on NAS, with sqlite store engine. All pods generated in the same k8s cluster.

**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
```
{"cache.cache_insert_data":"false","cache.cache_size":"4GB","cache.cpu_cache_threshold":"0.700000","cache.insert_buffer_size":"1GB","cache.preload_collection":"","cluster.enable":"false","cluster.role":"rw","engine.build_index_threshold":"4096","engine.omp_thread_num":"0","engine.search_combine_nq":"64","engine.simd_type":"auto","engine.use_blas_threshold":"1100","general.meta_uri":"sqlite://:@:/","general.timezone":"UTC+8","gpu.build_index_devices":"gpu0,","gpu.cache_size":"1GB","gpu.cache_threshold":"0.700000","gpu.enable":"false","gpu.gpu_search_threshold":"1000","gpu.search_devices":"gpu0,","logs.level":"debug","logs.log_rotate_num":"0","logs.max_log_file_size":"1GB","logs.path":"/test/milvus/db_data_011/sift_1b_4000000_128_l2/logs","logs.trace.enable":"true","metric.address":"192.168.1.237","metric.enable":"true","metric.port":"9091","network.bind.address":"0.0.0.0","network.bind.port":"19530","network.http.enable":"true","network.http.port":"19121","storage.auto_flush_interval":"1","storage.path":"/test/milvus/db_data_011/sift_1b_4000000_128_l2","system.lock.enable":"true","tracing.json_config_path":"","transcript.enable":"false","transcript.replay":"","version":"0.5","wal.buffer_size":"256MB","wal.enable":"true","wal.path":"/test/milvus/db_data_011/sift_1b_4000000_128_l2/wal","wal.recovery_error_ignore":"true"}
```
```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by fishpenguin** [comment]
This issue can be reproduced when source data is serialized to naas. It's because wal is open, the timing_flush operation and wal will write to naas at the same time, which causes the time overhead.
When wal is close, this issue won't appear.

**Comment by godchen0212** [comment]
Wal directory should be set to local disk rather than NAS disk.

**Comment by godchen0212** [comment]
The testing environment has low network bandwidth which mainly causes the big gap. 

After experiments, we find the network transmission rate is about 10M/s-12M/s. And when inserting 100000 vector with 128 dimension, the request data size is about 50M, the transmission time is approximately 4-5 seconds.

If we enable wal, the network transmission rate is about 6M/s-8M/s for wal occupies bandwidth to write NAS files. A request with 50M size requires about 6-8 seconds sent to the server which is same phenomenon as mentioned in issue.

And we can find the insert request processing time is about 0.3s. It is normal in our milvus server.
So, it is not a bug. We recommend improve network bandwidth to solve the problem extremely when the request packet is large.

Large request mainly appears in insert and search request. Some reference size is shown as follows 
50M request data: 100K vector, 128 dimension

Extra attention: The largest request packet that can be received in our server is 256M.
 
If a similar problem occurs, please check your request packet size and network transmission rate.
