### ISSUE TITLE
[Bug]: list_bulk_insert_tasks returns missing fields

### ISSUE THREAD

**Issue by abd-770** [milvus-io/milvus#38172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Running bulk insert and use list_bulk_insert_tasks to check the status

```
id = utility.do_bulk_insert(collection_name=collection_name, files=['bulk/json/01/1.json'])
tasks = utility.list_bulk_insert_tasks()
for task in tasks:
  print(task)
```
Output:

```
<Bulk insert state:
    - taskID          : 0,
    - state           : Completed,
    - row_count       : 0,
    - infos           : {'failed_reason': '', 'progress_percent': '100'},
    - id_ranges       : [],
    - create_ts       : 1969-12-31 16:00:00
>
```
However,

1. taskId is incorrect
2. row_count is wrong
3. id_ranges is wrong
4. create_ts is wrong

### Expected Behavior

`list_bulk_insert_tasks` should return correct values for the above fields.
Also, why does it not return other fields as mentioned in the documentation: https://milvus.io/api-reference/pymilvus/v2.4.x/ORM/utility/list_bulk_insert_tasks.md

**Comment by yanliang567** [comment]
a similar issue to https://github.com/milvus-io/milvus/issues/38051, please check

/assign @abd-770 
/unassign

**Comment by abd-770** [comment]
@yanliang567 We are currently using milvus 2.4.x, and this issue is for function `list_bulk_insert_tasks` returning invalid values for the returned fields.

**Comment by yanliang567** [comment]
/assign @bigsheeper 
please help to take a look

**Comment by abd-770** [comment]
@yanliang567 @bigsheeper can you guys provide an update on this?
Please update on this issue as well: https://github.com/milvus-io/milvus/issues/38051

**Comment by abd-770** [comment]
@yanliang567 Any updates?

**Comment by bigsheeper** [comment]
> @yanliang567 Any updates?

Hi @abd-770 ,

In version 2.4.x, we restructured the bulkinsert feature to enhance both performance and usability. Along with these improvements, the returned fields have also been adjusted accordingly(for example, `row_count ` -> `importedRows ` & `totalRows `).
For more details, please refer to the updated documentation here: https://milvus.io/docs/import-data.md.

**Comment by abd-770** [comment]
@bigsheeper I'm currently using 2.4.0, So is this an expected bug for this version? Also can you specify which version the enhancements are added?

**Comment by bigsheeper** [comment]
> @bigsheeper I'm currently using 2.4.0, So is this an expected bug for this version? Also can you specify which version the enhancements are added?

Hi @abd-770 ,

> So is this an expected bug for this version?
This behavior is not a bug but is intended by design.

> Also can you specify which version the enhancements are added?
Starting from version 2.4.0. We recommend referring to the 2.4 documentation and using the corresponding APIs: https://milvus.io/docs/import-data.md.
