### ISSUE TITLE
[Bug]: milvus v2.4.17 在k8s上启动失败

### ISSUE THREAD

**Issue by xmsh** [milvus-io/milvus#38205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.4.17
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu 
- CPU/Memory: 46c62G
- GPU: A10
- Others:
```

### Current Behavior

![40f505fe9a78a4aa01f1d67ff02dc83](https://github.com/user-attachments/assets/504f6911-f629-4a75-8764-55e1fbf5dbbe)
![36b4e340d4c5e10eae2cc023700923b](https://github.com/user-attachments/assets/d8d24423-550c-433a-a306-e5fdd80a5e6f)

**Comment by yanliang567** [comment]
according to the msg, it seems that milvus pod lost heartbeat with etcd, so it rebooted itself. please double check 
1. the etcd service is running against ssd volume for higher performance
if it reproduced for you, please attach the milvus logs and etcd logs.

Please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation.

/assign @xmsh 
/unassign

**Comment by xmsh** [comment]
![fcf6ad5b71ca8690409ac160e3bf659](https://github.com/user-attachments/assets/e86a5e08-efb4-4f11-9a14-fa2b3252d511)
这个etcd不是显示连接成功了吗？而且etcd的3个pod状态都是正常的

**Comment by xmsh** [comment]
[milvus-log.tar.gz](https://github.com/user-attachments/files/18006523/milvus-log.tar.gz)

**Comment by tinswzy** [comment]
> [milvus-log.tar.gz](https://github.com/user-attachments/files/18006523/milvus-log.tar.gz)

Hello, after analyzing the log information you provided, it seems that RootCoord failed to connect to Pulsar. However, the error message from the Pulsar client is not very clear:
```
[2024/12/04 10:28:32.340 +00:00] [WARN] [retry/retry.go:46] ["retry func failed"] [retried=0] [error="connection error"].
```
Please check whether your Pulsar cluster is running normally or if the network connection between Milvus and Pulsar is accessible.
Additionally, we will adjust this error message to make it more explicit.

**Comment by xmsh** [comment]
是的，没有启动Pulsar，我使用helm template my-release milvus/milvus --version=4.2.25 > milvus_manifest.yaml获取的yaml文件中没有定义pulsar。

**Comment by tinswzy** [comment]
> 是的，没有启动Pulsar，我使用helm template my-release milvus/milvus --version=4.2.25 > milvus_manifest.yaml获取的yaml文件中没有定义pulsar。

Startup logs indicate that Pulsar is being used. The cluster mode uses Pulsar by default.
```
[2024/12/04 10:26:39.844 +00:00] [INFO] [dependency/factory.go:85] ["try to init mq"] [standalone=false] [mqType=pulsar]
```
