### ISSUE TITLE
Error when build milvus 0.10.3  from source on CentOs7

### ISSUE THREAD

**Issue by nestea1949** [milvus-io/milvus#3824]
With all denpencies installed,when run build.sh -t Debug,errors show :
Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /usr/local/softwares/milvus-0.10.3/core/cmake_build/prometheus_ep-prefix/src/prometheus_ep/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_4563e/fast
gmake[3]: Entering directory `/usr/local/softwares/milvus-0.10.3/core/cmake_build/prometheus_ep-prefix/src/prometheus_ep/CMakeFi
les/CMakeTmp'
/usr/bin/gmake -f CMakeFiles/cmTC_4563e.dir/build.make CMakeFiles/cmTC_4563e.dir/build
gmake[4]: Entering directory `/usr/local/softwares/milvus-0.10.3/core/cmake_build/prometheus_ep-prefix/src/prometheus_ep/CMakeFi
les/CMakeTmp'
Building C object CMakeFiles/cmTC_4563e.dir/CheckFunctionExists.c.o
/usr/bin/cc   -g -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_4563e.dir/CheckFunctionExists.c.o   -c /opt/c
make-3.14.0/share/cmake-3.14/Modules/CheckFunctionExists.c
Linking C executable cmTC_4563e
/opt/cmake-3.14.0/bin/cmake -E cmake_link_script CMakeFiles/cmTC_4563e.dir/link.txt --verbose=1
/usr/bin/cc  -g -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_4563e.dir/CheckFunctionExists.c.o  -o cmTC_4563e
 -lpthreads
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
gmake[4]: *** [cmTC_4563e] Error 1
gmake[4]: Leaving directory `/usr/local/softwares/milvus-0.10.3/core/cmake_build/prometheus_ep-prefix/src/prometheus_ep/CMakeFil
es/CMakeTmp'
gmake[3]: *** [cmTC_4563e/fast] Error 2
gmake[3]: Leaving directory `/usr/local/softwares/milvus-0.10.3/core/cmake_build/prometheus_ep-prefix/src/prometheus_ep/CMakeFil
es/CMakeTmp'

**Comment by shengjun1985** [comment]
Please try to compile Milvus on Docker:
[Note] The images in the steps is for ubuntu18.04.
https://github.com/milvus-io/milvus/blob/master/INSTALL.md#compile-milvus-on-docker

Here is the CPU image of CentOs7
https://hub.docker.com/layers/milvusdb/milvus-cpu-build-env/v0.7.0-centos7/images/sha256-6de04fabd4e13b84fa91f98ed16f7023b92a5fe45751f90a9043eaa244990178?context=explore

Here is the GPU image of CentOs7
https://hub.docker.com/layers/milvusdb/milvus-gpu-build-env/v0.7.0-centos7/images/sha256-8368537775aae6179a37bcef3468a8948f84b5c9bb1311722d2f03c81b1d3acd?context=explore

**Comment by nestea1949** [comment]
> Please try to compile Milvus on Docker:
> [Note] The images in the steps is for ubuntu18.04.
> https://github.com/milvus-io/milvus/blob/master/INSTALL.md#compile-milvus-on-docker
> Here is the CPU image of CentOs7
> https://hub.docker.com/layers/milvusdb/milvus-cpu-build-env/v0.7.0-centos7/images/sha256-6de04fabd4e13b84fa91f98ed16f7023b92a5fe45751f90a9043eaa244990178?context=explore
> Here is the GPU image of CentOs7
> https://hub.docker.com/layers/milvusdb/milvus-gpu-build-env/v0.7.0-centos7/images/sha256-8368537775aae6179a37bcef3468a8948f84b5c9bb1311722d2f03c81b1d3acd?context=explore
Now it compiles  successfully and  the  milvus server starts . Another question is how can i  move the whole server to a new Linux server which has no docker or virtualization support

**Comment by scsven** [comment]
@nestea1949 Please try to compile this code below on host.

```c++
// main.cpp

#include <iostream>            
#include <thread>              

void test() {
    std::cout << "it's ok" << std::endl;
}

int main() {
    std::thread t1(test);
    t1.join();
    return 0;
}
```

```Makefile
# Makefile

all: test                      

test: main.cpp                 
    g++ $^ -o $@ -lpthread
```

Compile and run:

```bash
make
./test
```

**Comment by nestea1949** [comment]
> @nestea1949 Please try to compile this code below on host.
> // main.cpp
> 
> #include <iostream>            
> #include <thread>              
> 
> void test() {
>     std::cout << "it's ok" << std::endl;
> }
> 
> int main() {
>     std::thread t1(test);
>     t1.join();
>     return 0;
> }
> # Makefile
> 
> all: test                      
> 
> test: main.cpp                 
>     g++ $^ -o $@ -lpthread
> Compile and run:
> make
> ./test

it is ok

**Comment by scsven** [comment]
@nestea1949 Please provide complete log output. Maybe some other error occurred.
