### ISSUE TITLE
The Config file of Milvus can set the number of decimal places in the result of a query

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#3825]
People at sohu say this setting is useful because the result of the query, rounded up with python's round function, takes three times longer than all the other commands combined.It's a question someone on StackOverflow asked.

**Comment by BossZou** [comment]
@jingkl , May I ask that why you need to round up result of the query?

**Comment by yhmo** [comment]
Consider to add a "round_decimal" parameter in search parameters, such as:
SEARCH_PARAM = {'nprobe': 16, "round_decimal": 3}

**Comment by yhmo** [comment]
My proposal is to add a "round_decimal" parameter in search parameters, this is a TODO/NewFeature to milvus developers.
This new feature will be discussed in technical meeting.

**Comment by jingkl** [comment]
For this question refer to the issue #4818
