### ISSUE TITLE
[Bug]: [Nightly] Cluster pulsar ran too slow and failed for timeout(6h)

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#38260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 6ff1948
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Cluster pulsar ran too slow and failed for timeout(6h).
link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI(new)/detail/master/203/pipeline/156/
log: [artifacts-milvus-distributed-streaming-service-mdss-master-203-py-n-203-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI(new)/job/master/203/artifact/artifacts-milvus-distributed-streaming-service-mdss-master-203-py-n-203-e2e-logs.tar.gz)

expect: finish in 3h30min
actual: 86% in 6h (no error, just slow)

### Expected Behavior

pass

**Comment by NicoYuan1986** [comment]
@chyezh Can you help take a look?

**Comment by NicoYuan1986** [comment]
@congqixia Can you help take a look?

**Comment by yanliang567** [comment]
not reproduced recently
