### ISSUE TITLE
More time overhead when searching binary top-k=1 comparing with top-k=10

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#3839]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
![scrnli_9_22_2020_3-03-55 PM](https://user-images.githubusercontent.com/56623710/93852636-f6b4ab80-fce4-11ea-9174-22ac48f45e37.png)

**Steps/Code to reproduce behavior**
```
dataset: binary_50m_512d
metric_type: JACCARD
index_type: bin_flat
```
log path:
```
/test/milvus/db_data_011/binary_50m_4000000_512_jaccard/logs
```
**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by cqy123456** [comment]
The searching performance of top1 and top10 are almost the same when testing in nowhere.
However, the extra cost of searching is different in engine. And we will optimize this part later.

**Comment by JinHai-CN** [comment]
The performance testing need to be unified.

**Comment by del-zhenwu** [comment]
![Uploading scrnli_9_27_2020_1-59-50 PM.png…]()
if run with top-k=10 firstly, then run with top-k=1,  there is the same performance.

**Comment by shengjun1985** [comment]
row_limit = 4,000,000; n = 10,000,000; dim = 512; index_type = Bin_Flat; metric_type = JACCARD;
nq = 1000;

topk = 1
cost time 2477
cost time 2400
cost time 2385
cost time 2380
cost time 2378
cost time 2378
cost time 2370
cost time 2380
cost time 2370
cost time 2399
cost time 2374
cost time 2453
cost time 2412
cost time 2420
cost time 2371
cost time 2384
cost time 2366
cost time 2376
cost time 2367
cost time 2370
total cost time 47810

topk = 10
cost time 2388
cost time 2373
cost time 2381
cost time 2378
cost time 2387
cost time 2378
cost time 2376
cost time 2381
cost time 2380
cost time 2379
cost time 2388
cost time 2448
cost time 2429
cost time 2403
cost time 2395
cost time 2390
cost time 2381
cost time 2378
cost time 2384
cost time 2395
total cost time 47792

Here are the multiple tests results in my local machine.
The query time of the two cases are similar. But the variances of them are not small.
Moreover, I have checked the implementation strategy for these two situations, and they are the same.
So, I don't think we need to pay more attention to this issue.
Furthermore, If I have time later, I will try to improve the performance of binary flat with larger NQ.

**Comment by sibadakesi** [comment]
我这边512维度的向量，采用的IndexType.IVFLAT 索引为什么top_k为１和topk为10的时候速度相差十倍，继续增大topk的时候速度还会更慢.我看官网介绍topk是不影响速度的呀.

**Comment by shengjun1985** [comment]
@sibadakesi
What's your Milvus version, row_count, dim and nq?

**Comment by sibadakesi** [comment]
> @sibadakesi
> 您的Milvus版本是什么，row_count，dim和nq？

你好，我的milvus的版本是milvus:0.8.0-cpu ,row_count 3000w左右，单个partition_tag的数量为400w左右,dim为512，nq为10000,在检索一个向量时如果topk=100,需要一分多钟。我的内存读取设置的是16GB。

**Comment by shengjun1985** [comment]
@sibadakesi
The query performance of big NQ and big TOPK is optimized in version 0.10.2.
So it is suggest to use our latest version (0.10.5).
In addition, your data is far larger than your memory size (3000 * 10000 * 512 * 4 = 64G), so the performance will not be good.

**Comment by sibadakesi** [comment]
> @sibadakesi
> 在0.10.2版中优化了大NQ和大TOPK的查询性能。
> 因此建议使用我们的最新版本（0.10.5）。
> 此外，您的数据（3000 * 10000 * 512 * 4 = 64G）远远大于内存大小，因此性能将不佳。

好的谢谢，能否有快速升级版本的方法，比如我安装新版本的docker并将目录映射我老的版本的地址上。还是说我必须安装新的版本然后重新插入向量和构建索引。

**Comment by yhmo** [comment]
To migrate old version to new version, you can follow this article: https://zhuanlan.zhihu.com/p/274448542
Ideally, the 0.10.x can compatible with 0.7.x/0.8.x/0.9.x. But if you encountered problem, we recommend you re-insert vector and re-build index on new version.

**Comment by sibadakesi** [comment]
我已经将版本更新到新版本，检索速度还是跟topk有很大的变化如果topk=1那么只要1s，如果topk=100 大概需要100s.

**Comment by shengjun1985** [comment]
@sibadakesi 
Can you show the result of the command "lscpu"?

**Comment by sibadakesi** [comment]
> @sibadakesi
> 您可以显示命令“ lscpu”的结果吗？
好的，下面是lscpu的结果
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                6
On-line CPU(s) list:   0-5
Thread(s) per core:    1
Core(s) per socket:    6
座：                 1
NUMA 节点：         1
厂商 ID：           GenuineIntel
CPU 系列：          6
型号：              79
型号名称：        Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz
步进：              1
CPU MHz：             1199.981
CPU max MHz:           1700.0000
CPU min MHz:           1200.0000
BogoMIPS：            3396.07
虚拟化：           VT-x
L1d 缓存：          32K
L1i 缓存：          32K
L2 缓存：           256K
L3 缓存：           15360K
NUMA 节点0 CPU：    0-5
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm arat pln pts

**Comment by sibadakesi** [comment]
> @sibadakesi
> Can you show the result of the command "lscpu"?

好的，下面是lscup的显示:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                6
On-line CPU(s) list:   0-5
Thread(s) per core:    1
Core(s) per socket:    6
座：                 1
NUMA 节点：         1
厂商 ID：           GenuineIntel
CPU 系列：          6
型号：              79
型号名称：        Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz
步进：              1
CPU MHz：             1199.981
CPU max MHz:           1700.0000
CPU min MHz:           1200.0000
BogoMIPS：            3396.07
虚拟化：           VT-x
L1d 缓存：          32K
L1i 缓存：          32K
L2 缓存：           256K
L3 缓存：           15360K
NUMA 节点0 CPU：    0-5
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm arat pln pts

**Comment by shengjun1985** [comment]
@sibadakesi
It seems that your CPU is quite OK.
We found that your data (64g) is much larger than memory (16G).
It is suspected that the quick response is memory access, and the slow response is disk access.
So, I want to know how did you test it.
Is your query for a partition or for a collection?
Do you query on the same partition repeatedly?

**Comment by shengjun1985** [comment]
@ThreadDao 
This issue initially discussed Jaccard distance.
Binary performance is improved much on v0.10.6.
Please see if this issue can be closed.

**Comment by shengjun1985** [comment]
@sibadakesi
Your problem is quite different with this issue.
If you still need help, it is recommended to create a new issue. And describe your test environment and the test sequence in detail.
Thank you.
