### ISSUE TITLE
[Bug]: The radius and range_filter parameters of searh in the Java SDK are not effective

### ISSUE THREAD

**Issue by yongxin3344520** [milvus-io/milvus#38407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.5.0-beta/v2.5.0-beta-gpu
- standalone  
- SDK version: java-2.5.0
- win10
```

### Current Behavior

this is my part code :

Map<String, Object> stringObjectMap = searchParams(indexType) ;

        ((Map<String, Object>)stringObjectMap.get("params")).put("radius",  0.8);
        ((Map<String, Object>)stringObjectMap.get("params")).put("range_filter", 1.2f);

        SearchReq searchReq = SearchReq.builder()
                .data(data)
                .annsField(VECTOR_FIELD)
                .searchParams(stringObjectMap )
                .collectionName(collectionName)
                .partitionNames(selectParts.isEmpty() ? parts : new ArrayList<>(selectParts))
                .limit(Math.min(500, topK))
                .topK(Math.min(500, topK))
                .filter(ids.isEmpty() ? "" : (" id in [" + ids.toString() + "]"))
                .build();

        SearchResp searchResp = null ;

        MilvusClientV2 client = pool.getClient(key);

        // load
        client.loadCollection(LoadCollectionReq.builder().collectionName(collectionName).build());

        try {
            searchResp = client.search(searchReq);
        }catch (Exception e){
            log.error("", e);
        }finally {
            pool.returnClient(key, client);
        }

--------------------

private Map<String, Object> searchParams(IndexParam.IndexType indexType){
        Map<String, Object> objectMap = new HashMap<>();

        switch (indexType){
            case IndexParam.IndexType.IVF_PQ:
                objectMap.put("metric_type", "IP");
                Map<String, Object> param0 = new HashMap<>();
                param0.put("nprobe", 8);
                objectMap.put("params", param0);
                break;
            case IndexParam.IndexType.IVF_FLAT:
                objectMap.put("metric_type", "IP");
                Map<String, Object> param1 = new HashMap<>();
                param1.put("nprobe", 8);
                objectMap.put("params", param1);
                break;
            case IndexParam.IndexType.IVF_SQ8:
                objectMap.put("metric_type", "IP");
                Map<String, Object> param2 = new HashMap<>();
                param2.put("nprobe", 8);
                objectMap.put("params", param2);
                break;

            case IndexParam.IndexType.GPU_CAGRA:
                objectMap.put("metric_type", "IP");
                Map<String, Object> param3 = new HashMap<>();
                // param3.put("itopk_size", 128);
                objectMap.put("params", param3);
                break;

            case IndexParam.IndexType.GPU_IVF_FLAT:
                objectMap.put("metric_type", "IP");
                Map<String, Object> param4 = new HashMap<>();
                param4.put("nprobe", 8);
                objectMap.put("params", param4);
                break;

            case IndexParam.IndexType.GPU_IVF_PQ:
                objectMap.put("metric_type", "IP");
                objectMap.put("index_type", "GPU_IVF_PQ");
                Map<String, Object> param5 = new HashMap<>();
                param5.put("nprobe", 8);
                objectMap.put("params", param5);
                break;

            default:
                throw new RuntimeException("ERROR INDEX TYPE:"+indexType);
        }
        return objectMap;
    }

----------

### Expected Behavior

The radius and range_filter parameters of sealh in the Java SDK are not effective,  Those with similarity below the threshold were also queried.
Using Python is normal

**Comment by xiaofan-luan** [comment]
I don't think GPU index support range search. 

@liliu-z can you confirm?

**Comment by yongxin3344520** [comment]
These two parameters work in both GPU and CPU versions using Python, but do not work in Java CPU and GPU versions

**Comment by xiaofan-luan** [comment]
@yanliang567 
could you help on verify it?

**Comment by yongpengli-z** [comment]
This may be a problem，help confirm whether the method of passing parameters is correct @yhmo,Java-sdk search returns results, but python does not.
![image](https://github.com/user-attachments/assets/01c945e2-8752-4a3a-93d4-74dc61b06aad)
python 👇
range search:
>>> default_search_params = {"metric_type": "IP", "params": {"nprobe": 10, "radius":0.8, "range_filter": 1.2}}
>>> res = c.search(vectors[:nq], "fieldFloatVector", default_search_params, limit, "fieldInt64 >= 0")
>>> res
data: ['[]']

**Comment by yongpengli-z** [comment]
![image](https://github.com/user-attachments/assets/008217bd-b26b-472a-a93b-5af8729efec7)
@yongxin3344520

**Comment by yongxin3344520** [comment]
At least 3 weeks ago, I received your email reply and immediately conducted testing, and it was able to take effect. As of now, it is still stable and effective.  
Thank you very  much ！！！
