### ISSUE TITLE
Allowing multi-field vector ids

### ISSUE THREAD

**Issue by keotic** [milvus-io/milvus#3844]
**What would you like to be added ?**
Capability to add vectors with multi-keys ids would be great.
for example using id (0,0) to sentence 0 of document 0, and (0,1) to to sentence 1 of document 0 etc..

**Why is this needed ?**
This feature will make it much easier to index and retrieve vectors with multi-keys id.
Instead of making the mapping from multi-key to a single 64 int Id and then indexing the vector, it can be done seamlessly

**Comment by shengjun1985** [comment]
We will add the feature in v0.11.0.

**Comment by shengjun1985** [comment]
Milvus supported multiple scalar fields in v0.11.0.
It may solve your issue.

In addition, if your sentence number and document number are not too large,  I think you can also solve your issue by encoding the ID.
If you have more questions, please continue to contact our community.
