### ISSUE TITLE
[Bug]: Zilliz Cloud Colpali Search Vector Limit

### ISSUE THREAD

**Issue by TheAppCrafter** [milvus-io/milvus#38515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: Zilliz Cloud (compatible with Milvus 2.4.x)
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): tried both v2.4.10 and v2.5.0
- OS(Ubuntu or CentOS): 
- CPU/Memory: Mac M1 16GB
- GPU: None used
- Others:
```

### Current Behavior

I am building a RAG system based on Colpali. When searching the Zilliz cloud database I get the error: 'nq [23] is invalid, nq (number of search vector per search request) should be in range [1, 10], but got 23'

I'm performing the search like so:
            search_params = {"metric_type": "IP", "params": {}}
            results = self.client.search(
                collection_name,
                data,
                limit=int(50*topk),
                output_fields=["user_id", "doc_id", "page_id"],
                search_params=search_params,
            )

This only occurs on Zilliz Cloud and not Milvus light. 

I followed the colpali instructions you've provided here: https://milvus.io/docs/use_ColPali_with_milvus.md

This is the shape of my query query tensors: torch.Size([23, 128])

It seems that there is a small limit for dimensions in a multivector embedding in Zilliz Cloud that doesn't exist for Milvus light. If this is the case do you know when this limit will be lifted for Zilliz Cloud?

**Comment by yanliang567** [comment]
For privacy issue, please file a ticket for Zilliz Cloud issues. @TheAppCrafter 
I'd close this issue if you agree

**Comment by TheAppCrafter** [comment]
I thought it may have been an issue within a certain version of Milvus but it seems this limitation is with certain clusters in Zilliz Cloud only. I will reach out to Zilliz Cloud support, thanks.

**Comment by xiaofan-luan** [comment]
On Zilliz cloud Serverless tier, you get a limitation of nq < 10.

We are working on multi vector support and I guess this is what you really need. You store multi vector in one array (like an tensor). Under search, milvus will did the similarity match and maxsim operator for you.

@liliu-z is working on that and this might be on our next release

**Comment by michaelbridge** [comment]
Any update here re: multi-vector/max-sim support?

**Comment by xiaofan-luan** [comment]
> Any update here re: multi-vector/max-sim support?

This is on progress and might be released on Q2 or Q3 2025.

probably not something we can offer in short term. 

But the embedding list we support will actually have more than just maxsim, there will be multi metrics including dtw or even attention.
please track here https://github.com/milvus-io/milvus/issues/37090

**Comment by adit-0503** [comment]
Hi @xiaofan-luan Any updates on when this will be live?

**Comment by xiaofan-luan** [comment]
> Hi [@xiaofan-luan](https://github.com/xiaofan-luan) Any updates on when this will be live?

Multi Vector Support will be in 2.6.3, which could be in the next 1-2 weeks.
