### ISSUE TITLE
Use a common prefix for metrics

### ISSUE THREAD

**Issue by thirstycrow** [milvus-io/milvus#3854]
**Please state your issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**
It's hard to find milvus metrics if the prometheus instance also holds metrics for other kind of services, especially on grafana 7.x which uses prefixes to category metrics, and no longer supports full text searching.

**Describe the solution you'd like**
Use a `milvus_` prefix for all milvus metrics

**Comment by shengjun1985** [comment]
same as #3176
