### ISSUE TITLE
[Bug]: unexpected balance task after mixcoord restarts

### ISSUE THREAD

**Issue by weiliu1031** [milvus-io/milvus#38606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4 and master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. during querycoord restarts, querycoord will save collection's current target to meta, and recover it after new querycoord startup
2. the current target meta doesn't include segment's row num
3. when dist_handler update segment dist, it will get rowcount info from target, so segment's row count in dist becomes zero
4. balancer will get segment's row count info from target, then compute logic get the wrong score, and trigger some unexpected balance task

**Comment by xiaofan-luan** [comment]
should be fixed and verified
