### ISSUE TITLE
The values of the IVF_PQ parameter `m`.

### ISSUE THREAD

**Issue by Bennu-Li** [milvus-io/milvus#3870]
**Please state your issue using the following template and, most importantly, in English.**

**Location of incorrect documentation**
https://milvus.io/docs/v0.10.3/index.md#IVF_PQ

**Describe the problems or issues found in the documentation**
Milvus 0.10.3 adds more valid values to the indexing parameter m of IVF_PQ.

**Suggested fix for documentation**
An m is valid so long as it can be divided by dim, which represents the number of vector dimensions.
![image](https://user-images.githubusercontent.com/53458891/94236854-712d3780-ff40-11ea-9e24-f0060ac4e108.png)

**Comment by shengjun1985** [comment]
@Bennu-Li @JackLCL 
Is the following description clear?
https://github.com/milvus-io/milvus/issues/3254#issuecomment-690071274

**Comment by JackLCL** [comment]
Yes, it's clear.

**Comment by shengjun1985** [comment]
The notes is updated.
