### ISSUE TITLE
 remote request partition about milvus-em

### ISSUE THREAD

**Issue by wq1315** [milvus-io/milvus#3877]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
When I use the local milvus-em to request the milvus information of the server, the partition information cannot be requested.
`partitions?page_size=10&offset=0&from=data-menu`
This api is always pending

**Expected behavior**
It is expected that the status of this api request is 200, which can return partition information

**Method of installation**
- [ ] Docker/cpu

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)
cpu
- Milvus version (master or released version)
milvusdb/milvus:0.10.0-cpu

**Comment by shanghaikid** [comment]
please ensure your connection between the machine which runs em and the milvus is accessible to each other.

**Comment by wq1315** [comment]
Let me make an analogy. **_A_** represents the server's public network IP that can be accessed, and **_b_** represents the local IP, which cannot be accessed by other public networks. When opened on a local browser, both **_a_** and **_b_** deployed milvus-em Cannot access the partition information of the server milvus.

**Comment by fishpenguin** [comment]
Have this issue appeared again?

**Comment by scsven** [comment]
Not activity.
