### ISSUE TITLE
Params in Restful-api is different from the params in other SDKs

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#3882]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
python:
```
{"field": vec_field_name, "type": data_type, "params": {"dim": dimension}}
```

java:
```
        Map<String, Object> floatField = new HashMap<>();
        floatField.put("field","float");
        floatField.put("type",DataType.FLOAT);

```

http:
```

            "field_name": "field_vec",
            "field_type": "VECTOR_FLOAT",
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by RifeWang** [comment]
不同分支和 tag 的文档差别较大，建议你查阅所使用版本的 rest 文档，比如 [v0.10.3](https://github.com/milvus-io/milvus/blob/v0.10.3/core/src/server/web_impl/README.md) ，如果对文档有疑惑，你可以直接看 web server 部分的源码，比如 [HTTP 路由部分](https://github.com/milvus-io/milvus/blob/v0.10.3/core/src/server/web_impl/controller/WebController.hpp) 和 [HTTP 请求的处理](https://github.com/milvus-io/milvus/blob/v0.10.3/core/src/server/web_impl/handler/WebRequestHandler.cpp) ，我就是这么看的，刚好自己也整理了一下 https://rifewang.github.io/milvus-rest-doc/#/

**Comment by del-zhenwu** [comment]
need to update params name in JAVA-SDK

**Comment by sahuang** [comment]
In Java SDK 0.9.0, you can insert a field by calling `.addField("int64", DataType.INT64)` or `.addVectorField("float_vec", DataType.VECTOR_FLOAT, dimension)` and there is no need to specify "field_name" or "field_type".
