### ISSUE TITLE
Change params name of create_collection from 'field' to 'name'

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#3901]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
currently:
```
{
    "field": "a",
    "type": "int64",
    "params": {}
}
```
to

```
{
    "name": "a",
    "type": "int64",
    "params": {}
}
```
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by del-zhenwu** [comment]
@shanghaikid

**Comment by shanghaikid** [comment]
I prefer 

{
    "name": "a",
    "type": "int64",
    "params": {}
}

**Comment by scsven** [comment]
Done.
