### ISSUE TITLE
The embedding id is -1  when distance float value overflow

### ISSUE THREAD

**Issue by dhg012** [milvus-io/milvus#3910]
**Describe the bug**
In my test case, without normalizing the data, I choose one vector from the embedding file. We found two problems:
(1) the id is -1
(2)  the vector's id can't find.
I suspect that some boundary conditions are triggered by the distance's float value overflow problem

**Expected behavior**
(1) The returned result contains the vector's id, and the distance = 0;
(2) The returned result may contain some ids, and the id's value is not -1

- Milvus version (master or released version)
v0.10.1

**Screenshots**
result unexpected 

```javascript
{
    "num": 1,
    "result": [
        [
            {
                "distance": "340282346638528859811704183484516925440.000000",
                "id": "-1"
            },
            {
                "distance": "340282346638528859811704183484516925440.000000",
                "id": "-1"
            },
            {
                "distance": "340282346638528859811704183484516925440.000000",
                "id": "-1"
            },
            {
                "distance": "340282346638528859811704183484516925440.000000",
                "id": "-1"
            },
            {
                "distance": "340282346638528859811704183484516925440.000000",
                "id": "-1"
            },
            {
                "distance": "340282346638528859811704183484516925440.000000",
                "id": "-1"
            },
            {
                "distance": "340282346638528859811704183484516925440.000000",
                "id": "-1"
            },
            {
                "distance": "340282346638528859811704183484516925440.000000",
                "id": "-1"
            },
            {
                "distance": "340282346638528859811704183484516925440.000000",
                "id": "-1"
            },
            {
                "distance": "340282346638528859811704183484516925440.000000",
                "id": "-1"
            }
        ]
    ]
}
```

result expected 
```javascript
{
    "num": 1,
    "result": [
        [
            {
                "distance": "0.000000",
                "id": "1065007947"
            },
            {
                "distance": "3452360843306067369491670152375173120.000000",
                "id": "2253761204"
            },
            {
                "distance": "3732560747417264911111749558012477440.000000",
                "id": "2470228662"
            },
            {
                "distance": "3835426473761334985297652158843322368.000000",
                "id": "990681923"
            },
            {
                "distance": "3874313557399236264532665774723039232.000000",
                "id": "1065007889"
            },
            {
                "distance": "3920169550211892234902407516474310656.000000",
                "id": "1297763667"
            },
            {
                "distance": "3970206888529401019952986133748514816.000000",
                "id": "1033204473"
            },
            {
                "distance": "3989771807893323512535686251020288000.000000",
                "id": "1065007255"
            },
            {
                "distance": "4095462176687352138885473880768512000.000000",
                "id": "472839875"
            },
            {
                "distance": "4113341754578271200478884131128737792.000000",
                "id": "1397141124"
            }
        ]
    ]
}
```

**Comment by shengjun1985** [comment]
Can you tell us which index type did you used?
Can you provide some vector data for us to test?

**Comment by shengjun1985** [comment]
I tested and found that if the query value is strictly the same as the base data, it can be found, but others cannot be found.
This issue may be pretty hard to be solved.
It is suggested to solve it by reducing the data scale.

**Comment by dhg012** [comment]
> Can you tell us which index type did you used?
index type is l2
> Can you provide some vector data for us to test?
the embedding file:

[embeddings.txt](https://github.com/milvus-io/milvus/files/5321404/embeddings.txt)

base case vector:
[-1.25303176E18,7.0767757E18,-6.4320402E18,-3.0478596E19,-1.3952116E19,-1.5074635E19,-5.4352208E18,-1.2446101E19,4.2680187E19,-4.9224619E18,-2.2082084E19,3.3174438E19,3.0816388E19,3.34251178E18,-1.2335213E19,1.81963828E18,2.93704322E18,-2.8199612E19,-5.6411714E18,3.77738622E18,-7.4340516E18,-2.1313195E19,-5.6805713E18,-1.50150311E18,-9.0477362E17,1.7323995E19,-1.1599082E19,-8.1167257E18,-1.3909398E19,-3.59754185E18,-4.40903091E18,2.288941E19,-1.0757841E19,-1.8390751E19,1.3756478E19,2.74866939E18,-6.3324992E18,-7.5971179E18,2.4557506E19,-2.192864E19,-2.0719595E19,1.0585316E19,-1.771033E19,-1.3481278E19,4.5334456E18,-2.108631E19,-5.1780021E18,1.733292E19,9.917913E18,-2.54676803E17,1.3396423E19,-1.9317625E19,1.5510161E19,-2.5893607E19,1.9123474E19,1.372155E19,-1.31719E19,2.34371871E18,3.76030805E18,1.426689E19,2.6970539E19,9.653438E18,-1.4237894E19,1.069433E19,9.464966E18,6.0608319E18,1.3306717E19,9.991736E18,-1.1123423E19,-6.3743741E18,1.8310287E19,1.5927458E19,-1.9815935E19,-5.112668E18,4.42460796E18,7.0554837E17,1.2881989E19,-2.6173569E19,1.5598001E19,1.2209981E19,-2.25291E19,1.2173158E19,3.722592E19,-1.35437018E18,-1.62652803E18,-3.1710639E19,-7.0349761E18,-1.29332E19,1.7211412E19,-1.3943774E19,-1.938398E19,-2.67901E19,1.92742E19,-1.0254662E19,5.9899596E18,7.5066897E18,1.7333491E19,3.5530083E19,-2.62310132E18,-2.6385994E19,3.1017115E19,8.5284818E18,-1.019393E19,4.06058193E18,-2.0351578E19,6.2111351E18,4.25364105E18,2.424803E19,1.4429547E19,-5.967303E18,-3.42407197E17,-1.9966964E19,2.85304E19,9.766906E18,2.8052717E18,3.0928605E19,1.6532082E19,-1.6047084E19,4.32217224E18,1.472492E19,1.5191593E19,-6.011377E18,6.4706356E17,1.1832679E19,1.1154299E19,-1.0739464E19,-2.86756728E18,5.8102972E18]

**Comment by dhg012** [comment]
> I tested and found that if the query value is strictly the same as the base data, it can be found, but others cannot be found.
> This issue may be pretty hard to be solved.
> It is suggested to solve it by reducing the data scale.

Yes, normalization can solve this problem

**Comment by shengjun1985** [comment]
If we consider the float overflow, the performance will degrade a lot.
And we think it's rare. So it is not planed to solve.
