### ISSUE TITLE
Mention the "index_file_size" in the Benchmark 

### ISSUE THREAD

**Issue by AyushP123** [milvus-io/milvus#3918]
**Please state your issue using the following template and, most importantly, in English.**

**Location of incorrect documentation**
https://www.milvus.io/docs/benchmarks_azure

**Describe the problems or issues found in the documentation**
Since the algorithm's performance depends a lot on the "index_file_size" that is set while creating the collection, it will be useful to mention that for others to recreate the benchmark results.

**Comment by BossZou** [comment]
@AyushP123. You can refer [ann-benchmark/milvus_ivf_flat.py](https://github.com/milvus-io/ann-benchmarks/blob/0.10.0/ann_benchmarks/algorithms/milvus_ivf_flat.py) to find more details. The parameters "index_file_size" is set to 2048MiB when test.
