### ISSUE TITLE
Any random string can be passed as an index parameter and Milvus doesn't throw an error

### ISSUE THREAD

**Issue by manideep2510** [milvus-io/milvus#3919]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

`client.create_index()` function is accepting any random input parameter and does not raise any error, like below,

```python
index_param = {
        "m": 64,
        "nlist": 64,
        "nbits": 100,
        "randomthing": 10
        }

status = client.create_index(collection_name, IndexType.IVF_PQ, index_param)
```
```
Output: Status(code=0, message='Build index successfully!')
```
This will make it difficult to know whether we are passing the right parameters to the functions or not. It will get great if Milvus python API could throw an error message and let the user know that a wrong parameter has been passed.

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [x] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

    - 0.10.3

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by sahuang** [comment]
Currently irrelative parameters are ignored and only keywords are checked. Maybe later we can make the index parameter check more strict.

**Comment by manideep2510** [comment]
Thank you for the response. It will be awesome if you can make the index parameter check more strict and give an error when an unwanted parameter is passed. This will help in debugging if we pass a parameter which should not be passed.

**Comment by shengjun1985** [comment]
Not checking redundant keys allows multiple tests to use a same Json parameter.
Sometimes, it makes test programs much easier.
I am sorry that it brings some confusion to you. And we will consider your suggestions.
But in the current version, please fill in the parameters strictly according to our documentation.
Thank you very much.
