### ISSUE TITLE
How to pass "nbits" as an argument to IVFPQ?

### ISSUE THREAD

**Issue by manideep2510** [milvus-io/milvus#3920]
## Report needed documentation

**Report needed documentation**

By default, for IVFPQ, `nbits` is set to 8 in Milvus. And there is no information in the documentation on how I can change the parameter.

It is also difficult to know whether `client.create_index()` accepts (or does not accept) `nbits` as an index parameter as `client.create_index()` is accepting any random string as an index parameter as described in this issue #3919 

It will be great if you could give some information on whether I can give `nbits` as an index parameter during IVFPQ index creating and also add some information about `nbits` to the documentation.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken:

**Comment by sahuang** [comment]
nbits is set to 8 by default and currently you cannot change it during creating index.

**Comment by manideep2510** [comment]
Got it. Thanks. It will be great if you can make `nbits` parameter tunable.

**Comment by sahuang** [comment]
We plan to support it in 0.12.0

**Comment by shengjun1985** [comment]
We are going to put this function in v0.10.6.
"nbits" can be specified or not when building an IVF_PQ index.
cpu version: 1 <= nbits <=16
gpu version: nbits = 8
If an unsupported nbits is specified in the GPU version, the system will turn into CPU automatically.
