### ISSUE TITLE
Row count in a segment does not reflect the row count set with index_file_size

### ISSUE THREAD

**Issue by AyushP123** [milvus-io/milvus#3921]
**Describe the bug**
`index_file_size` does not translate to the expected row count in the segment.

**Steps/Code to reproduce behavior**
Create a collection with `index_file_size = 256`, `dims = 256`. Insert 5 million vectors into the DB. There are 19 segments as with the following row counts:
262144
262144
262144
**375712**
262144
262144
262144
262144
262144
262144
**167840**
262144
262144
262144
262144
262144
262144
262144
262144

**Expected behavior**
According to the documentation, Milvus creates a segment after `index_file_size` data has been inserted. So ideally the row counts should have been 256000 instead of 262144 ( in one case its 375k, which is not expected at all ).  

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [x] Build from source

**Environment details**
- AWS c5.4xlarge.

- Milvus version: v0.10.3 ( branch )

**Configuration file**
```
cache:
     cache_size: 20GB

storage:
     auto_flush_interval: 120
```
rest all config parameters are default.

**Comment by AyushP123** [comment]
@shengjun1985 I will also request an additional feature that might help a lot of users. Allow user to set `index_row_count` per segment instead `index_file_size`. This will bring in more certainty in terms of setting the algorithm hyperparameters. I will be more than happy to contribute to this.

**Comment by yhmo** [comment]
@AyushP123  
"index_file_size" is a threshold for segment merge, not a exact number of segment row count. Milvus merge small segments into large segment, until the segment size exceed "index_file_size". 
Sometimes a segment size could much bigger than "index_file_size", such as the "375k", it is merged from two segments which size close to 200k.
In 0.11.0, we use "segment_row_limit" to replace "index_file_size". "segment_row_limit" is also a threshold.
I agree with you that an accurate number of segment size(or row count) will bring in more certainty in terms of setting the algorithm hyperparameters. To achieve the goal, the code change may impact to whole insert/merge process. Do you have any proposal?

**Comment by yhmo** [comment]
The v1.1.1 is stable, we only fix critical bugs for v1.x.
Inactive and close this issue.
