### ISSUE TITLE
HEAD request results in 404 response

### ISSUE THREAD

**Issue by JeroenVanOort** [milvus-io/milvus#3922]
**Please state your issue using the following template and, most importantly, in English.**
When a HEAD request is made the result always seems to be a 404. 

**What would you like to be added ?**
I think the response code for GET and HEAD should be the same. If there is a good reason to not do so, I think a 405 code is appropriate.

**Why is this needed ?**
I'm working on a PHP client and wanted to implement a method for checking if a collection exists. I don't need the response body for that, so I wanted to make a HEAD request.

**Comment by BossZou** [comment]
@JeroenVanOort, currently we don't support HEAD request in restful APIs, so you are supposed to use GET request. And we consider your suggestion seriously。

**Comment by yhmo** [comment]
Inactive
