### ISSUE TITLE
Re-define the response returned by `list_collections/list_partitions`

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#3930]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
current **HTTP-API** response:
```
[
{"collection_name": "1"},
{"collection_name": "2"}
]
```
maybe the following structure in result is better:
```
["1", "2"]
``` 

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by shanghaikid** [comment]
No, I don't think so.
```
[
{"collection_name": "1"},
{"collection_name": "2"}
]
```

As an api user, array of [key:value] is better, we can easily add more information in the [key:value] object, avoid breaking the code structure.
