### ISSUE TITLE
Display of Milvus monitoring indicators using Grafana

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#3945]
In Pushgateway, the Memory Usage ratio was always 0%

![企业微信截图_16023159305255](https://user-images.githubusercontent.com/34296482/95650384-fc4c2700-0b15-11eb-84c8-a87f320d96de.png)
![企业微信截图_160231598267](https://user-images.githubusercontent.com/34296482/95650388-feae8100-0b15-11eb-867b-8c7fe76f7283.png)

**Comment by yhmo** [comment]
@jingkl 
Please provide your operation system information, CentOS or Ubuntu?

@del-zhenwu 
Please validate this issue.

**Comment by jingkl** [comment]
ubuntu,When configuring Prometheus for multiple Milvus services, could you determine which Milvus in Grafana

**Comment by jingkl** [comment]
@del-zhenwu

**Comment by jingkl** [comment]
![微信图片_20201014144955](https://user-images.githubusercontent.com/34296482/96074805-1dc55e00-0edc-11eb-81ab-dce04c0e1e03.png)Now the memory can change
@del-zhenwu

**Comment by fishpenguin** [comment]
There is no problem in my machine, please double check it.
