### ISSUE TITLE
Doc: FAQ error

### ISSUE THREAD

**Issue by Bennu-Li** [milvus-io/milvus#3947]
**Location of incorrect documentation**
https://milvus.io/docs/v0.10.3/performance_faq.md#Why-is-my-GPU-always-idle

**Describe the problems or issues found in the documentation**
 If you want to use GPU for query, you need to set the value of gpu_search_threshold in server_config.yaml to be less than nq

**Suggested fix for documentation**
![image](https://user-images.githubusercontent.com/53458891/95650874-10ddee80-0b19-11eb-9993-e64f7e1d0dd3.png)

Here should be `less than` 
Chinese documents have the same error

---

**Comment by shengjun1985** [comment]
Fixed.
