### ISSUE TITLE
The return of search is incorrect when use HTTP-API

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#3949]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
do search with the url: 
`http://192.168.1.6:19121/collections/test_9RlbRTdj/entities`

the body of GET request:
```
{'query': {'bool': {'must': [{'vector': {'float_vector': {'topk': 1, 'query': [[0.110734682846583,...,0.10075900588555384]], 'params': {'nprobe': 10}, 'metric_type': 'L2'}}}]}}, 'fields': None} 
```
the return no  "data":
```
{"code":0,"entities":[
{"entity":{"float":0.0,"float_vector":[0.12272283434867859,...,0.054779790341854095],"int64":0},"id":"1602467814997279000"},
{"entity":{"float":0.0,"float_vector":[0.12272283434867859,...,0.054779790341854095],"int64":0},"id":"1602467814997279000"},
{"entity":{"float":9.0,"float_vector":[0.013039511628448963,...,0.055422693490982056],"int64":9},"id":"1602467814997279009"}],"message":"OK","total":1200}
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [x] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
-0.11.0

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by ThreadDao** [comment]
the invalid format search query, such as `{'query': {'bool': {'must': [{'vector': {'float_vector': {'topk': 10, 'query': [[]], 'params': {'nprobe': 10}, 'metric_type': 'L2'}}}]}}, 'fields': None}` get an unexpected return
```
{"code":0,"entities":[
{"entity":{"float":0.0,"float_vector":[0.12272283434867859,...,0.054779790341854095],"int64":0},"id":"1602467814997279000"},
{"entity":{"float":0.0,"float_vector":[0.12272283434867859,...,0.054779790341854095],"int64":0},"id":"1602467814997279000"},
{"entity":{"float":9.0,"float_vector":[0.013039511628448963,...,0.055422693490982056],"int64":9},"id":"1602467814997279009"}],"message":"OK","total":1200}
```

**Comment by fishpenguin** [comment]
Already fixed
