### ISSUE TITLE
Performance slows down after cluster mode is turned on

### ISSUE THREAD

**Issue by fengdongdong00** [milvus-io/milvus#3955]
config：
version: 0.5
cluster:
  enable: true
  role: rw
general:
  timezone: UTC+8
  meta_uri: sqlite://:@:/
network:
  bind.address: 0.0.0.0
  bind.port: 19532
  http.enable: true
  http.port: 19123
storage:
  path: /var/lib/milvus
  auto_flush_interval: 1
wal:
  enable: true
  recovery_error_ignore: false
  buffer_size: 256MB
  path: /var/lib/milvus/wal
cache:
  cache_size: 4GB
  insert_buffer_size: 1GB
  preload_collection:
logs:
  level: debug
  trace.enable: true
  path: /var/lib/milvus/logs
  max_log_file_size: 1024MB
  log_rotate_num: 0
metric:
  enable: false
  address: 127.0.0.1
  port: 9098
Number of Vectors：270W
Dimensions：91

nq | IndexFileSize | topk | nlist | nprobe | avg_cost | concurrency | tps
-- | -- | -- | -- | -- | -- | -- | --
1 | 2408 | 100 | 16383 | 512 | 450 | 50 | 110
1 | 2408 | 100 | 16383 | 512 | 366 | 10 | 86

**Comment by fengdongdong00** [comment]
Under the same configuration and data, the cluster mode is not enabled

nq | IndexFileSize | topk | nlist | nprobe | avg_cost | concurrency | tps
-- | -- | -- | -- | -- | -- | -- | --
1 | 2408 | 100 | 16383 | 512 | 35 | 50 | 110
1 | 2408 | 100 | 16383 | 512 | 83 | 10 | 583

**Comment by yhmo** [comment]
The following script create a collection and insert 270w vectors(91 dimensional), then use multi-threads to perform 1000 queries:

```
import time
import threading
import numpy as np

from milvus import Milvus, IndexType, Status
from milvus.client.types import MetricType

SERVER_ADDR = "127.0.0.1"
SERVER_PORT = '19530'

TABLE_NAME = "TEST"
TABLE_DIMENSION = 91
TABLE_PARAM = {'collection_name': TABLE_NAME, 'dimension': TABLE_DIMENSION, 'index_file_size': 1000, 'metric_type':MetricType.L2}
INSERT_BATCH = 100000

INDEX_TYPE = IndexType.IVF_FLAT
INDEX_PARAM = {'nlist': 16383}

NQ = 1
TOPK = 100
SEARCH_PARAM = {'nprobe': 512}

print("connecting...")
MILVUS = Milvus(host=SERVER_ADDR, port=SERVER_PORT)
print("connected")


COLLECTION_NAME = 'test_collection'
DIMENSION = 91
param = {'collection_name': COLLECTION_NAME, 'dimension': DIMENSION, 'metric_type': MetricType.L2}

# drop old collection
if MILVUS.has_collection(COLLECTION_NAME):
    print("drop old collection...")
    MILVUS.drop_collection(COLLECTION_NAME)
    time.sleep(2)

# create new collection
print("create collection...")
MILVUS.create_collection(param)

def gen_vec_list(nb, seed=np.random.RandomState(1234)):
    xb = seed.rand(nb, DIMENSION).astype("float32")
    vec_list = xb.tolist()
    return vec_list

# insert 270w vectors
print("insert vectors...")
for k in range(270):
    vectors=gen_vec_list(nb=10000)
    status, ids = MILVUS.insert(collection_name=TABLE_NAME, records=vectors)

# create index
print("create index...")
MILVUS.create_index(collection_name=COLLECTION_NAME, index_type=INDEX_TYPE, params=INDEX_PARAM)

# search by multi-threads
def search():
    query_vectors = gen_vec_list(nb=NQ, seed=np.random.RandomState(13))
    status, results = MILVUS.search(collection_name=TABLE_NAME, query_records=query_vectors,
                                    top_k=TOPK, params=SEARCH_PARAM)

print("search...")
time_start = time.time()
threads = []
for i in range(1000):
    # search_binary_vec_list(query_vectors=query_vectors)
    x = threading.Thread(target=search, args=())
    threads.append(x)
    x.start()

for th in threads:
    th.join()

time_end = time.time()
print("search all done, time cost", time_end - time_start, 'sec')


```

**Comment by yhmo** [comment]
I did some test with this script:
1. start milvus with cluster.enable=false
2. run this script
3. restart milvus with cluster.enable=true
4. run this script again

I got same performance after run the script twice:
connecting...
connected
drop old collection...
create collection...
insert vectors...
create index...
search...
search all done, time cost 1.2783386707305908 sec

connecting...
connected
drop old collection...
create collection...
insert vectors...
create index...
search...
search all done, time cost 1.2986156940460205 sec

**Comment by yhmo** [comment]
@fengdongdong00 Could you show your script how you got different tps?

**Comment by fengdongdong00** [comment]
50 concurrent threads, continuous requests for one minute

> 
> 
> @fengdongdong00 Could you show your script how you got different tps?

50 concurrent threads, continuous requests for one minute

**Comment by yhmo** [comment]
@fengdongdong00 
I change my script, use 50 threads, each thread performs 1000 queries, 

```
def search():
    for i in range(1000):
        query_vectors = gen_vec_list(nb=NQ, seed=np.random.RandomState(13))
        status, results = MILVUS.search(collection_name=TABLE_NAME, query_records=query_vectors,
                                        top_k=TOPK, params=SEARCH_PARAM)

print("search...")
time_start = time.time()
threads = []
for i in range(50):
    # search_binary_vec_list(query_vectors=query_vectors)
    x = threading.Thread(target=search, args=())
    threads.append(x)
    x.start()

for th in threads:
    th.join()

time_end = time.time()
print("search all done, time cost", time_end - time_start, 'sec')
```
Run the script twice with cluster.enable=true/false, the time cost is almost same:

```
connecting...
connected
drop old collection...
create collection...
insert vectors...
create index...
load data...
search...
search all done, time cost 32.59415555000305 sec

connecting...
connected
drop old collection...
create collection...
insert vectors...
create index...
load data...
search...
search all done, time cost 32.851886510849 sec
```

**Comment by fengdongdong00** [comment]
Found the reason: the system is NUMA architecture, after specifying the CPU, it returns to normal

**Comment by yhmo** [comment]
Great.
