### ISSUE TITLE
Can we "Delete vectors by ID" from a specific partition?

### ISSUE THREAD

**Issue by dinuthomas** [milvus-io/milvus#3973]
Our application will have same items ( vectors and it's ids) in more than one partitions. While inserting a vector, we can specify the partition_tag. In the same way, while deleting an item, can the api allow us to specify the partition_tag? 

The entries from that specific partition ( passed in the request) shall be removed while the same vector could be available in another partitions untouched.

**Comment by yhmo** [comment]
Ideally, vector's id should be unique within a collection. But for performance concern, milvus doesn't check duplicate id when inserting vectors.
For your scenario, could you use multi-collections to store items?
