### ISSUE TITLE
Web_impl restful doc bugs

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#3976]
- [ ] `/collections(GET)`, Response , `"sigment_size"` may be wrong, should be `"segment_row_limit"`
- [ ] `/collections/{collection_name}/partitions(POST)`, Request, Body, `N/A` may be wrong, should be something like:

```json
{
    "partition_tag": "string"
}
```
- [ ] `/collections/{collection_name}/entities(GET)`
  - [ ] (1. Search entities in a collection): Request, Name, `/tables/{table_name}/entities` may be wrong
  - [ ] (1. Search entities in a collection): Body-Parameters, all parameters may be wrong
- [ ] `/collections/{collection_name}/entities(DELETE)`, Request-Body is incompatible with Example-Request
```json
# in Request-Body
{
    "ids": ["string"]
}

#in Example-Request
{"delete": {"ids": ["string"]}}
```
- [ ] `/collections/{collection_name}/entities(POST)`,
  - [ ] Request, Body, May be wrong, `"entities"` may be a list.
  - [ ] Body-Parameters, `ids` description maybe wrong, and `ids` should be `__id` according to the Request body.
  - [ ] Example-Request is incompatible with Request-Body
```json
#Example-Request
{"vectors":[[0.1],[0.2],[0.3],[0.4]]}
```

- [ ] `/collection/{collection_name}/fields/{field_name}/indexes (POST)`, Body Parameters, parameter `metric_type`'s description is copying from `index_type`, and is wrong.

- [ ] May need a summrization of all the `"type"` for a field

**Comment by fishpenguin** [comment]
already fixed.
