### ISSUE TITLE
Support logging to stdout

### ISSUE THREAD

**Issue by onmomo** [milvus-io/milvus#3977]
As we learned the log_config.conf is gone to configure easylogging++ log `FORMAT` and to log to stdout.
-> https://github.com/milvus-io/milvus/issues/2167

```
* GLOBAL:
        FORMAT                  =   {"timestamp\":\"%datetime{%Y-%M-%dT%H:%m:%s.%gZ}\",\"level\":\"%level\",\"logger\":\"%logger\",\"thread\":\"%thread\",\"message\":\"%msg\"}
        FILENAME                =   "/var/milvus/logs/milvus-%datetime{%H:%m}-global.log"
        ENABLED                 =   true
        TO_FILE                 =   false
        TO_STANDARD_OUTPUT      =   true
```

Could you provide us with instructions on how to do so with the new logging configuration?
As we understood, only these options are supported:

```
logs:
      level: info
      trace.enable: false
      path: /var/lib/milvus/logs
      max_log_file_size: 1024MB
      log_rotate_num: 1
```

**Comment by shengjun1985** [comment]
I am sorry that the feature is not supported in the current version.

**Comment by onmomo** [comment]
Ok, that's a pity. Is there a possibility to log everything to stdout / console? This would make our life much easier again to collect the Milvus container logs with our log aggregator system.

**Comment by scsven** [comment]
@onmomo Good idea. We will add a configuration to make it possible.

**Comment by scsven** [comment]
Done
