### ISSUE TITLE
Search response in http-api

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#3989]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
data in http-response
```
{"data":{"nq":1,"result":[[{"distance":"0.334419","id":"1602727509347967406"},{"distance":"0.334419","id":"1602727509677559406"},{"distance":"0.334419","id":"1602727509879554406"},{"distance":"0.334419","id":"1602727510082434406"},{"distance":"0.334419","id":"1602727510094428406"},{"distance":"0.334419","id":"1602727510561629406"},{"distance":"0.334419","id":"1602727510562302406"},{"distance":"0.334419","id":"1602727510562924406"},{"distance":"0.334419","id":"1602727511127466406"},{"distance":"0.334419","id":"1602727511128110406"}]]}}

```
why we need `nq` and `result` key-field, I think 
```
{"data": [[{"distance":"0.334419","id":"1602727509347967406"},{"distance":"0.334419","id":"1602727509677559406"},{"distance":"0.334419","id":"1602727509879554406"},{"distance":"0.334419","id":"1602727510082434406"},{"distance":"0.334419","id":"1602727510094428406"},{"distance":"0.334419","id":"1602727510561629406"},{"distance":"0.334419","id":"1602727510562302406"},{"distance":"0.334419","id":"1602727510562924406"},{"distance":"0.334419","id":"1602727511127466406"},{"distance":"0.334419","id":"1602727511128110406"}]]}
```
is more friendly to use

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by del-zhenwu** [comment]
@shanghaikid

**Comment by shanghaikid** [comment]
yes, we don't need it.  @fishpenguin
