### ISSUE TITLE
[BUG] Create partition should be failed if partition tag existed 

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#399]
**Describe the bug**
Partition A has been created, with tag "a", then create another partition with the same tag name "a", create still success

**Steps/Code to reproduce behavior**
```
        partition_name = gen_unique_str()
        status = connect.create_partition(table, partition_name, tag)
        assert status.OK()
        new_partition_name = gen_unique_str()
        status = connect.create_partition(table, new_partition_name, tag)
        assert not status.OK()
```

**Expected behavior**
create partition failed

**Environment details**
0.6.0

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
Fixed by PR426
