### ISSUE TITLE
An Exception should be thrown if the connection is closed repeatably when using java-sdk

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#3992]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
test case
```
    @Test(dataProvider = "DisConnectInstance", dataProviderClass = MainClass.class, expectedExceptions = ClientSideMilvusException.class)
    public void testDisconnectRepeatably(MilvusClient client, String collectionName){
        client.close();
    }
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [x] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
- 0.11.0

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by sahuang** [comment]
@thirstycrow any thoughts on this?

**Comment by sahuang** [comment]
We had a discussion and felt this is acceptable and there is no need to throw an exception when closing again
