### ISSUE TITLE
Horizontal scalability & high availability

### ISSUE THREAD

**Issue by WenqiJiang** [milvus-io/milvus#400]
https://www.bookstack.cn/read/Milvus/aboutmilvus-overview.md claims that Milvus is distributed and provides high availability. Are those features supported in the current release (0.5.3)? If so, is there a tutorial on setting up a cluster (the python example simply set up a single server)? What about the visualized system state supervisor by Prometheus？ 

Thanks.

**Comment by XuPeng-SH** [comment]
Hi, Milvus was designed to be deployed as distributed system from the beginning. We've released an experimental shards middleware called mishards in release 0.6.0 and prepared some demos how to use mishards to deploy with Milvus. 

Our kubernetes example is not a deployment for high availability, but it is very flexible for users to customize their own deployment policy for HA purpose.

Metrics supervisor Prometheus works fine in a single server and it is very convenient to be deployed in distributed system.

With mishards, we also integrated opentracing framework for better end-to-end tracing.

If you have any problem or new feature requirements during the use of Milvus, please let us know. Welcome to make your first contribution to Milvus.
