### ISSUE TITLE
Remove a warning message

### ISSUE THREAD

**Issue by PahudPlus** [milvus-io/milvus#4004]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Please remove the following warning from the milvus log file: 

WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 307200000 B, highwater 0 B)

**Steps/Code to reproduce behavior**

N/A

**Expected behavior**

Make sure this warning message does not occur. 

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**
I

**Comment by shengjun1985** [comment]
Fixed in 0.11.1
