### ISSUE TITLE
remove version from milvus.yaml

### ISSUE THREAD

**Issue by cydrain** [milvus-io/milvus#4007]
**Please state your issue using the following template and, most importantly, in English.**

**What would you like to be added ?**
remove version from milvus.yaml

if find unrecognized item when load milvus.yaml during Milvus boot up,
print out warning message:
"Ignore configuration xxx.xxx, possible incompatible configuration file."

**Why is this needed ?**
Simplify Milvus release process

**Comment by shengjun1985** [comment]
The version of the configuration file has not been updated for a long time.
This issue may be not needed.
Relate to PR #4951
