### ISSUE TITLE
[grpc_status:2]NotConnectError: Cannot check server version when using mishards on K8S

### ISSUE THREAD

**Issue by sinnergarden** [milvus-io/milvus#4009]
**Please state your issue using the following template and, most importantly, in English.**

When first time try to connect mishards (or after long time no connect), it may pop up error.

**Describe the bug**

When first time connect to mishards (or after long time no connect), it may pop up error like the following.
But when you try again, you can connect to the service.

Let's say you spin up 3 mishards instances, after the service set up, then you may have 3 chances to get the following error.

error log:
```
Addr [10.130.93.224:19530] _cmd
Rpc error: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception calling application: <StatusCode.UNAVAILABLE: (14, 'unavailable')> has type StatusCode, but expected one of: int, long"
        debug_error_string = "{"created":"@1602825329.668443586","description":"Error received from peer ipv4:10.130.93.224:19530","file":"src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"Exception calling application: <StatusCode.UNAVAILABLE: (14, 'unavailable')> has type StatusCode, but expected one of: int, long","grpc_status":2}"
>
        {'API start': '2020-10-16 13:15:29.663031', 'RPC start': '2020-10-16 13:15:29.663471', 'RPC error': '2020-10-16 13:15:29.668611'}
Traceback (most recent call last):
  File "main.py", line 55, in <module>
    tlk.list_collection()
  File "/ldap_home/xxx/milvus/toolkit.py", line 106, in list_collection
    milvus = Milvus(c._HOST, c._PORT)
  File "/ldap_home/xxx/miniconda3/envs/milvus/lib/python3.7/site-packages/milvus/client/stub.py", line 92, in __init__
    self._pool = SingletonThreadPool(pool_uri, **pool_kwargs)
  File "/ldap_home/xxx/miniconda3/envs/milvus/lib/python3.7/site-packages/milvus/client/pool.py", line 226, in __init__
    self._prepare()
  File "/ldap_home/xxx/miniconda3/envs/milvus/lib/python3.7/site-packages/milvus/client/pool.py", line 235, in _prepare
    raise NotConnectError("Cannot check server version: {}".format(status.message))
milvus.client.exceptions.NotConnectError: Cannot check server version: Error occurred. Exception calling application: <StatusCode.UNAVAILABLE: (14, 'unavailable')> has type StatusCode, but expected one of: int, long
```

**Steps/Code to reproduce behavior**

set up milvus service using helm install on K8S, with external mysql and nfs.

**Expected behavior**

It should not pop up any error.

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**

OS: Linux
CPU: 64 vcpu cores
Memory: 256G

- Milvus version (master or released version)

milvus: 0.10.3
helm: 3.x
pymilvus: 0.2.14

**Configuration file**

default in helm charts, just expand some memory / cpu resources, with external mysql and nfs.

**Comment by BossZou** [comment]
@sinnergarden , May you provide your mishrads docker version/tag here?

**Comment by shengjun1985** [comment]
If you still have questions, please continue to contact our community.

**Comment by wenwenxiong** [comment]
i meet the error too, how to fix this ?

**Comment by BossZou** [comment]
@wenwenxiong ,which version of Mishards and Milvus you used ? And is your milvus server running well?

**Comment by innerNULL** [comment]
> @wenwenxiong ,which version of Mishards and Milvus you used ? And is your milvus server running well?

We also has this issue, with pymilvus v0.4.0, milvus v0.10.6

**Comment by BossZou** [comment]
> > @wenwenxiong ,which version of Mishards and Milvus you used ? And is your milvus server running well?
> 
> We also has this issue, with pymilvus v0.4.0, milvus v0.10.6
> 
> ```
> milvus.client.exceptions.NotConnectError: Cannot check server version: Error occurred. Deadline Exceeded
> ```

@innerNULL , May you provide your mishards version ?  If your milvus server version is v0.10.6, you are recommended to use mishards image `milvusdb/mishards:0.10.6`.

**Comment by wenwenxiong** [comment]
https://github.com/milvus-io/pymilvus/issues/347

**Comment by wenwenxiong** [comment]
that say grpc lib error ,retry for fix it

**Comment by yhmo** [comment]
We recommend users use Milvus v2.0 to replace Mishards. Now the v2.0 rc4 has been released.
Inactive and close.
