### ISSUE TITLE
Range query support "EQ" and "NE" operators

### ISSUE THREAD

**Issue by sahuang** [milvus-io/milvus#4017]
**Please state your issue using the following template and, most importantly, in English.**

Currently Milvus v0.11.0 supports four operations: GT, GTE, LT, LTE. **EQ** (equals) and **NE** (not equals) are currently not supported. While "EQ" can be replaced by a term query, "NE" is not available.

Maybe range query should be able to support "EQ" and "NE" operators as well.

**Is your feature request related to a problem? Please describe.**

"NE" cannot be expressed by current DSL design.

**Describe the solution you'd like**

Add these operators to range query.

**Describe alternatives you've considered**

Not applicable.

**Comment by JinHai-CN** [comment]
I support this function can be implemented with MUST and MUST NOT operations.
