### ISSUE TITLE
Error with create index

### ISSUE THREAD

**Issue by shiyu22** [milvus-io/milvus#4022]
**Please state your issue using the following template and, most importantly, in English.**

**Location of incorrect documentation**
[create_index](https://milvus.io/cn/docs/v0.11.0/create_drop_index_python.md)

**Describe the problems or issues found in the documentation**
When I run create_index(), it shows the issue.
 `client.create_index('demo_films', IndexType.IVF_FLAT, ivf_param)`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'IndexType' is not defined

**Comment by shengjun1985** [comment]
fixed
