### ISSUE TITLE
Error with import pymilvus

### ISSUE THREAD

**Issue by shiyu22** [milvus-io/milvus#4023]
**Please state your issue using the following template and, most importantly, in English.**

**Location of incorrect documentation**
connect Milvus and [import pymilvus](https://milvus.io/cn/docs/v0.11.0/connect_milvus_python.md)

**Describe the problems or issues found in the documentation**
When I run `from milvus import Milvus, IndexType, MetricType, Status`, it shows the issue:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'IndexType' from 'milvus' (/data/workspace/conda/miniconda3/envs/video/lib/python3.7/site-packages/milvus/__init__.py)

**Comment by BossZou** [comment]
@shiyu22 , The latest pymilvus has changed much, The class `MetricType`, `IndexType` has been deleted. you may refer to [here](https://github.com/milvus-io/pymilvus/issues/258) to find more details.

**Comment by BossZou** [comment]
Fixed. Close it.
