### ISSUE TITLE
Error with insert and search data

### ISSUE THREAD

**Issue by shiyu22** [milvus-io/milvus#4024]
**Please state your issue using the following template and, most importantly, in English.**

**Location of incorrect documentation**
[insert data](https://milvus.io/cn/docs/v0.11.0/insert_delete_vector_python.md) and [search data](https://milvus.io/cn/docs/v0.11.0/search_vector_python.md)

**Describe the problems or issues found in the documentation**
when I run the command, it shows the issue. 
`milvus.insert(collection_name='test01', records=vectors, ids=vector_ids)`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/workspace/conda/miniconda3/envs/video/lib/python3.7/site-packages/milvus/client/stub.py", line 33, in inner
    return func(self, *args, **kwargs)
TypeError: insert() missing 1 required positional argument: 'entities'

Also, the search command has issue.

**Comment by shengjun1985** [comment]
[insert data](https://milvus.io/cn/docs/v0.11.0/insert_delete_entity_python.md) and [search data](https://milvus.io/cn/docs/v0.11.0/search_entity_python.md) are fixed.
