### ISSUE TITLE
Independent queues and lock for different collections is needed

### ISSUE THREAD

**Issue by godchen0212** [milvus-io/milvus#4027]
**Please state your issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**
Global lock and queue to all collections limit the throughout of milvus server.

For example, if we have three client to do operations in order as follows:
1.BuildIndex for collection_1
2.Compact for collection_2
3.CreateCollection for collection_3

Assume BuildIndex for collection_1 takes about 1minutes which is already a very short time for buildindex.
For Compact and BuildIndex share the same global lock instead of seperate lock for each collection, the compact operation for collection_2 is stucked. 
Moreover, compact operation is synchronous operation, compact request is stucked in request queue which makes CreateCollectionReq for collection_3 stucked in request queue.

This is very unreasonable, because the above three operations modify different collections, but they do not affect each other and cannot be executed in parallel. It even caused the client's timeout error for CreateCollection request.

At last, BuildIndex will take up all cpu resources. All operations effectiveness except search will decrease if a buildindex task is executed even if the collection affected by these operations and the buildindex operation is not the same.

**Describe the solution you'd like**
1.Create different request queue and lock for different collections, make operation for different, so that operations for different collections do not get stuck with each other.
2.Divide a buildindex operation into multiple small operations. When other tasks come in, pack the current state and perform other operations first. When other operations are completed, continue to build index.

**Comment by sworddish** [comment]
Agree, the current design of lock logic definitely need to be optimised. @shengjun1985 @yhmo

**Comment by yhmo** [comment]
> Agree, the current design of lock logic definitely need to be optimised. @shengjun1985 @yhmo

Yes, this is a limitation of current milvus. But it require large scale change in milvus source code, which will bring risk that we could not handle. So, we only focus on critical/crash issues. 
The milvus v2.0 will be open source. The v2.0 has no such problem.

**Comment by scsven** [comment]
refer: https://github.com/milvus-io/milvus/issues/2663

**Comment by yhmo** [comment]
The v1.1.1 is stable, we only fix critical bugs for v1.x, no more features/improvement.
Abandoned this feature.
