### ISSUE TITLE
Unable to connect Milvus EM according to the instructions on the official website

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#4032]
link:https://zilliz.com/products/em/

![image](https://user-images.githubusercontent.com/53512883/96532980-93a43d80-12bf-11eb-8b2f-8e573e31cbb7.png)

**Comment by Alanlxh** [comment]
I have the same problem. Could you tell me how to solve it?

**Comment by JackLCL** [comment]
@Alanlxh 
First, you need to check if the -e parameter is added to your startup command. 
Second, please make sure your ip is not using 127.0.0.1
