### ISSUE TITLE
an error in doc

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#4039]
link: https://milvus.io/cn/docs/v0.11.0/storage_operation.md

![image](https://user-images.githubusercontent.com/53512883/96665573-c580d700-1387-11eb-8db5-8482ad6ed5d9.png)

Maybe it should be "collection_2" and "collection_3".

**Comment by zyyerin** [comment]
![insert](https://user-images.githubusercontent.com/16808903/97251371-b3e57680-1842-11eb-85a1-8978d499e54b.png)

**Comment by shengjun1985** [comment]
@zyyerinThank you.

**Comment by PahudPlus** [comment]
Done. Will publish it shortly after.
