### ISSUE TITLE
Count not correct but status OK when META_FAILED

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#4042]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
-------------------------------- live log setup --------------------------------
[2020-10-20 16:16:45-ERROR-milvus.client.grpc_handler]: error_code: META_FAILED
reason: "Encounter exception when create collection:out of memory: out of memory"
 (grpc_handler.py:302)


=================================== FAILURES ===================================
____________ TestCreateBase.test_create_partition_insert_same_tags _____________

self = <test_partition.TestCreateBase object at 0x7f911eedd8d0>
connect = <milvus.client.stub.Milvus object at 0x7f911ef5b518>
collection = 'test_partition_2tbKwjYk'

    def test_create_partition_insert_same_tags(self, connect, collection):
        '''
        target: test create partition, and insert vectors, check status returned
        method: call function: create_partition
        expected: status ok
        '''
        status = connect.create_partition(collection, tag)
        assert status.OK()
        nq = 100
        vectors = gen_vectors(nq, dim)
        ids = [i for i in range(nq)]
        status, ids = connect.insert(collection, vectors, ids, partition_tag=tag)
        ids = [(i+100) for i in range(nq)]
        status, ids = connect.insert(collection, vectors, ids, partition_tag=tag)
        assert status.OK()
        status = connect.flush([collection])
        assert status.OK()
        status, res = connect.count_entities(collection)
>       assert res == nq * 2
E       assert 100 == 200
E         -100
E         +200

test_partition.py:165: AssertionError
____ TestCreateBase.test_create_partition_insert_same_tags_two_collections _____
```
**Steps/Code to reproduce behavior**
http://internal.zilliz.com:18080/jenkins/job/milvus-ci/job/0.10.4/27/artifact/_artifacts/0-10-4/centos7/cpu/milvus_cpu_sqlite_dev_test.log
**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
sqlite_orm throw exception, meta is no longer consist with collection data. count_entities() return incorrect value from cracked meta.

**Comment by yhmo** [comment]
link to #3998

**Comment by shengjun1985** [comment]
Please allow me to close the duplicate issues.
Let us trace the problem in the issue 3998.

**Comment by del-zhenwu** [comment]
it's an another issue, means that if the backend-store engine work unexpected, we need to make sure the response not OK

**Comment by yhmo** [comment]
The meta exception was thrown from create_partition(), not count_entities()
"Encounter exception when create collection......"

**Comment by del-zhenwu** [comment]
Need to add case with meta-failed. No reproduced after orm refactored.
