### ISSUE TITLE
The content of the introduction configuration file on the official website is incorrect

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#4046]
link: https://milvus.io/cn/docs/v0.11.0/milvus_config.md

![image](https://user-images.githubusercontent.com/53512883/96682126-f9212880-13aa-11eb-9fb6-63ffb5f68493.png)

The configuration file downloaded through the link " https://raw.githubusercontent.com/milvus-io/milvus/0.11.0/core/conf/demo/milvus.yaml " does not contain the two parameters "recovery_error_ignore" and "buffer_size".

**Comment by yhmo** [comment]
In 0.11.0, wal only has two items in config: 'enable' and 'path'.
'recovery_error_ignore' and 'buffer_size' has been removed.

**Comment by PahudPlus** [comment]
Fixed.
