### ISSUE TITLE
Need update page "Hello Milvus"

### ISSUE THREAD

**Issue by FangliangBai** [milvus-io/milvus#4050]
**Please state your issue using the following template and, most importantly, in English.**

**Location of incorrect documentation**
https://milvus.io/cn/docs/example_code.md

**Describe the problems or issues found in the documentation**

> 确认程序正确运行。

```
Query result is correct.
```
This is the old script output. The output of the new `example.py` for 0.11.0 is different.

**Steps taken to verify documentation is incorrect**
List any steps you have taken:
```py
python3 example.py
```

**Suggested fix for documentation**
Just update the example script or the document.

**Comment by PahudPlus** [comment]
fixed. Thanks.
