### ISSUE TITLE
我隔一段时间再次访问milvus时候出现错误

### ISSUE THREAD

**Issue by 785321021** [milvus-io/milvus#4052]
ERROR:    insert
<_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Connection timed out"
        debug_error_string = "{"created":"@1603329566.725876522","description":"Error received from peer ipv4:10.130.108.38:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Connection timed out","grpc_status":14}"

**Comment by shengjun1985** [comment]
Could you please provide more information?
Milvus version and SDK version?
Run in docker or not ?
What was your operations (create collection, inset ...)?
How long did Milvus run before the error happened?

**Comment by yhmo** [comment]
Somehow similar to #4079

**Comment by shengjun1985** [comment]
Let's trace the issue in 4079.
Please allow me to close this one.
If you have more questions, please continue to contact our community.
Thank you.
