### ISSUE TITLE
Server version need to update to 0.11.1

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#4055]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
self = <test_ping.TestPing object at 0x7f05690f52e8>
connect = <milvus.client.stub.Milvus object at 0x7f0569136dd8>

    def test_server_version(self, connect):
        '''
        target: test get the server version
        method: call the server_version method after connected
        expected: version should be the milvus version
        '''
        res = connect.server_version()
>       assert res == __version__
E       AssertionError: assert '0.11.0' == '0.11.1'
E         - 0.11.0
E         ?      ^
E         + 0.11.1
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [x] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 - 0.11.1

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by shengjun1985** [comment]
@ThreadDao
