### ISSUE TITLE
milvus raise exception when passing a complex dsl during searching

### ISSUE THREAD

**Issue by BossZou** [milvus-io/milvus#4059]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
I passed a complex dsl to server like this:
```json
dsl2 = {
    "bool": {
        "must": [
            {
                "must": [
                    {
                        "should": [
                            {
                                "term": {"release_year": [2003, 2005]}
                            },
                            {
                                "range": {"duration": {"GT": 100}}
                            }
                        ]
                    }
                ]
            },
            {
                "must": [
                    {
                        "vector": {
                            "embedding": {"topk": 1, "query": [query_embedding2], "metric_type": "L2"}
                        }
                    }
                ]
            }
        ]
    }
}
```

The dsl well-formed but client still receive a incorrect status, result in user encounter an exception:
```
    raise BaseException(status.error_code, status.reason)
milvus.client.exceptions.BaseException: <BaseException: (code=1, message=The child node of 'should' and 'must_not' can only be 'term query' and 'range query'.)>

```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [x] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
  v0.11.1

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by fishpenguin** [comment]
Fixed in pr4063
