### ISSUE TITLE
Change query result structure

### ISSUE THREAD

**Issue by fishpenguin** [milvus-io/milvus#4062]
**Please state your issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**
Currently server will pass 1 dimensional ids and distances to client, and sdk needs to filter -1 ids. The filter process can be put into server.
So there will be an offset array added to 'QueryResult' proto message, and sdk can use the offset to judge how many results returned in each nq.

**Comment by scsven** [comment]
Not activity.
