### ISSUE TITLE
There is a bug in doc CONTRIBUTING.md

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#4068]
**Where is the bug:**
[CONTRIBUTING.md](https://github.com/milvus-io/milvus/blob/0.11.0/CONTRIBUTING.md)

**The bug is:**
in Github workflow, 

2.Clone your fork to your local machine with `git clone git@github.com:<yourname>/milvus-io/milvus.git`.

**Correct description:**

`git clone git@github.com:<yourname>/milvus.git`

**Comment by shengjun1985** [comment]
Fixed in master.
