### ISSUE TITLE
Cmake version requirements in build from source is wrong

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#4073]
**Please state your issue using the following template and, most importantly, in English.**
[Requirements](https://github.com/milvus-io/milvus/blob/master/INSTALL.md#requirements)
Cmake version should be 3.14 or higher
https://github.com/milvus-io/milvus/blob/a009a19403a75c7153978ced73aa3b4caa0c181a/core/CMakeLists.txt#L14

**Comment by XuanYang-cn** [comment]
Also wrong in Tutorial from Milvus-io [link](https://tutorials.milvus.io/install-milvus-from-source-code/index.html?index=..%2F..index#0)

**Comment by shengjun1985** [comment]
@PahudPlus 
https://tutorials.milvus.io/

**Comment by shengjun1985** [comment]
Tutorial from Milvus-io is fixed in the following PR.
https://github.com/zilliztech/milvus-tutorials/pull/9
