### ISSUE TITLE
milvus search service  is always not connected  after serveral  days

### ISSUE THREAD

**Issue by leidaxia** [milvus-io/milvus#4079]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
I have create a milvus service in a single server maching,  and I create a collection and search it normally,    see
![image](https://user-images.githubusercontent.com/20982126/96966263-12a7a900-1540-11eb-9a22-59bd90067418.png)

But after serveral days, my search request is time out,   but when I restart the CONTAINER ID,  it is back to normal,  and  after serveral days, my search request is  time out,  it is a bad circle

when I curl -X GET "http://172.25.161.92:19121/state" -H "accept: application/json"
it returns ok and 200, ### **_it means milvus web service is ok_**

when I curl -X GET "http://172.25.161.92:19121/status" -H "accept: application/json"
it returns
server=oatpp/1.0.1
code=404
description=Not Found
message=Current url has no mapping ,  **_### it means now milvus server cannot use_**  , **### _but I have no any error log_**

When I  curl -X GET "http://xxx.xx.xxx.xx:19121/collections/dssm_easy_10014_channel_vec?info=stat" -H "accept: application/json"

it returns
{"partitions":[{"row_count":93984,"segments":[{"data_size":25218234,"index_name":"IVFFLAT","name":"1600756061967727000","row_count":93984}],
"tag":"_default"}],"row_count":93984}

curl -X GET "http://xxx.xx.xxx.xx:19121/collections/dssm_easy_10014_channel_vec/partitions?offset=0&page_size=3" -H "accept: application/json"

it returns
{"partitions":[{"partition_tag":"_default"}],"count":1}

**Comment by yhmo** [comment]
Similar to https://github.com/milvus-io/pymilvus/issues/256
@leidaxia How many search requests were done in the several days?

**Comment by leidaxia** [comment]
> Similar to [milvus-io/pymilvus#256](https://github.com/milvus-io/pymilvus/issues/256)
> @leidaxia How many search requests were done in the several days?

About hundreds of thousands search requests, but when I restart the CONTAINER , the search service is normally , but get /status , it always returns the 404

**Comment by yhmo** [comment]
Which meta backend, MySQL or SQLite?

Link to issue: #4031
So far, the issue is still in investigation.

**Comment by leidaxia** [comment]
> Which meta backend, MySQL or SQLite?
> 
> Link to issue: #4031
> So far, the issue is still in investigation.

SQLite ！

**Comment by yhmo** [comment]
Milvus use sqlite_orm library as a third-party to connect to SQLite, sometime we notice the sqlite_orm throw unexpected exception after long term(or intensive) work. We are plan to remove sqlite_orm from milvus, not sure this work could be done in next release. So could you try MySQL? Officially MySQL is strongly recommended for production usage.

**Comment by yhmo** [comment]
Milvus use sqlite_orm library as a third-party to connect to SQLite, sometime we notice the sqlite_orm throw unexpected exception after long term(or intensive) work. We are plan to remove sqlite_orm from milvus, not sure this work could be done in next release. So could you try MySQL? Officially MySQL is strongly recommended for production usage.

**Comment by leidaxia** [comment]
> Milvus use sqlite_orm library as a third-party to connect to SQLite, sometime we notice the sqlite_orm throw unexpected exception after long term(or intensive) work. We are plan to remove sqlite_orm from milvus, not sure this work could be done in next release. So could you try MySQL? Officially MySQL is strongly recommended for production usage.

Is it sure that if I change the sqlite to Mysql, this bug will be solved?

**Comment by yhmo** [comment]
So far, we notice some unstable bugs are using SQLite as meta backend, similar to this issue. Milvus use sqlite_orm as a third-party to interact with SQLite, but for unknown reason, the sqlite_orm occasionally throw exceptions and Milvus hangs in some background thread. We are now plan to remove sqlite_orm in 0.10.4.
For mysql, milvus directly connect to mysql server and mysql is more stable than sqlite, so I think change sqlite to mysql can solve your problem.

**Comment by leidaxia** [comment]
> So far, we notice some unstable bugs are using SQLite as meta backend, similar to this issue. Milvus use sqlite_orm as a third-party to interact with SQLite, but for unknown reason, the sqlite_orm occasionally throw exceptions and Milvus hangs in some background thread. We are now plan to remove sqlite_orm in 0.10.4.
> For mysql, milvus directly connect to mysql server and mysql is more stable than sqlite, so I think change sqlite to mysql can solve your problem.

OK,  when the version 0.10.4 will be released?

**Comment by yhmo** [comment]
0.10.4 is still in planning. Generally, the interval between two release versions is about one month, but since now we have 0.10.x and 0.11.x two lines, the 0.10.4 will be delay at lease half month.

**Comment by leidaxia** [comment]
> 0.10.4 is still in planning. Generally, the interval between two release versions is about one month, but since now we have 0.10.x and 0.11.x two lines, the 0.10.4 will be delay at lease half month.

ok, when I   curl -X GET "http://x.x.x.x:19121/status" -H "accept: application/json" , it returns that
server=oatpp/1.0.1
code=404
description=Not Found
message=Current url has no mapping

but the search api  is OK,  is it normal?

**Comment by fishpenguin** [comment]
Server status should be get by: curl -X GET "http://x.x.x.x:19121/system/status" -H "accept: application/json".

**Comment by leidaxia** [comment]
> Server status should be get by: curl -X GET "http://x.x.x.x:19121/system/status" -H "accept: application/json".
ok , I have got returned the status ok

**Comment by JamesIsHuang** [comment]
> > Server status should be get by: curl -X GET "http://x.x.x.x:19121/system/status" -H "accept: application/json".
> > ok , I have got returned the status ok

After changing to mysql, did the problem occur again?

**Comment by shengjun1985** [comment]
Inactive, close.
