### ISSUE TITLE
Expose MAX_PARTITION_LIMIT to config, as a hide item

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#4082]
**Please state your issue using the following template and, most importantly, in English.**
Current the max partition count for each collection is 4096, which is hardcode.
Sometimes user may want to create more partitions. Expose this value to server_config.yaml as a hide item.

**What would you like to be added ?**

**Why is this needed ?**

**Comment by yhmo** [comment]
Link to #4075

**Comment by scsven** [comment]
Existed. Named "engine.max_partition_num".

**Comment by yhmo** [comment]
0.10.4 need this.

**Comment by yhmo** [comment]
fixed by pr4138.
To define max partition limit, add this item in the server_config.yaml:
```
engine_config:
  max_partition_num: 10000
```

**Comment by yhmo** [comment]
pr4138 has been merged. Now partition number can exceed 4096, but set `engine_config.max_partition_num` in server_config.yaml.

**Comment by del-zhenwu** [comment]
close, has been updated in CI stages
