### ISSUE TITLE
参照官网安装的文档，安装成功之后 执行启动服务是失败 没有任何日志返回打印出来

### ISSUE THREAD

**Issue by at87958208** [milvus-io/milvus#4095]
安装参考教程：https://www.milvus.io/cn/docs/v0.11.0/milvus_docker-cpu.md
docker ps -a 有提示：
服务器CPU 型号：  Intel(R) Xeon(R) CPU           X5675  @ 3.07GHz
服务器CPU：
  Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt spec_ctrl intel_stibp

安装在虚拟机上跑，四核 16G内存 硬盘100G

如下：
[root@localhost ~]# docker ps -a
CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS                        PORTS                  NAMES
1eadf2636dc1        nginx                                       "/docker-entrypoint.…"   45 minutes ago      Up 31 minutes                 0.0.0.0:8080->80/tcp   nginx-test
a0bfaea01d3d        milvusdb/milvus:0.11.0-cpu-d101620-4c44c0   "/var/lib/milvus/bin…"   54 minutes ago      Exited (132) 30 minutes ago                          milvus_cpu_0.11.0
c509209a744a        hello-world                                 "/hello"                 2 hours ago         Exited (0) 2 hours ago                               clever_saha
[root@localhost ~]# docker logs a0bfaea01d3d
[root@localhost ~]#

服务没有起来

**Comment by yhmo** [comment]
CPI instruction contains "SSE4_2", but encounter "illegal instruction" error.

**Comment by cydrain** [comment]
@at87958208 this issue is similar with #2532
Can you download avx_test2.tar.gz and try if you can run this code in your machine ?

**Comment by at87958208** [comment]
> @at87958208 this issue is similar with #2532
> Can you download avx_test2.tar.gz and try if you can run this code in your machine ?

感谢 通过程序检测是可以安装的 返回sse42  16 pass   但是启动程序依然报错。。。。。。。 问题依然无法解决

**Comment by cydrain** [comment]
The only way left to debug this issue is:
1. Build Milvus debug (CPU version)
2. run this debug binary in your machine
3. check if you can get the backtrace info when "Illegal Instruction" error happens again

We can do nothing without more information

**Comment by shengjun1985** [comment]
It looks like #4246.
But we have not found the reason yet.

**Comment by shengjun1985** [comment]
Inactive. Close.
