### ISSUE TITLE
When execute a multiple vectors request, if the result of somerow is not enough, the query data field will be disorder.

### ISSUE THREAD

**Issue by keerbin** [milvus-io/milvus#4099]
**Describe the bug**
Use C++ SDK, execute a multiple verctors query, if some vertor has not enough data(the result row is less than topk), the fields of results will be disorder. 

**How to fix**
In ClientProxy.cpp ConstructTopkQueryResult function, the one_result.distances is ok. 
1. Add some logic for one_result.ids being -1.
2. The lenght of copy field should be real count(ids is not -1) not topk, user a cursor local variable and realcount.

**Steps/Code to reproduce behavior**

**Expected behavior**

**Method of installation**

**Environment details**

- Milvus version (master or released version)

**Configuration file**

```yaml
```

**Screenshots**

**Additional context**

**Comment by fishpenguin** [comment]
It's a C++ sdk bug, we will fix it soon in branch 0.11.1.
And python sdk is OK in this case. So you can try python sdk.

**Comment by fishpenguin** [comment]
Fixed
