### ISSUE TITLE
Trim blank space for collection name, partition name and field name

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#4101]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
=================================== FAILURES ===================================
_ TestCreateCollectionInvalid.test_create_collection_with_invalid_collectionname[ siede ] _

self = <test_create_collection.TestCreateCollectionInvalid object at 0x7f8fda4e3fd0>
connect = <milvus.client.stub.Milvus object at 0x7f8fd84fcba8>
get_invalid_string = ' siede '

    @pytest.mark.level(2)
    def test_create_collection_with_invalid_collectionname(self, connect, get_invalid_string):
        collection_name = get_invalid_string
        with pytest.raises(Exception) as e:
>           connect.create_collection(collection_name, default_fields)
E           Failed: DID NOT RAISE <class 'Exception'>

collection/test_create_collection.py:247: Failed
_ TestDropCollectionInvalid.test_drop_collection_with_invalid_collectionname[ siede ] _
```
**Steps/Code to reproduce behavior**
http://internal.zilliz.com:18080/jenkins/blue/organizations/jenkins/milvus-ci/detail/0.11.1/15/artifacts

**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [x] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by fishpenguin** [comment]
When collection is created, server will trim side_blank. So this is not a bug but is designed like this.

**Comment by shengjun1985** [comment]
@yhmo 
It is add in PR4061 (for master) and PR4071 (for 0.11.1).
Please help to explain the issue.

**Comment by shanghaikid** [comment]
@del-zhenwu trimming whitespace I think is good,  it somehow enhances our system's security.

**Comment by yhmo** [comment]
Related APIs:
CreateCollection
CreatePartition

Expected behavior:
Ignore outer whitespace for collection name, partition name, field name.
Assume user input " abc  ", it will be treated as "abc" by milvus, API return OK.
