### ISSUE TITLE
Is Milvus not support MySQL<5.7?

### ISSUE THREAD

**Issue by shiyu22** [milvus-io/milvus#4102]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
When upgrading to 0.11.0 and now getting this error for MySQL5.6.10:
`
Milvus server encounter exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'JSON NOT NULL,state TINYINT NOT NULL,created_on BIGINT NOT NULL,updated_on BIGIN' at line 1
`

But it with MySQL 5.7 and it works fine. Is Milvus no longer providing support for < 5.7?

**Expected behavior**
If it is, please note [the web](https://milvus.io/docs/v0.11.0/data_manage.md).

**Comment by yhmo** [comment]
#3792 recommend 5.7

**Comment by yhmo** [comment]
0.11.0 uses a JSON column type for meta system. Only MySQL 5.7 support for this column type, refer this link: https://dev.mysql.com/doc/refman/5.7/en/json.html. so 0.11.x requires mysql > 0.5.7
