### ISSUE TITLE
Hamming distance calculation is not accurate

### ISSUE THREAD

**Issue by JamesIsHuang** [milvus-io/milvus#4105]
Version: milvusdb/milvus:0.10.3-cpu-d091720-f962e8
description: I only inserted a vector and found that the searched distance is 82, which should be 0
collections info: {"collections":[{"collection_name":"thash_collection_test","count":1,"dimension":192,"index":"IVFFLAT","index_file_size":1024,"index_params":"{\"nlist\":2048}","metric_type":"HAMMING"}],"count":1}
vector string（Hexadecimal）: 2208024216270485dc7e40e3274599a922a2e9baab1478f7
When actually inserted, I converted it into a binary type

**Comment by JamesIsHuang** [comment]
should be Capitalization issues

**Comment by codepujan** [comment]
Any updates on the issue? I've been running into inaccurate Hamming distance problems as well.

**Comment by xiaofan-luan** [comment]
i

> Any updates on the issue? I've been running into inaccurate Hamming distance problems as well.

is this for 1.x or 2.x?
