### ISSUE TITLE
Update oatpp. New version 1.2.0

### ISSUE THREAD

**Issue by lganzzzo** [milvus-io/milvus#4112]
Hello guys,

The new Oat++ `1.2.0` has been released - please find the [changelog](https://github.com/oatpp/oatpp/blob/master/changelog/1.2.0.md).

#### List of new features that you may find interesting:

- [Oat++ ORM](https://oatpp.io/docs/components/orm/) with [SQLite adaptor](https://github.com/oatpp/oatpp-sqlite) - The new oatpp ORM is based on oatpp object-mapping which ensures code consistency and reduces the amount of code needed.  It also has a schema migration engine.
- Experimental [protobuf integration module](https://github.com/oatpp/oatpp-protobuf) - Makes it possible to use protobuf objects as regular oatpp DTOs. Automatic serialization/deserialization of proto objects to/from JSON may come in handy to reduce DTOs to protobuf objects conversions. Protobuf objects can also work with oatpp ORM.

#### Future improvements that you may find interesting:

- Automatic generation of REST API from GRPC 

---

Please let me know if you have any comments or questions.

Best Regards,
Leonid

**Comment by yhmo** [comment]
The v1.1.1 is stable, we only fix critical bugs for v1.x, no more features/improvement.
Abandoned this feature.
