### ISSUE TITLE
milvus 0.10.4  open FPGA fail in FPGA version

### ISSUE THREAD

**Issue by jackhouchina** [milvus-io/milvus#4122]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
milvus 0.10.4  open FPGA fail when search on FPGA 

**Steps/Code to reproduce behavior**
i get a open fpga fail  from the following code:
 /core/src/index/knowhere/knowhere/index/vector_index/fpga/xilinx_c.cpp:208: int TransBuffer2FPGA(char*, size_t, char*, loff_t, int): Assertion `fpga_fd >= 0' failed
Code:
###
   int fpga_fd = open(devicename, O_RDWR);
    assert(fpga_fd >= 0);
###
**Expected behavior**
 fpga_fd >= 0

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [* ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)
OS:ubuntu 18.04 
CPU: intel Skylake-16 cores 3GHz
Memory: 385G
- Milvus version (master or released version)
0.10.4

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
fpga:
   enable: true
   search_devices:
     - fpga0
```

**Screenshots**

**Additional context**
/core/src/index/knowhere/knowhere/index/vector_index/fpga/xilinx_c.cpp:208: int TransBuffer2FPGA(char*, size_t, char*, loff_t, int): Assertion `fpga_fd >= 0' failed

**Comment by shengjun1985** [comment]
Done
