### ISSUE TITLE
support Builder mode in go-sdk

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#4124]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
current expr in params:

search:
```
	dsl := map[string]interface{}{
		"bool": map[string]interface{}{
			"must": []map[string]interface{}{
				{
					"vector": map[string]interface{}{
						"float_vector": map[string]interface{}{
							"topk":        topk,
							"metric_type": "L2",
							"query":       vectorData[0:5],
							"params": map[string]interface{}{
								"nprobe": 10,
							},
						},
					},
				},
			},
		},
	}
	searchParam := milvus.SearchParam{collectionName, dsl, nil}
```

wanted expr:
```
	res, err := s.es.Search(
		s.es.Search.WithIndex(s.indexName),
		s.es.Search.WithBody(s.buildQuery(query, after...)),
	)
```
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by fishpenguin** [comment]
There is no need to add builder mode for go sdk

**Comment by fishpenguin** [comment]
Close this issue, we reach a consensus that it'not to be done,
