### ISSUE TITLE
按照https://milvus.io/cn/docs/v0.10.2/mishards.md 在K8S上搭建MIshard.执行helm dep update，报错：Error: chart metadata (Chart.yaml) missing

### ISSUE THREAD

**Issue by JamesIsHuang** [milvus-io/milvus#4125]
按照https://milvus.io/cn/docs/v0.10.2/mishards.md 在K8S上搭建MIshard.执行helm dep update，报错：Error: chart metadata (Chart.yaml) missing
![image](https://user-images.githubusercontent.com/12915720/97530806-dcf63a80-19ed-11eb-8629-7707d3550e9d.png)

**Comment by jeffoverflow** [comment]
To install Milvus Helm Chart , refer to [Milvus Helm Chart Installation](https://github.com/milvus-io/milvus-helm/tree/master/charts/milvus#installing-the-chart)

**Comment by shengjun1985** [comment]
If you have more questions, please continue to contact our community.
