### ISSUE TITLE
The error is Nil when DropCollection or GetCollectionInfo with nonexistent collection name in go-sdk

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#4131]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
func TestDropCollectionNotExisted(t *testing.T)  {
	client := GetClient()
	name := utils.RandString(8)
	status, error := client.DropCollection( name)
	assert.False(t, status.Ok())
	fmt.Println(error)
	t.Log(error)
}
```
output
```
<nil>
    collection_test.go:114: <nil>
--- PASS: TestDropCollectionNotExisted (0.00s)
PASS
0
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 -0.11.1

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by fishpenguin** [comment]
When DropCollection or GetCollectionInfo with nonexistent collection name in go-sdk, error should be nil, and status is not OK.
You should only check status.OK() in such case.
error is used to check if rpc transport is OK.
