### ISSUE TITLE
0.11.x support read-write separation

### ISSUE THREAD

**Issue by Bennu-Li** [milvus-io/milvus#4133]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
I started two milvus nodes， one writable node, one read-only node.  Metadata uses the same mysql, and map the same db directory.  the writable nodes can be used normally.  You can successfully connect to the read-only node, but when sending a request to the read-only node, such an error will occur:
![image](https://user-images.githubusercontent.com/53458891/97558435-142d1180-1a17-11eb-8203-7dc258d03897.png)

![image](https://user-images.githubusercontent.com/53458891/97558488-26a74b00-1a17-11eb-8da7-794e47d89169.png)

**Comment by Bennu-Li** [comment]
I found that after sending a request to a read-only node, the same error occurs when sending a request to a writable node.

**Comment by shengjun1985** [comment]
Readonly has not been implemented in 0.11.0.

**Comment by XuPeng-SH** [comment]
Hi @Bennu-Li,
Unfortunately to tell you, currently, 0.11.0 does not support read-write separation. You can open a new feature request for this.

**Comment by yhmo** [comment]
This feature is still in developing.
