### ISSUE TITLE
Error should be raised if field not exised in collection during `drop_index`

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#4135]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
func TestIndexDropFieldNameNotExisted(t *testing.T) {
	client, name := Collection(true, milvus.VECTORFLOAT)
	_name := utils.RandString(8)
	status, _ := client.DropIndex(name, _name)
	assert.Equal(t, status.Ok(), false)
}
```
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
fixed by pr4142

**Comment by del-zhenwu** [comment]
close
