### ISSUE TITLE
Does function GetCollectionStats have a better return type than a long and complex string

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#4136]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
because `stats` is inherently complicated, and `go` is a strongly typed language, so it is difficult to get the return value 
```
{"data_size":3211192,"partition_count":1,"partitions":[{"data_size":3211192,"id":88,"row_count":3000,"segment_count":1,"segments":[{"data_size":3211192,"files":[{"data_size":52100,"field":"_id","name":"_raw","path":"/C_88/P_88/S_33/F_178"},{"data_size":38792,"field":"_id","name":"_blf","path":"/C_88/P_88/S_33/F_184"},{"data_size":16100,"field":"_id","name":"_del","path":"/C_88/P_88/S_33/F_183"},{"data_size":28100,"field":"float","name":"_raw","path":"/C_88/P_88/S_33/F_179"},{"data_size":3076100,"field":"float_vector","name":"_raw","path":"/C_88/P_88/S_33/F_180"}],"id":33,"row_count":3000}],"tag":"_default"}],"row_count":3000}
```
for example, I get the `segments`
```
var statsMap map[string]interface{}
json.Unmarshal([]byte(stats), &statsMap)
assert.Equal(t, 0, int(statsMap["data_size"].(float64)))
assert.Nil(t, statsMap["partitions"].([]interface{})[0].(map[string]interface{})["segments"])
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 -0.11.1

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by fishpenguin** [comment]
You can use github.com/tidwall/gjson to parse the json string
