### ISSUE TITLE
Function HasPartition is not found in go-sdk

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#4137]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
	CreatePartition(partitionParam PartitionParam) (Status, error)

	// ListPartitions method
	// This method is used to create collection
	// return indicate if this operation is successful
	ListPartitions(collectionName string) ([]PartitionParam, Status, error)

	// DropPartition method
	// This method is used to delete collection partition.
	// return indicate if partition is delete successfully.
	DropPartition(partitionParam PartitionParam) (Status, error)
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [X] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 -0.11.1

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by fishpenguin** [comment]
Already fixed.
