### ISSUE TITLE
How to set the optimal segment_row_limit

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#4149]
Please provide additional documentation on how to set the optimal segment_row_limit for data volumes such as millions, tens of millions, or billions

**Comment by sahuang** [comment]
Should be added in the documentation.

**Comment by shengjun1985** [comment]
Is this enough?
https://milvus.io/cn/docs/v0.11.0/tuning.md

**Comment by jingkl** [comment]
> Is this enough?
> https://milvus.io/cn/docs/v0.11.0/tuning.md

The official website does not tell you how to set this value to be the optimal value. It only says the default value and the upper limit. It does not tell me, for example, how to set the vector of 100 million.

**Comment by shengjun1985** [comment]
If the data is static, please set ‘segment_row_limit’ as large as possible.
If the data is streaming, it depends on the frequency and the batch size of inserting. Sometimes 1,000,000 or 2,000,000 is chosen.
