### ISSUE TITLE
Need DSL introduction document for Milvus0.11.0

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#4150]
As title.

**Comment by BossZou** [comment]
May you can learn in [python doc](https://pymilvus.readthedocs.io/en/latest/query.html).

**Comment by sahuang** [comment]
I don't think it is a good way for users to learn the usage of anything (in this case, DSL query) under a specific SDK's documentation. The user may not use that programming language, and their first action is to usually look up our official website.

Therefore, DSL introduction should be placed here: https://milvus.io/docs/v0.11.0/search_entity.md. This is the place a normal user would look at when they do not know how to construct a DSL statement.

I highly recommend @PahudPlus to include more information about DSL in `Conduct a similarity search` section.

**Comment by PahudPlus** [comment]
Agreed. Will add a separate Advanced Guide on DSL.
