### ISSUE TITLE
insert milvus error

### ISSUE THREAD

**Issue by lidachuan211** [milvus-io/milvus#4151]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
 the client read data from milvus, such as function(getCollectionStats), response success.
the client write data into milvus , such as funciton(insert) ,throw error:
ServerSideMilvusException{errorCode=UNEXPECTED_ERROR, reason=Fail to get partition

Insert data with restful api, success! ,but generate two files:
![image](https://user-images.githubusercontent.com/3982728/97777700-f1ccfc80-1bac-11eb-9643-ecde999347bf.png)

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by sahuang** [comment]
The server side error says that you tried to insert entities into a partition that does not exist. Can you double-check the partitions you created in the collection and intended to insert into?

**Comment by lidachuan211** [comment]
thank you ,done,  find a question in milvus.yaml
