### ISSUE TITLE
Incorrect collection data size when row count larger than 2610000

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#4154]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Collection data size in meta incorrect when row count larger than 2610000

**Steps/Code to reproduce behavior**
1. Create a collection, dimension=200
2. insert 2620000 vectors
3. use get_collection_stats() to get collection information, the 'data_size' is 18446744071567022708(mysql) or 1(sqlite), which is incorrect

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
Already fixed by pr4155 in 0.11.1

**Comment by del-zhenwu** [comment]
Need to add case for computing data_size

**Comment by del-zhenwu** [comment]
added
