### ISSUE TITLE
Client run well unexpectedly if the type of inserted entities mismatch

### ISSUE THREAD

**Issue by BossZou** [milvus-io/milvus#4157]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
There is a field named "int" in a collection, which type is `INT64`. During inserting, I specify "int" field as `DOUBLE` type. I expect raise a exception in client side but the process run well.

**Steps/Code to reproduce behavior**
Create collection
```
    collection_name = fake.collection_name()
    collection_param = {
        "fields": [
            {"name": Field_Integer, "type": DataType.INT64},
            {"name": Field_Vector, "type": DataType.FLOAT_VECTOR, "params": {"dim": dim}},
        ],
        "segment_row_limit": 8192,
        "auto_id": True
    }

    connect.create_collection(collection_name, collection_param)
```

Insert entities
```
vectors = records_factory(dim, 10000)
integers = integer_factory(10000)

entities = [
     {"name": "Vec", "values": vectors},
     {"name": "Int", "values": integers, "type": sd}
]

connect.bulk_insert(hvcollection, entities)
```

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [x] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
- 0.11.1

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
For insert(), milvus server doesn't check data type, it only check the size of each field.
For example, a collection has two fields, one is int64, the other is float. When client invoke insert(), it should makesure the count each field is same. Milvs server will consume the data as binary bytes.

**Comment by BossZou** [comment]
However, this issue could cause a bug where data received by server is different from that requested by client. Assume the type of a field is defined as `FLOAT`, but call insert() specifying the field as `INT32` type. During serialization and deserialization, the data could loss precision. So I think it's a bug.

**Comment by yhmo** [comment]
duplicated with 4511
