### ISSUE TITLE
Does Milvus support to use on nvidia jetson xavier?

### ISSUE THREAD

**Issue by 17120033** [milvus-io/milvus#4161]
**Please state your issue using the following template and, most importantly, in English.**

**What would you like to be added ?**

**Why is this needed ?**

**Comment by 17120033** [comment]
note: i need to do embeddings similarity search on nvidia jetson xavier, like Face recognition task！！！

**Comment by scsven** [comment]
@17120033 Hi, Milvus does not support running on the ARM platform now. There is an old version that works on NVIDIA Jetson Nano: https://github.com/scsven/milvus/tree/jetson-nano.

**Comment by 17120033** [comment]
> @17120033 Hi, Milvus does not support running on the ARM platform now. There is an old version that works on NVIDIA Jetson Nano: https://github.com/scsven/milvus/tree/jetson-nano.

Thank you very much for your reply. In addition to Milvus, are there any other embeddings similarity search libraries that can be easily used on NVIDIA Jetson Xavier？

**Comment by yhmo** [comment]
@17120033 
We also don't know the answer.  But you can try compile faiss on ARM, please refer this link:
https://github.com/facebookresearch/faiss/issues/567

**Comment by digger18** [comment]
Any update on this matter? I would like to use Milvus on Jetson Xavier NX.

**Comment by yhmo** [comment]
> Any update on this matter? I would like to use Milvus on Jetson Xavier NX.

We don't have enough resource to investigate compile milvus on ARM. You need to try it by yourself.

**Comment by deeplearningers** [comment]
> 
did you find any other database？use milvus? thank u

**Comment by xiaofan-luan** [comment]
> > 
> 
> did you find any other database？use milvus? thank u

Should be fine to compile milvus and knowhere right know~
Feel free to test it and let us know if it works. So far Mac M1 processor is ready to go, we don't have any device on hand to do further test
