### ISSUE TITLE
milvus admin登录不上成功 报网络错误

### ISSUE THREAD

**Issue by Jie-Yuan** [milvus-io/milvus#4162]
![image](https://user-images.githubusercontent.com/20265321/97965228-000d5980-1df5-11eb-8b86-e4d86790a778.png)

启动方式["/bin/bash","-c","/app/build/env.sh && yarn start:prod"]

**Comment by yhmo** [comment]
Milvus server is still alive?

**Comment by nameczz** [comment]
What's your milvus version and milvus-em version?

Also you can follow https://zilliz.com/products/em

**Comment by Jie-Yuan** [comment]
> What's your milvus version and milvus-em version?
> 
> Also you can follow https://zilliz.com/products/em

是这个版本

**Comment by Jie-Yuan** [comment]
> Milvus server is still alive?



> Milvus server is still alive?

Yes

**Comment by Jie-Yuan** [comment]
之前的版本登录都没啥问题

**Comment by nameczz** [comment]
> > What's your milvus version and milvus-em version?
> > Also you can follow https://zilliz.com/products/em
> 
> 是这个版本

If you milvus is v0.11.0 and milvus-em is v0.5.0. 
Your docker run command like: 
docker run -d -p 3000:80 -e API_URL=http://your-milvus-em-ip:3000 milvusdb/milvus-em:v0.5.0.
API_URL is required.
