### ISSUE TITLE
Datatype not matched 

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#4173]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```

self = <test_get_entity_by_id.TestGetBase object at 0x7fc8ec1dd470>, connect = <milvus.client.stub.Milvus object at 0x7fc90181c5c0>, collection = 'test_5LnMhyF4', get_pos = 500

    def test_get_entity_field(self, connect, collection, get_pos):
        '''
        target: test.get_entity_by_id, get one
        method: add entity, and get
        expected: entity returned equals insert
        '''
        ids = connect.bulk_insert(collection, default_entities)
        connect.flush([collection])
        get_ids = [ids[get_pos]]
        fields = ["int64"]
        res = connect.get_entity_by_id(collection, get_ids, fields = fields)
        # assert fields
        res = res.dict()
        assert res[0]["field"] == fields[0]
        assert res[0]["values"] == [default_entities[0]["values"][get_pos]]
>       assert res[0]["type"] == DataType.INT64
E       AssertionError: assert <class 'type'> == <DataType.INT64: 5>
E         -<class 'type'>
E         +<DataType.INT64: 5>

entity/test_get_entity_by_id.py:292: AssertionError

```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by BossZou** [comment]
This bug has been fix at the lastest test version `pymilvus-test`.
