### ISSUE TITLE
Milvus EM cannot display vector data normally.

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#4189]
version：Milvus EM v0.4.0

![image](https://user-images.githubusercontent.com/53512883/98430003-63450780-20e5-11eb-9cc5-b7e940fc1f7e.png)

The count interface shows that there are 10 vectors, but the right panel shows no vectors.

**Comment by nameczz** [comment]
We can update milvus to v0.10.3 and em to v0.4.1. Will working fine.
