### ISSUE TITLE
Issue when installing on Raspberry Pi OS

### ISSUE THREAD

**Issue by rose-jinyang** [milvus-io/milvus#4191]
Hello
How are you?
Thanks for contributing this project.
I am going to use the milvus on Raspberry Pi OS.
I tried to install milvus-aarch64 source but failed.
Does the milvus support Raspberry Pi OS?
Thanks

**Comment by scsven** [comment]
@rose-jinyang The current version of Milvus does not support running on Raspberry Pi. There is an old branch based on v0.6.0 that works on Raspberry Pi 4b.

**Comment by scsven** [comment]
@rose-jinyang I'm sorry, I forgot to write the URL. This is the branch work on Raspberry Pi 4b with Ubuntu(I forgot the version, maybe 19.10): https://github.com/milvus-io/milvus/tree/aarch64. To build milvus from source code, 64 bit OS is required. There is a script in the `core` directory, just run it.
