### ISSUE TITLE
if the password of the mata mysql contains "@", milvus can not construct a connection to mysql

### ISSUE THREAD

**Issue by Alsace-lee** [milvus-io/milvus#4195]
for example :

I got a mysql database like this
mysql://root:123@abc@192.168.65.103:3306/milvus

if i write this line in the config file, milvus can not get start with this file.

**Comment by shengjun1985** [comment]
Excuse me, could you provide your Miluvs version?

**Comment by Alsace-lee** [comment]
> Excuse me, could you provide your Miluvs version?

we are runing milvus 0.10.2 in production

**Comment by yhmo** [comment]
I can successfully run Milvus with mysql which password contains "@", by the following steps:

1. Download mysql docker image
`docker pull mysql:5.7`

2. Run mysql container, set password to "123@456"
`docker run -p 3306:3306 -e MYSQL_ROOT_PASSWORD='123@456' -d mysql:5.7`

3. use mysql client login to mysql
`mysql -h127.0.0.1 -uroot -p'123@456'`

4. create a database named 'milvus'
`create database milvus`

5. modify Milvus's config file: server_config.yaml
```
general:
  timezone: UTC+8
  meta_uri: mysql://root:123@456@[your machine IP]:3306/milvus
```
Note: if you encounter error "Can't construct MySQL connection", please change the uri, replace the "127.0.0.1" by your machine's IP address

6. run milvus container
