### ISSUE TITLE
A collection is successfully created  with parameters outside of segmentRowLimit and autoId

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#4197]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
create a collection with params outside the `segment_row-count` and "auto_id', and the parameter showed in collection info.
```
params := map[string]interface{}{
			"auto_id":           autoId,
			"segment_row_limit": utils.DefaultSegmentRowLimit,
			"AAA": "aaa",
		}
```
```
[{float_vector 101 {{}} {{"params":"{\"dim\":128}"}}} {float 10 {{}} {{"params":"null"}}}] {{"params":"{\"AAA\":\"aaa\",\"auto_id\":false,\"segment_row_limit\":5000}"}}} {0 OK} <nil>
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**
maybe it's a problem for the further interface such as update collection

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 -0.11.1

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by sahuang** [comment]
Currently server only checks for the existence of required parameters; extra parameters will not be validated.

**Comment by shengjun1985** [comment]
same as the issue
https://github.com/milvus-io/milvus/issues/3919#issuecomment-705956914
