### ISSUE TITLE
Support string data type in entity

### ISSUE THREAD

**Issue by supercoderhawk** [milvus-io/milvus#4201]
Now, milvus not support string data type in entity according to the document
```python
Milvus doesn't support string type yet,
```
However, the string is a frequently-used data type for a production level search engine. I hope milvus will support string data  type in entity and it can be returned in the search result.

**Comment by sahuang** [comment]
Please refer to this issue: https://github.com/milvus-io/milvus/issues/1924
There has already been some discussions there.
