### ISSUE TITLE
How to create index for scalar data?

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#4202]
link: https://milvus.io/cn/docs/v0.11.0/release_notes.md#RESTful

![image](https://user-images.githubusercontent.com/53512883/98522001-2298ea00-22af-11eb-918d-b9f50526f473.png)

We cannot find a way to create an index for scalar data on the official website.

**Comment by fishpenguin** [comment]
The way you create scalar data index is similar to vector data, the difference is that the index type of scalar data is "SORTED".
Meanwhile, If you did not call create_index to create scalar data index, the index will be created automatically when search.

**Comment by BossZou** [comment]
Also need to add in python doc.

**Comment by BossZou** [comment]
At python client, you can refer to [scalar index](https://pymilvus.readthedocs.io/en/latest/param.html#scalar-index).

**Comment by BossZou** [comment]
Done. Close.
