### ISSUE TITLE
Failed to getQueryResultsList when search result is empty

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#4207]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
    @Test
    public void testSearchPartition() {
        String tag = "tag";
        List<String> queryTags = new ArrayList<>();
        queryTags.add(tag);
        List<Long> ids = init_data();
        service.createPartition(tag);
        Query query = genQuery(MetricType.L2, queryVectors, top_k, n_probe);
        SearchParam searchParam = service.buildSearchParam(query).setPartitionTags(queryTags).setParamsInJson("{\"fields\": [\"int64\"]}");
        SearchResult res_search = service.search(searchParam);
        Assert.assertEquals(res_search.getTopK(), 0);
        res_search.getQueryResultsList();
    }
```
console output
```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
```
source code:  when the size of `this.resultIdsList` is 0, the `get(i).get(j)` out of index
```
    public List<List<SearchResult.QueryResult>> getQueryResultsList() {
        return (List)IntStream.range(0, this.numQueries).mapToObj((i) -> {
            return (List)IntStream.range(0, ((List)this.resultIdsList.get(i)).size()).mapToObj((j) -> {
                return new SearchResult.QueryResult((Long)((List)this.resultIdsList.get(i)).get(j), (Float)((List)this.resultDistancesList.get(i)).get(j));
            }).collect(Collectors.toList());
        }).collect(Collectors.toList());
    }
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)
 -0.11.1

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by sahuang** [comment]
Fixed, please recheck @ThreadDao 

getQueryResultsList() will return a List<List<xxx>> with outer list size nq and inner list size 0.
