### ISSUE TITLE
Using the same index file and metadata on different machines with the same hardwares. The search performance of the two machines is quite different 

### ISSUE THREAD

**Issue by Alsace-lee** [milvus-io/milvus#4208]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

we got （32000k 256d）data, and create IVF_SQ8 index.
Using the same index file and metadata on different machines with the same hardwares. The search performance of the two machines is quite different (In matadata, the file type of each is 3 or 7). 
One of the machines can reach a performance of about 500ms, and the performance of the other is 10 times slower

**Steps/Code to reproduce behavior**
(1)  Start Milvus server using config file like this：
_version: 0.5
cluster:
  enable: true
  role: ro
general:
  timezone: UTC+8
  meta_uri: mysql://xxxx:xxxx@xxx..xxx.xxx:3306/milvus

network: 
  bind.address: 0.0.0.0
  bind.port: 7051
  http.enable: true
  http.port: 7050

storage:
  path: /var/lib/milvus
  auto_flush_interval: 1

wal:
  enable: false
  recovery_error_ignore: false
  buffer_size: 256MB
  path: /var/lib/milvus/wal

cache:
  cache_size: 19GB
  insert_buffer_size: 1GB
  preload_collection: '*'

gpu:
  enable: false
  cache_size: 6GB
  gpu_search_threshold: 1000
  search_devices:
    - gpu0
  build_index_devices:
    - gpu0

logs:
  level: info
  trace.enable: true
  path: /var/lib/milvus/logs
  max_log_file_size: 1024MB
  log_rotate_num: 0

metric:
  enable: false
  address: 127.0.0.1
  port: 9021_

The other one is totally the same.

(2) run the container
docker run -d --name milvus_ro_tel_micen_pic_7.100-7051  --cpus 10 -m 20480m -p 7051:7051 -p 7050:7050 -v $CONFDIR/conf:/var/lib/milvus/conf -v $DBDIR:/var/lib/milvus/db -v $LOGDIR/logs:/var/lib/milvus/logs -v $WALDIR/wal:/var/lib/milvus/wal milvusdb/milvus:0.10.3-cpu-d091720-f962e8

(3) you can read docker_inspect.txt for more details
[docker_inspect.txt](https://github.com/milvus-io/milvus/files/5515964/docker_inspect.txt)

**Expected behavior**

Performance should be at the level of 500 milliseconds

**Method of installation**
- [1 ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)
Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz  32cores cpu (support AVX2 AVX512 SSE4_2)
128GB memory 70%free

- Milvus version (master or released version)
 milvus 0.10.3

**Screenshots**
milvus_server has load 8500+MB index file already
![image](https://user-images.githubusercontent.com/61733548/98649855-0e1e2580-2373-11eb-9852-7f36f002546c.png)

when I start search
![image](https://user-images.githubusercontent.com/61733548/98649959-360d8900-2373-11eb-8bb8-1678083a9001.png)
All cpu resourse used, this is not expected situation

you can read the debug uploaded for detailes
[debug_log.txt](https://github.com/milvus-io/milvus/files/5515632/debug_log.txt)

**Additional context**
We have made many attempts, including not limited to replacing cpu instruction sets, migrating data, and expanding or shrinking hardware resources. None of this can change this situation.

**Comment by Alsace-lee** [comment]
add: When searching on a machine with poor performance, a single search will use up all CPU resources

**Comment by yhmo** [comment]
The most possible reason is: the machine is numa architecture

**Comment by yhmo** [comment]
Use these commands and docker parameters to avoid unstable performance on machine with NUMA:

- Firstly print numa information in cmdline:
`lscpu`
If the machine is NUMA, this command will print something like:
```
NUMA node 0 cpu: 0,2,4,6,8......
NUMA node 1 cpu: 1,3,5,7,9......
```
That means the machine has two NUMA nodes, the "0" node owns cpu 0,2,4,6,8 cpu, the "1" node owns cpu 1,3,,5,7,9

- Run docker container by following these parameters:
Specify CPUs in which to allow execution (0-3, 0,1)
`--cpuset-cpus=""`

Specify memory nodes in which to allow execution (0-3, 0,1). Only effective on NUMA systems.
`--cpuset-mems="" `
For example, we can start milvus container like this:
docker run --cpuset-cpus="0,2,4" --cpuset-mems="0" -it -d -p 19530:19530 milvusdb/milvus:x.x.x-xxx-xxxxx-xxxxxx

**Comment by Alsace-lee** [comment]
> The issue has been solved.
> Use these commands and docker parameters to avoid unstable performance on machine with NUMA:
> 
> * Firstly print numa information in cmdline:
>   `lscpu`
>   If the machine is NUMA, this command will print something like:
> 
> ```
> NUMA node 0 cpu: 0,2,4,6,8......
> NUMA node 1 cpu: 1,3,5,7,9......
> ```
> 
> That means the machine has two NUMA nodes, the "0" node owns cpu 0,2,4,6,8 cpu, the "1" node owns cpu 1,3,,5,7,9
> 
> * Run docker container by following these parameters:
>   Specify CPUs in which to allow execution (0-3, 0,1)
>   `--cpuset-cpus=""`
> 
> Specify memory nodes in which to allow execution (0-3, 0,1). Only effective on NUMA systems.
> `--cpuset-mems="" `
> For example, we can start milvus container like this:
> docker run --cpuset-cpus="0,2,4" --cpuset-mems="0" -it -d -p 19530:19530 milvusdb/milvus:x.x.x-xxx-xxxxx-xxxxxx


As you said, the server has two CPUs. Using the '-cpus' command during the container startup process, Docker cannot guarantee that the CPU resources and memory resources are divided into the same numa node, which will cause performance degradation.
