### ISSUE TITLE
[BUG]GPU resources are not fully used

### ISSUE THREAD

**Issue by Bennu-Li** [milvus-io/milvus#421]
**Describe the bug**
index_type: sq8h
search_resources: 
    - cpu
    - gpu0
    - gpu1
    - gpu2
    - gpu3

when I searched, it only used three graphics cards.
But after I restart the service,  it can use all the gpu resources.

**Comment by fishpenguin** [comment]
This bug only appeared once in v0.5.3, I need to reproduce this bug in 0.6.0.

**Comment by JinHai-CN** [comment]
Can't reproduce.
