### ISSUE TITLE
compatiable issue in tests/milvus_benchmark/client.py

### ISSUE THREAD

**Issue by altonchuzhan** [milvus-io/milvus#4210]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
encounter an error while running benchmark test. 
the command is 
`python3 main.py --local --host=*.* --port=19530 --suite=suites/cpu_accuracy_ann.yaml`
` 
File "main.py", line 172, in <module>
    main()
  File "main.py", line 168, in main
    runner.run(run_type, collection)
  File "/search/odin/zhangchuan/milvus.io/milvus/tests/milvus_benchmark/local_runner.py", line 32, in run
    logger.info(milvus_instance.show_collections())
  File "/search/odin/zhangchuan/milvus.io/milvus/tests/milvus_benchmark/client.py", line 184, in show_collections
    return self._milvus.show_collections()
`

**Steps/Code to reproduce behavior**
use milvus code branch 0.10.3, and client pymilvus==0.2.14

**Expected behavior**
no error

**Method of installation**
- [ x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
milvus code branch 0.10.3, and client pymilvus==0.2.14

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**
I checked the pymilvus code, the show_collections had been renamed as list_collections on 0.2.11. so I think there are compatiable problem amony multiple versions.
rename show_collections to list_collections fix my problem for now.

**Comment by altonchuzhan** [comment]
[the slack thread here](https://milvusio.slack.com/archives/C012DUVUFNZ/p1604977377037400)

**Comment by del-zhenwu** [comment]
actually we use the internal `milvus_benchmark` scripts to test, we will copy the valid scripts into `tests/milvus_benchmark` to fix this issue

**Comment by altonchuzhan** [comment]
thankyou, hope the fix online soon

**Comment by del-zhenwu** [comment]
> thankyou, hope the fix online soon

We will update it on branch `0.10.4`, and it's compatible for branch `0.10.3`, for the codes on brach `0.10.3` is frozen, I wonder if it is satisfied to you?

**Comment by altonchuzhan** [comment]
I hope there can be more test suite. it only have accuracy template for now, the doc said there are many kinds of template, e.g. build_performance,insert_performance,accuracy,stability,search_stability

btw, I quite want a latency per query counter for single query perf. you seem more intereted on load/throughput but don't care single query perf.

**Comment by altonchuzhan** [comment]
the fix is good.

**Comment by del-zhenwu** [comment]
Another few days I need to fix some style issues, scripts on branch can be used before PR merged

**Comment by del-zhenwu** [comment]
test scripts have updated
