### ISSUE TITLE
The query time fluctuates greatly

### ISSUE THREAD

**Issue by lllxxx3030** [milvus-io/milvus#4221]
Continuous circular query for 1000 times 1: N, the query time is from 8 ms to 500 ms, query time is not stable...

Is the reason for high CPU usage???

**Comment by yhmo** [comment]
Could you provide more information?
We need:
- milvus version
- how many entities in the collection, how many partitions
- the collection parameters: vector dimensions, segment size (index_file_size or segment_row_limit)
- what kind of index, index parameters such as nlist
- query parameters: nq, topk, nprobe

**Comment by lllxxx3030** [comment]
1、milvus_cpu_0.10.2
2、The number of vectors is 5000，partitions is 1
3、vector dimensions=256, segment size=1032000000, index_file_size=2147483648
4、index type is hnsw, m=16, efConstruction=500
5、nq=10, topk=10, cpus=4

**Comment by shengjun1985** [comment]
@lllxxx3030 
(1) What's your query parameter?
(2) Did the 1000 times tests use the same query vectors?
(3) If it is convenient, can you send us your Milvus debug log?

**Comment by shengjun1985** [comment]
@lllxxx3030
Your data size is very small (5000).
I tested in my notebook with C++ SDK thousands of times. And each time it cost only 1ms.
Which SDK did you choose?
Were there any other processes running when you tested?

**Comment by op-hunter** [comment]
@lllxxx3030 
I have repeated the experiment based on the information you provided by python sdk and can not reproduce your situation.
My test code: https://paste.ubuntu.com/p/nTJ4pWnPjd/
My test log: https://paste.ubuntu.com/p/SKZPx2bXwK/
By the way, in version 0.10.2, `index_file_size` must be in range [1, 4096].

**Comment by shengjun1985** [comment]
If you have more questions, please continue to contact our community.
