### ISSUE TITLE
 The Prometheus performance metrics sent by Milvus 0.11.0 is not right.

### ISSUE THREAD

**Issue by yu-hailong** [milvus-io/milvus#4226]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

![image](https://user-images.githubusercontent.com/17443614/98905249-10f55380-24f6-11eb-9cc6-1df2e49819cf.png)

1. The instance should be ip or hostname, so we can recoginize easily
2. the value is not correct, it is always zero even querying with high QPS 

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ X ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
0.11.0

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by fishpenguin** [comment]
The performance metrics of 0.11.0 has bugs, we will fix it later in branch 0.11.1.
