### ISSUE TITLE
Customize metric function

### ISSUE THREAD

**Issue by sunM123** [milvus-io/milvus#4227]
希望可以自定义向量距离计算方式，比如说采用主题模型进行向量表征时，对于向量的距离计算通常采用Hellinger Distance或者Jensen-Shannon Divergence (JSD)，使用余弦距离或欧氏距离并不合适

**Comment by sahuang** [comment]
Duplicated with #4262 

Please track that issue for our latest updates, thank you.

**Comment by shengjun1985** [comment]
@sunM123
Excuse me, what's your vector type, float or binary?
Metric function and index type are closely related.
So how much data do you have, and do you need to create index to speed up queries?
Furthermore, do these functions satisfy trigonometric inequalities (|AB|+|BC|<=|BC|)?

**Comment by sunM123** [comment]
向量的类型是浮点型的。据我了解，由LDA（即主题模型）生成的向量表征表示的是一种主题分布，再通过计算两个多项分布的距离来衡量它们之间的相似度。衡量多项分布的距离，并不适合于使用常规的例如余弦距离等方式计算相似性，（当然说不定尝试一下可能也会有不错的效果），不过常规来说还是使用Hellinger Distance和Jensen-Shannon Divergence (JSD)。关于HD，可以参考下面的博客：https://www.cnblogs.com/denny402/p/7054950.html（上述博客非本人所写，仅代表作者观点）。
关于建立索引加快查询速度，这是当然需要的。关于函数是否满足三角不等式，这个我还需要进一步查证。

**Comment by shengjun1985** [comment]
@sunM123
To add a new metric type without index (index type: FLAT) is an easy job.
Are you willing to contribute codes for our project?

After a new metric type added to FLAT, we can test the performance.
If necessary, we can research how to index them later.

**Comment by sunM123** [comment]
好的，如果可以的话，我之后会进行提交代码的尝试，非常感谢

**Comment by shengjun1985** [comment]
【Hellinger Distance】
![image](https://user-images.githubusercontent.com/49774184/104085526-3c44b680-528b-11eb-8b21-1fa2595f2de6.png)
If each coordinate value is preprocessed (take a square root), Hellinger Distance can be replaced by L2.
And it will let query be more efficient.

**Comment by shengjun1985** [comment]
【Jensen-Shannon Divergence】
![image](https://user-images.githubusercontent.com/49774184/104086424-e2e08580-5292-11eb-9482-7faad5922807.png)
JSD doesn't seem to be easy to index. so it may only supported by FLAT.

**Comment by scsven** [comment]
Not activity.
