### ISSUE TITLE
Version 0.11.0 of the dashboard.json is not available.

### ISSUE THREAD

**Issue by wanzaiqidao** [milvus-io/milvus#4231]
Version 0.11.0 of the dashboard.json is not available. I use this configuration and see no data on the dashboard. It needs an update.

**Comment by fishpenguin** [comment]
Do you mean grafana dashboard.json?
If so, Is it all "no data" or only partially "no data". If it all shows "no data", you need to check the sequence if you server starting.

**Comment by wanzaiqidao** [comment]
> Do you mean grafana dashboard.json?
> If so, Is it all "no data" or only partially "no data". If it all shows "no data", you need to check the sequence if you server starting.

It is partically "no data".  like this
![image](https://user-images.githubusercontent.com/16556519/99927352-06517e80-2d80-11eb-96e8-9525637f50a1.png)
And this is always zero.
![image](https://user-images.githubusercontent.com/16556519/99927414-46186600-2d80-11eb-9eb3-ea71c346da9e.png)

**Comment by fishpenguin** [comment]
This is the same issue with [4226](https://github.com/milvus-io/milvus/issues/4226), and have been fixed in milvus-0.11.1.
