### ISSUE TITLE
[2020-11-17 09:42:01,372][ERROR][SERVER][CPUTemperature][metric_thread] Could not open hwmon directory

### ISSUE THREAD

**Issue by JamesIsHuang** [milvus-io/milvus#4240]
system version: Linux version 4.14.193-113.317.amzn1.x86_64 (mockbuild@koji-pdx-corp-builder-60005) (gcc version 7.2.1 20170915 (Red Hat 7.2.1-2) (GCC)) #1 SMP Thu Sep 3 19:08:08 UTC 2020

I want to deploy monitor, and get this error log

milvus version: milvus:0.10.3-cpu-d091720-f962e8

**Comment by JamesIsHuang** [comment]
and grafana don't have any data

![image](https://user-images.githubusercontent.com/12915720/99339862-de66a480-28c1-11eb-90f5-8a1e267fdfee.png)

**Comment by fishpenguin** [comment]
hwmon directory is used to get cpu temperature. the complete path is "/sys/class/hwmon", can you check if there is the directory in your system.

**Comment by RobinQu** [comment]
+1 , using `milvusdb/milvus:0.11.0-cpu-d101620-4c44c0`
