### ISSUE TITLE
 Milvus client should know serverlist change and rebanlance request automatically.

### ISSUE THREAD

**Issue by yu-hailong** [milvus-io/milvus#4241]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
1. Connect to Milvus by domain name which includes 3 ro nodes
2. Do query, we found the reqeusts is sent to 3 nodes regularly
3. while removed one nodes from domain name, reqeusts were rebanlanced to the remained 2 nodes .
--
4. But we tried to add a new node into the domain name, no requests were sent to the new node.
   Unless，we inited client and reconnected milvus server, and then requests could be sent to the new node
So, we suggest, milvus client should know serverlist change and rebanlance request automatically.

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**
we suggest, milvus client should know serverlist change and rebanlance request automatically.

**Method of installation**
- [ X ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
0.10.3

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by scsven** [comment]
@yu-hailong It's not a good idea that the client knows the serverlist. A common practice is to use Nginx.

**Comment by yu-hailong** [comment]
I got it, we think gateway(like istio) is needed
