### ISSUE TITLE
insert vector fail

### ISSUE THREAD

**Issue by znn0301** [milvus-io/milvus#4258]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
A clear and concise description of what the bug is. java-sdk 0.9.1
InsertParam insertParam = InsertParam
                .create(collectionName)
                .addField("duration", DataType.INT32, durations)
                .addField("release_year", DataType.INT64, releaseYears)
                .addVectorField("embedding", DataType.VECTOR_FLOAT, embeddingsFloat)
                .setEntityIds(ids);
fail log:
java.lang.NoSuchMethodError: io.milvus.grpc.InsertParam.emptyLongList()Lcom/google/protobuf/Internal$LongList;

	at io.milvus.grpc.InsertParam.<init>(InsertParam.java:26)
	at io.milvus.grpc.InsertParam.<clinit>(InsertParam.java:1573)
	at io.milvus.client.InsertParam.<init>(InsertParam.java:43)
	at io.milvus.client.InsertParam.create(InsertParam.java:39)

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by znn0301** [comment]
The reason finded. grpc-api:1.30.2 conflicted with grpc-api:1.24.0 in my project.
But I start with a new project, only have milvus, there is a question:
List<Long> ids = LongStream.range(0, 10000).boxed().collect(Collectors.toList());
        List<Integer> durations = IntStream.range(0, 10000).boxed().collect(Collectors.toList());
        List<Integer> releaseYears = IntStream.range(0, 10000).boxed().collect(Collectors.toList());
        //List<List<Byte>> embeddings = randomByteVectors();
        List<List<Float>> embeddingsFloat = randomFloatVectors();

        InsertParam insertParam = InsertParam
                .create(collectionName)
                .addField("duration", DataType.INT32, durations)
                .addField("release_year", DataType.INT64, releaseYears)
                .addVectorField("embedding", DataType.VECTOR_FLOAT, embeddingsFloat)
                .setEntityIds(ids);

long count = client.countEntities(collectionName);
the result count equals 0 ,why?

Another question is:
List<Float> queryFiled = randomFloatVectors().get(0);
        List<List<Float>> queryEmbedding = new ArrayList<>();
        queryEmbedding.add(queryFiled);
        System.out.println(queryEmbedding.toString());
        final long topK = 10;
        String dsl = String.format(
                "{\"bool\":{\"must\":[{\"range\":{\"duration\":{\"GT\":250}}},{\"term\":{\"release_year\":[1,5,10]}},{\"vector\":" +
                        "{\"embedding\":{\"topk\":%d,\"metric_type\":\"L2\",\"type\":\"float\",\"params\":{\"nprobe\":10},\"query\":%s}}}]}}", topK, queryEmbedding.toString());
        SearchParam searchParam = SearchParam
                .create(collectionName)
                .setDsl(dsl);
        SearchResult searchResult = client.search(searchParam);

fail log:
java.lang.NoSuchMethodError: org.json.JSONObject.keySet()Ljava/util/Set;

	at io.milvus.client.SearchParam.locateVectorQuery(SearchParam.java:133)
	at io.milvus.client.SearchParam.setDsl(SearchParam.java:60)

**Comment by sahuang** [comment]
> The reason finded. grpc-api:1.30.2 conflicted with grpc-api:1.24.0 in my project.

This happened multiple times, you need to make sure the dependency is identical.

> But I start with a new project, only have milvus, there is a question:
> List ids = LongStream.range(0, 10000).boxed().collect(Collectors.toList());
> List durations = IntStream.range(0, 10000).boxed().collect(Collectors.toList());
> List releaseYears = IntStream.range(0, 10000).boxed().collect(Collectors.toList());
> //List<List> embeddings = randomByteVectors();
> List<List> embeddingsFloat = randomFloatVectors();
> 
> ```
>     InsertParam insertParam = InsertParam
>             .create(collectionName)
>             .addField("duration", DataType.INT32, durations)
>             .addField("release_year", DataType.INT64, releaseYears)
>             .addVectorField("embedding", DataType.VECTOR_FLOAT, embeddingsFloat)
>             .setEntityIds(ids);
> ```
> 
> long count = client.countEntities(collectionName);
> the result count equals 0 ,why?

You only specified the `InsertParam`. However, you also need to insert the entities into Milvus and most importantly, flush the collection. Your sample code seems to be copied from the examples in milvus java-sdk repo. You should count entities using the following steps.

```java
List<Long> entityIds = client.insert(insertParam);
long beforeEntityCount = client.countEntities(collectionName); // This is STILL 0 because you have not flushed the collection
client.flush(collectionName);
long afterEntityCount = client.countEntities(collectionName); // This is the number you want
```

For your second question, I suppose your DSL query, when the client-side is trying to parse the string into a JSON object, encounters some parse error. The example I provided is here: https://github.com/milvus-io/milvus-sdk-java/blob/0.9.1/examples/src/main/java/MilvusBasicExample.java#L218

Would you like to try running it first and see if the error still happens? Also you can print the `String dsl` to see if anything is wrong.

**Comment by sahuang** [comment]
I just noticed that the error raised is `java.lang.NoSuchMethodError` from `org.json.JSONObject.keySet()Ljava/util/Set`

It is much likely that there is another jar in the dependencies that has the same class (maybe another version for the same library) but doesn't have this method. Can I make sure that you did not use any other dependencies for json? In examples we use `org.json.JSONObject`.

**Comment by znn0301** [comment]
Thank you ,problem already solved.

**Comment by sahuang** [comment]
No worries.
