### ISSUE TITLE
Support config object

### ISSUE THREAD

**Issue by pvhduc97** [milvus-io/milvus#4259]
**What would you like to be added ?**
I want Milvus to have param object. For example when create a collection instead of declare configurations like this:
`param = {'collection_name':collection_name, 'dimension': _DIM, 'index_file_size': _INDEX_FILE_SIZE, 'metric_type': MetricType.L2}
`

I want to declare like this:
`param = CollectionConfig(collection_name=collection_name, dimension=_DIM, index_file_size=_INDEX_FILE_SIZE, metric_type=MetricType.L2)
`

**Why is this needed ?**
So that I can Ctrl+Space to know which argument/setting I can adjust without remembering each argument name in a "param dictionary". Sometimes i need to check documents/examples to know which setting i can config in the "param dictionary".

**Comment by yhmo** [comment]
The v1.1.1 is stable, we only fix critical bugs for v1.x, no more features/improvement.
Abandoned this feature.
