### ISSUE TITLE
We hope that Milvus can provide an interface for custom distance calculation methods.

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#4262]
Although Milvus has provided a variety of distance calculation methods, such as L2, IP, Hamming, etc. 
But there are still some times when the existing distance calculation methods cannot meet our needs, so we hope that Milvus can provide an interface for custom distance calculation methods.

**Comment by shengjun1985** [comment]
@JackLCL 
Would you like to collect more information?
(1) What new distances are needed in general? And what is the vector type (float or binary)?
(2) How much data do they have (e.g. n, dim, nq), and do they need to create index to speed up queries?
(3) Are there any users willing to contribute code to us?
