### ISSUE TITLE
Milvus website can't be opened

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#4267]
After opening milvus website and clicking on the button “Get Started”, 404 appears

![企业微信截图_16061156328073](https://user-images.githubusercontent.com/34296482/99936639-93a3cb80-2d9e-11eb-9a2b-b56120a19a97.png)
https://www.milvus.io/cn/docs/install_milvus.md

**Comment by shengjun1985** [comment]
Fixed.
