### ISSUE TITLE
low performance during loop batch search result

### ISSUE THREAD

**Issue by imaglib** [milvus-io/milvus#4269]
batch = 1000,  "topk": 100, it takes 100s to loop result , is it right?

**Comment by shengjun1985** [comment]
Could you please provide more information?
Milvus version
Milvus config
Data Size (n * dim)
Index_file_size (0.10.x) or segment_row_limit (0.11.x)
Index type, Index param and metric type
CPU type, Memory Size
How many times did you test?

**Comment by imaglib** [comment]
I think it does not matter with server, it took place when client receive the results. The batch size 1000, each one select top 50 items. I use the pymilvus to parse the 1000* 50 results. the codes as follows:
    def get__item(self, item):
        return (self._raw.distances, self._nq, self._entities, self._raw.scores,self._raw.distances, item)
        dis_len = len(self._raw.distances)
        topk = dis_len // self._nq if self._nq > 0 else 0
        start = item * topk
        end = (item + 1) * topk

        slice_entity = list()
        for it in range(start, end):
            entity = self._entities[it]
            if entity.id == -1:
                break

            slice_entity.append(entity)

        end = start + len(slice_entity)

        slice_score = list(self._raw.scores)[start: end] if dis_len > 0 else []
        slice_distances = list(self._raw.distances)[start: end] if dis_len > 0 else []

        return RawQueryResult(slice_entity, slice_distances, slice_score)

**Comment by shengjun1985** [comment]
@imaglib
You have found the bug of the issue. Thank you very much.
But would you like to fix it for our project?

**Comment by BossZou** [comment]
See #3271

**Comment by BossZou** [comment]
Fixed. close it.
