### ISSUE TITLE
Program exit abnormally.

### ISSUE THREAD

**Issue by owlwang** [milvus-io/milvus#4272]
**Describe the bug**
Program exit abnormally
```
Supported CPU instruction sets: sse4_2
FAISS hook SSE42
Milvus server started successfully!
No.0: /var/lib/milvus/bin/milvus_server(_ZN6milvus15PrintStacktraceEv+0x26) [0xb5ef36]
No.1: /var/lib/milvus/bin/milvus_server(_ZN6milvus12HandleSignalEi+0x190) [0xb5faa0]
No.2: /lib64/libc.so.6(+0x36400) [0x7f994f16e400]
No.3: /var/lib/milvus/bin/milvus_server(_ZN6milvus6server9SearchReq9OnExecuteEv+0xa4d) [0x8e1b8d]
No.4: /var/lib/milvus/bin/milvus_server(_ZN6milvus6server7BaseReq7ExecuteEv+0x20) [0x8c3440]
No.5: /var/lib/milvus/bin/milvus_server(_ZN6milvus6server12ReqScheduler13TakeToExecuteESt10shared_ptrINS0_8ReqQueueEE+0x12d) [0x8bf9fd]
No.6: /var/lib/milvus/bin/milvus_server(_ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJMN6milvus6server12ReqSchedulerEFvSt10shared_ptrINS4_8ReqQueueEEEPS5_S8_EEEEE6_M_runEv+0x47) [0x8c1fa7]
No.7: /var/lib/milvus/bin/milvus_server() [0x11192ff]
No.8: /lib64/libpthread.so.0(+0x7ea5) [0x7f994fd2cea5]
No.9: /lib64/libc.so.6(clone+0x6d) [0x7f994f2368dd]
Milvus server is going to shutdown ...
Milvus server exit...
terminate called after throwing an instance of 'std::system_error'
  what():  Resource deadlock avoided
```
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

do a query by enterprise manager devtool.
structure:

m_id: int64
m_vec: vector_float

query dsl:
```
{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "m_id": [
              233
            ]
          }
          }
      ]
    }
  }
}
```

**Method of installation**
- [ * ] Docker/cpu

- Milvus version (master or released version)

Milvus Release version: v0.11.0, built at 2020-10-16 13:33.03, with OpenBLAS library.
You are using Milvus CPU edition
Last commit id: 4c44c03fdeb14f7cbfcfa3ed3b124e32349d712e

**Configuration file**
only change cachesize from 4GB to 8GB

- Logs files:

[error.zip](https://github.com/milvus-io/milvus/files/5582406/error.zip)

**Comment by fishpenguin** [comment]
We do not support only search scalar field in dsl, it means you must include a vector query.
However, this is a bug that milvus should not crash. We will fix it in branch 0.11.1.

**Comment by owlwang** [comment]
Thanks for your quick response and looking forward to the next update.

**Comment by fishpenguin** [comment]
Fixed, closed this issue.
