### ISSUE TITLE
Use boost::dynamic_bitset instead of ConcurrentBitsetPtr

### ISSUE THREAD

**Issue by FluorineDog** [milvus-io/milvus#4277]
Currently, the calculation of DSL is based on `ConcurrentBitsetPtr`, which is slow due to unnecessary atomic memory access (access every bit will always flush the cache line). 

Change it with `boost::dynamic_bitset<>` will have the following pros: 
1. native support for bit manipulating operations: (and, or, negate, ...), and much faster
2. cheap memory access comparing to `ConcurrentBitset`
3. can use `boost::to_block_range` to export the internal storage (which `vector<bool>` can't)

**Comment by shengjun1985** [comment]
Our previous tests have shown that atomic itself is not a performance bottleneck.
But that the bitset has no access locality in IVF will result in severe performance degradation.
However, ff you find it convenient to use, you can also try to modify it.

**Comment by FluorineDog** [comment]
After investigation, maybe it's better to decouple the storage and search:
- For storage and DSL calculation, don't modify the code, just use the `ConcurrentBitmapPtr` anyway;
- For searching, use the following `BitmapView`, and create a `BitmapView` from `ConcurrentBitmapPtr`, `boost::dynamic_bitmap`, `std::bitset` etc., just like `const char*`, `std::string` to `std::string_view`
```c++
struct BitmapView {
  const char* ptr_to_bitmap;
  int64_t size; // optional
 public:
  bool test(int64_t index) { /* easy implementation */} 
};
```
