### ISSUE TITLE
milvus_server always use gpu0, but I didn't set it

### ISSUE THREAD

**Issue by lqqnjust** [milvus-io/milvus#4283]
Version: 0.10.2-gpu
I set search_devices: gpu8, build_index_devices: gpu9。
Use nvidia-smi ， I found milvus_servicer use gpu0 and gpu9。

**Comment by scsven** [comment]
@lqqnjust Hi, Milvus will use some memory on gpu0 whatever. If you find that Milvus uses other GPUs please let us know.
