### ISSUE TITLE
milvus_benchmark failed to run local due to missing of milvus_metrics module

### ISSUE THREAD

**Issue by douglarek** [milvus-io/milvus#4284]
Reproduce steps:
* $ git clone https://github.com/milvus-io/milvus.git -b 0.11.1
* [use docker run a local Milvus](https://milvus.io/docs/milvus_docker-cpu.md)
* $ cd tests/milvus_benchmark
* $ pip install -r requirements.txt
* $ python3 main.py --local --host=127.0.0.1 --port=19530 --suite=suites/gpu_search_performance_random50m.yaml

Got errors:

```
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    from k8s_runner import K8sRunner
  File "/home/works/milvus-src/tests/milvus_benchmark/k8s_runner.py", line 21, in <module>
    from milvus_metrics.api import report
ModuleNotFoundError: No module named 'milvus_metrics'
```

**Comment by del-zhenwu** [comment]
Scripts updated, move `import K8sRunner` into `queue_worker` in `main.py`
