### ISSUE TITLE
milvus_benchmark should be able  to run using a docker image 

### ISSUE THREAD

**Issue by douglarek** [milvus-io/milvus#4285]
I have issued a bug #4284 , since the environment is ever-changing, we should be able to run milvus_benchmark through a docker image just like we deploy a docker Milvus instance.

**Comment by del-zhenwu** [comment]
`docker mode` was removed several months ago, and using `k8s mode` in regression test instead. I will add `docker mode` later.

**Comment by douglarek** [comment]
> `docker mode` was removed several months ago, and using `k8s mode` in regression test instead. I will add `docker mode` later.

thanks, k8s is a little heavy for local run.
