### ISSUE TITLE
查询语句指定返回字段的fields不生效，只能返回id和对应的距离

### ISSUE THREAD

**Issue by Flipped95** [milvus-io/milvus#4290]
![image](https://user-images.githubusercontent.com/75009726/100196471-dcd95400-2f33-11eb-8387-a6046555f7b5.png)

**Comment by fishpenguin** [comment]
You create collection with a vector field name "vec", but you write "vector" in the "fields".

**Comment by Flipped95** [comment]
![image](https://user-images.githubusercontent.com/75009726/100403582-3d82a100-309a-11eb-90b0-f24daa1808f2.png)
![image](https://user-images.githubusercontent.com/75009726/100403573-36f42980-309a-11eb-96c3-4f0b27d22e89.png)
