### ISSUE TITLE
根据分区查询数据的restful接口不可用，提示Current url has no mapping

### ISSUE THREAD

**Issue by Flipped95** [milvus-io/milvus#4291]
![image](https://user-images.githubusercontent.com/75009726/100196739-43f70880-2f34-11eb-8c04-a8c3f82fb082.png)
![image](https://user-images.githubusercontent.com/75009726/100196743-45c0cc00-2f34-11eb-8244-d6c4d8f4395a.png)

**Comment by fishpenguin** [comment]
Which version of milvus did you use?

**Comment by fishpenguin** [comment]
This interface is deleted in 0.11, You can get the entites of a partition by: "/collections/{collection_name}/entities?page_size=10&offset=0&partition_tags="part_1".
It means that you need to point the page_size and offset when get entities from a partition.

**Comment by fishpenguin** [comment]
However, this interface still exists in readme.md of webserver. It's a doc bug, we will fix the readme.md in 0.11.1.
