### ISSUE TITLE
When the container is restarted, the lock file permission is denied. How to solve this problem?

### ISSUE THREAD

**Issue by qihaoxiansheng** [milvus-io/milvus#4295]
Error: Cannot lock file: /var/lib/milvus/wal/lock, error(11): Permission denied.

**Comment by scsven** [comment]
@qihaoxiansheng Do you mount `/var/lib/milvus/wal` directory? If multiple Milvus start on the same directory, you will get this error.

**Comment by qihaoxiansheng** [comment]
How to solve this problem?

**Comment by qihaoxiansheng** [comment]
After I stop milvus, I still hope to restart milvus successfully. If i encouter this problem, what should i do ?

**Comment by scsven** [comment]
@qihaoxiansheng If you mount `/var/lib/milvus/wal` to `/home/$USER/milvus/wal`, please go to `/home/$USER/milvus/wal` and remove the `lock` file manually.

**Comment by qihaoxiansheng** [comment]
If there is data in the previous mysql database,  after lock is removed, when I restart milvus, a new error will appear .
![image](https://user-images.githubusercontent.com/75019315/100305276-ba027a80-2fdb-11eb-8a58-6d7627f3f0b3.png)

**Comment by qihaoxiansheng** [comment]
If I encounter this new problem, what should I do ?

**Comment by scsven** [comment]
@qihaoxiansheng Is there another Milvus instance access this directory?

**Comment by qihaoxiansheng** [comment]
yes, have three milvus instance.

**Comment by scsven** [comment]
Not active, close.
