### ISSUE TITLE
Meta Access QPS is much larger than Query QPS while deploying on K8s

### ISSUE THREAD

**Issue by yu-hailong** [milvus-io/milvus#4300]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

We deployed 6 milvus ro node both on K8S( 3 pod docks) and 3 pysical machines(docker started)
and we found:
1. On pysical machines' docker, Meta Access QPS is same with Query QPS (green line = meta access qps; yellow line = query access)
![image](https://user-images.githubusercontent.com/17443614/100343592-872ba700-301a-11eb-9b56-0908f12a29a3.png)

2. On K8S dockers, Meta Access QPS is much larger than Query QPS(green line = meta access qps; yellow line = query access)
![image](https://user-images.githubusercontent.com/17443614/100343692-ade9dd80-301a-11eb-90dc-db25b3484560.png)

3. and the setting of grafana is the following
![image](https://user-images.githubusercontent.com/17443614/100343847-e5588a00-301a-11eb-967d-bfea62ea77ec.png)

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**
Meta Access QPS is same with Query QPS while deploying on K8s

**Method of installation**
- [ X ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
0.10.3 

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
I think this is a reasonable phenomenon.

For a single machine, each query require access meta two or three times: 
1. get files to search in the collection
2. list partitions of the collection
3. get files to search in the partitions

For multi-read-nodes, each node require access meta two or three times. So the Meta Access QPS is much higher than query QPS.

**Comment by yu-hailong** [comment]
> I think this is a reasonable phenomenon.
> 
> For a single machine, each query require access meta two or three times:
> 
> 1. get files to search in the collection
> 2. list partitions of the collection
> 3. get files to search in the partitions
> 
> For multi-read-nodes, each node require access meta two or three times. So the Meta Access QPS is much higher than query QPS.

I mean, while milvus run on physical machine, Meta Access QPS is same with Query QPS.
but on K8S, Meta Access QPS is MUCH LARGER than Query QPS.

please see the graph
