### ISSUE TITLE
Error: <BaseException: (code=1, message=Illegal data size for chunk field: Vec)>

### ISSUE THREAD

**Issue by herryzhang** [milvus-io/milvus#4301]
Milvus的版本是  0.11.0-GPU版
milvusdb/milvus:0.11.0-gpu-d101620-4c44c0 
pymilvus的版本是
0.3.0

collection的定义是这样的
collection_param = {"fields": [{"name": "Vec", "type": DataType.FLOAT_VECTOR, "params": {"dim": 512}}], "segment_row_limit": 100000,   "auto_id": False}
create_table(index_client, table_name=table_name, fields=collection_param)
增加数据的代码是这样的
# 插入数据
![image](https://user-images.githubusercontent.com/8223359/100359676-d5e53b00-3032-11eb-8b09-68e63224dfe3.png)

ids = []
vectors = []
for row in collection.find():
    ids.append(row['ids'])
    vectors.append(row['vec'])
print(len(ids))
print(len(vectors))
hybrid_entities = [{"name": "Vec", "values": vectors, "type": DataType.FLOAT_VECTOR}]
status = insert_vectors_ids(index_client, table_name, hybrid_entities, ids)
向量特征存在MongoDB
问题是这样的
在数据量为18条记录以下，插入是正常，
但在数据量超过18条是，就报错
Error: <BaseException: (code=1, message=Illegal data size for chunk field: Vec)>
ERROR:root:<BaseException: (code=1, message=Illegal data size for chunk field: Vec)>
![image](https://user-images.githubusercontent.com/8223359/100359626-c5cd5b80-3032-11eb-99f5-c903a0073785.png)

**Comment by BossZou** [comment]
@herryzhang A possible reason is that the inserted vectors are not aligned, that is, some vector dim is not equal to others. You may to check if this case occur.

**Comment by scsven** [comment]
Not active, close.
