### ISSUE TITLE
Setting DSL fields is invalid in restful api, fields are not returned

### ISSUE THREAD

**Issue by Flipped95** [milvus-io/milvus#4302]
![image](https://user-images.githubusercontent.com/75009726/100404022-53dd2c80-309b-11eb-92d5-0fefb8bbb20b.png)
![image](https://user-images.githubusercontent.com/75009726/100404037-5c356780-309b-11eb-94f5-2c256627f6ef.png)

**Comment by fishpenguin** [comment]
It's a doc error. In 0.11.0, if you want to get fields when search, you should write "fields" equal to "query" like below:
{
  "query": {
    "bool": {
      "must": [
        {
          "vector": {
            "vec": {
              "topk": 3,
              "metric_type": "L2",
              "values": [[1,1,1,1]]
            }
          }
        }
      ]
    }
  },
  "fields": ["int", "vec"]
}

**Comment by fishpenguin** [comment]
However, I think the way you write as the webserver readme.md is more reasonable. So this will be fixed in branch 0.11.1.

**Comment by Flipped95** [comment]
Tks
