### ISSUE TITLE
If there any document or demo for `scalar filter` released in v0.11.0? 

### ISSUE THREAD

**Issue by innerNULL** [milvus-io/milvus#4305]
As title, Thank you

**Comment by sahuang** [comment]
Some information on the official website: https://milvus.io/docs/v0.11.0/overview.md?-Scalar-field-filtering
If you are talking about SDK-specific examples or demo, please refer to the following.

Python: https://pymilvus.readthedocs.io/en/0.3.0/
Java: https://github.com/milvus-io/milvus-sdk-java/tree/0.9.1/examples/src/main/java
Go: https://godoc.org/github.com/milvus-io/milvus-sdk-go/milvus
RESTful: https://github.com/milvus-io/milvus/tree/0.11.0/core/src/server/web_impl

**Comment by innerNULL** [comment]
> Some information on the official website: https://milvus.io/docs/v0.11.0/overview.md?-Scalar-field-filtering
> If you are talking about SDK-specific examples or demo, please refer to the following.
> 
> `Python`: https://pymilvus.readthedocs.io/en/0.3.0/
> `Java`: https://github.com/milvus-io/milvus-sdk-java/tree/0.9.1/examples/src/main/java
> `Go`: https://godoc.org/github.com/milvus-io/milvus-sdk-go/milvus
> `RESTful`: https://github.com/milvus-io/milvus/tree/0.11.0/core/src/server/web_impl

got it, thank you
