### ISSUE TITLE
Using trained centroids for new segments

### ISSUE THREAD

**Issue by zhang19941219** [milvus-io/milvus#4306]
With metadata growing, I hope Milvus to add new vector into a temporary cluster by using faiss' 'Add()' method, or only to create index for segment which have not indexes when calling 'CreateIndex' method.

**Comment by sahuang** [comment]
> With metadata growing, I hope Milvus to add new vector into a temporary cluster by using faiss' 'Add()' method
Milvus currently does not support using trained centroids. Do you mean using _existing_ clusters for new vectors?

> or only to create index for segment which have not indexes when calling 'CreateIndex' method.
Can you state your question a little bit clearer? `CreateIndex` will create index on all segments, so it's not needed to create index for a specific segment.

**Comment by zhang19941219** [comment]
> Milvus currently does not support using trained centroids. Do you mean using existing clusters for new vectors?
yes

> Can you state your question a little bit clearer? CreateIndex will create index on all segments, so it's not needed to create index for a specific segment.
I don't need Milvus to create index on all segments, just on new segments.

**Comment by sahuang** [comment]
Just to confirm, your feature request is:

1) Support using trained centroids for new segments;
2) Create Index by segment;

Is that correct?

**Comment by zhang19941219** [comment]
Right，the second one's priority is higher

**Comment by sahuang** [comment]
For the former, we are currently investigating its effect, and may implement later if it's appealing.

For the latter, do you mind sharing your scenario where only partial segments will be indexed while others will not? This does not seem like a common practice when doing vector search.

Thanks.

**Comment by shengjun1985** [comment]
> only to create index for segment which have not indexes when calling 'CreateIndex' method.

That's what's going on right now.
Please refer to [create index](https://milvus.io/docs/v0.10.5/index.md#Create-indexes).
