### ISSUE TITLE
Specify partition to load for load_collection()

### ISSUE THREAD

**Issue by LeeXinghao** [milvus-io/milvus#4307]
**Please state your issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I wish I could use Milvus to do [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by shengjun1985** [comment]
@LeeXinghao 
We have provided PreloadCollection(), but you want a new interface PreloadPartition().
Is it right?

**Comment by LeeXinghao** [comment]
@shengjun1985  
是的！希望能提供 preloadPartition()方法，这样粒度更细更精准。

**Comment by LeeXinghao** [comment]
@shengjun1985 
Hello!   When can preloadPartition () be released? Which version will be released?

**Comment by yhmo** [comment]
Proposal:
Add a parameter for the old interface load_collection()
load_collection(collection_name, partition_tag)
The "partition_tag" parameter default is None, means load whole collection.
If user specify a wrong partition_tag, the interface will return error message.

We will do this change both on 0.10.x and 0.11.x.
For 0.10.x, the next version is 0.10.5, we just release 0.10.4 several days ago. Typically, a new version will be released after 2~3 weeks.

**Comment by LeeXinghao** [comment]
@yhmo 
okay, thank you！

**Comment by shengjun1985** [comment]
It is done.
