### ISSUE TITLE
Support joint search for multiple features

### ISSUE THREAD

**Issue by chenqingguo** [milvus-io/milvus#4327]
object has multiple features,E.g. a person has head and body and legs. when we search person,some object may has all parts but some person just has legs feature.
目标是由多块特征组成的，比如一个人由头、身体和下肢组成。当去检索人，底库的目标有可能有全部特征，也有可能只有下肢特征。
**Describe the solution you'd like**
although object consists of multiple features, I consider it as a whole feature(just splice all parts). E.g. An object hasn't head feature, then the first part of feature is zeros. 
目标是由多块特征组成，还是把它当做一个整体。比如一个目标没有头，那它的第一块特征就全是零。
**Describe alternatives you've considered**
i have implemented this feature in Flat Index. During add stage, compute  if part features exist as flag and save them.
我在暴搜索引初步实现了这个想法。入库时计算目标的局部特征是否存在(标志位)，保存这个信息。检索时，对每个目标，计算每块特征的相似度然后求平均和作为这个目标的最终相似度。由于入库时已经判断每一块特征是否参与计算，计算时直接使用即可。 

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by yhmo** [comment]
0.11.x supports multi-features for an entity, but doesn't support joint search.
