### ISSUE TITLE
Move the invalid result filtering process to the server

### ISSUE THREAD

**Issue by scsven** [milvus-io/milvus#4332]
**Please state your issue using the following template and, most importantly, in English.**

Currently, a search response could contain some results that id is `-1`, which means invalid. The SDK filters out all results with id is -1, this is not the best choice.

**What would you like to be added ?**

Move the invalid result filtering process to the Milvus server.

**Comment by sahuang** [comment]
https://github.com/milvus-io/milvus/issues/4062
