### ISSUE TITLE
Want a convenient way for Chinese users to download

### ISSUE THREAD

**Issue by khw934** [milvus-io/milvus#4335]
**Please state your issue using the following template and, most importantly, in English.**

**What would you like to be added ?**

**Why is this needed ?**

github 下载比较慢， 建议同步到码云 方便国内用户 下载

**Comment by yhmo** [comment]
The milvus on gitee:
https://gitee.com/milvus-io/milvus

**Comment by yaleimeng** [comment]
docker pull方式下载镜像非常慢（已经选择国内源），从源码编译又总是出错。
能否提供docker镜像的网盘下载渠道？

**Comment by yhmo** [comment]
> docker pull方式下载镜像非常慢（已经选择国内源），从源码编译又总是出错。
> 能否提供docker镜像的网盘下载渠道？

我在家里用电信宽带拉docker hub的镜像还挺快的，cpu版本的镜像只有220M，不应该下不下来啊，你确定你国内镜像设置对了么？ 
https://www.jianshu.com/p/3b062c177508
设置后要 `systemctl restart docker.service` 重启docker服务的
