### ISSUE TITLE
Want C++ API Document

### ISSUE THREAD

**Issue by khw934** [milvus-io/milvus#4337]
**Please state your issue using the following template and, most importantly, in English.**

**Location of incorrect documentation**
Provide links and line numbers if applicable.

**Describe the problems or issues found in the documentation**
A clear and concise description of what you found to be incorrect.

**Steps taken to verify documentation is incorrect**
List any steps you have taken:

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.

---

## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken:

是否可以提供c++ 的API 文档

**Comment by shengjun1985** [comment]
We think the comments on the API header are clear enough.
And there are also sample codes to help users.
So we are not going to provide another document.

Please refer to [MilvusApi.h](https://github.com/milvus-io/milvus/blob/0.11.1/sdk/include/MilvusApi.h).
If you have any questions, you are welcome to communicate in the community.
