### ISSUE TITLE
Compile error in C++ SDK example

### ISSUE THREAD

**Issue by khw934** [milvus-io/milvus#4338]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
![image](https://user-images.githubusercontent.com/35864027/100723311-920c8000-33fc-11eb-8478-6728e196afc2.png)

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by shengjun1985** [comment]
Excuse me, which version did you use?
C++ sdk_binary is fixed in 0.11.1 (issue #4329), and I will cherry-pick the fix to master as soon as possible (PR #4331).

**Comment by shengjun1985** [comment]
PR 4331 is merged. Please try again.

**Comment by shengjun1985** [comment]
Done.
