### ISSUE TITLE
[C++ SDK] Error message returned when CreateCollection

### ISSUE THREAD

**Issue by khw934** [milvus-io/milvus#4346]
![image](https://user-images.githubusercontent.com/35864027/100822837-122ef600-348e-11eb-9731-9b7259e86923.png)

版本是  10.0

代码如下：
// 创建集合
	milvus::FieldPtr field1 = std::make_shared<milvus::Field>("face_id", milvus::DataType::INT32, "");
	milvus::FieldPtr field2 = std::make_shared<milvus::Field>("duration", milvus::DataType::INT32, "");
	nlohmann::json vector_param = {{"dim", COLLECTION_DIMENSION}};
	milvus::FieldPtr field3 = std::make_shared<milvus::Field>("embedding", milvus::DataType::VECTOR_FLOAT, vector_param.dump());
	nlohmann::json json_param;
	json_param = {{"auto_id", false}, {"segment_row_limit", 4096}};
	milvus::Mapping mapping = {table_name.c_str(), {field1, field2, field3}, json_param.dump()};

	milvus::Status status = conn_->CreateCollection(mapping);
	std::cout << "CreateCollection function call status: " << status.message() << std::endl;

**Comment by fishpenguin** [comment]
Can you run sdk_simple?

**Comment by khw934** [comment]
yes
Running the example is the same error

**Comment by khw934** [comment]
> Can you run sdk_simple?

Yes，Running the example is the same error

**Comment by khw934** [comment]
> > Can you run sdk_simple?
> 
> Yes，Running the example is the same error

The version used is 10.0

**Comment by fishpenguin** [comment]
In milvus-0.10.0, Scalar field is not supported.
I see the sdk you used is 0.11.0.

**Comment by khw934** [comment]
> In milvus-0.10.0, Scalar field is not supported. However, I see the sdk you used is 0.11.0 version.

It should be version 11.0. Please check the reason

**Comment by fishpenguin** [comment]
I can run the sdk_simple in native. The reason of the bug seems to be that your collection dimension is not right. I cannot reproduce the bug. Please check your client and server version.

**Comment by scsven** [comment]
Not active, close.
