### ISSUE TITLE
We need a tool which can show the progress of creating index

### ISSUE THREAD

**Issue by yu-hailong** [milvus-io/milvus#4347]
**Please state your issue using the following template and, most importantly, in English.**

**What would you like to be added ?**
a tool  or  methord which can show the progress of creating index.

**Why is this needed ?**
When we create index for large data, it will cost long time.
And we don't know  the approximate finish time .
So we think the approximate finish time and current progress are prefer.

**Comment by shengjun1985** [comment]
When Milvus building index in the background, the IF GetCollectionInfo() can show which segments are finished.
Python and Java SDK provide the async IF, while other SDK has not provided.
However, there is no way to show the progress in a segmnet inner now.
