### ISSUE TITLE
我们公司有这样一个需求,模型可能会迭代更新,那么我可以定时将数据库中存储的特征值update同步一下,但是milvus中已经插入的特征值怎么同步更新,我没有找到go的update或者修改feature操作,难道删除milvus数据重新插入么?

### ISSUE THREAD

**Issue by yuanpengpeng** [milvus-io/milvus#4351]
我们公司有这样一个需求,模型可能会迭代更新,那么我可以定时将数据库中存储的特征值update同步一下,但是milvus中已经插入的特征值怎么同步更新,我没有找到go的update或者修改feature操作,难道删除milvus数据重新插入么?

**Comment by fishpenguin** [comment]
Milvus doesn't have update interface currently, you can use DeleteByID+Insert to realize update.

**Comment by sahuang** [comment]
Moved discussion to https://github.com/milvus-io/milvus/discussions/4350
