### ISSUE TITLE
In 0.10.3, while we try to return topk = 10K , error message return and prompt us that the topk is too large

### ISSUE THREAD

**Issue by yu-hailong** [milvus-io/milvus#4352]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
In 0.10.3, while we try to return topk = 1000, error message return and prompt us that the topk is too large.
The following is the error message ：
![image](https://user-images.githubusercontent.com/17443614/100843302-20dcd380-34b5-11eb-8ce1-0ab91a57f8bb.png)

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

we are told ， topk <= 16348 is supported.
![image](https://user-images.githubusercontent.com/17443614/100843453-5681bc80-34b5-11eb-8d0d-6c6330727454.png)

**Method of installation**
- [ X ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
0.10.3

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by sahuang** [comment]
Can you provide the last commit id in `docker logs`? In 0.10.3 the `topK` limit has already been raised to 16384.

**Comment by shengjun1985** [comment]
If you still have questions, please continue to contact our community.
