### ISSUE TITLE
[c++ sdk]Id can still be searched after deletion

### ISSUE THREAD

**Issue by vvoidon** [milvus-io/milvus#4357]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Using the demo in sdk/examples/simple, after deleting a single id by 'DeleteByIds', the id can still be found through 'SearchEntities', but the 'entities' in 'topk_query_result' is empty.

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [x] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)
OS:Ubuntu 20.04.1 LTS
CPU:Intel® Core™ i5-9300H CPU @ 2.40GHz × 8 
GPU:NVIDIA Corporation TU117M [GeForce GTX 1650 Mobile / Max-Q] / GeForce GTX 1650/PCIe/SSE2
Memory:7.6 GiB

- Milvus version (master or released version)
0.11.0

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**
![Screenshot from 2020-12-02 20-32-48](https://user-images.githubusercontent.com/26303309/100873350-18e55980-34de-11eb-8b17-f4702c1f2ff2.png)
![Screenshot from 2020-12-02 20-31-56](https://user-images.githubusercontent.com/26303309/100873372-1e42a400-34de-11eb-847c-199dfdc1a440.png)
![Screenshot from 2020-12-02 20-33-14](https://user-images.githubusercontent.com/26303309/100873377-20a4fe00-34de-11eb-952e-f47f11e8e11d.png)

**Additional context**

**Comment by fishpenguin** [comment]
Did you use 0.11.0 milvus server and 0.11.1 C++ sdk?

**Comment by vvoidon** [comment]
> Did you use 0.11.0 milvus server and 0.11.1 C++ sdk?

Thanks for your reply.
I've got the same result when using 0.11.0 C++ sdk.
it seems the same problem as #4200 
I try to update the server version to the newest, it works!
