### ISSUE TITLE
when search ,met the error: "Error: <BaseException: (code=5, message=DSL vector query field name: title_embedding is wrong)>"

### ISSUE THREAD

**Issue by joytode** [milvus-io/milvus#4358]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
using milvus 0.11 docker gpu version, with python client pymilvus 0.3,
search following query:
```python
query_hybrid = {
    "bool": {
        "must": [
            {
                "term": {"date": [1552060800]}
            },
            {
                "vector": {
                    "title_embedding": {"topk": 3, "query": [query_embedding], "metric_type": "L2"}
                }
            }
        ]
    }
}

results = client.search(collection_name, query_hybrid, fields=["date","title_embedding"])
```

Error: <BaseException: (code=5, message=DSL vector query field name: title_embedding is wrong)>
ERROR:milvus.client.grpc_handler:Error: <BaseException: (code=5, message=DSL vector query field name: title_embedding is wrong)>

when invoked get_collection_info api:
```python
info = client.get_collection_info(collection_name)
pprint(info)

{'auto_id': False,
 'fields': [{'indexes': [{'index_type': 'IVF_FLAT',
                          'metric_type': 'L2',
                          'params': {'nlist': 1000}}],
             'name': 'desc_embedding',
             'params': {'dim': 768},
             'type': <DataType.FLOAT_VECTOR: 101>},
            {'indexes': [{'index_type': 'SORTED'}],
             'name': 'date',
             'params': {},
             'type': <DataType.INT32: 4>},
            {'indexes': [{'index_type': 'IVF_FLAT',
                          'metric_type': 'L2',
                          'params': {'nlist': 1000}}],
             'name': 'title_embedding',
             'params': {'dim': 768},
             'type': <DataType.FLOAT_VECTOR: 101>}],
 'segment_row_limit': 4096}
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ x] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)
ubuntu 

- Milvus version (master or released version)
0.11

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by sahuang** [comment]
You have two vector fields in your collection, `desc_embedding` and `title_embedding`. Currently, Milvus only supports one vector field, therefore querying on the other may raise error in v0.11.0.
