### ISSUE TITLE
Question about index file size

### ISSUE THREAD

**Issue by qihaoxiansheng** [milvus-io/milvus#4369]
My problem about index file size. 
Yesterday,I inserted 10000 features to milvus container,which size is 78.125MB,and my index way is IVF_FLAT way. After inserting features,I found .idx file size of the db catalog only  had 1.4MB. I want to know why it is not 78.125MB ?

**Comment by shengjun1985** [comment]
We have optimized the storage method of IVF_FLAT in v0.11.0, and the original vector is no longer stored in the index file.

**Comment by qihaoxiansheng** [comment]
Using IVF_SQ8 method,original vector will be save in the index file?

**Comment by qihaoxiansheng** [comment]
In addition, I want to know why it has been changed to this way. Is there any improvement in performance?

**Comment by shengjun1985** [comment]
> Using IVF_SQ8 method,original vector will be save in the index file?

The storage of IVF_SQ8 is not changed.

> In addition, I want to know why it has been changed to this way. Is there any improvement in performance?

It does not affect query performance.
It only reduces disk usage.

**Comment by qihaoxiansheng** [comment]
Ok, thank you!
