### ISSUE TITLE
Multi-threads to call load_collection() and search() cause Milvus hang

### ISSUE THREAD

**Issue by jhd900518** [milvus-io/milvus#4378]
50个线程，并发调用特征检索，500ms超时时间，超时会中断线程，然后会出现连接不上，错误日志如下[2020-12-04 19:14:33,200][ERROR][SERVER][ReScheduleQueue][grpcpp_sync_ser] unsupported request type for search strategy

**Comment by fishpenguin** [comment]
Can you put your debug.log here?

**Comment by jhd900518** [comment]
代码如下：
 ListenableFuture<SearchResponse> searchResponseFuture = this.getClient().searchAsync(searchParam);
        try {
            return searchResponseFuture.get(2, TimeUnit.SECONDS);
        } catch (Exception e) {
            log.info("milvus earch error:{}", e.getMessage());
            return new SearchResponse();
        }
运行半小时后，会出现上诉问题

**Comment by jhd900518** [comment]
The log is as follows:
2020-12-05 16:04:25.003  INFO 476 --- [io-7500-exec-29] c.o.commons.milvus.MilvusDataSource      : milvus earch error:Waited 2 seconds for com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture@65fcd39a[status=PENDING, info=[inputFuture=[io.grpc.stub.ClientCalls$GrpcFuture@476158d1[status=PENDING, info=[GrpcFuture{clientCall=ClientCallImpl{method=MethodDescriptor{fullMethodName=milvus.grpc.MilvusService/Search, type=UNARY, idempotent=false, safe=false, sampledToLocalTracing=true, requestMarshaller=io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@1e52813d, responseMarshaller=io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@b539855, schemaDescriptor=io.milvus.grpc.MilvusServiceGrpc$MilvusServiceMethodDescriptorSupplier@3169b1d8}}}]]], function=[io.milvus.client.MilvusGrpcClient$$Lambda$727/1216404341@56cbf66f]]]

**Comment by jhd900518** [comment]
详细debug日志已发送到邮箱，谢谢

**Comment by fishpenguin** [comment]
Debug.log received.
Can you print your java sdk console error output here?

**Comment by fishpenguin** [comment]
You said when timeout it could not connect to server, in this circumstance, is a new thread be able to connect to milvus server?

**Comment by jhd900518** [comment]
sdk console log:

2020-12-05 16:04:25.003  INFO 476 --- [io-7500-exec-29] c.o.commons.milvus.MilvusDataSource      : milvus earch error:Waited 2 seconds for com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture@65fcd39a[status=PENDING, info=[inputFuture=[io.grpc.stub.ClientCalls$GrpcFuture@476158d1[status=PENDING, info=[GrpcFuture{clientCall=ClientCallImpl{method=MethodDescriptor{fullMethodName=milvus.grpc.MilvusService/Search, type=UNARY, idempotent=false, safe=false, sampledToLocalTracing=true, requestMarshaller=io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@1e52813d, responseMarshaller=io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@b539855, schemaDescriptor=io.milvus.grpc.MilvusServiceGrpc$MilvusServiceMethodDescriptorSupplier@3169b1d8}}}]]], function=[io.milvus.client.MilvusGrpcClient$$Lambda$727/1216404341@56cbf66f]]]

用你们的网页客户端是可以连接到的，但是用java sdk客户端连接会超时，调用检索接口会报上面那个错

**Comment by sahuang** [comment]
> c.o.commons.milvus.MilvusDataSource : milvus earch error

This does not seem to be an error message either from Java SDK or Milvus server. SDK only prints client-side or server-side error. 

> Waited 2 seconds for com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture

This seems to be caused by network issues, according to my [research](https://stackoverflow.com/questions/54626978/build-failed-waited-30-seconds-for-com-google-common-util-concurrent-settablef). Did you turn on firewall during connecting to Milvus? Other than search, are other APIs causing similar issues? (e.g. connect to Milvus, create collection etc.)

**Comment by jhd900518** [comment]
如你所说，创建库等api是可以使用的，只有检索这个api是会报错的，但是我们的防火墙和selinux都是默认关闭的，只有重启docker容器才能恢复检索api，我提供一下我们的milvus配置文件，请帮我们查看下配置文件是否有问题di

**Comment by fishpenguin** [comment]
We have reproduced this bug. It is a milvus server bug which may occur when you call preload and search next. So it is not recommend that in milvus-0.10.1 you call preload and search frequently.
We will fixed this bug later in milvus-0.10.5.

**Comment by yhmo** [comment]
It is a bug of search combine strategy. In certain condition, search request was not put into request queue to execute, client will be time out.
Script to reproduce this issue:

```
import time
import threading

import numpy as np
from milvus import Milvus, IndexType
from milvus.client.types import MetricType

SERVER_ADDR = "127.0.0.1"
SERVER_PORT = '19530'

COLLECTION_DIMENSION = 128
COLLECTION_NAME = "TEST"

INDEX_TYPE = IndexType.IVF_SQ8
INDEX_PARAM = {'nlist': 2048}
SEARCH_PARAM = {'nprobe': 16}
TOPK = 10

MILVUS = Milvus(host=SERVER_ADDR, port=SERVER_PORT)

def gen_vec_list(nb, seed=np.random.RandomState(1234)):
    xb = seed.rand(nb, COLLECTION_DIMENSION).astype("float32")
    vec_list = xb.tolist()
    return vec_list

def create_collection():
    status = MILVUS.drop_collection(collection_name=COLLECTION_NAME)
    time.sleep(2)
    tb_param = {'collection_name': COLLECTION_NAME, 'dimension': COLLECTION_DIMENSION, 'index_file_size': 1024,
                'metric_type': MetricType.L2}
    status = MILVUS.create_collection(tb_param)
    print('create collection', status)

def load_collection():
    status = MILVUS.load_collection(collection_name=COLLECTION_NAME)
    print('load collection', status)

def insert():
    for i in range(1):
        vec_list = gen_vec_list(10000, seed=np.random.RandomState(i+11))
        status, result = MILVUS.insert(collection_name=COLLECTION_NAME, records=vec_list)
        print('insert No.' + str(i), status)
    status = MILVUS.flush(collection_name=COLLECTION_NAME)
    print('insert done')

def create_index():
    status = MILVUS.create_index(collection_name=COLLECTION_NAME, index_type=INDEX_TYPE, params=INDEX_PARAM)
    print('create index', status)

def search(tag):
    # time_start = time.time()
    for i in range(100000):
        vec_list = gen_vec_list(1, seed=np.random.RandomState(i))
        MILVUS.load_collection(collection_name=COLLECTION_NAME)
        status, result = MILVUS.search(collection_name=COLLECTION_NAME, top_k=TOPK,
                                       query_records=vec_list, params=SEARCH_PARAM)

        if i%10 == 0:
            print('No.' + str(tag), i, 'done')
    # time_end = time.time()
    # total_cost = time_end - time_start
    # print('search No.' + str(tag), total_cost, 'sec', status)

def multi_search():
    time_start = time.time()
    SEARCH_COUNT = 50
    threads = []
    for k in range(SEARCH_COUNT):
        # search(tag=k, vec_list=vec_list)

        x = threading.Thread(target=search, args=(k,))
        threads.append(x)
        x.start()

    for th in threads:
        th.join()

    time_end = time.time()
    total_cost = time_end - time_start
    print("search total cost", total_cost, 'sec')
    print('QPS = ', SEARCH_COUNT/total_cost)


if __name__ == "__main__":
    create_collection()
    insert()
    # create_index()
    load_collection()
    multi_search()
```

**Comment by yhmo** [comment]
Multi-threads to call load_collection(), get_entity_by_id() and search() could lead to this problem.
We will fix this in 0.10.5. Before we fix it, you can remove the call of load_collection() to avoid this problem.

**Comment by jhd900518** [comment]
我想问一下，0.10.5发布的大概时间?我们到时候升级就可以了吗？

**Comment by yhmo** [comment]
Typically the interval of each version is about 2~3 weeks. We just public 0.10.4.
For 0.10.0 to 0.10.x, the data is fully compatible, sdk may has minor change. Upgrade is easy, data can be reused, just stop old container, start a new version container, update sdk.

**Comment by jhd900518** [comment]
好吧，谢谢

**Comment by yhmo** [comment]
pr4408 will fix this issue in 0.10.5

**Comment by del-zhenwu** [comment]
will close after 0.10.5 released

**Comment by del-zhenwu** [comment]
not reproduced currently

**Comment by yhmo** [comment]
Run the script whole night, milvus crash at src/scheduler/action/PushTaskToNeighbour.cpp within this function: Action::SpecifiedResourceLabelTaskScheduler()

**Comment by yhmo** [comment]
#4563 fix the random crash issue.
