### ISSUE TITLE
Using SDK with JDK 8 throws java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer

### ISSUE THREAD

**Issue by deil87** [milvus-io/milvus#4379]
**Describe the bug**
I'm using 0.9.1 version of the milvus-sdk-java and JDK 8u271.

I'm receiving a following error:  java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer
Error is thrown from SearchParam.toBinaryVectorRecord method's scope at line `bytes.flip();`

**Steps/Code to reproduce behavior**
```val dsl =
      s"""
          {"bool": {
            "must": [
                {
                "vector": {
                    "embedding": {
                        "topk": ${topK}, "metric_type": "JACCARD", "type": "binary", "query": ${queriesAsArr}
                    }
                  }
                }
            ]
          }
          }
        """

val searchParam = SearchParam.create(collectionName).setDsl(dsl)
```
**Expected behavior**
No exception is expected.  Tried to run with Java 11 and it worked. It looks like it was build with Java11 as a target version even though I can see 1.8 version in pom file here https://github.com/milvus-io/milvus-sdk-java/blob/master/pom.xml

**Method of installation**
- [ x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
irrelevant

- Milvus version (master or released version)
milvus_cpu_0.11.0

**Configuration file**
default

**Screenshots**
![image](https://user-images.githubusercontent.com/1162131/101178764-adb89600-3649-11eb-838f-00e32fd5cf9f.png)

**Additional context**
Related post on the Internet:
https://stackoverflow.com/a/61267496/1020472
https://github.com/nemtech/symbol-sdk-java/issues/213

**Comment by sahuang** [comment]
Please refer to https://github.com/milvus-io/milvus/discussions/4270 for more information.

Using JDK 11 will solve this issue.

**Comment by deil87** [comment]
@sahuang I see, thank you for a quick reply!
 Maybe it is worth to improve docs a bit here https://github.com/milvus-io/milvus-sdk-java as it says in `Prerequisites` section that it is Java 8 and higher. Maybe it would be better to add column to the table with Java SDK versions for Milvus with corresponding supported Java JRE versions?

**Comment by sahuang** [comment]
You are right, I think the documentation needs to be fixed.

I will update the prerequisite to Java 9 and above for SDK v0.9.x.

Thanks for the comment!

**Comment by sahuang** [comment]
This is already fixed. Thanks again for the contribution.

**Comment by deil87** [comment]
@sahuang shouldn't pom has different target then?
```<maven.compiler.target>1.8</maven.compiler.target>``` 
to 
``` <maven.compiler.target>1.9</maven.compiler.target>```

**Comment by sahuang** [comment]
True, I will update soon.

Actually for the upcoming Java SDK 0.9.2 (corresponding to Milvus v0.11.1), Java 8 will be supported again and there's no need to use Java 9+.

**Comment by deil87** [comment]
@sahuang I'm so glad that I have added this comment! Otherwise I would not know about that piece of information and it is   quite valuable for us. 

May I ask when should we expect Milvus 0.11.1 and corresponding SDK 0.9.2? Actually I can see on Readme page that 0.9.2 is already out. Does it support Java 8 already? Is it compatible with Milvus 0.11.0?
I actually tried to downgrade to Milvus 0.10.4 and SDK 0.8.5 but SDK's API is quite different. In case we need to wait for 0.11.1 release for a long time could you please suggest where can I find documentation/examples/unit tests for 0.8.5 version?

Thank you! We are so excited to use Milvus!

**Comment by sahuang** [comment]
Typically versions will be released every 2-4 weeks, so I guess in a month it would be out.

0.9.2 has not released Maven official version, it was just the codebase. It will support Milvus v0.11.0 and Java 8. In fact, only binary vector search requires Java 9+ for 0.9.1 because of some compatibility issues.

**Comment by deil87** [comment]
@sahuang Thank you for the extra details! May I ask you to invite me to your Slack? 

We wanted to ask about scalability of the Milvus. Currently I can see on the Release notes that Milvus v0.11.0 does not support Mishards:
```
 `v0.11.0 Milvus does not support the Mishards clustering solution.`
```
Is support for Mishards going to be back in v.0.11.1?  What is a recommended approach for scaling now?

**Comment by sahuang** [comment]
We have slack channel on the official website that you can join and ask questions.

For Mishards, I think you can open a separate issue because it is unrelated to this post :d
