### ISSUE TITLE
The read-write node should start failed with sqlite meta-uri config

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#4383]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Because the sqlite meta data can't be shared, so the node should not be started with sqlite meta-uri config in read-write separation mode.

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 -- master

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
general:
  timezone: UTC+8
  meta_uri: sqlite://:@:/
```

**Screenshots**

**Additional context**

**Comment by XuPeng-SH** [comment]
@ThreadDao @JinHai-CN @del-zhenwu,
The Sqlite metadata can be shared by one process of rw privilege with other processes of ro privilege. We should not restrict the users not to use sqlite as metadata engine.

**Comment by XuPeng-SH** [comment]
close it. SQLite could be used in a read-write separation solution.
