### ISSUE TITLE
Adding Fields DataTypes : Date

### ISSUE THREAD

**Issue by keotic** [milvus-io/milvus#4388]
A Date DataType for a field will enable query filtering by time ranges.
Can be implemented by over the INT64 field by a wrapper that handles the different DateTime formats and translates them to epoch time.

**Comment by denissabramovs** [comment]
Bump! I think this is important feature. Filtering scope of vectors for similarity search will be super useful.

**Comment by denissabramovs** [comment]
Adding some simple index for unix timestamps, to improve performance, would be a nice feature as well.
