### ISSUE TITLE
Build Milvus on ARM

### ISSUE THREAD

**Issue by yuanpengpeng** [milvus-io/milvus#4391]
milvus如何编译arm镜像,官方有已经打包好的arm镜像么,直接pull下来?

**Comment by shengjun1985** [comment]
I am sorry that Milvus had not supported ARM after version 0.6.0.
There is only a branch 'aarch64' which is based on 0.6.0 and can be built locally.

**Comment by yuanpengpeng** [comment]
0.10.3是否可以支持自己编译arm镜像,通过DockerFile ,我看cpu/centos/Dockfile有这个dockerfile,自己在ubuntu下面能编译一个arm镜像的么,将ubuntu源替换为arm架构的ubuntu

**Comment by scsven** [comment]
@yuanpengpeng If you want to get a Milvus docker image works on ARM, you may do somethings below:
1. Install all dependencies on ARM, which is listed in `core/ubuntu_build_deps.sh`;
2. Makes a `core/src/index/thirdparty/faiss` build on ARM;
3. Build Milvus on ARM;
4. Build the Milvus image;

You can refer to [this](https://github.com/milvus-io/milvus/commit/651b1224ae293262782b3e4a29418952baa135e9) where you need to modify the code.

**Comment by scsven** [comment]
@yuanpengpeng Faiss will be automatically compiled during the Milvus compilation process. So you don’t need to prepare a faiss image.

**Comment by scsven** [comment]
Not active, close.
