### ISSUE TITLE
The interval of read-only node load metadata from meta-store should be configurable

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#4397]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
The document says “The read-only node periodically load metadata from meta-store”,  but how long?
Now, the problem is that entities were inserted on the writable node but can't find out on the read-only node, 
and the collection was created on the writable node but exception `<BaseException: (code=4, message=Collection not exist: test_3d3uEoAI)>` throw

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 --master

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by XuPeng-SH** [comment]
@ThreadDao The interval can be configured by the env variable.
