### ISSUE TITLE
Why modify interfaces in faiss about new feature(support scalar filtering), why not add interfaces 

### ISSUE THREAD

**Issue by chenqingguo** [milvus-io/milvus#4402]
**Please state your issue using the following template and, most importantly, in English.**

**What would you like to be added ?**

**Why is this needed ?**

**Comment by chenqingguo** [comment]
The filter will be judged for each search, regardless of whether the user needs to filter. That may be slower than original search. 
So why not adding a search just focuses on filter search, and reserve original search method of faiss.

**Comment by shengjun1985** [comment]
Not to add new interfaces can avoid a lot of duplicate code and make the modification easier.
In addition, we allow the default parameter nullptr to ensure that the original call will still work.
Finally, the compiler ensures that they perform the same without filtering.

**Comment by chenqingguo** [comment]
Although you set default parameter nullptr, there are extra judges in the loop.
Anyway,"有得必有失".
I got yours design,Thanks.
