### ISSUE TITLE
Question about preloading collection. 

### ISSUE THREAD

**Issue by qihaoxiansheng** [milvus-io/milvus#4403]
After preloading many collections, the data is reloaded into memory when the container is restarted. With the data of increasing, the total amount of data will exceed the memory, and then the memory will burst. Is there some way to remove the pre loaded data?

**Comment by yhmo** [comment]
load_collection() internally do these things:
1. get segments information of this collection
2. read segment file one by one into cache
3. once the cache is full, stop loading

This is an example:
- Assume we have 2 collections "A" and "B".  
- "A" has 10 segments, each segment file is 1GB. "B" has 10 segments, each segment file is 2GB.
- Assume cache size set to 20GB

Now we call load_collection("A") to load "A", the 10 segments of "A" are read into cache, occupy 10GB memory, 50% of cache size.
Then we call load_collection("B") to load "B", milvus load 5 segments of "B" into cache, 5*2=10GB, now the cache is full. The load_collection() will return, the other 5 segments will not be loaded.

**Comment by yhmo** [comment]
Currently no api to purge data from cache. The search() api can force load collection data into cache. Call search() for "B", milvus will load all segments of "B" into cache, and purge "A" from cache.

**Comment by chenliyan** [comment]
> Currently no api to purge data from cache. The search() api can force to load collection data into cache. Call search() for "B", milvus will load all segments of "B" into cache, and purge "A" from cache.

In cluster mode, If I inserted in write node, then search the in readonly node, will the readonly node reload segments files in every search?

**Comment by yhmo** [comment]
Read node also has its cache, it only load segment files at the first time to query (make sure the cache larger than data).

**Comment by shengjun1985** [comment]
Answered.

**Comment by ArijitSinghEDA** [comment]
@yhmo Is there a method now to purge data from cache? I am using milvus 2,2,6
