### ISSUE TITLE
100m custom Vec data insertion result in milvus server terminated

### ISSUE THREAD

**Issue by douglarek** [milvus-io/milvus#4404]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
I want to test scalar index performance in mixed queries, and I wrote a go program(with milvus go-sdk) to import 100m custom Vec data. I created index when insertion ended, but milvus server was terminated automatically.

**Steps/Code to reproduce behavior**
1. start milvus server with my custom [milvus.yaml](https://gist.githubusercontent.com/douglarek/fbe209f31f36ed52c22f5970a50577b9/raw/43bc75411c2b52790b66ada367bbcf0770d18e84/milvus.yaml);
2. run my [go program](https://gist.githubusercontent.com/douglarek/fbe209f31f36ed52c22f5970a50577b9/raw/43bc75411c2b52790b66ada367bbcf0770d18e84/main.go);
3. observe milvus server active status

**Expected behavior**
milvus server could create index and be not  terminated automatically.

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)
Aliyun ECS 16C, 32G, 256G HDD

- Milvus version (master or released version)
0.11.0-cpu-d101620-4c44c0

**Configuration file**
https://gist.githubusercontent.com/douglarek/fbe209f31f36ed52c22f5970a50577b9/raw/43bc75411c2b52790b66ada367bbcf0770d18e84/milvus.yaml

**Screenshots**

my go program error occurred when created index:
```
2020/12/08 12:45:20 rpc error: code = Unavailable desc = transport is closing
```
I checked milvus server logs/xxx-error.log and docker logs , nothing found.
**Additional context**
All files needed: https://gist.github.com/douglarek/fbe209f31f36ed52c22f5970a50577b9

**Comment by fishpenguin** [comment]
Can you put your debug.log, info.log and error.log here?

**Comment by douglarek** [comment]
OK, please wait , I will upload it to my personal onedrive since so large.

**Comment by douglarek** [comment]
Log is here: https://1drv.ms/u/s!Agcd0X-LI-7UvFkDhrEAEZ6AcTnf?e=4KC0HN

**Comment by fishpenguin** [comment]
Is there any stacktrace info when milvus server crashed?

**Comment by douglarek** [comment]
> Is there any stacktrace info when milvus server crashed?

no

**Comment by fishpenguin** [comment]
We analysis the debug.log and find that when milvus server terminated. And we think it is because of some memory issue that milvus server memory growed to the system memory and cause that system killed the milvus process.
We are keeping find out the memory issue.

**Comment by fishpenguin** [comment]
We will add some memory related logs in milvus server. So if you do some operations related to large sum of data later, please pay attention to the memory of milvus used.

**Comment by scsven** [comment]
Not active, close.
