### ISSUE TITLE
Faiss assertion'err == cudaSuccess' failed in void faiss:: gpu::freeMemorySpace(faiss::gpu::MemorySpace, void*) at gpu/utils/MemorySpace.cpp:72; details: Failed to cudaFree pointer 0x7fc514000000 (error 1 invalid argument

### ISSUE THREAD

**Issue by xuyufeng1995** [milvus-io/milvus#4412]
I tested the code in benchmark0.11.0 three times and he exposed a bug.

When setting up the collection, I set the segment_row_limit parameter to 150w and the parameter to 100w, and insert the 118w vector data into milvus. Due to the milvus restriction that each insertion must not exceed 256M, I divided it into multiple insertions, each insertion was 2w, when the insertion was about 110w, the milvus service shut down, the log was Faiss assertion'err == cudaSuccess' failed in void faiss:: gpu::freeMemorySpace(faiss::gpu::MemorySpace, void*) at gpu/utils/MemorySpace.cpp:72; details: Failed to cudaFree pointer 0x7fc514000000 (error 1 invalid argument)
The second time I set the segment_row_limit parameter to 150w, the same operation was performed in the previous step, this time no error was reported. So I added the 118w vector again. When it was inserted to about 160w, the milvus service shut down and the log was the same as the previous one.
For the third time, I set the segment_row_limit parameter to 400w, and also inserted 226w data into milvus without any problems.
So I think the segment_row_limit directly determines the size of the database, so this problem should be a bug
milvus version:0.11.0
code: https://github.com/milvus-io/bootcamp/tree/0.11.0/benchmark_test/scripts

**Comment by xuyufeng1995** [comment]
I tested the code in benchmark0.11.0 three times and he exposed a bug.

         1、When setting up the collection, I set the segment_row_limit parameter to 150w and the parameter to 100w, and insert the 118w vector data into milvus. Due to the milvus restriction that each insertion must not exceed 256M, I divided it into multiple insertions, each insertion was 2w, when the insertion was about 110w, the milvus service shut down, the log was Faiss assertion'err == cudaSuccess' failed in void faiss:: gpu::freeMemorySpace(faiss::gpu::MemorySpace, void*) at gpu/utils/MemorySpace.cpp:72; details: Failed to cudaFree pointer 0x7fc514000000 (error 1 invalid argument)
          2、The second time I set the segment_row_limit parameter to 150w, the same operation was performed in the previous step, this time no error was reported. So I added the 118w vector again. When it was inserted to about 160w, the milvus service shut down and the log was the same as the previous one.
          3、For the third time, I set the segment_row_limit parameter to 400w, and also inserted 226w data into milvus without any problems.

So I think the segment_row_limit directly determines the size of the database, so this problem should be a bug

milvus version:0.11.0
code: https://github.com/milvus-io/bootcamp/tree/0.11.0/benchmark_test/scripts

**Comment by shengjun1985** [comment]
https://github.com/milvus-io/milvus/issues/3646#issuecomment-696484340

It is a common issue when out of GPU memory.

**Comment by shengjun1985** [comment]
@xuyufeng1995 
How about the size of your GPU memory?

**Comment by yhmo** [comment]
The benchmark test steps:
```
python main.py --collection <collection_name> -c
python main.py --collection <collection_name> --index <index_type> --build
python main.py --collection <collection_name> --load
```
It firstly create a collection, then specify an index type, and load data.
Because the index type is specified, once a segment's row count exceed "segment_row_limit", milvus will build index for this segment. Otherwise, small segments will be merged to large segment until the segment row count exceed "segment_row_limit".
If the config(milvus.yaml) allow gpu to build index, milvus will copy segment data into GPU memory, if the segment size is too large, you may get gpu memory error.

Please check your milvus.yaml to see if the gpu build index is enabled:
```
gpu:
  enable: true
  cache_size: 1GB
  gpu_search_threshold: 1000
  search_devices:
    - gpu0
  build_index_devices:
    - gpu0
```

How many dimensions of you vector?

**Comment by shengjun1985** [comment]
If you have more questions, please continue to contact our community.
