### ISSUE TITLE
"Query fail: index is null"   in read-only node

### ISSUE THREAD

**Issue by houhou2021** [milvus-io/milvus#4415]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
When performing vector query, the read-only node often has an exception that fail to open vector index xxx , which makes it impossible to query some vectors that must exist. 

Error follows:
``` 
[ERROR][ENGINE][read_internal][taskloader_th] Fail to open vector index: /var/lib/milvus/db/tables/index/1607414317228500000/1607414317228500000
[ERROR][ENGINE][Load][taskloader_th] Failed to load index from /var/lib/milvus/db/tables/index/1607414317228500000/1607414317228500000
[ERROR][ENGINE][Search][taskexecutor_th] [search][0] ExecutionEngineImpl: index is null, failed to search
[ERROR][SERVER][OnExecute][reqsched_thread] [search][0] Query fail: index is null
[ERROR][SERVER][TakeToExecute][reqsched_thread] Request failed with code: Error: index is null

```

After opening the debug log, it is found that the segment is merged, as follows:

```
[DEBUG][ENGINE][Serialize][wal_thread] New raw file 1607414317228500000 of size 2080768 bytes, lsn = 1241294287595
[DEBUG][ENGINE][Serialize][wal_thread] Flushed segment 1607414317228500000
[DEBUG][ENGINE][UpdateCollectionFiles][wal_thread] UpdateCollectionFiles: UPDATE TableFiles SET table_id = 'index' ,engine_type = 3 ,file_id = '1607414317228500000' ,file_type = 1 ,file_size = 2082800 ,row_count = 254 ,updated_time = 1607414347111849 ,created_on = 1607414317228506 ,date = 1201108 WHERE id = 546124;
[DEBUG][ENGINE][MarkOngoingFileNoLock][milvus_server] Mark ongoing file:1607414317228500000 refcount:1
[DEBUG][ENGINE][UnmarkOngoingFileNoLock][milvus_server] Unmark ongoing file:1607414317228500000 refcount:0
[DEBUG][ENGINE][MarkOngoingFileNoLock][milvus_server] Mark ongoing file:1607414317228500000 refcount:1
[DEBUG][ENGINE][Merge][milvus_server] Merging from /var/lib/milvus/db/tables/index/1607414317228500000 to /var/lib/milvus/db/tables/index/1607414377123740000
[DEBUG][ENGINE][Merge][milvus_server] Merging completed from /var/lib/milvus/db/tables/index/1607414317228500000 to /var/lib/milvus/db/tables/index/1607414377123740000
[DEBUG][ENGINE][UpdateCollectionFiles][milvus_server] UpdateCollectionFiles: UPDATE TableFiles SET table_id = 'index' ,engine_type = 3 ,file_id = '1607414317228500000' ,file_type = 4 ,file_size = 2082800 ,row_count = 254 ,updated_time = 1607414377134561 ,created_on = 1607414317228506 ,date = 1201108 WHERE id = 546124;
[DEBUG][ENGINE][UnmarkOngoingFileNoLock][milvus_server] Unmark ongoing file:1607414317228500000 refcount:0
[DEBUG][ENGINE][CleanUpFilesWithTTL][milvus_server] Remove file id:546124 location:/var/lib/milvus/db/tables/index/1607414317228500000/1607414317228500000
[DEBUG][ENGINE][CleanUpFilesWithTTL][milvus_server] CleanUpFilesWithTTL: SELECT id FROM TableFiles WHERE segment_id = '1607414317228500000';
[DEBUG][ENGINE][CleanUpFilesWithTTL][milvus_server] Remove segment directory: /var/lib/milvus/db/tables/index/1607414317228500000
```

`Note: The access failure occurs before the file is removed`

My index_file_size is configured to 2048, and the size of the file involved in the merge is only 2082800 byte , and the index file has not been generated yet, but why do I still access a non-existent file during query?

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
0.10.3

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
storage:
  auto_flush_interval: 30
```

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
Could you tell us how do you deploy milvus? How many nodes deployed?

**Comment by houhou2021** [comment]
> Could you tell us how do you deploy milvus? How many nodes deployed?

Using mishards, the cluster has two nodes sharing data through nfs

**Comment by houhou2021** [comment]
I found the reason, because the FAISS_IDMAP was cleared due to insufficient memory.
