### ISSUE TITLE
编译milvus中faiss arm镜像这一步 faiss镜像名字怎么起

### ISSUE THREAD

**Issue by yuanpengpeng** [milvus-io/milvus#4417]
编译milvus中 faiss  arm镜像这一步 Makes a core/src/index/thirdparty/faiss build on ARM;   docker build -f Dockfile -t xx:xx .

这个编译的faiss镜像名字怎么起,不是随便起的吧,milvus应该会依赖它吧

**Comment by scsven** [comment]
duplicate issue #4391
