### ISSUE TITLE
Support second search after PQ index search

### ISSUE THREAD

**Issue by chenqingguo** [milvus-io/milvus#4421]
When the compression factor is 32 or even bigger, the search results of IVFPQ are low accuracy(nprobr=nlist,regardless the IVF). 
The common method is to use the results(top 2000 or much more) of PQ as a new database,then do a refine search(brute-force search). 
That can significantly improve topk‘s accuracy.
The problem is we have to save original vectors. 
My plan is to deal with IVFPQ index (encode data) on gpus and to search the original data on cpu.
Is it worth to do or do you have some suggestions?

**Comment by shengjun1985** [comment]
Yes, it worth.
As I know, many company did it.

**Comment by chenqingguo** [comment]
> Yes, it worth.
> As I know, many company did it.

So do you team have a plan about this feature?

**Comment by shengjun1985** [comment]
This is a strategy that can be tried.
However, we need to do more research before it is implemented.
And if you have any experience, it is welcome to share it with us.
