### ISSUE TITLE
Can not find the vector itself. (milvus v0.10.4, Java SDK v0.8.5, metric_type IP)

### ISSUE THREAD

**Issue by LeeXinghao** [milvus-io/milvus#4422]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [√] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**
Add any other context about the problem here

**版本信息：**
milvus v0.10.4 (Java SDK version v0.8.5)
**创建集合信息：**
索引类型：FLAT；metric_typ: IP
**说明**
入库了1000张图片的向量（经过归一化处理），入库完成之后在1000 中随机获取图片计算向量（经过归一化处理）去进行检索。经过比对入库的向量和进行检索的向量完全一样，但是存在检索不到相同向量的情况。

**Comment by LeeXinghao** [comment]
向量维度   dimension = 512L

**Comment by sahuang** [comment]
Can you provide the code you used for searching, or provide a minimum sample program so we can reproduce the issue?

**Comment by sahuang** [comment]
In addition, can you try to run this [example](https://github.com/milvus-io/milvus-sdk-java/blob/0.8.5/examples/src/main/java/MilvusClientExample.java) program and check if it works for you?

The example program inserts 100000 randomly generated float vectors into Milvus and uses IP as the metric type. First 5 vectors are used as the query and we compare the result ids and distances. You can also change the random vectors into your image embeddings.

**Comment by shengjun1985** [comment]
@LeeXinghao 
Some users encountered this problem because their normalization was wrong.
You can check the length of your vectors.

**Comment by LeeXinghao** [comment]
@sahuang  
[MilvusHelperUtil.java.zip](https://github.com/milvus-io/milvus/files/5664893/MilvusHelperUtil.java.zip)
this is my code file (.java)

**Comment by sahuang** [comment]
How did you call the helper functions to search? Did you flush collection after insert, then search vectors?

**Comment by LeeXinghao** [comment]
@shengjun1985 my vector length is always 512 dimensions

**Comment by LeeXinghao** [comment]
@sahuang 
We didn't refresh the collection, but we created the partition when we put it into the milvus db. We also brought the partition information to query when querying. Does this affect the results?

**Comment by sahuang** [comment]
If you do not call flush() and search immediately, the data will not be in the collection. Milvus has an auto flush interval of 1 second if you do not manually call the flush() API. I am not sure about the time difference between your searching and inserting.

**Comment by LeeXinghao** [comment]
I'm sure, more than 1 second. 😁

**Comment by sahuang** [comment]
Can you manually call flush() and try again? Meanwhile I can take a look at your helper file and check if there are any problems.

**Comment by LeeXinghao** [comment]
At present, min/max is 0-1. We use the intranet and can't share it

**Comment by sahuang** [comment]
Our example program has no problem in searching float vectors with IP and returning correct results. It may be other errors about calling the APIs.

**Comment by shengjun1985** [comment]
If you have more questions, please continue to contact our community.
