### ISSUE TITLE
Want an ARM image of Milvus v0.10.x

### ISSUE THREAD

**Issue by yuanpengpeng** [milvus-io/milvus#4423]
请问你们能提供一个milvus的arm镜像版本么,0.10.3版本以后的都可以,我们目前急需在盒子上现场部署使用,本地编译arm版本会出一些问题,在docker hub上只找到了0.6版本的,但是那时候不提供go的客户端,不胜感激!

**Comment by yuanpengpeng** [comment]
请问大概什么时候能给出一个milvus的arm镜像呢,谢谢了

**Comment by yhmo** [comment]
ARM上的编译很难搞，并且不同的ARM系统出现的编译问题也不一样，目前我们还抽不出人力来做这个方向。

大部分编译问题出在第三方库上，比如mysql的中间库。0.10.4去掉了SQLite的中间库，相对于其他版本会稍微好编译一点。
你可以尝试把mysql的依赖去掉，主要是 src/db/meta/MySQLMetaImpl.h/cpp这两个文件依赖到，把MySQLMetaImpl这个类曲调，调用这个类的地方也去掉，把工程配置里mysql相关的都去掉。


________________________________
