### ISSUE TITLE
Failed to restart Milvus after MySql password changed

### ISSUE THREAD

**Issue by pandab0y** [milvus-io/milvus#4429]
1. 修改mysql密码，  milvus 容器宕机  
2. 修改milvus配置文件中mysql密码
3.重启milvus容器， 报错：  failed to open database: Can't construct MySQL connection. Possible reason: out of storage, meta schema is damaged or created by in-compatible Milvus version

muilvus  version: v0.10.2

**Comment by yhmo** [comment]
I could not reproduce this problem. Milvus works well after reset  mysql password and restart milvus container.
My steps:
1. download mysql 5.7 image
`docker pull mysql:5.7`

2. start mysql container
`docker run -p 3306:3306 -e MYSQL_ROOT_PASSWORD=123456 -d mysql:5.7`

3.download milvus 0.10.2 cpu version image
` docker pull milvusdb/milvus:0.10.2-cpu-d081520-8a2393`

4. start a milvus container, mapping milvus work path to ~/milvus, in the ~/milvus/conf/server_config.yaml specify mysql uri:
```
general:
  timezone: UTC+8
  meta_uri: mysql://root:123456@172.16.50.29:3306/milvus
```

`docker run -it -d -p 19530:19530 -v ~/milvus/db:/var/lib/milvus/db -v ~/milvus/conf:/var/lib/milvus/conf -v ~/milvus/logs:/var/lib/milvus/logs -v ~/milvus/wal:/var/lib/milvus/wal milvusdb/milvus:0.10.2-cpu-d081520-8a2393`

5. use milvus python client to do something, create a collection, insert some vectors

6. change mysql password
`mysql -h127.0.0.1 -uroot -p'123456'`
`set password for root=password('aaa');`

7. use milvus python client to do something, the api return error message 'Failed to connect to meta server(mysql)'

8. stop milvus container
`docker stop [continer_id]`

9. modify the ~/milvus/conf/server_config.yaml to new password
```
general:
  timezone: UTC+8
  meta_uri: mysql://root:aaa@172.16.50.29:3306/milvus
```

10. restart milvus container
`docker start [container_id]`

11. use milvus python client to do something, create collection, insert, create index, everything is ok

**Comment by shengjun1985** [comment]
If you have more questions, please continue to contact our community.
