### ISSUE TITLE
Support "string" type field

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#4430]
**Please state your issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I wish I could use Milvus to do [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by douglarek** [comment]
@yhmo thanks, it is a very cool feature if supported.

**Comment by yhmo** [comment]
This feature is in progress in v2.0:
https://wiki.lfaidata.foundation/display/MIL/MEP+11+--+Support+String+DataType

**Comment by DrBamba** [comment]
Is there any approximation as for when will this feature be released? Is it going to be a part of 2.0.0?

**Comment by hadim** [comment]
Same question here. We are considering switching to milvus, but we need to be able to index our vectors using a string.

**Comment by alturkovic** [comment]
We are also facing the same issue. String tags in metadata are also a requirement for us besides the id field.

**Comment by xiaofan-luan** [comment]
> We are also facing the same issue. String tags in metadata are also a requirement for us besides the id field.

We decided to deliver string functions in the next release. (Possbily delivered at April) xige-16 and DD is volunteered to take the responsibility~~

If anyone want to join please let me know, since there are too many people wait for this functionality

**Comment by yanliang567** [comment]
String Type would be supported in 2.1

**Comment by hadim** [comment]
> String Type would be supported in 2.1

Will it also support string field as primary key?

**Comment by xiaofan-luan** [comment]
> > String Type would be supported in 2.1
> 
> Will it also support string field as primary key?
String as PK is in the plan

**Comment by chuongnvk54** [comment]
Hi  had similar problem when inserting string field please let me know when milvus version 2.1 will be released?

> > > String Type would be supported in 2.1
> > 
> > 
> > Will it also support string field as primary key?
> > String as PK is in the plan

**Comment by Shreypandey** [comment]
> String Type would be supported in 2.1

Is there any approximation of the release date of v2.1?

**Comment by Shreypandey** [comment]
/reopen
> String Type would be supported in 2.1

Is there any approximation of the release date of v2.1?
