### ISSUE TITLE
Milvus ro nodes quit abnormally

### ISSUE THREAD

**Issue by yu-hailong** [milvus-io/milvus#4437]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Our milvus cluster include 1rw + 3ro, and they run servel days normally.
But at 12/10 04:50, 3 three ro nodes does not work, and we found  at that time rw node became abnormal too, even we didn't any write on rw node.
1. the graph is cpu load of pysical machine while  rw node docker run on it.
![image](https://user-images.githubusercontent.com/17443614/101736055-c4edfc80-3afd-11eb-971f-4cdc6b2d5e04.png)

 2. The following is the ro node graph
![image](https://user-images.githubusercontent.com/17443614/101736791-ea2f3a80-3afe-11eb-87bb-9085e1035673.png)

At 12/10 4:50 , two ro nodes docker quit abnormally.
Only one ro node docker keep running, but there were lots of timeout while client query arrived. 
We want to know, if rw node became abnormal, it will effect ro nodes? 

**Steps/Code to reproduce behavior**
we do not know how to reproduce it.

**Expected behavior**

**Method of installation**
- [ X ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
0.10.3

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yu-hailong** [comment]
we try to see milvus log ,but no important things found.
If you need any logs, please let me kwnow the logs‘  name

**Comment by yu-hailong** [comment]
Because It is a complex problem, so if you want to know detail, you can call me : 13466316980 (Yu)
it is a problem happened on  online service , any help is prefered

**Comment by yu-hailong** [comment]
It is not only  a question , I think it is bug, it should be disscussed it is fixed or not  in future version

**Comment by yhmo** [comment]
@yu-hailong Sorry no response last week, last week our company is in annually activity, most of people are not online.
Recently we notice some issues report milvus is hangs during continually searching, we found steps to reproduce the hang issue, the issue is [#4378](https://github.com/milvus-io/milvus/issues/4378). 
If you have multiple clients, some clients call search(), some other call load_collection()/get_entity_by_id()/reload_segment(), the milvus could hang.
You said you deploy a cluster including 1rw + 3ro, did you use mishard?

**Comment by yhmo** [comment]
By using 0.10.3, to avoid the hang issue, remove the call of load_collection()/get_entity_by_id().

**Comment by yu-hailong** [comment]
> You said you deploy a cluster including 1rw + 3ro, did you use mishard?
we did not use mishards. rw node for write data. ro node for query, 3 ro node for high available

**Comment by shengjun1985** [comment]
@yu-hailong
Excuse me, after Milvus updated to 0.10.5, does this problem still occur?

**Comment by yu-hailong** [comment]
> @yu-hailong
> Excuse me, after Milvus updated to 0.10.5, does this problem still occur?

No, it did not occur.

**Comment by shengjun1985** [comment]
We have fixed a lot of serious bugs in 0.10.4 and 0.10.5.
If any new bug occurs, please continue to contact our community.
Thank you very much.
