### ISSUE TITLE
[Milvus EM]The shown segment_row_limit doesn’t  correspond with the setting value. 

### ISSUE THREAD

**Issue by miia12** [milvus-io/milvus#4440]
The setting value is 1000
<img width="1086" alt="截屏2020-12-10 下午4 40 08" src="https://user-images.githubusercontent.com/22544815/101747932-d4257800-3b06-11eb-874a-b56e899b5023.png">

The shown value is still 524288
<img width="1072" alt="截屏2020-12-10 下午4 40 14" src="https://user-images.githubusercontent.com/22544815/101747993-eef7ec80-3b06-11eb-9bf3-798d0b02bbbd.png">

**Comment by fishpenguin** [comment]
This is a em issue that it mistakenly writes "segment_row_limit" to "segment_row_count in http body.

**Comment by shanghaikid** [comment]
it will be fixed in the next version of EM. I think it will be releases along with the 0.11.1.
