### ISSUE TITLE
Failed to load index

### ISSUE THREAD

**Issue by victor-u** [milvus-io/milvus#4446]
Errors like this:
# Loading configuration from: /var/lib/milvus/conf/server_config.yaml
# Supported CPU instruction sets: avx512, avx2, sse4_2
# FAISS hook AVX512
# ERROR! Failed to preload tables: *
# Error: Failed to load index from /var/lib/milvus//db/tables/wps/1604072067170112000/1602754693737053000
# Milvus server is going to shutdown ...
# Milvus server exit...
# '''

Happended When i used the method DeleteEntityByID(with GO SDK)

**Comment by fishpenguin** [comment]
What's your milvus version and go sdk version?

**Comment by shengjun1985** [comment]
If you have more questions, please continue to contact our community.

**Comment by bowenzzzzzz** [comment]
@shengjun1985 @victor-u 
Hello, there.
Have you solve the issue? I meet the same issue, and I do not know what's going on this? Could you do me a favour?

The milvus version I used is 1.0.0
The logs is as follows.

Welcome to use Milvus!
Milvus Release version: v1.0.0, built at 2021-03-04 06:43.00, with OpenBLAS library.
You are using Milvus CPU edition
Last commit id: 21ea92ec7e57ab00cca671d74195c4eaa81869a2

Loading configuration from: /var/lib/milvus/conf/server_config.yaml
Supported CPU instruction sets: avx512, avx2, sse4_2
FAISS hook AVX512
ERROR! Failed to preload tables: *
Error: Failed to load index from /var/lib/milvus/db/tables/milvus1/1623828175485539000/1623828177165203000
Milvus server is going to shutdown ...
Milvus server exit...
