### ISSUE TITLE
search with partition

### ISSUE THREAD

**Issue by CrazyBeeline** [milvus-io/milvus#4460]
version:0.11.0

I want to search with partition with restful api
/collections/{collection_name}/entities (GET)  
how can I make my dsl .
the doc can not tell me how to do this

**Comment by yhmo** [comment]
@fishpenguin will answer this.

**Comment by fishpenguin** [comment]
You can write it in http body like :
```json
{
    "query": {
        "bool": {
            "must":[
                {"vector": 
                    {
                        "field_vec": {
                            "params": {
                                "nprobe": 64
                            }
                            "topk": 100,
                            "metric_type": "L2"
                            "values": [
                                [0.1, 0.2, "..."],
                                "..."
                            ]
                        }
                    }
                }
            ],
        },
        partition_tags: ["part_1", "part_2"],
        "fields": ["field_vec"]
    }
}
```

**Comment by fishpenguin** [comment]
This is a doc issue and has already fixed in milvus-0.11.1.

**Comment by CrazyBeeline** [comment]
dear! @fishpenguin 
I have two partitions ---> "test1" "test2"
"test1" has vectors 
"test2" has no vector
in your dsl "fileds" can not search correct.
this is my dsl  and "partition_tags" does not work
{
    "query": {
        "bool": {
            "must": [
                {
                    "vector": {
                        "vector": {
                            "params": {
                                "nprobe": 64
                            },
                            "topk": 100,
                            "metric_type": "IP",
                            "values": [
                                [
                                    1
                                ]
                            ]
                        }
                    }
                }
            ]
        }
    },
    "partition_tags": ["test2"],
    "fields": [
        "time"
    ]
}
this dsl can search vectors where in partition "test1"

**Comment by fishpenguin** [comment]
This is a milvus-0.11.0 restful api bug as [issue4205](https://github.com/milvus-io/milvus/issues/4205), and it has been fixed in [pr4206](https://github.com/milvus-io/milvus/pull/4206) in milvus-0.11.1.

**Comment by CrazyBeeline** [comment]
ths

**Comment by CrazyBeeline** [comment]
@fishpenguin  Can you tell me when to release version 0.11.0
