### ISSUE TITLE
During real-time insertion and retrieval, the retrieve qps periodically drops to 0

### ISSUE THREAD

**Issue by xealml** [milvus-io/milvus#4463]
**Please state your issue using the following template and, most importantly, in English.**
During real-time insertion and retrieval, the retrieve qps periodically drops to 0, how can I solve it in a real-time retrieval of scenes,can you give me some suggestion?

**Describe the bug**
as describe

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
The question is not clear.
Do you mean client continually call insert() and get_entity_by_id() ?

**Comment by shengjun1985** [comment]
Excuse me, what's your Milvus version and SDK version?

**Comment by xealml** [comment]
> Excuse me, what's your Milvus version and SDK version?

milvus==0.11.0
and correspond python

**Comment by xealml** [comment]
> The question is not clear.
> Do you mean client continually call insert() and get_entity_by_id() ?

insert(add) and query at the same time.

**Comment by shengjun1985** [comment]
Excuse me, can you provide your test codes?

**Comment by yhmo** [comment]
@xealml 
A possible reason is:
- create a collection and specify index(IVFLAT, IVFSQ8, etc.) by create_index()
- continually insert entities and search
- when entity row count hit the "segment_row_limit", milvus backgroud thread will begin build index for segment, this will partly occupy cpu capacity and slow down the search performance
- after one segment build index finish, the search can occupy all cpu resource and performance be fast again
- when next segment row count hit the "segment_row_limit", milvus backgroud thread will begin build index for this segment, search performance get worse.

This may be the reason why search performance is "periodically".

**Comment by xealml** [comment]
> @xealml
> A possible reason is:
> 
> * create a collection and specify index(IVFLAT, IVFSQ8, etc.) by create_index()
> * continually insert entities and search
> * when entity row count hit the "segment_row_limit", milvus backgroud thread will begin build index for segment, this will partly occupy cpu capacity and slow down the search performance
> * after one segment build index finish, the search can occupy all cpu resource and performance be fast again
> * when next segment row count hit the "segment_row_limit", milvus backgroud thread will begin build index for this segment, search performance get worse.
> 
> This may be the reason why search performance is "periodically".

Yes, may be that is the reason. The qps of the query droped to 0, and the problem occurs frequently.And I tried to set segment_row_limit=400w, the situation does not seem to improve.
