### ISSUE TITLE
About Spark Connector Plugin

### ISSUE THREAD

**Issue by innerNULL** [milvus-io/milvus#4466]
One case for using milvus is, encoding all texts to vectors with a pretrained nlp model, and inserting this vectors into a milvus collection, but when first time starting service, we usually has very huge amount texts to encoding and inserting, for encoding step, we can just submit a pyspark job, but for inserting step, if there should be a connection between spark and milvus? : )

**Comment by yhmo** [comment]
Each pyspark job should have an output result, spark can write the result to a file, right? Is is possible to detect the result file and read data to call milvus insert() interface.
