### ISSUE TITLE
Kubernetes service discovery fails (mishards) when pod is running, but it is not ready yet

### ISSUE THREAD

**Issue by jmichaelsilva** [milvus-io/milvus#4469]
Version v0.10.4

**Describe the bug**
Kubernetes service discovery fails (mishards) when pod is running, but it is not ready yet.

**Steps/Code to reproduce behavior**
Start some readonly nodes (pods) in a kubernetes cluster (mishards configured with k8s service discovery). Then, delete some readonly pods. Sometimes this still happens when mishards start.

**Method of installation**

Kubernetes
![image](https://user-images.githubusercontent.com/65552708/102388890-248e5100-3fb1-11eb-8c1b-d874b2e1db0d.png)

Mishards error screenshot:
![image](https://user-images.githubusercontent.com/65552708/102388990-4c7db480-3fb1-11eb-8c00-fa25af5ef2d0.png)
After this error the only way to recovery mishards is restarting the pod/container.

The error is in the following line of code:
https://github.com/milvus-io/milvus/blob/1c48f7f4e47252f8aa2b3c09c9289a9444f5887c/shards/discovery/plugins/kubernetes_provider.py#L78

Instead of just checking if the pod is running, should also check whether the mishards container is in a ready state. If the container isn't still ready. GRPC connection fails and mishards do not recovery itself.

**Comment by BossZou** [comment]
@jmichaelsilva , this bug has been fix at PR #4474, we'll release a new milvus and mishards images for version 0.10.5 later.

**Comment by BossZou** [comment]
@jmichaelsilva , Milvus and Mishards v0.10.5 has been released. You can use upgrade your nodes.

**Comment by jmichaelsilva** [comment]
Thank you @BossZou! I just upgraded to v0.10.5 and ran some tests (``I started some read-only nodes (pods) in a Kubernetes cluster (mishards configured with K8s service discovery). Then, I deleted some read-only pods``). 

This time, the following errors occurred:
![image](https://user-images.githubusercontent.com/65552708/104221893-5368dd00-5420-11eb-9004-639be373fbb5.png)

And:
![image](https://user-images.githubusercontent.com/65552708/104221971-6c718e00-5420-11eb-98f0-8204dd9f4ae3.png)

After these errors, mishards cannot recovery. I had to restart the mishards pod (it's bad for HA).

Should I open another issue or reopen this one? What do you prefer?

**Comment by BossZou** [comment]
@jmichaelsilva , did you upgrade mishards image to v0.10.5, you may upgrade mishards to ` milvusdb/mishards:0.10.5` then try again.

**Comment by jmichaelsilva** [comment]
@BossZou I've already upgraded (mishards, writable and readonly servers) to v0.10.5. As you can see below: 

Mishards:
```
  Containers:
   mishards:
    Image:      milvusdb/mishards:0.10.5
```

Writable:
```
  Containers:
   milvus:
    Image:       milvusdb/milvus:0.10.5-cpu-d010621-4eda95
```

Readonly:
```
  Containers:
   milvus:
    Image:       milvusdb/milvus:0.10.5-cpu-d010621-4eda95
```

So, the last error reported here (https://github.com/milvus-io/milvus/issues/4469#issuecomment-758137615) refers to v0.10.5.

I opened another issue https://github.com/milvus-io/milvus/issues/4618 with more details.

**Comment by yhmo** [comment]
#4618 is opened. Close this one.
