### ISSUE TITLE
_Rendezvous of RPC that terminated with:

### ISSUE THREAD

**Issue by KingBoyAndGirl** [milvus-io/milvus#4470]
2020-12-17 01:55:13,509 - milvus.client.grpc_client - ERROR - <_Rendezvous of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = ""
	debug_error_string = "{"created":"@1608170113.509400253","description":"Error received from peer ipv4:192.168.157.130:19530","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"","grpc_status":13}"
>
2020-12-17 01:55:13,510 - root - ERROR - list index out of range

都是用docker搭建的，版本如下：
![image](https://user-images.githubusercontent.com/48237066/102433012-733df880-404e-11eb-9293-82b7d8d770a4.png)
![image](https://user-images.githubusercontent.com/48237066/102433928-b0a28600-404e-11eb-9fe4-eea8c4064a03.png)

以下是服务端完整错误：
![image](https://user-images.githubusercontent.com/48237066/102434000-d0d24500-404e-11eb-9f72-08a0db3d739f.png)
请问怎么解决这个问题？

**Comment by BossZou** [comment]
@KingBoyAndGirl , I noticed there were some "StatusCode.UNIMPLEMENTED" status in error message. May you provide your milvus version and client sdk version?
