### ISSUE TITLE
[Milvus 0.6] Build error on ARM

### ISSUE THREAD

**Issue by yuanpengpeng** [milvus-io/milvus#4471]
我将milvus0.6版本源码上面的faiss文件夹下代码复制到arm机器上编译有问题,按照faiss官方文档说明,faiss编译成功,cd c_api下面编译c接口时,报如下错误:
g++ -std=c++11 -DFINTEGER=int  -fopenmp -I/usr/local/cuda/include  -fPIC  -Wno-sign-compare -g -O3 -Wall -Wextra -I.. -DNDEBUG  -march=armv8.2-a -c error_impl.cpp -o error_impl.o
error_impl.cpp:13:10: fatal error: FaissException.h: No such file or directory
 #include "FaissException.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:41: recipe for target 'error_impl.o' failed
make: *** [error_impl.o] Error 1

但是那个FaissException.h在iml文件夹下存在,什么原因?

**Comment by scsven** [comment]
@yuanpengpeng The reason for this error is that the `impl` directory is not in the search path of the header file. By the way, only the `aarch64` branch can be compiled on ARM.
