### ISSUE TITLE
Require papers about milvus index algorithm

### ISSUE THREAD

**Issue by yuanpengpeng** [milvus-io/milvus#4472]
milvus关于索引算法的发表的论文有么,暂时没找到,想拿出来看看

**Comment by sahuang** [comment]
Hi, Milvus paper is currently in progress and we will share it with the community once it's accepted. Meanwhile, we suggest you to read some other papers related to Faiss and HNSW, which we used as our indexes.

**Comment by shengjun1985** [comment]
https://2021.sigmod.org/sigmod_industrial_list.shtml
<Milvus: A Purpose-Built Vector Data Management System>
