### ISSUE TITLE
Too much disk space is being used in read-write separation mode

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#4497]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
One million entities with 128 dimension vectors (float datatype), and without any scalar fields, and build sq8 index (nlist 16384).
when `cluster=false`,  the disk space is 644M
```
zilliz@apollo:/test/milvus/db_data_011/cluster/sift_1m_2000000_128_l2_2_1608637343/db$ du -sh
644M	
```
when `cluster=true`, the disk space is 1.8G
```
zilliz@apollo:/test/milvus/db_data_011/cluster/sift_1m_2000000_128_l2_2_1608630084/db$ du -sh
1.8G	
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 -0.11.1

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by XuPeng-SH** [comment]
@ThreadDao It should be fixed with the latest image.
