### ISSUE TITLE
compile error on milvus 0.10.3

### ISSUE THREAD

**Issue by liaodaihai** [milvus-io/milvus#4501]
when i Install Milvus from Source Code, i followed the procedure https://github.com/milvus-io/milvus/blob/0.10.3/INSTALL.md.
When i execute step2 $ ./build.sh -t Release,i encounter this error:
![Image_20201223164937](https://user-images.githubusercontent.com/41409707/102983312-d7792480-4546-11eb-87fc-02f53686d343.png)
-- Milvus version: .. (full: '0.10.3')
-- Building milvus_engine on x86 architecture
CMake Error at CMakeLists.txt:140 (include):
  include could not find load file:

    DefineOptions

CMake Error at CMakeLists.txt:141 (include):
  include could not find load file:

    BuildUtils

CMake Error at CMakeLists.txt:142 (include):
  include could not find load file:

    ThirdPartyPackages

-- Building Milvus GPU version
ENABLE_CPU_PROFILING = OFF
CMake Error at CMakeLists.txt:191 (config_summary):
  Unknown CMake command "config_summary".

-- Configuring incomplete, errors occurred!
See also "/home/hequn/core/CMakeFiles/CMakeOutput.log".
See also "/home/hequn/core/CMakeFiles/CMakeError.log".
./build.sh: 118: ./build.sh: [[: not found
./build.sh: 122: ./build.sh: [[: not found
make: *** No rule to make target 'install'.  Stop.

**Comment by liaodaihai** [comment]
My environment is like this.
Ubuntu 18.04
GCC 7.0
CMake 3.14
CUDA 11.0
NVIDIA driver 450.80.02

**Comment by liaodaihai** [comment]
![Image_20201223164937](https://user-images.githubusercontent.com/41409707/102983717-79007600-4547-11eb-95be-d8289e8169ef.png)

**Comment by BossZou** [comment]
@liaodaihai , Did you run `ubuntu_build_deps.sh` to install dependences?

**Comment by liaodaihai** [comment]
@BossZou yes i finished it!

**Comment by liaodaihai** [comment]
I execute the step2 $ ./build.sh -t Release -g ,i ecounter the error:
/usr/local/cuda/targets/x86_64-linux/include/cub/util_cpp_dialect.cuh:129:13: warning: CUB requires C++14. Please pass -std=c++14 to your compiler. Define CUB_IGNORE_DEPRECATED_CPP_DIALECT to suppress this message.
   CUB_COMPILER_DEPRECATION(C++14, pass -std=c++14 to your compiler);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                         
src/index/CMakeFiles/faiss_ep.dir/build.make:110: recipe for target 'src/index/faiss_ep-prefix/src/faiss_ep-stamp/faiss_ep-build' failed
make[2]: *** [src/index/faiss_ep-prefix/src/faiss_ep-stamp/faiss_ep-build] Error 2
CMakeFiles/Makefile2:696: recipe for target 'src/index/CMakeFiles/faiss_ep.dir/all' failed
make[1]: *** [src/index/CMakeFiles/faiss_ep.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by yhmo** [comment]
@liaodaihai 
Looks like your cmake version is not qualify.
Print your cmake version:
`cmake --version`

My cmake version is 3.14.4

**Comment by yhmo** [comment]
And, there should be a cmake script under this folder:
` /milvus/core/cmake/DefineOptions.cmake`

Is this file exist?

**Comment by liaodaihai** [comment]
@yhmo It exists.

**Comment by liaodaihai** [comment]
@yhmo I changed the version of cmake, my camke version is 3.14.4,but the error still exists.

**Comment by shengjun1985** [comment]
@liaodaihai
There may be some strange reasons that cannot be solved in a short term.
Please try to solve it with [compile-milvus-on-docker](https://github.com/milvus-io/milvus/blob/master/INSTALL.md#compile-milvus-on-docker).
Furthermore, we have fixed a lot of bugs in v0.10.4.
So it is suggested to install that version in place of v0.10.3.

**Comment by liaodaihai** [comment]
I have tried v0.10.4,i get the same error.

**Comment by liaodaihai** [comment]
@shengjun1985

**Comment by shengjun1985** [comment]
Compiling with docker can solve many environmental factors.
Can you try to [compile-milvus-on-docker](https://github.com/milvus-io/milvus/blob/master/INSTALL.md#compile-milvus-on-docker)?

**Comment by liaodaihai** [comment]
@shengjun1985 compile-milvus-on-docker is successful, but i think compile-milvus-on-docker is not convenient.

**Comment by martinGit01** [comment]
I  have built it successfully with GCC7.5.0 on centos7.
When I build it with Gcc6.5.0, i met the same issue as you,  I think you can try it with GCC7.5.0.

**Comment by liaodaihai** [comment]
I solve the problem when i change mu cuda version to 10.2.

**Comment by liaodaihai** [comment]
I solved the problem when i change my cuda version to 10.2.

**Comment by yhmo** [comment]
In the page [compile-milvus-on-docker](https://github.com/milvus-io/milvus/blob/master/INSTALL.md), in the "Requirements" section, mentioned:
```
For GPU-enabled version, you will also need:
CUDA 10.x (10.0, 10.1, 10.2)
NVIDIA driver 418 or higher
```
