### ISSUE TITLE
Add a metric to display the number of files opened by Milvus

### ISSUE THREAD

**Issue by scsven** [milvus-io/milvus#4504]
**Please state your issue using the following template and, most importantly, in English.**
t seems that there are some bugs caused by too many open files.

**Comment by fishpenguin** [comment]
[Pr4509](https://github.com/milvus-io/milvus/pull/4509) can only monitor total open file descriptors in system by nodeexporter but can not monitor the number of file opens by milvus. It is hard to display the number of files opened by Milvus, so this issue need to follow up in later version of milvus.

**Comment by scsven** [comment]
Not activity.
