### ISSUE TITLE
Insert should be failed if field type not matched

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#4511]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```

=================================== FAILURES ===================================
____________ TestInsertBase.test_insert_with_field_type_not_match_B ____________
[gw0] linux -- Python 3.6.8 /usr/local/bin/python3

self = <test_bulk_insert.TestInsertBase object at 0x7f8aa18764a8>
connect = <milvus.client.stub.Milvus object at 0x7f8aed306f98>
collection = 'test_mubfaWvy'

    @pytest.mark.level(2)
    def test_insert_with_field_type_not_match_B(self, connect, collection):
        '''
        target: test insert entities, with the entity field type updated
        method: update entity field type
        expected: error raised
        '''
        tmp_entity = update_field_type(copy.deepcopy(default_entity), "int64", DataType.DOUBLE)
        with pytest.raises(Exception):
>           connect.bulk_insert(collection, tmp_entity)
E           Failed: DID NOT RAISE <class 'Exception'>

entity/test_bulk_insert.py:446: Failed
```
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by BossZou** [comment]
See #4157

**Comment by yhmo** [comment]
duplicated with #4157
