### ISSUE TITLE
Want a way for Chinese users to compile C++ SDK

### ISSUE THREAD

**Issue by khw934** [milvus-io/milvus#4512]
【SDK】在国内执行 build.sh 编译c++ SDK 卡死， 估计是网络的原因， 请考虑下国内的网络情况

执行 milvus/sdk/build.sh 会卡死

**Comment by yhmo** [comment]
Please refer this issue: https://github.com/milvus-io/milvus/discussions/4323
C++ sdk only depends on 2 third-party: zlib and grpc
Sometimes it block at downloading grpc zip file, you can use wget manually download the zip file, copy the file to destiny folder.

**Comment by khw934** [comment]
> Please refer this issue: #4323
> C++ sdk only depends on 2 third-party: zlib and grpc
> Sometimes it blocks at downloading grpc zip file, you can use wget manually download the zip file, copy the file to destination folder.


After downloading these two libraries, put them in that directory ？？？？

**Comment by cos120** [comment]
I found `mysqlpp` is very slow, i modify cmake file and create local http server to provide packages, milvus has some environment variable to hook package url.

**Comment by yhmo** [comment]
@khw934 
For example, the error message tell you grpc download failed:

```
   29 [ 28%] Performing download step (download, verify and extract) for 'grpc_ep'
   28 -- Downloading...
   27    dst='/home/xxxx/milvus/sdk/cmake_build/grpc_ep-prefix/src/master.zip'
   26    timeout='none'
   25    inactivity timeout='none'
   24 -- Using src='https://github.com/youny626/grpc-milvus/archive/master.zip'
   23 -- [download 100% complete]
   22 CMake Error at grpc_ep-stamp/download-grpc_ep.cmake:170 (message):
   21   Each download failed!
   20 
   19     error: downloading 'https://github.com/youny626/grpc-milvus/archive/master.zip' failed
```
Then you can use wget to manually download the 'https://github.com/youny626/grpc-milvus/archive/master.zip' and put the zip into '/home/xxxx/milvus/sdk/cmake_build/grpc_ep-prefix/src/master.zip'

**Comment by shengjun1985** [comment]
If you have more questions, please continue to contact our community.
