### ISSUE TITLE
For the case of batch-inserting with multi-threading task, c++ api is much slower than python api

### ISSUE THREAD

**Issue by innerNULL** [milvus-io/milvus#4515]
Just as title, I used 100k records splitted in 10 part files, which means the batch size is 10k.

**Comment by innerNULL** [comment]
My guess is it seems python's inserting-entities api is not asynchronous, so the server side will not be blocked by too many inserting requests happend in a shord peroid?

**Comment by fishpenguin** [comment]
What version of milvus and sdk did you use? And did you use asynchronous python api or synchronous python api?

**Comment by innerNULL** [comment]
> What version of milvus and sdk did you use? And did you use asynchronous python api or synchronous python api?

@fishpenguin For python sdk, the version is 0.3.0, for cpp sdk, the version is 0.11.0, the python api I used is [insert](https://pymilvus.readthedocs.io/en/0.3.0/api.html#milvus.Milvus.insert), the cpp api I used is `Insert` ref to [ClientTest.cpp](https://github.com/milvus-io/milvus/blob/master/sdk/examples/simple/src/ClientTest.cpp)
