### ISSUE TITLE
module 'milvus' has no attribute 'MetricType'

### ISSUE THREAD

**Issue by un-poco** [milvus-io/milvus#4524]
ubuntu 18.04 
pymilvus==0.3.0

I can successfully import milvus 
or from milvus import Milvus
But I can not make it to import MetricType, Why?

**Comment by fishpenguin** [comment]
In pymilvus0.3.0, there is no MetricType module. You should write MetricType with string like "IP" or "L2".

**Comment by BossZou** [comment]
@un-poco , you are recommended to refer to [example](https://github.com/milvus-io/pymilvus/blob/0.3.0/examples/example.py).

**Comment by shengjun1985** [comment]
Answered.
