### ISSUE TITLE
Maybe we should allow milvus to count entities in specific partition

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#4527]
**Please state your issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**
I wish I could know how many entities in this partition in a simple way.
Add `partition_tag` parameter in `count_entities` interface like `insert` and `search`.
```
def count_entities(self, collection_name, timeout=30):
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by yhmo** [comment]
Actually, get_collection_stat() can get entity number for each partition.
