### ISSUE TITLE
Load collection successfully with empty partition tags arraylist

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#4534]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
    @Test(dataProvider = "Collection", dataProviderClass = MainClass.class)
    public void test_load_empty_partitions(MilvusClient client, String collectionName) {
        List<String> tags = new ArrayList<>();
        Response load_res = client.loadCollection(collectionName, tags);
        System.out.println(load_res.getMessage());
        assert !load_res.ok();
    }
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 -0.10.5

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by sahuang** [comment]
Confirmed that when empty arraylist is passed as partition tags, the whole collection will be loaded.
