### ISSUE TITLE
restful api "/collections/{collection_name}/partitions (DELETE)" didn't work

### ISSUE THREAD

**Issue by bitxinyu** [milvus-io/milvus#4536]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
restful api "/collections/{collection_name}/partitions (DELETE)" didn't work. and response code is 404

**Steps/Code to reproduce behavior**
The code for each step is copied from here https://github.com/milvus-io/milvus/tree/0.11.0/core/src/server/web_impl
1. create a collection
![image](https://user-images.githubusercontent.com/11964010/103258631-d7f33e80-49d0-11eb-9b5d-65f057aaf8de.png)
2. create a partition in collection
![image](https://user-images.githubusercontent.com/11964010/103258658-03762900-49d1-11eb-9611-8ecfaa7c0dcd.png)
3. check this partition
![image](https://user-images.githubusercontent.com/11964010/103258680-1b4dad00-49d1-11eb-8151-9b2e90dca4fe.png)
4.delete this partition, I got a 404 error
![image](https://user-images.githubusercontent.com/11964010/103258706-3a4c3f00-49d1-11eb-8c1c-42fb1584cd46.png)

**Expected behavior**
In restful api document, `The deletion is successful if no information is returned.`

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
0.11.0

**Configuration file**
use default `milvus.yaml`, but meta_url is a  mysql database,

**Comment by fishpenguin** [comment]
The is a doc bug, in milvus-0.11.0, we change this api to "/collections/{collection_name}/partitions/{partition_tag} (DELETE)", but the doc has not updated.
We will update the doc in milvus-0.11.1

**Comment by bitxinyu** [comment]
> The is a doc bug, in milvus-0.11.0, we change this api to "/collections/{collection_name}/partitions/{partition_tag} (DELETE)", but the doc has not updated.
> We will update the doc in milvus-0.11.1

I see.
I have tested all the restfull api. and found many bugs in document. :rofl: 
Thanks for your work.

**Comment by fishpenguin** [comment]
Yes, we didnot check the restful api doc carefully when 0.11.0 released. And we will fix these doc bugs in 0.11.1

**Comment by fishpenguin** [comment]
Fixed.
