### ISSUE TITLE
[0.11.0] Milvus works well although the configured memory is larger than the actual memory

### ISSUE THREAD

**Issue by b06180618** [milvus-io/milvus#4537]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

configured memory: 4G
actual memory: 1G

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by b06180618** [comment]
！

**Comment by shengjun1985** [comment]
Milvus doesn't alloc the configured memory all at once, so it will run well for a while.
And how much data do you have?

**Comment by shengjun1985** [comment]
Answered.
