### ISSUE TITLE
Can you share the design and implementation principle of scalar filtering

### ISSUE THREAD

**Issue by orange-jams** [milvus-io/milvus#4541]
**Please state your issue using the following template and, most importantly, in English.**

**Location of incorrect documentation**
Provide links and line numbers if applicable.

**Describe the problems or issues found in the documentation**
A clear and concise description of what you found to be incorrect.

**Steps taken to verify documentation is incorrect**
List any steps you have taken:

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.

---

## Report needed documentation

**Report needed documentation**
Design and implementation principle of scalar filtering.

**Describe the documentation you'd like**
The application of scalar filtering in index building and vector retrieval is described in detail.

**Steps taken to search for needed documentation**
List any steps you have taken:

**Comment by shengjun1985** [comment]
Scalar filtering will generate bitset to indicate which vectors are valid.
Then, we will only return those valid vectors when querying.

**Comment by fishpenguin** [comment]
[DSL design doc](https://docs.google.com/document/d/1U83LY36TyaG3WD67Q9HWg9saD3qQcz9BfMcEScgwQPM/edit?usp=sharing)

**Comment by orange-jams** [comment]
> Scalar filtering will generate bitset to indicate which vectors are valid.
> Then, we will only return those valid vectors when querying.

But, how to use bitset to find those valid vectors within index files?

**Comment by shengjun1985** [comment]
> But, how to use bitset to find those valid vectors within index files?

It is pretty easy.
Before caculating the distance, I will check the valid bitset first.
And if it is invalid, not to push it into the result heap.

**Comment by orange-jams** [comment]
> > But, how to use bitset to find those valid vectors within index files?
> 
> It is pretty easy.
> Before caculating the distance, I will check the valid bitset first.
> And if it is invalid, not to push it into the result heap.

Now i have another question: if  i need  to do scalar filtering and vector search in the same time, what's the procedure of it?

**Comment by fishpenguin** [comment]
Do you want to implement this procedure yourself or just want to know the procedure of milvus?
In milvus, we do scalar filtering first and this will generate a bitset, then the bitset will be passed to vector search.

**Comment by orange-jams** [comment]
> Do you want to implement this procedure yourself or just want to know the procedure of milvus?
> In milvus, we do scalar filtering first and this will generate a bitset, then the bitset will be passed to vector search.

I want to know after the bitset passed to vector search, how does it work

**Comment by shengjun1985** [comment]
> Scalar filtering will generate a bitset to indicate which vectors are valid.
> In the vector search process, before caculating the distance, I will check the valid bitset first.
> And if it is invalid, not to push it into the result heap.

I have answered. But where is not clear?

**Comment by orange-jams** [comment]
> > Scalar filtering will generate a bitset to indicate which vectors are valid.
> > In the vector search process, before caculating the distance, I will check the valid bitset first.
> > And if it is invalid, not to push it into the result heap.
> 
> I have answered. But where is not clear?

I have not understand how to use valid bitset to filter vector in result heap especially using index type annoy.

**Comment by sahuang** [comment]
Index type does not matter in terms of the bitset.

**Comment by sahuang** [comment]
Index type does not affect the usage of bitset.

After scalar-field filtering, there is a bitset that will be passed into core vector search algorithms. The bitset has a length of nb, the total vectors you insert into Milvus. It takes the value of either 0 or 1. If a vector is filtered out, it will be marked in the bitset as 1, and vise versa. For example, originally entity A is marked as 0 in the bitset. If you search with a DSL with the term X, and A is not term X, it will be marked as 1.

When performing a vector similarity search, we test each base vector's presence by calling a test function based on bitset. If it's 1, we know it's deleted and not going to do further calculations. Otherwise, we put it into the result heap as a candidate.

**Comment by orange-jams** [comment]
> If it's 1, we know it's deleted and not going to do further calculations

As annoy index is stable, when performing a vector similarity search, how could you filter out these invalid vectors  as they are already in index tree.

**Comment by sahuang** [comment]
We just filter out the vectors in the result. They are still present in the index tree. You may refer to the code for more information: https://github.com/milvus-io/milvus/blob/453def59699bb706b33363e1d92c5d0b9705ea1b/core/src/index/thirdparty/annoy/src/annoylib.h#L1360-L1368

**Comment by shengjun1985** [comment]
Answered.

**Comment by orange-jams** [comment]
> We just filter out the vectors in the result. They are still present in the index tree. You may refer to the code for more information:
> 
> https://github.com/milvus-io/milvus/blob/453def59699bb706b33363e1d92c5d0b9705ea1b/core/src/index/thirdparty/annoy/src/annoylib.h#L1353-L1375

So in my understanding, scalar-field filtering doesn't change the procedure of vector searching besides building result heap.

**Comment by sahuang** [comment]
Yes, it is just an extra judgment on top of the original vector search process.

**Comment by orange-jams** [comment]
> Yes, it is just an extra judgment on top of the original vector search process.

Thank you so much.
