### ISSUE TITLE
 Inconsistency of data  between servers.

### ISSUE THREAD

**Issue by LaoWhites** [milvus-io/milvus#4542]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Same server in docker with same metaServer and pv, but different collections returned.

**Steps/Code to reproduce behavior**

**Expected behavior**
Same result should returned by different server instance with same metaServer and pv.

**Method of installation**
- [ ] Docker/cpu

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
0.11

**Configuration file**
default configuration

```yaml
paste-file-content-here
```

**Screenshots**
![image](https://user-images.githubusercontent.com/29367057/103328489-0be36800-4a94-11eb-9e67-d5af339ec500.png)

![image](https://user-images.githubusercontent.com/29367057/103328427-dfc7e700-4a93-11eb-8df8-0379433cf1ce.png)

**Additional context**

**Comment by XuPeng-SH** [comment]
@LaoWhites 
Could you explain more about your problem? For 0.11.0, it doesn't support to open more than 1 Milvus process base on the same meta and storage data.

**Comment by shengjun1985** [comment]
same as #4133
