### ISSUE TITLE
low latency、high throughput feature support

### ISSUE THREAD

**Issue by sunyaofei** [milvus-io/milvus#4543]
**Please state your issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**
We can get from [Mishards](https://github.com/milvus-io/milvus/tree/0.11.1/shards) milvus can be deployed with Mishards  as cluster to support massive-scale(10 billion, 100 billion or even larger datasets). However, when it comes to case that datasets is limited(say, millions or tens million) and low latency、high throughput is required, Mishards cannot handle it.
Here, we need a solution to solve the problem above in production environment.

**Describe the solution you'd like**
Under kubernetes, we can use envoy and headless service to achive the goal

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by shengjun1985** [comment]
PR is merged.
Thank you very much.
