### ISSUE TITLE
java.lang.NoSuchMethodError: io.milvus.grpc.VectorRowRecord.emptyFloatList()Lcom/google/protobuf/Internal$FloatList;

### ISSUE THREAD

**Issue by Slash-Wong** [milvus-io/milvus#4551]
Milvus 0.11.0 ,jdk 9 向分区或者集合中插入向量就会报这个错误

**Comment by sahuang** [comment]
Can you refer to https://github.com/milvus-io/milvus-sdk-java/issues/132 and see if the solution works?

**Comment by Slash-Wong** [comment]
冲突
