### ISSUE TITLE
Milvus can not use with Locust

### ISSUE THREAD

**Issue by yuguosen** [milvus-io/milvus#4555]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
when i use Locust to test Milvus,they can not use together,when i import Locust and init Milvus Client it will stuck
 on init nothing to show no errors no info out 

**Steps/Code to reproduce behavior**
when code is 
```
from  locust import TaskSet
MILVUS_HOST = "xxxxx"
MILVUS_PORT = "19530"
from milvus import Milvus, DataType
print("asasasssss")
client=Milvus(MILVUS_HOST, MILVUS_PORT)
```
it will stuck on the line `client=Milvus(MILVUS_HOST, MILVUS_PORT)`

when code is 
```
MILVUS_HOST = "xxxx"
MILVUS_PORT = "19530"
from milvus import Milvus, DataType
print("asasasssss")
client=Milvus(MILVUS_HOST, MILVUS_PORT)
print(client)
from  locust import TaskSet
```
it will stuck on the line `from  locust import TaskSet`

just like this 

![image](https://user-images.githubusercontent.com/18343971/103399194-c0f05000-4b7a-11eb-84ae-0362bf7f5a90.png)

**Method of installation**
- [ ] Docker/cpu
**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)
OS: Debian
python:3.6
Milvus version:0.11.0

- Milvus version (master or released version)
```
sudo docker run -d --name milvus_cpu_0.11.0 \
-p 19530:19530 \
-p 19121:19121 \
-v /home/$USER/milvus/db:/var/lib/milvus/db \
-v /home/$USER/milvus/conf:/var/lib/milvus/conf \
-v /home/$USER/milvus/logs:/var/lib/milvus/logs \
-v /home/$USER/milvus/wal:/var/lib/milvus/wal \
milvusdb/milvus:0.11.0-cpu-d101620-4c44c0
```

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by ThreadDao** [comment]
try to new milvus client like this:
```
# from milvus import Milvus, DataType
# from  locust import TaskSet
# MILVUS_HOST = "localhost"
# MILVUS_PORT = 19530
# print("asasasssss")
# client=Milvus(MILVUS_HOST, MILVUS_PORT, try_connect=False, pre_ping=False)
# print(client.list_collections())
```

**Comment by cos120** [comment]
locust use gevent which has conflict with grpc, I enable gevent by adding follow code between `import locust` and `import milvus`, it works out. my milvus version is 0.10.4.
```python
import grpc._cython.cygrpc
grpc._cython.cygrpc.init_grpc_gevent()
import grpc.experimental.gevent as grpc_gevent
grpc_gevent.init_gevent()
```

**Comment by shengjun1985** [comment]
If you have more questions, please continue to contact our community.
