### ISSUE TITLE
Want to insert more info into a collection

### ISSUE THREAD

**Issue by b06180618** [milvus-io/milvus#4558]
**Please state your issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I wish I could use Milvus to do [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by fishpenguin** [comment]
In milvus-0.11.x, we support insert scalar fields with vectors. And the type of scalar fields includes int and float.

**Comment by shengjun1985** [comment]
If you have more questions, please continue to contact our community.
