### ISSUE TITLE
Very Low QPS on 75000000 vectors(128 dimension)

### ISSUE THREAD

**Issue by owlwang** [milvus-io/milvus#4566]
We've tried create 75 million vectors(128 dimension) database, using the following params:

index: IVFSQ8
nlist: 32768 (according to the formula 4 * sqrt(total_vector_number))
segment_row_limit: default value (524288)

and modify the milvus.conf change the cache_size to 30GB.

We use wrk to test the QPS of the web API We can only get 10 QPS. (nprobe = 16)
and CPU utilization only 65%

Is this normal?

Do you have any suggestions for optimization？

<img width="1531" alt="CPU" src="https://user-images.githubusercontent.com/13383393/103602773-d3d29e00-4f47-11eb-8c03-a76a40b2339e.png">
<img width="1133" alt="wrk" src="https://user-images.githubusercontent.com/13383393/103602777-d59c6180-4f47-11eb-9dce-91eca258e8ec.png">

**Method of installation**
- Docker/cpu

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)
AWS c5d.9xlarge ( 36cpu 72GB memory )

search_vector.lua:
```lua
math.randomseed(os.time())
math.random(); math.random(); math.random()

function randomVector(length)
    if not length or length <= 0
    then
        return ''
    else
        if length > 1
        then
            return math.random() .. ',' .. randomVector(length - 1)
        else
            return math.random()
        end
    end
end

request = function()
    local vectors = randomVector(128)
    local qsl = '{"query":{"bool":{"must":[{"vector":{"m_vec":{"topk":15,"values":[[%s]],"metric_type":"L2","params":{"nprobe":16}}}}]}},"fields":["m_id"]}'

    wrk.method = "GET"
    wrk.body = string.format(qsl, tostring(vectors))
    wrk.headers["Content-Type"] = "application/json"
    return wrk.format()
end
```

**Comment by shengjun1985** [comment]
> nlist: 32768 (according to the formula 4 * sqrt(total_vector_number))

It should be 4 * sqrt(segment_row_limit).

> segment_row_limit: default value (524288)

If your data is static, you can set it as large as possible (the max value is 4 × 1024 × 1024).

In addition, merging multiple queries instead of only one query at a time can improve query performance.

**Comment by owlwang** [comment]
About nlist, maybe I misunderstood the meaning of the document, but maybe it can be improved?

https://milvus.io/cn/docs/v0.11.0/performance_faq.md?%E5%BA%94%E5%A6%82%E4%BD%95%E8%AE%BE%E7%BD%AE-IVF-%E7%B4%A2%E5%BC%95%E7%9A%84-%3Ccode%3Enlist%3Ccode%3E-%E5%92%8C-%3Ccode%3Enprobe%3Ccode%3E-%E5%8F%82%E6%95%B0%EF%BC%9F
「一般来说，推荐值为 4 × sqrt(n)，其中 n 为数据集的向量总条数。」

Thank you for your quick response.

**Comment by shengjun1985** [comment]
n should be min(segment_row_limit, row_count).
We will fix the DOC. Thank you very much.

**Comment by owlwang** [comment]
We've tried re-create 75 million vectors(128 dimension) database, the same hardware and software.

**even worse than the above params.**

index: IVFSQ8
segment_row_limit": 4194304
nlist: 8192 (according to the formula 4 * sqrt(segment_row_limit))

**We can only get 2.8 QPS. (nprobe = 16)**

and CPU utilization only 9%


<img width="1172" alt="wrk2" src="https://user-images.githubusercontent.com/13383393/103617360-15c00c00-4f69-11eb-8e20-1603a61aa8ad.png">


<img width="1493" alt="cpu2" src="https://user-images.githubusercontent.com/13383393/103617346-122c8500-4f69-11eb-9c04-283587163226.png">

**Comment by yhmo** [comment]
Theoretically, big segment should get better performance than small segment.
We need to do some test on our local machine firstly.

**Comment by shengjun1985** [comment]
Sorry, I just found that you are using multi client testing.
On 0.11.0, the server has not done query merging. So the performance won't be good in that case.
If you don't care about attribute filtering, it's recommended to use 0.10.x.
However, the low CPU utilization should be investigated.

**Comment by owlwang** [comment]
We are testing the 0.10.4 now.
Will report the performance later.

**Comment by owlwang** [comment]
We use milvus 0.10.4 to build the 75000000 vectors(128 dimension) database.
nlist: 8192
index: IVF_SQ8
index_file_size: 4096

use the wrk to test the qps 
use 32 connections:
we get **1500** qps
use 1 connection:
we get **184** qps

I think there should be some problems in Milvus version 0.11

<img width="1100" alt="milvus10" src="https://user-images.githubusercontent.com/13383393/103640741-88da7a00-4f8b-11eb-94c8-22471e20c072.png">
<img width="1085" alt="milvus10_1" src="https://user-images.githubusercontent.com/13383393/103641089-23d35400-4f8c-11eb-855c-7db51d44322b.png">

And CPU 30% utilization:
<img width="1478" alt="CPU" src="https://user-images.githubusercontent.com/13383393/103641149-3f3e5f00-4f8c-11eb-9f71-fa7f840651c7.png">

```lua
math.randomseed(os.time())
math.random(); math.random(); math.random()

function randomVector(length)
    if not length or length <= 0
    then
        return ''
    else
        if length > 1
        then
            return math.random() .. ',' .. randomVector(length - 1)
        else
            return math.random()
        end
    end
end

request = function()
    local vectors = randomVector(128)
    local qsl = '{"search":{"topk":15,"vectors":[[%s]],"params":{"nprobe":16}}}'
    wrk.method = "PUT"
    wrk.body = string.format(qsl, tostring(vectors))
    wrk.headers["Content-Type"] = "application/json"
    return wrk.format()
end
```

**Comment by yhmo** [comment]
I do some test on my machine, to compare performance between 0.11.1 and 0.10.5:

```
hardware:
Intel i7-8700 CPU 3.20GHz, 12 processors
64GB memory
Nvidia GeForce GTX 1660  6GB memory
SSD disk

dataset:
10000000 vectors, dimension = 128
5 segments, each segment is 1GB

index:
IVF_SQ8, nlist = 8192

query parameter:
nq = 1, topk = 10, nprobe = 32

```

Performance of 0.11.1:
```
Insert time cost: 201 seconds
Build index time cost: 442 seconds
1 client performs 100 queries: qps = 153
50 client, each client performs 20 queries: qps = 196
```

Performance of 0.10.5:
```
Insert time cost: 138 seconds
Build index time cost: 421 seconds
1 client performs 100 queries: qps = 137
50 client, each client performs 20 queries: qps = 684
```

Since 0.10.x can combine similar queries into one query, we can see the qps of 50 clients is much better than 0.11.1

**Comment by owlwang** [comment]
I don't think it's the problem query merging.

When I query on Milvus 0.11.0 the QPS is very low，It can't even be used normally in the production environment. Even I use your parameters (see above test)

But after I switch to version 0.10, even single connection QPS can reach **184**, 32 connection can reach **1500** 

Under the same hardware conditions, such a gap（10 -> 184/1500） cannot be explained by merging queries

**Comment by yhmo** [comment]
Last night I test 0.11.0(cpu version) with same workflow:

```
hardware:
  Intel i7-8700 CPU 3.20GHz, 12 processors
  64GB memory
  Nvidia GeForce GTX 1660  6GB memory
  SSD disk

dataset:
  10000000 vectors, dimension = 128
  5 segments, each segment is 1GB

index:
  IVF_SQ8, nlist = 8192

query parameter:
  nq = 1, topk = 10, nprobe = 32

milvus config:
  cpu cache: 30GB
```

Performance of 0.11.0(cpu version):
```
Insert time cost: 1552 seconds
Build index(by cpu) time cost: 16250 seconds
1 client performs 100 queries: qps = 37
50 client, each client performs 20 queries: qps = 49
```

**Comment by yhmo** [comment]
We can notice the cpu build index time cost is 16250 seconds (4.5 hours), so I think the possible reason of your low qps is:
some segments not yet finish index, milvus use raw vectors to do brute-search.

**Comment by owlwang** [comment]
Thank you for the test.
I'm pretty sure we've built the index because the .idx file for each segment has been generated.

Also how to  modify the  **index_file_size** in **0.11**? The official document only mentions **segment_ row_ limit**

Can you try to build the db with following params and test again?

index: IVFSQ8
segment_row_limit": 4194304
nlist: 8192 (according to the formula 4 * sqrt(segment_row_limit)) (you may need change this value)

**Comment by yhmo** [comment]
Milvus has two build index ways:
- pre-define index type, let background work thread build index automatically
   1. create a collection
   2. pre-define index type by create_index()
   3. insert data
   4. once a segment is full, the background work thread will build index for this segment automatically
   5. if you perform search(), build index thread may still in processing, some segments have no index, yet. Milvus will use raw vector data to do brute-search for these segments.

- build index after all data is inserted
   1. create collection
   2. insert all data
   3. call create_index() to build index for the collection, after all segments index is built, the create_index() return. it make sure all segments have index.
   4. client call search(), since all segments have index, milvus will use index to do search.

**Comment by yhmo** [comment]
My test last night is almost same parameter with you:
IVFSQ8, segment_row_limit=4000000, nlist=8192

**Comment by yhmo** [comment]
For 0.10.x, use index_file_size to control segment size.
For 0.11.x, use segment_row_limit to control segment size.

**Comment by owlwang** [comment]
My workflow is 2. build index after inserting all data. 

I'm very sure that all the index are finished because I was watching the CPU utilization and the index progress by the number of .idx files.

**Comment by owlwang** [comment]
1. cache_size = 30GB (So all the index data in memory)
2. All the tests are completed by using the wrk to request the web API
3. All the tests are done with the index completed(I'm very sure).
4. All the tests were tested more than five times and got the best results.


| Milvus Version | nlist | segment_row_limit | index_file_size | QPS |
|----------------|-------|-------------------|-----------------|-----|
| 0.11.0         | 32768 | 524288            | -               | 10  |
| 0.11.0         | 8192  | 4194304           | -               | 2.8 |
| 0.10.4         | 8192  | -                 | 4096               | 184（single connection） |
| 0.10.4         | 8192  | -                 | 4096               | 1500（32 connection） |

**Comment by yhmo** [comment]
Ok, then maybe the same reason with #4208. 
We need to check whether your machine is numa architecture. With numa, Docker cannot guarantee that the CPU resources and memory resources are divided into the same numa node, which will cause performance degradation.


- Firstly print numa information in cmdline:
`lscpu`
If the machine is NUMA, this command will print something like:
```
NUMA node 0 cpu: 0,2,4,6,8......
NUMA node 1 cpu: 1,3,5,7,9......
```
That means the machine has two NUMA nodes, the "0" node owns cpu 0,2,4,6,8 cpu, the "1" node owns cpu 1,3,,5,7,9

**Comment by owlwang** [comment]
Our test environment is Amazon's EC2
Ubuntu 18.04
AWS c5d.9xlarge ( 36cpu 72GB memory )

**Comment by yhmo** [comment]
So, your machine is not numa. Exclude this reason.
Could you do the following step to generate a log file for me:
1. restart milvus server
2. one client to call load_collection() and then call search() three times
3. go to the docker container to copy log file(newest generated) "/var/lib/milvus/logs/xxx.log" and send to me

**Comment by wineternity** [comment]
I found the QPS is low below 10 is beacuse the query contains the field, each search need to ` Get entity by id in segment 20107`,  without the field the qps can reach 100req/s

**Comment by yhmo** [comment]
> I found the QPS is low below 10 is beacuse the query contains the field, each search need to ` Get entity by id in segment 20107`, without the field the qps can reach 100req/s

The 0.11.0 filtering search is not optimized before we abandon it. Now the v2.0 also can support filtering search, you can try 2.0.
