### ISSUE TITLE
migrate milvus into sharding + replica architecture

### ISSUE THREAD

**Issue by godlockin** [milvus-io/milvus#4570]
We are using milvus to do some vector call back & calculations on some NER, searching and recommendation jobs, but as the milvus is more like a singleton database whose collections may have several shardings

We need to maintain our own load-balance to handle the requests waves, in case of the instance overload made whole system crash.

Maybe it will be quite helpful to make it more distribution, e.g. take the similar architecture like Elasticsearch or other solutions?

I'm not quite familiar with the data structure of milvus, so, maybe the main challenge was to ensure the data consistency?

**Comment by XuPeng-SH** [comment]
@godlockin 
In the past, we had a sharding solution "Mishards" to support sharding requirements. But it has stopped updating after 0.11.x. We have a new awesome distributed system under development, which will be launched in a few months.

**Comment by anvuongb** [comment]
@XuPeng-SH hi thanks for the answer, can you share more information on the distributed system?

**Comment by yhmo** [comment]
Hi anvuongb,
We decide to stop maintain for 0.11.x because we need to redesign the architecture to let milvus be more powerful and cloud-native. We have finished basic design and framework of the new architecture, we plan to public all the design doc and base source code in the Feb. Please stay tuned.

**Comment by jmichaelsilva** [comment]
Does this mean that mishards will be discontinued?
I just deployed Milvus v0.10.5 with mishards.

**Comment by yhmo** [comment]
> Does this mean that mishards will be discontinued?
> I just deployed Milvus v0.10.5 with mishards.

We will continue maintain milvus 0.10.x and its mishards.

**Comment by Maslino** [comment]
May I ask what's the recent progress of the new awesome distributed system?

**Comment by weidezhang** [comment]
yes, is there a design document for that? looking forward to try it. thx

**Comment by yhmo** [comment]
The Milvus v2.0 has been released in recent. Close this issue.
