### ISSUE TITLE
[0.10.4] Error in source code compilation

### ISSUE THREAD

**Issue by yuanpengpeng** [milvus-io/milvus#4583]
源码编译milvus时候,0.10.4分支------"Add lib/ directory to LD_LIBRARY_PATH  $ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:[Milvus root path]/core/milvus/lib"这一步没有找到lib目录位置

是位置变了么

**Comment by scsven** [comment]
@yuanpengpeng Please replace [Milvus root path] with your milvus path.

**Comment by yuanpengpeng** [comment]
> @yuanpengpeng Please replace [Milvus root path] with your milvus path.

可是我下载下来的milvus 0.10.4分支源码里面就没有core/milvus/lib这个目录,core下面没有milvus这个目录,搜索了一下也没有lib这个文件夹,github上看了一下分支也没有

**Comment by shengjun1985** [comment]
Before launching Milvus server, you need build it firstly.
Here is the reference [build-from-source](https://github.com/milvus-io/milvus/blob/0.10.4/INSTALL.md#build-from-source).

**Comment by shengjun1985** [comment]
If you have more questions, please continue to contact our community.
