### ISSUE TITLE
Error in search

### ISSUE THREAD

**Issue by gongxiaoze** [milvus-io/milvus#4584]
PS D:\project\sopic> python37 .\app.py
Using TensorFlow backend.
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

Addr [127.0.0.1:19530] search
Rpc error: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "GOAWAY received"
        debug_error_string = "{"created":"@1609988816.330000000","description":"Error received from peer ipv4:127.0.0.1:19530","file":"src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"GOAWAY received","grpc_status":14}"
>
        {'API start': '2021-01-07 11:04:59.424116', 'RPC start': '2021-01-07 11:04:59.426117', 'RPC error': '2021-01-07 11:06:56.330586'}

milvus version : 0.10.2
pymilvus: 0.2.14

**Comment by scsven** [comment]
@gongxiaoze It seems some error occurred on gRPC. Please provide the detail environment of Milvus, OS, CPU, GPU, and Memory.

**Comment by gongxiaoze** [comment]
> 
> 
> @gongxiaoze It seems some error occurred on gRPC. Please provide the detail environment of Milvus, OS, CPU, GPU, and Memory.


docker milvus version: 0.10.2
pymilvus: 0.2.14
gpu: no
mem: 50G (enough)

After restarted milvus. Once I call the search function, milvus exit. I try on the 0.10.5, it's same. 
I try a test in a empty collection,  it works, so strange.

**Comment by gongxiaoze** [comment]
> 
> 
> @gongxiaoze It seems some error occurred on gRPC. Please provide the detail environment of Milvus, OS, CPU, GPU, and Memory.
in the error file, some logs is recorded blow
[2021-01-08 08:49:23,313][ERROR][ENGINE][LoadDeletedDocs][taskloader_th] Failed to load deleted docs: std::bad_alloc
[2021-01-08 08:49:23,313][ERROR][ENGINE][Load][taskloader_th] Failed to load deleted docs from /var/lib/milvus/db/tables
/milvus/1609970781025587000/1609970782066358000

i check the path, it exists. how i do?

**Comment by shengjun1985** [comment]
This mistake is rare, and we can't see the reason for it at present.
Did you run Milvus on Ubuntu or on CentOS ?
Can you update Milvus to 0.10.5 ?

**Comment by gongxiaoze** [comment]
> 
> 
> This mistake is rare, and we can't see the reason for it at present.
> Did you run Milvus on Ubuntu or on CentOS ?
> Can you update Milvus to 0.10.5 ?

I have already try the 0.10.5, not work too. 
Yesterday I export all data and import to a new empty collection. now it works.  i suspect the data is causing the problem, but i can't prove that

**Comment by shengjun1985** [comment]
It is fine that it works.
This may be a bug in the old version. And we will continue to observe it.
If you find more questions in the future, please continue to contact our community.
