### ISSUE TITLE
Get similar list in a collection

### ISSUE THREAD

**Issue by shiyu22** [milvus-io/milvus#4586]
**Please state your issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**
 I wish I could use Milvus to do get_similar_list(), which can find the most similar list in the specified collection, and as you said return the toasters of all images.

**Describe the solution you'd like**
The feature request as [discussion4457](https://github.com/milvus-io/milvus/discussions/4457)

**Comment by yhmo** [comment]
Use #5215 to track this feature, close this one.
