### ISSUE TITLE
How about the process of developing "IVF & Graph" index

### ISSUE THREAD

**Issue by yuanpengpeng** [milvus-io/milvus#4587]
请问我看社区中说milvus会开发----"IVF & Graph：Milvus实现中"  是将倒排算法和基于图的索引算法结合么,现在进展到哪一步了,请问下这个思路是什么样的,想交流下

**Comment by shengjun1985** [comment]
This is a kind of index for those large segments.
When an IVF index built with a large 'nlist', searching the 'nprobe' nearest centroids may cost too many times.
So storing the 'nlist' centroids in a graph may improve the search performance.
Before implementation, we need to do many experiments to determine whether it is effective and in what cases.
At present, we are still in the experimental stage.
If you have relevant experience, it is pleasure to share with us.
