### ISSUE TITLE
Connection refused on tcp6 port 19121

### ISSUE THREAD

**Issue by Slash-Wong** [milvus-io/milvus#4588]
![异常信息](https://user-images.githubusercontent.com/38338543/103967189-71bea680-519c-11eb-8b06-7ec49a79ebb4.PNG)

也就是说19121端口服务不可用！！什么原因

**Comment by Slash-Wong** [comment]
但 19530端口服务正常

**Comment by BossZou** [comment]
@Slash-Wong , which version of milvus you used ? And may you provide your config file here?

**Comment by Slash-Wong** [comment]
最新的版本 0.11.0。下面是yml文件内容



`version: 0.6
cluster:
  enable: false
  role: rw
general:
  timezone: UTC+8
  meta_uri: mysql://xxx:xxxx@xxxx.xx.xxx.xxx:3306/milvus233 
network: 
  bind.address: 0.0.0.0
  bind.port: 19530
  http.enable: true
  http.port: 19123
storage:
  path: /var/lib/milvus
  auto_flush_interval: 1
wal:
  enable: true
  path: /var/lib/milvus/wal

cache:
  cache_size: 4GB
  insert_buffer_size: 1GB
  preload_collection:
  max_concurrent_insert_request_size: 2GB

gpu:
  enable: false
  cache_size: 1GB
  gpu_search_threshold: 1000
  search_devices:
    - gpu0
  build_index_devices:
    - gpu0
logs:
  level: info 
  trace.enable: true
  path: /var/lib/milvus/logs
  max_log_file_size: 1024MB
  log_rotate_num: 0
  log_to_stdout: false
  log_to_file: true

metric:
  enable: false
  address: 127.0.0.1
  port: 9091

`

**Comment by BossZou** [comment]
@Slash-Wong , you need update your config `http.port` to 19121 and then restart milvus.

**Comment by shengjun1985** [comment]
If you have more questions, please continue to contact our community.
