### ISSUE TITLE
Is the branch aarch64 the source code of ARM version of Milvus?

### ISSUE THREAD

**Issue by yuanpengpeng** [milvus-io/milvus#4590]
请问下aarch64这个分支是milvus的arm版本的源代码么,为什么里面还有x86_64-linux-gnu ,apt.repos.intel.com这种intel和x86的依赖

**Comment by yhmo** [comment]
The aarch64 is an experimental branch to build milvus under some kind of arm device, but we didn't make it work. To avoid confusion, we will delete this branch.
