### ISSUE TITLE
[BUG][CI] Domain host set not correct in CI

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#460]
**Describe the bug**
current host domain: `milvus-ci-1-single-cpu-milvus-engine.milvus.svc.cluster.local`
expected host domain: `milvus-ci-1-single-cpu-engine.milvus.svc.cluster.local`

**Steps/Code to reproduce behavior**

**Expected behavior**

**Environment details**
0.6.0

**Screenshots**

**Additional context**

**Comment by ZhifengZhang-CN** [comment]
Fix
