### ISSUE TITLE
While update from 0.10.3 to 0.10.5,  grafana did not show milvus service metrics。

### ISSUE THREAD

**Issue by yu-hailong** [milvus-io/milvus#4614]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
While update from 0.10.3 to 0.10.5,  grafana did not show milvus service metrics

![image](https://user-images.githubusercontent.com/17443614/104438174-a7afc080-55ca-11eb-877f-ac9f00135e4c.png)

We checked on Prometheus, it seems "cluster label" is not  delivered in 0.10.5

![image](https://user-images.githubusercontent.com/17443614/104438470-fcebd200-55ca-11eb-9b06-72a700b0fe84.png)

And in 0.10.3, it is OK
![image](https://user-images.githubusercontent.com/17443614/104438587-1f7deb00-55cb-11eb-89f9-5c3e39b5a2cb.png)

**Steps/Code to reproduce behavior**

**Expected behavior**

**Method of installation**
- [ X ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
0.10.5

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by fishpenguin** [comment]
Did you set metric.enable to true in server_config.yaml?

**Comment by yu-hailong** [comment]
> Did you set metric.enable to true in server_config.yaml?

Yes ,we did.

```
metric:
enable: true
address: kube-master-hzaz1-hubble.cloud.qiyi.domain
port: 27243
cluster_label: milvus_character
instance_label: ro:k8s_character
```

**Comment by yu-hailong** [comment]
the settings are same with 0.10.3.
we just update from 0.10.3 to 0.10.5 ,and the grafana does not work,
and we found the cluster label is not delivered.

**Comment by fishpenguin** [comment]
Can you get these metrics in prometheus(localhost:9090 by default) or pushgateway(localhost:9091 by default)?

**Comment by yu-hailong** [comment]
> Can you get these metrics in prometheus(localhost:9090 by default) or pushgateway(localhost:9091 by default)?

![image](https://user-images.githubusercontent.com/17443614/104679518-d5ab1700-5728-11eb-8257-eeca8a97efcf.png)

**Comment by yu-hailong** [comment]
And the following is the pushgateway

10.5
![image](https://user-images.githubusercontent.com/17443614/104682746-633e3500-5730-11eb-8d7f-b9cb665bc06c.png)

10.3
![image](https://user-images.githubusercontent.com/17443614/104682708-473a9380-5730-11eb-8af5-7fe986503d32.png)

**Comment by fishpenguin** [comment]
Did you change the way and flow of starting metrics? We just added a metric for internal use in 0.10.5, but not changed anything about metrics. And I can get these metrics in 0.10.5 with only one milvus instance in my machine.

**Comment by yu-hailong** [comment]
> Did you change the way and flow of starting metrics? We just added a metric for internal use in 0.10.5, but not changed anything about metrics. And I can get these metrics in 0.10.5 with only one milvus instance in my machine.
We can get metrics, but no cluster label.
Because we have some application using milvus, we have to use "cluster" to distinguish them

**Comment by yu-hailong** [comment]
we did setting as the follows, we want to distinguish them by cluster label.

```
metric:
enable: true
address: kube-master-hzaz1-hubble.cloud.qiyi.domain
port: 27243
cluster_label: milvus_character
instance_label: ro:k8s_character
```

**Comment by yu-hailong** [comment]
@fishpenguin Do you have any progress about the problem . This problem block us updating mivlus

**Comment by fishpenguin** [comment]
Sorry reply you so late.
In milvus, we didn't receive the "cluster_label" and "instance_label" in config as a parameter. So I don' think it would be effective when you set cluster_label and instance_label in config.
Did you do some modify about milvus metrics by your own?

**Comment by yu-hailong** [comment]
> Sorry to reply you so late.
> In milvus, we didn't receive the "cluster_label" and "instance_label" in config as parameters. So I don' think it would be effective when you set cluster_label and instance_label in config.
> Did you do some modify about milvus metrics by your own?

https://github.com/milvus-io/milvus/pull/3551/files

I asked jianghua, he did some modification and provider the cluster/instance label, and request merge
But it seems it was not merged into release version

**Comment by fishpenguin** [comment]
That is because this pr didn't pass dco, and was closed due to its inactivity.
Can you or he propose this pr again? If inconvenient, I can do this and add this feature in milvus-0.10.6.

**Comment by yu-hailong** [comment]
> activity.

**Comment by yu-hailong** [comment]
> That is because this pr didn't pass dco, and was closed due to its inactivity.
> Can you or he propose this pr again? If inconvenient, I can do this and add this feature in milvus-0.10.6.

I'll appreciate it very much if you could help me to do this

**Comment by yu-hailong** [comment]
by the way，do you know when 0.10.6 can be released?

**Comment by shengjun1985** [comment]
In plan, we will release 0.10.6 next month.
And if you want to use it as soon as possible, you can checkout the branch and compile it locally after that PR merged.
Reference:
[Install Milvus from Source Code](https://github.com/milvus-io/milvus/blob/master/INSTALL.md)

**Comment by shengjun1985** [comment]
@yu-hailong 
Would you like to create a new PR to 0.10.6?

**Comment by yu-hailong** [comment]
> @yu-hailong
> Would you like to create a new PR to 0.10.6?
you can do it instead of me, I know little about hwo to create PR.

**Comment by yu-hailong** [comment]
> In plan, we will release 0.10.6 next month.
> And if you want to use it as soon as possible, you can checkout the branch and compile it locally after that PR merged.
> Reference:
> [Install Milvus from Source Code](https://github.com/milvus-io/milvus/blob/master/INSTALL.md)

we checkout the 0.10.5 source ,and do merge  https://github.com/milvus-io/milvus/pull/3551/files ,
then following the step to recomiple source, but two errors happened, and we cannot find detail
the following error mean compile failed?

![image](https://user-images.githubusercontent.com/17443614/105441240-16fc7300-5ca3-11eb-86ff-ab1730436fc0.png)

**Comment by fishpenguin** [comment]
There are two scripts under milvus/core folder:
centos7_build_deps.sh and ubuntu_build_deps.sh
Most of dependencies are listed in the script.
Please be sure that these dependencies have been installed in your machine

**Comment by yu-hailong** [comment]
/data/milvus/milvus/core/src/index/knowhere/knowhere/index/vector_index/FaissBaseIndex.cpp:13:10: fatal error: fiu-local.h: No such file or directory
 #include <fiu-local.h>
          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/index/knowhere/CMakeFiles/knowhere.dir/knowhere/index/vector_index/FaissBaseIndex.cpp.o] Error 1



/data/milvus/milvus/core/src/index/knowhere/knowhere/index/vector_index/IndexIVF.cpp:25:10: fatal error: fiu-local.h: No such file or directory
 #include <fiu-local.h>
          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/index/knowhere/CMakeFiles/knowhere.dir/knowhere/index/vector_index/IndexIVF.cpp.o] Error 1

**Comment by shengjun1985** [comment]
It seems that your build param is wrong.
If you just want to build a release CPU version: ./build.sh -t Release
If you want to build a release GPU enable version: ./build.sh -t Release -g

**Comment by yu-hailong** [comment]
> It seems that your build param is wrong.
> If you just want to build a release CPU version: ./build.sh -t Release
> If you want to build a release GPU enable version: ./build.sh -t Release -g

I use “./build.sh -t Release” on centos 7， but failed and the error msg like this

**Comment by fishpenguin** [comment]
Can you try to use "./build.sh -t Release -i".

**Comment by yu-hailong** [comment]
> Can you try to use "./build.sh -t Release -i".
the error is same

**Comment by shengjun1985** [comment]
It may be a cmake dependency error. We will try to fix it later.
After error happens, you can try the following steps to solve it.

cd cmake_build/
make fiu_ep
cd ..
./build.sh -t Release

**Comment by yu-hailong** [comment]
> It may be a cmake dependency error. We will try to fix it later.
> After error happens, you can try the following steps to solve it.
> 
> cd cmake_build/
> make fiu_ep
> cd ..
> ./build.sh -t Release

Thank you, now building is sucessful.
the reason is that  python3 installed failed(꒦_꒦)

**Comment by yu-hailong** [comment]
> > @yu-hailong
> > Would you like to create a new PR to 0.10.6?
> > you can do it instead of me, I know little about hwo to create PR.

@fishpenguin  Will the function be merged into 0.11.x ?

**Comment by fishpenguin** [comment]
>@fishpenguin Will the function be merged into 0.11.x ?

0.11.x has been removed, and won't develop, so this won't be merged into 0.11.x.

**Comment by yu-hailong** [comment]
> > @fishpenguin Will the function be merged into 0.11.x ?
> 
> 0.11.x has been removed, and won't develop, so this won't be merged into 0.11.x.

Do you mean, the future version will begin with 0.12.0?

**Comment by shengjun1985** [comment]
> Do you mean, the future version will begin with 0.12.0?

We haven't decided yet.

**Comment by shengjun1985** [comment]
@yu-hailong
The PR is merged into master.
Please wait for 0.10.6 release.
And thank you for your contribution.
