### ISSUE TITLE
Mishards does not recover after failing one or more read-only servers.

### ISSUE THREAD

**Issue by jmichaelsilva** [milvus-io/milvus#4618]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Mishards does not recover after failing one or more read-only servers.

**Steps/Code to reproduce behavior**
I started some read-only nodes (pods) in a Kubernetes cluster (mishards configured with K8s service discovery). Then, I deleted some read-only pods

The following errors occurred:
![image](https://user-images.githubusercontent.com/65552708/104587179-4da01100-5645-11eb-8253-eb3e537a8b79.png)

And:
![image](https://user-images.githubusercontent.com/65552708/104587200-57c20f80-5645-11eb-9848-338f8efd8520.png)

After these errors, mishards cannot recover. I had to restart the mishards pod (it's bad for HA).

**Expected behavior**

**Method of installation**
- [ X ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
Google Kubernetes cluster (Container Optimazed OS with Docker):

1 mishards pod (8vcpu/15Gb)
1 writable pod (16vcpu/15Gb)
6 readonly pods (8/52Gb each pod)

- Milvus version (master or released version)
v0.10.5

**Configuration file**
```
mishards_config.yaml:
----
SQLALCHEMY_DATABASE_URI=mysql://milvus:###@#########:3306/milvus

MAX_WORKERS=50

DEBUG=false
SERVER_PORT=19530
WOSERVER=tcp://milvus-writable.milvus.svc.cluster.local:19530

DISCOVERY_CLASS_NAME=kubernetes
DISCOVERY_KUBERNETES_NAMESPACE=milvus
DISCOVERY_KUBERNETES_POD_PATT=.*-ro-servers-.*
DISCOVERY_KUBERNETES_LABEL_SELECTOR=tier=ro-servers
DISCOVERY_KUBERNETES_POLL_INTERVAL=10
DISCOVERY_KUBERNETES_IN_CLUSTER=True

TRACER_CLASS_NAME=jaeger
TRACING_SERVICE_NAME=mishards
TRACING_REPORTING_HOST=jaeger-agent.istio-system
TRACING_REPORTING_PORT=5775
```
```
server_config.yaml:
----
version: 0.5

cluster:
  enable: true
  role: rw

general:
  timezone: "UTC-3"
  meta_uri: mysql://milvus:####@########:3306/milvus

network: 
  bind.address: 0.0.0.0
  bind.port: 19530
  http.enable: false
  http.port: 19121

storage:
  path: "/var/lib/milvus"
  auto_flush_interval: 1

wal:
  enable: true
  recovery_error_ignore: true
  buffer_size: 512MB
  path: /var/lib/milvus/db/wal

cache:
  cache_size: 6GB
  insert_buffer_size: 6GB
  preload_collection: 

gpu:
  enable: false
  cache_size: 1GB
  gpu_search_threshold: 1000
  search_devices:
    - gpu0      
  build_index_devices:
    - gpu0

logs:
  level: debug
  trace.enable: true
  path: /var/lib/milvus/logs
  max_log_file_size: 1024MB
  log_rotate_num: 0

metric:
  enable: true
  address: prometheus-pushgateway.monitoring.svc.cluster.local
  port: 9091
```
```
readonly_server_config.yaml:
----
version: 0.5

cluster:
  enable: true
  role: ro

general:
  timezone: "UTC-3"
  meta_uri: mysql://milvus:####@########:3306/milvus

network: 
  bind.address: 0.0.0.0
  bind.port: 19530
  http.enable: false
  http.port: 19121

storage:
  path: "/var/lib/milvus"
  auto_flush_interval: 1

wal:
  enable: false
  recovery_error_ignore: true
  buffer_size: 512MB
  path: /var/lib/milvus/db/wal

cache:
  cache_size: 48GB
  insert_buffer_size: 2GB
  preload_collection: 

gpu:
  enable: false
  cache_size: 1GB
  gpu_search_threshold: 1000    
  search_devices:
    - gpu0
  build_index_devices:
    - gpu0

logs:
  level: debug
  trace.enable: true
  path: /var/lib/milvus/logs
  max_log_file_size: 1024MB
  log_rotate_num: 0

metric:
  enable: true
  address: prometheus-pushgateway.monitoring.svc.cluster.local
  port: 9091

```

**Screenshots**
Above

**Additional context**
https://github.com/milvus-io/milvus/issues/4469

**Comment by BossZou** [comment]
@jmichaelsilva , I cannot reproduce in my host machine. I launch three wo nodes and then remove two nodes, however I didn't  
 encounter any error.

**Comment by BossZou** [comment]
Before deleting ro nodes, Mishards search log is like:
![kctl-mishards-search-3-nodes](https://user-images.githubusercontent.com/40255591/105656378-07786680-5efd-11eb-8970-5bfc1dbc5b9f.png)

When deleting nodes, Mishards could delete pod group :
![kctl-mishards-delete-podsd](https://user-images.githubusercontent.com/40255591/105656441-2d057000-5efd-11eb-8058-eea408c89443.png)

After deleted, Mishards search log is like:
![kctl-mishards-1-node](https://user-images.githubusercontent.com/40255591/105656466-3ee71300-5efd-11eb-8980-baa1f12e64a4.png)

**Comment by jmichaelsilva** [comment]
@BossZou thanks for your reply.

Sometimes when you don't have clients requesting (search) mishards, then mishards work as you described. However, if you have some client requesting, then the error reported by me occurs.

Could you test with some clients requesting mishards?

**Comment by yhmo** [comment]
We recommend users use Milvus v2.0 to replace Mishards. Now the v2.0 rc4 has been released.
Inactivate and close.
