### ISSUE TITLE
Terms of must and must_not together are not working

### ISSUE THREAD

**Issue by tailtq** [milvus-io/milvus#4619]
**Please state your issue using the following template and, most importantly, in English.**
Combination of must and must_not is not working

**Describe the bug**
This is my dsl
`dsl = {
            "bool": {
                "must": [
                    {
                        "must_not": [
                            {
                                "term": {
                                    "object_uuid": [current_uuid]
                                }
                            }
                        ]
                    },
                    {
                        "must": [
                            {
                                "vector": {
                                    "vector": {"topk": topk, "query": vectors, "metric_type": metric_type}
                                }
                            },
                            {
                                "term": {
                                    "process_uuid": process_uuids,
                                },
                            },
                        ]
                    },
                ],
            },
        }`
By using this dsl, I received from search method the entities which violate the `must_not` condition but follow the term `process_uuid`.

**Expected behavior**
The expected result in my mind would be the combination of 3 conditions.

**Method of installation**
- [ ] Docker/cpu
- [x] Docker/gpu   →    milvusdb/daily-build:0.11.1-centos7-gpu-20210111
- [ ] Build from source

**Version**
- Milvus version 0.11.1

I'm not familiar with creating issue. Please tell me if I'm wrong in any points. Thank you guys so much.

**Comment by fishpenguin** [comment]
Which sdk did you use?

**Comment by fishpenguin** [comment]
This is a dsl bug when using "must_not" with must, we will fix this in 0.11.1 soon.

**Comment by tailtq** [comment]
Thanks

**Comment by shengjun1985** [comment]
Thanks for finding the problem.
The PR is merged. Please checkout the branch and compile it locally.
If you have more questions, please continue to contact our community.
