### ISSUE TITLE
Set the timeout response time

### ISSUE THREAD

**Issue by Lydia-Lv** [milvus-io/milvus#4620]
**Please state your issue using the following template and, most importantly, in English.**

**What would you like to be added ?**
I want to be able to set the timeout when a client connects to milvus server

**Why is this needed ?**
When the milvus server docker dies, it takes a long time（sometimes 20s are needed） to return

**Comment by jingkl** [comment]
For this question refer to the issue #4814

**Comment by scsven** [comment]
There is a parameter name `timeout` in pymilvus methods.
