### ISSUE TITLE
while delete one vector from rw node, it  can still be searched from ro node in 0.10.X

### ISSUE THREAD

**Issue by yu-hailong** [milvus-io/milvus#4625]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
While delete one vector from rw node, it  can still be searched from ro node in 0.10.X
will it be fixed in 0.10.6?

we have some case using 0.10.X, and the deletion synchronization is need.

**Steps/Code to reproduce behavior**

**Expected behavior**

**Method of installation**
- [X ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
0.10.3

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by BossZou** [comment]
@yu-hailong , How did you deploy your wr node and ro node ?

**Comment by yu-hailong** [comment]
> @yu-hailong , How did you deploy your wr node and ro node ?

1rw node + 3 ro node.  we do adding/deleting  vector through rw node, and query from ro node.
As I said, while we deleted some vector by id, I can not search it from rw node,
 but I can see it in query result while querying on ro node.

**Comment by BossZou** [comment]
@yu-hailong , if you deploy rw node and ro nodes individually, Milvus cannot make sure that ro nodes do not search the vectors deleted on rw node. If you need to solve this problem, you are recommended to use Mishards to deploy your Milvus cluster.

**Comment by yu-hailong** [comment]
> @yu-hailong , if you deploy rw node and ro nodes individually, Milvus cannot make sure that ro nodes do not search the vectors deleted on rw node. If you need to solve this problem, you are recommended to use Mishards to deploy your Milvus cluster.

We tried mishards, and found while ro down,  the query error rate will increase. we can not endure this
So we use rw domain(mapping 1 node) + ro domain(mapping 3 rode), and they using share file system to share data.
while querying, we use domain to keep high available.

And we found while adding vector from rw node, we can search it from ro node; Why  deletion synchronization can not be done like adding ?

**Comment by BossZou** [comment]
@yu-hailong, because once new data inserted, Milvus will store them in a new segment and add an new record in metadata. During serching, Milvus first scan metadata to decide which segments to be searched. However, if user deleted some vectors, there is no new record added into metadata, so ro node could not detect deletion behavior.

**Comment by yu-hailong** [comment]
thank you for your explanation. 
I know it is not a easy problem for resolving, 
Maybe some synchronization mechanism should be added, so rw node and ro node will do the same action while deleting.

**Comment by shengjun1985** [comment]
It should be fixed in branch 1.1
If you want to use it as soon as possible, you can checkout the branch and compile it locally.
Otherwise, please wait for the next release.

Reference:
[Install Milvus from Source Code](https://github.com/milvus-io/milvus/blob/1.1/INSTALL.md)
