### ISSUE TITLE
add similarity threshold param in search function to return results those similarities greater than it.

### ISSUE THREAD

**Issue by stawary** [milvus-io/milvus#4626]
**Please state your issue using the following template and, most importantly, in English.**

**What would you like to be added ?**
Add similarity threshold param in search function to return results those similarities greater than it.

**Why is this needed ?**
In some situations, I can't determine the top_k param. Some questions may have many similar questions, when query it should use a large top_k, while some use a small top_k. 
One solution may be that I can use a very large top_k such as 100, then handle the results and drop the results whose similarities are smaller than a threshold. The best solution is that you add a threshold param is search function, and further more, you can add paging function, just like LIMIT in sql. In this way, milvus can do the job like baidu search engine, when search a certain question, return the related websites and can invoke the api in batches——paging.
I will be appreciated if you can take my suggestions into consideration. My company is carrying out a QA system based on expert experience, and I am very delighted to find milvus as a solution, thank you for your job.

**Comment by yhmo** [comment]
It sounds like a "search by range" feature. And for the "paging" function, there is an issue about this: #3851

**Comment by shengjun1985** [comment]
＠stawary
Thank you for your concern for our project.
We are currently considering the feature of "range query" and want to collect some actual requirements.
Would you like to help us?
(1) What size is your data set (row_count, dim)?
(2) What metric type and indexes do you usually used (L2, IP, ...; FLAT, IVF_FLAT, ...)?
(3) Usually, the query is a batch or singal? (nq=?)
(4) If the distance range is specified, how large will be the result set?
(5) Will your vectors be deleted, or do you need to filter by attributes?
(6) Is there a problem if the result set is not sorted?
(7) Is there a requirement for recall rate?
Thank you very much.

**Comment by stawary** [comment]
@shengjun1985 
Thank you for your quick reply. 
(1) The expert experience data set would be too large because it's hard to collect. I think 100k rows and 1000 dims may be enough.
(2) I am not familiar with the metric type and indexes you list ...
(3) Usually the query is a batch.
(4) The result set will be less than 100 rows, most situations 10 rows may be enough for expert experience data.
(5) When the QA data is not good, we may delete the QA data and vector. In my project, with the postgreSQL db, I don't need filter by attributes.
(6) You'd better return sorted data.
(7) The recall rate is import for me.

**Comment by shengjun1985** [comment]
@stawary
　　I see. Thanks a lot.
　　The most difficulty of "range query" is that the result set is uncontrollable and may be very large (for example 100000). And this will be a challenge to the merging and transmission. The feature "range query" should spend a lot of resource to solve it.
　　From your usage, you use batch query, the result set is not large (10 ~ 100), and there is a need for sorting, then using the current "top-k query" is a good solution. In this way, the client will have some extra work, but it is simple.
　　Finally, it should be very efficient for Milvus to process only 100000 rows of data. If you really care about the recall rate, you may even query by FLAT. If you have more questions, please continue to contact our community.

**Comment by stawary** [comment]
@shengjun1985  Got it, thank you very much.
