### ISSUE TITLE
How to configure Milvus according to my own computer

### ISSUE THREAD

**Issue by sky186** [milvus-io/milvus#4639]
1、一次插入到 milvus 表中的数据  不超过 256M，是否是如下位置自定义修改大小，
buffer_size必须在[64，4096]（MB）范围内
wal:
  enable: true
  recovery_error_ignore: false
  buffer_size: 256MB
  path: /var/lib/milvus/wal

2、建立索引搜索阶段 **_INDEX_FILE_SIZE** = 1024  # max file size of stored index

https://www.milvus.io/cn/blogs/2020-2-16-api-setting.md/  参数文档介绍是设置1024
这里 设置64 等小一点的值（2048向量），正常不报错，**这里设置的大小对 精度速度的影响，如何设置一个合适的值？**

    WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 131072 B, highwater 268977408 B)
    Faiss assertion 'err == cudaSuccess' failed in void faiss::gpu::freeMemorySpace(faiss::gpu::MemorySpace, void*) at gpu/utils/MemorySpace.cpp:72; details: Failed to cudaFree pointer 0x7efdec000000 (error 1 invalid argument)

3、congfig文件 cpu ,gpu 大小容量如何根据各自电脑设置，对搜索的影响，根据不同规模数据会不同设置吗
例如四卡 v100 (32G) 显卡 
 cpu  和 gpu 几个 size 设置的 标准是什么， （gpu 多卡，也许有其他人的任务占用，会怎么样）

cache:
  cache_size: 128GB
  insert_buffer_size: 4GB
  preload_collection:

gpu:
  enable: true
  cache_size: 4GB
  gpu_search_threshold: 1000
  search_devices:
    - gpu0
  build_index_devices:
    - gpu0

@shengjun1985 
 您好如果您有空的话希望可以回复一下，谢谢您 ^^

**Comment by yhmo** [comment]
1. The max data size of one inset action is 256MB, this is a const value defined in source code, can not be changed from outside.
The wal.buffer_size in server_config.yaml is only for wal function, no need to change it.

2. Typically, index_file_size=1024MB is good for most of cases. If the value is too small, it could slow down the search performance. For accuracy, we didn't do much experiment to verify this. For my opinion, accuracy is more depend on search parameter 'nprobe' .
