### ISSUE TITLE
milvus-em use domian name to connect milvus without requiring both the host and port

### ISSUE THREAD

**Issue by bitxinyu** [milvus-io/milvus#4643]
**Is your feature request related to a problem? Please describe.**
we use k8s to manage web services. The addresses of many web services are appended to a common path.
eg. milvus restful api has been mapping to http://dev.company.com/milvus-service-restful
but milvus-em  requiring both the host and port to connect milvus.
I wish I could connect to the service with only the domain name.

set `host:http://dev.company.com/milvus-service-restful` and `port: 80` or` port:19121` didn't work 
milvus v0.10.5
milvus-em v0.4.1

**Comment by shanghaikid** [comment]
@bitxinyu can you access http://dev.company.com/milvus-service-restful/state from your browser ?

**Comment by bitxinyu** [comment]
> @bitxinyu can you access http://dev.company.com/milvus-service-restful/state from your browser ?

yes, of  course. I have tested all the restfull api, and they all work.
![2021-01-25_10-21](https://user-images.githubusercontent.com/11964010/105654779-abf8a980-5ef9-11eb-9a3c-cf6f172efa3b.png)

when I use milvus-em to connect milvus,  `port` just be appended to `http://dev.company.com/milvus-service-restful`
![2021-01-25_10-26](https://user-images.githubusercontent.com/11964010/105654979-1c9fc600-5efa-11eb-9432-039212365680.png)

**Comment by nameczz** [comment]
For now, we always add port after host to call restful api. 
Host: http://dev.company.com/milvus-service-restful.
Port: 19121
Restful Api: http://dev.company.com/milvus-service-restful:19121/state is working correct?

**Comment by nameczz** [comment]
> > @bitxinyu can you access http://dev.company.com/milvus-service-restful/state from your browser ?
> 
> yes, of course. I have tested all the restfull api, and they all work.
> ![2021-01-25_10-21](https://user-images.githubusercontent.com/11964010/105654779-abf8a980-5ef9-11eb-9a3c-cf6f172efa3b.png)
> 
> when I use milvus-em to connect milvus, `port` just be appended to `http://dev.company.com/milvus-service-restful`
> ![2021-01-25_10-26](https://user-images.githubusercontent.com/11964010/105654979-1c9fc600-5efa-11eb-9432-039212365680.png)

For now, we always add port after host to call restful api.
Host: http://dev.company.com/milvus-service-restful.
Port: 19121
Restful Api: http://dev.company.com/milvus-service-restful:19121/state is working correct?

**Comment by bitxinyu** [comment]
> @nameczz 
> For now, we always add port after host to call restful api.
> Host: http://dev.company.com/milvus-service-restful.
> Port: 19121
> Restful Api: http://dev.company.com/milvus-service-restful:19121/state is working correct?

Looks like something is wrong.
here is result of port 19121 and port 80  .
![2021-01-25_12-19_1](https://user-images.githubusercontent.com/11964010/105661447-6099c780-5f08-11eb-8672-ffffa0be8a1e.png)
![2021-01-25_12-20](https://user-images.githubusercontent.com/11964010/105661460-668fa880-5f08-11eb-8587-df44d4e5079f.png)

and without port
![2021-01-25_12-19](https://user-images.githubusercontent.com/11964010/105661500-7d35ff80-5f08-11eb-8f80-74cefcc780f9.png)

in my opinion, `port 19121` has been mapping to http://dev.company.com/milvus-service-restful,
We should not add the port number after the new address,the port number is redundant.

**Comment by nameczz** [comment]
> > @nameczz
> > For now, we always add port after host to call restful api.
> > Host: http://dev.company.com/milvus-service-restful.
> > Port: 19121
> > Restful Api: http://dev.company.com/milvus-service-restful:19121/state is working correct?
> 
> Looks like something is wrong.
> here is result of port 19121 and port 80 .
> ![2021-01-25_12-19_1](https://user-images.githubusercontent.com/11964010/105661447-6099c780-5f08-11eb-8672-ffffa0be8a1e.png)
> ![2021-01-25_12-20](https://user-images.githubusercontent.com/11964010/105661460-668fa880-5f08-11eb-8587-df44d4e5079f.png)
> 
> and without port
> ![2021-01-25_12-19](https://user-images.githubusercontent.com/11964010/105661500-7d35ff80-5f08-11eb-8f80-74cefcc780f9.png)
> 
> in my opinion, `port 19121` has been mapping to http://dev.company.com/milvus-service-restful,
> We should not add the port number after the new address,the port number is redundant.
Yeah, i agree with that. But we need separate host and port in v0.4.1 and we will change it in next release.

**Comment by nameczz** [comment]
@bitxinyu Yeah, i agree with that. But we need separate host and port in v0.4.1 and we will change it in next release.

**Comment by bitxinyu** [comment]
Great ! Thanks for your work, I'm looking forward to the next version.

**Comment by nameczz** [comment]
> Great ! Thanks for your work, I'm looking forward to the next version.

We released v0.4.2 milvus-em and you can have a try. Thanks for your suggestion and any more advices is welcome!

**Comment by bitxinyu** [comment]
> > Great ! Thanks for your work, I'm looking forward to the next version.
> 
> We released v0.4.2 milvus-em and you can have a try. Thanks for your suggestion and any more advices is welcome!

why milvus-em v0.4.2 need port and milvus port ? UI of v0.4.2 looks like v0.5.0. and both port and milvus port should be given.
the size of milvus-em v0.4.2 much larger than v0.4.1. 
![image](https://user-images.githubusercontent.com/11964010/109471599-eda5e280-7aab-11eb-8c65-e70d23da63b3.png)

**Comment by nameczz** [comment]
> why milvus-em v0.4.2 need port and milvus port ? UI of v0.4.2 looks like v0.5.0. and both port and milvus port should be given.
> the size of milvus-em v0.4.2 much larger than v0.4.1.
> ![image](https://user-images.githubusercontent.com/11964010/109471599-eda5e280-7aab-11eb-8c65-e70d23da63b3.png)
Sorry for that, my cicd program has some problem, now i fixed it and released v0.4.2 again.

**Comment by bitxinyu** [comment]
@nameczz Thanks for your work! Upgrade to the latest version and everything works fine .

**Comment by shengjun1985** [comment]
Thanks all.
