### ISSUE TITLE
Want to know the impact of partitiontag on query performance

### ISSUE THREAD

**Issue by pjhope** [milvus-io/milvus#4650]
1、50万60维向量  建立IVF_SQ8索引    查询一次 topK200  cpu机器  16c 理论耗时在多少毫秒比较正常？（nlist设置为1000）
 （2ms  5ms  10ms  15ms）

2、以下三种情况都是  建立IVF_SQ8索引，查询一次 topK200 ，cpu机器 16c
      a. 50万60维向量  不设置partitionTag           
      b. 50万60维向量  设置partitionTag(100个)   查询时指定 1个partitionTag
      c. 50万60维向量  设置partitionTag(100个)   查询时指定 10个partitionTag
      d. 50万60维向量  设置partitionTag(100个)   查询时不指定partitionTag

问题1：想估算下自己设置的参数是否有问题，或者与开发者预期的性能是否相符。
问题2：想了解下同样的数据，设置partitionTag和不设置partitionTag的查询速度；
            据测试发现（d耗时 >> c耗时 >> b耗时 ~ a耗时），d的耗时是远大于a的耗时（感觉每个partitionTag串行去查，耗时线性增长），是否符合预期？

**Comment by yhmo** [comment]
500000 vectors with 60 dimensions. Single search performance typically is a couple of milliseconds.
I did same test on my machine (i7-8700 CPU @ 3.20GHz 12 cores).
index=IVF_SQ8, nlist=1000
search parameters: nq=1, nprobe=32, topk=200
search performance: 2ms~3ms

Search performance mainly relate with the following factors:

- how many vectors
- how many segments
- vector dimensions
- index parameters
- search parameters
- CPU ability
- remote meta service(MySQL) latency

**Comment by shengjun1985** [comment]
It is sure that more partitions lead to more segment number, and lead to worse performance.
Please refer to [Partition](https://milvus.io/docs/v0.10.5/storage_concept.md?Partition).

**Comment by yhmo** [comment]
As we know, partition is a subset of collection, multiple partitions split data into pieces. You create 100 partitions, if you insert 5000 vectors to each partition, that means the collection will totally has 100 segments. The search performance result is make sense: d >> c >> b ~ a

**Comment by shengjun1985** [comment]
If you have more questions, please continue to contact our community.
