### ISSUE TITLE
Deleted vector still returns in search

### ISSUE THREAD

**Issue by tailtq** [milvus-io/milvus#4656]
**Please state your issue using the following template and, most importantly, in English.**
After deleting vector in Milvus, I still encounter the deleted vector in search result in big set.

Note: I already visited at [Issue 4200](https://github.com/milvus-io/milvus/issues/4200) a week ago but see no different.

**Steps/Code to reproduce behavior**
1. Insert around 1M vectors into Milvus.
2. Generate random vector using numpy with seed and proceed searching (top k = 3)
3. Delete the second id returned
4. Search again with the same input
5. Second id still returns in search

**Expected behavior**
Deleted id should not be returned from Milvus

**Method of installation**
- [ ] Docker/cpu
- [x] Docker/gpu
- [ ] Build from source

**Milvus version (master or released version)**
milvusdb/daily-build:0.11.1-centos7-gpu-20210113

Please take a look. Thank you guys.

**Screenshots**
This image goes along with my code below. This is the result from my search.
https://i.imgur.com/kDXnW4M.png

**My code**
```
import numpy as np

from milvus import Milvus, DataType

_HOST = 'host'
_PORT = 'port'
client = Milvus(_HOST, _PORT)

collection_name = 'test_search_error'

# if collection_name in client.list_collections():
#     client.drop_collection(collection_name)
#
# collection_param = {
#     "fields": [
#         {"name": "embedding", "type": DataType.FLOAT_VECTOR, "params": {"dim": 512}},
#     ],
#     "segment_row_limit": 4096,
#     "auto_id": True
# }
# client.create_collection(collection_name, collection_param)
#
# for i in range(100):
#     vectors = []
#
#     for j in range(10000):
#         vectors.append(list(np.random.random((512,))))
#
#     ids = client.insert(collection_name, entities=[
#         {"name": "embedding", "values": vectors, "type": DataType.FLOAT_VECTOR},
#     ])
#     print(f"INSERT {i}")
#     client.flush([collection_name])

result = client.delete_entity_by_id(collection_name, ids=[1611472225837707474])
client.flush([collection_name])

for e in client.get_entity_by_id(collection_name, [1611472225837707474]):
    print(e)

np.random.seed(10)
query_embedding = list(np.random.random((512,)))
query_hybrid = {
    "bool": {
        "must": [
            {
                "vector": {
                    "embedding": {"topk": 3, "query": [query_embedding], "metric_type": "L2"}
                }
            }
        ]
    }
}
results = client.search(collection_name, query_hybrid, fields=["embedding"])

print("----------search----------")
for entities in results:
    for topk_film in entities:
        current_entity = topk_film.entity
        print("- id: {}".format(topk_film.id))
        print("- distance: {}".format(topk_film.distance))
        print("\n")

**Comment by BossZou** [comment]
@tailtq Version 0.11 is no longer actively maintained, please change to using version 0.10 or waiting for our next version.

**Comment by tailtq** [comment]
@BossZou Sorry, can I ask the reasons why you guys reverted from version 0.11 to 0.10.5? Because version 0.11 has the DSL feature that I want the most.

**Comment by yhmo** [comment]
@tailtq 
Please read the announcement: https://github.com/milvus-io/milvus/discussions/4640
The main reason is to make milvus more cloud-native. The functions of 0.11.x/0.10.x also will be considered and implemented in the new architecture.

**Comment by tailtq** [comment]
@yhmo Thanks, so I will close this issue!
