### ISSUE TITLE
The definition of "Recall"

### ISSUE THREAD

**Issue by lingzhengyou** [milvus-io/milvus#4664]
milvus官网中对于召回率的定义是：返回的结果集中正确的结果所占的比重。
但实际上准确率(Accuracy),精确率(Precision),召回率(Recall) 是机器学习(ML),自然语言处理(NLP),信息检索(IR)等领域,评估(Evaluation)的几个指标
![image](https://user-images.githubusercontent.com/53212318/105958743-fde62e80-60b5-11eb-87cf-cd1d0a431f99.png)

1、精确率(precision)的公式是P = \frac{TP}{TP+FP},它计算的是所有"正确被检索的item(TP)"占所有"实际被检索到的(TP+FP)"的比例.
大白话就是“ 你预测为正例的里面有多少是对的”，精确率的基数是检索返回的样例。
2、召回率(recall)的公式是R = \frac{TP}{TP+FN},它计算的是所有"正确被检索的item(TP)"占所有"应该检索到的item(TP+FN)"的比例。
大白话就是“正例样本里你的预测正确了多少”，召回率的基数是样本里的所有正例样本。
3、准确率是针对我们原来所有样本而言的，它表示的是所有样本有多少被准确预测了

例如做一个检索，符合要求的数据是200条，结果我返回了300条数据，300条结果数据理有150条符合要求，那么这里精确率=150/300=50%，召回率=150/200=75%。

官网定义的召回率在这里应该是属于精确率，这是专业术语，建议官网和行业保持一致，以免误解，不至于有人会问：为什么milvus和我全网查询的召回率的定义不一样？难道全网都错了就milvus对了？

**Comment by shengjun1985** [comment]
In the Milvus TOPK interface, the number of the returned results is usually equal to the number of the expected results. In such cases, "FN = FP", thus precision = recall.
For the convenience of understanding, we have blurred the two concepts.
Thank you for your advice. We will describe our definition more precisely.

**Comment by ireneontheway5** [comment]
I'll update it in the terms.md

**Comment by shengjun1985** [comment]
The article referring to this description on CSND has been fixed.
https://blog.csdn.net/weixin_44839084/article/details/103471083
Thank you very much.
