### ISSUE TITLE
Search within ids

### ISSUE THREAD

**Issue by ufuk23** [milvus-io/milvus#4667]
We need to search with given ids as well as vectors using rest API.

For example:

POST
http://localhost:19121/collections/art/vectors
{
"search": {
"topk": 3,
"vectors": [[0,0,0,0,0,0,1,0,0,0,0,0,0,0,0.01,0,0,0,0,0,0,0.2,0,0,0,0,0,0,0,0.3,0,0,0,0,0,0,0,0,0,0,0]],
"params": {"nprobe": 16},
"ids":["5", "23", "123", "1234", "334"]
}
}

For example, we need a scenario that works on Solr search engine and get the filtered results with IDs from Solr to search their feature vectors in Milvus by the same IDs. We have the filtered IDs coming from Solr and need to search their feature vectors. We don't want to search the whole collection of the milvus db, we need a subset of the collection by specified IDs. How could we do that?

**Comment by yhmo** [comment]
To get vector data from milvus by id, you can use:
`/collections/{collection_name}/vectors?ids={vector_id_list} (GET)`
This api is to obtain vectors by ID.
Example:
`curl -X GET "http://127.0.0.1:19121/collections/test_collection/vectors?ids=1578989029645098000,1578989029645098001" -H "accept: application/json" -H "Content-Type: application/json"`
Response:
```
{
  "vectors": [
    {
      "id": "1578989029645098000",
      "vector": [0.1]
    },
    {
      "id": "1578989029645098001",
      "vector": [0.2]
    }
  ]
}
```
The RESTful api document:
https://github.com/milvus-io/milvus/blob/master/core/src/server/web_impl/README.md

**Comment by yhmo** [comment]
If you need "search by IDs", there is an issue about this: #3203

**Comment by ufuk23** [comment]
> To get vector data from milvus by id, you can use:
> `/collections/{collection_name}/vectors?ids={vector_id_list} (GET)`
> This api is to obtain vectors by ID.
> Example:
> `curl -X GET "http://127.0.0.1:19121/collections/test_collection/vectors?ids=1578989029645098000,1578989029645098001" -H "accept: application/json" -H "Content-Type: application/json"`
> Response:
> 
> ```
> {
>   "vectors": [
>     {
>       "id": "1578989029645098000",
>       "vector": [0.1]
>     },
>     {
>       "id": "1578989029645098001",
>       "vector": [0.2]
>     }
>   ]
> }
> ```
> 
> The RESTful api document:
> https://github.com/milvus-io/milvus/blob/master/core/src/server/web_impl/README.md

Yes I know but we need to search the vector by ids, just getting the vectors by ids is not what we need. If I get the vectors by ids then how could I search them by a vector?

**Comment by yhmo** [comment]
@ufuk23 
To understand your requirement clearly, let's use an example:
1. Assume there is a collection which name is "C1", it contains 3 vectors: v1(id=1), v2(id=2), v3(id=3).
2. Now you got 2 ids from Solr: [1,3]
3. Firstly if you want to get the 2 vectors from the 2 ids, get_entity_by_id() can do this
4. You said you want to "search them by a vector", we could not catch your point. Do you mean you want to perform a search action only search v1 and v2, ignore the v3? 

If yes, the requirement is more like a filtering search. something like "search in C1 which id in list[1, 2]"?

**Comment by ufuk23** [comment]
Yes I mean I want to perform a search action only search v1 and v2, ignore the v3.
Assume that we have billion records on Solr and corresponding billion vectors on Milvus. For example
1- The user make a solr search and get 1 million of records with IDs (from Solr backend)
2- The user has a vector as well to search (on Milvus backend)
3- Now I need to search on Milvus with the vector just for these 1 million of record IDs coming from the Solr, not billion vectors. Milvus must search by a vector and the specified IDs while ignoring other records.

I don't need to search whole Milvus DB, I need a search by a vector and IDs intersection. Could I explain the need clearly?

**Comment by yhmo** [comment]
Yes it is clear now. 
After you got 1 million of IDs from Solr(by some kind of filtering), you call RESTful api with the IDs as parameter, Milvus only search within the 1 million vectors. 
My concern is the performance: find out 1 million records from billion records, the performance could be very poor.

**Comment by ufuk23** [comment]
@yhmo That's exactly what I mean. Before I have found the Milvus I work on the ElasticSearch with the same case, and that's right I realized that performance is important. Now I have 1.3 million vectors in a Milvus collection and when I search it by **just a vector** the response is too slow, it is about 1 minute. I expected that it takes 1-2 seconds. My vector dimension is 1000 (float values), the metric is L2, and I have a machine that has i7 CPU, 8 GB ram. Could you help me, please?

**Comment by yhmo** [comment]
> @yhmo That's exactly what I mean. Before I have found the Milvus I work on the ElasticSearch with the same case, and that's right I realized that performance is important. Now I have 1.3 million vectors in a Milvus collection and when I search it by **just one vector** the response is too slow, it is about 1 minute. I expected that it takes 1-2 seconds. My vector dimension is 1000 (float values), the metric is L2, and I have a machine that has i7 CPU, 8 GB ram, docker container. Could you help me, please?

Your data size:  1.3 million, 1000 dimensions = 1000*4*1.3M = 5.2GB, that means to get good performance, Milvus requires at least 5.2GB memory at runtime. You said the performance is poor(1 minute), I guess that may cause by insufficient cache size(you can specify 6GB cache size in the server_config.yaml)
To get best performance, you can create IVF_SQ8 index for the collection, this kind of index only require 1/3 memory of the data size.

**Comment by yhmo** [comment]
I just do some test on my machine:
i7 CPU 12 cores
64GB 

milvus version: 0.10.5
1.3 million vectors
1000 dimensions
search 1 vector, topk=10

I didn't create index, the search performance is about 200ms(0.2 second).

**Comment by ufuk23** [comment]
Thanks for your help. Your machine is so powerful :) I made another test:
i7 and 8GB ram
Milvus version: 0.10.5
1 million vectors with 1000 dimensions
search 1 vector, topk=3
cache size=4GB (because of lack of my memory)

- When I start the docker container and perform the first search, the docker container increases the memory usage to 3.8 GB and it takes about > 90 seconds
- When I keep going the search request it takes <1 second as I expected and the docker container has still 3.8GB ram 
- Is it normal for the first search request? I think it should load the vectors from the disc to the memory, right?
- What about the parameter probe in this case?

**Comment by yhmo** [comment]
> Thanks for your help. Your machine is so powerful :) I made another test:
> i7 and 8GB ram
> Milvus version: 0.10.5
> 1 million vectors with 1000 dimensions
> search 1 vector, topk=3
> cache size=4GB (because of lack of my memory)
> 
> * When I start the docker container and perform the first search, the docker container increases the memory usage to 3.8 GB and it takes about > 90 seconds
> * When I keep going the search request it takes <1 second as I expected and the docker container has still 3.8GB ram
> * Is it normal for the first search request? I think it should load the vectors from the disc to the memory, right?
> * What about the parameter probe in this case?

The first search request need to load data from disk to memory, so the first search request performance is mainly depend on disk read speed(my disk is SSD, read speed > 500M/s). It seems your storage is some kind of network shared storage?
Did you create index IVF_SQ8?
Once the data is loaded into memory, milvus will keep it in memory, so the second search request will be fast.
Milvus print each phase time cost in log file(under the /db/logs folder, xxx-debug.log).

**Comment by ufuk23** [comment]
Hi, I cannot create IVF_SQ8 index, it doesn't work while running the following request

(POST) http://localhost:19121/collections/art/indexes
{  "index_type": "IVF_SQ8" }

the response is:
{   "message": "The index type is invalid.",
    "code": 8
}

I run the GET request to get the index information and the reponse is:  {"index_type":"FLAT","params":{}}
I don't know why it doesn't work

**Comment by yhmo** [comment]
> Hi @yhmo , I cannot create IVF_SQ8 index, it doesn't work while running the following request
> 
> (POST) http://localhost:19121/collections/art/indexes
> { "index_type": "IVF_SQ8" }
> 
> the response is:
> { "message": "The index type is invalid.",
> "code": 8
> }
> 
> I run the GET request to get the index information and the reponse is: {"index_type":"FLAT","params":{}}
> I don't know why it doesn't work

Seems you miss parameters of the index, try send this:
`{ "index_type": "IVF_SQ8", "params": { "nlist": 4096 } }`

**Comment by ufuk23** [comment]
@yhmo, I am afraid that I have tested that code before but it didn't work. I don't know why maybe it is a configuration problem :(

**Comment by michellemay** [comment]
Going back to the original question: will milvus support pre/post-filtering of the most similar vectors?
I think the solr case is really useful in practice.

Correct me if I'm wrong but it all boils down to 'if' the underlying library supports streaming filtering (filter as we retrieve documents from the structure).

**Comment by yhmo** [comment]
> Going back to the original question: will milvus support pre/post-filtering of the most similar vectors?
> I think the solr case is really useful in practice.
> 
> Correct me if I'm wrong but it all boils down to 'if' the underlying library supports streaming filtering (filter as we retrieve documents from the structure).

Yes, the mechanism of Solr is worth learning, it is very suitable for stream data processing. Milvus splits data into segments,when search request is received, milvus performs query in each segment one by one. For example, a collection has 10 segments, milvus firstly query the No.1 segment, get top10 vectors, then query the No.2 segment, get another top10 vectors, reduce the two top10 vectors to one top10 vectors, and then query the No.3 segment.... In each segment, milvus start multiple threads to parallel compute distances. It is more like "batch processing". On my opinion, provide customize/post-query filter after each segment is a valuable feature.

**Comment by cceyda** [comment]
I really would like this feature as well. My use case is similar to the ones described; I use elasticsearch.
> stream data processing ...It is more like "batch processing". On my opinion, provide customize/post-query filter after each segment is a valuable feature.

If there was something on milvus side that can consume  [sliced scroll](https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#slice-scroll) results would be 🔥

**Comment by yhmo** [comment]
Similar requirement to #5443.
The #5443 define some API, allow user to calculate distance for specified vectors. We are developing this feature in v2.0 now.
User can specify some ids, the milvus will retrieve vectors from db according to these ids, and calculate distance be tween the input vectors and the specified vectors. Result a list of distance, user can sort the distance at client side to get topk result.

**Comment by yhmo** [comment]
@cceyda 
The result paging function is a feature, there is an issue about this: https://github.com/milvus-io/milvus/issues/3851
But this feature is not yet in plan, since there are some other high priority features need to be done.

**Comment by yhmo** [comment]
The #5443 has been done. A new api named "calc_distance" has been added, allow user to calculate distance between vectors. User can pick vectors by id array to calculate, so that he can do a workaround for "search within ids". Note: the output result is not arranged. To find out a topk result, user need to arrange the distances in client side.
