### ISSUE TITLE
delete entity by Id passing a non-existent vector ID returns ok

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#4671]
![企业微信截图_16119088258622](https://user-images.githubusercontent.com/34296482/106250619-de363e00-624e-11eb-872a-31b16d9c46a5.png)

**Comment by yhmo** [comment]
I think this behavior is as-designed.

**Comment by jingkl** [comment]
> I think this behavior is as-designed.

I think this design is problematic and should go ahead and determine if the ID exists in the collection

**Comment by yhmo** [comment]
When milvus receive delete request, it iterates each segment to see if an id is in this segment, if the id is in this segment, milvus marks the id as "deleted". After all segments are iterated, if there are still some ids left, they will be regarded as "non-exist", that means no need to do anything for 'non-exist' id. 
Return OK means all these ids are no longer be searchable in this collection, including the "non-exist" ids. 
Return ERROR means something is wrong when delete an "exist" id.
