### ISSUE TITLE
Can't access MySQL server from pymilvus

### ISSUE THREAD

**Issue by Rtut654** [milvus-io/milvus#4679]
I got this problem when trying to create mysql table:
<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = ""
	debug_error_string = "{"created":"@1611908454.549921872","description":"Error received from peer ipv6:[::1]:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"","grpc_status":12}">

 after this code 
milvus = Milvus()
milvus.connect(host='localhost', port='19530')
### Status(code=0, message='Success')
dim = 10
param = {'table_name':'test1', 'dimension':dim}
milvus.create_table(param)

I have pymilvus version  0.2.7, milvus and Mysql ( v5.7) servers running in docker-compose containers

**Comment by yhmo** [comment]
The error message indicate the milvus server could not be found, please double-check your milvus version and pymilvus version:
```
docker ps|grep milvus
pip show pymilvus
```

**Comment by Rtut654** [comment]
Okay, so  pymilvus version: is 0.2.7 and milvus:0.10.5-cpu-d010621-4eda95

**Comment by yhmo** [comment]
Please read the versions mapping in this page: https://pypi.org/project/pymilvus/
The pymilvus 0.2.7 is for milvus 0.6.0.
You should upgrade pymilvus to 0.2.15 for milvus 0.10.5

**Comment by Rtut654** [comment]
Yeah, but  what can I use instead of create_table() to create MySQL table with my parameters? In 0.2.15 this function is not available and all tutorials I found use it (for example https://medium.com/unstructured-data-service/milvus-metadata-management-3-e65b14137f58 ).

**Comment by yhmo** [comment]
> Yeah, but what can I use instead of create_table() to create MySQL table with my parameters (I want to match milvus numerical id with my own uuid)? In 0.2.15 this function is not available and all tutorials I found use it (for example https://medium.com/unstructured-data-service/milvus-metadata-management-3-e65b14137f58 ).

The create_table() was renamed to create_collection() after pymilvus0.2.8. The article in medium is written in old version.
The official site of pymilvus documentation is in: https://pypi.org/project/pymilvus/

**Comment by yhmo** [comment]
Upgrade pymilvus to 0.2.15:
```
pip3 uninstall pymilvus
pip3 install pymilvus==0.2.15
```

This is an example script for pymilvus 0.2.15 and milvus 0.10.5:

```
import time

import numpy as np
from milvus import Milvus, IndexType
from milvus.client.types import MetricType

# collection parameters
COLLECTION_NAME = "TEST"
COLLECTION_DIMENSION = 128
METRIC_TYPE = MetricType.IP
INDEX_FILE_SIZE = 100
COLLECTION_PARAM = {
    'collection_name': COLLECTION_NAME,
    'dimension': COLLECTION_DIMENSION,
    'index_file_size': INDEX_FILE_SIZE,
    'metric_type':MetricType.L2
}

# index parameters
INDEX_TYPE = IndexType.IVF_SQ8
INDEX_PARAM = {'nlist': 1000}

# search parameters
NQ = 1
TOPK = 10
SEARCH_PARAM = {'nprobe': 32}

# connect milvus server
SERVER_ADDR = "127.0.0.1"
SERVER_PORT = '19530'
MILVUS = Milvus(host=SERVER_ADDR, port=SERVER_PORT)

def gen_vec_list(nb, seed=1234):
    ran = np.random.RandomState(seed)
    xb = ran.rand(nb, COLLECTION_DIMENSION).astype("float32")
    vec_list = xb.tolist()
    return vec_list

def create_collection():
    status = MILVUS.create_collection(COLLECTION_PARAM)
    print("create collection:", COLLECTION_NAME, status)


def drop_collection():
    status = MILVUS.drop_collection(collection_name=COLLECTION_NAME)
    print("drop collection:", COLLECTION_NAME, status)

def flush_collection():
    MILVUS.flush(collection_name_array=[COLLECTION_NAME])

def describe_collection():
    print("describe table")
    status, row_count = MILVUS.count_entities(collection_name=COLLECTION_NAME)
    status, table = MILVUS.get_collection_info(collection_name=COLLECTION_NAME)
    print(table)
    print(COLLECTION_NAME, "row count =", row_count)
    status, index = MILVUS.get_index_info(collection_name=COLLECTION_NAME)
    print("index information: ", index)

def create_index():
    print("create index...")
    time_start = time.time()
    status = MILVUS.create_index(COLLECTION_NAME, index_type=INDEX_TYPE, params=INDEX_PARAM)
    time_end = time.time()
    print(status)
    print("create index time cost:", time_end - time_start, 'sec')

def insert(vec_list, vector_ids=None, tag=None):
    time_start = time.time()
    status, ids = MILVUS.insert(collection_name=COLLECTION_NAME, records=vec_list, ids=vector_ids, partition_tag=tag)
    time_end = time.time()
    print("insert vectors:", len(vec_list), " time cost:", time_end - time_start, 'sec')

def print_result(results):
    print("query results for each vector:")
    index = 0
    for each_query in results:
        print("No.", index, "topk result:")
        index += 1
        for each_score in each_query:
            print("id = ", each_score.id, " distance = ", each_score.distance)

def search():
    time_start = time.time()
    query_vectors = gen_vec_list(nb=NQ)
    status, results = MILVUS.search(collection_name=COLLECTION_NAME, query_records=query_vectors, top_k=TOPK, params=SEARCH_PARAM)
    time_end = time.time()
    print_result(results)
    print("search time cost:", time_end - time_start, 'sec')

def main():
    drop_collection()
    create_collection()

    # insert vectors
    for k in range(20):
        print("No.", k)
        vec_list = gen_vec_list(10000, seed=k)
        insert(vec_list=vec_list)
        flush_collection()

    describe_collection()

    # search without index(brute-force search))
    search()

    # create index
    create_index()
    describe_collection()

    # search with index
    search()

if __name__ == '__main__':
    main()
```

**Comment by Rtut654** [comment]
Thanks a lot! I got an access to MySQL server and I see in sql container newly created collections. The only problem is that I still struggling with the initial goal - since milvus allows to create only numeric id of vectors I need to keep the connection between milvus auto id (or my own numeric) and my uuid (string id) of each vector. Theoretically I should create collection with my field, say name_id and fill it by batch of names along with inserting vectors, but I can't find in documentation any ways of direct insert into sql table (collection).

**Comment by yhmo** [comment]
It is risk to directly change mysql table. Manually change the sql table schema may lead to milvus problem.
For milvus 0.10.x, it only store two fields: a numeric id filed, and a vector data field. Typically, users use another sql service(postgresql, mysql, etc..) to store their string id. Milvus returns numeric ids, then perform a sql statement in the sql service to get corresponded string id.

The new milvus version will support multiple customize fields in a collection. It is in developing.

**Comment by Rtut654** [comment]
Got it, thanks! I was mainly searching for this kind of answer.
