### ISSUE TITLE
Mishards solution based on milvus 0.10.5-cpu Write service is a single point and does not support domain binding and dynamic IP deployment.

### ISSUE THREAD

**Issue by luochenxi** [milvus-io/milvus#4682]
**Feature request**
ENV:
+ [Milvus:0.10.5-cpu](https://milvus.io/cn/docs/v0.10.5/milvus_docker-cpu.md)
+ [Mishards](https://github.com/milvus-io/milvus/blob/master/shards/README_CN.md)
+ Docker version 19.03.6, build 369ce74a3c
+ docker-compose version 1.27.4, build 40524192

Deployment Architecture：
+ Abstract Services:   Based on the same image
+ Instantiated pods:   Multiple pods running on the same image
+ k8s implements resource allocation, elastic scaling, routing gateways, failover, and service configuration control via environment variables.
 
I wish I could use Milvus to do similar searches。

But，I encountered 2 problems after reading the [doc1](https://github.com/milvus-io/milvus/blob/master/shards/README_CN.md) , [doc2](https://github.com/milvus-io/bootcamp/blob/master/solutions/Mishards/README.md) .

![image](https://user-images.githubusercontent.com/18586097/106560552-29f42a80-6562-11eb-934c-f1ca1d169c15.png)

As shown above:
+  **Question A:  Write node Only supports single point and no domain name support.**
+  **Question B:  Unable to dynamically fetch all Ip's of milvus cluster.**

**The solution I want**
+ Write services support multiple pods and stateless scaling
+ All IPs can be obtained dynamically or support domain binding

**Alternatives I've considered**
+  Additional to the cluster an etcd, mysql, etc. for service discovery, the instances within the cluster can be up and down, stateless scaling.
+ Communication between service modules supports domain binding.

**Additional context**
+ SDK Client support domain binding and service discovery.

**Comment by scsven** [comment]
@luochenxi Sorry, Mishards do not support multiple write nodes now. But the domain is supported in the deployment.

**Comment by luochenxi** [comment]
@scsven  Does the `DISCOVERY_STATIC_HOSTS` field in the configuration file support filling in the domain name?

**Comment by jmichaelsilva** [comment]
Hello @luochenxi,

**About Question B: Unable to dynamically fetch all Ip's of milvus cluster.**

I'm also using mishards on kubernetes and the following configuration (mishards) is working for me: 
```
    WOSERVER=tcp://milvus-writable.milvus.svc.cluster.local:19530

    DISCOVERY_CLASS_NAME=kubernetes
    DISCOVERY_KUBERNETES_NAMESPACE=milvus
    DISCOVERY_KUBERNETES_POD_PATT=.*-ro-servers-.*
    DISCOVERY_KUBERNETES_LABEL_SELECTOR=tier=ro-servers
    DISCOVERY_KUBERNETES_POLL_INTERVAL=10
    DISCOVERY_KUBERNETES_IN_CLUSTER=True
```

This example uses the WO-SERVER DNS Service and the Kubernetes DISCOVERY_CLASS (RO-SERVER). 

The mishards kubernetes discovery class also needs a cluster role as described here https://github.com/milvus-io/milvus/blob/master/shards/kubernetes_demo/mishards_rbac.yaml.

**Comment by yhmo** [comment]
Inactive, close
