### ISSUE TITLE
Do not support STRING type and account login

### ISSUE THREAD

**Issue by pilipala818** [milvus-io/milvus#4695]
**1.Temporarily don't support STRING type.**

**In practice, STRING type data is used frequently.**

**2.Please add an account login function.**

**In case, IP addresses are being tracked and cause data leakage.**

**Comment by shengjun1985** [comment]
String type has been mentioned all the time (#1294, #4430, and so on).
But the most challenge is storage and performance.
In the latest design, we tend to do a transformation mapping outside the system.
