### ISSUE TITLE
RPC error

### ISSUE THREAD

**Issue by Tennyson53** [milvus-io/milvus#4707]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
`Addr [99.47.151.90:19530] show_partitions
Rpc error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1612774113.538179001","description":"Error received from peer ipv4:99.47.151.90:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Deadline Exceeded","grpc_status":4}"`
>
	{'API start': '2021-02-08 16:48:03.536900', 'RPC start': '2021-02-08 16:48:03.537408', 'RPC error': '2021-02-08 16:48:33.538416'}`

**Steps/Code to reproduce behavior**
[list_partitions()]

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)
Docker；CPU 6；Memory 10G

- Milvus version (master or released version)
0.10.5

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
Seems milvus server is not available or pymilvus sdk version is not match milvus server.
Firstly check whether the milvus container is running:
`docker ps [container_id]`

Secondly check the pymilvus sdk version:
`pip3 list|grep pymilvus`

**Comment by shengjun1985** [comment]
If you have more questions, please continue to contact our community.
