### ISSUE TITLE
Can't seem to find the service.yml for milvus 11.0

### ISSUE THREAD

**Issue by Sushanti99** [milvus-io/milvus#4710]
`wget https://raw.githubusercontent.com/milvus-io/milvus/0.11.0/core/conf/demo/milvus.yaml
`

--2021-02-11 03:30:49--  https://raw.githubusercontent.com/milvus-io/milvus/0.11.0/core/conf/demo/milvus.yaml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-02-11 03:30:49 ERROR 404: Not Found.

**Comment by appcom2016** [comment]
https://github.com/milvus-io/milvus/blob/experimental/core/conf/demo/milvus.yaml

**Comment by Sushanti99** [comment]
Thanks for this
