### ISSUE TITLE
The GPU cache holds much more data than the configured value

### ISSUE THREAD

**Issue by op-hunter** [milvus-io/milvus#4719]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
GPU memory increases abnormally.

**Steps/Code to reproduce behavior**
(1) create a collection
(2) for loop many times (for example 20 times)
build IVFSQ8H index
query
drop index
check the GPU memory used

**Expected behavior**
When the query is done, the size of GPU memory used should not be greater than that in config file.

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [x] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)
GPU

- Milvus version (master or released version)
0.10.5

**Configuration file**
gpu:
     cache_size: 4GB

**Comment by yhmo** [comment]
The "cache_size" is only for query. There is comment in the config file: "The size of CPU memory used for caching data for faster query". That means the value is to control the hot data size in memory for getting best performance of query.
Milvus has some background threads require extra memory: insert buffer, wal buffer, build index. In the config file, the "cache.insert_buffer_size" is for insert buffer, the "wal.buffer_size" is for wal buffer.
If milvus start a background thread to build index, it will cost extra memory, the cost size depend on the index algorithm(typically is a bit larger than a segment size).
