### ISSUE TITLE
Gets all vectors of segment in a collection via the restful interface

### ISSUE THREAD

**Issue by Bennu-Li** [milvus-io/milvus#4721]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
I insert two entities in a collection, which have the same id but different vectors. When I use the restful interface to get all vectors in a segment, I get the same two vectors.
![image](https://user-images.githubusercontent.com/53458891/108341642-d39b1300-7214-11eb-9968-83f441cf0812.png)

**Steps/Code to reproduce behavior**
https://github.com/milvus-io/milvus/tree/master/core/src/server/web_impl#collectionscollection_namesegmentssegment_namevectors-get

**Method of installation**
- [ ] Docker/gpu

- Milvus version (master or released version)
0.10.4

**Additional context**
Is there any way I can get the two different vectors with the same ID that I inserted?

**Comment by scsven** [comment]
Please refer:
https://github.com/milvus-io/milvus-tools

**Comment by yhmo** [comment]
Inactive, close
