### ISSUE TITLE
Query failed

### ISSUE THREAD

**Issue by CrazyBeeline** [milvus-io/milvus#4729]
search collection failed

error info 
![error](https://user-images.githubusercontent.com/25030234/108484790-2d641180-72d7-11eb-9f33-c88270c7c86b.png)

milvus info
![image](https://user-images.githubusercontent.com/25030234/108484443-c7778a00-72d6-11eb-8304-c46fddb5b433.png)

collection info
dimension:1024
index_file_size:1024
metric_type:IP
index:IVFSQ8H

milvus conf
![image](https://user-images.githubusercontent.com/25030234/108485215-a4010f00-72d7-11eb-97bb-93060fb66cdd.png)
memory_cache:30G

GPU info
![image](https://user-images.githubusercontent.com/25030234/108669728-8c649900-7518-11eb-9b5a-ed8da9a90c6f.png)
![image](https://user-images.githubusercontent.com/25030234/108669767-9dada580-7518-11eb-84b2-87fd35ba58ee.png)

memory info
![image](https://user-images.githubusercontent.com/25030234/108486319-ee36c000-72d8-11eb-80b7-0e31048677cf.png)

**Comment by shengjun1985** [comment]
The error occurred when cudaHostAlloc, and the error code is 46 (cudaErrorDevicesUnavailable).
See [cuda error](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) and [cudaHostAlloc](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#group__CUDART__MEMORY_1gb65da58f444e7230d3322b6126bb4902).

**Comment by CrazyBeeline** [comment]
@shengjun1985 
It's strange that
I create lots of collections, but only one collection has this error.
as I restart milvus server 
this error happen whih the same collection
This situation is not in line with the fair competition of computer resources


How can I solve this problem if you say this

**Comment by op-hunter** [comment]
@CrazyBeeline 
Please provide more infomation to help us reproduce this issue. For example, the data scale, index create and search parameters, your test procedure.

**Comment by CrazyBeeline** [comment]
@op-hunter 
1.here is milvus metadata
[milvus_entity.zip](https://github.com/milvus-io/milvus/files/6014382/milvus_entity.zip)
2.search parameters like this
{"search":{"topk":2,"vectors":[],"params":{"nprobe":256}}}
vector size No more than 1000
3.milvus ops from restful API .Some operations are as follows
-----------------------------------
/collections/{collection_name}/vectors (POST) Inserts vectors to a collection.
/collections/{collection_name}/vectors (PUT) Searches vectors in a collection.
/collections/{collection_name}/vectors (PUT) Delete vectors.
/system/task flush  collection
------------------------------
/collections/{collection_name}/vectors (POST) Inserts vectors to a collection with partition.
/collections/{collection_name}/vectors (PUT) Searches vectors in a collection with partition.
/collections/{collection_name}/vectors (PUT) Delete vectors.
/system/task flush  collection
---------------------------------

**Comment by yhmo** [comment]
> @shengjun1985
> It's strange that
> I create lots of collections, but only one collection has this error.
> as I restart milvus server
> this error happen whih the same collection
> This situation is not in line with the fair competition of computer resources
> 
> How can I solve this problem if you say this

Which collection has this error?

**Comment by CrazyBeeline** [comment]
@yhmo 
person_face_25

**Comment by CrazyBeeline** [comment]
@yhmo 
sorry! person_face_28  has this error

**Comment by yhmo** [comment]
@CrazyBeeline 
Could you try these steps:
1. drop_index for the person_face_28
2. create_index for the person_face_28
3. search person_face_28

**Comment by CrazyBeeline** [comment]
@yhmo 
![image](https://user-images.githubusercontent.com/25030234/108684294-afe60e80-752d-11eb-9879-8ff3f3f1e7ae.png)

**Comment by yhmo** [comment]
> @yhmo
> ![image](https://user-images.githubusercontent.com/25030234/108684294-afe60e80-752d-11eb-9879-8ff3f3f1e7ae.png)

Could you run a sql query to your mysql server?:
SELECT * FROM TableFiles WHERE table_id="person_face_28";

**Comment by CrazyBeeline** [comment]
@yhmo 
![image](https://user-images.githubusercontent.com/25030234/108686414-592e0400-7530-11eb-9b8c-347ab69d6d23.png)
![image](https://user-images.githubusercontent.com/25030234/108686442-63e89900-7530-11eb-8a1a-1fe4c1c6f4ae.png)

**Comment by yhmo** [comment]
Could you send me the file:  /var/lib/milvus/db/tables/person_face_28/1613715822711153000/1613715822711153000
My email: yihua.mo@zilliz.com

**Comment by yhmo** [comment]
@CrazyBeeline 
I use the data file to construct a collection on my milvus, same name, same index/query parameters, but could not reproduce the error. Build index successfully by GPU, search also succeed.  
My gpu is GeForce GTX 1660 (6GB), my NVIDIA driver version is 450.57. Not sure what is the reason. Do you have another machine with different GPU?

**Comment by CrazyBeeline** [comment]
only milvus runs on P40 .
I will copy milvus data to test env tomorrow !

**Comment by CrazyBeeline** [comment]
@yhmo 
I test in my local env 
![image](https://user-images.githubusercontent.com/25030234/108965364-baccaa80-76b7-11eb-9ab2-8ea0baeb0d8a.png)

**Comment by yhmo** [comment]
> @yhmo
> I test in my local env
> ![image](https://user-images.githubusercontent.com/25030234/108965364-baccaa80-76b7-11eb-9ab2-8ea0baeb0d8a.png)

Build index successfully. No error.
What is your local env NVIDIA driver version?

**Comment by CrazyBeeline** [comment]
![image](https://user-images.githubusercontent.com/25030234/108983074-72b68380-76c9-11eb-96f7-24a17103d11d.png)

**Comment by yhmo** [comment]
Seems this error doesn't relate to NVIDIA driver version, since the older version(418.43) is succeed. 
I guess it relates to the GPU device(P40-8Q) and its state, but I can not get conclusion(we have no such device).

**Comment by yhmo** [comment]
Inactive, close
