### ISSUE TITLE
Search in ID's

### ISSUE THREAD

**Issue by Sushanti99** [milvus-io/milvus#4734]
Can I narrow down the vector search in milvus's collection? Suppose I have ID's of [1,2,3] after inserting in milvus. Can I conduct a search on milvus only looking for ID's [1,2] and get the distance?

the discussion is elaborated in the discussions section : https://github.com/milvus-io/milvus/discussions/4731

**Comment by shengjun1985** [comment]
> Creating partitions is a good idea in Milvus but there's a performance limitation of 4096 number of collections and partitions that can be created in one Milvus cluster. As far as I know, the performance decreases exponentially after this number.

How many partitions do you need to create and how many partitions do you involve in each query?
If you do not specify many partitions for each query, it's better to solve your problem through partitions. The reason is that finding vectors by ID is also an inefficient operation.

**Comment by Sushanti99** [comment]
The partition number needs to be scalable. I'm going to be treating every video as a partition to search/isolate results per video. So the upper cap for partitions would not be enough.

**Comment by shengjun1985** [comment]
Will you have a query on different partitions (videos)?
Or will you only access one partition (video) in one query?

**Comment by Sushanti99** [comment]
I'll only be searching on one video at a time.

**Comment by shengjun1985** [comment]
Thank you very much. I have understand your usage.
Your largest challenge is not vector comparison (only 2000 vectors), but vector search (to find these 2000 vectors). In the current system, you can try to build a collection for each video. And it has the least impact on performance.

**Comment by Sushanti99** [comment]
Isn't there the same uppercap of 4096 on the number of collections too? 
Because my long term goal is to use this in a production environment, each video will be a collection - thereby implying to create hundreds of thousands of collections?

**Comment by shengjun1985** [comment]
We don't limit the number of collection.

**Comment by Sushanti99** [comment]
What's your estimate on the max number of collections till it significantly affects performance?

**Comment by shengjun1985** [comment]
The number of collections only affects the meta query.
And I think it is hard to affect the performance.

**Comment by yhmo** [comment]
Inactive, close
