### ISSUE TITLE
Logging to StdOut

### ISSUE THREAD

**Issue by jcrist1** [milvus-io/milvus#4735]
**Please state your issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**
Milvus release 0.11.0 supported logging to stdout (see this issue: [3977](https://github.com/milvus-io/milvus/issues/3977)) but that release is no longer available. It was fantastic that the feature was implemented, but now trying to troubleshoot an issue with our deployment, I would like to downgrade, but would lose support for logging to stdout.

**Describe the solution you'd like**
Milvus should be configurable to log to stdout, so that we can process the logs in a unified way with the other workloads on our cluster.

**Describe alternatives you've considered**
We are currently using the 0.11.0 release, but that doesn't appear to be supported anymore.

**Additional context**
The solution to 3977 was merged into release 0.11.0 in  [PR-3993](https://github.com/milvus-io/milvus/pull/3993)

**Comment by shengjun1985** [comment]
Thanks for the reminder, we have the plan to move that function to 0.10.x.
And if you want to use it as soon as possible, you can modify the code in [LogUtil.cpp](https://github.com/milvus-io/milvus/blob/master/core/src/utils/LogUtil.cpp) and compile it locally. 
```c++
Status
InitLog(bool trace_enable, bool debug_enable, bool info_enable, bool warning_enable, bool error_enable,
        bool fatal_enable, const std::string& logs_path, int64_t max_log_file_size, int64_t delete_exceeds) {
    ...
    defaultConf.setGlobally(el::ConfigurationType::ToFile, "false");
    defaultConf.setGlobally(el::ConfigurationType::ToStandardOutput, "true");
```
Please refer to [Install Milvus from Source Code](https://github.com/milvus-io/milvus/blob/master/INSTALL.md)
