### ISSUE TITLE
Change `index_file_size` to `index_build_threshold`

### ISSUE THREAD

**Issue by jielinxu** [milvus-io/milvus#475]
**Is your feature request related to a problem? Please describe.**
The parameter name `index_file_size` is confusing and not precise in meaning. This parameter is not about the size of an index file, rather, it's a threshold beyond which index is built for the raw data file.

**Describe the solution you'd like**
Change the name `index_file_size` to `index_build_threshold`, and update the corresponding description.

**Comment by BossZou** [comment]
I think this tag has been used in many place. So i suggest that we do not change `index_file_size` currently. This need discussion.

**Comment by BossZou** [comment]
close it. reopen if needed in the future.
