### ISSUE TITLE
get_vectors_by_id is very slow, 500ms for 10 ids, 5s for 100 ids etc. 0.10.5

### ISSUE THREAD

**Issue by iantbutler01** [milvus-io/milvus#4756]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

get_vectors_by_id is prohibitively slow, the time it takes to retrieve vectors is 500ms for 10 ids and increases significantly as the number of vectors to retrieve increases.

**Steps/Code to reproduce behavior**
Create any collection then insert 128dim vectors with an iv_sq8 index into that collection and then use get_vectors_by_id with 10+ ids to retrieve.

**Expected behavior**

Similar performance to general queries which are in the 10s of ms range.

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
0.10.5

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
There is an issue about performance of get_entity_by_id():  #3243

As we know milvus split vectors into segments, typically each segment size is 1GB, if we have 500k 128 dimensional vectors, there will be 3 segments generated.
Milvus create a bloom filter file for each segment, and each segment has a id file which store vector ids for this segment.

For get_entity_by_id(), Milvus run 3 steps to fetch a vector:
1. check each segment's bloom filter file
2. if a bloom filter says this id maybe in this segment, milvus read the id file, double-check whether this id is really in this segment
3. if the id is really in this segment, milvus read the raw data file, get the vector data and return


From the steps, we can know each time when get_entity_by_id() is executed, milvus will read bloom filter files from hard disk. Milvus doesn't keep the bloom filter in memory cache, because we shall give the top priority to search().

**Comment by iantbutler01** [comment]
@yhmo When I was digging around it looked like file reading performance and a few other things had made it into 11.0 and I'm concerned that even though you're no longer supporting 11.0 that those fixes/optimizations will go to waste. We were on 11.0 previously before switching back to 10.5 and from what I remember getting the vectors in particular from ids was faster on that version. I'm hoping the fixes get backported. 

If you give me a bit I can go find the commits I'm talking about.

**Comment by yhmo** [comment]
I compare 0.11.0(experiment branch) and 0.10.5 with same workflow:
1. create collection
2. insert 500k 128 dimensional vectors
3. invoke get_entity_by_id() to get 10 ids, run 100 times

For 0.11.0, average time cost of step3 is: 6.5ms
For 0.10.5, average time cost of step3 is: 12ms

The performance of 0.10.5 is worse than 0.11.0(experiment).

After investigation, I think the root cause is in bloom filter. 0.10.5 use a const capacity to initial bloom filter, the cost capacity is 500000, defined in src/codecs/default/DefaultIdBloomFilterFormat.cpp (line no.30):
`constexpr unsigned int bloom_filter_capacity = 500000;`

In 0.11.0(experiment), the capacity of bloom filter for each segment is dynamic, depend on collection parameter 'segment_row_count', the code is in src/segment/SegmentWriter.cpp (line no.150):
```
int64_t row_count = segment_ptr_->GetRowCount();
segment::IdBloomFilterPtr bloom_filter_ptr = std::make_shared<segment::IdBloomFilter>(row_count);
```

The capacity of bloom filter decide its size, in 0.10.5, each bloom filter file size is 2.8MB. In 0.11.0, the size could be very small(100k+). So when user invoke get_entity_by_id(), the 0.11.0 read few data from IO and get better performance.

**Comment by yhmo** [comment]
Test scripts:

For 0.10.5, pymilvus=0.2.15:

```
import time
import numpy as np
from milvus import Milvus, IndexType, Status
from milvus.client.types import MetricType

SERVER_ADDR = "127.0.0.1"
SERVER_PORT = '19530'

COLLECTION_NAME = 'TEST'
COLLECTION_DIMENSION = 128

MILVUS = Milvus(host=SERVER_ADDR, port=SERVER_PORT)


def create_collection():
    MILVUS.drop_collection(collection_name=COLLECTION_NAME)
    tb_param = {'collection_name': COLLECTION_NAME, 'dimension': COLLECTION_DIMENSION, 'index_file_size': 1024,
                'metric_type': MetricType.L2}
    status = MILVUS.create_collection(tb_param)

def gen_vec_list(nb, seed=np.random.RandomState(1234)):
    xb = seed.rand(nb, COLLECTION_DIMENSION).astype("float32")
    vec_list = xb.tolist()
    return vec_list

batch_count = 10000
def insert():
    time_start = time.time()
    vec_list = gen_vec_list(batch_count)
    for k in range(50):
        print("No.", k)
        vec_ids = [k * batch_count + i for i in range(batch_count)]
        status, result = MILVUS.insert(collection_name=COLLECTION_NAME, records=vec_list, ids=vec_ids)
    time_end = time.time()
    print("insert done", time_end - time_start, 'sec')

def get_entity_by_id():
    ids = [k * batch_count for k in range(10)]

    time_start = time.time()
    status, result = MILVUS.get_entity_by_id(collection_name=COLLECTION_NAME, ids=ids)
    time_end = time.time()
    print("get_entity_by_id", time_end - time_start, 'sec')


if __name__ == "__main__":
    create_collection()
    insert()

    time_start = time.time()
    for i in range(100):
        get_entity_by_id()
    time_end = time.time()
    print("average:", (time_end - time_start) / 100, 'sec')
```

For 0.11.0(experiment), pymilvus=0.3.0:

```
import sys, getopt
import struct
import time
import random
import string
import os
import re
import psutil
import json
import threading
from multiprocessing import Pool, Process

# 3rd imports
import numpy as np
import numpy as np
from milvus import Milvus, Status, DataType


SERVER_ADDR = "127.0.0.1"
SERVER_PORT = '19530'

COLLECTION_NAME = "TEST"
SEGMENT_ROW_COUNT = 1000000

VECTOR_FIELD_NAME = "vec_float"
VECTOR_DIMENSION = 128


COLLECTION_FIELDS = [
    {"name": VECTOR_FIELD_NAME, "type": DataType.FLOAT_VECTOR, "params": {"dim": VECTOR_DIMENSION}},
    ]

AUTO_ID = False

MILVUS = Milvus(host=SERVER_ADDR, port=SERVER_PORT)

def create_collection():
    try:
        # MILVUS.drop_collection(collection_name=COLLECTION_NAME)
        create_param = {
            "fields": COLLECTION_FIELDS,
            "segment_row_limit": SEGMENT_ROW_COUNT,
            "auto_id": AUTO_ID}

        MILVUS.create_collection(collection_name=COLLECTION_NAME, fields=create_param)
        print(COLLECTION_NAME, "created")
    except:
        print('create_collection exception')

def gen_vec_list(nb, dim, seed=np.random.RandomState(1234)):
    xb = seed.rand(nb, dim).astype("float32")
    vec_list = xb.tolist()
    return vec_list

def generate_entities(count):
    entities = []
    for field in COLLECTION_FIELDS:
        name = field['name']
        type = field['type']

        if type == DataType.FLOAT_VECTOR:
            params = field['params']
            dim = params['dim']

            dd = gen_vec_list(nb=count, dim=dim)
            entities.append({"name": name, "type": type, "values": dd})
    return entities

batch_count = 10000
def insert():
    time_start = time.time()
    vec_list = generate_entities(batch_count)
    for k in range(50):
        print("No.", k)
        vec_ids = [k * batch_count + i for i in range(batch_count)]
        ids = MILVUS.insert(collection_name=COLLECTION_NAME, entities=vec_list, ids=vec_ids)
    time_end = time.time()
    print("insert done", time_end - time_start, 'sec')

def get_entity_by_id():
    ids = [k * batch_count for k in range(10)]

    time_start = time.time()
    result = MILVUS.get_entity_by_id(collection_name=COLLECTION_NAME, ids=ids)
    time_end = time.time()
    print("get_entity_by_id", time_end - time_start, 'sec')

if __name__ == "__main__":
    create_collection()
    insert()

    time_start = time.time()
    for i in range(100):
        get_entity_by_id()
    time_end = time.time()
    print("average:", (time_end - time_start)/100, 'sec')
```

**Comment by yhmo** [comment]
0.11.0 persist the capacity of bloom filter into file, so that it can use dynamic capacity. 
But 0.10.5 doesn't persist this value,  data migration is not a good idea...

**Comment by yhmo** [comment]
Another reason of the performance difference is: 
0.11.0 has 'snapshot', it keep meta in memory so that milvus no need to always access MySQL/SQLite. 
0.10.0 always access MySQL/SQLite to get collection/segment info.

**Comment by shengjun1985** [comment]
CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz * 8

segment file size = 1024 MB
row count = 1,000,000
dim = 128
 | query id num | v 1.0.0 | v 1.x |
 | -- | -- | -- | 
| 10 | 9ms | 2ms |
| 100 | 149ms | 19ms |

**Comment by shengjun1985** [comment]
We have improved it in branch 1.x.
Before the next release, you can checkout that branch and compile it locally.
Please refer to: [Install Milvus from Source Code](https://github.com/milvus-io/milvus/blob/master/INSTALL.md)

**Comment by innerNULL** [comment]
> branch

thanks for your good job~

**Comment by iantbutler01** [comment]
Very good work, thank you all! Happy to close this when the next version is released with those changes.

**Comment by yhmo** [comment]
With the following script to test get_entity_by_id():


```
import time
import numpy as np
from milvus import Milvus, IndexType, Status
from milvus.client.types import MetricType

SERVER_ADDR = "127.0.0.1"
SERVER_PORT = '19530'

COLLECTION_NAME = 'TEST'
COLLECTION_DIMENSION = 128

MILVUS = Milvus(host=SERVER_ADDR, port=SERVER_PORT)


def create_collection():
    MILVUS.drop_collection(collection_name=COLLECTION_NAME)
    tb_param = {'collection_name': COLLECTION_NAME, 'dimension': COLLECTION_DIMENSION, 'index_file_size': 1024,
                'metric_type': MetricType.L2}
    status = MILVUS.create_collection(tb_param)

def has_collection():
    status, has = MILVUS.has_collection(collection_name=COLLECTION_NAME)
    return has

def gen_vec_list(nb, seed=np.random.RandomState(1234)):
    xb = seed.rand(nb, COLLECTION_DIMENSION).astype("float32")
    vec_list = xb.tolist()
    return vec_list

batch_count = 10000
def insert():
    time_start = time.time()
    vec_list = gen_vec_list(batch_count)
    for k in range(100):
        print("No.", k)
        vec_ids = [k * batch_count + i for i in range(batch_count)]
        status, result = MILVUS.insert(collection_name=COLLECTION_NAME, records=vec_list, ids=vec_ids)
    time_end = time.time()
    print("insert done", time_end - time_start, 'sec')
    MILVUS.flush(collection_name_array=[COLLECTION_NAME])

def get_entity_by_id():
    ids = [k * batch_count for k in range(100)]

    time_start = time.time()
    status, result = MILVUS.get_entity_by_id(collection_name=COLLECTION_NAME, ids=ids)
    time_end = time.time()
    print("get_entity_by_id", time_end - time_start, 'sec')


if __name__ == "__main__":
    if not has_collection():
        create_collection()
        insert()

    repeat = 100
    time_start = time.time()
    for i in range(repeat):
        get_entity_by_id()
    time_end = time.time()
    print("average:", 1000*(time_end - time_start) / repeat, 'ms')
```

Performance v0.10.5 VS v1.1.0:
query id num | v0.10.5 | v1.1.0
-- | -- | --
10 | 7.8 ms | 2.9 ms
100 | 55.9 ms | 12.6 ms

**Comment by yhmo** [comment]
The v1.1.0 docker image has been published. Official declaration will be published later.
