### ISSUE TITLE
Incorrect description about python interpreter version at Milvus website

### ISSUE THREAD

**Issue by BossZou** [milvus-io/milvus#4759]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

At official website, we require user has installed python 3.5. However, there may be some problem and from pymilvus 0.4.0, the lowest python version is 3.6, so the website should update these information.

Here is website:
https://milvus.io/cn/docs/v0.10.6/example_code.md

**Comment by PahudPlus** [comment]
Python version updated and published.

**Comment by PahudPlus** [comment]
@shengjun1985
