### ISSUE TITLE
Bug while creating IVF_SQ8 by Restful API

### ISSUE THREAD

**Issue by ufuk23** [milvus-io/milvus#4761]
This creating index request below doesn't work on milvus v.0.10.5 

(POST) http://localhost:19121/collections/art/indexes
{ "index_type": "IVF_SQ8", "params": { "nlist": 4096 } }

It returns
**{ "message": "The index type is invalid.","code": 8}** 
and we cannot create type IVF_SQ8 index.
How can we create the index?

**Method of installation**
- [ ] Docker/cpu (milvus v.0.10.5)

**Environment details**
- Hardware/Software conditions (Ubuntu server 20.04 LTS, Docker, 2 core CPU, 16 GB ram)
- Hardware/Software conditions (Windows 10, Docker, 2 core CPU, 8 GB ram)
- I tried that request on ubuntu and windows both.

- Milvus version (master or released version)
v0.10.5

**Configuration file**
Default yaml config file (not changed)

**Comment by BossZou** [comment]
@ufuk23 
IVF_SQ8 should be IVFSQ8, more info please refer to [index-and-search-parameters](https://github.com/milvus-io/milvus/tree/master/core/src/server/web_impl#index-and-search-parameters).
