### ISSUE TITLE
Mishards: add route cache

### ISSUE THREAD

**Issue by kuaikuai** [milvus-io/milvus#4763]
file_based_hash_ring_router.py call db.Session.query directly， We can add a cache
caching the result set so that repeatedly running the same query hits the cache instead of the database.

**Comment by BossZou** [comment]
@kuaikuai , Currently Mishards query meta to find available data to search， which may be modified by write node. Currently Querying metadata is the only way to detect these change. So to cache the result of query may cause inconsistency.

**Comment by yhmo** [comment]
Inactive and close
