### ISSUE TITLE
Faiss assertion'err == cudaSuccess' failed in void faiss:: gpu::freeMemorySpace(faiss::gpu::MemorySpace, void*) at gpu/utils/MemorySpace.cpp:72; details: Failed to cudaFree pointer 0x7fc514000000 (error 1 invalid argument #4412

### ISSUE THREAD

**Issue by jiesonshan** [milvus-io/milvus#4770]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

Faiss assertion'err == cudaSuccess' failed in void faiss:: gpu::freeMemorySpace(faiss::gpu::MemorySpace, void*) at gpu/utils/MemorySpace.cpp:72; details: Failed to cudaFree pointer 0x7fc514000000 (error 1 invalid argument #4412

how set parameter when use GPU?

**Comment by shengjun1985** [comment]
When you creating a collection, "index_file_size" is usually set to 1/4 of a single GPU memory.

**Comment by shengjun1985** [comment]
If you have more questions, please continue to contact our community.
