### ISSUE TITLE
milvs 0.10.6 server crash after insert

### ISSUE THREAD

**Issue by cocodee** [milvus-io/milvus#4773]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Run sdk-simple test case
After inserting few entities to milvus server, it crashed with below message:

free(): invalid pointer

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**
sdk_simple output

root@74aaf674b8b2:/milvus/sdk/cmake_build/examples/simple# ./sdk_simple -s 100.100.142.131
Client start...
Connect function call status: OK
Server version: 0.10.6
SDK version: 0.10.0
ShowCollections function call status: OK
All collections: 
	test_go(300000 entities)
	C_2021_3_3_17_28_12(100000 entities)
CreateCollection function call status: OK
===========================================
Collection name: C_2021_3_4_12_14_5
Collection dimension: 512
Collection index file size: 1024
Collection metric type: L2 distance
===========================================
Collection is created
DescribeCollection function call status: OK
===========================================
Collection name: C_2021_3_4_12_14_5
Collection dimension: 512
Collection index file size: 1024
Collection metric type: L2 distance
===========================================
Build entities No.0 begin...
Build entities No.0 totally cost: 1243 ms
Insert 100000 entities No.0 begin...
InsertEntities function call status: OK
Returned id array count: 100000
Insert 100000 entities No.0 totally cost: 1262 ms
Build entities No.1 begin...
Build entities No.1 totally cost: 1190 ms
Insert 100000 entities No.1 begin...
Insert rpc failed!
InsertEntities function call status: Socket closed
Returned id array count: 100000
Insert 100000 entities No.1 totally cost: 304 ms
Build entities No.2 begin...
Build entities No.2 totally cost: 1175 ms
Insert 100000 entities No.2 begin...
Insert rpc failed!
InsertEntities function call status: failed to connect to all addresses
Returned id array count: 100000
Insert 100000 entities No.2 totally cost: 293 ms
Build entities No.3 begin...
Build entities No.3 totally cost: 1185 ms
Insert 100000 entities No.3 begin...
Insert rpc failed!
InsertEntities function call status: failed to connect to all addresses
Returned id array count: 100000
Insert 100000 entities No.3 totally cost: 269 ms
Build entities No.4 begin...
Build entities No.4 totally cost: 1183 ms
Insert 100000 entities No.4 begin...
Insert rpc failed!
InsertEntities function call status: failed to connect to all addresses
Returned id array count: 100000
Insert 100000 entities No.4 totally cost: 270 ms
Flush begin...
Flush gRPC failed!
Flush function call status: OK
Flush totally cost: 0 ms
ShowCollectionInfo gRPC failed!
failed to connect to all addresses
Collection info: 
GetCollectionStats function call status: failed to connect to all addresses
GetEntityByID begin...
GetVectorByID rpc failed!
GetEntityByID function call status: failed to connect to all addresses
GetEntityByID totally cost: 0 ms
Create index begin...
Wait until create all index done
===========================================
Index collection name: C_2021_3_4_12_14_5
Index type: IVFFLAT
Index extra_params: {"nlist":16384}
===========================================
CreateIndex rpc failed!
CreateIndex function call status: failed to connect to all addresses
DescribeIndex rpc failed!
GetIndexInfo function call status: failed to connect to all addresses
===========================================
Index collection name: 
Index type: Unknown index type
Index extra_params: 
===========================================
Create index totally cost: 0 ms
ShowCollectionInfo gRPC failed!
failed to connect to all addresses
Collection info: 
GetCollectionStats function call status: failed to connect to all addresses
Delete entity: 	50000	150000
DeleteByID gRPC failed!
DeleteByID function call status: failed to connect to all addresses
Flush begin...
Flush gRPC failed!
Flush function call status: OK
Flush totally cost: 0 ms
Compact begin...
Compact gRPC failed!
CompactCollection function call status: failed to connect to all addresses
Compact totally cost: 0 ms
Preload begin...
PreloadCollection gRPC failed!
PreloadCollection function call status: failed to connect to all addresses
Preload totally cost: 0 ms
===========================================
Search begin...
Search rpc failed!
failed to connect to all addresses
Search function call status: failed to connect to all addresses
===========================================
Search totally cost: 0 ms
===========================================
Returned result count: 0
ERROR: Returned result count not equal nq
===========================================
===========================================
DropIndex gRPC failed!
DropIndex function call status: failed to connect to all addresses
CountCollection rpc failed!
C_2021_3_4_12_14_5(-1 rows)
DropCollection gRPC failed!
DropCollection function call status: failed to connect to all addresses
Client stop...
Destroy connection function call status: OK

**Comment by cocodee** [comment]
2021-03-04 03:44:51,930 ERROR [default] [SERVER][GetSysCgroupMemLimit][milvus_server] Failed to read /sys/fs/cgroup/memory/memory.limit_in_bytes, reason: basic_ios::clear: iostream error
WARNNING: You are using SQLite as the meta data management, which can't be used in production. Please change it to MySQL!
Supported CPU instruction sets: avx512, avx2, sse4_2
FAISS hook AVX512
free(): invalid pointer

**Comment by yhmo** [comment]
I could not reproduce this error. 
- Your operation system is?
- Is the file exist?  '/sys/fs/cgroup/memory/memory.limit_in_bytes'
- Your milvus server is run from docker or compiled by your self?
- Any change to the server_config.yaml file?

**Comment by cocodee** [comment]
using docker/cpu/ubuntu18.04/Dockerfile docker images fix this
