### ISSUE TITLE
C++ SDK build error

### ISSUE THREAD

**Issue by yinpeng1993** [milvus-io/milvus#4776]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
I complie the c++ sdk from source code, when I run the build.sh , following error I got:
![error](https://user-images.githubusercontent.com/31834016/109942503-390bfb00-7d0f-11eb-9ce0-e7d02753c2a3.PNG)

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [x] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)
os: centos7u2
gcc: 4.8.5
cmake: 3.19.2

- Milvus version (master or released version)
0.10.6

**Comment by fishpenguin** [comment]
Did you install protobuf in your machine before run this build.sh?

**Comment by yinpeng1993** [comment]
no， only installed gcc and cmake.

**Comment by fishpenguin** [comment]
Can you upgrade you gcc to version 7.5?

**Comment by yinpeng1993** [comment]
I have upgraded gcc to 7.5, but it not work.
![error](https://user-images.githubusercontent.com/31834016/110053322-24be1180-7d94-11eb-862b-8ae175e8053b.PNG)

**Comment by yinpeng1993** [comment]
I upgrade gcc and  all it's dependencies, and it worked. Thanks you.

**Comment by yhmo** [comment]
This issue is done
