### ISSUE TITLE
Warning adding id=1024803688 to bloom filter: 4 bit counter Overflow

### ISSUE THREAD

**Issue by NotSky** [milvus-io/milvus#4780]
client.insertAsync(insertParam)

2021-03-04 06:59:14,663][WARNING][ENGINE][Add][milvus_server] Warning adding id=1024813563 to bloom filter: 4 bi
t counter Overflow
[2021-03-04 06:59:14,663][WARNING][ENGINE][Add][milvus_server] Warning adding id=1024809785 to bloom filter: 4 bi
t counter Overflow
[2021-03-04 06:59:14,663][WARNING][ENGINE][Add][milvus_server] Warning adding id=1024767638 to bloom filter: 4 bi
t counter Overflow
[2021-03-04 06:59:14,663][WARNING][ENGINE][Add][milvus_server] Warning adding id=1024772303 to bloom filter: 4 bi
t counter Overflow
[2021-03-04 06:59:14,663][WARNING][ENGINE][Add][milvus_server] Warning adding id=1023340892 to bloom filter: 4 bi
t counter Overflow
[2021-03-04 06:59:14,663][WARNING][ENGINE][Add][milvus_server] Warning adding id=1024745932 to bloom filter: 4 bi
t counter Overflow
[2021-03-04 06:59:14,663][WARNING][ENGINE][Add][milvus_server] Warning adding id=1022513069 to bloom filter: 4 bi
t counter Overflow
[2021-03-04 06:59:14,663][WARNING][ENGINE][Add][milvus_server] Warning adding id=1024753185 to bloom filter: 4 bi
t counter Overflow
[2021-03-04 06:59:14,663][WARNING][ENGINE][Add][milvus_server] Warning adding id=1024780741 to bloom filter: 4 bi
t counter Overflow
[2021-03-04 06:59:14,663][WARNING][ENGINE][Add][milvus_server] Warning adding id=1024803340 to bloom filter: 4 bi
t counter Overflow
[2021-03-04 06:59:14,663][WARNING][ENGINE][Add][milvus_server] Warning adding id=1024788779 to bloom filter: 4 bi
t counter Overflow
[2021-03-04 06:59:14,663][WARNING][ENGINE][Add][milvus_server] Warning adding id=1024774555 to bloom filter: 4 bi
t counter Overflow
[2021-03-04 06:59:14,663][WARNING][ENGINE][Add][milvus_server] Warning adding id=1024254835 to bloom filter: 4 bi
t counter Overflow
[2021-03-04 06:59:14,663][WARNING][ENGINE][Add][milvus_server] Warning adding id=1024774945 to bloom filter: 4 bi
t counter Overflow
[2021-03-04 06:59:14,663][WARNING][ENGINE][Add][milvus_server] Warning adding id=1024782838 to bloom filter: 4 bi
t counter Overflow
[2021-03-04 06:59:14,663][WARNING][ENGINE][Add][milvus_server] Warning adding id=1024791805 to bloom filter: 4 bi
t counter Overflow
[2021-03-04 06:59:14,663][WARNING][ENGINE][Add][milvus_server] Warning adding id=1024801586 to bloom filter: 4 bi
t counter Overflow
[2021-03-04 06:59:14,663][WARNING][ENGINE][Add][milvus_server] Warning adding id=1024803688 to bloom filter: 4 bi
t counter Overflow

![image](https://user-images.githubusercontent.com/5802285/110061073-dfa0dc00-7da1-11eb-9962-64ebcebf0d7a.png)

**Comment by shengjun1985** [comment]
Thanks for finding the problem.
But which version do you use, and how can we reproduce this problem?

**Comment by NotSky** [comment]
> Thanks for finding the problem.
> But which version do you use, and how can we reproduce this problem?

milvus:0.10.5-cpu-d010621-4eda95

**Comment by NotSky** [comment]
> Thanks for finding the problem.
> But which version do you use, and how can we reproduce this problem?

Linux version 4.18.0-147.5.1.el8_1.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 8.3.1 20190507 (Red Hat 8.3.1-4) (GCC)) #1 SMP Wed Feb 5 02:00:39 UTC 2020

**Comment by NotSky** [comment]
批量写入步骤：
用一个线程安全的集合接收向量，当集合大小>=10000的时候，调用client.insertAsync(insertParam)，然后clear这个集合。
========
向量维度：512
insert_buffer_size:1GB
cache_size: 8GB
最终结果是一条都没写进去。
=============
如果单条写入是可以的。

**Comment by shengjun1985** [comment]
Our local test found that if there are a large number of duplicate IDs, there will be this error.
Excuse me, how about your IDs?

**Comment by NotSky** [comment]
上面的图里不是有一堆id吗？例如：1024803688

**Comment by shengjun1985** [comment]
I have another question.
Is your ID generated by the system or specified by yourself?

**Comment by shengjun1985** [comment]
The direct reason for this issue is that there are too many hash conflicts when processing IDs.
At present, I'm not sure whether the hash space is too small or the IDs themselves has a lot of repetitions.

**Comment by yhmo** [comment]
In milvus, each segment has a bloom filter, the bloom filter capacity is 500000, this value is a hard code. If a segment row count is much greater than this value(500000), user may encounter this warning. This warning doesn't block the main functions, but will decrease the effectiveness of bloom filter, for example: get_entigy_by_id() will read more segments from disk. 

A segment row count is mainly affected by index_file_size and vector dimension. For example, if the index_file_size = 1024MB, vector dimension = 256, each segment row count is 100000. But if index_file_size = 1024MB, vector dimension is 8, then each segment row count will be 3200000, this is much greater than 500000, user may encounter this warning.

Could you tell us:
1. the value of index_file_size of your collection
2. the vector dimension of your collection

**Comment by shengjun1985** [comment]
It has been connect offline.
"index_file_size" is 1024; "IDs" is provided by other system and "dim" is 512.
Thus, each segment row count should be about 520000.

**Comment by ykllllll** [comment]
I also encountered the same problem
![image](https://user-images.githubusercontent.com/49083553/110764525-20ab5b80-828e-11eb-9a69-2eaffeb8dfea.png)
index_file_size:1024
dimension: 512

**Comment by yhmo** [comment]
> I also encountered the same problem
> ![image](https://user-images.githubusercontent.com/49083553/110764525-20ab5b80-828e-11eb-9a69-2eaffeb8dfea.png)
> index_file_size:1024
> dimension: 512

This warning has two possible reason:
1. segment's row count exceed 500000
2. more than 15 duplicate id, for example, you insert 20 vectors in one time with same id, you will get this warning.

**Comment by ykllllll** [comment]
Because of business requirements, the data I insert will contain a large number of duplicate IDs. How can I solve this problem?

**Comment by yhmo** [comment]
> Because of business requirements, the data I insert will contain a large number of duplicate IDs. How can I solve this problem?

This warning doesn't affect main function such as search. It only affect the performance of some api such get_entity_by_id().

**Comment by ykllllll** [comment]
> > Because of business requirements, the data I insert will contain a large number of duplicate IDs. How can I solve this problem?
> 
> This warning doesn't affect main function such as search. It only affect the performance of some api such as get_entity_by_id().

Thank you for the reply

**Comment by yhmo** [comment]
> > > Because of business requirements, the data I insert will contain a large number of duplicate IDs. How can I solve this problem?
> > 
> > 
> > This warning doesn't affect main function such as search. It only affect the performance of some api such as get_entity_by_id().
> 
> Thank you for the reply

By the way, if there are lot of duplicate IDs, the search() will return result contains duplicate id. For example, you insert lot of id=88, then search, the search() return result like this:
```
id=88, distance=0.1
id=88, distance=0.2
id=88, distance=0.3
id=88, distance=0.4
id=88, distance=0.5
```
Can this kind of result meet your business requirement?

**Comment by ykllllll** [comment]
Yes, because the images come from the same video, the video ID is returned


---Original---
From: ***@***.***&gt;
Date: Thu, Mar 11, 2021 17:53 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [milvus-io/milvus] Warning adding id=1024803688 to bloom filter: 4 bit counter Overflow (#4780)




    
Because of business requirements, the data I insert will contain a large number of duplicate IDs. How can I solve this problem?
  
This warning doesn't affect main function such as search. It only affect the performance of some api such as get_entity_by_id().
  
Thank you for the reply
  
By the way, if there are lot of duplicate IDs, the search() will return result contains duplicate id. For example, you insert lot of id=88, then search, the search() return result like this:
 id=88, distance=0.1 id=88, distance=0.2 id=88, distance=0.3 id=88, distance=0.4 id=88, distance=0.5  
Can this kind of result meet your business requirement?

**Comment by yhmo** [comment]
> Yes, because the images come from the same video, the video ID is returned


For this kind of usage. I suggest use a combine id, combine from video id and image id. 
Each id is a 64 bit integer, for example, you can use the front 16 bit to represent video id, and the last 48 bit for image id. This can make sure each id is unique. When you get result from search(), you get the id, pick the front 16 bit as video id.

**Comment by ykllllll** [comment]
> > Yes, because the images come from the same video, the video ID is returned
> 
> For this kind of usage. I suggest use a combine id, combine from video id and image id.
> Each id is a 64 bit integer, for example, you can use the front 16 bit to represent video id, and the last 48 bit for image id. This can make sure each id is unique. When you get result from search(), you get the id, pick the front 16 bit as video id.

yes,it's a good idea.
