### ISSUE TITLE
milvus.client.exceptions.VersionError

### ISSUE THREAD

**Issue by eeezae** [milvus-io/milvus#4786]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
>>> milvus = Milvus(MILVUS_HOST, MILVUS_PORT, pool_size=10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mc/opt/anaconda3/lib/python3.8/site-packages/milvus/client/stub.py", line 97, in __init__
    self._pool = SingletonThreadPool(pool_uri, **pool_kwargs)
  File "/Users/mc/opt/anaconda3/lib/python3.8/site-packages/milvus/client/pool.py", line 226, in __init__
    self._prepare()
  File "/Users/mc/opt/anaconda3/lib/python3.8/site-packages/milvus/client/pool.py", line 237, in _prepare
    raise VersionError(
milvus.client.exceptions.VersionError: Version of python SDK(1.0.0) not match that of server0.10.0, excepted is ('1.0.x',)
```

**Method of installation**
- [x ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)
Macos, i5-8250u, No GPU, 8gb

- Milvus version (master or released version)
milvusdb/milvus:0.10.0-cpu-d061620-5f3c00

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by eeezae** [comment]
pymilvus version is 1.0.0

**Comment by shanghaikid** [comment]
![image](https://user-images.githubusercontent.com/185051/110200362-8667a400-7e98-11eb-8de2-7df8cacdc324.png)
@eeezae if you are on milvus:0.10.0, you should use pymilvus 0.2.14

**Comment by eeezae** [comment]
It works now, thanks a lot.
