### ISSUE TITLE
EM has not supported to import binary vectors

### ISSUE THREAD

**Issue by jolejian2012** [milvus-io/milvus#4791]
em的import vector只支持float。binary方面还不支持，请官方大神能及时修正

**Comment by shanghaikid** [comment]
We will add it soon. Stay tuned.

**Comment by nameczz** [comment]
> em的import vector只支持float。binary方面还不支持，请官方大神能及时修正

I found em already support binary vector. 
If your collection dimension is 16, your vector need looks like [1,2]. 
Every value means int8. 
So dimension need to be multiples of 8.

**Comment by shengjun1985** [comment]
If you have more questions, please continue to contact our community.
