### ISSUE TITLE
If any document about data-migration in k8s-milvus-deployment scenario

### ISSUE THREAD

**Issue by innerNULL** [milvus-io/milvus#4795]
In the [QA](https://milvus.io/cn/docs/v0.10.6/operational_faq.md), there are some introductions about how to migrate milvus db data in standalone mode (by copy the data), but how can I do it if I deploy the milvus service on k8s? 

For example, for now we deployed old version of milvus on our k8s, but how should we migrate our data if we plan upgrade our milvus cluster to newer version?

THANKS

**Comment by yhmo** [comment]
Milvus data is compatible from 0.7.x to 0.10.x.  You can specify new milvus version in k8s yaml config file and restart the service.
If you encounter any problem, please let us know.

**Comment by innerNULL** [comment]
> Milvus data is compatible from 0.7.x to 0.10.x. You can specify new milvus version in k8s yaml config file and restart the service.
> If you encounter any problem, please let us know.

@yhmo got it, thanks~
