### ISSUE TITLE
DSL & adding metadata with vectors in 1.0.0

### ISSUE THREAD

**Issue by suvashishtha** [milvus-io/milvus#4799]
Does milvus 1.0.0 supports adding metadata to vectors and hybrid search with DSL? These features are available in milvus 0.10.6 milvus-sdk-java 0.8.6 but absent from 1.0.0. Is it intended?

**Comment by yhmo** [comment]
@suvashishtha 
The DSL and hibrid search is experimental in 0.10.x, not fully tested, so we remove it from v1.0.
If you require this feature, you can keep using 0.10.6. Until our new milvus published, the new milvus has this feature, and it supports both distributed/stand-alone mode. We plan to publish the new milvus at the end of this month. But I think we still need a lot of work to make the new milvus to be stable after we publish it, so you may keep using 0.10.6 for a couple of months.
We will also provide data extract/migration tool for user upgrade from old milvus to new milvus.

**Comment by yhmo** [comment]
Close this issue since the question has been answered.
