### ISSUE TITLE
Compile milvus on linux or mac

### ISSUE THREAD

**Issue by ChunelFeng** [milvus-io/milvus#4801]
如题，请给出对应文档

**Comment by yhmo** [comment]
mac上编不过，只能用ubuntu或者centos。可以参考这个： https://zhuanlan.zhihu.com/p/272746341

**Comment by ChunelFeng** [comment]
阿里云esc可以跑起来么，用的是ubuntu-20.04系统，没有gpu环境。

**Comment by shengjun1985** [comment]
We haven't tested in that environment.
But for security, you can test in a docker. Please refer to [compile-milvus-on-docker](https://github.com/milvus-io/milvus/blob/1.x/INSTALL.md#compile-milvus-on-docker).

**Comment by ChunelFeng** [comment]
> We haven't tested in that environment.
> But for security, you can test in a docker. Please refer to [compile-milvus-on-docker](https://github.com/milvus-io/milvus/blob/1.x/INSTALL.md#compile-milvus-on-docker).

if u want to try this environment, u can use my esc to try. please connect me as free when u need.

**Comment by yhmo** [comment]
> > We haven't tested in that environment.
> > But for security, you can test in a docker. Please refer to [compile-milvus-on-docker](https://github.com/milvus-io/milvus/blob/1.x/INSTALL.md#compile-milvus-on-docker).
> 
> if u want to try this environment, u can use my esc to try. please connect me as free when u need.



> 阿里云ecs可以跑起来么，用的是ubuntu-20.04系统，没有gpu环境。
> 码农小白，不了解gpu和相关环境操作。

没有gpu可以编译cpu版本。说实话我们也没在阿里云上以及unbuntu20上编译过。问题是，你如果缺少码农领域的知识，编译出来也没有意义啊。如果只是使用milvus而不是研究代码的话，按照文档里的步骤启动一个milvus的docker容器就能用了。同样，在mac下也可以很方便地启动milvus的docker容器使用。基本步骤就如https://www.milvus.io/cn/docs/milvus_docker-cpu.md里所述。

**Comment by shengjun1985** [comment]
If you have more questions, please continue to contact our community.
