### ISSUE TITLE
parameter of logs section doesn't work:  log_rotate_num

### ISSUE THREAD

**Issue by orange-jams** [milvus-io/milvus#4802]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
I have set log_rotate_num to 1,actually there are more than ten files for each logging level.

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
0.10.5

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
I did some test:
1. set log_rotate_num = 1:
    set max_log_file_size = 600MB
```
 logs:
  level: debug
  trace.enable: true
  path: /tmp/milvus/logs
  max_log_file_size: 600MB
  log_rotate_num: 1
  log_to_stdout: false
  log_to_file: true
```

2. start milvus server, continually insert vectors, the log file size larger and larger
   after long time, take a look at logs folder, seems no problem:
   I saw "xxx.debug.log" and "xxx.debug.log.5", that means some log files have been deleted (xxx.debug.log.1 to xxx.debug.log.4)
![222](https://user-images.githubusercontent.com/2282099/110911380-94f90400-834d-11eb-9a88-2604208f15e6.png)

**Comment by shengjun1985** [comment]
If you have more questions, please continue to contact our community.
