### ISSUE TITLE
The amount of inserted data doesn't match the amount of stored data in Milvus 

### ISSUE THREAD

**Issue by Chisdo** [milvus-io/milvus#4805]
【PROBLEM SOLVED！】
**Describe the bug**
ISSUE: The amount of inserted data doesn't match the amount of stored data in Milvus.

** Environment **
Deploy mishards by using the method mentioned @ https://milvus.io/docs/v1.0.0/mishards.md:
 - cd ./milvus/shards
 - sudo make deploy

** behaviour **
milvus = Milvus(host, port)
status, ids = milvus_conn.insert(
            collection_name=collection_name,
            records=vectors,
            partition_tag=partition_name,
            ids=vector_ids
        )

** expected behavior ** 
The insertion number is equal to the number inserted in milvus DB.

** actual behavior **
The number is not matched.

** SOLUTION **
I solved the insertion problem by using MySQL to save metadata.
[The method is from official website: https://milvus.io/docs/v1.0.0/data_manage.md]

**Comment by yhmo** [comment]
Could it be reproduced?
Please provide more information, such as steps description, script, screen shot, etc.

**Comment by Chisdo** [comment]
Thx for replying @yhmo. I solved the insertion problem by using MySQL to save metadata.

**Comment by Chisdo** [comment]
** SOLUTION **
I solved the insertion problem by using MySQL to save metadata.
[The method is from official website: https://milvus.io/docs/v1.0.0/data_manage.md]
