### ISSUE TITLE
Failed to connect to Milvus server: io.milvus.client.ConnectFailedException: Channel is not shutdown or terminated

### ISSUE THREAD

**Issue by zhouxiupeng** [milvus-io/milvus#4807]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [* ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)
Linux milvus_hb2e 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Milvus version (master or released version)
milvus-sdk-java-0.8.22
milvus:0.10.0-cpu-d061620-5f3c00

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`
version: 0.5
cluster:
  enable: false
  role: rw

general:
  timezone: UTC+8
  meta_uri: mysql://milvus:mil.....
network:
  bind.address: 0.0.0.0
  bind.port: 19530
  http.enable: true
  http.port: 19121

storage:
  path: /var/lib/milvus
  auto_flush_interval: 1
wal:
  enable: true
  recovery_error_ignore: false
  buffer_size: 512MB
  path: /var/lib/milvus/wal
cache:
  cache_size: 40GB
  insert_buffer_size: 1GB
  preload_collection:
gpu:
  enable: false
   .....
logs:
  level: debug
  trace.enable: true
  path: /var/lib/milvus/logs
  max_log_file_size: 1024MB
  log_rotate_num: 0
metric:
  enable: false
  address: 127.0.0.1
  port: 9091
```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**
Create a connection

String host = BasicParameter.milvus_server_ip;
int port = Integer.parseInt(BasicParameter.milvus_server_port);		
ConnectParam connectParam = new ConnectParam.Builder().withHost(host).withPort(port).build();
Response connectResponse = milvusClient.connect(milvusConnectParam);

Because it is a background program, the program starts to create a good connection. 
If there is no data, the connection is not closed.
Before using the connection, I first judge whether the connection is valid:
if (!milvusClient.isConnected()) {
try {
	String host = BasicParameter.milvus_server_ip;
         int port = Integer.parseInt(BasicParameter.milvus_server_port);
				
	ConnectParam connectParam = new ConnectParam.Builder().withHost(host).withPort(port).build();
	Response connectResponse = milvusClient.connect(milvusConnectParam);
	
	} catch (ConnectFailedException e) {
				logger.error("Failed to connect to Milvus server: " + e.toString());
				e.printStackTrace();
}
}
I found that this failed to create the connection again, and I would prompt:
Failed to connect to Milvus server: io.milvus.client.ConnectFailedException: Channel is not shutdown or terminated

**Comment by zhouxiupeng** [comment]
就是说，创建了连接，连接长时间不用，会自动断开。断开后，再用 milvusClient.connec 进行连接，还是不能不连接。目前采用办法是把应用重启一下，重启之后就好了。除了重启之外，应该能有其他办法吧?

**Comment by yhmo** [comment]
What is the class of the "milvusClient"?
In milvus java sdk, the MilvusGrpcClient has no such methods: connect(), isConnected()

**Comment by zhouxiupeng** [comment]
MilvusClient milvusClient = new MilvusGrpcClient();

**Comment by zhouxiupeng** [comment]
import io.milvus.client.MilvusClient;
import io.milvus.client.MilvusGrpcClient;
MilvusClient milvusClient = new MilvusGrpcClient();
ConnectParam milvusConnectParam= new ConnectParam.Builder().withHost(BasicParameter.milvus_server_ip)
				.withPort(Integer.parseInt(BasicParameter.milvus_server_port)).build();
Response connectResponse = milvusClient.connect(milvusConnectParam);
使用之前，我都是先判断 	if (milvusClient.isConnected()) {
如果没有连接，我在重新创建连接。再重新创建连接时，会报:Channel is not shutdown or terminated 异常信息。

**Comment by zhouxiupeng** [comment]
具体再创建连接的代码如下：
if (!milvusClient.isConnected()) {
				try {
					milvusConnectParam = new ConnectParam.Builder().withHost(BasicParameter.milvus_server_ip)
							.withPort(Integer.parseInt(BasicParameter.milvus_server_port)).build();
					
					Response connectResponse = milvusClient.connect(milvusConnectParam);
					logger.info(connectResponse.getMessage() + "|" + connectResponse.ok() + "|"
							+ connectResponse.toString());
				} catch (ConnectFailedException e) {
					logger.error("Failed to connect to Milvus server: " + e.toString());
                                         这里会提示那个异常信息
					e.printStackTrace();
				}
			}

**Comment by yhmo** [comment]
There is an issue about this: https://github.com/milvus-io/milvus-sdk-java/issues/117
The connect()/isConnected() is removed after v0.8.4. 

_The reason is that, according to gRPC documentation, it is not recommended to check whether connectivity is set successfully by ConnectivityState (it is an experimental API). Instead, you can just start the server and start sending RPC requests. This will wake up the connection and enable subsequent communications. There is no need to check if Milvus server is connected before each API call._

_From Milvus 0.10.1 onwards, if you want to use Java SDK, simply establish a connection via operations (e.g. insert/query). isConnect is unnecessary._

So, with 0.8.2, in your client code, no need to reuse the milvusClient object. If its connection is lost, just re-create a new MilvusGrpcClient.

**Comment by zhouxiupeng** [comment]
Thank you very much.
