### ISSUE TITLE
the example links is gone

### ISSUE THREAD

**Issue by willdx99j3** [milvus-io/milvus#4808]
Hi Team,

When I try to read https://github.com/milvus-io/pymilvus/blob/1.0.1/examples/example.py, it returns 404, could you please kindly check?

Thanks in advance!

**Comment by matrixji** [comment]
I guess it should be link to https://github.com/milvus-io/pymilvus/blob/v1.0.1/examples/example.py

**Comment by shengjun1985** [comment]
@willdx99j3
Thanks for finding the problem.
But where did you click this link?

**Comment by willdx99j3** [comment]
https://milvus.io/docs/v1.0.0/example_code.md

> @willdx99j3
> Thanks for finding the problem.
> But where did you click this link?

https://milvus.io/docs/v1.0.0/example_code.md

**Comment by shengjun1985** [comment]
Thanks all. It is fixed now.
