### ISSUE TITLE
milvus c++ sdk build error: downloading 'https://github.com/madler/zlib/archive/v1.2.11.tar.gz' failed

### ISSUE THREAD

**Issue by GreenValue** [milvus-io/milvus#4809]
**Enviroment**
LSB Version:	core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

**Failed in downloading v1.2.11.tar.gz**
But I downloaded  v1.2.11.tar.gz by wget, so I'm sure net is ok.

**log**
```root@ppress-202012:/usr/work/src/milvus/sdk# ./build.sh 
cmake -DCMAKE_BUILD_TYPE=Debug ../
-- The CXX compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Third Party MAKE_BUILD_ARGS = -j8
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Building GRPC-master from source
-- Building ZLIB-v1.2.11 from source
-- Build type = Debug
-- Build type = Debug
-- Building milvus_sdk on x86 architecture
-- Could NOT find Python (missing: Python_LIBRARY Python_INCLUDE_DIR Development) (found version "2.7.17")
clang-tidy not found
clang-format not found
-- Found cpplint executable at /usr/work/src/milvus/sdk/build-support/cpplint.py
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/work/src/milvus/sdk/cmake_build
Scanning dependencies of target zlib_ep
[  2%] Creating directories for 'zlib_ep'
[  5%] Performing download step (download, verify and extract) for 'zlib_ep'
-- Downloading...
   dst='/usr/work/src/milvus/sdk/cmake_build/zlib_ep-prefix/src/v1.2.11.tar.gz'
   timeout='none'
-- Using src='https://github.com/madler/zlib/archive/v1.2.11.tar.gz'
-- Retrying...
-- Using src='https://github.com/madler/zlib/archive/v1.2.11.tar.gz'
-- Retry after 5 seconds (attempt #2) ...
-- Using src='https://github.com/madler/zlib/archive/v1.2.11.tar.gz'
-- Retry after 5 seconds (attempt #3) ...
-- Using src='https://github.com/madler/zlib/archive/v1.2.11.tar.gz'
-- Retry after 15 seconds (attempt #4) ...
-- Using src='https://github.com/madler/zlib/archive/v1.2.11.tar.gz'
-- Retry after 60 seconds (attempt #5) ...
-- Using src='https://github.com/madler/zlib/archive/v1.2.11.tar.gz'
CMake Error at zlib_ep-stamp/download-zlib_ep.cmake:159 (message):
  Each download failed!

    error: downloading 'https://github.com/madler/zlib/archive/v1.2.11.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'https://github.com/madler/zlib/archive/v1.2.11.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'https://github.com/madler/zlib/archive/v1.2.11.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'https://github.com/madler/zlib/archive/v1.2.11.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'https://github.com/madler/zlib/archive/v1.2.11.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'https://github.com/madler/zlib/archive/v1.2.11.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         
    


CMakeFiles/zlib_ep.dir/build.make:90: recipe for target 'zlib_ep-prefix/src/zlib_ep-stamp/zlib_ep-download' failed
make[2]: *** [zlib_ep-prefix/src/zlib_ep-stamp/zlib_ep-download] Error 1
CMakeFiles/Makefile2:82: recipe for target 'CMakeFiles/zlib_ep.dir/all' failed
make[1]: *** [CMakeFiles/zlib_ep.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by yhmo** [comment]
A workaround:
1. import the https://github.com/madler/zlib to Gitee, you can refer this article: https://www.pianshen.com/article/30731204310/
2. replace the download url in the /milvus/sdk/cmake/ThirdPartyPackages.cmake,  line No.194
    `set(ZLIB_SOURCE_URL "https://github.com/madler/zlib/archive/v1.2.11.tar.gz")`
    change the url to gitee address that you import in the step 1
3. compile the sdk project

**Comment by matrixji** [comment]
As I see logs contains: 
```
Protocol "https" not supported or disabled in libcurl
```

I suggest check which curl are used in your ubuntu first. @GreenValue 
```bash
which curl
curl --version
```

I guess you may build a curl from source without ssl/https support.

**Comment by GreenValue** [comment]
@matrixji  
curl has support https as below.
root@ppress-202012:/usr/work/src/milvus/sdk# which curl
/usr/bin/curl
root@ppress-202012:/usr/work/src/milvus/sdk# curl --version
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

**Comment by GreenValue** [comment]
The download error can not be sovled by replace url from 	[https://github.com/madler/zlib/archive/v1.2.11.tar.gz]() to	[https://gitee.com/zhaozhongchen/zlib/archive/v1.2.11.tar.gz]().

so , i set MILVUS_WITH_ZLIB to OFF as below, then build, but another error come.
![image](https://user-images.githubusercontent.com/16701660/111109708-3a061d80-8596-11eb-8992-1218edebab20.png)

Scanning dependencies of target grpc_ep
make[2]: *** No rule to make target '../zlib_ep', needed by 'grpc_ep-prefix/src/grpc_ep-stamp/grpc_ep-build'.  Stop.
CMakeFiles/Makefile2:134: recipe for target 'CMakeFiles/grpc_ep.dir/all' failed
make[1]: *** [CMakeFiles/grpc_ep.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by GreenValue** [comment]
Is check_file_hash function right?

root@ppress-202012:/usr/work/src/milvus/sdk/cmake_build/grpc_ep-prefix/src# cat /usr/work/src/milvus/sdk/cmake_build/zlib_ep-prefix/src/zlib_ep-stamp/download-zlib_ep.cmake 
```
# Distributed under the OSI-approved BSD 3-Clause License.  See accompanying
# file Copyright.txt or https://cmake.org/licensing for details.

cmake_minimum_required(VERSION 3.5)

function(check_file_hash has_hash hash_is_good)
  if("${has_hash}" STREQUAL "")
    message(FATAL_ERROR "has_hash Can't be empty")
  endif()

  if("${hash_is_good}" STREQUAL "")
    message(FATAL_ERROR "hash_is_good Can't be empty")
  endif()

  if("" STREQUAL "") #？？？？ maybe wrong here ？？？？
    # No check
    set("${has_hash}" FALSE PARENT_SCOPE)
    set("${hash_is_good}" FALSE PARENT_SCOPE)
    return()
  endif()

  set("${has_hash}" TRUE PARENT_SCOPE)

  message(STATUS "verifying file...
       file='/usr/work/src/milvus/sdk/cmake_build/zlib_ep-prefix/src/v1.2.11.tar.gz'")

  file("" "/usr/work/src/milvus/sdk/cmake_build/zlib_ep-prefix/src/v1.2.11.tar.gz" actual_value)

  if(NOT "${actual_value}" STREQUAL "")
    set("${hash_is_good}" FALSE PARENT_SCOPE)
    message(STATUS " hash of
    /usr/work/src/milvus/sdk/cmake_build/zlib_ep-prefix/src/v1.2.11.tar.gz
  does not match expected value
    expected: ''
      actual: '${actual_value}'")
  else()
    set("${hash_is_good}" TRUE PARENT_SCOPE)
  endif()
endfunction()
```

**Comment by yhmo** [comment]
**Dont** set MILVUS_WITH_ZLIB to OFF, because grpc require zlib as dependency.

I import grpc and zlib to my gitee account, and replace the url to gitee, I can compile successfully.
You can use my url to try:
```
if (DEFINED ENV{MILVUS_GRPC_URL})
    set(GRPC_SOURCE_URL "$ENV{MILVUS_GRPC_URL}")
else ()
    set(GRPC_SOURCE_URL
            "https://gitee.com/yhmo/grpc-milvus/repository/archive/master.zip")
endif ()

if (DEFINED ENV{MILVUS_ZLIB_URL})
    set(ZLIB_SOURCE_URL "$ENV{MILVUS_ZLIB_URL}")
else ()
    set(ZLIB_SOURCE_URL "https://gitee.com/yhmo/zlib/repository/archive/master.zip")
endif ()
```

> The download error can not be sovled by replace url from https://github.com/madler/zlib/archive/v1.2.11.tar.gz to https://gitee.com/zhaozhongchen/zlib/archive/v1.2.11.tar.gz.
> 
> so , i set MILVUS_WITH_ZLIB to OFF as below, then build, but another error come.
> ![image](https://user-images.githubusercontent.com/16701660/111109708-3a061d80-8596-11eb-8992-1218edebab20.png)
> 
> Scanning dependencies of target grpc_ep
> make[2]: *** No rule to make target '../zlib_ep', needed by 'grpc_ep-prefix/src/grpc_ep-stamp/grpc_ep-build'. Stop.
> CMakeFiles/Makefile2:134: recipe for target 'CMakeFiles/grpc_ep.dir/all' failed
> make[1]: *** [CMakeFiles/grpc_ep.dir/all] Error 2
> Makefile:129: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by GreenValue** [comment]
replace your url also could not solve download error。

**maybe camke has something wrong. 
camke was build from source， but it seemd not link to any libcurl.so**.

```
root@ppress-202012:/usr/work/soft/cmake-3.15.3# cmake --version
cmake version 3.15.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
root@ppress-202012:/usr/work/soft/cmake-3.15.3# whereis cmake
cmake: /usr/bin/cmake /usr/local/bin/cmake /usr/share/cmake
root@ppress-202012:/usr/work/soft/cmake-3.15.3# ldd /usr/bin/cmake
	linux-vdso.so.1 (0x00007fffbc3ff000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3dec875000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f3dec66d000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3dec44e000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f3dec0c5000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3debd27000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f3debb0f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3deb71e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3ded664000)
root@ppress-202012:/usr/work/soft/cmake-3.15.3# 
```

**Comment by yhmo** [comment]
> replace your url also could not solve download error。
> 
> **maybe camke has something wrong. camke was build from source， but it seemd not link to any libcurl.so**.
> 
> ```
> root@ppress-202012:/usr/work/soft/cmake-3.15.3# cmake --version
> cmake version 3.15.3
> 
> CMake suite maintained and supported by Kitware (kitware.com/cmake).
> root@ppress-202012:/usr/work/soft/cmake-3.15.3# whereis cmake
> cmake: /usr/bin/cmake /usr/local/bin/cmake /usr/share/cmake
> root@ppress-202012:/usr/work/soft/cmake-3.15.3# ldd /usr/bin/cmake
> 	linux-vdso.so.1 (0x00007fffbc3ff000)
> 	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3dec875000)
> 	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f3dec66d000)
> 	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3dec44e000)
> 	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f3dec0c5000)
> 	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3debd27000)
> 	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f3debb0f000)
> 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3deb71e000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00007f3ded664000)
> root@ppress-202012:/usr/work/soft/cmake-3.15.3# 
> ```

I think you need to re-compile your cmake.
Please refer this article: https://zhuanlan.zhihu.com/p/272746341
In the section 4, how to compile cmake to link with curl:

```
wget https://github.com/Kitware/CMake/releases/download/v3.14.0/cmake-3.14.0.tar.gz
tar -zxv -f ./cmake-3.14.0.tar.gz
cd cmake-3.14.0
./bootstrap --system-curl
make
make install
```

**Comment by GreenValue** [comment]
Recompile camke ,then resovled.
Thanks a lot.
Why don't puting  [https://zhuanlan.zhihu.com/p/272746341](url) to sdk build readme?

But Another Erorr come:
```
Makefile:993: recipe for target 'stop' failed
make[3]: *** [stop] Error 1
make[3]: *** Waiting for unfinished jobs....
DEPENDENCY ERROR

The target you are trying to run requires an OpenSSL implementation.
Your system doesn't have one, and either the third_party directory
doesn't have it, or your compiler can't build BoringSSL.

Please consult INSTALL to get more information.

If you need information about why these tests failed, run:

  make run_dep_checks

CMakeFiles/grpc_ep.dir/build.make:114: recipe for target 'grpc_ep-prefix/src/grpc_ep-stamp/grpc_ep-build' failed
make[2]: *** [grpc_ep-prefix/src/grpc_ep-stamp/grpc_ep-build] Error 2
CMakeFiles/Makefile2:164: recipe for target 'CMakeFiles/grpc_ep.dir/all' failed
make[1]: *** [CMakeFiles/grpc_ep.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by yhmo** [comment]
> Recompile camke ,then resovled.
> Thanks a lot.
> Why don't puting [https://zhuanlan.zhihu.com/p/272746341](url) to sdk build readme?
> 
> But Another Erorr come:
> 
> ```
> Makefile:993: recipe for target 'stop' failed
> make[3]: *** [stop] Error 1
> make[3]: *** Waiting for unfinished jobs....
> DEPENDENCY ERROR
> 
> The target you are trying to run requires an OpenSSL implementation.
> Your system doesn't have one, and either the third_party directory
> doesn't have it, or your compiler can't build BoringSSL.
> 
> Please consult INSTALL to get more information.
> 
> If you need information about why these tests failed, run:
> 
>   make run_dep_checks
> 
> CMakeFiles/grpc_ep.dir/build.make:114: recipe for target 'grpc_ep-prefix/src/grpc_ep-stamp/grpc_ep-build' failed
> make[2]: *** [grpc_ep-prefix/src/grpc_ep-stamp/grpc_ep-build] Error 2
> CMakeFiles/Makefile2:164: recipe for target 'CMakeFiles/grpc_ep.dir/all' failed
> make[1]: *** [CMakeFiles/grpc_ep.dir/all] Error 2
> Makefile:129: recipe for target 'all' failed
> make: *** [all] Error 2
> ```

Hmmm... not all developer encounter this problem. But, yes, put it into readme is a good suggestion.

**Comment by yhmo** [comment]
Close issue since it has been resolved.
