### ISSUE TITLE
Support String ID 

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#4810]
Users want  to provide String entity IDs when inserting, deleting, or searching vectors by IDs

1.Insert

When inserting into Milvus, a list of strings will be provided as entity IDs.

When the vector and IDs insertion is completed, the returned result contains the insertion status and IDs, and the entity IDs should be of string type.

API Reference:

insert(collection_name, records, ids=None, partition_tag=None, params=None, timeout=None, **kwargs)

ids (list[str]) -- list of id

Return type (Status, list(str))

2.search

When the user query is completed, the user expects the string ID as the result output.

3.delete /get entity by ID 

User can delete or get the vector by IDS, the IDs passed are required to be a list of string IDs

API Reference:

delete_entity_by_id(collection_name, id_array, timeout=None)

id_array (list[str]) -- list of vector id

get_entity_by_id(collection_name, ids, timeout=None)

ids (list[str]) -- list of vector id

Previous issue Link: https://github.com/milvus-io/milvus/issues/3199

**Comment by yhmo** [comment]
This feature is in progress in v2.0:
https://wiki.lfaidata.foundation/display/MIL/MEP+11+--+Support+String+DataType

**Comment by yhmo** [comment]
Duplicate with #4430, close this one, tracked by #4430
