### ISSUE TITLE
Support search by ID

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#4811]
The user needs an interface to search for ID-based similarity vectors.

API Reference:

search_by_id

(collection_name, ids,top_k, partition_tags=None, params=None, timeout=None, **kwargs)

collection_name (str) -- Name of the collection.

top_k (int) -- number of vertors which is most similar with query vectors

nprobe (int) -- cell number of nprobe

ids (list]) -- list of vector id

partition_tags (list) -- tags to search

User can get the search result as topk similar vectors of the vector corresponding to the IDs

Previous issue Link : https://github.com/milvus-io/milvus/issues/3203

**Comment by cocodee** [comment]
Is there any progress on this issue?

**Comment by yhmo** [comment]
> Is there any progress on this issue?

Milvus v1.x won't support this feature. We will implement it in v2.0. search_by_id() is base on get_vector_by_id(), now the get_vector_by_id() is in developing.

**Comment by yhmo** [comment]
Use #5215 to track this feature, close this one.
