### ISSUE TITLE
Support get entity by id API with partition name

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#4813]
The user wants to specify the partition_name to use the get entity by id API , which can speed up the search process

API Reference:

get_entity_by_id(collection_name, ids,partition_name,timeout=None)

Parameters

partition_name (str) -- Partition Name

**Comment by jingkl** [comment]
For this question refer to the issue:https://github.com/milvus-io/milvus/issues/4564

**Comment by shengjun1985** [comment]
It is planed in 1.1.0.
And let's trace it in issue 4564.
