### ISSUE TITLE
Support for not recording sensitive values in logs

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#4816]
When users use mysql to manage metadata, they need to set the meta_uri parameter in the configuration file. After the configuration is done, the database account and password of the linked MySQL will be printed in the INFO logs, the database password is a sensitive value and should not be shown in the INFO logs

The INFO log form is as follows:

[2021-01-05 10:32:51,288][INFO][SERVER][LogConfigInFile][milvus_server]

Config in file

version: 0.5
cluster:
enable: true
role: ro
general:
timezone: UTC+8
meta_uri: mysql://root:123456@192.168.1.85:3306/milvus

It is recommended to use an encrypted form to display the database password in the INFO log.

For example:

meta_uri: mysql://root:******@192.168.1.85:3306/milvus

Previous issue Link : #4540

**Comment by yhmo** [comment]
duplicated with #4540

**Comment by yhmo** [comment]
Duplicated with #4540, close this one
