### ISSUE TITLE
Support milvus rpm/deb install packages

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#4819]
Users would like us to provide the official Milvus rpm/deb install  packages .

Provide the download path of Milvus rmp/deb package.

If the package suffix rpm can be installed using the command rpm, yum and dnf, If the package suffix deb can be installed using the command dpkg and apt-get

Examples：

wget *********/milvus.rpm

yum install milvus.rpm

Previous issue Link :#3728

**Comment by batara666** [comment]
yes +1
