### ISSUE TITLE
 Support search by distance

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#4821]
The user wants to add an interface to Milvus that searches for vectors based on similarity and will only return results that match the similarity.

API Reference:

search by distance
Find the similar vectors in the specified collection.
search_by_distance(collection_name, query_records，Threshold)
Parameters
collection_name (str) – The name of the collection to insert.
query_recordslist[list[float32]]) -- vectors to query

Threshold(int) –. The value of distance similarity

nprobe (int) -- cell number of probe
Returns
Status: Whether the operation is successful. result: query result
Previous issue Link :#3201

**Comment by yhmo** [comment]
There are some concern points for this feature:
- If the distance is large, there will be millions of vectors included into result, could even break the RPC transport limit.
- For IVF index or HNSW index, it is not easy to set a reasonable parameter such as "nprobe".
- Milvus split vectors to segments to store, to get a search result, milvus need to search segment one by one, and reduce multiple results into one final result. If there are millions of vectors included into result, the sort/reduce will cost lot of time.
- The search_by_distance() parameters are different to search(), maybe we need a "limit" parameter to limit the result count. And a "sort" parameter to specify whether to sort the results. But it is hard to make a decision.

**Comment by shinoys222** [comment]
- The limit value can be restricted from 1 to a reasonable multiple of dimension of the vector to not exceed the rpc transport limit. Sorting may be necessary to not lose the most similar neighbours.
- Instead of specifying a fixed nprobe search param. Does a factor parameter work to calculate nprobe based on threshold distance and the input query vectors?

**Comment by yhmo** [comment]
Hi shinoys,
@shengjun1985 and @op-hunter did some investigations on this issue, I have ask them to consider your suggestions and you can discuss more in this issue.

**Comment by yhmo** [comment]
I think it is not easy to calculate a reasonable nprobe value, we need to know all centers of the buckets, need to know how many vectors in each bucket. And for hnsw or other index type, the thing may be different.

**Comment by shengjun1985** [comment]
(1) About interface
Maximum query batch: ?
query result sort: option
query result limit: option
My suggestion is to add an interface to `knowhere::index` layer first. Then the upper logic can be implemented step by step.

(2) About index
FLAT: Easy
Graph Index(HNSW): The algorithm needs to be implemented.
IVF_FLAT: The algorithm needs to be designed.
IVF_SQ8 / IVF_PQ: The distance information is distorted and it may not support.
My suggestion is to implement them from easy to difficult.

**Comment by op-hunter** [comment]
@shinoys222 Hello, thank you for your vaulable advice. Actually, we had already considered to support the function of searching by distance on indexes and we had implemented on `IndexFlat` and `IndexBinaryFlat`. When it comes to other ANN indexes, we had not find a good strategy to trade off recall againt search cost. For example, `IndexIVFFlat`, the bucket of the closest centroid may not contains the closest neighbor of a query, so when a query falls into the area that is the boundary of several buckets, how to choose a proper parameter `nprobe` to balance the search precision and search costs is still on the way.
