### ISSUE TITLE
Official website documentation error.

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#4824]
link: https://milvus.io/cn/docs/v1.0.0/operational_faq.md?%E4%B8%BA%E4%BB%80%E4%B9%88-Milvus-%E5%9C%A8%E5%90%AF%E5%8A%A8%E6%97%B6%E8%BF%94%E5%9B%9E-Illegal-instruction%EF%BC%9F

![image](https://user-images.githubusercontent.com/53512883/111267003-4eb1e680-8666-11eb-96eb-ee00bdde130b.png)

**Comment by PahudPlus** [comment]
如果你的 CPU 对于 SSE42、AVX、AVX2、AVX512 这四种指令集都不支持，则 Milvus 在启动时会返回上述报错信息。可以通过 `cat /proc/cpuinfo` 查看 CPU 支持的指令集。

**Comment by shengjun1985** [comment]
It is fixed. Thanks all.
