### ISSUE TITLE
compact function: Excepted error: unsupported operand type(s) for +: 'float' and 'str'

### ISSUE THREAD

**Issue by shushenglee** [milvus-io/milvus#4827]
**Please state your issue using the following template and, most importantly, in English.**
True is:
       milvus.compact(collection_name="test01", timeout=1)
But in the documents, it is:
       milvus.compact(collection_name="test01", timeout="1")

**Describe the bug**
Excepted error: unsupported operand type(s) for +: 'float' and 'str'

**Comment by yhmo** [comment]
Could you provide the documents address?

**Comment by shushenglee** [comment]
https://milvus.io/cn/docs/v1.0.0/compact_python.md

**Comment by yhmo** [comment]
Ok, the document is incorrect. the "timeout" should be an integer. We will fix it.

**Comment by BossZou** [comment]
@PahudPlus , The document need to be fixed.

**Comment by PahudPlus** [comment]
Issued fixed.

**Comment by shengjun1985** [comment]
Thanks all.
