### ISSUE TITLE
What is the maximum vector dimension supported by Milvus?

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#4829]
Maybe it's necessary to add such a faq.

**Comment by yhmo** [comment]
It is defined here: milvus/core/src/utils/ValidationUtil.cpp

The max dimension is 32768:
`constexpr int64_t COLLECTION_DIMENSION_LIMIT = 32768;`

**Comment by shengjun1985** [comment]
At present, this restriction applies to both float vectors and binary vectors.
But it may need to be treated differently.

**Comment by yhmo** [comment]
Since float vector size is 32 times of binary vector, we suggest to set the dimension limit of binary vector to be: 32678 * 32

**Comment by shengjun1985** [comment]
The variable type of "dimension_" is uint16_t.
[MetaTypes.h](https://github.com/milvus-io/milvus/blob/1.0/core/src/db/meta/MetaTypes.h)
```C++
struct CollectionSchema {
    ...
    uint16_t dimension_ = 0;
    ...
};
```

**Comment by shengjun1985** [comment]
Modifying the dimension limitation will break compatibility.
So keep it as it is now.
