### ISSUE TITLE
[DOC] milvus/install.md contains an incorrect command

### ISSUE THREAD

**Issue by yamasite** [milvus-io/milvus#483]
## Report incorrect documentation

**Location of incorrect documentation**
milvus/install.md

**Describe the problems or issues found in the documentation**
The following command does not add a correct value to `LD_LIBRARY_PATH`:

```bash
$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:[Milvus root path]/core/milvus/lib
```

**Steps taken to verify documentation is incorrect**
After running:
```bash
$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:[Milvus root path]/core/milvus/lib
```
The following command still returns an error:
```bash
$ ./start_server.sh
$ ../bin/milvus_server: error while loading shared libraries: libmysqlpp.so.3: cannot open shared object file: No such file or directory
```
**Suggested fix for documentation**
We should use the following command instead:
```bash
$ export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/opt/milvus/lib"
```

**Comment by yamasite** [comment]
Closed because this issue could not be reproduced.

**Comment by w5688414** [comment]
../bin/milvus_server: error while loading shared libraries: libmysqlpp.so.3: cannot open shared object file: No such file or directory
