### ISSUE TITLE
On Milvus database backup and insert search backup

### ISSUE THREAD

**Issue by 1138886114** [milvus-io/milvus#4830]
I now deploy the Milvus service in a production server, and other production servers connect to this server to insert the search service. This is very dangerous when this server goes down.

I hope that Milvus service has master node, backup node, and the data of insertion operation in the master node is synchronized to backup node in real time. In this way, when the server of the master node is down, it will automatically connect to the server of backup node for operation, so as not to affect normal business

**Comment by shengjun1985** [comment]
Thank you for your advice.
This feature will be considered in the our new developing version.

**Comment by yhmo** [comment]
The v1.1.1 is stable now, we only fix critical issues, no more features and big changes.
Milvus v2.0(distribute & cloud-native) has been released. The v2.0 has multiple nodes with different role(proxy-node, data-node, query-node, index-node, root-coordinator, etc).
