### ISSUE TITLE
How can I build milvus c++sdk (libmilvus_sdk.so) by Proto2?

### ISSUE THREAD

**Issue by GreenValue** [milvus-io/milvus#4839]
- Build Enviroment
①build libmilvus_sdk.so In cuda:10.2-devel-ubuntu18.04
②build my process using proto2 by link libmilvus_sdk.so 

- Problem
when run my process , there is falut:
[libprotobuf FATAL /usr/include/google/protobuf/repeated_field.h:1453] CHECK failed: (n) >= (0): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: (n) >= (0):

**Comment by GreenValue** [comment]
The protobuf version is different between libmilvus_sdk.so and my other *.cc,
so resolved by use same protobuf by define in CMakeList.txt as below:
```
root@81dec92b6e90:/usr/work/src/ut_img_understand# cat CMakeLists.txt 
cmake_minimum_required(VERSION 3.14)
project(test)
set(CMAKE_CXX_STANDARD 17)

include_directories(${PROJECT_SOURCE_DIR})
include_directories(/usr/work/src/milvus/core/cmake_build/thirdparty/grpc/grpc-src/third_party/protobuf/src)
aux_source_directory(./ src_files)
aux_source_directory(./proto proto_files)

add_executable(ut_milvus
    ${src_files}
    ${proto_files}
	)
target_link_libraries(ut_milvus
	 pthread
        /usr/work/src/milvus/sdk/cmake_build/grpc_ep-prefix/src/grpc_ep/libs/opt/protobuf/libprotobuf.a
	${PROJECT_SOURCE_DIR}/libmilvus_sdk.so
	 )
```

**Comment by yhmo** [comment]
What is the "proto_files"?
