### ISSUE TITLE
Reduce sizing tool options to 1

### ISSUE THREAD

**Issue by YikSanChan** [milvus-io/milvus#4852]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
As said in https://github.com/milvus-io/milvus/discussions/4850, there are currently 2 options for sizing tool: https://zilliz.com/sizing-tool vs https://www.milvus.io/tools/sizing. Should be only 1.

**Comment by shengjun1985** [comment]
At present, https://zilliz.com/sizing-tool is the effective link, which is on the official website (https://milvus.io/).
And the other one has been abandoned.
Thank you for your advice. We will solve it soon.

**Comment by shanghaikid** [comment]
fixed.
