### ISSUE TITLE
Support full-text search in documents

### ISSUE THREAD

**Issue by YikSanChan** [milvus-io/milvus#4853]
**Please state your issue using the following template and, most importantly, in English.**

**Location of incorrect documentation**
The whole docs.

**Describe the problems or issues found in the documentation**
We're only able to search h1/h2/h3/etc, while not able to search paragraph appearance.

**Steps taken to verify documentation is incorrect**
Simply try searching `nlist`

![image](https://user-images.githubusercontent.com/17229109/112431363-62520100-8d7a-11eb-9385-5e7255649bf4.png)

**Suggested fix for documentation**
Maybe try Algolia (https://docsearch.algolia.com/)? It is free for open source project like this.

With Algolia, searching documents can't be easier. See React website for example:

![image](https://user-images.githubusercontent.com/17229109/112431822-f6bc6380-8d7a-11eb-9880-eb027e2b7f21.png)

**Comment by shengjun1985** [comment]
Thank you for your advice.
It's in the plan.

**Comment by shengjun1985** [comment]
It is supported. Thanks all.
