### ISSUE TITLE
Clicking anchors doesn't change URL in browser

### ISSUE THREAD

**Issue by YikSanChan** [milvus-io/milvus#4854]
**Please state your issue using the following template and, most importantly, in English.**

**Location of incorrect documentation**
It applies to every single page in docs.

**Describe the problems or issues found in the documentation**
Clicking anchors doesn't change URL in browser. It should, so that people can easily copy the detailed URL for reference.

**Steps taken to verify documentation is incorrect**
List any steps you have taken:
1. Visit https://milvus.io/docs/v1.0.0/mishards.md
2. Click "What is Mishards"
3. Note the URL in browser doesn't change

**Suggested fix for documentation**
Should make sure the URL change after clicking the anchors. For example, https://reactjs.org/docs/getting-started.html#learn-react. Note the #learn-react part

**Comment by shengjun1985** [comment]
The current style may be inconvenient for copying the links. We will try to improve it.
Thank you very much.

**Comment by YikSanChan** [comment]
@shengjun1985 @shanghaikid AFAIK Milvus site uses GatsbyJS. Maybe helpful to refer to https://using-remark.gatsbyjs.org/hello-world-kitchen-sink/#markdown-in-gatsby

**Comment by shanghaikid** [comment]
fixed.
