### ISSUE TITLE
For the PQ index, the milvus sizing tool calculates incorrectly.

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#4855]
For PQ indexes, the disk usage and memory usage are related to nlist, index_file_size, vector dimension, and parameter m, as shown in the following figure:

![image](https://user-images.githubusercontent.com/53512883/112444514-165a8880-8d89-11eb-8c9e-80ae11b28481.png)

**Comment by JackLCL** [comment]
Another thing, it would be better if the calculation formula could be displayed on the sizing tool's page.

**Comment by shanghaikid** [comment]
Will fix it soon

**Comment by JackLCL** [comment]
Fixed.
