### ISSUE TITLE
The inserted data number increase automatically without any operations

### ISSUE THREAD

**Issue by Chisdo** [milvus-io/milvus#4862]
My behavior:
1. build mishards with using default settings @https://milvus.io/docs/v1.0.0/mishards.md [sudo make deploy_m].
  - HOST_ = '127.0.0.1'
  - PORT_ = '19531'
2. create 2 collections
  - {name='A', dimension=2048, index_file_size=2048, 'nlist'=2048}
  - {name='B', dimension=512, index_file_size=2048, 'nlist'=2048}
3. using Milvus.insert: 
  - insert 8.2M data in collection 'A' with several partitions[a1, a2, a3, a4]. 
  - insert around 8.2M data in collection 'B' with serveral partitions[b1, b2, b3, b4].
4. [after the index was built successfully] using Milvus.search to search serveral times
5. Then I may run [sudo make deploy_m] to reboot the mishards for serveral times. And right now, the total number of inserted data is extremelly large.
  - The Mishards behavior: After rebooting the Mishards, it just keeps running for a long time while the number of data in collection got to keep increasing. Then the data number isn't going up anymore but the CPU usage suddenly jump to an extremely high level[around 1800%].

*** QUESTION ***
1. I am wondering that what the Mishards is doing with adding so much data?
2. How can I delete those useless data?

*** Some data here ***
The following data shows Milvus.list_collections result.
['PEDESTRIAN', 'FACE']

The following data shows Milvus.get_collection_stats result and the total number is calculated by myself.
-- PEDESTRIAN --
{'partitions': [{'row_count': 1, 'segments': [{'data_size': 8200, 'index_name': 'IVFFLAT', 'name': '1616234710547495000', 'row_count': 1}], 'tag': '_default'}, {'row_count': 12851545, 'segments': [{'data_size': 2207005562, 'index_name': 'IVFFLAT', 'name': '1616236344056881000', 'row_count': 267099}, {'data_size': 2201208162, 'index_name': 'IVFFLAT', 'name': '1616237475295170000', 'row_count': 266392}, {'data_size': 2383772962, 'index_name': 'IVFFLAT', 'name': '1616238481556851000', 'row_count': 288656}, {'data_size': 2171417562, 'index_name': 'IVFFLAT', 'name': '1616239203421118000', 'row_count': 262759}, {'data_size': 2169515162, 'index_name': 'IVFFLAT', 'name': '1616240055433071000', 'row_count': 262527}, {'data_size': 2181191962, 'index_name': 'IVFFLAT', 'name': '1616240846406756000', 'row_count': 263951}, {'data_size': 2202593962, 'index_name': 'IVFFLAT', 'name': '1616241739016515000', 'row_count': 266561}, {'data_size': 2208071562, 'index_name': 'IVFFLAT', 'name': '1616242505594269000', 'row_count': 267229}, {'data_size': 2207128562, 'index_name': 'IVFFLAT', 'name': '1616243368801023000', 'row_count': 267114}, {'data_size': 2204037162, 'index_name': 'IVFFLAT', 'name': '1616244165384610000', 'row_count': 266737}, {'data_size': 3707318400, 'index_name': 'IVFFLAT', 'name': '1616745370872130000', 'row_count': 452112}, {'data_size': 3707318400, 'index_name': 'IVFFLAT', 'name': '1616745372392353000', 'row_count': 452112}, {'data_size': 3707318400, 'index_name': 'IVFFLAT', 'name': '1616745373525120000', 'row_count': 452112}, {'data_size': 3707318400, 'index_name': 'IVFFLAT', 'name': '1616745609629254000', 'row_count': 452112}, {'data_size': 3707318400, 'index_name': 'IVFFLAT', 'name': '1616745611688613000', 'row_count': 452112}, {'data_size': 3707318400, 'index_name': 'IVFFLAT', 'name': '1616745613355923000', 'row_count': 452112}, {'data_size': 3707318400, 'index_name': 'IVFFLAT', 'name': '1616745807013322000', 'row_count': 452112}, {'data_size': 3707318400, 'index_name': 'IVFFLAT', 'name': '1616745808963846000', 'row_count': 452112}, {'data_size': 3707318400, 'index_name': 'IVFFLAT', 'name': '1616745809819749000', 'row_count': 452112}, {'data_size': 3707318400, 'index_name': 'IVFFLAT', 'name': '1616746363069211000', 'row_count': 452112}, {'data_size': 3707318400, 'index_name': 'IVFFLAT', 'name': '1616746364526121000', 'row_count': 452112}, {'data_size': 3707318400, 'index_name': 'IVFFLAT', 'name': '1616746365535324000', 'row_count': 452112}, {'data_size': 1853659200, 'index_name': 'IVFFLAT', 'name': '1616746430539610000', 'row_count': 226056}, {'data_size': 1853659200, 'index_name': 'IVFFLAT', 'name': '1616746430729171000', 'row_count': 226056}, {'data_size': 1853659200, 'index_name': 'IVFFLAT', 'name': '1616746431265557000', 'row_count': 226056}, {'data_size': 3724112162, 'index_name': 'IVFFLAT', 'name': '1616743824478491000', 'row_count': 452112}, {'data_size': 3724112162, 'index_name': 'IVFFLAT', 'name': '1616743825987606000', 'row_count': 452112}, {'data_size': 3724112162, 'index_name': 'IVFFLAT', 'name': '1616743827278282000', 'row_count': 452112}, {'data_size': 3724112162, 'index_name': 'IVFFLAT', 'name': '1616744207221301000', 'row_count': 452112}, {'data_size': 3724112162, 'index_name': 'IVFFLAT', 'name': '1616744209077121000', 'row_count': 452112}, {'data_size': 3724112162, 'index_name': 'IVFFLAT', 'name': '1616744210643236000', 'row_count': 452112}, {'data_size': 3724112162, 'index_name': 'IVFFLAT', 'name': '1616744597129024000', 'row_count': 452112}, {'data_size': 3724112162, 'index_name': 'IVFFLAT', 'name': '1616744599080927000', 'row_count': 452112}, {'data_size': 3724112162, 'index_name': 'IVFFLAT', 'name': '1616744600818832000', 'row_count': 452112}], 'tag': '20210317'}, {'row_count': 6179740, 'segments': [{'data_size': 2202823562, 'index_name': 'IVFFLAT', 'name': '1616236324008745000', 'row_count': 266589}, {'data_size': 2205521362, 'index_name': 'IVFFLAT', 'name': '1616237488839718000', 'row_count': 266918}, {'data_size': 2263692162, 'index_name': 'IVFFLAT', 'name': '1616238416867033000', 'row_count': 274012}, {'data_size': 2206579162, 'index_name': 'IVFFLAT', 'name': '1616239172148217000', 'row_count': 267047}, {'data_size': 2204201162, 'index_name': 'IVFFLAT', 'name': '1616240007130596000', 'row_count': 266757}, {'data_size': 2260723762, 'index_name': 'IVFFLAT', 'name': '1616240858098431000', 'row_count': 273650}, {'data_size': 2173319962, 'index_name': 'IVFFLAT', 'name': '1616241748927181000', 'row_count': 262991}, {'data_size': 2178330162, 'index_name': 'IVFFLAT', 'name': '1616242520299887000', 'row_count': 263602}, {'data_size': 2203151562, 'index_name': 'IVFFLAT', 'name': '1616243329085307000', 'row_count': 266629}, {'data_size': 2421976762, 'index_name': 'IVFFLAT', 'name': '1616244290304018000', 'row_count': 293315}, {'data_size': 2716332000, 'index_name': 'IVFFLAT', 'name': '1616744700151848000', 'row_count': 331260}, {'data_size': 2716332000, 'index_name': 'IVFFLAT', 'name': '1616744700306042000', 'row_count': 331260}, {'data_size': 1358166000, 'index_name': 'IVFFLAT', 'name': '1616744827016139000', 'row_count': 165630}, {'data_size': 2716332000, 'index_name': 'IVFFLAT', 'name': '1616745651158622000', 'row_count': 331260}, {'data_size': 2733125762, 'index_name': 'IVFFLAT', 'name': '1616743985598389000', 'row_count': 331260}, {'data_size': 2733125762, 'index_name': 'IVFFLAT', 'name': '1616743985599667000', 'row_count': 331260}, {'data_size': 2733125762, 'index_name': 'IVFFLAT', 'name': '1616743985601613000', 'row_count': 331260}, {'data_size': 2733125762, 'index_name': 'IVFFLAT', 'name': '1616744314000556000', 'row_count': 331260}, {'data_size': 2733125762, 'index_name': 'IVFFLAT', 'name': '1616744314122659000', 'row_count': 331260}, {'data_size': 2733125762, 'index_name': 'IVFFLAT', 'name': '1616744314157919000', 'row_count': 331260}, {'data_size': 2733125762, 'index_name': 'IVFFLAT', 'name': '1616744699686397000', 'row_count': 331260}], 'tag': '20210318'}, {'row_count': 5066166, 'segments': [{'data_size': 2182405562, 'index_name': 'IVFFLAT', 'name': '1616238454551871000', 'row_count': 264099}, {'data_size': 2175738962, 'index_name': 'IVFFLAT', 'name': '1616241655566356000', 'row_count': 263286}, {'data_size': 2773682962, 'index_name': 'IVFFLAT', 'name': '1616648921941473000', 'row_count': 336206}, {'data_size': 2773682962, 'index_name': 'IVFFLAT', 'name': '1616648921943859000', 'row_count': 336206}, {'data_size': 2773682962, 'index_name': 'IVFFLAT', 'name': '1616648921951036000', 'row_count': 336206}, {'data_size': 2756889200, 'index_name': 'IVFFLAT', 'name': '1616744900056875000', 'row_count': 336206}, {'data_size': 2756889200, 'index_name': 'IVFFLAT', 'name': '1616744900082150000', 'row_count': 336206}, {'data_size': 2756889200, 'index_name': 'IVFFLAT', 'name': '1616744900089586000', 'row_count': 336206}, {'data_size': 2756889200, 'index_name': 'IVFFLAT', 'name': '1616745883220284000', 'row_count': 336206}, {'data_size': 2756889200, 'index_name': 'IVFFLAT', 'name': '1616745895666324000', 'row_count': 336206}, {'data_size': 2756889200, 'index_name': 'IVFFLAT', 'name': '1616745895667604000', 'row_count': 336206}, {'data_size': 2756889200, 'index_name': 'IVFFLAT', 'name': '1616746529044796000', 'row_count': 336206}, {'data_size': 2756889200, 'index_name': 'IVFFLAT', 'name': '1616746529228527000', 'row_count': 336206}, {'data_size': 2756889200, 'index_name': 'IVFFLAT', 'name': '1616746529261501000', 'row_count': 336206}, {'data_size': 1378444600, 'index_name': 'IVFFLAT', 'name': '1616746625655193000', 'row_count': 168103}, {'data_size': 1378444600, 'index_name': 'IVFFLAT', 'name': '1616746625806666000', 'row_count': 168103}, {'data_size': 1378444600, 'index_name': 'IVFFLAT', 'name': '1616746625832816000', 'row_count': 168103}], 'tag': '20210316'}, {'row_count': 5812071, 'segments': [{'data_size': 2173582362, 'index_name': 'IVFFLAT', 'name': '1616236921930541000', 'row_count': 263023}, {'data_size': 2179125562, 'index_name': 'IVFFLAT', 'name': '1616238380509632000', 'row_count': 263699}, {'data_size': 2209227762, 'index_name': 'IVFFLAT', 'name': '1616239427194289000', 'row_count': 267370}, {'data_size': 2181929962, 'index_name': 'IVFFLAT', 'name': '1616240517399180000', 'row_count': 264041}, {'data_size': 2174451562, 'index_name': 'IVFFLAT', 'name': '1616241619931163000', 'row_count': 263129}, {'data_size': 2178502362, 'index_name': 'IVFFLAT', 'name': '1616242624412246000', 'row_count': 263623}, {'data_size': 2198379162, 'index_name': 'IVFFLAT', 'name': '1616243645227955000', 'row_count': 266047}, {'data_size': 3435882162, 'index_name': 'IVFFLAT', 'name': '1616649015267969000', 'row_count': 416962}, {'data_size': 3435882162, 'index_name': 'IVFFLAT', 'name': '1616649015284670000', 'row_count': 416962}, {'data_size': 3435882162, 'index_name': 'IVFFLAT', 'name': '1616649015288321000', 'row_count': 416962}, {'data_size': 3419088400, 'index_name': 'IVFFLAT', 'name': '1616745070570455000', 'row_count': 416962}, {'data_size': 3419088400, 'index_name': 'IVFFLAT', 'name': '1616745070570349000', 'row_count': 416962}, {'data_size': 3419088400, 'index_name': 'IVFFLAT', 'name': '1616745070660944000', 'row_count': 416962}, {'data_size': 1709544200, 'index_name': 'IVFFLAT', 'name': '1616745192531373000', 'row_count': 208481}, {'data_size': 3419088400, 'index_name': 'IVFFLAT', 'name': '1616746100024712000', 'row_count': 416962}, {'data_size': 3419088400, 'index_name': 'IVFFLAT', 'name': '1616746100054425000', 'row_count': 416962}, {'data_size': 3419088400, 'index_name': 'IVFFLAT', 'name': '1616746100055479000', 'row_count': 416962}], 'tag': '20210319'}], 'row_count': 29909523}
[(1, '_default'), (12851545, '20210317'), (6179740, '20210318'), (5066166, '20210316'), (5812071, '20210319')]
PEDESTRIAN total number is 29909523
-- FACE --
{'partitions': [{'row_count': 0, 'segments': None, 'tag': '_default'}, {'row_count': 9217251, 'segments': [{'data_size': 1317501410, 'index_name': 'IVFFLAT', 'name': '1616244820166061000', 'row_count': 638760}, {'data_size': 1087745466, 'index_name': 'IVFFLAT', 'name': '1616245230917028000', 'row_count': 527011}, {'data_size': 1154353698, 'index_name': 'IVFFLAT', 'name': '1616245618453504000', 'row_count': 559408}, {'data_size': 1168558602, 'index_name': 'IVFFLAT', 'name': '1616246073027543000', 'row_count': 566317}, {'data_size': 1902791154, 'index_name': 'IVFFLAT', 'name': '1616649178300588000', 'row_count': 923434}, {'data_size': 1902791154, 'index_name': 'IVFFLAT', 'name': '1616649178493295000', 'row_count': 923434}, {'data_size': 1902791154, 'index_name': 'IVFFLAT', 'name': '1616649178503043000', 'row_count': 923434}, {'data_size': 1898580304, 'index_name': 'IVFFLAT', 'name': '1616746708137823000', 'row_count': 923434}, {'data_size': 1898580304, 'index_name': 'IVFFLAT', 'name': '1616746708161870000', 'row_count': 923434}, {'data_size': 1898580304, 'index_name': 'IVFFLAT', 'name': '1616746708166745000', 'row_count': 923434}, {'data_size': 949290152, 'index_name': 'IVFFLAT', 'name': '1616746785996537000', 'row_count': 461717}, {'data_size': 949290152, 'index_name': 'IVFFLAT', 'name': '1616746786032269000', 'row_count': 461717}, {'data_size': 949290152, 'index_name': 'IVFFLAT', 'name': '1616746786070972000', 'row_count': 461717}], 'tag': '20210317'}, {'row_count': 4918121, 'segments': [{'data_size': 1100496778, 'index_name': 'IVFFLAT', 'name': '1616245769697659000', 'row_count': 533213}, {'data_size': 2003415744, 'index_name': 'IVFFLAT', 'name': '1616746818185128000', 'row_count': 974424}, {'data_size': 2003415744, 'index_name': 'IVFFLAT', 'name': '1616746818191620000', 'row_count': 974424}, {'data_size': 2003415744, 'index_name': 'IVFFLAT', 'name': '1616746818194156000', 'row_count': 974424}, {'data_size': 1001707872, 'index_name': 'IVFFLAT', 'name': '1616746914847949000', 'row_count': 487212}, {'data_size': 1001707872, 'index_name': 'IVFFLAT', 'name': '1616746914897524000', 'row_count': 487212}, {'data_size': 1001707872, 'index_name': 'IVFFLAT', 'name': '1616746914907304000', 'row_count': 487212}], 'tag': '20210316'}, {'row_count': 9970829, 'segments': [{'data_size': 1334218746, 'index_name': 'IVFFLAT', 'name': '1616244824060226000', 'row_count': 646891}, {'data_size': 1088094986, 'index_name': 'IVFFLAT', 'name': '1616245236149876000', 'row_count': 527181}, {'data_size': 1101461042, 'index_name': 'IVFFLAT', 'name': '1616245624940310000', 'row_count': 533682}, {'data_size': 1101241050, 'index_name': 'IVFFLAT', 'name': '1616246068915191000', 'row_count': 533575}, {'data_size': 2123124450, 'index_name': 'IVFFLAT', 'name': '1616649858727065000', 'row_count': 1030600}, {'data_size': 2123124450, 'index_name': 'IVFFLAT', 'name': '1616649858730933000', 'row_count': 1030600}, {'data_size': 2123124450, 'index_name': 'IVFFLAT', 'name': '1616649858731363000', 'row_count': 1030600}, {'data_size': 2118913600, 'index_name': 'IVFFLAT', 'name': '1616746954394488000', 'row_count': 1030600}, {'data_size': 2118913600, 'index_name': 'IVFFLAT', 'name': '1616746954628340000', 'row_count': 1030600}, {'data_size': 2118913600, 'index_name': 'IVFFLAT', 'name': '1616746954670116000', 'row_count': 1030600}, {'data_size': 1059456800, 'index_name': 'IVFFLAT', 'name': '1616747055418180000', 'row_count': 515300}, {'data_size': 1059456800, 'index_name': 'IVFFLAT', 'name': '1616747055455895000', 'row_count': 515300}, {'data_size': 1059456800, 'index_name': 'IVFFLAT', 'name': '1616747055469797000', 'row_count': 515300}], 'tag': '20210318'}, {'row_count': 3, 'segments': [{'data_size': 6168, 'index_name': 'IVFFLAT', 'name': '1616244361588008000', 'row_count': 3}], 'tag': '20210315'}, {'row_count': 7354211, 'segments': [{'data_size': 1089801466, 'index_name': 'IVFFLAT', 'name': '1616244992452609000', 'row_count': 528011}, {'data_size': 1293826570, 'index_name': 'IVFFLAT', 'name': '1616245549473631000', 'row_count': 627245}, {'data_size': 1087671450, 'index_name': 'IVFFLAT', 'name': '1616246110300888000', 'row_count': 526975}, {'data_size': 1559089634, 'index_name': 'IVFFLAT', 'name': '1616650405315612000', 'row_count': 756264}, {'data_size': 1559089634, 'index_name': 'IVFFLAT', 'name': '1616650405316613000', 'row_count': 756264}, {'data_size': 1559089634, 'index_name': 'IVFFLAT', 'name': '1616650405321187000', 'row_count': 756264}, {'data_size': 1554878784, 'index_name': 'IVFFLAT', 'name': '1616747120376683000', 'row_count': 756264}, {'data_size': 1554878784, 'index_name': 'IVFFLAT', 'name': '1616747120385791000', 'row_count': 756264}, {'data_size': 1554878784, 'index_name': 'IVFFLAT', 'name': '1616747120403662000', 'row_count': 756264}, {'data_size': 777439392, 'index_name': 'IVFFLAT', 'name': '1616747195110001000', 'row_count': 378132}, {'data_size': 777439392, 'index_name': 'IVFFLAT', 'name': '1616747195113406000', 'row_count': 378132}, {'data_size': 777439392, 'index_name': 'IVFFLAT', 'name': '1616747195136019000', 'row_count': 378132}], 'tag': '20210319'}], 'row_count': 31460415}
[(9217251, '20210317'), (4918121, '20210316'), (9970829, '20210318'), (3, '20210315'), (7354211, '20210319')]
FACE total number is 31460415
total data number is 61369938

**Comment by yhmo** [comment]
We will try reproduce it firstly.

**Comment by Chisdo** [comment]
Sure. Plz let me know if you need more infos.

>

**Comment by yhmo** [comment]
I can reproduce it by the following script:

steps:
1. make deploy_m
2. run the script, "AAA" row count = 100000, "BBB" row count = 100000
3. make deploy_m
4. run the script, "AAA" row count = 170000, "BBB" row count = 200000

Only can reproduce on mishards. The single milvus server works fine for these steps.
From the log, looks like the bug is related with segments merge.

```
import numpy as np

from milvus import Milvus, MetricType, IndexType

MILVUS = Milvus(host="localhost", port=19531)

COLLECTION_NAME = "TEST"
COLLECTION_DIMENSION = 2048
COLLECTION_PARAM = {'collection_name': COLLECTION_NAME,
                    'dimension': COLLECTION_DIMENSION,
                    'index_file_size': 2048,
                    'metric_type':MetricType.L2}

def create_collection(name = COLLECTION_NAME):
    print("create collection ", name)
    param = COLLECTION_PARAM
    param["collection_name"] = name
    status = MILVUS.create_collection(param)
    return status

def has_collection(name = COLLECTION_NAME):
    status, has = MILVUS.has_collection(collection_name=name);
    return has

def flush_collection(name = COLLECTION_NAME):
    status = MILVUS.flush(collection_name_array=[name])
    print(name, "flushed")

def describe_collection(name = COLLECTION_NAME):
    status, row_count = MILVUS.count_entities(collection_name=name)
    status, collection = MILVUS.get_collection_info(collection_name=name)
    print(collection)
    print("row count =", row_count)
    return status

def create_partitions(tag, name = COLLECTION_NAME):
    print("create partitions ", tag)
    status = MILVUS.create_partition(name, tag)
    return status

def gen_vec_list(nb, seed=np.random.RandomState(1234)):
    xb = seed.rand(nb, COLLECTION_DIMENSION).astype("float32")
    vec_list = xb.tolist()
    return vec_list

def insert(vec_list, name=COLLECTION_NAME, vector_ids=None, tag=None):
    status, ids = MILVUS.insert(collection_name=name, records=vec_list, ids=vector_ids, partition_tag=tag)
    return status

def build_collection(name=COLLECTION_NAME):
    if not has_collection(name=name):
        create_collection(name=name)
        for i in range(10):
            tag = 'part_' + str(i)
            create_partitions(name=name, tag=tag)

        batch_count = 1000
        repeat = 100
        for i in range(repeat):
            print(name, "insert No.", i)
            part_tag = 'part_' + str(i%10)
            vec_list = gen_vec_list(batch_count, seed=np.random.RandomState(i+13))
            insert(name=name, vec_list=vec_list, tag=part_tag)

        flush_collection(name=name)

if __name__ == "__main__":
    build_collection("AAA")
    build_collection("BBB")

    describe_collection("AAA")
    describe_collection("BBB")

```

**Comment by yhmo** [comment]
This is a bug of milvus server. In read-only mode, the milvus server still can merge segment at startup. Read-only node should not be allow to change data. We will fix it in next minor version.

**Comment by yhmo** [comment]
In /milvus/core/src/db/DBImpl.cpp line No.119~125
Read-only node should not invoke the "StartMergeTask" method.

**Comment by shengjun1985** [comment]
We will fix the bug in branch 1.x
If you want to use it as soon as possible, you can checkout the branch and compile it locally.
Otherwise, please wait for the next release.

Reference:
[Install Milvus from Source Code](https://github.com/milvus-io/milvus/blob/master/INSTALL.md)
