### ISSUE TITLE
Multi-process insert encounter error

### ISSUE THREAD

**Issue by WangBoys** [milvus-io/milvus#4863]
16个并发去操作insert，出现了这个错误，大佬可以帮我看一下是什么原因吗？
`Addr [192.168.252.102:19530] insert
Rpc error: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Broken pipe"
        debug_error_string = "{"created":"@1616758021.979269877","description":"Error received from peer ipv4:192.168.252.102:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Broken pipe","grpc_status":14}"
>
        {'API start': '2021-03-26 19:27:01.921121', 'RPC start': '2021-03-26 19:27:01.921891', 'RPC error': '2021-03-26 19:27:01.980273'}
`

**Comment by yhmo** [comment]
Please provide more information:
- collection parameters: index_file_size
- index parameters: nlist
- server_config.yaml
- the script of client

**Comment by WangBoys** [comment]
> Please provide more information:
> 
> * collection parameters: index_file_size
> * index parameters: nlist
> * server_config.yaml
> * the script of client

index_file_size: 4G
nlist: 10240
[script_and_config.zip](https://github.com/milvus-io/milvus/files/6218929/script_and_config.zip)

**Comment by yhmo** [comment]
Seems pymilvus has problem in multi-process:

```

from requests import request
import json
import time
import numpy as np
from multiprocessing import Pool

from milvus import Milvus, IndexType, Status
from milvus.client.types import MetricType

SERVER_ADDR = "127.0.0.1"
SERVER_PORT = '19530'

TABLE_NAME = "TEST"
TABLE_DIMENSION = 512

TABLE_PARAM = {'collection_name': TABLE_NAME,
               'dimension': TABLE_DIMENSION,
               'index_file_size': 4096,
               'metric_type':MetricType.IP}

def createCollection():
    milvus = Milvus(host=SERVER_ADDR, port=SERVER_PORT)
    milvus.drop_collection(collection_name=TABLE_NAME)
    milvus.create_collection(TABLE_PARAM)
    return milvus

def gen_vec_list(nb, seed=np.random.RandomState(1234)):
    xb = seed.rand(nb, TABLE_DIMENSION).astype("float32")
    vec_list = xb.tolist()
    return vec_list


def f(vectors):
    print('hello zilliz')
    milvus = Milvus(host=SERVER_ADDR, port=SERVER_PORT)
    print('milvus connected')
    status = milvus.insert(collection_name=TABLE_NAME, records=vectors)
    print(status)


if __name__ == '__main__':
    createCollection()

    for i in range(10000):
        vectors_arr = []
        for d in range(50):
            vectors = gen_vec_list(100)
            vectors_arr.append(vectors)
        with Pool(processes=16) as pool:
            index = 0
            for vecs in vectors_arr:
                index = index + 1
                print('pool', index)
                pool.apply_async(f, (vecs, ))      # runs in *only* one process
            pool.close()
            pool.join()

```

**Comment by yhmo** [comment]
Link to #4828

**Comment by yhmo** [comment]
@WangBoys 
Try add "mp.set_start_method('spawn')" at the entry of your script.

```
import multiprocessing as mp

if __name__ == '__main__':
    mp.set_start_method('spawn')
    createCollection()
```

We suggest you use multi-thread to call insert().

**Comment by XuanYang-cn** [comment]
> @WangBoys
> Try add "mp.set_start_method('spawn')" at the entry of your script.
> 
> ```
> import multiprocessing as mp
> 
> if __name__ == '__main__':
>     mp.set_start_method('spawn')
>     createCollection()
> ```
> 
> We suggest using multi-thread to call insert().

On Unix, python multiprocessing default to **fork** a new process, https://docs.python.org/3.7/library/multiprocessing.html#contexts-and-start-methods
>fork
The parent process uses os.fork() to fork the Python interpreter. The child process, when it begins, is effectively identical to the parent process. All resources of the parent are inherited by the child process. Note that safely forking a multithreaded process is problematic.
Available on Unix only. The default on Unix.

pymilvus uses multithreading to handling connections, if you fork a process from a parent process that has a connection between pymilvus and milvus, you will get the same multithreading lock to lock the child process.

 So in this case, we recommend you to set multiprocessing as **"spawn"**, which will establish a brand new process, and the child process won't be locked(usually slower than fork though).

By the way, it's unnecessary to establish so many connections, cuz every connection between pymilvus and milvus is **threading unique**. You can try to use one connection through all, or, you can try to create the collection first, and then using a new script to do time-consuming-insert.

**Comment by yhmo** [comment]
Close this issue as the question has been answered.
