### ISSUE TITLE
EM display problems

### ISSUE THREAD

**Issue by ichuangke** [milvus-io/milvus#4872]
**Describe the bug**
when i click "Advanced Settings" link, it returns to a blank page without any prompts,Then I try to  go back to the previous page,
click "<-" ,it does not work ,also is blank,must refresh the page to display

**Method of installation**
- [x] Docker/cpu

- Milvus version (master or released version)
milvus 1.0 cpu ,and milvus-em:v0.4.2.

**Configuration file**
default

**Comment by nameczz** [comment]
Hi, could you share your milvus config file? like server_config.yaml

**Comment by ichuangke** [comment]
I just set  cache_size to 1GB，others are default

**Comment by ichuangke** [comment]
> 
> 
> Hi, could you share your milvus config file? like server_config.yaml

I just set cache_size to 1GB，others are default

**Comment by yhmo** [comment]
Inactive and close
