### ISSUE TITLE
[Go SDK] grpc is not released in client.Disconnect()

### ISSUE THREAD

**Issue by yuanpengpeng** [milvus-io/milvus#4879]
milvus 10.2版本go的客户端，client.Disconnect()方法没有释放grpc，导致并发调用时，goroutine一直增加，Disconnect源码如下所示：

func (client *Milvusclient) Disconnect() error {
	client.Instance = nil
	return nil
}
并没有释放grpc的操作，我是来一个请求，调用一次milvus的new client，然后释放

**Comment by shengjun1985** [comment]
Thank you for your concern and support for Milvus.
It is a bug of go SDK.
Are you willing and able to fix it and submit a PR for us?

**Comment by fishpenguin** [comment]
This already fixed in milvus-sdk-go master and 1.x branch.

**Comment by shengjun1985** [comment]
@fishpenguin 
Please add the corresponding version for milvus 1.0 on milvus-sdk-go's home page (master branch).
Thank you.

**Comment by shengjun1985** [comment]
Fixed in branch 1.x.
Thanks all.

**Comment by shengjun1985** [comment]
milvus-sdk-go-1.0.1 is released, in which the bug is fixed.
