### ISSUE TITLE
Optimization on Kmeans and IVF_FLAT

### ISSUE THREAD

**Issue by yuanpengpeng** [milvus-io/milvus#4882]
请问下，我看milvus里面也集成了faiss的IVF索引算法，社区说是对faiss的IVF算法（本质应该是KMeans聚类）进行了深层次方面的优化，具体能简单介绍下如何优化的么，对此很感兴趣，因为最近也想对IVF算法方面进行一些优化

**Comment by yhmo** [comment]
@yuanpengpeng 

你可以在主页 https://milvus.io/ 的右下角找到微信图标，扫描里面的二维码加入用户群询问。
