### ISSUE TITLE
MongoDB backend support

### ISSUE THREAD

**Issue by kashkarik22i** [milvus-io/milvus#4885]
**Please state your issue using the following template and, most importantly, in English.**
We would like to use MongoDB as a backend for Milvus

**Is your feature request related to a problem? Please describe.**
It is a feature request

**Describe the solution you'd like**
The same data should be stored in a separately maintained MongoDB instance in a very similar manner to the current MySQL solution. Ideally we would like to only have one DB for milvus to clearly separate it from other DBs. 

**Describe alternatives you've considered**
No

**Additional context**
For different technical and legal reasons we cannot run all kinds of DBs in out infrastructure. MySQL is not supported, but MongoDB is.

**Comment by yhmo** [comment]
Link to #2475
