### ISSUE TITLE
The file size of PQ is quite different from the result of "Milvus Sizing Tools"

### ISSUE THREAD

**Issue by Chisdo** [milvus-io/milvus#4886]
**Describe the bug**
The file size of PQ is quite different from the result of "Milvus Sizing Tools"

**Steps/Code to reproduce behavior**
1.  create Collection with following parameters:
param = {'collection_name': 'PEDESTRIAN','dimension': 2048,'index_file_size': 4096,'metric_type': MetricType.L2}
milvus.create_collection(param)
index_param = {'nlist': 12000, 'm': 64}
milvus.create_index('PEDESTRIAN', IndexType.IVF_PQ, index_param)

2. Then, uniformly inserting 2.1M 2048-dim vectors into one COLLECTION with 31 PARTITIONS.

**Expected behavior**
The real size of ./milvus/db is【17GB】. Which is quite different from any estimated result from the "Milvus Sizing Tools" at the "PQ" row. 

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- OS: Ubuntu 18.04
- Azure: Standard_D4s_v4【4cpu with 16GB memory】

- Milvus version (master or released version)
1.0.0

**Configuration file**
1. Disable Wal
2. Link Metadata to MySQL
3. Increase Cache to 11GB and Insertion Cache to 2GB
4. rest setting are default setting

**Screenshots**
![Screen Shot 2021-03-31 at 19 57 41](https://user-images.githubusercontent.com/36720318/113178546-47ebbc00-9281-11eb-9bbc-017bc3a308b3.png)
![Screen Shot 2021-03-31 at 19 57 54](https://user-images.githubusercontent.com/36720318/113178554-49b57f80-9281-11eb-97d6-9a31f27a9b22.png)
![Screen Shot 2021-03-31 at 19 57 25](https://user-images.githubusercontent.com/36720318/113178571-4cb07000-9281-11eb-87fb-795e86d2e036.png)

**Additional context**
 - I'm wondering that when and how does the PQ algorithm compresses the file size into such a small size which is calculated by "Milvus Sizing Tools"[https://zilliz.com/sizing-tool]?
 - Why my ./milvus/db file size is much bigger than the estimated PQ file size?

**Comment by shengjun1985** [comment]
That tool can only calculate a single partition. In the case of multiple partitions, you have to calculate them one by one and add them yourself.
Of course, it is just a tip, it is not the cause of the problem.

**Comment by shengjun1985** [comment]
@nameczz
The "row file size" of IVF_PQ is wrong. Please help to fix.
Thank you.

**Comment by nameczz** [comment]
IVF_PQ row_file_size and disk size already fixed.

https://www.zilliz.com/sizing-tool

![image](https://user-images.githubusercontent.com/20559208/113279487-b8dcb380-9315-11eb-8748-c8131637340f.png)

**Comment by shengjun1985** [comment]
Thanks all.
