### ISSUE TITLE
[Go SDK] Question about the parameter "PartitionTagList" in loadCollection

### ISSUE THREAD

**Issue by yuanpengpeng** [milvus-io/milvus#4887]
type LoadCollectionParam struct {
	CollectionName   string
	PartitionTagList []string
}
这个partitionTaglist是什么意思，可以不传么，好像创建后预加载会报错，v0.10.2版本没有

**Comment by fishpenguin** [comment]
PartitionTagList can be passed as nil, what error did the loadcollection print?

**Comment by shengjun1985** [comment]
Answered.
