### ISSUE TITLE
v1.0.0 milvus server RES grows slowly

### ISSUE THREAD

**Issue by yuanpengpeng** [milvus-io/milvus#4893]
v1.0.0版本 go sdk  建立    IVF_FLAT索引 后并发查询RES内存缓慢增长泄露问题，发现milvus 以docker 容器起来后，并发调用过程中，milvus服务的RES缓慢增长，貌似存在内存泄露问题

**Comment by shengjun1985** [comment]
Could you tell me your test cases such as "row count", "dim", "nlist", "nq", "nprobe", "topk", "client nodes"?
And how about the speed of the memory growth?

**Comment by yuanpengpeng** [comment]
> Could you tell me your test cases such as "row count", "dim", "nlist", "nq", "nprobe", "topk", "client nodes"?
> And how about the speed of the memory growth?

起的一个全局客户端，一直向客户端请求（场景是视频流不断调用后端接口，后端接口里面调用milvus的一些api，比如搜索），大概持续了一个多小时，topk=4,    存入了500个人脸的特征向量，nprobe=32,nlist=16384, 每3-4秒，RES增长200-250m，还挺明显的，我看V1.0.0发布说修复了一些索引的查询内存泄露问题，但是没找到IVF_FLAT的，不知道是不是确实有这个情况存在

**Comment by op-hunter** [comment]
@yuanpengpeng  How long does the phenomenon you memtioned last? I try to reproduce your description, build ivfflat index on 500 random vectors and do query 100000 times, at the beginning, the memory increases as you mentioned above, after severals minutes later, the memory of server is stable and not increase again. I rerun the test script and the memory nerver increases.

**Comment by op-hunter** [comment]
@yuanpengpeng  I use index hnsw test again, the same phenomenon too. Memory size increases only at the beginning of the queries, after about 70000 times query, the memory size is stable and not increase again. So this is the normal phenomeno.
