### ISSUE TITLE
Want to create an index without affecting the performance of inserts and queries

### ISSUE THREAD

**Issue by liujing-dilu** [milvus-io/milvus#4901]
**Please state your issue using the following template and, most importantly, in English.**

**What would you like to be added ?**
需要满足在刷新创建索引时,不影响比对以及数据修改等操作
**Why is this needed ?**
由于使用场景是人脸识别,对于milvus会经常有数据修改操作,由于刷新过程时间长,难免会出现一些意想不到的问题,希望有种方案,能够在不影响其它业务的时候进行刷新创建索引

**Comment by shengjun1985** [comment]
Could you provide more use case information?
(1) What's the size of your data (row count and dim)?
(2) How often do you update your data? And what are the update operations (insert only, or insert + delete)?
(3) What is your query frequency? And what's your query parameter (nq, topk)?

**Comment by liujing-dilu** [comment]
1.数据量为1000w
2.每天大概会修改10w个数据
3.使用的场景为地铁人脸识别,要求1:1000w,由于是实时比对要求比对速度快,只能单条比对,不能批量比对,返回topn通常为3,最大要求是30

**Comment by shengjun1985** [comment]
> 每天大概会修改10w个数据

每秒2个，持续12个小时；还是每天有一次导入，导入量10万？
这里的修改是指只有插入，还是插入加删除？

**Comment by liujing-dilu** [comment]
每天会有修改的高峰期和地铁的高峰期相同,修改包括删除和插入,整体下来在10w左右.每天凌晨闲时(没有进行比对的时候)会进行一些删除和创建collection的操作以及批量导入的操作

**Comment by shengjun1985** [comment]
I used to test FLAT on an 8-core notebook, row count = 1,000,000, dim = 128, nq = 1, tokp = 4, and the query time was only 18ms. Your nq and topk are small too. So it may run well not to create any index.

However, I guess you will build a partition for every day's data and will keep it for three months. In this way, there will be too many partitions, which may affect the query performance. You may need to reduce the number of collections and partitions to solve it.

In all, you can test whether it meets your needs without creating any index.
And then have a look where we need to improve.

**Comment by liujing-dilu** [comment]
但是我们实际是需要索引的啊,因为count=10 000 000,dim=1024,比你测试的那个大很多,并且期望是能够ms级,越快越好

**Comment by liujing-dilu** [comment]
我们目前使用的方案是完全把建索引和其他业务独立出来,使用的两个milvus,数据不共享,当刷新完后会切换到新创建索引的milvus中,但是这种复杂度太高.希望你们能够在内部搞两个独立的业务逻辑,一个用于建索引,一个用于其它业务,内存还有硬盘占用较大也可以接受,主要是client调用要简单

**Comment by shengjun1985** [comment]
Please refer to:
[How can I get the best performance from Milvus through setting index_file_size?](https://milvus.io/docs/v1.0.0/performance_faq.md#How-can-I-get-the-best-performance-from-Milvus-through-setting-index_file_size)
[Does searching while inserting affect the search speed?](https://milvus.io/docs/v1.0.0/performance_faq.md#Does-searching-while-inserting-affect-the-search-speed)

**Comment by shengjun1985** [comment]
If building index in the background cannot solve it, you can try multiple computers with Mishard.

**Comment by liujing-dilu** [comment]
使用Mishard但是存储是共享的,不会在刷新创建索引时有影响吗

**Comment by lnazj** [comment]
hello，I want to ask to a question about milvus.  When I'm using the milvus , but I add and delete a lot of data. Then I want to refresh the milvus to make index to improve comparison efficiency ，what do I need to do? Do I need to create a new milvus?

**Comment by yhmo** [comment]
> 使用Mishard但是存储是共享的,不会在刷新创建索引时有影响吗

You data set is only 1000w, no need to use mishards.

**Comment by yhmo** [comment]
@liujing-dilu @lnazj 
For your scenario, a possible solution is:
- do the follow things in the middle of the night:
   1. drop_index()
   2. compact()
   3. create_index()
- don't create index in business time, only do search/delete/insert


For example:
Assume we have a business: we have 1000w vectors 1024 dimensional, in each day we insert 10w new vectors and delete 10w vectors. The 1000w vectors are collected in recent 3 months, we create 3 collections, one collection for each month. We will delete collection that older than 3 months.

The collection parameter: index_file_size=2048MB=2GB
1000w 1024dim vectors data size = 1000w*1024*4=40GB
There will be 20~21 segments in milvus, each segment contains 50w vectors


At the beginning, we create index IVFSQ8(nlist=2048 or 4096) for the 1000w vectors, the index data size is about 12GB. With good hardware(multi-core cpu, 32GB+ memory), I guess the search (nq=1, topk=3~30) performance can be 10~20ms. 
Only do search/insert/delete in business time. In each day, insert 10w vectors to a small segment, the small segment could affect search performance a little, but not a bottleneck. In each day, delete 10w vectors, only mark a id in "delete_docs" file, the search engine will read the "delete_docs" and filter out deleted vectors during searching, "delete_docs" file is very small, read the file will not be a bottleneck of search.
In the middle of night, do drop_index()->compact()->create_index() to reorganize the data. compact() will shrink the segments according to "delete_docs", create_index() will rebuild index for segments for next business time.

**Comment by sky186** [comment]
@shengjun1985 
您好，目前京东开源的vearch 感觉和你们的milvus 有点像，能请问下各有什么优缺点吗？

**Comment by yhmo** [comment]
> @shengjun1985
> 您好，目前京东开源的vearch 感觉和你们的milvus 有点像，能请问下各有什么优缺点吗？

There are some articles describe the difference of vearch and milvus, you can use "vearch milvus" keyword to search on baidu.com

**Comment by liujing-dilu** [comment]
@yhmo 那您的意思是在忙时不能够进行刷新建索引吗,或者说一旦开始建索引(如手动创建索引)是否不能再进行其他操作了

**Comment by yhmo** [comment]
> @yhmo 那您的意思是在忙时不能够进行刷新建索引吗,或者说一旦开始建索引(如手动创建索引)是否不能再进行其他操作了

建索引还没完成的时候，部分segment是没有索引的，搜索是暴力搜索，性能肯定不好。如果是cpu版本，建索引都是使用cpu，虽然我们会在search请求进来的时候打断建索引的工作，把cpu让出来给查询请求，但是频繁的查询请求会使得建索引时间拉得很长。
所以在每天夜间建索引是个好的做法，夜间建好索引后，白天的查询就能借助索引完成，除了那几万条当天insert的向量是暴搜，其他的1000万条都是用索引查询。白天删除几万条向量也不会对查询性能有影响，或者说影响很小。

**Comment by liujing-dilu** [comment]
@yhmo 但是我是想知道到底在建索引的时候如果进行删除数据删除collection,添加数据,创建collection,并不单指进行search,会不会出现问题

**Comment by yhmo** [comment]
> @yhmo 但是我是想知道到底在建索引的时候如果进行删除数据删除collection,添加数据,创建collection,并不单指进行search,会不会出现问题

建索引的时候删collection, 以及insert/delete都是允许的，不会出问题。不过你如果要删除一个collection，就不要对其建索引，因为后台如果已经开始建索引，你又删除了那个collection，那么建索引的任务就会杨白劳，因为建索引任务在给一个segment建索引的时候不会去查看这个collection又没有被删除，直到建好索引之后才发现这个collection已经被删除了，于是就把刚建好的索引丢弃，相当于做了一些无用功。

**Comment by liujing-dilu** [comment]
@yhmo 比如建索引的时候我删除一个collection,但是已经建立好索引,然后我又重新创建同名的collection,但是数据变了,是否会有影响(使用场景就是我需要删除这个collection的所有数据,通过删除collection来实现,然后重新创建collection添加新的数据)

**Comment by lnazj** [comment]
如果正在给某一个segment创建索引的时候，有两种情况需要请教：
（1）这时候增加了人100人，然后这100人会被创建上索引吗？
（2）根据上面的回答：
do the follow things in the middle of the night:
drop_index()
compact()
create_index()

如果drop_index()成功了，compac()也成功了，但是create_index()失败了，肯定会影响第二天的比对的呀。请教这种情况有更好的处理方案呢？

**Comment by liujing-dilu** [comment]
是否可以在创建新的索引的时候,旧的索引还存在用于search,新的索引和旧的索引是完全独立的,当新的索引创建完成将比对切换为使用新的索引之后,再把旧的索引drop

**Comment by shengjun1985** [comment]
> 如果正在给某一个segment创建索引的时候，有两种情况需要请教：
> （1）这时候增加了人100人，然后这100人会被创建上索引吗？

暂时不会。只有等新增的数据量达到segment_file_size时才会。
> （2）根据上面的回答：
> do the follow things in the middle of the night:
> drop_index()
> compact()
> create_index()
> 
> 如果drop_index()成功了，compac()也成功了，但是create_index()失败了，肯定会影响第二天的比对的呀。请教这种情况有更好的处理方案呢？

可以只调用compact()，这样会逐步合并数据，并对合并后的数据建索引。未合并的数据其旧索引还能用。不过合并后未达到segment_file_size的部分（合并剩余的零头，最多一份）不会建索引。如果此时手动调用create_index可以对这部分强制建索引。
考虑到你的数据每天要修改，那一晚上都建不成的索引，哪怕索引质量再高，作用也下降了。感觉索引质量稍差一些（比如参数小一点），保证一晚上能建好，这样能发挥最大的作用。

**Comment by yhmo** [comment]
> @yhmo 比如建索引的时候我删除一个collection,但是已经建立好索引,然后我又重新创建同名的collection,但是数据变了,是否会有影响(使用场景就是我需要删除这个collection的所有数据,通过删除collection来实现,然后重新创建collection添加新的数据)

由于segment的id不同，所以新建的同名collection并不会受到旧的索引的影响。segment的id是由timestamp生成的，新建collection的segment不可能和旧的collection的segment重复id。除非你在milvus生成segment id的时候准确地把系统时钟调到旧的segment创建的那一时刻，精确到微秒。

**Comment by yhmo** [comment]
> 是否可以在创建新的索引的时候,旧的索引还存在用于search,新的索引和旧的索引是完全独立的,当新的索引创建完成将比对切换为使用新的索引之后,再把旧的索引drop

在1.0版本上做这个代价太大，我们会在2.0里考虑的。

**Comment by yhmo** [comment]
Inactive, close
