### ISSUE TITLE
Error creating IVF_sq8H in Milvus documentation 

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#4904]
Creating IVF_sq8H indexes according to the official website 1.0 documentation keeps reporting errors
![企业微信截图_16177826175265](https://user-images.githubusercontent.com/34296482/113832193-f4b2c580-97ba-11eb-811b-09cc383ad11e.png)
![企业微信截图_16177825752152](https://user-images.githubusercontent.com/34296482/113832176-ef557b00-97ba-11eb-9f9b-04c2aa0f88e5.png)

**Comment by shengjun1985** [comment]
Only GPU enable version support IVF_SQ8_H.
