### ISSUE TITLE
[NOT AN ISSUE] Different index_type listed on website and pymilvus api doc

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus#491]
https://milvus.io/docs/zh-CN/userguide/milvus_operation/ 
https://milvus-io.github.io/milvus-sdk-python/pythondoc/types.html

index_type : IVF_SQ8  in website doc 
index_type: IVFSQ8 in pymilvus doc

in pymilvus, there is another type: MIX_NSG, but not on website's documentation

**Comment by yamasite** [comment]
```text
index_type : IVF_SQ8 in website doc
index_type: IVFSQ8 in pymilvus doc
```
This is not an issue.  I saw IVF_SQ8 in pymilvus doc. 

```text
in pymilvus, there is another type: MIX_NSG, but not on website's documentation
```

NSG is missing in 0.6.0 doc. I will file an issue to milvus-io/doc instead.

https://github.com/milvus-io/docs/issues/361
