### ISSUE TITLE
Picture display error in https://www.milvus.io/cn/blogs/2019-12-18-datafile-cleanup.md

### ISSUE THREAD

**Issue by yuanhanglian** [milvus-io/milvus#4914]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
https://zhuanlan.zhihu.com/p/96103412

**Comment by shengjun1985** [comment]
Some articles are difficult to access because of the network.
Chinses users can find most of the articles at [zilliz at zhihu](https://www.zhihu.com/org/zilliz-11).
