### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by EaChou** [milvus-io/milvus#4920]
**Please state your issue using the following template and, most importantly, in English.**

**What would you like to be added ?**
I hope to make a judgment on the custom id, and insert a vector with the same id to cover it，Avoid vectors with the same id when customizing the id
**Why is this needed ?**
Business use requirements

**Comment by shengjun1985** [comment]
same as #4820

**Comment by shengjun1985** [comment]
This check greatly affects the insert performance.
We are not going to support it in v1.x.
However, we may consider this feature in v2.x.
