### ISSUE TITLE
Why in a FLAT collection with L2, the distances returned by calling search are inaccurate,which is larger than the result by using Numpy.linal.norm

### ISSUE THREAD

**Issue by yangtiger0306** [milvus-io/milvus#4923]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
I insert 2 vectors = [[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 0.0, 0.0]]  into a collection, and create L2 index,  when I use first vector [1.0,1.0,1.0,1.0] to search(topK=10, "nprobe": 16), the distances returned is [0, 2.0].  
I use Numpy.linal.norm to calculate the 
Euclidean distance between [1.0, 1.0, 1.0, 1.0] and [1.0, 1.0, 0.0, 0.0]  is 1.4142135623730951 , not equal 2.0.

Here's the log:
server_version 
 (Status(code=0, message='Success!'), '1.0.0')
client_version 
 1.0.1
CollectionSchema(collection_name='example_collection_', dimension=4, index_file_size=32, metric_type=<MetricType: L2>)
[[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 0.0, 0.0]]
[1618224121711449000, 1618224121711449001]
{'partitions': [{'row_count': 2, 'segments': [{'data_size': 48, 'index_name': 'IDMAP', 'name': '1618224121883889000', 'row_count': 2}], 'tag': '_default'}], 'row_count': 2}
[[1.0, 1.0, 1.0, 1.0]]
Creating index: {'nlist': 2048}
(collection_name='example_collection_', index_type=<IndexType: FLAT>, params={'nlist': 2048})
[[1.0, 1.0, 1.0, 1.0]]
Searching ... 
[
[
(id:1618224121711449000, distance:0.0),
(id:1618224121711449001, distance:2.0)
]
]
1.4142135623730951 1.4142135623730951

Process finished with exit code 0

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

```
import random
import numpy as np
from milvus import Milvus, IndexType, MetricType, Status
_HOST = '127.0.0.1'
_PORT = '19530' 
_DIM = 4  
_INDEX_FILE_SIZE = 32
def main():
    milvus = Milvus(_HOST, _PORT)
    print('server_version', '\n', milvus.server_version())
    print('client_version', '\n', milvus.client_version())
    collection_name = 'example_collection_'
    status, ok = milvus.has_collection(collection_name)
    if not ok:
        param = {
            'collection_name': collection_name,
            'dimension': _DIM,
            'index_file_size': _INDEX_FILE_SIZE,  # optional
            'metric_type': MetricType.L2  # optional
        }

        milvus.create_collection(param)

    # Show collections in Milvus server
    _, collections = milvus.list_collections()

    # Describe demo_collection
    _, collection = milvus.get_collection_info(collection_name)
    print(collection)
    vectors = [[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 0.0, 0.0]]
    print(vectors)
    status, ids = milvus.insert(collection_name=collection_name, records=vectors)
    if not status.OK():
        print("Insert failed: {}".format(status))
    print(ids)
    milvus.flush([collection_name])
    status, result = milvus.count_entities(collection_name)
    _, info = milvus.get_collection_stats(collection_name)
    print(info)
    status, result_vectors = milvus.get_entity_by_id(collection_name, ids[:1])
    print(result_vectors)
    index_param = {
        'nlist': 2048
    }

    print("Creating index: {}".format(index_param))
    status = milvus.create_index(collection_name, IndexType.FLAT, index_param)

    # describe index, get information of index
    status, index = milvus.get_index_info(collection_name)
    print(index)

    # Use the top 10 vectors for similarity search
    query_vectors = vectors[0:1]
    print(query_vectors)
    # execute vector similarity search
    search_param = {
        "nprobe": 16
    }

    print("Searching ... ")

    param = {
        'collection_name': collection_name,
        'query_records': query_vectors,
        'top_k': 10,
        'params': search_param,
    }

    status, results = milvus.search(**param)
    if status.OK():
        print(results)

    # manually calculate Euclidean distance
    dist1 = np.sqrt(np.sum(np.square(np.array(vectors[0]) - np.array(vectors[1]))))
    dist2 = np.linalg.norm(np.array(vectors[0]) - np.array(vectors[1]))
    print(dist1, dist2)
    # Delete demo_collection
    status = milvus.drop_collection(collection_name)
if __name__ == '__main__':
    main()
```

**Expected behavior**
My expection is 
 in FLAT collection with L2 , the distance between [1.0, 1.0, 1.0, 1.0] and [1.0, 1.0, 0.0, 0.0]  should be correct as numpy result 1.4142135623730951 ,not 2.0

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
server:1.0.0
client:1.0.1

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by shengjun1985** [comment]
Because whether to find the square root does not affect the sorting result, we give the square of L2 distance.
This can improve performance a little bit.

**Comment by yangtiger0306** [comment]
> Because whether to find the square root does not affect the sorting result, we give the square of L2 distance.
> This can improve performance a little bit.

@shengjun1985 Got it ! Thanks all ~

**Comment by JackLCL** [comment]
@shengjun1985 @PahudPlus 
This should be explained in our official documentation.

**Comment by scsven** [comment]
Not activity.
