### ISSUE TITLE
How mishard pod call write pod in the same namespace

### ISSUE THREAD

**Issue by zengqi0730** [milvus-io/milvus#4940]
when i deploy milvus mishard yamls in k8s, i apply them in the namespace assigned, the pods are running but didn't run as usual !
I found that fun in mishards/server.py
```
    def pre_run_handler(self):
        woserver = settings.WOSERVER
        url = urlparse(woserver)
        ip = socket.gethostbyname(url.hostname)
        socket.inet_pton(socket.AF_INET, ip)
        _, group = self.writable_topo.create('default')
        group.create(name='WOSERVER', uri='{}://{}:{}'.format(url.scheme, ip, url.port or 80))
```

is the 'default' the namespace? Should I modified it to where i deploy ？

**Comment by yhmo** [comment]
The group = self.writable_topo.create('default'), is mishards internal definition, doesn't related with k8s namespace.
Could you tell us how you deploy mishard on k8s.

**Comment by yhmo** [comment]
Inactive and close.
