### ISSUE TITLE
QPS not good with mishards: 4 ro nodes, 1 rw node, search with CPU, but we want 1000QPS for least

### ISSUE THREAD

**Issue by qingfengshiran** [milvus-io/milvus#4943]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
QPS not good with mishards: 4 ro nodes, 1 rw node, search with CPU

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.
1、create collection with param index_file_size=2048, metric_type=MetricType.L2, dimension=128
2、 insert 200000000 vectors to the collection
3、create index with param indextype = IndexType.IVF_SQ8, list = 2048
4、single thread search the vector with one nq, probe = 16, time cost 41ms
<img width="646" alt="image" src="https://user-images.githubusercontent.com/42227773/114809800-6dc6a400-9ddd-11eb-91ca-e4722b4a3762.png">
5、five threads search the vector with one nq, probe = 16, single time cost 222ms
<img width="617" alt="image" src="https://user-images.githubusercontent.com/42227773/114809878-8d5dcc80-9ddd-11eb-91c4-5f9ed3ebbe08.png">
6、check every cpu memory use around 6G
<img width="610" alt="image" src="https://user-images.githubusercontent.com/42227773/114810449-b2067400-9dde-11eb-8b2f-d26d1d583104.png">

Max QPS only can reach 50.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)
CPU only

- Milvus version (master or released version)
milvusdb/milvus:1.0.0-cpu-d030521-1ea92e
milvusdb/mishards:latest

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

this is cluster_ro_server.yml config====================================
version: 0.5
cluster:
  enable: true
  role: ro

general:
  timezone: UTC+8
  meta_uri: mysql://root:milvusroot@10.4.45.87:3306/milvus

  bind.address: 0.0.0.0
  bind.port: 19530
  http.enable: true
  http.port: 19121

storage:
  path: /var/lib/milvus
  auto_flush_interval: 1

wal:
  enable: true
  recovery_error_ignore: false
  buffer_size: 256MB
  path: /var/lib/milvus/wal

cache:
  cache_size: 80GB
  insert_buffer_size: 1GB
  preload_collection: "*"

gpu:
  enable: false
  cache_size: 1GB
  gpu_search_threshold: 1000
  search_devices:
    - gpu0
  build_index_devices:
    - gpu0

fpga:
   enable: false
   search_devices:
     - fpga0

logs:
  level: debug
  trace.enable: true
  path: /var/lib/milvus/logs
  max_log_file_size: 1024MB
  log_rotate_num: 0
  log_to_stdout: false
  log_to_file: true

metric:
  enable: false
  address: 127.0.0.1
  port: 9091

this is cluster_rw_server.yml config====================================
version: 0.5

cluster:
  enable: true
  role: rw

general:
  timezone: UTC+8
  meta_uri: mysql://root:milvusroot@10.4.45.87:3306/milvus

network: 
  bind.address: 0.0.0.0
  bind.port: 19530
  http.enable: true
  http.port: 19121

storage:
  path: /var/lib/milvus
  auto_flush_interval: 1

wal:
  enable: true
  recovery_error_ignore: false
  buffer_size: 256MB
  path: /var/lib/milvus/wal

cache:
  cache_size: 80GB
  insert_buffer_size: 1GB
  preload_collection:

gpu:
  enable: false
  cache_size: 1GB
  gpu_search_threshold: 1000
  search_devices:
    - gpu0
  build_index_devices:
    - gpu0

fpga:
   enable: false
   search_devices:
     - fpga0

logs:
  level: debug
  trace.enable: true
  path: /var/lib/milvus/logs
  max_log_file_size: 1024MB
  log_rotate_num: 0
  log_to_stdout: false
  log_to_file: true

metric:
  enable: false
  address: 127.0.0.1
  port: 9091

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
Okey... we need to verify this to see if there is bug in Mishards distribute segment logic, or any possibility to improve the performance of Mishards.

**Comment by qingfengshiran** [comment]
> Okey... we need to verify this to see if there is bug in Mishards distribute segment logic, or any possibility to improve the performance of Mishards.

How about this issue going now?

**Comment by yhmo** [comment]
From my local test:
1 rw node, 4 ro nodes
Create a collection, insert some vectors to generate 5 segments, then search(). I saw the segments distribution is not averagely:
2 segments were send to ro_1
3 segments were send to ro_3
The ro_2 and ro_4 do nothing

The mishards distributes segment according to hash ring. Ideally, the distribution should be averagely for large amount of segment.

You can observe this in your read-only node's logs:
1. restart mishard and all nodes
2. use docker exec -it [container id] bash enter a ro node container
3. go to /var/lib/milvus/logs, open the latest xxx.debug.log file
4. use vim to search this string: "FilesToSearch: SELECT id, table_id, segment_id, file_id, file_type, file_size, row_count, date, engine_type, created_on, updated_time FROM TableFiles WHERE (id = "

For example, if a ro node query 2 segments, the string will be ".... FROM TableFiles WHERE (id = xx OR id = xx)". By these way, we can know how many segments were distributed to this node.

**Comment by yhmo** [comment]
For your dataset: 200000000 vectors 128 dimensions, total data size is 95GB. Each segment size is 2GB, there are almost 50 segments.
4 read-only nodes, if these segments are distributed to ro nodes averagely, each node will need to query 12 segments. Although milvus can combine small nq request into large nq request to improve QPS, 1000 QPS is still a big challenge.

**Comment by yhmo** [comment]
"single thread search the vector with one nq, probe = 16, time cost 41ms"
"five threads search the vector with one nq, probe = 16, single time cost 222ms"

From this result, you may think single thread search is faster than multi-thread search.
In fact, this is because milvus combine the small nq request from multi clients, for example:
There 5 clients(threads) performs search(nq=1), milvus receive 5 request at same time, it will combine the 5 requests into a single request with nq=5. That means the search engine only execute once to get result for the 5 vectors. These behavior can improve QPS, but for some clients, the latency will be longer.
Assume single thread execute one request cost 41ms. If the single thread run 100 requests, totally it will cost 41x100=4100ms
If you use 5 threads run 100 requests, each thread run 20 requests, totally it only cost 1000ms.

**Comment by qingfengshiran** [comment]
> "single thread search the vector with one nq, probe = 16, time cost 41ms"
> "five threads search the vector with one nq, probe = 16, single time cost 222ms"
> 
> From this result, you may think single thread search is faster than multi-thread search.
> In fact, this is because milvus combine the small nq request from multi clients, for example:
> There 5 clients(threads) performs search(nq=1), milvus receive 5 request at same time, it will combine the 5 requests into a single request with nq=5. That means the search engine only execute once to get result for the 5 vectors. These behavior can improve QPS, but for some clients, the latency will be longer.
> Assume single thread execute one request cost 41ms. If the single thread run 100 requests, totally it will cost 41x100=4100ms
> If you use 5 threads run 100 requests, each thread run 20 requests, totally it could only cost 1000ms.
> 
> For more information, you can refer: https://zhuanlan.zhihu.com/p/148274838

I have create multi-threads to run requests, such 100 threads, every thread loop 20 times, time still not very good.
For example in the before picture, 1 thread loop 5 times, singe time is 41ms, total is 205ms, but 5 threads loop 1 time, single cost 222ms, total is 222ms, I think 5 threads loop 1 time, need 41ms return, not 222ms

**Comment by yhmo** [comment]
Let me do a test for 20M vectors, 1/10 of your dataset.

**Comment by yhmo** [comment]
The following script is a test for comparing single-thread and multi-thread search:

```
import random
import time
import threading
import numpy as np
from milvus import Milvus, IndexType
from milvus.client.types import MetricType

SERVER_ADDR = "127.0.0.1"
SERVER_PORT = '19531'
COLLECTION_NAME = "TEST"
COLLECTION_DIMENSION = 128
COLLECTION_PARAM = {'collection_name': COLLECTION_NAME,
                    'dimension': COLLECTION_DIMENSION,
                    'index_file_size': 1024,
                    'metric_type':MetricType.IP}
INDEX_TYPE = IndexType.IVF_SQ8
INDEX_PARAM = {'nlist': 2048}
NQ = 1
TOPK = 10
SEARCH_PARAM = {'nprobe': 16}

MILVUS = Milvus(host=SERVER_ADDR, port=SERVER_PORT)

def gen_vec_list(nb, seed=np.random.RandomState(1234)):
    xb = seed.rand(nb, COLLECTION_DIMENSION).astype("float32")
    vec_list = xb.tolist()
    return vec_list

def create_collection():
    # create collection
    status = MILVUS.create_collection(COLLECTION_PARAM)
    print("create", COLLECTION_NAME, status)
    # status = MILVUS.create_index(COLLECTION_NAME, INDEX_TYPE, INDEX_PARAM)

def insert():
    # insert
    batch = 10000
    for i in range(2000):
        vectors = gen_vec_list(batch)
        status, ids = MILVUS.insert(collection_name=COLLECTION_NAME, records=vectors)
        print("No.", i, "insert", len(ids), "vectors", status)

    status = MILVUS.flush(collection_name_array=[COLLECTION_NAME])

def drop_collection():
    MILVUS.drop_collection(collection_name=COLLECTION_NAME)

def load_collection():
    MILVUS.load_collection(collection_name=COLLECTION_NAME)

def create_index():
    time_start = time.time()
    status = MILVUS.create_index(COLLECTION_NAME, INDEX_TYPE, INDEX_PARAM)
    print("create index", status)
    time_end = time.time()
    print("create index time cost:", time_end - time_start, 'sec')

def print_result(results):
    for each_query in results:
        print("======================")
        for each_score in each_query:
            print("id =", each_score.id, "distance =", each_score.distance)


def search():
    time_start = time.time()
    q_records = [[random.random() for _ in range(COLLECTION_DIMENSION)] for _ in range(NQ)]
    status, results = MILVUS.search(collection_name=COLLECTION_NAME, query_records=q_records, top_k=TOPK,
                                    params=SEARCH_PARAM)
    # print_result(results)
    # print("search", status)
    time_end = time.time()
    print("search time cost:", time_end - time_start, 'sec')

def search_repeat(repeat):
    for i in range(repeat):
        search()

def search_one_by_one():
    time_start = time.time()
    search_repeat(100)
    time_end = time.time()
    print("search 100 times one by one time cost:", time_end - time_start, 'sec')

def search_multi_threads():
    time_start = time.time()
    threads = []
    for k in range(5):
        x = threading.Thread(target=search_repeat, args=(20,))
        threads.append(x)
        x.start()

    for th in threads:
        th.join()

    time_end = time.time()
    print("search 100 times with 5 threads time cost:", time_end - time_start, 'sec')

if __name__ == "__main__":
    create_collection()
    insert()
    create_index()
    load_collection()

    search_multi_threads()
    search_one_by_one()


```

I start mishards with 1 rw node 4 ro nodes on one machine(I didn't use cluster).
20M vectors 128 dimensions, IVFSQ8 nlist=2048， index_file_size=1024MB
nq=1,topk=10,nprobe=16
Execute 100 requests one by one, time cost is 20 seconds.
Use 5 threads, each thread execute 20 requests, time cost is 3 seconds.

**Comment by yhmo** [comment]
With my script, there are 9 segments. I noticed they are not averagely distributed to nodes:
ro_1: 1 segment
ro_2: 1 segment
ro_3: 1 segment
ro_4: 2 segments
rw:    4 segments

**Comment by yhmo** [comment]
The hash ring can not ensure averagely distributed data to nodes. This is why the Redis create a new concept "Hash Slots", to overcome the shortage of hash ring.
Mishards use a standard hash ring(/milvus/shards/mishards/hash_ring.py) to distribute data, so we can see the workload for each node is different. I don't think we have enough resource to replace the algorithm.

We can change some parameters to improve QPS, for example, use high nlist(8192 or 16384) to create index, use low nprobe to search few buckets. Or create more read-only nodes. 

The max QPS it can reach is depend on:
1. data, including vectors count, index type, index parameters, etc..
2. read-only node count
3. hardware ability, mainly the CPU

**Comment by yhmo** [comment]
Inactive and close
