### ISSUE TITLE
Source code installation compiling Milvus without internet

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#4944]
The user wants to be able to download a compressed installation package of external dependencies when installing Milvus in the source code. Rather than downloading them one by one online, which can cause problems, for example some packages may not download successfully. The user would like us to compress all the external dependencies in the link into a single package so that they can be installed and compiled without network access after download.

https://github.com/milvus-io/milvus/blob/1.0/core/cmake/ThirdPartyPackages.cmake

**Comment by yhmo** [comment]
Abandoned
