### ISSUE TITLE
Please add HOSTNAME support for metric pushgateway.

### ISSUE THREAD

**Issue by noumanriazkhan** [milvus-io/milvus#4948]
I am deploying Milvus and Prometheus via compose file but Milvus metric push service only support IP_ADDRESS but not HOSTNAME. I have added static IPs to containers to make this work but I would like to request for such a feature in Milvus.

Thanks & Great work though!

**Comment by fishpenguin** [comment]
Actually you can put your HOSTNAME in metric.address, the metrics can alse be pushed to pushgateway.

**Comment by noumanriazkhan** [comment]
I get NO DATA in grafana when I set the hostname of pushgateway, it only is able to send when I set the IP.

**Comment by noumanriazkhan** [comment]
One more thing, the prometheus.yml (with URL to download) does not contain job for 'milvus_server' but the one in docker folder does.

**Comment by fishpenguin** [comment]
>One more thing, the prometheus.yml (with URL to download) does not contain job for 'milvus_server' but the one in docker folder does.

We write the address and port of milvus server to represent milvus_server job, which is only a demo. You can change the prometheus.yml to write 'milvus_server' to represent the job.

>I think alert_rules.yml should be updated to catch liveness from pushgateway metrics.

We will consider to add this in next version of milvus,. However, the alert_rules.yml is easy to configure, you can add the alert rules you want.

**Comment by yhmo** [comment]
Close since it has workaround.
