### ISSUE TITLE
Unable to access the Restful APIs

### ISSUE THREAD

**Issue by dinuthomas** [milvus-io/milvus#4971]
https://github.com/milvus-io/milvus/tree/0.10.6/core/src/server/web_impl

This URL is not reachable

**Comment by shengjun1985** [comment]
The old version is no longer maintained, you can access the new version.
[1.0]: https://github.com/milvus-io/milvus/tree/1.0/core/src/server/web_impl
[1.1]: https://github.com/milvus-io/milvus/tree/1.1/core/src/server/web_impl

Can you tell us where you found that link? And we will fix it.

**Comment by dinuthomas** [comment]
Thank you,
This information is enough for me now.
