### ISSUE TITLE
a typo src/grpc/README.md

### ISSUE THREAD

**Issue by shengjh** [milvus-io/milvus#498]
## Report incorrect documentation

**Location of incorrect documentation**
File is src/grpc/README.md

**Describe the problems or issues found in the documentation**
Line 1: We manually change two APIs in "milvus.pd.h".
Therer is no file named "milvus.pd.h". It may be a typo. 

**Suggested fix for documentation**
Change "milvus.pd.h" To "milvus.pb.h"

**Comment by yhmo** [comment]
The src/grpc/README.md is out of date. We don't need to manually modify milvus.pb.h any more. The src/grpc/README.md should be deleted.

**Comment by shengjh** [comment]
@yhmo Do you mean its no need to modify those API (add_vector_data() add_row_id_array())?

**Comment by fishpenguin** [comment]
> @yhmo Do you mean its no need to modify those API (add_vector_data() add_row_id_array())?

Yes. this modify is just used for old version, we drop this modify in 0.6.0 because it's not friendly for contributers and users.
I close this issue.
