### ISSUE TITLE
Incorrect link address

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#4985]
**Location of incorrect documentation**
https://www.milvus.io/cn/docs/v1.0.0/example_code.md

In this line "如果需要进一步了解 Milvus Python SDK，请参考 Milvus Python SDK Readme。"

The link address of "Milvus Python SDK Readme" is "https://github.com/milvus-io/pymilvus/blob/master/README.md"
It should be "https://github.com/milvus-io/pymilvus/blob/1.0/README.md"

**Comment by LocoRichard** [comment]
> **Location of incorrect documentation**
> https://www.milvus.io/cn/docs/v1.0.0/example_code.md
> 
> In this line "如果需要进一步了解 Milvus Python SDK，请参考 Milvus Python SDK Readme。"
> 
> The link address of "Milvus Python SDK Readme" is "https://github.com/milvus-io/pymilvus/blob/master/README.md"
> It should be "https://github.com/milvus-io/pymilvus/blob/1.0/README.md"

I think it should be "https://github.com/milvus-io/pymilvus/blob/v1.0.0/README.md".

**Comment by yhmo** [comment]
It should be https://github.com/milvus-io/pymilvus/blob/v1.0.1/README.md
The recommended pymilvus version for milvus1.0.0 is v1.0.1

**Comment by LocoRichard** [comment]
We have fixed the link issue, pls check.
