### ISSUE TITLE
Obtain cluster result

### ISSUE THREAD

**Issue by sevenold** [milvus-io/milvus#4989]
How to obtain the clustering of features through the milvus feature library to know the growth of a certain feature or a certain category of features?

**Comment by shengjun1985** [comment]
Milvus has not provided the interface yet.

**Comment by xiaofan-luan** [comment]
This is a interesting feature, let's see if more people are intersted

**Comment by OrjwanZaafarani** [comment]
is it supported now?

**Comment by xiaofan-luan** [comment]
> is it supported now?

Hi @OrjwanZaafarani , what infomation of cluster are u looking for? We support prometheus for monitoring the cluster, and attu shows the cluster topology
