### ISSUE TITLE
Config files need to be changed

### ISSUE THREAD

**Issue by neza2017** [milvus-io/milvus#4995]
**this table list the configure items and default values for "statistics" channel in file `configs/advanced/channel.yaml`**
|       module     |       config iterm    | default value |
| ------------------ | -------------------------| -----------------|
| master service | masterStatistics  | master-statistics | 
| query node | queryNodeStats | query-node-stats |
| data service | dataServiceStatistic | dataservice-statistics-channel |

**it would be better to name the configure items and default values in one name-style, something likes this table**
|       module     |       config iterm    | default value |
| ------------------ | -------------------------| -----------------|
| master service | masterStatistics  | master-statistics | 
| query node | queryNodeStatistics | query-node-master-statistics |
| data service | dataServiceStatistic | data-service-statistics |

**Comment by XuanYang-cn** [comment]
Configuration files are a mess now, no one can tell from a first glance whether the specific config is useful or not.

Nor can anyone easily move out these useless configs.

And the names for these configurations are pretty much misleading.

**This need to change**

**Comment by XuanYang-cn** [comment]
First, we need to remove not using config

**Comment by XuanYang-cn** [comment]
Second, we need to rename misleading config-names
