### ISSUE TITLE
Install.md Build from source documentation is out of date with master

### ISSUE THREAD

**Issue by egolearner** [milvus-io/milvus#5003]
**Please state your issue using the following template and, most importantly, in English.**

**Location of incorrect documentation**
https://github.com/milvus-io/milvus/blob/master/INSTALL.md#install-in-centos

**Describe the problems or issues found in the documentation**
1. There's no `./centos7_build_deps.sh` in the repo.
2. Ubuntu guild does not work either.

**Steps taken to verify documentation is incorrect**
List any steps you have taken:
I tried using milvusdb/milvus-cpu-build-env:v0.7.0-ubuntu18.04 or Docker image built with https://github.com/milvus-io/milvus/blob/master/build/docker/env/cpu/ubuntu18.04/Dockerfile to compile master code. 
Got the following errors.
```
internal/querynode/../core/output/lib/libmilvus_segcore.so: undefined reference to `faiss::LOG_WARNING_[abi:cxx11]'
internal/querynode/../core/output/lib/libmilvus_segcore.so: undefined reference to `faiss::LOG_ERROR_[abi:cxx11]'
internal/querynode/../core/output/lib/libmilvus_segcore.so: undefined reference to `faiss::hook_init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
collect2: error: ld returned 1 exit status
Makefile:123: recipe for target 'singlenode' failed
make: *** [singlenode] Error 2
make: *** Waiting for unfinished jobs....
# github.com/milvus-io/milvus/internal/querynode
internal/querynode/../core/output/lib/libmilvus_segcore.so: undefined reference to `faiss::LOG_WARNING_[abi:cxx11]'
internal/querynode/../core/output/lib/libmilvus_segcore.so: undefined reference to `faiss::LOG_ERROR_[abi:cxx11]'
internal/querynode/../core/output/lib/libmilvus_segcore.so: undefined reference to `faiss::hook_init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
collect2: error: ld returned 1 exit status
Makefile:127: recipe for target 'milvus' failed
```

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.

---

## Report needed documentation

**Report needed documentation**
Keep install.md update with master branch.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken:

**Comment by egolearner** [comment]
0.10.3 branch is long gone.

**Comment by scsven** [comment]
@egolearner There is a tag named `v0.10.3`, please use the tag instead.  And we will fix the mistakes in the documents.

**Comment by egolearner** [comment]
@scsven 
Thanks for your reply.
Master branch is a lot ahead of `v0.10.3`. Would you consider maintaining up-to-date compiling guide?

**Comment by yhmo** [comment]
@egolearner 
The master branch is for new milvus v2.0 (new architect, new language) now, If you want to working on the old milvus v1.x, please use 1.x branch or 1.1 branch(the latest code is in 1.1 branch).

**Comment by egolearner** [comment]
@yhmo 
Maybe v2.0 compiling guide will make it more convenient for the community to contribute.

**Comment by shengjun1985** [comment]
Develop Doc for 2.0:
https://github.com/milvus-io/milvus#to-start-developing-milvus
