### ISSUE TITLE
Mishards sometimes throw errors "Search failed"

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#5007]
**Please state your issue using the following template and, most importantly, in English.**
This issue is reported by user on slack.

**Describe the bug**
Deploy mishards on GCP

1.Prometheus data for insert per second is always consistent even when there is no write

2.The milvus mishard setup with a single write node and multiple read nodes failes to scale and always get error message: Search failed

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
2021-04-19 04:41:33 io.milvus.client.AbstractMilvusGrpcClient logError 
ERROR: Search failed:
error_code: UNEXPECTED_ERROR
reason: "Conn Group milvus-release-sharechat-creation-readonly-659798b6f-d7llq is Empty. Please Check your configurations"
Attempt no: 1
2021-04-19 04:41:34 io.milvus.client.AbstractMilvusGrpcClient logError 
ERROR: Search failed:
error_code: UNEXPECTED_ERROR
reason: "Conn Group milvus-release-sharechat-creation-readonly-659798b6f-d7llq is Empty. Please Check your configurations"
Attempt no: 2
2021-04-19 04:41:34 io.milvus.client.AbstractMilvusGrpcClient logError 
ERROR: Search failed:
error_code: UNEXPECTED_ERROR
reason: "Conn Group milvus-release-sharechat-creation-readonly-659798b6f-d7llq is Empty. Please Check your configurations"
returning default list after 3 retries
messages received: 16 
valid messages: 16
matchesFound: 0
clip post messages: 0
global queue messages: 16
10:12
ERROR: search RPC failed:
Status{code=UNKNOWN, description=Exception calling application: Fail connecting to server on 10.44.31.9:19530. Timeout, cause=null}
Attempt no: 1
2021-04-19 04:35:43 io.milvus.client.AbstractMilvusGrpcClient logError 
ERROR: search RPC failed:
Status{code=UNKNOWN, description=Exception calling application: Fail connecting to server on 10.44.31.9:19530. Timeout, cause=null}
Attempt no: 2
2021-04-19 04:37:14 io.milvus.client.AbstractMilvusGrpcClient logError 
ERROR: search RPC failed:
Status{code=UNKNOWN, description=Exception calling application: Fail connecting to server on 10.44.31.9:19530. Timeout, cause=null}
returning default list after 3 retries
messages received: 50 
valid messages: 50
matchesFound: 0
clip post messages: 0
global queue messages: 50

**Comment by yhmo** [comment]
By milvus-helm project,  increase/reduce the count of read-nodes can reproduce this error.

**Comment by sworddish** [comment]
what's the status of this bug?

**Comment by yhmo** [comment]
> what's the status of this bug?

Currently no resource to investigate it. The debug environment is not easy to build.

**Comment by yhmo** [comment]
This issue cannot catch v1.1.0 release point,  postpone to 1.2.0

**Comment by linchpinlin** [comment]
The same problem, when I upgrade readonly.replicas from 5 to 6.

**Comment by yhmo** [comment]
> @yhmo
> hello, I have the same problem, when I upgrade readonly.replicas from 5 to 6.

This is a bug of mishards. But we have no resource to deal with mishards issues now, most of resource is put into v2.0. Keep it as a know issue, wait v2.0 to replace mishards.
