### ISSUE TITLE
The search time of ivf_sq8 index increased by 26% when nq and topk are 100

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5031]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
http://172.16.50.20:5000/queries/75/source#169
Focus on the result between 2021-3-10 and 2021-3-12
```
gpu_search_threshold = 200
```
![image](https://user-images.githubusercontent.com/27288593/115979409-5bf0b800-a5b8-11eb-8cfb-974770a4a8d4.png)

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [x] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
-1.1 or 1.0

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by op-hunter** [comment]
There is one commit on Mar.12, commit id: c1fe9f635134889e50d361cc12e903c11826f8b2.
The previos commit id: fa07bf5390deedd01c328fef0ab08c3853858c4a.
I have compiled two GPU version server on the both commit id above and do a serveral tests, results shows below:
|fa07bf5390deedd01c328fef0ab08c3853858c4a| c1fe9f635134889e50d361cc12e903c11826f8b2|
|0.048067331314086914| 0.03842949867248535|
|0.04757428169250488| 0.04794812202453613|
|0.03976249694824219| 0.0462040901184082|
|0.03840184211730957| 0.04009509086608887|
|0.0393826961517334| 0.039357900619506836|
|0.03887033462524414| 0.039276838302612305|
dataset: sift-1m * 10
nlist: 16384
nprobe: 32
gpu_search_threshold: 200
nq: 100
topk: 100
query two times and get the better search time.

**Comment by ThreadDao** [comment]
![image](https://user-images.githubusercontent.com/27288593/116339693-74f3a600-a810-11eb-87c9-62707b7700b6.png)

**Comment by del-zhenwu** [comment]
rerun the same test case with using 1.0, still got the same result, so the search performance decreased before 1.0 released.
