### ISSUE TITLE
The search time of ivf_sq8h index increased by 28% when nq and topk are 100

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5034]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Please focus on the data of 2021-3-18 and 2021-3-19. and `gpu_search_threahold = 200`
![image](https://user-images.githubusercontent.com/27288593/115979731-2b118280-a5ba-11eb-9a23-d1ec12df47e2.png)

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [x] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 -1.1 or 1.0

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by del-zhenwu** [comment]
duplicated with #5031

**Comment by yhmo** [comment]
Close this one. Tracked by #5031
