### ISSUE TITLE
A suggestion to metadata management description in milvus documentation

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#5070]
**Please state your issue using the following template and, most importantly, in English.**
Before the v0.10.3, we use sqlite_orm library to connect/interact with SQLite, we found it sometimes throw exceptions randomly. But we could not find out the root cause. So we recommend user use MySQL as meta backend, especially for production.
In v0.10.4, we remove the sqlite_orm library, we directly call SQLite api. Seems this is much better than before, we never see the exceptions again. Personally I think SQLite is stable/robust enough for production, lot of companies use SQLite as database for their application, such as Firefox, Adobe AIR, etc . We still keep the recommendation because we think MySQL is better than SQLite.

**Location of incorrect documentation**
https://www.milvus.io/docs/v1.0.0/data_manage.md

**Describe the problems or issues found in the documentation**
Currently, the milvus reference give this sentence:
"Milvus uses SQLite as metadata management service in the backend by default. SQLite is embedded in the Milvus process, so there is no need to run additional services. However, in production, it is strongly recommended that you use MySQL as metadata management service because of reliability."

This sentence may bring confusion to users, they may think the SQLite cannot be used in production at all. But in fact SQLite is not no-go solution. 

**Suggested fix for documentation**

A suggestion to modify the sentence:
"When it comes to metadata management, Milvus uses SQLite by default not only because of its simplicity that no additional services needed to run, but also its decent robustness. However, in production, MySQL is recommended if you need even better reliability."

**Comment by yhmo** [comment]
The milvus server print a sentence at start: "WARNNING: You are using SQLite as the meta data management, which can't be used in production. Please change it to MySQL!"
This sentence also need to be changed, postpone this issue to next version 1.2.0.

**Comment by shengjun1985** [comment]
Done.
Thanks all.
