### ISSUE TITLE
Server crashed when creating a GPU IVF index whose dimension is 2048/4086/8192

### ISSUE THREAD

**Issue by Chisdo** [milvus-io/milvus#5078]
1. ISSUE:
 - GPU-enabled Milvus build index failed and keep restarting

2. Envs:
 - GPU: 2080 TI
 - GPU 1.0.0 Milvus
 - most of server_config.yaml are gpu-enabled-milvus default setting excepting disable WAL and set cache_size to 100GB

3. Steps to reproduce:
 i. build collection: {index_file_size=1024, **_dimension=2048_**}
 ii. index_parameter: {nlist: 1500}, index_type: {IVF_FLAT or IVF_PQ}
 iii. use GPU to build index
 iv1. client crushed info: 
<img width="695" alt="Screen Shot 2021-04-28 at 11 35 49" src="https://user-images.githubusercontent.com/36720318/116342909-fa2d8980-a815-11eb-8dc9-2dbd8d083040.png">
 iv2. server crushed info:
<img width="1093" alt="Screen Shot 2021-04-28 at 11 29 53" src="https://user-images.githubusercontent.com/36720318/116342936-0580b500-a816-11eb-83f9-d811b59d6217.png">
 v. I set up docker 'restart=always'. Hence, after restarting the Milvus, it starts to build index automatically on the background. Then, crush again.
 vi. At the end, the Milvus trapped into a 'restart -> build index -> crushed' cycle.

4. Expected behavior**
 i. I know the dimension might be too big for GPU, hence, I expect some 'assertion failed' for this failure.
 ii. For fixing this issue, my current solution is dropping the index before the Milvus crushed after each restarting. I expect the official solution of solving this issue should not be restarting the Milvus.

**Method of installation**
- [ ] Docker/cpu
- [x] Docker/gpu
- [ ] Build from source

**Comment by yhmo** [comment]
Could you show me the debug log before crash?
And please provide more information:
- how many vectors in the collection?
- metric type is L2 or IP?

**Comment by Chisdo** [comment]
> Could you show me the debug log before crash?
> And please provide more information:
> 
> * how many vectors in the collection?
> * metric type is L2 or IP?
> * Use `nvidia-smi -lms 100` to check the gpu memory usage on the node

1. 3M 2048-dim vectors in the collection. 
2. L2
3. GPU usage was keeping increasing rapidly[power usage] until the crash

**Comment by yhmo** [comment]
Link to #3646

**Comment by yhmo** [comment]
Seems the crash only occurs when dimension=2048.
Use the following script to test:
```
import random
import time
import threading
import numpy as np
from milvus import Milvus, IndexType
from milvus.client.types import MetricType

SERVER_ADDR = "127.0.0.1"
SERVER_PORT = '19530'
COLLECTION_NAME = "TEST"
COLLECTION_DIMENSION = 2100
COLLECTION_PARAM = {'collection_name': "",
                    'dimension': COLLECTION_DIMENSION,
                    'index_file_size': 1024,
                    'metric_type':MetricType.IP}
INDEX_TYPE = IndexType.IVF_FLAT
INDEX_PARAM = {'nlist': 1000}
NQ = 1
TOPK = 10
SEARCH_PARAM = {'nprobe': 16}

MILVUS = Milvus(host=SERVER_ADDR, port=SERVER_PORT)

def gen_vec_list(nb, seed=np.random.RandomState(1234)):
    xb = seed.rand(nb, COLLECTION_DIMENSION).astype("float32")
    vec_list = xb.tolist()
    return vec_list

def create_collection(name = COLLECTION_NAME):
    param = COLLECTION_PARAM
    param['collection_name'] = name
    status = MILVUS.create_collection(param)
    print("create", name)

def drop_collection(name = COLLECTION_NAME):
    status = MILVUS.drop_collection(collection_name=name)
    print("drop", name)

def get_collection_stats(name = COLLECTION_NAME):
    status, stat = MILVUS.get_collection_stats(collection_name=name)
    print(stat)

def create_index(name = COLLECTION_NAME):
    status = MILVUS.create_index(collection_name=name, index_type=INDEX_TYPE, params=INDEX_PARAM)
    print("index", status)

def insert(name = COLLECTION_NAME):
    batch = 10000
    for i in range(20):
        vectors = gen_vec_list(batch)
        status, ids = MILVUS.insert(collection_name=name, records=vectors)
        print("insert", i, len(ids), name)
    MILVUS.flush(collection_name_array=[name])

def search():
    q_records = [[random.random() for _ in range(COLLECTION_DIMENSION)] for _ in range(NQ)]
    status, results = MILVUS.search(collection_name=COLLECTION_NAME, query_records=q_records, top_k=TOPK,
                                    params=SEARCH_PARAM)
    print(status)
    print(results)

if __name__ == "__main__":
    drop_collection()
    create_collection()
    insert()
    create_index()
```

When COLLECTION_DIMENSION=1024/1500/2000/2100, milvus works well.
Only when COLLECTION_DIMENSION=2048, milvus crashed.
