### ISSUE TITLE
Remove unittest file from docker image

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#508]
**Describe the bug**
```
root@6d1f122cf348:/opt/milvus# du -sh *
321M	bin
24K	conf
103G	db
21M	lib
33G	logs
16K	scripts
3.0G	unittest

```

**Steps/Code to reproduce behavior**

**Expected behavior**

**Environment details**
0.6.0

**Screenshots**

**Additional context**

**Comment by ZhifengZhang-CN** [comment]
Done
