### ISSUE TITLE
load file disk2cpu cost 1000ms every time when query different collection 

### ISSUE THREAD

**Issue by JNero** [milvus-io/milvus#5086]
**前提:**
  -  单机版milvus，机器性能足够(最大内存占用1.2%),docker没有做资源限制。

**方法:**
  - 1.三份数据，分别建立了三个索引。collection名分别是 A_flat,B_hnsw,C_hnsw。
  -  2.自己封装了http接口去调用milvus 的rpc接口，依次调用三个collection。

**操作过程:**
  - 1.第一次调用B_hnsw，耗时1201ms；然后第二次调用B_hnsw，耗时5ms。
  - 2.第一次调用A_flat，耗时853ms；然后第二次调用A_flat，耗时28ms。
  - 3.第三次调用B_hnsw，耗时1194ms(在1步骤已经load过一次的索引，再次出现了长耗时)；然后第四次调用，耗时6ms；
  - 4.使用C_hnsw也出现了如上的情况。

**Debug过程:**
 - 去milvus服务查看debug日志，跟踪发现，每次切换索引查询时，都出现了load file disk2cpu cost 1.2s (1201ms) /0.8s (853ms)的日志。

**问题:**
 - 根据官网描述，仅在第一次查询时会耗时久，因为要将文件从磁盘load到内存中。但是在这里每次更换接口查询时，每次都会load，请问这里问题出在哪里？

**Comment by shengjun1985** [comment]
How about the data size of the three collections and the `cache_size` in your config?

Here is the default config value.
```yaml
cache:
  cache_size: 4GB
```

**Comment by JNero** [comment]
> How about the data size of the three collections and the `cache_size` in your config?
> 
> Here is the default config value.
> 
> ```yaml
> cache:
>   cache_size: 4GB
> ```

A_flat =1G,B_hnsw=1.4G,C_hnsw=400M

cache_size=1G

那应该就是cache_size设置小了的原因吧。

**Comment by shengjun1985** [comment]
Yes.
Modify the config file and try again : )

**Comment by JNero** [comment]
> Yes.
> Modify the config file and try again : )

ok,thx
