### ISSUE TITLE
Status(code=<StatusCode.UNAVAILABLE: (14, 'unavailable')>, message='Error occurred. Broken pipe') 

### ISSUE THREAD

**Issue by 785321021** [milvus-io/milvus#5091]
我正常查询milvus正常，没有问题。
如果我是用python的多进程查询milvus，8个进程。前边的8个查询会出错，后边的查询就正常了，每次第一次开启多进程查询会有错误，错误信息如下：

Status(code=<StatusCode.UNAVAILABLE: (14, 'unavailable')>, message='Error occurred. Broken pipe') None

Addr [172.19.80.37:19530] search
Rpc error: <_MultiThreadedRendezvous of RPC that terminated with:
 status = StatusCode.UNAVAILABLE
 details = "Broken pipe"
 debug_error_string = "{"created":"@1619683885.638189000","description":"Error received from peer ipv4:172.19.80.37:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Broken pipe","grpc_status":14}"
>
 {'API start': '2021-04-29 16:11:25.636274', 'RPC start': '2021-04-29 16:11:25.637291', 'RPC error': '2021-04-29 16:11:25.638888'}

**Comment by yhmo** [comment]
duplicated with #5093
