### ISSUE TITLE
Python multi-processor query get "Broken pipe" error

### ISSUE THREAD

**Issue by 785321021** [milvus-io/milvus#5093]
我单独查询milvus没有问题，用python的多进程同时查询milvus，8个进程，刚开始的时候前8次查询会提示错误，后边的查询没有问题，错误信息如下

Status(code=<StatusCode.UNAVAILABLE: (14, 'unavailable')>, message='Error occurred. Broken pipe') None

Addr [172.19.80.37:19530] search
Rpc error: <_MultiThreadedRendezvous of RPC that terminated with:
 status = StatusCode.UNAVAILABLE
 details = "Broken pipe"
 debug_error_string = "{"created":"@1619683885.638189000","description":"Error received from peer ipv4:172.19.80.37:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Broken pipe","grpc_status":14}"
>
 {'API start': '2021-04-29 16:11:25.636274', 'RPC start': '2021-04-29 16:11:25.637291', 'RPC error': '2021-04-29 16:11:25.638888'}

我的代码用的：
from multiprocessing import Pool

**Comment by yhmo** [comment]
For multi-process usage, please refer this:
https://milvus.io/docs/v0.6.0/operational_faq.md#Why-does-my-multiprocessing-program-fail

**Comment by yhmo** [comment]
And refer this issue: [#4863](https://github.com/milvus-io/milvus/issues/4863), it also get "Broken pipe" error,
Add "mp.set_start_method('spawn')" at the entry of your script maybe can resolve your problem.

**Comment by xiaofan-luan** [comment]
close this issue since it is not active for more than 3 months, reopen it if you have any other questions @785321021
