### ISSUE TITLE
Milvus 1.1 mishards can not run

### ISSUE THREAD

**Issue by JUNgege10** [milvus-io/milvus#5111]
milvus.client.exceptions.VersionError: Version of python SDK(1.0.0) not match that of server1.1.0, excepted is ('1.0.x',)

**Comment by shengjun1985** [comment]
mishards 1.1 has not released yet.
Please wait a few days.

**Comment by JUNgege10** [comment]
Okay TKS

**Comment by yhmo** [comment]
The milvus 1.1.0 and mishards 1.1.0 docker images have been released today.
Make sure sdk version matched, pymilvus==1.1.0
