### ISSUE TITLE
Relax the topk limit from 16384 to 1M for CPU search

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#5115]
**Please state your issue using the following template and, most importantly, in English.**
Loose the topk limitation from 16384 to 1M.

**Describe the bug**
Now the topk limitation is hard code (16384), but we heard some users say they want to query for high topk. 

**Expected behavior**
Change the definition in **/milvus/core/src/utils/ValidationUtil.h**
`constexpr int64_t QUERY_MAX_TOPK = 16384;`

And **/milvus/core/src/index/knowhere/knowhere/index/vector_index/ConfAdapter.cpp**
`static const int64_t MAX_K = 16384;`

Note:
- For GPU version, if user specify` topk < 16384` and `nq > gpu_search_threshold`, milvus will use GPU to search. Else, milvus will use CPU to search.
- If the search scope's vector count is less than topk, the result count will be less than topk
  For example: 
    10 segments, each segment has 100000 vectors, totally there are 1M vectors
    create IVF index, nlist = 1024
    search with nprobe = 100, topk = 1M, the result count is 100000+ , not 1M
    if with nprobe = 1024, topk = 1M, the result count is 1M

**Comment by yhmo** [comment]
Fixed in v1.1.1

**Comment by airwindk** [comment]
Hi it seems that the topk limit was reverted back to 16384 in milvus 2.0 - would it be possible to have this expanded to 1M as done in v1.1.1?

**Comment by hakan458** [comment]
Any comment on this?
