### ISSUE TITLE
Issue 3352, Thirdparty files download path can be configured 

### ISSUE THREAD

**Issue by lajiyuan** [milvus-io/milvus#5137]
Issue 3352： https://github.com/milvus-io/milvus/issues/3352

The -f parameter is still not supported.

![image](https://user-images.githubusercontent.com/38530078/117431631-09ba7a00-af5c-11eb-9f28-6fa3df8ec4f5.png)

**Comment by XuanYang-cn** [comment]
This function is supported on branch experimental & master

Not supported on 1.x, and no plans to support it.

**Comment by lajiyuan** [comment]
Ok. I'll close this issue.
