### ISSUE TITLE
NotConnectError: Timeout

### ISSUE THREAD

**Issue by orange-jams** [milvus-io/milvus#5138]
**Please state your issue using the following template and, most importantly, in English.**
Milvus Server cannot be connected after serval days.

**Describe the bug**
Retry to connect server 99.47.136.11:19530 failed.
---------------------------------------------------------------------------
FutureTimeoutError                        Traceback (most recent call last)
/usr/local/anaconda2/envs/python35/lib/python3.5/site-packages/milvus/client/grpc_handler.py in ping(self, timeout)
    206                 try:
--> 207                     ft.result(timeout=timeout)
    208                     return True

/usr/local/anaconda2/envs/python35/lib/python3.5/site-packages/grpc/_utilities.py in result(self, timeout)
    139     def result(self, timeout=None):
--> 140         self._block(timeout)
    141 

/usr/local/anaconda2/envs/python35/lib/python3.5/site-packages/grpc/_utilities.py in _block(self, timeout)
     85                         if remaining < 0:
---> 86                             raise grpc.FutureTimeoutError()
     87                         else:

FutureTimeoutError: 

During handling of the above exception, another exception occurred:

NotConnectError                           Traceback (most recent call last)
<ipython-input-87-2b9169101447> in <module>()
      1 from milvus import *
----> 2 client=Milvus(host="99.47.136.11", port="19530")

/usr/local/anaconda2/envs/python35/lib/python3.5/site-packages/milvus/client/stub.py in __init__(self, host, port, handler, pool, **kwargs)
     90             self._pool = ConnectionPool(pool_uri, **pool_kwargs)
     91         elif pool == "SingletonThread":
---> 92             self._pool = SingletonThreadPool(pool_uri, **pool_kwargs)
     93         elif pool == "Singleton":
     94             self._pool = SingleConnectionPool(pool_uri, **pool_kwargs)

/usr/local/anaconda2/envs/python35/lib/python3.5/site-packages/milvus/client/pool.py in __init__(self, uri, pool_size, wait_timeout, try_connect, **kwargs)
    224         # if self._try_connect:
    225         #     self._max_retry = kwargs
--> 226         self._prepare()
    227 
    228     def _prepare(self):

/usr/local/anaconda2/envs/python35/lib/python3.5/site-packages/milvus/client/pool.py in _prepare(self)
    229         conn = self.fetch()
    230         if self._try_connect:
--> 231             conn.client().ping()
    232 
    233         status, version = conn.client().server_version(timeout=30)

/usr/local/anaconda2/envs/python35/lib/python3.5/site-packages/milvus/client/grpc_handler.py in ping(self, timeout)
    216                         raise
    217         except grpc.FutureTimeoutError:
--> 218             raise NotConnectError('Fail connecting to server on {}. Timeout'.format(self._uri))
    219         except grpc.RpcError as e:
    220             raise NotConnectError("Connect error: <{}>".format(e))

NotConnectError: Fail connecting to server on 99.47.136.11:19530. Timeout

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
0.10.5

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
The connection is timeout. Does the milvus server work correctly?

**Comment by orange-jams** [comment]
> The connection is timeout. Does the milvus server work correctly?

Yes, the milvus server works correctly.

**Comment by yhmo** [comment]
> > The connection is timeout. Does the milvus server work correctly?
> 
> Yes, the milvus server works correctly.

The client and server are on different machine?
To exclude network problem, run the client on same machine with the server.
If still timeout, check the server version and client sdk version, make sure they are match. And check the server container is expose the correct port(docker run -p 19530:19530 ...).

**Comment by xiaofan-luan** [comment]
close this issue since it is not active more than 3 months. let us know if you have any updates @orange-jams
