### ISSUE TITLE
milvus 0.10.5 grpc error when connect the server

### ISSUE THREAD

**Issue by orange-jams** [milvus-io/milvus#5143]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
I deployed milvus:0.10.5-cpu on openshift, then when connecting the server I get the following error message

Addr [99.47.136.11:19530] _cmd
Rpc error: <_MultiThreadedRendezvous of RPC that terminated with:
    status = StatusCode.DEADLINE_EXCEEDED
    details = "Deadline Exceeded"
    debug_error_string = "{"created":"@1620455231.385659887","description":"Error received from peer ipv4:99.47.136.11:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
    {'RPC start': '2021-05-08 14:26:41.384839', 'API start': '2021-05-08 14:26:41.384643', 'RPC error': '2021-05-08 14:27:11.385994'}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda2/envs/python35/lib/python3.5/site-packages/milvus/client/stub.py", line 92, in __init__
    self._pool = SingletonThreadPool(pool_uri, **pool_kwargs)
  File "/usr/local/anaconda2/envs/python35/lib/python3.5/site-packages/milvus/client/pool.py", line 226, in __init__
    self._prepare()
  File "/usr/local/anaconda2/envs/python35/lib/python3.5/site-packages/milvus/client/pool.py", line 235, in _prepare
    raise NotConnectError("Cannot check server version: {}".format(status.message))
milvus.client.exceptions.NotConnectError: Cannot check server version: Error occurred. Deadline Exceeded

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
0.10.5

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
Typically, the "Cannot check server version: Error occurred. Deadline Exceeded" means the client cannot access milvus server. Maybe mistake or something block the connection.
In the issue #4928, the user also deploy milvus on openshift, and they can connect milvus successfully.

**Comment by xiaofan-luan** [comment]
close for now since it's no longer active for more than 3 months. @orange-jams
