### ISSUE TITLE
Error code definition

### ISSUE THREAD

**Issue by scsven** [milvus-io/milvus#5144]
Proposal

System Error: E01000~
K8S Error: E02000~
Proxy Error: E03000~
Master: E04000~
Data Service/Node: E05000~
Index Service/Node: E06000~
Query Service/Node: E07000~
SDK Error: E08000~

**Comment by yanliang567** [comment]
what about this:
System Error: E01000~
K8S Error: E02000~
Proxy Error: E03000~
Master: E04000~
Data Service/Node: E05000~
Index Service/Node: E06000~
Query Service/Node: E07000~
SDK Error: E08000~

**Comment by yanliang567** [comment]
if possible, please fix the design for error code in 2.0

**Comment by xiaofan-luan** [comment]
what kind of cases do we need error code?

**Comment by xiaofan-luan** [comment]
@scsven

**Comment by yanliang567** [comment]
I think we need a definition of all errors with error code and error msg, so that users would search and understand the error quickly in the docs
