### ISSUE TITLE
Automatic tuning of index parameters

### ISSUE THREAD

**Issue by shengjun1985** [milvus-io/milvus#5149]
Milvus provides users with multiple vector index types, and each index type has different index parameters. However, for many users, it is challenging to fully understand all the index parameters and functions so that optimal parameters are often not chosen. 

We hope to create a tuning tool that can help users automatically generate query parameters for better performance.

**Comment by xiaofan-luan** [comment]
@shengjun1985  are we still working on this?

**Comment by shengjun1985** [comment]
YiXiaoMeng and LvZhao are working on it.
