### ISSUE TITLE
Need an API to list all connection name 

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#5155]
**Please state your issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**
When testing of API add_connection, we can not check the result of add or not.

**Describe the solution you'd like**
Need an API list_connection to check all connection name.

**Describe alternatives you've considered**

**Additional context**

**Comment by czs007** [comment]
[pr](https://github.com/milvus-io/pymilvus-orm/pull/119)

**Comment by czs007** [comment]
Added in sdk repo, please refer to this [pr](https://github.com/milvus-io/pymilvus-orm/pull/119)

**Comment by wangting0128** [comment]
Verified
