### ISSUE TITLE
Exception should be raised if delete entity on the none-existed partition

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#5164]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
    # TODO:
    def _test_delete_vector_from_partition_not_existed(self, connect, collection):
        '''
        target: test.get_entity_by_id with partition params, partition tag not existed
        method: add vector, and delete
        expected: status not
        '''
        vectors = gen_vectors(nb, dim)
        status = connect.create_partition(collection, tag)
        assert status.OK()
        status, ids = connect.insert(collection, vectors, partition_tag=tag)
        assert status.OK()
        status = connect.flush([collection])
        assert status.OK()
        length = 1
        tmp_tag = gen_unique_str()
        status = connect.delete_entity_by_id(collection, ids[:length], partition_tag=tmp_tag)
        assert not status.OK()


```
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by shengjun1985** [comment]
@del-zhenwu 
Please confirm.

**Comment by yhmo** [comment]
With latest code of branch 1.1
- get_entity_by_id() on a non-exist partition, client will receive this status:
Status(code=1, message='The specified partition does not exist') []

- delete_entity_by_id() on a non-exist partition, client will receive this status:
Status(code=1, message='Collection xx partition_tag xxx does not exist. Use milvus.partition to verify whether the partition exists. You also can check whether the partition name exists.')
