### ISSUE TITLE
CPU utility is low when search request can't be combined.

### ISSUE THREAD

**Issue by denial-aa** [milvus-io/milvus#5167]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
CPU utility is low when search request can't be combined.

**Steps/Code to reproduce behavior**
vectors was originized in around 1000 different partition, each partition is small.request was randomly distribute in these 1000 partition,which make request can't be combined(only request with same patition will be combined) and result in low cpu utility.

**Method of installation**
Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)
centos 7, 40 core CPU ,128G mem

- Milvus version (master or released version)
v 1.0.0

**Comment by shengjun1985** [comment]
This needs a more powerful scheduler which allows multi tasks execute simultaneously.

**Comment by yhmo** [comment]
Need to investigate this. There maybe be improvement in scheduler machinery for such scenario.

**Comment by yhmo** [comment]
Now we only fix critical bugs for v1.x. Abandon this issue.
