### ISSUE TITLE
Support service registration and discovery

### ISSUE THREAD

**Issue by godchen0212** [milvus-io/milvus#5174]
**Please state your issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**
We want to know right away that a service is up or crashes down.

**Describe the solution you'd like**
Implements service registration through etcd lease and keepalive mechanism and implements service discovery through etcd watch mechanism.

**Comment by neza2017** [comment]
please the format of `key`  and `value` that the modules used to register in etcd ?

**Comment by godchen0212** [comment]
> please the format of `key` and `value` that the modules used to register in etcd ?

key: metaRootPath + "ServerName(-ServerID)(optional)"
value: json format
{
    "NodeName": ServerName(-ServerID)(optional) // ServerName and ServerID
    "IP": IP // IP of service
    "LeaseID": LeaseID // The ID of etcd lease
}
MetaRootPath is configurable in the config file.

For example:
A proxynode with id 0 uses the following key and value to register with etcd.
key: "by-dev/meta/node/proxynode-0"
value: {"NodeName":"proxynode-0","IP":"172.16.50.13:19530","LeaseID":7668637733884014890}
