### ISSUE TITLE
Data (Incremental) backup strategy

### ISSUE THREAD

**Issue by innerNULL** [milvus-io/milvus#5186]
Hi, 

I plan to backup my milvus data, and the milvus service is deployed on k8s cluster.

My question is, All I need to backup is just the milvus records data saved on k8s nfs pv and the metadata saved in mysql?

Thanks.

**Comment by yhmo** [comment]
Yes
- records data under /milvus/db folder
- metadata in a database named 'milvus' in MySQL.

**Comment by innerNULL** [comment]
> Yes
> 
> * records data under /milvus/db folder
> * metadata in a database named 'milvus' in MySQL.

@yhmo got it, thanks~
