### ISSUE TITLE
Support to use the local filesystem to persist data

### ISSUE THREAD

**Issue by scsven** [milvus-io/milvus#5187]
Currently, Milvus uses minIO to store data, because the data needs to be shared by multiple components distributed on the network. With standalone deployment, all components in one progress, use the local filesystem to persist data can provide better performance.

We hope to implement a kv-store based on the local filesystem and add a configure to switch minIO or local filesystem as the storage backend in standalone deployment.

**Comment by 1uvu** [comment]
So what kinds of data type the storage needs to contain, e.g., string, list, set, and hash table?
I don't know much about this project at present, please forgive me.
