### ISSUE TITLE
No connection is available after creating connection

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5198]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
1. test scripts
```
from pymilvus_orm import Connections, utility

ip = "192.168.1.x"
port = 19530

if __name__ == '__main__':
    conn = Connections()
    conn.configure(default={"host": ip, "port": port})
    conn.get_connection(alias="default")
    conns = conn.list_connections()
    print("connections: {}".format(conns))
    print(utility.list_collections(using='default'))
```
2. results
```
connections: ['default']
Traceback (most recent call last):
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.6/site-packages/pymilvus_orm/connections.py", line 131, in get_connection
    return self.create_connection(alias, **self._kwargs[alias])
KeyError: 'default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zong/zong/Projects/milvus/tests20/python_client/base/test.py", line 15, in <module>
    print(utility.list_collections(using='default'))
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.6/site-packages/pymilvus_orm/utility.py", line 258, in list_collections
    return get_connection(using).list_collections()
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.6/site-packages/pymilvus_orm/connections.py", line 134, in get_connection
    raise KeyError("There is no connection with alias %r." % alias)
KeyError: "There is no connection with alias 'default'."
```
3. the reason is 
```
# utility.py
def list_collections(timeout=None, using="default") -> list:
    return get_connection(using).list_collections()
```
```
# connections.py
# Singleton Mode in Python

connections = Connections()
configure = connections.configure
list_connections = connections.list_connections
get_connection_addr = connections.get_connection_addr
remove_connection = connections.remove_connection
create_connection = connections.create_connection
get_connection = connections.get_connection
```
4. The problem also exist in Collections and so on

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 -pymilvus-orm master

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
It has been fixed by sdk. Please retest.

**Comment by xiaocai2333** [comment]
This design is for interacting with other components, and users can only call instances in connections.

**Comment by xiaocai2333** [comment]
It will be fixed in pymilvus-orm.
But you need add `self._connect` before `print(utility.list_collections(using='default'))`.
Because `conn` and `pymilvus.utility` are different objects.

**Comment by ThreadDao** [comment]
1. new a Connections object not import connections (`connections = Connections() // pymilvus-orm.py`)
`conn = Connections()`
2. create a connection
```
conn.configure(...)
conn.create_connection(..)
```
3. use connection
`utility.list_collections()`
This call will fail. Because in utility, `connections` is be used rather `conn`
`from .connections import get_connection //utility.py`


**I** don't know if I made it clear

**Comment by xiaocai2333** [comment]
The connections class is implemented in a singleton class, so that different construction methods construct the same object.

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/136
