### ISSUE TITLE
Config file version doesn't match

### ISSUE THREAD

**Issue by buzhihuoyefeng** [milvus-io/milvus#5203]
**Please state your issue using the following template and, most importantly, in English.**
I try to install v.1.0.0,but the vision of server_config.yaml is 0.5,finally I see error:"ERROR [default] [SERVER][CheckConfigVersion][milvus_server] Invalid config version: . Expected config version: 0.5 Invalid config version: . Expected config version: 0.5 Milvus server exit... Config check fail: Invalid config version: . Expected config version: 0.5 ERROR: Milvus server fail to load config file " in my log.

**Location of incorrect documentation**
Provide links and line numbers if applicable.

**Describe the problems or issues found in the documentation**
A clear and concise description of what you found to be incorrect.

**Steps taken to verify documentation is incorrect**
List any steps you have taken:

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.

---

## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken:

**Comment by shengjun1985** [comment]
How did you install Milvus, [from Source Code](https://github.com/milvus-io/milvus/blob/1.1/INSTALL.md) or [on Docker](https://milvus.io/docs/install_milvus.md)?
And have you check your config file?

**Comment by yhmo** [comment]
I think this is caused by in-compatible/legacy config file. 
Inactive and close.
