### ISSUE TITLE
Weird default pagination settings for Partitions in milvus-admin UI

### ISSUE THREAD

**Issue by scipe** [milvus-io/milvus#5207]
Hello friends. 
I just found weird pagination settings for partitions in admin UI. Look at screenshot below.
![Screenshot 2021-05-13 at 18 58 27](https://user-images.githubusercontent.com/3996622/118152383-4afbcf80-b41d-11eb-9869-7198cf53a828.png)

So I have 5 partitions (+1 _default). But for some reason I can see only 2 partitions on one page. I can change page and see others partitions.. but it's kinda weird. 

Image: milvusdb/milvus-em:v0.4.2
Milvus: 1.1.0

**Comment by shanghaikid** [comment]
@scipe I see the next page button is enabled, can you click that button to see if there are some partitions? 

anyway, we will investigate this issue.

**Comment by scipe** [comment]
Yeah, I can see all of them by changing page. There is 2 partitions per each page. 

In chrome console I see xhr request to api with limit=2.

**Comment by shanghaikid** [comment]
@scipe thanks for this finding. We will release a hot fix for the admin UI. 

I think we will open source this UI soon,  stay tuned.

**Comment by nameczz** [comment]
@scipe Already released v0.4.3, fix this bug. Any more advice is welcome!

**Comment by scipe** [comment]
Thanks dude! I will upgrade my deployments :)

**Comment by scipe** [comment]
Hey buddy @yhmo. Any chance to approve https://github.com/milvus-io/milvus-helm/pull/177 ?
