### ISSUE TITLE
Support using the ID search that already exists in the collection

### ISSUE THREAD

**Issue by scsven** [milvus-io/milvus#5215]
In some scenarios, users need to search with vectors that already exist in the collection. 

We hope to add a function that searches using ids already exist in the collection.

related: #4811 #4586 #4457 #3203

Requirement from @keotic :
In a scenario where the query vectors ids are given, conducting a search by using the ids as queries instead
of vectors will reduce the big overhead of retrieving the vectors by ids and then conducting a search.

For example: given a 1000 entities ids as queries, on a 2048 dim index, there will be a call to get the entities by ids
that will return 1000 * 2048 vectors, then there will be another call with the same payload of 1000 * 2048 to get the top k of each vector.

We can prevent the 2 calls and the payload transfer by retrieving the vectors by their ids on the server / db side and making the search.

**Comment by Tialo** [comment]
Was it implemented? I couldn't find if this could be done. @yhmo

**Comment by xiaofan-luan** [comment]
not yet

**Comment by Tialo** [comment]
Maybe this should be reopened? This feature is useful and reopening would make it clear that it is still anticipated

**Comment by xiaofan-luan** [comment]
we have other issues track this

**Comment by Tialo** [comment]
Can you mention number of relevant issue? Because I've seen that this issue was often mentioned, for example here https://github.com/milvus-io/milvus/issues/4811#issuecomment-898172679

**Comment by xiaofan-luan** [comment]
https://github.com/milvus-io/milvus/issues/39157 is one of them
