### ISSUE TITLE
Support to set precision of distances in search result

### ISSUE THREAD

**Issue by scsven** [milvus-io/milvus#5217]
The search request will return the id and distance fields, where the distance field is a floating-point number. The distance calculated by Milvus is a 32-bit floating-point number, but the python SDK return and display it in 64-bit floating-point. Some precision is invalid. In addition, some users want to be able to directly set the precision of the return value.

We hope support to specify the precision of the distance returned when searching.

related: #4818

**Comment by priyanshuone6** [comment]
Hey, I saw this project on Summer 2021 and found It interesting, could you please tell me what should be my next steps?

**Comment by kateshaowanjou** [comment]
> Hey, I saw this project in Summer 2021 and found It interesting, could you please tell me what should be my next steps?

Hi Priyanshu, are you currently a student? The Summer 2021 program, much like GSoC, is only open to students to participate. If yes, please read the student guideline here first before you register and apply for the task: https://summer.iscas.ac.cn/help/en/student/.

Then you can apply the task or other tasks that you find interesting from the Milvus community: https://summer.iscas.ac.cn/#/org/orgdetail/milvus?lang=en

If you have any questions, feel free to email the mentor of the task. In this case, the mentor is Cai Zhang <cai.zhang@zilliz.com>.

**Comment by kateshaowanjou** [comment]
> > Hey, I saw this project in Summer 2021 and found It interesting, could you please tell me what should be my next steps?
> 
> Hi Priyanshu, are you currently a student? The Summer 2021 program, much like GSoC, is only open to students to participate. If yes, please read the student guideline here first before you register and apply for the task: https://summer.iscas.ac.cn/help/en/student/.
> 
> Then you can apply the task or other tasks that you find interesting from the Milvus community: https://summer.iscas.ac.cn/#/org/orgdetail/milvus?lang=en
> 
> If you have any questions, feel free to email the mentor of the task. In this case, the mentor is Cai Zhang [cai.zhang@zilliz.com](mailto:cai.zhang@zilliz.com).
