### ISSUE TITLE
Support kafka as the messaging system

### ISSUE THREAD

**Issue by wxyucs** [milvus-io/milvus#5218]
Milvus uses a messaging system to process Insert and Search requests. Currently, there are only two messaging systems supported, pulsar for distributed deployment and RocksDB for standalone deployment.

We hope to support Kafka as the messaging system, and it can be configured for users.

**Comment by martyanov** [comment]
@scsven Is there any ETA for Kafka? Pulsar seems as a much weaker choice in comparioon to Kakfa? What was the reasoning behind the choice?

**Comment by xiaofan-luan** [comment]
> @scsven Is there any ETA for Kafka? Pulsar seems as a much weaker choice in comparison to Kafka. What was the reasoning behind the choice?

Hi martyanov, we may want to support both kafka and Pulsar in the near future. We love pulsar because it's careful design and storage/compuation disaggregation. But for sure kafka has more users and better stability !

**Comment by xiaofan-luan** [comment]
any updates?
I would like to import this feature part by part rather than a big bang to the codebase team~
