### ISSUE TITLE
Channel-name's vairable name is confusing

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#5230]
`ChannelID` vs `ChannelName`

Some places like https://github.com/milvus-io/milvus/blob/168b917f5b1ffe9f9257a25548cb264b0032b2b6/internal/proto/internal.proto#L115 uses ChannelID

Some places like https://github.com/milvus-io/milvus/blob/168b917f5b1ffe9f9257a25548cb264b0032b2b6/internal/datanode/flow_graph_insert_buffer_node.go#L149 uses ChannelName

We need to unify the variable name.

**Comment by shanghaikid** [comment]
Maybe you can take a look at this styling guide. 

https://github.com/golang/go/wiki/CodeReviewComments @XuanYang-cn @scsven

**Comment by XuanYang-cn** [comment]
@czs007 @xige-16 We need to discuss about this
