### ISSUE TITLE
The original description is lost when creating a collection with duplicate names

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5231]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
1. create collection "c"
2. create collection with (name="c", schema=None, data=None)
3. two collections have different schema (description is different)
```
 {"auto_id": true, "description": "default collection", "fields": [{"name": "int64", "description": "int64 type field", "type": 5}, {"name": "float", "description": "float type field", "type": 10}, {"name": "float_vector", "description": "float vector type field", "type": 101, "params": {"dim": 128}}]} (test_collection.py:73)
 {"auto_id": true, "description": "", "fields": [{"name": "int64", "description": "int64 type field", "type": 5}, {"name": "float", "description": "float type field", "type": 10}, {"name": "float_vector", "description": "float vector type field", "type": 101, "params": {"dim": "128"}}]} (test_collection.py:74)
```
4. the reason in `schema.py`
```
    @classmethod
    def construct_from_dict(cls, raw):
        fields = [FieldSchema.construct_from_dict(field_raw) for field_raw in raw['fields']]
        return CollectionSchema(fields, raw.get('description', ""))
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus-orm master

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
It has been fixed in pymilvus. Please retest it.
