### ISSUE TITLE
Release the vector data from memory after the related index loaded into memory

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#5270]
**Is your feature request related to a problem? Please describe.**
In Milvus 1.0, when an index is built, both the index and the vector data are loaded into memory, which causes double size of the memory are consumed. e.g.  128d, 10M-rows vector data consume 5G memory, and 5M more memory for index ivf_flat.

**Describe the solution you'd like**
When the index were built and loaded into memory, the related vector data in memory shall be released from memory.

If this is not in the 2.0 plan, please try to make it.

**Comment by xige-16** [comment]
If there is an index file when loading, milvus 2.0 does not load the original vector when loading.

**Comment by yanliang567** [comment]
close per comments above
