### ISSUE TITLE
Not support to CUDA11

### ISSUE THREAD

**Issue by sweshixing** [milvus-io/milvus#5281]
**Please state your issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**
For RTX 3090, milvus 1.x cannot work normally on  milvus gpu container that Milvus.io released.I have tried to compile milvus 1.0 and 1.1 source code，none of  them can  compile successfully. It dose not seem to support cuda 11, could you 
please make the next version of milvus compile  on cuda 11 nomarlly?

THANKS!

**Comment by sweshixing** [comment]
> The RTX 3090 is NVIDIA Ampere architect, it require CUDA 11.0.
> But currently the FAISS support to cuda10.x, it cannot be compiled with cuda11.0. Milvus depends on FAISS, so Milvus currently cannot support cuda11.0, too.

In [Rebuild for cuda111_112 #29](https://github.com/conda-forge/faiss-split-feedstock/pull/29#issue-574670722), it seems to support cuda11 now?

**Comment by yhmo** [comment]
> > The RTX 3090 is NVIDIA Ampere architect, it require CUDA 11.0.
> > But currently the FAISS support to cuda10.x, it cannot be compiled with cuda11.0. Milvus depends on FAISS, so Milvus currently cannot support cuda11.0, too.
> 
> In [Rebuild for cuda111_112 #29](https://github.com/conda-forge/faiss-split-feedstock/pull/29#issue-574670722), it seems to support cuda11 now?

The link you give is not from FAISS project. In FAISS project, the FAISS install documentation still use CUDA 10:
https://github.com/facebookresearch/faiss/blob/master/INSTALL.md

For cuda 11 compatible issue, we had a code change on a experimental branch:
https://github.com/milvus-io/milvus/pull/4701/files
The difference between cuda 10 and 11 is a name changed.
