### ISSUE TITLE
No exception was thrown when creating a collection without vector fields

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5285]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
create collection only with an int field didn't raise an exception.
```
    def test_collection_without_vectors(self):
        """
        target: test collection without vectors
        method: create collection only with int field
        expected: raise exception
        """
        self._connect()
        c_name = gen_unique_str(prefix)
        schema = gen_collection_schema([gen_int64_field()])
        ex, _ = self.collection.collection_init(c_name, schema=schema)
        log.info(str(ex))
```
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus-orm master

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/140
