### ISSUE TITLE
Question on milvus/core/src/utils/BlockingQueue.inl

### ISSUE THREAD

**Issue by aixi** [milvus-io/milvus#529]
**What is your question?**
template<typename T>
void
BlockingQueue<T>::SetCapacity(const size_t capacity) {
    capacity_ = (capacity > 0 ? capacity : capacity_);
}

the parameter capacity is size_t type, it is a unsigned integral type, maybe no need to check capacity > 0, as long as someone does not set capacity to 0

**Comment by JinHai-CN** [comment]
This is a protection to prevent set 0 to capacity.
