### ISSUE TITLE
milvus client init with timeout

### ISSUE THREAD

**Issue by mask-zpt** [milvus-io/milvus#5290]
It will block forever in method getServerVersion when the milvus server is not on serving. No Exception throws .

![image](https://user-images.githubusercontent.com/4207801/118760624-b7575280-b8a5-11eb-8db1-ce5afe4875fd.png)

eg. Miluvs version 0.10.6  , client version : milvus-sdk-java 0.8.6

**Comment by yhmo** [comment]
The java sdk 0.8.6 seems is problematic. I use 0.8.5 can work with milvus 0.10.6.

```
    String host = "localhost";
    int port = 19530;

    ConnectParam connectParam = new ConnectParam.Builder().withHost(host).withPort(port).build();
    MilvusClient client = new MilvusGrpcClient(connectParam);

    Response res = client.getServerVersion();
    System.out.format("Collection Stats: %s\n", res.getMessage());
```

**Comment by yhmo** [comment]
Inactive and close.
