### ISSUE TITLE
Collection is empty after insert data with dataframe

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5302]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
    def test_collection_with_dataframe(self):
        self._connect()
        nb = ct.default_nb
        c_name = cf.gen_unique_str(prefix)
        data = cf.gen_default_dataframe_data(nb)
        log.info(data.count())
        collection, _ = self.collection.collection_init(c_name, schema=default_schema, data=data)
        log.info(collection.num_entities)
        assert_default_collection(collection, c_name, exp_num=nb)
```
The first line if `data.count()`
```
FAILED [100%][2021-05-19 17:34:00,461 - INFO - refactor_test]: 
int64           3000
float           3000
float_vector    3000
dtype: int64 (test_collection.py:220)
[2021-05-19 17:34:00,570 - INFO - refactor_test]: 0 (test_collection.py:222)

testcases/test_collection.py:214 (TestCollectionParams.test_collection_with_dataframe)
0 != 3000

Expected :3000
Actual   :0
<Click to see difference>
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus-orm master

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yanliang567** [comment]
The same problem to partition.insert
