### ISSUE TITLE
The schema type is not checked when the collection is repeatedly created

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5304]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
1. create a collection name "test"
2. create the collection with dup name "test" and non-CollectionSchema schema
3. expected `raise SchemaNotReadyException(0, "schema type must be schema.CollectionSchema.")`
However, the exception is:
```
 assert 'schema type must be schema.CollectionSchema' in "'tuple' object has no attribute 'to_dict'"
E        +  where "'tuple' object has no attribute 'to_dict'" = str(AttributeError("'tuple' object has no attribute 'to_dict'",))
```
Reason: when `test` collection exist and schema is not none, the code didn't check `if isinstance(schema, CollectionSchema)`
pymilvus-orm.collection.py
```
        if has:
            resp = conn.describe_collection(self._name)
            server_schema = CollectionSchema.construct_from_dict(resp)
            if schema is None:
                self._schema = server_schema
                if data is not None:
                    self.insert(data=data)
            else:
                if server_schema != schema:
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/140
