### ISSUE TITLE
ANN search by entities ids

### ISSUE THREAD

**Issue by keotic** [milvus-io/milvus#5307]
**Please state your issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**
In a scenario where the query vectors ids are given, conducting a search by using the ids as queries instead
of vectors will reduce the big overhead of retrieving the vectors by ids and then conducting a search.

For example: given a 1000 entities ids as queries,  on a 2048 dim index, there will be a call to get the entities by ids
that will return 1000 * 2048 vectors, then there will be another call with the same payload of 1000 * 2048 to get the top k of each vector.

We can prevent the 2 calls and the payload transfer by retrieving the vectors by their ids on the server / db side and making the search.

**Describe the solution you'd like**
The same search apis, but with ids instead of vectors and the query

**Describe alternatives you've considered**
As described above, making 2 calls with big payload

**Additional context**
Adding range search  capabilities (Dot lower threshold, or L2 max distance)  will allow to further reduce calls and payloads size

**Comment by yhmo** [comment]
Duplicate with #4811

**Comment by shengjun1985** [comment]
For some graph indexes, passing ID is more efficient than passing vector.
This feature is worth investigating.

**Comment by shengjun1985** [comment]
We can discuss it in #5215
