### ISSUE TITLE
No exception was thrown when creating a collection with empty fields

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5312]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
create a collection with empty fields [] didn't raise an exception
```
    def test_collection_empty_fields(self):
        """
        target: test collection with empty fields
        method: create collection with fields = []
        expected: exception
        """
        self._connect()
        c_name = cf.gen_unique_str(prefix)
        schema = cf.gen_collection_schema(fields=[])
        ex, _ = self.collection.collection_init(c_name, schema=schema)
        log.debug(ex.name)
```
collection.name
```
[2021-05-20 11:32:21,416 - DEBUG - refactor_test]: collection_Ur9PGHgy (test_collection.py:255)
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus-orm master

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/140
