### ISSUE TITLE
milvus-bot: I, robot

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#5319]
**First Law**

I obey your orders and rules like `/assign @XuanYang-cn `.

**Second Law**

I merge PRs unless the PR violates the rules of the first law.

**Third Law**

I notify you when I need your help.

Could you please create me? @XuanYang-cn @scsven

**Comment by scsven** [comment]
@XuanYang-cn Maybe we need a new repo to handle this kind of problem?

**Comment by scsven** [comment]
@XuanYang-cn I think milvus-io/community may be the right where to discuss about robot.

**Comment by XuanYang-cn** [comment]
@scsven I think @jeffoverflow  has done a lot, and we may be able to have a Prow powered robot very soon.

**Comment by scsven** [comment]
@XuanYang-cn Agree. @jeffoverflow please join our discussion.

**Comment by jeffoverflow** [comment]
I can quickly build a robot system based on existing requirements.

**Comment by yhmo** [comment]
__T__     
     |  o | o |
     |__v__|    
 ]=o=[::+]=o=[   
       [___]
       /     |      
      _\    |_
