### ISSUE TITLE
Although there is an error, it seems that the illegal type of fields is not checked

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5331]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
CollectionSchema with invalid fields type (fields=invalid)
```
1,
[1, "2", 3],
(1,),
{1: 1},
None,
"12-s",
"12 s",
"(mn)",
"中文",
"%$#",
```
but the error message:
```
the xxx (eg int or str...) object is not iterable 
the xxx (eg int or str...) object has no attribute 'is_primary' 
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus-orm master

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yanliang567** [comment]
I think SDK should pop up the error about invalid type, instead of an error caused by the invalid type.

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/138

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/140

**Comment by ThreadDao** [comment]
Test CollectionSchema(fields) with invalid type fields (eg str)
Maybe the error exception should more instructive. Now the errors like `xx object has no len()`, ans `xx object has no attribute dtype` are difficult to assert and confuses users.

1. Firstly, check the fields should `isinstance(fields, list)', if not raise exception "fields should be a list"
2. second, check the field (in fields) that should be a `FieldSchema`  type, if not raise exception "...should be FieldSchema type"

The above are my thoughts, you have the final say.

**Comment by xiaocai2333** [comment]
The codes you pasted represent data? Instead of field type?

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/144
