### ISSUE TITLE
Enabling s3 storage by default on 1.x

### ISSUE THREAD

**Issue by matrixji** [milvus-io/milvus#5335]
**Please state your issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**
Currently, we are building Milvus with s3 support by ourselves, and we want to directly use the official images later.

**Describe the solution you'd like**
We have finished some testing with CPU/GPU mode with S3 support under self managed kubernetes, and I plan to do the PRs as below:
- [x] Enabling 1.x build with S3 support ON by default and disable it by default in configurations.
- [ ] Some guidelines for setup Milvus with S3 support, may including using: minio, ceph-radosgw, minio(gateway)+gcs.
- [ ] milvus-helm to support s3 storage configuration, from: https://github.com/matrixji/milvus-helm/tree/add-s3-storage-support

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by yhmo** [comment]
@matrixji 
Is this issue require change the server_config.yaml? I suppose there should be some items added ti server_config.

**Comment by matrixji** [comment]
> @matrixji
> Is this issue require change the server_config.yaml? I suppose there should be some items added ti server_config.

Agree with it, I'll add the s3 related storage item and descriptions to the server_config.yml within those commits.

**Comment by yhmo** [comment]
Already done
