### ISSUE TITLE
Code annotation wrong in pymilvus-orm:collection.py

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#5337]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
In function: is_empty and num_entities
collection.load() should be added after collection.insert() before showing the new property of the inserted collection:

>>>collection.is_empty
True
>>>data = [[1,2,3,4]]
>>>collection.insert(data)
[424769928069057860, 424769928069057861, 424769928069057862, 424769928069057863]
>>>collection.is_empty
 False

**Steps/Code to reproduce behavior**
N/A

**Expected behavior**
>>>data = [[1,2,3,4]]
>>>collection.insert(data)
[424769928069057860, 424769928069057861, 424769928069057862, 424769928069057863]
**>>> collection.load() # load collection to memory**
>>>collection.is_empty
 False

**Method of installation**
N/A

**Environment details**
N/A

- Milvus version (master or released version)
milvus 2.0
the latest pymilvus-orm 0.0.1

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaofan-luan** [comment]
collection.is_empty and num_entities should be refer to data on disk, in other way, it should be irrelevant  to whether the collection is load. We may add another parameter to indicate the memory status but for now it should be exactly the entity numbers user ingest

**Comment by binbinlv** [comment]
The design has changed, and no load action is needed. So no need to modify the text here, close it.

Name: pymilvus
Version: 2.0a1.dev42
Name: pymilvus-orm
Version: 2.0a1.dev40

Results:
>>> res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
>>> collection.is_empty
False
>>> collection.num_entities
500
