### ISSUE TITLE
No exception is thrown when creating a collection with multi float vector fields

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5345]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Create a collection with two float-vector fields, and no exception
```
    def test_collection_multi_float_vectors(self):
        self._connect()
        c_name = cf.gen_unique_str(prefix)
        fields = [cf.gen_float_vec_field(), cf.gen_float_vec_field(name="tmp")]
        schema = cf.gen_collection_schema(fields=fields)
        collection, _ = self.collection.collection_init(c_name, schema=schema)
        # assert_default_collection(collection, c_name, exp_schema=schema)
        log.info(collection.schema)
```
```
 {"auto_id": true, "description": "collection", "fields": [{"name": "float_vector", "description": "float vector type field", "type": 101, "params": {"dim": 128}}, {"name": "tmp", "description": "float vector type field", "type": 101, "params": {"dim": 128}}]} (test_collection.py:377)

```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus-orm master

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by ThreadDao** [comment]
Create a collection with fields both float-vec and binary-vec, and no exception
```
{"auto_id": true, "description": "collection", "fields": [{"name": "float_vector", "description": "float vector type field", "type": 101, "params": {"dim": 128}},
{"name": "binary_vector", "description": "binary vector type field", "type": 100, "params": {"dim": 128}}]} (test_collection.py:390)

```

**Comment by scsven** [comment]
@ThreadDao In Milvus, create a collection with multiple vector fields is legal. So it's not an issue.

**Comment by ThreadDao** [comment]
ok. please fix the exception
` [Collection API Exception]<function func_req at 0x7f8ede93d160>: <SchemaNotReadyException: (code=0, message=The schema must have one and only one vector column!)> `

**Comment by xiaocai2333** [comment]
The collection contains at least one vector column,  and there can be multiple vector columns.

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/143
