### ISSUE TITLE
Search performance get worse while increasing nlist

### ISSUE THREAD

**Issue by sweshixing** [milvus-io/milvus#5347]
**Describe the bug**
I have deployed two milvus-server in one machine. And one of milvus-server db is absolutely copied by another, I also have created two mysql databases for these two milvus-server.All the row data, meta data, logs, wal, conf of these two milvus-server are independent.

Milvus-server 1 and Milvus-server 2 has the same config expect servers' port and index nlist. Milvus-server 1's nlist is 65536, milvus-server 2's nlist is 5800. Their index type is all IVFSQ8. But milvus-server 1 cost 18s-20s to search with nq=1000 and nprobe=32, milvus-server 2 cost 5s to search with nq=1000 and nprobe=32. Why Search performance get worse while increasing nlist？

**Comment by shengjun1985** [comment]
Here is the introduction and search process of [IVF](https://milvus.io/docs/v1.1.0/index.md#IVF_FLAT).
According to your description, most time of server 1 may be spent on this step: `select the nprobe nearest units from the nlist units`.
So `nlist` is not as bigger as better.

**Comment by yhmo** [comment]
We can estimate computing workload for a single search action.
First of all, let's say "calculate two vectors distance" is a "unit".
For IVF index, the search action will run two steps:
1. calculate distance between input vector and each center point of nlist buckets, find out nprobe buckets
2. calculate distance between input vector and each vector of nprobe buckets

Assume there is only one segment.
Let's say the total vector count in db is total_count.
So, the first step will take `nq * nlist` "unit".
Ideally, each bucket has total_count/nlist vectors. So, the second step will take `nq * nprobe * total_count/nlist` "unit"
Two steps will take:
`nq *(nlist + nprobe * total_count/nlist) `"unit"

From this expression, we can know the performance is not always get better when nlist get larger.
In your case, nq = 1000, nprobe = 32, assume your vector count = 1000000
The server 1 nlist = 65536, the server 2 nlist = 5800.
Then, the server_1 will take 1000 * (65536 + 32 * 1000000/65536) = 66024281 = 66M units
The server_2 will take 1000 * (5800 + 32 * 1000000/5800) = 11317241 = 11M units
That means the server_1 's computing workload is 6 times of server_2, this is why "search performance get worse while increasing nlist".

**Comment by sweshixing** [comment]
> We can estimate computing workload for a single search action.
> First of all, let's say "calculate two vectors distance" is a "unit".
> For IVF index, the search action will run two steps:
> 
> 1. calculate distance between input vector and each center point of nlist buckets, find out nprobe buckets
> 2. calculate distance between input vector and each vector of nprobe buckets
> 
> Assume there is only one segment.
> Let's say the total vector count in db is total_count.
> So, the first step will take `nq * nlist` "unit".
> Ideally, each bucket has total_count/nlist vectors. So, the second step will take `nq * nprobe * total_count/nlist` "unit"
> Two steps will take:
> `nq *(nlist + nprobe * total_count/nlist) `"unit"
> 
> From this expression, we can know the performance is not always get better when nlist get larger.
> In your case, nq = 1000, nprobe = 32, assume your vector count = 1000000
> The server 1 nlist = 65536, the server 2 nlist = 5800.
> Then, the server_1 will take 1000 * (65536 + 32 * 1000000/65536) = 66024281 = 66M units
> The server_2 will take 1000 * (5800 + 32 * 1000000/5800) = 11317241 = 11M units
> That means the server_1 's computing workload is 6 times of server_2, this is why "search performance get worse while increasing nlist".

Thanks a lot！Your analysis is very detailed and easy to understand！So the best search performance is with nslit = sqrt(nprobe* total_count) .
