### ISSUE TITLE
No exception is thrown when creating a collection with non-bool is_primary value

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5350]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
1. define field with `is_primary=non-bool value' such as 1, []..
2. create a collection
```
    def test_collection_field_invalid_primary(self, get_invalid_string):
        """
        target: test collection with invalid primary
        method: define field with is_primary=non-bool
        expected: raise exception
        """
        self._connect()
        c_name = cf.gen_unique_str(prefix)
        int_field = cf.gen_int64_field(name="int", is_primary=get_invalid_string)
        float_vec_field = cf.gen_float_vec_field()
        schema = cf.gen_collection_schema(fields=[int_field, float_vec_field])
        c, _ = self.collection.collection_init(c_name, schema=schema)
        log.info(c.schema)
```
```
[  8%][2021-05-21 19:27:48,970 - INFO - refactor_test]: {"auto_id": true, "description": "collection", "fields": [{"name": "int", "description": "int64 type field", "type": 5}, {"name": "float_vector", "description": "float vector type field", "type": 101, "params": {"dim": 128}}]} (test_collection.py:507)
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus-orm master

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/140

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/141
