### ISSUE TITLE
The VectorIds inserted to milvus is not exactly what I just did inserted

### ISSUE THREAD

**Issue by lengyhua** [milvus-io/milvus#5356]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
1、We prepared about 20 pieces of sample data to insert into milvus and the vertorIds is as follows:
	   	`[6964655414562523045,6964655414562523046,6964655414562523048,6964655414562523051,6964655414562523052,6964655414562523053,6964655414562523055,6964655414562523057,6964655414562523059,6964655414562523060,6964655414562523068,6964655414562523070,6964655414562523071,6964655414562523072,6964655414562523049,6964655414562523050,6964655414562523056,6964655414562523061,6964655414562523063,6964655414562523064,6964655414562523065,6964655414562523066,6964655414562523067]`
2、After insert done, We get the inserted vectorIds using client.listIDInSegment(String collectionName, String segmentName) and we got vectorIds with slightly different with what we had just inserted, which is as follows:
  `[184,6964655414562523045,6964655414562523046,6964655414562523048,6964655414562523051,6964655414562523052,6964655414562523053,6964655414562523055,6964655414562523057,6964655414562523059,6964655414562523060,6964655414562523068,6964655414562523070,6964655414562523071,6964655414562523072,6964655414562523049,6964655414562523050,6964655414562523056,6964655414562523061,6964655414562523063,6964655414562523064,6964655414562523065,6964655414562523066]`
	
	It can be seen that the final vectorId: 6964655414562523067 is missing and vectorId: 184 appeared in the queried  result which I did not insert before.

3、Though the inserted vectorIds is not we just did, we still did the search by the same sample data, and the result is wrong of course, I picked one of them to explain:
	`6964655414562523045:[{"distance":1,"vectorId":184},{"distance":0.14214735,"vectorId":6964655414562523072},{"distance":0.12373489,"vectorId":6964655414562523068},{"distance":0.11202198,"vectorId":6964655414562523060},{"distance":0.111873925,"vectorId":6964655414562523063},{"distance":0.10618009,"vectorId":6964655414562523052},{"distance":0.10591597,"vectorId":6964655414562523053},{"distance":0.0835617,"vectorId":6964655414562523071},{"distance":0.071142904,"vectorId":6964655414562523064},{"distance":0.05324409,"vectorId":6964655414562523056},{"distance":0.05034396,"vectorId":6964655414562523049},{"distance":0.04912449,"vectorId":6964655414562523055},{"distance":0.037875578,"vectorId":6964655414562523059},{"distance":0.034030627,"vectorId":6964655414562523051},{"distance":0.024231153,"vectorId":6964655414562523050},{"distance":0.01668688,"vectorId":6964655414562523061},{"distance":0.0019118721,"vectorId":6964655414562523048},{"distance":-0.017082274,"vectorId":6964655414562523057},{"distance":-0.02947367,"vectorId":6964655414562523046},{"distance":-0.048240136,"vectorId":6964655414562523045},{"distance":-0.051583078,"vectorId":6964655414562523065},{"distance":-0.053393733,"vectorId":6964655414562523066},{"distance":-0.20088542,"vectorId":6964655414562523070}]`

	first: it contains the vectorId of 184 I just mentioned before, which is reasonable in the situation just happed in insertion.
	second: I have definitely confidence to say that the max score with 6964655414562523045 should be itself as I had just used the same sample in the collection and the searched sample.
	third:  {"distance":-0.048240136,"vectorId":6964655414562523045}, this result is absolutely wrong.

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [*] Docker/gpu
- [*] Build from source

- Milvus version (master or released version)
We compiled from #5306 based on 1.1

**Comment by yhmo** [comment]
With the latest code of branch 1.1, and use the following script to test:

```
import random
import time
import numpy as np
from milvus import Milvus, IndexType
from milvus.client.types import MetricType

SERVER_ADDR = "127.0.0.1"
SERVER_PORT = '19530'
COLLECTION_NAME = "TEST"
COLLECTION_DIMENSION = 128
COLLECTION_PARAM = {'collection_name': COLLECTION_NAME,
                    'dimension': COLLECTION_DIMENSION,
                    'index_file_size': 10,
                    'metric_type':MetricType.IP}


MILVUS = Milvus(host=SERVER_ADDR, port=SERVER_PORT)

def gen_vec_list(nb, seed=np.random.RandomState(1234)):
    xb = seed.rand(nb, COLLECTION_DIMENSION).astype("float32")
    vec_list = xb.tolist()
    return vec_list

def create_collection():
    status = MILVUS.create_collection(COLLECTION_PARAM)
    print("create", COLLECTION_NAME, status)

def insert():
    vec_ids = [6964655414562523045,6964655414562523046,6964655414562523048,6964655414562523051,6964655414562523052,6964655414562523053,6964655414562523055,6964655414562523057,6964655414562523059,6964655414562523060,6964655414562523068,6964655414562523070,6964655414562523071,6964655414562523072,6964655414562523049,6964655414562523050,6964655414562523056,6964655414562523061,6964655414562523063,6964655414562523064,6964655414562523065,6964655414562523066,6964655414562523067]
    vectors = gen_vec_list(len(vec_ids))
    status, ids = MILVUS.insert(collection_name=COLLECTION_NAME, records=vectors, ids=vec_ids)
    print("insert", len(ids), "vectors")
    print(ids)
    status = MILVUS.flush(collection_name_array=[COLLECTION_NAME])

def drop_collection():
    MILVUS.drop_collection(collection_name=COLLECTION_NAME)
    print("drop collection", COLLECTION_NAME)


def list_ids():
    status, stats = MILVUS.get_collection_stats(collection_name=COLLECTION_NAME)
    # print(stats)
    part_default = stats["partitions"][0]
    segments = part_default["segments"]
    for seg in segments:
        seg_name = seg["name"]
        print("list ids in segment", seg_name)
        status, ids = MILVUS.list_id_in_segment(collection_name=COLLECTION_NAME, segment_name=seg_name)
        print(ids)


if __name__ == "__main__":
    drop_collection()
    create_collection()
    insert()
    list_ids()



```
The result seems is correct:

```
drop collection TEST
create TEST Status(code=0, message='Create collection successfully!')
insert 23 vectors
[6964655414562523045, 6964655414562523046, 6964655414562523048, 6964655414562523051, 6964655414562523052, 6964655414562523053, 6964655414562523055, 6964655414562523057, 6964655414562523059, 6964655414562523060, 6964655414562523068, 6964655414562523070, 6964655414562523071, 6964655414562523072, 6964655414562523049, 6964655414562523050, 6964655414562523056, 6964655414562523061, 6964655414562523063, 6964655414562523064, 6964655414562523065, 6964655414562523066, 6964655414562523067]
list ids in segment 1621925088663047000
[6964655414562523045, 6964655414562523046, 6964655414562523048, 6964655414562523051, 6964655414562523052, 6964655414562523053, 6964655414562523055, 6964655414562523057, 6964655414562523059, 6964655414562523060, 6964655414562523068, 6964655414562523070, 6964655414562523071, 6964655414562523072, 6964655414562523049, 6964655414562523050, 6964655414562523056, 6964655414562523061, 6964655414562523063, 6964655414562523064, 6964655414562523065, 6964655414562523066, 6964655414562523067]
```

The steps is:
- create a collection
- insert 20 vectors into the collection, dimension=128, id = [6964655414562523045, 6964655414562523046, 6964655414562523048, 6964655414562523051, 6964655414562523052, 6964655414562523053, 6964655414562523055, 6964655414562523057, 6964655414562523059, 6964655414562523060, 6964655414562523068, 6964655414562523070, 6964655414562523071, 6964655414562523072, 6964655414562523049, 6964655414562523050, 6964655414562523056, 6964655414562523061, 6964655414562523063, 6964655414562523064, 6964655414562523065, 6964655414562523066, 6964655414562523067]
- list ids in segment

Anything missed ? @lengyhua

**Comment by yhmo** [comment]
The pr https://github.com/milvus-io/milvus/pull/5393 is to fix this, please get the latest code to try.

**Comment by lengyhua** [comment]
> The pr #5393 is to fix this, please get the latest code to try.

yes, @matrixji have solved this.

**Comment by shengjun1985** [comment]
It is fixed. Thanks all.
