### ISSUE TITLE
Improve documentation of function usage

### ISSUE THREAD

**Issue by DrBamba** [milvus-io/milvus#5357]
I found myself having a lot of trouble remembering exactly what each function returns and in what format.
It would be very helpful if every function will have exactly what variables it gets, what each one of them stands for, what she returns and in what formatit returns.
For now I had to just make a try, see what I'm getting and adjust my code. 
Which is very time consuming
For example when I Searched vectors, if there were vectors inside the collection it would return a list of lists of results per vector I searched for.
When the collection was empty it returns an empty list rather then maybe a list of empty lists per vector I searched for.

**Comment by yhmo** [comment]
We have stop update v1.x sdk (except critical bug reported). 
Now the v2.0 python sdk documentation is pretty good with rich description and examples: https://milvus.io/api-reference/pymilvus-orm/v2.0.0rc4/api/collection.html
Inactive and close.
