### ISSUE TITLE
The dtype of data is parsed wrong when inserts data to collection

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#5366]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

The dtype of data is parsed wrong when inserted data to collection
(pymilvus-> schema.py->parse_fields_from_data->...)

when inserting data into collection, it reports
 " pymilvus_orm.exceptions.SchemaNotReadyException: <SchemaNotReadyException: (code=0, message=The types of schema and data do not match.)>"

But the data type of the inserted data is actually match with that of collection schma field:
[i for i in range(nb)]              --- DataType.INT64
[float(i) for i in range(nb)]    --- DataType.FLOAT
[[random.random() for _ in range(dim)] for _ in range(nb)]      --- DataType.FLOAT_VECTOR

However, the data type parsed from code is:
[i for i in range(nb)]                       ----- DataType.FLOAT_VECTOR
[float(i) for i in range(nb)]            ----- DataType.FLOAT_VECTOR
[[random.random() for _ in range(dim)] for _ in range(nb)]      -----  DataType.UNKNOWN

which is not expected.

**Steps/Code to reproduce behavior**
 1. create collection
        default_schema = gen_default_collection_schema()
        collection = self._collection(default_collection_name, data=None, schema=default_schema)
2. insert data
            nb = 3000
            dim = default_dim
            vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
           collection.insert([[i for i in range(nb)], [float(i) for i in range(nb)], vectors])

And 

def gen_default_collection_schema():
    fields = [gen_int64_field(), gen_float_field(), gen_float_vec_field()] # DataType.INT64, DataType.FLOAT, DataType.FLOAT_VECTOR
    schema = CollectionSchema(fields=fields, description="default collection")
    return schema

**Expected behavior**
Data is inserted without any errors (dtype of inserted data is parsed successfully without errors)

**Method of installation**
- [ ] Docker/cpu

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
latest 2.0 (master)
pymilvus (latest)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
It has fixed in orm. 

https://github.com/milvus-io/pymilvus-orm/pull/128

**Comment by binbinlv** [comment]
Verified, and it has been fixed，so close it.

inserted successfully, and the data type is parsed successfully without any errors:
DataType.INT64
DataType.FLOAT
DataType.FLOAT_VECTOR
