### ISSUE TITLE
Create collection with a duplicate name but get different collection field params

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5367]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
1. create a collection with name "c"
2. create dup collection with "c"
3. `collection.schema == dup_collection.schema`
```
    def test_collection_dup_name(self):
        self._connect()
        collection = self._collection()
        c_name = collection.name
        assert_default_collection(collection)
        dup_collection, _ = self.collection.collection_init(c_name)
        assert collection.name == dup_collection.name
        assert collection.schema == dup_collection.schema
        assert collection.num_entities == dup_collection.num_entities
        assert id(collection) == id(dup_collection)
        assert collection.name in self.utility.list_collections()
```
The dup collection schema is changed `"params": {"dim": 128}` -> `"params": {"dim": "128"}`
```
collection: {"auto_id": true, "description": "", "fields": [{"name": "int64", "description": "", "type": 5}, {"name": "float", "description": "", "type": 10}, {"name": "float_vector", "description": "", "type": 101, "params": {"dim": 128}}]}
dup_collection: {"auto_id": true, "description": "", "fields": [{"name": "int64", "description": "", "type": 5}, {"name": "float", "description": "", "type": 10}, {"name": "float_vector", "description": "", "type": 101, "params": {"dim": "128"}}]}
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus-orm master

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yanliang567** [comment]
does it repro if:
  collection = self._collection()
  c_name = collection.name
 dup_collection = self._collection(c_name)

**Comment by xiaocai2333** [comment]
It has been fixed in pymilvus.
