### ISSUE TITLE
update "partition tag" to "partition name" for milvus 2.0 SDK

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#5375]
**Describe the bug**
partition tag is changed to partition name in milvus 2.0 SDK(pymilvus-orm), so the related messages should be updated accordingly

**Steps/Code to reproduce behavior**
        ex, _ = self.partition.partition_init(m_collection, None)
        log.info(ex)

**Expected behavior**
'partition name' value xxx is illegal

Actual
`partition_tag` value {1: 1} is illegal
`partition_tag` value None is illegal
...

**Comment by yanliang567** [comment]
related testcase:    
tests20/testcases/test_partition.py::TestPartitionParams::test_partition_invalid_name

**Comment by scsven** [comment]
Related pull requests:

https://github.com/milvus-io/pymilvus/pull/533
https://github.com/milvus-io/milvus/pull/5514

**Comment by yanliang567** [comment]
one more left with 'partition tag'
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=Invalid partition tag: . Partition tag should not be empty.)>

**Comment by scsven** [comment]
@yanliang567 
fixed in #5834

**Comment by yanliang567** [comment]
found 2 error msg was updated incompletely:
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=Invalid partition name: 12 s. Partition tag can only contain numbers, letters, dollars and underscores.)>
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=Invalid partition name: %$#. The first character of a partition tag must be an underscore or letter.)>

**Comment by scsven** [comment]
@yanliang567 Does this issue still exist?
