### ISSUE TITLE
can't get the connection to the docker server 

### ISSUE THREAD

**Issue by EUCHI1996** [milvus-io/milvus#5382]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

Hello ,

I got an issue when i try to run the example.py script to test milvus server.
I deploy milvus as container on port 19121, and i try to execute the script from the same machine with (Host=Ip address of the host machine and port =19121), but ii got this issue.
I used pymilvus 1.0.1 version, python 3.6.9 version
##########################################################################
Retry to connect server 127.0.0.1:19121 failed.
Traceback (most recent call last):
  File "/home/azureuser/.local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 207, in ping
    ft.result(timeout=timeout)
  File "/home/azureuser/.local/lib/python3.6/site-packages/grpc/_utilities.py", line 140, in result
    self._block(timeout)
  File "/home/azureuser/.local/lib/python3.6/site-packages/grpc/_utilities.py", line 86, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 127, in <module>
    main()
  File "example.py", line 27, in main
    milvus = Milvus(_HOST, _PORT)
  File "/home/azureuser/.local/lib/python3.6/site-packages/milvus/client/stub.py", line 97, in __init__
    self._pool = SingletonThreadPool(pool_uri, **pool_kwargs)
  File "/home/azureuser/.local/lib/python3.6/site-packages/milvus/client/pool.py", line 226, in __init__
    self._prepare()
  File "/home/azureuser/.local/lib/python3.6/site-packages/milvus/client/pool.py", line 231, in _prepare
    conn.client().ping()
  File "/home/azureuser/.local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 218, in ping
    raise NotConnectError('Fail connecting to server on {}. Timeout'.format(self._uri))
milvus.client.exceptions.NotConnectError: Fail connecting to server on 127.0.0.1:19121. Timeout
########################################################################

**Method of installation**
- [ ] Docker/cpu

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml`

**Comment by filip-halt** [comment]
Hi, 
Which version of Milvus docker container are you using?

**Comment by EUCHI1996** [comment]
I used this image milvusdb/milvus:0.10.5-cpu-d010621-4eda95

**Comment by EUCHI1996** [comment]
And i try also this image milvusdb/milvus:1.0.0-cpu-d030521-1ea92e

**Comment by filip-halt** [comment]
Any chance you can give it a try using pymilvus=1.1.0 and milvusdb/milvus:1.1.0-cpu-d050721-5e559c

**Comment by EUCHI1996** [comment]
Hello, i try with the given version but i still have the same issue

**Comment by filip-halt** [comment]
Any chance you can post the code that you are using to launch the server?

**Comment by EUCHI1996** [comment]
this is the code, that i used 

**********************

# This program demos how to connect to Milvus vector database,
# create a vector collection,
# insert 10 vectors,
# and execute a vector similarity search.

import random
import numpy as np

from milvus import Milvus, IndexType, MetricType, Status

# Milvus server IP address and port.
# You may need to change _HOST and _PORT accordingly.
_HOST = '127.0.0.1'
_PORT = '19121'  # default value
# _PORT = '19121'  # default http value

# Vector parameters
_DIM = 8  # dimension of vector

_INDEX_FILE_SIZE = 32  # max file size of stored index


def main():
    # Specify server addr when create milvus client instance
    # milvus client instance maintain a connection pool, param
    # `pool_size` specify the max connection num.
    milvus = Milvus(_HOST, _PORT)

    # Create collection demo_collection if it dosen't exist.
    collection_name = 'example_collection_'

    status, ok = milvus.has_collection(collection_name)
    if not ok:
        param = {
            'collection_name': collection_name,
            'dimension': _DIM,
            'index_file_size': _INDEX_FILE_SIZE,  # optional
            'metric_type': MetricType.L2  # optional
        }

        milvus.create_collection(param)

    # Show collections in Milvus server
    _, collections = milvus.list_collections()

    # Describe demo_collection
    _, collection = milvus.get_collection_info(collection_name)
    print(collection)

    # 10000 vectors with 128 dimension
    # element per dimension is float32 type
    # vectors should be a 2-D array
    vectors = [[random.random() for _ in range(_DIM)] for _ in range(10)]
    print(vectors)
    # You can also use numpy to generate random vectors:
    #   vectors = np.random.rand(10000, _DIM).astype(np.float32)

    # Insert vectors into demo_collection, return status and vectors id list
    status, ids = milvus.insert(collection_name=collection_name, records=vectors)
    if not status.OK():
        print("Insert failed: {}".format(status))

    # Flush collection  inserted data to disk.
    milvus.flush([collection_name])
    # Get demo_collection row count
    status, result = milvus.count_entities(collection_name)

    # present collection statistics info
    _, info = milvus.get_collection_stats(collection_name)
    print(info)

    # Obtain raw vectors by providing vector ids
    status, result_vectors = milvus.get_entity_by_id(collection_name, ids[:10])

    # create index of vectors, search more rapidly
    index_param = {
        'nlist': 2048
    }

    # Create ivflat index in demo_collection
    # You can search vectors without creating index. however, Creating index help to
    # search faster
    print("Creating index: {}".format(index_param))
    status = milvus.create_index(collection_name, IndexType.IVF_FLAT, index_param)

    # describe index, get information of index
    status, index = milvus.get_index_info(collection_name)
    print(index)

    # Use the top 10 vectors for similarity search
    query_vectors = vectors[0:10]

    # execute vector similarity search
    search_param = {
        "nprobe": 16
    }

    print("Searching ... ")

    param = {
        'collection_name': collection_name,
        'query_records': query_vectors,
        'top_k': 1,
        'params': search_param,
    }

    status, results = milvus.search(**param)
    if status.OK():
        # indicate search result
        # also use by:
        #   `results.distance_array[0][0] == 0.0 or results.id_array[0][0] == ids[0]`
        if results[0][0].distance == 0.0 or results[0][0].id == ids[0]:
            print('Query result is correct')
        else:
            print('Query result isn\'t correct')

        # print results
        print(results)
    else:
        print("Search failed. ", status)

    # Delete demo_collection
    status = milvus.drop_collection(collection_name)


if __name__ == '__main__':
    main()

**Comment by EUCHI1996** [comment]
# This program demos how to connect to Milvus vector database,
# create a vector collection,
# insert 10 vectors,
# and execute a vector similarity search.

import random

from milvus import Milvus, IndexType, MetricType, Status

# Milvus server IP address and port.
# You may need to change _HOST and _PORT accordingly.
_HOST = 'localhost'
_PORT = '19121'  # default value
# _PORT = '19121'  # default http value

# Vector parameters
_DIM = 8  # dimension of vector

_INDEX_FILE_SIZE = 32  # max file size of stored index


def main():
    # Specify server addr when create milvus client instance
    # milvus client instance maintain a connection pool, param
    # `pool_size` specify the max connection num.
    milvus = Milvus(_HOST, _PORT)

    # Create collection demo_collection if it dosen't exist.
    collection_name = 'example_collection_'

    status, ok = milvus.has_collection(collection_name)
    if not ok:
        param = {
            'collection_name': collection_name,
            'dimension': _DIM,
            'index_file_size': _INDEX_FILE_SIZE,  # optional
            'metric_type': MetricType.L2  # optional
        }

        milvus.create_collection(param)

    # Show collections in Milvus server
    _, collections = milvus.list_collections()

    # Describe demo_collection
    _, collection = milvus.get_collection_info(collection_name)
    print(collection)

    # 10000 vectors with 128 dimension
    # element per dimension is float32 type
    # vectors should be a 2-D array
    vectors = [[random.random() for _ in range(_DIM)] for _ in range(10)]
    print(vectors)
    # You can also use numpy to generate random vectors:
    #   vectors = np.random.rand(10000, _DIM).astype(np.float32)

    # Insert vectors into demo_collection, return status and vectors id list
    status, ids = milvus.insert(collection_name=collection_name, records=vectors)
    if not status.OK():
        print("Insert failed: {}".format(status))

    # Flush collection  inserted data to disk.
    milvus.flush([collection_name])
    # Get demo_collection row count
    status, result = milvus.count_entities(collection_name)

    # present collection statistics info
    _, info = milvus.get_collection_stats(collection_name)
    print(info)

    # Obtain raw vectors by providing vector ids
    status, result_vectors = milvus.get_entity_by_id(collection_name, ids[:10])

    # create index of vectors, search more rapidly
    index_param = {
        'nlist': 2048
    }

    # Create ivflat index in demo_collection
    # You can search vectors without creating index. however, Creating index help to
    # search faster
    print("Creating index: {}".format(index_param))
    status = milvus.create_index(collection_name, IndexType.IVF_FLAT, index_param)

    # describe index, get information of index
    status, index = milvus.get_index_info(collection_name)
    print(index)

    # Use the top 10 vectors for similarity search
    query_vectors = vectors[0:10]

    # execute vector similarity search
    search_param = {
        "nprobe": 16
    }

    print("Searching ... ")
    param = {
        'collection_name': collection_name,
        'query_records': query_vectors,
        'top_k': 3,
        'params': search_param,
    }

    status, results = milvus.search(**param)
    if status.OK():
        # indicate search result
        # also use by:
        #   `results.distance_array[0][0] == 0.0 or results.id_array[0][0] == ids[0]`
        if results[0][0].distance == 0.0 or results[0][0].id == ids[0]:
            print('Query result is correct')
        else:
            print('Query result isn\'t correct')

        # print results
        print(results)
    else:
        print("Search failed. ", status)

    # Delete demo_collection
    #status = milvus.drop_collection(collection_name)
    # added code
    print("results :")
    #print(results[5][0].distance)

if __name__ == '__main__':
    main()

**Comment by filip-halt** [comment]
What about the script run to start the docker server?

**Comment by EUCHI1996** [comment]
I don't use any script, i used docker run command : 
This the command that i used :  

***********************

sudo docker run -d --name milvus_cpu_1.1.0 -p 19530:19530 -p 19121:19121 -v /home/$USER/milvus/db:/var/lib/milvus/db -v /home/$USER/milvus/conf:/var/lib/milvus/conf -v /home/$USER/milvus/logs:/var/lib/milvus/logs -v /home/$USER/milvus/wal:/var/lib/milvus/wal milvusdb/milvus:1.1.0-cpu-d050721-5e559c

**Comment by filip-halt** [comment]
Can you run that same command without the "-d" and see if you get a successful startup?

**Comment by EUCHI1996** [comment]
The docker container is successfully started it's ok : 

I get this return when i run sudo docker logs container_id : 

*******************************


    __  _________ _   ____  ______
   /  |/  /  _/ /| | / / / / / __/
  / /|_/ // // /_| |/ / /_/ /\ \
 /_/  /_/___/____/___/\____/___/

Welcome to use Milvus!
Milvus Release version: v1.1.0, built at 2021-05-06 14:50.43, with OpenBLAS library.
You are using Milvus CPU edition
Last commit id: 5e559cd7918297bcdb55985b80567cb6278074dd

Loading configuration from: /var/lib/milvus/conf/server_config.yaml
WARNNING: You are using SQLite as the meta data management, which can't be used in production. Please change it to MySQL!
Supported CPU instruction sets: avx2, sse4_2
FAISS hook AVX2
Milvus server started successfully!

**Comment by filip-halt** [comment]
For the code in the example code, can you try changing it to 19530?

**Comment by EUCHI1996** [comment]
i try it without -d and i got the same issue

**Comment by EUCHI1996** [comment]
yes, i try with 19530 port and i get another error:

************************
Segmentation fault (core dumped)

**Comment by yhmo** [comment]
For the "Segmentation fault", please refer https://github.com/milvus-io/milvus/issues/5377
The grpcio lib version of client side may be unmatch to the server:
Try install the two libs by `pip install`:
```
grpcio==1.22.0
grpcio-tools==1.22.0
```

**Comment by EUCHI1996** [comment]
Hello @yhmo  ,

Thank you very much. I wish you good continuation and this kind of problem helps you to improve in the next versions of the milvus.

Best Regards !
