### ISSUE TITLE
Topk searching returns k pieces of same data

### ISSUE THREAD

**Issue by sweshixing** [milvus-io/milvus#5383]
**Describe the bug**
I queried vector by milvus and it returned topk data, but there was so weird that the topk data was all the same.

**Steps/Code to reproduce behavior**
```python
milvus_inputs = {
    "collection_name": MILVUS_CONFIG["collection_name"], 
    "query_records": query_vector,
    "top_k": top_k,
    "partition_tags": MILVUS_CONFIG["partitions"],
    "params": params
}
status, query_result = milvus_client.search(**milvus_inputs)
```
**milvus_inputs:** 
    - topk=20,
    - patririon_tags=None,
    - params={'nprobe':32}
    - query_records: A list with one piece of 256 demension vector
![9E0B2427-6A99-43F6-B80F-631A71F0F322](https://user-images.githubusercontent.com/24455669/119426034-18b27200-bd3b-11eb-8f74-038d1d35b2d8.png)

**collection detail**
Queried collection is simbert_test
![image](https://user-images.githubusercontent.com/24455669/119425268-a68d5d80-bd39-11eb-8d90-07fb8e2cdb4f.png)

After I called milvus_client.search(), it returned `query_result`, but `query_result`'s topk were 20 same ids and distance.
![44AD9CDC-2472-4028-8412-FA7F9BC996EF](https://user-images.githubusercontent.com/24455669/119426247-6e871a00-bd3b-11eb-88b8-61e6f02f8550.png)
![FB068B15-2F8F-44C8-BE2B-1B57E01DDE71](https://user-images.githubusercontent.com/24455669/119426254-71820a80-bd3b-11eb-8fe6-f62dc716c393.png)

Why topk queried results were all the same?

**Comment by shengjun1985** [comment]
What Milvus version do you use?
And is it possible that there are some duplicate vectors?

**Comment by sweshixing** [comment]
> What Milvus version do you use?
> And is it possible that there are some duplicate vectors?

milvus-cpu-1.1.0

But when I search id `1000002698544411`, it just returned one result.
When i used `1000002698544411` 's vector to search topk(20), it returned 20 same data.

![6239287A-B4E7-45A8-8E33-C7967D059EA6](https://user-images.githubusercontent.com/24455669/119448208-91c5bf80-bd63-11eb-82bf-f9c2feb4ac16.png)
![6A33660E-C351-403D-A42D-DE5F22B9DCBD](https://user-images.githubusercontent.com/24455669/119448207-91c5bf80-bd63-11eb-99e4-2471839d09e8.png)

**Comment by shengjun1985** [comment]
>  When I search id 1000002698544411, it just returned one result.

That interface only returns the first vector whose ID matches.

**Comment by sweshixing** [comment]
> > When I search id 1000002698544411, it just returned one result.
> 
> That interface only returns the first vector whose ID matches.

I had found that there were truely duplicate vectors.
