### ISSUE TITLE
Exceptions when partition.search without expr param

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#5384]
**Describe the bug**
in pymilvus-orm, when partition.search without expr, it pops up exceptions

**Steps/Code to reproduce behavior**
result = m_partition.search(data=search_vec,
                                    anns_field=default_float_vec_field_name,
                                    params={"nprobe": 32},
                                    limit=1
                                    )

**Expected behavior**
no exception

Actual:
TypeError: None has type NoneType, but expected one of: bytes, unicode
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/milvus/client/prepare.py:657: TypeError

in pymilvus-orm, the parititon.search defination is:
def search(self, data, anns_field, params, limit, **expr=None,** output_fields=None, timeout=None,
               **kwargs):
which means if no expr is specified by client, expr would be None. 
Then it pops up exception in pymilvus/milvus/client/prepare.py 
 @classmethod
    def search_requests_with_expr(cls, collection_name, data, anns_field, param, limit, expr, partition_names=None, output_fields=None, **kwargs):
        ....
    request.dsl = expr        # when try to assign None to request.dsl

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus/pull/548

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus/pull/559

**Comment by yanliang567** [comment]
verify in build today. close
