### ISSUE TITLE
Add a FAQ for "Segmentation fault" on some python client

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#5391]
**Please state your issue using the following template and, most importantly, in English.**
Lot of users encounter a problem when connect milvus server with pymilvus. For some cases, they use pymilvus in a docker container which low version of grpc libraries. Unmatched grpc version between server and client may cause "Segmentation fault" error.

**Location of incorrect documentation**
https://milvus.io/docs/v1.1.0/operational_faq.md

**Suggested fix for documentation**

Q: How can I do if pymilvus return "Segmentation fault" error?
A: 
Milvus use a customized grpc derived from official project in Dec,2019. It cannot be compatible with the grpcio lib which version is larger than 1.37.0.
To avoid this error, install compatible grpcio lib on your client:
     pip install grpcio==1.37.0
     pip install grpcio-tools==1.37.0

**Comment by TTheisen** [comment]
This note saved me hours of headache!

**Comment by shengjun1985** [comment]
The document is added.
Thanks all.
