### ISSUE TITLE
No exception is thrown when creating a collection with empty dataframe

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5404]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
    def test_collection_created_by_invalid_dataframe(self, get_invalid_df):
        self._connect()
        c_name = cf.gen_unique_str(prefix)
        data = pd.DataFrame()
        co, _ = self.collection.collection_init(name=c_name, schema=None, data=data)
        log.debug(co.schema)
```
Expected raise exception
Actually, no exception is thrown and the collection schema is:
```
{"auto_id": true, "description": "", "fields": []}
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
  pymilvus-orm master

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/145  This pr incidentally solves this problem.
