### ISSUE TITLE
The collection should not be created when the data types of different dataframe rows are inconsistent

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5405]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
test create and insert by DataFrame
df like this:
```
    A    B           C
0  1   2.0   [0.1, 0.2]
1  2   3.0           4
```
```
    def test_collection_created_by_invalid_dataframe(self, get_invalid_df):
        self._connect()
        c_name = cf.gen_unique_str(prefix)
        mix_data = [(1, 2., [0.1, 0.2]), (2, 3., 4)]
        df = pd.DataFrame(data=mix_data, columns=list("ABC"))
        log.info(get_invalid_df)
        ex, _ = self.collection.collection_init(name=c_name, schema=None, data=get_invalid_df)
        log.debug(ex.name)
        log.debug(self.utility.list_collections()[0])
```
The case result:
```
[2021-05-25 15:28:13,537 - DEBUG - refactor_test]: [] (test_collection.py:759)
[2021-05-25 15:28:13,548 - ERROR - refactor_test]: [Collection API Exception]<function func_req at 0x7f4a654b50d0>: 'int' object is not iterable (collection.py:19)
[2021-05-25 15:28:13,548 - DEBUG - refactor_test]: 'int' object is not iterable (test_collection.py:761)
[2021-05-25 15:28:13,549 - DEBUG - refactor_test]: ['collection_l4RWfCnq'] (test_collection.py:762)

Addr [172.28.255.155:19530] bulk_insert
Excepted error: 'int' object is not iterable
	{'API start': '2021-05-25 15:28:13.547618', 'RPC start': '2021-05-25 15:28:13.547784', 'Exception': '2021-05-25 15:28:13.548649'}
```

Two problems:
1. Unclear exception information
`'int' object is not iterable`
2. The collection created but no collection object returned
 pymilvus-orm.Collection() return an exception not a collection object, user need to re-create object with dup name???

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus-orm master

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/147
