### ISSUE TITLE
No exception is thrown when creating a collection with unknown data type

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5407]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Create a collection with DataType.UNKNOWN
```
    def test_collection_with_unknown_type(self):
        """
        target: test collection with unknown type
        method: create with DataType.UNKNOWN
        expected: raise exception
        """
        self._connect()
        c_name = cf.gen_unique_str(prefix)
        unknown_field = FieldSchema("unknown", DataType.UNKNOWN)
        fields = [unknown_field, cf.gen_float_vec_field()]
        schema = cf.gen_collection_schema(fields=fields)
        c, _ = self.collection.collection_init(c_name, schema=schema)
        log.error(c.schema)
```
Expected raise exception, but collection created successfully. I don't know what data to insert will successfully
```
{"auto_id": true, "description": "", "fields": [{"name": "unknown", "description": "", "type": 999}, {"name": "float_vector", "description": "", "type": 101, "params": {"dim": 128}}]} (test_collection.py:321)
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus-orm master

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/140/files
