### ISSUE TITLE
BaseException occurs when searching the collection more than once

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#5419]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
BaseException occurs when searching the collection more than once:

ERROR    milvus.client.grpc_handler:grpc_handler.py:56 Error: <BaseException: (code=1, message=[UnexpectedError] [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: 'N'

**Steps/Code to reproduce behavior**
Steps:
1 create the connection and collection

2 search for the first time, suceess
        nq = 2
        limit = 1
        vectors = [[random.random() for _ in range(default_dim)] for _ in range(nq)]
        res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
        log.info("test_search_param_invalid_value: The number of searched query is: %s" % len(res))

3 search for the second time, fail with exception
        res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
        log.info("test_search_param_invalid_value: The number of searched query is: %s" % len(res))

Code for reproduce：

from pymilvus_orm import CollectionSchema, FieldSchema
from pymilvus_orm import Collection
from pymilvus_orm import connections
from pymilvus_orm.types import DataType
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primaty=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=128)
schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
connections.create_connection()
import numpy as np
collection = Collection("test_collection1", schema=schema)
dim = 128
nb = 10
nq = 2
limit = 1
import random
default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
collection.load()
res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")

**Expected behavior**
search without exceptions

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
milvus master latest

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by DragonDriver** [comment]
please provide detailed test code

**Comment by binbinlv** [comment]
> please provide detailed test code

Updated.

**Comment by DragonDriver** [comment]
It is a bug of pymilvus 2.0, I will fix it as soon as possible.

**Comment by binbinlv** [comment]
> It is a bug of pymilvus 2.0, I will fix it as soon as possible.

OK, thanks very much.

**Comment by DragonDriver** [comment]
ptal @binbinlv

**Comment by binbinlv** [comment]
> ptal @binbinlv

it has been fixed now, thanks.

**Comment by binbinlv** [comment]
Verified, it has been fixed, so close it.
