### ISSUE TITLE
Insert list-like data with numpy.ndarray raise an exception

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5421]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
test case:
schema fields: [ int64 field, float field, float_vec field ]
```
    def test_collection_schema_insert_data(self):
        self._connect()
        # nb = ct.default_nb
        nb = 2
        collection = self._collection()
        assert_default_collection(collection)
        data = cf.gen_default_list_data(nb)
        log.debug(data)
        self.collection.insert(data=data)
        assert collection.num_entities == nb
```
1. insert with list-like data like this:
```
[array([0, 1]), array([0., 1.], dtype=float32), 2d float-vec...] (test_collection.py:892)
```
2. raise an exception
```
 The truth value of an array with more than one element is ambiguous. Use a.any() or a.all() (collection.py:19)

Addr [172.28.255.155:19530] bulk_insert
Excepted error: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
	{'API start': '2021-05-26 11:40:39.631333', 'RPC start': '2021-05-26 11:40:39.631997', 'Exception': '2021-05-26 11:40:39.636068'}
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus-orm master

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
We do not support ndarray at the moment.

**Comment by xiaocai2333** [comment]
We do not support ndarray at the moment.

**Comment by ThreadDao** [comment]
I think this exception message is hard to understand for users.
```
Addr [172.28.255.155:19530] bulk_insert
Excepted error: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
	{'API start': '2021-06-04 11:00:53.173435', 'RPC start': '2021-06-04 11:00:53.174107', 'Exception': '2021-06-04 11:00:53.178437'}
```

**Comment by xiaocai2333** [comment]
Currently does not support numpy.ndarray.
https://github.com/milvus-io/pymilvus-orm/pull/150
