### ISSUE TITLE
"Milvus server is going to shutdown" after starting service without any error logs or coredump

### ISSUE THREAD

**Issue by innerNULL** [milvus-io/milvus#5433]
Hi, here's an strange problem,

I start milvus service on bare mental with './start_server.sh' script, and the following is what I got:
![image](https://user-images.githubusercontent.com/10429190/119631009-125aed80-be42-11eb-88af-e4bd49c5493e.png)

The program didn't crash and I got nothing in error log, not any core file:
![image](https://user-images.githubusercontent.com/10429190/119631275-4f26e480-be42-11eb-920b-f5155bfdacf7.png)

Here are some info maybe helpful:
* Although I start milvus in standalone, I do not use sqlite but mysql to save meta-data, but It seems there is nothing wrong about mysql connection
* I'm not starting with an empty milvus data path but let the `storage.path` pointing an existed no-empty milvus data path which is the backup of another milvus service.
* Similar with above point, the target mysql database is not empty, I reuse the mysql database from another milvus service's backup.

So If there any potential reasons? Or how can I get some clue about this problem?

Thanks

**Comment by yhmo** [comment]
Any content in the xxx.info.log?

**Comment by innerNULL** [comment]
> Any content in the xxx.info.log?

@yhmo yep, 
![image](https://user-images.githubusercontent.com/10429190/119636308-176e6b80-be47-11eb-8226-648e92fc2163.png)
...
![image](https://user-images.githubusercontent.com/10429190/119636399-2ce39580-be47-11eb-8c50-7e8e1f4926ee.png)
 But seems nothing about error ?

**Comment by yhmo** [comment]
The info.log print out the crash call stack, it crashed during initializing the mysql connection. From the call stack, there is text lile "mysqlpp", this is a third-party library for connecting with mysql server, milvus meta component use this library to interact with mysql. It may be caused by cracked mysql database.

**Comment by innerNULL** [comment]
> mysqlpp

Thanks~I'll have a check
