### ISSUE TITLE
create/drop index specify segments

### ISSUE THREAD

**Issue by WordlessToContinue** [milvus-io/milvus#5436]
**Please state your issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**

create a collection , then build index, it generate some segments after constant addition and deletion. some segments has very few vectors。 then I want to merge and rebuild the index these segments, I must to call drop_index() and create_index(), it will rebuild  index  all segments，it take very long time。

**Describe the solution you'd like**
drop_index() can specify segments , then drop the specify segments' indexes
create_index() create indexes for these segments that do not have indexes

**Describe alternatives you've considered**
create_index() can specify segments , then can merge the segments and rebuild index

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by shengjun1985** [comment]
You can call the IF Compact().
Then those segments with more than 10% deletion will be rebuilt their index.

**Comment by shengjun1985** [comment]
Answered.
