### ISSUE TITLE
Add API to calculate distance for input vectors

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#5443]
**Please state your issue using the following template and, most importantly, in English.**
New requirement from Slack community.
Something like `CalcDistance(List<Float> vector, List<List<Float>> vectors)`, calculate distance for input vectors

**Is your feature request related to a problem? Please describe.**
Having this api would have helped user in delegating all distance and nearest neighbours queries to Milvus, instead of writing other script again. 

**Describe the solution you'd like**
- `Enum MetricType = {L2 = 1, IP = 2, HAMMIN=3, TANIMOTO=4}`

- `List<List<Float>> CalcDistance(List<List<Float>> vectors_1, List<List<Float>> vectors_2, MetricType metric)`
Both vector_1 and vector_2 are vector array. This api calculate distance between two vector arrays.
For example:
vectors_1 = [v1, v2, v3]
vectors_2 = [w1, w2]
The result will be:
[
  [dist_v1_w1, dist_v1_w2],
  [dist_v2_w1, dist_v2_w2],
  [dist_v3_w1, dist_v3_w2],
]

- `List<List<Float>> CalcDistance(List<List<Float>> vectors_1, String collection_name, List<List<Int64>> vectors_2, MetricType metric)`
The api calculate distance between vectors_1 and vectors_2 retrieved from milvus
vectors_2 is id array
collection_name is which collection the vectors_2 come from.

- `List<List<Float>> CalcDistance(String collection_1, List<List<Int64>> vectors_1, String collection_2, List<List<Int64>> vectors_2, MetricType metric)`
The api calculate distance between vectors_1 and vectors_2 both retrieved from milvus
vectors_1 is id array
collection_1 is which collection the vectors_1 come from.
vectors_2 is id array
collection_2 is which collection the vectors_2 come from.

**Comment by keotic** [comment]
Same feature but with vectors ids would be also useful

**Comment by yhmo** [comment]
> Same feature but with vectors ids would be also useful

Sure. I have modified the discription.

**Comment by jeet129** [comment]
Is this feature expected to be released in 2.0?

**Comment by yhmo** [comment]
> Is this feature expected to be released in 2.0?

We plan to release a Release Candidate version of v2.0 at the end of this month. This feature is not in the first release. But it could be planned in the following iteration.

**Comment by yhmo** [comment]
Proto definition:
```
## reused structure
message KeyValuePair {
    string key = 1;
    string value = 2;
}

message VectorField {
  int64 dim = 1;
  oneof data {
    FloatArray float_vector = 2;
    bytes binary_vector = 3;
  }
}

## new structure
message CalcDistanceRequest {
  common.MsgBase base = 1;
  schema.VectorField op_left = 2; // vectors
  schema.VectorField op_right = 3; // vectors
  repeated common.KeyValuePair params = 4; // "metric":"L2"/"IP"/"HAMMIN"/"TANIMOTO"
}

message CalcDistanceResults {
  common.Status status = 1;
  // num(op_left)*num(op_right) distance values
  oneof array {
    	IntArray int_dist = 2;
	FloatArray float_dist = 3;
  }
}

## new api
service MilvusService {
  ......
  rpc CalcDistance(CalcDistanceRequest) returns (CalcDistanceResults) {}
}

```

**Comment by yhmo** [comment]
Python sdk definition:
```
    def calc_distance(self, vectors_left, vectors_right, params=None, timeout=None, **kwargs):
        """
        Calculate distance between two vector arrays.

        :param vectors_left: The vectors on the left of operator.
        :type  vectors_left: 2-d array

        :param vectors_left: The vectors on the right of operator.
        :type  vectors_left: 2-d array

        :param params: parameters, currently only support "metric_type"
        :type  params: dict
            There are examples of supported metric_type:
                `{"metric_type": "L2"}`
                `{"metric_type": "IP"}`
                `{"metric_type": "HAMMIN"}`
                `{"metric_type": "TANIMOTO"}`
        """
```

**Comment by keotic** [comment]
@yhmo Great, Thanks
Are you planning to add a definition with ids as well?
Something like:
def calc_distance(self, vectors_ids_left, vectors_ids_right, params=None, timeout=None, **kwargs):

**Comment by yhmo** [comment]
> @yhmo Great, Thanks
> Are you planning to add a definition with ids as well?
> Something like:
> def calc_distance(self, vectors_ids_left, vectors_ids_right, params=None, timeout=None, **kwargs):


In v2.0 there is an api query() to retrieve entity data:
```
 def query(self, collection_name, expr, output_fields=None, partition_names=None, timeout=None):
        """
        Query with a set of criteria, and results in a list of records that match the query exactly.

        :param collection_name: Name of the collection to retrieve entities from
        :type  collection_name: str

        :param expr: The query expression
        :type  expr: str

        :param output_fields: A list of fields to return
        :type  output_fields: list[str]

        :param partition_names: Name of partitions that contain entities
        :type  partition_names: list[str]

        :param timeout: An optional duration of time in seconds to allow for the RPC. When timeout
                        is set to None, client waits until server response or error occur
        :type  timeout: float

        :return: A list that contains all results
        :rtype: list

        :raises:
            RpcError: If gRPC encounter an error
            ParamError: If parameters are invalid
            BaseException: If the return result from server is not ok
        """
```

So we think this can be done by two steps:
1. use query() to get vector data by ids
2. use calc_distance() to calculate distances

Combine the two steps into one api is a nice-to-have feature, we can plan it in next stage.

**Comment by keotic** [comment]
Thanks, but the idea of calculating distance / or searching by ids to to prevent retrieving the embedding payload on the first call and sending it back again in the second one.
For performance reasons it is better to do it server side.

For example, if we have a list of 10K vectors ids of dim 2048, and we want to get the distance between them, we first need to fetch 10K vectors (payload size =  10K * 2048) and then send it back for the calculation / search ( again delivering payload of 10K * 2048 for search and 20K * 2048 for distance)  we want to avoid the payloads

**Comment by yhmo** [comment]
> Thanks, but the idea of calculating distance / or searching by ids to to prevent retrieving the embedding payload on the first call and sending it back again in the second one.
> For performance reasons it is better to do it server side.
> 
> For example, if we have a list of 10K vectors ids of dim 2048, and we want to get the distance between them, we first need to fetch 10K vectors (payload size = 10K * 2048) and then send it back for the calculation / search ( again delivering payload of 10K * 2048 for search and 20K * 2048 for distance) we want to avoid the payloads

So, your common usage is to calculate distance between large amount of ids?

**Comment by yhmo** [comment]
I have redefined the api to support calculate distance by ids.

**Comment by keotic** [comment]
We have 2 usages involving large amount of vectors:
1. Ann search ( we have the ids, don’t want to retrieve and send the vectors payload)
2. Calculate distances between groups of known ids

**Comment by jeet129** [comment]
Also, I am assuming its implicit that these APIs will be available for all the clients for ex. java sdk.

**Comment by yhmo** [comment]
The first release of v2.0 only support python sdk. Other sdk(java/go) could not catch the release date,  and planned in next stage.

**Comment by xiaofan-luan** [comment]
one question
1) for python orm api, where we put this CalcDistance API?
collection.calc_distance(self, ids_left, ids_right, params=None, timeout=None, **kwargs) make sense to me.

calc_distance(self, vectors_left, vectors_right, params=None, timeout=None, **kwargs) should not be put into collection api list, maybe util?

**Comment by jeet129** [comment]
@yhmo, any estimated timelines of api support in java sdk?

**Comment by yhmo** [comment]
> @yhmo, any estimated timelines of api support in java sdk?

I think the java sdk will begin after the v2.0 RC version released, personally I estimated it require about one month to develop/test the java sdk.

**Comment by yanliang567** [comment]
@czs007 could you please generate the api docs first? After that please assign this issue to @binbinlv  to develop tests for the new api
