### ISSUE TITLE
Error when inserting None data

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5445]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Insert with None data
```
    def test_insert_none(self):
        collection = self._collection()
        ex, _ = collection.insert(data=None)
```
```
datas = None

    def parse_fields_from_data(datas):
        if isinstance(datas, pandas.DataFrame):
            return parse_fields_from_dataframe(datas)
        fields = []
>       for d in datas:
E       TypeError: 'NoneType' object is not iterable

../../../../../.virtualenvs/milvus/lib/python3.6/site-packages/pymilvus_orm/schema.py:227: TypeError
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus-orm master

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/141
