### ISSUE TITLE
Search result is wrong after deletion of a partition

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#5461]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Search result is wrong after deletion of a partition: the entity in the deleted partition is still be searched and returned

**Steps/Code to reproduce behavior**
Steps:
1 create connection and collection with 2 partitions 

2 Insert 500 entities in each partition
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 500}, {"name": "search_partition", "description": "", "num_entities": 500}]

3 Search (limit 1000) -- here return 1000 entities
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> len(res[0])
1000

4 delete a partition
>>> collection.drop_partition(par[1].name)
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 500}]

5 Search (limit 1000) -- here still return 1000 entities which should be 500 entities?
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> len(res[0])
1000

Code:

from pymilvus_orm import CollectionSchema, FieldSchema
from pymilvus_orm import Collection
from pymilvus_orm import connections
from pymilvus_orm.types import DataType
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=128)
schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
connections.create_connection()
import numpy as np
collection = Collection("test_search_collection3", schema=schema)
collection.create_partition(partition_name="search_partition", description="search partition")
par = collection.partitions
dim = 128
nb = 500
nq = 1
limit = 1000
import random
default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors],  par[0].name)
collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors],  par[1].name)
collection.load()
collection.num_entities
collection.partitions
res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
len(res[0])
collection.drop_partition(par[1].name)
collection.partitions
res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
len(res[0])

**Expected behavior**
The entities in the deleted partitions should not be searched

**Method of installation**
- [ ] Docker/cpu

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)
   CPU

- Milvus version (master or released version)
   milvus master

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by DragonDriver** [comment]
It's a little confusing, but you should call `collection.release()` and `collection.load()` after `collection.drop_partition(par[1].name)`. Or you can call `par[1].release()` before `collection.drop_partition(par[1].name)`.

**Comment by binbinlv** [comment]
OK, cool, thanks.

**Comment by binbinlv** [comment]
Reopen this issue: it fails at pymilvus version (2.0a1.dev8)

code:

from pymilvus_orm import CollectionSchema, FieldSchema
from pymilvus_orm import Collection
from pymilvus_orm import connections
from pymilvus_orm.types import DataType
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primaty=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=128)
schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
connections.create_connection(host="172.20.255.155", port="19530")
import numpy as np
collection = Collection("test_search_collection_binbin_2", schema=schema)
collection.create_partition(partition_name="search_partition_1", description="search partition")
par = collection.partitions
dim = 128
nb = 500
nq = 1
limit = 1000
import random
default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors],  par[0].name)
collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors],  par[1].name)
collection.load()

>>> collection.num_entities
1000
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 500}, {"name": "search_partition_1", "description": "", "num_entities": 500}]
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> len(res[0])
1000
>>> collection.drop_partition(par[1].name)
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 500}]
>>> res1 = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> len(res1[0])
1000
>>> collection.release()
>>> collection.load()
>>> res1 = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> len(res1[0])
1000
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 500}]

**Comment by binbinlv** [comment]
It is good in the latest version of pymilvus-orm:
Name: pymilvus
Version: 2.0a1.dev22
Name: pymilvus-orm
Version: 2.0a1.dev15

**Comment by czs007** [comment]
> It's a little confusing, but you should call `collection.release()` and `collection.load()` after `collection.drop_partition(par[1].name)`. Or you can call `par[1].release()` before `collection.drop_partition(par[1].name)`.

drop should call relase by default in the server side.

**Comment by DragonDriver** [comment]
This issue should have been solved by the newest version. Please re-check this.

**Comment by binbinlv** [comment]
Re-tested in the following version, if add "collection.release()", it is good now. But if "drop should call release by default in the server side" just as zhenshan said, it still could not call release by default. 

So whether is it a point should be improved?

Results:
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 500}, {"name": "search_partition_1", "description": "", "num_entities": 500}]
>>> collection.load()
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> len(res[0])
>>> collection.drop_partition(par[1].name)
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 500}]
>>> res1 = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> len(res1[0])
1000
>>> collection.release()
>>> collection.load()
>>> res1 = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> len(res1[0])
500

**Comment by czs007** [comment]
@neza2017  QueryCoord should be notified to execute ReleasePartition when rootCoord DropPartition
