### ISSUE TITLE
NSG build failed using GPU-edition if set gpu_enable false

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#547]
**Describe the bug**
Build failed on dataset sift-1m, if set  enable: false

**Steps/Code to reproduce behavior**

**Expected behavior**
It will use CPU to build, if enable set false

**Environment details**
0.6.0-GPU-edition

**Screenshots**

**Additional context**

**Comment by fishpenguin** [comment]
Already fixed by commit [1b6d90a](https://github.com/milvus-io/milvus/commit/fd304cf4b43344dfe3d0a161b3e79915d81ad2fb)
