### ISSUE TITLE
Pymilvus crushed !!!!!!!

### ISSUE THREAD

**Issue by Chisdo** [milvus-io/milvus#5477]
1. My solution: 
It took me tons of hours to fix this bug by myself !!! 
set up:
grpcio==1.37.0
grpcio-tools==1.37.0

2. Problem:
When,
grpcio==1.38.0
grpcio-tools==1.38.0,
from milvus import Milvus
Milvus(IP, PORT) function would crush.

3. My suggestion:
Plz add restriction for grpcio and grpcio-tools, 

4. Problem reproduces steps:
- touch Dockerfile
[add content: 
FROM python:3.8-slim
RUN pip install pymilvus]
- docker-compose build -f Dockerfile -t test:v1 .
- docker run -it test:v1
- [in Python compiler]
- from milvus import Milvus
- milvus_conn = Milvus(ip_to_server, port_to_server)
- call anything like: milvus_conn.list_collections()
- 
5. both Pymilvus==1.1.0 or 1.0.0 or 1.0.1 would crush if grpcio==1.38.0

**Comment by yhmo** [comment]
Link to #5377 

The grpcio release its new version 1.38.0 on May 21, 2021. This version is incompatible to milvus grpc version.
Milvus grpc is forked from grpc official project in Dec, 2019. https://github.com/milvus-io/grpc-milvus
It is customized for some special reason. It seems this version can compatible grpcio from 1.22.0 to 1.37.0.

A fix has been submitted on pymilvus's 1.x branch: https://github.com/milvus-io/pymilvus/pull/522
And we prepare to ad an item in FAQ about this: https://github.com/milvus-io/milvus/issues/5391

**Comment by Chisdo** [comment]
ahhhh... I should notice the previous issue earlier. Thx for your help and apology for my rude.
