### ISSUE TITLE
Segmentation fault (core dumped) when running example.py

### ISSUE THREAD

**Issue by willdx99j3** [milvus-io/milvus#5486]
Hi, team,

When I tried to install as the tutorial's instructions, for both GPU & CPU version:
https://milvus.io/cn/docs/v1.0.0/milvus_docker-cpu.md
https://milvus.io/cn/docs/v1.0.0/milvus_docker-gpu.md

and install the python sdk:
pip3 install pymilvus==1.0.1

download example code:
wget https://raw.githubusercontent.com/milvus-io/pymilvus/v1.0.1/examples/example.py

and run: 
python3 example.py

it returns Segmentation fault (core dumped) .

I have tried at different cloud server, with GPU and without GPU, could you please help to check?

Thanks!

**Comment by czs007** [comment]
please refer to this conversation  https://github.com/milvus-io/pymilvus/pull/522
Hope it can help you solve the problem.

**Comment by yhmo** [comment]
Link to #5377

The grpcio release its new version 1.38.0 on May 21, 2021. This version is incompatible to milvus grpc version.
Milvus grpc is forked from grpc official project in Dec, 2019. https://github.com/milvus-io/grpc-milvus
It is customized for some special reason. It seems this version can compatible grpcio from 1.22.0 to 1.37.0.

A fix has been submitted on pymilvus's 1.x branch: milvus-io/pymilvus#522
And we prepare to add an item in FAQ about this: #5391

**Comment by ModMorph** [comment]
Can confirm that after I installed grpcio==1.37.0 and grpcio-tools==1.37.0 to the conda env I was using, the SIGSEGV went away for me when I was just trying to create a collection.  Thanks @yhmo!  "Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)"

**Comment by shengjun1985** [comment]
Solved.
