### ISSUE TITLE
[BUG] Never got a response from a request sent to flask + gunicorn

### ISSUE THREAD

**Issue by fauzantaufik** [milvus-io/milvus#5489]
**Describe the bug**
Running flask+gunicorn+pymilvus in docker. the whole app is running but when trying to send request it seems request never give a response.

the problem doesnt happen when running flask+pymilvus only.

it's keep loading to receive response

![image](https://user-images.githubusercontent.com/33479894/120053028-4147ae00-c052-11eb-9520-66c9a2c90da4.png)

Flask+gunicorn and pymilvus in running :
![image](https://user-images.githubusercontent.com/33479894/120053070-70f6b600-c052-11eb-831a-2e656269c101.png)

![image](https://user-images.githubusercontent.com/33479894/120053079-7bb14b00-c052-11eb-80c4-8ed9f60fbc55.png)

**Steps/Code to reproduce behavior**
I have tried gunicorn with 1 workers, then 3 workers
I also have tried gunicorn with class_type 'sync' and 'eventlet'

**Expected behavior**
Flask response the request

**Environment details**

- Running in docker
- Container OS : Debian GNU/Linux
- HOST Hardware/Softward conditions (Windows, Processor	Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, 2592 Mhz, 6 Core(s), 12 Logical Processor(s)
 GPU, 64MB)
- Method of installation from Docker
- image name : milvusdb/milvus:1.1.0-cpu-d050721-5e559c
- Milvus version (v1.1.0)
- Using default milvus server_config.yaml

**Screenshots**
directory and docker-compose script

![image](https://user-images.githubusercontent.com/33479894/120053298-9afca800-c053-11eb-9e75-332683fd1378.png)

**Additional context**
The application is ML application using distill-bert from sentence-transformer

**Comment by XuanYang-cn** [comment]
link to the same issue in pymilvus https://github.com/milvus-io/pymilvus/issues/532

**Comment by yhmo** [comment]
I could not reproduce it.
With the following steps/script:
1. start a docker container from milvus v1.1.0
2. write a script **server.py** as http server:
```
import random
import numpy as np
from milvus import Milvus
from milvus.client.types import MetricType
from flask import Flask

SERVER_ADDR = "127.0.0.1"
SERVER_PORT = '19530'
COLLECTION_NAME = "TEST"
COLLECTION_DIMENSION = 128
COLLECTION_PARAM = {'collection_name': "",
                    'dimension': COLLECTION_DIMENSION,
                    'index_file_size': 1024,
                    'metric_type':MetricType.L2}

MILVUS = Milvus(host=SERVER_ADDR, port=SERVER_PORT)

app = Flask(__name__)

def gen_vec_list(nb, seed=np.random.RandomState(1234)):
    xb = seed.rand(nb, COLLECTION_DIMENSION).astype("float32")
    vec_list = xb.tolist()
    return vec_list

def create_collection(name = COLLECTION_NAME):
    param = COLLECTION_PARAM
    param['collection_name'] = name
    status = MILVUS.create_collection(param)
    print("create", name)

def drop_collection(name = COLLECTION_NAME):
    status = MILVUS.drop_collection(collection_name=name)
    print("drop", name)

def insert(name = COLLECTION_NAME):
    batch = 100
    vectors = gen_vec_list(batch)
    status, ids = MILVUS.insert(collection_name=name, records=vectors)
    MILVUS.flush(collection_name_array=[name])
    print("insert", len(ids))

def search():
    print("search begin")
    q_records = [[random.random() for _ in range(COLLECTION_DIMENSION)] for _ in range(1)]
    status, results = MILVUS.search(collection_name=COLLECTION_NAME, query_records=q_records, top_k=10,
                                    params={})
    print("results", results)
    return "search: " + str(status) + str(results)

@app.route('/')
def index():
    drop_collection()
    create_collection()
    insert()
    return search()

def main():
    app.run(debug=True)

if __name__ == '__main__':
    main()
```
3. start the http server by flask:
`python3 server.py`

```
* Serving Flask app '000' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 126-078-929
```

4. write a script to sent request to the http server:
```
import requests
res = requests.get("http://127.0.0.1:5000")
print(str(res.status_code), res.text)
```
**The result returned immediately and correctly.**

5. stop the flask http server,  start http server by gunicorn:
`gunicorn server:app`

```
[2021-05-31 11:36:27 +0800] [9671] [INFO] Starting gunicorn 20.1.0
[2021-05-31 11:36:27 +0800] [9671] [INFO] Listening at: http://127.0.0.1:8000 (9671)
[2021-05-31 11:36:27 +0800] [9671] [INFO] Using worker: sync
[2021-05-31 11:36:27 +0800] [9674] [INFO] Booting worker with pid: 9674
```

6. write a script to sent request to the http server:
```
import requests
res = requests.get("http://127.0.0.1:8000")
print(str(res.status_code), res.text)
```
**The result returned immediately and correctly.**

**Comment by fauzantaufik** [comment]
Thank you for replying and trying to reproduce this

I think this is not milvus issue anymore, I found the problem occur when loading sentence transformer model with gunicorn, it never finish to load the model

here is the code

![image](https://user-images.githubusercontent.com/33479894/120162748-e6b17c00-c222-11eb-90ca-38ce497744ab.png)

**Comment by yhmo** [comment]
> Thank you for replying and trying to reproduce this
> 
> I think this is not milvus issue anymore, I found the problem occur when loading sentence transformer model with gunicorn, it never finish to load the model
> 
> here is the code
> 
> ![image](https://user-images.githubusercontent.com/33479894/120162748-e6b17c00-c222-11eb-90ca-38ce497744ab.png)

Not sure how the model works. You can try add more log to help investigation.

**Comment by fauzantaufik** [comment]
the problem is multiple load model when initialize application with gunicorn, my mistake

thanks for all your help
