### ISSUE TITLE
The exception of insert with invalid field name DataFrame is not clear

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5499]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
1. create a collection with fields ["int64", "float", "float_vector]
2. insert with DataFrame with invalid column name (int64 -> invalid)
```
[
    "12-s",
    "12 s",
    "(mn)",
    "中文",
    "%$#",
    "a".join("a" for i in range(256))]
```
3. The exception is:
```
[2021-05-31 10:52:43,175 - ERROR - refactor_test]: [Collection API Exception]<function func_req at 0x7ffa399f2f28>: 'int64' (collection.py:19)
[2021-05-31 10:52:43,175 - ERROR - refactor_test]: 'int64' (test_insert.py:125)
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus-orm master

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
Please paste the test code.

**Comment by ThreadDao** [comment]
```
    def test_insert_invalid_field_name_dataframe(self, get_invalid_field_name):
        self._collection()
        df = cf.gen_default_dataframe_data(10)
        df.rename(columns={ct.default_int64_field_name: get_invalid_field_name}, inplace=True)
        log.info(df)
        ex, _ = self.collection.insert(data=df)
        log.error(str(ex))
```

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/147  This pr also checks whether the column names are consistent.
