### ISSUE TITLE
Return vector data by ID

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#550]
**Is your feature request related to a problem? Please describe.**
Some customer want to get vector data by its ID.

**Describe the solution you'd like**
For user-defined id,  iterate each file to find out the vector.
For internal-defined id, quickly find out a file that contains this id, and return the vector.

**Comment by JinHai-CN** [comment]
@yhmo Please connect it with the PR.

**Comment by yhmo** [comment]
already implemented in master branch
