### ISSUE TITLE
When the entity is missing a field value, it should not be inserted successfully

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5505]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
1. insert 10 entities, no.10 entity is missing a int64 field value
```
    def test_insert_value_less(self):
        self._collection()
        nb = 10
        int_values = [i for i in range(nb-1)]
        float_values = [np.float32(i) for i in range(nb)]
        float_vec_values = cf.gen_vectors(nb, ct.default_dim)
        data = [int_values, float_values, float_vec_values]
        ids, _ = self.collection.insert(data=data)
        log.info(ids)
        log.info(len(ids))
```
Now, 9 entities inserted successfully. but we expect to raise exceptions and no insert.
```
[100%][2021-05-31 14:22:04,734 - INFO - refactor_test]: [425002509439028275, 425002509439028276, 425002509439028277, 425002509439028278, 425002509439028279, 425002509439028280, 425002509439028281, 425002509439028282, 425002509439028283] (test_insert.py:273)
[2021-05-31 14:22:04,735 - INFO - refactor_test]: 9 (test_insert.py:274)
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus-orm master

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/141
