### ISSUE TITLE
An out-of-range exception is thrown when inserting a entity with missing float-vector field value.

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5508]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
insert 10 entities, no.10 entity is missing the float-vector field value
```
    def test_insert_vector_value_less(self):
        self._collection()
        nb = 10
        int_values = [i for i in range(nb)]
        float_values = [np.float32(i) for i in range(nb)]
        float_vec_values = cf.gen_vectors(nb-1, ct.default_dim)
        data = [int_values, float_values, float_vec_values]
        ex, _ = self.collection.insert(data=data)
        log.info(str(ex))
```
```
[2021-05-31 14:31:00,039 - ERROR - refactor_test]: [Collection API Exception]<function func_req at 0x7fc7eedd18c8>: list index out of range (collection.py:19)
[2021-05-31 14:31:00,040 - INFO - refactor_test]: list index out of range (test_insert.py:290)

Addr [172.28.255.155:19530] bulk_insert
Excepted error: list index out of range
	{'API start': '2021-05-31 14:31:00.034280', 'RPC start': '2021-05-31 14:31:00.035107', 'Exception': '2021-05-31 14:31:00.039433'}
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus-orm master

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/141

**Comment by yanliang567** [comment]
@ThreadDao  what about if missing a non_vector_float_field value?
