### ISSUE TITLE
Assert message is not user friendly when searching without connection

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#5539]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Assert message does not make sense when searching after removing connection

'NoneType' object has no attribute 'search_with_expression'

And in the former pymilvus-orm version, it reports assert with "no connnection ..."

**Steps/Code to reproduce behavior**
1 create connection and collection

2 search normally

3 remove connection

4 search: assert with "'NoneType' object has no attribute 'search_with_expression'"

**Expected behavior**
something like "no connection is..."

**Method of installation**
- [ ] Docker/cpu

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
master
pymilvus and pymilvus-orm: 2.0a1.dev8

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/155

**Comment by binbinlv** [comment]
Verified in the following version, closed this issue.
Name: pymilvus
Version: 2.0a1.dev34
Name: pymilvus-orm
Version: 2.0a1.dev22
