### ISSUE TITLE
Improve cpu usage of building IVF index for binary vectors

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#5543]
**Please state your issue using the following template and, most importantly, in English.**
Improve cpu usage of building IVF index for binary vectors

**Describe the bug**
50M binary vectors, index type = IVFFLAT, nlist=4096, index_file_size = 4GB, during building index, the cpu usage rate is 30%~40% on my 12 cores machine.

**Comment by hadim** [comment]
Not sure this is related but just in case: https://github.com/facebookresearch/faiss/issues/1617

**Comment by shengjun1985** [comment]
Thank you very much.
We've noticed that commit. In fact, I also fixed a bug in that commit. : )

**Comment by yhmo** [comment]
Depend on faiss version. Currently we only fix critical bugs for v1.x, no more features, including third-party library upgrading. Inactive and close.

**Comment by hadim** [comment]
What about Milvus 2.x?
