### ISSUE TITLE
index_file_size is invalid

### ISSUE THREAD

**Issue by xuewenzhang** [milvus-io/milvus#5553]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
When I insert the vector into the collection, mivlus cannot divide the data segment according to the size of index_file_size.

**Steps/Code to reproduce behavior**
Insert the vector into the collection, and use get_collection_stats to view the detailed collection information, and find an exception.

**Expected behavior**
It is expected that the vector will be divided into data segments with index_file_size as a parameter. If index_file_size=1024, each data segment is 1024M in size

**Method of installation**
Follow the official website link to install milvus using docker：https://milvus.io/cn/docs/v1.1.0/milvus_docker-cpu.md
1 sudo docker pull milvusdb/milvus:1.1.0-cpu-d050721-5e559c
2 mkdir -p /home/$USER/milvus/conf
cd /home/$USER/milvus/conf
wget https://raw.githubusercontent.com/milvus-io/milvus/v1.1.0/core/conf/demo/server_config.yaml
3 sudo docker run -d --name milvus_cpu_1.1.0 \
-p 19530:19530 \
-p 19121:19121 \
-v /home/$USER/milvus/db:/var/lib/milvus/db \
-v /home/$USER/milvus/conf:/var/lib/milvus/conf \
-v /home/$USER/milvus/logs:/var/lib/milvus/logs \
-v /home/$USER/milvus/wal:/var/lib/milvus/wal \
milvusdb/milvus:1.1.0-cpu-d050721-5e559c

4 sudo docker ps

**Environment details**
centos7.3 

- Milvus version (master or released version)
1.1.0

**Configuration file**
Default configuration file

**Screenshots**
(Status(code=0, message='Success'),
 {'partitions': [{'row_count': 482000,
    'segments': [{'data_size': 878000408,
      'index_name': 'IDMAP',
      'name': '1622441710305968000',
      'row_count': 427043},
     {'data_size': 71073864,
      'index_name': 'IDMAP',
      'name': '1622441720387230000',
      'row_count': 34569},
     {'data_size': 35609920,
      'index_name': 'IDMAP',
      'name': '1622441738804265000',
      'row_count': 17320},
     {'data_size': 357744,
      'index_name': 'IDMAP',
      'name': '1622441739804662000',
      'row_count': 174},
     {'data_size': 5950064,
      'index_name': 'IDMAP',
      'name': '1622441739810022000',
      'row_count': 2894}],
    'tag': '_default'},
   {'row_count': 0, 'segments': None, 'tag': 'tag01'}],
  'row_count': 482000})

**Additional context**

**Comment by yhmo** [comment]
Milvus has different merge strategy under different conditions. You can refer this article: https://zhuanlan.zhihu.com/p/148106312
It not always merge segments to be big one, to avoid "write amplify". When you call create_index(), the small segments will be merged into big segments.

**Comment by yhmo** [comment]
Milvus segment merge machinery cannot ensure each segment size is exactly equal to index_file_size.
Inactive and close.
