### ISSUE TITLE
Docker all_in_one deploy version mismatches

### ISSUE THREAD

**Issue by filip-halt** [milvus-io/milvus#5554]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
For the 1.0 branch, the mishards all_in_one.yml uses docker 0.10. 

For the 1.1 branch, the all_in_one docker composer deployment results in a version mismatch of server1.1.0 and Python SDK(1.0.0) in the mishards node. The only change that I made was to use the CPU version without the Nvidia runtime.

**Steps/Code to reproduce behavior**
Run the `make deploy` command from milvus/shards directory

**Expected behavior**
Correct version of milvus for 1.0 and no errors for 1.1

**Method of installation**
- [x] Docker/cpu

**Comment by yhmo** [comment]
Yes, it is a typo.

**Comment by yhmo** [comment]
fixed
