### ISSUE TITLE
I  cant download the datasets with molecular-search-with-milvus example

### ISSUE THREAD

**Issue by lookcat** [milvus-io/milvus#5564]
**Location of incorrect documentation**
https://tutorials.milvus.io/how-to-do-reverse-molecular-search-with-milvus/index.html?index=..%2F..cn#2

**Describe the problems or issues found in the documentation**
Not datasets

**Steps taken to verify documentation is incorrect**
wget https://raw.githubusercontent.com/milvus-io/bootcamp/0.10.0/solutions/mols_search/smiles-data/test_1w.smi

**Comment by shiyu22** [comment]
Hi, you can follow [this Bootcamp](https://github.com/milvus-io/bootcamp/tree/master/solutions/molecular_similarity_search/quick_deploy) for the dataset.

**Comment by lookcat** [comment]
> Hi, you can follow [this Bootcamp](https://github.com/milvus-io/bootcamp/tree/master/solutions/molecular_similarity_search/quick_deploy) for the dataset.



sercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.109.133, ...
正在连接 raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 404 Not Found
2021-06-03 16:47:27 错误 404：Not Found。

it not work with me.

**Comment by shiyu22** [comment]
```bash
wget https://raw.githubusercontent.com/milvus-io/bootcamp/1.0/solutions/mols_search/smiles-data/test_1w.smi
```
You can try to download it with this link.

**Comment by lookcat** [comment]
nice.
