### ISSUE TITLE
No data in the collection after partition insert

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#5582]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
No data in the collection after partition insert 

**Steps/Code to reproduce behavior**
Steps:
1 create connection and collection, successfully
2 create partition, successfully
3 partition insert, successfully without reporting errors
4 partition.num_entities is still 0
>>> partition.insert(data)
[]
>>> partition.num_entities
0
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 0}, {"name": "test_partition", "description": "", "num_entities": 0}]

5 partition.load() or collection.load()
6 partition.num_entities is still 0

>>> partition.load()
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 0}, {"name": "test_partition", "description": "", "num_entities": 0}]
>>> partition.num_entities
0
>>>
>>> collection.load()
>>> partition.num_entities
0
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 0}, {"name": "test_partition", "description": "", "num_entities": 0}]

Code:
from pymilvus_orm import CollectionSchema, FieldSchema
from pymilvus_orm import Collection
from pymilvus_orm import connections
from pymilvus_orm.types import DataType
from pymilvus_orm import Partition
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primaty=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=128)
schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
connections.connect(host="172.18.255.155", port="19530")
import numpy as np
collection = Collection("test_search_collection_binbin_6", schema=schema)
partition = Partition(collection, "test_partition")
nb = 10
dim=128
import random
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
data=[[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors]
partition.insert(data)
partition.num_entities
collection.partitions
partition.load()
partition.num_entities
collection.partitions
collection.load()
partition.num_entities
collection.partitions

**Expected behavior**
partition.num_entities is the number of inserted data after partition insert

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
milvus: master
pymilvus:
Name: pymilvus
Version: 2.0a1.dev8
pymilvus-orm
Name: pymilvus-orm
Version: 2.0a1.dev13

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by binbinlv** [comment]
Collection insert has this issue too on this version:

>>> from pymilvus_orm import CollectionSchema, FieldSchema
>>> from pymilvus_orm import Collection
>>> from pymilvus_orm import connections
>>> from pymilvus_orm.types import DataType
>>> from pymilvus_orm import Partition
>>> int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primaty=True)
>>> float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
>>> float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=128)
>>> schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
>>> connections.connect(host="172.18.255.155", port="19530")
<milvus.client.stub.Milvus object at 0x7f13755ac9e8>
>>>
>>> import numpy as np
>>> collection = Collection("test_search_collection_binbin_one", schema=schema)
>>> dim = 128
>>> nb = 500
>>> nq = 1
>>> limit = 1000
>>> import random
>>> default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
>>> vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 0}]
>>> collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
[]
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 0}]
>>> collection.num_entities
0
>>> collection.load()
>>> collection.num_entities
0
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 0}]
>>> collection.load()
>>> collection.num_entities
0

**Comment by binbinlv** [comment]
Collection insert is good now at the latest version, but the partition search is still bad:
Name: pymilvus
Version: 2.0a1.dev22
Name: pymilvus-orm
Version: 2.0a1.dev15


>>> from pymilvus_orm import CollectionSchema, FieldSchema
>>> from pymilvus_orm import Collection
>>> from pymilvus_orm import connections
>>> from pymilvus_orm.types import DataType
>>> from pymilvus_orm import Partition
>>>
>>> int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primaty=True)
>>> float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
>>> float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=128)
>>> schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
>>> connections.connect(host="172.18.255.155", port="19530")
<pymilvus.client.stub.Milvus object at 0x7fc212406a20>
>>>
>>>
>>> import numpy as np
>>> collection = Collection("test_search_collection_binbin_two",schema=schema)
>>> partition = Partition(collection, "test_partition")
>>> nb = 10
>>> dim=128
>>> import random
>>> vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
>>> data=[[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors]
>>>
>>>
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 0}, {"name": "test_partition", "description": "", "num_entities": 0}]
>>>
>>>
>>> partition.num_entities
0
>>> partition.insert(data)
[425404389226646864, 425404389226646865, 425404389226646866, 425404389226646867, 425404389226646868, 425404389226646869, 425404389226646870, 425404389226646871, 425404389226646872, 425404389226646873]
>>>
>>> partition.num_entities
0
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 10}, {"name": "test_partition", "description": "", "num_entities": 0}]
>>> partition.load()
>>> partition.num_entities
0
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 10}, {"name": "test_partition", "description": "", "num_entities": 0}]

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/152

**Comment by binbinlv** [comment]
Verified in the following version, the issue is fixed, so close it.
Name: pymilvus
Version: 2.0a1.dev27
Name: pymilvus-orm
Version: 2.0a1.dev19

>>> from pymilvus_orm import CollectionSchema, FieldSchema
>>> from pymilvus_orm import Collection
>>> from pymilvus_orm import connections
>>> from pymilvus_orm.types import DataType
>>> from pymilvus_orm import Partition
>>> int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primaty=True)
>>> float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
>>> float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=128)
>>> schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
>>> connections.connect(host="172.22.255.155", port="19530")
<pymilvus.client.stub.Milvus object at 0x7f9a2f0a1f98>
>>> import numpy as np
>>> collection = Collection("test_search_collection_binbin_two",schema=schema)
>>> partition = Partition(collection, "test_partition")
>>> nb = 10
>>> dim=128
>>> import random
>>> vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
>>> data=[[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors]
>>>
>>>
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 0}, {"name": "test_partition", "description": "", "num_entities": 0}]
>>>
>>>
>>> partition.num_entities
0
>>>
>>>
>>> partition.insert(data)
[425468318129524045, 425468318129524046, 425468318129524047, 425468318129524048, 425468318129524049, 425468318129524050, 425468318129524051, 425468318129524052, 425468318129524053, 425468318129524054]
>>> partition.num_entities
10
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 0}, {"name": "test_partition", "description": "", "num_entities": 10}]
