### ISSUE TITLE
gpu docker pull timeout

### ISSUE THREAD

**Issue by deep-practice** [milvus-io/milvus#5587]
system:ubuntu18.04 
docker:19.03.13
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by yhmo** [comment]
You can search "docker hub 国内镜像" to find the solution.

**Comment by deep-practice** [comment]
I plan to build from source,but the docs about how to build from source seems out of date

$ git clone https://github.com/milvus-io/milvus
$ cd ./milvus/core
$ git checkout 0.10.3
./ubuntu_build_deps.sh

https://github.com/milvus-io/milvus/blob/1.0/INSTALL.md

**Comment by deep-practice** [comment]
ubuntu18.04 build from source error:
/home/work/demo/milvus-1.0/core/src/index/knowhere/knowhere/common/Dataset.h:14:15: fatal error: any: 没有那个文件或目录
/home/work/demo/milvus-1.0/core/src/index/knowhere/knowhere/common/Exception.cpp:36:22: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]

**Comment by deep-practice** [comment]
加了国内镜像之后，docker可以正常拉取了

**Comment by yhmo** [comment]
> 加了国内镜像之后，docker可以正常拉取了

Ok, then I close this issue.
