### ISSUE TITLE
Describe limitation of index_file_size

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#5590]
In 1.1.0 and older version, the index_file_size limitation range is [1, 4096]MB.
In next version 1.1.1, we enlarge the index_file_size limitation range to [1, 131072]MB

We need to describe this in milvus documentation. I think we can do this in this page: https://milvus.io/docs/v1.1.0/storage_concept.md

**Comment by PahudPlus** [comment]
@claireyuw When you publish 1.1.1, please double check.

**Comment by shengjun1985** [comment]
The description in [v1.1.1](https://milvus.io/docs/v1.1.1/storage_concept.md) is: index_file_size (1024 MB by default and 128 GB at most).
The description in [v1.1.0](https://milvus.io/docs/v1.1.0/storage_concept.md) and [v1.0.0](https://milvus.io/docs/v1.0.0/storage_concept.md) is: index_file_size (1024 MB by default and 4096MB at most).

Thanks all.
