### ISSUE TITLE
use mysql for metadata storage，but show sqlite error msg when do search

### ISSUE THREAD

**Issue by sloth2012** [milvus-io/milvus#5600]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
I don't know whether it is a bug or my illegal operation. 
At the beginning, when I start milvus, it works well,  it meet the Error after daily update twice.

the env is mishards docker-compose.

**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- aliyun 8core 64g
- milvus 1.1.1 (mishards docker-compose, 1 read, 1 write)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

no need , I only change the meta_uri, and cluster settings

**Screenshots**
![image](https://user-images.githubusercontent.com/4048815/120759813-fe9c3f00-c545-11eb-901c-0492e0ad41d8.png)

**Comment by sloth2012** [comment]
get_entity_by_id works well, only search raises error

**Comment by sloth2012** [comment]
I tried directly search with ro or wr ip:port (default 19540 or 19541), it works well, but with 19531，it raises sqlite error， I guess it may be a bug with transfering request。

**Comment by yhmo** [comment]
@sloth2012 
The mishard can be deployed by docker composer file, or ".env" file, or k8s/helm.
Could you tell me how you deploy the mishard?

**Comment by sloth2012** [comment]
> @sloth2012
> The mishard can be deployed by docker composer file, or ".env" file, or k8s/helm.
> Could you tell me how you deploy the mishard?

just docker-compose

**Comment by yhmo** [comment]
Under the mishard project, to use sqlite as meta service, run command "make deploy"; to use mysql as meta service, run comamnd "make deploy_m".

**Comment by yhmo** [comment]
"make deploy" use the **/milvus/shards/all_in_one/all_in_one.yml** as docker composer file
"make deploy_m" use the `/milvus/shards/all_in_one_with_mysql/all_in_one.yml`  as docker composer file
You can see in the two files are different, the `all_in_one_with_mysql/all_in_one.yml` has this line:
`SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:milvusroot@milvus-mysql:3306/milvus?charset=utf8mb4`

**Comment by sloth2012** [comment]
yes, I found I still need append this environment variable after modify meta_uri in server.yml。 
this SQLALCHEMY_DATABASE_URI is not showed in the officer file：https://github.com/milvus-io/milvus/blob/1.1/shards/all_in_one/all_in_one.yml。

thank you！

by the way， I want to know， mount the local dir as logs or wal with milvus, should  the ro and wr share the same dir like db ?

**Comment by yhmo** [comment]
> yes, I found I still need append this environment variable after modify meta_uri in server.yml。
> this SQLALCHEMY_DATABASE_URI is not showed in the officer file：[https://github.com/milvus-io/milvus/blob/1.1/shards/all_in_one/all_in_one.yml。](https://github.com/milvus-io/milvus/blob/1.1/shards/all_in_one/all_in_one.yml%E3%80%82)
> 
> thank you！
> 
> by the way， I want to know， mount the local dir as logs or wal with milvus, should the ro and wr share the same dir like db ?

Only the wr node can access wal folder, no need to shared the wal folder.
For logs folder, both wr and ro nodes can generate log files name such as "milvus-20-09-10-09_00-debug.log", I am afraid they could generate same file name and conflict each other, so I suggest distinct the logs folder. For example, wr node use wr_logs folder, ro node use ro_logs folder.

**Comment by sloth2012** [comment]
> > yes, I found I still need append this environment variable after modify meta_uri in server.yml。
> > this SQLALCHEMY_DATABASE_URI is not showed in the officer file：[https://github.com/milvus-io/milvus/blob/1.1/shards/all_in_one/all_in_one.yml。](https://github.com/milvus-io/milvus/blob/1.1/shards/all_in_one/all_in_one.yml%E3%80%82)
> > thank you！
> > by the way， I want to know， mount the local dir as logs or wal with milvus, should the ro and wr share the same dir like db ?
> 
> Only the wr node can access wal folder, no need to shared the wal folder.
> For logs folder, both wr and ro nodes can generate log files name such as "milvus-20-09-10-09_00-debug.log", I am afraid they could generate same file name and conflict each other, so I suggest distinct the logs folder. For example, wr node use wr_logs folder, ro node use ro_logs folder.

At the beginning, I separate logs and wal in different directory. But once I restart I found the wr works well, but ro is always restarting. I tried a lot, finally I found just copy the wr logs and wal to replace ro, then it restart well. So I don't understand why they still need each other  like this.

**Comment by yhmo** [comment]
> > > yes, I found I still need append this environment variable after modify meta_uri in server.yml。
> > > this SQLALCHEMY_DATABASE_URI is not showed in the officer file：[https://github.com/milvus-io/milvus/blob/1.1/shards/all_in_one/all_in_one.yml。](https://github.com/milvus-io/milvus/blob/1.1/shards/all_in_one/all_in_one.yml%E3%80%82)
> > > thank you！
> > > by the way， I want to know， mount the local dir as logs or wal with milvus, should the ro and wr share the same dir like db ?
> > 
> > 
> > Only the wr node can access wal folder, no need to shared the wal folder.
> > For logs folder, both wr and ro nodes can generate log files name such as "milvus-20-09-10-09_00-debug.log", I am afraid they could generate same file name and conflict each other, so I suggest distinct the logs folder. For example, wr node use wr_logs folder, ro node use ro_logs folder.
> 
> At the beginning, I separate logs and wal in different directory. But once I restart I found the wr works well, but ro is always restarting. I tried a lot, finally I found just copy the wr logs and wal to replace ro, then it restart well. So I don't understand why they still need each other like this.
> 
> beside. I want to know if the container is removed, can I recover data just with db, without the wal directory?

In the mishards project, in the example deploy yaml `/milvus/shards/all_in_one_with_mysql/all_in_one.yml`, we only mapping db folder to same path for the write node and read node.  RO node doesn't access wal folder. You can disable wal for the ro node in its config file:
```
wal:
  enable: false
```

The wal folder store the insert/delete actions data, ensure the data can be recovered even the write node crashed. After recover, the insert/delete data will be load from wal folder, consumed by milvus, store into db folder. 
If the wr container din't mapping the wal folder to outside path, then you remove the container, start another container, the new container won't recover data since its wal folder is empty. This is only for the case that your previous container is killed or crashed.

**Comment by sloth2012** [comment]
> > > > yes, I found I still need append this environment variable after modify meta_uri in server.yml。
> > > > this SQLALCHEMY_DATABASE_URI is not showed in the officer file：[https://github.com/milvus-io/milvus/blob/1.1/shards/all_in_one/all_in_one.yml。](https://github.com/milvus-io/milvus/blob/1.1/shards/all_in_one/all_in_one.yml%E3%80%82)
> > > > thank you！
> > > > by the way， I want to know， mount the local dir as logs or wal with milvus, should the ro and wr share the same dir like db ?
> > > 
> > > 
> > > Only the wr node can access wal folder, no need to shared the wal folder.
> > > For logs folder, both wr and ro nodes can generate log files name such as "milvus-20-09-10-09_00-debug.log", I am afraid they could generate same file name and conflict each other, so I suggest distinct the logs folder. For example, wr node use wr_logs folder, ro node use ro_logs folder.
> > 
> > 
> > At the beginning, I separate logs and wal in different directory. But once I restart I found the wr works well, but ro is always restarting. I tried a lot, finally I found just copy the wr logs and wal to replace ro, then it restart well. So I don't understand why they still need each other like this.
> > beside. I want to know if the container is removed, can I recover data just with db, without the wal directory?
> 
> In the mishards project, in the example deploy yaml `/milvus/shards/all_in_one_with_mysql/all_in_one.yml`, we only mapping db folder to same path for the write node and read node. RO node doesn't access wal folder. You can disable wal for the ro node in its config file:
> 
> ```
> wal:
>   enable: false
> ```
> 
> The wal folder store the insert/delete actions data, ensure the data can be recovered even the write node crashed. After recover, the insert/delete data will be load from wal folder, consumed by milvus, store into db folder.
> If the wr container din't mapping the wal folder to outside path, then you remove the container, start another container, the new container won't recover data since its wal folder is empty. This is only for the case that your previous container is killed or crashed.

ok, 3ku.
