### ISSUE TITLE
Want to support string as ID

### ISSUE THREAD

**Issue by YuLiGod** [milvus-io/milvus#5603]
Now Milvus only supports numbers as IDS, which bothers me

For example, if I want to insert a vector of an image, I need to use the MD5 value of the image as the ID, so that I can find my image accurately

But now I can only make a mapping table, which greatly reduces my efficiency and makes me very upset

Finally, I would like to thank Li Chenglong, the developer of Milvus user communication group, for giving me a lot of suggestions to use Milvus faster

**Comment by yhmo** [comment]
Duplicated with #4810 
We have realized String ID is an  important feature to users. We plan to implement it on the v2.0.

**Comment by YuLiGod** [comment]
Your reply speed is very fast, repeated questions can be judged by L2 distance, thank you very much!


In addition, I want to know exactly whether v2.0 can solve the problem of string as ID





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "milvus-io/milvus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月4日(星期五) 下午4:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [milvus-io/milvus] Want to support string as ID (#5603)





 
Duplicated with #4810
 We have realized String ID is an  important feature to users. We plan to implement it on the v2.0.

**Comment by yhmo** [comment]
In the v2.0, you can define multiple fields for a collection, each filed can be different type, the types including vectors, long, double, float, etc. The string type field is in roadmap of 2.0.

**Comment by yhmo** [comment]
This feature is in progress in v2.0:
https://wiki.lfaidata.foundation/display/MIL/MEP+11+--+Support+String+DataType

**Comment by yhmo** [comment]
Duplicate with #4430, close this one, tracked by #4430
