### ISSUE TITLE
Error message should be more specific if Index() with None collection

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#5646]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Error log should be more detail if Index() with None collection.

```
DEBUG    refactor_test:api_request.py:35 (func_req)[<class 'pymilvus_orm.index.Index'>] Parameters ars arg: [None, 'float_vector', {'index_type': 'IVF_SQ8', 'metric_type': 'L2', 'params': {'nlist': 64}}, 'index_ei202Jbt'], kwargs: {'check_task': 'error_response', 'err_code': 1, 'err_msg': 'Collection'}
ERROR    refactor_test:api_request.py:19 Traceback (most recent call last):
  File "/home/zw/tmp/tmp/milvus/tests20/python_client/utils/api_request.py", line 15, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/zw/tmp/tmp/milvus/tests20/python_client/utils/api_request.py", line 36, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pymilvus_orm/index.py", line 60, in __init__
    conn = self._get_connection()
  File "/usr/local/lib/python3.6/dist-packages/pymilvus_orm/index.py", line 68, in _get_connection
    return self._collection._get_connection()
AttributeError: 'NoneType' object has no attribute '_get_connection'

```
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/155

**Comment by xiaocai2333** [comment]
It will throw an exception if does not create  a connection.
