### ISSUE TITLE
build milvus from source

### ISSUE THREAD

**Issue by mingrenbuke** [milvus-io/milvus#5655]
[https://github.com/milvus-io/milvus/blob/1.1/INSTALL.md](https://github.com/milvus-io/milvus/blob/1.1/INSTALL.md)
It seems not working when I run the follow codes.
`$ git clone https://github.com/milvus-io/milvus
$ cd ./milvus/core
$ git checkout 0.10.3`
No core dir exists.

**Comment by yhmo** [comment]
The master branch is for v2.0
We have change version's source code from  branch to tag, the INSTALL.md need update now.
To checkout source code of 0.10.3, you can open the web page: https://github.com/milvus-io/milvus/tree/v0.10.3, from the commit list find out the last commit id, then use "git checkout" to sync to the commit:
```
git clone https://github.com/milvus-io/milvus
git checkout 1.1
cd ./milvus/core
git checkout 50d5b9f179dd85ada5a4ff7bd7606f3ed7cb19c4
```

**Comment by shengjun1985** [comment]
The `INSTALL.md` in branch 1.1 is fixed.
Thank you very much for reporting the bug.
