### ISSUE TITLE
Remove field name returned by collection.index.params

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#5660]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
(Pdb) cw2.collection.indexes[0].params
{'index_type': 'IVF_SQ8', 'metric_type': 'L2', 'params': {'nlist': 64}, 'field_name': 'float_vector'}
(Pdb) index_2.params
{'index_type': 'IVF_SQ8', 'metric_type': 'L2', 'params': {'nlist': 64}}
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/156

**Comment by xiaocai2333** [comment]
Index params no longer contains field name. Because Index has _field_name attribute.
