### ISSUE TITLE
Collection initial failed after creating invalid index

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#5663]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Collection initial failed after creating invalid index

**Steps/Code to reproduce behavior**
1 create collection （insert binary data)
2 create invalid index -- report code=1, message=create index failed (successfully)
   default_index = {"index_type": "IVF_FLAT", "params": {"nlist": 128}, "metric_type": "L2"}
3 try to drop this collection and initial the collection first 
4 collection() -- failed for trying to creating index (however, the parameter was recorded in the server side is not valid)

**Expected behavior**
Not trying to creating index at this invalid scenario, and return collection and index object only

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
latest
Name: pymilvus
Version: 2.0a1.dev27
Name: pymilvus-orm
Version: 2.0a1.dev19

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/156

**Comment by binbinlv** [comment]
Verified in the following version, and it has been fixed, so close this issue.
Name: pymilvus
Version: 2.0a1.dev34
Name: pymilvus-orm
Version: 2.0a1.dev22
