### ISSUE TITLE
Multi-threaded creation of singleton mode may cause problems

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#5664]
**Please state your issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**
Multi-threaded creation of singleton mode may cause problems, as follows:
class SingleInstanceMetaClass(type):
    def __init__(cls, name, bases, dic):
        cls.__single_instance = None
        super().__init__(name, bases, dic)

    def __call__(cls, *args, **kwargs):
        if cls.__single_instance:
            return cls.__single_instance
        single_obj = cls.__new__(cls)
        single_obj.__init__(*args, **kwargs)
        cls.__single_instance = single_obj
        return single_obj

class Connections(metaclass=SingleInstanceMetaClass):
    """
    Connections is a class which is used to manage all connections of milvus.
    Used as a singleton in this module.
    """

    def __init__(self):
        """
        Construct a Connections object.
        """
        self._kwargs = {"default": {"host": DefaultConfig.DEFAULT_HOST,
                                    "port": DefaultConfig.DEFAULT_PORT}}
        self._conns = {}

**Describe the solution you'd like**
Multi-threaded initialization objects are also unique.

**Describe alternatives you've considered**
Locking when initializing the object may avoid this problem.

**Comment by DragonDriver** [comment]
Yeah, thanks for pointing out this. I will use a `check-lock-check` pattern to keep the instance initialized only once.

**Comment by DragonDriver** [comment]
Already fixed by [pr 160 of pymilvus-orm](https://github.com/milvus-io/pymilvus-orm/pull/160).
