### ISSUE TITLE
Memory usage is not steadily rising during preloading table

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#567]
**Describe the bug**
This issue may decrease the preloading time

**Steps/Code to reproduce behavior**

**Expected behavior**
steadily rising in memory usage

**Environment details**
0.6.0

**Screenshots**
![Screenshot_2019-11-27 dashboard3 - Grafana(1)](https://user-images.githubusercontent.com/56623710/69692851-4bf84e80-110e-11ea-96c3-3b33659f34bf.png)

**Additional context**

**Comment by yhmo** [comment]
As designed

**Comment by del-zhenwu** [comment]
Cost 5min more than 0.6 with using sift-1b.

**Comment by tinkerlin** [comment]
0.10.0 cost 10mins
