### ISSUE TITLE
The binary vector dim of creating collection and inserting data are inconsistent

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5675]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
1. create connection and connect
2. create a collection from binary DataFrame without schema.  Before calling the `np.packbits`, the dim of the binary vector is 128, after that is 128/18
```
def gen_binary_vectors(num, dim):
    raw_vectors = []
    binary_vectors = []
    for _ in range(num):
        raw_vector = [random.randint(0, 1) for _ in range(dim)]
        raw_vectors.append(raw_vector)
        binary_vectors.append(bytes(np.packbits(raw_vector, axis=-1).tolist()))
    return raw_vectors, binary_vectors
```
```
    def test_collection_binary_created_by_dataframe(self):
        self._connect()
        c_name = cf.gen_unique_str(prefix)
        df, _ = cf.gen_default_binary_dataframe_data(ct.default_nb)
        schema = cf.gen_default_binary_collection_schema()
        self.collection_wrap.init_collection(name=c_name, data=df)
        assert_default_collection(self.collection_wrap, exp_name=c_name, exp_num=ct.default_nb, exp_schema=schema)
```
Raise exception:
```
[Milvus API Exception]<function api_request at 0x7fc489de1e50>: Collection field dim is 16, but entities field dim is 128 
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus              2.0a1.dev32
 pymilvus-orm          2.0a1.dev20

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by ThreadDao** [comment]
Regress this issue according to this case:
```
@pytest.mark.tags(CaseLabel.L0)
    # @pytest.mark.xfail(reason="issue #5675")
    def test_construct_from_binary_dataframe(self):
        conn = self._connect()
        c_name = cf.gen_unique_str(prefix)
        df, _ = cf.gen_default_binary_dataframe_data(nb=ct.default_nb)
        self.collection_wrap.construct_from_dataframe(c_name, df,
                                                      check_task=CheckTasks.check_collection_property,
                                                      check_items={exp_name: c_name, exp_schema: default_binary_schema})
        conn.flush([c_name])
        assert self.collection_wrap.num_entities == ct.default_nb
```

**Comment by cydrain** [comment]
there are 2 issues related with this case:
1. pymilvus-orm calculate binary vector dim in-correctly, fixed with folloging PR
https://github.com/milvus-io/pymilvus-orm/pull/172

2. in test20/python_client/check/func_check.py
```
    def check_collection_property(collection, func_name, check_items):
        ... ...
        if num_entities == 0:
            assert collection.is_empty
        assert collection.num_entities == num_entities
        ... ...
```
above code is in-correct, because this collection has not been flushed, num_entities is 0
