### ISSUE TITLE
The connection interface of add_connection adds the wrong format connection and no error is reported

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#5684]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
The connection interface of add_connection adds the wrong format connection and no error is reported.

**Steps/Code to reproduce behavior**
    def test_connection_add_wrong_format(self):
        """
        target: test add_connection, regardless of whether the connection exists
        method: add existing and non-existing configurations at the same time
        expected: list_connections include the configured connections
        """
        self.connection_wrap.add_connection(alias1={"host": "localhost", "port": "1"},
                                            alias2={"host": "hostlocal", "port": "-1"},
                                            testing={"": ""})
        list_conn = self.connection_wrap.list_connections(check_task=CheckTasks.check_list,
                                                          check_items={"list_content": [('default', None),
                                                                                        ('alias1', None),
                                                                                        ('alias2', None),
                                                                                        ('testing', None)]})[0]
        assert self.connection_wrap.get_connection_addr("default")[0] == {'host': 'localhost', 'port': '19530'}
        assert self.connection_wrap.get_connection_addr("alias1")[0] == {"host": "localhost", "port": "1"}
        assert self.connection_wrap.get_connection_addr("alias2")[0] == {"host": "hostlocal", "port": "-1"}
        assert self.connection_wrap.get_connection_addr("testing")[0] == {"": ""}

**Expected behavior**
add_connection with param of testing={"": ""}  should raise error

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
pymilvus-orm == 2.0a1.dev8

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/171

**Comment by wangting0128** [comment]
Verified
