### ISSUE TITLE
Is there cosine similarity api ? 

### ISSUE THREAD

**Issue by yan-rui** [milvus-io/milvus#5693]
**Please state your issue using the following template and, most importantly, in English.**
Some task need cosine similarity. I Know cosine similarity is equel to IP and L2 when vectors normalized. However we need cosine score also.
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I wish I could use Milvus to do [...]

**Describe the solution you'd like**
Add consine similarity into metric types.
**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by shengjun1985** [comment]
Excuse me, but are your vectors normalized?
If they are, IP distance is equal to cosine score.
It they aren't, Milvus does not provide such API and you need normalize them before inserting.

**Comment by yan-rui** [comment]
> Excuse me, but are your vectors normalized?
> If they are, IP distance is equal to cosine score.
> It they aren't, Milvus does not provide such API and you need normalize them before inserting.

Yes, I know that.
Just needs cosine score in some projects.
And some projects will not normalize vectors.

**Comment by yan-rui** [comment]
So my suggestion is adding Cosine distance metric.

**Comment by shengjun1985** [comment]
May I ask why you not to normalize the data before inserting?
As far as I known, it is slower to calculate the cosine distance of the non normalized data than the inner product of the normalized data. So, normalization before insertion can improve query performance.

**Comment by yan-rui** [comment]
Just a suggestion.  Some porject like mine wants cosine score to directily evaluate my algorithm.

**Comment by xiaofan-luan** [comment]
@shengjun1985  what about have a preprocessing stage and do normalization before insert into milvus

**Comment by shengjun1985** [comment]
We can add such a stage.
But the vectors stored in the system will be different with they inserted.
So what the IF GetEntityById() returns (before or after normalization) needs to be determined.
