### ISSUE TITLE
Unsuccessful connec creation is also added to the connection list

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#5697]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Unsuccessful connec creation is also added to the connection list.

**Steps/Code to reproduce behavior**
@pytest.mark.parametrize("connect_name", ["test_alias_nme"])
    def test_connection_connect_wrong_params(self, host, port, connect_name):
        """
        target:
        method:
        expected:
        """

        # created connection with wrong connect name
        self.connection_wrap.connect(alias=connect_name, ip=host, port=port, check_task=CheckTasks.err_res,
                                     check_items={"err_code": -1,
                                                  "err_msg": "Param is not complete. Please invoke as follow:"})

        # list all connections and check the response
        self.connection_wrap.list_connections(check_task=CheckTasks.check_normal,
                                              check_items={"list_content": [('default', None)]})

**Expected behavior**
Unsuccessful connection creation is not added to the connection list.

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
pymilvus-orm == 2.0a1.dev8

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**
        host = self._kwargs[alias].get("host", None)
        port = self._kwargs[alias].get("port", None)
        handler = self._kwargs[alias].get("handler", DefaultConfig.DEFAULT_HANDLER)
        pool = self._kwargs[alias].get("pool", DefaultConfig.DEFAULT_POOL)

        kwargs.pop("host", None)
        kwargs.pop("port", None)
        kwargs.pop("handler", None)
        kwargs.pop("pool", None)

        conn = Milvus(host, port, handler, pool, **kwargs)
        self._conns[alias] = conn
        return conn

Should not be added to the list of self._conns after failed to create a connection.

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/171

**Comment by wangting0128** [comment]
Verified
