### ISSUE TITLE
Create collection throw error, but actually create successfully.

### ISSUE THREAD

**Issue by nameczz** [milvus-io/milvus#5698]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
When create collection, set autoID false and without primary key.
Will throw { error_code: 'UnexpectedError', reason: 'primay key is undefined' }, it's correct.
But then you call hasCollection will return true. showCollections also contain this collection.

**Steps/Code to reproduce behavior**
1. create collection with autoID=false and without primay key 
2. throw error
3. call has collection return true

**Expected behavior**
Do not create collection when throw error.

**Method of installation**
- [ ] Docker/standalone

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
Milvus 2.0

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/171

**Comment by nameczz** [comment]
I think this is fixed
