### ISSUE TITLE
load hangs when loading data for collection with more than one partitions (both partitions are inserted data)

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#5712]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
load hangs when loading data for collection with more than one partitions (new created partitions have data)
[load once]
(1) collection with _default partition only:
      insert data  ---- load successfully
(2) collection with two partitions (_default and new created one): 
      insert data into only "_default" partition,  new created partition is empty  ---- load successfully
(3) collection with two partitions (_default and new created one):
      insert data into two partitions ---- load failed (hanging)

**Steps/Code to reproduce behavior**

Code:
from pymilvus_orm import CollectionSchema, FieldSchema
from pymilvus_orm import Collection
from pymilvus_orm import connections
from pymilvus_orm.types import DataType
from pymilvus_orm import Partition

int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primaty=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=128)
schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
connections.connect(host="172.18.255.155", port="19530")
import numpy as np
collection = Collection("test_search_collection_binbin_5", schema=schema)
collection.create_partition(partition_name="search_partition_1", description="search partition")
par = collection.partitions
dim = 128
nb = 500
nq = 1
limit = 1000
import random
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors],  par[0].name)
collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors],  par[1].name)
collection.partitions
default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
collection.load()

**Expected behavior**
Load returns without errors (no hanging)

**Method of installation**
- [ ] Docker/cpu

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
Name: pymilvus
Version: 2.0a1.dev34
Name: pymilvus-orm
Version: 2.0a1.dev22

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
This bug has been fixed in branch master. Please retest it.

**Comment by binbinlv** [comment]
no hangs on the following version, so close it.
Name: pymilvus
Version: 2.0a1.dev35
Name: pymilvus-orm
Version: 2.0a1.dev31
