### ISSUE TITLE
Mishards tutorial: milvus' git clone command needs updating

### ISSUE THREAD

**Issue by ss892714028** [milvus-io/milvus#5714]
**Please state your issue using the following template and, most importantly, in English.**
on this page: https://milvus.io/docs/v1.0.0/mishards.md
git clone https://github.com/milvus-io/milvus downloads the latest version of milvus, however, the latest version does not have milvus/shards directory

**Location of incorrect documentation**
Provide links and line numbers if applicable.
https://milvus.io/docs/v1.0.0/mishards.md
Start a Milvus and Mishards instance
1. Clone the Milvus repository to your local machine:
```bash
git clone https://github.com/milvus-io/milvus
```

**Describe the problems or issues found in the documentation**
A clear and concise description of what you found to be incorrect.
git clone https://github.com/milvus-io/milvus downloads the latest version of milvus, however, the latest version does not have milvus/shards directory

**Steps taken to verify documentation is incorrect**
List any steps you have taken:
milvus/shards does not exist in the current master branch (milvus 2.0)

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.
specify a branch with version <2.0
change to 
```bash
git clone https://github.com/milvus-io/milvus -b 1.1
```

---

## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken:

**Comment by LocoRichard** [comment]
Thank you for your contribution. We have fixed the issue.
