### ISSUE TITLE
recommended to add alias parameter legalization check

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#5725]
**Please state your issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**
Aliases have not been checked for parameter legalization,   recommended to uniformly add string legalization checks for alias。
Contains the following connection interface：
1. def disconnect(self, alias):
2. def remove_connection(self, alias):
3. def connect(self, alias=DefaultConfig.DEFAULT_USING, **kwargs) -> Milvus:
4. def get_connection(self, alias=DefaultConfig.DEFAULT_USING) -> Milvus:
5. def get_connection_addr(self, alias):

**Describe the solution you'd like**
Passing an illegal string, raise the corresponding exception.

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by XuanYang-cn** [comment]
Good advice, I'm on it.

/unassign @czs007

**Comment by wangting0128** [comment]
Alias input these four parameters： None， (1,)，1.0， 1， the following interfaces do not report errors：
  1. def disconnect(self, alias):
  2. def remove_connection(self, alias):
  3. def get_connection_addr(self, alias):
  
logs:
DEBUG    ci_test:api_request.py:40 (api_request) Request: [<bound method Connections.disconnect of <pymilvus_orm.connections.Connections object at 0x7ff37c374668>>] args: [None], kwargs: {}
DEBUG    ci_test:api_request.py:19 (api_response) Response : None


DEBUG    ci_test:api_request.py:40 (api_request) Request: [<bound method Connections.disconnect of <pymilvus_orm.connections.Connections object at 0x7ff37c374668>>] args: [1], kwargs: {}
DEBUG    ci_test:api_request.py:19 (api_response) Response : None


DEBUG    ci_test:api_request.py:40 (api_request) Request: [<bound method Connections.disconnect of <pymilvus_orm.connections.Connections object at 0x7ff37c374668>>] args: [1.0], kwargs: {}
DEBUG    ci_test:api_request.py:19 (api_response) Response : None


DEBUG    ci_test:api_request.py:40 (api_request) Request: [<bound method Connections.disconnect of <pymilvus_orm.connections.Connections object at 0x7ff37c374668>>] args: [(1,)], kwargs: {}
DEBUG    ci_test:api_request.py:19 (api_response) Response : None
