### ISSUE TITLE
Search with expressions returns wrong results

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#5739]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Search with expressions returns wrong results
1 connect, collect, and insert 500 entities
2 search with different expressions
   (1) expression:  int64 in [1, 2, 3]   -- returns 3  (correct)
   **(2) expression:  int64 not in [1, 2, 3] --return 3  which is same with (1) (not correct)**
   (3) expression:  not (int64 in [1, 2, 3]) --return 497 (correct)

Scenario (2) should be the same with (3), not (1)

**Steps/Code to reproduce behavior**
Code:
from pymilvus_orm import CollectionSchema, FieldSchema
from pymilvus_orm import Collection
from pymilvus_orm import connections
from pymilvus_orm.types import DataType
from pymilvus_orm import Partition

int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primaty=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=128)
schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
connections.connect(host="172.18.255.155", port="19530")
import numpy as np
collection = Collection("test_search_collection_binbin_5", schema=schema)
dim = 128
nb = 500
limit = 1000
import random
default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
collection.partitions
collection.load()
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 in [1, 2, 3]")
>>> len(res[0])
3
>>> res[0].ids
[425544096292474553, 425544096292474555, 425544096292474554]
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 not in [1, 2, 3]")
>>> len(res[0])
3
>>> res[0].ids
[425544096292474553, 425544096292474555, 425544096292474554]
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "not (int64 in [1, 2, 3])")
>>> len(res[0])
497

**Expected behavior**
Scenario (2) should be the same with (3), not (1)

**Method of installation**
- [ ] Docker/cpu

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
Name: pymilvus
Version: 2.0a1.dev35
Name: pymilvus-orm
Version: 2.0a1.dev22

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by FluorineDog** [comment]
confirmed, fixed by #5741

**Comment by FluorineDog** [comment]
@binbinlv fix PR #5741  has been merged, please verify

**Comment by binbinlv** [comment]
Verified in the latest milvus version, so close this issue.
(commit 4165b761c957eac2328aeda989766deacf6c223d)
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 in [1, 2, 3]")
>>> len(res[0])
3
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 not in [1, 2, 3]")
>>> len(res[0])
497
>>>
>>>
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "not (int64 in [1, 2, 3])")
>>> len(res[0])
497
