### ISSUE TITLE
Search with big nq and topk crash milvus

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#5747]
**Please state your issue using the following template and, most importantly, in English.**
Search with big nq and topk crash milvus

**Describe the bug**
gRPC will throw exception when application try send a huge message size larger than 2GB. If user input big nq and topk to search, the result size may exceed 2GB, and crash milvus.

**Steps/Code to reproduce behavior**
1. create a collection, dimension = 8
2. insert 100000 vectors
3. call search(), nq = 11000, topk = 16384

The result size is 11000*16384*(sizeof(int64)+sizeof(float))=2162688000=2.01GB, milvus will crashed by the gRPC exception.

**Expected behavior**
Check the input for search, if search result size exceed 2GB, return error to client.

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
Has been fixed in v1.1.1, released today.

**Comment by zxbing** [comment]
very good, test now
