### ISSUE TITLE
Create collection with exception "should create connect first", but actually connection is created

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#5756]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Create collection with error "should connect first", but actually connection is created 
(on latest pymilvus-orm version, Version: 2.0a1.dev24)
[pymilvus is good, bug should be in pymilvus-orm)

It is **good** on 2.0 a1.dev22:
Name: pymilvus
Version: 2.0a1.dev35
Name: pymilvus-orm
**Version: 2.0a1.dev22**

**Fail:**
Name: pymilvus
Version: 2.0a1.dev35
Name: pymilvus-orm
**Version: 2.0a1.dev24**

ERROR    ci_test:api_request.py:22 Traceback (most recent call last):
  File "/milvus/tests20/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/milvus/tests20/python_client/utils/api_request.py", line 41, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus_orm/collection.py", line 101, in __init__
    conn = self._get_connection()
  File "/usr/local/lib/python3.6/site-packages/pymilvus_orm/collection.py", line 153, in _get_connection
    raise ConnectionNotExistException(0, "should create connect first")
pymilvus_orm.exceptions.ConnectionNotExistException: <ConnectionNotExistException: (code=0, message=should create connect first)>

**Steps/Code to reproduce behavior**
Using pymilvus-orm interface
1 create connection
2 create collection, and report error
[Milvus API Exception]<function api_request at 0x7f98323e47b8>: <ConnectionNotExistException: (code=0, message=should create connect first)>

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
milvus: master
Name: pymilvus-orm
Version: 2.0a1.dev24
Name: pymilvus
Version: 2.0a1.dev35

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by binbinlv** [comment]
The issue still exists on the following version:
Name: pymilvus
Version: 2.0a1.dev35
Name: pymilvus-orm
Version: 2.0a1.dev26

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/163

**Comment by binbinlv** [comment]
Verified in the following version, and close it.
Name: pymilvus-orm
Version: 2.0a1.dev27
