### ISSUE TITLE
Support using mmap to load index data

### ISSUE THREAD

**Issue by scipe** [milvus-io/milvus#5761]
Hi guys. Is any way to disable/enable IO_FLAG_MMAP for faiss under the hood?

**Comment by shengjun1985** [comment]
The flag `IO_FLAG_MMAP` is always disabled.
May I ask your actual use cases?

**Comment by scipe** [comment]
Hm. I saw in your sources ([here](https://github.com/milvus-io/milvus/blob/a3e4339027bccd3f7c9c6a05ffe211619b4e5f0e/internal/core/src/index/thirdparty/faiss/impl/index_read.cpp)) that it's enabled by default..

Okay so we have a 300m dataset and when we test raw FAISS we can reduce memory cost with the at flag. 

Now our server with milvus need 170~GB RAM for IFV_SQ8.

**Comment by scipe** [comment]
Any reason why you not allowed enable this flag? Any chances to allow edit it?

**Comment by yhmo** [comment]
The milvus is designed as a in-memory search engine. When search, milvus load data into memory(the limit is determined by cache_size in config file), and manage data by LRU strategy. By caching all required data in memory, milvus can obtain best search performance. mmap can improve the I/O performance, but cannot obtain best search performance like in-memory cache. So we disable the mmap of faiss.
The cache system is in up level, to support faiss-mmap, we need to overwrite the cache logic code. I think there will be log of code change.

**Comment by scipe** [comment]
So, @yhmo in general you want to support that feature or you it should not be here by design

**Comment by yhmo** [comment]
No, I am not meaning "it should not be here". It may be a valuable feature for some users. 
I just worry about the code change bring large impact to main functions.

**Comment by yhmo** [comment]
Currently the milvus team is focusing on the upcoming v2.0, we have limit resource to maintain v1.x. I intend to keep it in investigation level until we get more dev resource to implement it.
