### ISSUE TITLE
A link in a blog article is broken

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#5769]
**Please state your issue using the following template and, most importantly, in English.**
The link https://github.com/milvus-io/bootcamp/blob/master/demo/recommender_system in this milvus post https://zilliz.com/blog/building-personalized-recommender-systems-milvus-paddlepaddle is broken

**Location of incorrect documentation**
At the bottom of the article, give some links:

```
Reference
01 MovieLens Million Dataset (ml-1m): http://files.grouplens.org/datasets/movielens/ml-1m.zip
02 ml-1m-README: http://files.grouplens.org/datasets/movielens/ml-1m-README.txt
03 Fusion Recommendation Model by PaddlePaddle: https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/basics/recommender_system/index.html#id7
04 Bootcamp: https://github.com/milvus-io/bootcamp/blob/master/demo/recommender_system
05 Milvus: https://milvus.io/en/
```
The link "04" is broken

**Suggested fix for documentation**
Change the "04" to this link:
https://github.com/milvus-io/bootcamp/tree/master/solutions/recommendation_system

**Comment by LocoRichard** [comment]
Thank you, we have fixed the link. closing the issue
