### ISSUE TITLE
Documentation typo Issue

### ISSUE THREAD

**Issue by seo-jinBro** [milvus-io/milvus#5789]
In [milvus_distributions-gpu](https://milvus.io/docs/v1.1.0/milvus_distributions-gpu.md), current doc is

```
An index built with CPU is identical to built with CPU. The only difference is the time to build the index: GPU usually takes less time.
```

It should be

```
An index built with GPU is identical to built with CPU. The only difference is the time to build the index: GPU usually takes less time.
```

**Comment by cxie** [comment]
Hi @seo-jinBro, thanks for pointing out the typo. Could you help us to submit a PR to correct this typo? There is an Edit button on the up-right corner and you can start to edit the doc from there. Your contributions would be greatly appreciated by the Milvus Community. Please feel free to let me know if you encounter any difficulties.

**Comment by seo-jinBro** [comment]
@cxie Thanks for your suggestion. I made a [PR](https://github.com/milvus-io/docs/pull/578) for it. Thank you.
