### ISSUE TITLE
Build index hang in GPU version when gpu resources disabled

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#579]
**Describe the bug**
Build index hang in GPU version but gpu_resource_config.enable = false

**Steps/Code to reproduce behavior**
1. Build GPU version and run. 
2. Modify the server_config.yaml, set gpu_resource_config.enable = false
3. Create table and add some vectors
4. Create index

Result:
Milvus hangs

**Expected behavior**
In GPU version, if gpu_resource_config.enable set to false, we should use cpu to build index and search.

**Comment by yhmo** [comment]
The root cause is:
If gpu_resource_config.enable set to false, the ExecutionEngineImpl::CreatetVecIndex() shouldn't return gpu index.

**Comment by cydrain** [comment]
fixed
