### ISSUE TITLE
Describe index still has data after drop index on same vector field

### ISSUE THREAD

**Issue by nameczz** [milvus-io/milvus#5800]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Describe index has data after drop index

**Steps/Code to reproduce behavior**
1. create collection
2. create index on vector_field
3. describe index return data.
4. drop index return success
5. describe index still return index data

**Expected behavior**
Describe index return empty after drop index

**Method of installation**
- [ ] Docker/standalone

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
v2.0

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by neza2017** [comment]
This issue has fixed, this is my test code, please check it
```python
from pymilvus import Milvus, IndexType, MetricType, DataType
from sklearn import preprocessing
import time
import random

_HOST = '127.0.0.1'
_PORT = '19530'  # default value
_DIM = 128  # dimension of vector

connection = Milvus(_HOST, _PORT)
collection_name = 'issue_5800_'
ok = connection.has_collection(collection_name)
if not ok:
    param = {
        'fields': [
            {"name": "int64", "type": DataType.INT64, "is_primary": True},
            {"name": "float32", "type": DataType.FLOAT},
            {"name": "float_vec", "type": DataType.FLOAT_VECTOR, "params": {"dim": _DIM}},
        ],
        "segment_row_limit": 1000,
        "auto_id": True,
    }
    connection.create_collection(collection_name, param)
ok = connection.has_collection(collection_name)
print("has collection", collection_name, ok)
index_params = {
    "metric_type": "L2",
    "index_type": "IVF_FLAT",
    "params": {"nlist": 2048}
}

connection.create_index(collection_name,"float_vec",index_params)
idx = connection.describe_index(collection_name)
print(idx)
connection.drop_index(collection_name,"float_vec")

print("============= drop index =============")
idx = connection.describe_index(collection_name)
print(idx)
```
output
```txt
has collection issue_5800_ True
{'metric_type': 'L2', 'index_type': 'IVF_FLAT', 'params': {'nlist': 2048}, 'field_name': 'float_vec'}
============= drop index =============
None
```

**Comment by neza2017** [comment]
@nameczz

**Comment by nameczz** [comment]
Docker: milvusdb/milvus-dev:master-latest
I am not use pymilvus. I use proto client to operate milvus directly. 
And index still exist after drop index.
![image](https://user-images.githubusercontent.com/20559208/123362621-8d2f3980-d5a3-11eb-8ad7-f6423168062b.png)

**Comment by nameczz** [comment]
i think this is fixed
