### ISSUE TITLE
Run Milvus docker image report Process killed

### ISSUE THREAD

**Issue by yucongshub** [milvus-io/milvus#5813]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Jun 16 18:57:31 localhost kernel: traps: milvus_server[64972] trap invalid opcode ip:924db0 sp:7ffc291698c8 error:0 in milvus_server[400000+bfa000]
Jun 16 18:57:31 localhost abrt-hook-ccpp: Process 7 (milvus_server) of user 0 killed by SIGILL - ignoring (repeated crash)
Jun 16 18:57:31 localhost abrt-hook-ccpp: Saved core dump of pid 64972 to core.64972 at /var/lib/milvus (2048000 bytes)

**Method of installation**
- [x] Docker/cpu
- [x] docker pull milvusdb/milvus:1.1.0-cpu-d050721-5e559c

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)
- Memory 512G
- CPU Intel(R) Xeon(R) CPU E7- 8870  @ 2.40GHz
- [root@localhost ~]# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
- [root@localhost ~]# uname -a
Linux localhost.localdomain 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Milvus version (master or released version)
- milvusdb/milvus:1.1.0-cpu-d050721-5e559c

**Configuration file**
[server_config.txt](https://github.com/milvus-io/milvus/files/6662509/server_config.txt)

**Comment by yhmo** [comment]
Ok, it is first time I see this kind of error. So far I have no idea why this happens.
Your docker version is?
Does the error occur even with this simple command? 
`docker run -p 19530:19530 milvusdb/milvus:1.1.0-cpu-d050721-5e559c`

**Comment by yucongshub** [comment]
> Ok, it is first time I see this kind of error. So far I have no idea why this happens.
> Your docker version is?
> Does the error occur even with this simple command?
> `docker run -p 19530:19530 milvusdb/milvus:1.1.0-cpu-d050721-5e559c`

This simple command still causes the error.
Jun 17 11:32:11 localhost kernel: docker0: port 2(veth432cec1) entered blocking state
Jun 17 11:32:11 localhost kernel: docker0: port 2(veth432cec1) entered disabled state
Jun 17 11:32:11 localhost kernel: device veth432cec1 entered promiscuous mode
Jun 17 11:32:11 localhost kernel: IPv6: ADDRCONF(NETDEV_UP): veth432cec1: link is not ready
Jun 17 11:32:11 localhost NetworkManager[2010]: <info>  [1623900731.7201] manager: (veth7198fbe): new Veth device (/org/freedesktop/NetworkManager/Devices/48)
Jun 17 11:32:11 localhost NetworkManager[2010]: <info>  [1623900731.7227] manager: (veth432cec1): new Veth device (/org/freedesktop/NetworkManager/Devices/49)
Jun 17 11:32:11 localhost containerd: time="2021-06-17T11:32:11.895641120+08:00" level=info msg="starting signal loop" namespace=moby path=/run/containerd/io.containerd.runtime.v2.task/moby/c23b67250d3def6a51ac1409685dd61f32d149c8b91356bc3ea050d93874e41c pid=74682
Jun 17 11:32:12 localhost kernel: IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
Jun 17 11:32:12 localhost kernel: IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Jun 17 11:32:12 localhost kernel: IPv6: ADDRCONF(NETDEV_CHANGE): veth432cec1: link becomes ready
Jun 17 11:32:12 localhost kernel: docker0: port 2(veth432cec1) entered blocking state
Jun 17 11:32:12 localhost kernel: docker0: port 2(veth432cec1) entered forwarding state
Jun 17 11:32:12 localhost NetworkManager[2010]: <info>  [1623900732.3283] device (veth432cec1): carrier: link connected
Jun 17 11:32:12 localhost kernel: traps: milvus_server[74753] trap invalid opcode ip:924db0 sp:7ffdc4cda168 error:0 in milvus_server[400000+bfa000]
Jun 17 11:32:12 localhost abrt-hook-ccpp: Process 8 (milvus_server) of user 0 killed by SIGILL - dumping core
Jun 17 11:32:12 localhost dockerd: time="2021-06-17T11:32:12.645723356+08:00" level=info msg="ignoring event" container=c23b67250d3def6a51ac1409685dd61f32d149c8b91356bc3ea050d93874e41c module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Jun 17 11:32:12 localhost containerd: time="2021-06-17T11:32:12.646009009+08:00" level=info msg="shim disconnected" id=c23b67250d3def6a51ac1409685dd61f32d149c8b91356bc3ea050d93874e41c
Jun 17 11:32:12 localhost containerd: time="2021-06-17T11:32:12.646788563+08:00" level=error msg="copy shim log" error="read /proc/self/fd/14: file already closed"
Jun 17 11:32:12 localhost kernel: docker0: port 2(veth432cec1) entered disabled state
Jun 17 11:32:12 localhost abrt-server: Executable '/var/lib/milvus/bin/milvus_server' doesn't belong to any package and ProcessUnpackaged is set to 'no'
Jun 17 11:32:12 localhost abrt-server: 'post-create' on '/var/spool/abrt/ccpp-2021-06-17-11:32:12-74753' exited with 1
Jun 17 11:32:12 localhost abrt-server: Deleting problem directory '/var/spool/abrt/ccpp-2021-06-17-11:32:12-74753'
Jun 17 11:32:12 localhost NetworkManager[2010]: <info>  [1623900732.8190] manager: (veth7198fbe): new Veth device (/org/freedesktop/NetworkManager/Devices/50)
Jun 17 11:32:12 localhost kernel: docker0: port 2(veth432cec1) entered disabled state
Jun 17 11:32:12 localhost kernel: device veth432cec1 left promiscuous mode
Jun 17 11:32:12 localhost kernel: docker0: port 2(veth432cec1) entered disabled state
Jun 17 11:32:12 localhost NetworkManager[2010]: <info>  [1623900732.8438] device (veth432cec1): released from master device docker0
 

[root@localhost ~]# docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 12
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1

**Comment by yhmo** [comment]
Similar to this https://cloud.tencent.com/developer/article/1356935, related with cpu instruction.
And a similar issue #4095, also caused by cpu instruction, but we didn't get the root cause .

**Comment by yhmo** [comment]
@yucongshub 
Can you try run milvus on another machine? I guess the milvus cannot compatible with some kinds of cpu.

**Comment by yucongshub** [comment]
> @yucongshub
> Can you try run milvus on another machine? I guess the milvus cannot compatible with some kinds of cpu.

Thanks.I'll try another machine.

**Comment by shengjun1985** [comment]
If you meet more problems, please continue to contact our community.
