### ISSUE TITLE
Auto flush did not be triggered when nb >=32000

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#5837]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Auto flush did not be triggered when nb <70000

**Steps/Code to reproduce behavior**
Code:
from pymilvus_orm import CollectionSchema, FieldSchema
from pymilvus_orm import Collection
from pymilvus_orm import connections
from pymilvus_orm.types import DataType
from pymilvus_orm import Partition

int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=128)
schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
connections.connect(host="", port="")
import numpy as np
collection = Collection("test_search_collection_binbin_6", schema=schema)
dim = 128
nb = 50000
nq = 1
limit = 1000
import random
default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
>>> collection.partitions
**[{"name": "_default", "description": "", "num_entities": 0}]**
>>> nb = 10000
>>> vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
>>> res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors]
>>> collection.partitions
**[{"name": "_default", "description": "", "num_entities": 0}]**
>>> nb = 10000
>>> vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
>>> res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
>>> collection.partitions
**[{"name": "_default", "description": "", "num_entities": 70000}]**

**Expected behavior**
Auto flush will be triggered when nb >= 32000

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
milvus master
Name: pymilvus
Version: 2.0a1.dev35
Name: pymilvus-orm
Version: 2.0a1.dev31

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
Previously, there was an insertChannelNum parameter in the data_service.yaml file, which indicated how many batches were allocated when inserting. Insert a segment in each batch, and auto flush will be triggered when the data in the segment reaches 32,000 rows. Now we have deleted this parameter.
And for pymilvus-orm users, every time they get num_entities, flush is actually called actively. So no matter when and where, pymilvus-orm users can see all the data.
pymilvus-orm==2.0a1.dev37

**Comment by binbinlv** [comment]
Verified in the following version, it has been fixed. And now the threshold of 32000 for auto flush has been cancelled, each time user get num_entities, flush is actually called actively. 

Name: pymilvus
Version: 2.0a1.dev40
Name: pymilvus-orm
Version: 2.0a1.dev38
