### ISSUE TITLE
Search returns 0 result if manual flush is not be called (num_entities shown is not zero)

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#5845]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Search returns 0 result if manual flush is not be called (auto flush seems not work)
And search returns 0 when partition number is not zero which is correct as inserted

**Steps/Code to reproduce behavior**
Steps:
1 create connection, collection, and insert data
2 load and search [partition number exists and correct, but search return 0 which should return 1000]
3 manual flush, load and search [return 1000 which is correct)

Code:
```
from pymilvus_orm import CollectionSchema, FieldSchema
from pymilvus_orm import Collection
from pymilvus_orm import connections
from pymilvus_orm.types import DataType
from pymilvus_orm import Partition
from pymilvus_orm import utility

int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=128)
schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
connections.connect(host="", port="")
import numpy as np
collection = Collection("test_search_collection_binbin_0", schema=schema)
par = collection.partitions
dim = 128
nb = 80000
nq = 1
limit = 1000
import random
default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
collection.load()
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 80000}]
>>>
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> len(res[0])
0

**>>> utility.get_connection().flush([collection.name])**
>>>
>>> collection.load()
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> len(res[0])
1000
```

**Expected behavior**
Search return the topK values

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
milvus master
Name: pymilvus
Version: 2.0a1.dev35
Name: pymilvus-orm
Version: 2.0a1.dev31

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
It has been fixed on newest master branch.

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/milvus/issues/5865

**Comment by binbinlv** [comment]
Verified in the following vesion, it has been fixed, and now the data could be searched without manual flush. And "num_entities" could be get immediately after insert without manual flush.

Name: pymilvus
Version: 2.0a1.dev40
Name: pymilvus-orm
Version: 2.0a1.dev38

Results:
>>> nb = 3000
>>> res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 3000}]
>>> collection.load()
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> len(res[0])
1000
>>> nb = 10000
>>> vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
>>> res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 13000}]
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> len(res[0])
1000
>>> nb = 80000
>>> vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
>>> res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 93000}]
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> len(res[0])
1000

**Comment by czs007** [comment]
> Verified in the following vesion, it has been fixed, and now the data could be searched without manual flush. And "num_entities" could be get immediately after insert without manual flush.
> 
> Name: pymilvus
> Version: 2.0a1.dev40
> Name: pymilvus-orm
> Version: 2.0a1.dev38
> 
> Results:
> 
> > > > nb = 3000
> > > > res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
> > > > collection.partitions
> > > > [{"name": "_default", "description": "", "num_entities": 3000}]
> > > > collection.load()
> > > > res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
> > > > len(res[0])
> > > > 1000
> > > > nb = 10000
> > > > vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
> > > > res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
> > > > collection.partitions
> > > > [{"name": "_default", "description": "", "num_entities": 13000}]
> > > > res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
> > > > len(res[0])
> > > > 1000
> > > > nb = 80000
> > > > vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
> > > > res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
> > > > collection.partitions
> > > > [{"name": "_default", "description": "", "num_entities": 93000}]
> > > > res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
> > > > len(res[0])
> > > > 1000

Actually, in the implementation of num_entities in the pymilvus-orm package, flush is  called.

**Comment by binbinlv** [comment]
> > Verified in the following vesion, it has been fixed, and now the data could be searched without manual flush. And "num_entities" could be get immediately after insert without manual flush.
> > Name: pymilvus
> > Version: 2.0a1.dev40
> > Name: pymilvus-orm
> > Version: 2.0a1.dev38
> > Results:
> > > > > nb = 3000
> > > > > res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
> > > > > collection.partitions
> > > > > [{"name": "_default", "description": "", "num_entities": 3000}]
> > > > > collection.load()
> > > > > res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
> > > > > len(res[0])
> > > > > 1000
> > > > > nb = 10000
> > > > > vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
> > > > > res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
> > > > > collection.partitions
> > > > > [{"name": "_default", "description": "", "num_entities": 13000}]
> > > > > res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
> > > > > len(res[0])
> > > > > 1000
> > > > > nb = 80000
> > > > > vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
> > > > > res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
> > > > > collection.partitions
> > > > > [{"name": "_default", "description": "", "num_entities": 93000}]
> > > > > res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
> > > > > len(res[0])
> > > > > 1000
> 
> Actually, in the implementation of num_entities in the pymilvus-orm package, flush is called. @binbinlv

OK, thanks.
