### ISSUE TITLE
Search new added empty partition after load returns "partitions have been released"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#5852]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Search new added empty partition returns "partitions have been released"

And in the former test, search is successful and returned 0

**Steps/Code to reproduce behavior**
Code:
from pymilvus_orm import CollectionSchema, FieldSchema
from pymilvus_orm import Collection
from pymilvus_orm import connections
from pymilvus_orm.types import DataType
from pymilvus_orm import Partition
from pymilvus_orm import utility

int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=128)
schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
connections.connect(host="", port="")
import numpy as np
collection = Collection("test_search_collection_binbin_0", schema=schema)
par = collection.partitions
dim = 128
nb = 80000
nq = 1
limit = 1000
import random
default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
utility.get_connection().flush([collection.name])
collection.load()
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> len(res[0])
1000

collection.create_partition(partition_name="search_partition_1", description="search partition")

>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 50000}, {"name": "search_partition_1", "description": "", "num_entities": 0}]

collection.load()

>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0", ["search_partition_1"])
Error: <BaseException: (code=1, message=partitions have been released , collectionID = 425717734546017601

**Expected behavior**
Search successfully and return 0

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
Name: pymilvus
Version: 2.0a1.dev35
Name: pymilvus-orm
Version: 2.0a1.dev31

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
Maybe it has been fixed, lease retest it.

**Comment by binbinlv** [comment]
Verified in the following version, it has been fixed.

Name: pymilvus
Version: 2.0a1.dev40
Name: pymilvus-orm
Version: 2.0a1.dev38

Results:

>>> collection.create_partition(partition_name="search_partition_1", description="search partition")
{"name": "search_partition_1", "description": "search partition", "num_entities": 0}
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 3000}, {"name": "search_partition_1", "description": "", "num_entities": 0}]
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0", ["search_partition_1"])
>>> len(res[0])
0
