### ISSUE TITLE
The value of retry times is too big

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#5857]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
    def _wait_for_healthy(self, timeout=300, retry=250):
```
**Steps/Code to reproduce behavior**
The client will never return if the server can not be connected, user should know this issue asap.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yanliang567** [comment]
I prefer a smart retry with times and timeout, say 30s or 5 retries, return once either one reached

**Comment by cydrain** [comment]
In Minio, if connection lost, it will re-connect with increasing interval time:
100ms, 200ms, 500ms, 1s, 2s, 5s, 10s
if still fail to connect, system error out.

We can use this kind of retry mechanism.

**Comment by yanliang567** [comment]
@czs007 any updates?
