### ISSUE TITLE
New inserted data could not be searched except for loading again

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#5858]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
New inserted data could not be searched except for loading again
[ load() has been run when inserting the origin data]

**Steps/Code to reproduce behavior**
Steps:
1 create connection and collection
2 insert data and flush
3 load
4 search -- success with correct data number
5 insert data and flush again
6 search [new inserted data could not be searched]
7 load again, [new inserted data could be searched after loading again]

Code:
from pymilvus_orm import CollectionSchema, FieldSchema
from pymilvus_orm import Collection
from pymilvus_orm import connections
from pymilvus_orm.types import DataType
from pymilvus_orm import Partition
from pymilvus_orm import utility

int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=128)
schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
connections.connect()
import numpy as np
collection = Collection("test_search_collection_binbin_2", schema=schema)
dim = 128
nb = 500
nq = 1
limit = 1000
import random
default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
utility.get_connection().flush([collection.name])

>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 500}]

collection.load()
res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> len(res[0])
500

nb=300
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
utility.get_connection().flush([collection.name])

>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 800}]

res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")

>>> len(res[0])
500

collection.load()
res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")

>>> len(res[0])
800

**Expected behavior**
new inserted data could be searched without loading again

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
Milvus master
Name: pymilvus
Version: 2.0a1.dev35
Name: pymilvus-orm
Version: 2.0a1.dev31

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by binbinlv** [comment]
Verified, and fixed.

Name: pymilvus
Version: 2.0a1.dev52
Name: pymilvus-orm
Version: 2.0a1.dev58
milvus-master

Results:
>>> res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 500}]
>>>
>>>
>>> collection.load()
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> len(res[0])
500
>>> nb=300
>>> vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
>>> res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 800}]
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>>
>>> len(res[0])
800

**Comment by binbinlv** [comment]
Now using pymilvus, it is good.  And the action is that new data could be searched after insert instantly without a flush again between insert and search. 

But if uses pymilvus-orm, it still needs a flush after insert new data (between new insert and search)

The action of pymilvus-orm and pymilvus is not consistent here, need reopen to have a look. 

@xige-16 could you or anyone please help to have a look?

On pymilvus, the new data could be searched after insert instantly without a flush again between insert and search:

>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> len(res[0])
500
>>> nb=300
>>> vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
>>> res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> len(res[0])
800

But using pymilvus-orm:
test case: test20/python_client/testcases/test_search.py::TestCollectionSearch::test_search_new_data

original case: fail 
limit(topK) searched (500) is not equal with expected (800)

If add a flush operation between new insert and search (like the following case), it is good.
    def test_search_new_data(self):
        """
        target: test search new inserted data without load
        method: 1 search the collection
                2 insert new data
                3 search the collection without load again
        expected: new data should be searched
        """
        log.info("test_search_new_data: search new data without another load")
        # 1. initialize with data
        limit = 1000
        nb_old = 500
        collection_w = self.init_collection_general(prefix, True, nb_old)[0]
        # 2. search for original data after load
        vectors = [[random.random() for _ in range(default_dim)] for _ in range(default_nq)]
        log.info("test_search_new_data: searching for original data after load")
        collection_w.search(vectors[:default_nq], default_search_field,
                            default_search_params, limit, default_search_exp,
                            check_task=CheckTasks.check_search_results,
                            check_items={"nq": default_nq,
                                         "limit": nb_old})
        # 3. insert new data
        nb_new = 300
        cf.insert_data(collection_w, nb_new, False)
        par = collection_w.partitions
        log.info(par)
        # 4. search for new data without load
        collection_w.search(vectors[:default_nq], default_search_field,
                            default_search_params, limit, default_search_exp,
                            check_task=CheckTasks.check_search_results,
                            check_items={"nq": default_nq,
                                         "limit": nb_old+nb_new})

**Comment by binbinlv** [comment]
This issue only exists on standalone version, distributed version is good.

**Comment by bigsheeper** [comment]
Did you set the `queryNode.gracefulTime` to 0 in milus.yaml?  I'v run this test on standalone and cluster also, and it all passed . @binbinlv

**Comment by binbinlv** [comment]
@ I remember I have tried this value, but I will retry and confirm it later. @bigsheeper

**Comment by xige-16** [comment]
If the issue has been fixed, please close it. @binbinlv

**Comment by binbinlv** [comment]
Tried with setting queryNode.gracefulTime as 0, but it still exists, please have a look again, Logs are pasted below if it could be a help. Thanks. @bigsheeper 
Run test case:
tests20/python_client/testcases/test_search.py::TestCollectionSearch::test_search_new_data

Results:
[2021-07-14 03:06:18 - ERROR - ci_test]: search_results_check: limit(topK) searched (500) is not equal with expected (800) (func_check.py:175)

Logs:
[log.tar.zip](https://github.com/milvus-io/milvus/files/6813263/log.tar.zip)

**Comment by binbinlv** [comment]
There is a queryNode.gracefulTime in milvus.yaml which is default as 1000ms. Then after insert, it is allowed for search not to get the data in 1s. But now this value queryNode.gracefulTime is not exposed to be modified, so it will not work even modify this value to 0 in milvus.yaml.

After time.sleep(1) between new insert and search, this case passed, so work as design and close this issue.

But If the design of "gracefulTime" is exposed to users, then this value should be exposed to be modifiable, thanks. new issue was recorded for this (issue #6514) @xige-16
