### ISSUE TITLE
Milvus installation guide 1.1.1, GPU and CPU have wrong docker image.

### ISSUE THREAD

**Issue by ss892714028** [milvus-io/milvus#5861]
**Please state your issue using the following template and, most importantly, in English.**
Milvus installation guide GPU and CPU wrong image.

**Location of incorrect documentation**
Provide links and line numbers if applicable.
https://milvus.io/docs/v1.1.1/milvus_docker-cpu.md
https://milvus.io/docs/v1.1.1/milvus_docker-gpu.md

**Describe the problems or issues found in the documentation**
A clear and concise description of what you found to be incorrect.
on gpu side:
sudo docker pull milvusdb/milvus:1.1.1-cpu-d061621-330cc6
on cpu side:
sudo docker pull milvusdb/milvus:1.1.1-gpu-d061621-330cc6

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.
exchange the two would be fine.

**Comment by LocoRichard** [comment]
Thank you, we have fix issue.
