### ISSUE TITLE
Chinese version of Milvus installation guide, wrong milvus version.

### ISSUE THREAD

**Issue by ss892714028** [milvus-io/milvus#5862]
**Please state your issue using the following template and, most importantly, in English.**
Chinese version of Milvus installation guide, wrong milvus version.

**Location of incorrect documentation**
Provide links and line numbers if applicable.
https://milvus.io/cn/docs/v1.1.1/milvus_docker-cpu.md
https://milvus.io/cn/docs/v1.1.1/milvus_docker-gpu.md
**Describe the problems or issues found in the documentation**
A clear and concise description of what you found to be incorrect.
sudo docker pull milvusdb/milvus:1.1.0-gpu-d050721-5e559c
sudo docker pull milvusdb/milvus:1.1.0-cpu-d050721-5e559c

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.
should be milvus:1.1.1 on both
---

## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken:

**Comment by LocoRichard** [comment]
Thank you, we have fix the issue
