### ISSUE TITLE
Collection primary field changed

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5873]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

1. create collection A with fields [int_field_one, int_field_two, vec_field], and primary field is `int_field_one`
2. create collection B with duplicate name of A and new primary_field `int_field_two`
3. collection A's primary_field become `int_field_two`??
```
    def test_collection_dup_name_new_primary(self):
        self._connect()
        c_name = cf.gen_unique_str(prefix)
        int_field_one = cf.gen_int64_field()
        int_field_two = cf.gen_int64_field(name="int2")
        fields = [int_field_one, int_field_two, cf.gen_float_vec_field()]
        schema = cf.gen_collection_schema(fields, primary_field=int_field_one.name)
        collection_w = self.init_collection_wrap(name=c_name, schema=schema,
                                                 check_task=CheckTasks.check_collection_property,
                                                 check_items={exp_name: c_name, exp_schema: schema,
                                                              exp_primary: int_field_one.name})
        new_schema = cf.gen_collection_schema(fields, primary_field=int_field_two.name)
        error = {ct.err_code: 0, ct.err_msg: "The collection already exist, but the schema isnot the same as the "
                                             "schema passed in"}
        self.collection_wrap.init_collection(c_name, schema=new_schema, check_task=CheckTasks.err_res,
                                             check_items=error)
        assert collection_w.primary_field.name == int_field_one.name
```
```
testcases/test_collection.py:152 (TestCollectionParams.test_collection_dup_name_new_primary)
int2 != int64

Expected :int64
Actual   :int2
<Click to see difference>
```
The reason is the last line of the orm code below. `self._schema = schema`
```
    def __init__(self, name, schema=None, **kwargs):
        self._name = name
        self._kwargs = kwargs
        conn = self._get_connection()
        has = conn.has_collection(self._name)
        if has:
            resp = conn.describe_collection(self._name)
            server_schema = CollectionSchema.construct_from_dict(resp)
            if schema is None:
                self._schema = server_schema
            else:
                if not isinstance(schema, CollectionSchema):
                    raise SchemaNotReadyException(0, "Schema type must be schema.CollectionSchema.")
                if server_schema != schema:
                    raise SchemaNotReadyException(0, "The collection already exist, but the schema is"
                                                  "not the same as the schema passed in.")
                self._schema = schema
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus              2.0a1.dev39
 pymilvus-orm          2.0a1.dev33

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by sunby** [comment]
The `fields` variable is modified in the first `gen_collection_schema`. The `int_field_one` field's `is_primary` is changed to True. After the second `gen_collection_schema`, the `int_field_two.is_primary` is set to True. According to [primary_field in orm](https://github.com/milvus-io/pymilvus-orm/blob/c3ade8588b0bd708f239c0a0f6959881b1773812/pymilvus_orm/schema.py#L61) , the first collections's primary field is also changed to `int_field_two`.

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/170
