### ISSUE TITLE
docker pull failed from registry.zilliz.com

### ISSUE THREAD

**Issue by shicript** [milvus-io/milvus#5883]
Install with Docker-Compose distribute milvus failed.
Screen shot:
![截屏2021-06-19 上午9 35 05](https://user-images.githubusercontent.com/24455669/122627392-a33f8480-d0e1-11eb-9ed9-0b73a9556fa6.png)

**Comment by jeffoverflow** [comment]
Milvus 2.0 docker image has not been released yet, it will be uploaded to Dockerhub soon.
