### ISSUE TITLE
stop server failed

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#590]
**Describe the bug**
stop_server.sh can not stop server
```
root@6e61026bea39:/opt/milvus/scripts# bash stop_server.sh 
Milvus server closed successfully!
root@6e61026bea39:/opt/milvus/scripts# 
```
but not really stop

**Steps/Code to reproduce behavior**

**Expected behavior**

**Environment details**
0.6.0

**Screenshots**

**Additional context**

**Comment by del-zhenwu** [comment]
Some warning message is needed

**Comment by yhmo** [comment]
The root cause is: background build index task not yet finish.

**Comment by del-zhenwu** [comment]
close it
