### ISSUE TITLE
mishard: `not found in metadata` during search an empty collection

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#5923]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```

=================================== FAILURES ===================================
_____________ TestSearchParamsInvalid.test_search_with_2049_nprobe _____________

self = <test_search.TestSearchParamsInvalid object at 0x7fc35c14c8d0>
connect = <milvus.client.stub.Milvus object at 0x7fc36274b828>
collection = 'test_search_HYITMj8b'

    def test_search_with_2049_nprobe(self, connect, collection):
        '''
        target: test search function, with 2049 nprobe in GPU mode
        method: search with nprobe
        expected: status not ok
        '''
        if str(connect._cmd("mode")[1]) == "CPU":
            pytest.skip("Only support GPU mode")
        for index in gen_simple_index():
            if index["index_type"] in [IndexType.IVF_PQ, IndexType.IVFLAT, IndexType.IVF_SQ8, IndexType.IVF_SQ8H]:
                index_type = index["index_type"]
                index_param = index["index_param"]
                self.init_data(connect, collection)
                connect.create_index(collection, index_type, index_param)
                nprobe = 2049
                search_param = {"nprobe": nprobe}
                query_vecs = gen_vectors(nprobe, dim)
                status, result = connect.search(collection, top_k, query_vecs, params=search_param)
>               assert status.OK()
E               AssertionError: assert False
E                +  where False = <bound method Status.OK of Status(code=4, message='test_search_HYITMj8b:[] not found in metadata')>()
E                +    where <bound method Status.OK of Status(code=4, message='test_search_HYITMj8b:[] not found in metadata')> = Status(code=4, message='test_search_HYITMj8b:[] not found in metadata').OK

entity/test_search.py:1303: AssertionError
```
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
Mishards access MySQL to collection segments information, but Milvus server can change metadata at the same time. For example, mishards performs a SQL statement to collection segments information of a collection, but at the same time the milvus server drop the collection, delete the collection from metadata, then the Mishards could encounter this error.

This bug could not be fixed due to the limitation of mishards internal machinery. We recommend Mishards users use Milvus v2.0 to replace Mishards.
