### ISSUE TITLE
Different parameter names are input for collection.search and parition.search

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#5934]
**Describe the bug**
Different parameter names are input for collection.search and parition.search

**Steps/Code to reproduce behavior**
Collection.search(self, data, anns_field, **param**, limit, expr=None, partition_names=None, output_fields=None, timeout=None, **kwargs):
Partition.search(self, data, anns_field, **params**, limit, expr=None, output_fields=None, timeout=None,
               **kwargs):

**Expected behavior**
the two search param should be same, or it confused users.

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
pymilvus-orm                       2.0a1.dev31

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/178

**Comment by xiaocai2333** [comment]
pymilvus-orm==2.0a1.dev42

**Comment by czs007** [comment]
> pymilvus-orm==2.0a1.dev42

@yanliang567 
@xiaocai2333 remember to notify the author

**Comment by yanliang567** [comment]
verified.
