### ISSUE TITLE
When init a collection schema with fields whose is_primary and auto_id are both True, its auto_id is False

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5935]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
1. define int_field with is_primary=True and auto_id=True
2. define vec_field with is_primary=False
3. init a schema with int_field and vec_field
4. verify schema auto_id is True
```
    def test_collection_auto_id_in_field_schema(self):
        """
        target: test collection with auto_id in field schema
        method: specify auto_id True in field schema
        expected: todo
        """
        self._connect()
        log.debug("debug")
        # int_field = cf.gen1_int64_field("int", is_primary=True, auto_id=True)
        int_field = cf.gen_int64_field(is_primary=True, auto_id=True)
        log.debug(f'int_field auto_id: {int_field.auto_id}')
        vec_field = cf.gen_float_vec_field(name='vec')
        schema, _ = self.collection_schema_wrap.init_collection_schema([int_field, vec_field])
        log.debug(schema)
        assert schema.auto_id
```
```
int_field auto_id: True (test_collection.py:622)
{"auto_id": false, "description": "", "fields": [{"name": "int64", "description": "", "type": 5, "is_primary": true, "auto_id": false}, {"name": "vec", "description": "", "type": 101, "params": {"dim": 128}}]} (test_collection.py:625)

```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus              2.0a1.dev42
 pymilvus-orm          2.0a1.dev39

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/178

**Comment by xiaocai2333** [comment]
pymilvus-orm==2.0a1.dev42
