### ISSUE TITLE
data insertion IDS does not support special characters 

### ISSUE THREAD

**Issue by Chenhongcai800** [milvus-io/milvus#5936]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
In business, IDS has special characters, such as "700084-3062-916866", IDS becomes "700084" after inserting data, causing error

**Steps/Code to reproduce behavior**
 Execute the order ：
curl -X POST "http://10.27.240.7/collections/rcm_collection/vectors" -H "accept: application/json" -H "Content-Type: application/json" -d "{\"ids\":[\"700084-3062-916866\"],\"vectors\":[[0.04229329526424408, 0.05360675975680351, -0.00041014672024175525]]}"

**Expected behavior**
 When searching, the data of IDS: '700084-3062-916866' can be found 

**Method of installation**
- [√ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 1.1.0

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by shengjun1985** [comment]
We will support string id in v2.0.
https://github.com/milvus-io/milvus/issues/5603#issuecomment-855180248

**Comment by shengjun1985** [comment]
Please allow me to close the issue.
And let‘s trace it in 5603.
If you have more questions, please continue to contact our community.
