### ISSUE TITLE
search in collection with empty partition should not throw exception

### ISSUE THREAD

**Issue by bigsheeper** [milvus-io/milvus#5940]
**search in collection with empty partition should not throw exception**

**Describe the bug**
search in collection (no partitions specifed) with empty partition should not throw exception

**Steps/Code to reproduce behavior**
tests:
collection/test_load_collection.py::TestLoadCollection::test_load_collection_release_all_partitions
collection/test_load_collection.py::TestReleaseAdvanced::test_release_partition_during_searching 
should not throw exception

**Expected behavior**
test pass

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [x] Build from source

- Milvus version (master)

**Comment by binbinlv** [comment]
#5948
