### ISSUE TITLE
An exception should be thrown when creating a schema with inconsistent auto_id

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5943]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
inconsistent auto_id means: auto_id=True in FieldSchema, auto_id=False in CollectionSchema
```
     def test_collection_auto_id_inconsistent(self):
        """
        target: test collection auto_id with both collection schema and field schema
        method: 1.set primary field auto_id=True in field schema 2.set auto_id=False in collection schema
        expected: raise exception
        """
        self._connect()
        int_field = cf.gen_int64_field(is_primary=True, auto_id=True)
        vec_field = cf.gen_float_vec_field(name='vec')
        error = {ct.err_code: 0, ct.err_msg: "Primary key field can only be one"}
        schema, _ = self.collection_schema_wrap.init_collection_schema([int_field, vec_field], auto_id=False,
                                                                       check_task=CheckTasks.err_res, check_items=error)
```
No exception is thrown.
```
Response : {"auto_id": false, "description": "", "fields": [{"name": "int64", "description": "", "type": 5, "is_primary": true}, {"name": "vec", "description": "", "type": 101, "params": {"dim": 128}}]}  (api_request.py:19)
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus              2.0a1.dev42
 pymilvus-orm          2.0a1.dev39

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/178

**Comment by xiaocai2333** [comment]
pymilvus-orm==2.0a1.dev42
