### ISSUE TITLE
Should an exception be thrown or auto_id is False when auto_id is None?

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5945]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

1. `auto_id=None` in FieldSchema, an exception was thrown
```
    def test_collection_auto_id_none(self):
        """
        target: test collection with auto_id is None
        method: set auto_id=None
        expected:
        """
        self._connect()
        int_field = cf.gen_int64_field(is_primary=True, auto_id=None)
        vec_field = cf.gen_float_vec_field(name='vec')
        schema, _ = self.collection_schema_wrap.init_collection_schema([int_field, vec_field])
        log.debug(schema.auto_id)
```
```
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus_orm/schema.py", line 189, in __init__
    raise ParamError("Param auto_id must be bool type.")
pymilvus_orm.exceptions.ParamError: Param auto_id must be bool type.
```
2. `auto_id=None` in Collection Schema, `schema.auto_id=False`
```
    def test_collection_auto_id_none(self):
        self._connect()
        int_field = cf.gen_int64_field(is_primary=True)
        vec_field = cf.gen_float_vec_field(name='vec')
        schema, _ = self.collection_schema_wrap.init_collection_schema([int_field, vec_field], auto_id=None)
        log.debug(schema.auto_id)
```
```
{"auto_id": false, "description": "", "fields": [{"name": "int64", "description": "", "type": 5, "is_primary": true, "auto_id": false}, {"name": "vec", "description": "", "type": 101, "params": {"dim": 128}}]} 
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus              2.0a1.dev42
 pymilvus-orm          2.0a1.dev39

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/178
Throw an exception when auto_id=None.

**Comment by xiaocai2333** [comment]
pymilvus-orm==2.0a1.dev42
