### ISSUE TITLE
Milvus is crashed when searching after releasing partitions

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#5949]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Milvus is crashed when searching after releasing partitions

**Steps/Code to reproduce behavior**

Run test case under tests:
collection/test_load_collection.py::TestReleaseAdvanced::test_release_partition_during_searching

Modify the code as the following for fixing issue #5940,

    def test_release_partition_during_searching(self, connect, collection):
        """
        target: test release partition during searching
        method: insert entities into partition, flush and load partition, release partition during searching
        expected:
        """
        nq = 1000
        top_k = 1
        connect.create_partition(collection, default_tag)
        query, _ = gen_query_vectors(field_name, default_entities, top_k, nq)
        connect.insert(collection, default_entities, partition_name=default_tag)
        connect.flush([collection])
        connect.load_partitions(collection, [default_tag])
        res = connect.search(collection, query, _async=True)
        connect.release_partitions(collection, [default_tag])
        res = connect.search(collection, default_single_query)
        assert len(res[0]) == 0

if add "connect.flush([collection])"  after  "connect.release_partitions(collection, [default_tag])", milvus will not crash

**Expected behavior**
No crash for milvus

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
master

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by bigsheeper** [comment]
@binbinlv

**Comment by binbinlv** [comment]
Test on milvus master latest, it is fixed.
