### ISSUE TITLE
Milvus is crashed when inserting data with multiple datatype fields

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#5951]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Milvus is crashed when inserting data with multiple datatype fields( int64, int 32, int 16, int 8, float, float_vector)

**Steps/Code to reproduce behavior**
Code:
from pymilvus_orm import CollectionSchema, FieldSchema
from pymilvus_orm import Collection
from pymilvus_orm import connections
from pymilvus_orm.types import DataType
from pymilvus_orm import Partition

int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
int32_field = FieldSchema(name="int32", dtype=DataType.INT32)
int16_field = FieldSchema(name="int16", dtype=DataType.INT16)
int8_field = FieldSchema(name="int8", dtype=DataType.INT8)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=128)

connections.connect(host="", port="")
import numpy as np
schema = CollectionSchema(fields=[int64_field, int32_field, int16_field, int8_field, float_field, float_vector])
collection = Collection("test_search_collection_binbin_01", schema=schema)
collection.partitions
[{"name": "_default", "description": "", "num_entities": 0}]

dim = 128
nb = 3000
nq = 1
limit = 1000
import random
default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
data = [[i for i in range(nb)], [np.int32(i) for i in range(nb)], [np.int16(i) for i in range(nb)], [np.int8(i) for i in range(nb)], [np.float32(i) for i in range(nb)], vectors]
res = collection.insert(data)

Addr [***] bulk_insert
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1624281311.894187000","description":"Error received from peer ipv4:172.22.255.155:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
>
	{'API start': '2021-06-21 13:15:11.806941', 'RPC start': '2021-06-21 13:15:11.807852', 'RPC error': '2021-06-21 13:15:11.894871'}

**Expected behavior**
insert successfully without errors

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
milvus-master
Name: pymilvus
Version: 2.0a1.dev40
Name: pymilvus-orm
Version: 2.0a1.dev38

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by DragonDriver** [comment]
Already fixed. PTAL @binbinlv

**Comment by binbinlv** [comment]
Verified in the following version, and it has been fixed.
milvus:master
Name: pymilvus
Version: 2.0a1.dev43
Name: pymilvus-orm
Version: 2.0a1.dev45

Results:
>>> from pymilvus_orm import CollectionSchema, FieldSchema
>>> from pymilvus_orm import Collection
>>> from pymilvus_orm import connections
>>> from pymilvus_orm.types import DataType
>>> int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
>>> int32_field = FieldSchema(name="int32", dtype=DataType.INT32)
>>> int16_field = FieldSchema(name="int16", dtype=DataType.INT16)
>>> int8_field = FieldSchema(name="int8", dtype=DataType.INT8)
>>> float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
>>> float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=128)
>>> connections.connect()
<pymilvus.client.stub.Milvus object at 0x7fe0b9838ba8>
>>> import numpy as np
>>> schema = CollectionSchema(fields=[int64_field, int32_field, int16_field, int8_field, float_field, float_vector])
>>> collection = Collection("test_search_collection_binbin_01", schema=schema)
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 0}]
>>> dim = 128
>>> nb = 3000
>>> nq = 1
>>> limit = 1000
>>> import random
>>> default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
>>> vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
>>> data = [[i for i in range(nb)], [np.int32(i) for i in range(nb)], [np.int16(i) for i in range(nb)], [np.int8(i) for i in range(nb)], [np.float32(i) for i in range(nb)], vectors]
>>> res = collection.insert(data)
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 3000}]
