### ISSUE TITLE
Query hang  if MILVUS_CLUSTER_ENABLED=true

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#5962]
**Describe the bug**
Query hang without response if Milvus deployed with  MILVUS_CLUSTER_ENABLED=true 
(not repro if standalone)

**Steps/Code to reproduce behavior**
collection schema: int64, float, vector
collection with 1200 entities
term_expr = 'int64 in [1,2,3,4,5]'
collection_w.query(term_expr)

can easily run testcase test_query in tests20/testcases/

**Expected behavior**
query response with results

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
master 2.0

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by fishpenguin** [comment]
Fixed in [pr6037](https://github.com/milvus-io/milvus/pull/6037)

**Comment by yanliang567** [comment]
verify on Built:     
Thu Jun 24 08:46:20 UTC 2021
GitCommit: 0f409da
