### ISSUE TITLE
No exception is thrown when inserting duplicate data in the primary field

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5977]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
auto_id=False
```
    def test_construct_auto_id_false_repeated_values(self):
        """
        target: test construct with false auto_id and repeated values
        method: auto_id=False, primary field values repeated
        expected: todo
        """
        self._connect()
        nb = 100
        df = cf.gen_default_dataframe_data(nb)
        df.iloc[1:, 0] = 1
        log.debug(df.head(5))
        # error = {ct.err_code: 0, ct.err_msg: "Primary key type must be DataType.INT64"}
        self.collection_wrap.construct_from_dataframe(cf.gen_unique_str(prefix), df,
                                                      priamry_field=ct.default_int64_field_name, auto_id=False)
        log.debug(self.collection_wrap.num_entities)
```
No exception is thrown and all entities are inserted `num_entities = nb =100`

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus              2.0a1.dev43
 pymilvus-orm          2.0a1.dev40

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yanliang567** [comment]
by design in bug triage meeting
