### ISSUE TITLE
[Chaos] Build Index hang without timeout after indexnode deleted and restart

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#5993]
**Describe the bug**
Build Index hang without timeout after indexnode deleted and restart

**Steps/Code to reproduce behavior**
1. deploy Milvus with cluster mode
2. insert 5000 entities into a collection
3. build index {"index_type": "IVF_SQ8", "metric_type": "L2", "params": {"nlist": 64}}
4. delete indexnode pod

**Expected behavior**
build index fails with an error immediately, at least there should be a timeout.

**Actually**
build index hang even after indexnode pod restarted

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

- Milvus version (master or released version)
Milvus 2.0 cluster deployment
Built:     Tue Jun 22 03:36:05 UTC 2021
GitCommit: 438e7fb4d

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
Can you paste the indexcoord's log here?

**Comment by yanliang567** [comment]
indexnode log after restarted:
[indexnode1.log](https://github.com/milvus-io/milvus/files/6700209/indexnode1.log)

**Comment by yanliang567** [comment]
on Built:     Wed Jun 23 07:31:13 UTC 2021      GitCommit: 9ebca59
raise BaseException(Status.UNEXPECTED_ERROR, "create index failed")
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=create index failed)>
 (api_request.py:22)
[2021-06-23 20:51:17,392 - ERROR - ci_test]: (api_response) [Milvus API Exception]<function api_request at 0x7f88905a8430>: <BaseException: (code=1, message=create index failed)> (api_request.py:23)

Logs:
[indexcoord2.log](https://github.com/milvus-io/milvus/files/6701967/indexcoord2.log)
[indexnode2.log](https://github.com/milvus-io/milvus/files/6701977/indexnode2.log)

**Comment by czs007** [comment]
One guess is that the retry time is too long. The previous implementation was to retry 300 times, each time waiting for 6 seconds, about half an hour. Looks like it's stuck. please refer to this #6083 and retry. @yanliang567

**Comment by yanliang567** [comment]
will retry after #6083 merged.

**Comment by yanliang567** [comment]
not repro on build master-20210624-cea83dd

**Comment by yanliang567** [comment]
reproduced on master-20210719-b98b30b
when running test_chaos.py with indexnode chaos. (keep building index while chaso)
checking the indexcoord.log, it trying to connect the indexnode by ip 10.97.4.171, while the actual indexnode ip is 10.97.4.182. so building index hangs

**Comment by yanliang567** [comment]
/assign @xiaocai2333 
the datanode had the same issue before, and @sunby fixed it.

**Comment by xiaocai2333** [comment]
Please paste the whole indexcoord.log here. @yanliang567

**Comment by czs007** [comment]
As you have mentioned, build index hang even after index node pod restarted

It is related to the startup logic, and the logic of trying to reconnect to invalid addresses should not be repeated.
Please wait for @godchen0212 's pull request to refactor the Session.

**Comment by ThreadDao** [comment]
Now index building does not hang and returns a timeout error. I will close the issue first.
