### ISSUE TITLE
Search return partition_tag

### ISSUE THREAD

**Issue by sevenold** [milvus-io/milvus#6002]
The search result return to the partition_tag where the searched vector is located.

**Comment by zhaoning1987** [comment]
Yes, the support of this feature will be really helpful. Let's consider following scenario: every vectors have an attribute named color, we insert red vectors in a partition named 'red' while blue vectors in partition 'blue'. Searching topK among red vectors will be simply searching topK in partition 'red', but if we need search topK in whole collection (no matter what color), there is no way to get the partitions of these K results, therefore we cannot not get the colors of these K results.

**Comment by yhmo** [comment]
Neither v2.0 not v1.0 can do this now.
To support this feature, the search result structure need to be refined.
Currently search result structure is:
```
[
    nq_1:[{top1_id, distance}, {top2_id, distance}, ...]
    nq_2:[{top1_id, distance}, {top2_id, distance}, ...]
    ......
]
```
To return more info, the result structure should be:
```
[
    nq_1:[{top1_id, distance, attribute_1, attribute_2...}, {top2_id, distance, attribute_1, attribute_2...}, ...]
    nq_2:[{top1_id, distance, attribute_1, attribute_2...}, {top2_id, distance, attribute_1, attribute_2...}, ...]
    ......
]
```

**Comment by sevenold** [comment]
possibly get the partition_tag by id?
@yhmo

**Comment by yhmo** [comment]
> possibly get the partition_tag by id?
> @yhmo

Get entity attributes by id is available in v2.0. We provide this api:
`def query(self, collection_name, expr, output_fields)`

User can define a field to store partition tag in collection schema, then insert entities with their partition tag as an attribute. Call the query() to specify the field to return entity's partition tag.

**Comment by yhmo** [comment]
@sevenold 
I just confirmed, in v2.0, the search() api can return specified attributes.
For example, user define a collection with two fields: vector field "vec_data" and an int64 field "partition_id", then insert entities with vector data and its partition_id. Because the first version of 2.0 not support string field, user need to maintain a map between string partition_tag to integer partition_id.
When search, there is a parameter to specify returned fields, user can specify "partition_id" to return. By the partition_id, user can know which partition this entity belong.

**Comment by xiaofan-luan** [comment]
> rch result return to the partition_tag where the searched vector is located.

how about put partition tag in one field? then you can get entity by id

**Comment by sevenold** [comment]
> > rch result return to the partition_tag where the searched vector is located.
> 
> how about put partition tag in one field? then you can get entity by id

sure, search vector return id then get tag by id ?

**Comment by xiaofan-luan** [comment]
> > > rch result return to the partition_tag where the searched vector is located.
> > 
> > 
> > how about put partition tag in one field? then you can get entity by id
> 
> sure, search vector return id then get tag by id ?

when search you can specify the output field, if you duplicate tag into field then you can retrieve partition tag.

**Comment by yhmo** [comment]
Solution:
1. define a filed name "partition_tag"
2. specify "partition_tag" as an output field when search

Inactive and close.
