### ISSUE TITLE
Insert twice with true auo_id to return duplicate primary keys

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#6007]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
1. create a collection with auto_id=True
2. insert nb=10 entities twice. The primary keys returned by two inserts have duplicate values
```
@pytest.mark.tags(CaseLabel.L1)
    def test_insert_twice_auto_id_true(self):
        """
        target: test insert ids fields twice when auto_id=True
        method: 1.create collection with auto_id=True 2.insert twice
        expected: verify primary_keys unique
        """
        c_name = cf.gen_unique_str(prefix)
        schema = cf.gen_default_collection_schema(auto_id=True)
        collection_w = self.init_collection_wrap(name=c_name, schema=schema)
        df = cf.gen_default_dataframe_data(10)
        df.drop(ct.default_int64_field_name, axis=1, inplace=True)
        mutation_res, _ = collection_w.insert(data=df)
        log.debug(mutation_res.primary_keys)
        mutation_res_1, _ = collection_w.insert(data=df)
        log.debug(mutation_res_1.primary_keys)
```
```
[425817585676914248, 425817585676914249, 425817585676914250, 425817585676914251, 425817585676914252, 425817585676914253, 425817585676914254, 425817585676914255, 425817585676914256, 425817585676914257] (test_insert.py:483)

[425817585676914251, 425817585676914252, 425817585676914253, 425817585676914254, 425817585676914255, 425817585676914256, 425817585676914257, 425817585676914258, 425817585676914259, 425817585676914260] (test_insert.py:485)
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus              2.0a1.dev44
 pymilvus-orm          2.0a1.dev45

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by czs007** [comment]
@ThreadDao  please recheck this.
