### ISSUE TITLE
[Chaos] Search hang after querynode deleted and restarted

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#6032]
**Describe the bug**
Search hang after querynode deleted and restarted

**Steps/Code to reproduce behavior**
1. deploy Milvus with cluster mode
2. delete querynode pod and wait until it restarted to running state
3. do a search  (you can run test_partition_release_after_collection_released in tests20/python_client/testcases/test_partition.py)

**Expected behavior**
Search return with results 

- Milvus version (master or released version)
Milvus 2.0
Built:     Wed Jun 23 07:31:13 UTC 2021
GitCommit: 9ebca59

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**
Add any other context about the problem her
[querynode1.log](https://github.com/milvus-io/milvus/files/6700791/querynode1.log)
e.

**Comment by xige-16** [comment]
I can't reproduce it locally. I restart querynode and rerun test test_partition_release_after_collection_released successfully. Trouble you to check again. @yanliang567

**Comment by yanliang567** [comment]
not repro on
Built:     Thu Jun 24 08:46:20 UTC 2021
GitCommit: 0f409da
