### ISSUE TITLE
upgrade cuda version to cuda-11 

### ISSUE THREAD

**Issue by EitanZ-GSI** [milvus-io/milvus#6038]
**Is your feature request related to a problem? Please describe.**
i wish Milvus will support cuda-11 in order to support latest Gpu's devices. 
Gsi compeny perform neural-Hash train in order to convert float32 data set to a binary data set with lower bit demention . 
train is been done using Gpu . 

**Describe the solution you'd like**
upgrade milvus cuda dependency from 10.X to 11.

**Describe alternatives you've considered**
N/A

**Comment by shengjun1985** [comment]
Is it OK that we only release on cuda-10, but providing a compilation option to allow users to compile on cuda-11 by themselves?

**Comment by yhmo** [comment]
The cuda 11 renamed an api, which is invoked by milvus search engine. So we can't build a milvus to compatible with both cuda 11 and 10.x. Except we build two images, one for cuda 11, another for cuda 10.x.

**Comment by shengjun1985** [comment]
The struct `cudaPointerAttributes` is different between cuda-10 and cuda-11.
So the program compiled in one environment may not run in another.

refer to:
[struct cudaPointerAttributes v10.0](https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/structcudaPointerAttributes.html)
[struct cudaPointerAttributes v11.0 ](https://docs.nvidia.com/cuda/archive/11.0/cuda-runtime-api/structcudaPointerAttributes.html)

**Comment by EitanZ-GSI** [comment]
Thanks a lot fot the quick response ! 

Does it means that after the PR will be approved ,  we will be able to compile and start the GPU server using cuda 11 ?

**Comment by shengjun1985** [comment]
Yes. I installed CUDA 11 locally, and the compilation and the running all passed.
The PR is merged. Please test it in branch 1.1.
If you meet any problems, please continue to contact our community.

**Comment by yhmo** [comment]
@EitanZ-GSI 
You can compile milvus 1.1 latest code with cuda 11 by the following steps:
1. `docker pull milvusdb/milvus-gpu-build-env:v0.7.0-ubuntu18.04`
2. `docker run --gpus all -it -p 19530:19530 milvusdb/milvus-gpu-build-env:v0.7.0-ubuntu18.04`
3. `docker exec -it [container id] bash`
4. `wget http://developer.download.nvidia.com/compute/cuda/11.0.2/local_installers/cuda_11.0.2_450.51.05_linux.run`
5. `sh cuda_11.0.2_450.51.05_linux.run`
6. Only select the item "CUDA toolkit" to install
```
CUDA Installer  
│ - [ ] Driver  
│      [ ] 450.51.05 
│ + [X] CUDA Toolkit 11.0  
│   [ ] CUDA Samples 11.0    
│   [ ] CUDA Demo Suite 11.0   
│   [ ] CUDA Documentation 11.0 
│   Options 
│   Install 
```
7. After cuda 11 installed, the /usr/local/cuda is pointint to /usr/local/cuda-11.0
8. `git clone https://github.com/milvus-io/milvus.git`
9. `cd ./milvus/core`
10.` git branch 1.1 remotes/origin/1.1`
11. `git checkout 1.1`
12. `./build.sh -g`
13. After compile finished, modify the ./conf/server_config.yaml
```
  gpu:
    enable: true
    cache.enable: false
    cache_size: 1GB
    gpu_search_threshold: 1
    search_devices:
      - gpu0
```
14. run the script : start_server.sh
15. Use pymilvus client to test create/insert/search, search nq=10

**Comment by yhmo** [comment]
Link to #6315

**Comment by shengjun1985** [comment]
It is supported in branch 1.1.
And the users can compile it locally.
