### ISSUE TITLE
[Chaos] Search fails with exception if querycoord deleted and restarted

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#6040]
**Describe the bug**
Search fails with exception if querycoord deleted and restarted

**Steps/Code to reproduce behavior**
1. deploy Milvus 2.0 with cluster mode
2. delete querycoord pod and wait until it restarted to running state
3. do a search

**Expected behavior**
return successfully with results

**Actually**
Exception:
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=call query coordinator LoadCollection: rpc error: code = Unavailable desc = transport is closing)>

Checking the querycoord pod logs, it displays :
[2021/06/23 11:28:15.395 +00:00] [DEBUG] [impl.go:131] ["LoadCollectionRequest received"] [role=QueryCoord-0] [msgID=425839095480782219] [collectionID=425839208556396545] [schema="name:\"partition__GccrNJOS\" fields:<fieldID:100 name:\"int64\" is_primary_key:true data_type:Int64 > fields:<fieldID:101 name:\"float\" data_type:Float > fields:<fieldID:102 name:\"float_vector\" data_type:FloatVector type_params:<key:\"dim\" value:\"128\" > > "]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x14b4950]

goroutine 205 [running]:
github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).Enqueue(0x0, 0xc00001b750, 0x1, 0x1)
        /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:413 +0x90
github.com/milvus-io/milvus/internal/querycoord.(*QueryCoord).LoadCollection(0xc0002d8b40, 0x24f6760, 0xc00064d470, 0xc000418c40, 0x22b5dc0, 0x2507900, 0x2507760)
        /go/src/github.com/milvus-io/milvus/internal/querycoord/impl.go:161 +0x667
github.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).LoadCollection(0xc0003e47e0, 0x24f6760, 0xc00064d470, 0xc000418c40, 0xc0003e47e0, 0x24ccda0, 0xc0000aef50)
        /go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:254 +0x4d
github.com/milvus-io/milvus/internal/proto/querypb._QueryCoord_LoadCollection_Handler.func1(0x24f6760, 0xc00064d470, 0x2266060, 0xc000418c40, 0x23551f6, 0x2d, 0x24f6760, 0xc00064d470)
        /go/src/github.com/milvus-io/milvus/internal/proto/querypb/query_coord.pb.go:2526 +0x89
github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1(0x24f6760, 0xc00064d200, 0x2266060, 0xc000418c40, 0xc000410c60, 0xc000410c80, 0xc00053cb78, 0x83f4a6, 0x2223380, 0xc00064d200)
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/tracing/opentracing/server_interceptors.go:30 +0xda
github.com/milvus-io/milvus/internal/proto/querypb._QueryCoord_LoadCollection_Handler(0x22b5dc0, 0xc0003e47e0, 0x24f6760, 0xc00064d200, 0xc000415980, 0xc0006422a0, 0x24f6760, 0xc00064d200, 0xc00019a300, 0x77)
        /go/src/github.com/milvus-io/milvus/internal/proto/querypb/query_coord.pb.go:2528 +0x150
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000d3500, 0x2503be0, 0xc0006d4000, 0xc0008ea200, 0xc00003d7d0, 0x31ae3a0, 0x0, 0x0, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:1024 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc0000d3500, 0x2503be0, 0xc0006d4000, 0xc0008ea200, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:1313 +0xd34
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0002ac310, 0xc0000d3500, 0x2503be0, 0xc0006d4000, 0xc0008ea200)
        /go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:722 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:720 +0xa5

- Milvus version (master or released version)
Built:     Wed Jun 23 07:31:13 UTC 2021
GitCommit: 9ebca59

**Screenshots**

**Additional context**
[querycoord1.log](https://github.com/milvus-io/milvus/files/6701452/querycoord1.log)

**Comment by yanliang567** [comment]
seems like it reproduces occasionally

**Comment by xige-16** [comment]
It seems that queryCoord received a load request before it was fully started. then the queryCoord crash

**Comment by xige-16** [comment]
#6067  fixed the issue of queryCoord crash

**Comment by yanliang567** [comment]
verified on Built:    
Thu Jun 24 08:46:20 UTC 2021
GitCommit: 0f409da
