### ISSUE TITLE
load hangs after partition released

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#6045]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
load hangs after partition released

**Steps/Code to reproduce behavior**
Code:
from pymilvus_orm import CollectionSchema, FieldSchema
from pymilvus_orm import Collection
from pymilvus_orm import connections
from pymilvus_orm.types import DataType
from pymilvus_orm import Partition

int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=128)
schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
connections.connect()
import numpy as np
collection = Collection("test_search_collection_binbin_6", schema=schema)
partition = Partition(collection, "test_partition")
par = collection.partitions
dim = 128
nb = 500
nq = 1
limit = 1000
import random
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors],  par[0].name)
collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors],  par[1].name)
collection.partitions
collection.load()
partition.release()
collection.load()

**Expected behavior**
load successfully

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
milvus:master
Name: pymilvus
Version: 2.0a1.dev43
Name: pymilvus-orm
Version: 2.0a1.dev45

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xige-16** [comment]
This issue seems to have been resolved by #6097 , Please check and close it @del-zhenwu

**Comment by xige-16** [comment]
@binbinlv

**Comment by binbinlv** [comment]
Verified, and fixed.

Name: pymilvus
Version: 2.0a1.dev49
Name: pymilvus-orm
Version: 2.0a1.dev57
milvus: master

Results:
>>> collection.load()
>>> partition.release()
>>> collection.load()
>>>
