### ISSUE TITLE
The exception message for query with invalid string expr is strange

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#6046]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
@pytest.mark.parametrize("expr", ["12-s", "中文", "a", " "])
    def test_query_expr_invalid_string(self, expr):
        """
        target: test query with invalid expr
        method: query with invalid string expr
        expected: raise exception
        """
        collection_w, vectors, _, = self.init_collection_general(prefix, insert_data=True)
        error = {ct.err_code: 1, ct.err_msg: "invalid expr"}
        collection_w.query(expr, check_task=CheckTasks.err_res, check_items=error)
```
```
 [Milvus API Exception]<function api_request at 0x7f4252f144c0>: <BaseException: (code=1, message=Not implemented because:unsupported binary operator -)> (api_request.py:23)
```
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus              2.0a1.dev44
 pymilvus-orm          2.0a1.dev45

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by fishpenguin** [comment]
Working on it...

**Comment by fishpenguin** [comment]
Fixed

**Comment by ThreadDao** [comment]
Image GitCommit: d3c503f
The exception message:
```
<BaseException: (code=1, message=Not implemented because:unsupported binary operator -)> (api_request.py:23)

<BaseException: (code=1, message=Not implemented because:scalar expr is not supported yet)> (api_request.py:23)

<BaseException: (code=1, message=Not implemented because:scalar expr is not supported yet)> (api_request.py:23)

<BaseException: (code=1, message=Not implemented because:unexpected token EOF (1:1)
 |  
 | ^)> (api_request.py:23)
```
/cc @fishpenguin
