### ISSUE TITLE
Index is created failed with exception

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#6048]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Index created failed with assert
success: IVF_FLAT,  IVF_SQ8

fail:  "IVF_PQ", "HNSW", "RHNSW_FLAT", "RHNSW_PQ", "RHNSW_SQ", "ANNOY"

**Steps/Code to reproduce behavior**
Code:

from pymilvus_orm import CollectionSchema, FieldSchema
from pymilvus_orm import Collection
from pymilvus_orm import connections
from pymilvus_orm.types import DataType
from pymilvus_orm import Partition
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=128)
schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
connections.connect()
import numpy as np
collection = Collection("test_search_collection_binbin_6", schema=schema)
collection.partitions
dim = 128
nb = 500
nq = 1
limit = 1000
import random
default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
collection.partitions
default_index = {"index_type": "IVF_PQ", "params": {"nlist": 128}, "metric_type": "L2"}
collection.create_index("float_vector", default_index)
Error: <BaseException: (code=1, message=invalid index params: [key:"index_type" value:"IVF_PQ"  key:"params" value:"{\"nlist\": 128}"  key:"metric_type" value:"L2" ])>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pymilvus_orm/collection.py", line 902, in create_index
    timeout=kwargs.pop("timeout", None), **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 63, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 749, in create_index
    return handler.create_index(collection_name, field_name, params, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 63, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 55, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 720, in create_index
    raise BaseException(status.error_code, status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=invalid index params: [key:"index_type" value:"IVF_PQ"  key:"params" value:"{\"nlist\": 128}"  key:"metric_type" value:"L2" ])>

**Expected behavior**
created successfully

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
milvus:master
Name: pymilvus
Version: 2.0a1.dev43
Name: pymilvus-orm
Version: 2.0a1.dev45

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
The index about IVF_PQ must contain 'm' and 'nbits' params.

**Comment by binbinlv** [comment]
> The index about IVF_PQ must contain 'm' and 'nbits' params.

OK, retested specifying m, and bits as default, then it success. 

>>> default_index = {"index_type": "IVF_PQ", "params": {"nlist": 128, "m" : 64}, "metric_type": "L2"}
>>> collection.create_index("float_vector", default_index)
Status(code=0, message='')

And may I ask why "m" could not be given a default value just as "nbits"?

**Comment by binbinlv** [comment]
close it first.
