### ISSUE TITLE
Can't build PQ index with m=64, nbits=8 due to SharedMemPerBlock limitation

### ISSUE THREAD

**Issue by klimentij** [milvus-io/milvus#6050]
**Please state your issue using the following template and, most importantly, in English.**
With the data I have, I need at least 64 sub-quantizers to reach the desired recall@100 (0.9) according to my experiments on Milvus-CPU

**Describe the bug**
When I try to create a PQ index with m=64, nbits=8 or 16 and any nlist for a 500000x768 collection I get the following error:
```
Status(code=1, message="Error in void faiss::gpu::GpuIndexIVFPQ::verifySettings_() const at gpu/GpuIndexIVFPQ.cu:454: Error: 'requiredSmemSize <= getMaxSharedMemPerBlock(device_)' failed: Device 0 has 49152 bytes of shared memory, while 8 bits per code and 64 sub-quantizers requires 65536 bytes. Consider useFloat16LookupTables and/or reduce parameters")
```

**Steps/Code to reproduce behavior**
 With T4 GPU try to create a PQ index with m=64, nbits=8 or 16 and any nlist for a 500000x768 collection

**Expected behavior**
When getting this exception from FAISS, Milvus automatically sets `faiss.GpuClonerOptions().useFloat16 = True` or provides an API so that users could set `useFloat16 = True` this manually (as done in your FAISS [benchmark](https://github.com/milvus-io/milvus/blob/119ecfc633905fdf7e8b1cd47114427c18c40cf8/internal/core/src/index/thirdparty/faiss/benchs/bench_gpu_sift1m.py#L71))

**Method of installation**
Docker/gpu

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)
Debian GNU/Linux 10
16 CPU, 102 Gb RAM, T4 16Gb GPU

- Milvus version (master or released version)
1.1.0

**Configuration file**
gpu:
  enable: true
  cache_size: 10GB
  gpu_search_threshold: 300
  search_devices:
    - gpu0
  build_index_devices:
    - gpu0

**Comment by shengjun1985** [comment]
The suggestion is very useful.
Thank you very much.
