### ISSUE TITLE
No response to query

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#6051]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
1. create a collection and insert 1200 entities
2. query and no response
**_query with the image of commit dca24f3 is ok, and query with image of commit b72e4c6 no response_**
[0.log](https://github.com/milvus-io/milvus/files/6702412/0.log)

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus              2.0a1.dev47
 pymilvus-orm          2.0a1.dev52

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by ThreadDao** [comment]
@fishpenguin

**Comment by fishpenguin** [comment]
Already fixed in https://github.com/milvus-io/milvus/pull/6054
