### ISSUE TITLE
Server crashed when query with invalid output fields

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#6056]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Server crashed when query with `output_fields="12-s"`
```
@pytest.mark.parametrize("fields", ct.get_invalid_strs)
    def test_query_invalid_output_fields(self, fields):
        """
        get_invalid_strs: [
                  [],
                  1,
                  [1, "2", 3],
                  (1,),
                  {1: 1},
                  None,
                  "12-s",
                  "12 s",
                  "(mn)",
                  "中文",
                  "%$#",
                  "a".join("a" for i in range(256))]
        """
        collection_w, vectors, _, = self.init_collection_general(prefix, insert_data=True)
        error = {ct.err_code: 1, ct.err_msg: 'invalid output fields'}
        collection_w.query(default_term_expr, output_fields=fields, check_items=CheckTasks.err_res, check_task=error)
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus              2.0a1.dev47
 pymilvus-orm          2.0a1.dev52
 image tag: master-20210623-dca24f3

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by cydrain** [comment]
this case is in test20/python_client/testcases/test_query.py Line:338
but when run this line
```
        collection_w, vectors, _, = self.init_collection_general(prefix, insert_data=True)
```
Milvus will throw exception "do not contain any data" (reported from proxy/task.go Line:446)

Please help to check

/assign DragonDriver

**Comment by cydrain** [comment]
Cannot reproduce this issue, please check again.

/unassign DragonDriver
/assign ThreadDao
