### ISSUE TITLE
[Chaos] Milvus operations hang if operations requested during proxy deleted period

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#6058]
**Describe the bug**

**Steps/Code to reproduce behavior**
1. deploy Milvus with cluster mode
2. add a connection and connect to Milvus
3.  write a loop to create collection, insert data and search
4. delete proxy pod every 2 seconds for 20 seconds
5. wait proxy pod restarted until running state

**Expected behavior**
1. the operation return errors during proxy absence 
2. and return success after proxy back to running

**Actually**
the create/insert/search operation that requested during proxy deleted period hand without timeout.
one more side effect, after this issue repro,  it fails to create collections permanently even restart the proxy again. 

Background info for reference:
if there are no operations requested during proxy delete period and we request operations after proxy back to running, the operations would return success, just like the proxy had never been deleted.

- Milvus version (master or released version)
Milvus 2.0 with cluster mode
Built:     Wed Jun 23 07:31:13 UTC 2021
GitCommit: 9ebca59

**Screenshots**

**Additional context**
[proxy1.log](https://github.com/milvus-io/milvus/files/6705983/proxy1.log)
[rootcoord1.log](https://github.com/milvus-io/milvus/files/6705985/rootcoord1.log)
[querycoord3.log](https://github.com/milvus-io/milvus/files/6705987/querycoord3.log)

**Comment by yanliang567** [comment]
@czs007 any updates for this issue

**Comment by yanliang567** [comment]
i think we should have a timeout at sdk client side.

**Comment by ThreadDao** [comment]
Now it seems that the milvus operation is not stuck during proxy deleted. I re-test on milvus commit of `fb22d12`

**Comment by ThreadDao** [comment]
```
Built: Wed Aug 18 02:14:27 UTC 2021
GitCommit: e45cb6c
```
After proxy restarts, sometimes flush requests get stuck. And I don't sure about the re-produce conditions. So close it first.
