### ISSUE TITLE
Server crashed when query without loading

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#6059]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
    def test_query_partition_without_loading(self):
        """
        target: test query on partition without loading
        method: query on partition and no loading
        expected: raise exception
        """
        collection_w = self.init_collection_wrap(name=cf.gen_unique_str(prefix))
        partition_w = self.init_partition_wrap(collection_wrap=collection_w)
        df = cf.gen_default_dataframe_data(ct.default_nb)
        partition_w.insert(df)
        assert partition_w.num_entities == ct.default_nb
        error = {ct.err_code: 1, ct.err_msg: 'cannot find collection'}
        collection_w.query(default_term_expr, partition_names=[partition_w.name],
                           check_items=CheckTasks.err_res, check_task=error)
```
```
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1624504413.340148168","description":"Error received from peer ipv4:172.18.255.155:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus 2.0a1.dev47
 pymilvus-orm 2.0a1.dev52
 image tag: master-20210623-dca24f3

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by congqixia** [comment]
Re-tested with latest version
test/python_test/entity/test_query.py::TestQueryPartition::test_query_partition_without_loading  passed
tests20/python_client/testcases/test_query.py::TestQueryBase::test_query_partition_without_loading  xpassed

Note that the tests20/python_client requirment.txt has been updated in the last commit(to update pymilvus-orm version)

Please verify @ThreadDao
