### ISSUE TITLE
Expectation for vector upsert function

### ISSUE THREAD

**Issue by Alsace-lee** [milvus-io/milvus#6060]
Since made-in-china.com released "image search" in November 2020, as the vector retrieval engine, Milvus has shown very powerful performance.
Because of the powerful performance of Milvus, we decided to promote more business scenarios.
However,in some scenarios, the feature vector may change frequently, for example : user behaviors，Therefore, we need to frequently update the vector corresponding to a single ID. 
Milvus ,not supporting upsert operation, makes this difficult.
We have great expectations for Milvus to support the upsert operation, is that in you future plan ?
thanks

**Comment by Veyronl** [comment]
相同id的更新操作其实是不可避免的,希望milvus能增加该功能,希望milvus越来越好
再次感谢milvus的开源精神

**Comment by xiaofan-luan** [comment]
we already 

> Since made-in-china.com released "image search" in November 2020, as the vector retrieval engine, Milvus has shown very powerful performance.
> Because of the powerful performance of Milvus, we decided to promote more business scenarios.
> However,in some scenarios, the feature vector may change frequently, for example : user behaviors，Therefore, we need to frequently update the vector corresponding to a single ID.
> Milvus ,not supporting upsert operation, makes this difficult.
> We have great expectations for Milvus to support the upsert operation, is that in you future plan ?
> thanks

Great to know that you are using Milvus and it works well. We are planing on how to do upsert and it seems to be a tough issue.  Current plan is to add an optional distributed keyvalue system to support deduplication, anyone has  elegant solution please give us some advice

**Comment by yhmo** [comment]
According to the current [plan](https://wiki.lfaidata.foundation/display/MIL/Milvus+2.0+Roadmap+and+Time+schedule), the feature "Supports upsert/primary key deduplication" is to be implemented in v2.2.
