### ISSUE TITLE
Search is 0 if run load before "collection.partitions" and no results any more even run "collection.partitions" and "load" several times later

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#6065]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Search is 0 if run load before "collection.partitions" and no results any more even run "collection.partitions" and "load" more times

Good case: insert, run "collection.partitions" and "load", and "search"
Bad case: insert, load, run "collection.partitions", load, and search even +  "collection.partitions", load, search...

**Steps/Code to reproduce behavior**
Code:
Good case: 
from pymilvus_orm import CollectionSchema, FieldSchema
from pymilvus_orm import Collection
from pymilvus_orm import connections
from pymilvus_orm.types import DataType
from pymilvus_orm import Partition

int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
int32_field = FieldSchema(name="int32", dtype=DataType.INT32)
int16_field = FieldSchema(name="int16", dtype=DataType.INT16)
int8_field = FieldSchema(name="int8", dtype=DataType.INT8)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=128)
connections.connect()
import numpy as np
schema = CollectionSchema(fields=[int64_field, int32_field, int16_field, int8_field, float_field, float_vector])
collection = Collection("test_search_collection_binbin_01", schema=schema)
dim = 128
nb = 3000
nq = 1
limit = 1000
import random
default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
data = [[i for i in range(nb)], [np.int32(i) for i in range(nb)], [np.int16(i) for i in range(nb)], [np.int8(i) for i in range(nb)], [np.float32(i) for i in range(nb)], vectors]
res = collection.insert(data)
collection.partitions
>>>[{"name": "_default", "description": "", "num_entities": 3000}]
>>>
collection.load()
res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> len(res[0])
1000

Fail case:
from pymilvus_orm import CollectionSchema, FieldSchema
from pymilvus_orm import Collection
from pymilvus_orm import connections
from pymilvus_orm.types import DataType
from pymilvus_orm import Partition
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
int32_field = FieldSchema(name="int32", dtype=DataType.INT32)
int16_field = FieldSchema(name="int16", dtype=DataType.INT16)
int8_field = FieldSchema(name="int8", dtype=DataType.INT8)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=128)
connections.connect()
import numpy as np
schema = CollectionSchema(fields=[int64_field, int32_field, int16_field, int8_field, float_field, float_vector])
collection = Collection("test_search_collection_binbin_01", schema=schema)
dim = 128
nb = 3000
nq = 1
limit = 1000
import random
default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
data = [[i for i in range(nb)], [np.int32(i) for i in range(nb)], [np.int16(i) for i in range(nb)], [np.int8(i) for i in range(nb)], [np.float32(i) for i in range(nb)], vectors]
res = collection.insert(data)
collection.load()
collection.partitions
>>>[{"name": "_default", "description": "", "num_entities": 3000}]

collection.load()
res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> len(res[0])
0

collection.partitions
[{"name": "_default", "description": "", "num_entities": 3000}]
collection.load()
res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> len(res[0])
0

**Expected behavior**
Search successfully

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
milvus: master
Name: pymilvus
Version: 2.0a1.dev47
Name: pymilvus-orm
Version: 2.0a1.dev53

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by czs007** [comment]
working on it

**Comment by DragonDriver** [comment]
#6068 will fix this

**Comment by binbinlv** [comment]
OK, will retest it after the merge of #6068.

**Comment by binbinlv** [comment]
Verified, and fixed.

Name: pymilvus
Version: 2.0a1.dev52
Name: pymilvus-orm
Version: 2.0a1.dev58
milvus-master

Results:
>>> res = collection.insert(data)
>>>
>>>
>>> collection.load()
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 3000}]
>>> collection.load()
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> len(res[0])
1000
>>>
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 3000}]
>>>
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> len(res[0])
1000
