### ISSUE TITLE
Construct_from_dataframe with auto_id None didn't raise exception

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#6077]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
    def test_construct_with_none_auto_id(self):
        """
        target: test construct with non-int64 as the primary field
        method: non-int64 as the primary field
        expected: raise an exception
        """
        self._connect()
        c_name = cf.gen_unique_str(prefix)
        df = cf.gen_default_dataframe_data(ct.default_nb)
        error = {ct.err_code: 0, ct.err_msg: "Param auto_id must be bool type"}
        self.collection_wrap.construct_from_dataframe(c_name, df, primary_field=ct.default_int64_field_name,
                                                      auto_id=None, check_task=CheckTasks.err_res, check_items=error)

```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus              2.0a1.dev47
 pymilvus-orm          2.0a1.dev54
```
  9 2021-06-24T08:11:01.662625034Z stdout F Built:     Thu Jun 24 07:42:18 UTC 2021
  10 2021-06-24T08:11:01.662626949Z stdout F GitCommit: 133814b
  11 2021-06-24T08:11:01.662628909Z stdout F GoVersion: go version go1.15.2 linux/amd64
```

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/190
