### ISSUE TITLE
Querynode crashed if running search test in multiple processes

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#6079]
**Describe the bug**
Querynode crashed if running search test in multiple threads 

**Steps/Code to reproduce behavior**
1. deploy Milvus 2.0 with cluster mode
2. in tests20/python_client/testcases/ run
    pytest test_search.py::TestCollectionSearch --host <ip>  -s --workers 4

**Expected behavior**
Milvus shall not crash no matter tests pass or not

- Milvus version (master or released version)
Built:     Wed Jun 23 12:28:03 UTC 2021
GitCommit: b72e4c6

**Additional context**
[querycoord4.log](https://github.com/milvus-io/milvus/files/6707782/querycoord4.log)
[querynode4.log](https://github.com/milvus-io/milvus/files/6707809/querynode4.log)
[rootcoord4.log](https://github.com/milvus-io/milvus/files/6707813/rootcoord4.log)

**Comment by sunby** [comment]
I ran this case and got: 
`fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f3917bd7795]

runtime stack:
runtime.throw(0x23849ae, 0x2a)
    /usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
    /usr/local/go/src/runtime/signal_unix.go:718 +0x2e5

goroutine 27803 [syscall]:
runtime.cgocall(0x150f095, 0xc001296e00, 0x8)
    /usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc001296dd0 sp=0xc001296d98 pc=0x794e7b
github.com/milvus-io/milvus/internal/querynode._Cfunc_ReduceQueryResults(0xc00139a370, 0x2, 0xc001126660, 0x0, 0x0)
    _cgo_gotypes.go:750 +0x51 fp=0xc001296e00 sp=0xc001296dd0 pc=0x14e8691
github.com/milvus-io/milvus/internal/querynode.reduceSearchResults.func1(0xc00139a370, 0x2, 0xc001126660, 0x1, 0x2)
    /home/sunby/Documents/milvus/internal/querynode/reduce.go:50 +0x65 fp=0xc001296e38 sp=0xc001296e00 pc=0x14fbcc5
github.com/milvus-io/milvus/internal/querynode.reduceSearchResults(0xc00139a350, 0x2, 0x2, 0x2, 0xc001126660, 0x2, 0x2, 0x0, 0x0)
    /home/sunby/Documents/milvus/internal/querynode/reduce.go:50 +0x17d fp=0xc001296ef0 sp=0xc001296e38 pc=0x14f22bd
github.com/milvus-io/milvus/internal/querynode.(*queryCollection).search(0xc00019f080, 0xc0014ab9e0, 0x0, 0x0)
    /home/sunby/Documents/milvus/internal/querynode/query_collection.go:888 +0x28f1 fp=0xc001297838 sp=0xc001296ef0 pc=0x14d5631
github.com/milvus-io/milvus/internal/querynode.(*queryCollection).receiveSearch(0xc00019f080, 0xc0014ab9e0)
    /home/sunby/Documents/milvus/internal/querynode/query_collection.go:411 +0x11f3 fp=0xc001297e70 sp=0xc001297838 pc=0x14ce693
github.com/milvus-io/milvus/internal/querynode.(*queryCollection).consumeQuery(0xc00019f080)
    /home/sunby/Documents/milvus/internal/querynode/query_collection.go:235 +0x2d3 fp=0xc001297fd8 sp=0xc001297e70 pc=0x14cb6f3
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc001297fe0 sp=0xc001297fd8 pc=0x7ff321
created by github.com/milvus-io/milvus/internal/querynode.(*queryCollection).start
    /home/sunby/Documents/milvus/internal/querynode/query_collection.go:98 +0xa5
`

Maybe @FluorineDog can help.  @xige-16

**Comment by sunby** [comment]
here is the log of querynode
[query_node.log](https://github.com/milvus-io/milvus/files/6708201/query_node.log)

**Comment by xige-16** [comment]
I can't reproduce it locally @yanliang567 @sunby

**Comment by xige-16** [comment]
> **Describe the bug**
> Querynode crashed if running search test in multiple threads
> 
> **Steps/Code to reproduce behavior**
> 
> 1. deploy Milvus 2.0 with cluster mode
> 2. in tests20/python_client/testcases/ run
>    pytest test_search.py::TestCollectionSearch --host   -s --workers 4
> 
> **Expected behavior**
> Milvus shall not crash no matter tests pass or not
> 
> * Milvus version (master or released version)
>   Built:     Wed Jun 23 12:28:03 UTC 2021
>   GitCommit: [b72e4c6](https://github.com/milvus-io/milvus/commit/b72e4c63726e28cd54f90c642faf5394d4a24c12)
> 
> **Additional context**
> [querycoord4.log](https://github.com/milvus-io/milvus/files/6707782/querycoord4.log)
> [querynode4.log](https://github.com/milvus-io/milvus/files/6707809/querynode4.log)
> [rootcoord4.log](https://github.com/milvus-io/milvus/files/6707813/rootcoord4.log)

the querynode.log doesn't seem to have crashed

**Comment by xige-16** [comment]
I update pymilvus-orm's version to 2.0a1.dev51 and this problem has been reproduced. I'm working on it

**Comment by xige-16** [comment]
#6115 has fix the problem of querynode crash, but pytest test_search.py::TestCollectionSearch --host -s --workers 4 also can't pass @binbinlv

**Comment by xige-16** [comment]
Trouble you check it after pr #6115 merged @yanliang567

**Comment by yanliang567** [comment]
will try after the pr merged

**Comment by xige-16** [comment]
> will try after the pr merged

pr #6115 merged

**Comment by yanliang567** [comment]
The query node does not crash this time.  But the testing processes were still stuck, and after interrupting the test process, any new requests to insert data would hang for mins.
master-20210626-2e37fca
pymilvus                           2.0a1.dev51
pymilvus-orm                       2.0a1.dev58

**Comment by DragonDriver** [comment]
debug this, stuck on assigning segment id when inserting, @czs007 
/unassign
/assign @czs007

**Comment by yanliang567** [comment]
@czs007 any updates for this issue?

**Comment by czs007** [comment]
working on it

**Comment by yanliang567** [comment]
[datacoord.6079.log](https://github.com/milvus-io/milvus/files/6739113/datacoord.6079.log)
[datanode.6079.log](https://github.com/milvus-io/milvus/files/6739116/datanode.6079.log)
[indexcoord.6079.log](https://github.com/milvus-io/milvus/files/67391
[quercoord.6079.log](https://github.com/milvus-io/milvus/files/6739122/quercoord.6079.log)
[rootcoord.6079.log](https://github.com/milvus-io/milvus/files/6739128/rootcoord.6079.log)
[indexnode.6079.log](https://github.com/milvus-io/milvus/files/6739118/indexnode.6079.log)

**Comment by yanliang567** [comment]
it is caused by the test framework: more and more collections were created and it causes Milvus very slow.
Fixed it by deleting collections for each test in teardown
