### ISSUE TITLE
Return the object of the collection according to the collection name

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#6081]
**Please state your issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**
Clear all the collections, now there is no interface that passes the collection name to drop the collection.
There is only an interface of list_collections that list all collection names in the utility class.

**Describe the solution you'd like**
Hope there is an interface that get_collection(collection_name, _using="default"), the object of the collection is returned when the name of the collection is passed in.

**Describe alternatives you've considered**
In the utility class, add the interface of get_collection(collection_name, _using="default").

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by DragonDriver** [comment]
According to the design of pymilvus-orm, you can directly use `Collection(name=collection_name)` to get a collection object if the collection already exists in server.

Please check this.
/assign @czs007 
/assign @xiaocai2333

**Comment by ANYMS-A** [comment]
> According to the design of pymilvus-orm, you can directly use `Collection(name=collection_name)` to get a collection object if the collection already exists in server.
> 
> Please check this. /assign @czs007 /assign @xiaocai2333

Can we add the method for MilvusClient like "get_collection(collection_name=xxx)" which can return a Collection object directly based on the cilent object?
