### ISSUE TITLE
restful api search result return id -1

### ISSUE THREAD

**Issue by zhaoning1987** [milvus-io/milvus#6085]
step:
1. start milvus with image milvusdb/milvus:1.1.1-cpu-d061621-330cc6
2. create a collection
3. insert a record (id:1, vector:[1,1]) in the collection
4. do a search with topk=10, it is supposed to get only one result which is the one we insert in step3, however we got another result with id -1.
![image](https://user-images.githubusercontent.com/39478004/123240012-82789400-d512-11eb-931b-13c387a38a9a.png)
![image](https://user-images.githubusercontent.com/39478004/123240078-915f4680-d512-11eb-8675-7eb5a187b660.png)

Note: python sdk do not have this issue

**Comment by shengjun1985** [comment]
If the returned results are less than `topk`, the engine will fill with `-1`.
However, the restful API did not filter those values.

Now, it is fixed in branch 1.1.
Thanks all.
