### ISSUE TITLE
Remove debug log in pymilvus

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#6086]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
 0.07429646581939768, 0.09651448698634858, 0.10112509234897797, 0.06186283605548727, 0.08297692892040379, 0.0771778377119907, 0.062174817367198154, 0.09057794319354384]]}]
 | ....................................^)> (grpc_handler.py:57)

```
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by cydrain** [comment]
Don't know where the debug log coming from.
Please provide the re-produce steps.
