### ISSUE TITLE
Get load collection still return all collections

### ISSUE THREAD

**Issue by nameczz** [milvus-io/milvus#6109]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Get load collection still return all collections

**Steps/Code to reproduce behavior**
1. Create two collections
2. Load one collection
3. Get collection with type: 1
4. Return all collections

**Expected behavior**
Return loaded collections when type:1

**Method of installation**
- [ ]  milvusdb/milvus-dev:master-latest

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
Milvus 2.0

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xige-16** [comment]
enum ShowCollectionsType {
  All = 0;
  InMemory = 1;
}

Get collection with type = 0 will return all collection in system, the result is right
@nameczz

**Comment by xige-16** [comment]
if you want to get collection list loaded in memory, please set type = 1

**Comment by nameczz** [comment]
> if you want to get collection list loaded in memory, please set type = 1

I described issue has some problem. What i passed is type = 1. 
I changed issue description.
@xige-16

**Comment by xige-16** [comment]
The issue has been solved by pr #6149. Trouble you check it. @nameczz

**Comment by nameczz** [comment]
I think this is fixed
