### ISSUE TITLE
[Chaos] Create/Insert/Flush/Search Ops are blocked when the indexcoord pod was deleted and an attempt of building index is keeping retry

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#6110]
**Describe the bug**
Create/Insert/Flush/Search Ops are blocked when the indexcoord pod was deleted and an attempt of building index is keeping retry

**Steps/Code to reproduce behavior**
1. deploy Milvus 2.0 with cluster mode
2. start a thread to create collection in a loop
3. start a thread to insert data in a loop
4. start a thread to flush data in a loop
5. start a thread to search vectors in a loop
6. start a thread to query data in a loop
7. start a thread to build index in a loop
7. delete indexcoord pod every 2s for 20s

**Expected behavior**
during the period of indexcoord unavailable,  all the ops except building index should succeed

**Actually**
build index fails as expected
query succeeds as expected
create, insert, flush and search are blocked(hang) until the indexcoord pod back to running state

**Milvus version (master or released version)**
master-20210624-cea83dd
pymilvus 2.0a1.dev47
pymilvus-orm 2.0a1.dev53

**Additional context**

**Comment by yanliang567** [comment]
[indexcoord-6110.log](https://github.com/milvus-io/milvus/files/6713266/indexcoord-6110.log)
[indexnode-6110.log](https://github.com/milvus-io/milvus/files/6713267/indexnode-6110.log)
[querycoord-6110.log](https://github.com/milvus-io/milvus/files/6713270/querycoord-6110.log)
[rootcoord-6110.log](https://github.com/milvus-io/milvus/files/6713273/rootcoord-6110.log)

**Comment by czs007** [comment]
pulsar_conf_path=/pulsar/conf/standalone.conf
pulsar_conf_path=abc.txt
echo "" >> $pulsar_conf_path
echo "maxMessageSize=1073741824"  >> $pulsar_conf_path
echo "" >> $pulsar_conf_path
echo "nettyMaxFrameSizeBytes=1073741824" >> $pulsar_conf_path

will delete lateer

**Comment by godchen0212** [comment]
Maybe same as #5976, the PR #6107 has fixed this issue.
Please test it again. @yanliang567

**Comment by ThreadDao** [comment]
After re-testing, the Milvus `5c383d1` version has not fixed this issue!

**Comment by ThreadDao** [comment]
Below is the client log. You can get the time period from chaos injected to chaos deleted. So you can filter out all pods logs on kibana-dev based on this time period. This issue indicated that other interfaces are unavailable during the indexCoord pod is killed.
1. The client logs: 
[client.log](https://github.com/milvus-io/milvus/files/6979743/client.log)

2. The pod names
```
milvus-zong-datacoord-7878c484f4-6f6fr                 1/1     Running   0          52m
milvus-zong-datanode-5f95b6455c-9h99x                  1/1     Running   0          52m
milvus-zong-etcd-0                                     1/1     Running   0          52m
milvus-zong-indexcoord-5cc6bf68f-qwrx9                 1/1     Running   0          52m
milvus-zong-indexnode-99577778-mrwrx                   1/1     Running   0          5s
milvus-zong-minio-8454ddbcd6-t4mrm                     1/1     Running   0          52m
milvus-zong-proxy-7c66d8575c-x8hbl                     1/1     Running   0          52m
milvus-zong-pulsar-779449cc9c-brks8                    1/1     Running   0          52m
milvus-zong-querycoord-6cfd9bd646-br8rd                1/1     Running   0          52m
milvus-zong-querynode-85ddfc64c6-vqlbm                 1/1     Running   0          52m
milvus-zong-rootcoord-6f49469978-n8vg6                 1/1     Running   0          52m
```
3. If you can't view it on kibana, you can refer to the following log files
[milvus_logs.tar.gz](https://github.com/milvus-io/milvus/files/6979765/milvus_logs.tar.gz)

**Comment by xiaocai2333** [comment]
Can you reproduce it again? @yanliang567

**Comment by yanliang567** [comment]
@ThreadDao please help to repro it 
/assign @ThreadDao

**Comment by ThreadDao** [comment]
1. Version
```
Version:   daae056
Built:     Wed Aug 25 02:33:34 UTC 2021
```
2. Result
```
[2021-08-25 15:03:54,618 - DEBUG - ci_test]: ******2nd assert after chaos injected:  (test_chaos.py:143)
[2021-08-25 15:03:54,618 - DEBUG - ci_test]: Expect Succ: Op.create succ rate 1.0, total: 2 (test_chaos.py:26)
[2021-08-25 15:03:54,618 - DEBUG - ci_test]: Expect Succ: Op.insert succ rate 1.0, total: 3 (test_chaos.py:26)
[2021-08-25 15:03:54,619 - DEBUG - ci_test]: Expect Succ: Op.flush succ rate 1.0, total: 2 (test_chaos.py:26)
[2021-08-25 15:03:54,620 - DEBUG - ci_test]: Expect Fail: Op.index succ rate 0.0, total: 1 (test_chaos.py:22)
[2021-08-25 15:03:54,621 - DEBUG - ci_test]: Expect Succ: Op.search succ rate 1.0, total: 2 (test_chaos.py:26)
[2021-08-25 15:03:54,621 - DEBUG - ci_test]: Expect Succ: Op.query succ rate 1.0, total: 39 (test_chaos.py:26)
```
So close it first!
