### ISSUE TITLE
Search released partition still report "partition has been released" after load

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#6111]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Search partition still report "partition has been released" after load

**Steps/Code to reproduce behavior**
Steps:
1 create connect, collection, and insert(1000 entities, 500 in each partition separately), load
2 partition release and search 
3 search collection (return 500), search released partition (return error) -- right
4 collection load
5 search collection (return 1000), search per-released partition ( still return error) -- here search should be successful

Code:
from pymilvus_orm import CollectionSchema, FieldSchema
from pymilvus_orm import Collection
from pymilvus_orm import connections
from pymilvus_orm.types import DataType
from pymilvus_orm import Partition

int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=128)
schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
connections.connect()
import numpy as np
collection = Collection("test_search_collection_binbin_6", schema=schema)
partition = Partition(collection, "test_partition")
par = collection.partitions
dim = 128
nb = 500
nq = 1
limit = 1000
import random
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors], par[0].name)
collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors], par[1].name)
collection.partitions
>>> [{"name": "_default", "description": "", "num_entities": 500}, {"name": "test_partition", "description": "", "num_entities": 500}]

collection.load()
partition.release()
default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")

>>> len(res[0])
500
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0", ["test_partition"])
Error: <BaseException: (code=1, message=partition has been released, collectionID = 425876429560610817

collection.load()
res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> len(res[0])
1000
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0", ["test_partition"])
Error: <BaseException: (code=1, message=partition has been released, collectionID = 425876429560610817
, partitionID = 425876429560610819

)>
Error: <BaseException: (code=1, message=partition has been released, collectionID = 425876429560610817
, partitionID = 425876429560610819

)>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pymilvus_orm/collection.py", line 612, in search
    partition_names, output_fields, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 63, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 1042, in search_with_expression
    return handler.search_with_expression(collection_name, data, anns_field, param, limit, expression, partition_names, output_fields, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 63, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 55, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 92, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 622, in search_with_expression
    return self._execute_search_requests(requests, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 63, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 55, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 591, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 582, in _execute_search_requests
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=partition has been released, collectionID = 425876429560610817
, partitionID = 425876429560610819

**Expected behavior**
Search successfully with right values

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
milvus: master
Name: pymilvus
Version: 2.0a1.dev49
Name: pymilvus-orm
Version: 2.0a1.dev57

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xige-16** [comment]
the issue has been solved by pr #6135. Trouble you check it

**Comment by binbinlv** [comment]
Verified, and fixed.

Name: pymilvus
Version: 2.0a1.dev52
Name: pymilvus-orm
Version: 2.0a1.dev58
milvus-master

Results:
>>> partition.release()
>>> default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>>
>>> len(res[0])
500
>>> collection.load()
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> len(res[0])
1000
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0", ["test_partition"])
>>>
>>> len(res[0])
500
