### ISSUE TITLE
Broken links found on documentation pages.

### ISSUE THREAD

**Issue by yzeng25** [milvus-io/milvus#6120]
**Please state your issue using the following template and, most importantly, in English.**
Broken links found on documentation pages.
--

**Describe the problems or issues found in the documentation**
Hi folks,

I found several broken links on the documentation pages. It would be awesome if you could fix them soon.

**Locations of incorrect documentation**
Problem 1
1. Location: `https://milvus.io/`
2. Problem: The hyperlink `https://github.com/milvus-io/milvus/tree/master/sdk` redirects to a 404 page on GitHub. I tried the other buttons around it, they redirect to somewhere like `milvus/milvus-sdk-java`. So I am wondering if there is a related repository named `milvu/milvus-sdk-cpp` for the correct hyperlink.
![image](https://user-images.githubusercontent.com/36651058/123392550-c382ae00-d5cf-11eb-9b57-192d616a4c19.png)

Problem 2
1. Location: https://milvus.io/scenarios
2. Problem: The hyperlink `https://github.com/milvus-io/bootcamp/blob/master/EN_solutions/pic_search/README.md` redirects to a 404 page on GitHub. Maybe it was moved to somewhere else? I cannot find `./EN_solutions` subdirectory under `./master` directory.
![image](https://user-images.githubusercontent.com/36651058/123393799-098c4180-d5d1-11eb-8cbd-b3640259b91b.png)

Problem 3
1. Location: `https://milvus.io/scenarios`
2. Problem: The hyperlink `https://github.com/milvus-io/bootcamp/tree/master/solutions/QA_System`redirects to a 404 page on GitHub. Same as the Problem 2 above.
![image](https://user-images.githubusercontent.com/36651058/123394603-e31ad600-d5d1-11eb-844c-35b77dd167e9.png)

Problem 4
1. Location: `https://milvus.io/scenarios`
2. Problem: The hyperlink `https://github.com/milvus-io/bootcamp/blob/master/EN_solutions/mols_search/README.md`redirects to a 404 page on GitHub. Same as the Problem 2 above.
![image](https://user-images.githubusercontent.com/36651058/123394850-28d79e80-d5d2-11eb-800a-c5816129f036.png)

**Steps taken to verify documentation is incorrect**
List any steps you have taken:

1. visit  `https://milvus.io/` or `https://milvus.io/scenarios` 
2. click on corresponding links listed above.

**Suggested fix for documentation**

Replace broken links with valid links.

---

## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken:

**Comment by shengjun1985** [comment]
It is fixed. Thanks all.
