### ISSUE TITLE
In-page jumping failed on 'https://milvus.io/cn/docs/v1.1.1/product_faq.md' page

### ISSUE THREAD

**Issue by yzeng25** [milvus-io/milvus#6122]
**Please state your issue using the following template and, most importantly, in English.**
Hi folks,
I found some in-page jumping failed on `https://milvus.io/cn/docs/v1.1.1/product_faq.md` page.

**Location of incorrect documentation**
https://milvus.io/cn/docs/v1.1.1/product_faq.md

**Describe the problems or issues found in the documentation**

As shown in the screenshot below, when I click on links listed in the box, they would not jump at all. Yet the links in English documents work out well. For the sake of simplicity, I did not test **all** links listed here. But I think you should take a closer look at all pages under `./product_faq`, both in English and in Chinese, in order to fix this problem.
![image](https://user-images.githubusercontent.com/36651058/123396344-c7183400-d5d3-11eb-8009-b854ef7795f6.png)

**Steps taken to verify documentation is incorrect**
List any steps you have taken:

1. visit `https://milvus.io/cn/docs/v1.1.1/product_faq.md`
2. click on the links, and fail to jump to the right sections.

**Suggested fix for documentation**
I guess these failing links were added to the docs recently, and there should be somewhere else that stores or automates this jump feature. Or maybe the `#milvus-会收费吗` in the end of each link was not formatted properly.

---

## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken:

**Comment by yhmo** [comment]
Yes, it is really a problem.

**Comment by shanghaikid** [comment]
https://milvus.io/cn/docs/v1.1.1/product_faq.md please try it again : )

**Comment by shengjun1985** [comment]
@shanghaikid 
There are duplicate entries in the directory.
Please check again.

**Comment by yzeng25** [comment]
> @shanghaikid
> There are duplicate entries in the directory.
> Please check again.

Yeah, both entries are valid now, but one entry is enough.

**Comment by shengjun1985** [comment]
It is fixed. Thanks all.
