### ISSUE TITLE
Fail to find the collection if running in multiple processes

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#6140]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

**Steps/Code to reproduce behavior**
run a test in multiple processes in tests20/python_client/testcases: 
  pytest test_partition.py::TestPartitionParams::test_partition_insert  --host 10.98.0.7 --tags L0 L1 -s  **--workers 4**

**Expected behavior**
run successfully

**Actually**
ERROR    pymilvus.client.grpc_handler:grpc_handler.py:57 Error: <BaseException: (code=1, message=getSegmentsOfCollection, err:describe collection failed: can't find collection: coll__Wmjlaxvl)>

- Milvus version (master or released version)
Built:     Fri Jun 25 08:54:15 UTC 2021
GitCommit: eb818d0
pymilvus                           2.0a1.dev51
pymilvus-orm                       2.0a1.dev58

**Comment by yanliang567** [comment]
it seems to be a test framework issue

**Comment by wangting0128** [comment]
solved
