### ISSUE TITLE
Write node down result in read-only node also unavailable

### ISSUE THREAD

**Issue by axin3892** [milvus-io/milvus#6141]
**Describe the bug**

The cluster is built based on the mishard, when the write node is down, first the write node is inaccessible and mishard reports a timeout error, after a few minutes the read node is also unavailable and any command sent to it would  return a timeout error by mishard. Why does the downtime of the write node cause the read node to fail?

mishard returns the following error

![捕获1582](https://user-images.githubusercontent.com/52096123/123504587-e6bf6300-d68c-11eb-8d4f-56a02e8248d0.PNG)

**Comment by XuanYang-cn** [comment]
@axin3892 Mishards is healthy unless a write node is healthy.
Because all the requests are operating by write-node **EXCEPT** search, which is operating by read-node. 
If a write-node down, mishard's actually not functional for all the API.

**Comment by axin3892** [comment]
> @axin3892 Mishards is healthy unless a write node is healthy.
> Because all the requests are operating by write-node **EXCEPT** search, which is operating by read-node.
> If a write-node down, mishard's actually not functional for all the API.

i think because the write node is a single node, the write node crash should not affect the normal use of the search function, otherwise it will cause frequently service crashes

**Comment by yhmo** [comment]
In Mishards, write node also can take part in search. 
Whether to use write node for search is defined in this config file: /milvus/shards/all_in_one_with_mysql/all_in_one.yml

```
services:
    .......
    mishards:
        ......
        environment:
            DISCOVERY_STATIC_HOSTS: milvus_wr, milvus_ro
```
The DISCOVERY_STATIC_HOSTS specify which node can take part in search. By default, write node is included.

So, when write node is down, mishards will wait search result from write node, the client will get time out error.
Exclude write node from the "DISCOVERY_STATIC_HOSTS" can avoid this problem.
