### ISSUE TITLE
The query returns vector field when specify vector field in output_fields

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#6143]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
    def test_query_output_part_vec_field(self):
        collection_w, vectors, _, = self.init_collection_general(prefix, insert_data=True)
        res, _ = collection_w.query(default_term_expr, output_fields=[ct.default_int64_field_name, ct.default_float_vec_field_name])
        log.debug(res)
```
```
 [{'int64': 0, 'float_vector': [0.008928, ..., 0.056926]}, {'int64': 1, 'float_vector': [0.064098, ..., 0.111683]}] (test_query.py:322)
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus              2.0a1.dev52
 pymilvus-orm          2.0a1.dev58
 GitCommit: 2e37fca

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by czs007** [comment]
@fishpenguin What is the behavior after repair? Throw an exception? What is the exception information?
