### ISSUE TITLE
When will the pure cpu version of milvus be distributed?

### ISSUE THREAD

**Issue by TTian-vivo** [milvus-io/milvus#615]
As we all konw, in the case of a large amount of data, we must separate the data onto different machines. I see distributed development with GPU version, but the CPU version has not been updated, I look forward to the pure cpu version coming online as soon as possible.

**Comment by shanghaikid** [comment]
when?

**Comment by yhmo** [comment]
Recently we fixed several important bugs including some crash issues. Now v0.6.0 is in last round testing phase. Hopefully we can release it in 1 or 2 days.

**Comment by yhmo** [comment]
Milvus CPU version docker image has been published today, please use the command to pull and run it:
docker pull milvusdb/milvus:cpu-latest
docker run -it -p 19530:19530 -d milvusdb/milvus:cpu-latest
