### ISSUE TITLE
What features do you want❓

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#6151]
Sincerely thank you for using and continuing to pay attention to Milvus. In order to understand what features the user want for Milvus and Milvus tools. And we want to learn that how hot each feature is. So an issue is opened to keep track of it. Everyone who has a need for Milvus can comment on this issue. You can refer to the following format to provide information:

Feature: xxx (such as: support collection rename)
issue number: xxx (such as: https://github.com/milvus-io/milvus/issues/4812)

In your own issue,  please explain what is your application scenario? Why do you need this feature? The more details the better. Here is an example of an issue:

I want the collection rename API to switch between two collections
Scenario: 
A collection every 10 minutes to re-import a batch of data, there will be services have been querying this collection , when the collection has some data expired, you can not go one by one to delete records, it is best to carry out a full update, requiring the new collection of the same name and the old.
Implementation steps:
1. Create a new collection B;
2. Use the collection rename API to change the name of collection B to collection A;
3. Delete the original collection A.

If you find that the feature you need is already recorded in the comments, please give this comment a like and then go to the issue in this comment and write down your application scenario and the reason why you need this feature.
We will determine how popular each feature is based on the number of likes it receives, and then decide on the priority of development. 
Of course, you can also submit a pull request directly to Milvus, so you can also become a Milvus Contributor. Here is a guide on how to contribute code：https://github.com/milvus-io/milvus/blob/master/CONTRIBUTING.md

**Comment by Alsace-lee** [comment]
I hope  an entity upsert API added to SDK, which allows us to update a entity
Scenario:
In some scenarios, because of business data changes, the vector or scalar field in an entity corresponding to a certain ID needs to be updated.
In milvus1.0, we delete and then insert to achieve this function, but when this operation is too frequent, it will cause update blocking.
Therefore, we are very eager to have an update interface to implement the upsert action

**Comment by liushu-smartnews** [comment]
We have STRONG need for collection hot reload, which can be implemented by collection rename or alias.
Feature: support collection rename (or alias)
issue number: #4812

**Comment by liushu-smartnews** [comment]
We want some automatic expiration mechanisms in our applications, so that we don't need additional scheduled jobs to remove outdated items, and can make the time range more precise.
Feature: automatic item expiration
Issue: #6162

**Comment by liushu-smartnews** [comment]
Feature: support collection rename
Issue: #4812

Collection rename / alias is CRITICAL for some of our use cases, because the searching side and new collection generating side are completely separate.
I also left a message under #3821 before, which was merged to #4812.

**Comment by xiaofan-luan** [comment]
> I hope an entity upsert API added to SDK, which allows us to update a entity
> Feature: upsert entity
> ISSUE: #6060
> Scenario:
> In some scenarios, because of business data changes, the vector or scalar field in an entity corresponding to a certain ID needs to be updated.
> In milvus1.0, we delete and then insert to achieve this function, but when this operation is too frequent, it will cause update blocking.
> Therefore, we are very eager to have an update interface to implement the upsert action

Milvus 2.0 plan to support upsert by delete the old id and insert a new one, functionality will be ready by the end of August. Frequently delete/update may still causing query performance degrade, compaction will be introduced to solve the problem.

Also, insert/delete in milvus 2.0 can be distributed so hopefully it could be much faster and no blocking will happen

**Comment by xiaofan-luan** [comment]
> Feature: automatic item expiration
> Issue: #6162
> 
> We want some automatic expiration mechanisms in our applications, so that we don't need additional scheduled jobs to remove outdated items, and can make the time range more precise.

Data Time to Live mechanism is on the way. Once we implemented compaction in Milvus 2.0, time to live is gonna to be a  accessory products. 

Also, you can simply partition the data by day and delete data by partition

**Comment by xiaofan-luan** [comment]
> Feature: support collection rename
> Issue: #4812
> 
> Collection rename / alias is CRITICAL for some of our use cases, because the searching side and new collection generating side are completely separate.
> I also left a message under #3821 before, which was merged to #4812.

collection rename is a practical function. So far we are working on more general mechanisms, so rename is not our first priority.
Anyone interested in implementing this function?

**Comment by liushu-smartnews** [comment]
> > Feature: support collection rename
> > Issue: #4812
> > Collection rename / alias is CRITICAL for some of our use cases, because the searching side and new collection generating side are completely separate.
> > I also left a message under #3821 before, which was merged to #4812.
> 
> collection rename is a practical function. So far we are working on more general mechanisms, so rename is not our first priority.
> Anyone interested in implementing this feature?

Thank you for the answer!
This "practical function" is our only blocking issue in current use cases, though.
Either TTL or upsert are "nice to have" for us, but the lack of "hot reload" already blocked 2 use cases, because of some internal limitations...

**Comment by xiaofan-luan** [comment]
> > > Feature: support collection rename
> > > Issue: #4812
> > > Collection rename / alias is CRITICAL for some of our use cases, because the searching side and new collection generating side are completely separate.
> > > I also left a message under #3821 before, which was merged to #4812.
> > 
> > 
> > collection rename is a practical function. So far we are working on more general mechanisms, so rename is not our first priority.
> > Anyone interested in implementing this feature?
> 
> Thank you for the answer!
> This "practical function" is our only blocking issue in current use cases, though.
> Either TTL or upsert are "nice to have" for us, but the lack of "hot reload" already blocked 2 use cases, because of some internal limitations...
> 
> Um, if both TTL & upsert are available, seems we can also have an alternative solution with (maybe very high) performance overhead...

Get it, once 2.0 stable release done after august, we will definitely take this feature into consideration. So far maybe what you can do is to use A/B collection and switch collection per day by configuration?
 Let's see how many users plus 1 under your request,  if more users are interested we will definitely prioritize the rename funciton.

**Comment by liushu-smartnews** [comment]
> > > > Feature: support collection rename
> > > > Issue: #4812
> > > > Collection rename / alias is CRITICAL for some of our use cases, because the searching side and new collection generating side are completely separate.
> > > > I also left a message under #3821 before, which was merged to #4812.
> > > 
> > > 
> > > collection rename is a practical function. So far we are working on more general mechanisms, so rename is not our first priority.
> > > Anyone interested in implementing this feature?
> > 
> > 
> > Thank you for the answer!
> > This "practical function" is our only blocking issue in current use cases, though.
> > Either TTL or upsert are "nice to have" for us, but the lack of "hot reload" already blocked 2 use cases, because of some internal limitations...
> > Um, if both TTL & upsert are available, seems we can also have an alternative solution with (maybe very high) performance overhead...
> 
> Get it, once 2.0 stable release done after august, we will definitely take this feature into consideration. So far maybe what you can do is to use A/B collection and switch collection per day by configuration?
> Let's see how many users plus 1 under your request, if more users are interested we will definitely prioritize the rename funciton.

Thank you for understanding! I also discussed with our managers yesterday. We will learn more about Milvus v2.0 and evaluate the effort to implement this feature, and possibly we would like to contribute to it. Likely to decide next week or so.

**Comment by yan-rui** [comment]
I want Search In vectorSet/IdSet like 
searchInIdSet(collection_name, id, idSet)
searchInVectorSet(collection_name, vector, vectorSet)
searchInIdSet(collection_name, vector, idSet)
searchInVectorSet(collection_name, id, vectorSet)


In my case, I want to search topk ids from specific Id set which online.

**Comment by xiaofan-luan** [comment]
> I want Search In vectorSet/IdSet like
> searchInIdSet(collection_name, id, idSet)
> searchInVectorSet(collection_name, vector, vectorSet)
> searchInIdSet(collection_name, vector, idSet)
> searchInVectorSet(collection_name, id, vectorSet)
> 
> In my case, I want to search topk ids from specific Id set which online.

We are going to support search by id. Any idea about searchInIdSet and searchInVector is a must? can you list your situation?

**Comment by yan-rui** [comment]
> > I want Search In vectorSet/IdSet like
> > searchInIdSet(collection_name, id, idSet)
> > searchInVectorSet(collection_name, vector, vectorSet)
> > searchInIdSet(collection_name, vector, idSet)
> > searchInVectorSet(collection_name, id, vectorSet)
> > In my case, I want to search topk ids from specific Id set which online.
> 
> We are going to support search by id. Any idea about searchInIdSet and searchInVector is a must? can you list your situation?

In my situation,  recommend system must return online items. Users cant talk with offline people.

**Comment by xiaofan-luan** [comment]
> > > I want Search In vectorSet/IdSet like
> > > searchInIdSet(collection_name, id, idSet)
> > > searchInVectorSet(collection_name, vector, vectorSet)
> > > searchInIdSet(collection_name, vector, idSet)
> > > searchInVectorSet(collection_name, id, vectorSet)
> > > In my case, I want to search topk ids from specific Id set which online.
> > 
> > 
> > We are going to support search by id. Any idea about searchInIdSet and searchInVector is a must? can you list your situation?
> 
> In my situation, recommend system must return online items. Users cant talk with offline people.

if you put all users in one collection and one items in another collection,  you should be able to use uids to query vectors from one collection set, and retrieve similar items from another collection, is that what you need?

**Comment by yan-rui** [comment]
> > > > I want Search In vectorSet/IdSet like
> > > > searchInIdSet(collection_name, id, idSet)
> > > > searchInVectorSet(collection_name, vector, vectorSet)
> > > > searchInIdSet(collection_name, vector, idSet)
> > > > searchInVectorSet(collection_name, id, vectorSet)
> > > > In my case, I want to search topk ids from specific Id set which online.
> > > 
> > > 
> > > We are going to support search by id. Any idea about searchInIdSet and searchInVector is a must? can you list your situation?
> > 
> > 
> > In my situation, recommend system must return online items. Users cant talk with offline people.
> 
> if you put all users in one collection and one items in another collection, you should be able to use uids to query vectors from one collection set, and retrieve similar items from another collection, is that what you need?

In my recommend system(rs), items also are users. They are in one vector space.  
My situation:
I trained all user's vectors saved into milvus.
User A query our rs, meanwhile user B,C,D are online, E is offline. RS must search in [B, C, D]. If I search in whole collection, I may get result include E, which I dont need. 
In social networking software, when a user open a page named  "The people you may want to talk with!", it means "The people(ONLINE) you may want to talk with!". 


 
--
 
英汉翻译:social media



 
--
 
英汉翻译:social media



 
--
 
英汉翻译:social media

**Comment by xiaofan-luan** [comment]
> > > > > I want Search In vectorSet/IdSet like
> > > > > searchInIdSet(collection_name, id, idSet)
> > > > > searchInVectorSet(collection_name, vector, vectorSet)
> > > > > searchInIdSet(collection_name, vector, idSet)
> > > > > searchInVectorSet(collection_name, id, vectorSet)
> > > > > In my case, I want to search topk ids from specific Id set which online.
> > > > 
> > > > 
> > > > We are going to support search by id. Any idea about searchInIdSet and searchInVector is a must? can you list your situation?
> > > 
> > > 
> > > In my situation, recommend system must return online items. Users cant talk with offline people.
> > 
> > 
> > if you put all users in one collection and one items in another collection, you should be able to use uids to query vectors from one collection set, and retrieve similar items from another collection, is that what you need?
> 
> In my recommend system(rs), items also are users. They are in one vector space.
> My situation:
> I trained all user's vectors saved into milvus.
> User A query our rs, meanwhile user B,C,D are online, E is offline. RS must search in [B, C, D]. If I search in whole collection, I may get result include E, which I dont need.
> In social networking software, when a user open a page named "The people you may want to talk with!", it means "The people(ONLINE) you may want to talk with!".

understand，you actually need a separate scalar to illustrate online and offline .  Once Milvus support update this is doable, you can simply update the user's state from 0->1 and 1->0

**Comment by yan-rui** [comment]
> > > > > > I want Search In vectorSet/IdSet like
> > > > > > searchInIdSet(collection_name, id, idSet)
> > > > > > searchInVectorSet(collection_name, vector, vectorSet)
> > > > > > searchInIdSet(collection_name, vector, idSet)
> > > > > > searchInVectorSet(collection_name, id, vectorSet)
> > > > > > In my case, I want to search topk ids from specific Id set which online.
> > > > > 
> > > > > 
> > > > > We are going to support search by id. Any idea about searchInIdSet and searchInVector is a must? can you list your situation?
> > > > 
> > > > 
> > > > In my situation, recommend system must return online items. Users cant talk with offline people.
> > > 
> > > 
> > > if you put all users in one collection and one items in another collection, you should be able to use uids to query vectors from one collection set, and retrieve similar items from another collection, is that what you need?
> > 
> > 
> > In my recommend system(rs), items also are users. They are in one vector space.
> > My situation:
> > I trained all user's vectors saved into milvus.
> > User A query our rs, meanwhile user B,C,D are online, E is offline. RS must search in [B, C, D]. If I search in whole collection, I may get result include E, which I dont need.
> > In social networking software, when a user open a page named "The people you may want to talk with!", it means "The people(ONLINE) you may want to talk with!".
> 
> understand，you actually need a separate scalar to illustrate online and offline . Once Milvus support update this is doable, you can simply update the user's state from 0->1 and 1->0

How to update user's state ？ I cant find api in pymilvus or java sdk.

**Comment by xiaofan-luan** [comment]
> > > > > > > I want Search In vectorSet/IdSet like
> > > > > > > searchInIdSet(collection_name, id, idSet)
> > > > > > > searchInVectorSet(collection_name, vector, vectorSet)
> > > > > > > searchInIdSet(collection_name, vector, idSet)
> > > > > > > searchInVectorSet(collection_name, id, vectorSet)
> > > > > > > In my case, I want to search topk ids from specific Id set which online.
> > > > > > 
> > > > > > 
> > > > > > We are going to support search by id. Any idea about searchInIdSet and searchInVector is a must? can you list your situation?
> > > > > 
> > > > > 
> > > > > In my situation, recommend system must return online items. Users cant talk with offline people.
> > > > 
> > > > 
> > > > if you put all users in one collection and one items in another collection, you should be able to use uids to query vectors from one collection set, and retrieve similar items from another collection, is that what you need?
> > > 
> > > 
> > > In my recommend system(rs), items also are users. They are in one vector space.
> > > My situation:
> > > I trained all user's vectors saved into milvus.
> > > User A query our rs, meanwhile user B,C,D are online, E is offline. RS must search in [B, C, D]. If I search in whole collection, I may get result include E, which I dont need.
> > > In social networking software, when a user open a page named "The people you may want to talk with!", it means "The people(ONLINE) you may want to talk with!".
> > 
> > 
> > understand，you actually need a separate scalar to illustrate online and offline . Once Milvus support update this is doable, you can simply update the user's state from 0->1 and 1->0
> 
> How to update user's state ？ I cant find api in pymilvus or java sdk.

once delete is supported, you can delete the offlined user and maintain a online user vector list

**Comment by xiaofan-luan** [comment]
> > > > > > > I want Search In vectorSet/IdSet like
> > > > > > > searchInIdSet(collection_name, id, idSet)
> > > > > > > searchInVectorSet(collection_name, vector, vectorSet)
> > > > > > > searchInIdSet(collection_name, vector, idSet)
> > > > > > > searchInVectorSet(collection_name, id, vectorSet)
> > > > > > > In my case, I want to search topk ids from specific Id set which online.
> > > > > > 
> > > > > > 
> > > > > > We are going to support search by id. Any idea about searchInIdSet and searchInVector is a must? can you list your situation?
> > > > > 
> > > > > 
> > > > > In my situation, recommend system must return online items. Users cant talk with offline people.
> > > > 
> > > > 
> > > > if you put all users in one collection and one items in another collection, you should be able to use uids to query vectors from one collection set, and retrieve similar items from another collection, is that what you need?
> > > 
> > > 
> > > In my recommend system(rs), items also are users. They are in one vector space.
> > > My situation:
> > > I trained all user's vectors saved into milvus.
> > > User A query our rs, meanwhile user B,C,D are online, E is offline. RS must search in [B, C, D]. If I search in whole collection, I may get result include E, which I dont need.
> > > In social networking software, when a user open a page named "The people you may want to talk with!", it means "The people(ONLINE) you may want to talk with!".
> > 
> > 
> > understand，you actually need a separate scalar to illustrate online and offline . Once Milvus support update this is doable, you can simply update the user's state from 0->1 and 1->0
> 
> How to update user's state ？ I cant find api in pymilvus or java sdk.

once delete is supported, you can delete the offlined user and maintain a online user vector list

**Comment by yan-rui** [comment]
> > > > > > > > I want Search In vectorSet/IdSet like
> > > > > > > > searchInIdSet(collection_name, id, idSet)
> > > > > > > > searchInVectorSet(collection_name, vector, vectorSet)
> > > > > > > > searchInIdSet(collection_name, vector, idSet)
> > > > > > > > searchInVectorSet(collection_name, id, vectorSet)
> > > > > > > > In my case, I want to search topk ids from specific Id set which online.
> > > > > > > 
> > > > > > > 
> > > > > > > We are going to support search by id. Any idea about searchInIdSet and searchInVector is a must? can you list your situation?
> > > > > > 
> > > > > > 
> > > > > > In my situation, recommend system must return online items. Users cant talk with offline people.
> > > > > 
> > > > > 
> > > > > if you put all users in one collection and one items in another collection, you should be able to use uids to query vectors from one collection set, and retrieve similar items from another collection, is that what you need?
> > > > 
> > > > 
> > > > In my recommend system(rs), items also are users. They are in one vector space.
> > > > My situation:
> > > > I trained all user's vectors saved into milvus.
> > > > User A query our rs, meanwhile user B,C,D are online, E is offline. RS must search in [B, C, D]. If I search in whole collection, I may get result include E, which I dont need.
> > > > In social networking software, when a user open a page named "The people you may want to talk with!", it means "The people(ONLINE) you may want to talk with!".
> > > 
> > > 
> > > understand，you actually need a separate scalar to illustrate online and offline . Once Milvus support update this is doable, you can simply update the user's state from 0->1 and 1->0
> > 
> > 
> > How to update user's state ？ I cant find api in pymilvus or java sdk.
> 
> once delete is supported, you can delete the offlined user and maintain a online user vector list
Offline users will come back. How can I get their vectors again?

**Comment by orange-jams** [comment]
Feature: Provides documentation for offline distributed deployment
Issue: #

For some reasons, we can only install offline software. So we hope the community can provide documents about offline Distributed Milvus 2.0 installation。

**Comment by xiaofan-luan** [comment]
> Feature: Provides documentation for offline distributed deployment
> Issue: #6611
> 
> For some reasons, we can only install offline software. So we hope the community can provide documents about offline Distributed Milvus 2.0 installation。

Anyone who has a successfully deploy milvus offline please share your experience.

**Comment by henripal** [comment]
One thing that seems like it would be easy and ***extremely*** valuable would be some way to access the cluster centroids of a given index. I haven't found a good way to do that yet, but I routinely do it in native FAISS

**Comment by xiaofan-luan** [comment]
> One thing that seems like it would be easy and _**extremely**_ valuable would be some way to access the cluster centroids of a given index. I haven't found a good way to do that yet, but I routinely do it in native FAISS

Can you explain the scenario you want to care about centroids?  This may not be a general purpose requirement for milvus because we also support HNSW, ANNOY and other libs, they don't have the idea of centroids

**Comment by henripal** [comment]
For chemistry it's often important to get a diverse set of molecules or to identify chemotypes, and the centroids are a good way to do that!

**Comment by xiaofan-luan** [comment]
> For chemistry it's often important to get a diverse set of molecules or to identify chemotypes, and the centroids are a good way to do that!

gotca. Seems to be a reasonable requirements. If we implement a classification api which returns centroids for a collection that makes to me. Let's wait for some more +1 then we can start working on this

**Comment by yan-rui** [comment]
> > > > > > > > > I want Search In vectorSet/IdSet like
> > > > > > > > > searchInIdSet(collection_name, id, idSet)
> > > > > > > > > searchInVectorSet(collection_name, vector, vectorSet)
> > > > > > > > > searchInIdSet(collection_name, vector, idSet)
> > > > > > > > > searchInVectorSet(collection_name, id, vectorSet)
> > > > > > > > > In my case, I want to search topk ids from specific Id set which online.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > We are going to support search by id. Any idea about searchInIdSet and searchInVector is a must? can you list your situation?
> > > > > > > 
> > > > > > > 
> > > > > > > In my situation, recommend system must return online items. Users cant talk with offline people.
> > > > > > 
> > > > > > 
> > > > > > if you put all users in one collection and one items in another collection, you should be able to use uids to query vectors from one collection set, and retrieve similar items from another collection, is that what you need?
> > > > > 
> > > > > 
> > > > > In my recommend system(rs), items also are users. They are in one vector space.
> > > > > My situation:
> > > > > I trained all user's vectors saved into milvus.
> > > > > User A query our rs, meanwhile user B,C,D are online, E is offline. RS must search in [B, C, D]. If I search in whole collection, I may get result include E, which I dont need.
> > > > > In social networking software, when a user open a page named "The people you may want to talk with!", it means "The people(ONLINE) you may want to talk with!".
> > > > 
> > > > 
> > > > understand，you actually need a separate scalar to illustrate online and offline . Once Milvus support update this is doable, you can simply update the user's state from 0->1 and 1->0
> > > 
> > > 
> > > How to update user's state ？ I cant find api in pymilvus or java sdk.
> > 
> > 
> > once delete is supported, you can delete the offlined user and maintain a online user vector list
> 
> Offline users will come back. How can I get their vectors again?

#6911
