### ISSUE TITLE
Algolia search bar partially failed.

### ISSUE THREAD

**Issue by yzeng25** [milvus-io/milvus#6155]
**Please state your issue using the following template and, most importantly, in English.**
Hi folks,

Sorry to bother you again... The Algolia search bar on the upper left corner on document pages is not working as expected.
**Location of incorrect documentation**
https://milvus.io/cn/docs/v2.0.0/overview.md
and other pages begin with `https://milvus.io/cn/docs/~`

**Describe the problems or issues found in the documentation**
While the Algolia search bar works fine on English docs pages, it failed to return any results on Chinese doc pages. 

**Steps taken to verify documentation is incorrect**
List any steps you have taken:

1. Open Chrome
2. Visit `https://milvus.io/cn/docs/v2.0.0/overview.md`
3. Go to the search bar
4. Type in something that I think will definitely return some results, such as "什么", "数据库", and "向量".
5. Search bar returns no result.

Screenshots below are comparisons.

![image](https://user-images.githubusercontent.com/36651058/123573098-e4314a80-d7ff-11eb-9ae1-ad51fb1c7624.png)

![image](https://user-images.githubusercontent.com/36651058/123573136-f7dcb100-d7ff-11eb-8796-d121cc97a1f3.png)

![image](https://user-images.githubusercontent.com/36651058/123573193-1347bc00-d800-11eb-888d-77db9e36081e.png)

![image](https://user-images.githubusercontent.com/36651058/123573261-32dee480-d800-11eb-81d7-5fd84f0b7bfd.png)

![image](https://user-images.githubusercontent.com/36651058/123573299-42f6c400-d800-11eb-8c17-a8555ff13801.png)

![image](https://user-images.githubusercontent.com/36651058/123573335-52760d00-d800-11eb-8de7-e60781171251.png)

**Suggested fix for documentation**

You should check if the English docs and the Chinese docs are sharing the same Algolia DocSearch.

 If they **are not** sharing the same Algolia DocSearch, returning no results for Chinese docs means that the API key of Algolia DocSearch was not inserted correctly in Chinese docs. Deleting  API key of Algolia DocSearch by accident could also cause this problem. I've had this problem before, check [here](https://github.com/cnrancher/docs-rancher2/wiki/Algolia-DocSearch-%E6%90%9C%E7%B4%A2%E6%A1%86%E5%A4%B1%E6%95%88%E7%9A%84%E6%8E%92%E6%9F%A5%E5%8F%8A%E4%BF%AE%E5%A4%8D%E8%BF%87%E7%A8%8B) for details

If the English docs and the Chinese docs **are** sharing the same Algolia DocSearch, things are bit complicated here. I haven't encountered any issue like this, thus I could not give any advice under this circumstance. 

According to Algolia DocSearch Support team, they would perform a page crawling every 24 hours. Any sort of update(adding/deleting pages) will show up at most 48 hours later, given that there is time zone difference between China and European countries, where Algolia DocSearch base at. In other words, if modifications are not showing up after 48 hours, something must go wrong.

---

## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken:

**Comment by nameczz** [comment]
Yes, we may have some wrong config about Algolia search. 
Algolia search is working in chinese version now.
Thank you for your contribution!

**Comment by yzeng25** [comment]
> Yes, we may have some wrong config about Algolia search.
> Algolia search is working in chinese version now.
> Thank you for your contribution!

Cool! Thank you.
