### ISSUE TITLE
[Chaos] deletion of etcd pod crashes milvus standalone pod

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#6157]
**Describe the bug**
deletion of etcd pod crashes milvus standalone pod

**Steps/Code to reproduce behavior**
1. deploy Milvus 2.0 with standalone mode
2. delete etcd pod

**Expected behavior**
etcd pod restarts successfully

**Actually**
it crashes Milvus standalone pod

- Milvus version (master or released version)
master-20210626-6036ef2

**Additional context**

**Comment by neza2017** [comment]
`milvus 2.0` assumes that `etcd` never goes offline, so when any component has disconnect from `etcd`,  It means that component has offline, so `milvus 2.0` would kill it.

**Comment by yanliang567** [comment]
after Milvus standalone pod back to running state, Milvus is going to work as usual. 
close.
