### ISSUE TITLE
The callback of insert dose not take effect in pymilvus orm

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#6160]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
    def test_insert_async_callback(self):
        collection_w = self.init_collection_wrap(name=cf.gen_unique_str(prefix))
        df = cf.gen_default_dataframe_data(nb=ct.default_nb)
        future, _ = collection_w.insert(data=df, _async=True, _callback=assert_mutation_result)
        future.done()
        assert collection_w.num_entities == ct.default_nb
```
```
def assert_mutation_result(mutation_res):
    log.info(f"The result is {mutation_res}")
    assert mutation_res.insert_count == ct.default_nb
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus              2.0a1.dev53
 pymilvus-orm          2.0a1.dev59

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by DragonDriver** [comment]
According to the implementation of pymilvus, callback function only takes effect when `future.result()` is called.

Why? In fact many callback functions operate on the result of future(for example, the test case here).

Anyway, I will fix this by calling callback functions both when `future.done()` and `future.result()` are called.

**Comment by DragonDriver** [comment]
Already fixed, please retest this. thx

/unassign
/assign @ThreadDao

**Comment by ThreadDao** [comment]
fixed and will close
