### ISSUE TITLE
Automatic item expiration

### ISSUE THREAD

**Issue by liushu-smartnews** [milvus-io/milvus#6162]
Problem:
We continuously update a collection containing items of last 2~3 days, and need to remove outdated items from the collection continuously.

Preferred Solution:
We want Milvus to automatically remove old items with some per-item time-to-live behavior.
E.g. attach expiration timestamps to items, ignore expired items in get/search, and release resources in periodical compactions.

**Comment by yhmo** [comment]
Link to #6601 and #5519

**Comment by yhmo** [comment]
For distribute mode, milvus use Pulsar to transfer operations log, use ETCD to store metadata, use Minio to store data.
For standalone mode, milvus use Rocksmq to transfer operations log, use ETCD to store metadata, use Minio to store data.

Pulsar can natively support retention. The metadata and data must be consist, so it is no need to enable retention for ETCD and Minio.
The #6601 is to make Rocksmq support retention, now the work is done in the v2.0 RC4.

**Comment by Dsantra92** [comment]
Can I work on this issue?

**Comment by xiaofan-luan** [comment]
> Can I work on this issue?

Welcome Dsantra92, assign this issue to you~, let me know you need extra help

**Comment by devkapilbansal** [comment]
Hi @Dsantra92 are you working on this? If not, I would like to look into this

**Comment by Dsantra92** [comment]
@devkapilbansal sure

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan I would like to continue this issue. I am completely new for milvus, it would be great if you can provide some insights on how to approach this issue.

Hi devkapilbansal, welcome! just assigned the issue to you,  let us know what kind of help you want.

**Comment by devkapilbansal** [comment]
Hi @xiaofan-luan,
Can you please provide some more details to work on this issue?

>We continuously update a collection containing items of last 2~3 days, and need to remove outdated items from the collection continuously.
Which part of code handles this responsibility?

**Comment by xiaofan-luan** [comment]
> Hi @xiaofan-luan, Can you please provide some more details to work on this issue?
> 
> > We continuously update a collection containing items of last 2~3 days, and need to remove outdated items from the collection continuously.
> > Which part of code handles this responsibility?

We introduce a mechanissm named compaction in RC8, see https://wiki.lfaidata.foundation/display/MIL/MEP+16+--+Compaction.

Compaction runs in the background, read out the data, and rewrite data back, with all deleted data removed.

If we want to support expire, the first thing is to add a collection schema, such as TTL. Each entity in milvus has a timestamp field,  it is a Hybrid ts and can be converted to physical time.

If ingested entity passed time to live, then we can remove this entity while compaction happened.

Let me know if I explain clearly, thanks~

**Comment by devkapilbansal** [comment]
Hi,
Although I am trying to look into this. I am currently busy and may not get sufficient time to work. Anyone feel free to work on this if it's urgent.

**Comment by Writtic** [comment]
@devkapilbansal @xiaofan-luan I want to assign this issue to me also.

**Comment by sunby** [comment]
> @devkapilbansal @xiaofan-luan Hi, I want to assign this issue to me.

Thanks for your interest! Just like @xiaofan-luan said, you can add this feature in compaction. Compaction related codes are in `internal/datacoord/compaction_trigger.go`, `internal/datacoord/compaction.go` and `internal/datanode/compaction_executor.go`. If you have some questions, you can discuss with @congqixia and me.

BTW, compaction only release resources periodically. But we should also make the data unsearchable in `Query/Search` and this is another challenge for which you can ask @xige-16 if you meet some problems.

**Comment by xiaofan-luan** [comment]
hi writtic, reach me or sunby at slack see if we can give your more information.
for entity remove, we can purge data when compaction happens, which should be simple, but since compaction is background, data may still be valid if it expired.
If we need to handle data visibility, we need to extend time travel to support a range [startTs, endTs), so that data will be filterd out while query

**Comment by Writtic** [comment]
@sunby @xiaofan-luan Hi, I glad to hear your kindness. 
Before contributiing the issue, I setup development environment with devcontainer on VSCode and followed the instruction like `make test-go` command and . But error message came out and there is no authority on docker user to solve the problem (501).

```
Install the project...
-- Install configuration: "Release"
-- Installing: /go/src/github.com/milvus-io/milvus/internal/storage/cwrapper/output/lib/libwrapper.a
make[1]: Leaving directory '/go/src/github.com/milvus-io/milvus/cwrapper_build'
Running go unittests...
Running go unittest under /go/src/github.com/milvus-io/milvus/internal/
ok      github.com/milvus-io/milvus/internal/allocator  0.184s  coverage: 69.6% of statements
ok      github.com/milvus-io/milvus/internal/kv 0.062s  coverage: 100.0% of statements
# github.com/tecbot/gorocksdb
/go/pkg/mod/github.com/tecbot/gorocksdb@v0.0.0-20191217155057-f0fad39f321c/array.go:4:11: fatal error: rocksdb/c.h: No such file or directory
 // #include "rocksdb/c.h"
           ^~~~~~~~~~~~~
compilation terminated.
ok      github.com/milvus-io/milvus/internal/kv/etcd    16.571s coverage: 93.2% of statements
ok      github.com/milvus-io/milvus/internal/kv/mem     0.026s  coverage: 23.8% of statements
ok      github.com/milvus-io/milvus/internal/kv/minio   0.419s  coverage: 80.6% of statements
FAIL    github.com/milvus-io/milvus/internal/kv/rocksdb [build failed]
FAIL
Makefile:125: recipe for target 'test-go' failed
make: *** [test-go] Error 2
```

I'm not sure I miss something.. and also other build commands are failed.

**Comment by congqixia** [comment]
Hi @Writtic. Thanks for the detail information.
The line 
```
 // #include "rocksdb/c.h"
```
indicates that this c dependency is not compile yet. Just check the `Makefile`, `make test-go` will not trigger compilation for RocksDB. I will make a fix PR for this problem.

Quick solution: Run `make all` before run `make test-go`. Feel to to contact us if you have any other questions.

**Comment by Writtic** [comment]
@sunby @xiaofan-luan Hi, I try to contact on Slack but you are inactive. so I ask you a question about this issue here.
I'm wondering it's enough to check files you mentioned on [reply](https://github.com/milvus-io/milvus/issues/6162#issuecomment-987622798) or not.
I'm not sure the entity can be checked on those files.
For now, I looking into `compactor.go` for figuring out how to check the entity during execute condition to merge operation.

**Comment by sunby** [comment]
> @sunby @xiaofan-luan Hi, I tried to contact on Slack but you are inactive. so I ask you a question about this issue here. I'm wondering it's enough to check files you mentioned on [reply](https://github.com/milvus-io/milvus/issues/6162#issuecomment-987622798) or not. I'm not sure the entity can be checked on those files. For now, I looking into `compactor.go` for figuring out how to check the entity during execute condition to compact operation.

Hi, `merge()` in `compactor.go` checks the entity and filters the deleted key. 
`datacoord/compaction_trigger.go` is the entrance of compaction. It defines some triggering conditions of compaction.
`datacoord/compaction.go` saves the compaction status of a task.
`datanode/compactor.go` defines a compaction task and the execution logic.
`datanode/compaction_executor.go` defines a simple scheduler of compaction tasks on datanode.
Grpc interfaces and request/response structures are defined in `data_coord.proto`.
The Grpc interfaces implementation are in `datacoord/services.go` and `datanode/data_node.go`.
If you want to add a config item (i.e. expiration time), you can add it in milvus.yaml and parse it in `datacoord/param_table.go`.

I think these are enough to check the compaction logic. If you still have a question, please let me know :).

**Comment by Writtic** [comment]
@sunby 

Hi, I complete to make expiration logic and now I'm writing test for it. It the meantime, I come up with several ideas for test case.

1. In `Test merge` on `compactor_test.go`, There is `genInsertData()` for generate data with very unrealistic timestamp like `[]int64{3, 4}`. So, I created the mock method `genInsertDataWithExpiredTS()` with appropriate timestamp like the birthday of Golang, 2009-11-10 23:00:00 +0000 UTC, for instance `[]int64{329749364736000000, 329636118528000000}`. 

2. For testing `merge()`, I suppose the current time which is compared to expiration time is matter. So, I added parameter `currentTs Timestamp` on `merge()` method. And then I create mock method, `genTimestamp()`, with the birthday of Golang for testing the feature of expiration.

3. Finally, I tested `merge()` with the mock methods. The result value of `merge()`, `numOfRow`, is zero as expected but `idata` is still one. `idata` is container of inserted data so it can remain with zero rows and the tested result is, I think, fine. But just in case, I wanna hear your opinion.

FYI, Here is the test code.

```
	t.Run("Test merge", func(t *testing.T) {

                ...

		t.Run("Merge with expiration", func(t *testing.T) {
			Params.DataCoordCfg.EnableAutoExpiration = true
			Params.DataCoordCfg.CompactionEntityExpiration = 259200 // 3 days in seconds
			iData := genInsertDataWithExpiredTS()
			meta := NewMetaFactory().GetCollectionMeta(1, "test")

			iblobs, err := getInsertBlobs(100, iData, meta)
			require.NoError(t, err)

			iitr, err := storage.NewInsertBinlogIterator(iblobs, 106)
			require.NoError(t, err)

			mitr := storage.NewMergeIterator([]iterator{iitr})

			dm := map[UniqueID]Timestamp{
				1: 10000,
			}

			ct := &compactionTask{}
			idata, numOfRow, err := ct.merge(mitr, dm, meta.GetSchema(), genTimestamp())
			assert.NoError(t, err)
			assert.Equal(t, int64(0), numOfRow)
			assert.Equal(t, 1, len(idata))
		})
       	})
```

**Comment by xiaofan-luan** [comment]
keep the issue alive~

**Comment by Writtic** [comment]
I leave a question about [Support dynamic schema for collection](https://github.com/milvus-io/milvus/issues/15372) on https://github.com/milvus-io/milvus/issues/15372#issuecomment-1050734942

> Hi, @xiaofan-luan. I have a question about this issue.
> 
> ### To support mutable attribute of collection level
> `CollectionSchema` and `CollectionMeta` doesn't seem to be mutable candidates. Shall I make another `struct` matched to `CollectionID`? Otherwise, just define and implement new task like `UpdateCollectionTask` on DDL request process?

**Comment by xiaofan-luan** [comment]
should be done in 2.2
