### ISSUE TITLE
The timeout of insert dose not take effect in pymilvus orm

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#6167]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
      def test_insert_async_callback_timeout(self):
        nb = 100000
        collection_w = self.init_collection_wrap(name=cf.gen_unique_str(prefix))
        df = cf.gen_default_dataframe_data(nb)
        err_msg = "partitionID of partitionName:p can not be find"
        future, _ = collection_w.insert(data=df, _async=True, _callback=assert_mutation_result, timeout=1)
        future.done()
        with pytest.raises(Exception, match=err_msg):
            future.result()
```
```
Failed: DID NOT RAISE <class 'Exception'>
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus              2.0a1.dev53
 pymilvus-orm          2.0a1.dev59

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by sunby** [comment]
The cost of inserting 100000 is about 0.7s. So this case would not timeout. I set the timout to 0.3 and get DeadlineExceed exception. But this err_msg in this case is wrong. @ThreadDao

**Comment by ThreadDao** [comment]
fixed
