### ISSUE TITLE
 'Connections' object has no attribute 'connect' 

### ISSUE THREAD

**Issue by JiweiZh** [milvus-io/milvus#6176]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
2.0.0 follow milvus documentation guide, when connect to milvus server, AttributeError: 'Connections' object has no attribute 'connect'.

**Environment details**
- centos7.7, docker version 19.03.8

- Milvus version (master or released version)
2.0.0, pymilvus-orm: 0.0.1

**Screenshots**
![image](https://user-images.githubusercontent.com/16006025/123608948-d3013180-d831-11eb-9004-ba4492d7ed1c.png)

![image](https://user-images.githubusercontent.com/16006025/123608988-dc8a9980-d831-11eb-95e4-1a3b2084b4e2.png)

**Comment by czs007** [comment]
@JiweiZh 

Please install the  pre-release version through the following command:
pip install pymilvus-orm==2.0.0rc1
