### ISSUE TITLE
Link error about hello_milvus.py

### ISSUE THREAD

**Issue by shiyu22** [milvus-io/milvus#6183]
**Please state your issue using the following template and, most importantly, in English.**

**Location of incorrect documentation**
https://milvus-io-dev.azurewebsites.net/cn/docs/v2.0.0/hellomilvus.md

**Describe the problems or issues found in the documentation**
When I run hello_milvus.py with the current link,it shows the ERROR:
```
  File "hello_milvus.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
```
So it's a wrong download address, it should be
`wget https://raw.githubusercontent.com/milvus-io/pymilvus-orm/main/examples/hello_milvus.py`

**Comment by shengjun1985** [comment]
It is fixed. Thanks all.
