### ISSUE TITLE
Deleted vectors still present in search results (ivfsq8)

### ISSUE THREAD

**Issue by vipulsharechat** [milvus-io/milvus#6187]
Using CPU version, 1.1.1, docker installation.
However, entities are not there when I try to fetch them using getEntityById

**Comment by shengjun1985** [comment]
Can you provide more information for us?
(1) Multi nodes with Mishards or only one node?
(2) What's the operation sequence and did you call Flush() ?
(3) Is it easy to reproduce?
(4) Once it is reproduced, will the bug be still in the following query or getEntityById?

**Comment by vipulsharechat** [comment]
1) one node
2) used java sdk, called deleteEntityById(), called flush after deletion
3) yes
4) yes

**Comment by shengjun1985** [comment]
Could you provide us a sample code to reproduce it?

**Comment by vipulsharechat** [comment]
```
         List<Long> ids = List.of(533419148L);
        milvus.deleteById("clips", ids);
        milvus.flush("clips");
```

clips is the name of our collection. sdk version we are using is 1.1.0 
Our setup is multiple milvus machines using a shared storage with help of gcsfuse.

**Comment by yhmo** [comment]
@vipulsharechat 
Could you use `docker logs [container id]` to print the  log?

**Comment by vipulsharechat** [comment]
nothing came up in logs, but if I do getEntityById it says can not fetch deleted docs

**Comment by yhmo** [comment]
> getEntityById it says can not fetch deleted docs

“getEntityById it says can not fetch deleted docs”, "it" means logs or status returned by api?

**Comment by vipulsharechat** [comment]
error_code: UNEXPECTED_ERROR
reason: "Failed to load deleted docs: Failed to open file: /var/lib/milvus/db/tables/1611048691489190000/1611405363489124000/deleted_docs, error: No such file or directory"

**Comment by shengjun1985** [comment]
Mishards only contains one write node, and one mysql server. The metadata is stored in the mysql server.
Two writable server will generate conflict/duplicate data.

The read-only server config should be:
```
cluster:
  enable: true
  role: ro
```
The one writable server can config like this:
```
cluster:
  enable: true
  role: rw
```

**Comment by yhmo** [comment]
This issue is caused by multiple writable milvus servers share same db path and metadata service(confirmed in the Slack). Since two milvus server modify metadata at the same time, the metadata doesn't consist with the db data, so the milvus cannot read deleted_docs file from disk.
