### ISSUE TITLE
The behavior of collection init and partition init is not consistent in method "__repr__"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#6193]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
The behavior of collection init and partition init is not consistent in method "__repr__"

in partition init, "__repr__" is rewritten as the following, while it is not in collection.
partition.py::Partition::__init__:
def __repr__(self):
        return json.dumps({
            'name': self.name,
            'description': self.description,
            'num_entities': self.num_entities,
        })

**Steps/Code to reproduce behavior**
N/A

**Expected behavior**
Consistent return

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
- pymilvus-orm latest

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/221

**Comment by xiaocai2333** [comment]
The function __repr__ has been added for Collection. Please check it. @binbinlv

**Comment by binbinlv** [comment]
OK, thanks. Fixed.
