### ISSUE TITLE
Log is written slowly when partition init return "self.num_entities" in "__repr__" method which leads lots of flush operations

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#6195]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Log is written slowly when partition init return "self.num_entities" in "__repr__" method which leads lots of flush operations

**Steps/Code to reproduce behavior**

Representative case:

tests20/python_client/testcases/test_partition.py::TestPartitionParams::test_partition_maximum_partitions

**Expected behavior**
The design of incorporation of Flush and num_entities may need better solution.

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
Milvus-master (latest)
Name: pymilvus
Version: 2.0.0rc2.dev2
Name: pymilvus-orm
Version: 2.0.0rc2.dev3

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/221

**Comment by xiaocai2333** [comment]
/uncc
/cc @binbinlv 
@binbinlv

**Comment by xiaocai2333** [comment]
"num_entities" is no longer included in __repr__ of Collection or Partition. Please check it. @binbinlv

**Comment by binbinlv** [comment]
OK, "num_entities" has been removed as a workaround. This item may be needed to be added back after the improvement of the design of "num_entities" and flush operation.

Close it first.
