### ISSUE TITLE
CUDA: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by anki-code** [milvus-io/milvus#621]
Hello! Thank you for great solution!

I'm trying to use [your starting manual](https://www.milvus.io/docs/en/userguide/example_code/):
1. I have a machine with Ubuntu 18 and GeForce GTX TITAN X
2. I run docker as described [in the manual](https://www.milvus.io/docs/en/userguide/example_code/)
3. Then I try to run [example.py](https://github.com/milvus-io/pymilvus/blob/master/examples/example.py)

I've got the error in the milvus docker container logs:
```
# docker run -t --gpus all -e "TZ=UTC" -p 19530:19530 -p 8080:8080 -v /milv
us/db:/opt/milvus/db -v /milvus/conf:/opt/milvus/conf -v /milvus/logs:/opt/milvus/log
s milvusdb/milvus:latest

    __  _________ _   ____  ______
   /  |/  /  _/ /| | / / / / / __/
  / /|_/ // // /_| |/ / /_/ /\ \
 /_/  /_/___/____/___/\____/___/

Welcome to Milvus!
Milvus Release version: v0.5.3, built at 2019-11-08 12:25.16

Loading configuration from: ../conf/server_config.yaml
Initial log config from: ../conf/log_config.conf
Milvus server start successfully.
Faiss assertion 'err__ == cudaSuccess' failed in void faiss::gpu::runL2Norm(faiss::gpu::Tensor<T, 2, true, IndexType>&, bool, faiss::gpu::Tensor<T, 1, true, IndexType>&, bool, cudaStream_t) [with T = float; TVec = float4; IndexType = int; cudaStream_t = CUstream_st*] at gpu/impl/L2Norm.cu:294; details: CUDA error 209 no kernel image is available for execution on the device
./start_server.sh: line 3:     7 Aborted                 (core dumped) ../bin/milvus_server -c ../conf/server_config.yaml -l ../conf/log_config.conf
```

What I'm doing wrong?

**Comment by JinHai-CN** [comment]
GeForce GTX TITAN X, Compatibility 5.2. Current Milvus support GPU compatibility: 6.0/6.1/7.0/7.5.
In Milvus 0.6.0, you may change the conpile options to support compatibility 5.2 GPU.

**Comment by cydrain** [comment]
close

**Comment by anki-code** [comment]
As I understand right i have 10.1 version of CUDA:
```
# nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
```
And milvus is not compatible for it because supported only 6.0/6.1/7.0/7.5.

I reviewed `build.sh` and it looks like I can't set the version because:
```
GPU_VERSION="OFF"
...
g)
    GPU_VERSION="ON"
```
As you can see I can only ON or OFF the GPU without version.

Could you please give me more detailed instructions. Thanks for fast answer!

**Comment by JinHai-CN** [comment]
GPU_VERSION is used to compile milvus with CUDA or without CUDA. If you want Milvus to work under Compatibility 5.2, you need to change build_faiss chapter of core/src/index/cmake/ThirdPartyPackagesCore.cmake.

You may find:
`    if (KNOWHERE_GPU_VERSION)
        set(FAISS_CONFIGURE_ARGS ${FAISS_CONFIGURE_ARGS}
                "--with-cuda=${CUDA_TOOLKIT_ROOT_DIR}"
                "--with-cuda-arch=-gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75"
                )`

Add one more gencode and code(compute_52 and sm_52) will make milvus work.

**Comment by cydrain** [comment]
We mentioned above is GPU Compute Capability,
In Nvidia's official website,
https://developer.nvidia.com/cuda-gpus#compute
you can get:
GeForce GTX TITAN X | 5.2

While Milvus by default only support GPU Compute Capability 6.0/6.1/7.0/7.5.
You can update above build parameter to let Milvus support GPU Compute Capability 5.2 to let your GPU work.

**Comment by anki-code** [comment]
Thanks for answer! I'll try to build it from sources.

**Comment by anki-code** [comment]
Guys! Could you please help me with step by step guide? I've read the [install from source](https://github.com/milvus-io/milvus/blob/master/install.md) but the best way is to use docker for building.

Could you please help me with the steps like this:
1. Checkout ... code and add `-gencode=arch=compute_52,code=sm_52`
2. Run docker build this command ...
3. Run milvus from new container this command ...

I think it would very helpful for other milvus users as guide to building milvus from sources via docker.

**Comment by JinHai-CN** [comment]
Here is a PR on how to build from source in docker images. But we haven't review it. You might to check it.

**Comment by yhmo** [comment]
If you can read Chinese, please refer to this article:
https://zhuanlan.zhihu.com/p/93304375

**Comment by anki-code** [comment]
> Here is a PR(#601) on how to build from source in docker images. But we haven't reviewed it. You might to check it.

I've built milvus as described in the PR with `-gencode = arch = compute_52, code = sm_52` and it works now! Many thanks!
