### ISSUE TITLE
IVF_PQ search on CPUs when using GPU-version

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#622]
**Describe the bug**
it should run on GPU as expected 

**Steps/Code to reproduce behavior**

**Expected behavior**

**Environment details**
0.6.0-GPU-version
and gpu_enable set true

**Screenshots**

**Additional context**

**Comment by fishpenguin** [comment]
Already fixed by commit [f45df1a](https://github.com/milvus-io/milvus/commit/10d50d2fb768ae731de6511018aac60a9fd4083d)
