### ISSUE TITLE
Failed to run hello milvus guide 

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#6223]
**Please state your issue using the following template and, most importantly, in English.**

**Location of incorrect documentation**
Provide links and line numbers if applicable.

1. python3 hello_pymilvus_orm.py is the wrong command. Downloaded file are named as hello_milvus.py
2.python3 hello_milvus.py failed as

Traceback (most recent call last):
  File "hello_milvus.py", line 88, in <module>
    hello_milvus()
  File "hello_milvus.py", line 81, in hello_milvus
    print(hit, hit.entity.get("random_value"))
AttributeError: 'Hit' object has no attribute 'entity'

**Describe the problems or issues found in the documentation**
A clear and concise description of what you found to be incorrect.

**Steps taken to verify documentation is incorrect**
List any steps you have taken:

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.

---

## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken:

**Comment by PahudPlus** [comment]
Could you please create PR for this?
