### ISSUE TITLE
Found a couple of 404 broken links. 

### ISSUE THREAD

**Issue by PahudPlus** [milvus-io/milvus#6226]
**Please state your issue using the following template and, most importantly, in English.**

A couple of the links on the tutorial page are broken. 

**Location of incorrect documentation**
https://milvus.io/api-reference/pymilvus-orm/v2.0.0rc1/tutorial.html

- The link of "hello milvus"

**Comment by xiaocai2333** [comment]
It has been fixed in 2.0.0rc2, please check it.

**Comment by xiaocai2333** [comment]
@PahudPlus
