### ISSUE TITLE
The getEntityById throws an exception "UNEXPECTED ERROR : Collection or Partition is empty"  when "_default" is passed as partition name parameter

### ISSUE THREAD

**Issue by jeet129** [milvus-io/milvus#6228]
For Milvus java sdk 1.1.0, the getEntityById expects the partition name as one of the parameters. Since we are not creating any explicit partitions for our use case, we are expecting our data to be present in "_default" partition which is the case indeed. 

While making a call to getEntityById if we pass empty string for partition name it works fine, but if we pass "_default" for partition name the getEntityById fails throwing:
`io.milvus.client.AbstractMilvusGrpcClient logError
ERROR: getEntityByID in collection `variance_test100` failed:
error_code: UNEXPECTED_ERROR
reason: "Collection or partition is empty"`

This behaviour looks like a bug to me as deleteEntityById works with empty string as well as passing "_default" as partition name for us.

**Method of installation**
- [ ] Docker/cpu

**Environment details**
- Milvus version (master or released version)
1.1.0

**Configuration file**
Default Settings

**Comment by shengjun1985** [comment]
There is another bug in v1.1.1.
If WAL is enable, deleteEntityById with "_default" partition can not delete the entity.
If WAL is disable, deleteEntityById with "_default" partition can delete the entity.

**Comment by shengjun1985** [comment]
It is fixed in branch 1.1.
If you want to use it as soon as possible, you can checkout the branch and compile it locally.
Otherwise, please wait for the next release.
Thanks you very much.

Reference:
[Install Milvus from Source Code](https://github.com/milvus-io/milvus/blob/1.1/INSTALL.md)
