### ISSUE TITLE
"Install on Kubernetes" is more commonly used. 

### ISSUE THREAD

**Issue by PahudPlus** [milvus-io/milvus#6229]
**Please state your issue using the following template and, most importantly, in English.**

Install on Kubernetes more commonly used. Substitute "Install with Helm" with "Install on Kubernetes" on both standalone and cluster installation. 

**Location of incorrect documentation**
https://milvus.io/docs/v2.0.0/install_standalone-docker.md

**Describe the problems or issues found in the documentation**
A clear and concise description of what you found to be incorrect.

**Steps taken to verify documentation is incorrect**
List any steps you have taken:

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.

---

## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken:

**Comment by YiyunNi** [comment]
https://github.com/zilliztech/milvus-docs/releases/tag/v1.2.3-2.0dev
