### ISSUE TITLE
Need more details about how to do vector search

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus#6232]
In this [milvus docs](https://milvus.io/api-reference/pymilvus-orm/v2.0.alpha/tutorial.html),
- no search params in detail documented
- no good search expression documented
I found this one, but, it's really difficult to understand.  https://github.com/milvus-io/milvus/blob/master/docs/design_docs/query_boolean_expr.md

I think there will be better if we have
- very detailed information about every single parameter
- very comprehensive examples about the new expression parameters

**Comment by xiaofan-luan** [comment]
already finish the document, so close it
