### ISSUE TITLE
Milvus docker will crash after mac sleeping for hours

### ISSUE THREAD

**Issue by nameczz** [milvus-io/milvus#6243]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Milvus docker will crash after mac close the screen for hours

**Steps/Code to reproduce behavior**
1. docker-compose up -d in standalone
2. close mac screen
3. Next day milvus docker will crash and need docker-compose up again.
**Expected behavior**
Milvus docker is still alive after mac sleeping.

**Method of installation**
- [ ] milvusdb/milvus-dev:master-latest

**Environment details**
- Standalone

- Milvus version (master or released version)
2.0-rc1

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by DragonDriver** [comment]
Maybe docker or MacOS caused this issue. See some same issues on [docker-for-mac](https://github.com/docker/for-mac/issues).

How about other container? For example, running a mysql container and check if this container is still alive after mac sleeping.

**Comment by nameczz** [comment]
Other containers is still alive, and i think it's hard to reproduced. 
Next time i will try to get more logs.

**Comment by nameczz** [comment]
![image](https://user-images.githubusercontent.com/20559208/124370511-28629600-dcab-11eb-9957-bd686f04b8ae.png)
![image](https://user-images.githubusercontent.com/20559208/124370513-2c8eb380-dcab-11eb-9f2e-432279493af7.png)
![image](https://user-images.githubusercontent.com/20559208/124370515-31536780-dcab-11eb-8259-c5f462ee4f90.png)
