### ISSUE TITLE
Proxy should provide clients a interface which returns some important metrics, such as deploy version, deploy mode.

### ISSUE THREAD

**Issue by DragonDriver** [milvus-io/milvus#6249]
**Please state your issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I wish I could use Milvus to do [...]

**Describe the solution you'd like**
I want proxy to provide clients a interface which returns some important metrics, such as deploy version, deploy mode, etc. And for now, we cannot divide search requests in the server though the size of search result may exceed the limit of message stream. So we need do this dividing operation in client according to the limit, however, this limit is hard code in client now. If the limit in the server is larger than the limit in the client then everything is OK, but if the limit in the client is larger? So I think it's more reasonable that client get these information from server.

This interface can be named `GetInfos`

```protobuf
service MilvusService {
	rpc GetInfos(GetInfosRequest) returns (GetInfosResponse) {}
}

message GetInfosRequest {
	// maybe server will provide different infos according to the req
	map<string, string> req = 1;
}

message GetInfosResponse {
	common.Status status = 1;
	map<string, string> resp = 2;
}
```

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by xiaofan-luan** [comment]
Agree with having a interface on collecting metrics. Be sure this interface can be integrated with milvus insight.
@nameczz @Tumao727  @shanghaikid  any suggestion on the interface design?

Also search should not rely on this interface, we should solve result streaming issue on another issue

**Comment by shanghaikid** [comment]
I think Milvus should establish some event mechanism, any clients can consume these events.  
Events may contain data operations, single node status, all node status, performance, query/search logs... etc
And all these events can be configured ON/OFF, if performance matters. 

What do you think @xiaofan-luan ?

**Comment by xiaofan-luan** [comment]
@shanghaikid  good point.  We should seperate this into two parts:
1. How we expose some DML,DDL and DCL operations. Since we has pulsar, we can implement certain change data capture operation, and any one interested could just cosume data from stream.
2. How user can query current state, such as node status, code version, some basic metrics (qps, tps, load, latency).

Let's focus on part 2 in this issue? any suggestions about what metrics you may interest?
@DragonDriver ,  can you investigate some other systems? such as cassandra and es, see how they implement this mechanism and share a design doc?

**Comment by shanghaikid** [comment]
@xiaofan-luan 
I list some metrics which I can image: 

### - System info
- system version
- nodes info
  - node name
  - hardware info
    - cpu info
    - memory info
    - capacity info
  - connection info (which node connect to which node)
  - created time
  - updated time
- system configurations

### - System statistics
  - hardware statistics(all and per node)
    - cpu info/usage
    - storage capacity/usage
    - node memory capacity/usage
  - loaded collections/partitions
    - name
    - loaded time
  - collections/partitions count
  - indexes count
  - QPS
  - latency

### - Logs
  - search/query logs
    - ip/time/query parameters
  - system Logs
    - system up/down logs

**Comment by DragonDriver** [comment]
# Milvus Metrics

## How about other system?

### Cassandra

#### Metric Type

There are [six metric types](https://cassandra.apache.org/doc/latest/operating/metrics.html#metric-types) in Cassandra:

- Gauge
- Counter
- Histogram
- Timer
- Latency
- Meter

#### Different Metrics and How they are organized

- Table Metrics
	- Organized Format: `<type=Table><Keyspace><Table><MetricName>`
- Keyspace Metrics
	- Organized Format: `<type=Keyspace><Keyspace><MetricName>`
- ThreadPool Metrics
	- Organized Format: `<type=ThreadPools><Path><ThreadPoolName><MetricName>`
- Client Request Metrics
	- Organized Format: `<type=ClientRequest><RequestType><MetricName>`
- Cached Metrics
	- Organized Format: `<type=Cache><CacheName><MetricName>`
- CQL Metrics
	- Organized Format: `<type=CQL><MetricName>`
- DroppedMessage Metrics
	- Organized Format: `<type=DroppedMessage><Type><MetricName>`
- Streaming Metrics
	- Organized Format: `<type=Streaming><PeerIP><MetricName>`
- Compaction Metrics
	- Organized Format: `<type=Compaction><MetricName>`
- CommitLog Metrics
	- Organized Format: `<type=CommitLog><MetricName>`
- Storage Metrics
	- Organized Format: `<type=Storage><MetricName>`
- HintsService Metrics
	- Organized Format: `<type=HintsService><MetricName>`
- SSTable Index Metrics
	- Organized Format: `<type=Index><RowIndexEntry><MetricName>`
- BufferPool Metrics
	- Organized Format: `<type=BufferPool><MetricName>`
- Client Metrics
	- Organized Format: `<type=Client><MetricName>`
- Batch Metrics
	- Organized Format: `<type=Batch><MetricName>`
- JVM Metrics
	- BufferPool
	- FileDescriptorRatio
	- GarbageCollector
	- Memory
	- MemoryPool

#### How Metrics of Cassandra Work?

Cassandra use DropWizzard Metrics library to manage metrics.

There are serveral ways that report metrics of Cassandra:

- Reporting Via JMX
- Reporting Via HTTP
- Other Reporting
	- STDOUT
	- CSV
	- SLF4J
	- Ganglia
	- Graphite

I don't think the way how Cassandra implements their metrics is suitable for Milvus, Cassandra is totally in Java way. But we can borrow the organized format of metrics from Cassandra.


### ElasticSearch

Reference: [Elasticsearch monitoring metrics](https://www.elastic.co/guide/en/kibana/current/elasticsearch-metrics.html)

#### Different Metrics

- Cluster Overview
- Nodes
	- Node Overview
	- Node Adavanced
- Indices
	- Index Overview
	- Index Adavanced
- Job
- CCR (cross-cluster replication metrics)
- Logs

## Milvus Metrics

Now, we already have metrics system implemented by promethus, these metrics are used by DevOps team to monitoring our Milvus cluster. And in fact these metrics can already be got by [query api of promethus](https://prometheus.io/docs/prometheus/latest/querying/api/). Proxy can provide a grpc interface to expose these metrics to end user. Like DropWizzard Metrics used in Cassandra, there are serveral metric types in promethus:

- Counter
- Gauge
- Histogram
- Summary

Borrowing the organized format of metrics from Cassandra, we can define the grpc interface below:

```protobuf
service MilvusService {
	rpc GetMetrics(GetMetricsRequest) returns (GetMetricsResponse) {}
}

message GetMetricsRequest {
	// request is the jsonic format string, in this way, we can also extend request more easier,
	// for example, as @shanghaikid mentioned above, we can distinguish the metric type in request,
	/*
	{
	    "metric_type": "system_info"
	}
	{
	    "metric_type": "system_statistics"
	}
	{
	    "metric_type": "logs"
	}
	{
	    "metric_type": "all"
	}
	*/
	string request = 1;
}

message GetMetricResponse {
	common.Status status = 1;
	// response is the jsonic format string, in this way, we can also extend response more easier
	// for example
	/*
	{
		"cpu": {
			"type": "Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz",
			"usage": 6,
		},
		"memory": {
			"total": "32000",
			"usage": "12000",
		}
		"loaded_collections": [
			{
				"name": "coll1",
				"loaded_time": "2021/07/05 11:13:44.372 +08:00",
				"loaded_partitions": [
					{
						"name": "partition1",
						"loaded_time": "2021/07/05 11:13:44.372 +08:00",
					},
					...
				]
			},
			...
		],
		"collection_count": 3,
		"partitions_count": [
			{
				"coll1": 2,
			},
			...
		],
		"indexes_count": [
			{
				"coll1": 2,
			},
			...
		],
		"qps": 10096,
		"latency": 0.1
	}
	*/
	string response = 2;
}
```

**Comment by DragonDriver** [comment]
@nameczz @shanghaikid

**Comment by shanghaikid** [comment]
Any updates ? will we have a design doc for this feature? @DragonDriver

**Comment by DragonDriver** [comment]
> Any updates ? will we have a design doc for this feature? @DragonDriver

sorry for my too late response. yeah, i will share a design doc about this later. However, in fact all these metric information listed above are too many to implement in few days. So according to your [feature #90](https://github.com/milvus-io/milvus-insight/issues/90) maybe i wil implement the node connection info part first.

**Comment by DragonDriver** [comment]
I draft a MEP in confluence: [MEP 8  -- Add metrics for proxy](https://wiki.lfaidata.foundation/display/MIL/MEP+8+--+Add+metrics+for+proxy). Can you guys give some suggestions? @shanghaikid @nameczz @xiaofan-luan @czs007
