### ISSUE TITLE
[monitor] The unit of GPU-unilizition-history is wrong

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#625]
![Screenshot_2019-11-30 dashboard3 - Grafana(1)](https://user-images.githubusercontent.com/56623710/69896896-3d649e00-137f-11ea-9c44-cb00aa921b3f.png)
**Describe the bug**

**Steps/Code to reproduce behavior**

**Expected behavior**
it's Gb not Kb

**Environment details**

**Screenshots**

**Additional context**

**Comment by fishpenguin** [comment]
Already fixed. Newest dashboard.json has been sent to zhenxiang and jielin
