### ISSUE TITLE
PrimaryKeyException on https://milvus.io/cn/docs/v2.0.0/hellomilvus.md

### ISSUE THREAD

**Issue by gogo422** [milvus-io/milvus#6251]
There is a PrimaryKeyException on https://milvus.io/cn/docs/v2.0.0/hellomilvus.md.
while create a collection the PAGE is
default_fields = [
    schema.FieldSchema(name="count", dtype=DataType.INT64, is_primary=False),
    schema.FieldSchema(name="score", dtype=DataType.FLOAT),
    schema.FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
]
the parameter is_primary should be True can solve the error~

**Comment by xiaofan-luan** [comment]
> There is a PrimaryKeyException on https://milvus.io/cn/docs/v2.0.0/hellomilvus.md.
> while create a collection the PAGE is
> default_fields = [
> schema.FieldSchema(name="count", dtype=DataType.INT64, is_primary=False),
> schema.FieldSchema(name="score", dtype=DataType.FLOAT),
> schema.FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
> ]
> the parameter is_primary should be True can solve the error~

This document seems to be moved to https://milvus.io/cn/docs/v2.0.0/example_code.md, seems it it already fixed?

**Comment by gogo422** [comment]
It's already fixed. THX
