### ISSUE TITLE
Error message does not specify the reason accurately when search using vector with not matched dim

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#6257]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Error message does not specify the reason accurately when search using vector with not matched dim

**Steps/Code to reproduce behavior**

Code:
>>> from pymilvus_orm import CollectionSchema, FieldSchema
>>> from pymilvus_orm import Collection
>>> from pymilvus_orm import connections
>>> from pymilvus_orm.types import DataType
>>> int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
>>> float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
>>> float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=128)
>>> schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
>>> connections.connect()
>>> import numpy as np
>>> collection = Collection("test_search_collection_binbin_6", schema=schema)
>>> dim = 128
>>> nb = 500
>>> nq = 2
>>> limit = 1000
>>> import random
>>> default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
>>> vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
>>> res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
>>> collection.num_entities
>>> collection.load()
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> len(res[0])
>>> dim = 129
>>> vectors = [[random.random() for _ in range(dim)] for _ in range(nq)]
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")

Results:
Error: <BaseException: (code=1, message=[UnexpectedError] Assert "(field_meta.get_sizeof() == element.line_sizeof_)" at /go/src/github.com/milvus-io/milvus/internal/core/src/query/Plan.cpp:306

)>
Error: <BaseException: (code=1, message=[UnexpectedError] Assert "(field_meta.get_sizeof() == element.line_sizeof_)" at /go/src/github.com/milvus-io/milvus/internal/core/src/query/Plan.cpp:306

)>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pymilvus_orm/collection.py", line 604, in search
    partition_names, output_fields, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 63, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 1043, in search_with_expression
    return handler.search_with_expression(collection_name, data, anns_field, param, limit, expression, partition_names, output_fields, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 63, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 55, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 92, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 622, in search_with_expression
    return self._execute_search_requests(requests, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 63, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 55, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 591, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 582, in _execute_search_requests
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=[UnexpectedError] Assert "(field_meta.get_sizeof() == element.line_sizeof_)" at /go/src/github.com/milvus-io/milvus/internal/core/src/query/Plan.cpp:306

**Expected behavior**
error message: something like "invalid dim" or "dim not matched"

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
milvus: master
Name: pymilvus
Version: 2.0.0rc2.dev4
Name: pymilvus-orm
Version: 2.0.0rc2.dev15

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by DragonDriver** [comment]
Though it's ok to check dimension in the client, I think it's a little complicated. To do this, I need parse the whole schema in client and get dimension in schema information.

**Comment by DragonDriver** [comment]
> Though it's ok to check dimension in the client, I think it's a little complicated. To do this, I need parse the whole schema in client and get dimension in schema information.

@FluorineDog

**Comment by DragonDriver** [comment]
The check was already added into client part. But I think it's also neccessary to give a clear error information in segcore part. @FluorineDog

**Comment by binbinlv** [comment]
Verified and fixed.

milvus: master (ca4a562)
Name: pymilvus
Version: 2.0.0rc2.dev6
Name: pymilvus-orm
Version: 2.0.0rc2.dev17

Results:
>>> dim = 129
>>> vectors = [[random.random() for _ in range(dim)] for _ in range(nq)]
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
...
pymilvus.client.exceptions.ParamError: The dimension of query entities is different from schema
