### ISSUE TITLE
After insert data successfully, describe collection return row count 0.

### ISSUE THREAD

**Issue by nameczz** [milvus-io/milvus#6270]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
After insert data successfully, describe collection return row count 0.

**Steps/Code to reproduce behavior**
1. create collection
2. create partition
3. insert to new partition return success
4. describe collection return  rowcount = 0
5. describe partition return  rowcount = 0

**Expected behavior**
Row count equal insert data counts.

**Method of installation**
- [ ] milvusdb/milvus-dev:master-latest

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
2.0-rc

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by DragonDriver** [comment]
I reproduce this issue. But if i call `Flush` before `GetCollectionStatistics`, the statistics is correct.

**Comment by DragonDriver** [comment]
```python
#!/usr/bin/env python

import sys

sys.path.append("..")
import random
import datetime
from pymilvus import Milvus, DataType
import time

ip = "127.0.0.1"
port = "53100"
port = "19530"

default_float_vec_field_name = "fvec"
dim = 128
nb = 10
nq = 2

def gen_vectors(num, dim, is_normal=True):
    vectors = [[random.random() for _ in range(dim)] for _ in range(num)]
    return vectors

fields = {
    "fields": [
        # {"name": "int32", "type": DataType.INT32},
        {"name": "int64", "type": DataType.INT64, "is_primary": True, "auto_id": True},
        {"name": "float", "type": DataType.FLOAT},
        {"name": default_float_vec_field_name, "type": DataType.FLOAT_VECTOR,
         "params": {"dim": dim},
         "indexes": [{"index_type": "IVF_PQ", "metric_type": "L2"}]},
    ]
}

c = "dadu_river_operation"

if __name__ == "__main__":
    client = Milvus(host=ip, port=port)
    if client.has_collection(c):
        client.drop_collection(c)

    print(f"[{datetime.datetime.now()}] create_collection, begin ...")
    client.create_collection(c, fields)
    print(f"[{datetime.datetime.now()}] create_collection, done ...")

    print(f"[{datetime.datetime.now()}] create_partition, begin ...")
    p = "test_p"
    client.create_partition(c, p)
    print(f"[{datetime.datetime.now()}] create_partition, done ...")

    entities = [
        # {"name": "int32", "type": DataType.INT32, "values": list(range(nb))},
        # {"name": "int64", "type": DataType.INT64, "values": list(range(nb))},
        {"name": "float", "type": DataType.FLOAT, "values": list(range(nb))},
        {"name": default_float_vec_field_name, "type": DataType.FLOAT_VECTOR, "values": gen_vectors(nb, dim)}
    ]

    print(f"[{datetime.datetime.now()}] insert, begin ...")
    print(client.insert(c, entities, p).primary_keys)
    print(f"[{datetime.datetime.now()}] insert, done ...")

    print(f"[{datetime.datetime.now()}] describe_collection, begin ...")
    desc = client.describe_collection(c)
    print(desc)
    print(f"[{datetime.datetime.now()}] describe_collection, done ...")

    print(f"[{datetime.datetime.now()}] get_collection_stats, begin ...")
    stats = client.get_collection_stats(c)
    print(stats)
    print(f"[{datetime.datetime.now()}] get_collection_stats, done ...")

    print(f"[{datetime.datetime.now()}] flush, begin ...")
    client.flush([c])
    print(f"[{datetime.datetime.now()}] flush, done ...")

    print(f"[{datetime.datetime.now()}] get_collection_stats, begin ...")
    stats = client.get_collection_stats(c)
    print(stats)
    print(f"[{datetime.datetime.now()}] get_collection_stats, done ...")
```

[2021-07-02 16:46:42.116149] create_collection, begin ...
[2021-07-02 16:46:42.153380] create_collection, done ...
[2021-07-02 16:46:42.153414] create_partition, begin ...
[2021-07-02 16:46:42.159860] create_partition, done ...
[2021-07-02 16:46:42.159988] insert, begin ...
[426040444636564857, 426040444636564858, 426040444636564859, 426040444636564860, 426040444636564861, 426040444636564862, 426040444636564863, 426040444636564864, 426040444636564865, 426040444636564866]
[2021-07-02 16:46:42.216485] insert, done ...
[2021-07-02 16:46:42.216503] describe_collection, begin ...
{'collection_name': 'dadu_river_operation', 'auto_id': False, 'description': '', 'fields': [{'field_id': 100, 'name': 'int64', 'description': '', 'type': 5, 'params': {}, 'is_primary': True, 'auto_id': True}, {'field_id': 101, 'name': 'float', 'description': '', 'type': 10, 'params': {}, 'is_primary': False, 'auto_id': False}, {'field_id': 102, 'name': 'fvec', 'description': '', 'type': 101, 'params': {'dim': 128}, 'is_primary': False, 'auto_id': False}]}
[2021-07-02 16:46:42.217518] describe_collection, done ...
[2021-07-02 16:46:42.217528] get_collection_stats, begin ...
{'row_count': 0}
[2021-07-02 16:46:42.218307] get_collection_stats, done ...
[2021-07-02 16:46:42.218316] flush, begin ...
[2021-07-02 16:46:45.235523] flush, done ...
[2021-07-02 16:46:45.235546] get_collection_stats, begin ...
{'row_count': 10}
[2021-07-02 16:46:45.236303] get_collection_stats, done ...

**Comment by DragonDriver** [comment]
I think this is a feature instead of bug.

/unkind bug
/kind feature
/unassign
/assign @nameczz

**Comment by nameczz** [comment]
I tried flush after insert. Still not working.
/kind bug

**Comment by xiaofan-luan** [comment]
@DragonDriver  @sunby why this is a feature? If flush is called by user then it should return the actual row count?

**Comment by yanliang567** [comment]
@DragonDriver any updates?
/assign @DragonDriver

**Comment by DragonDriver** [comment]
> I tried flush after insert. Still not working return rowcount = 0.
> /kind bug

`flush` is asynchronous in Milvus, `flush` will return all sealed segments and you may need waiting for these segment state to be `flushed`.

**Comment by DragonDriver** [comment]
> @DragonDriver @sunby why this is a feature? If flush is called by user then it should return the actual row count?

Yeah, when `flush` is done, I mean, all sealed segments are flushed, I think data coordinator should return the actual row count? However, just after `insert` was done, because `insert` is also asynchronous in Milvus, data nodes do not consume the insert message, so the row count is not accurate.

**Comment by nameczz** [comment]
@DragonDriver  I tried flush collection again, it's working now! Thanks
