### ISSUE TITLE
Utility.wait_for_index_building_complete hang without response

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#6272]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Utility.wait_for_index_building_complete hang without response

**Steps/Code to reproduce behavior**
run tests in milvus/tests20/python_client
pytest testcases/test_utility.py::TestUtilityBase::test_wait_index_collection_index  --host _<host>_

**Expected behavior**
return success or timeout, not hang

- Milvus version (master or released version)
master-20210702-07b0989
pymilvus                           2.0.0rc1
pymilvus-orm                       2.0.0rc2.dev4

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Comment by xiaocai2333** [comment]
It seems the wrong interface was called when wrapping the API, and `wait_for_index_building_complete` should be used instead of `wait_for_loading_complete`.
In `/milvus/tests20/python_client/base/utility_wrapper.py` file, line 46:
```
    def wait_for_index_building_complete(self, collection_name, index_name="", timeout=None, using="default",
                                         check_task=None, check_items=None):
        func_name = sys._getframe().f_code.co_name
        res, is_succ = api_request([self.ut.wait_for_loading_complete, collection_name,
                                    index_name, timeout, using])
        check_result = ResponseChecker(res, func_name, check_task, check_items, is_succ,
                                       collection_name=collection_name, index_name=index_name,
                                       timeout=timeout, using=using).run()
        return res, check_result
```

**Comment by yanliang567** [comment]
Fixed the test framework issue
