### ISSUE TITLE
The milvus query will hang when the query node is reduced.

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#6275]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
The milvus query will hang when the query node is reduced.

**Expected behavior**

**Method of installation**
Milvus2.0  Cluster  
helm

- Milvus version (master or released version)
v2.0.0rc1

**Screenshots**
![image](https://user-images.githubusercontent.com/53512883/124233904-f2f06800-db45-11eb-9a36-702c599e050a.png)

**Comment by xige-16** [comment]
I will fix it later

**Comment by xige-16** [comment]
I can't reproduce the issue, did you insert 100w data to the default partition? @JackLCL

**Comment by yanliang567** [comment]
@JackLCL Could you please give more info as requested above?

**Comment by JackLCL** [comment]
> I can't reproduce the issue, did you insert 100w data to the default partition? @JackLCL

Yes, I insert 100w 768d data to  the default partition, and insert 100w 768d data to  the another partition.
Total of 2 million data.

**Comment by JackLCL** [comment]
Here are my test steps:
1. Run milvus2.0 cluster by helm using 8 query nodes
2. insert 100w 768d data to  the default partition, and insert 100w 768d data to the example_partition, total 200w data.
3. create index 
4. load()
5. search()
6. reduce the number of query nodes to 1
7. release()
8. load()
9. search()
When I search after reduce query node to 1, milvus server hang.

**Comment by bigsheeper** [comment]
I'v run a test and it passed, can you retest it again? @JackLCL

**Comment by JackLCL** [comment]
> I'v run a test and it passed, can you retest it again? @JackLCL

OK， I will retest again.

**Comment by xige-16** [comment]
If you start milvus using docker-compose.yaml, you may need to update it. @JackLCL

**Comment by JackLCL** [comment]
> If you start milvus using docker-compose.yaml, you may need to update it. @JackLCL

I am using k8s to deploy milvus cluster.

**Comment by JackLCL** [comment]
My issue is as same as with [#6528](https://github.com/milvus-io/milvus/issues/6528)

**Comment by scsven** [comment]
@JackLCL There are clear steps in #6528, please discuss there.

**Comment by JackLCL** [comment]
> @JackLCL There are clear steps in #6528, please discuss there.

OK
