### ISSUE TITLE
[Chaos] Failed to insert if datanode is in chaos

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#6287]
**Describe the bug**
Failed to insert if datanode is in chaos

**Steps/Code to reproduce behavior**
1. deploy Milvus 2.0 in cluster mode
2. write a loop to insert data 
3. keep deleting datanode pod 

**Expected behavior**
Inserting data succeed when datanode is in chaos

**Actually**
Inserting data failed

Referring to the topology of Milvus 2.0, inserting data returns success when it writes into pulsar. So chaos of datanode should not fail inserting. 

- Milvus version (master or released version)
master-20210702-07b0989
pymilvus                           2.0.0rc2.dev6
pymilvus-orm                       2.0.0rc2.dev17

**Comment by yanliang567** [comment]
[6287.datacoord.log](https://github.com/milvus-io/milvus/files/6758020/6287.datacoord.log)
[6287.datanode.log](https://github.com/milvus-io/milvus/files/6758021/6287.datanode.log)
[6287.rootcoord.log](https://github.com/milvus-io/milvus/files/6758022/6287.rootcoord.log)

**Comment by czs007** [comment]
any update on this ？ @XuanYang-cn

**Comment by XuanYang-cn** [comment]
Yes, @sunby  is working on it

**Comment by XuanYang-cn** [comment]
The reason is that dataCoord's assigning segment will call `watchDmChannel` of datanode if datanode rebooted. So if datanode in chaos, the insert will block until dataCoord discovers datanode.

The solution is to make `watchDmChannel` calls running in background.

**Comment by sunby** [comment]
If DataNode restarts frequently, there will be many PUT events sent by etcd watcher and DELETE events will be sent after ttl (default 10 seconds). And once we receive a PUT event we will init our client which will failed because of the crash of DataNode. So it will block until initing failed. I open a channel to receive events and divide these events to DataNode client in a goroutine. Once we receive a DELETE event. We will delete the DataNode client and all uncompleted events will stop.

**Comment by czs007** [comment]
@sunby  ci not passed

**Comment by yanliang567** [comment]
/unassgin @sunby 
/assign @yanliang567 
reopen for not verified yet

**Comment by yanliang567** [comment]
still repros on master-20210713-d4239f0
pymilvus                           2.0.0rc2.dev14
pymilvus-orm                       2.0.0rc2.dev31

**Comment by sunby** [comment]
I write a loop to insert entries and keep restarting datanode, but I can not reproduce this problem..

**Comment by sunby** [comment]
I just stop the datanode and keep inserting. Still can not reproduce it

**Comment by yanliang567** [comment]
verify on master-20210714-f3a5b46 that inserting succeeds.
But flush requested during chaos hangs
