### ISSUE TITLE
cannot find -l:librocksdb.a

### ISSUE THREAD

**Issue by yyfrankyy** [milvus-io/milvus#6294]
https://github.com/milvus-io/milvus/blob/119ecfc633905fdf7e8b1cd47114427c18c40cf8/internal/kv/rocksdb/cwrapper/build.sh#L13

I found that `librocksdb.a` locates in `lib64` directory

```
$ find . -name librocksdb.a
./internal/kv/rocksdb/cwrapper/output/lib64/librocksdb.a
```

and so as `libarrow.a`, is this platform related?

**Comment by fishpenguin** [comment]
The .a files should be in the cwrapper/output/lib directory in corresponding path of this project.
For example, librocksdb.a should be in milvus/internal/kv/rocksdb/cwrapper/output/lib after build from source.

**Comment by yyfrankyy** [comment]
In my environment, it's compiled and written in the `lib64` folder, and `make all` failed unless I linked it to `lib`, what information can I provide to help investigate it?

**Comment by fishpenguin** [comment]
The .a files shouldn't be written into lib64 folder if you run make all. Did you compiled the .a by your own script?
If so, you may need to create a link in the corresponding .../cwrapper/output/lib and link the file to .a file in lib64.

**Comment by yyfrankyy** [comment]
nope, I just do `make all` in the root directory, I'm not sure if OS's arch affected this.

**Comment by fishpenguin** [comment]
This is a bug that we have fixed right now, in some environment, the lib may be compiled as lib64.
You can pull the latest master branch code, and this bug won't appear.

**Comment by fishpenguin** [comment]
Fixed.
