### ISSUE TITLE
Milvus starts successfully for the first time, then restarts with an error after a while

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#6297]
1.Milvus worked fine in the first week, restarted the service in the second week and reported an error connecting to Milvus
2. Milvus standalone/pymilvus-orm version 2.0.0 rc1 

![微信图片_20210705104301](https://user-images.githubusercontent.com/34296482/124410815-cfaffd80-dd7d-11eb-9c0f-3f6881aa1485.png)

**Comment by jingkl** [comment]
I found this problem with both the distributed version and the standalone version

**Comment by yanliang567** [comment]
@jingkl does Milvus restart itself automatically or what do you do to restart the Milvus service?

**Comment by jingkl** [comment]
> does Milvus restart itself automatically or what do you do to restart the Milvus service?

It will not restart automatically, you need to restart Milvus docker manually
