### ISSUE TITLE
where is the docker-compose.yml file

### ISSUE THREAD

**Issue by isuoge** [milvus-io/milvus#6313]
I can`t get the docker-compose.yml file

 wget https://raw.githubusercontent.com/milvus-io/milvus/master/deployments/docker/standalone/docker-compose.yml -O docker-compose.yml

this command return Connection refused.

**Comment by cydrain** [comment]
if you have cloned Milvus to your home directory, the docker file will be here:
~/milvus/deployments/docker/standalone/docker-compose.yml

try this command
```
wget ~/milvus/deployments/docker/standalone/docker-compose.yml -O docker-compose.yml
```

**Comment by isuoge** [comment]
> if you have cloned Milvus to your home directory, the docker file will be here:
> ~/milvus/deployments/docker/standalone/docker-compose.yml
> 
> try this command
> 
> ```
> wget ~/milvus/deployments/docker/standalone/docker-compose.yml -O docker-compose.yml
> ```

thank you
