### ISSUE TITLE
problem while trying to insert vectors 

### ISSUE THREAD

**Issue by doron1336** [milvus-io/milvus#6314]
hi, I am using milvus 1.0.0 with pymilvus.

my problem accurs while trying to insert 32000 vectors of size 2560, I simply load the vector and use the insert method as described below but the vectors did not save - it still shows zero vectors inside the collection.

I am using python 3.7

windows 10

collection params - param = {'collection_name':'test01', 'dimension':2560,  'metric_type':MetricType.IP}

**Comment by xiaofan-luan** [comment]
> hi, I am using milvus 1.0.0 with pymilvus.
> 
> my problem accurs while trying to insert 32000 vectors of size 2560, I simply load the vector and use the insert method as described below but the vectors did not save - it still shows zero vectors inside the collection.
> 
> I am using python 3.7
> 
> windows 10
> 
> collection params - param = {'collection_name':'test01', 'dimension':2560, 'metric_type':MetricType.IP}

you may want to try flush after insertion?

**Comment by doron1336** [comment]
Thank you for the quick response

The insertion part of the code looks like
Status, IDs = milvus_client.insert(collection_name='test01', records=vectors)
milvus_client.flush()

Yet it doesn't work for some reason

**Comment by yhmo** [comment]
If you check the "Status" returned by insert(), the status will give this error "The amount of data inserted each time cannot exceed 256 MB".
Because milvus doesn't allow insert data size exceed 256MB. Your data size is 32000 * 2560 * 4 = 312.5MB, this value exceeds the limit.

**Comment by yhmo** [comment]
There is an item about this limit in milvus product FAQ: https://milvus.io/docs/v1.1.1/product_faq.md
```
**Is there a volume limit on the vectors inserted each time?**
Vectors inserted each time must not exceed **256** MB.
```

**Comment by doron1336** [comment]
Thank you very much, it is indeed what happened

For future development I hope milvus will support larger volumes
