### ISSUE TITLE
Error running hello_milvus.py

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#6320]
I have two machines, one machine running hello_milvus.py works fine, the other machine is failing, the error screenshot and log file are shown below
milvus /pymilvus orm version is 2.0.0rc1
[log.txt](https://github.com/milvus-io/milvus/files/6767116/log.txt)

![2d893c02-8d81-43e7-8e8d-c3fd14bb4c14](https://user-images.githubusercontent.com/34296482/124537110-da38c880-de4b-11eb-847a-b7f9374d8186.png)

**Comment by xiaocai2333** [comment]
Please check the version of `hello_milvus.py`. I guess its version is not 2.0.0rc1. 
Use this command `wget https://raw.githubusercontent.com/milvus-io/pymilvus-orm/v2.0.0rc1/examples/hello_milvus.py
`.
