### ISSUE TITLE
The arm platform support

### ISSUE THREAD

**Issue by itzhusir** [milvus-io/milvus#6329]
请问有ARM 版本的镜像吗？或者有在ARM平台上编译的步骤吗？

**Comment by xiaofan-luan** [comment]
@shengjun1985 any suggestion on arm compilation?

**Comment by yhmo** [comment]
@itzhusir 
You can search "arm" in the project issues. There are some issues about how to compile milvue on arm. 
#4391 #4423 #4161

We tried compile milvus on arm before, it is a difficult thing. The main problem is, you may face some weird compile errors by some third-parties in different arm platform.
