### ISSUE TITLE
Get milvus information api support in proto

### ISSUE THREAD

**Issue by nameczz** [milvus-io/milvus#6331]
**Please state your issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**
Support get milvus information api in milvus proto.
Like: milvus version , milvus type(standlone or distributed)

**Describe the solution you'd like**
We can get information by proto service.

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by DragonDriver** [comment]
same as #6249
