### ISSUE TITLE
num_entities of collection is not identical to the number of inserted entities under multiple replicas

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#6347]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
num_entities of collection is not identical to the number of inserted entities under multiple replicas

proxy: 2, datanode: 2, querynode:2, indexnode:2

NAME                                         READY   STATUS    RESTARTS   AGE
milvus-testing-datacoord-96b78f749-zmgr5     1/1     Running   0          56m
milvus-testing-datanode-79f4c4bc74-5t5d8     1/1     Running   0          56m
milvus-testing-datanode-79f4c4bc74-lbnb4     1/1     Running   0          56m
milvus-testing-etcd-0                        1/1     Running   0          56m
milvus-testing-indexcoord-6c69cbd5f6-8pfqg   1/1     Running   0          56m
milvus-testing-indexnode-64d4d7784c-552s2    1/1     Running   0          56m
milvus-testing-indexnode-64d4d7784c-zffb2    1/1     Running   0          56m
milvus-testing-minio-7cfb4db88-wscgl         1/1     Running   0          56m
milvus-testing-proxy-6667757878-hz8cc        1/1     Running   0          56m
milvus-testing-proxy-6667757878-rtgzq        1/1     Running   0          56m
milvus-testing-pulsar-84975967c7-442ms       1/1     Running   0          56m
milvus-testing-querycoord-68d9d4b9-zk6fp     1/1     Running   0          56m
milvus-testing-querynode-697b84fc4f-8kz6s    1/1     Running   0          56m
milvus-testing-querynode-697b84fc4f-qznfk    1/1     Running   0          56m
milvus-testing-rootcoord-7c9866649c-7hmmf    1/1     Running   0          56m

**Steps/Code to reproduce behavior**
1 deploy multiple replica environment
2 Run test case:

tests20/python_client/testcases/test_insert.py::TestInsertAsync::test_insert_async_long

Results:
________________________________________________________________________________ TestInsertAsync.test_insert_async_long _________________________________________________________________________________

self = <test_insert.TestInsertAsync object at 0x7f79975df588>

    @pytest.mark.tags(CaseLabel.L2)
    def test_insert_async_long(self):
        """
        target: test insert with async
        method: insert 5w entities with callback func
        expected: verify num entities
        """
        nb = 50000
        collection_w = self.init_collection_wrap(name=cf.gen_unique_str(prefix))
        df = cf.gen_default_dataframe_data(nb)
        future, _ = collection_w.insert(data=df, _async=True)
        future.done()
        mutation_res = future.result()
        assert mutation_res.insert_count == nb
        assert mutation_res.primary_keys == df[ct.default_int64_field_name].values.tolist()
>       assert collection_w.num_entities == nb
E       assert 36339 == 50000
E        +  where 36339 = <base.collection_wrapper.ApiCollectionWrapper object at 0x7f79975cd160>.num_entities

test_insert.py:747: AssertionError

**Expected behavior**
Numbers of entity shows right.

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
- Milvus master
- Name: pymilvus
Version: 2.0.0rc2.dev8
Name: pymilvus-orm
Version: 2.0.0rc2.dev24

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by XuanYang-cn** [comment]
In my computer(one machine), I tried

- 1 proxy
- 2 datanode, indexnode, querynode

The testcase passed. I can't reproduce this problem.

### I'll try 2 proxy next.
(It's a little trick to start 2 proxy in one machine though.)

**Comment by XuanYang-cn** [comment]
> In my computer(one machine), I tried
> 
> * 1 proxy
> * 2 datanode, indexnode, querynode
> 
> The testcase passed. I can't reproduce this problem.
> 
> ### I'll try 2 proxy next.
> (It's a little trick to start 2 proxy in one machine though.)

I tried 2 proxy, still cannot reproduce it.

**Comment by binbinlv** [comment]
Rerun this on the same configuration (both in the same pymilvus/orm version and latest), can not reproduce after several times running (one/multiple process). 

The latest build and pymilvus/orm is OK.
commit: 3387b07

Close it first, will reopen it if it occurs again in the future.
