### ISSUE TITLE
[CPU] Create index PQ should fail if table metric type set Inner Product

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#636]
**Describe the bug**
Since IP is not supported by faiss ivf_pq, creating index with pq should fail when table metric type set as IP.
Currently index could be created successfully

_GPU-version is OK_

**Steps/Code to reproduce behavior**

**Expected behavior**

**Environment details**
0.6.0-CPU-verison

**Screenshots**

**Additional context**

**Comment by Yukikaze-CZR** [comment]
This issue is duplicate of #616
