### ISSUE TITLE
Drop an existing collection without knowing the schema

### ISSUE THREAD

**Issue by peixin-lin** [milvus-io/milvus#6360]
I am new to Milvus. 
This is the problem I am dealing with : 
Some collection was created and the schema used for the collection was not recorded and I no longer need the collection but I am unable to drop it.
According to what I have learned from the documentations, I can :
* list all the existing connections use utility.list_connections() but I cannot see the schemas
* use Collection.schema but I need the schema for creating the instance, which is a paradox

Is there a convenient way to know the schema of existing collection or drop it without creating an instance of it? Please advice.

**Comment by DragonDriver** [comment]
Get the collection object by name and then call collection.drop()?

/assign @xiaocai2333 
/assign @czs007 

example:

```python
coll = Collection(name)
coll.drop()
```

**Comment by yanliang567** [comment]
@DragonDriver @peixin-lin  code sample above works.
/unassign @scsven 
/unassign @czs007 
/assign @peixin-lin

**Comment by yhmo** [comment]
Inactive and close. If still has problem please re-open it.
