### ISSUE TITLE
Refactor proxy, improve the code quality

### ISSUE THREAD

**Issue by DragonDriver** [milvus-io/milvus#6362]
**Please state your issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I wish I could use Milvus to do [...]

**Describe the solution you'd like**
Refactor proxy, improve the code quality.

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by xiaofan-luan** [comment]
why we want to do the refactoring? what part of the code will be affected? you really need unit test before you do refactoring, otherwise you may mess up things. #6361 is probably good start before you do the refactoring
