### ISSUE TITLE
Need API to get milvus configuration

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus#6367]
User would like to see milvus configuration on GUI. so there should be an API or proto file, so that we can check milvus configuration.

**Comment by xiaofan-luan** [comment]
emm, can we do this from k8s side? @zwd1208

**Comment by zwd1208** [comment]
> emm, can we do this from k8s side? @zwd1208

By getting the configmap from the apiserver or use operator mode.  but non k8s deployment cannot be supported.

**Comment by shanghaikid** [comment]
@xiaofan-luan are there any in memory settings be implemented in the future? That means user can adjust settings without restart the server.  

Anyway, we need a way to read Milvus configuration no matter in standalone mode or cluster mode.

**Comment by xiaofan-luan** [comment]
we will need a mechanism to do dynamic configuration and configuration acquisition， guess this is not the first priority for now? We will need to refine this part after milvus 2.0 release
