### ISSUE TITLE
Search stuck problem caused by wrong Load synchronization semantics

### ISSUE THREAD

**Issue by czs007** [milvus-io/milvus#6370]
Imagine that the SDK has the following usage scenarios, and each step is a synchronous operation：
step1	Insert()
step2	Flush()
step3	LoadCollection()
step4	Search()

After step3 is finished, the SDK thinks that all data has been loaded into the memory, which is indeed the case. 

However, the synchronization semantics of the current load operation is that the number of flush segment rows is the same as the number of rows in the QueryNode's memory. For QueryNode, it only means that the Historical segments are loaded into the memory. It does not guarantee that all DMChannels are subscribed.

Thus, when the Search request triggered by the SDK reaches the QueryNode and QueryNode has not completed all the Watch operations of the DMChannel, the results returned to the Proxy after processing the Search request are not complete.

- Milvus version (master or released version)

**Comment by czs007** [comment]
This is the test pipeline where the bug occurs
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-6333/3/pipeline/76/
@xige-16

**Comment by xige-16** [comment]
The queryCoord should provide an interface to show if the specified collection load done.
