### ISSUE TITLE
quey slowly

### ISSUE THREAD

**Issue by thereisck** [milvus-io/milvus#6375]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaofan-luan** [comment]
@thereisck could you please offer more information? what is the dataset, what you query you are running? what milvus version? how do you define slow? otherwise we can't do anything

**Comment by yhmo** [comment]
Performance is not good in v2.0. There is already an issue #5720. Close this one.
