### ISSUE TITLE
Can id be customized?

### ISSUE THREAD

**Issue by Wenorm** [milvus-io/milvus#6379]
Can the id in the returned result be specified when inserting data?

**Comment by xiaofan-luan** [comment]
> Can the id in the returned result be specified when inserting data?

yes you can have your own id. but you have to make sure it is not duplicate

**Comment by shanghaikid** [comment]
what happened if I insert data with duplicated id?

**Comment by xiaofan-luan** [comment]
the later one would overwrite the former one

**Comment by shanghaikid** [comment]
There is no API reference mentioned `autoID`,

https://milvus.io/api-reference/pymilvus-orm/v2.0.0rc1/api/collection.html

**Comment by yanliang567** [comment]
@shanghaikid  auto_id is a property of CollectionSchema, please check the link below:
https://milvus.io/api-reference/pymilvus-orm/v2.0.0rc1/api/schema.html#pymilvus_orm.CollectionSchema

**Comment by yanliang567** [comment]
/assign @Wenorm 
specify auto_id=False in CollectionSchema, would enable you input your own ids:
`dim = 128`
`id_field = FieldSchema(name="cus_id", dtype=DataType.INT64, is_primary=True, description="customized primary id")`
`age_field = FieldSchema(name="age", dtype=DataType.INT64, description="age")`
`embedding_field = FieldSchema(name="embedding", dtype=DataType.FLOAT_VECTOR, dim=dim)`
`schema = CollectionSchema(fields=[id_field, age_field, embedding_field], 
                                                   auto_id=False, 
                                                       description="desc of collection")`
`collection_name1 = "tutorial_1"`
`collection1 = Collection(name=collection_name1, schema=schema)`

**Comment by Wenorm** [comment]
> the later one would overwrite the former one

But I did an experiment, and the data of repeated id was not overwritten.
![image](https://user-images.githubusercontent.com/75149614/125180019-f65faf80-e227-11eb-9920-46a24375c32f.png)

**Comment by xiaofan-luan** [comment]
> > the later one would overwrite the former one
> 
> I did an experiment, the data id is duplicate, but the data is not overwrite.
> ![image](https://user-images.githubusercontent.com/75149614/125180019-f65faf80-e227-11eb-9920-46a24375c32f.png)

emm, good catch, the expected behavior is to merge all data with same id, but it looks like it is not implemented as expected.
Would mind offer you test case so we can fix the bug

**Comment by Wenorm** [comment]
> > > the later one would overwrite the former one
> > 
> > 
> > I did an experiment, the data id is duplicate, but the data is not overwrite.
> > ![image](https://user-images.githubusercontent.com/75149614/125180019-f65faf80-e227-11eb-9920-46a24375c32f.png)
> 
> emm, good catch, the expected behavior is to merge all data with same id, but it looks like it is not implemented as expected.
> Would mind offer you test case so we can fix the bug

This is the test code I used.
 @xiaofan-luan 
`import random
from tqdm import tqdm
import math
from pymilvus_orm import connections, FieldSchema, CollectionSchema, DataType, Collection, list_collections,utility
import time

host='172.88.88.88'
port = '19530'
connections.add_connection(default={"host": host, "port": port})
connections.connect(alias='default')

dim = 768
description="test"
schema = CollectionSchema([
    FieldSchema(name="id", dtype=DataType.INT64, description="primary_field", is_primary=True),
    FieldSchema(name="year", dtype=DataType.INT64, description="year"),
    FieldSchema(name="embedding", dtype=DataType.FLOAT_VECTOR, dim=dim)
], description=description)
collection_name = "test"
collection = Collection(name=collection_name, schema=schema)
partitions = ["2012","2013","2014","2015","2016","2017","2018","2019","2020","2021"]
for partition in partitions:
    collection.create_partition(partition)

def genVector(dim):
    """Generate vector"""
    raw_embedding = [random.random() for _ in range(dim)]
    # Normalized
    sum_ = 0.0
    for num in raw_embedding:
        sum_ += num*num
    sum_ = math.sqrt(sum_)
    embedding = [num/sum_ for num in raw_embedding]
    return embedding

batch = 1000
for year in range(2012, 2022):
    for _ in tqdm(range(2)):
        ids = [random.randint(0,100) for i in range(batch)]
        years = [year for _ in range(batch)]
        embeddings = [genVector(dim) for _ in range(batch)]
        entities = [ids, years, embeddings]
        collection.insert(data=entities, partition_name=str(year))
    utility.get_connection().flush(['test'])

index_param = {
        "metric_type":"L2",
        "index_type":"IVF_FLAT",
        "params":{"nlist":100}
    }
collection.create_index(field_name="embedding", index_params=index_param)

collection.load()
embeddings=[genVector(dim) for _ in range(1)]
search_params = {"metric_type": "L2", "params": {"nprobe": 50}}
limit=100
start=time.time()
results = collection.search(embeddings, 'embedding', search_params, limit, expr=None)
cost=time.time()-start
print(cost)
print(len(results[0]))
result=results[0]
print(result.ids)
print(result.distances)`

**Comment by DragonDriver** [comment]
Proxy don't have the timestamps of search result, so Proxy cannot decide the order of records with same primary key. So I think we should merge these search results in query nodes, or query nodes should return the timestamps of all hit records and then Proxy can merge them. When there are same primary keys in hit records, hit record with greater timestamp should overwrite the record with less timestamp.

How do you think about this?
/assign @bigsheeper 
/assign @FluorineDog

**Comment by hadim** [comment]
My understanding is that the official behaviour should be "new vector with an existing primary key overwrite the previous one" while the current existing behaviour is "new vector with an existing primary key is added while keeping the previous one(s)".

Can you please confirm which one of those statements is actually true in Milvus 2.*? That is quite important to be aware of when dealing with very large vector databases.

_I am talking here about user-provided primary keys obviously._

Also related to https://github.com/milvus-io/milvus/issues/6624

**Comment by yanliang567** [comment]
@xiaofan-luan could you please answer the question from @hadim  above

**Comment by xiaofan-luan** [comment]
> My understanding is that the official behaviour should be "new vector with an existing primary key overwrite the previous one" while the current existing behaviour is "new vector with an existing primary key is added while keeping the previous one(s)".
> 
> Can you please confirm which one of those statements is actually true in Milvus 2.*? That is quite important to be aware of when dealing with very large vector databases.
> 
> _I am talking here about user-provided primary keys obviously._
> 
> Also related to #6624
@DragonDriver @hadim @yanliang567 @ThreadDao 

The plan is to deduplicate while read, thus new vector with similar id will be merged to the latest. There exists two key issues while implement the result merge:

1) As dragondriver mentioned, the merge operation should be a two stage operation. 1) first stage happens on querynode, second stage happend on proxy. We need to return timestamp field to proxy in order to do the merge.

2) Too many same primary keys will cause serious trouble. Say if we have 10 segments, each segments returns 10 duplicate pk entities(Although there maybe a few not deplicated entities, the 10 duplicate ones are the nearest neighbour), after merge we will have only one result, and this does not really make sense to the users. To solve the problem, we will need to change segcore to return not duplicate data, this also left some work to do.

Generally speaking, yes we need to reduce data on read path by timestamp and make sure all the data is returned. but there still left some work to do, we will deliver this ASAP

**Comment by xiaofan-luan** [comment]
close for now
