### ISSUE TITLE
Delete entity by ID in v2.0.0

### ISSUE THREAD

**Issue by peixin-lin** [milvus-io/milvus#6383]
There is a delete_entity_by_id method in previous versions but I didn't see the equivalent in v2.0.0.
Is this feature no longer supported in the future?
Does it mean I have to use v1.x.x if this feature is necessary for me?

**Comment by xiaofan-luan** [comment]
> There is a delete_entity_by_id method in previous versions but I didn't see the equivalent in v2.0.0.
> Is this feature no longer supported in the future?
> Does it mean I have to use v1.x.x if this feature is necessary for me?

we are actively working on this issue. Design doc should be ready by the end of next week, if get lucky milvus 2.0.0 release would support delete by id

**Comment by yhmo** [comment]
Duplicate with #7130. Close this one.
