### ISSUE TITLE
Search (collection.search) is not working from saved collection 

### ISSUE THREAD

**Issue by aquibjaved** [milvus-io/milvus#6384]
**I am trying to use the saved `collection` for doing a search but `collection.search()`stuck and not responding.**

**Description**
I have created a collection named `sentence_only_vector` I have created two field schema

1. id_field : where `is_primary=True` and `auto_id=False`
2. embedding: where my embedding created using distilbert model separately, with `dims=768` in total I have ~ 11 000 vectors

**Steps/Code to reproduce behavior**

1. created ~11000 vectors sized 768 data shape is [11000 x 768] and ids which are int (no negative ints) 
2. Then I used `collection.insert([ids, sentence_only_vectors])` 
3. I created an index with the following params:
    `
       index_param = {
        "metric_type":"L2",
        "index_type":"IVF_FLAT",
        "params":{"nlist":50} }
    `
    `
    field_name = 'embedding'
     collection.create_index(field_name=field_name, index_params=index_param)
     `
4. search part
  ``` 
    collection.load()
    search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
    results = collection.search([sentence_vectors[0]], field_name, param=search_params, limit=10, expr=None)
  ```

Till here everything works as expected.
after this, I shut down everything, and later started the docker service and doing the following steps in order to search from saved collections (my assumption is, it will also load the FAISS index when we load collections using `collection.load()`).

1. This is how I am loading it
 ```
 collection = Collection(name='sentence_only_vector')
 collection.load()
 
 print(collection.schema)
 >>> {"auto_id": false, "description": "desc of collection", "fields": [{"name": "id", "description": "ids of the vectors", "type": 5, "is_primary": true, "auto_id": false}, {"name": "embedding", "description": "", "type": 101, "params": {"dim": 768}}]}
 
 [When I run the following, I am not getting any output kind of code stuck here ]
 * results = collection.search(sentence_vectors[:5], field_name, param=search_params, limit=10, expr=None)
```

**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, Memory)
   McOS BigSur, Memory: 8 GB 2133 MHz LPDDR3

- Milvus version (2.0.0rc1)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`
no changes here

```yaml
paste-file-content-here
```

**This is the code for search**
![Screenshot 2021-07-08 at 1 04 27 PM](https://user-images.githubusercontent.com/14982079/124911550-2b33f280-dfed-11eb-8440-f943ea9cfa5e.png)

**Apologies, if this is something else, **

**Comment by xiaofan-luan** [comment]
thanks for the detailed input, /assign @xige-16 please take a look

**Comment by xige-16** [comment]
Restarting pulsar docker may cause this problem. We are looking for a solution to the issue. You can try not to restart the pulsar service first. @aquibjaved

**Comment by aquibjaved** [comment]
@xige-16 
I guess I am misunderstood, do you mean after indexing not to stop the docker services. if this is the case, yes it was working.
but once I shutdown and restart the services it's not working

**Comment by xige-16** [comment]
> @xige-16
> I guess I am misunderstood, do you mean after indexing not to stop the docker services. if this is the case, yes it was working.
> but once I shutdown and restart the services it's not working

Is your deployment method stand-alone or cluster?

**Comment by aquibjaved** [comment]
> > @xige-16
> > I guess I am misunderstood, do you mean after indexing not to stop the docker services. if this is the case, yes it was working.
> > but once I shutdown and restart the services it's not working
> 
> Is your deployment method stand-alone or cluster?

It's stand-alone

**Comment by xige-16** [comment]
did you set the volume configuration for the minio container in docker compose file, Otherwise you may lose index data after restart docker service.

**Comment by xige-16** [comment]
I can't reproduce the issue, could you provice the log info which can be collected by command docker logs milvus-standalone's container ID, like "docker logs 500adaeb919a"

**Comment by xige-16** [comment]
@aquibjaved

**Comment by aquibjaved** [comment]
Hello @xige-16 
sorry for the late response, 
```
~ ⌚ 9:32:26
$ docker ps
CONTAINER ID   IMAGE                                         COMMAND                  CREATED      STATUS                   PORTS                                           NAMES
2939ff2112bb   milvusdb/milvus:v2.0.0-rc1-20210628-b87baa1   "/tini -- milvus run…"   2 days ago   Up 6 minutes             0.0.0.0:19530->19530/tcp, :::19530->19530/tcp   milvus-standalone
957051fa0e15   quay.io/coreos/etcd:latest                    "etcd -listen-peer-u…"   2 days ago   Up 6 minutes (healthy)   2379-2380/tcp                                   milvus-etcd
e75574447937   minio/minio:RELEASE.2020-12-03T00-03-10Z      "/usr/bin/docker-ent…"   2 days ago   Up 6 minutes (healthy)   9000/tcp                                        milvus-minio
(base)
~ ⌚ 9:32:34
$ docker logs e75574447937

 You are running an older version of MinIO released 6 months ago
 Update: Run `mc admin update`


Attempting encryption of all config, IAM users and policies on MinIO backend
Endpoint:  http://172.18.0.3:9000  http://127.0.0.1:9000

Browser Access:
   http://172.18.0.3:9000  http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
Detected default credentials 'minioadmin:minioadmin', please change the credentials immediately using 'MINIO_ACCESS_KEY' and 'MINIO_SECRET_KEY'
Exiting on signal: TERMINATED
```

**Comment by aquibjaved** [comment]
Here's my docker resource configuration,
the issue I am getting is only after restarting the server, 

![Screenshot 2021-07-09 at 10 25 57 AM](https://user-images.githubusercontent.com/14982079/125048312-12384980-e0a0-11eb-95dc-621f7589f531.png)

I am going to replicate this with half of the data (~6000 vectors [6000x768]),
not sure if this is a space issue or something

**Comment by xige-16** [comment]
> Hello @xige-16
> sorry for the late response,
> 
> ```
> ~ ⌚ 9:32:26
> $ docker ps
> CONTAINER ID   IMAGE                                         COMMAND                  CREATED      STATUS                   PORTS                                           NAMES
> 2939ff2112bb   milvusdb/milvus:v2.0.0-rc1-20210628-b87baa1   "/tini -- milvus run…"   2 days ago   Up 6 minutes             0.0.0.0:19530->19530/tcp, :::19530->19530/tcp   milvus-standalone
> 957051fa0e15   quay.io/coreos/etcd:latest                    "etcd -listen-peer-u…"   2 days ago   Up 6 minutes (healthy)   2379-2380/tcp                                   milvus-etcd
> e75574447937   minio/minio:RELEASE.2020-12-03T00-03-10Z      "/usr/bin/docker-ent…"   2 days ago   Up 6 minutes (healthy)   9000/tcp                                        milvus-minio
> (base)
> ~ ⌚ 9:32:34
> $ docker logs e75574447937
> 
>  You are running an older version of MinIO released 6 months ago
>  Update: Run `mc admin update`
> 
> 
> Attempting encryption of all config, IAM users and policies on MinIO backend
> Endpoint:  http://172.18.0.3:9000  http://127.0.0.1:9000
> 
> Browser Access:
>    http://172.18.0.3:9000  http://127.0.0.1:9000
> 
> Object API (Amazon S3 compatible):
>    Go:         https://docs.min.io/docs/golang-client-quickstart-guide
>    Java:       https://docs.min.io/docs/java-client-quickstart-guide
>    Python:     https://docs.min.io/docs/python-client-quickstart-guide
>    JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
>    .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
> Detected default credentials 'minioadmin:minioadmin', please change the credentials immediately using 'MINIO_ACCESS_KEY' and 'MINIO_SECRET_KEY'
> Exiting on signal: TERMINATED
> ```

You may need to upgrade the version of minio, docker logs xxx would print the log info as bellow:
~/standalone$ docker logs 06cefa5d3007

    __  _________ _   ____  ______    
   /  |/  /  _/ /| | / / / / / __/    
  / /|_/ // // /_| |/ / /_/ /\ \    
 /_/  /_/___/____/___/\____/___/     

Welcome to use Milvus!
Version:   b87baa1
Built:     Mon Jun 28 07:30:31 UTC 2021
GitCommit: b87baa1
GoVersion: go version go1.15.2 linux/amd64

open pid file: /run/milvus/standalone.pid
lock pid file: /run/milvus/standalone.pid
[2021/07/13 08:33:55.672 +00:00] [DEBUG] [mq_factory.go:116] ["RocksmqPath=/var/lib/milvus/rdb_data"]
[2021/07/13 08:33:55.756 +00:00] [DEBUG] [service.go:122] ["grpc init done ..."]
[2021/07/13 08:33:55.757 +00:00] [DEBUG] [mq_factory.go:116] ["RocksmqPath=/var/lib/milvus/rdb_data"]
[2021/07/13 08:33:55.758 +00:00] [DEBUG] [proxy.go:89] [Proxy] [State=Abnormal]
[2021/07/13 08:33:55.760 +00:00] [DEBUG] [service.go:127] ["init params done"]
[2021/07/13 08:33:55.760 +00:00] [DEBUG] [session_util.go:63] ["Session try to connect to etcd"]
[2021/07/13 08:33:55.761 +00:00] [INFO] [logger.go:48] ["parsed scheme: \"endpoint\""]
[2021/07/13 08:33:55.762 +00:00] [INFO] [logger.go:48] ["ccResolverWrapper: sending new addresses to cc: [{etcd:2379  <nil> 0 <nil>}]"]
[2021/07/13 08:33:55.762 +00:00] [DEBUG] [session_util.go:75] ["Sessiont connect to etcd success"]

**Comment by xige-16** [comment]
You also could update your docker-compose.yaml and rerun, we have fix some bug and update docker image. @aquibjaved

**Comment by aquibjaved** [comment]
thank you for the response, 
I updated the minio, in compose file. I had checked the logs.
I will try again with the latest version of minio and also Milvus 

![image](https://user-images.githubusercontent.com/14982079/125424416-cca1ec9d-1b85-4af8-a6dd-294236392e46.png)


> You also could update your docker-compose.yaml and rerun, we have fix some bug and update docker image. @aquibjaved

**Comment by yhmo** [comment]
Milvus v2.0 RC4 has been released on Aug 13. 
I suppose this issue has been resolved. If still has problem, please re-open it.
