### ISSUE TITLE
Download file from minio to local storage

### ISSUE THREAD

**Issue by godchen0212** [milvus-io/milvus#6385]
**Please state your issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I wish I could use Milvus to do [...]
I wish minio kv can have methods to download files from minio to local storage.
This is a sub issue of getEntityByID

**Describe the solution you'd like**
Add two methods to MinIOKV to download files from minio to local storage.
// FGetObject is to get one file downloaded to local storage.
FGetObject(key, localPath string) error
// FGetObjects is to get multify files downloaded to local storage.
FGetObjects(keys []string, localPath string) error

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by xiaofan-luan** [comment]
we'll need a better abstract level for this. hopefully user should not care whether file is get from disk or local disk

**Comment by godchen0212** [comment]
I think there should be an additional abstraction about file reading and writing that is different from the current kv interface. Kv storage and file storage should be two different concepts. I prefer to put file storage interface under the storage package. Now the contents of the storage package are more like serialization and deserialization. @xiaofan-luan

**Comment by xiaofan-luan** [comment]
ok, make sense to me

**Comment by godchen0212** [comment]
#6463 An vector file manager is proposed.
