### ISSUE TITLE
query hangs under multiple replicas

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#6387]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
query hangs under two proxy replicas (proxy: 2, datanode: 2, querynode:2, indexnode:2)

It is good under the following configuration:
(proxy: 1, datanode: 2, querynode:2, indexnode:2)

**Steps/Code to reproduce behavior**
1 configure multiple replicas environment:
 (proxy: 2, datanode: 2, querynode:2, indexnode:2)
2 run test case:
tests20/python_client/testcases/test_query.py::TestQueryBase::test_query

Logs:
bad scenario:
(proxy: 2, datanode: 2, querynode:2, indexnode:2)
[badCaseLog.tar.zip](https://github.com/milvus-io/milvus/files/6784156/badCaseLog.tar.zip)

good scenario:
(proxy: 1, datanode: 2, querynode:2, indexnode:2)
[goodCaseLog.tar.zip](https://github.com/milvus-io/milvus/files/6784158/goodCaseLog.tar.zip)

**Expected behavior**
query works without stuck

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
- milvus master: d972a03
Name: pymilvus
Version: 2.0.0rc2.dev9
Name: pymilvus-orm
Version: 2.0.0rc2.dev27

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by czs007** [comment]
Looks similar to this #6323 

How did you configure two proxy？

**Comment by binbinlv** [comment]
@czs007 OK， I will retry.

You mean how to configure two proxy or why I configure two proxy?

If how to configure:  helm install ...
--set proxy.replicas=2 \

**Comment by binbinlv** [comment]
Verified and fixed.

milvus master :6b4b71b

**Comment by xiaofan-luan** [comment]
Duplicate #6323
