### ISSUE TITLE
Can not connect to gRPC port periodically

### ISSUE THREAD

**Issue by yan-rui** [milvus-io/milvus#6397]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

Can not connect to gRPC port but http port healthy.
There is no error in milvus-21-07-01-15:29-error.log and milvus-21-07-01-15:29-trace.log  

![image](https://user-images.githubusercontent.com/51695497/125017662-3008ad00-e0a6-11eb-9bd2-e3bc6b185b97.png)

**Steps/Code to reproduce behavior**

Cant reproduce because I dont know when it will happen or why it will happen.  It happened 2 times, about 1 week per time.

- Milvus version (master or released version)
1.1.1 cpu docker

**Comment by yan-rui** [comment]
seems like #5398

**Comment by yhmo** [comment]
Analysis in #6547

**Comment by yhmo** [comment]
Close this one, tracked by #6547
