### ISSUE TITLE
Need to get internal search time from API

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus#6399]
As a user, I would like to know how much time does milvus take to do a vector search, for example, 50ms.

Don't know how other database does this, in database or in SDK level?

**Comment by xiaofan-luan** [comment]
we won't support it from API or SDK, user can measure per request from client side.
But we should have metrics to visualize search average latency, 99 latency, 99.9 latency and max latency. 
@czs007 do we have these changes?

**Comment by xiaofan-luan** [comment]
@czs007
