### ISSUE TITLE
The field data in search result contained empty target entry occasionally

### ISSUE THREAD

**Issue by DragonDriver** [milvus-io/milvus#6403]
**Please state your issue using the following template and, most importantly, in English.**

When searching a collection with `output_fields`, query nodes return empty target entry occasionally.

**Comment by shanghaikid** [comment]
I think if user executes search without `output_fields`, milvus should return data with all fields. 

it's kind weird in a program that you get nothing without `output_fields`.

**Comment by DragonDriver** [comment]
> I think if user executes search without `output_fields`, milvus should return data with all fields.
> 
> it's kind weird in a program that you get nothing without `output_fields`.

we can get the primary keys if we search without `output_fields`

**Comment by shanghaikid** [comment]
> > I think if user executes search without `output_fields`, milvus should return data with all fields.
> > it's kind weird in a program that you get nothing without `output_fields`.
> 
> we can get the primary keys and the scores(or distances) if we search without `output_fields`

I think as an application developer, `select *` is the default mind set. if you add `output_fields`, that means a filter applied.   @xiaofan-luan what do you think? 

and still, there is no document that I can find about the `output_fields`.

**Comment by xiaofan-luan** [comment]
> > > I think if user executes search without `output_fields`, milvus should return data with all fields.
> > > it's kind weird in a program that you get nothing without `output_fields`.
> > 
> > 
> > we can get the primary keys and the scores(or distances) if we search without `output_fields`
> 
> I think as an application developer, `select *` is the default mind set. if you add `output_fields`, that means a filter applied. @xiaofan-luan what do you think?
> 
> and still, there is no document that I can find about the `output_fields`.

agree we need clear definition about output fields. 

the behavior empty output_fields make sense to me, otherwise we don't have the way to return only ids(which maybe a useful case if user only want id to query redis/mysql). However, we should have a wildcard matching strategy in output fields such as  "*".

Another way to express this is using "" and nil, "" means you want nothing else rather than id, nil means all output are wanted.
Any suggestion what it the current rule milvus follows?

**Comment by xiaofan-luan** [comment]
@czs007 @DragonDriver

**Comment by xiaofan-luan** [comment]
let's discuss this in a seperate issue.

**Comment by DragonDriver** [comment]
Cannot be reproduced. Close this.
