### ISSUE TITLE
Data insertion failure

### ISSUE THREAD

**Issue by Bennu-Li** [milvus-io/milvus#6406]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
version: milvus2.0 standalone
data: 6881 vectors of 16951 dimensions.

I inserted all the data at once and found the following problem:

2021-07-09 14:53:53,530 ｜ ERROR ｜ grpc_handler.py ｜ handler ｜ 71 ｜ 
Addr [192.168.1.85:19538] bulk_insert
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "keepalive watchdog timeout"
        debug_error_string = "{"created":"@1625813633.483286000","description":"Error received from peer ipv4:192.168.1.85:19538","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"keepalive watchdog timeout","grpc_status":14}"
>
        {'API start': '2021-07-09 14:50:47.261430', 'RPC start': '2021-07-09 14:50:47.261772', 'RPC error': '2021-07-09 14:53:53.530424'}

**Screenshots**
<img width="1855" alt="截屏2021-07-09 下午3 19 07" src="https://user-images.githubusercontent.com/53458891/125039739-66a3ef00-e0c9-11eb-8ed7-d0004d84930a.png">

**Additional context**
There is the logs file:
[c97ab79c690f1a1146b9719324db4b56388ff9b8dce26bcf0c19bd8fa09c102b-json.log](https://github.com/milvus-io/milvus/files/6789549/c97ab79c690f1a1146b9719324db4b56388ff9b8dce26bcf0c19bd8fa09c102b-json.log)

**Comment by Bennu-Li** [comment]
There is the script that i use to tested: 
https://github.com/milvus-io/bootcamp/tree/master/benchmark_test/scripts

The data that I use is randomly generated using numpy.

**Comment by neza2017** [comment]
the proxy log show it's caused by `Timeout`, but the `len(RowData)` is `zero`
```log
{"log":"[2021/07/09 06:54:13.355 +00:00] [DEBUG] [impl.go:1202] [Insert] [role=Proxy-] [msgID=426197226951478606] [timestamp=0] [db=] [collection=test_dim_16951] [partition=_default] [len(RowData)=0] [len(RowIDs)=0]\n","stream":"stdout","time":"2021-07-09T06:54:13.355095342Z"}
{"log":"[2021/07/09 06:54:13.355 +00:00] [DEBUG] [impl.go:1212] [\"Insert Done\"] [error=timeout] [role=Proxy-] [msgID=426197226951478606] [timestamp=0] [db=] [collection=test_dim_16951] [partition=_default] [len(RowData)=0] [len(RowIDs)=0]\n","stream":"stdout","time":"2021-07-09T06:54:13.355122573Z"}
```

**Comment by xiaofan-luan** [comment]
@scsven we need better exception info on this

**Comment by scsven** [comment]
@xiaofan-luan It's a grpc.RpcError raising, now it's raised directly because we cannot give more info. I think it's the best way to let users know that some error of the network happened. Do you have some suggestions?

**Comment by scsven** [comment]
@Bennu-Li Could you provide the version of pymilvus and pymilvus-orm?

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan It's a grpc.RpcError raising, now it's raised directly because we cannot give more info. I think it's the best way to let users know that some error of the network happened. Do you have some suggestions?

yeh, that's why we need to do precheck in pymilvus SDK? from the exception it really looks like a timeout

**Comment by czs007** [comment]
I noticed that in your screenshot, the service port is 19538. Is it deliberately set? @Bennu-Li

**Comment by czs007** [comment]
Another possible reason is that the http proxy  is turned on in the terminal.  @Bennu-Li

**Comment by Bennu-Li** [comment]
> @xiaofan-luan It's a grpc.RpcError raising, now it's raised directly because we cannot give more info. I think it's the best way to let users know that some error of the network happened. Do you have some suggestions?

pymilvus: 2.0.0rc1
pymilvus-orm: 2.0.0rc1

**Comment by Bennu-Li** [comment]
> Another possible reason is that the http proxy is turned on in the terminal. @Bennu-Li

I did turn on the http proxy, I try to turn off the proxy and load data, it works.
