### ISSUE TITLE
Failed to return raw vectors

### ISSUE THREAD

**Issue by neza2017** [milvus-io/milvus#6408]
when search return, milvus 2.0 seems to skip vector field, neither float vector nor binary vector

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [x] Build from source

**Comment by xiaofan-luan** [comment]
good catch, we need a Milvus enhance plan to improve that

**Comment by yhmo** [comment]
The query() api can return raw vectors in latest version rc4.
