### ISSUE TITLE
Support wildcard match on search/query output field

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#6411]
**Please state your issue using the following template and, most importantly, in English.**
Search and query has to specify output field, it not currently it only returns ids.

**Is your feature request related to a problem? Please describe.**
I wish Milvus could support * in output field and retrieve all the field including the vector field.

**Describe the solution you'd like**
add * support in output field. * should not be a valid field name and should be banned at sdk.
we need better document to explain  output field.

**Describe alternatives you've considered**
we can use nil, or the default value as select * , but it maybe confusing and causing performance degradation.
thus we import * directly, it should be easier to understand, and default behavior is not changed.

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by xiaofan-luan** [comment]
@shanghaikid @DragonDriver @czs007 
how do you think this proposal.

**Comment by DragonDriver** [comment]
I will implement this soon.
