### ISSUE TITLE
Only one query node used in searching if 3 querynode replicas deployed

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#6415]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Only one query node used in searching if deployed 3 querynode replicas, the test client generates 100-user concurrent search request during this testing.

![Kubernetes-Compute-Resources-Pod-Grafana (2)](https://user-images.githubusercontent.com/56623710/125054277-a0302680-e0d8-11eb-8752-ff54f5dfce15.png)
![Kubernetes-Compute-Resources-Pod-Grafana (1)](https://user-images.githubusercontent.com/56623710/125054283-a1f9ea00-e0d8-11eb-8d44-8dc297554f92.png)
![Kubernetes-Compute-Resources-Pod-Grafana](https://user-images.githubusercontent.com/56623710/125054287-a2928080-e0d8-11eb-9137-6eaca6c93118.png)

pod names:
```
NAME                                                   READY   STATUS    RESTARTS   AGE
benchmark-dm9h7-1-etcd-0                               1/1     Running   0          38s
benchmark-dm9h7-1-milvus-datacoord-7fccffb97d-g8zk5    1/1     Running   0          39s
benchmark-dm9h7-1-milvus-datanode-744b859975-2sjcq     1/1     Running   0          38s
benchmark-dm9h7-1-milvus-indexcoord-5744599f97-kcv4n   1/1     Running   0          38s
benchmark-dm9h7-1-milvus-indexnode-549d67b968-q4mqd    1/1     Running   0          38s
benchmark-dm9h7-1-milvus-proxy-858844cb57-7cmsz        1/1     Running   0          39s
benchmark-dm9h7-1-milvus-pulsar-758d7895db-t6j8v       1/1     Running   0          38s
benchmark-dm9h7-1-milvus-querycoord-59487bfb6-298xg    1/1     Running   0          39s
benchmark-dm9h7-1-milvus-querynode-d6ff86794-6t9qb     1/1     Running   0          39s
benchmark-dm9h7-1-milvus-querynode-d6ff86794-jfbcq     1/1     Running   0          39s
benchmark-dm9h7-1-milvus-querynode-d6ff86794-pxxsn     1/1     Running   0          39s
benchmark-dm9h7-1-milvus-rootcoord-5bff5c9fc8-rfj7s    1/1     Running   0          39s
```
logs:
https://kibana-dev.zilliz.cc/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-2h,to:now))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,key:kubernetes.pod_name,negate:!f,params:!(benchmark-dm9h7-1-milvus-querynode-d6ff86794-6t9qb),type:phrases,value:benchmark-dm9h7-1-milvus-querynode-d6ff86794-6t9qb),query:(bool:(minimum_should_match:1,should:!((match_phrase:(kubernetes.pod_name:benchmark-dm9h7-1-milvus-querynode-d6ff86794-6t9qb))))))),hideChart:!t,index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))

**Steps/Code to reproduce behavior**
install cluster by helm, set querynode replicas 3.

dataset: sift-10m, use the default segment configuration

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

cluster version with 3 query nodes

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xige-16** [comment]
could you provide all the log file of the three query node? @del-zhenwu

**Comment by del-zhenwu** [comment]
> could you provide all the log file of the three query node? @del-zhenwu

log uri uploaded.

**Comment by xige-16** [comment]
[querynode7.log](https://github.com/milvus-io/milvus/files/6790606/querynode7.log)

**Comment by xige-16** [comment]
the nodeIDs are 4, 7 ,8. there are only two segment when loadCollection, and assigned to node4 and node7, and  two dmChannels also are asisgned to node4 and node7, node7 connect etcd failed but keep alive， so there is only one querynode serving search.

**Comment by xige-16** [comment]
@bigsheeper querynode shouldn't keep alive after connecting etcd.
