### ISSUE TITLE
Call grpc Insert api with empty vector value like [] will cause milvus crash

### ISSUE THREAD

**Issue by nameczz** [milvus-io/milvus#6419]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Call grpc Insert api with empty vector value like [] will cause milvus crash

**Steps/Code to reproduce behavior**
1. connect grpc client
2. create collection
3. insert with empty vector value like [] and other fields has correct data.
4. milvus crash
**Expected behavior**
Not crash, may be throw error instead.

**Method of installation**
- [ ] milvusdb/milvus-dev:master-latest           

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
2.0

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**
![image](https://user-images.githubusercontent.com/20559208/125061101-95c55b00-e0df-11eb-9686-d27364283ee2.png)
**Additional context**

**Comment by scsven** [comment]
@nameczz Please provide the SDK version.

**Comment by nameczz** [comment]
> @nameczz Please provide the SDK version.

It's not pymilvus. I am implement milvus-node-sdk. 
But you can have a try on pymilvus. I think it's same.

**Comment by scsven** [comment]
@nameczz pymilvus made a check before an RPC call, raise an exception if entity is an empty list.

@czs007 Could we add check in Proxy?

**Comment by nameczz** [comment]
Good idea, milvus-node-sdk can check data before an RPC call, too. 
But it still need to fix on Proxy side.

**Comment by czs007** [comment]
> @nameczz pymilvus made a check before an RPC call, raise an exception if entity is an empty list.
> 
> @czs007 Could we add check in Proxy?

LGTM

**Comment by DragonDriver** [comment]
/kind bug
I will fix this soon, thx for pointing this @nameczz

**Comment by DragonDriver** [comment]
Already fixed. Please retest this. thx.

/unassign
/assign @nameczz

**Comment by nameczz** [comment]
I think this is fixed. Thanks!
