### ISSUE TITLE
Server down if set invalid params during running docker 

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#642]
**Describe the bug**
```

Welcome to Milvus!
Milvus Release version: v0.6.0, built at 2019-12-01 05:37.53, with OpenBLAS library.
You are using Milvus GPU edition

Loading configuration from: ../conf/server_config.yaml
Initializing log config from: ../conf/log_config.conf
GPU resources ENABLED !
Error: failed to open database: database is locked: database is locked. Possible reason: the meta system does not work.
/opt/docker-entrypoint.sh: line 7:     6 User defined signal 1   ./start_server.sh
Milvus server is going to shutdown ...

```

```
docker run --runtime=nvidia -it -p 19531:19530 -p 8081:8080 -v conf:/opt/milvus/conf -d registry.zilliz.com/milvus/engine:0.6.0-gpu-ubuntu18.04-release
```
**Steps/Code to reproduce behavior**

**Expected behavior**

**Environment details**
0.6.0

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
Could not reproduce

**Comment by tianyunperfect** [comment]
这个问题还在，我新建docker 的命令如下：
docker run -d --name milvus_cpu \
	-e "TZ=Asia/Shanghai" \
	-p 19530:19530 -p 8080:8080 \
	-v /home/worker/tianyun/milvus/db:/var/lib/milvus/db \
	-v /home/worker/tianyun/milvus/conf:/var/lib/milvus/conf \
	-v /home/worker/tianyun/milvus/logs:/var/lib/milvus/logs \
	milvusdb/milvus:cpu-latest

请问该怎么办？
