### ISSUE TITLE
Improve insert tps on standalone version

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#6422]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
The top tps: 50000+/-
and 70000+/- on milvus 1.0 version

```
insert_batch_size: response_time/tps
client-insert-batch-1000:  0.03/33879.64
client-insert-batch-10000: 0.2/47095.89
client-insert-batch-20000: 0.42/48035.22
client-insert-batch-50000: 1.02/48907.64
client-insert-batch-100000: 1.96/50904.4
client-insert-batch-200000: 4.36/45837.34

```
dataset : sift-1m-128d

**Steps/Code to reproduce behavior**

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaofan-luan** [comment]
one thing we can do is do split batches into 10000 entity per batch, thus it can fully run in parallel and improve the throughput
