### ISSUE TITLE
Server not healthy occasionally if started with 2 indexnode

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#6426]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
NAME                                                   READY   STATUS    RESTARTS   AGE
benchmark-4tx2f-1-etcd-0                               1/1     Running   0          8m29s
benchmark-4tx2f-1-milvus-datacoord-6cdb775c54-2mgsr    1/1     Running   0          8m29s
benchmark-4tx2f-1-milvus-datanode-6b8bd8d95c-rdhzr     1/1     Running   1          8m29s
benchmark-4tx2f-1-milvus-indexcoord-78d9bf7747-sl5tf   1/1     Running   0          8m29s
benchmark-4tx2f-1-milvus-indexnode-8544d788d8-28scg    1/1     Running   0          8m29s
benchmark-4tx2f-1-milvus-indexnode-8544d788d8-f58tf    1/1     Running   0          8m29s
benchmark-4tx2f-1-milvus-proxy-7b559f5889-spj9x        1/1     Running   0          8m29s
benchmark-4tx2f-1-milvus-pulsar-784bf574c6-g4526       1/1     Running   0          8m29s
benchmark-4tx2f-1-milvus-querycoord-659bc968c6-qzxs6   1/1     Running   0          8m29s
benchmark-4tx2f-1-milvus-querynode-56bd8dc9bb-wnh7m    1/1     Running   1          8m29s
benchmark-4tx2f-1-milvus-rootcoord-5c5fc8c78b-2x8rz    1/1     Running   0          8m29s
```
querynode log:
 
https://kibana-dev.zilliz.cc/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-5m,to:now))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,key:kubernetes.pod_name,negate:!f,params:!(benchmark-4tx2f-1-milvus-querynode-56bd8dc9bb-wnh7m),type:phrases,value:benchmark-4tx2f-1-milvus-querynode-56bd8dc9bb-wnh7m),query:(bool:(minimum_should_match:1,should:!((match_phrase:(kubernetes.pod_name:benchmark-4tx2f-1-milvus-querynode-56bd8dc9bb-wnh7m))))))),hideChart:!t,index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))

datanode log:
https://kibana-dev.zilliz.cc/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-10m,to:now))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,key:kubernetes.pod_name,negate:!f,params:!(benchmark-4tx2f-1-milvus-datanode-6b8bd8d95c-rdhzr),type:phrases,value:benchmark-4tx2f-1-milvus-datanode-6b8bd8d95c-rdhzr),query:(bool:(minimum_should_match:1,should:!((match_phrase:(kubernetes.pod_name:benchmark-4tx2f-1-milvus-datanode-6b8bd8d95c-rdhzr))))))),hideChart:!t,index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))
```


ul 10, 2021 @ 12:31:36.407 | [2021/07/10 04:31:36.407 +00:00] [INFO] [data_node.go:205] ["DataNode ctx done"]
-- | --

  | Jul 10, 2021 @ 12:31:36.407 | [2021/07/10 04:31:36.407 +00:00] [ERROR] [session_util.go:229] ["keep alive"] [error="context done"] [stack="github.com/milvus-io/milvus/internal/log.Error\n\t/go/src/github.com/milvus-io/milvus/internal/log/global.go:42\ngithub.com/milvus-io/milvus/internal/util/sessionutil.(*Session).processKeepAliveResponse.func1\n\t/go/src/github.com/milvus-io/milvus/internal/util/sessionutil/session_util.go:229"]

  | Jul 10, 2021 @ 12:31:36.218 | [2021/07/10 04:31:36.218 +00:00] [WARN] [logger.go:51] ["grpc: addrConn.createTransport failed to connect to {benchmark-4tx2f-1-milvus-datacoord:13333 <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp: lookup benchmark-4tx2f-1-milvus-datacoord on 10.96.0.10:53: server misbehaving\". Reconnecting..."]

  | Jul 10, 2021 @ 12:31:36.218 | [2021/07/10 04:31:36.218 +00:00] [INFO] [logger.go:48] ["pickfirstBalancer: HandleSubConnStateChange: 0xc00053e4b0, {TRANSIENT_FAILURE connection error: desc = \"transport: Error while dialing dial tcp: lookup benchmark-4tx2f-1-milvus-datacoord on 10.96.0.10:53: server misbehaving\"}"]


```
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
Maybe this is the reason(#6458 ), it has been fixed. Please retest it.
