### ISSUE TITLE
The total memory usage during indexing deployed with 2 indexnodes is double size as the cpu usage deployed with one indexnode

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#6427]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

one indexnode:
![Kubernetes-Compute-Resources-Pod-Grafana (4)](https://user-images.githubusercontent.com/56623710/125152679-d32df500-e180-11eb-9fe0-bab26f2d44d3.png)

two indexnodes:
![Kubernetes-Compute-Resources-Pod-Grafana (6)](https://user-images.githubusercontent.com/56623710/125152691-de812080-e180-11eb-83cd-f78fcdfa72de.png)
![Kubernetes-Compute-Resources-Pod-Grafana (7)](https://user-images.githubusercontent.com/56623710/125152695-dfb24d80-e180-11eb-8a1b-4eb6997608cf.png)

**Steps/Code to reproduce behavior**
dataset: sift-10m
index: ivf_flat/nlist: 1024
**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
Please retest it. Five days ago, I had a pr(#6459 ) that refactored the task allocation logic of IndexCoord. If this problem persists, please keep a log of IndexCoord and IndexNode.

**Comment by del-zhenwu** [comment]
![Kubernetes-Compute-Resources-Pod-Grafana (10)](https://user-images.githubusercontent.com/56623710/126111149-097d679c-dbea-4de5-85ab-ae8859b2f669.png)
![Kubernetes-Compute-Resources-Pod-Grafana (11)](https://user-images.githubusercontent.com/56623710/126111152-638ff0db-00b8-4701-b4e2-b1b1147a4579.png)

One node used 3.5Gb and anthor used 5Gb
