### ISSUE TITLE
<BaseException: (code=1, message=CreateIndex failed, error = etcdserver: too many operations in txn request)>

### ISSUE THREAD

**Issue by Wenorm** [milvus-io/milvus#6428]
when i create a index for my data, and i get a error <BaseException: (code=1, message=CreateIndex failed, error = etcdserver: too many operations in txn request)>, what is it meaning? I have 100 million vector，and the dimension of vector is 768，ten partition，10 million per partition.

**Comment by xiaofan-luan** [comment]
assign @xiaocai2333 any idea?

**Comment by xiaocai2333** [comment]
I think this is probably a problem with IndexCoord. It takes about 600 segments for 100 million vectors, that is, IndexCoord will receive 600 requests to build indexes, and each request will write Meta to ETCD, but ETCD allows up to 128 concurrent writes at the same time. 
Do we need to write in batches? @xiaofan-luan

**Comment by xiaofan-luan** [comment]
> I think this is probably a problem with IndexCoord. It takes about 600 segments for 100 million vectors, that is, IndexCoord will receive 600 requests to build indexes, and each request will write Meta to ETCD, but ETCD allows up to 128 concurrent writes at the same time.
> Do we need to write in batches? @xiaofan-luan

128 is too small. We probably need to modify the limit to a larger value, say 4096 or higher.
Another thing we should do it add a retry when rate limited by etcd, thus user should not aware of this issue.

**Comment by Wenorm** [comment]
Please provide this support as soon as possible, thank you.

**Comment by Wenorm** [comment]
Is there another way I can successfully index 100 million vectors? @xiaofan-luan

**Comment by xiaocai2333** [comment]
Try inserting in batches of ten, each batch contains 10 million vectors. Then creating index.

**Comment by xiaocai2333** [comment]
What‘s your milvus version? The bug is in rc1, we will have a new release soon. It will fix this.

**Comment by Wenorm** [comment]
> Try inserting in batches of ten, each batch contains 10 million vectors. Then creating index.

This is the way that i try before.

**Comment by Wenorm** [comment]
> What‘s your milvus version? The bug is in rc1, we will have a new release soon. It will fix this.

2.0

**Comment by xiaocai2333** [comment]
rc2 has been released. Try with rc2 version. @Wenorm

**Comment by xiaofan-luan** [comment]
no more information after more than two weeks, close the issue
