### ISSUE TITLE
Does delete entity by id only make effect for searching if I rebuild the index?

### ISSUE THREAD

**Issue by peixin-lin** [milvus-io/milvus#6434]
The version I am using is v1.1.2.

I called the function delete_entity_by_id and search the deleted id immediately after that. 
I found out that the deleted id is still present in the search result.

I delete the entity, drop the index and build the index again. 
This time the deleted id  no longer exists in the search result.

Does that mean if I need the deleted entities no longer showed in the search results, I have to rebuild the index?
Is this case true for every kind of index?

**Comment by shengjun1985** [comment]
After you call flush, the deleting and inserting will make effect.
But our latest 1.x release is v1.1.1. Did you compile the branch 1.1 locally?

**Comment by peixin-lin** [comment]
> After you call flush, the deleting and inserting will make effect.
> But our latest 1.x release is v1.1.1. Did you compile the branch 1.1 locally?

Flush works. Thank you.
Sorry for didn't make it clear. I am using milvus v1.1.1 with pymilvus==v1.1.2.

**Comment by shengjun1985** [comment]
This issue is solved.
And if you have more questions, please continue to contact our community.
