### ISSUE TITLE
collection.num_entities does not return, keeps getting stuck and search error

### ISSUE THREAD

**Issue by Bennu-Li** [milvus-io/milvus#6438]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
version: milvus2.0 standalone
data: 6881 vectors of 16951 dimensions.

pymilvus: 2.0.0rc1
pymilvus-orm: 2.0.0rc1

After i insert data, I use collection.num_entities to see the number of rows but it doesn't return, it keeps getting stuck. 
And i try to search, if limit<8, it works. Otherwise, it reports an error:
<img width="1150" alt="截屏2021-07-12 下午3 12 58" src="https://user-images.githubusercontent.com/53458891/125245920-bb42a680-e323-11eb-8f1e-5e8020e2508a.png">

**Comment by neza2017** [comment]
I have test in my localhost with build `milvus 2.0` from souce, `collection.num_entities` return correct, but failed on search.
```bash
> python main.py --collection test_dim_16951 --load  
dim_16951.npy insert rows 6881  insert milvus time:  19.694791316986084
total insert time:  19.694788694381714
> python main.py --collection test_dim_16951 --rows
6881
> python main.py --collection test_dim_16951 --search_param 1 --performance
{'metric_type': 'L2'}
2021-07-12 15:03:50,317 ｜ INFO ｜ performance_test.py ｜ performance ｜ 50 ｜ begin to search, nq = 1
1 1 0.07430839538574219
1 1 0.0529017448425293
2021-07-12 15:03:50,449 ｜ ERROR ｜ grpc_handler.py ｜ handler ｜ 78 ｜ 
Addr [127.0.0.1:19530] search_with_expression
Excepted error: limit 10 is too large!
	{'API start': '2021-07-12 15:03:50.447969', 'RPC start': '2021-07-12 15:03:50.448089', 'Exception': '2021-07-12 15:03:50.449935'}
2021-07-12 15:03:50,450 ｜ ERROR ｜ milvus_helpers.py ｜ search_vectors ｜ 114 ｜ Failed to search vectors in Milvus: limit 10 is too large!
```
this exception raise from file `pymilvus/client/prepare.py`
```python
if kwargs.get("_deploy_mode", DeployMode.Distributed):
    factor = 10
    max_nq_per_batch = (5 * 1024 * 1024) / (bytes_per_vector * limit * factor)
    max_nq_per_batch = int(max_nq_per_batch)
    if max_nq_per_batch <= 0:
        raise ParamError(f"limit {limit} is too large!")
```
the `dim` of vector is `16951`, so `bytes_per_vector=16951*4=67804`
```python
max_nq_per_batch = (5 * 1024 * 1024) / (bytes_per_vector * limit * factor)
                                = (5 * 1024 * 1024) / (67804 * 10 * 10)
                                = 0.7732405167836706
```
so what does this check do, and why ? can we fix it?
@czs007

**Comment by yanliang567** [comment]
@DragonDriver any updates

**Comment by DragonDriver** [comment]
> @DragonDriver any updates

This is not a bug, it's due to the max message size limit of pulsar. We will increase the throughput of search in next version by changing the search result mechnism in next version. When the milvus side is completed, I will remove the limit in sdk.

/assign @xige-16

**Comment by xige-16** [comment]
If not any update, the issue could be closed. @yanliang567

**Comment by yanliang567** [comment]
verified that 
1. num_entities returns correct
2.  search successfully
on master-20210803-aba234f
pymilvus                           2.0.0rc3.dev16
pymilvus-orm                       2.0.0rc3.dev15
