### ISSUE TITLE
Transport is closing error when multiple search 

### ISSUE THREAD

**Issue by bigsheeper** [milvus-io/milvus#6443]
**Transport is closing error when multiple search **

**Steps/Code to reproduce behavior**
Run `pytest entity/test_search.py -n 12` in tests/python_test

**Expected behavior**
tests timeout

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Comment by xige-16** [comment]
pr #6351 has fix the contex deadline issue , please rerun again @bigsheeper

**Comment by bigsheeper** [comment]
Fixed by #6351
