### ISSUE TITLE
Aync testcase failed with NoneType erorrs

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#6451]
**Describe the bug**
FlushAsync, IndexAsync,  InsertAsync fail 

**Steps/Code to reproduce behavior**
1.  go to /milvus/tests/python_test
2. run test_flush.py::TestFlushAsync::test_flush_async_long_drop_collection     
           test_index.py::TestIndexAsync::test_create_index_callback  
           entity/test_insert.py::TestInsertAsync::test_insert_async

**Expected behavior**
run successfully

**Actually**
FAILED test_flush.py::TestFlushAsync::test_flush_async_long_drop_collection - AttributeError: 'NoneType' object has no attribute 'status'
FAILED test_index.py::TestIndexAsync::test_create_index_callback[get_simple_index8] - AttributeError: 'NoneType' object has no attribute 
FAILED entity/test_insert.py::TestInsertAsync::test_insert_async[1000] - AttributeError: 'NoneType' object has no attribute 'status'

- Milvus version (master or released version)
master-20210712-a8e5fd2
pymilvus                           2.0.0rc2.dev12

not reproduced against:  pymilvus 2.0.0rc2.dev6

**Comment by binbinlv** [comment]
Run test case under multiple replica environment, and reported 'NoneType' object has no attribute '__getitem__', maybe the same issue, so pasted the logs here if could be a help for analysis.

FAILED test_search.py::TestCollectionSearch::test_search_binary_jaccard_flat_index - AttributeError: 'NoneType' object has no attribute '__getitem__'
FAILED test_search.py::TestCollectionSearch::test_search_index_partition_empty - AttributeError: 'NoneType' object has no attribute '__len__'
FAILED test_search.py::TestCollectionSearch::test_search_binary_hamming_flat_index - AttributeError: 'NoneType' object has no attribute '__getitem__'
FAILED test_search.py::TestCollectionSearch::test_search_binary_tanimoto_flat_index - AttributeError: 'NoneType' object has no attribute '__getitem__'

proxy:1, querynode:2, datanode:2, indexnode:2
milvus: d896e31
Name: pymilvus
Version: 2.0.0rc3.dev1
Name: pymilvus-orm
Version: 2.0.0rc3.dev4

Logs:
[log.tar.zip](https://github.com/milvus-io/milvus/files/6809090/log.tar.zip)

**Comment by yanliang567** [comment]
@binbinlv this issue was fixed in rc2, so if it repros again, please file a new issue.

**Comment by binbinlv** [comment]
OK, issue #6495.
