### ISSUE TITLE
Creating Index and automatically load issue

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#6456]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
I want to confirm the following puzzles, thanks:

when the quantity of inserted data is over the minimum requirement for indexing, then

(1) if load before create_index, then not load again, index is actually working or not? If not, why automatically load is not applied to these scenario. for data, only one load is needed.

(2) if a load is a must after create_index before search, but there is no any warnings or hints, then how to distinguish the following test scenario (1) and (3)? After all, there is an automatically load function for new added data.

Three scenarios tested:
(1) load before create_index, and search (load + create_index +search)
     search without any errors, but does index really works?

(2) load after create_index (create_index + load + search)
      assert, issue #6435

(3) load before and after create_index (load + create_index + load + search)
     search without any errors, here I think index must really work, but from the user end, there is no difference between scenario (1) and (3), both search successfully without any errors or warnings.

**Steps/Code to reproduce behavior**
(1) load before create_index (load + create_index)
from pymilvus_orm import CollectionSchema, FieldSchema
from pymilvus_orm import Collection
from pymilvus_orm import connections
from pymilvus_orm.types import DataType
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=128)
schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
connections.connect()
import numpy as np
collection = Collection("test_search_collection_binbin_6", schema=schema)
dim = 128
nb = 5000
nq = 2
limit = 1000
import random
default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
collection.load()
index_params = {"index_type": "IVF_SQ8", "metric_type": "L2", "params": {"nlist": 128}}
collection.create_index(field_name="float_vector", index_params=index_params)
res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> len(res[0])
1000
(2) load after create_index (create_index + load)
issue #6435
(3) load before and after create_index (load + create_index + load + search)
from pymilvus_orm import CollectionSchema, FieldSchema
from pymilvus_orm import Collection
from pymilvus_orm import connections
from pymilvus_orm.types import DataType
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=128)
schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
connections.connect()
import numpy as np
collection = Collection("test_search_collection_binbin_6", schema=schema)
dim = 128
nb = 5000
nq = 2
limit = 1000
import random
default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
collection.load()
index_params = {"index_type": "IVF_SQ8", "metric_type": "L2", "params": {"nlist": 128}}
collection.create_index(field_name="float_vector", index_params=index_params)
collection.load()
res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> len(res[0])
1000

**Expected behavior**
Are there any possibilities that scenario (1) could enable index no matter when load is executed.

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
milvus master
Name: pymilvus
Version: 2.0.0rc2.dev13
Name: pymilvus-orm
Version: 2.0.0rc2.dev30

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xige-16** [comment]
This feature is supported before version 2.0.
/assign

**Comment by xige-16** [comment]
querynode shou load index after index built done on indexNode. @bigsheeper 
/assign @bigsheeper
