### ISSUE TITLE
typo error in core/src/DBImpl.cpp:55

### ISSUE THREAD

**Issue by cydrain** [milvus-io/milvus#646]
**Describe the bug**
Typo error in core/src/DBImpl.cpp:55
static const Status SHUTDOWN_ERROR = Status(DB_ERROR, "Milsvus server is shutdown!");

**Steps/Code to reproduce behavior**
N/A

**Expected behavior**
static const Status SHUTDOWN_ERROR = Status(DB_ERROR, "Milvus server is shutdown!");

**Comment by yhmo** [comment]
Fixed by PR655
