### ISSUE TITLE
Vector file storage

### ISSUE THREAD

**Issue by godchen0212** [milvus-io/milvus#6463]
**Please state your issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**
I want to get pure vector data file without binlog format saved in local storage.

**Describe the solution you'd like**
1.A interface to get local vector file path with file name.
2.If the file exists in local storage, return local file path.
3.If the file not exists in local storage, get the vector binlog from minio storage and decode binlog to get pure vector data. Save the vector data to local stage. And return local file path

Public Interfaces
type FileManager interface {
      GetFile(path string) (string, error)
      PutFile(path string, content []byte) error
      Exist(path string) bool
      ReadFile(path string) []byte
}

A VectorFileManager implements FileManager interface.
type VectorFileManager struct {
      localFileManager  FileManager
      remoteFileManager FileManager

      insertCodec *InsertCodec
}
LocalFileManager is responsible to local file manager. And can be implements with golang os library.
RemoteFileManager is responsible for cloud storage or remote server storage, and will be implemented with minio client now.

**Comment by godchen0212** [comment]
@neza2017 @cydrain @xiaofan-luan

**Comment by xiaofan-luan** [comment]
Share we name it ChunkManager or BlockManager rather than file manager?
also what's the difference of GetFile, ReadFile? 
If I'm correct, GetFile interface is to load from S3 to local disk, and Read load data from local disk to memory?
I would suggest to use load, read, write, exist as the function name.  Also for put is this a write through or write back? didn't see a clear definition

**Comment by godchen0212** [comment]
Thank for the advice. The interfaces has been changed to these for a clear definition.
Public Interfaces
`type ChunkManager interface {
      Load(key string) (string, error)
      Write(key string, content []byte) error
      Exist(key string) bool
      ReadAll(key string) ([]byte, error)
      ReadAt(key string, p []byte, off int64) (n int, err error)
}
`

A VectorChunkManager implements ChunkManager interface.
type VectorChunkManager struct {
      localChunkManager  ChunkManager
      remoteChunkManager ChunkManager

      insertCodec *InsertCodec
}
