### ISSUE TITLE
Unify the usage of query and search

### ISSUE THREAD

**Issue by cydrain** [milvus-io/milvus#6466]
**Please state your issue using the following template and, most importantly, in English.**

**What would you like to be added ?**

**Why is this needed ?**
To unify the usage of "query" and "search".
Rename:
QueryResult    -> SearchResult
SubQueryResult -> SubSearchResult
QueryDataset   -> SearchDataset
QueryInfo      -> SearchInfo
Plan           -> SearchPlan

**Comment by xiaofan-luan** [comment]
nice catch！ milvus 1.0 mixed search and query into the same interface, we probably want to separate it clearly
