### ISSUE TITLE
Search binary results wrong with metrics of Hamming when limit (topK) is bigger than the quantity of inserted entities

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#6469]
#### Describe the bug:
Search binary results wrong with metrics as Hamming

Insert 2 binary entities, and search with limit (topK) 10, then the searched ids in searched results are:
[1, 0, -1, -1, -1, -1, -1, -1, -1, -1]

which should be
[1, 0]

#### Expected behavior:
searched ids should be [1, 0] which is the smaller one of limit (topK) and entities quantity of collection

#### Steps/Code to reproduce:

    def test_search_binary_hamming_flat_index(self):
        """
        target: search binary_collection, and check the result: distance
        method: compare the return distance value with value computed with HAMMING
        expected: the return distance equals to the computed value
        """
        log.info("Test case of search interface: test_search_binary_hamming_flat_index")
        # 1. initialize with binary data
        collection_w, _, binary_raw_vector, insert_ids = \
            self.init_collection_general(prefix, True, 2, is_binary=True)
        # 2. create index
        default_index = {"index_type": "BIN_IVF_FLAT", "params": {"nlist": 128}, "metric_type": "HAMMING"}
        collection_w.create_index("binary_vector", default_index)
        # 3. compute the distance
        collection_w.load()
        query_raw_vector, binary_vectors = cf.gen_binary_vectors(3000, default_dim)
        # 4. search and compare the distance
        search_params = {"metric_type": "HAMMING", "params": {"nprobe": 10}}
        res = collection_w.search(binary_vectors[:default_nq], "binary_vector",
                                  search_params, default_limit, "int64 >= 0",
                                  check_task=CheckTasks.check_search_results,
                                  check_items={"nq": default_nq,
                                               "ids": insert_ids,
                                               "limit": 2})[0]

#### Environment:
- Milvus version(e.g. v1.1.0 or 8b23a93): d4239f0
- SDK version(e.g. pymilvus v2.0.0rc2):
   Name: pymilvus
   Version: 2.0.0rc2.dev12
   Name: pymilvus-orm
   Version: 2.0.0rc2.dev30
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by cydrain** [comment]
working on it
