### ISSUE TITLE
change Mishards to adapt to Milvus at version 0.6.0

### ISSUE THREAD

**Issue by shenchenguo** [milvus-io/milvus#647]
**Is your feature request related to a problem? Please describe.**
Milvus add feature about “partition” to improve query efficiency.
And in meta db table `Tables`, several new fields have been added for the “partition” implementions.
But now Mishards it only works with Milvus at version older than 0.5.3.

**Describe the solution you'd like**
Change Mishards to adapt to Milvus at version 0.6.0.

**Describe alternatives you've considered**
Alter shards/mishards/models.py, add meta fields in Table `Tables`.

**Additional context**

**Comment by JinHai-CN** [comment]
We will release 0.6.0 firstly. After that, we will consider to update mishards for 0.6.0 Milvus.
