### ISSUE TITLE
CPU, Memory and Goroutines usage increase and not released 

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#6483]
#### Describe the bug:
CPU, Memory and Gorutine usage increase and not released after running tests

#### Expected behavior:
The resources should be released after tests completed, but it did not. 

#### Steps/Code to reproduce:
1. deploy Milvus 2.0 with cluster mode
2. go to /milvus/tests20/python_client and run 
pytest testcases/ --host host --tags L0 L1 --workers 4

#### Environment:
- Milvus version(e.g. v1.1.0 or 8b23a93): master-20210713-d4239f0
- SDK version(e.g. pymilvus v2.0.0rc2):
pymilvus                           2.0.0rc2.dev14
pymilvus-orm                       2.0.0rc2.dev31

#### Additional context:
0. after deployment originally(top 1):
CPU: rootcoord-0.04(vcpu)
Mem: proxy- 63M
Goroutines: rootcoord- 0.16k

1. after run test for 1 time(top 3)
CPU: rootcoord-1.28; datanode-1.2; querynode-0.68
Mem: datanode-291M; querynode-169M; rootcoord-134M
Goroutines: datanode-4.2k; querynode- 1.76k; rootcoord-1.6k

2. after run test for 2 times(top 3)
CPU: rootcoord-1.73; datanode-1.6; querynode-0.9
Mem: datanode-392M; querynode-338M; rootcoord-203M
Goroutines: datanode-8.18k; querynode- 3.38k; rootcoord-3.05k

3. after run tests for 3 times(top 3)
CPU: datanode-1.96; rootcoord-1.88; querynode-1.2
Mem: datanode-487M; querynode-413M; rootcoord-283M
Goroutines: datanode-12.12k; querynode-5.01k, rootcoord-4.49k

**Comment by XuanYang-cn** [comment]
Memory raises rapidly on case `testcases/test_partition.py::TestPartitionOperations` in DataNode

**Comment by yanliang567** [comment]
after one night with no requests to milvus, the resource still not released

**Comment by XuanYang-cn** [comment]
**DataNode**
- Running pprof, goroutinue and memory leak is caused by BackGroundGC problem.

**Comment by xiaofan-luan** [comment]
> **DataNode**
> 
> * Running pprof, goroutinue and memory leak is caused by BackGroundGC not working and producer not closed.
> 
> ```
> goroutine profile: total 349
> 32 @ 0x760d05 0x72d00f 0x72cc8b 0x11bb7e5 0x796e01
> #	0x11bb7e4	github.com/apache/pulsar-client-go/pulsar.(*partitionProducer).failTimeoutMessages+0xc4	/home/yangxuan/Github/GO/milvus_env/pkg/mod/github.com/apache/pulsar-client-go@v0.5.0/pulsar/producer_partition.go:458
> 
> 32 @ 0x760d05 0x770e6f 0x11ba645 0x796e01
> #	0x11ba644	github.com/apache/pulsar-client-go/pulsar.(*partitionProducer).runEventsLoop+0xe4	/home/yangxuan/Github/GO/milvus_env/pkg/mod/github.com/apache/pulsar-client-go@v0.5.0/pulsar/producer_partition.go:296
> 
> 32 @ 0x760d05 0x770e6f 0x11c221d 0x796e01
> #	0x11c221c	github.com/apache/pulsar-client-go/pulsar.(*producer).runBackgroundPartitionDiscovery.func1+0x15c	/home/yangxuan/Github/GO/milvus_env/pkg/mod/github.com/apache/pulsar-client-go@v0.5.0/pulsar/producer_impl.go:143
> 
> 32 @ 0x760d05 0x770e6f 0x1287319 0x1286df7 0x796e01
> #	0x1287318	github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).collectInputMessages+0x198	/home/yangxuan/Github/milvus/internal/util/flowgraph/node.go:123
> #	0x1286df6	github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start+0x3b6			/home/yangxuan/Github/milvus/internal/util/flowgraph/node.go:69
> 
> 16 @ 0x760d05 0x72d00f 0x72cc8b 0x11ac446 0x796e01
> #	0x11ac445	github.com/apache/pulsar-client-go/pulsar.(*partitionConsumer).runEventsLoop+0xe5	/home/yangxuan/Github/GO/milvus_env/pkg/mod/github.com/apache/pulsar-client-go@v0.5.0/pulsar/consumer_partition.go:793
> 
> 16 @ 0x760d05 0x72d00f 0x72cc8b 0x12088e7 0x796e01
> #	0x12088e6	github.com/milvus-io/milvus/internal/util/mqclient.(*pulsarConsumer).Chan.func1+0xa6	/home/yangxuan/Github/milvus/internal/util/mqclient/pulsar_consumer.go:40
> 
> 16 @ 0x760d05 0x770e6f 0x11ab6d1 0x796e01
> #	0x11ab6d0	github.com/apache/pulsar-client-go/pulsar.(*partitionConsumer).dispatcher+0x250	/home/yangxuan/Github/GO/milvus_env/pkg/mod/github.com/apache/pulsar-client-go@v0.5.0/pulsar/consumer_partition.go:646
> 
> 16 @ 0x760d05 0x770e6f 0x11b6c2a 0x796e01
> #	0x11b6c29	github.com/apache/pulsar-client-go/pulsar.(*negativeAcksTracker).track+0x5a9	/home/yangxuan/Github/GO/milvus_env/pkg/mod/github.com/apache/pulsar-client-go@v0.5.0/pulsar/negative_acks_tracker.go:81
> 
> 16 @ 0x760d05 0x770e6f 0x11c06fd 0x796e01
> #	0x11c06fc	github.com/apache/pulsar-client-go/pulsar.(*consumer).runBackgroundPartitionDiscovery.func1+0x15c	/home/yangxuan/Github/GO/milvus_env/pkg/mod/github.com/apache/pulsar-client-go@v0.5.0/pulsar/consumer_impl.go:232
> ```

good catch

**Comment by XuanYang-cn** [comment]
After #6551, BackGroundGC in datanode works as expected, no flowgraph goroutinue is leaking.

working on #6552 now.
