### ISSUE TITLE
Memory usage steadily rising during concurrently inserting 

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#6484]
#### Describe the bug:
![Kubernetes-Compute-Resources-Pod-Grafana (8)](https://user-images.githubusercontent.com/56623710/125421209-8a85c3e6-2191-4185-bc2b-35a61f478e64.png)

#### Expected behavior:

no load in operations
no manual flush

#### Steps/Code to reproduce:
1. create collection
2. insert 1,000 entities per request
Memory usage is about 7Gb in 30mins.

#### Environment:
- Milvus version(e.g. v1.1.0 or 8b23a93):  standalone mode
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by del-zhenwu** [comment]
14Gb in 1h

**Comment by xiaofan-luan** [comment]
which node consumes most of the data?

**Comment by del-zhenwu** [comment]
> which node consumes most of the data?

The above result comes from testing with the standalone mode, will try cluster mode during regression testing.
