### ISSUE TITLE
2048 dimension 20000000 items response time is almost 20 seconds

### ISSUE THREAD

**Issue by liunancun** [milvus-io/milvus#6492]
#### Describe the bug:
2048 dimension 20000000 items response time is almost 20 seconds

#### Expected behavior:
Respond as soon as possible

#### Steps/Code to reproduce:
Search operation topk=31

#### Environment:
- Milvus version(e.g. v1.1.0 or 8b23a93): 1.1.1-cpu-d061621-330cc6
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v1.1.0
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz/128G
- GPU: 
- Others: 

#### Configuration file:
default

**Comment by liunancun** [comment]
![image](https://user-images.githubusercontent.com/12378933/125544543-c95228b1-7751-4863-bed7-b25c3969a4d8.png)

**Comment by shengjun1985** [comment]
2048 dimension 20000000 items: 2048 * 4 * 20000000 = 163G.
But your memory is only 128G.
If you accept a reduction in recall, it is recommended to try another index type, such as IVF_SQ8 or IVF_PQ.

**Comment by liunancun** [comment]
Is the memory requirement so high? We are now applying it to the image search, and we have only uploaded 200W pictures. Maybe the entire gallery has about 2000W pictures.

**Comment by shengjun1985** [comment]
2,000,000 items need 16G. Well, it's not a lack of memory.
Could you call get_collection_stats() to check whether all the segments finish indexing?
And what about your query parameters such as `nq`, `nprobe`?

**Comment by liunancun** [comment]
Cache_size is set to 12G, and insert_buffer_size is set to 3G. Does it matter? By default, nprobe is equal to 16.
The default when creating an index before nprobe is 1024, and the default is 16384 when you delete the index and recreate it later.

**Comment by liunancun** [comment]
What index should be used in an application like mine, and how should the parameters be set appropriately?

**Comment by liunancun** [comment]
Image search application, the number of images is greater than 2000W.

**Comment by yhmo** [comment]
2 million 2048 dim vectors, raw data size is 16GB.

The cache_size is to set the capacity of cpu memory to hold data required by search action. Your cache_size=12GB, less than 16GB, milvus will have to swap data between hard disk and cpu memory.

Milvus split vectors data into segments, the index_file_size is to set size of each segment, the default value is 1024MB, that means each segment will be 1024+ MB. During search, milvus load segment one by one into cache, if the cache size can hold all segments, search performance will be best.

Before launch milvus server, make sure the cache size can hold all segment data. Since your 2 millions vectors size is 16GB, the cache_size should be greater than 16GB, you can set 18 or 20GB. You can specify cache_size in the server_config.yaml file:
```
cache:
  cache_size: 18GB
```

There is an online tool to calculate vector data size: https://zilliz.com/sizing-tool

The following script is to insert 200w random vectors and search:
```
import random
import time
import threading
import numpy as np
from milvus import Milvus, IndexType
from milvus.client.types import MetricType

SERVER_ADDR = "127.0.0.1"
SERVER_PORT = '19530'
COLLECTION_NAME = "TEST"
COLLECTION_DIMENSION = 2048
COLLECTION_PARAM = {'collection_name': COLLECTION_NAME,
                    'dimension': COLLECTION_DIMENSION,
                    'index_file_size': 2048,
                    'metric_type':MetricType.L2}
INDEX_TYPE = IndexType.IVF_FLAT
INDEX_PARAM = {'nlist': 2048}
SEARCH_PARAM = {'nprobe': 16}

NQ = 1
TOPK = 32

MILVUS = Milvus(host=SERVER_ADDR, port=SERVER_PORT)

def gen_vec_list(nb, seed=np.random.RandomState(1234)):
    xb = seed.rand(nb, COLLECTION_DIMENSION).astype("float32")
    vec_list = xb.tolist()
    return vec_list

def create_collection(name = COLLECTION_NAME):
    param = COLLECTION_PARAM
    param['collection_name'] = name
    status = MILVUS.create_collection(param)
    print("create", name, status)

def load_collection(name=COLLECTION_NAME):
    MILVUS.load_collection(collection_name=name)
    print("load collection", name)

def flush_collection(name=COLLECTION_NAME):
    MILVUS.flush(collection_name_array=[name])
    status, count = MILVUS.count_entities(collection_name=name)
    print("flush collection, row count:", count)

def drop_collection(name = COLLECTION_NAME):
    status = MILVUS.drop_collection(collection_name=name)
    print("drop", name)

def has_collection(name = COLLECTION_NAME):
    status, has = MILVUS.has_collection(collection_name=name)
    print("has_collection", has)
    return has

def get_collection_stats(name = COLLECTION_NAME):
    status, stat = MILVUS.get_collection_stats(collection_name=name)
    print(stat)

def create_index(name = COLLECTION_NAME):
    time_start = time.time()
    print("begin create index...")
    status = MILVUS.create_index(collection_name=name, index_type=INDEX_TYPE, params=INDEX_PARAM)
    time_end = time.time()
    print("create index finished, time cost:", time_end - time_start, "sec", status)

def insert(name = COLLECTION_NAME):
    batch = 10000
    gen_cost = 0.0
    insert_cost = 0.0
    for i in range(10):
        time_1 = time.time()
        vectors = gen_vec_list(batch, seed=np.random.RandomState(i+13))
        time_2 = time.time()
        status, ids = MILVUS.insert(collection_name=name, records=vectors)
        time_3 = time.time()
        print("insert", i, name, len(ids), status)
        gen_cost = gen_cost + (time_2 - time_1)
        insert_cost = insert_cost + (time_3 - time_2)
    print("generate random vectors cost:", gen_cost, "sec")
    print("insert cost:", insert_cost, "sec")

def search(name = COLLECTION_NAME):
    q_records = [[random.random() for _ in range(COLLECTION_DIMENSION)] for _ in range(NQ)]
    time_start = time.time()
    status, results = MILVUS.search(collection_name=name, query_records=q_records, top_k=TOPK,
                                    params=SEARCH_PARAM)
    print("=========RESULT==========")
    for each_query in results:
        for each_score in each_query:
            print("id =", each_score.id, "distance =", each_score.distance)
    print("=========================")

    time_end = time.time()
    print("search nq:", NQ, "topk:", TOPK)
    print("time cost:", (time_end-time_start)*1000, "ms")


if __name__ == "__main__":
    # create collection
    if not has_collection():
        create_collection()

    # insert vectors and flush into storage
    insert()
    flush_collection()

    # create index for all segments
    create_index()

    # prrint collection status
    get_collection_stats()

    # load data into cache
    load_collection()

    # search
    search()

```

**Comment by yhmo** [comment]
Different index type may require different cache size:
- FLAT is brute-force search, required data size is equal to total raw data size.
- IVF_FLAT is IVF index with raw vectors, required data is also equal to total raw data size.
- IVF_SQ8 is IVF index with compacted vectors, required data is about 25% ~ 30% of raw data size.
- IVF_PQ is IVF index with simplified vectors, required data is about 10% ~ 25% of raw data size.

**Comment by yhmo** [comment]
So, when you import 20 million vectors, the raw data size is 160GB. If your machine's cpu memory is not enough, you can choose IVF_SQ8 or IVF_PQ index.
If you choose IVF_SQ8 index, the required cache size is about 40 ~ 45 GB.

**Comment by liunancun** [comment]
What is the difference between IVF_SQ8 and IVF_PQ? If IVF_PQ is selected, how to fill in the m parameter?

**Comment by yhmo** [comment]
My suggestion for 20 millions 2048 dim vectors:
index_file_size = 2048MB or 4096MB
cache_size = 50GB(IVF_SQ8)
nlist = 2048

For more details, please refer to the performance FAQ: https://milvus.io/docs/v1.1.1/performance_faq.md

**Comment by liunancun** [comment]
Okay thank you!

**Comment by yhmo** [comment]
> What is the difference between IVF_SQ8 and IVF_PQ? If IVF_PQ is selected, how to fill in the m parameter?

IVF_SQ8 lost few precision, its recall rate is closely to IVF_FLAT.
IVF_PQ lost more precision, it is fast, but recall rate is not good.

For more details, please refer: https://milvus.io/cn/docs/v1.1.1/index.md#CPU

**Comment by shengjun1985** [comment]
The issue seems to be solved.
Close.
