### ISSUE TITLE
queryNode.gracefulTime should be exposed to be modifiable

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#6514]
#### Describe the bug:
queryNode.gracefulTime is not modified when modify it to 0 in milvus.yaml

#### Expected behavior:
queryNode.gracefulTime should be exposed to be modifiable

#### Steps/Code to reproduce:
Details are in issue #5858

#### Environment:
- Milvus version(e.g. v1.1.0 or 8b23a93): 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by yanliang567** [comment]
@binbinlv shall we close this issue as #5858 was closed.

**Comment by binbinlv** [comment]
OK, I see the graceful time has been exposed through the milvus doc.

Close it.
