### ISSUE TITLE
[Chaos] Flush requested during chaos hang if datanode deleted

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#6520]
#### Describe the bug:
if datanode deleted after a flush requested and before the flush completed, the  flush hang even after datanode get back to running

#### Steps/Code to reproduce:
1. deploy Milvus 2.0 with cluster mode
2. write a loop to insert data and flush
3. delete datanode 

#### Expected behavior:
The flush request can return timeout, or it can return success after datanode back. But hanging is not acceptable.

4. after datanode back to running, new flush requests can return successfully, but the one requested during the chaos keeps hanging.

#### Environment:
- Milvus version:  master-20210714-f3a5b46
- SDK version: 
pymilvus                           2.0.0rc2.dev14
pymilvus-orm                       2.0.0rc2.dev31

**Comment by ThreadDao** [comment]
Current situation:
1. when dataNode pod is killed, flush request hangs
2. after deleting chaos and restarting the pod, the before flush request is returned, and a new flush request is available.
