### ISSUE TITLE
The search gets stuck after the queryNode pod shrinks

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#6528]
#### Describe the bug:

1. deploy cluster milvus with two queryNode pods
2. create `query_scale_one` collection and insert 5000 entities
3. search  on `query_scale_one` with nq=5, limit=10, {"metric_type": "L2", "params": {"nprobe": 10}}
4. create `query_scale_two` collections and insert 5000 entities
5. search  on `query_scale_two` with nq=5, limit=10, {"metric_type": "L2", "params": {"nprobe": 10}}
6. shrink queryNode pod (queryNode pods from 2 to 1)
7. same search on collection `query_scale_one` and `query_scale_two` 
8. search gets stuck

#### Expected behavior:
search successfully

#### Steps/Code to reproduce:
/milvus/tests20/python_client/scale/test_query_node_scale.py
```
    def test_shrink_query_node(self):
        """
        target: test shrink queryNode from 2 to 1
        method: 1.deploy two queryNode
                2.search two collections in two queryNode
                3.upgrade queryNode from 2 to 1
                4.search second collection
        expected: search result is correct
        """
        # deploy
        release_name = "scale-query"
        env = HelmEnv(release_name=release_name, queryNode=2)
        env.helm_install_cluster_milvus(image_pull_policy=constants.IF_NOT_PRESENT)

        # connect
        connections.add_connection(default={"host": '10.98.0.8', "port": 19530})
        connections.connect(alias='default')

        # collection one
        data = cf.gen_default_list_data(nb)
        c_name = "query_scale_one"
        collection_w = ApiCollectionWrapper()
        collection_w.init_collection(name=c_name, schema=cf.gen_default_collection_schema())
        collection_w.insert(data)
        assert collection_w.num_entities == nb
        collection_w.load()
        res1, _ = collection_w.search(data[-1][:nq], ct.default_float_vec_field_name,
                                      ct.default_search_params, ct.default_limit)
        assert res1[0].ids[0] == data[0][0]

        # collection two
        c_name_2 = "query_scale_two"
        collection_w2 = ApiCollectionWrapper()
        collection_w2.init_collection(name=c_name_2, schema=cf.gen_default_collection_schema())
        collection_w2.insert(data)
        assert collection_w2.num_entities == nb
        collection_w2.load()
        res2, _ = collection_w2.search(data[-1][:nq], ct.default_float_vec_field_name,
                                       ct.default_search_params, ct.default_limit)
        assert res2[0].ids[0] == data[0][0]

        # scale queryNode pod
        pdb.set_trace()
        env.helm_upgrade_cluster_milvus(queryNode=1)

        # search
        res1, _ = collection_w.search(data[-1][:nq], ct.default_float_vec_field_name,
                                      ct.default_search_params, ct.default_limit)
        assert res1[0].ids[0] == data[0][0]
        res2, _ = collection_w2.search(data[-1][:nq], ct.default_float_vec_field_name,
                                       ct.default_search_params, ct.default_limit)
        assert res2[0].ids[0] == data[0][0]

        # env.helm_uninstall_cluster_milvus()
```
server logs:
[proxy.log](https://github.com/milvus-io/milvus/files/6816064/proxy.log)
[queryCoord.log](https://github.com/milvus-io/milvus/files/6816065/queryCoord.log)
[queryNode_x28tf.log](https://github.com/milvus-io/milvus/files/6816068/queryNode_x28tf.log)
[queryNode_x47tf.log](https://github.com/milvus-io/milvus/files/6816069/queryNode_x47tf.log)

#### Environment:
- Milvus version(e.g. v1.1.0 or 8b23a93): 
 5016e50
- SDK version(e.g. pymilvus v2.0.0rc2):
 pymilvus              2.0.0rc3.dev1
 pymilvus-orm          2.0.0rc2.dev32
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by bigsheeper** [comment]
> /assign @bigsheeper could you please take a look on reproducing this issue?

okay

**Comment by yanliang567** [comment]
@bigsheeper any updates?

**Comment by xige-16** [comment]
After querynode 1 crash, the dmChannel (v1, v2)will be reshceduled to other querynode,  the search service will be not avaliable util querycoord load balance successfully.  Druing the loadbalance process, proxy can't get vchannel's (v1, v2) search results, and  the seach get stuck finaly.

**Comment by xige-16** [comment]
when querycoord process the loadbalance task, the proxy could return error immediately.

**Comment by ThreadDao** [comment]
1. Version
```
Version:   f5451d1
Built:     Mon Aug 23 10:01:47 UTC 2021
```
2. Result
After queryNode shrinking, search successfully and get correct results.
