### ISSUE TITLE
Htt

### ISSUE THREAD

**Issue by chole22** [milvus-io/milvus#6571]
#### Environment:
- Milvus version(e.g. v1.1.0 or 8b23a93): 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: 

#### Additional context:

**Comment by chole22** [comment]
-

**Comment by yanliang567** [comment]
@chole22 Could you please give more information about the issue? what is is Htt ? which version of Milvus and pymilvus are you using?
