### ISSUE TITLE
Data race when mq msgstream close

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#6574]
#### Describe the bug:
https://github.com/milvus-io/milvus/pull/6551/checks?check_run_id=3076091397
```
==================
WARNING: DATA RACE
Write at 0x00c0003197f8 by goroutine 40:
  internal/race.Write()
      /usr/local/go/src/internal/race/race.go:41 +0x125
  sync.(*WaitGroup).Wait()
      /usr/local/go/src/sync/waitgroup.go:128 +0x126
  github.com/milvus-io/milvus/internal/msgstream.(*MqTtMsgStream).Close()
      /go/src/github.com/milvus-io/milvus/internal/msgstream/mq_msgstream.go:518 +0xd4
  github.com/milvus-io/milvus/internal/util/flowgraph.(*InputNode).Close()
      /go/src/github.com/milvus-io/milvus/internal/util/flowgraph/input_node.go:32 +0x6d
  github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Close()
      /go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:99 +0x13a
  github.com/milvus-io/milvus/internal/util/flowgraph.(*TimeTickedFlowGraph).Close()
      /go/src/github.com/milvus-io/milvus/internal/util/flowgraph/flow_graph.go:90 +0xf3
  github.com/milvus-io/milvus/internal/datanode.(*dataSyncService).close()
      /go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:86 +0x119
  github.com/milvus-io/milvus/internal/datanode.(*DataNode).ReleaseDataSyncService()
      /go/src/github.com/milvus-io/milvus/internal/datanode/data_node.go:218 +0x54d
  github.com/milvus-io/milvus/internal/datanode.(*DataNode).BackGroundGC()
      /go/src/github.com/milvus-io/milvus/internal/datanode/data_node.go:202 +0x369

Previous read at 0x00c0003197f8 by goroutine 63:
  internal/race.Read()
      /usr/local/go/src/internal/race/race.go:37 +0x206
  sync.(*WaitGroup).Add()
      /usr/local/go/src/sync/waitgroup.go:71 +0x219
  github.com/milvus-io/milvus/internal/msgstream.(*MqTtMsgStream).Start()
      /go/src/github.com/milvus-io/milvus/internal/msgstream/mq_msgstream.go:510 +0x8e
  github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start()
      /go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:54 +0x72b

Goroutine 40 (running) created at:
  github.com/milvus-io/milvus/internal/datanode.TestDataNode.func7()
      /go/src/github.com/milvus-io/milvus/internal/datanode/data_node_test.go:211 +0x110
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1127 +0x202

Goroutine 63 (running) created at:
  github.com/milvus-io/milvus/internal/util/flowgraph.(*TimeTickedFlowGraph).Start()
      /go/src/github.com/milvus-io/milvus/internal/util/flowgraph/flow_graph.go:75 +0x19a
  github.com/milvus-io/milvus/internal/datanode.(*dataSyncService).start()
      /go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:77 +0xd6
==================
```

**Comment by XuanYang-cn** [comment]
#### How to reproduce locally:

Add this test in `internal/msgstream/mq_msgstream_test.go` and run with 

```
go test -run RmqTtMsgStream_Start_Close_Race -race
```
```
func TestStream_RmqTtMsgStream_Start_Close_Race(t *testing.T) {
	factory := ProtoUDFactory{}

	rocksdbName := "/tmp/rocksttmq_start_close"
	etcdKV := initRmq(rocksdbName)
	defer etcdKV.Close()

	consumerChannels := []string{"insert1", "insert2"}
	consumerGroupName := "InsertGroup"
	rmqClient2, _ := mqclient.NewRmqClient(client.ClientOptions{Server: rocksmq.Rmq})
	outputStream, _ := NewMqTtMsgStream(context.Background(), 100, 100, rmqClient2, factory.NewUnmarshalDispatcher())
	outputStream.AsConsumer(consumerChannels, consumerGroupName)
	go outputStream.Start()
	go outputStream.Close()
}

```

**Comment by xige-16** [comment]
msgstream's start function is non-blocked, It's best not to go msgstream.start()

**Comment by xige-16** [comment]
@bigsheeper The startup of a node in flowgraph can be divided into two parts, the first step is to start the msgstream, and then start a go func() to execute. 
```go
func (fg *TimeTickedFlowGraph) Start() {
	wg := sync.WaitGroup{}
	for _, v := range fg.nodeCtx {
		wg.Add(1)
                 v.Start(fg.ctx, &wg)
                 go v.execute()
	}
	wg.Wait()
}
```

**Comment by XuanYang-cn** [comment]
> @bigsheeper The startup of a node in flowgraph can be divided into two parts, the first step is to start the msgstream, and then start a go func() to execute.
> 
> ```go
> func (fg *TimeTickedFlowGraph) Start() {
> 	wg := sync.WaitGroup{}
> 	for _, v := range fg.nodeCtx {
> 		wg.Add(1)
>                  v.Start(fg.ctx, &wg)
>                  go v.execute()
> 	}
> 	wg.Wait()
> }
> ```

But because of the `wg.Wait()`, we'll still have to call `go Start()`. @xige-16

**Comment by bigsheeper** [comment]
> > @bigsheeper The startup of a node in flowgraph can be divided into two parts, the first step is to start the msgstream, and then start a go func() to execute.
> > ```go
> > func (fg *TimeTickedFlowGraph) Start() {
> > 	wg := sync.WaitGroup{}
> > 	for _, v := range fg.nodeCtx {
> > 		wg.Add(1)
> >                  v.Start(fg.ctx, &wg)
> >                  go v.execute()
> > 	}
> > 	wg.Wait()
> > }
> > ```
> 
> But because of the `wg.Wait()`, we'll still have to call `go Start()`. @xige-16

maybe you could use context with deadline in this unittest.

**Comment by XuanYang-cn** [comment]
> > > @bigsheeper The startup of a node in flowgraph can be divided into two parts, the first step is to start the msgstream, and then start a go func() to execute.
> > > ```go
> > > func (fg *TimeTickedFlowGraph) Start() {
> > > 	wg := sync.WaitGroup{}
> > > 	for _, v := range fg.nodeCtx {
> > > 		wg.Add(1)
> > >                  v.Start(fg.ctx, &wg)
> > >                  go v.execute()
> > > 	}
> > > 	wg.Wait()
> > > }
> > > ```
> > 
> > 
> > But because of the `wg.Wait()`, we'll still have to call `go Start()`. @xige-16
> 
> maybe you could use context with deadline in this unittest.

This unittest is just the minimum way to reproduce this bug. The real problem occurs when flowgraph `close()`. because flowgraph `start()` and `close()` are in different goroutines, so if `close()` immediately after `start()` of a flowgraph, this race will be triggered in more probability.

**Comment by XuanYang-cn** [comment]
This unit test is not even in the code.

**Comment by bigsheeper** [comment]
well, i see, i'll fix it immediately

**Comment by XuanYang-cn** [comment]
Using `waitgroup` inside goroutine will trigger a data race, this's the main problem.

Ref: https://github.com/golang/go/issues/23842#issuecomment-365878004

**Comment by bigsheeper** [comment]
> Using `waitgroup` inside goroutine will trigger a data race, this's the main problem.
> 
> Ref: [golang/go#23842 (comment)](https://github.com/golang/go/issues/23842#issuecomment-365878004)

I'm planning to move msgStream's closing to `case ctx.Done` in node's `start`, how do you think
