### ISSUE TITLE
The skip-ci commit missing ci-passed label

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#6583]
#### Describe the bug:
You expected to skip ci and auto-merge but need to add ci-passed label manually every time.

#### Expected behavior:
Detect last commit skip-ci and auto label ci-passed

#### Environment:
- Milvus version(e.g. v1.1.0 or 8b23a93): 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by yanliang567** [comment]
@ThreadDao Could you please specify the PR link here for investigation?
