### ISSUE TITLE
Query with none output_fields should return all fields

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#6593]
#### Describe the bug:
When query with `output_fields=None` all fields should return. The collection has int64, float, float_vector three fields, but only int64 and float two fields are returned.

#### Expected behavior:
return all fields

#### Steps/Code to reproduce:
/milvus/test20/python_client/test_query.py
```
        def test_query_output_field_none(self):
        """
        target: test query with none output field
        method: query with output field=None
        expected: return all fields
        """
        collection_w, vectors = self.init_collection_general(prefix, insert_data=True)[0:2]
        res, _ = collection_w.query(default_term_expr, output_fields=None)
        assert set(res[0].keys()) == set(default_all_fields)
```

#### Environment:
- Milvus version(e.g. v1.1.0 or 8b23a93): 
- a992dcf
- SDK version(e.g. pymilvus v2.0.0rc2):
 pymilvus              2.0.0rc3.dev5
 pymilvus-orm          2.0.0rc3.dev6
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by cydrain** [comment]
current `query` behavior:
|| output |
-----------

**Comment by ThreadDao** [comment]
Got it. I will close this issue.
