### ISSUE TITLE
Refactor snapshot of timestamp statistics in proxy

### ISSUE THREAD

**Issue by DragonDriver** [milvus-io/milvus#6599]
#### What would you like to be added:

I want to refactor snapshot of timestamp statistics in proxy, change the workflow when generating timestmap statistics.

#### Why is this needed:

There is a small bug when scheduler generates the timestamp statistics.

We use below data structures to hold timestap statistics.

```go
type pChanStatistics struct {
	minTs Timestamp
	maxTs Timestamp
}

type pChanStatInfo struct {
	pChanStatistics
	refCnt int
}

type DmTaskQueue struct {
	BaseTaskQueue
	lock sync.Mutex

	statsLock            sync.RWMutex
	pChanStatisticsInfos map[pChan]*pChanStatInfo
}
```

When there are task changes in scheduler, we will update the `pChanStatisticsInfos`. When task enqueues, the related pchan info will be updated, if pchan is not in `pChanStatisticsInfos`, a new kv pair was added into `pChanStatisticsInfos` and the `refCnt` was 1, otherwise we will increase the `refCnt` of `pChanStatInfo` and update related `minTs` and `maxTs`. When task was done or task failed, we will decrease the `refCnt`. However, we made a mistake here, when there are continous dml tasks, the `maxTs` will be updated, the `minTs` can be updated only when the `refCnt` is zero, but tasks are continous, the `refCnt` won't be decreased to zero.

We will use below data structure to hold statistics.

```go
type pChanStatInfo struct {
   maxTs Timestamp
   tsSet map[Timestamp]struct{}
   minTs Timestamp
}
```

When task was done or task failed, remove the ts of task from `tsSet`, if the `minTs` was removed, iterate `tsSet` to get a new `minTs`, if the `tsSet` is empty, there are no tasks with related pchan.

**Comment by czs007** [comment]
LGTM
