### ISSUE TITLE
Unit tests for the Knowhere library are not available

### ISSUE THREAD

**Issue by xiaohu4313888** [milvus-io/milvus#6604]
#### Expected behavior:
I try to make a unit test on knowhere, but it can't work.
Knowhere is too dependent on Milvus's third-party libraries to run and use as a stand-alone library

#### Steps/Code to reproduce:
include_directories(${MILVUS_THIRDPARTY_SRC})
#this line is in /index/knowhere line 50
set(depend_libs
        gtest gmock gtest_main gmock_main
        faiss fiu
        ngt
        index_log
        )
#this  lib is used in /index/unittest/CMakeList.txt

#### Environment:
- Milvus version(e.g. v1.1.0 or 8b23a93): 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by abodyy4272** [comment]
MILVUS_THIRDPARTY_SRC

**Comment by abodyy4272** [comment]
MILVUS_THIRDPARTY_SRC

**Comment by XuanYang-cn** [comment]
@xiaohu4313888 Good catch. Please helping us fixing it.

**Comment by XuanYang-cn** [comment]
I think copy the easylogging++ file into `index/thirdparty` would be nice, what do you think? @xiaohu4313888
