### ISSUE TITLE
Offering a guide to install Milvus 2.0 locally 

### ISSUE THREAD

**Issue by orange-jams** [milvus-io/milvus#6611]
#### Is your feature request related to a problem? Please describe:
For some reasons, we can only install offline software. And when i follow the online documents to deploy distributed milvus 2.0, some problems happened such as can't starting rootcoord.

#### Describe the solution you'd like:
So we hope the community can provide documents about offline Distributed Milvus 2.0 installation。

**Comment by xiaofan-luan** [comment]
> #### Is your feature request related to a problem? Please describe:
> For some reasons, we can only install offline software. And when i follow the online documents to deploy distributed milvus 2.0, some problems happened such as can't starting rootcoord.
> 
> #### Describe the solution you'd like:
> So we hope the community can provide documents about offline Distributed Milvus 2.0 installation。
> 
> #### Describe alternatives you've considered:
> #### Additional context

Hi Orange, as long as you have a docker/k8s environment, we believe is should be working no matter online or offline.
If you give out the error logs that would be helpful to investigate why root coordinator can not be up.

Offline deployment is complicated, do you guys think offer a installation guide is doable? @zwd1208 @jeffoverflow

**Comment by orange-jams** [comment]
> > #### Is your feature request related to a problem? Please describe:
> > For some reasons, we can only install offline software. And when i follow the online documents to deploy distributed milvus 2.0, some problems happened such as can't starting rootcoord.
> > #### Describe the solution you'd like:
> > So we hope the community can provide documents about offline Distributed Milvus 2.0 installation。
> > #### Describe alternatives you've considered:
> > #### Additional context
> 
> Hi Orange, as long as you have a docker/k8s environment, we believe is should be working no matter online or offline.
> If you give out the error logs that would be helpful to investigate why root coordinator can not be up.
> 
> Offline deployment is complicated, do you guys think offer a installation guide is doable? @zwd1208 @jeffoverflow

I have provide the error logs on rootcoord can't start in discussions, here is th link: discussions:#6318

**Comment by jeffoverflow** [comment]
> > > #### Is your feature request related to a problem? Please describe:
> > > For some reasons, we can only install offline software. And when i follow the online documents to deploy distributed milvus 2.0, some problems happened such as can't starting rootcoord.
> > > #### Describe the solution you'd like:
> > > So we hope the community can provide documents about offline Distributed Milvus 2.0 installation。
> > > #### Describe alternatives you've considered:
> > > #### Additional context
> > 
> > 
> > Hi Orange, as long as you have a docker/k8s environment, we believe is should be working no matter online or offline.
> > If you give out the error logs that would be helpful to investigate why root coordinator can not be up.
> > Offline deployment is complicated, do you guys think offer a installation guide is doable? @zwd1208 @jeffoverflow
> 
> I have provide the error logs on rootcoord can't start in discussions, here is th link: discussions:#6318

@orange-jams  You can refer to this document at [How to Save and Load Docker Images to Offline Servers](https://www.percona.com/blog/2017/05/23/how-to-save-and-load-docker-images/)

**Comment by xiaofan-luan** [comment]
> > > #### Is your feature request related to a problem? Please describe:
> > > For some reasons, we can only install offline software. And when i follow the online documents to deploy distributed milvus 2.0, some problems happened such as can't starting rootcoord.
> > > #### Describe the solution you'd like:
> > > So we hope the community can provide documents about offline Distributed Milvus 2.0 installation。
> > > #### Describe alternatives you've considered:
> > > #### Additional context
> > 
> > 
> > Hi Orange, as long as you have a docker/k8s environment, we believe is should be working no matter online or offline.
> > If you give out the error logs that would be helpful to investigate why root coordinator can not be up.
> > Offline deployment is complicated, do you guys think offer a installation guide is doable? @zwd1208 @jeffoverflow
> 
> I have provide the error logs on rootcoord can't start in discussions, here is th link: discussions:#6318

So in your environments you have no internet access? We are thinking of offering a  guide to install Milvus locally so you can run Milvus on a network isolated environment. 

However this might be a very tough one because Milvus has 8 components and 3 dependencies: etcd, pulsar, minio. You have to make sure every thing is working fine in your environment.

**Comment by orange-jams** [comment]
> > > > #### Is your feature request related to a problem? Please describe:
> > > > For some reasons, we can only install offline software. And when i follow the online documents to deploy distributed milvus 2.0, some problems happened such as can't starting rootcoord.
> > > > #### Describe the solution you'd like:
> > > > So we hope the community can provide documents about offline Distributed Milvus 2.0 installation。
> > > > #### Describe alternatives you've considered:
> > > > #### Additional context
> > > 
> > > 
> > > Hi Orange, as long as you have a docker/k8s environment, we believe is should be working no matter online or offline.
> > > If you give out the error logs that would be helpful to investigate why root coordinator can not be up.
> > > Offline deployment is complicated, do you guys think offer a installation guide is doable? @zwd1208 @jeffoverflow
> > 
> > 
> > I have provide the error logs on rootcoord can't start in discussions, here is th link: discussions:#6318
> 
> So in your environments you have no internet access? We are thinking of offering a guide to install Milvus locally so you can run Milvus on a network isolated environment.
> 
> However this might be a very tough one because Milvus has 8 components and 3 dependencies: etcd, pulsar, minio. You have to make sure every thing is working fine in your environment.

Yes,  we don't have no internet access in our environments. Looking forward to your guide！

**Comment by jeffoverflow** [comment]
@orange-jams  See: [Milvus offline installation](https://github.com/milvus-io/milvus/tree/master/deployments/offline)

**Comment by orange-jams** [comment]
> @orange-jams See: [Milvus offline installation](https://github.com/milvus-io/milvus/tree/master/deployments/offline)

Nice! Today I'll try it.
