### ISSUE TITLE
The port restrictions of Pushgateway conflict with our existing monitoring system

### ISSUE THREAD

**Issue by BlueStar111** [milvus-io/milvus#6612]
#### Describe the bug:
When we configured Pushgateway, we found that the official port limit, 1024-65535, but our existing monitoring system, the port is not in this range

![image](https://user-images.githubusercontent.com/47586657/126110009-5f0acff6-914a-4967-ad8d-1cb89b0b9335.png)

#### Environment:
- Milvus version(e.g. v1.1.0 or 8b23a93): v1.1.0
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:

**Comment by fishpenguin** [comment]
We set the port range to (1024, 65535) because that in linux, only root user can access port below 1024.
However you can do a port reflection for your monitoring system

**Comment by yhmo** [comment]
Inactive and close
