### ISSUE TITLE
Milvus is in normal state, but the service is not available

### ISSUE THREAD

**Issue by xTerry** [milvus-io/milvus#6620]
Milvus is in normal state, but the service is not available

No error log and large debug log ,the content is merge logs ，version:v0.10.5

![image](https://user-images.githubusercontent.com/2304854/126139638-61cab587-5744-4562-b767-d43552770e5f.png)
![image](https://user-images.githubusercontent.com/2304854/126139672-71e29ee2-56fc-4c94-a5e9-ba86411730c7.png)
![image](https://user-images.githubusercontent.com/2304854/126139712-d86b250c-33b6-44b1-b0f1-9ba1fa983619.png)
![image](https://user-images.githubusercontent.com/2304854/126139947-d3435cba-c7f1-4946-a3e7-069b759c9836.png)

**Comment by xTerry** [comment]
服务状态正常，但不可用，很奇层，问了群里的专家反馈也是在merge状态下应该是可用的，但结果反之 ，不知道是0.10.5的bug呢还是所有版本都有此类问题

**Comment by JackLCL** [comment]
Do you try to upgrade to the latest version 1.1.1 and see if you still have the problem?
@xTerry

**Comment by xTerry** [comment]
@JackLCL Upgrade to the 1.1.1，It still exists，but running the a day，It‘s recovery.Change to 0.10.5 ,No problem.
Thanks.

**Comment by xTerry** [comment]
@JackLCL Upgrade to the 1.1.1，It still exists，but running the a day，It‘s recovery.Change to 0.10.5 ,No problem.
Thanks.
