### ISSUE TITLE
Failed to insert data into specified partition

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#6640]
#### Steps/Code to reproduce:
1. create a collection
2. create a partition "part_1" in the collection
3. insert some data into the partition
ids = milvus.insert(name, [
            {"name": "A", "type": DataType.FLOAT, "values": aaa[start:end]},
            {"name": "B", "type": DataType.FLOAT, "values": bbb[start:end]},
            {"name": "C", "type": DataType.FLOAT, "values": ccc[start:end]},
        ],"part_1")

The insert() return error:
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=partitionID of partitionName:part_1 can not be find)>

#### Expected result:
It shouldn't return error.

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): v2.0.0-RC2
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.0.0rc2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by DragonDriver** [comment]
i will fix this soon
/assign

**Comment by sanjaygithu** [comment]
Hi @yhmo , Its working fine for my application. may be you can close this Thread.
