### ISSUE TITLE
The pod milvus-datanode failed to restart automatically, status always CrashLoopBackOff

### ISSUE THREAD

**Issue by Bennu-Li** [milvus-io/milvus#6644]
#### Steps/Code to reproduce:
I insert 100,000 pieces of 128-dimensional data in batches, and check the number of vectors in the collection through collection.num_entities after insertion. Repeat this operation, after inserting 600 million pieces of data, the pod milvus-datanode error.

This is the client running log

<img width="1439" alt="截屏2021-07-20 上午11 48 40" src="https://user-images.githubusercontent.com/53458891/126259026-5a003bbc-8b98-4451-a3a8-7d06ef107d15.png">

Below is the status of all pods：
<img width="965" alt="截屏2021-07-20 上午11 51 02" src="https://user-images.githubusercontent.com/53458891/126259207-8381bf8f-5dcf-436f-b5d7-b6f75e9b29c9.png">

And from the log, the datacoord pod also hung up, but it did not restart automatically.

#### Environment:
- Milvus version( v2.0.0-RC2):
- Deployment mode(cluster):
- SDK version(pymilvus v2.0.0rc2):

Attached is the log of the relevant pod:

[datanode.log](https://github.com/milvus-io/milvus/files/6845393/datanode.log)
[etcd.log](https://github.com/milvus-io/milvus/files/6845396/etcd.log)
[datacoord.log.zip](https://github.com/milvus-io/milvus/files/6845407/datacoord.log.zip)
[rootcoord.log.zip](https://github.com/milvus-io/milvus/files/6845409/rootcoord.log.zip)

**Comment by neza2017** [comment]
it seems that `datacoord` disconnect with `etcd`,  log of `datacoord`
```log
[2021/07/19 21:08:28.700 +00:00] [DEBUG] [session_util.go:233] ["session keepalive channel closed"]
```
log of `etcd`
```log
2021-07-19 21:05:23.751549 W | etcdserver: request "header:<ID:8737399705771116514 > put:<key:\"by-dev/meta/datacoord-meta/s/426424370341871617/426424370341871618/426437169470242817\" value_size:499 >" with result "size:6" took too long (354.356736ms) to execute
2021-07-19 21:09:05.408069 W | etcdserver: read-only range request "key:\"by-dev/meta/master-service/collection/426424370341871617\" revision:5892 " with result "error:context canceled" took too long (19.958094364s) to execute
```

**Comment by Bennu-Li** [comment]
Datacord did not restart after hanging up, causing datanode to fail to restart automatically.  so I restarted the datacord manually.
But
 another problem occurred after restarting，the datacoord pod always flush segment.  Below is the log:

<img width="1033" alt="截屏2021-07-20 下午4 29 09" src="https://user-images.githubusercontent.com/53458891/126288251-83b4fc70-77b8-4743-85d4-de0c680acd23.png">

Attached is the log :
[datacoord.log.zip](https://github.com/milvus-io/milvus/files/6846843/datacoord.log.zip)
[datanode.log.zip](https://github.com/milvus-io/milvus/files/6846863/datanode.log.zip)
