### ISSUE TITLE
How to control the permissions

### ISSUE THREAD

**Issue by duanyongyao** [milvus-io/milvus#6647]
### Discussed in https://github.com/milvus-io/milvus/discussions/6646

<div type='discussions-op-text'>

<sup>Originally posted by **duanyongyao** July 20, 2021</sup>
How do I control the permissions, such as access via user name and password, and control read and write permissions

The python SDK documentation provides the following ways to connect to Milvus server,but I think this is very dangerous that anyone who knows the ip and port can have full permissions, Create,Read,Update,Delete.

```python
# Connect to Milvus server
milvus = Milvus(host='localhost', port='19530')
```

Is there any way I can control permissions and ensure data security?</div>

**Comment by xiaofan-luan** [comment]
Milvus does not has access control support yet. 
Based on the roadmap, it will implemented on 2.1, which is around October this year. Contributions on multi tenancy and encryption support is highly welcomed.

**Comment by yhmo** [comment]
@duanyongyao 
Currently milvus doesn't support user/account management, both for v1.x and v2.0. 
You need to build a middle ware to do it. The [Mishards](https://github.com/milvus-io/milvus/tree/1.1/shards) is a good example for such middle ware. 
The basic solution is:
- The middle ware implements same RPC interfaces with Milvus. The Mishards implements all Milvus interfaces in this class: https://github.com/milvus-io/milvus/blob/1.1/shards/mishards/service_handler.py, and inject the class into gRPC as a handler, the inject code is in this file(in the start() method): https://github.com/milvus-io/milvus/blob/1.1/shards/mishards/server.py
- The middle ware persist user/account information into MongoDB or SQLite, manage permissions.
- The middle ware manages a list of Milvus servers, distribute request from different user to different Milvus server.
- The middle ware doesn't take part in computing, it directly return results from Milvus server to user client.

**Comment by yangj2133** [comment]
I strongly support the ability to add permission controls！

**Comment by filip-halt** [comment]
I think we should also look into encrypting the traffic between proxy and client. How much work would go into using SSL with GRPC? Seems like we would need to generate keys for the node on startup and pass them along to grpc.

**Comment by CaptXiong** [comment]
So does Milvu supports the right controls for now?

**Comment by divyajaincs** [comment]
Does milvus supports the permission and controls now with v2.x?

**Comment by CaptXiong** [comment]
> Does milvus supports the permission and controls now with v2.x?

yep!  even support control each index with different rights

**Comment by divyajaincs** [comment]
@CaptXiong any documentation which i can refer for user controls and permissions, right now following this documentation. [i'm](https://milvus.io/docs/rbac.md) 
I'm facing issue while granting the privilege to collection.

![rabc](https://github.com/milvus-io/milvus/assets/25703066/cad8f45d-6f7a-434c-8150-a00cc55434fb)
