### ISSUE TITLE
Memory consumption more than expected

### ISSUE THREAD

**Issue by laol777** [milvus-io/milvus#6675]
I have huge ram memory allocation for [100 M test](https://github.com/milvus-io/bootcamp/blob/master/benchmark_test/lab2_sift1b_100m.md) on Milvus 2.0
after the end of the test, I have 80 GB of memory allocated.

#### Steps/Code to reproduce:

1. **(start standalone milvus)** [installation link](https://milvus.io/docs/install_standalone-docker.md)
``` 
wget https://raw.githubusercontent.com/milvus-io/milvus/master/deployments/docker/standalone/docker-compose.yml -O docker-compose.yml
docker-compose up -d
```
2. **(run test)**
make test by instruction
```
https://github.com/milvus-io/bootcamp/blob/master/benchmark_test/lab2_sift1b_100m.md#2-create-a-table
https://github.com/milvus-io/bootcamp/blob/master/benchmark_test/lab2_sift1b_100m.md#3--import-data-and-build-indexes
```

#### Expected result:
lower memory consumption

#### Actual results:
80 gb ram

#### Environment:
- Milvus version: v2.0.0-RC2
- Deployment mode: - standalone
- SDK version: pymilvus v2.0.0rc2
- Ubuntu:
- CPU/Memory: AMD threadripper 1950x, 96 gb RAM
- GPU: 2x1080 ti
- Others:

**Comment by yhmo** [comment]
Data size of sift1b_100m: 128 * 4 * 100MB = 50GB. 
Need to investigate why it consumed more 30GB.

**Comment by yhmo** [comment]
Link to #7056

**Comment by xiaofan-luan** [comment]
duplicate with #7056
