### ISSUE TITLE
Run rootcoord error

### ISSUE THREAD

**Issue by xuqinkun** [milvus-io/milvus#6685]
I get an error when I run the rootcoord throuth the command:  bin/milvus run rootcoord
The log is as follow:
Welcome to use Milvus!
Version:   v0.10.2-1946-g0aeb61db4-dev
Built:     Wed Jul 21 02:57:33 UTC 2021
GitCommit: 0aeb61db4
GoVersion: go version go1.16.5 linux/amd64

open pid file: /run/milvus/rootcoord.pid
lock pid file: /run/milvus/rootcoord.pid
[2021/07/21 11:03:26.931 +08:00] [DEBUG] [service.go:123] ["grpc init done ..."]
[2021/07/21 11:03:26.934 +08:00] [DEBUG] [service.go:128] ["init params done"]
[2021/07/21 11:03:26.934 +08:00] [DEBUG] [session_util.go:63] ["Session try to connect to etcd"]
[2021/07/21 11:03:26.934 +08:00] [INFO] [logger.go:48] ["parsed scheme: \"endpoint\""]
[2021/07/21 11:03:26.934 +08:00] [INFO] [logger.go:48] ["ccResolverWrapper: sending new addresses to cc: [{etcd:2379  <nil> 0 <nil>}]"]
[2021/07/21 11:03:26.938 +08:00] [DEBUG] [session_util.go:80] ["Sessiont connect to etcd success"]
[2021/07/21 11:03:26.938 +08:00] [DEBUG] [session_util.go:109] ["Session checkIDExist Begin"]
[2021/07/21 11:03:26.940 +08:00] [DEBUG] [session_util.go:116] ["Session checkIDExist End"]
[2021/07/21 11:03:26.940 +08:00] [DEBUG] [session_util.go:121] ["Session try to get serverID"]
[2021/07/21 11:03:26.942 +08:00] [DEBUG] [session_util.go:152] ["Session get serverID success"]
panic: All attempts results:
attempt #1:function CompareAndSwap error for compare is false for key: RootCoord
attempt #2:function CompareAndSwap error for compare is false for key: RootCoord
attempt #3:function CompareAndSwap error for compare is false for key: RootCoord
attempt #4:function CompareAndSwap error for compare is false for key: RootCoord
attempt #5:function CompareAndSwap error for compare is false for key: RootCoord
attempt #6:function CompareAndSwap error for compare is false for key: RootCoord
attempt #7:function CompareAndSwap error for compare is false for key: RootCoord
attempt #8:function CompareAndSwap error for compare is false for key: RootCoord
attempt #9:function CompareAndSwap error for compare is false for key: RootCoord
attempt #10:function CompareAndSwap error for compare is false for key: RootCoord
attempt #11:function CompareAndSwap error for compare is false for key: RootCoord
attempt #12:function CompareAndSwap error for compare is false for key: RootCoord
attempt #13:function CompareAndSwap error for compare is false for key: RootCoord
attempt #14:function CompareAndSwap error for compare is false for key: RootCoord
attempt #15:function CompareAndSwap error for compare is false for key: RootCoord
attempt #16:function CompareAndSwap error for compare is false for key: RootCoord
attempt #17:function CompareAndSwap error for compare is false for key: RootCoord
attempt #18:function CompareAndSwap error for compare is false for key: RootCoord
attempt #19:function CompareAndSwap error for compare is false for key: RootCoord
attempt #20:function CompareAndSwap error for compare is false for key: RootCoord
attempt #21:function CompareAndSwap error for compare is false for key: RootCoord
attempt #22:function CompareAndSwap error for compare is false for key: RootCoord
attempt #23:function CompareAndSwap error for compare is false for key: RootCoord
attempt #24:function CompareAndSwap error for compare is false for key: RootCoord
attempt #25:function CompareAndSwap error for compare is false for key: RootCoord
attempt #26:function CompareAndSwap error for compare is false for key: RootCoord
attempt #27:function CompareAndSwap error for compare is false for key: RootCoord
attempt #28:function CompareAndSwap error for compare is false for key: RootCoord
attempt #29:function CompareAndSwap error for compare is false for key: RootCoord
attempt #30:function CompareAndSwap error for compare is false for key: RootCoord

goroutine 24 [running]:
github.com/milvus-io/milvus/internal/util/sessionutil.(*Session).Init(0xc000410850, 0x226beb6, 0x9, 0xc000584060, 0xf, 0x1, 0x1)
	/code/milvus/internal/util/sessionutil/session_util.go:99 +0x157
github.com/milvus-io/milvus/internal/rootcoord.(*Core).Register(0xc000327a40, 0x10, 0x0)
	/code/milvus/internal/rootcoord/root_coord.go:874 +0xd6
github.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).init(0xc0002174a0, 0x100000000, 0xc0000caa48)
	/code/milvus/internal/distributed/rootcoord/service.go:130 +0x142
github.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).Run(0xc0002174a0, 0xffffffffffffffff, 0x243cc38)
	/code/milvus/internal/distributed/rootcoord/service.go:108 +0x2f
github.com/milvus-io/milvus/cmd/components.(*RootCoord).Run(...)
	/code/milvus/cmd/components/root_coord.go:45
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runRootCoord.func1(0xc000581900, 0x243c3b0, 0xc0000a0a40, 0xc0000112c0, 0xc0000caa40)
	/code/milvus/cmd/roles/roles.go:97 +0xfc
created by github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runRootCoord
	/code/milvus/cmd/roles/roles.go:82 +0xb0

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):2.0
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu (from docker image)
- CPU/Memory: 
- GPU: 
- Others: 

#### Configuration file:
etcd:
  endpoints:
    - localhost:2379
  rootPath: by-dev
  metaSubPath: meta # metaRootPath = rootPath + '/' + metaSubPath
  kvSubPath: kv # kvRootPath = rootPath + '/' + kvSubPath
  segmentBinlogSubPath: datacoord/binlog/segment  # Full Path = rootPath/metaSubPath/segmentBinlogSubPath
  collectionBinlogSubPath: datacoord/binlog/collection # Full Path = rootPath/metaSubPath/collectionBinglogSubPath
  flushStreamPosSubPath: datacoord/flushstream # Full path = rootPath/metaSubPath/flushStreamPosSubPath
  statsStreamPosSubPath: datacoord/statsstream # Full path = rootPath/metaSubPath/statsStreamPosSubPath

minio:
  address: localhost
  port: 9000
  accessKeyID: minioadmin
  secretAccessKey: minioadmin
  useSSL: false
  bucketName: "a-bucket"

pulsar:
  address: localhost
  port: 6651
  maxMessageSize: 5242880 # 5 * 1024 * 1024 Bytes

rocksmq:
  path: /var/lib/milvus/rdb_data

rootCoord:
  address: localhost
  port: 53101

proxy:
  port: 19531

queryCoord:
  address: localhost
  port: 19531

queryNode:
  gracefulTime: 1000 # ms, for search
  port: 21123

indexCoord:
  address: localhost
  port: 31001

indexNode:
  port: 21122

dataCoord:
  address: localhost
  port: 13334

dataNode:
  port: 21125

log:
  level: debug # info, warn, error, panic, fatal
  file:
    rootPath: "" # default to stdout, stderr
    maxSize: 300 # MB
    maxAge: 10 # day
    maxBackups: 20
  format: text # text/json

#### Additional context:
Build from source, I want to run the all components on the Ubuntu which is issued by the docker.

**Comment by cydrain** [comment]
This case can happen when you launched 2 rootcoord.
Please check if this is the case.

**Comment by xuqinkun** [comment]
@cydrain right, but I can't kill the milvus process. After that, the docker container will  be down.

**Comment by cydrain** [comment]
@xuqinkun I cannot get your point.
If you launch Milvus as the document, there should have only 1 rootcoord running in the docker.

**Comment by xuqinkun** [comment]
@cydrain Right, but I want to run the rootcoord on the container for debug. The components are build from source.

**Comment by cydrain** [comment]
@xuqinkun 
This is about how to debug go routine, I'll close this issue.

**Comment by xuqinkun** [comment]
@cydrain All right
