### ISSUE TITLE
Data Persistence Failed

### ISSUE THREAD

**Issue by xinjiguaike** [milvus-io/milvus#6686]
I run milvus by docker-compose(docker-compose.yml as follows, volumes mapping has been bold)：

#### Steps/Code to reproduce:

1. stop milvus
   `docker-compose down`
2. start milvus
   `docker-compose up -d`

#### Expected result:

milvus can be connected normally

#### Actual results:

milvus started, but report **"proxy not healthy"** when connect from milvus insight, and the milvus-standalone container output (it seems the etcd keeps the old queryNode ip; [current milvus-standalone container ip address: 172.31.0.4] ) :

    [2021/07/21 02:51:16.565 +00:00] [DEBUG] [client.go:66] ["QueryNodeClient try connect "] [address=172.30.0.4:21123]
    [2021/07/21 02:51:16.565 +00:00] [INFO] [logger.go:48] ["parsed scheme: \"\""]
    [2021/07/21 02:51:16.565 +00:00] [INFO] [logger.go:48] ["scheme \"\" not registered, fallback to default scheme"]
    [2021/07/21 02:51:16.565 +00:00] [INFO] [logger.go:48] ["ccResolverWrapper: sending update to cc: {[{172.30.0.4:21123  <nil> 0 <nil>}] <nil> <nil>}"]
    [2021/07/21 02:51:16.566 +00:00] [INFO] [logger.go:48] ["ClientConn switching balancer to \"pick_first\""]
    [2021/07/21 02:51:16.566 +00:00] [INFO] [logger.go:48] ["pickfirstBalancer: HandleSubConnStateChange: 0xc001f7b7a0, {CONNECTING <nil>}"]
    [2021/07/21 02:51:18.566 +00:00] [WARN] [logger.go:51] ["grpc: addrConn.createTransport failed to connect to {172.30.0.4:21123  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 172.30.0.4:21123: operation was canceled\". Reconnecting..."]

#### Environment:

-   Milvus version: v2.0.0-rc2-20210712-a8e5fd2
-   Deployment mode: standalone
-   OS: Ubuntu 16.04
-   CPU/Memory: Intel Broadwell x86_64 4c / 32G
-   GPU: None
-   Others:

#### Configuration file(docker-compose.yml):

    version: "3.5"

    services:
        etcd:
            container_name: milvus-etcd
            image: quay.io/coreos/etcd:latest
            command: etcd -listen-peer-urls=http://127.0.0.1:2380 -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 -initial-advertise-peer-urls=http://127.0.0.1:2380 --listen-metrics-urls=http://127.0.0.1:2381 --initial-cluster default=http://127.0.0.1:2380
            volumes:
                - /data/milvus/etcd:/default.etcd
            logging:
                driver: "json-file"
                options:
                    max-size: "300m"
            healthcheck:
                test:
                    [
                        "CMD",
                        "wget",
                        "-q",
                        "--tries=1",
                        "--spider",
                        "http://localhost:2381/health",
                    ]
                interval: 30s
                timeout: 20s
                retries: 3

        minio:
            container_name: milvus-minio
            image: minio/minio:RELEASE.2020-12-03T00-03-10Z
            environment:
                MINIO_ACCESS_KEY: minioadmin
                MINIO_SECRET_KEY: minioadmin
            command: minio server /minio_data
            volumes:
                - /data/milvus/minio:/minio_data
            logging:
                driver: "json-file"
                options:
                    max-size: "300m"
            healthcheck:
                test:
                    ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
                interval: 30s
                timeout: 20s
                retries: 3

        standalone:
            container_name: milvus-standalone
            image: milvusdb/milvus:v2.0.0-rc2-20210712-a8e5fd2
            command: ["milvus", "run", "standalone"]
            volumes:
                - /data/milvus/rocksmq:/var/lib/milvus
            logging:
                driver: "json-file"
                options:
                    max-size: "300m"
            environment:
                ETCD_ENDPOINTS: etcd:2379
                MINIO_ADDRESS: minio:9000
            ports:
                - "19530:19530"
            depends_on:
                - "etcd"
                - "minio"

    networks:
        default:
            name: milvus

**Comment by xiaofan-luan** [comment]
I don't thinks this is persistence issue. Did you check that 172.30.0.4 is stopped? if it is stopped it should be anyway removed from etcd.

**Comment by saltedsword** [comment]
Same issue. I have solved this problem by setting static network for service standalone. But I'm stuck in another problem: The process was blocked when I called collection.load() or collection.num_entities. Somebody help me😭

This is the standalone log:
```bash
milvus-standalone | [2021/07/23 07:00:41.384 +00:00] [DEBUG] [proxy.go:303] ["send timestamp statistics of pchan"] [channels="[]"] [tss="[]"]
milvus-standalone | [2021/07/23 07:00:41.584 +00:00] [DEBUG] [proxy.go:303] ["send timestamp statistics of pchan"] [channels="[]"] [tss="[]"]
milvus-standalone | [2021/07/23 07:00:41.784 +00:00] [DEBUG] [proxy.go:303] ["send timestamp statistics of pchan"] [channels="[]"] [tss="[]"]
milvus-standalone | [2021/07/23 07:00:41.834 +00:00] [DEBUG] [impl.go:1794] [GetQuerySegmentInfo] [role=Proxy-] [db=] [collection=face_collection]
milvus-standalone | [2021/07/23 07:00:41.834 +00:00] [DEBUG] [root_coord.go:1284] [DescribeCollection] [name=face_collection] [msgID=0]
milvus-standalone | [2021/07/23 07:00:41.834 +00:00] [DEBUG] [root_coord.go:1304] ["DescribeCollection Success"] [name=face_collection] [msgID=0]
milvus-standalone | [2021/07/23 07:00:41.834 +00:00] [DEBUG] [root_coord.go:1469] ["ShowPartitionRequest received"] [role=RootCoord] [msgID=0] [collection=face_collection]
milvus-standalone | [2021/07/23 07:00:41.834 +00:00] [DEBUG] [root_coord.go:1506] ["ShowPartitions succeed"] [role=RootCoord] [msgID=0] ["collection name"=face_collection] ["partition names"="[_default,company_1]"] ["partition ids"="[426513119809834306,426513119862063105]"]
milvus-standalone | [2021/07/23 07:00:41.834 +00:00] [DEBUG] [root_coord.go:1696] [ShowSegments] ["collection id"=426513119809834305] ["partition id"=426513119809834306] [msgID=0]
milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [root_coord.go:1719] ["ShowSegments Success"] ["collection id"=426513119809834305] ["partition id"=426513119809834306] ["segments ids"="[]"] [msgID=0]
milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [root_coord.go:1696] [ShowSegments] ["collection id"=426513119809834305] ["partition id"=426513119862063105] [msgID=0]
milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [root_coord.go:1719] ["ShowSegments Success"] ["collection id"=426513119809834305] ["partition id"=426513119862063105] ["segments ids"="[426513119875170305,426513122300002305]"] [msgID=0]
milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [collection_replica.go:107] ["collections in collectionReplica"] [info={}]
milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [collection_replica.go:108] ["partitions in collectionReplica"] [info={}]
milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [collection_replica.go:109] ["segments in collectionReplica"] [info={}]
milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [collection_replica.go:110] ["excludedSegments in collectionReplica"] [info={}]
milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [impl.go:377] ["QueryNode::Impl::GetSegmentInfo for historical"] [SegmentID=426513119875170305]
milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [impl.go:380] ["QueryNode::Impl::GetSegmentInfo, for historical segmentID not exist"] [SegmentID=426513119875170305]
milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [impl.go:377] ["QueryNode::Impl::GetSegmentInfo for historical"] [SegmentID=426513122300002305]
milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [impl.go:380] ["QueryNode::Impl::GetSegmentInfo, for historical segmentID not exist"] [SegmentID=426513122300002305]
milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [collection_replica.go:107] ["collections in collectionReplica"] [info={}]
milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [collection_replica.go:108] ["partitions in collectionReplica"] [info={}]
milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [collection_replica.go:109] ["segments in collectionReplica"] [info={}]
milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [collection_replica.go:110] ["excludedSegments in collectionReplica"] [info={}]
milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [impl.go:391] ["QueryNode::Impl::GetSegmentInfo for streaming"] [SegmentID=426513119875170305]
milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [impl.go:395] ["QueryNode::Impl::GetSegmentInfo, for streaming segmentID not exist"] [SegmentID=426513119875170305]
milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [impl.go:391] ["QueryNode::Impl::GetSegmentInfo for streaming"] [SegmentID=426513122300002305]
milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [impl.go:395] ["QueryNode::Impl::GetSegmentInfo, for streaming segmentID not exist"] [SegmentID=426513122300002305]
milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [impl.go:437] [getSegmentInfo] ["num rows"=0] ["memory size"=0]
milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [impl.go:1828] ["GetQuerySegmentInfo "] [infos=null] [status=]
```

**Comment by xiaofan-luan** [comment]
> Same issue. I have solved this problem by setting static network for service standalone. But I'm stuck in another problem: The process was blocked when I called collection.load() or collection.num_entities. Somebody help me😭
> 
> This is the standalone log:
> 
> ```shell
> milvus-standalone | [2021/07/23 07:00:41.384 +00:00] [DEBUG] [proxy.go:303] ["send timestamp statistics of pchan"] [channels="[]"] [tss="[]"]
> milvus-standalone | [2021/07/23 07:00:41.584 +00:00] [DEBUG] [proxy.go:303] ["send timestamp statistics of pchan"] [channels="[]"] [tss="[]"]
> milvus-standalone | [2021/07/23 07:00:41.784 +00:00] [DEBUG] [proxy.go:303] ["send timestamp statistics of pchan"] [channels="[]"] [tss="[]"]
> milvus-standalone | [2021/07/23 07:00:41.834 +00:00] [DEBUG] [impl.go:1794] [GetQuerySegmentInfo] [role=Proxy-] [db=] [collection=face_collection]
> milvus-standalone | [2021/07/23 07:00:41.834 +00:00] [DEBUG] [root_coord.go:1284] [DescribeCollection] [name=face_collection] [msgID=0]
> milvus-standalone | [2021/07/23 07:00:41.834 +00:00] [DEBUG] [root_coord.go:1304] ["DescribeCollection Success"] [name=face_collection] [msgID=0]
> milvus-standalone | [2021/07/23 07:00:41.834 +00:00] [DEBUG] [root_coord.go:1469] ["ShowPartitionRequest received"] [role=RootCoord] [msgID=0] [collection=face_collection]
> milvus-standalone | [2021/07/23 07:00:41.834 +00:00] [DEBUG] [root_coord.go:1506] ["ShowPartitions succeed"] [role=RootCoord] [msgID=0] ["collection name"=face_collection] ["partition names"="[_default,company_1]"] ["partition ids"="[426513119809834306,426513119862063105]"]
> milvus-standalone | [2021/07/23 07:00:41.834 +00:00] [DEBUG] [root_coord.go:1696] [ShowSegments] ["collection id"=426513119809834305] ["partition id"=426513119809834306] [msgID=0]
> milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [root_coord.go:1719] ["ShowSegments Success"] ["collection id"=426513119809834305] ["partition id"=426513119809834306] ["segments ids"="[]"] [msgID=0]
> milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [root_coord.go:1696] [ShowSegments] ["collection id"=426513119809834305] ["partition id"=426513119862063105] [msgID=0]
> milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [root_coord.go:1719] ["ShowSegments Success"] ["collection id"=426513119809834305] ["partition id"=426513119862063105] ["segments ids"="[426513119875170305,426513122300002305]"] [msgID=0]
> milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [collection_replica.go:107] ["collections in collectionReplica"] [info={}]
> milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [collection_replica.go:108] ["partitions in collectionReplica"] [info={}]
> milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [collection_replica.go:109] ["segments in collectionReplica"] [info={}]
> milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [collection_replica.go:110] ["excludedSegments in collectionReplica"] [info={}]
> milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [impl.go:377] ["QueryNode::Impl::GetSegmentInfo for historical"] [SegmentID=426513119875170305]
> milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [impl.go:380] ["QueryNode::Impl::GetSegmentInfo, for historical segmentID not exist"] [SegmentID=426513119875170305]
> milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [impl.go:377] ["QueryNode::Impl::GetSegmentInfo for historical"] [SegmentID=426513122300002305]
> milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [impl.go:380] ["QueryNode::Impl::GetSegmentInfo, for historical segmentID not exist"] [SegmentID=426513122300002305]
> milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [collection_replica.go:107] ["collections in collectionReplica"] [info={}]
> milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [collection_replica.go:108] ["partitions in collectionReplica"] [info={}]
> milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [collection_replica.go:109] ["segments in collectionReplica"] [info={}]
> milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [collection_replica.go:110] ["excludedSegments in collectionReplica"] [info={}]
> milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [impl.go:391] ["QueryNode::Impl::GetSegmentInfo for streaming"] [SegmentID=426513119875170305]
> milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [impl.go:395] ["QueryNode::Impl::GetSegmentInfo, for streaming segmentID not exist"] [SegmentID=426513119875170305]
> milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [impl.go:391] ["QueryNode::Impl::GetSegmentInfo for streaming"] [SegmentID=426513122300002305]
> milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [impl.go:395] ["QueryNode::Impl::GetSegmentInfo, for streaming segmentID not exist"] [SegmentID=426513122300002305]
> milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [impl.go:437] [getSegmentInfo] ["num rows"=0] ["memory size"=0]
> milvus-standalone | [2021/07/23 07:00:41.835 +00:00] [DEBUG] [impl.go:1828] ["GetQuerySegmentInfo "] [infos=null] [status=]
> ```

I hit the same issue, let us investigate on this

**Comment by xiaofan-luan** [comment]
We  will fix this  issue at RC3

**Comment by saltedsword** [comment]
> We will fix this issue at RC3

That would be great! Appreciate it!😄

**Comment by yhmo** [comment]
The RC4 has been released on Aug 13, please try the new version. (RC3 is skipped)

**Comment by xinjiguaike** [comment]
bravo!

**Comment by xinjiguaike** [comment]
> The RC4 has been released on Aug 13, please try the new version. (RC3 is skipped)

It seems the issue @saltedsword mentioned was not fixed in the RC4 release; after the milvus restarted, the search process was hang up (hang on the grpc connection); by debugging, it shows the codes hold on follows(timeout == None):

```
    if timeout is None:
        while not wait_complete_fn():
            _wait_once(wait_fn, MAXIMUM_WAIT_TIMEOUT, spin_cb)
    else:
        end = time.time() + timeout
        while not wait_complete_fn():
            remaining = min(end - time.time(), MAXIMUM_WAIT_TIMEOUT)
            if remaining < 0:
                return True
            _wait_once(wait_fn, remaining, spin_cb)
    return False
```  

the call stack as follows:
> wait, _common.py:140
result, _channel.py:711
_execute_search_requests, grpc_handler.py:579
handler, grpc_handler.py:55
search_with_expression, grpc_handler.py:622
handler, grpc_handler.py:92
handler, grpc_handler.py:55
search_with_expression, stub.py:1042
inner, stub.py:40
handler, stub.py:51
search, collection.py:626
search_vectors, milvus_helpers.py:121
do_search_materials, search.py:30
search_materials, main.py:101
run_endpoint_function, routing.py:149
app, routing.py:214
app, routing.py:52
handle, routing.py:241
__call__, routing.py:580
__call__, exceptions.py:71
__call__, errors.py:159
__call__, applications.py:112
__call__, applications.py:199
handle, routing.py:390
__call__, routing.py:580
__call__, exceptions.py:71
__call__, cors.py:78
__call__, errors.py:159
__call__, applications.py:112
__call__, applications.py:199
__call__, proxy_headers.py:45
run_asgi, h11_impl.py:396
_run, events.py:81
_run_once, base_events.py:1859
run_forever, base_events.py:570
run_until_complete, base_events.py:603
run, server.py:49
run, main.py:386
<module>, main.py:137

**Comment by AlviseSembenico** [comment]
/reopen 
I am experiencing the same issue after restart of kubernetes. Version 2.0.1
