### ISSUE TITLE
Support specified shard number when create collection.

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#6690]
#### Is your feature request related to a problem? Please describe:
currently Milvus didn't support user specified shard nums, which brings a  lot of confusing on why the cluster is not balanced.

#### Describe the solution you'd like:
User should be able to specify a shard number when create collection. Valid shard number should be a number between 1-4096, thus milvus can be balanced under 1000 nodes cluster.

#### Additional context:
Partition * Shard would be a very big number, thus growing segment could be a fairly large number. 
If a user has 64 shard with 1024 partitions, growing segment numbers should be 65536 and this consumes huge memories in both datanode and querynode, any suggestions on this?

**Comment by xiaofan-luan** [comment]
@sunby @czs007 any suggestions how we solve the issues of too many growing segments?

**Comment by xiaofan-luan** [comment]
We decide to restrict shard * partition to be less than 16384 for now. this may causing flush small segments frequently, hopefully compaction should help .

**Comment by czs007** [comment]
The number of Partitions and the number of Shards should not exceed 4096.

The increase in QueryNode memory consumption has nothing to do with the number of segments, but with the amount of data to be loaded.

The increase in DataNode memory consumption is indeed related to the number of segments. The reason is that we set the number of growing segment rows to be greater than 32,000 rows before being written to storage. When a large number of segments do not meet this requirement, the memory of the DataNode will be consumed drastically.


Is it possible to change the strategy of persisting segments in the DataNode? For example, we can check the overall memory level to automatically persist segments, regardless of how many rows there are currently in the segment.

The consequence is that there are many fragmented files inside the segment, and we can add an additional routine to merge these fragmented files. This is the compaction within the semgent, which is different from the compaction between segments.

@xiaofan-luan @sunby @XuanYang-cn

**Comment by XuanYang-cn** [comment]
> The increase in DataNode memory consumption is indeed related to the number of segments. The reason is that we set the number of growing segment rows to be greater than 32,000 rows before being written to storage. When a large number of segments do not meet this requirement, the memory of the DataNode will be consumed drastically.


I don't see this as a problem, users are the one who's pretty sure about how many number-of-row vectors they have. And it's easy to estimate how many segments and how large the segment will be with fixed shards numbers. They can change the `32000` config accordingly.

**Comment by czs007** [comment]
> > The increase in DataNode memory consumption is indeed related to the number of segments. The reason is that we set the number of growing segment rows to be greater than 32,000 rows before being written to storage. When a large number of segments do not meet this requirement, the memory of the DataNode will be consumed drastically.
> 
> I don't see this as a problem, users are the one who's pretty sure about how many number-of-row vectors they have. And it's easy to estimate how many segments and how large the segment will be with fixed shards numbers. They can change the `32000` config accordingly.

But the number of Partitions is gradually increasing. Do I have to calculate whether my configuration needs to be updated every time I add a new partition?

**Comment by xiaofan-luan** [comment]
> The number of Partitions and the number of Shards should not exceed 4096.
> 
> The increase in QueryNode memory consumption has nothing to do with the number of segments, but with the amount of data to be loaded.
> 
> The increase in DataNode memory consumption is indeed related to the number of segments. The reason is that we set the number of growing segment rows to be greater than 32,000 rows before being written to storage. When a large number of segments do not meet this requirement, the memory of the DataNode will be consumed drastically.
> 
> Is it possible to change the strategy of persisting segments in the DataNode? For example, we can check the overall memory level to automatically persist segments, regardless of how many rows there are currently in the segment.
> 
> The consequence is that there are many fragmented files inside the segment, and we can add an additional routine to merge these fragmented files. This is the compaction within the semgent, which is different from the compaction between segments.
> 
> @xiaofan-luan @sunby @XuanYang-cn
If we have too many growing segments, for example 1024 * 1024, even if each segment only consumes 32000 datas, the entire memory consumption is TB level, that is probably too much. If you flush each segment in a few thousand rows, vector index is not efficient.

Also too many segments may cause failure recovery and load balance slow, my suggestion is partition and shard should restricted in a certain value

**Comment by czs007** [comment]
> > The number of Partitions and the number of Shards should not exceed 4096.
> > The increase in QueryNode memory consumption has nothing to do with the number of segments, but with the amount of data to be loaded.
> > The increase in DataNode memory consumption is indeed related to the number of segments. The reason is that we set the number of growing segment rows to be greater than 32,000 rows before being written to storage. When a large number of segments do not meet this requirement, the memory of the DataNode will be consumed drastically.
> > Is it possible to change the strategy of persisting segments in the DataNode? For example, we can check the overall memory level to automatically persist segments, regardless of how many rows there are currently in the segment.
> > The consequence is that there are many fragmented files inside the segment, and we can add an additional routine to merge these fragmented files. This is the compaction within the semgent, which is different from the compaction between segments.
> > @xiaofan-luan @sunby @XuanYang-cn
> > If we have too many growing segments, for example 1024 * 1024, even if each segment only consumes 32000 datas, the entire memory consumption is TB level, that is probably too much. If you flush each segment in a few thousand rows, vector index is not efficient.
> 
> Also too many segments may cause failure recovery and load balance slow, my suggestion is partition and shard should restricted in a certain value

The segment persistence I mentioned here does not refer to seal/flush the segment but just writes the data in the buffer to a file to reduce the memory consumption. These many small files form the whole segment.

**Comment by xiaofan-luan** [comment]
> > > The number of Partitions and the number of Shards should not exceed 4096.
> > > The increase in QueryNode memory consumption has nothing to do with the number of segments, but with the amount of data to be loaded.
> > > The increase in DataNode memory consumption is indeed related to the number of segments. The reason is that we set the number of growing segment rows to be greater than 32,000 rows before being written to storage. When a large number of segments do not meet this requirement, the memory of the DataNode will be consumed drastically.
> > > Is it possible to change the strategy of persisting segments in the DataNode? For example, we can check the overall memory level to automatically persist segments, regardless of how many rows there are currently in the segment.
> > > The consequence is that there are many fragmented files inside the segment, and we can add an additional routine to merge these fragmented files. This is the compaction within the semgent, which is different from the compaction between segments.
> > > @xiaofan-luan @sunby @XuanYang-cn
> > > If we have too many growing segments, for example 1024 * 1024, even if each segment only consumes 32000 datas, the entire memory consumption is TB level, that is probably too much. If you flush each segment in a few thousand rows, vector index is not efficient.
> > 
> > 
> > Also too many segments may cause failure recovery and load balance slow, my suggestion is partition and shard should restricted in a certain value
> 
> The segment persistence I mentioned here does not refer to seal/flush the segment but just writes the data in the buffer to a file to reduce the memory consumption. These many small files form the whole segment.

Yeah i know, even for 32000 entity it takes around 32M memory for dim 128 vectors. we can. we can not afford more than 10000 growing segments

**Comment by yanliang567** [comment]
get off from rc3 for enhancement

**Comment by fhaltmayer** [comment]
> get off from rc3 for enhancement

Can I ask why we are deprioritizing this? It seems like a big issue that a lot of people were having with 1.0.0 was being limited to only one write node when dealing with their large dataset, and with 2.0.0 we've only increased it to two..

**Comment by yanliang567** [comment]
rc3 is going to release in a few days, and we are not ready for this enhancement yet. @fhaltmayer 
@xiaofan-luan any more comments?

**Comment by xiaofan-luan** [comment]
@czs007  are we still actively working on this?
