### ISSUE TITLE
Milvus 2.0 insert error

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#6697]
I followed the official website to install milvus 2.0 in two ways:
1.minikube install Milvus 2.0
2.docker compose install Milvus 2.0
Only the following error is reported when inserting data, which occurs very frequently
![微信图片_20210721140750](https://user-images.githubusercontent.com/34296482/126439587-5cccf78b-59dc-4e86-86ac-68dac449a8af.png)

**Comment by ss892714028** [comment]
I have encountered this as well with Minikube Milvus 2.0 rc2
![image](https://user-images.githubusercontent.com/34635663/126603246-5776f656-53d9-42e8-88c3-17504ec3d926.png)
This error occured after inserting 100k at a time, total of 60 million vectors into Milvus collection.
After the error, kubectl get pods looks normal
![image](https://user-images.githubusercontent.com/34635663/126603848-0ff4dedb-05c0-4ccd-ba36-7eb7cae8980d.png)
port forward prints error message
![image](https://user-images.githubusercontent.com/34635663/126603949-34fa1e91-6fbd-4127-b07a-94c853ce6eeb.png)
After a while, port forward becomes normal
![image](https://user-images.githubusercontent.com/34635663/126603997-0024535a-34d5-4acd-a981-f3617dc99218.png)
However, after the first error message, Milvus cannot be connected the whole duration.
![image](https://user-images.githubusercontent.com/34635663/126604075-d4e4e204-0b99-46cc-b268-e487d78f12bd.png)

**Comment by zwd1208** [comment]
maybe the process crashed，you can watch milvus log by run `kubectl logs <pod_name> -n <namespaces>`
