### ISSUE TITLE
etcd crashed when running test case for several times

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#6699]
#### Steps/Code to reproduce:
Running the following case for several times 
/milvus/tests20/python_client/testcases/test_search.py::TestCollectionSearch::test_search_max_dim

#### Expected result:
ectd will not crash

#### Actual results:
NAME                                        READY   STATUS             RESTARTS   AGE
milvus-testing-etcd-0                       0/1     CrashLoopBackOff   5          67m
milvus-testing-minio-7cfb4db88-gnxvx        1/1     Running            0          67m
milvus-testing-standalone-5c76d794f-6mwxt   1/1     Running            1          67m

#### Environment:
- Milvus version(): cbb4052
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
Name: pymilvus
Version: 2.0.0rc3.dev6
Name: pymilvus-orm
Version: 2.0.0rc3.dev6

- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by binbinlv** [comment]
Logs could not be uploaded for the big size, could you please ping me to get logs, thanks.

**Comment by neza2017** [comment]
no space left for etcd
```log
2021-07-21T07:49:51.3579468Z stderr F 2021-07-21 07:49:51.355644 C | mvcc/backend: cannot commit tx (write /bitnami/etcd/data/member/snap/db: no space left on device)
```
@binbin12580

**Comment by binbinlv** [comment]
OK, Thanks. 
@neza2017
