### ISSUE TITLE
debian make all fail

### ISSUE THREAD

**Issue by xiyichan** [milvus-io/milvus#6711]
#### Actual results:
![image](https://user-images.githubusercontent.com/34647972/126473426-532626c4-cf41-43aa-b8b4-d871e7f154ef.png)

```shell
make[3]: Leaving directory '/root/go/src/milvus/cmake_build'
[ 38%] Built target yaml-cpp
make[2]: Leaving directory '/root/go/src/milvus/cmake_build'
Makefile:155: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/go/src/milvus/cmake_build'
Makefile:100: recipe for target 'build-cpp' failed
make: *** [build-cpp] Error 1
```

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): master
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): debian
- CPU/Memory: 2c4g
- GPU: null
- Others:

**Comment by scsven** [comment]
@xiyichan Please provide the full compilation log. The reason for the error cannot be seen according to the screenshot. 

/assign @xiyichan

**Comment by xiyichan** [comment]
> @xiyichan Please provide the full compilation log. The reason for the error cannot be seen according to the screenshot.
> 
> /assign @xiyichan

抱歉了，我现在把这个issue关掉，我换了个ubuntu系统已经可以编成功了，日志无法找回来。
