### ISSUE TITLE
Memory of querynode increases 100%+ without query requests

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#6712]
#### Steps/Code to reproduce:
1. deploy Milvus 2.0 with cluster mode
2. keep inserting data(with nb =1000) into collectionA and flush  for 100 times

#### Expected result:
memory of querynode should not increase

#### Actual results:
memory of querynode increases from 90M to 230M during inserting, and lasts around 220M 

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):master-20210721-cbb4052
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-orm         2.0.0rc3.dev5
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by xiaofan-luan** [comment]
> #### Steps/Code to reproduce:
> 1. deploy Milvus 2.0 with cluster mode
> 2. keep inserting data(with nb =1000) into collectionA and flush  for 100 times
> 
> #### Expected result:
> memory of querynode should not increase
> 
> #### Actual results:
> memory of querynode increases from 90M to 230M during inserting, and lasts around 220M
> 
> #### Environment:
> * Milvus version(e.g. v2.0.0-RC2 or [8b23a93](https://github.com/milvus-io/milvus/commit/8b23a9338db0c30a617b77be50c8a49753c620e8)):master-20210721-cbb4052
> * Deployment mode(standalone or cluster):cluster
> * SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-orm         2.0.0rc3.dev5
> * OS(Ubuntu or CentOS):
> * CPU/Memory:
> * GPU:
> * Others:
> 
> #### Configuration file:
> #### Additional context:

I thought that might be related to go garbage collection rather than a leak. Did we every try to increase run time and see if memory keep increasing?

**Comment by xige-16** [comment]
If the collection is not loaded, querynode's memory should not grow at all.

**Comment by yanliang567** [comment]
Not reproduced again. close for now.
