### ISSUE TITLE
Milvus to run on Mac with Apple M1 chipset

### ISSUE THREAD

**Issue by RyanWei** [milvus-io/milvus#6722]
#### Is your feature request related to a problem? Please describe:
When trying to run Milvus 2.0 on Mac with M1 chipset, I've encountered following error:

ryan@Ryans-MacBook-Air ~ % docker ps -a
CONTAINER ID   IMAGE                                         COMMAND                  CREATED        STATUS                      PORTS           NAMES
1af450a19e66   milvusdb/milvus:v2.0.0-rc2-20210712-a8e5fd2   "/tini -- milvus run…"   17 hours ago   Exited (132) 17 hours ago                   milvus-standalone
b15cd36af0cf   quay.io/coreos/etcd:latest                    "etcd -listen-peer-u…"   17 hours ago   Up 17 hours (healthy)       2379-2380/tcp   milvus-etcd
7b4157065d87   minio/minio:RELEASE.2020-12-03T00-03-10Z      "/usr/bin/docker-ent…"   17 hours ago   Up 17 hours (healthy)       9000/tcp        milvus-minio
ryan@Ryans-MacBook-Air ~ % docker logs 1af450a19e66
qemu: uncaught target signal 4 (Illegal instruction) - core dumped
ryan@Ryans-MacBook-Air ~ %

#### Describe the solution you'd like:
I think Milvus currently only support CPUs with AVX,SSE instructions.
Could you please allow Milvus to run on CPUs without these instructions?

#### Describe alternatives you've considered:
Support Neon for ARM or not using SIMD instruction.

**Comment by shengjun1985** [comment]
https://zhuanlan.zhihu.com/p/342965457

**Comment by mkurovski** [comment]
/reopen

Still not working on M1 which is important to support due to more widespread adoption.

**Comment by lowtalker** [comment]
/reopen

adding a request for m1 support

**Comment by miguelsmuller** [comment]
following this thread

**Comment by contentfree** [comment]
This is still an issue in 2.2.9. Any chance of getting an aarch64 / arm64 image built with a working qemu?

**Comment by xiaofan-luan** [comment]
> This is still an issue in 2.2.9. Any chance of getting an aarch64 / arm64 image built with a working qemu?

I know many person has already compiled and runned succesfully on Mac m1.
How did you compile?

**Comment by xiaofan-luan** [comment]
But we don't have plan to support neon for ARM Cpus right now. Arm support already done
