### ISSUE TITLE
Exception occurs when search after index (HNSW)

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#6731]
#### Steps/Code to reproduce:
Run test case:
/milvus/tests20/python_client/testcases/test_search.py::TestCollectionSearch::test_search_after_different_index

Logs:
[log.tar.zip](https://github.com/milvus-io/milvus/files/6860670/log.tar.zip)

#### Expected result:
No exceptions

#### Actual results:
FAILED test_search.py::TestCollectionSearch::test_search_after_different_index[2-8-False-False-HNSW-params4]

(api_response) : <BaseException: (code=1, message=Search failed, C runtime error detected, error code = 1, error msg = [json.exception.type_error.302] type must be number, but is null

#### Environment:
- Milvus version(): 9aa56cd
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
Name: pymilvus
Version: 2.0.0rc3.dev6
Name: pymilvus-orm
Version: 2.0.0rc3.dev6

- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by DragonDriver** [comment]
i am working on this.
/assign

**Comment by DragonDriver** [comment]
For `HNSW`, parameter `ef` is required when searching. See [HNSW in milvus](https://milvus.io/docs/index.md#HNSW).
/assign @binbinlv

**Comment by DragonDriver** [comment]
> For `HNSW`, parameter `ef` is required when searching.
> For `ANNOY`, `search_k` is required.
> And same as other index type.
> See detail in [vector index of milvus](https://milvus.io/docs/v2.0.0/index.md#CPU).
> 
> but it seems that there is a small bug in `RHNSW_PQ`, i will fix this soon.
> 
> /assign @binbinlv

For `RHNSW_PQ`, `dim` here is too low.

I made a test that changes the search params to below:

```python
{
    "metric_type": "L2",
    "params": {
        "nprobe": 10,   # ivf
        "ef": 1,        # hnsw
        "search_k": 1,  # annoy
    }
}
```

and then everything is ok.

**Comment by DragonDriver** [comment]
Index paramters check of RHNSWPQ will be fixed by #6950

**Comment by binbinlv** [comment]
@DragonDriver 
OK, actually this case "test_search_after_different_index_with_params", I specified the search parameters for each index.

And this case without specifying parameters, I think the error message is not user friendly.

(api_response) : <BaseException: (code=1, message=Search failed, C runtime error detected, error code = 1, error msg = [json.exception.type_error.302] type must be number, but is null

Could you improve it? Thanks.

**Comment by DragonDriver** [comment]
> @DragonDriver
> OK, actually this case "test_search_after_different_index_with_params", I specified the search parameters for each index.
> 
> And this case "test_search_after_different_index" without specifying parameters, I think the error message is not user friendly.
> 
> (api_response) : <BaseException: (code=1, message=Search failed, C runtime error detected, error code = 1, error msg = [json.exception.type_error.302] type must be number, but is null
> 
> Could you improve it? Thanks.

I don't know much detail of `segcore` part, especially `search` workflow of `segcore` part. I can let the exception in this case to be more clear but i don't know if there are any other problems. So maybe it's better to let @fishpenguin to fix this?

How do you think about this?
/assign @fishpenguin
