### ISSUE TITLE
create IVF-PQ index failed

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#6732]
#### Steps/Code to reproduce:
Run test case:
/milvus/tests20/python_client/testcases/test_search.py::TestCollectionSearch::test_search_after_different_index

index params:
[Collection.create_index] args: ['float_vector', {'index_type': 'IVF_PQ', 'params': {'nlist': 128, 'm': 16, 'nbits': 8}, 'metric_type': 'L2'}]

Logs:
[log.tar.zip](https://github.com/milvus-io/milvus/files/6860664/log.tar.zip)

#### Expected result:
Create index successfully

#### Actual results:

FAILED test_search.py::TestCollectionSearch::test_search_after_different_index[2-8-False-False-IVF_PQ-params3] - AssertionError

[2021-07-22 07:14:21 - ERROR - ci_test]: (api_response) : <BaseException: (code=1, message=create index failed)> (api_request.py:25)

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): 9aa56cd
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
Name: pymilvus
Version: 2.0.0rc3.dev6
Name: pymilvus-orm
Version: 2.0.0rc3.dev6

- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by xiaocai2333** [comment]
In this case, 'dim' = 8, 'm' = 16. The param 'm' means compress the vector into 'm' parts. So 'm' must be a divisor of 'dim', and 'm' preferably a quarter of 'dim'. @binbinlv

**Comment by binbinlv** [comment]
@xiaocai2333  OK, thanks for clarify, will retest it.

**Comment by binbinlv** [comment]
Verified, and change the m =2 when dim = 8, work as design here.

But may we report the error message more specific? Just like add why the index is created fail?

@xiaocai2333

**Comment by xiaocai2333** [comment]
OK， I will fix it.

**Comment by xiaocai2333** [comment]
Working on it.

**Comment by yanliang567** [comment]
let me know if you cannot catch the train rc3 @xiaocai2333

**Comment by xiaocai2333** [comment]
I have fixed it, but the CI is too difficult to pass 😂.

**Comment by binbinlv** [comment]
The error message has been added, but new assert occurs. So close this issue, open another issue for this new assert: #6921
