### ISSUE TITLE
Minukube Milvus 2.0 standalone, pods appear to be running after error but cannot connect with sdk

### ISSUE THREAD

**Issue by ss892714028** [milvus-io/milvus#6735]
#### Steps/Code to reproduce:
after the error described in issue #6697 occors, milvus pod repeatly restarts and crashes. Although kubectl get pods shows the pods are running, 
![image](https://user-images.githubusercontent.com/34635663/126611488-91a09b2d-3f92-4bcd-ae62-6f23e57b7a90.png)

Milvus service cannot be connected
![image](https://user-images.githubusercontent.com/34635663/126611844-9142d464-11d4-4373-847b-525dd5115aa2.png)

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): v2.0.0-RC2
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): v2.0.0rc2
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 6 cores/64gb
- GPU: 
- Others:

**Comment by ss892714028** [comment]
I restarted the Milvus pod using 
[milvus.log](https://github.com/milvus-io/milvus/files/6861304/milvus.log)

```bash
kubectl get pod my-release-milvus-standalone-69947cdbcf-4qn96 -o yaml | kubectl replace --force -f -
```

Still cannot connect to Milvus server, I have shared the log file with this message

**Comment by MayetG** [comment]
I have the same issue for cluster Milvus

**Comment by zwd1208** [comment]
It seems network problem，can you check your cluster component such as kube-proxy/flannel is running?

**Comment by MayetG** [comment]
its no longer a problem with the newer helm releases - thank you!
