### ISSUE TITLE
collection.num_entities failed

### ISSUE THREAD

**Issue by Bennu-Li** [milvus-io/milvus#6737]
#### Steps/Code to reproduce:
iteratively calls collection.num_entities and collection.insert(), 100k 128 dim vectors at a time, after 900 million data inserted, Pymilvus throws the following error:
![image](https://user-images.githubusercontent.com/53458891/126609037-4165f7da-72a9-4c19-ac13-10a345cc689d.png)

After the error, 
1. Milvus server can still be connected Calling collection.
2. Collection can still be created, all of the operations on the newly created collection appears to be normal.
3. Calling num_entities on the original collection (the one that triggers the insert error) throws error; however, there is a chance that cllection.num_entities also returns the number of vectors.
![image](https://user-images.githubusercontent.com/53458891/126608949-66c01fc9-36a2-4f9b-b3fc-9cb1cf736600.png)

Pods appear to be abnormal:
![image](https://user-images.githubusercontent.com/53458891/126609441-e2231f60-5db0-4ce7-90a9-cfd2c3457f75.png)

The script i used: https://github.com/milvus-io/bootcamp/tree/master/benchmark_test/scripts

[proxy.log](https://github.com/milvus-io/milvus/files/6860870/proxy.log)

#### Environment:
- Milvus version(v2.0.0-RC2)
- Deployment mode(cluster):
- SDK version(pymilvus v2.0.0rc2):

**Comment by yanliang567** [comment]
@Bennu-Li how many proxy node did you configure? how much memory did you configure for each proxy node? It could be proxynode or datanode OOM issue.

**Comment by Bennu-Li** [comment]
> @Bennu-Li how many proxy node did you configure? how much memory did you configure for each proxy node? It could be proxynode or datanode OOM issue.

one proxynode. I didn't limit the memory for proxynode
