### ISSUE TITLE
[Load] Load 50M data, while querynode cosumes 145M memory

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#6745]
#### Steps/Code to reproduce:
1. deploy Milvus 2.0 with cluster mode
2. insert 100,000 entities (about 50MB) into a collection
3. collection.load()

#### Expected result:
querynode consumes 50M memory

#### Actual results:
querynode consumes 145M memory, about 3 times as the data size

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): master-20210721-cbb4052
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: 

#### Additional context:
memory increases from 40MB to 185MB
![Screen Shot 2021-07-22 at 5 49 32 PM](https://user-images.githubusercontent.com/82361606/126620936-a714ecfd-4ef5-4b30-8a16-91a791bdaac6.png)

**Comment by yanliang567** [comment]
after collection.release(), the querynode memory releases 25MB in a short time, and keeps at 155MB.
![Screen Shot 2021-07-22 at 7 15 37 PM](https://user-images.githubusercontent.com/82361606/126631020-78aa0ec7-76d1-4162-ab47-106202a50bd7.png)

**Comment by xiaofan-luan** [comment]
@bigsheeper any updates on this?

**Comment by yhmo** [comment]
Link to #6675

**Comment by xiaofan-luan** [comment]
duplicate with #7056

**Comment by xiaofan-luan** [comment]
close for duplicate
