### ISSUE TITLE
To create an index need to call connection.load()

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#6748]
To create an index, you need to call connection.load(),
You can't call load once inside the inserted data, but you need to call load every time you change the index.
This should only need to load once

![22](https://user-images.githubusercontent.com/34296482/126629471-5b830523-9e26-41f2-aae7-b1f77c7a4338.png)

![21](https://user-images.githubusercontent.com/34296482/126629455-08644405-ba76-40dd-bf10-b10e6fc7b344.png)

**Comment by XuanYang-cn** [comment]
It's not a bug, although it may seem pretty weird comparing to 1.x.

(2021.9.15) Now, when calling `load_collection`, querynode will load indexes exist at this moment

For the later-built indexes, even with the same index type and params, querynode WON'T load them.

**So after loading collection, indexes in the memory will stay UNCHANGED, until releasing and reloading next time**, no matter
the same indexes built later or a new index type.
