### ISSUE TITLE
Milvus 2.0  started by docker compose, docker compose does not automatically connect to minio and etcd services after restarting Milvus services

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#6749]
Milvus hung up before and restarted with docker compose up

![1](https://user-images.githubusercontent.com/34296482/126657436-9ba3f771-40d0-4fdf-a99b-9358bafe51b8.png)
After restarting, use the client to link to the error report
![2](https://user-images.githubusercontent.com/34296482/126657468-88c812b5-5315-4f33-8938-8d35703558eb.png)
Milvus docker's logs，Internal components not working properly after Milvus service restart
![3](https://user-images.githubusercontent.com/34296482/126657481-fca7e4ab-be62-4fc0-aafd-0d22624f6652.png)
Then after  use docker compose down and up again, the data will be lost
![4](https://user-images.githubusercontent.com/34296482/126657493-4846cbf3-3609-4c06-bd48-81d5d33c3152.png)

**Comment by yhmo** [comment]
Please use the latest rc4 to try again.
