### ISSUE TITLE
Data takes 2 times more disk space than estimates from Milvus sizing tool

### ISSUE THREAD

**Issue by ss892714028** [milvus-io/milvus#6754]
#### Steps/Code to reproduce:
78 million, 128 dim vectors takes up 85 G of disk space, where in Milvus tools, the estimate is less than 40 G.

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: 

#### Configuration file:
[etcd.log](https://github.com/milvus-io/milvus/files/6866031/etcd.log)

**Comment by xiaofan-luan** [comment]
please offer more information about what is your deployment?
This may not be a bug, more likely to be data are shown on both logs and log snapshots.
You may want to check your data directory, do  a flush and clean log directory.
Milvus 2.0 stable release will clean up data automatically

**Comment by yhmo** [comment]
Answered and inactive, close it.
