### ISSUE TITLE
Call collection.load(): (code=1, message=call query coordinator LoadCollection: rpc error: code = DeadlineExceeded desc = context deadline exceeded)>

### ISSUE THREAD

**Issue by Bennu-Li** [milvus-io/milvus#6769]
#### Steps/Code to reproduce:
The status of the pods in the Milvus cluster are all running, call collection.load() error.
![image](https://user-images.githubusercontent.com/53458891/126749974-0f29942d-9d9a-423d-8210-9ee753e223b2.png)

pod status:
![image](https://user-images.githubusercontent.com/53458891/126750155-e4f18cec-f208-4b1e-a9ea-dd5dcfb7f281.png)

Through the logs , the querycoord received the request, but querynode don't respond.

[querycoord.log](https://github.com/milvus-io/milvus/files/6867201/querycoord.log)
[querynode.log](https://github.com/milvus-io/milvus/files/6867202/querynode.log)

#### Environment:
- Milvus version(v2.0.0-RC2):
- Deployment mode(cluster):
- SDK version(pymilvus v2.0.0rc2):

**Comment by del-zhenwu** [comment]
maybe duplicated with https://github.com/milvus-io/milvus/issues/6374

**Comment by xige-16** [comment]
["DataCoord Client grpc error"] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"], it seems the rootCoord was not connected， could you please provide the rootCoord's log?

**Comment by Bennu-Li** [comment]
it maybe duplicated with [#6849](https://github.com/milvus-io/milvus/issues/6849) , and it was solved.
