### ISSUE TITLE
website with different language

### ISSUE THREAD

**Issue by shiyu22** [milvus-io/milvus#677]
## Report incorrect documentation

**Location of incorrect documentation**
https://milvus.io/en/
https://milvus.io/docs/en/userguide/install_milvus/

**Describe the problems or issues found in the documentation**
In the first web, we can change different language in top left corner, but the second cannot.
Some other pages have the same problem.

**Comment by yamasite** [comment]
Nice catch! This is a limitation of our current documentation framework. However, we will soon migrate the Milvus documentation to a new framework, which will solve this issue.
