### ISSUE TITLE
Get collection will hang when Milvus standalone server is restarted with Docker Compose

### ISSUE THREAD

**Issue by jeffoverflow** [milvus-io/milvus#6777]
#### Steps/Code to reproduce:
The tarball contains `docker-compose.yml` and `hello_milvus2.py`.
[milvus_standalone_docker_compose.tar.gz](https://github.com/milvus-io/milvus/files/6867823/milvus_standalone_docker_compose.tar.gz)

- First start Milvus standalone Server:
```shell
tar zxvf milvus_standalone_docker_compose.tar.gz
cd test/
docker-compose up -d
docker inspect -f '{{range .NetworkSettings.Networks}}{{.Aliases}} {{.IPAddress}}{{end}}' $(docker-compose ps -q)
```
![image](https://user-images.githubusercontent.com/24581746/126764312-946b17f0-9089-413e-8a17-462e5435ccbe.png)

and run `hello_milvus2.py`

```shell
python3 hello_milvus2.py
```
![image](https://user-images.githubusercontent.com/24581746/126764266-1b51ff89-528b-4089-a39e-41f185ccd1b9.png)

export logs
```shell
docker logs milvus-standalone > 1.log
```
[1.log](https://github.com/milvus-io/milvus/files/6867863/1.log)

- Restart Milvus standalone Server
```shell
docker-compose down
docker-compose up -d
docker inspect -f '{{range .NetworkSettings.Networks}}{{.Aliases}} {{.IPAddress}}{{end}}' $(docker-compose ps -q)
```
![image](https://user-images.githubusercontent.com/24581746/126766545-6fcdf523-df7c-4ecb-9f4a-a71ad4ce7a80.png)

and rerun `hello_milvus2.py`, Milvus client get collection will hang.

```shell
python3 hello_milvus2.py
```
![image](https://user-images.githubusercontent.com/24581746/126764941-a7cea3aa-552d-4069-9475-3a1d67f0d691.png)

export logs
```shell
docker logs milvus-standalone > 2.log
```
[2.log](https://github.com/milvus-io/milvus/files/6867901/2.log)

#### Expected result:
1. list_collections() at the 2nd run of hello_milvus2 should return the collection that created at 1st run of hello_milvus2
2. Milvus should not hang if running hello_milvus2 for any times 

#### Actual results:
1. list_collections() return [] at the 2nd run of hello_milvus2
2. Milvus hang at the 2nd run of hello_milvus2

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): v2.0.0-RC2
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS):  Mac
- CPU/Memory:  8 vCPU / 32 G
- GPU: none
- Others: Docker

**Comment by yanliang567** [comment]
in short, data persistence of Milvus does not work if deployed with docker compose

**Comment by xige-16** [comment]
collection.num_entitties calls the flush interface, and the reason of milvus hang is that flush has not yet been completed. and #6658  may fix the issue. @jeffoverflow  @sunby

**Comment by xiaofan-luan** [comment]
close the duplicated issue
