### ISSUE TITLE
search timeout when running ci

### ISSUE THREAD

**Issue by sunby** [milvus-io/milvus#6785]
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-6590/7/pipeline/87/

**Comment by chole22** [comment]
https://github.com/milvus-io/milvus/issues/6785#issue-952007616
[Uploading financial_identifier_requests.csv…]()

**Comment by xiaofan-luan** [comment]
not active, close for now
