### ISSUE TITLE
[Load] Indexnode crashes when dropping an index

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#6787]
#### Steps/Code to reproduce:
1. deploy Milvus 2.0 with cluster mode
   1.1  limit indexnode and *node memory to 250MB , cpu 0.5
   1.2 limit index coord and *coord memory to 60MB
2. insert data(nb=10,000) for 10 times  
3. build index with {"index_type": "IVF_SQ8", "metric_type": "L2", "params": {"nlist": 64}}
   3.1 after index built, index node memory consumed 130MB
4. drop the index

#### Expected result:
drop index successfully

#### Actual results:
Indexnode crashes,  checking the resource consuming: memory 160MB, cpu 0.04

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): master-20210721-cbb4052
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by yanliang567** [comment]
<img width="625" alt="Screen Shot 2021-07-24 at 9 46 42 AM" src="https://user-images.githubusercontent.com/82361606/126864441-141fa9ca-3a9b-4cce-a5ef-338867cfb028.png">
<img width="798" alt="Screen Shot 2021-07-24 at 11 31 11 AM" src="https://user-images.githubusercontent.com/82361606/126864442-385389ea-1dca-49fa-9875-257def8366b7.png">

**Comment by xiaocai2333** [comment]
@yanliang567  Can you provide the indexcoord log?

**Comment by yanliang567** [comment]
need a while to re-setup an env, please hold on.

**Comment by xiaocai2333** [comment]
Working on it.

**Comment by yanliang567** [comment]
this time indexnode did not crash, but indexcoord crashed. :(
[indexcoord.6787.after.log](https://github.com/milvus-io/milvus/files/6892089/indexcoord.6787.after.log)
[indexcoord.6787.previous.log](https://github.com/milvus-io/milvus/files/6892090/indexcoord.6787.previous.log)
[indexnode.6787.log](https://github.com/milvus-io/milvus/files/6892091/indexnode.6787.log)

**Comment by xiaocai2333** [comment]
The bug of indexcoord crashed has been fixed, please retest it. @yanliang567

**Comment by yanliang567** [comment]
not reproduced on master-20210728-23bffe3
close
