### ISSUE TITLE
Cannot create producer on topic with backlog quota exceeded

### ISSUE THREAD

**Issue by huazaizai0322** [milvus-io/milvus#6791]
#### Steps/Code to reproduce:
Collection insertion that lasts several hours.

#### Expected result:
normal

#### Actual results:
![image](https://user-images.githubusercontent.com/38968544/126887316-d881b472-d950-40b4-a13d-a8e89f922cd1.png)

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): 
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.0.0rc2
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 
- GPU: 
- Others: 

#### Additional context:
After more than ten hours of normal operation of milvus, pulsar suddenly appeared backlog quota exceeded error.

**Comment by xige-16** [comment]
Is your disk filling up?

**Comment by xige-16** [comment]
> Is your disk filling up?

If not, could you describe your operation steps and the scale of inserted data?

**Comment by yanliang567** [comment]
@huazaizai0322

**Comment by huazaizai0322** [comment]
@xige-16 @yanliang567 
最开始的时候是pulsar中 backlog quota exceeded，之后我设成-1。
过一段时间，pulsar的pvc写满了，我将pvc容量增大，然后重启了pulsar。
当pulsar重启之后，发现datanode无法消费消息，就将milvus所有节点都重启，当我继续插入collection的时候，发现datacoord有日志更新，但是两个datanode节点都没有日志更新，都处于无消费状态。
![image](https://user-images.githubusercontent.com/38968544/126919704-555b1a95-b0e9-4201-886f-bd01b59dc698.png)
该截图，上面是datacoord，下面是datanode，当我正在插入collection的时候，datacoord会有日志更新，但是datanode的日志一直停留在启动的时候，两个datanode日志显示一样。

**Comment by huazaizai0322** [comment]
@xige-16 @yanliang567 
![image](https://user-images.githubusercontent.com/38968544/126920120-74d0514e-d818-4487-bf6d-42f01729de8e.png)
通过这个截图可以看到，pulsar的内存在增加，但是两个datanode完全没有动静，导致pulsar消息无法被消费，最后内存就容易爆掉

**Comment by sunby** [comment]
@huazaizai0322 Can you upload the full datacoord and datanode log? Thank you.

**Comment by huazaizai0322** [comment]
@sunby
第一张截图是datacoord的，基本上d都是插入数据的日志；
第二张截图是datanode的，起来之后就没有日志了，一直处于不消费状态；
我现在想知道怎么确认datanode是否注册成功了？
如果注册成功了，为什么不开始消费？
![image](https://user-images.githubusercontent.com/38968544/126923211-a2359b4e-2f2c-4d54-86ae-bbeac8604a62.png)
![image](https://user-images.githubusercontent.com/38968544/126923241-b987e428-cd15-4fc5-a1c8-b5a669b42126.png)

**Comment by huazaizai0322** [comment]
@sunby 
现在新插入的数据，全部block在pulsar里面了，pulsar的pvc都已经200多G了。
我将milvus所有节点、etcd、pulsar全部都试着重启过，datanode就是不消费。
![image](https://user-images.githubusercontent.com/38968544/126923449-cecc2daa-6081-4c5c-87b2-491238755556.png)

**Comment by sunby** [comment]
This issue will be fixed in rc3
