### ISSUE TITLE
Msg Stream Exponential Stream should not double retry time for ever

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#6796]
#### Steps/Code to reproduce:
Retry.go in Msgstream use exponential retry, but each retry sleep should has a limit rather than double forever.

#### Expected result:
retry sleep should be limited to a reasonble upper bound, say 1 minute.

#### Actual results:

![image](https://user-images.githubusercontent.com/83447078/126896245-b9205815-ef96-4547-895a-9c372bfdcc62.png)

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by xige-16** [comment]
I‘m looking into it.

**Comment by xiaofan-luan** [comment]
> I‘m looking into it.

No worry, I will send the pull request later

**Comment by xige-16** [comment]
The retry func in package is ussless，

**Comment by xige-16** [comment]
The retry func in msgstream package is uselss, you could use Do func in retry package instead. (internal/util/retry/retry.go)

**Comment by xiaofan-luan** [comment]
> The retry func in msgstream package is uselss, you could use Do func in retry package instead. (internal/util/retry/retry.go)

yep, that is exactly I'm doing. I'll remove retry.go in msg stream
