### ISSUE TITLE
Setup a default log retention time

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#6798]
#### What would you like to be added:
Need to add default log retention time , say 3 days. Log should be cleaned automatically if data is consumed.

#### Why is this needed:
We've see many user hit pulsar quota exceed. Persistent volume full is very dangerous and may cause serious trouble.

**Comment by xiaofan-luan** [comment]
We will wait until rocks mq support retention https://github.com/milvus-io/milvus/issues/6601

**Comment by yanliang567** [comment]
get off from rc3 due to no ETA for #6601

**Comment by yanliang567** [comment]
this is a long-term enhancement, lets keep it
