### ISSUE TITLE
Is there a "rollback" operation in Milvus? 

### ISSUE THREAD

**Issue by peixin-lin** [milvus-io/milvus#6805]
Situation: After I do some mutation on a collection (insertion or delete), I decide to abort my mutation before I flush the data.
Question: Is there an operation similar to the rollback operation in MySQL that allow me to abort these changes and they will not be made effect after a future flush operation?

**Comment by xiaofan-luan** [comment]
I don't think support any form of transaction in Milvus is a good idea, at least so far. 
I guess what you need is snapshot and rollback?

**Comment by yhmo** [comment]
Answered and inactive, close it.
