### ISSUE TITLE
In the case of only tens of thousands of data, the search time is likely to exceed 300ms intermittently

### ISSUE THREAD

**Issue by genting** [milvus-io/milvus#6812]
#### Steps/Code to reproduce:
        milvus_begin_time=time.time()
        vectors = milvus_client.search_vectors(table_name, [feat], TOP_K)
        milvus_end_time = time.time()
        milvus_time=milvus_end_time-milvus_begin_time
#### Expected result:
The amount of data is 42,000. When testing the retrieval time with the above code, it is found that the retrieval time is uneven, occasionally 300ms

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):
- v2.0.0
- Deployment mode(standalone or cluster):
- standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
- pymilvus v2.0.0rc2
- OS(Ubuntu or CentOS): 
- ubuntu18.04
- CPU/Memory: 
- 48GB
- GPU: 
- Others: 

#### Configuration file:
![Uploading lALPDh0cP9sYkQHNA83NB20_1901_973.png…]()
![lALPDiQ3PSTHh3_Mk80DVA_852_147](https://user-images.githubusercontent.com/33156177/126972302-1564821e-b919-462c-8834-06b031eb0e67.png)

**Comment by yhmo** [comment]
@genting 
Could you provide more informations:
- Vector dimensions?
- Did you create index? If yes, what kind of index, what is the parameter(nlist, etc)
- How many vectors(nq) in the "[feat]"
- If you created IVF_FLAT index, what is the value of "nprobe"
- What is the value of the "TOP_K"

**Comment by genting** [comment]
Some more detailed information is included in the attachment. Thanks Reply


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "milvus-io/milvus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月29日(星期四) 下午2:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [milvus-io/milvus] In the case of only tens of thousands of data, the search time is likely to exceed 300ms intermittently (#6812)





 
@genting
 Could you provide more informations:
  
Vector dimensions?
 
Did you create index? If yes, what kind of index, what is the parameter(nlist, etc)
 
How many vectors(nq) in the "[feat]"
 
If you created IVF_FLAT index, what is the value of "nprobe"
 
What is the value of the "TOP_K"

**Comment by genting** [comment]
1：Vector dimensions  512 
2 ："index_type": "IVF_SQ8", "metric_type": L2, "params": {"nlist": 16384}
3: 42272
5: TOP_K 50

**Comment by yhmo** [comment]
@genting It seems your are using milvus v1.x, not v2.0.
I guess your steps are:
1. create a collection by `create_collction()`
2. create index by `create_index()`
3. insert 42000 vectors
4. search

For v1.x, there are two ways to build index:
A. create_collection() -> create_index() -> insert()
B. create_collection() -> insert() -> create_index()

The A: specify index type and insert, milvus will automatically build index for segments which size larger than `index_file_size`
The B: manually build index after insert data, force build index for each segment which row count larger than 4096.
Please refer this documentation: https://milvus.io/docs/v1.1.1/create_drop_index_python.md

If your steps is A, the segment with 42000 row count may less than `index_file_size`, that means no index is build, the search is brute-force search.

To verify this, you can modify your code like this:
1. create_collection() // create a new collection
2. insert()   // insert 42000 rows
3. create_index() // create index IVF_SQ8 with nlist=16384
