### ISSUE TITLE
Milvus generates wrong log file name of component

### ISSUE THREAD

**Issue by jeffoverflow** [milvus-io/milvus#6813]
#### Steps/Code to reproduce:
![image](https://user-images.githubusercontent.com/24581746/126985803-290dd7e7-a82e-4a46-8f90-d7777bd3d3a3.png)

When I export the Milvus log to file, Milvus generates wrong log file name. And when multiple instances of the component are started, the logs generated by these instances are output to the same log file. These log file can't be useful in helping to identify and fix issues.

#### Expected result:
Each instance has a correct and unique log file name.

#### Actual results:
Milvus generates wrong log file name of component

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): v2.0.0-RC2
- Deployment mode(standalone or cluster): standalone and cluster

/assign @xiaofan-luan

**Comment by xiaofan-luan** [comment]
working on it
