### ISSUE TITLE
grpc deadline Exceeded  when running test cases

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#6817]
#### Steps/Code to reproduce:

Running test search cases :
pytest  /milvus/tests20/python_client/testcases/test_search.py  --workers 4

Logs:
[log.tar.zip](https://github.com/milvus-io/milvus/files/6878638/log.tar.zip)

#### Expected result:
No errors

#### Actual results:
FAILED test_search.py::TestCollectionSearch::test_search_before_after_delete[500-128-False-False] - AttributeError: 'NoneType' object has no attribute '__len__'
FAILED test_search.py::TestCollectionSearch::test_search_before_after_delete[500-128-False-True] - grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
FAILED test_search.py::TestCollectionSearch::test_search_before_after_delete[500-128-True-True] - grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
FAILED test_search.py::TestCollectionSearch::test_search_before_after_delete[500-128-True-False] - AttributeError: 'NoneType' object has no attribute '__len__'
FAILED test_search.py::TestCollectionSearch::test_search_partition_after_release_one[2-8-False-False] - AttributeError: 'NoneType' object has no attribute '__len__'
FAILED test_search.py::TestCollectionSearch::test_search_partition_after_release_one[2-8-False-True] - grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
FAILED test_search.py::TestCollectionSearch::test_search_partition_after_release_one[2-8-True-False] - AttributeError: 'NoneType' object has no attribute '__len__'
FAILED test_search.py::TestCollectionSearch::test_search_partition_after_release_one[2-8-True-True] - grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
FAILED test_search.py::TestCollectionSearch::test_search_partition_after_release_one[2-128-False-True] - grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
FAILED test_search.py::TestCollectionSearch::test_search_partition_after_release_one[2-128-False-False] - AttributeError: 'NoneType' object has no attribute '__len__'
FAILED test_search.py::TestCollectionSearch::test_search_partition_after_release_one[2-128-True-True] - grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
FAILED test_search.py::TestCollectionSearch::test_search_partition_after_release_one[2-128-True-False] - AttributeError: 'NoneType' object has no attribute '__len__'
FAILED test_search.py::TestCollectionSearch::test_search_partition_after_release_one[500-8-False-True] - grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
FAILED test_search.py::TestCollectionSearch::test_search_partition_after_release_one[500-8-False-False] - AttributeError: 'NoneType' object has no attribute '__len__'
FAILED test_search.py::TestCollectionSearch::test_search_partition_after_release_one[500-8-True-True] - grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
FAILED test_search.py::TestCollectionSearch::test_search_partition_after_release_one[500-8-True-False] - AttributeError: 'NoneType' object has no attribute '__len__'

[2021-07-26 13:26:13 - ERROR - pymilvus.client.grpc_handler]:
Addr [172.18.255.155:19530] search_with_expression
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1627305973.930117500","description":"Error received from peer ipv4:172.18.255.155:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Deadline Exceeded","grpc_status":4}

self = <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exc...55:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
timeout = None

    def result(self, timeout=None):
        """Returns the result of the computation or raises its exception.

        See grpc.Future.result for the full API contract.
        """
        with self._state.condition:
            timed_out = _common.wait(
                self._state.condition.wait, self._is_complete, timeout=timeout)
            if timed_out:
                raise grpc.FutureTimeoutError()
            else:
                if self._state.code is grpc.StatusCode.OK:
                    return self._state.response
                elif self._state.cancelled:
                    raise grpc.FutureCancelledError()
                else:
>                   raise self
E                   grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
E                   	status = StatusCode.DEADLINE_EXCEEDED
E                   	details = "Deadline Exceeded"
E                   	debug_error_string = "{"created":"@1627307871.226342900","description":"Error received from peer ipv4:172.18.255.155:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Deadline Exceeded","grpc_status":4}"

#### Environment:
- Milvus version(): e43b43e
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
Name: pymilvus
Version: 2.0.0rc3.dev6
Name: pymilvus-orm
Version: 2.0.0rc3.dev7 (also 2.0.0rc3.dev8)

- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by binbinlv** [comment]
Same rpc error when running CI, so pasted here if it could be a help.

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-6839/1/pipeline/106

**Comment by xiaocai2333** [comment]
Execution timeout caused this error. The timeout period is too short, I see timeout=5, try increasing it.

**Comment by binbinlv** [comment]
I increased the timeout to 20s, then it indeed could avoid this error.

And discussed with yanliang, there are two points maybe needed to be fixed:

(1) this error occurs at different case for each CI or tests, then why sometimes it could return in 5s and sometimes not. It indicates system is unstable. Then it should have some bugs needed to be digged or somewhere could be improved. 
If some individual cases need long timeout(such as maximum config cases), we could set the timeout for these cases separately. But now for this case, maybe the root cause is that system is not stable.

(2) This error message is meaningless for timeout issue.

@xiaocai2333 @czs007 @yanliang567 
what is your suggestion?

**Comment by xiaocai2333** [comment]
I agree. We do need to improve the stability of the system.

**Comment by yanliang567** [comment]
Moving to rc2 backlog, as there is a workaround with more timeout

**Comment by binbinlv** [comment]
It occurs in nightly CI rencently, [standalone], so put it in RC6 to have a look again.

https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/122/

- milvus(build from source):  7c4b15e
- pymilvus: 2.0.0rc5.dev29

error="syncTimestamp Failed:rpc error: code = DeadlineExceeded
RootCoord Client grpc error"] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"
