### ISSUE TITLE
Current installation docs do not cover how to prevent data loss after restarting the docker.

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus#6822]
We need details about how to mapping volumes to these dockers.

**Comment by jeffoverflow** [comment]
You can deploy Milvus with docker-compose.  See: https://github.com/milvus-io/milvus/blob/master/deployments/docker/standalone/docker-compose.yml

**Comment by shanghaikid** [comment]
Thanks, but we still need a doc describe these VOLUMES  @LocoRichard

**Comment by LocoRichard** [comment]
issue fixed. It can be closed now.
