### ISSUE TITLE
Need to change Milvus' documentation

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#6837]
Need to tell where to change milvus.yaml
The difference between dockers compose and minikube modifications
https://milvus.io/docs/v2.0.0/configuration_standalone-basic.md
![微信图片_20210727172616](https://user-images.githubusercontent.com/34296482/127130697-aa4a54ee-191a-4b3b-9a95-eae5559fd7bf.png)

**Comment by LocoRichard** [comment]
Thank you @jingkl . It's well received, and I am working on it. A kind reminder is that please file doc issues of milvus.io in our milvus-io/milvus-docs repo. Thank you again.

**Comment by LocoRichard** [comment]
issue fixed. Although I can't close it.
