### ISSUE TITLE
Bug: proxy returns wrong distances for some metric_types, such as tanimoto, jaccard

### ISSUE THREAD

**Issue by DragonDriver** [milvus-io/milvus#6843]
In order to reduce all search results from query nodes in Proxy, we should tag a score for every hit record in search result. Score is related with distance and in fact we only have distances now. However, score is not always positively related to distance. For example, `L2` distance and `Hamming` distance, larger distance between two vectors means that the two vectors are less similar. Proxy sort the hit record by descending score, so for those metric_types that score is positively related to distance, we will negate the distance to keep the descending order. After the reduce operation is done, we will negate the score to distance again to get right distance. However, only `ip` distance is negated now, we ignored other metric_types that score is positively related to distance, for example, tanimoto, jaccard.

**Comment by DragonDriver** [comment]
I will fix this soon.
/assign

**Comment by DragonDriver** [comment]
We need to add `distances` in `SearchResultData` and then fill the real distance.

```protobuf
message SearchResultData {
  int64 num_queries = 1;
  int64 top_k = 2;
  repeated FieldData fields_data = 3;
  repeated float scores = 4;
  IDs ids = 5;
  repeated int64 topks = 6;
  repeated float distances = 7;
}
```

**Comment by xiaofan-luan** [comment]
@DragonDriver how is the progress for now?

**Comment by yanliang567** [comment]
@DragonDriver is this ready for testing? if yes, please assign to me. thanks

**Comment by xiaofan-luan** [comment]
@DragonDriver  we should add distance in the returned result, how about reverse score for IP so we always follow smaller score wins

**Comment by DragonDriver** [comment]
> @DragonDriver we should add distance in the returned result, how about reverse score for IP so we always follow smaller score wins

OK

**Comment by DragonDriver** [comment]
Fixed by simply "reversing" the distance to score.
We can reopen this later if we need to change the way we score to the hit records.

**Comment by cydrain** [comment]
| metric type | range | similar | not similar |
-------------------------------------------------------
| L2 | (-inf, inf) | small | large |
