### ISSUE TITLE
After inserting data into Milvus Pymilvus hangs when calls search, num_entity.

### ISSUE THREAD

**Issue by ss892714028** [milvus-io/milvus#6850]
#### Steps/Code to reproduce:
created 3 collections, ann_1m, ann_10m, ann_100m and inserted 1 million, 10 million and 100 million vectors respectively, 100k at a time. During inserting 100 million vectors into ann_100m collection, after 61.7 million vectors inserted, insert time cost becomes unstable and pymilvus throws the following error.
![image](https://user-images.githubusercontent.com/34635663/127260419-c6761db9-7932-4c19-b459-8909eeb6f407.png)

However, after the error, the insert seems to continue and all 100 million vectors are inserted into ann_100m collection.
![image](https://user-images.githubusercontent.com/34635663/127260521-f369f3fc-9a5b-40dc-94c0-d60612bfa6db.png)

After the insert, operation (search, num_entity) with Milvus hangs, with Pymilvus not throwing any errors.
I have attached the log with this issue. 
[0728insert.new.log](https://github.com/milvus-io/milvus/files/6890189/0728insert.new.log)

In the log, on 7/27 is the collection creation and vector insertion, 3 collections ann_1m, ann_10m, ann_100m with 1 million, 10 million and 100 million vectors respectively. On 7/28 roughly 01:38:35, called num_entity and pymilvus hangs forever. 
#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):  v2.0.0-RC2
- Deployment mode(standalone or cluster): standalone, minikube
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus v2.0.0rc2
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: intel i7 8700/50g
- GPU: 
- Others:

**Comment by yanliang567** [comment]
@ss892714028  what's the dim of vectors? what about call search or num_entities against ann_1m or 1nn_10m?  I am asking because if you inserted 100m vectors with 128d, the data size is almost 50G, which could exceed the memory you have.

**Comment by ss892714028** [comment]
> @ss892714028 what's the dim of vectors? what about call search or num_entities against ann_1m or 1nn_10m? I am asking because if you inserted 100m vectors with 128d, the data size is almost 50G, which could exceed the memory you have.

This is caused by insufficient memory, I am closing this issue. :)
