### ISSUE TITLE
Calling the release interface causes the Milvus service to hang

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#6868]
Calling the release interface twice, with 10 million data in the collection, causes Milvus to hang the second time
![release](https://user-images.githubusercontent.com/34296482/127295428-be955003-55bb-4952-a4bb-8a96b50fa7c4.png)

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):v2.0.0-RC2 
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus v2.0.0rc2
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 64
- GPU: 
- Others:

**Comment by xiaofan-luan** [comment]
@xige-16 is this still a reason for current version?

**Comment by xige-16** [comment]
> @xige-16 is this still a reason for current version?

I'll check it out.

**Comment by xige-16** [comment]
I didn't reproduce the bug.  I put this issue on rc6 first, and I will turn it offf if it doesn't recur later.

**Comment by xige-16** [comment]
This issue no longer appears, if it does, I will open it again.
