### ISSUE TITLE
Data persist issue with external directory(volumes) instead of docker-container

### ISSUE THREAD

**Issue by desharma12** [milvus-io/milvus#6876]
Hi,
I have setup the milvus by docker-compose(milvus cluster setup). milvus version is 2.0.0.rc1.
I have change the "etcd", "minio", "pulsar" path in docker-compose.yml file to insert the data in this directory instead of docker container. I created the volumes to store the data in the these directory.

Change the docker-compose.yml file, and add the volumes for etcd/minio/pulsar, like as:
1: for etcd:
    disk_path:/etcd:/default.etcd

2: for minio:
  disk_path:minio:/minio_data

3: for pulsar:
 disk_path :/pulsar/data

**Run/Stop Docker container**
To start the docker container, using the below command:
  docker-compose up -d
To stop the docker container, using the below command:
  docker-compose down

When I start the docker container, it is working fine at initial level. but when I restart the docker container again and again. then it is showing "proxy is not healthy" on Insite url. see the attached screenshot
<img width="928" alt="1" src="https://user-images.githubusercontent.com/88093307/127326718-6d38fc9b-d101-4261-ae3c-202650b82091.png">

Also unable to insert/search the record from milvus. it is showing "server is not healthy, please try again later", seethe attached screenshot
<img width="390" alt="error" src="https://user-images.githubusercontent.com/88093307/127327147-bdc846ca-dd31-45b1-ad0a-a442b6fe347f.png">

when check the all the service, then it is showing pulsar service is exit, see the attached screenshot
<img width="479" alt="pulsar" src="https://user-images.githubusercontent.com/88093307/127327318-7a1a0fff-80f7-4320-ac41-186b71b54f98.png">

See the pulsar logs:
milvus-pulsar | 21:04:04.331 [main] ERROR org.apache.pulsar.PulsarStandaloneStarter - Failed to start pulsar service.
milvus-pulsar | io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
milvus-pulsar |         at io.grpc.Status.asRuntimeException(Status.java:533) ~[io.grpc-grpc-api-1.33.0.jar:1.33.0]
milvus-pulsar |         at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533) ~[io.grpc-grpc-stub-1.33.0.jar:1.33.0]
milvus-pulsar |         at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:616) ~[io.grpc-grpc-core-1.33.0.jar:1.33.0]
milvus-pulsar |         at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:69) ~[io.grpc-grpc-core-1.33.0.jar:1.33.0]
milvus-pulsar |         at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:802) ~[io.grpc-grpc-core-1.33.0.jar:1.33.0]
milvus-pulsar |         at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:781) ~[io.grpc-grpc-core-1.33.0.jar:1.33.0]
milvus-pulsar |         at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[io.grpc-grpc-core-1.33.0.jar:1.33.0]
milvus-pulsar |         at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[io.grpc-grpc-core-1.33.0.jar:1.33.0]
milvus-pulsar |         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
milvus-pulsar |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
milvus-pulsar |         at java.lang.Thread.run(Thread.java:829) ~[?:?]
milvus-pulsar | Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /192.168.160.6:4181
milvus-pulsar | Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
milvus-pulsar |         at io.grpc.netty.shaded.io.netty.channel.unix.Errors.throwConnectException(Errors.java:124) ~[io.grpc-grpc-netty-shaded-1.33.0.jar:1.33.0]
milvus-pulsar |         at io.grpc.netty.shaded.io.netty.channel.unix.Socket.finishConnect(Socket.java:243) ~[io.grpc-grpc-netty-shaded-1.33.0.jar:1.33.0]
milvus-pulsar |         at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:672) ~[io.grpc-grpc-netty-shaded-1.33.0.jar:1.33.0]
milvus-pulsar |         at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:649) ~[io.grpc-grpc-netty-shaded-1.33.0.jar:1.33.0]
milvus-pulsar |         at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:529) ~[io.grpc-grpc-netty-shaded-1.33.0.jar:1.33.0]
milvus-pulsar |         at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:465) ~[io.grpc-grpc-netty-shaded-1.33.0.jar:1.33.0]
milvus-pulsar |         at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[io.grpc-grpc-netty-shaded-1.33.0.jar:1.33.0]
milvus-pulsar |         at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[io.grpc-grpc-netty-shaded-1.33.0.jar:1.33.0]
milvus-pulsar |         at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.grpc-grpc-netty-shaded-1.33.0.jar:1.33.0]
milvus-pulsar |         at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.grpc-grpc-netty-shaded-1.33.0.jar:1.33.0]
milvus-pulsar |         ... 1

Can you please guide me, how to fix this issue.

Thanks

**Comment by yhmo** [comment]
It may be defect of rc1, please try the latest version rc4.
