### ISSUE TITLE
Improve guidelines for test framework

### ISSUE THREAD

**Issue by xige-16** [milvus-io/milvus#6877]
#### What would you like to be added:
1. the deployment environment
2. how to run cluster milvus
3.  LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 when run ./e2e-k8s.sh
4. how to find the log paths?

**Comment by yanliang567** [comment]
@wangting0128 please help to update the guide https://github.com/milvus-io/milvus/tree/master/tests20/python_client acoordingly

**Comment by wangting0128** [comment]
@xige-16 
Does this document solve your problem?
https://github.com/milvus-io/milvus/blob/master/tests20/python_client/README_CN.md

**Comment by xige-16** [comment]
> @xige-16
> Does this document solve your problem?
> https://github.com/milvus-io/milvus/blob/master/tests20/python_client/README_CN.md

I just went through the above problems following this document.

**Comment by wangting0128** [comment]
> > @xige-16
> > Does this document solve your problem?
> > https://github.com/milvus-io/milvus/blob/master/tests20/python_client/README_CN.md
> 
> I just went through the above problems following this document.

Okay, can this issue be closed?
