### ISSUE TITLE
Cache inMemory collection info in proxy

### ISSUE THREAD

**Issue by xige-16** [milvus-io/milvus#6887]
#### What would you like to be added:
internal/proxy/task.go: 1406-1435

	// check if collection was already loaded into query node
	showResp, err := st.qc.ShowCollections(st.ctx, &querypb.ShowCollectionsRequest{
		Base: &commonpb.MsgBase{
			MsgType:   commonpb.MsgType_ShowCollections,
			MsgID:     st.Base.MsgID,
			Timestamp: st.Base.Timestamp,
			SourceID:  Params.ProxyID,
		},
		DbID: 0, // TODO(dragondriver)
	})
	if err != nil {
		return err
	}
	if showResp.Status.ErrorCode != commonpb.ErrorCode_Success {
		return errors.New(showResp.Status.Reason)
	}
	log.Debug("query coordinator show collections",
		zap.Any("collID", collID),
		zap.Any("collections", showResp.CollectionIDs),
	)
	collectionLoaded := false
	for _, collectionID := range showResp.CollectionIDs {
		if collectionID == collID {
			collectionLoaded = true
			break
		}
	}
	if !collectionLoaded {
		return fmt.Errorf("collection %v was not loaded into memory", collectionName)
	}
before every search request , a gprc recall to queryCoord will be sent, proxy could use cache info to speed up the process

**Comment by DragonDriver** [comment]
OK, i will take some time to list all objects used in Proxy that need to be cached. Not only for loaded collection list, but also for some others. I will also share a design doc about how to refactor the cache in Proxy later.

**Comment by DragonDriver** [comment]
Maybe in-memory collection list is not appropariate to be cached. When there are two or more proxy in system, any `load` or `release` operation will lead the inconsistency of cache. So we should invalidate the cache every time users call `load` or `release`, this will also be a big cost. If the frequency of search is much bigger than the frequency of `load` of `release`, caching in-memory collection list is better. But if there are a lot of collections in system and the users let the collections online/offline in query nodes frequently, caching is worse.
