### ISSUE TITLE
Where is the restful api doc in milvus 1.1.1 website?

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#6901]
link: https://milvus.io/cn/docs/v1.1.1/home

![image](https://user-images.githubusercontent.com/53512883/127608054-6bc7063f-a0ad-4363-8dff-0890cac9b3f5.png)

**Comment by shanghaikid** [comment]
The doc should link to https://github.com/milvus-io/milvus/tree/1.1/core/src/server/web_impl

**Comment by LocoRichard** [comment]
/assign @shanghaikid 
issue fixed, need to close the issue.
