### ISSUE TITLE
Distance is calculated wrong using calc_distance interface when metric type is "IP"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#6902]
#### Steps/Code to reproduce:
```python
from pymilvus_orm import connections
from pymilvus_orm import utility
import random
connections.connect()
vectors_l = [[random.random() for _ in range(2)] for _ in range(5)]
vectors_r = [[random.random() for _ in range(2)] for _ in range(5)]
op_l = {"float_vectors": vectors_l}
op_r = {"float_vectors": vectors_r}
results = utility.calc_distance(vectors_left=op_l, vectors_right=op_r)
import numpy as np
distance1= np.linalg.norm(np.array(vectors_l[0]) - np.array(vectors_r[0]))
```

results:
```
results = utility.calc_distance(vectors_left=op_l, vectors_right=op_r)
results
[[0.2557201385498047, 0.20111922919750214, 0.13177073001861572, 0.4435957670211792, 0.5783697366714478], [0.3167160153388977, 0.45764774084091187, 0.23657941818237305, 0.03262489289045334, 0.07185335457324982], [0.008473444730043411, 0.7094448804855347, 0.07139235734939575, 0.37216416001319885, 0.11417490243911743], [0.15033380687236786, 0.4071313738822937, 0.10462988913059235, 0.5507066249847412, 0.5219589471817017], [0.34655046463012695, 0.054755423218011856, 0.1604655385017395, 0.08397960662841797, 0.34670916199684143]]

distance1= np.linalg.norm(np.array(vectors_l[0]) - np.array(vectors_r[0]))
distance1
0.5056877409702799
```

#### Expected result:
for L2, sqrt=false:

for vectors_l[0] and vectors_r[0]: it is 0.5056877409702799
which is not equal with 0.2557201385498047.

#### Actual results:
[[0.2557201385498047, 0.20111922919750214, 0.13177073001861572, 0.4435957670211792, 0.5783697366714478], [0.3167160153388977, 0.45764774084091187, 0.23657941818237305, 0.03262489289045334, 0.07185335457324982], [0.008473444730043411, 0.7094448804855347, 0.07139235734939575, 0.37216416001319885, 0.11417490243911743], [0.15033380687236786, 0.4071313738822937, 0.10462988913059235, 0.5507066249847412, 0.5219589471817017], [0.34655046463012695, 0.054755423218011856, 0.1604655385017395, 0.08397960662841797, 0.34670916199684143]]

#### Environment:
- Milvus version():7307332
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
Name: pymilvus
Version: 2.0.0rc3.dev7
Name: pymilvus-orm
Version: 2.0.0rc3.dev9

- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by yhmo** [comment]
By default "sqrt" is False.
The np.linalg.norm() sqrt is True.
You can verify it by the following code:

```
vectors_l = [[0.2652013845482013, 0.7569466587033686]]
vectors_r = [[0.05753491542962896, 0.7358918451495691]]
print(vectors_l)
print(vectors_r)
op_l = {"float_vectors": vectors_l}
op_r = {"float_vectors": vectors_r}
params = {"sqrt": True}
results = utility.calc_distance(vectors_left=op_l, vectors_right=op_r, params=params)
print("milvus", results)

import numpy as np
distance1= np.linalg.norm(np.array(vectors_l[0]) - np.array(vectors_r[0]))
print("numpy", distance1)
```

Set the "sqrt"= True, the results are equal.
Set the "sqrt"=False, the results are not equal.

**Comment by binbinlv** [comment]
OK, thanks very much. @yhmo 

And retry, work as design, so close it.

**Comment by binbinlv** [comment]
When specifying metric type as "IP", the distance calculated is wrong (which is the same with that the default metric type "L2"), so maybe the metric type not works.

from pymilvus_orm import connections
from pymilvus_orm import utility
import random
connections.connect()
vectors_l = [[0.2652013845482013, 0.7569466587033686]]
vectors_r = [[0.05753491542962896, 0.7358918451495691]]
print(vectors_l)
[[0.2652013845482013, 0.7569466587033686]]
print(vectors_r)
[[0.05753491542962896, 0.7358918451495691]]
op_l = {"float_vectors": vectors_l}
op_r = {"float_vectors": vectors_r}
params = {"metric_type": "IP"}
results = utility.calc_distance(vectors_left=op_l, vectors_right=op_r, params=params)
results
[[0.04356867074966431]]

import numpy as np
distance1= np.inner(np.array(vectors_l[0]), np.array(vectors_r[0]))
distance1
0.5722892125848243

**Comment by binbinlv** [comment]
Wrong use of parameter name, close it.
