### ISSUE TITLE
(crash) unknown field name "source_nodeIDs"

### ISSUE THREAD

**Issue by codenoid** [milvus-io/milvus#6903]
#### Steps/Code to reproduce:

I don't know

#### Environment:
- Milvus version milvusdb/milvus:v2.0.0-rc2-20210712-a8e5fd2
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus
- OS(Ubuntu or CentOS): Ubuntu 20.04
- CPU/Memory: 8C/32GB
- GPU: Intel Iris Plus
- Others: ok

#### Configuration file:

default

#### Additional context:

even after I drop all the container, and use the fresh standalone version, the bug still there

5 sec after I start the server, i do .insert with pymilvus, but

```sh
server is not healthy, please try again later
```

the crash comes after a minutes (if i'm not wrong) after start

![Screenshot from 2021-07-30 14-13-39](https://user-images.githubusercontent.com/14269809/127615939-d7347404-ccf4-4ab1-81fa-e09373e47f39.png)

**Comment by codenoid** [comment]
1. Start the server
2. pymilvus insert
3. Do *literally* nothing
4. Milvus exited

![Screenshot from 2021-07-30 14-44-36](https://user-images.githubusercontent.com/14269809/127619290-ad68b9c8-09ce-4de0-a026-1e7525bf2fe3.png)

**Comment by codenoid** [comment]
It's working again after I drop all container, erase any cache, and move (root) working dir

**Comment by czs007** [comment]
It is because of the wrong use of the proto interface. We are fixing this problem. 
@codenoid Thank you for your feedback.
