### ISSUE TITLE
 Milvus official website hybrid search website link not working

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#6904]
https://milvus.io/bootcamp
![ali](https://user-images.githubusercontent.com/34296482/127616353-e9e6cfff-3b70-4475-8e62-7009cc6d3b90.png)

We already support scalar queries in Milvus 2.0, can we take down the tutorial now?

**Comment by shanghaikid** [comment]
you can ask @shiyu22 to update this part.

**Comment by shiyu22** [comment]
Update it, and the hybrid search is for Milvus1.x, you can refer to https://github.com/milvus-io/bootcamp/tree/1.1/solutions/hybrid_search
