### ISSUE TITLE
standalone minikube milvus 2.0 rc2 load stuck

### ISSUE THREAD

**Issue by ss892714028** [milvus-io/milvus#6906]
#### Steps/Code to reproduce:
There are 10m 128-dimensional data in the collection. The python client reported an error when building the sq8 index, but calling get_index_progress showed that the 10m data has been indexed. After calling load on the same collection, pymilvus stuck for a long time, and calling get_loading_progress at the same time showed that only 9,000,175 vectors were loaded. 
![image](https://user-images.githubusercontent.com/34635663/127633872-6e492f09-dbb6-4e46-b56e-cc44dc4a7444.png)
error from PyMilvus when building index
![image](https://user-images.githubusercontent.com/34635663/127633881-7bbc3a4d-a3a7-4f32-9b7d-3b221198247a.png)
10 million data is loaded according to get_index_progress
![image](https://user-images.githubusercontent.com/34635663/127633893-43c042e0-ef30-42dc-9765-bf5567631841.png)
Pymilvus stuck during load
![image](https://user-images.githubusercontent.com/34635663/127634808-cfed4cf8-3bf6-4b90-840b-03423d74824e.png)
only 9m data loaded

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): rc2
- Deployment mode(standalone or cluster): minikube standalone
- SDK version(e.g. pymilvus v2.0.0rc2): rc2
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 12c/50g
- GPU: na
- Others: 

#### Additional context:
log file is here
[processed_log.log.zip](https://github.com/milvus-io/milvus/files/6906638/processed_log.log.zip)

**Comment by xiaocai2333** [comment]
This should be a bug about 'load'. From the log. there are two segemnts that failed to load. This bug may have been fixed, please retest it. @ss892714028

**Comment by xiaocai2333** [comment]
I temporarily close it, if you still encounter this problem, please reopen it.
