### ISSUE TITLE
Customize collection channel via SDK

### ISSUE THREAD

**Issue by Bennu-Li** [milvus-io/milvus#6907]
#### Is your feature request related to a problem? Please describe:
I found that insert performance does not increase with the number of datanodes.

**Comment by del-zhenwu** [comment]
The numbers of proxy node does affect on the insert performance, instead of the data node

**Comment by yanliang567** [comment]
data node affects the performance of flush()

**Comment by yanliang567** [comment]
@Bennu-Li  so what's your reference of this ticket?

**Comment by Bennu-Li** [comment]
> @Bennu-Li so what's your reference of this ticket?

@sunby told me this:

The default is 2 channels for 1 collection, and one datanode is enough.
Without reaching the bottleneck, 2 datanodes can't really improve the insertion speed
If each channel consumes a certain speed, more channels can speed up insertion.

**Comment by xiaofan-luan** [comment]
duplicate with #6690
