### ISSUE TITLE
Search in sub-set specified by given id array

### ISSUE THREAD

**Issue by yan-rui** [milvus-io/milvus#6911]
在推荐场景，有一种非常普遍的情况，需要在指定的集合中搜索topk，而不是在全集中搜索topk

例1:
在社交推荐中，当推荐系统（以下简称RS）给一个user推荐他可能愿意交流的其他user时，要求其他user必须是在线状态。线上一般会维护一个当前在线用户的列表。当RS向MIlvus请求时，把在线的这部分user ID一起放入请求中(或者其他方式)。MIlvus在搜索topk的user时，只在请求中包含的这部分user ID中搜索。

例2:
更加普遍的情况，MIlvus一般用在召回阶段，往往在filter之后。所以在召回时，需要指定哪些 ID 是需要过滤的，或者指定只在过滤后的小collection中搜索。

需求如下：
searchInIdSet(collection_name, id, idSet)
searchInVectorSet(collection_name, vector, vectorSet)
searchInIdSet(collection_name, vector, idSet)
searchInVectorSet(collection_name, id, vectorSet)

整个collction：[1,2,3,4,5],
当前请求时，2、5不在线，所以需要在 [1,3,4] 中搜索

**Translation by Google translator:**

In the recommendation scenario, there is a very common situation where you need to search for topk in the specified collection instead of searching for topk in the full set

example 1:
In social recommendation, when the recommendation system (hereinafter referred to as RS) recommends to a user other users that he may be willing to communicate with, it requires other users to be online. Online generally maintains a list of current online users. When RS makes a request to MIlvus, it puts the online user ID into the request (or other methods). When MIlvus searches for topk users, it only searches in this part of the user ID included in the request.

Example 2:
More generally, MIlvus is generally used in the recall phase, often after the filter. Therefore, when recalling, you need to specify which IDs need to be filtered, or specify to search only in the filtered small collection.

The requirements are as follows:
searchInIdSet(collection_name, id, idSet)
searchInVectorSet(collection_name, vector, vectorSet)
searchInIdSet(collection_name, vector, idSet)
searchInVectorSet(collection_name, id, vectorSet)

The entire collction: [1,2,3,4,5],
At the time of the current request, 2 and 5 are not online, so you need to search in [1,3,4]

**Comment by yhmo** [comment]
We will provide a new api named "calc_distance()", #5443. Can this api meet your requirement?
The definition of the new api:
def calc_distance(self, vectors_left, vectors_right, params=None, timeout=None, **kwargs):
"""
        Calculate distance between two vector arrays.

        :param vectors_left: The vectors on the left of operator.
        :type  vectors_left: dict
        `{"ids": [1, 2, 3, .... n], "collection": "c_1", "partition": "p_1", "field": "v_1"}`
        or
        `{"float_vectors": [[1.0, 2.0], [3.0, 4.0], ... [9.0, 10.0]]}`
        or
        `{"bin_vectors": [b'\x94', b'N', ... b'\xca']}`

        :param vectors_right: The vectors on the right of operator.
        :type  vectors_right: dict
        `{"ids": [1, 2, 3, .... n], "collection": "col_1", "partition": "p_1", "field": "v_1"}`
        or
        `{"float_vectors": [[1.0, 2.0], [3.0, 4.0], ... [9.0, 10.0]]}`
        or
        `{"bin_vectors": [b'\x94', b'N', ... b'\xca']}`

        :param params: parameters, currently only support "metric_type", default value is "L2"
                       extra parameter for "L2" distance: "sqrt", true or false, default is false
                       extra parameter for "HAMMING" and "TANIMOTO": "dim", set this value if dimension is not a multiple of 8, otherwise the dimension will be calculted by list length
        :type  params: dict
            There are examples of supported metric_type:
                `{"metric": "L2"}`
                `{"metric": "IP"}`
                `{"metric": "HAMMING"}`
                `{"metric": "TANIMOTO"}`
            Note: "L2", "IP", "HAMMING", "TANIMOTO" are case insensitive

        :return: 2-d array distances
        :rtype: list[list[int]] for "HAMMING" or list[list[float]] for others
            Assume the vectors_left: L_1, L_2, L_3
            Assume the vectors_right: R_a, R_b
            Distance between L_n and R_m we called "D_n_m"
            The returned distances are arranged like this:
              [D_1_a, D_1_b, D_2_a, D_2_b, D_3_a, D_3_b]
"""

For example:
```
    op_l = {"float_vectors": [vec_1]}
    op_r = {"ids": [1, 2, ,3, 4], "collection": "users", "field": "user_profile"}
    params = {"metric": "L2", "sqrt": True}
    results = milvus.calc_distance(vectors_left=op_l, vectors_right=op_r, params=params)
```
Assume the "user_profile" is a vector field.
The results will be distance between vec_1 and "1", "2", "3", "4" vectors.

**Comment by xiaofan-luan** [comment]
@yan-rui sorry, please update your issue in English. This may help other people in the community

**Comment by yan-rui** [comment]
> We will provide a new api named "calc_distance()", #5443. Can this api meet your requirement?
> The definition of the new api:
> 
> ```
> def calc_distance(self, vectors_left, vectors_right, params=None, timeout=None, **kwargs):
> """
>         Calculate distance between two vector arrays.
> 
>         :param vectors_left: The vectors on the left of operator.
>         :type  vectors_left: dict
>         `{"ids": [1, 2, 3, .... n], "collection": "c_1", "partition": "p_1", "field": "v_1"}`
>         or
>         `{"float_vectors": [[1.0, 2.0], [3.0, 4.0], ... [9.0, 10.0]]}`
>         or
>         `{"bin_vectors": [b'\x94', b'N', ... b'\xca']}`
> 
>         :param vectors_right: The vectors on the right of operator.
>         :type  vectors_right: dict
>         `{"ids": [1, 2, 3, .... n], "collection": "col_1", "partition": "p_1", "field": "v_1"}`
>         or
>         `{"float_vectors": [[1.0, 2.0], [3.0, 4.0], ... [9.0, 10.0]]}`
>         or
>         `{"bin_vectors": [b'\x94', b'N', ... b'\xca']}`
> 
>         :param params: parameters, currently only support "metric_type", default value is "L2"
>                        extra parameter for "L2" distance: "sqrt", true or false, default is false
>                        extra parameter for "HAMMING" and "TANIMOTO": "dim", set this value if dimension is not a multiple of 8, otherwise the dimension will be calculted by list length
>         :type  params: dict
>             There are examples of supported metric_type:
>                 `{"metric": "L2"}`
>                 `{"metric": "IP"}`
>                 `{"metric": "HAMMING"}`
>                 `{"metric": "TANIMOTO"}`
>             Note: "L2", "IP", "HAMMING", "TANIMOTO" are case insensitive
> 
>         :return: 2-d array distances
>         :rtype: list[list[int]] for "HAMMING" or list[list[float]] for others
>             Assume the vectors_left: L_1, L_2, L_3
>             Assume the vectors_right: R_a, R_b
>             Distance between L_n and R_m we called "D_n_m"
>             The returned distances are arranged like this:
>               [D_1_a, D_1_b, D_2_a, D_2_b, D_3_a, D_3_b]
> """
> ```
> 
> For example:
> 
> ```
>     op_l = {"float_vectors": [vec_1]}
>     op_r = {"ids": [1, 2, ,3, 4], "collection": "users", "field": "user_profile"}
>     params = {"metric": "L2", "sqrt": True}
>     results = milvus.calc_distance(vectors_left=op_l, vectors_right=op_r, params=params)
> ```
> 
> Assume the "user_profile" is a vector field.
> The results will be distance between vec_1 and "1", "2", "3", "4" vectors. The results is not arranged by value, you need to sort the results and pick up tok.

That's great ! 
When the api will be release ?

**Comment by yhmo** [comment]
> > We will provide a new api named "calc_distance()", #5443. Can this api meet your requirement?
> > The definition of the new api:
> > ```
> > def calc_distance(self, vectors_left, vectors_right, params=None, timeout=None, **kwargs):
> > """
> >         Calculate distance between two vector arrays.
> > 
> >         :param vectors_left: The vectors on the left of operator.
> >         :type  vectors_left: dict
> >         `{"ids": [1, 2, 3, .... n], "collection": "c_1", "partition": "p_1", "field": "v_1"}`
> >         or
> >         `{"float_vectors": [[1.0, 2.0], [3.0, 4.0], ... [9.0, 10.0]]}`
> >         or
> >         `{"bin_vectors": [b'\x94', b'N', ... b'\xca']}`
> > 
> >         :param vectors_right: The vectors on the right of operator.
> >         :type  vectors_right: dict
> >         `{"ids": [1, 2, 3, .... n], "collection": "col_1", "partition": "p_1", "field": "v_1"}`
> >         or
> >         `{"float_vectors": [[1.0, 2.0], [3.0, 4.0], ... [9.0, 10.0]]}`
> >         or
> >         `{"bin_vectors": [b'\x94', b'N', ... b'\xca']}`
> > 
> >         :param params: parameters, currently only support "metric_type", default value is "L2"
> >                        extra parameter for "L2" distance: "sqrt", true or false, default is false
> >                        extra parameter for "HAMMING" and "TANIMOTO": "dim", set this value if dimension is not a multiple of 8, otherwise the dimension will be calculted by list length
> >         :type  params: dict
> >             There are examples of supported metric_type:
> >                 `{"metric": "L2"}`
> >                 `{"metric": "IP"}`
> >                 `{"metric": "HAMMING"}`
> >                 `{"metric": "TANIMOTO"}`
> >             Note: "L2", "IP", "HAMMING", "TANIMOTO" are case insensitive
> > 
> >         :return: 2-d array distances
> >         :rtype: list[list[int]] for "HAMMING" or list[list[float]] for others
> >             Assume the vectors_left: L_1, L_2, L_3
> >             Assume the vectors_right: R_a, R_b
> >             Distance between L_n and R_m we called "D_n_m"
> >             The returned distances are arranged like this:
> >               [D_1_a, D_1_b, D_2_a, D_2_b, D_3_a, D_3_b]
> > """
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For example:
> > ```
> >     op_l = {"float_vectors": [vec_1]}
> >     op_r = {"ids": [1, 2, ,3, 4], "collection": "users", "field": "user_profile"}
> >     params = {"metric": "L2", "sqrt": True}
> >     results = milvus.calc_distance(vectors_left=op_l, vectors_right=op_r, params=params)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Assume the "user_profile" is a vector field.
> > The results will be distance between vec_1 and "1", "2", "3", "4" vectors. The results is not arranged by value, you need to sort the results and pick up tok.
> 
> That's great !
> When the api will be release ?

It will be available in RC3, released in this week.

**Comment by yhmo** [comment]
Due to some technical issues, RC3 is delay for one week. We decide skip the RC3, and directly publish the RC4.

**Comment by yhmo** [comment]
The RC4 has been released, please try the new api in RC4.

**Comment by yhmo** [comment]
The new api calc_distance() allow user to pick vectors by id to calculate distance. So that user can do a workaround for "search in sub-set specified by given id array". Note: the api return distance is not arranged, user need to arrange it in client side.
