### ISSUE TITLE
[Doc] Add index desgin doc

### ISSUE THREAD

**Issue by xiaocai2333** [milvus-io/milvus#6919]
#### What would you like to be added:

Share index desgin for Milvus users.

#### Why is this needed:

Share index desgin for Milvus users.

**Comment by yhmo** [comment]
Please attach the design doc link here when it is done.

**Comment by xiaocai2333** [comment]
doc link: https://github.com/milvus-io/milvus/blob/master/docs/design_docs/index_design.md
