### ISSUE TITLE
Some thoughts about Milvus Roadmap

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#6951]
1. Community users put forward a lot of requirements on milvus, there needs to be a public place(such as milvus website, github) to see what requirements are currently available, which requirements have entered the roadmap, which have not entered. This should be dynamically updated;
2. For each requirement, regardless of size, it is best to be reflected in the roadmap, and it is best to give support plans and support time;
3. User requirements can be found at https://github.com/milvus-io/milvus/issues/6151;

**Comment by yhmo** [comment]
This is a public page to track milvus progress:
https://wiki.lfaidata.foundation/display/MIL/Milvus+2.0+Roadmap+and+Time+schedule

**Comment by yhmo** [comment]
I have updated the roadmap page. Use tables to records major features schedule/status/owner.

**Comment by xiaofan-luan** [comment]
Anyone is welcomed to add comments on the roadmap page or directly discuessed under git issues.
