### ISSUE TITLE
How to modify config file

### ISSUE THREAD

**Issue by yxz9087** [milvus-io/milvus#6967]
I used docker-compose to deploy milvus2.0，but I cannot find how to modify config files and restart service.
Please help，thanks

**Comment by jingkl** [comment]
Milvus 2.0 stand-alone version modified milvus.yaml
Therefore, we first modify the Milvus.yaml configuration file and then start it with docker-compose.
First, copy a Milvus.yaml file to the local link to the Milvus.yaml file:
https://github.com/milvus-io/milvus/blob/master/configs/milvus.yaml
After the copy is complete, modify the required configuration parameters in Milvus.yaml
After the change, you need to modify the docker-compose .yml file. The modified part of the file is as follows:
Need to map the path of the local modified configuration file  /data/workspace/*****/milvus.yaml to the file path of Milvus 2.0 milvus.yaml

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.0.0-rc2-20210712-a8e5fd2
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
      -  /data/workspace/*****/milvus.yaml:/milvus/configs/milvus.yaml
    ports:
      - "19530:19530"
    depends_on:
      - "etcd"
      - "minio"

Then use the docker-compose up -d command to start.

**Comment by yhmo** [comment]
Already resolved. Close it.
