### ISSUE TITLE
Import vector error (milvus2.0rc2)

### ISSUE THREAD

**Issue by ChenCongZhu2017** [milvus-io/milvus#6979]
#### Steps/Code to reproduce:
import random

from pymilvus_orm import (
    connections, FieldSchema, CollectionSchema, DataType,
    Collection, list_collections,
)

def hello_milvus():
    # create connection
    connections.add_connection(default={"host": "172.17.16.15", "port": "19530"})
    connections.connect(alias='default')

    print(f"\nList collections...")
    print(list_collections())

    # create collection
    dim = 128
    default_fields = [
        FieldSchema(name="count", dtype=DataType.INT64, is_primary=True),
        FieldSchema(name="random_value", dtype=DataType.DOUBLE),
        FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
    ]
    default_schema = CollectionSchema(fields=default_fields, description="test collection")

    print(f"\nCreate collection...")
    collection = Collection(name="milvus_test", schema=default_schema)

    print(f"\nList collections...")
    print(list_collections())

    #  insert data
    nb = 10
    vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
    collection.insert(
        [
            [i for i in range(nb)],
            [float(random.randrange(-20, -10)) for _ in range(nb)],
            vectors
        ]
    )

    print(f"\nGet collection entities...")
    print(collection.num_entities)

    # create index and load table
    default_index = {"index_type": "IVF_FLAT", "params": {"nlist": 128}, "metric_type": "L2"}
    print(f"\nCreate index...")
    collection.create_index(field_name="float_vector", index_params=default_index)
    print(f"\nload collection...")
    collection.load()

    # load and search
    topK = 5
    search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
    import time
    start_time = time.time()
    print(f"\nSearch...")
    # define output_fields of search result
    res = collection.search(
        vectors[-2:], "float_vector", search_params, topK,
        "count > 100", output_fields=["count", "random_value"]
    )
    end_time = time.time()

    # show result
    for hits in res:
        for hit in hits:
            # Get value of the random value field for search result
            print(hit, hit.entity.get("random_value"))
    print("search latency = %.4fs" % (end_time - start_time))

    # drop collection
    collection.drop()

hello_milvus();

#### Actual results:
List collections...
['zhucc_milvus_test', 'coll_milvus_test']

Create collection...

List collections...
['milvus_test', 'zhucc_milvus_test', 'coll_milvus_test']
Error: <BaseException: (code=1, message=GetSegmentID failed: SegmentIDAllocator failRemainRequest err:syncSegmentID Failed:rpc error: code = DeadlineExceeded desc = context deadline exceeded)>
Traceback (most recent call last):
  File "/Users/a2345/python_libs/lib/python3.8/site-packages/pymilvus/client/stub.py", line 63, in handler
    raise e
  File "/Users/a2345/python_libs/lib/python3.8/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/Users/a2345/python_libs/lib/python3.8/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/Users/a2345/python_libs/lib/python3.8/site-packages/pymilvus/client/stub.py", line 852, in insert
    return handler.bulk_insert(collection_name, entities, partition_name, timeout, **kwargs)
  File "/Users/a2345/python_libs/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
    raise e
  File "/Users/a2345/python_libs/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/Users/a2345/python_libs/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 539, in bulk_insert
    raise err
  File "/Users/a2345/python_libs/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 535, in bulk_insert
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=GetSegmentID failed: SegmentIDAllocator failRemainRequest err:syncSegmentID Failed:rpc error: code = DeadlineExceeded desc = context deadline exceeded)>

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): rc2
- Deployment mode(standalone or cluster): cluster (docker-compose)
- SDK version(e.g. pymilvus v2.0.0rc2):v2.0.0rc2
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others: 

#### Configuration file:
Default configuration

#### Additional context:

[milvus-proxy.log](https://github.com/milvus-io/milvus/files/6924554/milvus-proxy.log)
[milvus-indexcoord.log](https://github.com/milvus-io/milvus/files/6924555/milvus-indexcoord.log)
[milvus-datanode.log](https://github.com/milvus-io/milvus/files/6924559/milvus-datanode.log)
[milvus-pulsar.log](https://github.com/milvus-io/milvus/files/6924563/milvus-pulsar.log)

**Comment by czs007** [comment]
@ChenCongZhu2017  
Thank you for your feedback. We will check this bug as soon as possible. rc3  version will be released this week.

**Comment by ChenCongZhu2017** [comment]
#

**Comment by yhmo** [comment]
The RC4 has been released on Aug 13. Please use the new version to try again.

**Comment by ChenCongZhu2017** [comment]
> The RC4 has been released on Aug 13. Please use the new version to try again.
OK,Thank you
