### ISSUE TITLE
Milvus does not respond when accessing num_entities or performing an insert operation

### ISSUE THREAD

**Issue by arthuo** [milvus-io/milvus#6981]
#### Steps/Code to reproduce:
connections.connect("default", host='127.0.0.1', port='19530')
print(connections.list_connections())

collection_name = "faceSearch"

face_id = FieldSchema(name="face_id", dtype=DataType.INT64, is_primary=True)
face_feature = FieldSchema(name="face_feature", dtype=DataType.FLOAT_VECTOR, dim=1024)
schema = CollectionSchema(fields=[face_id, face_feature], description="face search")
collection = Collection(name=collection_name, schema=schema)
   
print(collection.num_entities)
nb = 10
vectors = [[random.random() for _ in range(1024)] for _ in range(nb)]

collection.insert([[i for i in range(nb)], vectors])
print(collection.num_entities)
connections.disconnect("default")

#### Expected result:
[('default', <pymilvus.client.stub.Milvus object at 0xxxxxxx>)]
0
10

#### Actual results:
[('default', <pymilvus.client.stub.Milvus object at 0xxxxxxx>)]
When my code runs to collection.num_entities, the Milvus service will wait indefinitely, but sometimes it can successfully output 0 and wait on the insert operation.In addition, the sample code was tested a few days ago and everything was executed normally.

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): v2.0.0-rc2
- Deployment mode(standalone or cluster): standalone (Start by docker-compose)
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.0.0rc2
- OS(Ubuntu or CentOS): Ubuntu 18.04 LTS
- CPU/Memory: Intel(R) Core(TM) i7-8700 CPU cores * 12, Memory 16GB
- GPU: NVIDIA 3080
- Others: use cpu version

#### Configuration file:
Default configuration

#### Additional context:
[milvus-standalone.log](https://github.com/milvus-io/milvus/files/6927873/milvus-standalone.log)
[milvus-minio.log](https://github.com/milvus-io/milvus/files/6927878/milvus-minio.log)
[milvus-etcd.log](https://github.com/milvus-io/milvus/files/6927879/milvus-etcd.log)

**Comment by yanliang567** [comment]
this could be an occasional stability issue which is going to be fixed in rc3

**Comment by arthuo** [comment]
> this could be an occasional stability issue which is going to be fixed in rc3
Thank you, is the rc3 version released this week?

**Comment by arthuo** [comment]
For me, when the Milvus service did not respond, I tried to delete the mirror and pull again, but it was unsuccessful. Then, I deleted the Milvus data, located in /home/$USER/volumes, and the Milvus service returned to normal. What's wrong with this, I don’t know yet, but it works very well.
