### ISSUE TITLE
Milvus is restarted when inserting 3 million entities

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#6986]
#### Steps/Code to reproduce:
```python
    def test_milvus_default(self):
        from utils.util_log import test_log as log
        # create
        name = cf.gen_unique_str(prefix)
        t0 = datetime.datetime.now()
        collection_w = self.init_collection_wrap(name=name)
        tt = datetime.datetime.now() - t0
        log.debug(f"assert create: {tt}")
        assert collection_w.name == name

        # insert
        nb = 3000000
        data = cf.gen_default_list_data(nb)
        log.info("inserting")
        t0 = datetime.datetime.now()
        _, res = collection_w.insert(data)
        tt = datetime.datetime.now() - t0
        log.info("inserted successfully")
        log.debug(f"assert insert: {tt}")
        assert res

        # flush
        t0 = datetime.datetime.now()
        log.info("flushing")
        num = collection_w.num_entities
        log.info("flushed")
        log.info(num)
        assert num == len(data[0])
        tt = datetime.datetime.now() - t0
        log.debug(f"assert flush: {tt}")

```

Logs:
[logs_6986.tar.zip](https://github.com/milvus-io/milvus/files/6928410/logs_6986.tar.zip)

#### Expected result:
Inserted sucessfully

#### Actual results:
Milvus is restarted

#### Environment:
- Milvus version(): 07cc449
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
Name: pymilvus
Version: 2.0.0rc3.dev16
Name: pymilvus-orm
Version: 2.0.0rc3.dev15

- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by binbinlv** [comment]
Standalone: 
the service is still online after pods restarted.

**Comment by yanliang567** [comment]
3M entities(saying 128d) could be 1.5GB, which exceeds the max data size of rpc in miluvs (512M), but crashing is not acceptable indeed.

**Comment by xiaofan-luan** [comment]
@czs007 please add a limit that milvus can not accept insert batch size more than 1m.  each system has to have limit

**Comment by czs007** [comment]
> 3M entities(saying 128d) could be 1.5GB, which exceeds the max data size of rpc in miluvs (512M), but crashing is not acceptable indeed.

@yanliang567  @binbinlv 
Checked the log, it was failed before insert was started. Prompt that rootCoord cannot be connected.

**Comment by yanliang567** [comment]
close, as we successfully inserted 100million entities on rc7
