### ISSUE TITLE
Searched numbers is larger than inserted entities

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#6994]
#### Steps/Code to reproduce:
Run test case:
/milvus/tests20/python_client/testcases/test_search.py::TestCollectionSearch::test_search_new_data

Logs:
[log_6994.tar.zip](https://github.com/milvus-io/milvus/files/6929117/log_6994.tar.zip)

#### Expected result:
searched numbers is equal with nb when limit > nb

#### Actual results:
[2021-08-04 06:29:04 - ERROR - ci_test]: search_results_check: limit(topK) searched (1000) is not equal with expected (800) (func_check.py:191)

test_search.py::TestCollectionSearch::test_search_new_data[2-8-False-False] PASSED                                                                                                                   [  6%]
test_search.py::TestCollectionSearch::test_search_new_data[2-8-False-True] FAILED                                                                                                                    [ 12%]

#### Environment:
- Milvus version():ad77a6e
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
Name: pymilvus
Version: 2.0.0rc3.dev16
Name: pymilvus-orm
Version: 2.0.0rc3.dev15

- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by DragonDriver** [comment]
I will fix this soon.

**Comment by xiaofan-luan** [comment]
duplicate with #7001, close it
