### ISSUE TITLE
Code error in API documentation

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#7000]
https://milvus.io/api-reference/pymilvus-orm/v2.0.0rc2/api/utility.html
![new](https://user-images.githubusercontent.com/34296482/128148909-581f389a-712d-4210-8a36-efeb6390cc53.png)
schema = CollectionSchema(fields=[field_int64, field_vector], description="get collection entities num")
The line of code in the official website should look like this, as shown below：
![new2](https://user-images.githubusercontent.com/34296482/128149006-804a0f9f-d366-4fca-b081-b10ad2afb4b7.png)

**Comment by jingkl** [comment]
https://milvus.io/cn/api-reference/pymilvus-orm/v2.0.0rc2/api/partition.html
![02](https://user-images.githubusercontent.com/34296482/128162197-01d9f5a6-51d1-4c9b-84ff-93ed82c044d9.png)
There is an error in the way partitions are created on the official website
![test02](https://user-images.githubusercontent.com/34296482/128162077-673d8897-b69d-4505-b769-015accba47bf.png)

**Comment by yhmo** [comment]
Already fixed.
