### ISSUE TITLE
Creating collection hangs when system running for some time (run test cases)

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#7006]
#### Steps/Code to reproduce:
After running some test cases, create cllection hungs:

```python
from pymilvus_orm import CollectionSchema, FieldSchema
from pymilvus_orm import Collection
from pymilvus_orm import connections
from pymilvus_orm.types import DataType
dim = 128
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
connections.connect()
import numpy as np
collection = Collection("test_search_collection_binbin_6", schema=schema)
```

#### Expected result:
command hangs without return

#### Actual results:
No hangs

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): latest
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
Name: pymilvus
Version: 2.0.0rc3.dev16
Name: pymilvus-orm
Version: 2.0.0rc3.dev15

- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by binbinlv** [comment]
Logs could not be pasted here for the size, please ping me to get the logs, thanks.

**Comment by DragonDriver** [comment]
No response from etcd. So HasCollection hung.

**Comment by abodyy4272** [comment]
https://hostpubg.com

**Comment by DragonDriver** [comment]
We are debugging on why etcd don't response, it will take a while.

**Comment by DragonDriver** [comment]
We have already updated the deploy policy of milvus helm, it may avoid this issue. Can you retry this using the newer milvus helm version?
/assign @binbinlv

**Comment by binbinlv** [comment]
@DragonDriver 

I have retried this last week, and it is indeed not exist now. But it seems that the root cause has not been found? It is just be bypassed. So I did not close it.

**Comment by abodyy4272** [comment]
https://github.com/milvus-io/milvus/commit/dd0d2659bb92cace3477ea77e7834f93425dcd22

**Comment by DragonDriver** [comment]
Yeah, we didn't find why etcd do not response yet.

**Comment by binbinlv** [comment]
Similar issue occurs when running nightly CI, so pasted here if it is the same root cause and could be a help.

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/118/artifacts
distributed version: 
artifacts-milvus-distributed-master-118-e2e-nightly-logs.tar.gz

[2021-08-27T19:59:42.637Z] testcases/test_search_20.py::TestCollectionSearch::test_search_with_output_fields[5000-500-8-True-False] timeout: sending signal TERM to command '/home/jenkins/agent/workspace/tests/scripts/e2e.sh'

It hangs at test case: test_search_with_output_fields until the timeout of whole nightly tests.

And hangs at step "create creation".

```
[2021-08-27 15:48:07,713 - INFO - ci_test]: [setup_method] Start setup test case test_search_with_output_fields. (client_base.py:51)
[2021-08-27 15:48:07,740 - INFO - ci_test]: Test case of search interface: initialize before test case (client_base.py:147)
[2021-08-27 15:48:08,762 - INFO - ci_test]: init_collection_general: collection creation (client_base.py:159
```

**Comment by godchen0212** [comment]
According to the log, I cannot find the log about the proxy receiving this create collection. 
It may be because the request was not received, or it was stuck in the process of enlisting. 
I will modify the existing log to make sure the cause of the problem.

**Comment by binbinlv** [comment]
From RC6, could not reproduce it in the recent tests, so close it first and will reopen it when it occurs again.
