### ISSUE TITLE
Can't start Milvus

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#701]
**What is your question?**
When I start Milvus according to the official website. I get the following error message.

Welcome to use Milvus by Zilliz!
Milvus release version: v0.4.0 built at 2019-09-29 10:00.01
Loading configuration from: ../conf/server_config.yaml
Initial log config from: ../conf/log_config.conf
ERROR: db_path is empty
2019-12-04 09:40:48,185 ERROR [default] [SERVER] Wrong URI format: URI = 
ERROR: invalid db_backend_url: 
ERROR: invalid resource config: resources empty
/opt/docker-entrypoint.sh: line 9: exec: start: not found

**Comment by JinHai-CN** [comment]
Obviously, there is wrong in server_config.yaml, please provide server_config.yaml.

**Comment by JackLCL** [comment]
I used the old milvus version. It can be solved by pulling latest image.
