### ISSUE TITLE
ERROR: The Compose file './docker-compose.yml' is invalid 

### ISSUE THREAD

**Issue by hande6688** [milvus-io/milvus#7019]
按照官方安装：https://milvus.io/cn/docs/v2.0.0/install_standalone-docker.md
执行：docker-compose up -d
报错：
ERROR: The Compose file './docker-compose.yml' is invalid because:
networks.default value Additional properties are not allowed ('name' was unexpected)

**Comment by yhmo** [comment]
Duplicated with #7020, close this.
