### ISSUE TITLE
ERROR: The Compose file './docker-compose.yml' is invalid

### ISSUE THREAD

**Issue by hande6688** [milvus-io/milvus#7020]
按照官方安装：https://milvus.io/cn/docs/v2.0.0/install_standalone-docker.md
执行：docker-compose up -d
报错：
ERROR: The Compose file './docker-compose.yml' is invalid because:
networks.default value Additional properties are not allowed ('name' was unexpected)

**Comment by yhmo** [comment]
@hande6688 
What is your operation system? Mac OS or other linux(ubuntu,centos)?

**Comment by hande6688** [comment]
@yhmo linux系统

**Comment by yhmo** [comment]
@jeffoverflow Please take a look this issue.

**Comment by jeffoverflow** [comment]
What is the version of Docker and Docker Compose?  @hande6688
