### ISSUE TITLE
Test case "test_insert_binary_multi_times" failed for server is not serving

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#7027]
#### Steps/Code to reproduce:
Run nightly test cases:
milvus/tests/python_test/entity/test_insert.py::TestInsertBinary::test_insert_binary_multi_times 

Logs:
[artifacts-milvus-distributed-master-93-e2e-nightly-logs.tar.gz](https://github.com/milvus-io/milvus/files/6959113/artifacts-milvus-distributed-master-93-e2e-nightly-logs.tar.gz)

#### Expected result:
Test cases run successfully

#### Actual results:
FAILED entity/test_insert.py::TestInsertBinary::test_insert_binary_multi_times 
E                   Failed: Timeout >360.0s

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): latest
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
pymilvus-orm==2.0.0rc3.dev15
pymilvus==2.0.0rc3.dev16
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by sunby** [comment]
Insert requests are not received by server.

**Comment by binbinlv** [comment]
Run "test_insert_binary_multi_times" case for 100 times in local env, no errors. 

And I will close it tomorrow morning if no same error occurs again in today's nightly cases.

**Comment by timshen** [comment]
@binbinlv   any update?

**Comment by binbinlv** [comment]
Could not reproduce now, close it. Will reopen it if it occurs in the future.
