### ISSUE TITLE
Milvus takes a particularly long time to build indexes

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#7029]
Only 10 vectors were inserted into the collection to build the index and it took a long time to complete

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):v2.0.0-RC2
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.0.0rc2
- OS(Ubuntu or CentOS): (Ubuntu
- CPU/Memory: 

![create](https://user-images.githubusercontent.com/34296482/128817617-2a1c29e1-8fb3-4c7c-8bb0-faccdcc4bc63.png)
[create_index.zip](https://github.com/milvus-io/milvus/files/6959383/create_index.zip)

**Comment by xige-16** [comment]
It seems that the flush process is not completed. Has the problem been fixed? @sunby

**Comment by xige-16** [comment]
The issue has been fix. If you're in a hurry, you can use the lastest image first. @jingkl

**Comment by yhmo** [comment]
@jingkl Please verify this issue on RC4.
