### ISSUE TITLE
Should rocksmq support inactive topic retention?

### ISSUE THREAD

**Issue by fishpenguin** [milvus-io/milvus#7037]
#### Why is this needed:
Currently milvus operations will create many topics in msgstream, but rarely call deleteTopics because pulsar supports inactive topics retention and delete automatically. Rocksmq doesn't support topic retention and auto-delete which causes that there are so many topics remain in rocksmq and greatly impact on milvus performance.
So Should rocksmq support topic retention or just delete topic manually in msgstream?

**Comment by xiaofan-luan** [comment]
I guess we do need this delete topic api but this should be called by drop collection immediately,.
Similar to S3 log snapshots, we need to maintain old topics for a couple of days before we cleanup
