### ISSUE TITLE
Data is incomplete in collection after insert is done

### ISSUE THREAD

**Issue by jaelgu** [milvus-io/milvus#7039]
#### Steps/Code to reproduce:
1. Install & start Milvus 2.0-RC2 Cluster with docker
2. Use benchmark (sift1m) in bootcamp to create collection & insert data
3. Check row count

#### Expected result:
row count should be 1m

#### Actual results:
row count: 993432 after insert is done without error

```
binary_128d_00000.npy insert rows 100000  insert milvus time:  7.904932975769043
binary_128d_00001.npy insert rows 100000  insert milvus time:  6.682743072509766
binary_128d_00002.npy insert rows 100000  insert milvus time:  6.480204820632935
binary_128d_00003.npy insert rows 100000  insert milvus time:  6.827396869659424
binary_128d_00004.npy insert rows 100000  insert milvus time:  7.229616165161133
binary_128d_00005.npy insert rows 100000  insert milvus time:  6.531720876693726
binary_128d_00006.npy insert rows 100000  insert milvus time:  6.616898059844971
binary_128d_00007.npy insert rows 100000  insert milvus time:  6.970038890838623
binary_128d_00008.npy insert rows 100000  insert milvus time:  6.859661102294922
binary_128d_00009.npy insert rows 100000  insert milvus time:  6.608635187149048
total insert time:  68.7118308544159
```

* recall accuracy is very low (<10%) --> So I think data is not completely inserted, not the bug of incorrect row count by num_entities
* if drop collection and create & insert again, then data is complete & (row count: 1m) and recall accuracy is ~99%
* if restart containers, pulsar exits soon after it starts; has to delete volumes for successful up

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): v2.0.0-RC2
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-orm==2.0.0rc2
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: NO
- Others: 

#### Additional context:

[logs.txt](https://github.com/milvus-io/milvus/files/6961361/logs.txt)

**Comment by jaelgu** [comment]
Standalone is ok. All 10m data is inserted.

**Comment by xige-16** [comment]
Is your sdk pymilvus or pymilvus-orm?

**Comment by jaelgu** [comment]
pymilvus-orm
