### ISSUE TITLE
When I start milvus , I find nothing in db directory.

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#704]
When I start Milvus according to the official website(https://milvus.io/docs/zh-CN/userguide/install_milvus/).  I find nothing in db directory.

**Comment by jielinxu** [comment]
Try to keep the primary path in the `docker run` command consistent with the path you set in server_config.yaml. You can choose your own path depending on your docker priviledges.

**Comment by jielinxu** [comment]
For Milvus v0.6.0, the default primary path will be changed to `var/lib/milvus`. For older versions, the default is `opt/milvus`.

**Comment by JackLCL** [comment]
OK, I get it. And you'd better add it on the  website.

**Comment by RAHULMI49** [comment]
Hi, I am haivng the same issue, How to give the primary path while executing the docker run command?
