### ISSUE TITLE
Memory consumed totally 3-4 times as data size 

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#7056]
#### Steps/Code to reproduce:
in tests20/python_client: run pytest test_e2e.py --host x.x.x.x after updating nb=100,000 
or
1. deploy Milvus 2.0 cluster 
    1.1 after deployment, Milvus consumes about 380MB memory totally.
2. insert 100,000 entities (about 50MB) into a collection
3. flush
4. load
5. search
6. make a sq8 index
7. query

#### Expected result:
memory consumed smoothly

#### Actual results:
total memory consumed from 380MB to 1480MB and keeps at 750MB after step#7, looking into different pods:
querynode: 50MB to 222MB, and keeps at 200MB after step#7
datanode: 50MB to 470MB, and keeps 152MB after step#7
Indexnode: 50M to 286MB, and keeps at 150MB after step#7
proxy: 60M to 336MB, and keeps at 75MB after step#7 (I think 75MB is acceptable after step#7)

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):  master-20210810-bdb8396
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
pymilvus                           2.0.0rc3.dev16
pymilvus-orm                   2.0.0rc3.dev15

#### Additional context:
after deployment with no workload:
![Screen Shot 2021-08-11 at 2 16 53 PM](https://user-images.githubusercontent.com/82361606/129021021-a46ce867-1307-44c5-b038-bd8f226a64e6.png)
when there is workload
![Screen Shot 2021-08-11 at 2 17 43 PM](https://user-images.githubusercontent.com/82361606/129021052-ceacb3b3-8dbe-42c0-801e-3db78415a547.png)
after step#7
![Screen Shot 2021-08-11 at 2 18 33 PM](https://user-images.githubusercontent.com/82361606/129021098-07d635c8-583d-4268-a233-4de5718bcead.png)

**Comment by yanliang567** [comment]
there is a similar issue which focuses on querynode, #6745

**Comment by congqixia** [comment]
Currently invoking cgo functionality must do `data copy`, which means same data occupies twice memory in both golang and cpp side.
And decoding message and row-column conversion consumes same amount of memory as well.
That's the two main reasons cause 3~4 times memory consumption.
Maybe we should have some solution for this case.
@xige-16

**Comment by xige-16** [comment]
> Currently invoking cgo functionality must do `data copy`, which means same data occupies twice memory in both golang and cpp side.
> And decoding message and row-column conversion consumes same amount of memory as well.
> That's the two main reasons cause 3~4 times memory consumption.
> Maybe we should have some solution for this case.
> @xige-16

Changing the format of the internal data to arrow will solves the problem of copying the data between cgo and golang.

**Comment by xiaofan-luan** [comment]
assign @cydrain

**Comment by xiaofan-luan** [comment]
why are we copying the data? from design perspective,  data should not be resident in go?

**Comment by congqixia** [comment]
> why are we copying the data? from design perspective, data should not be resident in go?

By `copying the data`, do you mean copying the data from `go` managed memory to `c` managed memory? If that's the case, this behavior is the designed behavior of cgo. The reason is that it's unsafe to allow `c/cpp` to operate memory from go runtime. Say if the memory is cleaned up by gc when `c/cpp` tried to operate it.

**Comment by xige-16** [comment]
I will check if there is a memory leak
