### ISSUE TITLE
Distance is calculated wrong for binary vector using TANIMOTO metric

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#7064]
#### Steps/Code to reproduce:
```python
from pymilvus_orm import connections
from pymilvus_orm import utility
import random
connections.connect()
vectors_l = [b'\xc0']
vectors_r = [b'\x00']
op_l = {"bin_vectors": vectors_l}
op_r = {"bin_vectors": vectors_r}
params = {"metric": "TANIMOTO"}
results = utility.calc_distance(op_l, op_r, params)
```
#### Expected result:
for 
b'\xc0':  1100 0000
b'\x00': 0000 0000

TANIMOTO distance should be: length of the same part:
6 / (8+8-6)

#### Actual results:
Now the distance is: 2 / (8 + 8 -2)
```
results
[[0.1428571492433548]]
```

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): 7fc7623
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
Name: pymilvus
Version: 2.0.0rc3.dev16
Name: pymilvus-orm
Version: 2.0.0rc3.dev15

- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by yhmo** [comment]
@binbinlv The pr #7140 has been merged, please verify it on the next build

**Comment by binbinlv** [comment]
@yhmo  OK.

**Comment by binbinlv** [comment]
Verified and fixed.

milvus: (master: 09525f5)
results
```
[[0.6000000238418579]]
```
