### ISSUE TITLE
Distance is inf when searching binary vector using tanimoto metric (dim = 8)

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#7078]
#### Steps/Code to reproduce:
Run test cases:
testcases/test_search.py::TestCollectionSearch.test_search_binary_tanimoto_flat_index

#### Expected result:
Search return with right results

#### Actual results:
search with wrong results

nightly:
https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/96/consoleFull

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): 
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by DragonDriver** [comment]
Duplicated with #6843
