### ISSUE TITLE
Search stucked if querynode only load sealed segment, without watch inser channels

### ISSUE THREAD

**Issue by xige-16** [milvus-io/milvus#7081]
#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by xige-16** [comment]
If querynode hasn't watch any dmChannels, the local clock of querynode will not be pushed forward, causing the search to time out.

**Comment by xige-16** [comment]
The solution is to query the historical data of querynode directly without waiting for the local clock.

**Comment by xiaofan-luan** [comment]
> The solution is to query the historical data of querynode directly without waiting for the local clock.

Be awere this may change if delete channel is added.

**Comment by xige-16** [comment]
same with #6417
