### ISSUE TITLE
Offline install: failed to download "milvus/milvus" (hint: running `helm repo update` may help)

### ISSUE THREAD

**Issue by jaelgu** [milvus-io/milvus#7082]
#### Steps/Code to reproduce:
1. Follow https://github.com/milvus-io/milvus/tree/master/deployments/offline with minikube
2. Step "Get Kubernetes manifest of Milvus standalone"
#### Expected result:
Be able to download milvus_manifest.yaml

#### Actual results:
- Fail with error "failed to download "milvus/milvus" (hint: running `helm repo update` may help)"
- I have to online install release before this step, then I can run this step to get milvus_manifest.yaml

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by jaelgu** [comment]
it was failed to connect https://milvus-io.github.io/milvus-helm/. Now fixed.

**Comment by jeffoverflow** [comment]
Need to make sure you can properly access [https://milvus-io.github.io/milvus-helm/index.yaml](https://milvus-io.github.io/milvus-helm/index.yaml ) 

Enter the following command to verify that the link is accessible
```shell
curl -s --head https://milvus-io.github.io/milvus-helm/index.yaml | head -n 1
```
