### ISSUE TITLE
Segment can not auto flush

### ISSUE THREAD

**Issue by sunby** [milvus-io/milvus#7084]
After receiving datanode timetick, datacoord checks the flushable segments, if no segment is chosen, the expiration check logic will not be executed. This leads to that allocations of segment can not be released. We should expire allocations first.

**Comment by xiaofan-luan** [comment]
We may want to release rc5 as soon as possible to fix this issue. it is critical.
@yanliang567

**Comment by yanliang567** [comment]
> We may want to release rc5 as soon as possible to fix this issue. it is urgent.
> @yanliang567
we can plan that

**Comment by sunby** [comment]
I am working on it but I found a weird case. I run unit tests on my machine many times and it will stuck by chance. I found that pulsar consumer can not get a message from msgstream. I can reproduce it stably but don't know why for now. I will open another issue to report it and assign to me or @xige-16 . Maybe we can fix this issue first.

**Comment by czs007** [comment]
> I am working on it but I found a weird case. I run unit tests on my machine many times and it will stuck by chance. I found that pulsar consumer can not get a message from msgstream. I can reproduce it stably but don't know why for now. I will open another issue to report it and assign it to me or @xige-16 . Maybe we can fix this issue first.

please link your another issue to this issue
