### ISSUE TITLE
How to modify cache_size in Milvus2.0

### ISSUE THREAD

**Issue by yxz9087** [milvus-io/milvus#7089]
I have a  dataset  almost 20GB and 5,000,000 rows.When I tried to load partition from disk to memory,it stucked，finally grpc timeout error throwed.
I want to change cache_size config to have a try，but cannot find how to modify config file，please help~

**Comment by xiaofan-luan** [comment]
Milvus 2.0 does not support cache_size yet since it is too slow for most people. We are working on next generation disk Ann algorithm and might be ready by the end of this year.

So far you can try to use PQ or SQ8 to reduce memory usage or try to expand memory, does that make sense to you?

**Comment by yxz9087** [comment]
> Milvus 2.0 does not support cache_size yet since it is too slow for most people. We are working on next generation disk Ann algorithm and might be ready by the end of this year.
> 
> So far you can try to use PQ or SQ8 to reduce memory usage or try to expand memory, does that make sense to you?
So the memory is not limited in Milvus 2.0?
I used SQ8 to build index,but it stucked when load partition from disk to memory.

**Comment by xiaofan-luan** [comment]
can you share logs for both proxy, query coord and query node? So we can have a investigation on that
