### ISSUE TITLE
documentation inconsistent with the current release.

### ISSUE THREAD

**Issue by ss892714028** [milvus-io/milvus#7095]
### location
https://milvus.io/docs/v2.0.0/limitations.md#Milvus-limitations

### issue
Limitations on search params
TopK in rc2 should be size < 5mb. Is the listed 16384 for future releases?

**Comment by xiaofan-luan** [comment]
16384 is not a hard limitation, most of the limitations listed are suggestions. You may break the rule or change the parameter in the system but this may cause stability issues.

**Comment by LocoRichard** [comment]
Introduced clarification on the limitation page.  the issue can be closed.
@ss892714028

**Comment by ss892714028** [comment]
> Introduced clarification on the limitation page. the issue can be closed.
> @ss892714028

Looks good, closing this issue.
Thanks.
