### ISSUE TITLE
Build fail with error assignment mismatch

### ISSUE THREAD

**Issue by BUPTAnderson** [milvus-io/milvus#7098]
#### Steps/Code to reproduce:
build **master** branch

#### Expected result:
build pass

#### Actual results:
<code>
# github.com/milvus-io/milvus/internal/datanode
internal/datanode/data_node.go:327:17: assignment mismatch: 1 variable but etcdkv.NewEtcdKV returns 2 values
internal/datanode/data_node.go:327:35: cannot use etcdClient (type *clientv3.Client) as type []string in argument to etcdkv.NewEtcdKV
make: *** [milvus] Error 2
</code>

#### Environment:
- Milvus version : master branch

**Comment by congqixia** [comment]
Thanks for the reply! This is a known issue(#7080) and fixed in this PR #7083. Please get the latest version or use the more stable rc4 branch.
