### ISSUE TITLE
Need a robot to automatically update kind/bug issues

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#7103]
We need a robot to automatically update the github kind/bug issues:
1. add comments if no more comments in 15 days
2. close the issue if no more comments in 20 days

details in https://zilliverse.feishu.cn/docs/doccn9CLVtnvTSQKYoU6Qdyarle#

**Comment by xiaofan-luan** [comment]
agree, we have many left behind issues. We should probably pull the unhandled issues and timeout issues to our slack channel and let the triage council working on it.

**Comment by yanliang567** [comment]
verify and close
