### ISSUE TITLE
When the allocated memory space is smaller than the data size, more memory is not better .

### ISSUE THREAD

**Issue by shatealaboxiaowang** [milvus-io/milvus#7108]
#### Additional context:

When the allocated memory space is smaller than the data size, more memory is not better .
exp: data_size=20g, search_speed(cache_size=19g)=search_speed(cache_size=1G)

code:
myMilvus.set_config('cache', 'cache_size', '1GB')
top_k = int(confs_milvus.get('topk'))
q_records = [[random.random() for _ in range(dim)] for _ in range(1)]
for i in range(5):
start_time = time.time()
results = myMilvus.search(collection_name_create, top_k, q_records)
logging.info('Search running time: %s' % str(time.time() - start_time))

**Comment by xiaofan-luan** [comment]
any data to share? by saying not better what is the performance number?

**Comment by yhmo** [comment]
This is a known issue of 1.x. We have an issue #2123 for this requirement.
Duplicated and close this one.
