### ISSUE TITLE
Add some tests for  'Extend grammar of boolean expression #5210' 

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#7110]
#### What would you like to be added:
add some tests for  Extend grammar of boolean expression #5210 

#### Why is this needed:
currently the expression of search is not covered for #5210

**Comment by binbinlv** [comment]
@zhuwenxing  could you please help to add cases covering the extend grammar of expression.

And one suggestion:
please investigate the following questions first, then could add comments here, after discuss and confirmation, then you could start to develop the specific test cases.
(1) what kinds of test cases needed to be added according to #5210
(2) where to add in the test cases file
