### ISSUE TITLE
Inconsistent Milvus 2.0 rc version between milvus.io and Milvus github repo

### ISSUE THREAD

**Issue by ss892714028** [milvus-io/milvus#7111]
Milvus 2.0 rc4 is out according to hello_milvus, (https://milvus.io/docs/v2.0.0/example_code.md)
Quick install with docker-compose points to a ~~master branch's~~ rc2 docker-compose.yml file. (https://milvus.io/docs/v2.0.0/install_standalone-docker.md)
~~However, master branch's docker-compose.yml version is still rc2~~ (https://raw.githubusercontent.com/milvus-io/milvus/fd84cf7c55fb63e66a066052897b1bd6d6e73830/deployments/docker/standalone/docker-compose.yml)

**Comment by yanliang567** [comment]
the master branch's docker-compose.yml seems to good to me. so i think we need to update the link in quick install

**Comment by LocoRichard** [comment]
issue fixed, can be closed

**Comment by yanliang567** [comment]
@ss892714028  we have fixed the issue, please help to check and close it.

**Comment by ss892714028** [comment]
It is fixed in the chinese page, however the yml file on the English page is still rc2. https://milvus.io/docs/install_standalone-docker.md
https://raw.githubusercontent.com/milvus-io/milvus/fd84cf7c55fb63e66a066052897b1bd6d6e73830/deployments/docker/standalone/docker-compose.yml

**Comment by yanliang567** [comment]
@LocoRichard could you please try to fix the enu page as well?

**Comment by LocoRichard** [comment]
@yanliang567 all fixed, can be closed.

**Comment by ss892714028** [comment]
Thank you, all fixed. closing this issue :)
