### ISSUE TITLE
Insert error:  Deadline Exceeded and there're 100,000 more vectors in the system

### ISSUE THREAD

**Issue by Bennu-Li** [milvus-io/milvus#7117]
#### Steps/Code to reproduce:
I repeatedly inserted 100,000 128-dimensional vectors. During the insertion process, the following problems sometimes occur:
![image](https://user-images.githubusercontent.com/53458891/129536219-a6a434a1-2a1c-4b5e-8a28-83bbf37124e3.png)

After this problem occurs, there will be 100,000 more vectors in the collection. For example, I inserted ten times, each time I inserted 100,000 vectors, and the above problem occurred once during the insertion process. In the end, there will be 1.1 million vectors in the collection.

#### Environment:
- Milvus version(ev2.0.0-RC4）
- Deployment mode(cluster):
- SDK version(pymilvus-orm v2.0.0rc4):

**Comment by yanliang567** [comment]
seems like insert timeout. @czs007 please take a look.

**Comment by Bennu-Li** [comment]
> seems like insert timeout. @czs007 please take a look.

But why does the number of entities increase?

**Comment by XuanYang-cn** [comment]
I'm working on it now
/unassign @czs007

**Comment by XuanYang-cn** [comment]
Do you have logs or ways to reproduce this issue @Bennu-Li ?

I've tried to insert 100_000 vectors 30 times (totally 3_000_000) and the system works fine.

**Comment by XuanYang-cn** [comment]
I've tried many times locally, the system works fine.

milvus: 2.0.0RC4
pymilvus-orm 2.0.0rc4

**Comment by XuanYang-cn** [comment]
Closing for not reproducible.
