### ISSUE TITLE
Milvus is unusually slow when inserting and searching operations

### ISSUE THREAD

**Issue by arthuo** [milvus-io/milvus#7120]
#### Steps/Code to reproduce:
``` python
from pymilvus_orm import connections
from pymilvus_orm import Collection, CollectionSchema, FieldSchema, DataType
import pymilvus_orm
import random
import time


def insertVec2Milvus(vectors, ids):
    connections.connect('default', host='127.0.0.1', port='19530')

    collection_name = "example"
    if pymilvus_orm.utility.get_connection().has_collection(collection_name):
        collection = Collection(name=collection_name)
    else:
        face_id = FieldSchema(name="face_id", dtype=DataType.INT64, is_primary=True)
        face_feature = FieldSchema(name="face_feature", dtype=DataType.FLOAT_VECTOR, dim=1024)
        schema = CollectionSchema(fields=[face_id, face_feature], description="example")
        collection = Collection(name=collection_name, schema=schema)

    collection.insert([ids, vectors])

    index_param = {
        "metric_type": "L2",
        "index_type": "IVF_FLAT",
        "params": {"nlist": 1024}
    }
    collection.create_index(field_name="face_feature", index_params=index_param)

    pymilvus_orm.utility.get_connection().flush([collection_name])
    connections.disconnect("default")


def searchVecInMilvus(vector):
    connections.connect('default', host='127.0.0.1', port='19530')
    collection_name = "example"
    collection = Collection(name=collection_name)
    # create search params
    search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
    # load collection into memory
    collection.load()
    vectors = [vector]
    results = collection.search(vectors, "face_feature", param=search_params, limit=10, expr=None)
    for raw_result in results:
        for result in raw_result:
            print(f"id = {result.id}, distance = {result.distance}")
    collection.release()
    connections.disconnect("default")


if __name__ == '__main__':
    start_time = time.time()
    nb = 10000
    dim = 1024
    vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
    ids = [i for i in range(nb)]
    insertVec2Milvus(vectors, ids)
    m_time = time.time()
    print("cost {:.2f}ms".format(1000 * (m_time - start_time)))

    data = [random.random() for _ in range(dim)]
    searchVecInMilvus(data)
    end_time = time.time()
    print("cost {:.2f}ms".format(1000 * (end_time - m_time)))
```

#### Expected result:
My search operation in Milvus will take longer than normal. This is obviously an abnormal operation. Through the investigation, it takes about 1000ms for me to connect to the local Milvus server. It takes about 700ms to execute the load operation of the collection, and finally 1200ms to execute the release operation and disconnect operation of the collection.I preliminarily think it is caused by a problem with the RC2 version. Here, I kindly ask for your help, thanks.

#### Actual results:
the insert operation cost time: 10842.34ms
the search operation cost time: 3445.77ms

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): v2.0.0-RC2
- Deployment mode(standalone or cluster): standalone (Start by docker-compose)
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.0.0rc2
- OS(Ubuntu or CentOS): Ubuntu 18.04 LTS
- CPU/Memory: Intel(R) Core(TM) i7-8700 CPU cores * 12, Memory 16GB
- GPU: NVIDIA 3080
- Docker version: 20.10.7
- Others: use cpu version

#### Configuration file:
Default configuration

#### Additional context:
[milvus-standalone.log](https://github.com/milvus-io/milvus/files/6991060/milvus-standalone.log)
[milvus-minio.log](https://github.com/milvus-io/milvus/files/6991061/milvus-minio.log)
[milvus-etcd.log](https://github.com/milvus-io/milvus/files/6991062/milvus-etcd.log)

**Comment by xiaofan-luan** [comment]
We suggest not to load each time before you do search.
Load should be a one time task once you finished insertion.

**Comment by arthuo** [comment]
After I load the collection into the memory, do I need to perform a flush operation after inserting the data?

> We suggest not to load each time before you do search.
> Load should be a one time task once you finished insertion.

After I load the collection into the memory, do I need to perform a flush operation after inserting the data?

**Comment by arthuo** [comment]
> We suggest not to load each time before you do search.
> Load should be a one time task once you finished insertion.

After I load the collection into the memory, do I need to perform a flush operation after inserting the data?

**Comment by arthuo** [comment]
The problem has been resolved. Refer to Milvus Office Hours: https://docs.qq.com/doc/DTWZ1VFhia3ZDSlJJ
