### ISSUE TITLE
The MinIO data remains after the collection has been dropped

### ISSUE THREAD

**Issue by shiyu22** [milvus-io/milvus#7122]
#### Steps/Code to reproduce:
1. create a collection and insert 3000 vectors
2. drop collection
3. open MinIO in browser with `127.0.0.1:9000`

#### Expected result:
The MinIO has no data.

#### Actual results:
The MinIO browser shows a few segments.
<img width="1422" alt="截屏2021-08-16 18 09 58" src="https://user-images.githubusercontent.com/53459423/129547803-96eb7c97-00d2-4c6d-86ec-6f71b76caa53.png">

#### Environment:
- Milvus version: v2.0.0-RC4
- Deployment mode: standalone
- SDK version: pymilvus-orm v2.0.0rc4
- OS: MacOs

#### Additional context:
It seems to me that drop collection from the database should be a permanent deletion and not keep on disk. Alternatively, it can add the `soft_delete` interface to mark deleted data.

**Comment by xiaofan-luan** [comment]
this is a known issue by design. We may want to fix this before we support snapshot by simply cleanup the data.
