### ISSUE TITLE
IVF_FLAT cannot be loaded.

### ISSUE THREAD

**Issue by ss892714028** [milvus-io/milvus#7128]
#### Steps/Code to reproduce:
1. create collection
2. insert 100k vectors, 10 times. A total of 1 million vectors
3. create ivf_flat index
4. load
5. search nq=1 nprobe=1

#### Actual results:
search gets stuck
check utility.loading_progress, returns {'num_loaded_entities': 0, 'num_total_entities': 1000000}
However, in log file it shows: [2021/08/17 07:34:01.061 +00:00] [DEBUG] [task.go:307] ["LoadCollection execute done"] [msgID=427081143017799682] [collectionID=427081174746923009]
In Milvus insight, it shows:
![image](https://user-images.githubusercontent.com/34635663/129688547-1688eb3d-5d79-4c33-b0e1-f8841aad7fd5.png)

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):rc4
- Deployment mode(standalone or cluster):standalone docker-compose
- SDK version(e.g. pymilvus v2.0.0rc2):rc4
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 12/64g
- GPU: 
- Others: 

#### Configuration file:
[flat.log](https://github.com/milvus-io/milvus/files/6998145/flat.log)

#### Additional context:
SQ8 index works just fine, this issue is only associated with IVF_FLAT as far as I have tested

**Comment by del-zhenwu** [comment]
seems to be duplicated with #7077

**Comment by filip-halt** [comment]
I have a similar issue with both IVF_FLAT and SQ8. Are you able to release the collection because that also freezes and results in a socket closed error.

**Comment by xige-16** [comment]
> seems to be duplicated with #7077

[segment_loader.go:88] ["AppendIndex failed, C runtime error detected, error code = 1, error msg = map::at"]
 yes, I find the log info in flat.log.

**Comment by xige-16** [comment]
It seems that this problem will occur after the flat index is created. I will try to reproduce it locally today.

**Comment by xige-16** [comment]
The reason is that the slide meta value in the index file is incorrectly filled in. I'll fix the problem right away.

**Comment by xige-16** [comment]
```
std::unique_ptr<IndexWrapper::Binary>
IndexWrapper::Serialize() {
    auto binarySet = index_->Serialize(config_);
    auto index_type = get_index_type();
    if (is_in_nm_list(index_type)) {
        std::shared_ptr<uint8_t[]> raw_data(new uint8_t[raw_data_.size()], std::default_delete<uint8_t[]>());
        memcpy(raw_data.get(), raw_data_.data(), raw_data_.size());
        binarySet.Append(RAW_DATA, raw_data, raw_data_.size());
        auto slice_size = get_index_file_slice_size();
        // https://github.com/milvus-io/milvus/issues/6421
        // Disassemble will only divide the raw vectors, other keys was already divided
        knowhere::Disassemble(slice_size * 1024 * 1024, binarySet);
    }
```
index_->Serialize(config_) will call Disassemble func to generate slice_meta of index,  but knowhere::Disassemble(slice_size * 1024 * 1024, binarySet) after appending row data will override the slice meta.  And if the slice meta is wrong, the process of loading index will fail.

**Comment by xige-16** [comment]
> meta

The solution is to keep historical slide meta information when you call disassemble multiple times.

**Comment by xige-16** [comment]
> ```
> std::unique_ptr<IndexWrapper::Binary>
> IndexWrapper::Serialize() {
>     auto binarySet = index_->Serialize(config_);
>     auto index_type = get_index_type();
>     if (is_in_nm_list(index_type)) {
>         std::shared_ptr<uint8_t[]> raw_data(new uint8_t[raw_data_.size()], std::default_delete<uint8_t[]>());
>         memcpy(raw_data.get(), raw_data_.data(), raw_data_.size());
>         binarySet.Append(RAW_DATA, raw_data, raw_data_.size());
>         auto slice_size = get_index_file_slice_size();
>         // https://github.com/milvus-io/milvus/issues/6421
>         // Disassemble will only divide the raw vectors, other keys was already divided
>         knowhere::Disassemble(slice_size * 1024 * 1024, binarySet);
>     }
> ```
> 
> index_->Serialize(config_) will call Disassemble func to generate slice_meta of index, but knowhere::Disassemble(slice_size * 1024 * 1024, binarySet) after appending row data will override the slice meta. And if the slice meta is wrong, the process of loading index will fail.

The solution is to keep historical slide meta information when you call disassemble multiple times

**Comment by DragonDriver** [comment]
I made a mistake when using the `knowhere::Disassemble`, thx for pointing out this. @xige-16 
i wonder if `BinarySet::Append` should throw an exception when we use a duplicate key, in this case, we append to the binary set twice using the `INDEX_FILE_SLICE_META`.

**Comment by DragonDriver** [comment]
By the way, I think both `Assemble` and `Disassemble` should be called explicitly outside the `Serialize` and `Load`.

**Comment by xige-16** [comment]
The issue has been fixed, trouble you check it. @ss892714028

**Comment by ss892714028** [comment]
Thank you, the PR has been merged, closing this issue.
