### ISSUE TITLE
How to modify parameter segment.maxSize after installing Milvus with helm?

### ISSUE THREAD

**Issue by Bennu-Li** [milvus-io/milvus#7149]
#### Is your feature request related to a problem? Please describe:

I learned that currently the parameter segment.maxSize can only be modified by compiling Milvus with the source code, Is there any way to modify it when installing with helm or through the SDK?

The official documentation only explains in which files these parameters can be modified, but not how to modify it when starting Milvus with helm.
<img width="796" alt="截屏2021-08-18 上午10 55 30" src="https://user-images.githubusercontent.com/53458891/129829509-d54011f0-cea4-46cf-ba00-b1e1c84530be.png">

**Comment by Bennu-Li** [comment]
After starting the Milvus cluster, I got the following eleven pods.
<img width="877" alt="截屏2021-08-18 上午11 23 32" src="https://user-images.githubusercontent.com/53458891/129831924-fed594a2-138e-49ee-a639-466e0be8ad53.png">

And after entering pod my-release-milvus-datacoord-7bb8dff5d4-mxrt7, I changed the parameters in /milvus/configs/advanced/data_coord.yaml segment.maxSize to 1024.
Will this change take effect and how can I verify that my changes have taken effect?

**Comment by DragonDriver** [comment]
Sorry, but we don't support to reload runtime config now. This feature may be our goal in next release version. In order to fix your issue now, you can modify the config file before running the datacoord, in this case, maybe you should bind a new config to the datacoord pod.

**Comment by DragonDriver** [comment]
I don't know if milvus helm support to modify this parameter. Maybe @zwd1208 @jeffoverflow can answer your question.
/assign @zwd1208 
/assign @jeffoverflow

**Comment by jeffoverflow** [comment]
Recently, we will refactor the configuration of Milvus.

**Comment by L-lei** [comment]
> I don't know if milvus helm support to modify this parameter. Maybe @zwd1208 @jeffoverflow can answer your question.
> /assign @zwd1208
> /assign @jeffoverflow

Hello, can you tell me what configuration needs to be modified to install Milvus 2.0, or what hardware configuration is required
Does the persistentvolumeclaim need to be created manually
