### ISSUE TITLE
Milvus crash when searching and building index simultaneously using SQ8H

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#715]
SQ8H: Server may be down if searching and building index run in parallel

**Comment by cydrain** [comment]
crash with following backtrace:
#0 faiss::gpu::GpuIndexIVF::copyFrom()
#1 faiss::gpu::GpuIndexIVFSQHybrid::copyFrom()
#2 faiss::gpu::ToGpuCloner::clone_Index()
#3 faiss::gpu::index_cpu_to_gpu()
#4 knowhere::IVFSQHybrid::CopyCpuToGpu()
#5 knowhere::cloner::CopyCpuToGpu()
#6 milvus::engine::VecIndexImpl::CopyToGpu()

**Comment by cydrain** [comment]
Crash in file GpuIndexIVF.cu, API GpuIndexIVF::copyFrom()
FAISS_ASSERT(index->quantizer->ntotal > 0);

index->quantizer is null

**Comment by cydrain** [comment]
The root cause of this issue is, "cache_insert_data" is enabled, index data is inserted into cache directly, not loaded from disk, so Milvus does not save index->quantizer to index->quantizer_backup.

**Comment by cydrain** [comment]
fixed
