### ISSUE TITLE
Fail to start new docker container with existing volumes if index was created: proxy is not healthy

### ISSUE THREAD

**Issue by jaelgu** [milvus-io/milvus#7150]
#### Steps/Code to reproduce:
1. Download yml file from https://github.com/milvus-io/milvus/blob/master/deployments/docker/cluster/docker-compose.yml
2. Create a milvus cluster docker container `docker-compose up -d`
3. Create a collection with some data
4. Create index & call flush()
5. Delete the container: `docker-compose down` (but keep volumes)
6. Re-create a container with previous volumes: `docker-compose up -d`
7. Try with the new container: connect, list_collections, create/get collection, etc.
8. Check service status: docker-compose ps

#### Expected result:
- all operations should work properly
- all services should run stably & keep healthy

#### Actual results:
- only able to run connections.connect(), but other operations fail with error "proxy is not healthy"
- pulsar exits very soon & can't keep running

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): v2.0.0-RC4
- Deployment mode(standalone or cluster): cluster
- SDK version: pymilvus v2.0.0rc4
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 32GB
- GPU: N/A
- Others: 

#### Additional context:
[log.txt](https://github.com/milvus-io/milvus/files/7004402/log.txt)

**Comment by jaelgu** [comment]
If index was not created, then same steps do not have the same issue

**Comment by DragonDriver** [comment]
How you create the volumes? According to the [Set up a standalone Pulsar in Docker](http://pulsar.apache.org/docs/en/standalone-docker/), `/pulsar/data` and `/pulsar/conf` should be persisted.

**Comment by jaelgu** [comment]
> How you create the volumes? According to the [Set up a standalone Pulsar in Docker](http://pulsar.apache.org/docs/en/standalone-docker/), `/pulsar/data` and `/pulsar/conf` should be persisted.

I just followed steps mentioned above. I used the same docker-compose.yml downloaded from https://github.com/milvus-io/milvus/blob/master/deployments/docker/cluster/docker-compose.yml without change anything.

**Comment by DragonDriver** [comment]
thx for pointing out this @jaelgu , i will try to fix this soon.
/assign

**Comment by zhuwenxing** [comment]
Came to a same issue, but it was datacoord and rootcoord ecited!
![image](https://user-images.githubusercontent.com/12268675/130030685-aa0db28f-30fe-441d-8d0a-25c7e1723bef.png)

[08-19.log](https://github.com/milvus-io/milvus/files/7012704/08-19.log)

**Comment by yanliang567** [comment]
this could be a data compatibility issue if docker-compose up a newer version in step#6, set top priority

**Comment by zhuwenxing** [comment]
The same issue will happen when use docker-compose to deploy a standalone milvus by the steps above.

```
Exception: server is not healthy, please try again later
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-3-3afacc014abe> in <module>
      1 # create connection and list collection
----> 2 connections.connect()
      3 
      4 print(f"\nList collections...")
      5 col_list = list_collections()

~/opt/anaconda3/lib/python3.8/site-packages/pymilvus_orm/connections.py in connect(self, alias, **kwargs)
    160                 self._conns[alias] = conn
    161                 return conn
--> 162             conn = connect_milvus(**self._kwargs[alias])
    163             self._conns[alias] = conn
    164             return conn

~/opt/anaconda3/lib/python3.8/site-packages/pymilvus_orm/connections.py in connect_milvus(**kwargs)
    146             handler = tmp_kwargs.pop("handler", DefaultConfig.DEFAULT_HANDLER)
    147             pool = tmp_kwargs.pop("pool", DefaultConfig.DEFAULT_POOL)
--> 148             return Milvus(tmp_host, tmp_port, handler, pool, **tmp_kwargs)
    149         if alias in self._conns:
    150             if len(kwargs) > 0 and self._kwargs[alias] != kwargs:

~/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/stub.py in __init__(self, host, port, handler, pool, channel, **kwargs)
    120         self._pool_uri = _set_uri(host, port, _uri, self._handler)
    121         self._pool_kwargs = _pool_args(handler=handler, **kwargs)
--> 122         self._update_connection_pool(channel=channel)
    123 
    124         # store extra key-words arguments

~/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/stub.py in _update_connection_pool(self, channel)
    174 
    175         if not channel:
--> 176             self._wait_for_healthy()
    177 
    178     @property

~/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/stub.py in inner(self, *args, **kwargs)
     38     @functools.wraps(func)
     39     def inner(self, *args, **kwargs):
---> 40         return func(self, *args, **kwargs)
     41 
     42     return inner

~/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/stub.py in _wait_for_healthy(self, timeout, retry)
    145                     time.sleep(1)
    146                     retry -= 1
--> 147             raise Exception("server is not healthy, please try again later")
    148 
    149     def __enter__(self):

Exception: server is not healthy, please try again later

```

Milvus version: master-20210819-7233b62
SDK version: pymilvus 2.0.0rc3.dev6
Deployment mode: standalone

But all containers are running
```
NAME                COMMAND                  SERVICE             STATUS              PORTS
milvus-etcd         "etcd -advertise-cli…"   etcd                running             2379/tcp, 2380/tcp
milvus-minio        "/usr/bin/docker-ent…"   minio               running (healthy)   9000/tcp
milvus-standalone   "/tini -- milvus run…"   standalone          running             0.0.0.0:19530->19530/tcp, :::19530->19530/tcp
```
[08-20.log](https://github.com/milvus-io/milvus/files/7019712/08-20.log)

**Comment by jaelgu** [comment]
I also tried standalone, the error "server is not healthy" is gone and all operations work well after waited a while (~ 5 min).

**Comment by zhuwenxing** [comment]
> I also tried standalone, the error "server is not healthy" is gone and all operations work well after waited a while (~ 5 min).

But in my environment, after 20 minutes, it still failed.

**Comment by yanliang567** [comment]
data compatibility issue, shall be fixed in rc5
