### ISSUE TITLE
Good first issue in PyMilvus repository

### ISSUE THREAD

**Issue by DragonDriver** [milvus-io/milvus#7154]
### Good first issue 
- Suitable for people **who have little knowledge of Milvus or PyMilvus, and Python enthusiastic.**
- **Usually takes no more than 30 mins to fix.**

#### If you want to look into a certain issue, please follow the issue link and comment `/assign @YOUR_GITHUB_NAME`.

- If the issue has no assignees, you are safe to assign yourself.
- After you comment `/assign @YOURSELF`, the `sre-ci-robot` will add you into the `Assignees`
- This message may be outdated, feel free to comment on this page so that I'll update everything for you.

#### Please don't edit THIS message, feel free to leave a comment below!
---

|No.|link|Brief intro|Assign|States|
|----|----|----|----|:----:|
|10|https://github.com/milvus-io/pymilvus/issues/689|[BUG] The value of standalone deployment key differs from server|@JackLCL|**Closed**|
|9|https://github.com/milvus-io/pymilvus/issues/684|Link of docs in Readme is pointed into readthedocs|@rahulmistri1997|**Closed**|
|8|https://github.com/milvus-io/pymilvus/issues/671|Bug in 'collection.partition' after create_partition with descriptions||**Unassigned**|
|7|https://github.com/milvus-io/pymilvus/issues/666|Expose guarantee_timestamp parameter when searching a collection||**Unassigned**|
|6|https://github.com/milvus-io/pymilvus/issues/661|The number of retries to check whether the server is healthy is incorrect|@RazaKhanGit|**Assigned**|
|5|#7264|Input metric parameter is changed in calc_distance interface|@xuqiwe|**Closed**|
|4|#6889|No `__enter__` in self._connection() used in query function.|@XuanYang-cn|**Closed**|

**Comment by XuanYang-cn** [comment]
I'm mantaining this page

**Comment by yhmo** [comment]
This issue also can be a good first issue for pymilvus:
https://github.com/milvus-io/milvus/issues/7264

**Comment by XuanYang-cn** [comment]
A copy here: https://github.com/milvus-io/pymilvus/issues/685

**Comment by DingQK** [comment]
Hi! I am new to the community of Milvus and I really want to contribute to the project of PyMilvus. Are there any suitable issues to start with right now? Thank you so much!

**Comment by XuanYang-cn** [comment]
> Hi! I am new to the community of Milvus and I really want to contribute to the project of PyMilvus. Are there any suitable issues to start with right now? Thank you so much!

Thanks for the enthusiasm. We have a similar issue at the PyMilvus repository. You may find the issues that fit your interests here milvus-io/pymilvus#685

**Comment by XuanYang-cn** [comment]
No need to draw people from the Milvus repo, closing this issue now.

**Comment by DingQK** [comment]
@

> > Hi! I am new to the community of Milvus and I really want to contribute to the project of PyMilvus. Are there any suitable issues to start with right now? Thank you so much!
> 
> Thanks for the enthusiasm. We have a similar issue at the PyMilvus repository. You may find the issues that fit your interests here [milvus-io/pymilvus#685](https://github.com/milvus-io/pymilvus/issues/685)

Thank you so much! I will check the issue!
