### ISSUE TITLE
Building index does not make indexes to those data that are searched 

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#7158]
#### Steps/Code to reproduce:
1. deploy Milvus 2.0 
2. create a collection and insert 1200 entities
3. collection.load()
4. collection.search()   # param={"metric_type": "L2", "nprobe": 16}, limit=1)
5. insert 5000 more entities
6. build index ({"index_type": "IVF_SQ8", "metric_type": "L2", "params": {"nlist": 64}})
7. utility.index_building_progress()

#### Expected result:
{'total_rows': 6200, 'indexed_rows': **6200**} 

#### Actual results:
{'total_rows': 6200, 'indexed_rows': **5000**}

Notes: 
1. If you skip  collection.search() on step#4, it does not reproduce.
2. This issue brings a side effect, which is:  if release and reload collection the collection after step#7, it fails in searching with  _<BaseException: (code=1, message=Search failed, C runtime error detected, error code = 1, error msg = Error in virtual milvus::knowhere::DatasetPtr milvus::knowhere:_  

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): rc4
- Deployment mode(standalone or cluster): docker-compose standalone (i don;t think it matters)
- SDK version(e.g. pymilvus v2.0.0rc2):
pymilvus                           2.0.0rc3.dev16
pymilvus-orm                       2.0.0rc3.dev15

**Comment by xiaocai2333** [comment]
Although I strictly follow the above steps, I still cannot reproduce it. If you can reproduce it, please paste the log here. @yanliang567

**Comment by xiaocai2333** [comment]
And I release collection and reload after step#7, search can be executed normally.

**Comment by yanliang567** [comment]
trying to repro it on a latest build

**Comment by yanliang567** [comment]
still repro on master-20210903-960741e
```
        # create
        name = cf.gen_unique_str(prefix)
        collection_w = self.init_collection_wrap(name=name)
        assert collection_w.name == name

        # insert
        data = cf.gen_default_list_data()      # 1200 by default
        _, res = collection_w.insert(data)

        # flush
        assert collection_w.num_entities == len(data[0])

        # search
        collection_w.load()
        search_vectors = cf.gen_vectors(1, ct.default_dim)
        search_params = {"metric_type": "L2", "params": {"nprobe": 16}}
        res_1, _ = collection_w.search(data=search_vectors,
                                       anns_field=ct.default_float_vec_field_name,
                                       param=search_params, limit=1)
        assert len(res_1) == 1
        # collection_w.release()

        # index
        d = cf.gen_default_list_data(nb=5000)
        collection_w.insert(d)
        assert collection_w.num_entities == len(data[0]) + 5000
        _index_params = {"index_type": "IVF_SQ8", "params": {"nlist": 64}, "metric_type": "L2"}
        index, _ = collection_w.create_index(field_name=ct.default_float_vec_field_name,
                                             index_params=_index_params,
                                             name=cf.gen_unique_str())
        assert len(collection_w.indexes) == 1
        log.debug(f"entities: {collection_w.num_entities}")
        log.debug(f"index progress: {utility.index_building_progress(collection_w.name)}")

```
results:
```
[2021-09-04 01:35:55,998 - DEBUG - ci_test]: entities: 6200 (test_e2e_20.py:51)
[2021-09-04 01:35:56,007 - DEBUG - ci_test]: index progress: {'total_rows': 6200, 'indexed_rows': 5000} (test_e2e_20.py:52)
```

**Comment by xiaocai2333** [comment]
'num_entities' will call'flush' for the collection. So the 1200 rows of data inserted for the first time will be flushed, and the shard num defaults to 2, so the data will be written to 2 segments, each of which has about 600 rows of data. There is a setting that segments with less than 1024 rows of data will not be indexed, so the final indexed data is only 5000 rows.

It is recommended to delete and compare with 'num-entities'. @yanliang567

**Comment by yanliang567** [comment]
This would be confusing for users, any solutions?

**Comment by yanliang567** [comment]
@xiaocai2333 One more question, so the unindexed 1200 entities would be searched in FLAT if i search at this moment?

**Comment by xiaocai2333** [comment]
> @xiaocai2333 One more question, so the unindexed 1200 entities would be searched in FLAT if i search at this moment?

These 1200 entities would be searched by violent way.

**Comment by xiaofan-luan** [comment]
This may not be a issue, if you write less than 1024 entities then no index will be build this entities is less than nlist. the data is still visible and once compaction happens we will build index on top of them @yanliang567

**Comment by yanliang567** [comment]
okay, close it for now
