### ISSUE TITLE
The final number of segments is abnormal

### ISSUE THREAD

**Issue by LemonSqi** [milvus-io/milvus#7159]
Q: The background merging is not completed. It is expected that there is only 1 segment, but there are 2 segments in the result

#### Steps/Code to reproduce:
vector data: 100W 128dim float32  (total < 500M)

go-sdk:
var indexFileSize = int64(512) 
no index

#### Expected result:
only 1 segment

#### Actual results:
2 segments

tablefiles:
1168	1629276630639704000	1629276663375973000	1	1629276663375973000	1	312000000	600000	1629276667714639	1629276663375976	1210718	0
1171	1629276630639704000	1629276668362185000	1	1629276668362185000	1	208000000	400000	1629276669941879	1629276668362188	1210718	0

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by yhmo** [comment]
It is as-designed, please refer this article: https://zhuanlan.zhihu.com/p/148106312

**Comment by yhmo** [comment]
Close due to as-designed.
