### ISSUE TITLE
Update the error msg returned by initializing Collection when its name is not created before

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#7165]
#### Steps/Code to reproduce:
```
c = Collection(name) # the collection name is not created before
```

#### Expected result:

msg: collection not existed
#### Actual results:
```
pymilvus.orm.pymilvus_orm.exceptions.SchemaNotReadyException: <SchemaNotReadyException: (code=0, message=Should be passed into the schema.)>
```

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):
- Deployment mode(standalone or cluster): 
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-orm
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by yanliang567** [comment]
the msg should indicates 
1. collection does not exist
2. shall specify schema if want to create a new collection

**Comment by cydrain** [comment]
now the exception is like following:
```
pymilvus.orm.pymilvus_orm.exceptions.SchemaNotReadyException: <SchemaNotReadyException: (code=0, message=Collection 'noname' not exist, or you can pass in schema to create one.)>
```
