### ISSUE TITLE
Resolve memory fragmentation and merge indexes.

### ISSUE THREAD

**Issue by ChangqingChen** [milvus-io/milvus#7171]
In the case of frequent data imports, Milvus may have many indexes in memory.  Is it possible to automatically merge indexes in this case.  If the in-memory index is too fragmented, I think it can have some impact on performance.

**Comment by xiaofan-luan** [comment]
Good catch! Are you hitting the fragmentation issue already? Is it 1.x or 2.x? We are planing on segment compaction to merge fragmented segments in 2.0. Wanna to join our discussion in the tech meeing?

**Comment by ChangqingChen** [comment]
> Good catch! Are you hitting the fragmentation issue already? Is it 1.x or 2.x? We are planing on segment compaction to merge fragmented segments in 2.0. Wanna to join our discussion in the tech meeing?

I'm learning the technical solution of Milvus but haven't used it yet. I've had similar problems in other scenarios.  There's a lot of fragmentation in a single machine, and it definitely affects performance. I'm not sure how fragmented Milvus is.  How do I participate in a tech discussion.

**Comment by xiaofan-luan** [comment]
We have technical discussion biweekly https://wiki.lfaidata.foundation/pages/editpage.action?pageId=43287098

**Comment by xiaofan-luan** [comment]
you are also welcomed to ask questions at discussion or our wechat group

**Comment by xiaofan-luan** [comment]
close for now, we've already working on tech designs of segment compaction
