### ISSUE TITLE
Load data failed

### ISSUE THREAD

**Issue by linchpinlin** [milvus-io/milvus#7180]
#### Steps/Code to reproduce:

> helm upgrade --install --set cluster.enabled=true --set queryNode.replicas=5 --set dataNode.replicas=5 --set indexNode.replicas=2 milvus milvus/milvus

columns: [id, float_vector]
dim=205
total quantity= 3500w

>     default_index = {"index_type": "IVF_FLAT", "params": {"nlist": 256}, "metric_type": "L2"}

I search two vectors with 3 nprobe, and it took about 2 minutes. So I rebuild the index with 2048 nlist and reload the data. However, after a long time (several hours) I couldn't get any results. I tried to release and reload the data, or drop the collection and reinsert the date ...., but the problem persists.

#### Environment:
- v2.0.0-RC4
- cluster
- pymilvus v2.0.0rc4
- CentOS: 
- CPU/Memory: 32/32

#### Additional context:
[k8s pod logs](https://drive.google.com/file/d/1xERlTZix7WLeXLblzX3smNW-DF4Lo0JH/view?usp=sharing)

**Comment by xige-16** [comment]
Load will trigger this bug after creating the ivf flat index， and the issue has been fix by pr #7167.

**Comment by xige-16** [comment]
You can use other types of indexes or use the latest milvus image.

**Comment by linchpinlin** [comment]
I rebuild the IVF_SQ8 index with 2048 nlist and reload the data. However, after a long time (several hours) I couldn't get any results. I tried to release and reload the data, or drop the collection and reinsert the date ...., but the problem persists.
[k8s pod logs](https://drive.google.com/file/d/1Tyd8a9xea8p8CtDJokdeE9zTACzh3WnM/view?usp=sharing)

**Comment by xige-16** [comment]
The solution is to restart the cluster and avoid loading the index of IVF_LFLAT, or directly use the latest milvus image to restart the cluster, there will be no such problem.

**Comment by linchpinlin** [comment]
@xige-16 
I have deleted the cluster and PV, but the problem still exists(IVF_SQ8)
[k8s pod logs](https://drive.google.com/file/d/1Tyd8a9xea8p8CtDJokdeE9zTACzh3WnM/view?usp=sharing)
