### ISSUE TITLE
Wrong method metioned for closing connections 

### ISSUE THREAD

**Issue by timshen** [milvus-io/milvus#7193]
#### Steps/Code to reproduce:
Go to page https://milvus.io/docs/v2.0.0/connect.md#Close-server-connection

#### Expected result:
When you no longer need Milvus services, you can call disconnect() for Milvus Python SDK

#### Actual results:
When you no longer need Milvus services, you can call close()

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by YiyunNi** [comment]
https://github.com/milvus-io/milvus-docs/pull/448
