### ISSUE TITLE
Milvus does not return when call collection.num_entities with binary data

### ISSUE THREAD

**Issue by shiyu22** [milvus-io/milvus#7195]
#### Steps/Code to reproduce:
1. insert more than 1 million 2048 dimension binary data
2. call `collection.num_entities` to get the number

#### Expected result:
return the number of the collection

#### Actual results:
Milvus hangs and it cannot do search/insert, but Milvus can create a collection and return `collection.num_entities(0)` for another collection.

#### Environment:
- Milvus version: v2.0.0-RC4
- Deployment mode :cluster
- SDK version: pymilvus-orm v2.0.0rc4
- OS: Ubuntu

**Comment by shiyu22** [comment]
I can still reproduce this issue on RC5, but I found that `collection.num_entities` is not returning because the insert is not returning, which I did as follows:
1. Inserting 1000 pieces of data at a time was run over 4000 times and the last call never returned a result, but the procedure still exists.
2. Call `num_entities` to get the number of rows in the collection, but it never returned.
3. The inserting process that was killed and call `num_entities` again and also did not return.

I found that the **rootcoord** and **datacoord** logs are updated at 3:00, but the **datanode** has no logs since 1:00. Here are the logs: 

[datanode.log](https://github.com/milvus-io/milvus/files/7088104/datanode.log)
[datacoord.log](https://github.com/milvus-io/milvus/files/7088103/datacoord.log)

**Comment by sunby** [comment]
> I can still reproduce this issue on RC5, but I found that `collection.num_entities` is not returning because the insert is not returning, which I did as follows:
> 
> 1. Insert 1000 vectors at a time and run 4000 consecutively, and the last call never returned a result, but the procedure still exists. The code of batch insert can follow [Batch inserting binary data is too slow #7181](https://github.com/milvus-io/milvus/issues/7181)
> 2. Call `num_entities` to get the number of rows in the collection, but it never returned.
> 3. The inserting process that was killed and call `num_entities` again and also did not return.
> 
> I found that the **rootcoord** and **datacoord** logs are updated at 3:00, but the **datanode** has no logs since 1:00. Here are the logs:
> 
> [datanode.log](https://github.com/milvus-io/milvus/files/7088104/datanode.log)
> [datacoord.log](https://github.com/milvus-io/milvus/files/7088103/datacoord.log)
> [rootcoord.zip](https://github.com/milvus-io/milvus/files/7088112/rootcoord.zip)

I don't find the call of `num_entities` in your scripts in #7181. Can you paste full insert scripts here? I find server received `flush` request called in `num_entities` many times and  successully execute it.

**Comment by Uzay-G** [comment]
I am also having a problem like this: when I call `num_entities` it just hangs. Was the issue closed because it's been fixed?
