### ISSUE TITLE
Cal_distance returns wrong error when calculating with default metric type

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#7217]
#### Steps/Code to reproduce:
Run test_utility_20.py::TestUtilityBase::test_calc_distance_default_metric

And it is good in pymilvus: 2.0.0rc5.dev18 version.

It is bad in pymilvus: 2.0.0rc5.dev19 and 2.0.0rc5.dev20 versions.

I think this issue is caused by this pr (milvus-io/pymilvus#648) which fixing issue #7086.

#### Expected result:
Return distance without errors

#### Actual results:
params value {'sqrt': False} is illegal (api_request.py:27)

#### Environment:
- Milvus version(): bf2c427
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
pymilvus:
2.0.0rc5.dev19 and 2.0.0rc5.dev20 versions.
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by yhmo** [comment]
Fixed by milvus-io/pymilvus#656

**Comment by binbinlv** [comment]
Verified and fixed.

Name: pymilvus
Version: 2.0.0rc5.dev24
