### ISSUE TITLE
Memory consumption increased by stairs if index-load-search repeatly

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#7222]
#### Steps/Code to reproduce:
1. deploy Milvus cluster - 1 replica for each pod with no resource limit
2. create a collection with 128d-10m entities
3. build index
4. collection.load
5. search
6. collection.release
7. collection.index.drop
8. repeat from step#3

#### Expected result:
Memory consumption keeps stable 

#### Actual results:
memory consumption increase by stairs for each repeat

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): master-20210820-bf2c427
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
pymilvus              2.0.0rc5.dev18

#### Configuration file:
1 replica for each pod with no resource limit

#### Additional context:
<img width="1184" alt="Screen Shot 2021-08-22 at 5 01 42 PM" src="https://user-images.githubusercontent.com/82361606/130350002-5bb8e57a-8f44-4c67-883e-461f42295374.png">

**Comment by xige-16** [comment]
I have tested repeated load and release, and the memory will stop rising after it reaches a certain level. You can test it again.

**Comment by xige-16** [comment]
It may also be a problem with go's gc

**Comment by yanliang567** [comment]
remove urgent, if memory consumption keeps increasing without a limitation, lets reset to rugent

**Comment by czs007** [comment]
If this phenomenon is not observed in the new version, can it be closed?
@yanliang567

**Comment by yanliang567** [comment]
let me retry.

**Comment by yanliang567** [comment]
on master commit id 41190c2
memory keeps increasing in querynode and indexnode  if doing index-loading-search repeatly 
at first:
![image](https://user-images.githubusercontent.com/82361606/146479453-3edd5f3e-77dc-4b72-8365-7e55eba9f7dc.png)
after repeat for 4 times: querynode increased 90.5%, indexnode increased 16.4%
![image](https://user-images.githubusercontent.com/82361606/146479513-c12505e0-9d21-4a06-9b75-2c0f200c940f.png)

**Comment by xiaofan-luan** [comment]
@yanliang567 is this similar issue  @godchen0212 trying to solve?

**Comment by xiaocai2333** [comment]
> @yanliang567 is this similar issue @godchen0212 trying to solve?

yes

**Comment by yanliang567** [comment]
verified not increased by stairs any more
