### ISSUE TITLE
IVF_FLAT data compression!

### ISSUE THREAD

**Issue by Z4HRA-S** [milvus-io/milvus#7232]
#### Description
I'm trying to implement a text similarity search  API for Arabic texts based on cosine similarity. So I need to store normalized vectors. But when I insert vectors with IVF_FLAT index, the norm of vectors changes. As I recall from previous versions of Milvus (v0.11.0 and v0.10.5), The IVF_FLAT index type, stores vectors as they are with no compression. Is that changed in v1.0.0? 
My API worked fine with Milvus v0.11.0 and pymilvus 0.4.0.
The Collection and Index configs are shown below.
```
from milvus import Milvus
import numpy as np
from sentence_transformers import SentenceTransformer

client = Milvus("127.0.0.1",19530)
print(client.get_collection_info("test"))
print(client.get_index_info("test"))

model = SentenceTransformer("model_path")
text = "Arabic_tweet_text"
q = model.encode([text], batch_size=1)
print("The norm of vector before normalization: ", np.linalg.norm(q[0]))

q = [(np.array(em) / np.linalg.norm(em)).tolist() for em in q]
print("The norm of vector after normalization: ", np.linalg.norm(q[0]))

client.insert("test",records=q,ids=[13], partition_tag="test")
s,v = client.get_entity_by_id("test", [13])
print("The norm of vector inserted in milvus: ", np.linalg.norm(v[0]))
```
#### Expected Result
```
CollectionSchema(collection_name='test', dimension=256, index_file_size=1024, metric_type=<MetricType: IP>))
IndexParam(_collection_name='test', _index_type=<IndexType: IVFLAT>, _params={'nlist': 100}))
The norm of vector before normalization: 24.014126
The norm of vector after normalization: 1.0000000252805568
(Status(code=0, message='Add vectors successfully!'), [13])
The norm of vector inserted in milvus: 1.0000000252805568
``` 
#### Actual Result
```
CollectionSchema(collection_name='test', dimension=256, index_file_size=1024, metric_type=<MetricType: IP>))
IndexParam(_collection_name='test', _index_type=<IndexType: IVFLAT>, _params={'nlist': 100}))
The norm of vector before normalization: 24.014126
The norm of vector after normalization: 1.0000000252805568
(Status(code=0, message='Add vectors successfully!'), [13])
The norm of vector inserted in milvus: 0.03114730469241069
```

#### Environment:
- Milvus version: v1.0.0
- Deployment mode: standalone
- SDK version: pymilvus v1.0.1
- OS: Ubuntu

**Comment by xiaofan-luan** [comment]
nope, v1.0 has similar behavior as 0.10

**Comment by yhmo** [comment]
I got error with your script:
404 Client Error: Not Found for url: https://huggingface.co/api/models/sentence-transformers/model_path

I think the root cause is you didn't call the flush() between the insert() and get_entity_by_id():
```
from milvus import Milvus
from milvus.client.types import MetricType
import numpy as np

client = Milvus("127.0.0.1",19530)

vec = [2,2]
print("Before normalization",vec)
nor_vec = [ele/np.linalg.norm(vec) for ele in vec]
print("After normalization",nor_vec)

collection_name = "AAA"
s, has = client.has_collection(collection_name=collection_name)
if has:
    client.drop_collection(collection_name=collection_name)
client.create_collection(param={'collection_name': collection_name,
               'dimension': len(vec),
               'index_file_size': 1024,
               'metric_type':MetricType.L2})

records = [vec]
ids = [i + 100 for i in range(len(records))]
print(ids)
client.insert(collection_name=collection_name,records=records, ids=ids)
client.flush()
s,v = client.get_entity_by_id(collection_name=collection_name, ids=ids)
print("The vector inserted in milvus: ",v)
```

**Comment by Z4HRA-S** [comment]
> I got error with your script:
> 404 Client Error: Not Found for url: https://huggingface.co/api/models/sentence-transformers/model_path
> 
> I think the root cause is you didn't call the flush() between the insert() and get_entity_by_id():
> 
> ```
> from milvus import Milvus
> from milvus.client.types import MetricType
> import numpy as np
> 
> client = Milvus("127.0.0.1",19530)
> 
> vec = [2,2]
> print("Before normalization",vec)
> nor_vec = [ele/np.linalg.norm(vec) for ele in vec]
> print("After normalization",nor_vec)
> 
> collection_name = "AAA"
> s, has = client.has_collection(collection_name=collection_name)
> if has:
>     client.drop_collection(collection_name=collection_name)
> client.create_collection(param={'collection_name': collection_name,
>                'dimension': len(vec),
>                'index_file_size': 1024,
>                'metric_type':MetricType.L2})
> 
> records = [vec]
> ids = [i + 100 for i in range(len(records))]
> print(ids)
> client.insert(collection_name=collection_name,records=records, ids=ids)
> client.flush()
> s,v = client.get_entity_by_id(collection_name=collection_name, ids=ids)
> print("The vector inserted in milvus: ",v)
> ```

I tried it with flush and with a random numpy vector. The problem is still here.
