### ISSUE TITLE
"Access Denied" when create index

### ISSUE THREAD

**Issue by jaelgu** [milvus-io/milvus#7234]
#### Steps/Code to reproduce:
1. Start milvus with Kubernetes Cluster
2. Create collection
3. Insert data (eg. sift1m)
4. Create index (IVF_FLAT or IVF_SQ8)

#### Expected result:

Index created without error.

#### Actual results:

Error: Access Denied.

![2021823-164558](https://user-images.githubusercontent.com/86251631/130418344-20aacc3d-122a-43a4-9574-9123661a5843.png)

#### Environment:
- Milvus version: v2.0.0-RC4
- Deployment mode: cluster (minikube)
- SDK version: pymilvus v2.0.0rc4
- OS(Ubuntu or CentOS): 
- CPU/Memory: 12 CPUs / 62Gi
- GPU: N/A
- Others: 

#### Additional context:
[indexcoord_log.txt](https://github.com/milvus-io/milvus/files/7030520/indexcoord_log.txt)
[indexnode_log.txt](https://github.com/milvus-io/milvus/files/7030522/indexnode_log.txt)

**Comment by xiaocai2333** [comment]
This is because an error occurred while reading data from minio.
