### ISSUE TITLE
Search return error after global reduce  if querynode only watchDmChannel and has't receive any insert message

### ISSUE THREAD

**Issue by xige-16** [milvus-io/milvus#7240]
#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by xige-16** [comment]
querynode return a empty result, but proxy want all search results have topk IDs and distances even though they are all -1.

**Comment by cydrain** [comment]
Test search on an empty collection, get following response returned:
```
response {
    results {
        num_queries = 2
        ids = []
        scores = []
        top_k = 0
        topks = [0, 0]
    }
    status {
        error_code = 0
        reason = "empty search result"
    }
}
```

The response looks correct.

**Comment by xige-16** [comment]
pr #7244 has fixed the issue.

**Comment by xige-16** [comment]
The problem no longer occurs, close this issue first.
