### ISSUE TITLE
RootCoordClient mess key not exist RootCoordClient getRootCoordAddr failed

### ISSUE THREAD

**Issue by wq1315** [milvus-io/milvus#7260]
#### Steps/Code to reproduce:
**I deploy the distributed version of milvus through docker compose.Then I created a collection,such as the following code:**

```python
from pymilvus_orm import Collection, DataType, FieldSchema, CollectionSchema
dim = 2048
default_fields = [
    FieldSchema(name="id", dtype=DataType.INT64, is_primary=True),
    FieldSchema(name="uuid", dtype=DataType.INT64),
    FieldSchema(name="embedding", dtype=DataType.FLOAT_VECTOR, dim=dim)
]
default_schema = CollectionSchema(fields=default_fields, description="test collection") 
collection = Collection(name="vectors", schema=default_schema)
```

**Then I insert the vector**

```python
#coding: utf-8
import multiprocessing
import time

def func(entities):
    collection.insert(entities)
    
collection = Collection('vectors')

if __name__ == "__main__":
    pool = multiprocessing.Pool(processes = 5)
    for i in tqdm(range(10000)):
        nb = 300
        dim = 2048
        years = [i for i in range(nb)]
        embeddings = [[random.random() for _ in range(dim)] for _ in range(nb)]
        entities = [years, embeddings]
        pool.apply_async(func, (entities, ))  
        
    pool.close()
    pool.join() 
```

#### Expected result:
**In the end, I couldn't search vector and connect to the service of milvus**

#### Actual results:
**When I connect again, the following problems occurred** 
> Exception: server is not healthy, please try again later

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):v2.0.0-rc4-20210811-bdb8396
- Deployment mode( cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc4):pymilvus v2.0.0rc4
- OS( CentOS): CentOS
- CPU/Memory: 325G
- GPU: 128G
- Others: 

#### Configuration file:
Default configuration

#### Additional context:
[pulsar.log](https://github.com/milvus-io/milvus/files/7037195/pulsar.log)
[rootcoord.log](https://github.com/milvus-io/milvus/files/7037196/rootcoord.log)
[proxy.log](https://github.com/milvus-io/milvus/files/7037198/proxy.log)
[datacoord.log](https://github.com/milvus-io/milvus/files/7037199/datacoord.log)

**Comment by cydrain** [comment]
@wq1315 this issue still exist in rc6 ?

**Comment by wq1315** [comment]
@cydrain  I deploy the distributed version of milvus with kubectl , this issue still exist in rc6 . when I deploy the distributed version of milvus with docker-compose,I haven't found this problem.

**Comment by wq1315** [comment]
@cydrain  I deploy the distributed version of milvus with kubectl , this issue still exist in rc6 . when I deploy the distributed version of milvus with docker-compose,I haven't found this problem.

**Comment by wq1315** [comment]
@cydrain I deploy the distributed version of milvus with kubernetes , this issue still exist in rc6 . when I deploy the distributed version of milvus with docker-compose,I haven't found this problem.

**Comment by wq1315** [comment]
@cydrain I deploy the distributed version of milvus with kubernetes , this issue still exist in rc6 . when I deploy the distributed version of milvus with docker-compose,I haven't found this problem yet.

**Comment by 24king** [comment]
can anyone do some help for this problem，get the same error.

**Comment by 24king** [comment]
After review some code, I am sure we need to wait some time before the milvus 2.0 to become reliable.

**Comment by wq1315** [comment]
@24king When will milvus 2.0 be released?
