### ISSUE TITLE
Which graphics cards does Milvus support?

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus#727]
Which graphics cards does Milvus support? Can you provide some information in docs?

**Comment by JinHai-CN** [comment]
Currently, we don't have each kinds of GPU cards to test. But according to the design, we support the NVIDIA GPU cards which Compute Capability not less than 6.0. You may check https://developer.nvidia.com/cuda-gpus to find all supported GPU and if there is GPU not supported in the list, please also comment it in this issue.
