### ISSUE TITLE
Some suggestions on the high availability solution of Milvus open source vector search framework

### ISSUE THREAD

**Issue by LemonSqi** [milvus-io/milvus#7299]
Hello, Milvus Engineers:

Recently, I was thinking about how to design the high availability solution of Milvus - open source framework to meet the needs of actual business scenarios. In this regard, through the previous research results of Milvus generation 1 and generation 2 architecture, it is found that Milvus still has some deficiencies in data availability. I hope to hear the suggestions of Engineers:

Possible data high availability design mechanism of Milvus in actual business application scenarios:

1) Horizontal ha expansion

![1](https://user-images.githubusercontent.com/36250184/130776040-bc5e6e78-7f7c-4c23-baf9-b7f888b39533.png)

At present, Milvus architecture supports the horizontal expansion of read nodes, but the consideration of data availability in memory is relatively limited. When a node goes down, if you want to access the node's data, you need to go through the process of data reloading and reallocation. When the data scale is large, the loading efficiency of memory is slow, which is in some business scenarios with high requirements for data availability and real-time search, Obviously, it is unacceptable. Similar to HDFS system (block storage design), we hope that Milvus can design replica mode for data segment and ensure the dynamic consistency of replica data, which is the basis of data availability in horizontal expansion mode

2) Vertical ha expansion

![2](https://user-images.githubusercontent.com/36250184/130775945-7a1bdfba-e9b7-4276-9bb4-fb0dc4a807ec.png)

Considering the design of vertical ha, we hope to realize the switching between hot standby and dual active modes. From the perspective of application, the simplest mode is hot standby mode, which can effectively realize the switching between active and standby when the primary node is down. At the same time, we need to solve the problem of data consistency under the primary and standby nodes. In addition, in some business scenarios, such as the hot spot scenario, we hope that some specific nodes can switch to the vertical dual active mode to share the processing pressure of limited nodes on high concurrent requests, so as to improve the ability of streaming requests in the hot spot scenario. Of course, data layering in hot scenes is another design pattern, which should be refined according to the actual situation.

The above is my thinking and appeal on the high availability solution of Milvus framework. Looking forward to your reply. 
       Thank you!

**Comment by M-A-N-I-S-H-K** [comment]
@xiaofan-luan  how did you achieve HA with horizontal scaling of multiple shared nodes?

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan how did you achieve HA with horizontal scaling of multiple shared nodes?

For now, once the node crash, all segment will be reassigned to alived worker nodes by coordinator. 
If coordinator itself crashed, it will be replaced brought up by k8s.

This issues talks about another possibility, while we support two in memory copy for the same data, thus failover can happen without wait for segment reassignment. We will work on the reassignment on Milvus 2.1(Probably by the end of this year.)

**Comment by M-A-N-I-S-H-K** [comment]
is there a video regarding  complete understanding for how the milvus cluster works.
I did go through the documentation, however it's still kind of unclear to me. A video with explanation on how the cluster works on v2.0 setup as opposed to v1.0 would be of great help. @xiaofan-luan

**Comment by xiaofan-luan** [comment]
> is there a video regarding complete understanding for how the milvus cluster works.
> I did go through the documentation, however it's still kind of unclear to me. A video with explanation on how the cluster works on v2.0 setup as opposed to v1.0 would be of great help. @xiaofan-luan

That is a good idea! Any other community offers similar video we can learn from?

**Comment by xiaofan-luan** [comment]
I thought that is a good example https://www.youtube.com/watch?v=dxrEHqMFUWI~

**Comment by T3arD0wn** [comment]
Hey @xiaofan-luan any update on this so far? 

> > is there a video regarding complete understanding for how the milvus cluster works. 
> > I did go through the documentation, however it's still kind of unclear to me. A video with explanation on how the cluster works on v2.0 setup as opposed to v1.0 would be of great help.  @xiaofan-luan
> 
> That is a good idea! Any other community offers similar video we can learn from?
