### ISSUE TITLE
Could NOT find benchmark (missing: benchmark_DIR)

### ISSUE THREAD

**Issue by LilySys** [milvus-io/milvus#731]
Hi, when i run ./build.sh -t Debug, i got following question:
 Could NOT find benchmark (missing: benchmark_DIR)
i use milvus on centos.

**Comment by JinHai-CN** [comment]
Firstly, we recommend you to follow https://github.com/milvus-io/milvus/blob/master/install.md#compile-milvus-on-docker to compile Milvus, 
Secondly, which branch are you using?

**Comment by LilySys** [comment]
thank you, i got error just according to the source code installation guide, I don't know what you mean by branch，can you be specific？

**Comment by JinHai-CN** [comment]
I mean use the installation docker we provided to compile Milvus and use master branch.

**Comment by JinHai-CN** [comment]
No action.
