### ISSUE TITLE
insert timeout when running CI

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#7319]
#### Steps/Code to reproduce:
Running CI: [FAILED testcases/entity/test_insert.py::TestInsertBase::test_insert_flush_drop_collection]

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-7314/1/pipeline/71/

Logs:
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-7314/1/artifacts

#### Expected result:
Insert successfully

#### Actual results:
Insert timeout

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): 16bef70d8
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
- pymilvus: 2.0.0rc5.dev29
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by yanliang567** [comment]
@binbinlv is it reproduced recently ?

/assign @binbinlv 
/unassign @sunby

**Comment by binbinlv** [comment]
This does not occur recently, close it first, will reopen it if it occurs again in the future.
