### ISSUE TITLE
Querynode memory consumption suddenly increased even there are no search requests

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#7326]
#### Steps/Code to reproduce:
1. Milvus 2.0 cluster
2. insert 128d-10m entities
3. build index(building index failed due to client connection stopped by accident)
4. do nothing

#### Expected result:
memory consumption keeps smoothly

#### Actual results:
querynode memory increased suddenly after 9hours (at 09:30)
![Screen Shot 2021-08-27 at 9 28 54 AM](https://user-images.githubusercontent.com/82361606/131057723-ee0f0d21-8e39-44b5-bea0-53d16b9b178f.png)
![Screen Shot 2021-08-27 at 9 29 38 AM](https://user-images.githubusercontent.com/82361606/131057729-9a4110cd-1234-4d2c-898f-0ac01b540885.png)

```
milvus-loading-datacoord-8679fffb7b-2fmdw       1/1     Running            0          11h     10.97.3.160   qa-node001.zilliz.local   <none>           <none>
milvus-loading-datanode-7db8bb455c-tn6wc        1/1     Running            0          11h     10.97.3.163   qa-node001.zilliz.local   <none>           <none>
milvus-loading-etcd-0                           1/1     Running            0          11h     10.97.6.138   qa-node004.zilliz.local   <none>           <none>
milvus-loading-indexcoord-bb796ff79-sl68r       1/1     Running            0          11h     10.97.6.135   qa-node004.zilliz.local   <none>           <none>
milvus-loading-indexnode-6f9754b466-nxq5h       1/1     Running            0          11h     10.97.6.136   qa-node004.zilliz.local   <none>           <none>
milvus-loading-minio-7dd8bbb455-xpb7w           1/1     Running            0          11h     10.97.3.165   qa-node001.zilliz.local   <none>           <none>
milvus-loading-proxy-68f499c8c7-9nwhl           1/1     Running            0          11h     10.97.3.166   qa-node001.zilliz.local   <none>           <none>
milvus-loading-pulsar-6bd7df697-56vq6           1/1     Running            0          11h     10.97.3.167   qa-node001.zilliz.local   <none>           <none>
milvus-loading-querycoord-7bb764f564-7szbp      1/1     Running            0          11h     10.97.6.137   qa-node004.zilliz.local   <none>           <none>
milvus-loading-querynode-564565745b-t77xf       1/1     Running            0          11h     10.97.3.164   qa-node001.zilliz.local   <none>           <none>
milvus-loading-rootcoord-c9bb788f6-qlfwt        1/1     Running            0          11h     10.97.3.162   qa-node001.zilliz.local   <none>           <none>

```

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): 055d94e
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus                           2.0.0rc5.dev18

#### Additional context:
[proxy.mem.log](https://github.com/milvus-io/milvus/files/7063574/proxy.mem.log)
[querycoord.mem.log](https://github.com/milvus-io/milvus/files/7063575/querycoord.mem.log)

**Comment by xige-16** [comment]
pr #7527 has fixed the memory leak when searching.

**Comment by yanliang567** [comment]
working on the verification
/assign
/unassign @xige-16

**Comment by yanliang567** [comment]
not repro on master master-20210908-3c2821e

**Comment by SuoSiFire** [comment]
@xige-16  Does this problem exist in the v1.1.1 ?
