### ISSUE TITLE
Proxy crashed: panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#7348]
#### Steps/Code to reproduce:
Running L0, L1 test cases on multiple replica env:
```
                               --set proxy.replicas=2 \
                               --set queryNode.replicas=2 \
                               --set indexNode.replicas=2 \
                               --set dataNode.replicas=2 \
```

Logs:
[log.tar.zip](https://github.com/milvus-io/milvus/files/7070415/log.tar.zip)

#### Expected result:
No crash

#### Actual results:
proxy crashed:
Fail connecting to server on  ...... Timeout

```
[2021-08-28 08:22:12 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ['int64 in [0, 1]', ['%'], None, 20], kwargs: {} (api_request.py:44)
[2021-08-28 08:22:12 - ERROR - pymilvus.client.grpc_handler]:
Addr [172.20.255.155:19530] query
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1630138932.941082000","description":"Error received from peer ipv4:172.20.255.155:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Socket closed","grpc_status":14}"
>
	{'API start': '2021-08-28 08:22:12.878805', 'RPC start': '2021-08-28 08:22:12.879725', 'RPC error': '2021-08-28 08:22:12.943789'} (grpc_handler.py:76)
```

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):  af574d1
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
Name: pymilvus
Version: 2.0.0rc5.dev29

- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by yanliang567** [comment]
multi-nodes is the priority for rc7, set to urgent

**Comment by czs007** [comment]
Please try with the latest version

**Comment by yanliang567** [comment]
@binbinlv any chance to retry on latest build?
 /assign @binbinlv

**Comment by binbinlv** [comment]
This panic has been recreated in benchmark tests:

Milvus log for benchmark could be found using "https://kibana-dev.zilliz.cc/app/discover"

panic: runtime error: index out of range [0] with length 0

![image](https://user-images.githubusercontent.com/83755740/133547408-226dafdc-4329-4bcd-8476-f30be6203f83.png)

configure:
benchmark-b8f6l-1-etcd-0                               1/1     Running   0          84s
benchmark-b8f6l-1-milvus-datacoord-6f8967dd6b-9z7xm    1/1     Running   0          84s
benchmark-b8f6l-1-milvus-datanode-86bb99bcff-nsv7q     1/1     Running   0          84s
benchmark-b8f6l-1-milvus-datanode-86bb99bcff-x9nmm     1/1     Running   0          84s
benchmark-b8f6l-1-milvus-indexcoord-876c9b6f7-vps5w    1/1     Running   0          84s
benchmark-b8f6l-1-milvus-indexnode-ccf47c9d8-8fclt     1/1     Running   0          84s
benchmark-b8f6l-1-milvus-indexnode-ccf47c9d8-hr9nz     1/1     Running   0          84s
benchmark-b8f6l-1-milvus-proxy-56c8796fd9-82wt9        1/1     Running   0          84s
benchmark-b8f6l-1-milvus-pulsar-5c88957db8-rphfw       1/1     Running   0          84s
benchmark-b8f6l-1-milvus-querycoord-55444d87d6-n7t8r   1/1     Running   0          84s
benchmark-b8f6l-1-milvus-querynode-85f69bcc66-94s7x    1/1     Running   0          84s
benchmark-b8f6l-1-milvus-querynode-85f69bcc66-ss9nz    1/1     Running   0          84s
benchmark-b8f6l-1-milvus-rootcoord-68f77b9466-6jk5w    1/1     Running   0          84s

**Comment by fishpenguin** [comment]
I'm working on it.

**Comment by congqixia** [comment]
The fixing PR has been merge. Could you please verify panicking has been solved?? @binbinlv

**Comment by binbinlv** [comment]
@congqixia  OK, working on it, thanks.

**Comment by binbinlv** [comment]
It did not occur through recreating, so close it.
