### ISSUE TITLE
No sqrt in L2 calculation?

### ISSUE THREAD

**Issue by gistart** [milvus-io/milvus#7365]
Looks like Milvus v2 does not calculate square root for L2 metric, which is super confusing.

If it's the intended behaviour and not a bug -- this definitely should be mentioned in the docs: https://milvus.io/docs/v2.0.0/metric.md#Euclidean-distance-L2

#### Steps/Code to reproduce:

Full script: https://pastebin.com/m4x7DQd7

```
DATA = [
    [1.0, 2.0],
    [3.0, 4.0],
    [5.0, 6.0],
]

def l2_dist(v1, v2):
    return math.sqrt( sum((a - b)**2 for a,b in zip(v1, v2)) 

if __name__ == "__main__":
    conn = connections.connect(host='localhost', port='19530')
    
    for v1, v2 in itertools.combinations(DATA, r=2):
        print("Compare:", v1, "and", v2)
        print(" naive:", l2_dist(v1, v2))

        calc_res = conn.calc_distance(
            {"float_vectors": [v1]},
            {"float_vectors": [v2]},
            params={"metric": "L2"}
        )
        print("milvus:", calc_res[0])
        print()
```

#### Expected vs actual results:

```
Compare: [1.0, 2.0] and [3.0, 4.0]
 naive: 2.8284271247461903
milvus: 8.0

Compare: [1.0, 2.0] and [5.0, 6.0]
 naive: 5.656854249492381
milvus: 32.0

Compare: [3.0, 4.0] and [5.0, 6.0]
 naive: 2.8284271247461903
milvus: 8.0
```

#### Environment:
- Milvus version: `milvus:v2.0.0-rc4-20210811-bdb8396`
- Deployment mode: standalone
- SDK version: `pymilvus-orm==2.0.0rc4`

**Comment by xiaofan-luan** [comment]
@yhmo could you please take a look? thanks

**Comment by yhmo** [comment]
@gistart 

The "sqrt" is an optional parameter. You can set the params like this: {"metric_type": "L2", "sqrt": true}
The following is the description of the params:
```
:param params: key-value pair parameters
                       Key: "metric_type"/"metric"    Value: "L2"/"IP"/"HAMMING"/"TANIMOTO", default is "L2",
                       Key: "sqrt"    Value: true or false, default is false    Only for "L2" distance
                       Key: "dim"     Value: set this value if dimension is not a multiple of 8,
                                             otherwise the dimension will be calculted by list length,
                                             only for "HAMMING" and "TANIMOTO"
        :type  params: dict
            Examples of supported metric_type:
                `{"metric_type": "L2", "sqrt": true}`
                `{"metric_type": "IP"}`
                `{"metric_type": "HAMMING", "dim": 17}`
                `{"metric_type": "TANIMOTO"}`
            Note: metric type are case insensitive
```

**Comment by gistart** [comment]
@yhmo 

Thank you!

In my test script I show that collection search also does not compute sqrt by default (I trimmed example code for clarity).

Found this docstring only for `utility.calc_distance` function. Does it also work for collection search?

**Comment by yhmo** [comment]
Search api has no such parameter to compute sqrt value. Because ANN search is not accuracy, sqrt the distance doesn't help to get a more precise result.  And sqrt computing will cost more cpu cycle,  performance is bad. So search api doesn't support sqrt.

**Comment by gistart** [comment]
Well, computing it client-side e.g. via python costs significantly more cpu than server-side (via c/go).

And it's not necessarily about accuracy, more like existing models w/ predetermined threshold values. 

Thank you!
