### ISSUE TITLE
The response of Pymilvus and ORM is inconsistent when drop index repeatedly

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#7372]
#### Steps/Code to reproduce:
```
    def test_index_drop_repeatedly(self):
        c_name = cf.gen_unique_str(prefix)
        collection_w = self.init_collection_wrap(name=c_name)
        conn = self._connect()
        collection_w.create_index(default_field_name, default_index_params)
        log.debug(collection_w.index()[0].params)
        collection_w.drop_index()
        conn.drop_index(collection_w.name, default_field_name)
        # collection_w.drop_index()
```
a. In Pymilvus:  dropping index repeatedly is allowed (no exception)
b. In ORM: dropping index repeatedly will throw an exception

#### Expected result:
Although the Pymilvus is not exposed to users, it is currently accessible by `connect(ORM)`. Therefore the response should be unified.

#### Actual results:
In Pymilvus no exception
In ORM throw exception `<IndexNotExistException: (code=0, message=Index doesn't exist.)>`

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):
  1c88c8b Mon Aug 30 07:33:32 UTC 2021
- Deployment mode(standalone or cluster):
   cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
   pymilvus              2.0.0rc5.dev29
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by XuanYang-cn** [comment]
I think the API behaviour is correct. PyMilvus APIs are stateless, thus dropping a non-exist index is allowed. ORM-style APIs have states, drop a non-exist index will raise errors.  @ThreadDao

**Comment by ThreadDao** [comment]
So should similar behaviors of other interfaces be unified according to this behavior? like repeatedly connect? repeatedly drop collection? repeatedly load and release and so on...

**Comment by XuanYang-cn** [comment]
Good question

**Comment by XuanYang-cn** [comment]
After discussing with @czs007, we made some consensus, and still have some questions to discuss.

To sum up:

@ThreadDao, You're right at the beginning. The behaviour of PyMilvus API and ORM-styled API should be the same.

The question is: **Which API to keep when meeting difference**? 

It's still under discussion.

**Comment by XuanYang-cn** [comment]
Moving this into 2.0.0-backlog

**Comment by XuanYang-cn** [comment]
This's what we'll do in PyMilvus:

1. Clarify PyMilvus APIs behaviours.
2. Mark stateless APIs as `deprecated`.  (GA???)
    - Uses Google-style docstrings.
    - Firstly, reimplement orm out-of-rely from stateless APIs.
    - Secondly, mark those stateless APIs as `deprecated`.

**Comment by XuanYang-cn** [comment]
This altering would cost much time, closing this issue. 

There will be updates on the PyMilvus repo.
