### ISSUE TITLE
Support `BIN_IVF_FLAT` for substructure/superstructure metrics

### ISSUE THREAD

**Issue by hadim** [milvus-io/milvus#7373]
#### Is your feature request related to a problem? Please describe:

I want to use `BIN_IVF_FLAT` to increase search speed versus `BIN_FLAT` with superstructure and substructure metrics.

#### Describe the solution you'd like:

Support `BIN_IVF_FLAT` for superstructure and substructure metrics.

#### Describe alternatives you've considered:

Use `BIN_FLAT`.

#### Additional context:

---

ping @maclandrol

**Comment by hadim** [comment]
According to https://github.com/milvus-io/milvus/issues/1603, `IVF_FLAT` is not possible for those two metrics.

Can someone confirm this?

**Comment by yhmo** [comment]
In Milvus, for binary vectors, IVF is not available for substructure and superstructure. Because the two metrics are Non-metric distance: https://37steps.com/1617/non-euclidean-and-non-metric-dissimilarities/
