### ISSUE TITLE
Milvus EM sometimes display NaN items

### ISSUE THREAD

**Issue by Never-up** [milvus-io/milvus#7391]
在milvus界面查看数据时，出现总item时出现NaN
如一下图片这种情况
(https://zhisheng-aifile.oss-cn-hangzhou.aliyuncs.com/WechatIMG3869.jpeg)

**Comment by xiaofan-luan** [comment]
please use english in the issue for the rest of the community, thanks

**Comment by nameczz** [comment]
@Never-up 
Please provide your milvus version and milvus-em version.
And how to reproduce this .
