### ISSUE TITLE
Milvus 2.0 rc5 standalone version always quits automatically

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#7396]
Milvus 2.0.0 rc5 always quits automatically and takes a lot of time to restart each time
Error reporting of log presence before restarting 
![er](https://user-images.githubusercontent.com/34296482/131609474-fd46f0cd-86f9-4690-a3fe-518be74d1afb.png)

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):2.0.0rc5
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus2.0.0 rc5
- OS(Ubuntu or CentOS): Ubuntu

**Comment by yanliang567** [comment]
this was dup to #7390

**Comment by yanliang567** [comment]
BTW, this was fixed in rc5-hotfix1 and latest mater build with commit #7393
