### ISSUE TITLE
DataNode flush failed but data discarded

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#7397]
A second flush will only contain part of the data.

**Comment by XuanYang-cn** [comment]
- [ ] Flush needs a retry

- [ ] Minio resources need to be take cared at the background

**Comment by yanliang567** [comment]
any reproduce steps with actual result and expection?
any plan for rc7 or updates for now?
@XuanYang-cn

**Comment by yanliang567** [comment]
@XuanYang-cn was this fixed

**Comment by XuanYang-cn** [comment]
This is fixed
