### ISSUE TITLE
300万条512维向量测试检索时很慢？

### ISSUE THREAD

**Issue by JiliuLiSU** [milvus-io/milvus#7404]
您好 我用300万条512维向量测试检索时很慢，每次检索都在1分钟左右，indextpye是IVF_FLAT，milvus版本是1.1.1。请问可能的原因是什么呢

**Comment by yhmo** [comment]
For IVF_FLAT, data size = 3000000*512*4 = 6 GB
In the milvus config file:  server_config.yaml, there is an item named "cache_size":
```
cache:
  cache_size: 4GB
```
Its default value is 4GB, not enough for your data size. If cache size is not enough, milvus will have to swap data from hard disk, this will be very slow.

You can change the config to cache_size: 8GB, then restart milvus server and try again.

**Comment by JiliuLiSU** [comment]
Thank You Very Much

**Comment by JiliuLiSU** [comment]
> For IVF_FLAT, data size = 3000000_512_4 = 6 GB
> In the milvus config file: server_config.yaml, there is an item named "cache_size":
> 
> ```
> cache:
>   cache_size: 4GB
> ```
> 
> Its default value is 4GB, not enough for your data size. If cache size is not enough, milvus will have to swap data from hard disk, this will be very slow.
> 
> You can change the config to cache_size: 8GB, then restart milvus server and try again.

<html>
<body>


Thank You Very Much
--



</body>
</html>

> For IVF_FLAT, data size = 3000000_512_4 = 6 GB
> In the milvus config file: server_config.yaml, there is an item named "cache_size":
> 
> ```
> cache:
>   cache_size: 4GB
> ```
> 
> Its default value is 4GB, not enough for your data size. If cache size is not enough, milvus will have to swap data from hard disk, this will be very slow.
> 
> You can change the config to cache_size: 8GB, then restart milvus server and try again.

Thank you very much
