### ISSUE TITLE
Partial data is not flushed if don't call num_entities

### ISSUE THREAD

**Issue by jaelgu** [milvus-io/milvus#7408]
#### Steps/Code to reproduce:
docker-compose standalone
1. Create a collection
2. Insert sift1m data
3. Create index
4. Check index_progress

#### Expected result:

total_rows=1000000

#### Actual results:
<img width="496" alt="Screen Shot 2021-09-02 at 4 15 26 PM" src="https://user-images.githubusercontent.com/86251631/131810144-e356a2d5-0cd0-45c8-b800-856a42085eb2.png">

total_rows=900000

- if manually call num_entities before, then call index_progress returns correct total_rows.
- waited a few more minutes after insert & index, but still missing 100000 data in total_rows for index_progress
- same happens to load_progress that total_rows is 900000 without call num.entities before.

#### Environment:
- Milvus version: v2.0.0-RC5
- Deployment mode(standalone or cluster): standalone
- SDK version: pymilvus v2.0.0rc5
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others: 

#### Additional context:
[v2rc5_logs.txt](https://github.com/milvus-io/milvus/files/7097317/v2rc5_logs.txt)

**Comment by jaelgu** [comment]
- sometimes happens to cluster as well
- also reproduced with rc5-hotfix

**Comment by yanliang567** [comment]
I think this is known issue, and @congqixia  is working on it.
