### ISSUE TITLE
Call Insert() hang

### ISSUE THREAD

**Issue by Bennu-Li** [milvus-io/milvus#7446]
#### Steps/Code to reproduce:
- Repeatedly insert data, inserting 100,000 128-dimensional vectors each time.

- After insert 147050070 vectors, continue inserting data, but Milvus client don't renturn anymore.

- Create a new collection and insert data to it, it still don't renturn.

#### Environment:
- Milvus version(2.0.0-RC5)
- Deployment mode(cluster)
- SDK version(pymilvus v2.0.0rc5)

**Comment by yanliang567** [comment]
I think this is a known issue, and @sunby is working on it.

**Comment by yanliang567** [comment]
@sunby please confirm whether it is a dup to #7195

**Comment by sunby** [comment]
> @sunby please confirm whether it is a dup to #7195

yes, it is same as #7195

**Comment by yanliang567** [comment]
close for dup issue
