### ISSUE TITLE
Start Milvus docker container fail in Centos 7.7

### ISSUE THREAD

**Issue by zjsen668** [milvus-io/milvus#745]
**Describe the bug**
When I start the milvus docker container in centos 7.7, It exit immediately with log “./start_server.sh: line 3:     7 Illegal instruction     (core dumped) ../bin/milvus_server -c ../conf/server_config.yaml -l ../conf/log_config.conf”.

But, I start it successfully in another server with ubuntu18.

**Steps/Code to reproduce behavior**
docker run -td --name milvus_cpu -e "TZ=Asia/Shanghai" -p 19530:19530 -p 8080:8080 -v /home/milvus/db:/var/lib/milvus/db -v /home/milvus/conf:/var/lib/milvus/conf -v /home/milvus/logs:/var/lib/milvus/logs milvusdb/milvus:cpu-latest

**Environment details**
- Intel(R) Xeon(R) CPU E3-1225
- Docker19.03, CentOS Linux release 7.7.1908
- v0.6.0
- default configuration (server_config_cpu.yaml)

**Screenshots**
![milvus](https://user-images.githubusercontent.com/16451999/70587231-5b928f80-1c04-11ea-8d0e-580512560f3a.png)

**Comment by yhmo** [comment]
"Illegal instruction" means that CPU was trying to execute instruction which does not understand. This may happen if the program compiled with instruction set which is not supported by your CPU.

**Comment by yhmo** [comment]
Could you use "cat /proc/cpuinfo" to get your cpu information and send to us?

**Comment by zjsen668** [comment]
> Could you use "cat /proc/cpuinfo" to get your cpu information and send to us?

**Here is the cpu info：**

`processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 58
model name      : Intel(R) Xeon(R) CPU E3-1225 V2 @ 3.20GHz
stepping        : 9
microcode       : 0x19
cpu MHz         : 1600.250
cache size      : 8192 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips        : 6385.06
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 58
model name      : Intel(R) Xeon(R) CPU E3-1225 V2 @ 3.20GHz
stepping        : 9
microcode       : 0x19
cpu MHz         : 1604.625
cache size      : 8192 KB
physical id     : 0
siblings        : 4
core id         : 1
cpu cores       : 4
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips        : 6385.06
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 2
vendor_id       : GenuineIntel
cpu family      : 6
model           : 58
model name      : Intel(R) Xeon(R) CPU E3-1225 V2 @ 3.20GHz
stepping        : 9
microcode       : 0x19
cpu MHz         : 1621.500
cache size      : 8192 KB
physical id     : 0
siblings        : 4
core id         : 2
cpu cores       : 4
apicid          : 4
initial apicid  : 4
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips        : 6385.06
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 58
model name      : Intel(R) Xeon(R) CPU E3-1225 V2 @ 3.20GHz
stepping        : 9
microcode       : 0x19
cpu MHz         : 1615.750
cache size      : 8192 KB
physical id     : 0
siblings        : 4
core id         : 3
cpu cores       : 4
apicid          : 6
initial apicid  : 6
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips        : 6385.06
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:`

**Comment by yhmo** [comment]
It seems your machine's cpu dones't support Intel AVX2 instructions. Milvus search engine depends on faiss, and we build the faiss library with AVX2 instructions. That is why you encountered the "illegal instructions" error. You can use 'cat /proc/cpuinfo' to another machine which can run milvus successfully, its cpu information should contains "avx2".
We use 'avx2' to build faiss since its performance is batter than 'avx'. If you still want to run milvus on the centos machine, please follow this [guideline](https://milvus.io/docs/en/userguide/install_milvus/#build-from-source) to build milvus from source code. And, before you compile it, change "-mavx2" to "-mavx" in /core/src/index/cmake/ThirdPartyPackagesCore.cmake line No.711.

**Comment by zjsen668** [comment]
> It seems your machine's cpu dones't support Intel AVX2 instructions. Milvus search engine depends on faiss, and we build the faiss library with AVX2 instructions. That is why you encountered the "illegal instructions" error. You can use 'cat /proc/cpuinfo' to another machine which can run milvus successfully, its cpu information should contains "avx2".
> We use 'avx2' to build faiss since its performance is batter than 'avx'. If you still want to run milvus on the centos machine, please follow this [guideline](https://milvus.io/docs/en/userguide/install_milvus/#build-from-source) to build milvus from source code. And, before you compile it, change "-mavx2" to "-mavx" in /core/src/index/cmake/ThirdPartyPackagesCore.cmake line No.711.

I'll have a try. Thanks for your help!

**Comment by zhangAlwin** [comment]
> > It seems your machine's cpu dones't support Intel AVX2 instructions. Milvus search engine depends on faiss, and we build the faiss library with AVX2 instructions. That is why you encountered the "illegal instructions" error. You can use 'cat /proc/cpuinfo' to another machine which can run milvus successfully, its cpu information should contains "avx2".
> > We use 'avx2' to build faiss since its performance is batter than 'avx'. If you still want to run milvus on the centos machine, please follow this [guideline](https://milvus.io/docs/en/userguide/install_milvus/#build-from-source) to build milvus from source code. And, before you compile it, change "-mavx2" to "-mavx" in /core/src/index/cmake/ThirdPartyPackagesCore.cmake line No.711.
> 
> I'll have a try. Thanks for your help!

guideline link has already been invalid...
