### ISSUE TITLE
It takes 5 minutes to connect to milvus

### ISSUE THREAD

**Issue by linchpinlin** [milvus-io/milvus#7465]
#### Steps/Code to reproduce:
Milvus(uri='tcp://127.0.0.1:19530')
or
milvus_init = Milvus(host=host, port=port)
Gunicorn（gevent）+ Flask

#### Environment:
- Milvus version: 1.1.1
- Deployment mode(standalone or cluster): cluster

**Comment by linchpinlin** [comment]
If in the flask environment, everything is OK
![8ca831a0-3cfa-485c-8c36-c2599f9a2c2f](https://user-images.githubusercontent.com/31131753/131959401-6e804c70-87e3-445d-b568-4604eb326b9d.png)

**Comment by linchpinlin** [comment]
I found out that it relies on the timeout parameter of Gunicorn, if the timeout is 10, the connection needs 10s...

**Comment by ScholliYT** [comment]
Hi @linchpinlin I think I am facing the same issue. I try to use milvus together with a flask api. Whenever I use 

```python
from gevent import monkey
monkey.patch_all()
```

I can't establish a connection to the database. What code did you end up with?

**Comment by linchpinlin** [comment]
Hi, @ScholliYT 
```
from gevent import monkey
monkey.patch_all()
import grpc.experimental.gevent as grpc_gevent
grpc_gevent.init_gevent()
```
It resolves the problem.
