### ISSUE TITLE
Hang too long to get collction.num_entities

### ISSUE THREAD

**Issue by czhen-zilliz** [milvus-io/milvus#7466]
#### Steps/Code to reproduce:

Env: milvus rc5-hotfix1
Milvus address: 172.16.20.82:19530 (@shanghaikid 's environment, you can connect it directly in sh office)
SDK: pymilvus-rc5

Our Milvus(rc4) instance has a collection `car_search` (which was created at rc2)with 250k entities, before we upgrade milvus to rc5-hotfix1, we inserted 50k more entities. But it failed to show num_entities after be upgraded.

```
>>> from pymilvus import connections
>>> connections.add_connection(default={"host": '172.16.20.82', "port": 19530})
>>> connections.connect(alias='default')

>>> from pymilvus import list_collections
>>> list_collections()
['car_search2', 'any', 'car_search']

>>> from pymilvus import Collection, DataType, FieldSchema, CollectionSchema
>>> collction = Collection('car_search')

>>> collction.num_entities
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/czhen/Documents/github/milvus_cli/venv/lib/python3.7/site-packages/pymilvus/orm/pymilvus_orm/collection.py", line 353, in num_entities
    conn.flush([self._name])
  File "/Users/czhen/Documents/github/milvus_cli/venv/lib/python3.7/site-packages/pymilvus/client/stub.py", line 52, in handler
    return func(self, *args, **kwargs)
  File "/Users/czhen/Documents/github/milvus_cli/venv/lib/python3.7/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/Users/czhen/Documents/github/milvus_cli/venv/lib/python3.7/site-packages/pymilvus/client/stub.py", line 908, in flush
    return handler.flush(collection_names, timeout, **kwargs)
  File "/Users/czhen/Documents/github/milvus_cli/venv/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/Users/czhen/Documents/github/milvus_cli/venv/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 1074, in flush
    self._wait_for_flushed(collection_name, lambda: future.result().coll_segIDs[collection_name].data)
  File "/Users/czhen/Documents/github/milvus_cli/venv/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/Users/czhen/Documents/github/milvus_cli/venv/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 1043, in _wait_for_flushed
    time.sleep(0.5)
KeyboardInterrupt
```

#### Expected result:

Pymilvus should return `num_entities` correctly and quickly.

#### Actual results:

Pymilvus hang for a long while. And raise the error as above. It seems costed too much time when waiting for flushed.

Besides, we try to use Node SDK and it return a 250k entities result which is incorrect.

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): rc5 hotfix 1
- Deployment mode(standalone or cluster): docker standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.0.0rc5
- OS(Ubuntu or CentOS): macOS
- CPU/Memory: 
- GPU: 
- Others:

**Comment by yanliang567** [comment]
@sunby is it a dup to #7195

**Comment by congqixia** [comment]
> @sunby is it a dup to #7195

@yanliang567 we checked the log, these two issues are not the same. We suspected that that root cause was some meta error between RC2~RC5 hot fix. The error scene environment has been delete. Could you please try to reproduce this one?

**Comment by yanliang567** [comment]
@zhuwenxing could you please help to reproduce this issue?

**Comment by zhuwenxing** [comment]
> @zhuwenxing could you please help to reproduce this issue?

:ok_hand:

**Comment by zhuwenxing** [comment]
I checked the RC2's docker-compose.yml, there are no volumes in content. So I am wondering how you upgrade RC2 to RC4? When RC4 upgrade to RC5-hotfix, I have not occurred this issue.

**Comment by shanghaikid** [comment]
I don't remember, it has been too long.

**Comment by yanliang567** [comment]
@shanghaikid @czhen-zilliz shall we close this issue for now, and reopen it if reproduced to you?

**Comment by shanghaikid** [comment]
Sure. Thanks.

**Comment by JamCrash** [comment]
I faced the same problem, is it solved now?

**Comment by yanliang567** [comment]
not reproduced on rc6, please try it @JamCrash

**Comment by JamCrash** [comment]
but I can reproduced it in minikube, I do like this:
first helm install the server cluster, and do test, the test doing well,
then helm uninstall the server cluster, wait a second an restart it, then do the test, the problem above is reproduced stabilized

**Comment by yanliang567** [comment]
that's a known,which is by default helm install does not persist the data inserted. to workaround it, you need to pull the latest milvus-helm repo and manually set the annotations for pulsar, etcd and minio

**Comment by JamCrash** [comment]
I am using the latest repo already, but how to set the annotations?

**Comment by yanliang567** [comment]
Please refer to the code below as an example:
` helm install my-release milvus/milvus --set cluster.enabled=true --set etcd.persistence.annotations."helm\.sh/resource-policy"=keep --set minio.persistence.annotations."helm\.sh/resource-policy"=keep --set pulsarStandalone.persistence.annotations."helm\.sh/resource-policy"=keep`

**Comment by JamCrash** [comment]
I deployed the cluster in the above way, this time I got stuck in the searching step:
List collections...
['hello_milvus']

Create collection...

List collections...
['hello_milvus']

Get collection entities...
9000

Create index...

load collection...

Search...

**Comment by JamCrash** [comment]
> I deployed the cluster in the above way, this time I got stuck in the searching step:
> List collections...
> ['hello_milvus']
> 
> Create collection...
> 
> List collections...
> ['hello_milvus']
> 
> Get collection entities...
> 9000
> 
> Create index...
> 
> load collection...
> 
> Search...

helm install first time ..., test well ;
helm uninstall then helm install, test block

**Comment by yanliang567** [comment]
@JamCrash Mmm...could you please file a new issue, we will investigate it

**Comment by JamCrash** [comment]
> @JamCrash Mmm...could you please file a new issue, we will investigate it

I file a new issue for this problem： #8109
