### ISSUE TITLE
Query  api needs to add  test cases

### ISSUE THREAD

**Issue by fishpenguin** [milvus-io/milvus#7469]
#### What would you like to be added:

Query only support query by primary key field. Currently it supports all kinds of expression which defined in search api.

#### Why is this needed:

Query api supports query by expression which is similar to search scalar filter by [pr7386](https://github.com/milvus-io/milvus/pull/7386).

**Comment by ThreadDao** [comment]
1. Add cases for query on non-primary fields
2. Add cases for query with `not in` expr
