### ISSUE TITLE
Milvus V1.1.1. The number of WAL files continues to increase.

### ISSUE THREAD

**Issue by SuoSiFire** [milvus-io/milvus#7485]
#### Steps/Code to reproduce:

I use milvus of v1.1.1 to deploy one write node and multiple read nodes. After a few months of normal use, it was suddenly discovered yesterday that the inserted feature could not be retrieved after a few hours. So I went to look at the file directory and found that more than a dozen wal files were not processed. Then I restarted the service. After a long time, the service processed all the wal files. However, the number of wal files has started to increase again.

#### Expected result:

wal files should always be processed, not just when restarting.

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): v1.1.1
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): java
- OS(Ubuntu or CentOS): centos
- CPU/Memory:  120G
- GPU: no
- Others: 

#### Configuration file:

{    "cache.cache_size": "200GB",    "cache.insert_buffer_size": "10GB", "wal.buffer_size": "1GB"}

#### Additional context:

Since the log was not mounted before, the log will be provided later.

**Comment by yhmo** [comment]
Could you describe your insert pattern? How many vectors per insert request? How many insert requests per minute? Dimension of the vectors?

**Comment by SuoSiFire** [comment]
I found that it may be that my delete operations are relatively large and I did not delete them in batches, which caused the wal processing speed to slow down. It looked better after I changed it.

I found this log in the debug log 

[2021-09-05 17:56:40,158][DEBUG][SERVER][PrintTimeRecord][wal_thread] handle segment 1630140249199818000: Find uids and set deleted docs and bloom filter, append 0 offsets (510.640301 seconds [510640.301074 ms])

**Comment by SuoSiFire** [comment]
But now I have a new problem. I tried to index a new collection, but he got stuck. 

I can see in the debug log that the indexing request started, but it has not been successful. 

It has been stuck for about 10 minutes.

**Comment by SuoSiFire** [comment]
I found this [issue](https://github.com/milvus-io/milvus/issues/4838), but the code version I used is v1.1.1, so I should bring this fix.

**Comment by yhmo** [comment]
> But now I have a new problem. I tried to index a new collection, but he got stuck.
> 
> I can see in the debug log that the indexing request started, but it has not been successful.
> 
> It has been stuck for about 10 minutes.

Index time cost depends on how many vectors in this collection, and what the index parameter is. For example, nlist=128 and nlist=4096 time cost is totally different.

The #4838 is for not block an empty collection index if the background build index thread is working.  If your new collection is empty, but it stuck, that means the background build index thread is working for old collection.
