### ISSUE TITLE
cpu resource not fully used during search

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#749]
**Describe the bug**
cpu resource not fully used during search

1000w 128Dim vectors
index type: IVFLAT
nlist: 16384
index_file_size: 1024
metric_type: L2
search nq=1, topk=1000, cpu occupancy is only 35%

**Comment by yhmo** [comment]
cpu occupancy mainly depends on nq.
On a 12 cpu cores machine:
nq = 1,   cpu occupancy is about 10%
nq = 5,   cpu occupancy is about 40%
nq = 10, cpu occupancy is about 70%
nq = 12, cpu occupancy is about 80%

**Comment by JinHai-CN** [comment]
One query use one thread to calculate according to the code. Therefore, low nq can't fully use the CPU. I think this is a good point to indicate us how to optimize the query.

**Comment by JinHai-CN** [comment]
Fixed.
