### ISSUE TITLE
pin_mem_size 256MB, temp_mem_size 256MB, resource count 2

### ISSUE THREAD

**Issue by 785321021** [milvus-io/milvus#7493]
#### Steps/Code to reproduce:
search top 50

#### Expected result:
Faiss assertion 'err__ == cudaSuccess' failed in void Faiss::gpu::runL2Norm(Faiss::gpu::Tensor<T, 2, true, IndexType>&, bool, Faiss::gpu::tensor<float, 1, true, IndexType>&, bool, cudaStrean_t) [with T = float; TVec = float4; Indextype = int; cudaStream_t = CUstream_st*] at gpu/impl/L2Norm.cu:292; details: CUDA error 209 not kernel image is available for execution on the device

#### Environment:
- Milvus version(1.1.1):
- SDK version(pymilvus==1.1.2):
- OS(CentOS): 
- CPU/Memory:    512G
- GPU:       20G * 4
- Others: 

#### Configuration file:
debug.log:
[2021-09-05 01:41:44,785][DEBUG][ENGINE][CheckCpuInstructionSet][milvus_server] Supported CPU instruction sets: avx512, avx2, sse4_2
[2021-09-05 01:41:44,826][DEBUG][ENGINE][Initialize][milvus_server] FAISS hook AVX512
[2021-09-05 01:41:44,827][DEBUG][KNOWHERE][InitDevice][milvus_server] DEVICEID 0, pin_mem_size 256MB, temp_mem_size 256MB, resource count 2
[2021-09-05 01:41:44,827][DEBUG][KNOWHERE][InitDevice][milvus_server] DEVICEID 1, pin_mem_size 256MB, temp_mem_size 256MB, resource count 2
[2021-09-05 01:41:44,827][DEBUG][KNOWHERE][InitDevice][milvus_server] DEVICEID 2, pin_mem_size 256MB, temp_mem_size 256MB, resource count 2
[2021-09-05 01:41:44,827][DEBUG][KNOWHERE][InitDevice][milvus_server] DEVICEID 3, pin_mem_size 256MB, temp_mem_size 256MB, resource count 2
[2021-09-05 01:41:44,834][DEBUG][SERVER][GetInstance][milvus_server] [search][0] Build index gpu: gpu0 gpu1 gpu2 gpu3
[2021-09-05 01:41:44,834][DEBUG][SERVER][GetInstance][milvus_server] [search][0] Build index gpu: gpu0 gpu1 gpu2 gpu3
[2021-09-05 01:41:44,838][DEBUG][SERVER][StartService][milvus_server] Specify openmp thread number: 32
[2021-09-05 01:41:44,838][DEBUG][ENGINE][Build][milvus_server] MetaUri: mysql://root1:Adgjl123456@172.19.80.58:3306/milvus

no error log

docker logs :
Faiss assertion 'err__ == cudaSuccess' failed in void Faiss::gpu::runL2Norm(Faiss::gpu::Tensor<T, 2, true, IndexType>&, bool, Faiss::gpu::tensor<float, 1, true, IndexType>&, bool, cudaStrean_t) [with T = float; TVec = float4; Indextype = int; cudaStream_t = CUstream_st*] at gpu/impl/L2Norm.cu:292; details: CUDA error 209 not kernel image is available for execution on the device

#### Additional context:
Through nvidia-smi, it is found that the video memory used by the Milvus container accounts for a small part. If it does not reach all the video memory of the graphics card, it will report an error video memory overflow. According to the debug log, it seems that the video memory that the container is willing to use is limited
（通过nvidia-smi发现milvus容器用的显存占很小一部分，根本没达到显卡的全部显存，就报错显存溢出，根据debug日志发现好像容器乐意使用的显存呗限制了）

**Comment by scsven** [comment]
@785321021 `CUDA error 209` It seems related to a hardware problem. Please provide more information about your graphics card, the CUDA version, and the driver version.

**Comment by 785321021** [comment]
graphics card:   
NVIDIA-SMI 465.27       Driver Version: 465.27       CUDA Version: 11.3
04:00.0 VGA compatible controller: ASPEED Technology, Inc. ASPEED Graphics Family (rev 41)
18:00.0 VGA compatible controller: NVIDIA Corporation Device 2204 (rev a1)
3b:00.0 VGA compatible controller: NVIDIA Corporation Device 2204 (rev a1)
86:00.0 VGA compatible controller: NVIDIA Corporation Device 2204 (rev a1)
af:00.0 VGA compatible controller: NVIDIA Corporation Device 2204 (rev a1)

docker logs：
Welcome to use Milvus!
Milvus Release version: v1.1.1, built at 2021-06-15 14:51.12, with OpenBLAS library.
You are using Milvus GPU edition
Last commit id: 330cc61bede475c4a7a71841d54e633586cea829

Loading configuration from: /var/lib/milvus/conf/server_config.yaml
GPU resources ENABLED !
Supported CPU instruction sets: avx512, avx2, sse4_2
Nvidia driver version: 465.27
CUDA Driver Version / Runtime Version : 11.3 / 10.1
FAISS hook AVX512
Milvus server started successfully!
Faiss assertion 'err__ == cudaSuccess' failed in void faiss::gpu::runL2Norm(faiss::gpu::Tensor<T, 2, true, IndexType>&, bool, faiss::gpu::Tensor<float, 1, true, IndexType>&, bool, cudaStream_t) [with T = float; TVec = float4; IndexType = int; cudaStream_t = CUstream_st*] at gpu/impl/L2Norm.cu:292; details: CUDA error 209 no kernel image is available for execution on the device

**Comment by scsven** [comment]
@785321021 What is the model of your graphics card? Is it the RTX series?

**Comment by 785321021** [comment]
GPU 00000000:18:00.0
    Product Name                          : NVIDIA GeForce RTX 3090
    Product Brand                         : GeForce
    Display Mode                          : Disabled
    Display Active                        : Disabled
    Persistence Mode                      : Disabled
    MIG Mode
        Current                           : N/A
        Pending                           : N/A
    Accounting Mode                       : Disabled
    Accounting Mode Buffer Size           : 4000
    Driver Model
        Current                           : N/A
        Pending                           : N/A
    Serial Number                         : N/A
    GPU UUID                              : GPU-4fb6ac9a-29e1-b611-4af7-b61a99e3b92d
    Minor Number                          : 0
    VBIOS Version                         : 94.02.42.00.3E
    MultiGPU Board                        : No
    Board ID                              : 0x1800
    GPU Part Number                       : N/A
    Inforom Version
        Image Version                     : G001.0000.03.03
        OEM Object                        : 2.0
        ECC Object                        : N/A
        Power Management Object           : N/A
    GPU Operation Mode
        Current                           : N/A
        Pending                           : N/A
    GPU Virtualization Mode
        Virtualization Mode               : None
        Host VGPU Mode                    : N/A
    IBMNPU
        Relaxed Ordering Mode             : N/A
    PCI
        Bus                               : 0x18
        Device                            : 0x00
        Domain                            : 0x0000
        Device Id                         : 0x220410DE
        Bus Id                            : 00000000:18:00.0
        Sub System Id                     : 0x14541B4C
        GPU Link Info
            PCIe Generation
                Max                       : 3
                Current                   : 1
            Link Width
                Max                       : 16x
                Current                   : 16x
        Bridge Chip
            Type                          : N/A
            Firmware                      : N/A
        Replays Since Reset               : 0
        Replay Number Rollovers           : 0
        Tx Throughput                     : 0 KB/s
        Rx Throughput                     : 0 KB/s
    Fan Speed                             : 33 %
    Performance State                     : P8
    Clocks Throttle Reasons
        Idle                              : Active
        Applications Clocks Setting       : Not Active
        SW Power Cap                      : Not Active
        HW Slowdown                       : Not Active
            HW Thermal Slowdown           : Not Active
            HW Power Brake Slowdown       : Not Active
        Sync Boost                        : Not Active
        SW Thermal Slowdown               : Not Active
        Display Clock Setting             : Not Active
    FB Memory Usage
        Total                             : 24268 MiB
        Used                              : 504 MiB
        Free                              : 23764 MiB
    BAR1 Memory Usage
        Total                             : 256 MiB
        Used                              : 6 MiB
        Free                              : 250 MiB
    Compute Mode                          : Default
    Utilization
        Gpu                               : 0 %
        Memory                            : 0 %
        Encoder                           : 0 %
        Decoder                           : 0 %
    Encoder Stats
        Active Sessions                   : 0
        Average FPS                       : 0
        Average Latency                   : 0
    FBC Stats
        Active Sessions                   : 0
        Average FPS                       : 0
        Average Latency                   : 0
    Ecc Mode
        Current                           : N/A
        Pending                           : N/A
    ECC Errors
        Volatile
            SRAM Correctable              : N/A
            SRAM Uncorrectable            : N/A
            DRAM Correctable              : N/A
            DRAM Uncorrectable            : N/A
        Aggregate
            SRAM Correctable              : N/A
            SRAM Uncorrectable            : N/A
            DRAM Correctable              : N/A
            DRAM Uncorrectable            : N/A
    Retired Pages
        Single Bit ECC                    : N/A
        Double Bit ECC                    : N/A
        Pending Page Blacklist            : N/A
    Remapped Rows                         : N/A
    Temperature
        GPU Current Temp                  : 28 C
        GPU Shutdown Temp                 : 98 C
        GPU Slowdown Temp                 : 95 C
        GPU Max Operating Temp            : 93 C
        GPU Target Temperature            : 83 C
        Memory Current Temp               : N/A
        Memory Max Operating Temp         : N/A
    Power Readings
        Power Management                  : Supported
        Power Draw                        : 23.34 W
        Power Limit                       : 350.00 W
        Default Power Limit               : 350.00 W
        Enforced Power Limit              : 350.00 W
        Min Power Limit                   : 100.00 W
        Max Power Limit                   : 350.00 W
    Clocks
        Graphics                          : 0 MHz
        SM                                : 0 MHz
        Memory                            : 405 MHz
        Video                             : 555 MHz
    Applications Clocks
        Graphics                          : N/A
        Memory                            : N/A
    Default Applications Clocks
        Graphics                          : N/A
        Memory                            : N/A
    Max Clocks
        Graphics                          : 2100 MHz
        SM                                : 2100 MHz
        Memory                            : 9751 MHz
        Video                             : 1950 MHz
    Max Customer Boost Clocks
        Graphics                          : N/A
    Clock Policy
        Auto Boost                        : N/A
        Auto Boost Default                : N/A
    Processes
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 126570
            Type                          : C
            Name                          : /root/anaconda3/envs/mlv/bin/python
            Used GPU Memory               : 251 MiB
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 215617
            Type                          : C
            Name                          : /root/anaconda3/envs/mlv/bin/python
            Used GPU Memory               : 251 MiB

**Comment by 785321021** [comment]
@scsven

**Comment by 785321021** [comment]
@scsven 
I install “NVIDIA Container Toolkit” Then, only 253m video memory is used during operation. If it exceeds 500m, there will be this error. The actual video memory is 24g. It's far from reaching the online level of the graphics card. I wonder if it's the docker container that limits the available video memory
（我中间安装了 NVIDIA Container Toolkit  然后运行过程中显存只使用了253M。超过500M就会有这个错误。实际显存有24G。远远没达到显卡上线，我怀疑会不会是docker容器把可使用的显存限制了）

python code error messages：
Status(code=<StatusCode.UNAVAILABLE: (14, 'unavailable')>, message='Error occurred. keepalive watchdog timeout')

docker logs messages：
(mlv) [root@localhost lixin_test]# docker logs 032074643bd5

    __  _________ _   ____  ______    
   /  |/  /  _/ /| | / / / / / __/    
  / /|_/ // // /_| |/ / /_/ /\ \    
 /_/  /_/___/____/___/\____/___/     

Welcome to use Milvus!
Milvus Release version: v0.10.0, built at 2020-06-15 14:52.16, with OpenBLAS library.
You are using Milvus GPU edition
Last commit id: 5f3c0052478a08d07d68c5dc1aab57a42293f430

Loading configuration from: ../conf/server_config.yaml
GPU resources ENABLED !
WARNNING: You are using SQLite as the meta data management, which can't be used in production. Please change it to MySQL!
Supported CPU instruction sets: avx512, avx2, sse4_2
Nvidia driver version: 455.45.01
CUDA Driver Version / Runtime Version : 11.1 / 10.1
FAISS hook AVX512
Milvus server started successfully!
Faiss assertion 'err__ == cudaSuccess' failed in void faiss::gpu::runL2Norm(faiss::gpu::Tensor<T, 2, true, IndexType>&, bool, faiss::gpu::Tensor<float, 1, true, IndexType>&, bool, cudaStream_t) [with T = float; TVec = float4; IndexType = int; cudaStream_t = CUstream_st*] at gpu/impl/L2Norm.cu:292; details: CUDA error 209 no kernel image is available for execution on the device
./start_server.sh: line 3:     8 Aborted                 (core dumped) ../bin/milvus_server -c ../conf/server_config.yaml
(mlv) [root@localhost lixin_test]#

**Comment by scsven** [comment]
@785321021 Hi, RTX 3090 is Ampere micro-architecture, with compute capability 8.6, which needs to compile with `sm_86`, but it not be contained in v0.10.0. The highest compute capability that has been supported is `sm_75`.
See this build script: https://github.com/milvus-io/milvus/blob/v0.10.0/core/src/index/thirdparty/faiss/build.sh#L2

**Comment by 785321021** [comment]
I am Look forward to  milvus    support   NVIDIA   RTX 3090   and    NVIDIA Ampere A30
