### ISSUE TITLE
Querynode addQueryChannel before watchDMLChannels

### ISSUE THREAD

**Issue by bigsheeper** [milvus-io/milvus#7495]
#### Steps/Code to reproduce:
Querynode addQueryChannel before watchDMLChannels, and queryCollection would register empty tSafeWatcher, because there is no vChannels in collection before calling watchDMLChannels.

#### Expected result:
search passed

#### Actual results:
search timeout
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-7434/9/pipeline

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by bigsheeper** [comment]
would be fixed by #8050

**Comment by yanliang567** [comment]
@bigsheeper any updates?

**Comment by czs007** [comment]
@yanliang567
