### ISSUE TITLE
Monitor configuration file url is broken

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#750]
**Describe the bug**
https://www.milvus.io/docs/en/userguide/monitor/
https://www.milvus.io/docs/zh-CN/userguide/monitor/
```
设置 Prometheus

    下载 Milvus Prometheus 配置文件 。
```

The link url is broken
**Steps/Code to reproduce behavior**

**Expected behavior**

**Environment details**

**Screenshots**

**Additional context**

**Comment by jielinxu** [comment]
Fixed in the docs.
