### ISSUE TITLE
panic: Invalid argument: end key comes before start key

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus#7506]
This morning I tried to insert some data, everything was ok. 

In the afternoon, I find the server is crashed.  
I did nothing during the time. 
Here is my log. 

Server: milvusdb/milvus:v2.0.0-rc5-hotfix1-20210901-9e0b2cc

[2021/09/06 08:59:43.738 +00:00] [DEBUG] [rocksmq_retention.go:353] ["In expiredCleanUp: "] [topic=car_search_427467498275209217_0] [endID=0] [deletedAckedSize=0]
panic: Invalid argument: end key comes before start key

goroutine 135 [running]:
github.com/milvus-io/milvus/internal/util/rocksmq/server/rocksmq.(*retentionInfo).retention.func1(0x2264640, 0xc000253640, 0x2263b40, 0xc000a711b8, 0x0)
	/go/src/github.com/milvus-io/milvus/internal/util/rocksmq/server/rocksmq/rocksmq_retention.go:269 +0xb9
sync.(*Map).Range(0xc00054d258, 0xc0049bdf08)
	/usr/local/go/src/sync/map.go:345 +0x1d9
github.com/milvus-io/milvus/internal/util/rocksmq/server/rocksmq.(*retentionInfo).retention(0xc00054d1e0, 0xc0003ac2af, 0xe)
	/go/src/github.com/milvus-io/milvus/internal/util/rocksmq/server/rocksmq/rocksmq_retention.go:265 +0x13e
created by github.com/milvus-io/milvus/internal/util/rocksmq/server/rocksmq.(*retentionInfo).startRetentionInfo
	/go/src/github.com/milvus-io/milvus/internal/util/rocksmq/server/rocksmq/rocksmq_retention.go:121 +0x11e

[standalone.log.zip](https://github.com/milvus-io/milvus/files/7114725/standalone.log.zip)

**Comment by fishpenguin** [comment]
This is a rocksmq retention bug, and already fixed in latest master branch and will be released in RC6.
