### ISSUE TITLE
Need a script to check if Apache license exists in go files

### ISSUE THREAD

**Issue by DragonDriver** [milvus-io/milvus#7507]
#### What would you like to be added:

I want to add a script to check if Apache license exists in all go files. Meanwhile, using this script as a GitHub action would be better.

By the way, a script that automatically add milvus license to go files would also be very nice.

#### Why is this needed:

Decrease the time that developers add Apache license to newer added files.

**Comment by shanghaikid** [comment]
https://github.com/google/addlicense

**Comment by ashish-patwal** [comment]
Hey @DragonDriver , just wanted to ask should i add the shell script to github actions ,  as you mentioned in the issue ?
