### ISSUE TITLE
Change the monitor description about Prometheus

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#753]
**Describe the bug**
https://www.milvus.io/docs/en/userguide/monitor/

```
Milvus uses Prometheus, an open source time series database, to store and monitor its metrics
```
Prometheus is monitoring and alerting toolkit

**Steps/Code to reproduce behavior**

**Expected behavior**

**Environment details**

**Screenshots**

**Additional context**

**Comment by jielinxu** [comment]
Fixed in the docs
