### ISSUE TITLE
[benchmark] create a large number of growing segments, memory will run out quickly

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#7543]
#### Steps/Code to reproduce:
creating a large number of growing segments by 
1. keeping inserting a small numbers(10) of entities 
2. and keeping flush(get num_entities) frequently

#### Expected result:
Memory will not rise abnormally and overflow

#### Actual results:
memory run out quickly.

#### Analysis:
the growing segment will still pre-allocate the size of a chunk. If the vector is 128-dimensional, the pre-allocated space is about 16M, so every flush consumes 16M memory and the total memory will run out quickly.

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):9e0b2cc
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc6.dev4
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by cydrain** [comment]
After change size_per_chunk_ from 16M to 256K, run Milvus standalone locally, memory usage increases 2.5G in 24 minutes.

**Comment by cydrain** [comment]
#7635 is to support set segcore chunk_size via config file.

Will reduce chunk_size in another PR.

**Comment by wangting0128** [comment]
@xige-16 
hi, when will the final plan for this be available?

**Comment by yanliang567** [comment]
after discussion, there is not a perfect solution right now... will have a completed fix in 2.0 GA

**Comment by xige-16** [comment]
After milvus supports handoff, we'll retest this case
