### ISSUE TITLE
Can you show me Milvus Meta Schema and description？

### ISSUE THREAD

**Issue by YUANJASON** [milvus-io/milvus#755]
Can you show me Milvus Meta Schema and description？

**Comment by yhmo** [comment]
We will add meta schema into milvus documentation(https://milvus.io/docs) later. 
![tables_schema](https://user-images.githubusercontent.com/2282099/70610580-c8c31680-1c3e-11ea-8b06-a13b129bd967.png)
![tablefiles_schema](https://user-images.githubusercontent.com/2282099/70610596-d1b3e800-1c3e-11ea-8955-ce7638cae3bc.png)
