### ISSUE TITLE
Request more docs about Troubleshoot in UserGuide

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#756]
Server issue
  1. Update description in https://www.milvus.io/docs/zh-CN/userguide/troubleshoot/:
  "服务器" to "服务"
  2. Add server operational issue:

  1) Connect issue:
     1. check expose port in `docker run`
     2. check server log

  2) Other operations
       Make sure the sdk-version and server-version is matched
       Check SDK readme, and status returned

**Comment by yhmo** [comment]
Issues that occur during the server operation. Issues of this type may or may not cause server down. Error messages are recorded in /home/$USER/<milvus>/logs.

The logs folder is different according to different situation. If milvus is started from docker, the default logs path is /var/lib/milvus/logs.  If milvus is started from compiled source code, the default logs path is /tmp/milvus/logs

**Comment by jielinxu** [comment]
Fixed in the 0.6.0 doc
