### ISSUE TITLE
create index failed

### ISSUE THREAD

**Issue by mayunjie** [milvus-io/milvus#7594]
#### Steps/Code to reproduce:
1、insert vector
2、create index

#### Expected result:
create success

#### Actual results:
1、low cpu load，nearly 1.0
2、create very slowly
3、uncomplete after 12 hour 

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): 1.1.1
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): Java v1.1.1
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 32 core/ 300G
- GPU: 
- Others: 

#### Configuration file:
1、Collection param： dimension=16384     metricType=HAMMING     index.file.size=10240
2、index param: nlist=16384    indexType=IVFLAT
3、data count = 4,000,000

#### Additional context:
docker image: 1.1.2-cpu-rc

**Comment by yhmo** [comment]
Create index thread is blocked. The root cause is still in investigation.
The following script can reproduce this issue:

import random
import time
import threading
import numpy as np
from milvus import Milvus, IndexType
from milvus.client.types import MetricType

SERVER_ADDR = "127.0.0.1"
SERVER_PORT = '19530'
COLLECTION_NAME = "TEST"
COLLECTION_DIMENSION = 16384
COLLECTION_PARAM = {'collection_name': COLLECTION_NAME,
                    'dimension': COLLECTION_DIMENSION,
                    'index_file_size': 10240,
                    'metric_type':MetricType.HAMMING}
INDEX_TYPE = IndexType.IVF_FLAT
INDEX_PARAM = {'nlist': 16384}
NQ = 1
TOPK = 10
SEARCH_PARAM = {'nprobe': 16}

MILVUS = Milvus(host=SERVER_ADDR, port=SERVER_PORT)

def create_collection(name = COLLECTION_NAME):
    param = COLLECTION_PARAM
    param['collection_name'] = name
    status = MILVUS.create_collection(param)
    print("create", name)

def drop_collection(name = COLLECTION_NAME):
    status = MILVUS.drop_collection(collection_name=name)
    time.sleep(1)
    print("drop", name)

def get_collection_stats(name = COLLECTION_NAME):
    status, stat = MILVUS.get_collection_stats(collection_name=name)
    print(stat)

def create_index(name = COLLECTION_NAME):
    print("building index...")
    time_start = time.time()
    status = MILVUS.create_index(collection_name=name, index_type=INDEX_TYPE, params=INDEX_PARAM)
    time_end = time.time()
    print("build index", " time cost:", time_end - time_start, 'sec')

def drop_index(name = COLLECTION_NAME):
    MILVUS.drop_index(collection_name=name)
    print("drop_index", name)

def insert(name = COLLECTION_NAME):
    print("prepare insert")
    batch = 10000
    for i in range(400):
        vectors = gen_binary_vectors(batch)
        status, ids = MILVUS.insert(collection_name=name, records=vectors)
        print("insert", i, len(ids), status)
    MILVUS.flush(collection_name_array=[name])

def gen_binary_vectors(num, dim = COLLECTION_DIMENSION):
    print("generating binary vectors", "num=", num, "dim=", dim)
    binary_vectors = []
    raw_vector = [random.randint(0, 1) for i in range(dim + num)]
    for i in range(num):
        binary_vectors.append(bytes(np.packbits(raw_vector[num:dim+num], axis=-1).tolist()))
    return binary_vectors

if __name__ == "__main__":
    drop_collection()
    create_collection()
    insert()

    get_collection_stats()
    create_index()
    get_collection_stats()

**Comment by yhmo** [comment]
I set nlist=128, then it works well. 
I guess the build index algorithm run into dead circle when the nlist is too large.

**Comment by JackLCL** [comment]
@mayunjie
In "nlist = 4*sqrt(n)",  n is the number of vectors in a segment.

**Comment by mayunjie** [comment]
@JackLCL 
i set index_file_size = 10G, so a segment should have 500 million vectors.
Should i set index_file_size a small num?  I think this maybe lead to too many segment created

**Comment by JackLCL** [comment]
When you set the index_file_size smaller, the number of segments does increase, but the amount of data in each segment decreases. I'm not sure how it affects the overall search performance. You can do an experiment to test it.

**Comment by mayunjie** [comment]
And I think the actual problem is why CPU load is always low when create index, either 128 or 4096 or 16384.
Is this a normal phenomenon?

**Comment by yhmo** [comment]
This is my test result after running whole night:

```
building index... {'nlist': 128}
build index  time cost: 67.33702230453491 sec

building index... {'nlist': 256}
build index  time cost: 131.37729954719543 sec

building index... {'nlist': 512}
build index  time cost: 346.8158481121063 sec

building index... {'nlist': 768}
build index  time cost: 652.2407240867615 sec

building index... {'nlist': 1024}
build index  time cost: 1098.9840669631958 sec

building index... {'nlist': 1536}
build index  time cost: 2239.2903842926025 sec

building index... {'nlist': 2048}
build index  time cost: 3907.11416888237 sec

building index... {'nlist': 4096}
build index  time cost: 15120.309646844864 sec

```

**Comment by mayunjie** [comment]
@yhmo 
you cpu load is ?

**Comment by yhmo** [comment]
CPU load is low.
I think the parallel algorithm is not optimized for binary IVF index in the search engine, faiss level.

**Comment by mayunjie** [comment]
> 
> 
> CPU load is low.
> I think the parallel algorithm is not optimized for binary IVF index in the search engine, faiss level.

**Comment by mayunjie** [comment]
Can this be optimized?

**Comment by yhmo** [comment]
> Can this be optimized?

I think currently no resource to do this.

**Comment by mayunjie** [comment]
Has version2.0.0 optimized this?

**Comment by sloth2012** [comment]
Same issue with this

**Comment by yhmo** [comment]
> Has version2.0.0 optimized this?

No, 2.0 not optimize this. Currently for 2.0 the most important thing is stability issues.

**Comment by mayunjie** [comment]
> 
> 
> > Has version2.0.0 optimized this?
> 
> No, 2.0 not optimize this. Currently for 2.0 the most important thing is stability issues.

This is a very worse experience, Can you fix this issue after the stability issues
