### ISSUE TITLE
about server_config.yaml

### ISSUE THREAD

**Issue by mrright2019** [milvus-io/milvus#760]
This is mine server_config.yaml
`version: 0.1                        # config version

server_config:
  address: 0.0.0.0                  # milvus server ip address (IPv4)
  port: 19530                       # milvus server port, must in range [1025, 65534]
  deploy_mode: single               # deployment type: single, cluster_readonly, cluster_writable
  time_zone: UTC+8                  # time zone, must be in format: UTC+X

db_config:
  primary_path: /data/fideo_share/ml/searchData/milvus    # path used to store data and meta
  secondary_path:                   # path used to store data only, split by semicolon

  backend_url: sqlite://:@:/        # URI format: dialect://username:password@host:port/database
                                    # Keep 'dialect://:@:/', and replace other texts with real values
                                    # Replace 'dialect' with 'mysql' or 'sqlite'

  insert_buffer_size: 4             # GB, maximum insert buffer size allowed, must be a positive integer
                                    # sum of insert_buffer_size and cpu_cache_capacity cannot exceed total memory

  preload_table:                    # preload data at startup, '*' means load all tables, empty value means no preload
                                    # you can specify preload tables like this: table1,table2,table3

metric_config:
  enable_monitor: false             # enable monitoring or not, must be a boolean
  collector: prometheus             # prometheus
  prometheus_config:
    port: 8080                      # port prometheus uses to fetch metrics, must in range [1025, 65534]

cache_config:
  cpu_cache_capacity: 16            # GB, size of CPU memory used for cache, must be a positive integer
  cache_insert_data: false          # whether to load inserted data into cache, must be a boolean

engine_config:
  use_blas_threshold: 11000000000          # if nq <  use_blas_threshold, use SSE, faster with fluctuated response times
                                    # if nq >= use_blas_threshold, use OpenBlas, slower with stable response times
  gpu_search_threshold: 0        # threshold beyond which the search computation is executed on GPUs only

gpu_resource_config:
  enable: true                      # whether to enable GPU resources
  cache_capacity: 8                 # GB, size of GPU memory per card used for cache, must be a positive integer
  search_resources:                 # define the GPU devices used for search computation, must be in format gpux
      - gpu0
      - gpu1
      - gpu2
      - gpu6
  build_index_resources:            # define the GPU devices used for index building, must be in format gpux
      - gpu0
      - gpu1
      - gpu2
      - gpu6
`
When I search a query,It cost about 2 minute.How I fix it?

**Comment by mrright2019** [comment]
about 10000000 vectors

**Comment by JinHai-CN** [comment]
What is the dimension?

**Comment by mrright2019** [comment]
> What is the dimension?

512

**Comment by mrright2019** [comment]
> What is the dimension?

我想用gpu来运行，因为速度太慢了，我应该怎么配置

**Comment by JinHai-CN** [comment]
512 vector means 2KB size. 10000000 vectors means the total vector size is about 20GB. Which kind of index you are using?

**Comment by JinHai-CN** [comment]
> > What is the dimension?
> 
> 我想用gpu来运行，因为速度太慢了，我应该怎么配置

Normally, CPU cache size need to be larger than the total data size. Then, all data can be loaded into memory. It will make your query much more fast.

**Comment by mrright2019** [comment]
> 512 vector means 2KB size. 10000000 vectors means the total vector size is about 20GB. What kind of index you are using?

 
I haven't set the index yet. Which index is suitable?

**Comment by JinHai-CN** [comment]
If you haven't set any index, the raw data will be used to search. As I said, the total data size is about 20GB and your CPU cache size is 16GB. This will slow down your query. You need let the CPU cache size is larger than 20GB. We have written an article in Milvus WeChat Official Accounts to describe how to choose index. You may check it out.

**Comment by yhmo** [comment]
Firstly, change the cpu_cache_capacity to greater than data size(> 20GB), and restart milvus server again.
Secondly, you need to call create_index({'index_type': IndexType.IVF_SQ8, 'nlist': 16384})  from python sdk to create index. After index is created, the search performance will be much better.

**Comment by mrright2019** [comment]
> If you haven't set any index, the raw data will be used to search. As I said, the total data size is about 20GB and your CPU cache size is 16GB. This will slow down your query. You need let the CPU cache size is larger than 20GB. We have written an article in Milvus WeChat Official Accounts to describe how to choose index. You may check it out.

Thinks.It really is nice of you

**Comment by yhmo** [comment]
之前查询慢的原因应该是内存缓存设的不够大，导致数据文件反复从磁盘读进来导致的。 最好把cpu_cache_capacity设的比数据量大百分之二十这样吧。

关于gpu搜索的效率，请参考一下这篇文章：https://milvus.io/blog/2019/12/03/select-index
使用gpu查询的时候，不一定会比cpu快，因为目前数据没有常驻显存，每次查询时会把数据从内存拷进显存，有效率损失，我们后面会做优化。在nq（查询的目标向量条数）比较小的时候，gpu不比cpu快，而当nq超过一定值之后，gpu就明显比cpu快了

**Comment by mrright2019** [comment]
> Firstly, change the cpu_cache_capacity to greater than data size(> 20GB), and restart milvus server again.
> Secondly, you need to call create_index({'index_type': IndexType.IVF_SQ8, 'nlist': 16384}) from python sdk to create index. After index is created, the search performance will be much better.

When I set  CPU cache as 80G.It cost about 1-2 seconds.But,after create_index({'index_type': IndexType.IVF_SQ8, 'nlist': 16384}).It cost about 8 seconds.

**Comment by mrright2019** [comment]
> 之前查询慢的原因应该是内存缓存设的不够大，导致数据文件反复从磁盘读进来导致的。 最好把cpu_cache_capacity设的比数据量大百分之二十这样吧。
> 
> 关于gpu搜索的效率，请参考一下这篇文章：https://milvus.io/blog/2019/12/03/select-index
> 使用gpu查询的时候，不一定会比cpu快，因为目前数据没有常驻显存，每次查询时会把数据从内存拷进显存，有效率损失，我们后面会做优化。在nq（查询的目标向量条数）比较小的时候，gpu不比cpu快，而当nq超过一定值之后，gpu就明显比cpu快了

我这种场景下，要求实时返回，gpu_search_threshold应该设置多少合适

**Comment by yhmo** [comment]
你的nq一般是多少？查询参数的nprobe以及topk是多少？

**Comment by mrright2019** [comment]
nprobe:16,topK:1000-2000,nq我也不知道什么值合适

**Comment by yhmo** [comment]
gpu_search_threshold这个值的意思是： 当nq小于这个值时，使用cpu搜索； 而当nq大于这个值时，使用gpu搜索。
你试一下把gpu_search_threshold设为500， 然后用nq=499搜，看看cpu执行的速度；然后再用nq=501搜，看看gpu执行的速度

**Comment by yhmo** [comment]
我们自己的机器上两张2080的显卡上跑5000万128维度的向量查询平均是在0.5秒左右。你的向量维度是多少？

**Comment by mrright2019** [comment]
> gpu_search_threshold这个值的意思是： 当nq小于这个值时，使用cpu搜索； 而当nq大于这个值时，使用gpu搜索。
> 你试一下把gpu_search_threshold设为500， 然后用nq=499搜，看看cpu执行的速度；然后再用nq=501搜，看看gpu执行的速度

谢谢，我用nq=1100,gpu_search_threshold=1000，速度优化到了0.2s。再次感谢前辈！

**Comment by mrright2019** [comment]
> 我们自己的机器上两张2080的显卡上跑5000万128维度的向量查询平均是在0.5秒左右。你的向量维度是多少？

有两个，512维和72维

**Comment by yhmo** [comment]
之前跑出8秒那次，有可能是因为gpu建索引还没完成之前有搜索请求进来，gpu正在建索引任务，搜索任务就会等待。

**Comment by mrright2019** [comment]
> 之前跑出8秒那次，有可能是因为gpu建索引还没完成之前有搜索请求进来，gpu正在建索引任务，搜索任务就会等待。

如果要阅读该项目的源码，有什么好的建议吗

**Comment by cydrain** [comment]
Suggest read these articles first in the official website: https://medium.com/unstructured-data-service
