### ISSUE TITLE
ERROR: Milvus server fail to load config file

### ISSUE THREAD

**Issue by LilySys** [milvus-io/milvus#765]
Welcome to Milvus!
Milvus Release version: v0.6.0, built at 2019-12-06 08:56.57, with OpenBLAS library.
You are using Milvus CPU edition
Last commit id: 2b40ddbb277e06e03a3a85a29b07cd1225538e48

Loading configuration from: ../conf/server_config.yaml
Initializing log config from: ../conf/log_config.conf
Config file not exist: ../conf/server_config.yaml
ERROR: Milvus server fail to load config file
Milvus server exit...

**Comment by yamasite** [comment]
If you used the following command to get the server config file:

```shell
$ wget https://raw.githubusercontent.com/milvus-io/docs/master/assets/server_config_cpu.yaml
```
Please change the filename to `server_config.yaml`. Otherwise, Milvus server cannot find the config file. This is missing in our current documentation. Feel free to let us know if you have other questions.

**Comment by LilySys** [comment]
thank you, the problem is solved.

**Comment by LiangXD** [comment]
how to solve this problem？
