### ISSUE TITLE
milvus.client.exceptions.NotConnectError: Fail connecting to server on 127.0.0.1:19530. Timeout

### ISSUE THREAD

**Issue by LilySys** [milvus-io/milvus#766]
**Describe the bug**
When i run the python exampler program, i got the problem as follows:
Traceback (most recent call last):
  File "/home/lily/anaconda3/lib/python3.6/site-packages/milvus/client/grpc_client.py", line 199, in connect
    grpc.channel_ready_future(self._channel).result(timeout=timeout)
  File "/home/lily/anaconda3/lib/python3.6/site-packages/grpc/_utilities.py", line 140, in result
    self._block(timeout)
  File "/home/lily/anaconda3/lib/python3.6/site-packages/grpc/_utilities.py", line 86, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 118, in <module>
    main()
  File "example.py", line 27, in main
    status = milvus.connect(**param)
  File "/home/lily/anaconda3/lib/python3.6/site-packages/milvus/client/grpc_client.py", line 203, in connect
    raise NotConnectError('Fail connecting to server on {}. Timeout'.format(self._uri))
milvus.client.exceptions.NotConnectError: Fail connecting to server on 127.0.0.1:19530. Timeout

**Environment details**
- ubuntu16.04 
- Method of installation:Docker cpu
- Milvus version (v0.6.0)

**Additional context**
when i run "dockers log", it shows that the milvus server started successfully.

Welcome to Milvus!
Milvus Release version: v0.6.0, built at 2019-12-06 08:56.57, with OpenBLAS library.
You are using Milvus CPU edition
Last commit id: 2b40ddbb277e06e03a3a85a29b07cd1225538e48

Loading configuration from: ../conf/server_config.yaml
Initializing log config from: ../conf/log_config.conf
Milvus server started successfully!

**Comment by LilySys** [comment]
i use the python3.6

**Comment by yamasite** [comment]
Could you please let us know your pymilvus version?

**Comment by yhmo** [comment]
Firstly, make sure docker port is mapping correctly  "docker run -p 19530:19530 ......." 
Secondly, make sure pymilvus version is 0.2.6 (pip3 install pymilvus==0.2.6)

**Comment by LilySys** [comment]
(一)The container informations as follow:
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                                              NAMES
c688aac6dcb7        milvusdb/milvus:cpu-latest   "/var/lib/milvus/doc…"   2 hours ago         Up 2 hours          0.0.0.0:8080->8080/tcp, 0.0.0.0:19530->19530/tcp   milvus_cpu
(二)The pymilvus version as follows:
       pymilvus                           0.2.6

**Comment by BossZou** [comment]
Do milvus docker and example program run in the same host machine? And the example program run in host machine or docker inside?

**Comment by LilySys** [comment]
milvus docker and example program in the same host machine.
the example program run  in host machine.

**Comment by BossZou** [comment]
Hello, I tried in my host machine and all run well. Would you like apply more information to help me solve this issue ? Please check if port is already in use in host machine by running cmd `netstat -ap | grep 19530` or `lsof -i:19530`?

**Comment by yhmo** [comment]
This issue is resolved from private channel. It is not a milvus bug.

**Comment by EUCHI1996** [comment]
Hello,

Please what is the solution of this problem ?

**Comment by parthplc** [comment]
In my case it was caused due full diskspace
