### ISSUE TITLE
MYSQL and boost error

### ISSUE THREAD

**Issue by LilySys** [milvus-io/milvus#767]
**Describe the bug**
when i run the command "./build.sh -t Debug", i got two problem as follows:
(一)
./lib/options.cpp: In member function ‘virtual mysqlpp::Option::Error mysqlpp::SecureAuthOption::set(mysqlpp::DBDriver*)’:
./lib/options.cpp:265:20: error: ‘MYSQL_SECURE_AUTH’ was not declared in this scope
    dbd->set_option(MYSQL_SECURE_AUTH, &arg_) ?
(二)
root/milvus/core/src/index/thirdparty/SPTAG/AnnService/inc/Helper/ConcurrentSet.h:8:28: fatal error: shared_mutex.hpp: No such file or directory

**Environment details**
- centos7.6 teslaT4  Driver Version: 418.67  CUDA Version: 10.1
- Method of installation (from source)
- Milvus version (v0.3.1, or v0.4.0)
- i do not change the server_config.yaml

**Comment by LilySys** [comment]
milvus version: .. (full: '0.6.0')

**Comment by JinHai-CN** [comment]
You may follow the link: https://github.com/milvus-io/milvus/blob/master/install.md#compile-milvus-on-docker and use docker to compile Milvus.

**Comment by yhmo** [comment]
This issue depend on #768
