### ISSUE TITLE
Memory consumption keeps high even after workload off for hours

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#7690]
#### Steps/Code to reproduce:
1. deploy Milvus 2.0 cluster
2. insert 10M entities, index, load and keep search for a few mins

#### Expected result:
After workload off, memory consumption shall get down

#### Actual results:
Memory keeps high even after workload off for a few(8+) hours

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): master-20210908-3c2821e
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):

#### Additional context:
<img width="1154" alt="Screen Shot 2021-09-10 at 11 01 50 AM" src="https://user-images.githubusercontent.com/82361606/132792692-34904ede-3d49-4ede-bc38-87bf4de28df1.png">

**Comment by congqixia** [comment]
@yanliang567 are collections released after workload?

**Comment by yanliang567** [comment]
collections were dropped.

**Comment by xiaofan-luan** [comment]
can we still reproduce after go version increase?

**Comment by yanliang567** [comment]
keep it for tracking

**Comment by czs007** [comment]
Still keep it for tracking？ @yanliang567
