### ISSUE TITLE
Implement a restful API server for milvus

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#7700]
#### What would you like to be added:

A restful API is an architectural style for an application to access and use data through http requests. The data can be used to GET,PUT,POST and DELTE data types, which refers to the reading, updating, creating and deleting of operations concerning resources. 

Milvus 1.1 used to support restful API, we've also seen many other search engines such as elastic search and solr supports both http and rpc requests. It would be much easier for applications written in language such as PHP and rust to use http to utilize milvus.

#### Why is this needed:

Implement a http server on proxy module, serves http request and convert to same request type as grpc request

**Comment by matrixji** [comment]
Typo in title, `restul` should be `restful`, maybe `RESTful` is more accuracy.

**Comment by parshnt** [comment]
hi @xiaofan-luan, I would like to work on the feature. can you assign it to me.

**Comment by xiaofan-luan** [comment]
Welcome  to the community parshnt! you may want to write some MEP before start coding and we can have a deep discussion on techmeeting, see previous enhancement plan at https://wiki.lfaidata.foundation/pages/viewpage.action?pageId=43287103

**Comment by xiaofan-luan** [comment]
Anyone wanna to join parshnt is also welcomed~

**Comment by ArkaprabhaChakraborty** [comment]
Yes I want to join him too.

**Comment by xiaofan-luan** [comment]
> Yes I want to join him too.

Welcome Arkaprabha!^_^

**Comment by ArkaprabhaChakraborty** [comment]
So any idea how do we start @parshnt ? Is there any IRC or slack channel that we can join to discuss our workflow?

**Comment by parshnt** [comment]
+1 to what @ArkaprabhaChakraborty asked

**Comment by yhmo** [comment]
@ArkaprabhaChakraborty  @parshnt
Create a raw design document in [MEP](https://wiki.lfaidata.foundation/pages/viewpage.action?pageId=43287103) is a good start.
The title can be: **MEP 15 -- Support RESTful API for Milvus**

**Comment by xiaofan-luan** [comment]
@parshnt @ArkaprabhaChakraborty any updates dude?

**Comment by ArkaprabhaChakraborty** [comment]
Well, I didn't know how to start as I didn't get any headstart from the other contributor.

**Comment by haorenfsa** [comment]
Just made a start: [MEP 20 -- Support RESTful API for Milvus](https://wiki.lfaidata.foundation/display/MIL/MEP+20+--+Support+RESTful+API+for+Milvus)

**Comment by yhmo** [comment]
Note: There are still dozen of stability/critical issues blocking GA release, adding restful server may bring impact to GA release work. Currently pending this task, will restart after GA successfully release.

**Comment by xiaofan-luan** [comment]
hi @haorenfsa ,do you want to setup some discussion about the restful API implementation?

**Comment by xiaofan-luan** [comment]
@DragonDriver please help on the MEP review

**Comment by haorenfsa** [comment]
> hi @haorenfsa ,do you want to setup some discussion about the restful API implementation?

for now I can think of 2 things we need to decide:
- Which HTTP framework will we be using?
- Shall we add `db_name` in the URI path?

**Comment by xiaofan-luan** [comment]
> > hi @haorenfsa ,do you want to setup some discussion about the restful API implementation?
> 
> for now I can think of 2 things we need to decide:
> 
> * Which HTTP framework will we be using?
> * Shall we add `db_name` in the URI path?

thought there is a duplicated issue of this one https://github.com/milvus-io/milvus/issues/15200, ask anosh to join the team and we can build it together.

for the two questions：
1. I would recommend to use FastAPI as the framework, since the milvus bootcamp repo is already using FastAPI
2. we may want to support namespace in the nearest future, so better to think of how to make this extendable

**Comment by xiaofan-luan** [comment]
We should take a discussion on next techmeeting, @haorenfsa wanna to give a 10 minutes quick talk about the plan? [next meeting will be on Feb. 16th, 2022](https://wiki.lfaidata.foundation/pages/viewpage.action?pageId=43287098)

**Comment by haorenfsa** [comment]
> We should take a discussion on next techmeeting, @haorenfsa wanna to give a 10 minutes quick talk about the plan? [next meeting will be on Feb. 16th, 2022](https://wiki.lfaidata.foundation/pages/viewpage.action?pageId=43287098)

sure, glad to.

**Comment by haorenfsa** [comment]
Anyone willing to contributing to this issue is welcomed to join our [slack channel](https://app.slack.com/client/TM98LD8DQ/C032WUEDNSF/thread/C032WUEDNSF-1644824306.745679)
we'll talk about details there @parshnt

**Comment by haorenfsa** [comment]
The design can be found in [MEP 20 -- Support RESTful API for Milvus](https://wiki.lfaidata.foundation/display/MIL/MEP+20+--+Support+RESTful+API+for+Milvus)

**Comment by kish5432** [comment]
HI Team,

We have created a user('sample_rw') assigned to a role(sample_rw) in database 'sample_db' and granted below privileges.
User 'sample_rw' is able to insert the records into a collection through python SDK. But when the user tried to insert with RESTful API he is getting permission denied issue.But same time restapi is working fine with root user.
Please check and help

>>> role.list_grants(db_name="sample_db")
GrantInfo groups:
- GrantItem: <object:Collection>, <object_name:*>, <db_name:sample_db>, <role_name:sample_rw>, <grantor_name:root>, <privilege:*>
- GrantItem: <object:Global>, <object_name:*>, <db_name:sample_db>, <role_name:sample_rw>, <grantor_name:root>, <privilege:CreateCollection>
- GrantItem: <object:Global>, <object_name:*>, <db_name:sample_db>, <role_name:sample_rw>, <grantor_name:root>, <privilege:DescribeCollection>
- GrantItem: <object:Global>, <object_name:*>, <db_name:sample_db>, <role_name:sample_rw>, <grantor_name:root>, <privilege:DropCollection>
- GrantItem: <object:Global>, <object_name:*>, <db_name:sample_db>, <role_name:sample_rw>, <grantor_name:root>, <privilege:ManageOwnership>
- GrantItem: <object:Global>, <object_name:*>, <db_name:sample_db>, <role_name:sample_rw>, <grantor_name:root>, <privilege:SelectOwnership>
- GrantItem: <object:Global>, <object_name:*>, <db_name:sample_db>, <role_name:sample_rw>, <grantor_name:root>, <privilege:ShowCollections>
>>> 


with user login details:
$ curl -X POST  -H "Authorization: Bearer xxxx:xxxxxx"  -H "accept: application/json"  -H "content-type: application/json"    https://xxxxxxxxxxx/v1/vector/insert  -d '{
  "dbName": "sample_db",
     "collectionName": "test_collection",
     "data": {
         "fv": [0.8571546620302857,0.9641475471462333,0.08567717313921608,0.13432940904698243,0.1890460289592979,0.7523212221534346,0.26457543815328943,0.906124520660575,0.6434270148074686,0.6919709380695496,0.08513712899210901,0.6955820429129014,0.19041700260526362,0.6868949148167189,0.5205770852693863,0.3408847441187388,0.4091818010219346,0.2867709952076234,0.45345894514323914,0.45336905561964924,0.05804026814011953,0.8282242635377253,0.9567584014499193,0.03433122119418708,0.009343980934914065,0.5159025856983694,0.07996005660684236,0.08795708740650099,0.730560985383037,0.9907083884410652,0.0706667101731997,0.29986365292925066,0.35151052808280236,0.36504725008299,0.5579956222062197,0.24986683407835852,0.4959885849799248,0.33282447803778537,0.6599896565310761,0.4196496711388049,0.8819083135456631,0.29362639854988615,0.1793261203122516,0.4105548932445513,0.5479233007479314,0.528065488880527,0.008021239843094552,0.19903549170951718,0.2579345046428181,0.08928041448086188,0.0843072241585272,0.11632753840531374,0.7396226772205095,0.7004215809843761,0.7012340713357124,0.11639977853092742,0.7924918405053252,0.6474386987142657,0.8580416091547161,0.4307054357279765,0.8151406521346829,0.27801978297732677,0.6867512726747023,0.696810764495065,0.1199584021692901,0.02246220833316337,0.08664096023786483,0.06787264466058729,0.7586542095398996,0.6124999893865388,0.8268544813293115,0.0660994532104986,0.4921222621278514,0.5565700397914162,0.7925275831431204,0.4402851109315238,0.5194617801730552,0.9850534239703279,0.5545234629572051,0.3325636559085685,0.5045594396023703,0.5852510043682908,0.6673969915777964,0.9584902275055907,0.5077708803445422,0.6208293336899937,0.08645987938846966,0.08172853110769007,0.0766928277083736,0.3001851195419942,0.43643464928171816,0.2659326081465676,0.2951735706272818,0.8554037611464511,0.433170795236578,0.9185500588386686,0.8849227909382855,0.5730070598015662,0.7003760055835375,0.666053836921161,0.4853969093158139,0.6465162575514416,0.2309551103378249,0.5241315479815563,0.8937782468208011,0.44465518892508205,0.7521438997182532,0.24189609880854612,0.4995511185889827,0.5298022952325463,0.8014062891798011,0.5862729384611438,0.18149870135598078,0.7642286400212697,0.35644897379556295,0.3962761152476162,0.4444430246758133,0.03779341145402593,0.19794741774832403,0.6586873026678575,0.30627165191351335,0.604523597390817,0.1540358009721583,0.5091227590918217,0.7770485150827673,0.772382677073479,0.22304871413462135,0.23085222008052586],
         "id": "101",
         "double": "0.7594569790709774"
     }
 }'
{"code":65535,"message":"rpc error: code = PermissionDenied desc = PrivilegeInsert: permission deny"}


with root login details:
$ curl -X POST  -H "Authorization: Bearer root:Milvus"  -H "accept: application/json"  -H "content-type: application/json"    https://xxxxxxxxxxxxxxx/v1/vector/insert  -d '{
  "dbName": "sample_db",
     "collectionName": "test_collection",
     "data": {
         "fv": [0.8571546620302857,0.9641475471462333,0.08567717313921608,0.13432940904698243,0.1890460289592979,0.7523212221534346,0.26457543815328943,0.906124520660575,0.6434270148074686,0.6919709380695496,0.08513712899210901,0.6955820429129014,0.19041700260526362,0.6868949148167189,0.5205770852693863,0.3408847441187388,0.4091818010219346,0.2867709952076234,0.45345894514323914,0.45336905561964924,0.05804026814011953,0.8282242635377253,0.9567584014499193,0.03433122119418708,0.009343980934914065,0.5159025856983694,0.07996005660684236,0.08795708740650099,0.730560985383037,0.9907083884410652,0.0706667101731997,0.29986365292925066,0.35151052808280236,0.36504725008299,0.5579956222062197,0.24986683407835852,0.4959885849799248,0.33282447803778537,0.6599896565310761,0.4196496711388049,0.8819083135456631,0.29362639854988615,0.1793261203122516,0.4105548932445513,0.5479233007479314,0.528065488880527,0.008021239843094552,0.19903549170951718,0.2579345046428181,0.08928041448086188,0.0843072241585272,0.11632753840531374,0.7396226772205095,0.7004215809843761,0.7012340713357124,0.11639977853092742,0.7924918405053252,0.6474386987142657,0.8580416091547161,0.4307054357279765,0.8151406521346829,0.27801978297732677,0.6867512726747023,0.696810764495065,0.1199584021692901,0.02246220833316337,0.08664096023786483,0.06787264466058729,0.7586542095398996,0.6124999893865388,0.8268544813293115,0.0660994532104986,0.4921222621278514,0.5565700397914162,0.7925275831431204,0.4402851109315238,0.5194617801730552,0.9850534239703279,0.5545234629572051,0.3325636559085685,0.5045594396023703,0.5852510043682908,0.6673969915777964,0.9584902275055907,0.5077708803445422,0.6208293336899937,0.08645987938846966,0.08172853110769007,0.0766928277083736,0.3001851195419942,0.43643464928171816,0.2659326081465676,0.2951735706272818,0.8554037611464511,0.433170795236578,0.9185500588386686,0.8849227909382855,0.5730070598015662,0.7003760055835375,0.666053836921161,0.4853969093158139,0.6465162575514416,0.2309551103378249,0.5241315479815563,0.8937782468208011,0.44465518892508205,0.7521438997182532,0.24189609880854612,0.4995511185889827,0.5298022952325463,0.8014062891798011,0.5862729384611438,0.18149870135598078,0.7642286400212697,0.35644897379556295,0.3962761152476162,0.4444430246758133,0.03779341145402593,0.19794741774832403,0.6586873026678575,0.30627165191351335,0.604523597390817,0.1540358009721583,0.5091227590918217,0.7770485150827673,0.772382677073479,0.22304871413462135,0.23085222008052586],
         "id": "101",
         "double": "0.7594569790709774"
     }
 }'
{"code":200,"data":{"insertCount":1,"insertIds":[101]}}

Thanks
