### ISSUE TITLE
Compile && Run Milvus across multiple platforms

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#7706]
#### What would you like to be added:

Milvus is designed to run at any language, any environment. However, due to some high performance lib dependencies, Milvus failed to compile and run on macOS and windows environments and for now only ubuntu and centos is supported

Please help us on compiling milvus and run on different runtime environments (any environment except for linux server counts, such as mac laptop, windows laptop, android mobile device).

#### Why is this needed:
If Milvus can be built and run on mac and windows, it will greatly simplified current development process. Also, it will could support more users in need

**Comment by matrixji** [comment]
Currently working on compiling/running with Windows(MSYS), maybe later try with macOS (Apple Silicon)
/assign @matrixji

**Comment by xiaofan-luan** [comment]
@matrixji how is it going? any help wanted?

**Comment by matrixji** [comment]
> @matrixji how is it going? any help wanted?

Compiling on windows is done locally, but this whole change is pretty LARGE, so I'd like to split it with several PRs for review. like first part #7853 
Meanwhile, I still have not finished hello_milvus with milvus.exe under Windows, so I'm using my branch [windows-dev](https://github.com/matrixji/milvus/tree/windows-dev) to keep rebase from `milvus:master` for local investigation.

**Comment by xiaofan-luan** [comment]
> Status sync up:
> 
> * Now tested success with hello_milvus under windows (standalone mode) locally, whole changes:  [windows-dev](https://github.com/matrixji/milvus/tree/windows-dev), including 4 commits.
> * 3 related PRs are raised [Improvements: Some adaptation for gcc-10. #7853](https://github.com/milvus-io/milvus/pull/7853) [Support windows compilations #9105](https://github.com/milvus-io/milvus/pull/9105) [Support windows compilations #9106](https://github.com/milvus-io/milvus/pull/9106), the final commit has a dependency on them.
> 
> Continue work:
> 
> * How to create a release artifact for windows, maybe a zip file including minio.exe etcd.exe
> * Some guidance for how to start the windows-based milvus.
> 
> Do we need an MEP to track?

Hey matrixji, sorry for the late reply~ how is the current progress? 
We are thinking of building a windows ci pipiline for building milvus and runing the test cases through, do you think we are ready for this?

**Comment by matrixji** [comment]
> We are thinking of building a windows ci pipiline for building milvus and runing the test cases through, do you think we are ready for this?

3 related PRs for full compiling under windows are under review. #9105 #9106 #11388.
Currently, my personal [windows-dev branch](https://github.com/matrixji/milvus/tree/windows-dev) contains a GitHub action for compiling/package under windows/MSYS(Only compile and package, no Testing). IMO, for contributing this whole part, we have 2 options:
- Raise PR after the above-related changes Merged, as the whole makefile/build-scripts depends on the related code changes. Actually, I prefer this one.
- Raise a new PR including the whole change, but this will be more difficult for the reviewers.

For the testing pipeline, currently, I didn't have more investigations on Milvsus's test framework. I think your guys are more professional on it

**Comment by xiaofan-luan** [comment]
> * Raise PR after the above-related changes Merged, as the whole makefile/build-scripts depends on the related code changes. Actually, I prefer this one.

Sure, Let us review through all the related PRs one by one, once those are all in we can setup a CI pipeline to see if unit test/ integration test can be run under windows environemnt

**Comment by xiaofan-luan** [comment]
> * after the above-related changes Merged, as the whole makefile/build-scripts depends on the related code changes. Actually, I prefer this one.

I would also prefer the first choice, let's move in all the prs step by step, probably after 2.0-GA release thus it won't block current stability

**Comment by XuanYang-cn** [comment]
> > * after the above-related changes Merged, as the whole makefile/build-scripts depends on the related code changes. Actually, I prefer this one.
> 
> I would also prefer the first choice, let's move in all the prs step by step, probably after 2.0-GA release thus it won't block current stability

As @xiaofan-luan said, I'm delighted to review all the PRs of this issue after GA. Thanks for the patience again @matrixji

**Comment by MrRace** [comment]
@aakejiang  Does it  support android mobile device now？I would like to use a vector database in android mobile device
