### ISSUE TITLE
Add server build commit info interface

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#771]
**Is your feature request related to a problem? Please describe.**
Just as  `mode` command, `build_commit` is needed 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cydrain** [comment]
use in this way:
m._cmd("get_config *")  ==> to get all configurations
m._cmd("build_commit_id")  ==> to get build commit id

**Comment by cydrain** [comment]
done
