### ISSUE TITLE
Implement C++ SDK for milvus

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#7713]
**What would you like to be added:**
Create a C++ library so that C++ users can include the library into their project, to interact with milvus service.

**Why is this needed:**
Implement a C++ SDK for milvus v2.0

**Comment by xiaofan-luan** [comment]
@ArkaprabhaChakraborty hi @ArkaprabhaChakraborty , you are interested on this issue? let me assign to you

**Comment by ArkaprabhaChakraborty** [comment]
Yes I am. Where do I begin? Also I need to to learn about how to bring out milvus functionality into C++ so that I can make a header only library for it.

**Comment by xiaofan-luan** [comment]
> Yes I am. Where do I begin? Also I need to learn about how to bring out milvus functionality into C++ so that I can make a header only library for it.

Nice, I think there are two major reference, the first you want to check is python sdk user reference https://milvus.io/api-reference/pymilvus/v2.0.0rc6/install.html, c++ client should has similar functionalitites(But you may want to implement step by step).
Another good reference is milvus protobuf, all the server exposed interface is in the protobuf file, and you can generated c++ impl of the interface from the proto

**Comment by xiaofan-luan** [comment]
Create a raw design document in MEP is a good start.
The title can be: MEP 15 -- Support C++ SDK for Milvus

And you can join milvus slack to discuss: https://slack.milvus.io/

**Comment by xiaofan-luan** [comment]
@ArkaprabhaChakraborty  hi ark, any updates?

**Comment by ArkaprabhaChakraborty** [comment]
Not yet but I'm on it. Sorry for the delay I got busy with my exams :)
