### ISSUE TITLE
multi-thread concurrent search  very slow

### ISSUE THREAD

**Issue by white-source** [milvus-io/milvus#7731]
vector data: 30w , 64dim vectors;
docker: milvus:1.1.0-cpu-d050721-5e559c
environment: 24c，64G
request_parameters: nq=50,topK=50; cpu_cache=10G

abtest result:

1.   ab -n10000  -c 1   qps=50;
Concurrency Level:      1
Time taken for tests:   219.009 seconds
Complete requests:      10000
Failed requests:        5
   (Connect: 0, Receive: 0, Length: 5, Exceptions: 0)
Write errors:           0
Total transferred:      5990005 bytes
Total body sent:        1990000
HTML transferred:       4800005 bytes
Requests per second:    45.66 [#/sec] (mean)
Time per request:       21.901 [ms] (mean)
Time per request:       21.901 [ms] (mean, across all concurrent requests)
Transfer rate:          26.71 [Kbytes/sec] received
                        8.87 kb/s sent
                        35.58 kb/s total

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       0
Processing:    11   22  18.5     12     183
Waiting:       11   22  18.4     12     182
Total:         11   22  18.5     13     183

Percentage of the requests served within a certain time (ms)
  50%     13
  66%     18
  75%     25
  80%     30
  90%     47
  95%     62
  98%     79
  99%     92
 100%    183 (longest request)

2.  ab -n10000  -c 100 

Concurrency Level:      100
Time taken for tests:   211.492 seconds
Complete requests:      10000
Failed requests:        6
   (Connect: 0, Receive: 0, Length: 6, Exceptions: 0)
Write errors:           0
Total transferred:      5990006 bytes
Total body sent:        1990000
HTML transferred:       4800006 bytes
Requests per second:    47.28 [#/sec] (mean)
Time per request:       2114.920 [ms] (mean)
Time per request:       21.149 [ms] (mean, across all concurrent requests)
Transfer rate:          27.66 [Kbytes/sec] received
                        9.19 kb/s sent
                        36.85 kb/s total

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.2      0       3
Processing:    15 2103 305.2   2160    2617
Waiting:       12 2103 305.2   2160    2617
Total:         15 2103 305.1   2160    2617

Percentage of the requests served within a certain time (ms)
  50%   2160
  66%   2250
  75%   2296
  80%   2329
  90%   2397
  95%   2437
  98%   2481
  99%   2517
 100%   2617 (longest request)

3 if  just use cur test one time need 10~20ms

my god ,why it's so slow when qps is high?

**Comment by yhmo** [comment]
The milvus v1.x request execution machinery:
- Multi clients send parallel search requests to server, each client keep a rpc connection to server.
- Milvus server has a producer/consumer pipeline for search requests, we call it as request queue. Each rpc connection is a producer, they put search requests into the queue. There is only one consumer for the queue:  the database core.  The db core process search request one by one.
- After the db core take a search request, it firstly query the metadata service to know how many segments will be searched, then load these segments into memory/cache(if they are already in cache, nothing to do). Secondly, the search engine will use all cpu cores to do ANNS computation.
- After this request finished, the db core send back the results to its client. And takes next search request from the queue at the same time.

**Comment by yhmo** [comment]
Assume client A, B, C send search request at the same time with different search parameter. Milvus db core takes the request of A to process,  then the other two requests will have to wait in the queue. After A request is finish, let say, it cost 50ms, the client A say:" Well, my request cost 50ms". Then db core takes the request of B to process, cost 50ms. Since the client already wait 50ms(for A), totally it wait 100ms, it says:"Well, my request cost 100ms". The the C request is processed, the C totally wait 150ms. That is why some requests fast and some requests slow.

**Comment by yhmo** [comment]
Milvus can combine small(with small nq) search requests into a larger(with larger nq) request to execute. This behavior can improve the QPS.
There is a hidden config in the server_config.yaml for search combine:
```
engine_config:
  search_combine_nq: 64
```
That means milvus will combine small request into a larger request with nq no more than 64. Assume three requests come in at same time, with nq=10, nq=15, nq=20, milvus will combine them into a request with nq=45 to execute. The search engine can run more efficient with larger nq, so the time cost for nq=45 will less than execute nq=10, nq=15, nq=20 respectively. 

The default value of "search_combine_nq" is 64, you can change this value to observe the QPS.

**Comment by white-source** [comment]
Tanks
My problem is slovled.
Two step 
1 user collection.load() 
2 -e OMP_NUM_THREADS=11 
the total command is below
sudo docker run -d --name milvus_cpu_1.1.0 \
-p 19530:19530 \
-p 19121:19121 \
-e OMP_NUM_THREADS=11 \
-v /home/$USER/milvus/db:/var/lib/milvus/db \
-v /home/$USER/milvus/conf:/var/lib/milvus/conf \
-v /home/$USER/milvus/logs:/var/lib/milvus/logs \
-v /home/$USER/milvus/wal:/var/lib/milvus/wal \
milvusdb/milvus:1.1.0-cpu-d050721-5e559c

then abtest qps from 56  improve to 350

ps：
the gpu version is very slow when qps it high,so i  replace all the gpu version to cpu version.
now i user4 nodes  cluster that can support 1000qps.

Tanks,again.

**Comment by ucas010** [comment]
hi ,dear
what does it mean ?
-v /home/$USER/milvus/db:/var/lib/milvus/db
-v /home/$USER/milvus/conf:/var/lib/milvus/conf
-v /home/$USER/milvus/logs:/var/lib/milvus/logs
-v /home/$USER/milvus/wal:/var/lib/milvus/wal \

-v /home/** is what and the /var/** is what ?
thx
