### ISSUE TITLE
Insert 4096 dimensional vectors crash milvus

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#7741]
#### Steps/Code to reproduce:
1. create a collection
2. insert 4096 dim vectors continually, each time insert 500 ~ 1000 vectors

milvus crashed

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):  RC5-hotfix1
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: 

#### Additional context:
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.302 +00:00] [DEBUG] [segment.go:208] ["Proxy SegIDAssigner, pickCanDoFunc getAssign err:"] [collID=427624176252554561] [partitionID=427624176252554562] [channelName=first_model_427624176252554561_1_v] [error="can not find assign info with collID 427624176252554561, partitionID 427624176252554562, channelName first_model_427624176252554561_1_v"]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.302 +00:00] [DEBUG] [segment.go:224] ["Proxy SegIDAssigner pickCanDoFunc"] [records="{\"427624176252554561\":{\"427624176252554562\":{\"first_model_427624176252554561_1_v\":5}}}"] [len(newTodoReqs)=1] [len(CanDoReqs)=0]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.302 +00:00] [DEBUG] [segment.go:264] ["Proxy SegIDAssigner reduceSegReqs"] [len(segReqs)=1]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.302 +00:00] [DEBUG] [segment.go:294] ["Proxy SegIDAssigner reduceSegReqs after reduce"] [len(segReqs)=1] [BeforeCnt=5] [AfterCnt=5]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.302 +00:00] [DEBUG] [grpc_services.go:82] ["handle assign segment request"] [collectionID=427624176252554561] [partitionID=427624176252554562] [channelName=first_model_427624176252554561_1_v] [count=5]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.304 +00:00] [DEBUG] [grpc_services.go:106] ["Assign segment success"] [assignments="[{\"SegmentID\":427624204826050561,\"NumOfRows\":5,\"ExpireTime\":427624206241628164}]"]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.305 +00:00] [DEBUG] [segment.go:182] ["Proxy SegIDAssigner pickCanDoFunc"] [len(ToDoReqs)=1]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.305 +00:00] [DEBUG] [segment.go:224] ["Proxy SegIDAssigner pickCanDoFunc"] [records="{\"427624176252554561\":{\"427624176252554562\":{\"first_model_427624176252554561_1_v\":5}}}"] [len(newTodoReqs)=0] [len(CanDoReqs)=1]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.305 +00:00] [DEBUG] [task.go:844] [Proxy] ["repackFunc, reqSegCountMap, reqID"=427624176252407002] [mapinfo="{\"427624204826050561\":5}"]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.305 +00:00] [DEBUG] [task.go:896] [Proxy] ["threshold of message size: "=524288]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.306 +00:00] [DEBUG] [task_scheduler.go:238] ["Proxy DmTaskQueue popPChanStats"] [tID=427624176252407002]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.306 +00:00] [DEBUG] [impl.go:1187] ["Insert Done"] [] [role=Proxy-] [msgID=427624176252407002] [timestamp=0] [db=] [collection=first_model] [partition=_default] [len(RowData)=8] [len(RowIDs)=8]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.327 +00:00] [DEBUG] [id.go:145] ["IDAllocator pickCanDoFunc"] [need=1] [total=147550] [remainReqCnt=0]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.328 +00:00] [DEBUG] [impl.go:385] [DescribeCollection] [role=Proxy-] [msgID=427624176252407011] [timestamp=427624205730447362] [db=] [collection=first_model]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.329 +00:00] [DEBUG] [root_coord.go:1307] [DescribeCollection] [name=first_model] [msgID=427624176252407011]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.329 +00:00] [DEBUG] [root_coord.go:1327] ["DescribeCollection Success"] [name=first_model] [msgID=427624176252407011]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.329 +00:00] [DEBUG] [impl.go:392] ["DescribeCollection Done"] [] [role=Proxy-] [msgID=427624176252407011] [timestamp=427624205730447362] [db=] [collection=first_model]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.353 +00:00] [DEBUG] [impl.go:1176] [Insert] [role=Proxy-] [msgID=0] [timestamp=0] [db=] [collection=first_model] [partition=_default] [len(RowData)=0] [len(RowIDs)=0]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.354 +00:00] [DEBUG] [id.go:145] ["IDAllocator pickCanDoFunc"] [need=1] [total=147549] [remainReqCnt=0]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.354 +00:00] [DEBUG] [task.go:745] ["Proxy Insert PreExecute"] [collSchema="name:\"first_model\" description:\"collection description\" fields:<fieldID:100 name:\"id\" is_primary_key:true description:\"int64\" data_type:Int64 autoID:true > fields:<fieldID:101 name:\"embedding\" description:\"float vector\" data_type:FloatVector type_params:<key:\"dim\" value:\"4096\" > > fields:<fieldID:102 name:\"mdz_id\" description:\"int64\" data_type:Int64 > fields:<fieldID:103 name:\"page_number\" description:\"int64\" data_type:Int64 > fields:<fieldID:104 name:\"segment_coordinates\" description:\"float vector\" data_type:FloatVector type_params:<key:\"dim\" value:\"4\" > > fields:<fieldID:105 name:\"segment_id\" description:\"int64\" data_type:Int64 > fields:<fieldID:106 name:\"category_id\" description:\"int64\" data_type:Int64 > "]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.354 +00:00] [DEBUG] [id.go:145] ["IDAllocator pickCanDoFunc"] [need=11] [total=147548] [remainReqCnt=0]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.355 +00:00] [DEBUG] [task.go:564] ["Proxy, transform"] [ID=427624176252407012] [BlobLen=16440] [dTypes="[5,101,5,5,101,5,5]"]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.356 +00:00] [DEBUG] [task.go:792] ["_assignSemgentID, produceChannels:"] [Channels="[first_model_427624176252554561_0_v,first_model_427624176252554561_1_v]"]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.356 +00:00] [DEBUG] [segment.go:182] ["Proxy SegIDAssigner pickCanDoFunc"] [len(ToDoReqs)=1]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.356 +00:00] [DEBUG] [segment.go:208] ["Proxy SegIDAssigner, pickCanDoFunc getAssign err:"] [collID=427624176252554561] [partitionID=427624176252554562] [channelName=first_model_427624176252554561_0_v] [error="can not find assign info with collID 427624176252554561, partitionID 427624176252554562, channelName first_model_427624176252554561_0_v"]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.356 +00:00] [DEBUG] [segment.go:224] ["Proxy SegIDAssigner pickCanDoFunc"] [records="{\"427624176252554561\":{\"427624176252554562\":{\"first_model_427624176252554561_0_v\":5}}}"] [len(newTodoReqs)=1] [len(CanDoReqs)=0]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.356 +00:00] [DEBUG] [segment.go:264] ["Proxy SegIDAssigner reduceSegReqs"] [len(segReqs)=1]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.356 +00:00] [DEBUG] [segment.go:294] ["Proxy SegIDAssigner reduceSegReqs after reduce"] [len(segReqs)=1] [BeforeCnt=5] [AfterCnt=5]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.356 +00:00] [DEBUG] [grpc_services.go:82] ["handle assign segment request"] [collectionID=427624176252554561] [partitionID=427624176252554562] [channelName=first_model_427624176252554561_0_v] [count=5]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.358 +00:00] [DEBUG] [grpc_services.go:106] ["Assign segment success"] [assignments="[{\"SegmentID\":427624204983336961,\"NumOfRows\":5,\"ExpireTime\":427624206254735364}]"]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.358 +00:00] [DEBUG] [segment.go:182] ["Proxy SegIDAssigner pickCanDoFunc"] [len(ToDoReqs)=1]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.358 +00:00] [DEBUG] [segment.go:224] ["Proxy SegIDAssigner pickCanDoFunc"] [records="{\"427624176252554561\":{\"427624176252554562\":{\"first_model_427624176252554561_0_v\":5}}}"] [len(newTodoReqs)=0] [len(CanDoReqs)=1]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.358 +00:00] [DEBUG] [task.go:844] [Proxy] ["repackFunc, reqSegCountMap, reqID"=427624176252407012] [mapinfo="{\"427624204983336961\":5}"]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.359 +00:00] [DEBUG] [segment.go:182] ["Proxy SegIDAssigner pickCanDoFunc"] [len(ToDoReqs)=1]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.359 +00:00] [DEBUG] [segment.go:208] ["Proxy SegIDAssigner, pickCanDoFunc getAssign err:"] [collID=427624176252554561] [partitionID=427624176252554562] [channelName=first_model_427624176252554561_1_v] [error="can not find assign info with collID 427624176252554561, partitionID 427624176252554562, channelName first_model_427624176252554561_1_v"]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.359 +00:00] [DEBUG] [segment.go:224] ["Proxy SegIDAssigner pickCanDoFunc"] [records="{\"427624176252554561\":{\"427624176252554562\":{\"first_model_427624176252554561_1_v\":6}}}"] [len(newTodoReqs)=1] [len(CanDoReqs)=0]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.359 +00:00] [DEBUG] [segment.go:264] ["Proxy SegIDAssigner reduceSegReqs"] [len(segReqs)=1]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.359 +00:00] [DEBUG] [segment.go:294] ["Proxy SegIDAssigner reduceSegReqs after reduce"] [len(segReqs)=1] [BeforeCnt=6] [AfterCnt=6]
[32mmilvus-standalone |[0m [2021/09/10 06:54:48.359 +00:00] [DEBUG] [grpc_services.go:82] ["handle assign segment request"] [collectionID=427624176252554561] [partitionID=427624176252554562] [channelName=first_model_427624176252554561_1_v] [count=6]
[32mmilvus-standalone |[0m panic: runtime error: slice bounds out of range [::401852777] with length 268435456
[32mmilvus-standalone |[0m 
[32mmilvus-standalone |[0m goroutine 1779 [running]:
[32mmilvus-standalone |[0m github.com/milvus-io/milvus/internal/storage.(*PayloadWriter).GetPayloadBufferFromWriter(0xc024ffa5d0, 0xc000000000, 0x0, 0x2478e0, 0xc02a279000, 0x7)
[32mmilvus-standalone |[0m 	/go/src/github.com/milvus-io/milvus/internal/storage/payload.go:388 +0xd2
[32mmilvus-standalone |[0m github.com/milvus-io/milvus/internal/storage.(*baseEventWriter).GetMemoryUsageInBytes(0xc0201ffbd0, 0x0, 0x0, 0x15)
[32mmilvus-standalone |[0m 	/go/src/github.com/milvus-io/milvus/internal/storage/event_writer.go:109 +0x3b
[32mmilvus-standalone |[0m github.com/milvus-io/milvus/internal/storage.(*baseEventWriter).Finish(0xc0201ffbd0, 0x0, 0x0)
[32mmilvus-standalone |[0m 	/go/src/github.com/milvus-io/milvus/internal/storage/event_writer.go:140 +0x73
[32mmilvus-standalone |[0m github.com/milvus-io/milvus/internal/storage.(*baseBinlogWriter).Close(0xc024fd0180, 0xc037b44000, 0x5fcf000)
[32mmilvus-standalone |[0m 	/go/src/github.com/milvus-io/milvus/internal/storage/binlog_writer.go:109 +0x21b
[32mmilvus-standalone |[0m github.com/milvus-io/milvus/internal/storage.(*InsertCodec).Serialize(0xc024fe8f60, 0x5ef39ec32e70d42, 0x5ef39ec3c480001, 0xc00405e5a0, 0xc00405e5a0, 0x1, 0x18, 0xc00090ccc0, 0xc026bbe3e0, 0x40, ...)
[32mmilvus-standalone |[0m 	/go/src/github.com/milvus-io/milvus/internal/storage/data_codec.go:211 +0x35a
[32mmilvus-standalone |[0m github.com/milvus-io/milvus/internal/datanode.flushSegment(0xc01fd7f980, 0x5ef39ec3c480001, 0x5ef39ec32e70d42, 0x5ef39ec32e70d41, 0xc0004570c0, 0x2708280, 0xc0002af8c0, 0xc0257a2c60, 0x0, 0xc000457080, ...)
[32mmilvus-standalone |[0m 	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:659 +0x199
[32mmilvus-standalone |[0m github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate(0xc000457080, 0xc0258dcf60, 0x1, 0x1, 0x0, 0x0, 0x0)
[32mmilvus-standalone |[0m 	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:595 +0x6ed4
[32mmilvus-standalone |[0m github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start(0xc005713ce0, 0x26f7c40, 0xc0008ff340, 0xc003e4afd0)
[32mmilvus-standalone |[0m 	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:84 +0x13a
[32mmilvus-standalone |[0m created by github.com/milvus-io/milvus/internal/util/flowgraph.(*TimeTickedFlowGraph).Start
[32mmilvus-standalone |[0m 	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/flow_graph.go:76 +0xfe

**Comment by yhmo** [comment]
This script can reproduce the issue:

```
import random
import time

from pymilvus import (
    connections, list_collections,
    FieldSchema, CollectionSchema, DataType,
    Collection
)


def test():
    # create connection
    connections.connect()

    print(f"\nList collections...")
    print(list_collections())

    # create collection
    dim = 4096
    default_fields = [
        FieldSchema(name="count", dtype=DataType.INT64, is_primary=True),
        FieldSchema(name="random_value", dtype=DataType.DOUBLE),
        FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
    ]
    default_schema = CollectionSchema(fields=default_fields, description="test collection")

    print(f"\nCreate collection...")
    collection = Collection(name="hello_milvus", schema=default_schema)

    print(f"\nList collections...")
    print(list_collections())

    #  insert data
    nb = 1000
    vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
    for i in range(1000):
        print("insert no.", i)
        start = time.time()
        collection.insert(
            [
                [i for i in range(nb)],
                [float(random.randrange(-20, -10)) for _ in range(nb)],
                vectors
            ]
        )
        end = time.time()
        print("insert cost", end-start, "seconds")

    print(f"\nGet collection entities...")
    print(collection.num_entities)
   
test()
```

**Comment by XuanYang-cn** [comment]
## Why panic
```go
slice := (*[1 << 28]byte)(pointer)[:length:length]  
```

2 ^ 28 = 2 ^ 14 + 4096 (dim) * 4 (float 32)

So we at most support the 2^14 = 16384 num of rows for 4096 dim vectors 

## The real problem

Of course, we can just raise up the 2 ^ 28 to 2 ^ 32 or something, but this's not the real problem. 

The problem is the size of 32000 numOfRows vectors varies largely depending on the **Dimension** of the vectors. 

And vector dimension in [1, 32768], size of 32000 numOfRows:  [128KB, 4GB]

## Solution

32000 num of rows is not a good auto-flush threshold. We should consider the size of one vector.  

Flush for every 5MB for instance.

**Comment by yanliang567** [comment]
@binbinlv could you please help to check why ci does not meet this issue? I believe we tested a scenario with max_dim

**Comment by binbinlv** [comment]
@yanliang567  OK, working on it.

**Comment by binbinlv** [comment]
This case is triggered by two conditions:
1 big dim
2 insert N times ( Here N should be relatively larger):
[from my reproduce, milvus is restarted when inserting at 52nd time, 80th time, and 113rd time. And after 3 times' restart, then milvus is crashed and could not be connected showing "Fail connecting to server on"]

And in our CI/Nightly CI tests, "max_dim" insert scenario is only covered by "test_search_max_dim" which will insert data with dim = 32768, and then search. However, this case only insert once because it is search related case which focusing more on the search results when dim is large.

in insert related case, we have case "test_insert_multi_times" which covering the multiple times' insert, but here are some restrictions:
(1) the insert times is about 20-30, and it is not large enough to trigger this issue.
(2) and all the dim is default as 128, no case about large dim in insert test files.

Solution:
So suggest 
(1) add more dim value combination at case "test_insert_multi_times" in "test_insert_20.py" file.
(2) increase the insert times in this case.
