### ISSUE TITLE
When pchannel consists of multiple vchannels, MsgPositions should also become multiple in one msgpack

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#7742]
Because msgpacks contain pchannel information not vchannel information.

This may trigger bugs, need to take special care when changing p:v from  1:1 to  1:n

**Comment by yanliang567** [comment]
@xiaofan-luan please take a look

**Comment by xiaofan-luan** [comment]
@XuanYang-cn Why msg pack contains pchannel? it should contains only vchannel infomation?

**Comment by xige-16** [comment]
Even if p:v is changed to 1:n, the msgpack of msgstream still contains the messages between two adjacent timetick msgs. Even if the flowgraph filters out some messages, the seek position is still valid.

**Comment by XuanYang-cn** [comment]
> @XuanYang-cn Why msg pack contains pchannel? it should contains only vchannel infomation?

I have no idea, but the position of a msgpack DOES contain pchannel info now. DataNode has to convert it into vchannel.

**Comment by XuanYang-cn** [comment]
> Even if p:v is changed to 1:n, the msgpack of msgstream still contains the messages between two adjacent timetick msgs. Even if the flowgraph filters out some messages, the seek position is still valid.

Seems right. 

In this case, the startPositions and the endPositions  of a msgpack shouldn't be a slice, since it only contains 1 startposition and 1 endposition for the pchannel.

**Comment by XuanYang-cn** [comment]
To sum up:

Which one SHOULD msgpack contain?  pchannel info or vchannel info ?
- If its pchannel info (As now):
1. p:v = 1: n doesn't influence the correctness of the positions (@xige-16 )
2. startPosition and endPosition shouldn't be slice, since there are one startPos and one endPos for a msgPack of a pchannel (@XuanYang-cn )

- If its vchannel info: (@xiaofan-luan )
Pub and sub need to be re-impl. It's msgstream that needs to filter vchannel data, it's vchannel that DataNode should sub. It's vchannel pos for msgPack to carry. And it's vchannel pos for DataNode to seek.

**Comment by xiaofan-luan** [comment]
> * It's msgstream that needs to filter vchannel data, it's vchannel that DataNode should sub. It's vchannel pos for msgPack to carry. And it's vchannel pos for DataNode to seek.

I prefer the second solution, how much effort we will have to pay to change the filter channel part? 
We should put vchannel info into each message and filter based on vchannel name

**Comment by xiaofan-luan** [comment]
@XuanYang-cn is this still a issue?

**Comment by XuanYang-cn** [comment]
NO, closing this Issue
