### ISSUE TITLE
Memory Leak on proxy task_scheduler

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#7769]
#### Steps/Code to reproduce:
We've seen a  searchResultBufFlags array in proxy task scheduler. 
It is never cleaned from the map so I guess there is a memory leak especially when search number is going up.

We need to check on how to fix it

#### Expected result:
Delete or clean it when necessary

**Comment by haorenfsa** [comment]
Maybe I can do this.
Will a proper expire time be enough, Like github.com/patrickmn/go-cache? 
@xiaofan-luan
