### ISSUE TITLE
Milvus stop searching with limit set to 1000

### ISSUE THREAD

**Issue by kevinzezel** [milvus-io/milvus#7771]
Hi,

Pymilvus freeze and stop searching with IVF FLAT with nlist=16384, nprob=2 or 4 or 8 or 16 ... any and limit 1000.  it is necessary to restart jupyter notebook kernel or python script.

if the limit is set to values much less than 1000, works normally.

```
emb = np.load('emb.npy')
emb_list = [list(i) for i in emb]

batch_size = 50
num = math.ceil(emb.shape[0]/batch_size)

nprobe = [2**i for i in range(1,15)]
bs = batch_size

final_milvus = {}
for n in nprobe:
    search_params = {"metric_type": "IP", "params": {"nprobe": n}}
    index_ordenado_milvus = []
    scores_milvus = []
    for i in range(bs):
        t = time.time()
        res = collection.search(emb_list[i*num:i*num+num], "embedding", search_params, num_top,None)
        for j in range(len(res)):
            indexes_milvus.append(np.array(res[j].ids))
            scores_milvus.append(res[j].distances) 
       
    indexes_milvus = np.vstack(indexes_milvus)
    scores_milvus = np.vstack(scores_milvus)
    
    final_milvus[f'nprobe_{n}'] = {
        'indexes_milvus':indexes_milvus,
        'scores_milvus':scores_milvus,
    }
```

#### Environment:
Milvus version: v2.0.0-RC5
Deployment mode: standalone
SDK version: pymilvus v2.0.0rc4
OS: Ubuntu 18.04.1-64 Minimal for Bare Metal
CPU/Memory: 2x 2.2GHz Intel Xeon-Broadwell (E5-2650-V4)/ 756gb ram
GPU: 2x NVIDIA Tesla-V100-PCIe-32GB
Others: IBM Bare Metal
Docker image Ubuntu 20.04 and Python 3.8.10

**Comment by xiaofan-luan** [comment]
ehh, do you have any exceptions or server logs for further investigation?

**Comment by yanliang567** [comment]
@zhuwenxing could you please help to reproduce it on latest build?

**Comment by zhuwenxing** [comment]
> @zhuwenxing could you please help to reproduce it on latest build?

👌

**Comment by kevinzezel** [comment]
I updated to version rc6 and it worked perfectly. It seems to be something with the rc5 version.

Thanks in advance

**Comment by kevinzezel** [comment]
> ehh, do you have any exceptions or server logs for further investigation?

I couldn't find the error in the docker logs.

**Comment by yanliang567** [comment]
@kevinzezel do you mind closing this issue as it is working on rc6?

**Comment by kevinzezel** [comment]
Yes!! Thanks in advance
