### ISSUE TITLE
Insert 5w entities 24 times,  but get 1,198,820 entities

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus#7778]
![image](https://user-images.githubusercontent.com/185051/133019287-a40cbfd5-3ed9-4c8a-8a31-a6e1fa99b142.png)

#### Steps/Code to reproduce:
1. start rc6
2. create a collection called `car_search2` with shema
```
id: int64
vector: float_vector
brand: int64
color: int64
```
3.  open milvus_cli(pymilvus_rc5)
   a. connect
   b. import vectors.csv -c car_search2
   c. repeat 24 times 

#### Expected result:
get 120w entities

#### Actual results:
get 1,198,820 entities

#### Environment:
- milvusdb/milvus:v2.0.0-rc6-20210910-020f109
- macbook pro 15

#### Configuration file:
Default

Here is the log

[standalone.log.zip](https://github.com/milvus-io/milvus/files/7151169/standalone.log.zip)

**Comment by shanghaikid** [comment]
If something wrong happened during inserting, what's the stratgy to  handle this. 
1. remove inserted data ?
2. keep inserted data ?

**Comment by yanliang567** [comment]
I think this is a known issue to us.
@congqixia could you please take a look?
