### ISSUE TITLE
No ci-passed rules for go files changed with [skip ci]

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#7788]
Adding or changing comment in go files with `[skip ci]` will not have `ci-passed` label

**Comment by yanliang567** [comment]
any changes in go files shall NOT skip ci, this is expected.   
whats your expectation?

**Comment by congqixia** [comment]
> any changes in go files shall NOT skip ci, this is expected.
> whats your expectation?

If that's the case, [skip ci] format shall not work when any go file has been changed.

**Comment by yanliang567** [comment]
> > any changes in go files shall NOT skip ci, this is expected.
> > whats your expectation?
> 
> If that's the case, [skip ci] format shall not work when any go file has been changed.

that's what we want.:)
