### ISSUE TITLE
Confusing error message returned in search_vectors

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#779]
**Describe the bug**

If partition tag set empty string, the message returned should be 
```
  reason: "Invalid partition tag:  Partition tag should not be empty."
```

```
Search failed:
status {
  error_code: ILLEGAL_ARGUMENT
  reason: "Invalid partition tag: . Partition tag should not be empty."
}

```

**Steps/Code to reproduce behavior**

**Expected behavior**

**Environment details**

**Screenshots**

**Additional context**

**Comment by scsven** [comment]
Not activity, close
