### ISSUE TITLE
Create index failed with type: sq8h on GPU-version

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#780]
**Describe the bug**
create index failed with message:
```
Unsupported index type: 5
```

**Steps/Code to reproduce behavior**
create index with type: sq8h 

**Expected behavior**

**Environment details**
using
**master branch**
GPU-version

**Screenshots**

**Additional context**

**Comment by BossZou** [comment]
Can you supply more information to help us solve this issue?

**Comment by ZhifengZhang-CN** [comment]
Fixed
