### ISSUE TITLE
Searched entity number is smaller than limit under multiple replica env

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#7803]
#### Steps/Code to reproduce:
1 Deploy multiple replica env: proxy= 2, queryNode = 2, indexNode = 2, dataNode = 2
```
helm install
                             --set proxy.replicas=2 \
                             --set queryNode.replicas=2 \
                             --set indexNode.replicas=2 \
                             --set dataNode.replicas=2 \
```

2 Run test case:
test_search_20.py::TestCollectionSearch::test_search_before_after_delete

3 Server logs:
[log.tar.zip](https://github.com/milvus-io/milvus/files/7152717/log.tar.zip)

#### Expected result:
limit(topK) searched is  equal with expected

#### Actual results:
limit(topK) searched (999) is not equal with expected (1000)

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):  e2c15d5
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
pymilvus 2.0.0rc6.dev11 and pymilvus 2.0.0rc7.dev1
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by yanliang567** [comment]
@bigsheeper any updates ?

**Comment by bigsheeper** [comment]
> @bigsheeper any updates ?

find nothing from the log, I'm trying to repro

**Comment by bigsheeper** [comment]
> @bigsheeper any updates ?

find nothing from the log, I'm trying to repro

**Comment by bigsheeper** [comment]
Repro on my localhost, after adding some logs I found that query nodes have been returned 1000 results to proxy, so I guess the global reducing causes this bug. @DragonDriver

**Comment by DragonDriver** [comment]
working on this

**Comment by DragonDriver** [comment]
Proxy reduce algorithm caused this issue. I will fix this soon.

**Comment by DragonDriver** [comment]
Already fixed. Appreciate your efforts for finding this issue. @binbinlv

**Comment by binbinlv** [comment]
@DragonDriver  OK,  I will verify it later, thanks for your great effort on fixing this.

**Comment by binbinlv** [comment]
Verified, and fixed.

Milvus: b2e8ba7
pymilvus: 2.0.0rc7.dev11
