### ISSUE TITLE
Request a method to get `index building` and `file merging` status

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#781]
**Is your feature request related to a problem? Please describe.**
User can not get the `file merging or index building` status, except to query meta data.
Can we provide the method to get the background server status, it will be helpful

**Describe the solution you'd like**
A command interface may be a solution

**Describe alternatives you've considered**

**Additional context**

**Comment by JinHai-CN** [comment]
We need to get the milvus status.

**Comment by scsven** [comment]
Index building status implemented in #3546
