### ISSUE TITLE
When load() is in progress, `get_loading_progress` shows 0

### ISSUE THREAD

**Issue by jaelgu** [milvus-io/milvus#7870]
#### Steps/Code to reproduce:
1. Prepare: have a collection with data large enough so that load() will take a while
2. Case 1:
    a. **DON'T call `num_entities`**: Call `load()`
    b. **While load() is still in progress**: Call `get_loading_progress` 
    result --> {'total_rows': 0, 'indexed_rows': 100000000}
    expect: total_rows = 100000000
3. Case 2:
    a. **DON'T call `num_entities`**: Call `load()`
    b. **While load() is still in progress**: Call `num_entities` 
    result 1 --> sift100m data & cluster: hangs
    result 2 --> sift10m data & standalone: good
    expect: should return correct num_entities anyway

#### Environment:
- Milvus version: v2.0.0-RC6
- Deployment mode: standalone/cluster
- SDK version: pymilvus v2.0.0rc6
- OS: Ubuntu/CentOS
- CPU/Memory: 
- GPU: N/A
- Others:

**Comment by DragonDriver** [comment]
sorry, but the loading state of collection can be only 0 or 100. 0 means loading is in progress, 100 means loading done.

we will support loading progress soon in later versions.

/assign @xige-16

**Comment by jaelgu** [comment]
@xige-16 how about case2 mentioned above?

**Comment by DragonDriver** [comment]
`num_entities` will call `flush`and we will wait for `flush` done, seems that `flush` cost a lot of time.

**Comment by shanghaikid** [comment]
> sorry, but the loading state of collection can be only 0 or 100. 0 means loading is in progress, 100 means loading done.
> 
> we will support loading progress soon in later versions.
> 
> /assign @xige-16

That makes no sense. why do you name  this function `get_loading_progress` if you don't provide any progress at all.
