### ISSUE TITLE
one set of external dependent service shall support multipe milvus instances

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#7905]
#### Is your feature request related to a problem? Please describe:
yes. I deployed one set of external dependent service: external-minio, external-pulsar and external-etcd, when deploying 2 Milvus instances that depends on the set of service, both Milvus services do not work as expected.

#### Describe the solution you'd like:

1. Multiple Milvus instances are able to run on the same set of external services.
2. Data of different Milvus instances shall be isolated by different rootPaths, buckets and channels.
3. rootPaths, buckets and channels shall be customized by users

#### the current situation we have:
1. bucket is available to configure in milvus-helm  values.yml
2. rootPaths is not available in helm configuration, has to be changed in milvus.config.milvus.yaml
3. channels is not available neither in helm configurations nor in milvus.advance.channel.yaml

**Comment by yanliang567** [comment]
@ThreadDao please help to verify after pr merged

**Comment by xiaofan-luan** [comment]
We are almost there, just need to fix some unit test issue

**Comment by xiaofan-luan** [comment]
To enable multi milvus cluster on single pulsar,etcd,minio
Check the following configuration

1. msg.chanNamePrefix.cluster : default value is by-dev
2. etcd.rootPath: default value is by-dev
3. minio.bucketname : default value is a-bucket

let me know if it could work or not @ThreadDao

**Comment by xiaofan-luan** [comment]
we can work on verifying this

**Comment by xiaofan-luan** [comment]
@ThreadDao

**Comment by ThreadDao** [comment]
It works. I verified on Milvus `master-20210928-ed4421d`. So close this issue fitst.
