### ISSUE TITLE
Search result wrong when filtering with expression using non-zero bool field 

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#7910]
#### Steps/Code to reproduce:
```python
from pymilvus import CollectionSchema, FieldSchema
from pymilvus import Collection
from pymilvus import connections
from pymilvus import DataType
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
bool_field = FieldSchema(name="bool", dtype=DataType.BOOL)
dim = 128
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
schema = CollectionSchema(fields=[int64_field, bool_field, float_vector])
connections.connect()
import numpy as np
collection = Collection("test_search_collection_binbin_6", schema=schema)
nb = 20
nq = 2
limit = 10
import random
default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
bool_array = [np.bool(i) for i in range(nb)]
res = collection.insert([[i for i in range(nb)], bool_array, vectors])
collection.load()
res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "bool == True")
```

#### Expected result:
0 == false, non-zero == true

#### Actual results:
Here if bool is non-zero, it returns the entities which the bool field is "false".
```
>>> bool_array
[False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True]
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "bool == 1")
>>> res[0].ids
[2, 7, 19, 13, 10, 9, 15, 5, 1, 12]
>>>
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "bool == 0")
>>> res[0].ids
[0]
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "bool == 2")
>>>
>>> res[0].ids
[0]
res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "bool == -1")
>>> res[0].ids
[0]
```

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): latest
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
pymilvus 2.0.0rc7.dev2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by fishpenguin** [comment]
Fixed by [pr7814](https://github.com/milvus-io/milvus/pull/7814).

**Comment by binbinlv** [comment]
@fishpenguin  hello, I think this issue could not fixed by pr7814. 

Now the bool expression could be supported using "bool == True" or "bool == 1".

But if specifying "bool == 2" (non-zero), I think the behavior could be the same with "bool == 1", and now it is the same with "bool == 0" or "bool == False".

**Comment by binbinlv** [comment]
@fishpenguin hello, kun, any updates?

**Comment by xiaofan-luan** [comment]
Let's only support true&&false for now, any suggestions?

**Comment by binbinlv** [comment]
It is OK for me, just remind of the friendly error message for not-support types and values.

**Comment by fishpenguin** [comment]
OK for me.
> Let's only support true&&false for now, any suggestions?

@xiaofan-luan only "bool == true/false"? Shall we support "bool in [ true/false ]"?

**Comment by fishpenguin** [comment]
Should expr like "bool == 0/1" be supported?

**Comment by fishpenguin** [comment]
I think it's better to support "bool_field == true/false and 1/0".

**Comment by xiaofan-luan** [comment]
@scsven any comments? thought if we support number, then not support bool_field = -1 or bool_field > 2 might be a little confusing.

**Comment by xiaofan-luan** [comment]
bool in [ true/false ] support is ok, it‘s a sugar nice to have. I just changed the priority to backlog

**Comment by scsven** [comment]
> @scsven any comments? thought if we support number, then not support bool_field = -1 or bool_field > 2 might be a little confusing.

I think we should NOT support until it is REQUIRED in some cases.

**Comment by scsven** [comment]
Fixed. Please update your test cases.

/unassign @fishpenguin 
/assign @binbinlv

**Comment by binbinlv** [comment]
working.

**Comment by binbinlv** [comment]
Verified and fixed.
