### ISSUE TITLE
How is milvus compare to faisis of facebook?

### ISSUE THREAD

**Issue by zhanglistar** [milvus-io/milvus#792]
**What is your question?**
How is milvus compare to faisis of facebook?

**Comment by JinHai-CN** [comment]
Please access https://milvus.io/docs/en/aboutmilvus/vector_db/
In summary, Milvus is a server and faiss is just a library.

**Comment by yhmo** [comment]
Milvus is aim to AI research/product developers. You can regard it as a combination of "vector data management" + "computing resource scheduler" + "ANN library"(including faiss/sptag, more library will be integrated in future).
We will try our best to build Milvus to be an easy to use tool, with rich documentations,  lot of peripheral tools. For more information. please visit Milvus official website:https://milvus.io/

**Comment by JinHai-CN** [comment]
No further action.
