### ISSUE TITLE
install milvus 0.5.3 or other branchs

### ISSUE THREAD

**Issue by shiyu22** [milvus-io/milvus#795]
## Report incorrect documentation

**Location of incorrect documentation**
https://github.com/milvus-io/docs/blob/0.5.3/userguide/install_milvus.md

**Describe the problems or issues found in the documentation**
At 'Use Docker', it has wrong docker images tags and config file link in step 2/3/4.

**Suggested fix for documentation**
milvusdb/milvus:latest may change to milvusdb/milvus:0.5.3-d111319-75998b
...
and it has the same problem in other branchs.

**Comment by jielinxu** [comment]
Fixed in the 0.5.3 doc
