### ISSUE TITLE
Jenkins CI not stable

### ISSUE THREAD

**Issue by cydrain** [milvus-io/milvus#799]
Jenkins CI not stable, please check following CI run.
http://jenkins.milvus.io:18080/blue/organizations/jenkins/milvus-ci/detail/PR-794/3/pipeline/82/

2nd run and 3rd run are with identical code, but different result.

**Comment by ZhifengZhang-CN** [comment]
2nd run and 3rd run are not same pipeline

**Comment by ZhifengZhang-CN** [comment]
This is not a bug
