### ISSUE TITLE
Build index with CPU timeout

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#800]
**Describe the bug**
nb: 10000
dim: 128
index_type: IVF_PQ
timeout: 300s

**Steps/Code to reproduce behavior**

**Expected behavior**

**Environment details**
master-CPU-version

**Screenshots**

**Additional context**

**Comment by JinHai-CN** [comment]
Can reproduce it?

**Comment by del-zhenwu** [comment]
close
