### ISSUE TITLE
 How to modify the storage path of the index library db, milvus is the default？

### ISSUE THREAD

**Issue by hande6688** [milvus-io/milvus#8034]
Milvus just created the name of a collection and did not have the function of storing the index library path. It is inconvenient to find the location of the index library every time. Is there a solution?

**Comment by xiaofan-luan** [comment]
Hi Hande, I was a little confused, did you want to change index storage path or index library path milvus relies on?

**Comment by hande6688** [comment]
就是我们插入索引生成的索引文件

**Comment by hande6688** [comment]
@xiaofan-luan 改变索引库的存储路径
