### ISSUE TITLE
Test block in searching step when redeploy cluster using helm

### ISSUE THREAD

**Issue by JamCrash** [milvus-io/milvus#8109]
#### Steps/Code to reproduce:
ENV: Ubuntu20.04,  python3.8,  pymilvus==2.0.0rc6 and the latest milvus chart

Steps: 
1. First start a new minikube cluster
2. Install the cluster: helm install my-release milvus/milvus --set cluster.enabled=true --set etcd.persistence.annotations."helm\.sh/resource-policy"=keep --set minio.persistence.annotations."helm\.sh/resource-policy"=keep --set pulsarStandalone.persistence.annotations."helm\.sh/resource-policy"=keep
3. port-forward....
4. Test: python3 hello_milvus.py, at this time the test is ok
5. Uninstall the cluster: helm uninstall my-release
6. Wait a second, then using the command in step 2 to install again
7. port-forward...
8. Test again: python3 hello_milvus.py, at this time the test block, and this condition can reproduce stably in my environment

#### Expected result:
return searching result

#### Actual results:
block and do not time out or raise exception like this: 

List collections...
['hello_milvus']

Create collection...

List collections...
['hello_milvus']

Get collection entities...
9000

Create index...

load collection...

Search...

**Comment by JamCrash** [comment]
有人麻

**Comment by JamCrash** [comment]
Is there anyone could reproduce this problem?

**Comment by yanliang567** [comment]
trying to reproduce it

**Comment by yanliang567** [comment]
it repros to me as well, seems like a dup to #7313 
pods after uninstall and reinstall:
```
milvus-4f9c-datacoord-b45d6688-96r8b                  1/1     Running     0          3m10s
milvus-4f9c-datanode-7c5f5f76c-glm4p                  1/1     Running     0          3m10s
milvus-4f9c-etcd-0                                    1/1     Running     0          3m9s
milvus-4f9c-indexcoord-77d894dd79-z9fp4               1/1     Running     0          3m10s
milvus-4f9c-indexnode-77d9f85cc6-s4gd8                1/1     Running     0          3m9s
milvus-4f9c-minio-6d55d476dc-klg5q                    1/1     Running     0          3m10s
milvus-4f9c-proxy-547c4f5847-4lqjg                    1/1     Running     0          3m9s
milvus-4f9c-pulsar-579c7c68b5-9hqmf                   1/1     Running     0          3m9s
milvus-4f9c-querycoord-7868cc6d88-d77lt               1/1     Running     0          3m9s
milvus-4f9c-querynode-65c96c55f8-kkp6w                1/1     Running     0          3m9s
milvus-4f9c-rootcoord-84896cbf68-74zvh                1/1     Running     0          3m9s

```

**Comment by yanliang567** [comment]
@XuanYang-cn could you please take look at this issue?
Search hangs for previous created collection, and it searches successfully if creating a new collection

**Comment by JamCrash** [comment]
Does this problem solved?

**Comment by JamCrash** [comment]
Did this problem solved?

**Comment by JamCrash** [comment]
Has this problem been solved？

**Comment by XuanYang-cn** [comment]
/unstale

Not reproducing this either.

**Comment by XuanYang-cn** [comment]
Feel free to reopen this if the same issue occurs
