### ISSUE TITLE
milvus_load.py -n完成最后一批数据load时，程序没往下运行

### ISSUE THREAD

**Issue by LilySys** [milvus-io/milvus#811]
**Describe the bug**
milvus_load.py -n完成最后一批数据load时，程序没往下运行

**Steps/Code to reproduce behavior**
自己的数据集，维度256，数据集大小10093312
创建表和索引之后，加载10093312数据，加载完最后1个batch，大小为93312时，程序就没往下执行了。

**Environment details**
- linux  GPU：4*P4  显存：4*16
- docker-gpu
- V0.6.
- server_config.yaml
version: 0.1                        # config version
server_config:
  address: 0.0.0.0                  # milvus server ip address (IPv4)
  port: 19530                       # milvus server port, must in range [1025, 65534]
  deploy_mode: single               # deployment type: single, cluster_readonly, cluster_writable
  time_zone: UTC+8                  # time zone, must be in format: UTC+X

db_config:
  primary_path: /var/lib/milvus    # path used to store data and meta
  secondary_path:                   # path used to store data only, split by semicolon

  backend_url: sqlite://:@:/        # URI format: dialect://username:password@host:port/database
                                    # Keep 'dialect://:@:/', and replace other texts with real values
                                    # Replace 'dialect' with 'mysql' or 'sqlite'

  insert_buffer_size: 4             # GB, maximum insert buffer size allowed, must be a positive integer
                                    # sum of insert_buffer_size and cpu_cache_capacity cannot exceed total memory

  preload_table:                    # preload data at startup, '*' means load all tables, empty value means no preload
                                    # you can specify preload tables like this: table1,table2,table3

metric_config:
  enable_monitor: false             # enable monitoring or not, must be a boolean
  collector: prometheus             # prometheus
  prometheus_config:
    port: 8080                      # port prometheus uses to fetch metrics, must in range [1025, 65534]

cache_config:
  #cpu_cache_capacity: 16            # GB, size of CPU memory used for cache, must be a positive integer
  cpu_cache_capacity: 25             # GB, size of CPU memory used for cache, must be a positive integer
  cache_insert_data: false          # whether to load inserted data into cache, must be a boolean

engine_config:
  #use_blas_threshold: 1100          # if nq <  use_blas_threshold, use SSE, faster with fluctuated response times
  use_blas_threshold: 801          # if nq <  use_blas_threshold, use SSE, faster with fluctuated response times
                                    # if nq >= use_blas_threshold, use OpenBlas, slower with stable response times
  #gpu_search_threshold: 1000        # threshold beyond which the search computation is executed on GPUs only
  gpu_search_threshold: 1001        # threshold beyond which the search computation is executed on GPUs only

gpu_resource_config:
  enable: true                      # whether to enable GPU resources
  cache_capacity: 4                 # GB, size of GPU memory per card used for cache, must be a positive integer
  search_resources:                 # define the GPU devices used for search computation, must be in format gpux
    - gpu0
  build_index_resources:            # define the GPU devices used for index building, must be in format gpux
    - gpu0

**Comment by shiyu22** [comment]
We cannot reproduce this problem, you can check if your data is correct.
