### ISSUE TITLE
Development toolchains support centos-8

### ISSUE THREAD

**Issue by matrixji** [milvus-io/milvus#8110]

**Comment by xiaofan-luan** [comment]
That would be great! 
We do expect more info on compiling and run milvus on different enviorntment.

**Comment by matrixji** [comment]
> That would be great!
> We do expect more info on compiling and run milvus on different enviorntment.

Some other PRs ongoing has compiled and run with standalone success under windows/MSYS locally, but currently failed with hello-milvus. Seems support windows will be a long story.
