### ISSUE TITLE
Very high memory usage when amount of data is bigger than cache_size

### ISSUE THREAD

**Issue by piotr-jagiello** [milvus-io/milvus#8113]
After loading more data than configured cache_size, search requests cause very high memory usage, way higher than cache_size.

#### Steps/Code to reproduce:
Following code reproduces this result for me on a c5.9xlarge machine (72 GB of RAM).
cache_size:16GB
insert_buffer_size: 2GB
wal.enable: true
wal.buffer_size: 256MB

The following script creates a collection and an index (with index_file_size 4GB), inserts 10 million random vectors (1024 dimensions each), flushes and then performs searches until killed. (I know the searches will be very slow with this configuration, since total data size is around 40GB - but I'm only concerned about memory usage in this issue).

```
import milvus
import numpy as np

m = milvus.Milvus(host='localhost', port='19530')
param = {'collection_name':'test', 'dimension':1024, 'index_file_size':4096, 'metric_type':milvus.MetricType.L2}
m.create_collection(param)
m.create_index('test', milvus.IndexType.IVF_FLAT, {'nlist': 1024})

print("collection and index created!")

for i in range(10000):
    id_list = list(range(i*1000, (i+1)*1000))
    vectors = np.random.random((len(id_list), 1024)) * 2 - 1
    m.insert(collection_name='test', records=np.ndarray.tolist(vectors), ids=id_list)

print("vectors inserted!")

m.flush(['test'])
print("flushed")

while True:
    print("search request...")
    m.search('test', 1, [[0.5]*1024], params={'nprobe': 32})
```

#### Expected result:
Based on the comment linked below on a past issue that seemed similar, I expected the memory usage to not be significantly higher than cache_size + insert_buffer_size + 2 * index_file_size, so in this case 16GB + 2GB + 2*4GB = 26GB. 
https://github.com/milvus-io/milvus/issues/5636#issuecomment-855661469

#### Actual results:
Memory usage goes as high as 50GB, so almost double that.
(This is only memory usage of the milvus container, as shown by docker stats):
![milvus_mem](https://user-images.githubusercontent.com/78038159/133622425-12a702e8-8a51-4669-96ef-6e88bb405a7c.png)

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): Milvus 1.1.1
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 1.1.1
- OS(Ubuntu or CentOS): Docker container
- CPU/Memory: c5.9xlarge on AWS (36 VCPU, 72GB RAM)
- GPU: none
- Others: 

#### Configuration file:
```
version: 0.5

cluster:
  enable: false
  role: rw

general:
  timezone: UTC+8
  meta_uri: sqlite://:@:/

network: 
  bind.address: 0.0.0.0
  bind.port: 19530
  http.enable: true
  http.port: 19121

storage:
  path: /var/lib/milvus
  auto_flush_interval: 1

wal:
  enable: true
  recovery_error_ignore: false
  buffer_size: 256MB
  path: /var/lib/milvus/wal

cache:
  cache_size: 16GB
  insert_buffer_size: 2GB
  preload_collection:

gpu:
  enable: false
  cache_size: 1GB
  gpu_search_threshold: 1000
  search_devices:
    - gpu0
  build_index_devices:
    - gpu0

fpga:
   enable: false
   search_devices:
     - fpga0

logs:
  level: debug
  trace.enable: true
  path: /var/lib/milvus/logs
  max_log_file_size: 1024MB
  log_rotate_num: 0
  log_to_stdout: false
  log_to_file: true

metric:
  enable: false
  address: 127.0.0.1
  port: 9091

```

**Comment by yhmo** [comment]
Build index task also can cost memory. 
If you removed this line, how about the memory usage?
`m.create_index('test', milvus.IndexType.IVF_FLAT, {'nlist': 1024})`
