### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by mrright2019** [milvus-io/milvus#818]
启动的时候报错：
    __  _________ _   ____  ______    
   /  |/  /  _/ /| | / / / / / __/    
  / /|_/ // // /_| |/ / /_/ /\ \    
 /_/  /_/___/____/___/\____/___/     

Welcome to Milvus!
Milvus Debug version: v0.6.0, built at 2019-12-12 04:56.40, with OpenBLAS library.
You are using Milvus GPU edition
Last commit id: 47621f06fb5dd673dd5cb7a1f82276290712c6b9

Loading configuration from: ../conf/server_config.yaml
Initializing log config from: ../conf/log_config.conf
GPU resources ENABLED !
Error: failed to open database: locking protocol: locking protocol. Possible reason: the meta system does not work.
User defined signal 1
Milvus server is going to shutdown ...

**Comment by mrright2019** [comment]
我用 ./stop_server.sh 不起作用，
然后 我kill掉原本的线程就可以了

**Comment by yhmo** [comment]
当milvus内部正在做长时间的任务（比如建索引）时，用./stop_server.sh是没法立即停下来的，得等任务都完成才会退出。

**Comment by mrright2019** [comment]
> 当milvus内部正在做长时间的任务（比如建索引）时，用./stop_server.sh是没法立即停下来的，得等任务都完成才会退出。

直接kill掉进程会有什么问题吗

**Comment by yhmo** [comment]
直接kill掉也没问题的，相当于直接终止建索引的任务，下次milvus重启之后发现还有文件没有建索引，就会自动在后台建索引。

**Comment by mrright2019** [comment]
> 直接杀掉也没问题的，相当于直接终止建索引的任务，下次milvus重启之后发现文件没有建索引，就会自动在后台建索引。

可以在stop_server中直接杀死milvus的进程吗？如果不直接杀死 我再次运行start_server的时候启会动失败，而且他没有杀死进程缺输出success。总柑橘有点问题
