### ISSUE TITLE
Milvus latest version(340f92a) restart(reinstall) failed by docker-compose

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#8353]
#### Steps/Code to reproduce:
run github action [Deploy Test](https://github.com/milvus-io/milvus/actions/workflows/deploy-test.yaml)
The steps in reinstall script can be found in [deploy test README](https://github.com/milvus-io/milvus/blob/master/tests/python_client/deploy/README.md)
#### Expected result:
reinstall success

#### Actual results:
in the second deployment, when connect, raise exception `server is not healthy, please try again later`

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): `340f92a`
- Deployment mode(standalone or cluster): both
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc7.dev4
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 
- GPU: 
- Others: 

#### Additional context:

All the logs can be found here https://github.com/milvus-io/milvus/actions/runs/1263398107 in Artifacts

**Comment by yanliang567** [comment]
data persistence blocked, urgent

**Comment by czs007** [comment]
I tried it on the local machine and found that if milvus is not fully started after reinstalling, and pymilvus is triggered to do the operation at this time, the phenomenon of ·severe is not healthy· will appear. After a while, pymilvus tries again, and there is no problem.
@zhuwenxing

**Comment by czs007** [comment]
I used the method provided by @zhuwenxing  to reproduce it again on the local machine. The logic of waiting for the proxy in the python SDK startup phase is to retry 10 times and sleep for 1 second each time. If the state of the proxy is always unhealthy, an exception will be thrown.

**Comment by czs007** [comment]
please use latest pymilvus and retry @zhuwenxing

**Comment by zhuwenxing** [comment]
In deploy test GitHub action and local test, it behaves normally, so this issue can be closed
