### ISSUE TITLE
初始化docker失败

### ISSUE THREAD

**Issue by tianyunperfect** [milvus-io/milvus#836]
**Describe the bug**
使用官方教程，初始化docker失败，提示：
Error: failed to open database: unable to open database file: unable to open database file. Possible reason: the meta system does not work.

**Steps/Code to reproduce behavior**
docker run -d --name milvus_cpu -e "TZ=Asia/Shanghai" -p 19530:19530 -p 8080:8080 -v /home/$USER/milvus/db:/var/lib/milvus/db -v /home/$USER/milvus/conf:/var/lib/milvus/conf -v /home/$USER/milvus/logs:/var/lib/milvus/logs milvusdb/milvus:cpu-latest

**Expected behavior**
应该初始化成功，但是容器无法启动

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker,)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)
centos7
docker
milvus：0.6.0
配置文件使用的是github上提供的
wget https://raw.githubusercontent.com/milvus-io/docs/master/assets/server_config.yaml
wget https://raw.githubusercontent.com/milvus-io/docs/master/assets/config/log_config.conf

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
docker run命令后面的 “/home/$USER”，这个“$USER”换成你的用户名，要保证 /home/$USER 这个路径是一个存在的、可写的路径

**Comment by tianyunperfect** [comment]
> docker run命令后面的 “/home/$USER”，这个“$USER”换成你的用户名，要保证 /home/$USER 这个路径是一个存在的、可写的路径

这个我已经替换过了

**Comment by del-zhenwu** [comment]
Maybe duplicate with #642 @yhmo

**Comment by tianyunperfect** [comment]
> Maybe duplicate with #642 @yhmo

Hello, do you have any idea about how to solve the problem？

**Comment by del-zhenwu** [comment]
> > Maybe duplicate with #642 @yhmo
> 
> Hello, do you have any idea about how to solve the problem？
This issue happened with volume set NAS path, and I could not re-produce if docker volume set local disk path

**Comment by del-zhenwu** [comment]
> > Maybe duplicate with #642 @yhmo
> 
> Hello, do you have any idea about how to solve the problem？


This issue happened with volume set NAS path, and I could not re-produce if docker volume set local disk path

**Comment by yhmo** [comment]
先看一下/home/$USER/milvus/db 这个目录是否存在？如果存在的话，目录里是否有文件？

**Comment by tianyunperfect** [comment]
> 先看一下/home/$USER/milvus/db 这个目录是否存在？如果存在的话，目录里是否有文件？
> 
> Take a look at / home / $user / MILVUS / DB. Does this Directory Exist? If so, are there files in the directory?

这个目录是存在的，是一个docker自动创建的空的目录。

**Comment by yhmo** [comment]
这个目录里有没有一个叫meta.sqlite的文件？

**Comment by tianyunperfect** [comment]
> 这个目录里有没有一个叫meta.sqlite的文件？

没有，是空的目录

**Comment by yhmo** [comment]
感觉是没有权限往那个目录里写东西。你到命令行里进到/home/$USER/milvus 这个目录，执行  ls -lht 看一下目录信息

**Comment by tianyunperfect** [comment]
> 这个目录里有没有一个叫meta.sqlite的文件？

我又初始化了一次，这次把db的映射去掉了，然后报了一个新的错误：无法创建 /var/lib/milvus，可能server_config.yaml错误或者不存在，但是我用的官网的配置文件，打开后也是存在的，很诡异的问题啊，您有思路吗

**Comment by yhmo** [comment]
用最简易的方式启动看看：
docker run  -p 19530:19530 milvusdb/milvus:cpu-latest

**Comment by tianyunperfect** [comment]
> 用最简易的方式启动看看：
> docker run -p 19530:19530 milvusdb/milvus:cpu-latest

您好，最简易的方式都启动不来，错误是：无法创建/var/lib/milvus，可能server_config.yaml错误或者不存在，是我拉取的docker有问题吗？

**Comment by del-zhenwu** [comment]
"unable to open database file" in sqlite3, chown the db-path maybe effective:
check [https://stackoverflow.com/questions/7670289/sqlite3-operationalerror-unable-to-open-database-file]

**Comment by tianyunperfect** [comment]
> "unable to open database file" in sqlite3, chown the db-path maybe effective:
> check
> 
> ```
> https://stackoverflow.com/questions/7670289/sqlite3-operationalerror-unable-to-open-database-file
> ```

Hello. After initializing the docker container, no DB file was generated at all

**Comment by yhmo** [comment]
我拉了milvusdb/milvus:cpu-latest跑起来没出现问题，按理说这个镜像很多人都跑成功过，不应该是镜像的问题。你那边镜像启动后能否用docker exec -it xxx bash 进去看看/var/lib/ 这个目录有没有milvus文件夹

**Comment by tianyunperfect** [comment]
> 我拉了milvusdb/milvus:cpu-latest跑起来没出现问题，按理说这个镜像很多人都跑成功过，不应该是镜像的问题。你那边镜像启动后能否用docker exec -it xxx bash 进去看看/var/lib/ 这个目录有没有milvus文件夹。
> 在这个/var/lib/试着创建一个新文件夹看看有没有问题

我再试试定位一下问题，谢谢你了，目前容器启动不起来，所以也进不去

**Comment by yhmo** [comment]
如果找到问题的原因，可否告知我们？我们可能会把这个问题原因写进用户文档里

**Comment by tianyunperfect** [comment]
> 如果找到问题的原因，可否告知我们？我们可能会把这个问题原因写进用户文档里

你好，问题解决了，是权限问题，我手动创建了conf文件夹，然后logs和db文件夹是docker自动创建的，然后我发现这两个文件夹的创建者是root并且我不能修改权限，删除后手动创建logs和db文件夹就可以了。
另外，你刚说的那个最简单的方式  `docker run -p 19530:19530 milvusdb/milvus:cpu-latest `  ，这个好像因为没有配置文件还是启动不了。
最后，再次感谢！
