### ISSUE TITLE
milvus的一些功能

### ISSUE THREAD

**Issue by mrright2019** [milvus-io/milvus#837]
不知道是milvus在开发中还是文档我没找到
请问milvus有类似faiss的降维功能吗？还是说我只能事先降维 事后插入？

**Comment by jielinxu** [comment]
Milvus doesn't support pre-transforming of data. You need to reduce the number of dimensions before inserting the vectors.

**Comment by mrright2019** [comment]
> Milvus doesn't support pre-transforming of data. You need to reduce the number of dimensions before inserting the vectors.

Will these features be added in the future?

**Comment by yhmo** [comment]
Not yet in our plan. Could you log an issue to provide detail information about  the requirement?

**Comment by mrright2019** [comment]
> Not yet in our plan. Could you log an issue to provide detail information about the requirement?

当我使用google bert提取句向量，提取出来的是768维，但是如果直接用来做相似度有唯独爆炸的问题，能否向faiss一样自带降维的功能，或者是根据我当前的数据动态的降维（例如设置触发条件，在上一次降维后数据在原来的基础上又增加了10%，再执行一次降维）。

**Comment by yhmo** [comment]
这样的话，每降维一次，就要重建一次索引？

**Comment by mrright2019** [comment]
> 这样的话，每降维一次，就要重建一次索引？

那就想个算法来支持动态降维，插入时降维，即使不是最优解也无所谓，损失一点精度而已，但是总会有数据量越来越多导致之前降维的算子和后来降维的算法差异很大，得维持这两者变化不至于太大，不行就设置两个参数，动态降维，全量降维，全量降维的时候重建索引。我只是拍脑门想的。这方面我解除的不多。但是这是个从事机器学习领域相关人员经常会遇到的场景

**Comment by yhmo** [comment]
想对数据降维主要是出于节省存储空间的考虑对吧？

**Comment by mrright2019** [comment]
> 想对数据降维主要是出于节省存储空间的考虑对吧？

不是，当数据维度过大的时候，用距离度量无法判断他是否相似，因为相似不相似的结果相差不大

**Comment by Heisenberg-Y** [comment]
As far as I know, there are plenty of dimension reduction algorithms in machine learning like PCA, LDA and so on. Faiss only supports the PCA algorithm, which may not be effective to all kinds of data set. In my point of view, it's a better option to do the dimension reduction work with your favored algorithm before you add them into Milvus.

**Comment by mrright2019** [comment]
> As far as I know, there are plenty of dimension reduction algorithms in machine learning like PCA, LDA and so on. Faiss only supports the PCA algorithm, which may not be effective to all kinds of data set. In my point of view, it's a better option to do the dimension reduction work with your favored algorithm before you add them into Milvus.

If possible, we hope Milvus can add these functions in the future. Otherwise, the cost of maintaining the project is too high.
Just like elasticsearch.

**Comment by yhmo** [comment]
Dimensional reduction may involve user business logic.It should be a part of data preprocess. I have created issue #862 for vector data preprocess to track related requirements.
