### ISSUE TITLE
Data can't be restored if etcd is re-installed

### ISSUE THREAD

**Issue by jaelgu** [milvus-io/milvus#8379]
Steps:
1. Install Milvus cluster using k8s
2. Create a collection & insert data & create index
3. Delete etcd pod (k8s will create a new etcd instantly)
4. Test following operations once all pods are ready:
     - connections.connect, list_collection, has_collection: ok
     - num_entities, index_progress, load, search: all fail with error <BaseException: (code=1, message=server is not serving)>

Note:
After etcd is deleted, k8s creates a new etcd instantly. And rootcoord restarts twice.

Question:
- Should all other pods restart automatically if etcd is re-installed?
- Expect: data can be restored after etcd pod gets re-installed.

#### Environment:
- Milvus version: v2.0.0rc6
- Deployment mode: cluster
- SDK version: pymilvus v2.0.0rc6
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:

**Comment by yanliang567** [comment]
sounds like similar to #7306.
Answer to Q1, it is by design for now, a pod will restart itself if it failed to connect to etcd service
