### ISSUE TITLE
[Bug] DBImpl::DropPartition doesn't check the status

### ISSUE THREAD

**Issue by shengjh** [milvus-io/milvus#839]
**Describe the bug**
 There is a bug at DBImpl::DropPartition operation.
Full code is here. 
https://github.com/milvus-io/milvus/blob/b140d8259b115d04f228e5dd4f6c05f20c3e3562/core/src/db/DBImpl.cpp#L283-L292
**Steps/Code to reproduce behavior**
In this operation, Firstly delete partition table meta, as code 
`status = meta_ptr_->DropPartition(partition_name); `
Then, without check status, directly  delete table files.

**Expected behavior**
We should  check out the status.
@yhmo

**Comment by yhmo** [comment]
No need to check status

**Comment by JinHai-CN** [comment]
If drop partition failed, what milvus should do?
