### ISSUE TITLE
Need to optmize some import

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#8393]
#### What would you like to be added:
Using `import as` to avoid conflict

#### Why is this needed:
Using `import *` in python programs is considered a bad habit. The reason is:
1. Low code readability
2. Import all functions and classes may clash with other imports
3. ... and so on

**Comment by yanliang567** [comment]
@ThreadDao i think you are working on this issue, please help to close if it was done.

/assign @ThreadDao
