### ISSUE TITLE
[BUG] CI test always failed

### ISSUE THREAD

**Issue by JinHai-CN** [milvus-io/milvus#84]
**Describe the bug**
Now, each CI test triggered by PR never pass totally.

**Steps/Code to reproduce behavior**
Just issue a PR without 'skip ci' message

**Expected behavior**
Normally, all cases can pass now.

**Environment details**
CI environment

**Screenshots**
N/A

**Additional context**
N/A

**Comment by del-zhenwu** [comment]
close it
