### ISSUE TITLE
RESTful API documentation

### ISSUE THREAD

**Issue by roxima** [milvus-io/milvus#843]
**Describe the problems or issues found in the documentation**
[Comparison page](https://www.milvus.io/docs/en/reference/comparison/) states Milvus as supporting RESTful API. However, it is not documented in any way.

**Steps taken to search for needed documentation**
Searched the whole website and GitHub repository!

**Comment by jielinxu** [comment]
Hi @roxima 
We're optimizing the RESTful API at the moment, and the updated documentation will be published next week.

**Comment by roxima** [comment]
Great. Looking forward to it.
