### ISSUE TITLE
请问如何让id支持string类型？

### ISSUE THREAD

**Issue by tianyunperfect** [milvus-io/milvus#847]
**What is your question?**
我想让每一条向量对应一个字符串，检索的时候也能把这个字符串返回，faiss是支持自定义string ID的，我从milvus 的 java-sdk里面发现，自定义id只支持Long类型，请问怎么让它支持string类型呢？

**Comment by yhmo** [comment]
目前向量的id只能是64位整型。可以用一个额外的sql数据库来做一层映射，比如启动一个mysql服务，然后在里面建一张表，保存你需要的向量额外信息。从milvus查出结果后，用id在mysql里返回对应的额外信息。

**Comment by tianyunperfect** [comment]
> 目前向量的id只能是64位整型。可以用一个额外的sql数据库来做一层映射，比如启动一个mysql服务，然后在里面建一张表，保存你需要的向量额外信息。从milvus查出结果后，用id在mysql里返回对应的额外信息。
> 我们在考虑支持用户输入除了向量之外的额外信息，可以是多种类型的，目前还处于设计阶段，离上线还有一段较长的时间。

明白了，非常感谢！
