### ISSUE TITLE
Add ready-to-use config files to the Milvus repo for enhanced user experience

### ISSUE THREAD

**Issue by yamasite** [milvus-io/milvus#848]
### Is your feature request related to a problem? Please describe.
Currently, ready-to-use Milvus config files for Milvus installation are maintained by tech writers in the **milvus/docs** repo. These config files are manually edited from config file templates, which may be error-prone and time-consuming, with extra communication overhead between developers and tech writers.

Moreover, we have two server config files (for CPU version and GPU version) and the only difference lies in the value of `gpu_resource_config.enable`. In fact, one config file should be sufficient.

### Describe the solution you'd like
**Developers**
Developers can create and maintain ready-to-use Milvus config files in the **milvus** repo. We need two ready-to-use config files: `server_config.yaml` and `log_config.conf`, which can be positioned in a separate folder alongside the template config files.
**Tech Writers**
Tech writers will update the `wget` commands in the installation guide accordingly and remind users to change `gpu_resource_config.enable` to `true` before using the GPU-supported Milvus.

**Comment by cydrain** [comment]
done
