### ISSUE TITLE
BaseException: (code=1, message=getSegmentsOfCollection, err:rpc error: code = Canceled desc = grpc: the client connection is closing)

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#8521]
#### Steps/Code to reproduce:
Running L0 and L1 test cases on multiple replica env:
1 deploy multiple replica env: 
                               --set proxy.replicas=2 \
                               --set queryNode.replicas=2 \
                               --set indexNode.replicas=2 \
                               --set dataNode.replicas=2 \
2 Running L0 and L1 test cases

Logs is too big to upload, sent separately.

#### Expected result:
Test cases are executed successfully

#### Actual results:
Exception occurs

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): 52126f2
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc7.dev11
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by yanliang567** [comment]
is it related to #8400 ?

**Comment by binbinlv** [comment]
Maybe it is similar, but from the error message, it is a little different, so I open another issue to track this.

**Comment by XuanYang-cn** [comment]
**https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-8833/2/pipeline**

**Comment by XuanYang-cn** [comment]
see also #8824

**Comment by XuanYang-cn** [comment]
#8400 is the same reason as #8824

**Comment by zhuwenxing** [comment]
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-8820/2/pipeline

same error message

**Comment by XuanYang-cn** [comment]
reasons

The grpc connection failed between proxy and root, even though proxy reconnected to root soon, proxy still returns the error it received back to SDK, caused this error.

```
code=1, message=getSegmentsOfCollection, err:rpc error: code = Canceled desc = grpc: the client connection is closing
```

/unassign @sunby 
/assign @czs007

**Comment by binbinlv** [comment]
OK, working on verifying.

**Comment by binbinlv** [comment]
Similar issue appears again, see #8824.

**Comment by XuanYang-cn** [comment]
See #12307
