### ISSUE TITLE
query node exit

### ISSUE THREAD

**Issue by jilieryuyi** [milvus-io/milvus#8563]
#### Steps/Code to reproduce:
write and read at the same time

#### Expected result:
work normal

#### Actual results:
exit

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): v2.0.0-RC6
- Deployment mode(standalone or cluster): docker-compose cluster
- SDK version(e.g. pymilvus v2.0.0rc2): golang v2.0.0-alpha.2
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 40/128G
- GPU: 
- Others: 

#### Configuration file:
default config

#### Additional context:

Quit after working for a period of time, and cannot query normally after restarting, and it has been timed out
![微信图片_20210924094912](https://user-images.githubusercontent.com/2398119/134792845-37fddc01-b13c-45fc-9e61-815df3f82c67.png)

![微信图片_20210924094832](https://user-images.githubusercontent.com/2398119/134792848-c3809185-837a-473d-8ef6-4c3de7e1f126.png)

logs
[milvus_logs.zip](https://github.com/milvus-io/milvus/files/7230686/milvus_logs.zip)

**Comment by bigsheeper** [comment]
It seems not the full log of query node, missing the log of `querynode (1).log`, could you offer the full query node log?

**Comment by bigsheeper** [comment]
also missing the full querycoord log, how many times have you restarted the query node?

**Comment by yanliang567** [comment]
@jilieryuyi  could you please help to provide the logs we need above?

/assign @jilieryuyi

**Comment by congqixia** [comment]
@yanliang567 log files already sent to @bigsheeper

**Comment by bigsheeper** [comment]
From the log, I found there are too many segments are created. In milvus, a segment is created each time flush is called, and the minimum size of one segment is `DIM * 4 * 32768(see milvus/configs/advanced/query_node.yaml:segcore.chunkRows)` even though we only insert a few rows into segment. Query node OOM because load too many segments and beyond the memory limit, same as #6726.

**Comment by xiaofan-luan** [comment]
close because of duplication with #7543
