### ISSUE TITLE
For search function adding a precision control

### ISSUE THREAD

**Issue by elfisworking** [milvus-io/milvus#8573]
#### What would you like to be added:
for search function in pymilvus adding a parameter to implement a precision control , for example if parameter added "round_decimal" is 3 , the output will be 3.145 compared with current 3.14523432.
#### Why is this needed:
some precision is not necessary and in C++  float is 32bit while in python that is presented with 64bit. This difference would make precision loss.

**Comment by yanliang567** [comment]
@elfisworking i think you are working on this issue

/assign @elfisworking

**Comment by yanliang567** [comment]
close as testing work would be tracked in #9604
