### ISSUE TITLE
Support delete / update, attribute filtering and search by id

### ISSUE THREAD

**Issue by youny626** [milvus-io/milvus#861]
- Support delete and update operations
- Support attribute filtering
- Support search by user-provided id
- Support deduplication of user-provided id

Design doc:
https://docs.google.com/document/d/1CDKdTj_DnE90YaZrPgsMaphqOTkMdbKETNrsFKj_Bco/edit?usp=sharing

Related issues: #2, #124, #1084 , https://github.com/milvus-io/pymilvus/issues/113, https://github.com/milvus-io/milvus-sdk-java/issues/59

**Comment by cleomart** [comment]
Do you know when will the delete/update operation feature be implemented?

**Comment by yamasite** [comment]
@cleomart Milvus 0.7.0 will support this feature. Please stay tuned！

**Comment by cleomart** [comment]
@yamasite Do you have an approximate date of the release? Thank you in advance.

**Comment by yamasite** [comment]
@JinHai-CN Could you please help answer @cleomart 's question? Do we have an approximate date for Milvus 0.7.0 release?

**Comment by JinHai-CN** [comment]
We plan to Milvus 0.7.0 in the early of March.

**Comment by JinHai-CN** [comment]
Only DeleteByID, GetVectorByID and SearchByID can be supported in 0.7.0.

Filtering data would be another issue.

**Comment by scsven** [comment]
Implemented, close.
