### ISSUE TITLE
Provide interface/module for data preprocess

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#862]
**Is your feature request related to a problem? Please describe.**
Provide interface/module for data preprocess.
Data preprocess module allow user change vector data before data is import into milvus storage, such as dimensional reduction.

**Comment by Jimexist** [comment]
this doesn't only apply to pre-process, since there are some fixed-memory processing like incremental PCA that can be run on current documents.

**Comment by yhmo** [comment]
Will be considered in v2.x

**Comment by xiaofan-luan** [comment]
similar to #7704, close for now
