### ISSUE TITLE
etcdserver: mvcc: database space exceeded

### ISSUE THREAD

**Issue by DaPenggg** [milvus-io/milvus#8636]
#### Steps/Code to reproduce:
I excuted the python code todo insert data at last night, but i see the milvus crash at the morning.

#### Expected result:
insert data ok.

#### Actual results:
goroutine 415 [running]:
github.com/milvus-io/milvus/internal/util/sessionutil.(*Session).Init(0xc007d9bc00, 0x2513ede, 0x9, 0xc01068c3f0, 0xf, 0x1, 0x1)
        /go/src/github.com/milvus-io/milvus/internal/util/sessionutil/session_util.go:96 +0x153
github.com/milvus-io/milvus/internal/datacoord.(*Server).Register(0xc0005c20e0, 0x9, 0x26f3e80)
        /go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:177 +0xd9
github.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).init(0xc004a06af0, 0xc004a06a00, 0x0)
        /go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:81 +0xe6
github.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).Run(0xc004a06af0, 0xffffffffffffffff, 0x27241c0)
        /go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:169 +0x2f
github.com/milvus-io/milvus/cmd/components.(*DataCoord).Run(...)
        /go/src/github.com/milvus-io/milvus/cmd/components/data_coord.go:41
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runDataCoord.func1(0x2594501, 0x27238c0, 0xc00061dac0, 0xc000446000, 0xc008f2bce0)
        /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:213 +0xdc
created by github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runDataCoord
        /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:198 +0xb0
panic: etcdserver: mvcc: database space exceeded

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): RC6
- Deployment mode(standalone or cluster): standalone 
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus v2.0.0rc2
- OS(Ubuntu or CentOS):  Ubuntu
- CPU/Memory: normal
- GPU: None
- Others: None

#### Configuration file:
default

#### Additional context:

default

**Comment by xiaofan-luan** [comment]
looks like the etcd data exceed quota. You might want to increate disk quota for now. Another issues is because milvus doesn't open etcd data cleaning for now, this will be solved in rc7
