### ISSUE TITLE
Milvus doesn't handles partition description now

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#8668]
Originated here: https://github.com/milvus-io/pymilvus/issues/671#issuecomment-927263598

the gRPC proto lack a field for description. The proto is defined in this proto file: `milvus/internal/proto/milvus.proto`
```
message CreatePartitionRequest {
// Not useful for now
common.MsgBase base = 1;
// Not useful for now
string db_name = 2;
// The collection name in milvus
string collection_name = 3;
// The partition name you want to create.
string partition_name = 4;
}
```

We can see no "description" in the `CreatePartitionRequest`. Once the server receives this request, it stores the partition's information into ETCD so that the client can ask for the partition information later.

To fix this bug:

- add a "partition_description" to the CreatePartitionRequest, in the `milvus/internal/proto/milvus.proto`

- add code to handle "partition_description" in the proxy level:
```
milvus/internal/proxy/impl.go CreatePartition()
milvus/internal/proxy/task.go createPartitionTask
```

- add code to handle "partition_description" in the rootcoord level:
```
milvus/internal/rootcoord/root_coord.go CreatePartition()
milvus/internal/rootcoord/task.go CreatePartitionReqTask
milvus/internal/rootcoord/meta_table.go AddPartition()
```

- add code to return "partition_description"
```

**Comment by abhijeet007rocks8** [comment]
@XuanYang-cn Can I try to work on this issue?

**Comment by xiaofan-luan** [comment]
@DiptoChakrabarty Hi Dipto, are you still interested? assign this to you

**Comment by xiaofan-luan** [comment]
> @XuanYang-cn Can I try to work on this issue?

Hi welcome @abhijeet007rocks8 , Dipto comes a bit earlier~  already assigned to him.  Feel free to work on any of the other issues.

**Comment by XuanYang-cn** [comment]
> Hey I would like to try this

It's been 15 days since your last comment on this issue, I'm afraid this issue is open for others now.  Thanks a lot, please check out other issues.

**Comment by symphony233** [comment]
hi, If I use the **latest** protoc tool to generate `milvus.pb.go` which generated by modified `milvus.proto` file, and it will eliminate fields like 	
```
XXX_NoUnkeyedLiteral struct{} `json:"-"`
XXX_unrecognized     []byte   `json:"-"`
XXX_sizecache        int32    `json:"-"`
```
in the original file.

Is that ok to milvus? 
If not please tell me how to generate *.pb.go as above with redundant code? (may I think it's redundant, that's the [ref](https://stackoverflow.com/questions/50704319/xxx-type-in-generated-pb-go-file))

**Comment by XuanYang-cn** [comment]
@symphony233 Sorry for the late response.

You can use `make generated-proto-go` to generate milvus.pb.go from milvus.proto
