### ISSUE TITLE
When using alias to drop the collection, SDK raise error with message about index

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#8679]
#### Steps/Code to reproduce:
```
import random

from pymilvus import (
    connections, list_collections,
    FieldSchema, CollectionSchema, DataType,
    Collection
)


def hello_milvus():
    # create connection
    connections.connect()

    print(f"\nList collections...")
    print(list_collections())

    # create collection
    dim = 128
    default_fields = [
        FieldSchema(name="count", dtype=DataType.INT64, is_primary=True),
        FieldSchema(name="random_value", dtype=DataType.DOUBLE),
        FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
    ]
    default_schema = CollectionSchema(fields=default_fields, description="test collection")

    print(f"\nCreate collection...")
    collection = Collection(name="hello_milvus", schema=default_schema)
    collection.create_alias("a")
    alias = Collection("a")
    print(f"\nList collections...")
    print(list_collections())

    # # drop collection
    alias.drop()


hello_milvus()
```

#### Expected result:
raise error `can't use the alias to drop a collection`

#### Actual results:
raise error `Error: <BaseException: (code=1, message=DescribeIndex failed, error = collection a not found)`

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):master-20210926-8091e76
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.0.0rc7.dev13
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by XuanYang-cn** [comment]
> /assign @lsgrep

He needs to comment on this issue so that the robot can assign him

**Comment by zhuwenxing** [comment]
@lsgrep  Please take a look

**Comment by lsgrep** [comment]
OK

**Comment by yhmo** [comment]
@zhuwenxing Already fixed by #8780, please verify it in latest build.

**Comment by lsgrep** [comment]
I think #8780 only solves the half of the problem, I will create another PR to disable dropping collection via `alias`.

**Comment by zhuwenxing** [comment]
Verified and passed in pymilvus-2.0.0rc7.dev25 and master-20211013-4b77e6e

New error message is `pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=Drop collection failed: cannot drop the collection via alias = a)>`
