### ISSUE TITLE
Message broker using NATS ? Discussion

### ISSUE THREAD

**Issue by gedw99** [milvus-io/milvus#8683]
#### Is your feature request related to a problem? Please describe:

https://milvus.io/docs/v2.0.0/architecture_overview.md shows kefka, which is a great system, but NATS Jetstream is a very good replacement and is 100% golang. 

Good info here: https://docs.nats.io/compare-nats

NATS also does cluster replication using onyl nats, and also does message dedup now. 

#### Describe the solution you'd like:

Ability to use NATS, cause its so much easier than Kafka to use, setup and especially for Ops.

Its also FAST

**Comment by DragonDriver** [comment]
Yeah, in our architecture, we can configure the implementation of message broker later.

As you know, we use RocksDB as our message broker when deploying standalone milvus, instead we use Pulsar when deploying distributed milvus. RocksDB in milvus is compiled with milvus binary, and pulsar is also easy to deploy with documentation. Is there any issues when you deploy those two components?

We use a `MsgStream` to wrapper the message broker.  We're very glad to intergrate more suitable systems to `MsgStream`, but at least now we don't have enough time to do this.

So can you give us some more detailed suggestions about NATS? Or we can discuss more detail.

@gedw99

**Comment by xiaofan-luan** [comment]
Shouldn't be hard to combine milvus together with NATS, may need some refactor, wanna to give a try? @gedw99

**Comment by gedw99** [comment]
@xiaofan-luan 
I am swamped with work at the moment.

NATS is really easy BTW. Some tips:

1. You can embed a NATS server into the main code OR run a global cluster.  
 
https://github.com/nats-io/nats-server 

https://github.com/nats-io/nats-server/blob/main/server/jetstream_cluster.go

just add this flag to run it as a Jetstream cluster: https://github.com/nats-io/nats-server/blob/main/main.go#L54

Service file: https://github.com/nats-io/nats-server/blob/main/util/nats-server-hardened.service

2. The go.nats client is very easy to use. Its the golang code you write to talk to Nats 
 
https://github.com/nats-io/nats.go


3. The CLI makes it easy to test your code:
 
https://github.com/nats-io/natscli

4. And to run on k8 use Nack:

https://github.com/nats-io/nack

https://github.com/nats-io/nats-operator

**Comment by gedw99** [comment]
BTW NATS Server aso supports Websockets and MQTT build it.

So you can build Web Apps that use NATS via the Websockets.

IOT devices can use the NATS protocol direct. There is no reliance on HTTP, so you can compile using tinygo onto almost any MCU based hardware and it will work.

SO with NATS you can run on global cluster, with web, IOT, Mobile, etc clients.

Its pretty cool...

**Comment by deshetti** [comment]
Hi, I agree with @gedw99 that NATS is a really good option to support in addition to Pulsar & Kafka. It is pretty lightweight and performant compared to Kafka & Pulsar. As @gedw99 mentioned it also fits in pretty well that it is built in Golang, has good support for K8s & is [CNCF incubating](https://www.cncf.io/projects/nats/) project.

Milvus + MinIO + etcd + NATS IMO would be a pretty good/forward-looking stack

**Comment by xiaofan-luan** [comment]
> Hi, I agree with @gedw99 that NATS is a really good option to support in addition to Pulsar & Kafka. It is pretty lightweight and performant compared to Kafka & Pulsar. As @gedw99 mentioned it also fits in pretty well that it is built in Golang, has good support for K8s & is [CNCF incubating](https://www.cncf.io/projects/nats/) project.
> 
> Milvus + MinIO + etcd + NATS IMO would be a pretty good/forward-looking stack

Great! we just need one volunteer  to implement NATS stream storage

**Comment by gedw99** [comment]
@deshetti 

NATS now has an Object store, and so can replace Minio. This is experimental, but i expect it to work well because the store under it has been stable for quite a while.

https://docs.nats.io/nats-concepts/jetstream/obj_store/obj_walkthrough

NATS has had a KV store for a while and so replaces Etcd / Consul: https://docs.nats.io/nats-concepts/jetstream/key-value-store/kv_walkthrough

All this is distributed of course OR you can embed NATS inside milvus itself also since is just non CGO golang.
Many do both, so that New users can run everything locally, but then in Prod use an externals NATS Jetstream cluster.

**Comment by xiaofan-luan** [comment]
> , so that New users can run everything locally, but then in Prod use an externals NATS Jetstream cluster.

Looks like a very promising solution and covers all we need? intersesting

**Comment by gedw99** [comment]
You can test it out running a 4 node cluster with https://github.com/bruth/nats-zero-down.  It will run them in the background locally.   Just follow the README. 

Here is a makefile that runs the basics of KV and object store against the cluster.
``` 
# nats

NATS_VERSION=latest
NATS_CLI_VERSION=latest
NATS_NSC_VERSION=latest

print:
	@echo
	@echo "NATS_VERSION:        $(NATS_VERSION)"
	@echo "NATS_CLI_VERSION:    $(NATS_CLI_VERSION)"
	@echo "NATS_NSC_VERSION:    $(NATS_NSC_VERSION)"

dep-install:
	go install github.com/nats-io/nats-server/v2@$(NATS_VERSION)
	go install github.com/nats-io/natscli/nats@$(NATS_CLI_VERSION)
	go install github.com/nats-io/nsc@$(NATS_NSC_VERSION)


# !! Assumes that bruth__nats-zero-down code is on disk..
NATS_CLUSTER_FSPATH=./bruth__nats-zero-down/nats-zero-down/replace-cluster-nodes

# Pick one. Single or Cluster...
# NATS_SERVER_LIST=localhost:4222
NATS_SERVER_LIST=localhost:4222,localhost:4223,localhost:4224


run-server-print:
	@echo NATS cluster 
	@echo "NATS_CLUSTER_FSPATH:        $(NATS_CLUSTER_FSPATH)"
	@echo "NATS_SERVER_LIST:           $(NATS_SERVER_LIST)"
run-server:
	rm -rf {pids,logs,data}
	mkdir -p {pids,logs,data}
	nats-server --config $(NATS_CLUSTER_FSPATH)/configs/n0.conf
run-server-delete:
	rm -rf {pids,logs,data}

run-cluster:
	# uses bruth code...
	cd $(NATS_CLUSTER_FSPATH) && chmod +x ./scripts/*.sh
	cd $(NATS_CLUSTER_FSPATH) && ./scripts/start-cluster.sh
run-cluster-stop:
	# uses bruth code...
	cd $(NATS_CLUSTER_FSPATH) && ./scripts/stop-cluster.sh
run-cluster-list:
	# uses bruth code...
	#cd $(NATS_CLUSTER_FSPATH) && ./scripts/list-nodes.sh
	nats -s $(NATS_SERVER_LIST) --user sys --password pass server list
run-cluster-list-watch:
	cd $(NATS_CLUSTER_FSPATH) && ./scripts/watch-servers.sh
run-cluster-check:
	nats -s $(NATS_SERVER_LIST) server check jetstream


### TESTS, etc

NATS_CLI_CMD=--server=$(NATS_SERVER_LIST)

run-print:
	@echo NATS
	@echo "NATS_CLI_CMD:    $(NATS_CLI_CMD)"

run-check:
	nats $(NATS_CLI_CMD) server check jetstream

run-account:
	nats $(NATS_CLI_CMD) account info

run-kv-watch:
	nats $(NATS_CLI_CMD) kv watch my_kv
run-kv-test:
	nats $(NATS_CLI_CMD) kv add my_kv
	nats $(NATS_CLI_CMD) kv put my_kv Key1 Value1
	nats $(NATS_CLI_CMD) kv get my_kv Key1
	nats $(NATS_CLI_CMD) kv del my_kv Key1 -f
run-kv-test-cleanup:
	nats $(NATS_CLI_CMD) kv rm my_kv -f


run-object-watch::
	nats $(NATS_CLI_CMD) object watch myobjbucket
run-object-test:
	nats $(NATS_CLI_CMD) object add myobjbucket
	nats $(NATS_CLI_CMD) object info myobjbucket
	nats $(NATS_CLI_CMD) object put myobjbucket ./image.png
	nats $(NATS_CLI_CMD) object ls myobjbucket
	nats $(NATS_CLI_CMD) object get myobjbucket image.png
	nats $(NATS_CLI_CMD) object seal myobjbucket
	nats $(NATS_CLI_CMD) object put myobjbucket ./image.png
run-object-test-cleanup:
	nats $(NATS_CLI_CMD) object rm myobjbucket -f

```
