### ISSUE TITLE
[benchmark][cluster] Panic but don't quit

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#8702]
#### Steps/Code to reproduce:
error code：
`[2021/09/27 10:39:01.005 +00:00] [FATAL] [logutil.go:96] [panic] [recover="\"Failed to create consumer by-dev-datacoord-timetick-channel, error = All attempts results:\\nattempt #1:connection error\\nattempt #2:connection error\\nattempt #3:ServiceNotReady\\nattempt #4:ServiceNotReady\\nattempt #5:ServiceNotReady\\nattempt #6:ServiceNotReady\\nattempt #7:ServiceNotReady\\nattempt #8:ServiceNotReady\\nattempt #9:ServiceNotReady\\nattempt #10:ServiceNotReady\\nattempt #11:ServiceNotReady\\nattempt #12:ServiceNotReady\\nattempt #13:ServiceNotReady\\nattempt #14:ServiceNotReady\\nattempt #15:ServiceNotReady\\nattempt #16:ServiceNotReady\\nattempt #17:ServiceNotReady\\nattempt #18:ServiceNotReady\\nattempt #19:ServiceNotReady\\nattempt #20:ServiceNotReady\\n\""] [stack="github.com/milvus-io/milvus/internal/logutil.LogPanic\n\t/go/src/github.com/milvus-io/milvus/internal/logutil/logutil.go:96\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:969\ngithub.com/milvus-io/milvus/internal/msgstream.(*mqMsgStream).AsConsumer\n\t/go/src/github.com/milvus-io/milvus/internal/msgstream/mq_msgstream.go:146\ngithub.com/milvus-io/milvus/internal/datacoord.(*Server).startDataNodeTtLoop\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:359"]`

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by godchen0212** [comment]
I try to reproduce this problem locally, but it seems work well.
![20210928-160621](https://user-images.githubusercontent.com/67679556/135048440-c2a06925-074d-4dc4-806c-67f6d07ab670.png)

**Comment by yanliang567** [comment]
@wangting0128  please keep an eye on recent run results, we'd like to close it if not reproduced any more.
