### ISSUE TITLE
Improve milvus unittest coverage with fiu mocking some errors

### ISSUE THREAD

**Issue by ABNER-1** [milvus-io/milvus#872]
**Describe the solution you'd like**
Using a lib called 'fiu'.

**Comment by shengjh** [comment]
lib fiu is a useful open  source fault injection library. Uinsg it to improve code coverage by adding some points of failure. For details, please see [https://blitiri.com.ar/p/libfiu/](url)

**Comment by scsven** [comment]
fiu has been integrated in Milvus
