### ISSUE TITLE
Update maximum supported dimension to greater value 

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#873]
**Is your feature request related to a problem? Please describe.**
The maximum dimension value that  we currently support is 16384,
Can we change the maximum dimension to test milvus-server based on dataset Kosarak,
http://fimi.uantwerpen.be/data/ 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yhmo** [comment]
Change dimension limit to 32768, since some public dataset using high dimensional vectors(more than 20k)

**Comment by yhmo** [comment]
Fixed in tanimoto branch
