### ISSUE TITLE
is  milvus support filter first then  calculate the    Inner product 

### ISSUE THREAD

**Issue by chenchuangc** [milvus-io/milvus#8797]
###  my use situation
i want use milvus as the calculate engine.
follow the steps :
1. filter the vector doc by ids , about 10k ids
2. calculate the Inner product  of  the 10k vector  and the request vector
3. return to top1000   

can i use milvus to implement it ?

英语不太好，用汉语注释一下
### 使用场景  
milvus是否支持先过滤后计算相识度
我想使用milvus来做双塔粗排
1. 需要先过滤10000个id,
2. 然后在1w个过滤后的结果使用向量的相识度计算（请求中会携带向量）
3. 召回率需要是100%

麻烦问一下milvus可以支持么
索引的类型是否需要选择FLAT

**Comment by xiaofan-luan** [comment]
So it's like query by id , and search specified vector among queried result?

**Comment by xiaofan-luan** [comment]
I believe calc distance api is what you need.
It can calculate distance from specified vectors to vectors specified a id list, please check pymilvus API
