### ISSUE TITLE
syncTimeStamp Failed when list_collections 

### ISSUE THREAD

**Issue by sicklife** [milvus-io/milvus#8822]
#### Steps/Code to reproduce:
from pymilvus import (
    connections, list_collections,
    FieldSchema, CollectionSchema, DataType,
    Collection
)

def hello_milvus():
    # create connection
    connections.connect(host='172.21.32.15', port='31626', )

    print(f"\nList collections...")
    print(list_collections())

hello_mivlus()

#### Expected result:

list all collections

#### Actual results:

![image](https://user-images.githubusercontent.com/8018334/135192218-fe3cf35b-124d-4920-9d5f-60527f0ae44d.png)

#### Environment:
- Milvus version(datanode image:   milvus/milvus:v2.0.0-rc6-20210910-020f109):
- Deployment mode: **cluster** 
- SDK version(e.g. pymilvus v2.0.0rc6):
- OS: Ubuntu 
- CPU/Memory: 
- GPU: No
- Others:

**Comment by xiaofan-luan** [comment]
Hi sicklife ,  can you offer use detailed logs? that will be really helpful
