### ISSUE TITLE
Differentiate tech docs and design docs labels

### ISSUE THREAD

**Issue by claireyuw** [milvus-io/milvus#8829]
#### What would you like to be added:
Use labels such as `kind/design-docs` and `kind/tech-docs` to differentiate doc related issues.
Maybe also add `doc-no-change`, `doc-error`, `doc-update`, `doc-new` and such to indicate specific doc requests.

#### Why is this needed:
This makes it easier to identify doc requests and also helps remind engineers of involving documentation in the design process.

**Comment by xiaofan-luan** [comment]
done, I just separate it by kind/developer-doc and kind/user-doc
