### ISSUE TITLE
describe_index with ValueError: 9 is not a valid IndexType

### ISSUE THREAD

**Issue by shiyu22** [milvus-io/milvus#883]
**Describe the bug**
ValueError: 10 is not a valid IndexType

**Steps/Code to reproduce behavior**
```
TABLE_NAME = "test"
DIM = 512
TABLE_PARAM = {
    "table_name": TABLE_NAME,
    "dimension": DIM,
    "index_file_size": 1024,
    "metric_type": MetricType.JACCARD
}
client.create_table(TABLE_PARAM)
client.describe_index(TABLE_NAME)
```

**Expected behavior**
Status(code=0, message='Success'), IndexParam(table_name='test', index_type=<IndexType: IVFLAT>, nlist=16384)

**Comment by yhmo** [comment]
Fixed in tanimoto branch
