### ISSUE TITLE
Integrate diskANN with milvus

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#8830]
#### Is your feature request related to a problem? Please describe:
DiskANN is  a Graph based indices for approximate nearest neighbor search open sourced  by microsoft. 

see details at https://github.com/microsoft/DiskANN

#### Describe the solution you'd like:
I want to integrate diskANN to milvus thus we can have some type of hybrid index for billion vector case. any one intereted?

**Comment by Dsantra92** [comment]
This looks like a very cool thing to work on. Would you mind telling me more about what exactly you mean by hybrid index here?

**Comment by geekypandey** [comment]
I am interested to work on this issue.

**Comment by xiaofan-luan** [comment]
> This looks like a very cool thing to work on. Would you mind telling me more about what exactly you mean by hybrid index here?

Hey Dsantra92, it means memory and ssd storage hybrid. Tradition vector index is stored in memory which cost too high. It's also very hard to cache data by chunk for a ANNs index since data access locality is bad. Thus hybrid index put a compressed index in memory,  and put the real data on disk, which is a very good tradeoff.

**Comment by xiaofan-luan** [comment]
> I am interested to work on this issue.

Welcome @geekypandey, assign this issue to you. let me know if you need extra information

**Comment by xiaofan-luan** [comment]
@parthiv11 hey parthiv11, need any help?

**Comment by parthiv11** [comment]
@xiaofan-luan am i eligible for Hacktoberfest swag

**Comment by parthiv11** [comment]
Can you help me for this issue

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan am i eligible for Hacktoberfest swag

Hey parthiv, sorry that the Hacktoberfest event is done~ but the community welcomes any contribution and we will still send some gifts if you made some progress.

**Comment by xiaofan-luan** [comment]
may I know what step you are at? did you successfully build and setup dev environment on your laptop? what kind of help do you need.

**Comment by parthiv11** [comment]
No i am not talking about this issue. 
I have made some prs in milvus-io organisations

**Comment by xiaofan-luan** [comment]
Sure which issues?

**Comment by parthiv11** [comment]
https://github.com/search?q=org%3Amilvus-io+author%3Aparthiv11&type=issues

**Comment by xiaofan-luan** [comment]
@kateshaowanjou  Hi kate, could you please help to check?

**Comment by parthiv11** [comment]
@xiaofan-luan why you are not active on slack

**Comment by kateshaowanjou** [comment]
If this is not relevant to this issue, please do not comment under this issue to avoid confusion. You can go here for general discussion about Hacktoberfest instead: https://discuss.milvus.io/c/hacktoberfest/9. 

> @xiaofan-luan No i am not talking about this issue. I have made some PRs in milvus-io organisation
