### ISSUE TITLE
[Bug] test_util.cpp have a wrong assert 

### ISSUE THREAD

**Issue by shengjh** [milvus-io/milvus#889]
**Describe the bug**
in test_util.cpp, there is a wrong assert.

**Steps/Code to reproduce behavior**
code here.

https://github.com/milvus-io/milvus/blob/36042605aea41ab7d7f4c54bcb361e09802808bc/core/unittest/server/test_util.cpp#L90-L99
at Line 96, should ue ASSERT_EQ, since time_struct.tm_mon >= 0
**Expected behavior**
Use ASSERT_EQ instead.

**Comment by Yukikaze-CZR** [comment]
fix in PR #888
