### ISSUE TITLE
[BUG] RequestScheduler error when start after stop.

### ISSUE THREAD

**Issue by ABNER-1** [milvus-io/milvus#891]
**Describe the bug**
It will fail when i run this code demo:
```c++
    milvus::server::RequestScheduler::GetInstance().Start();
    milvus::server::RequestScheduler::GetInstance().Stop();
    milvus::server::RequestScheduler::GetInstance().Start();
    milvus::server::RequestScheduler::GetInstance().Stop();
```

**Steps/Code to reproduce behavior**
fail when 2rd stop at ```iter->join();```
You should judge ```iter->joinable()```

**Expected behavior**
run as normal

**Comment by fishpenguin** [comment]
Already fixed
