### ISSUE TITLE
Developer Document having missing information which can make unit test fail

### ISSUE THREAD

**Issue by elfisworking** [milvus-io/milvus#8917]
#### What would you like to be added:
i want to add more information to guide new developer. Document url is https://github.com/milvus-io/milvus/blob/master/DEVELOPMENT.md
#### Why is this needed:
if i follow instructions completely, i will fail to do go test for losing container environment. But document does't tell us to open container before doing test. And in E2E test,  docker-compose.yml file in dev dir is only used for distributed mode while if we want to start standalone mode, the dir location is standalone dir. Now the information is missing.

**Comment by scsven** [comment]
Welcome! If you encounter some problem, you can mention me for help. :)

/assign @elfisworking
