### ISSUE TITLE
V1.1.1 too many disk space occupied

### ISSUE THREAD

**Issue by mayunjie** [milvus-io/milvus#8922]
#### Steps/Code to reproduce:
1、create collection
2、insert 5 million datas， dim 16384， index_file_size 2048

#### Expected result:
occupy 5m*2046bytes = 10GB disk space

#### Actual results:
occupy more than 100G disk spce

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):1.1.1
- Deployment mode(standalone or cluster): both
- SDK version(e.g. pymilvus v2.0.0rc2):Java v1.1.1
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 32 core/ 300G
- GPU: 
- Others: 

#### Configuration file:
1、Collection param： dimension=16384 metricType=HAMMING index.file.size=2048

#### Additional context:

docker image: 1.1.2-cpu-rc

**Comment by yhmo** [comment]
I did some testing, but the milvus 1.1.1 didn't occupy so lot of disk space.
My test steps:
1. start a new milvus container
   `docker run -p 19530:19530 -p 19121:19121 milvusdb/milvus:1.1.1-cpu-d061621-330cc6`
2. go into the container:
   `docker exec -it [container id] bash`
3. in the container, run this command to continually print disk consume(unit:MB) of milvus db folder:
  `while true; do du -ms ./db ./wal ./logs; sleep 1; done;`

4. run this script, insert 5M binary vectors(16384 dim), 10000 vectors for each batch:
```
import random
import time
import numpy as np
from milvus import Milvus, IndexType
from milvus.client.types import MetricType

SERVER_ADDR = "127.0.0.1"
SERVER_PORT = '19530'
COLLECTION_NAME = "TEST"
COLLECTION_DIMENSION = 16384
COLLECTION_PARAM = {'collection_name': COLLECTION_NAME,
                    'dimension': COLLECTION_DIMENSION,
                    'index_file_size': 2048,
                    'metric_type':MetricType.HAMMING}


MILVUS = Milvus(host=SERVER_ADDR, port=SERVER_PORT)

def create_collection(name = COLLECTION_NAME):
    param = COLLECTION_PARAM
    param['collection_name'] = name
    status = MILVUS.create_collection(param)
    print("create", name)

def drop_collection(name = COLLECTION_NAME):
    status = MILVUS.drop_collection(collection_name=name)
    time.sleep(1)
    print("drop", name)

def insert(name = COLLECTION_NAME):
    print("prepare insert")
    batch = 10000
    vectors = gen_binary_vectors(batch)
    for i in range(500):

        status, ids = MILVUS.insert(collection_name=name, records=vectors)
        print("insert", i, len(ids), status)
    MILVUS.flush(collection_name_array=[name])

def gen_binary_vectors(num, dim = COLLECTION_DIMENSION):
    print("generating binary vectors", "num=", num, "dim=", dim)
    binary_vectors = []
    raw_vector = [random.randint(0, 1) for i in range(dim + num)]
    for i in range(num):
        binary_vectors.append(bytes(np.packbits(raw_vector[num:dim+num], axis=-1).tolist()))
    return binary_vectors

if __name__ == "__main__":
    drop_collection()
    create_collection()
    insert()

```

Result:
The peak value of disk consume is about 15GB:
7038	./db
4557	./wal
2	./logs

7038	./db
4557	./wal
2	./logs

9253	./db
4557	./wal
2	./logs

9783	./db
3917	./wal
2	./logs

10565	./db
3917	./wal
2	./logs

10114	./db
3789	./wal
2	./logs
