### ISSUE TITLE
[BUG] Optimizer all pass can not use 'throw;'  without the scope of try-catch

### ISSUE THREAD

**Issue by ABNER-1** [milvus-io/milvus#893]
**Describe the bug**
using 'throw;' without the scope of try-catch will invoke std::terminate which can't be caught.

**Steps/Code to reproduce behavior**
All pass in Init() function, like this
```c++
if (!s.ok()) {
        throw ;
    }
```

**Expected behavior**
Maybe throw a meaningful exception here.

**Comment by JinHai-CN** [comment]
Please provide the assignee if some one is handling this issue.

**Comment by JinHai-CN** [comment]
@fishpenguin Fixed?

**Comment by fishpenguin** [comment]
Already fixed
