### ISSUE TITLE
[BUG] The server start error messages could be improved to enhance user experience

### ISSUE THREAD

**Issue by yamasite** [milvus-io/milvus#90]
**Describe the bug**
The server start error messages lack vital information for troubleshooting. 

**Expected behavior**

| Current error message  |  Suggested error message       |
| ---------- | ---------------------------------- |
ERROR: mode specified in server_config is not one of ['single', 'cluster', 'read_only'] | Error: server_config.deploy_mode is not one of single, cluster_readonly, and cluster_writable. | wrong value for server_config.yaml   server_config.mode
ERROR! Failed to create database root path: {path} | Error: Failed to create database primary path: {path}. Possible reason: db_config.primary_path is wrong or not available. | wrong value for server_config.yaml   db_config.db_path,  or the path is not available
ERROR! Failed to create database slave path: | Error: Failed to create database secondary path:{path}. Possible reason: db_config.secondary_path is wrong or not available. | wrong value for server_config.yaml   db_config.slave_path,  or the path is not available
ERROR! Failed to open database: {error message} | Error: Failed to open database. Possible reason: {error message} | the meta system is not work,
ERROR: invalid server IP address: {it} | Error: Invalid server IP address: {address}. Possible reason: server_config.address is invalid. | illegal server address for server_config.yaml   server_config.address
ERROR: port xxx is not a number | Error: Port {port} is not a number. Possible reason: server_config.port is invalid. | illegal server port for server_config.yaml   server_config.port
ERROR: port xxx out of range [1025, 65534] | Error: Port {port} is not in range [1025, 65534]. Possible reason: server_config.port is invalid. | illegal server port for server_config.yaml   server_config.port,   range is 1025~65534
ERROR: db_path is empty | Error: db_path is empty. Possible reason: db_config.db_path is empty. | empty string for server_config.yaml db_config.db_path
ERROR: invalid db_backend_url: {url} | Error: Invalid db_backend_url: {url}. Possible reason: db_config.db_backend_url is invalid. The correct format should be like sqlite://:@:/ or mysql://root:123456@127.0.0.1:3306/milvus. | illegal url for server_config.yaml db_config.db_backend_url,    the right format is sqlite://:@:/  or mysql://root:123456@127.0.0.1:3306/milvus
ERROR: Invalid server config time_zone: {time zone} | ERROR: Invalid server config time_zone: {time zone} |  
ERROR: Invalid insert_buffer_size: {buffer size} | ERROR: Invalid insert buffer size: {buffer size}. Possible reason: db_config.insert_buffer_sizel is not a positive integer. |  
ERROR: Invalid metric config auto_bootup: {enable metric} | ERROR: Invalid metric config: {enable metric}. Possible reason: metric_config.enable_monitor is not a boolean. |  
ERROR: Invalid metric collector: {metric collector} | ERROR: Invalid metric config: {metric collector}. Possible reason: metric_config.collector is invalid. |  
ERROR: Invalid metric config prometheus_port: {port} | ERROR: Invalid metric config: {port}. Possible reason: metric_config.prometheus_config.port is not in range [1025, 65534]. |  
ERROR: Invalid cache config cpu_cache_capacity: {capacity} | ERROR: Invalid cpu cache capacity: {capacity}. Possible reason: cache_config.cpu_cache_capacity is not a positive integer. |  
ERROR: Cache config cpu_cache_capacity exceed system memory: | ERROR: Invalid cpu cache capacity: {capacity}. Possible reason: cache_config.cpu_cache_capacity exceeds system memory. |  
ERROR: Sum of cpu_cache_capacity and buffer_size exceed system memory | ERROR: Invalid cpu cache capacity: {capacity}. Possible reason: sum of cache_config.cpu_cache_capacity and db_config.insert_buffer_size exceeds system memory. |  
ERROR: Invalid cache config cpu_cache_threshold: {threshold} | ERROR: Invalid cpu cache threshold: {threshold}. Possible reason: cache_config.cpu_cache_threshold is not in range (0.0, 1.0]. |  
ERROR: Invalid cache config gpu_cache_capacity: {capacity} | ERROR: Invalid gpu cache capacity: {capacity}. Possible reason: cache_config.gpu_cache_capacity is not a positive integer. |  
ERROR: Fail to get GPU memory for GPU device: {device} | ERROR: Fail to get GPU memory for GPU device: {device} |  
ERROR: Cache config gpu_cache_capacity exceed GPU memory: {capacity} | ERROR: Invalid gpu cache capacity: {capacity}. Possible reason: cache_config.gpu_cache_capacity exceeds GPU memory. |  
ERROR: Invalid cache config gpu_cache_threshold: {threshold} | ERROR: Invalid gpu cache threshold: {threshold}. Possible reason: cache_config.gpu_cache_threshold is not in range (0.0, 1.0]. |  
ERROR: Invalid cache config cache_insert_data: {bool} | ERROR: Invalid cache insert option: {bool}. Possible reason: cache_config.cache_insert_data is not a boolean. |  
ERROR: Invalid engine config use_blas_threshold: {threshold} | ERROR: Invalid blas threshold: {threshold}. Possible reason: engine_config.use_blas_threshold is not a positive integer. |  
ERROR: Invalid gpu device: {device} | ERROR: Invalid gpu device: {device}. Possible reason: resource_config.search_resources does not match your hardware. |  
ERROR: Empty resource config search_resources | ERROR: Invalid search resource. Possible reason: resource_config.search_resources is empty. |  
ERROR: Invalid resource config index_build_device: {device} | ERROR: Invalid index build device: {device}. Possible reason: resource_config.index_build_device does not match your hardware.

**Comment by cydrain** [comment]
UPDATE
Error: server_config.mode in server_config.yaml is not one of single, cluster_readonly, and cluster_writable.

**Comment by yhmo** [comment]
Fixed by PR #121
