### ISSUE TITLE
index methods implementation

### ISSUE THREAD

**Issue by charlotte12l** [milvus-io/milvus#900]
Hi:

I'm interested in your implementation of index methods, like IVF_SQ8, IVFFlat. However, I can't find your code implementation for these methods except third party (FAISS,SPTAG). Did you use the implementations of third party? Could you please point me to your implementation? Thanks!

**Comment by cydrain** [comment]
IVF_SQ8 and IVF_FLAT are implemented in FAISS, you can find the code under faiss directory.

**Comment by JinHai-CN** [comment]
Fixed.
