### ISSUE TITLE
Proxy Unit test has race

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#9076]
#### Steps/Code to reproduce:
Run Proxy unit test

#### Expected result:
Passes

#### Actual results:
Failed with DATA RACE

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): a5cd484
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: 

#### Additional context:
https://github.com/milvus-io/milvus/runs/3775187112?check_suite_focus=true

**Comment by DragonDriver** [comment]
I take a look at the code of `queryService.close`. It seems that `stopQueryCollection` is not necessary.
@congqixia
