### ISSUE TITLE
Handling the returned error

### ISSUE THREAD

**Issue by godchen0212** [milvus-io/milvus#9168]
#### What would you like to be added:
Handling the returned error value.
#### Why is this needed:
If the returned error is not handled, there is no way to know what error has occurred in the system.
For example:
```go
// save deleted node to kv
deleted := node.Clone(SetChannels(nil))
c.saveNode(deleted)
```

In fact, the saveNode operation has an error return value, which represents whether the operation is successful or not. If it is successful, err is nil, otherwise err represents the error value that occurred. If we don't deal with it, if there is an error in this place, it is difficult for us to know what went wrong.

It should be like this:

```go
// save deleted node to kv
deleted := node.Clone(SetChannels(nil))
err := c.saveNode(deleted)
if err != nil {
	log.Warn("DataCoord Cluster handleUnRegister save deleted node", zap.Error(err))
	return
}
```

**Comment by yanliang567** [comment]
@godchen0212 is this done now?
/assign @godchen0212
