### ISSUE TITLE
propose GGNN index 

### ISSUE THREAD

**Issue by hudengjunai** [milvus-io/milvus#919]
near exact nn-search index alg mentioned in this paper .
as [url:https://github.com/cgtuebingen/ggnn](https://github.com/cgtuebingen/ggnn) paper said

- [Arxiv Pre-Print](https://arxiv.org/abs/1912.01059)

**Comment by JinHai-CN** [comment]
Great! Do you know any implementation on this paper?

**Comment by hudengjunai** [comment]
> Great! Do you know any implementation on this paper?
Actually ,I have not found any implementation yet. It's a pity that I am not a master of GPU-programmer.  I would contribute if I have some ideas.
