### ISSUE TITLE
Is their any plan to provide  industry solutions?

### ISSUE THREAD

**Issue by hudengjunai** [milvus-io/milvus#920]
Is their any plan to provide some typical full-pipeline solution like   
- high recall@1 accuracy(0.99x) scene ,eg. faceRecognition search .   
- massive classes/fine-grained and large scale products image search .    
- small video duplicate.     

I think some typical landing-scene would be very helpfull to promote milvus.  
Do you think so?

**Comment by JinHai-CN** [comment]
Great! Thank you for your advice, firstly.

Now we already have some demos: https://github.com/milvus-io/bootcamp/tree/master/solutions

Yes, we do have plan to provide the typical full stack solution. The requirements and architecture are still in design phase. I am appreciate it, if you can provide some more scenarios.

**Comment by hudengjunai** [comment]
> Great! Thank you for your advice, firstly.
> 
> Now we already have some demos: https://github.com/milvus-io/bootcamp/tree/master/solutions
> 
> Yes, we do have plan to provide the typical full stack solution. The requirements and architecture are still in design phase. I am appreciate it, if you can provide some more scenarios.

Thank you for your reply, It seems this [milvus book](https://www.bookstack.cn/read/Milvus/reference-application.md)  :section [应用场景] a application plan?

**Comment by JinHai-CN** [comment]
Yes, we are planning to provide unstructured data search engine frame to provide more scenarios.

**Comment by JinHai-CN** [comment]
Fixed.
