### ISSUE TITLE
Performance issues：cpu_cache_capacity

### ISSUE THREAD

**Issue by tianyunperfect** [milvus-io/milvus#923]
**What is your question?**
我的在使用默认配置的情况下，导入大量数据，测试性能非常差。
请问我该怎么知道cpu_cache_capacity应该设置多大呢？

**Comment by yhmo** [comment]
Make sure cpu_cache_capacity value is larger than total data size.
For example, assume there are 1 million 512 dimensional vectors already imported, each vector size is 2KB, total size is 2k*1M= 2GB, to make sure all data can be hold in cpu memory(to get best search performance), the cpu_cache_capacity should be greater than 2.
For some kind of index type, SQ8, can save cpu memory. Generally SQ8 index file size is only about 30% of the raw vector size. So if you already build SQ8 index, cpu_cache_capacity set to 1 is enough.
(抱歉我们规定只能以英文回答，以后尽量用英文吧)

**Comment by tianyunperfect** [comment]
ok，thanks.

**Comment by tianyunperfect** [comment]
> Make sure cpu_cache_capacity value is larger than total data size.
> For example, assume there are 1 million 512 dimensional vectors already imported, each vector size is 2KB, total size is 2k*1M= 2GB, to make sure all data can be hold in cpu memory(to get best search performance), the cpu_cache_capacity should be greater than 2.
> For some kind of index type, SQ8, can save cpu memory. Generally SQ8 index file size is only about 30% of the raw vector size. So if you already build SQ8 index, cpu_cache_capacity set to 1 is enough.
> (抱歉我们规定只能以英文回答，以后尽量用英文吧)

If a single 512-dimensional vector takes 2 kb, then a 128-dimensional vector is 0.5 kb?

**Comment by yhmo** [comment]
Right, vector data type is float(4 bytes), 128 dimensional vector is 4*128 = 512 bytes = 0.5kb
