### ISSUE TITLE
创建索引后，再次插入数据，插入后需要再次创建索引吗？

### ISSUE THREAD

**Issue by tianyunperfect** [milvus-io/milvus#924]
**What is your question?**
创建索引后，再次插入数据，插入后需要再次创建索引吗？

**Comment by JinHai-CN** [comment]
If new imported data size reaches the index building size limit, new data will be built as index automatically. Otherwise, it won't be built as index. But you still can use build interface to create index for the new imported data manually, even its size not reach the size limit.

**Comment by yhmo** [comment]
For more information, please refer to this article: https://zhuanlan.zhihu.com/p/90812583

**Comment by tianyunperfect** [comment]
> If new imported data size reaches the index building size limit, new data will be built as index automatically. Otherwise, it won't be built as index. But you still can use build interface to create index for the new imported data manually, even its size not reach the size limit.

Thank you very much.

**Comment by tianyunperfect** [comment]
> For more information, please refer to this article: https://zhuanlan.zhihu.com/p/90812583

Thank you very much.
