### ISSUE TITLE
String DataType

### ISSUE THREAD

**Issue by musedivision** [milvus-io/milvus#9458]
#### What would you like to be added:
Add Support for `String` DataType field. 

```python
foreign_id_field = FieldSchema(name="foreign_id", dtype=DataType.String, description="foreign id of vector in a different database")
```

e.g.
```python
dim = 384
id_field = FieldSchema(name="id", dtype=DataType.INT64, description="primary_field")
foreign_id_field = FieldSchema(name="foreign_id", dtype=DataType.String, description="foreign id of vector in a different database")
embedding_field = FieldSchema(name="embedding", dtype=DataType.FLOAT_VECTOR, dim=dim)
schema = CollectionSchema(fields=[id_field, barcode_field, embedding_field], primary_field='id', auto_id=True,
                          description='desc of collection')
```

Allowing easy retrieval of information about the identity of the vector when searching:
```python
collection.search(
            query, "embedding", search_params, top_k, output_fields=["foreign_id"]
        )
```

#### Why is this needed:
I am building out a image retrieval system using visual embeddings.

To integrate the similarity search with other data sources. This is usually by joining the data with some kind of `uuid` in string format. 
In most cases, short vector identities in string format would suffice. 

Especially since many image retrieval paper suggest the use of centroid of each category: [On the Unreasonable Effectiveness of Centroids in Image Retrieval](https://arxiv.org/abs/2104.13643) 

I would be happy to contribute towards this feature. Although some guidance towards the tasks involved would be much appreciated!

**Comment by mdcroce** [comment]
Hey @musedivision! Thanks for collaborating to the project. Is this feature in progress? Can I test it? Thanks!

**Comment by musedivision** [comment]
Hey @xiaofan-luan, 

Thanks so much for responding and providing that info on the enhancement plan.
@czs007 Could you advise on the current progress and the best ways to start contributing?

Unfortunately @mdcroce I have not made any progress on this feature. Using an external store (SQL DB) is still the current method for using strings: https://github.com/milvus-io/milvus/discussions/4942#discussioncomment-618912

**Comment by xiaofan-luan** [comment]
> 

Due to the priority issue we delayed the string type support, once milvus 2.0 GA is released we will work on this

**Comment by xiaofan-luan** [comment]
duplicate with 4430
