### ISSUE TITLE
'use_blas_threshold' could be set to negative number via rest API

### ISSUE THREAD

**Issue by liangliu** [milvus-io/milvus#953]
**Describe the bug**
'use_blas_threshold' could be set to negative number via rest API

**Steps/Code to reproduce behavior**
1, use rest API to set 'use_blas_threshold' like this: use_blas_threshold = -10
2, response code 200 and use_blas_threshold value on server side is changed

**Expected behavior**
use_blas_threshold should be always above zero (>0), the API call should return error and the operation should take no effect to the server side

**Environment details**

**Screenshots**

**Additional context**

**Comment by liangliu** [comment]
please note not only **use_blas_threshold** but also **gpu_search_threshold** should not allowed to set to negative number, please correct both accordingly.

**Comment by cydrain** [comment]
fixed with #1078
