### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by tianyunperfect** [milvus-io/milvus#954]
**What is your question?**
Docker single node, 6.4 million 128 dimensional data, only using CPU to query a single vector, server 64 core, tps only 100, Is this normal?

**Comment by yhmo** [comment]
tps 100 means each second process 100 queries. Each query is 10ms, I think it is reasonable. Since queries are processed one by one in a task sequence.

**Comment by yhmo** [comment]
We assume each query will use all cpu resource to compute. But for single vector query, for some technical reason, cpu occupy rate is no more than 30%. Batch query is more efficient.

**Comment by tianyunperfect** [comment]
> We assume each query will use all cpu resource to compute. But for single vector query, for some technical reason, cpu occupy rate is no more than 30%. Batch query is more efficient.

Hello, multi-threaded testing, the average response time is 350ms, CPU utilization reached 90% , which direction could to optimize it?

**Comment by tianyunperfect** [comment]
Do I have a clear description of my problem？

**Comment by tianyunperfect** [comment]
A single thread takes 12ms, but multiple threads take 260ms. How can I optimize that?

**Comment by tianyunperfect** [comment]
我还是有中文描述一下我的问题吧。
环境：
linux 7
docker CPU only，单节点、cpu64个逻辑线程（核）
情况：
一个并发的情况下，tps为77，每次耗时12，效果还可以。
多并发（30个线程）情况下，tps为100，每次耗时260左右，tps提升不了，我应该怎么提升多并发情况的tps呢？

**Comment by JinHai-CN** [comment]
What type of index you are building vectors with?

**Comment by yhmo** [comment]
For multi-clients, queries time cost is calculated begin query send to server and end with result returned. Query time cost is overlap, so each query cost 260ms. But the total time to process 1000 queries is almost same for single-client and multi-clients. 
You can do a test to verify:  Use single client to perform 1000 queries, calculate total time cost; then use 30 clients to perform 1000 queries, calculate total time cost; compare two total time and they should be almost equal. 
Please refer this chart:
![Selection_052](https://user-images.githubusercontent.com/2282099/71972472-a7f2de80-3247-11ea-8a66-d3b6264f11ed.png)

**Comment by tianyunperfect** [comment]
> For multi-clients, queries time cost is calculated begin query send to server and end with result returned. Query time cost is overlap, so each query cost 260ms. But the total time to process 1000 queries is almost same for single-client and multi-clients.
> You can do a test to verify: Use single client to perform 1000 queries, calculate total time cost; then use 30 clients to perform 1000 queries, calculate total time cost; compare two total time and they should be almost equal.
> Please refer this chart:
> 1 client performs 8 queries
> 2 clients perform 8 queries
> 4 clients perform 8 queries
> total time is equal, but average time cost(per query) is different.
> ![Selection_052](https://user-images.githubusercontent.com/2282099/71972472-a7f2de80-3247-11ea-8a66-d3b6264f11ed.png)


非常感谢，图片我看懂了，我可以理解为目前milvus服务端不支持并发吗？因为图片里面多一个线程访问的时候是需要等待上一个完成。
Thank you very much, I see the picture, Can I  understand that the current milvus server does not support concurrency? Because the picture shows an additional thread access time is required to wait for the completion of the previous.

**Comment by tianyunperfect** [comment]
> What type of index you are building vectors with? What is the TOPK of your each query?

hi，My Index is IVF_SQ8

**Comment by yhmo** [comment]
So far, milvus doesn't support parallel query internal. Because vector query is very CPU-intensive, each query use many threads to compute, so process multiple queries at the same time will lead to cpu resource contest. 
But you still can use multi-clients to do different things concurrently. For example, one client inserts vector, the other client performs query.

**Comment by tianyunperfect** [comment]
OK，thanks ，Do you have a docker cluster deployment solution? I'm cannot find on the website: milvus.io

**Comment by yhmo** [comment]
We do have an experimental sharding solution for milvus. Please refer the README.md under this folder: https://github.com/milvus-io/milvus/tree/master/shards

**Comment by yhmo** [comment]
Question has been answered. Close this issue.
