### ISSUE TITLE
Accuracy value of dataset: <glove-200-ip> using CPU-version is unstable

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#958]
**Describe the bug**
![Screenshot_2020-01-09 Awesome-pyecharts(2)](https://user-images.githubusercontent.com/56623710/72032865-a408a000-32cb-11ea-8af6-b42d7a6cdefe.png)
![Screenshot_2020-01-09 Awesome-pyecharts(1)](https://user-images.githubusercontent.com/56623710/72032872-a5d26380-32cb-11ea-8867-1c1cecaa4eb2.png)
![Screenshot_2020-01-09 Awesome-pyecharts](https://user-images.githubusercontent.com/56623710/72032878-a965ea80-32cb-11ea-8ca3-f6e002556a58.png)

**Steps/Code to reproduce behavior**

**Expected behavior**

**Environment details**
branch: master
test_commit_id: 95be87026ab8f6aeb7cc069ae5a120715050df4e

**Screenshots**

**Additional context**

**Comment by JinHai-CN** [comment]
@del-zhenwu Still available?

**Comment by del-zhenwu** [comment]
no re-produce

**Comment by del-zhenwu** [comment]
close it
