### ISSUE TITLE
[BUG] Remove .a file in milvus/lib for docker-version

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#96]
**Describe the bug**
-rw-r--r-- 1 root root    Oct 13 05:36 libfaiss.a
-rw-r--r-- 1 root root    Oct 19 11:49 libknowhere.a
remove these files in compiled libs

**Steps/Code to reproduce behavior**
N/A

**Expected behavior**
No more files not related to milvus-libs after build

**Environment details**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Comment by youny626** [comment]
Done
