### ISSUE TITLE
Failed to load collection after trying to search an indexed collection with invalid search params

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#9600]
#### Steps/Code to reproduce:
1. deploy a Milvus cluster
2. create a collection and build index. e.g. ifv_flat: nlist 64
3. trying to search with invalid search params. e.g. 'param': {'metric_type': 'L2', 'nprobe': 64}, 'limit': 10
4. trying to create a new collection and load the new collection

#### Expected result:
loading any collections shall be successful

#### Actual results:
it failed to load any collections any more

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):
- Deployment mode(standalone or cluster): master-20211009-12b985c
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-2.0.0rc7.dev25

kubectl get pod | grep milvus-985

**Comment by xige-16** [comment]
Maybe the querynode crashed, did there be a log?
