### ISSUE TITLE
[Enhancement]: Change default consistency to bounded staleness

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#9618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Milvus designed to support multiple consistency types, including strong, bounded staleness or session consistency.

So far the default consistency level is strong, which cause very slow performance(each search takes 200ms or so)

I Suggest to change default time to wait data sync to 1s, thus under most cases search do not need to wait until data sync finish.

### Why is this needed?

Make most of the search happens faster, most of the Milvus users don't have strict requirement on data consistency and it has very little impact on recall

**Comment by DragonDriver** [comment]
https://github.com/milvus-io/pymilvus/pull/739
This pr can also help users to choose the consistency level in pymilvus api. This pr was almost complete.

**Comment by DragonDriver** [comment]
I suggest change the default consistency level to session-consistency in sdk side.
And I will implement this in the sdk side soon.
For every sdk users, they will wish to see all the data that they have already inserted.
The bounded-staleness level may not satisfy this requirements.

By the way, it's a little difficult to change the default to the bounded-staleness consistency level now.
First, it have a few conflicts with the `gracefulTime` of query nodes.
Second, we will change a lot of test cases that will be affected by the bounded-staleness.
I can imagine that many test cases depend on the strong-consistency.

**Comment by DragonDriver** [comment]
Closed. Already completed in https://github.com/milvus-io/pymilvus/pull/827.

**Comment by DragonDriver** [comment]
Already implemented. Feel free to reopen this if any discussion is required.
