### ISSUE TITLE
The NOTICE.md is not the most updated

### ISSUE THREAD

**Issue by jielinxu** [milvus-io/milvus#966]
## Report incorrect documentation

**Location of incorrect documentation**
The NOTICE.md file is out-dated.

**Describe the problems or issues found in the documentation**
Some third-partiy dependencies are not included in the file.

**Suggested fix for documentation**
Update the NOTICE.md by adding these third-party dependencies.

**Comment by cydrain** [comment]
done

**Comment by JinHai-CN** [comment]
Removed 3rd party:
- Apache Arrow

Added 3rd party:
https://github.com/nlohmann/json
libfiu
OATPP
gmock
