### ISSUE TITLE
[Feature]: Backup and restore

### ISSUE THREAD

**Issue by Jacse** [milvus-io/milvus#9685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Milvus brands itself as a clound-native, highly scalable vector database. Howver, any production-level usage of Milvus will require some sort of backup/restore ability en case of catastrophic failure. It seems this isn't supported (at least in a straight-forward way).

It would be great with either a cli-tool to do a compllete backup/restore to a live Milvus instance or a endpoint directly on Milvus to manage backups and initiate restores.

### Describe the solution you'd like.

Copied from a previous issue:

* issue a command, specify the repo location, the backup 
* ability to query for backup status.
* the backup mechanism to ensure that the files are all present and correct (not truncated or corrupted along the way).
* backup details (location, status, time taken etc) stored in a manifest somewhere. This way I can automate the whole thing to happen regularly.
* issue a command to restore a backup, specify repo configuration (location etc). Restore happens.
* ability to query for restore status, which would list percentage complete of all files to be restored and an overall indicator: RESTORING, COMPLETE, FAILED (with reason).

### Describe an alternate solution.

Commands to do full/incremental backup and restore operations through the milvusdm tool.

## Related discussions

* [Auto failover and data redundancy](https://github.com/milvus-io/milvus/issues/3535). Closed with comment "Not needed."
* [Backups](https://github.com/milvus-io/milvus/issues/4830). Closed with unclear comment "V2 has nodes with different roles"
* [One command backup/restore](https://github.com/milvus-io/milvus/issues/1127). Closed with comment stating that Milvus in v2 supports storing data to S3.

**Comment by xiaofan-luan** [comment]
Hi @Jacse, yes we do have plan to implement backup and restore for Milvus 2.0~ all the closed issues are from Milvus 1.1 branch, sorry for the confusion. 

The community is busy with stability and more prioritized functions, such as delete entities and compaction, if many users are looking forward to the backup/restore functionality,  we would probably deliver this by the end of this year.

Also, anyone interested in implementing this functionality are welcomed~
