### ISSUE TITLE
[Feature]: Add support for Auto-tuning

### ISSUE THREAD

**Issue by vamossagar12** [milvus-io/milvus#9690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

FAISS provides a way to Auto-tune the runtime parameters:

https://github.com/facebookresearch/faiss/wiki/Index-IO,-cloning-and-hyper-parameter-tuning#auto-tuning-the-runtime-parameters 

This is something which is useful when the user already knows the Ground Truth data. 

### Describe the solution you'd like.

It would be great to add this feature to the Milvus APIs. I am raising a Feature request, but if need be we would be happy to contribute on this as well.

**Comment by xiaofan-luan** [comment]
@vamossagar12 is this feature supoorted Faiss 1.6.3? We dind't support 1.7.1 yet

**Comment by vamossagar12** [comment]
@xiaofan-luan , AutoTune.h and AutoTune.cpp are already part of the FAISS library that you have added in the thirdparty libraries of Milvus:

https://github.com/milvus-io/milvus/blob/master/internal/core/src/index/thirdparty/faiss/AutoTune.cpp
https://github.com/milvus-io/milvus/blob/master/internal/core/src/index/thirdparty/faiss/AutoTune.h

So, this support can be added I believe

**Comment by vamossagar12** [comment]
hi @xiaofan-luan , can this feature be supported?

**Comment by xiaofan-luan** [comment]
Cool, Anyone interested? I will first mark this issue as hacktoberfest issue see if anyone want to make this
