### ISSUE TITLE
[Enhancement]: Milvus built bins and libs should be installed directly in the final dirs

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#9772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

We install the libs and bins into one place and then copy them into another.

```dockerfile
# in milvus/build/docker/milvus/Dockerfile
 26 COPY ./bin/ /milvus/bin/                                                                                      
 27                                                                                                               
 28 COPY ./configs/ /milvus/configs/                                                                              
 29                                                                                                               
 30 COPY ./lib/ /milvus/lib/ 
 31
 32 ENV PATH=/milvus/bin:$PATH                                                                                    
 33 ENV LD_LIBRARY_PATH=/milvus/lib:$LD_LIBRARY_PATH:/usr/lib  
```

Furthermore, we should use the system's default install lib-dir. For example, ubuntu will install libraries into `/lib` by default, while CetOS will install libraries into `/lib64` by default, **so no hardcode in compilation and installation is required**.

**Comment by yanliang567** [comment]
/assign @XuanYang-cn 
I think you would work on this enhancement, right?
