### ISSUE TITLE
 In Mishards readme, the link to Milvus installation guide is incorrect

### ISSUE THREAD

**Issue by yamasite** [milvus-io/milvus#983]
## Report incorrect documentation

**Location of incorrect documentation**
- https://github.com/milvus-io/milvus/blob/master/shards/README.md
- https://github.com/milvus-io/milvus/blob/master/shards/README_CN.md

**Describe the problems or issues found in the documentation**
The link to Milvus installation guide is incorrect.

**Suggested fix for documentation**
The installation guide should be directed to one of the following links:
- https://www.milvus.io/docs/guides/get_started/install_milvus/install_milvus.md
- https://www.milvus.io/cn/docs/guides/get_started/install_milvus/install_milvus.md

**Comment by JinHai-CN** [comment]
Fixed?

**Comment by yamasite** [comment]
Fixed
