### ISSUE TITLE
Add stdout message to log file

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#984]
**Describe the bug**
All stdout message should be logged into log file

**Steps/Code to reproduce behavior**

**Expected behavior**

**Environment details**

**Screenshots**

**Additional context**

**Comment by JinHai-CN** [comment]
Not clear description. @del-zhenwu

**Comment by JinHai-CN** [comment]
@del-zhenwu Still available?

**Comment by BossZou** [comment]
@del-zhenwu , please provide more requirements details. If no problem here, I will close this issue.

**Comment by del-zhenwu** [comment]
close it
