### ISSUE TITLE
[Enhancement]: DataNode should save binlog paths of stats-log and delta-log

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#9858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

/assign

**Comment by XuanYang-cn** [comment]
**stats binlog**:

Generated with insert-binlog, I recommended storing the binlog paths along with insert binlogs'.

When `GetInsertBinlogPaths`, the stats-binlog-path can be filtered out by path prefix:

```
xxx/stats-log/xxx/xxx/xxx
xxx/insert-log/xxx/xxx/xxx
```

**Comment by congqixia** [comment]
All part is done for this issue's features
