### ISSUE TITLE
some values can be set to 0 via rest API

### ISSUE THREAD

**Issue by liangliu** [milvus-io/milvus#987]
**Describe the bug**
cache_capacity can be set to 0
updates: some other values could be set to 0 too, like:

cache_insert_data
use_blas_threshold
gpu_search_threshold

**Steps/Code to reproduce behavior**
1, make sure response of config/gpu_resources enable = True (that means other values could be changed)
2, use config/gpu_resources API (put) to set cache_capacity = 0

**Expected behavior**
1, cache_capacity should be greater than 0 (>0), set to 0 should be failed
2, response message should return per request

**Environment details**

**Screenshots**

**Additional context**

**Comment by cydrain** [comment]
Setting these config to 0 is allowed

**Comment by liangliu** [comment]
close per dev's comments
