### ISSUE TITLE
Add Cosine similarity to MetricsType

### ISSUE THREAD

**Issue by wendilinplay** [milvus-io/milvus#994]
Hi, I found there is only IP and L2 for distance metrics, could you please add cosine similarity option?

**Comment by JinHai-CN** [comment]
Cosine similarity only care about the angle difference, but IP care about angle and magnitude difference. So if you normalize your vectors, the IP will be same as cosine similarity.

**Comment by wendilinplay** [comment]
- Yes. Nomalizing vectors is what I'm doing now. The only problem is in
   order to do benchmarking and a2a comparison with other ANN tools, I have to
   add the time of normalizing and transforming the IP distance to Cosine
   distance to the end2end speed metrics, and it doesn't look good when the
   data is big.  As a are result, Milvus is fastest to build the index, but
   slowest to return KNN cosine similarity distance because of the
   unnecessary duplicate computation before and after the Milvus querying.

**Comment by yhmo** [comment]
In my opinion, normalizing and transforming is pre-process phase, there should be a pre-process tool for such work.

**Comment by JinHai-CN** [comment]
@wendilinplay Yes, we do have a plan on preprocess module which might include normalization or 
dimension reduction. On this part, if you have some advices, please let us know.

**Comment by hnyoumfk** [comment]
Normalizing by preprocess module is a good idea, is there any plan for that feature now? And will developing cosine similarity as distance metrics cause some other performance problem?

**Comment by totalhack** [comment]
Did the normalization preprocessing idea ever get implemented? I'm also interested in using cosine similarity as I investigate Milvus. Ideally this would just be a directly supported distance measure.
