### ISSUE TITLE
[Enhancement]: Classify yaml files into different folders according to the type of chaos

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#9955]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Classify YAML files into different folders according to the type of chaos

### Why is this needed?

Because we have more and more types of chaos that need to inject.  If we still place them in one folder, it will be hard to manage.

### Anything else?

Previous
```
├── chaos_datacoord_network_partition.yaml
├── chaos_datacoord_podkill.yaml
├── chaos_datanode_container_kill.yaml
├── chaos_datanode_network_partition.yaml
├── chaos_datanode_pod_failure.yaml
├── chaos_datanode_podkill.yaml
└── testcases.yaml
```

Expectation
```
├── memory_stress
│   └── chaos_querynode_memory_stress.yaml
│   └── testcases.yaml
├── network_partition
│   ├── chaos_datacoord_network_partition.yaml
│   ├── chaos_indexcoord_network_partition.yaml
│   └── testcases.yaml
└── pod_kill
    ├── chaos_datacoord_podkill.yaml
    ├── chaos_datanode_podkill.yaml
    └── testcases.yaml

```

After changed folder structure,  Just need to change `TESTS_CONFIG_LOCATION` from `chaos_objects/` to `chaos_objects/${chaos_type}` in `constants.py`

**Comment by yanliang567** [comment]
/assign @zhuwenxing 
I think you are working on it
